### ISSUE TITLE
[FE, BE] 10-10EZ - BUG: Investigate Failed submissions due to missing dependent data

### ISSUE THREAD

**Issue by JoshingYou1** [department-of-veterans-affairs/va.gov-team#68726]
## Background
Further investigation is needed, as we continue to see these errors after we have reduced the timeframe for retries.

>we have another EZ failure with the missing Dependent data (SSN in this case) and it occurred within 14 retries (we reduced from 24 retries within the last week).
>With 14 retries, that should be a 24-25 hour turnaround from the first submission, which would indicate that the SIP fix did not resolve the issue.
>We need to determine whether the 14 retries are indeed within ~25 hours, and if so, we need to investigate this issue more to find a solution

<details>
<Summary>Original ticket background (expand to view)</Summary>

We have now seen 3 EZ submissions (1 Friday and 2 today) that have had total retry failures, all with Dependent errors that would normally be checked on the Frontend.

Friday's failure had 3 errors
Missing Required Field: Date child became your dependent
Missing Required Field: Child's date of birth
Missing Required Field: Child's SSN
This morning's failure had 1 error
Missing Required Field: Date child became your dependent
This afternoon's failure had 3 errors
Missing Required Field: Date child became your dependent
Missing Required Field: Child's date of birth
Missing Required Field: Child's SSN

</details>

## Tasks
- [ ] Determine whether the 14 retries are indeed within ~25 hours
- [ ] If so, Continue investigation on root cause of the issue
- [ ] If not, discuss with PM/Heather
- [ ] Determine how we can obtain the number of applications that are currently Saved In-Progress, and if possible, the dates of their initial submission

## Acceptance Criteria
- Investigation to confirm timeframe for retries, and root cause of the issue is complete

**Comment by JoshingYou1** [comment]
If the user utilizes the browser's back button (confirmed only on Chrome) to go back to the **Review your dependents** page, they are able to bypass the validations on required fields. Here's a screen recording of the aforementioned behavior

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmlNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42d0aeeaf35e458f19936a26d7585d5f8cf71c01/dependent_bug.mov)

When the request reaches `vets-api` the dependent is missing the required fields:
```
[{"fullName"=>{"first"=>"Jacob", "last"=>"Testerson"}, "dependentRelation"=>"Son", "attendedSchoolLastYear"=>false, "dependentEducationExpenses"=>0, "disabledBefore18"=>false, "cohabitedLastYear"=>true, "grossIncome"=>0, "netIncome"=>0, "otherIncome"=>0}, {"grossIncome"=>0, "netIncome"=>0, "otherIncome"=>0, "dependentEducationExpenses"=>0}]
```

**Comment by hdjustice** [comment]
Re-opening for further investigation

> we have another EZ failure with the missing Dependent data (SSN in this case) and it occurred within 14 retries (we reduced from 24 retries within the last week).
> With 14 retries, that should be a 24-25 hour turnaround from the first submission, which would indicate that the SIP fix did not resolve the issue.
> We need to determine whether the 14 retries are indeed within ~25 hours, and if so, we need to investigate this issue more to find a solution.
