### ISSUE TITLE
527 FORM DEACTIVATION: QuickSubmit Mockups and email copy

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68731]
## Issue Description
**User Stories:**
As a user attempting to apply for Pension benefits online,
I need to know what my options are when choosing to submit via PDF,
so that I can decide whether I want to mail my PDF form or submit it electronically via their system.

As a Pension team,
we need to ensure users attempting to apply for Pension benefits online know about the "quick submit" path to upload a PDF version of their form electronically,
so that they can decide whether they want to use that to submit their claim or not.

**More Info:**
- Using "QuickSubmit" would allow a path for Veterans to still submit all-digitally. It already exists, we'd just be helping them find it. It would also allow us to frame "deactivation" as more of a "digital redirect" and give us time to build the updated online submission version of the form.
- QuickSubmit is a feature supported by a team in VBA within a product called AccessVA that requires separate login.

**General Overall Tasks:**
- Update any verbiage on existing Pension deactivation designs that let veterans know that while the Pension online form is temporarily unavailable, they can still:
- Use "QuickSubmit" as a path where Veterans can still upload the PDF version of the 527 form
- Provide a link to QuickSubmit within the verbiage.

**Goals**
Any widgets and/or communications already drafted, within the form flows already identified, will be updated to communicate that while Pension form is temporarily unavailable, the veteran has the option to use QuickSubmit as an option to submit a PDF form digitally.

---
## Tasks
- [x] Update the latest copy for Pension deactivation including the QuickSubmit options. Areas to update include:
- Info alert on “How to apply” page – for auth user
- Info alert on “How to apply” page – unauth user
- Info alert for “Review” page (authenticated)
- Info alert for “Review” page (no draft claim)
- Email 

- [x] Run copy changes by Julie Strothman
- [x] Run copy changes by CAIA/Governance Team

See document attached for reference: [content.for.pension.deactivation.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk9LQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--380a1badbe63cb087a106608cdb5fa1106cc9a51/content.for.pension.deactivation.docx)

Other past Sketch files exist here:

- Review Page (authenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/JAvlVl9
- Review Page (no draft claim) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/vR1dAd3
- Widget How to apply (authenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/9lxzZLM
- Widget How to apply (unauthenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/y95jwGo

## Acceptance Criteria
- We will have drafted copy to mention the QuickSubmit option for the identified Pension pages and email template, that we will be able to request from CAIA for approval.

**Comment by mayacoforma** [comment]
**Designs**
I have shared the Sketch file that includes mockups for the "How to Apply" and "Review Pages" as well as the email: https://sketch.com/s/30db3f6b-ebfd-47af-8586-357bf4206133

**Copy**
I've created a Google Doc that contains the text for the web pages and email regarding the deactivation of the Pension form: https://docs.google.com/document/d/1XAzu3tat0yI41g4TBSgevrZ9aVEwYuMPUpAiRG4e38w/edit?usp=sharing

**Comment by mayacoforma** [comment]
@vbellissimo Waiting on feedback from CAIA and Julie S.

**Comment by mayacoforma** [comment]
@vbellissimo I'm changing the status to "blocked" as we await feedback from Julie S. and CAIA.

**Comment by vbellissimo** [comment]
@mayacoforma @aplatt-coforma I'm closing this task.

Thank you Maya for working on this. CAIA got ahead of it and finished these copy changes yesterday. As of Wednesday, November 8, 2023, the Pension form has officially been deactivated.
