### ISSUE TITLE
ARM Analytics Report

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#68737]
## Issue Description

Completing report based on analytics findings.

---

## Tasks
- [x] Create report
- [x] Review with team
- [x] Share with benefits team
- [ ] Create new ticket for analytics request - 1 pt ticket
- [ ] Upload to dedicated GitHub folder
- [ ] Create new analytics request for any open questions

---

## Acceptance Criteria
- [ ] Final document uploaded to GitHub

**Comment by jfinnerty13** [comment]
https://docs.google.com/presentation/d/1HKY9ctvmOwa7c_5X9H3HxpB1aiWjN_-N7qcvN7OvqmQ/edit?usp=sharing

**Comment by jfinnerty13** [comment]
Lots of questions - in process of getting reviewed by Zach and VA team

**Comment by jfinnerty13** [comment]
Deck updated with Zach and Alex's comments. In review with larger team - will update Monday or Tuesday next week.

**Comment by jfinnerty13** [comment]
Share-out is Nov 21st at 1230 - 130PM EST
