### ISSUE TITLE
[UX][Design] Create Final Wireframes w/ Annotations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68747]
## Background
We need to be able to handle missing appointment data consistently with the other products (Mobile, Appointments).

[Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1698766620395509?thread_ts=1698759028.519289&cid=C03CGTDLTFF)

## Tasks
- [ ] Create final mockups. (Add directly into Production sketch file. Pre-check-in: In person and Check-in pages. Just needs to be documented for the appt detail page.) 
    - Which fields does this apply to?
    - What about facility address?
- [ ] Create front end ticket for implementation 

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] Create front end ticket

**Comment by benbrasso-agile6** [comment]
@ytsaoca lemme know if you wanna discuss this one at all

**Comment by ytsaoca** [comment]
According the [thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1698961140711369), appointments and Mobile App and Kristen are still working through empty status, we will document for now what we know for sure, and then create a new one once there's a larger update.

**Comment by ytsaoca** [comment]
Documented what other teams are doing in [this sheet](https://docs.google.com/spreadsheets/d/16cVuXAsCJO3gQCufcD1BFPG4WMnNWaWMYD8dllR1wuM/edit?usp=sharing). The teams will talk more about this topic for our SME sync

**Comment by benbrasso-agile6** [comment]
I like that

**Comment by benbrasso-agile6** [comment]
@ytsaoca do you want to sync on this ticket too?

**Comment by ytsaoca** [comment]
Updated the documentation. The appointment team is going to follow mobile app's lead.  Here is [appointment's work ](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=3229-95053&mode=design&t=j7XnLcJI9ITQCM6q-0)for empty states

**Comment by benbrasso-agile6** [comment]
Thanks, I'll take a loook

**Comment by benbrasso-agile6** [comment]
I'll validate this today

**Comment by benbrasso-agile6** [comment]
Looks good Ya-ching. Let's send this back to the backlog and wait to hear when this is ready for us to work on from Appointments/Misty/Kristen. 

Also, I added a couple comments in their Figma file, FYI - https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=3229%3A95055&mode=design&t=Jzqged44hrLX1lik-1

**Comment by loripusey** [comment]
I think this is moot
