### ISSUE TITLE
Ensure that annotations and merge blocking only happens for spec files that still exist

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#68752]
## Issue Description
Currently if a test is non-functional but is deemed no longer necessary, if the test is deleted, the CI in the branch will be flagged as blocking due to that test not being "fixed". We should not be blocking based on a test that no longer exists. Currently the cleanup of deleted files is performed on branch removal. To avoid creating more BigQuery operations that could lead to rate limiting, we are going to avoid messing with the system that we know works and just add a check that ensures that a file exists before applying an annotation to it and/or blocking the PR based on a file.

---
## Tasks
- [ ] Add a check to only block a PR based on a disallowed file if the file still exists.

## Acceptance Criteria
- [ ] A branch with a deleted file is not blocked from merging based on the file.
- [ ] The existing allow list/stress test flow runs without errors.
