### ISSUE TITLE
Add Keyboard Shortcuts for Slack and GitHub to Support Best Practices Doc

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#68758]
## Description 
This ticket will house the task of updating the Support Best practices doc [()with](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices) any keyboard shortcut efficiencies. This is a product of this retro: https://easyretro.io/publicboard/gZ9iAM0ydCcTLgARY2hQdE93iUG2/31d748bc-7a25-460e-bad7-5189360efdb1

---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Add any shortcuts to the Support Best Practices Doc [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
Uploaded to Confluence, added to support best practices and Launched Enhancements Doc
