### ISSUE TITLE
Advanced Support Best Practices: Add Questions to Ask Ourselves for Each Issue Type

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#68759]
## Description 
This ticket will house the task of adding questions that we need to ask either ourselves or the VFS folks submitting tickets before we start work on a ticket. There should be questions to ask for different types of tasks (i.e. access requests vs. PR reviews)

This is a product of this retro: https://easyretro.io/publicboard/gZ9iAM0ydCcTLgARY2hQdE93iUG2/31d748bc-7a25-460e-bad7-5189360efdb1

---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Add questions we need to ask to each section of the Advanced Support Best Practices Doc here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1
- [ ] Ask what questions we need to ask and add them to each section of the Advanced Support Best Practices doc here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices+Tier+2
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Example is PR Reviews:

- Review by a peer
- 24 hour window has passed
- All checks are passing

**Comment by alyssagallion** [comment]
No longer applicable. All of our step-by-step instructions already include questions we should ask if applicable.  Closing!
