### ISSUE TITLE
BE | Military Information | Create military occupational specialties endpoint

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#68778]
## Background
We want to create an endpoint that allows the client to specify which military datasets that should be returned (occupations, service history, etc.).

## Tasks 
- [x] Create an endpoint that returns just a veteran's military occupation specialties.
- [x] Create a feature flag for this new endpoint.
- [x] Review with Richard Davis from MHV Cartography team to ensure continuity

## Acceptance Criteria 
- [x] New endpoint exists that returns just MOS data for a veteran.
- [x] Endpoint and feature flag tested in staging.

**Comment by tpharrison** [comment]
Need to merge with changes from [#15132](https://github.com/department-of-veterans-affairs/vets-api/pull/15132) before opening a new PR.  The changes are in the same set of files.

**Comment by tpharrison** [comment]
Sent email to Linda Ciston asking about BGS outage notifications.
