### ISSUE TITLE
BE | Military Information | Technical Design and Review

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#68774]
## Background 
Determine the best path forward for making military information available to VA.gov.

Options:
1. Create an endpoint that the FE call and specify the data sets it wants. 
2. Create multiple endpoints supporting specific types of military information.
3. Create endpoints for both of the above options.

> Note: Understanding [how military information](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68771) is being used across VA.gov would be ideal, but is not blocking.

## Tasks 
- [ ] Review options with Rebecca Tolmach's team.
- [ ] Review options with Adam Whitlock.

## Acceptance Criteria 
- [ ] Options have been reviewed with people above.
- [ ] Option has been chosen.

**Comment by mtcA6** [comment]
we'll cover this as we work through all of the sub tickets on #68770, tom is going to add a task to each of those stories as he works through them to make sure we're not duplicating functionality.
