### ISSUE TITLE
BE | Military Information | Create Profile Endpoint for Military Information (miniEpic)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#68770]
## Background 

We need to create an endpoint that calls VA Profile and returns the following data sets. 

1. dates of, and branches of, service (already supported)
2. units with which the Veteran or Service member served
3. deployment locations and start and end dates of deployments
4. military occupational specialties
5. training courses
6. military awards and decorations

The reason we're building our own data point, 

## Tasks 

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69973
- [ ] #68774
- [x] Once we're returning everything, iterate and narrow down things as we return
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68775
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68776
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68777
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68778
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68779
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68780
```
