### ISSUE TITLE
Provide better headers for PTSD event requests

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#68783]
## Value Statement
**_As a_** veteran who receives a request to provide a statement explaining service connected event for PTSD
**_I want to_** see header descriptions for that request that is concise, professional, and distinct
**_So that_** I can quickly distinguish it from other requests and get a sense the VA is handling requests in a serious way

---
## Background Context
- See example pain point description in reddit here: https://www.reddit.com/r/VeteransBenefits/comments/17gpxjs/upset_and_confused/

## Acceptance Criteria
- [ ]  _PTSD request headers distinguish them from other requests_
- [ ]  _Headers use syntax and punctuation consistent with VA.gov site guidelines_
- [ ]  _Request language includes recognition that providing information like this can trigger traumatic memories and provides links to resources the veteran might need_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- What are the most common file request types? 
- What are plain language descriptions for common file request types?
- What are plain language descriptions for certain kinds of requests that are most common?

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
