### ISSUE TITLE
Create Slack Use/Shortcut Documentation 

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#68787]
## Description 
For the team to better navigate Slack especially with the changes in layout, it might be useful to share Slack shortcuts that can be used to better refine searching for information, reminding yourself or users of information, keeping up with threads, etc. 

---

## Definition of Done
_What must be done to officially complete this task?_

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Compile Slack tips 
- [x] Share draft with team for feedback
- [x] Create internal confluence document
- [x] Add to team canvas
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
Uploaded to Confluence, added to support best practices and Launched Enhancements Doc
