### ISSUE TITLE
Document expectations for QA artifacts

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68792]
## User Story
As a VFS product manager, I want to understand how the QA Standards artifacts (ie Regression Test plan, test plan, e2e test participation, unit tests and traceability reports) align with the initiative I am bringing through the Collaboration Cycle so that I can be sure my team is prepared at Staging Review.

Assignee: @it-harrison @rferguson13 
Peer Reviewer: @briandeconinck 

## Description
Since the changes to the unit test coverage QA standard have been announced, VFS teams have been struggling to understand how Platform measures adherence to the QA Standards. VFS teams have asked if new QA artifacts need to be created for each incremental change they make (ie the work they bring through the Collaboration Cycle). Ideally, VFS teams should provide testing artifacts that support the product (ie a test suite), with updates to reflect the change they are making within this iteration. They do not need to provide a full test plan for their small incremental change, however they should show updates to their product test plan that account for the change they are making to their product.

How might we better communicate our testing artifact expectations for VFS teams so that they provide clear, consistent artifacts that meet the QA standards?

## Impacted Artifacts
[QA standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) page on Platform Website

## Tasks
- [x] Propose how we should communicate this information. For example, should we just update the page with the need to know information? Should we create a new page? What about an FAQ page? What do YOU think makes the most sense for ensuring VFS teams are able to easily understand the QA artifact ask.
- [x] Share proposal (or multiple proposals) with Shira for review and feedback
- [ ] Once approved, update the Platform Website pages
- [ ] Draft a change announcement for the #vfs-change-announcements channel on Slack 
- [ ] Share with Shira for communication at ToT

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams understand what is expected of their QA artifacts for each Collaboration Cycle initiative 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison if you have direct questions in Slack or in gh tickets (or even from SR recordings) can you document them here?

**Comment by it-harrison** [comment]
This ticket will carry-over. We need more time to review and revise.

**Comment by rferguson13** [comment]
@shiragoodman https://vfs.atlassian.net/wiki/spaces/PPST/pages/2840756225/68792+Expectations+for+QA+standards

**Comment by shiragoodman** [comment]
@rferguson13 @it-harrison I provided some comments in the draft - it's looking good so far! However, I do have a few concerns, so please see my comments and make the appropriate changes. If you'd like to schedule time to discuss over Zoom, let me know and I can set something up.

**Comment by rferguson13** [comment]
@shiragoodman I responded to your comments and made some changes.

@it-harrison - My knowledge on this topic has run out. Can you add what we're looking for for each of the tests? E.g. why we're asking for them and what they need to prove.

**Comment by it-harrison** [comment]
@rferguson13 I updated the document with some more details

**Comment by shiragoodman** [comment]
Can we emphasize somewhere on the page that QA artifacts are required for Staging Review and that if we don't have the artifacts, Governance will cancel the SR.

Please and thank you!

**Comment by rferguson13** [comment]
@shiragoodman Added!

**Comment by shiragoodman** [comment]
Thanks @rferguson13 - I will take a look at this again next week after Brian has had a chance to review.

**Comment by briandeconinck** [comment]
@rferguson13 Added some comments!

**Comment by rferguson13** [comment]
@briandeconinck Thanks for the feedback! I've replied with one or two questions back. Otherwise, it's looking good!

**Comment by it-harrison** [comment]
@shiragoodman proposed change announcement:

Attention: VFS Teams

**What**: [QA Artifacts Documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) Updated
**Why**: To provide VFS teams with better guidance on QA artifacts required for Collaboration Cycle Staging Reviews

**Comment by it-harrison** [comment]
this ticket continuing into next sprint; document has been updated but we still need to publish and announce the work

**Comment by it-harrison** [comment]
change announcement: https://dsva.slack.com/archives/C03R5SBELQM/p1702055605362979
