### ISSUE TITLE
[Content] [UX] Draft email template for file a BT claim notification 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#68851]
## Tasks

Part of the research study for travel reimbursement for filing a BT claim starts with an email notification. 

[There is a standard email template for health care appts here to reference](https://dsva.slack.com/archives/C010R6AUPHT/p1698260472147129?thread_ts=1698077123.601159&cid=C010R6AUPHT).  

Using that template, create an email template to let Veteran's know that they can file a BT claim for their "visit" yesterday. Don't necessarily need to use the word "visit," but the email would need to include all in-person appts from yesterday. I'd suggest listing more than 1 appointment. 

- [ ] Sync up with Christina to determine how many appts and the dates of those appts that she's using in CodePen
- [ ] Draft email template (Google Doc, Word, Git, etc.) 
- [ ] Provide to Christina

## AC

- [ ] Email drafted
- [ ] Provided to Christina for use in CodePen

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/68851?planning-poker) with Zenhub @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@loripusey please pull into this upcoming sprint

**Comment by loripusey** [comment]
done

**Comment by benbrasso-agile6** [comment]
TY

**Comment by kellysmith1008** [comment]
Synced with Christina this morning in slack - while the dates may change (to November and December to make it more aligned with the timing of the study) I can start with these types of appointments and change the dates as needed. Placing here for this afternoon when I start the template:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHkyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e358b7fecc72bde790a9210d9ebb67663504604/image.png)

**Comment by kellysmith1008** [comment]
Starting to work on this one today. @cgednalske are the dates in the screenshot above from codepen still the correct dates you want me to use?

**Comment by kellysmith1008** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f37508e0925dfbbc0fd8d8fa731e32a4b5a8f2f/image.png)
Pasting this here so I'm using a similar format for multiple appointments as the MHV template

**Comment by benbrasso-agile6** [comment]
@cgednalske hey, look at you using that updated day/day of week structure 👍

**Comment by kellysmith1008** [comment]
Mockup ready and in unified sketch under past appointments workflow. @benbrasso-agile6 has given feedback - waiting on Christina's day to start for her feedback but I think this will be able to close before sprint review today

**Comment by benbrasso-agile6** [comment]
Looks nice, just saw the latest 👍

**Comment by loripusey** [comment]
Can we close? @benbrasso-agile6 @kellysmith1008

**Comment by kellysmith1008** [comment]
Yes ma'am - there may be 1 additional content tweak, but it's a quick fix if we decide to go that route. I'll close it now
