### ISSUE TITLE
NOD | Add home phone to contact info, and add primary phone page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#68869]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to choose my primary phone number
**_So that_** I don't have to provide a mobile number if I don't have one

## Background Context

In our Supplemental Claim form, we show both the home & mobile phone on the contact information page. Immediately after that page is a question asking if either the home of mobile phone is a primary phone number. Currently in the NOD form, we only show the mobile phone assuming that the Veteran has a mobile phone. They may already be using the same number for both the home & mobile phone, but we still want to give them a choice.

## Acceptance Criteria

- [ ] Contact page shows both home & mobile phone numbers
- [ ] A new choice page is added to allow the Veteran to choose their primary phone
- [ ] If only one phone number is defined within the Veteran's profile, do not ask for a primary phone

## Tasks
- [ ] Design available for these changes
- [ ] Add home phone to contact info page
- [ ] Add primary phone page conditionally visible if both home & mobile numbers have a valid phone number
- [ ] Use or create common shared code for the contact info and primary phone pages
- [ ] Add unit tests
- [ ] Update e2e tests

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
I've got a PR open to move the Supplemental Claim primary phone code into the shared folder, but as I started working on adding a primary phone question to NOD, I encountered a few concerns.

But some background first:

- All of the contact info page code used to live in each of our app's folders.
- NOD & HLR only required a mobile phone number
- Supplemental Claims used to require a home OR mobile phone number, but not both. 
- When the code was generalized, and moved into platform, supporting a requirement of home OR mobile became very complicated, so it was made to require BOTH home and mobile

In anticipation of adding a primary phone page to NOD, a [PR is open to move the Supplemental Claim primary phone page to the appeals shared folder](https://github.com/department-of-veterans-affairs/vets-website/pull/29234) - that's working fine, but not yet merged. The concern was noted after working on NOD:

- When adding a home phone to the contact info page, we're now locked into the requirement of having _both_ a home & mobile phone defined in their profile
- If the Veteran has an in-progress form, they won't know about the requirement until they try to submit - good thing is that the accordion chapter and page within will highlight and a message stating that the primary phone isn't defined will be visible; so maybe we need to add a redirect back to the contact info page?
- If we add a redirect, should it go the primary phone page if they do have both home & mobile numbers? Or should it go to the contact info page if the home number is missing?
- If we add a redirect, we'll need to add a feature flag so we can test and limit usage until everything is validated

With these concerns, I think we need to further investigate and discuss them before proceeding with implementation. That, and this extra work would change the work estimate.

**Comment by saderagsdale** [comment]
@Mottie moving this to the backlog.

**Comment by eileen-coforma** [comment]
@Mottie Do we need a spike ticket for this?

**Comment by Mottie** [comment]
I think we need a meeting to hash out the behavior... so maybe a ticket for that?
