### ISSUE TITLE
Pension Team Sprint 7 Plan: 11/08/2023—11/21/2023

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68864]
## Sprint 7: 11/08/2023—11/21/2023

- Outages (PTO, holiday, or unplanned): 
-- Coforma team members: Nov 7
-- Vicky: Nov 20, 21
-- Maya: Nov 20, 21

## Goal(s):
**Research/Design**

- [ ] Review what is currently captured in Google Analytics for Pension #68919
- [ ] Define research hypotheses for pain points in Pension form experience #68918
- [ ] [ Document the Pension-specific claims process](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/zh/158)

_Pension MVP relaunch design refinements_

- [ ] 527 FORM DESIGN: Prep for design / dev handoff #68988
- [ ] 527 FORM DESIGN: Review & prioritize VBA feedback #69038
- [ ] 527 FORM DESIGN: Implement high priority VBA stakeholder feedback #69040
- [ ] 527 FORM DESIGN: Review CAIA feedback #69039

**Engineering**

_Pension deactivation_

- [ ] (Todd) Potentially assist with this card: Implement CAIA changes on Pension Review Page and Widget #66663

_MVP Relaunch: Pension form MVP updates:_

- [ ] (Todd) [MVP] Step 1 Claimant/Vet Info: Unauthenticated experience, add warning message #68557
- [ ] (Todd) [MVP] Step 2 Military Info: Add new question, Service Number #68564
- [ ] (Todd) [MVP] Step 2 Military Info: Remove questions #68561
**Continuing to create more FE tasks for Todd based on new developments from open questions answered from VBA meetings**

_MVP Relaunch: Setting up logging and monitoring:_
- [ ] (Tai) Pension Log Update for DataDog Dashboard #64938 **- This _may_ rollover from Sprint 6**
- [ ] (Dan) Figure out what creates the PDFs for Pension form #68913
- [ ] (Tai) Set Sidekiq retries #69027 **- Needs refining**

_Creating an ITF:_
- [ ] (Dan) Create an ITF with current API #69022 **- Needs refining**

_Migrating to Lighthouse Benefits Intake API:_ 
- [ ] (Wayne) Migrate to Lighthouse Benefits Intake API #69023 **- Needs refining**

## Added to sprint post planning
