### ISSUE TITLE
HLR | Add home phone to contact info, and add primary phone page

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#68870]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to choose my primary phone number
**_So that_** I don't have to provide a mobile number if I don't have one

## Background Context

In our Supplemental Claim form, we show both the home & mobile phone on the contact information page. Immediately after that page is a question asking if either the home of mobile phone is a primary phone number. Currently in the NOD form, we only show the mobile phone assuming that the Veteran has a mobile phone. They may already be using the same number for both the home & mobile phone, but we still want to give them a choice.

## Acceptance Criteria

- [ ] Contact page shows both home & mobile phone numbers
- [ ] A new choice page is added to allow the Veteran to choose their primary phone
- [ ] If only one phone number is defined within the Veteran's profile, do not ask for a primary phone

## Tasks
- [ ] Design available for these changes
- [ ] Add home phone to contact info page
- [ ] Add primary phone page conditionally visible if both home & mobile numbers have a valid phone number
- [ ] Use or create common shared code for the contact info and primary phone pages
- [ ] Add unit tests
- [ ] Update e2e tests

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@eileen-coforma Will add design links, then this can move to the sprint backlog.

**Comment by Mottie** [comment]
Moving this to blocked for now... see this comment in the [NOD add home phone ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68869#issuecomment-2067260247)
