### ISSUE TITLE
PM | Profile | Editing as a Subtask / Default Send / Checkboxes | VA 508 Office Audit Request

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#68878]
## Background 

Now that we've launched the 'multi-feature' items we need to have a 508 review 

## Tasks 
- [x] submit a request for a 508 review 

## Acceptance Criteria 
- [x] we've initiated the 508 review 
- [x] 508 ticket number: "REQ19449739 - 508 group reviews and works with customer to fulfill request"
