### ISSUE TITLE
Content/copy updates

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#68881]
## Issue Description
This ticket is addressing missing copy or text, including labels
---
## Tasks
- [x] Label missing on radio buttons
- [x] "Need help?" copy has changed
- [x] App description copy (directly under h1) has changed
- [ ] UI elements should use sentence case (input labels specifically)

## Acceptance Criteria
- [ ] All tasks complete and reviewed in staging.

**Comment by cosu419** [comment]
Putting in fix to use sentence case for "Organization name" label and "Need Help?" heading.
