### ISSUE TITLE
DR | Increase unit test coverage

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#68890]
## Value Statement
**_As a_** developer
**_I want to_** improve unit test coverage for our appeals form
**_So that_** we can fulfill the new compliance requirement of 80%

## Background Context

Our stakeholders have set a new compliance goal of exceeding 80% unit test coverage in all fields, in all of our apps. The fields that need 80% coverage are: lines (of code), functions, statements and branches. Our Notice of Disagreement and Supplemental Claims apps have fulfilled this requirement in all fields, but our Higher-Level Review app is at 78.74% in functions and 77.03% in the branches fields ([ref](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report)). These values may not match test coverage when testing locally

In any case, we need to review all of the unit test coverage, in all fields, for all of our apps to ensure we meet this 80% requirement. Locally, we use the following command to generate a report.

```
yarn test:coverage-app {application-path}
```

`application-path` would be the path to the folder within vets-website, e.g. `appeals/996`

After running, it _should_ open a new browser tab in `/vets-website/coverage/index.html`

## Acceptance Criteria

- [ ] HLR unit test coverage at 80% in all fields
- [ ] NOD unit test coverage at 80% in all fields
- [ ] Supplemental Claim  unit test coverage at 80% in all fields

## Tasks
- [ ] Review test coverage for HLR
- [ ] Update HLR unit tests to increase coverage
- [ ] Review test coverage for NOD
- [ ] Update NOD unit tests to increase coverage
- [ ] Review test coverage for  SC
- [ ] Update SC unit tests to increase coverage

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
We cannot have unit tests for some components because the library will not dive into the inputs in the shadow DOM. Setting up Cypress tests is more involved and setting up E2E tests puts us at a disadvantage in terms of efficiency.

Action item: bring up with platform and enablement team.

**Comment by HeatherWidmont** [comment]
Above 90% across the board, but Robin has only worked on HLR & hasn't touched NOD or Supplemental Claims yet. @Mottie is focused on the test plan spreadsheet that Sade put together since that takes priority

**Comment by Mottie** [comment]
I've updated this ticket to only target our HLR form. Since this work took 6 PR to get the code up to desired levels, I think we should split out SC & NOD into separate tickets.

**Comment by saderagsdale** [comment]
@Mottie If you make the tickets I can add them to refinement.
