### ISSUE TITLE
Create Database Retention Policy for Vets API

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#68907]
Backups of Vets API's production database should be retained for a long enough period that recovery can be made. [A recent request for data](https://dsva.slack.com/archives/CBU0KDSB1/p1698856776404149?thread_ts=1698844302.580919&cid=CBU0KDSB1) dating 28 months back prompted our discussion on this topic. Our current data retention [is 7 daily RDS snapshots](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-vets-api/blob/main/main.tf#L214).

After discussing with Platform Reliability, [Platform Security](https://dsva.slack.com/archives/C01CJV0L9PS/p1698861978639809) and Bill Chapman, the following rolling backup schedule was decided:

- 7 daily backups
- 5 weekly backups
- 12 monthly backups
- 5 yearly backups

This would mean we would have at most 29 backups existing simultaneously. [Amazon Backups](https://docs.aws.amazon.com/aws-backup/latest/devguide/about-backup-plans.html) should fit this use case well as it provides space-saving incremental backups.

```[tasklist]
## Tasks
- [ ] As a stopgap, increase our current RDS snapshots from 7 to 30.
- [ ] Add, test, and apply appropriate IaC to provision desired backups
- [ ] Consider the (possible) upcoming renaming of our production database
```

```[tasklist]
## Acceptance Criteria
- [ ] Deployed environments have a working backup retention policy for Vets API's primary database (Postgres).
```
