### ISSUE TITLE
Discovery: Find a way to handle manually skipped tests that should be fixed

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#68912]
## Issue Description
We have a long standing practice on platform of skipping problematic tests to avoid problems. This has been done traditionally by applying a `.skip` in the test itself. However, with the allow list automating this process and giving control of this to platform, we want to avoid situations where teams just skip a test to "avoid fixing it".  We need to figure out a reliable method to separate tests that are newly being developed and are skipped due to not being ready yet, vs tests that are being skipped after they've been running, just to avoid fixing them.

An early idea i had, is that if a test exists on the allow list, it means it's run through CI and that at one point, it was flagged as ready to go. Tests do not get added in CI on a failure, and if they run overnight and fail they get added as disallowed, so I think a test containing ".skip" that has an existing entry on the allow list may be able to become blocking. Testing will need to be done around this.

---
## Tasks
- [ ] Think of ideas that might result in a good way to differentiate these two groups of tests
- [ ] Test the above theory and any other ideas that come up via step 1
- [ ] Document all findings, and create a ticket to implement the recommended solution, linking that document in the new ticket.

## Acceptance Criteria
- [ ] A ticket is created for a solution to teams skipping their tests to get around our QA checks.
---

**Comment by pjhill** [comment]
One possibility is to introduce the pattern of "pending" tests. Any test without a callback will be detected as a "pending" test instead of a skipped test. Engineers who want to stub out a test can follow this pattern -- 
https://mochajs.org/#pending-tests

**Comment by LindseySaari** [comment]
Working on the cypress portion of the ticket and has built out a list of the tests. Working through ideas on how to gather this list with details around the allowlist. There are many parameters to this including OCTO, ToT and trying to find the easiest barrier of entry here.

**Comment by IGallupSoCo** [comment]
[Initial design document draft for this ticket](https://vfs.atlassian.net/wiki/spaces/PRT/pages/edit-v2/3873669130?draftShareId=8aa3af77-52ca-4bda-877f-1004c4b973d8)

**Comment by IGallupSoCo** [comment]
[Published design doc with a list of the currently disabled test specs](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3873669130/Design+Document+Addressing+manually+skipped+e2e+tests)

**Comment by IGallupSoCo** [comment]
Write a ticket to:
- Create a new script along the lines of the annotate-non-isolated-apps.js file and then modify the GHA action/workflow to also use that script during CI
