### ISSUE TITLE
Review what is currently captured in Google Analytics for Pension

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68919]
## Issue Description
Team attended the Platform Analytics office hours on Tue, Oct 31

- DOMO: Analytics team confirmed that there is NO current Pension form data set up anywhere in DOMO
- Google Analytics: There IS Pension form data set up in [Google Analytics found here](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fpension~2F)

**User story**
As a new Pension team,
we need to do a deep dive into Google Analtyics,
so we can understand what kind of pertinent information we're already capturing about users visiting va.gov for Pension-related activities.

This fits into one of our research priorites: **Create a Measurement Dashboard** [found here.](https://docs.google.com/spreadsheets/d/1X2CJzIy5ZyCZRnZ9XzLRbW8H4YEE0R6IFLZAbux_X6M/edit?usp=sharing)

---
## Tasks
- [x] Jamie gain access to Google Analytics and DOMO via Platform support
- [x] Download Adswerve browser plugin: https://chrome.google.com/webstore/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom
- [x] Explore what is currently being tracked in Google Analytics: https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fpension~2F
- [x] Determine how we can use the Adswerve browser plugin to do a reverse inspection of what event triggers Google Analytics is already tracking; For example: Collapsable widgets on “more info” (ask July to clarify which widget this is)
- [ ] Identify any metrics gathered from Google Analytics that align with the list of metrics we've already identified as important for our team to track.

## Acceptance Criteria
- We will have an understanding of what kind of information is currently being tracked in Google Analytics and compare to the list of metrics we've identified as important for our team to track.

**Comment by ToddWebDev** [comment]
@lilmashpotato 
# Form: 21P-527EZ - Application for Veterans Pension

## Routes (URLs)
### Base URLs
[https:www.staging.va.gov/pension/application/527EZ](https://staging.va.gov/pension/application/527EZ)

[https:www.va.gov/pension/application/527EZ](https://va.gov/pension/application/527EZ)

Note: All of the following urls are listed with the `va.gov` base url

### Introduction
[https:www.va.gov/pension/application/527EZ/introduction](https://va.gov/pension/application/527EZ/introduction)

### Chapters and Pages
#### Applicant Information
- Applicant Information
[https:www.va.gov/pension/application/527EZ/applicant/information](https://va.gov/pension/application/527EZ/applicant/information)

#### Military History
- Service Periods
[https:www.va.gov/pension/application/527EZ/military/history](https://va.gov/pension/application/527EZ/military/history)
- General History
[https:www.va.gov/pension/application/527EZ/military/general](https://va.gov/pension/application/527EZ/military/general)
- Reserve and National Guard
[https:www.va.gov/pension/application/527EZ/military/reserve-national-guard](https://va.gov/pension/application/527EZ/military/reserve-national-guard)
- Pow Status & Severance Pay
[https:www.va.gov/pension/application/527EZ/military/pow-severance](https://va.gov/pension/application/527EZ/military/pow-severance)

#### Work History
- Disability History
[https:www.va.gov/pension/application/527EZ/disability/history](https://va.gov/pension/application/527EZ/disability/history)
- Employment History
[https:www.va.gov/pension/application/527EZ/employment/history](https://va.gov/pension/application/527EZ/employment/history)

#### Household Information
- Marriage History
[https:www.va.gov/pension/application/527EZ/household/marriage-info](https://va.gov/pension/application/527EZ/household/marriage-info)
- Current Marriage / 1st Marriage / 2nd Marriage / Etc.
[https:www.va.gov/pension/application/527EZ/household/marriages/:index](https://va.gov/pension/application/527EZ/household/marriages/:index)
- Spouse Information (Required if married)
[https:www.va.gov/pension/application/527EZ/household/spouse-info](https://va.gov/pension/application/527EZ/household/spouse-info)
- Spouse Marriage History (Required if spouse married more than once)
[https:www.va.gov/pension/application/527EZ/household/spouse-marriages/:index](https://va.gov/pension/application/527EZ/household/spouse-marriages/:index)
- Dependent Children
[https:www.va.gov/pension/application/527EZ/household/dependents](https://va.gov/pension/application/527EZ/household/dependents)
- Children Information (Required if dependents)
[https:www.va.gov/pension/application/527EZ/household/dependents/children/information/:index](https://va.gov/pension/application/527EZ/household/dependents/children/information/:index)
- Children Address (Required if dependents)
[https:www.va.gov/pension/application/527EZ/household/dependents/children/address/:index](https://va.gov/pension/application/527EZ/household/dependents/children/address/:index)

#### Financial Disclosure
- Net Worth
[https:www.va.gov/pension/application/527EZ/financial-disclosure/net-worth](https://va.gov/pension/application/527EZ/financial-disclosure/net-worth)
- Monthly Income
[https:www.va.gov/pension/application/527EZ/financial-disclosure/monthly-income](https://va.gov/pension/application/527EZ/financial-disclosure/monthly-income)
- Expected Income
[https:www.va.gov/pension/application/527EZ/financial-disclosure/expected-income](https://va.gov/pension/application/527EZ/financial-disclosure/expected-income)
- Other Expenses
[https:www.va.gov/pension/application/527EZ/financial-disclosure/other-expenses](https://va.gov/pension/application/527EZ/financial-disclosure/other-expenses)
- Spouse Net Worth (Required if married)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/net-worth/spouse](https://va.gov/pension/application/527EZ/financial-disclosure/net-worth/spouse)
- Spouse Monthly Income (Required if married)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/monthly-income/spouse](https://va.gov/pension/application/527EZ/financial-disclosure/monthly-income/spouse)
- Spouse Expected Income (Required if married)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/expected-income/spouse](https://va.gov/pension/application/527EZ/financial-disclosure/expected-income/spouse)
- Spouse Other Expenses (Required if married)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/other-expenses/spouse](https://va.gov/pension/application/527EZ/financial-disclosure/other-expenses/spouse)
- Dependents Net Worth (Required if dependents)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/net-worth/dependents/:index](https://va.gov/pension/application/527EZ/financial-disclosure/net-worth/dependents/:index)
- Dependents Monthly Income (Required if dependents)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/monthly-income/dependents/:index](https://va.gov/pension/application/527EZ/financial-disclosure/monthly-income/dependents/:index)
- Dependents Expected Income (Required if dependents)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/expected-income/dependents/:index](https://va.gov/pension/application/527EZ/financial-disclosure/expected-income/dependents/:index)
- Dependents Other Expenses (Required if dependents)
[https:www.va.gov/pension/application/527EZ/financial-disclosure/other-expenses/dependents/:index](https://va.gov/pension/application/527EZ/financial-disclosure/other-expenses/dependents/:index)

#### Additional Information
- Direct Deposit
[https:www.va.gov/pension/application/527EZ/additional-information/direct-deposit](https://va.gov/pension/application/527EZ/additional-information/direct-deposit)
- Contact Information
[https:www.va.gov/pension/application/527EZ/additional-information/contact](https://va.gov/pension/application/527EZ/additional-information/contact)
- Aid and Attendance and Housebound benefits
[https:www.va.gov/pension/application/527EZ/additional-information/aid-attendance](https://va.gov/pension/application/527EZ/additional-information/aid-attendance)
- Document Upload
[https:www.va.gov/pension/application/527EZ/documents](https://va.gov/pension/application/527EZ/documents)
- Fully Developed Claim Program
[https:www.va.gov/pension/application/527EZ/additional-information/fdc](https://va.gov/pension/application/527EZ/additional-information/fdc)

#### Review and Submit
- Review Application
[https:www.va.gov/pension/application/527EZ/review-and-submit](https://va.gov/pension/application/527EZ/review-and-submit)

**Comment by lilmashpotato** [comment]
Spoke to Jamie Stutt (Platform Analytics) and she reviewed the list of links and thought they looked good to share with the DOMO ticket - her suggestions were 

'You just need to make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit?usp=sharing) or download the [Excel file](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f). Add your list and then submit the [request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+for+%5BTeam%5D) so we can get the form added to the DOMO report. I don't think it would hurt to mention that the form is likely going thru and update and there may be a version 2 shortly

**Comment by lilmashpotato** [comment]
Info on PA&I - here is a link (For PO/Emily) to submit a ticket to PA&I:
https://paicustomerportal.vba.va.gov/

**Comment by lilmashpotato** [comment]
Nothing is being tracked currently, and we should not set up a DOMO dashboard until we relaunch, since we are deactivating the form this week.

**Comment by lilmashpotato** [comment]
re: Using Google Analytics - from Jamie Stutt from Platform Analytics:

"Time to complete application and time to complete each section of application used to be part of the regular form reports but they were removed due issues around those metrics
We'd already covered that the forms can be completed over multiple visits across days, weeks or months
Since a "User" in GA is a browser cookie, someone returning multiple times can be multiple "Users" or have some of their visits not tracked due to browser settings
You can probably see how the metric in the report might end up looking truly odd and untrustworthy to the point it was removed."

**Comment by lilmashpotato** [comment]
We've decided to hold off on creating a dashboard while the form has been taken down. We will re-engage with the team once the MVP has relaunched. This ticket has a list of links of all of the pages within the form (prior to take down)- we will need to produce this again in order to request a DOMO dashboard.
