### ISSUE TITLE
Investigate traffic to eBenefits using Google Analytics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68939]
## Issue Description
There has been some discussion with the team around including a link to eBenefits in our Find a Representative MVP, so that users can have a way to see if they have current representation.  Until we release our Representative Status Widget, there will be no way for users to obtain this information on VA.gov.

While including a link to eBenefits would open up the potential for users to see any current representation, there are UX concerns:
- eBenefits is confusing to use, has dead-ends, and doesn't always work/load as expected
- eBenefits only allows DS Logon, which VA.gov users may not have
- We are unsure if eBenefits is accessible

This ticket is to examine traffic to eBenefits, using Google Analytics, to factor into our decision on whether or not to include a link to eBenefits in our Find a Representative MVP.

---
## Tasks
- [x] Examine Google Analytics traffic from VA.gov to eBenefits
- [x] Examine Google Analytics traffic directly on eBenefits, with relation to managing representatives
- [x] Share findings with the team

## Acceptance Criteria
- [x] The team decides whether or not to include a link to eBenefits

**Comment by oddball-lindsay** [comment]
1. For the month of October, there were 53,617 unique page views to the https://www.va.gov/disability/get-help-filing-claim/ landing page and of these:
   1. 14 of users (0.03%) clicked on the eBenefits link to the search tool (https://www.ebenefits.va.gov/ebenefits/vso-search)
   2. 5 of users (0.03%) clicked on the eBenefits link to the manage rep tool (https://www.ebenefits.va.gov/ebenefits/manage/representative)
2. For the month of July (we were curious about traffic before we started) there were only 388 unique events to the manage rep tool which equates to 0.14% of the total 276,858 unique events

Takeaway: traffic to the manage rep tool on eBenefits is minimal, both from VA.gov and in eBenefits itself.  

**This data, paired ux concerns around the eBenefits experience, points to not linking to eBenefits in our Find a Representative tool.**
