### ISSUE TITLE
Review centralized content for police transparency pages on VAMC sites

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#68949]
## Description
The police transparency team is building a new centralized content page for VAMCs to add to their websites. The page will include data and definitions on VA police units at each location.

The team needs us to review their draft of the new centralized content. They're working to identify a SME for an accuracy review.

## Deliverable
This timeline is dictated by federal legislation. When we receive draft content, this work should take priority over other projects.

- By 11/17, the team will share a draft of the centralized content.
- By 12/8, we’ll share recommendations for centralized content.

## Resources
- [CAIA recommendations](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/Ec-X8t6D9ZJPgoB085oaA2gBSA4iE4S0ixgjbIlJvaiCYw?e=hDZdQV) (Word documet)
- [VAMC page design](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) (Sketch)

## Tasks
- [x] Police transparency team: Draft centralized content
- [x] AP: Move content to Word document
- [x] KF: Edit
- [x] AP: Review and update, as needed
- [x] AP: Share content recommendations with team
- [ ] AP: Update with stakeholder feedback, as needed

## Criteria
- [ ] Content recommendations have been shared with the police transparency team

**Comment by xiongjaneg** [comment]
@aprocik1 Here's the Facilities' team's current draft centralized content VA Police page as it appears in Drupal CMS
![prod cms va gov_centralized-content_vamc-system-va-police-page-content](https://github.com/department-of-veterans-affairs/va.gov-team/assets/73648238/c886e13e-52b3-4d6b-8542-13bc4add671c)

**Comment by aprocik1** [comment]
Thanks @xiongjaneg! I just want to confirm: This is the centralized content that will be pulled into each VAMC's police statistics page. It'll be paired with specific police statistics from each site. Is that correct?

**Comment by xiongjaneg** [comment]
Hi @aprocik1 Yes, the centralized content language will be standard across all VAMC police pages. The [current Sketch design](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) has the purpose and content sections coming before the statistics (filterable by facility and year) and the FAQs coming after the statistics. Please let me know if you have any other questions. Thanks!

**Comment by aprocik1** [comment]
@katherine-fung: I copied the centralized content from Drupal into this [Word document](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/Ec-X8t6D9ZJPgoB085oaA2gBSA4iE4S0ixgjbIlJvaiCYw?e=hDZdQV) for us to offer suggested edits. I also added a little more detail based on the Sketch design. And I began leaving recommendations for you to consider. Please update as you see fit. Thanks!

**Comment by katherine-fung** [comment]
Hi @aprocik1, I've updated the Word doc with my edits, and left a few questions for you and the product team: 

https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/Ec-X8t6D9ZJPgoB085oaA2gBxK6_wHXuCLOVm5p_OaZL7Q?email=Anthony.Procik%40va.gov&e=ubvtfa 

Thanks!

**Comment by aprocik1** [comment]
Thanks @katherine-fung! I made some additional edits based on the team's most updated Sketch design. Can you review [this ](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/Ec-X8t6D9ZJPgoB085oaA2gBSA4iE4S0ixgjbIlJvaiCYw?e=9CtWug)again for any outstanding questions and recommendations? Then we'll share it with the team.

**Comment by xiongjaneg** [comment]
That's awesome, thank you! I'll share with my team and follow up as needed.

**Comment by davidmpickett** [comment]
FYI - I have updated the [Centralized Content node for VA police](https://prod.cms.va.gov/centralized-content/vamc-system-va-police-page-content) with many of these copy edits. Here's a [side-by-side comparison](https://prod.cms.va.gov/node/63204/revisions/view/822129/824142/visual_inline). 

I will also be working to make sure your other requested changes get routed to the relevant parts of our systems.

**Comment by davidmpickett** [comment]
@aprocik1 @katherine-fung - Your suggestion to add "at [facility name]" to the H1 conflicts with the [IA guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/va-police-facilities-page.md) we got from @kristinoletmuskat and @mnorthuis. Not sure if there needs to be more conversation there, but for now we will stick to the IA guidance.

However, we will be using a lowercase p in all instances of VA police in the product.
cc @aklausmeier

**Comment by kristinoletmuskat** [comment]
Ooo thanks @davidmpickett , I'm gonna circle back with A and Katherine and get aligned.

We also wanted to check with @laflannery about whether we need any header changes on the page once a user has selected the dropdown, to let screenreader users know the page content has changed -- Mikki mentioned we might have done that in the past.

**Comment by davidmpickett** [comment]
@aprocik1 @katherine-fung 

I wanted to share this updated Word doc. I have accepted all the changes that have been implemented and added some content that was added or shifted during iterations. There are still some open conversations @mmiddaugh has with stakeholders, but wanted to get this back in your hands ASAP. 

[67055.CAIA.recommendations.dmp.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13551342/67055.CAIA.recommendations.dmp.docx)

@thejordanwood has also updated the [sketch file](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174).

FYI on timing - we will be taking this to Platform Midpoint review soon (async) and @xiongjaneg has scheduled our Staging Review for December 14. 

Let us know if you have any questions!

**Comment by aprocik1** [comment]
@davidmpickett, we've left some suggested edits and a question for you in the [Word document](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ESKYtD-cnh9Pg8rBf_kgYaoBmr8Mg7eMTrtKtKoGrXCDiA?e=IQyeOD). We're happy to return to this again, as needed. Thanks for keeping us updated!

**Comment by aprocik1** [comment]
Hi @davidmpickett! I know you all had your staging review last Thursday 12/14. And from your CAIA intake request, I know the goal was to publish centralized content today. Is there any additional work left for us to do on this ticket?

FYI: Our content team will be OOO from Monday 12/25 to Monday 1/1.

**Comment by davidmpickett** [comment]
Hi @aprocik1, so we ended up have a shift in plans. We did a simplified launch of police pages yesterday that only contained introduction, contact information, and FAQ. [Example](https://www.va.gov/chicago-health-care/va-police/).

In January, we will be taking the design for the data components of the page through the collab cycle (async midpoint followed by staging review). We are still working internally on some updates to the [sketch file](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) and [content doc on Sharepoint](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ESKYtD-cnh9Pg8rBf_kgYaoBmr8Mg7eMTrtKtKoGrXCDiA?e=IQyeOD). We will let you all know when they are ready for your team to review again.

**Comment by aprocik1** [comment]
Great, thanks for letting us know @davidmpickett. Congrats on the simplified launch, and looking forward to working together in the new year. We'll be on the lookout for future updates!

**Comment by davidmpickett** [comment]
@aprocik1 and @katherine-fung Happy new year! I just completed my latest round of edits to the [content doc on Sharepoint](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ESKYtD-cnh9Pg8rBf_kgYaoBmr8Mg7eMTrtKtKoGrXCDiA?e=IQyeOD) and @mmiddaugh has added some answers from stakeholders to your questions. FYI the [sketch file](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) is mostly up to date with this doc, but doesn't reflect work I did on term definitions in Additional Info components.

@xiongjaneg will be initiating a Platform Midpoint review (async) very soon. We're likely still a couple sprints away from taking this to Staging Review, so if you could review this within the next couple weeks, that would be great. Thanks!

**Comment by aprocik1** [comment]
Happy new year, @davidmpickett! Thanks for keeping us in the loop. Katherine and I reviewed the content document and left some suggested edits. Let us know if there's anything else we can support on.

**Comment by davidmpickett** [comment]
Awesome! Thank you for the support! I accepted the changes and resolved most comments. There's still a couple open questions that might lead to some changes before Staging Review, but I feel like this is mostly wrapped.

**Comment by aprocik1** [comment]
Hi @davidmpickett, can we close this ticket, or do you think you may need future content support on this page?

**Comment by davidmpickett** [comment]
We're still waiting to get data for the dynamic part of the page. It's hard to say the content is fully final until we confirm that. So I think there may be one more round of revisions in the future and should keep the ticket open. @mmiddaugh does that sounds right?

**Comment by aprocik1** [comment]
@davidmpickett, I'm going to close this ticket for now. If we need to return to this work, we can reopen it or create a new task on your intake ticket. Thanks for collaborating with us on this!
