### ISSUE TITLE
Explore possible user flows for How to apply wizards

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#6895]
## User Story or Problem Statement
How might we streamline the UX for our disability and education forms to ensure users complete the critical pre-requisite questions that help guide them to the correct form?

## Goal
- Explore possible user flows

## Objectives or Key Results this is meant to further
- no product outline for this work. TBD
---
## Tasks
- [x] Create user flow diagrams
- [ ] Review with team and incorporate additional ideas

## Acceptance Criteria
- [ ] Team agrees on option to move forward
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
2020-03-19 PW Standup
- Went thru the flows with Jen and team. We can regroup Monday morning, before we close this out. We'll put a rec on the Mural board/on this ticket and then close this ticket out then.

**Comment by andaleliz** [comment]
- meeting follow-up with additional info: https://dsva.slack.com/archives/C52CL1PKQ/p1584719236398700

**Comment by MickinSahni** [comment]
2020-03-25 PW Planning:

- Closing this out for Sprint 17. 
- Creating a follow-up ticket [for sprint 18] related to different versions/permutations of flows e.g. from Disability, deep link, content page, Education, from search, a url from a postcard. Once this is wrapped up, we'll be able to move towards implementation.
