### ISSUE TITLE
[CST] implement accessible tab designs for claims detail pages

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#68964]
## Value Statement
**_As a_** veteran who relies on voice activation software to interact with websites
**_I want to_** the tabs in the CST detail view to be semantically aligned with the visual design
**_So that_** I can actually interact with important links and tabs to navigate the right sections of the page

---
## Background Context
- As part of the broader evidence/request initiative, we need to increase the accessibility of the detail page(s) tab designs. 

## Acceptance Criteria
- [ ] _Sub-nav for "Status", "Files" and "Overview" are visually and semantically aligned to help with voice activation software legibility_
- [ ] _Sub-nav links to VA.gov design standards and best practices_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidakennedy** [comment]
Connecting the dots on this question from @jerekshoe in a [Slack thread concerning some of the accessibility annotations](https://dsva.slack.com/archives/C04KHCT3ZMY/p1699473422407219).

I’d like to tweak these [accessibility annotations](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/a/Go9z7lw) a bit:

- Keep the `ul` and `li` elements, but wrap them in the `nav`. **Reasoning**: This is how we do navigations everywhere else on the site, so I don’t want to deviate.
- The `h1` on the page that has the inner text wrapped in a span with `role="text"`: Don’t do that, just have the text in there with the utility style for the subhead. **Reasoning**: I don’t want to get in the habit of using ARIA to make specific screen readers read things a certain way. It’s not sustainable.
