### ISSUE TITLE
Add uiSchema option to hide empty review rows

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#6896]
## User Story or Problem Statement
As a front-end developer, I need to hide empty review rows on the review and submit page, so I can remove unneeded empty entries.

Example: An empty street address line 2 or 3, or an empty name suffix

![Screen Shot 2020-03-12 at 5 19 54 PM](https://user-images.githubusercontent.com/136959/76772291-a32e3780-676e-11ea-8436-8c27e68ba885.png)

## Goal

- Match new review page designs
- May improve accessibility because screenreaders will read the labels without any value and this may be confusing to some users

## Objectives or Key Results this is meant to further

- Match design
- Improve accessibility

## Tasks

- [ ] Add an optional `ui:option` to not include a review row when the value is an empty string,`undefined` or `null`
- [ ] Add unit tests

## Acceptance Criteria

- [ ] Remove empty review rows when the`ui:option` is set and the value is an empty string, `undefined` or `null`.
