### ISSUE TITLE
ToU FE: Pre-Launch

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#68970]
## Description
List of items to complete before launching ToU (see [Slack Thread](https://dsva.slack.com/archives/C053QAL4ZNZ/p1698857627423739))

## Tasks
- [x] Update copy from FINAL legal document (waiting on Tom)
- [x] Logout URL for people who don't accept ([TOU SSOe Logout](https://github.com/department-of-veterans-affairs/vets-website/pull/26525))
- [x] Cerner cookie ([PR #26697](https://github.com/department-of-veterans-affairs/vets-website/pull/26697))
  - [x]  Add error code 110 for Cerner Provisioning Failure ([PR #](https://github.com/department-of-veterans-affairs/vets-website/pull/))
- [x] Request from MHV to send their users to our login page & redirect back tot MHV afterwards ([Middle Auth PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26542))
- [x] Bug: Mobile app (Android) not redirecting mobile users who don't accept TOU
- [x] Remove Accept/Decline button from top ([PR #26525](https://github.com/department-of-veterans-affairs/vets-website/pull/26525))
- [x] Remove Breadcrumbs ([PR in content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1745))
- [x] Remove Terms of Use from VA.gov - Sign in Modal & Unified Sign in Page ([PR #26649](https://github.com/department-of-veterans-affairs/vets-website/pull/26649))
  - [x] Remove FedWarning component from VA.gov - ([PR #26691](https://github.com/department-of-veterans-affairs/vets-website/pull/26691))

**Comment by asg5704** [comment]
- [ ] Test TOU SSOe Logout (Joe)
- [ ] Feature request: Add redirect to VA Mobile App to logout from /declined page

**Comment by asg5704** [comment]
- [x] Content changes ([Figma](https://www.figma.com/file/nxW1NHF0q1EasvUGp1eh5a/Terms-of-Use---Final?type=design&node-id=1%3A364&mode=design&t=P6WAcHHA1nGjDMiP-1) and ticket created
