### ISSUE TITLE
[CST] Ensure long condition lists do not automatically obscure/conceal important information

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#68971]
## Value Statement
**_As a_** veteran who has claimed many conditions in their disability compensation claim
**_I want to_** to be able to read all my claimed conditions, but not have the list overshadow other important content on the page
**_So that_** I can still find important information and action items 

---
## Background Context
- We have a design solution for this and it can be found in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/67669

## Acceptance Criteria
- [ ] _User is able to read the full list of conditions they've claimed if they want to_
- [ ] _In the event their condition list is long, the length of the list does not automatically obscure other information on the page that is important_

## Designs and Build Notes
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/67669
## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherWidmont** [comment]
@samcoforma to get started on this after he's finished wrapping up the other 3 tickets in the code review process. @davidakennedy to DM Sam when he's finished with the a11y work for this ticket. DK is not a blocker for Sam getting started.

**Comment by davidakennedy** [comment]
I did some research and testing on the "Show full list" button and how to handle that in an accessible way. Here are some notes:

 The current design is challenging because the "Show full list" button gets removed after activating it. Because that happens, we have to send focus somewhere. Although, even if it stayed on the page, you'd still have the same challenge.
 
 I see two options here: 1. Sending focus to the paragraph at the start of the issue list. 2. Sending focus to the first letter of the first word after the button expands the text. Both of these have drawbacks.

 Drawbacks of sending focus to the paragraph at the start of the issue list:

- If a screen reader user has traversed the text of the issues, reading the ones before the button, sending them to the beginning of the paragraph after the button gets removed means they have to read text again. We're sending them backward.

 Drawbacks of sending focus to the first letter of the first word after the button expands the text:

- We'd be sending the user forward, but to a letter, or inner text, not a specific HTML node. We'd have to wrap the letter in a `<span>` tag and send the user there. It will likely be more technically challenging to implement.
- It may be more challenging for users to know where they landed because it's no a single word vs. a HTML node. Some screen readers handle this differently and the screen reader user may need to "back out" of the letter first before moving forward with the rest of the text.

## Demo for Testing

I made a quick and dirty prototype to help myself test this, and think through the drawbacks:

- [CodePen](https://codepen.io/davidakennedy/pen/PoVbwzR)
- [CodePen debug view](https://cdpn.io/pen/debug/PoVbwzR/388329d4ad6f0e09dcce4d7048623084)

## Recommendation

Of the two options here, sending focus to the paragraph at the start of the issue list is the better one. Reasoning: Even though it sends people backward potentially, it's better for forward navigation and context when landing on the claims list.

A few other accessibility notes:

- If possible, we should try to make the ellipses come after a whole word. Reasoning: If we cut off a word, it may be harder for screen reader users to know what it means. Also, ellipses aren't announced by screen readers typically.
- Ideally, I'd like for the button label to be more specific. Currently, it says "Show full list" but a list of what? Could we make it more specific? Maybe "Show full claim list"? Reasoning: Screen reader users may often tab through interactive controls only, without the context of surrounding text. So this makes it more capable to stand on its own.

cc: @skylerschain @samcoforma

**Comment by davidakennedy** [comment]
Coming back to this, following up on a conversation I had today with @samcoforma. We talked about using CSS, specifically `text-overflow: ellipsis` to make this design happen. After some further research:

- On the surface, this seems like a good solution, except that you can't control how the words are cut off. It could cut off a word in the middle vs. at the end of a whole word. This could be problematic for those with cognitive disabilities and people who use screen readers.
- This does feel like a legitimate use case of the property, but it could lead to failures of [Success Criterion 1.4.10 Reflow](https://www.w3.org/TR/WCAG/#reflow) in some cases. I don't think that would happen here because we're not requireing 2d scrolling and we have a "read more" button.
- See [Text-overflow: ellipsis considered harmful](https://yatil.net/blog/text-overflow-ellipsis-harmful)
- [The ballad of text overflow](https://www.tpgi.com/the-ballad-of-text-overflow/)

I recommended a JavaScript based approach so we could have more control over the ellipsis and so it would be more understandable to more people since we wouldn't break in the middle of a word.

**Comment by HeatherWidmont** [comment]
@samcoforma fixing a unit test that's broken, working on it today

**Comment by pmclaren19** [comment]
Talked with @jerekshoe and @skylerschain about the design of this and we are going to change it into a list instead of a large paragraph. Sounds like we will also get rid of the ellipsis. @skylerschain is going to create a new sketch design and will link the sketch to this ticket when it is ready. @samcoforma let us know if you have any questions.

**Comment by samcoforma** [comment]
@skylerschain @davidakennedy The code changes to complete this ticket are being deployed to staging now. When you have a chance, can you please review them on staging and close this ticket or provide feedback? Thanks! cc: @jerekshoe @HeatherWidmont
