### ISSUE TITLE
Spike | Burial | Can claims be retried

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68993]
## Issue Description
Determine if Burial 530 claims can be retried and determine what happens if errors occur (e.g., Veteran is notified via error messaging or email, etc.)

---
## Tasks
- [x] Determine if Burial 530 claims can be retried
- [x] Determine what happens if errors occur (e.g., Is Veteran notified, etc.)
- [x] Determine what needs to happen to make claims retry-able 

## Acceptance Criteria
- [x] Document findings
- [x] Create follow-on tickets as needed
---

**Comment by micahaspyr** [comment]
Claims are currently being retried. No further work needed on this spike
