### ISSUE TITLE
Fix No Last Name Error

### ISSUE THREAD

**Issue by evansmith** [department-of-veterans-affairs/va.gov-team#69001]
## Issue Description
Companion ticket for: https://github.com/department-of-veterans-affairs/va.gov-team/issues/68141

---
## Tasks
- [ ] Filter names with '?' contained in them.
- [ ] Confirm validation will prevent submission for the Veteran

## Acceptance Criteria
- [ ] When a '?' is entered as a first or last name, the system will prompt the Veteran to alter the field
---

**Comment by evansmith** [comment]
Closing because this is a duplicate of #69004, when creating the ticket it said it had errored which led me to creating it again.
