### ISSUE TITLE
Spike | CH 36 | Can claims be retried

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69006]
## Issue Description
Determine if Ch 36 25-8832 claims can be retried and determine what happens if errors occur (e.g., Veteran is notified via error messaging or email, etc.)

---
## Tasks
- [x] Determine if claims can be retried
- [x] Determine what happens if errors occur (e.g., Is Veteran notified, etc.)
- [x] Determine what needs to happen to make claims retry-able 

## Acceptance Criteria
- [x] Document findings
- [x] Create follow-on tickets as needed
---

**Comment by micahaspyr** [comment]
This is currently being retried so nothing more to add to this ticket and it should be considered done.  Like burials and pensions, this does not notify the Veteran if the claim has failed processing
