### ISSUE TITLE
Fix No Last Name Issue

### ISSUE THREAD

**Issue by evansmith** [department-of-veterans-affairs/va.gov-team#69004]
## Issue Description
Companion Issue to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/68141
A Veteran submitted ? as their last name, prompting an error from BIS

---
## Tasks
- [ ] Prevent submission of ? as a first or last name.
- [ ] Filter ? from first and last name.

## Acceptance Criteria
- [ ] ? is successfully removed from first and last name. 
- [ ] Validation warns the Veteran to change the form field/prevent submission to BIS.
---

**Comment by evansmith** [comment]
@tblackwe with further research, we already remove ? from the field in the normalize methods, so I think this will primarily be a front end fix.

**Comment by tblackwe** [comment]
curious how it slipped through to the backend, but thanks for following up with the change

**Comment by evansmith** [comment]
I think that since the field was populated with '?' it passed FE validation and when the backend normalized it had passed the point where validations would have picked it up.

**Comment by Midge-dev** [comment]
Taking a look!
@evansmith @tblackwe

**Comment by Midge-dev** [comment]
Update: I have a draft PR up that addresses the name validations on the front end. This form uses 2 different schemas - validations were built into only one of them so that was fixed and tested manually and confirmed working in all areas of the form that captures names.
My concern is now that these changes may be blocked from merge until we get the test coverage for entirety of the application (686c-674) up to standard set on 11/6 regarding flaky tests and coverage.

cc: @tblackwe @evansmith @sortizsh @steele-lm

**Comment by steele-lm** [comment]
@Midge-dev 686/674 do not have any open flaky tests on the unit and E2E lists, so I think we're clear!
