### ISSUE TITLE
[MVP] Set Sidekiq retries

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69027]
## Issue description
See this ticket from Thomas for reference:
- [CODE YELLOW] Submission Retries Logging #68995

**User story**
As a team managing the Pension online form,
we need to ensure we build retries into the form submissions,
so that we can detect and manage form submission fails when they happen.

## Tasks

- [ ] Update SubmitSavedClaimJob Error logging to reflect retry eg something like `CentralMail::SubmitSavedClaimJob failed, retrying...` and change level to `warn` 
- [ ] Update SubmitSavedClaimJob sidekiq_retries_exhausted to include new `error` logging eg `CentralMail::SubmitSavedClaimJob failed, exhausted retries`
- [ ] Check in with Thomas on feedback for what other forms have done

## Acceptance criteria

- [ ] Datadog error in staging showing distinct logs for retrying vs exhausted Pension/Burial submission

**Comment by mjknight50** [comment]
Here is some additional information for @TaiWilkin 

A thread discussing the appropriate length:
https://dsva.slack.com/archives/C053U7BUT27/p1697743066917679

some documentation:
https://github.com/sidekiq/sidekiq/wiki/Error-Handling#automatic-job-retry

I think the short answer is that `14` is what we want.

**Comment by vbellissimo** [comment]
Tai will be reaching out to Thomas for someone on his team to peer review it. Possibly Dakota.

**Comment by vbellissimo** [comment]
Logs exist that capture when

- a claim submission upload has **begun**
- a claim submission upload has **failed**
- a claim submission upload has **succeeded**

Sidekiq_retries_exhausted() implemented for all sidekiq jobs

Logs include claim submission ID
