### ISSUE TITLE
Research and possibly remediate happy path failures around form.treatments dates

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#69020]
Research and possibly remediate happy path failure 
- form.treatments[].startDateIsNull 
- form.treatments[].endDateIsNull

## Acceptance Criteria
- [ ] Determine root cause of errors
- One of the following
  - [ ] New ticket created to fix issue
  - [ ] PR Opened to Fix issue
  - [ ] Comments on this ticket describing why it is not fixable at this time

**Comment by tblackwe** [comment]
Missing treatment dates causing issues with primary path submissions
https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.submission_id%3A%282425786%20OR%202425790%20OR%202425798%20OR%202425954%20OR%202426316%20OR%202426424%20OR%202426603%20OR%202427767%20OR%202428591%20OR%202428642%20OR%202430393%20OR%202430395%20OR%202430663%20OR%202430674%20OR%202430676%20OR%202432881%20OR%202433113%20OR%202433115%20OR%202434416%20OR%202434420%20OR%202434425%20OR%202434436%20OR%202434441%20OR%202435518%20OR%202435526%20OR%202435537%20OR%202437602%20OR%202437637%20OR%202437680%20OR%202438724%20OR%202440191%20OR%202440216%20OR%202440237%20OR%202440949%20OR%202451685%20OR%202456337%20OR%202457720%20OR%202457818%20OR%202458446%20OR%202458592%20OR%202464889%20OR%202468621%20OR%202485951%20OR%202492786%20OR%202492804%20OR%202494371%20OR%202512520%20OR%202524834%20OR%202535780%20OR%202551381%20OR%202557973%20OR%202564595%20OR%202567520%20OR%202573752%29%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false

**Comment by freeheeling** [comment]
Reviewing the UI:
- there is **no** treatment end date field, only an option to provide a month and year when a facility was first visited for a given condition
- providing a date for when a facility was first visited (treatment start date) is optional (_not required_)
- it is possible to provide only a month or only a year, the only validation being that the first treatment date must be after the start of the earliest service period
  - however, the date validation logic is buggy in the case where a Veteran has more than one military service history (see provided screenshots)
    - if only providing a year, the value cannot be equal to the start of a Veteran's earliest service year
    - whereas the validation logic determining when an error message is returned, if only providing a month and not a year value, is unclear

<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a9f72c166aa6fd2f25bf9566f33ed1876ff67fd/Screen%20Shot%202024-02-27%20at%204.43.27%20PM.png" alt="Screen Shot 2024-02-27 at 4.43.27 PM.png" />
<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1866d85e261f4ab89ec8a1ed7e0048b19a61074/Screen%20Shot%202024-02-27%20at%205.04.46%20PM.png" alt="Screen Shot 2024-02-27 at 5.04.46 PM.png" />
<br>
<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79515009261f77d1fba67f8c82401275af973b40/Screen%20Shot%202024-02-27%20at%204.44.47%20PM.png" alt="Screen Shot 2024-02-27 at 4.44.47 PM.png" />
<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmlWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2139dd36768f0196816b6a7a7554ed1a0f7a399/Screen%20Shot%202024-02-27%20at%204.44.56%20PM.png" alt="Screen Shot 2024-02-27 at 4.44.56 PM.png" />
<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm1WQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5751a52fdcfbf41b240d9cd08eb552546fe8b7b/Screen%20Shot%202024-02-27%20at%204.45.29%20PM.png" alt="Screen Shot 2024-02-27 at 4.45.29 PM.png" />

---

Error messages referencing both treatment start date and end date are warnings and are not, I believe, indicative of submission failure. Similar to the finding in [#69018](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/69018), referencing [this Slack message](https://dsva.slack.com/archives/C8R3JS8BU/p1598452486013000?thread_ts=1598380418.010300&cid=C8R3JS8BU), only a severity of `ERROR` in a log's payload conveys that a required element is missing and therefore a submission failed processing.

**Comment by freeheeling** [comment]
**TODO:**
- document date validation in instances where more than one service periods

**Comment by freeheeling** [comment]
As is, neither date field (month/year) are required. Would there be any issues with removing the current validation that requires the treatment start date be after the start of the earliest service period, other than the fact that the condition’s treatment date might not therefore logically be service connected?

Or would it be better to fix the logic so that only the year, or month and year (not month only), are validated against the earliest service period? For example, if the earliest service period was May 1, 2000. If only the year was entered, it would have to be 2000 or later. If a month and year were selected/entered, it would have to be May 2000 or later. And, if only a month was entered, it wouldn’t be validated (e.g., selecting and saving only March would not result in an error).

**Comment by sortizsh** [comment]
blocked, needs DR ticket @sortizsh  will write one

**Comment by freeheeling** [comment]
@sortizsh Feel free to reference my just updated comment from 3/1 in determining what/how to ticket. Thanks!

**Comment by sortizsh** [comment]
Linked ticket for the https://github.com/department-of-veterans-affairs/va.gov-team/issues/77849 start/end date. Julie will discuss the multiple service dates question with Scott.

**Comment by freeheeling** [comment]
Questions answered regarding path forward. Removing blocked label and changing pipeline to In Progress. To begin addressing in subsequent sprint.

**Comment by freeheeling** [comment]
Deployed to prod. <img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--583a6ee642f9a441ffbb3e59b22a69130c0559fa/Screenshot%202024-04-16%20at%202.02.46%E2%80%AFPM.png" alt="Screenshot 2024-04-16 at 2.02.46 PM.png" />
<img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXRuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed19b1d494d09d3df275a2dff03c9b1ad8bc687e/Screenshot%202024-04-16%20at%202.01.56%E2%80%AFPM.png" alt="Screenshot 2024-04-16 at 2.01.56 PM.png" />
Moving to Done.
