### ISSUE TITLE
Spike | CH 31 | Can claims be retried

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69033]
## Issue Description
Determine if Ch 31 28-1900 claims can be retried and determine what happens if errors occur (e.g., Veteran is notified via error messaging or email, etc.)

---
## Tasks
- [x] Determine if claims can be retried
- [x] Determine what happens if errors occur (e.g., Is Veteran notified, etc.)
- [x] Determine what needs to happen to make claims retry-able 

## Acceptance Criteria
- [x] Document findings
- [x] Create follow-on tickets as needed
---

**Comment by micahaspyr** [comment]
There is a [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/14467) from Tai Wilkin that implements the retry on the dependent submit_saved_claim_job. Looking at the sentry logs, the submit_saved_claim_job (which the submit1900 job also uses for processing) is where the submit1900 job looks to have been failing and not retrying.  If the PR gets merged, it should take care of this issue.
