### ISSUE TITLE
Spike | COE | Can claims be retried

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69036]
## Issue Description
Determine if COE 26-1800 claims can be retried and determine what happens if errors occur (e.g., Veteran is notified via error messaging or email, etc.)

---
## Tasks
- [x] Determine if claims can be retried
- [x] Determine what happens if errors occur (e.g., Is Veteran notified, etc.)
- [x] Determine what needs to happen to make claims retry-able 

## Acceptance Criteria
- [x] Document findings
- [x] Create follow-on tickets as needed
---

**Comment by micahaspyr** [comment]
- Claims are not being retried as this is a synchronous api call
- I don't see where the Veteran is being notified of an issue via vets-api
- To make this retryable on the backend, we would need to make this an async job.
- Followup questions
1. @DLarson-Oddball I'm not sure if I'm understanding this correctly on the frontend, but is the coe sort of retried on the frontend when checking for the status of a COE

**Comment by micahaspyr** [comment]
This code here must be refactored to
`def submit_coe_claim
      claim = SavedClaim::CoeClaim.new(form: filtered_params[:form])

      unless claim.save
        StatsD.increment("#{stats_key}.failure")
        Raven.tags_context(team: 'vfs-ebenefits') # tag sentry logs with team name
        raise Common::Exceptions::ValidationErrors, claim
      end

      response = claim.send_to_lgy(edipi: current_user.edipi, icn: current_user.icn)

      Rails.logger.info "ClaimID=#{claim.confirmation_number} Form=#{claim.class::FORM}"
      clear_saved_form(claim.form_id)
      render json: { data: { attributes: { reference_number: response, claim: } } }
    end`
