### ISSUE TITLE
[Research] Moderate sessions for 10-10EZR MVP research study

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#69052]
## Issue Description
UX team completes tasks that happen after submitting plan to research repo through beginning synthesis. This includes conducting the sessions as well as the pre and post tasks around that.

---
## Tasks
- [x] Create Mural board from template to use, adjust for number of participants
- [x] Create Slack observer sign up canvas board
- [x] Monitor study Slack channel setup by Perigean
- [x] Conduct sessions

## Acceptance Criteria
- [x] Scheduled sessions are completed, 
- [x] Roster doc and any transcripts/recordings are downloaded (locally only!) and deleted after synthesis ticket completed
---
