### ISSUE TITLE
Prepare for NoK/EC research sessions

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#69058]
### User story

As a researcher, I want to prepare for user testing with Veterans, so that I'm ready to get the best possible insight from the sessions.

## Acceptance criteria

- Pilot sessions conducted and insights incorporated into research materials
- Research participants have been scheduled who meet all of the most important recruitment criteria as well as most of the lower-priority goals

## Questions

- Is a verbatim required as a final deliverable? or is it just an enabler for the synthesis process?

## Tasks

- [x] Reviewed a recent Cindy Merrill [prep tasks ticket](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board) for tasks/details that may be missing below
- [x] Kick off meeting with Perigean (optional but recommended)
- [x] Schedule pilot studies
- [x] Ensure staging user is working consistently
- [x] Launch observer sign-up sheet
  - [x] Schedule one team member per session for note-taking (verbatim) and observing
  - [x] leave two open slots for other stakeholders
- [x] Establish note taking docs/process
- [x] Set up mural board for observers to note observations
  - [x] Think through synthesis steps to make data collection step clearer
- [x] Conduct pilot study - 1 
- [x] Conduct pilot study - 2 (AT) 
- [x] Tighten up the CodePen prototype as a backup to staging

**Comment by jonathanjnelson** [comment]
Documenting for awareness: @radavis 

-  Please remove address line 2 and 3 for _Next of kin_ for users 10 - 17 
![Screenshot 2023-11-02 at 11 38 25 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/60caae4d-bdd3-44d5-9d87-59c0a985591b)

-  For the staging users, it looks like the “Review your personal health care contacts” link is not underlined 
![Screenshot 2023-11-06 at 12 58 22 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/b7e68f50-d4a5-4998-8a74-99107af24bda)

-  Can we enable the updated My HealtheVet landing page for these users? Currently, it triggers the "not registered at a facility message" - I would assume participants will attempt to navigate to the My HealtheVet and it might be informative to see where they where they look for info

**Comment by radavis** [comment]
@jonathanjnelson 

> Please remove address line 2 and 3

I changed line 2 to "Apt 2" per an earlier conversation, and removed line 3. Is this acceptable?

> “Review your personal health care contacts” link is not underlined

This styling issue has been addressed. Please check staging to verify.

> Can we enable the updated My HealtheVet landing page for these users?

I assume this is possible. The current conditions necessary to access `/my-health` requires that the account/user/Veteran has been associated with one or more facilities (which implies they have some form of VA health care).
