### ISSUE TITLE
Enable NoK/EC integration testing Nov 21

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#69061]
### User story

As a Cartrographers team member, I want the _______ API team to grant staging access this sprint, so that we can pick up the integration story when we're ready (#67088).

## Acceptance criteria

- Confirmed that the NoK/EC page has read access to the API in staging (note: integration testing is out of scope for this story)

## Tasks

- [x] Write-up API volume estimates
- [x] Follow-up via email
- [ ] Confirm read access to VA Profile, Health Benefit Service endpoints

**Comment by wesrowe** [comment]
Note from refinement 11/13: there may be another endpoint currently used by Profile that almost certainly has the data we need (read-only).

**Comment by LynneJohnson224** [comment]
API intake request pending approval - working to identify a POC to see how to get an update or approval. Once approved, will work with Mike Richard from VA Profile to integrate the API

**Comment by LynneJohnson224** [comment]
API intake request status updated to Scheduling

**Comment by wesrowe** [comment]
## Notes from Profile team meeting:

- We clarified that we're only releasing read-only now, targeting Feb 1 2024 (they may create a second intake request, internal disagreement on their side)
  - Edit functionality would be a fast-follow (not immediate; "tail lights in the distance")
- Use cases where editing is not relevant were mentioned and would need further discovery
  - eg, a user without VHA health care would not have a record in VES to write to)
- Health benefit data is available from a different API, but VAgov doesn't get it today
  - Barry Wilbanks mentions that they could handle orchestration to make the additional call on their side (BW estimated it would benefit us at least 0.5 sec per call for them to orchestrate, rather than making sequential calls ourselves)

Future meetings: 2-week cadence; Jeff will lead going forward (instead of Michael Richard)

TO DOs: 
- [ ] Get average and peak transactions per second expected. They thought we were 1010ez, but I think we should be working from Profile numbers

**Comment by radavis** [comment]
VA Profile team requested "volume estimates" for API traffic. (e.g. - What are the read/write rates for the 10-10EZ?)

- [ ] Average transactions per second (read)
- [ ] Average transactions per second (write)
- [ ] Peak transactions per second (read)
- [ ] Peak transactions per second (write)

Use Sentry/DataDog/Appropriate-tool to plot and report this data, forward data to VA Profile team.

**Comment by wesrowe** [comment]
closing; the unfinished AC (confirm access) is rolled into the follow-up integration story
