### ISSUE TITLE
[CST] prevent null hearing types on board appeals

### ISSUE THREAD

**Issue by jstrothman** [department-of-veterans-affairs/va.gov-team#69062]
## Issue Description

1. As a Veteran who requested a Board Appeal, I want to understand what happens next.
2. As a product owner, I want to be able to describe the text variations that may appear here, so I can ensure it makes sense in context and so I can share it with the Board 

On https://staging.va.gov/track-claims/appeals/A3827/status
Testing with [vets.gov](http://vets.gov/).[user+54@gmail.com](mailto:user+54@gmail.com) 
I see 
![hearing type null](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1080991/85e30716-e62c-4040-983b-7e032b89071f)

I think the paragraph is line 1479: https://github.com/department-of-veterans-affairs/vets-website/blob/7fbb87f7399efd7a9dd95aca4974368c5fc37fc9/src/applications/claims-status/utils/appeals-v2-helpers.jsx#L1112

---
## Tasks
- [ ] Determine if we need to prevent hearing type == "null"
- [ ] If yes, add prevention of null state
- [ ] Describe the expected hearing types that may appear in the heading: "You'll have your [x] hearing"

## Acceptance Criteria
- [ ] We'll ensure Veterans don't see "You'll have your null hearing"
- [ ] We'll be able to describe the possible variations of what Veterans see in this header and ensure they're sensible in context
