### ISSUE TITLE
Research: PR Review Data Discovery

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69069]
## Description 
This ticket will house the task of identifying what data can be pulled around PR Reviews. It will allow us to identify if we can reduce the number of PR reviews we receive, ensure that we are only receiving those that are relevant and identify what successes we have already seen (i.e. decrease in PR reviews outside of policy).

_Note: One result could be to add labels of "in policy" vs. "out of policy" to ensure folks are following our procedures._

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Identify what reporting exists already 
- [ ] Identify what reporting is possible to pull in for the future
- [ ] Document both in a Confluence research doc
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@lindsay-insco Hey Lindsay! I've put this for our next sprint to ensure you have time to close out the current work you have planned. If you complete the others, feel free to pull this into current sprint and knock it out. Thanks!

**Comment by lindsay-insco** [comment]
The new Issue Metrics GitHub Actions [here](https://github.blog/2023-07-19-metrics-for-issues-pull-requests-and-discussions/) looks to possibly help us gather the vital PR metrics we really want to collect long-term. @bmatos312 has been investigating the capabilities of the action after he and I synced on what resources exist

**Comment by lindsay-insco** [comment]
Document with investigation into existing GitHub action passed on and up for discussion regarding implementation if desired. @bmatos312 did the true discovery.
