### ISSUE TITLE
EVSS Migration - 526 Submit - re-revisit EVSS To Lighthouse form 526 transformation service

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#69080]
follow-up to #65051

on hold until stable submit526 endpoint from Lighthouse in sandbox/production

## Issue Description
- List of issues found with the debugging tool
- LH validation checks

---
## Tasks - 
- [ ] Possibly pair with Bala to submit our request to VBMS - check if he would be the right contact for testing this
- [ ] Ask LH for validation schema
- [ ] Check if sandbox is integrated with VBMS staging and do we have access
- [ ] Check if LH creates a pdf after claims submission

## Acceptance Criteria
- [ ] Successful submission using vets-api code
- [ ] Passes LH validations

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
@RakshindaAslam @aurora-a-k-a-lightning we are seeking to merge what we have so far into master, with a few items [still in play](https://dsva.slack.com/archives/C02CQP3RFFX/p1701986590863839):

1. There is a workaround for a TE-related LH bug that should be removed once the fix is deployed to sandbox and tested 
2. There is a service period/confinements bug that must be validated once LH deploys _that_ fix to sandbox

We also noticed that the `claimDate` was now missing on the LH submit and generatePDF requests, and wanted to open a dialogue in and around whether it might still be needed or not. It's known that the backup submission process often uses this claimDate with getPDF to try and recover backdated submissions from the error queue, so I would imagine that at least the new generatePDF endpoint would need it.
