### ISSUE TITLE
CH 31 | Move Submissions to Benefits Intake API

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69108]
## Issue Description
The CH31 form is currently using the depreciated CMS API to submit claims, and it needs to be migrated to the Benefits Intake API.

See the work done in [686/674 to Lighthouse API](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66905) 
[Link to PR](https://app.zenhub.com/workspaces/benefits-dependents-experience-6459139e7d64bf0015f6af13/issues/gh/department-of-veterans-affairs/vets-api/14057)

This work should leverage the newly created Benefits Intake Service 
[Link to code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/benefits_intake_service/service.rb) 
[Link to code that shows service being used](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/central_mail/submit_central_form686c_job.rb)

---
## Tasks
- [x] Create flipper for CH31 submissions to Benefits Intake API
- [x] Implement Benefits Intake API submission using existing service
- [x] Create/Update unit tests
- [ ] Create Ticket to remove flipper in future
## Acceptance Criteria
- [x] When flipper on, Validate that CH31 submission is successfully received by Benefits Intake API
- [x] When flipper off, Validate that CH31 submission is successfully received by legacy Central Mail system
- [ ] Link to flipper removal ticket provided
---

**Comment by micahaspyr** [comment]
Flipper.enable? method call not working not working on CI test but does locally.  I might be missing some sort of 'require' statement

**Comment by micahaspyr** [comment]
Verified that this works out in the wild!  Moving this to done
