### ISSUE TITLE
Burial | Move Submissions to Benefits Intake API

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69112]
## Issue Description
The Burial form is currently using the depreciated CMS API to submit claims, and it needs to be migrated to the Benefits Intake API.

See the work done in [686/674 to Lighthouse API](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66905) 
[Link to PR](https://app.zenhub.com/workspaces/benefits-dependents-experience-6459139e7d64bf0015f6af13/issues/gh/department-of-veterans-affairs/vets-api/14057)

See note on regex differences between Benefits Intake API and EMMS API: https://github.com/department-of-veterans-affairs/va.gov-team/issues/70689#issuecomment-1843447247

This work should leverage the newly created Benefits Intake Service 
[Link to code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/benefits_intake_service/service.rb) 
[Link to code that shows service being used](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/central_mail/submit_central_form686c_job.rb)

---
## Tasks
- [ ] Create flipper for Burial submissions to Benefits Intake API
- [ ] Implement Benefits Intake API submission using existing service
- [ ] Create/Update unit tests
- [ ] Create Ticket to remove flipper in future
## Acceptance Criteria
- [ ] When flipper on, Validate that Burial (21-530EZ) submission is successfully received by Benefits Intake API
- [ ] When flipper off, Validate that Burial (21-530EZ) submission is successfully received by legacy Central Mail system
- [ ] Link to flipper removal ticket provided
---

**Comment by micahaspyr** [comment]
Once VR&E ticket is merged, I'll put in a PR for this with the Flipper changes.  I think it's best to do it sequentially.  But this ticket's PR will be pretty straightforward
