### ISSUE TITLE
Copy of Implement CAIA changes on Pension Review Page and Widget 

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69116]
## Issue Description
_Stakeholders have requested some additional copy changes to the widget that will appear on the "how to apply" and form review page for the pension form deactivation. There is new copy on each page, no updated design or functionality. See Fiorella with questions. Original work on the pension widget was done in #64136 and review page in #63626._

CAIA changes are located within the Sketch files for the Review pages and Widget: 
- Review Page (authenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/JAvlVl9
- Review Page (no draft claim) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/vR1dAd3
- Widget How to apply (authenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/9lxzZLM
- Widget How to apply (unauthenticated) https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/y95jwGo

---
## Tasks
- [x] Update copy in pension "how to apply" widget
- [x] Update copy in pension "review page" widget

## Acceptance Criteria
- [ ] Copy updates appear in pension "how to apply" widget
- [ ] Copy updates appear in pension "review page" widget
- [ ] Fiorella signs off on design implementation

**Comment by steele-lm** [comment]
Unnecessary dupe. Closing.
