### ISSUE TITLE
Research: DSVA Slack Profile Audit

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69128]
## Description 
This ticket will house the task of researching the best way to audit DSVA slack profiles to ensure everyone's is updated on both Platform and VFS teams. 

---

## Definition of Done
All tasks are done below.
---

## Tasks 

- [ ] Email Slack to identify if there is a reporting structure to pull profile content
- [ ] If there is no way to pull the incomplete profiles via Slack, identify best way to perform an audit outside of manually
- [x] Create ticket for executing work
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
- Process: Shira
- Data: Curt
- Reminder: Team of Teams Update/VFS All Teams

**Comment by alyssagallion** [comment]
Research complete. @bmatos312 Can you document what you found for these steps listed above? 

 Email Slack to identify if there is a reporting structure to pull profile content
 If there is no way to pull the incomplete profiles via Slack, identify best way to perform an audit outside of manually
