### ISSUE TITLE
Update COE API Key

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69125]
## Issue Description
_Veterans are unable to submit COE claims through VA.gov. Complete background included below. An expired API key is the likely cause. The key expiration was extended to allow for full testing before updating._

> We are getting reports that there are numerous calls being made where Veterans are not able to request a COE through VA.gov. Not sure if this has made it back to you all or not. A SNOW ticket has been opened on our end and we have begun to do research on the LGY side. Is there someone on the VA.gov side that can also start to look into this to see if the issue may be on the VA.gov side? Below are the details from the SNOW ticket we received (not sure that you’ll be able to view it). Please let us know your thoughts.
> 
> https://jira.devops.va.gov/browse/LGY-1357872
> Details: Veterans are unable to submit a COE application through va.gov.  The system tells them their request cannot be submitted. VA is getting numerous calls and emails regarding not being able to request a COE.
> 
> The reason for these COE failures for Veterans was due to the expiration of the API Key between LGY and VA.gov. We were able to put a temporary fix in on our end to allow the COE applications to become successful again.
> 
> However, we have been asked to create a long term solution for this issue going forward but need your assistance to allow LGY to coordinate with VA.gov. Our Security team has asked that we create a new API Key and release it with our 24.2 release which is on November 28th, 2023. This new API Key for the VA.gov Service Account would expire 180 days from the date created. We would need VA.gov's assistance to coordinate with us to use this new API Key.
> 
> Could you please let us know who we can work with on the VA.gov side to make this happen so we can avoid future outages? Is this something that VA.gov would be able to accommodate by our 11/28/23 release? I'm including some of our technical resources in the event that you have questions on how this will work. Please let us know your thoughts.

---
## Tasks
- [ ] Track down the key in AWS that needs updating.
- [ ] Define process and test new key in staging

## Acceptance Criteria
- [ ] API is updated
- [ ] COE can be successfully submitted on VA.gov
---

**Comment by tblackwe** [comment]
Platform confirmed that we can update our own key. I believe I have located it in AWS, waiting for confirmation from COE team.

**Comment by steele-lm** [comment]
Defining the process and testing in staging before the next expiration date.

**Comment by steele-lm** [comment]
Steve Albers is working on this.

**Comment by sortizsh** [comment]
production key is expiring at the end of April. Steve has been working on this, please coordinate with him to KT
