### ISSUE TITLE
BTSSS miscellaneous team starter documentation

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#69142]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x] Create `ceremonies` folder under main `beneficiary-travel` folder
- [x] Create sprint goals shell
- [x] Create sprint review agenda shell
- [x] Create issue [template](https://github.com/department-of-veterans-affairs/va.gov-team/tree/6237dfeae86b772284ff99238e642b8c5eddf641/.github/ISSUE_TEMPLATE)(s) for team (with default beneficiary-travel label)
- [x] Create decision log template under main `beneficiary-travel` folder

## Acceptance Criteria
- [x] Initial artifacts or paths to artifacts are linked to this ticket
- [x] All tasks are complete

**Comment by laurenernest** [comment]
- The [Sprint Goals](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/ceremonies/sprint-goals.md) doc and [Sprint Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/ceremonies/sprint-review.md) doc can be found under the [Ceremonies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/beneficiary-travel/ceremonies) folder in the team's space.
- [BTSSS Team Epic Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=epic%2C+beneficiary-travel&projects=&template=btsss-epic.md&title=%5BEpic%5D) and [BTSSS Team User Story / Task Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=beneficiary-travel&projects=&template=btsss-story.md&title=) can be found in the [New Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose) template list.
- A general team/product [decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/decision-log.md) can be found on the main team folder.
