### ISSUE TITLE
[Design] Iterate on appt detail pages based on Matt feedback

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69159]
## Tasks

- [x] Iterate on appt detail pages based on Matt feedback
- [x] Show to Appointments, Kristen & Matt

## AC

- [x] Wireframes completed 
- [x] Approval from Appointments, Kristen & Matt

**Comment by benbrasso-agile6** [comment]
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/4F5BF309-978E-4255-95F9-2CBC4AABCE3D/canvas
