### ISSUE TITLE
Shadowing Research: Complete Discussion Guide 

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#69205]
## Issue Description
Team DBEX-CARBS to complete discussion guide to prepare for shadowing research. 

Unknown around feedback from Shannon
---
## Tasks
- [x] Complete discussion guide as needed 

## Acceptance Criteria
- [x] Completed discussion guide **SOMETHING HERE ABOUT SUBMITTED FOR REVIEW**

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
[Conversation Guide ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2023-11-Shadowing-Research/Conversation-guide.md)
