### ISSUE TITLE
Review navigation spouse transition page

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#69219]
## Description

To support the ability to edit a section on the review page, we need to add a transition screen that gives an alert to a veteran after they add a spouse in the review mode. 

This is part of the additional work that needs to be taken into account in adding the ability to edit information from the review and submit page. It will satisfy the development work in #67575 

Given: Veteran wants to click edit on review and submit page
When: Veteran changes marital status and adds a spouse
Then: The veteran will see a transition page notifying them there are more fields to be added and click to continue adding spouse income and employment history 

## Tasks
- [x] Create transition page
- [x] Refactor shared component to support new transition page

## Acceptance criteria

- [x] Veteran is notified they need to complete more information if marital status is changed to true while in review navigation mode.
- [x] Attempting to submit the form without the spouse income information results in an error, and a highlighted accordion

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by amponce** [comment]
@Dr-Pongo @OptionSelect PR is ready for review https://github.com/department-of-veterans-affairs/vets-website/pull/27028
