### ISSUE TITLE
Uncompressed publish to S3 - vets-website

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#69226]
## Description
Enable uncompressed publishing of the vets-website repository to S3.

## Tasks
- [ ] Modify the deployment script to support uncompressed publishing.
- [ ] Conduct tests to ensure the integrity of the uncompressed publish.
- [ ] Update project documentation accordingly.

## Acceptance Criteria
- [ ] vets-website can be published to S3 without compression.
