### ISSUE TITLE
Datasync to EFS/Create EFS - vets-website

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#69227]
## Description
Establish an Elastic File System (EFS) for DataSync with the vets-website repository.

## Tasks
- [ ] Provision the required EFS in AWS.
- [ ] Set up DataSync tasks for EFS.
- [ ] Configure appropriate security and permissions.

## Acceptance Criteria
- [ ] EFS is created and configured for use with vets-website DataSync.
