### ISSUE TITLE
Shadowing Research: Recruitment 

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#69221]
## Issue Description
This ticket is designed to house the activities required to recruit participants for the shadowing research. 

---
## Tasks
- [ ] Write the screener
- [ ] Have Shannon review the screener
- [ ] Submit request to Perigean
- [ ] Hold a kickoff meeting with Perigean

---
## Acceptance Criteria
- [ ] Perigean is able to begin the recruit **NOT MAKING A FULL RECRUIT THE AC BECAUSE IT IS A DIFFICULT ONE**

**Comment by nnicholas7** [comment]
11/8/23
- Shadowing Research Plan has been created and reviewed by Shannon.  Team 1 & 2 are working on incorporating feedback.
- Conversation Guide- Conversation guide has been created and is being reviewed by Shannon.

**Comment by evelynhilbrichdavis** [comment]
[Proposed research](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1#card-91063432) (plan, conversation guide, and screener)
