### ISSUE TITLE
Uncompressed publish to S3 - content-build

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#69223]
## Description
Implement an uncompressed publishing process for the content build to S3.

## Tasks
- [ ] Modify the deployment script to allow uncompressed publish.
- [ ] Test the uncompressed publishing process in a staging environment.
- [ ] Update documentation to reflect the new publishing process.

## Acceptance Criteria
- [ ] Content builds can be published to S3 uncompressed.
