### ISSUE TITLE
Datasync to EFS/Create EFS - content-build

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#69224]
## Description
Set up the necessary infrastructure for DataSync to EFS by creating an Elastic File System (EFS).

## Tasks
- [ ] Provision an EFS in AWS.
- [ ] Configure the EFS for DataSync.
- [ ] Ensure security and access controls are properly configured.

## Acceptance Criteria
- [ ] EFS is created and ready for DataSync with the content build.
