### ISSUE TITLE
Design | CH 36 | Update VA File Number Component

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69241]
## Issue Description
_CAIA #63707 noted that the file VA file number field is confusing, so it needs to be updated to follow design system guidance._

### Staging or Production Link
- [Staging Link](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832/introduction)

### Prototype Link
- [Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691434304975/3f0c405c820c184d21393b3bbd76324a5ee7c677?sender=u0e8ac1d6d7681bb7e1b80558)

### Test Users
- vets.gov.user+24@gmail.com
- [staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

## Reproduction steps
1. Go to the [unauthenticated form](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/claimant-information)
2. Scroll down to "Your VA file number"

## Proposed solution or next steps
Follow the design system guidelines for [VA file number](https://design.va.gov/patterns/ask-users-for/social-security-number#usage).

- Use a label like "VA file number (if known)," no red text. ~~We also suggest adding helper text to explain why it's helpful for the Veteran to provide the VA file number, even though its optional.~~
- A VA file number is how a Veteran’s claim is tracked through the compensation system and how documents and other evidence are associated with a Veteran’s file in the VA’s electronic database.

---
## Tasks
- [x] Follow the design system guidelines for [VA file number](https://design.va.gov/patterns/ask-users-for/social-security-number#usage)
- [ ] Update design to reflect suggested "VA file number if known" field name.
- [ ] Update design to include helper text.

## Acceptance Criteria
- [ ] Update #68001 with suggested copy
---

**Comment by steele-lm** [comment]
Confirmed solution with Julie P.
