### ISSUE TITLE
Complete onboarding checklist - Rebecca

### ISSUE THREAD

**Issue by smythe5** [department-of-veterans-affairs/va.gov-team#69242]
- [x] VA Customer Experience DevOps and Agile Releases (CEDAR) Onboarding (fingerprinting, background check questionnaire, etc.)

- [x] Join Slack and standups

- [x] [Complete Github onboarding checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69320) (in progress)
- [x] [Complete VSO new member checklist](https://docs.google.com/document/d/1sjW_F_wyUA0CrPEOS1mxXGcYm79npnli_ZTjekSsp9M) (in progress)

**Comment by uxrebecca** [comment]
Realized today there's another onboarding checklist (in addition to Github one and Slack Canvas I've been going through). Going to duplicate the checklist in here to track in one place since I'm getting confused with multiple lists.

**Comment by uxrebecca** [comment]
Completed!
