### ISSUE TITLE
Staging Review SSO-login

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#6925]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_

- Link to product [outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/README.md)) **COMPLETE**

- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live) **COMPLETE**

- [Access information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/accessibility-test-credentials.md) for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_  **COMPLETE**

- Link to your product test cases/test plan in TestRail with test execution logs: **SEMI-COMPLETE** [Test Cases](https://dsvavsp.testrail.io/index.php?/runs/view/241&group_by=cases:section_id&group_order=asc)
**NOTE:** We know we have not completed all of our test cases but are hoping for something along the lines of a provisional approval pending full completion to avoid delaying further. @pjhill 

- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/overview/22) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/overview/22) reports in TestRail _for QA practice area review_ **SEMI-COMPLETE** see note above.

- Link to your accessibility test cases:
 
  **Markdown: Github accessibility test cases for new UX components:**
* [Sign-in Page: Cerner users only](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/accessibility-plan-signin-page.md)
* [Modal: all first time users](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/accessibility-plan-modal.md)
* [Sign-Out Page: Cerner users only](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/accessibility-plan-sign-out.md)-  **COMPLETE**

## Meeting attendees from **requesting team**
- Product Manager (required): **Alexis James**
- DEPO product lead (required): **Steven Kovacks**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Ambika Roos, Bridget Hapner, Eric Buckley**

## Scheduling
Preferred dates or times: tbd

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by meganhkelley** [comment]
Hi @marriej ! I can schedule this for 30 minutes on 3/26 from 1:30 - 2 pm ET, or on 3/31 between 11 - 12 pm ET. Which would y'all prefer?

**Comment by marriej** [comment]
Hi @meganhkelley the 3/26 date please.

**Comment by meganhkelley** [comment]
Scheduled for 3/26 @ 1:30 pm ET

**Comment by marriej** [comment]
Hi @meganhkelley can we please reschedule our Staging Review to April 6th or 7th?

**Comment by meganhkelley** [comment]
No problem — done! Moved to 4/7

**Comment by marriej** [comment]
Hi @meganhkelley - things are shifting again any chance we could do this review on Friday 4/5? We have been asked to have things ready for Cerner by 4/7.

**Comment by meganhkelley** [comment]
Hey @marriej ! This Friday is 4/3 — we can likely make that work! Some reviewers may not be able to attend but will provide written feedback. Alternatively we can do Thursday 4/2 between 1:30 - 2:30 pm ET, which is when we have a calendar block for all reviewers. 

Keep in mind the 2 day turnaround time for our reviews — whenever this is scheduled for, we need to be able to access all artifacts (linked above) 48 hours in advance to give folks time to prep feedback. 

Let me know what y'all want to do!

**Comment by marriej** [comment]
Thanks @meganhkelley 4/3 is what we are aiming for, since we need time to be able to complete testing and get all artifacts to you on Wednesday.

**Comment by marriej** [comment]
@meganhkelley unfortunately, we have been dealing with CAG issues that have impeded our testing so all of our documentation is not in yet. Would you have a slot available for next Thursday? Also, if at all possible if y'all have time to give feedback on some of the documentation we have provided that would be helpful so we can be sure to have everything in good standing next Tuesday. Thanks for your patience as things keep moving around.

**Comment by meganhkelley** [comment]
Per Slack convo with @marriej we are keeping tomorrow's meeting on the calendar to regroup all together, and will reschedule the formal Staging Review from there as needed

**Comment by emilywaggoner** [comment]
Noting from a Slack convo:

I think the design, content, and a11y reviews should focus on the following test cases in TestRail, which look like they contain a new page, component, or copy:

### Outbound SSO Test Cases
- T1890 ID.me LOA3 VA.gov modal UX
- T1920 SSOe Down Message

### Scheduling page alert test cases
- T1910: View My VA Health and VAOS alert
- T1911: Do not view My VA Health and VAOS Alert
- T1914: Navigate to My VA Health [No SSOE session]
- T1915: Navigate to VAOS [No SSOE session]

### Standalone Sign In Page test cases
- T1916: Sign in with MHV
- T1919: Sign out of My VA Health to signed out state

**Comment by bridgethapner** [comment]
Hi there @emilywaggoner - thank you for sharing this! 

Due to the VAOS full launch being pushed back, I just realized we need to add a couple more test cases to the **Scheduling page alert test cases** section that involve a scenario where an alert box points to My VA Health and MHV (instead of VAOS). 

I will add those this afternoon and post their IDs here. cc @marriej

**Comment by marriej** [comment]
@meganhkelley @andreahewitt-odd - All links have been updated in the ticket above, please note that the following test cases (as specified by @emilywaggoner) are no longer relevant since these pages are not launching at this time:

### Scheduling page alert test cases
- T1910: View My VA Health and VAOS alert
- T1911: Do not view My VA Health and VAOS Alert
- T1914: Navigate to My VA Health [No SSOE session]
- T1915: Navigate to VAOS [No SSOE session]

**Comment by peggygannon** [comment]
@meganhkelley I have no additional content feedback for the SSO Log in staging review. @bridgethapner and I worked closely together on these screens. Content is approved by VSP.

**Comment by pjhill** [comment]
Is this an epic? I don't seem to be able to attach my QA feedback to this ticket via the epic linking mechanism.  At any rate, here is my QA feedback ticket -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/8657

I may not be able to attend the review meeting this afternoon; however, I will try to be as responsive as possible asynchronously regarding any questions or comments in the QA feedback ticket.

**Comment by meganhkelley** [comment]
Product feedback:
 
- Be sure to update your moderated feedback plan for accuracy, and we encourage you to conduct moderated production testing with more than 1 end user.
- Calculate the _number_ of users for each phase of release, and better define what you will be looking for to confirm success before moving into your next phase of incremental release (reach out to @joanneesteban to help with success metrics as needed)
- Be sure to document your definition of "login", as it looks to be crucial to your KPIs and release plan! 

Thanks!
