### ISSUE TITLE
Test form 26-1880 for VA Profile pre-fill

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#69260]
This form doesn't have a team anymore, so the Platform Product team will test it ourselves. From this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64879#issuecomment-1739929634 we need to test to make sure these fields get prefilled:
```yaml
periodsOfService: [military_information, tours_of_duty]
currentlyActiveDuty: [military_information, currently_active_duty_hash]
activeDuty: [military_information, currently_active_duty]
```
Link to the form in staging: https://staging.va.gov/find-forms/about-form-26-1880/

### Tasks
- [x] Log onto staging with a user that has service history
- [x] Start filling out the form and see if the service periods and active duty information are prefilled

### Validation
- [ ] Read comments and make sure everything looks good.

**Comment by rmtolmach** [comment]
I logged in as `vets.gov.user+54@gmail.com` and started filling out the application. On this page of the application, nothing was prefilled with the flipper on or off:
<img width="406" alt="Screenshot 2023-11-06 at 2 34 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/fa3a3be7-04ae-40a7-927c-02c945571b82">
I think this would be the section that would be prefilled with the `currently_active_duty` military info, but I could be wrong... Either way, it was not prefilled with the flipper on or off, so I'm not worried about a regression. 

On the next page of the application, however, this information WAS pre-filled with the flipper on and off:
<img width="453" alt="Screenshot 2023-11-06 at 2 55 53 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/bec795b3-34d3-4a6d-8372-650812762d27">
So that tells me that `periodsOfService: [military_information, tours_of_duty]` is working ✅

**Comment by rjohnson2011** [comment]
COE page is showing the same for me in staging env when using vets.gov.user+36@gmail.com

**Comment by rjohnson2011** [comment]
<img width="907" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72466113/17cb94e7-0587-487f-906e-adb5f40bc0c2">
User 36 pre-populated when filling out form 22-1990 https://staging.va.gov/education/apply-for-education-benefits/application/1990/military-history/service-periods

**Comment by laineymajor** [comment]
This should have been placed in our next sprint. I'm going ahead and doing so :)

**Comment by rjohnson2011** [comment]
Looks good to go! 💯
