### ISSUE TITLE
Identify Content for PagerDuty Access

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#69264]
## Info
The team has gotten a request to add content on PagerDuty to the Platform website. Currently, nothing exists, so this ticket will be used to gather requirements of _what_ needs to be added, and _how_ detailed it needs to be, as well as _who_ we'll need to work with to get this content written and prepared.

## Tasks

- [x] Map out requirements of what information on PagerDuty needs to be included on the Platform website.

-  Add Table of Contents to documentation 
-  Add requirements for granting access to a user 
-  Add step-by-step process for granting access to PagerDuty
-  Add launched item to the Launched Support Enhancements Confluence Doc

- [x] Identify team, or subject matter expert who our team will work with on creating an outline for the content.

## Acceptance Criteria:

- [x] Must have requirements documented for initial version of PagerDuty content on the platform website.
- [x] Team, or individual identified who can partner with Content team to get content drafted.
- [x] Process has been documented mapped out

## Findings:
**Potential SMEs:** Lindsey Hattamer, Alyssa Gallion, Clint Little, Lindsay Insco

## Confluence Links: 
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2434433157/Create+Maintenance+Window+in+PagerDuty
- https://vfs.atlassian.net/wiki/spaces/KB/pages/1940127903/PagerDuty+Account+Requests

**Comment by johnny-jesensky-adhoc** [comment]
Hi @EWashb, I discussed this ask with Alyssa briefly yesterday. I've added this task to this upcoming sprint to map out some of the critical requirements around the PagerDuty content, and determine exactly what we'll need for this content.

This should be a helpful exercise for me in building my understanding of the current process for creating brand new content on the platform. I am going to be mapping out all of the steps I uncover as part of this ticket. Hopefully, this is something that we can improve upon for similar requests in the future.

**Comment by EWashb** [comment]
This is great. Thanks @johnny-jesensky-adhoc

**Comment by johnny-jesensky-adhoc** [comment]
Connected with Alyssa on this on **Wednesday, November 15th**. Her team will be creating some content on getting access to PagerDuty [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838560893/Granting+Access+to+PagerDuty), and will be pulling it into next sprint - specifically, [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/70047).

Will look to confirm additional requirements with @EWashb on specifics of what else is needed on PagerDuty content, or if the following requirements on access are sufficient, (listed above in the description of the ticket).

**Comment by EWashb** [comment]
Thank you for the update. Do we plan on also getting this information to the following link:

https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools

**Comment by johnny-jesensky-adhoc** [comment]
Following up on a Slack conversation from today (11/20), I've created a ticket for the Content Team to work on to get this written, reviewed, and deployed to the Platform Website in the most appropriate location.

We are currently planning to pull that into next sprint, (Sprint 41). Ticket can be found [here](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/70262).

Will confirm with this group once the changes are live.

FYI @EWashb, @alyssagallion
