### ISSUE TITLE
Connect Optimal Workshop VFS Survey Data to DOMO

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69269]
## Description 
This ticket will house the task of connecting DOMO and Optimal Workshop so that we can view Platform Support VFS Survey data easily.

---

## Definition of Done
All of the tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Create the following DOMO cards using the data [here](https://va-gov.domo.com/datasources/c632c4e2-1130-402a-99df-1a0e2b1f570d/details): Satisfaction Score (percentage), Survey Responses (percentage for each response type, i.e. Very Satisfied) and Survey Comments (word cloud).
- [x] If you need help creating cards for the data in DOMO, you will want to reach out to Alyssa to determine if a) We can be trained via Platform Analytics Office Hours or b) We can be trained via the Platform Analytics Junior Analyst. Alyssa will reach out to Michelle when that time comes.
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
Dataset (if you need access, send a group message to Michelle Dooley and Alyssa Gallion)https://va-gov.domo.com/datasources/c632c4e2-1130-402a-99df-1a0e2b1f570d/details

---

**Comment by alyssagallion** [comment]
@jknipes asking Michelle if we get all analytics on one dashboard instead of another separate dashboard.

**Comment by jknipes** [comment]
@alyssagallion cards have been added to[separate dashboard in DOMO](https://va-gov.domo.com/page/1729270793)

**Comment by alyssagallion** [comment]
Next steps: Documentation of process for data feeding from Optimal Workshop to DOMO/where the reports live (Confluence docs).

**Comment by alyssagallion** [comment]
Final product here: https://va-gov.domo.com/page/1729270793
