### ISSUE TITLE
CH 31 | List of all Online Claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69279]
## Issue Description
_In order to understand if there are null claims, the Central Mail team needs a list of all Chapter 31 claims ever submitted online._

We can leverage [this query](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/dependents/all_claims_report.rb).

---
## Tasks
- [x] Compile a list of all Chapter 31 claims that includes:
   - [x] Claim Type
   - [x] Submission date
   - [x] VA.gov Saved Claim ID
   - [x] Veteran Participant ID
   - [x] Central Mail Submission ID
   - [x] File name for uploaded pdf (if available)
- [x] Provide to Emily Thiese

## Acceptance Criteria
- [x] List of all Chapter 31 online claims ever submitted provided to Emily Thiese
---

**Comment by tblackwe** [comment]
script written: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/nondisability/ch31_all_claims.rb

300K records, waiting to run it until later.

**Comment by micahaspyr** [comment]
All done and sent to Emily
