### ISSUE TITLE
Ch 36 | List of all Online Claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69278]
## Issue Description
_In order to understand if there are null claims, the Central Mail team needs a list of all Chapter 36 claims ever submitted online._

We can leverage [this query](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/dependents/all_claims_report.rb).

---
## Tasks
- [x] Compile a list of all Chapter 36 claims that includes:
   - [x] Claim Type
   - [x] Submission date
   - [x] VA.gov Saved Claim ID
   - [x] Veteran Participant ID
   - [x] Central Mail Submission ID
- [x] Provide to Emily Thiese

## Acceptance Criteria
- [x] List of all Chapter 36 online claims ever submitted provided to Emily Thiese
---

**Comment by tblackwe** [comment]
script added at https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/nondisability/ch36_all_claims.rb

**Comment by micahaspyr** [comment]
All done!
