### ISSUE TITLE
ITF Database Changes

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69273]
## Issue Description
Dan will pull the createdAt value from the InProgressForm table
Insert it into a new column within SavedClaim table that represents the ITF before we delete InProgressForm
This can't help retroactively, only going forward as a backup data point
NOTE: This field will only be populated for pension.

---
## Tasks
- [x] _Create migration file for new column and apply schema changes_
- [x] _Add database rollback for deletion of InProgressForm and creation of SavedClaim if any errors occur_

## Acceptance Criteria
- [x] _Successful form submissions should result in the new itf_datetime field being populated w/ the InProgressForm created_at date before the InProgressForm entry is deleted_
- [x] _Failed form submissions should result in a DB rollback where InProgressForm entry still exists and no SavedClaim entry is created_
