### ISSUE TITLE
Add Rebecca's photo to DI slide and General Orientation deck

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#69274]
Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
New team member Rebecca Ferguson began supporting Governance at the end of October 2023. We need to add her photo to our Design Intent slide and the General Orientation slide deck

## Impacted Artifacts
[Design Intent - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775973945/Design+Intent+-+During+the+Meeting) - DI slide
General Orientation slide deck in [this folder](https://drive.google.com/drive/folders/1F0dPvQk1UKqOZl0BgZmtbsQaU5GB1sC9)
- [Updated DI welcome slide](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23db8d1d252_0_248)
- [Updated General Orientation slide](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.g13a1ca42010_0_0)
- [Updated Design & Research Orientation slide](https://docs.google.com/presentation/d/1gSeffl2STubvPDH9EoB-wUE2Al73wAwsG9QPQQU6eqw/edit#slide=id.g117fcfce7fd_1_16)

## Tasks
- [x] Add Rebecca's photo to the slides where appropriate

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Rebecca's photo has been added to the Design Intent slide and General Orientation slide deck

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@allison0034 this is ready for peer review!
- [Updated DI welcome slide](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23db8d1d252_0_248)
- [Updated General Orientation slide](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.g13a1ca42010_0_0)

**Comment by briandeconinck** [comment]
Just noticed that @allison0034 wasn't tagged as an assignee on this ticket, so might have missed it on the board. Since it's after 5pm ET this will likely carry over into the next sprint.

**Comment by allison0034** [comment]
@briandeconinck can you also update the [Design Orientation slide deck](https://docs.google.com/presentation/d/1gSeffl2STubvPDH9EoB-wUE2Al73wAwsG9QPQQU6eqw/edit#slide=id.g117fcfce7fd_1_16)?

**Comment by briandeconinck** [comment]
@allison0034 Updated the [Design Orientation slide](https://docs.google.com/presentation/d/1gSeffl2STubvPDH9EoB-wUE2Al73wAwsG9QPQQU6eqw/edit#slide=id.g117fcfce7fd_1_16)!

**Comment by allison0034** [comment]
Good to close!
