### ISSUE TITLE
COE | List of all Online Claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69280]
## Issue Description
_In order to understand if there are null claims, the Central Mail team needs a list of all COE claims ever submitted online._

We can leverage [this query](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/dependents/all_claims_report.rb).

---
## Tasks
- [ ] Compile a list of all COE claims that includes:
   - [ ] Claim Type
   - [ ] Submission date
   - [ ] VA.gov Saved Claim ID
   - [ ] Veteran Participant ID
   - [ ] Central Mail Submission ID
- [ ] Provide to Emily Thiese

## Acceptance Criteria
- [ ] List of all COE online claims ever submitted provided to Emily Thiese
---

**Comment by tblackwe** [comment]
@steele-lm @emilytheis COE claims don't have have key information as part of the claim record.
I can provide Veteran name and DOB but not file number/participant ID

Is generating the list of all COE without pID useful?
