### ISSUE TITLE
Upgrade flipper and flipper-ui gems

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#69297]
### Description
In order to Update to Rails 7+, we must update Flipper. We've held back flipper-ui, because updating it broke the Flipper UI. We kept it at 0.22.0. We need to investigate why it is is breaking and come up with a solution, as this is both breaking and blocking. We need to move to AT LEAST 23.1, but should probably catch up and update to ~> 1.0.0

**Dependency info:**

Rails 7.0.8 depends on activesupport 7.0.8
flipper-active_support_cache_store is dependent on both flipper ~> 0.22. and activesupport < 7

flipper / flipper-active_support_cache_store must be updated to at least 0.23.1 to satisfy the "activesupport < 8" dependency

### Tasks
- [x] Update to 0.23.1 and fix UI issues ([First](https://github.com/department-of-veterans-affairs/vets-api/pull/14431)/[Third](https://github.com/department-of-veterans-affairs/vets-api/pull/14478) attempt + [ENV var addition](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2392))
- [x] Ideally update to ~>1.0.0 if it can be done without much headache (PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/14482))
- [x] Update Depencies blocked by flipper/flipper-ui
  - [x] rack-protection (blocked by flipper-ui < 1.0)

### Acceptance Criteria
- [x] Gem Update is applied and in Production ([PR Here](https://github.com/department-of-veterans-affairs/vets-api/pull/14431))
- [x] UI is in tact

**Comment by ryan-mcneil** [comment]
Update: 

Found that [this PR](https://github.com/flippercloud/flipper/pull/552/files#diff-814f770067c0c662d9a1aeb3f8be5b89f34d8efa33aafb72f09f885cebd327a2R49-R57) added the CSR that prevents us from retrieving our styles from https://design.va.gov/formation.min.css

Here's the [issue](https://github.com/flippercloud/flipper/issues/538) that sparked the change

Currently investigating solutions for either replacing/appending to the CSR, or just moving the stylesheet to vets-api
