### ISSUE TITLE
Collaboration Cycle for Employee Experience Team, 21-526EZ, Max CFI

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/va.gov-team#69299]
### VFS team name

Employee Experience Team

### Product name

21-526EZ

### Feature name

Max CFI

### GitHub label for product

21-526EZ

### GitHub label for feature

n/a

### Public DSVA Slack channel for VFS team

#benefits-employee-exp

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

We launched a pilot in September 2023 for one disability, tinnitus. Since then, we've conducted A/B testing and broader, exploratory research to inform the direction for this project. We have gotten signals that our intervention is working and are moving forward with the next phase of this work – improving our intervention by giving Veterans more timely and accurate information and empowering them to make informed decisions about their disability claims.

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://dvagov.sharepoint.com/:w:/s/vaabdvro/EfmEWJOyv2JGmv6KIuooApABES5611G3_SHkuIWR4JumRA?e=ezeWOW

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kicckoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C01BVF2A3V0/p1699314844998689)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] [User flow and design sketches](https://sketch.com/s/4319cad9-d81b-4b8e-8339-d4150fbd5274) Page: Design explorations (required)

  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C03C8661PAP/p1699551729496339)
- [x] Meeting date/time: **Tuesday, November 14, 2023 at 3:30PM ET**
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [X] Update this ticket with the Zoom recording
  - [Design Intent recording link](https://oddball-io.zoom.us/rec/share/usaUDAoY_M4Fb7_QnBCFqjN_e02puu89ENHEAEGSo1q-VFMicxkolh7KB1gATqCo.wC1oqXFGNB7D_Y51)
  - Passcode: `$6#7E=1i`
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [x] Link to the Sitewide CAIA Intake Request ticket below

Sitewide CAIA Intake Request Ticket - #69856 

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] Finalized [design prototype or mockup](https://codepen.io/team/a6it/live/WNmxaBP)
- [x] Specify which pages are included in the review: Start page, Yellow prototype, Purple prototype
- [x] [Research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Research-Plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Conversation-Guide.md)
 
**Content artifacts**
  
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form. 

Ticket #69856 

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
 
[IA Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701808829216/178998265b5996341a48a0b7c499292188b223fb?sender=u4cef3aa06e6e500fdad48741)

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C01BVF2A3V0/p1705072945038169) 
- [x] Meeting date/time: Friday, January 19th at 11:30am EST

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/K6KWu2MiJGIXAlZjvXxNvYpSoa85C5_KjwV5OXCP5CbZiKcDkNuiOE3zPGmlCZSM.I4D4lXftG8t9r9Ry
  - Passcode: V%PPx2r!
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below

--> https://github.com/department-of-veterans-affairs/va.gov-team/issues/81747

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
VFS TEAM RESPONSE: [Link to markdown page with staging test user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-max-cfi.md)
- [x] Staging URL
- [x] Specify which pages are included in the review        
- [x] Staging test user information         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
VFS TEAM RESPONSE: n/a
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
  
**IA artifacts**
VFS TEAM RESPONSE: n/a
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**
VFS TEAM RESPONSE:
- Our "Steps to Reproduce" are outlined in the [Link to markdown page with staging test user info](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-max-cfi.md)
- Because the [standard QA artifacts](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) are handled at the product level (e.g. 21-526EZ), we have not prepared all of them due to the small scope of this release. As described in the above link – for each condition listed at the max on the Rated Disabilities screen, we’re conditionally displaying the message "You're already at the maximum rating for this disability." If there are larger QA artifacts that would make sense to update given this change, we are happy to make those changes.
- Unit tests --> Unit test for front-end [here](https://github.com/department-of-veterans-affairs/vets-website/blob/7223facfd15a2beb191d46fa6264f5411d7dee3a/src/applications/disability-benefits/all-claims/tests/pages/ratedDisabilities.unit.spec.jsx#11) and the coverage report for the [Disability-benefits/all-claims](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report). Unit tests for back-end can be found from results of Github Action for latest [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16746) related to max-cfi shows the files relating to max-cfi / claim fast tracking have greater than 80% code coverage.
- E2E tests --> It is a minimal change in front-end behavior of the disability-benefits/all-claims application (specifically only the rated disabilities page of the 526), and its base functionality already has cypress [e2e tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/disability-benefits/all-claims/tests) present. So we believe additional e2e tests are not necessary, and the change in behavior is well tested via unit tests.

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
VFS TEAM RESPONSE: Accessibility ticket --> https://github.com/department-of-veterans-affairs/va.gov-team/issues/83441
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C01BVF2A3V0/p1716230040459079)
- [x] Meeting date/time: May 28th, 2024 at 11:30 a.m.

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Staging review meeting recording](https://oddball-io.zoom.us/rec/share/_Ru4A_ChqmuRrXuwaalF4IqDlYDl4ZZSFXeHljNAO9MnVJ5_U98cnNghzfNYpJk.EVjjyC8iEh5258H2)
  - Passcode: `h4?FF&cb`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by briandeconinck** [comment]
Just noting here that accessibility feedback has now been added to the epic and the milestone. Sorry for the delay!

**Comment by mackhowell-nava** [comment]
A list of the non-blocking follow-up issues that emerged from our staging review:

1. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83990
2. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83991
3. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83992
4. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83993
5. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83994
6. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83995
7. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83996
8. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83997
9. https://github.com/department-of-veterans-affairs/va.gov-team/issues/83998

We're planning to coordinate and hand these off the 526 team, but keeping a record of them here for now.

**Comment by kristinoletmuskat** [comment]
Hey @amylai-va and @mackhowell-nava, we're following up on some older collab cycle intakes to check whether they've launched. Did y'all end up launching this CFI change to 100% of users?

**Comment by yurenanava** [comment]
Closed as complete
