### ISSUE TITLE
DR | Move Contestable Issues Widget to Shared

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#69305]
## Value Statement
**_As a_**  Developer
**_I want to_** be refactor the contestable issues widget component
**_So that_** we can have a consistent interaction across our appeals forms and reduce future tech debt

## Background Context

- Research was completed with the assistance of GitHub codeclimate to identify potential refactoring to reduce tech debt. As a result, the goal is to bring the ratings to of F to an A - to make code more manageable.
- Contestable Issues Widget component has a Code Climate Rating of F
  - [src/applications/appeals/10182/components/ContestableIssuesWidget.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/components/ContestableIssuesWidget.jsx)
  - [src/applications/appeals/996/components/ContestableIssuesWidget.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/components/ContestableIssuesWidget.jsx)
  - [src/applications/appeals/995/components/ContestableIssuesWidget.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/components/ContestableIssuesWidget.jsx)
- The following functions will be refactored into a shared container file
  - `const handlers` in 995/996/10182
- `<div name="eligibleScrollElement" />` in 995/996/10182
- `if (onReviewPage && inReviewMode && items.length && !hasSelected) {` - in 995/996/10182 (optionally testing folder since temporary)
- ```const items = value
    .map(item => ({
      ...item.attributes,
      [SELECTED]: item[SELECTED],
    }))``` in 996/10182
- Upgrade NOD and HLR with SC's focus management

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Function moved into a new shared container file
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Identify functions to be refactored
- [x] Have access to decision reviews folder (src/applications/appeals/<AppealForm>/components) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/components/ContestableIssuesWidget.jsx)
  > 996 - Higher Lever Review (src/applications/appeals/996/components/ContestableIssuesWidget.jsx)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/components/ContestableIssuesWidget.jsx)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away and duplication in the PR is marked as fixed

**Comment by saderagsdale** [comment]
@Mottie What's the next step to validate this?

**Comment by Mottie** [comment]
I was getting @rocio-desantiago to validate and close this ticket.

**Comment by rocio-desantiago** [comment]
Validated ✅ 
Confirmed all 3 forms work as intended. 

| HLR | NOD | SC |
| ------- | ------ | ----- |
| <img width="518" alt="HLR_ContestableIssues" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/8a1ca018-70d5-4ac8-bf9c-97ca843ff195"> | <img width="518" alt="NOD_ContestableIssues" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/f69b01e3-78f5-4c26-964e-fa14f812d3cf"> | <img width="518" alt="contestable issues page" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/d5c4364f-df79-47ad-9974-2e8d5a941f07"> |

**Comment by saderagsdale** [comment]
@rocio-desantiago @Mottie get rest! You weren't supposed to respond tonight lol.
