### ISSUE TITLE
Upgrade faraday gem (and any others held back)

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#69303]
### Description
While not a dependency for Rails 7, [faraday](https://rubygems.org/gems/faraday/versions/2.7.11) is extremely behind, and we should attempt to upgrade it, and the handful of other gems being held back. We are currently using faraday 0.17.6 (last updated 11/2022), while the latest is [2.7.11](https://rubygems.org/gems/faraday/versions/2.7.11). There will be a bit of discovery and trial/error here, as we may be blocked by the [faraday_adapter_socks](https://github.com/goldeneggg/faraday_adapter_socks) gem. We will likely have to clone it

### Tasks
- [x] Figure out a solution for faraday_adapter_socks ([PR](https://github.com/department-of-veterans-affairs/vets-api/pull/14544))
- [ ] Upgrade faraday as far as it will go
  - [ ] Upgrade to 1.10.0 ([PR](https://github.com/department-of-veterans-affairs/vets-api/pull/14552))
  - [ ] Upgrade to 2.7+
- [ ] Upgrade depencies as applicable (separate PRs if possible)
  - [ ] [restforce](https://rubygems.org/gems/restforce/versions/7.0.0)
  - [ ] [oktokit](https://rubygems.org/gems/octokit/versions/8.0.0) (?), then [danger](https://rubygems.org/gems/danger/versions/9.3.2)
  - [ ] [sentry-raven](https://rubygems.org/gems/sentry-raven/versions/3.1.2)
- [ ] Test and Deploy

### Acceptance Criteria
- [ ] faraday and all related gems are upgraded and deployed to all envs.

**Comment by ryan-mcneil** [comment]
Note, Due to extra complexity, this ticket only covered the work required to update to Faraday 1.10.0. More PRs have been created to complete the remaining work: [Faraday 2.7](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/71538) and [dependencies](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/71539)
