### ISSUE TITLE
[FSR] Discovery: Current feature flag status

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#69313]
## Description
Investigate in progress form statuses. We're still seeing some users that have feature flags disabled when the flag has been live for an extended period of time. (At least longer than 60 days which is the form expiration). 

Based on some searching already it appears some users have no feature flag information stored in their `formdata`, so it's likely an issue with the `useEffect` in the main `App.jsx` that's not firing or not storing correctly. 

The initial discovery and discussion around this issue spawned additional conversations that merit some exploring. Our current form expiration is 60 days from the "updated date", so a user can theoretically work on a form indefinitely as long as they hit continue within the 60 day window. One option moving forward is setting that 60 day expiration based on the date/time the form was initially created, so we have a hard cut off for when users should no longer be engaging in legacy user flows. 

This discovery ticket should be focused on the root cause of the incorrect feature flag issue, but addressing that issue can and likely will have a ripple effect, so we should explore our options for stale forms and how we want to proceed with feature flag and form expiration in the future.

## Tasks
- [x] Attempt to recreate and identify the bug where users save in progress data is not populated with feature flags
- [ ] Determine LoE for addressing the but or fixing it outright if the complexity is low.
- [ ] Determine the number of users impacted so we can figure out how to proceed if those users are still attempting to submit
- [ ] Determine path forward for users 'stuck' in legacy experiences. 
  - Depending on the level of impact we could work up an email, or just remove the in progress form data 
- [ ] **Coordinate with UX, Design, BE, Stakeholder(s) to create an epic to address the potential 60 day expiration change**

## Acceptance criteria

- [x] Feature flag bug is identified and fixed (or a new ticket has been generated to address the issue)
- [ ] Path forward for affected user(s) has been laid out
- [x] (Optional) Epic has been created to address the 60 day expiration change

## Testing
- [ ] (Optional) Manual testing completed 

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Update time! Finally got producction terminal access so I can run queries on in progress and submitted forms. Did some research on basic rails commands for active record querying, and connected with BE for a howto/whatnottodo session. Connected with Denise to discuss the current situation and what info we need to collect so we can make informed decisions on what to do next as far as updating the expiration date for forms, and how to implement a change like that with the lowest impact.

**Comment by Dr-Pongo** [comment]
Another update! Made some notes in the engineering team folder concerning learning rails terminal for the first time, and an approach to collecting the relevant data
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/back-end/inprogress-exploration.md

**Comment by Dr-Pongo** [comment]
Closing out this ticket since we have an epic to address overarching issues surrounding save in progress and submitted form data

https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72412
