### ISSUE TITLE
[Deactivation] Build and send Pension Deactivation Email

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69310]
## Issue Description
Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1699313352419439

Used the plain text copy attached to build the deactivation email in the email creating system: [DeactivationEmailCopy.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmV0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b051c95b350c248898f04a837960d338c367b98/DeactivationEmailCopy.txt)

---
## Tasks

- [x] Build Pension deactivation email from mockups shared by Katherine Fung, attached in comments.
- [x] Use plain text copy attached here and campaign tracking URLs provided from ticket #69288
- [x] Share preview of email build with project team
- [ ] Incorporate any additional feedback from CAIA (Katherine) or OCTO (Emily) if needed
- [ ] Engineer sends Pension deactivation email after pages on va.gov have been updates (static and widgets)

## Acceptance Criteria
- Engineer will all available assets to build the Pension deactivation email in the system.
- Users in in-progress 527EZ forms receive the email

Similar ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/67849#issuecomment-1802350086

**Comment by vbellissimo** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2F0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e78e8032091be4b7998d20ad61a5d11f1d319529/Screenshot%20%28349%29.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2V0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fbe5ad7813d4d93e10be619549a3946a2c2beca/Screenshot%20%28350%29.png)

**Comment by vbellissimo** [comment]
Confirming this task was done via this Slack message: https://dsva.slack.com/archives/C05MS96P6P2/p1699555845018799?thread_ts=1699550863.258139&cid=C05MS96P6P2

Closing this ticket now.
