### ISSUE TITLE
Determine what Claims research videos need to be watched, and make follow on issues for each team member

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#69328]
## Description
The [DSVA Claims product brief](https://drive.google.com/file/d/1q_DnzDBd8cudJx7UAa8_8HznSmgikjCk/view) has a link to SharePoint [RVSR shadowing videos](https://dvagov.sharepoint.com/:w:/s/HypertensionRapidDecisionPilot/EcS-aferXkBIpjQ839LMDM4BQbhoV-JPsKkpmTPdFiUicQ?e=q65DRt), but is missing links to the below:
- VSR training videos (TK from @Ford, Shannon or @Ropp, Lesley K. )
- VSR shadowing videos (TK from @Ford, Shannon or @Ropp, Lesley K. )

For further details and ongoing discussions, refer to the appropriate [Slack thread](https://coa-solutions.slack.com/archives/C05LRBB31C4/p1699311409751549).

## Tasks
- [x] Reach out to Jen, Lesley, or Shannon to compile a list of all the required videos.
- [x] Filter the content down to the appropriate assignments for each teammate
- [x] Create individual issues for each Claims team member to track their progress in watching the identified videos.

**Comment by lropp** [comment]
VSR shadowing videos: 
https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.qwmog0ep0758

**Comment by lropp** [comment]
VSR Training videos : 

- https://dvagov.sharepoint.com/:w:/s/vaabdvro/EWv-TkeCp9tDjEEmHvO5z7QBbe9wHG6-H7a-H2xncvJOuw?e=Hd1qu6
- https://dvagov.sharepoint.com/:b:/s/vaabdvro/ER_KpRbH7edDtqc19jf-NroBbNJNykZiGHjgt6v_QIgTcQ?e=XvtYhb
-

**Comment by lropp** [comment]
I've updated the product brief with these links as well.
