### ISSUE TITLE
Make use of v3 components

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#69322]
## Issue Description
We received a suggestion in Midpoint Review to use USWDS v3 components as much as possible. Some of the components ported from facility locator are not enabled as v3. 

Generally this is as simple as adding the uswds property, but there may be some style regression issues that arise. 

---
## Tasks
- [x] VAPagination converted to v3
- [x] VAmodal converted to v3
- [x] va-alert converted to v3
- [x] va-breadcrumbs converted to v3
- [x] va-radio converted to v3
- [ ] Non-VA inputs and buttons should be VA v3 components

## Acceptance Criteria
- [x] Above components are v3 enabled VA components
