### ISSUE TITLE
Investigate integration options between Domo and Call center related to Modern Credential Adoption

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#69330]
## Issue Description
Investigate integration options between Domo and Call center data to support KPIs on dashboard: Numbers of call center support requests related to login.gov/ID.me

This will require some discovery into granularity and quality of call center support requests, and access to data/API.
• The Domo Salesforce Issues (MVP) dashboard has filters for:
o Login.gov, ID.me, DS Logon and MHV: with sub-categories of forgotten password and identity verification issues
o There are are also filters for Identity and Account Sign In: with sub-categories of navigation issues and security

Would potentially include development and process changes within call center to track call to the test segment.

---
## Tasks
- [x] Perform discovery of automated integration options between Domo and Call Center
- [x] Investigate available data related to authentication

## Acceptance Criteria
- [x] Documented integration options
- [x] Documtention of available relevant data

**Comment by sdickson-gt** [comment]
There is a callcenter dataset in Domo called: "[Output] VA 411 Product Mapping" which has the data and subcategories listed in the description.
