### ISSUE TITLE
Correct expected discrepancies between FSRFormBuilder and FSR service

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#69339]
## Issue Description
(Follow on to #69334)
The previous logger ticket will inevitably reveal discrepancies between the new and old implementations. Correct these where appropriate (some may be benign) and write specs for each discrepancy found.

---
## Tasks
- [ ] Identify discrepancies
- [ ] write tests for discrepancies
- [ ] correct discrepancies

## Acceptance Criteria
- [ ] The FormBuilder can safely replace code in the FSR service
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
