### ISSUE TITLE
Find out # of Pension claims for FY23 (Oct 1, 2022 - Sep 30, 2023)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69337]
## Issue Description
As a Pension team,
**we need to provide a volume of Pension claims for FY23 (Oct 1 2022 to Sept 30 2023),**
so we can share this number with our VBA counterparts at their request.

---
## Tasks
- [x] Reach out to Platform Analytics team to see if this information lives within Google Analytics
- [x] Review GA ourselves to investigate
- [x] Provide findings to Emily to pass on to VBA stakeholders

## Acceptance Criteria
- We will be able to provide VBA insight into the volume of Pension claims submitted for FY23 (Oct 1 2022 to Sept 30 2023)

## Findings
- Found via this GA link: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p1[…]-table.filter=527ez&explorer-table.plotKeys=%5B%5D/
- Slack thread for reference: https://dsva.slack.com/archives/C05MS96P6P2/p1699376584255329

**Comment by lilmashpotato** [comment]
Here is data that I got from Platform Analytics from GA - Note, this is total events, not a count Users who have completed the form:

[https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p1[…]-table.filter=527ez&explorer-table.plotKeys=%5B%5D/](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20221001&_u.date01=20230930&_r.drilldown=analytics.eventCategory:Transactions&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.filter=527ez&explorer-table.plotKeys=%5B%5D/)
