### ISSUE TITLE
Incorporate FSRFormBuilder class into FSR service

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#69334]
## Issue Description
Now that we have a FormBuilder class we need to integrate it into the service at large. In this early stage I don't want to do a complete change over without some assurances that the FormBuilder forms are at parody with the service forms. 
at the final stages of the user form, vha form and vba form, compare the service version to the builder version. If they are meaningfully different call a rails logger (maybe do like a diff?).

---
## Tasks
- [ ] Use FormBuilder in the FSR service
- [ ] compare FormBuilder result to service result (user form)
- [ ] compare FormBuilder result to service result (vba form)
- [ ] compare FormBuilder result to service result (vha form)

## Acceptance Criteria
- [ ] Loggers successfully demonstrate the differences between the old and new implementations
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
