### ISSUE TITLE
[FSR] Review page error alert messaging and functionality 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#69352]
## Description
Implement more helpful error handling on final review page. 

### [Design ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67811)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXV2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cd3b2646ea85276b3954036b778915de8cb63fe/image.png)

#### Example of Review page error message that has been implemented:

 - [Review & submit validation error links #21252](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21252)
   - [PR #16431](https://github.com/department-of-veterans-affairs/vets-website/pull/16431)

Given: Error handling isn't exactly clear on final review page
When: A veteran attempts to submit a form with an error
Then: Error alert links to set focus to the accordion where the error exists

## Tasks
- [ ] Examine the existing solution listed above and determine how to adjust it for our needs
- [ ] Implement error alert messaging and functionality
- [ ] Coordinate with design if we need to make adjustments

## Acceptance criteria

- [ ] Error messaging on final review page is clear and functioning as expected
- [ ] Works with current version of the form (post review navigation)

## Testing
- [ ] Complete manual testing
- [ ] Generate e2e/unit test for new functionality 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Final text has been confirmed. Just need Medallia side to wrap up and deploy to prod so we can include the number on our side

**Comment by Dr-Pongo** [comment]
Pre sprint 117 planning 01/16. I'll call it at 3 points left (been context switching a bunch with other tasks)

**Comment by Dr-Pongo** [comment]
[Review error documentation for reference](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/docs/reviewErrors.md)

**Comment by Dr-Pongo** [comment]
This is going to carry over again :( Only going to mark it as two points remaining for sprint 118 so I can create more tickets to break down the work into smaller tickets since it's more involved than I initially thought

**Comment by HeatherRienks** [comment]
thank you!!!

**Comment by Dr-Pongo** [comment]
I'm going to create some spin off tickets from this one. After struggling for some time this will be done much faster by narrowing scope to each chapter so we can include required fields for a lot of the custom pages that are needed to trigger the third party validator which shows the error messaging. 

We can leverage the `_override` functionality to help with stuff like employment history and any other specially nested data structures. With the override we should be able to get the corresponding accordion to highlight when the link in the error message is clicked, and hopefully show more detail on what the potential problem is. I should have the tickets up later today!

**Comment by Dr-Pongo** [comment]
Closing out this ticket since the work is more involved than anticipated!

**Appropriately sized tickets to address work:**
- [75831 Veteran information Chapter](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75831})
- [75832 Householed Income Chapter](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75832)
- [75833 Household Assets Chapter](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75833)
- [75834 Household Expenses Chapter](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75834)
- [75835 Resolution Option & Bankruptcy Chapters](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75835)
