### ISSUE TITLE
Project Kickoff for "View and update my representative/POA"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6935]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of [feature outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-POA)
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Jason Wolf - jwolf@governmentcio.com**
- DEPO Product Lead (required): **Steve Kovacs - steven.kovacs@va.gov**
- Entire VFS team (recommended): **James Adams - jadams@governmentcio.com**
**Jesse Cohn** - jesse.cohn@adhocteam.us
**Micah Chiang** - micah@adhocteam.us
**Kathleen Crawford** - kcrawford@governmentcio.com
**Derek Dyer** - ddyer@governmentcio.com
**Nick Wygonik** - nwygonik@governmentcio.com

## Scheduling
Preferred dates or times:

**Comment by meganhkelley** [comment]
Scheduled for 3/24 @ 11:30 am ET

**Comment by meganhkelley** [comment]
@jason-gcio let me know if that scheduling delay is blocking to y'all — since it is a kickoff that we will record, we could do this later this week even though most folks wouldn't be able to make it.

**Comment by mnorthuis** [comment]
For reference, here are the two existing content pages I mentioned...I don't believe there are other content pages, but need to do a full dig, there may be many places that we reference accredited reps and link to these pages as well, so we will need to work through that. 

- https://www.va.gov/disability/get-help-filing-claim/
- https://www.va.gov/decision-reviews/get-help-with-review-request/

**Comment by meganhkelley** [comment]
Meeting recording: https://zoom.us/rec/share/_OVLJLLzqVtJEqv_zUyFRYsALJjnaaa81yNM_fIPxUqwDAxjbI-tqq8O_7VeC3LL

**Comment by meganhkelley** [comment]
Hi @jason-gcio! Can you please be sure to add this work into the Collaboration Point Tracker, so that we have all artifacts and tickets in one place? Thank you! https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809

**Comment by vbellissimo** [comment]
Cancelling/old task.
