### ISSUE TITLE
Copy of Create FsrForm class

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#69350]
## Issue Description
Make a class for the FsrForm, which takes a sanitized form from FsrBuilder and performs the formatting for the specific FSRs. Should have children for user, vha and vba that contain all of the meaningful logic.

---
## Tasks
- [ ] Create parent class FsrForm
- [ ] Create child class UserFsrForm
- [ ] Create child class VhaFsrForm
- [ ] Create child class VbaFsrForm

## Acceptance Criteria
- [ ] FsrBuilder's responsibilities are further broken out into standalone classes for each FSR
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
At this time I don't think adding debt/copay models would be worth the effort. If we ever need to break an FSR submission down into individual debts it would make perfect sense, but not now.
