### ISSUE TITLE
Create a Domo Dashboard view of Users with both/either modern and legacy credentials, filterable by recently/last used of each

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#69367]
## Issue Description
We want to be able to get a Organic and Reactivation segment user counts filterable based on last/recently used.  This will allow us to view and make decisions for LGA based on the scale of segments based on activity.

The LastUsed data from MPI is not reliable and needs to be addressed to provide the needed views.

---
## Tasks
- [ ] Update the MPI data to include prior two years LastUsed data for all credentials
- [ ] Update the MPI data on a monthly bases with LastUsed data
- [ ] Create a view of Organic user counts filterable by last used date
- [ ] Create a view of Reactivation user counts filterable by last used date

## Acceptance Criteria
- [ ]  a view of Organic user counts filterable by last used date
- [ ] a view of Reactivation user counts filterable by last used date

**Comment by sdickson-gt** [comment]
There are too many anomalies in both MPI and SSOe data to create a new dataset from both sources to correct LastUsed.  The LastUsed field is fixed in MPI as of Oct and we can revisit in a few months with a view of reactivations since then.
