### ISSUE TITLE
[Design] Update MDT usability test materials (v2)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#6936]
## User Story or Problem Statement

Problem description: How might we create a usability test that allows Veterans/usability participants to give feedback on the application as they would actually use it?

## Goal
The goal is to create a usability test conversation guide that does not stop the participant between pages (per Shawna's feedback)

## Tasks
- [x] Rework the usability test conversation guide to include fewer (or no) hard stops for users mid-flow.

## Acceptance Criteria
- [x] New conversation guide completed in google docs for VSP feedback round (GH md file to come after)
- [ ] Conversation guide uploaded as a PDF if needed

**Comment by rebeccawalsh** [comment]
Decided that we will hand our plan and guide off to VSP as GH markdown, since some members are VA and won't be able to access Docs. This is just more standard practice and is worth the extra time to put it up.

Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/research-plan.md

Conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/conversation-guide.md
