### ISSUE TITLE
Change historic rates links to clone links on Veterans rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#6937]
## User Story or Problem Statement
As a content team member, I need to change the links to historic disability compensation rates to PDFs so they are easier to manage going forward.

![Screen Shot 2020-03-17 at 2.27.31 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/88ea97b3-307d-4265-b3a1-e109cc4deb8b)Drupal page: prod.cms.va.gov/disability/compensation-rates/veteran-rates

## Goal
Change the historic rates links at bottom of [Veteran rates](https://www.va.gov/disability/compensation-rates/veteran-rates/) to PDFs, which will be housed in Drupal. Post only the last three years of rates (2019, 2018, 2017)

## Objectives or Key Results this is meant to further
- Continue to move all elements into Drupal and make it easier to change out historic rates in future years.
---
## Tasks
- [ ] Upload PDFs of historic rates to Drupal
- [ ] Change links on Drupal page to PDFs instead

## Acceptance Criteria
- [ ] _PDF links appear in historic rates section on live page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
2020-03-18 PW Standup
* Moving out of sprint and into Ready for grooming

**Comment by MickinSahni** [comment]
2020-03-18 PW Grooming
* Anne reaching out to get PDFs for Randi to implement
* Groomed - changing pages into PDFs (instead of links to legacy pages) 
  * removing needs grooming label

**Comment by AnneHurley** [comment]
Howie to show Anne method of reverting, in Drupal, a page to its previous year's content. We can then generate an actual link to that historic chart. Will do this for all the 2019 rates historic charts.

**Comment by jenniferlee-dsva** [comment]
I'm confused by this ticket. The Web Content Team would do the cloning and linking to it. We should learn how to do this for ourselves, so we can maintain this via Drupal. ( @beeyayjay is just looking into HOW we can do this and -- I believe -- is giving us instructions on how we can support this ourselves. She is also going to build the export out functionality for tables, but that can happen (I think?) later in the year when we need to share exports with SMEs to update with new rates.) 

Also, we will need @mnorthuis 's IA and URL guidance on how we should implement this idea/solution. 

Let's use our Monday content weekly to walk through this together. Will Slack. 

@MickinSahni fysa

**Comment by AnneHurley** [comment]
@jenniferlee-dsva We created this ticket more or less as a placeholder, before we knew Beth was coming, and when I was talking to Howie about how one of us content people in Drupal might do this. Great to have @beeyayjay take the lead on the technical side, and looking forward to having the convo on Monday.

**Comment by AnneHurley** [comment]
@howardbrande @RLHecht  mentioned you were waiting for your sandbox environment to update (I believe) before I can log in - can you let me know when that is ready for me?
@mnorthuis  and @daniellethierryusdsva - Need your guidance on what to name the URLs of these cloned historic pages before we can go live. Please advise.
@jenniferlee-dsva  FYSA

**Comment by jenniferlee-dsva** [comment]
I believe Howie recommended using the auto url generate checkbox. This will create the URL based on the H1 page title. (And we would simply update the page title by adding `historic `or `archive `or some such somehow -- which I defer to Mikki/Danielle on for the pattern -- so it's crystal clear that that page is no longer valid.) @AnneHurley

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @jenniferlee-dsva!

My instinct for url is to stick with the "historical" language VA/VA.gov has been using. @mnorthuis let me know when you'd like to since on this to solidify. Thanks!

**Comment by AnneHurley** [comment]
@daniellethierryusdsva @RLHecht  and I cloned the main disability rates page for last year; it should go live on the main page in the links at the bottom tomorrow. 

Assuming all is good with this first one, I can do the 3 remaining disability pages as well, and we can implement the redirect.
@lunascoop @stephorkandatx @jenniferlee-dsva FYSA

**Comment by DanielleThierryUSDSVA** [comment]
Awesome, thanks @AnneHurley and @RLHecht! Will check it out tomorrow.

**Comment by DanielleThierryUSDSVA** [comment]
The cloned page looks great – thank you @AnneHurley and @RLHecht! 

Some added thoughts as we continue to build these out.

1. Are we setting these pages to no-index in Drupal so that they don’t get crawled by search engines and potentially come up higher than/rather than the current rates page? This may have already been discussed, but I didn’t see it on this issue so just checking.

2. Since the historic rates page looks so similar to the current rates page, I think we can make a few simple tweaks to make it very clear to Veterans that these are old rates and help them get to the current rates quickly if they want those.

Some simple ways we can think about doing that:

- **Make it clear in the intro but revising the first sentence a bit:**

View historical Veterans disability compensation rates for 2019. Use our compensation benefits rate tables to find your monthly payment amount. We base your monthly payment amount on your disability rating and details about your dependent family members.

- **Add an end date anywhere we include an effective date so it’s clear these rates no longer apply. Example below:**

Compensation rates for Veterans with a 10% to 20% disability rating
Effective December 1, 2018 – November 30, 2019

- **Consider adding somewhere near the top of the page something like the below:**

**Want the current Veterans disability compensation rates?**
[Get rates for the current year](link to current rates page)

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  - Have made updates to the main Historical 2019 disability rates page. 

- Clarified language in intro
- Added text and a link under intro for people to go to current rates page
- Added end date "to November 30, 2019" to "effective" language.

 preview-prod.vfs.va.gov/preview?nodeId-4714

Ready for @RLHecht

**Comment by RLHecht** [comment]
Edits on main disability historic rates page checked. @DanielleThierryUSDSVA here's the PDF[https://app.zenhub.com/files/133843125/c973a004-ab35-4841-abe7-c7124b64c392/download](https://app.zenhub.com/files/133843125/c973a004-ab35-4841-abe7-c7124b64c392/download)

**Comment by RLHecht** [comment]
Edits on historic special monthly compensation rates page are checked. @DanielleThierryUSDSVA here's the PDF: [https://app.zenhub.com/files/133843125/47f22f11-f435-4394-902d-da2e6fbfa9bf/download](https://app.zenhub.com/files/133843125/47f22f11-f435-4394-902d-da2e6fbfa9bf/download)

**Comment by jenniferlee-dsva** [comment]
Summary of decisions and action items from call with @mnorthuis @RLHecht  @kevwalsh . This approach should be used for the other cloned historic rate pages. 

1. Enable the menu. 
2. Treat the historic page as a level 4 (i.e., a child of the 2020 rates page). 
3. Make the menu/nav label shorter than the H1 (e.g., "Historic 2019 rates" in nav)
4. See example of level 4 menu behavior: https://www.va.gov/health-care/about-va-health-benefits/dental-care/dental-insurance/   -- This is the desired pattern if these steps work and there are no menu bugs.

This approach is for the interim/short term; we will evaluate all L4+ nav behaviors more holistically during L4 work. 
FYSA @AnneHurley  @DanielleThierryUSDSVA  @johnhashva

**Comment by mnorthuis** [comment]
URL pattern for these historic rates pages, since they will be sitting as a child to the current rates, can be simplified and structured as:
/historic-rates-2019

**Comment by RLHecht** [comment]
@mnorthuis @jenniferlee-dsva I updated the menu link and URL. Just confirming this is correct for the first historical rates page: ![Screen Shot 2020-04-23 at 8.08.48 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/39166b67-4a2a-40bb-be8c-1c37fe9ca0fa)

**Comment by RLHecht** [comment]
Left nav fixed and enabled on historic special monthly rates table as well. ![Screen Shot 2020-04-23 at 8.44.51 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/237d8c56-22e5-49b1-9178-0324f80be573)

**Comment by RLHecht** [comment]
Special allowances rates has now also been cloned, updated and published.

**Comment by RLHecht** [comment]
Birth defects rates has now been cloned, updated and published. @AnneHurley Does this mean this ticket can now move to validate? I believe so but confirming with you first!

**Comment by AnneHurley** [comment]
@RLHecht Yes - and means that @lunascoop can resume redirects of these four pages.

**Comment by mnorthuis** [comment]
@RLHecht I don't see the birth defect rates out there yet, just wanted to confirm.

**Comment by AnneHurley** [comment]
@mnorthuis @howardbrande @RLHecht  Howie confirmed that the content deploy failed. It's not yet clear why but CMS team is looking into it.

**Comment by RLHecht** [comment]
@mnorthuis The birth defects page is now up there. Closing this ticket!
