### ISSUE TITLE
Prepare presentation of Feedback data

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#69389]
## Purpose
Prepare artifacts associated with the synthesis of the survey.  Our goal w/ this updated Survey is to be able to track changes qtr-over-qtr, and make these results easily accessed and absorbed by Leadership and Platform teams.

Communicating these on Demo Day and a SDT Confluence space will help:
1) Communicate data to Leadership & Platform teams
2) Tell the story over time of progress or not

## Notes
- Important to relay info in a way that Leadership understands its significance, and hopefully is actionable for them as well when it comes to prioritization.

## Tasks
- [x] Prepare format to be shared on SDT's Confluence space
- [x] Create new data visualizations to compare Q3vsQ4 2023
- [x] Prepare slide deck to present at Demo Day

## Acceptance Criteria
- [x] [Deck is ready to present](https://docs.google.com/presentation/d/1AC6c-GJdMjhEljuv9OJshcZxTbDdn24CkQ3uv575EgU/edit#slide=id.p1) for Demo Day
- [x] [Confluence site is updated](https://vfs.atlassian.net/wiki/spaces/AP/pages/2629173255/new+Customer+Satisfaction+Survey+2023+and+beyond) and ready
