### ISSUE TITLE
Publicize Survey in Slack

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#69381]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey
[Previous documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)

## Tasks
- [x] Verify that Platform's [Survey page](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey#PlatformSatisfactionSurvey-ThesurveyiscurrentlyclosedRedforthisquarter.) is showing the Survey as OPEN.
- [x] Publicize Survey (Slack)
-draft messaging
-execute messaging
- [x] Schedule reminders in Slack

## Acceptance Criteria
- [x] Survey is socialized in Slack

**Comment by twoangstroms** [comment]
Rolling over to next sprint for scheduling reminders: Need first to get a sense of engagement before setting closing date for survey.
