### ISSUE TITLE
Prepare and Launch Platform Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#69380]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [x] [Prepare Survey in Optimal Workshop](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)
- [x] Update Confluence Documentation
- [x] Update Platform website documentation
- [x] [Launch Survey](https://ows.io/qs/mo77qlll)
- [x] Confirm Survey's visibility & data funneling

## Acceptance Criteria
- [x] Confluence documentation is updated
- [x] Platform website documentation is updated
- [x] Survey is live
