### ISSUE TITLE
Obtain Access to Necessary Development Tools 

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#69399]
### Description
The [VFS onboarding checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D) has an item to gain access to various tools. Please review the relevant documentation, identify the tools needed for the project, and complete the access request process for each necessary tool.

### Tasks
- [x] Request access to tools listed under [developer tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Additionalaccessfordevelopers).
- [x] Assess the [DEPO platform documentation](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) to identify any additional tools.
- [x] Verify that access to each tool is granted and confirm functionality.
- [x] Confirm complete access to all necessary tools before closing this task.

### Tools
- [x]  SOCKS access (will grant access to Jenkins, Sentry)
- [x]  TestRail access
- [ ]  Terminal Access (Vets API Access - EKS)
- [x]  AWS console access
