### ISSUE TITLE
Canary Launch for Benefits Claims

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#69392]
## Issue Description
We need to run an A/B test for Benefits Claims to make sure our monitoring is accurate

- This involves NOT flipping the submit flag, and instead flip Benefits Claims flag and running a submit click-through with test users
- - A failure in the Benefits Claims call will result in a failure with Claims and submit overall, maybe watch both
- Link to Benefits Claims Dash: (Update when ready)

---
## Tasks
- [ ] Find veteran prod users https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md
- [ ] Write up testing instructions in testrail, use for the run
- [ ] Run Canary sessions using testing instructions (or use scheduled meeting)
- [ ] Verify accuracy of metrics - we get activity, activity logs can be used to identify Canary users
- [ ] Any updates needed are made to monitoring

## Acceptance Criteria
- [ ] Successful calibration

**Comment by mchae-nava** [comment]
This is happening at the same time as PPIU
