### ISSUE TITLE
[FSR] Dev environment for testing

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#69390]
## Description
It would be really nice to be able to have a dev version of the FSR where we have some more wiggle room with playing outside of using a feature flag. 

There's been some investigation into [bypassing login for local devs](https://github.com/department-of-veterans-affairs/vets-api/pull/9256), but it would be helpful to have an unauth version of the form we can use and share for testing maybe on the dev.va.gov environment instead of staging. 

There are existing variables/functions we can leverage to determine what environment the application is currently being run in, so maybe we can leverage these to load a separate form schema where we can have experimental pages and versions of the form strictly for testing purposes. 

platform environment helpers can be found below:
`src/platform/utilities/environment/index.js`, `isDev` looks promising

## Tasks
- [ ] Investigate options for using dev.va.gov
- [ ] Experiment with unauth version of the form
- [ ] Determine size complexity if we need to load a fully separate form.js

## Acceptance criteria

- [ ] LoE is determined for implementing unauth/experimental version of the form
- [ ] Any necessary tickets are generated for additional discovery or development work

## Testing
- [x] N/A if non development work
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
@Dr-Pongo @HeatherRienks, I have added a new PR related to issue #69390. However, there is currently no ticket tracking the work I completed. This PR is for enhancing the GMT Threshold developer experience

**Comment by denisecoveyduc** [comment]
@Dr-Pongo  Is the original ask on this ticket still needed?

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo - he will review this next week in further detail and report back.

**Comment by Dr-Pongo** [comment]
I do think this would be beneficial to explore, especially once we clean up some of the legacy version of the FSR. Having the option for an unauthenticated or just testing version of the FSR on production could be massively beneficial for getting user feedback. I think the largest time drain in testing sessions revolve around sign in issues, so this could help that process. We could also load smaller portions of the form for specified feedback so it won't be necessary to have a veteran work through the lengthy form. Let me know if that makes sense!

@denisecoveyduc @HeatherRienks

**Comment by OptionSelect** [comment]
Per convo with Andrew noting my findings but seems like its not operable to me. I don't believe feeding an alternate formConfig to the App seems to work fully. I was able to get into the supposed flow as evidenced by the screenshot with the Test preceding the subheading and less chapters; however, after completing the veteran info chapter we should be navigated to resolution options but instead were routed to household income. Its as if it still had knowledge of the other config even though we were certainly inside the environment.isLocalHost testFormConfig that was fed to the App.

<img width="1103" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0d6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1747b8949f43e0a230eba378dfe3bf33b8a290e/image.png" alt="image.png" />
<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0t6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e725f0abffe6f7e6b1d168d87f813d6f4dafc6bc/image.png" alt="image.png" />
<img width="616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL096QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5216d6b7ce91fdf1d98aea46ac9ee54e8c79197c/image.png" alt="image.png" />
<img width="895" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1N6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7139e69c070af5625e39d05ff95127176e518cda/image.png" alt="image.png" />

**Comment by HeatherRienks** [comment]
Per FE Sync and @OptionSelect, let's have another FE dev look at this to see what our options are. Will create a new tix for the backlog.
