### ISSUE TITLE
ARM Nav & Search - User Test - Conduct Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#69396]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
1. Navigation
2. Search
---
## Tasks
- [x] Complete interviews
- [x] Manage interview day to day (team and recruiter coordination, debriefs, interviews, etc.)
- [x] Download videos and transcripts
- [x] Compile notes
- [x] Upload notes, transcripts, and video to Sharepoint
- [x] Upload notes and transcripts to EnjoyHQ
- [x] Create Zenhub ticket for analysis and reporting
---
## Acceptance Criteria
- [ ] All documents uploaded and ready for analysis & reporting

**Comment by oddball-lindsay** [comment]
Due to some no-shows, extending acceptance of interviews through Weds 11/22 (Tuesday 11/21 not included)

**Comment by jfinnerty13** [comment]
Completed upload to Sharepoint and Enjoy HQ
https://app.enjoyhq.com/sh/pj/e1d9be64-dd77-47b2-a563-b9e8f82c7f7a

Closing ticket
