### ISSUE TITLE
Canary Launch for PPIU

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#69391]
## Issue Description
We need to run an A/B test for PPIU to make sure our monitoring is accurate

- This involves NOT flipping the submit flag, and instead flip PPIU flag and running a submit click-through with test users
- - A failure in PPIU will result in a failure with Claims and submit overall, maybe watch both
- There are two PPIU calls: one prefill, one in the submit flow
- Link to PPIU Dash: (Update when ready)

This is to track the Canary section from our [PPIU release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/488b30b6fa454ef3c3f7f12aeeff26a12522193d/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20PPIU-DirectDeposit%20Service%20Endpoint%20Migration%20Release%20Plan.md)

We'll be scheduling times with users from [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) and verifying activity is captured properly in our [DataDog dashboard](https://vagov.ddog-gov.com/dashboard/pfj-tf3-mb4?refresh_mode=sliding&from_ts=1700158863442&to_ts=1700162463442&live=true)

---
## Tasks
- [x] Find veteran prod users https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md
- [x] Write up testing instructions in testrail, use for the run
- [x] Run Canary sessions using testing instructions (or use scheduled meeting)
- [ ] Verify accuracy of metrics - we get activity, activity logs can be used to identify Canary users
- [ ] Any updates needed are made to monitoring
- [ ] Establish Comms: put message out in evss migration slack channel 

## Acceptance Criteria
- [ ] Successful calibration

**Comment by mchae-nava** [comment]
Discussing with Mobile, some VA stakeholders on the official avenue for preventing adjudication on claims submitted by our volunteers

**Comment by mchae-nava** [comment]
Attempted to see if ProdTest is a viable alternative to point to

**Comment by mchae-nava** [comment]
RCTests caught some discrepancies, but otherwise went smoothly. Leaving this in review while we double check with our volunteer users using Aurora's feature gate
