### ISSUE TITLE
Research opportunities for improving notification workflow

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#69401]
## User Story
As a Governance team member, I want to be notified when VFS teams schedule Collaboration Cycle touchpoints so that I can complete all necessary scheduling tasks and ensure the VFS team is prepared for the meeting. 

Assignee: @briandeconinck @rferguson13 
Peer Reviewer: @shiragoodman 

## Description
Earlier this year, Governance team introduced new Slack workflows to be used by VFS teams when they schedule their Collaboration Cycle touchpoints. The preferred flow is as follows:

1. VFS team schedules touchpoint in Calendly.
2. VFS team uses Slack workflow to notify Governance of scheduled touchpoint.
3. Governance team completes scheduling tasks. 

Since the workflow release, Governance team has noticed that many VFS teams fail to complete step 2. Because all Calendly events are still populated on the Collaboration Cycle Calendar, Governance team can easily see when step 1 has been completed, but step 2 has not.  

The below workflow ends up being what happens instead:

1. VFS team schedules touchpoint in Calendly.
2. Governance team notices event on CC Calendar and waits for action.
3. After no action, Governance team nudges VFS team via Slack or via Calendly email to notify us via Slack workflow. 
4. VFS team uses Slack workflow to notify Governance of scheduled touchpoint.
5. Governance team completes scheduling tasks. 

Governance team still values the Slack workflow as it allows us to have a direct line of communication with the VFS team for asking questions pre-touchpoint, we can ensure the full VFS team (and not just the scheduler) are informed of the touchpoint since it's shared on their team channel, and it ensures notification of the scheduled touchpoint is communicated in the #platform-collaboration-cycle channel for all Collab Cycle stakeholders.

Since VFS teams do not have any issues completing step 1, but fail to complete step 2, how might we be able to take the notification we do receive via Calendly and/or the Google Collab Cycle calendar and integrate it with a modified Slack workflow for the VFS team so that the scheduling tasks can be completed and we still benefit from the Slack workflow?

## Tasks
- [x] Explore opportunities for revisions to the Slack workflow that utilize Calendly and/or Google calendar
- [x] Document proposed solution(s) in a Confluence draft page for Governance team review
   - [Options for improving notification workflow](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833220014/69401+-+Research+opportunities+for+improving+notification+workflow)
- [x] Present at weekly initiative meeting

**Note:** Implementation for this change will not occur in this ticket. The purpose of this ticket is only to document a proposed solution to the problem identified in the Description.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have identified possible solutions for implementing a better touchpoint notification workflow

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@shiragoodman Here ya go! https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833220014/69401+-+Research+opportunities+for+improving+notification+workflow 

Looking forward to your feedback.

**Comment by shiragoodman** [comment]
Team to present at Weekly Initiative meeting on 11/21

**Comment by briandeconinck** [comment]
Weekly Initiative Meeting recap:

There's lots of interest in the Calendly-to-Slack webhook option, with a possible follow-up to see if there's also a way to trigger reminders in Slack to attach artifacts prior to the deadline for each meeting. (Calendly-generated email reminders could be an option here too.) The sense of the room was also "see if it will work, but don't get too invested in it."

We agreed that the next step should be exploring the feasibility of Calendly-to-Slack to see if it's really a viable option, and then making a final decision based on that.

**Comment by shiragoodman** [comment]
exciting! I'll work on getting a ticket set up for next steps @briandeconinck @rferguson13
