### ISSUE TITLE
Phase Two of What We Can Help With Doc

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69403]
## Description 
This ticket will house the task of making updates to the VFS facing [What We Do and Don't Do Doc on Platform Site](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support). We need to add better formatting to ensure it remains digestible.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Sort content into buckets using this [documentation outline](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2813460496?draftShareId=752b4db0-c764-4895-b814-721b9b920321&inEditorTemplatesPanel=auto_closed) 
- [x] Make content collapsible so that folks can hide what they don't need to see
- [x] Send to Alyssa to review
- [x] Alyssa will publish
- [x] Content team pushes live on the Platform Site page here https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
Editing Page Link: https://vfs.atlassian.net/wiki/spaces/SUP/pages/2692612097/What+We+Can+Help+With+-+Platform+Support

---

**Comment by alyssagallion** [comment]
Transferred over to the live page: https://vfs.atlassian.net/wiki/spaces/SUP/pages/2692612097/What+We+Can+Help+With+-+Platform+Support

Will be pushed by content team in their next round. 

Added to the launched support enhancements page and will post in #vfs-platform-support and #vfs-all-teams when it is live. Closing!
