### ISSUE TITLE
Add Feature Toggle for adding Physical Location

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#69402]
## Item Description
Veterans would like to see the physical location of their appointment.  Physical location is being provided by the `vaos-service`.  This feature toggle will suppress physical location on the appointment details page until testing is complete and we enable in production.

---

## Tasks
- Add `va_online_scheduling_physical_location` feature toggle

## Acceptance Criteria: 
- [ ] The toggle is created for VAOS

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
@vbahinwillit - did we add this toggle`va_online_scheduling_physical_location`? I don't see it on the flipper list.
