### ISSUE TITLE
[FE] Nametag: Implement Space Force emblem

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#69413]
## Background
We received a logo to use for the Space Force emblem within the Nametag and Angela created a design in #67953 

[This is the finalized design](https://www.sketch.com/s/225eebbb-fb9a-42db-8655-75c30a9dc935/a/mPwL2vg)

Now we need to implement it.

## Tasks
- [x] Add Space Force file path to list of constants
- ~[ ] Write unit test~ not necessary, we don't have unit tests for any other logo/emblem
- [x] Add to vets-website repo 
- [x] Add to content-build repo
- [x] Move to validate (we'll need to figure out how to get a staging test user assigned to Space Force)

## Acceptance Criteria
- [ ] We can see the Space Force emblem in the nametag banner on staging

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log into staging with Space Force test user and confirm you can see the emblem in the banner

**Comment by allisonlu** [comment]
@ajakabcin 

this should be on staging! however i'm not sure what user is part of Space Force to validate this

**Comment by ajakabcin** [comment]
Thanks @allisonlu ! Hmm same for me - not sure how to go about getting a staging user assigned to space force (or any branch for that matter). I'll ask in our slack chat!

**Comment by ajakabcin** [comment]
@allisonlu user 226 is a space force veteran now, however the emblem does not appear to be showing in staging. let's look into this when you're back from pto
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/a96c40f8-fd13-4818-bf0d-e28c454c4509)

**Comment by adamwhitlock1** [comment]
I did some initial digging into this, and I'm not 100% sure why there are assets folders in the vets-website repo AND the content-build repo, but I think that might be where the file _also_ needs to go.

https://github.com/department-of-veterans-affairs/content-build/tree/main/src/site/assets/img

I did notice some commits done in the past to add logos so it does seem like that would be the place to add the space force logo in addition to the vets-website repo, and see if that resolves our issue. My inclination is that the assets folder for vets-website is strictly to make sure that locally an asset/image loads, but the actual site uses the files in the content-build. 

Let me know if you have any question on that @allisonlu and it might also be worth confirming with the [sitewide-public-websites](https://join.slack.com/share/enQtNjI2NzUyMjg0ODA5OS1hNTU2NmQ5ODc4OTI3N2JiMjk2NWYwZmVhNmM5OWNlN2QxNmNlYjE3MGE1ZWJiYTc0ZGZkNzRiNmM4M2VmMTMy) folks as well. I believe they work on the content-build repo

**Comment by allisonlu** [comment]
Confirmed emblem is showing up for user 226!

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/c3c0cc5e-cff0-4c2d-a6d8-784db40c9a74)

**Comment by adamwhitlock1** [comment]
Woo hoo! Can confirm that user 226 showed the emblem when I logged in as well. Great work @allisonlu

**Comment by ajakabcin** [comment]
Confirmed with user 226!
<img width="702" alt="Screenshot 2023-12-05 at 9 46 07 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/36d28ed0-d30d-4dac-864f-7f92e781185a">
