### ISSUE TITLE
Gather list of Github Repositories Teams Granted Access to & Not

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#69412]
## Description 
Gather list of repositories users who complete platform orientation are automatically granted access to

---

## Definition of Done
All Tasks below complete

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Gather list and verify it with Tier 2/Clint/etc. 
- [ ] Add to Github documentation in Confluence 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Will grab list from Shira.

**Comment by alyssagallion** [comment]
We have since taken over vets.gov/write access and have successfully documented it here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2860384263/Requirements+to+Be+Added+to+vets.gov-write
