### ISSUE TITLE
VISN in Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6941]
## User Story 
As a Veteran, I want to see VISN specific options in Facility Locator so that I am aware of services that are offered. 

## Goal
VISN specific services can be displayed. 
Particular use case: availability of online chat triage in VISN 8 and VISN 20
This is not intended as veteran facing filter at this time. 

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 
---

## Tasks
- [ ]Make VISN available to front end for VA facilities

## Acceptance Criteria
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
