### ISSUE TITLE
[Design] My VA: Create down-time message for planned VBA maintenance

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#69417]
## Background
There is an upcoming planned maintenance period for VBA systems (making adjustments for COLA) that will affect several features on My VA. These features (along with other things like Direct Deposit in Profile) will be down for users Saturday 11/18 - Sunday 11/19. We need to display a message on My VA below the H1 to let them know this is planned maintenance down time and that there isn't something wrong with their account/the system. (More info in resources section)

Danielle T will be sharing copy for downtime alerts in `#cola-downtime-planning-2023`

**Note: this must be ready for review with Samara before she heads to the OCTO offsite (11/13-11/16)**

## Tasks
- [x] Create design for downtime message using approve copy from OCTO
- [x] Share with team for implementation

## Acceptance Criteria
- [x] Design for downtime message exists and is shared with team

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Confirm design exists and copy matches OCTO approved copy

## Resources
More info in these threads:
- [Samara's note](https://dsva.slack.com/archives/C909ZG2BB/p1699291070039279)
- [Team discussion ](https://dsva.slack.com/archives/C909ZG2BB/p1699291296658539)
- [Notice from Samara about copy for the message](https://dsva.slack.com/archives/C909ZG2BB/p1699380768847469)

**Comment by andaleliz** [comment]
FYI Danielle let me know she is hoping to have content completed early next week.

**Comment by andaleliz** [comment]
@ajakabcin looking at the Sketch files, it doesn't appear that there are currently use cases that display alerts on My VA. Is that right?

**Comment by andaleliz** [comment]
@Samara-Strauss and @ajakabcin we still don't have copy for the alert but here's what I'm thinking:

- LOA1 users would not see the maintenance alert
- LOA3 users will see a dismissible, warning, v2 alert under the h1 and above the other sections on the page.  I don't think there are any other alerts that could possibly show on in that spot on the page, but please let me know if I should account for that.  The worst case scenario I could think of is if there are errors in every other section 😱 so [that's what I started with for a mock-up. ](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/p/01547CDB-2D6D-4126-A965-B08A7DBE6C7B/canvas). I shared this with Danielle to get her thoughts from a content perspective - and she agreed that it's the best option given the scenario.

Thoughts?

**Comment by Samara-Strauss** [comment]
Mockup works for me!

**Comment by andaleliz** [comment]
Wonderful! I will leave this open and sit tight until we get copy from Danielle. I set a reminder to follow up Tuesday if I haven't heard anything, and am also in the #cola-downtime-planning-2023 channel.

**Comment by Samara-Strauss** [comment]
Awesome, thank you. I'll also check in on Monday morning before I head to Philly.

**Comment by andaleliz** [comment]
@allisonlu and @ajakabcin [the mock-ups ](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/p/01547CDB-2D6D-4126-A965-B08A7DBE6C7B/canvas) have been updated with copy provided by Danielle. 

Do you both have everything you need for this at this point?  I learned there will also be a sitewide banner up so it feels a little redundant to have this alert too - but haven't heard that we _shouldn't_ move forward with our plan so here we are :)

**Comment by ajakabcin** [comment]
Looks great @andaleliz thank you!
