### ISSUE TITLE
Copy of Create Github Page in Confluence for Team

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69432]
## Description 
As a platform support specialist I need clear information on Github access so that I can better serve users.

Github is not always handled by one team our source, and the process to obtain access to different repositories across the platform are unclear due to this. This was brought up as a bigger issue than anticipated when a user needed access to a private repository but couldn't even get access to their team's repository. Some items needed their own team's additional support, some items required Github support. 

In order to best clear this issue, there seems to be value in adding Github information for the support team to work off of. 

---

## Definition of Done
When all tasks are completed
---

## Tasks 
- [ ] Draft GitHub access policy on Platform side
- [ ] Compile clean document
- [ ] Present draft to team
- [ ] Approved by Alyssa, Brandan, and Joe. 
- [ ] Publish to Confluence
--- 

## Resources & Additional Info 
[Escalated Github access request that prompted need for more information
](https://dsva.slack.com/archives/C02RLAUM2LV/p1689965150539589)
---

**Comment by alyssagallion** [comment]
Accidental creation of dupe issue. Closing.
