### ISSUE TITLE
EMIS Migration Testing

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#69437]
## Issue Description
Testing for EMIS migration - the scope to be discovered via  https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/68521

---
## Tasks
- [ ]  Regression test for prefill pages

## Acceptance Criteria
- [ ]Successful regression test for prefill pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by christinec-fftc** [comment]
Bunch of testing was done in [#68521](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/68521).

We were able to verify that prefill itself was working properly for 526. There is a bug with multiple data sources ([slack thread](https://dsva.slack.com/archives/C03LT909K1A/p1699470000620169)). Once that issue is fixed in staging, we can use this ticket to retest manually and verify the correct service history is being pre-populated on 526.

**Comment by christinec-fftc** [comment]
[Testing Notes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701453153231/790268b181530b43d5949d74b1f081a51c8bf04d?sender=ufe55a1a25f3f25394be01959)

**Comment by sethdarragile6** [comment]
As Christine mentioned [in slack](https://dsva.slack.com/archives/C03LT909K1A/p1701466429884739?thread_ts=1701443933.932369&cid=C03LT909K1A), we were able to successfully test from a migration perspective. We did see some awkwardness in the UI relating to the missing service period, and created this [ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/71043) to investigate/fix.
