### ISSUE TITLE
[CST] move timeline to overview tab

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#69449]
## Value Proposition
As a veteran with a pending disability claim, I don't want the current timeline in CST to obscure important information related to evidence submissions, so that I can find and take action on important requests.

## Design
[Sketch Link](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas)

UPDATE 12/20/23 - will just be moving the timeline to the overview tab

## Background
As part of our evidence request initiative, we think we've found a better place for the current timeline and that is in a separate "Overview" tab. This is a temporary solution as we re-work the claim contextualization framing entirely, which will likely use a different means to convey the claims process to veterans.

## Considerations
The new content should be behind the feature flag `cst_use_claim_details_v2`

## Tasks
- [x] Create a new tab labeled 'Overview'
- [x] Create a new component for the Overview Tab
- [x] Move the timeline from the Status tab to the Overview Tab
- [x] Put tab behind a feature flag

## Acceptance Criteria
- [x] The timeline is now part of the 'Overview' tab that shows when the feature toggle is enabled

**Comment by pmclaren19** [comment]
Talked to @skylerschain @uxgary about changing the acceptance criteria of this ticket. After investigating found that updating the timeline to use the new platform components isn't in the best interest of time/ user experience since we will eventually be replacing the timeline all together. Going to update this ticket acceptance criteria to include just moving the timeline over to a new tab callled overview and not updating the actual timeline.
