### ISSUE TITLE
Identify what related resources should be included on the FDG

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#69448]
## Purpose
What resources would be helpful/useful to users?

We know a number of them exist in various locations across VA resources (Github, Confluence, Platform Docs, etc).  What are they, and which ones should we reference and link to?  The idea being that any useful existing resources get pulled under the FDG umbrella for easy access or awareness by the user.

## Tasks
- [x] Identify useful [existent resources ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3056533512/Related+Resources+for+Forms+Digitization+Guide)
- [x] Identify useful [non-existent resources](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3056533512/Related+Resources+for+Forms+Digitization+Guide#Option-2%3A-Database.)
- [x] Create [discussion space](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3056533512/Related+Resources+for+Forms+Digitization+Guide#For-Discussion) that allows us to determine which to link to, and which to build out further
- [x] Consensus reached on which to link to, and which to build out further

## Acceptance Criteria
- [x] Findings are documented

**Comment by steel36** [comment]
This issue will roll over as Nicole reports that it is still in progress.
