### ISSUE TITLE
Design/BE | Enhanced Military Information | How do we get PROD data

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#69452]
## Background 
We discussed on 11/7 the need for more realistic data to understand the fields we're going to show in the UI, how to structure the data etc. 

## Tasks 
- [x] Reach out to Platform Support team and request access to VA Profile production data.
- [x] Identify a few Veterans who are willing to let us work with their data (UX)

## Acceptance Criteria 
- [x] Production access granted ([thread where Tom shared the details](https://dsva.slack.com/archives/C909ZG2BB/p1701270518472639))
- [x] We've found ideally 4 (one from each branch of service) 2 minimum veterans who can work with us in production

**Comment by tpharrison** [comment]
Before I reach out to Platform Support or VA Profile, I'm asking a few developers that may have production access how they went about getting it.

**Comment by andaleliz** [comment]
@mtcA6 sharing an update, that as soon as we know what the data looks like, I will reach out to some team members to invite them to help us out (last task on this ticket). I want to hold off on reaching out until we know exactly what kind of data we'll be pulling/exposing, so that I can set expectations accordingly.  

I have at least 3 people I can reach out to already, though I expect the upcoming holiday and people being OOO could delay responses. Maybe we'll know enough that I can start asking around Monday.

**Comment by tpharrison** [comment]
Opened [Platform Support Ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1700148591675389) to request production access.

**Comment by tpharrison** [comment]
Access request for Vets-API ArgoCD Terminal made.  Ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/70623

**Comment by tpharrison** [comment]
I have been granted production access through ArgoCD terminal.

**Comment by andaleliz** [comment]
@tpharrison I've identified at least 2 folks so far who can work with us, so I think we can close out this ticket given the tasks and AC above.  Feel free to reopen if you disagree.
