### ISSUE TITLE
[CST] Evidence request alerts on claims details page (status tab)

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#69450]
## Value Proposition
As a veteran with an open evidence request in CST, I want to be able to find those requests and distinguish them from other content  in claims detail pages.

## Background
As part of our evidence request initiative, we have a new evidence request design that will be applicable on claim detail pages.

Replacing ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/58594

## Currently what happens
When a user goes to the Status tab they see the following alert 
![Screenshot 2024-01-08 at 9 57 19 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/1c6aa810-4ce0-46b7-ac7f-da736c0495a5)

When they select 'view details' they are directed to the Files tab where they see all first party alerts (the alerts in yellow)  and second party alerts (the alerts in grey) 
![Screenshot 2024-01-17 at 2 28 09 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/54e79feb-70e0-49c1-adc4-c637791d57c9)
Also on the Files tab under the 'Additional evidence' header there is an alert
![Screenshot 2024-01-17 at 3 06 30 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/f72a4cce-d5b5-4f0c-8a87-001c24666b00)

## What we want to happen
When a user goes to the the Status tab they see a new header 'What you need to do' and underneath that header they see all first party alerts. 
![Slice 1](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/5db237fa-9997-4906-9e62-7a8e3c62ec6f)

On the Files tab they no longer see the 'Files requests' header. All first and secondary alert display under the 'Additional evidence' header. After the alerts, there is no longer an alert that says 'Please only submit additional evidence that supports this claim' and instead there is text.
![Screenshot 2024-01-17 at 3 09 06 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/911d5516-79d7-4694-8b94-93dec38d6869)
![Screenshot 2024-01-17 at 3 14 15 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/092aac80-917c-4f71-9c85-66e9b4b08b3a)

When there are no first party alerts users will see the following message under the header:  
![Screenshot 2024-01-08 at 10 18 24 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/8823a2a4-82c6-4c72-9dbc-6c2f884c60b0)

## Open questions
- Should we have a feature flag around this showing up on the status tab vs only files tab - yes lets use the feature flag `cst_use_claim_details_v2`
- Should we have a feature flag around the old alert component vs new alert component - yes lets use the feature flag `cst_use_claim_details_v2`
- If the current alert component is being used everywhere keep it as is and just reuse it. But if the current alert component is only being used here then make a new component or update the current one.

## Design Approach 
[Mocks in Figma](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-809&mode=design&t=vr7AAdcV08s2Uxmp-0)

## Acceptance Criteria

- [x] There are clear alerts on the status page identifying evidence requests for the veteran
- [x] The header for the "what you need to do" section has to clearly differentiate this section for the user from other parts of the page.
- [x] Different evidence requests can be distinguished from one another and contain enough detail to provide a clear action item for the veteran

- [x] Contains a header that says 'What you need to do'
- [x] First Party Alerts show up under the Status tab
- [x] When a user selects 'view details' on a First Party Alert and they provided the requested information, the alerts for those requests go away (speak with @jerekshoe on if this currently happens, looks like it doesnt in Dev env)
- [x] Body text descriptions cannot be insanely long (apply existing logic from old cards if it's the best way to accomplish this)
- [x] Content elements/fields (such as dates) will conform to the previous alert designs and provide the same information to veterans
- [x] When there are no First Party Alerts, an empty state message appears under the header that says 'There's nothing that we need from you right now. We'll let you know when there's an update.'
- [x] New functionality is behind the feature flag `cst_use_claim_details_v2`

```[tasklist]
### Tasks
```

**Comment by pmclaren19** [comment]
@jacobworrell @skylerschain can someone please add the sketch or figma link to this ticket?

**Comment by skylerschain** [comment]
Added – let me know if you have any questions!

**Comment by HeatherWidmont** [comment]
A lot of refactoring work, we may need to repoint this.

**Comment by HeatherWidmont** [comment]
Has the PR in drafts, currently working on testing. Sorting through fun EVSS issues 😄
