### ISSUE TITLE
[Deactivation] Update copy for first Pension form intro page AND grey widget on "how to apply"

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69454]
## Issue Description

We need to update the existing gray widget on the ["how to apply" page](https://www.va.gov/pension/how-to-apply/) to include information about Intent to File

Info found on the gray widget includes:

_- the online form being temporarily unavailable right now_
_- how they can apply in the meantime (PDF by mail or Quicksubmit)_
_- info about whether they should submit an intent to file._
_- wait until Jan 2024 to apply online then_

We also need to update the info alert on the _unauthenticated_ version of the [Pension application form page intro](https://www.va.gov/pension/application/527EZ/introduction) that is now deactivated. 
It says: 

> You don’t have any saved online pension form.
You can apply for VA pension benefits by mail, in person at a VA regional office, or with the help of a VSO or other accredited representative.
>
>[Learn more about how to apply for VA pension benefits](https://www.va.gov/pension/survivors-pension/)

However, if you're a Veteran who doesn't have a saved online pension form, this message would be incorrect and concerning.
The link goes to the Survivor's Pension page, but should instead go to: https://www.va.gov/pension/how-to-apply/ (unless we change the link)

---
## Tasks

- [x] Draft copy update to include reference of ITF to the current gray widge on the ["how to apply" page](https://www.va.gov/pension/how-to-apply/) to include information about Intent to File

A mockup of this idea exists from Emily on this Slack message: https://dsva.slack.com/archives/C05MS96P6P2/p1699454972803689?thread_ts=1699390990.579769&cid=C05MS96P6P2
- [ ] Draft copy for unauthenticated info alert on Pension form intro page
- [ ] Review copy draft with CAIA, OCTO (Julie/Emily) and PM (Vicky)
- [ ] Provide copy to frontend engineer (Sean and/or Thomas? include Todd) for build
- [ ] Engineer makes changes and publishes copy updates

## Acceptance Criteria
- We will have incorporated ITF reference to the existing gray widget on the ["how to apply" page](https://www.va.gov/pension/how-to-apply/)
- We will have replaced the existing gray widget copy on the [first Pension application form page](https://www.va.gov/pension/application/527EZ/introduction) **that is now deactivated** with the same updated copy found on the gray widget on the ["how to apply" page](https://www.va.gov/pension/how-to-apply/)

**Comment by vbellissimo** [comment]
Proposed copy provided by Emily: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3kyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc75bed5eee2e21eb4288801f6c192e3a3ece94f/image.png)

**Comment by jstrothman** [comment]
@katherine-fung Re the proposed copy for the info alert: Maybe we move the widget end-note to the first bullet? 

- The first bullet has info about if you already started applying online
- The new 2nd bullet says you can create an ITF, and doesn't say you don't need to if you already started online (which really is if you already started in the last 90 days?)
- The end of the widget has a note: We'll record the potential start date as the date you first saved your online application. (And doesn't use ITF language)

**Comment by jstrothman** [comment]
Proposed copy for the form intro page (unauthenticated) to change from: 

> You don’t have any saved online pension form.
You can apply for VA pension benefits by mail, in person at a VA regional office, or with the help of a VSO or other accredited representative.
>
>[Learn more about how to apply for VA pension benefits](https://www.va.gov/pension/survivors-pension/)

to

>You can’t use our online application right now
>
>We’re updating our online application. 
If you started applying online already, you can still sign in to VA.gov to refer to your saved information when you fill out the PDF form.
>
>[Learn more about how to apply for VA pension benefits](https://www.va.gov/pension/how-to-apply/)

**Comment by vbellissimo** [comment]
For tracking purposes, added @mjknight50 as an assignee here, based off this conversation: https://dsva.slack.com/archives/C05MS96P6P2/p1699540384804199

**Comment by mjknight50** [comment]
I think we've completed all changes related to deactivation.
