### ISSUE TITLE
Prep research plan for validating new standards within Governance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#69456]
## User Story
As a Governance team member, I want to identify how we'll validate the application of the revised VA.gov Experience Standards within Governance team at the Staging Review so we can we be certain we've built a process that supports our needs.

Assignee: @erinrwhite 
Peer Reviewer: @rferguson13 @allison0034 

## Description
Before we fully launch the revised VA.gov Experience Standards, we want to pilot them with ourselves to ensure they meet our goals. In the previous state of the VA.gov Experience Standards, we had 91 standards across 11 categories. We now have 22 different standards across 7 categories, have restructured them according to the user experience, have added a new layer of descriptive tags and have redefined our launch-blocking criteria. We need to validate that when  identifying findings at Staging Review with the revised VA.gov Experience Standards, that we're able to easily find the applicable category and standard, comfortably apply the appropriate descriptive tags, confidently identify if the issue is launch blocking or not, and communicate clearly at the Staging Review meeting details of the violation for the VFS team.

The purpose of this ticket is to create a Research Plan for validating our revised standards and new process within our own Governance team.

A few notes:

- We can use a combination of different [research methodologies](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1472888866/Platform+Research+Methods) to meet our specific needs
- We'll need to pilot with live Staging Reviews, and want to be sure to give the VFS team the opportunity to not participate in our pilot (and hold the Staging Review as we do today) if they choose to
- We'd like to pilot with ideally 5 VFS teams at 5 Staging Reviews, however that is subject to change depending on the frequency and cadence in which Staging Reviews are scheduled
- We will be creating 2 research plans per this ticket and ticket #63507 however the pilot window and the teams/products we pilot with at Staging Review will be the same. 

## Impacted Artifacts
[Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan)

## Tasks
- [x] Prepare Research Plan for validating new standards within Governance
- [x] Share with Governance team for review and feedback
- [ ] Share with Matt for review, feedback and sign-off

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have prepared a research plan for validating our new VA.gov Experience Standards within Governance

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Same here - [rough draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan) ready for your initial review @allison0034 @rferguson13. Questions: is the research approach okay? What can be clearer? What's missing?

**Comment by allison0034** [comment]
I don't think I have a problem with the approach but it would be helpful to know what questions you want to ask.

**Comment by erinrwhite** [comment]
@allison0034 @rferguson13 Thank you. I got [some questions added to the document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan#Method) - what's missing or needs to be rewritten? Thanks!

**Comment by rferguson13** [comment]
@erinrwhite Looks good. Just one comment on the page.

**Comment by allison0034** [comment]
Looks really good! I made a couple of comments : )

**Comment by shiragoodman** [comment]
Hey @erinrwhite - commenting here as well. I reviewed the research plan for Governance and I think it looks good! Please see [my comments on the VFS team research plan ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63507#issuecomment-1812731014)as many of them apply here as well.

**Comment by erinrwhite** [comment]
I think this is ready to go for final review!

[2023-11: New experience standards (Governance team): Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan)

**Comment by rferguson13** [comment]
@erinrwhite Just one comment!

**Comment by shiragoodman** [comment]
@erinrwhite I mostly had the same concerns here that I had for the VFS study. See [other comment.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63507#issuecomment-1819187183)

Thank you for your hard work and diligence with this! I'm excited to get it going :)

**Comment by allison0034** [comment]
@erinrwhite this looks great!

**Comment by erinrwhite** [comment]
Same here! Tagging @humancompanion-usds for his review when he has time. It's a holiday week so this'll likely move to the next sprint.

[Research Plan with Governance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan)

**Comment by erinrwhite** [comment]
Closing - if we need to make changes based on OCTO feedback, we will address in a separate ticket.
