### ISSUE TITLE
[Deactivation] Monitor deactivation email clicks in Google Analytics or DOMO

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69462]
## Issue Description
Right after the Pension form and pages were deactivated on November 8, 2023, an email was sent to Pension applicants with an in-progress status on the online form. The email included links to specific parts of the website for more information.

More details about what was included in this email found [on this card](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69310): 

We need to monitor how many people are clicking on each of the links of the email so:

- we can gauge the level of engagement from email recipients; and
- provide any relevant information to OCTO and VBA

More info from Laura on how to do this on this Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1699453527916079?thread_ts=1699395055.746399&cid=C05MS96P6P2

---
## Tasks
- [x] Starting November 9, 2023 (because we want to check it after the email was sent on Nov 8), visit the [VA Notify Domo dashboard](https://va-gov.domo.com/page/2040841289)
- [x] Filter the dashboard by campaign (template) named `2023pensiondeactivation`
- [x] Or visit this link in our GA: https://analytics.google.com/analytics/web/#/report/content-landing-pages/a50123418w177519031p176188361/_u.date00=20231109&_u.date01=20231109&_r.drilldown=analytics.landingPagePath:www.va.gov~2Fpension~2Fapplication~2F527ez~2Fintroduction~2F&explorer-table.secSegmentId=analytics.campaign&explorer-table.plotKeys=%5B%5D/ 
- [x] Provide any updates observed to Vicky/Emily as needed.

## Acceptance Criteria
- [x] As a team, we will have an idea how many people are clicking on which links from the deactivation email, based on information gathered from DOMO

**Comment by vbellissimo** [comment]
Since the Pension deactivation email was sent, it looks like...

- approximately 30 new users have navigated to the website's Pension section from the email
- when they land here, they browse about 6 pages total within VA.gov 
- they usually spend about 6 minutes doing this before they leave

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVAzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b210e2cfea5972f90be6398489da94bfbd6b42b/Screenshot%202023-11-21%20at%202.07.13%20PM.png)

cc'ing @emilytheis @jstrothman for reference.
