### ISSUE TITLE
[FE] My VA: Implement down-time message for planned VBA maintenance

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#69472]
## Background
There is an upcoming planned maintenance period for VBA systems (making adjustments for COLA) that will affect several features on My VA. These features (along with other things like Direct Deposit in Profile) will be down for users **Saturday 11/18 - Sunday 11/19**. We need to display a message on My VA below the H1 to let them know this is planned maintenance down time and that there isn't something wrong with their account/the system. Additionally the claims, payments, and debts tools will be unavailable and therefore we should hide these sections.

Design created in #69417 with [sketch file](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/p/01547CDB-2D6D-4126-A965-B08A7DBE6C7B/canvas)

**Note: this must be ready for review with Samara before she heads to the OCTO offsite (11/13-11/16)**

## Tasks
- [x] Open PR on `vets-api` to [add a new feature flag](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml) --- feature flag name: `auth_exp_vba_downtime_message`
- [x] Set up feature flag functionality on `vets-website`
- [x] Implement down-time message below the H1
- [x] Conditionally hide claims, payments, and debts when the message is displayed
- [ ] Toggle feature flag on for downtime

## Acceptance Criteria
- [ ] Down-time message appears on My VA below the H1 for the designated period of time (tbd) when the flag is turned on
- [ ] Claims, payments, and debts sections do not appear when flag is turned on

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log into staging with any LOA3 account and confirm the downtime message appears when the feature flag is on

**Comment by allisonlu** [comment]
@ajakabcin @andaleliz 

just to clarify – this alert only appears at the top of the page, and other sections of the page are not affected. Will users be able to see statuses of their benefits? I can't tell from the Sketch file if the other sections should be hidden or have an error message.

This is what I have so far (on my local):
![vba-message](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/1d703bd1-f4cd-4a45-9ade-df584da7abd8)

**Comment by andaleliz** [comment]
Hi @allisonlu! I'm sorry the Sketch file isn't more clear - I'm just now realizing this is our first time working together on a thing and I'm not sure how you prefer to get annotations. 

My understanding is that we won't be able to pull any info related to claims, payments, or debts, so those sections would be hidden. Health and education sections would not be impacted by the maintenance window.

Benefit application drafts is a little muddy to me - if a person were to click to continue an impacted form, I don't think they'd be able to  work on it, so it makes me want to hide that stuff. But, since we can successfully pull the data, I think that might be overkill for this short maintenance window and we can leave that part alone for now.

**Comment by ajakabcin** [comment]
Hey @allisonlu sorry I missed this yesterday! Agree with what @andaleliz said! I also didn't realize we would be hiding claims, payments, or debts but agree that's the path forward.

**Comment by allisonlu** [comment]
@ajakabcin ready for validation! i see it on staging for Cecil

**Comment by ajakabcin** [comment]
Looks good to me! Plan is for Adam to turn this on in prod by EOD today. Awesome work getting this out the door so quickly @andaleliz and @allisonlu !
