### ISSUE TITLE
[EPIC] USWDS v3 component migration

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#69482]
## Background
We learned in [this slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1695320888067059) that there are updated USWDS v3 components available for use in Sketch and in our FE components. 

The way I see this, there are 3 layers, FE, Design/Sketch, Contact Center Guides

### FE
From a FE perspective, the recommendation is to slowly add these components in as we work on new items to uncover any potential bugs.

### Design/Sketch
From the design side of things, we'll have to update our sketch files (there are many!) and we'll need to consider how we go about this to ensure production and sketch stay in step. 

### Contact Center Guides
Similarly to sketch as we update to the new components we should update any impacted contact center guides. 

## Acceptance Criteria 
- [ ] sketch is updated 
- [ ] FE is reflecting the latest and greatest set of components and we've removed the old ones from the code 
- [ ] Contact center guide is matching FE
