### ISSUE TITLE
[FE] My VA: Technical discovery on v3 components

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#69483]
## Background
We learned via [this slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1695320888067059) that there are updated USWDS v3 components available for use in Sketch and in our FE components. This transition will involve FE work and lots of updates to our design documentation. In order to assess a level of effort on that work we should do an inventory of what all will need to be updated on My VA. This work also has implications for Google Analytics as it migrates to GA4 - updating the components will help with that effort.

## Tasks
- [x] Review slack thread and documentation on v3 components
- [x] Review components in use on My VA and identify what will need to be updated
- [x] Discuss with team (including Profile devs and designers) on strategy/order of operations for making the updates
- [x] Work with PM to create tickets

## Acceptance Criteria
- [x] List of components needing updates exists
- [x] Strategy/plan for making the updates exists

**Comment by allisonlu** [comment]
## uswds v3 - my va + common

from [VA design system Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-accordion--default)

| components that can be upgraded to v3 | on My VA? | in /common/ folder? | what section/s or file/s? |
| -- | -- | -- | -- |
| Accordion | ❌ | ✅ | DevToolsLoader |
| Additional info | ✅ | ❌ | CernerWidgets (v2 only) |
| Alert | ✅ | ✅ | IdentityNotVerified; MPIConnectionError; Dashboard; CernerWidgets ([old](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/CernerWidgets.jsx#L55) and [v2](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/CernerWidgets.jsx#L123)); DowntimeNotification; BenefitPayments; ClaimsAndAppeals; Debts; HealthCareContent; DebtNotificationAlert; Notifications; and some non-component files (see below) |
| Breadcrumbs | ❌ | ❌ | |
| Button pair | ❌ | ❌  | |
| Button | ❌| ❌  | |
| Checkbox group | ❌ | ❌ |  |
| Checkbox | ❌ | ❌ | |
| Featured content | ❌ |  ❌ |
| Icon | ❌ |  ❌  | |
| Memorable date | ❌ |  ❌  ||
| Modal | ❌ | ✅  | DevToolsLoader |
| Number input | ❌ | ❌  | |
| Pagination | ❌ |  ❌  | |
| Privacy agreement | ❌ |❌ | |
| Process list | ❌ |❌ | |
| Progress bar | ❌ |❌ | |
| Radio button | ❌ | ❌ ||
| Search input | ❌ | ❌ ||
| Select | ❌ | ❌ ||
| Statement of Truth | ❌ | ❌ ||
| Text input | ❌ | ❌ ||
| Textarea | ❌ | ❌ ||



---


### va-alert non-component files involved

- [covid-19.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/covid-19.jsx#L164)
- [helpers.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/helpers.jsx#L262)

### other notes
- For components that are using react-bindings, we can still just add `uswds` attribute (from what i can see in some Storybook examples), but we should confirm with DST that this applies for all v3 components
- we're mainly using the alert component ([warning variation](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default#warning)) for error states for each section when our API calls fail
- other than that, we use the 
  - [default](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default) for Covid-19 alert
  -  [error variation](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default#error) for Downtime notification alert
  -  [continue variation](https://design.va.gov/storybook/?path=/docs/components-va-alert--default#sign-in-or-tool-prompt) for unverified accounts
- _(out of scope for this ticket)_ the [RenderClaimsWidgetDowntimeNotification.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/RenderClaimsWidgetDowntimeNotification.jsx#L23) component might be a dupe of the `renderWidgetDowntimeNotification` function helpers.jsx

**Comment by allisonlu** [comment]
not sure if Profile has done technical discovery yet, but i put together a list for that directory too:

## uswds v3 - profile

from [VA design system Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-accordion--default)

| components that can be upgraded to v3 | on Profile? | what section/s or file/s? |
| -- | -- | -- |
| Accordion | ❌ | |
| Additional info | ✅ | many |
| Alert | ✅ | also many |
| Breadcrumbs | ✅  | ProfileBreadcrumbs |
| Button pair | ❌ | |
| Button | maybe | AccountSecurityTables has a non-web-component button that has a `va-button-link` class - this probably won't be affected |
| Checkbox group | ❌ |  |
| Checkbox | ✅  | NotificationCheckbox (react-binding) |
| Featured content | ✅  | CopyAddressModalPrompt, MilitaryInformation |
| Icon | ❌ | |
| Memorable date | ❌ | |
| Modal | ✅  | CopyAddressModalFailure, CopyAddressModalSucess, BankInfo, EditConfirmCancelModal (all react-bindings) |
| Number input | ❌ | |
| Pagination | kind of (derivative) | ConditionalProcessList |
| Privacy agreement | ❌ | |
| Process list | ❌ | |
| Progress bar | ❌ | |
| Radio button | ❌ | |
| Search input | ❌ | |
| Select | ❌ | |
| Statement of Truth | ❌ | |
| Text input | ❌ | |
| Textarea | ❌ | |
