### ISSUE TITLE
[BE] 10-10EZR - Standalone form: Exploration on getting status/data from EE Service on Means Test

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#69489]
## Background
As a Veteran who needs to provide an update to my health record, I want to provide information that may change or maintain my financial responsibility for VA health care, so that I can receive the benefits that I am entitled

A financial assessment, also known as a "Means test" is done for Veterans who do not automatically qualify for no-copays.  These Veterans must provide Spouse, Dependent and/or Income information, so that the Health Eligibility Center (HEC) can complete the assessment and determine whether the Veteran qualifies for low or no copays.

If the Veteran does qualify for low or no copays and they want to maintain or improve their financial responsibility each year, they must submit a 10-10EZR annually (starts January 1st), which would include their Spouse, Dependent and/or Income information, so that the annual "means test" is completed.

We may want to prevent the Veteran from providing updates to Spouse, Dependent and/or Income information, if they already have a "means test" on file.  
We need to explore the Eligibility & Enrollment service to find out what information is available and if there is a sort of status or something that would tell us:
- There is a "means test" already on file for the current year
- Results of the "means test'
- Data used for the "means test" (Spouse, Dependent and/or Income details) (Nice to have)

### Resources
<details>
<Summary>Conversation in Slack</Summary>

**Heather Justice**
Update on how ES would handle an EZR submitted within a current year that has already had a means test:
If there are less dependents on the EZR than on the current record
We need to test this to truly understand what will happen
Desired outcome: Any information that would impact the financial assessment/means test would be ignored.  The Veteran should only have one means test per income year (this is calendar year).
Future: We need to consider adding a check on E&E service to see if there is a means test already present in the current income year, and if there is, possibly preventing any info that could impact income from being updated. 
Insurance information can be updated any time, but Josh F is double checking on how multiple policies with adding/removing would work.
There is a caveat that the EZR service hasn't been used in about 8 years, and we may find out more on what actually happens during the end-to-end testing.
cc 
[@patrick](https://dsva.slack.com/team/UFN410MGF)
 
[@Kristen McConnell](https://dsva.slack.com/team/U0158T9DJCA)

**Patrick Bateman**
and im inferring that if a veteran does not have a current means test, that means (:drum_with_drumsticks:) they have never submitted dependent data, and therefore there is no data to be changed or overwritten?
what about data from a prior year?
i mean this should also be a UX red-flag right?
Any information that would impact the financial assessment/means test would be ignored.
why would we enable a user to enter information that would be ignored? has this been discussed and addressed?

**Jessica Stump**
It is basically the entire household financial information section. We knew those with a certain SC% should skip it and had "short form" on the list for v2. Being able to check if they had a means test the previous calendar year is new

**Heather Justice**
 this has not been discussed as I just found out and did not have time to talk it thru with everyone.  I want to understand the process from the business side of this before we decide on the actual outcome for this use case.  Joshua was stating that a Veteran should not be allowed to submit information that would change their means test for the year, that was why he was saying it being ignored would be the outcome.  I will find out more info from HEC to round out our understanding.

also, a little more info on means tests.
Veterans can start sending EZRs for a new means test in January of the new year with the previous year's household data (Jan 2024 EZR will have 2023 financials and household info)
A Veteran who has never completed an EZR can complete one for a means test any time during the year, and 'should not' submit another one until the upcoming January.
The risk is someone sending in an EZR with different information because they didn't like the means test results they got.

FYI - Simone is contradicting the above information, stating that they would indeed update the current record if the EZR is submitted with new information before the new income year (essentially before January), but it would not trigger a new test (edited) 

**Patrick Bateman**
ok my first question was going to be, “what happens when a veteran who has a means test on file, that means test result required copayments, and veteran loses their job in july?”
based on the above, the veteran would be stuck with copayments for the remainder of the year until a new means test is executed in january. but upon digging into it (including in this [directive](https://www.va.gov/vhapublications/ViewPublication.asp?pub_ID=8867)), there is a hardship process for this exact situation that basically waives copayments until next year’s means test is executed.
so what this really feels like is a potential pivot (and im assuming others have gotten here already) where we only allow veterans to enter information for income, dependents, and deductible expenses on the EZR if they don’t have a means test on file for the calendar year. otherwise, we should ask direct them to the hardship waiver process.
of course we know that we can’t get access to “does this veteran have a means test on file?” information yet because the enrollment system can’t give us this info, right?

**Heather Justice**
Joshua F said we may be able to get it from the E&E service

**Patrick Bateman**
ah that’d be nice. if we could get the results of that test, and maybe even the info used for the test, that’d be a nice bonus.

**Heather Justice**
Yep, I am writing a story to explore that

**Patrick Bateman**
ok do you think it is too extreme to say that we’re not going to launch any means test related sections of the EZR (which might mean not launching any of the EZR) until we can determine whether or not the user has an active means test?

**Heather Justice**
So I am on the fence there.  If a Veteran does provide an update prior to January, then the assumption is that it would just update the record and nothing else is done.
Is this a bad thing? Possibly, if the Veteran doesn't know that it won't impact their means test/copays since it is not a new Income Year.
Could we add an explanation, that makes sense? Sure.. That might work until we get the system logic in place.  But that is more scope to an already tight timeline.
Does the business want the record updated within an already tested year?  It wouldn't make sense really, if nothing changes.. We would have to ask them (edited) 

**Patrick Bateman**
Does the business want the record updated within an already tested year?
i think :point_up: that is my concern. there is no reason for the veteran to submit this information if they have one on file already, as far as i know. and im very doubtful that information updated in a prior calendar year could be pulled into the next calendar year for the means test calculation (so the idea of “pre updating” data for next year falls apart).

**Heather Justice**
Yep, exactly my thought, it does not make sense

**Patrick Bateman**
so you’d have to write prominently on the section, “if you’ve already submitted this information this year, don’t fill out this section.”
but thennnnn
you’d have to make all the fields optional.
so then you’d have to add a breakpoint in the form for the user to decide to fill out or not (like the EZ)

i think if we can get access to the means test status information in the next 3 months, i’d be comfortable with advising the user that:
income, dependent, and deductible information will not be used if they already submitted that information in the current year;
if they have had a change in circumstance since the last time they filed, they should use the hardship waiver process
and then give them the option to fill out or skip those sections

**Kristen McConnell**
Also, the non-means test sections (I would argue) are better covered by the functionality available in the profile too.

**Heather Justice**
Except for Insurance, yes.. all the Veteran info is in the Profile
and how often is someone updating insurance?

**Patrick Bateman**
the only entity that cares about updating insurance is VA, b/c facilities get to bill private insurance foe VA care. there is no real incentive for veterans to update insurance. so not very often unless forced :slightly_smiling_face:
ok so basically we’re back at the beginning. only difference is that it is cold out now.

**Heather Justice**
ha yep.  Ok, let me see what we can do.  I know we cant hide those pages, but this might be a viable workaround.
One catch i can think of is if they say yes to married, and/or dependents, all required fields must be completed to be sent to ES, or it will reject it (same issue as EZ right now)
so we cant make them all optional

**Patrick Bateman**
do we have a list of user scenarios / journeys for the ezr somewhere i can take a peek at?

Heather Justice
Here are the [use cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZR-Update-health-care-benefits.md) and here is the [sketch file with the user flow](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/E00D429A-2608-489A-BB55-4A53C6FA6317/canvas)

**Patrick Bateman**
ok for cases B, C, D, E, F, G, H, I… the reason a veteran would be doing that (other than they just like to update stuff) is to qualify for lower / no copays, eligibility for travel reimbursement, and (to the extent it matters) a higher priority group. our current MVP doesn’t actually do this if the veteran already has a means test on file. is that summary correct?

**Kristen McConnell**
That summary matches my understanding at this point.

**Heather Justice**
That is my understanding too

**Patrick Bateman**
ok then i think we have no choice but to condition the launch of the EZR on the availability “does this veteran have an active means test?” information .

**Patrick Bateman**
@Heather Justice
 as far as finding out if we can get this data from an existing endpoint/resource, how might we do that?

**Heather Justice**
We need to see what is available in the EE service.  I am going to see if one of the BE engineers can check it out.

</details>
 
- Feedback from Team:
     - Adding dependents within the year may not benefit the Veteran, however it could be beneficial to not have to re-enter the information when it is time for the next "means test".

## Tasks
- [x] Explore the EE Service for data points available
- [x] Create an outline/list of these data points and what kind of information they would include
- [x] If possible, formulate an opinion on:
     - [x]  What data points we can use to determine if a current year "means test" is on file
     - [x]  What data points we can use to possibly display to the user of the previous "means test"
     - [x]  Is there any other information we can use for other possibilities (is there anything here that would make things easier for the Veteran, and/or us?)
  
## Acceptance Criteria
- The EE Service has been reviewed, an outlined list of data points is created and is ready for discussion on how to use it.

**Comment by JoshingYou1** [comment]
The following data is from the user with the email `vets.gov.user+3@gmail.com` in the list of staging users: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv.

```
"incomeTest": {
  "gmtAddressInfo": {
    "line1": "142 WHITEHAVEN CIR",
    "city": "HIGHLANDS RANCH",
    "county": "DOUGLAS",
    "state": "CO",
    "zipcode": 80129,
    "country": "USA"
  },
  "incomeYear": 2022,
  "discloseFinancialInformation": true,
  "agreesToPayDeductible": true,
  "effectiveDate": "2023-07-23T00:00:00.000-05:00",
  "totalNumberOfDependents": 0,
  "primaryIncomeTest": true,
  "futureTest": false,
  "incomeTestsource": "HEC",
  "incomeTestType": "Means Test",
  "incomeTestReportDate": "2023-09-01T10:08:33.000-05:00",
  "thresholdA": 39849,
  "gmtThresholdAmount": 62600,
  "totalIncome": 53750,
  "netIncome": 47737.65,
  "deductibleExpenses": 6012.35,
  "netWorth": 0,
  "statuses": {
    "status": [
      {
        "determinedStatus": "GMT Copay Required",
        "completedDate": "2023-09-01T10:08:33.000-05:00",
        "lastEditedDate": "2023-09-01T10:08:33.000-05:00",
        "incomeTestType": "Means Test",
        "status": "GMT Copay Required"
      },
      {
        "incomeTestType": "Co-Pay Exemption Test",
        "status": "Non-Exempt"
      }
    ]
  },
  "networthThreshold": 80000,
  "pensionThreshold": 16037,
  "childIncomeExclusionThreshold": 13850,
  "cadAdjusted": false
}
```

The object above is an example of potential means test data we can pull from ES. Here's a quote from Josh Faulkner:
```
the incomeYear is what will tell you if its a current year disclosure and test or a past year test, means tests do not expire anymore but Rx copay tests still require to be done annually for medication copay exemption
```
In the data above, there is `"incomeTestType": "Means Test"`, which could be helpful as well.

The data located in the `statuses` object should tell us the results of a means test as well as when it was completed. This could be some of the info we show to the user. I pulled this out of the main object above:
```
{
  "determinedStatus": "GMT Copay Required",
  "completedDate": "2023-09-01T10:08:33.000-05:00",
  "lastEditedDate": "2023-09-01T10:08:33.000-05:00",
  "incomeTestType": "Means Test",
  "status": "GMT Copay Required"
}
```

Regarding the data used for the means test, here's another quote from Josh F:
```
everything under financials info goes into the test when the EZ is submitted
```
