### ISSUE TITLE
Burial | Confirm Accepted Claim

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69480]
## Issue Description
We need to confirm acceptance of the Burial 530 online claims by downstream systems. Example: Central Mail sends back a claim ID or success response, so we can validate the claim was accepted.

---
## Tasks
- [ ] Identify how to confirm accepted receipt of Burial claims
- [ ] Document the solution
- [ ] Create dashboard to track confirmed claims

## Acceptance Criteria
- [ ] Dashboard that tracks acceptance of Burial VA.gov claims by the final end-point.
---
