### ISSUE TITLE
Forms Dashboard Updates - 5655 & 10-10EZR - INTERNAL

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#69494]
## Issue Description

This is an internal ticket for 2 dashboard updates 

[10-10EZR](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/68871)

[5655 - version 4](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/68094)

---
## Tasks
- [x] Update template  - Christine
- [x] Review & Approve template before hand off to Phil - Michelle & Joe
- [x] Upload to BQ - Phil
- [x] QA updated dashboard - Christine

## Acceptance Criteria
- [x] All tasks above completed and handed off to team.

**Comment by michelle-dooley** [comment]
@dorseypa1 here is the template ready to be uploaded to BQ https://docs.google.com/spreadsheets/d/13PPfoLnFDLASe0WTaAehurp9t2nSmEF-tMkc1iL1dnI/edit#gid=1109167657
