### ISSUE TITLE
Optimize Queries in Looker Dashboards with Mobile Team to reduce BQ Costs

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#69496]
###  Description
**Note**: Greta is no longer with the Mobile Team - instead, we'll be needing to work with Ameet and Victor on this. JJ and Phil connected with the Mobile Team on 2/8, and 2/12, and determine the following would be an appropriate courses of action.

**Team:** Flagship Mobile Team

The Mobile Team has been running Looker dashboards that are incurring very large BQ costs due to the way they are set up/running. ~~Greta~~ Victor on the mobile team will be working with Phil to create views within BQ to replace how the data is extracted to Looker today. Once she completes those views, Phil will review for performance optimization and any other assistance we may provide to help minimize costs and streamline processing.

### Tasks
- [x] ~~Greta~~ Victor and Phil connect to review queries feeding Looker dashboards
- [x] Phil reviews queries and provide optimization on guidance, as well as cost estimates for running
- [x] Track BQ costs for reduction using new views
- [x] Documentation: 
     - [x] Document the way they are doing the Looker process today and why it is so costly
     - [x] Document our recommendations/changes made and guidelines 
---
### Acceptance Criteria
- [x] Identify list of queries feeding Looker dashboards.
- [x] Identify points of inefficiencies and areas for improvements within queries.
- [x] Create issues for BQ fixes within backlog, and look to refine and pull into upcoming sprint. 
- **Backlog ticket** - https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/76918
- [x] Draft resolution plan to be shared with all parties, (Dave Conlon, Andrea Hewitt, Mobile Team), to ensure next steps are agreed upon, and understood.
- End state for this - Looker dashboard, (_**Flagship Mobile Monthly Report**_) is updated to use views and is no longer incurring/reducing large processing costs

### Generated Artifact
[Write-Up and Plan](https://docs.google.com/document/d/1J7FosnQHBp151vtqm_PgR0QQMR_DxaijSNbmIScZBrs/edit)

**Comment by michelle-dooley** [comment]
Removing from this sprint as this is blocked by mobile team due to other priorities. The query in question has been turned off but we will continue to monitor.

**Comment by johnny-jesensky-adhoc** [comment]
Queries from Looker dashboards being used by Mobile Team, https://docs.google.com/spreadsheets/d/1mGcfIsmfMqH4EASgWWFkzkHOZOPXbyMQSarVtsgtFV0/edit#gid=0

FYI @dorseypa1

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1, I created a [ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/76918) in our backlog to work towards a materialized views for the Mobile Team, as well as an artifact with a larger plan, which I'll be moving to Confluence.

I'll connect with Dave on this next week to talk through some next steps. Good work on this one this sprint. Moving this ticket to _Done_.
