### ISSUE TITLE
Examine Best Practices for survey naming conventions

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#69517]
## Purpose
We've seen the Support team create the VFS Satisfaction Survey, and it's unclear who's being asked and what they're satisfied about.

Can we employ our SD principles that provide general naming guidance for teams who create surveys?

## Tasks
- [x] connect with platform design lead for survey way-finding
- [x] desk research
- [x] [create recommendations page in Confluence](https://vfs.atlassian.net/wiki/spaces/~318780155/pages/2849898601/Survey+naming+conventions+for+the+Platform)
- [x] group discussion / review

## Acceptance Criteria
- [x] recommendations are ready and available
- [ ] publicize

**Comment by tayism** [comment]
This work will roll over to allow time for group discussion/review.
