### ISSUE TITLE
Facility Locator Edge Case Dashboard - Data 

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#69515]
## Issue Description

We need to pull together the dataset to be used for the [Facilities edge case request](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/61633) based on our [mock up](https://docs.google.com/presentation/d/1WQIc7Rlgr1pET3Kmzkfr_wUn7u6-Y6wEVG_V2HgF7wg/edit#slide=id.g267a520b92f_0_168) and feedback from our meeting with team. 

Requirements:
Facility Locator page url: va.gov/find-locations/
Aggregation: monthly
Updates: monthly
Metrics: users, previous page path, device, browser, page path, pageviews, events....

---
## Tasks
- [x] Define/review requirements
- [x] Create query and pull 1 day of test data
- [ ] QA test data
- [ ] Iterate until data is as needed for dashboard
- [ ] Begin designing dashboard

## Acceptance Criteria
- [ ] Data is extracted and ready for dashboard
---

**Comment by michelle-dooley** [comment]
Sprint update: This work will continue into the next sprint.

**Comment by michelle-dooley** [comment]
Link to supporting worksheet for reference https://docs.google.com/spreadsheets/d/1siGoD2djYPr3adFjjO_pO_9Hf1WhqVbe-EaRFt3yYIQ/edit#gid=1442645657

**Comment by michelle-dooley** [comment]
Adding our slack threads for reference. https://dsva.slack.com/archives/C01S78V4AUA/p1701186549719079

**Comment by michelle-dooley** [comment]
Closing this ticket for tracking. Will create new one for QA work.
