### ISSUE TITLE
[spike] Accessible copy of completed form 

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#69534]
## Value Statement
**_As a_** Veteran
**_I want to_** have an accessible copy of my completed Board Appeal form
**_So that_** I can keep as a record, and use it for review.

---
## Background Context
We initially wanted to supply a PDF download for Veterans to give them access to their completed claim. After discussion with Lighthouse, we found that their current method of PDF generation is not accessible, so we conducted a brainstorm for ideas to provide Veterans with a copy of their completed claim that can put accessibility first.

From the brainstorming session, we've narrowed down to a few ideas. 
1. Creating an accessible PDF based on digital form submission
2. Creating an HTML version of a completed form that exists on va.gov as record
3. Sending completed form information via email

Before diving deeper into design, we want to estimate the dev feasibility and effort of the ideas

Some questions to think about in terms of feasibility:
- How feasible is it to cache data for long-term? What is the impact on storage?
- How actionable is our solution? 
    - Are there dependencies?
- What is the level of effort to implement?

## Acceptance Criteria
- [ ] Feasibility and estimates provided for all four options listed below
- [ ] Open questions about a11y and security answered

## Designs and Build Notes
- [Brainstorming Mural](https://app.mural.co/t/coforma8350/m/coforma8350/1691785014802/16e7144c246d8d8a18518135f70c7071051c2ba7?sender=udbf574074425980f04c55360)
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Appeal-PDF-Download-Initiative%20Brief.md)

### Option 1: Email claim download
- Confirmation page that sets expectation for email
- Email with download link
- Authorization
- Automatic download of PDF using existing PDF generation library that includes accessible formatted doc with digital form submission answers + non-accessible paper form

```mermaid
flowchart TB;
    id1["Confirmation"]-->id2[Confirmation email]-->id3[Authentication]--"Automatic download"-->id4[Complete claim + PDF];
```
- [Email automatic download mockup](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/prototype/8C47EA88-21A3-4BEC-9CA8-38A6E56058B3/a/8C47EA88-21A3-4BEC-9CA8-38A6E56058B3)

### Option 2: Persistent HTML page for completed claim
- Confirmation page that sets expectation for email
- Email with HTML link
- Authorization
- Authenticated page linked to Veteran's account with completed claim information
- Link to download non-accessible paper form PDF

```mermaid
flowchart TB;
   id1["Confirmation"]-->id2[Confirmation email]-->id3[Authentication]-->id4["Authenticated page with completed 
claim information download link"]-->id5[PDF];
```
- [Persistent HTML page mockup](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/prototype/40A84FC0-A2EC-46CF-8DAB-03E58C1D7934/a/40A84FC0-A2EC-46CF-8DAB-03E58C1D7934)

### Option 3: Email completed form data
- Confirmation page that sets expectation for email
- Email with completed form data is sent to Veteran.

```mermaid
flowchart TB;
   id1["Confirmation"]-->id2[Confirmation email with completed form data in body];
```

## Out of scope
- Development work
- Secondary aspects (ie. archive repository / organization of completed claims)

## Open questions
- Is it possible to generate an accessible PDF in the frontend using the NODE library DK referenced? 
- Are there risks with sending completed form data through email?
- How accessible are print modal generated PDFs?
- How accessible are VA emails?
- How are additional attachments treated?
- How will text in open form fields be treated?

## Tasks
- [ ] Determine feasibility of saving in-progress form data after form submission
- [ ] Determine level of effort for creating an accessible PDF on the frontend using NODE library of the completed form using digital form data
- [ ] Determine level of effort in packaging a Lighthouse-generated PDF to a frontend generated PDF 
- [ ] Determine level of effort of creating a persistent HTML page with completed form data
- [ ] Determine level of effort to link to an authorized page
- [ ] Determine feasibility and level of effort of loading form data into an email to the Veteran
- [ ] Determine scalability of the 4 options, and what type of complexities we need to consider
- [ ] Determine if there are security risks in the 4 options

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@eileen-coforma to make wireframes for each LOE request
@saderagsdale to ask LH about the Ruby on Rails gem

**Comment by saderagsdale** [comment]
@saderagsdale @Mottie @data-doge Review tasks and confirm alignment

**Comment by eileen-coforma** [comment]
Removed the option of using print modal from confirmation page, because DK said that the print modal can't reliably generate an accessible PDF to begin with.

**Comment by HeatherWidmont** [comment]
@Mottie to scope the complexity of the technical work

**Comment by saderagsdale** [comment]
Takeaways from the convo:

(Preferred) Option 2: Persistent HTML page

- Benefits us because we want to save the data anyway
- Allows us to get better usage data about user demand
- Most components are already set up to meet the accessibility requirements needed
- Not bespoke, so don’t have to build for each form
- Could reuse code from the review and submit page, already compatible with the form system
- Should we build another app or build the form for each page?
- Maybe more extensible to other parts of the form flow if we want to place the persistent HTML link in other places

**Comment by saderagsdale** [comment]
@eileen-coforma closing this based on our morning meeting. Let me know if you want to keep it open.
