### ISSUE TITLE
Content Dashboard Update - Resources and support - INTERNAL

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#69532]
## Issue Description

The Content, Accessibility & IA team has requested an update to the [Content Dashboard](https://va-gov.domo.com/page/426422632). Here is their [request ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/69037) that contains the urls that need to be added. 

Here are the [instructions for loading new content page](https://vfs.atlassian.net/wiki/spaces/AT/pages/1713045522/How+to+-+Loading+new+content+pages+to+the+Content+KPI+Dashboard). This would be a new section/product_name the name to be used 'Resources and support' and will be a new tab on the worksheet link in the instructions

---
## Tasks
- [x] Update the [content template](https://docs.google.com/spreadsheets/d/1EsBH0RWTg48y9I0QTtCSYfzqUdPZQF5ccm4N6uEitQc/edit#gid=972850618) per instructions above. product_name = 'Resources and support' - Christine
- [x] Upload new ursl to BQ vsp_sites/content_urls dataset - Phil
- [ ] QA data from GA once loaded into Domo

## Acceptance Criteria
- [ ] New urls have been added to Content dashboard
---
