### ISSUE TITLE
Create Slack Reminder to reference documentation on morning of IC rotation

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#69537]
## Issue Description
_A reminder in Slack needs to be created so that the next Tier 1 Support person can easily grab informative documents from Confluence to answer any questions relating to their rotation as Incident Commander_

---
## Tasks
- [ ] _Configure reminder in the #Platform-Tech-Team-Support channel in Slack that links to Incident Commander Playbook and Incident Commander Toolkit documents, and reminder is triggered 8am EST every Wednesday._

## Acceptance Criteria
- [x] _Slack reminder appears 8am EST every Wednesday in #platform-tech-team-support Slack channel, Oddball workspace_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alyssagallion** [comment]
@jknipes Moved this to the backlog since it isn't a support ticket!

**Comment by jknipes** [comment]
@alyssagallion can we post Confluence page links in Oddball #plaform-tech-team-support channel, is this better in our Tier 1 Team DM?

**Comment by jknipes** [comment]
Slack [reminder set](https://oddball.slack.com/archives/C0459AQ5GBT/p1702934437335209)
