### ISSUE TITLE
VBA Cost Of Living Adjustment Support

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#69547]
### Requirements/Ask:

The weekend of **Saturday, November 18 – Sunday, November 19, 2023**. The Cost of Living Adjustment (COLA) will be applied to Veterans Benefits Administration (VBA) Compensation Services and Pension & Fiduciary Services benefits. This will cause a down time for products on VA.gov that rely on VBA's database. 

The following applications will be unavailable:

- All applications that access the VBA Corporate database (includes BGS)
- All applications that access the Benefits Delivery Network (BDN)
- All Veterans Benefits Management System (VBMS) applications
- All applications that use Common Security System (CSS) for login validation, such as Education
- All access to the VBA Corporate database through Benefits Enterprise Portal (BEP) via web or Thick-Client application via Tuxedo

[Original announcement in slack](https://dsva.slack.com/archives/C064JKBD0N8/p1699292323567839)

In supporting this the Platform team has been asked to perform several tasks:

```[tasklist]
### Tasks
- [x] To review services located in [this Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699022689906/c254ed5503dedce1ff1c3240ada0cfa7cb91caf2?sender=9eac489b-df76-4c6a-b8bd-05011472f293) and to cross check them with our PagerDuty services to identify what can be supported via a Maintenance Window / Downtime Notification.
- [x] To create tickets for each of the line items in the Mural board so that each can be individually tracked
- [x] To work to identify which teams "own" the respective items in the mural and potentially the associated services in PagerDuty
- [x] To clarify how Maintenance Windows / Downtime Alerts work so it can be properly communicated outward as well as what fields align with what portion(s) of the message
- [x] To update the Mural board with findings from the PagerDuty investigation
```
### Acceptance Criteria:
- [x] All items in the Mural board are accounted for with an update (either information complete OR needs assistance from elsewhere)
- [x] A detailed write up, in Confluence, on how Maintenance Windows / Downtime Alerts is updated/created and accounts for how the fields are leveraged, how the timing works, etc.
- [ ] Share the write up and details related to the line items with OCTODE

**Comment by bdech** [comment]
[Link ](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/69627)to the Epic that contains all of each individual ticket, along with a ticket related to Maintenance Windows/Downtime Alerts in Confluence.

**Comment by alyssagallion** [comment]
@little-oddball I'm going to close this ticket since we have completed our work. Let me know if we need to do anything else!
