### ISSUE TITLE
DR | Distinguish between evidence upload logging for SC and NOD

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#69546]
## Value Statement
**_As a_**  Developer
**_I want to_** be able to see separate logs for SC evidence uploads and NOD evidence uploads
**_So that_** we can have more precise error logs

## Background Context
Our “Evidence Upload to S3” panel in the [NOD Dashboard](https://vagov.ddog-gov.com/dashboard/tvp-imf-tb7/benefits---notice-of-disagreement?refresh_mode=sliding&from_ts=1698692251914&to_ts=1699297051914&live=true) is showing an unusually high number of evidence submissions.  This is because, in [NOD | Log KPIs #65543](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65543), we didn’t distinguish between SC and NOD submissions for evidence uploads to S3. See [previous PR for adding KPIs](https://github.com/department-of-veterans-affairs/vets-api/pull/13973/files#diff-381befcb7e4a786ae0bf251cd3e835c964f8fb64730bef8ef8ca26b371d2b17bR16).

## Out of scope

* Other logging refactors / clean up

## Tasks

- [x] Research where to get `form_id` from the API call to `#save_attachment_to_cloud!`
- [x] Restructure the logging for [`DecisionReviewEvidencesController#save_attachment_to_cloud!`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/decision_review_evidences_controller.rb#L21) to have the proper `form_id` depending on which form the upload came from
- [x] Update tests
- [x] Set up DataDog alert for evidence uploads from unexpected form id
- [x] Monitor Datadog and verify that the evidence upload logs appear separately
- [x] Update NOD and SC Datadog dashboards

## Definition of Ready 
- [x] We've identified how to get the `form_id` to the part of the code where the logging occurs
- [x] We have access to the appropriate DataDog dashboards

## Definition of Done
- [x] We can look at evidence upload logs and identify which form it came from
- [x] The log data are not exactly the same in both NOD and SC dashboards
- [x] The “Evidence Upload to S3” panel in the [NOD Dashboard](https://vagov.ddog-gov.com/dashboard/tvp-imf-tb7/benefits---notice-of-disagreement?refresh_mode=sliding&from_ts=1698692251914&to_ts=1699297051914&live=true) displays logs more proportional to the number of NOD form submissions and evidence submissions to Lighthouse.

**Comment by saderagsdale** [comment]
PR is merged, will deploy today.

**Comment by data-doge** [comment]
Deployed today, and everything works as intended. I left a little update in https://dsva.slack.com/archives/C05UPRR0HK3/p1700624214657119. There's still a bit of clean up I need to do in DataDog, so I'm going to leave this ticket open until that's complete.

**Comment by data-doge** [comment]
Created new "unexpected form ID" alert in DataDog ([link](https://vagov.ddog-gov.com/monitors/179138)), and cleaned up DataDog S3 dashboards. Closing this ticket.
