### ISSUE TITLE
Link edit for #69406

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#69559]
## Info
Content edits according to [content support ticket #69406](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69406)

## Tasks
- [x] Review support ticket 
- [x] Confirm the correct link for logging into the local environment is updated. Look to confirm with the individual who submitted the ticket - Alex Taker.
- [x] Make content updates to the website accordingly
- [x] Prepare page for deployment

## Acceptance Criteria

- [ ] Platform website will be updated with the correct link to setting up a local account, and deployed.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/69559?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
Contacted ticket originator (Alex Taker) via Slack to see if they know where the link should go to. They provided me with a suggestion: https://github.com/department-of-veterans-affairs/vets-website#running-a-mock-api-for-local-development

**Comment by BSmolensky** [comment]
I reached out to Ryan Smith (frequent updater of the page in question) via slack to see if he agrees with this new suggested link.

**Comment by BSmolensky** [comment]
Ryan Smith got back to me. Says he will take a look at it soon.

**Comment by BSmolensky** [comment]
Heard back from Ryan (the SME). He informed me that the original link needs to stay but that the new link (provided by the ticket originator) should be added to the pages as part of a multi-step/options list. I will create this new content and then have Ryan double check that the wording is accurate and easy for developers to understand. Then I will check the page for launch-blocking issues. Then I will send it to Scroll Viewport for deployment.

**Comment by BSmolensky** [comment]
Wrote Draft changes to page and sent them to the SME for approval.

**Comment by BSmolensky** [comment]
Draft changes approved by SME. Page check for LB issues. None found. Page is ready to deploy.

**Comment by johnny-jesensky-adhoc** [comment]
This was deployed on 12/4. Moving this to _Done_.

FYI @BSmolensky
