### ISSUE TITLE
Develop Outreach and Events Info Alert

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#6955]
## User Story or Problem Statement
Given VA events are likely to be impacted by the current crisis, I want to know whether certain events are continuing, canceled, rescheduled, or otherwise impacted so that I can plan accordingly. 

Relevant page: https://www.va.gov/outreach-and-events/events/

## Tasks
- [x] Generate content for an info alert
- [ ] Provide heads-up to OPIA before publishing
- [ ] Publish info alert in Drupal

## Acceptance Criteria
- [ ] An info alert is created and published on https://www.va.gov/outreach-and-events/events

## Notes
> This is likely on an event-by-event basis so for an info alert we probably want to keep it generic.
> We want to tell people to check with the event organizers before they attend to make sure it's still on
> Josh Tuscher is the main POC for Events.

**Comment by MickinSahni** [comment]
Adding this as unplanned to Sprint 17

**Comment by AnneHurley** [comment]
Note: Dave Conlon: Josh Tuscher is the main POC for Events.

**Comment by AnneHurley** [comment]
Suggested alert text, modeled on the alert text on Blue Water Navy page:
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/

H: Coronavirus alert

Please check with the organizers of each event to make sure the event is still happening. For more information, you can visit the Centers for Disease Control (CDC) for the latest coronavirus information. You can also read about VA's public health response.

**Comment by AnneHurley** [comment]
@davidconlon @mickin @kevwalsh @RLHecht 

Have emailed Josh Tuscher and cc'd you all to alert him to fact that the Events page does *not* accommodate alerts/banners. 

We could edit the intro text to include a version of the above language, but it wouldn't be called out in as obvious a way as an alert would.

**Comment by MickinSahni** [comment]
2020-03-19 PW Standup
- have a way to add the alert to the page with Randi
- haven't heard back from Josh

**Comment by AnneHurley** [comment]
Have written alert text for Outreach and Events page, and for Events page. @RLHecht  if you can read over the text, and screen share to see if I'm deploying it correctly, that'd be great. Standing by.

**Comment by AnneHurley** [comment]
H: COVID-19 may affect whether events take place

Please check with the organizers of each event to make sure the event is still happening. For more coronavirus information, you can visit the Centers for Disease Control (CDC). You can also read about the VA public health response.

Waiting on @davidconlon and Josh Tushner (emailed both) to approve copy, then will apply to

- Outreach and events page
- Events page
- Each individual event page

**Comment by AnneHurley** [comment]
@RLHecht  I've updated the name, title and copy of the alert to remove all mentions of covid, CDC or health. 

 
https://prod.cms.va.gov/admin/content/alerts
[Alerts events screenshot]
(https://images.zenhubusercontent.com/5c6313e20f871b64caae9909/6632792d-a26e-4871-9c5f-7899d76e608b)

^here is how it looks now in the Alerts directory. I've edited the wording of the headline. Let me know what you think. 

If you can move to publish after you edit, that would be great. I can email all the DEPO folks when I start in the morning.

**Comment by RLHecht** [comment]
@AnneHurley The text looks OK to me but two questions:

1. This is currently set as a warning and not an informational alert. I think that's OK because it's the same as the coronavirus banner on the home page but just wanted to confirm.
2. It's set to go on all the individual pages and the events page but also this one:  https://www.va.gov/outreach-and-events/
Jen hadn't mentioned that one in the email and I think it makes sense for it just to be on the events main page since this one is not all about in-person functions.

**Comment by RLHecht** [comment]
Made the changes we discussed and published with a content only deploy. Moving to validate.

**Comment by MickinSahni** [comment]
2020-03-20 PW Standup
- Validated!

![image](https://user-images.githubusercontent.com/13204473/77179207-85c6d980-6a9e-11ea-998b-9e5c12532d75.png)
