### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Enable application in production

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#69557]
## Description
In order to begin user research, we need to enable the EZR in production. This production release needs to be behind a feature flag, as we are not ready for public consumption of the application. As a result, we would like to redirect users who may "accidentally" stumble upon the application page to be redirected to the VA.gov homepage. Only user research participants and 1010 team members with verified ID.me accounts will be permitted access at this time.

## Tasks
- [x] Create feature toggle record in `vets-api` repo
- [x] Add redirect functionality in EZR application for users who do not have the feature active in `vets-website`
- [x] Enable EZR application prod deployment in `content-build` repo
- [x] Add user emails to list of enabled users in Flipper UI

## Acceptance criteria
- Application is successfully available in prod for users behind the feature flag
