### ISSUE TITLE
Remove v0/terms_and_conditions_controller

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#69551]
# Issue Description
I don't think this is used anymore, and can be removed.  Here is some monitoring for it on dev/staging though which should probably be removed as well:

https://vagov.ddog-gov.com/monitors/manage?q=terms&order=desc

# Tasks
* [x] Remove `TermsAndConditions`, `TermsAndConditionsAcceptance`, `TermsAndConditionsAcceptanceSerializer`, and related files from vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/14495
* [x] Remove `terms_and_conditions` & `terms_and_conditions_acceptances` tables from vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/14516
* [x] [Check with Authenticated Experience team](https://dsva.slack.com/archives/C053JC66YHF/p1699905944166199) to verify terms and conditions is safe for removal
* [x] Remove [related monitoring for terms and conditions](https://vagov.ddog-gov.com/monitors/manage?q=terms&order=desc)

**Comment by bramleyjl** [comment]
Terms and Conditions PRs are ready for review; I'm holding off on removing the Datadog synthetic tests until the removal PRs are approved.

**Comment by bramleyjl** [comment]
PRs landed yesterday, related checks have been deleted.
