### ISSUE TITLE
Create content for #69342

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#69560]
## User Story
As a VFS team member,
I need to understand what the process is for making a required form field optional
so that I know how to add optional fields.

## Info
Content edits according to [content support ticket #69342](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69342)

## Tasks
- [x] Review support ticket 
- [x] New content will need to be written - an outline has been provided on the ticket.
- [x] Build draft of content.
- [x] Confirm where on the IA the content will live.
- [x] Confirm final content updates with Tommasina Miller, and/or, another SME.
- [x] Prepare page for deployment.
- [x] Deploy page to production.

## Acceptance Criteria

- [ ] Platform website will have updated instructions on how to make required form fields optional.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/69560?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by johnny-jesensky-adhoc** [comment]
Jill had some bandwidth, so pulling this into the current sprint today, **Wednesday, November 29th**.

**Comment by taylojill** [comment]
Replied to requestor via GitHub ticket asking for a link to current documentation she referenced.

**Comment by taylojill** [comment]
Sent follow up message to requestor via GitHub.

**Comment by taylojill** [comment]
Connected with requestor via Slack content channel, received link to current documentation. I'll review and provide updates on my progress.

**Comment by johnny-jesensky-adhoc** [comment]
Update on this ticket. We pulled this into the current sprint about midway through due to some extra bandwidth, but are still working through this. This ticket will be carried over into Sprint 42. 

FYI @jwoodman5, @taylojill

**Comment by taylojill** [comment]
Reached out to Micah Chiang and Matt Dingee via platform-content Slack channel requesting assistance. Michah is no longer maintaining the Confluence pages. Waiting for feedback from Matt.

**Comment by taylojill** [comment]
Reached out to the veteran facing forms team via their Slack channel. I asked if they knew who maintains the Platform web site pages related to the support request.

**Comment by taylojill** [comment]
Draft page sent to requestor via Platform content channel in Slack. Waiting for feedback.

**Comment by taylojill** [comment]
Content approved with one minor change. Page will be updated, moved to IA, reviewed for launch-blocking issues, and prepared for deployment.

**Comment by johnny-jesensky-adhoc** [comment]
Confirmed the [page](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-make-a-required-form-field) has been launched - moving this to _Done_. 

FYI @taylojill
