### ISSUE TITLE
FE/BE | Profile | Contact Information | Domo Metrics Errors

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#69598]
## Background
In Domo, contact-information is showing a high percentage of errors.  These errors are related to the `v0/user` endpoint which is called from different areas of the Profile.  Domo only shows error counts, but doesn't provide any details or reasons for the errors.

Related Slack thread - https://dsva.slack.com/archives/C909ZG2BB/p1699284663365349.
See this [domo data page for the source data ](https://va-gov.domo.com/analyzer?cardid=860591610) that feeds into the success vs failure card on the domo profile page. 
Followed up w [analytics team asking how we can share more details in our GA tracking](https://dsva.slack.com/archives/C1Q4294JJ/p1704470840645779). < w/an update to the data layer we'll be able to adjust the domo metrics

## Tasks
- [x] Compare metrics to Datadog to try and get more insight into what types of errors are occurring.
- [ ] ~Review findings with Samara and/or Michelle Dooley.~
- [x] update the event data layer, in the case of a failure pass the codes through to GA

## Acceptance Criteria
- [x] the data layer is updated and passing info back to GA

**Comment by mtcA6** [comment]
@tpharrison got some more information let me know if you can see this [in domo](https://va-gov.domo.com/kpis/details/860591610). I'll snag some time for us to chat about this list.

**Comment by tpharrison** [comment]
Thanks @mtcA6!  I can't see it and the "request access" button seems to be disabled...

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/653787/a6ad5cb6-75b7-4fef-9de7-efdb2ae7a62a)

**Comment by mtcA6** [comment]
hmm no worries, I can show you what they showed me yesterday and hopefully we can make a plan to submit a ticket and have some of those events removed (or maybe reclassified)

**Comment by tpharrison** [comment]
@mtcA6 Is there anything I need to work on?

**Comment by mtcA6** [comment]
@tpharrison nope I think we need Adam to update the ga events layer.

**Comment by adamwhitlock1** [comment]
I have a PR open that is being reviewed around adding some error keys to the user endpoint request events.

It should pass either vets-api based AND/OR downstream based error keys to GA so that we have better insight into failure events.

Since this is still in review I will roll it over to next sprint, but wouldn't roll over any points unless further changes need to be made after it is merged.

**Comment by adamwhitlock1** [comment]
<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFpDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39e010e909a25e3d0bb87f862c7fb289bb1c25c0/Screenshot%202024-02-08%20at%2011.35.36%E2%80%AFAM.png" alt="Screenshot 2024-02-08 at 11.35.36 AM.png" />


Errors are noiw being sent as the error-key on events. This is in the authd experience sandbox dashboard right now.

**Comment by mtcA6** [comment]
[Submitted the request to the analytics team for the update to the domo dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75886). Closing this ticket out
