### ISSUE TITLE
DR | Show appropriate error message for encrypted PDFs

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#69617]
## Value Statement
**_As a_** Veteran
**_I want to_** receive an appropriate error message if I am unable to upload evidence
**_So that_** I can take the appropriate action

---
## Background Context

When a Veteran uploads a password-protected PDF, the frontend checks if the PDF has a password and requests it before uploading the file to the backend. Once the backend receives the file and password, it attempts to decrypt and upload the file to an S3 bucket. We're getting the following error:

```
Warning: Using a password on the command line interface can be insecure.
Use the keyword PROMPT to supply a password via standard input instead.
Error: Invalid PDF: unknown.encryption.type.r
Error: Failed to open input PDF file:....
```

Which is when we discovered that the current library to unlock PDFs is not equipped to handle 256-bit encryption.

While the platform team investigates alternatives, we need to show an appropriate error message to the Veteran, so that they don't try to keep entering passwords in an attempt to unlock a PDF that we are not able to unlock. This content change will need to be _added to the backend_

Error messages needed:
- PDF decryption not supported 

## Design
- [Figma](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=429-21653&mode=design&t=b9emhxa9oFQc4NBR-11)
- Update inline error message.
- Additional information component added to page, with content as in design.

## Tasks
- [ ] Determine appropriate error messages, coordinate with CAIA
- [ ] Update error message in backend code
- [ ] Create PDFs for testing 
- [ ] Add appropriate error logging for Datadog

## Acceptance Criteria
- [ ] When a user uploads an encrypted PDF file, and the decryption is not supported, the user will see an inline error.
- [ ] The user is able to open the additional information component to see the evidence submission process by mail and fax.

## Out of scope
- Addressing errors caused by owner passwords on PDFs (covered by https://github.com/department-of-veterans-affairs/va.gov-team/issues/77776)

---
## Definition of Ready 
- [ ] Determine new error messages

## Definition of Done
- [ ] Error message appropriate to problem is shown to Veteran
- [ ] Successfully tested in staging
- [ ] Reach out to Veterans having this issue via Help desk

**Comment by saderagsdale** [comment]
Needs a backend dev to look at the library and make an assessment. May get answers from someone on the platform team (Can we decrypt or remove an owner password?)

**Comment by saderagsdale** [comment]
@anniebtran will timebox the effort to look at the error message and determine the cause so we can make it more actionable.

**Comment by eileen-coforma** [comment]
@saderagsdale @anniebtran is this something we still need, and is it related to the PDF errors or has this become a duplicate?

**Comment by saderagsdale** [comment]
I believe yes it is still a valid issue. @Mottie can you confirm if we're still using the library that cannot handle 256-bit encryption that was causing this?

**Comment by eileen-coforma** [comment]
I suggest a single error message for both errors, since the OWNER password is a very specific use case. Reviewing error language with CAIA on Tues 4:30ET to try and condense message.

**Comment by eileen-coforma** [comment]
Attached the design for the inline error message that's been approved by CAIA.

**Comment by Mottie** [comment]
Code changes merged in and available in staging. I made a recording...

![incorrect password entered showing the follow error message - We can’t unlock your PDF. Save your file without a password and try uploading it again.](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/33676767-b2f0-453b-afa5-17d9d55105cb)

**Comment by Mottie** [comment]
Additional changes are needed

**Comment by eileen-coforma** [comment]
Sent changes to Julie for async review. She said she'd get to it by 1PM today.

**Comment by HeatherWidmont** [comment]
PRs have been merged, ready to validate. Will validate in parking lot tomorrow
