### ISSUE TITLE
DR | Collect baseline data for outcomes

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#69616]
## Value Statement
**_As a_** product team
**_We want to_** measure our progress toward our desired outcomes
**_So that_** we know when to pivot or consider work complete.

---
## Background Context
- Our KPIs for various efforts live in Domo, DataDog, Google Analytics, and Sentry. Pulling them into a single view that we review regularly will strengthen our prioritization approach and help us spot signals to adjust our direction. 

## Acceptance Criteria
- [ ] We have a shared space to document and view success metrics
- [ ] We agree on how to fold this into prioritization and planning
- [ ] We have stakeholder alignment on approach

## Open questions
- How to get access to historical and current data for product hardening?
- Accessibility metrics?

## Tasks
- [ ] Assign team members to each "outcome"
     * Outcome 1: Product hardening (assignee: @anniebtran, @rocio-desantiago, @Mottie) 
     * Outcome 2: Accessibility (assignee: @davidakennedy)
     * Outcome 3: Connecting use cases (@rubensun @saderagsdale @eileen-coforma)
- [ ] Confirm which KPIs are available, and which need "massaging" (ex: qualitative KPIs)
- [ ] Qualitative KPIs only: determine how we might represent these (@rubensun @davidakennedy)

## Definition of Ready 

- [ ] Access to data
- [ ] Understanding of individual tasks

## Definition of Done

- [ ] Metrics have a public home
- [ ] Team has a cadence for reviewing and updating
- [ ] Reminders are baked into the process
- [ ] Stakeholder alignment

**Comment by saderagsdale** [comment]
@saderagsdale schedule huddles and write out data gathering tasks for each
