### ISSUE TITLE
DR | Build 3-month roadmap view

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#69629]
## Value Statement
**_As a_** product team
**_We want to_** see our discovery and development work in the near term
**_So that_** we can see where how current work (the mission) supports the vision.

---
## Background Context
- Some roadmap stakeholders are curious to see a view that helps them understand the pipeline a bit more intimately. Similarly, the team occasionally asks about priorities and how to know when things move. Some questions I've received include: 
     * How can I follow discovery more independently?
     * How can I understand what's transitioning from discovery into a priority?
     * How can I see when something might be launching soon?

## Acceptance Criteria
- [ ] We have a shared space to document and view our near term work
- [ ] We agree on what we would love to see, based on role
- [ ] We have stakeholder alignment on approach

## Open questions
- How do you reference a roadmap, and when do you seek it?

## Tasks
- [ ] Get feedback from each role
- [ ] Schedule a brainstorm / roadmap design challenge
- [ ] Get stakeholder buy-in

## Definition of Ready 

- [ ] Alignment on how to collaborate
- [ ] Understanding of individual tasks

## Definition of Done

- [ ] Roadmap has a public home
- [ ] Team has a cadence for reviewing and updating
- [ ] Stakeholder alignment
