### ISSUE TITLE
Services Impacted by COLA Tracking (Intent to File (0995, 526)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69628]
## Description 
Form tool investigation related to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69547). This ticket will cover investigating the service **Intent to File (0995, 526)**.

Overview: 

<i>The weekend of Saturday, November 18 – Sunday, November 19, 2023. The Cost of Living Adjustment (COLA) will be applied to Veterans Benefits Administration (VBA) Compensation Services and Pension & Fiduciary Services benefits. This will cause a down time for products on VA.gov that rely on VBA's database.

The following applications will be unavailable:

All applications that access the VBA Corporate database (includes BGS)
All applications that access the Benefits Delivery Network (BDN)
All Veterans Benefits Management System (VBMS) applications
All applications that use Common Security System (CSS) for login validation, such as Education
All access to the VBA Corporate database through Benefits Enterprise Portal (BEP) via web or Thick-Client application via Tuxedo</i>

---

## Definition of Done
All of the tasks are complete below.
---

## Tasks 
_Steps to reach definition of done._ 

- [x] Identify who owns the product, endpoint, feature, etc.
- [x] Identify if they use PagerDuty to manage maintenance windows
- [x] If yes, discuss with the product owner PM to determine the kind of maintenance window we need to create and 
   move onto the next item
- [ ] If no, move onto the next item
- [x] Maintenance Window Added and proof included in ticket

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
**Form, Tool, or Endpoint:** Intent to File (0995, 526)

**Expected Impact of COLA:** Intent to File will not be able to be retrieved or created

**Plan:** Trigger a manual maintenance window to indicate 526 and 0995 cannot be submitted

**Owner:** (placeholder)

**Do we have a maintenance window for this:** (placeholder)

**Comment by lindsay-insco** [comment]
[EVSS maintenance Window added](https://dsva.slack.com/archives/C8R3JS8BU/p1699893462043699) [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3ZWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0b0eb1abc9a0486800fb0cacca1587f0ca13186/Screenshot%202023-11-14%20at%204.43.37%20PM.png)

**Comment by lindsay-insco** [comment]
COLA VBMS Maintenance Window Slack Reminder [Here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700074598998649)

[VBMS Maintenance Window added](https://dsva.slack.com/archives/C064JKBD0N8/p1700074282175959)
![Screenshot 2023-11-15 at 1 44 59 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90409405/941774dd-77a9-4c7b-adf9-8fd486f437fd)

**Comment by lindsay-insco** [comment]
COLA BGS Maintenance Window Slack Reminder [Here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700074612976729)

[VBMS Maintenance Window added](https://dsva.slack.com/archives/C064JKBD0N8/p1700074282175959)
![Screenshot 2023-11-15 at 1 47 21 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90409405/a3109c1a-b4f1-40bd-8da5-346782f44530)

**Comment by lindsay-insco** [comment]
COLA BGS Maintenance Window Slack Reminder [Here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700074612976729)

[VBMS Maintenance Window added](https://dsva.slack.com/archives/C064JKBD0N8/p1700074282175959)
![Screenshot 2023-11-15 at 1 47 21 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90409405/a3109c1a-b4f1-40bd-8da5-346782f44530)
