### ISSUE TITLE
Update Insights Documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6963]
## User Story or Problem Statement
How might we update our documentation to alleviate single points of failure & personnel training ?

## Goal
Determine which documentation pieces need to be added & updated. Update and add as necessary.

---
## Tasks/Issues
_What work is necessary for this story to be completed?_
- [ ] Service Design interviews Nedie
- [ ] Update current VFS-facing GA/GTM GH Documentation
- [ ] Document what needs to be added
- [ ] Document internal implementation process
- [ ] Document current internal pain points

## Acceptance Criteria
With the goal of decreasing single points of failure:
- [ ] VFS teams understand how to communicate with Analytics on GTM & GA issues
- [ ] VFS teams can understand how to use GA at a high level
- [ ] VFS PMs/POs and FE engineers understand the GTM implementation process
- [ ] Analytics understands how to implement GTM and the entire process around implementation
- [ ] Analytics understands current GTM/GA pain points
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@nedierecel Priority Order for the attached issues are:

1. #7156 
2. #7157 
3. #7172 
4. #7161

**Comment by joanneesteban** [comment]
We can work simultaneously on each issue, but GTM is highest risk/value to be completed.

**Comment by joanneesteban** [comment]
Add #8745

**Comment by jonwehausen** [comment]
Closing.
