### ISSUE TITLE
Add Downtime Alerts Information to Maintenance Windows Documentation (VBA/COLA)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69632]
## Description 
This ticket will house the task of identifying if Downtime Alerts documentation has been added to this document: [Advanced Support Best Practices](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1).

_Note: This information is both in the [Advanced Support Best Practices](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1) (Platform Support) and [Create Maintenance Window in PagerDuty](https://vfs.atlassian.net/wiki/spaces/OT/pages/2434433157/Create+Maintenance+Window+in+PagerDuty) (Platform Infrastructure Team)'s spaces in Confluence._ 

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [x] Add downtime alert process to the documentation if it doesn't already exist
- [x] Clarify with Clint that we don't need any additional information for either maintenance windows or downtime alerts content
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
Confirmed downtime alert with Clint 

The ask is that there is a message alerting that a maintenance window is occurring. There is no way to automate this quickly on the Tier 1 side of things.

But Slack has scheduled message features that could be utilized to handle this ask. Maintenance window alerts can be posted in various spaces - #on-call being one big example.

**Comment by lindsay-insco** [comment]
Long-term there IS an API that may assist but just a few days may not be long enough to ensure this integration would work for the COLA outage https://developer.pagerduty.com/api-reference/4c0936c241cbb-list-maintenance-windows

**Comment by lindsay-insco** [comment]
There IS a way to populate downtime alerts for VFS and documentation is on the Platform site [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications)

I have updated the PagerDuty Maintenance Window instructions on Confluence [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2434433157/Create+Maintenance+Window+in+PagerDuty) that includes information on downtime alerts for VFS as well as internal Slack notifications for us as members of Support and all staff supporting these services.  I have posted these updates to Alyssa.

**Comment by lindsay-insco** [comment]
Passing to @alyssagallion

**Comment by alyssagallion** [comment]
Work completed. Closing!
