### ISSUE TITLE
Discovery spike: Document current UX for phone support options across VAgov and health portals

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#69656]
### User story

As a Veteran using health tools, I want to be able to easily find the right phone support number for issues I'm experiencing trying to manage my health on MHV-on-VAgov, so that I don't experience the frustration of calling the wrong support number or not even finding a support number.

As a VA health stakeholder, I want to understand how the existing "contact us" options on VAgov might be used to provide phone numbers for the various Help Desks, so that we can identify risks and make a UX plan to address them.

As a help desk stakeholder (MHV or Oracle), I want to ensure that Veterans can continue to easily find our contact number when they have problems, so that we maximize our chance to make the transition smooth for veterans and maintain high satisfaction.

As a non-health contact center stakeholder (e.g., VAgov, Benefits hotline, etc.), I want the VAgov UX to clearly convey which number a Veteran should call for a specific health-platform issue, so that my operations aren't disrupted by wrong numbers.

### Notes:
- We're not sure if the Help Desk is ready to support MHV users on VA.gov (vs the national portal)
- Oracle help desk doesn't seem to have a phone number listed on VAgov's Contact us page
- We don't know if Health leadership or the tools teams have plans around support
- Consider related "help" experiences across VAgov
- [team discussion](https://agilesix.slack.com/archives/C05PH6V3MJL/p1705082610219019) of how we might use a survey for user research

### Related resources
- [Journey map of help resources for Veterans on VA.gov (3 years old)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/bd02a6188674fa6a97aeef0c1cde8edb0fb718cd/products/iris/product/Get-Help-User-Journey-Mapping-notes.md) - could have some useful information
- [Health chat - notes (2 years old)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/bd02a6188674fa6a97aeef0c1cde8edb0fb718cd/products/facilities/medical-centers/discovery/health-chat-discovery.md) - could have some useful information
- Sara update in [slack](https://agilesix.slack.com/archives/C05PH6V3MJL/p1701463480833279): 
  - Per Mikki, there are lots and lots of "how to" and "guide" type documentation pages living in MHV National Portal, most will not be ported to VAgov
  -  not sure to what extent there is overlap between those resources and what the actual "HelpDesk" does when contacted. [Here is a sitemap of the MHV National Portal](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1682456995317/a093a3be3eca4c440897e4e7df14b0b603c437c4?sender=uf94a77a19aaf687331c09367), but note that this Mural hasn't been updated in 6 months, so the lower sitemap of the VAgov integration is not a source of truth.
- Per a SM research report from April 2022 (slide 22 in the PDF in [this slack thread](https://dsva.slack.com/archives/C062892HSAC/p1698942710769159)), "Participants did not know where to find help for messaging – Further exploration needed for navigating to the Resources and Support pages."
- Florence reached out to MHV help desk and documented her [findings in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/metrics-performance-monitoring/MHV-Helpdesk-data.md) – these are notes from a meeting with Robyn Singleton and Kophie Mathis
- Per [octo folks in auth/health space](https://dsva.slack.com/archives/C0581MN69TJ/p1704468600766739), this has not been thought about, but the default approach would be to ensure all the relevant numbers are available on the "Contact us" page

## Acceptance criteria

- [work-ahead?] Query Patrick and leadership about existing plan/understanding
- Documented existing Help desk/contact us UX on national portals
  - Findings of current UX can be [documented in this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704739824626/19b2ef8a0b5a072f695d0f9b7b55ea95a3be3b97?sender=uebde62ceb342c6477fb09406)
- Documented existing VAgov "Contact us" UX and gaps if we were to leverage as-is across transition from national portals  (same Mural)
- Obtained baseline analytics data for contact us pages on VAgov and national portals
- Shared findings with octo health stakeholders

## Tasks and working notes

- [x] query octo folk about known plans for help desk
  - [thread](https://dsva.slack.com/archives/C0581MN69TJ/p1704474682583049?thread_ts=1704468600.766739&cid=C0581MN69TJ)
  - pinged Samara in that thread, who is covering contact center during Chante's leave (thru 2/5); asked if anyone has discussed MHV transition's potential impact on existing VAgov contact center
- [x] document [in mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704739824626/19b2ef8a0b5a072f695d0f9b7b55ea95a3be3b97?sender=uebde62ceb342c6477fb09406) existing contact us/help desk UX across VAgov, MHV national portal, and My VA Health (Oracle) portal
- [x] Slack (Wes DMed) Patty Henry requesting top reasons Veterans call MHV help desk
- [x] request access to the MHV PowerBI dashboard (wes has access now; [My HealtheVet Analytics Dashboard Request Form (office.com)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DIxtf6a-r7kWCHberJRqzv-KbKKObK71KpYpxP335EsFUN0UwT1Q4WlFJUjNKN0szRllNUUdMRUZYNC4u&data=05%7C02%7C%7C2ffc6969134b4f96d55508dc1b803816%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638415484705490136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=axOOAMqhV0sCuQ6dA1JLtSgmTz%2F8bzMlVY5QD%2BPQRIs%3D&reserved=0) – NOTE: answer "no" to the question about whether you need access to PII)
- [ ] speculate on contact KPIs we might want to baseline 
- [ ] Synthesize info we're getting for team to work from:
  - current state – visuals in the mural
  - why Veterans call MHV help desk
  - insights into KPIs that are already being watched by MHV stakeholders
- [ ] reach out to help desk stakeholders for KPI baselines and about how they're preparing for transition, issues they anticipate (eg, Veterans calling the wrong help desk)
  - [ ] Patricia Henry – MHV help desk
  - [ ] Kelsi Hampton – My VA Health help desk
  - [ ] Kophie Mathis – help desk analytics/dashboard (PowerBI)
- [ ] Follow-up user story(s) written

**Comment by sterkenburgsara** [comment]
@wesrowe I think you're right that PRA is going to block us from a survey. But I will reach out to Robyn and think about other unmoderated methodologies we might be able to leverage.

**Comment by wesrowe** [comment]
planning: moving back to Ready, as transition KPIs will be higher priority this sprint (24)

**Comment by wesrowe** [comment]
closing this; team can reference it for #79258.

**Comment by wesrowe** [comment]
@fmccaf1, I just corrected the ticket above – it ended up being email (she didn't respond to slack), and I just forwarded it. her response was basically to pull Kophie in, and his dashboard had the data I was seeking (and more).
