### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Design & content QA changes

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#69651]
## Issue Description
Listing out any content/design/accessibility changes found in UX QA. 

- [Spreadsheet UX team working on](https://docs.google.com/spreadsheets/d/1PKSmgFvbhAEuUCqXa454i-pjkxZEykVQJ0MeJe7UYGQ/edit?usp=sharing)
- [Midpoint Review - Design MUST ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68457)

---
## Tasks
- [x] Intro page - unenrolled alert content updates - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/oM129z3)
- [x] Veteran Information page - note content - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/71AaWd7)
         - Note: If you need to update your personal information, call our VA benefits hotline at 800-827-1000 (TTY: 711).  We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
You can also call your VA health facility to get help changing your name on file with VA. Ask for the eligibility department. Find your nearest VA health facility.
- [x] Veteran mailing address & home address pages - additional info component content - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/elo2bEj) 
         - If you live on a military base outside the county, the United States is automatically chosen as your country.
         - This is also the same update in the Should Midpoint feedback [#68668](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68668)
- [x] More usability/QA bug - On the contact information page, there is not a required text label on the phone number field, but you can't continue without entering. Field error shows about valid phone number req.     
- [x] Dependent education page - small typo book should be books - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/1VLMz8k)
- [x] Dependent support page - small text edits, missing "any", lowercase s - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/5nY3O0y)
         - Missing "any" If your dependent didn’t live with you in 2022, did you provide any financial support?
Need to change to lower case S in support bold text
- [x] Dependents income page - Missing a "," after property in Net income label - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/bLoR4YV)
- [x] Review dependents page - remove link, red color - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/bLoR4YV)
- [x] Spouse income page - Missing a "," after property in Net income label - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/3obreaZ)
- [x] Private insurance page - Design MUST midpoint feedback, move intro sentence in add info out to page content - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/vRr8rR3)
- [x] Add policy page - Missing hint text in group code fields - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/x027D7A)
- [x] Insurance review page - Same issue with color of remove button to red - [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/r9wMw4a)
- [x] Review page - red error alert 

## Acceptance Criteria
- [ ] Items found listed under tasks corrected in staging
---

**Comment by katelyncai** [comment]
I'm still seeing "...call your VA medical center" (check box 2) on staging.

**Comment by longmd** [comment]
Just a couple notes here:

1. As noted in the midpoint review feedback ticket, the additional info for address is hardcoded in the forms library, so any content updates would need to go through them.
2. The alert for failed submissions is being handled with a BE fix and being tracked in another ticket there.

**Comment by longmd** [comment]
@jessicastump / @katelyncai , this list is ready to be validated. I have an additional pending fix coming for the list loop trigger question defaulting to 'Yes' after completing a record.

**Comment by jessicastump** [comment]
Awesome, thank you @longmd!! I will take a look through staging this afternoon.
Glad the list/loop yes question has a fix in too - this came up during our first research session today as an issue. :)

**Comment by longmd** [comment]
@jessicastump , I saw it as part of the thread you tagged me in. So yea... that is slightly separate from the list above, so when you see the tagged PR (26680) above marked as merged, itll be headed to staging.

**Comment by fbonds** [comment]
Re: "More usability/QA bug - On the contact information page, there is not a required text label on the phone number field, but you can't continue without entering. Field error shows about valid phone number req."

This is still occurring.

**Comment by jessicastump** [comment]
Trying to validate these and keep getting this error when trying to login. Using ID.me as I have always done previously.
![Screenshot 2023-11-13 at 2 54 46 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/c8d16503-4242-4991-b5fd-fb3a1337d832)

have tried restarting/updating/etc with no luck, will try again here in a few..

**Comment by longmd** [comment]
```

Re: "More usability/QA bug - On the contact information page, there is not a required text label on the phone number field, but you can't continue without entering. Field error shows about valid phone number req."

This is still occurring

```
RE: this one, we will track as part of #69778.

**Comment by jessicastump** [comment]
Was able to get logged in finally and through the form in staging and all the minor content/design edits are complete minus the one usability bug mentioned. This is complete. 
(Also was able to get to the confirmation page successfully this time too!!)
