### ISSUE TITLE
Refine Mockups for 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6965]
## Goal
There are a lot of moving parts in the 686 and one of the most important is content.  There are many places that have been suggested for "helper" text to be slotted in to help with form instruction and context.  These need to be added to the mockup so that FE can be notified to make adjustments

## Considerations
- Per ticket #6830, there might need to be some unification on button and breadcrumb content
- We need a gated landing page to establish/embed a Flipper component
- [Mockup index](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)

## Tasks
- [x] Confirm text, labels, etc. for 686/674 match mockups
- [x] Implement any incidental changes required by Content (Peggy Gannon)
- [ ] Implement changes per stakeholder feedback
- [x] Summarize a list of changes making them easy to track
- [x] The form title page on the intro page
- [x] The submission confirmation page
- [x] Share with the FE engineers

## Acceptance Criteria
- [x] A discrete list of changes (changelog on mockup index page maybe?) has been shared with the FE engineers to make adjustments as necessary

**Comment by sporeboy** [comment]
Worked on reconciling page titles (H1's), breadcrumbs, and IA URLs. Added table to research Readme.md here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/README.md

Mikki's assessment regardinging IA and URLs is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md

**Comment by sporeboy** [comment]
Created MD doc listing found changes here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0420.md

**Comment by sporeboy** [comment]
No feedback forthcoming from Peggy. No shareholder feedback to date. Incidental revisions/alignment with FE made.
