### ISSUE TITLE
FE/Design | USWDS v3 Component Migration | Alert Component

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#69667]
## Background 
As part of our work on [EPIC | Profile | Maintenance Period Alerts#68877](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68877) we determined that migrating the alert component might be a good first component to migrate / update using the new components 

## Tasks 
- [ ] update the alert components in all of the pages of the profile? should we go page by page here? do all of the pages have alerts? Is it ALL alerts or one specific type of alert? 
     - [ ] hub
     - [ ] personal info 
     - [ ] contact info 
     - [ ] personal health contacts (do we know if there are any alerts for this page or not yet because it's read only)
     - [ ] direct deposit 
     - [ ] military information 
     - [ ] account security 
     - [ ] connected apps 
- [ ] FE makes the updates
- [ ] During staging validation, the person doing the validation takes a screenshot and updates the contact center guide
- [ ] Once the updates are on production, design can update the Sketch files

## Acceptance Criteria 
- [ ] we have updated  the alerts in the UI, in Sketch, and in the Contact Center guide

**Comment by mtcA6** [comment]
@andaleliz @adamwhitlock1 pulled this together so we talk about it during next Wednesday's refinement. 

I have process concerns/doubts that I'm hoping you all can help me clarify since how we write the tickets will impact how you tackle the code adam and how we then handle the impacts to sketch and contact center guide.  
some additional thoughts I'm curious on are: 
- what sort of considerations we need to take for testing? 
- Do we go page by page or alert by alert to replace them? 
- do we need to call out which component we're replacing? < this might actually help me visualize what we're talking about here
- also, is this a case of ctrl+f and replace all the spots in the code where you find a specific alert type? < which i think i only care about this because I want us to write these tickets so we handle the component updates in manageable chunks so you don't have super massive PR's.

**Comment by andaleliz** [comment]
These are all great questions @mtcA6! Talking through them in refinement is a great plan. 

This might help you visualize what we're talking about, or at least have a better understanding in prep for refinement:
- `va-alert` is the current version of the alerts we have all throughout profile right now. [This is the default variety in Storybook](https://design.va.gov/storybook/?path=/docs/components-va-alert--default), but if you scroll down the page, or navigate via the sidebar on the left, you can see all the different flavors.  All alerts in profile use some kind of flavor of this alert.
- `uswds-va-alert` is the new version of the alert that we need to upgrade too.  [Here's a direct link to it,](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default), but if you scroll further down the left sidebar, you can see a section called **USWDS** at the bottom where all the components ready for upgrade are documented. 
- If you want to nerd out and play around, you can click on the canvas tab in the upper left (screenshot below) and mess with the toggles and see all the different properties available for the component. This is true for any component on the site.

<img width="977" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/3df036be-28b5-47fb-9843-39288f03962d">

**Comment by mtcA6** [comment]
changed course, going page by page now.
