### ISSUE TITLE
Services Impacted by COLA Tracking (COE/LGY submissions)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#69678]
## Description 
Form tool investigation related to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69547). This ticket will cover investigating the service **Intent to File (0995, 526)**.

Overview: 

<i>The weekend of Saturday, November 18 – Sunday, November 19, 2023. The Cost of Living Adjustment (COLA) will be applied to Veterans Benefits Administration (VBA) Compensation Services and Pension & Fiduciary Services benefits. This will cause a down time for products on VA.gov that rely on VBA's database.

The following applications will be unavailable:

All applications that access the VBA Corporate database (includes BGS)
All applications that access the Benefits Delivery Network (BDN)
All Veterans Benefits Management System (VBMS) applications
All applications that use Common Security System (CSS) for login validation, such as Education
All access to the VBA Corporate database through Benefits Enterprise Portal (BEP) via web or Thick-Client application via Tuxedo</i>

---

## Definition of Done
All of the tasks are complete below.
---

## Tasks 
_Steps to reach definition of done._ 

- [x] Identify who owns the product, endpoint, feature, etc.
- [x] Identify if they use PagerDuty to manage maintenance windows
- [ ] If yes, discuss with the product owner PM to determine the kind of maintenance window we need to create and 
   move onto the next item
- [x] If no, move onto the next item

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by jknipes** [comment]
- **who owns the product, endpoint, feature, etc**: Submissions go through LGY service, no direct impact
- **do they use PagerDuty to manage maintenance windows**: Yes
