### ISSUE TITLE
Copy of ARM 21-22 Form - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#69680]
## Issue Description

Veteran user test of 21-22 form flow.

## Tasks
- [x] Create GitHub research folder
- [x] Create research plan
- [x] Define screener questions
- [x] Create conversation guide
- [ ] Submit all materials to team for review
- [ ] Create ZenHub ticket for revisions

## Acceptance Criteria
- [ ] All materials complete and ready for team review

**Comment by jfinnerty13** [comment]
Blocked until prototype is complete

**Comment by jfinnerty13** [comment]
https://drive.google.com/drive/folders/1uwJYxglqTTLY87l4YDYsCw3bT0qdtHUO?usp=drive_link

**Comment by jfinnerty13** [comment]
Sent to team for review, comments due 12/01
https://dsva.slack.com/archives/C05L6HSJLHM/p1701111672554759

**Comment by jfinnerty13** [comment]
https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/450
Ready to submit for research review Monday
