### ISSUE TITLE
[Analytics] Identify where largest drop off is within the 45MR flow

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69699]
## Problem

Dig into understanding why there's a bigger % of Veterans not completing check in with the 45MR vs. the text "check in" method. Whether it's in GA or DD, we should figure out if it's related to something specific we see in the data.

E.g., a pure hypothesis, "if Veterans are attempting online check in for the first time now via the 45MR, and therefore, might not have completed pre-check-in either, and answering "No" to their demos during check in, is there something we can do in the pre-check-in SMS notification and pre-check-in LoROTA verification page content to better communicate the value-prop to Veterans of completing pre-check-in, so their next check in has a better chance of completion. If the data about check in points to people not completing demos in the 45MR, then we really need to emphasize the benefit/value in pre-check-in to Veterans." Again, this is a pure hypothesis. 

We need to find some time to dig into where Veterans are dropping off the most (focus on that) during the 45MR workflow after their identify verification. E.g., could be demos, could be travel, could be when Veterans see travel w/o demos, etc.

[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1699471299755309)

[Most recent data from Slack thread that shows % success rate drop off](https://dsva.slack.com/archives/C022AC2STBM/p1699547847158239?thread_ts=1698076388.436609&cid=C022AC2STBM) 

## Tasks

- [ ] Identify where largest drop off is within the 45MR flow
- [ ] Identify potential solutions to increase % completion 
- [ ] Select a solution
- [ ] Create implementation (ux, engineering, etc.) tickets

**Comment by benbrasso-agile6** [comment]
Will do one more look to see what data I can pull. 

The end result of this ticket (after talking to Brian) will probably be creating a ticket to get more information logged in DataDog, which I can spell out.

**Comment by benbrasso-agile6** [comment]
So, in chatting with @brianseek for a few days now, our best option(s) are to 1) identify what we're looking to track, and then, 2) implement the work needed to surface that information. And, since a national rollout is approaching, this will become much easier since filtering the data, currently, by station in DataDog has proved problematic. 

Here is a draft that we'll want to review together to ensure that, 1) it's capturing what we need (which at a high level is, how many start the eCheck-in process from a 45MR, how many complete the eCheck-in process from a 45MR, and of those who don't complete the process from a 45MR, what was the reason), and 2) that the data points listed below are categorized under the appropriate tracking tool. E.g., right now, the check in team does not have write access to the VeText DataDog instance. 

- VeText Dasboard
     - How many 45MR were sent? 
     - How many notifications were sent with a link from texting "check in"? 
     - How many system error notifications were sent? 
- Tevi (CHIP) Dashboard
     - How many check in links were selected? 
     - How many check in links were selected and too early? 
     - How many check in links were selected and too late?
     - How many times did insurance need to be reviewed?
     - How many times was a phone number not found? 
     - How many times were there no appointments found?  
     - (Are there any other errors that aren't currently being logged in Google Analytics? Or are any of these currently being tracked as errors already in Google Analytics?) 
- Google Analytics
     - How many times did someone start ID verification from a 45MR? From texting "check in"? 
     - How many times did someone succeed ID verification from a 45MR? From texting "check in"? 
     - How many times did someone fail ID verification from a 45MR? From texting "check in"? 
     - How many times did someone succeed (API check in request) in a check in from a 45 MR? From texting "check in"? 
     - How many times did someone fail (API check in request) in a check in from a 45 MR? From texting "check in"? 
     - How many times did someone select No to contact info for 45 MR? From texting "check in"? 
     - How many times did someone select No to emergency contact info for 45 MR? From texting "check in"? 
     - How many times did someone select No to NOK info for 45 MR? From texting "check in"?      

@loripusey once you've had a chance to review this, what I'll do is set up a meeting with you, me, Kay, Kristen and Brian to agree on these information. Or, we can do it at next Priorities meeting. 

We may also consider t-shirt sizing these efforts. For example, the Google Analytics one might provide the most value, and be the most feasible. 

Moving this into Validate.

**Comment by benbrasso-agile6** [comment]
The reality is (over the last 30 days) that of the [21,896 successful eCheck-in ID verifications](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22API%20Request%20-%20day-of-validating-user-.*%20-%20success%22,0%5D%5D/), [88% successfully check in](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22API%20Request%20-%20check-in-user%20-%20success%22,0%5D%5D/) (i.e., vets-api check in call is success).

**Comment by loripusey** [comment]
> How many system error notifications were sent?
Unless we further define this, is it really helpful?

> How many times did insurance need to be reviewed?
> How many times was a phone number not found?
> How many times were there no appointments found?
Don't these  need to be done at the VeText level?

My question is, don't we have most or all of these metrics in place? Isn't the problem that they are not all located in the same product (GA vs DD)?

@benbrasso-agile6 I'd like for us to meet first and put this in a format where we can evaluate if we already have the measure and where it's located. Also, a format that is easier for Kay to look at.

**Comment by loripusey** [comment]
@benbrasso-agile6 also, we have catalogued our reasons for not completing check-in or pre-check-in in this [spreadsheet](https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=1014412992); maybe this will help

**Comment by loripusey** [comment]
validated, closing, will create f/u tickets as needed
