### ISSUE TITLE
Services Impacted by COLA Tracking (Supplemental 0995 submissions)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69707]
## Description 
Form tool investigation related to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69547). This ticket will cover investigating the service **Supplemental 0995 submissions**.

Overview: 

<i>The weekend of Saturday, November 18 – Sunday, November 19, 2023. The Cost of Living Adjustment (COLA) will be applied to Veterans Benefits Administration (VBA) Compensation Services and Pension & Fiduciary Services benefits. This will cause a down time for products on VA.gov that rely on VBA's database.

The following applications will be unavailable:

All applications that access the VBA Corporate database (includes BGS)
All applications that access the Benefits Delivery Network (BDN)
All Veterans Benefits Management System (VBMS) applications
All applications that use Common Security System (CSS) for login validation, such as Education
All access to the VBA Corporate database through Benefits Enterprise Portal (BEP) via web or Thick-Client application via Tuxedo</i>

---

## Definition of Done
All of the tasks are complete below.
---

## Tasks 
_Steps to reach definition of done._ 

- [x] Identify who owns the product, endpoint, feature, etc.
- [x] Identify if they use PagerDuty to manage maintenance windows
- [ ] If yes, discuss with the product owner PM to determine the kind of maintenance window we need to create and 
   move onto the next item
- [x] If no, move onto the next item
- [x] Maintenance Window added

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
**Form, Tool, or Endpoint:** 526 Submissions

**Expected Impact of COLA:** Users will be stuck at the ITF point in the flow

**Plan:** Team is working on creating a feature flag for this downtime. Maintenance Window will be created for VBMS, BGS, and EVSS

**Owner:**  526 Submissions
[#benefits-disability](https://dsva.slack.com/archives/C04KW0B46N5)


[Primary Conversation](https://dsva.slack.com/archives/C053U7BUT27/p1699551424173949) regarding ownership and maintenance windows for 0995, 526 Intent to File, 526 Submissions

**Do we have a maintenance window for this:** From conversation in the slack thread above, they're discussing implementing a feature toggle for this outage. To err on the side of caution maintenance windows will be created for VBMS, BGS, and EVSS.

**Comment by lindsay-insco** [comment]
[EVSS maintenance Window added](https://dsva.slack.com/archives/C8R3JS8BU/p1699893462043699) 
![Screenshot 2023-11-14 at 4 43 37 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90409405/88b36f3b-3577-4062-a91c-41c5a51f70b5)

**Comment by lindsay-insco** [comment]
COLA VBMS Maintenance Window Slack Reminder [Here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700074598998649)

[VBMS Maintenance Window added](https://dsva.slack.com/archives/C064JKBD0N8/p1700074282175959)
![Screenshot 2023-11-15 at 1 44 59 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90409405/941774dd-77a9-4c7b-adf9-8fd486f437fd)

**Comment by bdech** [comment]
BGS Maintenance Window Slack Reminder [Here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700074612976729)[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e9b8bbad2828075fbafd3e09fc0b6a6b410b418/image.png)
