### ISSUE TITLE
Services Impacted by COLA Tracking (526 Submissions)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69704]
## Description 
Form tool investigation related to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69547). This ticket will cover investigating the service **526 Submissions**.

Overview: 

<i>The weekend of Saturday, November 18 – Sunday, November 19, 2023. The Cost of Living Adjustment (COLA) will be applied to Veterans Benefits Administration (VBA) Compensation Services and Pension & Fiduciary Services benefits. This will cause a down time for products on VA.gov that rely on VBA's database.

The following applications will be unavailable:

All applications that access the VBA Corporate database (includes BGS)
All applications that access the Benefits Delivery Network (BDN)
All Veterans Benefits Management System (VBMS) applications
All applications that use Common Security System (CSS) for login validation, such as Education
All access to the VBA Corporate database through Benefits Enterprise Portal (BEP) via web or Thick-Client application via Tuxedo</i>

---

## Definition of Done
All of the tasks are complete below.
---

## Tasks 
_Steps to reach definition of done._ 

- [x] Identify who owns the product, endpoint, feature, etc.
- [x] Identify if they use PagerDuty to manage maintenance windows
- [ ] If yes, discuss with the product owner PM to determine the kind of maintenance window we need to create and 
   move onto the next item
- [x] If no, move onto the next item

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
**Form, Tool, or Endpoint:** 526 Submissions

**Expected Impact of COLA:** Intent to File will not be able to be retrieved or created

**Plan:** Trigger a manual maintenance window to indicate 526 and 0995 cannot be submitted. Platform support is creating Maintenance windows for VBMS, BGS, and EVSS
https://dsva.slack.com/archives/C04KW0B46N5/p1699886400323929

**Owner:** 
**526:** [#benefits-disability](https://dsva.slack.com/archives/C04KW0B46N5)

**Do we have a maintenance window for this:** Yes

**Comment by bdech** [comment]
duplicate to https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/69674
