### ISSUE TITLE
[Content] [Design] Update content in Review page wireframe to coincide of eCheck-in production userflow

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69713]
## Tasks

- [x] Update content for [Review page wireframe](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/F298E098-2FFD-460E-9B8A-C46F4A54EB99/canvas#Version) to coincide of eCheck-in production userflow
- [x] Create new Page under Features in Check in Sketch file and add wireframes

https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/B528AED2-D251-4879-9081-673DEAFDB0F1/canvas#Version

Userflow - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/0157CB5C-B33B-4324-B375-AC686EFA3B4A/canvas#Version

## Acceptance Criteria
- [ ] Does CAIA need to review? 
- [ ] Does platform design need to review? 
- [x] Does UX team review? 
- [ ] Does check in team need to review via Slack?  
- [ ] Do VA OCTO PO's need to approve? 
- [x] Does Lori need link for FE?

**Comment by benbrasso-agile6** [comment]
https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/B528AED2-D251-4879-9081-673DEAFDB0F1/canvas#Version

Going to move this into Validate
