### ISSUE TITLE
[Research] Registration Reasons Tree Test - Monitor Study & Synthesis

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#69718]
## Issue Description
The unmoderated tree test study will need to be monitored while it is open, sending participant ID codes to Perigean via Slack at the end of each business day.
The synthesis will included downloading artifacts from Optimal Workshop and conducting synthesis.

---
## Tasks
- [x] Have Kick off call with Perigean
- [x] Conduct pilot study
- [x] Send codes to Perigean each day once study begins
- [x] Download necessary doc from Optimal Workshop study
- [x] Complete research findings summary doc
- [x] Create presentation doc

## Acceptance Criteria
- [x] Tree test is complete, findings synthesized and artifacts created - this is ready for team review
---

**Comment by jessicastump** [comment]
Registration tree test:
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1700003975101/6149b2a464425891624dd5bd0508b70164fa0920?sender=uadf1ed7fe7c76f0914967329)
- [Findings doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-11-Registration%20Reasons%20Tree%20Test/research-findings.md)
- [Presentation deck](https://docs.google.com/presentation/d/12bAdo_7uoi1ab7n2tnmaed01RFbMMuYtZub-IdAGvtU/edit?usp=sharing)

@hdjustice / @aagosto90  
Thoughts/edits/typos/etc on the presentation deck before I download a PDF for github?

Next steps: PO/PM research readout and workshop session. Thinking we can open these as a new ticket and close this one?

**Comment by jessicastump** [comment]
Going to close this and have opened the [ticket to share synthesis and next steps](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71805). Feel like we have spent more than 8 story points of work on this so far ;)
