### ISSUE TITLE
Update Screenshot security section of Style Guide

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#69724]
## Description
While writing the Tip of the Sprint, we noticed that the [style guide section on screenshot security](https://vfs.atlassian.net/wiki/spaces/AP/pages/1806172307/Images+videos+and+other+media#Other-image-tips) instructs users to black out PII by creating a box over it with 100% opacity. But it doesn't give further instructions. As a team, we need to brainstorm to come up with the best advice to give users. 

- Do we provide detailed instructions on who to black-out info? 
- Do we link to instructions on how to do that? 
- Or do we alter the instructions to advice some other option for eliminating PII? 

Once we agree on the advice, we need to draft that advice. Then we need to get approval on the wording from the entire team. Then we need to update and post the changes. 

## Tasks

- [x] Agree as a team on what changes need to me made.
- [x] Draft changes
- [x] Get team approval on final wording of changes
- [x] Update the style guide with the team-approved changes. 

## Acceptance Criteria

- [x] Style guide has been updated.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/69724?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
Changes have been made: https://vfs.atlassian.net/wiki/spaces/AP/pages/2904359061/How+to+hide+Personal+Identifying+Information+PII+in+an+image

Waiting on Team Approval to Close ticket.

**Comment by johnny-jesensky-adhoc** [comment]
Moving this to Done, per discussion in SU today.

FYI @jknipes
