### ISSUE TITLE
Action items from Forms Dig. feedback

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#69726]
## Purpose
We need to use the feedback from our session w/ the PO to tweak the research clarity or context.

Notes from meeting:
[Taylor](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2833088532/PO+Feedback+Session+11+9+23) - includes approach and next steps
[Bryan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2832629892/Notes+Form+Dig.+DI+Artifacts+review+w+PO)

## Tasks
- [x] scope out how to obtain the needed data
- [x] [send outreach to participants to gather data](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2844000325/Guerilla+Outreach+Maturity+Model)
- [x] [build a maturity model](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1701210475637/ad34b783b6fa6f6f72dbad3e7d6421ed398a2278?sender=u9ea6bd3ca12795949b606150)
- [x] incorporate into [recommendations doc](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2805596168/Recommendations+for+Digitizing+Forms)
- [x] incorporate into [best practices mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1698704140241/b26184fddc093987f7303a7157541f0e03139768?sender=u9ea6bd3ca12795949b606150)

## Acceptance Criteria
- [x] SDT has reviewed
- [x] the recommendations doc can show when work between new and old teams is being addressed
- [x] the best practices mural can show who we might make changes for: newer or older employees

**Comment by tayism** [comment]
Rolling over to the next sprint due to needing a bit more time for data gathering.
