### ISSUE TITLE
[MVP] Template card

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69723]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 

As shown on the designs

## Designs
- 

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work
- [ ] Back-end work

## Review
- [ ] Designer has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

```[tasklist]
### Tasks
```
