### ISSUE TITLE
Collaboration Cycle for [Veteran Status, Veteran Status MVP Page]

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#69732]
### VFS team name

Veteran Status

### Product name

Veteran Status card

### Feature name

MVP page

### GitHub label for product

veteran-status-card

### GitHub label for feature

n/a

### Public DSVA Slack channel for VFS team

veteran-status

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Team kickoff was 10/19

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-status/product.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kicckoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/CBU0KDSB1/p1699634568272229)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] User flow (required). https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1700074189128/bcb1173e855a57794c63cd57bebd1ee87eae32d0?sender=ud143866fd5369378295a0267
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes. https://www.figma.com/file/UwSvhj9Yn5trM5L5W3UgH0/VA-Status---Wireframes?type=design&node-id=86-446&mode=design&t=DAECCmixYsW0EwSR-0
- [ ] Research plan
- [ ] Product Outline. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-status/product.md
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C061RNJQ6SE/p1700066863130229)
- [x] Meeting date/time: Monday, November 20, 2023, at 3:30 p.m. Eastern
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [ ] Feedback ticket attached
  * [x] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/JXXn9gtceVqopgJgXP2yjY_gUMsEXMuyk0LL7uAAW1bRGPY2Joa6CKLKORAaTHK5.MtIVmka1O6fdSfJ4
  - Passcode: SC2#Pmvb
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] Finalized design prototype or mockup
https://www.figma.com/file/UwSvhj9Yn5trM5L5W3UgH0/VA-Status---Wireframes?type=design&node-id=793-4306&mode=design&t=zvoqdoV4Wk9itUER-4
- [x] Specify which pages are included in the review 
Only the mockup titled "Option 1- all content" and the card image next to it are relevant.
- [x] Research plan
https://github.com/department-of-veterans-affairs/va.gov-team/blob/b894fb6b78ddf63492cf38e65ac0e0627017984e/products/veteran-status/Research/2023-12-VetStatus-Use-Case-Discovery/2023-12-Research-Plan.md
- [x] Conversation guide
 https://github.com/department-of-veterans-affairs/va.gov-team/blob/b894fb6b78ddf63492cf38e65ac0e0627017984e/products/veteran-status/Research/2023-12-VetStatus-Use-Case-Discovery/2023-12-ConversationGuide.md
- [x] Dynamically generated PDF sample (with mock user data) -  [Veteran_status_card.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13954849/Veteran_status_card.pdf)

**Content artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/70681

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C061RNJQ6SE/p1705078815565649)
- [x] Meeting date/time: Monday, January 22, 2024, at 3:30 p.m. Eastern

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [ ] Feedback ticket attached
  * [ ] No feedback
* Design
  * [ ] Feedback ticket attached
  * [x] No feedback
* IA
  * [x] #74180
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/Ye9OtOxsDiYT0HaDanqxVUl6HBUQuzUz0T9Bvh7amWyPMTcxdHOmvghGyT0OAeaX.XYz3MyENWS78rRMG)
  - Passcode: +Dd*4+fC
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [X] Staging URL
https://staging.va.gov/profile/military-information
- [X] Specify which pages are included in the review           
Profile/Military Information page (including download and print modal, app store preview links)
- [x] Staging test user information         
[Staging test user accounts](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-Veteran-Status.md)
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [X] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/70681
  
**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/70681

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)

[Copy of Regression VS.1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14112763/Copy.of.Regression.VS.1.docx)

- [x] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
[Test cases VS.2.1.1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14141718/Test.cases.VS.2.1.1.docx)

- [ X] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)

-100 percent.  The 9 Use Cases documented and executed in the testing plan cover all user stories.

- [ x] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)

2 defects were identified by running test scripts.  Both were instances where text on the page did not match the text in the mockup, as identified below:
a. Test scenario 4 
Mockup calls for Veteran status” in Mobile callout header but page displays “Veteran Status”
Resolution: update code so that page matches mockup.  This defect was resolved by ticket https://app.zenhub.com/workspaces/veteran-status-6526f98f141b6f0ed1e059c4/issues/gh/department-of-veterans-affairs/va.gov-team/75056

b. Test Scenario 7
Mockup calls for “Periods of Service” but card displays “Period of Service”, even when 2 are displayed.
Resolution: team determined singular matches the existing header on Military Information.  No code change needed, updating mockups.

- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
[Veteran Status component e2e tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/tests/e2e/proof-of-veteran-status/proof-of-veteran-status.cypress.spec.js)
[Existing Military Information error handling tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/tests/e2e/military-information/military-information-api-error.cypress.spec.js)

- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage)
Ran locally, see screenshot below (note: some functions/branches are tested elsewhere in the codebase)  
<img width="100%" alt="Screenshot 2024-01-26 at 1 09 26 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72234279/1ad98f27-3d9b-4069-aa5c-e2d7906b13c8">

**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

Link to [Accessibility Testing issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74715)
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C061RNJQ6SE/p1706298522370859)
- [x] Meeting date/time: February 2 at 2pm ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/qCCqwaF1_cNCRKhXahhMDhwhPBpskZuy_sbiLGk7yow1LcpP5ktCRToloKjp5ukr.sd0wmb2FaBQoD413)
  - Password: `Pa3ei?#5`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by matt4su** [comment]
[Design Intent Veteran Status.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13417047/Design.Intent.Veteran.Status.pdf)

**Comment by matt4su** [comment]
Hi team, shortly after our MidPoint review session a stakeholder discussion resulted in a small change.  The DD214 component was moved back up the page between Periods of service and Veteran status.  Note this positioning change is aligned with IA feedback provided by Erin after our midpoint review session.  Mocks are updated in the Midpoint Review section and are also here for your reference.  https://www.figma.com/file/UwSvhj9Yn5trM5L5W3UgH0/VA-Status---Wireframes?type=design&node-id=793-4306&mode=design&t=zvoqdoV4Wk9itUER-4
