### ISSUE TITLE
[Epic] COVID-19 My VA alert: Get alert about health chat onto the dashboard for patients in VISNs 8 and 23

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#6974]
## Background

We need to show an alert that links patients to an existing VA health chat tool on the My VA dashboard. This alert should only show for patients with access to this tool, which is currently patients that go to hospitals in VISNs 8 and 23 (VISN = Veterans Integrated Service Network = essentially a group of VA hospitals).

## Tasks

- [x] FE: Investigate how we can determine which hospitals a VA.gov user goes to #6975
- [x] Mock up alert for the dashboard #6976
- [x] Build alert for the dashboard #6977
- [x] Remove VISN 8 from My VA health chat alert #7179
- [x] Launch to prod #7108
- [x] Analytics tracking for the health chat alert on My VA #7478
- [x] Implement analytics tag for My VA health chat alert #8033

## Acceptance criteria

- [x] The alert is live on the VA.gov My VA dashboard for patients in VISNs 8 and 23.
