### ISSUE TITLE
Use AWS OIDC instead of AWS secrets for GHA

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#69741]
### Summary
Use OIDC instead of AWS secrets in vets-api. This gets us away from storing these sensitive values in GH secrets. Ask @ph-One for pointers, if necessary. But first, read through [this Slack thread](https://dsva.slack.com/archives/C04CYC4LMU6/p1699970664394349).

### Tasks
- [ ] configure IAM Role to allow a repo to use OIDC to authenticate and use the role
- [ ] add that Role's ARN to the repo's Action Variables
- [ ] Update the workflows in vets-api that use `${{ secrets.AWS_SECRET_ACCESS_KEY }}` and `${{ secrets.AWS_ACCESS_KEY_ID }}`. (Similar to what is done in https://github.com/department-of-veterans-affairs/devops/pull/13615 and https://github.com/department-of-veterans-affairs/devops/pull/13718.)
- [ ] Delete secrets that were removed in above step from here: https://github.com/department-of-veterans-affairs/vets-api/settings/secrets/actions

**Comment by Mandalorian-Oddball** [comment]
Modified OIDC patterns and created policy. 
Tests failed. Troubleshooting GHA tests.

**Comment by JoeTice** [comment]
SPRINT 45 UPDATE: In Progress - Working on troubleshooting failing GHA tests, Keenan is moving to support this upcoming sprint, so this task will be moved to the Backlog and considered for resumption in Sprint 47
