### ISSUE TITLE
[FE] COVID-19 My VA alert: Investigate how we can determine which hospitals a VA.gov user goes to

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#6975]
## Background

Epic #6974

We need to show an alert that links patients to an existing VA health chat tool on the My VA dashboard. This alert should only show for patients with access to this tool, which is currently patients that go to hospitals in VISNs 8 and 23 (VISN = Veterans Integrated Service Network = essentially a group of VA hospitals).

Currently, we are pretty sure there is a way to determine which hospital(s) a VA.gov user goes to, but we aren't sure of the specifics around this. We need technical discovery to determine how we will access and consume this information.

- If this is up-to-date and accurate, [this is the list of facilities with access to this tool](https://mobile.va.gov/app/va-health-chat).

## Tasks

- [x] Talk to VAOS team about how we can determine at which hospital(s) a VA.gov user is a patient
- [x] Determine whether its just facilities in the list provided or if it also includes other facilities within the VISN's  (this is to be done by Samara first)
- [ ] (maybe) Look into what we can get from MVI

## Acceptance criteria

- [x] We know how we will determine at which hospital(s) a VA.gov user is a patient, and we know how we can consume this data in order to only show the My VA alert to patients in VISNs 8 and 23

**Comment by erikphansen** [comment]
We get a list of facilities a veteran is a patient at with our standard `GET user` call. The data is in `data.attributes.vaProfile.facilities`. This feature is fairly new but live in production

example:
```
"facilities": [
          { "facilityId": "983", "isCerner": false },
          { "facilityId": "984", "isCerner": false },
          { "facilityId": "200MHS", "isCerner": false },
          { "facilityId": "200ESR", "isCerner": false }
        ]
```

Note that those last two facilities are not facilities and will be removed when [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4021) is merged. It also won't affect what we need to do anyway.

**Comment by Samara-Strauss** [comment]
Update: I received confirmation from our stakeholder that we should show this alert only to veterans who are patients at the facilities listed on this page https://mobile.va.gov/app/va-health-chat. We do not need to use any other lists out there for VISNs 8 and 23. I was told that the longer list I sent along for comparison included facilities that weren't actually health care facilities (and therefore don't have access to the health chat tool). Please let me know if you have any questions about this!

**Comment by Samara-Strauss** [comment]
@erikphansen — we just found out that the health chat tool is staffed at different times in the different VISNs:

- VISN 8: 8:00 a.m. to 4:00 p.m. Monday through Friday
- VISN 23: 7:30  a.m – 4:30 p.m Monday through Friday

What I'm wondering: would it be possible to show the time/availability in the alert dynamically? So we could detect someone's parent facility and then based on that, show the times above? Let me know how easy/hard this would be and we can figure out how we want to proceed forward.

**Comment by erikphansen** [comment]
I'm not sure. There are supported facilities on this page (https://mobile.va.gov/app/va-health-chat) that are in Georgia, PR, and the Virgin Islands. Are those all part of VISN 8, because according to this page (https://www.ruralhealth.va.gov/contactus/visn.asp) VISN 8 is only Florida.

Are those times local? Or ET?

**Comment by Samara-Strauss** [comment]
> I'm not sure. There are supported facilities on this page (https://mobile.va.gov/app/va-health-chat) that are in Georgia, PR, and the Virgin Islands. Are those all part of VISN 8, because according to this page (https://www.ruralhealth.va.gov/contactus/visn.asp) VISN 8 is only Florida.

Ugh, the older pages on VA.gov are definitely not up to date/consistent. VISN 8 does include some facilities in Georgia, Puerto Rico, and the Virgin Islands, so we are good. https://www.va.gov/directory/guide/region.asp?ID=1008

> Are those times local? Or ET?

- Local times

**Comment by erikphansen** [comment]
Okay I can make this work. Now that we're adding in these testing facilities with IDs 983 and 984, I guess I'll just treat those as VISN 8? ¯\_(ツ)_/¯  I guess that doesn't matter much either way.

**Comment by Samara-Strauss** [comment]
Great, awesome. Thanks for helping to get this tracked down!

**Comment by Samara-Strauss** [comment]
Done! Alert is on staging/on prod behind a feature flag. We'll launch it when we get the go-ahead from our stakeholders.
