### ISSUE TITLE
Prepare VA Notify Trigger and build notification code to send by 2/21 (tentative)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69766]
## Issue Description
_The VA Notify team requests a trigger that will initiate the notification email we will need to send to Veterans with in-progress pension claims, once we release to 100% of traffic. The emails will notify Veterans with in-progress claims that the digital forms has been reactivated._

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
---
## Tasks
- [x] Verify your VA Notify platform access. [Instructions on this can be found here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify).
-- Access was provided to Matt, & Todd
- [x] Review VA Notify API docs (This [link](https://staging.notifications.va.gov/developer/api_docs) was in the VA Notify Playbook, but it's broken!)

- [x] Build notification code to call the VA Notify API for the pension form. We may be able to leverage Thomas Blackwell for insight/experience.
   - [x] Notification should trigger an email to all users who have an in-progress (started **_but not submitted_**) 527 form.
   - [x] The default email address should be the email the user entered into the 527 form. If no email exists within the form, use their MyVA profile email.
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Nice-to-have: Identify universe of users that will be notified, so we can understand:
   - How many in-progress users we expect to notify for pension
   - How many users entered an email address into the form.
   - How many users did not enter an email address into the form. We may have to investigate if we can use the email address entered into their MyVA profile as an alternative.

## Acceptance Criteria
- [ ] A notification trigger that sends an email to users with in-progress pension 527 forms.

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/69766?planning-poker) with Zenhub @mjknight50 @ToddWebDev

**Comment by vbellissimo** [comment]
@mjknight50 , as an FYI, here is the email copy already drafted in VA notify:

(the draft is here in VA Notify: https://staging.notifications.va.gov/services/725bbdd4-5a6e-4688-8678-fae4323ef3a3/templates/aef34a57-0eb9-4df2-80df-206dac6d4e65?templateSaved=true)

cc @katherine-fung @buddhima-coforma

**Comment by mjknight50** [comment]
Here is some code that Thomas's team used for this:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/pensions/in-progress-forms.md

**Comment by mjknight50** [comment]
From Steve Albers, VA Notify doesn't give feedback on success/failure since it is async.  He recommends something like this to determine that:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/shared_notes/vanotify-callback-notifications.md

**Comment by danlim715** [comment]
> From Steve Albers, VA Notify doesn't give feedback on success/failure since it is async. He recommends something like this to determine that: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/shared_notes/vanotify-callback-notifications.md

@mjknight50 They should be able to view the status of async jobs using the sidekiq dashboard. Is sidekiq not sufficient for their needs?

**Comment by mjknight50** [comment]
I guess it is a business question more than anything else.  Does the sidekiq dashboard show each email's success/failure or just a roll-up of some kind?
cc @vbellissimo

**Comment by buddhima-coforma** [comment]
@va-albers would you know the answer to Matt's question?^

**Comment by mjknight50** [comment]
The script can be saved here:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/benefits/scripts/526

**Comment by danlim715** [comment]
[Link to the core script PR](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1532)

**Comment by danlim715** [comment]
I'm not seeing the VANotify template on the dashboard anymore. Do we know what happened to it?

**Comment by aplatt-coforma** [comment]
@danlim715 - is it not here: https://staging.notifications.va.gov/services/725bbdd4-5a6e-4688-8678-fae4323ef3a3/templates/aef34a57-0eb9-4df2-80df-206dac6d4e65?templateSaved=true 

I don't have access to that link so please let me know if that does not work.

**Comment by aplatt-coforma** [comment]
For some reason it won't let me link the card so here's the content card for reference: 
[#75872 Pension Reactivation Email Content from Pension Benefits Team](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/75872)

**Comment by danlim715** [comment]
Updated template link: https://staging.notifications.va.gov/services/5e5cded3-3c76-46a3-9eef-cb63589e76be/templates/f7ec31d5-b39e-46c6-884c-ad4147a80e18

**Comment by danlim715** [comment]
PR for Staging bearer token ENV variables: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2780

**Comment by danlim715** [comment]
Just moved the template from the shared va.gov service to a newly created Pension Benefits service. Link to new template: https://staging.notifications.va.gov/services/066bd626-5082-45a3-84a1-349dabd2b6ba/templates/1e8602a5-b1c5-4c96-b1c5-d306db09fc14

**Comment by buddhima-coforma** [comment]
Template edit requested by Julie
<img width="1358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1lQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb5afa5ea4d3389b6ee90aa6db0585bb8ab1e1bb/image.png" alt="image.png" />

**Comment by matt4su** [comment]
Use "Claimant" as default value when Name not populated

**Comment by mjknight50** [comment]
3140 emails were sent:

```
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.561235Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":72,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"PensionReminderIpfProcessor succeeded!","payload":{"form_id":8950466,"form_type":"21P-527EZ"}}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.561957Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":49,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"PensionReminderIpfProcessor completed!"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.562229Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":50,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"--------------------------------------"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.562446Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":51,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Succeeded: 3140"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.562621Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":52,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Failed: 0"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.563065Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":53,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"--------------------------------------"}
=> true
irb(main):130> 
```

**Comment by danlim715** [comment]
<img width="329" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a187e4e4563a71f21506eec4df267f0e0276fa50/image.png" alt="image.png" />
