### ISSUE TITLE
[100% Traffic] Trigger Pension Reactivation Email

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69763]
## Issue Description
Similar to [Pension | Trigger Deactivation Email #67849](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67849)...

Once the Pension 527EZ form is re-activated, the VA Notify trigger created here needs to be activated to send an email to users with in-progress forms informing them that they can resume their pension form online.

---
## Tasks
- [ ] Select and validate recipients - Veterans with active in progress forms on or before 12/1/23
- [ ] Activate VA Notify Trigger
- [ ] Confirm successful email distribution (and know if there were any issues via callback)

## Acceptance Criteria
- [ ] User with in-progress 527EZ forms will receive an email about the Pension online form being available again on VA.gov

**Comment by aplatt-coforma** [comment]
For ticket tracking purposes, wanted to create a ticket link to https://github.com/department-of-veterans-affairs/va.gov-team/issues/75872 which tracked the creation of the email template to be used to send out the communication.

**Comment by mjknight50** [comment]
3140 emails were sent:

```
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.561235Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":72,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"PensionReminderIpfProcessor succeeded!","payload":{"form_id":8950466,"form_type":"21P-527EZ"}}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.561957Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":49,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"PensionReminderIpfProcessor completed!"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.562229Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":50,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"--------------------------------------"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.562446Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":51,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Succeeded: 3140"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.562621Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":52,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Failed: 0"}
{"host":"vets-api-sidekiq-654d8c6f6f-jw2d9","application":"vets-api-server","environment":"production","timestamp":"2024-04-09T15:02:51.563065Z","level":"info","level_index":2,"pid":38820,"thread":"12120","file":"(irb)","line":53,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"--------------------------------------"}
=> true
irb(main):130> 
```
