### ISSUE TITLE
Create Pension Reactivation Email Template

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69764]
## Issue Description
Once the Pension 527EZ form is re-activated, we need to draft the email that will be sent to Veterans who had an in-progress form at the time we deactivated the form.

Similar to:

- [Pension Email Template #64679](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/64679)
- [Deactivation Build and send Pension Deactivation Email #69310](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69310)

---
## Tasks
- [x] Design & Engineering: Verify your VA Notify platform access. [Instructions on this can be found here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify).
-- Access was provided to Gretchen, Maya, Matt, & Todd
- [x] Design: Work with CAIA/Katherine Fung & Julie Strothman to draft the necessary email copy and formatting; Created this CAIA intake request for this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75872

## Acceptance Criteria
- [x] The email template to send to users with in-progress 527EZ forms will be ready for deployment (but sent **_only_** once we release the online Pension form to 100% of traffic.

**Comment by katherine-fung** [comment]
Hi @vbellissimo and @jstrothman, 

I'm starting to draft copy for the email. Do we want the call to action be something in the spirit of: "You can continue your online application for VA pension benefits"?

**Comment by vbellissimo** [comment]
@jstrothman I think that makes sense, and align it with something like what we have posted on the intro page for those who are now able to access the online form?

![Screenshot 2024-02-14 at 5 27 06 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106613300/ac498ac8-8d19-457f-ba9f-09ff2bbd5f74)

Curious to know what @jstrothman thinks!

**Comment by vbellissimo** [comment]
Related Slack thread here: https://dsva.slack.com/archives/C06E83RNLQM/p1708452607458269
