### ISSUE TITLE
Content edits for ticket #69661 

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#69779]
## Info
Content edits according to [69661](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69661)
## Tasks
- [x] Review support ticket 
- [x] Review attached SharePoint Doc for suggested copy edits
- [x] Where needed, and based on copy edit suggestions, change references of Cerner to Oracle Health
- [x] Prepare page for deployment
- [x] Deploy page

## Acceptance Criteria

- [x] Platform website will have the right references from Cerner to Oracle Health
- [x] Page has been deployed

**Comment by johnny-jesensky-adhoc** [comment]
Hi @taylojill, this is the ticket I had created to reflect the work done on updating [Cerner to Oracle Health](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69661). It looks like the page wasn't updated as part of today's deployment.

Were you able to update the page? Want to double check I'm not looking in the wrong place!

**Comment by taylojill** [comment]
Page updated and checked for launch-blocking issues. Ready for deployment.
Here's what I did:
1.     Added an information box regarding the name change and future changes at the beginning of the document.
2.     Changed all Cerner references to Oracle Health, with the exception of code use/mentions.
3.     Updated link to correct 404 error.
4.     Made the name change in the "list of selectors" descriptions.
