### ISSUE TITLE
Remove Platform Support Assignment Daily Bot

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69795]
## Description 
When looking at the Platform Support schedule that is sent daily, it shows all Tier 1 folks vs. showing the person on schedule for that day. We'd like to research if it is possible to update the information or analyze if we even need to have it at all (since it's always the same people).

Link to example of message: https://dsva.slack.com/archives/CBU0KDSB1/p1701781722675089

---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 

- [x] Reach out to PMs to identify if they need this bot
- [x] If don't need it, identify how to remove it
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

- [Platform Support Schedule Example](https://dsva.slack.com/archives/CBU0KDSB1/p1699886315756199)
- [[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDNNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--975f70fdcbd7703790d3c18c21ad17329553a3fb/Screenshot%202023-11-13%20at%2011.36.55%20AM.png)

**Comment by alyssagallion** [comment]
Not applicable anymore. Closing.

**Comment by alyssagallion** [comment]
Scheduled a call with Clint to discuss further.

**Comment by alyssagallion** [comment]
Option removed by Erika. Closing.
