### ISSUE TITLE
Document the process when wanting to replace a new page on the Platform Website

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#69809]
## Info Description
When a page on the Content Platform website, is either migrated, or recreated, it will often lead to the creation of a new URL. This presents an issue when that page is referenced on other parts of the website.

Whenever possible, we should avoid changing the underlying URL of the page by recreating it. The ticket here is to write up our team's process/operating procedure into Confluence, so we have a record of it.

## Tasks
- [x] Create a Confluence page in outlining the process in our Team's Confluence space https://vfs.atlassian.net/wiki/spaces/CIT/overview
- [ ] The process should include avoiding changing the existing URL wherever possible. However, in the event this is unavoidable, we should look to either leverage a URL redirect within Scroll Viewport https://help.k15t.com/scroll-viewport-data-center/2.21/configure-global-url-redirects
- [x] Page should live in the following location within Confluence. _Platform Content Team_ --> _How We Work_ 

## Acceptance Criteria

- [x] A page has been created within our Platform Content Team space
- [x] The page has guidance on steps to follow when it appears there is a need to create a page.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/69809?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by johnny-jesensky-adhoc** [comment]
@laucon, It appears that the Redirect Macro functionality isn't immediately available, and might require either a permission bump, or some other plug-in. Finding the answer to that question is going to take some more investigative work, that will be sufficient work to be in it's own separate spike ticket. 

As such, for _this_ ticket, I changed some text in our second bullet, and have this in the _**Under Review**_ column. I think the text we have covers what this ticket set out to achieve, documenting our team's policy of avoiding re-creating pages that will change the URLs which has negative, cascading effects.

If you are ok with the text we have - we can move this to done.

**Comment by laucon** [comment]
@johnny-jesensky-adhoc Awesome. Your content looks great. However, I did edit it to correct a few grammatical mistakes and made it a bit easier to read by turning step 2 into a series of steps. I hope that's cool. I think it looks great now. Thank you so much for helping me with this. I think we can move it to done.

**Comment by johnny-jesensky-adhoc** [comment]
@laucon Perfect - just reviewed, and think it's looking good for now. K15t support referred me to the right redirects to use ([fallback redirects](https://help.k15t.com/scroll-viewport/fallback-redirects)), but that is something I'll look into at a later date.

Moving this to _**Done**_.
