### ISSUE TITLE
SPIKE | PDF service for Burial and CH 36

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69835]
## Issue Description
_To prepare for planned maintenance windows for VBMS, BGS, and EVSS related to the application of the cost of living adjustments to Veteran records, we need to determine what backend service is used to generate the pdf form submission for the Chapter 31 28-1900 and Burial 530 forms, so we can understand if these forms will be impacted by the windows. This information will also be helpful as we make form updates and need to validate the updates are correctly applied to pdf creation and submission._

---
## Tasks
- [x]  Investigate what creates the PDF when an online Chapter 31 form is submitted (vets-api or BGS)
- [x] Investigate what creates the PDF when an online Burial 530 form is submitted (vets-api or BGS)

## Acceptance Criteria
- [x] Document findings in appropriate repo
- [x] Update [this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699022689906/c254ed5503dedce1ff1c3240ada0cfa7cb91caf2?sender=u0e8ac1d6d7681bb7e1b80558) with findings

**Comment by micahaspyr** [comment]
PDF Generation:

- Both Ch31 28-1900 and Burial 530 submissions generate a pdf on vets-api before submission
