### ISSUE TITLE
[Design] Switch headings and body and icons to v3 in Unified 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69831]
## Tasks
- [ ] Switch headings and body and icons to v3 in Unified Sketch file in the Design page
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
@loripusey added this one

**Comment by zach-park** [comment]
@benbrasso-agile6 @ytsaoca @cgednalske , the heading, body, and icons in [the design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas) as well as the symbols are ready for validation. Thank you!

**Comment by benbrasso-agile6** [comment]
@cgednalske you want to help validate this one?

**Comment by benbrasso-agile6** [comment]
@cgednalske @zach-park you guys close this ticket when you're ready

**Comment by zach-park** [comment]
@cgednalske @benbrasso-agile6 . Ready for re-validation. Thank you.

**Comment by cgednalske** [comment]
@zach-park after talking with @benbrasso-agile6 it sounds like the following is the version/direction we should be using for the phone icon (used in VAOS). So in that case, production has the right direction but unified needs to be updated.

<img width="481" alt="Screenshot 2023-11-28 at 11 25 41 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/2c7c7993-4a32-435d-9b4a-1ff461abb035">

**Comment by zach-park** [comment]
Do they use a mixture of appointment icons and identification icons? The reason for asking is that we will be mixing two sets of icon groups if we use the appointment set for the telephone icon. I think we would be fine either way. Just need a confirmation. Thank you.:)

**Comment by benbrasso-agile6** [comment]
I think it's an oversight by the DS that there's two phone icons. I would think we would want to use appointment icons first, and then if we need one that doesn't exist in there, look in one of the other sets of icons 🤷

**Comment by zach-park** [comment]
Ah, I gave it more thought and I think I got it. In fact, I actually think we should be using both icons technically. One is for indicating a Phone appointment (VAOS' version). And the one we have been using is specifically for the phone number.

> Do they use a mixture of appointment icons and identification icons? The reason for asking is that we will be mixing two sets of icons if we use the appointment set for the telephone icon. I think we would be fine either way. Just need a confirmation. Thank you. :)

**Comment by benbrasso-agile6** [comment]
Ooooooohhhhh, interesting

**Comment by cgednalske** [comment]
@zach-park I added a comment about the Need help headings, but otherwise everything looks good. Once you take a look at that (and either make the change or leave it) I think we can close this!

**Comment by benbrasso-agile6** [comment]
@loripusey design team will chat about this next week when more of us are in the office. Will circle back with reasons and any to-do's.

**Comment by benbrasso-agile6** [comment]
@loripusey we did a retro on why this work wasn't done. The new USWDS v3 icons aren't all in Sketch. I don't know/think that the DST will be adding them into Sketch knowing that the license ends in February. So, we were able to tell the engineers which icons to use, but those are only available in Figma (and in Storybook), but the design team hasn't fully transitioned to Figma yet. In retrospect, we should have communicated that better, but also, the DST has been making changes to the libraries in Sketch and Figma, so it's difficult to keep up with what's available and what's not. 

Our plan is to use the new icons in Figma as we get everything over into Figma.
