### ISSUE TITLE
[Design] Switch headings and body and icons to v3 in Production file

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69832]
## Tasks
- [ ] Switch headings and body and icons to v3 in Production Sketch file in all pages
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
@loripusey this one is ready

**Comment by zach-park** [comment]
@benbrasso-agile6 @ytsaoca @cgednalske , the heading, body, and icons in the following page (as well as the symbols) are ready for validation. Thank you!

Pre-check-in:
- In person: https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/6559E321-AF82-42D1-837D-75F9DB19DF15/canvas
- Telephone: https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/37E0C5B9-D07D-4782-AF6B-6AD947AE0BE2/canvas

Check-in: https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/0213EBFE-75F9-4C0E-805B-5E77F30A8F04/canvas
Check-in w/ travel pay: https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/A6E73D11-A95C-4EC0-A3B7-792CE5799C59/canvas

**Comment by benbrasso-agile6** [comment]
@cgednalske pls take this one too

**Comment by benbrasso-agile6** [comment]
@cgednalske @zach-park you guys close this ticket when you're ready

**Comment by cgednalske** [comment]
@zach-park (except for phone icons for now) everything else should be ready to validate!

**Comment by zach-park** [comment]
Validated. Thank you!

**Comment by zach-park** [comment]
Validated. Thank you!
