### ISSUE TITLE
[Design] Switch to button pairs for v3 to Yes and No buttons

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69841]
## Tasks
- [ ] Switch Yes and No buttons to button pair component v3 in Production Sketch pages AND Unified check in Sketch Design page
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
@loripusey good to go

**Comment by ytsaoca** [comment]
Updated Production Sketch pages and Unified check in [Design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas#About).

**Comment by ytsaoca** [comment]
Updated Production Sketch pages and Unified check in [Design page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas#About).

**Comment by benbrasso-agile6** [comment]
Validated, nice work
