### ISSUE TITLE
check-in API should not record expected 40x responses as errors

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#69865]
## Issue Description
The check-in API controllers show a very high error rate in Datadog - on the order of 15+%:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20694532/0193d7f6-e990-42c2-9b97-4ea5a6a0c76d)

While I'm not super-familiar with the check-in product, this looks like it is *not* actually a user-facing problem, but more with how certain expected responses - 401s and 404s due to things like expected expired sessions or lack of data for a user - are being generated and recorded. 

If that's true, then the check-in controllers should be adjusted so these request traces are not recorded as errors in Datadog.

Check-in looks like it deviates from the common pattern in vets-api of throwing various exceptions and having the [ExceptionHandling concern](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/concerns/exception_handling.rb) map them to JSON responses and for certain expected exception types skip reporting to both Sentry and Datadog. Instead it looks like it's either throwing alternate exception types or rendering JSON responses with various statuses directly. I don't know how that's winding up as errored. In any case it should be doable to suppress the errored traces.

---
## Tasks
- [ ] Identify the class of 40x errors in check-in APIs that represent expected behavior
- [ ] Implement a way to avoid those being marked as errors in datadog
- [ ] (Hopefully the above also quiets down check-in related errors in sentry as well)

## Acceptance Criteria
- [ ] Check-in service in Datadog service catalog displays an error rate that is in line with actual errored vs. not behavior. 
- [ ] Actual user-affecting errors such as 50x errors continue to be reported correctly as errors. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by patrickvinograd** [comment]
For controllers that are generating a 404 via a vets-api standard `RecordNotFound` exception, there's an easy way to suppress those from showing as errors - including the `IgnoreNotFound` concern in your controller. As mentioned above I don't think it's quite that simple for check-in, but mentioning it here in case it suggests a similar clean approach

**Comment by loripusey** [comment]
@randomsync Please create task tickets for this effort and send me the links, we can do those in future sprints.
cc: @loripusey

**Comment by randomsync** [comment]
data from DataDog shows 401 errors not being logged anymore:

https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/reh-2jq-9ez

<img width="1219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK050QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38b866cfe44edc3d494c9a715cff6a759236a28b/image.png" alt="image.png" />
