### ISSUE TITLE
Add FeatureToggleEvents to Flipper UI

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#69863]
### Description
It's been requested that the events we are capturing related to Flipper/Feature Toggles are displayed in the Flipper UI.

We currently have about 20k records dating back to 2019 with the following shape:

```
 #<FeatureToggleEvent:0x00007ff445746238
  id: 19943,
  feature_name: "profile_use_field_editing_page",
  operation: "enable",
  gate_name: "percentage_of_actors",
  value: "25",
  user: "some_user@gmail.com",
  created_at: Wed, 25 Oct 2023 16:10:42.540362000 UTC +00:00,
  updated_at: Wed, 25 Oct 2023 16:10:42.540362000 UTC +00:00>
```

We could pretty easily do something like what was laid out in this [flipper PR](https://github.com/flippercloud/flipper/pull/102#issuecomment-612707892) or throw it into a more concise table similar to how other data in the Flipper UI is presented.

### Tasks
- [ ] Create new view containing N number of FeatureToggleEvents presented in a table (`/flipper/events` ?)
- [ ] Link `/flipper/features` (`flipper/views/features.erb`) to new events view
- [ ] Add information on the last N events to individual features pages (`flipper/views/feature.erb`)

### Acceptance Criteria
- [ ] New feature is deployed and working in all environments
