### ISSUE TITLE
Create React Widget for Landing Page Dynamic Content

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#69866]
Our Find a Representative tool will be accessed through a landing page -- a page on VA.gov that [exists today](https://www.va.gov/disability/get-help-filing-claim/), but will be updated to point to our product.

When we do our staged rollout for our product, we also need to stage the rollout of updated content for this landing page.  To do this in parallel, we will need to create a React widget that is connected to our feature toggle.  And, based on the feature toggle state, the old vs. new landing page content will appear.

Landing page content can be viewed [here](https://docs.google.com/document/d/1tIdX3Y444fxG16SCdwWdVssBb5vCbLDnVGMp32sCqiw/edit) and our widget will need to cover the dynamic content outlined in the "[H2] How do I find an accredited representative?" section:
- "Display 1: Modern tool" = feature toggle on (new experience connected to our staged rollout)
- "Display 2: Legacy tools" = feature toggle off (old experience we're moving away from)

CAIA will place the React widget on the landing page before we being our staged rollout, and we'll control visibility for the different stages through the feature toggle.  When we're ready to serve our product to 100% of users, then CAIA will replace the React widget with the new content for all to see.

The full process is detailed in this CAIA document: [Dynamic content in Drupal: Implementation and removal process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md#dynamic-content-in-drupal-implementation-and-removal-process)

## Tasks
- [x] Create a react widget that can dynamically display current and new landing page content
- [x] Confirm with CAIA that the react widget content is correct (`A Procik` in Slack or `aprocik1` in Github)
- [x] Share the widget with CAIA so they can implement it on their landing page
- [x] Connect react widget to Find a Representative feature toggle

## Acceptance Criteria
- [ ] A react widget with CAIA-approved content has been added to the Find a Representative feature toggle

**Comment by oddball-lindsay** [comment]
CAIA should have content ready for review on Monday 11/27 EOD and then we need stakeholders to review for accuracy.

**Comment by oddball-lindsay** [comment]
@cosu419 CAIA has confirmed that content on the [GDoc](https://docs.google.com/document/d/1tIdX3Y444fxG16SCdwWdVssBb5vCbLDnVGMp32sCqiw/edit) is finalized and ready to be implemented in the widget

**Comment by oddball-lindsay** [comment]
From Colin:
I wanted to recap the steps I took after discovering the documentation. The react widget has changed from the original version I sent today.
1. Added widget of widgetType: "find-a-rep-landing-content" to registry.scaffold.json
2. Added FIND_A_REP_LANDING_CONTENT widget type to widgetTypes.js
3. Added react widget to new representative-search folder in static-pages
```
import React from 'react';
import { connect } from 'react-redux';
import { useFeatureToggle } from '~/platform/utilities/feature-toggles/useFeatureToggle';

const renderNewLandingContent = () => {
  return (
    <>
      <p>Use our online tool to search for an accredited representative.</p>
      <a
        className="vads-c-action-link--green"
        href="/get-help-from-accredited-representative/find-rep"
      >
        Find an accredited representative
      </a>
    </>
  );
};

const renderOldLandingContent = () => {
  return (
    <>
      <p>You can find an accredited representative in 1 of 2 ways:</p>
      <ul>
        <li>
          <va-link
            href="https://www.ebenefits.va.gov/ebenefits/vso-search"
            text="Go to eBenefits"
          />
        </li>
        <li>
          <va-link
            href="https://www.va.gov/ogc/apps/accreditation/index.asp"
            text="Search the VA Office of the General Counsel's list"
          />
        </li>
      </ul>
    </>
  );
};

export const App = ({ show }) => {
  const {
    // useToggleValue,
    useToggleLoadingValue,
    // TOGGLE_NAMES,
  } = useFeatureToggle();

  // const appEnabled = useToggleValue(TOGGLE_NAMES.findARepresentative);

  const togglesLoading = useToggleLoadingValue();

  if (togglesLoading) {
    return null;
  }

  return (
    <>
      {show && renderNewLandingContent()}
      {!show && renderOldLandingContent()}
    </>
  );
};

const mapStateToProps = state => ({
  show: state?.featureToggles?.findARepresentative,
});

export default connect(
  mapStateToProps,
  null,
)(App);
```
4. Added creator function to representative-search folder:
```
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { connectFeatureToggle } from 'platform/utilities/feature-toggles';

export default (store, widgetType) => {
  const root = document.querySelector(`[data-widget-type="${widgetType}"]`);
  if (root) {
    import(/* webpackChunkName: "find-a-rep-landing-content" */
    './components/App').then(module => {
      const App = module.default;
      connectFeatureToggle(store.dispatch);

      ReactDOM.render(
        <Provider store={store}>
          <App />
        </Provider>,
        root,
      );
    });
  }
};
```
5. Imported and executed createFindARepLandingContent in static-pages-entry.jsx

**Comment by oddball-lindsay** [comment]
A confirmed that everything is working as expected!
