### ISSUE TITLE
[BE] 10-10EZR - V2 form: Add vets-API retries to the 10-10EZR form

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#69870]
## Background
Now that the EZR MVP has been launched, we want to implement the vets-API retry functionality so that submission failures have an opportunity to be successful and reduce the impact to the Veteran.

## Tasks
- [x] Add the Vets-API retry functionality - Submit the 10-10EZR form using a background job
     - Submissions will retry up to 14 times (spanning over about 24-25 hours based on standard retry table)
- [ ] Complete testing to confirm successful retries in the event of a submission failure
- [ ] Add Submission failures and Submission retries to the Datadog dashboard (similar to the EZ dashboard)
- [x] Add Submission failure alerts that will announce in the #health-tools-1010-apm Slack channel
     - Alert will announce when there are no retries left (similar to the EZ alert)
- [ ] Validate with PM upon completion

## Acceptance Criteria
- 10-10EZR submissions will now be retried up to 14 times, in the  event of a submission failure. The team will be alerted of the submission failure for investigation.

**Comment by lihanli** [comment]
@hdjustice  will the user get an email when the job fails?

**Comment by hdjustice** [comment]
@lihanli - I dont think we have set that up yet, but would definitely need to.  I can create a ticket for that and see how we might do that with VA Notify

**Comment by lihanli** [comment]
@hdjustice we should make a new issue for the 1010ezr datadog dashboard because it currently doesn't exist

**Comment by hdjustice** [comment]
Hi @lihanli - It does exist [here](https://vagov.ddog-gov.com/dashboard/kjp-9wp-u47/10-10ezr?refresh_mode=sliding&from_ts=1701450791978&to_ts=1701454391978&live=true).  My apologies, I should have added that to the ticket for reference.

**Comment by hdjustice** [comment]
Would you like me to make a ticket to add this tracking to the dashboard?

**Comment by hdjustice** [comment]
Update to the above, we have a DD dashboard for EZR however it is not pulling the right stats.  Another ticket has been created to address that issue.

**Comment by lihanli** [comment]
we can close this and finish the work in the va notify issue

**Comment by hdjustice** [comment]
Ticket #72846 created for submission failure emails to be sent thru VA notify to the Veteran
