### ISSUE TITLE
Design | Profile | Personal information | Add disability rating state

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#69874]
## Background
We realized Sketch is missing a couple of things from personal info:

- [x] desktop version of the personal info page with a disability rating
- [x] mobile version needs to be added to the main mobile page (currently only exists in the future state mobile page)

## Tasks

- [ ] Add the above states to the personal info sketch file
- [x] Let @mtcA6 know it is there

## AC
Sketch has the disability rating state added to mobile and desktop

**Comment by andaleliz** [comment]
@mtcA6 here is the [mobile version of this section](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/9lKQk3P) and [here's the desktop version](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/bLK2lRo).  Let me know if you have any questions!
