### ISSUE TITLE
[Content] Create Content for when Veteran selects direct link after 30 days

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69879]
## User Story

We will have a scenario where a Veteran selects a direct link (from email, for example) to file a claim for a specific appt/visit and it's past the 30 days of eligibility. Therefore, we need a card component to reflect that type of messaging. E.g, they can't file for this claim any longer because it's past 30 days. 

[Here's the card component used for when the Veteran is within the 30 days](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/73EE914F-7B6C-490B-84E0-F8E344E64201/canvas) and has an action to complete. 

Ya-ching is working on the design via this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68923). 

## Tasks
- [ ] Create the content

### Who needs to review? Check all that apply.   
- [x] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by kellysmith1008** [comment]
[Mocked up a first draft for this content](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/x07wLo5) - will work with Ya-ching to get it finalized and then we'll put it in validate for the UX team

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 oh, one thing I just thought of, should we solve for when there are more than 1 appts at that facility too? Grabbing some screenshots of how we solved for that in the VAOS upcoming appts page and in the email template, which I know you're aware of. But, I think we might need to consider the multi appt scenario here too. What do you think? Does that change anything?<br><br>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJ2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dd5c2b0510a4168ff41744d41d0c12de676d783/Screenshot%202023-11-20%20at%2011.40.03%E2%80%AFAM.png)<br><br>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW52QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a46aa8b3a8b29c235d207be8bbc33334a45d21ae/Screenshot%202023-11-20%20at%2011.39.22%E2%80%AFAM.png)
