### ISSUE TITLE
Assign Atlas Github Oauth Apps to va-vsp-bot

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#69876]
## Description

Atlas currently utilizes GitHub OAuth, and the OAuth apps are currently associated with a private user account. To enhance security and manageability, we need to transfer these apps to the va-vsp-bot account. These need be to approved by an admin and the transfer has been started.

## Tasks

- [x] Initiate the transfer process for GitHub OAuth apps.
- [x] Update configurations in the application to reflect the changes.
- [ ] Verify that the OAuth apps are functioning correctly after the transfer.
- [ ] Update documentation to reflect the new configuration.

## Additional Information

- GitHub OAuth apps are currently under a private account.
- Transfer to the bot account for enhanced security and organization.

**Comment by laineymajor** [comment]
Lindsey pinging clint on this ticket

**Comment by LindseySaari** [comment]
Github ticket opened here: https://github.com/department-of-veterans-affairs/github-user-requests/issues/18900

Slack Conversation: https://dsva.slack.com/archives/CU1E4CX9U/p1700499042311959

**Comment by LindseySaari** [comment]
@RachalCassity reinitiated the transfer to department-of-veterans-affairs. Waiting on GH personnel to push forward

**Comment by RachalCassity** [comment]
OAuth apps were successfully transferred.
