### ISSUE TITLE
Add TOU (Cerner) error to AuthApp

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#69882]
## Description
Create a new error for the `/auth/login/callback` page (eg AuthApp.jsx) so that when My VA Health (Cerner) provisioning fails the user is given information to remedy the error.

## Tasks
- [ ] Add the new error for Cerner Provisioning Failure
  - [ ] Add code `110` to the `authentication/errors.js`
  - [ ] Add message `My VA Health provisioning failed` to the same file
  - [ ] Update unit tests if required
- [ ] Add new error to the RenderErrorContainer
  - [ ] Alert content => should be `We’re having trouble provisioning your My VA Health account right now.`
  - [ ] Troubleshooting content will contain
    - [ ] An h2 => How can I fix this issue
    - [ ] The HelpDesk component with `startSentence` prop
    - [ ] And a button that opens the login modal (see others in that file
  - [ ] Update unit tests if required
