### ISSUE TITLE
Atlas Utility Teardown

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#69880]
## Description

After the governance team has some time to utilize our Atlas MVP, we will want to initiate the teardown process. We need to dismantle any configurations, infrastructure, manifests, etc., related to Atlas. This process will involve the teardown of Atlas in the utility environment

## Tasks

- [x] Identify and document all configurations and infrastructure related to Atlas.
- [x] Develop a teardown plan outlining the sequence of steps for dismantling Atlas components.
- [x] Execute the teardown plan in the development environment (dev).
- [x] Validate the successful teardown in the development environment.
- [x] Execute the teardown plan in the production environment (prod).
- [x] Validate the successful teardown in the production environment.
- [x] Update documentation to reflect the decommissioning of Atlas.

 ## Closing checklist
- [x]  EC2 instances removed
- [x]  Redis instances removed
- [x]  RDS instances removed
- [x]  ArgoCD references removed
- [x]  Documentation removed
- [x]  Devops references removed

## Additional Information

- Atlas is now currently running in both dev and prod environments and publicly accessible
- Ensure all components are appropriately decommissioned to free up resources.

**Comment by RachalCassity** [comment]
:rip: Codeowners Utility Teardown :rip:
The Platform Codeowners Utility app will be removed in 3 different PRs:
Remove from vsp-infra-argocd PR HERE
Remove from app-of-apps PR HERE
Remove platform-codeowners directory PR HERE

**Comment by RachalCassity** [comment]
Awaiting DevOps approval

**Comment by RachalCassity** [comment]
Decommissioning Documentation: https://vfs.atlassian.net/wiki/spaces/TT1/pages/2840526850/Platform+Codeowners+Utility+Decommission

**Comment by laineymajor** [comment]
This needs to be in NEXT sprint. To air on the side of caution, we need to retain this for now.

**Comment by LindseySaari** [comment]
@RachalCassity All of the PRs are approved and ready for merge

**Comment by LindseySaari** [comment]
Kyle will working on the Argo teardown pieces Mon/Tues. We are continuing to investigate any orphaned resources (RDS and Elasticache) and will tear down accordingly.

**Comment by LindseySaari** [comment]
RDS for utility instance has been stopped. If not alerted of anything breaking, this will be deleted today (Monday).

**Comment by LindseySaari** [comment]
The app-of-apps and manifest config has been removed. The remaining piece is deleting the RDS db instance from AWS (not terraformed).

**Comment by RachalCassity** [comment]
- [ ] EC2 instances removed
- [ ] Redis instances removed
- [ ] RDS instances removed
- [ ] ArgoCD references removed
- [ ] Devops references removed

**Comment by RachalCassity** [comment]
Devops modifications will be deploy via to terraform.

**Comment by RachalCassity** [comment]
@jennb33 This ticket is closed.
