### ISSUE TITLE
Research: Slack Automations for Tier 2 Rotation Participation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69889]
## Description 

**Overview**

This ticket will house the task of identifying better ways to accomplish the following:

- Notifying the specific people on Tier 2 rotation to join our bi-weekly standup on Tuesdays at 1 p.m. CST (see existing message attached below)
- Onboarding message to Tier 2 engineers with resources and tips for providing the best support (see existing message attached below)

**Goals**

_Standup Notification:_

- Automated process
- Avoiding creating a new calendar invite every two weeks to avoid forgetting or additional work on the Platform Support Team
- Tags the people on that rotation using PagerDuty information

_Onboarding Message:_

- Automated process
- List of items that Tier 2 needs to accomplish/items to read before starting on Support
- Sent the day before the rotation
- Tags the people on that rotation using PagerDuty information

---

## Definition of Done
All of the tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Identify technical automations that we can leverage to allow Tier 2 folks to participate well during their time on support while also reducing manual labor on the Platform Support team (i.e. updating calendar invites every two weeks would be manual)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkhUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--234e3b3c564d9eed3583aa88c1abec062c0aee72/Screenshot%202023-11-14%20at%2011.11.16%20AM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkRUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b10b2f1b3ad6d281c6bc3a0a45a3de6e138f3f40/Screenshot%202023-11-14%20at%2010.44.31%20AM.png)

**Comment by lindsay-insco** [comment]
Update: 

Spoke with PagerDuty support and Slack support on possible integration of `/oncall ` command which outputs PD schedule to tag team members.

It appears to be all or nothing, so we would result in tagging everyone on the schedule. This takes away the simple possibility of pulling just the team members we need into an automated standup or invite. 

There might be a little possibility with the API but PagerDuty still seems unsure about that. This is a surprisingly a highly requested feature but not one with a solution they were able to provide me. It looks like solutions in Slack that we already utilize just paste the direct links from PD and also lack any ability to tag or pull the data into an automatic tag.
