### ISSUE TITLE
Burial | Map and Update PDF

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#69894]
## Issue Description
_In order for burial 530 claims to be process efficiently, the claim pdf needs to contain all the relevant information entered online. The fields that are being added to the online form need to be mapped and added to the pdf that is generated and submitted to downstream systems. Fields that are removed from the online form need to be removed from the pdf._

- User flows: https://sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7
- Prototype or mockups: https://sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7

---
## Tasks
- [ ] Map new fields to pdf
- [ ] Add new fields to pdf
- [ ] Remove depreciated fields from the pdf

## Acceptance Criteria
- [ ] The burial 530 claim pdf includes all the information from the online claim within fields in the pdf
