### ISSUE TITLE
Update Appointments URL destination for "schedule and manage appointments" 

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#69895]
## User Story
As an authenticated user on VA.gov on the health portal landing page (`va.gov/my-health`), I want to be able to start scheduling an appointment when I select "schedule and manage appointments" so that I can finish the task I came to the site to do, instead of being sent to an informational static page that requires additional clicks to get to that task successfully. 

### Description
Currently, the MHV on VA.gov health portal landing page links users to the health-care benefit hub page to view and manage their upcoming appointments when users select the top link in the Appointments section of the page ("schedule and manage appointments"). _See [Slack thread here](https://dsva.slack.com/archives/C0581MN69TJ/p1699984366031149) for additional details._ 

Instead, this link should deep-link users into the scheduling flow so that they are more directly linked into the task they are trying to complete. 

Impact note: per GA (using a previous-page-path report), about 8,700 users clicked the link in question in the past 7 days.

<img width="851" alt="Screenshot 2023-11-14 at 11 02 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/fea5ecc3-9ffd-4959-81c0-7421eb9d9606">

## Tasks
- [ ] Connect with appointments team @JRRoof @kristenmcconnell @simiadebowale to confirm the approach outlined in this ticket. (As of 11/14 the url to deep-link to wasn't immediately clear.)
- [ ] Do technical discovery to figure out what it will take to successfully deep-link users into the scheduling task flow when they select this link text on the health portal landing page.
- [ ] Update the destination URL for the link text "schedule and manage appointments"
  * Remove URL: `va.gov/health-care/schedule-view-va-appointments/`
  * Replace with URL: `va.gov/my-health/appointments/schedule  `
  

## Acceptance criteria
- Users who are on the MHV on VA.gov health portal landing page, see the link text "schedule and manage appointments" under the Appointments section and navigate to the scheduling task flow when they select that link.

**Comment by outerpress** [comment]
The Appointments team will need to complete ticket #72066 to enable this work, added as blocker. FYI @simiadebowale @sterkenburgsara @JRRoof @kristenmcconnell

**Comment by outerpress** [comment]
#72066 is done on the appts side, so you should be able to direct-link into the scheduling flow now.

**Comment by sterkenburgsara** [comment]
@jzucadi Update: per @outerpress this is **not** working as expected on staging. 

* The first link still reads "Schedule and manage appointments." Please update the link text to read: **"Schedule a new appointment"**
  * Update URL destination for that link text to: `/my-health/appointments/schedule/type-of-care`

**Comment by sterkenburgsara** [comment]
@wesrowe this ticket looks duplicative of [this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77185#69895) - can I close this one since @jzucadi already got started on the other?

**Comment by wesrowe** [comment]
Yes, go ahead and close one. (Dealer's choice.) Sorry I didn't notice the duplication.

**Comment by outerpress** [comment]
Hi @wesrowe @sterkenburgsara just checking in on this one. It looks like (on staging) the first two links are currently pointing to the same page which is confusing, and seems like it would be an issue for someone clicking through trying to understand their options in appointments. Thanks!

**Comment by sterkenburgsara** [comment]
@wesrowe I think you closed the one that had an Assignee and a sprint attached to it, so this didn't get picked up. Can you please escalate?

**Comment by wesrowe** [comment]
the problem slipped past me, sorry about that. I'll comment on the other one, I guess, since Jim worked (and closed) it already.

**Comment by wesrowe** [comment]
closing this one as a dupe.
