### ISSUE TITLE
[Ongoing Service] Platform Communications - Publish Monthly Newsletter

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#6989]
### **Problem Statement** ### 
Not all VFS team members are aware of new platform tools and services released by VSP teams. 

VSP teams need additional communication channels outside Slack and TOTs for platform announcements.

### **Measuring Success** ### 
- successful delivery rate
- open rate
- click rate per unique opens

### **Goal** ### 
Distribute a regular email newsletter to VFS team members announcing platform updates with links to documentation.

Product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/service-design/newsletter-product-outline.md

## We will know we're done when:
- This is an ongoing service VSP will provide for the foreseeable future.

**Comment by jchasia-adhoc** [comment]
## Newsletter MVP Launch Checklist

- [ ] Content review
  - [x] [Copy edit v1](https://us19.campaign-archive.com/?e=%5BUNIQID%5D&u=6e3ab59c527a3cc8ef560eeb5&id=9b83534a50)
  - [ ] Finalize [product marketing doc](https://docs.google.com/document/d/1jgXFkDF25hPJLYHiyN3_js09dDyyGSWXyXIGITEpsUU/edit?usp=sharing) for automated code reviews
  - [ ] Mention other initiatives?
  - [ ] Slack deep linking for feedback
  - [ ] [Final draft](https://docs.google.com/document/d/1StimX2mHeW8cJD41cbbhzluhVPGABn2RV-STBLI1cv0/edit?usp=sharing) for review by Leadership
- [ ] Design review 
  - [ ] Review 508 Accessible best practices.
  - [ ] Route all feedback to #vsp-newsletters channel?
  - [ ] Newsletter Helpfulness rating 
- [ ] From email address
  - [ ] Setup access to our va.gov emails
  - [ ] Setup platform-feedback@va.gov and distribution list for replies
- [ ] KPIs are defined and tracked
  - [ ] Setup Mailchimp analytics
  - [ ] Setup [Google Analytics / Google Tag Manager](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/analytics-communication-guide.md#requesting-google-analytics-implementation-or-qa)
- [ ] E2E testing
  - [ ] Desired number of users: 3-5
  - [ ] Send participants a [link to subscribe](https://mailchi.mp/334fcd88fdc3/va-platform-newsletter) to the newsletter via Slack.
  - [ ] Send newsletter to subscribers via Mailchimp.
  - [ ] Ask participants to confirm newsletter renders correctly and links work  
  - [ ] Confirm analytics are coming through.
- [ ] Soft launch
  - [ ] ~20 “real users”
  - [ ] Send participants a link to subscribe to the newsletter via Slack.
  - [ ] Success metrics
    - [ ] 100% of emails opened
    - [ ] 100% click-through rate for links
    - [ ] Qualitative feedback from survey
  - [ ] Go Live!
    - [ ] Collaborate w/ Product Support and utility devs to establish support plan
    - [ ] [Go/No Go meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/go-no-go-meeting-template.md) 
    - [ ] Announcement in Slack channels and TOTs with link to subscribe
    - [ ] Import email addresses from VFS team roster
    - [ ] Access to newsletter from Documentation Homepage
      - [ ] "What's New" banner that opens the newsletter doc when clicked.
      - [ ] Link in the Working with the VSP section.

**Comment by rroueche** [comment]
@jchasia-adhoc nice! thank you for this clear list ^
