### ISSUE TITLE
Refactor and streamline error handling code

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#6990]
## Background

As a complementary body of work to upgrading [Sentry](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6769), we should address some of the finer points of our error tracking code throughout vets-api. 

This will help set the tone and procedures for future VFS teams hoping to leverage Sentry for debugging their features.

## High Level User Story/ies
As an engineer contributing to vets-api, I need clear guidelines on error tracking so I can fully leverage Sentry in the debugging process.

## Hypothesis or Bet

If we refactor and streamline error handling code then we expect VSP users to...
- ...further use qualitative error data to drive VFS feature development
- ...comply with platform standards for error handling and performance observability

## OKR

Specifically, this effort will help to reach the following results:

- Provide an avenue for customers to track error-based KPIs **(O2KR2)**
- Increase VA.gov user satisfaction by reducing unexpected errors **(O2KR3)**
- Increase affirmative response from VSP teammates complying with error handling **(O5KR1)**
- Allow for automatic enforcement of error volume **(O5KR3)**

## Definition of done

This epic is complete when....

- [ ] ... error handling code is well documented
- [ ] ... new engineers (and others) can understand how to implement a new custom error handler
- [ ] ... error handling is automatically engaged for vets-api code

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
