### ISSUE TITLE
[FE] Update Appointment List to New Day-of-Week Order 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#69903]
## Wireframes
[Wireframe ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69902)

* Update font size and spacing

## Tasks
- [ ] [FE] Update Appointment List to New Day-of-Week Order 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey Is the only change we need the size and spacing of the day name and number?

**Comment by loripusey** [comment]
@zach-park @benbrasso-agile6 @cgednalske Can you comment on what is needed for this ticket?

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/69902#issuecomment-1821287004

**Comment by brianseek** [comment]
This is merged and ready to be validated. 
Screenshot:
<img width="116" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2kwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8419d306f4b42e51078208f1030db3621b611a3f/localhost_3001_health-care_appointment-pre-check-in_appointment-details_0001-0001%20%282%29.png" alt="localhost_3001_health-care_appointment-pre-check-in_appointment-details_0001-0001 (2).png" />

**Comment by zach-park** [comment]
@brianseek , I noticed that the dividers appearance looks a bit out of place though. The dividers called out with red arrows should be there. And there should be narrower dividers where the blue arrows are. I've attached a screen capture from the wireframe. Is it something that can be looked into? Thank you again!
![localhost_3001_health-care_appointment-pre-check-in_appointment-details_0001-0001 (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91493630/3d4040c1-72ee-4bbb-85cf-8f1f32b851f1)

Wireframe:
![Screenshot 2024-05-03 at 12 55 56 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91493630/c12ce431-a278-4990-b93a-5d722c653595)

**Comment by brianseek** [comment]
Thanks @zach-park I think there are a lot of areas where the figma has evolved since we initially started working on this. We really need to do a full audit. There are also a lot of areas where unified figma isn't current. 

For this ticket, the scope is just the date display. We do need to get together for a ux/eng sync for a unified audit though.

**Comment by loripusey** [comment]
I'll create a ticket to audit & update unified.

**Comment by benbrasso-agile6** [comment]
Yeah, the [Design Priority 1 page in Figma](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=0-8045&mode=design) was never cleaned up. The only clean up page is the [Design page](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=0-272&mode=design) for the unified appts Figma file.

**Comment by brianseek** [comment]
@benbrasso-agile6 / @loripusey / @zach-park is this one good to close?

**Comment by benbrasso-agile6** [comment]
THe date set up in that first screenshot looks good to me. I'm fine closing.

**Comment by zach-park** [comment]
Yes. Thank you!
