### ISSUE TITLE
[Design] Update Wireframes to New Day-of-Week Order in Appointments List 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#69902]
## Background

[VAOS Figma file that shows date order flipped on appointments list](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?type=design&node-id=5359%3A89369&mode=design&t=QqHjPsXHEcXtMYTg-1)

[VAOS Figma file for spacing guidelines](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?type=design&node-id=4074%3A65409&mode=design&t=QqHjPsXHEcXtMYTg-1) 

[VAOS Figma file for aria labels](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?type=design&node-id=1468%3A67095&mode=design&t=QqHjPsXHEcXtMYTg-1)

Why did VAOS make this change? 

> Ah, yes. It was based of feedback from dev and a11y, to bring a bit more continuity between the other screen sized. We had antes mobile to match tablet and desktop designs.
I can find documentation to support

[Slack thread from Cierra](https://dsva.slack.com/archives/C03CGTDLTFF/p1700006820292629)

## Tasks
- [x] Update Wireframes to New Day-of-Week Order in Appointments List for Priorities 1 page & Design Page
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske @ytsaoca , the new day-of-week order is ready to ve validated (Please also note that all priority pages are also updated). 

Design page:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas

Priority 1 page: 
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas

**Comment by benbrasso-agile6** [comment]
Looks like VAOS is using 20 size, 26 line height vs. 17 for the day of the month. We want to match?

**Comment by benbrasso-agile6** [comment]
Good strategy updating the symbols 👍

**Comment by zach-park** [comment]
> Looks like VAOS is using 20 size, 26 line height vs. 17 for the day of the month. We want to match?

Thanks for catching them. I updated them. And they should be ready now. :)

**Comment by benbrasso-agile6** [comment]
@loripusey for the FE ticket: 

Wireframe - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/oM8pbPx#Version

> For the appointment list, date is size 20, line 26. Day of week is size 16, line 24. And, the order is vertically flipped.

**Comment by benbrasso-agile6** [comment]
@zach-park nice work, validate
