### ISSUE TITLE
VA Design Meeting Presentation

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#69919]
## Issue Description
Presenting on work so far with the ARM team including analytics, user testing, and secondary research.

---

## Tasks
- [x] Create report
- [x] Review with team
- [x] Update with revisions
- [x] Present to larger team

---

## Acceptance Criteria
- [x] Presented to larger VA team

**Comment by jfinnerty13** [comment]
Deck (mostly) finalized and ready to go. https://docs.google.com/presentation/d/1sxCiN-EYiaP7bEIDSpdkHpJD1aJieDqngYhhLp5meTk/edit?usp=sharing
