### ISSUE TITLE
Identity Dashboard (FE) - Teams management integration - Team View

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#69913]
## Description
This is part of the work that is required to fully integrate the Teams management (Teams page) with the Backend. This ticket focuses on hooking up the "Team View" page.

## Tasks
- [ ] When on the "Teams" page
  - [ ] Create a Fetch request to the BE API to see if the teams exist and conditionally render the "Table of Teams" or the "Empty State Teams" page
    - [ ] When on the "Table of Teams" view
      - [ ] Clicking the "Modify" button takes me to the "Edit my team" page
    - [x] When on the "Empty State Teams" view
      - [x] Current functionality exists

**Comment by ianmagenta** [comment]
This is currently blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/73169

**Comment by asg5704** [comment]
Closing as IDD is dead
