### ISSUE TITLE
Identity Dashboard (FE) - Teams management integration - Register Team

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#69910]
## Description
This is part of the work that is required to fully integrate the Teams management (Teams page) with the Backend. This ticket focuses on hooking up the "Register A Team" page.

## Tasks
- [x] On the *Register a new team* page
  - [x] When clicking the "Register team" button
    - [x] A fetch request occurs to the BE API to "register a new team" endpoint
- [x] Ensure that this works properly without needing to mock a user via the backend.
