### ISSUE TITLE
Copy of ARM Nav & Search - User Test - Conduct Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#69918]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
1. Navigation
2. Search
---
## Tasks
- [ ] Complete interviews
- [ ] Manage interview day to day (team and recruiter coordination, debriefs, interviews, etc.)
- [ ] Download videos and transcripts
- [ ] Compile notes
- [ ] Upload notes, transcripts, and video to Sharepoint
- [ ] Upload notes and transcripts to EnjoyHQ
- [ ] Create Zenhub ticket for analysis and reporting
---
## Acceptance Criteria
- [ ] All documents uploaded and ready for analysis & reporting

**Comment by jfinnerty13** [comment]
This may have to be split for the documenting in GitHub and EnjoyHQ portions @oddball-lindsay but playing it by ear and will do so if deemed necessary.

**Comment by oddball-lindsay** [comment]
Seeing some potential risks:
1. Data integrity: Janelle, Michael, Lindsay will investigate to understand the level of severity
2. Search terms are not being accounted for: work with CAIA to ensure terms pull up accurate search results (e.g. don't return information around nurses)

**Comment by jfinnerty13** [comment]
First draft done - in review with ARF and ARM teams. https://docs.google.com/document/d/10JrvAG6YXLx0kVsjZ-1SWRt6ffOPVv3VMSiMBgkVy_4/edit?usp=sharing

**Comment by jfinnerty13** [comment]
Report: https://docs.google.com/presentation/d/1MRX--_ulcdLjGyu87SQaxVsfWEgixBsX5cJFFO3Sq44/edit?usp=sharing

Presentation next Wed
