### ISSUE TITLE
Identity Dashboard (FE) - Teams management integration - Edit Team

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#69911]
## Description
This is part of the work that is required to fully integrate the Teams management (Teams page) with the Backend. This ticket focuses on hooking up the "Edit Team" page.

## Tasks
- [ ] On the "Edit your team" page
  - [ ] When clicking the "Add" button
    - [ ] A fetch request occurs to the BE API to "modify" users belonging to a team

**Comment by asg5704** [comment]
Closing as IDD is dead
