### ISSUE TITLE
Deprecated Page Issue

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#69926]
## Info
While deploying page: https://vfs.atlassian.net/wiki/spaces/pilot/pages/edit-v2/655032351, we noticed that there is a link to this deprecated page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/manual-review-triggers.md.

We need to reach out to the PM (Alyssa) of the deprecated page to find out if it needs to be resurfaced, or the link needs to be updated to something else.

## Tasks

- [x] Reach out to the PM (Alyssa) of the deprecated page to find out if it needs to be resurfaced or what. 
- [x] Review edits.
- [x] Prepare page for deployment.
- [x] Deploy page.

## Acceptance Criteria

- [x] Page has been updated with new, or updated content.
- [x] Page has been deployed and is live.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/69926?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
SME suggested the best course of action is to resurface/un-deprecate the page.

**Comment by BSmolensky** [comment]
The page has been updated and is ready for deployment.

**Comment by johnny-jesensky-adhoc** [comment]
This page was deployed on 12/13. Have checked this, and the links seem to be corrected. Moving this to _Done_.
