### ISSUE TITLE
Design to help Product refine engineering tickets for FE Pension work (Step 3)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69925]
## Issue Description
As a product manager,
I need to ask Designer's help to refine upcoming tickets created for frontend engineering work against the latest Design files,
so that we can proactively identify any missing acceptance criteria to the work for Pension engineers.

---
## Tasks
- [ ] Review the following set of engineering tickets and their acceptance criteria
- [ ] If needed, edit the tickets' description, acceptance criteria and/or any other information in the ticket that would help clarify the task for engineers.
_- Some examples of information that may be missing from the tasks are Page Titles for new pages, or incorporating new details included in recent comments in Sketch_ 

[MVP] Step 3: Create new page and questions for Enter pension details #69746
[MVP] Step 3: Create new page and questions for Claimant not determined disabled #69748
[MVP] Step 3: Create new page and questions for Enter nursing home status #69750
[MVP] Step 3: Create 2 new pages and questions for Claimant lives in nursing home #69751
[MVP] Step 3: Create new page, question and validation for Enter special monthly compensation status #69752
[MVP] Step 3: Match all questions and copy to designs for VA medical center pages #69942
[MVP] Step 3: Create 2 new pages and questions for Federal medical center status #69755
[MVP] Step 3: Match questions for over 65 and employment status #69757
[MVP] Step 3: Match questions and add new fields for Current employment #69758
[MVP] Step 3: Match questions and add new fields for Previous employment #69871

## Acceptance Criteria
- [ ] Designer will have reviewed the set of engineering tasks provided and made any edits needed to help clarify information for engineers taking on this work.
