### ISSUE TITLE
Audit & update documented workflow for running on-premise Sentry in local development environment

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#6992]
## User Story or Problem Statement
As a VSP engineer. I need accurate documentation for on-premise Sentry administration so I can manage configuration and upgrades with low toil.

## Background

- [Current documentation](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/README.md#runningtesting-sentry-locally)
- [Some notes for local testing here](https://hackmd.io/czGh4REETQmEGcNyXD14xg?both#Notes-for-starting-up-virual-machine) -- update the documentation with this.

## Goal
Reduce the overall effort and lift in maintaining an on-premise Sentry cluster by having a low-lift procedure for running and testing Sentry locally.

## Objectives or Key Results this is meant to further

O3 KR2

This will help improve the stability of our teams by improving documentation reliability. 

## Tasks
- [ ] Successfully provision and deploy a locally hosted Sentry instance by following current [documentation](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/README.md#runningtesting-sentry-locally)
- [ ] Modify documentation to reflect any additional or modified steps taken. Include operating system and tool version specifics.
- [ ] Convince another engineer to blind-test the new documentation draft and provide feedback

## Acceptance Criteria
- An engineer can follow the documentation to successfully...
    - [ ] generate events from a local `vets-api` instance 
    - [ ] generate events from a local `vets-website` instance (?)
    - [ ] provision and boot a working local Sentry cluster 
    - [ ] browse to the local Sentry UI and see event details

---

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
Note: We may want to include somewhere in the local setup documentation that an MFA session will need to be activated in order to use vagrant. [Explanation here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/vagrant/README.md#aws-profile-and-authentication)
