### ISSUE TITLE
Sentry/error handling setup

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#69920]
## Tasks
- [x] Waiting on Sentry access approval from VFS
- [ ] Push errors to ARM Sentry

## Acceptance Criteria
- [ ] Errors are being logged to the ARM team's Sentry tool
