### ISSUE TITLE
Update Frontend Best Practices with Pull Request Review Process

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69934]
## Description 
This ticket will house the task of reviewing and updating the Pull Request review process outlined here: [Frontend Support Responsibilities](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630975664/Front-end+Support+Responsibilities).

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Point to this page (after it has been updated): [Pull Request Best Practices](https://vfs.atlassian.net/wiki/spaces/pilot/pages/688259145/Pull+request+best+practices)
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
PR information synced with Tier 1 support requirements. Verified links to PR review queue in CoP review responsibility section along with reminder to check PRs several times a day. Tier 1 process updated substantially.
