### ISSUE TITLE
Create Pull Request Best Practices for Tier 2

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69939]
## Description 
This ticket will house the task of creating documentation around Tier 2 best practices for Pull Requests. Note that this ticket is dependent upon the work around automating PR request status updates in Slack (Joe Knipes ticket).

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Interview Tier 2 engineers to identify what their best practices may be for time management, reviewing PRs efficiently, etc.
- [ ] Type up best practices in document [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2510194732/Pull+Request+Code+Review+Procedures+-+DRAFT)
- [ ] Send the documentation to the same engineers and Alyssa for review 
- [ ] Publish the page
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Alyssa to schedule call to discuss with Tier 2 and run through a mini blueprint of the process.

**Comment by alyssagallion** [comment]
Discussion with Clint about who would own something like this. 

Clarify with Eric if this can be automated vs. manual.
