### ISSUE TITLE
Update Advanced Support Best Practices (Tier 2) with Pull Request Review Process

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69936]
## Description 
This ticket will house the task of reviewing and updating the Pull Request review process outlined here: [Advanced Support Best Practices (Tier 2)](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices+Tier+2)

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Confirm PR review procedure with at least 1 member of each CoP
- [x] Ask at least 1 other CoP member to review process async and revise
- [x] Point to this page (after it has been updated): [Pull Request Best Practices](https://vfs.atlassian.net/wiki/spaces/pilot/pages/688259145/Pull+request+best+practices)
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Completed. Closing!
