### ISSUE TITLE
Copy of Update DevOps Best Practices with Pull Request Review Process

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69932]
## Description 
This ticket will house the task of reviewing and updating the Pull Request review process outlined here: [DevOps Support Responsibilities](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2425552908/DevOps+Support+Responsibilities#AWS-IAM-Expiration).

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Point to this page (after it has been updated): [Pull Request Best Practices](https://vfs.atlassian.net/wiki/spaces/pilot/pages/688259145/Pull+request+best+practices)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Duplicate ticket. Closing.
