### ISSUE TITLE
Update Pull Request Best Practices Page

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#69937]
## Description 
This ticket will house the task of updating this page: [Pull Request Best Practices](https://vfs.atlassian.net/wiki/spaces/pilot/pages/688259145/Pull+request+best+practices).

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Update this page to reflect step-by-step instructions for reviewing PRs: [Pull Request Best Practices](https://vfs.atlassian.net/wiki/spaces/pilot/pages/688259145/Pull+request+best+practices)
- [ ] Update this page to reflect the steps after a PR review is denied (both for Tier 2 and Tier 1)
- [ ] Update this page to reflect the steps after a PR review is approved (both for Tier 2 and Tier 1)
- [ ] Make sure that the links to the individual development specialty queues are listed
        - [ ] [Backend Queue](https://github.com/search?q=team-review-requested%3Adepartment-of-veterans-affairs%2Fbackend-review-group+team-review-requested%3Adepartment-of-veterans-affairs%2Fva-api-engineers&type=pullrequests&state=open&s=created&o=desc)
        - [ ] [Frontend Queue](https://github.com/search?q=team-review-requested%3Adepartment-of-veterans-affairs%2Fva-platform-cop-frontend+is%3Aopen&type=pullrequests&state=open&s=created&o=desc&p=1)
        - [ ] [DevOps Queue](https://github.com/search?q=team-review-requested%3Adepartment-of-veterans-affairs%2Fva-platform-cop-devops&type=pullrequests&state=open&s=created&o=desc)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@johnny-jesensky-adhoc Hey Johnny! We created this ticket before we identified our new process with you. I believe you have a ticket for updating this page? Maybe we could sync up on it to see if we should just close this ticket, send to you, or update the scope of the ticket you already have? Sorry for the extra work if it exists already!

**Comment by lindsay-insco** [comment]
Passed along a copy of the existing best practices page with updated information!!

**Comment by lindsay-insco** [comment]
Copy of draft document [here](https://vfs.atlassian.net/wiki/spaces/~627d71088dd5f30068565fbc/pages/edit-v2/2877390849?draftShareId=82b8a56a-dd85-4e1e-bca3-572e1d2270be)
