### ISSUE TITLE
Shadowing Research: Interview Preparation 

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#69945]
## Issue Description

This ticket is to designed to capture the work to prepare for the upcoming shadowing interviews.  
---
## Tasks
- [x] Run a pilot session of the study
- [x]  Speak with Heather Real (VBA) about her recent experience filing (This depends on their availability) 
- [x] Prepare data management (Mural notes, observation/notetakers guide, etc)
- [x] Develop backup protocol in case Veteran is blocked from filing (staging profile, amendment to conversation guide with more questions) 
- [x] Stay in touch with Perigean throughout the recruit

---
## Acceptance Criteria
- [x] Data management plan is set up
- [x] We have a plan to handle issues during observation

**Comment by evelynhilbrichdavis** [comment]
Ran a pilot with Mike on 11/16, a great opportunity to think through how we will handle some of the blockers/questions participants might have. 
A majority of our participants have been scheduled--great news for what was anticipated as a difficult recruit.
