### ISSUE TITLE
BE | Profile | Military Info | Add endpoint returning all military info

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#69973]
## Background
Create a VA.gov API endpoint that returns all military information for a veteran.  This endpoint can be called from the browser and will help us get a better understanding of what military data values look like in both staging and production.

Ensure this endpoint is only callable when the feature toggle is enabled. 

## Tasks
- [x] Feature toggle
- [x] Service code
- [x] Controller
- [x] Specs

## Acceptance Criteria
- [x] The endpoint has a feature toggle.
- [x] The endpoint is secure (only available to authenticated users).
- [x] The endpoint can be called from a browser for authenticated users.

**Comment by tpharrison** [comment]
A user's military information can now be viewed in staging.

Steps:
1. Login with a user that has military information (try user16 or user226)
2. Once logged in, open a new browser tab and navigate to this URL...
    `https://staging-api.va.gov/v1/profile/military_info`
