### ISSUE TITLE
TOU (FE) - Create auto-provision route

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#69981]
## Description
Cerner (My VA Health) requires an auto-provisioning route on the FE so that a cookie is created to allow for SSOe enablement for Cerner users

## Tasks
- [ ] Create a separate route on the FE for My VA Health auto-provisioning
- [ ] Create a component that automatically calls the `/terms_of_use_agreements/update_provisioning` (API)
  - [ ] On success => Redirect user to `ssoeTarget` (after parsing)
  - [ ] On failure => Redirect user to `auth/login/callback` page with a code `110`
- [ ] Update and/or create unit tests for functionality
