### ISSUE TITLE
[FSR] Validation e2e testing

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#70000]
## Description
Write e2e cypress tests that focus on validation for progression blocking. If a user doesn't have a valid input for a required page they should be blocked from continuing with an error message. 

## Tasks
- [ ] Write e2e cypress test to test progression blocking validation

## Acceptance criteria

- [ ] Non-flaky e2e validation test 

## Testing
- [ ] Stress test new test locally to confirm it will pass in CI/CD

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
@Dr-Pongo -is this still required?

@Tom-Davis
