### ISSUE TITLE
Update developer documentation

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#70011]
### PROBLEM STATEMENT:
There are developer docs that have not been touched in a long time. 

_How might we work with the platform content team to identify high prio docs for review AND develop a team process to complete the review and/or updates?_

### ADDITIONAL INFORMATION
[Audit](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit?usp=sharing) of out of date developer docs

### DEFINITION OF DONE
- [ ] Documents identified by the platform content team have been reviewed for accuracy
- [ ] If document requires update(s), update(s) are made
- [ ] If document does NOT require update, the engineer reviewing documentation opens the doc for editing, then clicks save to indicate that this doc has been reviewed
