### ISSUE TITLE
MyVA Dashboard - Card Redirect/Clean Up

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#70014]
## Issue Description

As part of the recent updates to the [MyVA dashboard](https://va-gov.domo.com/page/1167851935) we created a new, more granular dataset 'BQ - All MyVA Users, Pageviews and Events 2' that can likely be used to replace the other MyVA datasets in an effort to minimize the number of datasets needed to support the dashboard (we did a similar thing for Profile dashboard with the 'BQ - Profile Detail' dataset). 

Here is a [list of all the cards on the dashboard and corresponding Domo dataset](https://docs.google.com/spreadsheets/d/1UsY1hFdBupmZP4LRJOcC3o0mP45iJDZmw8RpPoQDiqU/edit#gid=1242714507). Please review each as indicated to see if the new 'BQ - All MyVA Users, Pageviews and Events 2' dataset can be used to populate.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83169b163482c53deb48f62966bb7b86af5eeceb/image.png)

---
## Tasks
- [x] Review each card on the dashboard (per [mapping worksheet](https://docs.google.com/spreadsheets/d/1UsY1hFdBupmZP4LRJOcC3o0mP45iJDZmw8RpPoQDiqU/edit#gid=1242714507))
- [x] Create a new/copy of card and redirect to new BQ - All MyVA Users, Pageviews and Events 2 as applicable
- [x] QA existing vs new cards
- [x] Replace current cards with new cards applicable

## Acceptance Criteria
- [x] Cards on the MyVA dashboard have been redictected to the new dataset as applicable (later we will go in and remove the older legacy datasets)
---

**Comment by michelle-dooley** [comment]
Total events calc 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTM5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6ca1dd7d5d9fa9144e5006e4ca27a0a0ab40746/image.png)

**Comment by Blivaditis** [comment]
New data set is missing needed variables and is extremely large causing cards to not load. It was decided that the new dataset will not be used for these cards. Issue will be looked at again once GA4 is implemented.
