### ISSUE TITLE
FE | Profile Hub | Implement Recommendations from our Usability Study 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#70016]
## Background
We completed our usability testing and need to now implement the design feedback from this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69410). 

- [Mobile](https://www.sketch.com/s/b41a687f-8ab8-4be1-b189-692e5818cffd)
- [Desktop](https://www.sketch.com/s/b41a687f-8ab8-4be1-b189-692e5818cffd/p/EFCD1C39-A0C1-4A07-8510-1C0A7713FA1A/canvas) 

The main thing that has changed is the description language for each card, and we've added one additional link to the direct deposit card. 

## Tasks
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [x] Notify PM if this needs to be deployed to Staging behind feature flag
  
## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] All axe checks pass
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed
