### ISSUE TITLE
[CDP] Bug - Investigate authenticated redirects

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#70029]
## Description
Some authenticated users are experiencing an incorrect redirect from `*.gov/manage-va-debt/debt-balances`/`*.gov/manage-va-debt/copay-balances` destinations back to the app entry point of`*.gov/manage-va-debt/`. It seems to only happen the first time they attempt to access the page via a link. 

[Here's a link to the initial discussion from slack](https://dsva.slack.com/archives/CPE4AJ6Q0/p1699899063680819)

There's two spots where we redirect users back to the entry in the [CombinedPortalApp.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/combined/containers/CombinedPortalApp.jsx) which could be causing issues: 

- [User is not authenticated and profile is loading](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/combined/containers/CombinedPortalApp.jsx#L46-L55)
- [Combined debt portal feature flag is not active](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/combined/containers/CombinedPortalApp.jsx#L67-L77)
- Outside of this there are some platform level redirects, but I don't think they meddle with our inner app links

## Steps to recreate
Kind of tricky to recreate directly since it only happens the first time you try and navigate to a balance page, but I noticed it the first time with the following steps:

1. Login to user 228 on va home page (local or staging environment)
2. Copy/paste the copay url directly in the address bar (http://<environment>.va.gov/manage-va-debt/summary/copay-balances)
3. Use the "check the details of your current debt" link in the informational alert to navigate to the debt balances page direclty
4. It _should_ incorrectly redirect back to the `/manage-va-debt/` page. 

## Tasks
- [ ] Recreate issues with redirects
- [ ] Identify root cause of unecessary redirects
- [ ] Fix identified issue _OR_ create appropriately sized ticket to addresss.
- [ ] Notify related parties (mentioned in slack thread linked above) of the fix)

## Acceptance criteria

- [ ] Veterans are no longer unnecessarily redirected when accessing debt/copay balances directly
- [ ] Relevant parties notified of fix

## Testing
- [ ] Confirm functionality

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
2/26/24: Request from UX team:
"Might already be on front-end team’s radar but is it possible to prioritize this ticket? It will improve the UX of the debt portal (less clicking).
https://dsva.slack.com/archives/CPE4AJ6Q0/p1706716362763979"

**Comment by HeatherRienks** [comment]
Also, is this ticket, #62171 related to this effort?

**Comment by OptionSelect** [comment]
Brought into sprint late, pulling future stuff in because we had finished our goals for current!

**Comment by OptionSelect** [comment]
Per convo in threads, PR'd fix and tested on staging. Good to go!
