### ISSUE TITLE
FE | Enhanced Military Information | Link on Military Info Page 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#70025]
## Background
Making use of the endpoint Tom created #69973 we need to add a link to the military information page that opens to the data returned from the endpoint. 

Should be behind accessible behind the feature flag. 

## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  
## Acceptance Criteria
- [ ] when the feature toggle is enabled we've got a functioning link that takes to a page where we can copy out all of the user's military info

**Comment by mtcA6** [comment]
duplicated by this ticket:
- #70348
