### ISSUE TITLE
DR | Move VeteranInformation Component into Shared Components

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#70020]
## Value Statement
**_As a_**  Developer
**_I want to_** be refactor the `VeteranInformation` component
**_So that_** we can have a consistent interaction across our appeals forms and reduce future tech debt

## Background Context

- Research was completed with the assistance of GitHub codeclimate to identify potential refactoring to reduce tech debt. As a result, the goal is to bring the ratings to an A - to make code more manageable.
- The VeteranInformation component has a Code Climate Ratings of D,D and B with a code coverage < 80%
- Refactor 
  - `const mask` between all 3
  - `<div className="blue-bar-block">` in 995(SC)/996(HLR)

## **File Ratings**

| File | Rating |
| ------- | ------ | 
[src/applications/appeals/995/components/VeteranInformation.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/components/VeteranInformation.jsx) | D |
[src/applications/appeals/996/components/VeteranInformation.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/components/VeteranInformation.jsx) | D | 
[src/applications/appeals/10182/components/VeteranInformation.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/components/VeteranInformation.jsx) | B | 

## **Code Coverage**

| VeteranInformation.jsx | Statements | Branches | Functions | 
| ------- | ------ | ------ | ------ |
| 995 (SC) | 78.57% | 91.3% | 66.66% |
| 996 (HLR) | 78.57% | 91.3% | 66.66% |
| 10182 (NOD) | 78.57% | 91.66% | 66.66% |

## Out of scope

* Other apps/forms not in Decision Reviews
* Testing folder does not apply here

## Tasks

- [ ] Function moved into shared components folder
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Identify functions to be refactored
- [x] Have access to decision reviews folder (src/applications/appeals/<AppealForm>/components) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/components/VeteranInformation.jsx)
  > 996 - Higher Lever Review (src/applications/appeals/996/components/VeteranInformation.jsx)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/components/VeteranInformation.jsx)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away and duplication in the PR is marked as fixed
