### ISSUE TITLE
Discovery - Mapping of Conditions to Section V columns 1, 2, 3 and 4

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#70037]
## Issue Description
We need to know how the current 526 digital form fields map to all the schemas and the pdf for list of conditions.

Check in VBMS UAT, efolder to access the test pdf. Emily had given a demo on how to access it.
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [x] List of form fields that relate to conditions
- [ ] Map of form fields to schemas FE, BE, shared, JSON schemas /pdf for conditions in section V columns 1,2,3,4

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Some quick findings from experiments in Staging/VBMS UAT

- Staging is using the "SEP 2019" version of the 526, while we've been focused on "NOV 2022"
- In the "SEP 2019" version, our "Section V" is actually "Section IV" (but otherwise looks the same)
- "SEE ATTACHED" is _always_ written to the first line of Section V, with the data instead written to the overflow page
- Column 1 is populated by the condition name
- Column 3 is populated by the new/added option selected (i.e. "Caused by an in-service event, injury, or exposure"), plus the condition description on the next line- essentially combining the contents of 2 different fields
- Columns 2 and 4 are not being populated (as far as I can tell from just testing)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68383c84b20baf23b68e177a257bef5162425a38/image.png)

**Comment by RakshindaAslam** [comment]
@sethdarragile6 - when would the "secondaryDisabilities" section in the schema be filled out and with what information?

**Comment by sethdarragile6** [comment]
> @sethdarragile6 - when would the "secondaryDisabilities" section in the schema be filled out and with what information? cc @christinec-fftc

@RakshindaAslam The "Option 2" of the above mural should answer your basic question. Ultimately, it only amounts to writing "Secondary to [some Primary Condition X]" in column 3 of the form.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92405130/d68327d1-74b9-4a78-815c-ba4d6342a03e)
