### ISSUE TITLE
PagerDuty Access Steps for Tier 1

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70047]
## Description 
This ticket will house the task of outlining the steps to grant access to PagerDuty. The process can be added to this page: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838560893/Granting+Access+to+PagerDuty

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Add Table of Contents to documentation to [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838560893/Granting+Access+to+PagerDuty)
- [x] Add requirements for granting access to a user to [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2838560893/Granting+Access+to+PagerDuty)
- [x] Add step-by-step process for granting access to PagerDuty
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@bdech See conversation with Erika, Clint, and Johnny I added you to today.

**Comment by bdech** [comment]
This sprint task is completed. Closing out.
