### ISSUE TITLE
Burial | Update URL and Breadcrumb

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70049]
## Issue Description
_[CAIA has requested](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68984#issuecomment-1813052852) that the url and breadcrumb for the burial 530 form be updated to align with VA design standards._

Current url: www.va.gov/burials-and-memorials/application/530/

---
## Tasks
- [ ] Update the base URL to: ??? (need updated url www.va.gov/burials-and-memorials/burial-allowance/application/530/)
- [ ] Update breadcrumbs...
   - [ ] From: Home > Burials and memorials > Burial allowance > Review burial benefits application
   - [ ] To: Home > Burials and memorials > Burial allowance > Apply for burial benefits

## Acceptance Criteria
- [ ] New ulr is:
- [ ] New breadcrumbs appear as:
---

**Comment by fiorella-io** [comment]
The breadcrumbs have already been updated on the new burial designs
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/6bc41c5c-b4b7-4082-b567-479157ca7b4c)

**Comment by steele-lm** [comment]
@fiorella-io Reviewing this old ticket...do we need to action or work with the Platform Team on the requested url update for burial?

**Comment by fiorella-io** [comment]
@steele-lm What is the original CAIA ticket? I wonder if their request was not for the form but the information pages like it was for Ch 31

**Comment by steele-lm** [comment]
@fiorella-io I found the original reference! It was [a comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68984#issuecomment-1813052852) in the original CAIA intake request. I'll add the comment link to the body of this ticket as well.

**Comment by fiorella-io** [comment]
@steele-lm Based on that comment, we need to create a dev ticket to update the Burial form URL.
The URL should say `www.va.gov/burials-and-memorials/burial-allowance/apply-for-burial-benefits` 
<img width="80%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/3b07f0ef-2fca-484e-93ab-a5346fe69f6e">

Supplemental claim example:
<img width="50%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/65800469-e41b-46f0-bb7e-f8ba1aef592b">

**Comment by steele-lm** [comment]
I created a dev ticket for the url update: #76700
