### ISSUE TITLE
[MVP] SPIKE: Proof of concept to map data to PDF, better understand LOE

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70050]
## Issue Description
As a Pension team,
**we need to understand what it will take to map the new online questions of the Pension form to the PDF VSRs receive on the business end,**
so we can gather any remaining information we need to undestand the requirement to map new fields to the PDF form,
so we can get a better sense of the engineering level of effort.

[This document](https://docs.google.com/document/d/1eyL42-PtY6xxWc1-luTwekSNnK6InI_Rs6aN1I7SDVk/edit?usp=sharing) has been started that shows what all the new questions are on the online Pension form.

The new version of the PDF we are referencing is this one.

---
## Tasks
- [x] Investigate how to map the new online form questions found on the document provided above to the new version of the PDF form
- [x] Identify any information still missing in order to understand the level of effort
- [x] Estimate a level of effort 
- [x] Share findings with technical lead, product manager and VA stakeholders when necessary

## Acceptance Criteria
- We will have a better sense on the level of effort to map the new questions on the online Pension form to the new PDF version of the form.

**Comment by vbellissimo** [comment]
cc @mjknight50 for awareness

**Comment by danlim715** [comment]
With the exception of page 15 of the new PDF, the rest of the pages have a similar number of fields on them. Following the steps outlined in the docs [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/pdf-generation), we can easily map attributes from the schema to the pdf. There will need to be an initial commit to push in the new PDF and PdfFiller classes. This can be done in a 1-pointer ticket. Once that's in, we can split up the work based on each section. There are 13 sections on the form as well as 2 worksheets for residential care facilities and in-home attendant expenses for a total of 15 tickets worth of work, ranging from 2-4 in score depending on the number of fields in the section. Once each ticket is created, I can also add in the list of PDFtk keys relevant to each section.

Finally, we will need a ticket for the schema changes to be added. I think there's 2 options we have for going about making schema changes:
1. We do a comprehensive analysis of all the fields that need to be added and make the schema changes before working on the rest of the work. The downside is that it's a lot more work up front, and we run into the possibility of adding redundant or unnecessary fields to the schema.
2. We move forward with the data mapping work first and leave notes and `TODO comments` along the way whenever any gaps in the schema are identified. Then at the end, we compile all those notes and add the schema fields that need to be added. The downside to this is that we will have to revisit and update the code to ensure all the TODOs are resolved.

I'm okay with either way so let me know which way y'all prefer!
