### ISSUE TITLE
Create Labels To Distinguish Between Support and Sprint Work

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70054]
## Description 
This ticket will house the task of creating a label to separate the data for support vs. sprint work. At the moment we show that it takes 13 days to close a ticket, which is true for sprint work but not for support work. Adding this label will allow us to distinguish between the two on this board: https://va-gov.domo.com/page/835197588

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Create a new label titled "Platform Support Ticket" and "Platform Support Sprint Work"
- [x] Make sure that the label appears in the [DOMO dashboard](a "Platform Support Ticket" Label ) (if not, reach out to Michelle Dooley)
- [x] Add the label to any tickets that fit in either category (i.e. Active Support Issues should all be tagged with "Platform Support Ticket" and all others should be tagged with "Platform Support Sprint Work"
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by jknipes** [comment]
@alyssagallion please review to close

**Comment by alyssagallion** [comment]
Labels have been created. Communicated to Team of Teams. Closing.
