### ISSUE TITLE
Prepare TestRail for NoK/EC Staging Review

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70067]
### User story

As a Cartographers team member, I want use cases and test cases for Next of Kin/Emergency Contact to be ready in TestRail, so that we are ready to run the tests for staging review when user research is completed and the integration is enabled.

### Notes
We are actively working to get the integration working ( #69061 ). Staging is currently using mock data, so all test users have the same data.

## Acceptance criteria

- TestRail test cases are ready to produce required QA artifacts for Staging Review (collab cycle [docs](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review))

## Tasks

- [x] Determine location in github for Use Cases
- [x] Write use cases
- [x] Create test cases from use cases in TestRail

**Comment by radavis** [comment]
To verify the Next of kin/Emergency Contact feature (aka Personal health care contacts), sign into staging, visit /profile, click on "Personal health care contacts".

Feature is currently read-only with static data since we do not yet have access to the API that provides us with this data.

**Comment by fbonds** [comment]
edited tasks

**Comment by fbonds** [comment]
Created initial use case document (draft)
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/next-of-kin-emergency-contact/use-cases#readme

Linked to other use cases at this location:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/use-cases

**Comment by fbonds** [comment]
Completed uses cases document

**Comment by fbonds** [comment]
Added test cases (2) to testrail:
Digital Service @ VA
Project: myHealtheVet
Suite: nok-ec

1 of 2
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31e01955dfe8062ab641269db883ed75e7790b12/image.png" alt="image.png" />

2 of 2
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7444a398dcc3aa64fc89ce64d85ad3f90bba57b5/image.png" alt="image.png" />

**Comment by fbonds** [comment]
@wesrowe @radavis How's this?

**Comment by radavis** [comment]
Hey, @fbonds. This looks great. I was able to follow the instructions for [Executing tests in Test Rail](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail) to create a [Test Run](https://dsvavsp.testrail.io/index.php?/runs/view/5073&group_by=cases:section_id&group_order=asc) and work through the test cases.

**Comment by radavis** [comment]
There are [instructions](https://depo-platform-documentation.scrollhelp.site/developer-docs/cypress-to-testrail-reporter-plugin-configuration) for connecting vets-website Cypress tests to Test Rail test cases. Suggesting we add this development work to a follow-on ticket.

Summary of instructions:
- tag Cypress test cases with Test Rail test ID
- discover and set env vars for Test Rail integration
- run custom reporter

**Comment by wesrowe** [comment]
@radavis, is that level of test rail integration typical in the ecosystem? if so, could you give me a draft user story to include in a new ticket? I'm missing the "so what" part – i.e., "As a Cartographers team member, I want to integrate Cypress with Test Rail, so that _________"

**Comment by radavis** [comment]
As a Cartographers team member, I want to copy execution records from Cypress e2e tests into related TestRail test cases, so that there is a trail of QA documentation for a feature.
