### ISSUE TITLE
NOD | Write and run script to submit un-submitted evidence uploads

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#70076]
## Summary

The goal of this ticket is to identify all NOD evidence uploads that were not submitted to Lighthouse due to a bug ([described here](https://dsva.slack.com/archives/C5AGLBNRK/p1700090171197059?thread_ts=1698163822.882939&cid=C5AGLBNRK)), and write a script to submit them.

## Tasks

- [x] Identify un-submitted evidence uploads
- [x] Write script to submit them
- [x] Add logging
- [x] Write tests
- [x] Get feedback from platform on how to run the script (e.g. directly in prod console, via rake task, as lib script).
- [x] Get feedback from Michel at Lighthouse.
- [x] Run script and review logs 
- [x] If necessary, make adjustments and re-run script until all submissions successful.

## Acceptance Criteria

- [x] Script done and approved by platform and Michel at Lighthouse.
- [x] Script is run in production, and logs show that each submission was successful.

## Definition of Ready
- [x] N/A.

## Definition of Done
- [x] Acceptance criteria met.

**Comment by data-doge** [comment]
@saderagsdale Ran successfully in production.  All 139 upload jobs successfully enqueued for all 48 affected Veterans.  All uploads jobs ran successfully ([See DataDog](https://vagov.ddog-gov.com/logs?query=%40named_tags.jid%3A%28%227dfce1ccbfe91f00ea95952d%22%20OR%20%2229a7a6ab19ddd0251b0d4122%22%20OR%20%2282ab0ef9c158eacf4595d5d5%22%20OR%20%22602715eb6d18e1c22d5df10e%22%20OR%20%22c40ad76d053954ab2f72970a%22%20OR%20%22bd5489d954dd318fbb865523%22%20OR%20%226c297566ec09c4a719fa6195%22%20OR%20%22c36f246848bc8a46c7f30d4b%22%20OR%20%228c3515bad91e06bfe42d04f0%22%20OR%20%222489ea9857cf9ae07787403c%22%20OR%20%22d62b64bfddf49c2f8d28be86%22%20OR%20%2253f3de1076eaf1f2d40224e6%22%20OR%20%222106b47f6fcc73593b9c7cb3%22%20OR%20%22a12f10920ee05f8ca6692a19%22%20OR%20%22e562432037c3b38a90f414c6%22%20OR%20%222da871f7147b0acf9e205b70%22%20OR%20%22d05055dbdd0aa99523c59247%22%20OR%20%22944113446db47c26a7bb6116%22%20OR%20%22a0707e5aed788b4760ef2b04%22%20OR%20%22895647a1117b98cdabc4c94f%22%20OR%20%223f7430e8e45d2863c5cf6d27%22%20OR%20%22df8d81302902cf6eebca52bb%22%20OR%20%22295c988e995a4d6a06180256%22%20OR%20%22ce3d16dd7922c1f023a2e1de%22%20OR%20%22f74434a280015a8fd39c48e2%22%20OR%20%22248fec528dac4396f3d86566%22%20OR%20%2203266765a2aeae1fc7930933%22%20OR%20%2275515f9b6d7f5243dd2671b4%22%20OR%20%220919e75cdda08c0ff1a7ea03%22%20OR%20%223c6b6adb8dc7765a5ee7b2b6%22%20OR%20%227d8095412277f58bfad8f985%22%20OR%20%22502130fe2fd7872c08cea7b8%22%20OR%20%223be746a7c5884c0f60d0c44b%22%20OR%20%22966a30a3b0179556d0eca0f9%22%20OR%20%22489195b973e400cdf4be2ab2%22%20OR%20%22039de63f0a701462a8ca1898%22%20OR%20%22dd7cbb4243a4e7b7f6f9620c%22%20OR%20%221207e08a6e1db4de0785af18%22%20OR%20%2222208ada6c0135361d504cc3%22%20OR%20%22c8dde6cfd2a72f2d131236b5%22%20OR%20%22a0e8d584f86a30e165f70410%22%20OR%20%221fb159c9922cae1e3970c36c%22%20OR%20%2239bb8c38d982e031f82eb9d9%22%20OR%20%22a03df0c3da996858f11dff11%22%20OR%20%228b759a202b0bb50696a3b7b4%22%20OR%20%227327766adab2795b8b97480d%22%20OR%20%22658107e3a512f55391eb6fa1%22%20OR%20%226531a7725737c231fb32cfbf%22%20OR%20%224b4cdda212498b42bfa7e1db%22%20OR%20%2251d1fda9e6a1fdb6ec610e78%22%20OR%20%22834d8797a030779193ab461e%22%20OR%20%22d96b6bec61a0496b53c8f685%22%20OR%20%22efa2f140c82696d14c0abdf0%22%20OR%20%2250e3fbf297e1b63fb926456f%22%20OR%20%2215b8e3eae9264021b27728d3%22%20OR%20%221c43b57fb3d0b6ff47d7e9e9%22%20OR%20%22f8a4c3be9a72218d8dc20c1a%22%20OR%20%22c2103b3df6c3249b2ddfcc97%22%20OR%20%2245faffa7746be02d6c7d9837%22%20OR%20%228d3455d397abec9f1ba5f43c%22%20OR%20%22ab9ac134cadb6642f3e1153c%22%20OR%20%22d56aa4ac973f3675c4f10f9f%22%20OR%20%22f8d9be52e6f7e8d6a3672929%22%20OR%20%2223c39f9a7a4148bf56a1e747%22%20OR%20%223f09ff9a6015735b45f6a9e3%22%20OR%20%2256953a413af5915ae318a232%22%20OR%20%22eadde6619b264a7716d41c0c%22%20OR%20%224288ea75892cc48494e50deb%22%20OR%20%221372ac0c645215abbe518440%22%20OR%20%2217cc763dfe431bdee2f30c1b%22%20OR%20%22bedc3440ece08e751ccb3311%22%20OR%20%22948feb4d058a9cef9e757910%22%20OR%20%22eae0cbdd138d73308e5cc21a%22%20OR%20%228e3772cfb96b4cb9982877d4%22%20OR%20%2296879d54a589e60555dc817a%22%20OR%20%2248d9df4e636499c1e37a9598%22%20OR%20%224ca7b7578a5ca76fd132c70a%22%20OR%20%22801369f4024762963a429ef3%22%20OR%20%2267d6cc9a392d86f18748b901%22%20OR%20%22d3a0c60253e5fb3d06d49d5f%22%20OR%20%226a0172f284dfdfe4e3a8de3c%22%20OR%20%22fecb760123968462ab8ddf15%22%20OR%20%2220b6a5d9fdbc42c20f9d235d%22%20OR%20%22357e4aa77582d3e514186ca2%22%20OR%20%2234a76aafd239bfa7dd0325a6%22%20OR%20%2259bd081af9303095a97f8dd7%22%20OR%20%22b60be5bda55d8c609b9306e7%22%20OR%20%228812a2e97b3696ef60adaa25%22%20OR%20%22b2dcbca00639c4bfd0aed9a1%22%20OR%20%22bbd67ea9db4a3d88b7879201%22%20OR%20%227a5a6af38e8995e776ca594e%22%20OR%20%2204941f7ad3192eb3c0f903b6%22%20OR%20%223b3519862890eb9fb17dac57%22%20OR%20%22d2cb7be95bb0ef0ad35356a3%22%20OR%20%22bb7d6aef5617c74fb25adf5a%22%20OR%20%22653875c1140b9dae29f5345e%22%20OR%20%225b7979c9a4553458012ad342%22%20OR%20%22a30fc10c08e32aad4e82fce1%22%20OR%20%22f2de6902bfc6f0887e36ce36%22%20OR%20%22ca128466653bf6a763b6c4ad%22%20OR%20%22a6367c217c6d7e75bccfce6f%22%20OR%20%22af09f3324d25bf50c03a753c%22%20OR%20%2269bcbadeb140e54c2b6587eb%22%20OR%20%221cfbf8c7c382abf7c33b3477%22%20OR%20%22a322eff9d46c00b8106128cd%22%20OR%20%228d7eb6ebf2f9066cf5bf3571%22%20OR%20%22a31b6cb0dc984ce12c0729fb%22%20OR%20%22338591613f128d0697b4929f%22%20OR%20%2206eb4ecb5e2901ba7e2435d3%22%20OR%20%22422308c8fb52129e034cf9bf%22%20OR%20%22b84d6780218a7221b454bfc0%22%20OR%20%2233ce3c7209979de294f59ac0%22%20OR%20%224861f6135ec6988e8a972552%22%20OR%20%228fa1a1ce2960f117a6dd445f%22%20OR%20%220bb02ca9caa18a7d8fdb4eda%22%20OR%20%225107924c9d0f040eff7747b2%22%20OR%20%227cd3762efcd52e0ccd712f1c%22%20OR%20%22e22a35df2e1107ab7f5fb670%22%20OR%20%22a1df838c0ccc6c78d02d3971%22%20OR%20%22923a539dfe24fdbab9791146%22%20OR%20%223b3d9990fb3be21cbb7c2641%22%20OR%20%223de406496afbe856e6fba334%22%20OR%20%221c86b3a3c2cb7a96ea5fba91%22%20OR%20%22002ce9a093bfc0236b3aee91%22%20OR%20%226351ef4cd7680b773fa63a1e%22%20OR%20%220803ac7a8a57c030ad4f2d48%22%20OR%20%22eb02b8a18498df5565db6aac%22%20OR%20%22b217f493d4a4b43e56f91b4d%22%20OR%20%22f39afcb5598e95db1b2511d2%22%20OR%20%229adfbb15e483848428f214b5%22%20OR%20%229c7ef0abbec6d21bc85b0682%22%20OR%20%2282e458e7788b0cc449552219%22%20OR%20%22c84db5ffb5bde3a9bfb52757%22%20OR%20%2250e6003025567ff17b11d4f0%22%20OR%20%22090470b36b9f7ea1b8aef014%22%20OR%20%22de951b68bac8d2c2497543e6%22%20OR%20%2200d229a0ec5c2afe181a4818%22%20OR%20%223275f9341d4837523a612332%22%20OR%20%22db56c0eb7a40cb9b1d1c4742%22%29%20%40level%3Aerror%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1700514000000&to_ts=1700515980000&live=false)), except for one, which then succeeded on retry ([see DataDog](https://vagov.ddog-gov.com/logs?query=%40named_tags.jid%3A%2223c39f9a7a4148bf56a1e747%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1700514000000&to_ts=1700515980000&live=false)).
