### ISSUE TITLE
Traceability Reports (Coverage for Reference & Summary (Defects))

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#70072]
To enter the Staging Review portion of the Collaboration cycle, we need to provide QA documentation including a "Regression Test Plan" and a "Test Plan".  

Below are the definitions of these two plans, from Platform's [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan) documentation:

> **Traceability Reports**
> VFS teams can create a Traceability Report by clicking on the appropriate link in the Create Report panel on the Reports tab of TestRail. 
> - For an example of a Coverage for References report, [see this Coverage Report for Search](https://dsvavsp.testrail.io/index.php?/reports/view/12). 
> - For an example of a Summary (Defects) report, [see this Summary (Defects) report for Search](https://dsvavsp.testrail.io/index.php?/reports/view/14). 
>
>VFS Teams not using TestRail are still expected to share Traceability Reports at the Collaboration Cycle Staging Review.

There is this note "Teams not using TestRail are still expected to share Traceability Reports".  Curious to understand what those examples look like and to understand if this type of reporting applies to our Find a Representative product.

## Tasks

- [ ] Review examples for Coverage for References report and Summary (Defects) report
- [ ] Determine if these types of reports apply to our Find a Representative product
- [ ] _Create a Coverage for References report for Find a Representative (if applicable)_
- [ ] _Create a Summary (Defects) report for Find a Representative (if applicable)_

## Acceptance Criteria

- [ ] We decide if these reports make sense for our product
- [ ] _Traceability reports have been created (if applicable)_

**Comment by cosu419** [comment]
Put in a request for test rail (each team is allotted one account).
