### ISSUE TITLE
DR | Move AddIssue component into shared

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#70091]
## Value Statement
**_As a_**  Developer
**_I want to_** be refactor the `AddIssue` component
**_So that_** we can have a consistent interaction across our appeals forms and reduce future tech debt

## Background Context

- Research was completed with the assistance of GitHub codeclimate to identify potential refactoring to reduce tech debt. As a result, the goal is to bring the ratings to an A - to make code more manageable.
- The `AddIssue` component has a Code Climate Ratings of F

## **File Ratings**

| File | Rating |
| ------- | ------ | 
[src/applications/appeals/10182/components/AddIssue.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/components/AddIssue.jsx) | F |
[src/applications/appeals/995/components/AddIssue.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/components/AddIssue.jsx) | F | 
[src/applications/appeals/996/components/AddIssue.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/components/AddIssue.jsx) | F| 

## Out of scope

* Other apps/forms not in Decision Reviews
* Testing folder does not apply here

## Tasks

- [ ] Function moved into shared components folder
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Identify functions to be refactored
- [x] Have access to decision reviews folder (src/applications/appeals/<AppealForm>/components) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/components/AddIssue.jsx)
  > 996 - Higher Lever Review (src/applications/appeals/996/components/AddIssue.jsx)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/components/AddIssue.jsx)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away and duplication in the PR is marked as fixed

**Comment by saderagsdale** [comment]
@Mottie Breaking up PRs

**Comment by Mottie** [comment]
Awaiting platform code review, then we can merge and we can call this work complete

**Comment by Mottie** [comment]
Verified working in staging
