### ISSUE TITLE
Spike | Is info lost when a user signs in?

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70103]
## Issue Description
_It is suspected that when a user starts a form unauthenticated and then signs in at some point within the online form, they lose their in-progress data._

---
## Tasks
- [ ] Confirm if a user loses or retains their data if they authenticate after they start an online form for:
   - [ ] Chapter 36
   - [ ] Burial

## Acceptance Criteria
- [ ] Determine data retention for users who move from unauthenticated to authenticated when filling out the Chapter 36 form or burial form.
- [ ] Create follow-on ticket if data is lost when a user authenticates
---
