### ISSUE TITLE
Limit number of search results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7010]
## User Story or Problem Statement
As a Veteran, I want to see the five closest facilities so I can be served at a location close to me.

## Goal
Align search functionality with user expectations 
Improve search performance

## Objectives or Key Results this is meant to further
OBJECTIVE 1: Enhance the search process 
OBJECTIVE 3: Deliver a usable and accessible experience

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Regardless of facility type chosen, the user is presented with five results on the first page. **(TBD: need to choose a number of total results)**
- [ ] Results are presented with closest location first, remainder in descending order. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
