### ISSUE TITLE
Identity Dashboard (FE)- Complete Integration of Client Configs Management with Backend and Identity Dashboard

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#70114]
### Summary
Fully integrate the Client Configs management (Client Config page) with the Backend and Identity Dashboard. This involves implementing client configuration editing and display features, configuring the `clientConfigForm` with an API request to the Identity Dashboard, and addressing the specified scenarios.

### Components and Modules:

-  **`src/app/@authenticated/client-config/page.js`**
   - List client configurations.
   - Implement conditional rendering based on loading state and configurations.
   - Provide an option to create a new configuration.

- **`src/components/ClientConfig/...`**
   - `Configuration.js`: Render a table row with configuration details.
   - `createConfigPrompt.js`: Prompt to create a new integration.
   - `index.js`: Render a table of client configurations.

- **`src/components/NewIntegrationForm/...`**
   - Form for creating a new integration.
   - Utilize Formik, Chakra UI, and Next.js router.
   - Implement progressive headers, form sections, and navigation buttons.

- **`src/app/@authenticated/client-config/[id]/edit/page.js`**
  - Implement Formik for editing configurations.
   - Asynchronous data fetching for teams and current configuration.
   - Develop a multi-step form for General, Authentication, Authorization, Final.

- **`src/app/@authenticated/client-config/[id]/page.js`**
   - Display details of a client configuration.
   - Use a table format for configuration attributes.
   - Include edit and delete buttons with Next.js router navigation.

- **`src/components/ClientConfig/utils.js`**
   - Develop utility functions for client configuration API interaction.
   - Ensure compatibility with VA Identity (VAID) API.

#### On the "Create new integration" Page
- [x] Implement a multi-step form with Formik for General, Authentication, Authorization, and Final steps.
- [x] Validate the required fields using `yup` or another validation library.
- [x] Capture and save state when navigating forward/backward through the form.
- [x] Upon clicking the "Finalize setup" button, initiate a fetch request (POST) to the Backend API's "Client Config creation" endpoint with the necessary fields.

#### On the "Client Configuration" Page
- [x] Initiate a fetch request (GET) request to the Backend API to check if client configs exist, and conditionally render either the "Table of Client Configs" or the "Empty State Client Configs" page.
- [x] In the "Table of Client Configs" view:
- [x] Implement functionality for the "Modify" button to navigate to the "Edit my Client Config" page.
- [x] In the "Empty State Client Config" view:
- [x] Display 'No Current Configs' component and render button that navigates to New Integration Form.

#### On the "Edit Client Configuration" Page
- [x] Load the "Edit Client Configuration" page with the current details of the selected client configuration.
- [x] Initiate a fetch request (GET) request to the Backend API to allow for asynchronous data fetching for teams and the current configuration to pre-populate the form.
- [x] Implement a form with Formik for General, Authentication, Authorization, and Final steps.
- [x] Allow the user to fill or edit general details, configure authentication-related settings, set authorization rules, and review the configuration details before finalizing.
- [x] Clicking the "Update Config" button should trigger a fetch request (PATCH) to the Backend API's "Client Config Update" endpoint with the updated configuration.
- [x] Provide feedback on the success or failure of the update process.
- [x] In case of success, navigate the user back to the "Client Configuration" page with the updated details.
- [x] Initiate a fetch request (DELETE) request to the Backend API to allow for users to delete current Client Config.

### Milestones
1. **Client Configs Frontend Implementation**
   - Implement frontend components and modules.
   - Create reusable components to assist in the navigation of aformentioned pages. 
   - Dynamically render components ensuring that data properly displays. 

2. **Backend Integration and API Requests**
   - Configure the `clientConfigForm` with API requests to the Identity Dashboard (Backend).
   - Create utility functions to appropriately interact with Identity Backend. 

3. **Testing and Refinement**
   - Write tests for the implemented features.
   - Refine and ensure proper functioning of all components.
   - Assign issues related to testing and refinement to this milestone.

4. **Documentation and Finalization**
   - Update documentation to reflect changes and additions.
   - Finalize the integration and prepare for deployment.
   - Assign issues related to documentation and finalization to this milestone.

### Related Issues

[61181](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61181)
[60072](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60072)
