### ISSUE TITLE
Add mileage filter to search

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7012]
## User Story:
As a Veteran, I want to define my search parameters in miles so that I can find a facility in the area I specify.

## Goal
Allow Veteran to filter search results by mileage

## Objectives or Key Results this is meant to further
OBJECTIVE 1: Enhance the search process 

## Tasks 
- [ ] TBD based on design

## Acceptance Criteria
- [ ] TBD based on design

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
