### ISSUE TITLE
Passkeys: Proof of Concept

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#70138]
## Description
This includes the body of work to create a Proof of Concept with Passkeys on VA.gov

## Tasks
- [ ] Should have a feature toggle for passkeys being enabled
  - [ ] Create separate ticket for work
- [ ] Use technical requirements + user stories knowledge to create integration

**Comment by parkerbees** [comment]
Duplicate of 70136
