### ISSUE TITLE
Passkeys: Users Stories, Technical Flowchart, Technical Requirements, Presentation

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#70136]
## Description
This is a ticket to document the technical architecture for Passkeys from Frontend to Backend and should include how it will work, different options to accomplish passkeys auth, and features & limitations of passkeys

## Tasks
- [ ] Set up a meeting to talk about how passkeys should work from the FE to Backend
  - [ ] Create a LucidChart of technical flows
  - [ ] Create a list of User Stories 
  - [ ] Create a technical requirements list from User Stories
  - [ ] Create a presentation on the features & limitations
