### ISSUE TITLE
Spike: Passkeys

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#70130]
## Description
This is a Spike ticket for Passkeys feature on VA.gov.  This should include scoping of work, defining MVP for the Proof of Concept, how are are going to integrate, and technical architecture.

## Tasks
- [ ] Research what Passkeys are and how to integrate
- [ ] Scope work of passkeys (include how long it should take)
- [ ] Define the MVP for the Proof of Concept including features
- [ ] Create meetings for technical architecture

**Comment by parkerbees** [comment]
Duplicate of 70136
