### ISSUE TITLE
Enable PPIU/Direct Deposit in production: Canary

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#70143]
## Issue Description
This is to track the Canary section from our [PPIU release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/488b30b6fa454ef3c3f7f12aeeff26a12522193d/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20PPIU-DirectDeposit%20Service%20Endpoint%20Migration%20Release%20Plan.md)

We'll be scheduling times with users from [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) and verifying activity is captured properly in our [DataDog dashboard](https://vagov.ddog-gov.com/dashboard/pfj-tf3-mb4?refresh_mode=sliding&from_ts=1700158863442&to_ts=1700162463442&live=true)

## Tasks
- [ ] Follow steps in the 'Canary' section of the release plan
- [ ] Record findings and issues in the plan doc

## Acceptance Criteria
- [ ] All boxes checked in the 'Canary' section of the plan doc
- [ ] Any issues/observations recorded in the plan doc

**Comment by sethdarragile6** [comment]
This ticket is a duplicate, closing!
