### ISSUE TITLE
Design help Product refine engineering tickets for FE Pension work (Step 4)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70147]
## Issue Description
As a product manager,
I need to ask Designer's help to refine upcoming tickets created for frontend engineering work against the latest Design files,
so that we can proactively identify any missing acceptance criteria to the work for Pension engineers.

---
## Tasks
- [x] Review the following set of engineering tickets and their acceptance criteria
- [x] If needed, edit the tickets' description, acceptance criteria and/or any other information in the ticket that would help clarify the task for engineers.
**_- Some examples of information that may be missing from the tasks are Page Titles for new pages, or incorporating new details included in recent comments in Sketch_** 

**Removed from scope:**
- Please also **ensure each task for engineers have a clear definition on the form flow logic**.
- Create any additional design prototypes as needed

**List of tasks for Step 4:**

-  [MVP] Step 4 Household info: Create new page and question for What's your marital status and match copy #69959
-  [MVP] Step 4 Household info: Create new page and question for Reason you're separated and match copy #69960
-  [MVP] Step 4 Household info: Create new page and question for Financial support for your spouse and match copy #69961
-  [MVP] Step 4 Household info: Create new page and question for Current spouse marital history and match copy #69962
-  [MVP] Step 4 Household info: Match rearranged questions, options and add multi-entry for Spouse's former marriage(s) #69963
-  [MVP] Step 4 Household info: Match question wording for 7 questions under Dependent children details #69967
-  [MVP] Step 4 Household info: Create expandable section for Dependent's disabilities and match copy #69970
-  [MVP] Step 4 Household info: Match question wording for 6 questions under Dependent children details #69972

## Acceptance Criteria
- [x] Designer will have reviewed the set of engineering tasks provided and made any edits needed to help clarify information for engineers taking on this work.

**Comment by mayacoforma** [comment]
@vbellissimo Here's the link to the prototype for step 4: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/4okemVZ/play
