### ISSUE TITLE
Create diagrams for identity classes and methods 

### ISSUE THREAD

**Issue by achievedaniel** [department-of-veterans-affairs/va.gov-team#70166]
## Issue Description
Identify all classes and methods in identity diagraming what methods are called and what attributes are passed. This is also a good opportunity to identify unused classes and methods and methods that could be refactor. 

---
## Tasks
- [ ] Identify classes and methods
- [ ] Create diagram linking all classes inheritances and calls
- [ ] Identify unused code for potential removal
- [ ] Identify potential code to be reactor

## Acceptance Criteria
- [ ] Completed diagram 
- [ ] List of potential refactors and code to be deleted
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
