### ISSUE TITLE
[FSR Wizard] Form builder discovery for user research

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#70160]
## Description

For the wizard research, we'll need to test the updated content and logic of the new complete a subtask pattern; rather than using UXPin to create a prototype, we'd like to use an off-the-shelf form builder that's more accessible to test the content. 

Scenario: In common language describe the work or issue

Given: A veteran wants to fill out the FSR
When: A veteran wants to determine whether or not the FSR is for them
Then: A veteran will be able to click through the new wizard and get the answer they need

## Tasks
- [x] [Research accessible form builders and ask CAIA folks if they know any](https://dsva.slack.com/archives/C0NGDDXME/p1691011151978379)
- [x] Create trial accounts
- [x] Create a prototype with content and flow from Sketch files

## Acceptance criteria

- [x] An accessible form builder is found
- [x] An accessible prototype can be created to test the content and logic of the new wizard 

## Testing
- [x] Test logic and paths go to correct results
- [x] Test with screen reader to make sure the prototype is accsible 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
@HeatherRienks @Tom-Davis 

Added the discovery ticket we discussed yesterday for the form builder research.

cc: @mgleo @charlottecesana

**Comment by mgleo** [comment]
Will continue with [#70365](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/70365)

**Comment by josephrlee** [comment]
Here's the form: https://tally.so/r/wL7Rap 

It's the best accessible form builder I found in my testing, it's not perfect (the focus doesn't set to the headline) but it works pretty well! 

This is ready to be marked as closed now!

cc: @Tom-Davis @HeatherRienks

**Comment by Tom-Davis** [comment]
Closing as complete - the research is finished and linked.
