### ISSUE TITLE
Update Platform team labels in  the Platform Orientation gh templates

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#70171]
## User Story
As a Platform Support team member, I want to be able to find tickets my team is responsible for so that I can easily take the necessary action.

As an Analytics & Insights team member, I want my teams label to be removed from tickets we are no longer responsible for so that our backlog is not cluttered with other teams' tickets. 

As a Governance team member, I want my teams label to be removed from tickets we are no longer responsible for so that our backlog is not cluttered with other teams' tickets. 

Assignee: @shiragoodman 
Peer Reviewer: @allison0034 @rferguson13 

## Description
Platform Support team is going to be taking over the task of adding new VFS teams and new VFS Team members to the VFS Team Roster, soon to be Platform Atlas. In order to ease with the transition, we need to add the Platform Support team label (`platform-tech-team-support`) to both templates. In addition, we need to remove both Analytics and Insights team labels (`analytics-request` and `analytics-insights`) from both templates as they are no longer responsible for this work.

The `governance-team` label can be removed from the New VFS Team template, however, at this time, the label should remain in place on the New VFS Team Member template as Governance team still provides support adding new users to the vets.gov-write gh team. Platform Support will likely pick up this task at a later date.

Since we're updating labels, the urls will change, meaning the urls where these templates are linked out on Platform Website need to be updated. This should only impact the [Guidance for New teams and team members page](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members).

## Impacted Artifacts
[Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members)
New VFS Team template in gh
New VFS Team Member template in gh

## Tasks
- [x] Confirm the correct gh label for Platform Support team (`platform-tech-team-support`) with @alyssagallion and/or @jknipes 
- [x] Create a pull request for the New VFS Team gh template and update the following:
   - [x] Add the Platform Support team label
   - [x] Remove the Governance team label
   - [x] Remove both Analytics & Insights team labels
- [x] Create a pull request for the New VFS Team Members gh template and update the following:
   - [x] Add the Platform Support team label
   - [x] Remove both Analytics & Insights team labels
- [x] After both PRs are approved and merged, update the links to the templates on the Guidance for new teams and team members page on Platform Website
- [x] After PW publishes, confirm that links direct you to the correct template with the correct labels

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Analytics & Insights team is no longer notified of New VFS Team or New VFS Team member tickets
- [x] Governance team is no longer notified of New VFS Team tickets
- [x] Platform Support is notified via their team label of both the New VFS Team and New VFS Team Member tickets 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by jknipes** [comment]
Correct label is`platform-tech-team-support` , purple

**Comment by shiragoodman** [comment]
@allison0034 @rferguson13 i have made the changes to both templates and created PRs for you to review

- https://github.com/department-of-veterans-affairs/va.gov-team/pull/71300
- https://github.com/department-of-veterans-affairs/va.gov-team/pull/71301

**Comment by shiragoodman** [comment]
this ticket will move into the next sprint as peer review has not yet been completed and the revised links have not been updated on PLatform Website.

**Comment by allison0034** [comment]
PRs look good

**Comment by shiragoodman** [comment]
new template urls have been updated on the [Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members) page. Awaiting Platform Website publishing via scroll viewport.

**Comment by shiragoodman** [comment]
I have just verified that the links on the Guidance for new teams and team members page point to the tickets with updated labels. @rferguson13 or @allison0034 - can one of you please verify? I will close after.

**Comment by allison0034** [comment]
@shiragoodman looks good, you can close!
