### ISSUE TITLE
SPIKE | Confirm Document Upload

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70181]
## Issue Description
_The Benefits Intake API can send a success message that doesn't actually confirm the document was uploaded. More info [here](https://developer.va.gov/explore/api/benefits-intake/docs?version=current). To confirm successful submission, we need to poll for a status beyond the initial handoff._

---
## Tasks
- [ ] Confirm whether or not we are already polling.
- [ ] If not, audit submission sent and identify if any failed and create follow-on ticket to add polling.

## Acceptance Criteria
- [ ] Polling status is determined
- [ ] Submission audit is completed (if needed)
- [ ] Follow on ticket to add polling is created (if needed)
---
