### ISSUE TITLE
[Content] Research and write "Wilkes-Barre, PA" Facilities INTRO content required for ALL facilities [Content]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7019]
## User Story or Problem Statement
As a Veteran web user, I need to know the specific details and key health services of the local facilities related to my area, so I can better plan my journey to the specific facility and location. 

## Goal
_Short and descriptive detail of top health services for the local facilities_

## Objectives or Key Results this is meant to further
- _Reduce click through count_
- _Document pages that can be created in a scalable manner_

## Resources - Tools - Documentation
[Wilkes-Barre Health Service Playbook](https://drive.google.com/drive/folders/1lj6_MZ4x6CKxybS3FWicbwYnxFKUvduv)
[Wilkes-Barre Legacy Web Page](www.wilkes-barre.va.gov)
[Example Facility pages at Pittsburgh](https://www.va.gov/pittsburgh-health-care/locations/)
[VISN_4_Medical_Systems_and_Clinics_List](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)

## Tasks
_Write Intro content for the following Facilities:_
- [ ] Wilkes-Barre VA Medical Center
- [ ] Allentown VA Clinic
- [ ] Columbia County VA Clinic
- [ ] Northampton County VA Clinic
- [ ] Sayre VA Clinic
- [ ] Tobyhanna VA Clinic
- [ ] Wayne County VA Clinic
- [ ] Williams Port VA Clinic

## Acceptance Criteria
_Confirm all have been reviewed and documented in Content Approval Process folder on Google Drive_
* Wilkes-Barre VA Medical Center
* Allentown VA Clinic
* Columbia County VA Clinic
* Northampton County VA Clinic
* Sayre VA Clinic
* Tobyhanna VA Clinic
* Wayne County VA Clinic
* Williams Port VA Clinic
