### ISSUE TITLE
Add Step to Governance Offboarding Ticket 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70208]
**Description** 

In a conversation with Shira Goodman, we determined it is important to add a step to the [Governance Offboarding Ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+Offboarding%2C+operations&projects=&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D) to ensure that the VFS Roster stays up to date. 
---

**Definition of Done**
All tasks below must be complete. 
---

**Tasks** 

_Steps to reach definition of done._ 

- [x] Add step to offboarding ticket to ensure folks are moved off of the VFS Roster when offboarding
- [x] Add steps to documentation [VFS Roster Management doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2798846283/VFS+Roster+Management?focusedCommentId=2813853787)
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

**Resources & Additional Info** 

Context: 
[Ticket mentioned in below screenshot
](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/41808)[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03de1b0a6a7a4b3154a8b018ae0615be97671a6a/Screen%20Shot%202023-11-17%20at%2011.44.12%20AM.png)

---

**Comment by jknipes** [comment]
This step is already part of the [offboarding ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+Offboarding%2C+operations&projects=&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D)

**Comment by jknipes** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1MQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--772903056225f1eb5b039403d72d73b059656f35/image.png)

**Comment by jknipes** [comment]
@alyssagallion please review and close

**Comment by alyssagallion** [comment]
No need to pursue, step has already been added to the offboarding ticket.
