### ISSUE TITLE
Research | Auth Exp | Process improvement | Figure out where to capture miscellaneous research insights. 

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#70207]
## Background
Many times, we hear feedback and observe behaviors about the authenticated experience in research studies that are meaningful, but not related to the main goals of the research study. This means they're probably not captured in a findings report we can refer to later.

Liz created [a doc to capture these things for now](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/miscellanous-research-notes.md). @pamela-drouin knows better ways!

In this ticket, we'll collaborate on a better way to capture these findings to make them more useful for our team, and possibly other VFS teams too.

## Tasks

- [ ] Liz and Pam meet to review methods and align on a way forward
- [ ] Enter research data
- [ ] Share with team

**Comment by mtcA6** [comment]
@ajakabcin missed when liz initially posted this on a s[lack up thread](https://dsva.slack.com/archives/C909ZG2BB/p1700237251544049?thread_ts=1700235021.400329&cid=C909ZG2BB) 

Surfacing some additional context from the thread: 
>T: Cleaning up some Sketch files, finishing claims adjudication ticket, organizing notes from the Find A Rep session I attended earlier this week. There were some interesting comments about personalization and [I’ll drop them here for now](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/miscellanous-research-notes.md). As this grows, we can probably think of a better way to store this data. Pam knows of a better way to do this, so we’re going to collaborate next sprint. I created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70207). It doesn’t have the profile label on it since this isn’t specific to the profile product.

We should discuss how to make this more actionable. Thinking we can chat about this during our 1:1

**Comment by andaleliz** [comment]
I forgot about this ticket, but this will be a good one to pick up early in the new year if we have extra bandwidth in a sprint. Maybe during a window when we're waiting for research recruiting?

**Comment by pamela-drouin** [comment]
Sounds good to me 😄

**Comment by andaleliz** [comment]
@mattmarino-adhoc and @pamela-drouin I totally forgot about this ticket and saw it today. Since we all have research that recently wrapped or in progress, I wanted to check in with you both. 

Any thoughts about the best way for us to capture this data?

I'm sure we'll all encounter it in the upcoming studies, and I definitely heard a few things I should note somewhere during my last study.

**Comment by pamela-drouin** [comment]
I have half-thoughts. I might be able to spend a little bit of time today on this. I will post thoughts here!
