### ISSUE TITLE
Copy of [FE] My VA: Clean up feature flag code on mock server

### ISSUE THREAD

**Issue by Dottifacilities** [department-of-veterans-affairs/va.gov-team#70212]
## Background
Currently the way our [feature toggles are set up on our mock server](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/common/mocks/feature-toggles/index.js) is clunky and doesn't feel sustainable the more features we add. 

If we model our mock feature toggle file after [profile's](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/mocks/endpoints/feature-toggles/index.js), we can just update or add feature toggles in one place, rather than two. This will improve developer quality-of-life in the long run. 

## Tasks
- [ ] update `src/applications/personalization/common/mocks/feature-toggles/index.js`
- [ ] update src/applications/personalization/common/mocks/server.js

## Acceptance Criteria
- [ ] Feature toggle file is updated
- [ ] Feature toggles still behave correctly

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Devs: @dellerbie and @adamwhitlock1 
- _How can this work be validated?_ confirm that all feature toggles are working as intended on mock server

## Resources
- [Adam's note + suggestions](https://github.com/department-of-veterans-affairs/vets-website/pull/24735#discussion_r1268315096)
- [feature toggle mocks on /profile/](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/profile/mocks/endpoints/feature-toggles/index.js)

**Comment by Dottifacilities** [comment]
Create this as a copy of the original issue as a test - can be closed and ignored
