### ISSUE TITLE
[Design, FE] 10-10EZ - Saved-In-Progress: Exploration on recent errors impacted by saved-in-progress forms

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#70217]
## Background
Since the end of October, we started to see submission failures for the 10-10EZ, failing all retries.  The error message states `Missing required fields` and then lists the fields missing: a combination of Child DOB, SSN and Dependent date.  
There has been one failure that has an error message `Missing required fields`, and the missing field was the insurance company name.
There has also been several failures with error message  `undefined method [] for nil:NilClass`, which seems to indicate the Dependent name is missing.

We have since removed the functionality of "Save in progress" within the Dependents and Insurance sections.  The Veteran must complete adding all dependents and/or insurance policies within a single session before it will save.

Now, we need to determine how to implement a validation mechanism on fields within the Dependents and Insurance sections, after a Veteran has saved the form (or auto-save), left the form and is now returning to the form.
This will need UX and Engineering involvement to determine the right solution to reinstate the saved-in-progress functionality, while also alerting the Veteran to complete fields that are required and missing data within the Multiple Response component.

**Note**: We will want to keep in mind that this solution could resolve the problem with incomplete pre-filled data that we pull from Enrollment System for the EZR.  
I don't believe that the VA Profile includes all Dependent/Insurance info we would need to pre-fill for the EZ, but that can be discussed at another time for another feature.

### Resources
- [Mural Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699485613760/d40578dbce4f0433d792988db24e4dec8d5b4fd1?sender=uadf1ed7fe7c76f0914967329)
- [Sketch file](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/33FAF070-83AE-4DF8-88E2-3670A68A0092/canvas)

## Tasks
- [ ] Start conversations between UX and Engineering
- [x] Explore possible solutions
- [ ] Narrow to 1-3 potential solutions & discuss with PMs
- [ ] Once a decision on a solution is made, communicate to the team and PO
- [ ] Consider whether this will resolve the Pre-fill issue of not being able to validate required fields for missing data
- [ ] Create tickets for the work that needs to be done

## Acceptance Criteria
- A solution has been agreed upon and next steps are known.

**Comment by jessicastump** [comment]
Information gathering [Mural started here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699485613760/d40578dbce4f0433d792988db24e4dec8d5b4fd1?sender=uadf1ed7fe7c76f0914967329)

**Comment by hdjustice** [comment]
What stage are we at on this one?  I am sorry we haven't spent much attention on this.

**Comment by aagosto90** [comment]
@hdjustice We agreed that the best approach would be the longer but correct approach - an alert within a card where there's missing information ([Sketch mockup](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/kKGwddZ)), but we'll need to test in order to roll this solution out. So next steps were for Matt K. to work on the CodePen template setup so we can test this approach in conjunction with other version 2 updates to EZR early next year. Therefore I think we can close this ticket out if you agree, but we should note in any future tickets for testing EZR updates that we'll include this alert-within-card design in testing.

**Comment by hdjustice** [comment]
Ok thank you @aagosto90!  I will see what we have out there so far and get some tix set up.  We will need the solution for both EZ and EZR, and if we can test with EZR sooner, then I am ok with that.  I am going to leave this open until I can get the other tix set up so we dont forget

**Comment by hdjustice** [comment]
Let's talk about this for EZ

**Comment by hdjustice** [comment]
Check this for additional tickets on EZ side and check in with Alex on Codepen status
