### ISSUE TITLE
Addition of new CORS rules to maintenance windows buckets

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#7022]
## User Story or Problem Statement
Frontend needed some changes to a few S3 buckets to set new CORS rules. In an attempt to get the terraform changes applied, we ran into several issues with our existing s3_bucket module(s). The originating conversation can be found [here](https://dsva.slack.com/archives/C30LCU8S3/p1584566965407500). 

This also led to a state discrepancy with a changed name of staging appeals vpc. That originating conversation can be found [here](https://dsva.slack.com/archives/C0S6H6BQU/p1584571732123400). PR for this fix is [here](https://github.com/department-of-veterans-affairs/devops/pull/6544).

## Goal
_What outcome(s) do we want to see?_
Existing buckets continuing to exist with previously applied policies + new CORS configs.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
Using the existing state / modules in place, add the new CORS configs to S3 buckets holding env specific `maintenance_windows.json` files.

## Acceptance Criteria
- [x] Existing buckets continue to exist with all necessary policies + new CORS configs. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
