### ISSUE TITLE
[epic] NOD | Evidence not sent to Lighthouse

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#70237]
## What happened?

When we started accepting submissions for NOD v2, evidence was successfully uploaded to S3, but not to Lighthouse.

Root cause: The backend code submitted form data to Lighthouse, but not the evidence that had been uploaded to S3. The code to submit this evidence to Lighthouse was not added. 

Additional detail: Lighthouse helped us obtain records for each NOD v2 form submission with accompanying evidence uploads. There were 48 of these records. Each of these records contain a reference to the documents uploaded to S3, and provide us with all the veteran information we need to properly submit the uploaded evidence to Lighthouse using the code that we should have been using in the NOD v2 form submission code.
In case you're interested, you can find a draft PR for that script here.

## Next steps

- [x] Turn off feature toggle to return to previous form version.
- [x] Identify affected claims and un-submitted (or “pending upload”) evidence uploads, and common identifier to associate them with the claim.
- [x] Write script to submit un-submitted evidence uploads.
- [x] Run script to submit the evidence uploads.
- [x] Add evidence upload code to the new endpoint.
- [x] Confirm that BVA received claims and evidence.
- [x] Turn the feature toggle on again.
- [x] Post-mortem.

## Definition of Done

- [x] **Confirm that the claims and evidence are mapped appropriately.** We want to ensure Each Veteran's claim is mapped to the right evidence. 
- [x] **Check if the submissions we pushed through went through CMP.** We want to ensure there's a traceable "footprint" for these claims and evidence in case CMP or BVA needs it at a later time.
- [ ] Business line approval to close
- [ ] PO approval to close

**Comment by saderagsdale** [comment]
Based on the intake team’s feedback below, we should be in good shape to pass the evidence through. We’ll want to coordinate with them to ensure it lands as expected.
The appellant may select the Evidence Submission lane when they execute the 10182. There is no requirement that the additional evidence be attached at that time. When we docket the appeal, per the reg, they have 90 days to submit any. After the 90 days, the appeal moves on. This is true whether they submit evidence at the same time, later, or not at all. The only time it changes is if they waive the remainder of the 90 day window when they send the evidence in. If so, then we proceed with the appeal without holding it for the full 90 days. So no, we don’t reach out. Our docket letter tells them they have 90 days if they wish to submit evidence. As long as we get their evidence within the 90 day window there is no harm.
There is no change in status upon receipt of the evidence unless the window is waived as explained above.
If evidence is received after docket, a mail task is assigned in Caseflow, the evidence uploaded to VBMS and, if it was received within the 90 days, will be reviewed by the decision maker when the appeal is decided.
However, if we received evidence after the 90 days, the Judge may not consider it. This would be a problem in the cases you are referring too since their evidence could be excluded from consideration due to system fault, so further discussion may be needed to determine what to do should this occur.
