### ISSUE TITLE
IA Tracker: Form 20-10207

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#70233]
### Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

### Links

- [Intake Ticket #]

### Team

- Team Name:
- Designer:
- Product Manager:
- Slack (_optional_): 

### Timeline
_When does IA review need to be completed by? When is Midpoint Review?_

---

### Work Needed (if applicable)

- IA Spec: **[Needed / Not Needed]**
- Feedback for product team: **[Needed / Not Needed]**

### Tasks
Check all that apply.

- [ ] Create process ticket draft
- [ ] Watch any Collab Cycle recordings
- [ ] Determine IA deliverables
- [ ] Collaborate with CAIA
- [ ] Ask questions to product team
- [ ] Create IA Spec
- [ ] Share IA Spec with product team
- [ ] Update Site Map and VA.gov Mega IA sheet

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by jennymayoco** [comment]
[Process ticket draft](https://docs.google.com/document/d/1zVXEQ3TxSo5IdNfJ02vImNaYWAMJ9C8XGKg7iqYSgYU/edit)

**Comment by jennymayoco** [comment]
Update from Mikki on 10-10hs and possible overlap:

- The **FSR (form 5655)** is for requesting financial assistance or relief from health care debt/copays that you have already incurred and the **10-10HS** is for requesting relief from all future copays - basically you submit your financial info and it may change your priority group to lessen or omit future copays. You can also submit financial info using the 10-10EZR which can also impact priority group and reduction/elimination of copays so there might be some overlap there, but we might not be aware of the intricacies.
- So the 10207 is specific to requesting faster processing of **VBA claims** (one reason is financial hardship, but may also be due to age and terminal illness), and the other 2 forms are specific to health care copays.

**Comment by jeana-adhoc** [comment]
**If someone submits the app online, but decides to mail the supporting docs, does this impact their timeline at all?**   

TBD

**Is there any overlap with VA form 10-10hs? Do you need to submit that as well if you select financial hardship or is this separate?**      

Based on a recent comment from Jenny - i think the answer to this is that there is no overlap.

**75 or over at the board level, which is different from the 85 or older for regional. What should be represented in the form?**      

The form, and form processing manual all list 85. I'm not sure we can change it to 75? Is this something we need to talk to the stakeholder about?

**Suicide ideation not listed as one of the reasons in the PDF or circumstances but listed in one of the resources, is this an accepted condition in the form?**   

We discovered this recently as well. Since it's not listed on the PDF itself, I'm not sure it should be added (OMB concerns). But we can ask the stakeholder

**To confirm, non-veteran claimant = survivor / dependent or both?**

Either. Anyone that has a claim that is not a Veteran

**For DD214, shouldn’t VA already have this on file? Should there be an option to upload at the end of the flow if not?**

As far as I know, VA does not have the DD214 on file automatically. Veterans have to send it/upload it. There is an opportunity within the flow to upload all of the requested documentation, including the DD214

**Depending on the type of claims you are requesting priority processing for, how to make this clear so folks don’t mail evidence to the wrong place?**

I have this text on the introduction page:

Find the benefit type you're requesting priority processing for. Then use the corresponding mailing address. 

**Compensation claims**   
Department of Veterans Affairs Compensation Intake Center    
PO Box 4444    
Janesville, WI 53547-4444

**Pension and survivors benefit claims**   
Department of Veterans Affairs Pension Intake Center    
PO Box 5365    
Janesville, WI 53547-5365   

**Board of Veterans' Appeals**   
Department of Veterans Affairs Board of Veterans' Appeals    
PO Box 27063    
Washington, DC 20038   

**Fiduciary**   
Department of Veterans Affairs Fiduciary Intake Center    
PO Box 5211    
Janesville, WI 53547-5211

**Will there be an option for third party / POA to upload the corresponding documentation? What if this form is already on file?**

There's not an opportunity to upload the proper 3rd party/POA documentation with this form. If the form is already on file, then the processor will process the claim. If the form is not on file, then the 3rd party should be contacted -- however, I just realized there's no way of contacting the 3rd party. I assume the Veteran will then be notified, but I need to double check on this.

We do include this on the intro page as well:
- **If you’re a third-party representative** (a family member or other assigned person who is not a power of attorney, agent, or fiduciary) requesting VA records for someone else, we must have an authorization form on record (VA Form 21-0845) for us to release their information. 

  [Go to VA Form 21-0845 Authorization to Disclose Personal Information to a Third-Party (opens in new tab)](https://www.va.gov/find-forms/about-form-21-0845/) 

- **If you’re a power of attorney** requesting VA records for someone else, we must have an official record that you were appointed as their representative (VA Form 21-22 or VA Form 21-22a).

  [Go to VA Form 21-22 Appointment of Veterans Service Organization as Claimant's Representative (opens in new tab)](https://www.va.gov/find-forms/about-form-21-22/)

**Comment by jennymayoco** [comment]
Shared the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-20-10207.md) with the product team and tagged @megzehn @strelichl to create an entry point ticket. Moving this ticket to validate
