### ISSUE TITLE
Findings for VSA a11y spot check review for "View dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7024]
### For reference

**VSA Development Review** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review)

## Team Name

vsa-ebenefits

## Product/Feature Name

"View dependents"

## Product description

The first part of a larger form application where a Veteran can first view what dependents are on or not on award for different benefits so they can take action and apply or notify for a change in benefit or compensation.

## Review stage

- [ ] **Development intent review** (Review design to discuss approach to take with development, identify what components and semantic HTML would be appropriate, identify any accessibility issues and how to address) - This would happen as designs are passed to development, before development begins.

- [x] **Spot check review** (Review and follow the steps in the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md) first.) This happens well before launch, so that the 508 office can review and any issues addressed *before* launch.

- [ ] **Other:** Please indicate what you're requesting

## Point of contact

Jason Wolf (@jason-gcio) - PM
Micah Chiang (@micahchiang) - FE
Jesse Cohn (@cohnjesse) - FE

## Preferred times for dev intent checkpoint

Any time in the next sprint or 2, afternoons to accommodate west coasters 

## Staging URL and credentials

URL: https://staging.va.gov/disability/view-dependents/

  - Test-accounts `(usual staging password)`  
    - User (Mark): vets.gov.user+228@gmail.com (has zero on award, 2 not)
    - User (Eric): vets.gov.user+10@gmail.com (has zero on award, 3 not)
    - User (Jeanette): vets.gov.user+123@gmail.com (has zero on award, 1 not)
    - User (Pauline): vets.gov.user+38@gmail.com (has zero on award, 11 not)
    - User (Sam): vets.gov.user+45@gmail.com (has zero on award, 2 not)
    - User (Claude): vets.gov.user+232@gmail.com (has zero on award, 1 not)
    - User (Terrence): vets.gov.user+102@gmail.com (has zero on award, **zero** not)
    - User (Randall): vets.gov.user+99@gmail.com (has **2** on award, 1 not)
    - User (Jesse): vets.gov.user+54@gmail.com (has zero on award, 1 not)
    - User (Jerry): vets.gov.user+271@gmail.com (has **2** on award, **4** not)

## Test plan

Login as one or several different users
Ensure that all 508 compliance initiatives are met, including screen readers, magnification and mobile

**Comment by jenstrickland** [comment]
@jason-gcio I suspect that the ALL CAPS names are coming from the database, so am not documenting a ticket for this. Would you like me to document it in a ticket, so you can go back to the API for a fix?

**Comment by jason-gcio** [comment]
> @jason-gcio I suspect that the ALL CAPS names are coming from the database, so am not documenting a ticket for this. Would you like me to document it in a ticket, so you can go back to the API for a fix?

Sure - we might even need to go further than that though...If I recall when we ran into this with Rated Disabilities we came to the conclusion that changing that data was less than ideal and so we left it as it came from where the data is stored.  We completely realize that CAPS are not great to read, but to make an adjustment like that we just need more definitive direction.

**Comment by jenstrickland** [comment]
@jason-gcio I'm pretty sure it's the database from where the data comes from. If they know it is a 508 issue, perhaps they'll clean their data?

**Comment by jenstrickland** [comment]
@jason-gcio The spot check is complete. I recommend addressing #8515 and #8520 before the staging review, if possible. #8520 will be brought up by VSP Design, and #8515 is a tough experience for screen readers.

**Comment by jenstrickland** [comment]
@jason-gcio I checked the screen on mobile, and was surprised to see the link above the h1, and no breadcrumbs. Do y'all know if this is how it should look?

![IMG_7281](https://user-images.githubusercontent.com/57469/80541727-acb7db80-8979-11ea-842a-692db5421493.PNG)

**Comment by jason-gcio** [comment]
@jenstrickland - Hmm, interesting, I think that link is the mobile breadcrumb.  I wonder if to save space, mobile is altering the breadcrumb to save room: it has removed the current crumb you are on, and removed everything preceding the page leading to it as well.  Breadcrumbs on mobile only show the previous page to save real estate, and if that is true, then "Add or remove dependents" (which is the guiding info landing page here) would be "back" one step, so this is correct.

**Comment by 1Copenut** [comment]
@jason-gcio && @jenstrickland You're correct, the breadcrumbs use CSS to show a "back-by-one" at mobile size, for a space saver. Some of our deeply nested content was creating a 2 or 3 line breadcrumb, so we took a minimal approach. The CSS switch is in the file [_m-breadcrumbs.css on line 86](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/d980e9cf9a3f9042cc264f8fb430901b400dc18a/packages/formation/sass/modules/_m-breadcrumbs.scss#L86)

**Comment by jenstrickland** [comment]
This seemed off because this was View Dependents. Maybe I don't know the path to get here. If the previous page is Add or remove dependents, it would make sense to a user. It didn't make sense without the flow.
