### ISSUE TITLE
Fix Link for Broken Dashboard Link (Ticket #70235)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70246]
## Info
Content edits according to [70235](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/70235)

## Tasks
- [x] Review support ticket 
- [x] Locate the source of the correct/updated link (requires SOCKS access, so will need to rely on someone with that level of permission).
- [ ]Make edits to page by updating the link to the correct one.
- [x] Prepare page for deployment
- [x] Deploy page

## Acceptance Criteria
- [ ] Page has been deployed

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/70246?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by taylojill** [comment]
Message sent to SME (Rachal Cassity) via Slack requesting confirmation that link is valid if using SOCKS proxy.

**Comment by taylojill** [comment]
Per Rachal Cassity, the dashboard was moved to Datadog and is currently in work via this ticket. I will remove page link and note that the move to Datadog is in work and link will be updated at a later time.

**Comment by taylojill** [comment]
Removed link and added the following note: Breakers Dashboard (Move to Datadog currently in work. Link will be updated at a later time.) Page reviewed for launch-blocking issues, ready to deploy.
