### ISSUE TITLE
Support: Mon-Thur Deploy (S41)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70244]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (11/22) - Lauren
- [x] Thursday (11/23) - N/A (Thanksgiving)
- [x] Monday (11/27) - Lauren
- [x] Tuesday (11/28) - Brian
- [x] Wednesday (11/29) - Lauren 
-  Thursday (11/30) - Jill, failed due to bug in Scroll Viewport
- [x] Friday (12/1) - Brian, makeup launch from 11/30
- [x] Monday (12/4) - Jill
- [x] Tuesday (12/5) - Brian

## Acceptance Criteria

- [x] The Platform website will be deployed Monday-Thursday between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support

Temporary rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

**Comment by johnny-jesensky-adhoc** [comment]
Deployments completed for this sprint. Marking as _Done_.
