### ISSUE TITLE
Platform | Using `/resume` bypasses downtime services check

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#70251]
## Value Statement
**_As a_** Veteran
**_I don't want to_** continue a form when backend services are offline
**_So that_** submissions of a form don't fail

## Background Context

We had a sitewide downtime due to upstream server updates. The services were showing as being offline in a sitewide banner and on introduction pages. But monitors were still showing activity leading to errors.

While testing, it was found that within the `/my-va` app a "Continue your application" section uses `/resume` paths. When platform routes these paths, it bypasses the form introduction page, where all the downtime checks are done, and lets the Veteran immediately jump into the form at their last `returnUrl`. We need to add downtime checks in this flow. If a service is offline, we should probably reroute the Veteran to the introduction page instead of the `returnUrl`.

## Acceptance Criteria

- [ ] Prevent Veteran from starting a form with a service that is offline
- [ ] Add tests & all tests passing

## Tasks

- [ ] Add downtime check to `/resume` paths
- [ ] Route the Veteran to the intro page when a service is down, other go to the `returnUrl`
- [ ] Add unit & e2e tests

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/70251?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by micahchiang** [comment]
This ticket will be handed off to authenticated experience.
