### ISSUE TITLE
[BE] 10-10EZ - BUG: Gather data for EZ Retries and Saved-In-Progress volumes, delete all SIP EZ forms with Dependent info

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#70263]
## Background
To determine the on-going impact of the EZ Retry failures due to the Saved-in-progress forms missing Dependent and/or Insurance information for those applications that were saved prior to removing the Save-in-progress functionality to avoid further failures, we need to pull the volumes of SIP forms and (if possible) SIP forms in a retry cycle.

In a conversation with Patrick (below), it was agreed to delete all SIP forms that have dependent information.  This will cause the applicant to restart the form from the beginning.

<details>
<summary>Conversation (expand to view)</summary>

> **Heather Justice**
> FYI I am watching these.
> Note: For any applications that are resuming from SIP and have partial dependent or insurance info, the submission will fail almost right away if they haven't checked all their input, since the error cannot be resolved.  They will receive an email notice of the failure.
> The team has prioritized the long term fix for this, however any applications still in-progress may fail if the dependent and/or insurance info is incomplete.
> I know this doesn't look great as we cycle through the remaining SIP submissions. (edited) 
> 
> **Patrick Bateman**
> :wave: thanks heather. once it fails validation, does it goes back into the retry queue and continue to fail for 2 - 3 days, then finally run out of retries, fail completely, and then send the email?
> 
> **Heather Justice**
> We reduced the retries to 14 over the span of about 25 hours, so it wont take days to fail any submissions (except for those currently in the old 24 retry cycle)
> and yes, they get the emails after failing completely.
> 
> **Patrick Bateman**
> ok. so 25 hours from user submits, they get an email notifying them that they need to resubmit. how much longer until we’re confident that all of the SIPs with this issue have been exhausted? (edited) 
> 
> **Heather Justice**
>  Yes, that is right.  I have Luis checking on that, and hope to have more info on that volume today.
> 
> **Patrick Bateman**
> ok, based on that, i’ll probably make a decision to do something like invalidate all of the SIPs that might fail, forcing the user to start again (which they would have to do anyway when the form fails) or catching this specific error on the initial validation and pulling it out of the queue so we can notify the user immediately.
> 
> **Heather Justice**
> Ok sounds good
> 
> Here is what we have found so far:
> 15,668 1010ez forms with a save in progress record
> Last 60 days prior to removing SIP functionality shows Dependent info pages accessed by 28% of those who start the form. 
> Average that over the 15k SIP forms, and it comes to about 4400 SIP forms that may have dependent info.
> Still working on volumes of forms that are currently in a retry cycle
> 
> **Patrick Bateman**
> ok and remind me, the error happens when the user left the form while on the dependents page, or when they left the form at any point and their form included at least one dependent?
> 
> **Heather Justice**
> It usually happens while on the dependents page.  They wouldn't be able to get past the dependents page to the income pages in the same session.
> 
> **Patrick Bateman**
> ok so is it possible to write a query against the SIP table in the vets-api DB that returns a count of all 1010ez SIP forms that:
> have some dependent info filled in
> …and of those, how many have income info filled in
> and the subtract #2 from #1 to get us exact amount of forms that could possibly fail?
> and then if we’ve done that, just invalidate any 1010ez SIP that has:(1) some dependent info filled in; and (2) no income information filled in?
> 
> **Heather Justice**
> Lihan - Do you know if this is possible?
> 
> **lihan li**
> the errors have all been from dependents information, don't see why the income info is related to the errors
> we should just delete all SIP that have dependents
> the existing retrying jobs will still fail. and maybe the fix didn't work either
> 
> **Patrick Bateman**
> my understanding is that a user cannot get to the income section if they haven’t completed the dependent section. and if they haven’t completed dependent section, then they will likely fail on submit
> im fine deleting all SIPs with dependent info, was just trying to slice it thinner
> 
> **lihan li**
> if they have a SIP before the fix, then they can get to income section with missing info
> 
> **Patrick Bateman**
> ah
> ok then yep, im good with deleting all SIPs with dependent info.

</details>

## Tasks
- [x] Query db for EZ applications that are currently Saved-in-progress (SIP)
- [x] Query db for EZ Applications that are currently in a retry cycle (if possible)
- [x] Provide the volumes to the team/PM

## Acceptance Criteria
- We will have volumes for EZ applications currently saved-in-progress
- We will have volumes for EZ applications currently in a retry cycle

**Comment by lihanli** [comment]
15668 1010ez forms with a save in progress record

**Comment by lihanli** [comment]
22 1010ez applications being retried

**Comment by lihanli** [comment]
SIP with dependents should be deleted now. the terminal instance always times out before the command finishes but I see that there were a few thousand forms deleted, the count now is 12546
