### ISSUE TITLE
Pension Team Sprint 8 Plan: 11/22/2023—12/05/2023

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70266]
## Sprint 8: 11/22/2023—12/05/2023

**- Outages (PTO, holiday, or unplanned):** 
-- **Wed, Nov 22:** Vicky, Maya
-- **Thu, Nov 23 (Thanksgiving Day):** Everybody
-- **Fri, Nov 24:** Dan, Todd, Wayne, Coforma team members, VA
-- **Nov 27, 28, 29:** Todd
-- **Dec 4-8:** Eunice (Military leave)

## Theme(s):

- Design reviewing/QA cards completed by engineering
- Start frontend changes to form for Steps 4 & 5
- Progress in our schema and PDF mapping efforts? (see Notes below)

## Notes:
- Per Emily, OK to move this out of the sprint since this may be somewhat of a moving target: Document all new questions, questions removed on Google Sheet doc #70402
- For backend PDF mapping tickets, pull in corresponding sections as the front end changes are being done.
- - Added only #70382 and #70385 to the sprint for now. If we get ahead on front end tickets, then we can pull more of the PDF mapping tickets in.
- **Add to sprint (high-priority)**: "Do we have error monitor when our own backend errors out? was there monitoring in the past?" Dan/Matt to help fill in this ticket: #70487 . 
 
## Sprint 8 Goal(s):

**RESEARCH/DESIGN**

**_MVP relaunch_**

- [ ] Review/QA all cards in staging completed by engineering #70405 **Existing shared cards w/engineering**
- [ ] Design help Product refine engineering tickets for FE Pension work (Step 4) #70147
- [ ] Design help Product refine engineering tickets for FE Pension work (Step 5) #70148
- [ ] Update form flow logic diagram in existing MURAL for Steps 1-4 #70301 (removed mid-sprint)
- [ ] Update form flow logic diagram in existing MURAL for Steps 5-7 #70303 (removed mid-sprint)

**ENGINEERING**

**_MVP relaunch: Frontend work_**
- [ ] [MVP] Step 3: Match question wording and copy for Are you 65 years old or older?  #69757 - **_Sprint 7 rollover_**
- [x] [MVP] Step 3: Create 2 new pages and questions for Claimant lives in nursing home #69751 - **_Sprint 7 rollover_**
- [x] [MVP] Step 1 Claimant/Vet Info: VA File Number Logic & Copy Updates #70328
- [x] [MVP] Step 1 Applicant Info: Add new question for email #70330
- [x] [MVP] Step 1 Applicant Info: Add new question for mailing address #70329
- [x] [MVP] Step 2 Military Info: Match exiting questions to new design wording and copy #70331
- [ ] [MVP] Step 4 Household info: Create new page and question for What's your marital status and match copy #69959
- [ ] [MVP] Step 4 Household info: Create new page and question for Reason you're separated and match copy #69960
- [ ] [MVP] Step 4 Household info: Create new page and question for Financial support for your spouse and match copy #69961
- [ ] [MVP] Step 4 Household info: Create new page and question for Current spouse marital history and match copy #69962
- [ ] [MVP] Step 4 Household info: Match rearranged questions, options and add multi-entry for Spouse's former marriage(s) #69963
- [ ] [MVP] Step 4 Household info: Match question wording for 7 questions under Dependent children details #69967
- [ ] [MVP] Step 4 Household info: Create expandable section for Dependent's disabilities and match copy #69970
- [ ] [MVP] Step 4 Household info: Match question wording for 6 questions under Dependent children details #69972

**_PDF data mapping_**
- [ ] [PDF Mapping] Push in the new PDF and PdfFiller classes #70382
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 1: Identification Info #70385

**_Setting up logging and monitoring:_**
_- Holding off on additional Datadog work so we can catch up on FE work._

## **Future Sprints**

**_MVP relaunch: Frontend work_**
**SPRINT 9 (Dec 6-Dec 19):** Step 5 FE work, not including Gross Monthly Income questions pending decisions from VBA/VA)
**SPRINT 10 (Dec 20-Jan 2 ONLY 4 WORKING DAYS):** Step 5 for pending Gross Monthly Income questions
**SPRINT 11 (Jan 3-Jan 16):** Steps 6 & 7**

- [ ] [MVP] Step 4 Household Info: Remove 2 questions #70596
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Over 25k in assets #70403
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Estimate total value of your assets #70408
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Did you transfer any assets? #70410
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Do you own your home? #70413
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Is your home on more than 2 acres? #70423
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for What's the value of the land more than 2 acres? #70425
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Is the additional land marketable? #70428
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Do you have more than 4 sources of income? #70535
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Do you have any in-home or care facility expenses? #70538
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Your care expenses/provider name & type #70543
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Your care expenses/provider 1: start & end dates #70544
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Your care expenses/provider 1: How much do you pay? #70545
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Your care expenses/provider 1: How often do you pay? #70546
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Does your spouse have any in-home or care facility expenses? #70549
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Spouse's expenses/provider name & type #70550
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Spouse's expenses/provider 1: start & end dates #70551
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Spouse's expenses/provider 1: How much do you pay? #70552
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Spouse's expenses/provider 1: How often do you pay? #70554
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Does your child have any in-home or care facility expenses? #70562
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Child's expenses/provider name & type #70563
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Child's expenses/provider 1: start & end dates #70564
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Child's expenses/provider 1: How much do you pay? #70565
- [ ] [MVP] Step 5 Financial info, expenses: Create new page and question for Child's expenses/provider 1: How often do you pay? #70566

**_PDF data mapping_**
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 2: Contact Info #70386
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 3: Service Info #70387
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 4: Pension Info #70388
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 5: Employment History #70389
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 6: Marital Status and Spouse Info #70390
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 7: Prior Marital History #70392
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 8: Dependent Children #70393
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 9: Income and Assets #70394
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 10: Info About Unreimbursed Medical Expenses #70395
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 11: Direct Deposit Info #70396
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 12: Claim Certification and Signature #70397
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 13: Witness to Signature #70398

**_Intent to File_**
- [ ] [MVP] Extend Pension Form Expiration #68648

**_Schema mapping_**
- [ ] [Schema mapping] Document all new questions, questions removed on Google Sheet doc #70402

**_Migrating to Lighthouse Benefits Intake API:_** 
_- Complete this migration; incorporate polling strategy._
