### ISSUE TITLE
Write & Publish PagerDuty Content

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70262]
## Description
We will be needing to provide access to PagerDuty on the Platform Website, as we will be opening up some seats to VFS Teams. This ticket is to create, and publish content around PagerDuty on the Platform Website.

We learned from Clint Little, that the steps to get access to PagerDuty are the following:

> "If a person requires/needs/wants PagerDuty access they request this through the #vfs-platform-support channel. This generates a ticket for Tier1 to review and they typically reach out to me for approval (primarily because we need/have to be "picky" about granting licenses)."

## Definition of Done

- [x] All tasks below are complete.

## Tasks
Steps to reach definition of done.

- [x] Located proper location for access instructions, likely will be on the [Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) page
- [x]  Add requirements for granting access to a user to this page, using the guidance provided above in the description
- [x] Confirm content is correct with Alyssa Gallion, Erika Washburn, and Clint Little.
- [x] Once confirmed, prepare page for deployment.
- [ ] Deploy page.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/70262?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by johnny-jesensky-adhoc** [comment]
@laucon - following up on your question around the PagerDuty access ticket - please update the documentation to lead the user to the following path:

**Assign To:** DevOps Support
**Request Topic:** Access Request. 

The support team is going to be making some changes to this menu in the near future, so this will likely change eventually, but this path should suffice for now.

**Comment by EWashb** [comment]
I like what you have for the NOW portion of the work and the reason for the ticket to begin with. Those instructions are clear and concise. I have nothing to add to them.

For the later, I agree that there's a second ticket needed to look at this holistically. One- what can we do on the Support Team to request the information needed at the initial point of ticket creation and then Two- what documentation can the Content Team provide to support that.

**Comment by johnny-jesensky-adhoc** [comment]
@EWashb, @alyssagallion - Great, thanks for the feedback. I went ahead and created a [separate ticket ](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/71013)in our backlog for our team to flesh out.

@laucon, I just reassigned this ticket to you. Please proceed by adding the below language on the _[Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools)_ page. Please reach out to me directly if you have any questions.

> “To request access to PagerDuty, submit a ticket in the #vfs-platform-support Slack channel. Assign the ticket to “DevOps Support” using the Request Topic, “Access Request.” In the ticket, explain that you want access to PagerDuty.
> 
> See Getting help from the Platform in Slack for more information on creating a Slack ticket in the #vfs-platform-support channel. The ticket will be routed to the Platform Support Tier 1 team to triage. They will provide next steps on your access approval.”

**Comment by laucon** [comment]
Done. It should be deployed Monday. :)

**Comment by johnny-jesensky-adhoc** [comment]
The[ Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) page has been updated and deployed as of 12/4. Closing this ticket out, and will shift our attention to [this ticket ](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/71013)that will look to clarify instructions when submitting a ticket.
