### ISSUE TITLE
Identity Dashboard (FE) - Investigate Login

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#70270]
## Description
There were issues reported with the Identity Dashboard frontend related to redirects and the monitoring page. This ticket aims to investigate and resolve those issues. 

## Tasks
- [x] Investigate the source of the redirect problem.
- [x] Investigate the source of the monitoring page problem.
- [x] Fix any issues as necessary.
