### ISSUE TITLE
Resolve or assign vets-api CodeQL issues

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#70287]
### Summary
CodeQL does security scanning for repos within the department-of-veterans-affairs github org. There is no enforcement _at this time_ for fixing them, but nevertheless it would be good to look into them. These are the [CodeQL issues reported](https://github.com/department-of-veterans-affairs/vets-api/security/code-scanning?query=is%3Aopen+branch%3Amaster+) in vets-api.

### Tasks
- [ ] Investigate the warnings
- [ ] Fix the violations or if they're happening in code that Platform doesn't own, pass them on to the owning team. (_Note: if you click on an alert, there is a button to "Create issue" from a particular alert_)

### Acceptance criteria
- [ ] All CodeQL issues have been accounted for (resolved or assigned to another team)
