### ISSUE TITLE
Complete set up for research

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#70283]
## User Story
As a Governance team member, I want to get set up for executing my research plan so that I am prepared to begin research once we receive PO approval. 

Assignee: @erinrwhite 
Peer Reviewer: @rferguson13 

## Description
In tickets #63507 and #69456 we defined our research plans for validating our new VA.gov experience Standards with VFS teams as well as with the Governance teams (aka ourselves). While we await for PO approval on the research plan, we need to set up the surveys, modify our operational guidance (add temporary steps), and get the research set up so that we are fully prepared.

## Impacted Artifacts
[VFS research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2832498689/2023-11+New+experience+standards+VFS+teams+Research+plan)
[Governance research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan)
[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
[Staging Review - during the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting)
[Staging Review - After the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting) -???

## Tasks
- [x] [Governance team survey](https://dj540s05.optimalworkshop.com/questions/leq99pvk)
- [x] [VFS team survey](https://dj540s05.optimalworkshop.com/questions/8gw2k8yr)
- [x] [#70283 - Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2867298305/%2370283+-+Staging+Review+-+Scheduling)
- [x] [#70283 - Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2868707329/%2370283+-+Staging+Review+-+During+the+meeting)
- [x] [#70283 - Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866675752/%2370283+-+Staging+Review+-+After+the+Meeting)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team is ready to execute the [VFS team Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2832498689/2023-11+New+experience+standards+VFS+teams+Research+plan)
- [ ] Governance team is ready to execute the [Governance team Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan)

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@erinrwhite I got this ticket a bit more flushed out and added you as assignee. I think you should have enough to go on. We can address any gaps when I'm back on 11/27.

**Comment by erinrwhite** [comment]
Continuing this ticket into the next sprint!

**Comment by erinrwhite** [comment]
@rferguson13 Morning! Can you review these two draft surveys?

[Governance team survey](https://dj540s05.optimalworkshop.com/questions/leq99pvk)
[VFS team survey](https://dj540s05.optimalworkshop.com/questions/8gw2k8yr)

Questions:
 - updates to question wording, or wording on the welcome page for the VFS survey?
 - should these surveys be all on one page or one question per page?
 - any other feedback?

**Comment by rferguson13** [comment]
@erinrwhite - I noticed only one of the VSF Team Survey questions was required. Is that by design?

**Comment by erinrwhite** [comment]
@rferguson13 gotcha! updated the VFS survey. Any other edits on either survey, or thoughts on one long page vs 1 question at a time?

**Comment by rferguson13** [comment]
@erinrwhite I know it goes against design principles, but I don't mind the long page as much. Maybe two pages to avoid fatigue, but I could see teams getting frustrated with 13ish pages.

**Comment by erinrwhite** [comment]
@rferguson13 that's what I was thinking too! Okay, thank you for the feedback. More soon.

**Comment by erinrwhite** [comment]
@rferguson13 

I think these documentation drafts are ready for your review! I noted the changed sections using comments. Overall, not a lot of alterations.

 - [#70283 - Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2867298305/%2370283+-+Staging+Review+-+Scheduling)
 - [#70283 - Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2868707329/%2370283+-+Staging+Review+-+During+the+meeting)
 - [#70283 - Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2866675752/%2370283+-+Staging+Review+-+After+the+Meeting)

**Comment by rferguson13** [comment]
@erinrwhite Overall, this looks good! One clarifying question on two of the pages - should we have a suggested timeline for filling out the surveys? E.g. "Please try to complete this survey within 1-2 business days."

**Comment by erinrwhite** [comment]
@rferguson13 thank you for the review! I made the updates based on your feedback. I *think* this ticket might be complete. Can you check behind me?

**Comment by rferguson13** [comment]
@erinrwhite Looks good!

**Comment by erinrwhite** [comment]
@rferguson13 hooray! 
@shiragoodman We didn't check anything under "team notification" here - just verifying none is needed?

**Comment by shiragoodman** [comment]
thanks @erinrwhite . I probably checked it by Zenhub didn't register. No notification needed. 👍
