### ISSUE TITLE
[PM] My VA BAD section: Form look-up for existing SiP forms

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#70284]
## Background
We are planning to improve the "save in progress" configuration process. Part of that will be notifying the teams who own the forms that are currently configured as SiP so they can make necessary updates. We have a list of forms that are currently configured but need to do a look-up and map them to the teams. 

[Google sheet](https://docs.google.com/spreadsheets/d/1kra-6J4y3qJxthaS1s4IPgrNLAB7a0qq3a5_m1KDiKM/edit#gid=0)

## Tasks
- [x] Look up forms
- [x] Map to teams
- [ ] ~Work with Chante to get in touch with appropriate teams~

## Acceptance Criteria
- [ ] Forms looked up and mapped

**Comment by ajakabcin** [comment]
Didn't get to this within the sprint, rolling to next

**Comment by ajakabcin** [comment]
Unfortunately I did not get to this within this sprint and with my PTO coming up over next sprint it's unlikely to get done then - pushing this to the first sprint in January.

**Comment by ajakabcin** [comment]
Deprioritizing this and pushing to backlog for now
