### ISSUE TITLE
[FE/UX] 10-10EZR: STG Review Layout/Accessibility Changes

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70306]
**Fix the following issues**

- [x] [70185](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70185) - HTML markup isn't valid - 
- [x] [70193](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70193) (DONE! Just putting it here for tracking) - Design component or pattern is not functioning or working as expected. - All pages: Nav link for "My Health" is broken in breadcrumbs - goes to /my-heath instead of /my-health
- [x] [70194](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70194) - Design component or pattern is not functioning or working as expected - There seems to be padding between the prefill alert and the h3 and then also h3 and the question. This is throughout the whole form.
- [x] [70195](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70195) - Design component or pattern is not functioning or working as expected - On Step 1, the address block left border is 7px and is not using the component in Storybook. The address block left border should be 3px.
- [x] [70196](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70196) - Design component or pattern is not functioning or working as expected - On the Insurance policies page /insurance-information/policies, it is not immediately clear what question the user is being asked
- [x] [70219](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70219) - Design component or pattern is not functioning or working as expected - On Step 3, "Provide either your insurance..." and "Or" are Bitter and 16px. This does not match the current typography in the design system.
- [x] [70198 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70198)- Content likely to be missed by screen reader users - No VA.gov Experience Standard for the issue found.
- [x] [70199](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70199) - Content likely to be missed by screen reader users - No VA.gov Experience Standard for the issue found.
- [x] [70200](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70200) - Content likely to be missed by screen reader users - No VA.gov Experience Standard for the issue found.
- [x] [Review Aliyah's feedback](https://dsva.slack.com/archives/C05QKRZGHFS/p1700258551160389?thread_ts=1700257274.711279&cid=C05QKRZGHFS)
- [x] Discuss with Aliyah and UX if there are any content questions--have Aliyah review once we're done
- [x] Validate with PM

**Moved to Icebox because it cannot be completed as part of this ticket:**
- [ ] [70197](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70197) - A user flow has repetitive or redundant steps - There are two points during the form flow where the user could enter personal information and financial information about their spouse.

**Comment by jessicastump** [comment]
For number 70196, the private insurance page question and review - [here is the Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/5254D5F8-252D-4C39-9AA7-978939F2ED26/canvas) from the Slack convo

**Comment by jessicastump** [comment]
For number 70219, the design files have this as text style body > bold.

**Comment by longmd** [comment]
@jessicastump / @alexseelig , do we agree that 70197 is just a greater flow to think about for the future and not one where there is any immediate action that needs taken? They could not even give a recommendation on a solution.

**Comment by jessicastump** [comment]
I agree that should be part of a bigger household section update effort and not part of this, we could make it a v2 similar to the insurance section suggested updates.

**Comment by alexseelig** [comment]
I have moved 70197 to the Icebox and noted it in the body of the story

**Comment by longmd** [comment]
@alexseelig / @hdjustice / @jessicastump , all the relevant issues have all been completed and are ready for final sign-off/validation and closing.

**Comment by jessicastump** [comment]
An initial/partial review. 

- [70193](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70193) - Yep, done! ;) 
- [70195](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70195) -Verified completed
- [70196](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70196) - Verified completed
[70219](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70219)  - The two lines of text don’t match. “Provide either your insurance policy number or group code.” I think is the fieldset title and still showing in serif/Bitter font. The Or is a sans serif bold… but the design typography guidance does not list these on the typography reference/in the ticket. Would changing these to a regular paragraph styling make them consistent/is that possible?

**Comment by longmd** [comment]
@jessicastump , as soon as the referenced PR is in place, these will be any unavailable pages will be available again. I misunderstood the ask for `70219`, so I have made both the Sans text and base font size.

**Comment by longmd** [comment]
@hdjustice / @jessicastump , the edits for the broken/missing pages are in staging.

**Comment by hdjustice** [comment]
I am looking at this one

**Comment by jessicastump** [comment]
70219 looks correct in staging now to me...
But I am having trouble getting into the household section/spouse questions now with the current year income on file alerts in place. I did add a comment to #70452 ticket though.
I have tried with test users 228 and 11 so far.

**Comment by longmd** [comment]
@jessicastump , there is a BE bug that is preventing us from accessing those at the moment. Josh has put in a fix. Once it is up, we will be able to use test user +40 to access.

**Comment by hdjustice** [comment]
same on 70219 - looks like it matches up now.

**Comment by hdjustice** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/70185 - The information is read properly, even when tabbing to the first phone number field

**Comment by hdjustice** [comment]
@longmd - i think that addresses everything, let me know if I missed anything

**Comment by longmd** [comment]
@hdjustice , I have a [PR up](https://github.com/department-of-veterans-affairs/vets-website/pull/27060) for the two finds related to the policy list and medicare claim number hint. Once merged in, I think we will be good to go to close this one!! 🚀

**Comment by longmd** [comment]
@hdjustice , here is visual evidence of the reported issues from the insurance being fixed:

**Policies before:**

<img width="1239" alt="Screenshot 2023-12-08 at 3 43 26 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/e0314867-a6bd-4014-a366-78c2b95330ae">

**Policies after:**

<img width="1208" alt="Screenshot 2023-12-08 at 3 44 41 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/cad9e8e1-ca78-4f3b-a9ed-376230336a5a">

**Medicare claim number (everything inside that label gets read:**

<img width="689" alt="Screenshot 2023-12-08 at 3 45 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/bf0e7122-96f7-4ccf-a69c-b72b937320d9">

**Comment by hdjustice** [comment]
Medicare screen has "who meet" twice
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/67b74626-8856-4087-a385-cac96949d80e)

**Comment by hdjustice** [comment]
Using NVDA - Medicare hint can now be heard after the question, when focus is on the input field, as expected.  The insurance review page, on the existing policy card, the Edit link and Remove button are announced properly.

**Comment by hdjustice** [comment]
Medicare content update removing the extra "who meet" has been completed and deployed
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/df708546-a921-45e6-b1bd-dafe27dda42d)
