### ISSUE TITLE
[MVP] Update form flow logic diagram in existing MURAL for Steps 5-7

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70303]
## Issue Description
As a Pension team,
**we need to have an overall form flow logic diagram for the Pension form,**
so that when engineerings build new question fields OR edit existing ones they are aware and confident they are following the form flow logic at every point.

A MURAL board exists for the form flow's conditional logic. [See this board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660) for reference.

---
## Tasks
- [ ] Update the form flow logic diagram found in the [existing MURAL board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660) for Steps 5-7
- [ ] Share any updates completed to the MURAL's existing form flow logic diagram with Pension engineers, product manager and VA stakeholders.

## Acceptance Criteria
- [ ] The [existing MURAL board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660) will show the most updated form flow logic for Steps 5-7.

**Comment by mayacoforma** [comment]
Update on #70303: "Update form flow logic diagram (Steps 5-7)" I have completed updating the logic flow diagram, finalizing steps 5-7. No feedback is required for this task; I am simply sharing to highlight the progress made. 
.Png of steps 1-7: (attached)
Mural Board: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703103128492/30dc0956f99482beffb457eb2ae884430cc2d3f4?sender=u2d8a66f6d38755bd8c4c6218

Note: I've moved the final version into the VA's mural workspace, link is above.

[Uploading... Pension 527EZ Form Logic Diagram (WIP)_2023-12-20_20-04-07.png]
