### ISSUE TITLE
[PM] My VA Health Care: release updates to health care + mhv link

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#70309]
## Background
Last sprint we implemented the changes to the health care section to show the MHV on VA.gov link for all LOA3 users and made updates to the oracle (fka cerner) users' experience. (See [67431](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67431) and [67432](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67432).) We need to release this to users.

## Tasks
- [x] Turn on feature flag in production: `my_va_remove_cerner_message`
- [ ] Confirm all looks good in prod
- [x] Fill in pre-launch baseline stats

## Acceptance Criteria
- [x] New experience appears in prod for health care section (mhv link and oracle users updates)
- [x] Pre-launch stats are filled in
