### ISSUE TITLE
DR | Add error for no eligible issues

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#70334]
## Value Statement
**_As a_** Veteran
**_I want to_** know when issues are not loading because I don't have eligible issues or if the system is down
**_So that_** I can choose whether to wait for the system or to add new issues

---
## Background Context
- As part of the solution for intermittent errors that happen for the contestable issues backend (#[62872](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62872)), we implemented a clearer error message that states 'we can't load your issues right now'. This replaced the previous error that mentioned 'we cannot find eligible issues' as a more accurate message for backend outage. 
- However, the 'we couldn't find any eligible issues' message should still occur when there is a Veteran account that does not have eligible issues in VBMS.

## Acceptance Criteria
- [ ] For Veteran accounts that don't have issues on file, or have issues that don't meet the deadline restrictions show the 'we couldn't find any eligible issues' error message.
- [ ] For Veteran accounts that do have issues on file, but run into a backend error, show the 'we can't load your issues right now' error message. 

## Designs and Build Notes
- If the Veteran has no issues on file, show 'we couldn't find any eligible issues' error. ([Design](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/mPE88vz))
- If contestable issues can't load due to backend error, show the 'we can't load your issues right now' error ([Design](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/qbAvv22))

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] 
- [ ] 

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by eileen-coforma** [comment]
This is now a duplicate of #73525. Already closed.
