### ISSUE TITLE
Developer Docs Audit - Review Metrics for Priority for Wave 2

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70339]
## Description
This is to continue the work done updating the pages identified as part of our Dev Docs audit. We need to determine how many documents/pages fall into that second wave, and what the criteria is for updating the pages.

We will be reviewing some of the metrics around Support Requests, and use that to help determine/assess a priority to update.

## Tasks

- [x] Support metrics have been reviewed, and analyzed for trends.
- [x]  Wave 2 of developer docs review criteria has been established. Focusing on back-end developer docs.
- [x]  Documents have been flagged in the [dev docs audit spreadsheet](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit#gid=799240787).
- [x] Team identified to help update docs.

## Acceptance Criteria
- [x] Additional documents in Dev Docs list have been flagged with a priority wave based on findings.
- [x] Teams have been notified.

## Wave 2 Developer Docs (Backend Developer Documentation)
**_Best Practices --> Supporting Code_**
- Spec File Examples
- Service Object Implementation
- Match Response Schema Implementation
- Controller Route Serializer
- Swagger Implementation
---
_**Running Vets API Locally**_
- Response serialization
- Development
- Request processing
- PDF generation
- Documentation
- Forms
- Service objects
---
**_Tools & Debugging_**
- AWS Shell Access
- Betamocks
- Triage Tier Definitions
- Set up your AWS Account
---
_**Backend Standards + Architecture**_
- Working with the Engineering Team
- Threat Model in Practice
- Integration Approach
- Overview
- Authorization Design Doc
---
**_Misc_**
- VA.gov Continuous Integration Process
- Writing Small PRs
- Health Quest Service

**Comment by johnny-jesensky-adhoc** [comment]
Messaged Lainey on Wave 2 document priorities - will be working to ensure those docs are updated as part of an upcoming ticket. Marking this as _Done_.
