### ISSUE TITLE
Design | Auth Experience | Audit | Opportunity review of VA.gov

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#70337]
## Background
We know the auth exp on VA.gov isn't great. Let's create an informal audit doc of the opportunities for improvement we see across the site.

## Tasks

- [x] Review [opportunity doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/123eb1aaebf2273ffa9c744f1ddad976cd57d61f/products/identity-personalization/personalization-enhancements/opportunities.md) created earlier this year so it's fresh
- [x] Review VA.gov and create list of opportunities. Make sure to include top task areas of the site.
- [x] Share list with Auth Exp team for discussion

## AC

- [ ] Opportunity list has been reviewed with team

**Comment by Samara-Strauss** [comment]
Sorry this is VERY late in the game -- this list/deliverable should focus on the problems. It should not be a list of recommendations or solutions.

**Comment by andaleliz** [comment]
@Samara-Strauss yep, that's what I'm planning on capturing through this work.  I started jotting down some things off the top of my head on [this Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701044250903/5b3495239169c934c4fbf620eb50178b1952c97d?sender=ub868d471cfdb1c56cc0b4512), and I'll be logging into the site to really dig in later today and tomorrow.

I'm not quite sure yet what shape the final deliverable will take - probably either a more organized Mural board (you can see some of the categories that occurred to me so far), a spreadsheet, or a markdown doc. 

Do you have any preference on the shape final deliverable?

I'm also meeting with Matt later today to chat with him about this and get his fresh perspective on the problems on the site.

**Comment by Samara-Strauss** [comment]
> Do you have any preference on the shape final deliverable?

An organized list would be totally fine. Something easily scannable and shareable.

> I'm also meeting with Matt later today to chat with him about this and get his fresh perspective on the problems on the site.

Awesome! I'm gonna talk to AJ about having Matt put together his own deliverable next sprint (assuming he is busy onboarding this sprint, but if not, he can work on it sooner).

**Comment by andaleliz** [comment]
@Samara-Strauss, could you please take a look at [my Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701044250903/5b3495239169c934c4fbf620eb50178b1952c97d?sender=ub868d471cfdb1c56cc0b4512)and let me know if the comments on the stickies are on the right track, before I go further? 

I've covered broad strokes on the main areas of the site and [tools associated with the top 25 pages people visit when signed in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/research-and-analytics/2023-generative-logged-in-research/analytics-review-findings.md#what-are-the-25-most-popular-pages-visited-while-signed-in). I still need to go through a form flow or two. 

Thanks, and I look forward to your feedback!

**Comment by Samara-Strauss** [comment]
Liz, this is incredible and I am so excited about everything :D

**Comment by andaleliz** [comment]
@Samara-Strauss awesome! I'm so happy to hear that. I'm aiming to have this finished up and in a scannable, sharable form no later than Thursday late morning.

FYI, I am purposely not sharing any of my work with Matt until he goes through this exercise too, so I don't influence him.

**Comment by pamela-drouin** [comment]
What you've pulled together is comprehensive! I agree with everything you've pointed out. The ones that stand out the most to me are around wayfinding and differentiating/making sense of My VA/Profile/MHV on VA 😵‍💫

**Comment by andaleliz** [comment]
@Samara-Strauss, I [finished my write up](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/auth-exp-problems.md) and it is ready for your reading pleasure :)

I'm excited to hear your thoughts and how you'd like to proceed! I wrote down some potential next steps that came to mind, but nothing is prescriptive or absolutely necessary in my mind.  

I'll leave this ticket open until I hear back from you.

**Comment by andaleliz** [comment]
Oh, I forgot to mention - I didn't get to go as in-depth into forms as I expected. I encountered so many bugs and weird things, it became way more time consuming than I expected or felt was worthwhile for this particular project. It was starting to go beyond the scope of this work and into the realm of bug-hunting.

**Comment by pamela-drouin** [comment]
Liz, I'm reviewing this and it's fantastic so far. A question: are all of your findings within our [sphere of control](https://medium.com/@chrisjmoss/https-medium-com-chrisjmoss-agile-advice-extending-your-sphere-of-influence-b3e21dd1ec4f)?

**Comment by Samara-Strauss** [comment]
FINALLY had a chance to review. This is excellent and so helpful to have a list of problems in one, consolidated place. Thank you so so much. I'm going to do some thinking about how we might want to incorporate some of these findings into our work for the next year.

This should be good to close!
