### ISSUE TITLE
Pre-Usability Review [Left Nav]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7033]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [x] [Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-left-nav-enhancement-feature-brief.md)
- [x] Link to [prototype](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874#issuecomment-595797269)
- [x] Link to [mobile prototype](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874#issuecomment-601907235)
- [x] Link to or attach artifact with copy _This work is mostly design change. content is not impacted._
- [ ] Link to research plan: _It was determined during kickoff that we may not be heading directly into usability from this meeting so this artifact is not needed at this time._ 
- [ ] Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- [x] Link to **DRAFT** [test cases/test plan](https://dsvavsp.testrail.io/index.php?/cases/view/391) (even if just a draft) in TestRail _for QA practice area review_

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Ryan Thurlwell**
**Kevin Hoffman**

## Scheduling
Preferred dates or times: 

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by meganhkelley** [comment]
Scheduled for 3/31 — as mentioned in Slack @mmiddaugh, please let us know if that delay is blocking to you and we can get it moved sooner! 

Also, reviewers note that per Andrea's Slack message, this team is not doing usability testing (just using this template) and some artifacts above will be missing — only expected artifacts here are the Product Brief/Outline and the Mockup/Prototypes 

Kickoff for this feature #6751

**Comment by meganhkelley** [comment]
Rescheduled for 3/24 to unblock team

**Comment by mmiddaugh** [comment]
Feedback requested from the following practice areas during kickoff 3/24:
1. Design
2. Accessibility
3. QA
