### ISSUE TITLE
FE & Design | Profile | Enhanced military info | Build FE dev tool to improve data consumption

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#70348]
## Background
We're going to get a whole bunch of data from the military service info api. Let's get it into a format that's easier to work with once we need to get this in front of veterans. @adamwhitlock1 has gotten started on this.

This tool should only be present on the local environment or if a feature toggle is turned on for that user in staging or production. We will start by using the `profile_use_experiemental` toggle to trigger the tool being present. The tool should also not be included in the code bundle for profile and instead requested when the tool is toggled on (Adam has already started on figuring this part out) that way the tool doesn't increase the load time for the production site.

As a developer / non-production tool, what could this look like?
- panel or modal that opens to display the data
- a section below the main page content that dumps out the data is a more readable way
- if it is used as a non-veteran facing tool to consume and display data for troubleshooting, then maybe it could just log out information to the console, so that it doesn't affect the UX at all (this is more around the idea of using this tool long term for other data/situations)
- From a technical standpoint, how should the data be provided to such a tool? Wrapping a component in a `<Devtool>` instance and then accessing the children, or just passing data in as props to the `<Devtool data={'blah'} />` or maybe both? Making the tool versatile enough to use elsewhere, but friendly enough to get in front of a veteran is the key.
- The ability to copy the data or parts of the data to the clipboard so that potentially complex pieces of JSON / nested data would not need to be manually copied.
 
How would the data look and be formatted?
- raw json data that is 'dumped' out with minimal formatting, but would be hard to sift through.
- a way to hide certain data that isn't important and make it easier to read
- its pretty open right now since we don't exactly know what military info will look like, but other use cases like the notification settings / default send indicator work could have used a way for us to 'peep' at the underlying data, so its interesting to think about how a tool like this would look  

## Tasks
- [ ] Adam to build FE
- [ ] Liz to provide UX feedback/ideas
- [ ] Create documentation about how this tool works
- [ ] ...

**Comment by adamwhitlock1** [comment]
this one I'd say roll over 2 points on. Spent a lot of time on the PPIU stuff and just getting to the point on this one for writing tests and getting it ready to review with Liz in a day or two.

**Comment by mtcA6** [comment]
@adamwhitlock1 is there a way I should test this?

**Comment by adamwhitlock1** [comment]
This is kind of a 'build the tool' task more than using it for the new military information endpoint specifically, since that endpoint wasn't quite available yet when I was building this.

I suppose the next step would be to hook up the new mil info endpoint to the devtool and display the data in staging.

Right now, I have turned on the devtool toggle, and created a placeholder devtool instance that will show only in staging and be exempt from any production build bundle.

You can see it within the military info page right now in staging:
![Screenshot 2023-12-19 at 11 18 23 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/f1318afb-4891-43af-9ff5-9be4538f19ff)

If you click on the little code icon, there is an expandable panel that displays that allows a user/dev to inspect the underlying data that was used within that devtools instance, more or less for diagnostic purposes.

![Screenshot 2023-12-19 at 11 19 13 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/e84098a8-47ca-4bb4-8c40-99d4aa7279ce)

So yea thats it so far, but I figure that as we move forward with mockups and getting some prototypes created, we can use this devtool to evaluate the data that is returned and also conditionally include a new layout/info section on the page.

**Comment by mtcA6** [comment]
I was WAY behind on my email gh alerts, gonna check this out! @adamwhitlock1 thanks!
