### ISSUE TITLE
Add Reminder to Support Channel for Tier 2 to Check PR Queues

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70354]
## Description 
This ticket will house the task of creating a Slack reminder for Tier 2 rotation members. It will remind them to check for PR reviews to ensure we maintain compliance with the 24-hour policy.

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Add a reminder in the DSVA #platform-tech-support-team channel reminding Tier 2 folks to check the DevOps, Frontend and Backend Queues. [Links outlined here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2845835331).
- [ ] If possible, make sure that the automation tags those on Tier 2 rotation automatically to ensure they see the notification even if notifications are off for the channel
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
