### ISSUE TITLE
NOD | Clean up NOD create request body `example.json` in vets-json-schema

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#70357]
## Value Statement
**_As a_**  Developer
**_I want to_** be able to reference/use the NOD `create` request body example defined in vets-json-schema
**_So that_** we have example data to use in tests that is accurate and consistent

## Background Context
As discovered in the work to clean up the NOD v2 controller and tests, we found that [the mock/example data being used](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/NOD-create-request-body_v1/example.json) in the [original iteration of the request specs](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/requests/v1/notice_of_disagreements_controller_request_spec.rb#L27) was actually using the structure of the _response_ body instead of the _request_ body ([see Lighthouse docs for `POST /notice_of_disagreements`](https://dev-developer.va.gov/explore/api/decision-reviews/docs?version=current)) and [this comment for investigation notes](https://github.com/department-of-veterans-affairs/vets-api/pull/14584#discussion_r1399836263). So the goal here is to clean that up and fix that example to have the proper structure. 

This should also hopefully clean up the Swagger docs for [`vets-api`](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/) (switch to v1 instead of v0 in the `https://dev-api.va.gov/v0/apidocs` in the "explore" bar at the top of the page)

## Out of scope

* Other example data clean up

## Tasks

- [ ] Update the example in [example.json](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/NOD-create-request-body_v1/example.json)
- [ ] Determine if there are any additional steps to update the `vets-json-schema` dependency for `vets-api` app
- [ ] Determine if any other apps (i.e. `vets-website`) are impacted by this change
- [ ] Clean up any tests on `vets-api` that might be impacted by this update
- [ ] Check that v1 Swagger docs are updated locally once the `example.json` is updated

## Definition of Ready 
- [ ] We've identified any additional steps to update `vets-api` to pick up this change
- [ ] We've identified any additional clean up that `vets-website` might need as a result of this change
- [ ] We've identified any tests that might break from this update

## Definition of Done
- [ ] We can see the updated Swagger documentation and it displays the correct request body structure for `POST /v1/notice_of_disagreements`
- [ ] Our v1 tests can use this updated example and continue to pass

**Comment by saderagsdale** [comment]
@anniebtran will estimate.

**Comment by data-doge** [comment]
Closing. Annie tested locally by hardcoding timezone. If our logs show this error reoccuring, we can re-open ticket.

**Comment by data-doge** [comment]
Woops, closed wrong ticket - ignore please.

**Comment by saderagsdale** [comment]
@data-doge I changed the status to "Ready for Pickup" and moved it to sprint 44.
