### ISSUE TITLE
Research: Automate PR Status Updates in Slack

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70351]
## Description 
While on support rotation, Eric Boehs used a macro that shows updates on current PR reviews in the #paltform-tech-team-support channel. [View example here](https://dsva.slack.com/archives/C02RLAUM2LV/p1699564245567579) or in the attached screenshot. 

Note: This ticket is only designed to handle the task of creating an automation, not overhauling the PR review process entirely. See Pull Request Review Enhancements epic for additional details on other enhancements we are making.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Review this ticket and the documentation provided
- [x] Speak with Eric to determine what work would need to be done to create a macro for PR request automation (DevOps, FrontEnd, and Backend)
- [x] Create a ticket outlining what steps need to be accomplished to enable this macro and put it in the backlog 
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2YyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbcee00e3432cd395654f3ed4d22f31611b85df9/Screenshot%202023-11-21%20at%2010.27.09%20AM.png)

**Comment by alyssagallion** [comment]
Research complete. Closing.

**Comment by alyssagallion** [comment]
See ticket for executing the bot here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/78088
