### ISSUE TITLE
Create Forms Digitization Guidance landing MVP

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#70369]
## Purpose
There is no 1 Stop Shop for discovering all of the disconnected information and resources useful for digitizing a form.  In addition, most teams generally piece together a process for performing the digitization of a form in a vacuum. There is some forms guidance on the Platform Docs site and other disparate locations, but what other guidance would be beneficial to complete the arc for teams who are newish to the process, or needing the benefit of a proven process?

Ultimately, can we use our learnings from the recent research effort, along with gathering all of the existing resources, and and assemble it on the Platform Docs site to create more of a 1-stop shop for Forms Digitization guidance?

Existing resources:
Forms Library [overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview)
[Getting started page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md) from github (hasn't been updated in > year, and not easy to find or know it exists)
Form design [process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/design-resources/form-design-process.md) (not sure this exists in updated form)

## Problem Statement
Form Digitization is a high priority for the VA but there is an enormous backlog of work combined with a slow and inconsistent process for digitization.

We intend to create a resource that establishes the main steps needed to digitize a form, along with notable pain points and best practices, and emphasizes available resources.

## High Level User Stories
-As a VFS team, I want a standardized process for form digitization so that I can easily and efficiently produce digitized forms that meet standards while utilizing Platform tools and guidance. 
-As Platform leadership, I want the digitization of forms to be more consistent so that teams don't struggle to perform this activity.
-As OCTODE, I want forms digitization to become clearer and easier so that the large backlog of hardcopy forms can be made to conform to the modernization efforts of the broader VA.

## Bet
By creating guidance on digitizing forms, we can provide VFS teams with a jump start on their efforts, as initial wayfinding was demonstrated to be one of the largest time sinks according to our research.  

Additionally, we can help them move efficiently by providing the proven steps and best practices, along with pain points that are often encountered.  

Accomplishing this will thereby reduce the time needed for a team to successfully complete a form's digitization.

## Definition of Done
- [x] Phases and Steps are fleshed out and contain helpful information
- [x] Landing is Drafted
- [x] Phases and Steps are easy to locate and understand
- [x] Landing is Published
- [x] Related artifacts are linked and functional

## Desirable Outcomes
-VFS team will be able to quickly identify what is needed to get a form underway
-VFS team will be able to easily note and find the latest resources that are relevant to form creation.
-VFS teams reuse rather than invent (ex: adopt a previous model of stakeholder aligning rather than having to figure it out)-Consistency across form process that becomes predictable/easy to replicate and measure
-VFS teams will be set up for success from the beginning of their process and receive guidance through each step
-Forms digitization becomes clearer and easier, allowing for better progress with the large backlog of hardcopy forms. 

## Undesirable Outcomes
- The guidance is hard to absorb
- The guidance is mistaken for a rigid checklist/blocker
- SDT or PCT get a lot of "what does this mean" questions
- The guidance is too broad to be actionable

## KRs / HMs
KR:  Decrease in the time it takes teams to digitize a form
HM: Increase in Veteran satisfaction with form availability.
HM:  Reduction in negative overall experience over time
HM:  Reduced time to stakeholder alignment
HM:  New landing and pages are accessed with regularity

## Documentation
[Product Outline](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2856321060/Product+Outline+-+Forms+Digitization+Guidance+landing)
