### ISSUE TITLE
[UX][Design] SPIKE: Determine whether we need to change the position on page or UI of the Refresh button and feature

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70362]
## Background

Over the last 30 days, ~11% of unique pageviews of /details/ (appointment list page) select the Refresh button (at least once) in check in. 

SPIKE: Determine whether we need to change the position on page or UI of the Refresh button and feature within the unified check in appointment list page. 

Unified check in appointment list page - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ

Refresh feature in production - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/L4JGlEy

Message from Matt about if a design pattern for refresh page exists: 

> Nothing exists. Starting from something we have is one option. The [pull down to refresh pattern](https://ui-patterns.com/patterns/pull-to-refresh) is fairly common and is worth investigating.

## Tasks
- [ ] Review the materials in the Background before the SPIKE meeting
- [ ] Create design options (team chooses fidelity of the design options based on situation)
- [ ] Get feedback from appropriate stakeholder(s). E.g., content or a11y SMEs, platform design, UX team, check in team, VA OCTO PO's, check in PO, Angela Fowler (a11y) or Sara Sterkenburg (IA).
- [ ] Incorporate feedback into solution(s) 
- [ ] Choose the target design solution
- [ ] Check to see if tickets exist to implement the final design decision and are accurate (or create them, if necessary)

## Acceptance Criteria
- [ ] Design solution has been chosen
- [ ] Design solution idea has been vetted and approved by appropriate stakeholders 
- [ ] Follow up tickets have been created for content and design implementation

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/70362?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by benbrasso-agile6** [comment]
Our decision is to explore some UI changes to the current pattern, but no pull down.
