### ISSUE TITLE
[FSR Wizard] Prototype for Updated Wizard (Complete a subtask)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#70365]
## Description

For the wizard research, we'll need to test the updated content and logic of the new complete a subtask pattern; rather than using UXPin to create a prototype, we'd like to use an off-the-shelf form builder that's more accessible to test the content. 
This can be utilized for co-design sessions.

Scenario: In common language describe the work or issue

Given: A veteran wants to fill out the FSR
When: A veteran wants to determine whether or not the FSR is for them
Then: A veteran will be able to click through the new wizard and get the answer they need

## Tasks
- [x] Create a prototype with content and flow from Sketch files

## Acceptance criteria

- [x] Prototype has been created
- [x] Prototype has been QA'd

## Testing
- [x] Test logic and paths go to correct results
- [x] Test with screen reader to make sure the prototype is accessible 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [] Attach to an Epic
- [] Estimate Points
</details>

**Comment by josephrlee** [comment]
Here's the prototype: https://tally.so/r/wL7Rap 

A couple of caveats: 
- It's not the best from a screenreader standpoint (very hard to find an accessible form builder)
- The other main caveat is that when you click start over, it opens it up in a new window/tab

**Comment by josephrlee** [comment]
@Tom-Davis @HeatherRienks this is ready to be closed now.

**Comment by Tom-Davis** [comment]
Closing as complete - the prototype is finished and linked.
