### ISSUE TITLE
[Data-Load] Create and upload BUTLER, PA - "Campus Map" information from legacy to NEW web pages [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7036]
## User Story or Problem Statement
As a Veteran Web user, I want to see the VAMC campus map page, so I best know the location of my visit and how best to get to my location.

## Goal
_Move legacy MC website campus information from legacy websites over to new CMS system_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience by moving existing stories into new format_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[Pittsburgh example of Campus Map Information](https://www.va.gov/pittsburgh-health-care/)

## Tasks
_Create new page and complete moves from legacy websites to new Campus Map Detail page to include:_
- [ ] Embedded file for download Content Block
- [ ] Embedded image of Campus map.
- [ ] Any additional Embedded maps or files for download.
- [ ] Any language or directions in WYSIWYG.

## Acceptance Criteria

* Embedded file for download Content Block
* Embedded image of Campus map.
* Any additional Embedded maps or files for download.
* Any language or directions in WYSIWYG.
