### ISSUE TITLE
Obtain access to necessary development tools - Oren

### ISSUE THREAD

**Issue by emily-gullo** [department-of-veterans-affairs/va.gov-team#70384]
### Description
The [VFS onboarding checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D) has an item to gain access to various tools. Please review the relevant documentation, identify the tools needed for the project, and complete the access request process for each necessary tool.

### Tasks

- [ ]  Request access to tools listed under [developer tools](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Additionalaccessfordevelopers).
- [ ]  Assess the [DEPO platform documentation](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) to identify any additional tools.
- [ ]  Confirm complete access to all necessary tools before closing this task.

### Tools
 
- [ ] SOCKS access (will grant access to Jenkins, Sentry)
- [ ]  TestRail access
- [ ]  Terminal Access (Vets API Access - EKS)
- [ ]  AWS console access

(Thanks to the Claims Evidence team for the content of this ticket)

**Comment by nihil2501** [comment]
As of now I've obtained access to:
- DSVA Slack
- VA GitHub organization
- Zenhub

But access to the following bundle is (loosely?) all blocked on my eAPP:
- SOCKS
- Vets API Access - EKS
- AWS console access
- TestRail (will just bundle this task with the above, and also reconsider the following comment `TestRail accounts are limited. Please limit account creation to dedicated QA personnel and a shared account for VFS team.` found [here](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-TestRailaccess)

**Comment by nihil2501** [comment]
Also [Datadog access has some more involved steps involving DOTS Okta](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)

**Comment by nihil2501** [comment]
Moving this to Done to represent completion of steps that are relevant currently.
