### ISSUE TITLE
[MVP] Design Review/Sign off for front end changes

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#70404]
### Summary
This ticket is to make sure Maya has a chance to review all of the front end changes that were complete during her OOO. Below are listed tickets that have been reviewed and ready on Staging.

**Front end tickets that are on stage ready to be design reviewed:**
- [ ] #69745 - [MVP] Apply for Veterans Pension Page: Copy Updates
- [ ] #68564 - [MVP] Step 2 Military Info: Add new question, Service Number
- [ ] #68561 - [MVP] Step 2 Military Info: Remove questions
- [ ] #69746 - [MVP] Step 3: Create new page and questions for Enter Social Security Disability details
- [ ] #69748 - [MVP] Step 3: Create new page and questions for Claimant not determined disabled
- [ ] #69750 - [MVP] Step 3: Create new page and questions for Enter nursing home status
- [ ] #69942 - [MVP] Step 3: Match all questions and copy to designs for VA medical center pages
- [ ] #69755 - [MVP] Step 3: Create 2 new pages and questions for Federal medical center status
--- Currently in progress 
- [ ] #70097 - [MVP] Step 3: Match question wording and copy for Are you currently employed?
- [ ] #69758 - [MVP] Step 3: Add new fields for Current employment
- [ ] #69871 - [MVP] Step 3: Create new page and fields for Previous employment

### Acceptance Criteria

-  Design review all tickets listed above. They should all be available on Stage.
-  If there are changes request, create a new engineering ticket to request those changes. (Please consult with eng to determine if 1 ticket can cover all change requests or break them up into multiple tickets.)
-  Check the Design Review checkbox in each ticket listed above  to indicate that design review is complete and add a comment to reference any change requests.

**Comment by vbellissimo** [comment]
This task is no longer needed.
