### ISSUE TITLE
Prepare for tracking Find a Rep KPIs 

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#70419]
I met with the Analytics team and we need to complete some additional tasks to make sure we're prepared for tracking Find a Rep KPIs during our staged rollout and post-launch.

#### Tasks
- [x] Create a new implementation ticket, with information around our custom events
- [x] Create an edge case KPI dashboard ticket for tracking in Domo
- [x] Work with Analytics in Office Hours to setup a dashboard in Google Analytics

**Comment by oddball-lindsay** [comment]
Implementation ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/70420

**Comment by oddball-lindsay** [comment]
Edge case KPI dashboard ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/70424

**Comment by oddball-lindsay** [comment]
Expecting a data layer example from Jamie Stutt on Friday morning, for the Search button custom event.

**Comment by oddball-lindsay** [comment]
1:1 with Jamie scheduled for Monday 12/11

**Comment by oddball-lindsay** [comment]
Jamie is using our staging environment to create data layers and events so we can be setup to track everything when we do go live.
