### ISSUE TITLE
[FSR Wizard] SME conversational interviews to inform Wizard redesign

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#70414]
## Description

UX team will host 4-6 conversational/informal interviews with SME's to inform the Wizard redesign.

This will be an opportunity to gather background information from SMEs and to share early Wizard design work for feedback. 

## Tasks
- [x] Write 1 page research goals and conversation guide for internal alignment (CC)
- [x] Review research plan/conversation guide with UX team and refine (CC, MG, JL)
- [x] Reach out to SMEs, confirm participation, schedule interviews (CC)
- [x] Carry out interviews (CC, MG, JL)
- [x] [ Synthesize feedback](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694632724840/26a6a7207a23a315f2b995eee59f34791a28f0be?sender=ua78f969c4cddcbfe56b27885) (CC, MG, JL)
 
 
## Acceptance criteria

- [x] Research plan/conversation guide has been created
- [x] Guide has been refined per UX team feedback
- [x] Interviews have been scheduled

## Testing
- [ ] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by mgleo** [comment]
Mural link with notes: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694632724840/26a6a7207a23a315f2b995eee59f34791a28f0be?sender=ua78f969c4cddcbfe56b27885

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis Moved to Validate

**Comment by Tom-Davis** [comment]
Closing as complete.
