### ISSUE TITLE
Explore issues w/ previous Cypress versions

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#70422]
# Description
Cypress upgrade to 13.5.1 is failing with time outs in certain Cypress job threads for the CI workflow. We need to investigate why these time outs are happening. There seems to be some evidence that the Cypress upgrade is responsible. We should examine the spec that Cypress is timing out on.

# Tasks
- [ ] Run the tests locally
- [ ] Inspect results of local tests
- [x] Add logging to CI in order to detect the detailed actions being taken immediately before time out occurs
- [ ] Examine Cypress change logs for potential causes

# Acceptance Criteria
- [ ] Time out cause is identified
- [x] A plan for resolving the time out is proposed

**Comment by pjhill** [comment]
Cypress 13.6.1 is failing to download properly --
<img width="1405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenROQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5dea342e52ada5324a114804bb024254fb27f7ef/image.png" alt="image.png" />


CMS starting experiencing the same / similar issue with the CB workflow last week. I believe they had success with Cypress 13.3, so I'm going to try that as well.

**Comment by pjhill** [comment]
Cypress 12.17.4 is the last upgrade that works -- https://github.com/department-of-veterans-affairs/vets-website/actions/runs/7182075293/job/19557778956

**Comment by pjhill** [comment]
In the specific failing spec -- `rated-disabilities.cypress.spec.js` the issue appears to be with a change to how `cy.intercept` is working.

**Comment by pjhill** [comment]
`src/applications/rated-disabilities/tests/e2e/rated-disabilities.cypress.spec.js` was failing because of the use of `beforeEach`. When I ripped that out and explicitly visit the URL in each test spec it works. Seems silly, but perhaps I'm missing something.

Cypress is still timing out on some specs. Need to dig into those now.

**Comment by pjhill** [comment]
The time outs seem to be linked to keyboard tests. I'm skipping keyboard nav tests one by one to see if I can get time outs to stop while running Cypress tests in CI.

The tests do not hang when run locally.

**Comment by pjhill** [comment]
This draft PR passes in CI, but it's less than ideal because 3 keyboard test specs are skipped.
https://github.com/department-of-veterans-affairs/vets-website/pull/27137

**Comment by pjhill** [comment]
Still not hanging locally -- it's hard to fix a thing you can't reproduce locally. I'm going to unskip the `all-claims-keyboard-only` spec, push that, and try to use the playback of the failure from the Mochawesome report to figure out what's going on.

**Comment by pjhill** [comment]
Cypress 13.3 download is failing now.

**Comment by pjhill** [comment]
For all intents and purposes this appears to be blocked by some kind of issue with the TIC -- https://dsva.slack.com/archives/C04CYC4LMU6/p1703002223743319

Until the issue with the TIC is resolved, we won't be able to download Cypress successfully on self-hosted runners operating in govcloud.

**Comment by pjhill** [comment]
This ticket is blocked while the Cypress download for version 13+ is not working. Once that blocker is clear, we will pursue the upgrade under this ticket -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/72406
