### ISSUE TITLE
DR | Update timezone list for SC, HLR, and NOD in `vets-json-schema`

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#70429]
## Value Statement

**_As a_** veteran
**_I want to_** be able to submit my form from a newly added timezone
**_So that_** I don't unintentionally create duplicate submissions from re-attempting to submit

## Background Context

We saw errors for Supplemental Claim submissions when the timezone is `America/Ciudad_Juarez` which was newly added by the Lighthouse team to their schema, but we did not update the schemas we use to validate responses from Lighthouse ([`vets-json-schema`](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/SC-create-request-body_v1/schema.json#L155)) so we get a validation error in our [service call](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/appeals/supplemental_claim_services.rb#L43) even if it was a success on Lighthouse's end. 

[Slack thread for more context](https://dsva.slack.com/archives/CKUCFQAHJ/p1700602740440309?thread_ts=1698083531.827299&cid=CKUCFQAHJ)
[Post in our alerts slack channel](https://dsva.slack.com/archives/C05UPRR0HK3/p1700600980905529?thread_ts=1700600481.415289&cid=C05UPRR0HK3)

## Out of scope

* Other updates to schemas

## Tasks
- [x] Remove the timezone enum from our own validations (and rely on Lighthouse's instead).
- [ ] Talk to Lighthouse about division of responsibilities with respect to timezone enum updates on browsers.
- [ ] Reach out to this Veteran and prompt them to re-submit, and then track whether that re-submission succeeded (via Kimberley and DataDog).

## Definition of Ready 
- [x] Verified which version(s) of the schemas need to be updated (**Need to double check that HLR is using v1 vets-api endpoint)
- [x] Verified whether NOD v1 call is getting validated against an out-of-date timezone schema — it is not validating against any schema
- [x] ~Verified where to pull the list of timezones that Lighthouse references for their schemas (should be [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/config/schemas/decision_reviews/v2/200995.json#L51)) — confirmed in [Slack thread](https://dsva.slack.com/archives/CKUCFQAHJ/p1700608545186779?thread_ts=1698083531.827299&cid=CKUCFQAHJ)~ No longer necessary if we are removing the enum definition in these schemas entirely
- [x] Verified where `vets-json-schema` dependency needs to be updated (do we need to do anything to make sure `vets-api` pulls the updated schemas?)

## Definition of Done

- [ ] Tasks above complete.
- [ ] No more error logs about timezones

**Comment by Mottie** [comment]
You can get the most current list by using this JS:

```js
Intl.supportedValuesOf('timeZone')
```

But, I think it might be better to expect Lighthouse to keep their list up-to-date, so maybe in our schemas we remove the `enum` list and make it a required string value.

**Comment by anniebtran** [comment]
@Mottie Works for me, seems like the more maintainable route 🙃

**Comment by HeatherWidmont** [comment]
There is a PR out, but @anniebtran will sync with @Mottie about how to test

**Comment by anniebtran** [comment]
Tested the PR updates manually and it seems to work fine, so will work on getting that PR merged and everything updated accordingly

**Comment by anniebtran** [comment]
Following up on this task in the task list:

> Reach out to this Veteran and prompt them to re-submit, and then track whether that re-submission succeeded (via Kimberley and DataDog).

It looks like they have an AppealSubmission record for SC that was created on 11/22 (a day after the veteran ran into the error) and it has 3 AppealSubmissionUploads, all with `lighthouse_upload_id`s so I think the veteran was able to resolve it themselves 😄

**Comment by anniebtran** [comment]
Leaving one last update before I head out for time off — the only thing that remains here is to monitor for any other timezone errors in the logs. 

I don't anticipate we will see anymore _BUT_ if we do and it's from NOD (v1), it's likely because the schema validation there is happening in `vets-api` instead of `vets-json-schema` — the problem should _not_ occur in NOD v2 because that vets-json-schema is updated (and I don't think we validate the JSON response anyway, but I could be remembering incorrectly). Just something to be aware of if it somehow does pop up again. cc: @data-doge

**Comment by data-doge** [comment]
Thanks Annie! Let's close this ticket. If our logs show this error reoccuring, we can re-open.
