### ISSUE TITLE
GA4: Design System Meeting

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#70447]
## Issue Description

Meet with Design System team to discuss new property set up, web component status and next steps for both teams to complete set up.

---
## Tasks
- [x] Prepare for meeting (set up new property, document current status and next steps, etc)
- [x] Meet with team to review and answer questions, finalize action plan with expected delivery dates
- [x] Document take aways and begin next steps

## Acceptance Criteria
- [x] Met with Design System team and every one knows their next steps and deliverable dates
---
