### ISSUE TITLE
GA4: New Property Set UP

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#70446]
## Issue Description

We need to set up a new GA4 property for a cleaner/better set up migration.

---
## Tasks
- [ ] Create new property
- [ ] Test new property

## Acceptance Criteria
- [ ] New property has been configured
