### ISSUE TITLE
Update command path for #70343

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70444]
## Info
Content edits according to [content support ticket #70343](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70343)

## Tasks
- [x] Review support ticket 
- [x] Update the command path specified to the proper URL
- [x] Outline what additional changes could be made to provide more information about what YOUR_APP_URL should be.
- [x] Make content updates to the website accordingly.
- [x] Prepare page for deployment

## Acceptance Criteria
- [x] Platform website will be updated with the correct command URL, and additional information on the YOUR_APP_URL.

**Comment by johnny-jesensky-adhoc** [comment]
Lauren had some bandwidth, so pulling this into the current sprint today, Wednesday, November 29th.

**Comment by johnny-jesensky-adhoc** [comment]
This was completed and included in the deployment on 11/29. Moving this to _Done_.

FYI @laucon
