### ISSUE TITLE
MHV Support

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#70454]
## Issue Description

In support of the MHV team GA implementation we need to document what we have completed to date, blockers to current work and expected timelines to remaining work.

There is also an interest in a self service model, review options to support such work (if any) and prepare for meeting with Dave to discuss.

---
## Tasks
- [x] Review current MHV tickets
- [x] Document within each ticket what pieces have been completed and what we need from them in order to complete remaining tasks.
- [ ] Consider possible self service model options and document (if any) - how does GA4 play into this?
- [ ] Review current status and self service options  with Dave on 12/29

## Acceptance Criteria
- [ ] Met with Dave and we are aligned on next steps.
