### ISSUE TITLE
Resurrect Old Platform Support GitHub Board and Add New Optimal Workshop Data

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70468]
## Description 

Our [current DOMO dashboard](https://va-gov.domo.com/page/835197588?userId=17756940) will not allow us to pull in Optimal Workshop data into one view. As a result, we are resurrecting the old Platform Support Dashboard and will include [cards created by Basil](https://va-gov.domo.com/page/1729270793) on Platform Analytics sourcing data from our Platform Support VFS Survey Optimal Workshop results.

We have scheduled a call for the week of 11/27 to discuss logistics.

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Have call with Basil/Michelle to discuss logistics and scope of what is needed
- [x] Next Steps: Once the new form gets a submission Basil will work with the data sets more. If we can't merge them which is possible due to participant ID's potentially overlapping Basil will create copies of the cards made for the old survey and use the new dataset.
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by michelle-dooley** [comment]
Basil is working on this this sprint and will reach out as needed.
