### ISSUE TITLE
BQ - Cost Management & Governance

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#70469]
## Issue Description

As BQ costs continue to rise (even without the Mobile teams dashboard included) we need to review our queries and optimize for performance. We also need to create a governance plan/process for new teams to follow as they request access to BQ. 

[tracking sheet](https://docs.google.com/spreadsheets/d/1pI3ILk_UsZ7o_YHGHq8en-ImUJOXmUgFfPshLyXgSek/edit#gid=0)

---
## Tasks
- [x] Identify and list all queries by last run date and size
- [x] Review/audit queries run in the past month
- [ ] Determine if they are still needed or are they supporting a dataset no longer in use?
- [ ] For those still needed review for optimization opportunities (partitioning, less data fields, less joins, etc) 
- [ ] Optimized queries as applicable (if they are not owned by use work with owners)
- [ ] Create governance documentation to be posted on Confluence
