### ISSUE TITLE
Basil Training/Onboarding

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#70461]
## Issue Description

Items for Basil to review/complete as part of his training/onboarding

---
## Tasks
- [ ] GA - continue to shadow/assist Jamie as possible
- [ ] BQ - meet with Phil to go over data flow and BQ processes/connections, etc
- [x] Domo - assist Support Team as need with survey dashboard, work on [MyVA card redirects](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/70014), help Christine create Facility Locator cards
- [x] Get access to Adswerve and go through a form flow as a user and observe tracking events [21-526EZ Disability Compensation](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction)
- [x] Go through [team Confluence space](https://vfs.atlassian.net/wiki/spaces/AT/overview) - audit any links that may not be working, any instructions or documentation that may need updating, any questions that come, etc

## Acceptance Criteria
- [ ] Above steps completed as applicable.
---
