### ISSUE TITLE
[MVP] Setup DataDog alerts for both retry and queue exhaustion 

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#70462]
## User Story

As a Pension team preparing to relaunch the online form soon,
we need to revisit our logging and monitoring set up in Datadog and planned processes to identify error alerts,
so that we can

## Issue Description
- When a sidekiq retry happens we should see it in a custom log.  When queue exhaustion happens, we should be get alerted.

---
## Tasks
- [ ] Setup log for retries that happen in pension_benefit_intake_job.rb
- [ ] Setup alerting based upon this exhaustion in pension_benefit_intake_job.rb
```
sidekiq_retries_exhausted do |msg|
      Rails.logger.error('Lighthouse::PensionBenefitIntakeJob exhausted!',
                         { saved_claim_id: @saved_claim_id, error: msg })
    end
```

## Acceptance Criteria
- [ ] Log and alerts are created.
- [ ] Review with Steve Albers

**Comment by va-albers** [comment]
Thanks this is all good!  A couple of things I think we could add to this:
- Write out a custom metric (using statsd) for queue exhaustion
- Have a Datadog monitor that alerts for any cases of queue exhaustion
- Make sure that we have a plan for how to address cases of queue exhaustion (including resubmitting the request or if that is impossible letting the veteran know that the request wasn't completed)  Let me know if you want to discuss this part.

**Comment by buddhima-coforma** [comment]
Linking related prior ticket https://github.com/department-of-veterans-affairs/vets-api/pull/14467
