### ISSUE TITLE
Remove or Replace Content on Platform Content GitHub Page

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70479]
## Description 
This ticket will house the task of updating or removing the content on this page: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/platform-support

This is an ask from our PO Erika Washburn.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Alyssa to determine if we are removing or replacing this content with Erika
- [ ] Once identified, we will replace or remove this content
- [ ] Add next steps here
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Derailed by DORA metrics work. Will put in next sprint.

**Comment by alyssagallion** [comment]
Unable to verify with Erika until next week, OCTO on site. Pushing to next sprint.

**Comment by alyssagallion** [comment]
Updated the content on the page listed above to point to the Platform Site as the source of truth. It points to documentation to encourage people to read through it and the point of contact is in the documentation (incentive for reading it). See content in screenshot below. Closing!

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDdjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c2e1997755e6b6ae6a0753e31bb1824ae363f35/Screenshot%202024-05-14%20at%2010.03.51%20AM.png" alt="Screenshot 2024-05-14 at 10.03.51 AM.png" />
