### ISSUE TITLE
[Design] Create Final Wireframes for refresh component on appt list page within unified check in 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70483]
## Background

Over the last 30 days, ~11% of unique pageviews of /details/ (appointment list page) select the Refresh button (at least once) in check in. 

Implement decision from [design SPIKE](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70362)

Add to appt list artboards in Unified check in sketch file: Design Page and Priority 1 Page

[Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1700674909603239) to see if there's an existing component in the VA DS. 

Matt's [tertiary buttons ](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/p/8E62D47D-F38C-4727-8E27-B5DF3424F12F/canvas)that didn't get tested. [Slack thread about tertiary buttons](https://dsva.slack.com/archives/C01DBGX4P45/p1698694121477999). 

[Secondary button that VAOS uses](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Oeykn1R). 

## Tasks
- [x] Create final wireframes with content
- [ ] Create symbol
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [x] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [x] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske @loripusey , here is the selected wireframe with the secondary button (w/o inline icon) that we narrowed down during the DS office hour:
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/gmEMrM/a/mP00Mjz

**Comment by benbrasso-agile6** [comment]
@zach-park can you add it into Design Priority 1 appt list pages?

**Comment by benbrasso-agile6** [comment]
Or, just create an artboard showing just that component, and add it once to the Design Priority 1 page.

**Comment by zach-park** [comment]
> @zach-park can you add it into Design Priority 1 appt list pages?

The appointment list wireframes in the [design priority 1 page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas) is updated with the [Refresh apponimtnet].

**Comment by benbrasso-agile6** [comment]
Looks good, Zach. @loripusey you have a ticket for FE? Or did we just need to mention this to John in Slack?

**Comment by benbrasso-agile6** [comment]
So, in following the [tertiary button pattern that Appointments](https://www.figma.com/file/qm63ZVrjq6eohFpWnVqj7F/Add-Print-Button-to-Appt-List?type=design&node-id=1262%3A15151&mode=design&t=LdyGANW0ASK2e5NI-1) tested and I think is using in production, which [Matt had created in Sketch](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/v/vZaEMJ/p/0DF382A9-2B80-4782-A4EE-36A3CFB3A8D1/canvas?posX=-1637.908202479924&posY=-785.2936228417432&zoom=0.940777599811554), I think this option could work. What do you all think? @zach-park @cgednalske 

[Refresh feature in unified check in](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/C8E8D93A-E91D-4AC9-8ACC-95F9EA934A74/canvas#Version)

**Comment by benbrasso-agile6** [comment]
If ya'll do like it, please toss it in Slack for Brian to review. (We should try to show engineers stuff as early as we can, for the future.)

**Comment by cgednalske** [comment]
@benbrasso-agile6 are you aware of the discussion yesterday around the logic of how this would and wouldn't work for appointments and tasks? We'll need to discuss more with @brianseek and plan to use PLs in standups. 

There are questions around if and how we can have tasks refresh - either separately or with appointments - and that likely needs to be addressed first before we can confirm the UI. 👀

**Comment by cgednalske** [comment]
Some questions that might need clarification:

- When can/do tasks refresh?
- When can/do appointments refresh?
- Depending on the answer above, will we need to and can we include task refreshing with appointment refreshing?
- If not, do we need an action to refresh for tasks in addition to appointments?

**Comment by benbrasso-agile6** [comment]
Yes, I watched the sprit demo recording.

**Comment by benbrasso-agile6** [comment]
To do tasks are from VeText. Appts are from VAOS MAP service. Brian mentioned, like in production today, we can only update the status of the to do tasks from VeText. 

This is our implementation for now. In the future, we are hoping that we can have an implementation that isn't pulling and displaying appt info from two different sources. But, for the time being, that's how it needs to be.

**Comment by cgednalske** [comment]
Ok awesome! So then going back to your comment above, where are you referring to putting the tertiary button? Are you proposing that to address those questions?

**Comment by benbrasso-agile6** [comment]
I would keep the functionality the way it is today, where we're just looking for status updates to the VeText payload, eg, the to do tasks. Keeping it the same will help us get "something" into production quicker. Then, adjust thereafter if needed.

**Comment by cgednalske** [comment]
> To do tasks are from VeText. Appts are from VAOS MAP service. Brian mentioned, like in production today, we can only update the status of the to do tasks from VeText.
> 
> This is our implementation for now. In the future, we are hoping that we can have an implementation that isn't pulling and displaying appt info from two different sources. But, for the time being, that's how it needs to be.

Sounds good but can you clarify what the solution for now is? The refresh button Zach already had? I'm not clear where your comment about the other tertiary button came from.

**Comment by benbrasso-agile6** [comment]
Because priority 1 won't have actions and statuses on the upcoming appts (from VAOS MAP service), there's no need for a refresh feature on them, imo. Again, later, once we're pulling data from one place (for to do tasks from VeText and upcoming appts), our UI design might change. But, that's far down the road.

**Comment by cgednalske** [comment]
(re-commenting because I think we're overlapping our comments a little 🙃) 

Sounds good, but can you clarify what the solution for now is? The refresh button at the bottom of the list Zach already had? I'm not clear where your comment about the other tertiary button came from.

**Comment by benbrasso-agile6** [comment]
The functional change (from production to unified) that I realized for the engineers though is that if someone does refresh the to-do's in unified, we shouldn't include an appt from the past, like we do today in production. We'd only want to show future appts (from the VeText payload) in the to-do section. We'll want to add an annotation for this. And, will be curious to hear @brianseek thoughts, if he's following that train of thought. They may have already solved for this.

**Comment by benbrasso-agile6** [comment]
@cgednalske did you look at the sketch link I provided in my comment?

**Comment by cgednalske** [comment]
I looked at the links but was thrown off where all that was coming from. Ok, so then yes, we are trying to address the questions we had yesterday with a different UI. Gotcha 👍 

I'm a fan of using the tertiary button up there, though we should check placement (cc @zach-park) - might need to be below the cards and not inline with the header, though maybe it's ok. Also, is it ok to use the tertiary button in general? Wanting to confirm because VAOS is moving away from that and towards the secondary button in their redesign, and at office hours didn't they say to go with the button and not tertiary?

**Comment by benbrasso-agile6** [comment]
From all the conversations that I'm seeing, this would be an acceptable use case for the tertiary button (according to our convo with Matt yesterday). We will have to go through either midpoint or staging review (I forget if we've done midpoint for this work yet or not; I assume we'll go to staging review when engineers are done the Priority 1 work), so I feel like we should go with this UI solution and see how Matt reacts then :) (Of course, I agree, see what you and Zach think about the positioning. I would use the links I provided from Matt and VAOS as points of reference on what positioning will be acceptable.)

**Comment by cgednalske** [comment]
Circling back to respond to my own comment 😄  I think that solution works for now. I'll can throw a comment in the DS channel to double check those few things, but I say we go with it.

**Comment by benbrasso-agile6** [comment]
I added the different states of the button into our Symbols page too. Zach could clean them up if they need cleaning up.

**Comment by cgednalske** [comment]
@benbrasso-agile6 oh jinx! Sounds good 👍 
(I'm going to ask those questions mostly because of the possible accessibility concern with the placement above the things it's refreshing, but again, I think that sounds good!)

**Comment by benbrasso-agile6** [comment]
> I looked at the links but was thrown off where all that was coming from. 

I created it this morning because I had the idea last night :)

**Comment by benbrasso-agile6** [comment]
> @benbrasso-agile6 oh jinx! Sounds good 👍
(I'm going to ask those questions mostly because of the possible accessibility concern with the placement above the things it's refreshing, but again, I think that sounds good!)

Would also check with Peter, e.g., their Print button. Assume he ran that by a11y. E.g., they didn't place it at the bottom of their appt list page.

**Comment by benbrasso-agile6** [comment]
@zach-park I was chatting with Lori, and we should move forward with making that refresh all the check in statuses on the page, not just the top part of the page. 

<img width="1592" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0YwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12afd44f80d66c46430dba241433cebda50422cd/Screenshot%202023-12-19%20at%204.35.55%E2%80%AFPM.png" alt="Screenshot 2023-12-19 at 4.35.55 PM.png" />

**Comment by loripusey** [comment]
@benbrasso-agile6 talked to the engineers, they are going to discuss their refresh button ticket during their eng sync on thursday after Brian gets back
