### ISSUE TITLE
[DATA-LOAD] Associate all "LEBANON, PA" facilities-IDs to System using home page [Data Tech]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7049]
## User Story or Problem Statement
As a Veteran Web user, I want to see the local Faculties pages associated to the System, so that I can choose the best facility and options for my Health Care Journey.

## Goal
_Highlight the Individual FACILITY Pages per System_

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran traveling to each facility_
- _Reduce Click through count by_Highlighting top stories_

## Resources - Tools - Documentation
[VISN 4 System Playbooks and Facility Data](https://drive.google.com/drive/folders/126o9eJ4IRDAQb30So1LqE5tWV6T9lHkC)

## Tasks
_Complete load of data from spreadsheet to CMS related facilities listed below:_
- [ ] Lebanon VA Medical Center
- [ ] Berks County VA Clinic
- [ ] Cumberland County VA Clinic
- [ ] Landcaster County Va Clinic
- [ ] Schuylkill County VA Clinic
- [ ] Yourk VA Clinic
- * Spreadsheet will highlight the main areas of information, THAT MUST BE TRANSFERRED TO Facilities detail page

## Acceptance Criteria

*Confirm all facilities are linked by Facility ID and show up on Preview
