### ISSUE TITLE
[Design] [UX] Create User flow for filing a travel reimbursement claim for a past appointment

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70504]
## Description 

[Initial userflow with different health apps](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695774555765/73dec2c323f80ae6cb2a6e0a646221e2aeb680c4?sender=u37bb983bd3fc3cc00c7d3286)

[Userflow for VAOS](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/55601245-1C43-4A62-9DF8-2C830998B53E/canvas)

Example low-fi userflow: [Check in with travel and review page](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/0157CB5C-B33B-4324-B375-AC686EFA3B4A/canvas) 

Assumptions: 
- Allow Veterans to file a mileage-only claim for a Past Appointment. For example, receive an SMS the day after an appointment, request a LoROTA entry by replying, then receive a link back to file a claim for that visit. Veterans would have access to see their past appointments from the last 30 days, but only be able to file a reimbursement for the appt information provided from the VeText payload.
- Go navigate back to past appointments list, see the claim status for that appointment and other appointments, but can't file for other appointments. 
- Provide navigation to VAOS or BTS3 to file more claims for other appointments: https://www.va.gov/health-care/get-reimbursed-for-travel-pay/#file-a-claim-for-general-healt
- BTS3 API lag response time has been resolved. E.g., no need for f/u SMS messages. 

## Tasks
- [ ] Determine when this might engineering work might get implemented. I.e., to understand what Sketch file the design pages should live. (I think maybe use the Check In Sketch file first.) 
- [ ] Create low-fi userflow (or userflow options) for filing a travel claim the day after >1 in-person appointments at the same facility 
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Don't think this work will be our team's responsibility. Closing for now until we hear otherwise.
