### ISSUE TITLE
Jumpbox - Document Application

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#70502]
## Description
Document the updates made to SOCKS in the necessary areas: internal developer facing docs, external vfs-facing docs

---

## Tasks
- [x] Developer docs
  - [x] Draft developer docs
  - [x] Peer review developer docs
  - [x] Finalize developer docs and locate in the proper space on Confluence
- [x] Write user documentation
  - [x] Draft user docs
  - [x] Peer review user docs
  - [x] Finalize user docs & post to platform website

## Acceptance Criteria
- [x] JumpBox has been documented and peer-reviewed and posted to the proper locations

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/pso-tf-jumpbox/tree/prt-tf-aws-users
https://github.com/department-of-veterans-affairs/pso-tf-jumpbox/
