### ISSUE TITLE
Jumpbox - Test New Application Playbook

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#70501]
## Description
Conduct comprehensive testing of the rewritten playbook for JumpBox to ensure it meets all operational requirements and acceptance criteria.

---

## Tasks
- [ ] Create a test plan for JumpBox.
- [ ] Create detailed manual test cases that verify the JumpBox playbook functions as intended.
- [ ] Execute tests against the defined acceptance criteria.
- [ ] Document any issues and iterations made during testing.
- [ ] (Stretch) Explore the use of an appropriate automated testing framework to verify the infrastructure code.
- [ ] (Stretch) Write at least one automated test to incorporate into the test plan that verifies the infrastructure code for JumpBox.

## Acceptance Criteria
- [ ] All test cases for the JumpBox playbook are executed and passed.
- [ ] Documented evidence of successful tests and iterations.

**Comment by pjhill** [comment]
In order to derive some of the behaviors of the current jumpbox, we can look through the code that creates it.

Here's the Jenkins release pipeline  -- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/Jenkinsfiles/releases/jumpbox-vetsgov

There's a deployment pipeline for dev, staging, and prod Jumpbox instances.  [Here's dev](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jumpbox-vetsgov-dev.yml).
