### ISSUE TITLE
Jumpbox - Rollout New Application

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#70506]
## Description
Each Application that has been updated to the hardened AL2 image and now that new version needs to replace the old version. 

This ticket is intended to be a blank slate that reflects the steps necessary to roll out each app, since the steps involved will likely differ from one to another. Each app has an initial assessment that should define the steps of the rollout for that particular app, those steps should then be transferred to this ticket to be actioned when ready.

## Tasks
- [ ] Rollout steps defined in the assessment task have been transferred to this ticket
FROM ORIGINAL ROLLOUT:
- [ ] Turn off the pipeline creating the AL1-based jumpbox instance
- [ ] Turn on the creation of the hardened AL2-based jumpbox instance with the use of the old instance's IP address

## Acceptance Criteria
- [ ] Rollout tasks have been transferred here
- [ ] ROLLOUT AC HERE
