### ISSUE TITLE
[Research][Content] Create Content for SMS notifications 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70515]
## Description 

Similar to texting "check in" to 53079 that initiates the creation of a LoROTA entry, create the following text messages for: 

1) receiving a notification to file a claim by responding "xx"
2) the response with a unique url, and 
3) Similar to check in, ERROR_PHONE_NOT_FOUND = 'We don\'t have this phone number in our records. Try again using a mobile phone that\'s in our records. If you need more help, ask a staff member or call us. Find our phone number: https://www.va.gov/find-locations/'
4) Similar to check in, CHECK_IN_ERROR = 'We\'re sorry. We can\'t check you in online. Ask a staff member for help.'

## Tasks
- [ ] Create the content

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Closing for now. Think this will be Appointments team work.
