### ISSUE TITLE
Review Instances - Document Application

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#70559]
## Description
Document the updates made to Review Instances in the necessary

---

## Tasks
- [ ] Developer docs
  - [ ] Draft developer docs
  - [ ] Peer review developer docs
  - [ ] Finalize developer docs and locate in the proper space on Confluence
- [ ] Write user documentation
  - [ ] Draft user docs
  - [ ] Peer review user docs
  - [ ] Finalize user docs & post to platform website

## Acceptance Criteria
- [ ] Review Instances has been documented and peer-reviewed and posted to the proper locations
