### ISSUE TITLE
SOCKS- Rollout New Application

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#70567]
## Description
Each Socks and Jumphost that has been updated to the hardened AL2 image and now that new version needs to replace the old version. 

## Tasks
- [x] Update to most recent TF versions
- [ ] Apply new Gitlab Pipelines to repository
- [x] Enable sync of legacy pipeline repo
- [x] Deploy Dev and Prod environments

## Acceptance Criteria
 - [x] **Scenario: Update to most recent TF versions**
  - Given the current TF versions are outdated
  - When the TF versions are updated to the most recent versions
  - Then the new versions should be successfully installed and ready for use
- [ ] **Scenario: Apply new Gitlab Pipelines to repository**
  - Given the repository has no new pipelines applied
  - When new pipelines are applied using the updated TF versions
  - Then the new pipelines should be successfully applied and working as expected
- [x] **Scenario: Enable sync of legacy pipeline repo**
  - Given the legacy pipeline repo is not synced with the new pipeline repo
  - When the syncing process is enabled between both repos
  - Then both repos should be successfully synced and up-to-date with each other's changes
- [x] **Scenario: Deploy Dev and Prod environments**
  - Given the Dev and Prod environments have not been updated with the new application version
  - When the new application version is deployed to both environments
  - Then both environments should be successfully updated with the new version and running as expected

**Comment by ben-allen-oddball** [comment]
After feedback converted deployment to serverless fargate.  Everything worked accept for fail2ban was not able to filter correctly because of the NLB was masking the true IP.  Attempted to configure OpenSSHD to accept the proxy protocol but was not possible.  Reverted configuration to the EC2 based deploy.

**Comment by JoeTice** [comment]
Still some follow-up cleanup work happening next sprint, but the main focus of this is completed
