### ISSUE TITLE
DR | Update form submission error

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#70581]
## Value Statement
**_As a_** Veteran attempting to submit a Decision Review on VA.gov
**_I want to_** see consistent error messaging when my submission fails
**_So that_** I have the same up-to-date instructions available across all forms. 

---
## Background Context
- As part of our document front/backend interactions (#[67648](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67648)), we discovered that there are mismatched error messages between the three decision review forms for form submission. The error style has been updated for Supplemental Claims, but not for NOD and HLR.

The phone number should also be updated to Benefits hotline for more direct help.

<details>
<summary> Current form submission error message on NOD / HLR</summary>

![current NOD and HLR error message](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b44ca55eb1d394f1016dc8580130e033a4b3e34/image.png)
</details>

## Acceptance Criteria
- [ ] When there is an error for form submission on NOD, it shows the v3 styled error alert with content from design and build notes.
- [ ] When there is an error for form submission on HLR, it shows the v3 styled error alert with content from design and build notes.
- [ ] When there is an error for form submission on SC, it shows the v3 styled error alert with content from design and build notes.

## Designs and Build Notes
Error alert:
Header: Your decision review request didn't go through
Body: We're sorry. We're working to fix the problem, but it may take us a while. Your request has been saved. We suggest you try submitting again tomorrow.
If you're still having trouble submitting your request, call us at 1-800-827-1000 (TTY:711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. Your in-progress ID is ID number.

[FIGMA](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1187-14587&m=dev)

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] 
- [ ] 

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@eileen-coforma:

- Confirm if the help number displayed is accurate
- Post an updated design reflecting v3 components
- Doublecheck AC

**Comment by eileen-coforma** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80680

**Comment by saderagsdale** [comment]
Waiting for feedback from Julie on content. (@eileen-coforma will reach out)

**Comment by eileen-coforma** [comment]
Confirmed the phone number should be the Benefits hotline.
Confirming language with Julie, after looking at platform guidance.
Our forms have a limitation where we can't put alert messages above headers, so our alerts are below the accordions.

**Comment by Mottie** [comment]
Changes have been merged, but are not yet available in staging. To duplicate these error messages for validation, follow these steps:
- Navigate to the review & submit page
- Open the dev tools (<kbd>F12</kbd> or right click & inspec)
- Go to the `Application` tab
- Find & select `Local storage` > `https://staging.va.gov`
- In the right panel, find `csrfToken`
- Change the value. I usually just add an `1` at the beginning
- Submit the form

**Comment by Mottie** [comment]
We can validate this in parking lot next week

**Comment by shaunburdick** [comment]
Validated with @skylerschain in parking lot
