### ISSUE TITLE
NOD | Audit evidence upload parity between S3 and Lighthouse

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#70584]
## Value Statement

**_As an_** engineer
**_I want to_** verify that the number of S3 evidence uploads on the NOD form are proportional to the number of Lighthouse uploads, and be able to dismiss any discrepancies as expected.
**_So that_** I know that the evidence upload to Lighthouse process in the NOD form is working as expected.

---
## Background Context

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/69546 we fixed our NOD logging to properly distinguish between NOD and SC evidence uploads.  That means that we can now evaluate whether our S3 evidence uploads are proportional to our Lighthouse uploads.  Our evidence upload process is probably in great shape, but it would be good to verify that.

We've verified that such parity exists in production, with NOD v1 (i.e. feature toggle turned OFF). We've also verified that such parity exists in staging, with NOD v2 (i.e. feature toggle turned ON). 

When we re-release NOD v2 in production (i.e. turn the feature toggle ON), we should monitor our NOD Dashboard, daily, to ensure that such parity continues.

By parity, I mean that for each set of S3 uploads for a Veteran, there exists a corresponding set of Lighthouse evidence uploads. The size of each set need not be identical, since Veterans have the ability to delete uploaded files before submitting the NOD form.

## Tasks

- [ ] Check NOD dashboard, daily, for a week, and confirm parity (defined above).

## Acceptance Criteria

- [ ] Parity (defined above) exists for all NOD v2 submissions, for a week after turning feature toggle on.

## Definition of Ready 

- [ ] NOD v2 feature toggle turned ON.

## Definition of Done

- [ ] Acceptance criteria met.

**Comment by saderagsdale** [comment]
@data-doge cc @anniebtran (for Tuesday) iIs this still valuable, or potentially necessary for re-releasing the NOD form?

**Comment by data-doge** [comment]
@saderagsdale we can just fold this ticket into https://github.com/department-of-veterans-affairs/va.gov-team/issues/64642, or whatever other ticket we want to use to represent work on the NOD v2 re-launch. If that sounds good to you, we can close this ticket.

**Comment by saderagsdale** [comment]
Covered already.
