### ISSUE TITLE
DR | Set dynamic `env`s for our DR DataDog dashboards

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#70586]
## Value Statement

**_As an_** engineer
**_I want to_** have the `env` in our DR DataDog dashboards be dynamic, and not hardcoded to prod
**_So that_** I can test our lower environments as well as our prod environment.

---
## Background Context

In most of our DR DataDog Dashboard widgets, we are using a dynamic `$env` filter which allows us to toggle between production and staging environments. But some widgets are still hardcoded to look at our production environment only. We want all widgets (BUT NOT ALERTS) to be using the dynamic $env filter.

## Tasks

- [ ] Go through all DR DataDog Dashboard widgets and ensure we're using a dynamic $env filter.

## Acceptance Criteria

- [ ] All DR Dashboard widgets are using a dynamic $env filter.

## Definition of Ready 

N/A. Ready now.

## Definition of Done

- [ ] Acceptance criteria met.

**Comment by saderagsdale** [comment]
Aimed at improving our testing efforts in staging.

**Comment by saderagsdale** [comment]
Moving to S43 as an urgent but non-critical item given capacity. We can move it back up if needed.

**Comment by HeatherWidmont** [comment]
@Mottie to review a couple of things with @anniebtran & @data-doge in the parking lot today

**Comment by HeatherWidmont** [comment]
Reviewed most of it, but still need to review a bit more. @Mottie & @data-doge to review the rest in tomorrow's parking lot

**Comment by data-doge** [comment]
Validated today. Looks great.
