### ISSUE TITLE
DR | Audit error handling/logging in vets-api interactions with external services (i.e. Lighthouse)

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#70582]
## Value Statement

**_As a_** product team member
**_I want to_** have comprehensive error handling/logging for backend interactions with external services like Lighthouse
**_So that_** I can more easily trace/find where errors and bugs are coming from

---
## Background Context
This work follows the FE/BE interaction work done further up in the stack for this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/67648 as a part of an effort to have a deeper understanding of all the moving parts in our forms so that we can identify any gaps in functionality and error logging/monitoring, as well as improve knowledge sharing amongst the team.

## Tasks
- [ ] Confirm all documentation for backend APIs and services that are currently involved in our form saving/submission process are currently accurate
  - [ ] [HLR eng documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/higher-level-review/engineering)
  - [ ] [Supplemental Claims eng documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims/engineering)
  - [ ] [NOD eng documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement/engineering)
- [ ] Update documentation as needed
- [ ] Audit the error handling and logging in those APIs/services to understand what kind of errors we may encounter in our monitoring systems
- [ ] Add or update any error handling or logging as needed
- [ ] Figure out where to make eng documentation more visible for new and older team members to more easily reference

## Acceptance Criteria
- [ ] All tasks complete

## Definition of Ready 
- [ ] We've identified if existing backend documentation is accurate or not
- [ ] We've figured out where it would be most useful to have links to this documentation for knowledge transfer/sharing

## Definition of Done
- [ ] Acceptance criteria met
- [ ] Links to documentation are more handy for folks who are onboarding or looking at errors
