### ISSUE TITLE
Explore Calendly-to-Slack webhook integration

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#70583]
## User Story
As a Governance team member, I want to explore the Calendly-to-Slack webhook integration so that I can determine if it is a good fit for addressing our Slack notification workflow challenges.

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
In ticket #69401, Governance team explored options for improving the notification workflow. We liked the idea of an integration between Calendly and Slack as it asks VFS teams to only complete 1 step (opposed to 2) and allows Governance team to still have the benefits of a Slack thread on the teams Slack channel.

The purpose of this ticket is the dig deeper into the Calendly-to-Slack webhook integration. Resources include [Getting started with webhooks ](https://help.calendly.com/hc/en-us/articles/223195488-Getting-started-with-webhooks)and [Create workflows that start with a webhook.](https://slack.com/help/articles/360041352714-Create-workflows-that-start-with-a-webhook)

This ticket may potentially explore how we can automate updating calendar invite for title, distribution list, zoom info, CC request # and Slack thread (Design Intent, Midpoint, Staging).

## Tasks
- [x] Create a new document in the [Ideas](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1991278596/Ideas) folder in the Governance team space for documenting 
   -  [x] Let's move the[ Potential solutions ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833220014/69401+-+Research+opportunities+for+improving+notification+workflow#Calendly-to-Slack-webhook-integration)doc over the Ideas folder as well.  Trying to get in the habit of keeping draft guidance and artifacts in one folder (AKA documentation docs), and have discovery work, etc. elsewhere. 
- [x] Explore the logistics of setting up the Calendly webhook integration
   - Do we need admin permission via Slack? 
      - **Answer:** No!
   - Is our existing Calendly account sufficient? 
      - **Answer:** Yes!
   - What other challenges might we encounter? 
      - **Answer:** Two big challenges emerging are...
         - Is the data coming out of Calendly structured in a way that Slack can display it in workflow messages?
         - Can we pre-populate a list of Slack channels for VFS PMs to choose from in Calendly, so they can select their public channel to kick off the workflow?
- [ ] Identify the impact to VFS facing services:
   - Calendly?
   - Collab Cycle req gh ticket?
   - touchpoint pages on PW?
 - [ ] Identify the impact to Governance operational processes.
- [ ] Decide whether or not this solution is feasible. Feel free to consult with other Governance team members. Please share your findings at the Weekly Initiative Meeting. 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have determined whether or not the Calendly-to-Slack webhook integration is a valid solution for our notification workflow challenges.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Work will be continuing into the next sprint. Current status:
- Successfully getting data from Calendly's webhook subscription.
- Successfully triggering a workflow in Slack. 

What's not totally clear is if I can get the data from Calendly (meeting attendee name, email, answers to questions) to come through in a way that Slack likes and will display in the message. Should have some answers there soon-ish, which will inform how this can proceed.

**Comment by briandeconinck** [comment]
Expanding on my notes from yesterday, and pinging @shiragoodman and @it-harrison for thoughts on whether/how to move forward here...

As noted above, I'm successfully getting data from Calendly and the data from Calendly is successfully triggering a workflow in Slack. The issue is parsing the Calendly data (name of the person who started the touchpoint, their answers to any questions we ask on the scheduling form, their public Slack channel name) into something that can be used to build the messages posted by the workflow in Slack.

The [Calendly webhook payload](https://calendly.stoplight.io/docs/api-docs/69c58da556b61-webhook-payload) is **nested JSON** structured roughly as follows (removed the extra metadata we don't care about):

```
{
   "event": "invitee.created",
   "payload":{
        "email":"brian.deconinck@adhocteam.us",
        "name":"Brian DeConinck",
        "questions_and_answers":[
            {
                "answer":"Some answer",
                "position":0,
                "question":"Some question?"
                },
            {
                "answer":"Some other answer",
                "position":1,
                "question":"Some other question?"
                },
            {
                "answer":"Yet another answer",
                "position":2,
                "question":"Yet another question?"
            }
        ],
    }
}
```

When Slack workflows are triggered by a webhook, they can only parse **flat JSON** --- confirmed today by Slack support. So that means for this to work the response from the Calendly API would have to be something more like:
```
{
   "event": "invitee.created",
   "email":"brian.deconinck@adhocteam.us",
   "name":"Brian DeConinck",
   "answer_0":"Some answer",
   "answer_1":"Some other answer",
   "answer_2":"Yet another answer",
}
```

No way to get Calendly to re-structure its data, no way to get Slack to parse nested JSON.

So I think that leaves two options here:
1. Give up!
2. Set up some intermediate app that receives the Calendly nested JSON, flattens it, and then passes it along to Slack to start the workflow.

(2) above is where I'm looking at @it-harrison for feasibility. It doesn't seem like it should be hard to do this, and there may even be third-party services like Zapier that could do it for us. But I'm not sure if it's actually worth the effort.

Note that there's another separate challenge still unresolved: If we want the workflow to post messages in the VFS team's public channel, then the VFS PM will have to provide their channel in Calendly. But the Slack workflow would be looking for the channel ID (eg. `GNF5GSD9N`) in the webhook payload and not the human-friendly name (`platform-governance-team`). So either VFS PMs would need to be trained to find and provide their channel ID, or we would have to have some thing (*waves hands*) that matches whatever they provide to a list of channel IDs.

So that's where we stand here. Very interested in everyone's thoughts!

**Comment by shiragoodman** [comment]
Thank you @briandeconinck for doing so much research with Calendly and Slack. I'm sure you're a bit disappointed that the solution isn't easier to implement. I'll wait for Ian to chime in with his thoughts on a potential intermediate app, however once he does, I'd still like to regroup and discuss our options... even going back and reviewing the [Research opportunities for improving notification workflow](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833220014/69401+-+Research+opportunities+for+improving+notification+workflow) suggestions that you and @rferguson13 put together. I'm still confident that there's an improvement we can make to the current workflow, I think we just might need to look at it from a different perspective.

**Comment by shiragoodman** [comment]
@briandeconinck can you please schedule a 30 minute meeting later this week with the full team to discuss the [potential solutions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833220014/69401+-+Research+opportunities+for+improving+notification+workflow#Calendly-to-Slack-webhook-integration) that were originally proposed?

**Comment by briandeconinck** [comment]
Update: Governance team met on 1/10 to discuss options. Decided to wait on upcoming changes to our Design Intent processes, track how often teams struggle with the two-step scheduling, and then reassess. Closing this ticket.

**Comment by shiragoodman** [comment]
[Tracking document ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2906750986/Calendly+Slack+schedule+tracking)for future reference.
