### ISSUE TITLE
5 Digit in street address interpreted as zip code 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7059]
## What happened?
If street number is 5 digits, it is used as zip code for searching

## Tasks
- [ ] Send address field in " in query

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Turns out we have already been handling this appropriately. 
See https://github.com/department-of-veterans-affairs/vets api/blob/master/lib/facilities/ppms/client.rb#L174

May need to be handled by PPMS or may be resolved by moving to sending lat/long parameters as part of
