### ISSUE TITLE
Run/Test Sentry 9.1.2 Locally

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#7060]
## User Story or Problem Statement

As a developer on VSP I need to test and verify changes to Sentry configuration so that we can confidently upgrade our current Sentry version (9.1.1) to 9.1.2 (before upgrading to 10.0.0).

Local testing is needed to verify that there are no obvious issues and to understand any migration requirements more thoroughly before upgrading in production environment.

## Objectives or Key Results this is meant to further

- Stability of the platform's systems will improve by modernizing tools, and normalizing upgrade path (O3)

## Tasks
- [ ] Set version to `9.1.2` in relevant configuration files and post-deploy commands
- [ ] Read changelog to catch any major issues to be aware of
- [ ] Provision local vagrant playbook according to [documentation](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/README.md#runningtesting-sentry-locally) (see #6992)

## Acceptance Criteria
- [ ] Local Sentry stack accepts messages and otherwise behaves as expected
- [ ] Pull request is opened including Sentry 9.1.2 upgrade configuration

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
v 9.1.2 up and running locally with queued message successfully sent to Sentry

**Comment by LindseySaari** [comment]
Testing 9.1.1 => 9.1.2 upgrade locally through vagrant workflow
