### ISSUE TITLE
Deploy Sentry 9.1.2 to Production

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#7061]
## User Story or Problem Statement

As an engineer on VSP I need the latest 9.1.x release of Sentry so I can confidently upgrade to 10.0.0.

## Goal

sentry.vfs.va.gov points to latest 9.1.x version in preparation for 10.0.0 upgrade

## Objectives or Key Results this is meant to further

- Stability of the platform's systems will improve by modernizing tools, and normalizing upgrade path (O3)

## Tasks
- [ ] Coordinate with operations team to approve changes
- [ ] Merge the changes into `master` 
- [ ] Trigger a build job in [Jenkins](http://jenkins.vfs.va.gov/job/builds/job/sentry/)
- [ ] Verify the upgrade is complete by checking sentry.vfs.va.gov version information
- [ ] Communicate any impact to ALCON

## Acceptance Criteria
- [ ] [Sentry](http://sentry.vfs.va.gov) points to 9.1.2 running instance
- [ ] Error capture is unaffected

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnpaulashenfelter** [comment]
@kfrz @LindseySaari i think you should consider whether its worth two production changes, especially since v10 is so different from v9 (specifically the whole Kafka & Zookeeper). Not sure the effort is worth it unless there's a *really* clear migration path that gets better with the interim update.

**Comment by kfrz** [comment]
@johnpaulashenfelter at first I agreed but after some more understanding of the playbooks, I believe we'd have to modify/copy the entire pipeline including the build and deploy jobs and adding new AWS resources. @omgitsbillryan might be better suited to answer the question "What's required to spin up a side-by-side comparison of Sentry 10 w/ our existing stack?" 

We'll be diving into the 10.0.0 upgrade locally next week and start to see what problems arise specifically. We will also need to do some analysis of resource allocation, which I've reflected in the relevant [issue body](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/7062) along with some other thoughts in that thread.

**Comment by LindseySaari** [comment]
[Sentry 10 Infra Approach Slack Thread](https://dsva.slack.com/archives/CJYRZK2HH/p1585063979460800)
