### ISSUE TITLE
Configure Support Bot Local Test Environment

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#70615]
## Issue Description
In order to test the support bot changes, a local environment will need to be set up. This will involve creating a separate slack space, creating a slack application for it, and then configuring all relevant environmental variables. 

---
## Tasks
- [ ] Set up support bot testing environment.
- [ ] Test changes to ensure they're reflected.

## Acceptance Criteria
- [ ] A way to test upcoming feature improvements to the support bot exists.
---

**Comment by CBonade** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78d94e38af87c0c0fc467048c8e12eea9f903564/image.png)


All set in my own slack workspace
