### ISSUE TITLE
Run/Test Sentry 10.0.X Locally

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#7062]
## User Story or Problem Statement

As an engineer on VSP I need to test and verify changes to Sentry configuration so that we can confidently upgrade to Sentry 10.0.0.

Local testing is needed to work through new configuration issues and to understand any migration requirements more thoroughly before upgrading in production environment.

## Useful links

https://github.com/getsentry/onpremise#updating-sentry
https://forum.sentry.io/c/on-premise/7
https://docs.sentry.io/server/installation/
https://github.com/getsentry/onpremise

## Goal
Sentry 10.0.0 deployment upgrade plan is wholly understood and roadmapped.

## Objectives or Key Results this is meant to further

- Stability of the platform's systems will improve by modernizing tools, and normalizing upgrade path (O3)

## Tasks

- [ ] Determine if we can use docker-compose directly or how best to adapt it to our environments
- [ ] Carefully read changelog and understand significant changes
- [ ] Carefully update [this documentation](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/sentry#architecture) about Sentry's architecture
- [ ] Determine best structure for any new resources needing allocation
- [ ] Modify existing resource Terraform scripts to describe new/updated resources
- [ ] Update runbooks to use new configuration templates
- [ ] Write new roles and runbooks as needed to reflect new dependencies, leveraging onpremise docker-compose
- [ ] Follow upgrade instructions where appropriate and document any pain points or obstacles thoroughly
- [ ] Consult with operations engineer(s) and determine if approach is sound.

## Acceptance Criteria

- [ ] Local Sentry stack accepts messages and otherwise behaves as expected
- [ ] Pull request is opened including Sentry 10.0.0 upgrade configuration

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
Even with upgrade scripts we will want to think about separating the container infrastructure into further separate components and any potential ripple considerations this might have.

The new [docker-compose.yml](https://github.com/getsentry/onpremise/blob/master/docker-compose.yml) looks to include a couple more layers than we're providing for.

```yaml
version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-sentry-defaults: &sentry_defaults
  << : *restart_policy
  build:
    context: ./sentry
    args:
      - SENTRY_IMAGE
  image: sentry-onpremise-local
  depends_on:
    - redis
    - postgres
    - memcached
    - smtp
    - snuba-api
    - snuba-consumer
    - snuba-replacer
    - symbolicator
    - kafka
```

In fact, I'm not sure we're even able to use a docker-compose workflow for deploying to our infrastructure (or if we'd want to). @omgitsbillryan thoughts? 

New major components and dependencies:

- [Snuba](https://blog.sentry.io/2019/05/16/introducing-snuba-sentrys-new-search-infrastructure) for event queue data, Docker. Includes three components (api, consumer, replacer).
- Clickhouse <does what?> via Dockerfile
- Kafka <does what?> via Dockerfile
- Zookeeper <does what?> via Dockerfile
- Symbolicator

A few other utility-tier Docker containers are spun up with the [compose file](https://github.com/getsentry/onpremise/blob/master/docker-compose.yml). 

This will require some careful consideration and architecture of new ASG and constructing appropriate roles/policies/resources.

I am beginning to think it's a great idea to start "fresh" and ensure we consult with the operations crew to make sure our approach is solid and progressive.

**Comment by LindseySaari** [comment]
Description of some of the major components and dependencies found [here](https://blog.sentry.io/2019/05/16/introducing-snuba-sentrys-new-search-infrastructure)
