### ISSUE TITLE
[Evidence Service to Lighthouse] Test implementation in staging

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#70639]
## Background
Once we have a working implementation available in staging, we should check that this works the way that we expect it to and that we are able to upload all of the supported file types. We should also verify that uploading password protected files works as expected

## Considerations
File types we support: `pdf, gif, jpeg, jpg, bmp, txt`
We also support encrypted PDFs. You should be prompted to enter a password on the FE. **NOTE:** There is a known issue with PDFs that use AES-256 encryption and is out of scope for this issue

## Tasks
- [x] Verify that all file types that are supported upload as expected
- [x] Verify that password protected PDFs can be uploaded

## Acceptance Criteria
- [x] We are confident that Veterans will be able to upload all of the file types that we tell them we support
- [x] Password-protected PDFs are decrypted properly

**Comment by jerekshoe** [comment]
**Update (12/7):** Tested with all of the file types listed above and with a password protected PDF. From what I can tell everything is working as expected
