### ISSUE TITLE
FE | My VA | Remove '/resuming' from Applications In Progress or Remove whole section of My VA during downtime

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#70646]
## Issue Description
Robin brought up the problem in this slack support thread:
https://dsva.slack.com/archives/CBU0KDSB1/p1700492838678679

Existing forms-system ticket is: https://github.com/department-of-veterans-affairs/va.gov-team/issues/70251

My Va should either check for a downtime flag and remove the `/resume` from the url to a form in progress, or hide the Applications in Progress section of the page altogether to prevent users from resuming applications when the dependent services are down.

This wasn't accounted for because the `/resume` url being present will cause the form system to enter directly into the form flow and bypass the introduction page altogether, which was responsible for showing downtime and gating a form. 

Fixing this on My VA is a bit more of a bandaid fix as the route will still be directly accessible, and _could_ be saved or bookmarked by a users and then manually visited in rare cases. Regardless of the route being available though, we should fix My VA and decide if the section should just be gated off during downtime.

## Tasks
- Decide on whether to gate whole section or remove `/resume` from forms in progress urls
- Implement solution
- Follow up on the related form system ticket

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass
