### ISSUE TITLE
Sentry 10 Upgrade

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#7064]
## User Story or Problem Statement

As an engineer on VSP I need the current Sentry version 10.0 in production so I can leverage the nifty new features.

## Goal

On-premise Sentry is upgraded to latest release

## Objectives or Key Results this is meant to further

* Stability of the platform's systems will improve by modernizing tools, and normalizing upgrade path (O3)

## Tasks

- [ ] Verify configuration is working as expected by spinning up a sandbox env if possible
- [ ] Update any values needed in Credstash
- [ ] Upgrade Postgres RDS instance to at least 10 (might be done already at this point)
- [ ] Verify any significant changes are in place if needed?
- [ ] Collaborate with operations to merge changes into master
- [ ] Trigger build job in Jenkins
- [ ] Verify upgrade is complete by checking Sentry UI after deploy
- [ ] Communicate all changes to ALCON

## Acceptance Criteria

- [ ] Sentry points to 10.0.0 running instance cluster
- [ ] Error capture and platform performance/stability is unaffected

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnpaulashenfelter** [comment]
@alexpappasoddball @ricetj what are the next steps here? Seems like the current status is moving it to the Icebox and/or a future epic?

**Comment by alexpappasoddball** [comment]
moving to backlog

**Comment by alexpappasoddball** [comment]
@omgitsbillryan @kfrz @LindseySaari The direction for this has changed and we are going to pick this back up in Sprint 25.  Lets chat about the plan on how best to track this.  @ricetj we might need some assistance from Ops on this one!

**Comment by alexpappasoddball** [comment]
As discussed in sprint planning today, @omgitsbillryan is going to break this ticket out into more granular tasks now that we have a good idea of the steps necessary to upgrade Sentry to V10.  Let me know if you need any help Bill.
