### ISSUE TITLE
Outline feedback mechanisms for Service Design Team

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70647]
## Description: 
The Service Design Team is currently taking action on [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60558). After meeting with Dan Turner, this ticket is to help map out some findings from the research that was performed over the summer.

## Tasks:

- [ ] Document out user stories from IA findings, and opportunities around feedback collection on the Platform Website.
- [x] List out all methods of feedback entry, with root problem we are trying to solve for.

- [x]  Connect with Dan Turner on findings.
- [ ]  Outline next steps.

## Acceptance Criteria:
- [ ] IA research has been summarized in support of feedback mechanisms on Mural board.
- [ ] Meeting with Dan Turner to summarize findings.

**Comment by jknipes** [comment]
Service Design team has been dissolved. We will address IA using more current feedback. Keeping this in Icebox for now.

**Comment by jknipes** [comment]
IA concerns will be addressed in separate tickets. Closing this issue.
