### ISSUE TITLE
[UX] SPIKE: Identify Veteran pain points across updated PCI Service Blueprint 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70658]
## Tasks
- [ ] Review the PCI Service Blueprint on your own before the UX team meets
- [ ] From the updated PCI Service Blueprint that expands the PCI ecosystem for Veterans, including filing a travel reimbursement claim for a past appointment and filing a travel reimbursement claim during eCheck-in, identify potential Veteran pain/friction points (which might inform future research studies with Veterans). 
- [ ] Draft initial list of questions we want answered from a research study with Veterans to address pain points. 
- [ ] Add as a future research study to the Priorities board, if multiple pain points have been identified that can be researched. 

## Acceptance Criteria
- [ ] Veteran pain/friction points have been identified 
- [ ] Initial list of questions have been drafted that we want answered from a research study with Veterans to address pain points. 
- [ ] Add as a future research study to the Priorities board, if multiple pain points have been identified that can be researched.

**Comment by benbrasso-agile6** [comment]
Closing for now. Think this will be Appointments team work.
