### ISSUE TITLE
[Design] Switch body and links to v3 in Production file and Unified Check In file on Design Page (and symbols)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70661]
## Tasks
- [x] Switch body and links to v3 in Production file and Unified Check In file on Design Page (and symbols)
- [x] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske , the Unified and Production sketch files are ready for validation now. Thank you.

**Comment by benbrasso-agile6** [comment]
thanks, will take a look

**Comment by benbrasso-agile6** [comment]
Left comment here to check out: https://sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/oMbG8dD?annotation=09d86d74-d91b-4009-821d-af2ebdbc8010

**Comment by zach-park** [comment]
Check-in production file is updated and ready to be validated. Also double-checked the Unified sketch file and it looked good.

**Comment by benbrasso-agile6** [comment]
Production looks good, will look at unified shortly
