### ISSUE TITLE
[REVIEW] Internal Review, test, and scan all pages for "LEBANON, PA" System and facility pages in Devshop [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7068]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing, review, initial Accessibility scan with AXE-Coconut _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Chrome AXE-Coconut](https://chrome.google.com/webstore/detail/axe-coconut-web-accessibi/iobddmbdndbbbfjopjdgadphaoihpojp/related?hl=en)
[Chrome AXE](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd/related?hl=en-US)

## Tasks
_Complete review of system and facility pages, first manual review and testing of links and then AXE test:_
- [ ] Lebanon VA Medical Center
- [ ] Berks County VA Clinic
- [ ] Cumberland County VA Clinic
- [ ] Landcaster County Va Clinic
- [ ] Schuylkill County VA Clinic
- [ ] Yourk VA Clinic
- * Document all errors, items that need update and testing on each page using spreadsheet listed above_

## Acceptance Criteria
* All pages must have been documented in Spreadsheet
* AXE testing must be screenshot and loaded into Spreadsheet for Accessibility and 508 teams
