### ISSUE TITLE
SPIKE | Burial | Missing Identify Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70689]
## Issue Description
_150 Burial claims within the last 60 days were missing identify information and had no Central Mail GUID, which could mean that the claims were never sent to CMP. We need to determine:_

---
## Tasks
- [x] Confirm what happened. Example: Did we fail to retrieve an identity and then never send them to CMP in the first place?
- [x] Determine how to fix it
- [x] Determine if it was a silent failure. Example: Did the veteran receive any front-end notification or email or any signal of a problem?
- [x] Determine if the submissions can be re-generated for re-submission

## Acceptance Criteria
- [x] Answers to above questions
- [ ] Follow on tickets created
---

**Comment by micahaspyr** [comment]
I pulled some claims from the burial spreadsheet where the participant_id column show an 'Error'.   

I then searched by state of Burial claims that had a central mail submission numbers below.

failed: 84 (last_seen 11-30-2023)

The majority of these errors in Sentry show "Metadata Field Error - Invalid character(s) detected"
A small amount show "Document already uploaded with uuid [xxxxx]"
Lastly the "Intake API is undergoing maintenance" aka service is unavailable

**Comment by micahaspyr** [comment]
1.  Metadata Field Error - Invalid character(s) detected is causing the issue
2. Not sure as I need to be able to see the metadata sent with the claim
3. The failure is SILENT and the vet is not notified of the issue, but the submission is marked as a failure.
4. The submissions can not be retried with the metadata error as it fails outright, meaning a retry is just going to be using the same data and will subsequently fail

**Comment by micahaspyr** [comment]
I provided Emily Theis from the VA with some up to date failure info that includes the guid/uuid for those burial claims that were in a failed state (something that was missing in the prior csv generated file).  Will update when I get more info

**Comment by micahaspyr** [comment]
The regex for the first and last name of the Veteran attached to the burial claim looks to reject characters such as periods and the squiggly single quote.  We have the regex for the current EMMS API interface but it will change when we move to using Benefits Intake API. Regexes are for names below

EMMS API (current): ^[A-Za-z'/ -]+$
Benefits Intake API: ^[a-zA-Z\-\/\s]{1,50}$

**Comment by micahaspyr** [comment]
47 Burial claims have been identified as potentially retryable.  Was told to hold off by Emily before we decide to run these again.
