### ISSUE TITLE
SPIKE | Scope Burial PDF Mapping

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70685]
## Issue Description
We need to understand the effort and work needed to map the new Burial form questions to the PDF that is generated when the online claim is submitted and that VSRs subsequently use to process claims.

Fiorella compiled the following references:
- [530-Fields-to-be-deleted.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13531721/530-Fields-to-be-deleted.xlsx)
- [527_530 va.gov differences.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13531722/527_530.va.gov.differences.xlsx)
- The new version of the PDF is [here](https://www.vba.va.gov/pubs/forms/VBA-21P-530EZ-ARE.pdf).

---
## Tasks
- [ ] Investigate how to map the new online form questions found on the document provided above to the new version of the PDF form
- [ ] Identify any information still missing in order to understand the level of effort
- [ ] Estimate a level of effort 
- [ ] Share findings with technical lead, product manager and VA stakeholders when necessary

## Acceptance Criteria
- [ ] We will have a better sense on the level of effort to map the new questions on the online Burial form to the new PDF version of the form.
