### ISSUE TITLE
SPIKE | Pension | Missing Identify Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70690]
## Issue Description
_44 Pension claims within the last 60 days were missing identify information and had no Central Mail GUID, which could mean that the claims were never sent to CMP. We need to determine:_

---
## Tasks
- [ ] Confirm what happened. Example: Did we fail to retrieve an identity and then never send them to CMP in the first place?
- [ ] Determine how to fix it
- [ ] Determine if it was a silent failure. Example: Did the veteran receive any front-end notification or email or any signal of a problem?
- [ ] Determine if the submissions can be re-generated for re-submission

## Acceptance Criteria
- [ ] Answers to above questions
- [ ] Follow on tickets created
---
