### ISSUE TITLE
Research: Access Request Labeling for Zenhub

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70731]
## Description 
This ticket was created as a result of the November 28, 2023 retro. We identified the following issue with the access request process:

- Sometimes the tickets that are submitted as access requests don't automatically get the platform-tech-team-support label added to them. This mean that they do not appear on the Zenhub board (only GitHub) and folks have to search for them or forget they exist.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Identify why the label isn't applied all of the time
- [x] Identify if there is a way to ensure the tag is added every time automatically
- [x] Identify if that is not possible, what manual processes we can implement to ensure access tickets are always seen within our current process (i.e. looking at tickets on the Zenhub board)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by EWashb** [comment]
Update: work on this is currently blocked as we look into funding for our enterprise. I am working with Josh C and the TAC to get this funded before the 12/31/23 end date.

**Comment by bdech** [comment]
Unfortunately we can't control labels being added if the user is creating the GitHub issue without starting from the template https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose

The labels are added because the template is setup to automatically add the specified labels.

**Comment by alyssagallion** [comment]
Label is adding itself to all tickets and we have extended our Zenhub subscription for a year. Closing.
