### ISSUE TITLE
Submitting Pull Requests for Approval Documentation Update: After a Pull Request is Submitted

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70738]
## Description 
This ticket will house the task of adding a "After a pull request is submitted" section to set expectations for VFS teams. This section should include 

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify if this documentation exists somewhere else already
- [x] Type up a potential paragraph/instructions that note what happens to a Pull Request after it has been submitted (i.e. marked approved or sent back with edits)
- [x] Send a message to Johnny Jesensky and Alyssa Gallion to request its addition to the Platform Site

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Communicated to Johnny. @lindsay-insco To add the link to the document where we documented said process and then good to close!

**Comment by lindsay-insco** [comment]
https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/edit-v2/2873983012?draftShareId=ad941c01-a6a9-4695-980a-f576d762a79a - Document made by Isaiah with feedback from team!

**Comment by lindsay-insco** [comment]
https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/edit-v2/2873983012?draftShareId=ad941c01-a6a9-4695-980a-f576d762a79a - Document made by Isaiah with feedback from team!
