### ISSUE TITLE
Advanced Support Best Practices Documentation Update: Access Request Management

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70736]
## Description 
This ticket will house the task of adding best practices for access request management to our [Advanced Support Best Practices (Tier 1) document.](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1)

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Outline the step-by-step process for finding access requests (as it is today) in GitHub and Zenhub
- [x] Include a step for adding the #platform-tech-team-support label so that the ticket will show up in both places
- [x] Take note of any improvements we can make to the process to increase efficiency and decrease stress for the team
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/2870903148/Locating+Labeling+Access+Requests

**Comment by bdech** [comment]
Linked in Advanced Support Best Practices https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Access-Request-Management
