### ISSUE TITLE
How to Handle Access Expirations Documentation Update

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70734]
## Description 
In our November 28, 2023 retro, we discovered that the full access request process isn't documented in all related documentation. This ticket will house the task of updating the related docs to access requests.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Ensure that the section [How to Handle Access Expiration](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#How-to-Handle-Access-Expiration) is on each of the following pages:  [Frontend](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630975664/Front-end+Support+Responsibilities), [Backend](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities) and [DevOps](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2425552908/DevOps+Support+Responsibilities#AWS-IAM-Expiration) have all of the same information around access extensions (missing from frontend/devops?)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_

**Comment by bdech** [comment]
Front-end does not have any access related requests.

**Comment by bdech** [comment]
The DevOps page contains a link to another confluence article which explains access expiration for AWS. That can be found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request)

**Comment by bdech** [comment]
Reviewed all documentation, no changes/additions needed. Access Requests are properly documented as it relates to each CoP.
