### ISSUE TITLE
COE | Create DD Dashboard and Monitor

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70748]
## Issue Description
_Set up a Datadog dashboard to monitor COE. Related ticket is #67880._

---
## Tasks
- [ ] Set up DD dashboard that monitors logs for COE.
- [ ] Set up monitor alert for COE.

## Acceptance Criteria
- [ ] DataDog dashboard for COE
- [ ] DataDog monitor for COE
---
