### ISSUE TITLE
Integrate BIS Country Codes into Front End

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70752]
## Issue Description
_After researching #67556 we discovered a mismatch between the IsoCountryCode library that we pull from in the back end, the Country Names we present on the front end, and the Country Codes that are expected in BIS.
A short term fix was implemented to create special cases in the code for the country names that come in from the front end and manually match them to the expected value in BIS (example: the front end passes in Bosnia, IsoCountryCode lookup returns Bosnia and Herzegovina, but BIS expects Bosnia-Herzegovina)._

A long term fix needs to be implemented that leverages a BIS API to display the accepted country names on the frontend.

---
## Tasks
- [ ] Leverage the BIS API to display the accepted list of country names within the 686/674 online form.
- [ ] Remove short term fix

## Acceptance Criteria
- [ ] The 686/674 online form displays the list of accepted country names from BIS
- [ ] The short-term fix is removed/retired
---

**Comment by steele-lm** [comment]
Tickets related to the short term fix:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/67556#issuecomment-1821447930
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/70380
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/70379

**Comment by steele-lm** [comment]
Fix that was implemented in 2023:

<img width="840" height="642" alt="Image" src="https://github.com/user-attachments/assets/50e520e5-fbaa-410e-9945-a6ae784068ec" />
