### ISSUE TITLE
[possible tech debt] Move health supplies reordering form to My Health route

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70757]
### User story

As an authenticated user, I want to find the form for reordering CPAP/hearing aid supplies/ under `/my-health/` in the VAgov IA, so that it's easy to stay oriented and move back up to the MHV landing page if needed.

### Notes

- confirmed via [slack](https://dsva.slack.com/archives/C0581MN69TJ/p1704918870850539?thread_ts=1704918822.102979&cid=C0581MN69TJ) that there is a single app to move:
  - it’s all in one app (`src/applications/health-supply-reordering`)
- There is also a static page that needs the sign-in widget added to it, as well as "verify your identity" alerts for any signed-in users who see either page. Only LOA3 users should be able to click a direct link to access the form. CAIA will need to make those updates (more in comment below).
  - `va.gov/health-care/order-medical-supplies/`
- CAIA has a [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77499) to put the entry-point links behind login widgets; that is a dependency for this ticket.

## Acceptance criteria

- CPAP/hearing aid supply reorder URL is under `/my-health/`
- Code related to the form is in the appropriate location
- Old URL is redirected to new path
- Requested CAIA update links to this app from static pages
  - Static page has a sign-in widget instead of an exposed primary action link to this form
  - After sign-in, the static page also checks for LOA3 status (id-verified credentials) before exposing the link to the form. 

## Tasks

- [ ] Sign-in widget for static page - [Figma file]()
- [ ] ID-verification alert for static page - [Figma file]()
- [ ] document use cases – either in issue or Test Rail (team preference)
- [ ] test against use cases

**Comment by carlosfelix2** [comment]
@batemapf Requested that the path be all lowercase. 

> when your making the change, would please set the new path to my-health/order-hearing-aid-or-cpap-supplies-form? i uppercased the cpap in there and got yelled at by the IA team and have been promising to fix it…for a while :slightly_smiling_face:

**Comment by carlosfelix2** [comment]
Look to stage 1 PRs:
* https://github.com/department-of-veterans-affairs/vets-website/pull/27533
* https://github.com/department-of-veterans-affairs/content-build/pull/1872
* https://github.com/department-of-veterans-affairs/devops/pull/13890

**Comment by carlosfelix2** [comment]
I found that the migration steps from before have a problem that the vets-website and content-build repos need to be updated at the same time in Stage 2 for that to work. I also found that specifying the same app with different paths in the content-build repo's registry file will result in a virtual redirect to the rootUrl specified in the apps manifest. So, the migration steps are now as follows:


1. Stage 1 - Pre-setup for the redirect
  - [x] Add the new `/my-health/order-hearing-aid-or-cpap-supplies-form` path to the [reverse React proxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml) in the `devops` repo to open up the new path to the React apps.
  - [x] Add a new React app to the Drupal registry in the `content-build` repo to point to the new URL, but using the same original app. This will result in the app redirecting itself to the URL specified in the app's manifest file.
  - [x] Wait until all changes are deployed to production and verify `/my-health/order-hearing-aid-or-cpap-supplies-form` redirects to `/health-care/order-hearing-aid-or-CPAP-supplies-form`.
2. Stage 2 - Enable the new URL
  - [ ] Change the existing ordering app in the `vets-website` repo to the new path.
  - [ ] Change any static links to the reordering site that exist in the `vets-website` repo to use the new URL. There are only a few in unit/e2e tests.
  - [ ] Wait until all changes are deployed to production and verify `/health-care/order-hearing-aid-or-CPAP-supplies-form` redirects to `/my-health/order-hearing-aid-or-cpap-supplies-form`.
3. Stage 3 - Make the redirect permanent
  - [ ] Add a new redirect from the old to the new URL in the [reverse proxy redirect config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml) of the `devops` repo.
  - [ ] Remove  the old `/health-care/order-hearing-aid-or-CPAP-supplies-form` path from the [reverse React proxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml) in the `devops` repo.
  - [ ] Wait until all changes are deployed to production and verify `/health-care/order-hearing-aid-or-CPAP-supplies-form` redirects to `/my-health/order-hearing-aid-or-cpap-supplies-form`.
4. Stage 4 - Cleanup
  - [ ] Remove the app using the old URL from the registry in the `content-build` repo. 
  - [ ] Wait until all changes are deployed to production and verify `/health-care/order-hearing-aid-or-CPAP-supplies-form` redirects to `/my-health/order-hearing-aid-or-cpap-supplies-form`.
  - [ ] Contact CAIA to do a content audit to replace any of the old links to the new one. File an intake request for CAIA to update any links to the ordering tool.

**Comment by wesrowe** [comment]
status at planning mtg: waiting on CAIA for ticket referenced above

**Comment by sterkenburgsara** [comment]
@carlosfelix2 @wesrowe realizing that the supply re-order form is currently visible to unauth users and this won't work when it migrates to `/my-health`since the entire health portal sits behind authentication. I wrote this up in a [Slack post here](https://dsva.slack.com/archives/C0581MN69TJ/p1709137757791709), but repeating the nuts & bolts below for documentation. 

The CPAP & hearing aid batteries supply re-order form is currently visible to unauth users and this won't work when it migrates to `/my-health` since the entire health portal sits behind authentication. We need the CAIA team to update the `/health-care` benefit hub pages for both entry points to actually have a sign-in modal in place (currently there is just an action link that routes users to the form even when in an unauth state). If we don't update those, unauth users will be able to see & click that link but will not be able to get to the form.

**Relevant pages:**
* https://www.va.gov/health-care/order-cpap-supplies/
* https://www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/

Not only do those pages need sign-in modals in place, but CAIA needs to implement "verify your identity" alerts for any signed-in LOA1/2 users. Only LOA3 users should be routed to the actual form. Also need to ensure this form is removed from our xml index when it migrates, so that it isn't being picked up by crawlers. // cc @mnorthuis

**Comment by wesrowe** [comment]
A thought on implementation - did we look at changing the login widget that CAIA uses all over the benefit hubs so that every instance has the LOA1 check? or did CAIA do that already?

**Comment by wesrowe** [comment]
FYSA, CAIA created a [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77499) for adding login widgets to the entry point pages for this form.

**Comment by wesrowe** [comment]
Update on CAIA and entry points: CAIA needs a team to implement the login widgets on these entry points. I [referred](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75016#issuecomment-2004312861) them to Public Websites, the dev team for the benefit hubs.

**Comment by sterkenburgsara** [comment]
@wesrowe is this unblocked now? I believe Carlos merged the sign-in widget ticket. 

// cc @Jenny-yw

**Comment by carlosfelix2** [comment]
We are waiting on the identity team to complete the integration into the UI.

**Comment by wesrowe** [comment]
This ticket can be wound down since we're launching the new app at the /my-health URL. 

After the new app launches, we can review whether this work left behind any tech debt.

**Comment by wesrowe** [comment]
Not clear what this is for. We have #79957 for cleaning up old app. Closing.
