### ISSUE TITLE
Upgrade Tier 1 Jenkins Permissions to Allow for Migration

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#70764]
## Issue Description
Tier 1 Support Specialists currently unable to see option to `Build With Parameters` in Jenkins to run database migrations for GIDS

---
## Tasks
- [ ] Discuss process for acquiring permissions with Clint Little
- [ ] Create ticket for engineer work
- [ ] Test Migration

## Acceptance Criteria
- [ ] Tier 1 Support Specialists able to run database migrations for GIDS in `staging`, `dev` and `prod` environments

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alyssagallion** [comment]
Unplanned sick time, unable to get to work. Will put in backlog for now.

**Comment by alyssagallion** [comment]
No longer relevant. Not something we want to take on. Closing.
