### ISSUE TITLE
[UX] [PRODUCT] Run Test Cases for Functional Testing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#70768]
## Description
As a team, we need to perform functional testing so that we can ensure our feature is ready for release. 

## Tasks
- [x] Complete this [TestRail test plan](https://dsvavsp.testrail.io/index.php?/plans/view/5022), which consists of these 2 test runs
    - [x] [UX Test Run 12/2023](https://dsvavsp.testrail.io/index.php?/runs/view/5023&group_by=cases:section_id&group_order=asc)
    - [x] [Product Test Run 12/2023](https://dsvavsp.testrail.io/index.php?/runs/view/5024)

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/70768?planning-poker) with Zenhub @benbrasso-agile6 @kellysmith1008

**Comment by kellysmith1008** [comment]
Lori and I tested and validated this today. Test rail tests complete.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I'm not sure if @loripusey will share about this ticket or not in sprint review, but UX's portion was to run the tests to make sure what we saw in the review page is what we have in the design specs. That portion of it turned out just fine - what did come from the testing I did was we noticed that the additional component content under "Are you claiming only mileage" had the wrong content in it, but Brian was able to fix that while working towards completing the travel review page ticket so we're all set now.  If you wouldn't mind sharing for me at sprint review, I'd appreciate it! Thanks!

**Comment by benbrasso-agile6** [comment]
Np, thanks Kelly
