### ISSUE TITLE
Additional Questions about account security - notifications, verification timing

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#70773]
### Description of UX Tasks
As part of our work to map current account security and recovery processes, we realized we had some additional unanswered questions.

- [x] Get info about ID.me notifications, especially as related to fraud or potentially fraudulent sign ins
   - [x] Set meeting (Dec 14th)
   - [x] Meet and discuss, including
   - Who is in charge of their content (esp around fraud and security).
   - time estimate for verification process
      - median time to verify with IDme - self service, unsupervised 4 min
      - wait time to connect to a trusted referee, 3 min
      - time to verify via trusted referee (entire time, 28 min - sometimes including personal breaks on user side)
   - send IDme answers back about USiP link that doesn't correctly link to create account
- [x] Get info about Login.gov notifications, especially as related to fraud or potentially fraudulent sign ins
- [x] Consider how our team can offer notifications that don't overlap with CSP notifications - create a new ticket if add'l work should be undertaken. That may include research to understand how much notification veterans want. For example, if a CSP notifies about sus activity on a user's CSP account, should we also notify them if sus activity in there VA account?

### Documentation

- [Assisting Victims of Fraud](https://docs.google.com/document/d/1ASo1xGhpD6J__mWNaCVoSUbCZWyX-7DRkCbi_iB8AJk/edit)
- [VA Fruad prevention plan](https://docs.google.com/document/d/1zQ37yYtgETKgAuMa8ryFd0ELjPHRSuOqHHdJHgahED0/edit?usp=sharing)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694787677574/98397861b6a02d24c5cb0b91f461f458a825ad74?sender=u2bba352d5b2fc0f0969e0146)
- [secondary research current account recovery process.md in Sensitive GH repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/Identity/BDPR)

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

```[tasklist]
### Tasks
- [ ] test task 1
- [ ] test task 2
```
