### ISSUE TITLE
CH 36 | Mitigate Failed Claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70789]
## Issue Description
_27 Chapter 36 claims within the last 60 days were missing identify information and had no Central Mail GUID, which could mean that the claims were never sent to CMP._

---
## Tasks
- [x] Identify remaining claim errors
- [x] Mitigate remaining claim errors

## Acceptance Criteria
- [ ] All claims submit successfully
---

**Comment by micahaspyr** [comment]
I'll need to look into this first thing tomorrow morning, but the fix for the other Central Mail claims should also apply to ECC as it is also a Central Mail claim

**Comment by micahaspyr** [comment]
No claim failures have been seen since December 11th leading me to believe the CM fixes for the other Central Mail claims (Burial, Pension) have also rectified for CH 36
