### ISSUE TITLE
Burial | Mitigate Failed Claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70785]
## Issue Description
_150 Burial claims within the last 60 days were missing identify information and had no Central Mail GUID, which could mean that the claims were never sent to CMP. A root cause of this are metadata errors due to unaccepted special characters._

---
## Tasks
- [ ] Identify remaining claim errors
- [ ] Mitigate remaining claim errors

## Acceptance Criteria
- [ ] All claims submit successfully
---
