### ISSUE TITLE
Facility meta description field in Drupal is not populating the template

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#7079]
## What happened?
![view-source_https___www_va_gov_pittsburgh-health-care_locations_h-john-heinz-iii-department-of-veterans-affairs-medical-center__and_Edit_VAMC_facility_Pittsburgh_VA_Medical_Center-University_Drive___VA_gov_CMS_and_h__john_heinz_iii_departme](https://user-images.githubusercontent.com/643678/77201356-b91b5f80-6ac2-11ea-8a7f-43afa7fd17b4.jpg)

## Steps to Reproduce

1. Compare the Meta description content on https://prod.cms.va.gov/node/84/edit to the meta description [in the front end](view-source:https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/) and in [the google search](https://www.google.com/search?q=h.+john+heinz+iii+department+of+veterans+affairs+medical+center&oq=H.+John+Heinz+III+Department+of+Veterans+Affairs+Medical+Center&aqs=chrome.0.0j69i60l3.212j0j1&sourceid=chrome&ie=UTF-8)  

## Desired behavior
They should all be the same. 

## Acceptance Criteria
- [ ] Meta description in Drupal works as intended.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ethanteague** [comment]
@kevwalsh - in your screenshot, you are showing node 84 for the drupal piece (University Drive) and HJ Heinz for the build output, so this mismatch is going to create a discrepancy between input and output. I compared `http://va-gov-cms.lndo.site/node/84/edit` to the output for `http://localhost:3001/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/` and the metas matched up. Did the same for `http://va-gov-cms.lndo.site/node/175/edit` (Heinz) and `http://localhost:3001/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/`. Apologies if I'm missing something obvious.
![heinz_metas_drupal](https://user-images.githubusercontent.com/2404547/84902314-ad681680-b07a-11ea-81e7-749c2f6aab0a.png)
![heinz_metas](https://user-images.githubusercontent.com/2404547/84902315-ae00ad00-b07a-11ea-9271-548dfa934527.png)
![university_drive_drupal_metas](https://user-images.githubusercontent.com/2404547/84902316-ae994380-b07a-11ea-8e2c-fc816c85c2bf.png)
![university_drive_metas](https://user-images.githubusercontent.com/2404547/84902317-ae994380-b07a-11ea-95f9-ad2daac228d5.png)

**Comment by kevwalsh** [comment]
@ethanteague this was so long ago i barely remember it. but it sure likes like i had some wires crossed, and if you can't reproduce it... WON'T FIX!
