### ISSUE TITLE
Discovery: How might MHV on VA.gov alert users about EHR system downtime?

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70798]
### User story

As an authenticated user who has access to health tools, I want to be notified in the case that a back-end system has a scheduled or unscheduled downtime window before I have a bad experience.

### Notes
- Various documentations available:
  - Platform [downtime alerts doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications)
  - Platform content guidance regarding [system alerts](https://design.va.gov/content-style-guide/error-messages/system)
  - PagerDuty [maintenance alerts docs](https://support.pagerduty.com/docs/maintenance-windows)
  - Maintenance banner [web component](https://design.va.gov/storybook/?path=/docs/components-va-maintenance-banner--default)
- CMS "full width alert" alternative
  - requires a content release, which typically run every 40-60 mins during business hours
  - looks different from in-page `va-alert` component
- Solution should also work for the mobile app
- Separate API possibilities are possible: just 1 or all 4 endpoints could go down
  - 3 MHV APIs (rx, records, messaging)
  - 1 VAOS backend
- Oracle (Cerner) doesn't need separate treatment, it and VistA are upstream of the 4 APIs
- Testing DowntimeNotification with `yarn mock-api` [Slack thread](https://dsva.slack.com/archives/C044WNQT4P9/p1703096233686569)

Right after we started this story we learned the tool teams had a PR up for adding downtime alerts to their apps: 
- [slack thread](https://dsva.slack.com/archives/C03ECSBGSKX/p1703096388437429?thread_ts=1703093664.273269&cid=C03ECSBGSKX)
- Wes publicized in the thread our intention to recommend a way forward from the MVP solution in the PR

Goals for the solution:
- Can be activated quickly outside of any release or content-build cycles
- Enables responses across all APIs or specific to a single API
  - ...and the alerts can be tailored to apps impacted by the down API(s)
- Ideally would create a single source of truth for API downtime that could be leveraged by the Mobile app

## Acceptance criteria

- Documented downtime scenarios for major dependencies that would impact the user experience for MHV on VAgov (tools as well as landing page)
- Drafted recommended approach across landing page and tools

## Tasks

- [x] Read all relevant documentation
- [x] Consulted DST (design system team) at office hours
- [ ] Ticketed next step(s), including looping in tool teams (team + Wes)

**Comment by radavis** [comment]
There's an opportunity to refactor the DowntimeNotifications component, removing unused code. The call to `getGlobalDowntime()` has been [commented out for 3 years](https://github.com/department-of-veterans-affairs/vets-website/blame/170e0f8/src/platform/monitoring/DowntimeNotification/containers/DowntimeNotification.jsx#L55).

**Comment by dcloud** [comment]
The presence of the `DowntimeNotification` component and `externalServices` object that ties into PagerDuty suggests to me that the _scheduled_ or expected downtime has an existing solution, and next steps, based on [Platform Downtime Notifications](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-AddinganewPagerDutyservice) are:

- Add new PagerDuty services for each MHV "child" service: https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-AddinganewPagerDutyservice
- Update devops repo for each 
- Have each application add the `DowntimeNotification` and assign dependencies. The landing page would depend on the "all mhv" service. Apps like medications would depend on the "all mhv" service plus a medications-specific service

It's unclear what steps would be taken for _unplanned_ downtime, aka an _outage_. PagerDuty certainly has mechanisms for reacting to outages, but I don't know if/how that is set up for VA PagerDuty. I'm not sure if an _outage_ can or should be handled as a maintenance window.

**Comment by dcloud** [comment]
Began a doc for this at https://github.com/department-of-veterans-affairs/va.gov-team/pull/72520/files?short_path=db315a8#diff-db315a8adad6908236b3c8cd9f4d60ac6a40ac2dbdd57cd9048cdb50523450e5

**Comment by wesrowe** [comment]
Notes from sync with Sara, Keith, Jim, Wes:
- Tool teams will implement downtime-alert component as SM is already doing
- Eng need to figure out nuts and bolts about how to actually make Appt and MHV Pagerduty flags available to landing page (to go into new ticket)
  - anticipate modifying the existing DT alert code to ease tool teams' adoption
- Content: finalize content
  - for tool content, need to pull SM's content and just get the same message across tools
  - for landing page, adapt that content for for Appts downtime alone, MHV-wide downtime alone, or both at the same time
  - [we decided not to alert on the LP when individual tool services are down]

**Comment by dcloud** [comment]
I've [drafted a doc in va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/pull/72520/files) for general findings. It needs work and updates since the MHV app/services teams have merged [their PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27233)

**Comment by keithcheung828** [comment]
Updated Mural for [downtime notifications design](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702946244611/d44fd191e13bc9d66a67d6e27deda6f1ee4a6f88?sender=u4c72b2ff45e7c2f8e2942500)

**Comment by dcloud** [comment]
@keithcheung828 We can confirm that the `DowntimeNotification` component allows us to customize what gets rendered, with the minor caveat that we would need to handle logic around approaching vs current downtime in addition to the logic for what the combination of alerts would look like.

**Comment by radavis** [comment]
> User Story: As an authenticated user who has access to health tools, I want to be notified in the case that a back-end system has a scheduled or **unscheduled downtime** window before I have a bad experience.

Unscheduled downtime, as in "a supporting service will be taken down, now" can be handled as a scheduled downtime event, and a corresponding downtime event for a service would be created in PagerDuty.

**Comment by radavis** [comment]
When reading this user story, I began to wonder how we might handle a service outage and wrote out some thoughts.

> User Story: As an authenticated user who has access to health tools, I want to be notified in the case that a back-end system has a scheduled or **unscheduled downtime** window before I have a bad experience.

Unscheduled downtime, as in "a supporting service will be taken down, soon/now" can be handled as a scheduled downtime event, and a corresponding maintenance window for the service can be created within PagerDuty, triggering the `DowntimeNotification` component.

Unscheduled downtime, as in "a supporting service has become unresponsive," aka, an outage, should be handled 1) gracefully by FE code when CRUDing resources, 2) by the `breakers` gem on the BE preventing requests to the downstream service and responding with an appropriate HTTP status code, 3) by ops teams, who would see that one or more services have become unresponsive, 4) by team members, who would create a maintenance window within PagerDuty for the downed service as part of the [incident response procedure](https://depo-platform-documentation.scrollhelp.site/developer-docs/incident-response-documentation-for-application-te). Note that the breaker status of services can be found in [Datadog](https://vagov.ddog-gov.com/dashboard/7yz-4e3-6hs/vsp---breakers).

Perhaps there is an opportunity here to have vets-api update PagerDuty when a breaker trips on a service integration, automatically creating a maintenance window.

**Comment by dcloud** [comment]
FWIW, the [maintenance banner](https://design.va.gov/components/banner/maintenance#usage) says:

> This component is ONLY for site-wide [system status messages](https://design.va.gov/content-style-guide/error-messages/system). There is no other appropriate use.

**Comment by wesrowe** [comment]
We need to carry this story into sprint 22. There seems to be some needed coming together between Engineering and Design. The AC is "Drafted recommended approach across landing page and tools." 
- E.g., the question in comments above seems unanswered, of what design system component to use on the landing page.
- I don't think I saw anything in Keith's presentation about the alerts on the tool pages. Daniel found that the Appts team did something custom with the downtimeAlert component. That's a key input to the UX design across the portal; the landing page can't just do our own thing, it needs to rhyme with the tools' implementations.

**Comment by keithcheung828** [comment]
Consulted with DS team that the downtime alert design is based on the [alert page on design systems](https://design.va.gov/components/alert#usage)

**Comment by wesrowe** [comment]
Some interesting discoveries that will guide our recommendation:
- tool-level implementation from late December has several major UX issues that need to be addressed ([slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1704412340440999))
  - didn't include time window
  - has no reference to app that is missing from page – even the H1 from the page is gone. this is an a11y issue, so urgent before next downtime.
  - Daniel suggested adding an opt-in header feature to the downtime notification component
- the "all-MHV" PagerDuty service that the tool teams are leveraging may not mean what we thought it meant. Per [Stephen Barrs](https://dsva.slack.com/archives/C04DRS3L9NV/p1704471144967659?thread_ts=1702663719.861489&cid=C04DRS3L9NV), that PD service "is owned by the identity team and is triggered when there are issues with users attempting to authenticate using the MHV credential." this is a totally separate functional domain from the APIs.
  - so our rec may need to include a new "all MHV" PD service
- will a modal be involved? the docs of the DTA component say a modal appears in the final hour before a window; however, I haven't seen anything about a modal in our team's investigation so far.

**Comment by wesrowe** [comment]
recommendation scope from meeting 1/8 (Daniel, Keith, Wes):
- assume a single MHV PagerDuty
- recommend content for landing page and tools (including headings and alert content)
  - recommend heading/tool name for tool pages
  - landing page will warn users about missing functionality but not hide any tool links
- technical recommendation for whether/how DTA component itself needs to be changes to accommodate UX recommendations (for either landing page or tool pages)
- modals required in current DTA component?
  - custom render prop overrides the modal trigger, so it won't show on any tool page (Appts is passing a custom render prop, but other tools use out of box with modal)

**Comment by dcloud** [comment]
Also in our discussion, it seemed we were focused on _timed_ maintenance windows, aka scheduled downtime. PagerDuty will provide start and end times regardless of whether the maintenance window was planned/scheduled or not. 


The platform component doesn't mention start or end times, perhaps assuming that the unscheduled downtime case is more common than the scheduled maintenance window.

**Comment by wesrowe** [comment]
I told Janie (PO for SM) in [this thread](https://dsva.slack.com/archives/C03ECSBGSKX/p1704833272892049?thread_ts=1704475687.002169&cid=C03ECSBGSKX) that we would share our recommendation there when it's ready. There's another thread where I should post it also when the time comes.

**Comment by keithcheung828** [comment]
[Mural updated](downtime with and w/o timed maintenance windows) to contain: 
1. MHV downtime with and w/o timed maintenance windows
2. Single tool downtime with and w/o timed maintenance windows
3. Multi tool downtime with and w/o timed maintenance windows

**Comment by keithcheung828** [comment]
4. If alerts are not able to specify tools that are down, an alternative design is shown below:
<img width="351" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNit4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0c92a890995c57ee40b7daba4acc1a9dc87179d/Generic%20tool%20scheduled%20down.png" alt="Generic tool scheduled down.png" />

**Comment by keithcheung828** [comment]
Please see the [updated mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705509202969/42becb4e1bcb478d93488ced78511a9c6acf9276?sender=u4c72b2ff45e7c2f8e2942500).

**Comment by wesrowe** [comment]
@keithcheung828, is this screenshot from the mural accurate? It's supposed to be the current state of the Inbox page, in the pre-maintenance timeframe. But it doesn't have an H1. 
<img width="279" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/8037cb55-c422-4b64-99f5-1f09a7cc641c">

**Comment by wesrowe** [comment]
@keithcheung828 made final changes to mural. closing!
