### ISSUE TITLE
[FE] My VA Health: Re-instate Cerner/Oracle message

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#70797]
## Background
We need to reinstate the message that cerner/oracle users see in the Health Care section of My VA. This is simply reverting back to what we used to show for Cerner, sketch link below:

https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/mPwRlZz

When we implemented the change to remove the Cerner message we did it in conjunction with adding a link to the MHV landing page for all health care users and both changes were added using the feature flag `my_va_remove_cerner_message`. We need to rename the flag so it's not confusing since the flag will only be applicable to the code which implemented the addition of the MHV link. Tickets for the previous work for reference linked below:

- #67432 
- #67431 

## Tasks
- [x] Reinstate Cerner message for Cerner users (no flag needed)
- [x] Rename the feature flag (`my_va_remove_cerner_message`) to something more appropriate 

## Acceptance Criteria
- [x] Cerner message appears for Cerner users
- [x] All LOA3 users who are not Cerner users still see the link to the new MHV landing page in the Health Care section on My VA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_

|Scenario | User | Steps to reproduce|
|---|---|---|
| Cerner user | 36 | Log into staging with user 36 - confirm the Cerner message displays|
|Regular health care user | 41 | Log into staging with user 41 - confirm "visit mhv" link appears in link list|
|Non-health care user | 3 | Log into staging with user 3 - confirm "visit mhv" link appears in link list|

**Comment by allisonlu** [comment]
The changes are up on `vets-website`, but I don't think the name change on `vets-api` has been pushed to staging, so this isn't _quite_ ready for validation yet. I'll check back next week and let you know when it's ready!

**Comment by allisonlu** [comment]
The new feature flag name is now on staging for `vets-api`! 

https://staging-api.va.gov/flipper/features/my_va_enable_mhv_link

**Comment by ajakabcin** [comment]
Looks great - I confirmed things are working as expected with users 36, 41 and 3 as noted in the ticket. Thanks @allisonlu !

**Comment by ajakabcin** [comment]
I'm going to close this out - we're aware there's an issue with the link to legacy mhv portal but that's unrelated to the work here
