### ISSUE TITLE
Design | Profile | Enhanced military Info | Co-design sessions with internal participants

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#70802]
## Background 
Now that we've located veterans who are willing to share their information we will use this ticket to coordinate co-design sessions with those veterans

## Tasks 

- [ ] Schedule sessions with 3-4 willing participants, ideally from different branches of service, and with different years of service
- [ ] Create a mural board template to be used in the sessions
- [ ] Conduct sessions

## Acceptance Criteria 
- [ ] have a rudimentary concept of the information we can use to talk about this w/non-VA-employed veterans

**Comment by mtcA6** [comment]
@pamela-drouin based on how the research went I'm going to close this out as "not planned" and if we do decide to move forward we can reopen it.
