### ISSUE TITLE
Map NDBx Form Submission Pathways

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70815]
## Issue Description
_Create a visual map of the form submission pathways, backup pathways, and fail safe pathways for Chapter 36, Chapter 31, Burial, and COE in this [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?sender=u0e8ac1d6d7681bb7e1b80558)._

---
## Tasks
- [ ] Map happy path submission pathway
- [ ] Map backup submission pathway
- [ ] Map fail safe submission pathway

## Acceptance Criteria
- [ ] VA Mural contains pathways for Chapter 31, Chapter 26, Burial/Pension, and COE
---
