### ISSUE TITLE
Copy of Shadowing Research: Interview Sessions

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#70817]
## Issue Description
This ticket documents the interview sessions being conducted over the course of a sprint. We're doing interview sessions for [Veteran Shadowing Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2023-11-Shadowing-Research) that we are conducting in order to better understand the end-to-end experience of 526 completion. 
---
## Tasks
- [ ]  Conduct or take notes for interview sessions, 2 hours each 
- [ ]  Manage data from interviews and prepare Mural notes for synthesis
- [ ]  Early synthesis (not yet at topline stage) 

## Acceptance Criteria
- [ ]  Interviews are complete
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
This morning's interview counted toward total completes of the 526 (4 of 5 desired). If our next participant starts the form, our research will come to a close.

**Comment by evelynhilbrichdavis** [comment]
As per the extension of our study, we are still waiting on 1 participant to start the 526.  Our research was officially extended during this sprint so Perigean could recruit more than our initial n=9 sessions. We have conducted n=10 and are working closely with Perigean to plan sessions to get us to our n=5 count.
