### ISSUE TITLE
[FE] Auth Exp Nametag: Support multiple middle initials

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#70821]
## Background
As explained in #68144 we need to be able to support multiple middle initials in the nametag banner.

## Tasks
- [x] Update helpers.js file to capitalize middle initials
- [x] Write/update unit tests for this change
- [x] Check cyprus/e2e tests and update as needed
- [x] Move to validate and tag PM for testing

## Acceptance Criteria
- [x] The nametag banner is able to support multiple middle initials 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ We'll need to work with VA Profile (I think) to get a test user updated with multiple middle initials

**Comment by ajakabcin** [comment]
@DanielMiller-agile6 we just talked about this in refinement but I failed to mention this: I'll slot this for next sprint, but if you have bandwidth within this sprint once your current assigned work is wrapped up then we can pull this in. Thanks!

**Comment by andaleliz** [comment]
Hi! [This slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1701702000475709) got me looking at the [nametag docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/nametag/README.md) today. Is it possible to get them updated as part of, or after this ticket? I think it'd be helpful to add some more details here about how this works (e.g. which VA Profile data fields are being used), especially as other teams explore personalization.

**Comment by ajakabcin** [comment]
Yup! @andaleliz we usually do a documentation update once the feature is out

**Comment by ajakabcin** [comment]
@andaleliz I actually don't think we have use case documentation for the Nametag (not that I can find at least) - within Profile documentation or My VA. So an additional thanks for flagging so we get that spun up. I think we can decide where to put it (under profile or my va) and then link to it for both products.

**Comment by andaleliz** [comment]
@ajakabcin I linked them in my earlier comment - though it's not set up like the rest of our use case docs, exactly. It's more like all the uses cases are in one doc.  It's a starting point at least.

IMO it would make sense at the `/identity-personalization/` level since it applies to both profile and My VA, and _ideally_ would be used anywhere else on the site where there is a desire to reflect the Veteran's name back to them.

**Comment by ajakabcin** [comment]
Dropped this down to a 1 - I'd like to keep it open into next sprint so we can try and get a test user with multiple middle initials

**Comment by DanielMiller-agile6** [comment]
PR is merged and should be available for ttesting on dev/staging soon.  We can track deploy progress here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/

**Comment by ACParker89** [comment]
This can be closed once test user is completed- follow up to find out how to set up a test account.

**Comment by ajakabcin** [comment]
We won't be able to find a test user for this so instead will need to validate at unit test level. 

@DanielMiller-agile6 or @allisonlu can you confirm when you have a moment and then close out? Thank you!

**Comment by DanielMiller-agile6** [comment]
Validated that our tests produce expected strings for middle initials, when provided to client in a full name.  Also verified NameTag component still works as expected for names that don't include multiple middle initials.  We can be on the lookout for users who may define their middle name this way, but seems to be a fairly rare use-case.
