### ISSUE TITLE
[Content] Create content for canceled appts for check in 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70820]
## Tasks
- [x] Review and update content, if needed, for VeText check in response for cancelled appt for Design Priority 1 in unified check in, e.g., should potentially mention it's been canceled, but not specific as to who canceled it. Since Veteran is attempting to check in, that means that they're likely at a facility. 
- [x] Update content sketch files
- [x] Ask Lori to send change request to Justin from VeText
<br>
<img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/b0b1d2c6-e770-41db-a746-640bdcd45425" width="250">

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [x] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [x] Yes
- [ ] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [x] Work was reviewed by groups indicated above
- [x] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/70820?planning-poker) with Zenhub @kellysmith1008

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 While working through this, I thought of a (potentially extreme) edge case where an appointment is canceled **after** the 45 minute text reminder has gone out. Do you want me to/do I need to account for that scenario and have wording in there as well? Does that question even make sense?!

**Comment by benbrasso-agile6** [comment]
It does make sense, let me think for a sec...

**Comment by benbrasso-agile6** [comment]
We would just want to review and adapt this https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/04C2CEC7-895F-4D1E-93A8-6BA0F1B97FED/canvas which was for pre-check-in. Why we didn't think about that when we were during pre-check-in, I don't know :)

**Comment by kellysmith1008** [comment]
[Mocked up an additional text message](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/0ArO8V2) for canceled appointments in Priority 1 check in

**Comment by benbrasso-agile6** [comment]
Left two small comments. Otherwise, looks perfect. Nice work.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @loripusey After a small tweak to the content based on feedback from Peter Russo, the content is ready to send to Justin for VeText work
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/0ArO8V2
Moving to validate now

**Comment by loripusey** [comment]
Let Justin know to add this to the VeText backlog. [See slack thread.](https://dsva.slack.com/archives/C022AC2STBM/p1704735768753859)

**Comment by benbrasso-agile6** [comment]
Added into our Design page in Unified Check In Sketch file too

**Comment by benbrasso-agile6** [comment]
Added into Figma too https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=259%3A1284&mode=design&t=Gb1GX4Vyel93Hrg0-1

**Comment by kellysmith1008** [comment]
Go for it

**Comment by benbrasso-agile6** [comment]
@loripusey added into sprint goals https://github.com/department-of-veterans-affairs/va.gov-team/issues/73137
