### ISSUE TITLE
ARM Analytics Report

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#70834]
## Issue Description
Analytics request to PA&I team and updating final analytics report.

---

## Tasks
- [ ] Manage back and forth with PA&I team
- [ ] Update analytics report
- [ ] Schedule share-out with larger team

---

## Acceptance Criteria
- [ ] Final report delivered

**Comment by oddball-lindsay** [comment]
Expecting to hear back from PA&I on 1/11

**Comment by oddball-lindsay** [comment]
We got the data!

**Comment by jfinnerty13** [comment]
DONE
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2023-12-ARM-analytics/research-findings.md

https://dvagov.sharepoint.com/:p:/s/vaabdvro/Eb4PaT37w9BAq5GkGPbym84BqayV_--MOhiE1wRb6pnTCA?e=by1NKB
