### ISSUE TITLE
[Discovery] Logged in homepage: Review and refine research proposal

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7083]
## Background

Samara created [this research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md) as a preliminary proposal for the activities we want to be part of the logged in homepage discovery effort. Now that we've got the team together, I'd like another set of eyes on this to provide feedback and further refine some of the details.

## Tasks

- [x] Review the plan
- [x] Add a section for research goals & needs
- [x] Map goals back to research activities
- [x] (If necessary) Change/add to/update research methods based on research goals and needs
- [x] Review with the team

## Acceptance Criteria

- [ ] Liz/Samara/Shawna/Tressa are aligned on research goals, needs, and methods

**Comment by andaleliz** [comment]
[Created a research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-plan.md) based on the [research needs document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md#stakeholder-interviews) that follows the VSA template. Still a work in progress.

And, here's a [mural board mapping research goals to methods](https://app.mural.co/t/vsa8243/m/vsa8243/1584898521775/64383bc2873e8c81bdd84190e16726e20855818e)

**Comment by Samara-Strauss** [comment]
Hey! This is looking great. Let's take a few minutes to discuss during our review/sprint planning today.

A few thoughts:

- AWESOME mapping of goals to research methods. And this list of goals looks good/comprehensive to me.
- "How might their experience be improved with an improved logged in experience and notification system?" Idk if this is already clear or not, but when we're talking about a notification system, what I'm interested in answering is this: how can we better notify users of status updates or actions needed? And in what role does the logged in homepage play in status updates/notifications about actions needed?
- Under methods, I noticed you didn't include a competitive analysis, which we had talked about maybe doing in our meeting on Friday. I'm totally fine with this call, just curious as to why you decided against it.
- You can remove anything from the Participants & Recruitment section and below. I think this is a great high-level plan, and we can fill out a separate plan for the user interviews when we're ready to start that process. We should, ideally, have a research plan that just focuses on the interviews when the time comes so that it's cleaner and easier to follow for Lauren/recruiting.

**Comment by Samara-Strauss** [comment]
@sshein

**Comment by andaleliz** [comment]
Updated the doc! Thanks for the feedback @Samara-Strauss.  @sshein, let me know if you have any feedback too.

**Comment by Samara-Strauss** [comment]
Looking good to me! One last request — Can you please link the Mural board from the research plan? That'll make it easier to find for documentation purposes once we close out this ticket.

**Comment by sshein** [comment]
looks good. One thought. a lot of the plan is focused on what people are currently doing on VA.gov.  One of the instigators of this project was that we're moving a bunch of stuff over from eBenefits that may well fit on a logged in dashboard - so veterans are not currently "doing these tasks" on VA.gov. Can we add some questions like "what is currently being migrated from other places onto VA.gov that veterans would expect to find on their dashboard" or something to that effect? I think talking to Steve Kovacs in the stakeholder interviews would make sense here for this purpose.

**Comment by Samara-Strauss** [comment]
> Can we add some questions like "what is currently being migrated from other places onto VA.gov that veterans would expect to find on their dashboard" or something to that effect? I think talking to Steve Kovacs in the stakeholder interviews would make sense here for this purpose.

Agreed! Thanks for raising this, @sshein.

**Comment by andaleliz** [comment]
Ah, really good point! Def not something I considered, @sshein   

I've added a new bullet under Research Questions:
> What is currently being migrated from other places onto VA.gov that Veterans would expect to find on their dashboard?
> - Which tasks are Veterans completing on other VA websites (e.g. eBenefits)?
> - What don't we know?

And I also added the mural board to the Resources section. I think we can close this out.
