### ISSUE TITLE
[FE] 10-10CG - Facilities selection: Review & Submit page update

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#70847]
## Background
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. We need to create the results list that contains radio cards to allow for the selection of a single facility. 

## Scope
The form Review & Submit screen will need to display the facility selected and, in the case of the Caregiver facility not being the same, will need to display the associated Caregiver facility.  Reference the Figma design below

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- [Figma designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2865-26636&node-type=SECTION&t=ZgpbfszDr5lawbcW-0)

## Tasks
- [ ] Update UI on the Review & Submit screen to display the facility selected, and associated Caregiver facility if applicable
- [ ] Edit functionality will refer user back to the Facility Search screen
- [ ] All changes are restricted from production via feature flag

## Acceptance Criteria
- The user will be able view their selected facility (and associated Caregiver facility if applicable) from the Review & Submit screen
- The user will be able to edit, and be returned back to the facility search screen
