### ISSUE TITLE
Update feature toggle names for precision/clarity

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#70842]
### Background
These are our two feature toggles in FAR as of 11/29:

1. `find_a_rep` = backend feature toggle (enables entire backend)
2. `find_a_representative` = frontend feature toggle (enables entire frontend)

We also have `findARepresentative` (camel case) which is how we reference the frontend feature toggle in the context of frontend code.

We decided to move forward with these just to get through Staging Review, but it would be nice to have alignment on naming, which is what this ticket is for.

### New Toggle names

1. `find_a_representative_enable_api` will be enabled prior to staged rollout
2. `find_a_representative_enable_frontend` will be disabled prior to staged rollout and will be enabled to an increasing % of users during the staged rollout.  This will control visibility of both our Find a Rep product and it's related entry point on the CAIA landing page.

### Tasks
Here's a sequence that should avoid any interruptions:

- [ ] PR #1 vets-api - add new toggles (without removing old ones)
- [ ] Enable new toggles where applicable in flipper
- [ ] PR #2 vets-api - update toggle references in ARM backend code
- [ ] PR #3 vets-website - update toggle references in ARM frontend code
- [ ] PR #4 - vets-api  - remove old toggles
