### ISSUE TITLE
[FE] 10-10CG - Facilities selection: Search Results and "show more" link

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#70846]
## Background
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. We need to create the results list that contains radio cards to allow for the selection of a single facility. 

The cards should contain the facility name and address as shown in the Sketch designs listed below. Based on consultation with design system and accessibility experts, we can omit any pagination for this list. We should show all results on the same screen.

**NOTE:** To get appropriate styling between the facility name and facility description, we may need to request for the Design System team to add a CSS part attribute to that markup in the web component to allow us to target those items for styling. 

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- Figma designs
     - [Search Input](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2475-14725&t=xgkK7brjz069I7kE-0)
     - [Search Error](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2475-16237&t=xgkK7brjz069I7kE-0)
     - [Search Results](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2476-14650&t=xgkK7brjz069I7kE-0)
     - [Search Selection](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2476-15276&t=xgkK7brjz069I7kE-0)
     - [Search Selection - error](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2476-15822&t=xgkK7brjz069I7kE-0)
     - [Confirmation - different](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18217&t=xgkK7brjz069I7kE-0)

## Tasks
- [x] Create accessible list of 5 search results using radio cards
- [x] Add a link that allows the user to click and "show more" facilities in the list
- [x] Ensure all work is implemented behind feature flag and not visible in production

## Acceptance Criteria
- Facility selection search results component successfully renders a list of 5 facilities with a "Show more" link, which allows additional 5 facilities to load each time the link is clicked.
- All created components match the provided designs from the UX team

**Comment by hdjustice** [comment]
Update design links @hdjustice

**Comment by hdjustice** [comment]
design links updated

**Comment by coope93** [comment]
Looking into an issue @allanto-ah found in regards to the facilities api returns a 500 error when the facilities list that is returned is nil.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified the issue that was found in regards to the facilities API returning 500 error. No regression issues found as well. Search results and "load more facilities" link are working as expected
