### ISSUE TITLE
[Discovery] Logged-in homepage: Stakeholder interviews — Review and refine list of stakeholders

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7086]
## Background

Epic #7085

We will be conducting stakeholder interviews for the logged-in homepage discovery per our [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md#stakeholder-interviews). We should review and refine[ the list of stakeholders](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md#stakeholder-interviews) to make sure we are talking to the right people.

## Tasks

- [x] Review existing list
- [x] Determine final list of stakeholders

## Acceptance criteria

- [x] We know who we want to talk to so that we can start scheduling interviews with the right folks.

**Comment by andaleliz** [comment]
FYI added Mel Woodard to the list, designer of our [blue sky prototype](https://vsateams.invisionapp.com/d/main?origin=v7#/projects/prototypes/13596891?scrollOffset=216), per our convo last week

**Comment by andaleliz** [comment]
[Created a research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-plan.md) based on the [research needs document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md#stakeholder-interviews) that follows the VSA template. Still a work in progress.

**Comment by Samara-Strauss** [comment]
@sshein

**Comment by andaleliz** [comment]
Final list of stakeholders:
- Charles Worthington
- Chris Johnston
- Lauren Alexanderson
- Samara Strauss
- Clarice Chan
- Steve Kovacs
- Andrea Schneider
- Matt Self
- Jen Lee
- Ryan Thurlwell
- Mel Woodard
- Kevin Hoffman
- John Hashimoto
- Mikki Northius
- Dave Conlon
- Andy Lewandowski

@Samara-Strauss shall I update the [research needs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md#stakeholder-interviews) doc to reflect this updated list? Or do we need to preserve the OG list for some reason?

**Comment by Samara-Strauss** [comment]
I don't think we need to update that list since we'll have be able to see this full list of stakeholders reflected in research notes/the stakeholder interview summary. This looks good to close when you're ready!

**Comment by andaleliz** [comment]
Linking to [notes from our meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/stakeholder-review-notes.md) and closing out.
