### ISSUE TITLE
Pension Team Sprint 9 Plan: 12/06/2023—12/19/2023

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70867]
## Sprint 9: 12/06/2023—12/19/2023

**- Outages (PTO, holiday, or unplanned):** 
-- **Dec 6-8:** Dan (PTO)
-- **Dec 18** Dan (PTO)
-- **Dec 18-22:** Tai (PTO)
-- **Dec 4-8:** Eunice (Military leave)

## Theme(s):

- Finalize pending designs for Step 5 (In home care or care facility expenses, Other medical and/or burial expenses)
- Continue leftover, FE build for Step 4
- Start FE build for Step 5
- Progress in our schema and PDF mapping efforts
- Start planning for Platform's Collaboration Cycle Staging Review

## Notes:
- 
 
## Goal(s):

**RESEARCH/DESIGN**

**_MVP relaunch_**

- [x] [MVP] Update, finalize designs for Step 5 "in home care or care facility expenses" #71181
- [x] [MVP] Create designs for Step 5 "other medical/burial expenses" #71183
- [x] [MVP] Update, finalize designs for Step 5 "gross monthly income" #71098
- [ ] Sync with NDB team to share ideas on Dependents design pattern components #71413 - **Deprioritize this? To focus on the logic diagram and form flow auditing**
- [x] [MVP] Update form flow logic diagram in existing MURAL for Steps 1-3 #70301

**ENGINEERING**

**_MVP relaunch: Frontend work_**
- [x] [MVP] Step 3: Match question wording and copy for Are you 65 years old or older? #69757 - Sprint 7,8 rollover
- [x]  [MVP] Step 4 Household info: Create new page and question for What's your marital status and match copy #69959 - Sprint 8 rollover
- [x]  [MVP] Step 4 Household info: Create new page and question for Reason you're separated and match copy #69960 - Sprint 8 rollover
- [x]  [MVP] Step 4 Household info: Create new page and question for Financial support for your spouse and match copy #69961 - Sprint 8 rollover
- [x]  [MVP] Step 4 Household info: Create new page and question for Current spouse marital history and match copy #69962 - Sprint 8 rollover
- [x]  [MVP] Step 4 Household info: Match rearranged questions, options and add multi-entry for Spouse's former marriage(s) #69963 - Sprint 8 rollover
- [ ]  [MVP] Step 4 Household info: Match question wording for 7 questions under Dependent children details #69967 - Sprint 8 rollover
- [x]  [MVP] Step 4 Household info: Create expandable section for Dependent's disabilities and match copy #69970 - Sprint 8 rollover
- [x]  [MVP] Step 4 Household info: Match question wording for 6 questions under Dependent children details #69972 - Sprint 8 rollover
- [x] [MVP] Step 4 Household Info: Remove 2 questions #70596
- [x] [MVP] Step 5 Financial info, net worth: Create new page and question for Over 25k in assets #70403
- [x] [MVP] Step 5 Financial info, net worth: Create new page and question for Estimate total value of your assets #70408
- [x] [MVP] Step 5 Financial info, net worth: Create new page and question for Did you transfer any assets? #70410
- [x] [MVP] Step 5 Financial info, net worth: Create new page and question for Do you own your home? #70413
- [x] [MVP] Step 5 Financial info, net worth: Create new page and question for Is your home on more than 2 acres? #70423
- [x] [MVP] Step 5 Financial info, net worth: Create new page and question for What's the value of the land more than 2 acres? #70425
- [ ] [MVP] Step 5 Financial info, net worth: Create new page and question for Is the additional land marketable? #70428
- [x] [MVP] Step 5 Financial information, income: Create new page and question for Do you receive income? #71341
- [x] [MVP] Step 5 Financial information, income: Create new page and 4 questions for Add an income source #71345
- [x] [MVP] Step 6 Direct deposit and upload docs: Make sure Contact Info is no longer in this step #71443

**NOTE:** Additional FE work added to this sprint:
- [x] [MVP] Step 5 Financial information, expenses: Create new page and question for Did you pay any unreimbursed care expenses? #71726
- [x] [MVP] Step 5 Financial information, expenses: Create new page and 7 new questions for Add an unreimbursed care expense & multi-entry #71727
- [x] [MVP] Step 5 Financial information, expenses: Create new page and question for Did you pay any medical or other unreimbursed expenses #71728
- [ ] [MVP] Step 5 Financial information, expenses: Create new page and 6 new questions for Add a medical or other unreimbursed expense & multi-entry #71730
- [x] [MVP] Apply for Veterans Pension Page: Update copy from 60 days to "one year" #71647
- [x] [MVP] Step 2 Military history: Update date labels, remove button & option to enter multiple service periods #71705
- [ ] [MVP] Step 3: Correct button copy and remove button after max allowed for Current Employment list loop #71638
- [ ] [MVP] Step 4 Household Info: Add Place marriage terminated question/field to Veteran's Spouse Former Marriage #71712
- [x] [MVP] Step 4 Household Info: Remove Type of Marriage field from Veteran's Spouse's Former Marriage #70596

**_Staging review prep_**
- [ ] Start preparing for required Accessibility artifacts to prepare for staging review #71563
- [ ] Start preparing for required QA artifacts to prepare for staging review #71379

**_Intent to file_**
- [x] Change ITF expiration date #71079

**_PDF data mapping_**
- [ ] [PDF Mapping] Push in the new PDF and PdfFiller classes #70382 - Rollover from Sprint 8
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 1: Identification Info #70385 - Rollover from Sprint 8
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 2: Contact Info #70386
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 3: Service Info #70387
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 4: Pension Info #70388

**_Logging and monitoring strategy_** 
- [x] [Code Yellow] Review of watch tower alerts for Code Yellow #71382 - 30 minute meeting w/Steve
- [x] [Code Yellow] Pass along locations for controllers in Sidekiq jobs #71383 - Matt to pass along?

## **WARNING... Below tasks are not in scope for this sprint but are in scope for MVP**

**- SPRINT 10 (Dec 20-Jan 2 _ONLY 4 WORKING DAYS_)**
**- SPRINT 11 (Jan 3-Jan 16)**

**_Design/Research_**

- [ ] [MVP] Update form flow logic diagram in existing MURAL for Step 4 #71184
- [ ] [MVP] Update form flow logic diagram in existing MURAL for Steps 5-7 #70303
- [ ] [MVP] Test Pension form flow logic in staging for Steps 1-3 #71135
- [ ] [MVP] Test Pension form flow logic in staging for questions in Step 4 #71136
- [ ] [MVP] Test Pension form flow logic in staging for Steps 5-7 #71139

**_Staging review prep_**

- [ ] Start preparing for required Accessibility artifacts to prepare for staging review #71563
- [ ] Start preparing for required QA artifacts to prepare for staging review #71379
- [ ] Schedule Pension MVP relaunch for Staging review #69174

**_MVP relaunch: Frontend work_**

- [MVP] Step 6 Additional information: Update copy #71855 - **Simple copy changes or conditional logic for PDF reminders for MVP?**
- Audit for redundant/old pages no longer part of the form flow #71893 - **Who can help start doing this? An engineer to pair with designer to cross reference?**
- Remove redundant/old pages no longer part of the form flow #71896
- [MVP] Step 7 Review application: Update based on overall form field changes #71857 - **Dependent on the above? Need to have questions in order and redundant pages/questions removed**
- End to end frontend testing of the form

**_MVP relaunch: Backend work_**
- [MVP] Implement/confirm claim submission date appears on Pension PDF form #71456
- Ensure we capture the user signature appropriately - **Need more info on this?**
- PDF data mapping tasks listed below - **Map sections 5 through 13 of PDF**
- Update vets-json-schema #71917
- Add polling to Lighthouse Benefits Intake API #71897
- Prepare form scenarios for various PDF mapping use cases
- Backend, data mapping testing

**_PDF data mapping_**
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 5: Employment History #70389
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 6: Marital Status and Spouse Info #70390
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 7: Prior Marital History #70392
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 8: Dependent Children #70393
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 9: Income and Assets #70394
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 10: Info About Unreimbursed Medical Expenses #70395
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 11: Direct Deposit Info #70396
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 12: Claim Certification and Signature #70397
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 13: Witness to Signature #70398

**_Migrating to Lighthouse Benefits Intake API:_** 
- [ ] Add polling to Lighthouse Benefits Intake API #71897

**_Schema mapping_**
- [ ] Update vets-json-schema #71917
