### ISSUE TITLE
Discovery: Consolidate/merge duplicate docs on Continuous Deployment

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70863]
## Description
On a Slack thread in the #platform-cop-frontend, it was flagged that we have two documents essentially describing the same thing.

1. [Continuous deployment](https://depo-platform-documentation.scrollhelp.site/developer-docs/continuous-deployment#Continuousdeployment-Enablingcontinuousdeployment)
2. [Isolated application builds](https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds)

These two pages likely need to be merged, consolidated, or reconciled in some way, to avoid confusion

**Slack Thread:** https://dsva.slack.com/archives/C04868KS69L/p1701290307228389

## Tasks

- [x] Review content of pages with SME (possible SME Curt Bonade)
- [x] Determine what action should be taken, (merge, consolidate, refine, etc.)
- [x] Create edit ticket to make proposed changes

## Acceptance Criteria
- [x] All tasks completed

**Comment by jknipes** [comment]
Hey @acrollet , I'm revisiting this older ticket to see if we can knock it out. If you feel it is still relevant, would you be able to help us consolidate the 2 docs?

**Comment by acrollet** [comment]
@jknipes I think the best SME for this task would be @CBonade 🙂

**Comment by BSmolensky** [comment]
I think this ticket needs even more refinement. After taking a look at the Slack Conversation and the two linked pages....this is not an issue of simply 2 pages about the same thing -- in fact, the two linked pages above are not exactly about the same thing. BUT there are two IDENTICAL -- truly IDENTICAL -- page on the pw titled "Build and deply process flow."

Here they are: 

1. https://depo-platform-documentation.scrollhelp.site/developer-docs/build-and-deploy-process-flow
2. https://depo-platform-documentation.scrollhelp.site/developer-docs/build-and-deploy-process-flows

If you look closely at the IA, you'll see that 1 above is a child page of "Isolated application build" and 2 above is a child page of "Deployments."

**Comment by BSmolensky** [comment]
SME contacted. Waiting on response.

**Comment by BSmolensky** [comment]
SME's reply: 

> Right now we’re working on sweeping deployment changes that are due to launch the first wave of in February. This will require a lot of documentation overhaul and probably some new documentation and will include an overhaul of these docs. I don’t know that it’s worth rewriting these docs for the current state of this, when it’s going to be looking very different in the near future

**Comment by BSmolensky** [comment]
Based on SME's advice. We should not go forward with this edit. This whole section of the PW is getting overhauled. Perhaps we can create an icebox ticket for sometime in early Q2 to circle back and determine if this is still an issue post overhaul.

**Comment by BSmolensky** [comment]
All tasks complete. Ticket is ready to close.

**Comment by jknipes** [comment]
Closing as above
