### ISSUE TITLE
Update 'Create New Content Page' Doc for #70668

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#70869]
## Description
Erika has highlighted the need to update the _[Create a New Content Page](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-content-page)_, through [this footer ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70668). As was suggested in the related ticket, "we need to differentiate vagov-content and Drupal aka content-build."

**SME:** Erika Washburn

## Tasks
- [x] Connect with Erika to determine what updates need to be made.
- [x] Make edits on the page.
- [x] Review edits.
- [x] Prepare page for deployment.

## Acceptance Criteria

- [x] Page has been updated with new, or updated content.
- [x] Page has been deployed and is live.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/70869?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
Contacted SME. Waiting for response.

**Comment by BSmolensky** [comment]
Heard back from SME: "This definitely isn’t critical, but I would say let’s get this on the board before the beginning of February. That incumbent team with the most historical knowledge is rolling off on 2/7/24 so I would like to get their input before they go."

Moving this ticket back to the backlog for now. Happy to work on it as info trickles in.

**Comment by ndouglas** [comment]
Hi, I'm the soon-to-be-former tech lead of the CMS Team and I was asked indirectly to comment with my take. Disclaimer: I haven't worked directly with `vagov-content` or workflows involving it, so my opinion is based just on the general currents and workflows and discussions that I've seen within my team, immediately adjacent teams, and with the larger VA project.

The current information is still valid, strictly speaking; `vagov-content` does still receive a trickle of new and updated content.

However, the CMS is increasingly the source of truth. It has been my understanding for the time that I've worked here that `vagov-content` is a last resort for ad-hoc data, and is deprecated for all but the weirdest cases.

I feel like this page, as it is currently written, may put `vagov-content` and the CMS on undeserved equal footing.

My suggestion would be to eliminate any mention of `vagov-content`. If new information needs to be added there, the editor in question should be specifically directed to do so, by someone who has full knowledge and awareness of what that entails and its consequences. I don't believe we should document or support the idea of adding further new content to `vagov-content`.

**Comment by BSmolensky** [comment]
@ndouglas - Thank you for providing clear and thorough notes on this ticket. That is super helpful. I will make be in contact with you in this space as I incorporate you notes. Thanks again!

**Comment by BSmolensky** [comment]
@ndouglas - I am working on this ticket this week. As I understand your instructions, the page needs to be reworded/reformatted to include ONLY Drupal and delete all mention of `vagov-content`. 

Before I begin the rewording and reformatting work, I have two questions:

1. Have the Drupal instructions changed? As currently stated in the doc, users wishing to add new content via Drupal should: "coordinate with the CMS team via your project manager." Is this still the best/most accurate instructions to give users?
2. I would love to add an "If you have questions please contact" sentence at the end of the doc. What would be the best Slack channel to post Drupal questions? (and if you think I shouldn't add an "If you have questions please contact" sentence, just say so and I will not include it). 

Thank you for your help. I hope to have a draft done by the end of the week, if not sooner. Have a great day!

**Comment by ndouglas** [comment]
>Have the Drupal instructions changed? As currently stated in the doc, users wishing to add new content via Drupal should: "coordinate with the CMS team via your project manager." Is this still the best/most accurate instructions to give users?

Yes, that matches my understanding.

>I would love to add an "If you have questions please contact" sentence at the end of the doc. What would be the best Slack channel to post Drupal questions? (and if you think I shouldn't add an "If you have questions please contact" sentence, just say so and I will not include it).

I believe the best Slack channel would be `#cms-support`. @EWashb might have a better alternative, though.

>Have a great day!

You too! 🙂

**Comment by EWashb** [comment]
I think #cms-support would be the best place for now! Thank you both for your hard work on this.

**Comment by BSmolensky** [comment]
@ndouglas and @EWashb - Good Morning to you both! Here is a link to a draft of the edits to this page: https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/2920841217/Copy+of+Creating+a+new+content+page

Please let me know if you have any issues accessing it. If you have any notes, edits, comments, ideas, corrections, or tweaks, please feel free to comment directly on the doc or thread them here in this ticket. Either one works for me. 

Once we finalize the edits, I will paste these changes and schedule the corrected page for deployment during out next deployment period. Thank you to you both for your help in making this page better. Have a great day!

**Comment by ndouglas** [comment]
Hi Brian! Looks great to me!

**Comment by BSmolensky** [comment]
Hi Nate. Thanks so much. I will get this updated tomorrow and the corrected page should get deployed on Monday (our next deployment day). Thanks again for all your help. Have a great weekend!
