### ISSUE TITLE
[Discovery] Logged-in homepage: Stakeholder interviews — Create conversation guide

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7087]
Epic #7085

We will be conducting stakeholder interviews for the logged-in homepage discovery per our [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md#stakeholder-interviews). 

## Tasks

- [x] Determine if every stakeholder needs to be asked the same questions
- [x] Create conversation guide(s)
- [x] Review with the team
- [ ] Refine as necessary

## Acceptance criteria

- [ ] Conversation guide(s) is/are complete.

**Comment by andaleliz** [comment]
Based on current stakeholder list, I don't think a "one-size-fits-all" guide will work for all stakeholders but [this could be a starting point.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/conversation-guide-stakeholders.md)

**Comment by Samara-Strauss** [comment]
@andaleliz this looks great, and I think actually could work as a one-size-fits-all guide. We can go over everyone's roles ahead of time so you can determine if you'd like to add more specifically tailored questions beforehand, or if you would prefer to add those based on people's answers in the interviews.

Some thoughts on the existing questions:

- **What does a typical day look like for you?** Can I ask what you're hoping to learn from this question? 
- **What problems have you noticed about the current experience?** I think we might need to be a little more specific here — do you mean what problems have they noticed with My VA? The logged in homepage? Both?

**Comment by andaleliz** [comment]
> What does a typical day look like for you?
I was thinking it'd be a good warm up question to grease the wheels if needed, and honestly, I don't know many of the people so I'm interested to learn more about their day to day. But, definitely not a crucial question so we can nix it.

> What problems have you noticed about the current experience?
I meant with both - I'll update to add more clarity to that.

**Comment by Samara-Strauss** [comment]
> What does a typical day look like for you?

I think we can take this question out. I think you'll get the important info you need through the first question — "Tell me about your role and what you do in your work on va.gov." — and I can also give you an overview of who everyone is beforehand so that you know what to listen out for/can add any person-specific questions you feel are necessary.

> What problems have you noticed about the current experience?

Noted! Just looked at the modification to this question and it looks good to me.

**Comment by Samara-Strauss** [comment]
@sshein

**Comment by sshein** [comment]
looks good. Can we add "What are you worried about? What do you imagine going wrong with this project?" Also we could add some specific questions for designers versus broader stakeholders (Ryan and Mel) e.g. "can you show me some of your designs and talk about why you made some of these decisions?)"

**Comment by sshein** [comment]
oh no I somehow closed this ticket with a keyboard shortcut??? can't figure out how to re-open it @Samara-Strauss

**Comment by andaleliz** [comment]
@sshein breakdown was a way for me to just work through different categories of questions as I got ideas out of my head; it's really _all_ about the logged-in homepage.  Put those all in one section now, for clarity.

Yes, can definitely add some more specific questions for designers.  Created a Practice Specific section, in case there are other specifics that I think of once I learn more about the stakeholders I'll be talking to.  Meeting with Samara tomorrow to get a better understanding of that.

**Comment by andaleliz** [comment]
Adding link to [final conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/stakeholder-interviews/conversation-guide-stakeholders.md) (was moved and updated since it was initially linked in earlier comments)
