### ISSUE TITLE
Add Kevin to flipper admin

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#70879]
## User Story
As project, I want eng leads to have access to the feature flipper admin so that they can control the rollout and testing of features.

## Tasks
- [ ] Add kevin.duensing@adhocteam.us to admin list

## Acceptance Criteria
- [ ] Kevin can manage the toggle in the [Production](https://api.va.gov/flipper/features) and [Staging](https://staging-api.va.gov/flipper/features) flipper admin

## Technical Notes
The file to update: https://github.com/department-of-veterans-affairs/vets-api/blob/448d67a4120d0743c71174b0a71ca3d4febfb4c5/config/settings.yml#L658

---
## How to configure this issue
- [ ] **Attached to an Epic**

**Comment by kjduensing** [comment]
The process for gaining modification access to feature toggles has changed: [Github groups are used now instead of a hardcoded list of emails](https://dsva.slack.com/archives/C03R5SBELQM/p1691616340610669). This is due to the feature toggle access management migrating away from id.me in favor of Github OAuth.

I'm already a member of the necessary github flipper UI access groups:
* [va-gov-flipper-prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-flipper-prod/members?query=duensing)
* [va-gov-flipper-staging](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-flipper-staging/members?query=duensing)

[More detail on the updated process is here](https://depo-platform-documentation.scrollhelp.site/developer-docs/flipper-ui-access).

**Comment by laurenernest** [comment]
Great! Closing ticket.
