### ISSUE TITLE
[Design] Auth Experience: Opportunity review of VA.gov logged in experience

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#70889]
## Background
We know the logged-in experience (authenticated experience) on VA.gov isn't great. Let's create an informal audit doc of the opportunities for improvement we see across the site. Note that this should not be a list of proposed solutions but rather the problems/challenges/opportunities we face.

## Tasks
- [ ] Review [opportunity doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/123eb1aaebf2273ffa9c744f1ddad976cd57d61f/products/identity-personalization/personalization-enhancements/opportunities.md) created earlier this year so it's fresh
- [ ] Review VA.gov and create list of opportunities. Make sure to include top task areas of the site.
- [ ] Collaborate/exchange "lists" with Liz once you're both done with your reviews
- [ ] Share list with Auth Exp team for discussion

## AC
- [ ] Opportunity list has been reviewed with team
