### ISSUE TITLE
686c and 674 PDF service is not date stamping 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#70883]
## Issue Description
We discovered an issue with the 686c and 674 PDF generation service in vets-api. It is not appropriately date stamping the forms. In addition to the date in the signature fields, forms need a stamp of when the claim was received. It should be in the top right datestamp box for the 686c. The most up to date version of the 674 also has a datestamp box, so this may be a good time to load in the new version of that form at least. When claims go through the backup process, central mail adds a datestamp to the top left, but this doesn't happen in our "normal" submission flow"
This datestamp (and the signature date) should be the date the claim was submitted on va.gov, not the date the PDF was generated (Which appears to be the current signature date logic). This is relevant in a world of backup, batches, and retries.

Current online versions of 674 and 686 extracted here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/70911

![MicrosoftTeams-image (13)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/26395703/0f204887-8647-495d-84f2-5ba94aa7b9ae)

![MicrosoftTeams-image (12)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/26395703/7b4bc949-5078-4dd6-93e8-0496e87e1962)

## Tasks
- [ ] Update date stamp logic to capture the date the claim was submitted on va.gov
- [ ] Add the date stamp to the datestamp box on the 686c pdf
- [ ] Add the date stamp to the signature date field on the 686c pdf
- [ ] Upload the new pdf of the 674 form
   - [ ] Determine if any fields have been added or removed between the current and new 674 pdf  
- [ ] Map existing 674 data to new pdf
- [ ] Add the date stamp the date stamp box on the 674 pdf
- [ ] Add the date stamp to the signature date field on the 674 pdf

## Acceptance Criteria
- [ ] Date claim was submitted on va.gov appears in date stamp box on 686 pdf
- [ ] Date claim was submitted on va.gov appears in signature date field on 686 pdf
- [ ] Date claim was submitted on va.gov appears in date stamp box on 686 pdf
- [ ] Date claim was submitted on va.gov appears in signature date field on 674 pdf

**Comment by sortizsh** [comment]
lots of conversation happened here: https://dsva.slack.com/archives/C0547Q0K0LF/p1701363523669229

**Comment by steele-lm** [comment]
Closing this ticket because this request was broken out into two separate tickets in #71125 and #71229.
