### ISSUE TITLE
Revisit Feedback Portal questions: More engaging, more quantitative

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#70909]
## Purpose
Revisit Feedback Portal to evaluate whether and how we might make it more attractive to users, and also minimize analysis load for incoming items. The hypotheses are that too many open-ended (long text) questions both increase abandonment rate by potential participants, create more burden in parsing and coding, and don't offer trackable quantitive values that are easier for leadership to track in order to see change over time.

The current Feedback Portal is intended to gather qualitative feedback, but are there methods to minimize the "open-endedness" of the questions, thus reducing load?  

## Tasks
- [x] Consider what might be causing higher abandonment within OW
- [x] Consider how to lighten load of completing the form
- [ ] Revise questions to be more selecting than writing (select categories rather than write) and better match categories in Quarterly Survey
- [ ] Review in comparison to the [Slack option](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/71680)

## Acceptance Criteria
- [ ] Recommendations
