### ISSUE TITLE
Extract 686 and 674 pdfs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70911]
## Issue Description
_In order to determine what version of the form pdf the 686 and 674 online claims are producing, we need to extract the pdf from the vets-api-pdf generator._

---
## Tasks
- [x] Extract current version of 686 from pdf generator
- [x] Extract current version of 674 from pdf generator

## Acceptance Criteria
- [x] Pdf of the 686 form provided to Laura/Julie
- [x] Pdf of the 674 form provide to Laura/Julie

**Comment by steele-lm** [comment]
[21-674.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13516566/21-674.pdf)
[686C-674.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13516568/686C-674.pdf)
