### ISSUE TITLE
Update 686 and 674 pdfs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70928]
## Issue Description
_The current pdf that the online 686c form generates through the vets.api is the Sep 2018 version. The pdf needs to be replace with the Aug 2022 version. Similarly, the current pdf that the online 674 form generates is from Jun 2018 and it needs to be updated to the Oct 2021 version._

OLD 686: [686C-674.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98e91ac128750b96cc74a17fe22746478893b712/686C-674.pdf)
NEW 686: [VBA-21-686c-ARE.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9pQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a06d0f0e8261b8951122c837e810e54d41dba3c8/VBA-21-686c-ARE.pdf)

OLD 674: [21-674.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7f2146c13d3500f3a7fb167db8fdef6a5004682/21-674.pdf)
NEW 674: [VBA-21-674-ARE.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdd0cb68e93b81bd1d8bfa5b8f01132dc808534c/VBA-21-674-ARE.pdf)

---
## Tasks
- [ ] Replace the old 686 version of the pdf with the new version.
- [ ] Replace the old 674 version of the pdf with the new version.

## Acceptance Criteria
- [ ] Claims submitted for 686 generate the latest version of the pdf.
- [ ] Claims submitted for 674 generate the latest version of the pdf.
---
