### ISSUE TITLE
Map form data to new 686 pdf

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70933]
## Issue Description
_Map existing online 686 form data to the new version of the pdf uploaded in #70928 and add missing date stamps to the VA Date Stamp field on the first page and the signature line based on the updated date variable from #70883._

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f67bef1ebe8a5ce81dc26a2f1d8ad6fd1e99f15/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEVpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c490fc2aaa8673191a5e8675a759c05c6ec4f27/image.png)

Field changes are denoted within this [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690311086208/96d5f59b299912bc8c69542e6943d5b2213b9c72?wid=0-1701370180998).

---
## Tasks
- [ ] Map online form data to new pdf
- [ ] Add submission date to VA Date Stamp field on the first page of the pdf
- [ ] Add the submission date to the signature line on page 14 of the pdf

## Acceptance Criteria
- [ ] All existing 686 form data appears correctly on the pdf generated by vets.api
- [ ] The submission date appears in the VA Date Stamp field
- [ ] The submission date appears on the signature line
---

**Comment by evansmith** [comment]
@steele-lm I'm going to reopen this just because the unit tests aren't quite finished.
