### ISSUE TITLE
Update 686/674

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70947]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Veteran and the VBA, I need my claim to be submitted as the latest version of the 686 and 674 pdfs with the correct submission date included on the pdf, so the claim can be processed as quickly as possible.

## Hypothesis or Bet
**If** update the pdfs for 686 and 674 **then** claims will be processed more quickly and with more accurate information.

## OKR
 - Claims in minutes not months

## Definition of done
- [ ] 674 claims generate the latest version of the pdf form
- [ ] 674 claims include an accurate submission date stamped on the first page and signature page of the pdf
- [ ] 686 claims generate the latest version of the pdf form
- [ ] 686 claims include an accurate submission date stamped on the first page and signature page of the pdf
