### ISSUE TITLE
Secondary nav designs for research

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70946]
### User story

As a Cartographers team member, I want to get our team and OCTO design leads aligned around designs and direction for cross-tool navigation, so that we can move toward research study as quickly as possible.

### Notes
- Discussed in UX sync on 11/30
- Landing page tweaks might be inspired by the "4 boxes" from the national portal
- It would be nice to understand how exposed the designs are to IA churn at the tool level
- National portal GA analysis has been started: [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701186817946/7616950c143ed34bddc023f549f3bc78f99ff7be?sender=uebde62ceb342c6477fb09406), [Excel](https://agile6-my.sharepoint.com/:x:/p/florence_mccafferty/EYaT1hUxQzBMrzA01kGy-ygB4Xr6y3Y6w1eRbbJovhzSNA?e=4hzdN7)

## Acceptance criteria

- Documented quantitative GA analysis of how Veterans use MHV NP "4 boxes" (header vs sub-item clicks)
- Identified hypotheses/questions from previous round of research that need study
- Designed 2-3 options for secondary nav, ~including any landing page updates needed for each~ _[edit: removing emphasis on landing page as it's of secondary concern]_
- Obtained PO and OCTO design lead alignment on research direction
- Scheduled Design Intent meeting with Collab Cycle

## Tasks

- [x] Pinged Cindy Merrill about previous megamenu studies ( @AngelaFowler82 )
- [ ] Document National Portal analytics so that we can understand top clicks on: landing page, navigational components, etc. ( @fmccaf1) 
- [ ] Looking up past research studies for Secure Messaging to understand any issues we should be aware of there. How will we expose child pages on that tool if we go with the persistent horizontal nav bar strategy? ( @sterkenburgsara )
- [x] Ticketed next steps (with Wes help), e.g. prototyping in codepen, writing research plan and discussion guide

**Comment by wesrowe** [comment]
This ticket could use links when they're available (ie Sketch), but otherwise can be closed at the end of the sprint.
