### ISSUE TITLE
Spike | Requirements Gathering for Submission Metadata

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#70944]
Currently, 526 is the only claim type that persists data after claim submission. This data is required to be able to poll the Benefits Intake API. Additionally, this Record should contain sufficient information for a developer to rebuild and resubmit a claim as required for remediation efforts

Proposed schema:
Mandatory Fields - 
- form_type 
   - which form type was submitted
- benefits_intake_id
   - The Benefits Intake API ID, used as backup submission key for some claims, primary submission for others.

Needed to remediate claims
- user_account_id
   - Veteran Identifier, can be converted to UUID, IDME UUID, ICN, EDIPI, which gives us access to most veteran information
- form_json
   - The data from InProgressForm that represents the Veteran's submission 
   - In Progress Forms are deleted 60 days after last access date for all forms but 526, so we are persisting here to ensure we can remediate claims. 
   
Extras that not every form needs
- saved_claim_id  
   - The data converted from in progress form. not used by Simple Forms
- in_progress_form_id
   - for use by simple forms 
   - purged by forms that used SavedClaims upon submission
- submitted_claim_id
  - used by EVSS/Lighthouse Claims/BIS

## Acceptance Criteria
- [ ] Active Record Schema Defined
- [x] Approved for Dependents (686C/674)
- [ ] Approved for Disability (526EZ)
- [x] Approved for CH31 (28-1900)
- [x] Approved for CH36 (25-8832)
- [x] Approved for Pensions  (527EZ)
- [x] Approved for Burials (530)
- [x] Approved for CoE/LGY (26-1880)
- [x] Approved for Simple Forms 
- [ ] Approved for Decision Review (20-0995)

**Comment by Thrillberg** [comment]
Thanks for opening this @tblackwe ! I'm assuming that we're proposing another database entity beyond what 526 is already doing? Or is this meant to augment 526's data to be able to be used by other forms?

If the former, what name would this table have?

For the proposed fields, is it possible to steer away from "claim" terminology toward "form"? I think "form" is more generic and not all of our (Simple Forms) forms are claims, I believe. So `claim_type` might become `form_type`? On this type field, would that indicate a form id (like `21-0845`) or something else? Otherwise I love the fields!

We'd want to use it for all of our simple forms:
21-4142
21-0845
26-4555
21-10210
21P-0847
21-0972
...and much, much more!™

**Comment by tblackwe** [comment]
@Thrillberg will there be any variation on requirements for the Simple Forms? or can I simplify the approval?

**Comment by Thrillberg** [comment]
@tblackwe Nope, you can simplify the approval to blanket all Simple Forms. Thanks for the claim vs form update!

**Comment by tblackwe** [comment]
I am ok with ditching those two. removed from schema.

**Comment by SamStuckey** [comment]
I have a couple blocking questions for @tblackwe  or whomever can answer them

# 1
can you give me more context on the proposed:
- benefits_intake_id: The Benefits Intake API ID, used as backup submission key for some claims, primary submission for others.
Specifically, what kind of data is this?  is it a limit set of values?  Seems like it would be string and yes but i want to be sure

# 2
re the user_account_id.  This value is a 'foreign key'  pointing to the UserAccount table.  However, it's also a string, which means joins on this have the potential to be incredibly slow.  Additionally, the Account model actually holds the values you referenced, ie. UUIS IDME etc, so a foreign key pointing to that record seems more reasonable. This would break the paradigm set by Form526Submission, but tbh i don't really know what the UserAccount model is even for.  help?

# 3
what does this mean?  is saved_claim_id a foreign key?  the description of it as "converted data" is confusing me :thinking-rotating: 
  - saved_claim_id: The data converted from in progress form. not used by Simple Forms

# 4
The second sub-bullet here is also confusing me here. can you clarify?
- in_progress_form_id:purged by forms that used SavedClaims upon submission

**Comment by tblackwe** [comment]
On several claim types, when the SavedClaim is created, the related InProgressForm is deleted.

So the value is important for Simple Forms, but not helpful for 686/Burials/etc

**Comment by tblackwe** [comment]
Requirements met, closing ticket.
