### ISSUE TITLE
Map form data to new 674 pdf

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70942]
## Issue Description
_Map existing online 674 form data to the new version of the pdf uploaded in #70928 and add missing date stamps to the VA Date Stamp field on the first page and the signature line based on the updated date variable from #70883._

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/7ea087ff-e11f-4638-aa1a-a4963b05baba)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/d9d8d481-7e77-4ba8-96f6-0325f8fde004)

Field changes are denoted within this [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690311086208/96d5f59b299912bc8c69542e6943d5b2213b9c72?wid=0-1701373901961).

---
## Tasks
- [ ] Map online form data to new pdf
- [ ] Add submission date to VA Date Stamp field on the first page of the pdf
- [ ] Add the submission date to the signature line on the last page of the pdf

## Acceptance Criteria
- [ ] All existing 674 form data appears correctly on the pdf generated by vets.api
- [ ] The submission date appears in the VA Date Stamp field
- [ ] The submission date appears on the signature line
---
