### ISSUE TITLE
[FE] My VA Bene app drafts: Incorrect date formatting in benefit application drafts section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#70952]
## Background
A user reported having already submitted a form 526 (disability compensation) form, but it was still showing up on My VA in the Benefit Application Drafts section and with an expiration date and last updated of 1969.

[More info in slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1701366301816869)

## Tasks
- [x] Correct date/time issue
- [x] Test
- [x] Move to validate

## Acceptance Criteria
- [ ] Date and time stamp formatting is corrected

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_

**Comment by allisonlu** [comment]
this fix should be on staging now! we just need to find a staging user with at least one application in progress

**Comment by ajakabcin** [comment]
@allisonlu thank you! User 10 has one, I'll see if I can find some others.

**Comment by ajakabcin** [comment]
Confirmed with user 10 and user 226 - thanks @allisonlu
