### ISSUE TITLE
Implement changes to Experience Standards based on Design System SR

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#70956]
## User Story
As a Governance team member, I want to make some minor adjustments to the Staging Review process per the new VA.gov Experience Standards so that VFS teams are giving us valuable feedback in the pilot and not pointing out things we already know.

Assignee: @rferguson13 
Peer Reviewer:

## Description
On January 19, 2024, Governance team hosted our first Staging Review using the new Experience Standards with the Design System team for their search component. Since DST is not considered a VFS, we didn't include them in our pilot, however we still learned a lot from the experience and recognized we need to make a few adjustments to our process before running the pilot with an actual VFS team. Discussion took place in this [Slack thread](https://dsva.slack.com/archives/GNF5GSD9N/p1705691672526929), and the changes we will be making include:

- Update the[ How to Generate Staging Review issue tickets ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)guidance 
   - Note that this should be applicable for both VFS and DST - no need to have 2 guidance docs
- Update the QA section of the Design System SR script
   - validate changes with Ian
- Edit the DST DraftingTemplate for the "Next Steps for the VFS Team section"
   - Possibly include a link to the High-priority vs. priority vs. considerations guidance on Confluence (DST is Platform crew so they can access Confluence docs)
   - This section should not be included for Consider items, or their should be Consider-specific Next Steps 

**Note:** Governance team is simultaneously working on ticket #73800 to kick off the pilot. Please be sure to coordinate with the assignee and PR for that ticket to ensure we're in alignment on all changes.

## Tasks
- [x] Update the[ How to Generate Staging Review issue tickets ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)guidance 
- [x] Update the QA section of the Design System SR script
- [ ] Edit the DST DraftingTemplate for the "Next Steps for the VFS Team section"

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@erinrwhite I'm realizing now that you may have already updated the How to generate Staging Review issue tickets guidance! Can you please verify? If so, I will tweak this to include updating the How to generate doc to be reflective of DST process as well.

**Comment by erinrwhite** [comment]
@shiragoodman yes indeed - that page is already updated!

**Comment by rferguson13** [comment]
@shiragoodman Question: How do I go about updating the "Next Steps for the VFS Team" section? I don't see it in the Drafting Template itself. Is there a GitHub template that I need to edit?

**Comment by shiragoodman** [comment]
@rferguson13 that's something I will have to do in the code of the DraftingTemplate. If you're curious to learn, let me know and I can set up time to share with you how I make the updates. 

For now, please focus on updating the DST SR script re: QA, and review the How to generate Staging Review issue issue tickets page (for 2.0) to identify where changes are needed to be reflective of the DST ST process, and propose changes. For example, Step 2 is for verifying integrity of the data. That same steps occurs for DST SR but it's different data we're looking for (VFS product vs. DS component name). If you think having both VFS and DST guidance in 1 doc is too much, let me know and we can figure it out from there.

**Comment by rferguson13** [comment]
@shiragoodman Sounds good. I'll get to it today.

**Comment by rferguson13** [comment]
Hi @shiragoodman - since there's no peer reviewer, I'm tagging you. These are ready for review - I talked with Ian and reworked the DST SR meeting script; I also added a DST section for generating staging review tickets. 

- [How to generate Staging Review tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2920841230/70956+-+How+to+generate+Staging+Review+issue+tickets)
- [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)

**Comment by shiragoodman** [comment]
thanks @rferguson13 ! I will take a look soon :)

**Comment by shiragoodman** [comment]
@rferguson13 I provided comments in the How to gerenate SR tickets guidance. Tagging @erinrwhite as well since I think some of my comments may be applicable to the VFS section of the guidance (aka DraftingTemplate 2.0).

You also linked the design System SR - scheduling doc. I'm not sure why... The change we needed to make was in the script which is part of the Design System SR - during the meeting guidance. Can you please verify?

**Comment by rferguson13** [comment]
@shiragoodman Got my wires crossed. Here's what should have been linked: [Design System Staging Review - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2827943944/Design+System+Staging+Review+-+During+the+Meeting)

**Comment by shiragoodman** [comment]
@rferguson13 per standup, I will be talking about QA's role within the DST SR with Matt tomorrow at our 1:1, and will follow up afterwards!

**Comment by shiragoodman** [comment]
@rferguson13 this is good to close - thanks for making the QA changes!
