### ISSUE TITLE
Update health care copay rates for January 1 2024

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#70953]
## Issue Description

Update rates on [VA health care copay rates page](https://www.va.gov/health-care/copay-rates/)

The stakeholder is now VHA Finance/Revenue Operations, so Cindy is looping them in to the request. Waiting to hear back if we can plan to publish Dec 20 (to accommodate our OOO plans).

---
## Tasks
- [ ] Gather rates from stakeholder (Lily)
- [ ] Update rates page
- [ ] Copyedit
- [ ] Publish
- [ ] Notify stakeholder (Lily)

## Acceptance Criteria
- [ ] Updated rates are live
---

**Comment by chelsealevinson** [comment]
Confirming I copy edited and published this page. I also noticed that the Past rates: 2023 page wasn't on this ticket, but needed to be published. I consulted with Randi, and copy edited and published [the past rates page](https://preview-prod.vfs.va.gov/preview?nodeId=64127) too, along with updating the left nav and menu. Randi will alert stakeholders. Thanks all!
