### ISSUE TITLE
Investigate and Familiarize Self with GitHub Project Board

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#70963]
## Description 
This ticket will house the task of us familiarizing ourselves with GitHub Project Board. Tim Cosgrove is a SME on the topic if needed. This tool will replace the Zenhub Board we have currently. You can find more information about this tool here: https://docs.github.com/en/github-ae@latest/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Alyssa to read through documentation on GitHub Project Board
- [ ] Joe to read through documentation on GitHub Project Board
- [ ] Create a ticket to implement this tool and put it into the backlog

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
We will be trained on this tool in our Product CoP. Closing.
