### ISSUE TITLE
Create Slack Auto-Response for OOB

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#70970]
## Issue Description
When someone asks for an OOB deploy there often seems to be a lot of questioning happening back and forth in the slack thread to get more context. Is there a way we could require that info at the point of the request?

---
## Tasks
- [x] Create Auto-Response in Slack for Topic ID #20: Off Cycle Deployment requiring user to fill out field to provide context to the situation
- [x] Keep other components in place (ie. Team Assignment does not change)
- [x] Create OOB (out of band deployment) label in GitHub
- [x] Auto-assign OOB GitHub label to any ticket created using Topic ID #20 from Slack

## Acceptance Criteria
- [ ] Auto-Response created and tested
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
This will be sprint work and will require Reliability Team

**Comment by alyssagallion** [comment]
Curt implemented this feature in our Slack Bot changes here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/65230
