### ISSUE TITLE
Intake new Trexler File on 12/1

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#70974]
We receive a weekly Trexler File from Randy at OGC so that we can continue to keep the rep address and email information up to date.  This ticket is for receiving this weekly file and making the necessary updates in our Find a Representative backend.

### Tasks

- [ ] Download the new Trexler File from the Drop Location (accessed through the VA Network in Teams: OITSPM GCLAWS-VBA Integrations team > ABD (VASI 2823) Accreditation Interface thread > Files tab)
- [ ] Email the new Trexler File from your va.gov email account to a preferred email account, to manage outside of the VA network
- [ ] Sanitize the spreadsheet to remove unnecessary data
- [ ] Add the new Trexler File to the GitHub `department-of-veterans-affairs` organization’s `va.gov-team-sensitive` repository

Sidekiq is setup so that it will be looking for new files within 24 hours.  It will pick up this file in the evening and update our backend database with any new information.

**Comment by oddball-lindsay** [comment]
This was supposed to come in by 3p ET but I don't see anything yet.  If I don't see anything on Monday I will reach out to Randy

**Comment by oddball-lindsay** [comment]
I'm bad at dates and there was a file for 11/30 -- uploaded a day before expected.  Thinking we can close this out since Holden is out and just pursue the next 12/8 task - https://github.com/department-of-veterans-affairs/va.gov-team/issues/70975
