### ISSUE TITLE
Outline Key pages needed

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#70986]
## Purpose
Establish starter mini site within SD Confluence to use to build out the Landing.  This can be our proving ground to help us see what we have and what we need.

(Or should this be in the Platform website Drafts space in Confluence? Can get comments and feedback in this space, then once ready, route it to right section for publication.)
 
Frame out the Key pages needed

[Landing page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2856943641/Forms+Digitization+Guidance+landing) and child pages from it

## Tasks
- [x] Document the key spaces needed within the landing 
   - [x] The main Phases of FD (use [Galactus](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1689261269705/e41962a805581be8f08b6b1a79d934ae227d9d68?sender=u4397b715dc3690a417b71483) timeline and [Best Practices](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1697552616233/fb1436b83b73c91a51904a3745350b4372717f59?sender=u4f7db1750f2355f805e60296))
   - [x] Resources space?
   - [x] Recent Updates space?
   - [x] Sub pages?
   - [x] Forms Library explanatory page?
- [x] Create placeholder versions of each space/phase (this is just a page w/ title and maybe subheading)
- [x] Review and revise in light of page content 

## Acceptance Criteria
- [x] Placeholder pages will be in place for each defined space/phase
- [x] Placeholder pages for any other key spaces needed
- [x] Confluence test space is setup w/ pages

**Comment by twoangstroms** [comment]
Rolling over to next sprint; just needs review and revision

**Comment by steel36** [comment]
Additional steps were not captured in tasks.  Will roll over to next sprint.
