### ISSUE TITLE
Usability Test the FDG landing - create test plan and schedule

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#70999]
## Purpose:
Perform Usability Testing on new landing.  We want to ensure that it is easy to absorb and effective in its aim to educate users on the major phases and best practices.

**For reference:** [Notes from SME reviews Feb - Apr 2024](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3038446295/SME+Reviews+and+Conversations)

## Tasks
- [x] prep [test plan](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3267592193/Research+Plan+-+Testing+FDG+v1.1+Landing) (aim for up to 5 participants)
- [x] create [conversation guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3296821277/Conversation+Guide+FDG+Landing+Test)
- [x] recruit users
- [x] schedule test sessions

## Acceptance Criteria
- [x] test plan is ready
- [x] sessions scheduled

**Comment by twoangstroms** [comment]
Already spoken to about IR for OCTO/PO SME: Beth Potts (who shared with Danielle on her team), Shane Strassberg, Rachel Han.
