### ISSUE TITLE
Select a desirable location for the FDG space to exist within Platform Docs

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#70993]
## Purpose
Another tenent from our [own internal standards](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2210660360/How+to+Service+Design+Your+Tool+Service#1.-Make-it-easy-to-find-your-service) is findability.  Where is the best spot within Platform Docs IA for users to find this when looking, or wandering?

Let's also discuss this w/ Platform Content

## Tasks
- [x] Consider location options: [writeup](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3063971861/Where+shall+we+house+the+FDG)
- [x] Discuss options w/ team to filter toward a preferred option
- [x] Document choices and reasoning
  
## Acceptance Criteria
- [x] choice documented
