### ISSUE TITLE
Create imagery to support steps/wayfinding

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71000]
## Purpose
Let's include suitable graphics to make things more approachable, avoiding walls of text.
Here's the [working Figma document](https://www.figma.com/file/CeTfz0SmO0QTf00kx9SD4o/FDG-Wayfinding-Imagery?type=design&node-id=0-1&mode=design&t=sj1rahiQkhiN81Gw-0).
Here's the [_more organized options_ document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3118989313/Create+imagery+to+support+steps+wayfinding) in Confluence.

Examples:
<img width="571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54bc082fafe04b897a85fc4686c74465411de62f/image.png" alt="image.png" />

<img width="750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd1f891a3750d8bea9fb43e6bd81d4b3457a2920/image.png" alt="image.png" />

## Tasks
- [x] Create graphic of entire process (perhaps a graphic along the top of phase pages that highlights the phase where you are?)
- [x] Create graphic for each phase
- [x] Team review of [options ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3118989313/Create+imagery+to+support+steps+wayfinding)
- [x] Revisions made from feedback
- [x] Final [vote](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3118989313/Create+imagery+to+support+steps+wayfinding#Last-voting-round)
- [x] Insert phase page graphics into [respective pages](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2907111425/Forms+Digitization+Guidance+landing+-+test+bed)

## Acceptance Criteria
- [x] Graphics created and added to respective pages

**Comment by twoangstroms** [comment]
Let's talk about this to clarify. This isn't a journey map, but less granular, kind of like the Collab Cycle graphic?
