### ISSUE TITLE
[Backend] Populate test user data for participants 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#7100]
## User Story or Problem Statement
As a research participant testing the medical device reordering system I would like to see my own data populated - however to protect PII I would like to log in with a test user credentials. 

## Goal
_A test user account populated with data from research participants. 

## Tasks
- [ ] _Get participant's names and unique identifier from research team
- [ ] _Tie participants data with test user and populate data 

## Acceptance Criteria
- [ ] _On test user to one participant with real data on log-in 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
