### ISSUE TITLE
Insert bug graphics into phases

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71001]
## Purpose
Include graphics to visually highlight Best Practices and Pain Points.

Brainstorming, tracking, and voting [document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3105980489/Add+visual+bugs+for+topic+readability+in+FDG+Phase+pages)

## Tasks
- [x] Test whether these are supported by Platform docs (create some and put it in the test space to see if it works)
- [x] Create "bug" graphics for Best Practices
- [x] Create "bug" graphics for Pain Points
- [x] Consult with Accessibility Specialist on image use
- [x] Go/no-go for "bug" in column headers
~- [ ] Insert "bug" graphics for Best Practices~
~- [ ] Insert "bug" graphics for Pain Points~
- [x] Make a pass to evaluate if other visual enhancements are needed

## Acceptance Criteria
- [x] Graphics developed
- [x] Graphics usage evaluated
- [x] Any other enhancements tested
- [x] Tested enhancements placed

**Comment by twoangstroms** [comment]
Carrying over to next sprint
