### ISSUE TITLE
Veteran Status Use Case Discovery 

### ISSUE THREAD

**Issue by carafrissell1** [department-of-veterans-affairs/va.gov-team#71004]
**Summary** 
This qualitative study will explore how and when veterans use veteran discounts at retail service providers. We will learn more about how and when veterans use veteran specific discounts in retail stores and non-VA health care providers; what their current process is (when, where, medium, etc), what tools they use and what stumbling blocks they encounter.

 [GitHub folder ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/16d17777da46915b2b176740f26723cbfe1c7d7c/products/veteran-status/Research/2023-12-VetStatus-Use-Case-Discovery) with research artifacts

**Tasks**

- [ ] Align on plan and guide
- [ ] Submit for ReOps review
- [ ] Recruitment KO with Perigean 
- [ ] Pilot user test 
- [ ] Create analysis boards and docs
- [ ] Run sessions
- [ ] Analysis 
- [ ] Present / shareout 
- [ ] Ensure GitHub and ReOps tickets are up to date 

**Definition of Done**  

- [ ] Sessions were conducted 
- [ ] Analysis complete
- [ ] Analysis and findings presented in appropriate forum
- [ ] All relevant documentation is up to date

**Comment by Samara-Strauss** [comment]
To make it easier to keep track of, here is my feedback [from Slack](https://dsva.slack.com/archives/C061RNJQ6SE/p1701441330219269?thread_ts=1701291988.456319&cid=C061RNJQ6SE):

> Just finished reviewing -- I have no feedback for the research plan. I agree with the scope of the research and appreciate that it's being kept high-level. My feedback for the conversation guide:
> 
> - Question 3 -- what veteran IDs people have an how they use them -- is a hugely important question. I wanted to highlight that extra attention should be given here, since this is a key part of understanding the veteran status tool within the landscape.
> - I want to make sure we are able to assess how people prove -- or if they even need to prove -- that they are a veteran to access veteran discounts. I think this might come up in the line of questioning, but since it is not explicitly asked, I wanted to call it out.
> 
> Looking forward to seeing what comes out of this!
>

**Comment by pamela-drouin** [comment]
@andaleliz and I have consolidated our feedback below 🤓

## Research plan - recruitment

> I have never been denied an available veteran discount

In the `#4` screener question, this response disqualifies a potential participant. What’s the reasoning behind this? Just curious about your approach, because I wonder how much it might constrain the participant pool.  
 
> We will keep track of participant demographic information (identified gender, age, ethnicity, cognitive abilities) and other relevant information in an encrypted Excel file on the VA Network.

I don’t believe Perigean tracks info about cognitive abilities by default, so you may have to write a screener specifically for this. I’d also recommend being specific with them about what participant data you want captured in the roster PDF.  
  
> Ideally at least 3 participants use Assistive Technology

Are you looking for _any_ type of AT, or screen readers specifically? I might think about writing a specific screener question for this to be sure you get what you’re looking for. Perigean can surprise you :)  
  
> Do you have a Veteran Identification Card?

There are a lot of [different types of ID cards](https://www.va.gov/records/get-veteran-id-cards/), so it might be helpful to get more specific with this question or add helper text if you are specifically looking for people with the [VIC card](https://www.va.gov/records/get-veteran-id-cards/vic/). I know you’re also asking them about this in the convo guide, but you could also add an open text box after to have people type in the kind of card they have. That would an interesting data point, to see how they describe them in their own words in advance of the session.  
  
> Do you have and use the VA Mobile App?

There are so many VA/VA-adjacent mobile apps; similar to the ID card, you might want to add helper text to describe specifically what you’re looking for. It sounds like you’re only interested in people who use the Flagship app we’re most familiar with.  
  
## Conversation guide

- Love how the follow up questions are in code blocks, that’s such a nice way to distinguish them for the moderator. Definitely going to borrow that!
- Last I heard, there hadn’t been any research completed on the Veteran Status page in the mobile app. If there is time in your session, and you’re talking to someone who uses the flagship app, it could be really interesting to talk to them about it and hear their thoughts. You never know what they might say that could be helpful to inform the work on the web.

**Comment by carafrissell1** [comment]
Ok all thanks for the feedback! Responses below.

Samara:
 1.  Appreciate the call out on the complex landscape of ID cards.  I've added a note on what to probe for to make sure it doesn't get overlooked in real time.
 2.  Yes, agree, that's very important.  The notes on what to probe for on Q8 and 9 should make sure we hit those topics in those stories.
 
Pam and Liz:
1. Screener Q4 - I think understanding when something fails is important to understand what it needs to be successful.  The way the convo guide is set up, it contrasts a successful incident and a critical incident.  My hope is that that comparing and contrasting those two outcomes will reveal more than just looking at the successful outcome.  I know that this may create recruitment issues, and if it does we can pivot, but I'd rather start from here and modify.  
2. Thanks! Removed that wording
3. Added some clarification about visual AT, such as a screenreader.  I'll also cover this in the KO with Perigean and adjust the wording if they have any feedback.
4. Good call out.  I added some explainer text and a link to the VIC application process.  I'm also planning to cover this in my KO with Perigean.
5. Yes, that's accurate.  Here I also added some explainer text and a link to the VIC application process.  I'm also planning to cover this in my KO with Perigean.  I know mobile has found that to be helpful.

Ok all! Thanks for the feedback.

**Comment by pamela-drouin** [comment]
Thank you for explaining your approach to screener Q4! That does make a lot of sense and seems worth trying.
