### ISSUE TITLE
Add clinic phone number to appointment details

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#71009]
## Task Description
Update appointment details to show clinic phone number and extension, where applicable. Currently VA appointments show the main facility phone number.

## Notes and References
Questions:
- Which appointment types should show the clinic number instead of the main facility phone number?
- Are there situations where we should show the main facility number along with the clinic number in the same details.
- How do we show TTY?

## Assumptions:
- This does not apply to requests; these should still show the main facility phone number.
   - Is this true? Should Veterans be calling the clinic to ask about requests? I thought these were processed at a higher level, but maybe not.
- This does not apply to CC appts or requests - clinic phone number is a VA data point 
- Let's assume we always have the clinic phone number
- We should show only clinic phone number 

## Acceptance Criteria
- [x] Clinic number has been tested during research
- [x] Dev specs for clinic number have been created
- [x] Clinic number has been added by dev

## Deliverables
- [Figma Design Link ](https://www.figma.com/file/7fnXSBQ6FZ8HMDaPJXUMn7/Add-clinic-phone-%23-to-appt.-details-%7C-Appointments-FE?type=design&node-id=1%3A51&mode=design&t=vJZ4i04ZZRLfcsB9-1)

## Relevant dev tix

- [Backend services ticket: #7546](https://issues.mobilehealth.va.gov/browse/VAOSR-7546). - Done
- [Appts FE Ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/80375)

**Comment by outerpress** [comment]
@Cieramaddox to check if any design work is needed, and if there's any dev tix related to it

**Comment by Cieramaddox** [comment]
Dev ticket can be found [here](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/69444)

**Comment by outerpress** [comment]
SPL team is working on a VAOS-R ticket to expose the full phone number and extension on the FE before this can move forward. @ldelacosta could you link the VAOS-R ticket?

**Comment by ldelacosta** [comment]
@outerpress - here's the [VAOSR ticket #7546](https://issues.mobilehealth.va.gov/browse/VAOSR-7546). The BE services team will work on it next sprint. Will let the team know when it's available in staging. Thanks!

**Comment by ldelacosta** [comment]
Here's the FE ticket [80375](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/80375)

**Comment by outerpress** [comment]
Closing the design ticket, dev ticket is done and this is on prod! Fyi @Cieramaddox
