### ISSUE TITLE
Prepare for Design Sync presentation on FD research

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71014]
## Purpose
Prepare for 12/11 Design Sync presentation on FD research

## Tasks
- [x] schedule sync session to go over gameplan
- [x] tweak deck as needed
- [x] decide upon agenda

## Acceptance Criteria
- [x] props ready
- [x] agenda ready
