### ISSUE TITLE
Brainstorming workshop on closing loop to improve user satisfaction

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71016]
## Purpose
From PO ask:  https://vfs.atlassian.net/wiki/spaces/SDT/pages/2854551553/11+30+23+-+PO+PM+Sync+log

**How Might We take what we measure and make it Actionable, and “close the loop” that things are being acted on?**
-thinks things from Survey get taken in one ear and out the other
-Would like team to brainstorm on how to improve on item #2:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab9cef0a630571a4592ad843514509d05bcc7519/image.png)

Matt: maybe now that it’s been asked, he could present on it each qtr and say “here’s what we’ve learned, what are you (octo) doing about it?”
-might result in follow-up questions, leading to more research from our team
-or does Octo want us to automatically research things we hear about?

Close the loop, being able to say that “we did this because you (VFS) told us to.
Sometimes it’s just telling the story of “your feedback is absolutely valid” but…
We don’t really paint the story for users of what we’re prioritizing, and what we’re not right now, and why
     Thinks SDT could help define a process of being transparent about what OCTO is doing/prioritizing.
          And then hold us (OCTO) accountable
               “We should just be honest about all that”
          Offsites is generally when we go through the priorities

[Notes ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2898657340/Notes+from+2023+Q4+Satisfaction+Survey+Readout)from recent Survey Readout

## Tasks
- [x] schedule session
- [x] prep [Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1705940480563/3839a394a304da9982c97d60aa8a5a31396b94ed?sender=u4397b715dc3690a417b71483)
- [x] hold workshop
- document findings/takeaways
   - [x] Problem 1's [takeaways](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2923168036/Closing+the+Loop+on+Feedback+mechanisms)
   - [x] Problem 2's [takeaways](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2924609537/Closing+the+Loop+on+Feedback+mechanisms+-+Problem+2) 
- [x] Final pass, ensure needs are captured
- [x] share w/ Matt for any additional desirables
## Acceptance Criteria
- [x] Plans captured
