### ISSUE TITLE
How might we create a space for known bugs/gaps

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71017]
## Purpose
How can we create a space (bug bounties) for the things we know are gaps?

[PO Ask](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2854551553/11+30+23+-+PO+PM+Sync+log#4.-Another-idea-we-could-help-with%3A-(and-near-the-thought-of-%E2%80%9Cwhy-don%E2%80%99t-folks-contribute-to-the-Design-System%3F))
-step indicator example: works great w/ simple forms, but not for complex forms
-or need for more prominent active links: so they don’t disappear in walls of text

So how can we have a place where teams can post these asks, and other teams/individuals can see and move to help with these?

What sort of research would we need for this? What sort of working with the PCT would we need?

**thoughts:**
where might this live?
who would engage w/ this space
makers?
requestors?
how to incentivize folks to work on them?
who would own/manage this?

Recent Feature Requests seem like the might belong in such a space
Would we break these up by categories, spaces, or what?

## Tasks
- [ ] schedule brainstorming session
- [ ] discuss in workshop
- [ ] capture thoughts

## Acceptance Criteria
- [ ] thinking/next steps documented

**Comment by tayism** [comment]
There is a bug reporting system now in place at the top of the design system page.
