### ISSUE TITLE
Documentation Update - 'Getting help from the Platform in Slack'

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#71013]
## Description
This ticket is for the Content Team to review the language we have around contacting support. This was flagged during the process of adding instruction on submitting a ticket on getting access to PagerDuty. This will likely be broken into two parts, 

- "**One-** what can we do on the Support Team to request the information needed at the initial point of ticket creation."
- "**Two**- what documentation can the Content Team provide to support that."

_Reference [this ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/70262) for further context on this._

**Page:** [Getting help from the Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack)

The Support Team has already began updating some documentation on this in this space.

## Tasks
- [ ] Review needed changes with someone from the Support Team, (either Brandon Dech, or Alyssa Gallion)
- [ ] Work with them to make edits on the [Getting help from the platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack) page.
- [ ] Prepare page for deployment

## Acceptance Criteria

- [ ] Page has been updated with new Slackbot screenshots, and Support Guidance
- [ ] Page has been reviewed/signed-off by the Support Team
- [ ] Page has been redeployed with updates

**Comment by johnny-jesensky-adhoc** [comment]
Connected with Alyssa and Joe Knipes on this on Wednesday, December 13th. They were going to finish making updates to the [internal version of this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices), then connect with us to get the Platform Website version updated.

Until they are ready, this is momentarily paused.

**Comment by jknipes** [comment]
Closing ticket per @alyssagallion , page has been updated
