### ISSUE TITLE
Burials | Implement Unique Lighthouse API Key

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#71021]
Dependents, Disability, and SimpleForms currently use the same API key for document submission, creating a tracking issue within the Lighthouse team. They have asked us to implement unique keys per form

Acceptance Criteria:
 - [ ] Staging env Key assigned by Lighthouse Team
 - [ ] Prod env Key assigned by Lighthouse Team
 - [ ] Key added to AWS for lower tiers
 - [ ] Key added to AWS for production
 - [ ] Keys updated in devops repo Settings definition
 - [ ] Burials Specific API key passed to Benefits Intake Service

**Comment by tblackwe** [comment]
Iceboxing until we get around to implementing Benefits Intake for Burials

**Comment by lisacapaccioli** [comment]
@tblackwe  - Is this a Carb ticket? The Epic shows "carbs" on all but this one and since it's Burial I thought I should ask. Thanks

**Comment by tblackwe** [comment]
Closed, lighthouse asked us not to move forward
