### ISSUE TITLE
FE | General Maint | Notification Settings: RX Facilities Updates

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71025]
### Background

Justin Wowk (VEText product manager)[ messaged that a new facility has been added to the Rx shipment notifications:](https://dsva.slack.com/archives/C909ZG2BB/p1701442193670529)

- San Francisco (662) 

We need to add this to the gate that determines who sees the prescription shipment notification preference.

### Tasks

- [x] Add San Fran (662) the list of facilities that see the prescription shipment notification preference.
- [x] Double check list to make sure no other facilities are missing. [VEText_Rx_Active_12012023.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13530450/VEText_Rx_Active_12012023.xlsx)
- [x] ¿¿¿¿¿¿Do we do anything to build a process to check the [power BI report ](https://app.powerbigov.us/groups/me/apps/edb20dd9-adff-4cdb-9e08-35ecc7e2ea94/reports/44d4a7e8-0c78-4498-941c-066651f4042c/ReportSection?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf)Justin shared to make updates more automatic????

### Acceptance criteria

- [x] New facility has been added to the prescription shipment notification preference.
- [x] I don't think there is a way to validate this through a specific user, so you can just test locally and let us know when this work is complete.

**Comment by adamwhitlock1** [comment]
@mtcA6 This one is now in PR, and there were quite a few updates to do to the list... so I'm not sure the best way to handle this so that updates don't slip under the radar.

Since the Power BI report is guarded via VA login, I don't see an easy way to programmatically access this list, so maybe the best course of action is to set up like a monthly check in ticket to view the report and update the code with any new facilities? That's not ideal, but im open to thoughts.

I don't think we need to roll this over into next sprint as far as points go, and I will work on getting this approved and merged asap tomorrow.

**Comment by mtcA6** [comment]
I'll add a reminder to the team calendar to check the powerbi report the first of every month starting in February that way we grab this and create a ticket for it.

**Comment by adamwhitlock1** [comment]
Cool this is merged, so im going to close this one out. Thanks @mtcA6 !
