### ISSUE TITLE
[FE] My VA BAD section: Update "last opened" date to align with form language

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#71028]
## Background
As [Liz pointed out to us in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1701289759938769?thread_ts=1701205677.876489&cid=C909ZG2BB), the language in the open application draft cards within the Benefit Application Drafts section on My VA is different from what a user sees on the form/application itself. Currently on My VA we say "Last opened on..." but the form side says "last saved on". We need to update our language to better align with the form side.

(_Note that the examples below are different users/benefit forms - the examples are for the "latest" language only, not the date as those do not match_)
**My VA**
![Screenshot 2023-12-01 at 12 47 48 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/b8e744e7-2e3d-495d-885d-b8093f681f88)

**Form side message**
![image (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/334b6e35-ae5c-4bb7-a68d-a3e657549501)

## Tasks
- [ ] Update language in application draft card to read "Last saved on [date]"
- [ ] Make sure the date matches the last saved date of the form/application itself
- [ ] Update tests?
- [ ] ...

## Acceptance Criteria
- [ ] Benefit Application Draft cards on My VA read "Last saved on [date]" instead of "Last opened on [date]"
- [ ] The last saved on date matches that of the application/form itself

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_
1. Log into staging with test user ___
2. Scroll to Benefit Application Drafts section
3. Confirm language now reads "Last saved on [date]"

**Comment by allisonlu** [comment]
@ajakabcin 

ready for validation! confirmed on staging for judy.morrison
