### ISSUE TITLE
SPIKE | Investigate Failed Claim Data

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71038]
## Tasks
- [x] If a claim is 60 days or older, can we tell which claims failed?
- [x] If a claim 60 days or older fails, can we tell who it failed for?

## Acceptance Criteria
- [x] Send answer to Emily by EOD 12/1/2023
---

**Comment by micahaspyr** [comment]
Because we were deleting claims older than 60 days, we can not gather any info about them as the claims' unique identifier (guid) that we can grab from sentry, is no longer traceable
