### ISSUE TITLE
[Design] My VA BAD section: Update documentation to reflect "last saved on" changes

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#71031]
## Background
As outlined in #71028 , we have updated the language in the Benefit Application Draft cards to say "Last saved on [date]" instead of "Last opened on [date]." We need to make sure our documentation and sketch files reflect this change.

## Tasks
- [x] Update figma files: user flow diagram, desktop, mobile
- [x] Update [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/FE-documentation-MVP.md)

## Acceptance Criteria
- [x] Documentation is updated

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Confirm documentation and figma files are updated

**Comment by ajakabcin** [comment]
Looks great thank you!
