### ISSUE TITLE
[Design] My VA health care: Update documentation for addition of MHV link

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#71036]
## Background
As completed in #67261 and  #67431 we have updated the Health Care section on My VA with a link to the new MHV landing page and tool links to MHV tools (instead of legacy). We need to update our various documentation to reflect this change.

## Tasks
- [ ] Review and update as needed (4 use cases plus system scenarios): [use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/health-care-use-cases) 
- [ ] Review and update figma files as needed: [user flow diagram](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/p/23DF1405-7CBD-4457-B5B1-6D3518D13CEA/canvas), and all desktop and mobile sketch files linked within use case documentation (linked in previous task)
- [ ] Complete new version of [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-small-initiatives/my-va-support-of-MHV-on-va.gov-migration/FE-documentation/linking-to-mhv-from-my-va-health.md) (AJ created a template/shell for you to follow - review and update as needed) 

## Acceptance Criteria
- [ ] Documentation is updated

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Confirm documentation and figma files are updated

**Comment by mtcA6** [comment]
Not sure this is valid anymore, we need to see where the links and alerts even sit and need to determine if the accelerated timeline has changed anything. Closing and will re-open or create a new ticket based on the upcoming conversations
