### ISSUE TITLE
Prevent Loss of Claim Data

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71037]
## Issue Description
_Claim data is currently erased 60 days from an in-progress claim's last save date (is that accurate?), but claim data needs to be saved up to 12 months from the date the claim was started._

---
## Tasks
- [ ] Update the claim expiration date to use the claim's start date rather than last saved date (if needed). 
- [ ] Update all non-disability forms that leverage Central Mail (Chapter 31, Chapter 36, and Burial/Pension) forms to retain claim data for 12 months from the date the claim was started.

## Acceptance Criteria
- [ ] Claim data is retained for at least 12 months from claim start date
---
