### ISSUE TITLE
[DA, BE] 10-10EZR - Standalone form: Edit/update the EZR DD dashboard to display the correct tracking information

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#71034]
## Background
While Lihan was working on implementing retries for the newly built 10-10EZR form (not yet launched to users at the time of this ticket), it was discovered that the current setup for the [10-10EZR Datadog dashboard](https://vagov.ddog-gov.com/dashboard/kjp-9wp-u47/10-10ezr?refresh_mode=sliding&from_ts=1698862899219&to_ts=1701454899219&live=true) is not correct, and even if the form was launched to users, we would not see any data being tracked.

<details>
<summary>Conversation with details</summary>

>**lihan li**
>i think the dashboard you linked is broken though, it's referencing stats that don't exist
>
>**Heather Justice**
>I was just thinking that since EZR is not in prod yet, we wouldnt see anything here
>
>**lihan li**
>didn't someone submit a form in prod already? it's still referencing stats that don't currently exist and won't exist even if people in prod start using it
>successful submissions also aren't being tracked in this dashboard

</details>

## Tasks
- [x] Review the [EZ Dashboard](https://vagov.ddog-gov.com/dashboard/p5g-fys-epz/1010-health-apps?refresh_mode=sliding&from_ts=1701451935289&to_ts=1701455535289&live=true) compared to [EZR Dashboard](https://vagov.ddog-gov.com/dashboard/kjp-9wp-u47/10-10ezr?refresh_mode=sliding&from_ts=1698862899219&to_ts=1701454899219&live=true)
- [x] Determine what stats on the EZR dashboard need to be updated to ensure the tracking info will display
- [x] Run tests, such as submitting an EZR form in staging environment and making sure it shows up on the Staging environment within the dashboard
- [x] After successful testing, validate with PM before closing this ticket

## Acceptance Criteria
- The 10-10EZR Datadog dashboard has been updated to reflect the actual stats and tracking information we need to monitor during our launch.
