### ISSUE TITLE
Burial | Map NEW form fields to new pdf

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71046]
## Issue Description
Since the initial mapping of existing online burial form data to the new version of the form pdf, missing fields have been added to the online form and depreciated fields have been removed. These added/deleted fields need to be mapped to the new pdf to ensure a complete claim is submitted to Central Mail.

Fiorella compiled the following references:
- [Sketch file](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/p/4871EF16-DFC9-460E-AA1B-7ED24E33B188/canvas)
- [530-Fields-to-be-deleted.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13531721/530-Fields-to-be-deleted.xlsx)
- [527_530 va.gov differences.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13531722/527_530.va.gov.differences.xlsx)

New PDF that online form fields will be mapped to is [here](https://www.vba.va.gov/pubs/forms/VBA-21P-530EZ-ARE.pdf).

**NOTE: The Veteran's ssn entered in section 1 appears at the top of each page within the pdf.**

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/6c39dabd-a6fc-4c79-82fb-2952acda392a)

---
## Tasks
- [ ] Map new form fields to new pdf
- [ ] Remove any depreciated fields from database and new pdf

## Acceptance Criteria
- [ ] A submitted online burial 530 claim generates a pdf that includes all necessary form fields
