### ISSUE TITLE
Burial Updates | Step 1: Claimant Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71045]
## Issue Description
_The online Burial 530 form is outdated and needs to have missing fields added and depreciated fields removed._

- [Figma file](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-Redesign-MVP?type=design&node-id=174%3A43726&mode=design&t=C9b2ViKgeHHOCRbQ-1)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691512530884/67e3bc6677c8d17cf6fc8848319a6e40ebced1af?wid=0-1694615398728)
- Old form pdf
- [New form pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708a2c6535486d181b128af442f89e12b9bb5302/VBA-21P-530EZ-ARE.pdf)

---
## Tasks
- [ ] Add fields denoted in the Sketch file for Step 1: Claimant Info
- [ ] Add any required validation to new fields
- [ ] Remove fields denoted in the Sketch file for Step 1: Claimant Info
- [ ] Ensure copy in online form matches Sketch file
- [ ] Record variable names for all new and deleted fields, so they can be added/removed from the claim pdf that is generated at submission

## Acceptance Criteria
- [ ] Section 1 of the 530 online form includes all new fields
- [ ] Section 1 of the 530 online form no longer includes depreciated fields
- [ ] Add added/deleted variable names to _this TBD list?_
- [ ] Copy in online form matches Sketch file
- [ ] Fiorella or Gaige sign off on changes in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---

**Comment by fiorella-io** [comment]
New comment from @aliyahblackmore for the intro page:
Make sure to remove "your" from "Learn more about requesting ~~your~~ military service records (opens in new tab)"


<img width="70%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/3b60f334-c4fd-4ecc-b2a8-1e702d8c2ec5">

**Comment by fiorella-io** [comment]
@Midge-dev @DLarson-Oddball Changes to this step.
We need to ask the Relationship to Veteran question first and then ask for the claimant's personal information. 
<img width="544" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/3883601e-723a-4e36-99fe-0c492f68023b">
If any of these are selected, SSN and DOB are not required:
- Executor of the Veteran's estate
- Funeral director or cemetery owner
- Someone else acting for the Veteran's estate (including a family member or friend who paid for burial or funeral expenses)
<img width="737" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/d3dcbbb9-d9d0-4f58-8d3a-befcd90ef69e">

**Question:** Would it be easier to remove these fields or remove the required label?

**Comment by fiorella-io** [comment]
**Content change:** We need to remove this paragraph (text in red)
<img width="654" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/3d713d40-3acf-47cf-9199-cdfa56c3c590">

**Comment by fiorella-io** [comment]
I'm sorry for all the changes, but this should be the last content change @Midge-dev 

Change the options to the following:
What’s your relationship to the deceased Veteran? (*Required)

- Surviving spouse or partner from a legal union
- Checkbox description
- Child
- Parent
- Executor of the Veteran's estate
- Someone else acting for the Veteran's estate (including a family member or friend who paid for burial or funeral expenses)
- Funeral home, cemetery, or other organization
- Other family member or friend who isn't the executor of the Veteran's estate<img width="60%" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkM4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac0572cbce580cd4fac00c5959503f791f78c989/image.png" alt="image.png" />

**Comment by fiorella-io** [comment]
@Midge-dev updates to this again. I'm sorry!
CAIA kept suggesting an additional option but our SMEs want to match the paper form. This should be the last change for this step. 
What’s your relationship to the deceased Veteran? (*Required)
- Surviving spouse or partner from a legal union
- Child
- Parent
- Executor of the Veteran's estate or someone else acting for the Veteran’s estate
- Funeral home, cemetery, or other organization
- Other family member or friend who isn't the executor of the Veteran's estate
<img width="888" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/0e6a65e5-8250-4551-9909-832379876222">

**Comment by fiorella-io** [comment]
@Midge-dev @DLarson-Oddball Adjust content to the following:
1.0 Relationship
- Change "Whats" to "What's"
- Match all the options to the Figma file

1.1 Personal info
- I shouldn't see the prefill alert, since I didn't sign in

1.2 Mailing address 
- This error message is bad. I know we can't fix it. But it's terrible!
<img width="537" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/43bc666f-c043-4d62-bee6-9f22cb7f7cf6">
