### ISSUE TITLE
Conduct small survey of co-design resources to inform forthcoming mil info research

### ISSUE THREAD

**Issue by pamela-drouin** [department-of-veterans-affairs/va.gov-team#71060]
**Description:**
This GitHub ticket outlines the tasks and acceptance criteria for conducting small survey of co-design to inform the planning of a research workshop with veterans regarding their military information. The goal is to summarize key principles and best practices in co-design.

**Tasks:**
- [ ] Research and compile relevant literature on participatory design methods.
	- [ ] [Beyond Stickynotes](https://www.beyondstickynotes.com/)
	- [ ] [Convivial Toolbox](https://www.service-design-network.org/books-and-reports/convivial-toolbox-generative-research-for-the-front-end-of-design)
	- [ ] [Participatory Design](https://www.researchgate.net/publication/279063895_Participatory_Design.) article by Michael Muller
	- [ ] [Co-design and participatory design: a solid process primer](https://intenseminimalism.com/2013/co-design-and-participatory-design-a-solid-process-primer/)
	- [ ] Anything else
- [ ] Summarize key principles and best practices in participatory design.

**Acceptance Criteria:**
- [ ] Summary is able to inform the planning of a co-design workshop with veterans.

**Comment by pamela-drouin** [comment]
@mtcA6 @andaleliz added this ticket for myself. Anyone want to add labels to the ticket or resources I should look at?

**Comment by pamela-drouin** [comment]
@andaleliz & @mtcA6 I spent a ton of time reading many resources, but did not read through the books I listed. I wound up under-estimating this ticket!

While I could spend time writing up a summary, at this point, I don't think that would be useful. I am doubtful we will do a co-design workshop at this point with enhancing military information. If we do in the future, I can pick this ticket back up and wrap it up. I will be switching focus to tasks around the Sketch -> Figma migration for the remainder of the year.

**Comment by mtcA6** [comment]
@pamela-drouin based on how the research went I'm going to close this out as "not planned" and if we do decide to move forward we can reopen it.

**Comment by pamela-drouin** [comment]
Sounds good to me, @mtcA6! I did enough of it that it actually helped. I don't see needing to return to it to read the rest of the resources 🤓
