### ISSUE TITLE
[Letters] Isolate application

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#71072]
### Background
The letters application is not currently part of the isolated app-builds allowlist. The main benefit that we can gain by adding it to the allowlist is that once isolated, PRs that involve changes to the letters application will only have to pass GHA checks related to the unit/e2e tests in the letters application folder. It also helps to speed up the time that the GHA build steps take. This will speed up the time that it takes to get updates to the letters application out the door. It also enables continuous deployment, so changes that are made will be pushed to dev, staging and prod at the same time and we can bypass the daily production deploy.

## Steps
The platform documentation linked above has the full details about the process, but here is a breakdown of the steps we will need to take:
1) Run the `check-app-imports` script
This will check to see if our application is importing from other applications, and vice versa
```sh
yarn check-app-imports --app-folders letters
```

2) Run the megaMenu test
This will ensure that the site megamenu can be rendered when the application is running
```sh
yarn cy:run --spec src/platform/site-wide/mega-menu/tests/cypress/megaMenu.cypress.spec.js --env app_url=/records/download-va-letters/letters
```

3) Add the application to the allow-list
Relevant file in vets-website: `config/changed-apps-build.json`
```
{
    "rootFolder": "letters",
    "slackGroup": "@benefits-app-builds"
}
```

```[tasklist]
### Tasks
- [ ] Run the `check-app-imports` script
- [ ] Run the `megaMenu` script
- [ ] Add entry to the allow-list and create a PR
```

### Acceptance Criteria
- [ ] The letters application has been added to the isolated app build allowlist

**Comment by jerekshoe** [comment]
### Cross-app import check

**Command:**
```
yarn check-app-imports --app-folders letters
```

**Script output:**
```sh
yarn run v1.19.1
$ node script/check-cross-app-imports.js --app-folders letters
Analyzing app imports...
No cross app imports were found!
✨  Done in 238.49s.
```

**Comment by jerekshoe** [comment]
### MegaMenu check
**Command:**
```
# app_url value comes from the rootUrl property in manifest.json
yarn cy:run --spec src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js --env app_url=/records/download-va-letters/letters
```

**Script output (some lines removed for brevity):**
```
(Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  megaMenu.cypress.spec.js                 236ms        5        1        -        4        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        236ms        5        1        -        4        -

✨  Done in 13.05s.
```

**Comment by jerekshoe** [comment]
**Update (12/4):** PR should be ready to merge (checks have all passed), just waiting on approval from platform. Should be merged tomorrow (12/5)
