### ISSUE TITLE
[Letters] Upgrade from `react-router` v3 -> v6

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#71074]
## Background
We are using an old version of `react-router` in the letters app currently. We should update this to use `react-router` v6 instead

### Value proposition
* Platform has been discussing the need to remove our dependency on `react-router` v3 because it is preventing us to upgrade other libraries in `vets-website`. It is likely that they will require teams to update their applications to a new version of `react-router` and by doing it ahead of time, we won't have to divert our attention away from our other initiatives

## Considerations
We did this recently for the Rated Disabilities application, the PR below should serve as a useful point-of-reference:
* https://github.com/department-of-veterans-affairs/vets-website/pull/26654

* Besides updating the routes, we will also need to update the import to `startApp` in the `letters-entry.jsx` file. The import needs to be updated to use the `startApp` function exported by `platform/startup/router`. This version of the `startApp` function uses the v5/v6 `react-router` plumbing instead of the v3 version used by the current `startApp`
```js
import { startAppFromRouter as startApp } from '@department-of-veterans-affairs/platform-startup/exports';
```

**Links**
* Any components that use the `Link` component from `react-router` need to be updated to import from the `react-router-dom-v5-compat` package instead
* The `to` prop now uses relative routing so need to make sure that the paths point to the correct pages

**Nested Routing**
* Components that need to render `children` provided by `react-router` will need to use the `Outlet` component instead of rendering `props.children`

### Prerequisites
**Hooks**
Later versions of `react-router` have replaced the `withRouter` HOC with hooks (`useLocation`, `useNavigate`, etc.). In order to use hooks, we need to convert any class-based components that use the `withRouter` HOC to functional components.

**Components that will need to be converted to functional ones:**
* `AddressSection`

### Relevant files
* `src/applications/letters/containers/AddressSection.jsx` (Convert to functional component, use hooks)
* `src/applications/letters/containers/DownloadLetters.jsx` (`children` -> `Outlet`, use hooks)
* `src/applicaitons/letters/containers/LettersApp.jsx` (`children` -> `Outlet`)
* `src/applications/letters/containers/LetterList.jsx` (`Link` paths)
* `src/applications/letters/containers/Main.jsx` (`children` -> `Outlet`)
* `src/applications/letters/letters-entry.jsx` (`startApp` -> `react-router-dom-v5-compat` version)
* `src/applications/letters/routes.jsx`

## Tasks
- [ ] Convert the `AddressSection` component from a class-based one to a functional one
- [ ] Update import for the `startApp` to come from `platform/startup/router`
- [ ] Update routes to use `react-router` v6

## Acceptance Criteria
- [ ] Letters application is using `react-router` v6 for it's routing
