### ISSUE TITLE
[Rated Disabilities] Remove dependency on `moment.js`

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#71073]
### Background
We are using a library called `moment.js` to help with things like date formatting and date parsing. This library is no longer actively supported and their documentation recommends moving to a different library. We have been using another library called `date-fns` alongside `moment.js` that is still maintained

## Value proposition
* Platform has been discussing finding ways to push teams to move from moment to `date-fns`. This will help us avoid having to divert attention from other projects if and when they mandate that teams update their code
* `moment.js` is a fairly large library and it has been observed that us having it slows down page load times

## Considerations
Files that still include usage of `moment.js`:
* `src/applications/rated-disabilities/components/RatedDisabilityList.jsx`
* `src/applications/rated-disabilities/tests/components/RatedDisabilityList.unit.spec.jsx`
* `src/applications/rated-disabilities/tests/components/RatedDisabilityListItem.unit.spec.jsx`

**NOTE:** We don't need to convert the `effectiveDate` string because it comes back to us in ISO format, so we can compare the strings when sorting by `effectiveDate`

### Tasks
- [x] Remove conversion of `effectiveDate` string to `moment` object
    **Note:** Because the `effectiveDate` string comes back in ISO format, we can actually just compare the strings when sorting
- [x] Replace usages of `moment.js` with `date-fns`

### Acceptance Criteria
- [x] Any usages of `moment.js` in  the Rated Disabilities application have been replaced with `date-fns`
