### ISSUE TITLE
Burial Updates | Step 3: Military History

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71104]
## Issue Description
_The online Burial 530 form is outdated and needs to have missing fields added and depreciated fields removed._

- [Figma file](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-Redesign-MVP?type=design&node-id=206%3A40658&mode=design&t=dBn2MeEj7z5W6I5O-1)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691512530884/67e3bc6677c8d17cf6fc8848319a6e40ebced1af?wid=0-1694615398728)
- Old form pdf
- [New form pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708a2c6535486d181b128af442f89e12b9bb5302/VBA-21P-530EZ-ARE.pdf)

---
## Tasks
- [ ] Add fields denoted in the Sketch file for Step 3: Military History
- [ ] Add any required validation to new fields
- [ ] Remove fields denoted in the Sketch file for Step 3: Military History
- [ ] Ensure copy in online form matches Sketch file
- [ ] Record variable names for all new and deleted fields, so they can be added/removed from the claim pdf that is generated at submission

## Acceptance Criteria
- [ ] Section 3 of the 530 online form includes all new fields
- [ ] Section 3 of the 530 online form no longer includes depreciated fields
- [ ] Add added/deleted variable names to _this TBD list?_
- [ ] Copy in online form matches Sketch file
- [ ] Fiorella or Gaige sign off on changes in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---

**Comment by jstrothman** [comment]
@Midge-dev @fiorella-io For all of our list-loop sections, we should default to the [new default card component: the white version](https://design.va.gov/components/card#default---white-with-border) 

I say this because on the Pension form, we found that the hint text doesn't have sufficient contrast on the gray background. While changing the hint text color is an option, the Collab Cycle folks recommended shifting to the new default white-bg card, as that will become the guidance, and so we'd stay aligned with the design system. 

Here's the[ launch-blocking issue for pension as reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73970), although the guidance to switch to the new default card was offered verbally--not in the ticket

I put a comment about this in sketch, but am mentioning here in case that raises awareness at a better moment.

**Comment by fiorella-io** [comment]
@jstrothman Thank you for bringing this to our attention! I'll take a look at the new component and update our designs accordingly

**Comment by fiorella-io** [comment]
We will also be adding a modal when "Remove" is clicked to have claimants approve of the removal of the Veteran's service period or previous name

**Comment by fiorella-io** [comment]
Update the copy to match the Figma file:
Step 3.0
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/1afa1433-1a32-4ff4-9ae5-08e42894f213)
<img width="760" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/29f306c8-cc0a-4217-9c4c-e60c971e05ff">

**Comment by fiorella-io** [comment]
8 accessibility issues from Ax Dev tools
     - ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/99528728-fd50-4fad-8d03-15a332509822)
