### ISSUE TITLE
Burial Updates | Step 4: Benefits Section

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71106]
## Issue Description
_The online Burial 530 form is outdated and needs to have missing fields added and depreciated fields removed._

- [Figma file](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-Redesign-MVP?type=design&node-id=206%3A53218&mode=design&t=dBn2MeEj7z5W6I5O-1)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691512530884/67e3bc6677c8d17cf6fc8848319a6e40ebced1af?wid=0-1694615398728)
- Old form pdf
- [New form pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708a2c6535486d181b128af442f89e12b9bb5302/VBA-21P-530EZ-ARE.pdf)

---
## Tasks
- [ ] Add fields denoted in the Sketch file for Step 4: Benefits Section
- [ ] Add any required validation to new fields
- [ ] Remove fields denoted in the Sketch file for Step 4 Benefits Section
- [ ] Ensure copy in online form matches Sketch file
- [ ] Record variable names for all new and deleted fields, so they can be added/removed from the claim pdf that is generated at submission

## Acceptance Criteria
- [ ] Section 4 of the 530 online form includes all new fields
- [ ] Section 4 of the 530 online form no longer includes depreciated fields
- [ ] Add added/deleted variable names to _this TBD list?_
- [ ] Copy in online form matches Sketch file
- [ ] Fiorella or Gaige sign off on changes in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---

**Comment by fiorella-io** [comment]
@Midge-dev Updates to step 2. We're combining the Burial allowance question to match the paper form. cc/ @evansmith 

What type of burial allowance are you claiming? (*Required)
Check any that apply to you
I'm claiming a burial allowance for a service-connected death
I'm claiming a burial allowance for a non-service-connect death
I'm claiming a burial allowance for the unclaimed remains of a Veteran
<img width="592" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/54218a24-2689-475e-b2db-01c349fbf195">

**Comment by steele-lm** [comment]
Created https://github.com/department-of-veterans-affairs/va.gov-team/issues/83390 to capture the update needed for step 4.
