### ISSUE TITLE
RevProxy AL2 Testing Epic

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#71101]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
- [ ] Testing in staging
- [ ] Testing in Sandbox
- [ ] Testing in Production 

## Hypothesis or Bet
We have continued support on AL2 and have parity with what we used to have on AL1

## OKR
The RevProxy is deployed to production on AL2

## Definition of done
The RevProxy is deployed to production on AL2

**Comment by ph-One** [comment]
All reverse proxy work has been completed and is deployed dev through production
