### ISSUE TITLE
Burial Updates | Step 5: Additional Info and Doc Upload

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71112]
## Issue Description
_The online Burial 530 form is outdated and needs to have missing fields added and depreciated fields removed._

- [Figma file](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-Redesign-MVP?type=design&node-id=206%3A50053&mode=design&t=dBn2MeEj7z5W6I5O-1)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691512530884/67e3bc6677c8d17cf6fc8848319a6e40ebced1af?wid=0-1694615398728)
- Old form pdf
- [New form pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708a2c6535486d181b128af442f89e12b9bb5302/VBA-21P-530EZ-ARE.pdf)

---
## Tasks
- [ ] Add fields denoted in the Sketch file for Step 4: Additional Info and Doc Upload
- [ ] Add any required validation to new fields
- [ ] Remove fields denoted in the Sketch file for Step 4: Additional Info and Doc Upload
- [ ] Ensure copy in online form matches Sketch file
- [ ] Record variable names for all new and deleted fields, so they can be added/removed from the claim pdf that is generated at submission

## Acceptance Criteria
- [ ] Section 4 of the 530 online form includes all new fields
- [ ] Section 4 of the 530 online form no longer includes depreciated fields
- [ ] Add added/deleted variable names to _this TBD list?_
- [ ] Copy in online form matches Sketch file
- [ ] Fiorella or Gaige sign off on changes in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---
