### ISSUE TITLE
Research user notifications about situations of potential fraud

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#71120]
### Description of UX Tasks
One way that we can shorten the time it takes to find out about an incident of fraud is to make sure veteran's are aware of unauthorized changes being made in their VA account. We already notify veterans via email when their direct deposit information changes. We could potentially add SMS notification to that, and add notifications about when other personal information changes, like email address. We could also potentially add a hook to those notifications that will allow a veteran to indicate they did not make that change and automatically revert it.

This research could potentially be combine with another smaller research

### Tasks
- [ ] plan research around messaging
   - Many veterans proclaim being over messaged from the VA, are these types of messages ones that veterans will pay attention to?
   - what actions, anxieties, question or concerns will this messaging potentially raise with veterans?
   - how does it feel to get both an email and and SMS about the same thing?
- [ ] outline a potential messaging strategy, 
   - draft potential messaging that we can test with veteran participants

### Documentation

- [Assisting Victims of Fraud](https://docs.google.com/document/d/1ASo1xGhpD6J__mWNaCVoSUbCZWyX-7DRkCbi_iB8AJk/edit)
- [VA Fruad prevention plan](https://docs.google.com/document/d/1zQ37yYtgETKgAuMa8ryFd0ELjPHRSuOqHHdJHgahED0/edit?usp=sharing)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694787677574/98397861b6a02d24c5cb0b91f461f458a825ad74?sender=u2bba352d5b2fc0f0969e0146) about VA account recovery (restricted access)
- [secondary research current account recovery process.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/Identity/BDPR) (in Sensitive GH repo)

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

```[tasklist]
### Tasks
- [ ] test task 1
- [ ] test task 2
```

**Comment by claytonzook** [comment]
note - repurposing a test ticket

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
