### ISSUE TITLE
Add Question to Platform Support VFS Survey in Optimal Workshop

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#71121]
## Description 
This ticket will house the task of adding a question to our Optimal Survey. We have noticed a slight dip from 97% to 93% in satisfaction with 7 folks noting they are satisfied but not extremely satisfied. We are aiming to identify if the extremely satisfied status was not given because of things we can or can't control. 

The question will read: _"If you did not answer extremely satisfied what could our team do to change your answer to extremely satisfied?"_
---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add question to Optimal Workshop questionnaire 
- [x] Notify Platform Analytics team of addition
- [x] Request data be tied to existing dashboard [here](https://va-gov.domo.com/page/1729270793) 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
