### ISSUE TITLE
Capture and Add Submission Date Stamps to 686

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71125]
## Issue Description
_The date an online 686 form was submitted should appear in the "VA Date Stamp" box in the upper right-hand corner of the pdf and on the signature line. Currently, the pdf generation services in vets-api is not appropriately adding the date. Claims that go through the backup submission process have the date added, but claims that go through the happy path do not. Additionally, the date stamp should be the date the claim was submitted and not the date the pdf was generated, which is currently the case._

<img width="1226" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUl0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dc7701f0111754e7937ba3e0c11aa613cab02e2/image.png" alt="image.png" />

Example from 526:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/9629556b-c1e6-42ea-b5f7-3f900cfe5a76)

---
## Tasks
- [ ] Correct the date stamp variable to capture claim submission date (not pdf generation date)
- [ ] Add the date stamp to the "VA Date Stamp Box"
- [ ] Add the date stamp to the signature line date field
- [ ] Ensure all submitted claims (happy path and backup) receive date stamps

## Acceptance Criteria
- [ ] Date claim was created appears in the "VA Date Stamp Box" for all claims (happy and backup)
- [ ] Date claim was created appears in the signature line date field for all claims (happy and backup)
---
