### ISSUE TITLE
[MVP] Test Pension form flow logic in staging for Steps 1-3

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71135]
## Issue Description
As a Pension team,
we need to ensure the form flow logic is working as it should be in staging,
so that we can flag any question validation issues and work with engineering to correct.

---
## Tasks
- [x] In staging, test the form flow logic for Steps 1-3 of the Pension form
- [x] Document any question/answer validations issues not following the desired form flow outcomes
- [x] Share findings with Engineering and Product

## Acceptance Criteria
- We will have tested Steps 1-3 of the form flow logic on the Pension form in staging
- We will know what engineering will need to correct based on these findings

**Comment by aplatt-coforma** [comment]
Tested the form flow from 1-3 and noted 2 issues
1. In the form flow diagram, we show a screen for severance pay but I found the ticket that requested severance pay be removed from the form flow. Maya will update the form diagram to reflect this page removal.
2. In the form flow diagram, we show a warning message about providing additional forms if they select Yes to the question "Does Medicaid cover all or part of your nursing hoe costs?" I found the ticket that create these screens but do not see that warning mentioned in the tickets acceptance criteria. Asking @mayacoforma  and @vbellissimo  if this was intentional or an oversight. 

All other screens and flows looked good. I'll close this ticket and will create a new ticket for the decision on issue 2.

**Comment by vbellissimo** [comment]
@aplatt-coforma [According to the designs](https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/p/B6F7C443-FC6A-4E41-A43D-D20A4ACF0D11/canvas), the alert is if they answer "yes" to the question: Have you applied for medicaid?, not for Does medicaid cover all or part of your of your nursing home costs. I wrote the ticket for this task based on the designs. But I'll wait to hear what Maya says, in case we need to include it on the "Does Medicaid cover all or part of your nursing home costs?" page, as well.
