### ISSUE TITLE
[MVP] Test Pension form flow logic in staging for questions in Step 4

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71136]
## Issue Description
As a Pension team,
we need to ensure the form flow logic is working as it should be in staging,
so that we can flag any question validation issues and work with engineering to correct.

---
## Tasks
- [x] In staging, test the form flow logic for Step 4 of the Pension form
- [x] Document any question/answer validations issues not following the desired form flow outcomes
- [ ] Share findings with Engineering and Product

## Acceptance Criteria
- We will have tested Step 4 of the form flow logic on the Pension form in staging
- We will know what engineering will need to correct based on these findings
