### ISSUE TITLE
[MVP] Test Pension form flow logic in staging for Steps 5-7

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71139]
## Issue Description
As a Pension team,
we need to ensure the form flow logic is working as it should be in staging,
so that we can flag any question validation issues and work with engineering to correct.

---
## Tasks
- [x] In staging, test the form flow logic for Steps 5-7 of the Pension form
- [x] Document any question/answer validations issues not following the desired form flow outcomes
- [x] Share findings with Engineering and Product

## Acceptance Criteria
- We will have tested Steps 5-7 of the form flow logic on the Pension form in staging
- We will know what engineering will need to correct based on these findings

**Comment by Allexelaw** [comment]
I will also test pension form flow logic in staging @vbellissimo @aplatt-coforma and add any comments to MVP bug/issue list
