### ISSUE TITLE
FE/BE | Direct Deposit EVSS>LH Migration | Remove DD LH Migration Toggle

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71150]
## Background 
We've fully rolled out the feature and now need to remove the toggle we used. We started some of this work by removing references to the toggle in the code under:
- #69602 

Now we need to continue that work and remove the underlying toggle `profile_lighthouse_direct_deposit` altogether. 

There may be references to the toggle in both FE and BE code

## Tasks 
- [x] Remove any remaining toggle logic from FE
- [x] Remove toggle and logic from BE
- [x] Delete feature flag manually from each env after changes have been deployed to each env (step 3 [in these docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)).

## Acceptance Criteria 
- [x] the toggle is no longer available in the feature toggle list
- [x] we're not seeing a spike in errors after removing the toggle

**Comment by adamwhitlock1** [comment]
I think this can be closed out. The toggle has been removed and all legacy code has been removed. The only strange thing is that we are seeing very sporadic low numbers of requests still going through to the old ppiu endpoint though.

Tom and I are a little stumped on this considering literally all mention of the old endpoint have been removed.

The only thing that I can think, is that somewhere there are some old browsers or some browsers with non-cache busting settings that are still using some outdated version of the JS bundle... its really baffling. After the daily deploy every day the cache policy for our application bundles should enforce that all user's browsers request the updated source code for the site assets, but its honestly the only thing that I can think of.

**Comment by tpharrison** [comment]
Yes, we are still seeing 100+ requests/day come through the old EVSS controller.  The referrer on the request is empty, so I can't tell where the traffic is coming from.  I may have to open a ticket to investigate this further.
