### ISSUE TITLE
Copy/element updates for search results

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#71165]
Our accessibility rep Jamie took a look at our search results and has called out some things to update:

1. When an org/rep name is included as a search parameter and we mention it in search results, we need a space after that mention:
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDh1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc0cb9140c333852160a85b3976230fb37174826/image.png" alt="image.png" />
2. Update search results to use h3 headings
   1. Our tool is using `<strong>`: <img width="929" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVF1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02a5354f02df6d93126768bec71c6e81f5e20929/image.png" alt="image.png" />
   3. Recommendation is to update to `h3` like the facility locator: <img width="1087" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVV1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--399c7a51c73038188ec8c1a1ec8b6eeb234a011c/image.png" alt="image.png" />
3. Reconsider org/rep name character limit for search results -- currently we are cutting off a portion of the organization name ("Affairs" in this screenshot)
   1. <img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWd1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad9ab7a14c2695ef219d19c615d5d8e2d23edae3/image.png" alt="image.png" />
4. Update the plural spelling for attorney -- should be "attorneys" not "attornies"
   1. <img width="708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0F1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8d375cd72dfc2081671a37e8f55ad817d62d278/image.png" alt="image.png" />

Original slack thread: https://dsva.slack.com/archives/C05L6HSJLHM/p1701712089378129?thread_ts=1701271694.454669&cid=C05L6HSJLHM

### Tasks
- [ ] Add a space after the org/rep name mention, in the parameters summary of the search results
- [ ] Update the org/rep names in search results to use H3
- [ ] Reconsider the org/rep character limit for the search results so we do not cut off the name
- [ ] Update spelling for "attorneys"

**Comment by oddball-lindsay** [comment]
Looking into allowing users to search by hitting the "enter" key, adding that to this PR
