### ISSUE TITLE
[Content] Ensure content for cancelled appt alert (from prod) during pre-check-in is consistent with unified check in messaging

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71166]
## Tasks

- [x] Ensure content for cancelled appt alert (from prod) during pre-check-in is consistent with unified check in messaging for Design Priority 1. (Should be included in Design - Priority 1 Page. I.e., Ya-ching should have the artboard in that page.)
- [x] Create content for cancelled appt alert (from prod) during pre-check-in for later priority. E.g., Design Priority 1 might still be using the words "Pre-check-in," for example. But, in later priorities, we need to make sure the content aligns with content from later priorities. (Should be included in Design Page. I.e., Ya-ching should have the artboard in that page.) 
- [x] Review cancelled appt detail page content (from [VAOS](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=2237%3A84511&mode=design&t=d2kOLq2dT43TOyxE-1)) and ensure the content still is applicable to unified check in. (Should be included in Design - Priority 1 Page AND Design Page. I.e., Ya-ching should have the artboards in those pages.) 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [x] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [x] Work was reviewed by groups indicated above
- [x] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/71166?planning-poker) with Zenhub @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 here is a [link to the Sketch page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/04C2CEC7-895F-4D1E-93A8-6BA0F1B97FED/canvas) to work off of. I think there are two tasks, 1) content for the canceled page (which fits into Priority 1 wireframes), and 2) content (which could be identical to 1) for the alert that will be used in a later priority within unified check in. For example, the content in Priority 1 wireframes is closer to what's in production today.

**Comment by benbrasso-agile6** [comment]
And, here is the appt detail page for canceled to review. Used same content that Appointments/VAOS uses. But, feel free to review, please. https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/jAPE3z/p/4BACBAC3-9221-4B54-BCAC-3E2424DD408B/canvas/#Version

**Comment by benbrasso-agile6** [comment]
Task 4) Which is not listed in the tasks above, @kellysmith1008, from reviewing with engineers yesterday, we need a fallback for the [canceler] field when we can't fetch that value. I adjusted the annotation for you to write something in. https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/eG4a3x/p/4BACBAC3-9221-4B54-BCAC-3E2424DD408B/canvas?posX=-1662.5270740434376&posY=-384.7019963173191&zoom=0.5642133951187134

**Comment by kellysmith1008** [comment]
Proposed text for scenarios 1 and 2, waiting to hear from Ben on a question. Task 3 content looks fine and ready to go. Still working on content for [canceler] when a value can't be found.

**Comment by kellysmith1008** [comment]
Ok, content for all tasks is complete and updated in "Canceled alerts #68281 page in sketch. Moving to validate for @benbrasso-agile6 to validate now that the content is updated. I think we can close once it's validated - I don't think front end needs tickets as we're still designing this - but if I'm wrong, I'm happy to create the tickets for them.

**Comment by benbrasso-agile6** [comment]
Sounded like John was good with this. @loripusey @wullaski don't forget to create a ticket, if needed, for this work: 

[Priority 1 sketch page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/OQLnam/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas/#Version)

[Canceled pages](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/04C2CEC7-895F-4D1E-93A8-6BA0F1B97FED/canvas#Version)
