### ISSUE TITLE
Implement Metadata Validation

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71164]
## Issue Description
_Implement the metadata validator developed for the 526 form into the burial form to eliminate the metadata errors causing claim rejections._

Implementing metadata validation on Burial will also mitigate errors on Pension 527 and Chapter 36 (ECC).

---
## Tasks
- [ ] Implement metadata validator
- [ ] Monitor errors

## Acceptance Criteria
- [ ] Metadata validator is implemented within Burial 530 Form
- [ ] Follow-on tickets created for any remaining errors
---
