### ISSUE TITLE
TOU: Content Updates

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#71161]
## Description
Make the following changes to the Terms of Use pages 

## Tasks
- [x] Terms of use page (`/terms-of-use`)
    - [x] Remove first paragraph => Remove paragraph above accordions
    - [x] Change General disclaimer => Make word `disclaimer` lowercase
    - [x] Change the `call our MyVA411 main information line` => `Call us at 800-698-2411, and select 0 (TTY:711). We're here 24/7`
        - [x] Use va-telephone + `CONTACTS` import
    - [x] In the **What happens if you decline section** update second paragraph to `But you won't be able to use some VA online services, including these services:`  
- [x] Terms of Use Declined page (`/terms-of-use/declined`)
    - [x] Remove bolded word`Note:` and replace with nothing
    - [x] Change the `call our MyVA411 main information line` => `Call us at 800-698-2411, and select 0 (TTY:711). We're here 24/7`
        - [x] Use va-telephone + `CONTACTS` import

## Image
<img width="621" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVV6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--247116769eef14804182aa4840a0d1ff26e19478/Screenshot%202023-12-04%20at%203.23.19%E2%80%AFPM.png" alt="Screenshot 2023-12-04 at 3.23.19 PM.png" />
