### ISSUE TITLE
Build and publish VA home loan COE page in Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#71172]
## Issue Description

Once we get translated docs back we'll need to build and publish:

[How to request a VA home loan Certificate of Eligibility (COE)](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/)

**Resources**
[Checklist for content readiness for translation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/editorial-resources/preparing-content-for-translation-checklist.md#checklist-for-content-readiness-for-translation)

---
## Tasks
- [x] Build translated pages in Drupal (Ana)
- [x] Copyedit (Juliana)
- [x] Publish (Randi)
- [x] Send live page to State for QA (Randi)
- [x] Input any changes (Juliana)
- [x] Review and publish
- [x] Create ticket for PW to add Spanish toggle (Randi)

## Acceptance Criteria
- [x] Spanish pages are live
- [x] Ticket for toggle is created

**Comment by RLHecht** [comment]
@ABeltran77 Here's the content back from State. This page is ready to be built in Drupal. 

[LS-2022-0118394-M-SPA-FINAL_How to request a VA home loan Certificate of Eligibility.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14222353/LS-2022-0118394-M-SPA-FINAL_How.to.request.a.VA.home.loan.Certificate.of.Eligibility.docx)

**Comment by ABeltran77** [comment]
@RLHecht @strelichl @megzehn Built page in Drupal. I am still unable to preview in Drupal, please be aware that I cannot identify any needed edits/corrections  w/o this function.

**Comment by RLHecht** [comment]
Thanks @ABeltran77 can you put the Drupal node in here? Preview should be working again this afternoon. Can you check it then and make any additional changes you might need? Thank you!

**Comment by ABeltran77** [comment]
@RLHecht Reviewed and looks ready for @megzehn 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122648468/de3f3c5e-8975-48ff-8641-4ebf1ac35a01)

**Comment by RLHecht** [comment]
@saratorres2 Just removed Megan and added you to this one. This should be ready to review and publish. Thank you!

**Comment by RLHecht** [comment]
@juliana-jara It looks like this page was built in Drupal with content translated form State. But it was never copyedited and reviewed or compared to the live English page. Can you please copyedit and if there are changes we need to send to State let me know and we can queue them up. If there aren't, we can get this ready to publish. Thanks!

**Comment by juliana-jara** [comment]
Hi @RLHecht I have a few copy edit suggestions for the page in Spanish. You can see them [here](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2371172.docx?d=w48487cc3458c4241a80e4d15f80406bc&csf=1&web=1&e=TEpCQe).

**Comment by RLHecht** [comment]
Thanks! You can go ahead and make these edits in Drupal. I'm checking on what we're going to do with the broken link and will post back here.

**Comment by juliana-jara** [comment]
Hi @RLHecht  All the changes except the link issue were done on Drupal.
https://prod.cms.va.gov/solicitud-de-un-certificado-de-elegibilidad-coe-para-recibir-un-prestamo-hipotecario-de-va-coe-0

**Comment by RLHecht** [comment]
I published this page. Will send the live link to State once it's up.

**Comment by RLHecht** [comment]
Sent live link on 5/20

**Comment by RLHecht** [comment]
@juliana-jara here is the QA back from State. Can you please make any needed updates in the Drupal file and let me know if there is anything we don't want to change. Thanks!

[LS-2024-0125469 -LQA Notes-es_v1__VA.gov How to request a VA home loan Certificate of Eligibility.docx](https://github.com/user-attachments/files/20488533/LS-2024-0125469.-LQA.Notes-es_v1__VA.gov.How.to.request.a.VA.home.loan.Certificate.of.Eligibility.docx)

**Comment by RLHecht** [comment]
Thanks! i published these changes and created the toggle ticket for PW. closing this!
