### ISSUE TITLE
[MVP] Create designs for Step 5 "other medical/burial expenses"

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71183]
## Issue Description
As a Pension team,
**we need to create designs for "other medical/burial expenses" found in Section 10 [of the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf), as part of Step 5 of the online form**
so that the online form provides the full requirements of information required from VBA,
so that the user does not have to provide that information as part of development,
so that the online form aligns with the PDF version of the Pension form.

---
## Tasks
- [x]  Work with Julie Strothman to create designs for "other medical/burial expenses" found in Section 10 [of the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf), as part of Step 5 of the online form
- [x] Share designs with OCTO, CAIA and product to gather any necessary feedback
- [ ] If necessary, incorporate feedback into designs, to finalize for engineering

## Acceptance Criteria
- We will have designs for Step 5 of the online Pension form pertaining to "other medical/burial expenses", currently found in Section 10 [of the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)

**Comment by mayacoforma** [comment]
Update on #71183: "Other medical / burial expenses" section:

I'm requesting feedback from @katherine-fung  on the copy and from @vbellissimo  on the requirements. Could you please review the designs and let me know if I've captured all your feedback?

Screenfows: (attached)
Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/qb03kGd/play

Please leave comments in this sketch file with any additional. Thank you!

<img width="827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3RmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03dc755f75a654d088c460e3f1d765ce522167ab/%2371183%20Screenflows.png" alt="#71183 Screenflows.png" />

**Comment by mayacoforma** [comment]
Update on #71183: "Other medical / burial expenses" section:

Thanks for the second review, Katherine. I appreciate it. 
I've implemented the copy changes. I'll now move this task to 'Completed in Sprint.'

Screenfows: (attached)
Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/4ov13Mq/play

<img width="827" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--331e3c4cea24ff1e8dbbe2327d259fb734afb41c/71183%20Screenflows.png" alt="71183 Screenflows.png" />

**Comment by mayacoforma** [comment]
Made some additional copy updates based on Katherine's feedback.
