### ISSUE TITLE
NOD | Test the V2 version of the form using the test plan

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71193]
## Background Context
Oh, this ticket covers the test process for the form, not including bugs.

## Tasks
- [x] Decide who will be involved in testing (LH, CMP, MMS)
- [x] Decide how the team will test (everyone tests everything or test in sections?)
- [x] Decide when the team will test
- [x] Schedule a block for testing
- [x] Complete testing. Record the test session.
- [x] If we identify missing test cases, add them to the test plan
- [x] Decide what kind of test coverage is needed
- [x] Create an epic for bugs
- [x] Prioritize the bugs

## Definition of Ready 

- [x] Test plan is approved
- [x] Supporting teams are aware

## Definition of Done

- [x] Test is complete
- [x] Bugs are ticketed
- [x] Test plan is updated

**Comment by saderagsdale** [comment]
- One FE eng (Robin), one BE eng (Eugene), Derek, non-eng roles (Sade, Eileen)
- Block time on the calendar for testing (2-3 hr block)
- Screenshare, recorded, one person running through test cases
- Chrome browser

**Comment by HeatherWidmont** [comment]
Regression testing scheduled for tomorrow.

**Comment by HeatherWidmont** [comment]
- Recording: @eileen-coforma 
- Screenshare: @eileen-coforma (Robin to support) 
- Creating tickets: @Mottie & @data-doge 
- Performing BE checks: @data-doge 
- Set up thread for a guide & template for tickets: @saderagsdale

**Comment by eileen-coforma** [comment]
Recording posted to our drive: https://drive.google.com/drive/folders/1YK9ZXl6Q-02cOfM9JkaUhTsLJ5zn5cKx?usp=drive_link
