### ISSUE TITLE
[epic] NOD | Infinite loop bug prevented users from completing the form

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71190]
## What happened?

On May 23, 2023, a feature flag, and code to disable the submit button was added to the Notice of Disagreement form at 1:50 PM ET. This introduced a bug that prevented roughly ~3,152 users from accessing the form between July 27th - September 1st. We were notified on August 31st in this [Slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1693505338029709).

## Next steps

- [x] Deploy a [hotfix](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64802)
- [x] Gather list of affected Veterans
- [ ] Get [draft content](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/NoD%20errors%20-%20Comms%20to%20Veterans.docx?d=we190d63de79546c39a1d1f67c50c4c36&csf=1&web=1&e=EGxlDF) approved for email and letters
- [ ] Send information necessary for ADG to create a letter feed
- [ ] Release the NOD V2 form with "Reason for extension request" fields
- [x] Complete a [post-mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2023/2023-05-24-notice-of-disagreement-outage.md)
- [ ] Confirm remediation is complete with PO
