### ISSUE TITLE
NOD | Create a master test plan for NOD

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71192]
## Background context
That's part of our remediation efforts, we want to create a comprehensive test plan that allows us to identify and test all functional and non-functional use cases. Additionally, the test plan should allow us to see which test cases have code coverage, and what kind of code coverage they have.

---
## Tasks
- [x] Create a draft of the [test plan](https://docs.google.com/spreadsheets/d/1lYEtYiRmxNhMrZV9Exmc8xtPDedmZGPTowG2NeD3Uig/edit#gid=0)
- [x] Check with Lighthouse if they have a test plan or test cases we can add to make ours more comprehensive
- [x] Team review and edit
- [x] Product owner review and edit
- [ ] Add to test rail

**Comment by saderagsdale** [comment]
Working on test rail now.
