### ISSUE TITLE
NOD | Re-release the V2 form

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71194]
## Tasks
- [ ] Confirm re-release plan with engineering
- [ ] Confirm re-release plan with enablement team
- [ ] Create samples to send to BVA, CMP, and MMS
- [ ] Confirm that claims and evidence are arriving as expected in production through a canary test

## Open questions
- How do we want to validate that things are working in production? (thoughts on Steve's list of code yellow monitors?)

## Definition of Ready 

- [ ] TBD

## Definition of Done

- [ ] TBD
