### ISSUE TITLE
Design | Migrate to Figma | Update Personal Information Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71214]
## Background 
We need to migrate the [personal information product](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information) sketch files to Figma. 

In order to do that, we need to have our sketch files updated to the latest USWDS design components.

We need to update both [Mobile ](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565)and [Desktop ](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/287E1E08-975D-4190-AD19-D4514223484C/canvas)

## Tasks 
- [x] Identify v3 components available for use, that we also have in the profile:
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [x] Update all pages in Sketch file accordingly

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, user flow, and future state sketch files for personal information cleaned up and annotated in Figma
- [x] we've added a link to the Figma file in the product readme file.

**Comment by andaleliz** [comment]
@pamela-drouin and @mattmarino-adhoc I started working on this, and am wondering if we should we make the jump and update everything in Figma.  Here's why:

- **We have a lot of design system components in our design files that are already detached from the library.** This is mostly because the Sketch symbols wouldn't wrap onto multiple lines, so we had to break the symbols for mobile. I'm seeing this primarily for the additional info components, form input labels that have 2 lines, and alerts with headings.

- **I noticed some V3 components are wonky in Figma and need to be fixed again anyway.** I made progress with updating some symbols to V3 in the personal info file, so I went ahead and imported it to Figma to see what would happen (file shared with you).  I downloaded the desktop app and followed [the import instructions here](https://help.figma.com/hc/en-us/articles/360040514273-Import-Sketch-files), so hopefully I did it right. Some things look good, but not all. For example, `button pair`(Symbols page, Desktop section. Check out the symbols with a name that starts with `Editable field`) is rendered so it looks like primary button is missing, and the secondary button has no outline.  When I insert it into the doc via the assets panel, it looks fine.

Is it a better use of time to go ahead and upload everything into Figma, and fix them there?

These are the components I've encountered in our Sketch file so far that can't be updated to V3 and would need to be fixed in Figma anyway:

- additional info (desktop has wrong chevron, mobile doesn't handle line wrapping, any component with link is detached from library)
  - it seems like the mobile component in Figma still doesn't wrap onto two lines
- text input with label (mobile, doesn't handle line wrapping)
- text input with label and error state (mobile, doesn't handle line wrapping)
- button pair (mobile, buttons don't resize correctly)
- mobile standard alert (heading doesn't work with multiple lines of text)

What do you think?

As an aside, I'd love to have one or both of you help me learn a couple of things about Figma. Resizing layers is for some reason challenging me (maybe cuz it's not yet 7am?) and it'd be great to sit down for 15-30 minutes and have you show me a few things.  Let me know if you're up for that and I'll grab time on your calendars.

**Comment by mattmarino-adhoc** [comment]
Thanks for leading the way here, Liz! Addressing your concerns:


>     * **We have a lot of design system components in our design files that are already detached from the library.** This is mostly because the Sketch symbols wouldn't wrap onto multiple lines, so we had to break the symbols for mobile. I'm seeing this primarily for the additional info components, form input labels that have 2 lines, and alerts with headings.

I'm assuming there's no easy way around this, we'll just have to do those replacements more manually.

>     * **I noticed some V3 components are wonky in Figma and need to be fixed again anyway.** I made progress with updating some symbols to V3 in the personal info file, so I went ahead and imported it to Figma to see what would happen (file shared with you).  I downloaded the desktop app and followed [the import instructions here](https://help.figma.com/hc/en-us/articles/360040514273-Import-Sketch-files), so hopefully I did it right. Some things look good, but not all. For example, `button pair`(Symbols page, Desktop section. Check out the symbols with a name that starts with `Editable field`) is rendered so it looks like primary button is missing, and the secondary button has no outline.  When I insert it into the doc via the assets panel, it looks fine.
> Is it a better use of time to go ahead and upload everything into Figma, and fix them there?

Probably!

> These are the components I've encountered in our Sketch file so far that can't be updated to V3 and would need to be fixed in Figma anyway:
> 
>     * additional info (desktop has wrong chevron, mobile doesn't handle line wrapping, any component with link is detached from library)
>       
>       * it seems like the mobile component in Figma still doesn't wrap onto two lines
> 
>     * text input with label (mobile, doesn't handle line wrapping)
> 
>     * text input with label and error state (mobile, doesn't handle line wrapping)
> 
>     * button pair (mobile, buttons don't resize correctly)
> 
>     * mobile standard alert (heading doesn't work with multiple lines of text)
> 
> 
> What do you think?

I am wondering a couple things:
1. How proactive the design team can be with fixes in alpha state before the full alpha release on 1/16? Maybe they can help fix some of this stuff before then - if so, waiting a little bit could be beneficial.
2. I was already thinking about the fact that devs cannot get full access to Figma until Feb (I believe that was what the VA design presentation indicated). If that's the case, I'm not confident any new work should be put in Figma yet. Let's confirm what the plan for engineering access contains this week before we get too deep into work in Figma. 

> PS I'd love to have one or both of you help me learn a couple of things about Figma. Resizing layers is for some reason challenging me (maybe cuz it's not yet 7am?) and it'd be great to sit down for 15-30 minutes and have you show me a few things. Let me know if you're up for that and I'll grab time on your calendars.
> 
> PPS If we all have Sketch/Figma work to do, would you be into a sort of pomodoro sesh and hang out while we work, maybe listen to some good music? I'd be glad to set that up if so!

Absolutely up for that!

**Comment by andaleliz** [comment]
@mattmarino-adhoc thank you for your feedback, and for confirming that engineers will NOT get inspect access to Figma, ever.  

>How proactive the design team can be with fixes in alpha state before the full alpha release on 1/16? Maybe they can help fix some of this stuff before then - if so, waiting a little bit could be beneficial.

Is that something you can look into? That would be helpful to inform our way forward.

I'm still curious what @pamela-drouin thinks but I'm kind of torn about what to do, in the absence of that information.  In my brief experiment, it doesn't seem like it's that helpful to update to V3 components in Sketch now, and it also doesn't seem like it will take more than a 1/2 sprint to get everything fixed up in Figma once we migrate it over.  Holding off is not a bad thing.

However, if we want to keep moving forward with this now, I think this is one way to do it:
- We can copy the Auth Exp Pattern Library to Figma, and at least get that set up. I don't think those core components will change between now and Feb
- We can go ahead migrate and update components in sections of profile that we know are very unlikely to change before February, like Connected Apps, Account Security, Direct Deposit, Notification Settings, Edit-as-a-Subtask, and _maybe_ Contact Information.  We'll probably have to make some more updates once other components are fixed by the DST.
- Sections we know will change, and devs will need access to should stay in Sketch until we get much closer to Feb: Military Information, Personal Information, Profile Hub and maybe one other I'm missing.

We could also take this approach to the Figma office hours they mentioned and see if they have any advice/insight that can help.

**Comment by pamela-drouin** [comment]
@andaleliz @mattmarino-adhoc apologies for the late reply. I think your proposed approach makes sense, Liz, and to take our approach to the Figma office hours -- anyone catch when they'll be held?

**Comment by mattmarino-adhoc** [comment]
@andaleliz AND @pamela-drouin - I stated as much in Slack, but just to repeat it: there WILL be inspect mode access apparently in 2024, it just won't consist of all the functionality of dev mode (available only until EOY 2023). 

Regarding the status of the design system and fixes before the full alpha release on 1/16, I can definitely touch base with the design system team as we move forward. 

As far as waiting (or not), my suggestion is that we do go ahead and migrate things now, but if there is something that doesn't translate 1:1, or doesn't have a component available yet, we just prioritize fixes on level of importance. For the most current or important files:
- we first identify anything that is off/doesn't have a component yet
- document it in the Figma files
- reach out to the design system team regarding the status of those specific components that are broken/unavailable
- address those issues as best makes sense

Based on the info/timetable they give, we can address them when makes the most sense (like maybe for one component it'll be pushed to Figma next week so we might as well wait, but for another it's already out and won't be modified any more in alpha state so we should do manual fixes ourselves). For older files/things not currently in flux: we make notes of any import issues we identify, and circle back to them when makes sense - the further addition of alpha components may make things easier the longer we can hold off. (I know you both will be out for a bit for holiday vacation, I will be available for much of that time and can make this is a priority if we need to while you're away).

**Comment by mtcA6** [comment]
Wondering if it makes sense to document the problems as GH issues in addition to calling things out in the Figma files? That way we have eyes on that when AJ and I are working through our backlogs to prioritize with Samara. 

cc: @ajakabcin

**Comment by mtcA6** [comment]
@andaleliz is this a comprehensive list for the profile in its entirety? or just the components in the personal information section? 

> Additional info USWDS
> Alert USWDS
> Breadcrumbs USWDS
> Button pair USWDS
> Button USWDS
> Checkbox group USWDS
> Checkbox USWDS
> Featured content USWDS
> Modal USWDS
> Radio button USWDS
> Select USWDS
> Text input USWDS
> Textarea USWDS

**Comment by andaleliz** [comment]
@pamela-drouin Figma office hours are Tuesday at 3:30 ET. I signed up to go on behalf of the team and also added this to the AE Team Shared calendar so the link is easily accessible.

@mattmarino-adhoc thank you for the clarification about dev access.  I think the approach you've outlined makes a lot of sense and am cool to move forward with that. I'll continue with this ticket.

>document it in the Figma files

Can you share more about where/how to do this? If it's too complicated to do async we can jump on a call.

@mtcA6 yes, I think it's a good idea to create GH tickets. That'll make it easier to go back and make the updates once they're fixed.  In office hours, I will ask if we should also create GH tickets for their team as we spot bugs. If so, we can add those bug tickets as blockers to our own work.  

The list of components includes all of profile, not just personal information.  There was a `textarea` on the list by my mistake, so I removed that from your comment as well as the issue description so that no one gets confused later.

**Comment by andaleliz** [comment]
@mtcA6 I'd like to carry over 2 points for this one into the next sprint. I'm close to done but doing some nitpicky detailed cleanup :)

**Comment by andaleliz** [comment]
This is complete, except for the clean up of the future state files. This is more complex than I realized because they're all still in the old format of repeating things across many, many art boards. There's a lot of clean up to do, so I'll pick this back up on 12/26.

**Comment by mtcA6** [comment]
Do we need to create 2 linked follow up tickets here for:

1. the future state pages 
2. the work that needs to be done once the platform team fixes the bugs in figma

**Comment by andaleliz** [comment]
@mtcA6 nope, the future state pages are already part of this ticket, and we have #72085 for bug fixes.

**Comment by mtcA6** [comment]
Can we make sure that all the things in this list from #71216 were migrated? 

- List of Sketch files and their pages
	- [ ] Profile - Personal information
		- [ ] ✅ Mobile 
		- [ ] ✅ Desktop 
		- [ ] ✅ Future state - Mobile
		- [ ] ✅ Future state - Desktop
		- [ ] ✅ Symbols
		- [ ] 📦 Discovery
		- [ ] 📦 Iterations

**Comment by pamela-drouin** [comment]
I double-checked the file pages that have been imported, and there is an extra page in the this file: Exploration - add CST link. It seems to be missing the page in Sketch called Discovery. These pages do not match. Not sure why, or what I am missing! @andaleliz

**Comment by andaleliz** [comment]
@pamela-drouin and @mtcA6 the Discovery page contained old explorations of hint text and FAQ content variations that I really don't think we'll go back to. If we did, we'd have to get content reviewed all over again anyway so it felt like we could just clear those out and start from where we are today if content revisions are ever needed (like we are doing with the gender identity FAQ).

It's strange that the Exploration - add CST page is missing from Sketch, but it is in Figma. This was something we briefly talked about coming out of the personalization work done in the first half of 2023.
