### ISSUE TITLE
[BE] 10-10 Forms: Smoke testing in Staging environment for Faraday upgrade

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#71217]
## Background
The platform team will be upgrading Faraday and we need to perform testing to ensure everything is working as expected

>Original Post
>- Platform Team will be merging the first phase of the Faraday upgrade.  This first phase will bump Faraday from 0.17.6 to 1.10.0, and in the coming ~week we'll complete the upgrade by moving to the latest (2.7). The [upgrade PR here](https://github.com/department-of-veterans-affairs/vets-api/pull/14552) tackles any issues we ran into, most of which were within our test suite. Please take a look and provide feedback if necessary.
>- Impact:  Assuming code is sufficiently tested, there shouldn't be any issues. However, I would ask that at least one member from each team be prepared to smoke test a couple of their endpoints in staging to confirm everything is working properly. 

## Tasks

- [x] Perform testing for EZ application to confirm endpoints are working properly
- [x] Perform testing for CG application to confirm endpoints are working properly
- [x] Perform testing for EZR form to confirm endpoints are working properly
- [x] Report any issues to the team
- [x] Let PM know when completed and note results (success or issues) in the comments

## Acceptance Criteria
- The EZ, CG and EZR forms were tested to confirm expected functionality ahead of the production launch of the Faraday upgrade

**Comment by jadon1979** [comment]
All functioned properly as they should have
