### ISSUE TITLE
Capture and Add Submission Date Stamps to 674

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71229]
## Issue Description
_The pdf that is currently generated for 674 online claims is an old version, and it's missing the new "VA Date Stamp" field that is now included at the top of the new version of the pdf. As a stop-gap solution until we can update and map data to the new pdf, a "VA Date Stamp" field (and date) needs to be added to the top margin of the existing 674 pdf online claim is submitted. The date stamp should already be appearing on the signature line of the existing pdf. Additionally, the logic of the date stamp needs to be validated and possibly corrected, so the date stamp reflects the date the claim was submitted (and not the date the pdf was generated). The date stamps also need to be added to happy path and backup path claims._

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/5adabc44-e14f-47d5-9bc7-7727244c1969)

Example from 526:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/9629556b-c1e6-42ea-b5f7-3f900cfe5a76)

---
## Tasks
- [ ] Correct the date stamp variable to capture claim submission date (not pdf generation date)
- [ ] Add the date stamp text and date to the top right margin of the 674 pdf, so it appears as: "VA Date Stamp: mm/dd/yyyy"
- [ ] Confirm the date stamp is appearing in the signature line date field
- [ ] Ensure all submitted claims (happy path and backup) receive date stamps

## Acceptance Criteria
- [ ] Date claim was created appears in the upper right margin as "VA Date Stamp: mm/dd/yyyy" for all claims (happy and backup)
- [ ] Date claim was created appears in the signature line date field for all claims (happy and backup)
---
