### ISSUE TITLE
2024 Q1 SUPPORT TRACKING

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#71225]
### OVERVIEW
This is an effort to track the level of Tier 2 and on call support being offered by platform technical teams.

### ACTION ITEMS [LEAVE THIS EPIC OPEN]
If you are on Tier 2 support or on call and you are assigned a ticket:
- [ ] Make sure your name is listed under **assignees**
- [ ] Add your team's label under **labels** [our label is _platform-product-team_]
- [ ] Add the ticket to THIS sprint
- [ ] Work the ticket :)
*No need to assign an estimate for these purposes.

## OCTO Objective and OKR:
**Objective:** 
O2: Our platforms are the best way to deliver products at VA
**OKR**
O2 OKR2: Our platforms measure and improve the satisfaction of their internal users.
