### ISSUE TITLE
Design |  Migrate to Figma | Update Account Security Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71236]
## Background 
We need to migrate the account security sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [x] Add the file to the Account Experience project in Figma
- [x] Go through the file and update components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated if they're present in the file, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [x] Update all pages in Figma file accordingly

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [x] we've added a link to the Figma file in the product readme file.

**Comment by andaleliz** [comment]
Completed

**Comment by mtcA6** [comment]
pasting this list of things highlighted for migration in #71216 can we confirm all of those were moved? 
- [ ] Profile - Account Security
	- [ ] ✅ Mobile 
	- [ ] ✅ Desktop
	- [ ] ✅ Symbols
	- [ ] 📦 Iterations
	- [ ] 📦~Discovery~
	- [ ] 📦 ~Archive~

**Comment by pamela-drouin** [comment]
@andaleliz I double-checked the imported pages and went ahead and archived Iterations!
