### ISSUE TITLE
Design | Migrate to Figma | Move Nametag Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71231]
## Background 
We need to migrate the nametag sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [x] Add the file to the Account Experience project in Figma
- [ ] Go through the file and update components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated if they're present in the file, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [ ] Update all pages in Figma file accordingly

### Recommended Migration From #71216
- [x] My VA and Profile - Nametag
	- [x] ✅ Known use cases 

## Acceptance Criteria 
- [ ] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [ ] we've added a link to the Figma file in the product readme file.

**Comment by andaleliz** [comment]
@mattmarino-adhoc I forgot about this one when I shared that list in our DM. This would be a good one to work on, possibly in conjunction with the auth exp library file since the name tag is all over that library.

**Comment by pamela-drouin** [comment]
@mattmarino-adhoc Hi there! I noticed this was already imported into Figma. Did you import it? I'm just trying to figure out what needs doing since this ticket looks like it's in progress already (though it says ready).

**Comment by mattmarino-adhoc** [comment]
hey @pamela-drouin, the Nametag is already part of the Auth Exp library file and almost all set, with some more tweaking necessary (I noticed some differences in specs between Figma and what's live in Production).

**Comment by pamela-drouin** [comment]
cool, thanks @mattmarino-adhoc -- is this ticket that we're talking on right now extraneous?

**Comment by mattmarino-adhoc** [comment]
@pamela-drouin it appears it is, but let's confirm tomorrow.

**Comment by andaleliz** [comment]
@mattmarino-adhoc and I talked about this today and I agree with you two that it's extraneous and can be closed out.
