### ISSUE TITLE
Design | Migrate to Figma | Move Personal Health Contacts Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71239]
## Background 
We need to migrate the personal health care contacts sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [ ] Add the file to the Account Experience project in Figma
- [ ] Go through the file and update components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [ ] Update all pages in Figma file accordingly
- [ ] Add the breadcrumb where needed (probably hasn't been added since we launched the hub)

### Recommended Migration From #71216
- [ ] Profile - Personal health care contact
	- [ ] ✅ Mobile - Emergency contact and Next of kin
	- [ ] ✅ Desktop - Emergency contact and Next of kin
	- [ ] ✅ Symbols
	- [ ] 📦 Iterations
	- [ ] 📦  Explorations

## Acceptance Criteria 
- [ ] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [ ] we've added a link to the Figma file in the product readme file.

**Comment by andaleliz** [comment]
@jonathanjnelson are you actively working on these files anymore? Wondering if it's cool to migrate this over to Figma or you'd like us to hold off.  We are keeping things we're actively working on in Sketch for the time being.

**Comment by jonathanjnelson** [comment]
@andaleliz Sorry for my delay! I am not currently working on the Sketch file.

**Comment by jonathanjnelson** [comment]
That sounds good @andaleliz. Our team will be responsible for migrating the Sketch file to Figma. We will keep in the Authenticated Experience Team's Figma space but we will move over and update the components, etc.

**Comment by andaleliz** [comment]
@jonathanjnelson awesome! I'm going to close this ticket out and assume you all have your own ticket to track that work, but if that's not the case, feel free to re-open and assign whoever on your team will take care of it.
