### ISSUE TITLE
Design | Migrate to Figma | Move Hub Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71230]
## Background 
We need to migrate the Profile hub sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [x] Add the file to the Account Experience project in Figma
- [x] Go through the file and update components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated if they're present in the file, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [x] Update all pages in Figma file accordingly

### Recommended Migration From #71216
- [x] Profile - Hub landing page
	- [x] ✅ Mobile 
	- [x] ✅ Desktop 
	- [x] ✅ Symbols 
	- [x] 📦 Exploration: Long term plan for alerts 

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [x] we've added a link to the Figma file in the product readme file.

**Comment by pamela-drouin** [comment]
Hub progress:
- [x] Save sketch file to Mac
- [x] Import file to Figma
- [x] Archive specified pages
- [ ] clean-up:
  - [ ] set font styles to use library styles
  - [ ] update footer component
  - [ ] replace other components

**Comment by pamela-drouin** [comment]
Made some updates -- I am almost done updating the components in this file. I left some notes. Hopefully I will finish this soon!

**Comment by pamela-drouin** [comment]
Swapped out the current designs' Sketch links for Figma links (mobile/desktop). Still holding off on design clean-up till components are further along.

**Comment by pamela-drouin** [comment]
@mtcA6 carry 2 points into the next sprint to cover component clean-up.

**Comment by andaleliz** [comment]
@mtcA6 we need to carry over 3 pts into the next sprint.

**Comment by andaleliz** [comment]
complete!
