### ISSUE TITLE
Design | Migrate to Figma | Move Direct Deposit Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71234]
## Background 
We need to migrate the direct deposit sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [x] Add the file to the Account Experience project in Figma
- [ ] Go through the file and update components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated if they're present in the file, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [x] Update all pages in Figma file accordingly
- [x] Add the breadcrumb where needed (probably hasn't been added since we launched the hub)

### List from #71216
- [ ] Profile - Direct Deposit
	- [ ] ✅ Mobile
	- [ ] ✅ Desktop
	- [ ] ✅ Symbols
	- [ ] 📦 Discovery
	- [ ] 📦 Explorations
	- [ ] 📦 Iterations

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [x] we've added a link to the Figma file in the product readme file.

**Comment by andaleliz** [comment]
Note to future self:
- Mobile screens are done
-  For, Desktop screens, the artboard called `DD - Comp and Pen - Edit mode` and everything to the left is done.  Need to update the order of form elements to match mobile.
-  Other pages need a review.

@mtcA6 this will have to carry over into the next sprint. I'd like to finish it rather than have another designer finish up since I've started the work.

**Comment by pamela-drouin** [comment]
@andaleliz removing myself from this ticket to clean up my issue board. Happy to talk about it here though if you need me!

**Comment by andaleliz** [comment]
Complete
