### ISSUE TITLE
Design | Migrate to Figma | Move Notification Preferences Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71235]
## Background 
We need to migrate the notification settings sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [x] Add the file to the Account Experience project in Figma
- [x] Add the auth exp library
- [x] Go through the file and update components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated if they're present in the file, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [x] Update components from auth exp pattern library: heading w/ nametag, annotations
- [x] Add the breadcrumb where needed (probably hasn't been added since we launched the hub)

### Recommended Migration From #71216
- [x] Profile - Notification Settings
	- [x] ✅ Mobile 
	- [x] ✅ Desktop
	- [x] ✅ Symbols
	- [x] ✅ Specs
	- [x] 📦 Iterations
	- [x] 📦 Exploration - update help text in select screens
	- [x] 📦 Exploration - update missing contact info alert text
	- [x] 📦 Exploration - Add 1095-B form

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [x] we've added a link to the Figma file in the product readme file.

**Comment by mtcA6** [comment]
When migrating the notification preferences sketch files over it may make sense to take care of [#72952](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72952) at the same time, but maybe not, I leave it up to you all. We can handle it separately/later if that is too messy. Commenting on it now else I'll likely forget.

**Comment by pamela-drouin** [comment]
@mtcA6 I would keep them separate, and plan to migrate first, then fix the boards.

**Comment by pamela-drouin** [comment]
Notif settings progress so far:
- [x] Save sketch file to Mac
- [x] Import file to Figma
- [x] Update fonts
- [x] Archive specified pages
- [ ] clean-up:
	- [ ] set font styles to use library styles
	- [ ] update footer component
	- [ ] add breadcrumb component
	- [ ] replace other components

**Comment by mtcA6** [comment]
@pamela-drouin you mind throwing a size on this story?

**Comment by pamela-drouin** [comment]
@mtcA6 carry forward 4 points

**Comment by andaleliz** [comment]
Completo!
