### ISSUE TITLE
Design | Migrate to Figma | Move Military Information Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71233]
## Background 
We need to migrate the military info sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [x] Add the file to the Account Experience project in Figma
- [x] Add the Auth Exp library 
- [x] Go through the file and update VADS components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated if they're present in the file, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [x] Update all pages in Figma file accordingly
- [x] Update components from the auth exp library: section header, header with nametag, annotation, etc.
- [x] Add the breadcrumb where needed (probably hasn't been added since we launched the hub)

### Recommended Migration From #71216
- [x] Profile - Military Information
	- [x] ✅ Mobile 
	- [x] ✅ Desktop 
	- [x] ✅ Symbols
	- [x] 📦 Discovery
	- [x] 📦 Iterations
	- [x] 📦 Explorations
	- [x] `#`72292 - Design intent
	- [x] `#`73361 - Design intent iteration
	- [x] `#`72571 - post-feedback iterations
	- [x] `#`71889 - Explorations Enhanced military info - Hi fi

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [x] we've added a link to the Figma file in the product readme file.

**Comment by pamela-drouin** [comment]
@mtcA6 this is on hold while I switch focus to higher priority tickets (namely all that support the Military Information research study). Good news is the files are migrated! All that is left is component clean-up 😄

**Comment by pamela-drouin** [comment]
Carry forward 3 @mtcA6

**Comment by pamela-drouin** [comment]
@mtcA6 let's carry over the full points again. I can return to this ticket once I am done with research analysis/synthesis 😸

**Comment by mtcA6** [comment]
@pamela-drouin can you finish this ticket this sprint?

**Comment by pamela-drouin** [comment]
Now that the UAT research plan/convo guide updates are complete, I certainly can!

**Comment by mtcA6** [comment]
@pamela-drouin Can we make sure the military info page has the veteran status card section added to it especially since that is currently live in production?

**Comment by pamela-drouin** [comment]
@mtcA6 I took a look at what that work would involve, and it requires its own ticket since the user flow needs to be updated as well as both mobile and desktop screens. I created a [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81221) for this work.
