### ISSUE TITLE
Design | Migrate to Figma | Move Contact Information Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71232]
## Background 
We need to migrate the contact information sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

## Tasks 
- [x] Add the file to the Account Experience project in Figma
- [x] Add the auth exp library
- [x] Go through the file and update components and text styles as needed. This is a list of the available USWDS components that definitely need to be updated if they're present in the file, but there may be some other components that aren't symbols in Sketch, and make sense to update to a symbol in Figma.
  * Additional info USWDS
  * Alert USWDS
  * Breadcrumbs USWDS
  * Button pair USWDS
  * Button USWDS
  * Checkbox group USWDS
  * Checkbox USWDS
  * Featured content USWDS
  * Footer USWDS
  * Modal USWDS
  * Radio button USWDS
  * Select USWDS
  * Text input USWDS
- [x] Update components from auth exp library: section heading, nametag/header, and annotations
- [x] Add the breadcrumb where needed (probably hasn't been added since we launched the hub)

### Recommended Migration From #71216
- [x] Profile - Contact Information
	- [x] ✅ Mobile 
	- [x] ✅ Desktop 
	- [x] ✅ Symbols
	- [x] 📦 Iterations - Launched versions
	- [x] 📦 Iterations/discovery - modal and BAI
	- [x] 📦 Exploration- address validation accessibility improvement

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [x] we've added a link to the Figma file in the product readme file.

**Comment by pamela-drouin** [comment]
Contact info progress:
- [x] Save sketch file to Mac
- [x] Import file to Figma
- [x] Archive specified pages
- [ ] clean-up:
	- [ ] set font styles to use library styles
	- [ ] update footer component
	- [ ] add breadcrumb component
	- [ ] replace other components

**Comment by pamela-drouin** [comment]
@mtcA6 carry over 3 points (components still need updating)

**Comment by andaleliz** [comment]
Complete!
