### ISSUE TITLE
Design | Migrate to Figma | Update Connected Apps Sketch Files

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71237]
## Background 
We need to migrate the [connected apps](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/connected-apps) sketch files to Figma. 

In order to do that, we need to have our sketch files updated to the latest USWDS design components.

We need to update both [Mobile ](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e )and [Desktop ](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/p/EEFB2506-A317-4715-8397-7EA4304177BA/canvas )

## Tasks 
- [x] Identify v3 components available for use
- [x] Update all pages in Sketch file accordingly

## Acceptance Criteria 
- [x] at a minimum, mobile, desktop, user flow, and future state sketch files for personal information are ready to be migrated \
- [ ] we've created a follow-up FE story to implement the updated components in the UI

**Comment by andaleliz** [comment]
@mtcA6 I'd like to pull this one into the current sprint.

**Comment by andaleliz** [comment]
@mtcA6 I've added this file to Figma, and updated all the components I could. There are some DS bugs that need to be fixed, which will impact all profile design files. I created #72085 to track those. Alas, the design system bug tickets are in a different repo so we can't officially add those as blockers, but I'm subscribed to them and they are linked in the ticket.

We have a FE story as an AC on this one; given our meeting earlier today, do we still need to keep that as an AC for this particular ticket? If not, I think we can close this.

**Comment by mtcA6** [comment]
@andaleliz is there a link to the figma file?

**Comment by andaleliz** [comment]
@mtcA6 [there is](https://www.figma.com/file/eMR2XSTGnWQgF2YEphWK8O/Profile---Connected-Apps?type=design&node-id=0%3A1&mode=design&t=T55bTX1GPKFm4vPu-1)! I'm curious if you can see it.

@adamwhitlock1 this is a specific ["dev mode" link](https://www.figma.com/file/eMR2XSTGnWQgF2YEphWK8O/Profile---Connected-Apps?type=design&node-id=0%3A1&mode=dev&t=T55bTX1GPKFm4vPu-1). Can you check it out and lmk what this does for ya?

**Comment by andaleliz** [comment]
Oh great! Glad you can see it!  My initial thought is that it'll be confusing to have links to both, but talk me out of it. What would be the benefit of linking to both before we fully migrate over?

**Comment by mtcA6** [comment]
Thinking something like this: 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/b03c908d-3d2e-4472-a1f1-4c07c2fafbbe)

Why this is helpful, I have the profile readme page bookmarked and follow that to the related products to check the sketch files often. I'd like to get in the habit of looking at and using Figma.

**Comment by andaleliz** [comment]
Thanks @mtcA6. Are you thinking the same thing for all the links in the rest of the docs, or did you just want this on the product readme? [Here's one example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/use-cases/view-and-disconnect-apps.md) (there are links like this for every use case across all features)

**Comment by mtcA6** [comment]
Oh  no no that would be SOOOO MUCH! Those I'm thinking we would update later on when we're fully transitioning over. I think just one link at the bottom of the product readme so us non-figma licensed folks can locate the figma file is all we'd need for now. Then in Feb? or March? whenever we're ready to transition fully to figma we can update those other locations.

**Comment by andaleliz** [comment]
Got it! That all makes sense and I'll add those links to the docs as part of each ticket for the migration. 🙌

**Comment by mtcA6** [comment]
pasting this list of things highlighted for migration in #71216 can we confirm all of those were moved? 

	- [ ] Profile - Connected Apps
		- [ ] ✅ Mobile 
		- [ ] ✅ Desktop
		- [ ] ✅ Symbols

**Comment by adamwhitlock1** [comment]
> @mtcA6 [there is](https://www.figma.com/file/eMR2XSTGnWQgF2YEphWK8O/Profile---Connected-Apps?type=design&node-id=0%3A1&mode=design&t=T55bTX1GPKFm4vPu-1)! I'm curious if you can see it.
> 
> @adamwhitlock1 this is a specific ["dev mode" link](https://www.figma.com/file/eMR2XSTGnWQgF2YEphWK8O/Profile---Connected-Apps?type=design&node-id=0%3A1&mode=dev&t=T55bTX1GPKFm4vPu-1). Can you check it out and lmk what this does for ya?

This is really cool! There is even a VS Code extension for Figma where I can open the design and inspect it in 'dev mode' right in my editor. 🤯 

![Screenshot 2024-01-02 at 10 33 23 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/8670f7ab-afd4-44d1-a9a2-93f476969cfb)
