### ISSUE TITLE
[Design] MDT - Review content for the Introduction page (Unauth)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7125]
## User Story or Problem Statement
As a veteran that is not logged in, I need to be able to log into my account from the form's introduction page so I can place an order.

## Goal
_Review the content in the informational alert that prompts the veteran to sign in before placing an order. Currently, the content is written as if they're placing an application, which may be confusing because they aren't applying for anything when ordering resupply items._

## Objectives or Key Results this is meant to further
- _Finalizing the MDT ordering form_
---
## Tasks
- [x] _Review the current content in the informational alert on [the MDT form introduction page](https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction) (unauth)_
- [x] _Review the current button verbiage on [the MDT form introduction page](https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction) (unauth)_
- [x] _Document proposed content updates_
- [x] _Link the updated content to this ticket_

## Acceptance Criteria
- [x] _Markdown file containing content to be updated in staging_
---

**Comment by rileyorr** [comment]
<img width="669" alt="Screen Shot 2020-03-26 at 12 30 37 PM" src="https://user-images.githubusercontent.com/46329147/77688016-c11d4880-6f75-11ea-9290-e1e424e1a646.png">
The component above is displayed if the Veteran is not logged in and navigates to the form. The content should be updated to: 
Save time—and save your work in progress—by signing in before starting your order
When you’re signed in to your VA.gov account: (h4 utility)
* We can prefill part of your order based on your account details.
* You can save your order in progress, and come back later to finish filling it out. You’ll have 60 days from the date you start or update your order to submit it. After 60 days, we’ll delete the order form and you’ll need to start over.
[Blue button] Sign in to start your order

This content can also be found in [the markdown file for the introduction page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-introduction-screen.md). Let me know if if you have any questions @mojaray2k & @mr0sari0
