### ISSUE TITLE
[FE] - Add review button to pre-check-in details page

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#71267]
## Description 
Add review information button to appointment details page when clicked before pre-check-in is complete.

Add e2e test: A patient who clicks details from appointments list page, then clicks to verify info from details and completes pre-check-in

## Wireframes
- [Sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/aMkpY4r) 
- NOTE: The following is a screenshot of the Sketch file at the time this ticket was created, if the screenshot differs from the Sketch file when this ticket is worked, please raise the issue with the team during stand up

<img width="171" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNncwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fe0cb0815bba0c0750e4eb005aea0e8a78c3921/Screenshot%202023-12-05%20at%2010.51.15%E2%80%AFAM.png" alt="Screenshot 2023-12-05 at 10.51.15 AM.png" />

## Tasks
- [ ] [FE] Add button to details
- [ ] [FE] On click the button will start the the demographics review
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@loripusey is this in the TestRail test cases?

**Comment by loripusey** [comment]
@wullaski are we almost done with this one? It's been through 2 sprints, I'd hate to roll it over to a third.
cc @anita-halici
