### ISSUE TITLE
[FE] - Pre-check-in content updates

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#71266]
## Description
Update this text on confirmation:
<img width="278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk0wQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d6573ac0b1ef707d30af9b6f5ba8ab57f85783b/Screenshot%202023-12-05%20at%2010.43.57%E2%80%AFAM.png" alt="Screenshot 2023-12-05 at 10.43.57 AM.png" />

Since 45 minute window will be release, I think we can optimistically not wrap this in the feature flag.

We also need to catch up the subtitle content on the contact review page. This could be done in a rebase or in this PR.
The text should read:
`We can better follow up with you after your appointment when we have your current information.`

wireframe: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas

## Tasks
- [ ] [FE]- update content explaining the 45 minute text in pre-check-in
- [ ] [FE] - Update subtitle on contact page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
no longer needed

**Comment by brianseek** [comment]
Nothing new to validate beyond eng, moving to closed
