### ISSUE TITLE
Debt Portal IA Discovery

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#71265]
## Description

Based on comparative analysis and previous IA maps, 
Scenario: In common language describe the work or issue

Given: (The beginning state of the scenario)
When: (Specific action that the user takes)
Then: (Testable outcome that can be captured in the testing section, usually caused by the action in When)

## Tasks
- [x] Define top updates to be made based on comparative analysis and past qualitative analysis
- [x] Review [initial IA user maps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/3d1640f22a063e6d65c456a1c16064090f7ae35e/products/information-architecture/ia-design-docs/debt-portal.md) for combined debt portal
- [x] Review [site maps](https://app.mural.co/t/departmentofveteransaffairs9999/r/1672351979079)
- [x] [Create new IA user map draft](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701875723823/9500a14187ad9fd986ed97678263dee01b0d63ce?sender=ua78f969c4cddcbfe56b27885)

## Acceptance criteria

- [x] Top issues and updates identified
- [x] [Mural created that defines IA map and top issues](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701875723823/9500a14187ad9fd986ed97678263dee01b0d63ce?sender=ua78f969c4cddcbfe56b27885)

## Testing
- [x] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by mgleo** [comment]
Mural link: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701875723823/9500a14187ad9fd986ed97678263dee01b0d63ce?sender=ua78f969c4cddcbfe56b27885

**Comment by mgleo** [comment]
@Tom-Davis @HeatherRienks Moved to validate

**Comment by Tom-Davis** [comment]
Closing as complete.
