### ISSUE TITLE
Design | Burial | Review Error States on Review Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71261]
## Issue Description
_The existing review page for the Burial 530 form has some known issues, and adding the new fields to the form may trigger additional issues that need to be mitigated._

- [Sketch file](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/p/F90D6244-3B15-435E-A636-8B3AD3092014/canvas) for Burial form updates
- [CAIA review request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68984)
- [Collab Cycle Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65251)

---
## Tasks
- [ ] Review and mitigate existing review page issues
- [ ] Review and mitigate new review page issues triggered by new fields

## Acceptance Criteria
- [ ] Updated Sketch files
- [ ] CAIA approval
---

**Comment by fiorella-io** [comment]
- Created an enhanced version of the review page and included all the new fields 
- Captured issues on the existing forms and designed solutions for each

All links to designs and issues were added to this ticket
