### ISSUE TITLE
Add List of Repos to GitHub 101 Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#71279]
## Issue Description
Complete list of repositories available to team members upon receiving vets.gov-write access

---
## Tasks
- [x] Add [this list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54491) to [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2829058674/Github+101) in Confluence

## Acceptance Criteria
- [x] List added and checked for integration into document
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
[Updated to include new table](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2829058674/Github+101)
