### ISSUE TITLE
SPIKE | Confirm VA Date Stamp Appears on Burial Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71275]
## Issue Description
_The "VA Date Stamp" field in the upper right corner of the form should populate with the date the online form was submitted. This same date should be stamped on the signature line of the burial form. On some forms, the date stamp is missing from the "VA Date Stamp" field and/or the date being stamped on the form (date stamp field or signature line) is the date pdf was generated when it should be the date the online claim was submitted._

<img width="737" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFkwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e9e21b40ae3aa92f68afe5c39517d43dcc4b244/image.png" alt="image.png" />

See similar work done in #71125 and #71129 on the dependents forms.

---
## Tasks
- [ ] Confirm the date stamp in use is the claim submission date (not pdf generation date)
- [ ] Determine if the date stamp appears in the "VA Date Stamp Box" on the pdf
- [ ] Confirm the date stamp appears in the signature line date field
- [ ] Ensure all submitted claims (happy path and backup) receive date stamps

<!---## Acceptance Criteria
- [ ] Date claim was created appears in the "VA Date Stamp Box" for all claims (happy and backup)
- [ ] Date claim was created appears in the signature line date field for all claims (happy and backup)---!>
---

**Comment by steele-lm** [comment]
@evansmith Is this something you want to tackle at the same time as the pdf mapping work you're doing in #70721 ?

**Comment by evansmith** [comment]
@steele-lm I think it'd be good to do this one right after 70721
