### ISSUE TITLE
[CHIP] - CHIP security scan issue

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#71271]
## Description
From email:
Good Evening,

The CSOC CIR team has received a GitHub Advanced Security Secret Scanning SIEM Notable Alert for the Repository Name "chip”. We are providing a link to the alert for your awareness:

https://github.com/department-of-veterans-affairs/chip/security/secret-scanning?query=is%3Aopen+confidence%3Aother

We are requesting the following information regarding the repository:

Is this a valid secret, regardless of whether it is still in use? (Yes/No)
Describe what the secret is used for, including the VA System(s) impacted (if any)? (Yes/No)
Has the secret been revoked, rotated, or otherwise invalidated? (Yes/No)    
If yes, who performed the action, how was this confirmed and on what date?
Describe in detail the potential impact to the VA as a result of the exposure of the secret.  Be as specific as possible.

## Tasks
- [ ] [FE] investigate scan
- [ ] [FE] implement solution (if needed)
- [ ] [FE] respond to email with findings
- [ ] Update relevant documentations (readme and use cases)

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
