### ISSUE TITLE
Create isolated version of MHV Landing page app

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#71274]
## Description

Per [[EPIC]: Move landing page to isolated app build #70837](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70837), we want to opt in to app isolation. To do this for an existing app, we need to create a new copy of the app in vets-website while _temporarily_ preserving the non-isolated version.

The non-isolated version should exist until the content-build repo registers the isolated app and we are confident that the non-isolated version is no longer part of the build process.

### User story

As a Cartographers team member, I want our landing page to be built in isolation, so that deploys are done quickly and on-demand with less exposure to unrelated flaky CI steps.

## Acceptance criteria

- A "copy" of the landing page exists at a top-level app location, e.g. `src/applications/mhv-landing-page`. Maybe `git mv` to preserve git history?
- The "original" non-isolated copy exists at the old location until isolated version builds. We don't want `content-build` to choke on a missing app path.
- Work on [deploy, verify, cleanup](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71285) is assigned, begun. This is the "swap old for new" step

## Tasks

- [x] Create copy of code at `src/applications/mhv-landing-page`, preferably using `git mv`
- [x] Ensure copy of code still exists at `src/applications/mhv/landing-page`
- [x] Add CODEOWNERS entry for `src/applications/mhv-landing-page`
- [x] Copy medications landing page code (and dependencies) into the new MHV landing page location
- [x] Opt in to app isolation, clean up dependencies. 
Hint: `yarn check-app-imports --app-folders mhv-landing-page`

**Comment by dcloud** [comment]
If [this move, then isolate PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27001) works (and it seems to), then we may need fewer PRs than previously thought

**Comment by dcloud** [comment]
The medications team introduced breaking changes before our work could be merged, so this sets us back some time

**Comment by dcloud** [comment]
Marking this as blocked since multiple updates to the medications landing page were made, which blocks our "temporarily adopt medications about page" approach, and thus app isolation
