### ISSUE TITLE
[bug] Area of disagreement section not updating in Review page

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#71284]
## Value Statement
**_As a_** Veteran
**_I want to_** make changes to my area of disagreement while I'm reviewing
**_So that_** I can submit an accurate NOD

## Background Context
Found this error in the Review page. 
Staging user Charde 236.

Was able to replicate this error:
- Login and start form
- Choose an issue that's not the first issue on the list (or add a new issue)
- Go through form
- In Review page, edit issue, choose first issue on the list
- Error highlight does not show on the first issue disagreement, but shows on the second issue disagreement (which has a selection made)
- Click into disagreement of first error
- Try saving an option
- Does not save

Video:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTgxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7643e0d1c32a648b0c3d8cee9f3cb1628087ec28/2023-12-05%2015-05-37.mp4)

## Tasks

- [ ] Investigate cause of page not updating
- [ ] Fix cause of page not updating
- [ ] Prevent page update if there are errors
- [ ] Add unit tests

## Acceptance Criteria

- Area of disagreement can be edited within the form flow and on the review & submit page
- Changes made to the review & submit page area of disagreements is maintained upon update
- Area of disagreement on the review & submit page shows errors & prevents page update
- Code changes include unit test coverage

## Definition of done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Bringing it to Sprint 43
1. Robin is done with sprint work
2. It's launch blocking for NOD v2 release
3. Critical bug that blocks submission
4. Easy to fix
5. Much easier to fix than password PDF bug, which Rocio is working on

**Comment by Mottie** [comment]
Work merged in and ready for testing in staging @saderagsdale @eileen-coforma

**Comment by eileen-coforma** [comment]
@Mottie 

I can edit the disagreements in the review page now. The error style is still highlighting the wrong disagreement section, and the style does not disappear after updating disagreements.

Is the error styling part of this ticket?

**Comment by Mottie** [comment]
The error styling isn't part of this ticket. It's a form system issue that needs to be investigated & fixed. I haven't created a ticket for it yet.
