### ISSUE TITLE
Switch to isolated MHV landing page app, verify deploy to prod, then remove old version, clean up

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#71285]
## Description

Per [[EPIC]: Move landing page to isolated app build #70837](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70837), we want to opt in to app isolation. To do so, we need to temporarily keep the non-isolated version until we confirm the isolated version works in production.

To switch to the isolated version, we need to update [registry.json in content-build repo](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) to point to the isolated version of the app.

## Acceptance criteria

- Prerequisite completed: department-of-veterans-affairs/va.gov-team/issues/71274
- Isolated version of the app gets deployed to production
- Non-isolated version of app is removed *after* isolated version confirmed in production

## Tasks

- [ ] Update [registry.json in content-build repo](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) to point to new app
- [ ] Verify isolated version deployed to production
- [ ] Remove non-isolated version after other tasks completed
