### ISSUE TITLE
Include non-US countries in Yellow Ribbon

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7128]
### User Story or Problem Statement
Given Veterans look for Yellow Ribbon programs in and out of the US, 
I want to ensure the YR experience includes all countries 
so that folks can find the information they need. 
 
### Objectives or Key Results this is meant to further
-  Increased self-service
---
### Tasks
- [x] Gain access to Yellow Ribbon program data
- [x] Load the CSV ([YellowRibbonProgramSource_GIDS_03252020.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4388336/YellowRibbonProgramSource_GIDS_03252020.csv.zip)) into `dev` and `staging` GIDS:
       https://dev.va.gov/gids/uploads/new/YellowRibbonProgramSource
       https://staging.va.gov/gids/uploads/new/YellowRibbonProgramSource

### Acceptance Criteria
- [x] Remove `country` dropdown.
- [x] Add extra states to `state` dropdown.
- [x] Abstract states.json to platform/static-data
- [x] State dropdown is in alphabetical order

**Comment by MickinSahni** [comment]
Hi Matt, do you have access to YR program source CSV from prod GIDS you could share? We're hoping it'll help us include all countries in the YR tool. @mattpointzxer0

**Comment by mattpointzxer0** [comment]
From PROD? Nah. I'll slack you on gh along w/someone in EDU that can potentially help. Do you know the name of the .csv that contains the data you need?

**Comment by mattpointzxer0** [comment]
@MickinSahni ^^^

**Comment by MickinSahni** [comment]
> From PROD? Nah. I'll slack you on gh along w/someone in EDU that can potentially help. Do you know the name of the .csv that contains the data you need?

Thanks, Matt. @kelsonic, do you happen to know the file name?

**Comment by kelsonic** [comment]
@mattpointzxer0 it should be something like `yellow_ribbon_programs_source.csv` I believe! 🙂Basically whatever is on PROD for GIDS for the Yellow Ribbon Program CSV

**Comment by MickinSahni** [comment]
2020-03-26 
- Can't upload Prod yellow ribbon data csv to Admin center for GIDS. Check with Brian/Matts

**Comment by kelsonic** [comment]
We've discovered that out-of-country YRPs are denoted by the states `AA`, `AE`, and `AP`. Updating this ticket to 1) remove country dropdown and 2) include additional states to our state dropdown. https://dsva.slack.com/archives/C52CL1PKQ/p1585238508051200 @MickinSahni @andaleliz

**Comment by andaleliz** [comment]
Design spec updated to reflect removal of country field, [desktop](https://vsateams.invisionapp.com/share/P4W04QPWHTK) and [mobile](https://vsateams.invisionapp.com/share/36W0CAZHJ2U)

**Comment by kelsonic** [comment]
Thank you @andaleliz! You're the best! 🎉

**Comment by MickinSahni** [comment]
2020-03-30 PW Standup
- Validated on staging. No longer seeing Country dropdown and now seeing US regions/bases in State dropdown
![image](https://user-images.githubusercontent.com/13204473/77932033-f29a5a80-727a-11ea-8da7-4ae2c46ea96f.png)

![image](https://user-images.githubusercontent.com/13204473/77932055-fc23c280-727a-11ea-8399-a6abbec79fa4.png)

**Comment by andaleliz** [comment]
@kelsonic Thanks for including the update to the label as part of this, even though the design spec didn't include that (will update).  FYI we need to use sentence casing on form labels, so it should be `State or territory` (lowercase `t` on territory). Thanks!

**Comment by kelsonic** [comment]
Nice catch! Thanks @andaleliz! 🙂

**Comment by MickinSahni** [comment]
💯 validating after next deploy

**Comment by andaleliz** [comment]
@kelsonic - do we have the ability to alphabetize this list?  It feels a little weird to me to have that list of territories/military bases at the end.  I can only find one other drop down that has those `U.S. Armed Forces` options (1010ez) and it handles them by displaying them without the `United States` part. e.g. `Armed Forces Americas (AA)`

I think we should be consistent with other parts of the site - what do you think?
  

Also, @peggygannon, is `State or territory` still the correct label for the field if the options also include military bases?

**Comment by kelsonic** [comment]
@andaleliz We can but it will affect other teams that are using (or will use) the states JSON list... are we ok with showing the states alphabetized for every team across `vets-website`? @ncksllvn

**Comment by kelsonic** [comment]
>I think we should be consistent with other parts of the site - what do you think?

We're currently using the platform STATES list, which is intended to be used for all teams across `vets-website`. https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/static-data/STATES.json

**Comment by andaleliz** [comment]
Oooh, that sounds like it has big implications. If other teams are using this, and it's not already alphabetized, then I guess we _are_ being consistent with how other parts of the site are doing this? I'm surprised you can't alphabetize with React but obv I know jack about React!  I wonder how they're doing that on the 1010ez...

**Comment by kelsonic** [comment]
When we're importing that list of states we can alphabetize it for only our app, but just know it won't be consistent with other places in `vets-website` from what I've seen! 🙂

**Comment by andaleliz** [comment]
Can you point me to some examples of where this is being used, and it isn't alphabetized?  Curious to see how it's handled. Thanks!

**Comment by andaleliz** [comment]
I talked with the auth experience team, and there isn't a reason their state list is not alphabetized.  Other forms use the alpha ordered list - let's do the same.  

If possible, can we also follow the same format seen on other forms where the `armed forces` values are not prefixed with `United States` and have the abbreviation? Just to be consistent and give context in case that abbreviation shows up.

![Screen Shot 2020-03-30 at 1 44 51 PM](https://user-images.githubusercontent.com/55992116/78077002-88b2ab80-7375-11ea-8b07-03603c66d775.png)

**Comment by kelsonic** [comment]
> Also side note - why does Thailand show up when I select `Armed Forces Europe`?

This is because the `city` = `Thailand` and `state` = `AE`, so it's a result of bad data 🤦‍♂

**Comment by kelsonic** [comment]
> I talked with the auth experience team, and there isn't a reason their state list is not alphabetized. Other forms use the alpha ordered list - let's do the same.
> 
> If possible, can we also follow the same format seen on other forms where the `armed forces` values are not prefixed with `United States` and have the abbreviation? Just to be consistent and give context in case that abbreviation shows up.
> 
> ![Screen Shot 2020-03-30 at 1 44 51 PM](https://user-images.githubusercontent.com/55992116/78077002-88b2ab80-7375-11ea-8b07-03603c66d775.png)

PR is up for this! https://github.com/department-of-veterans-affairs/vets-website/pull/12076

**Comment by MickinSahni** [comment]
2020-04-01 PW Standup
- new PR to a->z sorting, waiting for deploy before validating

**Comment by MickinSahni** [comment]
Alphabetized in staging! 

![image](https://user-images.githubusercontent.com/13204473/78268589-64baab80-74d6-11ea-983d-b3ef76738116.png)
