### ISSUE TITLE
[FE] My VA C&A: Mismatch data in claims and appeals on My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#71289]
## Background
As reported in slack - we're seeing a difference in dates on My VA in claims and appeals vs what the claims status tool (CST) shows. Example below with user 22:

**As seen on My VA:**
![Screenshot 2023-12-05 at 3 57 49 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/9f5bd6ec-ff44-4832-820e-cade0f8a2e2c)

**As seen in CST detailed view:**
![Screenshot 2023-12-05 at 3 58 20 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/3a70ec0f-3d01-4bfc-811c-d29276f776f8)

**As seen in list of open claims within CST (looking for claim ID 600451940):**
![Screenshot 2023-12-05 at 3 59 54 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/36c91c50-2aca-4876-9810-beffdac1f97e)

## Tasks
- [x] Investigate mismatching dates between claims on My VA and the data in the CST
- [x] Determine what we need to do to resolve
- [x] Depending on LOE to resolve, address that as part of this ticket or work with PM to create a separate implementation ticket

## Acceptance Criteria
- [ ] We know why the dates are mismatched
- [ ] If within scope of this ticket we address the mismatch of data, or
- [ ] Separate ticket to address fix is created

**Comment by allisonlu** [comment]
@ajakabcin 

ready for validation for user 22! the date on the My VA Claims card should match the dates on the claim detail pages

**Comment by ajakabcin** [comment]
Confirmed! thanks @allisonlu
