### ISSUE TITLE
[Frontend] MDT - Update primary green buttons on the Introduction page (auth)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7129]
## User Story or Problem Statement
As a veteran that is logged in, I need to be able to progress from the form's Introduction page into the ordering flow so I can place an order. 

## Goal
_Update the design in staging so it aligns with the [prototype](https://vsateams.invisionapp.com/share/6CVSW1NTJB4)_

## Objectives or Key Results this is meant to further
- _Align the design in staging with the prototype so the form can be finalized._
---
## Tasks
- [ ] _Update both of the primary green buttons on the MDT's introduction page (auth) with [the content provided in the prototype](https://vsateams.invisionapp.com/share/6CVSW1NTJB4)_
- [ ] _Update the padding surrounding both of the buttons so it aligns with other forms on VA.gov_

## Acceptance Criteria
- [ ] _Frontend team please provide acceptance criteria_
---
