### ISSUE TITLE
DR | Fix JS error seen in Sentry

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#71299]
## Value Statement
**_As a_** developer
**_I want to_** fix errors that we're seeing from the contestable issue page
**_So that_** we're not blocking Veterans from completing the forms.

## Background Context

We've started seeing a `Cannot read properties of undefined (reading 'length') TypeError` and `undefined is not an object (evaluating 's.contestedIssues.length') TypeError` in Sentry. These appear to be from the Contestable issues widget shared by all 3 of our decision review apps.

## Acceptance Criteria

- [ ] All tasks complete
- [ ] All unit tests passing

## Tasks
- [ ] Fix code to prevent JS error
- [ ] Update unit tests

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Document any parts of code that can't be covered due to library limitations
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
