### ISSUE TITLE
Collaboration Cycle for Benefits team 1, Claim status tool , Claim Phase Experience

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#71293]
### VFS team name

Benefits team 1

### Product name

Claim status tool

### Feature name

Claims process overview page

### GitHub label for product

claim-status-tool

### GitHub label for feature

n/a

### Public DSVA Slack channel for VFS team

#benefits-management-tools

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

July 12, 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Product%20Outline.md

### Initiative Brief
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Improved%20Claims%20Process%20Understanding%20Initiative.md

#### Before 
[Current designs posted in a mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697490182408/80d09fbace925f5b50a50232f66e90f773d68d00?wid=75-1697490261656&outline=open)

#### After
[Proposed design in a mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697490182408/80d09fbace925f5b50a50232f66e90f773d68d00?wid=0-1697722885032&outline=open
)
### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the collab cycle kicckoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the appropriate workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1701876710562449)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

- Link to the [mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697490182408/80d09fbace925f5b50a50232f66e90f773d68d00?sender=u606d6bea4af40ec4fe659363) we will be presenting during design intent.
- [Research plan [Github]](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-10-Claim-Contextualization/research-plan.md)

** Team Members who will be in attendance**
- Jacob Worrell ([jacob.worrell@adhocteam.us](mailto:jacob.worrell@adhocteam.us))
- Skyler Schain ([skyler@coforma.io](mailto:skyler@coforma.io))
- Lauren Sinreich ([lauren.sinreich@coforma.io](mailto:lauren.sinreich@coforma.io))
- Julie Strothman ([julie.strothman@va.gov](mailto:julie.strothman@va.gov))

 
See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] User flow (required)
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes
- [x] Research plan
- [x] Any other artifacts you have so far
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C04KHCT3ZMY/p1702309949012329)
- [x] Meeting date/time: Friday, December 15, 2023, at 11:30 a.m. Eastern
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/4demsF8oQQ0zyRPTcp5R12BmB8bkFYVW07U9pYh-ySgSH7zme6smN0cegk6Q_mH6.Lk7UOkTlZkV_DtnX
  - Passcode: 8qs4@z^g
  
##### VFS actions

- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] Finalized [design mocks included in Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713276576012/25e677b1d846aff3bea16fc9175e473d5e509888?sender=u606d6bea4af40ec4fe659363)
- [x] The page title in the Fima file is called, **Midpoint review**
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-10-Claim-Contextualization/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-10-Claim-Contextualization/conversation-guide.md)
 
**Content artifacts**
  
- [ ] [Content edits [Figma]](https://www.figma.com/file/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=1723-23184&mode=design) **Note: ** A member of the CAIA team completed her content edits directly in the figma file. The page title in the Fima file is called, **CAIA Edits**

**IA artifacts**

- [ ] see "CAIA edits" above).

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C04KHCT3ZMY/p1713965738359599)
- [x] Meeting date/time: Tuesday, April 30, 2024 at 3:30 p.m. Eastern

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/wdsnvka5IwWnbDme8Q-s2Dwf8YCy79fcZ9LhuiZ-Zy3VbQ2CFfuxfGvm3MRXyu51.kr3jv4NOQtU-ztGB
  - Passcode: D5cQ?5D#
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below
 [Link to Contact Center ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86542)

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL: https://staging.va.gov/track-claims/your-claims/600519576/status
- [x] Specify which pages are included in the review     Status and Overview tabs. 
- [x] Staging test user information: Test user information in [this link](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv), row 25, Kyle Cole

  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request). [Content source of truth](https://docs.google.com/document/d/1WfWCfoQgKoMBg835VP7j_ptXmqb2o3RVme2u5dMOEr8/edit?usp=sharing). 
  
**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request): no IA sitewide feedback beyond what's attached as an issue to this epic. 

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/runs/view/5690&group_by=cases:section_id&group_order=asc)
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/runs/view/5689&group_by=cases:section_id&group_order=asc)
- [x] [Coverage for References] 100% of user stories tested in plan
- [x] [Summary(Defects): no additional defects found through functional QA and regression testing tracked in TestRails.
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  

You can view the claim status project code coverage by going to [this link](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report) and scrolling down to the Claim-status Application. 

For a more in-depth code coverage report please pull down `vets-website` and run the following command `yarn test:coverage-app claims-status`. This will provide you with a report of code coverage per file. Below is a list of the files that we made changes to.

**src/applications/claims-status/components/claim-overview-tab/**
- ClaimPhaseOverviewHeader.jsx
- ClaimPhaseStepper.jsx
- DesktopClaimPhaseDiagram.jsx
- MobileClaimPhaseDiagram.jsx

**src/applications/claims-status/components/claim-status-tab/**
- WhatWeAreDoing.jsx
- RecentActivity.jsx

**src/applications/claims-status/containers/**
- OverviewPage.jsx
- ClaimStatusPage.jsx

**src/applications/claims-status/utils/**
- helpers.js

**src/applications/claims-status/actions/**
- index.js -> submitRequest() and submit5103()
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88040). 
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C04KHCT3ZMY/p1720635170385729)
- [x] Meeting date/time: **Thursday, July 18, 2024 at 1:30PM ET**

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link ](https://oddball-io.zoom.us/rec/share/Oh-hlazQkAwEhHtLHyMhpd4OIDtvfrQ-iuJr1_ik8DEBbU4afPP9yS6Qs_O2FhUa._d80zNTZ2RveNKSO)
  - Password: jfmKQ%^6
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] [Link to the Readiness Review ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1799)

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by erinrwhite** [comment]
Hi folks, [IA feedback for Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72269) added a bit late as I was unexpectedly OOO yesterday. Thank you!

**Comment by kristinoletmuskat** [comment]
Hey @uxgary , did these changes launch at 100% into claim status tool yet?
