### ISSUE TITLE
Links for review for #71215

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#71305]
## Description
This ticket is to account for the link suggestions as part of #71215, which is labeled `frontend`.

**Note:** JJ reviewed on 12/12 and was having a hard time replicating the issue, so will need to connect with the proper engineering SME.

## Tasks
- [x] Reach out to original poster of 71215 Mike Eng to see if this is opening in new **window** or new **tab**
- [x] Connect with an engineer to determine if they are able to replicate the issue with the hyperlinks.
- [x] Make edits, (if needed), to the links on the Collaboration Cycle page
- [x] Prepare page for deployment
- [x] Deploy page
- [ ] Respond back to the original Github ticket.

## Acceptance Criteria

- [x] Issue has been confirmed, (replicated)
- [x] If applicable, page has been updated and deployed.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/71305?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by CherylEvans** [comment]
We reached out to Mike Eng on Slack. [LINK](https://dsva.slack.com/archives/CL181NRJQ/p1713977801010549)
We are trying to determine exactly how to fulfill this ticket and what we need from the engineers.

**Comment by CherylEvans** [comment]
@jknipes Here is the issue: Multiple links connect to Platform pages instead of linking to the Confluence source documentation. I performed an audit to find which links on the page were incorrectly linked to Platform pages vs Confluence pages by doing the following: Open page -> (E.G.: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) -> Right-click anywhere on the page and select INSPECT -> A developer panel will open up on the right side of the page -> Use Control F (Mac) or whatever 'FIND' function keys for your particular computer's OS -> type what you are searching for on the page (taget="_blank") and it will return every instance of the attribute on the page. Because code can be very touchy, I recommend searching for one word only and not the whole string (target). The up/down arrow will point you to every attribute instance. This tells you which links are tied to Platform pages (incorrect) and which links are tied to Confluence pages (correct).

**Comment by CherylEvans** [comment]
@jknipes @johnny-jesensky-adhoc @mengA6 
All CC touchpoint links are updated on the [CC page](https://vfs.atlassian.net/wiki/spaces/CC/overview)
The links open in the same tab when selected once SVP deployment on Monday is complete. 
I will update the ticket on Monday to ensure everything performs as expected.

**Comment by CherylEvans** [comment]
@jknipes @johnny-jesensky-adhoc @mengA6 All links now open in the same tab. Closing ticket.

**Comment by CherylEvans** [comment]
Closed. Complete
