### ISSUE TITLE
Attach "AssumeRoleWithWebIdentity" and SSM IAM policies to vets-api service account.

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#71315]
In the new EKS clusters, each application will its own SecretStore. The application's service account will need to have AssumeRoleWithWebIdentity and SSM IAM policies attached to the service account so the Secret Store can communicate with the AWS Parameter Store.

## Tasks

- [ ]  Attach AssumeRoleWithWebIdentity to vets-api AWS service account.
- [ ]  Attach SSM permissions to vets-api AWS service account.
- [ ]  Ensure the SecretStore and ExternalSecrets can deploy in the new EKS clusters.

**Comment by jennb33** [comment]
Per @RachalCassity this work may no longer be required; keep in the backlog. 
Currently we are all using the same AWS "SecretStore" role, and it is unknown if we are going to proceed with this ticket.

**Comment by jennb33** [comment]
Closing, Rachal doesn't think we will need this. We can always re-create if we need to.

**Comment by jennb33** [comment]
This ticket should happen after the EKS work is completed
