### ISSUE TITLE
Review Supporting Forms page

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#71327]
## Issue Description

The [Supporting Forms page](https://www.va.gov/supporting-forms-for-claims/) will continue to grow as more digital forms are added to the modernized site. How can we structure the page so that it's streamlined?

### Tasks
- [ ] Review page
- [ ] Brainstorm options for how forms can be structured on the page
- [ ] Share findings and proposed structure with Danielle and Mikki
- [ ] Implement changes

## Acceptance Criteria
- [ ] The Supporting Forms page has been updated so that the new format is sustainable and easy to scan.

**Comment by jennymayoco** [comment]
Upcoming forms that are candidates for the supporting forms page:

- 21-4148 (buddy statement)
- 20-10207 (priority processing)
- 20-10208 (upload evidence)

**Comment by jennymayoco** [comment]
#### Order of forms on page based on submission numbers from Content Office Hours notes:

- 4142
- 10210
- 0845
- 0966
- 10207
- 10206
- 4138
- 0847
- 0972

10208 isn't on this list because the team is confirming whether this form will still be digitized or not

**Comment by megzehn** [comment]
Thanks for documenting this list, @jennymayoco! I rearranged the order on the supporting forms page to match what you have here. 

Could you review when you get a chance? If the order looks good, I'll go ahead and publish. 

Updated preview link: https://prod.cms.va.gov/node/56902/latest

**Comment by megzehn** [comment]
Confirming Jenny reviewed the changes that we discussed and I published the first iteration.

There is still a second iteration that we want to share and get feedback on, so I think we can leave this ticket open.

**Comment by jennymayoco** [comment]
hi @strelichl, the second iteration hasn't happened yet and Kristin and I were thinking this is a good one for Sam to take on as one of their first IA tickets. We moved it to backlog for the time being

**Comment by scjwalker** [comment]
I checked with Mikki about doing further work on this page and she said that, based on the evaluation Jenny, she doesn't think there is any further work to do on this page right now. We can close this ticket.
