### ISSUE TITLE
BE | Profile | Monitoring | Separate group monitor into single monitors

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#71338]
## Background
As part of the code yellow initiative, a monitor has been created around profile updates.  See [Profile Update errors exceeding threshold](https://vagov.ddog-gov.com/monitors/169176).  This monitor will send an alert to the #accountexp-authexp_alerts channel if the total volume of these endpoints deviates outside of a set threshold.

The goal is to break out each endpoint so that it has it's own monitor.  This will allow the Profile team to tailor the triggers and alerts for each endpoint.

## Tasks
- [x] Add Address Monitor/Alert for Updates
- [x] Add Communication Preferences Monitor/Alert for Gets and Updates
- [x] Add Direct Deposit EDU (Ch33 bank account) Monitor/Alert for Gets and Updates
- [x] Add Email address Monitor/Alert for Updates
- [x] Add Gender identity Monitor/Alert for Updates
- [x] Add Military History Monitor/Alert for Gets
- [x] Add Personal Informations Monitor/Alert for Gets
- [x] Add Preferred name Monitor/Alert Updates
- [x] Add Rating Info Monitor/Alert for Gets and Updates
- [x] Add Telephone Monitor/Alert for Updates
- [x] Add document with links to all Profile monitors and alerts.

## Acceptance Criteria
- [x] Test each endpoint to ensure it is sent to the #accountexp-authexp_alerts channel
- [x] Document with links to above Profile monitors and alerts has been added.

**Comment by tpharrison** [comment]
You can [bookmark this page](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/observability_references.md) which has quick links to Profile related dashboards, logs, and monitors.
