### ISSUE TITLE
Implement Submission Metadata for Intake Polling

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#71336]
In #70944 we defined the requirements for a FormSubmission record. This ticket will implement that record in vets-api

Class: FormSubmission
Parent class: Application Record

- `id`: primary key, required
- `created_at`: date time, required
- `form_type`: string, required
- `form_data`: json, required
- `in_progress_form`: foreign key on InProgressForm, optional
- `saved_claim`: foreign key of SavedClaim, optional
- `user_account`: foreign key of UserAccount

 Class: FormSubmissionAttempt

- `id`: primary key, required
- `created_at`: date time, required
- `form_submission`: foreign key of FormSubmission, required
- `status`: enum, required
  - success
  - failure
  - pending
- `in_progress_form`: foreign key on InProgressForm, from form_submission, optional
- `saved_claim`: foreign key of SavedClaim, from form_submission, optional
- `user_account`: foreign key of UserAccount, from form_submission

## Acceptance Criteria
- [ ] FormSubmission record created per schema
- [ ] FormSubmissionAttempt record created per schema
- [ ] Unit tests created
