### ISSUE TITLE
IA support for FSR Complete a Subtask for Debt Resolution team

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#71331]
## About your team

- Team name: 
-	OCTO-DE product owner: @denisecoveyduc 
-	Product manager: @Tom-Davis 
-	Designer: @josephrlee, @mgleo, @charlottecesana 
- Accessibility specialist: N/A
- Content writer: N/A
-	Slack channel: #debt-resolution
 
### Describe what you need in a few sentences:

We're [currently working on updating our wizard](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/68211) for the [Financial Status Report](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction) to follow the [complete a sub-task pattern](https://design.va.gov/patterns/help-users-to/complete-a-sub-task), and with that, we'll be creating quite a few new pages. [I added some proposed URLs](https://sketch.com/s/50583485-ba58-4ef8-ae04-2c274a792547) and followed the [URL standards in the Content style guide](https://design.va.gov/content-style-guide/url-standards#url-standards). We'd like some feedback on the proposed URLs. 

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [X] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [ ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [ ] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is** ....
- **Provide date if available**: xx/xx/xxxx

#### Timing for your next step: 
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [ ] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [ ] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [ ] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: 
- **Collab. Cycle Ticket Opened (date)**: xx/xx/xxxx
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**:
- **User flows**:
- **Prototype or mockups**:
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**:
- **Research plan:**
- **Any epics/issues that may be helpful**:
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [ ] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by josephrlee** [comment]
@coforma-terry, just letting you know that this is a draft, I'll reach back out once it's ready to be reviewed!

**Comment by coforma-terry** [comment]
@josephrlee - do we have an update on this yet? Thanks

**Comment by HeatherRienks** [comment]
@mgleo and @charlottecesana  - FYI

**Comment by josephrlee** [comment]
@coforma-terry, yes, we're ready to move forward with feedback this request! 

cc: @HeatherRienks @mgleo @charlottecesana

**Comment by josephrlee** [comment]
@strelichl Thanks for the update. We probably won't be getting our study at the end of December anymore. So, reviewing the content in early January would still work for us. Thanks!

**Comment by josephrlee** [comment]
Hi @strelichl,

@charlottecesana can better answer the question for dates.
As far Sketch to Figma, we have migrated our file over to figma. Here is the updated figma file to review: https://www.figma.com/file/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---Streamlined-Waiver?type=design&node-id=24%3A25440&mode=design&t=lmBnNBWGXfw9Vkgu-1

**Comment by charlottecesana** [comment]
Hi @strelichl - our research plan and conversation guide are ready and we will have to submit them for platform approval and Perigean recruiting. This will take at least 2 weeks. I'd like to aim to start interviewing 1/22 or 1/23. We are hoping to get content feedback before then so that we share nearly final content with interview participants. 
Thank you!

**Comment by kristinoletmuskat** [comment]
Hi ya'll, here is that final IA documentation for the URLs on the subtask: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/debt-fsr-new-wizard.md

Let us know if you encounter any problems or weirdness during implementation, or if you have any Qs.

**Comment by kristinoletmuskat** [comment]
Hey ya'll, here is the new plan "Version 2" for the FSR subtask placement we just went over: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1682537441750/a9937e9953d80c221c5165131f611026e0419c7b?sender=ua67f17f1c416a96ea04d2476

I'll also update the markdown file above this week when I have a chance.

**Comment by josephrlee** [comment]
@kristinoletmuskat Here's the [analytics that we currently have for the wizard](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20231101&_u.date01=20240117&_r.drilldown=analytics.pagePath:~2Fmanage-va-debt~2Frequest-debt-help-form-5655~2Fintroduction~2F,analytics.eventCategory:Interactions/). It looks like it's pretty even split between those that visit and go through the wizard and then those that go directly to start the form. I can hop on a quick call if needed to parse through the data as well!

**Comment by kristinoletmuskat** [comment]
Just tagging @laurwill for the analytics above -- it looks like more ppl are going through the wizard than right into the 5655 form, but still a lot of folks going into that form.

**Comment by mgleo** [comment]
@kristinoletmuskat @laurwill 
The use of the Wizard is probably increased because of the current design of the page. The Wizard takes up a lot of space on the page. During studies, it has appeared that some participants believed that answering the questions on the Wizard was what they needed to do in order to access the form.

<img width="564" alt="Screenshot 2024-01-18 at 4 57 32 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/67d4b5c0-f002-4d93-9d76-b8d453a0873f">

**Comment by coforma-jamie** [comment]
> [!NOTE]
> ## Accessibility Digital Experience (DE) Ticket Status Update
> Accessibility DE is OCTO’s new accessibility team. We’re working on a new intake process. In the meanwhile:
> - This ticket has been moved to validate and will be closed on the Accessibility DE pipeline (only).
> - This ticket will remain “open” until the work from content and IA is completed.
> 
> If you need additional accessibility support, contact the Accessibility DE team on [#accessibility-help](https://dsva.slack.com/archives/C8E985R32).
> **Thank you for working with the accessibility team!**
