### ISSUE TITLE
[Design] Accessories page empty state

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7134]
## User Story or Problem Statement

Problem description. How might we let the Veteran know that they do not have any currently-authorized accessories?

## Goal
Show users a page state reflecting the absence of authorized accessories and instructions on what to do if there is a problem.

## Tasks
- [x] Create a mockup of this state
- [x] Upload to invision
- [x] Update GH documentation

## Acceptance Criteria
- [x] New state is reflected in GH

**Comment by rebeccawalsh** [comment]
Prototype links, descriptions, and content for this ticket can be found in GH here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-accessory-selection.md#use-case---veteran-has-no-accessories-on-record
