### ISSUE TITLE
[spike] SC | Investigate issue that briefly prevented form submission

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#71344]
## Value Statement
**_As a_** developer
**_I want to_** investigate why form submission is blocked
**_So that_** we can fix the issue preventing Veteran's from submitting our form

## Background Context

During our call with a Veteran, we were not able to ascertain the cause of the validation issue on the review & submit page. It appeared that the Veteran had selected contestable issues for submission, but after saving & returning to the form, no issues were selected. After multiple attempts, we gave up and had the Veteran restart the form and they were able to submit. We did save the in progress data to investigate the problem. There may be other Veterans encountering similar issues.

## Acceptance Criteria

- [ ] Investigate the problem
- [ ] Confirm if we know the root cause or not
- [ ] report back to the team on possible solutions
- [ ] Write solution ticket
- [ ] Write L+M ticket, if needed

## Tasks
- [ ] Investigate cause (**Timebox to 3 hours maximum**)
- [ ] Fix problem
- [ ] Add unit tests
- [ ] See if we can set up logging to identify this particular error (contestable issues absent, even though selected) so we can check for re-occurences.

## Definition of Ready 
- [ ] Timebox is defined
- [ ] Nature of the issue defined

## Definition of Done
- [ ] Document any parts of code that can't be covered due to library limitations
- [ ] We know if this can be logged, and add L&M if possible
- [ ] Sync with product and design first, and make a separate ticket

## Out of scope / next steps
- Coding solution not included here 
- Determine if setting up [review errors](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1615) would better inform Veterans of the problem

**Comment by saderagsdale** [comment]
Marking this one as a low priority, I think it can wait since it doesn't appear to be happening to other users. @Mottie

**Comment by data-doge** [comment]
@data-doge send Robin redacted data for most recent instance.

**Comment by saderagsdale** [comment]
@Mottie re-wrote the criteria in this spike to exclude code fixes and L+M. Let's timebox the investigation and decide next steps after.

**Comment by HeatherWidmont** [comment]
@Mottie will start after he gets the data from @data-doge - probably tomorrow

**Comment by data-doge** [comment]
Sent redacted IP data to @Mottie, and sent unredacted form data and metadata to @Mottie in Teams.

**Comment by HeatherWidmont** [comment]
@data-doge & @Mottie will discuss how to replicate that specific issue with that specific Veteran on that call at a later date

**Comment by saderagsdale** [comment]
Sade will try to replicate with the SC form
@Mottie and @data-doge will check DD RUM dashboard

**Comment by Mottie** [comment]
With the data I was provided, I found an issue in the international address schema, but I was not able to duplicate the problem we saw within the contestable issues pages. I'll open a fix ticket for the address work.

**Comment by HeatherWidmont** [comment]
@Mottie to look at DD RUM dashboard before fixing broken unit tests

**Comment by eileen-coforma** [comment]
PR merged, waiting for staging, need to test with user with null zip code before deployment.

**Comment by Mottie** [comment]
Tested in staging, it's now working as expected! 🎉

**Comment by HeatherWidmont** [comment]
@Mottie will take another look at the RUM today & if there are no issues he will close this ticket

**Comment by Mottie** [comment]
After reviewing a few of the over 980 RUM sessions from the past 2 weeks, it's difficult to determine which sessions are using international addresses. Almost every RUM session has errors, usually global platform or CMS errors, so we can't distinguish which sessions to review :(

Either way, we need to monitor the "Validation issue not displayed" error message in Datadog

**Comment by HeatherWidmont** [comment]
@Mottie will create a ticket for monitoring the "validation issue not displayed" error message & link it here. We can then close this ticket

**Comment by Mottie** [comment]
Closing this tickets and moving Datadog work to #72855
