### ISSUE TITLE
Facility Locator Edge Case Dashboard - Data QA & iterate

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#71355]
## Issue Description

This is a continuation of the [facility locator data ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/69515) for the [Facility locator edge case request](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/61633).  We need to complete the [dashboard](https://va-gov.domo.com/page/1954588686) set up and data QA portion of this work.

[dashboard mock up](https://docs.google.com/presentation/d/1WQIc7Rlgr1pET3Kmzkfr_wUn7u6-Y6wEVG_V2HgF7wg/edit#slide=id.g267a520b92f_0_168)

[worksheet](https://docs.google.com/spreadsheets/d/1siGoD2djYPr3adFjjO_pO_9Hf1WhqVbe-EaRFt3yYIQ/edit#gid=1442645657)

[WIP Domo dashboard](https://va-gov.domo.com/page/1954588686)

Requirements:
Facility Locator page url: va.gov/find-locations/
Aggregation: monthly
Updates: monthly
Metrics: users, previous page path, device, browser, page path, pageviews, events....

---
## Tasks
- [x] Create cards as defined by mock up
- [x] QA cards against GA reports
- [x] Update dataset as needed based on findings 
- [x] Iterate 

## Acceptance Criteria
- [x] Dashboard is ready for team review
---

**Comment by michelle-dooley** [comment]
The 'escape hatch' link is not currently tracked, will need to get Jamie set up in GTM. 

<img width="561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEpNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8adb26b261b373d451cb154c4558c67305fffb86/image.png" alt="image.png" />

<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGxNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d52d32fa8a5c322dd192c1a1b38f6a4219907873/image.png" alt="image.png" />

**Comment by dorseypa1** [comment]
> @dorseypa1 and @ChristineYoungZA need to make some update for the search metrics. We can discuss when we meet but wanted to document here for reference.
> 
> Total Searches: event_label = 'fl-search' should be used instead of 'search_query' Click through rate: event_label = 'fl-results-click' / total searches (fl-search)
> 
> We need to add the following fields to the dataset, They are part of the event_action field that are populated/collected via the data layer code:
> 
> <img alt="image.png" width="452" src="https://camo.githubusercontent.com/a511d70eb66128a64e925f88fffd0e74cceebf8a0f704e456aba8aa6068cb728/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842426430354e5157633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d663535303666323434633066646334326663353535363432333862333934323866643537306665622f696d6167652e706e67">
> 
> <img alt="image.png" width="890" src="https://camo.githubusercontent.com/6b58951a1b92496e97b6ce8c048ef30d9a3ddaa1bdaf29933d881872a9e98185/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a426148424264315a4e5157633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d323037336235396162323038343937343662333933356530373836343031646566393839323834322f696d6167652e706e67">

The images seem to be broken.  Can you resend?

**Comment by jestutt** [comment]
@michelle-dooley  Click event added.
<img width="683" alt="Screenshot 2023-12-13 at 12 08 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/b741aa29-66b6-49e3-8608-b86f5a6c2267">

**Comment by michelle-dooley** [comment]
Great thanks @jestutt !! @ChristineYoungZA we won't see in data yet b/c it will just now start tracking so we will have to QA that when we get an updated dataset.

**Comment by michelle-dooley** [comment]
Sprint update: QA work will continue into next sprint.

**Comment by michelle-dooley** [comment]
I have created a table in the [QA worksheet](https://docs.google.com/spreadsheets/d/1siGoD2djYPr3adFjjO_pO_9Hf1WhqVbe-EaRFt3yYIQ/edit#gid=1705523695) for all the cards, since this is net new need to make sure numbers align and we are answering the questions at hand. 

@Blivaditis - is looking at QA for Highlights, Findablity and Click Interactions sections.

@ChristineYoungZA - please Search and Surveys section for notes on changes to those cards.

**Comment by michelle-dooley** [comment]
@ChristineYoungZA - can you also work on the formatting. Would like to have some spacing between the cards similar to what you see on other dashboard so it is easier to read. (yellow highlight areas are what I am referring to). 

<img width="1542" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmwrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2148bcb512424eab056a92946e3e78b5436cda1/image.png" alt="image.png" />

**Comment by johnny-jesensky-adhoc** [comment]
Marking this as _Done_. Next steps on this dashboard will be adding some additional quarters worth of data, then will be reviewing with the team that submitted this. As of now, the overall report has been prepared and QA'd, meeting the AC.

This additional follow-on work will be pursued in [this separate ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/74966).

FYI @Blivaditis, @ChristineYoungZA , @dorseypa1
