### ISSUE TITLE
[Design] Implement feedback on HA Drupal Page

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7135]
## User Story or Problem Statement
As a Veteran, I need to view a page with clearly written content so that I can understand and utilize my benefit.

## Goal
To create a content page that is helpful for Veterans

## Tasks
- [x] Get content reviewed by VSP / Content
- [x] Make content updates to mockup
- [x] Place finalized content into GH

## Acceptance Criteria
- [x] Finalized content reflected in GH

**Comment by rileyorr** [comment]
I updated the mocks and uploaded the Word document containing all the edits to [the file in GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-drupal-pages.md).
I was going to write the content out in code block format like the other pages, but didn't because I figured the CMS team would reference the Word Doc when updating in Drupal.
