### ISSUE TITLE
Platform Support Dashboard

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#71361]
## Issue Description

This is a continuation of the work we are doing for the platform support team [survey dashboard](https://va-gov.domo.com/page/1729270793).  

---
## Tasks
- [x] Determine how to get new survey dataset merged with current dataset
- [x] Set up Domo to append (not replace so as to no over ride v1 of survey) each week (need to figure out how to only pull 1 week worth of data from Optimal)
- [x] Finish survey card set up
- [x] Copy/link cards from [Platform Github Ticket dasbhoard](https://va-gov.domo.com/page/835197588) - filter the cards on support dashboard to only show platform support tickets (confirm labels they want included)

## Acceptance Criteria
- [x] Dashboard is ready for hand off to team
