### ISSUE TITLE
ARM Analytics Request Updates

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#71365]
## Issue Description
Analytics request to PA&I team and updating final analytics report.

---

## Tasks
- [x] Update Analytics Request with Feedback
- [x] Send workshop updates to team
- [ ] Send emails to 21-22 team for numbers
- [ ] Send PA&I request to Zach

---

## Acceptance Criteria
- [ ] Request delivered to Zach

**Comment by jfinnerty13** [comment]
Updated request, waiting on Alex and Lindsay to confirm before sending to Zach.
https://docs.google.com/document/d/1FZ5cl6YT6gcHS1TM9uo8WwAHrbq-KBGIJYK2_IjcLtM/edit?usp=sharing

**Comment by jfinnerty13** [comment]
[12_2023 Analytics Recap.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1E3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62a23cc0791c1fd7ebd3ccedb56f9dafa8a6704b/12_2023%20Analytics%20Recap.pdf)
Sent recap to team

**Comment by jfinnerty13** [comment]
Confirmed with Alex. Lindsay sent to 21-22 team, and Zach will be submitting to PA&I tomorrow.
