### ISSUE TITLE
Confluence & GH Updates

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#71366]
## Issue Description

We need to update the team [confluence pages](https://vfs.atlassian.net/wiki/spaces/AT/overview) and our [GH templates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-feature-request-bug-report.md) per our recent audit (notes below).

[Confluence update notes](https://docs.google.com/document/d/1ivnwbjUFsOOmiuWX1pbNa91DpCDQD7_n8ymOpDRnXWs/edit)
[GH template update notes](https://docs.google.com/document/d/1e5Sd9oLk_ugHqGzU4hZeskTsn-RgT40IQ1anxsIcXg0/edit#heading=h.cr9mvp76ngck)

---
## Tasks
- [x] Update GH templates
- [x] Update Confluence pages

## Acceptance Criteria
- [x] GH templates and Confluence pages up to date.
---
