### ISSUE TITLE
GA4: Migration & Costs

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#71372]
## Issue Description

This is part of the larger GA4 migration work. This ticket will include the work needed to continue the web component set up/configuration and the cost analysis/forecast for GA4 and MHV.

---
## Tasks
- [ ] GA4 web component set up/configuration
- [ ] GA costs analysis (get contract details) - Michelle will own this
- [ ] Review cost with Andrea and Dave
- [ ] Review MHV set up and costs with team

## Acceptance Criteria
- [ ] GA4 migration tasks completed as defined.
---
