### ISSUE TITLE
[Research] Multiple file uploads

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#7139]
## User Story or Problem Statement

As a user providing supporting documentation for a form, they should to be able to upload multiple forms at once so they don't have to waste a lot of time uploading and defining file types for one file at a time.

## Goal

Make submission of supporting evidence as painless as possible for users

## Objectives or Key Results this is meant to further

- Improve site usability
- Ease user pain point of only being allowed to upload a single file at a time (e.g. form 526 supporting evidence)

## Tasks

- [ ] What design system changes need to be implemented? Related #76.
- [ ] What back-end changes would need to be implemented?
- [ ] What front-end changes need to be addressed?

## Acceptance Criteria

- [ ] Determine feasibility of allowing the user to upload multiple files at once.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
