### ISSUE TITLE
[bug] Proceeding with a password-encrypted PDF without adding password

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#71406]
## Value Statement
**_As a_** Veteran
**_I want to_** make sure my PDF can be unlocked
**_So that_** I can submit evidence with my request

## Background Context
Found this error in Upload additional evidence. 
Staging user Charde 236.

Was able to replicate this bug:
- Login and start form
- Choose 'Additional evidence' for Board Review Option
- Upload a password-protected PDF
- Ignore password field
- Click 'Continue'
- Proceed to the Review page
- Try submitting the form
- Get backend error, not validation error

Video:

https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/11a5169e-2742-46ad-aad0-e7e528307c61

- Add here

## Acceptance Criteria
- [x] When a user uploads a password-protected PDF, a required field appears for the password.
- [x] If a user tries to continue without entering a password, they are prevented and an inline error appears for the required field: Please provide a password to decrypt this file. They can't proceed to the Review page.
- [x] If a user enters the wrong password for the PDF, they get an inline error: We can't unlock your PDF. Save your file without a password and try uploading it again. They can't proceed to the Review page.
- [x] If user enters the right password, it would display the file name and size, and are able to proceed to the Review page.
- [x] If the user enters the right password, but the backend can't unlock it, they get an inline error: We can't unlock your PDF. Save your file without a password and try uploading it again. They can't proceed to the Review page.

## Designs and Build Notes
- Add here

## Tasks
- [ ] Check for a validation problem on the upload page
- [ ] Check for schema update necessary for review and submit page

## Definition of Ready 

- [ ] Bug behavior recorded and attached to ticket
- [ ] AC defined (expected behavior)

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@eileen-coforma add video recording

**Comment by eileen-coforma** [comment]
Video recording added

**Comment by data-doge** [comment]
Notes from huddle:
- Check for SC as well
- Probably simple validation problem on upload page.
- Possible schema update necessary for review and submit page.

**Comment by saderagsdale** [comment]
@eileen-coforma We'll need to define the expected behavior in the acceptance criteria before this can be picked up.

**Comment by saderagsdale** [comment]
@data-doge or @Mottie Can someone add the dev tasks to the ticket so it can be estimated?

**Comment by saderagsdale** [comment]
@rocio-desantiago Howdy - let me know if you'd like additional context for this one after reviewing what Eileen added to the ticket.

**Comment by rocio-desantiago** [comment]
Some notes from discovery today:
* breakpoint doesn't trigger NOD when Continued with protected file but was triggered for SC-995
* maybe this has to do with mousedown event? (click handler vs mousedown handler?)
* blur handler hack functioning as validation?

<img width="519" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFpqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43dc8e57800091848cc731ee1d9f442c5b7a7854/Screenshot%202023-12-14%20at%208.59.07%E2%80%AFPM.png" alt="Screenshot 2023-12-14 at 8.59.07 PM.png" />

**Comment by rocio-desantiago** [comment]
Testing with this file and discovered that this is only a bug with NOD. Confirmed Supplemental Claims file upload works.

[locked_pdf_password_is_test.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94e0dc0b9dbc7006f1f2c327532ea2a19485b5c9/locked_pdf_password_is_test.pdf)

**Comment by saderagsdale** [comment]
@rocio-desantiago Any idea why it affects NOD and not SC?

**Comment by rocio-desantiago** [comment]
@saderagsdale Still investigating. 

Compared the following files between NOD and SC and files in Platform.
Will pair with @Mottie to get some background context on difference.
_Files investigated so far are the following:_

**In Platform**
  - src/platform/forms-system/src/js/validation.js Looked at validateFileField - if there’s an error, an error message should be displayed. Which for our case - the error does display
  - src/platform/forms-system/src/js/fields/FileField.jsx - Files checked out to check where the continue button is being validated.
In platform
  - src/platform/forms-system/src/js/definitions/file.js
  - src/platform/forms-system/src/js/containers/FormPage.jsx - added debugger to `callOnContinue()` to investigate with the `va-button pair` behavior

**In Appeals**
- src/applications/appeals/995/utils/upload.js
- src/applications/appeals/shared/utils/upload.js
- src/applications/appeals/10182/utils/upload.js
- src/applications/appeals/995/pages/evidenceUpload.js
- src/applications/appeals/10182/pages/evidenceUpload.jsx
- src/applications/appeals/10182/content/EvidenceUpload.jsx
- src/applications/appeals/995/config/form-0995-schema.json
- src/applications/appeals/995/config/form.js
- src/applications/appeals/10182/config/form.js

**Comment by Mottie** [comment]
I opened a PR with a possible fix... we will need a thorough review before merging, so it'd be better to wait until after the holidays to finalize and merge this work (if it is the solution we go with)

**Comment by Mottie** [comment]
Work merged in and ready for testing in staging @saderagsdale @eileen-coforma

**Comment by eileen-coforma** [comment]
@Mottie @rocio-desantiago 
The validation is working now. User can't proceed to Review page without adding a password.

I couldn't test one of the AC. I don't know how a successful password-protected PDF looks like, because it keeps giving me the `We can't unlock your PDF. Save your file without a password and try uploading it again.`

**Comment by eileen-coforma** [comment]
@Mottie sent me a test PDF with password, and it unlocks it properly. I was able to validate the AC and move to Review page.

All ACs met.
