### ISSUE TITLE
Setup Domo boards for Metrics on the FDG space

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71411]
## Purpose
We'd like to have a dashboard that lets us easily monitor data like:
top viewed page
page views of each phase
page views of resource space

## Tasks
- [ ] Finalized desired data to observe
- [ ] Set up Domo dashboard

## Acceptance Criteria
- [ ] dashboard is operational
