### ISSUE TITLE
Sync with NDB team to share ideas on Dependents design pattern components

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71413]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] Meet with the Non-Disability Benefits team to discuss what design pattern components we can share for Pension and other online forms that require this component
- [ ] Document requirements for the design component discussed
- [ ] Document where in the user flow of the online Pension form this would live

**Not in scope:** Updating Pension online form designs to follow this shared design compontent

## Acceptance Criteria
- The Pension team designer will have a better understanding of the requirements for the Dependent design component pattern discussed with the Non-Disability benefits team
- The Pension team designer will share findings with product manager and OCTO

**Comment by vbellissimo** [comment]
Cancelling this task as it will tie into the Benefits design syncs
