### ISSUE TITLE
Help Improve 'Platform Support' Page

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#71438]
## Description
[What We Can Help With - Platform Support](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2692612097/What+We+Can+Help+With+-+Platform+Support) is an important page but the information is not presented in the best way possible. In fact, it is kind of a mess. 

- Using toggles/dropdowns for all the information on the page forces the user to take extra steps to access their desired info. It also creates a confusing layout for the user. 
- By separating Dos and Don'ts into separate categories, the support team has made the page harder to navigate and much harder for the vital info to reach the user. For instance, no one is going the look for "what you don't do" when it comes to say, Datadog. The best time to inform the user about what you DONT do with Datadog is when the reader is looking at the things you DO do with Datadog. 

By eliminating the toggles, returning the page to a "normal" layout, and combining the Do's and Don'ts in each support category, the Support Team can maximize the effectiveness of this very important page.  

## Tasks

- [x] Summarize recommendations for page
- [x] Review suggestions with Alyssa (who helped author the page)
- [x] Make changes to the page
- [ ] Prepare page for deployment
- [ ] Deploy page

## Acceptance Criteria

- [x] Suggested changes have been reviewed with owner
- [ ] Page has been deployed and is live in the PW

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/71438?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by taylojill** [comment]
Worked with Brian to determine the best format for the page. I'll draft something that can be presented to Alyssa.

**Comment by taylojill** [comment]
Link to recommended page format (in draft space) sent to Alyssa via platform-content channel.

**Comment by alyssagallion** [comment]
Hey y'all! The formatting looks good. Approved on my part.

**Comment by taylojill** [comment]
I'll keep working on it! Thanks @alyssagallion

**Comment by taylojill** [comment]
Submitted a draft review request to Brian. Waiting for feedback.

cc @jknipes

**Comment by taylojill** [comment]
Updated the page based on Brian's suggestions, and sent a link to Alyssa via platform-content channel thread asking for feedback and/or suggestions. Waiting for response.

**Comment by johnny-jesensky-adhoc** [comment]
Look to create a separate ticket on deploying the changes, look to try to knock out on a Friday, then to move into a future sprint.

**Comment by johnny-jesensky-adhoc** [comment]
Changes to this page have been logged, and confirmed with Alyssa - creating a [separate ticket ](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/73766)from this to be picked up next sprint.

FYI @jknipes, @taylojill
