### ISSUE TITLE
[FE] - Add travel review page to unified

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#71432]
## Descritpion
Re-base on main to get the new review page and flow. Then make visual/content changes to match the review page for unified sketch

Also create e2e user stories related to this work:

- Patient who wants to file travel and answers yes to all questions but does not agree to terms on review page
- Patient who wants to file travel, answers yes to all questions but decides to edit from the review page, then yes at review page

  
## Wireframes
- [Sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

## Tasks
- [ ] [FE] rebase with main to get review page and updates
- [ ] [FE] match the review page to the wireframes for unified review page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey / @kellysmith1008 Review page is now in unified. See screenshots:
<img width="169" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHhuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f0ce6616b0541b089e756453168ac64249ee8b4/localhost_3001_health-care_appointment-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%283%29.png" alt="localhost_3001_health-care_appointment-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (3).png" />
<img width="163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58f62362d23393e11d34ffe1084a0c3bd955ec5f/localhost_3001_health-care_appointment-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%284%29.png" alt="localhost_3001_health-care_appointment-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (4).png" />
<img width="130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODVuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7374fe7b07c4c6c1fd6ea60839e8a7c534e5f5a9/localhost_3001_health-care_appointment-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%285%29.png" alt="localhost_3001_health-care_appointment-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (5).png" />

**Comment by loripusey** [comment]
Looks good, reminds me I need to add the travel agreement to the TestRail test cases.

**Comment by benbrasso-agile6** [comment]
Look how fancy you are with the validation error + the add info expanded

LGTM
