### ISSUE TITLE
Modify "VFS" Guidance" in collab cycle feedback template, SR findings and QA findings tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#71441]
## User Story
As a VFS team member, I want a fast response to my question on the Staging Review ticket so that I'm able to address the issue quickly.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
In the "VFS Guidance" section of each and every Staging Review issue ticket, Governance team directs VFS teams to comment on the ticket if they have questions for Governance.
<img width="1131" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2svQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--969a6a253d1fcecf5c3e2d3a364dd63a261c0c41/image.png" alt="image.png" />
However, several comments on tickets have recently been overlooked, meaning the VFS team has to notify us a 2nd time, ultimately delaying the time it takes for Governance to respond, and impacting the VFS teams ability to address the issue quickly. [See example here. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59269)

The purpose of this ticket is to update the VFS guidance in the template so that the VFS team is directed to tag @platform-governance-team-members on their team Slack channel opposed to just commenting on the ticket. We're hopeful that by directing the VFS team to Slack, Governance will have improved visibility of the VFS team question/concern regarding the ticket, allowing us to respond faster and allowing the VFS team to address the issue quicker. 

It would be great if we standardized the content in all feedback in findings tickets so it's consistent across the board.

**Note**: in this ticket, we'll only update the Collab Cycle feedback template and the QA template for SR. Since the VA.gov Experience Standards ticket is currently generated in the DraftingTemplate, and that tool is being updated via the VA.gov Experience Standards initiative, we'll hold off on adding the new guidance to the in-use DraftingTemplate. One of the tasks within this ticket will be to share the new guidance with Shira so the content can be added to the new DraftingTemplate.

## Impacted Artifacts
[Collab Cycle feedback ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md)
[Collab Cycle QA findings ticket for Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-qa-findings-staging.md)

## Tasks
- [x] Draft the proposed content in a Documentation Draft in the Governance team Confluence space. Work on it there before making any commits to the gh issue templates
- [x] Submit for peer review
- [x] Once in agreement, merge changes to Collab Cycle feedback template and Collab Cycle QA findings ticket for SR
- [x] Share content with Shira so she can add to the new DraftingTemplate

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams are guided to reach out to Governance via Slack if they have questions/comments on their Collab Cycle feedback and/or findings

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
[Confluence page with draft text](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2901016712/71441+-+Modify+VFS+guidance+in+feedback+tickets) - will ping Shira early next Tuesday when it's ready for review!

**Comment by erinrwhite** [comment]
@shiragoodman [Draft text for all three ticket types](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2901016712/71441+-+Modify+VFS+guidance+in+feedback+tickets) ready for your review!

**Comment by shiragoodman** [comment]
@erinrwhite I provided some comments in the draft. LMK if you have any questions!

**Comment by erinrwhite** [comment]
@shiragoodman Excellent! I reviewed and incorporated the (really helpful!) changes you recommended. I am going to proceed to make updates on the QA and DI/MPR ticket templates.

**Comment by erinrwhite** [comment]
@shiragoodman pull requests ready for you:

#73762 
#73763

**Comment by shiragoodman** [comment]
@erinrwhite QA PR approved. However, I’m having 2nd thoughts about making changes to the DI/MPR feedback ticket at this time since we’re going to be making changes to the whole template in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73201 - starting this upcoming sprint!

Please delete your PR for the Collab Cycle feedback ticket. I am going to update ticket #73201 to include adding our Slack group.

If you have any questions, please ask!

Also, lmk when the changes to the VFS guidance for the SR template are ready. I will need to incorporate them into our new DraftingTemplate.

**Comment by erinrwhite** [comment]
Ok!

I will notify the team about the changes to the QA ticket, and note that changes to other ticket templates are coming.

And, [VFS guidance for staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2901016712/71441+-+Modify+VFS+guidance+in+feedback+tickets#Next-Steps-for-the-VFS-team) is ready to go in the confluence doc.

**Comment by erinrwhite** [comment]
Shared with team - closing.
