### ISSUE TITLE
IPP: Make intake flow screenreader friendly

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#71459]
As a Veteran who uses a screenreader, I need to be able to navigate through a prototype with my screenreader.

## Tasks

- [x]  Review documentation from Identity Core research, Figma, and VA a11y specialists
- [x]  Create a duplicate prototype with accessible elements
- [x]  Name elements and content
- [x]  Order elements
- [x]  Test with VoiceOver screenreader

## Acceptance Criteria

- [x] Figma intake prototype is screenreader friendly
- [x] Prototype has been reviewed by design team
- [x] Dry run completed with moderator, note taker and observer

**Comment by skirkman16** [comment]
Tested with VoiceOver screen reader. I noticed that the Screenreader reads buttons and links but it did not pick up text so I'm going to try replacing the texts with images and alt text.

**Comment by skirkman16** [comment]
finished prototype and recorded a demo. I am currently adjusting the conversation guide and scheduling a quick dry run to rehearse in advance of Friday
