### ISSUE TITLE
[spike] Solution brainstorming for NOD and SC upstream evidence failures

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71451]
## Background Context
CMP and MMS confirmed they do not intervene for most of the upstream evidence errors. We want to define an approach for handling each of those errors so we don't continue to drop evidence files. 

AFAICT, here are the list of errors we get downstream: https://dsva.slack.com/archives/CKUCFQAHJ/p1697561076051819?thread_ts=1697134097.537579&cid=CKUCFQAHJ; https://github.com/department-of-veterans-affairs/va.gov-team/issues/68756.

And here is [EMMS's API Error listing with descriptions](https://github.com/department-of-veterans-affairs/va.gov-team/files/13967929/EMMS.API.Error.listing.with.descriptions.xlsx)

## Open questions
- Which errors can we handle without asking the Veteran to do anything?
- Which errors can we handle by instructing the Veteran with straight forward error messaging so they can submit their evidence file?
- Which errors do we want to send an email notification for? In these cases, can we instruct the Veteran to upload their evidence through the claim status tool? How can we confirm that evidence uploaded through the tool connects to the supplemental claim of board appeal it was intended for? 
- What are the criteria for submitting SC evidence at a later time?
- What are the criteria for submitting NOD evidence at a later time?
- Can we [write validators](https://dsva.slack.com/archives/C057W3N9K2S/p1701886885543039?thread_ts=1701882265.151279&cid=C057W3N9K2S) to test these before implementation?

## Tasks
- [x] Talk to the enablement team about questions above
- [x] Annie and Eugene will review each error type and make recommendations to discuss with product, FE, and design
- [x] Discuss solution approaches with the team
- [x] Check for existing solutions with other teams in [#centralmail-failures-investigation](https://dsva.slack.com/archives/C06979ADKNY)
- [x] [Notes doc](https://docs.google.com/document/d/1FDWa9v1ooG4L__RODnAYZtcqCt4La1azTyZ6vkEr6KA/edit#heading=h.w7qgw74uvbq9) with spike details

## Definition of Ready 

- [x] We have a list of errors returned from Lighthouse, CMP, and MMS.

## Definition of Done

- [ ] We have a method for fixing each error, aiming to place as little burden on the Veteran as possible
- [ ] We have a method for validating that any code solutions will work before implementing them
- [x] We've identified types of PDFs needed for #73649 
- [x] We've added test cases to #73652 
- [ ] Approach is approved by the enablement team

**Comment by saderagsdale** [comment]
Next steps:

- Determine approach for each known error, using the existing spreadsheet in our sharepoint space
- Find answers to the remediation questions @saderagsdale

**Comment by saderagsdale** [comment]
Pickup after launching NOD form.

**Comment by HeatherWidmont** [comment]
@data-doge is nearly done putting together a doc summarizing everything we've learned. Once that is done they will loop in Eileen, Ruben, Robin, & Sade about UX resolutions.

**Comment by HeatherWidmont** [comment]
Closing this ticket in favor of the two additional spike tickets that @data-doge created
