### ISSUE TITLE
Medallia - QA Debt portal survey

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#71454]
## Issue Description
Work with Vsignals team to QA the Debt Portal survey on all urls
---
## Tasks
- [x] Test debt portal survey

## Acceptance Criteria
- [ ] Verify survey loads on all debt portal URLs 
- [x] Verify survey loads correctly with no styling issues
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
I have noted the following observations:

Survey still loads on  https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction 

I was not able to get the survey to load on any of the urls
- va.gov/manage-va-debt/request-debt-help-form-5655/confirmation
- va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist
- va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist

This could be because the survey is already loaded on the /introduction page.

Based on these observations, I would like to suggest the following recommendations:
1. It would be best not to serve the survey on the pages /additional-income-checklist and /other-expenses-checklist as question 1 and 2 would not make sense.
(Question 1: I was able to easily complete this form online. Question 2: Did you find any section of the form confusing or unclear? Please select all that apply.)

2. It would be better to serve the survey at the end of either /review-and-submit or /confirmation page. If the survey is placed on the /confirmation page, it should be served after 15 or 30 seconds.

**Comment by aubreyarcangel** [comment]
Upon Q/Aing with VSignals and Debt portal team, we've identified a bug that prevents the survey from loading documented in [this ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72105)

**Comment by ATMiddleton** [comment]
The decision was made to have the survey appear as a link available to all users and not an intercept survey.
