### ISSUE TITLE
Medallia - Adjust styling for Debt portal intercept survey

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#71462]
## Issue Description
The styling for the multi-select checkboxes is inconsistent with the rest of the form's styling. <img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEpGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--283d2be019ad59b7d4f8be441e2310ecabb22b26/Screenshot%202023-12-08%20at%2011.07.51%20AM.png" alt="Screenshot 2023-12-08 at 11.07.51 AM.png" />

---
## Tasks
- [x] Override the font-family styling for the checkbox label

## Acceptance Criteria
- [x] The font of the checkbox labels will be consistent with the rest of the form.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `DevOps`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Complete
