### ISSUE TITLE
SC | Increase unit test coverage

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#71499]
## Value Statement
**_As a_** developer
**_I want to_** improve unit test coverage for our appeals form
**_So that_** we can fulfill the new compliance requirement of 80%

## Background Context

Our stakeholders have set a new compliance goal of exceeding 80% unit test coverage in all fields, in all of our apps. The fields that need 80% coverage are: lines (of code), functions, statements and branches. Our Supplemental Claims app has fulfilled this requirement in all fields, but we should add as much test coverage as possible.

Locally, we use the following command to generate a report.

```
yarn test:coverage-app appeals/995
```

After running, it _should_ open a new browser tab in `/vets-website/coverage/index.html`

## Acceptance Criteria

- [ ] Supplemental Claim  unit test coverage at 80% in all fields

## Tasks

- [ ] Review test coverage for  SC
- [ ] Update SC unit tests to increase coverage

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Document any parts of code that can't be covered due to library limitations
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by HeatherWidmont** [comment]
Opened a PR, our team needs to review it. Working on a few more unit tests to get it above 90% across the board.

**Comment by HeatherWidmont** [comment]
2nd PR has been opened & needs to be reviewed (dashboard shows roughly 79% but it should be higher once its merged)

**Comment by Mottie** [comment]
All code updates have been merged. 

Coverage for 995 (Supplemental Claims) is now at:

99.01% Statements 1106/1117
94.77% Branches 816/861
99.26% Functions 269/271
99.17% Lines 1081/1090

<img width="924" alt="Screenshot 2024-02-08 at 2 35 01 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/d7b12dda-2630-4b1e-b566-7d82c22a288c">
