### ISSUE TITLE
[BE] - Encrypt and log phone numbers for BTSSS error responses

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#71509]
## Description
We would like to be able to figure out more information on the circumstances where BTSSS returns an Appointment not found error. Logging the phone number would give us the ability to look up the patient and see their appointments past and present.

Vetext has a method to encrypt phone numbers in logs, so we should be able to follow that. See this slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1662051335776019

Also see this slack thread around the conversation that prompted this ticket: https://dsva.slack.com/archives/C02UP02HHGX/p1701899676812369

## Tasks
- [ ] [BE] Encrypt and log phone number on BTSSS error

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Based on the [slack thread](https://dsva.slack.com/archives/C02UP02HHGX/p1701899737492629?thread_ts=1701899676.812369&cid=C02UP02HHGX), the purpose of the phone number encryption is to get the appointment details of the veteran (using [phone lookup tool](https://r01fd.r01.med.va.gov/smsbatch)) to debug the claim submission failure.

Currently, [phone lookup tool](https://r01fd.r01.med.va.gov/smsbatch) has a decrypt functionality to view the phone number encrypted in VeTEXT.  To minimize the decryption tool implementation, we need to use the secret credentials (key & IV) & algorithm used in VeTEXT/phone look up tool.

As of now, various modules in vets-api use KMS with a secret key stored in an [environment variable](https://github.com/department-of-veterans-affairs/vets-api/blob/471c1daf2b8aec2017679d99b744b134f435bdb5/config/initializers/kms_encrypted.rb#L4-L5) for encrypting a field.  Also, there is a [library](https://github.com/department-of-veterans-affairs/vets-api/blob/471c1daf2b8aec2017679d99b744b134f435bdb5/lib/aes_256_cbc_encryptor.rb#L3-L3) existing for `AES-256-CBC` algorithm but VeTEXT uses `AES-128-CBC`.  To handling the phone number encryption, it is necessary to implement a new library for encrypting with `AES-128-CBC` algorithm & integrate with travel_claims functionality in check-in module.

For using the encryption technique specifically used in vetext/phone look up tool, below list of changes must be made in vets-api,
- Create secret entries in parameter store
    - Note: AWS secrets manager is a good option to store the secret but currently the [aws_ssm_lookup script](https://github.com/department-of-veterans-affairs/devops/blob/0200986bbb88e42fef30f1420313c1c03cb4f06f/ansible/lookup_plugins/aws_ssm_custom.py#L147-L147) only used for reading parameter store & separate investigation work needed to confirm the script works for AWS secrets manager as well (Reference [Doc](https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html))
- Devops Repo changes to modify settings.yml to read secrets from parameter store
- Implement library for encryption with `AES-128-CBC`
- Integrate with check-in/travel claims for encrypting & logging the phone number

Above approach all tightly coupled with the secret and alogorithm used in upstream service and might not be extended for encrypting other fields (if required) in the future as the secret is purely tied with phone number encryption. 

The next steps are to have a quick talk with @Mark Deway to see if it is required to spend on this effort that cannot be extended in future and identify other ways to debug the issue in BTSSS.

**Comment by loripusey** [comment]
@mdewey When will you have time to meet with @kanchanasuriya regarding this ticket?

**Comment by kanchanasuriya** [comment]
@loripusey Discussed with @mdewey in [slack](https://dsva.slack.com/archives/C02UP02HHGX/p1704831042921879?thread_ts=1701899676.812369&cid=C02UP02HHGX).  Mark advised to put a pause on this implementation until we have a new API from BTSSS and revisit it when there is a need.
