### ISSUE TITLE
DR | Increase unit test coverage of shared code

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#71501]
## Value Statement
**_As a_** developer
**_I want to_** improve unit test coverage for our appeals form
**_So that_** we can fulfill the new compliance requirement of 80%

## Background Context

Our stakeholders have set a new compliance goal of exceeding 80% unit test coverage in all fields, in all of our apps. The fields that need 80% coverage are: lines (of code), functions, statements and branches. Our shared code does not yet achieve these goals. 

Locally, we use the following command to generate a report.

```
yarn test:coverage-app appeals/shared
```

After running, it _should_ open a new browser tab in `/vets-website/coverage/index.html`

## Acceptance Criteria

- [ ] DR shared unit test coverage at 80% in all fields

## Tasks
- [ ] Review test coverage for shared code
- [ ] Update shared unit tests to increase coverage

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Document any parts of code that can't be covered due to library limitations
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Done - and once HLR updates are available at 100%, we can remove the feature toggle and it should increase this coverage even more.

<img width="500" alt="code coverage: 94.92% statements, 90.08% branches, 92.98% functions, and 94.91% lines" src="https://github.com/user-attachments/assets/d5eb23a4-1fbd-4f51-851b-1d67ea1a7c70">
