### ISSUE TITLE
NOD | Increase unit test coverage

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#71500]
## Value Statement
**_As a_** developer
**_I want to_** improve unit test coverage for our appeals form
**_So that_** we can fulfill the new compliance requirement of 80%

## Background Context

Our stakeholders have set a new compliance goal of exceeding 80% unit test coverage in all fields, in all of our apps. The fields that need 80% coverage are: lines (of code), functions, statements and branches. Our Notice of Disagreement app has fulfilled this requirement in all fields, but we should add as much test coverage as possible.

Locally, we use the following command to generate a report.

```
yarn test:coverage-app {application-path}
```

`application-path` would be the path to the folder within vets-website, e.g. `appeals/10182`

After running, it _should_ open a new browser tab in `/vets-website/coverage/index.html`

## Acceptance Criteria

- [ ] NOD unit test coverage at 80% in all fields

## Tasks

- [x] Review test coverage for NOD
- [ ] Update NOD unit tests to increase coverage

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Document any parts of code that can't be covered due to library limitations
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by HeatherWidmont** [comment]
FE unit tests are failing for random apps due to a platform issue, we remain blocked. https://dsva.slack.com/archives/C05FCEH2NRG/p1707844087730839
