### ISSUE TITLE
Collaboration Cycle for Accredited Representation Management: Appoint a Representative + Representative Status Widget MVPs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#71535]
### VFS team name

Accredited Representation Management

### Product name

Appoint a Representative MVP + Representative Status Widget MVP (two products being developed simultaneously)

### Feature name

Appoint a Representative + Representative Status Widget

### GitHub label for team

accredited-representation-management-team

### GitHub label for product

appoint-a-representative
representative-status-widget

### Public DSVA Slack channel for VFS team

#benefits-representation-management

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

We began discovery for these products on 8/14/2023.  The decision to treat these as separate products was on 10/25/2023 and we have been designing with this in mind ever since.

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

[Product Outline for Appoint a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/product-outline-appoint-a-representative.md)
[Product Outline for Representative Status Widget](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/product-outline-representative-status-widget.md)

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.
Kickoff Slack Thread with VFS team: [Kickoff thread](link)
</details>

[Slack thread](https://dsva.slack.com/archives/C05L6HSJLHM/p1701993815757199)

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [ ] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
      - The Governance team is responsible for inviting our team members, including our Product Owner, Product Manager, and practice area specialists. We also notify OCTO-DE practice area leads when we finalize meeting scheduling. 
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Design Intent` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

**Required**:
  - [ ] User flow

**Not required, but nice to have**:
  - [ ] Wireframes (if provided, must include mobile wireframes)

**Optional**:
  - [ ] Research plan
  - [ ] Any other artifacts you have so far

##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

##### #### VFS Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
</details>
</details>

### Sitewide CAIA ~Intake Request~ Collaboration
<details>
<summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [x] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [x] Link to the Sitewide CAIA Intake Request ticket below

CAIA collaboration is being managed in this Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809

</details>

### Research Review
<details>
<summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
<summary>Toggle Midpoint Review</summary>

#### Skipping Design Intent
In early days, we had the idea of building one single product. Later, we decided to split into multiple products, but applied feedback from the initial design intent and midpoint review (https://github.com/department-of-veterans-affairs/va.gov-team/issues/65707) to our designs. We're ready to move right into a second Midpoint Review!
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
- [ ] Schedule your Midpoint Review when ready:
- Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
- Select a date and time and click “Confirm”
- Add your name and email
- Click "Add Guests" and enter the VFS meeting attendees email addresses
- Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
- Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review. **Do NOT add artifacts to Comments section**

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] Finalized design prototype or mockup

Authenticated:
- [Canvas View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836)
- [Desktop A Prototype View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/CB1C3151-23CF-40F6-9928-30D7900D7F25/a/CB1C3151-23CF-40F6-9928-30D7900D7F25)
- [Mobile A Prototype View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/F68BAB55-E083-411A-A706-CD4251A38CB7/a/F68BAB55-E083-411A-A706-CD4251A38CB7)
- [Desktop B Prototype View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/72737C69-C0CD-46A6-A41F-0BF3EB00A93B/a/72737C69-C0CD-46A6-A41F-0BF3EB00A93B)
- [Mobile B Prototype View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/EC0A2247-E3A4-415D-9DB7-C3796C104CCC/a/EC0A2247-E3A4-415D-9DB7-C3796C104CCC)

Unauthenticated:
- [Canvas View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/p/34CE53F2-4035-4059-92F5-17A79EA6B344/canvas)
- [Mobile Prototype View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/F73AB584-E113-4572-8AFA-7761671C7752/a/F73AB584-E113-4572-8AFA-7761671C7752)
- [Desktop Prototype View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/D69D63F0-5499-463F-B09E-782973BC590D/a/D69D63F0-5499-463F-B09E-782973BC590D)

- [x] Specify which pages are included in the review: All pages - the Canvas view reveals all states, but included prototypes in case that's easier to navigate. We plan to AB test screens for the authorization steps in our flow.
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2023-12-ARM-appointarep-usertest/research-plan.md) - in progress, should be finalized by 12/12
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2023-12-ARM-appointarep-usertest/conversation-guide.md) - in progress, should be finalized by 12/12
**Content artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
- [CAIA Content Recommendations](https://dvagov-my.sharepoint.com/:w:/g/personal/anthony_procik_va_gov/ESBhwaJYiI9Hs6IMoWyVwGcBMr02J_DyJwzl1Xj6w9P9cg?e=z6kBel) - stored in Sharepoint, must be on VA network to access

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
- [IA Design for Manage Accredited Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/manage-accredited-representative.md)

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05L6HSJLHM/p1702059322313469)
- [x] Meeting date/time: Tuesday, December 19, 2023 at 3:30 p.m. Eastern

##### Platform actions

* Accessibility
* [x] Feedback ticket attached
* [ ] No feedback
* Content
* [x] Feedback ticket attached
* [ ] No feedback
* Design
* [x] Feedback ticket attached
* [ ] No feedback
* IA
* [x] Feedback ticket attached
* [ ] No feedback
* [ ] Update this ticket with the Zoom recording
- Recording link: https://oddball-io.zoom.us/rec/share/Kgmon0w4vRFNUINfSZBJbE-1GQwDV09BazsuFlGHq7rEyi4xbQ_JMdRns74iFj4W.9icau0SY0O8UyayR
- Passcode: e=c9H8JI
##### VFS actions
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
</details>

### 2nd Staging Review (Appoint a Representative MVP)
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [x] **URL(s) to review the product**
  - https://staging.va.gov/get-help-from-accredited-representative/appoint-rep/
- [x] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search)
  - The entry point will be on our landing page (https://staging.va.gov/get-help-from-accredited-representative) and will be managed by CAIA.
- [x] **Test users and scenarios** (when applicable)
  - ARM test users for various scenarios can be viewed here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv
  - Recommended scenarios: 
     - Test user with an organization or individual appointed (lines 4-7) -- select a VSO representative (like George Orr) who is accredited with multiple organizations to view the 21-22 experience.
     - Test user with "no representative" -- select an attorney (like Adam Bond) to view the 21-22a experience.
     - Unauthenticated experience
- [x] **Link to Sitewide CAIA intake ticket**, if applicable.
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809
- [x] **Completed accessibility testing artifact:** see [instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/97463
- [x] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
  - [ ] Regression test plan 
     - This is the first version (MVP) of this Appoint a Representative product, so there is nothing to regress to.
     - If an incident were to occur during our staged roll out, we would enact our [Rollback Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/release-plan-appoint-a-representative-1.0.md#rollback-process) as detailed in the Release Plan.
  - [x] Test plan
     - 21:22 Flow: Unauthenticated, Veteran, Gold Star Wives of America, No authorizations
        - Test cases, 1-21 - https://dsvavsp.testrail.io/index.php?/suites/view/3624&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=26635
        - Test run - https://dsvavsp.testrail.io/index.php?/runs/view/6269&group_by=cases:section_id&group_order=asc
     - 21:22a Flow: Unauthenticated, Veteran, Bobby Baker, Address authorizations
        - Test cases - https://dsvavsp.testrail.io/index.php?/suites/view/3625&group_by=cases:section_id&group_order=asc&display_deleted_cases=0
  - [x] Coverage for References
     - [Coverage for Reference Report: Appoint a Representative - Unauthenticated 21-22 Form Flow](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92157#issuecomment-2529837442)
     - [Coverage for Reference Report: Appoint a Representative - Unauthenticated 21-21a Form Flow](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92157#issuecomment-2529815153)
  - [x] Summary (Defects) reports
     - No defects found in either 21-22 or 21-22a.
  - [x] E2E tests
     - https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-appoint/tests/e2e
  - [x] Code coverage
     - https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/representative-appoint
     - Run this command to see our code coverage for Appoint a Representative `yarn test:coverage-app representative-appoint`
  - [x] Endpoint monitoring playbook 
     - [Appoint a Representative Playbook/Incident Response Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/launch-materials/product-playbook-incident-response-plan.md) 
  - [x] Logging silent failures
     - Our products are monitored in the Datadog [Representation Management Service](https://vagov.ddog-gov.com/apm/services/representation-management/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&start=1730734525022&end=1730738125022&paused=false) and we plan to add additional monitoring when Appoint a Representative is in Production (https://github.com/department-of-veterans-affairs/va.gov-team/issues/92287) as part of our staged rollout.

**Not required, but nice to have artifacts**
- [x] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth.
   - https://dvagov.sharepoint.com/:f:/s/SitewideCAIA/EpKqFTllvlxOkDwz2iFgveAB9PjkKVIrJu_TUAkQPbsU0g?e=L92kpF
   - We also have content discussions in Figma: https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&mode=design&t=qs3g0N5S6p6hSnJo-0
- [x] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec.
   - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/manage-accredited-representative.md
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05L6HSJLHM/p1732300016941149)
- [x] Meeting date/time: **1:30pm ET Thu, Dec 12, 2024**

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Staging review recording](https://oddball-io.zoom.us/rec/share/mzW9yjM7Fx1C2PzvKu0ZwVxOEWV1tW4vj4t7l5nIY7fzTOrkft4mfjAjcvqdHI9i.BAqdq-swOOLHqZvm)
  - Passcode: `h*B0TKN$`

##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review (Appoint a Representative MVP)
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
   - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2114

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by oddball-lindsay** [comment]
@shiragoodman We are choosing to develop the Representative Status Widget MVP first, and then the Appoint a Representative MVP in May so I'm thinking it'd be helpful to break this into two Epics to better reflect these two separate launches.

Is there a way to clone this epic so I can simply edit to be more single-product oriented? or should I edit this one to be Widget focused and then submit a Kickoff for Appoint a Rep that you then convert into this type of epic?

**Comment by shiragoodman** [comment]
Hey @oddball-lindsay  - is your intended next step to go to Staging Review, separately, for both of these features?

**Comment by oddball-lindsay** [comment]
@shiragoodman I'm aiming for two separate Staging Reviews -- one for the Rep Status Widget in April, and a second for Appoint a Rep in June/July.

**Comment by shiragoodman** [comment]
@oddball-lindsay we can just do 2 staging reviews within this ticket, that way it's easy for my team to find their earlier feedback at Midpoint Review. I can update this ticket to include 2 Staging Review sections with the feature name in parentheses.

**Comment by shiragoodman** [comment]
updated!

**Comment by oddball-lindsay** [comment]
@shiragoodman we're getting close to our Appoint a Representative MVP release, but I'm not seeing a section here for Staging Review. Could you please help to add that in above? 🙏

**Comment by shiragoodman** [comment]
@oddball-lindsay that's really odd. Looks like the section for Midpoint Review and other touchpoints has also gone missing. I will bring this back to me team and we can look into it. However, for now I have updated your ticket to include the section for Staging Review. It does looks like you already had an SR for this work back in May... would this be a second SR?

**Comment by oddball-lindsay** [comment]
That's right @shiragoodman we had Staging Review for the Rep Status Widget which is now in production. I also thought it was odd that the other sections went missing! 

Staging Review for Appoint MVP is on the horizon, but not super imminent -- I hope to request one in 2-3 weeks. 🤞

**Comment by allison0034** [comment]
For awareness, something happened and this ticket had some sections deleted. This will be a 2nd staging review.
