### ISSUE TITLE
Update betamocks gem

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71536]
### Description
Update betamocks gem to allow usage with Faraday 2+

### Tasks
- [x] Fix issues related to the release of Faraday 1.10.3 - PRs [here](https://github.com/department-of-veterans-affairs/betamocks/pull/60) and [here](https://github.com/department-of-veterans-affairs/betamocks/pull/61)
  - Note that Riley jumped in to make the actual fix while I was out, and I released it
- [x] Update for use with Faraday 2.7 - PR [here](https://github.com/department-of-veterans-affairs/betamocks/pull/62)
- [x] Update vets-api to include the newly updated gems

### Acceptance Criteria
- [x] gem and vets-api are both updated to allow for the upgrade of Faraday 2.7
