### ISSUE TITLE
Upgrade dependencies once blocked by Faraday <1

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71539]
### Description
Upgrade Restforce, Octokit, Danger, and Sentry-Raven gems. This is an extension of the initial [Faraday Upgrade ticket](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/69303)

### Tasks
- [ ] Update Restforce to 7.0 - PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/14751)
- [ ] Update Octokit/Danger/sentry-raven - PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/14753)

### Acceptance Criteria
- [ ] gems updated and deployed to production
