### ISSUE TITLE
Update breakers gem

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71537]
### Description
Update breakers gem to allow usage with Faraday 2+

### Tasks
- [ ] Update for use with Faraday 2.7
- [ ] Update vets-api to include the newly updated gems

### Acceptance Criteria
- [ ] gem and vets-api are both updated to allow for the upgrade of Faraday 2.7
