### ISSUE TITLE
Update apivore gem

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71542]
### Description
Update `apivore` gem to allow us to bump `json-schema` as far as it can go (<4) and `hashie` to latest (5.0.X)

### Tasks
- [x] Update `json-schema` and `hashie` dependencies
- [x] Fix any broken tests in gem
- [x] Bump version and merge to master
- [x] Bump version in vets-api
- [x] Bump `json-schema` and `hashie` in vets-api and fix tests

### Acceptance Criteria
- [x] `apivore`, `json-schema`, and `hashie` are updated, tested and released to production

**Comment by ericboehs** [comment]
Merged on the 27th. Deployed today.
