### ISSUE TITLE
Update bgs_ext gem

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71540]
### Description
Update `bgs_ext` gem to allow us to bump `savon` to latest (2.14)

### Tasks
- [x] Update `savon` dependency
- [x] Fix any broken tests in gem
- [x] Bump version and merge to master
- [x] Bump version in vets-api
- [x] Bump `savon` in vets-api and fix tests

### Acceptance Criteria
- [ ] `bgs_ext` and `savon` are updated, tested and released to production

**Comment by ryan-mcneil** [comment]
Update: I just need to re-record a cassette to fix the last failing test, but I'm blocked by not being able to establish a connection to one of our instances. Hopefully I'll get this done in the next day

PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/14930)

**Comment by ryan-mcneil** [comment]
I was able to finagle the passing test by allowing vcr to properly format the request it expected, despite not being able to get a correct response, then piece together the cassette it expected
