### ISSUE TITLE
Update connect_vbms gem

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71541]
### Description
Update `connect_vbms` gem to allow us to bump `httpi` to latest (3.0.X)

### Tasks
- [ ] Update `httpi` dependency
- [ ] Fix any broken tests in gem
- [ ] Bump version and merge to master
- [ ] Bump version in vets-api
- [ ] Bump `httpi` in vets-api and fix tests

### Acceptance Criteria
- [ ] `connect_vbms` and `httpi` are updated, tested and released to production

**Comment by ryan-mcneil** [comment]
Update: Waiting on response from teams that own this gem. I will follow up with Grant Lewis after he returns from PTO Jan 3, and work on coordinating dependency bumps

**Comment by JoeTice** [comment]
Duplicate
