### ISSUE TITLE
Schedule Orientation for Steven Cummings, Jennifer Brown, and Kelly Argyros

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#71554]
## Description
A Platform website/content orientation is done for every person joining the Platform program. This introduces them to our team, the Platform website, our support services and how to collaborate with us. Here's are some team documents with more information:

- https://vfs.atlassian.net/wiki/spaces/CIT/pages/2477621264/FY2023+Q2+Platform+website+orientations
- https://vfs.atlassian.net/wiki/spaces/CIT/pages/2479325201/Platform+content+orientation+for+Platform+teams

Office Hours Zoom link: https://us06web.zoom.us/j/84651883090?pwd=YmdhM0dDemRmZWpVRUdHVmxRaG1Tdz09

**Targeted Orientation Date:** Thursday, February 1st, 2024 - at 4:00pm ET

## Tasks

- [x]  Determine the best office hours date to have orientation. Thursday, February 1st, 2024 - at 4:00pm ET
- [x]  Determine the date range to send new team member Slack message. Anytime in Sprint 43.
-Message them on Slack to let them know. See #3 in the pre-meeting scheduling process for message template.
- [x]  Adjust Zoom invite

## Acceptance Criteria

- [x] Orientation has been scheduled for Steven Cummings, Kelly, and Jennifer

**Comment by johnny-jesensky-adhoc** [comment]
Scheduled for Thursday, February 1st, 2024 - from 4:00pm - 4:30pm ET. May be subject to change if availability changes. Moving this to _Done_.
