### ISSUE TITLE
[spike] NOD | Audit backend tests

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#71569]
## Value Statement

**_As a_** developer
**_I want to_** have comprehensive test coverage on backend logic for the NOD form
**_So that_** I can have more confidence that we have appropriately handled error cases and can catch future regressions if the code is changed or updated

---
## Background Context
We are doing a deep dive into how we QA and ensure the integrity of our transactions within the NOD form before we re-release v2 to veterans. There's been a lot of work to gather information about what issues our system may run into as a veteran submits an NOD request, so this work is to make sure our written specs have all the known cases covered.

### Relevant Links / Information related to test cases **[TODO]**
@saderagsdale I might need your help filling this in with all the right links

## Tasks
- [x] Investigate the specs written for the NOD v2 `vets-api` endpoint (timebox to 3 hours)
  - [x] Figure out what [request specs](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/requests/v1/notice_of_disagreements_controller_request_spec.rb), controller specs, service specs, model specs, sidekiq job specs, etc. exist already, and make note of what test cases are already covered
  - ~[ ] Make sure any differences in tests between v1 and v2 endpoints are expected/accounted for~ Coverage is solid 👍 
  - [x] Take a look at code coverage (simplecov) for files relevant to NOD v2 and look for areas of improvement (i.e. lines of code that might not have any tests written with them in mind). Can download it from [GH actions on most recent commit to `master` branch](https://dsva.slack.com/archives/C04CYC4LMU6/p1699457263220439?thread_ts=1699455758.259639&cid=C04CYC4LMU6)
- ~[ ] Add tests/assertions to existing tests that are missing~ Coverage is solid 👍 

## Acceptance Criteria
- [x] We can confirm that claim and evidence submission is covered by backend testing
- [x] Errors are logged

## Definition of Ready 
- [x] We've identified what tests already exist
- [x] We've identified what tests still need to be added for certain cases or lines of code that don't have coverage but need it

## Definition of Done
- [x] Acceptance criteria met

**Comment by saderagsdale** [comment]
Will see how tomorrow goes with testing, and make a call from there.

**Comment by HeatherWidmont** [comment]
Risk - this may not happen this sprint due to the increased scope of the ADG work

**Comment by saderagsdale** [comment]
Derek to shadow.

**Comment by saderagsdale** [comment]
@anniebtran Morning - Do you have the capacity to prioritize picking this ticket up today? Hoping to set expectations with Zach and team ASAP if we see something that extends the scope of testing.

**Comment by HeatherWidmont** [comment]
@saderagsdale Annie said she does have capacity to pick this up today

**Comment by anniebtran** [comment]
@saderagsdale Just stepped through the code with Derek and the only tests that we saw that were lacking were mostly around logging and a couple of nitpicky metadata related details, but nothing glaring — major pieces of functionality seem to be covered by our specs. I'll double check the simplecov generated code coverage report but I think we're pretty good to go as far as test coverage on the backend for the various steps to submit an NOD form + evidence 👍

**Comment by saderagsdale** [comment]
@anniebtran What was missing from logging and metadata? Mostly asking to ensure we're covered if any submissions fail due to metadata validation issues. 

Slight segway: Are we setup to start calling the status endpoint from Lighthouse for the new NOD submission endpoint, so we can see any upstream failures? If not we can discuss how to monitor this tomorrow.

**Comment by anniebtran** [comment]
@saderagsdale 

To clarify, we're just missing a couple of lines to test that the metadata is what is expected and we could add more granular unit testing as far as logging, but I just (finally) found the file where we are more thoroughly testing logs in a more integrated way (i.e. as a part of a process vs. individually/as a small unit), so actually the test coverage for logging feels pretty robust 🙌 

> Mostly asking to ensure we're covered if any submissions fail due to metadata validation issues.

Good call — looking at the code, it appears we only use this metadata for our own records of the submission and there's validation (as far as I can tell) that is happening with that field.

> Are we setup to start calling the status endpoint from Lighthouse for the new NOD submission endpoint, so we can see any upstream failures? If not we can discuss how to monitor this tomorrow.

Is the status endpoint you're referring to related to the polling stream of work to catch upstream failures? If so, I don't think we have anything related to that set up yet.

**Comment by HeatherWidmont** [comment]
@saderagsdale what are our next steps here? Is this something you'd like to discuss in the parking lot?

**Comment by anniebtran** [comment]
Chatted w/ Eugene, Sade, and Derek in the parking lot — the overall findings were good, the major pieces of the code needed to submit an NOD in V2 were covered by both unit and integration tests. But we wanted to have some numbers around test coverage handy in case anyone asked, so I've pulled some from the simplecov generated report.

### Notice of Disagreements V1 controller (the API endpoint that vets-website hits when it submits the form)
`76.47%` for the **WHOLE** file
- Sounds low-ish, but we only really care about the `create` action and 
- it is only missing coverage for one line that has not changed in functionality from the V0 controller, which does have test coverage, so we're probably okay there.

<img width="611" alt="Screenshot 2024-01-09 at 3 31 20 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/13918424-8f64-4aff-830a-18311159e0ad">
<img width="1287" alt="Screenshot 2024-01-09 at 3 31 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/8e804695-d2e0-4c03-bd02-fb303a2299aa">

### Decision Review V1 Service (the interactions between our API and Lighthouse)
`96.45%` for the **WHOLE** file
- Very good coverage of the code we use for NOD
<img width="540" alt="Screenshot 2024-01-09 at 3 56 46 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/3d53d22f-2678-4453-8fc0-2fb2b9f5eff6">
<img width="1287" alt="Screenshot 2024-01-09 at 3 33 38 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/a11b3179-f807-4b8d-ad39-14bdf432ea8e">
<img width="1559" alt="Screenshot 2024-01-09 at 3 34 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/f45d4be0-a9ba-45b1-a261-02e9ea8102b2">
<img width="1560" alt="Screenshot 2024-01-09 at 3 34 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/22b6e843-cbc9-45f7-a35f-729273666771">
<img width="1563" alt="Screenshot 2024-01-09 at 3 35 06 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/dea7be92-3f5a-46c5-a994-607f0c4e0072">

### AppealSubmission model (defines the `#submit_nod` method that performs the form and evidence submission to Lighthouse)
`100%` coverage for the whole file 😄 
<img width="472" alt="Screenshot 2024-01-09 at 4 01 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/dbd8431d-1921-4042-93b6-0a8f2f58e2d0">

### SubmitUpload job (gets queued up in `AppealSubmission.submit_nod` and performs the evidence submission steps)
`86.27%` for the **WHOLE** file
- Pretty good coverage, any missing coverage is generally related to SC and not NOD
<img width="514" alt="Screenshot 2024-01-09 at 4 04 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/9930c5d7-e3ea-4db8-a550-1edb25aa08b1">
<img width="1554" alt="Screenshot 2024-01-09 at 3 37 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/337f4a2f-b86b-49f0-a949-9138342213a1">
<img width="1554" alt="Screenshot 2024-01-09 at 3 38 09 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/084a9fa6-e52f-4e01-928f-d09e9cb54b21">
<img width="1556" alt="Screenshot 2024-01-09 at 3 38 19 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/3da578f1-72ee-4659-ad9a-a8c4b24b40e3">

**Comment by HeatherWidmont** [comment]
@anniebtran to update the tasks of this ticket & check off all completed boxes

**Comment by saderagsdale** [comment]
@anniebtran There's one more thing. Since we're submitting to the Benefits Intake API I think we'd benefit from a review of their [documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current) to ensure we're setup for success in terms of schema validation. Additionally, when we do E2E testing, we'll want to use PDFs that test their requirements. What do you think?

**Comment by anniebtran** [comment]
Updated and check things off of the task list ✅ 

Following up on a question from @saderagsdale about making sure our logs are distinct between the different forms and it looks like NOD's logging is indeed separate and the only place where it was initially bundled together was when the veteran would add upload files to their form (pre-submission) and @data-doge took care of separating those NOD vs SC logs out [here](https://github.com/department-of-veterans-affairs/vets-api/pull/14582). So I think we're good on logging.

> Since we're submitting to the Benefits Intake API I think we'd benefit from a review of their [documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current) to ensure we're setup for success in terms of schema validation. Additionally, when we do E2E testing, we'll want to use PDFs that test their requirements. What do you think?

@saderagsdale Hmm I'm not entirely sure if I have the system architecture understood correctly, but we don't directly submit to the Benefits Intake API — from what I can tell, we're going through an extra Lighthouse "layer" of API via their [Decision Reviews API](https://developer.va.gov/explore/api/decision-reviews/docs?version=current) and from there Lighthouse calls the Benefits Intake API. We have limitations on what we're allowed to send to their Decision Reviews API (defined by a separate schema for that API) and if the data we send to the DR API is not compatible with their Benefits Intake API, then Lighthouse would probably need to update the requirements around what we're allowed to send to the DR API. So I don't believe reviewing the Benefits Intake API would be very fruitful, unless we're doing a deep dive audit to fix something upstream. Does that all make sense?

**Comment by saderagsdale** [comment]
@anniebtran @data-doge Ultimately, we do need to take into account the requirements for the Benefits Intake API, at least for the purpose of test criteria in the near term. API changes by LH tend to be planned a quarter in advance.

**Comment by anniebtran** [comment]
@saderagsdale Yeah, definitely makes sense for our broader testing goals and building E2E test cases, which feels like it's beyond the scope that this ticket covers. Seems like the E2E related work covered by the ticket we discussed in refinement though, so should we call this one good?
