### ISSUE TITLE
Update Style Guide: Toggles/Dropdown Widgets

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#71566]
Currently the Style Guide doesn't have any guidance on using Toggles/dropdown menu widgets. We should add guidance on that subject. 

Likely, the best place for it would be on the [Formatting and Organization](https://vfs.atlassian.net/wiki/spaces/AP/pages/622362663/Formatting+and+organization) page of the Style Guide, between the Notes, Cautions, and Warnings section and the Tables section. 

## Tasks

- [x] Determine as a team what our policy will be on Toggles/Dropdown widgets
- [x] Draft the wording
- [x] Get team approval on the wording
- [x] Place the new wording in the Style Guide
- [x] Communicate updates to the style guide through some means, (either an upcoming TOTS, or a Slack channel)

## Acceptance Criteria

- [x] Team has agreed on guidance on toggles/dropdown usage
- [x] Style guide has been updated with guidance on toggles/dropdowns

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/71566?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
Working on this ticket, led to an update to the [FAQ guidance](https://vfs.atlassian.net/wiki/spaces/AP/pages/2563244774/The+Do+s+and+Don+ts+of+Writing+FAQs). I created a [new ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/72683) for this and moved it to Review QA.

**Comment by BSmolensky** [comment]
Style Guide has been updated. New guidance can be found here: https://vfs.atlassian.net/wiki/spaces/AP/pages/622362663/Formatting+and+organization#Accordions
Team will announce new guidance via Tip of the Sprint on Wed Jan 3, 2024.

**Comment by johnny-jesensky-adhoc** [comment]
Confirming this has been added to our style guide, marking this as _Done_.
