### ISSUE TITLE
Document Internal GTM How-To

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#7156]
## User Story or Problem Statement
As a VSP Analytics & Insights team member, I need understand how the Platform internal GTM process works and how to implement GTM so I can support VFS teams in Google Analytics user tracking.

## Goal
Document necessary internal team Google Tag Manager processes and standards.

## Tasks
- [x] Nedie interviews with VSP Service Design
- [x] Joanne documents process pain points
- [x] List out GTM documentation
- [x] Groom current documentation - which documents need to be updated, added, or folders changed
- [x] Update current documentation
- [x] Add necessary new documentation
- [x] Edit GTM issue template

## Acceptance Criteria
- [ ] VSP Analytics team members can reassign Google Tag Manager support given staff changes
- [ ] VSP Analytics team members can understand the GTM process and their responsibilities
- [ ] VSP Analytics team members can understand VA GTM custom events and naming conditions so they can consistently implement GTM after staff changes
- [ ] VSP Analytics has GTM process pain points documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@joanneesteban Please see a list of documentation for Google Tag Manager:

#### Existing Documentation
[VFS-Facing Google Tag Event Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md#event-tracking) 
[VFS-Facing Overview of Form Events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/data-dictionary-form-events.md)

#### New work-in-progress documentation
[VSP Analytics-Insights Internal Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/google-tag-manager-process.md) - This needs more information on the Navigation setup and other use cases for VFS products.

**Comment by nedierecel** [comment]
@joanneesteban The Internal Process document has been updated. 

#### New Documentation
[Google Tag Manager Containers](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/google-tag-manager-containers.md) has also been created

**Comment by joanneesteban** [comment]
@bsmartin-ep @jonwehausen to take a look at the documentation links.

**Comment by joanneesteban** [comment]
@jonwehausen to add the estimation doc.

**Comment by jonwehausen** [comment]
[Story Pointing Estimation Documentation](https://docs.google.com/document/d/17mlWcVjEVox1szxhRRYWOS1AVFVdSKN0I0SvMU5SDXA/edit#)

**Comment by nedierecel** [comment]
New section of documentation added for [internal VFS implementation document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/google-tag-manager-process.md#tldr---general-acceptance-criteria-for-vfs-implementation)

**Comment by joanneesteban** [comment]
@jonwehausen & @bsmartin-ep - to QA documentation.

**Comment by joanneesteban** [comment]
Issue template:
- Add exemplary examples
- Add Brian, remove Nedie from assignment

Need to figure out what to do with ForeSee vs. GTM requests.

**Comment by joanneesteban** [comment]
These docs are awesome, thanks for getting them done so quickly, @nedierecel !

### Other Updates
- Added another tab to the [Google Analytics Documentation](https://docs.google.com/spreadsheets/d/1p43L1QrufgjuAZ6xBcQlBmJrRWOAhVP7tpIPmukz3PM/edit#gid=0) sheet with the GTM documentation

## Additional Feedback/Other Steps
- @joanneesteban - determine documentation location; align with collab cycle
   - We need to update the issue template for assignments (adding @bsmartin-ep and removing @nedierecel ). Also add that teams should be filling it out during the. We also need to add links to examples of tickets filled out that were most helpful to you all. (I don't see the setting to update issue templates anymore, I need to follow up with Admins on this).
- Within the [Build section of the collaboration cycle](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1585175387763/ebc0ae5ed4997ab30dd932409b12269a34bd5bce), where would you say each part of the GTM implementation is? Can we get more specific for better clarification on when teams are supposed to reach out to us?
- To make overall tracking easier, I think we need separate tickets for bugs. Thoughts on this? 
- May be useful to hand over documentation to Peter/Product Support to see if this type of documentation would suffice for getting help with QA (fysa @andreahewitt-odd ). We might also want to hand off to a Front End engineer or Content to see if documentation makes sense for what we eventually collab with Front Ends on VFS. 
- Estimation template is a great add. How can we add this to Github? 
- Docs will need updates for consistency on who the audiences are. We also need to align this with the other Analytics documentation, so this can be pushed.
- General How to Prioritize & higher level Best Practices (the QA, etc. that Brian discussed) should be added as well
- Are there additional custom dimensions and tags that we should add?

**Comment by nedierecel** [comment]
@joanneesteban Thanks for reviewing. A few follow-ups:

1. Broken GTM Link - Thanks for surfacing. Because GA and GTM are purchased as part of the same license, I renamed [the link to cover both resources.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/ga360-overview.md)

I'll insert internal processes on provisioning access and user groups to this link.

2. Collab Cycle - From our 1-on-1, GTM is throughout build, with preference that VFS teams start engaging very early in the Build Phase.

**Comment by joanneesteban** [comment]
@nedierecel 

Thank you!

Also, do you know if this [DAP doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/warning-about-analyticsusagov-aka-dap.md) is up-to-date?

**Comment by nedierecel** [comment]
@joanneesteban My predecessor wrote this, but I think the ideas listed within are still valid. Here are my hypotheses on what DAP is still different from our VA.gov property:

a) DAP will be higher b/c we are missing subdomains - Our VA.gov property still has some subdomains that were not brought into our purview. This is listed in [our Teams Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/ga360-overview.md#vagov-content-not-measured-within-vagov-production-property) with context on which subdomains were identified as not being part of our property during WBC. 

_Approach_: Perhaps worth a discussion/task in backlog to see if these subdomains need to be folded into our VA.gov property

b) DAP will be higher b/c it does not account for authentication correctly - When a veteran authenticates on VA.gov and gets sent to DS Logon or ID.me, the veteran is sent to those domains, respectively. 

We have it configured correctly so that this maintains the session in Google Analytics [(technical documentation listed here)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/ga360-overview.md#configuration-of-cross-domain-tracking).

I don't think DAP has that extra configuration, so it causes a new session to start once the veteran comes back to VA.gov after authenticating. Since we've had our GA360 property, I've encouraged teams to use the Platform Google Analytics rather than DAP.

**Comment by joanneesteban** [comment]
Priorities:
List out:
1. Anything that needs updating
2. Anything that's missing

VSP can implement & QA Tag Manager using the provided documentation.

**Comment by jonwehausen** [comment]
@joanneesteban 

Made the following additions today [within here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/google-tag-manager-process.md): 
- Added a section for what GTM should NOT be used for
- Added a section around QA testing: procedures, templates, edge cases, etc
- Added a template for DL requirements

Things that we should add next: 
- Which things we currently have globalized tracking for (accordions, jumplinks, etc)
- How we are working towards standardizing our naming convention according to the design system

**Comment by joanneesteban** [comment]
## Other Item

- [ ] Update issue template
    - [ ] Format with HTML comments
    - [ ] Adding examples of previously 'well-done' tickets

**Comment by bsmartin-ep** [comment]
@joanneesteban -

I did some tests with the HTML comments idea and I don't think it's a good idea.  You lose the ability to format the content and if you accidentally remove a comment declaration, it can blank out the entire ticket.

One other option is to put the _What this form is for_ section behind an accordion....

Collapsed | Expanded
-- | --
![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/d8afb7c2-9ddc-4cdd-a760-23440a7096f5) | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/50a86dc6-5445-4631-9aec-8a05bc11a991)

**Comment by bsmartin-ep** [comment]
@joanneesteban -

Here is the markup for both versions of the template instructions.  Let me know if you want me to update the template or if you want to combine this with the .md renaming.

### Accordion version

```
<details>
<summary>What this form is for</summary>    
<br>
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA
</details>
```

### HTML Comment version

```
<!---

What this form is for
---------------------------

Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

Please see the following information for implementation timeline:

New Teams: Implementation will usually be completed in 4 sprints:
 
 - Sprint 1: Discovery/Orientation
 - Sprint 2: FE Implementation
 - Sprint 3: Tagging Implementation
 - Sprint 4: QA
 
 All other teams: Implementation will usually be completed in 2 sprints
 
 - Sprint 1: Discovery and FE Implementation
 - Sprint 2: Tagging Implementation and QA

-->
```

**Comment by joanneesteban** [comment]
@bsmartin-ep Go ahead and implement the accordion version in the template. Let's hold off on the template renaming for now - we might end up renaming each analytics issue template per [9065](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/9065).

Do you have examples of previously filled analytics requests to also add to the issue template?

**Comment by bsmartin-ep** [comment]
@joanneesteban -

Template is updated.

As for a recommended ticket, I think #7199 is a good example.  It's informative and very well formatted.

**Comment by joanneesteban** [comment]
The GTM documentation looks good to me! I updated the [issue template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-implementation-and-qa-request-template.md) with Brian's example and and a link to the GTM documentation on the Platform folder.

Good to close if you're ready, @jonwehausen @bsmartin-ep
