### ISSUE TITLE
ARM Nav & Search - User Test - Share-out & Filing

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#71565]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
1. Navigation
2. Search

---

## Tasks
- [x] Share-out report with larger team
- [x] Convert report to GitHub and Enjoy HQ

---
## Acceptance Criteria
- [x] All documents complete, shared, and uploaded to systems

**Comment by jfinnerty13** [comment]
That's a wrap
Link to the deck/ https://dvagov.sharepoint.com/:b:/s/vaabdvro/EWAOMH2Q5F1PgQTIjL_4rlMBovJsEKKJnLeHtRZO9lfTdQ?e=YxojQU

Link to the recording/ https://dvagov.sharepoint.com/:v:/s/vaabdvro/EXLHnDARAOtOiI2w_zX6c_EBiQyxlpBmCsnOQcPRYDuAvw?e=yWAJis

Link to GitHub research folder/ https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2023-11-ARM-findarep-nav-usertest

And EnjoyHQ/ https://app.enjoyhq.com/sh/pj/e1d9be64-dd77-47b2-a563-b9e8f82c7f7a
