### ISSUE TITLE
Document GA Guides

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#7157]
## User Story or Problem Statement
As a VSP Analytics & Insights team member, I need understand how to communicate using GA so I can support VFS teams in understanding their data on Google Analytics.

## Goal
Document necessary Google Analytics processes and definitions.

## Tasks
- [x] List out GA documentation
- [x] Groom current documentation - which documents need to be updated, added, or folders changed
- [x] Update historical knowledge
- [ ] Stretch: Update current documentation
- [ ] Stretch: Add necessary new documentation

## Acceptance Criteria
- [ ] VSP Analytics team members understand processes and standards for provisioning GA access.
- [ ] VSP Analytics team members can provide GA support (including historical background and how to read custom dimensions) to VFS teams without a single point of failure
- [ ] VFS teams can find necessary GA support links
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
VFS customer questions [here](https://dsva.slack.com/archives/CBU0KDSB1/p1585656255191900) would be good examples of what to include on a guide. Definitions + where to find within GA.

For prioritization, GTM should be first, and I can help with outlining this issue.

**Comment by joanneesteban** [comment]
Started [template for GA documentation.](https://docs.google.com/spreadsheets/d/1p43L1QrufgjuAZ6xBcQlBmJrRWOAhVP7tpIPmukz3PM/edit#gid=0). 

Editing "Edit" and "Add necessary new documentation" as Stretch Goals. A couple of nuances should be edited for historical knowledge, but we can continue past April 10 if we need to.

**Comment by nedierecel** [comment]
@joanneesteban I added links to the Google Sheet for your review.

**Comment by joanneesteban** [comment]
User story for this:

As a VFS team member, I need to understand the Google Analytics metrics for my product on dashboards and within GA so that I can properly diagnose success or failure for my product.

Pain point: back and forth GA dashboarding clarifications and questions above and also [here](https://dsva.slack.com/archives/C909ZG2BB/p1585776377158600?thread_ts=1585773376.156200&cid=C909ZG2BB).

**Comment by joanneesteban** [comment]
@nedierecel is there a way to see which URLs or Products are WBC?

**Comment by nedierecel** [comment]
@joanneesteban Sure - all of the Modernized products should be reflected by using the Events report and looking for a pattern of `-submission-successful`. [These can be found within this report.](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20200101&_u.date01=20200403&_.useg=builtin1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=successful)

This is also touched on in our [Analytics-Insights documentation in our Platform folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/data-dictionary-form-events.md)

**Comment by nedierecel** [comment]
@joanneesteban I removed my name from Google Admin on VSP Platform Readme.

**Comment by nedierecel** [comment]
@joanneesteban I started this [WIP Data Dictionary and will add more before end-of-day Friday.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/wip-data-dictionary.md)

Some of this might also be redundant to content that exists in the Platform folder for [Pageviews and Events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/build-process-measuring-pageviews-and-events.md) and within [Form Events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/data-dictionary-form-events.md).

I'll continue drafting so that our team, Content & IA, and/or Service Design can refashion into more meaningful sections and for the right audiences.

**Comment by nedierecel** [comment]
@joanneesteban A paragraph on permissions/user groups has been added to the [GA360 Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/ga360-overview.md#access-to-google-analytics). 

@bsmartin-ep @jonwehausen There is also a section I added here on [cross-domain tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/ga360-overview.md#configuration-of-cross-domain-tracking). The authentication providers for ID.me and DSLogon are reflected in this list. I occasionally check the hostname report to audit if there are new domains appearing that either (a) need to be added to the referral exclusion list or (b) is a non-production hostname that should be filtered.

**Comment by joanneesteban** [comment]
@nedierecel Thank you! Can you share a screenshot of where the button is for adding a new user group? Also, is this just for adding a new user group? How can we edit a user group?

Also, I think it's fine if some of the definitions are reduntant. I think the intent behind looking at documentation after analytics has been implemented vs. while implementation is taking place might cause folks to look at separate documents.

**Comment by nedierecel** [comment]
@joanneesteban I'm having an operator-error issue adding the screenshot to markdown but wanted to include here for reference:

**Adding New Groups**
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/34e12720-d703-4a29-ae7e-8344a3a99ac8)

**Editing Groups**
Step 1 - Search for the group's name. These have a different icon next to the name, as shown here:
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/c6aaa7f1-3fef-4373-aac0-744c461b787f)

Step 2 - Click on the kebab icon and then "View Organization Details"
[image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/2c33e51b-b651-4040-839b-b2857bc6bb88)

Step 3 - When new screen is opened, click on members to see who belongs to that group/
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/0d9eb1ed-a908-4ddd-9513-0961087a1978)

**Comment by joanneesteban** [comment]
Priority for QA on this issue is the data dictionary. Users have multiple follow up questions after implementation and creating dashboards - we should try to maximize documenting definitions and processes for which we get general follow up questions.

Some of the questions that VFS teams generally have or we have seen:
- How can I see where users are interacting within my product/page?/How can I see how veterans are using my product?
- How can I see how users are moving through my site?
- Where do I see how people are entering my site?
- What's the difference between events and clicks/sessions/pageviews?
- What does scroll through mean for my page?
- What do failures mean on Google Analytics? What does this mean for my users? Does it include all failures? Is this the same as errors?
- What links are users clicking on my page?
- How many people are visiting my page? How long are they staying or going through my product's form?
- How do I see the % of traffic for my page by device?

Additional definitions
- Total transactions - is this global?
- Total interactions - is this global?
- Errors, Failures

We don't need to re-invent the wheel, but we also need to ensure that we can provide VFS teams with resources to self-serve and read metrics with our team serving as less of a blocker.
---

In order for users to access GA dashboards, we should also add this to documentation:

![image](https://user-images.githubusercontent.com/48964695/79289687-f7c0f180-7e97-11ea-8937-3c39346c1929.png)

---

A task for @joanneesteban is to organize the documentation within GH, and connect appropriate documentation to the Documentation Homepage and/or Collaboration Cycle.

**Comment by joanneesteban** [comment]
#### User Groups - Provisioning Access to GA

FYI - adding or editing users in user group only works if you own the user group. This may not be best way to provision access.

**Comment by joanneesteban** [comment]
@jonwehausen @bsmartin-ep 

GTM documentation QA in Sprint 24.

GA documentation QA in Sprint 25.

**Comment by joanneesteban** [comment]
Brian's documentation for 1mil row limit https://github.com/department-of-veterans-affairs/va.gov-team/issues/8329

**Comment by bsmartin-ep** [comment]
@joanneesteban  -

How would you describe the overall relationship between these two documentation repos?

### Repository for team information, planning docs, meeting notes, etc.
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics

### An onboarding guide to VSP Analytics and Insights
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics

**Comment by joanneesteban** [comment]
Another note for us:

We also need to separate out the documentation for requesting access to GA. The current format is confusing for folks to find.

**Comment by joanneesteban** [comment]
Not huge changes, but some of the GA documentation will need a couple of content tweaks before we're ready to share. [This is a Sheet with those notes.](https://docs.google.com/spreadsheets/d/1KIUQUYh_770ODWn4k-gd-yIArMzBlI3orbs-G7ilvRU/edit#gid=0) Feel free to ignore all of the non-GA/GTM stuff.

@bsmartin-ep @jonwehausen

**Comment by jonwehausen** [comment]
Agreed @joanneesteban - Continuing to chip away trying to get a shareable point by sprints close.

**Comment by joanneesteban** [comment]
@jonwehausen @bsmartin-ep 

A couple formatting edits before closing this out:
(this is in the [Google Sheet](https://docs.google.com/spreadsheets/d/1KIUQUYh_770ODWn4k-gd-yIArMzBlI3orbs-G7ilvRU/edit#gid=0))

- [ ] Google Analytics readme: Add "How to request Google Analytics access" link
- [ ] Google Analytics readme: Fix "Understanding Goals Conversions" link; this should be the "measuring success in analytics" doc. 
- [ ] Google Analytics readme: show the difference between GA and GTM references. Example: separate in the table of contents
- [ ] Navigating Google Analytics: Add link to "google-analytics-request-guide" on the text "please reach out to us for further assistance." 
- [ ] Measuring Success in Analytics: Should be renamed to add "Goals" in the title. 
- [ ] Measuring Success in Analytics: Formatting of "Implementing Goals" section should be fixed.
- [ ] Measuring Success in Analytics: If renaming doc, fix link in readme.
- [ ] GA360 Platform: Rename to `ga360-platform-access-levels`. Then fix readme link.
- [ ] Data Dictionary Form Events: Is this going to be renamed?

**Comment by jonwehausen** [comment]
Thanks Joanne! Appreciate you listing out. We'll get after these and get back with you.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

PR ready for your review.

https://github.com/department-of-veterans-affairs/va.gov-team/pull/9675

**Comment by jonwehausen** [comment]
@bsmartin-ep Thank you sir! Looks great, thank you for fixing the broken links as well. PR has been approved and merged.

**Comment by joanneesteban** [comment]
GA Guides were completed - will continue to iterate based off of new customer feedback.
