### ISSUE TITLE
Collaboration Cycle for [Cartographers, MHV on VA.gov, MHV Secondary Navigation ]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#71571]
### VFS team name

Cartographers

### Product name

MHV on VA.gov

### Feature name

MHV Secondary Nav

### GitHub label for team

Cartographers

### GitHub label for product

MHV-secondary-nav

### Public DSVA Slack channel for VFS team

mhv-on-vagov-cartography-team

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

ASAP

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

Secondary Nav [product outline](https://github.dev/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/README.md)
Related products:
- MHV-on-VAgov Landing page [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page)

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C0581MN69TJ/p1702057493830459)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
      - The Governance team is responsible for inviting our team members, including our Product Owner, Product Manager, and practice area specialists. We also notify OCTO-DE practice area leads when we finalize meeting scheduling. 
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Design Intent` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] User flow (required) [Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702062118264/b71c6832a1635ce6538abee9ed2fb706f810fe02?sender=ua13e567cb5c4221acaa14949)
- [ ] Whiteboard sketch or other lo-fi prototypes or wireframes
- [ ] Research plan
- [ ] Any other artifacts you have so far
  - [Research readout](https://dsva.slack.com/files/U03M5PVRL6Q/F068RTGSVAT/mhv_on_va.gov_secondary_nav._research_readout.pdf)re using the Benefit Hub secondary nav component (mobile) for this application
  - [Documentation of issues with existing secondary nav patterns on VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/research-and-analytics/health-integrated-navigation.md)
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C0581MN69TJ/p1702058408148689)
- [x] Meeting date/time: **Tuesday, December 12, 2023 at 3:30PM ET**
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Design intent video recording](https://oddball-io.zoom.us/rec/share/SJNIpRBArjHicMmDIh5oHseQARv9JKTu1DpnoYDD6Ne0MH21rDdxsXeQcUAiP6py.mC-0GmWFwENKdIGK)
  - Passcode: `e8a.8bEW`
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [ ] [Finalized design prototype or mockup](https://www.sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271/v/llY2Wd/p/7E0F45F7-24A5-4AEF-87F4-AD3941A2A7ED/canvas?posX=-846.6306311840237&posY=-720.6755436593202&zoom=2.309406042098999)
- [ ] Specify which pages are included in the review: Midpoint review (Design A and B) 
- [ ] [Research plan](https://dvagov.sharepoint.com/:w:/r/sites/HealthApartment/Shared%20Documents/MHV%20on%20VA.gov%20Landing%20Page/Health%20Portal%20Nav%20Research/Research%20plan.docx?d=w694d61cd69a74d399ef2fd161ac23a5a&csf=1&web=1)
- [ ] [Conversation guide](https://dvagov.sharepoint.com/:w:/s/HealthApartment/EVLOzSf2IilDl0gRPomXK4oBCTBq_NvxuQCtNhjmtBknfg?e=cUeTLP)
 
**Content artifacts**
  
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C0581MN69TJ/p1703200494994059)
- [x] Meeting date/time: Monday, January 8, 2024 at 3:30pm Eastern

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [ ] Feedback ticket attached
  * [x] No feedback
* Design
  * [ ] Feedback ticket attached
  * [x] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/xUOxMT-NvYmnMClEydeBb-_JTtmO78SEHnu8WWURcY_DGHp3fIkHAkPwuYsbyv29.KsOq0EBO-gBDoqK9)
  - Passcode: `x7rjT$6w`

##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Staging Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/) [**broken link**], add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 

[[Product artifacts](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-mhv-secondary-nav.md)]

- [x] Staging URL
- [x] Specify which pages are included in the review        
- [x] Staging test user information         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
  -  N/A
  
**IA artifacts**
- [x] [Integration sitemap + high level user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713450017254/6daf1f320cba1054fdfd840e4a7c881dda87120c?sender=uf94a77a19aaf687331c09367)
- [x] [Secondary navigation URLs & linked page breadcrumbs](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1716908835582/c67063cafb46cb565bbae66b16826333fe946acf?sender=uf94a77a19aaf687331c09367), with notes! 

**QA artifacts**

[[integration test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/qa/mhv-on-va-gov-integration-test-cases.pdf)]

[[secondary nav test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/qa/mhv-on-va-gov-integration-test-cases.pdf)]

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan) - Testrail [link](https://dsvavsp.testrail.io/index.php?/runs/view/5543&group_by=cases:title&group_order=asc) 
- [x] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan) - Testrail [link](https://dsvavsp.testrail.io/index.php?/plans/view/5541)
- [x] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) - Testrail [link](https://dsvavsp.testrail.io/index.php?/reports/view/810)
- [x] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports) - Testrail [link](https://dsvavsp.testrail.io/index.php?/reports/view/812)
- [x] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code) [link](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/mhv-landing-page/tests/e2e)
- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code) - [link](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/#:%7E:text=Mhv-landing-page:~:text=40.00%25-,Mhv%2Dlanding%2Dpage,-88.42%25) (CTRL/CMD+F, "Mhv-landing-page")
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). Ticket #83926 
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C0581MN69TJ/p1716234817125809)
- [x] Meeting date/time: May 30, 2024 at 3:30 p.m. ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Staging review meeting recording](https://oddball-io.zoom.us/rec/share/OIIDYGxmvsG7n-9bMhuF2eaZOyUQ_W3pBUnqciKzVl2vlrjC7QJ6AfGyfLroLg0A.eQSfeVEoMLAz8jQZ)
  - Passcode: `?$zF5e=7`  

##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below: [issue 1687](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1687) closed

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by brea11y** [comment]
Accessibility testing artifact has been submitted. Ticket #83926

**Comment by wesrowe** [comment]
launched and all tickets accounted for! closing
