### ISSUE TITLE
Research: Vets.gov Write Access Improvements

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#71596]
## Description 
There have been several discussions noting that we should:

- Revamp who gets access to vets.gov write access
- Identify what repos should be included in vets.gov write access ([as outlined here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54491))
- Identify any other improvements to the process we need (it seems Bill Chapman is the person to discuss this with)

We will start with research to identify the best routes for accomplishing the above. A new ticket will be created for the execution after research is complete. 
---

## Definition of Done
All tasks below should be completed.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Speak with Shira Goodman from Governance to identify who should be involved in this discussion (include Alyssa in the conversation)
- [ ] Schedule a phone call to discuss the goals and potential solutions/expectations around who should have access and what they should have access to (i.e. certain repos)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Brandon spoke with Clint about taking this work on, he noted we should revisit in Q2. Scheduled this for April 1st.

**Comment by alyssagallion** [comment]
@EWashb Is this something we still want to take on or are there other OCTODE conversations happening around it? I wanted to be sure before turning into an initiative or epic. Thanks!

**Comment by alyssagallion** [comment]
Moving to next sprint since Brandon is on IC.

**Comment by alyssagallion** [comment]
Followed up with Jonathan Kamens to assess if this is still something we want do from a security perspective.

**Comment by alyssagallion** [comment]
No response from security, doesn't seem to be high priority enough to pursue. Closing.
