### ISSUE TITLE
Familiarization with Behavior Analytics Tools to Generate a Report on User Sign-ins

### ISSUE THREAD

**Issue by joshmatulonis** [department-of-veterans-affairs/va.gov-team#71601]
## Description of UX Tasks
OKR's are expected to need monitoring through behavioral analytics tools. It is important to become comfortable using the available tools for use in monitoring/research/triangulating data. This will assist Identity to continue delivering an excellent, secure, private, usable sign in experience where fraud is continuously monitored and proactive measures are implemented to reduce its impact on users of VA.gov.

## Tasks
- [x] **Scenario 1: Research Identity Dashboard**
- [x] Gain access to tools- Datadog, GA, Domo, and any others.
   - [x] Ticket in with VA helpdesk for DD
- [x] Determine if R is available, in addition to other data viz tools.
  - [x] Become familiar with behavior analytics tools used to monitor telemetry and identify patterns/trends in sign in attempts.
  - [x] Sync with Joe on Datadog and reporting needs.
  - [x] Understand what data is available in Datadog, GA, and Domo.
  - [x] Create a report using the tools such as on avg weekly sign-ins within a time period and at a location. [Link to Report]( )
  

### Acceptance Criteria
- [ ]  Reviewed by UX Team
- [ ]  Reviewed by PMs
- [ ]  Documentation has been updated
- [ ]  Put published research in drive
- [ ] Product notes

### How to configure this issue

- [ ]  Attached to a Milestone (when will this be completed?)
- [x]  Attached to an Epic (what body of work is this a part of?)
- [x]  Labeled with Team (product support, analytics-insights, operations, service-design, Console-Services, tools-fe)
- [x]  Labeled with Practice Area (backend, frontend, devops, design, research, product, ia, qa, analytics, contact center, research, accessibility, content)
- [ ]  Labeled with Type (bug, request, discovery, documentation, etc.)

Dependencies

**Comment by joshmatulonis** [comment]
[Report on support calls](https://docs.google.com/spreadsheets/d/1kfrL-Tp_hVhvxAkmElKlpMpbgKZMlUWNl-RAzJ06xj4/edit?usp=sharing)
