### ISSUE TITLE
Document Initial Domo Processes

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#7161]
## User Story or Problem Statement
As a VSP Analytics & Insights team member, I need understand how to provision access to and connect data to Domo without a single point of failure.

## Goal
Document necessary Domo processes and definitions.

## Tasks
- [ ] Create a Domo How-To/Guide
    - [ ] Connecting to GA
    - [ ] Adding users
- [ ] (Joanne) Begin Domo Product Outline
- [ ] Switch over ownership of datasets/dashboards

## Acceptance Criteria
- [ ] VSP Analytics team members understand processes and standards for provisioning Domo access.
- [ ] VSP Analytics team members can connect GA data to VFS teams without a single point of failure

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
## Priorities

- VSP understand how to provision access to users
- VSP understand how to work together as a team to build out the dashboards (what does our internal process look like)
- VSP understand how to communicate with VFS on giving them the Product Success Tool

**Comment by joanneesteban** [comment]
## Documents added for review on 4/16/20

- [Provisioning access to users](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-add-users.md)
- [Dataset naming conventions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-data-naming-conventions.md)
- [Requesting the Product Success Tool](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/request-product-success-tool.md)
