### ISSUE TITLE
ARM 21-22 Form - User Test - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#71612]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
1. Rep landing page
2. 21-22 authenticated user flow

---
## Tasks
- [x] Request research review
- [x] Update user test to reflect collab cycle edits
- [x] Kick-off with Perigean
- [x] Set-up Enjoy HQ project
- [x] Create notetaker template
- [x] Kick-off with notetakers
- [x] Conduct pilot session
- [x] Kick-off with observers
- [x] Create interview Zenhub ticket
---
## Acceptance Criteria
- [x] Interviews scheduled

**Comment by jfinnerty13** [comment]
Sent for research review: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/450

**Comment by jfinnerty13** [comment]
Approved! Kick-off is Friday at 9am EST, then waiting on recruit

**Comment by jfinnerty13** [comment]
Recruitment complete and observers/notetakers signing up for sessions. Created following artifacts, kick-offs and pilot will be completed today
- https://app.enjoyhq.com/sh/pj/6eb83cbb-7658-43d4-85aa-ee3de0165db7
- https://docs.google.com/document/d/1cy1uZdFxywPxD8ASTG9Dj9CtBQNoCRtlO4oE4Tg-8ug/edit?usp=sharing
- https://dsva.slack.com/canvas/C06A76G3J3H
- https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702997471463/2b173921f1fd0f1c0e42af9a1b72620f83825d16?sender=u36b374887f74c9a3de2d0750
- https://docs.google.com/document/d/1cy1uZdFxywPxD8ASTG9Dj9CtBQNoCRtlO4oE4Tg-8ug/edit?usp=sharing
- https://docs.google.com/document/d/15bwmqf8qMroWrNQvtk7wvYkKl-FRwZqdM8Fh5eqnl5w/edit?usp=sharing
