### ISSUE TITLE
ARM 21-22 User Test - Conduct Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#71615]
## Issue Description
User test for ARM experience including Veteran representative engagement questions as well as VA.gov representative experiences of:
- Rep landing page
- 21-22 authenticated user flow
---
## Tasks
- [x] Complete interviews
- [ ] Manage interview day to day (team and recruiter coordination, debriefs, interviews, etc.)
- [x] Download videos and transcripts
- [x] Compile notes
- [ ] Upload notes, transcripts, and video to Sharepoint
- [ ] Upload notes and transcripts to EnjoyHQ
- [x] Create Zenhub ticket for analysis and reporting
---
## Acceptance Criteria
- [ ] All documents uploaded and ready for analysis & reporting

**Comment by jfinnerty13** [comment]
[2024-01 Appoint a Rep (Auth) User Test Themes_2024-01-03_20-49-55.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4257de9e977f5a78660602050d700956cd1b5e2/2024-01%20Appoint%20a%20Rep%20%28Auth%29%20User%20Test%20Themes_2024-01-03_20-49-55.pdf)

Day 1 themes complete and attached

**Comment by jfinnerty13** [comment]
[2024-01 Appoint a Rep (Auth) User Test Themes_2024-01-08_16-14-56.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5ae8b5cec0f005a572e03b66cd2e95546bc94c2/2024-01%20Appoint%20a%20Rep%20%28Auth%29%20User%20Test%20Themes_2024-01-08_16-14-56.pdf)
Day 2 themes attached

**Comment by oddball-lindsay** [comment]
interviews are complete!

**Comment by jfinnerty13** [comment]
[2024-01 Appoint a Rep (Auth) User Test Themes_2024-01-12_16-32-30.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHpEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29ca1bd0fe44d174386cc53feacdc83493b597f3/2024-01%20Appoint%20a%20Rep%20%28Auth%29%20User%20Test%20Themes_2024-01-12_16-32-30.pdf)
