### ISSUE TITLE
[Frontend] MDT - Add missing content to 'Veteran's personal information' (C1P1)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7162]
## User Story or Problem Statement
As a Veteran with incorrect personal information, I need contact information so I can remedy the mistakes.

## Goal
_Add missing content to the Veteran's personal information page (C1P1)._

## Objectives or Key Results this is meant to further
- _Finalize the MDT order flow_
---
## Tasks
- [ ] _Add the missing copy "Note: If you need to update.." to C1P1 as reflected [in the Invision prototype](https://vsateams.invisionapp.com/share/KNWJZ4EHE6C). The content can be copied directly from [this GH markdown file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-personal-details.md)_
- [ ] _Ensure additional missing copy is incorporated from the Invision prototype/GH markdown file_
- [ ] _Ensure existing copy matches the copy provided in the Invision prototype/GH markdown file_

## Acceptance Criteria
- [ ] _The copy between the staging environment and the Invision prototype matches_
---
