### ISSUE TITLE
[Analytics] [UX] Add GA event with a 45MR param in GA Dashboard widget

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71632]
## Tasks

https://dsva.slack.com/archives/C022AC2STBM/p1703106079739899?thread_ts=1703106049.615829&cid=C022AC2STBM

- [x] Add widget to pull in 45MR events into check in GA dashboard
- [x] Share with team 

## AC

- [x] Data is being pulled into widget in GA
- [ ] Team has validated

**Comment by benbrasso-agile6** [comment]
https://analytics.google.com/analytics/web/#/dashboard/1iHzB1FJTq6wHfngzN0LQg/a50123418w177519031p176188361/_u.dateOption=last7days/

https://analytics.google.com/analytics/web/#/dashboard/-LnfQTl3ShO8HbLIPQ7ZEQ/a50123418w177519031p176188361/_u.dateOption=last30days/

**Comment by benbrasso-agile6** [comment]
Pushing this into validate until the two bugs are fixed. or, we can decide to close.

**Comment by benbrasso-agile6** [comment]
Closing this ticket. Created two bug tix for FE that is in next sprint under the CIE Analytics Epic.
