### ISSUE TITLE
[MVP] Step 3: Correct button copy and remove button after max allowed for Current Employment list loop

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71638]
## Issue Description

Follow up task from review/QA of ticket #69758

- Julie S. mentioned that the VA design system doesn't offer disabled buttons for accessibility reasons.
- I checked the design system documentation (https://design.va.gov/components/button/) and confirmed.
- The way we are handling this in other parts of the form's design is to remove the button entirely and display an alert that they exceeded the max number of list / loop options.

## User Story
As a veteran who has completed the maximum employment entries allowed on the Pension form,
I need to see an alerts that states that I've entered the maximum number of items allowed,
so that I know to move to the next step of the form.

## Designs
- Screenflow reference: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/4EE913C1-DFEF-48D4-8744-C2B5A1BDE5CD/canvas

---
## Tasks
On Step 3 for Health and employment information, on the page with Current employment
- [ ] Once the user has entered the maximum number of items allowed into the current employment list loop, **remove the "Add another employment" button (Please note: the button may also be currently listed as "Add another job)**
- [ ] Once the user has entered the maximum number of items allowed into the current employment list loop, **add an alert that says "You've entered the maximum number of items allowed."**

See this screenshot as an example:
<img width="545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a8a40121966d13602e12cea0abfe4496659046d/288447076-ccd24ebf-9463-4d8d-9566-587d62f1b527.png" alt="288447076-ccd24ebf-9463-4d8d-9566-587d62f1b527.png" />

See this screenshot of example of the type of alert to use:
<img width="1135" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3b1be55220cf172df28d9e400f81244cfb89e47/288448204-ef4f244c-582d-426a-9483-c749deda67c0.png" alt="288448204-ef4f244c-582d-426a-9483-c749deda67c0.png" />

## Acceptance Criteria
- [x] Once the user has entered the maximum number of items allowed into the current employment list loop, they will no longer see a button to "Add another job"
- [x] Once the user has entered the maximum number of items allowed into the current employment list loop, they will see an alert that says "You've entered the maximum number of items allowed."

**Comment by aplatt-coforma** [comment]
Content looks good.
<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1IvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf35bb405018f77b64dbcc132ccccb8d83e6ca64/screencapture-staging-va-gov-pension-application-527EZ-employment-current-history-2023-12-21-13_25_48.png" alt="screencapture-staging-va-gov-pension-application-527EZ-employment-current-history-2023-12-21-13_25_48.png" />
