### ISSUE TITLE
Transition to VA Figma instance

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#71670]
## Task Description
Move files and processes from AH Figma instance to VA Figma instance

### Transfer process from AH to VA:

To transfer a project to another organization in Figma, we will need the following:

**From VA**
-  Destination URL of where the project will be moved to in the DSVA Figma organization: https://www.figma.com/files/project/175332858

**From your team:**
- Name of the team in Figma where the projects are currently in: VA Appointments FE Team
- Name of the projects that need to be transferred: Move to DSVA Figma

Once we have the destination URL, an admin from our team will initiate the transfer request to DSVA and an admin in their Figma organization will need to accept it. 

## Acceptance Criteria
- [x] Create a new cover page design
     - [x] Define new tags
     - [x] Add Team name
- [x]  Reach out to IT to figure out transfer process
- [x] Rename Templates file -> Feature Reference
- [x] Apply new cover page to all current files
- [x] Transfer everything over to DSVA Figma
- [x] Detach VAOS design system from Feature Reference
- [x] Move all VAOS-specific elements from VAOS Design System -> Feature reference
- [x] Delete VAOS Design System in Ad Hoc space
- [x] Delete archived Figma files in AD Hoc

---

**Comment by outerpress** [comment]
@Cieramaddox what's the plan for the feature reference and design system? I'm wondering if those should be separate efforts now that everything's copied over.

**Comment by outerpress** [comment]
Last thing to move over is the details redesign file.
