### ISSUE TITLE
Feedback Portal options for within Slack

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#71680]
## Purpose
How can we keep the feedback mechanism within Slack itself instead of linking out?
How might we address the high abandonment?  
Should we explore letting users remain in Slack with their form entry?  We'd also want to consider how to automate that approach.

Also: per our latest PO Sprint Review, Matt suggested moving ahead w/ the Slash command, then A/B testing with users to see what might be causing abandonment.

## Tasks
- [x] Research and document what options are available collecting Platform Feedback data in Slack
- [x] Recommendations about using Slack Apps
- [x] Document which channels to make this available in
- [x] [Document creating a direct survey to be delivered in Slack via Workflow Builder](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2879423007/Building+Platform+Feedback+in+Slack)

## Acceptance Criteria
- [x] Documentation on iterating survey setup in Slack
- [x] Recommendations

**Comment by gopixelsgo** [comment]
This ticket will roll over to next sprint to wrap up remaining work.
