### ISSUE TITLE
[UX] Read through platform documentation on Figma

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71698]
## Description 

Get familiar with the transition from Sketch to Figma. 

## Tasks

- [ ] [Request access to Figma](https://depo-platform-documentation.scrollhelp.site/research-design/figma-accounts-at-va)
- [ ] [Download Figma desktop app](https://depo-platform-documentation.scrollhelp.site/research-design/figma-accounts-at-va#FigmaaccountsatVA-Browservs.Desktopapp)
- [ ] Read (to be familiar with) [how to move files to Figma](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma)
- [ ] Read (to be familiar with) [how to design for Figma](https://depo-platform-documentation.scrollhelp.site/research-design/designing-with-figma-at-va)

## AC

- [x] Christina has completed tasks
- [x] Ben has completed tasks
- [x] Zach has completed tasks
- [ ] Ya-ching has completed tasks
- [x] Kelly has completed tasks

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/71698?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by benbrasso-agile6** [comment]
@benbrasso-agile6 @cgednalske @kellysmith1008 @ytsaoca @zach-park feel free to "unassign" yourself once completed

**Comment by cgednalske** [comment]
@loripusey closing this one 🎉
