### ISSUE TITLE
[UX] [Design] Move files to Figma

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71690]
## Tasks

- [x] Download all Sketch files locally
    - Zach will maintain the Sketch files on his local hard drive & backed up to another device or in the cloud so we don't lose them
- [x] Find project in Figma ([MHV on VA.gov](https://www.figma.com/files/project/175332858/MHV-on-VA.gov?fuid=1175479952799719494) per Kristen McConnel, look for updates in [Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1702318354274929)) and import Sketch files. Do NOT import Playground or Posters Sketch files. [How to import instructions. Recommend using the browser](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma). 
- [x] [Set thumbnails](https://www.figma.com/file/lQahoRhgSYvbLKkEDgHEsU/z_Template-%7C-Cover-Pages?type=design&node-id=0-1&mode=design&t=Uv5rwbVSDYsDSKkb-0)
- [x] [Enable component library](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma#HowtomoveyourworkfromSketchtoFigma-6.EnabletheVAdesignlibrary)

## AC

- [x] Files are in Figma ([MHV on VA.gov](https://www.figma.com/files/project/175332858/MHV-on-VA.gov?fuid=1175479952799719494) per Kristen McConnel)
- [x] Component library is enabled on each file  
- [ ] Have another designer validate the work

## Delivery

Unified Figma file:
https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-Check-In-%7C-Check-in?type=design&node-id=0-1&mode=design&t=Z8ISJMBZws4P5cVz-0

Pre-check-in Figma file:
https://www.figma.com/file/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in?type=design&mode=design&t=Wv7geVmBnjxcTpfH-0

eCheck-in Figma file:
https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in?type=design&mode=design&t=Wv7geVmBnjxcTpfH-0

**Comment by benbrasso-agile6** [comment]
@zach-park I started building the [check in production file here](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=0%3A1&mode=design&t=RspvPSTdtM8Eo7yz-1). Maybe we keep separate files for pre-check-in and check-in.

**Comment by zach-park** [comment]
Initial import of the Unified is available here:
https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-Check-In-%7C-Check-in?type=design&node-id=0-1&mode=design&t=Z8ISJMBZws4P5cVz-0
( @benbrasso-agile6 @cgednalske @ytsaoca @kellysmith1008 )

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske @ytsaoca , the [Unified Figma file](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-Check-In-%7C-Check-in?type=design&node-id=0-1&mode=design&t=Z8ISJMBZws4P5cVz-0) is ready for validation.

**Comment by benbrasso-agile6** [comment]
@zach-park can you move over Check In and Pre-Check-In too

**Comment by zach-park** [comment]
Check In and Pre-Check-In Figma file is added and ready for validation now:
https://www.figma.com/file/tHc7wMREc1EXuUtSMAWe7G/Pre-check-in-and-check-in---Production?type=design&mode=design&t=Wv7geVmBnjxcTpfH-0
@benbrasso-agile6 @cgednalske @ytsaoca @kellysmith1008

**Comment by benbrasso-agile6** [comment]
What I meant was, move over the echeckin file and the pre check in file. Two different files. And, so, we can use those two files to create new features, then move/copy into production file, like we do today in sketch. Cc @cgednalske

**Comment by zach-park** [comment]
> What I meant was, move over the echeckin file and the pre check in file. Two different files. And, so, we can use those two files to create new features, then move/copy into production file, like we do today in sketch. Cc @cgednalske

Noted. I'm working on them now. :)

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske @ytsaoca @kellysmith1008 , Pre-check-in and eCheck-in Figma files are ready to be validated. 

Pre-check-in Figma file:
https://www.figma.com/file/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in?type=design&mode=design&t=Wv7geVmBnjxcTpfH-0

eCheck-in Figma file:
https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in?type=design&mode=design&t=Wv7geVmBnjxcTpfH-0

**Comment by benbrasso-agile6** [comment]
LGTM thx Zach
