### ISSUE TITLE
[UX] [Design] Identify what needs to be cleaned up in files

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71691]
## Tasks

- [ ] Create list of things that need to be cleaned up in each file (could be high-level, could be detailed; it really depends after import) 
- [ ] Create a f/u ticket to implement that clean up work 

## AC

- [ ] Created list of clean up needed
- [ ] F/u ticket created to implement the file clean up work
