### ISSUE TITLE
[MVP] Step 2 Military history: Change branch of service question type, update date labels, remove button & option to enter multiple service periods

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71705]
## Issue Description
To better map data to the PFD, we need to:

- Update Branch of Service from short-text field to multi-select answer options, to match the PDF form. Answer options will be:
-- Army
-- Navy
-- Air Force
-- Coast Guard
-- Marine Corps
-- Space Force
-- USPHS
-- NOAA
- Match the start date and end date labels from the web form to match the PDF form. Labels should be:
-- Date initially entered active duty
-- Final release date from activity duty
- Remove the "Add another service period" button
- Remove the ability for user to enter multiple service periods

## Mockup of corrections:
<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43b9fb5fc65f61b97e04fb7b60da1d74b8ea97eb/Screenshot%202023-12-11%20at%204.30.15%E2%80%AFPM%20%281%29.png" alt="Screenshot 2023-12-11 at 4.30.15 PM (1).png" />

---
## Tasks

- [ ] Update Branch of Service from short-text field to multi-select answer options, to match the PDF form. Answer options will be:
-- Army
-- Navy
-- Air Force
-- Coast Guard
-- Marine Corps
-- Space Force
-- USPHS
-- NOAA

- [ ] Match the start date and end date labels from the web form to match the PDF form. Labels are shown on the mock up, but also below:
- Date initially entered active duty
- Final release date from active duty

- [ ] Remove the "Add another service period" button

- [ ] Remove the ability for user to enter multiple service periods

## Acceptance Criteria
- The Branch of Service question type will have multi-select options, to [match PDF form question 3E](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- The date labels on this page will match the PDF form fields ([3B & 3C on PDF](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf))
- The user will no longer be able to add multiple service periods

**Comment by TaiWilkin** [comment]
@vbellissimo Is this what you're thinking for multi-select?
<img width="617" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a19b3babada1a7d58e5a2545dc43619f70040b5b/Screenshot%202023-12-14%20at%201.53.12%E2%80%AFPM.png" alt="Screenshot 2023-12-14 at 1.53.12 PM.png" />

**Comment by jstrothman** [comment]
@vbellissimo @TaiWilkin For usability, let's use checkboxes rather than multi-select.

**Comment by jstrothman** [comment]
@TaiWilkin That looks great--sorry I couldn't see the screenshot in GitHub

**Comment by vbellissimo** [comment]
Thanks @jstrothman and thank you @TaiWilkin . I think it looks good, too. I'll move to our Completed column.

**Comment by vbellissimo** [comment]
@TaiWilkin sorry I noticed it's not in the PR phase yet. I won't move.

**Comment by aplatt-coforma** [comment]
Content looks good
<img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGQwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b845bcbe21bdb2b5901a1ec70cf963688cbe15e8/screencapture-staging-va-gov-pension-application-527EZ-military-history-2023-12-19-13_23_15.png" alt="screencapture-staging-va-gov-pension-application-527EZ-military-history-2023-12-19-13_23_15.png" />
