### ISSUE TITLE
Add 2024 Deployment Freeze Schedule to Platform Website

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#71701]
## Description
We need to update the 2024 deployment freeze schedule on the Platform Website. This information is documented on this page, in the [Deployment Policies](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-2023).

### 2024 Dates (from Clint Little, 12/14)

> The holiday release freeze is in effect during the following dates:
> 
> **2024**
1/15/2024 - Martin Luther King Jr. Day
5/27/2024 - Memorial Day
6/19/2024 - Juneteenth
7/4/2024 - Independence Day
9/2/2024 - Labor Day
11/11/2024 - Veteran's Day
11/28 - 11/29 - Thanksgiving
12/23 - 1/3/2025 - Holiday Freeze

## Tasks

- [x] Connect with Johnny on 2024 dates (JJ reached out to Clint)
- [x] Update the [deployment policies](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-2023) page with this information, in a similar format to how it was presented for 2023.
- [x] Prepare page for deployment.
- [x] Deploy page

## Acceptance Criteria

- [x] The Deployment Policies page is updated with dates for 2024 code freeze dates.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/71701?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by laucon** [comment]
Johnny, should we delete the 2023 dates after inserting the 2024 dates? That's unclear to me, though I would think that logically, the answer would be yes.

**Comment by johnny-jesensky-adhoc** [comment]
This page was deployed and made live last week with the 2024 freeze dates. Meets our AC, so moving this to _Done_.
