### ISSUE TITLE
Draft secondary nav research plan and designs

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#71714]
### User story

As a Cartographers team member, I want to share a secondary navigation research plan and design(s) with OCTO product and design stakeholders, so that we can get feedback and move quickly to developing the prototypes.

[Wes note: submitting to OCTO seems like a reasonable arbitrary milestone that would insulate the ticket from feedback turnaround, but I'm open to picking another arbitrary boundary]

## Acceptance criteria

- Rough-drafted research plan sections around goals, hypotheses, and study design
- Designed UI(s) appropriate to the research plan
- Submitted plan and design(s) to OCTO design leads for feedback

## Tasks

- [x] Meet with Ryan T and Kaitlin as needed to preserve alignment, seed iterative feedback
- [ ] Share draft plan and designs with Patrick for any red flags
- [ ] Coordinate OCTO sharing/approval approach with Kaitlin
