### ISSUE TITLE
Communicate Insights Staff Changes to Necessary Stakeholders

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#7172]
## User Story or Problem Statement
As a VFS team member, I need understand how to communicate to VSP Analytics & Insights.

## Goal
Update necessary stakeholders and processes for staff changes.

## Tasks
- [x] Respond to DMs & emails to post on #vfs-platform-support
- [x] Joanne to announce in ToT
- [ ] Nedie creates (basic) best practices communications doc to hand over to teammates

## Acceptance Criteria
- [ ] VFS teams understand how to communicate with VSP Analytics & Insights
- [ ] External teams understands how to communicate with VSP Analytics

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Updated the team charter to include Slack communication best practices.
