### ISSUE TITLE
[HCD] Migrate design files to Figma

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#71735]
## Value Statement

**_As a_** designer

**_I want to_** migrate my project Sketch files to Figma before Feb 16, 2024

**_so that_** our team does not lose any work from the transition to a new tool.

---
## Background Context
VA is transitioning from Sketch to Figma. Sketch accounts will be closed on Feb. 16, 2024. Files must migrate to Figma before deadline. 80% of components are currently available in Figma.

## Acceptance Criteria
- [x] All appeals Sketch files have been transitioned to Figma
- [x] Core project files have been cleaned up and updated, connecting to the Figma design system
   - [x] NOD
   - [x] SC
   - [x] HLR
- [x] Make sure styles are up-to-date (including some new v3 web components)
   - [x] NOD
   - [x] SC
   - [x] HLR
- [x] Add changelog to design files to keep track of updates
   - [x] Confirm widget changelog is acceptable

## Definition of Ready 
- [x] Access has been given to VA Figma project space

## Tasks
- [x] Prepare Sketch file
- [x] Download Sketch file
- [x] Import Sketch file to Figma
- [x] Set custom thumbnails
- [x] Enable the VA design library
- [x] Clean up file (reconnect broken symbols)
- [x] Invite team (read-only or editor access)

**Comment by eileen-coforma** [comment]
Update SIP style to v3 web styles (automatically updated for forms) - https://github.com/department-of-veterans-affairs/vets-website/pull/27243

**Comment by eileen-coforma** [comment]
Finished HLR, but found that SC review page was not updated to new components. Also, the review page does not have all the error states.

**Comment by eileen-coforma** [comment]
@Mottie Can you take a look at this to see if anything looks off/missing or inaccessible in general? https://www.figma.com/files/project/176170255/Decision-Reviews---Appeals?fuid=1141788357697076960

**Comment by Mottie** [comment]
I've started my review... 
- [x] NOD
- [ ] HLR
- [ ] Supplemental Claims

**Comment by Mottie** [comment]
Ok, I've completed my review of our DR forms!

**Comment by eileen-coforma** [comment]
Making updates to the design files based on the review.

**Comment by eileen-coforma** [comment]
Migration is complete. Separating out bug documentation work into a different ticket #82249
