### ISSUE TITLE
COE | Retry Claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71747]
## Issue Description
_In #63096 we learned that COE claims do not retry bc it's a synchronous api call. Veterans are not notified if there is an issue via vets-api._

This code here must be refactored to use a background job for processing after a claim is saved. Currently the COE form is cleared whether the request fails or not.  We'll need to tell the user that their form is being submitted. 

    def submit_coe_claim
      claim = SavedClaim::CoeClaim.new(form: filtered_params[:form])

      unless claim.save
        StatsD.increment("#{stats_key}.failure")
        Raven.tags_context(team: 'vfs-ebenefits') # tag sentry logs with team name
        raise Common::Exceptions::ValidationErrors, claim
      end

      response = claim.send_to_lgy(edipi: current_user.edipi, icn: current_user.icn)

      Rails.logger.info "ClaimID=#{claim.confirmation_number} Form=#{claim.class::FORM}"
      clear_saved_form(claim.form_id)
      render json: { data: { attributes: { reference_number: response, claim: } } }
    end
    
We COULD do something like 526 where we first try to autoestablish a claim before moving to a background job, but this may be of little benefit.   

---
## Tasks
- [ ] Make COE retryable
- [ ] Notify Veteran of retry submission

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by micahaspyr** [comment]
Forgot to put my initial thoughts here and steps I'll be implementing
1. Try and establish claim as is
  - If successful, return reference number as is currently done
  - If unsuccessful
    - Check if failure is a retryable error i.e. system outage
    - If so, retry the sidekiq job and notify the veteran the job has been queued and look to send the reference number via email
    - If not, state the error (likely lack of EDIPI

**Comment by steele-lm** [comment]
Question from Emily: Is the Veteran notified of the failure on the FE?

**Comment by micahaspyr** [comment]
The Veteran is notified by the form when there is a failure on the backend.  I'm putting this in blocked until we make a final decision

**Comment by steele-lm** [comment]
@micahaspyr Do we have an example of the error message the user sees?

**Comment by micahaspyr** [comment]
500 error:

![500-Error](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/e7062818-e137-4095-aafe-832eebb2168b)

Generic Error: 

![Generic-error](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/97c668f1-7c49-466f-8d26-f459ab6116b0)

Throttled Error:
![Throttled-error](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/5016b94c-b3eb-41a2-aac0-402eb4a3d4d5)

Validation Error:

![Validation-error](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/7ae9624b-ec67-41cb-b319-d7ea059e36ab)

**Comment by steele-lm** [comment]
Decision From Emily/Steve: Do not add async submission to COE. Existing FE error notifications in COE form are adequate to inform Veteran of an issue and steps to remediate. Future work should identify:
- How calls are failing and how often
- Behavior or FE validation error: What pattern do other forms follow? Is validation earlier in the form missing that could mitigate this error?
