### ISSUE TITLE
SPIKE | CH 31 | Cause of Failed Claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71743]
## Issue Description
_We suspect that some Chapter 31 claims are failing submission. We need to determine:_

---
## Tasks
- [ ] Confirm what happened.
   - [ ] Did we fail to retrieve an identity and then never send them to CMP in the first place?
   - [ ] How many failures?
   - [ ] Who did they happen to?
   - [ ] How far back did failures happen?
- [ ] Determine how to fix it
   - [ ] Do we have logs?
- [ ] Determine if it was a silent failure.
   - [ ] Did the veteran receive any front-end notification or email or any signal of a problem?
   - [ ] Did the claim retry?
- [ ] Determine if the submissions can be re-generated for re-submission

## Acceptance Criteria
- [ ] Answers to above questions
- [ ] Follow on tickets created
---
