### ISSUE TITLE
Publicize slash command for Feedback Portal and update docs

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71767]
## Purpose
Let's announce the new path and publicize in the appropriate channels.  Let's also update the Confluence documentation and Platform docs to reflect the changes.

*note: be sure to speak to the "flexibility" of the phrasing/words

Order of operations will matter, as the capability [isn't truly available](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2875392272/Testing+of+Slash+Command+launch+of+Feedback+Portal#Learnings%3A) until users encounter the shared link in Slack.

## Tasks
- [x] Remove existing workflow bookmark in platform-support, replacing it with new Feedback Portal workflow/link
- [x] Cancel existing Feedback Portal reminders in Slack
- [x] Update workflow permissions to all users in DSVA
- [x] update Confluence [explanatory doc](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2645753888/Platform+Feedback+Portal+explanatory+page)
- [x] update Platform docs [page](https://depo-platform-documentation.scrollhelp.site/support/give-feedback-about-platform-products-or-services)
- [x] post announcement and link in vfs-all-teams
- [x] post announcement and link in vfs-change-announcements
- [x] post announcement and link  in platform-support
- [x] Setup ongoing reminders in vfs-all-teams

## Acceptance Criteria
- [x] announcements posted in channels
- [x] confluence updated
- [x] Platform Docs page updated

**Comment by gopixelsgo** [comment]
This ticket is "in progress" but is already set to Sprint: Dec. 21 - Jan. 2, so it shouldn't _need_ to roll over, but in case it needs saying, I'm confirming that it should in fact roll over. 🙃

**Comment by twoangstroms** [comment]
Holding to next sprint to finalize Slack announcements and reminders
