### ISSUE TITLE
EVSS Migration - 526 Submit - hook up SubmitForm526 job to Lighthouse synchronous submit endpoint

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#71773]
## Issue Description
Lighthouse is updating the /submit endpoint to provide a synchronous response for the claim ID (/submit v2). We need to revisit the questions and issues we had to ensure the new endpoint fits in with previous migration code, assess any changes needed & issues that are still existing, so that we can complete the 2022 form rollout.

## Tasks
- update the SubmitForm526 job to capture established claim ID from Lighthouse synchronous submit endpoint
- in the BenefitsClaims service, use the Lighthouse synchronous submit endpoint

## Acceptance Criteria
- [ ] capture submitted claimID
- [ ] Successful submission using vets-api code

Out of scope:
---
## Need to Know - review previous issues/questions 
#2 on Task list - ClaimDate
- LH does not accept claim dates as EVSS does today
- This will not allow any submissions to be back-dated
- Check with Emily on need for this to be back-dated
#3 on Task list - Confinement period fails the submission
 - Check for the bug fix on LH endpoint
 - 
- follow-up to #65051 && #69080
- List of issues found with the debugging tool
- LH validation checks
[slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1701986590863839)

Check up on issues:
- [ ]  1: ~TE bug~
- [ ]  2: claimDate attribute
- [ ]  3: verify confinement/service period bug fix (when delivered)
- [ ]  [Place holder for possible other things that we don't know about yet]

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
- Verify confinement/service period bug fix is now in sandbox - https://dsva.slack.com/archives/C02CQP3RFFX/p1702403893661139?thread_ts=1701986590.863839&cid=C02CQP3RFFX
- Claim Date issue - LH will be handling the retries with the correct date so they are not considering this a requirement to accept claim date from 526.
cc @sethdarragile6 @aurora-a-k-a-lightning

**Comment by alatempa24** [comment]
Update from LH sync 5/31/24:
/submit v2 is slated to be released to LH staging soon, hoping for 6/5/24.

**Comment by alatempa24** [comment]
[Lighthouse confirmed sync submit endpoint is available in Lighthouse staging](https://dsva.slack.com/archives/C02CQP3RFFX/p1717686150321999?thread_ts=1717680875.277439&cid=C02CQP3RFFX).

**Comment by aurora-a-k-a-lightning** [comment]
this PR addresses the treatment date issue noted in #84199 as it was a blocker to complete this ticket
