### ISSUE TITLE
Feedback Mechanism Stage II Testing

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#71778]
## Issue Description
Complete phase II user testing for Rate Your Experience Feedback mechanism, confirm all requirements are met.   Complete styling and final review. 
---
## Tasks
- [ ] Phase II testing - 
- [ ]  Confirm all requirements have been met
- [ ]   Ensure va.gov experience standards and va.gov platform QA standards are met
- [ ]    Complete before meeting/VFS actions in the Staging Review section of their Collaboration Cycle Request ticket.
- [ ]    Add test user information, tasks in .md file in repository (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support/rate-tool )
- [ ]     Complete styling
- [ ]      Final Review

## Acceptance Criteria

- [ ] **Scenario 1: Phase II Testing**
  - [ ] Task 1: Perform Phase II testing
  - [ ] Task 2: Confirm all requirements have been met
  - [ ] Task 3: Ensure va.gov experience standards and va.gov platform QA standards are met
  - [ ] Task 4: Complete before meeting/VFS actions in the Staging Review section of their Collaboration Cycle Request ticket
  - [ ] Task 5: Add test user information, tasks in .md file in repository (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support/rate-tool)
  - [ ] Task 6: Complete styling
  - [ ] Task 7: Final Review
  - [ ] Acceptance Criteria:
    - [ ] Complete all above tasks
    - [ ] Verify that the issue is linked to https://github.com/department-of-veterans-affairs/va.gov-team/issues/65297

- [ ] **Scenario 2: Configuration**
  - [ ] Task 1: Attach the issue to a Milestone
  - [ ] Task 2: Attach the issue to an Epic
  - [ ] Task 3: Label the issue with the appropriate Team (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
  - [ ] Task 4: Label the issue with the appropriate Practice Area (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
  - [ ] Task 5: Label the issue with the appropriate Type (`bug`, `request`, `discovery`, `documentation`, etc.)
  - [ ] Acceptance Criteria: None specified

**Comment by UXCamG** [comment]
We are waiting on Medallia 2.0 implementation.
