### ISSUE TITLE
CH 36 | Create DD Dashboard and Monitor

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71775]
## Issue Description
_Set up a Datadog dashboard to monitor Chapter 36. Related ticket is #67879._

---
## Tasks
- [ ] Set up DD dashboard that monitors logs for Ch 36.
- [ ] Set up monitor alert for Ch 36.

## Acceptance Criteria
- [ ] DataDog dashboard for Ch 36
- [ ] DataDog monitor for Ch 36
---
