### ISSUE TITLE
[FE] [BUG] When Provider Name is blank, no content should be shown, including "with"

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#71772]
## Description
We do not currently have access to the Provider name; our guidance when the Provider information is not available is to display no content. This includes not displaying the "with" content.

## Tasks
- [ ] [FE] **When Provider Name is blank, no content should be shown, including "with"**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
Functionality is already in place, don't need this ticket, closing
