### ISSUE TITLE
Facility Operating Status (Alerts)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7178]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-locator-product-outline.md)

## High Level User Story/ies
As a Veteran, I need to know when the hours of operations for a facility have been impacted by an emergency so that I can adjust my plan to visit.

## Hypothesis or Bet
**If** we implement the ability to display an alert/banner at the facility sub-type level **then** we expect to provide timely facility information during emergencies. 

## OKR
OBJECTIVE 2: Deliver meaningful facility information 

## Definition of done
The following milestones have been successfully completed (or determined to be unnecessary for this work)
- [x] Project Kickoff (N/A due to urgency of work)
- [x] Design Intent Collaboration (N/A due to urgency of work)
- [x] Usability Testing Prep [#7477]
- [ ] Research Plan Review 
      - [#7520]
      - [#7838] 
- [x] Information Architecture (IA) Request (N/A due to nature of work)
- [x] Analytics Request [#7336]
- [x] [Contact Center Review](https://dsva.slack.com/archives/CNCEXNXK4/p1586467531002500)
- [ ] Staging Review
- [x] Privacy and Security Review (N/A due to nature of work)
- [ ] Full Accessibility and 508 Office Audit
- [ ] Post-launch Check-in

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
