### ISSUE TITLE
Feedback Mechanism Analytics Review 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#71780]
## Issue Description
Data will be analyzed and determine level of interaction with tool
---
## Tasks
- [x] _Review metrics 
- [ ] 

## Acceptance Criteria
- [ ] Tagging complete
- [ ] QA complete
- [ ] ---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by UXCamG** [comment]
We have identified the metrics that we will analyze and added report was added to  this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70604) . We will review analytics again once Vol 2 of Medallia has been implemented.

**Comment by UXCamG** [comment]
Awaiting final report from Jaime.
