### ISSUE TITLE
[BE] Update Sequence Diagram for Upcoming Appointments

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#71783]
## Description
Appointment data received from vaos/appointments service doesn't have enough information for vets-website to display for the veterans in front-end.  Facilities API needs to be called fetch facility specific information like appointment timezone, physical address, phone number etc. (Reference [slack thread](https://dsva.slack.com/archives/C023EFZPX4K/p1702052195232519?thread_ts=1701980841.534199&cid=C023EFZPX4K))

As part of this task, update [sequence diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/decisions/all-appointments-fetch.md) and confirm the request/response payload for GetAppointments API implemented in vets-api for fetching upcoming appointments.

## Tasks
- [ ] [BE] **Update Sequence Diagram for facilities API call**
- [ ] [BE] **Include failure scenarios in sequence diagram**
- [ ] [BE] **Identify response when either appointments or facilities API call fails**
- [ ] [BE] **Document GetAppointments API Request/Response payload for success & failure cases**

## Acceptance Criteria
- [ ] Sync within Engineering Team

**Comment by loripusey** [comment]
@randomsync so did you just swap this ticket into the sprint and the solution design ticket out of the sprint because they are equivalent? I'm confused.

**Comment by randomsync** [comment]
No, I pulled this in because it's a part of solution design. Not sure why the solution design ticket wasn't in this sprint, so pulled that one in as well.

**Comment by loripusey** [comment]
@randomsync is this one done?
