### ISSUE TITLE
Auto assign support label where applicable when a ticket is reassigned

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#71785]
## Issue Description
WIth all tasks being auto-assigned to tier 1, we have lost the COP assigned labels that were on tickets. The "Reassign ticket" button does not currently interact with GitHub at all. We'd like if a ticket is reassigned to a team that has a github label, to add that label to the ticket automatically.

---
## Tasks
- [ ] Add function to add team label to existing support GItHub issues where applicable.
- [ ] Ensure that labels get removed if reassigned again.

## Acceptance Criteria
- [ ] Reassigned tickets get the correct github labels.
