### ISSUE TITLE
[BE] Implement Facilities API Client Class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#71788]
## Description
Implement client class for calling facilities API (Ref [slack thread](https://dsva.slack.com/archives/C023EFZPX4K/p1702052195232519?thread_ts=1701980841.534199&cid=C023EFZPX4K))

## Tasks
- [ ] [BE] **Implement Client Class**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
