### ISSUE TITLE
[BE] Implement Service class for Facilities API

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#71789]
## Description
Implement service class for Facilities API (Ref [slack thread](https://dsva.slack.com/archives/C023EFZPX4K/p1702052195232519?thread_ts=1701980841.534199&cid=C023EFZPX4K))

## Tasks
- [ ] [BE] **Service class for Facilities API**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
