### ISSUE TITLE
[BE] Implement VAOS Appointment Serializer

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#71787]
## Description
Implement serializer for fetching only required fields in appointments payload received from VAOS appointments service.  Output of the serializer should be an array of appointments data with only fields required for sending to front-end or framing request payload for facilities API.

These are the fields to send to the frontend:

identifier
kind
status
serviceType
locationId
start
end
extension

{

    "data": [

        {

            "id": "180765",

            "identifier": [

                {

                    "system": "Appointment/",

                    "value": "413938333130383735"

                },

                {

                    "system": http://www.va.gov/Terminology/VistADefinedTerms/409_84,

                    "value": "983:10875"

                }

            ],

            "kind": "clinic",

            "status": "booked",

            "serviceType": "amputation",

            "serviceTypes": [

                {

                    "coding": [

                        {

                            "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,

                            "code": "amputation"

                        }

                    ]

                }

            ],

            "serviceCategory": [

                {

                    "coding": [

                        {

                            "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,

                            "code": "REGULAR",

                            "display": "REGULAR"

                        }

                    ],

                    "text": "REGULAR"

                }

            ],

            "patientIcn": "1013125218V696863",

            "locationId": "983GC",

            "clinic": "1081",

            "start": "2023-11-06T16:00:00Z",

            "end": "2023-11-06T16:30:00Z",

            "minutesDuration": 30,

            "slot": {

                "id": "3230323331313036313630303A323032333131303631363330",

                "start": "2023-11-06T16:00:00Z",

                "end": "2023-11-06T16:30:00Z"

            },

            "created": "2023-08-02T00:00:00Z",

            "cancellable": true,

            "extension": {

                "ccLocation": {

                    "address": {}

                },

                "vistaStatus": [

                    "NO ACTION TAKEN"

                ],

                "preCheckinAllowed": true,

                "eCheckinAllowed": true

            }

        },

        {

            "id": "180766",

            "identifier": [

                {

                    "system": "Appointment/",

                    "value": "413938333130383736"

                },

                {

                    "system": http://www.va.gov/Terminology/VistADefinedTerms/409_84,

                    "value": "983:10876"

                }

            ],

            "kind": "clinic",

            "status": "booked",

            "serviceType": "amputation",

            "serviceTypes": [

                {

                    "coding": [

                        {

                            "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,

                            "code": "amputation"

                        }

                    ]

                }

            ],

            "serviceCategory": [

                {

                    "coding": [

                        {

                            "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,

                            "code": "REGULAR",

                            "display": "REGULAR"

                        }

                    ],

                    "text": "REGULAR"

                }

            ],

            "patientIcn": "1013125218V696863",

            "locationId": "983GC",

            "clinic": "1081",

            "start": "2023-11-13T16:00:00Z",

            "end": "2023-11-13T16:30:00Z",

            "minutesDuration": 30,

            "slot": {

                "id": "3230323331313133313630303A323032333131313331363330",

                "start": "2023-11-13T16:00:00Z",

                "end": "2023-11-13T16:30:00Z"

            },

            "created": "2023-08-02T00:00:00Z",

            "cancellable": true,

            "extension": {

                "ccLocation": {

                    "address": {}

                },

                "vistaStatus": [

                    "FUTURE"

                ],

                "preCheckinAllowed": true,

                "eCheckinAllowed": true

            }

        },

        {

            "id": "180767",

            "identifier": [

                {

                    "system": "Appointment/",

                    "value": "413938333130383737"

                },

                {

                    "system": http://www.va.gov/Terminology/VistADefinedTerms/409_84,

                    "value": "983:10877"

                }

            ],

            "kind": "clinic",

            "status": "booked",

            "serviceType": "amputation",

            "serviceTypes": [

                {

                    "coding": [

                        {

                            "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,

                            "code": "amputation"

                        }

                    ]

                }

            ],

            "serviceCategory": [

                {

                    "coding": [

                        {

                            "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,

                            "code": "REGULAR",

                            "display": "REGULAR"

                        }

                    ],

                    "text": "REGULAR"

                }

            ],

            "patientIcn": "1013125218V696863",

            "locationId": "983GC",

            "clinic": "1081",

            "start": "2023-11-20T16:00:00Z",

            "end": "2023-11-20T16:30:00Z",

            "minutesDuration": 30,

            "slot": {

                "id": "3230323331313230313630303A323032333131323031363330",

                "start": "2023-11-20T16:00:00Z",

                "end": "2023-11-20T16:30:00Z"

            },

            "created": "2023-08-02T00:00:00Z",

            "cancellable": true,

            "extension": {

                "ccLocation": {

                    "address": {}

                },

                "vistaStatus": [

                    "FUTURE"

                ],

                "preCheckinAllowed": true,

                "eCheckinAllowed": true

            }

        },

        {

            "id": "180768",

            "identifier": [

                {

                    "system": "Appointment/",

                    "value": "413938333130383738"

                },

                {

                    "system": http://www.va.gov/Terminology/VistADefinedTerms/409_84,

                    "value": "983:10878"

                }

            ],

            "kind": "clinic",

            "status": "booked",

            "serviceType": "amputation",

            "serviceTypes": [

                {

                    "coding": [

                        {

                            "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,

                            "code": "amputation"

                        }

                    ]

                }

            ],

            "serviceCategory": [

                {

                    "coding": [

                        {

                            "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,

                            "code": "REGULAR",

                            "display": "REGULAR"

                        }

                    ],

                    "text": "REGULAR"

                }

            ],

            "patientIcn": "1013125218V696863",

            "locationId": "983GC",

            "clinic": "1081",

            "start": "2023-11-27T16:00:00Z",

            "end": "2023-11-27T16:30:00Z",

            "minutesDuration": 30,

            "slot": {

                "id": "3230323331313237313630303A323032333131323731363330",

                "start": "2023-11-27T16:00:00Z",

                "end": "2023-11-27T16:30:00Z"

            },

            "created": "2023-08-02T00:00:00Z",

            "cancellable": true,

            "extension": {

                "ccLocation": {

                    "address": {}

                },

                "vistaStatus": [

                    "FUTURE"

                ],

                "preCheckinAllowed": true,

                "eCheckinAllowed": true

            }

        },

        {

            "id": "180769",

            "identifier": [

                {

                    "system": "Appointment/",

                    "value": "413938333130383739"

                },

                {

                    "system": http://www.va.gov/Terminology/VistADefinedTerms/409_84,

                    "value": "983:10879"

                }

            ],

            "kind": "clinic",

            "status": "booked",

            "serviceType": "amputation",

            "serviceTypes": [

                {

                    "coding": [

                        {

                            "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,

                            "code": "amputation"

                        }

                    ]

                }

            ],

            "serviceCategory": [

                {

                    "coding": [

                        {

                            "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,

                            "code": "REGULAR",

                            "display": "REGULAR"

                        }

                    ],

                    "text": "REGULAR"

                }

            ],

            "patientIcn": "1013125218V696863",

            "locationId": "983GC",

            "clinic": "1081",

            "start": "2023-12-04T16:00:00Z",

            "end": "2023-12-04T16:30:00Z",

            "minutesDuration": 30,

            "slot": {

                "id": "3230323331323034313630303A323032333132303431363330",

                "start": "2023-12-04T16:00:00Z",

                "end": "2023-12-04T16:30:00Z"

            },

            "created": "2023-08-02T00:00:00Z",

            "cancellable": true,

            "extension": {

                "ccLocation": {

                    "address": {}

                },

                "vistaStatus": [

                    "FUTURE"

                ],

                "preCheckinAllowed": true,

                "eCheckinAllowed": true

            }

        },

        {

            "id": "180770",

            "identifier": [

                {

                    "system": "Appointment/",

                    "value": "413938333130383830"

                },

                {

                    "system": http://www.va.gov/Terminology/VistADefinedTerms/409_84,

                    "value": "983:10880"

                }

            ],

            "kind": "clinic",

            "status": "booked",

            "serviceType": "amputation",

            "serviceTypes": [

                {

                    "coding": [

                        {

                            "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,

                            "code": "amputation"

                        }

                    ]

                }

            ],

            "serviceCategory": [

                {

                    "coding": [

                        {

                            "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,

                            "code": "REGULAR",

                            "display": "REGULAR"

                        }

                    ],

                    "text": "REGULAR"

                }

            ],

            "patientIcn": "1013125218V696863",

            "locationId": "983GC",

            "clinic": "1081",

            "start": "2023-12-11T16:00:00Z",

            "end": "2023-12-11T16:30:00Z",

            "minutesDuration": 30,

            "slot": {

                "id": "3230323331323131313630303A323032333132313131363330",

                "start": "2023-12-11T16:00:00Z",

                "end": "2023-12-11T16:30:00Z"

            },

            "created": "2023-08-02T00:00:00Z",

            "cancellable": true,

            "extension": {

                "ccLocation": {

                    "address": {}

                },

                "vistaStatus": [

                    "FUTURE"

                ],

                "preCheckinAllowed": true,

                "eCheckinAllowed": true

            }

        }

    ]

}

## Tasks
- [ ] [BE] **Implement VAOS Appointment Serializer**
- [ ] [BE] **Add rspecs to verify the implementation**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@kanchanasuriya @randomsync where are we with this one? If it is not finished, I will put it back in the backlog to finish later.
cc: @anita-halici
