### ISSUE TITLE
[BE] Implement Facilities API Payload Serializer

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#71790]
## Description
Implement facilities API payload serializer

fields needed in the FE:
type
name
classification
timezone
phone
physicalAddress

Sample Response from Facilities API
```
{
  "id" : "442",
  "facilitiesApiId" : "vha_442",
  "vistaSite" : "442",
  "vastParent" : "442",
  "type" : "va_health_facility",
  "name" : "Cheyenne VA Medical Center",
  "classification" : "VA Medical Center (VAMC)",
  "timezone" : {
    "timeZoneId" : "America/Denver"
  },
  "lat" : 41.148026,
  "long" : -104.786255,
  "website" : "https://www.va.gov/cheyenne-health-care/locations/cheyenne-va-medical-center/",
  "phone" : {
    "main" : "307-778-7550",
    "fax" : "307-778-7381",
    "pharmacy" : "866-420-6337",
    "afterHours" : "307-778-7550",
    "patientAdvocate" : "307-778-7550 x7573",
    "mentalHealthClinic" : "307-778-7349",
    "enrollmentCoordinator" : "307-778-7550 x7579"
  },
  "mailingAddress" : {
    "type" : "postal",
    "line" : [ null, null, null ]
  },
  "physicalAddress" : {
    "type" : "physical",
    "line" : [ "2360 East Pershing Boulevard", null, null ],
    "city" : "Cheyenne",
    "state" : "WY",
    "postalCode" : "82001-5356"
  },
  "mobile" : false,
  "healthService" : [ "Audiology", "Cardiology", "CaregiverSupport", "Covid19Vaccine", "DentalServices", "Dermatology", "EmergencyCare", "Gastroenterology", "Gynecology", "MentalHealthCare", "Nutrition", "Ophthalmology", "Optometry", "Orthopedics", "Podiatry", "PrimaryCare", "Urology", "WomensHealth" ],
  "operatingStatus" : {
    "code" : "NORMAL"
  },
  "visn" : "19"
}
```

## Tasks
- [ ] [BE] **Implement serializer for facilities API**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
