### ISSUE TITLE
[FE] 10-10EZR - Standalone Form: Medicare and Medicaid data is not passed to ES

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#71804]
## Background
During End-to-end testing with ES/Joshua Faulkner, it was found that the EZR submissions did not include the Medicaid and Medicare data that was input on the form.  Per Joshua Faulkner, the raw submission data did not include the Medicaid and/or Medicare input.

The Private Insurance passed through and was received by ES successfully.

## Tasks
- [x] Investigate the submission data between VA.gov EZR form and ES
- [x] Determine the root cause of the issue
- [x] Determine the solution
- [x] Implement solution, ensuring it is behind the EZR feature toggle for the MVP work
- [x] Comment on this ticket to outline the solution
- [x] Validate with [QA](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/72162) and PM once solution is in Staging environment for end-to-end testing

## Acceptance Criteria
- The EZR form can be submitted for End-to-end testing and the Medicaid & Medicare input is submitted to ES.

**Comment by hdjustice** [comment]
It has been confirmed that the Frontend is sending 'false' for the values, regardless of the selection from the user.  Chapley is working on this.

**Comment by longmd** [comment]
Root cause of this issue stems from data structure updates that were performed to meet accessibility conflict with the data structure of the prefill data. This was causing new values that were input into the form to not overwrite prefill values that were already in the form data with the same key name. 

The solution is simply to reformat the prefill data when it comes into the form to meet the structure created by the forms library.
