### ISSUE TITLE
Add PDF support for PDF unlocking and generating

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71811]
## Issue Description
_As discovered in #52022, users trying to upload a password-protected pdf for dependents (686, 674), pension (527), and burial (530) receive an error. We need to add PDF support to the models that are handling the PDF unlocking and generating. (`claim_documents_controller.rb` & `form_attachment.rb`)._

- The mentioned models handle the PDF unlocking behavior for our other forms (`21P-527EZ`, `21P-530`, `21-686C`, `686c-674`, & `26-1880`). 

- The the same internal error exists on the Pension form as well (`21P-527EZ`, screenshot), and that team has been notified.

![Screenshot from 2023-12-05 13-59-24](https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/ec4d7547-6c3c-4c9b-ad7c-e0e0000ce23f)
 ![Screenshot from 2023-12-05 13-56-56](https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/5ea84404-305b-4f78-a9be-f888bea07114)

---
## Tasks
- [ ] Add support for pdf unlocking and generating to 686 and 674
- [ ] Add support for pdf unlocking and generating to COE 26-1880
- [ ] Add support for pdf unlocking and generating to burial 530

## Acceptance Criteria
- [ ] A user can upload a password protected pdf to their COE, 686/674, and burial claims and the document is submitted successfully to downstream systems
---

**Comment by steele-lm** [comment]
Micah confirmed: Pensions did not fix this, but I have identified the problem.

I was running into user issues as I was getting a "no edipi" error.  The reason was due to a flipper feature being turned off. "profile_user_claims" feature flag must be turned on in the flipper/features page.  Coding looks fairly straightforward.  Looking at specs for test coverage.

It's likely that the fix can be applied to other ndbex forms so I expect it to be future proofed

**Comment by micahaspyr** [comment]
This error should be fixed in this [PR 15394](https://github.com/department-of-veterans-affairs/vets-api/pull/15394)
I added an unlock file private method to claim_documents_controller.rb.  All forms should be covered by this feature but as this PR was specific to the 52022 ticket, it should still be tested.  An add on for this ticket would be for tests to be written for the other forms (686, etc)

**Comment by micahaspyr** [comment]
@Midge-dev verified that this works on the Burials form

**Comment by micahaspyr** [comment]
All listed forms are now able to unlock a password protected pdf! 👍
