### ISSUE TITLE
Meet w/ PR team PM

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71829]
Primary:  Bryan

## Purpose
Joe Tice, PM of Platform Reliability, had a potential process that might be a good candidate for improvement via Service Design

Initial discussion [notes](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2870018085/Potential+work+evaluation+from+Platform+Reliability+team)

## Tasks
- [x] Meet w/ Joe to learn more
- [x] evaluate work for next steps
- [x] discuss with team

## Acceptance Criteria
- [x] Discussion notes captures
- [x] next steps documented
