### ISSUE TITLE
Red Dot Notification Refactor

### ISSUE THREAD

**Issue by jzucadi** [department-of-veterans-affairs/va.gov-team#71827]
## Description

The purpose of this ticket is to investigate the current usage of the dot notification and refactor it so that does not render as a Symbol(react.element). Work was completed [on a different ticket ](https://github.com/department-of-veterans-affairs/vets-website/pull/26970) which indicated that the current implementation of the notification is causing some bugs. There is a high probability that additional time and fixes will be required down the road unless the red dot notification is refactored.

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/27172

## Acceptance criteria

- The red dot notification does not render as a <span> that is a react.element symbol object. 

## Tasks

- [x] Investigate the current red dot notification implementation logic
- [x] Refactor dot notification to rely on plain javascript or make it as a web component
- [x] Confirm all existing tests related to the dot notification and pages pass
- [x] Confirm no accessibility concerns exist with the new implementation

## Notes

- An approach that relies on the ::before css property is preferable, something lightweight instead of a object
 for example: 

``````
.message.unread::before {
    content: '';
    position: absolute;
    width: 12px;
    height: 12px;
    background-color: red;
    border-radius: 50%;
}
```````

<img width="567" alt="Screenshot 2023-12-13 at 6 13 46 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/7745936/b72016d2-e463-42d5-870b-fc2f9aa2d87a">

<img width="1063" alt="Screenshot 2023-12-13 at 6 12 17 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/7745936/ecc41a15-c2b7-4d2b-8897-dd1cc3832c4b">
