### ISSUE TITLE
Update 'Get Access to Datadog' Documentation

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#71832]
## Description
There is new process for getting access to Datadog. The DOTS Team will no longer be responsible for this. As such, we'll need to update the documentation we have on this.

**Slack Thread with Annoucement:** https://dsva.slack.com/archives/C01G6J7UGGH/p1702475877557299

**Pages We'll Likely Need to Update:**
- [Get Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)
- [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog)

**Drafts Space: [Datadog Access - NEW PROCESS DRAFT](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2888106936/Draft+-+Updates+to+Datadog+Documentation)** 
## Potential New Process Instructions (Need to Confirm):
**Page 1: [Get Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)**
> **How to Submit a ServiceNow Ticket for DataDog Requests:**
> The steps below show how to submit new monitoring requests, or, updates to existing monitoring requests to the **ECC group**. This group is now responsible for **ALL** Datadog issues such as adding or modifying user roles Enterprise monitoring, dashboards, or alerts for an Application Service, or to add or remove services, network devices, or administering other equipment to/from monitoring tasks.
> 
> - Go to the ServiceNow Portal at [ECC (Enterprise Command Center) Monitoring Services - your IT Service Portal (va.gov)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyourit.va.gov%2Fva%3Fid%3Dsc_cat_item%26sys_id%3D4cdf488b1ba4fcd412979796bc4bcb74&data=05%7C01%7C%7Ccb701e4e7fc944b6041308dbeacea9aa%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638361945550254440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sJfq3j8vnXwdtuQrfY%2FBaRttaqyOpKA6X17O8TMK9ug%3D&reserved=0)
> 
> - Complete the HelpDesk form.
> 
> - Use the drop down to select the application option where available
> 
> - Follow the remaining steps as applicable
> 
> You can attach any supporting documents such as a list of servers using the “paperclip” in the lower right-hand corner of the form.
> 
> Someone on the Monitoring Design Team will contact you to discuss your requirements.
> 
> To check the status of your ticket/request, please go to https://yourit.va.gov/va and click on your name in the upper right corner of the screen.

## Tasks
- [x] Confirm [this is the correct page](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog) we'll be updating, 
- [x] Check for other mentions or areas of the PW where Datadog might need some updates as well.
- [x] Work with SME to validate that the new instructions lead to a successful account creation. Worked primarily with Chris Floess, Rebecca Tolmach (https://dsva.slack.com/archives/CL181NRJQ/p1702476752355709))
- [x] Received final review from Clint.
- [x] Work to update the existing documentation
- [ ] Prepare page for deployment

## Acceptance Criteria

- [x] New process has been validated by a SME 
- [ ] Page has been deployed and is live

**Comment by BSmolensky** [comment]
@johnny-jesensky-adhoc - I took a look at both of these pages. 
### Troubleshooting Access to Data Dog

- NO NOTES. LOOKS GREAT! 
 
### Get Access to Datadog

- Overall looks great! I only have one note...
- **Be Consistent**: Make sure that you are referring to `DOTS-VA Okta` the same way every time. Sometimes the `-VA` is present and sometimes it is not. I would recommend that the `-VA` be present all the time. 
- Other than that, this one looks good too.

**Comment by johnny-jesensky-adhoc** [comment]
Page was updated and included as part of the _**Wednesday, January 10th**_ deployment. Marking this as completed.

FYI @jknipes
