### ISSUE TITLE
Epic | Profile | Migrate to Figma

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71836]
## Background
Sketch is being sunset and we need to migrate our sketch files to Figma. 

Once we've got Figma files, we'll need to refresh our documentation to point to Figma instead of Sketch.

## Tasks 

```[tasklist]
### Move Sketch Files
- [ ] #71216
- [ ] #71214
- [ ] #71234
- [ ] #71238
- [ ] #71231
- [ ] #71236
- [ ] #71237
- [ ] #71230
- [ ] #71232
- [ ] #71235
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72331
- [ ] #71239
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72570
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72670
- [ ] #72127
- [ ] #71233
```

```[tasklist]
### Update Our Documentation to point to the new Figma Files
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75434
```
```[tasklist]
### bug fixes once design system is fixed
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72085
```

## Acceptance criteria 
- [ ] all of the profile sketch files that we've determined necessary to migrate are available in Figma, the remaining files are archived (design to determine best centralized place to archive those)
