### ISSUE TITLE
Provider Based Scheduling Project Brief 

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#71845]
## Task Description
Create a comprehensive project initiative brief proposal based on the research recommendations from the provider-based scheduling research. 

## Notes and References
- Based the brief on the recommendations from the[ PBS research report](https://app.enjoyhq.com/sh/pj/aa5a9c69-6701-4d58-8f43-60adb21ce29d)
- Create a google doc as a draft 
- Once we are ready for it to be reviewed, [move it to GH here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/initiatives/provider-based-scheduling)

## Acceptance Criteria
- [ ] 

## Deliverables
- 

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by outerpress** [comment]
Duplicate
