### ISSUE TITLE
[Content] Create Content for updating 45MR text to include end time of check in window

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71852]
## Description 

There are a lot of attempts to check in after the check in window. I.e., Veterans are selecting the check in link in their text after the check in window has passed.

How can we reduce this pain point of Veterans attempting to check in, and having a bad experience. E.g., their path is verifying their ID, and then getting to the general error page. "We couldn't check you in. We're sorry. Something went wrong on our end. Check in with a staff member."

How might we update the 45MR text to include mention of the end of check in window. E.g., whether we say, "there's 45 mins to check in" or "you can check in until 00:00."
 
## Tasks
- [ ] Update the [45MR text](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/5nDVrdd) to include mention of the end of the check in window

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets
