### ISSUE TITLE
[FE] Dot indicator: confirm sent "unreads" are not included in dot indicator logic

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#71864]
## Background
The secure messaging team flagged an issue where "sent" messages might be counting toward unread messages due to legacy functionality where sent messages are counted as unread for the veteran when the provider (i.e. the recipient of the veteran's message) hasn't opened it. We need to review our logic and make sure sent messages are not being considered as unreads for dot indicator logic.

**Slack thread resources:**
* [MHV slack thread flagging sent messages being included in unreads](https://dsva.slack.com/archives/C03ECSBGSKX/p1702410919841979)
* [BE discussion](https://dsva.slack.com/archives/C05TU9FPZU0/p1702417734323489)

**Notes to dev:**
* [v1 health docs](https://dev-api.va.gov///my_health/apidocs)
* [EKS endpoint testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/eks-endpoint-testing)
* [MHV landing page ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/71809)
* [MHV landing page PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27344)

## Tasks
- [x] Review slack threads posted above
- [ ] If you need BE assistance loop in Daniel and/or Tom and reach out to Oleksii/Alex Morgun (SM team) for assistance
- [x] Determine whether we're including sent messages in our dot indicator logic
- [x] If we are, work with PM to create subsequent ticket(s) to update logic to not include sents

## Acceptance Criteria
- [x] We know whether sent messages are being factored into dot indicator logic for unread messages
- [x] (If necessary) subsequent ticket(s) are created to update logic

**Comment by allisonlu** [comment]
keeping estimate for sprint 28 to **3**

**Comment by ajakabcin** [comment]
Closing this - great work @allisonlu 

work to update the logic to remove sents as unreads is tracked in #74388
