### ISSUE TITLE
TOU Content Updates #6

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#71869]
## Description
CAIA + Sitewide Content requested changes. The Figma and tasks list should be the finalized TOU.

## Prototype
[Figma](https://www.figma.com/file/nxW1NHF0q1EasvUGp1eh5a/Terms-of-Use---Final?type=design&node-id=0%3A1&mode=design&t=P2rMfTLawkfTCJan-1)

## Tasks
- [ ] Terms of use page (`/terms-of-use`)
  - [ ] Add Sign in to VA.gov (action link component) below intro-text
      - [ ] Unauthenticeted (visible)
      - [ ] Authenticated + middle auth (hide)
  - [ ] Conditionalize intro-text
      - [ ] Unauthenticated (see figma)
      - [ ] Authenticated + middle auth (see figma)
  - [ ] Conditionalize header CSS
      - [ ] Unauthenticated + Authenticated (show header)
      - [ ] Middle auth (hide header)
  - [ ] Update the `Getting VA benefits` header (see figma)
  - [ ] Update content for phone number (see figma)
- [ ] Terms of use Declined page (`/terms-of-use/declined`)
  - [ ] Update the phone number component
  - [ ] Add Review the terms of use (va-link) should go to `/terms-of-use` page
