### ISSUE TITLE
[FE] Perform Accessibility Testing & Create Artifact

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#71867]
## Description
As a team, we need to perform accessibility testing so that we can ensure our feature is ready for release.  

## Tasks
- [x] Create an accessibility ticket/artifact using this [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [x] Add the HCE-Checkin label to the accessibility ticket
- [x] Associate the accessibility ticket with the appropriate feature Epic
- [ ] ~~Attach the accessibility ticket to the collab cycle ticket for the feature Epic~~
- [x] Complete & check-off each test in the ticket

**Comment by brianseek** [comment]
@loripusey I started to do this but I notice that the form says this at the top: "Complete required accessibility testing prior to your Staging review." Are we doing staging review for the review page? If not maybe we shouldn't do this.

**Comment by loripusey** [comment]
We did not do the entire collab cycle process for this but did get input from CAIA for the new page. I think it's ok to do the testing, but when you create a ticket, remove the a11y label from it and close it when you are done. That way we have the documentation that we did the testing but, because there will be no staging review, we won't confuse folks.

**Comment by brianseek** [comment]
ok sounds good

**Comment by brianseek** [comment]
Here is the closed ticket artifact: https://github.com/department-of-veterans-affairs/va.gov-team/issues/72689

This is ready for validation @loripusey

**Comment by loripusey** [comment]
Looks good, closing.
