### ISSUE TITLE
Tech debt - Fix Identity code

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#71878]
## Description 
Update Identity code for minor tech debt items

## Tasks
- [x] Fix the duplicate exports in the `LoginContainer` component and refactor if possible
- [x] Remove `TOKEN_KEYS` from `oauth/constants`
- [x] Change `SIS_API_VERSION` to be non-exported `oauth/constants`
- [x] Change `VAMockProvider` to be non-exported `auth/config/constants`
