### ISSUE TITLE
[AUTOMATION] Load System Health Services data [Engineer]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7188]
## User Story or Problem Statement
As a Data Tech, I need an optimized way to set content into existing content fields from a .csv or .txt file, so I can reduce time in loading and completing page content in VAMC- Web page/nodes.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase pages/nodes completed in a quarter_

## Resources - Tools - Documentation
[Review System and facility spreadsheet](https://dvagov.sharepoint.com/:f:/s/VHADigitalMedia/vamc-upgrade-project/Ej33rnb0EAZDkvT2A-696qUBx40SHv8dOusH-nP810orTg?e=3JLBLQ)

## Tasks
_Creation of the following Drupal System Level Health Services_
- [x] Create System Health Services using .csv/script (required unique ID)
- [x] Create script and submit Push Request for testing in Devshop
- [ ] After review/validation - Make changes for new Push Request until final approval 
- [ ] Document correct script format and all errors for future PR and troubleshooting.
- [ ] Deploy script into prod.cms.va.go instance
- [ ] Document any errors.
- [ ] Rebuild Devshop Instance
- [ ] Publish Devshop to see if instances appear in Working System Health Service pages.
- [ ] Record any formatting changes in Devshop for use in next script push.  

## Acceptance Criteria
_Validate outcome of pushing content to existing nodes_
* Create System Health Services using .csv/script (required unique ID)
* Create script and submit Push Request for testing in Devshop
* After review/validation - Make changes for new Push Request until final approval 
* Document correct script format and all errors for future PR and troubleshooting.
* Deploy script into prod.cms.va.go instance
* Document any errors.
* Rebuild Devshop Instance
* Publish Devshop to see if instances appear in Working System Health Service pages.

**Comment by SgardnerPMP** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1776/files?file-filters%5B%5D=.csv

**Comment by SgardnerPMP** [comment]
Continued work into Sprint 23, Final testing in PR1776 underway, entity lookup is final hurdle and testing of larger .csv file.
