### ISSUE TITLE
[MVP] Audit for redundant/old pages no longer part of the form flow

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71893]
## Issue Description
As a Pension team,
**we need to identify which pages are no longer relevant to the form relaunch,**
so that we can archive them.

---
## Tasks
- [x] Audit of pages in Google document: https://docs.google.com/document/d/1QiikP2lQGQqIE_9aqtUdnDeic4BSsSzqLSz4I7ouhUA/edit?usp=sharing
- [x] Engineering perform QA of Step 4
- [x] Request audit of Step 5 pages from engineer; screenshots?
- [x] Review results designer and engineering team

**Step 5 pages that will probably need to be archived/removed from form flow:**

[Link to screenshots](https://docs.google.com/document/d/11VWC8Y8fEu2eImtb9cH73IRmoMzZbpuQuOt9EphugfM/edit?usp=sharing) for these pages.

1. Financial information: financial/net-worth
2. Monthly income: financial/monthly-income 
3. Expected income: financial/expected-income 
4. Other expenses: financial/other-expenses 
5. Spouse net worth: financial/net-worth/spouse
6. Spouse monthly income: financial/monthly-income/spouse
7. Spouse expected income: financial/expected-income/spouse
8. Spouse other income: financial/other-expenses/spouse 
9. Dependents net worth: financial/net-worth/dependents/:index
10. Dependents monthly income: financial/monthly-income/dependents/:index 
11. Dependents expected income: financial/expected-income/dependents/:index 
12. Dependents other income: financial/other-expenses/dependents/:index 

## Artifacts
- Findings from QA of Step 4: https://docs.google.com/document/d/1iCQvC81K-TAfhSZYodovlwC4GM_VTfvEa5rtPnSleaU/edit?usp=sharing
- Proposed Step 4 modifications in MURAL board: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=29-1703173367057
- Follow on tasks form this audit:
-- [MVP] Step 5: Remove redundant/old pages from form flow #72332
-- [MVP] Step 5: Update form flow page order#72330
-- [MVP] Step 4: Revisions to page flow, order and questions#72455
