### ISSUE TITLE
[AUTOMATION] Creation of new .csv file to upload VISN-6 System and Facility Health Services to CMS [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7189]
## User Story or Problem Statement
As a Data Tech, I need an optimized way to load .csv of System and facility health services, so I can load existing list to system and facility pages for inspection and confirmation of PAO web maintainers.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase pages/nodes completed in a quarter_

## Resources - Tools - Documentation
[Review System and facility spreadsheet](https://dvagov.sharepoint.com/:f:/s/VHADigitalMedia/vamc-upgrade-project/Ej33rnb0EAZDkvT2A-696qUBx40SHv8dOusH-nP810orTg?e=3JLBLQ)

## Tasks
_Creation of the following .csv files
- [ ] System Health services unique to the each System in VISN-6
- [ ] Listing of Facility Health services unique to each Facility

## Acceptance Criteria
_Validate outcome of pushing content to existing page_
- [ ] System will have unique id equal to system + Health service name
- [ ] Facility health service will have unique ID equal to facility ID + Health service title
- [ ] Each facility HS will have combined health service "at" Facility name
- [ ] System is tested and loaded into CMS successfully
- [ ] Facility is tested and loaded into CMS successfully
