### ISSUE TITLE
Sprint 18: Logged-in homepage discovery

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7190]
### Order of priorities

1. Finalize research plan
2. Plan/maybe conduct stakeholder interviews

### Logged-in homepage discovery

- [x] Review and refine research proposal #7083
- [x] Review and refine list of stakeholders #7086
- [x] Create conversation guide #7087
- [x] Schedule interviews #7088
- [x] Conduct interviews #7089
