### ISSUE TITLE
SPIKE | Explore Frontend of Burial Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#71905]
## Issue Description
_In order to prepare for updating the Burial 530EZ form, we need to understand the frontend components and structure._

---
## Tasks
- [ ] Explore structure of form
- [ ] Explore schema of form
- [ ] Review [Sketch file](https://sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7) of updates

## Acceptance Criteria
- [ ] Adequate discovery completed to start work on #71045 and subsequent tickets
---
