### ISSUE TITLE
Add, "Using review instances to preview changes" to Staging Review operational guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#71904]
## User Story
As a Governance team member, I want to ensure I have all the resources/guidance necessary so that I can complete a Staging Review.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
The [Staging Environment Guidance ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2377875498/Staging+Environment+Guidance) currently includes guidance on review instances, but it does not include a reference to the Using review instances to preview changes page linked below.

The purpose of this ticket is to ensure that the Governance team documentation is updates appropriately and that Governance team members are aware of it's existence. 

## Impacted Artifacts

[Using review instances to preview changes](https://vfs.atlassian.net/wiki/spaces/pilot/pages/590774288/Using+review+instances+to+preview+changes)

## Tasks
- [x] Update the Staging Environment Guidance, where appropriate, to include reference to the review instances guidance

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team is able to easily access the "using review instances to preview changes" if/when a SR includes review instances.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@briandeconinck I added this link to [Staging Environment Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2377875498/Staging+Environment+Guidance) under review instances. Ready for your review

**Comment by briandeconinck** [comment]
This looks good @allison0034. I fixed an unrelated broken link I noticed while reviewing. I think you're good to close this out!
