### ISSUE TITLE
[AUTOMATION] Create package to combine creation of System, Association to Facilities, and creation of nodes in one activity [Engineer]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7191]
## User Story or Problem Statement
As a Data Tech, I need an optimized way to set content into existing content fields from a .csv or .txt file, so I can reduce time in loading and completing page content in VAMC- Web page/nodes.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase pages/nodes completed in a quarter_

## Resources - Tools - Documentation
[Review System and facility spreadsheet](https://dvagov.sharepoint.com/:f:/s/VHADigitalMedia/vamc-upgrade-project/Ej33rnb0EAZDkvT2A-696qUBx40SHv8dOusH-nP810orTg?e=3JLBLQ)

## Tasks
_Creation of the following Drupal types/menus and pages_
- [ ] Create System from .csv/script (required unique ID)
- [ ] Create Sections/(VISN/System/Menu) based on Systems (Taxonomy & Permissions)
- [ ] Associate/connect facilities to System (By Facility Numbers)
- [ ] Creation of multiple nodes (Use clone of node or .csv file)

## Acceptance Criteria
_Validate outcome of pushing content to existing page_
* Create System from .csv/script
* Create Sections/(VISN/System/Menu) based on Systems
* Associate/connect facilities to System
* Creation of multiple nodes (Use clone of node or .csv file)
