### ISSUE TITLE
AE - Sprint 18

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7193]
### Order of priorities
Any overflow from last sprint, plus:

1. Profile 2.0: Build starts
2. Profile 2.0: Finish conversation guide; Kickoff research; Conduct research
3. Address validation post-launch tickets (only the ones already listed)
4. My VA — MHV/Cerner split
5. PM work
6. Monitoring, maintenance, bug fixes, hardening, 508, etc

### Address validation
- [x] Ramp up to 50% #6426
- [x]  Ramp up to 100%  #6426
- [ ] Remove address validation feature flag #7405

### Profile 2.0
**Design**
- [x] Get build tickets ready ***
- [x] Profile 2.0 Screen Copy - Account Security - #6246
- [x] [Design] COVID-19 My VA alert: Mock up alert for the dashboard #6976
- [x] Design] Tressa to make "Connected Accounts" design/copy changes #6676
- [x] Create conversation guide #2586
- [x] Matt/Tressa to prepare use cases for Pre-Usability Testing (regression test) #6628
- [x] Kickoff recruiting for Profile 2.0 Research #6325
- [x]  Start conducting sessions #2587

**Dev** (will revisit once mocks/reqs are in these tickets)
- [x] [FE] Profile 2.0: Build the profile header #5350
- [ ] [FE] Profile 2.0: Build the "Military Information" section #5354
- [ ] [FE] Profile 2.0: Build the "Direct Deposit" section #5355
- [ ] [FE] Build Side Nav Component #7256
- [x] [FE] Create new profile app #7255 (erik)

### PM work
- [x] Figure out what design needs to accompany (#6466- HCA) and get design tickets created and added to the backlog.
- [ ] Profile 2.0 epic grooming/What comes next with profile 2.0? #7222
- [x] Work with Erik to create a ticket for the Find VA Benefits work coming out of [#5865] 

### Backend
Lihan to be working on BAM2 team this sprint (per Paul Short and Leah Keeler)

### Monitoring, maintenance, bug fixes, hardening, 508, etc.
- [x] [FE] Implement extended "Save" state on the modal #6981 
- [ ] Make Find VA Benefits work with JAWS+IE11 #7324
- [x] Add criteria to patientFacility selector #7433 (Brad)

-------Unplanned work--------

- [x] Profile 2.0 should front-load all required data #7699
- [ ] Make reusable Profile 2.0 info table component #7554
- [x] Wire header to reduce data #7651

### My VA — MHV/Cerner split

- [x] [FE] My VA: Health care update to "Schedule an appointment" related to MHV/Cerner split #7286

**Comment by Samara-Strauss** [comment]
You can take out anything for the logged-in homepage discovery. That's already [documented here](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7190).

**Comment by mshea0606** [comment]
@Samara-Strauss Ok thanks!
