### ISSUE TITLE
[BE] My VA TMA: Familiarization with Datadog etc

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#71930]
## Background
This ticket is track Daniel's work around Datadog onboarding/familiarization. As part of this ticket he'll be reviewing existing dashboards/widgets that Derrick made before rolling off the team, reviewing maintenance window alerts, and general Datadog functionality. He should work with Tom on this for guidance and support as needed.

## Tasks
- [ ] Get Datadog access set up (if not already there)
- [x] Work with Tom to get a deep dive into Datadog
- [x] Review existing dashboards for My VA created by Derrick before he rolled off the team and work with Tom to identify where work is still needed on them
- [ ] Look into maintenance window alerts to see how we can improve telemetry around these
- [ ] Work with Tom and AJ to create additional tickets as needed for improvements

## Acceptance Criteria
- [ ] Daniel has a basic understanding of Datadog and feels comfortable working with the existing My VA dashboards in Datadog

**Comment by DanielMiller-agile6** [comment]
Got started on reading some docs and finding instructions for access, but otherwise this ticket will carry over.  I didn't get as much time to work on this during the past sprint as i hoped, so probably leave this as a 5... maybe drop to 4 since some of the reading is out of the way.

**Comment by DanielMiller-agile6** [comment]
dropping to 3 for next sprint.  feel more familiar, but still have issues with local vets-api development environment i need to sort out before I feel comfortable working on datadog tasks.  I also still need to get access, but my PIV pin wasn't working, or I forgot it, so i need to get that sorted out as well :(

**Comment by DanielMiller-agile6** [comment]
dropping to one point in case we want to discuss any additional work coming out of this ticket
