### ISSUE TITLE
Add feedback portal link to Collab Cycle feedback ticket templates

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#71945]
## User Story
As a Platform team member, I want to ensure that VFS teams have easy access to the feedback portal so they're more likely to provide feedback.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
In order to help increase engagement in the [Feedback portal](https://dj540s05.optimalworkshop.com/questions/30da98e492625eb82c077b4b2a6d800c), Governance has been asked to include a link to it within the Collaboration Cycle guidance and documentation. Since the Collaboration Cycle feedback tickets for Design Intent and Midpoint Review and the findings tickets for Staging Review are all shared post-touchpoint, when the VFS team has completed a small portion of the Collaboration Cycle, we thought it would make the most sense to include the feedback portal link there. 

The purpose of this ticket is draft content in gh markdown language that can be included at the bottom of the ticket templates. Ideally, the same content will be included in all 3 ticket templates.

**Note**: in this ticket, we'll only update the Collab Cycle feedback template and the QA template for SR. Since the VA.gov Experience Standards ticket is currently generated in the DraftingTemplate, and that tool is being updated via the VA.gov Experience Standards initiative, we'll hold off on adding the feedback portal content to the in-use DraftingTemplate. One of the tasks within this ticket will be to share the feedback portal content with Shira so the content can be added to the new DraftingTemplate.

~~Another idea: can we customize the link to the feedback portal so that we can capture where the VFS team accessed the link from? For example, this link came from the DI/MPR feedback ticket where this other link came from the SR feedback ticket or QA feedback ticket. Need to connect with Service Design on this.~~ 12/20 note: will include as-is link for now but will propose this change to Service Design for future consideration.

## Impacted Artifacts
[Collab Cycle feedback ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-feedback.md)
[Collab Cycle QA findings ticket for Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collab-cycle-qa-findings-staging.md)

## Tasks
- [x] Reach out to Service Design team on #platform-service-design channel and inform them of this ticket. Ask if they have preferred language for adding the feedback portal to github templates. If not, no worries - we'll draft it ourselves. If so, then use it!
- [ ] Create pull requests for the Collab Cycle feedback template and add or draft the content there. (work on 1 at a time so you don't have to change 2 issue templates simultaneously)
   - suggestion from SG: maybe have a line break (---) and then the content so we can just add this to the as-is templates, instead of having to rework the existing content.
- [ ] Submit for peer review
- [ ] Once in agreement, merge changes.
- [ ] Make same changes to QA template - no need to create a PR - you can merge directly to main
- [ ] Share content with Shira so she can add to the new DraftingTemplate

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All new Collab Cycle feedback tickets and QA standards tickets include links to the Feedback portal

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@tayism FYI - let me know if you'd like to connect on this!

**Comment by erinrwhite** [comment]
Heard back from Service Design who gently reminded me this is a Slack workflow now! There is a [help page on the Platform website](https://depo-platform-documentation.scrollhelp.site/support/give-feedback-about-platform-products-or-services) we can link to as well. In progress.

**Comment by steel36** [comment]
@shiragoodman My concern would be that, due to the embedded positioning, the user is likely to assume it's a communication mechanism for your team, which might confuse things for both parties.  

Particularly since there isn't a Governance team channel that folks can reach out to you in, they may think/hope that the included link would be a way to contact you; but it isn't.

**Comment by shiragoodman** [comment]
Thanks @steel36 . I think that's a fair concern.

At this time, we'll hold off on making any changes that incorporate the feedback portal into our Collab Cycle messaging. However if you'd like our team to nudge VFS teams in any way, please let us know Bryan!

@erinrwhite this ticket can be closed/cancelled. LMK if you want to discuss.

**Comment by steel36** [comment]
Thank you.  Now that we have a more robust mechanism for collection, we certainly intend to fan the flame more.
