### ISSUE TITLE
Test Feedback Portal slash command

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#71944]
## Purpose
There is still uncertainty as to how a user gains access to created workflows.  let's test it

## Tasks
- Test access to the workflow by having non-SDT users attempt to access the intended workflow:
   - [x] contact a test subject
   - [x] have the user type "/platform feedback" 
   - [x] Confirm that they able to see and access the workflow?
   - [x] document
   - [x] Repeat for 2-3 users

## Acceptance Criteria
- [x] Document [test results](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2875392272/Testing+of+Slash+Command+launch+of+Feedback+Portal)
