### ISSUE TITLE
BE | Profile | Unplanned/Misc Tasks

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#71967]
## Background
This ticket tracks unplanned work during the sprint.

## Tasks
- [x] Code Yellow Initiative Work
  - [x] Met with Steve Albers to discuss monitoring (1 hr)
  - [x] Reviewing/updating incidents related to monitor alerts (4 hrs)
- [x] Met with Veteran Status team to discuss rules for veteran status (1 hr)
- [x] The Ask VA Team (AVA) requested assistance in identifying 11 fields in VA Profile (? hrs)
- [x] Update military service history doc with `serviceComponent` references.
- [x] #72341
- [x] #72342
- [x] Remove [my_va_lighthouse_claims feature toggle](https://github.com/department-of-veterans-affairs/vets-api/pull/14849#issuecomment-1863603907) (waiting to hear back to remove from prod)
- [x] Remove [my_va_show_header_link feature toggle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68531#issuecomment-1858231134)

**Comment by mtcA6** [comment]
@tpharrison is this ok to close out?

**Comment by tpharrison** [comment]
I still need to add an alert for the MHV team.  I'll add it today, then close this out.
