### ISSUE TITLE
IPP - Make Research Recommendations from Usability Tests with Veterans

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#71965]
As a VA OCTO researcher, I should be able to understanding the findings and justifications for recommendations from the IPP usability test for Veterans so that I can learn from the findings. 
## Tasks

- [x] Identify soft suggestions for how might we statements that emerged from UT for changes to product
- [x] Review soft suggestions with product lead to confirm what is in scope for pilot versus for MVP
- [x] Identify higher level recommendations for VA from findings
- [x] Identify screen reader specific friendly recs
- [x] Recommendations are clearly laid out in [research report (https://docs.google.com/document/d/1Nt5HbMd9JkA0JENMVRyzgw3XPTNCb6KsJ2mcj6OlEWg/edit)
- [x] Move final HMW and recommendations into this [document](https://docs.google.com/document/d/1Q-OHK4LuYSTNuuegMTDlPgsLGw6vKAanbszMqoc6Eqc/edit)
