### ISSUE TITLE
[DA] 10-10EZR - Standalone form: Data Monitoring - Set up Datadog RUM

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#71973]
## Background
As we prepare to launch the 10-10EZR form, we want to set up the RUM capability (Real User Monitoring) in Datadog.  It will allow us to see the interactions and movements of a user, real-time view of what is happening as the user moves through the site pages.

#### Resources
- Link to [Datadog RUM page](https://docs.datadoghq.com/real_user_monitoring/)
- Link to [Datadog RUM Setup instructions](https://docs.datadoghq.com/real_user_monitoring/browser/)
- [Link to 10-10EZ RUM Dashboard](https://vagov.ddog-gov.com/rum/performance-monitoring?query=%40session.type%3Auser%20%40application.id%3A9d5155fd-8623-4bc9-8580-ad8ec2cdd7fa&tab=overview&from_ts=1702484424513&to_ts=1702570824513&live=true)

## Tasks
- [ ] Set up monitoring for the 10-10EZR Form
- [ ] Set recording session sampling to 100% initially, during our first phase of the launch (10% of logged-in users will be able to access the form)
- [ ] Confirm privacy level is masking as expected, so that no PII is revealed or logged in Datadog monitoring

## Acceptance Criteria
- Real User Monitoring dashboard setup for the 10-10EZR

**Comment by luis-simauchi** [comment]
JS CODE TO DROP ONTO SITE BELOW

import { datadogRum } from '@datadog/browser-rum';

datadogRum.init({
    applicationId: 'd6b6178d-eef9-4252-baae-896432d38d45',
    clientToken: 'pub8ee92ee6af5b712950a32c81d2ee4351',
    site: 'ddog-gov.com',
    service: '10-10ezr',
    env: '<ENV_NAME>',
    // Specify a version number to identify the deployed version of your application in Datadog 
    // version: '1.0.0', 
    sessionSampleRate: 100,
    sessionReplaySampleRate: 100,
    trackUserInteractions: true,
    trackResources: true,
    trackLongTasks: true,
    defaultPrivacyLevel: 'mask-user-input',
});
