### ISSUE TITLE
[DA] 10-10CG - Data Monitoring - Set up Datadog RUM

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#71975]
## Background
We want to set up the RUM capability (Real User Monitoring) in Datadog for the 10-10CG form.  It will allow us to see the interactions and movements of a user, real-time view of what is happening as the user moves through the site pages.

#### Resources
- Link to [Datadog RUM page](https://docs.datadoghq.com/real_user_monitoring/)
- Link to [Datadog RUM Setup instructions](https://docs.datadoghq.com/real_user_monitoring/browser/)
- Link to [10-10EZ RUM Dashboard](https://vagov.ddog-gov.com/rum/performance-monitoring?query=%40session.type%3Auser%20%40application.id%3A9d5155fd-8623-4bc9-8580-ad8ec2cdd7fa&tab=overview&from_ts=1702484424513&to_ts=1702570824513&live=true)

## Tasks
- [x] Set up monitoring for the 10-10CG application
- [x] Set recording session sampling to 1% initially
- [x] Confirm privacy level is masking as expected, so that no PII is revealed or logged in Datadog monitoring

## Acceptance Criteria
- Real User Monitoring dashboard setup for the 10-10CG

**Comment by jadon1979** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/27870
