### ISSUE TITLE
Left Nav:  Section open state

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7198]
## User Story or Problem Statement
As a veteran, I need to know which elements in the navigation menu are clickable so I can more easily understand which page I am on. 

## Goal
Use neutral tone for the text and highlight colors in the "You are there/section open" state to avoid confusing users, per feedback on [#7196](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7196)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/1c04dcd3-bf43-4458-a97c-6f82b5eccfd3)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/ddca3d44-48c8-487b-bd2a-6bba30f24c25)

## Objectives or Key Results this is meant to further
OBJECTIVE 3: Deliver a usable and accessible experience

---
## Tasks
- [ ] Develop "you are there/section open" state consistent with Ryan's design (shown above) and in [Zeplin] (https://zpl.io/2jxORgp).
- [ ] Change the text color from blue to neutral (black) for open state
- [ ] Change the background color of a clicked nav item to light gray.  
- [ ] Change a clicked nav bar item's highlight color to neutral (black) 
- [ ] Ensure that clicking a nav bar item takes user to the page clicked 
- [ ] Ensure that clicking a nav bar item reveals all of its children and grandchildren
- [ ] Ensure that nesting pages have vertical line
- [ ] Ensure that content block has horizontal line at the top and bottom. 
- [ ] Include an indicator of current page for screen readers (aria-current="page" on the current page)
- [ ] Turn off pointer-events and default the cursor on the aria-current="page" breadcrumb
- [ ]  Use good accordion ARIA markup for the mobile "On this section" button. This includes aria-expanded="true | false" and ideally an aria-controls="UNIQUE_ID" that points to the navigation container. aria-controls only works for JAWS, but it's worth adding as a progressive enhancement.

## Acceptance Criteria
- [ ] When a user clicks an item from the left nav, the text changes to neutral (black) color.
- [ ] When a user clicks an item from the left nav, the vertical bar highlight turns to neutral (black) color.
- [ ] When a user clicks a nav item, the item's background changes to light grey. 
- [ ] When a user clicks an item from the left nav, the user is taken to that page
- [ ] When a user clicks an item from the left nav, all children and grandchildren of that page are revealed.
- [ ] When sub-pages are revealed, nesting pages have vertical line. 
- [ ] When a user clicks an item from the left nav, the content is bordered by horizontal line at the top and bottom. 
- [ ] When a screenreader user clicks an items from the left nav, there is an indicator of the current page. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate
