### ISSUE TITLE
Style Guide Update: Add Guidance on Social Media Links

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#71989]
## Description
As part of a recent page deployment, the Platform Content Team discussed the need for having guidance on how to handle using/linking social media links on our style guide.

[Slack Thread](https://adhoc.slack.com/archives/C02LYB7QXS5/p1702487142075729)

## Draft Text
Back of the napkin draft, as drafted by Brian.

> "We discourage linking out to social media sites as users on government computers often don't have access to those sites. If links to social media sites are vital to your content, please ensure that the pages you are linking to are viewable by everyone, even those who do not have social media accounts."

## Tasks
- [x] Review as a team the guidance and requirements on using social media links on the Platform Website.
- [x] Find best location in style guide
- [x] Update style guide with guidance

## Acceptance Criteria

- [x] Team has agree upon guidance on referencing, or directly linking out social media links.
- [x] Pages have been updated on the Style Guide
- [x] Style Guide has been updated

**Comment by johnny-jesensky-adhoc** [comment]
Style Guide has been updated, and reflected on [this Confluence page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1806172307/Images+videos+and+other+media).

**Location**
- _Style Guide --> Images, videos, and other media --> Social Media_

Moving this to _Done_.
