### ISSUE TITLE
[FE] - Update frontend to use real VAOS data

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#71995]
## Summary

Backend is going to create a serializer to sanitize the VAOS data. This ticket is to update our display to use the new data structure.

## Tasks
- [ ] [FE] review new data structure
- [ ] [FE] update FE to use new 
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@wullaski This looks good to me. I don't mind the processing being in the reducer either. One thing that I would ask Gaurav about is if you can get the stationNo. I have a feeling that we have it since they need it to hit the facilitiesAPI. THen we can treat the ID as the IEN and append the station still for going to the details page. Maybe the ID and IEN will match up. ¯\_(ツ)_/¯

**Comment by brianseek** [comment]
@wullaski you can go ahead and close this one when you are ready since there is no further validation needed
