### ISSUE TITLE
[BE] Sanitize identifier from VAOS appointments payload

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#71999]
## Description
Remove https://va.gov from the system value for the identifier objects being returned to the frontend.

example desired output:

```
            "identifier": [

                {

                    "system": "Appointment/",

                    "value": "413938333130383735"

                },

                {

                    "system": Terminology/VistADefinedTerms/409_84,

                    "value": "983:10875"

                }

            ],
```

## Tasks
- [ ] [BE] **Sanitize Identifier value**
- [ ] [BE] **Add rspecs to verify the implementation**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
