### ISSUE TITLE
Migrate designs and prototypes from Sketch to Figma

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#72006]
## Background
We now have Figma!  We like Figma!  

This ticket is to migrate our existing designs and prototypes on Sketch over to Figma

## Tasks
- [x] Migrate Find designs and prototype
- [x] Migrate Appoint + Widget auth designs and prototypes
- [x] Migrate Appoint + Widget unauth designs and prototypes

**Comment by mtri** [comment]
Find a representative is in Figma.
