### ISSUE TITLE
Content edits for #71990

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#72001]
## Description
This ticket is to make the updates requested based on [this Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71990).

## Details
> - Add more information about why outbound requests should (must?) be routed via the fwdproxy
> - Add a basic explanation of the network architecture, linking out to more detailed resources
> - Improve the configuration link in the AddinganewExternalServiceIntegration-ForwardProxy section to be to where the configuration is added

## SME:
**Kyle Matheny**

## Tasks

- [x] Review Github ticket
- [x] Determine SMEs who can help write the content (perhaps go to one of the engineering CoPs
- [x] Assign SME to write content
- [ ] Review the content
- [ ] Get Adrian Rollett (individual who submitted the ticket) to review changes
- [ ] Prepare page for deployment

## Acceptance Criteria:

- [x] SMEs have been identified who can help write content
- [ ] Page has been deployed with changes

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/72001?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by CherylEvans** [comment]
@acrollet 
 Good morning, Adrian! I realize you’re not in until Monday, but I want to take a moment and introduce myself. I am new to the Platform Content team and am working on ticket [72001](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/72001) (Content edits for ticket 71990).

- I reviewed the ticket and made a [draft copy](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3080683521/DRAFT+-+71990+-+Cheryl+-Copy+of+Adding+a+new+External+Service+Integration) of the [source page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1884586162/Adding+a+new+External+Service+Integration), which I will use to update the source page before publishing it on the PW.

- My next step is to work with you to determine the SME who will help write the updated content and coordinate our efforts.

- Once the assigned SME writes the updated content, you and I will review it to ensure it meets your content, style, and tone expectations.

- Once reviewed, I’ll move the changes from the draft page to the source page. 

- The [Platform Website page](https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration) will update when Platform Content runs our daily deployment.

Please let me know what time works best to discuss the way ahead or reply in the thread, and we can go from there. Thank you!!
FYSA 
@jknipes 
@johnny-jesensky-adhoc

**Comment by acrollet** [comment]
Hi @CherylEvans ! I would reach out to the Platform devops team for support on this issue. thanks!

**Comment by CherylEvans** [comment]
I contacted Peter Hill, who took the reins, to discuss this at their planning meeting and determine which SME is taking on the effort.

**Comment by jknipes** [comment]
unable to complete due to being blocked by SME, moving to Backlog

**Comment by jknipes** [comment]
Automation added sprint date to this ticket. We have removed the date until we are certain ticket can be worked on.

**Comment by CherylEvans** [comment]
@jknipes @pjhill Update:
"Good morning, Peter. 
I’m working on ticket 72001 and wanted to see if you are ready for me to review the content you created.
Here is the Slack discussion link. Thanks again for your help with this effort!"
Slack [LINK](https://dsva.slack.com/archives/CL181NRJQ/p1715265240434519)

**Comment by JoeTice** [comment]
We'll get this into the backlog and onto the schedule

**Comment by CherylEvans** [comment]
@jknipes Update: @little-oddball commented to @JoeTice 
"FYSA. Based on the updates in the ticket, I would say this hasn't made it to a Reliability Sprint to be worked as of yet. Just raising awareness to ensure some communication and coordination between content and reliability teams."
Joe commented: "Rgr, thanks for the heads up, we'll get this into the backlog and get is scheduled"
Slack [LINK](https://dsva.slack.com/archives/CL181NRJQ/p1715265240434519)
Joe, it looks like this is blocked for now. Thoughts?

**Comment by jknipes** [comment]
Currently unable to complete due to being blocked by SME, moving to Backlog
Need to confirm inclusion in future sprint with @JoeTice

**Comment by jknipes** [comment]
Sprint May 23 was auto-assigned, we have removed the dates from this ticket, which is still blocked

**Comment by jknipes** [comment]
@ph-One

**Comment by jknipes** [comment]
@ph-One we will work with you in Sprint 5, beg 7/4

**Comment by ph-One** [comment]
I have completed my updates

**Comment by CherylEvans** [comment]
I worked with @ph-One to make the updates. [Slack Link](https://dsva.slack.com/archives/CL181NRJQ/p1720453502887949)
The [document](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1884586162/Adding+a+new+External+Service+Integration) was published this afternoon—closing ticket.
