### ISSUE TITLE
Migrate `sentry-raven` to `sentry-ruby`

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#72028]
### Description
Upon finally upgrading to the latest version of `sentry-raven` it's now telling us that it's deprecated and we should migrate to `sentry-ruby`:
```
Post-install message from sentry-raven:
`sentry-raven` is deprecated! Please migrate to `sentry-ruby`
```

### Tasks
- [ ] Replace `sentry-raven` with `sentry-ruby`
- [ ] Test and Deploy

### Acceptance Criteria
- [ ] `sentry-ruby` has been deployed to production
