### ISSUE TITLE
INTAKE EPIC | Profile | Flagged Users

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72037]
## Background 

In the AE VA.gov Profile, users with flagged accounts are not authorized to view or change data in the Profile.  

Some examples of the flags in use are `Incompetent`, `Deceased`, `Fiduciary` 

While in the Profile the various services like contact information updates are gated, other applications that leverage our code are not blocked in the same way. We uncovered an example with the Letters tool. Users may have a flag on their account and cannot update their address in the profile but can make updates using the letters tool. 

[Blocked user documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/use-cases/blocked-account.md)

## What to do 
- We likely need to confirm all of the tools using this code and then determine if the business rules that drove us to lock down the profile also apply to the other use cases 

```[tasklist]
### Tasks
- [ ] [Practice Area FE?] | Flagged Users | Locate teams using Profile Code
- [ ] PM | Flagged Users | Reach out to the teams
- [ ] FE | Flagged Users | Block other applications from using the Profile Code if the user is flagged
```
