### ISSUE TITLE
Investigate issues with Makefile for running specs with Docker

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#72030]
### Description
While trying test some things related to the Debian upgrade, I ran into a handful of errors blocking specs from running in Docker.

### Tasks
- [x] Investigate why `make spec` / `make spec_parallel` don't work out of the box (notes below)
- [x] Update Makefile to correctly execute specs

### Acceptance Criteria
- [x] Specs run without issues on Docker from the master branch

**Comment by ryan-mcneil** [comment]
PRs for [k8s](https://github.com/department-of-veterans-affairs/vets-api/pull/14902) and [master](https://github.com/department-of-veterans-affairs/vets-api/pull/14903)
