### ISSUE TITLE
[Design] Create Final Wireframes & Content for Letting Veteran Know BTSSS is Down

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#72047]
## User Story

Veteran expects to review something to let them know that a feature is unavailable (e.g., filing for BT in check-in). That way they don't think they are doing something wrong by not seeing the travel questions, which the posters in their clinics say they should. 

## Tasks
- [x] Create final wireframes with content for Letting Veteran Know BTSSS is Down (Production, not unified check in.)  
- [x] Create wireframe variations, if needed, for how it appears on different pages in check in. E.g., auth page vs. contact info page vs. appts list page vs. appt detail page, etc. (Production, not unified check in.)  
- [x] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Looks good

**Comment by loripusey** [comment]
@benbrasso-agile6 is there something to look at? We haven't even pulled this into a sprint yet.

**Comment by benbrasso-agile6** [comment]
No. We should complete the dependent ticket first.

**Comment by benbrasso-agile6** [comment]
I was just saying the ticket tasks look good.

**Comment by benbrasso-agile6** [comment]
@ytsaoca  I created a page in Figma to demonstrate where the warning alert appears in the app and on the page. Do you want to go ahead and add the warning alert into each of those three frames on this page https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=36%3A325&mode=design&t=udjtkFQEAj6BFxG3-1

Kelly will work on the content next week for the warning alert when she is back.

**Comment by kellysmith1008** [comment]
Taking content from the [access error message page](https://design.va.gov/content-style-guide/error-messages/access):
@ytsaoca @benbrasso-agile6 What if we go with a version of Application or page is accessible - some parts of this may not be working: "You can still check-in for your appointment, but filing for a travel reimbursement claim may not work for you. You can still file within 30 days through the Beneficiary Travel Self Service System. (or whatever BTSSS really stands for!) and we can link out to BTSSS - though I wouldn't recommend doing that as it will (could) pull users from the check-in process. Thoughts? Happy to mock this up in figma if you need to see it

**Comment by benbrasso-agile6** [comment]
Actually, I think this works really well, and answers @cgednalske comment about moving it below the h1 (instead above it, like I had it). https://dsva.slack.com/archives/C02GXKL8WM6/p1704216873147279?thread_ts=1703872474.315719&cid=C02GXKL8WM6

**Comment by benbrasso-agile6** [comment]
I just updated the annotation @kellysmith1008 https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=36%3A325&mode=design&t=liIjuhE63qlpLdPr-1

**Comment by ytsaoca** [comment]
Hi @kellysmith1008 and @benbrasso-agile6,

I added an warning to the three frames on the Figma page. 
 I think the content works well for the contact info page.

Though not exactly related to this ticket, or maybe I missed the information somewhere, I wonder in this scenario, if users still go through all travel pay question pages and landed to the confirmation page? If yes, which do we show as the confirmation? https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/g1orPxJ
or 
https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/27YmRVl
Does the alert content on the confirmation page still makes sense?

**Comment by benbrasso-agile6** [comment]
Figma file looks great. Was @kellysmith1008 all done with the content? (Looks good to me.)

**Comment by benbrasso-agile6** [comment]
The first link. I think that alert content still works. (But, it's a good callout.)

Here's how it will look soon https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=1-8232&mode=design&t=yKZNNCio6ZUyXcZK-4

If Kelly thinks it should change though, I'm fine with that.

**Comment by benbrasso-agile6** [comment]
Should show Mark and Kay in Slack when ready :)

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I was going to suggest the second link @ytsaoca provided for consistency of language, but the more I think about it, I agree with you that the first link is a better option. This looks great, Ya-ching! Content is finished - nice work!

**Comment by kellysmith1008** [comment]
I think the informational alert on the confirmation page still works, Ya-ching - because we've already alerted them that travel pay is down, so we don't need to tell them we couldn't file their claim right now - they didn't go through any of the workflow for it. So that's why I think Ben is right that the first link, with the informational alert, is the better option. And I think it's a nice touch to keep information on travel pay on the confirmation page *because* we couldn't give them the workflow during check-in. Reminds them to still file.

**Comment by benbrasso-agile6** [comment]
@ytsaoca let me take a look at the sketch vs figma question. Will respond this morning.

**Comment by benbrasso-agile6** [comment]
I just imported a PNG into Sketch, just so it's there. https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/A6E73D11-A95C-4EC0-A3B7-792CE5799C59/canvas

**Comment by ytsaoca** [comment]
@benbrasso-agile6 Thanks for adding the PNG. I think it's better to be consistent to have wireframe artboards so I import the artboards to Sketch from Figma.

And thanks for answering my questions to the confirmation page. Based on [this thread](https://dsva.slack.com/archives/C022AC2STBM/p1704295086130259?thread_ts=1704290252.771299&cid=C022AC2STBM), it looks like we won't have the Travel pay questions if BTSSS is Down. I'm happy to document this path in the userflow if needed.

**Comment by benbrasso-agile6** [comment]
Sounds good. I know @cgednalske was suggesting we actually don't add anything in sketch, and instead point to the figma page. Let's talk more about it at UX sync.

**Comment by benbrasso-agile6** [comment]
@loripusey https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=36%3A325&mode=design&t=5Du9vlDZ0miXmUEw-1

**Comment by benbrasso-agile6** [comment]
@loripusey I moved the location of this design - https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=157%3A652&mode=design&t=8JVfVWmvjdF4aciC-1

**Comment by benbrasso-agile6** [comment]
@ytsaoca 

> Based on this thread, it looks like we won't have the Travel pay questions if BTSSS is Down. I'm happy to document this path in the userflow if needed.

Sounds good. Yeah, let me know when it's updated.

**Comment by ytsaoca** [comment]
@benbrasso-agile6  Updated the user flow https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/0157CB5C-B33B-4324-B375-AC686EFA3B4A/canvas

**Comment by benbrasso-agile6** [comment]
Looks good, @ytsaoca, the one change I would make is removing it from EC and NoK. The alert will only appear on their first landing page.
