### ISSUE TITLE
PM | Profile Hub | Submit a 508 Review Request

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72041]
## Background 

Now that we've launched the profile hub we need to have a 508 review 

## Tasks 
- [x] submit a request for a [508 review using these steps](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#HowtorequestsupportfromtheVA508Office-AuditRequest)

## Acceptance Criteria 
- [x] we've initiated the 508 review 
- [x] 508 ticket number: [RITM11104877]
