### ISSUE TITLE
Migrate Sketch files to Figma

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#72056]
### User story

As a Cartographers team member, I want to ensure all our historical design assets in [Sketch are migrated to Figma](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma), so that we are ready to lose access to Sketch in February.

## Acceptance criteria

- All Sketch files related to the MHV landing page and other Cartographers efforts are migrated to Figma
- Any useful historical information that can't be transferred to Figma has been saved elsewhere (e.g. comments in Sketch)

## Tasks

- [x] Ensure the access of Figma (e.g. Designer as editor, Engineer as viewer, etc.)
- [x] Locate the working files of MHV-Landing ([see the Figma link here](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&t=BiusItd1nrXZnycz-6))
- [x] Identify list of files that might be our responsibility to migrate
- [x] For each file, ensure everything makes it over to Figma cleanly
- [x] Took care of any comments or historical notes that don't migrate to Figma
- [x] Treated file version history as decided by team

**Comment by keithcheung828** [comment]
1. Per the 16 mins, we decided to export Sketch versions to Github
2. By doing so, @jzucadi suggested that exporting post exported Sketch files to .fig then .json files.
3. Please see [Web based tool for fig-json conversion](https://www.figma2json.com/)
4. @keithcheung828 and @jzucadi will discuss further after the final conversion of Sketch to Figma before the expriring of Sketch licensing (Awaiting the secondary nav design)

**Comment by keithcheung828** [comment]
Update: Historic files are now being saved in the [MHV Cartographer's shared drive](https://drive.google.com/drive/folders/1oodfZm4Dnf81ttcLGogQPFn9PuDmGWqH?usp=drive_link)
