### ISSUE TITLE
Move automated daily deploy to an earlier time

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#72051]
## Issue Description
Currently our daily deploy takes place at 3pm daily. The issue this has presented for Platform Support is that when the deploy goes wrong, it's often not discovered until closer to 4pm and by the time it's fixed it's often after hours. Our thoughts are that as long as there is a once daily deployment, it will not affect the VFS teams outside of that first switchover day.  This would allow the support staff to have more business hours to work out complications when they happen without pushing into overtime.

This issue has been raised to OCTO who approved of the change, however had numerous teams they wanted contacted about the issue as well to ensure nobody had objections to it. This process is still ongoing and this item will remain on hold until it's settled.

---
## Tasks
- [x] Obtain clearance necessary to make this change
- [x] Update cron schedule on daily deploy to move to noon EST or whatever time is universally agreed on.

## Acceptance Criteria
- [x] The automated daily deploy runs at the newly agreed on scheduled time.

**Comment by CBonade** [comment]
The first deploy scheduled at 1pm went out today!
