### ISSUE TITLE
Combine CI Cypress Test Prep and Unit Test prep into a single job

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#72059]
## Issue Description
Right now there are two separate jobs that prep for Cypress tests and unit tests accordingly. Both of these jobs are fairly quick, however, they have to take up two separate runners/instances to run. We can easily combine these into one job, and redirect any jobs that depend on variables from them, and save one runner per workflow from being taken up. It will still be the first job done in the workflow and should not hold up the workflow from completing, as it will always be waiting on the build.

---
## Tasks
- [ ] Combine cypress test prep and unit test prep jobs in CI, eliminating any duplicate steps.
- [x] Redirect other steps that depended on variables from these jobs to the new job reference

## Acceptance Criteria
- [ ] CI workflow runs as expected with no errors.

**Comment by CBonade** [comment]
Merged and completed!
