### ISSUE TITLE
FE Build/Deploy Pipeline Improvements - Near Term

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72068]
## Problem Statement
There are a number of known issues with the current set up of the frontend pipeline that we would like to make changes to, some of these changes can be made in the near term with limited risk, others require more thought and discovery to ensure that we implement the proper approach.

Research: https://vfs.atlassian.net/wiki/spaces/PRT/pages/2874015813/FE+Pipeline+Discussion

---

### Proposed Solution
Near term improvements consist of  modifying the trigger time and approach of the automated daily deploy, and making some improvements to the testing portion of the CI pipeline.

### Tasks/Efforts
- [ ] Move automated daily deploy to an earlier time
- [x] Combine CI Cypress Test Pre and Unit Test Prep into a single job
- [ ] Change automated daily deploy to source last commit that's cleared CI instead of last commit
- [x] Determine and implement unified test selection method for E2E tests & Stress tests
- [x] Discuss Unit Test approach to eliminate blockers from other team's tests

### Definition of Done
- [x] Improvements have been implemented, tested, and documented as appropriate
