### ISSUE TITLE
[CST] Change 'Submitted on' language to 'Received on'

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#72065]
## Value Proposition

As a veteran checking their status in the CST I want instances in which a claim is labeled as "submitted on X" to be correctly labeled as "received on X" because that is the more accurate label and I will not be misled about the date I submitted my claim. 

## Background
We should update the language we are using in the CST to replace instances of 'Submitted on X' to 'Received on X' to more accurately reflect the dates we are displaying. This is especially relevant to Veterans who have submitted BDDs, because the date that we are given by Lighthouse / EVSS is usually the date that they were discharged, not the date that they submitted their claim. **Note:** We don't have access to a data point currently that accurately reflects when they submitted the claim, if we did this would probably be a better data point to use instead of the one we have access to now

Scenario 1:
1) Soon-to-be-Veteran submits a BDD on 06/12/2023
2) They become a Veteran on 8/10/2023
3) They go to the Claim Status Tool
4) They see that their claim says 'Submitted on 8/10/2023' (Even though they actually submitted the claim on 06/12/2023)

Scenario 2:
1) Veteran submits a Compensation claim on 10/25/2023
2) VA.gov accepts the claim, but VBMS is down
3) The claim gets submitted 2 days later (10/27/2023)
4) They see that their claim says 'Submitted on 10/27/2023' (Even though they actually submitted the claim on 10/25/2023)

## Screenshot
![Screenshot 2024-01-18 at 1 20 01 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/16b05df2-a685-4730-9cf0-f547888db912)
![Screenshot 2024-01-18 at 1 21 28 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/b45ec5a8-51b9-4b16-a139-b84a5b374ffd)

## Considerations
The 2 main places we display the claim date are:
* On the claim cards (both the V3 and V2 versions)
* On the claim details subheading (both the LH and EVSS version)

## Tasks
- [x] Update the V2 claim card
- [x] Update the V3 claim card
- [x] Update the subheading on the EVSS version of the claim details page
- [x] Update the subheading on the Lighthouse version of the claim details page
- [x] Update any tests that are associated with the components mentioned above

## Acceptance Criteria
- [x] Claims cards are updated to use 'Received on' language
- [x] Claim details subheading is updated to use 'Received on' language
- [x] Update [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72494) so sitewide team is aware of this change
- [x] Notify VA Mobile, VA Chatbot team, and other status tool teams about the language changes and why we made those changes.

**Comment by HeatherWidmont** [comment]
@jerekshoe & @pmclaren19 will look at this in the parking lot today

**Comment by pmclaren19** [comment]
Tested in Staging for EVSS and Lighthouse and looks good!

**Comment by pmclaren19** [comment]
Assigning to @skylerschain to finish the last two acceptance criteria steps.
