### ISSUE TITLE
Determine and implement unified test selection method for E2E Tests & Stress Tests

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#72061]
## Issue Description
Currently regular E2E test selection and the E2E Stress Test run in separate jobs with parallel processes in each. They consume a large number of runner resources each and both use different methods for selecting which tests they want to run. However, if we're verifying tests they should follow the same logic for what's important to verify, and then we can combine these two steps to save resources and time both. Important to note that the stress test does not run against the main branch, so that will have to be maintained only running on feature branches after a restructure.

---
## Tasks
- [ ] Meet with QA to determine best practice for E2E test selection
- [ ] Implement unified test selection
- [ ] Combine regular E2E tests and stress test jobs into one that handles both correctly with one set of runners.

## Acceptance Criteria
- [ ] E2E Tests run in a much more efficient setup.

**Comment by CBonade** [comment]
After discussing this ticket with Peter and Isaac, this is going to have to be more than just altering how selection is done if we want this solution to be done properly. Part of this, is going to be dissecting how everything is currently done and trying to understand the original ideas behind them.

Our current plan is to do the following:

- Alter the selection to match the unit test selection method of only tests in shared directories with changed files
- Change how the tests are being split amongst containers to be even in each container instead of 50 per container right now which results in empty containers being spun up for no reason, consuming self-hosted runners
- Change the variable number of containers to the same each time, now that we'll likely not have anyone running the full suite in 1 PR.


As this implementation far exceeds the original expectation, I'm going to split this implementation out into its own ticket and adjust this estimate down to just a discussion estimate of 2 from its original 5.
