### ISSUE TITLE
Discuss Unit Test approach to eliminate blockers from other team's tests

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#72063]
## Issue Description
Currently, all of our unit tests run on every push to vets-website. While time is not a problem as they finish before the build does and do not hold up the workflow, as the suite has grown it has introduced some issues around the reliability of making it through the entire job without running out of memory, flakiness popping up (sometimes from another team) and other sources. We can possibly apply test selection to unit tests or some similar principal to streamline the feature branch into main merge flow, while still running all the tests against main post-merge. 

---
## Tasks
- [x] Discuss pros and cons of unit test selection.
- [x] Decide on a strategy moving forward
- [x] Create a ticket to implement the decided upon strategy

## Acceptance Criteria
- [ ] A ticket exists to streamline the unit test process.

**Comment by CBonade** [comment]
Had this meeting with Peter, Joe and Isaac on 1/18. The decided on approach was to utilize the selection method that the allow list processes are using where on the feature branch merge request, only the tests that are related to changed files run. On the main CI runs, all tests will still run. This will reduce unrelated failures prior to merge.

**Comment by CBonade** [comment]
Because this ticket was originally supposed to be a discussion ticket only, but the implementation happened in the process, I bumped the estimate up to a 3 from a 2. The implementation of this is complete.
