### ISSUE TITLE
FE | USWDS V3 Component Migration | Military Info Page

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72076]
## Background 
We need migrate to the USWDS V3 components we're going to start with a simpler page to get a feel for the process.

## uswds v3 components that are in profile

from [VA design system Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-accordion--default)

| components that can be upgraded to v3 | on Profile? | what section/s or file/s? |
| -- | -- | -- |
| Accordion | ❌ | |
| Additional info | ✅ | many |
| Alert | ✅ | also many |
| Breadcrumbs | ✅  | ProfileBreadcrumbs |
| Button pair | ❌ | |
| Button | maybe | AccountSecurityTables has a non-web-component button that has a `va-button-link` class - this probably won't be affected |
| Checkbox group | ❌ |  |
| Checkbox | ✅  | NotificationCheckbox (react-binding) |
| Featured content | ✅  | CopyAddressModalPrompt, MilitaryInformation |
| Icon | ❌ | |
| Memorable date | ❌ | |
| Modal | ✅  | CopyAddressModalFailure, CopyAddressModalSucess, BankInfo, EditConfirmCancelModal (all react-bindings) |
| Number input | ❌ | |
| Pagination | kind of (derivative) | ConditionalProcessList |
| Privacy agreement | ❌ | |
| Process list | ❌ | |
| Progress bar | ❌ | |
| Radio button | ❌ | |
| Search input | ❌ | |
| Select | ❌ | |
| Statement of Truth | ❌ | |
| Text input | ❌ | |
| Textarea | ❌ | |

_Originally posted by @allisonlu in https://github.com/department-of-veterans-affairs/va.gov-team/issues/69483#issuecomment-1852648582_
            
## Tasks 
- [ ] List out the components that need to be updated (post as a comment) 
- [ ] list out events (post as a comment) 
     - [ ] identify which have custom events 
- [ ] To toggle or not to toggle? that is the question - decide if we toggle this work or no
- [ ] make the updates 
- [ ] rework the tests 
- [ ] check analytics dashboards 
     - [ ] is there Domo impact  

## Acceptance Criteria 
- [ ] we've got a page updated with V3 Components

**Comment by mtcA6** [comment]
@adamwhitlock1 @allisonlu @DanielMiller-agile6 take a peek at the tasks and AC and add in anything you deem is missing. 

Might make sense to work through this page as a team to test out the best process. Let me and @ajakabcin know your thoughts!

**Comment by ajakabcin** [comment]
@allisonlu I'm going to mark this in our sprint epic but I'd like you to work with Adam on this ticket this sprint. Thanks!

**Comment by adamwhitlock1** [comment]
The work for updating the military information page were pretty minimal

- Updated components to use uswds prop
- Went ahead and updated some <a> links to use the <va-link> instead
- Updated tests where needed

My plan is to review this with the engineering team on thursday during out once-a-sprint engineering meeting and discuss any further implications for other more complex cases, but at least this page was pretty cut and dry!

Once PR is merged I'll update this ticket for validating.

**Comment by mtcA6** [comment]
@adamwhitlock1 that's good news! I'll keep an eye out for the validation info after y'all meet. :)

**Comment by adamwhitlock1** [comment]
user 80 can be used to validate this

<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2kzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8a7eb22fe386451140f773e18621a4df9cdbdc0/Screenshot%202024-01-10%20at%204.12.30%E2%80%AFPM.png" alt="Screenshot 2024-01-10 at 4.12.30 PM.png" />

**Comment by adamwhitlock1** [comment]
I'm not sure how I feel about the blue box with the border and rounded corners. It is a [featured-content](https://design.va.gov/storybook/?path=/docs/components-va-featured-content--default) component, and kinda looks out of place with the new version's styling.

We could also look into using a variant of the [alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--default) or the [card component](https://design.va.gov/storybook/?path=/docs/components-va-card--default)

**Comment by ajakabcin** [comment]
@adamwhitlock1 and @allisonlu who is the best person/role to validate this? 

also do we have an image of what this component looked like pre-migration for comparison?

cc @mtcA6

**Comment by mtcA6** [comment]
@pamela-drouin what are your thoughts on the new component?

**Comment by mtcA6** [comment]
> @adamwhitlock1 and @allisonlu who is the best person/role to validate this?
> 
> also do we have an image of what this component looked like pre-migration for comparison?
> 
> cc @mtcA6

What I don't know is if we updated the sketch file already or no, it kinda looks pretty similar to me 

[see sketch](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/zeYjvr/p/9FFC38AC-32C3-4AC1-86F6-A146B1F933A7/canvas?posX=-1362.7434338732546&posY=-454.0557748832796&zoom=1.3757731914520264)

**Comment by pamela-drouin** [comment]
@mtcA6 if the featured-content component, V1 and V3 are both visible here for comparison: https://design.va.gov/components/featured-content

I don't really have an opinion of either, and I don't believe all of the components are updated in Figma yet.

**Comment by adamwhitlock1** [comment]
@ajakabcin I think anybody can validate on staging, basically the page just needs to look the same-ish aside from the featured comment chunk at the bottom which now has a border and rounded corners.

![Screenshot 2024-01-16 at 12 34 38 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/14ff85cc-bf6c-4484-9cea-5855f34d8dfb)

The before migration version was pretty much the same layout wise.

**Comment by allisonlu** [comment]
I can validate from the dev tools (the `uswds` attribute is set to true on staging)

![Screenshot 2024-01-16 at 3 52 08 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/52418c8c-12a4-439f-b4ef-0cd3188bb864)
