### ISSUE TITLE
Intake new Trexler File on 12/15

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#72083]
We receive a weekly Trexler File from Randy at OGC so that we can continue to keep the rep address and email information up to date.  This ticket is for receiving this weekly file and making the necessary updates in our Find a Representative backend.

### Tasks

- [ ] Download the new Trexler File from the Drop Location (accessed through the VA Network in Teams: OITSPM GCLAWS-VBA Integrations team > ABD (VASI 2823) Accreditation Interface thread > Files tab)
- [ ] Email the new Trexler File from your va.gov email account to a preferred email account, to manage outside of the VA network
- [ ] Add the new Trexler File to the GitHub `department-of-veterans-affairs` organization’s `va.gov-team-sensitive` repository
