### ISSUE TITLE
Pension Team Sprint 10 Plan: 12/20/2023—01/02/2024

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72091]
## Sprint 10: 12/20/2023—01/02/2024

**- Outages (PTO, holiday, or unplanned):** 
-- Dec 20-Dec 22: Christie, Lauren
-- Dec 21: Buddhima
-- Dec 22: Emily, Buddhima, Scott
**-- Dec 25: Everybody**
-- Dec 26: Scott, Dan
-- Dec 26-Dec 29: Coforma, Allexe, Gretchen, Todd, Vicky, Wayne
-- Dec 29: Dan
**-- Jan 1: Everybody**
-- Jan 2: Anh, Lauren
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL04rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b384788872cbf8969532047561e5ffa4457776b1/Screenshot%202023-12-21%20at%209.04.56%E2%80%AFAM.png" alt="Screenshot 2023-12-21 at 9.04.56 AM.png" />

## Theme(s):

- Design formalizing Pension form logic diagram
- Finalize pending FE updates
- Continue PDF data mapping
- Expand our QA efforts across the team
- Start schema mapping updates
- Prepare staging review artifacts and schedule date for review

## Notes:
- 
 
## Goal(s):

**QA/TESTING**

- [MVP] Review all changes in staging environment in the "Review/QA" column - **Anh has been helping with this**
- [x] [MVP] Test Pension E2E form flow logic in staging #72422 - **Maya**
- [ ] [MVP] Prepare E2E test scenarios for staging review & data mapping purposes #72271 **- Vicky**
- [x] [MVP] Test Pension form flow logic in staging for Steps 1-3 #71135 - **Anyone who can help**
- [ ] [MVP] Test Pension form flow logic in staging for questions in Step 4 #71136 - **Anyone who can help**
- [ ] [MVP] Test Pension form flow logic in staging for Steps 5-7 #71139 - **Anyone who can help**

**_Staging review prep_**

- [ ] [MVP] Start draft of Pension Release Plan #72273 - **Vicky, align with Matt & PO on this**
- [x] [MVP] Schedule Pension MVP relaunch for Staging review #69174 - **Vicky, align with team on this**
- [ ] [MVP] Start preparing for required Accessibility artifacts to prepare for staging review #71563 - **Todd**
- [ ] [MVP] Start preparing for required QA artifacts to prepare for staging review #71379 - **Matt**
- [ ] [MVP] Prepare necessary Design artifacts to provide before staging review #71623 - **Maya**

**RESEARCH/DESIGN**

**_MVP relaunch_**
- [x] [MVP] Update form flow logic diagram in existing MURAL for Steps 5-7 #70303

**ENGINEERING**

**_MVP relaunch: Frontend work_**

- [x] [MVP] Audit for redundant/old pages no longer part of the form flow #71893 - **Vicky & Zack taking a pass at this**
- [ ] [MVP] Step 4: Revisions to page flow, order and questions #72455
- [x] [MVP] Step 5: Remove redundant/old pages from form flow #72332
- [ ] [MVP] Step 5 & beyond: Update form flow page order #72330
- [ ] [MVP] Step 6 Additional information: Update copy #71855
- [ ] [MVP] Step 7 Review application: Update based on overall form field changes #71857 - **Will probably require a manual QA but fields should automatically populate based on existing questions on the form**

**_PDF data mapping_** - Scott & Dan

- [x] [PDF Mapping] Modify Sections 1-4 PDF mapping #72350

- [x] [PDF Mapping] Map online form fields to new PDF for Section 5: Employment History #70389
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 6: Marital Status and Spouse Info #70390
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 7: Prior Marital History #70392
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 8: Dependent Children #70393
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 9: Income and Assets #70394
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 10: Info About Unreimbursed Medical Expenses #70395
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 11: Direct Deposit Info #70396
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 12: Claim Certification and Signature #70397
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 13: Witness to Signature #70398

- [ ] [MVP] Implement/confirm claim submission date appears on Pension PDF form #71456
- [ ] [MVP] Ensure we capture form online user signature properly #72279 - **Need more info on this from Emily**

**_Migrating to Lighthouse Benefits Intake API:_** 
- [ ] [MVP] Add polling to Lighthouse Benefits Intake API #71897 - **Wayne?**
- [ ] [MVP] Perform API meta data validation #72276 - **Who will own this?**

**_Schema mapping_**
- [ ] [MVP] Update vets-json-schema #71917 - **Who will own this?**

## **WARNING... Below tasks are not in scope for this sprint but are in scope for MVP**

**- SPRINT 11 (Jan 3-Jan 16)**

**_MVP relaunch: Frontend work_**

- [ ] [MVP] Coordinate relaunch copy edits to static pages with CAIA/Katherine

**_Logging and monitoring strategy_**

- [ ] [MVP] Setup DataDog alerts for both retry and queue exhaustion #70462 **- Tai & Buddhima**
