### ISSUE TITLE
[UX][Design] Create Design Options for an experimental notification collection pattern

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72101]
## Description 

The purpose of this design work is to create and test a new design pattern with Veterans, building off of what VFS teams have already researched, tested, or explored, that allows them to review and complete more than 1 time-sensitive task in a health app (like Appointments or Check In), which could easily be scaled upstream on VA.gov experiences (i.e., used on), including My VA, MHV on VA.gov, Profile, or on-site notifications.  

In addition, the design pattern (or variations of the pattern) need to consider solving for scenarios where there is a primary action vs. secondary actions, as well as grouping sets of similar actions.

Initial exploration was started in [Sketch](https://www.sketch.com/s/845dc4de-d3ec-4dab-a14a-f89d79c47de5/p/73048119-1222-4B42-AAFB-42011E57E6DB/canvas). 

The design pattern should the scenario(s) and entrance path(s) identified in [[UX] Identify scenario(s) and entrance path(s) to use for exploration of notification collection pattern #72100](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/72100). 

Goals and objectives have been documented in [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702399452662/39f5a4a805c7ed89c0d4f337111637ae5d540df1). 

**What we know**

- [Notification component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1181) was deprecated because it was was too similar to a task card (same except close button) 
- Notification hub work was paused for a few reasons, found in [MyVA’s onsite notifications documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications#re-evaluating-the-vanotifyonsite-vagov-notifications-strategy) 
- (from our research) Task card is highly successful/discoverable as a single notification
- (from our research) Task cards/notifications should likely not be dismissible
- (from our research) Task card is more successful than dot indicator
- Solution needs to be something that is not limited to one application, but could be scaled or applied as a solution (in some capacity) anywhere

**Past VFS research**

- [Appointments notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/appointment-reminders/research/2023-10-notification-kano/research-plan-survey-3-(appointments-only).md) (Upcoming)
- Past Appointments Travel Reimbursement
- [MyVA - onsite notifications stakeholder interviews](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications/notification-center-discovery)
- [My VA benefit payment and debt Info and onsite notifications research](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/64)
- [Research Plan for Authenticated Experience My VA - Dot Indicator](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/appointment-reminders/research/2023-10-notification-kano/research-plan-survey-3-(appointments-only).md) (On hold) 

## Tasks
- [x] Review the documents in this ticket (read & understand this ticket)
- [x] Create design options (team chooses fidelity of the design options based on situation)
- [x] Get feedback from appropriate stakeholder(s). E.g., content or a11y SMEs, platform design, UX team, check in team, VA OCTO PO's, check in PO, Angela Fowler (a11y) or Sara Sterkenburg (IA).
- [ ] Incorporate feedback into solution(s) 
- [ ] Create f/u tickets for next steps

## Acceptance Criteria
- [ ] Design solution(s) has been chosen that we want to test
- [ ] Design solution idea(s) to test have been vetted and approved by appropriate stakeholders 
- [ ] Follow up tickets have been created for next steps

**Comment by ytsaoca** [comment]
Discovery:https://app.mural.co/t/civicactions3117/m/civicactions3117/1706558414178/cd89a5d2c62a91e4d490afdebe0e20c8d4a45280?sender=u70b8b2930b03d3ef317d2520

User Scenarios: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702399452662/39f5a4a805c7ed89c0d4f337111637ae5d540df1?sender=u70b8b2930b03d3ef317d2520

Idea collection: https://www.figma.com/file/vhrM4Vy7TYayehwSoCWJq2/Experimental-notification-collection-patterns?type=design&node-id=0%3A1&mode=design&t=rHWW3QjTXGFyq1Bw-1

**Comment by benbrasso-agile6** [comment]
@ytsaoca @cgednalske I moved Ya-ching's Figma work into here - https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=107-502&mode=design&t=Almtovw6O5SPMzHY-4

**Comment by benbrasso-agile6** [comment]
@loripusey this will carry over 1 last sprint

**Comment by benbrasso-agile6** [comment]
@cgednalske feel free to reset the points on this ticket too

**Comment by benbrasso-agile6** [comment]
If needed, I would bring @zach-park into this for support, if/when you're ready, @cgednalske

**Comment by benbrasso-agile6** [comment]
@loripusey when Christina finishes this up this week, we should be able to close this Epic. Kristen wants to socialize it to other teams and then make some decisions on next steps. So, I'd assume we'd create a new Epic if those next steps involves our team.

**Comment by cgednalske** [comment]
@loripusey @benbrasso-agile6 Finished [exploration around notifications collection pattern](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=182%3A3268&mode=design&t=LnjzSxVP33av3kUQ-1) and met with Kristen to go over work and next steps.

**Next steps/notes:** 
- Now that discovery phase has wrapped up, Kristen will work on internal coordination with MHV and Auth teams, where there is interest in this sort of pattern. 
- Unified appointments is the first group hitting this, but we don't know yet who will end up running with it or testing.
- Some continued discovery completed around [appointment detail page](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=246%3A6732&mode=design&t=LnjzSxVP33av3kUQ-1). 
- Resulting [Appointment Detail page ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77232) created for if/when we pick this work back up. (not sure if it should be a spike or not)

**Comment by loripusey** [comment]
I added the ticket to the next sprint
