### ISSUE TITLE
[FSR] Intercept Survey staging bug

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#72105]
## Description
We're experiencing some issues with the Medallia intercept survey showing up on the following URLs:
 - `staging.va.gov/manage-va-debt/request-debt-help-form-5655/confirmation`
 - `staging.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist`
 - `staging.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist`

The survey is showing on the `/introduction page` just fine. The two checklist pages don't error out, but the survey can be manually triggered with `KAMPYLE_ONSITE_SDK.showForm(41)`. The `/confirmation` page is showing an error (screenshot below) that may not be caused by the survey, but is likely preventing it from showing up. 

We tested another authenticated page (`/manage-va-debt/summary`) to rule out authentication causing an issue, so current theory is the form system routing is causing some problems. 

The surveys should still be active on staging, so let's test and see if we can determine if this is a staging specific issue.

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4eb59287ac0ced00baaabf77132779090050f5b2/image.png" alt="image.png" />

## Tasks
- [x] Test survey in staging to help narrow down the issue. 
- [ ] Coordinate with platform to see if there's some staging security measure that's preventing the survey from loading. 
- [ ] (optional) See if we can get veteran who has debt/copay that is willing to test on production with the medalia team to determine if the issue is staging specific. 

## Acceptance criteria

- [ ] Root cause of survey failing to appear on staging identified
- [ ] Issue is determined to be staging specific and okidokey on production (OR) problem is fixed

## Testing
- [x] Attempt to get survey to populate on staging/production

Testing procedure:
Run through pages, use cheat code `KAMPYLE_ONSITE_SDK.showForm(41)` to manually trigger modal. 

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
I was able to trigger the survey on the `/confirmation` page with the cheat code; `KAMPYLE_ONSITE_SDK.showForm(41)`, but I occasionally get the following errors manually loading the script <img width="1046" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae46614be69761b9597e7fd5a83a76f42406732a/image.png" alt="image.png" />

**Comment by Dr-Pongo** [comment]
Also dropping the name of the script we should see so we can tell if it's loading on the page:
`<script type="text/javascript" async="" src="https://resource.digital.voice.va.gov/wdcvoice/5/onsite/generic1702910126539.js" charset="UTF-8"></script>`

**Comment by HeatherRienks** [comment]
@josephrlee @mgleo - FYI. FE will need designs before they can complete this work.

**Comment by mgleo** [comment]
<img width="1134" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1dXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a488118c84c2922019e582ed4d48f171d5c4c226/confirmation-page.png" alt="confirmation-page.png" />

@denisecoveyduc What are your thoughts on this copy?

**We would appreciate feedback on your experience filling out this form.
Provide feedback**

**Comment by Dr-Pongo** [comment]
Just dropping some dev screenshots to make sure it's lookin solid @mgleo 

Full form:
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07610fc909d3b2a334789b63bc04ec3f03fe70dd/image.png" alt="image.png" />


Streamlined:
<img width="1376" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2613ca4534eb39129e483a065663c869596d3d61/image.png" alt="image.png" />

**Comment by mgleo** [comment]
Looks good to me! 
Platform should update to the USWDS Alert component on the front end (Figma is currently showing the all green USWDS bg in my screenshot above).
This should be good to go CC @denisecoveyduc @josephrlee

**Comment by Dr-Pongo** [comment]
@mgleo I added screenshots with buttons and uswds alerts in the PR linked to this ticket! ^

**Comment by mgleo** [comment]
Thanks @Dr-Pongo!
CC @denisecoveyduc @josephrlee FYI Andrew was not able to commit the PR with an action link so it was converted into a button

**Comment by Dr-Pongo** [comment]
After the meeting on 01/04 we are getting merged into staging and hiding on production with a `environment.isProduction` check. 

**Next steps:** 
 - Confirming functionality on staging
 - Waiting for production survey form number from Medallia team
   - They are also configuring production settings

**Comment by Dr-Pongo** [comment]
Final text has been confirmed. Just need Medallia side to wrap up and deploy to prod so we can include the number on our side

**Comment by Dr-Pongo** [comment]
Got the production number!
| Environment | Survey number |
| :--: | :--: |
| Production | `43` |
| Saging | `41` |

**Comment by Dr-Pongo** [comment]
Errors in sentry are getting logged under `5655 Error loading end of form survey`, had a bit of a panic yesterday seeing a large spike, but that was due to mistaken UTC timestamps. So far less than a 1% failure to load survey rate, so going to close this ticket out and just regularly monitor sentry for potential issues. 

Also created a follow on ticket to add a feature flag that controls the visibility of the button:
[FSR] Survey information feature flag implementation [#74030](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/74030)
