### ISSUE TITLE
Support: Mon-Thur Deploy (S43)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#72113]
## User Stories
As a Platform team member who just contributed to the Platform website,
I need my content published,
so that I can share my content updates with the intended audience.

As a content team,
we need to review any new content changes made on the platform,
so that we can deploy every Tuesday and Thursday of the week.

## Tasks
Someone from our team will use Scroll Viewport to publish changes to the website after 3pm EST on:

- [x] Wednesday (12/21) - Lauren
- [x] Thursday (12/22) - Jill
- [x] Mon (12/25)- Wed (12/27): **NO DEPLOYMENT**
- [x] Thursday (12/28) - Jill (potential tag team)
- [x] Monday (1/1) - **NO DEPLOYMENT, New Year's Day**
- [x] Tuesday (1/2) - Brian
- [x] Wednesday (1/3) - Lauren
- [x] Thursday (1/4) - Jill
- [x] Monday (1/8) - Lauren
- [x] Tuesday (1/9) - Brian
- [x] Wednesday (1/10) - Lauren
- [x] Thursday (1/11) - Jill
- [x] Monday (1/15) - **NO DEPLOYMENT, MLK Jr. Day**
- [x] Tuesday (1/16) - Brian

## Acceptance Criteria

- [x] The Platform website will be deployed Monday-Thursday between 3:30 and 5pm for this sprint.
- [x] Any edits with launch-blocking issues will be announced to their content editors via #platform-content

## Other Info

Data tracking info:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2282979860/KPIs+-+Content+Support

Temporary rotating schedule:
https://vfs.atlassian.net/wiki/spaces/CIT/pages/2405171201/Deployment+rotation+schedule

**Comment by johnny-jesensky-adhoc** [comment]
All deployments completed in this current sprint - moving this to _Done_.

FYI @jknipes
