### ISSUE TITLE
Add Content for Incident Response  #72087

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#72111]
## Description
We received from feedback on a footer request about adding new documentation to the Platform Website on incident response documentation for application teams ([#72087](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72087)).

The content has been pretty flesh out, we just need to help with structuring it appropriately, determining exactly where it should live, and then get some review from Adrian, who submitted the ticket.

## Tasks

- [x] Review Github Ticket
- [x] Create draft of the content, structuring it appropriately
- [x] Determine with the rest of the PCT where it should live on the Platform Website
- [x] Send back to Adrian to review the content
- [x] Prepare page for deployment

## Acceptance Criteria

- [x] Page has been deployed.

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/72111?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by chrisj-usds** [comment]
@johnny-jesensky-adhoc 
Can we expedite this request please? OCTO is running a Code Yellow process on incident response and need to get this posted asap. 
FYI: @davidconlon @raywangoctova @EWashb

**Comment by johnny-jesensky-adhoc** [comment]
Hi @chrisj-usds, absolutely -  I've relayed the urgency of this request to my team, and have them working to complete this ASAP. 

Just a note -  I'll be OOO from tomorrow (12/21), through next Wednesday (12/27), but have instructed them to provide any further updates in this ticket. Thank you!

FYI @andreahewitt-odd , @BSmolensky

**Comment by BSmolensky** [comment]
@chrisj-usds - We are now waiting on the ticket originator to clarify a few processes. Once that is complete, we should be ready to deploy this page. Thanks for the head-up. Have a great night and a Happy Holidays.

**Comment by BSmolensky** [comment]
@chrisj-usds - [This page is good to go](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2883912091/Incident+response+documentation+for+application+teams). It should get deployed this afternoon.

**Comment by BSmolensky** [comment]
@chrisj-usds - [This page is good to go](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2883912091/Incident+response+documentation+for+application+teams). It should get deployed this afternoon.

**Comment by EWashb** [comment]
Thank you to @BSmolensky @johnny-jesensky-adhoc @acrollet  and anyone else that worked on this. I appreciate your response to this high-priority request.

**Comment by acrollet** [comment]
Thanks y'all, much appreciated!

**Comment by chrisj-usds** [comment]
Thanks all!!!

**Comment by BSmolensky** [comment]
Thank you for all the kind words. Glad we got done in time. It was a Team Effort! First, @acrollet did a lot of work in the ticket itself and was quick to respond to questions. Thanks, Adrian. @taylojill did a helpful copy edit once it was in Confluence and formatted, @laucon did the final review and moved it to Developer Docs, and then @taylojill deployed it. Go Team!

**Comment by johnny-jesensky-adhoc** [comment]
Yes, thanks for the work on this team. Just did a quick review, and confirmed this content is now live on the Platform Website [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/incident-response-documentation-for-application-te). Everything appears to have been deployed properly, and meets our acceptance criteria - moving this to _Done_.
