### ISSUE TITLE
Content Tip of the Sprint (S43)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#72116]
## Purpose
The Content team provides a new "content tip" every sprint with the #platform-content channel's audience. The purpose of this is to provide continuous style guidance and re-enforce content best practices for contributors of the Platform website.

## Tasks

- [x]  Pick a content tip idea from the style guide
- [ ]  Draft a content tip Slack post, similar to the first one posted on Thurs, Jan 5: https://dsva.slack.com/archives/CL181NRJQ/p1672938003050849
- [x]  If needed, get feedback from rest of Content team
- [ ]  Copy and paste the team-approved announcement of our Tip of the Sprint in to the platform-content slack channel.
- [ ]  Schedule for _**Thursday, January 4th, 2023**_

## Acceptance Criteria:

- [x]  A new content tip will be posted on #platform-content for this sprint.

**Comment by johnny-jesensky-adhoc** [comment]
This was posted today, _**Thursday,January 4th**_. Marking this as _Done_.  https://dsva.slack.com/archives/CL181NRJQ/p1704391201581469
