### ISSUE TITLE
[Design] Migrate Authenticated Experience Sketch library to Figma

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#72127]
As a designer, I want to ensure concepts created in Figma contain the most accurate representations possible of the VA's design system components so that developers can accurately build the best experiences possible. 

### **Tasks:**
- [x] Import Authenticated Experience library file into Figma
- [x] Assess functionality
- [x] Modify/fix any components that need adjustment to work in Figma
- [x] Document any identified shortcomings
- [x] Sync with other design team members of Authenticated Experience as needed for outstanding questions about functionality, appearance, etc. 
- [x] Review with design team members
- [x] Discuss plan for finalizing Auth. Exp. library, plan for future updates

### **AC:**
- [x] Authenticated Experience library from Sketch is ported into Figma (as fully as possible) and can be utilized in any other Figma files
- [x] Any shortcomings/issues identified are documented

**Comment by mattmarino-adhoc** [comment]
@ajakabcin More work will be required, this needs to push to the next sprint.

**Comment by mattmarino-adhoc** [comment]
Received word from Dan Brady the white, outlined version of the Card component is in progress for VADS, and should be available soon (TBD if that means before end of sprint).

**Comment by mattmarino-adhoc** [comment]
Decided on holding off on any more color replacement using the VADS color library as-is, until they make more progress. Will update more next sprint/when they're ready.

**Comment by mattmarino-adhoc** [comment]
Updated story to reflect that Auth. Exp. library is not finalized, we will need to update it as the VADS team continues their own additions to the overall design library.
