### ISSUE TITLE
Incoming Issues Tracking - Sprint 10 

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#72120]
## Issue Description
Contact Center will review and track all incoming issues escalated from VEO

---
## Tasks
- [x] Tabulate incoming issues into categories - Tier 2/Tier 3/Tier EVSS
- [x] Create a grid displaying the number of incoming issues for each category
- [x] Publish report for leadership at the end of each Sprint

## Acceptance Criteria
- [x] Report published for leadership viewing
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
<img width="534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGVuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--901fd69afefa90bd472078ffe4148a118cbd8722/image.png" alt="image.png" />
