### ISSUE TITLE
Left Nav design updates

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7212]
## User Story or Problem Statement
As a veteran, I need the left menu elements assist me in navigating the website so I can find what I am looking for more easily. 

## Goal
Use style to represent hover, active and open left nav element states to avoid confusing users

## Objectives or Key Results this is meant to further
OBJECTIVE 3: Deliver a usable and accessible experience

---
## Tasks
- [ ] Develop left nav consistent with Ryan's design in [Zeplin](https://zpl.io/2jxORgp) and according to https://design.va.gov

### General Left Nav styling
- [x] Three section heads ("SERVICES AND LOCATIONS", "NEWS AND EVENTS" and "ABOUT VA") are in all caps and _$color-gray-dark_ 
- [x] All other elements are in sentence case and _$color-link-default_
- [ ] Indent child pages
- [ ] Grandchild pages have a _$color-gray-lighter_ vertical line on the left which becomes visible when the section opens. Note: this can be tested [here](https://staging.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/psychology-internships-and-fellowships/)
- [ ] Remove carats for opening accordions
- [ ] Sections are divided on top and bottom by _$color-gray-lighter_ horizontal rule with space on each side
- [ ] Make sure the divider lines are either hidden programmatically or are borders created with CSS.
- [ ] Ensure horizontal rules do not separate parent from child items. 
- [ ] Menu items are clickable unless user is on that page. 

### Active/On State

- [x] Change text color from default blue to _$color-primary-darker_ when a left nav item is selected
- [x] Add border box around selected nav bar item with vertical left bar highlight in _$color-primary-darker_
- [x] When a left nav item is selected, the background color of the item changes to _$color-gray-lighter_

### Hover state
- [x] Add border box around selected nav bar item with vertical left bar highlight in _link-default blue_
- [x] The hover state behaves the same at any level. 
- [x] Ensure _$color-gray-lighter_ vertical line for grandchild pages are still visible in hover state. 

### Focus state
- [ ] Focus must go to the top of the page for each page
- [x] The styling for focus state is correct on staging. 
- [x] Ensure yellow halo overlays other styling with padding

### Open state
- [x] Ensure the text color of a clicked item changes from blue to _$color-gray-dark_ 
- [x] Ensure the background color of a clicked nav item changes to  _$color-gray-lightest_ 
- [x] Ensure the open menu item is bordered by a box with a left bar highlight in  _$color-gray-dark_ 
- [x] Change the horizontal section lines to full width and _$color-gray-dark_ 

### Functionality
- [ ] Ensure that clicking a nav bar item takes user to the page clicked 
- [ ] Ensure that clicking a nav bar item reveals all of its children and grandchildren
- [ ] When a section is opened, any previously opened sections close. 
 
### Mobile
- [ ] Reference Ryan's designs in [Zeplin](https://zpl.io/2jxORgp) and according to https://design.va.gov
- [ ] Change "More in this Section" to "In this section" (**if possible**) and move position to between the H1  and intro text. 
- [ ] Replace carat with "hamburger" icon
- [ ] Ensure menu expands down rather than to the right
- [ ] Add _$color-link-default_ stroke with rounded corners (similar to button style) around menu
- [ ] Should use good accordion ARIA markup for the mobile "On this section" button

## Acceptance Criteria

**Given a user has landed on https://staging.va.gov/pittsburgh-health-care/**

- [x] "SERVICES AND LOCATIONS", "NEWS AND EVENTS" and "ABOUT VA"" are displayed dark gray text and in all caps. 
- [ ] All other menu labels are in blue and in sentence case. 
- [ ] The menu does not include accordion carats. 
- [ ] Sections are divided on top and bottom with horizontal light gray lines which do not extend the full width. 
- [ ] Horizontal rules do not separate parent from child items.
- [ ] All menu items are clickable unless the user is on that page. 

**Given a user hovers over a menu item**

- [ ] The menu item's color remains blue. 
- [ ] The menu item has a blue border box with vertical left bar highlight. 
- [ ] The hover state behaves the same at any level. 
- [ ] If the menu item is a grandchild page, the gray vertical line is still visible. Note: this can be tested [here](https://staging.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/psychology-internships-and-fellowships/)

**Given a user clicks on an item in the left nav**

- [ ] The text of the selected item changes to almost black.
- [ ] The menu item gets an almost black vertical bar highlight on the left. 
- [ ] The item's background changes to light grey. 
- [ ] All child and grandchild pages are made visible and are indented. 
- [ ] Grandchild pages have a light gray vertical line on the left which becomes visible when the section opens. 
- [ ] Horizontal lines separating sections are still visible. 
- [ ] The horizontal lines at top and bottom of the section for the selected item extends the full width and is dark gray. 
- [ ] The horizontal lines for all other sections are light gray and not the full width  

**Given the user is accessing the page on mobile device**

- [ ] User will see navigation menu bordered by blue line with rounded corners
- [ ] User will see "In this section" displayed above the intro text 
- [ ] When user clicks "hamburger" icon, the menu expands downward 
- [ ] Buttons for "Make an appointment" "Register for care" and "Pharmacy" are stacked. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)## User Story or

**Comment by mmiddaugh** [comment]
![left nav mobile](https://user-images.githubusercontent.com/55411834/77566820-d0c06280-6e8b-11ea-989c-be469f55a882.png)

![Left Nav overall state](https://user-images.githubusercontent.com/55411834/77566829-d3bb5300-6e8b-11ea-8976-af7a6616901c.png)

![left nav states](https://user-images.githubusercontent.com/55411834/77566839-db7af780-6e8b-11ea-8814-8d81431bde11.png)

**Comment by mmiddaugh** [comment]
Description above incorporates [design](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7196) and [accessibility](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7149) feedback per the pre-usability review

**Comment by mmiddaugh** [comment]
Note: per @rtwell we will address the width of the left nav after the style changes are made.

**Comment by mmiddaugh** [comment]
Please see feedback from Design review for necessary changes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7896#issuecomment-614253889

**Comment by mmiddaugh** [comment]
508 tasks have been moved into a separate issue [#8145]
