### ISSUE TITLE
Hover state Left Nav Upgrade

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7213]
## User Story or Problem Statement
As a veteran, I need the left nav to indicate which page I am on so I can more easily navigate to the content I am searching. 

## Goal
Provide active state styling consistent with the rest of VA.gov

![image](https://user-images.githubusercontent.com/55411834/77554654-f80f3380-6e7b-11ea-944c-2243b1bd8abe.png)

## Objectives or Key Results this is meant to further
OBJECTIVE 3: Deliver a usable and accessible experience

---
## Tasks
- [ ] Develop "Hover" state consistent with Ryan's design (shown above), in [Zeplin] (https://zpl.io/2jxORgp) and according to https://design.va.gov/components/sidenav
- [ ] Add border box around selected nav bar item with vertical left bar highlight in **COLOR**
`
## Acceptance Criteria
- [ ] When a user hovers over an item from the left nav, the menu item's color does not change. 
- [ ] When a user hovers over an item from the left nav, the menu item is highlighted with border box and vertical left bar in **COLOR**
- [ ] Screen readers read the words (rather than spelling out letters.)
- [ ] Consistent with Ryan's design (shown above), in [Zeplin] (https://zpl.io/2jxORgp) and  https://design.va.gov/components/sidenav

**Comment by mmiddaugh** [comment]
closing as duplicate
