### ISSUE TITLE
[CST] Updates to claim details subheading

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#72134]
## Background
Need to make a few adjustments to the claim details subheading that we just added recently:
1) Change the font-family to a sans-serif one
2) Generate the heading text outside of the JSX so that voiceOver will read it correctly

**Note:** To use a san-serif font-family instead of a serif one, we can apply this css utility class: `vads-u-font-family--sans` to the element

### Current
<img width="669" alt="Screenshot 2023-12-18 at 12 24 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/dcb66728-9b3f-46dc-b71d-ebff51cb8a27">

### Spec
<img width="774" alt="Screenshot 2023-12-18 at 12 04 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/6ef98435-dcbb-4b96-a703-415aff6d386a">

## Tasks
- [ ] Update the font-family to a sans-serif one
- [ ] Move heading text generation to a variable outside of the JSX

## Acceptance Criteria
- [ ] The subheading uses a sans-serif font
- [ ] The subheading text is generated outside of the JSX

**Comment by pmclaren19** [comment]
Hey @skylerschain just merged the changes for this ticket and they are now in Staging. Please verify everything looks good when you can!

**Comment by skylerschain** [comment]
LGTM 👍
