### ISSUE TITLE
[FSR] Spouse work history navigation

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#72144]
## Description
Noticed this bug when using the new review navigation. 
Steps to recreate:
 - Add a spouse with employment history (current, previous, as long as the list is populated)
- Back nav, or use review navigation to the spouse employment question page
- Leave "yes" selected, hit next
- User is directed to the employment dates page when they should be routed to the summary page since there are exisitng jobs. 

Noticed the `nextPage` is not firing in `SpouseEmploymentQuestion` so the page navigation is a little off. 

## Tasks
- [x] Identify and fix spouse work history navigation issue

## Acceptance criteria

- [x] Users are routed from the spouse employment history question to summary page if they have already entered employment history. 

## Testing
- [x] Test that users are routed from the spouse employment history question to summary page if they have already entered employment history. 

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
Able to reproduce, still looking into a fix

**Comment by amponce** [comment]
PR submitted https://github.com/department-of-veterans-affairs/vets-website/pull/27322
