### ISSUE TITLE
Qualitative feedback analysis: Nov 1 thru Dec 15

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#72143]
### User story

As a Cartographers team member, I want to analyze the qualitative survey responses, so that we can learn from it.

### Notes

- How to request medallia feedback:
  - Go to the [issue template list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose) and select "Qualitative data request"
  - Fill out the form. Here's [an example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68830) 
- Where to store analysis:
  - Spreadsheet in the team Sharepoint
  - Findings in Github alongside [earlier analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/Medallia-feedback-analysis.md) (team needs to consider the IA of these analyses to scale going forward)

## Acceptance criteria

- Saved lightweight analysis of both quant and qual survey responses in Github
- Documented any insights in this ticket or new ticket(s) if appropriate

## Tasks

- [x] Request Medallia data for timeframe listed in ticket details above
- [x] Add new data to spreadsheet in the team sharepoint as a new tab
- [x] Scale GH page IA to account for multiple rounds of Medallia data 
- [x] Add in data analysis for new timeframe (11/1/23-12/15/23) to GH page

**Comment by sterkenburgsara** [comment]
Update: requested data on 12/20. [Ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72360).

**Comment by sterkenburgsara** [comment]
Update: edited GH page to hopefully scale better for future Medallia data analysis, incorporated new data into tables.  Analysis complete. 

@wesrowe A surprising number of qualitative responses surrounded users who created net-new Login.gov accounts because of recommendations on Va.gov, but were told they are "unable to access" MHV on VA.gov once they did so. We should pass this on and see if anyone knows what is going on there.

**Comment by wesrowe** [comment]
@sterkenburgsara, thanks for adding the tables! it's a little unclear which parts of the analysis (outside of the tables) were updated based on the latest round. 

also, could we track insights like the comment above (and the resulting ticket) somewhere in the doc?
