### ISSUE TITLE
[FE] - Add new appointment kind icon and labels in upcoming list

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#72163]
## Description
We cover phone and clinic currently, we need to add VVC and CVT.

## Wireframes
- [Sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

## Tasks
- [ ] [FE] - handle VVC and CVT
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
