### ISSUE TITLE
Collaboration Cycle for IIR Team, Yellow Ribbon Program, Yellow Ribbon Website Content

### ISSUE THREAD

**Issue by Lkahler67** [department-of-veterans-affairs/va.gov-team#72171]
### VFS team name

IIR Team

### Product name

Yellow Ribbon Program

### Feature name

Yellow Ribbon Website Content

### GitHub label for team

va-iir

### GitHub label for product

yellow-ribbon

### Public DSVA Slack channel for VFS team

#iir-product-teams-public

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

11/13/2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://docs.google.com/document/d/1qzVrA1mj6_gobz1m1-ijDe1n_edwVMMgwEmjlalmhZw/edit

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C05RJS5DANT/p1702934241471389?thread_ts=1702934238.763709&cid=C05RJS5DANT)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] User flow (required) [Figma Link to Current and Proposed Flows](https://www.figma.com/file/8OqbsVv02OlqQYktiVYsV8/Yellow-Ribbon-Content?type=design&node-id=0%3A1&mode=design&t=u77oK753YCAhCPhx-1)
- [x] Whiteboard sketch or other lo-fi prototypes or wireframes [Figma Link to Proposed Prototypes](https://www.figma.com/file/8OqbsVv02OlqQYktiVYsV8/Yellow-Ribbon-Content?type=design&node-id=0%3A346&mode=design&t=u77oK753YCAhCPhx-1)
- [ ] Research plan
- [x] Any other artifacts you have so far
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05RJS5DANT/p1704465212632339) 
- [x] Meeting date/time: Friday, January 12, 2024, 11:30am - 12:00pm Eastern
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/nprR7_58GwTf5NhCwE-8eU9ArDBmKjMcjfZKtpDPjBHZz_5WyKLFeUWlFy8dwpLM.Cv7YHZZUPh5qMHFs)
  - Passcode: `H3vQ@p!Y`
 
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Architecture Intent
<details>
  <summary>Toggle Architecture Intent instructions</summary>

##### VFS team actions
- [ ] Review [Architecture Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent) to understand what this touchpoint involves.
- [ ] Schedule your Architecture Intent (with at least 2 business days lead time from now):
  - Open the [Calendly Architecture intent calendar](https://calendly.com/collaboration-cycle/architecture-intent)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Architecture Intent artifacts for review` section below at least two business days before the scheduled Architecture Intent. Please don't add artifacts in the comments section.
  
**Architecture Intent artifacts for review**

[See guidance on Architecture Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent#ArchitectureIntent-Whatartifactswillbeneeded?) Feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] Fully completed [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md)
- [ ] [User data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md), if your application accepts data from a user.

##### Platform Team actions
- [ ] Meeting date/time:

##### Platform Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Mobile Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Security feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback  

##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
</details>

### Midpoint Review

<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [ ] Design prototype or high-fidelity mockup (must include mobile prototype/mockup)
  - Specify which pages are included in the review
- [ ] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), link to CAIA intake ticket. 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
 
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

* Accessibility
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode: 
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

#### Required artifacts
  - [ ] **URL(s) to review the product**
    - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
    - List pages, sections of pages, and/or user flows impacted by this work.
  - [ ] **Drupal or Staging URL for updated primary entry point**: the main way Veterans will access the tool through site navigation (not search)
  - [ ] **Test users and scenarios (when applicable)**
    - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a `.md` file in the va.gov-team-sensitive repository. 
    - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
  - [ ] **Link to Sitewide CAIA intake ticket, if applicable.**
  - [ ] **Completed accessibility testing artifact**: [see instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  - [ ] **QA Artifacts**: artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
    - [ ] Regression test plan
    - [ ] Test plan
    - [ ] Coverage for References
    - [ ] Summary (Defects) reports
    - [ ] E2E tests
    - [ ] Code coverage
    - [ ] Endpoint monitoring playbook

#### Not required, but nice to have artifacts
  - [ ] **Content source of truth**: link to CAIA Content feedback, such as a content source of truth.
  - [ ] **Information Architecture spec**: link to CAIA IA feedback, such as an IA spec.
##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording link 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

**Comment by Lkahler67** [comment]
[Initiative Brief [Yellow Ribbon 2024] - Google Docs.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/14435863/Initiative.Brief.Yellow.Ribbon.2024.-.Google.Docs.pdf)

**Comment by shiragoodman** [comment]
@mcommons10 @kingbmike do either of you know if this work is still in progress? Just checking in since it's been some time since there was last movement on the ticket.

**Comment by mcommons10** [comment]
Hi @shiragoodman - thanks for checking! We are no longer working on this project so this can be cancelled cc: @oddballpete
