### ISSUE TITLE
Tracking ticket: Benefits (526) Submit Uploads Success Percentage on Dec 17th

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#72178]
Benefits (526) Submit Uploads Success Percentage alert was triggered on Sunday December 17th at:

- triggered at 12:28 am
- recovered at 12:36 am
- triggered again at 4:425 am 
- recovered again at 4:39 am 

Then on Monday at:

- triggered at 3:13 PM
- Pending recovery at time of this ticket

Action:

 Investigation concluded that these events are due to 'sample window problem' and does indicate an actionable problem.

To close out incident we need to:

- [ ] 1. Determine if this alert is actionable and should stay on the Watch Tower list 
- [ ]    a. If actionable we need to fix Sample Window error
- [ ] 2. If not actionable or covered by another alert then remove from Watch Tower list
