### ISSUE TITLE
Add Atlas doc links to VFS Docs

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#72184]
## Issue Description
Update the VFS documentation we have to point to the Atlas docs

---
## Tasks
- [x] Add links to [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2798846283/VFS+Roster+Management) from [this page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2806841369/Atlas+User+Manual)
- [x] Submit for review to Alyssa Gallion

## Acceptance Criteria
- [ ] Confluence docs are up to date with links to current process for adding new VFS Teams and Team Members
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@alyssagallion please review
