### ISSUE TITLE
Reopen Ticket Button in Slack Channel Ticket Threads

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72185]
## Description 
We currently have the ability to close a ticket from our Slack Channel threads. However, we have had a few instances when the need to reopen the same ticket was necessary. @CBonade will need to investigate what options we have here.

---

## Definition of Done
All tasks below are completed.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Joe/Curt to work together to identify what items need to be completed to implement this feature
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)

- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
No use case for this, happens infrequently. Closing.
