### ISSUE TITLE
Update Find a Rep product documentation with new MVP scope

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#72183]
## Background
We decided not to launch our MVP due to issues with data accuracy.  While we define a plan to update the OGC accredited rep database, we have decided to expand our MVP scope to add solutions to the data issue on the product end, in addition to incorporating findings from research.  Essentially, our "v2" becomes the expanded scope for our MVP.

## Tasks
- [x] Update [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/product-outline-find-a-representative.md)
- [x] Update [MVP doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/mvp-find-a-representative.md)
- [x] Update [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/release-plan-find-a-representative-mvp.md) with new TBD dates (specifics can be defined closer to the release)

**Comment by oddball-lindsay** [comment]
completed, will schedule a message to alert the team in the morning tomorrow.

**Comment by oddball-lindsay** [comment]
We have decided to instead call this version 2.0, as opposed to a new MVP with new scope.  documentation has been updated to reflect this.
