### ISSUE TITLE
vets-api: Remove disability rating

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#72189]
### Summary
Turns out we did not need to migrate the eMIS calls for disability rating information to VA Profile. We need to undo that work since it's dead code now.

### Tasks
- [x] Undo all of the changes in https://github.com/department-of-veterans-affairs/vets-api/pull/14205
- [x] Instances where the disability cassettes were used (in form_profile_spec and maybe other places) will need to be removed.
- [x] Undo changes in https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2345
- [x] Undo changes in https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2346

### Acceptance criteria
- [ ] No Argo environments are failing. 
- [x] No tests failing

**Comment by rmtolmach** [comment]
Vets API PR
- https://github.com/department-of-veterans-affairs/vets-api/pull/14927

Manifest PRs
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2522
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2521

**Comment by rmtolmach** [comment]
All PRs merged. Closing.
