### ISSUE TITLE
vsp-infra-application-manifests: Remove eMIS references

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#72190]
### Summary
As part of the code deletion for eMIS, we'll need to delete eMIS references in [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) repo 

A quick search shows 65 results in 11 files. 

This will likely need to be done in two PRs: One for lower envs and one for Prod. 

### Tasks
- [x] Delete references in lower envs
- [x] Delete references in higher envs
- [x] Delete any emis parameters from AWS Parameter Store that were deleted in the code.

### Acceptance criteria
- [x] All references to eMIS in manifest repo are gone
- [x] Parameters deleted from manifest repo are deleted in param store. 
- [x] ArgoCD environments sync without errors after code is merged.

**Comment by rmtolmach** [comment]
PR for lower environments: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2565

**Comment by jennb33** [comment]
Rebecca will merge this on 1/16, lower environment PRs have been approved by Rachal and Gia

**Comment by jennb33** [comment]
This ticket is moving into the next sprint, per @rmtolmach, for more work to be done before it is considered complete.

**Comment by jennb33** [comment]
In process with Rebecca 1/17/2024

**Comment by rmtolmach** [comment]
More PRs:
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2606
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2607

After these are merged _and deployed_, I will delete the values from parameter store.

**Comment by rmtolmach** [comment]
PRs are merged and verified. I will delete parameters on Monday.

**Comment by rmtolmach** [comment]
I deleted these from parameter store:
```
/dsva-vagov/vets-api/dev/emis_host
/dsva-vagov/vets-api/dev/vet_verification_mock_emis_host
/dsva-vagov/vets-api/staging/vet_verification_mock_emis_host
/dsva-vagov/vets-api/sandbox/emis/host
/dsva-vagov/vets-api/sandbox/vet_verification/mock_emis_host
/dsva-vagov/vets-api/prod/vet_verification_mock_emis_host
/dsva-vagov/vets-api/prod/emis_host
```
Closing! 🎉
