### ISSUE TITLE
devops: Remove eMIS references

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#72197]
### Summary
As part of the code deletion for eMIS, we'll need to delete eMIS references in [devops](https://github.com/department-of-veterans-affairs/devops) repo. 

This includes deleting an alert if eMIS is down. I don't think we have any similar alerting if VA Profile is down. An alert will need to be created for VA Profile availability in Datadog (and Terraform). Do that as part of this ticket or make a new ticket.

### Tasks
- [x] Delete references (split into two PRs)
  - [x] Lowers environments
  - [x] Prod and sandbox 
- [x] Determine if we need an alert for VA Profile availability. 
- [x] If we do, make new alert in Datadog (and terraform)
  - [x] Alert needs to be actionable or or say that no action is required. 
- [x] Delete any AWS parameters removed in code (devops certs)

### Acceptance criteria
- [x] All references to eMIS in devops repo are gone (except pagerduty-related ones)
- [ ] Any environments that were impacted are operating smoothly (revproxy is deployed weekly on Wednesday. Forward proxy is deployed daily. Check for the dd modifications in Datadog UI.)
- [x] If appropriate, a new alert for VA Profile availability is created in datadog and terraform (terraform is applied)
- [x] Relevant AWS parameters removed

**Comment by LindseySaari** [comment]
Rebecca will need a devops review from a team member!

**Comment by rmtolmach** [comment]
PR: https://github.com/department-of-veterans-affairs/devops/pull/13860

**Comment by rmtolmach** [comment]
PR for alert modifications: https://github.com/department-of-veterans-affairs/devops/pull/13862

**Comment by jennb33** [comment]
Pending DevOps review by @flooose and @Kshitiz-devops - Chris will probably complete the PRs.

**Comment by jennb33** [comment]
In progress with Rebecca 1/17/2024

**Comment by rmtolmach** [comment]
More PRs:
- https://github.com/department-of-veterans-affairs/devops/pull/13895
- https://github.com/department-of-veterans-affairs/devops/pull/13896

**Comment by rmtolmach** [comment]
PRs are merged. I will delete parameters on Monday.

**Comment by rmtolmach** [comment]
deleted from param store:     
   /devops/certificates/vaausvrsapp81.aac.va.gov.key
    /devops/certificates/vaausvrsweb20.aac.va.gov.key
    /devops/certificates/vaausvrsweb40.aac.va.gov.key

The crts were not in param store.
