### ISSUE TITLE
[spike] DR | Review failed evidence uploads caused by temporary platform AWS issue

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#72199]
On Dec 18th, after the daily deploy, our evidence submissions to Lighthouse began failing. See [Slack alert](https://dsva.slack.com/archives/C05UPRR0HK3/p1702930807830609). It looks like there were roughly 30 failures. See [DataDog](https://vagov.ddog-gov.com/metric/explorer?graph_layout=stacked&start=1702928421652&end=1702940257780&paused=true#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgViBpOGPIQAHQaCJ4aUM1gbgDWOk4CmRAakiJORhV6YGl4AEaq4k548mg4GFCzmdkaGsAAVDzNGPWZ+CIIABQAlCB8oJHRubFYAEyJye1pGdnK+YXFEAvcpVGp1BpNVrtCxdHrafraQZwYajKQTOBTOAzDTzRYIZardabRTuDAiOAXJw6bRuA5HE5OM54C43O4AXSornceEwoXCbSwaByoHkGCFCAQORAMCMFMSovFkqcogEpGQABY+CAuaoeRgYqV4ncKKABUKZCAFYhJcowBh3PKxda4MqRKqUABWLU6vUGnRvdlUM3Cy1OiVSqA4GCM3mjTKJNCiF1yRTKdKJqAJpNOehMZQiNweNDGpIjVbYJwpqVze2WHhsnha+yJhAAYSkwhgKBEPLQPCAA). This was caused by a platform issue, which platform resolved by reverting. See [Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1702931321340939). 

These roughly 113 cases are cases where a Veteran successfully submitted their form, but then their evidence submissions failed, asynchronously, thereafter. We will need to identify these failed evidence submissions and then manually re-submit them.

## To-do:
- [x] Figure out claim types => SC
- [x] Figure out how to rehydrate logs assuming it will help us find out who those affected Veterans are (alternatively, we could run database query to find unsubmitted evidence uploads)
- [x] Figure out orphaned / not orphaned => not orphaned
- [ ] Then create follow-up ticket(s)

**Comment by saderagsdale** [comment]
@data-doge Thanks! Can you confirm which forms (SC, NOD) experienced the evidence submission failure?

**Comment by saderagsdale** [comment]
Note: Remediation path will be different depending on the form affected. Need to talk to the enablement team about refining the remediation process for transient errors or getting platform to prioritize them.

**Comment by HeatherWidmont** [comment]
Move to next sprint because this is not a dependency for the NOD infinite loop email work

**Comment by anniebtran** [comment]
All of these failures were SC so we aren't bound by the 90 day limit and these cases may have already been resolved by VA employees. We'll touch base at next standup

**Comment by saderagsdale** [comment]
Thanks @anniebtran! I have not sent any comms related to this issue to VBA, aside from flagging it for awareness. Is there a link to any communications that suggest someone from VA has triaged these? We'll need to verify that or plan to send it ourselves.

**Comment by data-doge** [comment]
@saderagsdale We haven't received any communications from VBA - though I vaguely remember hearing about a manual process where VA would reach out to Veterans who did not submit evidence with their SCs. I may be misremembering that though. Would be nice to chat through that with you at standup or whenever. We _may_ also have the ability to manually submit this evidence ourselves, but we'll hold off on pursuing that possibility until we've chatted with you.

**Comment by saderagsdale** [comment]
Got it. We'll want to send them the list of SC submissions and see what the status of each one is.

**Comment by anniebtran** [comment]
Just so it's documented somewhere — I created a spreadsheet of affected SC submissions is in Sharepoint and shared it with Sade so we can follow up when we're ready to shift focus to this 👍

**Comment by saderagsdale** [comment]
Check ancillary forms. (5103, 4142/a, evidence, and SC)

**Comment by anniebtran** [comment]
@saderagsdale I unfortunately can't check for 5103 acknowledgement on these records because the form data has been cleared out in the LH records (I'm not sure how long they keep that data around for SC submissions). Also seems that for 4142, we're submitting directly to Central Mail and I'm not seeing any records in our database that serve as any kind of receipt for it, but we do have logging/monitoring for the 4142 submission job and would've been alerted if the job/retries failed for this submission and I'm not seeing any. @data-doge let me know if I'm missing any context here or if you have other ideas for checking on these ancillary forms.

**Comment by anniebtran** [comment]
Chatted with Eugene a bit about this and I think we've reached the limit of what our team can look into on this — Central Mail might be able to locate those 4142s and I would imagine they'd also be able to check on the 5103. @saderagsdale anything else you want me to look into?

**Comment by HeatherWidmont** [comment]
Deprioritizing this in favor of other work this sprint. Moving back to the backlog

**Comment by anniebtran** [comment]
These are all covered by the current remediation effort and are included in the spreadsheet sent to VBA
