### ISSUE TITLE
Update 'Submitting Pull Request for Approval' Doc

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#72207]
## Description:
This ticket is to add the following additions on the _[Submitting Pull Request for Approval](https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval)_ doc

- **Existing Page:** [Submitting pull requests for approval]( https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval)
- **Updates/New Content:** [After a Pull Request is submitted:](https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/edit-v2/2873983012?draftShareId=ad941c01-a6a9-4695-980a-f576d762a79a)

## Tasks:

- [x] Review content additions on [this page](https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/edit-v2/2873983012?draftShareId=ad941c01-a6a9-4695-980a-f576d762a79a).
- [x] Reach out to Isaiah White if there are any questions
- [x] Add changes to the end of this page,  [Submitting pull requests for approval]( https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval)
- [x] Request approval from someone on Support Team, (likely Alyssa)
- [x] Prepare page for deployment

## Acceptance Criteria:

- [x] New content has been reviewed, and edited (if needed)
- [x] Page has been deployed with updates)

**Comment by laucon** [comment]
@IsaiahMW1 Hello! I have some questions about this [document](https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/edit-v2/2873983012?draftShareId=ad941c01-a6a9-4695-980a-f576d762a79a) that I wrote inside of comments. Can you answer them for me? Thanks!

**Comment by johnny-jesensky-adhoc** [comment]
@johnny-jesensky-adhoc - to reach out to Alyssa to provide an initial review on this.

**Comment by johnny-jesensky-adhoc** [comment]
This page was deployed - meets all of the AC, so moving to _Done_. If we need to tweak, can look to do so in an upcoming sprint.

@jknipes  - given the robustness of the changes on this document, this might be worth calling out in next week's ToT.
