### ISSUE TITLE
vets-website: Remove eMIS references - Investigation & Discovery

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#72209]
### Summary
As part of the code deletion for decommissioning eMIS, eMIS references (code, comments, etc.) in [vets-website](https://github.com/department-of-veterans-affairs/vets-website) repo will need to be deleted. Since this is vets-website code, this might be out of our scope. 

A quick search showed 82 results in 42 files. 

### Additional Info
This eMIS removal was originally attempted in one PR here - https://github.com/department-of-veterans-affairs/vets-website/pull/27743
Unfortunately, a number of E2E specs occurred without a clear indication of the cause. After discussing with Frontend CoP, the best course of action forward to determined to be creating a new branch for the effort with a commit for each individual file changed to properly identify the source of the E2E failures.

### Tasks
- [x] Find all references to eMIS in vets-website repo (document via inventory)
- [ ] Attempt to delete all references and make note of failing specs that may require additional work
- [ ] Develop additional tickets for removing all eMIS references while passing all unit & E2E tests 
- [x] Develop a line of communication with frontend CoP to determine a course of action to complete this task

### Acceptance criteria
- [x] Attempt to remove all references of eMIS and determine the cause of failing specs

**Comment by rmtolmach** [comment]
Curt suggested one of us (Product team) do it and get a thorough review from the FE CoP. I assigned Ryan since he leans more toward the FE than the rest of us.

**Comment by jennb33** [comment]
@rmtolmach can we please get clarification on what references means - code and comments?

**Comment by jennb33** [comment]
@rjohnson2011 went through the environments and test suites. Will continue a global search for eMIS and repoint to the VA Profile Redis and to build that out. Made modifications to the breaker/DataDog. 
Regard to the failures, he reviewed.
Did the environmental variables.

**Comment by jennb33** [comment]
This ticket will have to be reviewed by FE team. @rjohnson2011 is not sure if he has deploy permissions to the environment that it needs to go to. He thinks it will be done by Wednesday. This ticket will roll to the next sprint because of the work that needs to be done for review and deployment.
