### ISSUE TITLE
PagerDuty Discovery: Remove and replace eMIS references

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#72202]
### Summary
This is a discovery ticket.
As part of the code deletion for eMIS, we'll need to remove the eMIS service from [PagerDuty](https://dsva.pagerduty.com/service-directory?direction=desc&query=emis&sort_by=score&team_ids=all). This is used for maintenance windows. We'll also need to update any mappings from PagerDuty services to features for the frontend maintenance window/banner logic. Here's some more information on that. These are Patrick V's works, taken from [Slack](https://dsva.slack.com/archives/C04CYC4LMU6/p1701968583490099?thread_ts=1701889162.054999&cid=C04CYC4LMU6):

- There are services configured in pagerduty for many of our upstream dependencies, including eMIS. When one of them has downtime (planned or otherwise), we set a pagerduty maintenance window on that service to indicate its state.
- vets-api periodically polls pagerduty to discover any currently configured maintenance windows, and then exposes these via the /v0/maintenance_windows API endpoint.
- There's a mapping in vets-api settings under pagerduty > services  that maps from the pagerduty service ID to a logical name (in staging: `emis: PB6MPB5`)
- Then somewhere in the vets-website code there's a banner widget that different applications can use to display a downtime alert, based on what they get from that v0/maintenance_windows API. They have to know which upstreams affect them, e.g. sign-in shows a banner if ID.me or [Login.gov](http://login.gov/) or MPI is down.
- So somewhere in the frontend, there may be applications that are saying "if EMIS is down, show an alert to the user.

So to fully unwind that:
- Remove the pagerduty services for EMIS (prod and staging versions)
- Clean up settings.local.yml mapping for emis in the pagerduty stanza (though there's also no real harm if this sticks around)
- Determine if any frontend applications think they need to show a downtime banner based on status of EMIS, and swap them to be based on VAProfile (possible frontend teams like authd experience have already done this?) (Could this be determined by which services have used eMIS to create a maintenance window?)

### Tasks
Document how to do the following:
- [x] Understand and document how eMIS is used in PagerDuty and for maintenance windows
- [x] Based on what PagerDuty eMIS things needs deleting, determine if they need to be replaced with VA Profile, or if they already have been and document. 
- [x] Document what eMIS references need to be removed and replaced OR make new tickets based on discovery.

### Acceptance criteria
Document the following: 
- [x] If VA Profile exists as a "Service" in pd
- [x] links to where eMIS needs to be removed as a Service in pd
- [x] Where pd references for emis should be replaced in vets-api
- [x] new tickets are opened to cover anything not done in this ticket

**Comment by RachalCassity** [comment]
Do not see the EMIS service in PagerDuty. Are we sure this exists?
