### ISSUE TITLE
Establish initial Domo dashboard for Satisfaction Survey data

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#72235]
## Purpose
We recently learned that Airtable wasn't allowed behind the VA network wall.  Survey Monkey is supposed to be. BUT then we learned that is not; our available option is Optimal Workshop, which allows surveys ([called Questions](https://support.optimalworkshop.com/en/collections/1524596-questions) for some reason).

What would be involved in, and how could we, use Optimal Workshop for the quarterly Platform Satisfaction Survey and get the data into a tool such as Domo for actionable data visualizations?

Documentation on OW access [here](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-OptimalWorkshop) and use on Platform.

## Tasks
- [x] Determine process for getting OW survey data into Domo
- [x] Document proper formatting of the spreadsheet for Domo purposes
- [x] Document any other important related steps (timelines, links/mentions to other survey pages, etc)
- [x] Explore QoQ dashboard views
- [x] Share [Domo dashboards](https://va-gov.domo.com/page/2036772922?userId=1373762689) with SDT for discussion
- [x] Refine dashboards based on feedback

## Acceptance Criteria
- [x] Satisfaction Survey Domo dashboards are available and accurate
