### ISSUE TITLE
Dynamic EC2 DNS for Socks

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72236]
## Description
Implement dynamic DNS for EC2 instances in the SOCKS environment to enhance accessibility and management.

---

## Tasks
- [x] Assess current DNS configuration for SOCKS-related EC2 instances.
- [x] Develop a solution for dynamic DNS updates as EC2 instances are created or terminated.
- [x] Integrate dynamic DNS updates with the EC2 lifecycle.
- [x] Test DNS updates to ensure consistency and reliability.

## Acceptance Criteria
- [x] Dynamic DNS is successfully implemented for SOCKS-related EC2 instances.
- [x] DNS updates accurately reflect changes in EC2 instances.
- [x] The solution is tested and verified for reliability and consistency.

**Comment by ben-allen-oddball** [comment]
Carrying over.  Dyanmic DNS working for review and preview instances.  Working through dynamic DNS forwarding issues and other outliers (Prometheus, Sentury, nessus, jenkins, grafana, etc.)

**Comment by ben-allen-oddball** [comment]
Carrying over.  Dyanmic DNS working for review and preview instances.  Working through dynamic DNS forwarding issues and other outliers (Prometheus, Sentury, nessus, jenkins, grafana, etc.)
