### ISSUE TITLE
Shadowing Research: Interview Sessions (Part 3)

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#72231]
## Issue Description

This ticket documents the interview sessions being conducted over the course of a sprint. 

We're doing interview sessions for [Veteran Shadowing Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2023-11-Shadowing-Research) that we are conducting in order to better understand the end-to-end experience of 526 completion. 

As anticipated, qualified participants (Veterans who have never filed online) have been difficult to identify in the Perigean database. 

We are 1 participant away from our target goal of observing 5 participants work on the form. We extended the study last sprint and are working closely with Perigean to schedule our final sessions during this sprint. 

First interview ticket is [here](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/69213)

Second interview ticket is [here](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/69213) 

---
## Tasks
- [ ]  Conduct or take notes for interview sessions, 2 hours each 
- [ ]  Nichole is point for sign-up, scheduling, and Sharepoint data management
- [ ]  Evelyn is point for Perigean communication 

## Acceptance Criteria
- [ ]  Interviews are complete
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
DBEX Team 2 completed the final session while I was OOO. This ticket is no longer needed.
