### ISSUE TITLE
[Design] Create Final Wireframes in production Sketch file for confirmation pages to use pattern from unified check in experience's confirmation pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72243]
## Description 

30 sites have said that they're marking Veterans as "no shows" who have checked in, because they call them when they check in vs. calling them when it's their appt time or up until 15 mins after their appt time. 

## Tasks
- [ ] Create final wireframes in [production Sketch file](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/A6E73D11-A95C-4EC0-A3B7-792CE5799C59/canvas) for all of the check in completion pages to [use the new pattern used in Unified Check In](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas). Totals 7 artboards. 
- [ ] Update [content on confirmation pages to use content that Kelly is rewriting](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72247). 
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Going to close this for now. If engineers need changes next sprint, we can make those changes or create tickets if needed. 

https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=0%3A1&mode=design&t=io3sIn7j2bWpf9gr-1
