### ISSUE TITLE
[Content] Create Content to tell Veterans to see staff at their appt time if they haven't been called back yet

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72247]
## Description 

30 sites have said that they're marking Veterans as "no shows" who have checked in, because they call them when they check in vs. calling them when it's their appt time or up until 15 mins after their appt time. We should attempt to make it clear to Veterans to report to the waiting room after completing check in and check with staff if they haven't been called at their appt time. 

## Tasks
- [x] Edit content to tell Veterans to see staff at their appt time if they haven't been called back yet. (Applies to [our confirmation pages](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas).) Note: This change will be made in production first. 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [x] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [x] Yes
- [ ] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [x] Work was reviewed by groups indicated above
- [x] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 [I mocked up some ideas in a separate figma file](https://www.figma.com/file/srDWp4SOHIdmzS2PJHy9uQ/Wait-more-than-15-minutes---72247?type=design&node-id=0%3A1&mode=design&t=TPCf3D0ueeuZy7SZ-1) (I didn't want to mock them up in the production figma or sketch files as those are publicly shared) but it's easy to move the mockups into whatever file we want later. As I mentioned to you, I mocked up 3 possible options, starting with the text message and login page to make it more explicit to wait until you're in the facility to start the process. I mocked up 1 with "waiting room" but we've been asked before to avoid using that term, so we'd want to run it past... someone... and I changed the 15-minute content. You have editing rights on the figma file - let me know what you think. In my humble opinion, adding information at the end saying "we hope you didn't do this before you were in the facility cause we may have already marked you as a no-show" doesn't make sense -it's better to get the Veteran's attention first to prevent them from doing the check-in until they are in the facility. 
I also included some background about how no-show appointments work and why it's so very important that the Veteran doesn't get  marked as a no-show for something that the MSA did incorrectly.

**Comment by kellysmith1008** [comment]
Pulled this back into "in progress" as I'm still finessing the language. I put a proposal in figma this morning - assuming it doesn't need additional tweaking, I think we can either move it back to validate or close it.

**Comment by kellysmith1008** [comment]
Collaborated with Ben, Lori, and Kristen this morning and landed on the new content. @loripusey [here's a link](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=177%3A543&mode=design&t=x2GQIDHxawbLMpNR-1) to the specific figma design with the content. Going to close this ticket.

**Comment by benbrasso-agile6** [comment]
Nice work!
