### ISSUE TITLE
[FE, QA] 10-10EZ - Facility Selection: QA Facilities API functionality

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72257]
## Background
The static list used today is very outdated and causing issues for Veterans who are completing the 10-10EZ form.
We have connected to the Facilities API in lower level environments with success, and need to implement this functionality in Production.  This will allow a dynamic list of facilities to populate a dropdown menu, which will always be a current list and remove the manual maintenance from the 10-10 team.

This is an interim fix of the static list issue.  We have plans to redesign the facilities selection page to include a more dynamic search functionality, also built for the 10-10cg form.

## Tasks

- [x] FE - Ensure we are sending the same information downstream to Enrollment system, as we did prior to this fix
- [x] QA/PM - Review facilities in Staging with facilities on Facility Search page to ensure we are pulling the correct facilities
- [x] QA - Run a few tests, coordinating with Joshua Faulkner to ensure they are receiving the correct data
     - Specific facilities must be used for E2E testing due to Enrollment system constraint, confirm with Joshua F

## Acceptance Criteria
- Facility selection page on the 10-10EZ will use the current Facilities API to display the facilities within the state selected by the Veteran.

**Comment by fbonds** [comment]
Spot checking second task: comparing facility results to [Facilities Search Page](https://staging.va.gov/find-locations) for random selection of states (5)

**Comment by fbonds** [comment]
Submitted issue to Lighthouse regard discrepancy between what we're displaying and available VA clinics in Kansas (yesterday)

"Hi our Application built for va.gov accesses the following uri to get a list of VA medical facilities in Kansas.

/v1/facilities/va?type=health&per_page=100&state=KS

Which returns:
Colmery-O'Neil Veterans' Adminstration Medical Center
Dwight D. Eisenhower Department of Veterans Affairs Medical Center
Robert J. Dole Department of Veterans Affairs Medical and Regional Office Center
Paola VA Clinic
Fort Riley CBOC
Shawnee VA Clinic

but omits all these other open VA clinics in Kansas:
Dodge City VA Clinic
Fort Scott VA Clinic
Hutchinson VA Clinic
Junction City VA Clinic
Wyandotte CBOC
Lawrence VA Clinic
Parsons VA Clinic
Salina VA Clinic
Overland Park Radiation Oncology VA Clinic

Could you help us to understand why this is happening?"

Awaiting their reply

**Comment by fbonds** [comment]
The mismatch in results for Kansas seem to be a mismatch in product, not in stage.  Our update in Stage actually is reporting correct result set.  I am unable to reproduce my original incorrect result set and subsequently have determined somehow I accidently was testing prod.  Marking this step as complete.

**Comment by fbonds** [comment]
The next task for QA on this ticket (re: Check submission with JF) seems to be blocked by issue arising in [Slack thread](https://app.slack.com/client/T025UGMV9/C04AV6HGVD0)

**Comment by fbonds** [comment]
Verified Facility selection through application submittal with Joshua Faulkner in stage for the following users:
Neil Armstrong
Spokane VA Mobile Clinic - Washington
Michael Collins
Toledo VA Clinic - Ohio
Buzz Aldrin, Jr
Southeast Washington VA Clinic - DC

QA tasks complete

**Comment by hdjustice** [comment]
Great, thank you @fbonds !!

**Comment by hdjustice** [comment]
Chapley to add a comment here with next steps, Heather to create ticket

**Comment by jadon1979** [comment]
The issue here is that Validations for EZ are handled through vets-json-schema.  The validation checks preferred facility against an enum (list) of facilities in the schema.  Lighthouse supplies more facilities than we have in the enum so any selected facility from lighthouse, that is not in the schema, will trigger a validation failure.  

We need to update vets-json-schema to look explicitely for a string rather than an enum.  
Afterwards we will update vets-website with the new vets-json-schema version number and remove the facilities API feature flag.  
Vets-json-schema will need to be deployed. followed closely by vets-website.
