### ISSUE TITLE
Discovery Ticket - Copay Statement 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#72253]
## Issue Description
VHA have posed a few questions about the copay statements that we are providing in the debt portal.  This ticket is to review the details we are showing for the medical copay statements 

---
## Tasks
- [ ] Discovery work to answer the following questions: 
- Where are medical copay statements coming from? (Which API)
- How frequently are we receiving updated statements from that API?
- What is the date range of the statements being displayed in the portal? (is it 

## Acceptance Criteria
- [ ] Have a general understanding of the copay statements coming into the portal to answer above questions and provide any other context that would be helpful.
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asmithgovcio** [comment]
> Where are medical copay statements coming from? (Which API)

From what I can see this is handled in the vets-api codebase which calls a service to VBS, it looks like there's a VBSAPI however I don't think I have access to it. I don't see it listed under the repositories under the VA GitHub. The method being called that I want to dig into is `/vbsapi/GetStatementsByEDIPIAndVistaAccountNumber` which accepts two arguments `      data = { edipi: '123456789', vistaAccountNumbers: [36_546] }` but doesn't seem to take a date range. 

> How frequently are we receiving updated statements from that API?

From what I can see the API is setup to fetch updated statements every time it's requested, so anytime a person views this section in the application. It doesn't appear to be something that happens periodically or on a regular interval.

> What is the date range of the statements being displayed in the portal?

I tried looking into the code to see if there was a date range being passed and I couldn't find one, I don't have access to the actual api method that handles this so I couldn't dig beyond what's in the vets-api. I spoke with @Dr-Pongo and he looked on the front end and didn't see any date range being passed however from his understanding the front end is filtering out results older than 6 months on most requests so we should be seeing up to 6 months of copay statements.

**Comment by Dr-Pongo** [comment]
Yeah from and FE perspective I'm _pretty sure_ we're filtering out older than six months on the front end, but we can find some time later to confirm if we need it!

**Comment by denisecoveyduc** [comment]
Thanks for digging into this @asmithgovcio  & @Dr-Pongo!  If it is part of the VBS API then we can discuss any questions with them on one of our weekly Friday calls. @HeatherRienks you likely already have but if not could you make sure Austin is included on those invites?   From a FE perspective I'd love to understand if we are filtering out and only showing Veterans six months worth of copays. I have a feeling that we may be doing that for the VBA overpayment debts but not sure that we are for the copays coming in for VHA.

**Comment by HeatherRienks** [comment]
@denisecoveyduc -yes, @asmithgovcio has already been included on the VBS | VODA weekly calls. :)

**Comment by asmithgovcio** [comment]
@denisecoveyduc @Dr-Pongo @HeatherRienks We confirmed from Micheal Mcdougle that the cbs-api is currently returning 18 months worth of copays and they have up to 3 years worth of data however there is not a date range filter being supported so we can't fetch anything older than 18 months.

**Comment by denisecoveyduc** [comment]
@asmithgovcio So does that mean that18 months of copays are showing on the portal today?  Depending on how you answer that my second follow up question will be ... is there a way we could limit that 18 months to a lesser amount of time if the business decides it is needed?

**Comment by asmithgovcio** [comment]
@denisecoveyduc From my understanding we are getting up to 18 months worth in the portal today, @Dr-Pongo confirmed he could not find any filtering on the front end taking place to limit what we see right now so it should be the full 18 months. 

For your second question there is no way currently to limit what returns from the backend, to do that properly we'd have to make a change on the vets-api and vbs-api to support passing a date range. HOWEVER @Dr-Pongo confirmed to me that its possible to create a filter on the front end to limit the data displayed, the backend would still send the full 18 months worth but the front end would only display however many months worth we want to limit it to, this solution would only work for reducing the amount of data shown, never for increasing beyond the 18 months.

**Comment by HeatherRienks** [comment]
@denisecoveyduc  to confirm timeframe with VHA. Closing ticket.
