### ISSUE TITLE
FE | Profile Hub | Remove Toggle

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72259]
## Background 

Now that we've launched the hub and it has been live for a month we need to remove the feature toggle  

## Tasks 
- [x] remove all the code tied to the toggles 
- [x] remove the toggle from the feature flipper (BE Ruby code) 

## Acceptance Criteria 
- [x] the code no longer relies on the feature toggle and we've removed the feature toggle from the list
