### ISSUE TITLE
[Figma transition] Move Sketch templates to Figma 🎉 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#72252]
## Description

Sketch licenses will not be renewed next year, and all of our work will become inaccessible through the app on Feb. 16, 2024. We need to migrate the Sketch files our team created into Figma so that we can continue working.

Scenario: In common language describe the work or issue

Given: A designer needs to be able to work
When: A designer needs to create or modify new designs
Then: A designer will be able to use updated files in Figma

## Tasks
- [x]  Import [Sketch files](/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/p/254c8a2b-a0c3-46cf-bbaf-9d7e3f6bdbdc) into [figma](https://www.figma.com/files/project/175597876/Debt-Resolution?fuid=1207829915492285643)
- [x]  Edit each page for issues that come up during import 
- [x]  Replace local sketch components with the VA Design System figma components 
- [x]  Flag any design system problems in #platform-design-system 
- [x]  Review templates internally 

## Acceptance criteria

- [x] All Sketch files have been imported into Figma
- [x] Font and colors have been updated to use VA Design System
- [x] All local components have been replaced with VA Design System figma components 

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
I think this is ready to be closed out! Moving to validate now!

@Tom-Davis @HeatherRienks @mgleo
