### ISSUE TITLE
[BE]

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#72262]
## User Story
As a Veteran, I want to reliably submit travel claim through the check-in process

## Tasks
- [ ] [BE] Update BTSSS endpoint config in vets-api to use the fwdproxy (@Adrian to provide details)

## Acceptance Criteria
- [ ] Deployed to staging and prod
- [ ] Tested on staging and prod
