### ISSUE TITLE
[DevOps] Update BTSSS endpoint to use fwdproxy in staging

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#72263]
## User Story
As a Veteran, I want to reliably submit travel claim through the check-in process

Slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1702577596213329
platform docs on adding fwdproxy: https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration

## Tasks
- [x] [BE] Update BTSSS endpoint config in vets-api to use the fwdproxy (@acrollet to provide details)
  - [x] Make a curl request to BTSSS endpoint for testing connectivity from fwdproxy instance
  - [x] Find an available listener port: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-staging/main.tf#L78C1-L88C8
  - [x] Edit: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml and add this config (see linked DevOps PR).
  - [x] update https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-staging/main.tf#L78C1-L88C8 to add the ports
  - [x] update AWS Param store to add BTSSS url param to point to the fwdproxy URL
  - [x] update AWS Param store to add BTSSS auth url param to point to the auth fwdproxy URL
  - [x] Modify [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) for the changes in settings
  - [x] Modify settings.yml to get the fwd proxy urls from paramstore
  - [x] Add a feature flag to switch the calls between fwd proxy and BTSSS endpoint
  - [x] Modify [travel_claims/client/token](https://github.com/department-of-veterans-affairs/vets-api/blob/6ce71a80757546f6737118373e8796509bd853f4/modules/check_in/app/services/travel_claim/client.rb#L42) method to switch the calls between fwd proxy and BTSSS endpoint
  - [x] Modify [travel_claims/client/submit_claim](https://github.com/department-of-veterans-affairs/vets-api/blob/6ce71a80757546f6737118373e8796509bd853f4/modules/check_in/app/services/travel_claim/client.rb#L59-L59) method to switch the calls between fwd proxy and BTSSS endpoint

## Acceptance Criteria
- [x] Deployed to staging 
- [ ] Tested on staging

**Comment by loripusey** [comment]
@randomsync get with Adrian and clear up your last remaining questions; we will point next refinement

**Comment by loripusey** [comment]
@ndouglas make sure when you pull tickets into a sprint to let me know so that we can account for them in our reporting
cc: @anita-halici

**Comment by ndouglas** [comment]
@loripusey I thought I mentioned during scrum yesterday that I was working on this.

I wouldn't say I'm bringing it into the sprint _per se_, as there are ~7-8 tasks left with PRs, rounds of testing, etc. But I could split this out into discrete tickets with distinct deliverables if that makes reporting easier.

**Comment by loripusey** [comment]
I'll leave it up to you however you want to bundle the work

**Comment by ndouglas** [comment]
I'd give it a 5, 1 point completed last sprint and 4 left for this sprint IMHO.

**Comment by ndouglas** [comment]
Feature flag exists in staging:

![Screenshot 2024-04-22 at 11 40 47 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/3160d2b4-7424-4cb5-a74a-c6f6b493611b)

**Comment by ndouglas** [comment]
![Screenshot 2024-04-23 at 2 33 35 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/109d3996-c17c-4747-9be2-66bb05438c58)

![2024-04-23 btsss](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/95357239-939f-4af3-828b-0f4cf5bcbc9d)

With feature flag enabled, I completed check-in on staging and initiated a travel claim process. I did not encounter any errors. Checking with Gaurav to see if that is sufficient or if there is additional verification I should do.

**Comment by ndouglas** [comment]
I was unable to verify that things currently work in Staging _without_ the feature flag enabled -- there might be an API key error or something else, so I'm waiting until Mark Dewey is back from DC (should be back 4/29). Opening a successor ticket to validate this given the issues and closing this one as completed.

- [1](https://dsva.slack.com/archives/C02G6AB3ZRS/p1713900007076209)
- [2](https://dsva.slack.com/archives/C022AC2STBM/p1713982445408229)
