### ISSUE TITLE
Sunsetting EVSS ITF endpoint

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#72260]
## Issue Description
- We need to retire the EVSS code within vets-api. This work will account for the intent-to-file endpoint.

---
## Tasks
- [ ] Check with other teams and Emily what the standard for sunsetting is (this will help establish the ACs)
  - [ ] E.g. Decide if we need to remove the EVSS ITF-related code or simply disconnect the infrastructure
  - [ ] If we're doing a full-on removal, check DevOps and VSP infra-application manifests for EVSS keys in case those need to be removed
- [ ] Remove the feature flag from Flipper (if it's removed from the code, does that de-register it automatically?)
- [ ] Remove the API provider infrastructure and point directly to Lighthouse
- [ ] Update the tests to reflect the sunsetting of the EVSS endpoint

## Acceptance Criteria
- [ ] Remove EVSS migration infrastructure 
- [ ] Successful regression test for ITF through Datadog dashboard
- [ ] Document or playbook the process for future sunsetting
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
