### ISSUE TITLE
[FE] Update Production and Unified h1 headings to align with Design System requirements of 52 characters or less and one sentence headings

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#72266]
## Pre-check-in production
- Please update: "We're sorry. This links has expired." to "This link has expired" 

## Check-in production
- Please update: "Would you like to file a travel reimbursement claim now? to "Would you like to file a travel reimbursement claim?" 
- Please update: "Are you claiming only mileage and no other expenses today?" to "Are you claiming only mileage and no other expenses?"
- Please update: "You're checked in. But we couldn't file your travel claim." to "You're checked in"
- Please update: "You're checked in. You've created a travel claim already." to "You're checked in"

## Unified Priority 1
- Please update: "You're successfully reviewed your contact information" to "You successfully reviewed your contact information"
- Please update: "We're sorry. This link has expired." to "This link has expired"
- Please update: "Would you like to file a travel reimbursement claim now?" to "Would you like to file a travel reimbursement claim?"
- Please update: Are you claiming only mileage and no other expenses today?" to "Are you claiming only mileage and no other expenses?"
- Please update: "You're checked in. But we couldn't file your travel claim." to "You're checked in"

NOTE: In some instance, the work to change from two-sentence headings to a single sentence may have already been completed as part of #59165.
 

## Tasks
- [ ] [FE] **Update the h1 headings listed above**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature - feel free to tag @kellysmith1008 for validation
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@benbrasso-agile6 / @loripusey Phase 1(current app) of this work is complete. Once this is merged we will rebase the current app on the unified branch and finish it up. But since there is a code freeze, I am putting up some screenshots for review and we can merge next year. 

There is no screenshot for this one because it is no longer in use: Please update: "You're checked in. You've created a travel claim already." to "You're checked in"

Also as I mentioned in huddle today, we will need to put up the mixed language disclaimer after the freeze is lifted.
[headings-change.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01611e0cdb6b229a8a15cf9d69b65accb1507acb/headings-change.zip)

**Comment by benbrasso-agile6** [comment]
@kellysmith1008

**Comment by kellysmith1008** [comment]
Looks good to me

**Comment by brianseek** [comment]
@kellysmith1008 here is the updated unified heading as well:
<img width="140" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44a1ea9c6d16e8b2c08c3cecad09bc48e8907ec2/localhost_3001_health-care_appointment-pre-check-in_complete.png" alt="localhost_3001_health-care_appointment-pre-check-in_complete.png" />

**Comment by loripusey** [comment]
Kelly indicated that this was good
