### ISSUE TITLE
FE | USWDS v3 Component Updates | List Custom Events GA4

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72277]
## Background 
We attended analytics office hours and discussed the impact of migrating to new components AND the impact on our custom events. 

We need to generate a list of custom events so our events trigger correctly 

## Tasks 
- [x] review and create a list of custom events 
- [x] attach to this story and share the list with the analytics team 
- [ ] discuss the impact of those events
- [x] create tickets for further work around: 
  - changing anything to standard events if we can 
  - discuss any that can't be converted with standard events and figure out migration strategy with analytics team

## Acceptance Criteria
- [x] take the list of custom events back to the analytics team and discuss next steps

**Comment by adamwhitlock1** [comment]
Created the https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/engineering-docs/GA_Events_Inventory.md on the va.gov-team repo.

I will be further updating it as I continue to look at the events and determine which events could be standardized, and then will share with the analytics folks after the new year.

**Comment by adamwhitlock1** [comment]
Finished updating the docs listed above and will bring the list to GA office hours whenever they occur next to discuss next steps.

**Comment by mtcA6** [comment]
I think the next office hours overlaps w/your engineering sync up

**Comment by adamwhitlock1** [comment]
Met with analytics folks today during office hours.

For most custom events, they can use my list to make sure that those events are mapped into GA4 and the transition is relatively 'seamless'. I should still continue to audit these events and update our code to use standardized events when possible for things like api_calls or any links that can be updated to use common navigation events.

Next step for us is to set up and Analytics ticket to have them review the list and provide any feedback or required steps for us.

**Comment by adamwhitlock1** [comment]
I think we can close this one out. I created an analytics ticket here where they will follow up as they review the doc I created:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/73743
