### ISSUE TITLE
[MVP] Prepare E2E test scenarios for FE testing and staging review

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72271]
## Issue Description
Create E2E use cases, test scenarios that the team can use for:
- Frontend testing
- Backend, data mapping testing
- Provide at staging review

---
## Tasks
- [x] Document E2E test scenarios, use cases, for the purposes of staging review & data mapping testing.
-- [Link to working document in Google Sheets](https://docs.google.com/spreadsheets/d/1v1DApOkUABgVzA_4zFrGmF5prWv7T2E9OD5ojTC_iwU/edit?usp=sharing)
- [x] Share scenarios with engineering team.
- [ ] Share scenarios with VA stakeholders, as necessary.

## Acceptance Criteria
- We will have various testing scenarios documented that anyone in the team can leverage for testing purposes.

**Comment by vbellissimo** [comment]
@buddhima-coforma Added you as an assignee for this since you helped/helping with QA scenarios on that spreadsheet.
