### ISSUE TITLE
[Design] My VA health care: Remove link to MHV on va.gov from documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#72283]
## Background
We updated My VA with a link to the new MHV landing page but were asked to remove it from prod until the health tools are live to all users on va.gov. We need to update our various documentation to reflect this change - i.e. remove mention of the mhv link from documentation and sketch files.

## Tasks
- [x] Review and update as needed (4 use cases plus system scenarios): [use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/health-care-use-cases) 
- [x] Review and update sketch files as needed: [user flow diagram](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/p/23DF1405-7CBD-4457-B5B1-6D3518D13CEA/canvas), and all desktop and mobile sketch files linked within use case documentation (linked in previous task). Note that in most cases you shouldn't have to create new sketch files, check in the archives for the previous version of My VA without the MHV link but that has the current white card design and includes the "go to your inbox" link

## Acceptance Criteria
- [x] Documentation is updated

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Confirm documentation and sketch files are updated

**Comment by mattmarino-adhoc** [comment]
@ajakabcin let's review to validate and close this out. I also replaced the Sketch links with Figma ones which should be totally fine as far as everyone being able to view them, FYI (so we don't have to go and do that later anyway when Sketch access is lost).

**Comment by ajakabcin** [comment]
This looks great! Two minor things left that Matt's taking care of:

1. Remove "Visit my healthevet on va.gov" for the "non health care user scenario" for mobile and desktop
2. Update cerner use case scenario with cerner alert (pulled from archives)

Then this is good to go!

**Comment by mattmarino-adhoc** [comment]
Addressed the minor fixes and added the Cerner message alert accordion states (open and closed).
