### ISSUE TITLE
How to apply wizards: create versions of user flows reflecting how users move from various entry points to the forms 

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7228]
## User Story or Problem Statement
As a stakeholder, I need to see detailed user flows from each possible form entry point so I can understand technical and ux implications of moving the wizards to the existing form intro pages.

## Goal
- Uncover any nuances specific to a particular flows
- Finalize recommendation so we can begin engaging other teams

## Tasks
 - [ ] Visualize flow from content pages where wizards currently exist (education, disability, and HLR)
 - [ ] Visualize flow from deep links on content pages that link directly to forms
 - [ ] Visualize flow from a direct URL (organic search or mailers)

## Acceptance Criteria
- [ ] Flows created
 - [ ] Team has recommendation to move forward
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
2020-03-27 PW Standup
- Continuing in progress

**Comment by jenniferlee-dsva** [comment]
The new specific flows look great. Thanks @andaleliz. FYSA @MickinSahni: will look at this with Ben & Mem team at next Monday's DEPO sync. (https://github.com/department-of-veterans-affairs/digitalservice/issues/1128 )

**Comment by andaleliz** [comment]
Link to flows: https://app.mural.co/t/vsa8243/m/vsa8243/1585244567898/2167d6cafb30ce4a81e2ea8a082a6a832293e11c
