### ISSUE TITLE
DR | Add issue from review & submit not returning

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#72285]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to add an issue from and return to the review & submit page
**_So that_** I don't need to navigate through the form to get back to the review & submit page

## Background Context

While performing NOD testing, we noticed that while on the review & submit page, the contestable issues page link to add or edit an issue goes to the add/edit issue page, but no longer returns you back to the review & submit page. This problem may have been introduced while combining and moving shared code from each form into the shared folder.

## Acceptance Criteria

- [x] Add and editing issues directs users to add/edit page
- [x] Canceling, adding or updating the issue returns the user to the originating page (contestable issues vs review & submit page)
- [ ] Unit tests to check for regression

## Tasks
- [ ] Investigate the problem with the session storage saving the state
- [ ] Apply fix to ensure redirect
- [ ] Add unit tests specific to this redirect

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
This fix is now available in staging for testing

**Comment by eileen-coforma** [comment]
@Mottie @saderagsdale ACs met for this fix.

**Comment by saderagsdale** [comment]
@eileen-coforma Let's review it in scrum then we can close it.

**Comment by eileen-coforma** [comment]
Also validated in parking lot
