### ISSUE TITLE
[FE] 10-10EZ - Performance Monitoring: Apply Datadog privacy attributes to Forms Library review components

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72280]
## Background
As we set up the RUM (Real User Monitoring) dashboard in Datadog, there was an exposure of PII during user playback sessions. This exposure was occurring on the Review page, as it is a dynamically generated page from the Forms Library using the form data. 

In an effort to eliminate this expose, we changed the masking levels in the RUM setup to mask all text on the screen. In order to return to masking just input data, [we need to apply some specific classes and data attributes](https://docs.datadoghq.com/real_user_monitoring/session_replay/privacy_options) (available from Datadog) to the components that get rendered on the review page to apply the appropriate masking.

## Tasks
- [x] Apply `dd-privacy-hidden` class to all Review data field component 
- [x] Apply `dd-action-name` data attribute with a generic label to all Review data field component to ensure the value isn't tracked in the action sequence in the RUM session
- [x] Review the EZ app for any other areas that have been missed that may expose PII (such as page titles or card labels where a name or personal data may be disclosed)
- [x] Apply the same masking attributes in tasks 1 & 2 to any areas found to be potential exposure points for PII, if applicable

## Acceptance Criteria
- The application can function with a masked input only setting for RUM
