### ISSUE TITLE
Ramp-up on support responsibilities - Patrick Black

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72288]
### Description
Patrick is going to be going onto OnCall, and then Tier 2 support in the coming sprints, so we wanted to allow time for Patrick to get ramped up on processes

### Tasks
- [ ] [Support Best Practices](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices)
- [ ] Support Details ([Slack Thread](https://dsva.slack.com/archives/C02RLAUM2LV/p1703007251698119))
- [ ] [On Call Details](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/README.md)
- [ ] Lower Priority Docs - You personally probably don't need these, but they may be referenced by anyone who is the Incident Commander
  - [ ] [Incident Playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook)
  - [ ] [Incident Commander Tool Kit](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2652504280/Incident+Commander+toolkit)

### Acceptance Criteria
- [ ] You've read through the documents and are prepared for your On Call/Support Rotations
- [ ] You've bookmarked them for future reference during shifts
