### ISSUE TITLE
BE | Maintenance Period Alerts | C&P Direct Deposit | Add PagerDuty Services

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#72281]
## Background
The goal of this ticket is to figure out how to add a PagerDuty service.

We would like to create more granular PagerDuty services so we can apply maintenance windows to specific areas of the VA.gov Profile.  Specifically, C&P Direct Deposit is supported by the Lighthouse Direct Deposit API.  Lighthouse maintenance windows that affect C&P direct deposit are usually scheduled weekly, so we'd like to create a service/maintenance window for just this section of the Profile.  Adding a service to PagerDuty seems straightforward, but it looks like we'll need to configure vets-api with a PagerDuty Service ID.  We need to reach out to Platform Support and ask for assistance with adding and configuring a new service.

## Tasks
- [x] Investigate how to create and configure a new PagerDuty service.

## Acceptance Criteria
- [ ] ~Document how to create and configure a PagerDuty service.~
- [ ] ~Document how to add a maintenance window alert.~
- [x] Create ticket for mapping PagerDuty services to maintenance windows.

**Comment by tpharrison** [comment]
Opened a [Platform Support ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1705081116805369) asking for guidance on how to create new services.

Response...
> we are not certain - unfortunately it seems we are missing some knowledge in that space. I would make the changes to the <env>-setting.local.yml files when you set up the service. I expect there may be some trial and error though.

I think I understand how to add a new service, so once we're ready to add a service, I'll go through what I think the necessary steps are and see if it works.  Once confirmed, I'll document the steps.
