### ISSUE TITLE
Debt portal unmoderated study [discovery]

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#72299]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

As part of the debt portal IA information architecture redesign and rebranding we would like to set up discovery research through unmoderated methods (tree testing and/or card sorting). 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [x] Create Mural for planning
- [x] Think through meaningful cohorts to include in the research

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [x] Mural created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Moving this to "In Progress" since we need a ticket for our work on [the Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703026217501/7c184cbcc905ebf1a770f991d546e65f3565328b?sender=ua78f969c4cddcbfe56b27885).

Do we have an Epic for this?
If we want this ticket completed within this sprint, we should consider moving some of the tasks/acceptance criteria to another ticket.

@charlottecesana @Tom-Davis @HeatherRienks

**Comment by Tom-Davis** [comment]
I put this under the R&D Epic under the Architecture Redesign Super Epic - there will also be a development Epic where we will track the implementation.

**Comment by mgleo** [comment]
I believe this can be closed as we've created the Mural board. We can create another ticket to continue working on the unmoderated study.
cc @charlottecesana

**Comment by Tom-Davis** [comment]
@mgleo or @charlottecesana if either of you can move this to "validate" I can close it. Thank you!

**Comment by Tom-Davis** [comment]
Closing as complete.
