### ISSUE TITLE
DR | Area of disagreement focus on edit

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#72293]
## Value Statement
**_As a_** screen reader user using the review & submit page
**_I want to_** be able to have my attention focused on the appropriate element
**_So that_** I don't need to navigate to use the edit button

## Background Context

On the review & submit page, follow these steps to see the problem:
- Edit area of disagreement
- Use "Update page" button
- Note that focus is now on the `va-button` and not the `button` inside the web component

![After updating an area of disagreement, focus is shifted to the edit va-button web component instead of the edit button in the shadow dom](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/2b94b9f4-4c93-4be3-abb3-ae037fd2d3a0)

## Acceptance Criteria

- [ ] Focus must move to button within the va-button web component
- [ ] Unit tests and/or e2e tests added to check this behavior
- [ ] Behavior has been validated and approved by an a11y expert

## Tasks
- [ ] Investigate the problem with focus management
- [ ] Apply fix to ensure focus is on edit button
- [ ] Add tests specific to this focus behavior

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Fix merged in and ready for testing in staging

**Comment by eileen-coforma** [comment]
Validated on Safari with user 233 (Cara).

What's happening:
- Make edit to disagreement
- Update page
- Yellow focus outline is around the button itself, and not a square div around the button

**Comment by HeatherWidmont** [comment]
@davidakennedy will review & if everything looks okay we will close this

**Comment by davidakennedy** [comment]
Tested this today, and everything works as expected. Focus shifts to the button and not the container. Tested with user 228 (Colder).

cc: @HeatherWidmont
