### ISSUE TITLE
Locating Travel Claim status on VA.gov Study 

### ISSUE THREAD

**Issue by carafrissell1** [department-of-veterans-affairs/va.gov-team#72295]
### Summary

**Primary research question:** "If information about the status of a Travel Claim was available on VA.gov, where would veterans expect to find it?"  

Most likely methods to use include a card sort or a tree test.  

GitHub folder with research artifacts (to be created)

Research Repo tickets (to be created)

### Tasks

- [ ]  Define scope of research and questions (outline constraints) 
- [ ]  Decide on approach and draft plan and guide 
- [ ] Align on plan and guide with appropriate collaborators and stakeholders 
- [ ] Finalize plan and guide 
- [ ]  Submit for ReOps review
- [ ]  Submit recruit ticket
- [ ]  Recruitment KO with Perigean
- [ ]  Pilot user test
- [ ]  Create analysis boards and docs
- [ ]  Run sessions
- [ ]  Analysis
- [ ]  Present / shareout
- [ ]  Ensure GitHub and ReOps tickets are up to date for archiving

### Definition of Done

- [ ]  Sessions were conducted
- [ ]  Analysis completed
- [ ]  Analysis and findings presented in appropriate forum
- [ ]  All relevant documentation is up to date

**Comment by carafrissell1** [comment]
Assumption to evaluate: We can only - can we take away - we cannot change the structure.

**Comment by carafrissell1** [comment]
[H2-tree-test (1).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8b17f4ec6de36856f9784456bccd930fd4e83b0/H2-tree-test%20%281%29.xlsx)

use the 'baseline' tab as a starting place for the tree structure

**Comment by carafrissell1** [comment]
Baseline dated 1.10.24:
[Baseline.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXEyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a53e77f25283acdc1d3750e5648d977435db0a78/Baseline.xlsx)

**Comment by carafrissell1** [comment]
Working timeline:
Timeline (Expected)

Ending 1/24: Finalize plan and research artifacts
Thu 1/25 - Tues 1/30: Review by ReOps, Perigean touchbase
Wed 1/31 - Mon 2/12 AM:  Studies in field (close early if threshold met)
Tues 2/13 - Tues 2/20 : Analysis and reporting

**Comment by carafrissell1** [comment]
CAIA ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73678#issue-2084387989

**Comment by micahtaylor** [comment]
📝 Notes from meeting with CAIA 📝
No strong feelings from CAIA on showing MHV & MyVA but we will add it as an option. Maybe AccessVA since that is where they get to BTSSSS; but we aren't interested in putting it there. Also the Travel Claim static page that has a sign-in widget.

Other label options:

- Travel pay claim status
- Travel reimbursement status

**Comment by carafrissell1** [comment]
ReOps tickets:
https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/471

**Comment by carafrissell1** [comment]
Final plan:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/ea2c5a65b2e9a5c7410c7bdbe600650ffa85e82a/products/health-care/beneficiary-travel/research/2024-01-Status%20Visibility%20IA%20Study/ResearchPlan.md

**Comment by carafrissell1** [comment]
2/14 Note: friends and family readout complete, planning presentation to all interested stakeholders next week[02.12.Travel Pay Status Visibility Findings - Friends and Family.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1phQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00d3b3806805a4552fd4c58a6d9b3a3380d1b772/02.12.Travel%20Pay%20Status%20Visibility%20Findings%20-%20Friends%20and%20Family.pdf)
