### ISSUE TITLE
[FE] My VA Health Care: Remove appointment code that is not being used anymore

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#72297]
## Background
We launched our [appointment API to use the VAOS v2 a year ago](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41202), but there still exists functions within the `/personalization/appointments/actions` folder that only apply for the v0 endpoint and are not being used anymore. 

---
## Tasks
- [x] remove all unused functions in `src/applications/personalization/appointments/actions/index.js`
- [x] remove all unused functions in `src/applications/personalization/appointments/actions/utils.js`
- [x] update tests
- [x] update mock data
- [x] make sure UI looks and functions the same

## Acceptance Criteria
- [ ] Health care section - Next appointment card is still displaying correct data
- [ ] old v0 code is removed 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? FE_
- _How can this work be validated?_

## Resources
- #45480 
- #41202 
- #66858 
- #62294 
- #48002

**Comment by allisonlu** [comment]
still in progress. updating remaining estimate for sprint 28 to **3**

**Comment by allisonlu** [comment]
@ajakabcin 

updating to 1 point for sprint 29. 

PR is in review, and awaiting some more feedback before validation!

(same PR as #73088)

**Comment by DanielMiller-agile6** [comment]
I pulled down these changes from main and build is working locally for me.  Since these changes only remove unused functionality and tests pass,  I think we're good to close it out :)
