### ISSUE TITLE
Investigate Approach to Challenging Gems

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72298]
## Description
In the Gem updates that we're doing, we know there are a number of GEMS that are complicated to resolve, this ticket represents and investigation into those individual Gem updates, but is captured in this single ticket for simplicity's sake.

## Tasks
- [x] Determine status and path forward for faraday
- [x] Determine status and path forward for sidekiq
- [x] Determine status and path forward for apivore
- [x] Determine status and path forward for vbms

## Acceptance Criteria
- [ ] Status and path forward is determined for all of these gems, and tickets exist for the completion of that work
