### ISSUE TITLE
Conduct a Walkthrough of Educational and Career Counseling (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7229]
## Goal
We need a baseline to start creating initial product and design artifacts

## Tasks
- [x] Schedule a time (3/25 11:15 PT, 2:15 ET) to walk through the CH36 workflow
- [x] Create a markdown document with initial impressions, design hypotheses, and simple field research/ competitive analysis [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/discovery/README.md)

## Acceptance Criteria
- [x] Document notes and findings from that meeting in the feature folder within GH

**Comment by jason-gcio** [comment]
Here are some notes from the walkthrough this afternoon.  Please feel free to add anything!
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/discovery/README.md
