### ISSUE TITLE
[Design] 10-10EZ - Reg Only: Planning activities for shared understanding on priority use cases

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72307]
## Background
Now that we have had a couple research studies done, and gathered shared info with the VES Modernization team (who is working on the ES modernization, including the Reg Only path on the staff facing side), we are ready to start planning for wireframing, schedule working sessions with HEC stakeholders, creating journey maps and any additional activities needed to get everyone on the same page for how we will approach this feature.

- [Mural board link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702079427539/3151e3fa9a7eed55d21d5e39cb981938c5d2484a?fromVisitorModal=true&sender=uadf1ed7fe7c76f0914967329) for planning and boards to use for working sessions 
- VES Modernization timeline (TBD)
- Here is the link to the [Enrollment System Modernization](https://app.mural.co/t/departmentofveteransaffairs9999/r/1670446337223) Mural room for reference

## Tasks

- [x] Create the overview of how/what/when for these registration only “workshops”
- [x] Determine top 3 scenarios to start with 
- [x] Create session artifact / Mural area for workshops
- [x] For remaining reasons, complete assumptions table first draft
- [x] Work with UX team, PM and PO to determine the questions needing answers from HEC
- [x] Present concept to HEC at bi-weekly meeting (TBD Jan 17) 

There are open tickets to account for the work planned:
- [x] Practice sessions scheduled for each use case and session (see ticket [#72309](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72309))
- [x] Setup base of wireframes for use in Session 2 and testing with Veterans (see ticket [#72308](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72308))
- [x] Create experience map artifact (See ticket[#74006](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74006)
- [x] Conduct sessions (see ticket [#72310](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72310))
- [x] Veteran research planning (see ticket [#72311](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72311))

## Acceptance Criteria
- Planning for activities to gain shared understanding has been complete - reviewed and signed off by PM/PO and presented to HEC with timeline.

**Comment by jessicastump** [comment]
@hdjustice - I think the planning portion of this is about complete 

- We have tickets opened for the practice sessions before-hand and conducting the sessions so we could probably put the dates/times/ in one of those tickets as these get scheduled. 

- The online open task is to confirm our HEC/SME questions are 100% covered, maybe review async or a quick meeting? I guess that could also be covered in the practice sessions ticket too

**Comment by hdjustice** [comment]
@jessicastump - I would love to meet up and chat thru a quick outline and timeframe to give our HEC stakeholders today

**Comment by jessicastump** [comment]
Email Heather sent copied below and closing out this ticket; the work will continue in the tickets mentioned in the tasks lists.

> Hello all,
> 
> As we discussed during our last meeting, we want to get together for a few working sessions around Registration Only reasons and to dive into a few of the top reasons and the feedback we have from Veterans.
> 
> Our goal from these sessions is to not only gain a shared understanding of the registration process from a Veteran’s perspective, but to also use that understanding to start framing out a design that would be clear and easy for the Veteran to understand.
> 
> During each of the sessions, we will talk through:
> 
> The goal of the session
> Some research findings that relate to the Registration Only reason
> And walk through the Veteran journey to search for and obtain care for the Registration Only reason. 
> This is where we will discuss, brainstorm and volunteer as much information as we can together to formulate that shared understanding and a path forward.
>  
> We have outlined below the initial 1-hour sessions we would like to hold and the topics that will be discussed. Ideally, we would like to keep this order, and schedule them as close together as possible, so that we might get through them quickly and move to the next phase of designing the wireframes.  We plan to schedule additional sessions to work through the design together.
> 
> Please select the date and identify a 1-hour time block for each of the three sessions that work for you all and the SMEs.  Our team is the most flexible on these days.
> 
> Service-connected disability only
> 1/24 Wednesday
> 1/25 Thursday
> 1/26 Friday
> 2/1 Thursday
> 2/2 Friday
> 
> C&P Exam and/or Exposure Registry Exam
> 2/1 Thursday
> 2/2 Friday
> 2/6 Wednesday
> 2/7 Thursday
> 2/8 Friday
> 
> Mental Health Care
> 2/6 Wednesday
> 2/7 Thursday
> 2/8 Friday
> 2/15 Thursday
> 2/16 Friday
>  
> 
> Thank you all for your partnership!
