### ISSUE TITLE
BE | Direct Deposit C&P | EVSS Controller Traffic

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72306]
## Background 
We are still seeing 100+ requests/day come through the old EVSS controller (`/v0/ppiu/payment_information`).  

The referrer on the request is empty, so we can't tell where the traffic is coming from.

_Originally posted by @tpharrison in https://github.com/department-of-veterans-affairs/va.gov-team/issues/71150#issuecomment-1863808724_

## Tasks 
- [x] Determine if there is anything additional that can be logged to Datadog to help us understand where the requests are coming from.
- [x] If necessary, add additional logging

## Acceptance Criteria 
- [x] We determined the source of the issue and have resolved it or have created a follow up ticket for the same.
- [x] [see comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72306#issuecomment-1884937425) 526ez team is responsible

**Comment by tpharrison** [comment]
Joe Niquette looked into this and found [these logs](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20ppiu%20&cols=host%2Cservice%2C%40http.status_code%2C%40payload.user_uuid%2C%40http.referer&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=336994431213512540&storage=online_archives&stream_sort=time%2Cdesc&viz=stream&from_ts=1697042364190&to_ts=1704818364190&live=true)

The referer indicates a disability claim form.  I will follow up with the benefits-disabilities team.
