### ISSUE TITLE
[Design] 10-10EZ - Reg Only: Create low-fi wireframes to use in sessions/storytelling

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72308]
## Background
After conducting a couple research sessions, getting a better understanding of how the staff works through the Reg Only process, and obtaining volumes of various Registration Only scenarios (Service Connected & Mental Health), we have a better idea of how we would like to approach adding the Reg Only path to the 10-10EZ.
We want to create wireframes to help illustrate how the 10-10EZ will flow for various Veteran personas.  This will assist during our working sessions with the HEC stakeholders.

- [Planning Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702079427539/3151e3fa9a7eed55d21d5e39cb981938c5d2484a?sender=uadf1ed7fe7c76f0914967329)
- [Figma blank page setup](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=86-36817&mode=design&t=JwZY1vr9IwWyhBez-0)
- [Wireflow exploration Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696891719955/7e17ac86124fb9dcc6322be634ccdc4e8eb00a0a?sender=uadf1ed7fe7c76f0914967329)

## Tasks
- [x] Review previous wireflow exploration and add comments/notes on what is still useful or any helpful context (JS)
- [x] Create high level user flows for service connected and mental health (AA)
- [x] Review with team for feedback
- [x] Incorporate any feedback adjustments
- [x] Create low-fi wireframes for service connected registration paths (at different disability ratings) (JS)
- [ ] Create low-fi wireframes for intro page registration only path
- [ ] Create low-fi wireframes for mental health/other registration reasons (AA)
- [ ] Review with team for feedback (both)
- [ ] Incorporate any feedback adjustments (both)

## Acceptance Criteria
- Wireframes for the Reg Only pathway are completed and ready for next steps.

**Comment by jessicastump** [comment]
@aagosto90 and @hdjustice  - confirming before closing this ticket, with the MVP direction of 10-40 SC, we have the service connected wireframes done, should we close this ticket before the next sprint starts? The remaining tasks are around the mental health and intro page flows.

**Comment by hdjustice** [comment]
I am ok with separating out the mental health and intro page flows to other tickets.

**Comment by jessicastump** [comment]
Closing since there was 8 points of work on just the Service Connected wireframes done, will reopen tickets as needed to explore other post mvp flows (mental health and registration only from intro page)
