### ISSUE TITLE
[UX] 10-10EZ - Reg Only: Team "rehearsals" for storytelling practice

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72309]
## Background
We want to be well-prepared and confident as we speak to the HEC stakeholders about Registration Only pathway for Veterans.  To accomplish this, we want to hold rehearsals as a team.  This will help us speak intelligently and confidently about the Veteran personas, how they will work through the Reg Only flow, and the overall experience.

## Tasks
- [x] Rehearsals, Take your places everyone!
- [x] Create talking points doc for anyone to reference
- [x] Schedule practice session before each "workshop" 
   - [x] Use Case 1 (Service Connected) Session 1 
   - [x] Use Case 2 (Mental Health) Session 1 
   - [x] Use Case 3 (Exam) Session 1 

## Acceptance Criteria
- The team will be very prepared to present our stories in a thoughtful, and easily understood way

**Comment by jessicastump** [comment]
3 practice sessions are scheduled this week to prep for all scenarios working session 1.

**Comment by jessicastump** [comment]
Registration Mural boards to use during sessions:
- [Reason 1 (Service Connected Care Only) Session 1](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706634261021/f1e1dafb24abcea144cc5e539f26011254c04d8c?sender=uadf1ed7fe7c76f0914967329) - Friday, February 2nd - Send over with reminder 2.1?
- [Reason 2 (Exams - C&P, Clinical Eval, Exposure) Session 1](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706634336881/8d04dc452faa40f67ad7e9fc899596f2106d3609?sender=uadf1ed7fe7c76f0914967329) - Friday, February 9 - Send over with reminder 2/8?
- [Reason 3 (Mental Health Care / Other) Session 1](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706669268838/f4dca309f5232d4e1f57c7a1aeed8e2116bc08fe?sender=uadf1ed7fe7c76f0914967329) - Friday February 16 - Send over with reminder 2/15? 

@hdjustice Should we keep this ticket open for Session 2 or close this one and open a new one once ready? Some of that prep for session 2 could be more accounted for in the two existing tickets [#74006](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74006) and [#72308](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72308) so maybe a session 2 ticket won't be needed.

**Comment by jessicastump** [comment]
Closing this ticket after DSU today - will open session 2 tickets as needed and we are ready to begin with the first session tomorrow!
