### ISSUE TITLE
Finalize and Publicize recommendations for survey naming conventions

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#72305]
## Purpose
Make sure guidance pages are clear and correctly positioned for findability, then publish, and publicize

## Tasks
- [x] finalize guidance page(s)
- [x] finalize intended [location](https://vfs.atlassian.net/wiki/spaces/DCP/pages/2887680001/Guidance+How+to+name+surveys+for+Platform+research)
- [x] publicize naming recommendations

## Acceptance Criteria
- [x] recommendations are published
- [x] recommendations are publicized
