### ISSUE TITLE
Update Third VFS Survey Question to Be Optional

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72304]
## Description 

- Feature: Optimal Workshop third question "If you answered satisfied, what could our team do to turn your response to very satisfied?" to be optional. This applies to a situation where a VFS survey taker answers "very satisfied" to the survey so there is no need to improve. 
- Hypothesis: If we change this question to optional, then our data will be more granular and accurate.
- Acceptance Criteria: Question is updated to be optional

---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Update the Optimal Workshop third survey question to be optional
- [ ] Communicate the change to Basil so that we can ensure our data is mapped correctly
- [ ] Basil completes work 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
