### ISSUE TITLE
Create Initial Mockup for Educational and Career Counseling (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7231]
## Goal
Starting a mockup based on findings so far for the CH36 feature

## Tasks
- [x] Based on research findings and existing product documentation, create an initial mockup
- [ ] Prepare for an initial design intent review with the Design Practice to review for existing patterns and strategies

## Acceptance Criteria
- [ ] An initial mockup has been shared with the team

**Comment by sporeboy** [comment]
Initial set of screens built and available here: https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/

- FPO content; needs review/refinement
- Need to review "required" fields
- Need to investigate one-click option for logged-in Veterans
- Will need to schedule design intent review

**Comment by jason-gcio** [comment]
These screens look great Jim!

**Comment by sporeboy** [comment]
Screens and workflows updated to reflect "required" info.
