### ISSUE TITLE
[UX] 10-10EZ - Reg Only: Conducting the HEC working sessions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72310]
## Background
Now that we have prepared our wireframes and practiced our storytelling, we are ready to conduct several working sessions with the HEC Stakeholders.
The goals for these sessions are to gain a shared understanding of the Reg Only process, especially from a Veteran experience perspective, and to share our vision of how the Veteran will work through the flow within the 10-10EZ application.
Focus on top 2 use cases, based on high volumes - Service Connected, and Mental health.
Holding 2 sessions per use case.

## Tasks
- [x] Conduct the HEC working sessions
- [x] Gather input in a shared, central location (Mural probably)
- [x] With the 2nd and any subsequent sessions, be sure to overview what was done in the previous session
- [x] With the final session, recap what was done and what successes and learnings were had

## Acceptance Criteria
- Working sessions with HEC Stakeholders were held and completed successfully

**Comment by jessicastump** [comment]
`Moving over internal notes file:`

**### 240202 Friday, Registration-Only Workshop #1**

10-10 Team
Angela Agosto
Chapley Watson
Heather Justice
Hieu Vo
Jessica Stump
Katelyn Caillouet
Mitch Saltykov

HEC/ SME
Ambroja Watson
Byran Burgan
Cecilia Doporto
Jennifer Mdoe
Jessica Soza
Taccara Norwood
Samatha Ruble
Simone Gully


Jessica Presents:
First Study; Interview 
Veterans see disability and healthcare benefit as the same process.
Veterans are confused about the registration and enrollment process.
Simone “Not surprising, most Veterans don’t want to read, they want to be told. It is hard to put the Priority Group as front-facing”
Simone: Due to ACA, Registered can be seen and not impact on the marketplace. If you are Enrolled, you received a stipend due to low income, you’ll get a penalty for Enrollment”
Second Study; unmoderated Tree Test
Service-connected only “how would you like to find and sign up for health care”
Most went to the disability hub, not health care. 
How would you like to be informed of the health care benefit?
Most would like to be called, other would like to fill additional forms.
Most comment reason: help from the VA, provide steps-by-step or have someone assist.
Simone “if they are 50% or more, they would get the full benefits.”
Simone “Due to ACA, they will still need to choose Reg or Enrollment. Even if they’re choose Reg, they get treated as full Enrollment.
If a Veteran over 50% is in the healthcare marketplace, they will receive a stipend. They should be Registration-Only, if they are Enrollment they would get penalized due to ACA. 
Online have a similar question around ACA at the Facility Selection.
If they are Enrolled, they have to write a letter to Disenrolled. (Status to Cancelled/Decline), This process does not automatically put them into the Registration-Only.

Veteran Journey matrix
Samantha Ruble: It seems to be in line with what we received on the call-center. 
Registration in VES
Simone: It depends where the C&P is done
Simone: Functionally of when they file for the Disability claim, it will be a function of the Registration-Only. Something currently be worked out. They still have to apply for Enrollment. Anyone that is given Service-connected, they wil receive the Decision Letter. 
Legal issues: 
Simone: VBA and VHA are different entities, different authorities, determining different things. 
Simone “If you served under 24 months, you’re not eligible for health care. But if you have a service connection, you still have to re-apply. It is not an automatically. 
If the their rating is changed:
Simone: HEC received information from VBA and they will be automatically 
Ideal State for getting health care after receiving Disability Rating of 40%.
Ambroja: Want a Yes/No and disclosure about copays.
Samantha: Need financial finro to determine how far tehy want to carry their benefits.
Time frame for the typical Veteran to process
Samantha: Paper form takes about 30-40 minutes to process
Samantha: We’ll ask them the preliminary questions such as “did you serve more than 24 months”
Samantha; biggest hindrance for them is that the information is not in the system. DOD did not update, VBA did not update.


**### 240209 Friday, Registration-Only Workshop #2**

10-10 Team
Angela Agosto
Chapley Watson (not present)
Heather Justice
Hieu Vo
Jessica Stump
Katelyn Caillouet
Mitch Saltykov

HEC/ SME
Ambroja Watson
Byran Burgan
Cecilia Doporto (not present)
Cynthia A. Halls
Jennifer Mdoe
Jessica Soza
Kimberly Knight-Nelson
Taccara Norwood (not present)
Samatha Ruble
Simone Gully

Jessica summarize Session #1
Veterans cannot be in both Marketplace health care and VA health care, so they Registered. 
Future State; be registrated in VHA when they submit a claim. 
Ideal state for Service Connected from disability rating/ award letter link to accept copay and agreements.


The application process:
Simone: any record, regardless of what the enrollment say, the enrollment system will go out to find info from other system to bring back.
Registration questions are what’s needed to progress registration (Name, BOD, etc)
Simone: just ask if they wish to enroll (for service connected group). If they say no, ask if they want an appointment for screening. Then ask what type of appointment they want.
Samantha notes that Basic Demographics is a requirement.
Samantha: Once enrolled they will also receive a call to give information and assist with appointment scheduling.
Future State; Simone: if SC awarded, they get a letter that ask if they want to enroll.
If 'REGISTERED" does the Veteran need to consent to copays still? and/or provide income info for SC meds??
Simone: Yes, but don’t need to do the financial disclosure piece.
Need financial info to determined how far they want to carry their benefits.
Simone: Registration does not require financial information. If they want care outside of their SC, they would have to enroll.
30% Disable Rating scenario, 
Simone: let them know, legally, if you registrated you only receive care for your service-connected claims. If you enroll, you get full health services.
Call center
Samantha: Lots of question on how it impact other insurance and if there are additional cost. Does this affect my medicare?
Samantha: We use keywords in the VA system to find answers to their questions.
Samantha: mostly clarifying that they do not have to cancel their private healthcare. Generally they continue to use Private Healthcare and use VA to cover some cost.
Jessica Soza: We can provide knowledge management (has a google like keyword search): https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001046
Samantha: 90% of the time, they want to enroll because it covers much more.
ENROLLMENT PRIORITIZATION
Simone: PG7 above GMP threshold 
Samantha: Priority Group breakdown; https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001046/content/554400000049168/Enrollment-Priority-Groups#Table%20of%20Contents 
PG 2 & 3 provide so exempt medical copay, travel paid.
Jennifer Mdoe: Enrollment Priority Groups https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001046/content/554400000049168/Enrollment-Priority-Groups#Table%20of%20Contents 


APPOINTMENT
Simone, Registrated Veteran has access to appoint and access MHV account. 
If Registered does Veteran have access to MHV account? 
Simone: Yes. When you’re registrated and have a VAMC

Learning about additional health care benefits.
Simone: If they’re registrated, it is 
Simone: some only wants to registrat to get a registration exam. 


**### 240216 Friday, Registration-Only Workshop #2**

10-10 Team
Angela Agosto
Heather Justice
Hieu Vo
Jessica Stump (not present)
Katelyn Caillouet
Mitch Saltykov

HEC/ SME
Ambroja Watson (not present)
Allan
Byran Burgan
Cecilia Doporto (not present)
Cynthia A. Halls 
Jennifer Mdoe (not present)
Jessica Soza (not present)
Kimberly Knight-Nelson (dropped early)
Roosevelt Jr. MaCray (JR)
Samatha Ruble
Simone Gully
Taccara Norwood (not present)

HEC
Lots of TERA last minute update so lots of team members may not be available.
Finding a provider I trust
Simone: that is a clinal decision but we will still see them even if they are ineligible, we will provide them with resource (Registration)
Samantha: The online/paper always ask address so we link them to the closest VA Facility Center. If they call in, we’ll directly transfer. If paper or online, ECA will give them info in mail about their facilities (no email for enrollment). 
Samantha: [11:24 AM] Ruble, Samantha, HEC: Upon enrollment, we do ask for their closest VAMC and they would be linked to the facility that they live closest to.
Specific Provider?
Roosevelt: can request male/female provider, location, MD vs NP, could charge provide via patient advocate and firll out a form to change
Finiding a provider, Ideal State:
JR: all best done in one location. We did enrollment and initial appointment, less person to person transfer.
Samantha: Listing of the provider with their specialty, provider, and even with rating. Having that knowledge of who is available and who isn’t
JR: Uniformability across the VA; all the VA is conceptually the same but done different. Speaking as a Veteran and an employee.
Samantha: California VA vs Maine VA has the same service but done differently. 
JR: One location has all one stop shop. Another location will have different location for diffnerent services. 
JR: Stagetic marketing; they’ll get their information from friends, family, and neighbor. If we put reading material out there, they can come in with accurate information instead of hearsay. 
Determine if I qualify:
Complete Application:
JR: Think of VA has regular Healthcare. Just apply, if you get deny, you’ll get deny. People generally think that Mental healthcare is different. Priority Group 100-50% disability rating doesn’t necessary cover dental.
Samatha: Veterans specify what they what to address after they been assigned to their primary care provider.
How does this work VES
Samantha: It is our Enrollment System where we enter all of their data. We don’t schedule their appointment in VES but we will mark yes in VES if they answer yes they need appointment. They can transfer them to their preferred facility.
Need primary care first?
Samantha: Generally yes, they will be referred to mental health care but Primary Care will function like a Case Manager. 
Ideal System:
Samantha: Take care of health care appointment simutlaneously.
JR: The way VA is designed like you need to go to through Primary Care Provider first. In Little Rock Arkansas, you can just walk in and wait instead of waiting months. 
Samantha: if there aren’t mental health, they may be sent to Community Care.
Attend First Appointment:
Samantha: Just making sure the Veteran has all the materials with them (30-45 minutes complete over the phone)
JR: Enrollment is not difficult. If you need help, you will get help. The difficult part is reaching the Veteran (Communication and collaborating with other departments. Finding homeless Veterans that did not even know they’re Veterans. 
Ideal state:
JR: Town hall meetings so VHA and VBA can collaborate, brind back the structure from covid.
JR: Put our information on all of the media outlets (sosial media, TV, news, billboards, radio)
Samatha: We have PACT Act but we need to not just do big events but they day to day as well.
JR: Sentiment around VA is changing, we’ll get to the point where there is Veterans then providers. 
Learning about additional health care benefits:
Inegilible for enrollment
Samatha: Even if they’re ineligibility, they can still be seen for humantarity emergency or given resources into their community. But they need basic eligibility criteria to register.  
JR: The definition throws them off 
Registrated vs 
Samatha: They have to ask. They will have to call in and HEC will encourage them to fully enrolled.
ES statuses for non-enrolled
Samantha: If they are not eligible that one of the erolled reasons. Even if they’re rejected, they will be seen for an initial consultation and given resources to go into their community.

**Comment by jessicastump** [comment]
@aagosto90 - I added a few things to the [GitHub folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Registration/ux) for documenting and started a [topline summary doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/ux/ToplineSummary_registration-SME-working-sessions.md) where we can note key take-aways. I'll get the SC one done but thinking you could maybe assist with the mental health couple key notes?
