### ISSUE TITLE
Appoint a Rep (Unauth) - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#72316]
## Issue Description
Dependent (spouse, child, caregiver, etc.) user test of the 21-22/21-22a unauthenticated user flow.

## Tasks
- [x] Create GitHub research folder
- [x] Create research plan
- [x] Define screener questions
- [x] Create conversation guide
- [x] Submit all materials to team for review
- [x] Create ZenHub ticket for revisions

## Acceptance Criteria
- [x] All materials complete and ready for team review

**Comment by jfinnerty13** [comment]
Research plan and conversation guide created and ready for review: https://drive.google.com/drive/folders/1j_VB7CpApC_77Jlvxr4iC5BRJSyQvWRc?usp=drive_link

GitHub folder system: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-02-appointarep-unauth-usertest

**Comment by jfinnerty13** [comment]
Going to move this to complete as the work is done - just need to submit to the team closer to when we decide to test the prototype. Thanks!
