### ISSUE TITLE
CSAT Report for OCTO

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#72336]
## Issue Description

One of OCTO's 2024 KPIs is to improve the CSAT score by 5 points. In order to do this they first need to know what areas are scoring lower than average and their impact on the overall score (low score with very few responses will have less impact than those with a lot of responses). They want to be able to slice and dice the scores, by page, by form product, by product category, etc.

We need to look at Medallia data to determine what we can report on and how best to do so. The end goal is for them to be able to look at our data/report and know exactly what area(s) to focus on that will have the most impact.

Resources:

[Medallia - All Data Monthly](https://va-gov.domo.com/datasources/c2cdf24a-a65a-42e1-985c-3f284ce1585f/details/data/table) - this is the raw data coming out of Medallia, updated monthly used for most reports
[Medallia - All Forms](https://va-gov.domo.com/datasources/8a9d18a9-f962-4130-969c-45e4acb18dd5/details/data/tablea) - raw data that is updated daily, we prob want to use this one so we don't have to wait a month to see movement.
[[ETL] - Medallia Performance Dashboard](https://va-gov.domo.com/datacenter/dataflows/209/graph) - I think we need to create a new version of this using the 'Medallia - All Forms' dataset that is update daily (current is monthly)
<img width="1755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0I0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2819d8c76850b26c404bcd446684c862f720c158/image.png" alt="image.png" />
[[Output] Medallia - Directory & Product Mapping](https://va-gov.domo.com/datasources/3d83a71b-fba6-431d-8c80-5ce9d72312c2/details/data/table) - used as part of [Output] - Medallia Performance Dashboard 
[Medallia Product ETL](https://va-gov.domo.com/datacenter/dataflows/126/graph) - ETL with product mappings use to create [Output] Medallia - Directory & Product Mapping
<img width="1778" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVo0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1bf2c0695b988309ff2390cbbef9913a9cf4983/image.png" alt="image.png" />
[[Output] Monthly CSAT Scores: ForeSee & Medallia](<img width="1778" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXA0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4c6251d9b4a311ee75a8cdff1493be96b314452/image.png" alt="image.png" />) - this is the dataset used on current dashboards but it is only updated monthly. It contains the CSAT formulas
<img width="1566" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTk0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd32b5f810103dd5b21f78e1caab7db8b584ff12/image.png" alt="image.png" />

---
## Tasks
- [x] Review current Medallia datasets/flow per the docs above
- [x] Create a new version of the [Output] - Medallia Performance Dashboard using the 'Medallia - All Forms' dataset that is update daily (instead of 'Medallia - All Data Monthly')
- [x] Calculate/create CSAT scores for the new dataset (see [[ETL] ForeSee & Medallia Monthly CSAT](https://va-gov.domo.com/datacenter/dataflows/221/graph) for those formulas
- [x] Use new dataset to create cards that will give them the CSAT metrics as described above.

## Acceptance Criteria
- [x] We have provided OCTO a report that they can use to see areas of under performance and track over time.
---
