### ISSUE TITLE
Design | Migrate to Figma | Consolidate selected Sketch files/pages into Sketch Archive file

### ISSUE THREAD

**Issue by pamela-drouin** [department-of-veterans-affairs/va.gov-team#72331]
## Background
The AE UXers have decided that the best way to archive files/pages in Sketch that are no longer actively being worked on is to move them into a dedicated "archives" Sketch file, and then migrate that file for reference purposes. This is less time-consuming than exporting boards and uploading them to an archival folder in our repo. It will be easily accessible in our new tool as needed.

## Tasks
Move this Sketch stuff to the [AE Sketch Archive](https://sketch.com/s/d5237db2-f48d-4fe4-8554-d32065994609) sketch file. 

**Note**: Each top level area (Personal information; Profile hub) has a corresponding Page within the AE Sketch Archive file where all the respective boards can be copied.

- [ ] Deprecated -Profile-2.0  
	- [ ] 📦 Screens 1.0
	- [ ] 📦 Screens 2.0  pre-launch Sept 2020
	- [ ] 📦 Screens 2.0 Mobile exploration
	- [ ] 📦 Style Guide
	- [ ] 📦 Symbols
- [ ] Profile - Audit of alert messages 
	- [ ] 📦 Inventory_Audit 
	- [ ] 📦 Symbols
- [ ] Profile - Personal information
	- [ ] 📦 Discovery
	- [ ] 📦 Iterations
- [ ] Profile - Account Security
	- [ ] 📦 Iterations
	- [ ] 📦 ~Discovery~
	- [ ] 📦 ~Archive~
- [ ] Profile - Editing sub-task
	- [ ] 📦 Iterations 
- [ ] Profile - Direct Deposit
	- [x] 📦 Discovery
	- [x] 📦 Explorations
	- [x] 📦 Iterations
- [ ] Profile - Notification Settings
	- [ ] 📦 Iterations
	- [ ] 📦 Explorations
- [ ] Profile - Contact Information
	- [ ] 📦 Iterations - Launched versions
	- [ ] 📦 Iterations/discovery - modal and BAI
	- [ ] 📦 Exploration- address validation accessibility improvement
- [ ] Profile - Hub landing page
	- [ ] 📦 Exploration: Long term plan for alerts 
- [ ] Profile - Personal health care contact
	- [ ] 📦 Iterations
	- [ ] 📦  Explorations
- [ ] Profile - Military Information
	- [ ] 📦 Discovery
	- [ ] 📦 Iterations

## Acceptance criteria
The [AE Sketch Archive](https://sketch.com/s/d5237db2-f48d-4fe4-8554-d32065994609) sketch file is ready for migration.

**Comment by pamela-drouin** [comment]
@mtcA6 -- I created this ticket based on the conversation @andaleliz, @mattmarino-adhoc, and I had this morning about how best to archive sketch files. This ticket is the next step for #71216!

**Comment by mattmarino-adhoc** [comment]
Unassigning myself from this for now for the sake of tracking my points more effectively. I will add myself again/create a new story on the My VA board when appropriate.

**Comment by pamela-drouin** [comment]
@andaleliz I think this ticket is moot, because most "archived" pages are being archived in Figma as part of each product/feature's migration ticket. Think we can close this? (cc @mtcA6)

**Comment by andaleliz** [comment]
Yes, I think we're good to close it!
