### ISSUE TITLE
BE | General Maintenance | Investigate C&P DD logging to ensure that ICN is being logged on all updates.

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72342]
## Background
In order to help triage C&P Direct Deposit issues, any logging related to DD updates will need to contain the ICN of the user.

## Issues
- [Not seeing ICN in logs](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%40http.url_details.path%3A%2Fv0%2Fprofile%2Fdirect_deposits%2Fdisability_compensations%2A%20&cols=host%2Cservice%2C%40http.status_code%2C%40payload.user_uuid&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=336994431213512540&stream_sort=%40payload.user_uuid%2Cdesc&viz=stream&from_ts=1702924121587&to_ts=1703010521587&live=true)
- [Not seeing any records in APM](https://vagov.ddog-gov.com/apm/resource/vets-api/rack.request/bc1e3cb125eb0125?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%22V0%3A%3AProfile%3A%3ADirectDeposits%3A%3ADisabilityCompensationsController%23update%22&env=eks-prod&spanType=service-entry&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1696132800000&end=1704085140000&paused=true)

The line - [after_action :log_sso_info, only: :update](https://github.com/department-of-veterans-affairs/vets-api/blob/0da7e9298150a05e117ff6a8ff9d260f10ce6d42/app/controllers/v0/profile/direct_deposits/disability_compensations_controller.rb#L13) calls [log_sso_info](https://github.com/department-of-veterans-affairs/vets-api/blob/0da7e9298150a05e117ff6a8ff9d260f10ce6d42/app/controllers/concerns/authentication_and_sso_concerns.rb#L108) method of the `AuthenticationAndSSOConcerns` class.  It should log the ICN after every update request.

## Tasks
- [x] Work with Joe Niquette to make sure this requirement is being met.
- [x] If needed, make updates to logging.

## Acceptance Criteria
- [x] Any necessary changes are pushed to production.
- [x] Review logging with Joe Niquette.
