### ISSUE TITLE
BE | General Maint | Investigate decrease in traffic to VA Profile contact information hub starting on 12/15/23.

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72341]
## Background
VA Profile noticed a decrease in traffic to the contact information hub starting on 12/15/23 at 12:25pm through DVP-API.  They have asked our team to investigate.

Our logs do not show any decrease in traffic during that time.

## Tasks
- [x] Meet with Shawtel Adams (Operations & Maintenance, VA Profile) to discuss further.
- [x] Determine next steps.

## Acceptance Criteria
- [x] Create additional tickets if necessary.

**Comment by tpharrison** [comment]
Met with Shawtel Adams and we determined that the traffic is coming through DVP which is Salesforce.  Shawtel will reach out to their team and ask if they know more.

Going to keep this open until we hear back.
