### ISSUE TITLE
Transaction Time Report for OCTO

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#72344]
### Description

One of OCTO's 2024 KPIs is to reduce "transaction" time. Transaction time can be defined in a variety of ways, some as follows:

- **Time to Complete:** This would be specific to form products. Because of GA data limitations (cross devices, IPs, etc) we will only be able to calculate this for users that started and completed the form in the same session. 
- **Session Time:** This would be the time from the start of the session to the end of the session
- **Time on Page:** I don't think this is what they need for their KPI but since we are looking at time metrics I thought we should go ahead and include this too just in case.
- Others?

We need to create new or add to existing dataset for ALL VA.gov (not just forms). May want to leverage/review datasets used in the All VA.gov Dashboard and Monthly VA.gov Summary to determine where best to perform these calculations. 

---
### Tasks
- [ ] Create new transaction based metrics as defined above
- [ ] Review data for accuracy
- [ ] Create cards to be added to All VA dashboard

### Acceptance Criteria
- [ ] Transaction metrics have been created
- [ ] Transaction metrics have been QA'd, and verified
- [ ] Cards have been added to All VA dashboard in Domo and QA'd
---

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc -
@dorseypa1 might already have pointed this out but time tracking can only measure the time between interactions -- e.g. a User can read thru a page for 5 mins without triggering a follow up interaction. This can cause a skewed metric, particularly with content heavy information-based pages and probably why Michelle questioned Time on Page.

**Comment by johnny-jesensky-adhoc** [comment]
Look to move into Icebox - deprioritizing for now.

**Comment by AdamOye** [comment]
**Closing this ticket as part of backlog cleanup.**
This work is no longer prioritized, is outdated, or has been addressed elsewhere.
If this resurfaces as a need in the future, we can refile with updated context.
