### ISSUE TITLE
Drupal content review from BaM2 (Medical Device Tool)

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7234]
## Why you're here
- Content support for static public website pages

## Instructions
* Submit this request when VSA Public Website team intervention is required
* Provide detailed information of your request to help us understand our role in completing your request 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Background

* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
   * "Medical Device Tool" is a new form on VA.gov with which eligible Veterans can order hearing aid batteries and accessories from the VA. Veterans can order batteries, domes, wax guards, cleaning supplies, drying agents (desiccant), and more for their VA-issued hearing aids.
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md)
  * [Research folder outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/medical-device-tool/research)
  * [Invision link for content page - hearing aid batteries and accessories](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077289_Content_Page_-_Unauthenticated_-_Desktop)
  * [Invision link for content page - prosthetic socks](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/411275866_Content_Page_-_Desktop)
  * [Invision link for all form pages/states](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/403219934_Default_-_Desktop)
  * [Invision link for form 'happy path' walkthrough](https://vsateams.invisionapp.com/share/8NWBZNBFPMV#/408543330_Default_-_Desktop)

### Request Type
*Select all applicable and provide details behind your request* 

- [ ] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * Word document with draft if available, or link to the URL where the draft content appears:
      * 
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * 
   * Scope: How many screens? (Or messages, etc.) 
      * 
      
      
- [x] **Content support for a static public website page**
   * Is this to update existing static content? 
      * N
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * Y
   * Provide a list of URL/s that need to be reviewed or updated. 
      * Proposed URLs: /health-care/order-hearing-aid-batteries-and-accessories & /health-care/order-prosthetic-socks
   * If it's a small copy section, list what the new info should be and what it is replacing.
      * [Github link to Word Doc for HAs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/documents/MDT-Hearing-Aid-Content-v1.docx) 
      * [Github link to Word Doc for Socks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/documents/MDT%20-%20Prosthetic%20Socks%20Content.docx)

- [ ] **New URL or Redirect Requests**
   * Have you vetted this request by the VSP IA team?
      * < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * Link to VSP IA Redirect Request ticket
      * < Github issue link >
      
- [ ] **Implementation of REACT sign in widgets**
   * Full spec including different states and behaviors
      * < link to spec >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*

* Usability testing April 15

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: Benefits and Memorials 2
- DEPO product owner: Matt Self
- Product manager: Leah Keeler
- Designer: Rebecca Walsh, Riley Orr
- FE engineer: Amen Ra, Mahariel Rosario
- Product/team Slack channel: vsa-bam-2

--- 
#### Next steps
- [ ] Convert this request to an Epic
- [ ] follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by MickinSahni** [comment]
Planning notes
- Create ticket for Selina to "Content Review for Device Reordering" within this epic - @MickinSahni

**Comment by lunascoop** [comment]
I have completed my review and attached my edits.
[MDT - Prosthetic Socks Content_SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4456761/MDT.-.Prosthetic.Socks.Content_SC.docx)
[MDT-Hearing-Aid-Content-v1_SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4456762/MDT-Hearing-Aid-Content-v1_SC.docx)

**Comment by lunascoop** [comment]
> I have completed my review and attached my edits.
> [MDT - Prosthetic Socks Content_SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4456761/MDT.-.Prosthetic.Socks.Content_SC.docx)
> [MDT-Hearing-Aid-Content-v1_SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4456762/MDT-Hearing-Aid-Content-v1_SC.docx)

@peggygannon can you review my edits? Thanks

**Comment by stephorkandatx** [comment]
@peggygannon and/or @rebeccawalsh : have you had a chance to review the edits, or should we continue to keep this work "in progress" for the time being?

**Comment by peggygannon** [comment]
@lunascoop @stephorkandatx sorry, for my delayed response.  I'm meeting with @DanielleThierryUSDSVA tomorrow to sync about this.

**Comment by rebeccawalsh** [comment]
@lunascoop Meant to respond as well - we got your original edits and I believe we incorporated them in our test sessions. We can make any additional changes if Peggy has them.

**Comment by stephorkandatx** [comment]
Will roll to sprint 20

**Comment by stephorkandatx** [comment]
Moving this back to Backlog. The work is still being finalized. We will move forward & close when it's time

**Comment by rebeccawalsh** [comment]
@lunascoop The mockups have been updated to reflect the changes we discussed:
- [Unauthenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077289_Content_Page_-_Unauthenticated_-_Desktop)
- [Authenticated](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/410077290_Content_Page_-_Authenticated_-_Desktop)

**Comment by rileyorr** [comment]
Hi @stephorkandatx! Our tool is getting closer to launch and I was wondering what the status of this work is and if you need anything from me, @rebeccawalsh, or @leahkeeler

**Comment by mnorthuis** [comment]
@DanielleSoCompany @lunascoop Can we connect on this one soon?  I don't see the link to the IA in the initial request and I want to make sure we don't miss the full scope of work here - in addition to the content pages, there are top nav, hub page and left page links to be done.  There will also be a redirect needed.

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis Yes, that would be great. Can we plan a working session with you, @lunascoop, and @peggygannon this week?

**Comment by stephorkandatx** [comment]
@rileyorr it is in progress and there will be a working session soon, per the discussion above. If questions come out of that, we will be sure to send them your way. What is the current target for the tool launch?

**Comment by rileyorr** [comment]
@stephorkandatx Awesome, thank you! Our tentative launch date is June 24th.

**Comment by RLHecht** [comment]
@lunascoop I've done a copy edit on the two Drupal pages as they are so far. I know you still need to work on the react widgets and some other things.

**Comment by lunascoop** [comment]
Hi @DanielleThierryUSDSVA Here is the links to the draft drupal pages for review: 
- http://preview-prod.vfs.va.gov/preview?nodeId=5681
- http://preview-prod.vfs.va.gov/preview?nodeId=36

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. I pulled the preview content into Word docs to track changes and add comments.

[Order prosthetic socks_dt_6.18.20](https://app.zenhub.com/files/133843125/c7134e4a-6a72-4884-8782-afe94d45b789/download)

[Order hearing aid batteries and accessories_dt_6.18.20](https://app.zenhub.com/files/133843125/9a7676fb-9719-47a0-864e-9105fd5040f2/download)

- Please incorporate into the Drupal pages the tracked changes that don't have a "needs follow up" comment.
- There are a few "follow up" items for you (highlighted in below). Could you look into these, and let me know if you have any questions?
- There are also a few "follow up" items that I'm going to follow up on today (highlighted in yellow). I'll add final edits related to those in this issue later today.
- We'll want Peggy and/or Randi to do a final proof just to make sure we're good to go on the Drupal page after incorporating these changes.

Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Updates to follow-up items tracked and highlighted in blue. Let me know if you have any questions, or if you need any support in finalizing the Drupal pages. When all changes are in, could you please ask @RLHecht to do a final proof? Thanks!

[[Order hearing aid batteries and accessories_dt2_6.23.20](https://app.zenhub.com/files/133843125/e3e8784d-2e47-46f9-9ffa-a9e875d7d594/download)

[Order prosthetic socks_dt2_6.23.20](https://app.zenhub.com/files/133843125/959601d2-9327-4fb6-93ac-b93dc9cb2a61/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Let me know if you need anything else from me on this one for now. I understand from Mikki that this is now launching  around July 7 I believe.

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA will do and thanks for the feedback!

Hi @RLHecht these pages are ready for review. I made changes per Danielle's feedback (two comments above). 
- http://preview-prod.vfs.va.gov/preview?nodeId=5681
- http://preview-prod.vfs.va.gov/preview?nodeId=36

Re: the hearing aid supplies page:
- For the "Find the phone number for your local VA facility" link, I couldn't find the node related to the "Find VA locations" page. So I just linked to the actual page.

- When I review the changes w/the product team, I will some things per Danielle's feedback. For example, confirm the "download our catalog link" (it seems up-to-date) to PDF, adding process for shipping device to DLC for repairs.

- Also added DLC contact hours to copy

- The react widget Nick created does not include "online." May need to go back to him and update the text.

Re: the prosthetic socks page:
- Added DLC contact hours to copy

- Left the "More information" header as is (see Danielle's feedback for more information, haha jk!). In viewing the page, it seemed needed to separate from "By phone or email content." Randi, you can weigh in.

**Comment by lunascoop** [comment]
Quick question re: the 6th step on the prosthetic socks page. Should we say "we" as it pertains to eBenefits? I know that **we** are VA, but eBenefits too?

**Comment by RLHecht** [comment]
@lunascoop I reviewed the two pages above. Made some minor copy tweaks and also did the updated we discussed over slack (removing the more information H2 on the prosthetic socks page and updating the name of the hearing aid PDF.

**Comment by lunascoop** [comment]
Hi @rebeccawalsh and @leahkeeler. I'd like to schedule a review of the pages before they are published. What's your availability either tomorrow or Thursday? My schedule's fairly flexible on both days w/ the exception of sprint planning tomorrow from 1-2:30pm. Thanks!

**Comment by leahkeeler** [comment]
Hi @lunascoop Do you want me to schedule? I have access to Riley and Becca's cal

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop and @leahkeeler. Once we're fully aligned internally, would like to run these pages by SMEs to make sure we're all good. Leah, which SMEs have you been working with for these tools? We have our health care contacts, but want to make sure we're working with the folks involved with these specific tools. Thanks!

**Comment by leahkeeler** [comment]
We work with a team from the Denver Logistic Center, and have a standing meeting on Thursdays - would you like us to send this over for them to review, go over in meeting, or you can join the meeting - nicest bunch of people ever

**Comment by lunascoop** [comment]
Sure, or I can join the meeting. If I join the meeting, do you want to cancel the one we have scheduled for tomorrow?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @leahkeeler! That sounds perfect. 

@lunascoop that would be awesome if you could represent our team at the meeting. I can join as well for backup in case questions arise, but would be great if you could talk through the pages. Thank you!

And then once the Denver folks are good with content, I can just send to the health care SMEs we typically work with for an overall perspective (they're the folks who originally approved the combined page).

**Comment by MickinSahni** [comment]
Removed the sprint designation from this Epic.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop @leahkeeler Checking in on meeting with SMEs to review content. Can you let me (or @bethpotts if you can on Monday, as I'm out) where we're at with approval? Per above, I'd like to send to our main health care SMEs once we have the OK from the DLC folks. Thanks!

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA the meeting has been rescheduled for Monday afternoon. I will update you and @bethpotts then with approval status.

**Comment by lunascoop** [comment]
@DanielleThierryUSDSVA cc: @bethpotts I just attended the DLC meeting and reviewed the pages w/them. Overall, they're happy w/the pages but requested one change. For the prosthetic socks page, they want us to clearly specify that the DLC is how to order amputee prosthetic socks and not any other type of medical socks (ex: diabetic medical socks). Currently, they get a lot of calls from Veterans to order diabetic socks, which is not what they do (and bc it is not clear on our page). They suggest changing the page title to "Order amputee prosthetic socks" and include "amputee" in the copy to avoid confusion. There's also possibly the need to reorder the "How to order" info on the page. Most veterans reorder prosthetic socks by phone and not through eBenefits (and the eBenefits content comes first on the page). Also don't know if we want to look into the process to order diabetic prosthetic socks to either include as a separate section on the page, or elsewhere. They are still planning for a July 8th launch but need to do some testing before then. There may still be an issue w/ the API that may delay the launch, so the stakeholders will let us know later today.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @lunascoop. 

I've worked in additional information to distinguish that this is prosthetic socks for Veterans with lower limb amputations. 

I've also reworked the how to order info to bring phone up for this one. Typically, we want to showcase the online tool on a tool landing page. However, since this is currently not going to a tool on VA.gov itself and because there's that lengthy instruction step-by-step for eBenefits, @bethpottsVADEPO  and I think it's okay to have the phone number first for now.

I'd like @RLHecht to take one final look just to make sure I didn't introduce any errors in making the changes! @RLHecht, do you have time today to take a look? Thank you!

**Comment by rileyorr** [comment]
@DanielleThierryUSDSVA 

> I've worked in additional information to distinguish that this is prosthetic socks for Veterans with lower limb amputations.

Veterans can order prosthetic socks for arm amputations as well!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @rileyorr! Will revise based on that!

**Comment by rebeccawalsh** [comment]
@DanielleThierryUSDSVA For more specifics, you can see the types of amputee socks the DLC provides on the second page of this catalog! https://www.va.gov/opal/docs/nac/dlc/catalogProstheticSocks.pdf

**Comment by RLHecht** [comment]
@lunascoop @DanielleThierryUSDSVA I reviewed both of these pages again and they are good to go!

**Comment by DanielleThierryUSDSVA** [comment]
Woohoo! Thanks, everyone!!

**Comment by leahkeeler** [comment]
Huge Thank-you to everyone!!!! You guys are amazing and awesome!!!!!!!!!!!!

**Comment by DanielleThierryUSDSVA** [comment]
Work complete - closing ticket.

**Comment by lunascoop** [comment]
Closing this epic as the work for this effort is complete. The pages are live and react widget confirmed as working.
