### ISSUE TITLE
Create and Launch Feedback Portal within Slack

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#72359]
## Purpose
Implement decisions from previous ticket

Per our latest PO Sprint Review, Matt suggested moving ahead w/ the Slash command, then A/B testing with users to see what might be causing abandonment.

## Tasks
- [x] Create the portal using documentation
- [x] Launch portal for our internal evaluation
- [x] Team review and internal testing

## Acceptance Criteria
- [x] Portal is created internally
- [x] Portal is available for our review
- [x] Team testing is satisfied
- [x] ready to launch
