### ISSUE TITLE
Midpoint Review - IA Feedback - Benefits Non-Disability, Burial 530, Form Updates

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#72354]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through! I really appreciated seeing the flow and all the error messages as well.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

#### Intro page CTA

The [CTA on the authenticated intro page](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/p/F90D6244-3B15-435E-A636-8B3AD3092014/canvas) says “Start the pension application” - it should be updated to reflect this form.

#### Military history page - link to archives

On the [Military history page](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/p/E80CC1AC-3734-47D0-91A9-F8C057932A1C/canvas), the `National Archives` link text should more clearly indicate where the link goes. I recommend mirroring the text on the intro page `Request military service records on the National Archives website`. The link should also open in new window since it's inside the form flow.

#### Military history multi-response intermediary explanatory screen

On the [military history multiple response sequence](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/v/ze5qka/p/E80CC1AC-3734-47D0-91A9-F8C057932A1C/canvas?posX=-10229.143858263034&posY=-412.2413368677719&zoom=0.15510912239551544) that is using the [multi-response multi-page pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page), it's missing the text between the initial data entry and the detail screens, “Now we’re going to ask you some follow-up questions about each of your [items]. We’ll go through them one by one.” This is a crucial part of the flow that helps users understand what to expect on the next screens. 

<img width="488" alt="Screenshot 2023-12-20 at 11 11 59 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/4c07e1da-31a5-407c-8a3e-4f1b29aa5e50">

#### DD214 Upload workflow

Echoing feedback from Design and Content, I recommend moving the DD214 upload closer to the beginning of the form, after the [DD214 or other separation documents screen](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/uuid/A6F3AB03-150F-42F0-9503-647450725032). Research will hopefully clarify if this recommendation makes sense! It might also be worth adding some content to clarify that not only does this `help us process your application faster` but it also `saves you time completing this form`.

#### Military service periods field names/descriptions

Echoing feedback from Accessibility, several of the form fields relating to military service history might be confusing or unclear for users, especially folks who are not Veterans. With these fields being required, too, this could be a blocker. Are all fields truly required? Either way, if possible please include more information about what each field means or might contain. This could be hint text, an additional info component, or another third option - as long as it's consistent. 

These are the fields that weren't clear to me right away: 
 - `place of entry` on the [service period page](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/uuid/31D28529-CB06-4542-98E3-2504DA9E8B1E) (on our [service history pattern](https://design.va.gov/patterns/ask-users-for/service-history), this field is called `Branch of service`)
 - all fields on the [service period detail screens](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/uuid/8CC0CEB0-45D5-41E0-9657-1011B7B836DC)
 - `services rendered` on [previous name screens](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/uuid/0FD35A18-33BB-4F58-8979-4741AE70CCAC)

#### Remove previous name radio inputs on multiple response screen

On the [previous names list and loop](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/uuid/0FD35A18-33BB-4F58-8979-4741AE70CCAC), it seems like including the "Did the Veteran serve under another name?" label and radio buttons is not necessary. Please remove if so.

#### Military service periods dates - level of fidelity

On the military service history date fields, is exact date required, or can the date be an estimate? If only month/day are needed please consider the [approximate dates pattern](https://design.va.gov/patterns/ask-users-for/dates#dates-a-user-can-approximate). Especially since folks are needing to provide a lot of information already, knowing they don't need to provide specific dates might ease the cognitive load a bit. Another approach could be indicating that it's okay to guess. The forms team recently did this, [indicating in the hint text](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/uuid/AF025538-6025-4E79-9BD2-75334304DA58) "It's OK to estimate."

#### File upload max width error

On the [Upload death certificate](https://www.sketch.com/s/de782a35-e147-4c32-a2a8-ba53071ec8e7/a/uuid/894B354D-A105-4FF0-9932-0D907507A93B) screen, I see a sample error message `Image can’t be wider than 5000px`. Though it is an edge case, this could block the flow for users who are not tech savvy. 5000px sounds like a lot, **and** most smartphones have 12 megapixel cameras creating images that are 4032 pixels wide. It's not beyond the realm of possibility to imagine that this 5000 pixel error will be seen as cameras advance (or, if someone takes a photo with a digital camera, or scans a document at a higher DPI). Most of these issues will be caught with the file size limit, but in the case where the pixel limit is the issue, it is worth improving the flow here. 

A few paths forward I could see:
 - List this as a requirement for uploaded files, alongside maximum size (Easiest for developers, puts most burden on user)
 - Increase max allowed width in pixels, keeping filesize requirement
 - Auto-resize images larger than 5000px

<img width="405" alt="Screenshot 2023-12-20 at 10 43 16 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/c80761c1-b5fe-4cbf-b452-fc87082f794c">

**Comment by steele-lm** [comment]
"Must" items have been completed. Moving back to product backlog so outstanding "should" and "consider" can be prioritized after MVP launch.
