### ISSUE TITLE
Collaboration Cycle - Design Intent process improvements

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#72355]
## Problem Statement

The Design Intent is typically the first touchpoint completed by VFS teams in the Collaboration Cycle. The goal of the Design Intent is for VFS teams to share early iterations of their designs so that Governance can provide feedback, encouraging the VFS team to make changes to support the VA.gov Experience Standards. Although the process works smoothly for Governance teams, VFS teams have experienced challenges with the Design Intent around finding feedback tickets, clarity on artifact creation and delivery, too much text to read within the touchpoint page and Collab Cycle Request ticket, and several other problems. 

How might we streamline and simplify the Design Intent experience for VFS teams so that there are less hurdles and steps for them to complete?
How might we improve Design Intent communication to VFS teams so that expectations are clear and easily understood by all?
How might we reduce clutter so that VFS teams are able to complete the necessary steps with ease?

## History
The Platform Service Design team completed research on the Design Intent process in 2 parts. The [first part](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2728526101/Design+Intent+-+analysis+of+Platform+documentation+through+SD+lens) looked strictly at documentation available to VFS teams, and the [second part](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2816475137/Research+Findings+Design+Intent+Experience+Study) included interviews with various VFS teams. The Service Deign team provided recommendations for each pain point/problem identified, and even included an urgency level on a now, soon or later scale. Many of the pain points Governance seeks to address within this initiative originate from the Service Design research studies.
 
### Pain points/challenges with solution recommendations from Service Design
- **GitHub:** Individuals would like to be tagged in their tickets
   - Recommendation: Make this a requirement of whomever is adding feedback to the ticket, to tag at least one point of contact (PM or person who presented the work) in GitHub. Combined with tagging, also labelling them as action items will help surface them as such.

## Suggestions from Matt
 - pre- Design Intent meet and greet? More design-focused opposed to PMs
 - 

## Hypothesis or Bet
If we standardize how we tag, label and notify VFS teams of feedback tickets after the DI meeting, then VFS teams won't miss or overlook feedback, or have to spend extensive time tracking the feedback.

*How will this initiative impact the quality of VFS or Platform teams' work?*
*How will this initiative be easy for VFS or Platform teams? Or how will it be easier than what they did before?*

## We will know we're done when... ("Definition of Done")
- [x] We have updated the DI touchpoint page to better communicate VFS expectations
- [x] We have shortened the DI script and share it within the meeting for better use of time allotted
- [x] We have restructured the template for providing feedback at Design Intent to provide better, more clear direction to the VFS team
- [x] We have provided clear expectations to the VFS team on clarifying scope and boundaries
- [x] We have explored the idea of creating a short informational video on the DI

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
April 2024

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by humancompanion-usds** [comment]
@shiragoodman - Let's talk about this one on Friday. I don't see any issues attached to it. As I understood it Bryan and co. met with you all on potential design intent improvements that are now based on some research. Let's discuss next steps.

**Comment by shiragoodman** [comment]
We have completed all work associated with this epic and the DoD has been met. Closing.
