### ISSUE TITLE
Add Total Failures Alerts to CH 36, CH 31, Burial, and COE

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#72362]
## Issue Description
_The non-disability forms should replicate the level of failure alerting implemented on the 686/674 forms, so we are aware of changes in failure behavior (e.g. regex changes)._

---
## Tasks
- [ ] Add total failure alerts to all non-disability forms

## Acceptance Criteria
- [ ] Chapter 36 alerts if there are total failures
- [ ] Chapter 31 alerts if there are total failures
- [ ] COE alerts if there are total failures
- [ ] Burial alerts if there are total failures
---

**Comment by steele-lm** [comment]
Confirm alerts for the intake work Micah completed.

**Comment by sanjabaj2** [comment]
We have other tickets tracking logging/monitoring work. Let's keep this one back and review if anything is missing after that work is done.
