### ISSUE TITLE
Update references to VFS Team Roster to include Atlas

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#72361]
## User Story
As a Platform team member, I want to ensure our guidance is updated to reference the correct tools so that there is no confusion for VFS teams.

Assignee: @briandeconinck 
Peer Reviewer: @shiragoodman 

## Description
Platform Product team has officially transitioned the VFS Team Roster to Atlas. The purpose of this ticket is to update the New VFS Team Member template, the New VFS Team template, and the Guidance for new teams and team members page on Platform Website.

Note: we are not removing the language "VFS Team Roster" but instead specifying that the  location, ie "VFS Team Roster located in Atlas"

## Impacted Artifacts
[Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members) - flow chart ([Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1621540297622/94e7421ea7c560ea7dcaa1ca54cd6920731f48ae?sender=u0574179b1d97118ccc0e3591))
[New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md)
[New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/new-vfs-team.md)

## Tasks
- [x] Update the user flow Mural and take a snip of the user flow image 
- [x] Replace image on the Guidance for new teams and team members page
- [x] Create a pull request of the New VFS Team Member ticket and change language from:
   - `New VFS team member has been added to the VFS Team Roster` to
   - `New VFS team member has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)` with the link 
- [x] Create a pull request of the New VFS Team ticket and change language from:
   - `New VFS team has been added to the VFS Team Roster` to
   - `New VFS team has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)` with the link 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Platform Orientation has been updated to reference Atlas as the new source of truh

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@shiragoodman Ready for review, code changes are in #72966

**Comment by shiragoodman** [comment]
PR looks good as do other changes - you can close! @briandeconinck
