### ISSUE TITLE
Tools and resources for QA testing

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72367]
## Description
We are working on updating our QA documentation across the Platform

---

## Tasks
- [ ] Refer to the corresponding QA documentation item on this list (the name of this ticket should match an [item on the list](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2882109461/List+of+QA+Docs+to+Audit)
- [ ] Review the document and provide an updated draft version of a revised version for review
- [ ] Once reviewed and approved, update the original page

## Acceptance Criteria
- [ ] Page has been reviewed
- [ ] Changes have been made if needed

**Comment by pjhill** [comment]
LICEcap hasn't been updated in a while, but it does work on Apple silicon, so we can leave it!

**Comment by pjhill** [comment]
QA Product Dashboards are not generally in use and some of the data ingests no longer work. That said, I believe the current plan is to get them going again. So, I'm going to leave the documentation about them in place for now.

**Comment by pjhill** [comment]
wrk2 hasn't been updated in 5 years at this point. There's still some test specs for it in the `devops` repo, so I guess we should continue to explain it in our documentation.

**Comment by pjhill** [comment]
In general, these tools and resources are all still relevant.
