### ISSUE TITLE
Update Form 0781 to fix the date timestamp 

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#72364]
## Issue Description
In our sprint review on December 19, 2023, Emily reported that Form 0781 has the wrong timestamp. From Emily: "Both the datestamp (top right) and signature date (bottom, in the signature field) should exist on every form, and be populated with the form submission date, not the PDF creation date." 

We want to alter the standard PDF date timestamp that is added to the form in the `generate_stamp_pdf` method to use the form submission date. (*the 0781s submission date, but according to Emily, we think this logic really is just triggered inside the 526 submission so there doesn't really seem to be another way to submit it, so we could possibly use the 526 submission date if necessary)

Unknown to investigate: We're note clear on if the PDF date timestamp generates both the datestamp and the signature date mentioned above, so we will have to confirm. If the signature date is absent on 0781, we might want to look at the metadata field created on Form 4142 for an example (the field is called 'receiveDt' on Form 4142). 

---
## Tasks
- [ ] Determine which timestamp is malformed (See VA slack thread [here](https://dsva.slack.com/archives/C04KW0B46N5/p1703086863283479))
- [ ] If results are inconclusive, check VBMS UAT uploads to see that the standard PDF date timestamp is working properly
- [ ] If results conclude that we need a 'receiveDt' set in the form's metadata, add that using the 526 Submission created_at date to follow the new pattern established for Form 4142
- [ ] Ensure any other Form 0781 submission paths use the same timestamping pattern

## Acceptance Criteria
- [ ] All possible submission paths for Form 0781 add a correct date timestamp
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Create a ticket to update this for other pdfs in future.
cc @tommasina-va @RakshindaAslam
