### ISSUE TITLE
Create a project in TestRail

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72370]
## Description
We are working on updating our QA documentation across the Platform

---

## Tasks
- [ ] Refer to the corresponding QA documentation item on this list (the name of this ticket should match an [item on the list](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2882109461/List+of+QA+Docs+to+Audit)
- [ ] Review the document and provide an updated draft version of a revised version for review
- [ ] Once reviewed and approved, update the original page

## Acceptance Criteria
- [ ] Page has been reviewed
- [ ] Changes have been made if needed

**Comment by pjhill** [comment]
Maybe we should move the preamble about TestRail out of the individual guides -- but, I feel like previous content specialists have advised against that because a user could potentially dig directly into an individual TestRail guide using search.

**Comment by pjhill** [comment]
Updated some screen shots, nothing else really needed
