### ISSUE TITLE
Cypress to TestRail Reporter Plugin Configuration

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72375]
## Description
We are working on updating our QA documentation across the Platform

---

## Tasks
- [ ] Refer to the corresponding QA documentation item on this list (the name of this ticket should match an [item on the list](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2882109461/List+of+QA+Docs+to+Audit)
- [ ] Review the document and provide an updated draft version of a revised version for review
- [ ] Once reviewed and approved, update the original page

## Acceptance Criteria
- [ ] Page has been reviewed
- [ ] Changes have been made if needed

**Comment by pjhill** [comment]
Report plugin configuration is still good and accurate, but we should probably add instructions for using the Helper that Tze contributed about 2 years ago. There's a README in the `vets-website` repo, but we should probably create a new page for the tool on the Platform Website. Will work that effort under a different ticket.
