### ISSUE TITLE
Other helper functions

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#72385]
## Description
We are working on updating our QA documentation across the Platform

---

## Tasks
- [x] Refer to the corresponding QA documentation item on this list (the name of this ticket should match an [item on the list](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2882109461/List+of+QA+Docs+to+Audit)
- [x] Review the document and provide an updated draft version of a revised version for review
- [x] Once reviewed and approved, update the original page

## Acceptance Criteria
- [x] Page has been reviewed
- [x] Changes have been made if needed
