### ISSUE TITLE
[Design] QA Designs in Staging

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7238]
## User Story or Problem Statement
Problem description. How might we ensure that the UI is consistent across both the Invision prototypes and staging?

## Goal
_The UI in staging matches the Invision prototypes_

## Objectives or Key Results this is meant to further
- _Finalize the MDT in staging for usability testing_
---
## Tasks
- [ ] _The design team will review and compare the most up-to-date UI in staging with the Invision prototype_
- [ ] _If any updates are needed on staging, the design team will meet with the frontend team to review those changes_
- [ ] _Document meeting notes in GH, link to this ticket_
- [ ] _Create tickets for FE as needed_

## Acceptance Criteria
- [ ] _The frontend and design teams will be on the same page about the tool's UI and any necessary updates_
---
