### ISSUE TITLE
Upgrade Cypress to 13.x in `vets-website`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#72406]
# Description
Given that the issue with Cypress downloads has been worked around by storing the desired Cypress package in our own S3 bucket, we should now be able to proceed with upgrading to Cypress 13.X. As of the editing of this ticket, the latest version of Cypress is 13.11.

For reference, here is an old PR that had Cypress 13 working with our codebase some months ago. --

- This [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27137) was working at one time before the download started failing. Please note that it involves skipping several keyboard navigation tests.

# Tasks
- [x] Download latest version of Cypress
- [x] Work with IST to store the Cypress package in our S3 bucket
- [x] Update the CI process to use the new version of Cypress in our S3 bucket
- [x] Troubleshoot any issues with E2E test specs resulting from the upgrade

# Acceptance Criteria
- [ ] `vets-website` is using the latest version of Cypress 13

**Comment by pjhill** [comment]
Cypress is currently running 12.17.3. As of today (6/5/2024) the latest version of Cypress is [13.11.0](https://docs.cypress.io/guides/references/changelog#13-11-0).

I believe the major issue with this one was that the download was failing. This was resolved by storing the Cypress download in our S3 bucket. We should be able to do the same for this Cypress version.

**Comment by pjhill** [comment]
Requested that a teammate stage the Cypress download in the `vetsgov-website-builds` s3 bucket. [Link to Slack message.](https://oddball.slack.com/archives/C044Z57LS2Y/p1717703387285369)

**Comment by pjhill** [comment]
Draft PR [here](https://github.com/department-of-veterans-affairs/vets-website/pull/30213). Waiting for the Cypress download to be staged in the S3 bucket to update the [install action snippet ](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/install/action.yml#L50)to pull the new version.

**Comment by pjhill** [comment]
Running into an issue where the wrong version of Cypress is running. According to this readme about the Cypress images, there is NO Cypress version included in the category of image we are running --
https://github.com/cypress-io/cypress-docker-images/blob/master/README.md

**Comment by pjhill** [comment]
After logging out what is happening during the dependency installation, I see this -- 
<img width="317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d24a1df0dffeaf09cbf6f4f46ad08533ae746ebc/image.png" alt="image.png" />
Intriguing...

**Comment by pjhill** [comment]
`yarn install` does not appear to appropriately install the Cypress package retrieved from S3. I'm not sure entirely why. This seems to be resolved by a `npx cypress install` after the yarn install.

**Comment by pjhill** [comment]
For completeness sake, I did go down the road of updating the Cypress image being used for testing, but it was not required. I created a separate ticket to work on that upgrade process [here](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/85477).

**Comment by pjhill** [comment]
In order to get Cypress 13.11 in place I needed to skip the following tests --
- src/applications/appeals/995/tests/995-supplemental-claim-maximal.cypress.spec.js
- src/applications/disability-benefits/all-claims/tests/all-claims-keyboard-only.cypress.spec.js
- src/applications/edu-benefits/feedback-tool/tests/00.feedback-tool.cypress.spec.js
- src/applications/edu-benefits/feedback-tool/tests/01.feedback-tool-keyboard.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/keyboard-nav-test/secure-messaging-compose-error-message-keyboard-nav.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/keyboard-nav-test/secure-messaging-compose-keyboard-nav.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/keyboard-nav-test/secure-messaging-keyboard-nav-save-draft.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/keyboard-nav-test/secure-messaging-keyboard-nav-to-compose.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/secure-messaging-compose-errors.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/secure-messaging-custom-folder.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/secure-messaging-draft-save-with-attachments.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/secure-messaging-save-draft-errors.cypress.spec.js
- src/applications/mhv-secure-messaging/tests/e2e/secure-messaging-save-draft.cypress.spec.js

**Comment by pjhill** [comment]
PR is passing all checks -- pending review.
