### ISSUE TITLE
[FE] My VA: Unit test coverage work break-out

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#72407]
## Background
Allison reviewed the status of our unit test coverage in #68659 and provided recommendations for next steps. This ticket is to capture the work to break out the recommended path and create tickets for that work.

_If bandwidth allows within sprint 26, the tickets created as part of this work can be pulled in._

## Tasks
- [x] Review findings and recommendations [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68659#issuecomment-1799953853)
- [x] Review #57462 to see if it covers any of the recommended next steps
- [x] Create additional tickets to address unit test improvements and put them in test improvement epic: #61602  

## Acceptance Criteria
- Additional tickets for unit test improvements are created

**Comment by ajakabcin** [comment]
Met with Allison and we decided on three tickets in addition to the existing one for actions (#57462):

- utils: #72511
- helpers: #72514
- EducationAndTraining: #72516
