### ISSUE TITLE
[CST] Update UI of the Status tab

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#72409]
## Value Proposition
As a veteran with a pending disability claim, I want the Status tab to provide up-to-date, relevant information about what is going on with my claim, and inform me if there are any actions I need to take to advance the claim. 

## Design
[Figma Link](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=80-1335&mode=design&t=lQSiQjyc2RfpqXEi-4)

## Background
As part of our evidence request initiative, we want the Status tab to focus on Veteran and VA actions and timely updates. The new design reflects Veterans' desires to understand if there is anything they need to do to advance their claim, as well as see any recent actions the VA has taken.

## Considerations
This should be worked _after_ [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69449).

The new content should be behind the feature flag cst_use_claim_details_v2

## Design Approach 
New design
<img width="773" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL041QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2144c6f5a8d49f10de2a043bd112a477e46db230/Screenshot%202023-12-20%20at%2010.52.03%E2%80%AFAM.png" alt="Screenshot 2023-12-20 at 10.52.03 AM.png" />

## Tasks
- [ ] Create a claim status header and subheader
- [ ] Create a progress label that shows "In progress" or "Completed" with timestamp showing when the claim was most recently updated
- [ ] Create "What you need to do" section, which shows [Veteran requests when they are present](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-809&mode=design&t=86Am7C7RS1Fif8Km-0), and [shows an empty state string when they are not](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-593&mode=design&t=86Am7C7RS1Fif8Km-4). 
- [ ] Create "What we're doing" section, which contains a card showing which step in the process the claim is in. It also contains a "Overview of the process" link, which takes the user to the Overview tab.
- [ ] Create a "Recent Activity" section, which includes updates about tracked items and other claim activity. [NOTE: This needs to be specified in greater detail, which Skyler will work on.]
- [ ] Replace the old "Need help" component with the new "Need help" footer.

## Acceptance Criteria
- [ ] Header and subheader match the design spec for the Status tab.
- [ ] Progress label matches the status of the claim and "Last updated" timestamp is accurate and matches the most recent update from the Recent Activity section.
- [ ] "What you need to do" section shows the correct empty state string when there is no Veteran requests. When there are Veteran requests, it shows the request card with the correct information in it.
- [ ] "What we're doing" section has the card showing the correct step and matches the step that is in the Overview tab. Clicking on the link takes the user to the Overview tab. 
- [ ] The UI of the "Recent Activity" section matches the design spec for the Status tab. The correct updates show up in the "Recent Activity" section. [NOTE: This needs to be specified in greater detail, which Skyler will work on.]
- [ ] The "Need help" component is updated with the new [Need Help component](https://design.va.gov/components/form/need-help) as a footer on the Status tab.
