### ISSUE TITLE
[FSR 3.0 - PI1/24] FSR/SW 3.0 FE 5655 form data lifecycle (Code Cleanup A)

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#72412]
## Outline
The goal of this epic is to define the lifecycle for form 5655 data. 

### Problem: 
Currently in progress data persists after a form is submitted which can be problematic if a user returns to submit another FSR. 

### Goals:
 - [x] Remove stale in progress form data 
 - [x] Clearly define lifecycle for in progress form data
 - [x] Clearly define lifecycle for submitted form data

## High Level User Story/ies
As a engineer working on the FSR, I need to know how to handle form data so I can maintain the code base.

## Definition of done
 - [x] Clearly defined lifecycle for all form data in the form of documentation
 - [x] New lifecycle methods implemented
 - [x] Stale / legacy data has been cleaned up

### Adding helpful notes in description so they don't get lost in comments
 - Form 526 has a save form controller that removes in progress forms once submitted:
   - [PR to destroy submitted forms](https://github.com/department-of-veterans-affairs/vets-api/pull/14142)
   - [Code diff for above](https://github.com/department-of-veterans-affairs/vets-api/commit/53989864f07fbb68628fbf7667347a8ba929c13e) (pr diff got weird)

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by kjsuarez** [comment]
## Thoughts on the relationship between InProgressForm & Form5655Submission

#### Currently
- The InprogressForm for a 5655 submission is not destroyed unless it expires of natural causes
- Users can immidiately resubmit a successfully submitted InProgressForm as many times as they want
- Form5655Submissions do not store almost any form data and rely on the corresponding InProgressForm if this data is needed (resubmission)
-  The user has no notion of their existing/pending submissions except via email

#### Kevin's perfect world
- When createing a Form5655Submission the form data is stored on an encrypted column of the Form5655Submission, removing the need to rely on the InProgressForm for any reason post-submission
- When a form5655Submission is successfully created, its corresponding InProgressForm is deleted
- The user can choose to rehydrate an InProgressForm from the frontend via existing submissions.
