### ISSUE TITLE
Design | Migrate to Figma | Consolidate selected Sketch files/pages into Sketch Archive file for My VA

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#72410]
## Background
The AE UXers have decided that the best way to archive files/pages in Sketch that are no longer actively being worked on is to move them into a dedicated "archives" Sketch file, and then migrate that file for reference purposes. This is less time-consuming than exporting boards and uploading them to an archival folder in our repo. It will be easily accessible in our new tool as needed.

## Tasks
Move My VA files to  [AE Sketch Archive](https://sketch.com/s/d5237db2-f48d-4fe4-8554-d32065994609) sketch file. 

**Note**: Each top level area (Personal information; Profile hub) has a corresponding Page within the AE Sketch Archive file where all the respective boards can be copied.

- [x] Sync with Angela, AJ, and Samara about what My VA Sketch files can be deprioritized and archived
- [x] Add list of those files into this story to document what's being moved
- [x] Import into Figma
- [x] Provide minor adjustments to the files as necessary

## Acceptance criteria

My VA Sketch files determined to be ready for archiving are imported to Figma and moved into the archive file: 
- [x] Notification Center MVP 
- [x] My VA Overall Structure Explorations
- [x] My VA and Profile - Nametag
- [x] My VA Benefit Payments and Debts v2 - Usability testing
- [x] "My VA Final" (legacy file)
- [x] Action Items

## Out of scope
- Any files that need to be archived and also require extensive edits

**Comment by mattmarino-adhoc** [comment]
Estimated too high for archiving just the My VA files, this was really a 1.
