### ISSUE TITLE
[Reference] AMA Follow On Work: Launch

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#7242]
## User Story or Problem Statement
As a Veteran, I need to understand the new decision review process so I can choose the proper lane(s) when appealing a claim decision that I disagree with.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
-Veterans proceed from informational pages to an action (tracking appeal status, linking to HLR tool, downloading a form) demonstrating that they got the information they need to proceed with their appeal. 
-More users take actions related to Supplemental Claims or Higher-Level Reviews than actions related to Board Appeal, demonstrating that we have not inadvertently led users to believe that "board appeal" is the only (or the first) appeal option available to them. 

## Tasks
- [x] **Mikki** shares IA by 3/27, attaching to ticket #6920 
- [x] **Jen** reviews IA and provides feedback by Monday 3/30

- [x] **Laura** documents final piece of feedback from Jen (replacing "time frame" language, and hands off to Randi by 3/26

- [x] **Randi** makes "time frame" edits by Monday 3/30

- [x] **VSP Collaboration cycle** meeting (Friday 3/27) to identify any VSP issues

- [x]  **Randi** updates NODE IDs and closes ticket [6692](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6922) by Wednesday 

- [x]  **Randi** implements IA into Drupal pages by Wednesday 4/1 (dependent upon Mikki delivering IA and Jen reviewing it above)

- [x]  **Laura** puts Drupal preview links and Mikki's IA link in an email with SMEs, giving them 48 hours to  flag any factual errors (email to be sent on Wednesday 4/1). [IA request](#6920)

- [x] **Laura** to provide preview links for VSP team. 

- ~[ ] **Team** Implement analytics tracking per VSP feedback - #7558~

- [x] **Mickin/Team** complete [Staging Review](#7521)

- [x]  Publish 12 pages on (4/16):

- [x] 1. Decision reviews and appeals:  preview-prod.vfs.va.gov/preview?nodeId=3071
- [x] 2. After you request a decision review:  preview-prod.vfs.va.gov/preview?nodeId=3008- [ ] 
- [x] 3. Supplemental Claims:  preview-prod.vfs.va.gov/preview?nodeId=3011
- [x] 4. Higher-Level Reviews:   preview-prod.vfs.va.gov/preview?nodeId=3003
- [x] 5. Board Appeals:  preview-prod.vfs.va.gov/preview?nodeId=3029
- [x] 6. After a Board Appeal: preview-prod.vfs.va.gov/preview?nodeId=3013
- [x] 7. Multiple party contested claims: preview-prod.vfs.va.gov/preview?nodeId=3030
- [x] 8. Fiduciary claims: preview-prod.vfs.va.gov/preview?nodeId=3016
- [x] 9. Insurance claims: preview-prod.vfs.va.gov/preview?nodeId=3025
- [x] 10. FAQs: preview-prod.vfs.va.gov/preview?nodeId=3004
- [x] 11. Get help with review request: preview-prod.vfs.va.gov/preview?nodeId=3009
- [x] 12. Board hearings with a VLJ:  preview-prod.vfs.va.gov/preview?nodeId=3010

- [x] [TBD](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7650#issuecomment-609968725) - add new link to mega menu

## Acceptance Criteria

- [x] All decision review pages are live in Drupal

---
## How to configure this issue

- [x] **Attached to an Epic** 
Epic [6421](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6421)

**Comment by mnorthuis** [comment]
IA is attached to issue #6920 with 2 open questions.

**Comment by lwalsh617** [comment]
@RLHecht - Here's a word doc with all final copy edits to Drupal pages. Thank you!
[decison-review-drupal-edits-032620.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4389384/decison-review-drupal-edits-032620.docx)

**Comment by jenniferlee-dsva** [comment]
IA ticket review and 2 questions for @lwalsh617 and @mnorthuis here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6920#issuecomment-604710450

**Comment by MickinSahni** [comment]
Thanks for opening this, Laura. I'm not seeing any Must accessibility items here that aren't CMS (i.e. global) accessibility issues except for https://github.com/department-of-veterans-affairs/va.gov-team/issues/6697 which is dependent on https://github.com/department-of-veterans-affairs/va.gov-team/issues/6799.

**Comment by MickinSahni** [comment]
Open question - what should we send SMEs for final approval (with left nav changes)? Mockups? Drupal link? 
 - Anticipating roughly 2 days
 - @lwalsh617 to create ticket for left nav work

**Comment by jenniferlee-dsva** [comment]
Nav question: Initially we had informed SMEs we wouldn't be able to provide these as previews. But it looks like that functionality is now available in Drupal, so we should if that's true. 

Sending to SME question: I recommend Drupal preview links: 1/for the experience and 2/ for each page, so they have an inventory of every page.  I recommend using a PDF that includes each preview page with changes noted or highlighted instead of a copydeck, since Laura already provided them a walk through of form factor changes to come.

EX: PDF attached. Drupal previews can be 'saved as' PDFs from print and combined easily.

**Comment by MickinSahni** [comment]
@lwalsh617 to reach out to SMEs!

**Comment by lwalsh617** [comment]
Elizabeth Murphy provided Board feedback last night. Adding screenshots here for tracking. 

<img width="1033" alt="Screen Shot 2020-04-10 at 12 53 59 PM" src="https://user-images.githubusercontent.com/53535663/79008091-9f51c300-7b2a-11ea-91d1-bf50e8cd0559.png">
- [ ] Edit made in Drupal

<img width="1099" alt="Screen Shot 2020-04-10 at 3 32 32 PM" src="https://user-images.githubusercontent.com/53535663/79017943-8c49ed80-7b40-11ea-9c87-dcd2e494cb87.png">
- [ ] Edit made in Drupal

<img width="1080" alt="Screen Shot 2020-04-10 at 3 44 07 PM" src="https://user-images.githubusercontent.com/53535663/79018597-2e1e0a00-7b42-11ea-9d3d-c2be59f4470f.png">
- [ ] Edit made in Drupal

**Comment by MickinSahni** [comment]
> Elizabeth Murphy provided Board feedback last night. Adding screenshots here for tracking.
@lwalsh617 @tzelei will this require updates to the test cases? I'm not sure since we just reference a copy deck in TestRail for the hub page test case (C459), but mention copy specifics for the page title test case (C454).

**Comment by lwalsh617** [comment]
^ @MickinSahni @tlei123 I didn't make her edits to the page titles, as we had already edited them prior to getting her feedback. The only edit (which was the same on each page) --was removing the reference to "video conference hearing" in the second bullet under "Note" in the Board appeal section. So, this shouldn't impact hub page test case or page title test case. Hope that helps. L

**Comment by lwalsh617** [comment]
Sent email to SMEs on Friday. Need to follow up with them on our launch date/time.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @mnorthuis -- 
AMO/Fred recommend that we **NOT** retire the BVA hearing page. Rationale is in the attached Word doc. 
**JEN**--specific copy feedback is captured in this doc as well. Please let me know if you have any objections to his requests. Otherwise, I'll go ahead and make edits. 
Liz Murphy said she is sending edits to Board Appeal page. I'll post those here as soon as I get them from her. Thanks!
FYSA - @RLHecht @MickinSahni @stephorkandatx 
[AMO 3 issues for review - 4.10.20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4481922/AMO.3.issues.for.review.-.4.10.20.docx)

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 Only saw 3 edits - all look factually needed, so lgtm. 

**re not retiring the legacy BVA hearing page** - If they will not retire the [legacy-appeal related Board page](https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/) - then we may need to do a couple of things that need Mikki's guidance. 

I think all this can be pulled out of the launch to do as a post-launch work, if that works better.  

**Items for Mikki to provide guidance on:**
1/ Consider adding the legacy Board page BACK to the left nav, so that it is findable again. 
- Fred and team had originally asked for the link to be removed from the nav, but it doesn't make sense if it still needs to be available to Veterans as they claim, unless we really think it is fine that it's available only through body copy link from the `Manage a legacy appeal` page. 

2/ The H1 name of the legacy Board page may need to be modified in order to be crystal clear that it's only relevant/valid for older appeals in the legacy process. (Similar to how we changed the appeals page H1 to "Manage a legacy VA appeal." Like:` Board hearings for legacy appeals `or whatever. 

3/ We may need to change the URL `/file-an-appeal/board-of-veterans-appeals/` to match the updated URL of the legacy appeal page, which I believe will (with this launch) change from 'file an appeal' to manage/legacy something. 

4/ On the legacy Board page https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/ - there is a link and reference to VA Form 9, _which I think is okay,_ but might be good to ask the business to review the page and identify if there are any references to outdated form that need to be scrubbed.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @mnorthuis - Here is the Board's feedback. They concur are not retiring the BVA page. They have substantive changes on the Board Appeal page. 
FYSA - @stephorkandatx @MickinSahni @RLHecht

**Comment by tlei123** [comment]
@MickinSahni @lwalsh617 , re. the upcoming changes discussed today \[Wed 4/15]...

IF some changes are decided to be post-launch, would a **design-freeze** be feasible once the PRE-launch changes are done in InVision?  \[Such a freeze would be lifted immediately after I QA the pre-launch changes.]

I'd hate to log false-positive bugs in case I run my updated test-case for pre-launch changes, only to find out the InVision prototypes have evolved ahead with post-launch changes.  The only other way to manage this \[that I can think of right now] would be for @lwalsh617 to attach static screenshots of the pre-launch changes to some new Test Plan ticket.

Please let me know.  Thanks much!

**Comment by RLHecht** [comment]
@lwalsh617 @MickinSahni @jenniferlee-dsva @stephorkandatx All the Decision Reviews pages are set to published! The CMS team is following to make sure there aren't any broken links or other issues that are coming up before the deploy. I still need to add the link in the mega menu but am awaiting what the exact text is. I believe we are putting a link to the main/decision-reviews page under the Disability section as the last option in the "Manage" section but should the text be "Decision reviews and appeals"?

**Comment by mnorthuis** [comment]
@lwalsh617 In regards to the BVA page, we will need to move that out of Disability, assign a new URL and redirect the old.  Can we do that under a separate ticket to follow up this work?

We can do the additional links across the hubs to Decision Reviews in a separate ticket as well.

**Comment by lwalsh617** [comment]
@mnorthuis Sure thing, Mikki. I'll start a new ticket now.

**Comment by RLHecht** [comment]
Launch complete! Closing ticket.
