### ISSUE TITLE
VA partner request: Update Vietnam War eligibility info on Veterans Pension eligibility page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#72424]
## Issue Description
Pension stakeholders asked us to make changes to the Vietnam Era bullet on our [Eligibility for Veterans Pension](https://www.va.gov/pension/eligibility/) page because they said the current language is confusing. 

Their suggested edits:

Vietnam War dates for Veterans who served
o	in the Republic of Vietnam from November 1, 1955, to May 7, 1975, or
o	outside the Republic of Vietnam from August 5, 1964, to May 7, 1975.

We'll need to edit these changes so that it adheres to VA.gov style and meets plain language standards.

## Tasks
- [x] Update page in Drupal
- [x] Send to stakeholder for approval
- [x] Copyedit
- [x] Publish
- [x] Notify stakeholder that changes are live

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by RLHecht** [comment]
We made these edits and notified the stakeholder that we published the page. We also made the same change on the Survivors Pension page and published as well. Moving to validate.

**Comment by RLHecht** [comment]
Changes are live. Closing.
