### ISSUE TITLE
[UX] [Content] Decide whether to have modality-specific error pages or modality-agnostic error pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72429]
## Description 

Currently, we have different content on error pages for each appt modality, e.g., phone vs in-person. Knowing that we're adding VVC and CVT, we need to decide if it makes more sense to have separate error page content per modality or have it be more modality-agnostic, e.g., "something went wrong, here's a couple ways to contact VA." 

In addition, there are scenarios where pre-check-in could include more than 1 type of modality. So, the error page content could get unruly if we're having to list out content for 4 different modalities.  

Includes [ID verification error page on 4th attempt](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/K0R4yx1#Version). 

## Tasks

- [x] Identify (and/or have an understanding of the) differences between error pages for in-person vs phone pre-check-in (using [Sketch](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744#Version), staging and/or [error types in Git](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/analytics/error-types.md))
- [x] Understanding that we're going to be adding VVC and CVT appts to pre-check-in, talk to engineers about the pre-check-in error pages and see if they have an opinion, architecturally, for whether it makes more sense to have specific content per modality or generic content. (Brian has confirmed that switching to modality agnostic content would be preferable, i.e., one error page has content that supports any modality.)  
- [x] Document decision in ticket
- [ ] Create f/u tickets for wireframes and content 

## AC 

- [ ] Decision documented
- [ ] F/u tickets created for wireframes and content

**Comment by kellysmith1008** [comment]
[Finished the audit of all the error screens](https://docs.google.com/document/d/1wFbf2Pn8_CBJ8EMEeJ99buGwWokYMN7eUODSG9tou1k/edit?usp=sharing). I need to mock up some rough ideas first, but I have a feeling the answer here is going to be the same as we've already set a precedent to include both in-person and phone appointments in some error messages.

**Comment by kellysmith1008** [comment]
[Ticket created for wireframes and content work](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/74108). Closing this ticket

**Comment by benbrasso-agile6** [comment]
LGTM
