### ISSUE TITLE
Add DataDog Documentation to Documentation Bot Mapping

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72420]
## Description 

- Feature: Map DataDog documentation in the documentation bot (using [Platform Support Responses](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=604576535)) 
- Hypothesis: If we map the proper documentation to the applicable tickets, we will receive less questions about how to get access.
- Acceptance Criteria: Documentation is properly mapped to the documentation bot auto responder for DataDog related requests

---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Add topic and link to documentation (talk to Johnny/Alyssa to determine page to share)
- [ ] Verify properly mapped with Joe/Curt
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
We have verified that the topic "DataDog" (#35 in the [Platform Support Responses](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=604576535) doc) is properly mapped to the correct documentation (listed as #35 in the documentation bot auto response tab (in the [Platform Support Responses](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=604576535) doc). Complete.
