### ISSUE TITLE
Investigate reason for Puma backlog

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#72438]
## User Story
As the managers of the Puma servers, 
It is important to have the optimal configuration in place for Puma servers
So that Vets-API availability remains consistent and high-functioning for those who utilize the APIs. 

## Summary
We have a monitor, [[Prod] [EKS] Puma Backlog](https://vagov.ddog-gov.com/monitors/116657), that notifies us when the Puma backlog is over a threshold for an amount of time. Vets-api pods in EKS spin up in response to this and then scale back down when the backlog has gone down, so there's no immediate action that needs to take place in response. However, the ideal situation is for the Puma backlog to be at zero. Why is there ever a backlog?

As a band-aid solution to quiet this noisy alert, we changed the monitor to average over 15 minutes instead of 5. See https://github.com/department-of-veterans-affairs/devops/pull/13825.

This issue was discussed at BE CoP meeting. [Meeting notes](https://vfs.atlassian.net/wiki/spaces/BCP/pages/2876473345/12+18+23#2%EF%B8%8F%E2%83%A3--Discussion).

There is a [recurring scheduled downtime](https://vagov.ddog-gov.com/monitors/downtimes?id=7cab24d2-82fa-11ee-a5b1-da7ad0900007&sort=-start_dt). The alert gets muted every day from 3-4 ET. Kyle set that up because that was a predictable time of day that it would trigger the alert. 

## Tasks
- [x] Investigate why the Puma backlog is ever greater than zero. 
- [ ] Create design document for Puma servers
- [ ] Make new tickets based on findings. Or if the fix is small, implement it. 
- [ ] Document reasons for Puma backlog and indicate where it is stored **here**

## Success Metrics
- [ ] There is reasoning for the larger Puma backlog
- [ ] There is a documented and approved strategy for addressing the Puma backlog

## Acceptability Criteria
- [ ] Output includes Puma servers design document
- [ ] Documentation is complete for this research
- [ ] New work is ticketed for future Sprints

**Comment by rmtolmach** [comment]
Comment posted by @LindseySaari in https://github.com/department-of-veterans-affairs/va.gov-team/issues/66255#issuecomment-2043433561
> Some things that could potentially contribute to the puma backlog
> 1. Sudden spikes in traffic - the demand may outpace the rate at which free threads are available and additionally for HPA to catch up since we have an initialDelay of 30 seconds
> 2. The initialDelaySeconds: 30 means each newly created pod won't start accepting traffic until at least 30 seconds after it's been started.
> 3. Even with round-robin load balancing, not all requests are equal. Some might require significantly more processing time than others. This can lead to situations where pods get backed up processing a few resource-intensive requests even if they're under the threshold for scaling. Do we need some more bulkheads? Could we consider some advanced load balancing strategies?

**Comment by jennb33** [comment]
This work ties into the 5XX errors 
We may need to bump this until after the 5XX errors are resolved; it could rework.
@LindseySaari should this ticket move to another Sprint?

**Comment by LindseySaari** [comment]
I think this ties in nicely with the spot we've arrived at right now. I think @rmtolmach can work closely with @ericboehs and myself. Our latest change is to adjust the failureThreshold. We're thinking that pods aren't being taken out of commission soon enough when they're saturated, causing a backlog

PR here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2921

We may even be able to reduce this further. We also want to apply all the prod configs here to lower envs:

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2919
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2918

**Comment by rmtolmach** [comment]
I started a document with notes for myself https://vfs.atlassian.net/wiki/spaces/~121859534/pages/3247767579/Puma+backlog+investigation

**Comment by jennb33** [comment]
From the Stand on 6/26: need to investigate the reason why a backlog occurs during synch with Appeals. @rmtolmach @LindseySaari

**Comment by rmtolmach** [comment]
**End of week update:**
- The backlog during deploy (and other times) has been very low this week.
- Puma design document has not been started.

**Comment by jennb33** [comment]
This ticket has been duped for Sprint 5 as [87375](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87375), at 3 story points, in case the work is not completed in Sprint 4.
