### ISSUE TITLE
Labeling for Tier 2 Support Ticket Tracking 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72441]
## Description 

This ticket will house the task of cross communicating the message that is in this related ticket: https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/71225

Specifically these steps:

- [ ]  Make sure your name is listed under assignees
- [ ]  Add your team's label under labels [our label is platform-product-team]
- [ ]  Add the ticket to THIS sprint
- [ ]  Work the ticket :)

Note: This changes the process of assignees for Tier 1. Historically we have owned the ticket from start to finish, but Tier 2 will need to add their names as assignees and perform other related steps above. Needs discussion.

---

## Definition of Done
_What must be done to officially complete this task?_

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Discuss in a one-off meeting the impact on Tier 1 and plan out logistics of what this process looks like for Platform Suppport
- [ ] Add the above tasks listed in the description to our existing Advanced Support Best Practices (Tier 2) support tickets
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate in [this thread](https://oddball.slack.com/archives/C056EG9KU0G/p1701804055152589) and in #platform-tech-team-support and #vsp-product-managers
- [ ] Schedule conversation to discuss best way to get a Tier 2 assignee added (whether they add themselves or we add it for them)

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
This is not something our team has to own, engineer focused for other support they offer. Our team support time is tracked by the time Tier 2 is on support (roughly 80 hours) and doesn't need to be tracked otherwise using the process above.
