### ISSUE TITLE
Platform Support Takeover of Atlas

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#72449]
## Issue Description
Platform Support is taking over adding VFS Teams and Team Members to Atlas, to replace the VFS Roster. 
Tasks will need completion prior to this becoming a regular duty.

---
## Tasks
- [ ] Product Team (Lainey Trahan, Rachal Cassaty) sets up Tier 1 members for access to Atlas
- [ ] Tier 1 team member Atlas orientation
- [ ] Tier 1 Support will begin adding VFS Teams and VFS Team Members to Atlas
- [ ] Support Best Practices pages updated with process for adding Teams & Members to Atlas

## Acceptance Criteria
- [ ] Tasks above are completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alyssagallion** [comment]
Process taken over and work was done in other tickets. Closing.
