### ISSUE TITLE
[MVP] Step 4: Revisions to page flow, order and questions for marriage information

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72455]
## Issue Description
As a Pension team reviewing and QA'ing the Pension form flow,
we need to make revisions to the existing experience in Staging for Step 4 of the form, related to Marriage information,
so that it better aligns with the [expected form flow logic as documented](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703103128492/30dc0956f99482beffb457eb2ae884430cc2d3f4?sender=u9d01ee38af217e4877e75660) for our team here.

---

## Designs
- Mural visual references for the tasks below found here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=29-1703173367057
- Sketch designs: https://www.sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/prototype/BA40837F-A38E-44EE-874E-0D7C1A5EB65E/a/BA40837F-A38E-44EE-874E-0D7C1A5EB65E

## Tasks

_**Validation info: For marital status answers "Married" or "Separated", follow the pages/question flow below:**_

- [x] Remove the pages with redundant questions from the form flow, as shown on the [screenshots of this Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=29-1703173367057):
-- Current spouse's name (this page only has 4 fields: spouse's first name, middle name, last name, suffix)
-- Current marriage information (this page only has 1 question: Date of marriage)
-- Financial support for your spouse (this page only has 1 question: How much do you contribute each month to your spouse's support?)

- [ ] Re-order existing pages within Step 4, as shown on the [screenshots of this Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=29-1703173367057).

**In the veteran's former marriage information page(s)...**

- [x] Remove the question "Type of marriage" from veteran's prior marriage information pages (but keep for current marriage information)

**In the current marriage page...**

Update the "Type of marriage" field answer options:
- [x] Remove the answer options for Common Law, Proxy, Tribal
- [x] Leave Ceremonial and Other
- [x] Add a short text field for "Other"

**In the current spouse information page...**

- [x] Combine questions "Is [_current marriage name_] also a veteran?" and "What is their VA file number?" into one question.
The question will be:
`Is [_current marriage name_] also a veteran?`
`No`
`Yes`_add a short text field for this option_

- [x] Remove the question: How many times has your spouse been married?
- [x] Display the following fields if they answered "Separated" or "Married"
-- Spouse address fields
- [x] Display the following questions only if they answered "Separated"
-- What is the reason you do not live with your spouse?
-- How much do you contribute monthly to your spouse's support?

- [x] Change question format for "What is the reason you do not live with your spouse?" to radio button answers with the options:
-- Medical reason
-- Marital discord
-- Work
-- Other: _add a short text field for this option_

_**Validation info: If they answer "Yes" to "Has your spouse been married before?**_
_Show the list loop page for Spouse's former marriages_

_**Validation info: For marital status answers "Never married" or "Widowed" or "Divorced", follow the pages/question flow below:**_
_If they answer "Never married" or "Widowed" or "Divorced", skip any other pages related to marriage information and jump straight to the section/pages about Dependent Children._

## Acceptance Criteria
- Step 4 of the Pension form will no longer have redundant question fields for current spouse's name and date of marriage
- The pages for Step 4 section of the Pension form, related to marital information, will be reordered to align with the [expected form flow logic as documented](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703103128492/30dc0956f99482beffb457eb2ae884430cc2d3f4?sender=u9d01ee38af217e4877e75660) for our team here.
- "Type of marriage" will be removed from veteran's former marriage information pages  
- "Type of marriage" answer options will be updated to align with the PDF question format ([Question 6F on the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf))
- If a veteran's current spouse is also a veteran, we will ask for their VA file number, but remove the show/hide logic to reduce accessibility concerns.
- The question for "How many times has your spouse been married?" will be removed
- The fields for Spouse's Address will display if they answered "Married" or "Separated" to "What is your marital status?, not based on the answer logic of the question above it.
- The fields for What is the reason you do not live with your spouse? and How much do you contribute monthly to your spouse's support? will **only** display if they answered "Separated"  to "What is your marital status?
- The answer options for the "What is the reason you do not live with your spouse?" question will align with answer options for the same question on the PDF form ([Question 6I on the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)).
- If the use answers "Yes" to "Has your spouse been married before?", they will see the Former spouse's marriage questions list loop page
- If the user answers "never married", "widowed" or "divorced", to "What is your current marital status?" and they will skip all the follow-up pages of marriage-related questions and jump straight to the section/pages about Dependent Children.

**Comment by mayacoforma** [comment]
Update on #72455: "Revisions marriage section"

I created a screenflow and prototype of all the paths a user can take in the marriage section (married, never married, separated, widowed, divorce) to provide clarity to the team 
.Png of the screenflow 
Prototype:  https://sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/a/zy3y3yo/play

I'm seeking feedback from @vbellissimo  on the questions asked in the divorced and widowed flow. 

Widowed:
Is the date of the spouse's death required?
Is the place of the spouse's death required?
Divorced:
Is the reason for divorce required?
Is the marriage end date required?
Is the place where the marriage ended required?

Please leave comments and feedback in Sketch on the 📸 #72455 page. 

<img width="713" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemlDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44a9f1106c2d9b7d50adce5a3647f2a5c41491a4/%2372455%20screenflow.jpg" alt="#72455 screenflow.jpg" />

**Comment by mayacoforma** [comment]
I have incorporated the feedback from the VBA as well as Vicky and Julie's suggestions into the designs and prototype. Please find a recorded walkthrough of the proposed flow below:

https://drive.google.com/file/d/19-JIraPo_IR-A47-_Wmx8uvHWcHgoMNu/view?usp=sharing

@vbellissimo , would you mind reviewing and confirming if we are in alignment regarding the sequence and arrangement of the questions?

**Comment by mayacoforma** [comment]
@vbellissimo 

Here's the finalized prototype and screenflow. 

Prototype: https://sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/a/zy3y3yo/play

[#72455 - Screenflow.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c9dde65a652bb2f3185ba513a2ca43a0262a0fd/%2372455%20-%20Screenflow.pdf)

**Comment by katherine-fung** [comment]
Hello @zack and other engineers! 

When you're working on this ticket, please make these copy changes: 

1. On the ["First marriage"](https://www.sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/p/79EB9095-FA19-421B-8B9A-1686690FFE56/canvas) and "Current marriage" screens, the labels for the personal information fields that say "Spouse first name," "Spouse last name," etc should say "Spouse's first name," "Spouse's last name" with an apostrophe s like "Spouse's"

2. On the ["Current marriage" screen](https://www.sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/a/lR5RM0V), for the question "How did the marriage end?" please replace the radio buttons with: 
[ ] Spouse's death
[ ] Divorce 

3. On the ["Spouse's information" screen,](https://www.sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/a/kK5K2AP), the question "Is [spouse name] a veteran?" should use capitalized Veteran.  

4. On the ["Spouse's information" screen,](https://www.sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/a/kK5K2AP), the question "Do you currently live with your Sandra Smith?" should be "Do you currently live with Sandra Smith?" Please remove "your"


5. For the question "Reason you are separated?" 
please make the question "Reason for separation" 

The radio button options should be: 

[ ] One of us needs medical care in a dedicated facility 
[ ] One of us needs to live in a specific location for work
[ ] We're experiencing relationship differences or problems
[ ] Other. Describe the reason for your separation. 

(Context: Danielle Thierry, an OCTO content lead, helped us re-write this question in November. I made the changes in the V003 version of the prototype: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/JArPLJe)

cc @vbellissimo @mayacoforma @jstrothman

**Comment by mayacoforma** [comment]
@katherine-fung I've reviewed your feedback and will incorporate this in the designs when I get a chance.

**Comment by mayacoforma** [comment]
@ToddWebDev I've updated the designs with Katherine's copy changes. 

Screenflow:
[#72455 - Screenflow.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9edc15621e7ceceb3c257ab8b9dab8555a0faa33/%2372455%20-%20Screenflow.pdf)

Prototype:
https://sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/a/JAKAVY9/play

**Comment by katherine-fung** [comment]
Thank you for incorporating the copy changes @mayacoforma! 

I've left a few other comments and questions in the Sketch file: https://www.sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/p/79EB9095-FA19-421B-8B9A-1686690FFE56/canvas 

One is about "Place of marriage" question that I didn't see in the prototype, but is in the PDF. Another is about an a11y recommendation for the order of the questions on the Veteran's former marriage screens. These should be relatively straightforward - let me know if there's anything I should do to simplify the review or changes, or save any work on your end. 

cc @ToddWebDev @vbellissimo for awareness

**Comment by katherine-fung** [comment]
Hey @ToddWebDev, thanks for incorporating the content changes! 

I have 2 other copy changes to request. Are these doable? They're copy changes, and shouldn't affect the backend mapping.

1. For the "Type of marriage" question, can we change it to: 

> How did you get married? 
> [ ] In a civil or religious ceremony with an officiant who signed my marriage license _(this is equivalent to the current option ceremonial marriage)_
> [ ] Some other way _(this is equivalent to the current option other)_
> You can enter common law, proxy (someone else represented you or your spouse at your marriage ceremony), tribal ceremony, or another way.
> [open text field] 
> 

(VA says the most common marriage types for pension applicants are ceremonial and common law. If someone has a common law marriage, VA will process their application in a different way. We need to give the applicants some guidance that they can enter "common law" in the "other" field.) 

2. On the Veteran's former marriage screen, can we re-order the questions in the purple rectangle: 

> How did the marriage end? (*Required) 
> [ ] Spouse's death 
> [ ] Divorce 
> 
> Date of marriage (*Required) 
> 
> Date marriage ended (*Required) 
> 
> Place of marriage (city and state or foreign country) (*Required) 
> 
> Place marriage marriage (city and state or foreign country) (*Required)

This is to match the order of the questions on the screen about the Veteran's spouse's former spouse. For screenreader users, we also want the date of marriage and date marriage ended fields one right after the other.

<img width="543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc1e18428d8964a9c604e324c19f51a95b67389d/294015638-6503ad7b-bff8-4821-b94a-e5e07176ffdc.png" alt="294015638-6503ad7b-bff8-4821-b94a-e5e07176ffdc.png" />

**Comment by vbellissimo** [comment]
Checking this in staging and everything we discussed via our call on January 3 has been met. @ToddWebDev @katherine-fung @mayacoforma 

@katherine-fung, since this pull request has already been completed/merged and changes are already in staging, I will create a separate card for the comments above.

Thanks, all.
