### ISSUE TITLE
EPIC | Profile | Authenticated Menu Research for Add Disability Rating

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72452]
## Background
Earlier in 2023 we expanded the tools available in the auth menu by adding [Letters and Dependents](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62186) we're expanding on that initiative with a second round by adding **Claims** and **Disability Rating**.

Ultimately, based on feedback from CAIA we decided to only focus on **Disability Rating** and did not include **Claims**

This coincides with the updated header/footer for the website, we'll run usability testing on the redesigned website for the Auth menu

## Important artifacts 
- [Public websites redesign sketch files ](https://www.sketch.com/s/4558672b-741f-4d59-84f0-796020d3ef57/p/35AABFD6-32D4-4484-A092-69366F2D69EA/canvas)
- [Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/authenticated-menu/add-claims-and-disability-rating/README.md)
- [Current Auth Menu Sketch Files](https://www.sketch.com/s/b1dacba9-064d-4a24-bfa4-ae0da5790f08)
- [Research Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/discovery-research/authenticated-menu-usability)
- [Findings Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/authenticated-menu-usability/summary.md)

## Tasks 
```[tasklist]
### Discover/Research
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71332
- [x] Jan 9-12
- [ ] #72192
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72639
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72640
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73453
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72646
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72647
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72641
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75059
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72648
```

**Comment by andaleliz** [comment]
@mtcA6 we need to add a ticket in this epic, to set up the prototype. I chatted with @adamwhitlock1 and he feels like he has bandwidth to get started on this during the current sprint 🎉   I'll also be available to help and support as needed.

The sitewide team has already shared a couple of pens, and here's the complete list of what we'll use from them:
  - Unauth header
  - Auth header
  - [The page people will sign in from on their prototype](https://cdpn.io/pen/debug/gOEPoyo/43fa8051200887cb97f5b154ed54c8a3)
  - A mock sign in flow (this may be 2 separate pens)
  - [Signed-in version of My VA](https://cdpn.io/pen/debug/NWJNqGO/8943def52b93fcf8e4da03588cfe4d4b) (not sure we'll use this but nice to have)
  - Footer
  - [An unauth dummy page we can use so to avoid empty `href` values that confuse screenreaders.](https://cdpn.io/pen/debug/dyrMYdw/3f982de58cda384c4178f7d34235fe46) 
  - Pens for background things like CSS, meta tags, etc

For our side, I know we'll need to:
- Create a Profile page pen
- Create a View Disability page pen
- Swap the header on the dummy page to use the auth version
- Update the links in the header pens to point to the profile and disability page pens we create
- Determine the best way to make sure the user name in auth header can be changed on the fly.  Maybe it's as easy as updating the HTML, or perhaps we need to pass in some kind of variable. 

I _think_ we'll also need to:
- Set up a base CodePen to use the pens core pens we'll need for everything: header(s), footer, and the background pens.

**Comment by mtcA6** [comment]
@andaleliz sounds good, please go ahead and add a story. 

Cc: @ACParker89

**Comment by andaleliz** [comment]
[Done! ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73453)
