### ISSUE TITLE
[UX] [Design] [Spike] Test run moving files to Figma

### ISSUE THREAD

**Issue by zach-park** [department-of-veterans-affairs/va.gov-team#72466]
## Tasks

- [x] Download all Sketch files locally
- [x] Upload them as a draft files in Figma ([MHV on VA.gov](https://www.figma.com/files/project/175332858/MHV-on-VA.gov?fuid=1175479952799719494) per Kristen McConnel, look for updates in [Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1702318354274929)) and import Sketch files. Do NOT import Playground or Posters Sketch files. [How to import instructions. Recommend using the browser](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma). 
- [x] If desired, [set custom thumbnails](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma#HowtomoveyourworkfromSketchtoFigma-5.Setcustomthumbnails)
- [x] [Enable component library](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma#HowtomoveyourworkfromSketchtoFigma-6.EnabletheVAdesignlibrary)

## AC

- [x] Files are in the draft space in Figma 
- [x] Component library is enabled on each file  
- [x] Start identifying inconsistencies between sketch and figma
