### ISSUE TITLE
[Development] Visual monitoring of Letters API

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#7246]
## User Story or Problem Statement
We need a way to quickly answer stakeholder questions about the health of our Letters API

## Goal
Create a grafana dashboard for monitoring the Letters API

---
## Tasks
- [x] talk to Andrea about what questions she has about the API health
- Create grafana dashboard with 2-3 panels
  - [x] sum get letters errors - group by errors?
  - [x] sum get letters calls
  - [x] error rate

## Acceptance Criteria
Create grafana dashboard

**Comment by SarahJaine** [comment]
Met with Andrea today.  Ticket completed by [Letters API grafana dashboard](http://grafana.vfs.va.gov/d/uW0ZI5rZk/letters-api?orgId=1&from=now-15d&to=now-1m).

**Comment by SarahJaine** [comment]
![letters_api_errors_20 03 12-20 03 27](https://user-images.githubusercontent.com/9893700/77964736-2f7b4700-72a5-11ea-8a15-e312b1aa593e.png)
