### ISSUE TITLE
[Development] Original Claims: Update Front-End Flow in Staging

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#7247]
## User Story or Problem Statement
As a veteran, I need to be able to start my first claim on VA.gov so I can use have a better experience than eBenefits.

In vets-website, update the front end flow to support original claims only in staging.

## Tasks
- [ ] Update FE flow

## Acceptance Criteria
- [ ] FE ready to go
- [ ] Would be nice to get an integration test we can then use for SQA with MVI

**Comment by ndsprinkle** [comment]
Pull request for staging implementation: https://github.com/department-of-veterans-affairs/vets-website/pull/12015
