### ISSUE TITLE
[BE] 10-10EZR - Standalone form: Investigate issue found in DD trace logs on all submissions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72472]
## Background
For all the EZR submissions, there is an error/warning event after the successful submission that states `Unrecognized value for HTTP_SOURCE_APP_NAME request header`

<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXArQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9150b309f1b92942105f3298338183a6832aff4a/image.png" alt="image.png" />

We need to investigate this issue and determine the root cause, how we might avoid it from firing and confirm there has been no negative impact to the Veterans.

## Tasks
- [x] Investigate Datadog issue
- [x] Determine root cause - notate in comments if the root cause is found, & what is it, OR if it is not found.
- [x] Determine solution, if root cause is found
- [x] Determine impacts to Veterans (if any)

## Acceptance Criteria
- Datadog issue found during EZR submissions is investigated

**Comment by jadon1979** [comment]
`ezr` was not added as a frontend app to the statsd middleware.  This entry is needed to whitelabel ezr for sentry.  There is no impact to the veteran for this issue.

[https://github.com/department-of-veterans-affairs/vets-api/pull/14955](https://github.com/department-of-veterans-affairs/vets-api/pull/14955)
