### ISSUE TITLE
[Development] Assign BAM1 areas of ownership in Sentry

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#7249]
## User Story or Problem Statement
**_Came out of work for https://github.com/department-of-veterans-affairs/va.gov-team/issues/6813_**
It is tedious and time intensive for developers to review Sentry for errors and determine which are under our team's purview. Sentry is not pro actively reviewed by developers. Bugs are often surfaced and corrected after they negatively affect the users.

## Goal
Filtering rules are added to Sentry to identify errors related to our team's code. 

---
## Tasks
- [x] Create "benefits and memorials 1" team in sentry
-  ~Tagging via sentry "ownership" panel http://sentry.vfs.va.gov/settings/vets-gov/projects/platform-api-production/ownership/, doesn't seem to result in errors being tagged http://sentry.vfs.va.gov/vets-gov/platform-api-production/?query=assigned%3Abenefits-memorials-1~
- [x] Call with VSP resulted in correction to tagging. They have started assigning our team based on assignment rules. View assigned tickets at, http://sentry.vfs.va.gov/vets-gov/platform-api-production/?query=assigned%3A%23benefits-memorial-1
- [x] Determine which controllers our team should be monitoring - **see below**
- [ ] Assign "benefits and memorials 1" team as "owner" of controllers we need to monitor
	- **_Added in [first PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4108)_**
		- [x] BurialClaimsController - no spec for sad path
		- [x] EVSSClaimsController - added tag, added spec
		- [x] EVSSClaimsAsyncController - added tag, added spec
		- [x] LettersController - added tags and spec
	- **_Remaining_**
		- [ ] DisabilityCompensationController
		- [ ] DisabilityCompensationFormsController
		- [ ] IntentToFilesController

**Comment by SarahJaine** [comment]
Work started in branch https://github.com/department-of-veterans-affairs/vets-api/compare/sj-tag-controllers-vgt7249

**Comment by SarahJaine** [comment]
Task to "Assign "benefits and memorials 1" team as "owner" of controllers" (detailed in ticket) is on hold because filtering by owner will not be available until Sentry is upgraded to version 10.  Sentry 10 has more sophisticated search features.

**Comment by annaswims** [comment]
looks like Sentry upgrade will be happening sooner rather than later.

https://dsva.slack.com/archives/CQHBJ5U06/p1588350334057700

**Comment by annaswims** [comment]
This should be enough to wrap up this ticket https://github.com/department-of-veterans-affairs/vets-api/pull/5897
