### ISSUE TITLE
Revisit Feature Request process to improve clarity and follow-up

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#72509]
## Purpose
Is this process still clear enough?  is it working?  how to keep things moving better?  Tickets don't seem to be getting moved along to the right.  Are users instructed to do this?

Have we established a protocol for follow-up for our team?

**Some Slack questions from Platform members:**
what if we decide that we don't want to implement the feature? Or if we can't implement it? Or if it's too challenging to implement? Do requests only move off this board if they're completed/implemented? (edited) 

also... if a request has been open for a long time, is it still a need by the original requesting team? i'm checking on one of those situations right now :nod:

## Tasks
- [x] [create a space to evaluate and discuss](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2897608724/Revisiting+the+Feature+Request+Process)
- [x] clarify in async team review: what relevant Platform Team needs to do regarding movement of ticket along columns
- [x] evaluate in async team review: does completing a ticket not move it to the Done column?  if not, can it, or what needs to be altered to automate? (Note: it appears that moving an item to Done doesn't Close/Complete it, or vice-versa. experienced this on 1/11)
- [x] establish in async team review: [a protocol for SDT to follow-up on status of tickets](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2927722497/draft+Feature+request+process+-+User+guide+for+Platform+teams+v2#Prioritization-Process)
- [x] Take [inventory of all of the documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2897608724/Revisiting+the+Feature+Request+Process#All-the-locations-of-Feature-Request-process-related-documentation) where updates are needed (some is quite outdated)
**Will move to associated ticket  - [ ] Update protocols and relevant documentation with the decisions from above**
          - Feature request process - User guide for Platform teams in “About the Platform”
          - Feature Request Process and Feature Request intake in our SDT space
          - Platform products and services

**Will move to associated ticket - [ ] Final team review_
Will move to associated ticket - [ ] share updated process and documentation with Platform teams**

## Acceptance Criteria
**Will move to associated ticket - [ ] Documentation is updated with new process
Will move to associated ticket - [ ] Clarified process is shared**

**Comment by gopixelsgo** [comment]
this ticket will carry over to next sprint

**Comment by gopixelsgo** [comment]
This sprint we expanded the tasks to include an inventory of all of the documentation where updates are needed, and a Mural board for planning.

This ticket will roll into next sprint for completion of these tasks: 
- Update protocols and relevant documentation with the decisions from above
- Final team review
- share updated process and documentation with Platform teams

**Comment by steel36** [comment]
This ticket will close with the work continued in a subsequent [ticket](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/75066) to finalize deliverables.
