### ISSUE TITLE
[FE] My VA: Write FE unit tests for personalization/dashboard/utils

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#72511]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for `personalization/dashboard/utils`:
- appeals-v2-helpers.jsx
- getStatusContents.jsx
- helpers.js
- timezone.js

## Coverage (12/21/2023)
![Screenshot 2023-12-21 at 2 57 12 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/429ac91a-25ad-487c-9fe3-f57b8781bb32)

## Tasks
- [ ] Write FE unit test for `claims.jsx`
- [ ] Write FE unit test for `getStatusContents.jsx`
- [ ] Write FE unit test for `helpers.jsx`
- [ ] Write FE unit test for `timezone.jsx`
- [ ] update [audit table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardutils) after validation

## Acceptance Criteria
- Unit tests are written and running 
- `/utils/` has >80% coverage

## Resources
See files linked in `personalization/dashboard/utils' [table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md#personalizationdashboardutils)

**Comment by allisonlu** [comment]
@adamwhitlock1 @DanielMiller-agile6 

can you help me validate? 🤠 

1. run `yarn test:coverage --app-folder personalization/dashboard --coverage-html`
2. navigate to `/vets-website/coverage/dashboard/utils/index.html`
3. confirm that you see the following: 
![Screenshot 2024-02-14 at 11 40 25 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/287799c1-7425-4184-bf02-ae808a5ce38d)

**Comment by adamwhitlock1** [comment]
Validated

![Screenshot 2024-02-14 at 10 03 40 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/4716d0fc-fe53-4558-ab61-63cfe8aeb10a)

**Comment by allisonlu** [comment]
@ajakabcin closing this ticket as these are validated!
