### ISSUE TITLE
Upgrade active_model_serializer gem to v0.10.14

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#72560]
## Summary
Upgrade active_model_serializer to v0.10.14

## Tasks
- [x] upgrade gem
- [x] remove gem from `department-of-veterans-affairs` source 

## Acceptance criteria
- [x] `active_model_serializer` gem is v0.10.14
- [x] serialized data contains empty string for `id` where `id` is `nil` in serializer
