### ISSUE TITLE
Document data collection and processing for Feedback Portal within Slack

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#72562]
## Purpose
Capture the steps for processing submissions.
Also, how might we automate that approach?

## Tasks
- [x] Brainstorm options for suitable process and tools
- [x] Document what each of the options are; determine which is a fit  (Google Sheets potentially)
- [x] Unit test functionality
- [x] Outline process progression from manual to eventual automation
- [x] Get assistance from Governance on how they accomplish a similar outcome
- [x] [Document the process ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2792849409/How+to+Update+the+Platform+Feedback+Data+from+Slack+into+Domo)of how data will be collected and prepped for Domo
- [x] Update [data parsing document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2756476930/Portal+entry+parsing+process+INCOMPLETE) to align w/ newer process
- [x] Conduct a test run

## Acceptance Criteria
- [x] Documentation on process for processing submissions
- [x] Clear timeline for an entry getting processed
- [x] Clear definition of who is responsible, frequency, etc.
- [x] Where should the data live (Drive, etc.).

**Comment by twoangstroms** [comment]
Rolling into next sprint to get access to best-practices experts

**Comment by twoangstroms** [comment]
Split Confluence pages into [Options Thinking](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2895544321/Evaluating+Options+for+collecting+Data+for+Domo) and set up a page for [Process](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2884108347/Collecting+and+Prepping+Data+for+Domo) that documents what we can do manually so far with space for learnings, as well as what we can do to move towards a more automated process

**Comment by twoangstroms** [comment]
Rolling over to next sprint; just needs review and revision

**Comment by steel36** [comment]
This item was not completed due to absence of preferred team member for testing.  Will rollover to next sprint.
