### ISSUE TITLE
Create a new side-nav component for Profile 2.0

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7256]
## User story

As a veteran, I need to be able to easily navigate through the profile.

## Additional background

Epic #5346

## Design & Copy

- [InVision prototype](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/407039340)
- ["Profile Navigation" build specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/profile-navigation.md)

## Specs

<img width="745" alt="profile-nav-specs" src="https://user-images.githubusercontent.com/58752772/78706082-f5b8ca80-78ba-11ea-91da-373362008b37.png">
<img width="449" alt="profile-nav-hover" src="https://user-images.githubusercontent.com/58752772/78706090-f9e4e800-78ba-11ea-9ddc-341d54c85931.png">

## Tasks

- [ ] Build the profile navigation section.
- [ ] Implement correct copy.
- [ ] Get Tressa to test out this section and make sure it looks OK.

## Acceptance criteria

- [ ] This section has been built and reviewed by Tressa.

**Comment by mshea0606** [comment]
Hey @erikphansen! Brad no longer has the bandwidth to complete this card this sprint, i've moved it over to you.

**Comment by erikphansen** [comment]
That's fine @mshea0606 but I won't get to it this sprint. It will make more sense for me to do all the different sections first and then do the sidenav after.

**Comment by mshea0606** [comment]
@erikphansen  No problem, i agree.   I'll go ahead and move it to the backlog.

**Comment by tressaellen** [comment]
@erikphansen it's all looking so good! A few changes for the side nav:

- In Personal and contact information the 'i' in information should be lowercase

- Connected applications should read 'Connected apps'

<img width="331" alt="Screen Shot 2020-04-30 at 12 11 47 PM" src="https://user-images.githubusercontent.com/58752772/80755635-a5114780-8add-11ea-9b88-16a83fc69cf9.png">

In mobile view:

- 'Profile menu' is currently centered - should be left aligned.

<img width="500" alt="Screen Shot 2020-04-30 at 12 25 49 PM" src="https://user-images.githubusercontent.com/58752772/80755820-f4577800-8add-11ea-80fe-98f339a5777f.png">

**Comment by mshea0606** [comment]
Hi @erikphansen, can you please change  'Profile Menu' to 'Profile menu' in mobile view? After that, this should be good to go. Thanks!

**Comment by erikphansen** [comment]
@mshea0606 The mobile menu trigger button has been converted to sentence-case https://github.com/department-of-veterans-affairs/vets-website/issues/12700
