### ISSUE TITLE
[UX][Content] [Design] Create Final Wireframes & Content for Video appt card in appt list

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72598]
## Background
This work if for just Pre-Check-in (not eCheck-in)

## Tasks
- [ ] Create final component
- [ ] Create variation for pre-check-in success page with alert
- [ ] Add to all necessary artboards in Sketch Production file (pre-check-in)
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

Content and icons: [Telehealth Figma file](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-In?type=design&node-id=7%3A484&mode=design&t=J3IxGrMQTaWsuVpj-1)

Examples: 

<img width="320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEtKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9533112b44193c0412ff18d98be8aafc693df79f/Screenshot%202023-12-27%20at%202.25.20%E2%80%AFPM.png" alt="Screenshot 2023-12-27 at 2.25.20 PM.png" />
<br/><br/><br/><br/>
<img width="324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9KQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cf93017ca92a6f8e46b11ae5d2ed44a5fa8e536/Screenshot%202023-12-27%20at%202.37.02%E2%80%AFPM.png" alt="Screenshot 2023-12-27 at 2.37.02 PM.png" />

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by ytsaoca** [comment]
Wireframe for review: https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/9DB5F923-E382-464E-B470-0E1AD19E4F0F/canvas

'cc @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
validated
