### ISSUE TITLE
[UX][Content] [Design] Create Final Wireframes & Content for Video appt detail page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72599]
## Background
This work if for just Pre-Check-in (not eCheck-in)

## Tasks
- [ ] Check to see if there is a page with general instructions that we might be able to link the Veteran to
- [ ] Create final wireframe with content ([Example in sketch](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/mPKMmvg#Version))
- [ ] Add to all necessary artboards in Sketch Production file (pre-check-in)
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

Content and icons: [Telehealth Figma file](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-In?type=design&node-id=7%3A484&mode=design&t=J3IxGrMQTaWsuVpj-1)

Notes: 
- Pre-check-in appt details page is only accessible after pre-check-in is complete. 
- Consider whether we need to add more content to the instructions on the pre-check-in complete page to supplement the instructions for day of that are in the info alert on the pre-check-in success page. [Content for how to start a video appointment](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign-%7C-Appointments-FE?type=design&node-id=2358%3A43526&mode=design&t=ZfBwrEQRbjU34g3b-1).

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by kellysmith1008** [comment]
@ytsaoca I don't see any reason we shouldn't pull from what already exists for video appointments and use the content in Ben provided in the links above:
"You can join your appointment by using our appointments tool on VA.gov. We'll add the link 30 minutes before your scheduled appointment."
I like the idea of adding the additional information on how to join, but would love your thoughts on including it or not. Happy to hop on a meeting to discuss, or we can discuss here, or in the wireframes :)

**Comment by ytsaoca** [comment]
Hi @kellysmith1008 
I think it's beneficial to add the information about hoe to join and the content looks good. Just a small part that I would like to discuss. I wonder whether it is clear enough for this sentence, "**We'll add the link 30 minutes before your scheduled appointment.**" User might be confused about where the link will be add. Do they need to go back to this check-in flow or it's a link that will be added to the appointments tool on VA.gov. And I'm not sure if mentioning **appointments tool on VA.gov** is clear enough, either. Is it possible to have a direct link to the tool?

**Comment by ytsaoca** [comment]
@kellysmith1008 Thanks for clarification.
I like the idea that @benbrasso-agile6 mentioned. Or how about "you'll receive a text message or a notification (with a link) to start your appointment"?

**Comment by benbrasso-agile6** [comment]
I don't think the link will be in the notification. I think it directs you to the appt details page on Appointments on VA.gov, and then, depending if it's a VVC at Home or VVC with a GFE, it's a different link/tool.

**Comment by ytsaoca** [comment]
Got you. Then, I misunderstood it.

I was trying to be more specific that they would receive a text message that includes the link to the video appointment. Because in the original version, it didn't mentioned the channel and user might not notice the text message.

**Comment by benbrasso-agile6** [comment]
Also, it will either be an email or SMS, depending on what they're opted into. So, "notification" can capture both methods.

**Comment by kellysmith1008** [comment]
So I'm starting to think that, since we don't know if they'll get an email or a text message, and we don't know which type of VVC appointment it is (at home or in the clinic - though I thought VVC=Veteran video call and CVC=clinic video call but I might be making that up) maybe it's best if we don't tell them about how they'll access it now. This is for pre-check-in only, so they'll receive another notification once it's time to check-in. Thoughts? It's just odd to me to say "You'll receive a notification that help you find the link" or something like that - it's not like they can follow the steps or the link during pre-check-in anyway - it's not ready or setup yet.

**Comment by benbrasso-agile6** [comment]
It won't ever be at the clinic for this type. It's at home using your device or a provided GFE. For example, I think some GFEs have like built in devices for measuring something related to your condition.

**Comment by benbrasso-agile6** [comment]
CVT, which was already complete for design, is the in-person visit type. 

The two here we're talking about is VVC at Home and VVC with GFE (at Home). We can tell the difference in what we get back from Vetext. I just don't know what content is in the notifications on the day of the appts. I think most are going to point to the appt details page on Appointments on VA.gov. Then, it has the link and instructions on the appt detail page. @klawyer does that sound right?

**Comment by benbrasso-agile6** [comment]
But, yes, @kellysmith1008 you're on the right track. They'll receive a notification on the day of for how to join their appt.

**Comment by ytsaoca** [comment]
@kellysmith1008 I agree with you that this is for pre-check-in only, and "You'll receive a notification that help you find the link" it's not like they can follow the steps.

About the original second sentence "We'll add the link 30 minutes before your scheduled appointment" is same kind of odd to me because it seems not adding benefit by telling them what the link is for and where the link will be add. (And of course, I understand that there are different ways they will be notified.)

**Can we just say "You can join your appointment by using our appointments tool on VA.gov." and get rid of the second sentence? Or make the second one like "You will get more information [before your appointment/during check-in, etc]"**

I may overthink about it though

**Comment by benbrasso-agile6** [comment]
@ytsaoca how's this one coming along? Ready for a review?

**Comment by benbrasso-agile6** [comment]
Sounds like a plan. 

Do we need to add "... on the day of your appointment" or is that superfluous?  

> You can join your appointment by using our appointments tool on VA.gov on the day of your appointment

Should we include a link? In case Veterans want to understand what tool we're referring to? 

> You can join your appointment by using our appointments tool on VA.gov on the day of your appointment

> [Sign in to VA.gov to review your appointment](url)

**Comment by kellysmith1008** [comment]
Love that second proposal. Let's go with that

**Comment by ytsaoca** [comment]
Wireframes for review: 
https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/9DB5F923-E382-464E-B470-0E1AD19E4F0F/canvas

@kellysmith1008 @benbrasso-agile6  Not sure if we want to show the link in the detail page to keep consistency. Or should it be a primary/secondary link at the end of the detail page card?

If the current version doesn't work, just let me know and I'll fix it.

**Comment by benbrasso-agile6** [comment]
I like it all. The link belongs to the status, so I think it should be paired with it, like you have it. See what Kelly thinks.

**Comment by kellysmith1008** [comment]
LOVE THIS

**Comment by ytsaoca** [comment]
Thanks! Then, I'll close this ticket.

**Comment by benbrasso-agile6** [comment]
Nice work 👏
