### ISSUE TITLE
[UX][Content] [Design] Create Final Wireframes & Content for CVT appt card in appt list

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72594]
## Background
This work if for both Pre-Check-in and eCheck-in

## Tasks
- [ ] Create final component
- [ ] Create variation for pre-check-in success page with alert
- [ ] Add to all necessary artboards in Sketch Production file (pre-check-in and check-in)
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

Content and icons: [Telehealth Figma file](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-In?type=design&node-id=7%3A484&mode=design&t=J3IxGrMQTaWsuVpj-1)

Examples: 

<img width="320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEtKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9533112b44193c0412ff18d98be8aafc693df79f/Screenshot%202023-12-27%20at%202.25.20%E2%80%AFPM.png" alt="Screenshot 2023-12-27 at 2.25.20 PM.png" />
<br/><br/><br/><br/>
<img width="324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9KQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cf93017ca92a6f8e46b11ae5d2ed44a5fa8e536/Screenshot%202023-12-27%20at%202.37.02%E2%80%AFPM.png" alt="Screenshot 2023-12-27 at 2.37.02 PM.png" />

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by ytsaoca** [comment]
@benbrasso-agile6 I created new pages for CVT [https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/4A888CAB-7840-4134-B03B-D0DF42EC7B48/canvas) and [pre-check-in](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/A29096EA-7235-400F-981A-145542326EE2/canvas).
For the check-in detail page, because the original wireframe still has a blue alert on it so I keep it consistent. For pre-check-in, it is a body text like the other pre-check-in detail pages.

**Comment by benbrasso-agile6** [comment]
CVT - check in - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/4A888CAB-7840-4134-B03B-D0DF42EC7B48/canvas

CVT - pre check in - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/A29096EA-7235-400F-981A-145542326EE2/canvas

@ytsaoca looks perfect. 

@kristenmcconnell @loripusey want to take a look?

**Comment by loripusey** [comment]
Looks good to me, I'm assuming all we have changed are the icons and instructions. The spacing is off causing the details link to crash into other text, but this shouldn't affect development.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/63dbc9a5-5dc6-421a-81fd-5c2937a123c7)

**Comment by benbrasso-agile6** [comment]
Hmmm, wasn't like that before. Will take a look in a bit.

**Comment by benbrasso-agile6** [comment]
Should be fixed now. Buy, yeah, it's just the icon, "in person" is replaced with "video", h1 changes on appt detail page, and pre-check-in instructions change.

**Comment by kristenmcconnell** [comment]
It looks good to me as well. Did you get an answer from the design system team on the building icon?

**Comment by benbrasso-agile6** [comment]
Yeah, should be using the location_city one in USWDS v3, but there's issues with the icons (on the developer end) and a ticket has been logged for DST.

**Comment by benbrasso-agile6** [comment]
Closing out
