### ISSUE TITLE
[UX][Content] [Design] Create Final Wireframes & Content for CVT appt detail page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72595]
## Background
This work if for both Pre-Check-in and eCheck-in

## Tasks
- [ ] Create final wireframe with content ([Example in sketch](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/mPKMmvg#Version))
- [ ] Add to all necessary artboards in Sketch Production file (pre-check-in and check-in)
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

Content and icons: [Telehealth Figma file](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-In?type=design&node-id=7%3A484&mode=design&t=J3IxGrMQTaWsuVpj-1)

Note: Pre-check-in appt details page is only accessible after pre-check-in is complete. 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by ytsaoca** [comment]
Also posted the links to #72594
--
CVT - check in - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/4A888CAB-7840-4134-B03B-D0DF42EC7B48/canvas

CVT - pre check in - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/A29096EA-7235-400F-981A-145542326EE2/canvas

--

**Comment by benbrasso-agile6** [comment]
Let's go ahead and close these out
