### ISSUE TITLE
Copy of [Design] Create Final Wireframes & Content for CVT appt detail page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72596]
## Tasks
- [ ] Create final wireframe with content
- [ ] Add to all necessary artboards in Sketch Production file (pre-check-in and check-in)
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

Content and icons: [Telehealth Figma file](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-In?type=design&node-id=7%3A484&mode=design&t=J3IxGrMQTaWsuVpj-1)

Note: Pre-check-in appt details page is only accessible after pre-check-in is complete. 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets
