### ISSUE TITLE
Finalize the guide for Slack survey creation and data collection

### ISSUE THREAD

**Issue by gopixelsgo** [department-of-veterans-affairs/va.gov-team#72602]
## Purpose
Supports the creation of a Feedback Portal survey within Slack, a feedback mechanism to be tested as a potential solution to the current high abandonment rate. This ticket covers the additional revisions to Parts 1-3 of the survey creation guide as we test the survey's utility. Part 4 of the guide (Collecting and Prepping Data) is handled in [ticket #72562](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/72562).

## Tasks
- [x] Update Parts 1-3 of the [guide for creating a survey via Slack Workflow Builder](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2879423007/Building+Platform+Feedback+in+Slack) based on what is learned in testing 
- [x] Test survey with people outside of our team 
- [x] Team review of [documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2879423007/Building+Platform+Feedback+in+Slack)

## Acceptance Criteria
- [x] Survey creation guide finalized

**Comment by gopixelsgo** [comment]
rolling into next sprint to wrap up tasks
