### ISSUE TITLE
[FE] Make changes to Production per the new wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#72617]
## Release
Let's go ahead and release this when it is complete.

## Description 
30 sites have said that they're marking Veterans as "no shows" who have checked in, because they call them when they check in vs. calling them when it's their appt time or up until 15 mins after their appt time.  

## Wireframes
[Wireframes](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=0-1&mode=design&t=21DaDuMaDbxuv3lJ-0)

## Tasks
- [ ] [FE] Make changes per the new wireframes
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=0%3A629&mode=design&t=RspvPSTdtM8Eo7yz-1

**Comment by benbrasso-agile6** [comment]
This one go out yet?

**Comment by loripusey** [comment]
@wullaski ^^^^

**Comment by wullaski** [comment]
Got a PR going to fix this https://github.com/department-of-veterans-affairs/vets-website/pull/27605

**Comment by loripusey** [comment]
validated screenshot against Figma
