### ISSUE TITLE
PagerDuty: Remove and Replace eMIS References

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#72611]
## Issue Description
As part of the code deletion for eMIS, we'll need to remove the eMIS service/s from PagerDuty and create new PagerDuty alerting for VAProfile.  

This ticket is for the work that needs to be done within PagerDuty and the repos/storage containers that support it. References to eMIS should be removed in PagerDuty (according to this [recent Slack conversation](https://adhoc.slack.com/archives/C045LCF8WU8/p1703277830446589)), and it may be necessary to create Datadog alerting for the new VAProfile endpoints, along with a Datadog integration in Pagerduty. 

After removing those references from PagerDuty,, they will also need to be removed from devops repo, manifest repo, and Parameter Store. 

A separate ticket will address ensuring that VAProfile breakers services are represented in Datadog.

Previous discovery for this work can be found in this [ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/72202). (A separate ticket has been created to remove PagerDuty references to eMIS that exist in Vets-API.)

---
## Tasks
- [x] Create followup ticket to ensure Datadog is tracking VAProfile breaker alerts to monitor VAProfile services
- [x] Create Datadog VAProfile Alerts to monitor new VAProfile endpoints, if necessary.
- [x] Delete the [Prometheus:eMIS integration](https://dsva.pagerduty.com/service-directory/P0HNT0I/integrations) , found in the eMIS PagerDuty Service.
- [x] Delete the [External:eMIS](https://dsva.pagerduty.com/service-directory?direction=desc&query=emis&sort_by=score&team_ids=all) services in PagerDuty 
- [x] Delete emis pagerduty references from [devops repo](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fdevops+%22emis%22&type=code) and [Parameter Store](https://console.amazonaws-us-gov.com/systems-manager/parameters?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:emis):
  - [x] [/devops/pagerduty/external_emis](https://console.amazonaws-us-gov.com/systems-manager/parameters/%252Fdevops%252Fpagerduty%252Fexternal_emis/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:emis)
  - [x] [/dsva-vagov/prometheus/common/pager_duty_external_emis](https://console.amazonaws-us-gov.com/systems-manager/parameters/%252Fdsva-vagov%252Fprometheus%252Fcommon%252Fpager_duty_external_emis/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:emis)

## Acceptance Criteria
- [x] eMIS is no longer referenced in PagerDuty
- [x] no more emis references in devops repo or parameter store
- [x]  VAProfile alerting is live in PagerDuty
---

**Comment by rmtolmach** [comment]
> Create Datadog VAProfile Alerts to monitor new VAProfile endpoints

As part of https://github.com/department-of-veterans-affairs/devops/pull/13862/, I edited some alerts. There are alerts for VA Profile backend latency and I added an alert if VA Profile is unavailable. In terms of adding more alerts for VA Profile, I don't know if we need to do that. We don't own VA Profile, so any alerts would be largely un-actionable. But I could be wrong. I guess just ask yourself, "If I was on call or on support and was alerted for <the alert you're thinking of creating>, would the alert be helpful in any way?"

**Comment by rmtolmach** [comment]
Deleted emis service which deleted prometheus integration:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/c9681079-4ec5-4511-b8a8-3455714b35dc)

Also deleted the service for staging:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/e2d15e4d-71e9-4b8f-9f39-3b23e37dca22)

Vet360 (VA Profile) is represented on [this VSP External Service dashboard](https://vagov.ddog-gov.com/dashboard/98p-ckp-gu7/vsp-external-service-performance-indicators?refresh_mode=sliding&view=spans&from_ts=1706202807792&to_ts=1706206407792&live=true)

**Comment by rmtolmach** [comment]
I deleted the following parameters from parameter store:
- /devops/pagerduty/external_emis
- /dsva-vagov/prometheus/common/pager_duty_external_emis
