### ISSUE TITLE
UX | AuthMenu Claims and Disability Rating | Conversation Guide

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72639]
## Background
We need to create a convo guide for the Auth Menu Expansion that we're testing with the new header/footer

## Tasks
- [x] Draft conversation guide (link) 
- [x] Review with PM/PO
- [x] Incorporate edits
  

## Acceptance Criteria
- [x] Guide complete and ready to submit for the research kickoff

**Comment by andaleliz** [comment]
Finished draft and [requested feedback in my research plan ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72640#issuecomment-1887597762), so folks don't have to bounce between two tickets to give feedback on something they need to review together.
