### ISSUE TITLE
[Discovery] Logged-in homepage: Research review — Compile list of documents to review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7264]
## Background

Epic #6326

As part of the logged-in homepage discovery phase, we have decided to do a review of past research write-ups to help us gain insight/set context and to guide future user interviews so they are unique and answers new questions.

## Tasks

- [ ] [Review master list of past research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md)
- [ ] Determine which research docs should be revisited
- [ ] Compile a list of research docs to review

## Acceptance Criteria

- [ ] We have set the list of documents to review

**Comment by Samara-Strauss** [comment]
### List we have so far:

- [Personalization 2.0 Discovery: Summary and Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/personalization%202.0/discovery-research/README.md)
- [Dashboard 2.0 User Interviews Research Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/personalization%202.0/discovery-research/dashboard-interviews/research-summary.md)
- [Notification research (2018)](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Notifications/HCA%20MVP/Research/User%20Notifications%20Readout%20-%20end%20of%20sprint%20demo.pptx)
- [Brand consolidation research (2018)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-gov-relaunch-2018/user-research)
  - [April 2018 deck 1](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/user-research/study-3/Merger%20Study%203%20Research%20Readout.pptx)
  - [April 2018 deck 2](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/user-research/study-3/Merger%20Study%203b%20Research%20Readout.pptx)
  - [September 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/user-research/study-5/Brand%20Consolidation%20Research%20Summary%209-6-2018_Study%205%20only.pptx)
  - [October 1, 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/user-research/study-6/Brand%20Consolidation%20Research%20Summary%2010-1-2018_study%206%20only.pptx)
  - [October 25, 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/user-research/study-8/Brand%20Consolidation%20Research%20Summary%2010-25-2018_Study%208%20only.pptx)
- My VA research
  - [Original pre-launch usability testing (April 2018)](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/research/April%202018%20usability/Personalization%20MVP%20readout.pptx)

**Comment by Samara-Strauss** [comment]
Adding these to the above list:

- [Health care application/My VA dashboard research (April 2019)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/user-testing/dashboard-updates/research-summary.md)

**Comment by Samara-Strauss** [comment]
Also adding ["Find VA Benefits" user testing (September 2018)](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Recommendations/Research/MVP%20Research/User%20Testing/Research%20Summary.md)

**Comment by Samara-Strauss** [comment]
@andaleliz Feel free to take a look through the research history doc, but I think [the list in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7264#issuecomment-604643663) should be a good enough compilation of past research/context setting. If there's something else you'd like to include, feel free to add it to the list. Otherwise, I think my personal review is complete and so you can run with things from here!

**Comment by Samara-Strauss** [comment]
I just added some journey maps to [the list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7264#issuecomment-604643663). These are to help us establish a basic understanding of some of the processes veterans go through. We don't need to go through these with a fine-tooth comb or anything — just review them and get familiar with things at a high level so we can better apply them to the eventual logged in homepage design.

**Comment by Samara-Strauss** [comment]
Also added the Frog research readout from 2016
