### ISSUE TITLE
UX | AuthMenu Claims and Disability Rating | Research Logistics (kickoff meeting)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72646]
## Background
We completed the research plan  #72640 and convo guide #72639. This ticket covers the next steps to kickoff the research

## Tasks

- [x] Submit research plan
- [x] Meet with Perigean to discuss recruitment criteria
- [x] Confirm recruiting has been kicked off
- [ ] Run pilot session
- [x] Create observer Mural board
- [x] Schedule debrief sessions w/ team
- [x] Complete any other steps needed to prepare while recruiting takes place

## Acceptance criteria 
- [x] we're ready to run the study
