### ISSUE TITLE
UX | AuthMenu Claims and Disability Rating | Research Plan

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72640]
## Background 
We need to create a research plan for the Auth Menu Expansion we're testing in the new header/footer

## Tasks 
- [x] Write research plan
- [x] Review/share with PM & PO

## Acceptance Criteria 
- [ ] Plan is ready to submit and kick off the research

**Comment by andaleliz** [comment]
@mtcA6 sharing about a loose timeline to help with convos/planning while I'm out. This assumes that:
- the sitewide team's 1/17 target of having the prototype completed doesn't shift
- the sitewide team will make good progress while I'm out and we'll have a strong sense of what their prototype will include as we get into the research plan and convo guide work.
- This work will be my focus in the sprint when I come back

**Jan 9-12:** Work on the plan and conversation guide
**Jan 16:** kick off recruiting
**Jan 29-Feb 1:** Conduct sessions
**Feb 2:** Topline summary completed
**Feb 5-9:** Synthesis in progress
**Feb 12** (or thereabouts): Read out to team

**Comment by mtcA6** [comment]
I think they're on track for 1/17, they do not intend to add the two additional items to the auth menu so we'll need to do that. See the comments on [#16573](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16573)

My only question is, will you need Adam's help to add those to the codepen?

**Comment by andaleliz** [comment]
@mtcA6 I won't need Adam's help to add those to the CodePen, but I might need his help to build out some other pages. I will know more once I start working through the research plan (so in about 24 hrs).

**Comment by Samara-Strauss** [comment]
Hey Liz -- acknowledging receipt, and that I will review these tomorrow.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss, thanks for your feedback on our call today and all the great points you made! I updated both documents in the following ways:

1. **Deprioritized the co-design exercise.** As part of the post-task interview, I will ask questions to dig into expectations about what's in the menu, the ordering of the links, and what might be missing.  For sighted participants, I'd still like to use the mural board as a visual aid to guide that part of the convo, and reflect any updates they want to make. I think it'll be an interesting experiment in getting Veterans more involved in the process, and could make for a richer conversation. I don't think it'll add any more time to the session.
2. **Updated tasks so they are as follows:**
    - Task 1: navigation to view disability ratings
    - Task 2: navigation to letters
    - Task 3: navigation to profile (updated task to update phone number since we did address in previous research)
    - Task 4: optional if needed: review auth menu.  It occurred to me that there's a chance someone will completely fail and not ever find the auth menu. Unlikely but want to be prepared
  
Both docs are available for review in [this folder. ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/discovery-research/authenticated-menu-usability) Let me know if this feels better to you.  Thanks again for your comments!

**Comment by Samara-Strauss** [comment]
@andaleliz this is MUCH better. Thank you! Looks good to go for a review from Amanda or Cindy.

**Comment by andaleliz** [comment]
Thanks @Samara-Strauss! I [asked them in Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1705433286388719) to drop any feedback here in the next day or so.  I'm also checking with Adam to try to get an ETA for when we'll have the start of a prototype, so we can drop a link in the plan and kick off recruitment.  We have an **awesome** start with what the Sitewide team has provided us.

**Comment by aklausmeier** [comment]
@andaleliz  A few thoughts that came up while I was reviewing your research plan. 

- We typically kick off research with Research Ops pending finalized research plan, convo guide and prototype, curious if you are planning to kick off prior to your team's revised prototype being ready for Shane's review?
- Feel free to pull OCTO and OFCIO research priorities from our [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/research/phase2-AT/research-plan.md) and anything else you might still need. 
Might be good to link back to our research plan as your research is fulfilling "Phase 3" that we reference in our research plan.
- Cindy spun up a CAIA accessibility review [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73242#issuecomment-1890158684) for research plan, convo guide and prototype review, linking here for reference so you have context of concerns they brought up
   - including screen reader sessions being 2X in session length 
   - accessibility specialist scheduled/present for each SR session
- In our research we discovered that folks voiced confusion between **Profile** and **MyVA**. If you had time in wrap up questions you could consider: Ask participant how they would describe these two pages to another Veteran. 
- The Mural co-design could be an interesting experiment. I would update the desktop design to mirror the CodePen prototype, specifically the Sign out button being removed and sign out link added to bottom of auth menu. We know that with OFCIO guardrails having this separate sign out button on desktop is a no-go.
- If you have any questions, let me know. Happy to help clarify anything as you go through your research prep. Looking forward to observing a few sessions!

**Comment by cindymerrill** [comment]
FYI In my experience, Shane doesn't approve research for recruiting without a working prototype. @andaleliz @aklausmeier

**Comment by andaleliz** [comment]
@aklausmeier thank you for this feedback, and linking to that CAIA a11y review ticket. This is all really helpful.  I also appreciate your willingness to be available to answer any future questions we have too!
 
Responses to your questions/suggestions:

>curious if you are planning to kick off prior to your team's revised prototype being ready for Shane's review?

Yes, we are planning on kicking off recruiting before the prototype is totally complete. We expect to have it far enough along for Shane to understand what we're doing and be able to start recruiting.  I'm not sure Shane will go for it but I think it's at least worth a conversation with him (cc @cindymerrill).

>Feel free to pull OCTO and OFCIO research priorities from our research plan and anything else you might still need.
Might be good to link back to our research plan as your research is fulfilling "Phase 3" that we reference in our research plan.

Great idea, and thanks for pointing out these needed additions. I didn't realize that we were conducting the Phase 3 research you had planned; I was under the impression that this was a preliminary supplement to what your team would do in phase 3.  I've updated our plan accordingly. 

>In our research we discovered that folks voiced confusion between Profile and MyVA. If you had time in wrap up questions you could consider: Ask participant how they would describe these two pages to another Veteran.

I love this question, and have added it to the post-task interview portion of the convo guide. 

>The Mural co-design could be an interesting experiment. I would update the desktop design to mirror the CodePen prototype, specifically the Sign out button being removed and sign out link added to bottom of auth menu. We know that with OFCIO guardrails having this separate sign out button on desktop is a no-go.

Yes, I'm interested to see how it goes. I removed the sign out button from the desktop design, and added Sign Out to the bottom of the list of links. I also removed the `x` from the `Close` button on mobile, since I don't see that in your prototype, and added Sign Out to the bottom of that list of links too.

Closing out this ticket since we have no further revisions to our plan.

**Comment by Samara-Strauss** [comment]
> I didn't realize that we were conducting the Phase 3 research you had planned

I'm sorry -- that is on me for not having communicated this adequately.

**Comment by andaleliz** [comment]
No worries @Samara-Strauss! There was a bit of telephone going on since we were both out at different times, and the holidays. It feels like we still got a place that will cover the needs for Phase 3, even without that specified from the get go 😄
