### ISSUE TITLE
Integrate Engineering Resource Tracking into Support Best Practices

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72657]
## Description 
Clint is identifying work stream bandwidths by having Tier 2 engineers:

- Tag tickets with sprint the work was done in
- Assign the ticket to themselves
- Add Support Tracking epic
- Add label "Support"

---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Create a workflow in the Support Best practices that includes the steps above (the goal is to make sure the team does it every time)
- [ ] Send for review to Joe Knipes and Alyssa Gallion
- [ ] Once reviewed and published, add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
