### ISSUE TITLE
Update Support Bot Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72656]
## Description 
We have made several changes to the support bot as outlined in this related epic: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/61279
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add any Support Bot updates to this page: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2887582468/Platform+Support+Bot
- [x] Add any Documentation Bot updates to this page: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2887582480/Platform+Support+Documentation+Bot
- [ ] Ask Clint to archive this page as the process belongs to Platform Support not SRE: https://vfs.atlassian.net/wiki/spaces/SRE/pages/1883406342/Platform+Support+Bot
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Documentation complete.
