### ISSUE TITLE
[Discovery] Logged-in homepage: Research review — Review documents and document insights

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7265]
## Background

Epic #6326

As part of the logged-in homepage discovery phase, we have decided to do a review of past research write-ups to help us gain insight/set context and to guide future user interviews so they are unique and answers new questions.

## Tasks

- [ ] Review documents compiled in [comments of #7264](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7264#issuecomment-604643663)
- [ ] Document insights
- [ ] Review and share with the team

## Acceptance criteria

- [ ] Insights have been shared out to team

**Comment by andaleliz** [comment]
[Mural board to start gathering insights](https://app.mural.co/t/vsa8243/m/vsa8243/1587382187382/22e7d78e4344299d47cf1212f675dcc9b4def21a). Very much a work in progress, draft - posting at this time solely for documentation purposes.

**Comment by andaleliz** [comment]
Recapping convo between me and Samara documentation sake, originally posted in Slack by Samara:
>The purpose of the research review has two goals: 1) to establish a foundation for whoever is doing the logged in homepage design and 2) to make sure any user research we do isn't unnecessarily duplicative. Given that, the exercise here is really more about having a solid background than producing a comprehensive report that aggregates all the findings in one place. That feels overly duplicative and not like the best use of time.

>Conclusion: The research review report can be really simple and should serve as a jumping off point into the full reports themselves. Having the list is half the battle, so the "report" just needs to be the list of research we collected, a short summary of what the work was, and short list of bullet points of high-level conclusions.

**Comment by andaleliz** [comment]
@Samara-Strauss [Here's the previous research review write-up](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/previous-research-review.md) I put together. Hopefully this aligns with what you had in mind. If so, I'll close this out. Thanks!

**Comment by Samara-Strauss** [comment]
Hey! So this is definitely a good start. For each report/journey map, I think it would be helpful to have a 1 -2 sentence summary and, if necessary, ~3ish bullet points outlining important takeaways or highlights. I've created a couple examples below. What do you think? I'm hoping it won't take a significant time to put together something like this for each resource.

### [Personalization 2.0 Discovery: Summary and Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/personalization%202.0/discovery-research/README.md)

This 2019 report re-evaluate the MVP versions of VA.gov's My VA dashboard, user profile, and account settings page. Takeaways include:

- Why we should redesign the logged-in homepage and get rid of the My VA dashboard.
- Why we should combine the existing profile and account pages.
- Goals for these proposed efforts.
- Mockups showing what a potential future could look like.

### [Disabilities claim process map](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/va-product-journey-maps/Veteran%20Journey%20-%20Disability%20Claim%20-%2011x17%20-%20%209.4.17.pdf)

This journey map details the VA disability claims process from application to receipt of benefits, focusing on actions needed and veterans' positive, negative, and neutral feelings. We should use this resource to familiarize ourselves with the claims process and inform how we might highlight claims on the new logged-in homepage.

**Comment by andaleliz** [comment]
@Samara-Strauss, I am so grateful for version history right now! That was my first approach - but it felt too long for what we had discussed.  

Can you take a peek [at this version](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/previous-research-review-detailed.md) and just confirm it's what you're thinking? No need to go over the details, it needs finishing touches for sure (and the links are wonky for some reason)

**Comment by Samara-Strauss** [comment]
That first version is great!! Let's go with that.

**Comment by Samara-Strauss** [comment]
Though I don't think we need the additional appendix at the bottom if you've already linked the research document above.

**Comment by andaleliz** [comment]
Great! I've cleaned it up, and [updated the original](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/previous-research-review.md) `.md` file I created.  Deleted the second one to minimize confusion down the road.

I think this will serve our purposes well!

**Comment by Samara-Strauss** [comment]
This looks great to me! I think we can call this one done :) Feel free to close this ticket whenever.
