### ISSUE TITLE
Update VFS Roster Management Page to Reflect New Atlas Process

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72655]
## Description 
We currently have documented the process for adding a new team member to the VFS roster. However, we are now updating this information in the Atlas App and need to update the instructions on this page to reflect that: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2798846283/VFS+Roster+Management

Additional notes from our previous meeting (steps to add to process or items to explore):

- Before adding a person, check the de-activated users list to ensure they aren’t already listed as a record. People are constantly in rotation, so we want to be sure that they aren’t already in existence.
---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify if we need to update the page with any information that is not already outlined here: https://vfs.atlassian.net/wiki/spaces/PPT/pages/2806841369/Atlas+User+Manual (i.e. information that is specific to our team that does not apply to the other page) 
- [x] If there is none, we can just include the Atlas App page on the VFS Roster Management confluence page using the include page feature (under the plus sign)
- [x] If we do have details we need to add that are specific to our team we can update the page with that information while also including the Atlas App page above
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Duplicate ticket: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/73715

Closing this one.
