### ISSUE TITLE
Vets-API: Remove/Replace PagerDuty References to eMIS

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#72650]
## Issue Description
As part of the code deletion for eMIS, we'll need to replace the PagerDuty references to eMIS that exist in Vets-API.

Previous discovery for this work can be found in this [Zenhub ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/72202). (A separate ticket has been created to replace PagerDuty references to eMIS that exist in PagerDuty.)

The following are PagerDuty references for eMIS which could be replaced in Vets-API:

- [x] The [poll_maintenance_window_spec:84](https://github.com/department-of-veterans-affairs/vets-api/blob/a03f7e59f83f864792fd706bfc6535328b6d581d/spec/sidekiq/pager_duty/poll_maintenance_windows_spec.rb#L84) references an eMIS-related maintenance window factory
- [x] [Maintenance window factories](https://github.com/department-of-veterans-affairs/vets-api/blob/a03f7e59f83f864792fd706bfc6535328b6d581d/spec/factories/maintenance_windows.rb#L12-L68)
- [x] Pagerduty eMIS reference in [settings.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/f48b45006b708fb74be3ca7c155e5c279d40eb21/config/settings.yml#L889)
- [x] In that same file is a [PagerDuty Vet360 reference](https://github.com/department-of-veterans-affairs/vets-api/blob/f48b45006b708fb74be3ca7c155e5c279d40eb21/config/settings.yml#L236).(Vet360 is the old name for VAProfile.) Not sure if we want to repurpose this or keep as-is.
- [x] eMIS references are also present in this VCR Cassette: [spec/support/vcr_cassettes/pagerduty/external_services/get_services.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/f48b45006b708fb74be3ca7c155e5c279d40eb21/spec/support/vcr_cassettes/pagerduty/external_services/get_services.yml#L66-L210)
- For context, the above cassette is being used in the following specs, though the eMIS-related portions of it aren’t specifically being referenced:
--- [spec/lib/pagerduty/external_services/service_spec.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/f48b45006b708fb74be3ca7c155e5c279d40eb21/spec/lib/pagerduty/external_services/service_spec.rb#L11)
--- [vets-ap/spec/support/pagerduty/services/spec_setup.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/f48b45006b708fb74be3ca7c155e5c279d40eb21/spec/support/pagerduty/services/spec_setup.rb#L7)

---
## Tasks
- [x] Remove/replace references to eMIS in Vets-API where necessary.

## Acceptance Criteria
- [x]  Vets-API code files are updated where necessary to remove/replace eMIS references.
---

**Comment by rmtolmach** [comment]
> eMIS references are also present in this VCR Cassette: [spec/support/vcr_cassettes/pagerduty/external_services/get_services.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/f48b45006b708fb74be3ca7c155e5c279d40eb21/spec/support/vcr_cassettes/pagerduty/external_services/get_services.yml#L66-L210)

I'm going to leave the emis references in the VCR cassette mentioned. 

> In that same file is a [PagerDuty Vet360 reference](https://github.com/department-of-veterans-affairs/vets-api/blob/f48b45006b708fb74be3ca7c155e5c279d40eb21/config/settings.yml#L236).(Vet360 is the old name for VAProfile.) Not sure if we want to repurpose this or keep as-is.

I'm going to leave as-is. 🤔 Unless we want to rename it?

**Comment by rmtolmach** [comment]
PR is merged. Closing.
