### ISSUE TITLE
[Discovery] Logged-in homepage: Comparative analysis

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7266]
## Background

Epic #6326

As part of the logged-in homepage discovery, we would like to conduct a comparative analysis of other dashboards/notification centers.

## Tasks

- [x] Compile list of experiences to compare
- [x] Conduct analysis
- [x] Write-up findings
- [ ] Share with team

## Acceptance criteria

- [ ] Comparative analysis has been written up and shared with team

**Comment by andaleliz** [comment]
**Experiences mentioned in stakeholder interviews**
- Banking/finance mentioned repeatedly - Chase, BofA and Fidelity, specifically called out
- USAA
- Insurance - Geico, State Farm. BCBC listed as bad example
- Less traditional payment solutions like PayPal + Square
- Delta
- Google + Apple (personalization across a suite / ecosystem)

**Comment by andaleliz** [comment]
@Samara-Strauss, can we touch base (either here or we can meet) about what you have in mind in terms of output/documentation for this activity?  I felt that was productive for the previous research + analytics pieces, and realize now we didn't really discuss this one. 

cc @sshein for awareness

**Comment by Samara-Strauss** [comment]
HI! I am totally happy to meet quickly to discuss if that's helpful. 

[Here is a comparative analysis I did as part of last summer's personalization 2.0 research](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Identity/Personalization/Personalization%202.0/Discovery%20%26%20Research/Comparative%20Analysis). There are a few things I find useful about this format:

- I outlined what questions I was hoping to answer for the analysis.
- Lots of good screenshot examples!
- Explanation of what I think those screenshots illustrated and what we could learn from these examples.

What do you think? I am totally open to discussion and suggestions around the exact format this takes. If the above example looks good, great! If not, or if there are remaining questions, let's get something on the calendar for later today.

**Comment by andaleliz** [comment]
@Samara-Strauss That's exactly what I figured, but wanted to make sure to ask. No need to discuss further! Thank you. 😄

**Comment by andaleliz** [comment]
@Samara-Strauss, I came up with a list of questions to help frame things as I look at sites and solicit screenshots from other people for sites I don't have access to.  

I don't think that **every** site will answer **all** the questions, but I think it'll be valuable to keep all of these questions in my pocket.  I'm not planning on re-investigating the things you explored in your study.  Is there anything you'd like to change about this list?

- What are sites doing to signify they're providing a personalized experience once logged in?
- How do sites organize different types of content within a single logged-in homepage/dashboard view?
  - How is important information surfaced?
  - How are new features and "upsells" handled?
  - Does any of the content straddle the line between a dashboard / profile? 
  - If so, where did they place it?
- How do sites present different types of content? What appears as  widget vs  text link vs something else?
- What are sites doing for logged-in alerts/notifications?
  - Where do they live?
  - How are they marked as read/dismissed?
- How does navigation change when logged in?
  - How do you get back to your dashboard?
  - How do you get to content that is available without logging in?
- How do other sites make their logged-in homepage scaleable?

**Note on that last bullet**: I realize that will be hard to answer definitively, but important to keep my eyes out for. I may be able to get screenshots from folks who use the same site in different ways, which would help us understand that.  The finding in your write-up is an example of the kind of things I'd be looking for:

>Has a generic "Settings" page, which is currently sparse but could grow over time without having to change the nomenclature since "Settings" isn't overly specific.

**Comment by Samara-Strauss** [comment]
This list looks great to me!

> What are sites doing to signify they're providing a personalized experience once logged in?

For this, one of my expectations was that you would look at how the navigation changes, especially if there is a marked difference between a logged out view/a separate marketing site and logged in dashboard. I guess this might also get covered under "How are new features and "upsells" handled?" Just wanted to call that out in case you were thinking of something else there.

**Comment by andaleliz** [comment]
I was thinking more broadly with that question, looking more at overall how is site is welcoming the user and creating an overall sense of, "we know it's you, we know what's most important/relevant to you".  It'll be interesting to see if anyone crosses the Creepy Factor line too!  

I think all of the questions that follow also answer that in more specific ways (nav is addressed by the second to last bullet) but I wanted to write that down in a more broad sense, especially as I ask folks to help by providing screen shots.

**Comment by sshein** [comment]
I'd be happy to share what we did with QPP, liz, for the logged in navigation / homepage

**Comment by andaleliz** [comment]
@sshein That'd be great! Thanks for offering. What's the easiest way for you to share?

**Comment by sshein** [comment]
I can drop screencaps somewhere and give you any needed context in a meeting of some kind

**Comment by andaleliz** [comment]
Perfect. I have [an /images folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/images) going already - you can add them here.

**Comment by Samara-Strauss** [comment]
> I was thinking more broadly with that question, looking more at overall how is site is welcoming the user and creating an overall sense of, "we know it's you, we know what's most important/relevant to you". It'll be interesting to see if anyone crosses the Creepy Factor line too!
> 
> I think all of the questions that follow also answer that in more specific ways (nav is addressed by the second to last bullet) but I wanted to write that down in a more broad sense, especially as I ask folks to help by providing screen shots.

Awesome! All of this sounds good to me. Looking forward to seeing this progress!

**Comment by sshein** [comment]
you can see logged out QPP here: https://qpp.cms.gov/ - then when the user logged in, we had a side navigation that had categories and was collapsable. The "Dashboard" wasn't your traditional dashboard but had a timeline of events and then a list of their clinics with status/actions, see below. I'll also add this to your folder.

<img width="771" alt="Screen Shot 2020-05-04 at 3 36 47 PM" src="https://user-images.githubusercontent.com/3856611/81020324-67822680-8e1d-11ea-92c4-c726c1bf4123.png">

**Comment by andaleliz** [comment]
@Samara-Strauss meant to bring this up in planning today - we didn't discuss desktop and/or mobile for this. I've been asking folks to submit desktop screenshots primarily, mobile if they have extra time. But thinking this write up will be focused on desktop views. How does that align with what you were thinking?

**Comment by Samara-Strauss** [comment]
I think this is OK. The more we can get, the better, but we can probably extrapolate mobile patterns from desktop views.

**Comment by andaleliz** [comment]
@Samara-Strauss, [here's the comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/comparative-analysis.md) for your review!

**Comment by Samara-Strauss** [comment]
Yay! I will take a look tomorrow.

**Comment by Samara-Strauss** [comment]
@andaleliz this is awesome! No changes. Thank you so much for putting it together. It's already got my wheels turning about all the things we could do!

Unless anyone else has feedback, I think we can close this.

**Comment by andaleliz** [comment]
You're so welcome -  it got my wheels turning too! It was fun to look through all the sites.  I put a Mural board in the VSA AE room with all the screenshots in case that's helpful to whoever tackles design.
