### ISSUE TITLE
[DISCOVERY] Form526 Submission polling: #1 All the IDs

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#72663]
## Issue Description
With the migration to Lighthouse's API endpoint for submission, instead of receiving information during the submission process, the system will need to "poll" for information about the submission status to display to the user.

The goal is to gain an understanding as to what each "ID" means in the process.

---
## Tasks
- [x] Document the following:
- [x] Where is Form526Submission ID used?
- [x] Where is SavedClaim ID used? Is it relevant to the initial submission?
- [x] What is submitted_claim_id? 
- [x] How important is the `jId` (job ID) that is returned in the initial submission process? [Check the frontend polling mechanism ](https://github.com/department-of-veterans-affairs/vets-website/blob/dff8239bdedf540abb3a845800d42d97af95a170/src/applications/disability-benefits/all-claims/components/ConfirmationPoll.jsx#L45)
- [x] Which one is VBMS ID?

## Acceptance Criteria
- [x] Documented understanding of each ID involved in the initial Form526 process.
[Added information to this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/discovery_submission_polling.md)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
