### ISSUE TITLE
Design | Authenticated Experience | Migrate to Figma | Move Auth Menu Sketch file

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#72670]
## Background 
We need to migrate the auth menu sketch files to Figma. If we encounter weird things with any DST components along the way, we can reach out in #platform-design-system and they'll help us out.

I think it's ok to move this whenever, even though we're actively working on this in January. The FE work will very minimally rely on any mock-ups we produce to reflect changes we make to the current menu.

## Tasks 
- [ ] Add the file to the Account Experience project in Figma
- [ ] Add the libraries (VADS, auth exp)
- [ ] Add the auth exp patten library
- [ ] Go through the file and update components and text styles as needed.  This will likely mostly involve only text styles and maybe icons from VADS, and the heading and annotation components from the auth exp pattern library
- [ ] Update all pages in Figma file accordingly

## Acceptance Criteria 
- [ ] at a minimum, mobile, desktop, and symbol pages are cleaned up and annotated in Figma
- [ ] we've added a link to the Figma file in the product readme file.

**Comment by andaleliz** [comment]
@mtcA6 and @ajakabcin I forgot about this file until this week, and added it to both of your migration epics since it's a cross-team file. I think any of the designers can pick this up when possible.

**Comment by mtcA6** [comment]
good call-out @andaleliz was the why documented in a CAIA ticket somewhere? Or in slack? I remember you shared a list of details about the content decision but can't locate it. I checked #71332 and #72639 and didn't see the why. Searching slack I couldn't find it either. 

I've amended [the outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/authenticated-menu/add-claims-and-disability-rating/README.md#overview) by adding a note section. If you can find a link to that CAIA feedback could you add it to that note? If not let me know and I'll rephrase what is there. 

Including a screen grab so you know what 'note' I'm referring to on the [outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/authenticated-menu/add-claims-and-disability-rating/README.md)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/16ded40b-92b3-4dfb-a961-c7c7a7b16173)
