### ISSUE TITLE
[Discovery] Logged-in homepage: User research

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7268]
## Background

Epic #6326

As part of the logged-in homepage discovery phase, we have decided to conduct user interviews/testing to help us better gauge user needs and expectations.

## Tasks

- [x] Create research plan #7269
- [x] Create card sort #8230
- [x] Create co-design with veterans exercise #8232
- [x] Create conversation guide #7270
- [x] Kick-off recruiting #7273
- [x] Conduct interviews #7274
- [x] Synthesis #7276

## Acceptance criteria

- [x] Synthesis is complete and has been shared with the team
