### ISSUE TITLE
Update FAQ guidance in Style Guide

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#72683]
## Description
While working on the [Accordion Guidance for the Style guide](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/71566), I realized that our advice for [FAQ sections](https://vfs.atlassian.net/wiki/spaces/AP/pages/2563244774/The+Do+s+and+Don+ts+of+Writing+FAQs) needed to be updated to reflect the overall accordion guidance. So I updated the FAQ guidance. I scored it a 2.  

## Tasks

- [x] Draft new guidance for FAQs
- [x] Review FAQ guidance with rest of the content team
- [x] Make changes based on feedback from Team
- [x] Publish changes to Style Guide

## Acceptance Criteria

- [x] Style guide has been updated with new guidance.

**Comment by johnny-jesensky-adhoc** [comment]
Confirmed with Brian these edits are done during stand-up (1/03). Marking this as _Done_.
