### ISSUE TITLE
PM | Profile | Contact Center Guide | Major Issues and Error Messages Updates

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72692]
## Background
After working through the contact center guide to update for references to the profile hub we need to continue to refine the guide. As I was progressing through it was clear this needed a major rework and needed to be broken down into it's component parts because the guide is 100+ pages.

### Major Issues and Error Messages:
Error messages or alerts SPECIFIC to your product are an important tool for contact center representatives trying to triage an issue. Please provide screenshots and descriptions of ALL error or warning messages that are specific to your product. For each of these error messages, please provide the following:

- Screenshot of the error message
- Explanation of what might be causing the problem
- Suggestions for what might resolve the error message
- If available, please include any known work arounds

## Tasks 
need to create a ticket for each section of the profile and update the errors and major issues sections 

```[tasklist]
### Tasks
- [ ] PM | Profile | Contact Center Guide | Profile Hub
- [ ] PM | Profile | Contact Center Guide | Personal Info
- [ ] PM | Profile | Contact Center Guide | Contact Info
- [ ] PM | Profile | Contact Center Guide | Military Info
- [ ] PM | Profile | Contact Center Guide | Direct Deposit 
- [ ] PM | Profile | Contact Center Guide | Notification Settings
- [ ] PM | Profile | Contact Center Guide | Account Security 
- [ ] PM | Profile | Contact Center Guide | Connected Apps
``` 

## Acceptance Criteria 
The contact center guide has been refreshed
