### ISSUE TITLE
QA | Profile | Contact Center Guide | Profile Hub

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72693]
## Background
Update the profile hub section to incorporate the major issues and errors users might see

### Major Issues and Error Messages:
Error messages or alerts SPECIFIC to your product are an important tool for contact center representatives trying to triage an issue. Please provide screenshots and descriptions of ALL error or warning messages that are specific to your product. For each of these error messages, please provide the following:

- Screenshot of the error message
- Explanation of what might be causing the problem
- Suggestions for what might resolve the error message
- If available, please include any known work arounds

## Tasks
- [x] check each navigation section for reference to the nav menu on the left (Use personal information steps in combination with navigation settings steps to rewrite the steps for every tool) 
     - [x] Profile Hub 
     - [x] Personal Info 
     - [x] Personal Health Care Contacts
     - [x] Contact Info 
     - [x] Military Info 
     - [x] Direct Deposit
     - [x] Notification Settings 
     - [x] Account Security 
     - [x] Connected Apps
- [x] add all of the major issues and errors 

## Artifacts
- Product guide before updates : [VA.gov.Profile.product.guide.v10.07032024.docx](https://github.com/user-attachments/files/19216211/VA.gov.Profile.product.guide.v10.07032024.docx)

**Comment by oddJoseph** [comment]
Have created the following test cases to test all areas.  WIll be comparing to existing tests to ensure completeness...




<html>
<body>
<html><head></head><body><h1>VA.gov Profile Test Plan and Detailed Test Cases</h1>
<h2>Objective</h2>
<p>To thoroughly test functional and accessibility aspects of the VA.gov Profile application, ensuring that all user interactions perform correctly, are accessible to all users, and align with the provided product guide.</p>
<h2>Scope</h2>
<ul>
<li>Profile Hub</li>
<li>Personal Information</li>
<li>Contact Information</li>
<li>Personal Health Care Contacts</li>
<li>Military Information</li>
<li>Direct Deposit</li>
<li>Notification Settings</li>
<li>Account Security</li>
<li>Connected Apps</li>
</ul>
<h2>Test Cases</h2>
<h3>Profile Hub</h3>
<pre><code class="language-gherkin">Scenario: LOA3 User Profile Access
Given a user has verified their identity (LOA3)
When the user signs in to VA.gov
And selects Profile from the authenticated menu
Then the Profile Hub should display with access to all profile sections

Expected Result: Profile hub displays correctly with all profile sections available.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Keyboard Navigation
Given a user navigates using a keyboard
When the user tabs through the Profile Hub
Then all interactive elements receive focus and are operable via keyboard
Expected Result: All interactive elements are reachable and operable by keyboard.
</code></pre>
<h3>Personal Information</h3>
<pre><code class="language-gherkin">Scenario: Verify Non-Editable Legal Name and DOB
Given an LOA3 user views their Personal Information
Then the legal name and date of birth fields appear correctly but are not directly editable
Expected Result: Legal name and DOB are displayed correctly and links to FAQs provided.
</code></pre>
<pre><code class="language-gherkin">Scenario: Edit Preferred Name
Given a user in the Personal Information section
When editing their preferred name and clicking save
Then the preferred name updates successfully
Expected Result: Preferred name is updated and displayed correctly.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Screen Reader Navigation
Given a screen reader user
When navigating the Personal Information section
Then all fields and alerts are announced clearly
Expected Result: All fields and alerts are read out clearly.
</code></pre>
<h3>Contact Information</h3>
<pre><code class="language-gherkin">Scenario: Address Editing with Validation
Given an LOA3 user accesses Contact Information
When editing the address with validation prompts
Then suggestions or alerts appear, and user confirms address
Expected Result: Address saves successfully upon user confirmation.
</code></pre>
<pre><code class="language-gherkin">Scenario: Invalid Phone Number Error
Given a user enters an invalid phone number
When attempting to save
Then an appropriate validation error message appears
Expected Result: Clear error messaging guides the user to correct input.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Validation Error Announcement
Given a screen reader user enters an invalid phone number
When the user attempts to save
Then the validation error message is clearly announced
Expected Result: Error message clearly announced by the screen reader.
</code></pre>
<h3>Personal Health Care Contacts</h3>
<pre><code class="language-gherkin">Scenario: View Health Care Contacts
Given a user enrolled in VA healthcare benefits
When accessing health care contacts
Then emergency contacts and next-of-kin details display correctly
Expected Result: Correct details displayed clearly.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Keyboard Navigation
Given a keyboard user
When accessing healthcare contacts
Then all fields and links are accessible and operable
Expected Result: All fields operable via keyboard.
</code></pre>
<h3>Military Information</h3>
<pre><code class="language-gherkin">Scenario: Display Military Information
Given an LOA3 user accesses Military Information
Then service branch and periods of service are displayed correctly
Expected Result: Accurate military details are displayed.
</code></pre>
<pre><code class="language-gherkin">Scenario: Military Information Error Handling
Given military information cannot be accessed
When user views the Military Information section
Then an appropriate error message with contact information appears
Expected Result: User receives clear instructions to contact support.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Keyboard Accessibility
Given a keyboard user navigates Military Information
Then all elements and links are fully operable via keyboard
Expected Result: All interactive elements accessible by keyboard.
</code></pre>
<h3>Direct Deposit</h3>
<pre><code class="language-gherkin">Scenario: Successfully Update Bank Information
Given an LOA3 user
When entering valid bank details and clicking save
Then information saves and a confirmation message/email is sent
Expected Result: Confirmation message/email received with updated details.
</code></pre>
<pre><code class="language-gherkin">Scenario: Invalid Routing Number
Given a user inputs an invalid routing number
When attempting to save
Then appropriate validation error message displayed
Expected Result: Clear validation error message displayed.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Form Interaction
Given a screen reader user
When updating direct deposit
Then form fields and errors clearly announced
Expected Result: Clear and accurate screen reader announcements.
</code></pre>
<h3>Notification Settings</h3>
<pre><code class="language-gherkin">Scenario: Update Notification Preferences
Given an LOA3 user with mobile number added
When updating preferences
Then changes save with confirmation message
Expected Result: Notification settings save successfully with confirmation.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Checkbox Interaction
Given a screen reader and keyboard user
When interacting with notification checkboxes
Then selections clearly indicated audibly and visually
Expected Result: Clear audible feedback and visual confirmation provided.
</code></pre>
<h3>Account Security</h3>
<pre><code class="language-gherkin">Scenario: Identity Verification
Given an LOA1 user
When completing identity verification
Then user gains access to all profile sections
Expected Result: Full profile access after verification.
</code></pre>
<pre><code class="language-gherkin">Accessibility Scenario: Identity Verification Flow
Given a keyboard user
When navigating verification
Then all fields operable via keyboard
Expected Result: Verification process fully accessible by keyboard.
</code></pre>
<h3>Connected Apps</h3>
<pre><code class="language-gherkin">Scenario: Connect Third-party App
Given LOA3 user
When connecting a third-party app
Then app successfully connects and is displayed
Expected Result: App displayed correctly in Connected Apps section.
</code></pre>
<pre><code class="language-gherkin">Scenario: Disconnect Third-party App
Given user has apps connected
When disconnecting an app
Then app disconnects and confirmation displayed
Expected Result: Successful disconnection with confirmation message.
</code></pre>
<h3>Entry Criteria Checklist</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" disabled=""> Application available</li>
<li class="task-list-item"><input type="checkbox" disabled=""> Test cases reviewed and approved</li>
<li class="task-list-item"><input type="checkbox" disabled=""> Test environment ready</li>
</ul>
<h3>Exit Criteria Checklist</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" disabled=""> All test cases executed</li>
<li class="task-list-item"><input type="checkbox" disabled=""> No critical defects unresolved</li>
</ul>
<h2>Sample Report Formats</h2>
<p><strong>Test Execution and Defect Report:</strong></p>

Test Case ID | Scenario | Steps | Expected Result | Actual Result | Pass/Fail | Defect ID
-- | -- | -- | -- | -- | -- | --
TC001 | Profile Hub Access | Given-When-Then | Profile Hub available | Profile Hub displayed | Pass | N/A


<h2>Entry Criteria</h2>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" disabled=""> Application availability confirmed</li>
<li class="task-list-item"><input type="checkbox" disabled=""> Test cases reviewed and approved</li>
</ul>
<h2>Exit Criteria</h2>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" disabled=""> All test cases executed</li>
<li class="task-list-item"><input type="checkbox" disabled=""> No unresolved critical issues</li>
</ul></body></html>
</body>
</html>

**Comment by mtcA6** [comment]
@oddJoseph totally missed that I didn't add this into the sprint, when might we have an updated word doc?

**Comment by oddJoseph** [comment]
**UPDATED**

# VA.gov Profile Test Plan and Detailed Test Cases

## Objective
To thoroughly test functional and accessibility aspects of the VA.gov Profile application, ensuring that all user interactions perform correctly, are accessible to all users, and align with the provided product guide.

## Scope
- Profile Hub
- Personal Information
- Contact Information
- Personal Health Care Contacts
- Military Information
- Direct Deposit
- Notification Settings
- Account Security
- Connected Apps

## Test Cases

### Profile Hub

```gherkin
Scenario: LOA3 User Profile Access
Given a user has verified their identity (LOA3)
And the user does not have one of the flags (fiduciary, incompetent, deceased)
When the user signs in to VA.gov
And selects Profile from the authenticated menu
Then the Profile Hub should display with access to all profile sections
Expected Result: Profile hub displays correctly with all profile sections available.
```

```gherkin
Scenario: LOA1 User Profile Access
Given a user has not verified their identity (LOA1)
When the user signs in to VA.gov
And attempts to access the Profile Hub
Then the user is redirected to the Account Security page
Expected Result: Redirected to Account Security page with appropriate messaging.
```

```gherkin
Accessibility Scenario: Keyboard Navigation
Given a user navigates using a keyboard
When the user tabs through the Profile Hub
Then all interactive elements receive focus and are operable via keyboard
Expected Result: All interactive elements are reachable and operable by keyboard.
```

### Personal Information

```gherkin
Scenario: Verify Non-Editable Legal Name and DOB
Given an LOA3 user views their Personal Information
Then the legal name and date of birth fields appear correctly but are not directly editable
Expected Result: Legal name and DOB are displayed correctly and links to FAQs provided.
```

```gherkin
Scenario: Edit Preferred Name
Given a user in the Personal Information section
When editing their preferred name and clicking save
Then the preferred name updates successfully
Expected Result: Preferred name is updated and displayed correctly.
```

```gherkin
Accessibility Scenario: Screen Reader Navigation
Given a screen reader user
When navigating the Personal Information section
Then all fields and alerts are announced clearly
Expected Result: All fields and alerts are read out clearly.
```

### Contact Information

```gherkin
Scenario: Address Editing with Validation
Given an LOA3 user accesses Contact Information
When editing the address with validation prompts
Then suggestions or alerts appear, and user confirms address
Expected Result: Address saves successfully upon user confirmation.
```

```gherkin
Scenario: Invalid Phone Number Error
Given a user enters an invalid phone number
When attempting to save
Then an appropriate validation error message appears
Expected Result: Clear error messaging guides the user to correct input.
```

```gherkin
Accessibility Scenario: Validation Error Announcement
Given a screen reader user enters an invalid phone number
When the user attempts to save
Then the validation error message is clearly announced
Expected Result: Error message clearly announced by the screen reader.
```

### Personal Health Care Contacts

```gherkin
Scenario: View Health Care Contacts
Given a user enrolled in VA healthcare benefits
When accessing health care contacts
Then emergency contacts and next-of-kin details display correctly
Expected Result: Correct details displayed clearly.
```

```gherkin
Accessibility Scenario: Keyboard Navigation
Given a keyboard user
When accessing healthcare contacts
Then all fields and links are accessible and operable
Expected Result: All fields operable via keyboard.
```

### Military Information

```gherkin
Scenario: Display Military Information
Given an LOA3 user accesses Military Information
Then service branch and periods of service are displayed correctly
Expected Result: Accurate military details are displayed.
```

```gherkin
Scenario: Military Information Error Handling
Given military information cannot be accessed
When user views the Military Information section
Then an appropriate error message with contact information appears
Expected Result: User receives clear instructions to contact support.
```

```gherkin
Accessibility Scenario: Keyboard Accessibility
Given a keyboard user navigates Military Information
Then all elements and links are fully operable via keyboard
Expected Result: All interactive elements accessible by keyboard.
```

### Direct Deposit

```gherkin
Scenario: Successfully Update Bank Information
Given an LOA3 user
When entering valid bank details and clicking save
Then information saves and a confirmation message/email is sent
Expected Result: Confirmation message/email received with updated details.
```

```gherkin
Scenario: Invalid Routing Number
Given a user inputs an invalid routing number
When attempting to save
Then appropriate validation error message displayed
Expected Result: Clear validation error message displayed.
```

```gherkin
Accessibility Scenario: Form Interaction
Given a screen reader user
When updating direct deposit
Then form fields and errors clearly announced
Expected Result: Clear and accurate screen reader announcements.
```

### Notification Settings

```gherkin
Scenario: Update Notification Preferences
Given an LOA3 user with mobile number added
When updating preferences
Then changes save with confirmation message
Expected Result: Notification settings save successfully with confirmation.
```

```gherkin
Accessibility Scenario: Checkbox Interaction
Given a screen reader and keyboard user
When interacting with notification checkboxes
Then selections clearly indicated audibly and visually
Expected Result: Clear audible feedback and visual confirmation provided.
```

### Account Security

```gherkin
Scenario: Identity Verification
Given an LOA1 user
When completing identity verification
Then user gains access to all profile sections
Expected Result: Full profile access after verification.
```

```gherkin
Accessibility Scenario: Identity Verification Flow
Given a keyboard user
When navigating verification
Then all fields operable via keyboard
Expected Result: Verification process fully accessible by keyboard.
```

### Connected Apps

```gherkin
Scenario: Connect Third-party App
Given LOA3 user
When connecting a third-party app
Then app successfully connects and is displayed
Expected Result: App displayed correctly in Connected Apps section.
```

```gherkin
Scenario: Disconnect Third-party App
Given user has apps connected
When disconnecting an app
Then app disconnects and confirmation displayed
Expected Result: Successful disconnection with confirmation message.
```

**Comment by mtcA6** [comment]
@oddJoseph do you have an update of the attached product guide? 

I usually use track changes. Can you reschedule the hour w me?

**Comment by oddJoseph** [comment]
[https://docs.google.com/document/d/1e4_8tV1hnX8hxCeRNbA_-HjswGONm7E3_FRzjjHHxbY/edit?usp=sharing](url)

**Comment by mtcA6** [comment]
@oddJoseph added comments, some of the updates you made aren't correct. Once you correct them, let me know.

**Comment by mtcA6** [comment]
@oddJoseph sorry for the barrage of messages on here, was thinking a bit more as i reread the steps, i checked all of the navigation steps and those reference the hub so I checked those off. 

What I can't tell is if there are more errors that could pop up on the profile hub that need to be documented specifically in the profile hub section. Right now the only errors are the Bad address indicator (BAI) and the generic error if the entire site is failing. Are there any other possible errors that could pop there?

**Comment by oddJoseph** [comment]
@mtcA6  Thanks for the notes.  I have fixed the items you have noted.  In reference to your last message I will investigate this but we probably want it to be a different ticket for the future.

**Comment by mtcA6** [comment]
If you cannot answer it in 30-50 min looking at the code then we can call it done. But I don't want to carve this off into another ticket since the specific goal of this ticket is to document those errors and warning.

**Comment by mtcA6** [comment]
@oddJoseph still not looking quite right. Preferred name functionality should not be deleted unless you're moving it to a new place in the document and I missed that 

![Image](https://github.com/user-attachments/assets/a19c73a0-d3c2-4d97-8f18-5977f43cc4bf)

**Comment by oddJoseph** [comment]
> [@oddJoseph](https://github.com/oddJoseph) sorry for the barrage of messages on here, was thinking a bit more as i reread the steps, i checked all of the navigation steps and those reference the hub so I checked those off.
> 
> What I can't tell is if there are more errors that could pop up on the profile hub that need to be documented specifically in the profile hub section. Right now the only errors are the Bad address indicator (BAI) and the generic error if the entire site is failing. Are there any other possible errors that could pop there?

@mtcA6   for the profile hub section there shouldn't be errors other than those.  If they don't apply or don't exist it appears that section doesn't exist.  The errors aren't presented for each section until you go into the section details.

**Comment by mtcA6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/108288
