### ISSUE TITLE
[Discovery] Logged-in homepage: User research — Create conversation guide

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7270]
## Background

Epic #7268

As part of the logged-in homepage discovery phase, we have decided to conduct user interviews/testing to help us better gauge user needs and expectations.

## Tasks

- [x] Create conversation guide
- [x] Share with team
- [ ] Revise as necessary 

## Acceptance criteria

- [ ] Conversation guide is ready to be sent to Lauren to kick off recruiting

**Comment by andaleliz** [comment]
Providing an update - @sshein and I are collaborating on this today.  Will provide link here ASAP.

**Comment by Samara-Strauss** [comment]
Yay! Thank you for the update. It's super helpful. :)

**Comment by andaleliz** [comment]
@Samara-Strauss, hold on to your hat - [the conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/user-research/conversation-guide.md) is ready for you to review.  Looking forward to your feedback :)

**Comment by Samara-Strauss** [comment]
This is so great and I am so excited! Here are my thoughts. Let's discuss!

### Warm up

- For the warm up questions, can you ask what benefits they receive? This could be helpful for us to know in case they don't know what they want on their personalized homepage and we need help them think this through. 

### First task: Review current logged-in homepage

- I feel pretty strongly about this — can we not show them the current homepage until the very end of the research session? I think this will prime them and I don't want them to think they need to create a personalized homepage that looks just like the existing one. Let me know why you added this as the first section if feel strongly that this section should stay here.

### Second task: Create and Review Items

- Not that you'll necessarily stick with the script verbatim here, but I think you'll really need to drive home that what we are creating is their personalized homepage (as opposed to a generic homepage for all veterans). With the current wording, I don't think this is entirely clear.
- **To get started, let's create some stickies for the top 5 things you'd want to see when you log in.** Let me know what you think of this — what if we just ask what they want to see on their personalized homepage and then have them go back and prioritize/pick a top five later? Why: first, I don't want them to feel too boxed in right away and be too preoccupied with picking a top five instead of just letting us know what they care about. Second, we need to be prepared that they may list items that need to be broken down further, eg. "I want to see my health care information". Third, while I know we'll need to keep an eye on the time, I'd love if most of the participants' responses were self-generated. This is nothing against the pre-existing list we'll have— just that the less we can prompt, the more we'll know the veterans' responses are a result of their needs and not our priming.
- For things to watch for, we should know *why* each item is important to the participant. I could see this sparking good discussion/thinking for the organizing step, especially if we need to help them a bit.
- Also, within reason, we should want to know what information they expect to see with a particular item. For example, if they want to see their upcoming appointments, what do they want to know? We'll need to be careful not to go down too much of a rabbit hole here, but I'm wondering if understanding some of these specifics might help us as we determine what needs to be a more visual widget/block vs. a link *and* potentially give us insight into what information they consider to be notification/update related. Let me know your thoughts. I don't want this to derail the rest of the activity.

### Third Task: Organize Items

- **Let's organize the stickies on the page in the way you'd want to see them.** This is going to be so interesting! I know not everything is going to be in the convo guide because this exercise is super open ended, but I was just thinking that if people have trouble, we can ask them questions based on what they already mentioned was a priority. "What's the most important item?" "You mentioned X was important. Let's start there." No changes needed to the conversation guide, just food for thought!

----

### Backup Task 1: Card Sort

- **Go ahead and start moving the cards.** I know you might not stick to the script verbatim, but I still think this section could use more of an explanation of what the task is. We need to make sure the veteran understands they should move the cards into the homepage column the they would want to see on their homepage. Also, we should make it clear what the expectation is with the second column so they know how to use it if they want.
- Also, similar feedback to the first section of the co-design activity — for things to watch for, we should know why items are important and what kind of info would be associated with those items.

### Backup Task 2: Grouping cards

- If we haven't already, let's capture priority here. As best we can, we can order the items from most to least important.

### Post-Task Interview

- **If applicable: We didn't really talk about how this homepage might be different from your VA profile. Maybe they shouldn't be different. What are your thoughts around that?** If we ask this question, it might be helpful to make sure they know what the profile is. This could actually be a good time to bring up VA.gov and have a quick convo around this instead of talking about the website at the beginning of the research session. Also, I would phrase this more like "What do think the difference is between your personalized homepage/dashboard and your profile?" and lead the convo from there. I could see the current wording of this question being confusing.

### Thank-You and Closing

Up to you, but I usually remind them that they're going to be compensated for their time.

**Comment by andaleliz** [comment]
@Samara-Strauss The guide has been updated with everything we discussed today. One thing we didn't talk about:
>Up to you, but I usually remind them that they're going to be compensated for their time.

I haven't done that in the past because I'm not really sure how that works and can't answer any follow-up questions about it. Happy to remind them though if you can point me to details should they ask.

Second, as I worked through the card sort script, I thought more about your comment
>Third, while I know we'll need to keep an eye on the time, I'd love if most of the participants' responses were self-generated. This is nothing against the pre-existing list we'll have— just that the less we can prompt, the more we'll know the veterans' responses are a result of their needs and not our priming.

I reached out to Optimal Workshop to see if there is a way to do a hybrid sort with both blank/pre-determined cards, and "Create your own" categories.  I don't see a way to do this based on their docs.

Should we plan on an open card sort instead, so we can capture what they say in real time? I think I could easily add our pre-populated items to the sort during the session, if needed.  I hate to make a change while we're so close to the finish line, but I think this would get us closer to what we're doing in Mural.  I'm torn and would love your input.  

Thanks!

**Comment by Samara-Strauss** [comment]
This looks really good! I don't have any additional comments besides the answers to your questions:

> I haven't done that in the past because I'm not really sure how that works and can't answer any follow-up questions about it. Happy to remind them though if you can point me to details should they ask.

I believe that participants are compensated $50 for sessions that are under and hour, and the check is sent by Perigean. If you don't feel comfortable addressing this, that is totally fine! If you do, you might want to confirm with Brian or Shannon that this info is still accurate.

> I reached out to Optimal Workshop to see if there is a way to do a hybrid sort with both blank/pre-determined cards, and "Create your own" categories. I don't see a way to do this based on their docs.

This is a really great point, definitely something I had not thought of! From a quick scan through Optimal Workshop, it doesn't look like we can modify the list of items even in an open card sort once the card sort has launched. I think we can leave the convo guide the way it is and know that not being able to add veteran-generated items to the card sort is a constraint. If people mention important items we don't already have in the list, we can document those in our notes.

**Comment by andaleliz** [comment]
Wonderful! I'll close this issue out then.  Talk about a happy Friday!!
