### ISSUE TITLE
[R&D - PI1/24] Figma Transition

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#72725]
## Description

Sketch licenses will not be renewed next year, and all of our work will become inaccessible through the app on Feb. 16, 2024. We need to migrate the Sketch files our team created into Figma so that we can continue working.

Scenario: In common language describe the work or issue

Given: A designer needs to be able to work
When: A designer needs to create or modify new designs
Then: A designer will be able to use updated files in Figma

## Acceptance criteria

- [ ] All Sketch files have been imported into Figma
- [ ] Font and colors have been updated to use VA Design System
- [ ] All local components have been replaced with VA Design System figma components 
- [ ] All prototypes have been recreated in Figma

**Comment by Tom-Davis** [comment]
Closing as all epic work is complete.
