### ISSUE TITLE
Document Management System - FE/BE Development

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#72732]
### Description
To better serve Veterans who have submitted documents we are looking to provide access to those existing documents via a DMS (Document Management System).

VHA stakeholders have requested that we relocate the PDF version of all electronic submissions to DMS (Document Management System) instead of SharePoint

## Product Outline
Access to existing documents via a DMS (Document Management System).

- FE/BE Development

## Definition of done
- [ ] Establish contact with focal from DMS
- [ ] Determine timeline and DMS requirements to accept PDFs
- [ ] Establish service to DMS 
- [ ] Work with DMS to test PDF delivery
- [ ] Notify VAPO who will contact stakeholder for downstream testing and validation
- [ ] Once approved, connect with SharePoint to stop sending PDFs and remove relevant code.
- [ ] Team has identified a path forward to allow for access to existing documents via a DMS (Document Management System)..

### Scope of release:

Access to existing documents via the debt portal.

### Out of Scope:

Including non debt documents or items not already stored.

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

**Comment by Tom-Davis** [comment]
Closing as this effort is no longer needed at this time per @denisecoveyduc .
