### ISSUE TITLE
Pension Team Sprint 11 Plan: 01/03/2024—01/16/2024

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72745]
## Sprint 11: 01/03/2024—01/16/2024

**- Outages (PTO, holiday, or unplanned):** 
-- **Jan 3, 4, 5**: Anh
-- **Jan 3**: Lauren
-- **Jan 8**: Eunice
-- **Jan 12**: Zack
-- **Jan 15 (MLK Day): Everybody**

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL04rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b384788872cbf8969532047561e5ffa4457776b1/Screenshot%202023-12-21%20at%209.04.56%E2%80%AFAM.png" alt="Screenshot 2023-12-21 at 9.04.56 AM.png" />

## Theme(s):

- Preparing artifacts for staging review (design, accessibility, QA) - turn in to Platform by Fri, Jan 12
- Finalize necessary FE changes _for MVP_
- Continue and finish PDF data mapping
- Start schema mapping updates
- E2E testing

## Notes:
- **Create backlog ticket for revisiting enhacend FE signature component options**
- For MVP, leveraging existing "typed" version of the signature on the FE experience and map accordingly to PDF
 
## Goal(s):

**PRODCT/STAGING REVIEW PREP**

- [x] [MVP] Update existing Pension form product guide for Contact Center review #72805
- [x] [MVP] Start draft of Pension Release Plan #72273 - **Vicky, align with Matt and PO on this**
- [x] [MVP] Planning to re-launch static content pages for percentage release #72812
- [x] [MVP] Start preparing for required Accessibility artifacts to prepare for staging review #71563 - **Gretchen/Todd**
- [x] [MVP] Start preparing for required QA artifacts to prepare for staging review #71379 - **Matt/Buddhima/Zack**
- [x] [MVP] Prepare necessary Design artifacts to provide before staging review #71623 - **Maya**

**QA/TESTING**

- [MVP] Review all changes in staging environment in the "Review/QA" column - **Anh helping with this**
- [x] [MVP] Prepare E2E test scenarios for staging review & data mapping purposes #72271 **- Vicky**
- [x] [MVP] Test Pension form flow logic in staging for questions in Step 4 #71136 - **Anyone who can help**
- [x] [MVP] Test Pension form flow logic in staging for Steps 5-7 #71139 - **Anyone who can help**

**RESEARCH/DESIGN**

- [x] Create designs for Step 6 form flow #72498

**_MVP relaunch_**

**ENGINEERING**

**_MVP relaunch: Frontend work_** - **Todd and Tai and Zack, as needed**

- [x] [MVP] Step 4: Revisions to page flow, order and questions #72455
- [x] [MVP] Step 5 & beyond: Update form flow page order #72330
- [x] [MVP] Step 6: Update copy on 3 pages #71855
- [x] [MVP] Step 7 Review application: Update based on overall form field changes #71857

**_PDF data mapping_** - **Scott & Dan**

- [ ] [PDF Mapping] Map online form fields to new PDF for Section 6: Marital Status and Spouse Info #70390
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 7: Prior Marital History #70392
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 8: Dependent Children #70393
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 9: Income and Assets #70394
- [ ] [PDF Mapping] Map online form fields to new PDF for Section 10: Info About Unreimbursed Medical Expenses #70395
- [x] [PDF Mapping] Map online form fields to new PDF for Section 11: Direct Deposit Info #70396
- [x] [PDF Mapping] Map online form fields to new PDF for Section 12: Claim Certification and Signature #70397
- [PDF Mapping] Map online form fields to new PDF for Section 13: Witness to Signature #70398 **_Backlogged. May not do_**

- [x] [MVP] Implement/confirm claim submission date appears on Pension PDF form #71456
-[MVP] Ensure we capture form online user signature properly #72279 - **_Tied into #70397_**

**_Schema mapping_**
- [ ] [MVP] Update vets-json-schema #71917 - **Matt starting this; support from Dan as needed**

**_Migrating to Lighthouse Benefits Intake API:_** 
- [x] [MVP] Add polling to Lighthouse Benefits Intake API #71897 - **Wayne**
- [x] [MVP] Perform API meta data validation #72276 - **Wayne; Reach out to Eric Tillberg about how this has been done/ Ask Emily for more info if needed****

**_Logging and monitoring strategy_**
- [ ] [MVP] Setup DataDog alerts for both retry and queue exhaustion #70462 **- Tai & Buddhima**

**_Other tasks for MVP added to sprint and completed_**

- [x] Request DOMO dashboard setup for Pension #72979
- [x] [MVP] Update existing Pension form product guide for Contact Center review #72805
- [x] [MVP] Decision tree and form clean-up #73036
- [x] [MVP] Step 2 Military Info: Military Service field, update label and not required #72895
- [x] [MVP] Step 4 Household info/spouse's former marriage: Make/fix questions to be required #73203
- [x] [MVP] Step 4 household info: Add alert for "yes" to "Is the land marketable?" #73295
- [x] Step 4 Household Info/Current marriage: Update copy for "Type of marriage" question #72867
- [x] Step 4: Update copy typo for Marital Status #73130
- [x] Step 4 Household info/dependent children info: Move Child info onto a separate page #72989
- [x] Step 4 Household info/dependent children who does not live with you: Move child address, custodian name & amount onto separate page #72994
- [x] [MVP] Step 5 Financial info/Add an unreimbursed care expense: Remove answer option for "One-time" payment #73389
- [x] [MVP] Step 5 Gross Monthly Income: Make/fix questions to be required #73297
- [x] Step 6 Additional info / Faster claim processing: Make question required #73152 - Additional revisions made to this
- [x] [MVP] Add signature to summary page #73016
- [x] [MVP] Create SQL update statement to reset current page #73185
- [x] [MVP] Review unit testing to ensure 80% code coverage for staging review #72977
- [x] Create e2e tests with cypress #72933
- [x] [MVP] Troubleshoot confirmation page errors preventing existing page from showing after user submits form #73245
