### ISSUE TITLE
Host Platform Orientation sessions- January 2024 FY24-Q2

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#72748]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Platform team member supporting Platform Orientation, I want to host, record, transcribe and share the Platform Orientation sessions so that VFS team members are able to be easily oriented to the VA.gov Platform.

## Hypothesis or Bet
If we provide updated guidance to new VFS team members, then they will be able to be oriented to the VA.gov Platform quickly and easily.

## Definition of done
- [ ] Platform has hosted the live sessions for the applicable practice areas.
- [x] Platform has uploaded all recorded sessions to the Platform YouTube channel with the transcript and captions enabled
- [x] Platform has updated the link to the recording on the Orientation Sessions page on Platform Website
- [ ] The above has been completed for the following orientation sessions:
   - [x] General
   - [x] Design & Research
   - [x] QA
   - [x] Accessibility
   - [ ] Analytics
   - [ ] Front-end
   - [x] Back-end
   - [x] Design System

**Comment by shiragoodman** [comment]
@caw310 @michelle-dooley @rmtolmach @CBonade  - please use this epic for any tickets your team/COP creates for supporting Platform Orientation sessions this month. thank you!

**Comment by shiragoodman** [comment]
@micahchiang @CBonade did you guys have tickets for tracking the sessions you hosted? If so, can you please add them as child tickets to this epic? Thank you!

**Comment by caw310** [comment]
@shiragoodman we don't generally create a ticket for the sessions. Is this something you need us to do?

**Comment by shiragoodman** [comment]
@caw310 I think this ticket should suffice. If you or Micah could just comment confirming that everything was completed, that would work.

**Comment by caw310** [comment]
Micah recorded the DST session and uploaded the recording.
