### ISSUE TITLE
Add detail on 'Holiday Release Freeze' section on Deployment Policies

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#72754]
## Description
There was some dialogue that started from a [Slack thread](https://dsva.slack.com/archives/CE4304QPK/p1703174497369149), about what is actually allowed during a Holiday Release Freeze. After some back and forth, it was determine that it was necessary to update some of our documentation on the [Deployment Policies](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-Holidayreleasefreezeschedule) page, underneath the _**Holiday release freeze schedule**_ section.

Some text was provided, and JJ confirmed with Clint on 12/29 the following changes to make:

> 
> **Holiday Release Freeze Schedule**
> During holiday release freezes:
>
>- Automated deployments _**to production and sandbox**_ environments will not occur.
>- _**Teams can still continue to merge code to main or master branches. This will continue to be deployed through development and staging environments during the release freeze time frame.**_
>- All code deploys require approval via the "Requesting out-of-band-deploys" process below
>- Content-only deploys will continue as normal, but support will be limited.
>- Limited support will be available from the Platform team.
>
> There may be a change in this policy as VA dictates.

## Tasks

- [x] Review [Slack thread](https://dsva.slack.com/archives/CE4304QPK/p1703174497369149) to get full context around the ask.
- [x] Make changes to the _Holiday Release Freeze Schedule_ section
- [x] Review changes
- [x] Prepare page for deployment

## Acceptance Criteria

- [x] Edits to page have been made and reviewed
- [x] Page has been deployed

**Comment by taylojill** [comment]
Made changes to the Holiday release freeze schedule as listed above. Resolved two old comments from M. Chelen. Reviewed page for launch-blocking issues, ready to publish.

**Comment by johnny-jesensky-adhoc** [comment]
@taylojill, Confirmed the changes went through with today's deployment. Moving this to _Done_.
