### ISSUE TITLE
Design & Research Orientation - January 2024

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#72757]
## User Story
As a Platform team member supporting Platform Orientation, I want to host, record, transcribe and share the Design & Research Orientation session so that VFS team members are able to be easily oriented to the VA.gov Platform. 

Assignee: @allison0034 @naomimarcussen 

## Description
Platform is responsible for hosting the Platform Orientation sessions once every quarter. These sessions are recorded and shared on Platform Website.

The Design & Research Orientation for FY24-Q2 is January 8 at 2:00pm ET.

## Impacted Artifacts
[Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)

## Tasks
_**Note**: if the Zoom host and the Instructor/Session host are the same person, then all below tasks will be performed by the same individual._

### Zoom host
- [x] Ensure Zoom settings are set according to the guidance: [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) / Before you start your session / Zoom settings
- [x] After the session has been hosted, forward the Zoom recording to the Instructor/Session host
### Instructor/ Session host
- [x] Review the guidance in the [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) for During your orientation session
- [x] Host the orientation session as scheduled
- [x] Download mp4 and vtt files from Zoom recording
- [x] Clean up the transcript
- [x] Upload recording and transcript to YouTube
- [x] Change visibility of previous recording to Private (if applicable)
- [x] Update video link on Platform Website

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The live Design & Research Orientation for the quarter has taken place
- [ ] VFS team members are able to view the latest recording of the orientation session

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
FYSA @allison0034
