### ISSUE TITLE
Update Form 8940

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#72778]
## Issue Description
As a part of the work started with [here](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/71011), we want Form 8940 to reflect the 526 submission date once it is in production.

---
## Tasks
- [ ] Find where date is set for Form 8940
- [ ] Test in staging and post confirming screenshots from VBMS UAT

## Acceptance Criteria
- [ ] Signed at Date in all three pathways reflects Veteran submission date on ancillary form8940 regardless of when the submission was 'programmatically' completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
@lisacapaccioli pinging you on this as 4142 and 0781 are mentioned in the description. Not sure what T-REX would do on this, but happy to support if it makes sense.

**Comment by lisacapaccioli** [comment]
The date stamp issue appears to be wrong on Form 8940 (Veteran's Application for Increased Compensation Based on Unemployability). Carbs did the fixes for 4142 and 0781. Carbs currently doesn't have anything in the backlog for future work for 8940 (we have future work for the other two). I think this is a tech debt that could go to either team.
