### ISSUE TITLE
Discovery - Sketch to Figma migration for all DBEX team design files

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#72772]
Before we lose access to Sketch, migrate all Sketch files to Figma so that we can have access to design files going forward. 

This excludes the Toxic Exposure file, which is captured in #72932

The scope of this ticket is to identify the full scope of files that need to be migrated and creation of migration tickets

### Tasks
 - [ ] Reviewing our and Lydia's sketch files and previous design tickets to get the full account of all files for migration
 
### Acceptance criteria 
- [x] Identify the scope of migration
- [x] A list of all files to migrate
- [x] Smaller tickets created for migration of all sketch files - captured in epic: [DBEX Team - Migrate Sketch files to Figma #73099](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/73099)

### Places to look

1. ~~Sketch files under "Claims and Appeals" project~~
2. ~~Sketch files under other projects~~
3. ~~Sketch files owned by Lydia~~
3. ~~Previous design tickets (maybe other Sketch files outside of the VA.gov Design workplace? - not sure if that will be likely)~~
4. ~~Slack history (search for Sketch links)~~
4. Ask team for other places

##### "526 Error Messages" Sketch project

1. "526 ITF Error Message"
2. "526 Error Message Redesign" 

##### "Claims and Appeals" Sketch project

1. "\*BROKEN FILE\* 526 - Combat Questions" *(not actually broken)*
2. "Combat Questions1"
3. "4142 flow in 526EZ"
4. "526 intro pages"
6. "VA-Notify-content-templates copy"
7. "Form 526 PTSD question 1"
10. "526 - Task List Pattern"
13. "526EZ BDD SHA updates"
15.  "526 VAMC field"
16.  "526 phone number"
17.  "Active Cancer" *(related to pact act, wireframes for 526EZ)*
18.  "526 user flow"
19.  "526EZ form screenshots"
20.  "526 - Contact Page Concept (not applicable)"
23.  "Benefits Delivery at Discharge (BDD)" 
24.  "BDD - Military Service History"
25.  "PTSD Screens - Combat"
26.  "526 military service history"

#### Out of scope

1. "Claims and Appeals" Sketch project
    
    5. ~~"Dependents Management" sketch file~~
    14.  "~~Test123~~" (doctor's appointment, outstanding debt)
    2. ~~"Claim Status Tool" collection~~
    2. ~~"Decision Reviews" collection~~
    8. ~~"Dependents Management" collection > "Dependent Verification Email"~~ 
    9. ~~"Dependents Management" collection > "686C - Foreign Address Issue"~~ 
    10. ~~"Max CFIs" collection > "Max CFI design refinements"~~ *(is this in our team's scope?)*
    11. ~~"Max CFIs" collection > "Max CFI explorations"~~ *(is this in our team's scope?)*
    12. ~~"Max CFIs" collection > "Maxxed CFIs"~~ *(is this in our team's scope?)*
    13. ~~"Non-Disability" collection~~
    2. ~~"526 toxic exposure"~~ (out of scope for this, part of #72932 )
    11. "~~COE - Document Uploaad (sic)~~" *(home loan)*
    12. "~~LGY - COE~~" (home loan)
    21.  "~~COE Multiple Loans~~" *(home loan)*
    22.  "~~Burials - Burial Allowance Application (Form 21P-530)~~"
2. "Benefit applications" Sketch project  
    1. "~~10-10CG~~" (comprehensive assistance for family caregivers)

### Notes for migration

1. Approach to pointing people from Sketch to Figma: [VA Online Scheduling Sketch file example](https://sketch.com/s/0c37532e-f1a4-4f96-9c28-975c896192a1)

**Comment by mengA6** [comment]
One outstanding question [per slack](https://dsva.slack.com/archives/C053UDWMH7U/p1704472166438529?thread_ts=1704472160.424229&cid=C053UDWMH7U)
