### ISSUE TITLE
SC | Review ITF messaging

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#72779]
## Value Statement
**_As a_** Veteran
**_I want to_** have a link to the Intent to File (ITF) form (and online form once released)
**_So that_** I don't get blocked from submitting a Supplemental Claim if the automatic ITF fails

## Background Context

We continue to see Sentry errors related to ITF creation errors. Our ITF error message does provide a path for the Veteran with information about filling out the paper form; but it might be better to include a link to the [ITF form page](https://staging.va.gov/find-forms/about-form-21-0966/) with a button to download the form. In the future, this page will also include a link to the stand-alone ITF form.

<img width="699" alt="Intent to File creation error message telling the Veteran that something went wrong on our end and to either call the VBA help line or fill out the paper form" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/abbdcb10-4a00-40e6-b3c4-de3ff8807b96">

## Acceptance Criteria

- [ ] Evaluate ITF alert content
- [ ] Update design
- [ ] Implement (if needed)

## Tasks
- [ ] Update content/design with link
- [ ] Determine if the link should go to the about form page or to the online form (once released)
- [ ] Update content source of truth

## Definition of Ready 
- [x] Nature of the issue defined

## Definition of Done
- [ ] Assign ticket to developers to implement
- [ ] Changes (if any) implemented

**Comment by eileen-coforma** [comment]
526 team is doing a different treatment for their ITF error. Instead of blocking Veterans from applying, they say that the ITF couldn't be retrieved, but their date would at least be saved for the day the application was accessed/started. I'm not sure about the functionality or business decision behind this, and how it differs from Supp Claims.

Would want to ask if making this change would be a desire from our business stakeholders before moving on this.
