### ISSUE TITLE
Announce Feedback via Slack in ToT

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#72781]
## Purpose
Let's announce the new path and publicize in the appropriate channels.  Let's also update the Confluence documentation and Platform docs to reflect the changes.

*note: be sure to speak to the "flexibility" of the phrasing/words

Order of operations will matter, as the capability [isn't truly available](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2875392272/Testing+of+Slash+Command+launch+of+Feedback+Portal#Learnings%3A) until users encounter the shared link in Slack.

## Tasks
- [x] Prep ToT slide
- [x] Announce in ToT (Bryan)

## Acceptance Criteria
- [x] announced in ToT slide
