### ISSUE TITLE
[Discovery] Logged-in homepage: Create product outline

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7278]
## Background

We need a product outline for the logged-in homepage work

## Tasks

- [x] [Create product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/README.md)
- [x] Share with team
- [x] Implement feedback

## Acceptance criteria

- [x] Product outline has been reviewed and approved by team

**Comment by Samara-Strauss** [comment]
First draft is ready and has been circulated for feedback https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/README.md.
