### ISSUE TITLE
[Development] HLR updates

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#7279]
## User Story or Problem Statement

As a frontend dev, I need to update the Higher-Level Review form based on more feedback. And continue to implement minor fixes to the HLR form

## Goal

- Continue to make changes to the HLR form.
- Work on tech debt for this and related forms.

## Objectives or Key Results this is meant to further

Get 'er done.

## Tasks
- [x] Complete updates based on the recent AMO review.
- [x] Make other minor changes that pop up.
- [x] Work on tech debt

## Acceptance Criteria
- [x] HLR form matches the design
- [x] Fix other minor problems

**Comment by Mottie** [comment]
Related PRs:
- [ ] Tech debt (combine all `AddressViewField` components) - https://github.com/department-of-veterans-affairs/vets-website/pull/12054
- [ ] HLR specific updates - WIP
