### ISSUE TITLE
Landing page version for LOA1 accounts

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#72802]
### User story

As a Veteran with a non-identity-proofed account (LOA1 or equivalent), I want to be informed on the landing page of the need for a LOA3 or equivalent account, so that I get a clear understanding of what I can do to get access to the health tools I expect.

### Notes

- Veterans without LOA3 accounts are currently getting the "not registered at a facility" message on the landing page.
- [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1704221289781069) with 7 Veteran verbatims on the issue, with discussion
- Design hypothesis from Patrick (in thread): function/look much like what user sees when they are not LOA3 / identity proofed and trying to access authenticated tools

### Veteran qualitative feedback verbatims
These comments were entered in an open text field under the question `What task were you trying to do today?`

- I was trying to order CPAP supplies online and I am told though I am a 60% disabled veteran and have an account on this site I don't have authorized access to My Healthvet or access to order my CPAP supplies online. or anything through this website.
- I Login directly to Myhealthevet and have been using it for years as a Premium account. Your various messages suggest I use "[login.gov](http://login.gov/)" to get into Myhealthevet. When I try that and log in I get a message stating I am not qualified to use "Myhealthevet". What gives?
- Go on MyHealtheVet. I have used it for years and now you tell me I'm not registered???
- I set up a username and password to [login.gov](http://login.gov/) successfully. Now when I click on the link for MyHealthyvet on [Login.gov](http://login.gov/) it tells me I do not have access.  I can login to Myhealthyvet as before with no problem and see my appointments but not through [Login.gov](http://login.gov/)
- tried to create a [login.gov](http://login.gov/) account for future My HealtheVet use on [va.gov](http://va.gov/)...got a prompt that I was not enrolled in va health care, I've been enrolled since 2012
- your web site won't let me access my healtheVet AFTER I AM VERIFIED BY [ID.ME](http://id.me/). THE SITE RECOGNIZES MY AUTHENICATION BUT TELLS ME I CAN'T HAVE ACCESS. WHAT A PAIN IN THE ........ FIX THIS PLEASE
- this site has me verified by I'[d.me](http://d.me/) and it won't let me into my HealthVet, again and again and again.... Fix this please!!!!!!!!!!!!!

### Screenshots

<details><summary>Scenario as reproduced by Patrick on Prod</summary>

1. Imagine that you are a Veteran who has used VAgov to log into MHV many times before without a problem. You log into VAgov.
2. Today, VAgov suggests you create a Login.gov account.
3. Go to login.gov to create account, do that. (You have a LOA1 acct by default, though, and Login.gov ***does not suggest*** you verify your identity to upgrade it to LOA3.)
4. Log into VA.gov using new LOA1 account
5. Land on My VA – notice alert that is easily ignored
<img width="382" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/39713c5d-30ce-4fe8-bebb-3655c8d4aeaf">

6. Navigate to My HealtheVet without doing the suggested verification step
7. See that you're being told "You don't have access to My HealtheVet."
<img width="384" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/cd5bacbe-6f05-4ac1-874c-324a8a0261d1">

</details>

Recommendation from planning: implement My VA version asap. Light lift.

## Acceptance criteria

- Users with a non-identity-proofed account get a dedicated landing page experience

## Tasks

- [ ] Study qualitative feedback from an engineering perspective to identify any other possible issues going on
- [ ] Tried to locate one of the more ambiguous session replays in Datadog to see if it's useful in this context
- [ ] Consider shared component with My VA so content stays in sync
- [x] QA: create test cases in TestRail
- [x] QA: confirm deployment to stage
- [ ] QA: test feature/report bugs
- [ ] QA: Regression test (if bugs found/fixed)

**Comment by dcloud** [comment]
We had some discussion about _shared components_ on the secondary nav ticket, department-of-veterans-affairs/va.gov-team/issues/72499#issuecomment-1875685681

**Comment by dcloud** [comment]
Noting that there are multiple `IdentityNotVerified` components:

```
src/applications/disability-benefits/view-payments/components/IdentityNotVerified.jsx
src/applications/personalization/components/IdentityNotVerified.jsx
src/applications/vre/28-1900/components/IdentityNotVerified.jsx
```

I think the `src/applications/personalization/components/IdentityNotVerified.jsx` version is the one to make shared. It was updated in Feb 2023 whereas the other two were updated in Jan 2022, and the personalization version is already on the path to reusability.

**Comment by dcloud** [comment]
Here's a quick version of what it might look like to re-use the existing personalization component:

![Screen Shot showing an "identity not verified" alert on MHV Landing page](https://github.com/department-of-veterans-affairs/va.gov-team/assets/279327/1707daa5-2738-47bb-b5b1-b990181741fe)

I placed it below the "Welcome, Person" message but above the cards with the links, but that was just my first instinct.

**Comment by dcloud** [comment]
@fmccaf1 Here is an updated version that mentions the service name in the alert heading:

![Screen Shot 2024-01-08 at 13 13 19](https://github.com/department-of-veterans-affairs/va.gov-team/assets/279327/6f03e254-968d-499f-b6e4-8a6a21d9a462)

Currently, that heading is customizable, but [other text in the component](https://github.com/department-of-veterans-affairs/vets-website/blob/70c8a8a4d416cdd498a8cf6390b8576b84d2dafe/src/platform/user/authorization/components/IdentityNotVerified.jsx) is not.

Happy to iterate on this further!

**Comment by fmccaf1** [comment]
I like that alot! Thanks for sending this. I'm working on a mock-up now with different language.

**Comment by fmccaf1** [comment]
The link "learn how to verify your identity on VA.gov has this content at the top of the screen (not ideal at all):

<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3F4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87f97b93ea185de66cd74f5ec4cc5afa59f4aff5/image.png" alt="image.png" />


Image text reads: "If you have a Premium My HealtheVet or Premium DS Logon account, you have already verified your identity when you got your Premium account. You can use your exisiting account to sign into VA.gov to manage many of your benefits and services."

**Comment by fmccaf1** [comment]
The link "learn how to verify your identity on VA.gov has this content at the top of the screen (not ideal at all):

<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3F4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87f97b93ea185de66cd74f5ec4cc5afa59f4aff5/image.png" alt="image.png" />


Image text reads: "If you have a Premium My HealtheVet or Premium DS Logon account, you have already verified your identity when you got your Premium account. You can use your exisiting account to sign into VA.gov to manage many of your benefits and services."

**Comment by wesrowe** [comment]
@fmccaf1, the images won't render for me. Could you try re-pasting above? And maybe post the link you followed too?

**Comment by fmccaf1** [comment]
Okay, here is a stab at content. Unfortunately the alert component (the one with the green stripe and gray background) does not allow for any kind of dropdown or really any interactive element besides links to other pages. I tried to work with this DS regulation by adding the "additional info" component right underneath the alert, and using that as a space to address the issue we've been receiving user feedback about (VA.gov told me to get an ID.me or login.gov account and now I can't access my health tools). This design requires that we know whether the user account is ID.me or Login.gov to correctly display the alert header. I also removed the link under the alert in the original design because I noticed the content on the page the link points to is incorrect throughout.  

<img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDZ4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e199a90de502c566d096384b46b5fd4466245bb/Verify%20id%201.png" alt="Verify id 1.png" />

<img width="579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHV4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84017cf2648a27b473bcf7b5da48a2e6c7c284ca/Verify%20id%201a.png" alt="Verify id 1a.png" />

<img width="164" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCt4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--151cb00725bfe4ca4519c8e68419dd2e70cf821a/Verify%20id%20mobile.png" alt="Verify id mobile.png" />

**Comment by fmccaf1** [comment]
Text copied and pasted here:

For alert header: Verify your identity to use your ______ ~~login~~~ account on My HealtheVet

For alert <p>: Before we can give you access to your personal and health-related information, we need to verify your identity for this account. This helps to keep your information safe, and to prevent fraud and identity theft.

For additional info dropdown text: Having trouble verifying your identity?
Hidden text (within dropdown): If you have a My HealtheVet account, you can access My HealtheVet tools now by logging out and logging back in using your My HealtheVet login credentials. 

However, all My HealtheVet accounts will soon be discontinued so it is important that you complete all steps to set up an ID.me or login.gov account as soon as possible.  

Get help:
Go to the Login.gov help center (https://login.gov/help/)
Visit the ID.me support section (https://help.id.me/hc/en-us?_ga=2.57940392.365484499.1704728177-1563880044.1683821547)

Let me know if there are any questions!

**Comment by dcloud** [comment]
Since was initial idea "let's use what the personalization team created", do we intend to update the design/content for all VA.gov or do our own thing?

**Comment by fmccaf1** [comment]
@wesrowe I'm curious if you have any thoughts to share here. What I thought I was hearing was that this alert was not sufficient to address the issues our users were having (getting a new login and then unable to access MHV) so I tried to create copy that would help them with that. If I'm off in terms of the goal, let me know.

**Comment by wesrowe** [comment]
interesting questions. we definitely want to create an alert that works for MHV landing page users. it seems like the improvements within that component (as opposed to the more-info component below it) would be useful elsewhere like My VA. but I wouldn't make My VA's approval a requirement for our design.

that said, we should socialize it with MyVA when we're ready. they care about consistency and would probably want to adopt improvements.

**Comment by wesrowe** [comment]
>However, all My HealtheVet accounts will soon be discontinued so it is important that you complete all steps to set up an ID.me or login.gov account as soon as possible.  

@fmccaf1, I would suggest cutting this out, now that I'm seeing it in the UX. (I realize I might have indicated this might be a good idea in a previous meeting.) there are other places that this info will be communicated, I wouldn't want to create source of truth that would have to be kept accurate as things evolve.

**Comment by fmccaf1** [comment]
I will go with whatever you think is best @wesrowe but just adding my two cents: it seems like if we're telling users they can just revert back to using their MHV login, it seems like we're creating a problem for the future if we don't also let them know that this option will go away soon. I think that's a problem made worse by some MHV users trying to only use the portal and avoid VA.gov; if something else is posted in the future will they see it in time? But what you're saying makes sense and I'll leave this to your decision

**Comment by jonathanjnelson** [comment]
This is what I learned from conversation with Laura Willwerth (from the Content team): 

- A dedicated comms workgroup is coordinating and approving all content about the requirement to switch to Login.gov or ID.me  — there’s a new channel to track that work #secure-sign-in-transition
- That requirement isn’t public yet — pages currently say we encourage those accounts, but don’t yet talk about that upcoming change (like this page)
- Veterans will soon be getting these prompts (I am not sure when) and where in the Veterans experience), but all such prompts need to go through that comms approval process

There are currently 2 types of prompts when a user tries to access a feature with an unverified account.

For features like the health tools that still accept “premium” DS Logon or MHV accounts, users get a more general “verify your identity” prompt. Something like this (not sure this is the most common or recent version)

<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODYyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a17d23c6705950e2d14d8b279647ca1250a4273f/Screen%20Shot%202023-12-12%20at%202.14.21%20PM.png" alt="Screen Shot 2023-12-12 at 2.14.21 PM.png" />

Laura’s understanding is that if a user is signed in a with a “basic” MHV account, they’ll be shown options to verify with ID.me or Login.gov after they click “Verify your identity” (But the health tools still accept “Premium” MHV accounts and will do so for the next yearish)
For features that already explicitly require ID.me or Login.gov (maybe only direct deposit?), users see a prompt like this

<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUMyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc0c1b2d219826dd7ae9b4b32b3ff32f6af47b46/Screenshot%202023-10-26%20at%2010.42.19.png" alt="Screenshot 2023-10-26 at 10.42.19.png" />

**Comment by dcloud** [comment]
Going to make that "post-alert link" an optional override so My VA can keep the link

**Comment by dcloud** [comment]
Given the churn over post-alert content, I am going to update my PR to remove that post-alert content for now so we can being showing the relevant alert sooner rather than later. We can follow up with the post-alert content.

**Comment by dcloud** [comment]
We will need an additional ticket for follow-up on post-alert content

**Comment by wesrowe** [comment]
Tested with my personal LOA1 ID.me acct and got the desired result. 
<img width="342" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/21865e63-1262-4d79-893a-abad770e00af">

@dcloud, are you tracking what kinds of accounts you've QAed it with?

**Comment by wesrowe** [comment]
QA test cases we verified ([see Slack)](https://dsva.slack.com/archives/C0581MN69TJ/p1706031455893929?thread_ts=1705951194.295169&cid=C0581MN69TJ):

ID.me
- personal LOA1 acct (above)
- Staging user with LOA3: full access to landing page
- Staging user with LOA1: no-registration alert

Login.gov
- unverified: sees new Verify alert
- verified but no registration: saw no-reg alert

MHV credentials: untested because Staging isn't wired for MHV credentials; can't even reach screen to enter credentials

**Comment by fbonds** [comment]
Added test cases https://dsvavsp.testrail.io/index.php?/suites/view/1883&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

**Comment by wesrowe** [comment]
can this close, @fbonds? I see you added test cases, but did you run them and feel QA is done?

**Comment by fbonds** [comment]
Yes @wesrowe.  Verified working.  Please close.
