### ISSUE TITLE
[spike] SC | Evaluate cause of ITF creation failure

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#72813]
## Value Statement
**_As a_** Veteran
**_I want to_** know why my ITF creation failed
**_So that_** if I am missing a information, I know that I'll need to call the help desk instead of trying to fill out a PDF

## Outcome, Success Measure, KPI(S), and Tracking Link
- [ ] Reduced number of [`itf_creation_failed` errors in Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?environment=production&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+message%3A%22itf_creation_failed%2A%22&sort=-message&statsPeriod=90d&widths=-1)

## Acceptance Criteria

- [x] Evaluate ITF creation errors (time boxed to 2-3 hours)
- [x] Work with 526 team (owners of code) => Got context from Jerek, but will work with this team as a part of #77455 
- [ ] Determine if more specific error messages can be returned as the cause of the creation failure

## Open questions
- Add here

## Tasks
- [ ] Time box discovery (talk to LH and 526 team)
- [ ] Check in DataDog to see what kinds of http errors we get, and which of those, if any, warrant follow-up
- [ ] Check if there's a RUM recording for this error (to see whether it's transient)
- [ ] Determine cause of ITF creation failures
- [ ] Determine if return error messages can be improved

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
> It looks like we're getting ITF POST calls from both the [introduction page](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?environment=production&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2Fintroduction+message%3A%22itf_creation_failed%2A%22&sort=-message&statsPeriod=90d&widths=-1) and veteran-information page (linked in description above) — is this intended behavior?

An ITF call is made whenever the Veteran returns to the form at whatever step they previously saved it. So yes, this behavior is intended.

**Comment by anniebtran** [comment]
[Link to Slack thread in #benefits_engineering](https://dsva.slack.com/archives/C053U7BUT27/p1708964146907499) to see who might know what we can do to debug what's happening. Will start a follow up thread with Lighthouse if needed

**Comment by saderagsdale** [comment]
Open questions:

- Is this error blocking submission?
- Are SCs getting submitted without ITFs? (potentially causing confusion for Veterans)

**Comment by data-doge** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/58841 is possibly a duplicate of this ticket.

**Comment by saderagsdale** [comment]
Got some context from Jerek, will figure out what (if any) questions to ask LH next.

**Comment by anniebtran** [comment]
Screenshot of the error that veterans see when they run into an ITF creation failure:
<img width="473" alt="Screenshot 2024-02-28 at 11 02 48 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/92147fe8-3281-435e-8b67-c75b12210b5f">

Did some digging with Eugene on why we might get a 403 from our controller and it seems we're authorizing using the [restrictions we had set up for using EVSS](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/intent_to_files_controller.rb#L13) but maybe no longer need after [migrating to the Lighthouse endpoint for ITF](https://dsva.slack.com/archives/C1VBAHWQL/p1678291501111909?thread_ts=1678226265.946689&cid=C1VBAHWQL)

TODO:
- Confirm we're using Lighthouse's endpoint for ITF
  - If we are, remove / set up a different policy check for Supplemental Claims ITFs (create new ticket for this dev work)
- Confirm if 401s are being handled properly
- Confirm that 50* errors coincide with some possible downstream timeouts

**Comment by anniebtran** [comment]
@data-doge I think we're pretty much ready to close this ticket, but wanted to check on the last AC item in the description `Determine if more specific error messages can be returned as the cause of the creation failure`

The most common errors we're seeing from our endpoint:
  - 401s => The user is redirected to login
  - 500s => The current error message (screenshot in comment below) could possibly instruct the veteran to try again later, but in my most recent comment, I noticed that we might(?) be re-characterizing 404s from the LH API call as 500s. I know 404s are expected for the `GET` request but not sure what a 404 means for the `POST` request
  - 403s => Should get resolved by follow-up ticket

**Comment by anniebtran** [comment]
Thread started with Lighthouse in their [api-benefits-claims](https://dsva.slack.com/archives/CE6UEJ6BZ/p1709587854348959) slack channel to clarify what the 404/401 error codes mean from this endpoint and ask about the 401s being characterized as 500s because of an error occurring somewhere in the middle of their code

**Comment by anniebtran** [comment]
Re: the LH 401 => 500 recharacterization — Lighthouse said the error wasn't coming from their service (see thread linked above for messages)

Adding a [link](http://sentry.vfs.va.gov/organizations/vsp/issues/223355/events/5e8d9a05549946919ab38f96689369a6/) to a Sentry error that seems to be related, along with its [trace](https://vagov.ddog-gov.com/logs?query=trace_id%3A1966682152789357925%20&cols=host%2Cservice&fromUser=true&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1709584532373&to_ts=1709586552520&live=false) from DataDog — based on Sentry, it does seem like the error is coming from their service, so I've sent these traces to the Lighthouse team to see if they can help us assess what our next steps should be

**Comment by HeatherWidmont** [comment]
@anniebtran to reach out to LH about a fix

**Comment by anniebtran** [comment]
Sade started a [thread](https://dsva.slack.com/archives/C05FCEH2NRG/p1709842241310979) about the recharacterized 401 => 500 errors. Seems like the timeouts appear in large clusters during LH maintenance/downtimes, so might need to figure out how to surface that to the user on the frontend

Chatted with Thomas Blackwell about the 403 errors / what to do to handle them (e.g. #77455) and he's going to see if I can chat with Sam Stuckey next week when he's got more time.

**Comment by HeatherWidmont** [comment]
@anniebtran to reach out to Sam Stuckey

**Comment by anniebtran** [comment]
Some [more discussion](https://dsva.slack.com/archives/C05FCEH2NRG/p1709914875999389?thread_ts=1709842241.310979&cid=C05FCEH2NRG) about the timeout errors. Seems to be a pattern of timeouts during [Lighthouse Maintenance windows](https://dsva.slack.com/files/USLACKBOT/F06NAQLUT6C/va_apis_maintenance_-_va_systems_scheduled_maintenance_-_3_march_2024) (emails are posted in `#benefits-disability` slack channel) and `vets-api` deploys. Not sure how to integrate those maintenance windows into our downtime messaging (or if we even can), so might want to create a spike ticket to investigate that or other approaches to letting veterans know that LH as a downstream system is undergoing maintenance

**Comment by saderagsdale** [comment]
- Sade is looking into whether or not someone from VA.gov triages and manages maintenance windows.

**Comment by anniebtran** [comment]
There's one linked above: https://github.com/department-of-veterans-affairs/va.gov-team/issues/77455

And then I just created this one to cover the LH maintenance window work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/78441

**Comment by anniebtran** [comment]
Gonna close this in favor of those other tickets above that isolate the work that needs to be done for resolving these errors
