### ISSUE TITLE
[MVP] Planning to re-launch static content pages for percentage release

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72812]
## Issue Description

- For the initial January re-relaunch, let's re-release the page with the widget on the "How to apply?" only, until we re-release to 100% of users.
- Related to CAIA intake request: Request to coordinate timing & reactivate pension/how-to-apply/ page from Pension Benefits Team #73034

---
## Tasks

- [x] **Katherine -** Coordinate copy changes with VA stakeholders for the "How to Apply" page that will be released to production to % of traffic released during Canary testing on production. [See release planning schedule here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?sender=u9d01ee38af217e4877e75660). 
- [x] **Vicky -** CAIA intake request made: Request to coordinate timing & reactivate pension/how-to-apply/ page from Pension Benefits Team #73034
- [x] Hold meeting between with CAIA and engineering to coordinate copy changes according to timeline
-- Ask an engineer how they revert static content back; we will need to revert back to only a percentage of users we determine
-- Pension engineer would need to revert the How to Apply page to the former state
-- Engineer will need to write the code without publishing it right away (this has to be at a specific time); Is this new code? If new code, CAIA/Katherine will put the code in.
-- **Someone else from CAIA (not Katherine/perhaps Chelsea) will need to hit publish in the CMS to reactivate this code. Let's give her timeline expectations to make sure she is available on time.**

**Comment by katherine-fung** [comment]
Hi @vbellissimo, you'll need to open a CAIA intake ticket to request this work. [Example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69856)

**Comment by katherine-fung** [comment]
Hey @Midge-dev, here's the final copy for the widget content: 

https://docs.google.com/document/d/1auRNdpxhXHJbpS5fkQbWnaMQsBqgW7WpDRvuazb8rjo/edit 

FYI @vbellissimo Sean let @megzehn and I know that he plans to use the existing widget code that already lives on the "How to apply" page, and incorporate the copy changes for the state that shows the online form/"activated" state. If this is successful, @megzehn doesn't have to re-publish the page. Sean will control which content shows to how many people through the flipper. cc @strelichl for awareness.

**Comment by vbellissimo** [comment]
@katherine-fung I see... Good to know. Thank you!
