### ISSUE TITLE
[CST] Fix 404 upload issues

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#72823]
## Background
There have a been a number of 404s occurring with document uploads, which seems odd because most users should be uploading from the claim details page and if they are able to get to the file uploader, then they should be viewing the details for one of their claims. We should investigate this to make sure there isn't anything strange going on. 

We're seeing an average of X 404s come in per month since August....

## Value Proposition
* Our current DataDog monitors are set to consider any non 20X or 422 responses as errors and it appears that 404s are the main "error" status that is happening.
* The document uploads controller sees fairly low traffic, so even a couple of 404s in a short amount of time will trigger the monitor, which is something we should be looking to avoid

#### Prerequisites
* You will need to be able to make modifications to your Postgres DB
  * The steps below will assume that you are using `psql`
* You will need to make sure that the `benefits_documents_use_lighthouse` feature toggle is **disabled** and that the `cst_use_lighthouse_show` and `cst_use_lighthouse_index` feature toggles are **enabled**

1) Log in to the claim status tool and navigate to `http://localhost:3001/track-claims/your-claims`
2) After the page finishes loading, you should see a list of claims (The heading will be something along the lines of 'Claim for X')
3) Choose one of the claims in the list and click the 'View details' button
<img width="400" alt="Screenshot 2024-01-19 at 10 06 28 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/29b1dc44-93e5-46a6-923a-5b328d5fbc71">

4) This will take you to the details page for the claim you selected
<img width="400" alt="Screenshot 2024-01-19 at 10 08 33 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/5c0df361-4f1f-4041-92fd-71e174192da4">

5) Next, you will need to open a terminal and follow the commands below (lines that require input will start with $)
```bash
$ psql
psql (14.9 (Homebrew), server 14.10)
Type "help" for help.

# NOTE: user will be your username
$ user=# \c vets-api
psql (14.9 (Homebrew), server 14.10)
You are now connected to database "vets-api" as user "user".

# See how many evss_claims rows currently exist
$ vets-api=# SELECT count(*) FROM evss_claims;
 count
-------
   395
(1 row)

# If the first number (in this case 395) is anything besides 0,
# run the following to delete all rows from the table:
$ vets-api=# DELETE FROM evss_claims;
DELETE 395

# See how many evss_claims rows exist now
$ vets-api=# SELECT count(*) FROM evss_claims;
 count
-------
   0
(1 row)
```

6) Now go back to your browser and refresh the page (we want to make the API call for claim details again)
7) Select the files tab
<img width="400" alt="Screenshot 2024-01-19 at 10 16 24 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/89b6a4b8-72c7-4f25-b250-ed33aafb2e5d">

**NOTE:** For the next part you will want to have Chrome DevTools open to the 'Network' tab
8) You should see a section titled 'Additional Evidence' and a button labeled 'Add Files'

<img width="400" alt="Screenshot 2024-01-19 at 10 24 50 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/6f16f0f4-07cd-4fa8-baaf-e6a4d9e84846">

9) Click the 'Add files' button and select a file from the file picker that appears. (The file must be a PDF, GIF, JPEG, BMP or TXT file)
10) After you select a file, you will see a gray box with a Select labeled `What type of document is this?`. You can select  any of the options
11) After selecting one of the options from the dropdown, make sure to check the checkbox labeled 'The files I uploaded are supporting documents for this claim only.'
12) Next, click the button labeled 'Submit Files for Review'
13) In the Network tab, you should now see an entry (potentially 2) labeled documents. One of them should have red text, indicating an error. If you click on the line and view the 'Headers' tab, you should see that the status code is 404 Not Found

<img width="400" alt="Screenshot 2024-01-19 at 10 33 11 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/55666f2e-c7d6-4f19-b8da-525266f2382d">

## Tasks
- [x] Determine if this is related to something with the code, or the result of user error
- [x] If this is the result of user error, determine if we should not consider 404s to be errors for the purposes of monitoring

## Acceptance Criteria

- [x] Users no longer get an error message associated with 404 upload errors because those errors have been corrected.

**Comment by jacobworrell** [comment]
@jerekshoe consider adding steps to reproduce for testing purposes.
