### ISSUE TITLE
[Tech Debt] Fix unauthenticated e2e test for /my-health path

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#72838]
Cypress test for an unauthenticated user fails in CI. We need to investigate and refactor this test.

### Notes
- `src/applications/mhv-landing-page/tests/e2e/mhv-auth-redirect.cypress.spec.js`
- Relevant [example test failure](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/7389922325/job/20105644354):
> prompts user to authenticate, redirecting to my-health (failed)

- Also: [Mochawesome report for a failed test](https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/vets-website-cypress-reports/b002c5ad-8bff-4832-baab-94ad50106e94.html)
- 

## Acceptance criteria

- Assessed whether this test is necessary
- Rewrote test if deemed appropriate

## Tasks

- [ ] verify that we don't need to redirect certain users away from our page any more
- [ ] grok what the test is trying to catch
- [ ] try rewriting test
- [ ]

**Comment by radavis** [comment]
Ensure there is test coverage for 1) an unauthenticated user, 2) a user with no facilities (no health data). Question: Is there test coverage for the redirect, or can we remove the redirect?

**Comment by radavis** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv-landing-page/containers/App.jsx#L76

We used to redirect if the user didn't have health data or the app was not enabled. Since we are operating in production and no longer redirect users without health data, we can remove the redirect.

**Comment by radavis** [comment]
> https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv-landing-page/containers/App.jsx#L76
> 
> We used to redirect if the user didn't have health data or the app was not enabled. Since we are operating in production and no longer redirect users without health data, we can remove the redirect.

Split off ask into new ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/76200
