### ISSUE TITLE
[UX, FE] 10-10EZR - BUG: Blank Preferred Facility in ES causing submission failures for EZR

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72849]
## Background
There was a user who's submission failed twice due to not having a Preferred Facility on file in ES.
The problem is when an enrolled Veteran does not have a Preferred Facility on file in ES, and we dont ask for one on the form, the submission fails.  To prevent this, we want to check for the Pref Facility before they start the form and if empty, present them with an alert stating that they cant fill it out since they are missing the facility and their options are to call or complete the PDF.

#### Additional Context
>The 2 new errors from today were from the same user who happens to be enrolled but does not have a Preferred Facility on >file.  Since that section was not part of the paper form, we are not asking the question online.
>However, the EZ API we are using does require that value. Not having that value for a Veteran missing the facility causes a >submission failure.  Joshua F has indicated that this is a rare occurrence for an enrolled Veteran. 

## Tasks
- [x] UX - Create an alert/notification design component for the Introduction page that informs the Veteran of the missing info, and their options to complete the EZR form via PDF download (take to facility or mail in) or call HEC staff.
- [x] UX - Add any relevant error copy to error matrix (content did not convert well from Sketch to Figma)
- [x] UX - Add to error matrix
- [x] FE - Implement alert/notification component based on preferred facility data in Enrollment API
- [x] Add GA event to alert for tracking
- [x] Inform PM for engaging Analytics team on GA event
- [ ] Complete testing and validation

## Acceptance Criteria
- Specific alert will display for Veterans without Pref Facility in ES, providing them alternatives to complete the form via phone or PDF (mail or take in).

**Comment by katelyncai** [comment]
Synced with Aliyah really quick at the end of her day to update her on this bug and our content request. I introduced the problem and shared [Figma designs](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=679%3A3884&mode=design&t=JvDcvdFaRqxxe1RZ-1) with her.

We're both leaning toward keeping this content generic and providing options (updates by phone or by mail) for any Veterans this applies to. And we would like to revisit this with a longer term solution for EZR v2.

Aliyah plans to get back to us with suggested content tomorrow.

**Comment by longmd** [comment]
@hdjustice , the name of the GA event for this alert will be `ezr-missing-preferred-facility`.

**Comment by katelyncai** [comment]
@longmd Link in the new alert ("Learn more about how to update your health benefits information") to take users to the static page (https://www.va.gov/health-care/update-health-information/) dropping them on the "Option 1: By phone" H3.
<img width="1318" alt="Screenshot 2024-01-08 at 8 47 12 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8942468/bc088b35-3089-4a7d-b8a1-87f6cecbccb8">

**Comment by longmd** [comment]
@hdjustice , good to go with users who can complete the form. No adverse effects there. 

![screencapture-staging-va-gov-my-health-update-benefits-information-form-10-10ezr-introduction-2024-01-08-16_23_33](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/4c2cc7a2-5bbb-46f1-85b7-b27343d395fe)

**Comment by longmd** [comment]
@hdjustice , good to go with users that do not have the preferred facility data.

![screencapture-staging-va-gov-my-health-update-benefits-information-form-10-10ezr-introduction-2024-01-09-11_43_20](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/519b3d4e-0ab5-463b-be48-444aba41d641)

**Comment by hdjustice** [comment]
I also confirmed this alert is working as expected.  Great work everyone!
