### ISSUE TITLE
Toxic Exposure validation/error screens

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#72842]
## Issue Description
Create mocks for the error/validation screens in TE flow

---
## Tasks

- [x] Mock of validation if user selects a location and "none of these locations"
- [x] Mock of validation if user selects a hazard and "none of these"

## Acceptance Criteria

- [x] Mocks for error states and validation states approved in sketch

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kate-allbee** [comment]
Sketch file here: https://www.sketch.com/s/c353146f-eceb-4626-9918-7603c693417f
