### ISSUE TITLE
Copyedit for 2023 audit: Disability landing page

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#72843]
## Issue Description
For the rolling audit of all the pages in the disability hub, OCTO content lead assessed these content issues on the [Standard disability claims](https://www.va.gov/disability/) page and made changes that need copyediting before we republish the page:

- The intro paragraph has no more than 2 to 4 sentences, is within 200 to 400 characters with spaces, and follows our pattern and style for intros (short sentences, paragraph ends with a CTA, etc.). **Note:** I rewrote this.
- Relevant terms from page are in content brief and any relevant backlog work is noted.
- Assess the content in the blue box. **Note:** I moved all content out of the blue box. There's no need for a blue box on this page at all since we don't talk about eligibility.
- Fix any lead-ins to bulleted list so they are complete sentences.
- Rework "What evidence will VA gather..." section.

**Copyeditor will check these in addition to copyediting the above-mentioned edits:**

- Header levels are hierarchical
- The page has no broken links
- Text links have purpose and target
- The content is free of ability-focused language (view, walk, see, hear) Note: We allow "show" and "appear" when talking about evidence related to disability compensation.
- Flesch-Kincaid before and after grade level

---
## Tasks
- [ ] Copyedit the OCTO changes made (review revisions only, not the full page) to https://www.va.gov/disability/
- [ ] Check each item in the 5 bullets above.
- [ ] Request review from Matt Eakman, SME
- [ ] Incorporate his changes in Drupal
- [ ] Add Flesch-Kincaid before and after grade level to Github
- [ ] Add notes from him to the record of audit for this page
- [ ] Publish page

## Acceptance Criteria
- [ ] Updates are live on the site

**Comment by megzehn** [comment]
Update: We sent this over to Matt and published the PL changes. The next steps are to make sure that all this is recorded in our github audit files.

**Comment by megzehn** [comment]
The information is recorded in the github audit files. We can close this.
