### ISSUE TITLE
[Content] Update SMS Notifications for check in to address Veterans not being present after checking in online

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72851]
## Description 

We don't want Veterans to wait until their appointment time to talk to staff. We want them to talk to staff in three different scenarios:
- If you weren't in the waiting room when you completed check-in, because staff may have already call you back
- If you wait more than 15 minutes
- If you haven't been called back by your scheduled appointment time.

How can we address this in the SMS notifications for check in? 

## Tasks

- [ ] Create the content ([variations were started in Figma](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=99%3A2207&mode=design&t=Xg7jhpRw0oBYBEwR-1)). Will need 2 versions: 45MR and text "check in" methods. (See [userflow in Figma](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=14%3A6233&mode=design&t=eoo9iGjetSbjUgvD-1).) 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
@loripusey Added this ticket as an additional change, if we want to pursue it, cc @kellysmith1008

**Comment by kellysmith1008** [comment]
After some discussion in slack and figma, we landed on:
Let us know when you arrived at http://www.va.gov/c/r4Jhnma. 
If you have trouble with check-in, ask a staff member at your VA health facility for help.

@benbrasso-agile6 Good to close?

**Comment by benbrasso-agile6** [comment]
Yep, I added it into the Design Spec page in Figma. TY
