### ISSUE TITLE
[Design] [Content] Create Final Wireframes with content for ID Verification page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72853]
## Description 

We don't want Veterans to wait until their appointment time to talk to staff. We want them to talk to staff in three different scenarios:

- If you weren't in the waiting room when you completed check-in, because staff may have already call you back
- If you wait more than 15 minutes
- If you haven't been called back by your scheduled appointment time.

How can we address this in the ID Verification page? 

Note: Updates will utilize content that has been approved by CAIA within Unified Check In. E.g., changing the h1 and the first body sentence. 

## Tasks
- [ ] Create final wireframes with content ([started in Figma](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=139%3A1285&mode=design&t=5Du9vlDZ0miXmUEw-1)) 
- [ ] Create any needed markup into Sketch Page(s) for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
FYI, @loripusey added this one too as an option to pursue later

**Comment by loripusey** [comment]
I'm confused, why do we want to add this to the ID verification page?

**Comment by kellysmith1008** [comment]
It was a proposal when working in #72247 to alert the Veteran *before* completing the check in workflow that they need to be at the facility when starting check in. Gives them a little closer window to get into the building and in the waiting room before the MSA calls them back. Might prevent them from checking in before they arrive at the facility, whereas the content being crafted in the above ticket only appears to them after they've checked in.

**Comment by loripusey** [comment]
ah ok; I guess my only concerns is the amount of content we keep adding

**Comment by kellysmith1008** [comment]
Yeah, for sure. I added it as a proposal to maybe look into - we don't have to do it, but might be something to test or consider if we find the content added in the 15-minute message isn't as effective as we hop.

**Comment by benbrasso-agile6** [comment]
I like that approach

**Comment by loripusey** [comment]
We are not doing this right now, closing
