### ISSUE TITLE
DR | Add Datadog logging for validation errors that prevent submission

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#72855]
## Value Statement
**_As a_** developer
**_I want to_** investigate why form submission is blocked
**_So that_** we can fix the issue preventing Veteran's from submitting our form

## Background Context

After working on [#71344](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71344) and finding it difficult to find and evaluate Veterans having similar validation issues, we split out the work into this ticket...

When a Veteran has validation issues after attempting to submit their form, a generic error message is shown, and a "Validation issue not displayed" event is logged in Sentry. This event includes all the validation issues & error messages, but we aren't able to see this in Datadog. So we need to add logs specific for Datadog so we can see & cross-reference the problem within our dashboard ([reference docs](https://www.datadoghq.com/blog/monitor-javascript-console-logs/#log-custom-user-events-with-datadog))

## Acceptance Criteria

- [ ] When a Veteran encounters a validation error and is shown the generic error alert, a Datadog event is logged
- [ ] Datadog dashboards include details for "Validation issue not displayed" events
- [ ] No PHI/PII exposed in Datadog dashboard

## Tasks
- [ ] Investigate Datadog logging
- [ ] Investigate adding Slack notifications for known validation issues (e.g. contact info problems)
- [ ] Add Datadog logging which will include the same data logged to Sentry
- [ ] Ensure no PHI/PII is included in the logs
- [ ] Add tests
- [ ] Test logging in staging

## Definition of Ready 
- [ ] Investigation work is timeboxed to 2 hours
- [x] Logging events discussed with Steve Albers

## Definition of Done
- [x] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [x] Passed integration testing (if applicable)
- [x] Code reviewed (internal)
- [x] Submitted to staging
- [x] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
I'm meeting with another team that has more experience with Datadog logging on 1/12/2024. I also have a plan to meet with Steve Albers about adding [Datadog JavaScript logging](https://www.datadoghq.com/blog/monitor-javascript-console-logs/#log-custom-user-events-with-datadog) to the site &mdash; not sure if it's implemented or needed, but I'll have a better idea after the meeting with the other team.

**Comment by saderagsdale** [comment]
Steve is going to confirm the cost before the work is approved. Blocked for now.

**Comment by Mottie** [comment]
Steve Albers has told me to go ahead and proceed 🎉

**Comment by HeatherWidmont** [comment]
DD team will review his PR to ensure its set up properly & will get back to him (hopefully today). Once its reviewed Robin will take it out of draft, have our team & Platform team review it

**Comment by rubensun** [comment]
Next office hours on Monday.
@Mottie to ping Steve Albers

**Comment by HeatherWidmont** [comment]
@Mottie met with DD team this morning & they pinged another developer to review the PR. Still blocked

**Comment by HeatherWidmont** [comment]
@Mottie emailed helpdesk & they said they will take it to the team & will get back to us. That was on Friday 2/2

**Comment by HeatherWidmont** [comment]
@Mottie added Sade to the email thread, still haven't heard anything back yet

**Comment by HeatherWidmont** [comment]
@Mottie received an email from Fred at DD who reviewed it. Platform & @data-doge to review

**Comment by HeatherWidmont** [comment]
Entire FE is blocked because unit test failures won't pass. They're still trying to figure it out https://dsva.slack.com/archives/C05FCEH2NRG/p1707844087730839. This PR is ready to get merged in
