### ISSUE TITLE
[FE] 10-10EZ - Improvement: Discovery reducing frequency of prefill alert on each page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72871]
## Background
We received some feedback from a VA colleague and Veteran on completing the 10-10EZ form.  Overall, the feedback was positive, but there was an "annoyance" that we can look into.

>Extremely easy form! Took me like 5-7 minutes. Longest thing was me finding my wallet, that has my medical ID in it, so I could get the healthcare info. Other than that, super quick. My only nitpick was that it had text at the start of each page like "this form saves automatically..." or something like that. Each page I would read the paragraph to what was needed and read that same blurb again.. and again.. etc. It was also on the bottom as well. IMHO, not needed and I had to refocus what I actually needed to do each time. Just annoying. That make sense?

## Tasks
- [x] Explore how we can reduce the prefill alert to display at the beginning of each section, rather than every page 
- [x] Determine if the same change can be made to EZR
- [x] Determine the level of effort to implement
- [ ] Discuss when to schedule the implementation

## Acceptance Criteria
- The prefill alert frequency is investigated and a solution to reduce is decided upon.

**Comment by longmd** [comment]
These are manually added in the various form config files where data inputs are available for prefill. All we need to do is identify where the alerts no longer need to live and we can pull those out.

**Comment by hdjustice** [comment]
Let's talk about this in refinement

**Comment by hdjustice** [comment]
Confirming here - we are talking about the prefill alert at the top of the page (not the bottom)

**Comment by hdjustice** [comment]
Need list of pages with this alert, decide which pages to keep.
Jessica will test a couple paths to confirm when the alert displays - there may be a time where it displays on Service History page when there is no data prefilled.

**Comment by hdjustice** [comment]
#75445 created for work to complete this
