### ISSUE TITLE
Direct deposit CTA is categorized as "health tool"

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#7287]
## User Story or Problem Statement
Reviewing the code in vets-website `src/platform/site-wide/cta-widget/helpers.js`, I see that `DIRECT_DEPOSIT` is categorized under the `HEALTH_TOOLS` category.

Assuming that this is the VBA direct deposit feature, I don't think it belongs there. The health tool categorization does impact some checks that gate access to features, like making sure that the user has an MHV account - so that could potentially be an issue for users. 

Looks like the most recent commit that directly updated that categorization (other than alphabetization/other cleanup) was by @tzelei, so tagging him for any additional context, and tagging @ncksllvn for help routing  this to the right team for prioritization. 

If I am wrong and this direct deposit feature does somehow relate to MHV/health tools, then feel free to comment accordingly and close this.

## Goal
Clean(er) code.

---
## Tasks
- [ ] Move DIRECT_DEPOSIT out  of health tools category if it indeed doesn't belong there. 
- [ ] Update the CTA widget to render the direct deposit CTA correctly when it is no longer in the health tools category (e.g. in `platform/site-wide/cta-widget/index.js`)

## Acceptance Criteria
- [ ] Direct deposit CTA should continue to render correctly, but not be subject to any unnecessary health-related checks.

**Comment by ncksllvn** [comment]
Thanks @patrickvinograd!

@Samara-Strauss I added the `vsa-authenticated-exp` label 👍 CC: @erikphansen @bradl3yC

**Comment by patrickvinograd** [comment]
I removed the "tech debt" tag since the categorization does impact accessibility of the tool based on MHV account status, so could be a functional issue.

**Comment by Samara-Strauss** [comment]
Thanks for this! We'll add it to our backlog.

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606

**Comment by patrickvinograd** [comment]
I took a crack at fixing this (because it was tangled up with other changes to the CTA-widget) in https://github.com/department-of-veterans-affairs/vets-website/pull/12624

**Comment by Samara-Strauss** [comment]
@patrickvinograd thanks! When that is complete, please let us know so we can close out this ticket.

**Comment by mshea0606** [comment]
@patrickvinograd is this still an issue?

**Comment by Samara-Strauss** [comment]
@erikphansen what was the conclusion on this?

**Comment by erikphansen** [comment]
via a DM: Patrick thinks that he fixed it when re-jiggering the CTA widget.

**Comment by Samara-Strauss** [comment]
Awesome, thanks for the update!
