### ISSUE TITLE
CH 31 | Skip Wizard For In-Progress Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#72883]
## Issue Description
_Summary issue in CAIA ticket #64692._

### Details
As a Veteran who already has a form in progress, if I navigate to the apply online page, I don't want to see the wizard and need to click through again before finding the alert on the next screen letting me know I can continue an application.

### Staging or Production Link
- [Staging Link](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start)

### Prototype Link
- [Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684161597392/5c1f8869cf5d03b792c8b82cf19b39dc26c486c2?sender=u0e8ac1d6d7681bb7e1b80558)

### Test Users
- vets.gov.user+24@gmail.com
- [staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

### Designs
Entry point designs:
- [How to apply](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=128%3A8585&mode=design&t=p6wBtQbVHexIKh2h-1)
- [Eligibility](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=128%3A9534&mode=design&t=p6wBtQbVHexIKh2h-1)
- [Reemployment](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=128%3A9797&mode=design&t=p6wBtQbVHexIKh2h-1)
- [Rapid access to employment](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=128%3A10066&mode=design&t=p6wBtQbVHexIKh2h-1)
- [Self-employment](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=128%3A10334&mode=design&t=p6wBtQbVHexIKh2h-1)
- [Long-term services](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=128%3A10602&mode=design&t=p6wBtQbVHexIKh2h-1)
- [Independent living](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=128%3A10870&mode=design&t=p6wBtQbVHexIKh2h-1)

---
## Tasks
- [ ] Update How to Apply section
- [ ] Update Eligibility section
- [ ] Update Reemployment section
- [ ] Update Rapid Access to Employment section
- [ ] Update Employment section
- [ ] Update Long-Term Services section
- [ ] Update Independent Living section

## Acceptance Criteria
- [ ] Users with in-progress applications no longer see the wizard component when they visit a form entry page
- [ ] A user who has an in-progress application and is on [this page saved page](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/form-saved), and decides to click on "Start a new application", and click "Yes" in the modal that appears, THEN they see step 1 of the Ch31 form instead of the wizard.
- [ ] @fiorella-io reviews and signs-off on user experience in staging
---

**Comment by fiorella-io** [comment]
@steele-lm Can we also add to the AC that if a user has an in-progress application and is on [this page saved page](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/form-saved), and decides to click on "Start a new application", and click "Yes" in the modal that appears, THEN they see step 1 of the Ch31 form instead of the wizard

**Comment by steele-lm** [comment]
Closing this ticket bc the wizard feature will be removed as part of the overall form updates we are making. cc @fiorella-io
