### ISSUE TITLE
Pre-Usability Review [Profile 2.0 Connected Apps - FAQ and App Directory pages]

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#7290]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)) 
-- [This is in support of Profile 2.0 work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6478)
- Link to or attach prototype or mockups
-- [App directory ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6866)
--[ FAQs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6864)
- Link to or attach artifact with copy (if separate from prototypes/mockups)
-- see tickets above
- Link to research plan ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)) and script ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md))
-- N/A
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from **requesting team**
- Product Manager (required): **Carey Otto**
- DEPO product lead (required): **name**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **names**

## Scheduling
Preferred dates or times: ASAP, trying to get in synch with Profile 2.0 collab cycle

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

FYI- there are still a few minor design things Tressa and I want to work out, as the component she's designed on Profile will be repurposed here. Also need to synch up on UI copy between the 2 screens. Open to feedback on these issues.

**Comment by meganhkelley** [comment]
Scheduled for 3/31

**Comment by pjhill** [comment]
Given that both the App Directory and FAQ are new products, a regression test plan is not required for this effort.  I **would** encourage the team to start thinking about test scenarios that will verify these new apps are functioning correctly and being rendered appropriately across the many platforms that our Veterans use to access the platform.  It appears as though at the moment all we have is a prototype of each, but as soon as user stories and acceptance criteria are available we should begin to reference these user stories from the test cases in TestRail that verify them.

For more information about creating QA artifacts within TestRail please have a look at the documentation available in the [QA platform area](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/testrail).  If you have any questions then please reach out to me on Slack.

**Comment by meganhkelley** [comment]
From @careyotto — 

Design reviewers (@emilywaggoner @CrystabelReiter) : Would love your nerdy design thoughts on the "additional info" app widget in these designs. What's in the mock doesn't feel quite there.

@tressaellen and I want to land on something that will work equally well here and on the connected apps page. Have been exploring swapping out the fonts, aligning copy to the link, sticking with the design library's "additional info" link style, and other small tweaks.

**Comment by CrystabelReiter** [comment]
@careyotto @emilywaggoner I think here we could try sticking with the additional info component. I see that the link varies slightly from the design library's style https://design.va.gov/components/additional-info

Here the component is dark with a blue dotted underline, instead of a blue link. When it opens, a blue line goes along the edge indicating that the information underneath is associated with the link. Perhaps we can align the copy to the link and use the blue bar to indicate the "togetherness." I'd like to see what else ya'll explore though.

**Comment by tressaellen** [comment]
Here's an example of what this would look like with the additional info compenent. I'd love your thoughts @CrystabelReiter @emilywaggoner 

<img width="670" alt="Screen Shot 2020-03-24 at 2 39 30 PM" src="https://user-images.githubusercontent.com/58752772/78056218-38b1f580-7331-11ea-94d9-dacea70c4b30.png">

**Comment by pjhill** [comment]
I have not seen a test plan or test cases related to FAQ or App Directory created in TestRail.  I checked under the VSA-Authd-Exp project in TestRail -- https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc

I also don't see a test plan linked to this ticket anywhere.  Am I missing where the test cases and test plan have been created and linked?

**Comment by mnorthuis** [comment]
@careyotto @mshea0606 
Hi - Wondering if this epic and its resulting feedback issues have been reviewed?  I noticed that its not technically assigned to either of you, but would be up to someone on your team to review and respond to feedback and then close issues. Please let us know if you have any questions!
