### ISSUE TITLE
[dev task] NOD | Create script for the mailing info & email address & file number

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#72921]
## Background Context
Here is my working script for gathering a Veteran's file_number, email, and mailing address, given their ICN:

```
def get_data(icn)
  mpi_service = MPI::Service.new
  mpi_profile = mpi_service.find_profile_by_identifier(identifier: icn, identifier_type: 'ICN')&.profile
  raise 'No mpi profile!' if mpi_profile.nil?

  mpi_address = mpi_profile.address
  raise 'No address in mpi profile!' if mpi_address.nil?
  line_1 = mpi_address.street
  line_2 = mpi_address.street2
  street = line_1
  street += ", #{line_2}" if line_2.present?
  city = mpi_address.city
  postal_code = mpi_address.postal_code
  country = mpi_address.country

  address = "#{street}, #{city} #{postal_code}, #{country}"

  vet360_profile = VAProfile::ContactInformation::Service.get_person(mpi_profile.vet360_id.to_s)&.person
  raise 'No vet360 profile!' if vet360_profile.nil?

  emails = vet360_profile.emails
  current_emails = emails.select { |email| email.effective_end_date.nil? }
  raise 'All emails expired!' if current_emails.length == 0
  email = current_emails.first.email_address

  first_name = mpi_profile.given_names[0]
  middle_name = mpi_profile.given_names[1]
  last_name = mpi_profile.family_name
  suffix = mpi_profile.suffix
  common_name = [first_name, middle_name, last_name, suffix].compact.join(' ')

  bgs_external_key = (common_name.presence || email).first(39)
  bgs_service = BGS::Services.new(external_uid: icn, external_key: bgs_external_key)
  participant_id = mpi_profile.participant_id
  ssn = mpi_profile.ssn
  bgs_person = bgs_service.people.find_person_by_ptcpnt_id(participant_id) || bgs_service.people.find_by_ssn(ssn)
  raise 'No BGS person record found!' unless bgs_person
  file_number = bgs_person[:file_nbr]
  raise 'No file number!' unless file_number
  file_number = file_number.delete('-') if file_number =~ /\A\d{3}-\d{2}-\d{4}\z/

  [icn, file_number, email, address]
end
```

And here is a list of the ICNs for Veterans potentially impacted by the NOD infinite loop bug (i.e. the Veterans that ADG/VA will be sending letters/emails to): [Nod Infinite Loop Bug ICNs.csv](https://github.com/department-of-veterans-affairs/va.gov-team/files/13806305/Nod.Infinite.Loop.Bug.ICNs.csv)

## Acceptance Criteria
- [ ] Script generates a CSV with mailing info, email address, and file number for Veterans affected by infinite loop bug
- [ ] If the script is unable to generate the info, we can manually pull it (check script numbers against original file)

## Tasks
- [ ] Create a draft of the file
- [ ] Test it to confirm it gathers mailing info, email address, and file number
- [ ] Work with Thomas to add the CSV to a secure S3 bucket so it can be accessed through a remote desktop
- [ ] Send to Julie and Cory from enablement team

## Definition of Ready 

- [ ] We know what data we need
- [ ] We know what format to use
- [ ] We have access to the data
- [ ] We have access to the storage locations necessary to share the data

## Definition of Done

- [ ] Data is aligned with the number of affected Veterans
- [ ] Script pulls accurate data for each Veteran
- [ ] Data is approved by enablement team (Corey and Julie)

**Comment by saderagsdale** [comment]
Derek to shadow.

**Comment by HeatherWidmont** [comment]
@anniebtran to add a piece of code to upload the file to S3 then it should be ready for code review. Derek will review

**Comment by HeatherWidmont** [comment]
@anniebtran to check with Thomas about his capacity. If Thomas doesn't have capacity to work on this then @data-doge will review today

**Comment by HeatherWidmont** [comment]
Thomas & Derek reviewed, now we are waiting for Platform to review. @anniebtran will test on staging

**Comment by HeatherWidmont** [comment]
@anniebtran to chat with @data-doge about some (probably) small changes that need to be made to the script

**Comment by anniebtran** [comment]
Sounds like this is off my plate because [Cory found a different way to grab the data they needed](https://dsva.slack.com/archives/C05FCEH2NRG/p1705005122666599?thread_ts=1704997526.930759&cid=C05FCEH2NRG) and tbh it is probably more efficient than running our script given the constraints of the infrastructure we have in place (the console times out pretty quickly and we'd have to either do fairly small batches or find some asynchronous way of executing the code)

@saderagsdale should we close this ticket now?
