### ISSUE TITLE
Yellow Ribbon MVP - Create checklist for stakeholder UAT session

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7292]
## User Story or Problem Statement
As a stakeholder, I need a task checklist so I can appropriately review the Yellow Ribbon participating schools search tool.

## Goal
Help EDU stakeholders "kick the tires" on our YR tool in an organized way to ensure they thoroughly review to relevant functionality and data.
## Tasks
- [ ] Create checklist for Edu stakeholders to use as they go through the Yellow Ribbon tool
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
Adding to sprint 18 (unplanned)

**Comment by andaleliz** [comment]
@jenniferlee-dsva, @MickinSahni  How does [this draft ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/stakeholder-staging-review.md)look to you?  I know we weren't thinking of this as a formal UAT session.

I'm not sure exactly at what point the Drupal YR content page will be updated, so the first section may not be something we ask them to look at.  

Also, here's the list of folks I would've thought were on this list when I created this issue.  Should we now include Janice and Reggie? Anyone else I'm missing? 
- Tammy Hurley
- Matt Self
- Luke Tickner

Ideally I'd like to have them go through this in a ~15 min remote session so we can observe them; it's a nice opportunity to spot any general usability issues.

**Comment by jenniferlee-dsva** [comment]
I'll need to look at the draft later today. But re ppl - yes, I would include Janice and Joseph. (I don't recall a Reggie actually. If he is on Janice's team, I would let Janice represent and add him if she asks for him to be added). 

I'm cc:ing @johnhashimoto for FYSA. John, this tool is in the later stages, near launch. It would be great if you could follow this, so you, @MickinSahni and I can divide/manage all the things in PW. We can discuss at our afternoon sync. Thank you.

**Comment by jenniferlee-dsva** [comment]
@andaleliz - commented on draft ^ via this branch: https://github.com/department-of-veterans-affairs/va.gov-team/pull/7669

**Comment by andaleliz** [comment]
@jenniferlee-dsva Sounds good. Created issues to cover the next leg of work ([scheduling](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7692) and [conducting](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7693) the sessions) when we are ready.
