### ISSUE TITLE
Update Maintenance Window Documentation to Mirror New Process (IRBot)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72938]
## Description 
There is a new process for creating maintenance windows that is more automated. This process has been updated here: https://vfs.atlassian.net/wiki/spaces/PPS/pages/2851275379/Playbook+for+Maintenance+Windows+management+via+IRBot

We need to update our own documentation to ensure it mirrors the new process. 
---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Update this page to reflect the new Maintenance Window process: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Creating-a-Maintenance-Window-in-PagerDuty[hardBreak]
- [ ] Update this page to reflect the new Maintenance Window process: https://vfs.atlassian.net/wiki/spaces/OT/pages/2434433157/Creating+Maintenance+Windows+in+PagerDuty
- [ ] Ensure there are no other documents that need updating related to maintenance windows
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
New IRbot documentation created and presented to team.
