### ISSUE TITLE
Update Daily Support Assignment Bot

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72930]
## Description 
Each day an automation is sent to the #vfs-platform-support channel [here](https://dsva.slack.com/archives/CBU0KDSB1/p1701781722675089) (see screenshot below for example as well).

We want to be sure that the notification is in the proper channel, identify where it is sourced so that we can ensure it isn't just one person who controls it, and ensure support requests specific to certain teams end up in the right place.

---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify where this bot is sourced (i.e. is it a workflow, integration or support bot feature)
- [ ] Move the automation to the DSVA #platform-tech-team-support channel (should not be VFS facing in the #vfs-platform-support channel)
- [ ] Remove Frontend, Backend and DevOps assignments from list
- [ ] Point each other category (Analytics & Insights, Design Systems/Forms Library, Governance Team, and Platform Content Team) to their respective channels 
- [ ] Identify if there is a way to notify that channel when a support request is escalated to them (i.e. need to send to Governance)
- [ ]  (Platform Support) Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] (Platform Support) Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Work no longer relevant. For the items that are irrelevant, they have been put into smaller tickets. Closing!
