### ISSUE TITLE
Migrate Toxic exposure file to Figma

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#72932]
## Issue Description
Migrate Toxic exposure sketch files to figma 

Capturing the comments and decisions in the TE documentation
---
## Tasks

- [x] Migrate the Toxic exposure work to figma

[How to migrate files](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma) 

## Acceptance Criteria

- [x] File moved to Figma
[Figma Link
](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=39%3A75418&mode=design&t=4BbYTt6gCcS5rREQ-1)
- [x] All components/colors/type styles are fixed if broken in migration

Pages to fix in figma:

- [x] Page: WIP TE Mocks 01/2024
- [x] Page: Sprint Review
- [x] Page: TE Mocks - final wireframes for FE
- [x] Page: TE Mocks - Revisions post-research

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
