### ISSUE TITLE
Improve Slack Searchability

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#72950]
## Description 
It is sometimes hard to search for content or previously answered questions in Slack. This ticket will house the task of researching organizational tactics that will make content more findable (i.e. keywords, tagging, etc.)

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify any tactics that exist in Slack to sort/categorize tickets in Slack Channel
- [ ] Schedule a discussion with Tier 1 and Clint to discuss any options that already exist for search ability in Slack and show any research found
- [ ] Identify next steps if any with Clint 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
We will be moving to GH projects, which has a view that is better than what is offered in Slack. Closing.
