### ISSUE TITLE
Update/Replace fhir_client gem

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#72955]
## Summary

[fhir_client](https://github.com/fhir-crucible/fhir_client) is outdated and uses [rest-client](https://github.com/rest-client/rest-client) which is also outdated. These gems prevent other gem upgrades in the [vets-api](https://github.com/department-of-veterans-affairs/vets-api) repo. 

## Tasks
- [x] create a new repo or fork of `fhir_client`
- [x] replace rest-client with [http](https://github.com/httprb/http) gem (also known as `httprb` gem)
- [x] Add new gem via git to `Gemfile`

### New repo

[https://github.com/adhocteam/fhir_client/](https://github.com/adhocteam/fhir_client/)

### Gems that couldn't be upgraded because of fhir_client
- oauth2 (and oauth was preventing faraday upgrade)
- addressable
- http-accept

**Comment by ericboehs** [comment]
Done.
