### ISSUE TITLE
[DDL] Enable DDL to show different claim letters from other tools

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#72958]
## Background Context
All 3 teams that offer the ability to download claim letters are using the same service to determine what docType their applications will show. This prevents us from easily controlling which letter types we want to show in our own tool and forces us to coordinate with the other teams before we are able to add new letter types to the Download Decision Letters application. We should move the docType filtering out of the service and add the list of allowed document types as a parameter to our controller

## Value Proposition
We don't have the ability to control what letters are shown in the Download Decision letter currently. If our team or another teams updates the list currently, then all teams are opted into that change. This prevents us from ensuring that Veterans who use our tool are getting the best experience possible

## Relevant files
**vets-api**
ClaimLetterDownloader (service) - `lib/claim_letters/claim_letter_downloader.rb`
ClaimLettersController (controller) - `app/controllers/v0/claim_letters_controller.rb`

## Considerations
**ClaimLetterDownloader**
#### get_letters
This function is the top-level function called by the service to retrieve the list of letters. We need to update [this function](https://github.com/department-of-veterans-affairs/vets-api/blob/02f606e/lib/claim_letters/claim_letter_downloader.rb#L14-L27) to accept an **optional** array of allowed docTypes
#### Current code
```ruby
def get_letters
  res = nil

  if !Rails.env.development? && !Rails.env.test?
    req = VBMS::Requests::FindDocumentVersionReference.new(file_number)
    res = @client.send_request(req)
  else
    res = ClaimLetterTestData::TEST_DATA
  end

  format_letter_data(res) # Currently, filtering is done here
rescue VBMS::FilenumberDoesNotExist
  []
end
```

**ClaimLettersController**
Update [this function](https://github.com/department-of-veterans-affairs/vets-api/blob/02f606e/app/controllers/v0/claim_letters_controller.rb#L10-L14) to pass in an array of allowed docTypes
#### Current code
```ruby
def index
  docs = service.get_letters

  render json: docs
end
```

## Open questions
- [x] Should we be worried about filtering out based on docTypes when requesting documents by their ID
  * Currently we don't do any filtering based on docType, we only ensure that the document belongs to the Veteran

## Tasks
- [x] Modify `ClaimLetterDownloader` to accept `allowed_doctypes` as a parameter on its initializer
- [x] Update `claim_letter_downloader_spec.rb`
- [x] Modify `ClaimLettersController` to pass `allowed_doctypes` to `ClaimLetterDownloader`
- [x] Modify mobile team's `DecisionLettersController` to pass `allowed_doctypes` to `ClaimLetterDownloader`
- [x] Create new `VirtualAgentClaimLettersController` for Virtual Agent team
- [x] Create `spec/controllers/v0/virtual_agent_claim_letters_controller_spec.rb` RSpec test for new `VirtualAgentClaimLettersController`
- [x] Create new routes:
   - [x] `virtual_agent_claim_letters`
   - [x] `virtual_agent_claim_letters/:document_id`

## Acceptance Criteria
- [x] We are able to control what letters are being shown in the Download Decision Letter application
- [x] When we allow new document types to appear in DDL, it doesn't cause those letters to show in other applications unless we want them to.

**Comment by HeatherWidmont** [comment]
@samcoforma available to pick this up if Jerek needs help or is working on other higher priority work

**Comment by HeatherWidmont** [comment]
@samcoforma reached out to Chatbot & Mobile teams yesterday for coordination. Sam will update Mobile's controller, waiting to hear back from Chatbot team.

**Comment by HeatherWidmont** [comment]
@jerekshoe @samcoforma to discuss in the parking lot today. Will touch base with Karan at Virtual Agent.
