### ISSUE TITLE
Reconfigure Cypress to support babel-defined aliased imports

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#72953]
## Issue Description
Imports defined in `babel.config.json` work just fine in our files, however if those files are imported into Cypress for testing, Cypress cannot resolve those imports. Our linting rules request for developers to use the aliases, and best practices would support that as well. This limitation of Cypress is preventing our developers from being able to do the highest quality work they can and should be adjusted. I've attached an issue from the Cypress repository where someone had the identical issue and how it was resolved using Cypress' own documentation. 

Context: 

Support Thread: https://dsva.slack.com/archives/CBU0KDSB1/p1704392860031819
Cypress Issue referencing issue and solution: https://github.com/cypress-io/cypress/issues/17411
---
## Tasks
- [ ] Evaluate impact of altering the Cypress config to support Babel aliases
- [ ] If possible/practical, implement the changes to the config
- [ ] Announce the new feature once merged to VFS teams and encourage them to convert over their imports to start reducing linting warnings.

## Acceptance Criteria
- [ ] Cypress and our linting expectations line up with each other.
