### ISSUE TITLE
[Development] 526: Explore Secondary Disability Code Usage in Submit Transformer

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7296]
## User Story or Problem Statement
How might we avoid secondary disability claim errors?

This may be related to this older PR https://github.com/department-of-veterans-affairs/vets-website/pull/9893

## Goal
Reduce the number of claims errors related to secondary disabilities.

## Tasks
- [ ] Look at https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/submit-transformer.js and determine if and how the secondary disability data array is being populated
- [ ] Determine whether putting everything into the primary disability array is intentional and whether it is not jiving with the back end processing.

## Acceptance Criteria
- [ ] We fix any issues with how these arrays are handled.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
After looking into this ticket this morning with @Mottie and Chris Valarida, we determined that there intentionally isn't a `newSecondaryDisabilities` array being sent to the back end. This function [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/submit-transformer.js#L323) takes the separate secondary array and combines it with the primary array, but denotes them as secondary by adding this information to the description of the condition. This was done to handle conditions that were secondaries to secondaries, and so on.
