### ISSUE TITLE
[Development] 526: Look at the Review Page for 526 to Make Sure We Are Handling Removals Correctly

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7298]
## User Story or Problem Statement
How might we avoid data discrepancies when using the review page?

## Goal
No more errors between the data arrays holding the submitted/rated disabilities.

## Tasks
- [ ] Figure out if the form system has an "error" and whether it is an easy fix to correct either on the back-end (new ticket written for the form folks) or whether it is something we can fix on our back end as a temporary fix (new ticket for our back end)

## Acceptance Criteria
- [ ] Figure out where and how to fix this

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
After meeting with @Mottie and Chris Valarida this morning, we discovered there actually is a function in the code to handle this situation. The function is called `removeDisability` and it lives [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/pages/addDisabilities.js#L141). This function should be handling the removal of disabilities from the `treatedDisabilityNames` and `powDisabilities` arrays when appropriate, but it seems not to be working properly. We will continue to dig into this. There is also a test written for this specific function that is passing, so we will also need to see why that test passes but the data is not removed properly on submit.

**Comment by ndsprinkle** [comment]
For some reason, I am unable to replicate this both locally and in staging. This is strange as Robin and I have historically been able to replicate this. Silvio also was able to replicate it when we rediscovered this issue just a few days ago. I am going to test out some more scenarios to see if there's something about certain disability names/codes that affects this bug and also whether or not the disabilities are rated or new.

**Comment by ndsprinkle** [comment]
Following up to the comment above, this was not being replicated because rated disabilities are required to cause this situation. I will now do some new testing using rated disabilities.
