### ISSUE TITLE
[CST] Tell veterans when they can't submit a doc through EVSS when the service is down 

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#72980]
## Value Prop
As a veteran trying to submit a 5103, I want to know if VA didn't actually receive my submission, so that I can try to resubmit it again at a later time. 

## Background
The vets-api service we use for submitting 5103 requests to EVSS uses Sidekiq jobs to handle the request. We need to convert this to a synchronous call because it makes more sense for our use case.

To address this, we should convert EVSS::RequestDecision sidekiq job to synchronous call.

#### Reason for the change to synchronous
* If the EVSS service is down, the user will never be able to get to the part of the site where they can interact with the UI in a way that this request will be fired off.
  * The user has to be able to access the claim details page in order to click the button that allows the to submit a 5103 request
* This will make it easier to debug failures with the service
  * In DataDog, when the request is made, a 200 is almost always returned, regardless of if the job will eventually fail or not
  * If there is a failure, it is harder to debug the actual cause of the failure and fix it

## Context
Service that needs to be migrated is [here](https://github.com/department-of-veterans-affairs/vets-api/b0b8c01master/app/sidekiq/evss/request_decision.rb)

## Open Question

- [ ] What error message do we currently show when a submission fails? 

## Tasks
- [ ] Determine what needs to be done to make this happen

## Acceptance Criteria
- [ ] When making calls to EVSS to submit a 5103 from vets-api, the call is not handled by a Sidekiq job
- [ ] We show the default "try again, service is down" messaging when the service is down. 
- [ ] If the request to submit a 5103 doesn't go through, the user is alerted of this.
