### ISSUE TITLE
[FSR] Define criteria for stale in progress data removal

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#72991]
## Description
FE & BE need to define criteria for identifying and removing InProgressForms for 5655 that are stale and/or have been submitted. 

## Tasks
- [x] Define criteria for stale/submitted in progress form data removal
- [x] Create BE ticket to write and monitor the script that will remove
- [x] **Get approval from stakeholders for definitions and removals**

## Acceptance criteria
- [x] Removal criteria has been defined
- [x] BE ticket for removal has been generated

## Testing
- [x] N/A

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
@denisecoveyduc 
So here's what @kjsuarez and I came up with. He's creating a ticket to get unique identifiers for the categories below, so we can see a count, and if things look good we can remove the stale in progress form data. 


**Deletion Criteria:** 
- Older than 60 days 
- has attempted submit
- and return_url is '/veteran-information'
- and/or has undefined feature flags for [combined, enhanced, streamlined, streamlined_asset]


**Separate IPFs into 3 categories:**
1. IPFs that don't meet criteria that will be left untouched
2. IPFs that do meet criteria but have no submission and should be resubmitted manually
3. IPFs that meet all criteria and can be deleted

**Comment by Dr-Pongo** [comment]
Carrying this work over to sprint 118 with just one point remaining to review the data that @kjsuarez was able to gather in the categories listed above. Once we review and confirm we can remove the data I'll begin making additional tickets for cleaning out the feature flags and legacy logic
