### ISSUE TITLE
[CAIA General Support]: VA Form 20-10206, Request Personal Records POA/Third Party content

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#72998]
# CAIA General Collaboration 

## About your team

- **Team name**: Veteran Facing Forms
- **OCTO-DE product owner:** Matthew Dingee
- **Product name:** Request Personal Records (VA Form 20-10206)
- **Product manager:**  Tricia Baker
- **Slack channel:** `[#veteran-facing-forms](https://dsva.slack.com/archives/C044AGZFG2W)
- **Dedicated a11y specialist on your team (if you have one):** Jeana Clark
 
## About your request
We recently went through staging review for VA Form 20-10206, Request Personal Records ([staging link](https://staging.va.gov/records/request-personal-records-form-20-10206/introduction)). Some CAIA-approved content was flagged, and we'd like support exploring a solution. 

### Describe your project goals
Right now: There's an additional-info component labeled “How do I request personal records for someone else?”. The content exists on the intro page, and on the first step of the form where the authenticated user self-identifies. 

Based on the DS guidance, there’s too much content in the details of the component and we should either

1. Reduce the content,
2. Choose a different component, or
3. Point to another page where the user can learn more about the requirements

After considering the options and discussing with Megan Zehnder (@megzehn) here's where we're at:

1. Reduce the content
> Reducing the content might be possible, but it’s already fairly straightforward and written in accordance with plain-language standards (this is CAIA-approved content).
2. Choose a different component
> We’ve mocked-up a version with accordions, and we’re concerned it would then occupy more space than necessary on the page itself, and since the content doesn’t apply to the folks who are eligible to complete the online form, we don’t want to distract or overload them with unnecessary details. For the folks who need it, we want it to be discoverable, but we don’t want to add more cognitive load to the audience that’s here and ready to start working on their request.
3. Point to another page where the user can learn more about the requirements
> This may be the ideal route, but CAIA needs more time to look into the LOE to stand-up a static page that this and other forms could point to when it’s necessary to educate folks on how to become an authorized third-party representative or power of attorney

### What is your team working on?
Digitizing VA Form 20-10206, Request personal records for users who are LOA3 authenticated and who are asking for their own personal records (ie, not a third-party or POA requester).

### Content
- [ ] Creating new content 
- [x] Updating existing content 
- [ ] Translating content 
- [ ] Something else:  

### Accessibility
- [ ] Wireframes or prototypes review
- [ ] PDF review
- [ ] User research support
- [ ] Something else:  

### IA
- [ ] User flows
- [x] Page placement (possibly, if we point to a new page)
- [x] URLs (possibly, if we point to a new page)
- [ ] Breadcrumbs and left nav placement
- [ ] Redirects
- [ ] Something else: 

### Other
- [ ] Check this box if you're not sure what kind of support you need, and we'll schedule an introductory meeting to learn more about your project.

## Collaboration timeframe

We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Your timeline 
- [ ] Check yes, if this request is tied to a Congressional mandate or timeline? 

### Description
Since this is not a launch-blocking issue and we have stakeholders eager to see this form go live, we will go to production with the content as-is. We'd like to revise it once there's an ideal solution. Our targeted launch date is 1/9/2024. 

## Collaboration cycle 

- **Staging Review Ticket Number:** [#72158](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/72158)

### Phases Completed
**Check any phases you’ve already completed:**
- [ ] Design intent 
- [x] Midpoint review 
- [x] Staging 
  
## Supporting artifacts
- [Figma Mockups](https://va.gov) (see [local components](https://www.figma.com/file/ZfkeFX8ZnXYxIPetj28adt/Form-20-10206---Request-personal-records?type=design&node-id=105%3A26195&mode=design&t=7fwcoIyn0q5Van3Y-1) for the two variations of this content)
- [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md)
- [Staging link](https://staging.va.gov/records/request-personal-records-form-20-10206/introduction)

## Next steps
- [ ] Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.
    - A member of the CAIA team will aim to respond to your Slack message within 24 hours to acknowledge receipt - should we need any additional information regarding your request we will reach out to you to confirm.
    - The CAIA Operations group will meet to go over the info in your request and then reach out if we have any questions.
    - Depending on the request, it may make sense to schedule a kickoff meeting to better understand how we'll partner with you!
- [ ] Please review the remaining next steps in the **VFS Team Tasks** section, listed below.

## TASKS

<br>

```[tasklist]
### VFS Team Tasks
- [ ] If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
- [ ] If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+jilladams%2C+RLHecht&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.
```

```[tasklist]
### a11y Tasks
```

```[tasklist]
### Content Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73384
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92772
```

```[tasklist]
### IA Tasks
```

```[tasklist]
### CAIA Ops
- [ ] Provide GitHub Deliverable to VFS team post kickoff
```

**Comment by humancompanion-usds** [comment]
My recommendation is to follow our guidance from Accordion here:

> ### Additional reasons to consider something else
> * Users would benefit from seeing additional context for a discrete piece of content. Use the Additional info component instead to leverage show/hide functionality, especially in a form.
> * Content that can be organized under the current heading. Use the Additional info component if you have additional content that provides context and makes sense under the same heading as the content nearby.

With this in mind I think you could make the case that:
A. An accordion is the appropriate choice on the Intro page because there is significant content which could very much live under a distinct heading of "How do I request personal records for someone else?". It doesn't make sense under "What types of information can I request?" and thus doesn't make sense as an Additional Info component. Requesting records for someone else is arguably as important as the other h2s on the page and at the very least an h3. This relates to the 2nd rule above.
B. An additional info component might be appropriate, despite the content length, on the first step of the form because it provides additional context for a discrete piece of content, the fieldset. This relates to the 1st rule above. I would argue that if you make the 1st instance on the Intro page an Accordion that perhaps you don't need the full content on the 1st step to be repeated. 

That said, I agree that the ideal route is to have a dedicated page to explaining this that we can link to.

> when it’s necessary to educate folks on how to become an authorized third-party representative or power of attorney

Couldn't the Accredited representative team under Jen Bertsch do us a solid here and create that page? They are creating an entire section of the web site dedicated to helping Accredited representatives. How to become one certainly seems like content that should exist there.

**Comment by megzehn** [comment]
Hi! Just wanted to cross-post this update I put on the [content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73384) associated with this intake. 

> Update: I submitted https://github.com/department-of-veterans-affairs/VA.gov-team-forms/pull/1103 and shortened the copy we had for people signing forms on behalf of someone else. This is a temporary solution until we can answer a few more questions (When should someone fill out an alternate signer form versus an accredited rep form? Do we want to move this content to a static page? Is there a consistent experience for people signing on behalf of others that we can capture in a static page?)

CC @rachelshearerux for awareness!
