### ISSUE TITLE
Fetch SSOe SAML metadata

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7300]
Follow-up on ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/6823 when items are completed.

Note: this is an old issue, this [contemporaneous SSOe security review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/security-review/SSOSecurityReview.md) provides much of the necessary context for understanding what changes were made and why the current issue ticket is warranted.

## Issue Description

`vets-api` currently stores the SAML metadata it uses to communicate with ISAM in several files within the [devops repo](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/vets-api) (see the `_metadata_isam.xml` files) as well as [on a file within `vets-api`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/ssoe_idp_int_metadata_isam.xml) for development SAML. This method of storing SAML headers is brittle and can lead to outages in the event that the SAML headers expected by ISAM change unexpectedly. Instead, up to date headers can be fetched from the following ISAM endpoints and stored for use during the `vets-api` build process:

```
| localhost (developers) | INT | int.eauth.va.gov | https://int.eauth.va.gov/isam/saml/metadata/saml20idp |
| dev | INT | int.eauth.va.gov | https://int.eauth.va.gov/isam/saml/metadata/saml20idp |
| staging | SQA | sqa.eauth.va.gov | https://sqa.eauth.va.gov/isam/saml/metadata/saml20idp |
| prod | prod | eauth.va.gov | https://eauth.va.gov/isam/saml/metadata/saml20idp |
```
---
## Tasks
- [ ] Add job to `vets-api` build process to query the appropriate ISAM instance and save the SAML header response, then update the settings.yml file to direct to the new filepath
- [ ] Ensure job functions properly on Docker instances of vets-api
- [ ] Add comparison between dynamic SAML response and saved SAML, as well as an alert if a discrepancy is detected
- [ ] Add logging for non-200 responses from ISAM endpoint

**Comment by christine-dillman** [comment]
Tech debt and not essential for now.  However, anytime IAM updates we will have to update our metadata until this ticket is complete.

**Comment by joeniquette** [comment]
@patrickvinograd Do you have more information on what this request was for this?

**Comment by joeniquette** [comment]
| localhost (developers) | INT | int.eauth.va.gov | https://int.eauth.va.gov/isam/saml/metadata/saml20idp |
| dev | INT | int.eauth.va.gov | https://int.eauth.va.gov/isam/saml/metadata/saml20idp |
| staging | SQA | sqa.eauth.va.gov | https://sqa.eauth.va.gov/isam/saml/metadata/saml20idp |
| prod | prod | eauth.va.gov | https://eauth.va.gov/isam/saml/metadata/saml20idp |

**Comment by nsoutouras** [comment]
MSI - Should finish this sprint.  Depends on Login.gov

**Comment by nsoutouras** [comment]
@bramleyjl Can you give me an update on this one?

**Comment by nsoutouras** [comment]
Nick: Allows us to automatically pull metadata file changes that SSOe makes.  Benefit: Less downtime and less engineering time dedicated to creating PR.

**Comment by bramleyjl** [comment]
Getting back to this now - the SAML metadata fetching is working properly and has test coverage, I'm just tweaking the Slack notification formatting; should be ready for review within a day or two.

**Comment by bramleyjl** [comment]
This ticket is blocked pending the creation of a new Slack notification module (#34516), which it will leverage to notify #vsp-identity of SAML metadata conflicts

**Comment by bramleyjl** [comment]
After further discussion the Identity team decided that attempting to dynamically set `vets-api`'s SAML service's metadata on the application's startup would not be worth the technical complications. Specifically, the `Settings` values that would necessarily be dynamic were causing issues in our test suites; values would inadvertently be reused in subsequent tests and a clean testing environment was difficult to maintain.

As an alternative, a new [synthetic test](https://app.datadoghq.com/synthetics/details/2r7-e82-zzk) has been added to DataDog. This test will download ISAM's current metadata and perform the same check against what is currently used by vets-api, and runs once every 30 minutes. Test failures are rerun twice, and after three consecutive failures an alert is sent to the #va-identity-alerts channel.
