### ISSUE TITLE
[Design] Clean up pages in Figma Production file

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#73002]
## Tasks
- [x] Clean up pages in [Figma Production file](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=2-1305&mode=design&t=wTQaBfoA9Y4twTVu-0)
- [x] Apply auto-layout

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/73002?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by benbrasso-agile6** [comment]
How's this coming along @zach-park? Something that maybe @cgednalske could assist with, if needed?

**Comment by zach-park** [comment]
Hi @benbrasso-agile6 , yes, Chrstina and I are meeting today to collaborate and split tasks.

**Comment by zach-park** [comment]
The ticket is ready for validation, @ytsaoca @cgednalske @benbrasso-agile6 @kellysmith1008

**Comment by benbrasso-agile6** [comment]
Let's everyone try to take a peak at the work to see if we have any questions or comments :)
