### ISSUE TITLE
[Design] Create ONE local reusable component in Figma (similar to a local Symbol in Sketch)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#73006]
## Description 

Without creating a separate library (from the VA Library), how can we create a local component (e.g., Need Help component or an appt card component) that can be managed in one place, which would update all other instances using the local component. 

Attend Figma office hours or talk to Cierra from Appointments Team, if needed. 

## Tasks
- [ ] Create ONE local component that is reusable (e.g., Need Help component or an appt card component) 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by ytsaoca** [comment]
Created the card component with auto layout and properties in the Production file. ([component page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=356%3A1039&mode=design&t=tqBP8upzrM7zoRsX-1))

**Comment by benbrasso-agile6** [comment]
LGTM. Very well explained too!
