### ISSUE TITLE
Create Template For Case Closure 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#73001]
## Issue Description
_Create a template for notification of case closure

---
## Tasks
- [ ] _Draft template for Salesforce case closure 
- [ ] As a Support staff member, I need a template to notify Veteran that due to lack of response to Salesforce issue the case has been closed
- [ ] 

## Acceptance Criteria
- [ ] _Template is approved and available for use by support staff
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Incorporated into Issue #199
