### ISSUE TITLE
Draft evaluative research goals and plan for TE 1.1 Release  (a joint effort between TREX and CARBS)

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#73031]
## Issue Description
We will be conducting Veteran-facing usability testing on the new feature in the 526ez along with the IPF alerts from the 1.1 rollout. This user testing will complement ongoing UX monitoring of the release (#90466). Findings from this previous monitoring ticket will inform research questions and help to focus the study, itself. 

At a high level, we want to know what aspects of the UX are causing problems for Veterans, leading to abandonment, cognitive fatigue, frustration, etc. We are also curious about how the In Progress Form is impact opt-in/out rates for Veterans. 

## Veteran Impact
The outcome of this ticket will be a research plan, which we will use to align with OCTO and start the Platform process of launching a study. Findings from the study will help drive design improvements to the TE flow, making it easier and more intuitive for Veterans to apply for benefits. 

## Scope
The scope of this ticket includes making decisions about research methodology, participants, and logistics. At the time of writing this ticket, we're unsure whether we'll conduct the study in production or staging. 
1. This round of research will **not** include AT users-- we will run a separate study later this fall dedicated entirely to accessibility. 
2. This round of research will **not** include VSRs. See #87820 for future possible work with our downstream users. 

## Questions raised during the design phase
**Coming out of the design phase in January 2024, designers created a list of questions that were relevant or top-of-mind. These questions will be one input into the research plan, along with the findings from the early UX monitoring.** 
1. How to indicate that date ranges are optional without causing additional problems (might be a design system level question)
2. Importance of / behavior of "not sure" checkbox option
3. Importance of / behavior of "none" checkbox option
4. Service connection radio button option 1: changing "my condition was caused by an injury or exposure during my military service" to "my military service caused my condition" - do Veterans interpret the new language the way we expect them to? Do they see it as more narrow (conditions caused directly by military service vs. something that happened during military service)? per [Figma comment](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK?node-id=0:1296&mode=design#707037734). Same question on radio button option 3

---
## Tasks
- [X] Develop research questions and methodology
- [ ] Review existing research we can learn from: 
    - [ ] Health Enrollment team's research ([Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md#research-findings-for-10-10ez-toxic-exposure-questions-usability-study) / [PDF slide deck](https://dsva.slack.com/archives/C0NGDDXME/p1715622985565069?thread_ts=1715605202.876099&cid=C0NGDDXME)) - check back to see if they have updates from moving forward on the recommendations

## Acceptance Criteria
- [X] Draft research goals
- [X] Draft research plan
- [X] Shared with HCD Leads Maya and Rueben for review, and Tracy, Accessibility Lead 
- [X] Shared with OCTO for alignment and approval

---
## Driver
Evelyn

## Reviewers
Maya, Ruben, Tracy

**Comment by evelynhilbrichdavis** [comment]
References: 
1. [Toxic Exposure documentation page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md#outstanding-questions-and-next-steps)
2. [Jan '24- Decision to wait until post-release to test](https://dsva.slack.com/archives/C053UDWMH7U/p1706716795239259?thread_ts=1706567587.571679&cid=C053UDWMH7U).

**Comment by mayacarrolluxa6** [comment]
@evelynhilbrichdavis :mega: Toxic Exposure Release: Evaluative Research Timelines have been compressed to be completed by EOY

	•	In my sync with 
[@Shannon Ford](https://dsva.slack.com/team/U027Y23EC00)
 yesterday, we reviewed the [proposed evaluative research timelines](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717458460532/5a74ece0ca694a9e6c85b3a1130a8c7b8dabf123?sender=u2d8a66f6d38755bd8c4c6218) for the TE release.
	•	Both Shannon and 
[@Emily Theis](https://dsva.slack.com/team/U01V6J7FA7N)
 provided feedback on the plans, noting that research running into January 2025 was not ideal. They would prefer to see this effort completed by the end of the year.
	•	From OCTO's perspective, this is the top priority for the HCD team.
	•	After discussing with 
[@Ruben](https://dsva.slack.com/team/U04PF0GGBU1)
 we see this as a potential collaboration opportunity between CARBS and TREX.
	•	I’ve drafted a [revised evaluative research timeline](https://docs.google.com/document/d/1fAMb4xONNfWjxSkY3yoiQvVC3rvJfd7fVLBYvpSzl_I/edit?usp=sharing) with Shannon, which schedules us to begin planning the research this sprint.
	•	The main dependency is the 1.1 release timeline, as we need that version to be released to conduct testing in the staging or production environment.

**Comment by mayacarrolluxa6** [comment]
@evelynhilbrichdavis Sharing feedback from Shannon "Thanks for lining this up - a couple small changes - the research plan (with goals and screener criteria) are all due at the time we request recruiting to start. Some modifications can be made to the discussion guide after, but it mostly has to be in place. I'd shoot to have that to Shane by the 18th or 19th at the latest."

**Comment by evelynhilbrichdavis** [comment]
[July 2023 TE Usability Testing](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2023-07-Toxic-Exposure)

**Comment by evelynhilbrichdavis** [comment]
[Shared materials with Shannon for review on slack on 11/4](https://dsva.slack.com/archives/C053UDWMH7U/p1730745096969109), which closes the ticket based on AC
