### ISSUE TITLE
submit1900_job.rb | Add queue exhaustion and exception logging

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73032]
## Issue Description
_The following job does not check for queue exhaustion nor does it have explicit exception logging:_ 
- [submit1900_job.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/vre/submit1900_job.rb)

Steve added a temporary queue exhausting monitor:
- [VRE::Submit1900Job has exhausted its sidekiq queue](https://vagov.ddog-gov.com/monitors/188837)

---
## Tasks
- [x] Add checks for queue exhaustion to submit1900_job.rb
- [x] Add explicit exception logging to submit1900_job.rb

## Acceptance Criteria
- [x] submit1900_job.rb checks for queue exhaustion
- [x] submit1900_job.rb logs explicit exceptions
---

**Comment by micahaspyr** [comment]
Submit1900Job does not use queue exhaustion but it does kickoff other jobs that use queue exhaustion and they log exceptions, those being
- **VANotify::EmailJob** to send confirmation emails
  - does log exceptions but does not log when a queue has been exhausted
- **CentralMail::SubmitSavedClaimJob** to process attachments
  - does explicitly log exceptions when a queue has been exhausted as well as general exceptions

**Comment by micahaspyr** [comment]
@steele-lm let's split this ticket up for each job to  better track.  The PR for modifying the 3 jobs would be too big and too confusing

**Comment by steele-lm** [comment]
@micahaspyr I split this ticket into three tickets and assigned them all to you. 👍
