### ISSUE TITLE
EPIC | Profile | MHV and DS Logon Credential Retirement

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#73065]
## Retirement of DS Logon and MHV credentials

Outline a plan for how we will support the DS Logon/MHV credential retirement strategy.
`Note:` My VA will work on this in January.

<details><summary>Draft Plans</summary>
<p>

`draft plans - not finalized`
 
### MY VA and Va.gov profile
Consider adding messaging for Veterans with My HealtheVet or DS Logon accounts. Consider adding to My VA home, VA.gov profile hub page, Account security page as relevant. Explore additional changes to Account security page steps to encourage Veterans to create a new Login.gov or ID.me account.

#### When:
o February-March 2024: Add initial messaging (awareness + encouragement)
o August 2024: Increase urgency of messaging (encouragement + get help now)
o November 2024: Increase urgency of messaging (alert + get help now)
o After December 31, 2024: Adjust messaging to post-transition messaging.

#### Responsible teams:
o Authenticated experience team (PO: Samara Strauss)
o Danielle (content guidance) and Tom (technical guidance)

</p>
</details> 

## Important Artifacts 
- [octo comms plan (must be on CAG)](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7Be2c3273f-0e19-488f-b0f5-1bf82a0cc0cb%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1)

## Tasks 
```[tasklist]
### Tasks
- [ ] Link to the FAQ Page
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73358
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73357
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88653
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78808
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78814
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78809
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78815
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78810
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78816
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89716
```
```[tasklist]
### keep these in mind since we'll be making changes in the account security page
- [ ] #63079
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/53574
```
