### ISSUE TITLE
Copy of [FE] DS v3 #5: Update buttons

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#73079]
## Background
The Design System has moved to version 3. We need to move the button components we have that use the Design System to use version 3.

Switch to button pair for Yes and No buttons - https://design.va.gov/storybook/?path=/docs/uswds-va-button-pair--default

Switch to primary button for single buttons, such as "Check In Now" - https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary
  
## Tasks
- [ ] [FE] **Update buttons for DS v3**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
