### ISSUE TITLE
[FE] My VA - Health care: Time in Appointment card is not correct if user is in different timezone

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#73088]
## Background

Jeff Roof (PM, VAOS team) posted about an issue on Jan 5th afternoon:

> Appointments team is seeing a problem with how appointments are being displayed on the authenticated landing page when user is in a different time zone.  Here is a summary of the issue:

> **Authenticated Experience Page shows wrong appt time zone when user is in different time zone than the facility**
> - Authenticated Experience Page shows appt time @3:55 PM ET which is incorrect. Appt time is 5:55 PM ET, not 3:55 PM ET. This error seems to only happen because my system is set to Mountain time.  
> - Note, tested with VAOS tester in EST and there are no issues, the authenticated experience page and VAOS show the same appointment time.

Currently the date and time for the Appointments card on My VA is parsed so that the time is synced with user's local machine time. The time should be adjusted to the time and timezone of the appointment location.

### Screenshots 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/b717f721-5e32-44b3-9a3f-fd44f42e0dc4)

![image (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/8f259fd3-392b-43e3-a030-ac38fd402ca6)

---
## Tasks
- [ ] Review how VAOS team is parsing date, time, and timezone 
- [ ] Test with machine or browser timezone set to a different one than the appt
- [ ] Notify Jeff Roof to validate

## Acceptance Criteria
- [ ] Time and timezone of My VA appointment card matches time and timezone of Appointments list page, and individual Appointments page

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? PM, FE_
- _How can this work be validated?_

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1704481343168139) - issue brought up by Jeff Roof of Appointments team
- Appointments v2 API documentation - tbd

**Comment by allisonlu** [comment]
@ajakabcin @JRRoof 

Ready for validation on staging! 

## To validate
1. Log in as any user who has upcoming appointments
2. Click through "Schedule and manage your appointments" to navigate to the Appointments list landing page
3. Confirm that the time on the Next appointment card on My VA matches the time of the first appointment on the list

**Comment by JRRoof** [comment]
Next appointment on My VA page is now showing the correct time zone offset.  Appointment is being displayed in users local time zone.  Appointment list and appointment details still showing in time zone of the facility.

**Comment by JRRoof** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/f5a4e401-f8b8-4614-9893-151b58b64186)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/a5defd5b-bfc4-4dcf-8929-fb1de62d5ab5)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/17e8ee95-206a-473b-bd61-4283917b8d4e)

**Comment by allisonlu** [comment]
hi @JRRoof! what staging user are you checking with?

**Comment by allisonlu** [comment]
hi @JRRoof @simiadebowale! can you help validate that this issue isn't present anymore? thank you!

**Comment by allisonlu** [comment]
Closing ticket. Will create new ticket if an issue comes out of [this Slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1708550556578429)
