### ISSUE TITLE
Burial | Create Contact Center Product Guide

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73109]
## Issue Description
_All applications on the Veteran-facing Services Platform include a phone number Veterans can call to ask questions about the application's functionality. Because of this, before applications (or new features) launch on the Veteran-facing Services Platform, all teams must file a Veteran Support/Contact Center Review issue that includes a Product Guide. Product Video is optional but encouraged. The VSP Contact Center team will review these materials and share with the relevant contact centers to ensure that Veteran Support/Contact Center Representatives are prepared to answer questions about the new functionality._

## Resources

1. [Template for creating a product guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md)
2. Examples of product guides ([here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/templates/sample-product-guide-1.pdf) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/templates/sample-product-guide-2.pdf))

---
## Tasks
- [ ] Create a product guide for the burial 530EZ form
- [ ] Submit a request to the Contact Center to review the guide (see instructions [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md))

## Acceptance Criteria
- [ ] Approved product guide for 530EZ form
---

**Comment by fiorella-io** [comment]
I created the [Burial product guide](https://docs.google.com/document/d/1GPNbnQpxTU2DBNLu6-5f2jdpT8Lb6MG0/edit?usp=sharing&ouid=113863434185824859488&rtpof=true&sd=true). I think we should list all back-errors burial could have. @DLarson-Oddball, feel free to list all the back-end errors in the doc. 

@steele-lm, feel free to provide any feedback

**Comment by fiorella-io** [comment]
I was able to add all the screenshots so this Product guide is ready. 
Two screenshots that are missing:
1. A screenshot of the About form 530 is a direct link to our online form in the [3. Navigation](https://docs.google.com/document/d/1GPNbnQpxTU2DBNLu6-5f2jdpT8Lb6MG0/edit#heading=)
2. Screenshot(s) of submission failure and any system errors I could not trigger in the [5. Major Issues and Error Messages](https://docs.google.com/document/d/1GPNbnQpxTU2DBNLu6-5f2jdpT8Lb6MG0/edit#heading=). Maybe @seanasewell or @DLarson-Oddball can help us with these.
