### ISSUE TITLE
Sketch to Figma migration for all Carbs Team design files

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#73104]
Before we lose access to Sketch, migrate all Sketch files to Figma so that we can access design files in the future.  All files must be migrated before 2/16/2024.  

The scope of this ticket is to identify the full scope of the files that need to be migrated and begin migrating files to Figma.

**Tasks**

- [x] Review instructions on how to move files from Sketch to Figma
- [x] Review all files can create a list of files that need to be moved to Figma
- [x] Move files to Figma
- [x]  Update components on the most recent version

**Acceptance criteria**

- [x] Identify the scope of the migration
- [x] Create a list of files that need to be migrated
- [x] Move files to Figma
- [x] Update components on the most recent version

**Comment by nnicholas7** [comment]
The following files were created on Sketch and transferred to Figma:
- 526 ITF Error Message
- 526 Error Message Redesign

Each of these files is located in the VA Figma Account in the Disabilities Folder.  Link to the folder can be found here: https://www.figma.com/files/project/176170217.
