### ISSUE TITLE
AMA/Decision Review Follow-on (Phase 2) x VSP Collab Cycle

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7311]
- [x] Define/Planning Kickoff-Intent- #6380
- ~Define Design intent~
- [x] Discover Usability Testing Prep - #7153
- ~Discover Research Plan Review~
- [ ]  Discover IA Request - #6920  
- [x] Discover Analytics Request -#7345
- [ ] ~Build Contact Center Review~ @lwalsh617 to send Chante write-up of copy changes
- ~Build Privacy/Security Review~
- [x] Build Staging Review - #7521
- [x] Launch
  - [x] Update Mega Menu Link --> #7650 
  - [x] Launch (4/16)
- [ ] Post launch
  - [ ] Validate Post-launch checkin 
  - [ ] Validate/Launch Full A11y Review

## Acceptance Criteria
- determine what's necessary and what's not

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)

**Comment by meganhkelley** [comment]
The list documented here of Collaboration Cycle points that apply to this work has been reviewed and approved by VSP! ✅

**Comment by MickinSahni** [comment]
@meganhkelley @andreahewitt-odd 
The contact center check-in seems to fall into a grey area with the content-heavy work we're doing. Folks aren't interacting with a "brand new service" or "a new feature in an existing service" per se. I'm thinking we strike this one. cc @jenniferlee-dsva
 
Also for awareness, we anticipated going live this week but given we have an accessibility spot-check going on and a pending staging review, that seems unlikely.

**Comment by meganhkelley** [comment]
@clantosswett could you please give this team guidance on whether they need to do a Contact Center Review for this initiative? For context on this initiative, check out the Project Kickoff meeting recording: https://zoom.us/rec/play/v5J7Jez5-Dw3S4adtgSDAKcrW43vfP6shCNM8vNezku0UHRQO1WiMuYRY-NfioWXA_Rrl3vRVz1mrhGP?continueMode=true

**Comment by MickinSahni** [comment]
> @clantosswett could you please give this team guidance on whether they need to do a Contact Center Review for this initiative? For context on this initiative, check out the Project Kickoff meeting recording: https://zoom.us/rec/play/v5J7Jez5-Dw3S4adtgSDAKcrW43vfP6shCNM8vNezku0UHRQO1WiMuYRY-NfioWXA_Rrl3vRVz1mrhGP?continueMode=true
> 
> Additional context (product outline, etc) can be seen by clicking through to tickets linked above

Some additional context from @jenniferlee-dsva  -- this originally launched in 2019 with the pass of the Appeals Modernization Act and should've been communicated to Call Center at that time. Not sure it would be necessary again. cc @meganhkelley @clantosswett 

Also, with respect to the Analytics request #7345 -- we're going to launch without this as the Analytics team is diverted to Covid response.

**Comment by joanneesteban** [comment]
@MickinSahni @jonwehausen Apologies because I think there was some confusion on our understanding of this initiative. We're going to prioritize #7345 so that you can re-launch with analytics.

**Comment by MickinSahni** [comment]
> @MickinSahni @jonwehausen Apologies because I think there was some confusion on our understanding of this initiative. We're going to prioritize #7345 so that you can re-launch with analytics.

@joanneesteban That would be awesome, of course. :) We wanted to make sure we were being mindful of a) our timeline b) how useful analytics would actually be given how much we have and c) y'alls bandwidth.

**Comment by jenniferlee-dsva** [comment]
completed, closing
