### ISSUE TITLE
[Design][Content] Adapt canceled appt in pre-check-in for check in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#73137]
## Description 

How might we let Veterans know an appt is canceled in check in? (Specifically, Unified Check In)

> So, the Veteran arrives at the facility and we are going to tell them their appt has been canceled? How would we know what appointment they were attempting to check in for?

> The appt is still there (in the LoROTA entry) but veterans have on avg 1.2 apps / day with up to 12 appts in one day.  When they type check-in, we do not know what appt they are checking in for, we simply send to va.gov and you display all the appts and they select the appt they want to check in.  You could add the canceled appts to va.gov so they at least know which ones have been canceled.

## Tasks
- [ ] Adapt [content used for canceled appts in pre-check-in](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/04C2CEC7-895F-4D1E-93A8-6BA0F1B97FED/canvas) to check in 
- [ ] Add new artboards with adapted content in Priority 1 and Design pages. 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by loripusey** [comment]
Don't we already cover this scenario? This is from the product guide.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/b342fc1e-f980-4a8b-99bf-95146157a045)

**Comment by benbrasso-agile6** [comment]
Yeah, I just went ahead and updated Priority 1 with the appt detail page we did for pre-check-in and added it to check-in. So, it's the same. 

<img width="394" alt="Screenshot 2024-01-08 at 3 46 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/5e762486-651d-49e9-af58-0797baeb41bb">

No work needed here.

**Comment by benbrasso-agile6** [comment]
Removed from sprint goals
