### ISSUE TITLE
Intro page: Update copy to remove redundant military history twice from page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73148]
## Issue Description
<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--524f91c4c3968103195ce4950eace01db2880152/Screenshot%20%28373%29.png" alt="Screenshot (373).png" />

---
## Tasks
- [x] On the Intro page of the pension form, remove the second instance of "Your military history" bullet point found under the "You'll also need this information" section.
- [x] Remove the "You'll also need this information" header, combining the two lists
- [x] Place all '*Required' items at the top of the list

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/73148?planning-poker) with Zenhub @danlim715 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by wayne-weibel** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/27690

**Comment by aplatt-coforma** [comment]
Updates looks good
<img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkVVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf2ffbd3c2be23d16e80c0f2b6e34238d33cd3f2/Screenshot%202024-01-30%20at%209.56.54%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.56.54 PM.png" />
