### ISSUE TITLE
IA traceability of old standards to new standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73149]
## User Story
As an OCTO-DE IA lead, I want to ensure that there is IA standards coverage in the VA.gov Experience Standards so that VFS teams have a source of truth for IA standards _somewhere_ as they are not currently documented in the Design System.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
At the 12/4/23 Governance/OCTO meeting on the new VA.gov Experience Standards, OCTO IA lead Mikki Northuis expressed concern about the new standards not being as detailed as the old standards, specifically wrt information architecture. Since there is currently no source of truth for IA standards on VA.gov, OCTO has leaned on the VA.gov Experience Standards as an interim solution for communicating IA standards. There is concern from Mikki that broadening the VA.gov Experience Standards to the Veteran experience and removing specific details will mean that VFS teams will not be aware of and will not build products that support the IA standards for VA.gov.

## Impacted Artifacts

- [IA Experience standards spreadsheet](https://docs.google.com/spreadsheets/d/1s_O6EhuvAaGKH5VsGOEhwpCDwuiDvWbWMlmRfRHa5xo/edit#gid=0)

## Tasks
- Create inventory - [IA Experience standards spreadsheet](https://docs.google.com/spreadsheets/d/1s_O6EhuvAaGKH5VsGOEhwpCDwuiDvWbWMlmRfRHa5xo/edit#gid=0)
  - [x] Pull out list of existing/old Experience Standards that have the "IA" tag from the [Revised Experience Standards - Process document](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit?usp=drive_link), along with their recommended action (keep/merge/archive) and the new Experience Standard that will replace it.
  - [x] Locate any relevant documentation on design.va.gov that relates to the standard
  - [x] Note experience standards that are missing documentation on design.va.gov
- [x] Meet with Mikki to discuss next steps (meeting Wednesday, January 10, 2024)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have a plan on how to address gaps in IA coverage with the new Experience Standards

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@erinrwhite per our conversation this morning. Can you please update this ticket with the mapping spreadsheet you drafted? And add any other relevant details - thanks!

**Comment by erinrwhite** [comment]
@shiragoodman I've technically completed all the steps on this ticket. I believe next steps are:

- Meet with Matt and Mikki to agree on next steps
- Draft broad IA principles for design.va.gov, using old experience standards as a starting point

Not sure of order of operations, though.

Shall I create some starter tickets for these items, then close this ticket?

**Comment by shiragoodman** [comment]
@erinrwhite - thank you! We definitely will need a ticket for the 2nd bullet item, so if you don't mind creating that, I would appreciate it! 

I will follow up with you, Mikki and Matt via Slack on the #platform-collaboration-cycle channel.

**Comment by erinrwhite** [comment]
@shiragoodman Draft ticket in progress! #73684 

Okay to close this one out?

**Comment by shiragoodman** [comment]
yup - okay to close!
