### ISSUE TITLE
Replace Sketch references with Figma

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73142]
## User Story
As a VA.gov team member, I want to ensure I am being directed to the most up to date tools so that my time is not wasted trying to access outdated tools.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
Platform will be retiring Sketch as a tool in February 2024. The tool will be replaced with Figma.

The purpose of this ticket is to review Platform Governance documentation for Platform Orientation and Collaboration Cycle to ensure any references to Sketch are removed. 

## Impacted Artifacts
List all Confluence artifacts that reference Sketch here:
 - [How to complete a design review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2302869722/How+to+complete+a+design+review+for+Staging+review+touchpoint)
 - [How to complete a Design Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492563471/How+to+complete+a+Design+Midpoint+Review)
 - [How to complete a Design review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2605056001/How+to+complete+a+Design+review+for+Design+Intent)
 - [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
 - [How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)
 - [How to complete a Content Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2491613360/How+to+complete+a+Content+Midpoint+Review)
 - [How to complete an Accessibility review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2611511338/How+to+complete+an+Accessibility+review+for+Design+Intent)
 - [How to complete an IA review for Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2302312688/How+to+complete+an+IA+review+for+Staging+review+touchpoint)
 - [How to complete a Content review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2598371379/How+to+complete+a+Content+review+for+Design+Intent)
 - [How to complete an Information Architecture (IA) review for Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)
 - [How to complete an Information Architecture Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+Review)

List all Platform Website artifacts that reference Sketch here:
 - [Design at VA](https://depo-platform-documentation.scrollhelp.site/research-design/design-at-va)
 - [Design intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent)

## Tasks
- [x] Review Confluence and Platform Website guidance for Platform Orientation and Collaboration Cycle and identify any references to Sketch
- [x] List all artifacts with Sketch reference above in the Impacted Artifacts section
- [x] Make the change from "Sketch" to "Figma" and add additional content if/where necessary
- [x] Peer review

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Collaboration Cycle and Platform Website documentation no longer references Sketch

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Hi @erinrwhite all the references to Sketch have been changed to Figma. I missed one on [PW](https://depo-platform-documentation.scrollhelp.site/research-design/design-at-va), I changed it today and it should go live Tuesday. Since the sprint closes Tuesday I was hoping you could peer review all other files and then Tuesday afternoon peer review the one I missed.

All artifacts are listed under the Impacted Artifacts section.

**Comment by erinrwhite** [comment]
This is looking good! I am setting a reminder to check for the published page on platform website on Tuesday so that you can close this out. 👍🏻

**Comment by erinrwhite** [comment]
Page on platform website is looking good @allison0034 - good to close 👍🏻
