### ISSUE TITLE
[MVP] Step 5 Gross Monthly Income: Update question format for Gross Monthly Income recipient question

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73161]
## User story

As a pension team,
we need to ensure that the web form question format for "Who receives this income?" is reformatted to align with the PDF question format,
so that we can pass information from the online form to PDF more clearly and prevent veterans from going into Development, unnecessarily.

## Issue Description

On Step 5 of the Pension form for Financial information, under the Gross Monthly Income page

- Change the exiting question format for: Who receives this income?
-- from a short-text field answer option
-- to 3 radio button answer options: Veteran, Spouse, Dependent

- Ensure that the "Dependent" answer option has an indented text box field below it with the label "Which dependent?"

**Please note:** Please confer with an a11y specialist about how to adjust this approach to ensure it's understandable by someone using assistive tech"

---
## Tasks
- [ ] FE: Change question format for "Who receives this income?" from short text field to 3 radio buttons.
- [ ] FE: Ensure that the "Dependent" answer option has an indented text box field below it with the label "Which dependent?"
- [ ] BE: Update data mapping from web form to appropriate PDF question field(s)

## PDF data mapping

<img width="907" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f23bc15b61365cc0f3cc67f387ff7113ee525fb1/Screenshot%202024-01-17%20at%2010.00.10%E2%80%AFAM.png" alt="Screenshot 2024-01-17 at 10.00.10 AM.png" />

**Comment by aplatt-coforma** [comment]
Front end changes look good.
<img width="616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25xQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca9b40028be799580eb92d7b119138fa2ef46e6d/Screenshot%202024-01-22%20at%203.34.46%E2%80%AFPM.png" alt="Screenshot 2024-01-22 at 3.34.46 PM.png" />
