### ISSUE TITLE
Identity Dashboard (FE) - Include identity backend in login process

### ISSUE THREAD

**Issue by ianmagenta** [department-of-veterans-affairs/va.gov-team#73169]
## Description
Currently, there is no call to the identity backend to establish a user during login on the frontend.

## Tasks
- [ ] Create a `PUT` call to the `/user` endpoint during login
  - [ ] Ensure this works with the current login/logout setup and through multiple logins
- [ ] Update tests accordingly

**Comment by asg5704** [comment]
Closing as IDD is dead
