### ISSUE TITLE
[100% Traffic] Request CAIA & PW to update Pension URLs to recommended structure

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73179]
## Issue Description

- We need to request/work with CAIA to review our URL patterns to follow best practices.
- More information about [IA Design for Pension Form Reactivation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md#url) found here.
- In the case that our URL structure changes, we will also need to request redirects for these changes.
- Related ticket for redirect request for Pension form: [Redirect Request for Pension Form 527 #15012](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15012)

Other related to these cards:

- [CAIA Intake] Pension 527EZ Form Updates from Benefits & Claims | Non-Disability Experience #66578
- 2023 IA Audit - Pension - Draft #58341

Specifically, this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/66578#issuecomment-1804835985

---
## Tasks
- [x] Schedule meeting with CAIA for context (Feb 1, 2024)
- [x] Request/work with CAIA & Public Website team to review our URL structure
- [ ] Coordinate work for URL updates
- [ ] Work with Pension FE engineers as needed

**Comment by jennymayoco** [comment]
Hi @vbellissimo! I have upcoming PTO 1/25-1/30 and so I wanted to check in and see if there's a timeline for this IA work? I want to make sure someone has eyes on this work while I'm out in case of any questions and if there's anything I should kickoff before I head out. cc @strelichl

**Comment by vbellissimo** [comment]
Hi @jennymayoco , thanks for checking in on us. We may be at a point where we can start planning for this work. What do you think the first step of order should be? Does your team need to do an audit of the form pages' URLs? We now have a list of URLs we used to provide to the analytics team I can share with you. Let me know what I can do to help us get started.

**Comment by jennymayoco** [comment]
@vbellissimo Thank you for sharing this update! We can definitely review the form pages URLs and follow-up with any feedback. As for the base URL, there's a couple of redirects we'd work on for this. The first being taking down the temporary redirect for [this request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15012) and then implementing a redirect for the old base URL to go to the new base URL. If this all sounds good, I think a good next step is for me to connect with PW and align with how they'd like to approach this, whether to create one ticket or two separate tickets. I'm happy to jump on a call with you all and align on this as well and answer any questions!

You mentioned starting planning for this work, what's a possible timeline for the URL change in the next version? By when should we kick off this work with the PW team?

cc @katherine-fung @strelichl for visibility on timeline

**Comment by vbellissimo** [comment]
Hi @jennymayoco I think you're OOO starting tomorrow, but mind if I schedule 30 minutes for us after you come back? To get some better context. Thanks!

**Comment by jennymayoco** [comment]
@vbellissimo That would be great, thanks for setting that up!

**Comment by vbellissimo** [comment]
Notes from our meeting on February 1, 2024:

Request for redirects prior to deactivation of the form:
- [This ticket was originally created](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15012)], but it was cancelled.
- [According to the Non-Disability Benefits team](https://dsva.slack.com/archives/C057W3N9K2S/p1706900836223329), the request was cancelled because a custom implementation for redirects was put in place by their engineers that would allow the re-release of redirects based on incremental re-release of the form (25% of traffic, vs 50%, etc.)

With this in mind, I believe the pending action items are to:
- Reinstate the online Pension form to 100% of traffic
- Reinstate the online Pension form entry points that were deactivated. See [this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695069026901/50b83f710f1cd2f1f7f3bb63553c349ef90d402a?sender=u9d01ee38af217e4877e75660) and this card for more info.
- Request from CAIA & Public Website teams redirects to the online Pension form. Changing from https://.va.gov/pension/application/527EZ/applicant/information to the new URL structure recommended by CAIA's IA team.

**Comment by vbellissimo** [comment]
Hi @jennymayoco , wanted to drop by here and let you know we've officially launched the online form to 100% of traffic as of yesterday! With that said, I think we're ready any time now to update our form's URLs. Do we need to meet again? Let me know how we can coordinate to proceed and I will let my team know accordingly. Thank you!

**Comment by vbellissimo** [comment]
cc you @buddhima-coforma for awareness

**Comment by jennymayoco** [comment]
Hi @vbellissimo thank you for the update! Next step is for me to create a redirect ticket with the old form URL and the new form URL, which we are proposing `www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez`. This can be found in the [IA spec reactivation plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md) for reference. This redirect request would include all subsequent nested pages in the form flow. The Public Websites team will then review and implement depending on their sprint planning. 

Once the new link is updated, let your stakeholders know so they are aware and can update any links if needed.

Let me know if there's any questions in the meantime about the process! I will create the ticket and link it here.

**Comment by vbellissimo** [comment]
@jennymayoco Okay, sounds good. Thank you.

Will you let us know when the Public Websites team will review/implement? So I can communicate this to my team's engineers or be aware of anything we should know about.

Is there anything else you need from us in the meantime?

**Comment by jennymayoco** [comment]
@vbellissimo yes definitely! I don't have any other questions on my end.

Here is the [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77519). I think the link changes when it moves to the PW team's repo so I'll be sure to follow up with the new link. I'll cc you all as well.

**Comment by buddhima-coforma** [comment]
@jennymayoco pls loop me in on what's needed as @vbellissimo is out on parental leave. Thanks!
