### ISSUE TITLE
[100% Traffic] Coordinate with CAIA to reinstate Pension entry points across VA.gov

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73178]
## Issue Description
Once we re-release the online Pension form, we will need to work with CAIA to reinstate additional form entry points across VA.gov, so that veterans have full information architecture experience available to find the form.

Information about the entry points exists here:

- [IA Design for Pension Form Reactivation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md#urls-and-breadcrumbs)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695069026901/50b83f710f1cd2f1f7f3bb63553c349ef90d402a?sender=u9d01ee38af217e4877e75660) of documented entry points

This should be done by the time we're back at 100% of user traffic.
- [Related information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md) about Pension IA URLs available.
- Past ticket, CAIA's ticket to remove the entry points: #62547
- Past ticket, original CAIA intake request to review the IA/user flows: #66578

Pages related to Pension form:

- [How to apply for VA pension page](https://www.va.gov/pension/how-to-apply/)
- [Eligibility for VA pension](https://www.va.gov/pension/eligibility/)
- [About VA Form ](https://www.va.gov/find-forms/about-form-21p-527ez/)
- [Fully Developed Claims](https://www.va.gov/pension/how-to-apply/fully-developed-claim/) — 2 links in first and last accordions. Note: Product team may not be aware of this entry point.
- [Pension hub page](https://www.va.gov/pension/) — remove link and blurb. Note: Consider adding a note to the How to apply blurb to direct people with in-process forms (maybe future step).
- [Evidence needed page](https://www.va.gov/resources/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/) — remove CTA in intro
- [Top and left nav] — remove link to online form.
- [Form results page](https://www.va.gov/find-forms/?q=527EZ) - remove option to "Fill out VA Form 21P-527EZ online"

---
## Tasks
- [x] Contact CAIA/Megan Zehnder & Katherine Fung to make a request for CAIA to reinstate the following entry points that lead to the online Pension form.
- [x] Request/work with CAIA to update any copy as necessary
- [x] Request/work with CAIA to re-launch these pages
- [x] Work with Pension FE engineers as needed 

## Acceptance Criteria
- Once the online Pension form is released to 100% of traffic, the additional form entry points that lead to the online Pension form will be available to veterans on VA.gov again.

**Comment by vbellissimo** [comment]
Related Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1708709688349429
