### ISSUE TITLE
Discovery: Manage Signed in Devices Usability research - readout and presentations

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#73183]
### Description of UX Tasks
This ticket will track the efforts of presenting and socializing findings of the Managed Signed in Devices research

#### Tasks
- [x] Demo presentation - date tbd
- [x] Present for the VA UX practice meeting - Jan 29

#### Acceptance Criteria
- [x] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
