### ISSUE TITLE
Move Pension designs to Figma

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73188]
## Issue Description

Migrate pension-related files to Figma before the VA loses access to the Sketch workspace on January 24th. 
---
## Tasks
- [x] Export files from Sketch
- [x] Import files to Figma
- [x] Set up fonts
- [x] Set up icon libraries
- [x] Set up design system libraries

## Acceptance Criteria
- [x] All Pension Sketch files have been replicated in Figma

**Comment by gmaciolek** [comment]
After chatting with Julie, I'd like to tweak the tasks and acceptance criteria for this ticket a bit. We're going to consider the files "migrated" and continue to clean things up iteratively as we work on sections of the form going forward. We can remove: 
- Troubleshoot and fix any issues resulting from the migration
- Check to ensure all designs are using the new Figma VA design system component library

For acceptance criteria, I don't think there are specific VA requirements for organization. I would like to reorganize the files, though, but I think that work can be separated from migration tasks.

These tasks are still incomplete:
-  Troubleshoot pension team's access to Figma
-  Train team on on how to collaborate in Figma

**Comment by aplatt-coforma** [comment]
@gmaciolek - that sounds good. Feel free to update the acceptance criteria as you suggest and close this ticket.

For the tasks still to be incomplete, we can have a new ticket to cover the second item if you have plans to do a training. BUT I don't think it would be your responsibility to handle the first one. I believe access to Figma should be handle by the dots-dsva team

**Comment by gmaciolek** [comment]
Thanks @aplatt-coforma. I don't think we need to do any training at this point. I need to make sure I know how best to share designs in Figma for cross-functional collaboration, but I think we can wing it for the time being until it seems like we need more formal guidelines.
