### ISSUE TITLE
Change MPR script for conditional content

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73195]
## User Story
As a VFS team member, I want to get through the "boring" script as quickly as possible so that we can begin the meeting.

Assignee:
Peer Reviewer:

## Description
We have heard from VFS teams that the scripts we read at the beginning of DI, MPR and SR are long and "boring." In an effort to shorten the script, edits can be made to the last 2 lines:

> Please take 5 minutes and communicate with us what has changed since the Design Intent, and also let us know of any specific product area concerns where you would like Governance team feedback.
> 
> Additionally, if you didn't go through a Design Intent review and this is the first time we are seeing your product, please briefly walk us through what you are presenting today.

It is not necessary for the host to ready BOTH lines. One or the other will suffice. If the VFS team member had a Design Intent, read line 1. If they skipped the DI, read line 2. We can also make some minor edits to these 2 script lines to make them more concise.

## Impacted Artifacts
[Midpoint Review - During the Meeting (Synchronous)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous)

## Tasks
- [ ] Edit the guidance so that the host only reads 1 of the 2 lines
- [ ] We may need to add a step earlier on for the host to check to see if the VFS team had a DI or not

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All attendees of Midpoint Reviews are spending less time listening to the script before beginning the meeting

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@it-harrison Just ahead of our midpoint review this morning, I changed this up on our [MPR operational docs](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous) as well as the [page on platform website](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review) (to be published this afternoon) - can you check behind? Thanks!

**Comment by erinrwhite** [comment]
@it-harrison 

[Platform website updated!](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)

and, [MPR operational docs](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous#Step-3:-Read-the-script) 

are ready for final review 👍🏻

**Comment by erinrwhite** [comment]
@it-harrison nudge on this review. Thank you!

**Comment by it-harrison** [comment]
@erinrwhite looks good! sorry for delay!
