### ISSUE TITLE
Daily monitoring of Pension MVP launch in Datadog

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73197]
## How to use this ticket
This is a daily checklist for monitoring the health of our release. Tasks for this ticket should be completed first thing at the beginning of each day, and reported to the internal team and key stakeholders. Below are the metrics used to gauge the health of the release. See these links for details on the [release plan](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?sender=u9d01ee38af217e4877e75660).

Link to documentation of [Datadog Displays & Alerts in Google Sheets](https://docs.google.com/spreadsheets/d/1U7Yug9kf4bVkt-v9PJLwpeJoD6bAqkeiCisEjBkaLA0/edit?usp=sharing)

### Alerts planned to be tracked 

- High error alert
- Retries exhausted
- Low traffic

Above alerts will be automatically posted in the [#benefits-pension-notifications](https://dsva.slack.com/archives/C0667PCPVLM) Slack channel

---

## Tasks
- [ ] Engineering: Post the FE and BE error metrics for the previous day, including the type of error and intervention needed.
- [ ] Engineering: Craft an update, share with VA enablement team
- [ ] Product: At the end of the observation period, consult the VA enablement team about increasing the release.
