### ISSUE TITLE
Include Zoom link in location field of Collab Cycle touchpoint invites

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73190]
## User Story
As a person attending a collab cycle touchpoint, I want to easily be able to find the Zoom link in the expected field so that I don't have any issues joining the call.

Assignee: @briandeconinck 
Peer Reviewer: @rferguson13 

## Description
At the 1/8 Midpoint Review with the Cartographers team, Accessibility specialist Angela Fowler suggested that we add the Zoom link to the location field of an event invite. This will make it easier for folks using accessibility tools to locate the link, and it also may resolve the OCTO Outlook issue of Zoom links not being included in event invites. This has been a recurring problem with Governance PO, @humancompanion-usds .

The purpose of this ticket is to modify the Governance operational guidance for scheduling a Design Intent, Midpoint Review and Staging Review to include a step for adding the zoom link to the location field.

## Impacted Artifacts
[Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
[Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
[Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)
[Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

## Tasks
- [x] Update Zoom information page with code blocks containing just the Zoom link for each timeslot
- [x] Add a step (or bullet) to the appropriate location of all 3 guidance docs
- [x] Step should include copying and pasting the zoom link into the location field
- [x] Test the below scenarios using your VA.gov email account
   - Zoom information in body paragraph only
   - Zoom information in location field only
   - Zoom information in both body paragraph and location field
   - Zoom information in both body paragraph and location field, but the original date/time of the meeting has been moved
- [ ] ~If we do end up removing the Zoom information from the body paragraph, publish a change announcement to the #vfs-change-announcements channel~
   - Determined it doesn't make sense to remove from the body paragraph (at least for now) 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Zoom links are no longer dropped from the events for those using MS Outlook
- [x] Individuals using screen readers or other accessibility tools are able to easily find and open the Zoom link to the meeting
- [x] (If we end up removing Zoom information from the body of the invite) We have published a change announcement to Slack informing VFS teams

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by humancompanion-usds** [comment]
This actually happened again on Monday with the midpoint review. This is what it looks like when I view it in Calendar (I'll validate that it looks the same in Outlook):

<img width="288" alt="Screenshot 2024-01-09 at 1 10 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/52176351/505598d9-7117-4fad-9b8c-655a739e0eea">

As you can see there are some key spaces missing that cause the links to run into the text that follows thus making them unopenable. That makes that very convenient "Join" button not work because the word Meeting is apart of the URL being passed. Same thing with the link further down the message. It runs into the URL that follows and so it's mangled such that right-clicking on it and selecting Open Link also fails. So it becomes a task of copying the text, editing out the invalid parts, and entering that into the browser URL field. Not impossible, but I will admit that when it happens it makes me a few minutes late to that touchpoint meeting.

**Comment by briandeconinck** [comment]
@rferguson13 this is ready for review!

**Comment by rferguson13** [comment]
@briandeconinck - I just realized we should also update [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling). Would you like to do it or should I?

**Comment by briandeconinck** [comment]
Oooh -- I'll get that, thank you for remembering!

**Comment by rferguson13** [comment]
@briandeconinck The rest look good! Once that last one is done, we should be able to close this out.

**Comment by shiragoodman** [comment]
@briandeconinck @rferguson13 I updated the ticket to include a couple additional tasks as well as new acceptance criteria.

**Comment by briandeconinck** [comment]
Findings from testing with my @va.gov account in Outlook:
1. Zoom information in body paragraph only
   - Everything came through as expected, no issue. Zoom link present and functional in the message body. ✅ 
2. Zoom information in location field only
   - Everything came through as expected, no issue. Zoom link present and functional in the message location field. ✅ 
3. Zoom information in both body paragraph and location field
   - Zoom link was present and functional in both places, BUT there were some odd formatting issues in another part of the message body. (Not a missing space, but a link that linked more text than it was supposed to link. This is not present in the Google Calendar event on my @adhocteam.us calendar.) 🟡 
4. Zoom information in both body paragraph and location field, but the original date/time of the meeting has been moved
   - The new date/time/Zoom link didn't get passed along to Outlook at all. I never received any notification and the calendar event didn't update. But *canceling* the meeting did get passed along. ❌ 

So I wasn't able to reproduce what Matt is experiencing (at least, not in Outlook alone). But the weirdness in scenario 3 makes me think there's some fun randomness in how body text gets passed from Google to Outlook.

I didn't see any issues with links in the location field. My gut reaction is that we should keep including Zoom info in both the location and the body as the safest option, and then see if Matt or any other VA folks report problems there (or just don't show up to meetings). Does that sound reasonable @shiragoodman @rferguson13?

For scenario 4, that *shouldn't* be an issue for Collab Cycle touchpoints, since teams should be following the instructions to cancel and reschedule via Calendly, and so VA folks will get a newly generated event. But that's something we'll need to remember in general: if someone from VA is on the meeting, never move, always cancel and reschedule.

**Comment by shiragoodman** [comment]
thank you for completing this very thorough testing @briandeconinck . Tagging @humancompanion-usds for his awareness.

I agree that we should move forward with including links in both the location field and body section. 🤞 🤞 !

**Comment by shiragoodman** [comment]
@andreahewitt-odd @jwoodman5 tagging you FSYA. Thought you might be interested in Brian's findings above with testing Zoom and Outlook. LMK if you have any questions!

**Comment by briandeconinck** [comment]
@rferguson13 All of the touchpoint scheduling pages should be updated based on the discussion above (including Design System Staging Review). If you could give them a quick check I can close this out!

**Comment by rferguson13** [comment]
@briandeconinck This looks good to me. Let's close this out!
