### ISSUE TITLE
Redesign Collab Cycle feedback template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73201]
## User Story
As a VFS team member, I want to be able to easily find/locate feedback for my team/product from the Design Intent so that I can ensure my team makes the recommended changes.

As a Governance team member, I want to make sure that VFS teams can easily find our feedback tickets so that we're meeting their expectations.

As a Governance PO and PM, I want to make sure relevant labels are applied consistently to all feedback tickets so that we can begin tracking teams and products throughout the Collab Cycle (opposed to just at Staging Review). 

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
In their research, Service Design team found that VFS teams sometimes have trouble finding the feedback tickets post-Design Intent. It was recommended that Governance begin tagging the PM (or another VFS team representative) in DI feedback tickets so that they are able to easily locate the tickets and don't miss any of the feedback provided.

In addition to tagging the PM or assigning the ticket to the VFS team, Governance would also like to begin including additional labels to the feedback tickets that align with the Collab Cycle Request ticket. This would include the VFS team label, the product label and the feature label. The labels that are currently added to the ticket are the default `collaboration-cycle` and `collab-cycle-feedback` labels, plus the `design-intent` label and the practice area label. 

Re: assigning the tickets, team recommends that we assign the ticket to whoever opened the Collab Cycle Request ticket as a default.

To ensure Governance team members are consistent in applying labels, assigning tickets, and completing all post-meeting tasks at the feedback-ticket level, it may be helpful to begin including a checklist for Governance team members to complete within the ticket to ensure all items have been addressed.

Since we're already making several changes to the Collab Cycle feedback template, the best approach would be a complete redesign of the template, evaluating the value and benefit of the existing content (VFS Actions, etc.) and organization of the template.

Lastly, we had planned to make changes to the VFS guidance re: including the Platform Governance Slack group name in ticket #71441, however since this ticket was upcoming, the changes to the Collab Cycle Feedback template in #71441 were pulled and should now be included within this ticket. Please be sure to review the details of ticket #71441 to ensure they are incorporated into the Collab Cycle Feedback template.

## Impacted Artifacts
[Collab Cycle feedback ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+collaboration-cycle&projects=&template=collab-cycle-feedback.md&title=Name+of+Collab+Touchpoint+-+Practice+Area+Feedback+-+Name+of+Project)gh template
[How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)

## Tasks
- [ ] Propose a new template addressing the concerns detailed in the Description section of this ticket
   - Ensure all acceptance criteria is met
   - [x] include the VFS team label, the product label and the feature label. The labels that are currently added to the ticket are the default `collaboration-cycle` and `collab-cycle-feedback` labels, plus the `design-intent` label and the practice area label. 
   - [x] assigning the tickets, team recommends that we assign the ticket to whoever opened the Collab Cycle Request ticket as a default.
   - [x] Include the Platform Governance Slack group name in ticket #71441
- [x] Share with Governance team members (excluding QA) for their review and feedback
- [x] Review operational guidance (ie How to document feedback for a Design Intent). Make updates where necessary to support new template.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The PM or whoever opened the CC Request ticket will be added an assignee
- [x] Ensure instructions for Governance are included in the gh template so that necessary labels are added
- [x] The template does not include Must, Should and Consider as official headings
- [x] VFS Actions section has been revised to meet current expectations
- [x] VFS teams are guided to reach out to Governance via Slack if they have questions/comments
- [x] Governance team operational processes supports the modified template

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.

### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
In the new template we should consider structuring our feedback using [task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#about-issue-task-lists) so that VFS teams could easily [convert feedback items into individual tickets](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#converting-tasks-into-issues).

![Screenshot 2024-01-10 at 12 27 55 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/86207ffd-3f9f-4b9b-be3e-7d38417eb817)

**Comment by allison0034** [comment]
@erinrwhite good point... I will add that to the task list. [Started a PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/74132).

**Comment by allison0034** [comment]
Shared with team on [Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1706198473056269).

**Comment by allison0034** [comment]
@briandeconinck ready for your review. If you approve the PR and documents please close this ticket if it is late today so it makes it in this sprint. Thank you!
- [PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/74132)
- [How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review)
- [How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)

**Comment by shiragoodman** [comment]
thank you, @allison0034 !

**Comment by briandeconinck** [comment]
Caught one tiny typo, otherwise this all looks good! Merging and closing the ticket.
