### ISSUE TITLE
Appoint a Representative app generation

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#73219]
## Issue Description
There was some frontend work already started for Appoint a Rep, but we should generate a clean form app for minimal confusion, as the app configurations will be different this time around (appName, rootUrl, title etc). 

Ideally, we will solidify the app configurations before generating the app. We will retain the option to update these, but that process is somewhat tedious (not to mention risky - releases can break for other teams when repos are not properly synchronized). 

---
## Tasks
- Confirm that appName, rootUrl, and h1/title/breadcrumbs have been agreed upon for Appoint a Rep. 
- Generate a new form app using the yeoman generator
- Add app entry to registry.json in content-build
- Add our URL to the clientside routing list in the devops repo

## Acceptance Criteria
- [ ] New form app has been generated and merged to vets-website
- [ ] New app entry has been merged to content-build
- [ ] URL has been added to clientside routing list and merged to devops

**Comment by oddball-lindsay** [comment]
One final PR coming this afternoon
