### ISSUE TITLE
Datebox time stamp and Auth. level tracking 

### ISSUE THREAD

**Issue by AdamOye** [department-of-veterans-affairs/va.gov-team#73216]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
On our form templates we need to represent a date/time stamp in the box for good practice. In addition a "watermark" with the auth level should be included and considered standard practice on all forms 
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] Using the upper left date stamp box to leave a time stamp
- [ ] Displaying Auth level and va.gov at bottom of the form 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] A Date/time stamp in two areas of the form 
- [ ] Auth. level note and va.gov at the bottom of the form 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tbaker1026** [comment]
@Thrillberg Is this global for all forms or do you need a ticket per form?
