### ISSUE TITLE
[Design] Create initial local components for production file and create and publish initial Check-in Component Library 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#73225]
## Tasks
- [x] Audit production file to see what components makes sense to create
- [ ] Start creating a couple components (but don't need to apply them to frames yet)
- [x] Create and publish Check-in Component Library

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/73225?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park

**Comment by zach-park** [comment]
During today's Figma discussion with @cgednalske @ytsaoca and me, a brief discussion came up by Ya-ching about possibly setting up CIE's own Figma library for the delta components (e.g., symbols) that doesn't currently exist in VADS Component Library. - This may be an extra effort, but it could potentially help us manage the local components better in the future (i.e., We've had inconsistency issues between the Production and Unified sketch file's local symbols)... Just thought it might be good to document here what was discussed today because I think Ya-ching brought up a really good idea. ;-)

**Comment by benbrasso-agile6** [comment]
Sounds good. That seems to be the instructions from Platform on [creating team component libraries](https://depo-platform-documentation.scrollhelp.site/research-design/designing-with-figma-at-va#DesigningwithFigmaatVA-Teamcomponentlibraries)

**Comment by benbrasso-agile6** [comment]
Started a [Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1704830285663199) about the potential of a shared component library with Appointments team

**Comment by ytsaoca** [comment]
Created a quick guide for the process: https://docs.google.com/document/d/1mFR4QJLMYV1mVN_y2Q_QQuAqVV7akoht0qM66DDzmss/edit#heading=h.33jj1br7vnx8
