### ISSUE TITLE
Generate feature toggles for Appoint a Rep

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#73222]
## Issue Description
Tentatively introducing two new feature toggles, one generic for the frontend and one for the api. Names subject to change.

```
appoint_a_representative_enable_frontend
appoint_a_representative_enable_api
```

---
## Tasks
- [ ] Confirm toggle nomenclature with team 
- [ ] Add feature toggles to vets-api toggle list
- [ ] Wrap Appoint a Rep frontend in frontend toggle

## Acceptance Criteria
- [ ] Confirm toggle state is reflected in staging
