### ISSUE TITLE
[FE] 10-10EZ - Household section: Discovery on how to migrate to target state URLs

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#73237]
## Background
When we launched the Household section optimization work, we had to maintain the Original and the V2 URLs, since both were live at the same time.  Now that we are fully using the new Household section pages, we need to migrate them to the original URL structure (removing V2).

This team has not done this before, so we need to dive into researching how to switch to the target state URL structure, whether there is any data migration needed, redirects, and/or anything else.

## Resources
- [Platform Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/)

<details>
<Summary>Expand here for list of V2 URLs</Summary>

- household-information-v2/financial-onboarding
- household-information-v2/financial-disclosure
- household-information-v2/confirm-financial-disclosure
- household-information-v2/financial-information
- household-information-v2/marital-status
- household-information-v2/spouse-basic-information
- household-information-v2/spouse-additional-information
- household-information-v2/spouse-financial-support
- household-information-v2/spouse-contact-information
- household-information-v2/dependents
- household-information-v2/dependent-information?index=0 (this number increases as more dependents are added)
- household-information-v2/veteran-annual-income
- household-information-v2/spouse-annual-income
- household-information-v2/deductible-expenses

</details>

## Tasks
- [x] Explore the Platform Website for guidance on how to switch a page to a new URL, and if there is anything on doing this for multiple pages at once
- [x] Create a detailed outline of process steps to accomplish our goals
- [x] Meet with PM to review outline and create tickets for next steps

## Acceptance Criteria
- A detailed process outline is created to assist the team in moving the Household pages to target state URLs

**Comment by jadon1979** [comment]
**Plan:**  
1. Remove v1 household component calls from `config/form.js`
2. Update the following files and remove -v2 from the url paths
- config/form.js
- tests/e2e/hca-household-v2.cypress.spec.js
- tests/e2e/index.js
- utils/constants.js 
3. Rename `hca-household-v2.cypress.spec.js` to `hca-household.cypress.spec.js` for E2E testing
4. Remove `householdInformation` directory and rename the `householdInformationV2` directory to `householdInformation`
5. Update `migrations.js `so that the referenced urls are updated on forms currently in progress

**Comment by hdjustice** [comment]
Updated #62517 with details from the plan outlined above
