### ISSUE TITLE
[BE] Update BTSSS endpoint to use fwdproxy in prod

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73257]
## User Story
As a Veteran, I want to reliably submit travel claim through the check-in process

Slack thread: https://dsva.slack.com/archives/C02G6AB3ZRS/p1702577596213329
platform docs on adding fwdproxy: https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration

## Tasks
- [x] Make a curl request to BTSSS endpoint for testing connectivity from fwdproxy instance
- [x] Find an available listener port...
- [x] Add config to fwdproxy...
- [x] update AWS Param store to add BTSSS url param to point to the fwdproxy URL
- [x] Modify settings.yml to get the fwd proxy url from paramstore
- [x] Add a feature flag to switch the calls between fwd proxy and BTSSS endpoint
- [x] Modify [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) for the changes in settings

## Acceptance Criteria
- [x] Deployed to prod 
- [x] Tested on prod

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/73257?planning-poker) with Zenhub @kanchanasuriya @randomsync

**Comment by ndouglas** [comment]
Unblocked.

- Opened [this PR](https://github.com/department-of-veterans-affairs/devops/pull/14281) for the fwdproxy listeners.
- Auth URL SSM Param: `/dsva-vagov/vets-api/prod/check_in/btsss/auth/api_url`
- Claims URL SSM Param: `/dsva-vagov/vets-api/prod/check_in/btsss/claims/api_url`
- Opened `vsp-infra-application-manifests` PR: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2832

**Comment by ndouglas** [comment]
Verified environment variables are set correctly:

```
CIE_BTSSS_AUTH_API_URL=https://...
CIE_BTSSS_CLAIMS_API_URL=https://...
```

**Comment by ndouglas** [comment]
Marking this closed; the feature flag was enabled and ran without any indication of unintended issues.
