### ISSUE TITLE
Implement Domo Dashboard for reports of outdated information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#73252]
## Background
Implement a Domo Dashboard to track reports of outdated information.  The content of this dashboard is outlined in this [Slack Canvas](https://dsva.slack.com/docs/T03FECE8V/F06DAB53ATF) (originally defined through https://github.com/department-of-veterans-affairs/va.gov-team/issues/73251)

## Tasks
- [x] Get access to BigQuery and Domo
- [ ] ~Write a background job that can connect with BigQuery~
- [ ] ~Update our new BigQuery table with records that have been flagged as inaccurate (since the job last ran)~
- [ ] Create a Google Sheet to store data 
- [x] Partner with Mason to create a Domo dashboard
- [x] Push Domo dashboard to production

**Comment by holdenhinkle** [comment]
Support request for BigQuery and DOMO access - https://dsva.slack.com/archives/CBU0KDSB1/p1712694426206499

**Comment by holdenhinkle** [comment]
Request for DOMO access for our team - https://github.com/department-of-veterans-affairs/va.gov-team/issues/80383

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/16269

**Comment by oddball-lindsay** [comment]
Requesting BigQuery access for @holdenhinkle @jvcAdHoc and Josh, Analytics team is working on that.

**Comment by holdenhinkle** [comment]
From Slack DM today:

Philip Dorsey
  3:27 PM
Hi Holden, sorry about the delay.  All of you have BigQuery access now.  I also created the service account for you last week  and made you an owner.  Let mw know if you need any help from here.

**Comment by oddball-lindsay** [comment]
Received credentials, but experiencing an issue with authenticating with Google -- looking into it.  Estimating a couple more days of heads down time to complete.

**Comment by holdenhinkle** [comment]
I thought using batch mode (which is available on the free version of BQ) might work but it doesn't; it requires us to store the data we want to batch to BQ in a file stored in Google Cloud.

We definitely, 100%, need to stream the data to BQ. I just informed Philip Dorsey of this and asked him what the process of asking Andrea looks like.

**Comment by holdenhinkle** [comment]
I pinged Andrea Hewitt about this.

**Comment by oddball-lindsay** [comment]
Discovered that the data was being cut off and we actually have many more reports than expected -- thought it was less than 10, but it's actually 855.  

For the Domo Dashboard, we will rely on a [Google Sheet](https://docs.google.com/spreadsheets/d/1xWTanMzIhLMJjNPuLB-CU7NsqIrMtNiW8fnIPHyULus/edit#gid=1660636444) to store data, instead of BigQuery.  Considering hashing the IP address for added security.

**Comment by oddball-lindsay** [comment]
Had a working session with Mason, next steps:
1. Tweaking the design for stakeholder consumption
2. Pushing the dashboard to production
3. Provide access to the team (they need Domo access, we need to work with Johnny from Analytics to provide access for anyone that doesn't currenlty have a Domo account)
   1. A custom group can be created for managing access

**Comment by oddball-lindsay** [comment]
Right now the data needs to be manually updated, check on where this feature is headed before we think about an automated updating approach.

**Comment by oddball-lindsay** [comment]
Dashboard is live and the ARM team has been provided access!  Jen is fine with the manual update for now, so @holdenhinkle will help update this every two weeks, before our ARM leadership syncs.
