### ISSUE TITLE
Sample Epic for Demo Only

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#733]
## High Level User Story
As a sample administrator, I need to create an epic so I can demonstrate the feature.

## Hypothesis/(es)
**If** _we create this epic_ **then** _we expect teams will be able to manage their feature more accurately_.

## Goals
_All team members can add issues to the epic_ 

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`)

## Definition of Done
- [ ] **Labeled with Team** (`product support`)
- [ ] **Labeled with Practice Area** (`product`)
- [ ] **Labeled with `Epic`**
