### ISSUE TITLE
Upgrade Rails to 7.1.X

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#73307]
### Description
After Upgrading to 7.0.8, we should bump to latest, which will have it's own set of challenges, as a few deprecation warnings are introduced and we should get ahead of the game.

### Tasks
- [x] Update to ~> 7.1 (7.1.2 currently)
- [x] Fix any broken tests
- [ ] Merge to master and test in staging
- [ ] Standby for Prod deploy

### Acceptance Criteria
- [ ] vets-api + modules are all at the latest Rails version in all environments

**Comment by ryan-mcneil** [comment]
Update: Working on a [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15295) to update the namespace used in `Digest::UUID`. Trevor is working on another piece separately. When those PRs are merged, the [Rails 7.1.3 PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15143) should be close to clean

**Comment by JoeTice** [comment]
SPRINT 45 UPDATE: Rails update is blocked waiting on other teams for associated PRs to be approved, work is progressing on those teams towards completing that work, but we're still waiting. Ryan is going to be out for the next couple weeks, so we'll put this on the Backlog and return to it in Sprint 47/48, by which time hopefully the blockers are cleared.
