### ISSUE TITLE
Investigate Upgrading Carrierwave

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#73308]
### Description
We've pinned Carrierwave to 3.0.3 due to "breaking changes" in 3.0.4 (that haven't been resolved in 3.0.5 either) despite a CVE associated with it (though the CVE doesn't affect us). [Others have faced this too](https://github.com/carrierwaveuploader/carrierwave/issues/2708) (Rachal posted here as well), and a [fix](https://github.com/carrierwaveuploader/carrierwave/pull/2710) has been suggested. However, reading through both of those linked convos, it sees that they may not intend to "fix" it, because that was never the intention (questionable argument). [I've asked them](https://github.com/carrierwaveuploader/carrierwave/pull/2710#issuecomment-1884004823) if they intend to merge this "fix" or if we should plan to adapt. I have a feeling it may be the latter, so we should investigate how we can adapt our code to the intended use of carrierwave.

### Tasks
- [ ] Bump to 3.0.5 and investigate fix broken tests
- [ ] If tests seem too difficult to fix, we could fork carrierwave and implement this suggested fix above to satisfy our needs
- [x] Merge to master

### Acceptance Criteria
- [x] Deployed to all envs

**Comment by ryan-mcneil** [comment]
Update: After some conversations with carrierwave developer, he actually popped in submitted a [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15118) with a quick fix! Merged today!
