### ISSUE TITLE
Update 'Troubleshooting Access to Datadog' Doc

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#73311]
### Context
This is related to our recently updated instructions on [requesting access to Datadog](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/71832).

### Description
The team that manages Datadog access recently changed from DOTS, to ECC. This has been reflected in the work done on this ticket, however, we also need to make sure we are updating the page around [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog).

## Content Changes

Look to rephrase the guidance underneath **'Hosting Location'**

**Page : [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog)**
- Remove instances of DOTS
> - Please contact the DOTS team at #dots-dsva.
> **Additional Support** 
> - For issues getting access to DataDog in general or any issues with DOTS and access to DOTS services, please refer to the #dots-dsva Slack channel.

## Tasks
- [x] Edits have been reviewed, and confirmed
- [x] Edits have been made on the [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog) page
- [x] Pages have been prepared for deployment
- [x] Pages have been deployed

## Acceptance Criteria

- [ ] Edits have been reviewed by an engineer, or related SME
- [x] Updates have been deployed to the Platform Website

**Comment by johnny-jesensky-adhoc** [comment]
Look to split into two separate tickets:

- Page 1: Get Access to Datadog (3)
- Page 2: Troubleshooting Access to Datadog (2)

**Comment by taylojill** [comment]
Here's what I did:
- Removed all references to DOTS. 
- Added link to Get access to Datadog page. 
- Removed the TOC as it only had one item after removing DOTS references. 
- Updated image caption and alt text.
