### ISSUE TITLE
Remove Webpack from the Metalsmith script

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7332]
## Description
Webpack is currently run via the Metalsmith script. To separate the builds from each other, we need to run Webpack standalone. So we don't break anything during the transition, we need to ensure both content and applications are built the same as before.

## Goal
To split the content and application builds.

## Tasks
- [x] Add [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin) to the Webpack config
  - Only use this when running `yarn watch`
  - May need a new template for the landing pages
- [x] Remove `configureAssets` from the Metalsmith script
- [x] Rename the current `build` NPM script to `build:content`
- [x] Rename `build-webpack` to `build:webpack`
    - Just for consistency
- [x] Remove the `watch` script
- [x] Rename `watch-webpack` to `watch`
- [x] Rename `script/build.js` to `script/build-content.js`
- [x] Write a new `script/build.js` which
  - [x] Runs the Webpack build
    - [x] Only when `--assetSource !== 'local'`
  - [x] Runs the content build
  - In that order so the broken link checker step of the content build doesn't fail (may have to modify the link checker script for this)
- [x] Modify the Metalsmith script to call `downloadAssets` only if `buildtype !== 'local'`
  - The `yarn build` script will run webpack if `buildtype === 'local'`
  - It's more work than it's worth for an interim solution to modify the `downloadAssets` script to be standalone
    - It adds the files to Metalsmith's `files` object
- [x] Modify the Metalsmith script to read the Webpack output from disk if `buildtype === 'local'`
  - So the broken link checker and `processEntryNames` plugins work
- [x] Remove any unused Metalsmith-Webpack code
  - [x] `configureAssets` and its dependencies
- [x] Modify the Metalsmith script to not remove `/generated/` and its contents

## Acceptance Criteria
- [ ] The content and application builds in CI are unaffected
- [ ] The Webpack build can run standalone
- [ ] The content build can run standalone
- [ ] Running `yarn watch`
  - [ ] Builds only Webpack assets
  - [ ] Creates landing pages to serve the applications
- [ ] The landing pages created from Webpack are not created for any build except when running the dev server
    - This will change when the content build is removed from `vets-website` and we've transitioned the content deploy to use that
- [ ] Content-only deploys download the built application assets instead of running the application build
