### ISSUE TITLE
Make active_status available to front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7333]
## User Story 
As a Veteran, I want to see facility level operating status within the Facility Locator so that I will which facilities are open to provide services. 

## Goal
Facility level ` active_status` can be displayed. 
Particular use case: Operating status during COVID-19
This is not intended as veteran facing filter at this time. 

**This is relevant to all VA facility types**

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 
---

## Tasks
- [ ] Make `active_status` available to front end for VA facilities
active_status` is available as part of /facilities/{id}

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/7f282c89-d40d-43f7-83a8-1649b7050de5)

## Acceptance Criteria
- [ ]  `active_status` is available to front end

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
fyi, @arickalewis1 and @davidconlon 
according to VA Facilities API: 

> Active Status
> Facilities can be temporarily deactivated for a variety of reasons. If a facility comes back from this API with "active_status": "T", it is not currently operating. "active_status": "A" indicates normal operations at a facility.

**Comment by mmiddaugh** [comment]
no longer relevant
Active status field has been deprecated by Lighthouse API
