### ISSUE TITLE
SPIKE | Identify PDF-generation service for forms

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73336]
## Issue Description
_To prepare for applying new universal standards to pdfs (e.g., date stamps), we need to determine what pdf-generation service each form is using._

Reference info:
- [Slack thread about universal pdf requirements](https://dsva.slack.com/archives/C044AGZFG2W/p1704816796263409?thread_ts=1704482531.369139&cid=C044AGZFG2W)

---
## Tasks
- [ ] Identify the pdf-generation service (e.g., vets-api, EMMS, etc.) for the following forms:
   - [x] 686 and 674
   - [x] Chapter 31 28-1900
   - [x] Chapter 36 25-8832
   - [x] COE/LGY 26-1800
   - [x] Burial 21P-530EZ
   - [x] 526EZ Ancillary Form 21-4142
   - [x] 526EZ Ancillary Form 21-0781
   - [x] 526EZ Ancillary Form 21-8940
   - [x] 21-4142 Authorization to Disclose Information to the VA
   - [x] 21-0966 Intent to File
  
## Acceptance Criteria
- [ ] A list of the forms and their pdf service (document on GitHub and provide to Emily Theis)
---

**Comment by SloopKoning** [comment]
Form 0526 uses the route to EVSS  /form526/v2/getPDF

It looks like the 526 associated forms also use EVSS to generate their PDF versions.

**Comment by sortizsh** [comment]
hi @SloopKoning  what is the progress on this ticket? Have you been able to dig into the other forms above, not just the 526? thanks

**Comment by SloopKoning** [comment]
Still researching non-disability forms.### Pathnames in `vets-api` which have "pdf"
- pdf_pathnames.txt
- modules/appeals_api/db/migrate/20210525183405_add_pdf_version_api_version_to_appeals.rb
- modules/appeals_api/lib/appeals_api/nod_pdf_submit_wrapper.rb
- modules/appeals_api/lib/appeals_api/hlr_pdf_submit_wrapper.rb
- modules/appeals_api/lib/appeals_api/sc_pdf_submit_wrapper.rb
- modules/appeals_api/config/pdfs/
- config/evss/letter.pdf.example
- modules/claims_api/lib/claims_api/evidence_waiver_pdf/
- modules/claims_api/lib/claims_api/evidence_waiver_pdf/pdf.rb
- lib/central_mail/datestamp_pdf.rb
- modules/appeals_api/app/services/appeals_api/pdf_construction/
- lib/claim_letters/test_pdf/
- modules/claims_api/lib/claims_api/poa_pdf_constructor/
- modules/claims_api/lib/pdf_generator_service/
- modules/claims_api/lib/pdf_generator_service/pdf_client.rb
- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- modules/appeals_api/app/sidekiq/appeals_api/pdf_submit_job.rb
- modules/appeals_api/app/controllers/concerns/appeals_api/higher_level_reviews/pdf_form_field_v2_validator.rb
- modules/appeals_api/app/controllers/concerns/appeals_api/pdf_downloads.rb
- modules/health_quest/app/services/health_quest/questionnaire_manager/pdf_generator/
- app/sidekiq/vbms/submit_dependents_pdf_job.rb
- app/uploaders/validate_pdf.rb
- modules/appeals_api/app/models/concerns/appeals_api/pdf_output_prep.rb
- modules/claims_api/config/pdf_templates/
- lib/decision_review/utilities/pdf_validation/
- lib/pdf_info.rb
- lib/benefits_intake_service/utilities/convert_to_pdf.rb
- modules/vba_documents/app/swagger/vba_documents/document_upload/v1/pdf_upload_attributes_swagger.rb
- modules/vba_documents/app/swagger/vba_documents/document_upload/v1/pdf_dimension_attributes_swagger.rb
- lib/common/convert_to_pdf.rb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_filler.rb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
- modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_pdf_generator.rb
- lib/shrine/plugins/validate_unlocked_pdf.rb
- lib/pdf_fill/
- lib/pdf_fill/forms/pdfs/
- lib/pdf_utilities/
- lib/pdf_utilities/pdf_validator.rb
- lib/form1095_b/templates/pdfs/

**Comment by SloopKoning** [comment]
With the except of the 526 form, it looks like all other forms go through a common PDF generation method.  The `pdftk` and `minimagick` utilities appear to be the common processes used to generate the PDF files.  `minimagick` looks like it is only used when the form happens to be an image file.  These two ruby files in `vets-api` are the places to look if you want to make changes to PDF generation.

- lib/common/convert_to_pdf.rb
- lib/pdf_fill/filler.rb

**Comment by sortizsh** [comment]
no further action needed on this ticket or follow ups
