### ISSUE TITLE
Toxic Exposure - clean up documentation Pt. 2

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#73332]
As we wrap up the design work on Toxic Exposure, clean up our documentation so that we: 

1. have a clear source of truth for the current state
2. make clear the important parts of the history of what decisions were made and why (avoid repeating loops)

Follows from #69341 

### Tasks
- [x] Write up key decisions made and background behind them in [toxic exposure Github page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md) 

### Acceptance criteria
- [ ] Add previous google docs content to github (Not relevant anymore)
- [x] Add findings from research into github doc

[Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md) written with key decisions made and background: 
- [ ] Final Wireframes for FE Mocks --> Sprint Review Mocks
- [ ] Revisions post-research --> Final Wireframes for FE Mocks
- [x] Test Prototype --> Revisions post-research

Separate ticket for this - [ ] Midpoint --> Test Prototype
