### ISSUE TITLE
VEText Add SMS Terms to VA.gov page

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#73356]
# CAIA General Collaboration 

`WIP`

Use this ticket to request general collaboration with the Sitewide Content, Accessibility, and Information Architecture (CAIA) team.

## About your team

- **Team name**: VEText
- **OCTO-DE product owner:** Shane Elliott
- **Product name:** VEText
- **Product manager:** Justin Wowk
- **Slack channel:** https://join.slack.com/share/enQtNjQ1MzAwNjc0MTEwNi0xMWY3ZTcxZmJmNjNjMDI3MzVmMmZmMjhmYzA4OTJkZjUxYjExZjVmZTc1ZWJjZjIzMWNiYWE5ODUxNWIxNmE2
- **Dedicated content writer on your team (if you have one):** @ahicksfearless 
- **Dedicated a11y specialist on your team (if you have one):** `Insert name and/or GH handle`
 
## About your request
Our SMS service provider requires specific SMS messaging terms be posted on a public facing website.

### Describe your project goals

Add SMS terms to VEText public page: https://www.va.gov/resources/vetext-for-va-health-care-reminders-and-updates/

### What is your team working on?
_For example, you may be launching a new form, page, or product, or updating an existing one._

We are requesting new short code numbers from which text messages will be sent from.

### Describe how you would like to collaborate with CAIA

Content collaboration to ensure SMS terms conform to VA.gov guidelines.

`CAIA Collaboration goes here.`

## Type of Collaboration 
_Check all the types of collaboration you're requesting, below:_

### Content
- [ ] Creating new content 
- [x] Updating existing content 
- [ ] Translating content 
- [ ] Something else:  `insert type of collaboration`

### Accessibility
- [ ] Wireframes or prototypes review
- [ ] PDF review
- [ ] User research support
- [ ] Something else:  `insert type of collaboration`
### IA
- [ ] User flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and left nav placement
- [ ] Redirects
- [ ] Something else: `insert type of collaboration`
### Other
- [ ] Check this box if you're not sure what kind of support you need, and we'll schedule an introductory meeting to learn more about your project.

## Collaboration timeframe

We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Your timeline 
- [x] Check yes, if this request is tied to a Congressional mandate or timeline? The approval of a short code request is 6-10 weeks from submission to carriers. Our service provider will not submit our application until the SMS terms are posted on a publicly accessible URL. We need to obtain the new short code for the Cerner/Oracle Health integrated VEText application planned to laucn at the end of March 2024.

### Description
**Describe where you are in your project's timeline.** 
_For example, you may be drafting content, planning or synthesizing research, waiting on an SME review, or scheduling your MVP launch date. Add dates for any upcoming milestones._

We would like the following content added to the current VEText page:

VEText Terms and Conditions

1. VEText is the official SMS Appointment Reminder program for the U.S. Veterans Health Administration (VHA).  VEText sends reminders about Veteran health appointments with the date and time of the appointment, and may include the clinic name and location of the appointment depending on individual preferences.
2. You can cancel the SMS service at any time. Just text "STOP" to the short code. After you send the SMS message "STOP" to us, we will send you an SMS message to confirm that you have been unsubscribed. After this, you will no longer receive SMS messages from us. If you want to join again, just sign up as you did the first time and we will start sending SMS messages to you again.
3. If you are experiencing issues with the messaging program you can reply with the keyword HELP for more assistance, or you can get help directly by calling 800-698-2411.
4. Carriers are not liable for delayed or undelivered messages
5. As always, message and data rates may apply for any messages sent to you from us and to us from you. Message frequency will vary. If you have any questions about your text plan or data plan, it is best to contact your wireless provider.
6. If you have any questions regarding privacy, please read our privacy policy: https://www.va.gov/privacy-policy/

We would also need an HTML anchor added to the section so we can share the terms directly via a URL.

## Collaboration cycle 
If you’re going through the collaboration cycle with the governance team, link to the ticket:
- **Ticket Number:** `xxxxxx`
- If you’re not going through the collaboration cycle, or you’re unsure, check here, and we can follow up: 
    - [ ] Not going through collab cycle

**Note**: We ask that you partner with us **before** scheduling your midpoint review, **to ensure** we can agree on a deliverable and that there's time for your team to make changes.  

### Phases Completed
**Check any phases you’ve already completed:**
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
  
## Supporting artifacts
Please provide links to any supporting artifacts we might need to begin work. This can include your product outline, user flows, mockups and prototypes, draft content, etc.
- [Supporting artifact <name>](https://va.gov) `placeholder link`

## Next steps
- [ ] Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.
    - A member of the CAIA team will aim to respond to your Slack message within 24 hours to acknowledge receipt - should we need any additional information regarding your request we will reach out to you to confirm.
    - The CAIA Operations group will meet to go over the info in your request and then reach out if we have any questions.
    - Depending on the request, it may make sense to schedule a kickoff meeting to better understand how we'll partner with you!
- [ ] Please review the remaining next steps in the **VFS Team Tasks** section, listed below.

## TASKS

<br>

```[tasklist]
### VFS Team Tasks
- [ ] If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
- [ ] If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+jilladams%2C+RLHecht&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.
```

```[tasklist]
### a11y Tasks
```

```[tasklist]
### Content Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74705
```

```[tasklist]
### IA Tasks
```

**Comment by laurwill** [comment]
Hi @jwowk I flagged this for @DanielleThierryUSDSVA because I know there's some broader work going on around terms of use on VA.gov. I'll update you as soon as possible!

**Comment by laurwill** [comment]
Hi again @jwowk , following up on this — Danielle said some SMS-related terms got added into the unified terms of use, so wanted to confirm with you if those updates resolved this issue. Let me know if there's still work needed here!

**Comment by jwowk** [comment]
@DanielleThierryUSDSVA can you provide a link to the updated terms so I can review?

**Comment by laurwill** [comment]
Whoops I meant to link! https://www.va.gov/terms-of-use

**Comment by laurwill** [comment]
Hi @jwowk , is there still work needed here, or can we close this ticket?

**Comment by jwowk** [comment]
@laurwill we can close. Thank you!
