### ISSUE TITLE
Synthesize Platform Satisfaction Survey Results

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#73352]
## Purpose
Close out the survey and perform the synthesis of the results

## Tasks
- [x] [Synthesize](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Quarterly+Platform+Services+Satisfaction+Survey#Conduct-Synthesis---WORK-IN-PROGRESS) Results and populate data onto new spreadsheet
- [x] Ensure any related documentation is current and updated

## Acceptance Criteria
- [x] Results are synthesized
