### ISSUE TITLE
Prepare presentation of Survey Feedback data

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#73351]
## Purpose
Prepare artifacts associated with the synthesis of the survey.  Our goal w/ this updated Survey is to be able to track changes qtr-over-qtr, and make these results easily accessed and absorbed by Leadership and Platform teams.

Communicating these on Demo Day and a Domo Dashboard will help:
1) Communicate data to Leadership & Platform teams
2) Tell the story over time of progress or not

## Notes
- Important to relay info in a way that Leadership understands its significance, and hopefully is actionable for them as well when it comes to prioritization.

## Tasks
- [x] Collect Q1 2024 data visualizations
- [x] Create new data visualizations to compare Q1 2024 vs Q4 2023
- [x] Prepare slide deck to present at Demo Day
- [x] Share with team for feedback
- [x] Process feedback from team
- [x] Make final adjustments to slide deck with any updated Domo visualizations

## Acceptance Criteria
- [x] [Confluence site is updated](https://vfs.atlassian.net/wiki/spaces/AP/pages/2629173255/new+Customer+Satisfaction+Survey+2023+and+beyond) and ready
- [x] [Domo dashboard](https://va-gov.domo.com/page/29110933?userId=1373762689) is ready
- [x] [Deck](https://docs.google.com/presentation/d/1YJUk4xaFYiJdYCeZZgkS5wt1Se96pOCJy3Plu-Vd5uo/edit#slide=id.p1) is ready to present for Demo Day

**Comment by tayism** [comment]
This will be rolling over to the next sprint due to a recent illness/out-of-office barrier.

**Comment by tayism** [comment]
This ticket is more of a 4/5 in terms of pointing. Will be helpful to break up Domo tasks next quarter.
