### ISSUE TITLE
Publicize Survey in Slack

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#73354]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey
[How-to-Launch documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)

## Tasks
- [x] Verify that Platform's [Survey page](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey#PlatformSatisfactionSurvey-ThesurveyiscurrentlyclosedRedforthisquarter.) is showing the Survey as OPEN.
- [x] Publicize Survey (Slack)
-draft messaging using the [how-to-launch](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Quarterly+Platform+Services+Satisfaction+Survey#Recruit-Participants) guide
-execute messaging
- [x] **Publicize in weekly #design meeting and thread**
- [x] Schedule reminders in Slack
- [x] **Obtain screenshot roles 'scorecard' from the previous quarter in [Domo](https://va-gov.domo.com/page/2036772922)**
- [x] **[Notify OCTO-DE](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3027468348/Status+Report+Assistance+from+OCTO-DE) the survey is open via #platform-quarterly-readout**
- [x] **[Notify VFS PMs](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3033858106/Assistance+from+VFS+PMs) the survey is open in ToT** (Bryan)

## Acceptance Criteria
- [x] Survey is socialized in Slack

**Comment by tayism** [comment]
Adjusting points from 1 to 2 as steps have been added to this process (in bold).
