### ISSUE TITLE
Close Platform Satisfaction Survey (after 4/11)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#73353]
## Purpose
Close out the survey and perform the synthesis of the results

## Tasks
- [x] Close Survey in Optimal Workshop
- [x] Update Platform page to Closed status
- [x] Update Confluence page to Closed status

## Acceptance Criteria
- [x] Survey is closed
- [x] Pages reflect closed status
