### ISSUE TITLE
EVSS PCIU Migration: Remove calls to PCIU and PCIU_Address in 526ez pre-fill

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#73362]
## Issue Description
In 526ez's custom [pre-fill](https://github.com/department-of-veterans-affairs/vets-api/blob/81e325eebaa92b3fbb1a9a938a9c60c8572fd454/app/models/form_profiles/va_526ez.rb#L79), we are calling PCIU and PCIU_Address (a service that is a wrapper around PCIU) in order to [pre-fill contact information](https://github.com/department-of-veterans-affairs/vets-api/blob/81e325eebaa92b3fbb1a9a938a9c60c8572fd454/app/models/form_profiles/va_526ez.rb#L130) when a user starts a new application. We first call VA Profile for this information, and if it exists, we use it instead of any PCIU information that was returned. Since VA Profile now seems to be the de facto source of contact information at the VA, there should be no need for PCIU here at all, and so should be removed.

## Docs
- [PCIU discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/evss-pciu-migration-discovery.md) (esp this [section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/evss-pciu-migration-discovery.md#526ez-mailing_address-pre-fill))

NOTE: regardless whether or not we trust VA Profile, we should NOT be making extraneous calls to PCIU if VA Profile data was returned. An alternate version of this story could simply be to correct that behavior, which would minimize calls to EVSS

## Tasks
- [x] Create and use a flipper flag (in case VA Profile proves to be insufficient)
- [x] Create follow-up story to remove flipper flag 
- [x] Create follow-up story to create release plan
- [x] Create follow-up story to canary launch to test the contact info being  populated correctly from VA Profile
- [x] Create follow-up story to turn off logging
- [x] Create/modify unit tests as needed

## Acceptance Criteria
- [x] Remove PCIU calls in [initialize_veteran_contact_information](https://github.com/department-of-veterans-affairs/vets-api/blob/81e325eebaa92b3fbb1a9a938a9c60c8572fd454/app/models/form_profiles/va_526ez.rb#L130)
- [x] Check if the same information comes back from PCIU and VA Profile without the flipper
- [x] Logging in production to show if the email and phone number and mailing address is being populated via VA Profile or PCIU

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Created follow-up stories:
- [EVSS - Release Plan for PCIU - 526ez Prefill #74417](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/74417)
- [Canary Launch for 526ez Contact Info Pre-fill #74216](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/74216)
- [EVSS - Remove Flipper flag and Logging for PCIU - 526ez Prefill #74462](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/74462)

Other wrap up notes
- 2 prefill calls are made per session: one from either /introduction or /start (navigation depending), and one from the following page /veteran-information
- When the phone number (and/or the email, presumably) is missing, the application asks for you to update both (though phone number is not required. However, as was the case with staging user 99, the application considers plus-addressing to be invalid, even though a plus-address was pre-filled. If plus-addressing is already forbidden upstream from the application, then this is a "bug" specific only to our test environment. It might be worth validating that that is indeed the case in production- otherwise, the user may be stuck at this point (since email is required)
