### ISSUE TITLE
Design | Enhanced Military Info | Research plan

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#73363]
## Background
We've gone through design intent and refreshed our designs incorporating the must feedback.  We should start to prepare for research. 

## Tasks 
- [x] Write [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2024-01-military-info-enhancement-mvp/research-plan.md)
- [x] Review/share with PM & PO
- [x] Incorporate feedback

## Acceptance Criteria 
- [x] Plan is ready to submit and kick off the research (along with #74208, which is not yet done)

**Comment by andaleliz** [comment]
@pamela-drouin wanted to share a couple things while they're fresh from working through design intent feedback. I think they're obvious but just want to get them out of my head :) 
- it'd be great if through this research we can learn how to better organize the page and structure headings
- It'd also be very helpful if we can figure out how to label the "show more" button in a way that is specific but brief, and could make sense across branches. Tall order, I know.  Here's a bit of background convo about this, starting with [this comment.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73138#issuecomment-1885635568)
- For whatever it's worth, I'm really torn between which of the [latest designs](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/p/0D656B7A-B307-4C26-B5E9-9F4E426EDD40/canvas) we should move forward with. I'm not sure if you have a strong opinion about either one, or how you plan to incorporate them into the study.

**Comment by andaleliz** [comment]
@pamela-drouin this is so exciting to see! The plan makes sense to me, just a few points of feedback/comments:

### Background
> As a result of this request, we're adding duty status, dates, and military occupation specialties (MOS) to Profile, since these data elements have the best quality at the moment.

Might want to be more specific about which dates you’re talking about, since we do already include dates of service.

Also, there is a separate project brief for this specific MVP version. It took me forever to figure that out so not sure if you are aware. I think linking to either one is fine.

### Outcome
You have captured this so perfectly!

### Research questions
> How useful is including the start date of each occupation specialty? What about end dates?

I’d be curious to know this for deployment locations too. I don’t know that we have accurate data for this but it’d be good to learn more about expectations here.

### Methodology
> This research study mixes the generative and evaluative methods of interviewing, [card sorting? mapping? brainstorming?], and concept testing [it’s not really a usability test in my mind].

- I’m not sure how to label it either! I think leaving it at “generative and evaluative methods” is fine; people will get it once they see the conversation guide
- I agree with you - I think a concept test is the right name for what we’re doing.

> [Link to mock-up](url goes here) – Probably should migrate this to Figma...

I’m planning on migrating this over and cleaning it up once I’m done with the other things that are already in progress 

### Recruitment criteria

> 50% must have served overseas

⠀So smart of you to include this.

#### Screener questions
> I have nothing yet here – the only screener question I can think of is for the PACT Act – everything else seems like it would be covered under primary criteria in the Recruitment Request form, no?

I think you’ll need one for the PACT act and also for overseas.  For overseas, it *might* be interesting to also add a text box asking them to list where they served, as part of gathering data about how they talk about their service history.  I’ve seen some *weird* locations in the deployment data that I would be shocked if Veterans self-reported in the same way they show up from DoD.

**Comment by pamela-drouin** [comment]
@mtcA6 @Samara-Strauss @andaleliz -- I've incorporated initial feedback from Liz into the draft research plan. It is now ready for team review!

**Comment by Samara-Strauss** [comment]
This plan looks good to me.

One thing that might make things challenging -- I don't know how many Space Force veterans there are at this time since the branch is relatively new, so I just wanted to flag this. It might be an issue, it might not. If they can not get us Space Force veterans, then let's just pursue the other branches.

**Comment by pamela-drouin** [comment]
@Samara-Strauss, I agree this might wind up being challenging! I figure it can't hurt to try, and as long as we get Air Force coverage, the codes are similar enough that it should be a good enough substitute.

**Comment by mtcA6** [comment]
Agree the plan looks great! excited to see the convo guide
