### ISSUE TITLE
Investigate PPIU v0 controller activity directing to EVSS

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#73366]
## Issue Description

Flagged in thread here: https://dsva.slack.com/archives/C04KW0B46N5/p1704897871408249

Tom noticed that the v0 PPIU controller is directing traffic to EVSS. The referrer is: `/disability/file-disability-claim-form-21-526ez`. This is unusual because our current PPIU migration only relates to submit activities. However, since the referrer is the 526 form, we need to verify that we didn't miss anything, or that we aren't the cause of this activity

The controller in question: https://github.com/department-of-veterans-affairs/vets-api/blob/1eabe00c3481e0a3c0a661a5cb382212be9c0e01/app/controllers/v0/ppiu_controller.rb

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Identify cause of this issue
- [ ] Fix in the current roll-out, if this is caused by the migration work
- [ ] If not caused by migration but by 526, create a ticket for a fix

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
