### ISSUE TITLE
[QA] 10-10EZ - Household: Run a sample of test cases after URL migration

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#73386]
## Background
When we launched the Household section optimization work, we had to maintain the Original and the V2 URLs, since both were live at the same time.  Now that we are fully using the new Household section pages, we need to migrate them to the original URL structure (removing V2).

In ticket #73237, discovery was completed to outline a plan for migrating the household section of the form into the URL format that is consistent with the rest of the form, essentially removing the reference to "v2".

In ticket #62517, the URL migration was completed.  We now need to run a few test cases to ensure functionality is still working as expected.

## Tasks
- [x] Run test cases C, E and F from the [test outline document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Household%20section%20redesign/Staging%20Review_QA/Household%20Section%20Optimization%20Use%20Cases.md)
- [x] If issues are found, contact Chapley for troubleshooting and resolving the defect
- [x] Once all test cases are completed successfully, inform the team

## Acceptance Criteria
- All test cases are run successfully and we feel confident to release to production

**Comment by hdjustice** [comment]
Test cases were run, as well as in-progress test users were used to ensure they are directed to the new URLs.  We are a GO for production
