### ISSUE TITLE
Content review on Form 20-10206 to resolve Collab Cycle edits (POA and third-party rep content)

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#73384]
## Issue Description

From the intake ticket:

> Right now: There's an additional-info component labeled “How do I request personal records for someone else?”. The content exists on the intro page, and on the first step of the form where the authenticated user self-identifies.
> 
> Based on the DS guidance, there’s too much content in the details of the component and we should either
> 
> 1. Reduce the content,
> 2. Choose a different component, or
> 3. Point to another page where the user can learn more about the requirements
>
> After considering the options and discussing with Megan Zehnder (@megzehn) here's where we're at:
> 
> 1. Reduce the content
> Reducing the content might be possible, but it’s already fairly straightforward and written in accordance with plain-language standards (this is CAIA-approved content).
> 
> 2. Choose a different component
> We’ve mocked-up a version with accordions, and we’re concerned it would then occupy more space than necessary on the page itself, and since the content doesn’t apply to the folks who are eligible to complete the online form, we don’t want to distract or overload them with unnecessary details. For the folks who need it, we want it to be discoverable, but we don’t want to add more cognitive load to the audience that’s here and ready to start working on their request.
> 
> 3. Point to another page where the user can learn more about the requirements
> This may be the ideal route, but CAIA needs more time to look into the LOE to stand-up a static page that this and other forms could point to when it’s necessary to educate folks on how to become an authorized third-party representative or power of attorney

---
## Tasks
- [x] Add forms to ["signing for someone" sheet](https://docs.google.com/spreadsheets/d/1ZQvpRfuaPmRCGQwfQWgdt2cuTDWIOTQQ_iwcdfwmRoI/edit#gid=0) (Megan/Laura)
- [x] Document how different forms talk about "other" people signing (Derek)
- [ ] Assess content and make edits
- [ ] Review with Megan
- [ ] Share with stakeholder

## Acceptance Criteria
- [ ] Feedback provided in intake ticket
---

**Comment by megzehn** [comment]
Update: @d-beyer and I are meeting Thursday 2/1 to discuss this. This content is currently on many other forms ([like 1010D for example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/1010D/sourceoftruth_with_stories.md#step-1-of-4-signer-information)), so we'll want to align with Laura and Aliyah on how we approach this!

**Comment by megzehn** [comment]
Update: we met and started talking through this problem on this [Mural page. ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706803584498/86ffda087212b564f2578261af115768ec47b22e?sender=ud96213c0f6200ee8fda12457)

@d-beyer is going to start documenting how different forms talk about "other" people signing in this [excel sheet.](https://docs.google.com/spreadsheets/d/1ZQvpRfuaPmRCGQwfQWgdt2cuTDWIOTQQ_iwcdfwmRoI/edit#gid=0)

**Comment by d-beyer** [comment]
@megzehn I filled in the info for the forms listed in the sheet and added a few that I found as I was working.

**Comment by megzehn** [comment]
Update: I submitted follow-up edits for 20-10206 and shortened the copy we had for people signing forms on behalf of someone else. This is a temporary solution until we can answer a few more questions (When should someone fill out an alternate signer form versus an accredited rep form? Do we want to move this content to a static page? Is there a consistent experience for people signing on behalf of others that we can capture in a static page?) 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72934749/10905602-f931-4e57-93f9-1642188f191c)

Next steps:
- summarize current discrepancies based on what @d-beyer's been tracking [here](https://docs.google.com/spreadsheets/d/1ZQvpRfuaPmRCGQwfQWgdt2cuTDWIOTQQ_iwcdfwmRoI/edit#gid=0). 
- bring this language to our style guide sync and figure out next steps for iterating on it (CC @laurwill)

**Comment by d-beyer** [comment]
@megzehn I've added a second sheet to the spreadsheet that digests the original text a little bit further. I think it's now pretty easy to see what overlap and discrepancy there is.

The most common terminology is "third party representative or power of attorney". Different forms seem to be splitting or piling different things under those two terms. Let me know if you'd like to hop on a call at some point to talk through this.

**Comment by megzehn** [comment]
Thank you, @d-beyer!! I just added this to our agenda for the next forms style guide huddle (on 4.18), so we can talk through this more and figure out how to best approach it for online forms.

**Comment by megzehn** [comment]
Note that this work is being replaced by [the submitter pattern](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/11?filterQuery=assignee%3Amegzehn++submitter&pane=issue&itemId=90748284&issue=department-of-veterans-affairs%7Cva.gov-team%7C99034)!
