### ISSUE TITLE
Update deprecated Github link on 'PDF Generation' page

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#73390]
### Description:
Currently, there is a link on the [PDF generation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/721780786/PDF+generation) page that links links to a [deprecated github page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/vets-website/form-tutorial-basic.md). We need to fix that. This ticket involves locating the correct page to link to, and making the edits on the PDF Generation page.

## Tasks

- [x] Identify proper page/document to link to
- [x] Make edits on the PDF Generation page
- [x] Prepare page for deployment
- [x] Deploy page to Platform Website

## Acceptance Criteria:

- [x] Links has been updated to a non-deprecated page

- [x] Edits have been deployed

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/73390?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
Waiting guidance from Platform Product team

**Comment by jknipes** [comment]
Lindsey Hattamer provided: 

1. "I've updated the link to point to an existing page in vets-website, but it seems maybe the doc is/should be moved to Platform website. I cannot find a corresponding doc on the Platform website. I would say the information is domain knowledge of a FE developer. Please follow up with someone on the FE."
2. "I'm not aware of where this new page could be, but I would recommend resurfacing it if a newer document doesn't exist elsewhere. A FE dev would be the SME in this case."

**Comment by jknipes** [comment]
@laucon is there a dependency with [74507?](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/74507)

**Comment by laucon** [comment]
@jknipes No there is not. It's not like it's dependent on any other task. Adrian just thought of the idea for the edit because we were discussing the PDF Generation document.

**Comment by jknipes** [comment]
Link updated per this [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1706201808926989).
Updated page deployed, closing ticket.
