### ISSUE TITLE
Find a Rep: update copy, layout and move definitions to additional components 

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#73405]
## Background
We have updated copy from CAIA for various areas of Find a Representative.  This ticket is focused on the initial state, before the search has been imitated.  

[Link to prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&type=design&node-id=120-67785&viewport=-4254%2C3160%2C0.25&t=Lb19zccIpkRz5SdZ-1&scaling=min-zoom&starting-point-node-id=456%3A169444&show-proto-sidebar=1) for an interactive experience
[Link to CAIA content doc](https://docs.google.com/document/d/1C3up542aM1XsqmyEq7UMZWFrODH1QtDOBXeRzXhlQqo/edit) for easy copy/pasting of the most up-to-date recommendations

<img width="228" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzY0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3299f19c48c12c53805e1c26579f6fe2925aaac/image.png" alt="image.png" />

## Tasks
- [x] Update copy in paragraph below h1
- [x] Update h2 
- [x] Add two "additional components" below the h2 for the rep definitions
- [x] Update rep definition copy for each additional component
- [x] Remove original accordion with rep definitions in the accordion
- [x] Move the radio group below the two "additional components" with rep definitions
- [x] Update radio group copy
- [x] Update location input copy
- [x] Update name input copy
- [x] Remove magnifying glass from Search button / Update to standard v3 design pattern 

## Acceptance Criteria
- [ ] The initial state of Find a Representative in Staging matches the [design in Figma](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&type=design&node-id=120-67785&viewport=-4254%2C3160%2C0.25&t=Lb19zccIpkRz5SdZ-1&scaling=min-zoom&starting-point-node-id=456%3A169444)

**Comment by cosu419** [comment]
Immediately after merging I caught that the va-additional-info components are not split into multiple paragraphs. This change has been added but will appear in a later PR. 

Design:
<img width="431" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9DQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--270729cb309125179ffd481197ec56910edbf38c/image.png" alt="image.png" />

Current PR:
<img width="446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cf4d618cd6212efee24bc0494c7c19e6671bcbc/image.png" alt="image.png" />

Next PR:
<img width="455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3JDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58358ee67e7426a8a25b644cc783b3a2d00d85eb/image.png" alt="image.png" />
