### ISSUE TITLE
BE | Profile | Direct Deposit | Email Job Sidekiq Queue Exhaustion

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#73409]
## Background
When a veteran's C&P direct deposit information is updated, an email is sent to notify them of the change.

The email is sent using a background job called `VANotifyDdEmailJob`.  Datadog monitoring shows that some jobs are not being completed due to retry exhaustion. 

The purpose of this ticket is to understand why some jobs are failing due to exhaustion in the Sidekiq queue.

## Tasks
- [ ] Add error handling to `VANotifyDdEmailJob`.
- [x] Obtain access to the Sidekiq Admin UI in production.

## Acceptance Critiera
- [ ] Ensure that job errors are being properly logged in Datadog.
- [ ] Identify what is causing the error and determine next steps.

**Comment by tpharrison** [comment]
Made request for Sidekiq Admin UI production access - https://github.com/department-of-veterans-affairs/va.gov-team/issues/73466.
