### ISSUE TITLE
Pension Team Sprint 12 Plan: 01/17/2024—01/30/2024

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73414]
## Sprint 12: 01/17/2024—01/30/2024

**- Outages (PTO, holiday, or unplanned):** 
-- Jan 19: Todd
-- Jan 25, 26: Anh at SAFe training
-- Jan 26 - Feb 6: Steve Albers

## Theme(s):

- e2e testing
- Attend staging review
- Address any launch-blocking issues
- Launch form to production
- Monitor release data in Datadog, DOMO, Contact Center

## Notes:
- Add task related to Cypress testing scenarios and assistance from FE
 
## Goal(s):

**RESEARCH/DESIGN**

- [x] Create Pension form usability testing plan #73620
- [x] Move Pension designs to Figma #73188 - **Due date 1/23**
- [x] Document design debt for FE engineering #73621
- _Updates to design artifacts from MVP; various cards exist for this already_

**PLATFORM STAGING REVIEW**

- [x] Staging review: Create launch-blocking issues and prioritize backlog tasks for post-MVP #73597

**QA/TESTING**

- [x] Perform e2e testing with VA enablement team #73625
- [x] Perform e2e testing with Veteran VA employees in production #73626

**ENGINEERING**

**_Frontend_**

- [x] [MVP] Prepare and launch copy changes for How to Apply page for MVP release #73478
- [x] [MVP] Step 5 Gross Monthly Income: Update question format for Gross Monthly Income recipient question #73161
- _Launch-blocking FE tasks_
- _Any post-MVP FE work; various cards exist for this_

**Backend**
- [x] [PDF Mapping] Map online form fields to new PDF for Section 6: Marital Status and Spouse Info #70390 **(rollover, PR pending)**
- [x] [PDF Mapping] Map online form fields to new PDF for Section 7: Prior Marital History #70392 **(rollover, PR pending)**
- [x] [PDF Mapping] Map online form fields to new PDF for Section 8: Dependent Children #70393 **(rollover, PR pending)**
- [x] [PDF Mapping] Map online form fields to new PDF for Section 9: Income and Assets #70394 **(rollover, PR pending)**
- [x] [PDF Mapping] Map online form fields to new PDF for Section 10: Info About Unreimbursed Medical Expenses #70395 **(rollover, PR pending)**
- [x] [MVP] Update vets-json-schema #71917  **(rollover, PR pending)**
- _Launch-blocking BE tasks_
- [x] Turn on/test flipper to production on Jan 22 #73629
- [ ] Increase traffic to production for Canary testing #73630
- [ ] Increase traffic to production to 25% of traffic #73631 - _dependent on success of canary_

**LAUNCH MONITORING**
- [x] [MVP] Setup DataDog alerts for both retry and queue exhaustion #70462 **Rollover, in progress**
- [ ] Notify Contact Center of release to product (Canary release) #73615
- [ ] Daily monitoring of Pension MVP launch in GA/DOMO #73616
- [ ] Daily monitoring of Pension MVP launch in Datadog #73197
