### ISSUE TITLE
Update VA Forms Library Save Page (content edits for #73344)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#73413]
### Description & Background
Content edits for [footer request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73344)

### Content Changes
> 
> The second bullet should now refer to the VA_FORM_IDS object in the /platform/forms/constants file instead of In the personalization dashboard helpers file since the information now all resides in that file.
> 
> **The secondary bullets should be updated as follows:**
> formBenefits has been renamed to FORM_BENEFITS
> formLinks has been renamed to FORM_LINKS
> trackingPrefixes has been renamed to TRACKING_PREFIXES
> sipEnabledForms has been renamed to SIP_ENABLED_FORMS

> The links present in the bullet points for these variables should also be updated to point to the respective line numbers within https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js

## Tasks
- [x] Make edits to  based on guidance from VFS Engineer
- [x] Prepare page for deployment
- [x] Page has been deployed

## Acceptance Criteria
- [x] Edits have been made on the [appropriate VA Forms Library page](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si)
- [x] Page has been deployed

**Comment by johnny-jesensky-adhoc** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/73413?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by taylojill** [comment]
Sent message to the requestor stating I would check back soon (after I review the request).

**Comment by taylojill** [comment]
Updates complete. I sent a message to requestor asking for review and approval.

cc @jknipes

**Comment by taylojill** [comment]
Page updated, checked for launch-blocking issues, ready for deployment.
