### ISSUE TITLE
Engineering Team page: Remove Header Links and Correct Any Issues

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#73416]
## Issue Description
Working With The Engineering Team page in Confluence seems to have a link in the header, though this is not deploying as such onto Platform Website. This however could be an issue if we discover active links in page headers.

### Tip of The Sprint regarding this issue

- [HERE](https://dsva.slack.com/archives/CL181NRJQ/p1707156000582989)

### Style Guide mention
- [HERE](https://vfs.atlassian.net/wiki/spaces/AP/pages/622362663/Formatting+and+organization#Formatting-page-titles-and-headings)

## Tasks
- [x] Review and edit [Working with the Engineering Team](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887141893/Working+with+the+Engineering+Team) to change all of the weird things in the doc, including the link in the header
- [x] Add tips about not having links in headers into the style guide

---
## Acceptance Criteria
- [x] Header links in this document are removed
- [x] Launch blockers and style guide violations corrected
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@BSmolensky this seems to relate to the recent Tip Of The Sprint and style guide update regarding links in headers. OK to close?

**Comment by jknipes** [comment]
This Discovery ticket not part of midterm priorities, moving to Icebox

**Comment by laucon** [comment]
This ticket by itself could be a 2, but we'd also need other tickets if we want to check for more headers like this and/or add stuff to the style guide about not having links within headers

**Comment by laucon** [comment]
This is done and can be closed.

**Comment by jknipes** [comment]
Work has been completed, moving to _Closed_
