### ISSUE TITLE
Edit: Authorization Design

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#73415]
## Issue Description
Health Quest Service and Authorization Design Doc and many other documents in Confluence use personal names. This is not appropriate on the Platform website because human beings change jobs all the time, making documents go quickly out of date.

## Tasks
- [x] Review style guide guidelines
- [x] Find out Slack channel or other venue for contact vs. a person and use in document
- [x] Look at and edit [Authorization Design Doc](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887338517/Authorization+Design+Doc) and 

## Acceptance Criteria
- [x] This page been updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laucon** [comment]
Clarification: these two documents and many other documents have human beings' names. This is not appropriate on the Platform website because human beings change jobs all the time, making documents go quickly out of date.
1. We should do a full audit of all documents with human beings' names and get rid of human beings' names in all those docs.
2. We should also add text to the style guide to say to not mention humans' names and to mention job titles instead, if that's necessary and if that isn't already in the style guide.

**Comment by jknipes** [comment]
@laucon on the Health Quest Services page you may want to confirm with @LindseySaari whether to keep the contact name

**Comment by laucon** [comment]
This is done and we can close it. :)

**Comment by jknipes** [comment]
work is completed, moving to _Done_
