### ISSUE TITLE
Update 'Get Access to Datadog' Doc

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#73419]
### Context
This is related to our recently updated instructions on [requesting access to Datadog](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/71832).

### Description
The team that manages Datadog access recently changed from DOTS, to ECC.

## Content Changes
**Page 1:** [Get Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)

We received some [feedback from a VFS engineer](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/72256) (see comments) after our most recent changes to this page, 

> "_My only note of feedback is that **you might want to update the hosting location section to be more generic.** The requestor would need to know what datadog application they are requesting access to and to list that and/or any others they may need access to. Totally fine to use vanotify and the others as examples, but they'll all be named by product._"

Look to rephrase the guidance underneath **'Hosting Location'**

### Related ticket 
on [Reliability board](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/74881)

## Tasks
- [x] Review ticket 
- [x] Reach out to the Reliability Team for guidance - [LINK](https://dsva.slack.com/archives/C04B87D2QLS/p1710951134644319)
- [x] Create [Draft](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3035791361/73419+-+Cheryl+-+Copy+of+Get+Access+to+Datadog) of Get Access to Datadog
- [x] Edits have been reviewed and confirmed
- [x] Edits have been made on the [Get Access to Datadog ](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)page
- [x] Pages have been prepared for deployment
- [x] Pages have been deployed

## Acceptance Criteria

- [x] Edits have been reviewed by an engineer, or related SME
- [x] Updates have been deployed to the Platform Website

**Comment by jknipes** [comment]
Related ticket on [Reliability board](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/74881)

**Comment by BSmolensky** [comment]
Ticket Originator and SME is OOO until the 22nd of March.

**Comment by jknipes** [comment]
@CherylEvans please put draft language in this ticket to start

**Comment by CherylEvans** [comment]
@jknipes FYSA - I created a [Draft](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3035791361/73419+-+Cheryl+-+Copy+of+Get+Access+to+Datadog) of Get Access to Data Dog. Once I connect with Joe Tice on the language edits, I will make the changes to the draft. I'll keep you posted.

**Comment by CherylEvans** [comment]
@jknipes I reached out to Joe Tice on Slack. [Link](https://dsva.slack.com/archives/C04B87D2QLS/p1710951134644319)

**Comment by CherylEvans** [comment]
@jknipes I touched base with Joe T today. He is working with Peter Hill to find a viable solution. They will get back to me with an update.

**Comment by CherylEvans** [comment]
@jknipes Joe Tice's comments ([Slack link](https://dsva.slack.com/archives/C04B87D2QLS/p1711397185197719?thread_ts=1710951134.644319&cid=C04B87D2QLS)): Hi Cheryl... So, for the addresses, I was not able to get any good info on, so the list is similar to what's in the ticket, I'd just suggest not having a specific one identified for them to use, and just list the ones we know of
vagov.ddog-gov (this is the platform's)
vanotify-va-datadog
vetext-va-datadog
vagov-va-datadog

I will update the draft and submit to Joe for his final approval.

**Comment by CherylEvans** [comment]
@jknipes I updated the draft with the following([Slack link](https://dsva.slack.com/archives/C04B87D2QLS/p1711398278196749?thread_ts=1710951134.644319&cid=C04B87D2QLS)): 
Hosting Location:
Request access to the vanotify-va-datadog application (Platform) or
If you need access to other apps you can also list those:
vetext-va-datadog
vagov-va-datadog
vagov.ddog-gov

I'm waiting for Joe's approval.

**Comment by CherylEvans** [comment]
@jknipes Joe approved the changes. [Link](https://dsva.slack.com/archives/C04B87D2QLS/p1711398278196749?thread_ts=1710951134.644319&cid=C04B87D2QLS)

**Comment by CherylEvans** [comment]
I'll close the ticket later today once the updates are published.

**Comment by CherylEvans** [comment]
We are experiencing a work delay due to a Confluence outage:
Confluence is currently experiencing an outage: https://confluence.status.atlassian.com/
confluence.status.atlassian.comconfluence.status.atlassian.com

**Comment by CherylEvans** [comment]
Confluence is working as expected.

**Comment by CherylEvans** [comment]
Updates deployed to the Platform.
