### ISSUE TITLE
DS Logon Template 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#73427]
## Issue Description
_Create a DS Logon template to assist Veterans with resolving DS Logon issues

---
## Tasks
- [ ] _Draft template language to address challenges when accessing DS logon issues. 

## Acceptance Criteria
- [ ] Proof and approve template
- [ ] Publish template for use. 
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
