### ISSUE TITLE
DS Logon Template 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#73428]
## Issue Description
_Create a DS Logon template to assist Veterans with resolving DS Logon issues

---
## Tasks
- [ ] _Draft template language to address challenges when accessing DS logon issues. 

## Acceptance Criteria
- [x] Proof and approve template
- [x] Publish template for use. 
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Dependent on User guide from the transition team.

Closed until further action is required.

**Comment by ATMiddleton** [comment]
@starlow00 will review if template is required. 

Template

**Comment by starlow00** [comment]
Template created and shared with the team in Teams and AVA.

Will adapt into QRG material later.
