### ISSUE TITLE
Design + FE | Authenticated Menu | Add disability rating - build Codepen prototype

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#73453]
## Background
We need to create a prototype for our upcoming study. The sitewide team has already shared a couple of pens, and here's the complete list of what we'll use from them:

- Unauth header
- Auth header
- [The page people will sign in from on their prototype](https://cdpn.io/pen/debug/gOEPoyo/43fa8051200887cb97f5b154ed54c8a3)
- A mock sign in flow (this may be 2 separate pens)
- [Signed-in version of My VA](https://cdpn.io/pen/debug/NWJNqGO/8943def52b93fcf8e4da03588cfe4d4b) (not sure we'll use this but nice to have)
- Footer
- [An unauth dummy page we can use so to avoid empty href values that confuse screenreaders.](https://cdpn.io/pen/debug/dyrMYdw/3f982de58cda384c4178f7d34235fe46)
- Pens for background things like CSS, meta tags, etc

**Auth menu link order:**
My VA
My HealtheVet
Profile
Disability rating
Dependents
Letters
Sign Out

## Tasks
- [x] **Create a Profile hub page pen with authenticated header and name tag.** All links can point to the dummy page 
- [x] **Create a View Disability page pen with authenticated header.** If it's easy to copy/paste from prod to create a realistic page, that's wonderful. If not, we can simply have an `h1` that says "view disability rating" and "Thank you, please wait for the moderator." underneath.
- [x] **Create a Download benefit letters page pen with authenticated header.** If it's easy to copy/paste from prod to create a realistic page, that's wonderful. If not, we can simply have an `h1` that says "VA letters and documents" and "Thank you, please wait for the moderator." underneath.
- [x] Swap the header on the dummy page the sitewide team provided to use the auth version
- [x] Add the view disability rating link to the auth header, pointing to the code pen page. 
- [x] Update the links in the header pens to point to the profile hub, letters, disability page pens we create
- [x] Determine the best way to make sure the user name in auth header can be changed on the fly. Maybe it's as easy as updating the HTML, or perhaps we need to pass in some kind of variable.

I think we'll also need to:

- [x] Set up a base CodePen to use the pens core pens we'll need for everything: header(s), footer, and the background pens.

### If there is time
These would be icing on an already very awesome cake, and are listed in priority, only if things go super fast and smooth and we have extra time.
- [ ] **Create a Contact information page pen with authenticated header and name tag**. If it's easy to copy/paste from prod code to create a realistic page with static data, that's wonderful. If not, we can simply have an `h1` that says "Contact information" and "Thank you, please wait for the moderator." underneath.
- [ ] Update the contact information link on the hub page to point to this code pen.
- [ ] An abbreviated version of the VA.gov homepage with the unauth header, to give people a more realistic starting point.
- [ ] An abbreviated version of the VA.gov homepage with the auth header
- [ ] Link the logo in the header to point to the auth header homepage if it exists, or the unauth one if it doesn't.

## AC

- [ ] Prototype is ready for research
- [ ] Liz has added link to prototype to the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/authenticated-menu-usability/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/authenticated-menu-usability/conversation-guide.md).

**Comment by andaleliz** [comment]
@adamwhitlock1 I don't know that I've communicated our timeline to you at all, so wanted to drop a note about that here.

We're hoping to do our pilot session on 1/24 or 1/25, and conduct research on 1/29. If that's totally impossible from your perspective, that's fine! Just let us know what would be more feasible and we can adjust.

With those target dates, we need to kick off recruiting by 1/18 at the latest, and need a prototype link to drop into the research plan. It's fine if it's still a work in progress, I just need something to show as a starting point.  

Thoughts?

**Comment by andaleliz** [comment]
@adamwhitlock1, @laflannery let me know they're making a change to their prototype:

>We are going to change our sign in flow so that when you "sign in" you are taking to our homepage (the life insurance page) now instead of the MyVA page. I feel like Adam was grabbing our files and not using links to ours but jsut in case I wanted to make sure you knew in case this messed you all up

@laflannery if there are any more changes, this ticket is a good place to keep us both in the loop.

**Comment by adamwhitlock1** [comment]
Main collection of pages are here: https://codepen.io/collection/yreyZJ

Working on getting My VA added and the scripts/css dependencies moved from the Site-wide's codepen assets to ours

I've created a way to change the name and disability rating without having to edit the HTML manually, and instead update a js file with the variables at the top like this:

![Screenshot 2024-01-18 at 12 51 28 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/d7c685ed-62a3-4534-b1c2-3340e459a26e)

But right now this lives in basically every page's pen, so looking at a way to have a 'base' pen with this stuff and that be the only place where you would have to edit it.

**Comment by adamwhitlock1** [comment]
Added the Insurance page (authenticated and unauthenticated), and My VA to the collection. Now the authentication flow works and most pages are linked to each other:

Tasks still to finish:

- Update all titme tags on pages if needed
- Make sure header is consistent (form of the copying from the other teams pens could have brought over their header, but I think I got most of them subbed out)
- Continue work on a strategy for substituting dynamic data to make this more reusable. I'm thinking a single pen where that data can be edited and all pens use that to set name, after auth route, disability rating, or anything else that we think should be editable.
- Side thought: its messy dealing with all these pens because they all have cryptic urls, can reference each other, and have the potential for a lot of repeated code. I wonder if the 'project' feature of codepen could be used to make this better. I'm going to investigate.

**Comment by adamwhitlock1** [comment]
@andaleliz I think I have the main items completed if you want to take a look at the main pages.
I think I can get some of the extra items done here in the next day or two.

**Comment by andaleliz** [comment]
@adamwhitlock1 this looks AWESOME!! Thank you!  I reviewed it starting from [the unauth life insurance page](https://cdpn.io/pen/debug/JjzNWbR). There are just a couple small things:
- I think the logo and text in the header are linking to the Sitewide teams unauth life insurance page. Can you update the unauth header to point to the unauth life insurance page prototype, and the auth header to point to the auth life insurance page?  Side note: I'm torn about whether the dummy page makes more sense, but I'm going to see how the pilot goes before changing that aspect.
- When you have the auth menu and main menu open, the main menu is on top. Can we update order so the auth menu sits on top if both are open? That's the current behavior on prod, and I think a better UX.

If you have time to get to the bonus items, that would be terrific! But I feel like we're in such good shape and I could run a session right now if I had to. Thanks for all your work on this!

**Comment by adamwhitlock1** [comment]
I updated the links for the authed and un-authed menu, so those should now point to the respective insurance pages.

For the menus, I changed up the z-index so the auth menu sits on top. @andaleliz  Would it make sense to connect a 'click off menu' handler for either menu so that the menu closes when you click outside of it?

**Comment by andaleliz** [comment]
@adamwhitlock1 thank you! `z-index` is the property I could not think of last week 😆  

Yes, I think that handler sounds like a good idea.

**Comment by andaleliz** [comment]
Hi @adamwhitlock1! Just wanted to send an FYI - [Cindy told me about some small changes they're making to their prototype in Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1706055332157079). I went ahead and updated the link on the insurance page as suggested, and went through the prototype and updated other links (breadcrumbs + links on My VA) pointing outside the prototype to point to our thank you page. I think that will minimize the feather ruffling that could happen during a session.

The one thing I'm not sure about is the `aria-label` she mentioned for the VA seal. @laflannery can you share details here about the value you're adding for the label so we can add it to ours too? Thanks!

**Comment by laflannery** [comment]
@andaleliz From our first pilot session today (which I was not at unfortunately) there seemed to been an issue with JAWS reading out the header logo link. It was only reading "VA Seal U.S" and then stopping, almost like it was viewing the dot as a sentence period. The fix I proposed was adding an `aria-label` that didn't include the periods so JAWS would continue reading the full link text.

However, this morning I was not able to recreate this no matter what I did, nor was another specialist and I typically only use `aria-label` when absolutely necessary which I'm not not sold on in this case. So for now, I haven't changed anything. I have asked for more specifics from the pilot participant and if I do get any info and am able to recreate this and decide to change/add anything I will let you know.
