### ISSUE TITLE
Fix maintenance banner

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#73465]
## Description
Fix the maintenance banner that is displayed on the Sign in Modal and Sign in Page (USiP) so that a failed response from `/backend_statuses` (status code 500) displays the maintenance banner

## Tasks
- [x] Investigate which maintenance banner the identity team uses
- [x] Update vets-website so that a 400/500 or other error codes returned from `/backend_statuses` displays the maintenance banner
- [x] Update unit tests as needed
