### ISSUE TITLE
Shadowing Research: Documentation 

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#73467]
## Issue Description
- Now that we have completed [Veteran Shadowing Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2023-11-Shadowing-Research), we need to make sure all documentation is correctly archived so it is easy for current and future teams to reference the research. 
---
## Tasks
- [x]  (Nichole) Convert report to Github document 
- [x]  (Nichole) Put Murals in the proper folder
- [x]  (Evelyn) Accessibility pass on the Google doc report (Headers, alt text, etc)
- [x]  (Evelyn) Confirm with Shannon when we should delete videos from Sharepoint

## Acceptance Criteria
- [x]  (Nichole) Github research folder is complete as per Platform standards
- [x]  Other artifacts are cataloged and easy to locate for future teams
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
We will delete the research videos on Sharepoint on 1/26, but not until checking with Shannon.

**Comment by nnicholas7** [comment]
Research findings have been uploaded to Github.  All related research documents can be accessed using the links below.

Research Documentation can be found on Github
- Research Plan (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2023-11-Shadowing-Research/Research-Plan.md)
- Conversation Guide (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2023-11-Shadowing-Research/Conversation-guide.md)
- Research Findings (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2023-11-Shadowing-Research/research-findings.md) 
 
Mural boards are located in the DBEX Folder.  Please see links for reference.
- Shadowing Research Synthesis board with synthesis video (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703092286405/34f0b24b01e41338f7ba4ddfe0b9505128af7d60?sender=u813bb40bd648bc2b58599242)
- Shadowing Research Notetaking Doc- (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699984117470/8cfe1064b275d2baf77534bf53aa16a1b4b3963d?sender=uffa03f837f92a7ba90498999)
- Shadowing Ideation Session - (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704825496218/b8097a5a017fe9dc8f8c2a934ab98a69a903f296?sender=uffa03f837f92a7ba90498999 )
