### ISSUE TITLE
[Design] 10-10EZR Figma Migration: Additional Screens Converted

### ISSUE THREAD

**Issue by katelyncai** [department-of-veterans-affairs/va.gov-team#73476]
## Background
As we reach the end of the Sketch license, the VA.gov Platform and OCTO-DE leadership has decided to move from using Sketch to Figma as a design platform.

Now that we've completed migration for the key workflow pages of the 10-10EZR, we will determine what other pages are worth converting into Figma, which are worth documenting with images, and which are able to be archived or deleted.

## Tasks
- [x] Mark pages in EZ Figma file using key: ⚠️ needs conversion, 📄 export to image, 🗑️ delete page
- [x] For export to image, export those screens to PDF files or 2x PNGs. If there is a ticket number associated, upload images to those closed tickets in github.
- [x] Add pages that need converted to [Figma migration spreadsheet here](https://docs.google.com/spreadsheets/d/1uQnYLw6gktq_yfMdkBQFvoxhPxIxeZmDmiStaqtOJdA/edit#gid=0)
- [x] Add pages to tasks to this ticket listed below
     - [x] 📄 Presentation - EZR Wireframe Flow (Platform does not have component yet)
     - [x] 📄 Presentation - EZR v2 (Platform does not have component yet)
     - [x] ⚠️ Dependent Edu - #70095 &  #70873
     - [x] ⚠️ EZR Form Wireframe - #63037 (Platform does not have component yet)
     - [x] ⚠️ EZR in Profile: #63889
     - [x] ⚠️ Financial Disclosure Wireframes - #60583
     - [x] ⚠️ Midpoint SHOULD tickets (Compare with source-of-truth flow, see if it matches and if Dev needs to pick up the changes)
- [x] Update error messaging on [this page](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0-9612&mode=design&t=ZAZLKB8zOMkArUK3-0) to match Sketch copy for source-of-truth purposes

## Acceptance Criteria
- [x] All additional supplemental pages are updated in Figma that are needed or they are downloaded as images/archived

**Comment by katelyncai** [comment]
We have 2 pages (marked with ⚠️ in the [1010EZR Figma file](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0%3A8373&mode=design&t=XEmhxMpTTvJ9w0n1-1)) left to convert but they will iceboxed until the design system team has released wireflow components. Closing this out.
