### ISSUE TITLE
Complete Support Process Mini Blueprint

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#73479]
## Description

We recently performed an exercise with Naomi to identify opportunities, add any questions we have, and outline current processes around Platform Support and how that process connects to Platform Content's process. 

We skipped to the portions that were more applicable to our teams collectively. This left us with a gap in the process that we need to document.

This ticket will house the task of documenting the gaps in our support process [here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1705001314112/94be9d064aefed18a8e62b83a3cff00851510578?sender=udc895e519e95151fc0244426).
---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Set up phone call with Tier 1 to outline our general support process for Tier 1
- [ ] Work through the blueprint to document steps
- [ ] Create a ticket for distilling the information, [similar to this](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/73481).
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
No longer needed. Closing.
