### ISSUE TITLE
[MVP] Prepare and launch copy changes for How to Apply page for MVP release

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73478]
## Issue Description

- For the initial January re-relaunch, let's re-release the page with the widget on the "How to apply?" only, until we re-release to 100% of users.
- Related to CAIA intake request: Request to coordinate timing & reactivate pension/how-to-apply/ page from Pension Benefits Team #73034
- Prior ticket to plan for this: [MVP] Planning to re-launch static content pages for percentage release#72812

- [See Pension MVP release planning schedule here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?sender=u9d01ee38af217e4877e75660). 

---
## Tasks

Katherine:
- [x] Coordinate copy changes with VA stakeholders for the "How to Apply" page that will be released to production to % of traffic released during Canary testing on production. [See Pension MVP release planning schedule here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?sender=u9d01ee38af217e4877e75660). 
- [x] Provided finalized copy to engineering

Sean:
- [ ] Build copy changes to How to Apply page
- [ ] Share with CAIA/Katherine
- [ ] Finalize edits
- [ ] Flip content changes (in widget) to production with the Canary release percentage decided upon on January 24

## Acceptance criteria

- Once the Pension 527ez form is flipped to production on the week of January 22, the How to Apply page that leads to the form will have updated content for the % release of traffic on January 24.

**Comment by katherine-fung** [comment]
Putting this in the correct ticket: 

Hey @Midge-dev, here's the final copy for the widget content:

https://docs.google.com/document/d/1auRNdpxhXHJbpS5fkQbWnaMQsBqgW7WpDRvuazb8rjo/edit

FYI @vbellissimo Sean let @megzehn and I know that he plans to use the existing widget code that already lives on the "How to apply" page, and incorporate the copy changes for the state that shows the online form/"activated" state. If this is successful, @megzehn doesn't have to re-publish the page. Sean will control which content shows to how many people through the flipper. 
cc @strelichl for awareness.

**Comment by vbellissimo** [comment]
Thanks, @katherine-fung !
