### ISSUE TITLE
[CAIA Intake] Authenticated Experience: create resources and support page for military information

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#73492]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

**Note:** I've been working with @DanielleThierryUSDSVA on this, and she asked me to make sure to put that in the ticket so the team could talk to her and get up to speed.

## About your team

- **Team name**: Authenticated Experience
- **OCTO product owner:** Samara Strauss
- **Product name:** VA.gov Profile
- **Product manager:**  Travis Cahill
- **Slack channel:** [#accountexp-authexp](https://dsva.slack.com/channels/accountexp-authexp)
- **Dedicated content writer on your team (if you have one):** n/a
- **Dedicated a11y specialist on your team (if you have one):** n/a
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [x] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

We're expanding our military information page and currently have 2 additional info components with a few paragraphs of information. I've been working with @DanielleThierryUSDSVA and we think creating a resources and support page we can link to would be a better route, especially as the page continues to expand.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
We're about to enter a generative research phase and won't be launching enhancements to the page for at least another 4 sprints (8 weeks or so). 

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [x] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:**  #72292

## Supporting artifacts

- [Proposed page with two additional info components (top and bottom)](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/4oWVqpq) 
- [Content for top component](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/K0wRoOe) (crafted with Danielle)
- [Content for bottom component ](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/AxGmVg5)(crafted with Danielle)

## Tasks

```[tasklist]
### CAIA operations
- [ ] Initial Review - @coforma-terry and @strelichl 
```

```[tasklist]
### CAIA a11y tasks
```

```[tasklist]
### CAIA content tasks
```

```[tasklist]
### CAIA IA tasks
```

**Comment by mtcA6** [comment]
@DanielleThierryUSDSVA noticed the links are to sketch, i think the work completed here has been lost to the sands of time and would need to be redone. Thoughts on closing this out :/
