### ISSUE TITLE
Update the Design Intent script

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73509]
## User Story
As a Governance team member, I want to communicate the goal of the DI meeting so that all attendees are aware of the meeting purpose and the meeting structure.

As a Governance team member, I want to shorten the time it takes to communicate the goals of the DI meeting so that our time in the meeting can be used more efficiently.

As a VFS team member, I want to jump right into the meeting so that I am getting the most value possible from this 30 minute time slot.

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
The Design Intent script (which introduces the purpose of the meeting) is old, potentially outdated, and long. Many of the VFS teams we meet with have heard the script many times before.

The purpose of this meeting is to update and revise the Design Intent script. The script goals remain the same as they were previously - communicate the VFS team and VFS product (mandatory), explain the goals of the Design Intent and share the structure/agenda of the meeting. However in addition to meeting the same goals, we now have a new goal to shorten character count so that it takes significantly less time to read each Design Intent meeting. 

The script needs to be updated everywhere it is currently published, even if we have plans to remove it from the touchpoint page.

## Impacted Artifacts
[Design Intent touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) page
[Design Intent - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775973945/Design+Intent+-+During+the+Meeting)

## Tasks
- [x] Draft a new script
- [x] Share with Governance team members for review and feedback

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The DI script has been shortened to roughly half the length it currently is
- [x] The DI script still includes an introduction of the VFS team, VFS Product and VFS feature (if applicable)
- [x] The DI script is to-the-point, with no duplication of content, and written in plain language
- [x] The DI script is easy to read for Governance team hosts

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
Hi @allison0034 - [Here's my first pass](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2912485538/73509+-+Update+the+Design+Intent+script). I cut the script down from roughly 201 words to 116. Let me know what you think!

**Comment by allison0034** [comment]
@rferguson13 I made some comments... looking so much better!

**Comment by shiragoodman** [comment]
@rferguson13 Per discussion at standup, can you also take a look at the post-meeting script? We currently say things at the beginning of the meeting that we could/should say at the end of the meeting. Please let me know if you have any questions!

**Comment by rferguson13** [comment]
@shiragoodman - Here's another attempt! [73509 - Update the Design Intent script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2912485538/73509+-+Update+the+Design+Intent+script)

**Comment by shiragoodman** [comment]
per my Slack comment, this is looking great! Since Allison is out, feel free to move forward without her formal peer review. If she has comments when she returns, we can make adjustments then.
