### ISSUE TITLE
Redesign VFS-facing Design Intent guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73513]
## User Story
As a VFS team member, I want to clearly understand what is expected of me and what I should expect from the DI meeting so that I can be prepared and ready.

Assignee: @rferguson13 @erinrwhite 
Peer Reviewer: @allison0034 

## Description
In the research completed by Service Design (both phase 1 and 2), it was observed that the Design Intent touchpoint page on Platform Website is overwhelmed with information, making it difficult for VFS team members to easily obtain relevant information from the page. 

Service Design has made several recommendation, as seen below, including a proposed redesign of the touchpoint page , done in their Phase 1 research. The pain points, recommendations and opportunities were documented in their phase 2 research and are directly related to feedback from VFS teams.

The purpose of this ticket is to redesign the Design Intent touchpoint page and the Design Intent section of the CC Request ticket to better meet the needs of VFS teams. We recognize that all of the pain points id'd by Service Design cannot be addressed within this guidance, however we will attempt to resolve as many problems as possible whilst still keeping the page succinct and easy to comprehend.

In addition, we'd like to include a link to the [Guidance for Creating User Flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md) created by CAIA where appropriate. 

**Note:** In a later ticket, Governance will be recording a short video for the DI touchpoint page that explains the purpose of the DI and walks through the process.. aka the audio version of the content on the page. 

**Relevant docs from Service Design:**
- [Recommended:  Design Intent page - (with updated format/content)](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2730131458/Recommended+Design+Intent+page+-+with+updated+format+content)
   - [Observations from Service Design](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2728526101/Design+Intent+-+analysis+of+Platform+documentation+through+SD+lens#The-Design-Intent-page) supporting touchpoint page updates
- [Pain points, Recommendations, and Opportunities](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2809626855/Pain+points+Recommendations+and+Opportunities)
   - DI prep: Long process
   - DI prep: Lots to absorb
   - Artifacts: Confusion around prototype and research plan requirement, level of fidelity, timing; unsure which artifacts for which stage 
   - Documentation: Some outdated content, inconsistent with new docs 
   - Documentation: Context around the documents and expectations is not as clear
   - DI Review Meeting: What to expect

## Impacted Artifacts

- [Design Intent touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) on Platform Website
- Design Intent section of the Collab Cycle Request gh ticket via the [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Design-Intent-code-block) - single code block and individual code block for DI

## Tasks
- [x] Review the Service Design documents above. Identify and document a list of improvements (ie requirements) that should be made to the DI touchpoint page 
- [x] Peer review requirements
- [x] Once requirements are reviewed, propose redesign of the touchpoint page. Ensure all requirements are met.
- [x] Modify the DI section of the CC Request template to align with the touchpoint page
   - this will mostly be to ensure language aligns. We will not be redesigning the layout of the CC Request within this ticket.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have redesigned the Design Intent touchpoint page to reduce quantity of content, eliminate duplicative content, and make it easier for new VFS team members to understand DI expectations

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@erinrwhite - Here's my attempt at the page redesign! Let me know what you think: [73513 - Design Intent page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2940698630/73513+-+Design+Intent+page)

**Comment by erinrwhite** [comment]
@rferguson13 This is looking really great. I have some small additions and deletions - would it be best for me to comment, or just to edit the draft?

**Comment by rferguson13** [comment]
@erinrwhite Edit the draft!

**Comment by erinrwhite** [comment]
@rferguson13 you got it. Will take a look first thing in the morning!

**Comment by rferguson13** [comment]
@erinrwhite I love the changes you've made. They look good to me. 

Next we need to get to the GH ticket.

**Comment by shiragoodman** [comment]
@rferguson13 @erinrwhite I don't recall if I linked it above or not, but Service Design did make some recommendations for the DI section of the GH ticket. [Check it out here. ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2731114771/Design+Intent+section+of+CC+ticket)

**Comment by erinrwhite** [comment]
@rferguson13 [First attempt at updated GH ticket content!](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2949447681/73513+-+Design+Intent+section+of+CC+ticket)

**Comment by rferguson13** [comment]
@erinrwhite - Would you like me to add comments or just edit the doc directly?

**Comment by erinrwhite** [comment]
@rferguson13 edit directly please and thank you!

**Comment by shiragoodman** [comment]
@rferguson13 @erinrwhite I haven't had a chance to preview your new touchpoint page, but I do have a question as we start planning for next sprint. One of the pain points that Service Design pointed out is that VFS teams, with regards to artifacts, experience, "confusion around prototype and research plan requirement, level of fidelity, timing; unsure which artifacts for which stage." 

Do you feel this is something that's been addressed as you work on the touchpoint page for this ticket? Please let me know. if not, I think we'll want to take a closer look soon, but if so, I'm excited to see your changes!

**Comment by rferguson13** [comment]
@shiragoodman - I think we address this pretty well. We have a specific section that calls out what is required (the user flow) and how much detail there needs to be. There are also links to user flow guidance and to CAIA. 

We also call out other artifacts that aren't required, but nice to have. This should cover that without going overboard. We can always iterate!

**Comment by rferguson13** [comment]
@erinrwhite - Minor edits. Looks good!

@allison0034 - Shira is going to review these pages, but perhaps you should start peer reviewing as well?
- [Design Intent page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2940698630/73513+-+Design+Intent+page)
- [Design Intent section of CC ticket](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2949447681/73513+-+Design+Intent+section+of+CC+ticket)

**Comment by allison0034** [comment]
@rferguson13 this looks awesome! Much easier to understand the process. I made a few small comments for you to consider. My only complaint really is that the page is much longer, but it is much more clear. : )

**Comment by erinrwhite** [comment]
Thank you @allison0034 for the review! I made updates based on your feedback. Tagging @rferguson13 for visibility too - and one remaining content on the DI page:

[Design Intent page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2940698630/73513+-+Design+Intent+page)
[Design Intent section of CC ticket](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2949447681/73513+-+Design+Intent+section+of+CC+ticket)

**Comment by allison0034** [comment]
@erinrwhite  Made one small comment, otherwise looks great!

**Comment by erinrwhite** [comment]
@allison0034 Gah! Good eye, thank you - updated.

**Comment by shiragoodman** [comment]
@erinrwhite @rferguson13 @allison0034 ok! I took a look and provided some comments in both docs (only 1 comment in the gh ticket). Great job! Please tag me in the comments if you have questions and/or let me know when decisions have been made.

**Comment by rferguson13** [comment]
@shiragoodman - I believe all edits have been addressed. Shall we...publish? :)

**Comment by shiragoodman** [comment]
LET'S DO IT!

**Comment by erinrwhite** [comment]
Part 1 of 2 (@rferguson13 will update the Platform website page) is published. @allison0034 @shiragoodman 

["Single block for all touchpoints" code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Step-3:-Add-touchpoints-to-GitHub-ticket:~:text=Cycle%20touchpoints.-,Single%20code%20block%20for%20all%20touchpoints,-If%20only%20some) in Kickoff responsibilities doc
[Design Intent code block](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Design-Intent-code-block) in Kickoff responsibilities doc

**Comment by rferguson13** [comment]
@shiragoodman @erinrwhite @allison0034 - It's live! [Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
