### ISSUE TITLE
[Design] 10-10EZ Figma Migration - Additional Screens Converted

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#73517]
## Issue Description
The initial "source of truth" production design pages have been converted in Figma in ticket #71861. This ticket is to mark and convert what other pages are worth updating to Figma components, which are worth documenting with images, and which are able to be archived or deleted.

---
## Tasks
- [x] Mark pages in EZ Figma file using key: ⚠️ needs conversion, 📄 export to image, 🗑️ delete page
- [x] For export to image, export those screens to PDF files or 2x PNGs. If there is a ticket number associated, upload images to those closed tickets in github.
- [x] Add pages that need converted to [Figma migration spreadsheet here](https://docs.google.com/spreadsheets/d/1uQnYLw6gktq_yfMdkBQFvoxhPxIxeZmDmiStaqtOJdA/edit#gid=0)
- [x] Add pages to tasks to this ticket listed below
- [x] ⚠️ Flow Reg Only Early Explore - Issue#65659
- [x] ⚠️ SIP - Dependents Review Page - Issue #70217
- [x] ⚠️ File Upload - Issue #49495
- [x] ⚠️ Confirmation (after submission)
- [x] ⚠️ Short form FLOW - Epic #27679
- [x] ⚠️ ? SIGI-unauthenticated
- [x] 📄 + 💬 Household QA -  Epic #41403
- [x] ✅ Dependents Education Expenses -  Issue #70857

## Acceptance Criteria
- [x] All additional supplemental pages are updated in Figma that are needed or they are downloaded as images/archived
---

**Comment by hdjustice** [comment]
Consider the EZ may need more effort to complete than EZR or CG.  Story estimates may differ.
