### ISSUE TITLE
Generate slack post that explains what happens to Feedback submissions

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#73523]
## Purpose
We're asking VFS teams to give feedback, but that may not be attractive if they think it just goes into some file and nothing happens with it.  Let's briefly convey the journey that their thoughts take all of the way to OCTO leadership, and let's publish it in vfs-all-teams.

## Tasks
- [ ] Draft "where does my Feedback even go?"
- [ ] Share with SDT for review
- [ ] Revise
- [ ] final proofread by team
- [ ] schedule a time for it to publish in #vfs-all-teams

## Acceptance Criteria
- [ ] Revised draft is completed
- [ ] Slack post is scheduled
