### ISSUE TITLE
[bug] NOD | Fix no issues loaded alert visibility

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#73525]
## Value Statement
**_As a_** Veteran
**_I want to_** know why no issues are appearing on my contestable issues page
**_So that_** I know that nothing was loaded and I'll need to enter my issues manually

## Background Context

While testing Notice of Disagreement, we encountered a situation where the contestable issues endpoint returns an empty array. We do have an alert that is supposed to show when no issues are loaded, but it doesn't appear to be showing up as expected. We'll need to fix this problem and update the unit tests to prevent regression

## Acceptance Criteria

- [x] When no contestable issues are loaded, an alert must appear at the top explaining that no issues were loaded, or eligible
- [x] When the Veteran adds, then deselects all added issues, the other alert reminding the Veteran that no issues are selected must appear instead of the no issues loaded alert
- [x] Unit test have been updated and are all passing

## Tasks
- [ ] Fix issue where no issues loaded/eligible alert is visible
- [ ] Ensure no selected issues alert overrides no issues loaded alert when none selected
- [ ] Update unit tests to cover these situations
- [ ] Consider adding a check to the e2e test

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
Separate API load error from no issues error.

**Comment by saderagsdale** [comment]
@eileen-coforma Can you add link to the alert designs in Figma?

**Comment by eileen-coforma** [comment]
Validated in parking lot. Works as intended.
