### ISSUE TITLE
EVSS - Tech Discovery on how the claim is sent to VBMS via Lighthouse 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#73526]
## Issue Description
The scope of this ticket is to look into show the submitted structured data for a claim gets into VBMS. 
Can we determine what's being set in VBMS by BGS vs Lighthouse?

---
## Tasks
- [x] Is Lighthouse submission logic in vets-api repo at all? This could be a good starting point. Yes
- [x] We could take what the all claim data translation and compare to what's in VBMS 
- [x] Is there an API that's available? What is the schema that's expected? What is the endpoint?
- [x] What is the workflow that this data goes through to get into VBMS? Do they send directly to VBMS?

### This is how it works:
1. Lighthouse's implementation of the submit endpoint is in the `vets-api` repository. There are rumors of this moving out of the repository.
2. From the code in `vets-api` currently, there is no inkling as to what VBMS is expecting
3. This is because Lighthouse has containerized the EVSS endpoint that does the submission to VBMS/BGS, which means that the schema they use to "submit" is actually the EVSS schema that is used today by vets-api to submit to EVSS
4. Note: It has been said that "eventually" this EVSS containerized endpoint will "go away", being replaced by a new and "faster" VBMS endpoint that will hopefully accept the Lighthouse schema. This is nice because we won't need a lot of transformation layers anymore.
5. The Lighthouse submission process is as follows: 
6. When the submit endpoint is hit, 3 jobs are triggered in succession, depending on success or fail status (of course)
7. Job 1: Process the claim and generate a PDF. The data of the claim is sent to a Lighthouse "Generate 526 PDF" endpoint. This PDF is stored for later use. 
8. ->Job 2: Call the containerized EVSS endpoint to submit the claim to VBMS. The end result of this job is the `claim_id` from VBMS! The EVSS container first makes a call to BGS to retrieve some metadata about the claim, and then uses the metadata to establish the claim in VBMS,
9. --> Job 3: Call the "benefits-documents" endpoint to submit the PDF generated from Job 1. This endpoint updates the "suspense date" to "today" and then it sends the 526 PDF to VBMS directly.

Here is a diagram:

<img width="838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dda5d8e1e6ac44f0599de5dc068e3f8c3e3c06e2/DBex%20Diagrams%20-%20Submission%20Solutions.jpeg" alt="DBex Diagrams - Submission Solutions.jpeg" />

## Acceptance Criteria
- [x] Describe how the submitted structured data for a claim gets into VBMS

## Related Docs
- [ ] [Platform's doc on BGS](https://depo-platform-documentation.scrollhelp.site/developer-docs/benefits-gateway-service)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @mchae-nava @sethdarragile6 @aurora-a-k-a-lightning @tommasina-va @christinec-fftc
