### ISSUE TITLE
[Design] Clean up pages in Figma Unified Check In file

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#73559]
## Tasks
- [ ] Clean up Design page in [Figma Unified Check-in file](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-Check-In-%7C-Check-in?type=design&mode=design&t=J7OIRIkHizBqVgtq-0)
- [ ] Apply auto-layout

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Closing. I'll create a separate ticket for the new components we want to make.
