### ISSUE TITLE
[VA partner request] Update travel reimbursement note on VA claim exams page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#73555]
## Issue Description
Our VA partners in the MDEO office asked us to make an update to a note we have on our [VA claim exam](https://www.va.gov/disability/va-claim-exam/) page. Veterans living outside the U.S. and U.S. territories are asking for travel reimbursement but they aren't eligible. The note we currently have doesn't explicitly state that so they asked us to make it clearer. 

In the accordion **Will VA pay for my travel to and from a claim exam?** the suggested updated language is:

**Note:** Active-duty service members along with claimants residing outside of the United States and U.S. Territories aren’t eligible for travel reimbursement.

We need to adjust this content to make it more plain language and so that it meets VA.gov style standards. We should also review the rest of the page to make sure we don't need to adjust language in other place.

## Tasks
- [ ] Update content in Drupal
- [ ] Send to stakeholder for approval
- [ ] Copyedit
- [ ] Publish
- [ ] Notify stakeholder that change is live

## Acceptance Criteria
- [ ] Update is live on the site

**Comment by RLHecht** [comment]
Beth and I worked on this. I got the OK from the stakeholders and published the page. Moving to validate and will close when live.
