### ISSUE TITLE
Create an "Ideal flow" for OH scheduling as a base to prompt questions

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#73569]
## Task Description
 In effort to iterate quickly and understand constraints as design starts working on a OH scheduling flow, we need to note any questions we have that may lead us to a better understanding of constraints in order to help guide our designs. 

## Notes and References
-

## Acceptance Criteria
- [x] Create a "conversation map" of the scheduling experience
- [x] Create an "ideal flow"
- [x] Create questions at each step of the flow
- [x] Go through business rules for OH and add them to the figjam board. 

## Deliverables
- Figjam board of the [conversation map](https://www.figma.com/file/yPkd63oshqKiVEqYOpsICr/Conversation-map?type=whiteboard&node-id=0%3A1&t=O27cTYjXnxhWKNi7-1)

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by melissa-lefevre** [comment]
This is complete. Now we are able to use it as a tool to guide our feasibility exploration meetings.
