### ISSUE TITLE
OH scheduling: Feasibility exploration

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#73568]
## Task Description
Facilitate a collaborative knowledge sharing meeting in regard to building a scheduling flow that will enable Veterans to manage appointments on VA.gov who are enrolled at Oracle Health sites. In effort to iterate quickly and understand constraints as design starts working on a new scheduling user flow, we want to set up a time to ask technical questions. If we do not have answers in the moment, that is perfectly fine, we aim to start uncovering what we already know versus what may take more digging.

## Notes and References
-

## Acceptance Criteria
- [x] Schedule a weekly touchpoint and invite relevant participants 
- [x] Create an agenda
- [x] Use [this figjam board](https://www.figma.com/file/yPkd63oshqKiVEqYOpsICr/Conversation-map?type=whiteboard&node-id=0%3A1&t=O27cTYjXnxhWKNi7-1) to collect questions and answers
- [x] Add OH business rules to figam board
- [x] Facilitate meetings
- [x] Take running notes

## Deliverables
- [Meeting Agenda](https://docs.google.com/document/d/1i2dFmGFazNDUBeynta1IvIBbYSAjscYUNfVTvH-tcXg/edit?usp=sharing) (This will be updated each week with items to discuss and notes from each meeting will be added at the end of each meeting)

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by melissa-lefevre** [comment]
This is an ongoing meeting. I will keep it open until we are out of the feasibility exploration phase.
