### ISSUE TITLE
Share out PBS research

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#73560]
## Task Description
Now that the Provider based scheduling research has concluded, synthesized, and the report is complete, sharing the knowledge is the next piece. Since we gathered information that may impact various teams, we may need to tailer to make it relevant for the team. 

## Notes and References
- We already met with with Ben Brasso from check in about the issue around the QR codes not working for checkin but it could be good to reach back out with the final report.  

## Acceptance Criteria
- [ ] Share full presentation deck with Appointments team.  
- [ ] Create an abbreviated deck for the Monday VA Design meeting focusing on in person staff facing research
- [ ] Request to present at the Monday VA Design meeting
- [ ] Present at the Monday VA Design meeting
- [ ] Add the report to Appointment's GH[ here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/appointments/research/2023-09-provider-based-scheduling-research)
- [ ] Add all of the research materials to GH research repo [here ](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)
- [ ] Send Check-in a link to the report.

## Deliverables

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
