### ISSUE TITLE
Documentation of training material 

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#73565]
## Task Description
It will be helpful to have all of the training materials in one place to reference. It would be ideal if the materials are links to the living documents so that we are viewing up to date material. 

## Acceptance Criteria
- [x] Request training materials from an oracle health facility. 
- [ ] Gather training materials from VistA sites.  
- [x] Create a shared folder on the VA network to put all of the materials.

## Deliverables
- 

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by melissa-lefevre** [comment]
The Ohio site that shared training material does not have a live document but rather just pdfs.
