### ISSUE TITLE
OH scheduling: Project Plan

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#73572]
## Task Description
Write a project plan using the template to plan out the Oracle Health scheduling initiative. 

## Notes and References
- Consider the plan a living document and use it to track work. 
## Acceptance Criteria
- [ ] Create document
- [ ] Share with Peter and discuss together

## Deliverables
- [Project Plan
](https://docs.google.com/document/d/1dliQbhR3IiJqp0qLf43LBjyJKh1Fyq2Ndn0WT71gphU/edit?usp=sharing)
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
