### ISSUE TITLE
Redis Upgrade: Ensure services that use Redis have backup

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#73570]
## Issue Description
We will be creating a load-balancing rule, and we will be scaling down the Vets API pods. Most of the code is designed to call Redis and if record doesn’t exist, it makes a network call. During the upgrade, the Frontend will show a maintenance page and the backend API pods will be scaled down. Backup per endpoint shouldn’t matter at this point, because everything will be unreachable. Not sure on Lighthouse though; Derek should checking with Benefits and Claims.

---
## Tasks
- [ ] _Confirm API endpoint reachability with Lighthouse/Derek_
- [ ] _Create load-balancing rule_
- [ ] _Front end create maintenance page_
- [ ] _Front end displays maintenance page during upgrade_
- [ ] _Scale down Vets API pods_

## Acceptance Criteria
- [ ] _All necessary code changes will have been identified_
- [ ] _Codebase changes are made successfully_
- [ ] _Codebase changes are tested successfully in all lower and higher environments_
