### ISSUE TITLE
DR | "Stack level too deep" error

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#73584]
In Dec. 2023, we began to receive "SystemStackError: stack level too deep" errors on the Supplemental Claims form.  See [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?environment=production&field=title&field=release&field=environment&field=user.display&field=timestamp&name=SystemStackError%3A+stack+level+too+deep&project=3&query=issue.id%3A245145&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1). This error is thrown, synchronously, at some during the creation/submission of a Supplemental Claim. Which makes it a submission-blocking error, but not a silent error. Interestingly, the error we see here is the result of our error handling code erroring. So we are unable to see the underlying reason for these errors. There is some discussion of this error here: https://dsva.slack.com/archives/C05FCEH2NRG/p1704901615183509. 

An update (Feb 13), this error no longer appears to be occurring.

Another update: this error does appear to be occurring again.

Update 4/17/24: Refer to Derek's comment below for more details, but it looks like it's also happening in HLR

## Tasks
- [ ] Fix our error handling code so that we can see the underlying errors blocking submissions.
- [ ] Confirm that these underlying errors, once exposed, result in notifications to our alerts channel in Slack.
- [ ] Check on Veterans impacted to see if they are still blocked.

**Comment by anniebtran** [comment]
It looks like we're seeing the error [again](http://sentry.vfs.va.gov/organizations/vsp/issues/245145/?project=3&query=user.id%3A%222f7f28dd8ece4474b137358b45cea265%22&statsPeriod=14d) — this specific veteran was able to submit successfully though (had no evidence as a part of their form, so no evidence lost 👍 )

**Comment by anniebtran** [comment]
Another [instance](https://vagov.ddog-gov.com/logs?query=trace_id%3A2105909076536193323%20&cols=host%2Cservice&fromUser=true&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1708473091565&to_ts=1708475097626&live=false) of it

**Comment by dfong-adh** [comment]
Recent [occurence](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20service%3A%22higher-level-review%22%20resource_name%3A%22V1%3A%3AHigherLevelReviewsController%23create%22%20host%3A%22i-0b12b0da4f0f29ad2%22%20&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=3337219429991608960&spanType=service-entry&trace=6029b0cfc91ecca6&traceID=1056595653139032213&traceQuery=&view=spans&start=1713380626979&end=1713380686979&paused=true)

**Comment by anniebtran** [comment]
Seems like sometimes we don't get alerted by our monitors about this error occurring 😳 These two errors are in our dashboard but were not in our notifications channel: [trace 1](https://vagov.ddog-gov.com/apm/trace/1357344069920963729?colorBy=service&env=eks-prod&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=4156654681835993365&spanViewType=metadata&timeHint=1719945011841.099&view=spans) and [trace 2](https://vagov.ddog-gov.com/apm/trace/2922595922959451908?colorBy=service&env=eks-prod&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=3640203236770336125&spanViewType=metadata&timeHint=1719903539941.968&view=spans)

**Comment by eileen-coforma** [comment]
Investigation in the works

**Comment by anniebtran** [comment]
Investigation notes:
- Seems to not have a consistent cause — it occurs for Supplemental Claim submissions with or without evidence, and has occurred for HLR, though it may have been a one-time error due to a poorly timed db migration. 
- In some instances, the AppealSubmission record was created and InProgressForm destroyed, in others, only the AppealSubmission was created but the InProgressForm remained. Sometimes the code successfully completes the step to submit the form data to Lighthouse but if there's evidence, the code can error/blow up before we get to the step that uploads the evidence to Lighthouse and if the InProgressForm is deleted, we lose the data that would tie evidence back to the submission.

Suggestions/possible next steps:
- Adding a `rescue` block to the `PersonalInformationLog#create!` call so that we can properly handle an error instead of letting it recursively raise an error until we get a fatal error
- Might not be necessary with the work Derek is doing to persist form data until a submission is successful, but it could be valuable to think about how we could improve how we handle errors that occur in the middle of a transaction involving multiple steps/calls to the database

**Comment by eileen-coforma** [comment]
In code review. Poking platform.

**Comment by anniebtran** [comment]
The PR got merged, but it is a fairly infrequent error so I will monitor for the rest of the week and then re-evaluate what else needs to be done (i.e. possibly opening other tickets if the logging we added helps isolate what's erroring out)

**Comment by anniebtran** [comment]
PR was merged, working on validating but may take a few days as we don't see this error too frequently

**Comment by anniebtran** [comment]
Saw an [instance](https://vagov.ddog-gov.com/logs?query=%22Exception%20occurred%20while%20submitting%2A%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=desc&viz=stream&from_ts=1721140981437&to_ts=1721227381437&live=true) of an error that leads to the `stack level too deep`: 
```
Exception occurred while submitting Supplemental Claim: 1 validation error detected: Value at 'plaintext' failed to satisfy constraint: Member must have length less than or equal to 4096
```
Not sure what this means, but it's a start

**Comment by anniebtran** [comment]
Going to add the extra logging to NOD and HLR too since we saw a couple of `stack level too deep` errors for those forms as well 😩

**Comment by Mottie** [comment]
May open a new ticket to investigate errors from the logs

**Comment by anniebtran** [comment]
May have figured out what is possibly causing the `stack level too deep` error in Supplemental Claims, which is the form that most frequently encounters it, so I'll make a ticket to resolve it. But not sure what have caused it in NOD and HLR, but we can monitor for it now that we've added the extra logging

**Comment by anniebtran** [comment]
Haven't yet encountered the `stack level too deep` error from NOD and HLR since we've added the logging but upon inspecting their traces, they both happened around the same time and both share this error:
```
PG::UndefinedColumn: ERROR:  column form_submissions.in_progress_form_id does not exist
LINE 1: ...submissions" SET "in_progress_form_id" = $1 WHERE "form_subm...
                                                             ^

/usr/local/bundle/cache/ruby/3.3.0/gems/ddtrace-1.23.2/lib/datadog/tracing/contrib/pg/instrumentation.rb:35:in `exec_params': ERROR:  column form_submissions.in_progress_form_id does not exist
LINE 1: ...submissions" SET "in_progress_form_id" = $1 WHERE "form_subm...
                                                             ^
 (PG::UndefinedColumn)
	from /usr/local/bundle/cache/ruby/3.3.0/gems/ddtrace-1.23.2/lib/datadog/tracing/contrib/pg/instrumentation.rb:35:in `block in exec_params'
	...
```

So going to look into this a bit and see if there are any other instances of this error 👀

**Comment by anniebtran** [comment]
Gonna close this since there's a new ticket to cover the fix for SC and we haven't seen the `stack level too deep` error in HLR and NOD occur again with the new logging (yet) — if we do encounter the error for those forms in the future, we can create a ticket as we'll be able to find more details around what may be causing it for them.
