### ISSUE TITLE
Ensure watchtower monitor coverage remains complete

### ISSUE THREAD

**Issue by mheadd** [department-of-veterans-affairs/va.gov-team#73596]
### Description

We've already seen watchtower monitors get broken by changing metric tags, so we want to continue to ensure that all features are monitored. This could be a piece of the same validation as outlined in #73594, but breaking out the monitor validations specifically.

### Work items
- [ ] Write validation tool that checks monitor coverage for all tier 1 features
- [ ] Look up all tier 1 features in service catalog. Look up all monitors with watchtower tag and service tags. Report on features that don't have their expected monitors.
- [ ] Define and implement validation rules for monitors: env is correct, alerting if no data, receiver configured, tags set

### Questions / implementation details

* Should watchtower monitor configuration move to terraform? 
* Wrinkle with 2nd item above is that some features have background jobs (and hence 3 types of monitors), some don't (hence 2 types of monitors). How do we want to distinguish between the two? Custom service catalog extension attribute? Other ideas?
* There were a [set of monitors identified during the Monitoring and Alerting CY](https://dsva.slack.com/archives/C05QP4G0LA3/p1701994960681769) that were showing as green but functionally had no data. This is likely because they were for a valid metric but had a combination of tags that didn't have any data. The team tried some of the checkboxes for alerting on no data, but they didn't seem to work. How can we detect this reliably, so we don't have false negatives? (If fixed all the broken monitors I could find but we can easily re-create one to test against).

**Comment by mheadd** [comment]
Potentially related issue: [#68108](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68108)
