### ISSUE TITLE
My VA: Sprint 28 (1/17/24 - 1/30/24)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#73606]
# My VA

## General  (#31611)
**FE**
_from previous sprint_
- [ ] ~#65042~ moved to backlog 
- [ ] #70041 
- [ ] #70821 - waiting on test user 

## v3 Component Migration (#69482)
**FE**
- [x] Partner with Adam on #72076 

**Research & Design**
- [x] #73833 

## My VA Claims and Appeals Improvements (#71287, #54403)
**PM**
- [ ] #71288 

## My VA Telemetry, Monitoring & Alerting  / My VA Testing Improvements (#71927, #61602)
**FE**
- [ ] #72514

**BE**
- [ ] #71930

## My VA Health Care / My VA support of MHV on VA.gov Migration (#62258)
**FE**
- [ ] #73088 
- [ ] #66858 
- [ ] #72297
- [x] #71864 
- [x] #74388 

## Benefit Application Drafts Enhancements (#60509)
**FE**
- [x] #71028 

## My VA Sketch > Figma Migration (#72326)
**Research & Design**
- [x] #72127
- [x] #74091

# Notifications

## Dot Indicator (#63788) 
**Research & Design**
- [x] #72517 
- [ ] #73853 

# PM Tasks (Varying initiatives)
- [x] follow up on call center guide submission (#72135) - complete, VEO accepted late Friday 1/26
- [ ] #70284
