### ISSUE TITLE
[a11y Documentation] Create PDF creation/remediation page based on existing documentation

### ISSUE THREAD

**Issue by coforma-jamie** [department-of-veterans-affairs/va.gov-team#73623]
## CAIA a11ys assigned
- Jamie

## Description
As part of #55956, we want to include information about PDF accessibility and remediation. This should include an emphasis on _not_ using PDFs unless absolutely necessary.

@SarahKay8 created a document that explained her PDF remediation process and evaluated the pros and cons of different PDF testing tools (detailed in #63383). @artsymartha68 requested that this document be included in our new accessibility documentation.

## Definition of done
- [x] Create a markdown page that adapts the original document for a wider audience of VFS teams
- [x] Upload page to GitHub ([create-accessible-PDF.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/create-accessible-PDF.md))
- [x] Link to page on [draft accessibility landing page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/a11y-landing-page-draft.md)

```[tasklist]
### Tasks
- [x] Evaluate existing document
- [x] Determine missing information - info about defaulting to HTML and how to make accessible source documents
- [x] Draft page structure
- [x] Write page draft
- [x] Review draft with other CAIA accessibility specialists
- [x] Send to Martha for review and approval
- [x] Link from draft accessibility landing page
```
