### ISSUE TITLE
Perform e2e testing with Veteran VA employees in production

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73626]
## Issue Description
Using some of the [e2e testing scenarios documented](https://docs.google.com/spreadsheets/d/1v1DApOkUABgVzA_4zFrGmF5prWv7T2E9OD5ojTC_iwU/edit#gid=2009661867), ensure we test:
- Standalone PDF generation
- e2e in staging environment

---
## Tasks
- [x] Prepare for e2e testing activities, discuss live testing roles
- [x] Gather testers' usernames
- [x] Add tester usernames to flipper for production
- [x] Prepare URL to share with testers
- [x] Perform live e2e testing with VA enablement team & volunteer VA employees (Derek Uttley & David Reis)
- [x] Document findings from testing
- [x] Categorize launch-blocking issues, create tasks as needed, with input from VA enablement team.

Links to notes:

- https://docs.google.com/spreadsheets/d/1oi5TlNSUYMEDdK8_6O30sdkLDNbpaNDuN_-UJMwXrew/edit?usp=sharing
- https://docs.google.com/document/d/1Jqdx2r9QzD8AJru-vaQjHENPTt6SCyeOzD8N7UX1LHk/edit?usp=sharing

**Comment by buddhima-coforma** [comment]
Capturing notes here https://docs.google.com/document/d/1Jqdx2r9QzD8AJru-vaQjHENPTt6SCyeOzD8N7UX1LHk/edit
