### ISSUE TITLE
Perform e2e testing with VA enablement team in staging

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73625]
## Issue Description
Using some of the [e2e testing scenarios documented](https://docs.google.com/spreadsheets/d/1v1DApOkUABgVzA_4zFrGmF5prWv7T2E9OD5ojTC_iwU/edit#gid=2009661867), ensure we test:
- Standalone PDF generation (locally?)
- e2e in staging environment

---
## Tasks
- [x] Prepare for e2e testing activities, discuss live testing roles
- [x] Perform testing for a standalone PDF generation - Locally to share with stakeholders
- [x] Perform live e2e testing with VA enablement team, including standalone PDF generation
- [x] Inform OBI and other VA business stakeholders of testing done
- [x] Document findings from testing
- [x] Categorize launch-blocking issues, create tasks as needed, with input from VA enablement team.
