### ISSUE TITLE
Increase traffic to production to 25% of traffic

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73631]
## Issue Description

**- This task is dependent on success of Canary testing release in production**

See the [release plan schedule in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?wid=0-1704481087285) for reference.

---

## Tasks

- [ ] Increased the online form traffic to 25%
- [ ] Monitor submissions via Datadog display and alerts
- [ ] Provide submission data to OBI/VBA twice weekly
