### ISSUE TITLE
Increase traffic to production for Canary testing

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73630]
## Issue Description
**- This task is dependent on success of e2e testing in staging and success from our moderated user testing with VA veteran/employee volunteers from January 23**

---
## Tasks

- [ ] Increased the online form traffic to 5%?
- [ ] Monitor/aim for at least 10 claims submitted successfully
- [ ] Monitor submissions via Datadog display and alerts
