### ISSUE TITLE
[CHIP] SPIKE - Research new cerner payload from vetext

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#73636]
## Description
We need to create a new initiateCheckIn endpoint for cerner appointments. Sync up with Shane on what the new payload will look like. Then determine what we will need to do in the new cerner utility layer to support this new payload. 

## Tasks
- [ ] [FE] get sample payload from vetext
- [ ] [FE] create ticket for new initiate endpoint
- [ ] [FE] determine what we need in the service layer to support the cerner payload
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
here is what a OH appointment will look like:
`{
  "id": "4822366",
  "startDate": "2020-01-23T22:10:00.000+00:00",
  "endDate": "2020-01-23T23:10:00.000+00:00",
  "length": 60,
  "status": "Cancelled",
  "patient": {
    "address": "1166 6th Avenue\n22\nNew York, NY 23423\nUS",
    "birthDate": "1980-08-11T04:00:00.000+00:00",
    "cellPhone": "+55 (55) 5555-5555",
    "deceased": false,
    "edipi": "1000000105",
    "email": "humberto.ganesh+@lumahealth.io",
    "ethnicity": "Hispanic, Latino, or Spanish Origin",
    "gender": "female",
    "homePhone": "5155556789",
    "id": "12724066",
    "language": "English",
    "maritalStatus": "Married",
    "mrn": "6930",
    "officialName": "SMART II, NANCYU NHA EEEEEE",
    "practitionerId": "4122622",
    "practitionerName": "Cerner Test, Physician - Hospitalist Cerner",
    "usualName": ""
  },
  "patientStatus": "accepted",
  "practitionerIds": [],
  "practitionerNames": [
    "Endoscopy Rooms"
  ],
  "wardId": "32216049",
  "wardName": "Endoscopy",
  "buildingId": null,
  "siteId": null,
  "organizationId": null,
  "stationNo": "530",
  "cancellationReason": null,
  "comment": null,
  "description": "Surgery Rapid",
  "patientInstruction": null,
  "reasonCode": [
    "I have a cramp"
  ],
  "serviceCategory": [],
  "serviceType": [
    "4047611",
    "394576009"
  ],
  "serviceTypeCodes": [
    "4047611",
    "394576009"
  ],
  "serviceTypeGroupNames": [],
  "slot": [],
  "timezone": null
}`

**Comment by brianseek** [comment]
For BTSSS we will send the appointment date and EDIPI. 
Patient ICN is not in the payload at time of this comment. Will continue discussion tomorrow, because we will need ICN to get the MAP token.

**Comment by brianseek** [comment]
This is my proposed request body for the initiate endpoint:
```
{
  "patient": {
    "dob": "YYYY-MM-DD",
    "cellPhone[the number used to send text]": "+15555555",
    "name": "Last,First"
  },
  "appointments": [see above]
}
```

**Comment by wullaski** [comment]
We have:
- address(move to demographics)
- startDate

Clarification:
- `description` is that serviceType?
- `practitionerNames` is that the Provider?
- `patient.practitionerName`is that the Provider?
- `wardName` is that clinic friendly name?

Additional Fetch:
- Facility information(we have the facility id)

**Comment by brianseek** [comment]
closing this spike since we have the data we need.
