### ISSUE TITLE
NOD | Create PDFs and sample data for E2E testing

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#73649]
## Value Statement
**_As a_** Veteran Veteran filing an appeal on VA.gov
**_I want to_** upload evidence PDFs that pass validation
**_So that_** my evidence can be submitted with my appeal online. 

---
## Background Context
- We need sample PDFs for E2E testing
- [VA.gov Sandbox Test Accounts Page](https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts/benefits_test_accounts.md) (public repo)
[vets-api-mockdata repo](https://github.com/department-of-veterans-affairs/vets-api-mockdata)
- PDFs are located in modules/vba_documents/spec/fixtures
- [PDFs that Robin/Rocio have used for testing](https://dsva.slack.com/archives/C05FCEH2NRG/p1705088209145749)
- List of downstream evidence errors: https://github.com/department-of-veterans-affairs/va.gov-team/issues/68756. See also https://dsva.slack.com/archives/C05FCEH2NRG/p1697200982234799?thread_ts=1697148925.446959&cid=C05FCEH2NRG.

## Tasks
- [x] Review [Benefits Intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current) for details about PDF requirements
- [x] Identify common evidence upload errors to make test data for (which may already be done here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/68756)
- [x] Create sample PDF data that can be used to confirm if we're passing acceptable formats to Lighthouse
- [x] Update #73652 with any test cases it might be missing based on the findings from this work

## Definition of Ready 

- [x] We've identified the different accepted formats/requirements for PDFs that we need to generate samples of

## Definition of Done

- [x] We have PDF sample data that covers the different requirements defined by Lighthouse
- [x] #73652 is updated with any additional test cases discovered from this work (if there are any)

**Comment by data-doge** [comment]
For downstream failures: 
- PDFs we have:
  - Corrupted (encrypted + non-encrypted)
- PDFs we need:
  - a non-PDF mislabeled as a PDF (e.g. Robin's corrupted PDF, a literal JPEG).
  - PDF with non-string zip code.
  - "blank image" PDF
  - "Invalid PDF content, part content" PDF (ask LH for one?) (ask Kyle how to find one?)
  - Enormous PDF (> 100MB).
  - Enormous PDF (bigger than 78in x 101in).
- Things to clarify: 
  - Where do the zip code errors get thrown (PDF-level, or metadata?)
  - How do we create a "blank image" PDF (i.e. what kinds of blank PDFs, if not all, cause errors) (ask LH).

**Comment by saderagsdale** [comment]
Thomas Blackwell may have answers to your question about zip code

**Comment by HeatherWidmont** [comment]
@anniebtran is working through the list above to get the PDFs we need

**Comment by anniebtran** [comment]
Mock PDFs are in this [google drive folder](https://drive.google.com/drive/folders/1xdorqTvkMi1y9v80wUQzrM5QkxO1TswV?usp=drive_link) and #73652 has been updated
