### ISSUE TITLE
NOD | Complete E2E testing in lower environments

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#73652]
## Value Statement
**_As a_** Veteran submitting an NOD with a request for extension caused by the infinite loop bug
**_I want to_** resubmit my appeal with confidence that the data is share will be received
**_So that_** I can adjudicate my claim decision.

---
## Test Notes and Links
- [Google drive folder with test PDFs
](https://drive.google.com/drive/folders/1xdorqTvkMi1y9v80wUQzrM5QkxO1TswV?usp=sharing)
  - Note about the file sizes — Google Drive lists a file size smaller than what it is when I created the files/download them again. The file names for the large files are supposed to reflect what the sizes are when they're downloaded

Mock users to use on staging (find pws [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)):
- vets.gov.user+228@gmail.com (international address)
- vets.gov.user+54@gmail.com (US address)

## Tasks
- [x] Prepare test data
- [x] Confirm that the environment is ready for testing
- [x] Confirm test users with properly configured data (e.g. contestable issues)
- [x] Kickoff comms with Lighthouse, Centralized Mail Portal, Data Dimensions, Doma, and Board of Veterans Appeals
- [x] Confirm how LH, CMP, BVA, will pass test results back
- [x] Go through test cases, monitor logging and record results

## Out of scope
- Code work for upstream evidence failures

## Definition of Ready 
- [ ] The feature satisfies all functional requirements
- [ ] The feature code is integrated into the lower environment
- [ ] Unit tests and component tests for the feature have been executed and passed
- [ ] Lower test environment is configured to simulate the production environment as closely as possible
- [ ] Test data for the E2E tests have been prepared to cover various scenarios
- [ ] External systems that the feature relies on are configured in the lower environment
- [ ] Test users for each test case are ready
- [ ] Test plan approved by involved teams and stakeholders
- [ ] Test documentation is ready for use

## Definition of Done

- [x] E2E test scripts are executed to verify the end-to-end functionality of the feature
- [x] The E2E tests meet the predefined passing criteria
- [x] Integration points with other systems or components are validated
- [x] Defects identified during E2E testing are addressed
- [x] E2E testing documentation, including test cases and results, is updated
- [ ] Any test artifacts and data are cleaned up from the lower test environment
- [x] Test team signs off on the test phase
- [x] OCTO signs off on the test phase

**Comment by rubensun** [comment]
@saderagsdale to create thread with @data-doge and @anniebtran with CMP on next steps for verification.

**Comment by HeatherWidmont** [comment]
@data-doge will review the thread

**Comment by saderagsdale** [comment]
- @saderagsdale will confirm if all upstream systems are listed in the test doc.
- @anniebtran will add links to test files used for each test case in the SharePoint doc.

**Comment by anniebtran** [comment]
Completed positive test cases earlier this week. May need to redo if the ["valid" PDF](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/spec/fixtures/valid_doc.pdf) I borrowed from some test fixtures [doesn't have enough content](https://dsva.slack.com/archives/C05FCEH2NRG/p1706734203795469), so we'll see if there's any follow up there. Also ran a couple batches of negative cases yesterday and had to skip two cases (>5GB and corrupted file) because they were a little trickier to test than originally thought.

**Comment by HeatherWidmont** [comment]
Just waiting to hear back from Rashmi

**Comment by saderagsdale** [comment]
Michel from Lighthouse explained that CMP needs to change the status of the appeals, which Lighthouse will then use to trigger sending the evidence. I sent an email to Jacob from CMP to get the ball rolling.

**Comment by HeatherWidmont** [comment]
@saderagsdale put tentative release dates in slack thread: https://dsva.slack.com/archives/C05FCEH2NRG/p1707779560697499?thread_ts=1707778870.075259&cid=C05FCEH2NRG

**Comment by saderagsdale** [comment]
Moving old ticket documentation here:

### Positive Scenarios
- [ ] If a user submits a form with string values for ZIP code formatted in 5 digits and no PDF, it is accepted by Lighthouse and CMP. 
- [ ] If a user submits a form with string values for ZIP code formatted in 9 digits using XXXXX-XXXX format, and no PDF, it is accepted by Lighthouse and CMP. 
- [ ] If a user submits a form with string values for ZIP code formatted in 5 digits, or 9 digits in XXXXX-XXXX format, with an unencrypted PDF with no password, smaller than 78" x 101", under 100 MB, in an overall payload under 5GB, it is accepted by Lighthouse and CMP.
- [ ] If a user submits a form with string values for ZIP code formatted in 5 digits, or 9 digits in XXXXX-XXXX format, with an encrypted PDF but not locked with a password, smaller than 78" x 101", under 100 MB, in an overall payload under 5GB, it is accepted by Lighthouse and CMP.
- [ ] If a user submits a form with string values for ZIP code formatted in 5 digits, or 9 digits in XXXXX-XXXX format, with an encrypted and locked PDF with a password, smaller than 78" x 101", under 100 MB, in an overall payload under 5GB, it is accepted by Lighthouse and CMP.

### Negative Scenarios
- [ ] If a user submits a form with non-PDF evidence, it is rejected by Lighthouse 
  - Could use any image file here, but frontend might already limit uploads to PDFs
- [ ] If a user submits PDF over 100MB, it is rejected by Lighthouse. 
- [ ] If a user submits PDF greater than 78in, it is rejected by Lighthouse. 
- [ ] If a user submits PDF greater than 101in, it is rejected by Lighthouse. 
- [ ] If a user submits corrupted PDF, it is rejected by EMMS. 
- [ ] If a user submits blank PDF, it is rejected by EMMS. 
- [ ] If a user submits multiple PDFs that add up to an overall payload of more than 5GB, it is rejected by Lighthouse. 
- [ ] If a user submits locked PDF (that fails to be unlocked during upload?)
  - Need to investigate more and see if we somehow need to get past password validation when the veteran selects files to upload? There is an unlocking step that occurs after they select a file that is locked, but some files are still encrypted in S3 (not sure if they're supposed to be at that point)

**Comment by anniebtran** [comment]
Update: Lighthouse submitted evidence files to EMMS/CMP and they were processed manually by Darren/Rashmi. Currently updating the test cases spreadsheet with the results that were reported by Rashmi

**Comment by anniebtran** [comment]
Update: Results have been filled in on the test cases spreadsheet, Rashmi nudged Jacob Shepard to upload the evidence packets from CMP pre-prod to VBMS, which should update the statuses to "complete"
