### ISSUE TITLE
Remove exhaustive-deps eslint-disable from Search Page in Find a Rep

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#73679]
## Issue Description
The SearchPage component has 5 disabled warnings about exhaustive-deps. These warnings have no bearing on the app's current functionality, but addressing them would mitigate the potential to introduce bugs later on.

The issue is with how Find a Rep implements `useEffect` react hooks to run logic in response to a variable change. Modeling from the async pattern of Facility Locator, there are 5 useEffects whose body contains references to variables that must also be declared in the dependency array (aka the group of variables that trigger the logic to run when updated). 

The problem is that introducing these variables to the dependency array causes an infinite loop (because whenever they change, that would trigger a function which changes them again). So we need to refactor the code pattern in order to address the warnings. 

---
## Tasks
- [ ] Define logic outside the useEffect bodies where possible
- [ ] Make use of memoization where necessary
- [ ] Remove useEffects entirely where possible (replace with event listeners)

## Acceptance Criteria
- [ ] No linter warnings
- [ ] No disabling linter warnings
