### ISSUE TITLE
[FSR] Review page navigation testing

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#73673]
## Description
Review page navigation work is coming to a close. There's a bunch of edge cases that we did our best to cover, but dedicating some time to just run through and try to break the form will give thew whole dev team a little more peace of mind. 

Going to list as many of the potential pain points as I can, but let's add more if we think of them. 

## Tasks
  - A change made to one (or multiple) of the following sections for veteran and/or spouse can change to/from the streamlined version of the form, so let's double check these:
    - Employment, Benefits, Additional Income

- [x] **Full FSR changes to:** (Confirm Cash in Bank / Cash on Hand & Monetary assets are populated correctly.)
  - [x]  Streamlined short
  - [x]  Streamlined long
- [x] **Streamlined short changes to:**
  - [x]  Streamlined long
  - [x]  full FSR
- [x] **Streamlined long changes to:**
  - [x]  Streamlined long
  - [x]  full FSR

- [x] Create a ticket to generate e2e tests based on insights gained from manual testing

## Acceptance criteria

- [x] Review navigation has had one last manual run through by the devs
- [x] Front end e2e ticket has been generated for review navigation

## Testing
- [x] Yes
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
Linking [71257](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/71257) since it has some useful submission objects to test with

**Comment by OptionSelect** [comment]
Per convo with Andrew commenting the one found break scenario after testing Friday and Today. Attempting to fix here if it is quick, if not I'll spin up a new ticket focused on that effort specifically.

Break scenario (note: the selected asset still makes it to redux so I assume that value typed will as well, issue seems to be navigation only)

Streamlined -> Non Streamlined
- Select a copay
- Fill out all fields
- Cash in Hand 1000, Cash in Bank 2000 (any values that will stay streamlined)
- Enter Review Page
- Review nav to Cash in Hand/Cash In Bank
- Enter 100000 for CIH and 200000 for CIB to enter full form logic
- Check a household asset (US Savings Bonds is what I did)
- Enter a value and click continue
- Notice that page does NOT navigate

**Comment by OptionSelect** [comment]
Created the following ticket to catalog the effort for next sprint to tackle this due to change taking longer than anticipated and in order to not repurpose this ticket and have it roll.

https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/76644
