### ISSUE TITLE
[Design] 10-10EZ - Toxic Exposure: Create mock-up with new questions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#73671]
## Background
In an effort to quickly identify Veterans who have been exposed to toxic materials during specific time period and/or while deployed at specific locations, the HEC Stakeholders would like to have Toxic Exposure questions added to the 10-10EZ form.
This is intended to quickly identify these Veterans, so they can get the care they need.  It is also intended to providing Veterans a place to add the information so that this information is included in the Veteran's health record.  This information could qualify the Veteran for care they would not otherwise be able to receive. 

## Resources
- [TERA document draft 1.23.24](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/TERA%20draft%201-23-2024%20VA%20Form%2010-10EZ.pdf)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?fromVisitorModal=true&sender=u5ad49c107baa41137f271007)
- [Figma page](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=450-19244&mode=design&t=GyO36RKAPEFgXEna-0)
- [Sitewide PACT wizard](https://staging.va.gov/pact-act-eligibility/service-period-1) tool for reference

<details>
<Summary>Original Slack conversation (expand to view)</Summary>

>**Patrick Bateman**
>from jessie:
>- Attached are the drafts for the 10-10EZ and the 10-10EZR, and a mock-up for reference of the 10-10EZ. The mock-up will be used to help the forms team understand how we want the new TERA questions to look on both forms.
> 
>- At this time, only the TERA updates and increased burden time will be submitted to OMB, with a publishing goal of 2/1/24.
>- The second round of edits will include the 10-10EZ reorganization (sections and questions) and coordination with [VA.gov](http://va.gov/) to mitigate all identified discrepancies. That draft will be submitted with our PRA renewal with a publishing goal of 06/2024.
>
>**Patrick Bateman**
>the TERA file includes the sticky notes. the MOCK file is someone’s attempt at adding it to the form
>
>It would be cool to know how it was determined to add a whole new section.
>screening for toxic exposure. they copied the section from the 526EZ application for disability benefits (see [section IV](https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf))
>
>when i talked to them, i floated the idea of not including the question if the veteran already answered them in their 526 application
>
>since the computers and the internets have the ability to look up info that we already have — whereas a paper form just sits there :wink:
>
>or to take it a step further — why not just have that info prefilled for confirmation on the 526 from DoD >:slightly_smiling_face: i bet they know where you served.
>
>**Kristen McConnell**
>- (From Jessica Stump)
>- is this similar to the pact act wizard work/research going on?
>
>Yes. There is overlap. All of these workflows are ways to ask about toxic exposures. (edited) 
>
>**Kristen McConnell**
>I was going to look at some observer spots too, because there is also a clinical screener after you enroll in healthcare. You answer those questions before an appointment with your provider. So, a Veteran may see variations of these questions in the PACT Act Wizard, on the 526, on the 10-10, and again at an appointment. (edited)

</details>

## Tasks
- [x] Mock-up a design that removes the questions slated for removal per the TERA document, and add the other questions
     - The additional questions can be on a new page, or kept within the same page
- [x] We will need Content to assist with language and review 
     - [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74254#issue)
- [x] Meeting with 526 design team
- [x] Make any needed revisions
- [x] Send to HEC for accuracy check
- [x] Review with PM/team for final 

## Acceptance Criteria
- A design is created with some old questions removed, and new questions in place

**Comment by jessicastump** [comment]
[Link to the updated draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/VA%20Form%2010-10EZ_TERA_v2.1.pdf) v2.1 received 1/18. The Figma design files are updated to this version including sticky note changes. 

Also noting there was supplementary info in the intro of the paper form. The impact to the online form includes the financial disclosure intro page - list of enhanced eligibility factors.

**Comment by jessicastump** [comment]
![1010EZ-FormContentTERA-March5Release](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/e74d42e7-d4db-4557-aadc-4cd4d61403cf)


[Figma link](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=450-19244&mode=design&t=ylCGkWiOekwXTCr9-0)

**Comment by jessicastump** [comment]
The content review / Figma updates (and designs) are completed. Any other edits that come back will be opened via new tickets during QA next week.
