### ISSUE TITLE
Draft initial IA principles for Design System website

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#73684]
## User Story
As a VFS team member, I want to have an easy way to access a source of truth for IA standards in the Design System. 

As an OCTO-DE IA lead, I want to ensure that there is IA standards coverage in the VA.gov Design System as older, IA-specific Experience Standards are phased out and broader Experience Standards are put in place.

Assignee: 
Peer Reviewer: 

## Description

There is currently no source of truth for IA standards on design.va.gov, as OCTO has leaned on the [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards) as an interim solution for communicating IA standards. 

Governance team's [initiative to broaden the VA.gov Experience Standards](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45160) removes specific implementation details from the Experience Standards. The Design System is the source of truth for guidelines on design and content, and IA standards should be documented there as well.

In a previous ticket, those [IA standards were mapped to existing documentation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73149) in the Design System where available. Drafting IA standards for the Design System will create a source of truth for the remaining IA standards. 

## Impacted Artifacts

- New page on [design.va.gov](https://design.va.gov/)
- [Old VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards)
- New [standards source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=1992248744) and [drafting template](https://docs.google.com/spreadsheets/d/1dOAJNKYIFQOW5NGNtZ3l0PPEy5MNQHOl0zWEB2cl20E/edit#gid=727681601)

## Tasks
- [ ] Draft "IA principles" page for inclusion on design.va.gov in a collaborative workspace
- [ ] Work with Mikki and Matt to review and approve page content
- [ ] Create and publish section/page in [Design system documentation repo](https://github.com/department-of-veterans-affairs/vets-design-system-documentation) with new principles
- [ ] Add `ia-principles` descriptive tag in new [standards source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=1992248744) and [drafting template](https://docs.google.com/spreadsheets/d/1dOAJNKYIFQOW5NGNtZ3l0PPEy5MNQHOl0zWEB2cl20E/edit#gid=727681601), linking back to new page on the design system

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Based of the thread in our governance-team channel, I believe this can be closed. @erinrwhite if you agree, please do the honors!
