### ISSUE TITLE
[BE] Spike on Mobile Profile Service to call VA Profile using MAP token

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73685]
## Resource
Brittany Fowler or Stephen Barrs
[brittany@apothesource.com](mailto:brittany@apothesource.com)

## Description
As part of integrating CIE application with cerner, backend must be integrated with VAProfile to fetch patient's demographics information.

## Tasks
- [x] [BE] **Identify VA Profile API to get patient's demographics data**
- [ ] [BE] **Identify VA Profile API to set patient's confirmation timestamp**
- [x] [BE] **Identify Mobile Profile service API to call VA Profile**
- [x] [BE] **Verify Mobile Profile service API to call VA Profile using MAP token**
- [x] [BE] **Find out request/response payload to get patient's demographics data**
- [ ] [BE] **Find out request/response payload to set patient's confirmation timestamp**

## Acceptance Criteria
- [x] Document all the API call procedure with request/response payload

**Comment by randomsync** [comment]
Added details for integration with mobile proxy service: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/oracle-health-cerner-integration.md#va-profile

**Comment by randomsync** [comment]
Also, relevant slack thread: https://dsva.slack.com/archives/C022AC2STBM/p1704998076148299
