### ISSUE TITLE
[BE] Spike on API to set arrived status in cerner appointment

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73688]
## Description
Research and identify API to set patient status to ARRIVED in cerner appointment data

## Tasks
- [ ] [BE] **Research on API to set patient status to ARRIVED in cerner appointment data**

## Acceptance Criteria
- [ ] Sample call made to API
- [ ] Document request/response payload

**Comment by kanchanasuriya** [comment]
API is not currently available in staging to make a sample call.  However, we have enough information to integrate and verify when the service is available in staging. 

Updated the [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/oracle-health-cerner-integration.md) with API payload information.
