### ISSUE TITLE
Explore Automation of identifying unused gems

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#73683]
## Description
We use a large number of gems on the platform, and believe that at least some of them may no longer be in use. We would like to explore ways of identifying these unused gems in an automated fashion in order to minimize unused code.

## Tasks
- [ ] Explore approaches to identifying unused gems
- [ ] Explore ways to automate those approaches
- [ ] Document what you learn

## Acceptance Criteria
- [ ] Ideas have been documented
