### ISSUE TITLE
[BE] Implement mobile proxy service client class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73689]
## Description
Implement mobile proxy service client class

## Tasks
- [ ] [BE] **Implement mobile proxy service client class**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
