### ISSUE TITLE
SPIKE | 686 Net Worth Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73696]
## Issue Description
Request from BIS Team: VA.gov to check if 686c form is calling and sending values for net worth and over limit.

Problem: Pension program is not receiving a net-worth-over-limit indicator they are expecting from VA.gov.

<img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9cafd886dd65e8b052ff502c582052ee29658de/image.png" alt="image.png" />

Reference request: BEPBGS-4091 Investigate why Pension not receiving net worth over limit indicator. ITRP 4772 (BEPBGS-3984)

---
## Tasks
- [ ] Determine if 686c form is sending values downstream for net worth field in step 4.
   - [ ] If yes, what values are passed downstream?
- [ ] Determine if an error is generated or a flag is added on backend if the user indicates their income is over the limit (answers "yes").
   - [ ] If yes, is the error sent downstream? What is the error?

## Acceptance Criteria
- [ ] Summary of net worth field behavior in 686c for BIS team.

**Comment by tblackwe** [comment]
Did some digging on this today. The logic is disabled in production, enabled in staging.
It has been this way since September 14, 2021. 

If the flipper is on, and the claim is to remove a dependent, then we don't modify the claim but we do pass a different end product to RBPS
`          @end_product_name = 'PMC eBenefits Dependency Adjustment Reject'
          @end_product_code = '130DAEBNPMCR'
`

need to research more if we do anything with the flag for over the limit.

**Comment by tblackwe** [comment]
in https://github.com/department-of-veterans-affairs/vets-api/blob/05bd443e4fd75f78b3c0b5bc8cf352bbbfb53047/lib/bgs/vnp_veteran.rb#L15C46-L15C46
We set the net_worth indicator based on the application data.

need to test and see if we are digging out the value correctly.

**Comment by SloopKoning** [comment]
### File Paths where the file contains networth
```shell
cd vets-api
ag -l networth | fgrep -v spec > ../networth_paths.txt
ag =l net_worth | fgrep -v spec >> ../networth+paths.txt
sort -u ../networth_paths.txt > ../networth_paths.srt
```
- app/models/bgs_dependents/child_student.rb
- app/models/bgs_dependents/veteran.rb
- app/models/bgs_dependents/vnp_benefit_claim.rb
- app/models/saved_claim/dependency_claim.rb
- config/health_care_application/wsdl/voa-voaSvc-xsd-1.xml
- lib/bgs/vnp_veteran.rb
- lib/pdf_fill/forms/va21p527ez.rb
- lib/pdf_fill/forms/va686c674.rb
- modules/mobile/app/models/mobile/v0/award.rb
- modules/mobile/app/serializers/mobile/v0/award_serializer.rb
- modules/mobile/docs/index.html
- modules/mobile/docs/schemas/Awards.yml
- modules/mobile/docs/schemas/CreateDependents.yml

**Comment by sortizsh** [comment]
Laura will forward the Contact Center's email to Dewayne for additional context on the issue described above.

**Comment by MadBomber** [comment]
I am still working this spike.  In tracing all the ends and outs of the data and control flows I may have discovered a business logic error with regard to the field `net_worth_over_limit_ind`  in the `vets-api` repo.  There are only a few files where this field by name is being set.  Generally its be set to the value produced by a method `formatted_boolean` which takes a single parameter as input and returns either nil, "Y" or "N" based on the input.  It does this by testing the input value for nil.  If it is nil, the method returns nil.

The method then does a boolean test and returns "Y" when true, or "N" when faluse.

The problem that I see is that the input value being given to `formatted_boolean` appears to be a number.  In Ruby a number will *always* test as true.  Unless I've missed some other processing, I do not see any way the `net_worth_over_limit_ind` can ever be set to "N"

There is some processing in which yes/no questions are being added to a form with a hard-coded dollar amount:
lib/pdf_fill/forms/va686c674.rb:       

```ruby
      def add_household_income
        net_worth = @form_data.dig('dependents_application', 'household_income')
        "Did the household have a net worth greater than $130,773 in the last tax year? #{format_boolean(net_worth)}"
      end
```

**Comment by MadBomber** [comment]
I asked for and received additional context information regarding this spike.  That material is included below.

The following statements standout to me:
- Pension is not able to move forward until data is passed to RBPS.  Information being received, but not passed to RBPS for 686c form.
- Working in LINKTEST, but not in Production.  Service itself is populating in Prod test. 

I believe this is consistent with what @tblackwe mentioned a few weeks ago regarding some "logic" being turned off in production but turned on in the staging environment.  This is generally done using a feature enablement mechanisim called a "flipper" which allows different features in the software to be turned on and off under various conditions.  In this case we may have a flipper set on for staging but off for production.

## Additional Context

<div class="is-banner-signature" id="eyJ0eXBlIjoic2lnaHRzLWJhbm5lciIsIm5vcm10ZXh0IjoiaW50ZXJsYWNlZGNvdWxkbnRyZWNvZ25pemV0aGlzZW1haWxhc3RoaXNpc3RoZWZpcnN0dGltZXlvdXJlY2VpdmVkYW5lbWFpbGZyb210aGlzc2VuZGVybGF1cmFzdGVlbGVjb2Zvcm1haW8ifQ:1rY8xM:oTAN5NrGP4-7B94wLNE1oUvauLk" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Helvetica; font-size: 24px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><div>
  | INTERLACED couldn't recognize this email as this is the first time you received an email from this sender laura.steele @ coforma.io
-- | --


</div><br></div><div dir="ltr" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Helvetica; font-size: 24px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Dewayne,<div><br></div><div>Here is the original thread we were looped in on (without any context). I've highlighted the specific request around net worth info. If we have additional questions for the team that sent this inquiry request, please let me know and we can either reach out to them via email or set up a meeting to discuss.</div><div><br></div><div>Thanks,</div><div><br></div><div>Laura<br><br><div class="gmail_quote"><div dir="ltr" class="gmail_attr">---------- Forwarded message ---------<br>From:<span class="Apple-converted-space"> </span><strong class="gmail_sendername" dir="auto">Theis, Emily J.</strong><span class="Apple-converted-space"> </span><span dir="auto">&lt;<a href="mailto:Emily.Theis@va.gov">Emily.Theis@va.gov</a>&gt;</span><br>Date: Fri, Jan 12, 2024 at 1:36 PM<br>Subject: FW: Request<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>input for RBPS April SRs<br>To: Laura Steele &lt;<a href="mailto:laura.steele@coforma.io">laura.steele@coforma.io</a>&gt;<br></div><br><br><div class="msg4938790843065660087"><div lang="EN-US" link="#0563C1" vlink="#954F72" style="overflow-wrap: break-word;"><div class="m_4938790843065660087WordSection1"><p class="MsoNormal">I believe this is the bulk of the requests.<u></u><u></u></p><p class="MsoNormal"><u></u> <u></u></p><div><div style="border-width: 1pt medium medium; border-style: solid none none; border-color: rgb(225, 225, 225) currentcolor currentcolor; border-image: none; padding: 3pt 0in 0in;"><p class="MsoNormal"><b>From:</b><span class="Apple-converted-space"> </span>Raidt, Renee R., VBAVACO &lt;<a href="mailto:RENEE.RAIDT@va.gov" target="_blank">RENEE.RAIDT@va.gov</a>&gt;<span class="Apple-converted-space"> </span><br><b>Sent:</b><span class="Apple-converted-space"> </span>Wednesday, November 29, 2023 4:20 PM<br><b>To:</b><span class="Apple-converted-space"> </span>Theis, Emily J. &lt;<a href="mailto:Emily.Theis@va.gov" target="_blank">Emily.Theis@va.gov</a>&gt;<br><b>Cc:</b><span class="Apple-converted-space"> </span>Braddock, Nicholas, VBAVACO &lt;<a href="mailto:Nicholas.Braddock@va.gov" target="_blank">Nicholas.Braddock@va.gov</a>&gt;; Reeher, Elizabeth M., (Evoke) &lt;<a href="mailto:Elizabeth.Reeher@va.gov" target="_blank">Elizabeth.Reeher@va.gov</a>&gt;; Nelson, Riani B. (BAH) &lt;<a href="mailto:Riani.Nelson@va.gov" target="_blank">Riani.Nelson@va.gov</a>&gt;; Ciston, Linda C., (BAH) &lt;<a href="mailto:linda.ciston@va.gov" target="_blank">linda.ciston@va.gov</a>&gt;; Abu Khaled, Baha Eddin S. (BAH) &lt;<a href="mailto:BahaEddin.AbuKhaled@va.gov" target="_blank">BahaEddin.AbuKhaled@va.gov</a>&gt;<br><b>Subject:</b><span class="Apple-converted-space"> </span>Request<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>input for RBPS April SRs<span class="Apple-converted-space"> </span><u></u><u></u></p></div></div><p class="MsoNormal"><u></u> <u></u></p><p class="MsoNormal">Hello Emily,<u></u><u></u></p><p class="MsoNormal"><u></u> <u></u></p><p class="MsoNormal">Please see the following RBPS (SRs) Service Requests discussed with you on the RBPS April requirements Pt5 call, to provide<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>input.  Let us know if you have additional questions.<u></u><u></u></p><p class="MsoNormal"><u></u> <u></u></p><p class="MsoNormal"><a id="m_4938790843065660087OWAAM01155F1AA3DC4256A5DE63215C0CC228" href="mailto:linda.ciston@va.gov" target="_blank"><span style="font-family: Calibri, sans-serif; text-decoration: none;">@Ciston, Linda C., (BAH)</span></a><span class="Apple-converted-space"> </span>&amp;<span class="Apple-converted-space"> </span><a id="m_4938790843065660087OWAAMB506781FEF624FCBB58DA2FC48DC62D5" href="mailto:BahaEddin.AbuKhaled@va.gov" target="_blank"><span style="font-family: Calibri, sans-serif; text-decoration: none;">@Abu Khaled, Baha Eddin S. (BAH)</span></a><span class="Apple-converted-space"> </span>I am requesting BIS team pull volume of claims eligible for pension and in receipt of pension going to manual per month for :BEPBGS-3942 RBPS: When Using<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>to Enter Both Ex Spouse and New Spouse, No award given for Ex Spouse.<u></u><u></u></p><p class="MsoNormal"><u></u> <u></u></p><ul type="disc" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;">BEPBGS-3984 RBPS- Request Pension removal of 30% Service Connected (SC) rating criteria for Pension claims ITRP 4618. (<span style="background-color: rgb(255, 255, 0);">Related to BEPBGS-4091</span>)    <u></u><u></u></li></ul><p class="m_4938790843065660087MsoListParagraph">Description: Specifically<span style="font-size: 10.5pt; font-family: -apple-system; color: rgb(23, 43, 77); background: white;"><span class="Apple-converted-space"> </span>for Pension Claimants/Pension related RBPS claims, we would like to remove the 30% SC rating criteria that is currently a mandatory requirement for all RBPS dependency submissions to allow Pension claims to continue to pass through the RBPS rules and potentially to completion. Currently the 30% rating criteria is embedded into many of the RBPS rules including those associated to how RBPS determines the effective date of any dependency updates.</span><span style="color: rgb(0, 112, 192);"><u></u><u></u></span></p><ul type="disc" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0.25in;">Pension is not able to move forward until data is passed to RBPS.  Information being received, but not passed to RBPS for 686c form.<u></u><u></u></li><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0.25in;">Working in LINKTEST, but not in Production.  Service itself is populating in Prod test. <u></u><u></u></li><ul type="circle" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0.25in;"><b>Action Emily Theis: BIS need someone on<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>to look and see if they are calling and if putting those values in for net worth and over limit. <u></u><u></u></b></li><ul type="square" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0.25in;"><b>If getting an error, need to know what error is.<u></u><u></u></b></li></ul><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0.25in;"><b>Add BIS Linda Ciston, Baha Khaled and Sebastian Thomas for meeting invite to discuss.<u></u><u></u></b></li></ul><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0.25in;">BIS can put code in, but if<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>&amp; CRM are not sending the data, this is a large effort to address if the data is not able to be processed.<u></u><u></u></li><ul type="circle" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0.25in;"><b>Action Emily Theis: What version date and example of the 686c form<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>is using?<u></u><u></u></b></li></ul></ul><ul type="disc" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;"><span style="background-color: rgb(255, 255, 0);">BEPBGS-4091 Investigate why Pension not receiving net worth over limit indicator. ITRP 4772 (BEPBGS-3984)<u></u><u></u></span></li></ul><p class="m_4938790843065660087MsoListParagraph"><span style="background-color: rgb(255, 255, 0);">Description: Needs to be researched for both CRM and<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>for that field- “net worth over limit indicator”. Not seeing any claims for these fields at all. BIS to look and see why they are not getting that field or why it’s not being saved.</span><u></u><u></u></p><p class="m_4938790843065660087MsoListParagraph"><u></u> <u></u></p><p class="m_4938790843065660087MsoListParagraph"><u></u> <u></u></p><ul type="disc" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;">BEPBGS-3942     RBPS: When Using<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>to Enter Both Ex Spouse and New Spouse, No award given for Ex Spouse ITRP 4592 (Related to BEPBGS-4451)<u></u><u></u></li></ul><p class="m_4938790843065660087MsoListParagraph">Description: When using<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>to add and then remove a former spouse while adding a new spouse to the award.<u></u><u></u></p><p class="m_4938790843065660087MsoListParagraph">The former spouse was eligible to be added to the award for the time they were married to the veteran, and the new spouse will be added to the running award from the date of marriage.<u></u><u></u></p><p class="m_4938790843065660087MsoListParagraph">Expected Results: The former spouse is added to the award at the effective date of the rating and removed at the date of the termination of marriage. The new spouse is added to the award on the effective date of marriage.<u></u><u></u></p><p class="m_4938790843065660087MsoListParagraph">CRM- limited input of previous spouse.  Are they putting ex-spouse and marriage dates.<u></u><u></u></p><p class="m_4938790843065660087MsoListParagraph">If was ex-spouse, if spouse could be added. Set to manual.<u></u><u></u></p><ul type="disc" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;">BIS to look at<span class="Apple-converted-space"> </span><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>input.<u></u><u></u></li><ul type="circle" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;"><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>to provide a screen shot for ex-spouse, if adding a new spouse or removing a spouse.<u></u><u></u></li><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;">Per BIS Linda Ciston - We do have an active Prod issue.  All claims eligible for pension and in receipt of pension, go to manual.  Reported previously.  Prod issue now.  Will be more of an issue when make the pension change.<u></u><u></u></li><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;"><b><span style="color: rgb(68, 114, 196);">Action BIS Linda/Baha: Volume per month affected</span></b><span style="color: rgb(68, 114, 196);">. <span class="Apple-converted-space"> </span></span>Linda - Anyone eligible for pension, goes to manual.<u></u><u></u></li><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;">Once volume provided, can prioritize against other issues.<u></u><u></u></li></ul><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;">BEPBGS-4451 RBPS: Research input of ex-spouse when incomplete. Are marriage begin and end date populated? ITRP 5393 (Related to BEPBGS-3942)<u></u><u></u></li></ul><p class="MsoNormal"><b><span style="color: black;"><u></u> <u></u></span></b></p><ul type="disc" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="margin-left: 0in;">BEPBGS-1079     Modify Automated 686 input processes to store new form fields (removal of dependents) ITRP 1622 CUS.<u></u><u></u></li></ul><p class="MsoNormal" style="margin-left: 0.5in;"><span style="color: black;">New field for type of marriage, if not 1 of 2</span>responses:<span style="color: black;"><span class="Apple-converted-space"> </span>(Church marriage or courthouse), will go to manual.  Like Trible marriage. If turn on requirement for checking new fields, if new fields are populated, would all go to manual that have that information.<u></u><u></u></span></p><ul type="disc" style="margin-top: 0in;"><ul type="circle" style="margin-top: 0in;"><li class="m_4938790843065660087MsoListParagraph" style="color: black; margin-left: 0in;">Which 686c form version date are the marriage questions based off? <span class="Apple-converted-space"> </span><u></u><u></u></li><li class="m_4938790843065660087MsoListParagraph" style="color: black; margin-left: 0in;">Can you provide an example<span class="Apple-converted-space"> </span><span style="color: windowtext;">of<span class="Apple-converted-space"> </span></span>the current version of the 686c form<span class="Apple-converted-space"> </span><span style="color: windowtext;"><a href="http://va.gov/">VA.gov</a><span class="Apple-converted-space"> </span>is</span><span class="Apple-converted-space"> </span>using?<u></u><u></u></li></ul></ul><p class="MsoNormal"><span style="color: black;"><u></u> <u></u></span></p><p class="MsoNormal"><span style="font-size: 12pt; font-family: Arial, sans-serif;"><u></u> <u></u></span></p><div><p class="MsoNormal"><b>Renee Raidt, MHR<u></u><u></u></b></p><p class="MsoNormal"><span style="font-size: 10pt;">Program Analyst<u></u><u></u></span></p><p class="MsoNormal"><span style="font-size: 10pt;">Benefits Systems Management<u></u><u></u></span></p><p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; color: black;">Office of Business Integration (20C)<u></u><u></u></span></p><p class="MsoNormal"><span style="font-size: 10pt;">C: (425) 553-8499<u></u><u></u></span></p><p class="MsoNormal">USMC Veteran<u></u><u></u></p><p class="MsoNormal"><img id="<ii_18d89ea634d4cff311>" src="cid:ii_18d89ea634d4cff311" alt="image001.png" border="0" class="Apple-web-attachment Apple-edge-to-edge-visual-media Singleton" style="width: 2.4583in; height: 0.8333in; opacity: 1;"><u></u><u></u></p></div><p class="MsoNormal"><span style="font-size: 12pt; font-family: Arial, sans-serif;"><u></u> <u></u></span></p><p class="MsoNormal"><u></u> <u></u></p></div></div></div></div><br clear="all"><div><br></div><span class="gmail_signature_prefix">--<span class="Apple-converted-space"> </span></span><br><div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature"><div><p style="color: rgb(89, 89, 89); font-family: Roboto, &quot;Trebuchet MS&quot;, sans-serif; font-size: small; letter-spacing: 0.01em; margin: 10px 0px 0px; line-height: 1.35;"><strong style="color: rgb(44, 44, 44);">Laura Steele</strong>  She/Her<br>Senior Product Manager<br>M 608.513.2935  <span class="Apple-converted-space"> </span><a href="mailto:Laura.Steele@coforma.io" target="_blank" style="color: rgb(89, 89, 89);">Laura.Steele@coforma.io</a><span class="Apple-converted-space"> </span> <span class="Apple-converted-space"> </span><br><br><a href="https://coforma.io/" target="_blank"><img width="116" src="https://coforma.io/media/images/coforma_navy.original.jpg" style="width: 116px; min-width: 116px; max-width: 116px; border-radius: 1px;"></a><br><a href="https://www.google.com/url?q=http://eepurl.com/heJi_z&amp;sa=D&amp;source=editors&amp;ust=1643297602325558&amp;usg=AOvVaw1J-DdcC2O0yRWuamGitbuT" target="_blank" style="color: rgb(37, 114, 228); line-height: 2; margin-top: 2px; display: inline-block;">Get our newsletter</a></p></div></div></div></div>INTERLACED couldn't recognize this email as this is the first time you received an email from this sender laura.steele @ [coforma.io](http://coforma.io/)

Dewayne,

Here is the original thread we were looped in on (without any context). I've highlighted the specific request around net worth info. If we have additional questions for the team that sent this inquiry request, please let me know and we can either reach out to them via email or set up a meeting to discuss.

Thanks,

Laura

---------- Forwarded message ---------
From: Theis, Emily J. <[Emily.Theis@va.gov](mailto:Emily.Theis@va.gov)>
Date: Fri, Jan 12, 2024 at 1:36 PM
Subject: FW: Request [VA.gov](http://va.gov/) input for RBPS April SRs
To: Laura Steele <[laura.steele@coforma.io](mailto:laura.steele@coforma.io)>


I believe this is the bulk of the requests.

 

From: Raidt, Renee R., VBAVACO <[RENEE.RAIDT@va.gov](mailto:RENEE.RAIDT@va.gov)>
Sent: Wednesday, November 29, 2023 4:20 PM
To: Theis, Emily J. <[Emily.Theis@va.gov](mailto:Emily.Theis@va.gov)>
Cc: Braddock, Nicholas, VBAVACO <[Nicholas.Braddock@va.gov](mailto:Nicholas.Braddock@va.gov)>; Reeher, Elizabeth M., (Evoke) <[Elizabeth.Reeher@va.gov](mailto:Elizabeth.Reeher@va.gov)>; Nelson, Riani B. (BAH) <[Riani.Nelson@va.gov](mailto:Riani.Nelson@va.gov)>; Ciston, Linda C., (BAH) <[linda.ciston@va.gov](mailto:linda.ciston@va.gov)>; Abu Khaled, Baha Eddin S. (BAH) <[BahaEddin.AbuKhaled@va.gov](mailto:BahaEddin.AbuKhaled@va.gov)>
Subject: Request [VA.gov](http://va.gov/) input for RBPS April SRs

 

Hello Emily,

 

Please see the following RBPS (SRs) Service Requests discussed with you on the RBPS April requirements Pt5 call, to provide [VA.gov](http://va.gov/) input.  Let us know if you have additional questions.

 

[@Ciston, Linda C., (BAH)](mailto:linda.ciston@va.gov) & [@Abu Khaled, Baha Eddin S. (BAH)](mailto:BahaEddin.AbuKhaled@va.gov) I am requesting BIS team pull volume of claims eligible for pension and in receipt of pension going to manual per month for :BEPBGS-3942 RBPS: When Using [VA.gov](http://va.gov/) to Enter Both Ex Spouse and New Spouse, No award given for Ex Spouse.

 

BEPBGS-3984 RBPS- Request Pension removal of 30% Service Connected (SC) rating criteria for Pension claims ITRP 4618. (Related to BEPBGS-4091)    
Description: Specifically for Pension Claimants/Pension related RBPS claims, we would like to remove the 30% SC rating criteria that is currently a mandatory requirement for all RBPS dependency submissions to allow Pension claims to continue to pass through the RBPS rules and potentially to completion. Currently the 30% rating criteria is embedded into many of the RBPS rules including those associated to how RBPS determines the effective date of any dependency updates.

Pension is not able to move forward until data is passed to RBPS.  Information being received, but not passed to RBPS for 686c form.
Working in LINKTEST, but not in Production.  Service itself is populating in Prod test. 
Action Emily Theis: BIS need someone on [VA.gov](http://va.gov/) to look and see if they are calling and if putting those values in for net worth and over limit. 
If getting an error, need to know what error is.
Add BIS Linda Ciston, Baha Khaled and Sebastian Thomas for meeting invite to discuss.
BIS can put code in, but if [VA.gov](http://va.gov/) & CRM are not sending the data, this is a large effort to address if the data is not able to be processed.
Action Emily Theis: What version date and example of the 686c form [VA.gov](http://va.gov/) is using?
BEPBGS-4091 Investigate why Pension not receiving net worth over limit indicator. ITRP 4772 (BEPBGS-3984)
Description: Needs to be researched for both CRM and [VA.gov](http://va.gov/) for that field- “net worth over limit indicator”. Not seeing any claims for these fields at all. BIS to look and see why they are not getting that field or why it’s not being saved.

 

 

BEPBGS-3942     RBPS: When Using [VA.gov](http://va.gov/) to Enter Both Ex Spouse and New Spouse, No award given for Ex Spouse ITRP 4592 (Related to BEPBGS-4451)
Description: When using [VA.gov](http://va.gov/) to add and then remove a former spouse while adding a new spouse to the award.

The former spouse was eligible to be added to the award for the time they were married to the veteran, and the new spouse will be added to the running award from the date of marriage.

Expected Results: The former spouse is added to the award at the effective date of the rating and removed at the date of the termination of marriage. The new spouse is added to the award on the effective date of marriage.

CRM- limited input of previous spouse.  Are they putting ex-spouse and marriage dates.

If was ex-spouse, if spouse could be added. Set to manual.

BIS to look at [VA.gov](http://va.gov/) input.
[VA.gov](http://va.gov/) to provide a screen shot for ex-spouse, if adding a new spouse or removing a spouse.
Per BIS Linda Ciston - We do have an active Prod issue.  All claims eligible for pension and in receipt of pension, go to manual.  Reported previously.  Prod issue now.  Will be more of an issue when make the pension change.
Action BIS Linda/Baha: Volume per month affected.  Linda - Anyone eligible for pension, goes to manual.
Once volume provided, can prioritize against other issues.
BEPBGS-4451 RBPS: Research input of ex-spouse when incomplete. Are marriage begin and end date populated? ITRP 5393 (Related to BEPBGS-3942)
 

BEPBGS-1079     Modify Automated 686 input processes to store new form fields (removal of dependents) ITRP 1622 CUS.
New field for type of marriage, if not 1 of 2 responses: (Church marriage or courthouse), will go to manual.  Like Trible marriage. If turn on requirement for checking new fields, if new fields are populated, would all go to manual that have that information.

Which 686c form version date are the marriage questions based off? 
Can you provide an example of the current version of the 686c form [VA.gov](http://va.gov/) is using?
 

 

Renee Raidt, MHR

Program Analyst

Benefits Systems Management

Office of Business Integration (20C)

C: (425) 553-8499

USMC Veteran

image001.png

 

 



--
Laura Steele  She/Her
Senior Product Manager
M 608.513.2935   [Laura.Steele@coforma.io](mailto:Laura.Steele@coforma.io)  


[Get our newsletter](https://www.google.com/url?q=http://eepurl.com/heJi_z&sa=D&source=editors&ust=1643297602325558&usg=AOvVaw1J-DdcC2O0yRWuamGitbuT)

**Comment by sortizsh** [comment]
need a new ticket - do we turn this on or leave it off, and they just wanted the research completed? Laura will work with Thomas to draft a reply in the email.

**Comment by steele-lm** [comment]
Send email to Emily detailing our findings (flipper and a failed service) and requesting confirmation of priority.

**Comment by steele-lm** [comment]
@tblackwe Do we also need to look into fixing the potential logic error uncovered as part of this spike (see comment from 2/8)?

**Comment by steele-lm** [comment]
Marking as closed. We have follow on tickets to address debugging and confirming logic in our backlog and we will action when directed.

**Comment by MadBomber** [comment]
The associated feature flipper may be:
```
  dependents_enqueue_with_user_struct:
    actor_type: user
    description: Manage whether the enqueued job for 686c and 674 will be with a User model or the new User struct
    enable_in_development: true
  dependents_pension_check:
    actor_type: user
    description: Manage whether or not Pension check is enabled for the 686/674
    enable_in_development: true
```
