### ISSUE TITLE
[BE] Implement GET demographics data method in mobile proxy service client class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73691]
## Description
Implement method for getting patient's demographics data in mobile proxy service client class

## Tasks
- [ ] [BE] **GET demographics data implementation**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
