### ISSUE TITLE
[BE] Implement mobile proxy service class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73692]
## Description
Implement service class for mobile proxy service 

## Tasks
- [ ] [BE] **Implement mobile proxy service class**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
