### ISSUE TITLE
[BE] Implement GET demographics data method in Mobile Proxy Service class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73693]
## Description
Implement GET demographics data method in Mobile Proxy Service class

## Tasks
- [ ] [BE] **Implement GET demgraphics data method in mobile proxy service class**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
