### ISSUE TITLE
By Light Discovery and Logistics Epic

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#737]
## High Level User Story
As a team member, I need to view all documentation for tools like Slack and Zenhub.

## Hypothesis/(es)
**If** _we provide documentation and quality links_ **then** _our team benefits_.

## Goals
_All team members have access and ready use of documentation_ 

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`)

## Definition of Done
- [ ] **Labeled with Team** (`product support`)
- [ ] **Labeled with Onboarding Team** (`By Light`)
- [ ] **Labeled with `Epic`**
