### ISSUE TITLE
[BE] Implement serializer for processing demographics data response from mobile proxy service

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73709]
## Description
Implement serializer for processing demographics data response from mobile proxy service

## Tasks
- [ ] [BE] **Create mobile proxy service serializer class for demographics data**
- [ ] [BE] **Implement response payload processing**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
