### ISSUE TITLE
Update DataDog Access Documents

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#73707]
## Description 
We realized that there are several documents floating around around DataDog access. At the moment we have:

- [Get Access to DataDog](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2529591336/Get+Access+to+Datadog) (Confluence Page Pointing to VFS Platform Site)
- Get Access to DataDog (Confluence Page in Infrastructure Team Section), we removed the content since it is duplicated on the page above and simply pointed to the page above instead (more recently updated anyway).
- Granting Access to DataDog (Confluence page specific to the steps that Platform Support Team needs to know, both the tasks they perform and the teams who perform the rest of the steps, draft currently)

We want to be sure that we:

- Create one source of truth for Confluence back-end docs (Platform Support section)
- Ensure the Platform Site content is the most up-to-date information for current DataDog processes

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Ensure the public facing site is updated and is accurate. If there is a discrepancy reach out to Alyssa for the next steps. 
- [x] Ensure the Granting Access to DataDog page has all steps listed for granting access with explicit notes on what teams own which piece: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2906849396/Granting+Access+to+DataDog+-+DRAFT
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
https://vfs.atlassian.net/wiki/spaces/PTST/pages/2906849396/Granting+Access+to+DataDog
