### ISSUE TITLE
[BE] Implement method to set the confirmation timestamp in mobile proxy service client class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73710]
## Description
[BE] Implement method to set the confirmation timestamp in mobile proxy service client class

## Tasks
- [ ] [BE] **Implement method to set confirmation timestamp**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
