### ISSUE TITLE
[BE] Implement controller for setting demographics confirmation in VA profile

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73713]
## Description
Implement controller for setting demographics confirmation in VA profile

## Tasks
- [ ] [BE] **Implement control for setting demographics confirmation timestamp**
- [ ] [BE] **Add request specs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
