### ISSUE TITLE
[BE] Implement cerner checkin client class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73717]
## Description
Implement cerner checkin client class

## Tasks
- [ ] [BE] **Implement cerner checkin client class**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
