### ISSUE TITLE
Update VFS Roster Management/Atlas App Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#73715]
## Description 
We realized that there are several documents floating around around VFS Roster/Atlas. At the moment we have:

- [x] [New VFS Teams](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2061959315/New+VFS+Teams) (governance owned document)
- [x] [New VFS Team Members] (https://vfs.atlassian.net/wiki/spaces/PPS/pages/2041086016/New+VFS+team+members) (Governance owned document)
- [x] [Atlas Management for New VFS Teams/Team Members](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2798846283/VFS+Roster+Management?focusedCommentId=2813853787) 
- [x] [Atlas User Manual](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2806841369/Atlas+User+Manual)

We want to be sure that we:

- Create one source of truth for Confluence docs (Platform Support section)
- Make sure the VFS Roster Management page reflects Platform Support responsibilities and points to the Atlas User Manual where appropriate

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Create one source of truth for Confluence docs (Platform Support section)
- [x] Make sure the VFS Roster Management page reflects Platform Support responsibilities and points to the Atlas User Manual where appropriate
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Wait to start this work until you've received the training on the process.

**Comment by bdech** [comment]
VFS Roster Management has been re-named to Atlas Management for New VFS Teams/Team Members

**Comment by bdech** [comment]
Platform Governance article has been slightly edited to reflect current processes with Atlas

**Comment by bdech** [comment]
Platform Governance article on [New VFS Teams](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2061959315/New+VFS+Teams) has been updated to reflect current processes with Atlas

**Comment by bdech** [comment]
Final source of truth: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2798846283/Atlas+Management+for+New+VFS+Teams+Team+Members

**Comment by bdech** [comment]
@alyssagallion This is completed. Closing sprint ticket
