### ISSUE TITLE
[BE] Modify env-settings.yml in devops repo for adding mobile proxy service endpoint

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73712]
## Description
Modify `dev-settings.local.yml`, `staging-settings.local.yml`, `prod-settings.local.yml` in devops repo for adding mobile proxy service endpoint

## Tasks
- [ ] [BE] **Modify `dev-settings.local.yml`**
- [ ] [BE] **Modify `staging-settings.local.yml`**
- [ ] [BE] **Modify `prod-settings.local.yml`**

## Acceptance Criteria
- [ ] Deployed to dev,staging,prod
- [ ] Tested on dev,staging,prod
