### ISSUE TITLE
[BE] Implement method to set the confirmation timestamp in Mobile profile service class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73711]
## Description
Implement method to set the confirmation timestamp in Mobile profile service class

## Tasks
- [ ] [BE] **Implement set confirmation timestamp method**
- [ ] [BE] **Adding rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore

**Comment by kanchanasuriya** [comment]
Not required anymore

**Comment by kanchanasuriya** [comment]
Not required anymore
