### ISSUE TITLE
Remove 2 broken links from VR&E eligibility page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#73722]
## Issue Description
We have 2 broken links pointing to benefits.va.gov. One is to a PDF and the other is to an XLS file. We need to remove these so users don't encounter broken links and can then reach out to stakeholders to determine if there is somewhere better to point to. 

The links are both under "Get more information."
- [Download the NPWE program fact sheet (PDF)](https://benefits.va.gov/BENEFITS/factsheets/vocrehab/Non-paidWorkExperience.pdf)
- [Find an employment coordinator near you](https://www.benefits.va.gov/VOCREHAB/docs/EmploymentCoordinators.xlsx)

## Tasks
- [ ] Remove links (Randi)
- [ ] Copyedit and publish (Megan/Chelsea)
- [ ] Reach out to stakeholder (Randi)

## Acceptance Criteria
- [ ] Broken links are no longer live on the site

**Comment by RLHecht** [comment]
@megzehn @chelsealevinson We had 2 broken links on this page that I removed. Can one of you please check my changes and publish the page? I'll figure out who to reach out to for replacement info. Thank you!

**Comment by megzehn** [comment]
Thanks for flagging and making those changes, @RLHecht!

Confirming I reviewed and published the page. I'll leave this open until we learn about replacement info.

**Comment by RLHecht** [comment]
I think this is good to close. Thanks!
