### ISSUE TITLE
Test impact of removing logging on linting job in CI

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#73725]
## Issue Description
When CI merges to main, the linting job takes in excess of 30 minutes at times to run. One theory is that the logging of all 12,000+ warnings is slowing down the process. Switching off the logging may speed up the process. We should test this and implement it if results appear positive.

---
## Tasks
- [ ] Disable logging warnings (leave errors logging out as they are).
- [ ] Run the linting job and see if the job speeds up.
- [ ] Merge the PR if the results appear good

## Acceptance Criteria
- [ ] The results of the removal of the logging are evaluated and implemented if appropriate
---
