### ISSUE TITLE
Debt portal unmoderated study [planning]

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#73734]
## Description

Continue working on unmoderated research study for Debt Portal using Optimal Workshop
## Tasks
- [ ] Speak to CAIA if time allows (Danielle, Mikki)
- [ ] Determine card sort content 
- [ ] Determine cohorts
- [ ] Submit Research study to [Research Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)

## Acceptance criteria

- [ ] Research plan defined
- [ ] Research plan submitted

## Testing
- [x] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
We plan to proceed with a moderated study; moving this to Backlog for now.

**Comment by HeatherRienks** [comment]
Per Design Sync on 5/1/24, team has decided to put this on hold- will move to Icebox for now. Denise will help with prioritizing.

**Comment by denisecoveyduc** [comment]
UX Team will run a moderated study. Closing this as it is no longer needed
