### ISSUE TITLE
Count of 686 Claims Set to Manual Processing

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73746]
## Issue Description
_Request from OBI: We are trying to identify counts for the number of dependency cases that VA.gov is setting to manual processing (i.e. not sending to RBPS for automated processing) due to new fields on the 686c form._

OBI believes a discrepancy between the most recent version of the pdf form and the version the online 686c form generates may be source of many of the manual "flips:
- The new version of the 686c pdf (AUG 2022) separates civil and religious ceremony into two options:
<img width="903" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad49b7c2f54db7ecb8f6614cc2d4ed20a646f578/image.png" alt="image.png" />

- While the old version the online form uses (SEP 2018) does not:
<img width="741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94c390cedf7181aa392267bd1dc9f5b687c09a56/image.png" alt="image.png" />

---
## Tasks
- [ ] Identify how many 686c applications per month (for the last 12 months) are being set to manual processing by VA.gov.
- [x] Identify the reason each claim is set to manual processing
   - From OBI: Are there any other fields on the 686c form you are setting to manual because RBPS is unable to process?  We received the list below from RBPS that is supposed to be the reasons VA.gov is setting dependency claims to manual, but only the highlighted one appears related to the new 686c form:
     - AND note_txt NOT IN ('Claim set to manual by VA.gov: This application needs manual review because a 674 was submitted.'
     - ,'Claim set to manual by VA.gov: This application needs manual review because a 686 was submitted along with a 674.'
     - **,'Claim set to manual by VA.gov: This application needs manual review because a 686 was submitted to add a spouse due to civic/non-ceremonial marriage.'**
     - ,'Claim set to manual by VA.gov: This application needs manual review because a 686 was submitted for removal of a schoolchild over 18 who has stopped attending school.'
     - ,'Claim set to manual by VA.gov: This application needs manual review because a 686 was submitted for removal of a step-child that has left household.'
     - ,'Claim set to manual by VA.gov: This application needs manual review because a 686 was submitted for removal of a married minor child.'
     - ,'Claim set to manual by VA.gov: This application needs manual review because a 686 was submitted for removal of a child/dependent parent due to death.'

## Acceptance Criteria
- [ ] Report (csv) that contains:
   - [ ] The number of 686c claims VA.gov identifies for manual processing each month for the last 12 months
   - [ ] The reason each claims is marked for manual processing 
---

**Comment by tblackwe** [comment]
<img width="1725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzlWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e919c0044146d855c702cf261f7770a50ceee14f/image.png" alt="image.png" />

**Comment by tblackwe** [comment]
[Link to query](https://vagov.ddog-gov.com/logs?query=%40payload.txt%3AClaim%5C%20set%5C%20to%5C%20manual%5C%20by%2A%20&agg_m=count&agg_m_source=base&agg_q=%40payload.txt&agg_q_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.txt&index=%2A&messageDisplay=inline&refresh_mode=paused&sort_m=&sort_t=&storage=online_archives&stream_sort=desc&top_n=10&top_o=top&viz=toplist&x_missing=true&from_ts=1675227600000&to_ts=1706849940000&live=false)

**Comment by steele-lm** [comment]
Email sent to Nick Braddock and team (cc Emily) with report results.
