### ISSUE TITLE
[FSR Wizard] Prototype for Updated Wizard (Complete a subtask)

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#73744]
## Description

For the wizard research, we'll need to test the updated content and logic of the new complete a subtask pattern; utilizing CodePen to create an accessible prototype to for the upcoming wizard study.

Scenario: In common language describe the work or issue

Given: A veteran wants to fill out the FSR
When: A veteran wants to determine whether or not the FSR is for them
Then: A veteran will be able to click through the new wizard and get the answer they need

## Tasks
- [x] Create a prototype with content and flow from [updated Figma files](https://www.figma.com/file/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---Streamlined-Waiver?type=design&node-id=24-25440&mode=design&t=7qLZbWDCk60EPpeX-11)

## Acceptance criteria

- [x] Prototype has been created
- [x] Prototype has been QA'd

## Testing
- [x] Test logic and paths go to correct results
- [x] Test with screen reader to make sure the prototype is accessible 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
Here's a link to the collection I created: https://codepen.io/collection/yreymk

Here's a link to the prototype: https://cdpn.io/pen/debug/NWJRVez

**Comment by josephrlee** [comment]
The prototype is complete for now, but it can easily be edited if needed once we hear any additional feedback from CAIA. However for it to work seamlessly, we'll need to upgrade to at least a Pro account to have the page linking work properly. Without the pro version, linking between pages gets really silly because every time you do, it opens it up inside of a new `iframe` and you get this:

<img width="814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekRpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19d05e1d1c69070318f516ed60b526d009f324fb/Screenshot%202024-01-19%20at%2012.51.06%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 12.51.06 PM.png" />

cc: @HeatherRienks  @Tom-Davis @mgleo @charlottecesana

**Comment by josephrlee** [comment]
I'm going to move this into blocked for now until we can fix it with the Pro version. 

@HeatherRienks @Tom-Davis

**Comment by josephrlee** [comment]
We can mark this as closed now. I misread that I was waiting until we got the PRO version of CodePen to mark this as done! 

cc: @HeatherRienks @Tom-Davis
