### ISSUE TITLE
Test removing logging from CI linting job in vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#73741]
## Issue Description
When CI merges to main, the linting job takes in excess of 30 minutes at times to run. One theory is that the logging of all 12,000+ warnings is slowing down the process. Switching off the logging may speed up the process. We should test this and implement it if results appear positive.

---
## Tasks
- [x] Disable logging warnings (leave errors logging out as they are).
- [x] Run the linting job and see if the job speeds up.
- [ ] Merge the PR if the results appear good

## Acceptance Criteria
- [x] The results of the removal of the logging are evaluated and implemented if appropriate
---

**Comment by CBonade** [comment]
In my initial findings were that the eslint annotation warning logs being removed reduced the time it takes for the workflow to run by a few minutes vs the average it takes to run in main now. However, a side discovery of this work was that the same eslint annotation script is shared between the PR workflow and the main workflow. We ideally would like to maintain the PR warnings so developers still get those on their PRs while removing the warnings on the main runs. Therefore, the script will need to be reworked using either an environmental variable, or split into two scripts. I believe the environmental variable to be the better solution. We can explore this in our CI pipeline improvements efforts.
