### ISSUE TITLE
Update links for pension form reactivation

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#73775]
## Issue Description

This is a ticket for us to track work from the team request here: #73179  

From that ticket:
> - We need to request/work with CAIA to review our URL patterns to follow best practices.
> - More information about [IA Design for Pension Form Reactivation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/pension-form-reactivation.md#url) found here.
> - In the case that our URL structure changes, we will also need to request redirects for these changes.
> - Related ticket for redirect request for Pension form: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15012

---
## Tasks
- [x] Align with team to understand their timeline
- [x] Connect with PW team to establish a plan
- [ ] Create redirect tickets for 1) take down temp redirect and 2) update form URL

## Acceptance Criteria
- [ ] Users can access the form and submit their claim
- [ ] New form URL is up to standards
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jennymayoco** [comment]
#### Notes 2/1/24

- Form just launched and was deactivated so the team can review the ~14 submissions that came in
- Form might be 100% released by end of February, but no specific date yet set
- Team would like to wait until form has been reinstated to 100%
- Question about temporary redirect: Since there's currently a temporary redirect in place, is there a way to codify so that 25% of users that see the form won't be impacted by the redirect? Or should we completely remove the temp redirect?

**Next steps**
- [ ] Connect with Public Websites to see what we should do with the temp redirect
- [ ] Connect with Public Websites if we can time the new URL update with the staged release

**Comment by jennymayoco** [comment]
Update after connecting with PW team: temp redirect request was cancelled and team is using custom implementation instead so that it can be timed with the staged rollout. Pension team wants to wait for 100% release and then we can kick off the process of updating the URL so it's up to date with standards and will create a redirect ticket for that work then

**Comment by jennymayoco** [comment]
The [redirect](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77519) was implemented. Confirming the old URL `www.va.gov/pension/application/527EZ` redirects to `www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez`. There was an issue where if you reloaded the page, a 404 page would appear. This is now fixed so I'm moving this ticket to close
