### ISSUE TITLE
TIC/Snow Process Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#73777]
## Description 

We have received a few requests (and an incident) recently that required the use of TIC/SNOW processes. We need to document those processes in the context of what our team does in the process. 

---

## Definition of Done

All tasks below are complete

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Ask Alyssa to follow up with Michael Chelen for the one pager ([mentioned here](https://dsva.slack.com/archives/C02RLAUM2LV/p1705086144829509?thread_ts=1705011717.683079&cid=C02RLAUM2LV))
- [ ] Document the process that the team follows specific to Platform Support and point to any existing documentation that is helpful for both what we do and for the steps that we do not do ([this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2908454971/TIC+Snow+Tickets))
- [ ] Add a section for SNOW Tickets and point to the new documentation page on the [Advanced Support Best Practices (Tier 1) page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
https://vfs.atlassian.net/wiki/spaces/OT/pages/2485649530/Open+a+ServiceNOW+yourIT+ticket+and+assign+it+to+NOC

---

**Comment by alyssagallion** [comment]
Scheduled a call for @jknipes @bdech to discuss current process.

**Comment by lindsay-insco** [comment]
Going to demo SNOW information for platform team.
