### ISSUE TITLE
FEBE | Profile | Identify maintenance window / service mapping

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#73772]
## Background
Each external service outage is associated with a PagerDuty service, and each PagerDuty service aligns with a maintenance window. The purpose of this ticket is to identify the external services, PagerDuty services, and the associated maintenance outages. This information will enable us to add maintenance windows specifically to the affected portions of the Profile.

## Tasks
- [x] #71748 
- [x] Identify list of Pager Duty services that map to external services.
- [x] Identify maintenance windows that map to Pager Duty services.

## Acceptance Criteria

- [x] BE tickets for creating Pager Duty services and maintenance windows.
- [ ] FE tickets for displaying proper maintenance windows based on outage.

**Comment by tpharrison** [comment]
Reached out to Evan Parish (VA Notify team) to ask if he could provide more details around error code being returned.

**Comment by tpharrison** [comment]
@mtcA6 Let's review these findings before I create additional tickets...
cc/ @adamwhitlock1 

<!DOCTYPE html><p cid="n81" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><br class="Apple-interchange-newline"></p><p cid="n83" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"></p><p cid="n85" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">The table summarizes the existing Profile front end components and how they map to PagerDuty services.</span></p><figure class="md-table-fig table-figure" cid="n2" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;">
Feature | Front End Component Dependency | Pager Duty Service | Backend Systems | Team Owners
-- | -- | -- | -- | --
Rating Info | EVSS (replace with Lighthouse Service) | None | EVSS, BGS | Auth Exp: Profile
Personal Information | VA Profile, MVI | External: Vet360 | VA Pro, MPI | Auth Exp: Profile
Contact Information | VA Profile, MVI | External: Vet360 | VA Pro, MPI | Auth Exp: Profile
Personal Health Care Contacts | --- | External: Vet360 | VA Pro, MPI | MHV Cartography
Military Information | EMIS (replace with External: Vet360) | External: Vet360 | VA Pro | Auth Exp: Profile
C&P Direct Deposit Information | EVSS (replace with Lighthouse Service) | --- | Lighthouse, BGS | Auth Exp: Profile
EDU Direct Deposit Information | --- | External: BGS | BGS | Auth Exp: Profile
Notification Settings | --- | External: Vet360 | VA Pro | Auth Exp: Profile
Connected Apps | --- | --- | --- | Lighthouse?
Account Security | EMIS, MVI | --- | --- | Auth Exp: Profile
Global Profile | All | All | All | Auth Exp: Profile

</figure><p cid="n77" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="em" class="md-pair-s" style="box-sizing: border-box;"><em style="box-sizing: border-box; font-style: italic;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Note: FE components map "VA Profile" to the "Vet360 Service".</span></em></span></p><p cid="n89" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">The following BE tickets will be created for PagerDuty services:</span></p><ul class="ul-list" cid="n92" mdtype="list" data-mark="-" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.5rem; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><li class="md-list-item md-focus-container" cid="n94" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n95" mdtype="paragraph" class="md-end-block md-p md-focus" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="strong" class="md-pair-s md-expand" style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold; color: rgb(222, 222, 222);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Create PagerDuty Service for Lighthouse: Direct Deposit API</span></strong></span></p><ul class="ul-list" cid="n100" mdtype="list" data-mark="-" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative;"><li class="md-list-item" cid="n99" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n97" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">This service will be used to create a maintenance window for Direct Deposit C&amp;P.</span></p></li></ul></li><li class="md-list-item" cid="n103" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n101" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="strong" class="md-pair-s" style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold; color: rgb(222, 222, 222);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Create PagerDuty Service for Lighthouse: Veteran Service History and Elibilbility API</span></strong></span></p><ul class="ul-list" cid="n108" mdtype="list" data-mark="-" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative;"><li class="md-list-item" cid="n107" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n105" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">This service will be used to create a maintenance window for Rated Disabilities.</span></p></li><li class="md-list-item" cid="n115" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n113" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Not sure what this displays for the Profile.</span></p></li></ul></li><li class="md-list-item" cid="n124" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n122" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="strong" class="md-pair-s" style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold; color: rgb(222, 222, 222);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Discovery: Additional PagerDuty Services for Profile</span></strong></span></p><ul class="ul-list" cid="n129" mdtype="list" data-mark="-" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative;"><li class="md-list-item" cid="n128" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n126" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Determine if a service exists or is need for Connected Apps.  If so, inform the Lighthouse team responsible.</span></p></li></ul><ul class="ul-list" cid="n137" mdtype="list" data-mark="-" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative;"><li class="md-list-item" cid="n136" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n134" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Determine if a PagerDuty exists or is needed for Account Security and create any necessary tickets.</span></p></li></ul></li></ul><p cid="n138" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">The following FE tickets will be created for FE Maintenance Window components (needs Adam's review):</span></p><ul class="ul-list" cid="n144" mdtype="list" data-mark="-" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.5rem; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><li class="md-list-item" cid="n146" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n147" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="strong" class="md-pair-s" style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold; color: rgb(222, 222, 222);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Create FE Maintenance WIndow Component.</span></strong></span></p><ul class="ul-list" cid="n151" mdtype="list" data-mark="-" style="box-sizing: border-box; margin: 0px; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative;"><li class="md-list-item" cid="n150" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n148" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Create FE component for EDU Direct Deposit.</span></p></li><li class="md-list-item" cid="n154" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n152" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Create FE component for Notification Settings.</span></p></li><li class="md-list-item" cid="n157" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n155" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Create FE component for Rating Info.</span></p></li></ul></li></ul><p cid="n116" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="em" class="md-pair-s" style="box-sizing: border-box;"><em style="box-sizing: border-box; font-style: italic;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Note: FE tickets are dependent upon BE tickets.</span></em></span></p><p cid="n158" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">One final ticket should be create for collaborating with the MHV cartography team:</span></p><ul class="ul-list" cid="n163" mdtype="list" data-mark="-" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.5rem; padding: 0px 0px 0px 1.875rem; list-style: square; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><li class="md-list-item" cid="n165" mdtype="list_item" style="box-sizing: border-box; margin: 0px; position: relative;"><p cid="n166" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0px 0px 0.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative;"><span md-inline="strong" class="md-pair-s" style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold; color: rgb(222, 222, 222);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Collaborate and Document Maintenance Window documentation.</span></strong></span></p></li></ul><p cid="n161" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; overflow-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"></p><br class="Apple-interchange-newline">
