### ISSUE TITLE
Explore approach to approaching Preview Environment URLs

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#73785]
## Description
We want to change the URL of preview environments to something more user friendly - this URL will eventually become public, pending ESECC approval.

## Tasks
- [ ] Discuss possible approaches to Preview Environment URLs
- [ ] Document options and provide a recommended approach

## Acceptance Criteria
- [ ] A documented approach to URLs is available for discussion and review
