### ISSUE TITLE
Explore Approaches to Cleanup of K8s Branch

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#73782]
## Description
Based on some sacrifices that were made during the development of Milestone 1 to support a WASA scan, there are a handful of improvements that need to be made to preview environments as a result. This ticket is intended to cover the research into what needs to be done, summarize the options and provide a recommendation.

## Tasks
- [ ] Research approaches to the K8s branch
- [ ] Conduct discussions as needed with key stakeholders in this matter
- [ ] Document approaches, and provide a recommendation for a path forward to use for further discussions

## Acceptance Criteria
- [ ] A document exists and is ready to use to facilitate discussions on the path forward.
