### ISSUE TITLE
Plan PE Milestone 2

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#73783]
## Description
Dependabot is a tool that is intended to provide warnings about... but it is currently not functioning correctly. We need to investigate why it is malfunctioning, and determine how to resolve. This ticket is purely focused on the discovery of the issue, not implementing solutions.

## Tasks
- [ ] Investigate Root Cause of Dependabot Issues
- [ ] Conduct tests to verify assumptions
- [ ] Document issues and proposed solutions - either in Confluence, or in a solution/implementation ticket

## Acceptance Criteria
- [ ] Proposed fix is documented and pointed in a solution/implementation ticket
