### ISSUE TITLE
Discovery - Identify Root Cause of Dependabot Issues

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#73781]
## Description
Dependabot is a tool that is intended to provide warnings about... but it is currently not functioning correctly. We need to investigate why it is malfunctioning, and determine how to resolve. This ticket is purely focused on the discovery of the issue, not implementing solutions.

## Tasks
- [ ] Investigate Root Cause of Dependabot Issues
- [ ] Conduct tests to verify assumptions
- [ ] Document issues and proposed solutions - either in Confluence, or in a solution/implementation ticket

## Acceptance Criteria
- [ ] Proposed fix is documented and pointed in a solution/implementation ticket

**Comment by ericboehs** [comment]
It turns out Dependabot was working. It is configured to only open 5 pull requests at a time there were several pull requests opened ~3 months ago that never got closed so dependabot was pretty quiet and gems weren't getting updated.
