### ISSUE TITLE
Troubleshoot: Unit Tests not skipping as expected

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#73789]
## Description
The unit test allow list does not seem to be functioning properly and as a result is requiring some work arounds to get past those issues. We need to determine the root cause of the issues, how to resolve them, and put those fixes in place. Tests do not appear to be being skipped accordingly, listed tests do not appear to be blocking merges, and new tests do not appear to be being automatically added to the list.

## Tasks
- [ ] Investigate root cause of current unit test allow list features
- [ ] Determine and test potential approaches for how to resolve
- [ ] Implement the fix
- [ ] Test the implemented fix
- [ ] Update documentation as needed

## Acceptance Criteria
- [ ] Root cause has been identified
- [ ] A fix has been determined and made and is working successfully
- [ ] Documentation has been updated

**Comment by CBonade** [comment]
Merged a PR today that addressed two separate issues:

1) The stress tests failing was not blocking merges and it should be - that is now corrected.
2) The tests on the allow list flagged as not allowed tor un were not skipping accordingly. They are now.

Next to address is the add a new spec to the allow list causing query errors. Then this ticket will likely be ready to close.

**Comment by CBonade** [comment]
The issue of manually adding a unit test causing query failures has been corrected. This issue is ready to close.
