### ISSUE TITLE
Kick off pilot

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73800]
## User Story
As a Governance team member, I want to get everything in order to begin our research pilot so that the research process is smooth with minimal issues.

Assignee: @erinrwhite 
Peer Reviewer: @rferguson13 

## Description
We have written 2 research plans in tickets #69456 and #63507 to test out our new VA.gov Experience Standards with ourselves and with VFS teams. We have also prepared our operational guidance in ticket #70283 to begin the research study. The purpose of this ticket is to initiate the research plans and begin the pilot.

## Tasks
- [x] Ensure all of the modified operational guidance for Collaboration Cycle Staging Review is ready to go
- [x] Publish all operational guidance to the live Platform Products and Services space in Confluence

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All Governance team members know what is expected of them in the [VFS team Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2832498689/2023-11+New+experience+standards+VFS+teams+Research+plan) and the [Governance team Research Plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833842177/2023-11+New+experience+standards+Governance+team+Research+plan)
- [ ] All Governance team members have the guidance they need in order to execute both research plans

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@rferguson13 Hi Rebecca! I brought over the documentation to our live docs:

[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
[Staging Review - during the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting)
[Staging Review - After the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting) 

...and turned the surveys on. Can you check behind me to see if the docs still make sense? I had one comment on the Scheduling page as well.

This is also connected to the [updates to the Design System staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70961). Should those go live as well? 😄 @shiragoodman

**Comment by rferguson13** [comment]
@erinrwhite Looking good! Just one suggestion. I also responded to your comment on the Scheduling page.

**Comment by shiragoodman** [comment]
@rferguson13 @erinrwhite yes, the DS SRT page should go live as well. thank you for catching that!

**Comment by erinrwhite** [comment]
@rferguson13 @shiragoodman 

Lots o doc updates!

## Design system staging review docs #70961:
 - [How to Request a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review)
 - [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)
 - [Design System Staging Review - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2827943944/Design+System+Staging+Review+-+During+the+Meeting)
 - [Design System Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2827943956/Design+System+Staging+Review+-+After+the+Meeting)
 - [How to Document Findings for a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572189697/How+to+Document+Findings+for+a+Design+System+Staging+Review)
 - [Design System Drafting Template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2915926188/Design+System+Drafting+Template)
 - [High priority vs. priority vs. considerations](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2915434697/High+priority+vs.+priority+vs.+considerations)

## Documentation from #63513
Many of these pages now have info for "1.0" and "2.0" while we're in the pilot phase. I made this call to keep our docs from being duplicated in two places for too long, and to help Governance along as we use both processes. Once we launch the standards we'll need to remove the 1.0 documentation. 😬 

- [How to generate staging review tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)
- [Drafting Template outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)
- [How to document findings for staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)
- [How to add images to the drafting template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2396619099/How+to+Add+Images+to+the+Staging+Review+DraftingTemplate)
- [VA.gov experience standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards)
- [Staging Review findings - Issue template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2548957608/Staging+Review+findings+-+issue+template)


## TODO 
- Update staging review "during meeting" guidance to mention at beginning that we're in a pilot, and at the end that we're sending out a survey

**Comment by erinrwhite** [comment]
Unpretty updated [instructions for during-meeting script](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting#Step-3:-Read-the-script) sent to @rferguson13 for help - thank you!! Once we have some clarity here I can update the DS staging review script too.

**Comment by erinrwhite** [comment]
Thank you @rferguson13 for the language review on the Staging Review script! I don't think we need to update the DST during-meeting script because we won't be surveying them.

I *think* we are ready to move this ticket to the review phase. Please let me know if I'm missing anything. Once you've reviewed I will notify the team that we're all set.

**Comment by erinrwhite** [comment]
Updated the [during the meeting instructions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting) to share the link out at the end, and to specify where to look for the link after the meeting. @rferguson13 I _think_? this is ready for review now.

**Comment by rferguson13** [comment]
@erinrwhite this looks good to me! Nice work. Now all we need is a SR!

**Comment by erinrwhite** [comment]
Thanks for the review @rferguson13! Closing.
