### ISSUE TITLE
Draft Staging Review Dashboard team guidance 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73815]
## User Story
As a Governance team member, I want to have an internal doc that helps explain the organization, structure and data used in the Staging Review Dashboard in Domo so that I can help provide support to the dashboard if/when needed.

Assignee: @it-harrison 
Peer Reviewer: @allison0034 @briandeconinck 

## Description
In initiative #51477, Governance team made big changes to the Staging Review Dashboard in Domo (fka the Collaboration Cycle Dashboard). There were primarily 2 team members who supported the dashboard changes, however it is possible that in the future, those 2 team members may not be available. The purpose of this ticket is to document as much need-to-know information about the structure, organization, and data in use in the dashboard within the Governance Team [Team Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2035777566/Team+Guidance) space on Confluence. 

## Tasks
- [x] Create a new page in the Team Guidance section of the Governance Team confluence space
- [x] Organize the document by card or whatever order makes the most sense
- [x] Ensure the guidance is easily understood by someone who did not recently support Domo

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has internal guidance that explains the set up of the Staging Review Dashboard in domo

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
Hi @briandeconinck and @allison0034 a [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2926968882/Domo+Dashboard+Guide) is ready for review.

**Comment by allison0034** [comment]
This is a great overview! Couple of questions:

1. Can you link to an external document that explains how to create SQL tables for this? I think this will be above most of our heads BUT it might be worth trying.
2. Per the above, if this is something that requires someone who is a developer, maybe we should call that out? Like, here is a link to SQL basics but really someone who knows SQL should be doing this.
3. If we don't know SQL can we edit the dataflow you created? For example, if we want to change the format of the date or something that seems simple on the front end.

cc @shiragoodman copying you in to get your thoughts around my questions.

**Comment by shiragoodman** [comment]
taking a look at this now!

**Comment by briandeconinck** [comment]
I think I was able to follow all of this. I appreciate the definitions at the top, which were good motivation for following the tables.

I think Allison has a good callout here, that for best results any edits should be made by someone comfortable with SQL. This document gives a good tour for how the cards come together but a nice warning up front ("don't mess with these unless you know what you're doing!") could save someone a lot of heartache a few years from now.

**Comment by it-harrison** [comment]
@allison0034 @briandeconinck @shiragoodman tweaked the document by adding a disclaimer and links to Domo in the overview and strategy sections

**Comment by allison0034** [comment]
Looks good to me!

**Comment by briandeconinck** [comment]
Also looks good to me!

**Comment by shiragoodman** [comment]
@it-harrison this is great. Thank you! You can close this ticket.
