### ISSUE TITLE
Supplemental Claim | Update to use USWDS v3 components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#73828]
## Value Statement
**_As a_**  Benefits Decision Reviews team member
**_I want to_** make sure we're updating all of our forms to use USWDS v3 components & styles
**_So that_** Veteran's can get a consistent experience across our forms

## Background Context

The design system team made this announcement today:

> On February 16 all design system web components will default to their v3 variant. v3 will become opt out only.
> In one month, the design system team will be switching all web components to render their v3 variant automatically. If teams have a need to fall back to the original v1 variant, they will be able to do so by setting the uswds prop to false. However, v1 variants will eventually be fully retired and removed so opting out is discouraged.

So our team needs to evaluate and update styles & components within our Decision Reviews forms to match the USWDS v3 styles.

## Tasks
- [x] Update Supplemental Claim styles to match USWDS v3
- [x] Update components & web-components to match USWDS v3
- [x] While converting components to web-components, add unit tests to ensure functionality is preserved
- [x] Update unit & e2e tests
- [x] Update designs

## Acceptance Criteria
- [x] When a user accesses the form they can see visual changes from the V3 update.
- [x] When a user attempts to navigate the form using a keyboard they are can page forward and backwards. 
- [x] Given that a user has completed the form and included evidence, when they click submit is they are able to do so.
- [x] When a user attempts an action that prompts an error it is captured in testing.

## Definition of Ready 
- [x] Clear value description
- [x] Testable acceptance criteria
- [x] Accessibility added to acceptance criteria
- [x] Approved designs attached
- [x] Sample data provided where appropriate
- [x] Estimated to fit within the sprint
- [x] Dependencies and blockers linked

## Definition of Done
- [x] Meets acceptance criteria
- [x] Code reviewed (internal)
- [x] Submitted to staging
- [x] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Available for testing in staging

**Comment by saderagsdale** [comment]
@Mottie How would we test this to confirm nothing is broken? Does it have any impact on code coverage?

**Comment by saderagsdale** [comment]
@saderagsdale will ask Matt Dingee about acceptance criteria for this.

**Comment by saderagsdale** [comment]
@Mottie updated the AC.

**Comment by HeatherWidmont** [comment]
Team to review in parking lot today

**Comment by eileen-coforma** [comment]
We did validation today, and caught some mismatches. Part our code, part platform form system code not being up-to-date. @Mottie and @rocio-desantiago will work on this before next validation meeting.

**Comment by saderagsdale** [comment]
@eileen-coforma Cool beans. What were the mismatches?

**Comment by eileen-coforma** [comment]
@Mottie Has 3 lists
1. Things we need to fix (extra padding on error alerts, certain elements not updated to USWDS 3 yet)
2. Things platform needs to fix (form system we use is still on v1)
3. I forgot what the third list is...

**Comment by Mottie** [comment]
Work complete

**Comment by eileen-coforma** [comment]
Just realized the second validation didn't happen for this work. 

Caught a bug in SC Review and Submit where two of the pages we had hidden (in favor of the evidence summary page) was showing up, which could trigger errors.

**Comment by HeatherWidmont** [comment]
Will review in parking lot today

**Comment by Mottie** [comment]
Parts that still need to be updated to v3

## Design System Team owned:
- Breadcrumbs (part of content build template) - to be updated by DST ([Slack conversation](https://dsva.slack.com/archives/C044AGZFG2W/p1709660800311389?thread_ts=1709657020.756259&cid=C044AGZFG2W))
- OMB view privacy act statement button (inside `va-omb-info` web component) - see [#2492](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2492)
- Action link currently uses a class name for styling, in the future this will become a WC
- Form navigation buttons (back and continue) provided by form system; deeply integrated with e2e tests so this will take a lot of work to update - no work ticket found
- Review & submit accordion items in an error state - it's missing color definitions - see #77064 

## Decision Review Team owned:
- Contestable issues checkboxes are using plain HTML and simulating v3 WC - discussed with Eileen to probably keep this as-is
