### ISSUE TITLE
NOD | Update to use USWDS v3 components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#73829]
## Value Statement
**_As a_**  Benefits Decision Reviews team member
**_I want to_** make sure we're updating all of our forms to use USWDS v3 components & styles
**_So that_** Veteran's can get a consistent experience across our forms

## Background Context

The design system team made this announcement today:

> On February 16 all design system web components will default to their v3 variant. v3 will become opt out only.
> In one month, the design system team will be switching all web components to render their v3 variant automatically. If teams have a need to fall back to the original v1 variant, they will be able to do so by setting the uswds prop to false. However, v1 variants will eventually be fully retired and removed so opting out is discouraged.

So our team needs to evaluate and update styles & components within our Decision Reviews forms to match the USWDS v3 styles.

## Tasks
- [ ] Update NOD styles to match USWDS v3
- [ ] Update components & web-components to match USWDS v3
- [ ] While converting components to web-components, add unit tests to ensure functionality is preserved
- [ ] Update unit & e2e tests
- [ ] Update designs

## Acceptance Criteria
- [ ] When a user accesses the form they can see visual changes from the V3 update.
- [ ] When a user attempts to navigate the form using a keyboard they are can page forward and backwards. 
- [ ] Given that a user has completed the form and included evidence, when they click submit is they are able to do so.
- [ ] When a user attempts an action that prompts an error it is captured in testing.

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Available for testing in staging

**Comment by saderagsdale** [comment]
@Mottie How would we test this to confirm nothing is broken? Does it have any impact on code coverage?

**Comment by eileen-coforma** [comment]
![Screenshot 2024-01-31 at 12 59 30 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/818d32c8-26b1-40ec-9cda-69a17341dc67)
This error message looks off

**Comment by eileen-coforma** [comment]
@rocio-desantiago @Mottie 
![Screenshot 2024-01-31 at 1 40 29 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/a31eb111-32ac-4033-a72a-12affddf1b4a)

Hint text seems like it's set to mobile width.

**Comment by saderagsdale** [comment]
@saderagsdale will ask Matt Dingee about acceptance criteria for this.

**Comment by saderagsdale** [comment]
@Mottie Updated AC

**Comment by Mottie** [comment]
Switched back to in progress to fix a few issues.

**Comment by HeatherWidmont** [comment]
@Mottie working on bug related to this ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2491

**Comment by HeatherWidmont** [comment]
@Mottie pausing this work in favor of NOD v2 launch

**Comment by Mottie** [comment]
- Breadcrumbs (part of content build template) - to be updated by DST (see https://dsva.slack.com/archives/C044AGZFG2W/p1709660800311389?thread_ts=1709657020.756259&cid=C044AGZFG2W)
- OMB view privacy act statement button (inside va-omb-info WC) - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2492
- Action link currently uses a class name for styling, in the future this will become a WC
- Form navigation buttons (back and continue) provided by form system; deeply integrated with e2e tests so this will take a lot of work to update - no work ticket found
- Contestable issues checkboxes are using plain HTML and simulating v3 WC - discussed with Eileen to probably keep this as-is
- Updating hearing type in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28380)

**Comment by HeatherWidmont** [comment]
@Mottie to create a ticket for DST about form navigation buttons
