### ISSUE TITLE
Shared code | Update to use USWDS v3 components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#73827]
## Value Statement
**_As a_**  Benefits Decision Reviews team member
**_I want to_** make sure we're updating all of our forms to use USWDS v3 components & styles
**_So that_** Veteran's can get a consistent experience across our forms

## Background Context

The design system team made this announcement today:

> On February 16 all design system web components will default to their v3 variant. v3 will become opt out only.
> In one month, the design system team will be switching all web components to render their v3 variant automatically. If teams have a need to fall back to the original v1 variant, they will be able to do so by setting the uswds prop to false. However, v1 variants will eventually be fully retired and removed so opting out is discouraged.

So our team needs to evaluate and update styles & components within our Decision Reviews forms to match the USWDS v3 styles.

## Tasks
- [ ] Update Shared code styles to match USWDS v3
- [ ] Update components & web-components to match USWDS v3
- [ ] While converting components to web-components, add unit tests to ensure functionality is preserved
- [ ] Update unit & e2e tests
- [ ] Update designs

## Acceptance Criteria
- [ ] All tasks complete
- [ ] All tests passing
- [ ] Shared code is updated to use USWDS v3 styles & components

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Available for testing in staging

**Comment by saderagsdale** [comment]
@Mottie How would we test this to confirm nothing is broken? Does it have any impact on code coverage?

**Comment by eileen-coforma** [comment]
@rocio-desantiago @Mottie The 'progress-bar-segmented' on the form seems like it's still v1, not v3.

**Comment by rocio-desantiago** [comment]
> @rocio-desantiago @Mottie The 'progress-bar-segmented' on the form seems like it's still v1, not v3.

Correct. There are parts of the form that will still be V1 until form systems update to V3.

**Comment by saderagsdale** [comment]
@saderagsdale will ask Matt Dingee about acceptance criteria for this.

**Comment by HeatherWidmont** [comment]
Did get a response about what exactly they're looking for. @saderagsdale will add that as the AC & use that as a gauge what needs to change

**Comment by HeatherWidmont** [comment]
Team to review in parking lot today
