### ISSUE TITLE
HLR | Update to use USWDS v3 components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#73830]
## Value Statement
**_As a_**  Benefits Decision Reviews team member
**_I want to_** make sure we're updating all of our forms to use USWDS v3 components & styles
**_So that_** Veteran's can get a consistent experience across our forms

## Background Context

The design system team made this announcement today:

> On February 16 all design system web components will default to their v3 variant. v3 will become opt out only.
> In one month, the design system team will be switching all web components to render their v3 variant automatically. If teams have a need to fall back to the original v1 variant, they will be able to do so by setting the uswds prop to false. However, v1 variants will eventually be fully retired and removed so opting out is discouraged.

So our team needs to evaluate and update styles & components within our Decision Reviews forms to match the USWDS v3 styles.

## Tasks
- [ ] Update HLR styles to match USWDS v3
- [ ] Update components & web-components to match USWDS v3
- [ ] While converting components to web-components, add unit tests to ensure functionality is preserved
- [ ] Update unit & e2e tests
- [ ] Update designs

## Acceptance Criteria
- [ ] When a user accesses the form they can see visual changes from the V3 update.
- [ ] When a user attempts to navigate the form using a keyboard they are can page forward and backwards. 
- [ ] Given that a user has completed the form, when they click submit is they are able to do so.
- [ ] When a user attempts an action that prompts an error it is captured in testing.

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Available for testing in staging

**Comment by saderagsdale** [comment]
@Mottie How would we test this to confirm nothing is broken? Does it have any impact on code coverage?

**Comment by saderagsdale** [comment]
@saderagsdale will ask Matt Dingee about acceptance criteria for this.

**Comment by saderagsdale** [comment]
@Mottie Updated AC. Let me know what you think.

**Comment by HeatherWidmont** [comment]
Team to review in parking lot today

**Comment by rocio-desantiago** [comment]
Looking at tests for new PR: keyboard test is failing, says it can't navigate away from the informal conference page. Still investigating why based on this portion of the test:
```// Informal conference option
      cy.url().should(
        'include',
        chapters.informalConference.pages.requestConference.path,
      );
      cy.tabToElement('[name="root_informalConference"]');
      cy.chooseRadio(data.informalConference);
      cy.tabToContinueForm();```

**Comment by rocio-desantiago** [comment]
For the PR that only updates the Homelessness question:
When running `yarn cy:run --spec src/applications/appeals` locally
the tests failing are: 
- download/tests/submitted-appeal.cypress.spec.js
- testing/tests/appeals-testing.cypress.spec.js

**Comment by rocio-desantiago** [comment]
Cypress tests updated for both and in code review now. All tests passing. Even the 995 test that somehow was triggered by this PR even though no changes were made to 995 teeheehee

**Comment by rocio-desantiago** [comment]
Worked on # 77496 , but will look into why test is failing with message on Monday `Expected to navigate away from /decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/informal-conference`

**Comment by HeatherWidmont** [comment]
Rerunning the cypress because they are failing to start, have to manually do this which takes time

**Comment by rocio-desantiago** [comment]
Both merged!

**Comment by HeatherWidmont** [comment]
Will validate in parking lot today

**Comment by eileen-coforma** [comment]
Validated in parking lot. Works as intended.
