### ISSUE TITLE
[Design] V3 component implementation - identify changes

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#73833]
## Background
V3 components are being pushed on Feb 16th by the Platform team. Our Figma concepts need to reflect current state when that change happens. 

---
## Tasks
- [x] Determine what will and won't change with the rollout
- [x] Identify any risks for engineering and design
- [x] Record any findings not already documented
- [x] Prepare to update Figma files to reflect changes

## Acceptance Criteria
- [x] Findings documented
- [x] Prep for Figma update

## Validation
- [x] Validated by Product, Design, Engineering looking over documentation

## Resources
Related epic: [#66116](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66116)
Related issue: [#69483](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69483)

**Comment by mattmarino-adhoc** [comment]
No specific risks identified for My VA V3 updates. As of right now, the only noteworthy risk for Auth. Exp.'s updates center around the update of the breadcrumbs component used for Profile. There may be unintended consequences with styling otherwise, but nothing at this time appears like it would outright break components/the user experience. 

Additional info and Alert both will require an update to V3. New edits in My VA Figma files will reflect this upcoming change.
