### ISSUE TITLE
Identify PDF version for Ch36/PCPG (25-8832)

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73849]
## Issue Description
_Download the version of the 25-8832 pdf that the online Chapter 36 form is currently generating, so we can determine if it's the latest version._

---
## Tasks
- [ ] Identify and download the pdf the online form is currently generating
- [ ] Add it to the [vets.api pdf repo](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/pdf_fill/forms/pdfs)

## Acceptance Criteria
- [ ] PDF currently generated by online Chapter 36 form is attached to this ticket
- [ ] PDF currently generated by online Chapter 36 form is added to pdf repo
---

**Comment by evansmith** [comment]
@steele-lm I found this PDF labeled under 28-8832 in the pdf directory in vets-api, is this the pdf we're looking for? 
[28-8832.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/14170851/28-8832.pdf)

**Comment by steele-lm** [comment]
@evansmith YES! I missed that the form number changed last year, and I was looking for the new number (25-8832) in the repo.
