### ISSUE TITLE
Re-publish entry points for pension relaunch

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#73843]
## Issue Description
Child ticket of [73034](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73034) but linking isn't working

For the 100% launch of the form, we'll also need to republish these entry points:

- [ ] [How to apply for VA pension page](https://www.va.gov/pension/how-to-apply/)
- [ ] [Eligibility for VA pension](https://www.va.gov/pension/eligibility/)
- [ ] [About VA Form](https://www.va.gov/find-forms/about-form-21p-527ez/)
- [ ] [Fully Developed Claims](https://www.va.gov/pension/how-to-apply/fully-developed-claim/) — 2 links in first and last accordions.
- [ ] [Pension hub page](https://www.va.gov/pension/)
- [ ] [Evidence needed page](https://www.va.gov/resources/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/) — CTA in intro
- [ ] [Top and left nav]
- [ ] [Form results page](https://www.va.gov/find-forms/?q=527EZ) - option to "Fill out VA Form 21P-527EZ online"

[Corresponding product team ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/73178)

---
## Tasks
- [x] Pages updated
- [ ] Copyedit
- [ ] Publish

## Acceptance Criteria
- [ ] Entry points are live
---

**Comment by katherine-fung** [comment]
This is pending the team's confirmation of the form URL. Jenny, Lily and I are meeting with the team on Thursday about the URL.

**Comment by katherine-fung** [comment]
I'm going to use the previous form URL for the entry points. When the team is ready to use new URLs for the form, they/Jenny will request a redirect of the previous form URL to the new one. 

I've put the entry points back on these pages: 

- [ ] How to apply for VA pension page
- [ ] Eligibility for VA pension
- [ ] About VA Form
- [ ] Fully Developed Claims — 2 links in first and last accordions.
- [ ] Pension hub page
- [ ] Evidence needed page — CTA in intro
- [ ] [Top and left nav]
- [ ] Form results page - option to "Fill out VA Form 21P-527EZ online"

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I'm going to check off this list as I copy edit, but I'll keep them in draft until we're ready to publish them.

- [ ] [How to apply for VA pension page](http://preview-prod.vfs.va.gov/preview?nodeId=586)
- [ ]  [Eligibility for VA pension](http://preview-prod.vfs.va.gov/preview?nodeId=585)
- [ ]  [About VA Form](http://preview-prod.vfs.va.gov/preview?nodeId=6120)
- [ ]  [Fully Developed Claims — 2 links in first and last accordions.](http://preview-prod.vfs.va.gov/preview?nodeId=587)
- [ ]  [Pension hub page](http://preview-prod.vfs.va.gov/preview?nodeId=73)
- [ ]  [Evidence needed page — CTA in intro](http://preview-prod.vfs.va.gov/preview?nodeId=44702)
- [ ]  [Top and left nav]
- [ ]  Form results page - option to "Fill out VA Form 21P-527EZ online"

**Comment by megzehn** [comment]
Thank you so much for this work, @katherine-fung!! 

I reinstated all these entry points. I'll validate in a few hours to make sure they're all live, and then I'll close this ticket. 

I think we're OK to keep this actual at a 4 (for this ticket specifically), but let me know if you disagree @katherine-fung

**Comment by katherine-fung** [comment]
Closing this ticket because the work is done.

**Comment by megzehn** [comment]
Just noting that I finally validated this ticket. While validating I realized that I left off the reentry point in the top nav, so I just added the online Pension form link back in now. I checked the links in all the other places, and they all look good. 

CC @katherine-fung (just for awareness -- no action needed)
