### ISSUE TITLE
[UX] 10-10EZ Toxic Exposure - Discovery

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#73852]
## Issue Description

Background ticket: [[Design] 10-10EZ - Toxic Exposure: Create mock-up with new questions #73671](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73671)

Initial discovery to gather all the places and ways these questions are asked of Veterans and when it happens during the benefits application experience. 

- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks
- [x] Complete table on Mural board
- [x] Document any stakeholder questions and answers if received ([GitHub page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Q%20%26%20A%20to%20HEC%20and%20ES.md) and on Mural Board)

## Acceptance Criteria
- [x] Unknowns are clarified and design is ready to begin
---

**Comment by jessicastump** [comment]
@hdjustice - After the HEC call today, do you think this is about 90% completed? Just waiting for the answers that were punted to SMEs around if the Veteran already has a disability rating.

**Comment by hdjustice** [comment]
Hi @jessicastump - Yes I agree.  I think we are good to keep moving forward
