### ISSUE TITLE
[CHIP] SPIKE - figure out what is needed with a refresh endpoint

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#73854]
## Description
VeTEXT is going to handle the day of appointments re-fresh. This will be similar to the refresh that is currently done by CHIP via vista-api. This ticket is a spike to figure out what veTEXT will need from us to kick this off and get an updated appointment payload.

## Tasks
- [ ] [FE] get requirements from vetext
- [ ] [FE] create ticket for a refresh endpoint
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
closing this spike, refresh will not be needed for travel only
