### ISSUE TITLE
Make final changes in disability audit

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#73860]
## Issue Description
We need to make some final tweaks to the special claims audit pages. These are based on SME feedback and a conversation with Megan and @bethpotts.

These are the changes:

For [Automobile allowance](https://prod.cms.va.gov/node/895/latest), [Clothing allowance](https://prod.cms.va.gov/node/895/latest), and [Unemployability](https://prod.cms.va.gov/node/900/latest): 
- Change “condition” to “disability” in the new note that we added. ("**Note:** You must have a service-connected **disability** to get an adaptive-equipment grant. If you haven’t filed a claim for disability compensation yet, you’ll need to do that first.")

For [Temporary disability rating](https://prod.cms.va.gov/node/897/latest):
- Change “How do I file for disability compensation?” To “How do I get these benefits?”
- Under same header, tweak first sentence to: “You can file an online claim now to get a temporary 100% rating.”

For [Increased disability rating](https://prod.cms.va.gov/node/898/latest) for time in hospital (same changes as temporary disability rating):
- Change “How do I file for disability compensation?” To “How do I get these benefits?”
- Under same header, tweak first sentence to: “You can file an online claim now to get a temporary 100% rating.”

For [Prestabilization ratings](https://prod.cms.va.gov/node/899/latest)
- Change “How do I file for disability compensation?” To “How do I get these benefits?”
- Under same header, tweak first sentence to: “You can file an online claim now for a prestabilization rating…”

For [Title 38](https://prod.cms.va.gov/node/892/latest)
- Change “How do I file for disability compensation?” To “How do I get these benefits?”

---
## Tasks
- [X] Make all the requested edits on the special claims pages (MZ)
- [x] Review changes (CL)
- [x] Publish changes (CL)

## Acceptance Criteria
- [ ] All changes are live on the special claims pages
---

**Comment by megzehn** [comment]
Hi @bethpotts, this is the ticket where I'm tracking those final changes we discussed last Thursday. 

@chelsealevinson, these are ready for you to review and publish when you can! Thank you so much!

Let me know if there are any issues, or next steps that I missed.

**Comment by chelsealevinson** [comment]
Confirming I copy edited the changes and published all remaining pages. Thank you all!

**Comment by megzehn** [comment]
Thanks Chelsea! Closing this.
