### ISSUE TITLE
[CAIA A11y Research]: Authenticated Experience, Authenticated Menu (January 2024)

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#73875]
# Project Overview

> [!NOTE]
> **High-Level Overview:** Authenticated Experience
> - **Timeframe**: Jan 29-Feb 1, 2024
> - **Pilot**: 11:30 a.m. ET on Jan. 26, 2024 `#74259`
> - **Assistive Tech Users**: `3` or `4` [Users based on Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/authenticated-menu-usability/research-plan.md#accessibility-and-inclusion)
> - **Assistive Technology**:  `Screen Readers` `JAWS` `VO` `Fusion`
> - **Task Lists**: [See task lists for next steps/definition of done](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/27?pane=issue&itemId=50317215#:~:text=reveal%20supporting%20artifacts-,Next%20steps,-Authenticated%20Experience%20Team) for the Auth. Exp. Team and CAIA A11ys

## Assignee(s)
- @coforma-jamie `Research Session Support`
- @eli-oat `Pilot Support`

### A11y Availability

<details><summary>Toggle to reveal a11y availability information</summary>

_Thank you for reaching out to CAIA! We are looking forward to supporting your study. We wanted to let your team know that there are multiple studies taking place during the same timeframe as your study._ 

_We will do our very best to work with you and @artsymartha68, to support your research sessions, based on a11y availability. Should you have any questions, issues, or concerns please do not hesitate to contact @coforma-terry (CAIA A11Ys) and/or @artsymartha68 (OCTO) as soon as possible._

_We have blocked out your time slots on our [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York) and see that you are flexible, based on your notes in the Research Plan, thank you!_ 

</details>

## Team Info

- Team name: Authenticated Experience
- OCTO-DE product owner: Samara Strauss
- Product manager: Travis Chaill
- Designer: Liz Lantz
- FE engineer: Adam Whitlock
- Product/team Slack channel: #accountexp-authexp

<details><summary>Toggle to reveal additional team information</summary>

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### If you have an accessibility champion, what's their name?

Liz Lantz

### Calendar checking

- [X] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [X] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

### When is the timeframe for your testing?

Jan 29-Feb 1

</details>

## Research sessions

<details><summary>Toggle to reveal additional research session information</summary>

- **Planned dates of research:** 
  - **Start**: Jan 29, 2024
  - **End**: Feb 1, 2024 `Goal: Complete by Jan. 31, 2024, if possible`
  - **Reschedules**: Feb. 1, 2024
  - **Pilot:**`1/26 at 11:30 a.m. ET` invite sent  on 1/24/2024 @eli-oat @andaleliz 

### Length of sessions
* **Session length:** 30 minutes for non-screen reader participants, 45 minutes for screen reader participants
* **Buffer time between sessions:** 45 minutes
* **Maximum Sessions per day:** 4

</details>

## Testing Schedule

<details><summary>Toggle to reveal additional testing schedule and device information</summary>

### Availability

| Date   | Time Slots (Eastern)              | Screenreader Session Holds | 
|--------|-----------------------------|--------------------------------------------------------------|
| Jan 29 | `WINDOWS:`10am-5:30pm, and 7:30pm-9pm | Screenreaders between 10am-12pm or 1-2:15pm                  
| Jan 30 | `WINDOWS:` 7-7:45am, 10am-5pm          | Screenreaders between 10am-12pm or 1-2:15pm                 
| Jan 31 | `WINDOWS:` 10am-5:30pm                 | Screenreaders between 10am-12pm or 1-2:15pm                
| Feb 1  | `WINDOWS:` 8:30am-4:00pm               | Screenreaders between 8:30am-12pm or 1-2:15pm               

> _**LL Notes**: These are ideal times when a specialist is available. OK to schedule outside of these times if absolutely needed._

### Device & AT Combinations

CAIA A11Ys will be looking for information along the lines of the following. We realize that some of this information will not be available until the day of the session. 

| **Participant Number** | **CAIA A11Y** | **Date of Research (Eastern)** | **Assistive Tech** | **Skill Level** | **Operating System** | **Browser** |**Device Type** |
|-------------|-----------------------------|------------------|--------------------|-----------------|----------------------|-------------|-------------|
| _P#4                   | @coforma-jamie  | 1/29/2024 from 2:45 to 3:45 p.m.        | Jaws            | Advanced       |  Windows PC     | Unsure which browser they will use    | Laptop or Desktop |
| _P#8                   | @coforma-jamie  | 1/30/2024   from 2:45 to 3:45 p.m.       | VoiceOver   | Advanced       |  Apple    | VoiceOver  | Mobile |
| _P#12                   | `no CAIA a11y attending` @andaleliz  |  1/31/2024  from 2:45 to 3:45 p.m.        | Fusion  | Intermediate      |  Unsure   | Unsure    | Mobile ||                  |                    |                 |                      |             |         |

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

### Pilot Session

| Date   | Time (Eastern)              | Pilot Session | CAIA A11Y(s) Available
|--------|-----------------------------|--------------------------------------------------------------|--------------------------------------------------------------|
| Jan 26 | 11:30 a.m. | Pilot Session with CAIA  Ticket: [#74259](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74259)            | @eli-oat  `Evan Observing`

### Session Note Taking in Mural

> [LL 1/24/2024](https://dsva.slack.com/archives/C909ZG2BB/p1706116331483779?thread_ts=1706116148.817899&cid=C909ZG2BB) Slightly new approach in Mural for note taking. [Here’s the section setup for the pilot](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706115685060/fe256c047a321ae25a40e7cd742c03e6b286738a?wid=0-1656387114105), loosely organized by the tasks in the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/authenticated-menu-usability/conversation-guide.md).

> **A couple of notes:**
> - When you’re typing in a sticky in Mural, if you press tab it’ll automagically create a new sticky right next to the one you were just in, using the same color. I think this makes it faster to keep up with the speed of convo if necessary, so I didn’t set up a ton of blank stickies this time.
> - If there are general observations or something that comes up that isn’t totally related to the task, it’s helpful to me if you leave the sticky in that section rather than try to separate it and organize it elsewhere.

</details>

## Supporting artifacts 

<details><summary>Toggle to reveal supporting artifacts</summary>

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-
    - **QUESTION: Product Outline:** `Link cut off` [Should the link be this?](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer)
    - **ANSWER:** [This is the link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/header-footer/federal-standardized-header-footer/README.md) to the federal standardized header/footer product outline. I'm not sure where it was cut off but I'm happy to update it :) 
- Prototype or mockups: not ready yet, will be added to research plan and convo guide when ready.  We are forking the prototype for the standardized header and footer, which your team has already reviewed.
    - [Prototype in Research Plan as of 1/22/2024](https://cdpn.io/pen/debug/JjzNWbR)`Confirmed`
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/authenticated-menu-usability/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/authenticated-menu-usability/conversation-guide.md)
- [Epics/issue that may be helpful](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72452)

Note: this is supporting the standardized header/footer work. [Here is their epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14078) if that's helpful.

</details>

## Next steps

```[tasklist]
### Authenticated Experience Team - Next Steps
- [x] Post a link to this ticket in the accessibility-help Slack channel and tag Terry Nichols.
- [x] Your team's researchers and observers read through [platform guidance on research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)
- [x] **LINK TO PROTOTYPE**: Prototypes will be tested in the following environment:`CODEPEN` with CAIA A11y(s). [Is this the prototype](https://cdpn.io/pen/debug/JjzNWbR) @andaleliz  ? `CONFIRMATION REQUESTED`
- [x] **QQ RE: Product Outline:** See question in supporting artifacts, regarding the product outline link.
- [x] **PILOT**: Schedule a pilot with CAIA A11ys, if time allows. Possibly `1/25 or 1/26/2024` - scheduled for 1/26 at 11:30 a.m. ET with Eli
- [x] **INVITE CAIA A11YS**: CAIA Specialists will need to be assigned to your research, be sure to add the respective a11y specialist(s) to your session invites (include the Zoom or Teams link). Be sure to invite the CAIA A11y Capacity Calendar - if possible. `Generic Holds Placed Currently`
- [x] **AT PARTICIPANT COUNT AND DETAILS:** See table in the body of this ticket (_above in the Device & AT Combinations section_). Provide specialists your participant details like skill level, operating system, assistive tech used, browser `Prior to Sessions - If Possible` `Partial Info Prior to Sessions Helps`
```

```[tasklist]
### CAIA A11Y - Next Steps
- [x] **REVIEW PROTOTYPE:** Prototype is now available to be tested in the following environment:`CODEPEN`
- [x] **REVIEW ARTIFACTS:** CAIA Specialists review your conversation guide and research plan.
- [x] **CALENDAR HOLDS - RESEARCH WINDOW** Put initial calendar holds on [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/New_York) ~`GENERIC HOLDS CURRENTLY`~ `OFFICIAL INVITES CURRENTLY`
- [x] **PILOT SCHEDULING** Participate in a pilot session with the Auth. Exp. team for ~1/24/2024 (date in Research Plan) if time allows. If taking place, please create a pilot ticket (a11y can ref. prev. historical pilot tickets - DONE~ #74259). ~1/25 or 1/26 inquiry sent to a11ys on 1/23~ - ~TBD based on availability.~ `SCHEDULED 1/26 at 11:30 a.m. ET with Eli`
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74259
- [x] **PILOT Notes** [c/o Evan via GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0c6c5ce66b56528813218b24f806a5d294d4916f/teams/CAIA/accessibility/Deliverables/Authenticated Experience/2024 01 26 Authenticated Experience - Authenticated Menu - Pilot Research Session.md) shared via [comments 1/26/2024 in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73875#issuecomment-1912504123) and via the Pilot Ticket (noted in this task list).
- [x] **CALENDAR HOLDS - OFFICIAL INVITES** Put official calendar holds on [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/New_York) ~`PENDING INVITES FROM TEAM/PERIGEAN`~
- [x] **PARTICIPATION:** Participate in User Research Sessions: '`START`1/29/2024 `END` 2/1/2024 - 1 of 3 sessions
- [x] **A11Y FEEDBACK:** CAIA Specialists to use the following: [research notes prepared for the session](https://docs.google.com/document/d/1Je4CeVnHCemesgkQ88nelszzyXE-rSMtzPDQc71KWIo/edit#heading=h.bge1m11x3klh)
- [x] **NOTE TAKING:** New Mural from Liz, [see note taking section of this ticket.](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/27?pane=issue&itemId=50317215#:~:text=Session%20Note%20Taking%20in%20Mural) (Also linked in pilot ticket)
- [x] **POST-RESEARCH:** CAIA Post research, specialists will add accessibility findings to a [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73875#issuecomment-1917873488)
```

**Comment by andaleliz** [comment]
Hi @sara-amanda just want to follow up with you on this since our study starts next week. Do you have any questions? Shall I just have you added to the SR sessions as they're scheduled? Thanks!

**Comment by sara-amanda** [comment]
> Hi @sara-amanda just want to follow up with you on this since our study starts next week. Do you have any questions? Shall I just have you added to the SR sessions as they're scheduled? Thanks!

Hi, @andaleliz ! Yes, that works! I can see who might be available for your session, and also add that specific session to our CAIA A11y Capacity Calendar. Thank you!  I went ahead and updated the ticket, and added a task list "next steps" for your team and for CAIA A11ys. 😄

**Comment by sara-amanda** [comment]
## Research Ticket Updates

- **Moving ticket to**: In Progress
- **Title**: Adding Testing Timeframe to Title
- **Pilot Session:** `TBD` - if time allows
- **Additional Ticket Updates:** _Updated ticket body to reflect schedule window and dates, information needed for a11ys prior to or during sessions, current status, pending invites, and additional next steps. Plus, generated task lists for the Auth.Exp. Team and CAIA A11Ys._
- _Multiple studies note added._

cc: @coforma-terry

**Comment by andaleliz** [comment]
Thank you @sara-amanda! I love how organized your team is, this is so easy to work through ❤️ 

- I updated the ticket above with a link to the product outline, and confirmed that yes, that is the correct CodePen link to our prototype
- I'd love to schedule an a11y pilot with your team if possible. It looks like there is availability Thursday or Friday during the same windows I noted in our availability table. Can I just send an invite to you (or another specialist) during one of those open times?
- I based the screenreader session times based on the availability I saw on the CAIA calendar. If I didn't interpret it correctly, please let me know. I'd be glad to do an SR session any time during the available windows, but plan on doing them on my own if needed.

**Comment by sara-amanda** [comment]
_Thank you @andaleliz for your flexibility! 😄 I am reaching out to the team to see if we can get a pilot set up for 1/25 or 1/26 and will keep you posted._

**Comment by andaleliz** [comment]
@sara-amanda 3 of the SR sessions have been scheduled. Who should I add to the invites? I saw your note about adding the CAIA capacity calendar but I'm not quite sure how to do that.  Thanks!

**Comment by sara-amanda** [comment]
Thank you, @andaleliz ! 

I will add them, now to that calendar and see if we are available for you. 

Speaking of availability, are you available to do the pilot in either of these windows? 
- **Friday** between 11:30 and 1 eastern (first choice, preferred window)
- **Thursday** between 1:30 and 3:30 (second choice, if first choice window doesn't work)

**Comment by andaleliz** [comment]
@sara-amanda yep, I can do Friday! I'd love to start at 11:30 if possible.

**Comment by sara-amanda** [comment]
> 3 of the SR sessions have been scheduled - @andaleliz 

I see one invite so far from Perigean c/o Matt.

- [x] January 29⋅10:15 – 11:00am
- [ ] Date/Time for SR Session `You can FWD invite to me`
- [ ] Date/Time for SR Session `You can FWD invite to me`

I will take a look at our capacity during these times when the other two are added. Thanks!

**Comment by andaleliz** [comment]
@sara-amanda that first session isn't a screenreader session. I'll forward them all to you, via the email in your Slack profile. Coming at ya!

**Comment by sara-amanda** [comment]
@andaleliz Perfect! Thank you! I will remove that first one. Thanks, again!

**Comment by sara-amanda** [comment]
@andaleliz [do you happen to know the type of AT (i.e. VoiceOver)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73875#:~:text=if%20absolutely%20needed.-,Device%20%26%20AT%20Combinations,-CAIA%20A11Ys%20will) your users will be needing support with in the studies?

**Comment by sara-amanda** [comment]
## Mobile Testing Limitations

> ... I'd prefer to test on mobile with VoiceOver or TalkBalk for the pilot if possible. I'm really curious how the auth menu works on mobile for SR users.

Hi, @andaleliz ! We would love to test that for you, but unfortunately, we are currently only equipped to test on `desktop` devices. However, @artsymartha68  is looking into this for us, with our contractor officers at VA, to see if CAIA A11Y folks can use their personal `mobile` devices for pilot testing.

@eli-oat  will be reaching out shortly to you about the pilot session, tomorrow.

cc: @coforma-terry

**Comment by EvanAtCoforma** [comment]
Hello @andaleliz , here's the [link to the pilot deliverable notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0c6c5ce66b56528813218b24f806a5d294d4916f/teams/CAIA/accessibility/Deliverables/Authenticated%20Experience/2024%2001%2026%20Authenticated%20Experience%20-%20Authenticated%20Menu%20-%20Pilot%20Research%20Session.md). Please let me know if you have any issues!

cc: @sara-amanda , @eli-oat

**Comment by coforma-jamie** [comment]
## Findings (in progress)

### There's a lack of understanding about "My VA"
- P4 didn’t understand the difference between “profile” and “My VA”, suggested combining them. “My VA…is My VA and Profile the same thing?”
- P8 didn’t understand what My VA was without explanation, but found it valuable after hearing the meaning explained

### The accessible name ([user], menu, popup) wasn't understood; users expected to be taken to a profile, not a menu
- P4: “Just saying ‘Derek’ doesn’t mean anything. ‘Derek’ what? Tell me before I land on this what I should expect."
- P8: Expected to hear “Your information” or “Your profile” or similar. “I thought when it said ‘Calvin, popup,’ it would’ve had my information pop-up that I would’ve been able to review and edit.”
