### ISSUE TITLE
Configure local storage for Find a Rep report feature

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#73879]
## Issue Description
When a user reports incorrect data, they must either select from three checkboxes, or input a text string describing the inaccuracy. We will be tracking this on the frontend using local storage. 

When the backend is able to accept reports, we'll push to local storage only after a 200 response. Tentatively, we'll push on submit of a report. So, after the user clicks "Submit".

---
## Tasks
- [ ] Push Report modal checkbox selections to local storage onSubmit
- [ ] For a given representative, hide checkboxes which have already been selected on a report submitted by the user 

## Acceptance Criteria
- [ ] Confirm that checkboxes which were selected in a previous report stay hidden (including between sessions)

**Comment by cosu419** [comment]
The basic Report Modal functionality should be complete now, along with error handling/various modal states. There are still some pending backend changes to the flag endpoint, so once released to staging by Monday, it will probably 404. 

(moved this to a 5 to reflect time spent refactoring + dealing with broken tests)
