### ISSUE TITLE
GIBCT - Upgrade AWS Database servers: Discovery and Upgrade Plan for GIBCT application and postgres usage

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#73887]
## Issue Description
Do discovery on the GIBCT application and the postgres usage in order to upgrade the AWS Database server environments (DEV, STG, Sandbox and PROD)

---
## Tasks
- [x] Discovery work on GIBCT application
- [x] Discovery on postgres usage
- [x] Complete discovery 
- [x] Create AWS Database upgrade plan
- [x] Get approval on AWS Database upgrade plan

## Acceptance Criteria
- [x] Discovery is completed and upgrade plan is formed, reviewed and approved for upgrade to the various environments.

**Comment by jennb33** [comment]
New tickets: 
Discovery of GIBCT application and postgres usage - ticket [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887)
Form plan to upgrade [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887)
Upgrade postgres in Dev  [73890](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73890)
Upgrade postgres in staging [73897](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73897)
Upgrade postgres in prod [73905](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73905)

**Comment by Kshitiz-devops** [comment]
Discovery in Dev:

- needed to change instance class before upgrade
- needed to upgrade Postgis extension
-

**Comment by jennb33** [comment]
Getting a 404 error, @Kshitiz-devops is working with @RachalCassity on getting to the root cause of the error.

**Comment by jennb33** [comment]
PER @RachalCassity WE CAN PROGRESS TO STAGING

**Comment by jennb33** [comment]
@Kshitiz-devops Let’s get that discovery ticket updated with details around the issues with the GIDS dev deployment

**Comment by Kshitiz-devops** [comment]
GIDS dev environment rev proxy was pointing to EKS which was no longer serving the app. Changed the rev proxy to GIDS in BRD. After that there was still error, changed the fwd proxy to point to GIDS in BRD. Developer is still facing issue.
