### ISSUE TITLE
[BE] Implement cerner checkin service class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73889]
## Description
Implement cerner checkin service class

## Tasks
- [ ] [BE] **Implement cerner checkin service class**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
