### ISSUE TITLE
[BE] Implement controller for cerner checkin

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73896]
## Description
Implement controller for cerner checkin endpoint in vets-api

## Tasks
- [ ] [BE] **Configure route for cerner checkin endpoint**
- [ ] [BE] **Implement controller for cerner checkin endpoint**
- [ ] [BE] **Add request specs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
