### ISSUE TITLE
GIBCT - Upgrade AWS Database servers: Upgrade postgres in STG

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#73897]
## Issue Description
Upgrade AWS Database servers postgres in **DEV** environment

---
## Tasks
- [ ] Work from tickets [72347](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72347), [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887), and [73890](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73890) is complete. 

## Acceptance Criteria
- [ ] That the postgres upgrade is complete, tested, and correct after testing.

---
## How to configure this issue
- [ ] End of Sprint 45 (February 13, 2024)
- [ ] backend, devops
- [ ] upgrade

**Comment by jennb33** [comment]
New tickets: 
Discovery of GIBCT application and postgres usage - ticket [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887)
Form plan to upgrade [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887)
Upgrade postgres in Dev  [73890](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73890)
Upgrade postgres in staging [73897](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73897)
Upgrade postgres in prod [73905](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73905)

**Comment by jennb33** [comment]
@Kshitiz-devops is reaching out to Noah today to see if there are any concerns and for a date so that we can start planning for PROD

**Comment by jennb33** [comment]
Per @Kshitiz-devops Noah's team response is that they want to have their prod upgrade in feb 21 sprint

**Comment by jennb33** [comment]
@Kshitiz-devops given Noah/GIDS response, and the fact that we have moved ticket [73905](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73905) to the 2/29-3/12 Sprint, is there any other work that needs to be done with this ticket, or can it be closed? Please advise within this ticket, thank you

**Comment by jennb33** [comment]
Per @Kshitiz-devops we can close this ticket, our upgrade to PROD is pending GIDS's upgrade which is scheduled for 2/21.
