### ISSUE TITLE
GIBCT - Upgrade AWS Database servers: Upgrade postgres in DEV

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#73890]
## Issue Description
Upgrade AWS Database servers postgres in **DEV** environment

---
## Tasks
- [x] Work from tickets [72347](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72347) and [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887) is complete.

## Acceptance Criteria
- [x] That the postgres upgrade is complete, tested, and correct after testing.

---
## How to configure this issue
- [ ] End of Sprint 44 (January 30, 2024)
- [ ] backend, devops
- [ ] upgrade

**Comment by jennb33** [comment]
New tickets: 
Discovery of GIBCT application and postgres usage - ticket [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887)
Form plan to upgrade [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887)
Upgrade postgres in Dev  [73890](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73890)
Upgrade postgres in staging [73897](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73897)
Upgrade postgres in prod [73905](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73905)
