### ISSUE TITLE
[BE] Implement cerner checkin method in client class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73895]
## Description
Implement cerner checkin method in client class

## Tasks
- [ ] [BE] **Implement cerner checkin method**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
