### ISSUE TITLE
[BE] Modify devops/settings.yml for adding cerner checkin endpoint

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#73900]
## Description
Modify devops/settings.yml for adding cerner checkin endpoint
Note: Might require changes in `vsp-infra-application-manifests` repo as well

## Tasks
- [ ] [BE] **Modify devops/settings.yml for adding cerner checkin endpoint for dev**
- [ ] [BE] **Modify devops/settings.yml for adding cerner checkin endpoint for staging**
- [ ] [BE] **Modify devops/settings.yml for adding cerner checkin endpoint for prod**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Not required anymore
