### ISSUE TITLE
Bump fitbit_api to 0.17.1

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#73902]
### Description
We should update the `fitbit_api` gem to latest, as it's a couple years out of date. We can't bump to 1.0.0 until we bump `oauth2` to 2+ (currently blocked by `fhir_client`), so we'll go to 0.17.1, which was released last month.

### Tasks
- [ ] Bump fitbit_api to 0.17.1 (latest version not blocked by oauth2 update)
- [ ] Merge to master

### Acceptance Criteria
- [x] Deployed to all envs
