### ISSUE TITLE
Draft static page for FSR wizard replacement

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#73909]
## Issue Description

If the team implements our recommendation to take the wizard out of the FSR form, we'll need to create a new static page and coordinate publishing timing based on when the form goes live.

And static pages related to debt relief? working with Denise (their PO)

---
## Tasks
- [ ] Create new “request financial help” static page
- [ ] Share with stakeholders
- [ ] Copyedit
- [ ] Launch

## Acceptance Criteria
- [ ] New static page is live
---

**Comment by aliyahblackmore** [comment]
We're still waiting to hear back about when we should start on this work.

**Comment by laurwill** [comment]
Hi @aliyahblackmore , since you have lots of product work ongoing, we're going to have @d-beyer jump in and do just the static page draft — Derek, since we also want to keep your time reserved for migration, let's plan for you to do only the first draft of the static page, pass it off to me, and then get out of any ongoing work with the product team. 

Here's the resources to use for the draft:
- Draft page structure: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73145#issuecomment-1992574695 
- Full wizard content (which we need to migrate out of the wizard and onto this static page): https://docs.google.com/document/d/1ar1vRu2HVe3cgtYyoUMYfB2bO4dotG4D7jlagpynKaI/edit#heading=h.pvocuzd3spq9
- GitHub file from debt resolution team with explanations of the wizard content: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/wizard/research/VA-debt-action-paths.md

You can also go to the live FSR form to see the wizard in action: https://www.va.gov/manage-va-debt/request-debt-help-form-5655/introduction 

And 1 note about the page structure: In our call last week with the product team, they mentioned that the section I had titled "all other benefit overpayments" should ideally come after the "health care copays" section. They used "disability compensation, education, or pension benefits" as the catchall header for this section, but the STEM scholarship and Vet Tec sections are types of education overpayments. So we should try to find a way to adjust the header structure to avoid confusion about different types of education debts, while listing the "disability, education, pension" bucket higher up on the page. If you have an idea for how to do this, please try it out! But also fine to draft the page in the existing structure, and I can adjust when I review.

Thanks, and let me know if you want to sync as you start working on this!

**Comment by HeatherRienks** [comment]
following  :)

**Comment by d-beyer** [comment]
@laurwill I made a [rough draft of the static page](prod.cms.va.gov/request-help-with-va-debt).

I didn't address:
- The heading organization issue you brought up in your last comment above.
- The other information that didn't already have a spot in the structure (if you did an FSR in the past 6 months, how to make a payment, or asking the Committee of Waivers and Compromises to reconsider).

**Comment by HeatherRienks** [comment]
Hi @laurwill and @d-beyer, 
Just wanted to check in to see if there is anything needed from our team at this time. Thanks!

cc: @mgleo @josephrlee @Tom-Davis @denisecoveyduc

**Comment by HeatherRienks** [comment]
Hi @laurwill and @d-beyer,

Just wanted to check in to see if there is anything needed from our team at this time. Thanks!

cc: @mgleo @josephrlee @Tom-Davis @denisecoveyduc @charlottecesana

**Comment by denisecoveyduc** [comment]
Hi @laurwill You mentioned you had some updates for the team? Just following up as we'd like to move this work forward if we can. Thanks in advance.

**Comment by josephrlee** [comment]
@laurwill, I have a quick answer to one of your questions: 

> **Personal statement with FSR**
> 
> * Wizard says you'll need to submit a personal statement
> * This [FSR FAQ](https://www.va.gov/resources/submitting-a-financial-status-report-va-form-5655/) says "we sometimes ask for a personal statement"
>   **Is the statement always required?**

I know a personal statement is required when folks request a waiver (copay or overpayment).

**Comment by laurwill** [comment]
Thanks Joseph! Does that mean the statement is optional if you're using the FSR to ask for a compromise offer or repayment plan?

**Comment by josephrlee** [comment]
@laurwill, yes, that's how the logic is setup on the form currently.

**Comment by mgleo** [comment]
Hi @laurwill -- Throwing out another complication about the personal statement:
Veterans who get the Streamlined Waiver (Veterans who only have copay debt and qualify depending on their financial situation) will _not_ see an option to fill out a personal statement. 

The personal statement page is shown for all other options for both VBA and VHA debt when they go through the full FSR (not the Streamlined Waiver). It is not required for all of them, it is only required when they select "waiver" as @josephrlee mentioned. 

cc @denisecoveyduc

**Comment by charlottecesana** [comment]
Hi @laurwill, thank you for working on the static pages for VHA and VBA. We are waiting for information about your questions about monthly offsets and time limits. In the meantime, we're hoping to revise our study plan and conversation guide per the new static pages. Would it be possible to share a draft of this work in progress? Thank you in advance!

**Comment by laurwill** [comment]
Thanks all for helping track down these answers!

And @charlottecesana , absolutely — the drafts should give you a good idea of the direction, just with the understanding that we may adjust structure and wording as we get more info and go through our editorial process. And of course let me know if you have feedback or questions about the content. I'll share updated versions with you after we answer those questions.

- Draft updates to Manage VA debt page: http://preview-prod.vfs.va.gov/preview?nodeId=6521
- New Request help with debt from benefits overpayments page: http://preview-prod.vfs.va.gov/preview?nodeId=67350

**Comment by charlottecesana** [comment]
Thank you @laurwill! I am looking at the drafts and will follow up with any questions.

**Comment by denisecoveyduc** [comment]
Hey @laurwill Thanks for the detailed updates. Sounds like the team has covered a few things but adding a few comments from my side. I am glad to hear that we are distilling this information into distinct pages with clear and intentional focus for each. This will really help remove confusion for everyone. Are there any IA resources that highlight these pages? I’d like to review if there is.

**To go thru your questions.** 

- **Time Limits:** Let’s go with the FSR Wizard content description. The Veteran has 180 days to request help with debt, but it is recommended that they request it within 30 days to avoid fees and collection actions. To add some complexity thought this timeframe will need to be changed on December 29, 2024.  As a result of the Cleland Dole Act which went into effect December 29, 2022, the 180 days will change to 365 days. 
- **Personal Statement:** This is an opportunity at the end of the FSR (VA Form 5655) for the Veteran to write more about their personal situation. The personal statement is an optional field and it is meant to give the Veteran a chance to provide the reviewer with a better understanding of the their financial situation. As Megan pointed out it is not part of the streamlined waiver experience because Veterans who quality don’t need to provide additional context; we already know based on the information they submitted that they need assistance.  
- **Monthly Offsets:** The discrepancy you are seeing is because originally the messaging was established with only VBA in mind. Then we added VHA. I am collecting additional information about how offsets work but it seems that a health care copay would be sent over to DMC who would set up the offset. So, it is an option, but it is a complicated one which would start with the Veteran submitting an FSR.

**A few questions for you:**

- **IA Resources:** As asked above are there any IA resources that highlight the content pages you discussed?
- **Estimated Publishing Date:** Could you give us a sense of when the “Request help with debt from benefit overpayments” page will be ready to publish? The debt team will have some work to do to review the previous wizard experience and @Tom-Davis and I were just looking to get a sense of timeline so we can plan accordingly. 
- **FAQ page updates:** In speaking with the SMEs, they would like to review the updated FAQ pages for accuracy. Could you let me know once you have finalized your draft so we can coordinate who needs to review from both VHA and VBA?

Thanks – _let me know what comes up next_ 😉 

FYSA: @HeatherRienks @josephrlee @mgleo @charlottecesana

**Comment by laurwill** [comment]
Thanks so much for the info @denisecoveyduc ! 
- @kristinoletmuskat will update the IA documentation next week for you to review. (And Kristin, let me know if any adjustments to the drafts are needed based on the IA work.)
- For estimated timing, we can aim to have the draft updates ready for SMEs to review by the end of June (both the new page and related updates to the FAQ pages). Our content team is out the first week of July for a Bloom Works summer break, so we could aim to update the pages based on SME feedback when we return. And publishing date will depend on how fast we can get approval for all the content.

**Comment by kristinoletmuskat** [comment]
Hey @denisecoveyduc and @laurwill , here is a very basic IA diagram outlining the approach! And it can be found on [this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1
![Screenshot 2024-06-17 at 3 49 16 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/ab76af2c-7106-4c93-9e20-cc7e134ded14)
682537441750/a9937e9953d80c221c5165131f611026e0419c7b?wid=0-1711474615207), under 'Version 3'.

**Comment by laurwill** [comment]
Hi @denisecoveyduc and team, 

I mostly finished drafting suggested updates to the full set of debt-related pages, in addition to the new static page to replace the bulk of the wizard content. The changes to the financial hardship assistance page are still TBD—tracking in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69414). 

Here are 2 remaining questions you may be able to answer:
- I found a mention of requesting waivers for VA home loan debt on [this page](https://www.va.gov/housing-assistance/home-loans/trouble-making-payments/). Can Veterans use the FSR to request waiver for home loan debt? Are there specific instructions for that use case that we need to include in this new static content?
- Several pieces of content say "If you submitted an FSR within the last 6 months, you don't need to submit a new one unless your financial situation has changed." Does this mean that we require you to resubmit the FSR after every 6 month period even if your finances haven't changed? I don't think that's the intended meaning, so I've suggested rephrasing this as "If your financial situation changes, you'll need to submit a new FSR" — but if I'm missing something important about the 6 month time limit, I can adjust. (And apologies if I asked this before, I wasn't able to find the answer documented.)

This work has ballooned into a larger set of content updates across 5 existing pages and 1 new page, so I'd like to run the changes by Danielle before we send to SMEs. There's also a limitation in Drupal that prevents us from previewing changes to live Q&A sections in resources and support pages. For now, I've collected the changes in [this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719575899476/af5312c6ead879ab159500a9ee7a572e11ed0b0a?sender=u3038037989bec1f893349894). I'll see if there's a way to preview these more helpfully for SMEs in Tugboat, or I can move content into Word docs.

I'll pass to Danielle to review now, and hopefully get this wrapped up and ready to send to SMEs when I return from OOO on 7/8. Let me know if you have any questions about the approach here, and happy to sync next week if that's helpful!

**Comment by laurwill** [comment]
Aha! I found the conversation about the 6 month time rule: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73145#issuecomment-2070022148 Let me know if you have any more info to add there.

**Comment by HeatherRienks** [comment]
Hi @laurwill - thanks for all of your help with this effort! Just checking in to see if you have any updates to share.

cc: @denisecoveyduc

**Comment by laurwill** [comment]
I'm now tracking all work for static pages related to FSR in [this new ticket](https://dsva.slack.com/archives/C044AGZFG2W/p1725641240231159) — closing this one to keep things organized.
