### ISSUE TITLE
[Design] 10-10CG Figma Migration - Additional Screens Converted

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#73916]
## Background
As we reach the end of the Sketch license, the VA.gov Platform and OCTO-DE leadership has decided to move from using Sketch to Figma as a design platform.

Now that we've completed migration for the key workflow pages of the 10-10EZR, we will determine what other pages are worth converting into Figma, which are worth documenting with images, and which are able to be archived or deleted.

## Tasks
- [ ] Mark pages in EZ Figma file using key: ⚠️ needs conversion, 📄 export to image, 🗑️ delete page
- [ ] For export to image, export those screens to PDF files or 2x PNGs. If there is a ticket number associated, upload images to those closed tickets in github.
- [ ] Add pages that need converted to [Figma migration spreadsheet here](https://docs.google.com/spreadsheets/d/1uQnYLw6gktq_yfMdkBQFvoxhPxIxeZmDmiStaqtOJdA/edit#gid=0)
- [ ] Add pages to tasks to this ticket listed below
     - [ ] Page 1 - Issue Number
     - [ ] Page 2 - Issue Number
     
## Acceptance Criteria
- [ ] All additional supplemental pages are updated in Figma that are needed or they are downloaded as images/archived
