### ISSUE TITLE
Content review of FSR language 

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#73914]
## Issue Description

Overall content review needed:
Ensure consistent terminology and language around debt relief vs. resolution, waivers, etc.
Word cluster 

---
## Tasks
- [ ] Review content 
- [ ] Draft feedback in sketch?
- [ ] Share with stakeholder

## Acceptance Criteria
- [ ] Feedback provided to stakeholder
---

**Comment by aliyahblackmore** [comment]
@strelichl since Derek is working on this, unassigning myself here!
