### ISSUE TITLE
EPIC | Profile | Mockingbird - Mock Testing Repository 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#73925]
## Background
- Originally part of 54241
This mini epic is to track the mock testing data work 

With additional downtime in April/May 2024 we worked to build out a new mock repository solution. We're sharing that with VES and hoping the repository can be hosted in the cloud and made available for BE and FE engineers on other teams. 

### other contacts 
- VES team
     - Charley Stran
     - Jamie DeHaan 

## Tasks
```[tasklist]
### Mock Testing Data (for dev/local testing)
- [x] Tom is working on #54238 which will generate a bunch of tickets
- [ ] #60571
- [ ] #60531
- [ ] #60572
- [ ] #60574
- [ ] #60570
```
```[tasklist]
### New Mock Repository Build (may 2024) - Phase 0
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81552
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81550
- [ ] #82753
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83569
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83571
```

```[tasklist]
### Refining - Phase 1
- [ ] #84768
- [ ] #84769
- [ ] #84770
- [ ] #84771
- [ ] #84772
- [ ] #84773
- [ ] #84774
- [ ] #84775
- [ ] #84776
- [ ] #84777
- [ ] #84779
```
