### ISSUE TITLE
Update Style Guide: Bylines and Attributions

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#73920]
# Issue Description
During several recent deployment, the team has noticed documents that have bylines on them. We DO NOT want content to have bylines. There is no guidance in the style guide about bylines and attributions. We want this to be the subject of this sprint's TIp of the Sprint (TOTS), since it seems to be a trend.  So, before we can work on the TOTS, we need to update the style guide to reflect our team's guidance on bylines. 

# Tasks
- [x] Draft byline guidance
- [x] Find a good spot for it in the Style Guide's IA
- [x] Get team approval of language
- [ ] Finalize language to include feedback from team. 

## Acceptance Criteria
- [ ] Document is approved and ready to be linked for Tip Of The Sprint 1/18/24
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Reviewed with notes and edits, closing ticket
