### ISSUE TITLE
GIBCT - Upgrade AWS Database servers: Upgrade postgres for local instances

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#73939]
## Issue Description
Upgrade AWS Database servers postgres for local instances

---
## Tasks
- [ ] Work from tickets [72347](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72347) and [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887) is complete.

## Acceptance Criteria
- [ ] That the postgres upgrade is complete, tested, and correct after testing.

---
## How to configure this issue
- [ ] End of Sprint 46 (February 13, 2024)
- [ ] backend, devops
- [ ] upgrade
