### ISSUE TITLE
Medallia Survey Launch Error 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#73946]
## Issue Description
_The Debt portal survey is in production, however, there are failure to load errors on the confirmation page 40% of the time.
---
## Tasks
- [x] Investigate the error 
- [ ] 

## Acceptance Criteria
- [x] Loading errors reach an acceptable rate. 
- [ ] ---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
Error rate is at an acceptable level of 1% now. 

When we initially looked at the errors in Sentry, the rate was high, but Sentry time is in UTC, so the errors we saw were from before going live. 

http://sentry.vfs.va.gov/organizations/vsp/issues/247928/events/9dd7f5ee0fdf483e80a3c557f456d48e/events/?environment=production&project=4&statsPeriod=14d
