### ISSUE TITLE
Connect Report Modal inputs to Redux state store

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#73948]
## Issue Description
On the "Report Outdated Information" modal, the checkboxes + text input should connect to Redux state. This will be used to control the components + assemble the post request when the user reports outdated information. 

---
## Tasks
- [ ] Pass corresponding representative for a report modal to redux store
- [ ] Control checkbox inputs with redux
- [ ] Control text input with redux

## Acceptance Criteria
- [ ] Fully controlled checkbox/text input components
- [ ] Corresponding representative name appears in modal component

**Comment by oddball-lindsay** [comment]
@cosu419 to connect this back to design, is this ticket intended to cover all three of these modal states?
1. No information reported
2. Some information reported
3. All information reported

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142453186/c4a8e2c4-74af-4f45-b29b-a1ba6cecaa57)

**Comment by cosu419** [comment]
@oddball-lindsay Yes this covers all states. Those states will be visible once reports start getting saved in local storage ([ticket](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/73879)).
