### ISSUE TITLE
create_ch31_submission_report_job.rb | Add queue exhaustion and exception logging

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73954]
## Issue Description
_The following job does not check for queue exhaustion nor does it have explicit exception logging:_ 
- [create_ch31_submission_report_job.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/vre/create_ch31_submissions_report_job.rb)

Steve added a temporary queue exhausting monitor:
- [VRE::CreateCh31SubmissionsReportJob has exhausted its sidekiq queue](https://vagov.ddog-gov.com/monitors/188839)

---
## Tasks
- [ ] Add checks for queue exhaustion to create_ch31_submission_report_job.rb
- [ ] Add explicit exception logging to create_ch31_submission_report_job.rb

## Acceptance Criteria
- [ ] create_ch31_submission_report_job.rb checks for queue exhaustion
- [ ] create_ch31_submission_report_job.rb logs explicit exceptions
---
