### ISSUE TITLE
Shadowing Research Prioritization Activity

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#73959]
Work with stakeholders and Team 1 to prioritize recommendations from the Shadowing Research by creating a prioritization activity for the first meeting. 

**Task** 

- [x] Create a prioritization board to facilitate meeting (Nichole)
- [x] Share the prioritization board with Team 1 and Team 2 Product Managers (Nichole)
- [x] Collaborate with Evelyn on activity
- [x] Two-to-go from Julie
- [x] Share with Shannon
- [x] Create a document with 526ez north star goals

**Acceptance Criteria** 

- [x] Build out the outline for the prioritization activity
- [x] Two-to-go from Julie P. for review of activity, content
- [x] Share with Shannon for Feedback
- [x] Address feedback
- [x] Create a document with 526ez north star goals

**Comment by nnicholas7** [comment]
Shadowing Prioritization Board (link): https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703092286405/34f0b24b01e41338f7ba4ddfe0b9505128af7d60?sender=u813bb40bd648bc2b58599242

**Comment by nnicholas7** [comment]
1/23: Austin chatted with Rakshinda about the prioritization activity.  Rakshinda is suggesting a collaborative refinement of the activity. Currently awaiting the second pass from Julie P.

**Comment by nnicholas7** [comment]
1/25: Sent to Shannon for a review of the activity.

**Comment by nnicholas7** [comment]
Prioritization Meeting Recap
- Feb 1: Team 1 and 2 (Research and Product) meeting to get aligned on activity
- Feb 2: 1st Prioritization Activity Meeting (All of Team 1 and Team 2)
- Unknown date: Larger Priorization meeting headed by Emily/VBA

**Comment by nnicholas7** [comment]
1/30: Closing this ticket. The Shadowing Prioritization Board has been updated with Medallia findings and team feedback.  Mural board has links to both Shadowing and Medallia data readouts.   

Shadowing Prioritization Board (link): https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703092286405/34f0b24b01e41338f7ba4ddfe0b9505128af7d60?sender=u813bb40bd648bc2b58599242

**Comment by nnicholas7** [comment]
Additional information can also be found on this ticket: https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/76400
