### ISSUE TITLE
Research to determine if Templates are required to address common incoming issues 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#73952]
## Issue Description
_As a Support Staff member, I need a place to collaborate with others to research incoming issues to determine the volume and if a template/tool is required to utilize in solving incoming issues._ 

---
## Tasks
- [x] _Create and publish spreadsheet in TEAMS._
- [x] _Share details with Support members_
- [x] _Determine when to incorporate into daily process_

## Acceptance Criteria

 - [x] **Scenario: Research to determine if Templates are required to address common incoming issues**
  - Given a Support Staff member needs a place to collaborate with others to research incoming issues
  - When the Support Staff member creates and publishes a spreadsheet in TEAMS
  - Then the spreadsheet is shared with Support members and a decision is made on whether to incorporate a template/tool into the daily process
Remember, each scenario must have a name, and the formatting must be followed precisely.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
The team has developed a spreadsheet in TEAMS titled Case questions.  This spreadsheet will allow team members to add case details and questions surrounding a topic that we need guidance on.

Once the information is obtained, if a template is needed, Steven can use the details from the spreadsheet to create and share out to the team.

If Steven deems a template necessary, he will create a ZH ticket for tracking purposes and update the spreadsheet accordingly.

**Comment by Kimberley2023-CSM** [comment]
​xlsx icon Case questions.xlsx

Link above can only be accessed on VA side with permission access.

**Comment by ATMiddleton** [comment]
Closed - view  sharepoint link above.
