### ISSUE TITLE
submit_career_counseling_job | Add queue exhaustion and exception logging

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73958]
## Issue Description
_The following job does not check for queue exhaustion nor does it have explicit exception logging:_ 
- app\sidekiq\central_mail\submit_career_counseling_job.rb

Steve added a temporary queue exhausting monitor:
- [CentralMail::SubmitCareerCounselingJob has exhausted its sidekiq queue](https://vagov.ddog-gov.com/monitors/188840)

---
## Tasks
- [x] Add checks for queue exhaustion to app\sidekiq\central_mail\submit_career_counseling_job.rb
- [x] Add explicit exception logging to app\sidekiq\central_mail\submit_career_counseling_job.rb

## Acceptance Criteria
- [x] app\sidekiq\central_mail\submit_career_counseling_job.rb checks for queue exhaustion
- [x] app\sidekiq\central_mail\submit_career_counseling_job.rb logs explicit exceptions
---
