### ISSUE TITLE
[UX] Update PCI Service Blueprint w changes to userflow

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#73965]
## Tasks
- [x] Update [PCI Service Blueprint](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696788763395/d3aa60a7420ece422a6f6b84659c33350279b782?sender=u37bb983bd3fc3cc00c7d3286) w changes to userflow. [Initial draft of userflow changes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=14%3A6233&mode=design&t=2Scnat0itZJrY9Tl-1). 
- [x] Update links in to service blueprint in [Git repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin#product) when work is validated

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets
