### ISSUE TITLE
[CAIA A11y Research]: MHV Cartography Team: Secondary Navigation Research Study  (January 2024)

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#73996]
# Project Overview

> [!NOTE]
> **High-Level Overview**: MHV Cartography Team
> - **Timeframe**: 1/24/2024 - 1/31/2024
> - **Pilot**: 1/22/2024  [Pilot Study with AT user (JAWS)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/Comparison-study/Pilot-AT-Jan-22.md) `Completed`
> - **Assistive Tech Users**: `6` with `4` _SR sessions to be supported by CAIA_
> - _*[Jump over to DSVA Slack](https://dsva.slack.com/canvas/C0581MN69TJ) to sign up for available slots*._
> - **A11y Assignees** in [First Table Below](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/27?pane=issue&itemId=50443889#:~:text=plan.%20Confirmation%20Needed-,Testing%20Schedule,-P%23)
> - **A11y Device Information** [Second Table Below](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/27?pane=issue&itemId=50443889#:~:text=SUPPORT%20NOT%20NEEDED-,Device%20%26%20AT%20Combinations,-CAIA%20A11Ys%20will)
> - **Task Lists**: [See task lists for next steps/definition of done ](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/27?pane=issue&itemId=50443889#:~:text=conversation%20guide%0A...-,Next%20steps,-Cartography%20Team%20%2D%20Next)for MHV Cartography and CAIA A11ys

## CAIA A11y Support
- Jamie
- SK
- Sara

### A11y Availability

<details><summary>Toggle to reveal A11y Availability information</summary>

_Thank you for reaching out to CAIA! We are looking forward to supporting your study. We wanted to let your team know that there are multiple studies taking place during the same timeframe for half of your study._ 

_We will do our very best to work with you and @artsymartha68, to support your research sessions, based on a11y availability. Should you have any questions, issues, or concerns please do not hesitate to contact @coforma-terry (CAIA A11Ys) and/or @artsymartha68 (OCTO) as soon as possible._

_We have blocked out your time slots on our [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York) for the time span you have provided._

#### Additional Notes: 
_Thank you @jonathanjnelson for your flexibility, as we navigate multiple studies the week of Jan. 29, 2024, along with the departure of our colleague. We appreciate you taking on those two studies with ping magnification on the 30th and 31st, while we help to support the screen reader sessions._ 

</details>

## Team Info.

- Team name: Cartography
- OCTO-DE product owner: Patrick Bateman 
- Product manager: Wes Rowe 
- Designer: Jonathan Nelson, Florence McCafferty
- FE engineer: Jim Zaccardo
- Product/team Slack channel: mhv-on-vagov-cartography-team

<details><summary>Toggle to reveal additional team information</summary>

### Do you have an accessibility champion?

Yes, we have a champion

### If you have an accessibility champion, what's their name?

Jonathan Nelson 

### Calendar checking

- [ ] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [ ] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [ ] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

</details>

## Research Sessions

<details><summary>Toggle to reveal research session information</summary>

> **Goals**: The purpose of this research is to assess and compare participants' ability to navigate the health portal using two distinct navigation concepts, both on mobile and desktop (total of 4 designs in all).

> **Outcome**: This research will inform us on how Veterans use different navigation designs to complete health management tasks and will provide direction on the next iteration of secondary navigation on the My HealtheVet portal.

### Timeframe

- **Pilot Session**: 1/22/2024 `Completed with Jamie`
- **Timeframe**: 1/24/2024 - 1/31/2024

### Length of sessions

- **Session length:** 60 minutes
- **Buffer time between sessions:** 30 minutes
- **Maximum sessions per day:** `pending info`

### Sessions

`6` sessions `3` appear to have [users with assistive technologies](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/Comparison-study/research-plan.md) based on the research plan. `Confirmation Needed`

</details>

###  Testing Schedule

<details><summary>Toggle to reveal testing schedule and AT device information</summary>

P# | Sessions | Time Slots (ET) | CAIA A11ys Available
------------------|------------------|--------------|--------------
P5 | Jan. 25, 2024 | 12:30 p.m. - 1:30 p.m.  | @SarahKay8 
P9 | `rescheduled from 1/26` Jan. 30, 2024 | 4 p.m. - 5 p.m.  | @coforma-jamie 
P10 | Jan 29, 2024 | 9 a.m. - 10:00 a.m.  | @coforma-jamie 
P11 | Jan 29, 2024 | 11 a.m. - 12:00 p.m.  | @coforma-jamie 
P15 | Jan. 30, 2024 | 2:30 p.m. - 3:30 p.m..  | `SUPPORT NOT NEEDED`
P16 | Jan. 31, 2024 | 12:30 p.m. - 1:30 p.m.  | `SUPPORT NOT NEEDED`

### Device & AT Combinations

CAIA A11Ys will be looking for information along the lines of the following. We realize that some of this information will not be available until the day of the session. 

**Participant Number** | Date of Research | **Assistive Tech** | **Skill Level** | **Operating System** | **Browser** |**Device Type** |
|------------------------|------------------|--------------------|-----------------|----------------------|-------------|-------------|
| _P5_                   | 1/25/2024         | Pinch Magnification       | Advanced  |  Apple | Safari | Mobile|
| _P9_                   | `rescheduled from 1/26/2024` 1/30/24       | Jaws, NVDA, ZoomText, Dragon, etc. `Screen Reader/Pinch Magnification - Type TBD`           | Novice, Intermediate or Advanced  `TBD`     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | `Mobile` |
| _P10_                   | 1/29/2024         | VoiceOver           | Advanced     |  iPhone  | Safari    | `Mobile` |
| _P11_                   | 1/29/2024          | VoiceOver, magnification           | Novice     |  MacOS  | Chrome    | `Desktop` |
| _P15_   `SUPPORT NOT NEEDED`                 | 1/30/2024         | Jaws, NVDA, ZoomText, Dragon, etc. `Pinch Magnification - Type TBD`           | Novice, Intermediate or Advanced  `TBD`     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | `Mobile` |
| _P16_       `SUPPORT NOT NEEDED`            | 1/31/2024       | Jaws, NVDA, ZoomText, Dragon, etc. `Pinch Magnification - Type TBD`           | Novice, Intermediate or Advanced  `TBD`     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | `Mobile` ||                  |                    |                 |                      |             |         |

> Please note that a couple of the sessions state “Pinch magnification” which we may not need support in but I included anyway. But as you know, partipants often show up to sessions and don’t use their screen reader tool or vise versa

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

## Supporting artifacts

<details><summary>Toggle to reveal supporting artifacts</summary>

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav)
- [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703733197192/681451fa506f1df2e76079a7b8fa491984a37a10?sender=u24af215c7d9bf806b8545488)
- [Prototype or mockups](https://codepen.io/figaro/project/live/AMVvEP) `CODEPEN`
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/Comparison-study/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secondary-nav/Comparison-study/conversation-guide.md)

</details>
...

## Next steps

```[tasklist]
### Cartography Team - Next Steps
- [x] Post a link to this ticket in the accessibility-help Slack channel and tag Terry Nichols.
- [x] Your team's researchers and observers read through [platform guidance on research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)
- [x] Prototypes will be tested in the following environment:`CODEPEN` with CAIA A11y(s).
- [x] **SIGN-UPS**: Canvas Created by Team: _[Jump over to DSVA Slack](https://dsva.slack.com/canvas/C0581MN69TJ) to sign up for available slots._
- [x] **INVITE CAIA A11YS**: CAIA Specialists will need to be assigned to your research, be sure to add the respective a11y specialist(s) to your session invites (include the Zoom or Teams link). Be sure to invite the CAIA A11y Capacity Calendar - if possible. `Generic Holds Placed Currently`
- [x] **AT PARTICIPANT COUNT 4 AND DETAILS:** [See table in the body of this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73996#:~:text=SUPPORT%20NOT%20NEEDED-,Device%20%26%20AT%20Combinations,-CAIA%20A11Ys%20will) (_above in the Device & AT Combinations section_). Provide specialists your participant details like skill level, operating system, assistive tech used, browser `Prior to Sessions - If Possible` `Partial Info Prior to Sessions Helps`
```

```[tasklist]
### CAIA A11Y - Next Steps
- [x] Meet with Angela Fowler to discuss project handoff to CAIA A11ys for support #73648
- [x] **REVIEW PROTOTYPE:** Prototype is now available to be tested in the following environment:`CODEPEN`
- [x] **REVIEW ARTIFACTS:** CAIA Specialists review your conversation guide and research plan.
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73798
- [x] **SCHEDULE PILOT** Schedule a pilot session with the Cartography team for the week of 1/22/2024 and create ticket.
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73999
- [x] **CALENDAR HOLDS - RESEARCH WINDOW** Put initial calendar holds on [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=#ffffff&ctz=America/New_York&mode=WEEK&src=Y19mOTgyMzUwZmM3M2E4MTYyYTEwODhhYjE0ZDAwZGQzNzMzNWIyYjU1OWE2MGQ2YjY3ZWI4MDIxNDE2ZjgxYzJhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=#616161) `GENERIC HOLDS CURRENTLY`
- [x] **CALENDAR HOLDS - OFFICIAL INVITES** Put official calendar holds on [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=#ffffff&ctz=America/New_York&mode=WEEK&src=Y19mOTgyMzUwZmM3M2E4MTYyYTEwODhhYjE0ZDAwZGQzNzMzNWIyYjU1OWE2MGQ2YjY3ZWI4MDIxNDE2ZjgxYzJhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=#616161) `PENDING INVITES FROM TEAM/PERIGEAN`
- [x] **A11Y FEEDBACK Prep:** CAIA Specialists create a [research notes template](https://docs.google.com/document/d/131yib1ZWnoxwK7xmyI32drcPgGI0IJd0SlNqVwX3alo/edit) created and ready to use by JKF
- [x] **PARTICIPATION:** Participate in User Research Sessions: '`START`1/24/2024 `END` 1/31/2024
- [x] **A11Y FEEDBACK:** CAIA Specialists to take notes in the [research notes template](https://docs.google.com/document/d/131yib1ZWnoxwK7xmyI32drcPgGI0IJd0SlNqVwX3alo/edit).
- [x] **POST-RESEARCH:** CAIA Post research, specialists will create and send you a [findings document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/MHV%20Cartography%20Team/2024-01-31-Secondary-Navigation-Research.md)
- [ ] Finalize outstanding feedback week of 2/5/2024.
```

**Comment by sara-amanda** [comment]
## Research Ticket Updates

- **Moving ticket to**: In Progress
- **Title**: Adding Testing Timeframe to Title and MHV
- **Pilot Session:** Completed today with @coforma-jamie and Cartography Team (notes linked)
- **Additional Ticket Updates:** _Updated ticket body to reflect completed tickets, schedule window and dates, information needed for a11ys prior to or during sessions, current status, pending invites, and additional next steps. Plus, generated task lists for the Cartography Team and CAIA A11Ys._

cc: @coforma-terry

**Comment by sara-amanda** [comment]
## Testing Schedule Slots Updated

- [x] Table Updated in Body of Ticket
- [x] Updated Holds on Calendar

### Canvas
There is also a [Canvas](https://dsva.slack.com/canvas/C0581MN69TJ), where people can sign up. 

### Dates Obtained from Cartography
- Thursday, January 25 12:30 pm – 1:30pm screenreader/pinch magnification - smartphone
- Friday, January 26 2:30pm – 3:30pm screenreader/pinch magnification - smartphone
- Monday, January 29 9:00am – 10:30am screenreader - smartphone - smartphone
- Monday, January 29 11:00am – 12:00 pm pinch magnification/screenreader - desktop
- Tuesday, January 30 2:30pm – 3:30pm pinch magnification smartphone
- Wednesday, January 31 12:30pm – 1:30pm pinch magnification smartphone

Dates c/o @coforma-jamie c/o the MHV Cartography Team 

cc: @coforma-terry @artsymartha68
