### ISSUE TITLE
[Content] [VistA appts] Create content for new "Which of these best describes how far you are from the clinic?" page and body content for 1-2 variations of the "You're checked in" page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#74008]
## Background 

**_Question:_** 
_If Veterans check in outside, then go to the MSA desk when they arrive in the waiting room per our new instructions, but learn MSAs have still already called them back and marked them as absent, does this do anything to help resolve the issue?_

These changes are only helpful **_if we can influence action_**. As IVC looks into influencing staff action, we should further consider **_how we can influence Veteran action. What can we tell Veterans that would help resolve the core problem (and avoid telling Veterans to go see staff after checking in from outside the waiting room)?_** 

### What we don’t know: 
**_Because sites have different policies vs. national policies and policies aren’t always followed._** 

- How long staff will take to call the Veteran back the 1st time. 
- How long staff wait until a second callback/if staff will always call Veterans back a second time
- When exactly Veterans are checking in when this problem occurs

### What we can influence:

- If staff know that Veterans are in the waiting room or not
- How soon a Veteran checks in 
     - We can encourage Veterans to check in closer to the waiting room
- How quickly Veterans get to the waiting room after checking in
     - We can prompt Veterans to get there quickly and not dilly dally - within 5-10 minutes, for example

#### Asking for Veteran’s location

**This would do a few things:**
- Creates a "receipt" so to speak that the Veteran indicated they were not there yet. 
- Allows staff to know, at first glance, that they can expect a possible delay - anything to help prevent them from giving up right away and marking them absent.
- And, in the realm of "can't hurt solutions," the more staff know in the case, the better decisions they can make

**Options:**
- Ask about waiting room vs. not in waiting room
     - Checked in/in waiting room
     - Checked in/not in waiting room
- Or ask about specific timing:
     - I'm in the waiting room
     - I'm less than 5 minutes away
     - I'm more than 5 minutes away

**And, for either option, include more instructions for Veterans:**
- On the "are you in the waiting room" page, include more instructions to influence timing, such as:
     - Suggest they get there quickly
     - Suggest Veterans wait until they’re closer to the waiting room to finish checking in, if possible

## Tasks

[Userflow](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=14%3A6233&mode=design&t=fUaYD5jut6HibuKC-1) 

- [x] Create the content for the new "Which of these best describes how far you are from the clinic?" page. (Note: That is a draft H1 that needs to be rewritten.) 
- [x] Create the body copy below the "You're checked in" page's H1 for the 1-2 variations of answers to the question, "Which of these best describes how far you are from the clinic?"

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [x] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [x] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by kellysmith1008** [comment]
Mocked up 2 proposals from the [draft proposals](https://docs.google.com/document/d/1AjNS3qOqpJK1eObW5QW6mX-LkwjGDJaIX4tVNV89tJU/edit?usp=sharing) and tagged Ben and Kristen in them for validation. @benbrasso-agile6 I'm putting this in validate and will move it to done once you and Kristen provide feedback and choose an option

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 this ticket also includes potential changes to the Success page. Did you do that as well? I might have missed it.

**Comment by kellysmith1008** [comment]
Sheesh - nope. Definitely missed that part - so sorry about that!! Back into in-progress she goes :)

**Comment by kellysmith1008** [comment]
Putting this back in validation because I believe we've gotten signoff on both tasks from Kristen in figma - want to make sure @benbrasso-agile6 agrees.

**Comment by benbrasso-agile6** [comment]
Yes, I'm in agreement. Let's close this. @cgednalske has the design ticket associated with this one.

**Comment by cgednalske** [comment]
Ope - missed this comment ☝️  On it!

**Comment by cgednalske** [comment]
@benbrasso-agile6 @kellysmith1008 I'm searching around for the decision for this one but haven't found it yet. Could you point me to the option we chose? 😄 Right now I just have all versions at the ready.

**Comment by benbrasso-agile6** [comment]
https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=199%3A5811&mode=design&t=tHPFTxTHDQAKH4DD-1
