### ISSUE TITLE
[UX] 10-10EZ - Reg Only: Session 2 Artifact Creation for Working Sessions

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#74006]
## Issue Description
After the first working session for a registration reason scenario, refine the journey map and learnings from SMEs into a refined current state version and future state version to share in Session 2. 

These will be used during the second working session with HEC and in a shareable format. 

---
## Tasks
- [x] Create a journey map template to use in Mural
- [x] Update with current and future state versions for each Registration Reason listed below
  - [x] Service Connected Only
  - [x] Mental Health Care 
  - [x] C&P / Exposure Registry Exam

## Acceptance Criteria
- [x] Storytelling experience maps are refined and ready for second working session for each reason
---

**Comment by hdjustice** [comment]
Hi @jessicastump - is this ticket still needed?

**Comment by aagosto90** [comment]
Going to create these in Mural since there aren't any Figma libraries set up yet. We can revisit using Figma if a library is created for it now that the VES team knows that would be useful. [Link to Slack thread](https://dsva.slack.com/archives/C0NGDDXME/p1707401405441319)

**Comment by aagosto90** [comment]
Closing this ticket and creating a new one that outlines finalizing the journey maps for sharing with stakeholders
