### ISSUE TITLE
[Discovery] | Confirm you're done adding evidence (formerly Ask for your claim decision)

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#74003]
## Value Statement
**_As a_** Designer
**_I want to_** have a firm understanding of the process for Confirm your done adding evidence (formerly Ask your claim decision)
**_So that_** I can create content and a UI (user interface ) design that is comprehensive for veterans

## Acceptance Criteria

- [ ] Learn when and where things will appear
- [ ] Clear definition of the circumstances  in which some veterans seeing this notification
- [ ] Understand what happens in the background when the notification is sent
- [ ] understand what happens when veterans responds
- [ ] Findings should be validated by an SME. 

## Open questions
- Are notifications all digital or will there be paper?
- what info goes out from VBMS, what touch points are there.
 - what "actually" happens when veterans check they have submitted everything compared to what's "supposed" to happen

## Tasks
- [ ] 

## Definition of Done

- [ ] Clear value description
- [ ] Flow of when things are delivered and how
