### ISSUE TITLE
[Design] Create Final Wireframes for the new "Which of these best describes how far you are from the clinic?" page and 1-2 variations of the "You're checked in" page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#74010]
## Tasks

[Userflow](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=14%3A6233&mode=design&t=fUaYD5jut6HibuKC-1) 

- [ ] Create the wireframe for the new "Which of these best describes how far you are from the clinic?" page. (Note: That is a draft H1 that needs to be rewritten.) 
- [ ] Update the body copy below the "You're checked in" page's H1 for the 1-2 variations of answers to the question, "Which of these best describes how far you are from the clinic?"
- [ ] Add in text messages: 45MR and text "check in" methods

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by cgednalske** [comment]
@benbrasso-agile6 this is still something we need, right? But for the VISTA userflow only?

**Comment by benbrasso-agile6** [comment]
Left feedback in Figma

**Comment by cgednalske** [comment]
I think we're good to close this one! Sound good @benbrasso-agile6 @kellysmith1008?

[Figma link for these VistA screens](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=183-764&mode=design&t=SvbTdEDUT8MTUTUi-0)

**Comment by loripusey** [comment]
@cgednalske the link above takes me to this, can you give me a better link? I need to create some FE tickets for this work
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f5083312-025f-4e12-9478-856a44c41867)

**Comment by benbrasso-agile6** [comment]
https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3?node-id=921:6175&t=SvbTdEDUT8MTUTUi-0&locale=en&type=design
