### ISSUE TITLE
[UX] Update PCI Service Blueprint to add row(s) for OH check-ins

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#74025]
## Resources
[Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/check-in-for-oracle-health.md)

## Tasks
- [x] Update [PCI Service Blueprint](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696788763395/d3aa60a7420ece422a6f6b84659c33350279b782?sender=u37bb983bd3fc3cc00c7d3286) to add row(s) for OH check-ins

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [x] Check in team (e.g., PO, DM, engineers)  
- [x] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [x] Work was reviewed by groups indicated above
- [x] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696788763395/d3aa60a7420ece422a6f6b84659c33350279b782?sender=u37bb983bd3fc3cc00c7d3286

**Comment by benbrasso-agile6** [comment]
Make final tweaks to userflow options by Tuesday and ping Kay

**Comment by benbrasso-agile6** [comment]
This is blueprint ticket, not userflow ticket. Moved it back.

**Comment by benbrasso-agile6** [comment]
Need to rollover; couple things need to get worked out with Brian, re: https://dsva.slack.com/archives/C02G6AB3ZRS/p1707253719314269

And, need to document a bit about appt reminders. 

@loripusey I wasn't able to finish this before end of sprint

**Comment by benbrasso-agile6** [comment]
@loripusey want to validate https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707427471672/75fb6b9eea27c7b854e8b31c0e9017e2a54bb95a?sender=u37bb983bd3fc3cc00c7d3286

**Comment by loripusey** [comment]
I added a few comments that may help to clarify some things.

**Comment by benbrasso-agile6** [comment]
Updated https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707427471672/75fb6b9eea27c7b854e8b31c0e9017e2a54bb95a?sender=u37bb983bd3fc3cc00c7d3286
