### ISSUE TITLE
Remove broken link from burials page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#74029]
## Issue Description
We learned we have a broken link on our [After you apply for an eligibility determination](https://www.va.gov/burials-memorials/pre-need-eligibility/after-you-apply/) page. 

The link is under the "If you don’t qualify for burial benefits" H2: Get more information about claims and review processes
We have a link directly above pointing to a modernized page about appeals and reviews, so we don't need to replace this with anything,

Note: This page has draft changes that can't go live yet. We need to revert to the previously published version, make the change, publish, revert to the most recent draft, and remove the link again. 

## Tasks
- [x] Revert to previous draft version (Randi)
- [x] Remove broken link (Randi)
- [x] Publish 
- [x] Revert to previously saved draft (Randi)
- [x] Remove broken link and keep in draft (Randi)

## Acceptance Criteria
- [x] Broken link is no longer live on page
- [x] Draft changes are saved and in most recent version

**Comment by RLHecht** [comment]
I removed the link and Laura published. I resaved as draft. Once this is live we can close this @strelichl

**Comment by RLHecht** [comment]
Changes are live. @strelichl You can close!
