### ISSUE TITLE
[UX] Set up Metrics to Measure Success for OH check ins

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#74027]
## Tasks
- [x] Create metrics to measure and evaluate success for the Epic
- [x] Make metrics available to the team
- [x] Create FE ticket for implementation on their end

**Comment by benbrasso-agile6** [comment]
https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=2075861504

**Comment by benbrasso-agile6** [comment]
@loripusey https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/77091
