### ISSUE TITLE
[FSR] Survey information feature flag implementation

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#74030]
## Description
Create a feature flag that will control the visibility of the Medallia survey button on the confirmation page of the FSR. Since the feedback button is it's own component we can probably manage the render in there, just in case we implement it in multiple locations.

**Note:** Since the survey is already implemented and live on production make sure the feature flag is active when the change goes into the FSR code.

`SurveyInformation` is the name of the component that's implemented on the `ConfirmationPage` in a couple different spots. 

[Feature flag documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

## Tasks
- [ ] PR vets-api with feature flag changes
- [ ] PR vets-website with feature flag changes
- [ ] PR vets-website with feature flag implemented on `SurveyInformation`

## Acceptance criteria

- [ ] Feature flag controlling Medallia survey is active 

## Testing
- [ ] Test feature flag is controlling visibility of SurveyInformation

Testing procedure:
Test on local/staging environments to confirm functionality 

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
As of now, not needed as this is for the button only - the pop up should be addressed separately.
