### ISSUE TITLE
Medallia - add feedback button to school administrator landing page

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#74037]
## Issue Description
IIR team working to update the [School Administrators landing page](va.gov/school-administrators/) requested the adding the Medallia feedback button to the landing page.

---
## Tasks
- [x] Add feedback button

## Acceptance Criteria
- [x] Feedback appears at bottom of main on page
- [x] Feedback button opens Medallia survey modal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
Feedback button was added to the School admin landing page template. Work is complete.
