### ISSUE TITLE
Obtain emails of all VA.gov mobile users

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#74039]
## Issue Description
_As a _, I need to obtain list of emails of all VA.gov mobile users so that I can _ _

---
## Tasks
- [x] _Investigate API for retrieving all mobile user ICNs from datadog?_
- [x] _Determine how far back datadog has logs with mobile user icns?_
- [x] _Determine how to pull all the ICNs and create a distinct list of ICNs_
- [x] _Correlate the ICNs with email address from MPI dataset_

## Acceptance Criteria
- [x] _A list of distinct ICNs and associated email addresses (if available)_

**Comment by sdickson-gt** [comment]
Reviewing and have tested the datadog API to search logs.  Looking into nocode options, e.g. excel, to call the api and process the json response.

**Comment by sdickson-gt** [comment]
Emails provided to Lauren and Carl via VA tesams
