### ISSUE TITLE
Update support bot auto responder text

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74034]
## Issue Description
After demoing the support bot improvements, a text change was requested by Naomi to the survey auto response. Naomi and Alyssa worked together to come up with new text for this message so this text will need to be updated and deployed to the live support bot.

---
## Tasks
- [ ] Change survey link text from "HERE" to "how you would rate your service here". 
- [ ] Redeploy the support bot

## Acceptance Criteria
- [ ] The support bot's live text has a link that's more indicative of what action they're taking by clicking on the link.
---
