### ISSUE TITLE
[CST] Update to contention list overflow

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#74042]
## Value Proposition

As a veteran with a pending claim that contains many contentions, I would like my contention list to be presented in a way that is digestible, readable, and doesn't obscure other important content (such as action items for me), so that I can verify the contention information is correct, while also seeing other important claims content (such as action items). 

## Background

Now that we have [data from Data Dog](https://vagov.ddog-gov.com/dashboard/p2a-9ii-9hz) on the number of contentions that claims have, it seems like our [previous solution to the claim contention overflow](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67669) isn't ideal.

~35% of claims have more than 5 contentions, and some have many more than that.

- 18 out of the last 112k claims viewed in the CST had 100+ contentions
- 600 had 50+ contentions
- 4.34k had 25+ contentions
- 18.9k had 10+
- 38.6k had 5+

Our previously proposed design doesn't handle these scenarios very well, especially on mobile. Given this new information, we should use a pattern (like a modal) that can accommodate many contentions.

## Design

[Mocks in Figma](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-1345&mode=design)

Screenshot
<img width="572" alt="Screenshot 2024-02-06 at 1 23 56 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/fb60792b-8995-4385-b606-21cbfa46c70d">

## Tasks

- [ ] Create revised design spec for to handle claim contention overflow on desktop and mobile
- [ ] Ensure the new solution meets a11y criteria
- [ ] Build it

## Acceptance Criteria

- [ ] Presentation of contentions list does not require the user to excessively scroll to see all the contentions. 
- [ ] Contention list provides the user with a complete list of contentions if they want to see that
- [ ] Presentation of contentions list does not require the user to scroll excessively to discover other page content that's critical for the user to understand or take action on their claim

**Comment by jacobworrell** [comment]
@skylerschain to run design approach by DK. Once Skyler decides on design approach, we'll revise the AC accordingly.

**Comment by skylerschain** [comment]
Moving to "In progress" since @davidakennedy and I have started to work on this.

**Comment by skylerschain** [comment]
Moving to top of "Backlog" so @davidakennedy and I can pick this up next sprint.

**Comment by jacobworrell** [comment]
@skylerschain can we point this along side @davidakennedy before picking it up?

**Comment by HeatherWidmont** [comment]
"Decided we probably won't get this in for V2 & it will be a fast follow as we figure out a better solution" https://dsva.slack.com/archives/C056854SVT8/p1709741725755509?thread_ts=1709739825.403809&cid=C056854SVT8

**Comment by jacobworrell** [comment]
duplicative, closing
