### ISSUE TITLE
[Discovery] Why don't vets-api pods get replaced after sync?

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#74041]
### Problem
We merged a change into the manifest repo (https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2608) and needed it to be deployed immediately so we clicked Sync and it successfully synced, but none of the pods were replaced. We needed the pods to be replaced.

### Thoughts
During our daily vets-api deploy, this never happens. The pods always cycle and are replaced. This instance happened about 30 min after prod was deployed, so there weren't any other changes going out. It was only the single manifest change. There is a way to do a rolling restart of pods ([documented here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2636185641/Rolling+restart+of+vets-api)) but no one at the time had prod kubectl access. As a workaround, we ended up bumping up the CPU [in this PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2609/files) which did cause the pods to replace themselves.

- [Slack thread where we debugged this](https://dsva.slack.com/archives/C0460N83Y9G/p1705611546160239?thread_ts=1705610652.438949&cid=C0460N83Y9G)

### Tasks
- [x] Figure out why pods don't get replaced sometimes
- [x] Document findings in this ticket (or Confluence doc)
- [x] Share findings with the Backend CoP

**Comment by jennb33** [comment]
@rmtolmach - @LindseySaari and i reviewed and have a couple of questions:
1. what is the regularity/cadence of this happening? 
2. is there a negative impact when this happens? what is it?

**Comment by rmtolmach** [comment]
1. Doesn't happen often. Seems to happen when we want to deploy a certain change to the manifest repo shortly after the main sync (i.e. there's nothing from vets-api to deply). This scenario often occurs when something didn't go to plan during the scheduled sync/deploy. 
2. The negative impact is a delay in deployment. In this scenario, the commit we wanted to deploy was to fix production. If pods were replaced after the sync, prod would have been fixed 20 minutes faster (according to [the postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1414)). But because they were not replaced, we had to troubleshoot and eventually found a workaround.

**Comment by RachalCassity** [comment]
Documentation: [Restarting ArgoCD Deployments to Recycle Pods](https://vfs.atlassian.net/wiki/spaces/OT/pages/2575040571/Basic+EKS+vets-api+debugging+in+ArgoCD#Restarting-ArgoCD-Deployments-to-Recycle-Pods)

**Comment by RachalCassity** [comment]
Documentation modified: [How do the secrets work with the parent helm charts?](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2452193284/Vets+API+on+EKS#How-do-the-secrets-work-with-the-parent-helm-charts%3F)

**Comment by RachalCassity** [comment]
@jennb33 Documents have been reviewed. Closing ticket.
