### ISSUE TITLE
Collaboration Cycle for [Benefits Dependent Experience, 21-686c/674, Critical Form Updates]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#74059]
### VFS team name

Benefits Dependent Experience Team

### Product name

21-686c and 21-674

### Feature name

Critical Form Updates

### GitHub label for team

Tree

### GitHub label for product

686

### Public DSVA Slack channel for VFS team

benefits-dependents-management

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

December 2023

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Unsure

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/dependents/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C0547Q0K0LF/p1705690392481269)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [X] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687976281975/2a9c6ca9ea6d955afa7977c777bbb72b15280903?sender=u934f98f179a86c76e6ee9592) 686c Form Simple Flow (and future changes)
- [X] [Figma](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&mode=design&t=o5XCj8n60B1SAqFw-1)
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C0547Q0K0LF/p1706034784901569)
- [x] Meeting date/time: 1/30/24 at 3:30pm ET
  
##### Platform actions

* Accessibility
  * [ ] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/tpKbMxuRL_hbFwkwIQXhcghu2eecfwkUjk1MdGKRWHNppg_IpG4pHFQ5HjOYLcjD.oPzsViy9QU_46vl_)
  - Passcode: `%V21qDQK`
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

- [Sitewide CAIA Intake Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75068)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=8%3A9&mode=design&t=d8ieMFOiODqQO3M5-1)
- [x] Specify which pages are included in the review:
      - All pages under "DESIGNS in progress V2"
- [ ] Research plan
- [ ] Conversation guide
 
**Content artifacts**
  
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C0547Q0K0LF/p1708020762834489)
- [x] Meeting date/time: ~~Monday, February 12, 3:30 p.m. ET~~ ~Thursday, February 15, 3:30 p.m. ET~ Friday, February 23, 2024 at 11:30 a.m. Eastern

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/oIsnBW8FKn-BL51mEXNuog1ij_JqMUXLSSU9lHSyrGn859vvmTEAs27a2Pe4EmLH.R14Gn2uAO_GTLFlW
  - Passcode: T?E1VRwV
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [ ] Staging URL
- [ ] Specify which pages are included in the review        
- [ ] Staging test user information         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
  
**IA artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [ ] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
- [ ] [Test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-test-planTestPlan)
- [ ] [Coverage for References](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [Summary(Defects) reports](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)
- [ ] [E2E tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-e2e-test-participationE2ETestParticipation) (provide a link to the product’s code)
- [ ] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording link 
  - Password:
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by ajialeilani** [comment]
FYSA, as of midpoint review, we were using the [single page pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---single-page) and recently updated designs to use the preferred [multi page pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page).

**Comment by shiragoodman** [comment]
@steele-lm at Kickoff, I see you answered `Tree` when asked what your teams Github label is. I only see the `Tree` label used by us in the Collab Cycle. You also added the `dependents-benefits` label to this ticket... is that your teams preferred label in github?

**Comment by steele-lm** [comment]
@shiragoodman Apologies, our team went through a labeling switch after this ticket was written, and I missed updating it. We now use depenents-benefits, and "tree" has been depreciated.
