### ISSUE TITLE
[Test ticket]

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#74058]
## Value Statement
**_As a_** user type
**_I want to_** job to be done
**_So that_** desired outcome(s)

---
## Background Context
- Add here

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Designs and Build Notes

[Figma](https://www.figma.com/file/Yv1rMq4a6ECCuu83cA1Ebh/BMT-Template-(Copy)?type=design&node-id=2-11&mode=design&t=hpYq8YTEKE2u02Fr-11)

<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2poQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5de605dbdfe19ceed853db7426cba045cb9eea84/Screenshot%202024-01-19%20at%201.46.17%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 1.46.17 PM.png" />

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
labels: ["benefits-team-1", "benefits-management-tools"]
