### ISSUE TITLE
Complete move of data record to shareable space for Platform Feedback

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#74050]
## Purpose
We need the [main sheet ](https://docs.google.com/spreadsheets/d/1ltsn6ACSMd2lwGvr0PyhUYG2Fw3HhWcIG1ZQMfsNeu4/edit#gid=1055692254)to be accessible by all team members.  The optimal approach would be for it to be in a shared space such as our Service Design Team [folder](https://drive.google.com/drive/u/0/folders/1lZsgCTF_0ldIdk5nblvIrHf9HDiuJHmx), but this requires Google drive account info that we do not have.  I have reached out for guidance and Joe Tice and Curt Bonade have offered to help us set this up

## Tasks
- [x] Schedule session (Bryan)
- [x] Conduct [learning session ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2923036978/Session+help+w+Domo+setup+to+a+Google+sheet)(Bryan/Dan)
- [x] Make resultant changes (Dan)

## Acceptance Criteria
- [x] Sheet is available to all team members and connected to Domo dashboard

**Comment by twoangstroms** [comment]
Prepended Sheet in my Drive with DEPRECATED
