### ISSUE TITLE
Design | Profile | Maintenance | Rework the account security headings as links design

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#74053]
## Background
This ticket is to cover the work if the design system a11y folks determine we shouldn't have headings as links on this page. 

See the process list headings ([experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2383)) ticket for additional details. 

Currently our custom solution has drifted/does not align with the styling of the USWDS design component for a process list. Hit up Adam for more details. 

## Tasks
- [x] Whoever picks this up can remove the other designer from the assignees
- [x] If needed, work with CAIA to refine all the content so headings are no longer links, and the steps themselves contain the calls to action
- [x] Update[ Figma mock-ups](https://www.figma.com/file/05k2PTmuDVgBj2HnzUZayg/Profile---Account-Security?type=design&node-id=124-1858&mode=design&t=gd7nAFF11W5ApFnE-0)
- [x] Move to validate so Travis can create the FE ticket for the work

## AC

- Mock-ups reflect latest content
- Ready for FE

**Comment by mtcA6** [comment]
added this work to #73358 if it turns out to be too much in one story we can change course and reopen this story

**Comment by mtcA6** [comment]
@andaleliz I've modified this ticket and reopened it based on the comment traffic [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2383). Based on the a11y folks we should probably reconsider the headings as a link pattern

**Comment by andaleliz** [comment]
I've mocked-up all the proposed content and am waiting for CAIA to let me know how to best get feedback from them. I can't attend office hours.

**Comment by andaleliz** [comment]
@mtcA6 this is ready for FE.  

@adamwhitlock1 I used the snazzy new DS annotation kit; hope it's helpful! Lmk if you have any questions. 

I captured the concerns I raised in huddle today in #79182
