### ISSUE TITLE
Analytics Internal - BigQuery Support Request

### ISSUE THREAD

**Issue by MasonOddball** [department-of-veterans-affairs/va.gov-team#74070]
### Description

We have gotten a request for some assistance running a query in BigQuery. This was from an analyst on the CXDW team, that does not need direct access to BigQuery, but has asked for our support running a query.

> "The purpose of this ticket is to get a copy of the BQ dataset that was used to make this Domo dataset: https://va-gov.domo.com/datasources/87b86c11-397b-4320-b632-d87896b5c4fd/details/data/table 
> 
> However, where the current query checks where the Event_Action for like '%Forms -%', I am looking for an identical dataset that where the Event_Action is like '%Post-911 Status%' 
> 
> So to put it plainly, create the exact same dataset, same refresh cadence, everything the same, except for the altered where clause on Event_Action. 
> 
> Once the query has been created, I would also request the data be loaded into Domo, following an identical process to the above dataset. 
> 
> Please feel free to reach out to me with any clarifying questions!"

### Tasks

- [x] BigQuery requirements have been confirmed with Mason.
- [x] Confirm cost impact, before running the query in BQ.
- [x] Results from query have been documented, and shared with Mason.
- [x] Data has been loaded into Domo.
- [x] Follow-up with Mason, and close request.

### Acceptance Criteria

- [x] BigQuery requirements have been confirmed with Mason, (over Slack, meeting, etc.)
- [x] Query in BigQuery has been updated, and confirmed.
- [x] Data has been filtered in Domo.
- [x] Requester (Mason), has been notified.

**Comment by dorseypa1** [comment]
@MasonOddball , I modified and ran the query in BQ sing the 911 pattern.  Please take a look at this out put and let me know if this matches what you expected.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/ec409f29-b011-4a7d-9dc0-aa6dca5c1a1f)

**Comment by MasonOddball** [comment]
Hey Philip, this looks good to me! I had originally had this: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141271557/b6fc773f-02c6-4948-9c66-120350e9cd76)
but my assumption is this was made with miss information. Assuming those are the correct categories/labels. We should be good to go!

**Comment by MasonOddball** [comment]
Hey Phil, could we add in the last 12 months on top of the current month? We have some graphs that require that historical data

**Comment by dorseypa1** [comment]
> Hey Phil, could we add in the last 12 months on top of the current month? We have some graphs that require that historical data

Yes, I'll add the previous 12 months to the queue and let you know when it is ready.

**Comment by MasonOddball** [comment]
Hey Philip, not sure if part of trying to pull the last 12 months work caused this, but I went in this morning to check how the data pulls were doing, and I noticed this error. I clicked manual run to see what might be happening, but then it did load: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141271557/acde8b8c-672f-4e02-b26c-5a69d591ed02)

**Comment by dorseypa1** [comment]
Data from 1/1/2023 to 1/31/2024 has been uploaded to the Domo dataset.  Please check it out.

Concerning the errors over the weekend it looks like a timing conflict with the BQ load from GA so I'll move the scheduled update of the Domo dataset

**Comment by johnny-jesensky-adhoc** [comment]
Great, glad we were able to help with this.  Moving this to _Done_.

FYI @MasonOddball, @dorseypa1
