### ISSUE TITLE
Research instances of list and loop built from checkboxes, inside and outside of VA

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#74075]
## Issue Description
As part of sorting out a technical solution, per the comment thread on [Toxic Exposure: Gulf War Hazard 1990#67013](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/67013#issuecomment-1890067324), we want to find examples where a list and loop pattern is made from checkboxes, inside and out of VA. This can help an upcoming discussion with the platform team about extending the component to support this use case.

per [Slack discussion](https://dsva.slack.com/archives/C04KW0B46N5/p1705694992578789?thread_ts=1705604432.595939&cid=C04KW0B46N5)

### Exact matches: using checkboxes and separate screens for each list and loop item

1.[Add or remove a dependent on your VA disability benefits](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/) (VA Form 21-686c) - [per Slack](https://dsva.slack.com/archives/C044AGZFG2W/p1705086672480899?thread_ts=1705083895.846869&cid=C044AGZFG2W). [Screen Recording](https://jmp.sh/0NP4yjFh)

### Potential matches

1. [Healthcare.gov - one thing per page example](https://blog.navapbc.com/structuring-a-complex-eligibility-form-for-healthcare-gov-37d79a5ad6#b6aa) - if "who is seeking coverage" populates subsequent pages about each individual. Also referenced in ["looping questions" section](https://blog.navapbc.com/structuring-a-complex-eligibility-form-for-healthcare-gov-37d79a5ad6#46b7)

### Near matches

1. Financial status report (form 5655), [per slack](https://dsva.slack.com/archives/C053UDWMH7U/p1705952274392939) - list and loop questions are on a single screen
2. The ["Add item" example on the pattern documentation](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---add-item) (from Decision Review) - there are multiple subsequent questions, across multiple screens, but they group all the selected checkbox values together. 
[Decision review screen recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--309ebab42f57bc7cea30786e56f5431ac7b26b2d/Decision%20review.mp4)
1. Selecting from rated disabilities on the 526EZ, [per slack](https://dsva.slack.com/archives/C053UDWMH7U/p1705962035773289?thread_ts=1705952274.392939&cid=C053UDWMH7U) - groups checked options together to build additional checkbox lists in subsequent questions but doesn't list and loop. 
[526EZ screen recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3840501fd5bf43b69c13e74aa0e347ca7e7cac32/526%20flow%20with%20multiple%20rated%20disabilities%20-%20cropped.mp4)
1. [4142 - single page list and loop - per Slack](https://dsva.slack.com/archives/C044AGZFG2W/p1705084472552139?thread_ts=1705083895.846869&cid=C044AGZFG2W)

## Other resources

1. [Slack thread in #veteran-facing-forms about RJSF approach to building list and loop](https://dsva.slack.com/archives/C044AGZFG2W/p1705510002553399?thread_ts=1705083895.846869&cid=C044AGZFG2W)
2. From [Steven Straily in Agile Six slack](https://agilesix.slack.com/archives/CLN31LCS0/p1706027520998949?thread_ts=1706024967.745899&cid=CLN31LCS0): "Right now, our team (IVC Forms Modernization) and the Veteran Facing Forms team have been discussing a version of this component they are building and the weaknesses in the current one as well, for our purposes. So it seems like with several parallel efforts going on to modify this, it may be worth looking into sharing some resources for a complete overhaul and elevating that through the proper channels to prevent a bunch of rework in the future." 
    3. Linked to the above DSVA [Slack thread in #veteran-facing-forms about RJSF approach to building list and loop](https://dsva.slack.com/archives/C044AGZFG2W/p1705510002553399?thread_ts=1705083895.846869&cid=C044AGZFG2W)

---
## Tasks
- [x] Ask in Slack across OCTO teams for other examples
- [x] Look at other pattern libraries for examples
- [x] Search public forums for examples

## Acceptance Criteria
- [x] Gathered list and sent to stakeholders: including at least Rakshinda, Christine, Kate, Emily, Shannon

**Comment by mengA6** [comment]
[Asked in #design](https://dsva.slack.com/archives/C0NGDDXME/p1705940075543229)

**Comment by mengA6** [comment]
search for "multi page form patterns" seems useful

**Comment by mengA6** [comment]
Survey builders like Surveymonkey? Piping?

**Comment by mengA6** [comment]
[History of Multiple Responses pattern documentation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/commits/main/src/_patterns/ask-users-for/multiple-responses.md)

**Comment by mengA6** [comment]
"conditional logic" on forms?

**Comment by mengA6** [comment]
[Announced takeaways in slack and tagged stakeholders](https://dsva.slack.com/archives/C053UDWMH7U/p1706043617531979)
