### ISSUE TITLE
Forms Library - Maintenance and Improvement Work to improve developer experience

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#7407]
### High Level User Story/ies
As a FE dev building on va.gov, I need access to comprehensive developer documentation that explains both what the forms library is and also the proper way to use it build great forms for va.gov.

As a FE dev building on va.gov, I need to see improvements to the forms library to address my current and urgent needs related to my project.

As a FE dev building on va.gov, I need clear communication channels and transparency into current/future forms work so that I may track work from the beginning of the feedback process all the way into development.

### Problem Statement 

The VA.gov forms library — one of the most common tools that VFS teams use to build on VA.gov — is not enabling VFS teams to seamlessly and iteratively build great forms. For many months, development on the existing forms library was stalled, and the documentation has become severely out of date. 

How might we identify and prioritize quick wins the will help to soften the pain for developers building forms on VA.gov?

### Hypothesis or Bet
If we expand upon and reorganize forms library developer documentation, then VFS developers building forms will not need as much manual support from VSP.
If we make the forms library easier for developers to use, then VFS developers building forms will have a more positive experience using the DEPO platform to build on VA.gov.

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.

### Success metrics 
- [VSP KR] Decrease in logged customer support requests related to Forms Library
- [VSP KR] Increase in positive feedback from teams on the value of the platform quarter over quarter
- Number of discovery/development progress updates delivered per month (goal = 4)

### We will know we're done when...
- [ ] Communication channels are established and a regular cadence for feedback/questions is established.
- [ ] [Communication protocol](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9069) is published to help promote transparency including:
  - [x] Tactical Updates: establish a slack channel #forms-library and update in Zenhub
  - [ ] Strategic Updates: VSP Newsletter
  - [ ] Customer Delivery: Notify users when requested development\documentation is completed
- [ ] Immediate documentation gaps are filled with new or refactored forms instructional documents

### Additional Details/Notes (optional)
- Future work tracked in #4599
- [VSA created forms documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/engineering/forms-system)
- [Wishlist (Backlog Candidates)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/wishlist.md)
- [Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/2020-03-forms-doc-feedback.md)
- [Getting Started with VA.gov Forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md)

### Artifacts
- [Forms Library Product Outline - Improve Developer Experience (Short Term)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/forms-library/improve-dev-exp-product-outline.md)

### Communication
- Team that owns this super epic: VSP FE Tools
- Teams contributing to this super epic: VSP Content & IA

**Comment by andreahewitt-odd** [comment]
From Trevor -- list of potential tickets: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/182
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/314
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/316
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/317
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/318 (might be a non-issue meow)
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/767 (might be a non issue meow)
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/1141
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/1145
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/4679
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/5875

**Comment by meganhkelley** [comment]
Reformatted super epic to fit new template for Q3 roadmapping (used existing info from old format)

**Comment by meganhkelley** [comment]
I removed the documentation tickets from this super epic and assigned them all to the sub-epic I just created #10925

Let me know if that's confusing for folks.

**Comment by meganhkelley** [comment]
@caw310 this is an old epic that may still have some relevant tickets in it — I'm reassigning to your team in case you want to take a look.

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
