### ISSUE TITLE
Update Docker image for Cypress in CI

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74078]
## Issue Description
The current cypress image in use for CI Cypress tests is `public.ecr.aws/cypress-io/cypress/browsers:node16.14.2-slim-chrome103-ff102`. We should check if there is a more current image and update it. Then we'll need to verify that our tests still run properly and can complete successfully in CI.

---
## Tasks
- [x] Search for the newest node/chrome/ff image that can run cypress tests.
- [x] Update the image reference in vets-website CI.
- [x] Test that our Cypress suite can still run successfully
- [x] If it can't, try other images to find one that can but is more up-to-date than our current one.

## Acceptance Criteria
- [x] Our main branch contains a stable, current cypress environment image in the CI workflow.

**Comment by pjhill** [comment]
Updated to the latest node16 available from cypress-io's public ECR -- https://github.com/department-of-veterans-affairs/vets-website/actions/runs/7588776789/job/20672023058
