### ISSUE TITLE
Work Platform Site Content Process into Support Process 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74072]
## Description 
We need to work this process into our content escalation process to Platform Content for edits to the Platform Site. Note: This is an ongoing conversation with Joe Knipes/Platform Content Team. Additional discussions required.

Here are the Confluence docs that explain the editing and creation processes:

- [Create a New Page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page)
- [Edit Existing Page](https://vfs.atlassian.net/wiki/spaces/AP/pages/2046558209/Edit+Platform+website+documentation)
- The Edit page links back to the Create page several times so both are worth having.

Communication Procedures:

- [Platform website support overview](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1640333324/Platform+website+support+overview)
- It says basically, contact us in Slack at #platform-content, or create a [GitHub ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=documentation-support&template=documentation-support-request.yml&title=Documentation+support).

All in one doc: Most of this info is in our Orientation take-away doc.
- [Platform content orientation takeaways](https://vfs.atlassian.net/wiki/spaces/AP/pages/2502852652/Platform+content+orientation+takeaways)

---

## Definition of Done
_What must be done to officially complete this task?_

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Add the content creation steps into our flow for support (i.e. answer yes/no to the helpful question and if no, we submit a ticket to their team)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Add to style guide.

**Comment by alyssagallion** [comment]
N/A. We update our own documentation and Platform Content reviews for any issues to deploy. Closing.
