### ISSUE TITLE
Refine phoneNumberParser to handle OGC data edge cases

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#74083]
## Issue Description
The phoneNumberParser method invalidates valid numbers which are awkwardly formatted (unnecessary spaces/dashes, dots used in place of hyphens, etc)

---
## Tasks
- [x] Improve regex validation of phoneNumberParser
- [x] Write unit tests that account for these various edge cases identified in OGC data

## Acceptance Criteria
- [x] All unit tests passing
