### ISSUE TITLE
[CST] Track claims that are phased back

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#74089]
## Background
We need to add logging to DataDog to check to make sure that the Lighthouse Benefits Claims API is handling cases where claims have phased back in the same way that EVSS does.

## Context
We have observed issues in the past with the way that LH returns the list of completed dates for previous phases when a claim has move back to a phase that has previously been completed (ie. a claim is in phase 6 but then it moves back to phase 3). The way that this presents is that if we have a claim that has moved from phase 6 to phase 3 for instance, the list of completed dates will still include the completion dates for phases 3, 4, and 5, even though the claim is technically back in phase 3. We would expect to only see completion dates for phases 1 and 2 at that point

## Tasks
- [ ] Add a log to DataDog whenever the `data.attributes.currentPhaseback` field is set to true
- [ ] Update DD existing logging to include above attribute

## Acceptance Criteria
- [ ] We are able to find cases where claims have moved backwards in the phased claims process
- [ ] We have a dashboard widget that shows number of claims that move backwards over time

**Comment by jerekshoe** [comment]
Closing this ticket in favor of: https://github.com/department-of-veterans-affairs/va.gov-team/issues/84632
