### ISSUE TITLE
[Design] Figma migration - Auth. Exp. library fixes

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#74091]
## Background
The Authenticated Experience Figma library needs additional updates, based on the new fixes that were done in the VADS library file that can carry over to our team library. As a designer, I want to ensure our library is as spec-accurate so we can ensure the team can create and use functional Figma mockups and prototypes.

---
## Tasks
- [x] Update card instances
- [x] Add more variable states for components
- [x] Remove any remaining "ghost" artifacts
- [x] Review Figma files for My VA, ensure nothing is now broken due to these updates
- [x] Review with Profile designers to make sure their files are not broken in any way after the updates
- [x] Addition of improved annotation components

## Acceptance Criteria
- [x] Figma Authenticated Experience library file will reflect these completed tasks

## Validation
- Validated by Pam and Liz

## Resources

**Comment by mattmarino-adhoc** [comment]
Card instances are going to remain as-is for the time being. We still need some assistance from the VADS team, and will circle back when they're ready with the cards.

**Comment by mattmarino-adhoc** [comment]
Made changes to annotation components as well. Given the OK by Liz on library current state not breaking anything.
