### ISSUE TITLE
Create regression test plan for VSA Authenticated Experience team's Profile 2.0 product

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#7410]
## User Story or Problem Statement
As a Profile 2.0 team member, I need a suite of regression tests so I can be assured that Profile 2.0 includes all previous functionality from the Profile and Account pages.

## Goal
A suite of regression test cases has been created in TestRail for use and reuse as development proceeds with Profile 2.0.

## Objectives or Key Results this is meant to further
Complete artifacts for collaboration cycle
---
## Tasks
- [x] Gather information for user stories / acceptance criteria around existing profile and account functionality
- [x] Create test cases based on user stories / AC
- [x] Organize test cases into a regression test plan
- [x] Deliver test plan to Profile 2.0 team

## Acceptance Criteria
- [x] Regression test plan created for Profile 2.0
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc

**Comment by pjhill** [comment]
Although the initial suite of regression tests has been created, I need to update some of the tests and create several new tests in light of information regarding additional core functionality migrating to the new Profile 2.0 product from the old profile and accounts pages.

**Comment by pjhill** [comment]
OBE
