### ISSUE TITLE
Create Final Wireframes and content for modality-agnostic error pages

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#74108]
## User Story
So that Veterans receive the same information regardless of what type of appointment they have, we want to switch to modality-agnostic error pages. Based on the findings in #72429 we have set a precedent for including both in-person and virtual visit information [in error messages](https://docs.google.com/document/d/1wFbf2Pn8_CBJ8EMEeJ99buGwWokYMN7eUODSG9tou1k/edit). 

## Tasks
- [ ] Create new or update existing content to be modality-agnostic
- [ ] Create final wireframes with new/existing content
- [ ] Create any needed markup into Sketch Page(s) and figma for heading annotations, aria label values or link paths

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [X] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [X] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [X] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Would that be the content on an [error page like this one](https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/K0R4yx1#Version)? Does that content speak to CVT and VVC? 

[Modalities list](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-in?type=design&node-id=248-317&mode=design&t=cdNhSBShYqlTpDP1-4) 

cc @cgednalske as she was interested in this work too

**Comment by benbrasso-agile6** [comment]
My overall gut instinct is to attempt to find content that doesn't separate out instructions for each modality. E.g., listing out instructions for 4 modalities on a page could get unruly. But, that's just my thought. For example, I'm curious if there's a one-size fits all solution. E.g., "If you're at the facility, do X. If you're at home, do Y."

**Comment by kellysmith1008** [comment]
That's what my proposal does - if you're in-person, do this. If not, do this. Because regardless of modality type, you're either in the clinic or not in the clinic. So it's either "call us" or "talk to a staff member" and, in the event of the telephone appointment, "wait for your provider to call you" - or are you reading the proposal a different way? Is there a suggestion you have to make it clearer?

**Comment by benbrasso-agile6** [comment]
It feels like video appts at home aren't being addressed? Or, maybe I'm just misreading it?

**Comment by benbrasso-agile6** [comment]
Maybe, do you want to toss it in Figma? I could be just misreading it, you know?

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I mocked up the ideas I had in figma - and I noticed in my first pasting of the content I didn't include the video content - I edited the comment to make that addition. 
[The mockups are in the figma file on the Modality agnostic page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=1262-4757&mode=design) hopefully this helps show what I'm thinking

**Comment by benbrasso-agile6** [comment]
Looking 👀

**Comment by benbrasso-agile6** [comment]
Going to drag this back to in progress, as I believe Zach still needs to complete the wireframes

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske (cc: @loripusey) 
Ready for validation: https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-in?type=design&node-id=437%3A3&mode=design&t=no6bNAw9XH8dycVn-1

**Comment by benbrasso-agile6** [comment]
👀

**Comment by zach-park** [comment]
Also updated in:
PCI > [In-person](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=819-9743&mode=design&t=AdE6YUQziCdX4bAD-4)
PCI > [Phone](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=745-8702&mode=design&t=AdE6YUQziCdX4bAD-4)

**Comment by benbrasso-agile6** [comment]
Links for engineers are in https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/74107#issuecomment-1949426548
