### ISSUE TITLE
Update selectable options in Platform Feedback workflow

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#74109]
## Purpose
We received a recent item in Platform Feedback that indicates we need to adjust our options for a more general "someone might need to know about this" type option.

## Tasks
- [x] Draft updated options
- New options that have been suggested based on latest feedback: 
-is a blocker and I cannot accomplish the needed action
-requires me to perform a workaround
-is functional, but results in a poor experience
-is something a team (or someone) should know about
-is a positive experience that I want to share
- [x] Evaluate and get SDT feedback
- [x] Update options in Workflow

## Acceptance Criteria
- [x] Updated options are available when Workflow is summoned
