### ISSUE TITLE
Spike: Is there validation for bank account/routing number?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#74117]
## Issue Description

As pension team,
we want to review what validation, if any, exists for the bank routing number field on the online Pension form,
so that we can determine whether we need to update to a design system component or propose a new solution.

---
## Tasks
- [ ] Investigate if our current bank routing number field has any validation
- [ ] If it does, what is it leveraging? Anything from the VA Design System?
- [ ] If it doesn't, does anything from the VA design system exist for this?
- [ ] Determine how if and how we can improve this component to ensure veterans are alerted of potential issues when providing their bank routing number.

**Comment by vbellissimo** [comment]
https://en.wikipedia.org/wiki/ABA_routing_transit_number#Check_digit

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/74117?planning-poker) with Zenhub @danlim715 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
@vbellissimo @buddhima-coforma FYI

**Comment by vbellissimo** [comment]
Thanks @scottsdevelopment 

@ToddWebDev The way we have the frontend set up for the "signature" field at the end of the form, is it already following the VA standards? https://design.va.gov/patterns/ask-users-for/signature. There is nothing else in the Design System that is more sophisticated than this, right?
