### ISSUE TITLE
[CST] Add DataDog logging to identify non-Veteran users

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#74138]
### Background
With our move to Lighthouse Benefits Claims as our main API provider for claims data, we have noticed that some users are now supported that would not have been supported in the past, specifically non-Veteran users. These users have presented unique issues that were not present before including issues with document uploads and submitting 5103 requests.

### Considerations
We want to be able to identify users who either:
* Don't have a birls_id
* Don't have a file_number
* or both

This should help us understand what percentage of our users are non-Veterans and aide in our decision making process around how we can best support our users

### Tasks
- [x] Log to DataDog if the `current_user` doesn't have a birls_id
- [x] Log to DataDog if the `current_user` doesn't have a file_number
- [x] Update specs to check that this is happening

### Acceptance Criteria
- [x] We are logging to DataDog when we identify users that either have: no birls_id, no file_number, or both
- [x] We are able to identify the percentage of users who are non-Veterans
