### ISSUE TITLE
Remove BRD files in the devops repo

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#74142]
Vets API BRD files are still present in the devops repo. These are no longer used and need to be deleted. There is already a comment at the top of each file referencing the new manifest files. Review Instances are deployed via BRD but have a seperate settings.local.yml file in the devops repo. Removing all Vets API BRD files will not affect Review Instances.

**Tasks**

- [x] Delete devops/ansible/deployment/config/vets-api/dev-settings.local.yml.j2
- [x] Delete devops/ansible/deployment/config/vets-api/staging-settings.local.yml.j2
- [x] Delete devops/ansible/deployment/config/vets-api/sandbox-settings.local.yml.j2
- [x] Delete devops/ansible/deployment/config/vets-api/prod-settings.local.yml.j2
- [x] Delete devops/.github/workflows/k8s-settings-prompt.yml

**Comment by jennb33** [comment]
Need to review what Staging instance needs to be kept.

**Comment by jennb33** [comment]
Investigate what we need for documentation and where it needs to be updated.

**Comment by LindseySaari** [comment]
I started the conversation with [the devops folks here](https://dsva.slack.com/archives/C04CYC4LMU6/p1707164296496529)

**Comment by LindseySaari** [comment]
I have initiated [a draft PR](https://github.com/department-of-veterans-affairs/devops/pull/13954) for the deletion of these files. If no concerns emerge, I plan to allow a day or so for discussion in the devops channel before proceeding with the merge.
