### ISSUE TITLE
Covid Dashboard - Build & maintain analytics dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#7414]
## High Level User Story
As a health lead on DEPO, I need to understand how Veterans are using VA.gov so that I can better serve veterans during the pandemic

## Hypothesis/(es)
**If** _we create and maintain a dashboard with appropriate Covid-19 related metrics from VA.gov_ **then** _we expect stakeholders to better serve veterans during this time of crisis_.

## Pain Points
- Customer: There's a pandemic and we can help support constituents with analytics

## Desired Outcomes
- Customers use qual and quant data to support VHA shift of veterans using telehealth instead of going into physical locations during the pandemic

## Goals
Create Covid-19 dashboard and keep it up to date with relevant metrics for DEPO stakeholders to use for effectively transitioning Veterans to telehealth during the state of emergency.

### Links
[Dashboard](https://va-gov.domo.com/page/1872052027)

### Product Outline
Covid-19 Dashboard Product Outline TBA

### VSP Objectives
`O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.`

### VSP Key Results
- Increase in VA.gov user satisfaction

## KPIs
- User sentiment
- Dashboard release dates vs. telehealth/physical facility usage
- Number of recurring users per day or week

**How we will track the KPIs** : Domo, user feedback

## Definition of Done
- [ ] DEPO has access to Dashboard
- [ ] Dashboard is iterated according to DEPO feedback
- [ ] Continued maintenance of the dashboard until the end of the state of emergency
