### ISSUE TITLE
Copy of [FE] - Call new profile endpoint when updating status

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#74168]
## User Story
As a patient, I want to confirm my contact info so that I can be up to date in the system.

## Description
With the new profile integration, we are going to call a new endpoint (built in vets-api) to set the updated date when a patient says yes to all questions. If they say no to any question, this endpoint will not be called.

In addition to this work, we also want to make the existing update api call to be conditional if appointment is at a Vista site. For Vista appointments, we will call both endpoints and for OH(Cerner) we will just call the new profile vets-api endpoint.

## Tasks
- [ ] [FE] Add logic to call new endpoint
- [ ] [FE] make calling current endpoint conditional for Vista only
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
