### ISSUE TITLE
[FE] - Check-in for OH(cerner) appointment

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#74171]
## User Story
As a patient, I want to check-in for my appointment at a OH(cerner) site so that the staff know I am at my appointment.

## Description
Endpoint implimentation is still TBD, but we will need to let vets-api know that the user is checking into a OH/Vista appointment. This might be a new api from vets-api to do the OH(cerner) check-in or it could just be a param on the existing endpoint. This ticket is to update our current check-in to conditionally check-in for OH(cerner) or Vista.

## Tasks
- [ ] [FE] Update check-in to accommodate OH(cerner)
     - Ideally, we would use the same endpoint
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
closing with new OH direction
