### ISSUE TITLE
Collaboration Cycle for [IVC Forms, FMP 10-7959f-1 FMP Registration]

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74178]
### VFS team name

IVC Forms

### Product name

10-7959f-1 Foreign Medical Program (FMP) Registration

### Feature name

new product

### GitHub label for team

ivc-forms

### GitHub label for product

10-7959f-1

### GitHub label for feature

10-7959f-1

### Public DSVA Slack channel for VFS team

ivc-forms

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

1/17/2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/10-7959f-1%20product%20outline.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C05UDS77ZPH/p1705955745698379)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [x] [User flow (required)](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-18&mode=design)
- [x] Whiteboard, Figma or other lo-fi prototypes or [wireframes](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-19&mode=design)
- [x] [Research plan on GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/research/users/research-plan.md) or [Google docs](https://docs.google.com/document/d/1BZea80XTNSf1eqU70ySwQEtitv-kS4WV1IcIjIZ_iC0/edit#heading=h.sb4y01ez3tvp)
- [x] Any other artifacts you have so far: [Content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/content-source-of-truth.md)

  
##### Platform actions
- [X] [Slack request thread](https://app.slack.com/client/T03FECE8V/C05UDS77ZPH)
- [X] Meeting date/time: 1/29/24 at 3:30pm ET
  
##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/Q8K7wEY_4PqS7MJ_eXmLJTSVEndG3ZogHs1AX4VELv_Cq8MHekg4poa_AZRf0sPX.FAkQQqfVh-djs69j)
  - Passcode: `@@VvD=9A`
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [x] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [x] Link to the Sitewide CAIA Intake Request [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74190)

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html): https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/494

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=21-159521&mode=design&t=ZcHBpL76j7eojAIB-0)
- [ ] Specify which pages are included in the review 
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/research/users/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/research/users/conversation-guide.md)
- [x] [Annotations](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=347%3A13852&mode=design&t=PxFE7NExgP1AHoPU-1)
 
**Content artifacts**
  
- [x] Sitewide CAIA feedback: Discovery [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705521134491/52690602ad9bb3ef8f9cbc82d48bd9698e63e83f?wid=28-1707348259687&sender=u5b5b283ad7d33e12ab259320) (with comments)
- [x] [content source of truth](https://docs.google.com/document/d/1vbWsc0h5t7KdmkjAnKFaxmC0RKOH8U6KOe4vRIuro-g/edit#heading=h.nlndqlvv5a6u)

**IA artifacts**

- [x] Sitewide CAIA feedback: [IA tracker](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/75464)
- [x] [intake form](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/74190)

##### Platform actions
- [ ] [Slack thread with VFS team](https://dsva.slack.com/archives/C05UDS77ZPH/p1708712408339909)
- [ ] Meeting date/time: Feb 29, 2024 at 3.30 PM ET

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [ ] Feedback ticket attached
  * [x] No feedback
* Design
  * [ ] Feedback ticket attached
  * [x] No feedback
* IA
  * [ ] Feedback ticket attached
  * [x] No feedback
* [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/U9t6fwO_kEMcyN6djmSrE654kZ14C1lCwr_s-oDIVC2z0tUg6geUwWYkCBzv1vXi.XEpSkmXsGojRpXiD)
  - Passcode: fV^fh94!
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below: https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/77616

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90047)

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL:
https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/
- [x] Specify which pages are included in the review: all         
- [x] [Staging test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) - **Note: please use user 5 or 7**
- [x] [Entry point - drupal preview page](http://preview-prod.vfs.va.gov/preview?nodeId=50826)

  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
- [intake form](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/74190)  
- [drupal preview page](http://preview-prod.vfs.va.gov/preview?nodeId=50826)
- screenshot of react widget/entry point (Note: we're currently just adjusting the link styles on the static page)
(side 1)
<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--920376879418b1263038c0186a3470ef6aa0e7c3/image.png" alt="image.png" />
(side 2)
<img width="779" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6fd5665b8d98bb6ba935d3ca6d13053bab12fab/image.png" alt="image.png" />

**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
- [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/foreign-medical-program-registration.md)
- [IA tracker](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/75464)

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/runs/overview/77)
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/runs/overview/77)
- [x] [Coverage for References](https://files.slack.com/files-tmb/T46Q2J7QV-F07F2CMDB37-557e36660c/screenshot_2024-08-01_at_2.57.17_pm_720.png)
- [x] [Summary(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/946)
- [x] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/ivc-champva/10-7959f-1/tests) (provide a link to the product’s code)
- [x] [Code coverage](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/) (provide a link to the product’s code)  
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89740). 
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05UDS77ZPH/p1722616240821369) / [Reschedule thread with VFS team](https://dsva.slack.com/archives/C05UDS77ZPH/p1724187868365509)
- [x] Meeting date/time: ~~Aug 22, 2024 at 1:30 PM ET~~ Rescheduled: Friday, August 30, 2024 at 2 p.m. Eastern

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/z_hE4o_RePcCbTKQIvbmmoJEO2Xi5Xvlr_XRLoS_r-twk2dQ-LNCnLYXaz_LUp9r.CkbxC06WcEtF45TK) 
  - Password: `@r8!L6VL`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1762

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by brian-wilke** [comment]
Design Intent Artifacts:
User Flow: https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-18&mode=design
Wireframes: https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-19&mode=design

**Comment by rachaelpenfil** [comment]
[Research plan])(https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/research/users/research-plan.md)
