### ISSUE TITLE
web components v3 migration: Alert (opt in)

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#74189]
## Tasks

- [ ]  Explicitly **_opt in_** to v3 for all uses of the Alert web component in 526. This involves adding the `uswds=true` prop for all uses of the component
- [ ]  Investigate cases of alert styling, but not using the alert component (e.g. on the Introduction page). Consider switching to the Alert component for consistent styling and maintainability
- [ ]  Update any tests as needed
- [ ]  Provide a list of all affected pages and screenshots which will be helpful for manual testing

Fyi
- looks like there are 12 uses of the web component throughout 526
- there are styling differences between v1 and v3, including border and background color changes
<img width="1695" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3p4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa34ce9478f21667a26a0f22654015350847c658/image.png" alt="image.png" />
