### ISSUE TITLE
[FSR] Update process list component to uswds v3

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#74184]
## Description

Updating process list on **Introduction** and **Confirmation** pages to use [USWDS V3 version](https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--default).

Scenario: Need to update out of date components ahead of USWDS web component migration.

Given: A veteran fills out the FSR 
When: View the Intro and the Confirmations pages
Then: They will see the most update version of the web component 

## Tasks
- [x] Convert old `formation` code to new code. 

## Acceptance criteria

- [x] Old formation code has been updated to use the new [Process List component](https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--default). 

## Testing
- [ ] N/A if non development work
- [x] View in browser and make sure it works locally

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
@Tom-Davis @HeatherRienks 

Made a small unplanned ticket since I'm on a lull right now with wizard work. 

cc: @Dr-Pongo
