### ISSUE TITLE
web components v3 migration: Additional Info (opt in)

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#74188]
## Tasks

- [ ]  Explicitly **_opt in_** to v3 for all uses of the Additional Info web component in 526. This involves adding the `uswds=true` prop for all uses of the component
- [ ]  Update any tests as needed
- [ ]  Provide a list of all affected pages and screenshots which will be helpful for manual testing

Fyi
- looks like there are 14 uses of the web component throughout 526
- there are no visual changes, but there are a11y improvements to add the `aria-expanded` attribute
