### ISSUE TITLE
web components v3 migration: Radio button (opt out)

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#74196]
## Overview
Web components will default to their v3 version starting 2/16/24

## Tasks

- [ ]  Explicitly **_opt out_** of v3 for all uses of the Radio button web component in 526. This involves adding the `uswds=false` prop for all uses of the component
- [ ]  Update any tests as needed
- [ ]  Provide a list of all affected pages and screenshots which will be helpful for manual regression testing

Fyi
- looks like there are 4 use of the web component throughout 526
- there are styling differences between v1 and v3, including label and spacing styling changes
- we are opting out of v3 for now, because there are 42 uses of the radio button widget and we wouldn't want both types of radio button styling in the same form
- for any new pages with radio buttons in the short term, we'll also need to remember to opt out to maintain ui/ux consistency

<img width="1848" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZ5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5dd28c623cad5541355aba16f883889d6485740a/image.png" alt="image.png" />
