### ISSUE TITLE
[CAIA Intake] Form 10-7959f-1 - Foreign Medical Program (FMP) Registration

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74190]
## About your team

- **Team name**: IVC Forms
- **OCTO product owner:** Premal Shah
- **Product manager:**  Mary Wang
- **Designer:** Brian Wilke
- **a11y specialist:** Rachael Penfil
- **Slack channel:** ivc-forms
 
## About your initiative
Our team will be digitizing the registration form for the Foreign Medical Program (10-7959f-1). We would like CAIA's support in reviewing updates to content and structure.

### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [x] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?
The IVC Forms team is currently digitizing forms under the CHAMPVA program as well as Foreign Medical Program (among others) in order to deliver healthcare benefits more quickly and efficiently to Veterans and their families.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [x] Yes
- [ ] No
- [ ] I’m not sure

### Where are you at in your timeline?
In discovery and research planning, preparing for design intent. (Design intent was held 1/29/24).

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [x] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** [74178](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/74178)

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/10-7959f-1%20product%20outline.md)
- [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705521134491/52690602ad9bb3ef8f9cbc82d48bd9698e63e83f?sender=u5b5b283ad7d33e12ab259320)
- [Content source of truth](https://docs.google.com/document/d/1vbWsc0h5t7KdmkjAnKFaxmC0RKOH8U6KOe4vRIuro-g/edit#heading=h.nlndqlvv5a6u)
- [wireframes](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-19&mode=design)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA operations
- [x] Initial Review - @coforma-terry and @strelichl
```

```[tasklist]
### CAIA a11y tasks
```

```[tasklist]
### CAIA content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75701
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88012
```

```[tasklist]
### CAIA IA tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75464
```

**Comment by marywang2** [comment]
@strelichl since design intent was held last week and we've addressed the feedback - could we proceed with CAIA review for form 10-7959f-1? This is a relatively straightforward form and we have 2 teams operating on parallel tracks so we would like to get CAIA's input without being blocked by 10-10d.

**Comment by marywang2** [comment]
Hi @strelichl that date feels very late to me - possible to schedule earlier, perhaps next week? It is a very simple form and there's not much copy. We can also come to office hours next week.

**Comment by kristinoletmuskat** [comment]
Hey hey! I started working on some of the IA thinking in [your existing discovery Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705521134491/52690602ad9bb3ef8f9cbc82d48bd9698e63e83f?wid=28-1707348259687). I need to sign off for the day, but just wanted to mention that it might be worth throwing some findability tasks into your user research plan is possible! I'll let ya'll know when I have a more fleshed-out draft to review of the IA recs too.

**Comment by kristinoletmuskat** [comment]
Actually the draft is done! Feel free to review and add comments in the mural linked above.

**Comment by brian-wilke** [comment]
Thanks @kristinoletmuskat!  I have placed a couple of purple notes inline on your page there as well. Looking forward to discussing this afternoon

**Comment by laurwill** [comment]
Hi @brian-wilke @marywang2 , 
Just documenting the decision about the intro page from our sync today: 
Since FMP registration form is not really an "application" in the same way as other benefit applications, and there's no info or supporting documents the Veteran needs to gather before starting, the process list from the application form template probably isn't needed here. Instead, we'll use the "non-application" template for this form into page.

**Comment by kristinoletmuskat** [comment]
Hey @marywang2 and @brian-wilke , wanted to pass along the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/foreign-medical-program-registration.md) for this page. Let me know if anything looks incorrect!

And flagging for @aliyahblackmore and @laurwill , just wanted to make sure we're aligned on the entry points / crosslinks! There are a couple of non-va.gov and R+S pages that have the link to just download the registration form. I think it would be ideal if we could edit those, and open to your thoughts.

**Comment by aliyahblackmore** [comment]
Hi @kristinoletmuskat - I'm actually not involved in this FMP work - so I don't need to be looped in here :) 

Can you remove my tag from your comment whenever you have a moment?

**Comment by marywang2** [comment]
@strelichl @laurwill for the react widget setup detailed in this [page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md#content-design-process-steps), do we need to submit a new CAIA ticket for that? Or can it be part of this ticket?

**Comment by laurwill** [comment]
Hey @marywang2 , 
I made a child ticket on this intake to track the react work : https://github.com/department-of-veterans-affairs/va.gov-team/issues/88012 We can continue the convo there!
