### ISSUE TITLE
web components v3 migration: Breadcrumb (opt in)

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#74193]
## Tasks

- [ ]  Explicitly **_opt in_** to v3 for all uses of the Breadcrumb web component in 526. This involves adding the `uswds=true` prop for all uses of the component
- [ ]  Update any tests as needed
- [ ]  Provide a list of all affected pages and screenshots which will be helpful for manual testing

Fyi
- looks like there is 1 (global) use of the web component throughout 526
- there are styling differences between v1 and v3, including making the bottom most level breadcrumb a link

<img width="1665" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFh5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8ed21de52f7cde9962f31d4b61932530bc3b5f1/image.png" alt="image.png" />

**Comment by christinec-fftc** [comment]
Linking related [platform support request](https://dsva.slack.com/archives/CBU0KDSB1/p1707255659737289) where i asked about some styling changes between v1 and v3
