### ISSUE TITLE
web components v3 migration: Checkbox group (opt out)

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#74195]
## Tasks

- [ ]  Explicitly **_opt out_** of v3 for all uses of the Checkbox web component in 526. This involves adding the `uswds=false` prop for all uses of the component
- [ ]  Update any tests as needed
- [ ]  Provide a list of all affected pages and screenshots which will be helpful for manual regression testing

Fyi
- looks like there is 1 use of the web component throughout 526
- there are styling differences between v1 and v3, including label and spacing styling changes
- we are opting out of v3 for now, because there are 35 uses of the checkbox widget and we wouldn't want both types of checkbox styling in the same form
- for any new pages with checkboxes in the short term (e.g. for Toxic Exposure pages), we'll also need to remember to opt out to maintain ui/ux consistency

<img width="1784" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUx5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45cf005a5e405811363d358f660762a418db8981/image.png" alt="image.png" />

**Comment by christinec-fftc** [comment]
I think we can actually close this one out as already done. There's currently only one use of the checkbox web component and it is already opted out.

**Comment by RakshindaAslam** [comment]
Closing opt out ticket as no action is needed. All the checkbox widgets will be converted later.
