### ISSUE TITLE
UX/FE/BE | Enhanced Military Info | Plan for how to grab data & format it ahead of research sessions

### ISSUE THREAD

**Issue by pamela-drouin** [department-of-veterans-affairs/va.gov-team#74209]
In order to do a mapping session with veterans who participate in the Enhanced Military Info research study, we'll need to acquire participants' military history ahead of time and format it in such a way that it can easily be used in Mural for a mapping exercise. UX, FE, and BE will need to work together to figure out the best way to do this.

### Tasks

- [x] Identify what we need to grab data ahead of time
- [x] Determine a workflow and timeline for getting that data in Mural for workshop purposes

### Acceptance criteria

- [x] We have a plan and a workflow that makes sense for getting data that can be manipulated in a live research session

**Comment by pamela-drouin** [comment]
I've dug through the three json files that @andaleliz and @tpharrison were able to collect. This is what I'd like to pull/grab from veteran records into a CSV, and then paste that CSV into Mural for a mapping exercise. I'm hoping to achieve one sticky per item, if that makes sense. (1 value for `effectiveDate` would be its own sticky). @tpharrison is this feasible?

@andaleliz how's this list look, based on the time you've spent with this data? Anything you would recommend removing or including?

- militaryOccupations
	- `serviceProvidedCode`
	-  `serviceSpecificOccupationCode`
	- `serviceSpecificOccupationText`
	- `effectiveDate`
- militaryServiceHistory
	- militaryServiceEpisodes (may have multiple episodes)
		- `branchOfServiceText`; `organizationText`; `periodOfServiceTypeText`; `periodOfServiceBeginDate`; `periodOfServiceEndDate`; `characterOfDischargeText`; `narrativeReasonForSeparationText`; `enlistedServiceYears`; `selectedReservesYears` 
		- deployments
			- `deploymentBeginDate`
			- `deploymentEndDate`
			- `deploymentLocations` (may have multiple locations)
				- `deploymentCountryText`; `deploymentCountryCode`; `deploymentLocationBodyOfWaterText`; `deploymentLocationBeginDate`; `deploymentLocationEndDate`
		- guardReserves

**Comment by tpharrison** [comment]
@pamela-drouin This is feasible.  We may need a bit of back-and-forth discussion around the first one, but shouldn't take much effort.

**Comment by pamela-drouin** [comment]
@mtcA6 carry over 1 point 😁

**Comment by mtcA6** [comment]
@pamela-drouin I don't generally expect things in validate to have carry over points, what is left? should this be moved to `in progress` instead?

**Comment by pamela-drouin** [comment]
@mtcA6 ah, okay, I see. I put it in validate for Tom to look at. He said it's doable, but what's left in my mind is just lightly documenting what the workflow should be. If it needs to go back into progress for that, that works for me!

**Comment by pamela-drouin** [comment]
@mtcA6 Let's carry this forward again, Tom and I have a pilot session tomorrow so we'll see how the workflow works!
