### ISSUE TITLE
COE | Audit Submission Volume

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#74204]
## Issue Description
_To confirm receipt of claims, we need to confirm that the downstream LGY system is receiving the expected volume of COE submissions that VA.gov is sending._

---
## Tasks
- [ ] Determine how many claims COE claims VA.gov sent downstream (all time)
- [ ] Work with LGY team to determine volume of received claims and what parameters are needed to audit
- [ ] Identify any discrepancies and determine mitigation steps

## Acceptance Criteria
- [ ] We understand if there are any discrepancies between VA.gov COE submissions and receipt of claims
- [ ] Follow on tickets to mitigate any issues are written
---

**Comment by steele-lm** [comment]
Completed as part of Code Yellow 3.
