### ISSUE TITLE
Migrate `fhir_client` gem to VA org

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#74218]
### Description
To update dependencies quicker (and bypass a few rules), we forked the `fhir_client` gem into the adhoc org. We need to move it the VA. We currently have a [private repo](https://github.com/department-of-veterans-affairs/fhir_client) for it, but to make it public and usable, we must complete some steps outlined in this [doc](https://department-of-veterans-affairs.github.io/github-handbook/public-repositories-at-the-va), as requested by the VA support team ([here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/19660))

### Tasks
- [ ] Complete the steps listed in this [doc](https://department-of-veterans-affairs.github.io/github-handbook/public-repositories-at-the-va) and get the repo changed to public
- [ ] Push code to new repo so it reflects a working state
- [ ] Update vets-api to point at the new gem

### Acceptance Criteria
- [ ] gem is in a public VA repo and vets-api prod uses it

**Comment by ryan-mcneil** [comment]
Update: Gem migration complete (repo [here](https://github.com/department-of-veterans-affairs/fhir_client) and [awaiting approval ](https://github.com/department-of-veterans-affairs/github-user-requests/issues/19660#issuecomment-1912868948)
