### ISSUE TITLE
Update React Widget copy

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74215]
## Background
We have new copy from CAIA which has been updated based on research findings -- we'll want to update the content in the React widget to reflect these changes.  The original widget was created in https://github.com/department-of-veterans-affairs/va.gov-team/issues/69866

[CAIA content document for the landing page
](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/_layouts/15/Doc.aspx?sourcedoc=%7B235D28BD-20DF-4DAC-964E-64469CF69E55%7D&file=1.%20ARM%20FAR%20landing%20page%20content.docx&action=default&mobileredirect=true)

[Display 1: Modern tool]
> Use our online tool to search for an accredited attorney, claims agent, or VSO.
> [Primary action link] Find an accredited representative

[Display 2: Legacy tools]

> You can find an accredited attorney, claims agent, or VSO in 1 of these 2 ways:
> - Go to eBenefits to find an accredited representative by name, state, territory, or zip code.
> [Link] [Go to eBenefits](https://www.ebenefits.va.gov/ebenefits/vso-search)
> - Search the VA Office of the General Counsel’s list to find an accredited representative by name, city, state, or zip code.
> [Link] [Search the VA Office of the General Counsel’s list
](https://www.va.gov/ogc/apps/accreditation/index.asp)

Screenshot of CAIA's content guidance for a quick visual:
<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--438b597ee0f9c1810807df113504eb19b268d142/image.png" alt="image.png" />

## Tasks
- [ ] Update React widget with new CAIA copy
- [ ] Confirm with CAIA that the react widget content is correct and displaying as expected (A Procik in Slack or aprocik1 in Github)
- [ ] Confirm react widget is connected to Find a Representative feature toggle (https://github.com/department-of-veterans-affairs/va.gov-team/issues/70842)

## Acceptance Criteria
- [ ] The existing react widget has been updated to reflect the latest CAIA-approved content 
- [ ] The react widget is connected to the Find a Representative feature toggle
- [ ] CAIA confirms the widget is rendering as expected on the landing page

**Comment by oddball-lindsay** [comment]
@cosu419 I want to check the current copy in the React widget to see if we actually need to make changes.  Are you able to access that easily?
