### ISSUE TITLE
Canary Launch for PCIU Contact Info Pre-fill

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#74216]
## Issue Description
We need to run an A/B test for 526ez contact information pre-fill, so as to determine whether or not VA Profile (without supplemental PCIU calls) is reliable/sufficient for pre-filling contact information in the 526ez application. This involves:
- identifying one (or a few) canary user(s)
- having them start a new 526ez application, and noting what contact information pre-fills in the app
- flipping the `disability_compensation_remove_pciu` flag ON for the user(s)
- having them start a new 526ez application, and verifying that the same contact information pre-fills in the app
- looking at the logs in DataDog as needed to confirm or troubleshoot discrepancies

---
## Tasks
- [x] Find veteran prod users https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md
- [x] Write up testing instructions in testrail, use for the run
- [x] Run Canary sessions using testing instructions (or use scheduled meeting)
- [x] Verify accuracy of metrics - we get activity, activity logs can be used to identify Canary users
- [x] Any updates needed are made to monitoring
- [x] Establish Comms: put message out in evss migration slack channel

## Acceptance Criteria
- [x] Successful calibration
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Scheduled 3 canary users 🐦🐦🐦 for tomorrow:

-  Scott Cutlip: 2/8/24 11:30am-11:45 PST
-  Lee Delarm: 2/8/24 12:30pm-12:45 PST
-  Rocio De Santiago: 2/8/24 1:00pm-1:15 PST

These have been updated in the [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20526ez%20Contact%20Info%20Pre-fill%20Migration%20Release%20Plan.md#canary).

**Comment by sethdarragile6** [comment]
Run the 3 canary sessions, all passed. Updated [release plan](https://vagov.ddog-gov.com/dashboard/qv6-xpd-7xg?query=%22disability_compensation_remove_pciu%3Dtrue%22%20%40http.referer%3Ahttps%5C%3A%5C%2F%5C%2F%2A.va.gov%5C%2Fdisability%5C%2Ffile-disability-claim-form-21-526ez%2A&event=AgAAAY2KkLShUo5a5wAAAAAAAAAYAAAAAEFZMktrTVVWQUFCcW5zOUNTZkFQandBMgAAACQAAAAAMDE4ZDhhOTEtMmEwZi00MjE0LTg1Y2UtMDg1ZWYzNjEzNDYw&index=%2A&panelFrom=1707426755000&panelTo=1707426760000&panelType=logs&refresh_mode=paused&view=spans&from_ts=1707426627323&to_ts=1707426927323&live=false) with details.
