### ISSUE TITLE
Migrate govdelivery_tms to VA Org

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#74219]
### Description
To update dependencies quicker (and bypass a few rules), we forked the `govdelivery_tms` gem into the adhoc org. We need to move it the VA. We need to create a VA repo, and to make it public and usable, we must complete some steps outlined in this [doc](https://department-of-veterans-affairs.github.io/github-handbook/public-repositories-at-the-va)

Similar to #74218

### Tasks
- [x] Create a repo for `govdelivery_tms`
- [x] Complete the steps listed in this [doc](https://department-of-veterans-affairs.github.io/github-handbook/public-repositories-at-the-va) and get the repo changed to public
- [x] Push code to new repo so it reflects a working state
- [ ] Update vets-api to point at the new gem

### Acceptance Criteria
- [ ] gem is in a public VA repo and vets-api prod uses it

**Comment by ryan-mcneil** [comment]
Update: Repo has been created ([here](https://github.com/department-of-veterans-affairs/govdelivery-tms)) and is now under review by the VA to be made public
