### ISSUE TITLE
Research: is user behavior associated with auth/unauth session status?

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74217]
## Background
Our team has been discussing how much we want to learn about the auth vs. unauth experience for Find a Rep, which does not require authentication.   We should be able to have session data through Google Analytics to get a rough idea of how many users of this product are authenticated, but we've also been discussing if we want to implement tracking of specific user actions to determine if user behavior differs between auth vs. unauth users.

This ticket is for researching if button clicks are associated with a particular auth/unauth session.  From there we could possibly peek into user behavior in a team-only GA dashboard (not the DOMO dashbaord we plan to share with OGC).  this is a stretch goal, and we will only pick this up if we have time after the other FAR 2.0 work.

## Tasks
- [ ] Investigate if we can associate user behavior (like button clicks) with a particular auth/unauth session
- [ ] Estimate level of effort if this is possible
- [ ] Discuss priority of implementation with the team

## Acceptance Criteria
- [ ] We will understand if we can associate user behavior with auth/unauth sessions
- [ ] If this is possible, define with the team if this work to pursue for 2.0 or a future iteration
