### ISSUE TITLE
[CST] [DDL] change header and subheader in DDL to account for appeals decision letters

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74223]
## Value Statement
**_As a_** veteran looking for the right claim letters and appeal decisions in DDL
**_I want to_** see language on the page that acknowledges I'm in the right place to retrieve my appeals decision letter and is consistent with language used by the Board
**_So that_** I don't get the wrong impression that I'm not in the right place to get those letters.

---
## Background Context
The Board of Appeals does not refer to "letters," but rather to "decisions".
The mock-up shows desired language changes for https://staging.va.gov/track-claims/your-claim-letters -- however for the list items, it's likely we can't achieve what the mock suggests. (Details in description below.)

### Intro
- Breadcrumb change to "Your VA claim letters and appeal decisions"
- URL change from `/your-claim-letters` to `/your-claim-letters-and-appeal-decisions`
- H1 changes to "Your VA claim letters and appeal decisions"
- The intro paragraph changes to "You can download your claim letters and appeal decisions. We also mail you these letters."

### Letter list
The mock suggests changing the letter list items heading and description to be specific to whether it's a decision or some other kind of letter. It's likely that we can't distinguish which letters are non-decision notifications and which are decisions. Even if we can distinguish Board decisions from other letters, we wouldn't want to imply that the rest are _not_ decisions. 
The mock needs to be updated after a discussion of what we can & can't distinguish among letters. Also, we should consider whether there's ever useful information offered in the paragraph above the download link such that it doesn't just repeat what's in the heading

<img width="954" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS91QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0aa68393f983bd8f1e2ec6a1b7f9d9f9ec3b4641/image%20%281%29.png" alt="image (1).png" />

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Acceptance Criteria
- [ ] _New language that reference appeals decisions added to the page in the header_
- [ ] _New language that reference appeals decisions added to the description under the header_
- [ ] _Language is behind the appeals decisions feature flag already in place_

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
labels: ["benefits-team-1", "benefits-management-tools"]

**Comment by jacobworrell** [comment]
This ticket doesn't include anything below the fold of the header and descriptor below the header.

**Comment by samcoforma** [comment]
@skylerschain I'd like to discuss this ticket with you during parking lot today if possible. Specifically, the part about differentiating the letter types.

**Comment by pmclaren19** [comment]
Moving to Product Backlog since @samcoforma is OOO this sprint
