### ISSUE TITLE
[CST] Status tab, "What we're doing" section header + current claim phase

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74247]
## Value Proposition

As a veteran trying to distinguish which actions are for them vs. a third party, I want the section for third party actions clearly delineated from actions I need to take and contextualized by the claim phase I'm currently in, so that I'm able to keep track of third party requests, but not mistake them for actions I need to take myself. 

## Design

[Figma link for section overall](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-593&mode=design&t=WJW1EPaD4lQk3ooF-4)

[Figma link for individual step card variations](https://www.figma.com/file/lbRZz68qGRGTdUigcoJq3a/Local-BMT-Components?type=design&node-id=100-657&mode=design&t=qPmgwTdX5fBc615V-4) (Use lorem ipsum text for now)

<img width="474" alt="Screenshot 2024-01-24 at 4 08 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/5ed8f373-fe7a-4273-b9dd-8917865bf2ba">

## Engineering Notes
- Overview tab[ link ](http://localhost:3001/track-claims/your-claims/009_ClaimWithTrackedItems/overview)
- Use claim status field from Lighthouse to pull in statuses to status component
- We need to ensure there is logic to map steps to claim phase

## Out of scope

- We're not doing this for EVSS
- We're not using revised statuses or status names, but the current status quo statuses.

## Tasks

- [x] During Validation @jacobworrell asked that we add description text and not use lorem ipsum text. Descriptions should follow what's noted in [this](https://www.va.gov/resources/what-your-claim-status-means/) link 
- [x] Design needs to update designs to account for all five claim phases.
- [x] Design needs to let us know what the text for the Complete phase is

## Acceptance Criteria

- [x] The header of the "What we're doing" section clearly distinguishes it from the section that has actions for the veteran.
- [x] The phase the claim is in is within this section and contains a short description of what the VA is doing in this phase
- [x] There is a link to the Overview section of the claim so the veteran can get a better understanding of the whole claim process if they want to
- [x] Behind the cst_use_claim_details_v2

**Comment by skylerschain** [comment]
Updated the Design section with better links

**Comment by HeatherWidmont** [comment]
@jacobworrell to validate

**Comment by jacobworrell** [comment]
@pmclaren19 for each claim phase, let's add the description language from this page: https://www.va.gov/resources/what-your-claim-status-means/

The exception being "Complete". @skylerschain will provide a minor tweak for that one. 

Please and thanks you!

**Comment by pmclaren19** [comment]
@jacobworrell @skylerschain okay so this language? We should update the ticket as well I can do that. 
![Screenshot 2024-02-13 at 8 56 40 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/6c28e3c3-426c-4537-b978-356e9e289a29)

@skylerschain can you please provide me with the complete text that you want?

**Comment by pmclaren19** [comment]
@jacobworrell this can be validated in Staging now.

**Comment by jacobworrell** [comment]
Validated!
