### ISSUE TITLE
content edits for #72786

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#74245]
## Issue Description
Edit [Creating a new React widget](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget) based off guidance described here: [footer ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72786).

---
## Tasks
- [x] Complete discovery from [ticket 72795](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/72795)
- [x] Complete changes to the [Creating a new React widget](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget) page as described on [this footer ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72786).

## Acceptance Criteria
- [x] Creating a New React Widget page has been updated and deployed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Work completed, closing ticket
