### ISSUE TITLE
Implement design changes to rep result cards

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#74244]
## Issue Description

Mobile view:
<img width="366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVh5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--998b04a047c1bfe995191a74625e48100d92bab6/image.png" alt="image.png" />
<img width="282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXJ5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--294a5b5265dbec3199a3a74116adcc3439829a58/image.png" alt="image.png" />

Desktop:
<img width="834" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJ5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3f00a3abcd33a2286a6a99e653bfebe73ecf13c/image.png" alt="image.png" />

<img width="763" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWp5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a117d17df83ac4b8e9c1b2d22b50fe39d0f116b/image.png" alt="image.png" />

---
## Tasks
- [ ] Add icons to linkouts
- [ ] ~Add gray background to result container div~
- [ ] Add additional-info ("See Associated Organizations") component to display when applicable 
- [ ] Reposition "Report Outdated Information" button
- [ ] Add "Visit Website" to display when applicable

## Acceptance Criteria
- [ ] Design changes are reflected in staging

**Comment by cosu419** [comment]
There's an issue with the <va-icon> component - [Slack discussion](https://dsva.slack.com/archives/C01DBGX4P45/p1706034855424189). It's not showing up for me either. Looks like it's being actively worked on.
