### ISSUE TITLE
Bump fitbit_api to 1.0.0

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#74262]
### Description
Bump to 1.0.0 now that `oauth2` isn't being blocked by `fhir_client`

### Tasks
- [x] Bump fitbit_api to 1.0.0
- [x] Merge to master

### Acceptance Criteria
- [x] fitbit_api is 1.0.0 in Gemfile.lock
- [x] Deployed successfully
