### ISSUE TITLE
Shadowing Research Prioritization Meeting

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#74276]
After meeting with Team 1 to conduct refinement of the Shadowing Research Prioritization Activity update the board with the following requirements.

**Task**
- [x] Setup a meeting time with Team 1 and 2 to discuss refinement (Nichole/Rakshinda/Julie)
- [x] Update activity board with changes/suggestions (Nichole)
- [x] Schedule a time for the 1st internal prioritization meeting (Nichole)
- [x] Schedule 2nd prioritization meeting with Shannon and Emily 
- [x] Use second meeting to prioritization effort and BO value with Shannon & Emily

**Acceptance Criteria**
- [x] Activity board is updated with feedback and suggestions
- [x] 1st internal prioritization meeting is scheduled
- [x] 2nd external prioritization meeting scheduled with Emily & Shannon

Activity board link: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703092286405/34f0b24b01e41338f7ba4ddfe0b9505128af7d60?sender=uffa03f837f92a7ba90498999

**Comment by nnicholas7** [comment]
Update: Held 1st prioritization meeting with DBEx team (research, design and product) to be able to add user value to each other the findings.  The next prioritization meeting with Emily and Shannon is scheduled for Thursday to talk about effort and BO value.
