### ISSUE TITLE
[Design] Create remaining components for MHV UA Library for production file

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#74282]
## Tasks
- [ ] Audit production file to see what components makes sense to create
- [ ] Create remaining components (but don't need to apply them to frames yet)
- [ ] Create and publish MHV UA Component Library

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by ytsaoca** [comment]
Components are ready for review https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=356%3A1039&mode=design&t=YUM75NrpfpYvailr-1

@benbrasso-agile6 @zach-park @cgednalske @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@cgednalske you mind helping here? I'll take a quick look as well.

**Comment by benbrasso-agile6** [comment]
LGTM

Just change the buttons to big buttons. And, good to close. We can validate the accordion tomorrow.
