### ISSUE TITLE
Update DST DraftingTemplate

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#74286]
## User Story
As a member of the Design System team, I want to easily identify what type of issue was identified in Staging Review so that I can assign the fix to the correct person.

As a member of the Design System team, I want to know what the next steps are for me after Governance has identified an issue or a consider item so that I can address the appropriate issues.

Assignee: @shiragoodman @rferguson13 
Peer Reviewer: @erinrwhite 

## Description
After the January 19 SR with Design System team, the team noted some issues that should be addressed via this [Slack thread. ](https://dsva.slack.com/archives/GNF5GSD9N/p1705691672526929) The DST specific DraftingTemplate needs to be updated to give better direction to the VFS team.

In addition, Governance and DST PO @humancompanion-usds has shared that it would be really helpful for the DS team if Governance team's SR tickets specified where the issues was found - whether in the component itself (`code`) or in the guidance supporting the component (`guidance`).

## Impacted Artifacts
DST DraftingTemplate

## Tasks
- [ ] Add a new descriptive tag category to the DST DraftingTemplate for 'Location' with the drop down options being ~~'Storybook', 'Figma', or 'Design System'~~ `code` or `guidance`

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members are able to specify in the DST DraftingTemplate where they located the identified issue
- [ ] Design System Team members are able to easily assign the ticket to the correct person on the team

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@erinrwhite @rferguson13 FYI I have changed this ticket slightly. Instead of specifying the tool, I think `code` or `guidance` would be better options. If we find inconsistencies in the guidance, they may be visible across tools (such as in Figma and on design.va.gov), so I think limiting to one or the other will help us better classify the problems. LMK if you disagree or want to discuss further.

**Comment by rferguson13** [comment]
@shiragoodman Sounds good. If you want to update the Drafting Template, I'll work on documentation using those parameters

**Comment by shiragoodman** [comment]
@rferguson13 ok i've updated the DST DraftingTemplate and made the following changes:

- Added a new descriptive tag called Location. This will be required for non-Consider items. The options in the drop down are `code` or `guidance`
- If/when code/guidance is selected, it will appear in the DraftingTemplate in the **Findings details** section. like this:
<img width="497" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/7e24f6d8-34d0-403c-89e7-e8704a7b0d3c">

- If/when `code` of `guidance` is selected for non-consider items, the appropriate label will be added
- If a Governance team member selects `code` or `guidance` for a Consider item, no label will be added and the **Findings details** section will not specify where the issue was found
- I removed Design System Component as a Descriptive tag within the template. This is bc we add the component label at the top under the SR information. I didn't want it to be confusing for us of DST.
   - With that, the Design System component field is no longer included in **References** within the ticket. See below  
<img width="185" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/25716927-58ef-4b97-903e-4e4ff015161b">

- The **Next Steps** section at the bottom of the ticket has been updated for DST and is awaiting Matt's feedback per this [Slack post](https://dsva.slack.com/archives/GNF5GSD9N/p1707160818439389)

I made these changes to the live [DraftingTemplate 2.0- DST](https://docs.google.com/spreadsheets/d/1hMcbGxX95gxwEtqxDpJgdDzjeGXSRQxh6iiq9enYp44/edit#gid=727681601). Please feel free to take a look, generate some sample tickets and let me know if you have any questions, comments or recommendations.

cc @erinrwhite

**Comment by shiragoodman** [comment]
@rferguson13 per our conversations yesterday, Matt has approved the proposed "Next Steps for DST" within the DraftingTemplate. However, in that discussion with Matt, he requested that we upload our DST SR issue tickets to the vets-design-system-documentation repo, and no longer the va.gov-team repo. I have created ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/75511. I have also made 1 small change to the next steps section so it now says the following:

Next Steps for DST
- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Governance help validating the issue, please comment on the ticket
-  If this ticket has a `high-priority` label, please address as soon as possible so VFS teams are not impacted
-  If this ticket has a `consider` label, please consider for future implementation

**Comment by rferguson13** [comment]
Hi @shiragoodman - I updated the [Design System Drafting Template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2915926188/Design+System+Drafting+Template) page to match the change you made. 

Quick question: should we have the reviewers specifically call out if their issue a "code" or "guidance" issue during the actual meeting? For example, "This is a guidance issue. The issue is..." Or do we think that having it in the ticket and presenting is enough context?

**Comment by shiragoodman** [comment]
Thanks, @rferguson13 . Good question. I think the the context of the issue is likely enough. If we find moving forward that they continue to ask if it's code or guidance, then we can change it.

**Comment by rferguson13** [comment]
@shiragoodman - Are we ready to pass this along to @erinrwhite?

[Design System Drafting Template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2915926188/Design+System+Drafting+Template)

**Comment by shiragoodman** [comment]
yup! @erinrwhite ready for your review

**Comment by erinrwhite** [comment]
This is looking good to go, as are the updates to the drafting template itself! @rferguson13 @shiragoodman 

Noting that we will need to update our documentation somewhere to describe how we add descriptive tags and adjust experience standards text. Maybe the [VA.gov Experience standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) page on platform products and services.

**Comment by erinrwhite** [comment]
@shiragoodman Yes of course! This is not specific to the DST drafting template - it's more of a process note for us with the new standards. 

We know that we will be adding/updating descriptive tags (and probably experience standards too) in the future as we add new things to the Design System, update links, etc. We should probably document how to make those updates: which files need to be updated (Drafting Template, DST drafting template, any others?), etc. Make sense?

**Comment by erinrwhite** [comment]
Aaaand looks like we have a related ticket on this from years ago: #32362

**Comment by shiragoodman** [comment]
@erinrwhite thanks for flagging that. IIRC, we did actually start work on the ticket you linked, but put a pause on it per request of our PO. 

Would you like to take a stab at updating the ticket? I don't think it needs to be too complicated.. in fact, I'd prefer if we had something simple to follow. Guidance for ourselves on how we update and maintain our product.

Let me know what you think. We can chat 1:1 if you'd like.

**Comment by rferguson13** [comment]
@shiragoodman - Did a test and everything seems to be working well!

**Comment by shiragoodman** [comment]
awesome! glad to hear it. I think this is good to close. @erinrwhite you approve?

**Comment by erinrwhite** [comment]
@shiragoodman Absolutely. @rferguson13 I'll work on the GH ticket documentation page now - can you handle updating the page on platform website?

**Comment by shiragoodman** [comment]
sweet!

**Comment by erinrwhite** [comment]
> @erinrwhite thanks for flagging that. IIRC, we did actually start work on the ticket you linked, but put a pause on it per request of our PO.
> 
> Would you like to take a stab at creating a new ticket? I don't think it needs to be too complicated.. in fact, I'd prefer if we had something simple to follow. Guidance for ourselves on how we update and maintain our product.

@shiragoodman I started a draft ticket for this #76106 that needs some refinement 😬
