### ISSUE TITLE
Remove Backup Support Bot from Drop Down Options

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74296]
## Description 
When VFS Teams submit a ticket they sometimes choose the incorrect drop down (Support Bot Backup vs. /Support command). As a result, it does not create a GitHub ticket and doesn't track in DOMO/Looker analytics dashboards. 

We have confirmed there is no purpose to the backup bot in current processes. As a result, we want to remove that option entirely to avoid confusion and improve analytics/GitHub ticket creation.

---

## Definition of Done
All tasks are done below.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Work with Curt Bonade to remove the slack bot backup option (alternative could be Kerry Powell if not available)
- [ ] Identify other steps that need to be taken if any based on the above conversation with Curt/Kerry
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
See attachments for context.<img width="722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnJ3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28647147924fd40c59313ac6ff5184f3bcb91780/image%20%2815%29.png" alt="image (15).png" />

--- 
<img width="960" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZ3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56dae158766cc50cb6e9539ebe88b3574fb4d43e/Screenshot%202024-01-23%20at%201.23.57%20PM.png" alt="Screenshot 2024-01-23 at 1.23.57 PM.png" />

**Comment by alyssagallion** [comment]
Erika helping us identify who can help us with this.

**Comment by alyssagallion** [comment]
Removed. Closing.
