### ISSUE TITLE
[CST] Fine-tune DataDog monitors

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#74309]
## Value Proposition

As a developer, I want to fine-tune the DataDog monitors created in https://github.com/department-of-veterans-affairs/va.gov-team/issues/74308, so that I don't miss important information about the CST app or waste my time looking into noise.

## Background

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/74308, we created a series of monitors for the CST app. The goal of this ticket is to babysit and refine these monitors for a couple of sprints.

## Tasks
- [ ] Pay attention to alerts from these monitors in Slack.
- [ ] Look into each alert and carefully determine whether it was a false positive or false negative, and refine the monitors accordingly, in reasonably small increments.

## Acceptance Criteria
- [ ] The team identifies signals that are being separated from noise efficiently.
- [ ] Team has identified opportunities to reduce noise and those opportunities get ticketed.

## Definition of Ready
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74308 done.

## Definition of Done
- [ ] Acceptance criteria met.
- [ ] We have a process in place for continuing to pay attention to logging and monitoring
- [ ] We have a document that tracks number of false positives, and incidents that have occurred without an associated monitoring alert (false negatives). This covers the timespan that this ticket has been in progress (two weeks/one sprint). This timespan will increase if we haven't achieved a "0" for both false positives and negatives by the end of the initial timespan. What is the evaluation period for determining this? cc: @data-doge
