### ISSUE TITLE
Find a Rep search fields: update location and name copy, add radius

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74301]
## Background
Some updates to the search parameters include:We are adding in a search parameter for our Find a Rep search results, so users can set a search radius that best fits their needs.

Screenshots of the mobile design are below, you can also check out the [prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=120-67785&t=ZpiOj63pF6hMRnb2-0&scaling=min-zoom&page-id=0%3A19109&starting-point-node-id=456%3A169444&show-proto-sidebar=1).

<img width="303" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWNTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bc4ca339d9cbd4d5b729a045bb02c6def635110/image.png" alt="image.png" />

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b32858a2c55361d098db8192d969f2b0d3a1de1/image.png" alt="image.png" />

## Tasks
- [ ] Update copy of the location search box to `Address, city, state, or postal code (*Required)`
- [ ] Add in a new `Search area` parameter with options that match the detail in the screenshot above
- [ ] Update name field copy to `Name of accredited representative`

## Acceptance Criteria
- [ ] The search parameters in Staging match the prototype
