### ISSUE TITLE
IPP - Discovery: VA Notify Integration

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#74319]
**Problem:**

As part of the final step in the IPP Veteran Intake process, we send a confirmation email to Veterans letting them know the details of the appointment they made, their case number, what to bring to the appointment, etc. We need to implement a way to send this email to Veterans when they complete the intake process for the pilot so we can test the email as part of the IPP service.

How might we integrate with VA Notify to send the confirmation email? How might we ensure the case number and Veteran email address are populated? How might we determine the trigger to send the email? 

**Acceptance Criteria**

VA Notify Research is complete when we know
- how to integrate with VA Notify
- how to populate the case number
- how to trigger emails to send to the correct Veteran email address
- the feasibility of implementing
- the timeframe to implement

**Tasks**
- [ ] Identify initial POC for VA Notify
- [ ] Schedule meeting to talk through IPP pilot goals 
- [ ] Identify requirements needing satisfaction to enable VA Notify integration

**Comment by SophiaPhilipMO** [comment]
Updated @lmorris3 and @rdvyas to include action item for this sprint, identify POC and schedule meeting with VA notify

**Comment by SophiaPhilipMO** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md

**Comment by rdvyas** [comment]
Found the following resources for VA Notify integration:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md

Steps to complete the VA Notify integration:
Submit the intake form *
Kick-off with VA Notify **
Have your technical team review the VA Notify API docs *
Get access to the Self Service Portal **
Budget approval for notifications *
Create your notification content (Privacy Officer review required) *
VA Notify submits a communication preference intake for your team (if applicable)
Please note, if you have a new communication preference your team will need to determine a plan to communicate this to veterans so they know a new notification is available to opt into.
SMS only: VA Notify requests applicable phone number(s)
Build your notification code to call the VA Notify API *
Test your notification *
Launch your notification **
Evaluate business outcomes and make revisions as needed *

Closing discovery ticket and moving to items noted.

**Comment by mateoclarke** [comment]
Should we open some new tickets for the tasks that come out of discovery? cc/ @lmorris3 @rdvyas
