### ISSUE TITLE
Send GovDelivery email about newest style guide updates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#7431]
## User Story or Problem Statement
As someone who works on VA.gov, I need to know when the style guide is updated so I can make sure content adheres to the in-house style.

Pull request: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/181

## Goal
- An email sent through GovDelivery highlighting the most recent updates to the style guide. 
-  A new entry added to "What's New" in the style guide

## Objectives or Key Results this is meant to further
- Maintaining the VA.gov style guide as the single source of truth
---
## Tasks
- [x] Add a new "What's New" entry to include most recent updates (addresses, form labels, change to Board of Veterans' Appeals)
- [x] Send a GovDelivery email highlighting these changes. Also include a helpful Plain Language rule or tip, or something we notice often needs to be corrected. Some possibilities are contractions or not using "the" in front of VA. Open to other suggestions. 
## Acceptance Criteria
- [x] What's New section updated on live site
- [x] GovDelivery email sent to distribution list

**Comment by MickinSahni** [comment]
Ready to be picked up once we have bandwidth.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I did a PR to add to the What's New section in the style guide. While looking at the style guide I noticed our address changes came out looking weird on the live site so I made changes to that as well.
![Screen Shot 2020-04-02 at 3.08.37 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/fb4a0a5d-dd94-4605-b6a5-94f0c47ea98f)

Here's the pull request: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/181

I am also going to set up the GovDelivery email as part of this ticket.

**Comment by jenniferlee-dsva** [comment]
^ @RLHecht - Can you remove the html tags from showing in the examples? The `<div> `tags.

**Comment by RLHecht** [comment]
@jenniferlee-dsva These address block examples should be fixed now once we merge the PR.

**Comment by RLHecht** [comment]
This work is now complete. Style guide is updated and Govdelivery email was sent 4/20/20. Closing ticket.
