### ISSUE TITLE
Appoint a Rep (Unauth) User Test - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#74311]
## Issue Description
Dependent (spouse, child, caregiver, etc.) user test of the 21-22/21-22a unauthenticated user flow.

## Tasks
- [x] Request research review
- [x] Update user test to reflect collab cycle edits
- [x] Set-up Enjoy HQ project
- [x] Kick-off with Perigean
- [x] Create sign-up sheet
- [x] Transfer demographics to sign-up sheet & Excel
- [x] Create folders & update guideline documents
- [ ] Create notetaker template
- [x] Set up Slack channel w/ notetakers & observers
- [x] Kick-off with notetakers
- [x] Conduct pilot session
- [x] Kick-off with observers
- [x] Create debrief Mural
- [x] Create conduct interview Zenhub ticket

## Acceptance Criteria
- [ ] All materials ready for collab cycle research review

**Comment by oddball-lindsay** [comment]
@mtri heads up that if we need to make any edits to the prototype, deadline is EOD 2/12 (but ideally EOD 2/8).

**Comment by oddball-lindsay** [comment]
Kicking off w Perigean later today

**Comment by oddball-lindsay** [comment]
8 scheduled interviews, all VSOs, mostly desktop users.  Checking to see if attorneys/claims agents can support non-Veteran claimants

**Comment by jfinnerty13** [comment]
Set up materials today
* [Sign-up Sheet](https://dsva.slack.com/canvas/C06GT765X08)
* Research Materials
    * [Interview Videos](https://dvagov.sharepoint.com/:f:/s/vaabdvro/Er5RAHXeykVNqOzESPLddAgBfxsF0faoiwGBJs8Jzvj_YQ?e=yZd5sz) [Requires Sharepoint Access]
    * [GitHub Research Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-02-appointarep-unauth-usertest)
    * [EnjoyHQ Research Project](https://app.enjoyhq.com/sh/pj/d4c16ccd-d0d6-4498-9e83-269ae71df8e8)
    * [Debrief Mural Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707166205826/199fa6e778222f0d5b44d712082982b702fa2e45?sender=u36b374887f74c9a3de2d0750)
* Notetakers
    * [Note and Transcript Folder](https://dvagov.sharepoint.com/:f:/s/vaabdvro/EmBST48lrvFNu4lhYtkivyABq940ItmxoGpiC5ZWeABflA?e=QaaEbe) [Requires Sharepoint Access]
    * [Janelle Notetaker Guidelines](https://docs.google.com/document/d/1cnWj4zUaLjdpP1hAqJtyy4uxqZblC6GR27xprrhDlOo/edit?usp=sharing)
* Observers
    * [Janelle Observer Guidelines](https://docs.google.com/document/d/1TM9ZnGptQ3CMw9XIwzc7wR6hiGA49CRbAE6gYAmcWwk/edit?usp=sharing)

**Comment by jfinnerty13** [comment]
Set up materials today
* [Sign-up Sheet](https://dsva.slack.com/canvas/C06GT765X08)
* Research Materials
    * [Interview Videos](https://dvagov.sharepoint.com/:f:/s/vaabdvro/Er5RAHXeykVNqOzESPLddAgBfxsF0faoiwGBJs8Jzvj_YQ?e=yZd5sz) [Requires Sharepoint Access]
    * [GitHub Research Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-02-appointarep-unauth-usertest)
    * [EnjoyHQ Research Project](https://app.enjoyhq.com/sh/pj/d4c16ccd-d0d6-4498-9e83-269ae71df8e8)
    * [Debrief Mural Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707166205826/199fa6e778222f0d5b44d712082982b702fa2e45?sender=u36b374887f74c9a3de2d0750)
* Notetakers
    * [Note and Transcript Folder](https://dvagov.sharepoint.com/:f:/s/vaabdvro/EmBST48lrvFNu4lhYtkivyABq940ItmxoGpiC5ZWeABflA?e=QaaEbe) [Requires Sharepoint Access]
    * [Janelle Notetaker Guidelines](https://docs.google.com/document/d/1cnWj4zUaLjdpP1hAqJtyy4uxqZblC6GR27xprrhDlOo/edit?usp=sharing)
* Observers
    * [Janelle Observer Guidelines](https://docs.google.com/document/d/1TM9ZnGptQ3CMw9XIwzc7wR6hiGA49CRbAE6gYAmcWwk/edit?usp=sharing)
