### ISSUE TITLE
Analyze recent Medallia feedback on MHV landing page (S24)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#74331]
### User story

As a Cartographers team member, I want to analyze recent qualitative survey responses, so that we can learn from them.

### Notes

- How to request medallia feedback:
  - Go to the [issue template list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose) and select "Qualitative data request"
  - Fill out the form. Here's [an example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68830) 
- Where to store analysis:
  - Spreadsheet in the team Sharepoint
  - Findings in Github alongside [earlier analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/Medallia-feedback-analysis.md) 
- TIMING NOTE: we launched the LOA1 alert on Jan 23, hoping to see fewer comments about MHV users being told they don't have access to MHV (the not-registered alert)

## Acceptance criteria

- Saved lightweight analysis of both quant and qual survey responses in Github
- Documented any insights in this ticket or new ticket(s) if appropriate

## Tasks

- [x] Request Medallia data for timeframe since previous analysis (see github)
- [x] Add new data to spreadsheet in the team sharepoint as a new tab
- [x] Scale GH page IA to account for multiple rounds of Medallia data 
- [x] Add in data analysis for new timeframe to GH page

**Comment by keithcheung828** [comment]
GH page based on Medallia data is created ([See GH page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/My%20HealtheVet%20Medallia%20feedback.md))

**Comment by sterkenburgsara** [comment]
@keithcheung828 - it looks like you added this analysis to a new file instead of adding a column to the tables in the [existing medallia analysis doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/Medallia-feedback-analysis.md). Could you please combine your results with the running document we already had?

**Comment by keithcheung828** [comment]
@sterkenburgsara the data has been combined with the [existing medallia analysis doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/Medallia-feedback-analysis.md) Thanks!
