### ISSUE TITLE
Include disclaimer banner around data accuracy

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74338]
## Background
To solve for the potential inaccurate rep data in our product, we have decided to include a banner with a disclaimer.  This banner should not appear if there are no search results.  That empty state will be handled over here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/74342

Updated banner copy from CAIA:
> **We're updating our search tool**
> Our search tool may show outdated contact information for some accredited representatives. You can report outdated information in your search results.

This banner should be placed right below the "Your search results" header, above the search parameter summary.
<img width="248" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9TQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--665d943604b30c9d9a2d53662bf64256b679373c/image.png" alt="image.png" />

## Tasks
- [ ] Introduce a banner that displays conditionally at the top of search results, if there are search results.
- [ ] Include copy above

## Acceptance Criteria
- [ ] When users are viewing the search results, they will be able to understand that not all data may be accurate and that they can report on inaccuracies.
