### ISSUE TITLE
Add "Accredited claims agent" radio option, copy update for VSO

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74330]
## Background
We have decided to add claims agents back into our Find a Rep search.  

<img width="147" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--591af90ca3d6beaf6b6fc8c4b6c4cbee138db4a3/image.png" alt="image.png" />

## Tasks
- [ ] Add "Accredited claims agent" as the third (last) option for the "Type of accredited representative" section
- [ ] Update copy for the rep option to be "Accredited Veterans Service Officer (VSO)"

## Acceptance Criteria
- [ ] Find a Representative supports searching for Veteran Service Officers, Accredited attorneys and Accredited claims agents
