### ISSUE TITLE
Add additional data to survey recruitment page

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#74339]
## Purpose
Review the [what we've tried page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2902130790/Recruiting+Participants+What+we+ve+tried) and surface the data points Leadership may like to see

## Tasks
- [ ] Review Leadership request(s) for additional data to gather
- [ ] Gather data from various methods (Slack, Mural, etc)
- [ ] Add data to page

## Acceptance Criteria
- [ ] Page reflects additional survey data points
