### ISSUE TITLE
Updates to additional component rep definitions

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74333]
## Background
In https://github.com/department-of-veterans-affairs/va.gov-team/issues/74330 we are adding claims agents back to the Find a Rep search.  We need a definition to support this radio option, in the form of an additional component titled "What does an accredited claims agent do?".

Additionally, CAIA has provided updated content for the VSO and attorney definitions.

Screenshot of [design](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=647%3A63993&mode=design&t=LdU8arNlOGNi6sLm-1): 
<img width="602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9TQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4dd6da20a9f5ed905588c00f2385b8022ff3711/image.png" alt="image.png" />

## Tasks
- [ ] Add an additional component with the title "What does an accredited claims agent do?"
- [ ] Ensure rep definitions match the content in the [design](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=647%3A63993&mode=design&t=LdU8arNlOGNi6sLm-1)

## Acceptance Criteria
- [ ] Users of Find a Representative will be able to to understand all rep types, with CAIA-approved definitions.
