### ISSUE TITLE
When a user searches for an organization by name, highlight the organization in rep search result cards

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74345]
## Background
Platform team recommended surfacing the relevant Veteran Service Organization in search results, when an organization name is entered into the “Name” search input.  The idea is to connect the search results back to that search parameter.

All other organizations can continue to be listed in the additional component.

Design TBD

## Tasks
- [ ] Add a component to show a single organization above the additional component, in rep search result cards
- [ ] Conditionally show this component, so it only is displayed when the "Name" input matches an organization name

## Acceptance Criteria
- [ ] If an organization name is entered into the "Name" search input, that organization will be explicitly mentioned in the rep search result cards (above the additional component)
