### ISSUE TITLE
Diff contact info when processing The Trexler File, so we can track if reported contact information has been updated

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74343]
## Background
Diff contact info when processing The Trexler File, so we can track if reported contact information has been updated.  This will also improve the processing speed of new Trexler Files.

## Tasks
- [ ] Diff contact info when processing The Trexler File
- [ ] If any of the contact info for a rep is not flagged, skip and do not update
- [ ] If any of the contact info for a rep is flagged, update the rep record and associated table information (phone, email, address)

## Acceptance Criteria
- [ ] If a rep's information has been reported as inaccurate and is then updated to new information via OGC, we will be able to track that in the back end.  The new information will have a reset counter of 0 reports, and the old information that was reported will be marked as "updated".

**Comment by holdenhinkle** [comment]
This is done. Waiting for review/merge.
