### ISSUE TITLE
Empty state search experience

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74342]
## Background
Improving the empty state search experience for users:
1. Including feedback on the selected radius
2. Adding a recommendation to update the search
>For better results, you can increase your search radius, you can enter a different search term (city, state, or postal code), or you can change search type (Veterans Service Officer or accredited attorney).
3. Hide the sort, as there are no search results to sort through

[Mobile Design](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=120%3A67855&mode=design&t=LdU8arNlOGNi6sLm-1) of improved empty state:
<img width="402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79c4a53c984a6d85b1f2a757e48fbdfea238df89/image.png" alt="image.png" />

[Desktop Design](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=120%3A81277&mode=design&t=LdU8arNlOGNi6sLm-1)
<img width="951" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58bd44840747d608606f30f078e46ecfe29a4dc5/image.png" alt="image.png" />

## Tasks
- [ ] Include the search area in the search summary
- [ ] Update styling for the search summary, so all search parameters are bold and within quotations
- [ ] Add an additional line "for better results" -- see design

## Acceptance Criteria
- [ ] Users will have some guidance to increase their search area if their original search does not return results.
