### ISSUE TITLE
Fix embedded links on QA Standards page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#74369]
## User Story
As a VFS team member, I want to easily find the guidance for each QA standards so that I can be sure I'm meeting Platform expectations.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
The 5 QA Standards listed within the table on the [QA Standards page](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#) on Platform Website are links, intended to take the user to the additional details about each standards listed toward the bottom of the page. Right now, none of the links work. They all direct the user to the top of the page.

## Impacted Artifacts
[QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#) page on PW

## Tasks
- [ ] Fix the links within the table so they direct to the appropriate anchor links within the _How standards are validated_ section of the page

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Platform Website users are directed to the right guidance when they click the links within the table

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@briandeconinck [this](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2375909428/QA+standards) is ready for review (though it has not published yet)

**Comment by briandeconinck** [comment]
This looks good, I think you're good to publish @it-harrison!
