### ISSUE TITLE
Train Governance team members on how to generate SR issue tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#74371]
## User Story
As the Governance team PM, I want to train the rest of my team on how to execute the script for bulk uploading the Staging Review issue tickets so that I am no longer the only team member who can complete this process.

As a Governance team member, I want to learn how to execute the script for bulk uploading the Staging Review issue tickets so that I am no longer dependent on my PM and can share in the responsibility.

Assignee: @briandeconinck @allison0034 @it-harrison @rferguson13 @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
At the Collaboration Cycle Staging Review, Governance team documents all of their feedback in a Google Sheets tool called the DraftingTemplate. The DraftingTemplate will convert the teams feedback into github markdown, specifically following the issue ticket layout Governance team has defined for their SR issue tickets. This then allows Governance team to bulk upload all of the SR issues at once.

Historically, the Governance team PM, @shiragoodman, has been the sole person responsible for completing the upload. When the DraftingTempalte was introduced, there was an attempt to cross-train Governance team members on the bulk upload process, but due to the complexity and fragility of the DraftingTemplate, the team abandoned the idea and Shira has been responsible since.

Now that the DraftingTemplate is much simpler with less room for human error, Governance team would like to share in this responsibility, meaning the Governance team members will need to be trained in the bulk upload process.

## Impacted Artifacts
DraftingTemplate 2.0
DraftingTemplate 2.0 - DST
How to generate Staging Review issue tickets

## Tasks
- [x] Download and install node.js
   - [x] Allison
   - [x] Erin
   - [x] Rebecca
   - [x] Ian
   - [x] Brian
- [x] Install the GitHub CSV Tools service using this code in your command line utility: `npm install -g github-csv-tools `
   - [x] Allison
   - [x] Erin
   - [x] Rebecca
   - [x] Ian
   - [x] Brian
- [x] Generate a new [github token.](https://github.com/settings/tokens) Ensure the token has permissions to write issue tickets.
   - [x] Allison
   - [x] Erin
   - [x] Rebecca
   - [x] Ian
   - [x] Brian
- [x] Once all team members have successfully completed the above steps, Shira will schedule a meeting to walk through the process. Basic instructions on uploading in bulk to Github can be found [here](https://scottjjackson.medium.com/how-to-bulk-create-issues-in-github-a278d429b7bf) and specific instructions per our Staging Review can be found [here. ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)
- [ ] Create a dummy ticket with fake data. Check the box below when you have successfully completed an upload.
   - [ ] Allison
   - [ ] Erin
   - [ ] Rebecca
   - [ ] Ian
   - [ ] Brian

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All Governance team members have been trained to bulk upload GitHub issue tickets
- [ ] All Governance team members have successfully executed the GitHub CSV Tools script

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Is there a way for Shira to still be notified if/when a VFS team comments on the ticket if she's not the author of the ticket (ie if her github token is not used in the upload)?

**Comment by allison0034** [comment]
I have node, however it is outdated and I am getting en error when I try to update.

**Comment by rferguson13** [comment]
I'm having issues installing Node. Meeting with Ian on May 2 to try and resolve it.

**Comment by allison0034** [comment]
I was able to update node but now I have an error for GitHub CSV Tools, it may be a permissions issue.

**Comment by allison0034** [comment]
@shiragoodman  I did everything successfully, however I remember doing all these things last time. For some reason I don't think my personal token ever worked. Is there a way to check this?

**Comment by shiragoodman** [comment]
@allison0034 I'd recommend just creating a new token. The tokens usually have an expiration date so your old token is likely no longer working anyways.

**Comment by shiragoodman** [comment]
Governance team members ran into issues executing the GitHub CSV Tools script. A[ ticket was submitted](https://github.com/department-of-veterans-affairs/github-user-requests/issues/21813) to the VA Github admins and unfortunately, the script is not supported and known issues have been documented. Bc of this, Governance team is unable to complete this ticket. We will explore other options of bulk uploading tickets.
