### ISSUE TITLE
Organize Platform Tech Team Support Space in Confluence 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74378]
## Description 
We have recently added a ton of documentation to our Platform Tech Team Support section of Confluence. As a result, it could use some cleanup to make things easily findable. 

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Ensure all appropriate buckets of content are created
- [x] Move existing articles in buckets that make sense
- [x] Archive any pages with the owners who created them
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Complete. Reformatting pages in next sprint here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/74662
