### ISSUE TITLE
Review Onboarding Docs and Ensure Updated for Future Hires

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74379]
## Description 

It has been a bit of time since we have updated our onboarding docs. Now, as we grow, we need to review these documents again and ensure they are accurate. 

https://vfs.atlassian.net/wiki/spaces/PTST/pages/2634088477/Onboarding+Checklist+-+Platform+Support+Team

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Review [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2634088477/Onboarding+Checklist+-+Platform+Support+Team) and ensure the information is updated and accurate 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Derailed by DORA metrics work. Will put in next sprint.

**Comment by alyssagallion** [comment]
Complete. Closing. 

Results: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2634088477/Onboarding+Checklist+-+Platform+Support+Team
