### ISSUE TITLE
Payment history (VHA) updates - Tech Discovery

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#74384]
## High Level User Story/ies
As a Veteran who is logged into the Debt Portal I would like the ability to view my payment history with amounts and dates including any adjustments 

## Definition of done

- [ ] Determine what data is available via Cerner and or Vista and what we should use moving forward
- [ ] Identify if the data is available on DMC backend
- We have the API info.. it is established but our data has not been added to that API yet.
- Is there any "connection" type pre-work they can do or do we need to wait for the data to be available for them to do anything?

- [ ] Identify Business rules and exceptions for displaying data
