### ISSUE TITLE
GA4: Create base GA4 implementation

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#74387]
### Description
Due to the length of time since the initial transition to GA4 started, the evolution of the platform since that time, and a shift in measurement strategy, VA.gov will benefit more from a fresh start than trying to fix the current implementation. This starts with the creation of new GA4 properties for the production and lower environments (dev and staging) and the base implementation of the GA4 tracking code. 

**What does "base" mean?** 
A base implementation for Google Analytics (UA or GA4) is the set up of the account and instillation of the platforms code snippet. _Pageview_ tracking is a default measurement of the base implementation but other universal event tracking is added to the implementation at this time - e.g. external and download link clicks.  

### Tasks
GA Reset Property Configuration 
- This is primarily the 'Data collection and modification settings' 
-Data Stream settings
-Filters - the primary difference between the Prod and Lower Environments properties is that only Prod will have these filters:
---Debug
---Internal

- Privacy Concerns - erring on the side of caution where possible, these will be explained in comments 

Snippets Added to Site
- For VA.gov, we will be using GTM for implementation instead of directly installing the Google Tag into the site's code base

Default/Universal Events
- Pageviews
- External link clicks
- Download link clicks
- Contact link clicks(?)

### Acceptance Criteria
Confirmation that the reset Prod and Non-prod GA4 properties are receiving: 

- [x]   Traffic from the correct environments (Prod, Dev, Staging)
- [x]   Pageviews
- [x]   External link clicks
- [x]   Download link clicks

- [ ] Technical documentation has been documented [here](https://docs.google.com/document/d/1Mw8d2yRtuWEXX23ChGeCv51dJ7MJvrYgdY8dCXNBKtc/edit) (we will move this to Confluence eventually)

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc Traffic started showing up immediately in the GA4 RESET properties: 
 
- [GA4] VA.gov - Production - RESET 
<img width="410" alt="Screenshot 2024-02-13 at 8 20 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/a1f97c57-4295-495e-a38f-41a74a984e5a">

- [GA4] VA.gov - Non-Production - RESET
<img width="404" alt="Screenshot 2024-02-13 at 8 22 13 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/b74a435c-150f-4f2e-9628-20524fb42164">

Documentation was moved to [Create documentation for Base GA4 Implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75852)
