### ISSUE TITLE
[FE] Dot indicator: update unread logic to exclude Sent folder

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#74388]
## Background
In #71864, we determined that the unread logic for My VA is indeed displaying unreads from other folders, besides the default inbox. 

Wes Rowe from MHV has been [following up with the Secure Messaging BE team re: an API patch](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/71809#issuecomment-1875800564). In the meantime, they are just excluding the Sent folder in their logic, so I suggest we do the same until the SM BE team updates the API.

---
## Tasks
- [x] Update messaging mock data to include a Sent folder with unread messages
- [x] Update My VA unreadCount logic to match [MHV's updated logic](https://github.com/department-of-veterans-affairs/vets-website/blob/b1692e4d3d8f1c518360fcda8012fb38064caf83/src/applications/mhv-landing-page/utilities/data/index.js#L21-L35)
- [x] Write unit tests for `countUnreadMessages` and `getFolderList`

## Acceptance Criteria
- [ ] user has unread messages in their Sent folder, but dot indicator does not show up 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? any dev_
- _How can this work be validated?_ instructions coming soon~

## Resources
- [MHV landing page updated logic](https://github.com/department-of-veterans-affairs/vets-website/blob/b1692e4d3d8f1c518360fcda8012fb38064caf83/src/applications/mhv-landing-page/utilities/data/index.js#L21-L35)
- [MHV landing page PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27344)

**Comment by allisonlu** [comment]
@ajakabcin 

to validate:
1. (easiest) have @DanielMiller-agile6 or @adamwhitlock1 confirm that the [code from the PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27626) has indeed made it to the `main` branch
2. (more time) find a staging user who ONLY has unread messages in their Sent folder and confirm that the red dot indicator is not present

**Comment by adamwhitlock1** [comment]
Can confirm this code has landed in main. Should be good to close this.
