### ISSUE TITLE
[BE] 10-10EZ - TERA: Store form data input in VA.gov db

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#74394]
## Benefit to the Veteran
The Veteran will be able to submit their 10-10EZ application with Toxic Exposure details, so that they may qualify for expanded or new benefits they may not otherwise qualify for.
Storing this data input will allow us to transmit it to the Enrollment system, once it is set up to receive.

## Background 
On February 9th, we were advised that we should expect a push to have TERA questions on the EZ form by March 5th.  
Patrick advised that we should find a solution on VA.gov to store the TERA data input, even if it doesn't go anywhere right away.  This is very large RISK, as there is a 60-day limitation on PII in the VA.gov db.  Once the 60 days comes up, we have to write a job to delete the records.
The Enrollment system is currently scheduled for June to deliver the path for us to send TERA data.  The VES team may also be advised to deliver earlier than June, however we have been tasked to move forward with an interim solution.

In an effort to meet the deadline, imposed due to the communications going out to Veterans to apply for health care and include their TERA responses in March, we want to work toward this solution.

## Resources
- [Most recent TERA Draft 10-10EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/TERA%20draft%201-23-2024%20VA%20Form%2010-10EZ.pdf)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?fromVisitorModal=true&sender=u5ad49c107baa41137f271007)
- [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=450-19244&mode=design&t=GyO36RKAPEFgXEna-0)
- [Notes from Urgent Team meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Meeting%20Notes/2024-02-09%20Urgent%20Team%20meeting%20for%20early%20delivery.md)
- [Notes from last-minute Engineer update meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Meeting%20Notes/2024-02-09%20Mtg%20with%20Engineering%20on%20direction.md)

## Tasks

- [x] Review reference materials
- [x] Meet with teammates (Josh, Lihan) for any details needed
- [ ] Set up for application data to be stored in VA.gov db
     - This is in addition to submissions transmitting successfully. We do not want to stop the current process of submissions
- [ ] Complete testing, as per usual code testing guidelines
     - Be sure to capture any notes or comments in this ticket
- [ ] Inform PMs and Matt L that you have completed work and testing

## Acceptance Criteria
- The 10-10EZ application data input is set up to be stored in VA.gov db, in addition to the usual submission process.

**Comment by jadon1979** [comment]
This ticket should be put on the backburner until ES has been updated with the new fields and requirements.  Otherwise, we will end up with numerous tickets sitting stagnant for an undetermined amount of time in the backlog.  Determing prefill availability will also be necessary to accurately define tickets, but that is unknown until ES is updated.

**Comment by hdjustice** [comment]
Thank you Chapley!  Hope we can pull this back soon.

**Comment by jadon1979** [comment]
JSON schema for TERA 
`{
  "toxicExposure": {
    "type": "object",
    "properties": {
      "ionizingRadiation": {
        "type": "boolean"
      },
      "gulfWarHazardLocations": {
        "type": "object",
        "properties": {
          "onLocation": {
            "type": "boolean"
          },          
          "startDate": {
            "type": "string"
          },
          "endDate": {
            "type": "string"
          }
        }
      },
      "exposureOperations": {
        "type": "boolean"
      },
      "herbicideExposureLocations": {
        "type": "object",
        "properties": {
          "onLocation": {
            "type": "boolean"
          },          
          "startDate": {
            "type": "string"
          },
          "endDate": {
            "type": "string"
          }
        }
      },
      "exposures": {
        "type": "object",
        "properties": {
          "exposure": {
            "type": "array",
            "items": {
              "types": {
                "type": "string",
                "enum": [
                  "Air Pollutants",
                  "Chemicals",
                  "Containment water at Camp Lejeune",
                  "Radiation",
                  "Shad",
                  "Occupational Hazards",
                  "Asbestos",
                  "Mustard Gas",
                  "Warfare Agents",
                  "Other"
                ]
              }
            }
          },
          "specifiedExposure": {
            "type": "string"
          },
          "startDate": {
            "type": "string"
          },
          "endDate": {
            "type": "string"
          }
        }
      }
    }
  }
}`

**Comment by jadon1979** [comment]
Potential WSDL Docs 
```
  <xs:complexType name="toxicExposure">
    <xs:all>
      <xs:element name="ionizingRadiation" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="gulfWarLocation" type="gulfWarLocationInfo" minOccurs="0" maxOccurs="1"/>
      <xs:element name="exposureOperations" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="herbicideExposureLocation" type="herbicideExposureLocationInfo" minOccurs="0" maxOccurs="1"/>
      <xs:element name="exposures" type="exposuresInfo" minOccurs="0" maxOccurs="1"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="gulfWarLocationInfo">
    <xs:all>
      <xs:element name="onLocation" type="xs:string" minOccurs="0"/>
      <xs:element name="startDate" type="xs:string" minOccurs="0"/>
      <xs:element name="endDate" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="herbicideExposureLocationInfo">
    <xs:all>
      <xs:element name="onLocation" type="xs:string" minOccurs="0"/>
      <xs:element name="startDate" type="xs:string" minOccurs="0"/>
      <xs:element name="endDate" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="exposuresInfo">
    <xs:all>
      <xs:element name="exposure" type="exposureCollection" minOccurs="0"/>
      <xs:element name="specifiedExposure" type="xs:string" minOccurs="0"/>
      <xs:element name="startDate" type="xs:string" minOccurs="0"/>
      <xs:element name="endDate" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="exposureCollection">
    <xs:all>
      <xs:element name="value" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>  
```

**Comment by jadon1979** [comment]
Josh F sent this schema over 
[eeSummary 1.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5jQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee7690a330a91d6e200ca93b85544dc25658aa44/eeSummary%201.txt)

**Comment by hdjustice** [comment]
The direction has changes, as the Enrollment system will now make changes to receive all TERA data.  There is no longer a need to store PII in VA.gov DB
