### ISSUE TITLE
[CAIA General Support]: Sitewide Facilities - Review VBA Terms for publishing in VA Service Taxonomy

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-team#74390]
# CAIA General Collaboration 

Use this ticket to request general collaboration with the Sitewide Content, Accessibility, and Information Architecture (CAIA) team.

## About your team

- **Team name**: Sitewide Facilities
- **OCTO-DE product owner:** @mmiddaugh 
- **Product name:** VBA Regional Offices & VA Services Taxonomy
- **Product manager:**  @xiongjaneg 
- **Slack channel:** [#sitewide-facilities](https://join.slack.com/share/enQtNjUxMDMyMzI5MzkyNy00OTg5MjJhOTA0YzI5MDJmMzBjNTc0OWJkMGM1Y2Y2MzViZGVmNTA5YmY5ODJlNDg4MDE0NjE2ZmZhNDM4ZWFh)
- **Dedicated content writer on your team (if you have one):** @davidmpickett 
- **Dedicated a11y specialist on your team (if you have one):** @laflannery 
 
### Describe your project goals

Have a single source of truth for services offered at VA facilities (VAMCs, Vet Centers, VBA ROs).

### What is your team working on?

We are adding new terms to the VA Service Taxonomy to support the launch of the modernized VBA Regional Office pages.

We [previously worked with y'all](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58511) to review and copy edit potential terms. We now have some terms that are ready for **final review** in Drupal.

## Type of Collaboration 
_Check all the types of collaboration you're requesting, below:_

### Content
- [ ] Creating new content 
- [x] Updating existing content 
- [ ] Translating content 
- [ ] Something else: 

## Terms ready to review in Drupal

Label and link to Drupal | Tugboat example | Notes 
-- | -- | --
[Benefit letters and decision letters](https://prod.cms.va.gov/health-care/benefit-letters-and-decision-letters) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1142-)
[Burials and memorials](https://prod.cms.va.gov/health-care/burials-and-memorials) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1143-) 
[Careers and employment](https://prod.cms.va.gov/health-care/careers-and-employment) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1169-)
[Compensation benefits for survivors](https://prod.cms.va.gov/health-care/compensation-benefits-for-survivors) | NA
[Direct deposit information](https://prod.cms.va.gov/health-care/direct-deposit-information) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1170-)
[Disability compensation](https://prod.cms.va.gov/health-care/disability-compensation) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1144-)
[Education benefits for family members](https://prod.cms.va.gov/health-care/education-benefits-for-family-members) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1145-) |  Regional 
[Education benefits for Veterans](https://prod.cms.va.gov/health-care/education-benefits-for-veterans) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1146-) | Regional  
[Grief and bereavement counseling](https://prod.cms.va.gov/health-care/grief-and-bereavement-counseling) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1006-) | Term also has Vet Center fields
[Homeless Veteran Care](https://prod.cms.va.gov/health-care/homeless-veteran-care) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-39-) | Term also has VAMC and Vet Center fields
[Home loans](https://prod.cms.va.gov/health-care/home-loans) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1131-) | Regional 
[Life Insurance](https://prod.cms.va.gov/health-care/life-insurance) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1147-)
[Military records](https://prod.cms.va.gov/health-care/military-records) |  [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1148-)
[Military sexual trauma-related claims](https://prod.cms.va.gov/health-care/military-sexual-trauma-claims) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1171-)
[Pre-discharge claims](https://prod.cms.va.gov/health-care/pre-discharge-claims) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1172-)
[Pre-need burial planning](https://prod.cms.va.gov/health-care/pre-need-burial-planning) | NA
[Returning service member care](https://prod.cms.va.gov/health-care/returning-service-member-care) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-55-) | Term also has VAMC and Vet Center fields
[Transition assistance](https://prod.cms.va.gov/health-care/transition-assistance) |  NA
[Veterans Pension](https://prod.cms.va.gov/health-care/veterans-pension) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1130-)  | Regional
[Veteran readiness and employment programs ](https://prod.cms.va.gov/health-care/veteran-readiness-and-employment-programs) | [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-94-) | Term also has VAMC and Vet Center fields
[VetSuccess on Campus](https://prod.cms.va.gov/health-care/vetsuccess-on-campus) |  [Philadelphia](https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1173-)

**Regional** = These are Services that I have drafted Regional service header & description fields for. My understanding is these are services that have regional centers that veterans can meaningfully interact with.

Field | Notes for content reviewers
-- | --
Show for VBA Facilities | This is where the VBA fields begin
Type of care | No review needed - the categories have been confirmed with VBA stakeholders
VBA description | Many of these were previously copy-edited by CAIA & updated with feedback from VBA. Looking for final review on wording. 
Regional service header | Needs review from CAIA (wording) 
Regional service description | Needs review from CAIA (wording) 
Facility service header | Needs review from CAIA (wording) 
Facility service description | Needs review from CAIA (wording) 
Online self-service |  Needs review from CAIA (wording & link)

**How these Drupal fields will map to the Front End**

![VBA Content model_2023-12-11_23-17-13](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/b33fbba7-0973-448d-9d18-b12f2ef4fdcb)

## Collaboration timeframe

We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Your timeline 
- [ ] Check yes, if this request is tied to a Congressional mandate or timeline?

### Will you release this new product incrementally (for example, release to 25% of users to start)?
- [X] Yes (in the sense that we will publish terms in batches as they are approved, rather than all at once. The end users are Drupal CMS editors so there's no react widget needs.)
- [ ] No

**Note: **If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages). Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.

- [x] I acknowledge that if I change the roll out of this product to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines. 

### Description
**Describe where you are in your project's timeline.** 

We are beginning to pilot the Drupal CMS interface with a small group of VBA editors while we finish up building the front end. We would like to have more terms published so that editors can start adding Services to their Facilities by **March 19**.

## Collaboration cycle 
If you’re going through the collaboration cycle with the governance team, link to the ticket:
- **Ticket Number:** #46029

**Note**: We ask that you partner with us **before** scheduling your midpoint review, **to ensure** we can agree on a deliverable and that there's time for your team to make changes.  

### Phases Completed
**Check any phases you’ve already completed:**
- [x] Design intent 
- [x] Midpoint review 
- [ ] Staging 
  
## Supporting artifacts
Please provide links to any supporting artifacts we might need to begin work. This can include your product outline, user flows, mockups and prototypes, draft content, etc.
- [VA Service Taxonomy product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/va-service-taxonomy)
- [VBA Regional Office product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices)
- Original [source of truth](https://dvagov.sharepoint.com/:x:/s/VBAVA.govmodernization/ET964xEqUFREirhtu34HQVIBbsNOu12QIUc-EVNF_aW98g) for all VBA services content
- Annotated [design for the Front End](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/772C1EED-1ED9-4544-8DB1-FBB388534931/canvas) 
- Proposed [design for the Drupal interface](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=52-481&mode=design)

## Next steps
- [ ] Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.
    - A member of the CAIA team will aim to respond to your Slack message within 24 hours to acknowledge receipt - should we need any additional information regarding your request we will reach out to you to confirm.
    - The CAIA Operations group will meet to go over the info in your request and then reach out if we have any questions.
    - Depending on the request, it may make sense to schedule a kickoff meeting to better understand how we'll partner with you!
- [ ] Please review the remaining next steps in the **VFS Team Tasks** section, listed below.

## TASKS

<br>

```[tasklist]
### VFS Team Tasks
- [ ] If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
- [ ] If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.
- [x] If you are requesting content support, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### a11y Tasks
```

```[tasklist]
### Content Tasks
```

```[tasklist]
### IA Tasks
```

```[tasklist]
### CAIA Ops
```

**Comment by davidmpickett** [comment]
@laurwill @strelichl 
Just want to call out that this ticket is still a draft and we're not _quite_ ready for y'all to review (even the ones listed as ready for review). @mmiddaugh is currently getting [final review from VBA stakeholders](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17046). We will be sure to ping you when we have a batch that are ready.

**Comment by kristinoletmuskat** [comment]
@strelichl  I don't think IA needs to be involved in this  one

**Comment by davidmpickett** [comment]
Updated the table here to reflect additional terms that are ready for final review

**Comment by laurwill** [comment]
Hey @davidmpickett sorry for delayed response here, just want to confirm that we only need to review the Drupal links in the top table here? There's some older sketch links lower down, are you in Figma at all now or just Drupal?

**Comment by davidmpickett** [comment]
Hi @laurwill, let me do a little cleanup on the links before you start. Drupal is the content source of truth, but the designs might be helpful for understanding them in context better. I can also add a link to a staged environment that will allow you to see them fully in context (when the environment isn't being temper mental)

**Comment by laurwill** [comment]
Great! That all sounds good — and do you have a timeline we should be aiming for for this review?

**Comment by davidmpickett** [comment]
@laurwill Sorry for the delay, was traveling last week. I just updated the chart in the ticket to include all the terms that are drafted in Drupal with direct links to Drupal source of truth and links to example content on a Tugboat for most terms. (Tugboat requires SOCKS access).

Should be ready for your review. Let me know if you have any questions

**Comment by davidmpickett** [comment]
@strelichl I have a conflicting meeting at that time. I might be able to join if it ends early, but can't commit to that. Possible to async, or schedule a one-off call?

**Comment by davidmpickett** [comment]
@laurwill - here's a few screenshots for you to help with context. Let me know if you have any additional questions once you get in to it.

![Screenshot 2024-06-18 at 3 42 54 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/51967950/b5a288ec-7a43-49ec-8531-a3b4ba6f2592)

![Screenshot 2024-06-18 at 3 43 02 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/51967950/47e233f3-e61b-4cab-84b9-2bb98347424c)

![Screenshot 2024-06-18 at 3 43 40 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/51967950/4e90ed14-711e-426c-bb52-0bb3b0d0af3c)

**Comment by laurwill** [comment]
Hey @davidmpickett , thanks again for all the very clear documentation here! Here's my list of questions and suggestions — I'm OOO next week, but happy to chat when I'm back on 7/8. 

**General Qs about Facility service description field**
- Can we adjust the ones that start with a colon and use -ing phrasing (“Our benefit counselors can help you with: understanding eligibility…) to match the ones that use more direct phrasing like “Our benefit counselors can help you understand eligibility, gather required documents, and fill out paperwork"?
- In cases where the facility service description only repeats text from the VBA description, could we consider leaving it blank? For example, VetSuccess on Campus has duplicative content in these 2 fields, and I think it would work fine to remove facility service description completely and just keep the facility service header.

**Compensation benefits for survivors**
- If this is specific to survivor comp (and not other types of benefits for survivors), suggest changing label to “Survivor compensation” to match new family hub page and changing link to "https://www.va.gov/family-and-caregiver-benefits/survivor-compensation/ "
* In VBA description, suggest changing “we can help you learn about eligibility and apply for VA benefits or compensation.” to “we can help you learn about eligibility and apply for VA survivor compensation.”

**Direct deposit**
- In VBA description, change “disability compensation, pension, or education benefits from VA” to “VA disability compensation, pension, or education benefits”

**Disability compensation**
- In VBA description, suggesting changing this sentence: “If you've already initiated a claim or higher-level review, we can help you check the status.” Higher-level reviews are only 1 of the 3 types of decision reviews, and we don’t use “initiated” in site style. Suggest: “If you’ve already filed a disability claim or requested a decision review” 

**Education benefits for family members** and **Education benefits for Veterans**
- VBA descriptions for these 2 are statements of eligibility, instead of a “we can help you do xyz” approach that all the others follow. The family one is also slightly inaccurate, since family members can only use Post-9/11 GI Bill if they get transferred benefits, and we need to correct the DEA program name.
     - Suggestion for family description: “We can help you apply for VA education benefits for family members, including Dependents’ and Survivors’ Educational Assistance (Chapter 35) and the Fry Scholarship. We can also help you apply to use transferred Post-9/11 GI Bill benefits.”
     - Suggestion for Veteran version: “We can help you apply for VA education benefits, find the right school or training program, or get career counseling.”
- Suggest updating family version link to new family hub page: “[Learn how to manage education benefits for family members online](https://www.va.gov/family-and-caregiver-benefits/education-and-careers/)”
- Regional service descriptions both say “Check the status of your claim by calling a VA education representative at a Regional Processing Office.” Is this office the Regional Processing Office? Is the phone number directly below this the number they would call to check their claim? If so, suggest changing description to “Call us to check the status of your application for education benefits.”

**Home loans**
- Same Q about regional service description as on the education benefits terms — if we’re presenting the phone number right there, we’d usually say something more like “Call us to check the status of your home loan COE.”

**Military records**
- Could consider “Military service records” for term name to align with linked page

**Pre-discharge claims**
- in VBA description, change “initiated a claim” to “filed a claim”

**Returning service member care & Transition assistance**
- These seem to be the same. What’s the difference between these? Do they ever appear on the same facility page?

**Veterans Pension**
- We capitalize Pension in this program name, so suggest title casing term name
- In VBA description, could consider changing “age” to “service” — age isn’t always a deciding factor in eligibility, but service history is
- Regional service description says “you can submit your form by mailing it to this address” with no address — but as far as I know there’s only a single, national mailing address for all pension forms. Is this field supposed to offer different mailing addresses for different regional offices?

**VR&E**
- We use title case in this program name, so suggest title casing term name
- Change link (currently says “find out if you’re eligible” but links to PDF form detail page). Suggest “[Learn how to manage VR&E benefits online](https://www.va.gov/careers-employment/vocational-rehabilitation/)”

**VetSuccess on Campus**
- This has no link, do we want to link[ here](https://www.va.gov/careers-employment/vetsuccess-on-campus/)? Or is this not something they can really do online?

**Comment by davidmpickett** [comment]
## Dave's scratchpad for implementation and responses

> **General Qs about Facility service description field**
> - Can we adjust the ones that start with a colon and use -ing phrasing (“Our benefit counselors can help you with: understanding eligibility…) to match the ones that use more direct phrasing like “Our benefit counselors can help you understand eligibility, gather required documents, and fill out paperwork"?
> - In cases where the facility service description only repeats text from the VBA description, could we consider leaving it blank? For example, VetSuccess on Campus has duplicative content in these 2 fields, and I think it would work fine to remove facility service description completely and just keep the facility service header.
> 
> **Compensation benefits for survivors**
> - If this is specific to survivor comp (and not other types of benefits for survivors), suggest changing label to “Survivor compensation” to match new family hub page and changing link to "https://www.va.gov/family-and-caregiver-benefits/survivor-compensation/ "
> * In VBA description, suggest changing “we can help you learn about eligibility and apply for VA benefits or compensation.” to “we can help you learn about eligibility and apply for VA survivor compensation.”
> 
> **Direct deposit**
> - In VBA description, change “disability compensation, pension, or education benefits from VA” to “VA disability compensation, pension, or education benefits”
> 
> **Disability compensation**
> - In VBA description, suggesting changing this sentence: “If you've already initiated a claim or higher-level review, we can help you check the status.” Higher-level reviews are only 1 of the 3 types of decision reviews, and we don’t use “initiated” in site style. Suggest: “If you’ve already filed a disability claim or requested a decision review” 
> 
> **Education benefits for family members** and **Education benefits for Veterans**
> - VBA descriptions for these 2 are statements of eligibility, instead of a “we can help you do xyz” approach that all the others follow. The family one is also slightly inaccurate, since family members can only use Post-9/11 GI Bill if they get transferred benefits, and we need to correct the DEA program name.
>      - Suggestion for family description: “We can help you apply for VA education benefits for family members, including Dependents’ and Survivors’ Educational Assistance (Chapter 35) and the Fry Scholarship. We can also help you apply to use transferred Post-9/11 GI Bill benefits.”
>      - Suggestion for Veteran version: “We can help you apply for VA education benefits, find the right school or training program, or get career counseling.”
> - Suggest updating family version link to new family hub page: “[Learn how to manage education benefits for family members online](https://www.va.gov/family-and-caregiver-benefits/education-and-careers/)”
> - Regional service descriptions both say “Check the status of your claim by calling a VA education representative at a Regional Processing Office.” Is this office the Regional Processing Office? Is the phone number directly below this the number they would call to check their claim? If so, suggest changing description to “Call us to check the status of your application for education benefits.”
> 
> **Home loans**
> - Same Q about regional service description as on the education benefits terms — if we’re presenting the phone number right there, we’d usually say something more like “Call us to check the status of your home loan COE.”
> 
> **Military records**
> - Could consider “Military service records” for term name to align with linked page
> 
> **Pre-discharge claims**
> - in VBA description, change “initiated a claim” to “filed a claim”
> 
> **Returning service member care & Transition assistance**
> - These seem to be the same. What’s the difference between these? Do they ever appear on the same facility page?
> 
> **Veterans Pension**
> - We capitalize Pension in this program name, so suggest title casing term name
> - In VBA description, could consider changing “age” to “service” — age isn’t always a deciding factor in eligibility, but service history is
> - Regional service description says “you can submit your form by mailing it to this address” with no address — but as far as I know there’s only a single, national mailing address for all pension forms. Is this field supposed to offer different mailing addresses for different regional offices?
> 
> **VR&E**
> - We use title case in this program name, so suggest title casing term name
> - Change link (currently says “find out if you’re eligible” but links to PDF form detail page). Suggest “[Learn how to manage VR&E benefits online](https://www.va.gov/careers-employment/vocational-rehabilitation/)”
> 
> **VetSuccess on Campus**
> - This has no link, do we want to link[ here](https://www.va.gov/careers-employment/vetsuccess-on-campus/)? Or is this not something they can really do online?

**Comment by davidmpickett** [comment]
@laurwill Thank you for your very thorough review! I was able to implement most of your suggestions. There are three lingering actions items, but those will be handled in other tickets:

- **Term name changes** - These require a little more Drupal admin support. [I stubbed a ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18452) for our team to complete
- **Regional service descriptions** - You raised some good questions. This part of the VBA RO product has not received as much attention and analysis and won't be part of the MVP launch. I transferred your notes to [a future ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18000) so our team can revisit when we're ready to really grapple with this.
- **Stakeholder/product clarification** - I'll raise these with @mmiddaugh and we'll update accordingly.

## Stakeholder questions for @mmiddaugh
- **Returning service member care & Transition assistance**
  - These seem to be the same. What’s the difference between these? Do they ever appear on the same facility page?
  - "I believe the distinction is that "returning service members" may not be ending their military career, and are eligible for certain benefits between service periods, whereas "transition assistance" is really for those who are fully transitioning to civilian life. There are subtle, but important distinctions in how they interact with VBA, which is why we're splitting them up." - @davidmpickett 
- **VetSuccess on Campus**
  - This has no link, do we want to link [here](https://www.va.gov/careers-employment/vetsuccess-on-campus/)? Or is this not something they can really do online?
  -  "This does not seem to be something that can be completed by online self-service. Will confirm" - @davidmpickett 

I think we're good to close this ticket when you're back in the office @laurwill 

cc @jilladams @Agile6MSkinner for awareness

**Comment by mmiddaugh** [comment]
Returning service member care & Transition assistance
> These seem to be the same. What’s the difference between these? Do they ever appear on the same facility page?
> "I believe the distinction is that "returning service members" may not be ending their military career, and are eligible for certain benefits between service period, whereas "transition assistance" is really for those who are fully transitioning to civilian life. There are subtle, but important distinctions in how they interact with VBA, which is why we're splitting them up." - @davidmpickett

Confirming @davidmpickett's response - these are viewed as distinct populations with slightly different needs. In particular, "restarting benefits" was a significant nuance for VBA stakeholders. The stakeholders also confirmed that the naming conventions would be understood by their audience but I'm open to suggestions on how to better distinguish these services.  
- There is also an [issue in our backlog dating back to 2021](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-cms/13389) in which Vet Centers asked for a service which could represent the support and assistance available for transitions before/during deployment, particularly for families. Once both services are available, we'll revisit definitions and use for VAMCs and Vet Centers to clarify and edit the patient friendly names and descriptions for each. 
- Having said this ^, it's likely some VAMC, Vet Center, and VBA facilities will include both services

**Comment by mmiddaugh** [comment]
VetSuccess on Campus
- This service is less likely to be added to our Regional offices than to the VSOC locations which will be modernized later. If we choose to add the link to VSOC, it could follow the "Learn more about..." or "Find out it you are eligible..." pattern (similar to Transition Assistance). I think we can proceed without it for now until I am able to confirm with VSOC stakeholders.

**Comment by laurwill** [comment]
Hi @davidmpickett @mmiddaugh , it looks like I never responded to your last comments, my apologies! Is there still work needed from us here, or are these terms now live?

**Comment by davidmpickett** [comment]
@laurwill I don't think we need any more support from ya'll at this time. Thanks!

**Comment by jilladams** [comment]
Per Dave's notes on July 3, follow up work on all this is ticketed and we can close. Closing!
