### ISSUE TITLE
[CST] Add boolean to indicate whether a user should be able to upload in CST

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#74409]
### Background
We have discovered that users without BIRLS IDs cannot successfully upload files to the EVSS Documents service. Because we are using a Sidekiq job to upload to the EVSS Documents service, these failures are occurring silently and the UI incorrectly indicates that their files had been received successfully. As a precautionary measure, we should add a field to the response of `V0::BenefitsClaimsController#show` to indicate whether the logged-in user can upload files in the CST or not. This will allow us to update vets-website to conditionally hide or show elements based on this flag

### Engineering Notes
- Requests to EVSS Documents service will fail if the `va_eauth_birlsfilenumber` header is empty or contains an incorrect value.
- The `va_eauth_birlsfilenumber` header is populated from `current_user.birls_id`, so if the value of `current_user.birls_id` is nil, then the request is guaranteed to fail
-  Based on the above information, the `canUpload` flag should be true when the `current_user` has a non-nil `birls_id` and false when they have a nil `birls_id`
- The full path of the `canUpload` flag should be `data.attributes.canUpload`

### Tasks
- [x] Add the field `data.attributes.canUpload` to the `show` method of the `V0::BenefitsClaimsController` to indicate whether the user can upload files in CST
- [x] Add a spec to test that this produces the correct value

### Acceptance Criteria
- [x] A field is added to the claim details response that indicates whether the user should be able to upload in CST or not
