### ISSUE TITLE
[FE] Onsite Notifications: Homepage banner on My VA + CMS familiarization

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#74401]
## Background
As part of our effort to pick back up with notification work, we're going to explore using the homepage banner on My VA. This ticket is to get familiar with the CMS and determine if we can make it work on My VA.

Samara and AJ spoke with @EWashb about this effort. Point of contact on the homepage/CMS team is Tim Cosgrove.

## Tasks
- [ ] Meet with CMS team/Tim
- [ ] Play around with functionality to determine if this can work on My VA

## Acceptance Criteria
- [ ] We know if this is a viable solution for us on My VA

**Comment by allisonlu** [comment]
i haven't started this ticket, so will keep this as 3 points for sprint 31

**Comment by ajakabcin** [comment]
@allisonlu bumping this to sprint 34 since you'll be helping out profile with direct deposit work this coming sprint (33)

**Comment by ajakabcin** [comment]
Closing out - this work was paused indefinitely
