### ISSUE TITLE
[Data] 10-10EZR Monitoring: Create Google Analytics Dashboard for tracking EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#74402]
As a team member, I would like to see how and how often Veterans are using the online EZR so that we make sure the EZR is as easy to use as possible. 

- [x] Determine what the Analytics team can do for us in GA
- [x] Build a custom dashboard with the metrics outlined in [this ticket](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/73238)
- [ ] Track metrics every two weeks
- [ ] Once we have enough data, demo the dashboard to the team
- [x] Provide key insights and trends (e.g. "we're seeing a lot of people drop off at the expenses page)
- [ ] Share findings with Patrick
- [ ] **Success: We have a first draft of EZR metrics and some key insights**

**Comment by luis-simauchi** [comment]
Form metrics

Total Applications
Paper Applications (if possible, we get this info from HEC stakeholders emailed to us)
Online Applications (if possible, we get this info from HEC stakeholders emailed to us)
number of applications started
number of successful submissions
Average # of sessions to submission
Start to submission ratio
Performance metrics

Latency from controller & from external dependent resources
Types of status codes present in errors
Error rate
Avg. time on page / form
wish list item (user page flow funnel)

**Comment by luis-simauchi** [comment]
what we are already getting from EZR dash in DD:

**Comment by luis-simauchi** [comment]
saved in progress stats are available in GA as a API call (I think?) going to bake this into our list of stats for the GA DASH

**Comment by luis-simauchi** [comment]
PDF Downloaded - Download VA Form 10-10EZR (PDF) can also be tracked via events and will be included on the list of metrics as well

**Comment by luis-simauchi** [comment]
we can build deep dive views that link from the Event based dashboard widgets that can focus on users that SIP there forms prior to other actions such as submitting

**Comment by luis-simauchi** [comment]
link to the GA dash for EZR:
https://analytics.google.com/analytics/web/#/dashboard/CUlI050QSVudFoPp8ZnRgQ/a50123418w177519031p176188361/_u.dateOption=last30days/

**Comment by luis-simauchi** [comment]
going to put this in backlog till we open up the EZR to a 100% of user traffic

**Comment by luis-simauchi** [comment]
I am might re-tool this ticket to be data dog centric instead of google analytics
