### ISSUE TITLE
[CDP] Create feature flag for Payment History development

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#74412]
## Description
Create a feature flag for payment history development work. 

[Feature flag documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

## Tasks
- [ ] PR vets-api with feature flag changes
- [ ] PR vets-website with feature flag changes

## Acceptance criteria

- [ ] Feature flag controlling payment history development is active in development 

## Testing
Just confirm it's in the list of feature flags: active in development environments and disabled on production

Testing procedure:
Test on local/staging environments to confirm functionality 

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Closing due to this having been completed elsewhere.

<img width="1401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUJJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--265442fa1044e518f2364316f18b7080f442af3b/image.png" alt="image.png" />
