### ISSUE TITLE
EVSS - Release Plan for PCIU - 526ez Prefill

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#74417]
This ticket covers the release plan to deploy the removal of PCIU calls from the 526ez prefill. The scope includes:

Release plan - look at staggered release
Can point to specific user through feature toggle
Tasks in the ticket

---
## Tasks
- [x] Identify acceptance criteria for a successful run
- [x] Identify/document risks and mitigation
- [x] Build the dashboard for monitoring traffic for VA Profile + PCIU (status quo) versus VA Profile-only (our goal)

## Dashboard Notes
Logging was added in #[73362](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/73362) to record the presence of address, phone and email values that are returned, along with the on/off value of the `disability_compensation_remove_pciu` flag ([example](https://vagov.ddog-gov.com/logs?query=%22disability_compensation_remove_pciu%22%20%40http.referer%3Ahttps%5C%3A%5C%2F%5C%2Fstaging.va.gov%5C%2Fdisability%5C%2Ffile-disability-claim-form-21-526ez%2A%20&agg_t=count&cols=host%2Cservice&event=AgAAAY03MhXciZwSiwAAAAAAAAAYAAAAAEFZMDNNaVY3QUFCbTN3WGRoMklTMFFBQQAAACQAAAAAMDE4ZDM3MzQtZWRhNy00MzE5LWIyNjAtMmMzZWJjN2RjNTQ0&index=%2A&messageDisplay=inline&panel=%7B%22queryId%22%3A%22a%22%2C%22timeRange%22%3A%7B%22from%22%3A1706027451998%2C%22to%22%3A1706028351998%2C%22live%22%3Atrue%7D%7D&refresh_mode=sliding&stream_sort=desc&view=spans&viz=timeseries&from_ts=1706027451998&to_ts=1706028351998&live=true)). With this data we should (hopefully) be able to build a DataDog dashboard that will show basic aggregates of the number of requests (with the flag ON or OFF) where
- [x] Address is missing/present over an interval
- [x] Phone is missing/present over an interval
- [x] Email is missing/present over an interval
- [x] Averages/Percentages of the above per flag value

## Acceptance Criteria
- [x] Identify acceptance criteria for a successful run
- [x] Figure out how to monitor success(526ez form prefill, submit workflow)
- [x] Release plan; add to here https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans
- [x] Create Testrail testplan
- [x] Execute Testrun
- [x] Successful testrun
- [x] Create a ticket for starting the staggered release based on the plan
- [x] Risks have been documented
- [x] Built the dashboard for monitoring traffic for VA Profile + PCIU (status quo) versus VA Profile-only (our goal)

## Release Plan Link
https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20526ez%20Contact%20Info%20Pre-fill%20Migration%20Release%20Plan.md

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Created a first draft [dashboard](https://vagov.ddog-gov.com/dashboard/qv6-xpd-7xg?refresh_mode=weekly&view=spans&from_ts=1706515200000&to_ts=1706663054684&live=true)

**Comment by sethdarragile6** [comment]
Created pre-release test plan (retroactively) and canary launch test plan, added them to the release plan.
- Pre-test link: https://dsvavsp.testrail.io/index.php?/cases/view/58765
- Canary link: https://dsvavsp.testrail.io/index.php?/cases/view/58766

**Comment by sethdarragile6** [comment]
Reviewed release plan and schedule with team and @RakshindaAslam, closing out
