### ISSUE TITLE
Integrate with Lighthouse sandbox

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7441]
## Background
New sandbox environment for Lighthouse API:
> Only a url change is needed to switch over to the Sandbox environment, your API Key and test data will be exactly the same in the new Sandbox environment.

Dev url: dev-api.va.gov
New Sandbox url:  sandbox-api.va.gov

---
## Tasks
- [ ] Update dev url to point to new Lighthouse sandbox url
- [ ] Validate connection works
- [ ] Make any necessary documentation changes 

## Acceptance Criteria
- [ ] Successful integration with Lighthouse's sandbox environment

---

**Comment by MickinSahni** [comment]
PR up for this and putting into Sprint 18

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- Merged and also updated for B&M 1 team as well
