### ISSUE TITLE
Copy of Burial | Create Product Guide

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#74420]
## Issue Description
_All applications on the Veteran-facing Services Platform include a phone number Veterans can call to ask questions about the application's functionality. Because of this, before applications (or new features) launch on the Veteran-facing Services Platform, all teams must file a Veteran Support/Contact Center Review issue that includes a Product Guide. Product Video is optional but encouraged. The VSP Contact Center team will review these materials and share with the relevant contact centers to ensure that Veteran Support/Contact Center Representatives are prepared to answer questions about the new functionality._

## Resources

1. [Template for creating a product guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md)
2. Examples of product guides ([here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/templates/sample-product-guide-1.pdf) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/templates/sample-product-guide-2.pdf))

---
## Tasks
- [ ] Create a product guide for the burial 530EZ form
- [ ] Submit a request to the Contact Center to review the guide (see instructions [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md))

## Acceptance Criteria
- [ ] Approved product guide for 530EZ form
---
