### ISSUE TITLE
526 Architecture Diagram 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#74423]
## Issue Description
Diagram out 526 flow within and to/from other services.

Scope of this ticket is:
- Submit flow including external services being called, including back-up submission, documents upload, and ancillary forms
- Add other migrated endpoints, service calls and interactions 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Diagram of 526 flow within scope of this ticket
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
@mengA6 @aurora-a-k-a-lightning 
I've seen both of the architecture diagrams you both worked to produce. I know they are a little different, but are we able to consider this ticket complete? Or do we still have open questions?

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=5eec0a6b-0f42-4fac-a9ac-3d3beea72c8b

https://lucid.app/lucidchart/645d8a16-22de-4971-9626-198da0483430/edit?invitationId=inv_f335ce12-6583-4396-8892-0c33e67c8b9e&page=Ky8k5yKoOg9P#
