### ISSUE TITLE
NOD and SC | Fix maximum attachment size to match Lighthouse's API limits

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#74457]
## Value Statement
**_As a_** Veteran submitting a PDF that exceeds MB size requirements
**_I want to_** know when my file is too large as quickly as possible by seeing an error message
**_So that_** I can reduce the file size and successfully upload it.

---
## Background Context
- There is a maximum size limit of 100,000,000 bytes for evidence attachments. However, megabytes in Rails is defined as 2^20 which is 1048576 (i.e. `100.megabytes == 104_857_600.bytes`). Files that are between 100,000,000 and 104,857,600 bytes will not display a validation error during the form submission process but will fail upstream. This error accounts for [roughly 8%](https://docs.google.com/document/d/1FDWa9v1ooG4L__RODnAYZtcqCt4La1azTyZ6vkEr6KA/edit#heading=h.bblqm56b9rpq) of our downstream evidence upload errors.
- Uploader class: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/uploaders/decision_review_evidence_attachment_uploader.rb#L8C18-L8C27

## Acceptance Criteria
- [x] When a Veteran uploads a file that is over 100,000,000 bytes, they are made aware so they can fix the issue

## Designs and Build Notes
![B3C7E9C4-02B7-4F9E-808D-39AD71B42D8F](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90406121/1ff8130e-dd43-4de8-8cce-45d94559d1d4)

## Tasks
- [x] Update backend uploader class to use `100_000_000.bytes`
- [x] Update frontend to use 100,000,000 bytes
- [x] Update tests

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [x] Meets acceptance criteria
- [x] Passed E2E testing (90% coverage)
- [x] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [x] Code reviewed (internal)
- [x] Submitted to staging
- [ ] Reviewed and approved by product

**Comment by rocio-desantiago** [comment]
Pausing merging the fixes for this bug. 
Some of these results depending on if local, staging, or prod. 
I'd like to get clear on which message we want to stick with.
I ran into 4 different file errors:

| Environment and/or with fix or not | Error message
| ----- | ----- |
| NO FIXES | Document exceeds the file size limit of 100 MB |
Backend fix ONLY | We couldn’t upload your file because it’s too large. File size needs to be less than 95.4 MB | 
frontend fix ONLY | We couldn’t upload your file and/or We couldn’t upload your file because it’s too big. Please delete this file. Then upload a file that’s 95MB or less. |
BOTH FIXES | We couldn’t upload your file because it’s too large. File size needs to be less than 95.4 MB |

|All error messages
| ----- |
| <img width="500" alt="An image of a variety of file error messages" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/d81215f7-bbd3-4d19-8202-8e419b459a35"> |


@anniebtran found that this code isn't being used in staging or production, only locally.
`app/models/decision_review_evidence_attachment.rb`
| ----- |
| <img width="500" alt="Local file size error - backend message" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/213dfcab-6c21-4bcf-8c22-5806b2d835d1"> |

**Comment by saderagsdale** [comment]
@rocio-desantiago Thanks for flagging this. Let's talk about it tomorrow with @eileen-coforma when she returns.

**Comment by anniebtran** [comment]
To add on to Rocio's comment above — the [code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/decision_review_evidence_attachment.rb#L18-L21) that isn't being used on staging/production is a step for validating the uploads using Lighthouse's validation endpoint ([`/uploads/validate_document`](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)) and I think it already validates using [`100_000_000` MB](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/lib/vba_documents/document_request_validator.rb#L10). So it's possible that one part of the backend change is updating the environment variable so that we use Lighthouse's validation

**Comment by saderagsdale** [comment]
@anniebtran That makes sense. Definitely want to have parity across environments for testing purposes.

**Comment by rubensun** [comment]
Asking the user to delete and reupload files seems like unnecessary friction. Is this how we're handling this?
It's best to restrict uploads exceeding the allowable file size.

As far as the error goes. I'd recommend:
> The file you're trying to upload is too large. 100 MB is the maximum file size allowed. Check your file and try again.

**Comment by saderagsdale** [comment]
@saderagsdale discuss in refinement

**Comment by rocio-desantiago** [comment]
In this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27836): the minsize is updated so that at least the backend error shows up for the minimum size. Ideally we'd like Supplemental Claims error to match that of Notice of Disagreement as shown in this screenshot:
<img width="400" alt="NOD error for tiny PDF" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/37cc5dae-a294-4c70-957b-cf068996da2c">

**Comment by HeatherWidmont** [comment]
Platform reviewed. There is one failure but should clear so we can merge it. Will validate afterwards, likely in parking lot tomorrow.

**Comment by HeatherWidmont** [comment]
Eileen reviewed error message language with Julie & it looked okay. CAIA is also reviewing & will need a couple of days. @eileen-coforma will follow up with them on Friday.

**Comment by eileen-coforma** [comment]
@rocio-desantiago is it possible to also add a Frontend fix, so the Veteran doesn't have to delete the file manually?

**Comment by rocio-desantiago** [comment]
@eileen-coforma I had wondered about that. Let's write a new ticket to update that design pattern.

**Comment by HeatherWidmont** [comment]
Issue with staging, platform is working on fixing. Team will wait until its ready in staging to review

**Comment by saderagsdale** [comment]
Checked the slack thread, no changes yet.

**Comment by eileen-coforma** [comment]
@rocio-desantiago error messages approved by CAIA:

File is too large:
`We couldn’t upload your file because it’s too large. File size must to be less than 100 MB`

File is too small:
If we have to keep the delete file button, use the following:
`We couldn’t upload your file because it’s too small. Please delete this file. Try uploading a file that’s 1KB or more.`

If file is 0KB, is it possibly a blank file? If so, this is more accurate:
`The file you tried to attach is blank. Try attaching a different file.`

**Comment by saderagsdale** [comment]
@eileen-coforma Thanks for the content for large files. 

@rocio-desantiago @eileen-coforma let's move the content for small files to another ticket for refinement so we don't blow up the scope of this ticket. We need to know what happens to files that are too small. @data-doge Can you confirm how small a file must be to be considered "blank"? That may impact error messaging depending on file size, and that may require a spike.

**Comment by eileen-coforma** [comment]
Message still needs to be updated to the one approved by CAIA `We couldn’t upload your file because it’s too large. File size must to be less than 100 MB` 

Will validate again when that's complete.
