### ISSUE TITLE
EVSS - Remove Flipper flag and Logging for PCIU - 526ez Prefill

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#74462]
## Issue Description
Once the `disability_compensation_remove_pciu` [flag](https://github.com/department-of-veterans-affairs/vets-api/blob/ca3a4bcf2e116ba0eb45717bc0583a04d3e4aff9/app/models/form_profiles/va_526ez.rb#L133) has been turned on, and the success of the change has been verified, the flag (and the [logging](https://github.com/department-of-veterans-affairs/vets-api/blob/ca3a4bcf2e116ba0eb45717bc0583a04d3e4aff9/app/models/form_profiles/va_526ez.rb#L143)) can be safely removed.

## Tasks
- [ ] Remove the `disability_compensation_remove_pciu` from va_526ez.rb, such that it only calls `initialize_vets360_contact_info`
- [ ] Remove the logging statement described above
- [ ] Remove any unit tests in `form_profile_spec.rb` pertaining to the flag, as well as now-old PCIU-related functionality

## Acceptance Criteria
- [ ] Flag and logging (and unit tests) removed, with application functioning normally
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
per my discussion with @mchae-nava though the logging that we currently have here was meant to be temporary, we should consider adding more "long-term logging" and/or metrics (and perhaps even error handling?) in this area, so that more permanent monitoring/dashboarding can be left behind. This could either just be done within the context of THIS ticket, or maybe split off into another story
