### ISSUE TITLE
Investigate Issue raised by savon/bgs-ext update

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#74461]
### Description
Updating savon caused a notable failure in the 1010 Healthcare apps, when sending requests to HCA. [Healthchecks](http://sentry.vfs.va.gov/organizations/vsp/issues/250197/?environment=staging&project=3&query=is%3Aunresolved&statsPeriod=14d) to HCA and [requests from 1010 apps](http://sentry.vfs.va.gov/organizations/vsp/issues/222582/?environment=production&project=3&query=%22Common%3A%3AClient%3A%3AErrors%3A%3AHTTPError%22&statsPeriod=14d#threads) to HCA both failed, all noting the same error: `Couldn't create SOAP message due to exception: XML reader error: Duplicate declaration for namespace prefix 'tns'.` I'm aware of the duplicated namespace, but need to investigate what we can do so that requests are formatted properly

### Tasks
- [x] Determine why the requests are being formatted with duplicate `tns` namespaces
- [x] Make any adjustments (I believe it will be related to an HCA `wsdl` file
- [x] work with 1010 teams to re-record cassettes in review instances. (and potentially other teams as well)

### Acceptance Criteria
- [x] Cassettes are successfully re-recorded

**Comment by diondredroidios** [comment]
see below.

**Comment by ryan-mcneil** [comment]
Working on bumping bgs-ext and properly re-recording cassettes in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15646/files)

**Comment by ericboehs** [comment]
Blocked until we can figure out how to re-record the cassettes.

**Comment by ryan-mcneil** [comment]
PRs for re-recording [HCA](https://github.com/department-of-veterans-affairs/vets-api/pull/18115) and [Form1010](https://github.com/department-of-veterans-affairs/vets-api/pull/18154) cassettes.
