### ISSUE TITLE
[Payment History] Add statement data disclaimer for copays in combined debt portal

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#74460]
## Description

Currently, veterans are getting confused when they look at their copay statements and don't see any payment history. We need to add a notice/disclaimer that the information they're looking at only reflects the statement date and does not reflect real-time payment history.  

Scenario: A payment disclaimer is needed on copay pages stating that the real-time payment data is not available 

Given: A veteran looks at their copay statement in the combined debt portal
When: They want to see their most recent payment history
Then: They should see a notice saying that the data displayed is only statement data and not real-time.

## Tasks
- [x] Come up with a list of pages that need to be updated
- [x] Craft disclaimer copy
- [x] Update pages with disclaimer copy

## Acceptance criteria

- [x] List of pages has been approved by PO
- [x] Statement data disclaimer copy has been approved by PO
- [x] Pages have been updated with disclaimer copy

## Testing
- [x] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x]Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
These are the most likely pages that will need to be updated:

- **Copay balances overview page:** https://staging.va.gov/manage-va-debt/summary/copay-balances
- **Copay balance details page:** https://staging.va.gov/manage-va-debt/summary/copay-balances/eea5e722-ced7-4812-a5e9-d1d32472f986/detail
- **Copay balance statement detail page:** https://staging.va.gov/manage-va-debt/summary/copay-balances/eea5e722-ced7-4812-a5e9-d1d32472f986/detail/statement

**Comment by josephrlee** [comment]
**Mockup:**
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0QrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0493a3ef64f05c06a46dacba9da661d2c229d47a/Screenshot%202024-01-25%20at%2011.34.28%E2%80%AFAM.png" alt="Screenshot 2024-01-25 at 11.34.28 AM.png" />

**Current copy:**  
Your balance on May 4, 2022was $110.45. If you haven’t either paid your full balance or requested financial help, contact the VA Health Resource Center at 866-400-1238 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.

**Proposed disclaimer copy:** 
Your balance on October 11, 2023 was $105.24. **If you've already paid off your copay bill, the update will not reflect here until the next monthly statement is posted on {next statement date}.** 

Removing the last sentence on the current copy would be helpful in making it less confusing and more readable.

**Comment by josephrlee** [comment]
@denisecoveyduc , for this work, are we just updating and adding a disclaimer message to the copay paths? Or will this go on both overpayments and copays? It does seem like it should go in both places.

cc: @mgleo @charlottecesana

**Comment by denisecoveyduc** [comment]
Hi @josephrlee , Quick work on this!! Great job!  A few comments that will prompt some updates. 

- Veterans do not need to pay the balance in full. It is obviously recommended but not required. The way they have it written her suggests they 100% do.
- I don’t think we can tell when their next statement date will be. I will send you the January CPCC schedule in the slack thread. On that schedule you can see that statements are sent out by facility and don’t really follow a cadence from what I can see. So determining an exact date when a particular Veteran will receive their next statement is near impossible. 

Given these two comments let’s consider revising to something like…

**“Your balance on October 11, 2023 was $105.24. Any payment you have made since then will not reflect here until our systems are updated with your the next monthly statement"**

And I agree that this disclaimer should be in both places and I would like to update both VHA and VHA with the same clarity. 
I look forward to the next iteration

**Comment by josephrlee** [comment]
@denisecoveyduc, here is an updated version with the `va-card` styles being applied to it as well: <img width="1416" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19adc9c2f7e1d5e96e56bd57bb2f28f0c5037a79/Debt%20Card.png" alt="Debt Card.png" />

If this looks good, I can mockup what it would look like in all the different various places it'd go.

**Comment by denisecoveyduc** [comment]
@josephrlee that looks great to me! 🚀

**Comment by josephrlee** [comment]
@denisecoveyduc, here's a link to all the updated pages with the new disclaimer copy. 

https://www.figma.com/file/OiiDTTVTCf8j0GngRg0xxD/Combined-VA-Debt-Portal?type=design&node-id=43-914&mode=design&t=ajXx4YYESHu6A336-11

After working on it some more, we thought it'd be better to take the copy out of the actual card and instead put it as a sentence before the card.

**Comment by josephrlee** [comment]
@denisecoveyduc, after tinkering with it more, I came up with a couple of other variations for the details page. Which one do you think works the best?

Here are the screenshots: 

<img width="1416" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2M4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8987afa78b89c1bc53f0a861b0e6c2645b73cbd/Screenshot%202024-02-07%20at%203.41.25%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 3.41.25 PM.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2c4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f30a236b41947d9d8749fd6b0a2343ef6c99a4cc/Screenshot%202024-02-07%20at%203.41.40%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 3.41.40 PM.png" />
<img width="1592" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2s4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dda086ba831e8e7de80a7948a337407f43f7ccda/Screenshot%202024-02-07%20at%203.41.50%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 3.41.50 PM.png" />

cc: @mgleo @charlottecesana

**Comment by mgleo** [comment]
If we wanted to continue the phrasing used on other pages it could be "Updated on March 1, 2022. Payments after this date will not be reflected here."

In case the image isn't appearing, one of the previous pages, Debt and bill overview, says "Any payments you may have made will not be reflected here until our systems are updated with your the next monthly statement."

**Comment by charlottecesana** [comment]
I agree with the suggestions so far. The addition of the word "here" is important to signify that the payment is processed but not reflected in the debt portal. I also agree with Megan, that "reflected here" or "included here" sound more clear than "won't be shown".

**Comment by charlottecesana** [comment]
Also, I want to add that the word "reflect" might align more closely with mental models - I am seeing the word "reflect" in the Medallia survey feedback. I wonder if we can add another sentence of assurance, such as  "Updated on March 1, 2022. Payments after this date will not be reflected here, even if they have already been processed in the system." @josephrlee @mgleo @denisecoveyduc

**Comment by josephrlee** [comment]
Okay, thanks for all the great feedback y'all. I'll run with this sentence then as the final version: 
**Updated on March 1, 2022. Payments after this date will not be reflected here.**

@denisecoveyduc, does that sound good to you?

**Comment by denisecoveyduc** [comment]
@josephrlee That sounds amazing to me! Let's do it!!! 🚀

**Comment by josephrlee** [comment]
Great, this is ready to be marked as complete, have moved it to validate now!

@Tom-Davis @HeatherRienks

**Comment by josephrlee** [comment]
Closing this issue out! As I've merged the PR related to it!
