### ISSUE TITLE
Visualize new account creations associated with the Organic email

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#74476]
## Issue Description
_As a stakeholder in Login.gov adoption, I need to see qualitative data regarding how many users created Login.gov and ID.me accounts after receiving the Organic email so that I can determine the effectiveness of the email campaign and make informed decisions. _

---
## Tasks
- [x] _Configure DataDog to start tracking metrics related to newly added credentials for the Organic segment_
- [x] _Update the Domo Secure Sign-in Transition Email Campaign dashboard for the Organic email_
- [x] _Configure Domo with a daily datafeed to pull metrics from DataDog_
- [x] _Update Domo datafeed queries and DataDog dashboards to include eventType in criteria_
- [x] _Create Domo visualization of the account creations by CSP over time by day_

## Acceptance Criteria
- [x] _Domo Dashboard updated with a visualization of the account creations of the users who recieved the organic email._
- [x] _Display by CSP over time by day. _

**Comment by sdickson-gt** [comment]
Configured DD to capture and standardize attributes for new credentials added https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20AND%20%40logingovAdoption.eventType%3AnewCred&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1706201578338&to_ts=1706205178338&live=true

**Comment by sdickson-gt** [comment]
will follow up later to update dashboard with link to email.  Will also create separate ticket to update dashboard with additional views from SSOe and MPI data
