### ISSUE TITLE
Figure out Zenhub link permissions policy

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#74497]
- [ ] Ask Shira if everyone can see the zenhub board as linked to in [Design Intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent) or if only some people can see it
- [ ] Update [Design Intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent) as needed
- [ ] See if any other pages link to Zenhub boards
- [ ] Update those other pages if needed
- [ ] Figure out a general policy about Zenhub links
- [ ] Add that policy to the style guide and/or other how we work documents

## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@laucon can you please indicate where the ZenHub board link is on the Design Intent page, mentioned in the description?

**Comment by laucon** [comment]
@jknipes It's no longer there. A bunch of SMEs deleted that link and rewrote many parts of the page since we opened this ticket. So I think we can make this into a blank ticket since the problem got resolved on its own. :)

**Comment by jknipes** [comment]
Per the above comment, work is no longer necessary. Closing as _Done_
