### ISSUE TITLE
Alerting and Monitoring - Reinvest and Improve alerting standards on Va.gov

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#745]
## User Story
As a VA.gov team member, I want to have clear alerting and monitoring, so that I can see true problems and not have issues lost in the noise. 

## Goals
Improve our Alerting on VA.gov, so it is clearing for people who depend on it. 

## Measuring Success
- [x] Reduce noise 
- [ ] Proactive notifcations 
- [ ] update rules for Alerting
- [ ] Increase in customer NPS
- [ ] Reduction in volume of "non-human-needed" support requests month over month

## VSP OKRs 
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

**Comment by ricetj** [comment]
@ricetj  to connect with other work we will have in flight.

**Comment by jhouse-solvd** [comment]
@ricetj - Still relevant?

**Comment by ricetj** [comment]
This can be closed kept in mind for the DD migration.

**Comment by jhouse-solvd** [comment]
Defunct. Please see [THIS INITIATIVE](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13748) for current work related to improved monitoring (and alerting) solutions on the VSP.
