### ISSUE TITLE
[Backend] Technical Spike Debt Letters 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#7450]
## User Story or Problem Statement
Understand and prototype how to connect to eFolders using VBMS 

## Goal
_At the end of the technical spike there will be an understanding and prototype of how to connect with vbms that will allow the team to move along in development process.

## Objectives or Key Results this is meant to further
- _Ability to display debt letters on va.gov
---
## Tasks
- [ ] _Credentials to access vbms
- [ ] _Connect to vbms
- [ ] _Authenticate test user
- [ ] _Download | display document for test user 

## Acceptance Criteria
- [ ] _Connect to vbms 
- [ ] _Download document for given test user 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
