### ISSUE TITLE
10-7959f1 - Identify and implement form data to PDF mappings in the back end

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74518]
Complete the mapping file with how each property maps to a fillable field in the PDF. (May need to work with Don regarding specifics of work being done on 10-10d)
 
---
## Tasks
- [ ] Add a sample JSON payload in the back end for tests
- [ ] For non-fillable fields in the PDF, either regenerate the PDF to make them fillable or stamp the data using an x, y coordinate
- [ ] Add tests for the new model in the spec/ folder of the module
- [ ] Create vets-api pull request for internal and platform approval
- [ ] Merge pull request

**Comment by balexandr** [comment]
This is duplicate of https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/73933
