### ISSUE TITLE
Draft Custom Survey Form Aesthetics

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#74517]
## Issue Description
As a VFS Product team member, I need a mechanism to request a custom survey so that I can review user feedback relative to the identified URLs.  

Creating the 1st draft of the Custom Survey Request Form-
[Custom Survey Intake (DRAFT).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60f243b55e6a827f604a960d0e70c26f0dc1bc86/Custom%20Survey%20Intake%20%28DRAFT%29.docx)

## Tasks
- [x] use the existing Word doc draft
- [x] Team members will review draft - Steven, Camille, Sarifa, Aubrey and Anita 
- [x] Review final draft document 

## Acceptance Criteria
- [x] **Scenario 1: Reviewing the Draft Custom Survey Form**
  - [x] Draft Custom Survey Request Form
  - [x] Review by team members (Steven, Camille, Sarifa, Aubrey, and Anita)
  - [x] Team members should provide feedback on the draft

- [x] **Scenario 2: Creating the Final Document**
  - [x] Final draft Custom Survey Request Form
  - [x] Obtain stakeholders approval 
  - [x] Review final draft
  - [x] Create final document 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Team will review for final draft tomorrow.

**Comment by ATMiddleton** [comment]
Team collaborated and finalized internal steps determined the form requires updates including providing "standard questions".

**Comment by ATMiddleton** [comment]
Combined with #74620

**Comment by ATMiddleton** [comment]
Final draft review 2/7/24

**Comment by ATMiddleton** [comment]
2/7/24 - Team met to discuss next steps for form...  
@UXCamG will meet with platform team to confirm that the Custom Survey Request form can reside on https://depo-platform-documentation.scrollhelp.site/.  Additionally will confirm that form can contain a video instruction link.

**Comment by ATMiddleton** [comment]
The form has been updated to include sample approved questions.  

Next Steps - create video - on hold until Medallia 2.0 upgrade is complete
