### ISSUE TITLE
Epic: 10-7959f-1 FMP Registration - Back end build

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74510]
[Form Process Documentation as reference](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/form_process.md)

## **Description**
The Foreign Medical Program (FMP) is a Department of Veteran's Affairs' (VA) health care benefits program for Veterans with VA rated service-connected conditions that are residing or traveling abroad. FMP Registration [form](https://www.va.gov/find-forms/about-form-10-7959f-1/).

## **Product Outline**
Link to [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/foreign-medical-program/10-7959f-1/product-outline.md)

## **High Level User Story**
As a Veteran living overseas with a service related condition, I want to register online for the Foreign Medical Program so that I can receive health care services.

## **Hypothesis or Bet**
**If** we make this change **then** we expect to reduce the burden time it takes for the application to get to the business line to process it.
Create a better user and accessibility experience filling out an online application rather than a PDF

## **OKR**
As part of the IDEA Act, we are prioritizing forms that have the low complexity to build / high frequency of use and high impact to Veterans. 

## **Definition of done**

- [ ] The form will be available to fill out online from Find a Form and sent to PEGA for further processing

### Product

- [ ] Research
- [x] Identify Stakeholders 
- [ ] User Story & Workflow
- [x] Product Outline- github

### Design

- [x] Wireframes
- [ ] Walk through wireframes with the devs
- [x] Source of Truth
- [ ] Stakeholder review

### Collab Cycle Kick off

- [x] Create Collab Cycle Ticket
- [x] Product Outline
- [x] Channel #platform support

### Design Intent

- [x] Wireframes
- [x] Source of Truth
- [x] Schedule Meeting
- [ ] Implement Feedback for Design Intent

### Research review
- [ ] Research plan
- [ ] Conversation guide

### QA

- [ ] Manual Browser Test Plans in Test Rails
- [ ] Unit Tests
- [ ] End to end Tests Cypress
- [ ] QA test cases

### SiteWide Intake Form - Different Team

- [x] Create intake issue
- [x] Product Outline
- [x] Sketch Files
- [x] Source of Truth
- [x] #Ping sitewide-content.ai
- [ ] Implement feedback & breadcrumbs

### Midpoint Review

- [ ] Finalized Prototypes
- [ ] Source of Truth

### Analytics Review  (asynchronous)- Product - after coding is completed

- [ ] Create analytics ticket
- [ ] Product Outline
- [ ] Authenticated Test user Log ins
- [ ] Staging URL
- [ ] Document Page URL, interactions

### Staging Review

- [ ] Create Staging Review ticket
- [ ] Staging URL
- [ ] Staging User logins
- [ ] IA Intake Ticket linked
- [ ] Regression Tests
- [ ] End to end Tests
- [ ] Unit Tests
- [ ] Accessibility Tests- Open ticket

### Contact Center Review  (asynchronous)

- [ ] Product Guide

### Privacy Readiness Review (asynchronous)

- [ ] Create ticket
- [ ] Product Outline - Product
- [ ] Release Plan - Product
