### ISSUE TITLE
Make "operating status" and "operating notes" fields available to Facility Locator front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7452]
## User Story 
As a Veteran, I want to see facility specific operating status displayed in the Facility Locator so that I know how my facility's access might be impacted. 

## Goal
Facility specific operating status can be displayed. 

VHA has two concepts for this purpose: "operating status" and "operating notes". These fields will be made available in Drupal for all VA facility types and pulled in through the Facilities API. 
NOTE: Facility Locator currently uses Vets-API but they have a shared data source. 

We will need to display these status and associated details within Facility Locator search results and on facility detail pages. 

This is not intended as veteran facing filter at this time. 

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 

---

## Tasks
- [ ] Work with Lighthouse team to determine the best course for this work
      - Should the backend consume the information and make available to the front end?
      - Or should the frontend consume directly from Facilities API?
- [ ] Make "operating status" and "operating notes" available to front end for VA facilities

## Acceptance Criteria
- [ ] "operating status" and "operating notes" are available to front end
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This is blocked by the work in progress to make this info available via the API.
