### ISSUE TITLE
Research Label Organization for VFS Team Notifications

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74522]
## Description 
Context from Slack:

_i realized that I think we may need to look into creating our own label that is unique for VFS Team and VFS Team Member tickets.
I say this because it doesn't look like you can subscribe to multiple labels within the channel. At least from my testing so far. I think we may need to create a specific label that will be applied to both types of requests so were alerted on both.
For right now, I have it set to notify on the more common VFS Team Member tickets, versus the New VFS Team tickets as those are a lot less common.
Anyway rant over. I got sidetracked while working on the Atlas documentation. I'll have to look into this further in the near future._

Goals: 

The end goal is to have both the New VFS Team and New VFS Team Member tickets alert the platform-tech-team-notifications channel. Currently we are only alerted for New VFS Team Member tickets, which are way more common and important.

To do this you have to use a subscribe command for Slack/GitHub integration. I was doing some quick testing.
You subscribe by running the following command in the channel /github subscribe department-of-veterans-affairs/va.gov-team issues, +label:'new-vfs-team-member

GitHub is already integrated into the channel. So this command is essentially telling GitHub to provide any notifications from the VA org GitHub/va.gov-team repo for any issues that are tagged with the new-vfs-team-member label.
The issue I'm running into is I want to subscribe to another label new-vfs-team while also keeping alerts for new-vfs-team-member. That's the issue I'm running into. On a quick read of GitHub documentation, they make it sound like you can subscribe to multiple labels but that doesn't seem to be the case. I need to figure out how to have both types of tickets alert us in the notifications channel. The only solution I see from a quick glance is to create a new unique label that will be applied both types of tickets, IF your'e really limited to only subscribing to one label.
---

## Definition of Done
All tasks are complete below.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Research best practice for labeling to accomplish our goals
- [x] Implement strategy for accomplishing goals using labels
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
I realized that we can utilize the already existing 'platform-orientation' label. That label is set to be automatically applied when creating the following GitHub issues: "Platform Orientation Template", "New VFS Team", and "New VFS Team Member"

**Comment by bdech** [comment]
I'm going to change the GitHub label subscription in the channel, and test

**Comment by bdech** [comment]
New VFS Team Template notified in our channel
<img width="866" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1hQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0ae970462e1217deb37822e7758f7bdfd79ba98/image.png" alt="image.png" />

**Comment by bdech** [comment]
New VFS Team Template notified our channel<img width="896" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVhQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b92f0cb2deeee4c44794dabbf76afab021bb691/image.png" alt="image.png" />

**Comment by bdech** [comment]
Looks like the old Platform Orientation template has been sunset. I can no longer locate it listed as a template under "New Issue"

**Comment by alyssagallion** [comment]
VFS Team and VFS Member tickets are now routing to this channel: https://dsva.slack.com/archives/C06CY71PCAX

Closing.
