### ISSUE TITLE
Implement E2E Test Selection Changes

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74532]
## Issue Description
We discussed and decided on an approach for this change and now it needs to be implemented. This ticket serves as a carry-over for https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/72061 where this plan is detailed.

---
## Tasks
- [ ] Determine current method for test selection and test splitting
- [ ] Change selection to match unit test method of shared directory tests only
- [ ] Change number of containers to a consistent smaller number, ensuring to preserve a larger number for main CI runs where all tests will be run.
- [ ] Change the way tests are split to split evenly between each container, instead of putting 50 in each container resulting in some containers spinning up empty for no reason.

## Acceptance Criteria
- [ ] E2E test selection has been streamlined for feature branch merges while leaving the main branch in a state where all tests run.
---

**Comment by JoeTice** [comment]
Deprioritized due to daily deploy issues.

**Comment by CBonade** [comment]
Bumping up story points on this as there may be a bigger opportunity here to restructure our way we run cypress tests entirely, using the official Cypress github action. This would offload the responsibility of splitting up the tests to Cypress to do automatically without our overly-complicated script and allow us to get onto github-hosted runners. WIll require extensive testing, so putting a little extra time on this one.
