### ISSUE TITLE
Investigate What /Help Bot is Used For and Remove if Unnecessary 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74530]
## Description 
We recently noticed that there is a /help option in the support bot that is seemingly unnecessary. This ticket will house the task of identifying if that is true and removing the option if it is.

---

## Definition of Done
All tasks are below.

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Work with Clint to identify what the /help command is used for 
- [ ] If no longer useful, reach out to Alyssa/Erika to remove that option from support bot
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

<img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC85QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4cadb430e4c27ada9197e7a8da04555e1f29df9/Screenshot%202024-01-25%20at%2011.37.28%20AM.png" alt="Screenshot 2024-01-25 at 11.37.28 AM.png" />

**Comment by alyssagallion** [comment]
Removed. Closing.
