### ISSUE TITLE
Discovery: What GitHub Actions are being deprecated or are outdated?

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74542]
## Issue Description
We need to dissect the GitHub actions that are giving us warnings and errors and build ourselves a task list for what to update. The 4 main repositories we'll be concerned with are vets-website, content-build, qa-standards-dashboard-data, and product-directory. There are two types of updates, though both involve the same corrective action:

- Actions contain functions that are being deprecated and will not work after a certain time. We should make note, if we can find out, of when these deadlines are.
- Actions that are just outdated with new versions available. We should be proactive about updating these.

---
## Tasks
- [ ] Visit all 4 repositories and review workflows that have warnings and errors for any GitHub Actions. 
- [ ] Categorize these errors into deprecation warnings and old versions. For any deprecation warnings, attempt to locate and EOL date. Note: as we use many actions in many places, there may be cases of repeated actions in numerous locations.
- [ ] Write up tickets to correct these issues.
- [ ] If any other errors exist for issues that do not fall into these categories, make separate tickets to address these at a later time.

## Acceptance Criteria
- [ ] Our repositories no longer have warnings or errors related to deprecation or using outdated actions in GHA workflows.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/2924445826/GitHub+Actions+Upgrades
