### ISSUE TITLE
Vets API: Document how tracking of planned maintenance for Vets API is done

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74545]
## Issue Description
Because Platform Product currently does not have a dedicated status page, we have initiated the creation of a [maintenance window for Vets API](https://dsva.pagerduty.com/service-directory/P4VGI3W). This will serve as a method to record and monitor maintenance related activities and any associated downtime. 

This ticket is to document how the tracking of planned maintenance is done in the current state, and how it will be done if any changes are made to this maintenance window. 

The documentation on the planned maintenance will be kept here (doc site TK)

---
## Tasks
- [x] Confirm where the maintenance window is kept
- [x] Establish who is the owner of the maintenance window and its operations
- [x] Establish the maintenance process and schedule and who, if any, resources are involved
- [x] Test the maintenance process and assess any issues
- [x] Make any edits to the maintenance process
- [x] Retest as necessary
- [x] Finalize maintenance process
- [x] Document final maintenance process
- [x] Communicate final maintenance process to other teams and to stakeholders; share final documentation site with same group
- [x] Aparna referenced this IRBot Playbook as a request for the workflow

## Acceptance Criteria
- [ ] Final planned maintenance window documentation for Vets API

**Comment by jennb33** [comment]
Aparna referenced this [IRBot Playbook](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2851275379/Playbook+for+Maintenance+Windows+management+via+IRBot) as a request for the workflow

**Comment by jennb33** [comment]
@rjohnson2011 should have something for review today. IRBot is a Slackbot, and is an easy way to create maintenance windows and will be included in the documentation.

**Comment by rjohnson2011** [comment]
Documentation for Planned Maintenance in vets-api is in Review: https://vfs.atlassian.net/wiki/spaces/~527721881/pages/3027992592/Playbook+for+vets-api+Planned+Maintenance

**Comment by rjohnson2011** [comment]
Made requested revisions via Slack thread re: this PR - https://oddball.slack.com/archives/C045LCF8WU8/p1710787108127889
