### ISSUE TITLE
Atlas: Want to be able to re-sort list by name

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74551]
## Issue Description
- In Individuals --> +New Team Member. In the new team member form, the team selection box populates team names, but unsorted. It seems like the list is populated based on the most recently added record. Is it possible to have this list sorted alphabetically.
---
## Tasks
- [x] Change sort option to sort by Name, not Record ID, as a pre-sort option

## Acceptance Criteria
- [x] Users in Atlas will be able to sort by Name, Not Record ID
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] Attached to an Epic
- [x] Product Support
- [x] backend
- [ ] bug

<img width="1573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmIrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70451df781e112662e5e820134abb98cca01eaf6/image.png" alt="image.png" />

**Comment by RachalCassity** [comment]
Looking at this today.

**Comment by RachalCassity** [comment]
PR has been merged and tested.
