### ISSUE TITLE
EKS Upgrade Testing Plan: Step 4: Establish connectivity between vets-api and Redis/elasticache

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#74550]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

**From the [EKS Testing Proposal](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000631374/Vets+API+on+EKS+Automation+Discovery+and+Proposal)**: 
> As part of the current EKS upgrade process, comprehensive testing on various components of Vets API is essential in order to ensure seamless functionality and performance. Upgrading EKS can introduce changes that affect the behavior of deployed applications. Testing verifies that deployed applications remain compatible with any EKS changes. It ensures that all aspects of Vets API continue to operate as expected, without introducing regressions or unexpected behavior that could disrupt services for users. 
> 
> Because of future goals to conduct upgrades on a 3-6 month cadence, it is the Product Platform team’s goal to maximize the automation of these upgrade testing processes. By automating these tests, verification of successful upgrades is potentially expedited and the right amount of time for necessary adjustments can be allocated. The Vets API components that require testing are below, along with the potential automation strategies. The objective is to standardize testing methodologies across the platform, thereby eliminating the inconsistency of testing solutions across EKS applications.

Part Four of Testing plan - Establish connectivity between vets-api and redis/elasticache

Things to consider:
- at the moment we have to use port-forwarding to work with and test things in the cluster. Is this too much hurdle/inconvenience for beginning to work on this.
- we don't know the current state of the cluster. Has a redis cluster been created in AWS for this?
- Assuming the cluster exists, does the work for connecting to it merely have to be carried out, or have attempts been made at this, that haven't been fruitful?
- [ ] This will likely happen in an automated (K8) job

## Tasks
- [x] Evaluate the necessity and efficiency of port-forwarding for initial setup and testing.
- [x] Confirm the existence and status of the Redis cluster in AWS.
- [ ] If the cluster exists, establish connectivity between vets-api and Redis/ElastiCache.
- [ ] If attempts have been made previously, review and rectify the unsuccessful attempts.
- [ ] Secure and encrypt the connection in compliance with security standards.
- [ ] Conduct performance testing to ensure no bottlenecks are introduced.
- [ ] Document the connectivity setup, configuration, and troubleshooting guide.
- [ ] Document the steps that will need to be followed by the person doing the upgrade testing [in this Confluence document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test)
- [x] Add a **self.test_connectivity** method to the Redis store to the existing class [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/models/redis_store.rb)
- [x] Add a **self.test_connectivity** method to the Rails.cache
- [x] Add a **self.test_connectivity** method to Sidekiq

## How can this be automated
- [ ] Potentially create a cronjob that runs an ActiveRecord query - either a script or rake task
- [ ] Create Log-Based Alerts in Datadog - specify how notifications need to be received. **Edited 7/11 to add** that this should be added to the Postman test suite. 

## Success Metrics
- [ ] That Redis is working at 100%
- [ ] That an alert is sent via DataDog monitor if the connection fails 

## Acceptance Criteria
- [ ] **self.test_connectivity** method has been added to the three Redis instances
- [x] Successful Connectivity
- [ ] Configuration Validation: The configuration settings (like host, port, authentication) for Redis/ElastiCache are correctly set up and validated.
- [ ] Updated Documentation as necessary
- [ ] The documentation is updated with the necessary steps and instructions for this step.

**Comment by jennb33** [comment]
7/10 - we still need this work, per @LindseySaari. @rjohnson2011 will reprioritize. 
Controller for the Postgres check is [here](https://github.com/department-of-veterans-affairs/vets-api/blob/ddda4c32346d24b0c9b9cb0708e93e1077520b6a/app/controllers/v0/admin_controller.rb#L10), probably the Redis controller can go here too.

**Comment by jennb33** [comment]
7/11 update: @rjohnson2011 has identified the Redis clusters on Elasticache and will continue to test. Lindsey recommended creating a script and not worry about testing synthetics; then we will hand off to Reliability team who is actually executing the testing.

**Comment by jennb33** [comment]
7/17 update - Ryan and Lindsey are collaborating on this ticket and it should close in time for the Sprint ending at 1pm ET.

**Comment by rmtolmach** [comment]
I documented the step here (step 4): https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test
