### ISSUE TITLE
(PW) Sprint 103 Priorities & Candidates

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#74578]
# Sprint Priorities #

```[tasklist]
## 🥅 Goals 🥅
- [ ] 📣Drupal: #
- [ ] 📣FE:  #16976 
- [ ] 📣UX: #16867 
```
# Candidates for Sprint 102 (Jan 31, 2024 to Feb 13, 2024 )

#### Codeowners Set up for PW producs 

- [ ] **Value Prop**: To ensure rapid triage and fixing of defects resulting in a better Veteran experience, and to promote quick collaboration on products, ensure codeowners are properly identified for PW products in CMS. This will also facilitate a better transition for the new CMS team, as well as if PW team doesn't have the new contract in end of March.
   - [ ]  #1406

####  Defect (a11y): Invalid HTML for < ul > when adding Benefits Hub contacts
- [ ] **Value Prop**: Provide a better Veteran-facing experience by ensuring contact lists display correctly, thus rendering correctly when screen readers are used.
   - [x]  #12664

## Front-end

####V3 Components Opt-Out

- [ ] **Value Prop**: To ensure Veteran-facing products & wizards aren't adversely affected when the Design Team updates all V1 to V3 on February 26th, we are opting out, and then will strategically updated V1 components (which have a V3 counterpart) in our products to V3
   - [ ] #16976

#### Federal Standardized Header/Footer

- [ ] **Value Prop**: Continue build-out of the header, as well as forking injected header code, so we can quickly make any adjustments in order to meet March 25th in anticipation of possible contract shift, or if no contract changes, then to meet the April deadline/announcement.
   - [ ] #16815

#### Deprecate unused feature flags / toggles / flippers in FE and CMS

- [ ] **Value Prop**: Ensure possibly flaky Veteran-facing behavior doesn't occur because of outdated flippers. Work on 'Deprecate unused flippers...." stories in this epic #11530
   - [ ] #11872

####  Federal Standardized Header/Footer (Cindy)
- [ ] **Value Prop**: Provide better experiences to Veterans across the portfolio by adopting the new global OFCIO's Federal header/footer design, and also by improved performance.
   - [ ] #16374 
   - [ ] #16867 Phase 2 research sessions

####  Migrate Sketch files to Figma (Jordan)
- [ ] **Value Prop**: Update the styles and comments in the mockups and prototypes moved into Figma to ensure our UX folks are able to continue providing valuable designs for Veteran-facing projects. 
   - [ ] #16337 (this is the epic; Jordan will be chipping away at the associated stories)

####  Accessibility audi of Injected Header
- [ ] **Value Prop**: Ensure a better Veteran experience by ensuring the accessibility issues discovered aren't coming from the injected header itself, and if they are, tickets will be created to fix the issues.
   - [ ] #16948

   ```

 ``
