### ISSUE TITLE
Design for Health Care Application "status" update

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7457]
Related ticket Update the Health Care Application (HCA) to use new endpoint behavior #6466 and #7455

## Background

We need to figure out how to communicate the following three statuses to people who submit the health care application:

- **Received**: The application has been successfully received by the backend database.
- **Not received**: The application failed to send and was not received by the backend database.
- **Pending**: The application has been sent by the frontend but we're still waiting on a response from the  backend database.

Some things to consider:

- We already have a confirmation page, so there may not be anything else to do for the "Received state.
- We should have some sort of communication that submission is in progress. Idk if we show a spinning animation or "this may take a few seconds" message, but we might want to consider this if we don't.
- If an application is still pending, what should VA.gov show? What should the user do? 
- If the application fails to send, what should VA.gov show? What should the user do? 

## Tasks

- [ ] On staging, review the health care application submission process
- [ ] Regroup with Brad on his work
- [ ] Regroup with Lihan on how asynchronous application submissions work
- [ ] Review 526 flow to determine if we can just use that design
- [ ] Whether we can leverage 526 designs or not, provide updated designs for when/how we should show that an application has been received/not received/is still pending for the HCA.
- [ ] Review with team and make changes as necessary

## Acceptance Criteria
- [ ] Design has been completed

**Comment by Samara-Strauss** [comment]
This is no longer in this team's purview. Removing our team tags and moving to icebox.

**Comment by julieadair1** [comment]
@jparker0425 - is this something that needs to be prioritized?
cc: @dillo @batemapf
