### ISSUE TITLE
EVSS PCIU Migration: Address Controller Front End Discovery

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#74579]
## Issue Description
Discovery on PCIU usage was previously done on ticket [#64189](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/64189), and focused primarily on the pre-fill functionality. Some of that involved the [PCIU_Address](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/evss-pciu-migration-discovery.md#pciu_address) service, which was a wrapper around EVSS PCIU calls. Another consumer of this service is the [addresses controller](https://github.com/department-of-veterans-affairs/vets-api/blob/81e325eebaa92b3fbb1a9a938a9c60c8572fd454/app/controllers/v0/addresses_controller.rb), which _appeared_ to have no direct calls against it coming from vets-website by the 526ez application. There were, however, some evidence of their use by other applications due to some [tests](https://github.com/department-of-veterans-affairs/vets-website/blob/4d48aae81e266379427a34e80f21ae31a22aefd9/src/applications/letters/tests/02-keyboard-only.cypress.spec.js#L17) that were found. It is also possible that 526ez could be using address controller calls from other applications indirectly, and therefore could still be affected by an EVSS sunset.

Therefore, we'd like to do a more thorough investigation of the front end to have more confidence that all PCIU usage has been identified. If it is found that other applications are still using PCIU, we should inform the teams who are responsible for the affected code, so that they can then remove it in a more informed way. We should also explore using DataDog to track down address controller activity, in conjunction with front end code exploration.

---
## Tasks
- [ ] Identify any direct or indirect use of address controller calls from vets-website by the 526ez application
- [ ] If possible, identify any direct use of address controller calls by _other_ applications
   - [ ] Inform the relevant teams of this use via slack

## Acceptance Criteria
- [ ] Document all found address controller usage found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/evss-pciu-migration-discovery.md#pciu_address) (or start a new wiki)
- [ ] Create tickets to address any address controller usage by 526ez. Pun intended.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
@sethdarragile6 can this be closed?
