### ISSUE TITLE
[FSR] Update OMB exp date

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#74571]
## Issue Description
OMB information for FSR needs to be updated with expiration date
Date: `2026-11-30`  

Src: https://www.va.gov/vaforms/va/pdf/va5655.pdf 

---
## Tasks
- [x] Update OMB expiration date for FSR

## Acceptance Criteria
- [x] OMB expiration date has been updated
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
