### ISSUE TITLE
Redis POAM Discovery: dsva-vagov-rails-cache (Milestone 1)

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#74587]
## Problem

In order to reduce or even remove the need for downtime during future Redis upgrades of this cluster, we need to do discovery on whether or not the clusters will rebuild themselves if there is data loss. If this cache simply consists of things that the Rails framework caches, then we should be able to forego backups and take advantage of zero/near-zero downtime upgrades of these clusters.

## Questions to be answered

- [x] Are the contents of this cluster really just Rails framework-caches?
- [x] Given that we have one cluster, but many pods, how do the pods know which of the contents are their caches?
- [x] Given that we have one cluster, but many pods, how do they behave if the data is suddenly gone?
- [x] Do we write anything to the cluster independent of the Rails framework?
- [x] What changes would have to be made to make this cluster truly ephemeral (if any)?
- [x] How big is the cache in the middle of the night? Would there be zero downtime if it was done then?

## Tasks
- [x] Document findings from the questions above in a Confluence doc in the [Platform Product Team space](https://vfs.atlassian.net/wiki/spaces/PPT/overview?homepageId=2751725966)

## Success Metrics
- [x] Answering the Questions, above, into a comprehensive document

## Acceptability Criteria
- [x] That discovery is complete and documented with details.

**Comment by jennb33** [comment]
8/19 update: @Kshitiz-devops is trying to list the keys, but the user data doesn't have any prefixes. It's hard to list them without the prefixes. @LindseySaari will review it from the "looking through the codebase" angle.

**Comment by LindseySaari** [comment]
@Kshitiz-devops and I were able to analyze some of the data. It appears that there are over 100k keys in the cache around 1am, with even less from 3-4am ET. We are focusing on three specific key sets that require further assessment, which will involve consulting with the owning teams. The reason is that these keys can last anywhere from 12 to 24 hours. We need to evaluate the caching strategy to determine if the cache can rebuild itself without intervention and identify any potential consequences.

@Kshitiz-devops has been tasked with reaching out in the following channels.
`#debt-resolution`
`#vaos-engineering`
`#check-in-experience`

**Comment by LindseySaari** [comment]
The [discovery doc](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3389095967/Discovery+Vets+API+Rails+Cache) is complete. Closing!
