### ISSUE TITLE
[CST] Evidence submissions workaround for users without a BIRLS/File ID

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74586]
## Value Statement
**_As a_** user without a BIRLS/File ID on my account
**_I want to_** be able to respond to evidence requests made in CST
**_So that_** my submissions don't get lost to silent failures

---
## Background Context

Currently, users without a BIRLS/File ID are seeing tracked items evidence requests in CST. They are prompted to essentially take the same actions as any other user when it comes to submitting new evidence. Unfortunately, when these users submit documents the submissions end up failing downstream because Lighthouse/BGS cannot get the documents into the e-folder due to no File ID for the user being present. 

We need to implement a workaround solution for these users so that their submissions do not silently fail downstream. There are other means for folks to submit documents to VA and we should re-route these users to that service instead. 

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Acceptance Criteria
- [ ] _Users without a BIRLS File D who attempt to go to the evidence submission page are presented with a message letting them know that we're temporarily unable to process their requests via CST_
- [ ] _These same users are presented with the option to use X to process their request_
- [ ] _An alert and link is provided to Quicksubmit anywhere the file upload module previously was (file tab and evidence request response page) _
- [ ] - A new feature toggle should be created for this so we can test new solutions if needed.

## Design
- Design approach would be to create an alert replacement for every place that previously shows the evidence submission module, so one design.

## Engineering Notes
- Add here

## Out of scope
- Add here

## Open questions
- Are we currently tracking how many claims have 1P evidence requests? (Skyler)
- What, if anything, is the veteran seeing right now when it fails? (Skyler)
- Does it only fail via the "Request" page or will it also fail if veteran submits via Files tab? (Skyler) -

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
