### ISSUE TITLE
Redis POAM Discovery: Redis dsva-vagov-sidekiq (Milestone 1)

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#74589]
## Problem

Because the sidekiq Redis cluster is the most difficult to analyze in terms of efficient upgrades for **at least** the following reasons:

1. We're not owners of all of the code in vets-api, which means we don't know how robust the code is in terms of retry logic if a write to redis fails.
2. We don't know if the contents of the cluster will be recreated if data loss occurs.

It is important for the Platform Product team to better understand the potential for data loss. 

## Questions to Answer
- [ ] How realistic is it to get an overview of robustness of write failures
- [ ] How much of the data will be recreated if data loss occurs
- [ ] Given, we can't get clarity on the previous question, how can we **reduce** downtime? Right now, we have to make do a backup+upgrade such that there are no writes between the upgrade and the backup. How can we decouple the two?

## Tasks
- [ ] This may require a BE and DevOps resource
- [ ] Test what gets created when data is lost
- [ ] Is cluster mode an option?
- [ ] Timebox this effort to 2 days (approx) for discovery, then write up findings and share with team

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Definition of Done / Acceptance Criteria
- [ ] We want to know what we can do, if anything, or if the Redis cluster will always have to be upgraded the "hard way"
- [ ] (refer to [78048](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/78048) for other possible solutions)

## Documentation
- [ ] Documentation for the Sidekiq discovery can be found [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3426746609/Discovery+Vets+API+Sidekiq+Redis+dsva-vagov-sidekiq).

**Comment by flooose** [comment]
I think this story needs to be rephrased. 

I think the only real concern with sidekiq-redis is that any jobs that get queued **during** an upgrade that fails will have to be re-queued when we roll back to the backup that was created **prior** to them getting queued.

The focus on write failures in the description above isn't the problem because AWS offers near-zero downtime writes, i.e. shorter than any redis client-timeout should be.

See [this discussion](https://adhoc.slack.com/archives/C045LCF8WU8/p1706538875910319) for more context

**Comment by LindseySaari** [comment]
Placeholder doc created here: https://vfs.atlassian.net/wiki/spaces/PPT/pages/3426746609/Discovery+Vets+API+Sidekiq+Redis+dsva-vagov-sidekiq
