### ISSUE TITLE
EVSS PCIU Migration: Flipper flag and deploy to Prod/Stage

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74590]
## Issue Description
To prepare for the eventual sunsetting of EVSS, all calls to PCIU must eventually be removed from vets-api. During the course of discovery for Form526ez, it was discovered that calls to PCIU were being made in the [FormProfile base-class](https://github.com/department-of-veterans-affairs/vets-api/blob/0f17feca438f330f3122959116af00f28e84749b/app/models/form_profile.rb#L323) related to the [Pre-fill functionality](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill#VAFormsLibrary-HowtoworkwithPre-Fill-Vets-APIWork)- specifically to gather phone and email information. While Form526ez and many other forms intentionally use it in combination with their own derived Pre-fill classes, further digging through vets-api and in DataDog revealed that essentially every form in the system was calling out to PCIU. Either way, it became apparent that the scope of the problem was beyond just Form526ez.

The good news is that the base-class pre-fill is already calling out to VA Profile, which is widely considered the best one-stop source of all contact information within the VA. The specific reason we call out to PCIU here at all remains a mystery, although the best educated guess so far suggests that it may have to do with a potential lag between the time that the user enters/updates information and the time when it becomes available in VA Profile. In other words, if a user just updated their information and went straight to an application that uses Pre-fill, that information might not prefill in that application's form. This is just speculation, however, and there's a chance that if it WAS a problem when they added the PCIU calls 4-6 years ago, that latency might not be an issue anymore.

---
## Tasks
- [ ] Use a flipper flag to gate the removal of the base-class PCIU calls
- [ ] Deploy to Production/Staging with the flipper flag off (for Prod) and on (for Staging)

## Acceptance Criteria
- [ ] Flipper Flag is used to gate the removal of the base-class PCIU calls
---
## How to configure this issue
- [ ] EVSS PCIU Migration: Remove calls to PCIU in global Pre-fill
- [ ] Product Support
- [ ] backend, devops
- [ ] request

**Comment by RachalCassity** [comment]
This will be handled by the Benefits team and not related to the Platform Product Team

**Comment by jennb33** [comment]
Closing this ticket because it is not Platform Product work, per @RachalCassity's note above
