### ISSUE TITLE
EVSS PCIU Migration: Step 6e: Remove CIV2/PCIU related flipper flags 

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74592]
**CREATE DRAFT PR - CANNOT MERGE UNTIL Contact information V2 is successfully enabled in production**

## User Story
As a Platform eng, I want to fully enable the migration flippers and remove dead code, so that vets-api is fully off PCIU.

## Issue Description
The flipper related to this work should be turned on in Prod (and all lower envs). All code that was being run when the flipper was _off_ can be removed. 
**Flipper:**
- `remove_pciu`

## Tasks
- [ ] Confirm #104985 and #104987 are merged
- [ ] Create PR to remove flipper code from vets-api

## Acceptance Criteria
- [ ] PR to remove flipper code is merged
- [ ] Once PR is _deployed_, remove flipper from console in every env. (follow step 3 of [this section of this guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)) 

---
## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by RachalCassity** [comment]
Disability team is handing this, https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78244.

**Comment by jennb33** [comment]
Disability team ticket was closed 2 months ago (no specific date given). OK to close this ticket, @RachalCassity? 
cc: @lindsay-insco

**Comment by AshleyGuerrant** [comment]
@RachalCassity & @LindseySaari - is this ticket still relevant? Thanks in advance!

**Comment by RachalCassity** [comment]
Contact Information V2 has to replace PCIU in prod before PCIU references can be removed.

**Comment by AshleyGuerrant** [comment]
**Standup note:** Moving to blocked status. This work must start after the VFS & Mobile testing is complete, and after Step 6a-d is merged.

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** This work is blocked until the VFS & Mobile testing is complete, and after Steps 6a-d are merged. Moving out to Sprint 20, in case those dependencies are complete by then.

**Comment by AshleyGuerrant** [comment]
No critical bugs were identified while monitoring traffic in [Step 5.9](https://github.com/department-of-veterans-affairs/va.gov-team/issues/111164), this work is now unblocked. 🎉

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** This work is unfortunately blocked, and will roll over to another sprint. A Veteran-impacting issue with address validation was identified on 6/11 & is being discussed in #[vaprofile-vagov-addressoveride-issue](https://dsva.slack.com/archives/C090VB387SS). The sprint this ticket will be added to, depends on when the bug is fixed.

The SRE Team is supporting and pairing with The Authenticated Experience Team to resolve this issue promptly. After detailed investigation by the SRE Team, all signs point to the bug reported in this ticket not being fully resolved: [Allow users to update mailing address after successfully updating home address (VAProfile V2 validation_key requirement)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/109619).

cc @jwoodman5

**Comment by AshleyGuerrant** [comment]
@rmtolmach - thanks for consolidating those 2 tickets!
