### ISSUE TITLE
Add Any Items from Mural Board to Process Documentation for Zenhub/Github

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74599]
## Description 
Context: https://dsva.slack.com/archives/CU1E4CX9U/p1697741452532609
---

## Definition of Done
All tasks complete below.
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify if there are any process steps that we should move over to our best practices doc [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Sentry-access)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
