### ISSUE TITLE
Create Monitors for External Services That Will Alert on Synthetic Healthchecks That Fail 

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74605]
## Issue Description
As a backend developer, I want to see meaningful and accurate alerts on health check failures  for external services. These alerts should be accurate and in realtime, allowing us the opportunity to respond promptly.

By creating external service monitors that accurately reflect the errors, developers will be able to assess the severity of the error.

## Tasks
- [X] By getting input from the team, collectively confirm the type/s of alerting that would be beneficial for us to add, thinking specifically about what would be helpful when we're on-call or on Backend Support Rotation.
- [X] Rewrite this ticket with information collected.
- [x] Document best practices for choosing which endpoint/s should be used for these synthetic health checks, add information in Comments below.
- [ ] Integrate external service monitors that accurately reflect synthetic health check failures
- [ ] Implement alerting mechanism through Slack or PagerDuty (depending) to integrate with our current oncall rotations
- [ ] Alerts should provide sufficient information for developers to assess the severity of the error or failure, enabling prioritization of response efforts.

---
## Acceptance Critieria

- [ ] Create monitoring for synthetic healthchecks in Datadog as they apply to external services.
- [ ] Implement the integrated alerting mechanism with Slack and/or PagerDuty

**Comment by RachalCassity** [comment]
Created [PR](https://github.com/department-of-veterans-affairs/devops/pull/13913) for all monitors.

**Comment by jennb33** [comment]
This work might be redundant; @rmtolmach is going to do further research on the monitors then will work with @RachalCassity to determine the best way forward.

**Comment by rmtolmach** [comment]
I want to make sure this work doesn't overlap with what we currently have, which is: 
- an external service monitor for all external services. The query is `api_external_service_{{external_service}}_up`. [Datadog link](https://vagov.ddog-gov.com/monitors/manage?q=%22External%20Service%20Outage%22&order=desc) to all monitors.
- Four dashboards.
    1) [VSP - Breakers](https://vagov.ddog-gov.com/dashboard/7yz-4e3-6hs/vsp-breakers?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1710153287525&to_ts=1710167687525&live=true) you can see if an external service is up or down (in one graph)
    2) [Breakers - External Services - Success](https://vagov.ddog-gov.com/dashboard/i8s-xrp-yf6/breakers-external-services-success?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1710164085188&to_ts=1710167685188&live=true) to see trends over time (2 days or 1 week, for example) and to spot deviations in normal request traffic. 
    3) [Breakers External Services - Failures](https://vagov.ddog-gov.com/dashboard/ddc-w3t-mtf/breakers-external-services-failures?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1710164086791&to_ts=1710167686791&live=true) where you can compare to success chart for trend analysis.
    4) [Breakers External Services - Median Requests](https://vagov.ddog-gov.com/dashboard/bqf-7a8-t2z/breakers-external-services-median-requests?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1710164085845&to_ts=1710167685845&live=true). Not 100% sure exactly what this one does, but it could be useful in certain scenarios.

Alerting is not necessary for external monitors, since they're typically not actionable. I don't think adding a synthetic monitors for external service endpoints (there are > 50 of them) would be helpful. We already have so much information as-is. 

Closing.
