### ISSUE TITLE
[CST] File upload confirmation language change

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#74611]
## Value Statement
**_As a_** user uploading a file via CST
**_I want to_** understand that my file has been received by the VA and attached to the claim, even if the file doesn't immediately show up in CST
**_So that_** I can rest assured knowing my file has been added to the claim and I can go about my business without feeling the need to re-upload the file multiple times

---
## Background Context
Right now @jerekshoe is seeing some users uploading the same file multiple times, and theorizes it might have to do with the language in this banner. The "Note: It may take a few minutes for your file to show here" line is buried, which might be why users miss it and think they need to upload the file again.

[More context in this Slack thread
](https://dsva.slack.com/archives/C056854SVT8/p1706288144959889?thread_ts=1706284907.017799&cid=C056854SVT8)

## Acceptance Criteria
- [ ] _Update the wording of this banner so it makes it more immediately clear that the file might take a while to show up_
- [ ] _Make this file upload a "synchronous task" so that we can see if our wording solution impacts user behavior (we want to see fewer of the same file uploaded multiple times in a row)_

## Design

Current design
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a30d6e03567e929f3daf8a7972858dde93d677b/Screenshot%202024-01-26%20at%2010.21.51%E2%80%AFAM.png" alt="Screenshot 2024-01-26 at 10.21.51 AM.png" />

## Engineering Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
