### ISSUE TITLE
Video Instruction for Custom Survey Request Form

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#74618]
## Issue Description
As a User that is completing the Custom Survey Request Form that allows visitors to specified URLs, AI need a video describing the differences between the two survey options (Feedback button or intercept survey) and will aid in determining which survey will best suit the needs of my VFS product team. 

The video will document the User journey choosing the appropriate survey and how to include all information required to accurately complete the request form resulting in a custom Medallia survey to collect user feedback on identified URLs.   
---
## Tasks
- [ ] Determine video platform
- [ ] Compare and confirm form language 
- [ ] Create script 
- [ ] Create video and link 
- [ ] Determine placement of video link on form
- [ ] Embed OMB approved questions 
- [ ] Compare and confirm form language  
- [ ] 

## Acceptance Criteria
- [ ] Final version of form
- [ ] Published in Confluence 
- [ ] Public notification to VFS teams of form functionally and visibility 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Combined with #74620
