### ISSUE TITLE
EPIC - Request & Support Process

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#74622]
### Issue Description

Create processes & forms & dashboards to manage & fulfill requests from other va.gov Product Teams:

- Intake form
- Summation of the work we need to do

O4KR1: Develop request and support process for VA.gov product teams

[Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74622#issuecomment-1912447765)

```[tasklist]
### Tasks
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74676
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74677
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74683
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76158
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75458
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76068
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74688
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74791
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74792
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75144
```

**Comment by jimcconnelly** [comment]
[Here is the full Product Brief.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Product%20Briefs/Request%20%26%20Support%20Process.md)

**Comment by jimcconnelly** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8616c6731c14cad286c5fa49e2afe88af2008de/Request%20%26%20Support%20Process%2002-28-2024.png" alt="Request & Support Process 02-28-2024.png" />
