### ISSUE TITLE
Update Pages Mentioning Grafana, Loki, Prometheus

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#74635]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As an engineer, I need to know what monitoring systems are available so I can monitor the security and functionality of  on Platform.

## Hypothesis or Bet
If we make these changes on Platform Website, users will be aware of monitoring systems that are being retired and will be steered toward the most currently available tools.

## OKR
Platform Website regularly visited as the source for current information and processes.

## Definition of done

- [x] Pages updated to mention sunsetting of Loki, Granfana, and Prometheus
- [x] Pages provide links to requesting Datadog access
- [x] Review with SME for accuracy

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jknipes** [comment]
From Joe Tice in [recent Slack thread](https://dsva.slack.com/archives/C04B87D2QLS/p1706198727137769):

The messaging has been a little jumbled - but ultimately, the things that will be getting turned off as this change goes into effect are: Grafana, Loki, Prometheus, and Promtail

3 of these - Grafana, Loki, Prometheus all have pages on platform website

Prometheus - 17 pages
Loki - 11 pages
Grafana - 23 pages
These systems will be turned off on 1/30, but not completely removed until later

As a result, it feels like it may be prudent to do some sort or redirect, versus completely removing the pages

For example - arrivaing on a page for one of those tools, the first paragraph is something like...

PLATFORM UPDATE Jan 2024 - As of January 2024 this system is no longer operational, we encourage teams to utilize Datadog, for logging, monitoring and alerting. Access to Datadog can be requested through...
The remainder of the text on the page would remain below, but is perhaps grayed/dimmed out - until such time as those tools have been fully removed.

**Comment by jknipes** [comment]
All issues closed, pages updated and deployed. Moving to _Done_
