### ISSUE TITLE
CH 31/VRE | Update Confirmation Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#74636]
## Issue Description
_VRE stakeholders have requested that the copy within the confirmation email be updated to reflect longer processing times. The current copy states that, "We usually decide on applications within 1 week." The copy needs to be updated to reflect the current processing time._

[Email Text](https://docs.google.com/document/d/1Q7ns4wmVe8tO2N4CtUvj_li9jGMVJRq6vMskAs0rVZw/edit?usp=sharing)

---
## Tasks
- [ ] Confirm copy changes with VBA SME(s)
- [ ] Draft changes
- [ ] Complete CAIA review
- [ ] Complete stakeholder review of final draft (Emily, Julie S., VBA SME)
- [ ] Update text in VA Notify Template

## Acceptance Criteria
- [ ] Approved email copy from VBA and OCTO
- [ ] Updated email template in VA Notify
---
