### ISSUE TITLE
vets-api-mockdata: Remove eMIS 

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#74632]
### Summary
As part of the code deletion for eMIS, we'll need to delete eMIS references in vets-api-mockdata repo. Most of the references are in this one emis directory: https://github.com/department-of-veterans-affairs/vets-api-mockdata/tree/master/emis. The other references seem to be in `make_table.rb` and `mock_data_table.md`. It seems like you would delete emis references in `make_table.rb` and then run a command defined in the README that would update `mock_data_table.md` automatically. 

### Tasks
- [x] Delete all eMIS code in mockdata repo.
- [ ] Determine if the data needs scrubbed from git history, since it's emis information. 
- [x] Update the mock data table so it picks up the deletions from `make_table.rb`. Instructions [in the README](https://github.com/department-of-veterans-affairs/vets-api-mockdata/tree/master#update-the-mock-data-table).

### Acceptance criteria
- [ ] PR is merged
- [x] Mockdata is running fine for other services

**Comment by jennb33** [comment]
@RachalCassity is going to wait on this one until the exercise on mockdata is held on Friday 2/9

**Comment by RachalCassity** [comment]
PR in review. Waiting for mockdata recording Friday 2/9/24.

**Comment by RachalCassity** [comment]
https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/453

**Comment by RachalCassity** [comment]
@jennb33 Closed!
