### ISSUE TITLE
EKS Upgrade Testing Plan: Step 3: Establish connectivity between vets-api and Postgres/RDS

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74643]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

Part Three of Testing plan - Establish connectivity between vets-api and Postgres/RDS

**Tasks**
- [ ] Ensure Vets API can connect to Postgres
- [ ] Test in Rails console by accessing records
- [ ] Test a GET and PUT operation

**Things to consider:**

- what else?

**Comment by jennb33** [comment]
Dupe ticket, no points necessary
