### ISSUE TITLE
EKS Upgrade Testing Plan: Step 9: Logs & Monitoring

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74648]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

**From the [EKS Testing Proposal](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000631374/Vets+API+on+EKS+Automation+Discovery+and+Proposal)**: 
> As part of the current EKS upgrade process, comprehensive testing on various components of Vets API is essential in order to ensure seamless functionality and performance. Upgrading EKS can introduce changes that affect the behavior of deployed applications. Testing verifies that deployed applications remain compatible with any EKS changes. It ensures that all aspects of Vets API continue to operate as expected, without introducing regressions or unexpected behavior that could disrupt services for users. 
> 
> Because of future goals to conduct upgrades on a 3-6 month cadence, it is the Product Platform team’s goal to maximize the automation of these upgrade testing processes. By automating these tests, verification of successful upgrades is potentially expedited and the right amount of time for necessary adjustments can be allocated. The Vets API components that require testing are below, along with the potential automation strategies. The objective is to standardize testing methodologies across the platform, thereby eliminating the inconsistency of testing solutions across EKS applications.

### Part Nine of Testing plan - Logs & Monitoring

**Tasks**
- [x] Validate current Datadog monitor log in Vets-API to watch for errors
- [x] Validate current Sidekiq logs in Vets-API to watch for errors
- [x] Validate current Datadog monitor logs for both Vets API and Sidekiq to identify any errors or issues.
- [x] Consolidate the current Datadog monitor log in Vets-API and Sidekiq logs into a dashboard
- [x] Document the steps that will need to be followed by the person doing the upgrade testing [in this Confluence document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test)

**Things to consider:**
- [x] This will be the construct/customization of a dashboard, so no automation

**Ideas**
- Create a customized Datadog Dashboard for Vets Next. Things like error rates, hpa, filter by any error related logs, sync failures, etc will need to be monitored.

**Acceptance Criteria**
- [x] Datadog logs are present in Vets-API and watching for errors
- [x] Sidekiq logs are present in Vets-API and watching for errors
- [x] Regularly cadenced reports are being run from Datadog and Sidekiq from Vets-api for errors
- [x] The documentation is updated with the necessary steps and instructions for this step.

**Comment by rmtolmach** [comment]
I'm making progress on [the new dashboard](https://vagov.ddog-gov.com/dashboard/fzt-nkc-8x9?fromUser=false&refresh_mode=sliding&from_ts=1737929900145&to_ts=1738102700145&live=true). 

I created the following new monitors:
- [[vets-next] Puma Backlog](https://vagov.ddog-gov.com/monitors/315020)
- [[vets-next] Pods are down in {{kube_cluster_name.name}}](https://vagov.ddog-gov.com/monitors/315032)
- [[vets-next] Db-migrate failing](https://vagov.ddog-gov.com/monitors/315034)
- [[vets-next] - {{env.name}} - {{kube_deployment.name}} - {{container_name.name}} - High CPU Utilization](https://vagov.ddog-gov.com/monitors/315043)

Alerting sent to #platform-product-eks-upgrade-testing-alerts. The new ones all have the tag ["env:vets-next"](https://vagov.ddog-gov.com/monitors/manage?q=tag%3A%22env%3Avets-next%22&order=desc).

I didn't see any data available for Sidekiq in the vets-next cluster. 

I will finish up the dashboard tomorrow.

**Comment by rmtolmach** [comment]
Closing. [Reviewed by LIndsey](https://adhoc.slack.com/archives/C045LCF8WU8/p1738182653686079?thread_ts=1738170074.119619&cid=C045LCF8WU8).
