### ISSUE TITLE
EKS Upgrade Testing Plan: Step 7: Verify Sidecar containers

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74647]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

**From the [EKS Testing Proposal](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000631374/Vets+API+on+EKS+Automation+Discovery+and+Proposal)**: 
> As part of the current EKS upgrade process, comprehensive testing on various components of Vets API is essential in order to ensure seamless functionality and performance. Upgrading EKS can introduce changes that affect the behavior of deployed applications. Testing verifies that deployed applications remain compatible with any EKS changes. It ensures that all aspects of Vets API continue to operate as expected, without introducing regressions or unexpected behavior that could disrupt services for users. 
> 
> Because of future goals to conduct upgrades on a 3-6 month cadence, it is the Product Platform team’s goal to maximize the automation of these upgrade testing processes. By automating these tests, verification of successful upgrades is potentially expedited and the right amount of time for necessary adjustments can be allocated. The Vets API components that require testing are below, along with the potential automation strategies. The objective is to standardize testing methodologies across the platform, thereby eliminating the inconsistency of testing solutions across EKS applications.

Part Seven of Testing plan - Verify Sidecar containers

**Tasks**
- [x] Verify ClamAV is still working as expected
- [x] Check that socat is sending metrics properly (This relates to [Logs & Monitoring](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/74648))
- [x] Document the steps that will need to be followed by the person doing the upgrade testing [in this Confluence document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test)

**Things To Consider**
- [x] This will likely happen in an automated (K8) job for ClamAV - here's how this could be automated:
- [ ] ClamAV: Run a rake task that sends a request to clamav (just use the clamav client wrapper in Vets API). We could then Create Log-Based Alerts in Datadog for a failure. Our readinessProbe may take care of checking the connectivity though? 
- [ ] The new env can be added to this monitor potentially: https://vagov.ddog-gov.com/monitors/203466?view=spans
- [ ] SOCAT: Does our readinessProbe take care of verifying connectivity?
- [ ] Need to verify if SoCat can be automated with @ph-One 
NOTE: This work can be done concurrently with tickets [74633](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/74633) and [7464](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/74644)

**Ideas**
- [x] The two sidecars are socat proxy and clamav

**Success Metrics**
- [x] SoCat proxy is running and sending metrics
- [x] ClamAV is running
- [x] Monitors are set up and functioning for both SoCat and ClamAV

**Acceptance Criteria**
- [x] ClamAV is verified to be working as expected
- [x] Socat is sending metrics properly and they are double-checked.
- [x] The documentation is updated with the necessary steps and instructions for this step.

**Comment by jwoodman5** [comment]
Went over details around ClamAV and SoCat. Got good understanding around setting up some of the automated checks.

**Comment by jwoodman5** [comment]
PR is up.

**Comment by jwoodman5** [comment]
@Kshitiz-devops Please validate all tasks and A/C are done (check them off) once complete and close to the issue out by end of day (if complete).

**Comment by Kshitiz-devops** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3173/files
https://vagov.ddog-gov.com/monitors/294277
https://vagov.ddog-gov.com/monitors/294231
