### ISSUE TITLE
EKS Upgrade Testing Plan: Step 11: Scaling

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74653]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

**From the [EKS Testing Proposal](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000631374/Vets+API+on+EKS+Automation+Discovery+and+Proposal)**: 
> As part of the current EKS upgrade process, comprehensive testing on various components of Vets API is essential in order to ensure seamless functionality and performance. Upgrading EKS can introduce changes that affect the behavior of deployed applications. Testing verifies that deployed applications remain compatible with any EKS changes. It ensures that all aspects of Vets API continue to operate as expected, without introducing regressions or unexpected behavior that could disrupt services for users. 
> 
> Because of future goals to conduct upgrades on a 3-6 month cadence, it is the Product Platform team’s goal to maximize the automation of these upgrade testing processes. By automating these tests, verification of successful upgrades is potentially expedited and the right amount of time for necessary adjustments can be allocated. The Vets API components that require testing are below, along with the potential automation strategies. The objective is to standardize testing methodologies across the platform, thereby eliminating the inconsistency of testing solutions across EKS applications.

Part Eleven of Testing plan - Scaling

## Description
As part of the ongoing EKS upgrade, we need to ensure that the scaling operations of the Vets-API are robust and responsive. This part of the testing plan focuses on verifying the functionality and performance of scaling, particularly in the context of the HPA.

**Tasks**
- [ ] Test that scaling operations function as expected. This could most likely go hand in hand with the [load testing](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/74651). 
- [ ] If load testing is not feasible, explore manual scaling options
- [ ] Outline Scaling process tasks
- [ ] Validate HPA Performance
- [ ] Document the steps that will need to be followed by the person doing the upgrade testing [in this Confluence document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test)

**Ideas**
- Team-wide alert when there are ExternalMetric (CRD) failures via Datadog logs

**How Can This Be Automated?**
- Should be able to generate sufficient load with the load testing that we trigger a scale up event. Is there an API that could be incorporated into a test to verify the number of pods? Yes, Datadog metrics could be used for pod counts

**Acceptance Criteria**
- [ ] Successful Scaling Execution
- [ ] HPA functions seamlessly
- [ ] The documentation is updated with the necessary steps and instructions for this step.

**Comment by AshleyGuerrant** [comment]
**Standup note:** This work is blocked, There is no ingress to the cluster, so there is no URL to send the request (there is no available endpoint).
