### ISSUE TITLE
EKS Upgrade Testing Plan: Step 2: Verify Manifest Versions

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74655]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

Part Two of Testing plan - Verify Manifest Versions

**Tasks**
- [x] Ensure the manifest versions match the deployed manifest versions in ArgoCD. Manifest versions will automatically upgrade in ArgoCD so we want our manifest template versions to match.
- [ ] Document process of checking manifest version against deployed manifest version. 

**Things to consider:**
- [ ] Need to verify that this can be automated

**Acceptability Criteria**
- [x] Versioning is correct and matches the manifest and helm chart versions

**Comment by RachalCassity** [comment]
Documentation was added to the [Backend Support Responsibilities](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities)
<img width="877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70690b501f4eac920daf30a2287c28c96f2d973d/Screenshot%202024-02-27%20at%202.21.21%20PM.png" alt="Screenshot 2024-02-27 at 2.21.21 PM.png" />

**Comment by RachalCassity** [comment]
This probably should not be completely automated. 
1. PR approved 
2. PR merged
3. Create PRs to update manifest versions for all environments in the manifest repo. (This should not be automated to ensure lower environments deploy)

**Comment by RachalCassity** [comment]
Automation Process: 
https://vfs.atlassian.net/wiki/spaces/PPT/pages/2988441717/EKS+Upgrade+Testing+Plan+-+Automate+helm+versioning

**Comment by RachalCassity** [comment]
Also added directions on how to verify manifest versions in [Backend Responsibilities ](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#How-to-Verify-Manifest-Versions)

**Comment by RachalCassity** [comment]
Looking at this issue: https://github.com/argoproj/argo-cd/issues/12901

**Comment by RachalCassity** [comment]
Created this ticket to address warnings when building helm charts locally, [Fix 'cannot overwrite table' warnings when building vets-API manifest](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/77350)

**Comment by RachalCassity** [comment]
There is an ArgoCD feature request to have a warning when using an outdated apiVersion. Apparently the apiVersion warnings are shown when building manifest with kubectl, `kubectl get secretproviderclass <name> -o yaml`.  

ArgoCD automatically upgrades the manifest with the latest apiVersion without showing the warning. Kubernetes will not upgrade the apiVersion of an object even if you provide it with a newer apiVersion. There might be a way to run kubectl commands in a github action to alert us to upgrade the apiVersion.
