### ISSUE TITLE
EKS Upgrade Testing Plan: Step 12: Rolling Deploys

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74654]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

**From the [EKS Testing Proposal](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000631374/Vets+API+on+EKS+Automation+Discovery+and+Proposal)**: 
> As part of the current EKS upgrade process, comprehensive testing on various components of Vets API is essential in order to ensure seamless functionality and performance. Upgrading EKS can introduce changes that affect the behavior of deployed applications. Testing verifies that deployed applications remain compatible with any EKS changes. It ensures that all aspects of Vets API continue to operate as expected, without introducing regressions or unexpected behavior that could disrupt services for users. 
> 
> Because of future goals to conduct upgrades on a 3-6 month cadence, it is the Product Platform team’s goal to maximize the automation of these upgrade testing processes. By automating these tests, verification of successful upgrades is potentially expedited and the right amount of time for necessary adjustments can be allocated. The Vets API components that require testing are below, along with the potential automation strategies. The objective is to standardize testing methodologies across the platform, thereby eliminating the inconsistency of testing solutions across EKS applications.

Part Twelve of Testing plan - Rolling Deploys

**Tasks**
- [ ] Ensure the rolling deploy/sync function as expected
- [ ] Document the rolling deploy and sync function
- [ ] Document the steps that will need to be followed by the person doing the upgrade testing [in this Confluence document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3127246924/Steps+for+EKS+Upgrade+Test)

**Things to consider:**
- [ ] Need to verify that we have autosync enabled
 
**Ideas**
- This will just be part of the automated sync that can alert on any sync failures.
- We will need to update the GHA to update the Vets Next Vets API deployment image tag. I think this points to dev manifest currently though. Do we need to create a separate deployment?

**How Can This Be Automated?**
- [ ] Automated alerts based on sync failures or pod startup failures

**Acceptance Criteria**
- [ ] Successful Deployment
- [ ] Zero downtime
- [ ] Monitors/metrics show successful rollout, surge and scale back
- [ ] The documentation is updated with the necessary steps and instructions for this step.
