### ISSUE TITLE
Update all content to include "claims agents"

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#74650]
### Description
The ARM team decided to add "claims agents" to their Find and Appoint tool experiences. As a result, we need to update all content sources of truth.

### Resource
- [ARM content source of truth folder](https://dvagov.sharepoint.com/:f:/s/SitewideCAIA/EpKqFTllvlxOkDwz2iFgveAB9PjkKVIrJu_TUAkQPbsU0g?e=3Wg6Yj) (VA SharePoint)

### Tasks
- [x] AP: Update FAR landing page
- [x] AP: Update FAR tool
- [x] AP: Update AAR landing page
- [x] AP: Update AAR tool
- [x] AP: Update FAQ page

### Criteria
- [x] All content sources of truth have been updated

**Comment by aprocik1** [comment]
@oddball-lindsay, I created this ticket to track our work adding "claims agents" back into the experience. Here are the deliverables:

- **FAR landing page:** Updated [content source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/Eb0oXSPfIKxNlk5kRpz2nlUBNgioo9un0y68qJqQB6oQ8w?e=hFWbm2), updated [preview in Drupal](https://preview-prod.vfs.va.gov/preview?nodeId=62667)
- **FAR tool:** Updated [content source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EYHe12WNygRCngnaZ0jfXJEBj7b-qJIp9N6NZJyGFnVfRw?e=cMAeyt), updated [comments in Figma](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=0-19109&mode=design&t=ocj4sBcGkMFIBAft-0)
- **AAR landing page:** Updated [content source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EdOZHzu6ngdBh3jRCVzr8mMBMHYbjLSHM8kMmlBOZqBZnw?e=fjhuEs)
- **AAR tool:** In our [ARM / CAIA canvas](https://dsva.slack.com/docs/T03FECE8V/F065KP8MRHA), we agreed on a March timeline for this update. I may make a first round of edits before then, as time allows.
- **FAQ page:** Updated [content source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EWB1vmeODcFMgZP2UcYKUCUBBnCOk9_Bs1Fvhkc45nr79g?e=wiAjXk), updated [preview in Drupal](https://preview-prod.vfs.va.gov/preview?nodeId=63990)
   - Note: The FAQ page is a work in progress. The content and design are likely to change before FAR launch.

**Comment by oddball-lindsay** [comment]
@aprocik1 here are content collab opportunities based on our research study of the Appoint authenticated flow.  Also included are some ideas from the ARM team (we had a brainstorm after research findings were presented, to ideate on potential solutions).  We have our meeting tomorrow to review, discuss, and continue to ideate -- together this time!

**On the landing page, how might we inform Veterans about what representatives do, their differences, and the processes surrounding them?**
- Ideas included:
  - Numbered process list
  - Additional info components
  - Have a step before the Find a Rep CTA that links to the FAQ

**On the widget, how might we address Veterans unawareness that VA does NOT assign representatives and / or are confused why a representative’s there?**
  - Top idea was to place a disclaimer in widget linking to FAQ

**On the permissions pages, how might we provide additional context to help users understand the legal purpose of permissions?**
  - Top idea is to work with CAIA to find an eloquent way to provide legal reasons to Veterans
    - Will want to confirm wording with stakeholders

**How might we decrease drop-off on the review & final page by addressing non-digital submissions and improving user guidance?**
  - Top ideas included:
    - More clearly setting expectations earlier in the process, especially on the ‘Fill out your form …’ page
    - Swap the ‘Print Form’ button to ‘Download’, ‘Generate Form’, or another standard confirmation page option
    - Combine steps to have 1/ Print and sign and 2/ Representative sign and submit
      - With optional information on how to submit if your representative cannot do so

Also to consider: **Can we slim down the "form landing page"?**  Current mobile experience is all headers and feels a bit redundant.

**Comment by aprocik1** [comment]
Added this ticket to the sprint tracker
