### ISSUE TITLE
Reformat Pages in Platform Team Confluence

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74662]
## Description 
The purpose of this ticket is to formalize content on each of our Platform Team content pages in Confluence for easy searching. Additionally, we want to remove any duplicate content.
---

## Definition of Done
All of the work below is complete.
---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Review content in our Platform Team Confluence and make sure formatting matches on each page
- [ ] Archive any pages we no longer need
- [ ] Identify duplicate pages in other spaces that could be pointed to (our content should specific to our Platform Support space and responsibilities) 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Pulled into this sprint since I had some time. Work complete and closing!
