### ISSUE TITLE
fix error: "service_account_key" has been deprecated

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74669]
## Issue Description
The error `"service_account_key" has been deprecated.` appears in a number of GitHub actions across the front end repositories. This error needs to be corrected for the stability and reliability of our pipeline.

---
## Tasks
- [ ] Update workflows across front end repositories to eliminate this error from appearing.
- [ ] Ensure that the workflows still function appropriately after updating.

## Acceptance Criteria
- [ ] All workflows are functioning as expected with this error removed.
