### ISSUE TITLE
fix error: The following actions uses node12 which is deprecated and will be forced to run on node16

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74668]
## Issue Description
The error `The following actions uses node12 which is deprecated and will be forced to run on node16: aws-actions/configure-aws-credentials@v1, marvinpinto/action-inject-ssm-secrets@v1.2.1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/` appears in a number of GitHub actions across the front end repositories. This error needs to be corrected for the stability and reliability of our pipeline.

### Repos
Estimating 5-10 workflows per repository

- `vets-website`
- `product-directory`
- `qa-standards`

---
## Tasks
- [x] Update workflows across front end repositories to eliminate this error from appearing.
- [x] Ensure that the workflows still function appropriately after updating.

## Acceptance Criteria
- [x] All workflows are functioning as expected with this error removed.
