### ISSUE TITLE
Fix error:  The v0 series of google-github-actions/auth is no longer maintained

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74665]
## Issue Description
The error `The v0 series of google-github-actions/auth is no longer maintained.` appears in a number of GitHub actions across the front end repositories. This error needs to be corrected for the stability and reliability of our pipeline.

---
## Tasks
- [ ] Update workflows across front end repositories to eliminate this error from appearing.
- [ ] Ensure that the workflows still function appropriately after updating.

## Acceptance Criteria
- [ ] All workflows are functioning as expected with this error removed.

**Comment by CBonade** [comment]
Done and PR open for review!
