### ISSUE TITLE
Fix error: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74667]
## Issue Description
The error `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, aws-actions/configure-aws-credentials@v1, marvinpinto/action-inject-ssm-secrets@v1.2.1, actions/setup-node@v3, google-github-actions/auth@v0, google-github-actions/setup-gcloud@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.` appears in a number of GitHub actions across the front end repositories. This error needs to be corrected for the stability and reliability of our pipeline.

---

## Relates to
- https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/74668

## Tasks
- [x] Update workflows across front end repositories to eliminate this error from appearing.
- [x] Ensure that the workflows still function appropriately after updating.

## Acceptance Criteria
- [x] All workflows are functioning as expected with this error removed.

**Comment by CBonade** [comment]
The action actions/create-release is no longer maintained by GitHub and there are no updates available for it. This will require its own ticket.

The lighthouse action breaks the workflow when updated. This will need to be handled as a separate ticket to figure out how to alter our workflow to work with the new version.
