### ISSUE TITLE
Fix error: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74673]
## Issue Description
The error `The "set-output" command is deprecated and will be disabled soon. Please upgrade to using Environment Files.` appears in a number of GitHub actions across the front end repositories. This error needs to be corrected for the stability and reliability of our pipeline.

---
## Tasks
- [ ] Update workflows across front end repositories to eliminate this error from appearing.
- [ ] Ensure that the workflows still function appropriately after updating.

## Acceptance Criteria
- [ ] All workflows are functioning as expected with this error removed.

**Comment by CBonade** [comment]
Duplicate issue. Closing
