### ISSUE TITLE
After other errors have been corrected, create tickets for any of these errors that remain:

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74679]
## Issue Description
There's a handful of other errors that are outputting right now in GitHub actions that don't appear on the surface to be related to oudated actions:

```
Security advisory: Title: Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code Module name: @babel/traverse Dependency: styled-components Path: styled-components>@babel/traverse Severity: critical Details: CVE-2023-45133 - GitHub Advisory Database 

Security advisory: Title: Unauthenticated Denial of Service in the octokit/webhooks library Module name: octokit Dependency: octokit Path: octokit Severity: high

Testing Reports - Unit Tests
Error: Missing message content, please input a valid payload or message to send. No Message has been send.

The gcloud CLI is not authenticated (or it is not installed). Authenticate by adding the "google-github-actions/auth
```

Once the other errors related to outdated actions are solved, any of these that remain will need tickets to resolve in a future epic.
---
## Tasks
- [x] Resolve other errors related to actions being out of date
- [x] Check to see if all these errors still exist around different workflows in front end repositories
- [x] If any still remain, create tickets for each error to resolve them.

## Acceptance Criteria
- [x] New tickets exist to clean up any outstanding errors.
