### ISSUE TITLE
Split logging of feature branches and main CI for linting. Disable warnings in main CI.

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74687]
## Issue Description
Logging out 12,000+ linting errors in our main CI creates some delays and causes the job to take longer than necessary.  However, because the script file is shared between CI and feature branch linting annotations, disabling the warnings makes it where warnings don't show up on feature branches. Ideally, we'd like to leave warnings showing up on feature branches while removing them from the console output in CI. This will need to be controlled via an environmental variable, or split into a separate script entirely.

---
## Tasks
- [x] Determine best approach for splitting feature branch linting annotations from the linting output in main branch CI
- [x] Split the code
- [x] Ensure that feature branch annotations still show up where appropriate, while logging is removed from main branch CI for warnings (leaving errors still showing).

## Acceptance Criteria
- [x] Logging has been removed from main branch CI with no impact to feature branch linting annotations.
