### ISSUE TITLE
Combine Unit Tests and Unit Test Stress Test Jobs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74684]
## Issue Description
The goal here is to cut the number of runners that are used down to a minimum by combining these two processes. The changes here would determine whether or not a stress test is needed, and divide up tests accordingly.

Note: This concept was proposed before we had to change the way we ran unit tests. It is possible we can no longer do this, so the feasibility will need to be reassessed.

---
## Tasks
- [x] Assess feasibility of if these jobs can still be combined.
- [x] If possible, combine these steps
- [x] Test all scenarios to ensure nothing has been broken unintentionally.

## Acceptance Criteria
- [x] An approach has been determined for unit test jobs in CI
- [x] The jobs have either been left alone, or combined appropriately.
