### ISSUE TITLE
Combine E2E and E2E Stress test jobs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#74685]
## Issue Description
The e2e regular run and stress test run could be combined to cut down on the number of runners used per workflow. The determination could be made whether the stress test needs to run or not, and the process can be adjusted accordingly to run those tests in one shot instead of having it at two separate places, using double the runners.

---
## Tasks
- [ ] Determine approach for combining E2E jobs.
- [ ] Implement logic to check during test selection if a stress test is needed.
- [ ] Combine jobs and test stability of the CI workflow.

## Acceptance Criteria
- [ ] The CI workflow now only has one E2E job that handles all relevant E2E testing.

**Comment by JoeTice** [comment]
Deprioritized based adjustment to DORA metric focus
