### ISSUE TITLE
[Design] Create Final Wireframes with content for OH userflow option 3

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#74681]
## Tasks
- [ ] Create final wireframes with content for Option 3, which includes: 
- [ ] Text message
- [ ] ID verification page
- [ ] Have you arrived page
- [ ] Success page

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/74681?planning-poker) with Zenhub @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 @loripusey I changed the title of this ticket to "Option 3" not 2.

**Comment by benbrasso-agile6** [comment]
Working on new options in this file: https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=306%3A2015&mode=design&t=hZyXrcNYRaQhlXRg-1

**Comment by kellysmith1008** [comment]
Content is almost done - just waiting on a few last questions around Step 3 in the workflow. Shouldn't need to rollover

**Comment by benbrasso-agile6** [comment]
Going to place in Validate so @kellysmith1008 can give a final look. 

I also created all the error pages. There are tickets next sprint to review the content on those.

**Comment by kellysmith1008** [comment]
Reviewing now - made an edit but everything else looks good. Assuming everything else looks good, I'll respond here and close the ticket

**Comment by benbrasso-agile6** [comment]
Perfect, TY

**Comment by kellysmith1008** [comment]
The rest looks great - closing the ticket now
