### ISSUE TITLE
[Design] Create Final Wireframes with content for OH userflow appt statuses and button action

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#74682]
## Tasks
- [ ] Create final wireframes with content for appt statuses and button action on Appointments list/detail pages that will be used for both option 1 and 2 userflows

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/74682?planning-poker) with Zenhub @kellysmith1008

**Comment by kellysmith1008** [comment]
Placed some suggested content in a [figma comment ](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3?node-id=199:5657&mode=design#685615450)for review by you and Kristen

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 all of the Oracle Health wireframes are in this [Figma page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=183%3A765&mode=design&t=Q8uMRZcUcDDTbf6O-1). Please use this page to review and provide content edits for Option 1 and Option 3.

**Comment by benbrasso-agile6** [comment]
Statuses and buttons will no longer exist with the new flow options. Closing.
