### ISSUE TITLE
[Design] Create Final Wireframes with content for OH userflow option 1

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#74680]
## Tasks
- [ ] Create final wireframes with content for Option 1, which includes: 
- [ ] Text message
- [ ] ID verification page
- [ ] Success page

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/74680?planning-poker) with Zenhub @kellysmith1008

**Comment by kellysmith1008** [comment]
Will take a look at the content this afternoon or first thing tomorrow morning

**Comment by benbrasso-agile6** [comment]
Let's close one of these (this one). Since, the content work will ultimately be done just for one option at this point. So, this ticket is done.
