### ISSUE TITLE
Schedule New Members of VA-CMS team for orientation

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#74690]
## Information

A Platform website/content orientation is done for every person joining the Platform program. This introduces them to our team, the Platform website, our support services and how to collaborate with us. Here's are some team documents with more information:

- [About Platform Content orientations](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2488664654/Product+outline+-+Content+orientation+for+Platform+teams)
- [Agenda and roles](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2481651920/Platform+Content+Team+Orientation+Agenda+Reminder+List)

## Roles
1-3:  Joe
4-5:  Lauren
6:  Brian
7: Lauren
8: 
9: 

Office Hours Zoom link: [HERE](https://www.google.com/url?q=https://us05web.zoom.us/j/84975734927?pwd%3Dx6pqwbF2tGA7TojxKdDDXev8HbO81O.1&sa=D&source=calendar&ust=1709588681639459&usg=AOvVaw2lVJbujdTWb_JjrzD_xUY_)

Team member's first day was: **THURSDAY, JAN 18, 2024**

## Tasks

- [x] Determine the best office hours date to have orientation. At least **6 weeks** from their first day: **TUES, MARCH 12**

- [x] Determine the date range to send new team member Slack message. Preferably **about 1 week** before their orientation: **TUES, MARCH 5**

- [x] On **March 5**, Message them on Slack to let them know. [See #3 in the pre-meeting scheduling process](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2481651920/Platform+Content+Team+Orientation+Agenda+Reminder+List) for message template.

- [x] Adjust Zoom invite:
- Add new team member(s) to invite
- Change all Platform Content attendees to regular (vs optional)
- Update meeting title to: Platform Content Orientation for [enter new team member name]
- Update meeting body. [See #4 in this process](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2481651920/Platform+Content+Team+Orientation+Agenda+Reminder+List) for invite description

## Acceptance Criteria
- [x] A Platform Content orientation will be held on **Tuesday, March 12** for the following:
- [x] Steve Rancour
- [x] Jon Keister
- [x] Marisa Dominguez
- [x] Ian Sears
- [x] AJ Jones
- [x] Grace Kretschmer 
- [x] Amanda Nantais-Austin

**Comment by jknipes** [comment]
Orientation scheduled, participants emailed. Moving this to _Done_
