### ISSUE TITLE
Develop Analytics Plan

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7470]
## Background
We would like to re-evaluate the analytics and KPI's for profile 2.0 given the changes to the designs.

## Tasks
- [ ] Determine KPI's/analytics requirements
- [ ] Update KPI's in product outline
- [ ] Review with team to ensure everything is included

## Acceptance Criteria
- [ ] Finalized analytics requirements
