### ISSUE TITLE
Update Find a Rep unit tests

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#74720]
## Issue Description
Implementing the report modal caused many unit tests to break due to code refactoring. These will need to be repaired. We will also need to write new unit tests for the report modal functionality and various conditional states. 

---
## Tasks
- [ ] Repair broken unit tests
- [ ] Write new tests for report modal state behaviors
- [ ] Write new tests for errors reducer

## Acceptance Criteria
- [ ] All unit tests passing 
- [ ] Unit test coverage report passes 80% threshold

**Comment by oddball-lindsay** [comment]
Functions for four components are below 80% due to a push from yesterday, but should be fixed tomorrow.
