### ISSUE TITLE
SPIKE | COE | Claim Failures

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#74748]
## Issue Description
_We need to identify how COE claims are failing, how often each failure types happens, and add a failure % to the existing COE DataDog dashboard._

Examples of error messages users see are available in the comments of #71747 

---
## Tasks
- [ ] Identify how COE claims are failing
- [ ] Identify how often each type of failure happens
- [ ] Add a failure % to existing [COE DD dashboard](https://vagov.ddog-gov.com/dashboard/4ij-d6y-thi/benefits-coe?refresh_mode=sliding&view=spans&from_ts=1706544873249&to_ts=1706548473249&live=true)

## Acceptance Criteria
- [ ] List of COE failures
- [ ] Follow-up tickets to mitigate failures (if needed)
- [ ] % failure appears in COE DD dashboard
---

**Comment by steele-lm** [comment]
Dupe of [#93325](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93325)
