### ISSUE TITLE
Design | VRE | 31 |Confirmation Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#74743]
## Issue Description
_New confirmation (received) email templates are available. We need to review the current template the form is using and determine if updates need to be made._

- [Current emails](https://docs.google.com/document/d/1kkbkDhgaGJuNrJbz2uHZGWAmbAq0ac21_nkpDQ8FkTc/edit#heading=h.nvwukvkz72q6) in use that need to be updated.
- Design guidance [here](https://design.va.gov/patterns/help-users-to/stay-informed-of-their-application-status).
- [More info](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/patterns/Application%20status/readme.md)

---
## Tasks
- [x] Review current confirmation email and determine if changes need to be made to align to updated template
- [x] If changes do need to be made, update existing confirmation email template in VA Notify
- [x] Create new draft template
- [x] Update "Next Steps" and "What to do if you have questions" info

## Acceptance Criteria
- [ ] Confirmation / "Form Recieved" email template is created in VA Notify

**Comment by hubgitian** [comment]
## Existing Confirmation Email
### filename in VA Notify: `Chapter 31 (form 28-1900) Confirmation`
![Image](https://github.com/user-attachments/assets/53c219f6-7a6a-4e23-a0e8-ede17da17059)

**Comment by hubgitian** [comment]
## Updated content filename in VA Notify: 
### `28-1900 Chapter 31 Form Received - Draft`

This email content template is complete and matches the new Form Received template style.

<img width="844" alt="Image" src="https://github.com/user-attachments/assets/90881903-4938-4154-ab82-101b8656de98" />

**Comment by hubgitian** [comment]
### Content approved by CAIA ✅
#### VA Notify Filename: 28-1900 Chapter 31 Form Received - Draft

<img width="798" alt="Image" src="https://github.com/user-attachments/assets/b002a9e8-2063-4c33-868a-6941d0aff95e" />
