### ISSUE TITLE
Update E2E Tests for Find a Rep

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74779]
## Background
Latest changes to Find a Rep affected tests, need to repair.

## Tasks
- [ ] Write E2E test for triggering the Report modal
- [ ] Write E2E accessibility test for navigating report modal controls
- [ ] Write E2E tests for conditional render logic of various "report states" for a given rep result
- [ ] Write E2E test for search radius dropdowns (once updated in UI)
- [ ] Write E2E test for View Additional Info components

## Acceptance Criteria
- [ ] End to end tests reflect current state of Find a Rep
- [ ] All tests passing with adequate coverage
