### ISSUE TITLE
Pre-Usability Review [Display of Facility-level alert]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7477]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Facility-Level Alert Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-level-alerts/feature-brief.md)
- Link to or attach prototype or [mockups](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7477#issuecomment-608070721)
- Link to or attach artifact with copy (if separate from prototypes/mockups)
- Link to research plan: usability testing is not immediately planned for this COVID roll-out. We will do testing later for workflow usability [#7520](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7520)
- Link to regression test plan: _the **DRAFT** test plan linked below includes facility types which are not impacted by this change and can serve as a regression plan for existing functionality._  
- Link to **DRAFT** [Facility level operational status test cases/test plan](https://dsvavsp.testrail.io/index.php?/plans/view/245) for QA practice area review_ _(note: I will elaborate on the test cases with relevant images and specific results once the designs are complete and test facilities are known)_

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Aricka Lewis, Ryan Thurlwell and Gibran Rodriguez**

## Scheduling
Preferred dates or times: Tuesday, April 7 at 10 ET

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by mmiddaugh** [comment]
This request is per @meganhkelley to expedite the collab process for this work supporting facility status related to COVID. Please note: this is an enhancement to the facility information displayed in the existing Facility Locator search results, not an entirely new feature.

**Comment by meganhkelley** [comment]
Scheduled 4/7 @ 11 am ET

**Comment by arickalewis1** [comment]
Attaching facility level operating status alert for search results cards and facility detail pages

[Uploading locator-main-status-1.pdf…]()
[locator-detail-status-1.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4423298/locator-detail-status-1.pdf)

**Comment by meganhkelley** [comment]
from Aricka re: what the components are that folks should be reviewing: 

Aricka 
The alerts/tags on the card and then the alert and the dummy copy on the detail page

also re: text of alert itself: 
Aricka 
We pull that in from the facilities, so there's no copy

**Comment by joanneesteban** [comment]
(For a potential analytics review): Can these alerts be clicked on, or are they static?

**Comment by mnorthuis** [comment]
If the alerts are incorporated onto existing pages/content, and they do not link to new content pages, there is no IA review needed.

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7641 for analytics

**Comment by peggygannon** [comment]
@arickalewis1 do you have a mockup that shows the alert and the copy that will go on the VAMC detail page?

cc @meganhkelley

**Comment by arickalewis1** [comment]
@peggygannon the copy will come from the facility, they are given a 300 character limit. The above comment shows that layout. They copy directing them to the website for more information is coming from us.

**Comment by peggygannon** [comment]
@arickalewis1 OK, thanks. Will I be able to review the cop that comes from the facility? I recently edited content for the Vet Center status.
