### ISSUE TITLE
Prep and launch Platform Docs feedback page

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#74784]
## Purpose
Position the new page to get launched on Platform Docs site

## Tasks
- [x] Share for team review: [draft](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2927067279/Where+does+my+Feedback+even+go)
- [x] Team feedback
- [x] Update based on feedback
- [x] Review [guidance](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page) on launching a new page
- [x] add footer
- [x] Inform PCT
- [x] Place new docs page in appropriate section for sweeper
- [x] Verify that page is up on Platform Docs
- [ ] schedule slack post in #vfs-all-teams

## Acceptance Criteria
- [x] Revised draft is completed
- [x] Platform docs page is live
- [x] Slack post is scheduled
