### ISSUE TITLE
[Analytics] COVID-19: Analytics tracking for the health chat alert on My VA

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7478]
# Analytics Implementation or QA Request

## Background

This analytics request is for a new alert we just launched on My VA as part of the COVID-19 response. VISN 23 launched a health chat tool and wanted us to put an alert about this tool on the My VA dashboard on VA.gov that could only be seen by veterans/patients in VISN 23. Today, we launched this alert shown below only for veterans in VISN 23 (so people that do not have health care or are patients in another VISN will not see this). We need tracking on how many people click the "Learn more about VA health chat" button:

<img width="852" alt="Screen Shot 2020-04-01 at 12 04 26 PM" src="https://user-images.githubusercontent.com/34068740/78160999-cb769100-7412-11ea-9008-978c3c9bba93.png">

## Description
- **Is this request for Google Analytics implementation or QA?**

Google analytics implementation

- Who is this request for?

    - COVID-19 work for Samara/Authenticated experience
    
- Provide the Domain where Google Analytics needs to be implemented

https://www.va.gov/my-va  

- Please provide any upcoming deadlines or important milestones

ASAP
    
- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

  - We have a staging user, but since it's not one in our normal list, I'll have to send that info separately.

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Same as above.

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by Samara-Strauss** [comment]
@jonwehausen this launched last week and I'm a bozo and didn't think to get analytics on this before launch. Better late than never, I guess :)

**Comment by bsmartin-ep** [comment]
@jonwehausen - how does this look for data layer changes?

Interaction | Screenshot | Datalayer requirements
--- | --- | --- 
Click the *Learn more about VA health chat* button | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/584f39fb-5362-46af-9f68-2101b825f378) | ```dataLayer.push({ ``` <br> ```'event': 'dashboard-navigation',``` <br> ```'dashboard-action': 'view-link',``` <br>  ```'dashboard-product': 'learn-more-chat'``` <br> ```});```

After we update GTM, we should see this event action in GA:

> Dashboard - Navigation - View Link - **Learn more about VA health chat**

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

The dataLayer changes (https://github.com/department-of-veterans-affairs/va.gov-team/issues/7478#issuecomment-611836892) are ready for a dev resource.  Let me know if they have any questions.

We will get our GTM changes QA and published today.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

I added the new action to the LU.  Ready for your QA and for publishing...

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000264

**Comment by Samara-Strauss** [comment]
Great, I'll get a dev ticket created. Thanks!

**Comment by joanneesteban** [comment]
@mshea0606 Hi! Checking in on this - do you have a PR for us to move forward with the datalayer changes?

**Comment by Samara-Strauss** [comment]
@joanneesteban I'm so sorry I dropped the ball on this — checking in with Erik to see if #8033 is finished or not.

**Comment by Samara-Strauss** [comment]
@joanneesteban the work in #8033 has been merged. Just need confirmation from @bsmartin-ep that everything looks good!

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Per separation of duties, I will defer to you to QA and publish.

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000264?orgId=oXPY3GFFQwaHnjNHpFLyFg

Looks good on staging to me though:

![image](https://user-images.githubusercontent.com/62304138/80619505-c6593180-8a12-11ea-810d-6e613e14b23c.png)

**Comment by Samara-Strauss** [comment]
Based on #8033, it looks like we're good to go here. Can someone here confirm that for me? If so, please feel free to close this out. Thank you!

**Comment by mshea0606** [comment]
@Samara-Strauss this is good to close out. Closing it.

**Comment by Samara-Strauss** [comment]
Reopening temporarily — can someone show me where I can track the clicks on this button via Google Analytics?

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss ,

Apologies for the delayed response here - We've got this published and is now live. 

When data starts flowing in, you can find the event in Google Analytics [here](nt-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Dashboard%20-%20Navigation%20-%20View%20Link%20-%20Learn%20more%20about%20VA%20health%20chat). 

If for whatever reason that report link gets funky, the following steps should help you find consistently: 
1) Navigate to the "WBC Modernized View" 
2) Click on Behavior > Events > Top Events on the left nav
3) Toggle the primary dimension to "Event Action" 
4) In the search box on the right hand side type "Dashboard - Navigation - View Link - Learn more about VA health chat"

**Comment by Samara-Strauss** [comment]
Thank you!

**Comment by Samara-Strauss** [comment]
@jonwehausen thanks! all the steps above worked until number 4 when I typed in "Dashboard - Navigation - View Link - Learn more about VA health chat." This didn't generate any results. Thoughts?

**Comment by jonwehausen** [comment]
Hi Samara, 

We published this out Friday afternoon, so data most likely had not yet populated in unsampled reports. 

Run through those steps again this morning and you'll see data (looks to be very low volume so far from the weekend). 

Hope this helps, thanks!

**Comment by Samara-Strauss** [comment]
It worked! Thank you so much. Closing this again.
