### ISSUE TITLE
[CDP] Figmatize CDP file

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#74807]
## Description

Need to update the [CDP figma file ](https://www.figma.com/file/OiiDTTVTCf8j0GngRg0xxD/Combined-VA-Debt-Portal?type=design&node-id=14%3A1108&mode=design&t=ApJe3rSsG0tpHgT8-1) and have it match staging/production to be able to use it as a baseline to start work on the CDP redesign. 

Scenario: In common language describe the work or issue

Given: A designer needs to be able to work
When: A designer needs to create or modify new designs
Then: A designer will be able to use updated files in Figma

## Tasks
- [x]  Edit each page for issues that come up during import 
- [x]  Replace local sketch components with the VA Design System figma components 
- [x]  Flag any design system problems in #platform-design-system 
- [x]  Update pages to reflect what's in staging/production 

## Acceptance criteria

- [x] Font and colors have been updated to use VA Design System
- [x] All local components have been replaced with VA Design System figma components 
- [x] All pages reflect current live status of what's in staging/production 

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
This has been completed! Moving this to closed now!

cc: @HeatherRienks @Tom-Davis
