### ISSUE TITLE
[UX / FE] 10-10EZ Add item to content list of enhanced eligibility

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#74814]
## Issue Description
As a Veteran, I want to see an accurate and complete list of items that would put me in enhanced eligibility status and not needing to provide my household financial information for health care benefits or copays. 

Content: 

> It looks like the list for enhanced eligibility status doesn't include this last bullet point:
> "You served in a location where you had exposure to Agent Orange during the Vietnam War era"
> This is a screen capture from what I'm seeing in staging. The bullet point re: the Vietnam War era should come after "You served at least 30 days at Camp Lejeune between August 1, 1953, and December 31, 1987."

---
## Tasks
- [x] Update design docs and source or truth items to add in additional bullet 
- [x] [Figma link](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=792-30418&mode=design&t=PgPkNTcmhnjyb14x-0)
- [x] Update staging/validate/push to production

## Acceptance Criteria
- [ ] This is correct in production
---
