### ISSUE TITLE
[CDP] Update outdated code to use va-card component and va-on-this-page component 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#74826]
## Description

As a veteran viewing the combined debt portal, I expect it to look consistent with the rest of the VA experience. 

Scenario: A veteran is viewing the Debt Portal and sees their outstanding debts

Given: A veteran view logs onto the debt portal to look at their debts
When: They currently see old, outdated cards
Then: They should see new updated cards to match the rest of the MyVA experience 

## Tasks
- [x] Update the current grey background cards to use the new `va-card` component to match the VA design system
- [x] Update all the custom `On this Page` components [to match the DS](https://design.va.gov/storybook/?path=/docs/components-va-on-this-page--default) 
- [x] Update the links in the cards to use the [`active link`](https://design.va.gov/storybook/?path=/docs/components-va-link--active)

## Acceptance criteria

- [x] Current cards in debt portal will use the `va-card` component with a drop shadow to match the FSR 
- [x] All On This Page components will be updated to match current `va-on-this-page` styling
- [x] All the links in the cards will use the `active-link` 

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
