### ISSUE TITLE
Copy of EKS Upgrade Testing Plan: Login

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74825]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

Part Seven of Testing plan - Login

**Tasks**
- [ ] Verify that users can successfully log in using different authentication methods
- [ ] WHAT ARE DIFFERENT AUTH METHODS - THIS NEEDS SOME THOUGHT. I'm not sure if login will work with the way we are port forwarding? 
- [ ] May need to sync with Identity team on ideas

**Things to consider:**

- what else?

**Acceptability Criteria**
- [ ] TK
- [ ] TK
