### ISSUE TITLE
EKS Upgrade Testing Plan: Step 8: Discovery for Login work

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74824]
The VA Platform Product team is undergoing an EKS upgrade. As part of the process, it is necessary to conduct comprehensive testing on various components of Vets-API to ensure seamless functionality and performance during the upgrade.

From the [EKS Testing Proposal](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000631374/Vets+API+on+EKS+Automation+Discovery+and+Proposal): 
> As part of the current EKS upgrade process, comprehensive testing on various components of Vets API is essential in order to ensure seamless functionality and performance. Upgrading EKS can introduce changes that affect the behavior of deployed applications. Testing verifies that deployed applications remain compatible with any EKS changes. It ensures that all aspects of Vets API continue to operate as expected, without introducing regressions or unexpected behavior that could disrupt services for users. 
> Because of future goals to conduct upgrades on a 3-6 month cadence, it is the Product Platform team’s goal to maximize the automation of these upgrade testing processes. By automating these tests, verification of successful upgrades is potentially expedited and the right amount of time for necessary adjustments can be allocated. The Vets API components that require testing are below, along with the potential automation strategies. The objective is to standardize testing methodologies across the platform, thereby eliminating the inconsistency of testing solutions across EKS applications.

This is the ticket for the discovery work for the Login. The actual work will be done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/74649.

**Part Eight of Testing plan - Login and authenticated endpoints**
Research what kinds of tests could be added to the Postman test suite that would verify login works (for all types of login). Users will need to successfully log in using different authentication methods. How would we test authenticated endpoints? Mock authentication is probably what we'll use since there were some problems getting real auth to work. Vets-Next doesn't have ingress to the cluster and if possible, we'd like all the authenticated tests to exist in the Postman test suite. For the MVP, authenticated endpoints have been scoped out. So the discovery done here will help us post-MVP. Isaac from Reliability Team could help answer questions.

**Tasks**
- [x] Research & discovery for Login work
- [x] Research and discovery for how to test authenticated endpoints
- [ ] Authentication methods to use:
    - [ ] ~Synthetic testing~ Not possible.
    - [ ] Mock
- [x] May need to sync with Identity team on ideas. And/or Isaac
- [ ] Create list of test users
- [ ] Finalize the list of endpoints to test
- [ ] Determine if every single-sign-on provider needs to be tested

**Acceptability Criteria**
- [ ] Have validated list of authenticated methods
- [ ] Have validated list of authenticated endpoints to test
- [ ] Have list of testers
- [ ] Validation of whether or not each SSO provider should be tested

**Comment by rmtolmach** [comment]
### Current login options:

![Image](https://github.com/user-attachments/assets/1e3e08b3-1834-4dac-9d17-1c4f23b58a14)

**Comment by AshleyGuerrant** [comment]
Not completed during Sprint 14 but discovery began. Moving to Sprint 15.

**Comment by rmtolmach** [comment]
Current collection of postman tests. These are for _unauthenticated endpoints only_: [postman/vets-api.pm-collection.json](https://github.com/department-of-veterans-affairs/vets-api/blob/master/postman/vets-api.pm-collection.json).

I'm a little stuck on this: "Mock authentication is probably what we'll use since there were some problems getting real auth to work." If we're using mock auth to test authenticated endpoints, how does that achieve the goal of making sure login works after the upgrade? I understand how testing authenticated workflows without mocked auth could be very complex (or impossible with vets-next?), but does mocked auth give us any peace of mind that login is working? **Is the goal to test login or is the goal to test authenticated endpoints?**

**Possible next steps:**
- [ ] Understand if this is to test login or authenticated endpoints
- [ ] Reach out to Isaac in #platform-product-eks-upgrade-testing-alerts to see how 
- [ ] Ask for help in #identity-support.

**Comment by rmtolmach** [comment]
- I chatted with Lindsey yesterday and she said we want to test _both_ 1) authenticated endpoints and 2) login. I will update the description to reflect this.
- I started a convo with Isaac [in Slack](https://dsva.slack.com/archives/C075G6CD9S7/p1732299050630729).
- Ongoing convo with Lindsey [in Slack](https://adhoc.slack.com/archives/C045LCF8WU8/p1732299329453419).

**Comment by rmtolmach** [comment]
I met with Isaac to get a walk-through of the authenticated tests in Postman. Seems like a lot of work was done but they got stuck on some on some things. I think we can definitely use those existing tests, but maybe make the scope smaller in order to have authenticated tests post-MVP. 

I updated the confluence doc linked in my previous comment.

**Comment by rmtolmach** [comment]
The discovery doc was reviewed [by Isaac](https://dsva.slack.com/archives/C075G6CD9S7/p1732901532260789?thread_ts=1732299050.630729&cid=C075G6CD9S7) and Lindsey. The bottom line is: Integrate a subset of stable authenticated endpoint tests into the automated test suite to ensure reliable coverage while minimizing flakiness. Testing Login won’t be possible on the vets-next cluster.

I've updated #75649 to reflect this.

**Comment by rmtolmach** [comment]
Lindsey reviewed https://github.com/department-of-veterans-affairs/va.gov-team/issues/74649. Closing!
