### ISSUE TITLE
Refine Domo dashboard for Satisfaction Survey data

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#74835]
## Purpose
Make additional refinements within the constraints of Domo, looking to other existent boards for desirable layouts, styles, features.

## Tasks
- [x] Incorporate feedback from related Slack thread where possible
- [x] Determine what information might be most useful along top bar
- [x] Execute desired changes
- [x] SDT review
- [x] Make updates based on feedback
- [x] **reshare for feedback**
- [x] publicize w/ PO, Leadership

## Acceptance Criteria
- [x] Satisfaction Survey Domo dashboards are updated and accurate

**Comment by tayism** [comment]
@steel36 GT conducted a survey [via Optimal Workshop](https://app.optimalworkshop.com/a/dj540s05/questions/results/0e4e14d8-de2e-4489-98b1-b16a4b334cba#/t/results/questions) with OCTO to get feedback on their dashboards. Might be a helpful tool for us to use when this is ready.
