### ISSUE TITLE
GA4: Set-up initial connection with new GA4 properties to BigQuery

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#74848]
### Description
After successful completion of the new GA4 properties, we will need to set-up the connection to BigQuery for these new GA4 properties. This is needed so we can start to exporting data. 

**_Note:_** This will be dependent on the base implementation ticket that is currently in progress.

**New GA4 Properties:**
- [GA4] VA.gov - Non-Production - RESET
- [GA4] VA.gov - Production - RESET

### Tasks

- [x] Perform check on PI in GA4 properties
- [x] Need to set-up the initial connection from GA4 properties into BigQuery, 
- [x] Setup connection to _**GA4 Development Property**_ - [GA4] VA.gov - Non-Production - RESET
- [x]  Setup connection to _**GA4 Production Property**_ - [GA4] VA.gov - Production - RESET

- [ ] Confirm connection is live, and collecting events/data in BQ

### Acceptance Criteria

- [x] Connection from new GA4 properties is in BigQuery.
- [x] GA4 Development Property
- [x] GA4 Production Property
- [x] Confirm/test that data is being loaded in BQ
- [ ] TableIDs in BigQuery have been documented in this ticket.

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt - can you add the names of the GA4 properties to this ticket?

**Comment by johnny-jesensky-adhoc** [comment]
Made BQ to GA connections on a call with Jami and Phil - waiting to confirm data is flowing tomorrow (2/28).

FYI @dorseypa1, @jestutt 

<img width="1810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL09VQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ade0ab9490df2f341fccc2ffd8b70a77bee9e6c/image.png" alt="image.png" />
