### ISSUE TITLE
GA4: Web Component Tracking

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#74846]
### Description:
VA.gov components are reusable site building blocks that -- when used -- create a consistent visual, functional and accessible user experience. Many of these components have related dataLayer events attached to them which generate a significant portion of the existing tracked events -- and hopefully more as teams/applications continue to adopt their usage. 

Using the existing dataLayer events that drive GA UA event tracking, we will use GTM to  implement GA4 tracking for each of the component events. The goal is to have minimal to no changes to the existing dataLayer events to both speed the process along and reduce any stress the GA4 transition might have on the Design System FE's 

**Artifact(s):** 
- [Web and Form Components Tracker ](https://docs.google.com/spreadsheets/d/1_t71Ea-Sxi_hxvK2lswAkn1BUC-JniZic70KUUZF5I4/edit#gid=0)

### Tasks:
- [x]  Compile current list of components (Web) and attached events from Design System's documentation (see tracker document)
- [x]  Map the dataLayer parameters for each component event to GA4 fields/schema
- [ ]  Add each component event to GTM
- [x]  Using GA UA, locate placements to use for testing (where possible)
- [ ]  Test/Preview GTM implementation for each component event on staging 

### Acceptance Criteria:

_For each component event -_
- [ ] Has been added to GTM and published for lower environments (dev + staging)
- [ ] Has been added to GTM and published for production environment 
- [ ] Has been confirmed in GA4 (where possible)
- [ ] Compile any identified new tracking opportunities for future consideration/work

**Comment by johnny-jesensky-adhoc** [comment]
Need to break this out into Web and Form components. Tasks and AC will likely be the same. Look to clone.

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc 
Partially due to extended issues around PII being captured in the `file_download` events and some confusion on my (Jamie's) part around the some of the parameter mapping in the JavaScript that defines the components tracking, we are still at the GTM schema mapping stage for the web components. This means work will continue into the next Sprint with completion expected before the end of the Sprint.

**Comment by davidconlon** [comment]
@jestutt understood and makes sense. Thanks for the detail!

**Comment by johnny-jesensky-adhoc** [comment]
Moving this to _**Done**_ - breaking out the confirmation within GA4 and continual refinement into a separate ticket, as will be a larger, on-going effort.

[GA4: Confirm Web & Form Components in GA4](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/78309)

FYI @jestutt
