### ISSUE TITLE
Find a Rep search radius dropdown

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#74841]
## Issue Description
Search radius dropdown should be introduced per design spec.

<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9QQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ade127451f125bfa44943dc380cb452003840dac/image.png" alt="image.png" />

---
## Tasks
- [ ] Add `<va-select>` component to search controls
- [ ] Connect to redux state store
- [ ]  Pass search radius as explicitly set criteria to the api url

## Acceptance Criteria
- [ ] Search radius can be updated via dropdown

**Comment by cosu419** [comment]
Closed.
