### ISSUE TITLE
Support SSO team with test execution

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#7484]
## User Story or Problem Statement
As a VSP Product Support team member specializing in QA activities, I need to support the SSO product team in their effort to execute a large number of test cases in a short period of time.

## Goal
Execute tests in native environments that the SSO product team does not have access to.
Provide test execution feedback to SSO product team.

## Objectives or Key Results this is meant to further
All test runs have been executed
---
## Tasks
- [ ] Execute test runs
- [ ] Report results / feedback to product team
- [ ] Log issues
- [ ] Work with product team to resolve issues

## Acceptance Criteria
- [ ] Internet Explorer test run execution is complete
- [ ] Edge test run execution is complete

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pjhill** [comment]
OBE
