### ISSUE TITLE
Populate Find a Rep "See associated organizations" component

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#74867]
## Issue Description
Once this data is available from the backend, associated organizations for each rep should be stored in clientside state and passed to the "See associated organizations" `<va-additional-info>` component within each search result. 

---
## Tasks
- [ ] Confirm org list data is present in api response/getting pushed to global state
- [ ] Pass org list to search results

## Acceptance Criteria
- [ ] Associated orgs displaying where available for each rep

**Comment by cosu419** [comment]
@holdenhinkle Can we send back the associated organization that most closely matches the search term? To support this kind of thing:

<img width="607" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88ae9587bdc96dcef0480835a82dd5085cc91f83/Screenshot%202024-02-09%20at%205.21.35%20PM.png" alt="Screenshot 2024-02-09 at 5.21.35 PM.png" />
