### ISSUE TITLE
[CDP][FSR] Design System V3 web component update identification

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#74876]
## Description
The purpose of this ticket is to identify all of the web components in the CDP and FSR that need to be updated to v3, and create tickets to manage those updates.  

On **February 16, 2024** all design system web components will default to their v3 variant, and v3 will become opt out only. We need to run through the Combined Debt Portal, and the FSR to confirm we're using all the latest web components and those components are updated to v3 (adding `uswds`). Some additional details are included below.

https://dsva.slack.com/archives/C03R5SBELQM/p1706549819394489 
> It's strongly recommended all VFS teams prepare for this by dedicating time in their sprint to migrating all web components and addressing any resulting test suite failures. Migration can be done by setting the `uswds` prop to true on a web component. If a team has a need to opt out, the `uswds` prop can be set to `false`. However, V1 components will be fully sunsetted later this year (TBD), and opting out should be viewed as a temporary solution. If a team chooses to opt out, then they should dedicate time soon after on their road map to perform the migration in preparation for when V1 components are fully retired.

## Tasks
- [x] Identify all web components in CDP that need to be updated to v3
- [x] Identify all web components in FSR that need to be updated to v3
- [x] Create ticket(s) to update components in CDP to v3
- [x] Create ticket(s) to update components in FSR to v3

## Acceptance criteria

- [x] Tickets have been created to update CDP web components to v3
- [x] Tickets have been created to update FSR web components to v3
- [x] Any components we don't wish to update should have a recorded justification (in this ticket is fine for now)

## Testing
- [x] N/A 

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Currently there are 212 web components in FSR and 131 in Combined Debt Portal that will need to be reviewed and updated. I'm currently working out the best way to break this effort into tickets vs weighing in cannibalizing this ticket for the entire effort and tackling it head on.

<img width="208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7af43e7e90933a031f5a434c5277d7e03b38825/image.png" alt="image.png" />



<img width="256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae7cab2c1bf75115305b15cb3066004d8004726f/image.png" alt="image.png" />

**Comment by OptionSelect** [comment]
Per Micah Chang tests will need to be confirmed to work after as well.

https://dsva.slack.com/archives/CPE4AJ6Q0/p1706915810550319

**Comment by OptionSelect** [comment]
Draft PRs for both FSR & CDP up.

https://github.com/department-of-veterans-affairs/vets-website/pull/27805
https://github.com/department-of-veterans-affairs/vets-website/pull/27807

**Comment by OptionSelect** [comment]
CDP pr has been merged, working on fixing Cypress tests for FSR one!

**Comment by josephrlee** [comment]
Just an FYI, I created this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75752 which is semi-related to this work. It's for refactoring the Chekcbox Group component to use the latest DS version.

**Comment by OptionSelect** [comment]
FSR pr is pretty much done, just fighting with CI to get it merged so I can close this ticket.

**Comment by OptionSelect** [comment]
After they laxed the restraints on the CI build the FSR pr has been merged as well!
