### ISSUE TITLE
Create Analytics Reporting Process for Better Data Storytelling

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#74879]
## Description 
We would like to generate better data storytelling for the Platform Support Team to identify trends.

---

## Definition of Done
All tasks are completed below.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Reach out to Anita about ticket/spreadsheet they use for Contact Center to track tickets
- [ ] Create dashboard/ticket/spreadsheet based off of this information that notes trends of increased tickets, etc.
- [ ] Create a process around reporting data to Andrea
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
N/A. We have implemented analytics processes since this was created that replace the need for this ticket.
