### ISSUE TITLE
Update page to reflect new process for Datadog Access

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#74881]
## Description
In a recent effort to get Datadog access, I learned that the process has recently changed. This change affects the Get Access to Datadog page. https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog

Specifics as follows:
- In short, due to a process change in mid Dec, people only need to follow Step 2 now, Step 1 is no longer applicable - People simply submit a ServiceNow ticket, and they should be able to get in.  A link for reference to where this change was announced: 
**Process Change Ref:** https://dsva.slack.com/archives/C01U8EYHSEM/p1702579634269269?thread_ts=1702579428.439919&cid=C01U8EYHSEM

The only other suggestion - the guidance on the 'Host Location' answer was a little confusing when I was filling it out. For people on platform teams, they'll likely want to use these locations: vagov.ddog-gov.com - that contains the boards about performance, code yellow, etc. There may be others as well - It may be helpful to provide guidance on what others are out there and who to ask to find out which ones you need, as this may vary from one team to another.

## Tasks
- [x] Discuss changes and determine what will or will not be made
- [x] Make changes, review as needed

## Acceptance Criteria
- [x] Change is made on Confluence
- [x] Change is published to Platform Website

**Comment by jknipes** [comment]
Related ticket on [Platform Content Board](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/73419)

**Comment by CherylEvans** [comment]
@jknipes I reached out to Joe Tice with: "Hi Joe. Thanks again for meeting with me yesterday to discuss ticket 74881 and the associated issues with the language for Hosting Location, and the other issue with the changes needed for the process change regarding Steps 1 and 2 (Link to the Platform page).  I’ve reviewed the ticket and would like to share my thoughts.
As we discussed, I assigned myself the ticket and think adding clarifying language to resolve the problem would be possible.
My proposed solution is to leave Step 1 in place but add language to skip Step 1 based on who completes the process. For example, “If you’re part of (whatever group that should submit an Okta account creation ticket), please complete Step 1. All others can skip this step,” or something to that effect. This allows individuals who don’t need it to skip this step without removing the step for those who need it. Make sense?  I will include this thread in the ticket for reference." 
[Link to Slack thread](https://dsva.slack.com/archives/C04B87D2QLS/p1711043116351689)

**Comment by CherylEvans** [comment]
@jknipes Joe Tice approved this updated language:
If you are part of the DevOps CoP group on Platform you must submit an [Okta account creation ticket](https://jira.devops.va.gov/servicedesk/customer/portal/1/create/1016). 

**Note** - Having an Okta account is no longer a preliminary step to getting Datadog access.  
You no longer need to complete **Step 1** before moving to **Step 2**.

**Comment by CherylEvans** [comment]
I'll close the ticket later today once the updates are published.

**Comment by CherylEvans** [comment]
Confluence is working as expected.

**Comment by CherylEvans** [comment]
Updates deployed to the Platform
