### ISSUE TITLE
Fix broken timestamp spec 

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#74912]
## Issue Description
Past work to fix Form 4142's timestamp appears to have broken a test that fails every day after 4 or 5 MT, and one of the dates was off by a day:

Failing spec: ./spec/sidekiq/central_mail/submit_form4142_job_spec.rb:58

Failures:

  1) CentralMail::SubmitForm4142Job.perform_async with a successful submission job uses proper submission creation date for the received date
     Failure/Error: expect(submission.created_at.to_date).to eq(received_date)

       Expected #<Date:0x000000011b41c488> to eq #<Date:0x000000011b41c4b0>.
[1] pry(#<RSpec::ExampleGroups::CentralMailSubmitForm4142Job::PerformAsync::WithASuccessfulSubmissionJob>)> submission.created_at.to_date
=> Tue, 30 Jan 2024
[2] pry(#<RSpec::ExampleGroups::CentralMailSubmitForm4142Job::PerformAsync::WithASuccessfulSubmissionJob>)> received_date
=> Mon, 29 Jan 2024

It's on master, and would affect anyone attempting to run tests (pipeline included) after 4 or 5pm.

---
## Tasks
- [ ] Fix broken spec

## Acceptance Criteria
- [ ] Specs pass after 4 or 5pm MT
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
