### ISSUE TITLE
Top forms: Add custom form content fields into Drupal for form detail landing pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7491]
##Top forms: Add custom form content fields into Drupal for form detail landing pages

This ticket is related to VA form detail landing pages, per this [epic #5590 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5590)

**Summary:**

- On the new form detail landing pages, we are creating ~2~ new data fields: 'related to' + 'online tool' + when to use this form + related forms/instructions + custom helpful links.
-  All VA forms will display the 'related to' field. Only some forms will show the other custom content. ~'online tool' value (in the form of text and a CTA button).~ 
~- Per initial conversation, we are hosting these 2 new form data fields in Drupal. Our original plan was to have these added to the SQL forms db and have their dev import from a CSV file. We want to host these 2 fields in Drupal now, and need to confirm what is the best way to get these fields and form values into Drupal.~
- Based on @beeyayjay  recommendation and the content team's LOE for this work, these custom content fields will be added manually by the PW content team. 

**Task List**
- [x] Content writer to implement the content for the top forms (40 forms)
- [x] Content writer(s) to implement the content for the rest of the forms (400-ish forms)
- [x] Content editor to review the content

Publishing will be handled in a separate ticket, separate piece of work

---------------

**Content source docs:**

See this folder for the final docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs/README.md

~1/ Custom content for the top 40ish forms. Source will be a combination of spreadsheet (Google doc) and copydeck.~
~Google spreadsheet:~
~https://docs.google.com/spreadsheets/d/1WHWVLHpiiYDszGJbd6Z73Bcf2QcEGfVC/edit#gid=1343794643~

~Copydeck - as of this time 6/2 is the latest. Please check folder to confirm there hasn't been another updated version:~
~https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-content-docs/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx~

~2/ Related to and tool URL fields for the remaining 450ish forms. Source will be a spreadsheet. (SME validation is in flight for these; I've asked for ETA June 9 COB)~

---------------
**Product repo:**
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages

---
## ACceptance criteria
- custom form fields added to Drupal e.g. related_to, meta, online tool

**Comment by stephorkandatx** [comment]
In discussion with Beth, we believe this one can be closed as it's been captured in other work

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx - Updated original issue ^ per [new info regarding the content LOE and manual approach](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9224#issuecomment-634145788) for adding the custom content. Since Beth never provided an engineering LOE, and Randi provided content LOE in a different ticket, I just modified this one to become the implementation ticket. 

**There will be 2 chunks for content:**
1/ Add custom content for the top 40ish forms. Source will be a combination of spreadsheet (Google doc) and copydeck. 

2/ Add related to and tool URL fields for the remaining 450ish forms. Source will be a spreadsheet.

**Comment by jenniferlee-dsva** [comment]
I've updated the ticket with the GitHub folder where all 3 final content docs are now ready. Whenever the Drupal AX is ready, this content manual entry work can begin. 

Please reach out so we can sync before you begin @RLHecht @stephorkandatx. There's a tech issue that's in flight regarding Drupal processing memory (available nodes left), so depending on that, we may launch with just the top forms first.

**Comment by jenniferlee-dsva** [comment]
This work can begin any time. @RLHecht - let's find 30 mins to sync on a call.

**Comment by jenniferlee-dsva** [comment]
I separated out the content entries for the 400~ non-top forms, so these can be validated in chunks. And also, in case we need to launch with only the top forms (due to Drupal nodes/memory issue).  FYSA @RLHecht

**Comment by MickinSahni** [comment]
Pulled into sprint 25, @lunascoop can you drop an estimate?

**Comment by jenniferlee-dsva** [comment]
@RLHecht @lunascoop - Wanted to make you aware of a couple of updates that happened after the copydecks were finalized. I don't think this affects the custom content addition that you're working on, but thought you should know about this change, so you don't treat it as a bug. 

The copydeck shows the H1 and meta title patterned like this:  `VA Form xxxxx` and `VA Form xxxxx | Veterans Affairs`
The CMS update will now use `About VA Form xxxx` as the H1 -- adding the "About." 

This affects the: 

- H1
- Breadcrumb
- Meta title

**Comment by lunascoop** [comment]
Hi @RLHecht I've wrapped up the initial entry of the top 40 forms (31 according to Word doc). Here are the links and notes (if necessary for each draft page:

**Links in order according to Word doc:**

- https://prod.cms.va.gov/find-forms/about-form-21-4138
- https://prod.cms.va.gov/find-forms/about-form-22-1995 : Meta description too long, helpful link for Edith nourse roger for a legacy page
- https://prod.cms.va.gov/find-forms/about-form-21-526ez : No Related to info, not even disability. Helpful link title is different than in Word doc
- https://prod.cms.va.gov/find-forms/about-form-21-2680
- https://prod.cms.va.gov/find-forms/about-form-10-7959c : Meta description too long. Related forms for Spanish version missing in Drupal. Workaround per Slack comment (https://dsva.slack.com/archives/CUB5X5MGF/p1594238881403100?thread_ts=1594226787.398600&cid=CUB5X5MGF) Helpful Link for Family Member… different than on Word doc.
- https://prod.cms.va.gov/find-forms/about-form-10-10d : Cannot link Spanish version of 10-7959c bc it doesn’t exist in Drupal. Helpful Link title is different than on Word doc.
- https://prod.cms.va.gov/find-forms/about-form-21-22
- https://prod.cms.va.gov/find-forms/about-form-10-5345
- https://prod.cms.va.gov/find-forms/about-form-20-0995 : Helpful Link title for Decision Reviews and Supplemental Claims is different than on Word doc.
- https://prod.cms.va.gov/find-forms/about-form-21-686c : Online tool not live yet
- https://prod.cms.va.gov/find-forms/about-form-10-0137 : Meta description too long. Helpful link is a legacy page. Drupal page/node for 10-1037b is missing (Related forms)
- https://prod.cms.va.gov/find-forms/about-form-21-0781 : Cannot link w/in a Helpful link content field. See the How to apply for VA health care on Word doc
- https://prod.cms.va.gov/find-forms/about-form-21-0966 : Meta description too long.
- https://prod.cms.va.gov/find-forms/about-form-21-0845
- https://prod.cms.va.gov/find-forms/about-form-22-5490
- https://prod.cms.va.gov/find-forms/about-form-26-1880
- https://prod.cms.va.gov/find-forms/about-form-10-2850c
- https://prod.cms.va.gov/find-forms/about-form-21-4142 : Meta description too long.
- https://prod.cms.va.gov/find-forms/about-form-21p-0969
- https://prod.cms.va.gov/find-forms/about-form-21p-534ez : Meta description too long.
- https://prod.cms.va.gov/find-forms/about-form-10-10ez-pdf : Helpful links and content for hearing aid and prosthetic socks page needs to be updated when the pages go live on 07/15. The current page is splitting into two. Should we have a helpful link and content for both pages?
- https://prod.cms.va.gov/find-forms/about-form-10-3542
- https://prod.cms.va.gov/find-forms/about-form-22-1990e
- https://prod.cms.va.gov/find-forms/about-form-22-1990n
- https://prod.cms.va.gov/find-forms/about-form-22-1990
- https://prod.cms.va.gov/find-forms/about-form-22-5495
- https://prod.cms.va.gov/find-forms/about-form-va40-10007 : Meta description too long.
- https://prod.cms.va.gov/find-forms/about-form-21p-530
- https://prod.cms.va.gov/find-forms/about-form-21p-527ez
- https://prod.cms.va.gov/find-forms/about-form-10-10cg : Online tool still hasn’t launched

**Other links on top 40 VA forms excel spreadsheet not included in Word doc:**

- https://prod.cms.va.gov/find-forms/about-form-21-22a: Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-21-674 : Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-21p-509 : Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-10-0137-espanol : Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-10-0137a : Only related to and when to use info entered from spreadsheet
- Form 10-0137b not in Drupal: See Slack comment (https://dsva.slack.com/archives/CUB5X5MGF/p1594238881403100?thread_ts=1594226787.398600&cid=CUB5X5MGF)
- https://prod.cms.va.gov/find-forms/about-form-21-0781a : Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-21p-527 : Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-21p-534 : Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-10-10ez : Spanish version; Only related to,  when to use, and online tools info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-10-10ezr : Only related to and when to use info entered from spreadsheet
- https://prod.cms.va.gov/find-forms/about-form-21-0779 : Only related to and when to use info entered from spreadsheet

**Comment by RLHecht** [comment]
@jenniferlee-dsva I've reviewed all of the links @lunascoop  posted above. I updated the H2s to match what was on the copy deck and/or spreadsheet as well as the helpful links where Selina noted they were different. Let me know if we should close out this ticket or if you want to wait to confirm the meta descriptions won't be cut off.

**Comment by lunascoop** [comment]
Hi @DanielleThierryUSDSVA some of the Helpful links copy related to forms, 10-10ez and 21-0781 needs to be updated.

- **Re: 10-10ez:** There's currently a helpful link for the hearing aid and prosthetic socks page, which is being split into two pages and going live later today. I've created a helpful link w/copy for both pages that needs review.

- **Re: 21-0781:** The current copy for the _How to apply for VA health care_ helpful link includes a link. And linking is not supported w/in a Helpful link content field. Instead, we (myself, Jen and Randi) discussed making that link to VA mental health services a separate helpful link. So, I've created a helpful link w/copy that needs review, along with the copy I adjusted re: the _How to apply for VA health care_ helpful link.

Here are screenshots of the copy I adjusted. Here's an updated version of the copy deck too: 
[form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4927207/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx)

<img width="492" alt="Screen Shot 2020-07-15 at 2 20 17 PM" src="https://user-images.githubusercontent.com/42546515/87581373-d219d300-c6a6-11ea-81cb-e351de41de6b.png">
<img width="478" alt="Screen Shot 2020-07-15 at 1 55 08 PM" src="https://user-images.githubusercontent.com/42546515/87581374-d2b26980-c6a6-11ea-9eaa-e257744ec48e.png">
 
CC: @jenniferlee-dsva @RLHecht

**Comment by jenniferlee-dsva** [comment]
@RLHecht @lunascoop - noted update re 21-0966 ^  per slack message

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @lunascoop! Links/descriptions for hearing aid batteries and prosthetic socks look great. I've edited the health care/mental health descriptions. Copy deck attached with edits/notes. Thanks!

[form-detail-lp-coydeck-consolidated-RH-DT-JL-060220_dt_7.16.20](https://github.com/department-of-veterans-affairs/va.gov-team/files/4932361/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220_dt_7.16.20.docx)

**Comment by lunascoop** [comment]
I made the changes to the pages per Danielle's feedback. @RLHecht they are ready for review. I put them back in "Draft" status.

- https://prod.cms.va.gov/find-forms/about-form-21-0781
- https://prod.cms.va.gov/find-forms/about-form-10-10ez-pdf

**Comment by RLHecht** [comment]
Thanks @lunascoop. These look good. I moved them back into Review and deleted the notes next to the form in your comment above.

**Comment by MickinSahni** [comment]
hey @jenniferlee-dsva believe this is in your court to validate

**Comment by jenniferlee-dsva** [comment]
@MickinSahni @lunascoop - I have a separate formal "validate" ticket for these top 40~ forms: ticket #11010 , so this ticket can be closed, as it looks like all the custom content entering work as been completed. 

@lunascoop - Could you separately create a ticket to capture all of the form pages that we need to check against their tool launch later?  (Example: the hearing aid form, the 1010 CG caregiver form, etc.)  We just want a placeholder ticket in the backlog for later, so we can add the tool links  to those form pages when their tools launch. Maybe we need as separate tickets, since the tools may launch at different times?

**Comment by MickinSahni** [comment]
> Maybe we need as separate tickets, since the tools may launch at different times?

my rec would be to start with an epic around post-launch review of forms/online tools and build out from there.
