### ISSUE TITLE
EVSS - Release Plan for BRD

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#74932]
This ticket covers the discovery and release plan to deploy the migrated endpoint to LH for BRD separation locations endpoint. The scope includes:

Release plan - look at staggered release
Can point to specific user through feature toggle
Tasks in the ticket

---
## Tasks

- [x] Identify acceptance criteria for a successful run
- [x] Identify/document risks and mitigation
- [x] Build the dashboard for monitoring traffic for LH/EVSS

## Acceptance Criteria
- [x] Identify acceptance criteria for a successful run
- [x] Figure out how to monitor success(526ez form prefill, submit workflow)
- [x] Release plan; add to here https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans
- [x] Create Testrail testplan
- [x] Execute Testrun
- [x] Successful testrun
- [x] Create a ticket for starting the staggered release based on the plan
- [x] Risks have been documented
- [x] Built the dashboard for monitoring traffic for PPIU for LH/EVSS

## for testing in ArgoCD

# provider level

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tommasina-va** [comment]
We're creating a follow-up ticket to investigate some discrepancies uncovered in the DataDog dashboard.
