### ISSUE TITLE
AMA Updates Follow-On Work: Implementing Left-Nav Recommendations in Drupal 

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#7494]
## User Story or Problem Statement
As a Veteran who disagrees with a claim decision, I need decision review pages in lefthand nav so I can easily find them. 

## Goal
Implement Mikki's left-hand nav recommendations:
https://app.moqups.com/Rnc4BDEKrA/view/page/a5e3c0342

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

- [x] Laura finishes this ticket 
- [x] Nick confirms timing estimate
- [x] Nick implements nav
- [ ] Randi double-checks/fixes naming conventions

## Acceptance Criteria
- [x] Side bar for a Decision Reviews page shows up in preview
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6421
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
@lwalsh617 I'm not absolutely certain because this I wasn't familiar with the code but I think this is done. The sidenavs for Decision Reviews should be working from the Drupal preview after today's daily deployment around 3 PM. 

@MickinSahni I went ahead and grabbed this after grooming because it sounded like this was a blocker for some of our team and I wondered if it was an easy tech task.

**Comment by MickinSahni** [comment]
@RLHecht to check in Drupal that this is now working

**Comment by ncksllvn** [comment]
To validate, this page should have a sidebar - http://preview-prod.vfs.va.gov/preview?nodeId=3011. It doesn't yet. Looking into it...

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- Engineering work complete. Drupal config to connect pages in each hub to the side bar and naming convention needs to be updated
  - @RLHecht's on the case.

**Comment by RLHecht** [comment]
This is now working in preview! @lwalsh617 I just want to make sure that the titles in the left nav are correct, though. Should I be following exactly what's in Mikki's Moqup?

**Comment by MickinSahni** [comment]
Sprint 19 Planning
- Left nav up-to-date
- Left nav changes can now be drafts in Drupal
