### ISSUE TITLE
[CHIP] - Create an event validator for OH appointments from VeText

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#74959]
## Description

Create an event validator for OH appointments from VeText.

Filename:
- chip/layers/utilities/nodejs/vetextOHEventSchema.js
- chip/src/initiateCheckinOH/event.schema.js

Ex:
https://github.com/department-of-veterans-affairs/chip/blob/master/layers/utilities/nodejs/vetextEventSchema.js

Fields to validate:

```
"patient": {
    "dob": "YYYY-MM-DD",
    "cellPhone[the number used to send text]": "+15555555",
    "name": "Last,First"
  },
"appointments": [
  {
    "id": "4822366",
    "startDate": "2020-01-23T22:10:00.000+00:00",
    "status": "Cancelled",
    "patient": {
      "address": "1166 6th Avenue\n22\nNew York, NY 23423\nUS",
      "edipi": "1000000105",
      "icn": "12724066",
    },
    "patientStatus": "accepted",
    "practitionerNames": [
      "John Smith"
    ],
    "wardId": "32216049",
    "wardName": "Clinic Friend Name",
    "stationNo": "530",
    "serviceType": [
      "DIAGNOSTIC",
      "..."
    ],
    "timezone": null
  },
  {...},
]

```

## Tasks
- [ ] Create validator for success
- [ ] Create validator for error
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Product team has signed off on the feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR

**Comment by wullaski** [comment]
We can create the event.schema.js file when we create the initiateCheckinOH endpoint.
