### ISSUE TITLE
Generate & Deliver Monthly Domo Report for January 2024

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#74951]
### Description
We deliver these monthly reports to an audience of OCTO each month on the 8th. This ticket is to track the completion, QA check, and delivery of these reports.

> **What:**
> VEO, DMC & OMB stakeholders receive the Monthly VA.gov Summary.
> 
> **When:**
> Due by midday EST on the 8th of the month.
> 
> **Who:**
> Send via Slack to @Chris Johnston @Erica Robbins [GovCIO_VetsPS] @Lacey @Julia Badillo on the #vfs-analytics channel (see example)
> 

### Tasks

- [x] Check data (Data is up to date as of the last day of the previous month)
- [x] Check content
- [x] Export Dashboards as PowerPoint
- [x] Review data & content (Data is up to date as of the last day of the previous month, Labels show on charts, etc.
Redo title slides and section titles

- [ ] Change dashboard titles to, "VA.gov Monthly Metrics – month year"

- [x] Go through slides and move section titles to appear directly above appropriate section (Domo will often put them at bottom of last chart of previous section in PowerPoint export)

- [x] Rename the file

- [ ] Send the file to the appropriate stakeholders

### Acceptance Criteria
- [x] Report has been downloaded to a PPT format
- [x] Report has been QA'd, using the guidance provided in [this Confluence page](https://vfs.atlassian.net/wiki/spaces/AT/pages/2001928499/Updating+Recurring+Reports)
- [x] Report has been sent to Chris, Erica Robbins, Lacey, and Julia on the #vfs-analytics channel
