### ISSUE TITLE
Final Edits & QA for Facility Locators Edge Case Dashboard

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#74966]
### Description
This ticket is a follow-up from the following [custom dashboard request](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/61633). We have been working with the team, on building them an edge case dashboard, and are close to final delivery. This request is to knock out the final tasks in this next sprint.

**Domo Edge Case Dashboard:** https://va-gov.domo.com/page/1954588686

### Tasks

- [x] Perform final QA of dashboard in Domo, ([here](https://docs.google.com/spreadsheets/d/1siGoD2djYPr3adFjjO_pO_9Hf1WhqVbe-EaRFt3yYIQ/edit#gid=1705523695))
- [x] After QA, add additional quarters of data.
- [x]  Reach out to team, letting them know the dashboard is completed.
- [x] Close out [initial ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/61633).

### Acceptance Criteria

- [x] Data has been QA'd.
- [x] Additional quarters of data have been added.
- [x] Message has been sent in the [original ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/61633), letting them know the dashboard is completed.
- [x] Original ticket has been marked as _Done_

**Comment by johnny-jesensky-adhoc** [comment]
Final QA and edits have been made, moving this to _Done._ Have created a separate ticket in our backlog to make further, nice-to-have enhancements as a version 2, to be prioritized down the road.

That ticket can be found [here](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/76077).
