### ISSUE TITLE
[FE] 10-10EZ - Toxic Exposure: Add new questions to EZ form

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#74969]
## Background
In an effort to quickly identify Veterans who have been exposed to toxic materials during specific time period and/or while deployed at specific locations, the HEC Stakeholders would like to have Toxic Exposure questions added to the 10-10EZ form.
This is intended to quickly identify these Veterans, so they can get the care they need.  It is also intended to providing Veterans a place to add the information so that this information is included in the Veteran's health record.  This information could qualify the Veteran for care they would not otherwise be able to receive. 

As part of adding new questions, we will be introducing new fields to the application.  The fields include Yes/No, Freeform text and Dates.

## Resources
- [Original TERA draft 10-10EZ with sticky notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Archive/TERA%20Draft%202023_10-10EZ.pdf) (May have to download to see sticky notes)
- [Most recent TERA Draft 10-10EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/TERA%20draft%201-23-2024%20VA%20Form%2010-10EZ.pdf)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?fromVisitorModal=true&sender=u5ad49c107baa41137f271007)
- [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=450-19244&mode=design&t=GyO36RKAPEFgXEna-0)

## Tasks

- [x] Review designs and clarify outstanding questions
- [x] implement designs into 10-10EZ UI (Feature toggle?)
- [x] Ensure accessibility focus and components are included
- [x] Complete E-2-E testing as needed
- [ ] Notify team once deployed to Staging for testing
 
## Acceptance Criteria
- The 10-10EZ now has the TERA questions and corresponding fields, radio buttons, and checkboxes added.

**Comment by hdjustice** [comment]
Validated new questions on 10-10EZ - Looks great and will function as expected.  Note: E2E testing was completed successfully with VES team.
