### ISSUE TITLE
EVSS PCIU Migration: Objective 1: Review VA Profile API docs to map EVSS data to VA Profile

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74973]
## Issue Description
This ticket is to update the API documentation regarding the mapping of data retrieved from the External Veteran Services System (EVSS) to the VAProfile system. As changes have been made to either the EVSS or VAProfile endpoints, it is necessary to ensure that the documentation accurately reflects the current mappings and endpoints to facilitate integration and development efforts.

## Tasks
Documents to update:

- [x] [Service Object Implementation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885700252/Service+Object+Implementation)
- [x] [Betamocks Config](https://vfs.atlassian.net/wiki/x/K4B5c)
- [x] [Betamocks](https://vfs.atlassian.net/wiki/x/HgCkc)
- [x] [Spec File Examples](https://vfs.atlassian.net/wiki/x/o4Blc)
- [x] [Match Response Schema Implementation](https://vfs.atlassian.net/wiki/x/DAB2c)
- [x] [Controller Route Serializer](https://vfs.atlassian.net/wiki/x/GIB2c)

Documents Reviewed (by other teammate):
- [x] [Service Object Implementation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885700252/Service+Object+Implementation)
- [x] [Betamocks Config](https://vfs.atlassian.net/wiki/x/K4B5c)
- [x] [Betamocks](https://vfs.atlassian.net/wiki/x/HgCkc)
- [x] [Spec File Examples](https://vfs.atlassian.net/wiki/x/o4Blc)
- [x] [Match Response Schema Implementation](https://vfs.atlassian.net/wiki/x/DAB2c)
- [x] [Controller Route Serializer](https://vfs.atlassian.net/wiki/x/GIB2c)

**Comment by jennb33** [comment]
@rmtolmach will review this ticket

**Comment by RachalCassity** [comment]
https://vfs.atlassian.net/wiki/spaces/TS/pages/1887010852/Supporting+Code

**Comment by rmtolmach** [comment]
✅ Docs looks good. And they were moved from the Test Space to Developer Docs -> Backend developer documentation.
