### ISSUE TITLE
EVSS PCIU Migration: Identify forms to test

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74978]
### Original Issue
Develop a general asynchronous processing model for vets-api requests · Issue #480 · department-of-veterans-affairs/va.gov-team

### Conclusion
Latency issues in the past were due to an outdated data structure and should not be an issue moving forward with the migration. The VAProfile integration fixed the latency issues years after initial approach. It seems as though the PCIU migration was not complete due to how little PCIU is referenced. It is important to note that PCIU calls are significantly lower than other VAProfile services, like veteran status.

This was an issue years back and no longer an issue. This ticket can be closed.

---
## Tasks
- [x] Identify forms to test 
- [x] Test forms
- [x] Record testing results

## Acceptance Criteria
- [ ] TBD
---
## How to configure this issue
- [ ] EVSS PCIU Migration: Remove calls to PCIU in global Pre-fill
- [ ] Product Support
- [ ] backend, devops
- [ ] request

**Comment by RachalCassity** [comment]
### Original Issue
Develop a general asynchronous processing model for vets-api requests · Issue #480 · department-of-veterans-affairs/va.gov-team

## Conclusion
Latency issues in the past were due to an outdated data structure and should not be an issue moving forward with the migration. The VAProfile integration fixed the latency issues years after initial approach. It seems as though the PCIU migration was not complete due to how little PCIU is referenced. It is important to note that PCIU calls are significantly lower than other VAProfile services, like veteran status.

**Comment by RachalCassity** [comment]
This is handled by the Disability and Auth Experience team. This can be closed.
