### ISSUE TITLE
[QA] 10-10EZ - Toxic Exposure: Validate content and formatting

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#74986]
## Benefit to the Veteran
By completing QA using various use cases, we can ensure the new TERA section of the 10-10EZ will be accessible, easy to understand and functional for Veterans to fill out and submit to VA.

## Background
In an effort to quickly identify Veterans who have been exposed to toxic materials during specific time period and/or while deployed at specific locations, the HEC Stakeholders would like to have Toxic Exposure questions added to the 10-10EZ form.
This is intended to quickly identify these Veterans, so they can get the care they need.  It is also intended to providing Veterans a place to add the information so that this information is included in the Veteran's health record.  This information could qualify the Veteran for care they would not otherwise be able to receive. 

As part of adding new questions, we will be introducing new fields to the application.  The fields include Yes/No, Freeform text and Dates.

This ticket is to validate content and formatting matches to designs.

## Resources
- [Original TERA draft 10-10EZ with sticky notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Archive/TERA%20Draft%202023_10-10EZ.pdf) (May have to download to see sticky notes)
- [Most recent TERA Draft 10-10EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/TERA%20draft%201-23-2024%20VA%20Form%2010-10EZ.pdf)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?fromVisitorModal=true&sender=u5ad49c107baa41137f271007)
- [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=450-19244&mode=design&t=GyO36RKAPEFgXEna-0)
- [TERA Use Case document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZ-Toxic%20Exposure%20(TERA)%20MVP.md)

## Tasks

- [x] Validate content matches Designs
- [x] Validate formatting matches Designs
- [x] Document in this ticket of any conflicts or issues found
- [ ] PM will sign off and close this ticket once all content and formatting are validated
 
## Acceptance Criteria
- The 10-10EZ TERA questions content and formatting has been validated and conforms to design specifications.

**Comment by jessicastump** [comment]
I realize we haven't started this yet and it needs grooming still at tomorrow's refinement session :)
But flagging there were some 11th hour changes to the toxic exposure opt in/out page that Aliyah worked on with Danielle. Updated in [Figma here](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=1251-18225&mode=design&t=aNlBZdTu2ZopQlMP-4)
cc @hdjustice and @longmd

**Comment by jessicastump** [comment]
A quick content QA run through this afternoon :) 

Other than the opt in/out page changes mentioned above, only saw a couple other content edits needed from the latest designs.

**Gulf War locations page**
Header change to: 
_Service in Gulf War locations_

**Other toxic exposure page** 
Capitalized “Public Health” in link
 - Learn more about exposures on our _Public Health_ website (opens in new tab) 
 - This content change just came in today (2/27) based off of other VA.gov content just being finalized 


**Household Financial Information - Section Intro**
Enhanced eligibility status additional info component

Match content to add info component on toxic exposure opt in/out page adding this bullet: 
_- You were exposed to toxins or hazards by working with chemicals, pesticides, lead, asbestos, certain paints, nuclear weapons, x-rays, or other toxins. This exposure could have happened while training or serving on active duty, even if you were never deployed._

**Comment by jessicastump** [comment]
For the short form Authenticated alerts, there is currently a sentence referring to military service. Remove entire sentence.
![ShortFormAlert-FirstPage](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/51ac4a31-a22c-479b-b75f-f2c0a0d853cf)
![ShortFormAlert-WithinForm](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/b154bdab-82e7-4cd1-b26a-6d9c8bfc41ba)

**Comment by jessicastump** [comment]
Additional change to the UNauthenticated short form alert (remove part of last sentence, some changes)
![Alert (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/212d07a0-483c-4d3d-8be6-cd06284c9b2a)


Paragraph content change on page - Dates for other exposures
Correct content below and in Figma:
> Enter any date range when you were exposed to other toxins or hazards. You don't need to have exact dates.

**Comment by jessicastump** [comment]
@hdjustice and @longmd - The content/design changes I noticed are added in the comments above or those other tickets we opened for the confirm/intro pages and alerts. I can do another round of testing this afternoon if needed before I am out tomorrow.

**Comment by jessicastump** [comment]
Looks good in staging @longmd! Didn't see any content discrepancies, just the address formatting noted on the confirmation page [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77164). Only have tested unauthenticated so far though.
