### ISSUE TITLE
EVSS PCIU Migration: Step 5: EVSS PCIU Migration: Re-record cassettes

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74980]
## Issue Description
 VCR cassettes serve as fixtures for testing new VAProfile API interactions by recording HTTP interactions and replaying them during automated tests. Due to the PCIU deprecation, existing VCR cassettes will be outdated and new VCR cassettes will need be recorded for VAProfile requests.

These ticket might belong to another team. 

## Tasks 
- [ ] Review the current set of VCR cassettes used for VAProfile requests.
- [ ] Identify outdated or incorrect recordings that need to be updated.
- [ ] Re-record outdated VCR cassettes, if applicable

**Comment by LindseySaari** [comment]
Spec files and cassettes are in. Tests are passing but work is paused for support rotation.

**Comment by jennb33** [comment]
This ticket was duped for Sprint 9 as [91697](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91697) to allow for enough time to complete the work.
