### ISSUE TITLE
DR | Refactor Confirmation Pages

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#74981]
## Value Statement

**_As a_** developer
**_I want to_** refactor the Confirmation Page across all 3 forms
**_So that_** tech debt is reduced and so that future developers don't have to update the Confirmation Page in 3 locations

## Background Context

- Confirmation Page is undergoing content research. 
- Currently 996/10182 shared several identical lines of code leading to a maintainability rating of F.
- 995 is currently the most approved content
- Content from 10182 (NOD) prototype currently in research (to be applied to shared code once it goes through collaboration cycle

- The following files will be refactored into a new file `src/applications/appeals/shared/containers/ConfirmationPage.jsx`
  > src/applications/appeals/995/containers/ConfirmationPage.jsx
  > src/applications/appeals/996/containers/ConfirmationPage.jsx
  > src/applications/appeals/10182/containers/ConfirmationPage.jsx

## Out of scope
* Other apps/forms not in Decision Reviews

## Tasks

- [ ] variable created for each app for titles
- [ ] Unit tests updated
- [ ] E2E tests updated
- [ ] Forms functionality has not changed

## Definition of Ready 

- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/containers) in vets-website repository 
- [x] Access issues in Codeclimate
    - [x] [Supplemental Claims](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/containers/ConfirmationPage.jsx)
    - [x] [Higher Lever Review](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/containers/ConfirmationPage.jsx)
    - [x] [Notice of Disagreement ](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/containers/ConfirmationPage.jsx)

## Definition of Done

- [ ] Confirmation Page renders on all 3 forms with their respective form names
