### ISSUE TITLE
[spike] DR | Investigate Introduction Pages across appeal forms

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#74985]
## Value Statement

**_As a_** developer
**_I want to_** research the Introduction Page across all 3 forms
**_To Determine_** if files should be refactored and moved to shared folder.

## Background Context

After discovering outdated content in the Confirmation Page of the appeal forms, we would like to investigate the nature of the Introduction Page.

- The following files will be investigated to determine if refactorable into a new shared file: `src/applications/appeals/shared/containers/IntroductionPage.jsx`
  > [src/applications/appeals/995/containers/IntroductionPage.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/containers/IntroductionPage.jsx)
  > [src/applications/appeals/996/containers/IntroductionPage.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/containers/IntroductionPage.jsx)
  > [src/applications/appeals/10182/containers/IntroductionPage.jsx](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/containers/IntroductionPage.jsx)

## Out of scope
* Actual refactoring

## Tasks

- [ ] Determine if Introduction Page can be refactored
- [ ] Determine level of effort to refactor Introduction Pages across all 3 forms
- [ ] Determine if consultation if consultation with design is needed
- [ ] Create ticket for refactoring (if applicable)

## Definition of Ready 

- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/containers) in vets-website repository 
- [x] Access issues in Codeclimate

## Definition of Done

- [ ] New ticket created or research findings shared with group
