### ISSUE TITLE
DR | Refactor Reducers for Contestable issues

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#74990]
## Value Statement

**_As a_** developer
**_I want to_** refactor the reducers across appeal forms into the shared folder
**_So that_** tech debt is reduced and so that future developers don't have to update the Contestable Issues reducer in 3 locations

## Background Context

These files have a [CodeClimate](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/reducers/contestableIssues.js) maintainability rating of C and share duplicate code. 
In part of cleaning up our code and reducing duplicate code, we will refactor identical code to be shared.

- The following files will be refactored into a new shared file: `src/applications/appeals/shared/reducers/contestableIssues.jsx`
  > src/applications/appeals/995/reducers/contestableIssues.js
  > src/applications/appeals/996/reducers/contestableIssues.js

- The following files will be investigated to determine if refactorable into a new shared file: `src/applications/appeals/shared/reducers/contestableIssues.jsx`
  > src/applications/appeals/10182/reducers/contestableIssues.js

## Out of scope
* Actual refactoring

## Tasks

- [ ] Determine if 10182 can also be refactored
- [ ] Unit tests updated
- [ ] E2E tests updated
- [ ] Confirm that ContestableIssues load without change

## Definition of Ready 

- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/reducers/contestableIssues.js) in vets-website repository 
- [x] Access issues in Codeclimate

## Definition of Done

- [ ] Validate that contestable issues load as normal

**Comment by Mottie** [comment]
Refactor work merged; ready for discussion & closing.
