### ISSUE TITLE
Create alert for RDS CPU utilization

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#75009]
## Description

We currently have a monitor for [RDS CPU Utilization](https://vagov.ddog-gov.com/monitors/100554?view=spans&live=1w) in Datadog, but it doesn't currently alert anyone. 

## Tasks

- [x] DD Monitor
- [x] Alert to Slack
- [x] Alert to PagerDuty
- [x] Add to Terraform

**Comment by RachalCassity** [comment]
- Created [Vets API Alert and Monitoring Trends](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends).
- Started [RDS and POSTGRES Error Tracking Dashboard](https://vagov.ddog-gov.com/dashboard/yp7-h2s-3zy?refresh_mode=sliding&view=spans&from_ts=1705329036000&to_ts=1708007436000&live=true)

**Comment by RachalCassity** [comment]
Closing after standup
