### ISSUE TITLE
Repair and refine Domo dashboard for Platform Feedback data

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#75006]
## Purpose
Make additional refinements within the constraints of Domo, looking to other existent boards for desirable layouts, styles, features.

[Ideation and prototyping **document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2945974512/Domo+dashboard+for+Platform+Feedback+Data)**

## Tasks
- [x] Repair connections due to "Main" sheet changes
- [x] Determine what information might be most useful along top bar
- [x] Evaluate/make changes to layout
- [x] Team review
- [x] Make change based on feedback
- [x] publicize w/ PO, Leadership

## Acceptance Criteria
- [x] Satisfaction Survey Domo dashboards are updated and accurate
