### ISSUE TITLE
Alert on slow Postgres Queries

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#75010]
## Description

We have a [Datadog metric/query ](https://vagov.ddog-gov.com/metric/explorer?start=1706038579349&end=1706643379349&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYAEwGIFCeGE4a+NoAxkrIIOoIulmWgWZxyhgAbjDIhRg5AHQOGggwEBoNsVgNUHjanpIiwABUPAAEAEZYY8B2mTlOkeo8IDwAulSu7niYoeFbqjsYMWUJqxsgLVhouaDyGDcICLnJODBOWbsaEFlJaKJwJxyRTKDL-KB-AFOehMZQiNweNCrfjteSYLBAhQvf4iJTrHh8S5o8QAYSkwhgKBEOzQPCAA) specifically for pinpointing slow PostgreSQL queries. Proactively setting up alerts for these slow queries could enable us to detect and address bottlenecks promptly, potentially preventing widespread latency issues across the site.

### Tasks
- [x]  DD Monitor - [[Vets-API][PROD][POSTGRES][HIGH QUERY DURATION]
](https://vagov.ddog-gov.com/monitors/199084?view=spans)
- [x]  Alert to Slack
- [x]  Alert to PagerDuty
- [x]  Add to Terraform

**Comment by RachalCassity** [comment]
@jennb33 Closing!
