### ISSUE TITLE
Collaboration Cycle for [Modernized Check-in, eCheck-in, Mileage-only Travel Claim Submissions for VA Facilities that use Oracle Health EHR Software]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75013]
### VFS team name

Modernized Check-in

### Product name

eCheck-in

### Feature name

Mileage-only Travel Claim Submissions for VA Facilities that use Oracle Health EHR Software

### GitHub label for team

HCE-Checkin

### GitHub label for product

vets-website, vets-api, chip, lorota

### GitHub label for feature

oracle-health-travel

### Public DSVA Slack channel for VFS team

https://dsva.slack.com/archives/C022AC2STBM

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

January 1, 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C022AC2STBM/p1706795530917119)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [X] [User flow](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=306%3A2015&mode=design&t=tHPFTxTHDQAKH4DD-1) (required)
- [X] [Whiteboard, Figma or other lo-fi prototypes or wireframes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=306%3A2015&mode=design&t=tHPFTxTHDQAKH4DD-1)
- [X] Research plan - research has already been performed (see [findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2023-11%20Past%20Appointments%20Travel%20Reimbursement%20Generative%20Usability%20Study/research-findings.md))
- [X] NA - Any other artifacts you have so far
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C022AC2STBM/p1706885515586249)
- [x] Meeting date/time: **Tuesday, February 6, 2024 at 11:30AM ET**
  
##### Platform actions

* Accessibility
  * [ ] Feedback ticket attached
  * [x] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/K6sm9m75VMzENLgiRtauMl__F1f-UzIxEaM9lbM-pTAV5BupQAd25durv7EKRHHI.KUrS048JOAP3BPJ3)
  - Passcode: `m*H4+mQI`
  
##### VFS actions

- [x] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [x] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
Research has already been conducted; see [findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2023-11%20Past%20Appointments%20Travel%20Reimbursement%20Generative%20Usability%20Study/research-findings.md))
- NA [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=96%3A709&mode=design&t=RlA8fd2BGkeywMW7-1)
- [x] Specify which pages are included in the review: pages that already exist in production include a label such as "No change from eCheck-in" 
- [x] [Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2023-11%20Past%20Appointments%20Travel%20Reimbursement%20Generative%20Usability%20Study/research-findings.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2023-11%20Past%20Appointments%20Travel%20Reimbursement%20Generative%20Usability%20Study/conversation-guide.md)
- [x] [Draft in-person UAT research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-02%20In-Person%20Travel%20Reimbursement%20Research%20for%20Oracle%20Health%20Facilities/research-plan.md) 
 
**Content artifacts**
  
- [x] Please include a link to any [Sitewide CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75317)

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75317)
- [x] [Userflow (MVP 0.0.2)](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=1265-1102&mode=design&t=wB0sPLNcuTzdlun8-4)

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C022AC2STBM/p1707937864888239)
- [x] Meeting date/time: Thursday, February 22, 2024 at 3:30 p.m. Eastern

##### Platform actions

* Accessibility
  * [ ] Feedback ticket attached
  * [ ] No feedback
* Content
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [ ] Feedback ticket attached
  * [x] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/SjOGQAUWMJwyN9a85JOkSumbw8VKEQwG5bRti-V-E5TQRkY5iM7soZI2ZihYGkp2.cmAlQhSIJEX8SK--
  - Passcode: s&qpHN72
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below
  - [x] [Contact Center review request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90045) 

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [x] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
    - NOTE: request was posted in Platform Support to add a new entry to the Directory

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL: staging.va.gov/my-health/appointment-travel-claim/
      - **NOTE: link is a custom link with a GUID generated for each Veteran request, see Staging test user information below**
- [x] Specify which pages are included in the review        
    - All pages as this is a brand new application
- [x] [Staging test user information]()
    - Unique URLs will be generated (have to be done on day of testing) for the following dates:
         - August 23 - https://staging.va.gov/c/q30psZp
         - August 26 - https://staging.va.gov/c/bATMAua
         - August 27 - https://staging.va.gov/c/G4jbv9T
         - August 28 - https://staging.va.gov/c/JW7hvVS
             - multiple appointments - https://staging.va.gov/c/3V2udvW
    - Use last name `Tester` and DOB `04/07/1935`
    - Each URL can be used once per browser. Multiple people can use the same URL on the day.
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**  
- [x] Please include a link to any [Sitewide CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75317)

**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75317)
- [x] [Userflow (MVP 0.0.2)](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=1265-1102&mode=design&t=wB0sPLNcuTzdlun8-4)

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan)
    - NA, this is a brand new application
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/5141)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/873)
- [x] [Summary(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/874)
- [x] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/travel-claim/tests/e2e)
- [x] [Code coverage](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM040Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89938990bd7f195b18468ae040461da018e1f3ac/Code%20coverage%20report%20for%20All%20files.pdf)
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79046)
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C022AC2STBM/p1723646051710259)
- [x] Meeting date/time: Thursday, August 29, 2024 at 1:30 p.m. Eastern

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/wnX2_9YSFRbW3Dz5rb-7Sv7OL8A9H65fVlYd7jP3dcvnkc2Q7ek1l-n2UEEq73M9.baFClKzlcIxHPWd6) 
  - Password: `H*.3aGz6`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
 
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
     - [Readiness Review Ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1979)

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by loripusey** [comment]
[Initiate Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/check-in-for-oracle-health.md)

**Comment by loripusey** [comment]
Closing as all issues have been address; product is being pushed to production for internal performance testing but will NOT be made available to Veterans until internal API performance testing in production is complete.

**Comment by loripusey** [comment]
Closed the wrong ticket, re-opening, Sorry about that
