### ISSUE TITLE
Design Intent short video for touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75014]
## User Story
As a VFS team member with an upcoming Design Intent meeting scheduled, I want to know what is expected of me and my team prior to the meeting so that I can ensure all of our artifacts are shared.

As a VFS team member with an upcoming Design Intent meeting scheduled, I want to know what to expect in the meeting so that my team can be prepared and get the fullest value from the 30 minute meeting.

As a VFS team member preparing to schedule a Design Intent meeting, I want to know the value and benefits of the meeting, so that my team can decide whether or not it's worth our time.

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
For over a year now, Governance team has been discussing the idea of "short videos" within the context of Platform Orientation. We understand that people learn and absorb information in different ways - some people prefer to read text, some people prefer to hear and/or see it explained, and others might learn best from experience. While we can't currently support the latter, we are betting that introducing a short 2-3 minute video into existing context will better help VFS teams understand what is expected of them and what to expect within the process. This will hopefully result in less confusion with the VFS, less questions asked within office hours and support channels, and greater understanding of Platform processes.

We have decided to pilot this "short video" idea with the Design Intent. 

The purpose of this ticket is to draft a script, prepare a visual aid, record a video and embed the video within the Design Intent touchpoint page. 

Governance team is encouraged to review the [Pain points, Recommendations, and Opportunities](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2809626855/Pain+points+Recommendations+and+Opportunities) documented by Service Design team during their DI research study. Several of their findings should be taken into consideration while working on this ticket, including:

- DI prep: Long process
- DI prep: Lots to absorb
- Documentation: Context around the documents and expectations is not as clear
- DI Review Meeting: What to expect

### Questions to answer in the video
As a VFS team member, I want to know...

- When should I schedule a Design Intent?
- How do I schedule a Design Intent?
- What should my team do to prepare for the Design Intent?
- Where can I go to ask questions ahead of time?
- Who should be included at the Design Intent?
- What should I expect during the DI meeting?
- What should I expect after the DI meeting?

## Impacted Artifacts
DI touchpoint page

## Tasks
- [x] Please review the Design Intent sections of the General Orientation recordings from [July 2023](https://www.youtube.com/watch?v=ZQuCFvD_mfs), [October 2023 ](https://www.youtube.com/watch?v=hsB_K4B79EQ)and [January 2024](https://www.youtube.com/watch?v=PNuy0YmrXlI) to capture what information has previously been captured when discussing the Design Intent
   - Is there any information that was shared in the recordings that we're not currently capturing?
   - Were there any questions from VFS teams about the Design Intent?
   - Is there anything we can learn from these recordings to help us with our new DI-specific recording?
   - How long was DI discussed in each video?

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have recorded an informational video about the Design Intent and embedded it into the Design Intent touchpoint page on Platform Website

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
How will we measure success of this video?

**Comment by rferguson13** [comment]
@shiragoodman - I wasn't able to view the July 2023 and October 2023 videos — they were marked as "private." Is there a YouTube account I should log in to?

**Comment by rferguson13** [comment]
@allison0034[ Here is the first attempt at the script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2972352514/75014+-+Design+Intent+video+script). I've tried to mirror what Shira covers. There will be visuals to help. Is there more we can cut? Is anything missing?

**Comment by rferguson13** [comment]
@shiragoodman - Is there a VA "branded" slide deck template that I can use for this?

**Comment by shiragoodman** [comment]
@rferguson13 I'm not sure. Let me ask around.

**Comment by allison0034** [comment]
@rferguson13 is that script written the way you are going to read it on the video?

**Comment by allison0034** [comment]
@rferguson13 this is looking really good! When i read it I was at 4ish min so I made some suggestions to cut some things. Take a look! : )

**Comment by rferguson13** [comment]
@shiragoodman - Where can I find the orientation slide deck? I can go off of that :)

**Comment by shiragoodman** [comment]
Hey @rferguson13 ! I just had my bi-weekly 1 on 1 with @naomimarcussen. I caught her up on where we're at with the short video and our research plan. She had some questions and comments, and I think you might find them helpful.

- Naomi asked me how the video and the content on the DI touchpoint page differ from one another. Are they identical? Are they different? Are we suggesting VFS teams do both watch and read the content or are we suggesting they consume one or the other? Or is this more of a high level intro? After chatting, I think the latter is true. We know the video can't contain ALL of the content within the DI page (or else it would be way too long) so it should just be a high level introduction to the Design intent.
- Naomi also suggested that we state the purpose of the video in the video. Communicate that this is a high level intro and they should refer to the content on the page for additional and more descriptive details.
- By keeping it high level, this would benefit us bc we won't need to rerecord the video as often if/when changes to the DI occur.
- Naomi also said that we should communicate why you'd want to watch the video over reading the text.

@naomimarcussen if I misstated anything or left anything out from our discussion, please feel free to let me know!

Also, @rferguson13 - I haven't reviewed the script or anything else yet, so if you're already communicating some of this, awesome!

**Comment by rferguson13** [comment]
@shiragoodman - These are great points! 
- Yes, it's more the latter. The video is meant to be a quick overview whereas the text is the nitty-gritty of the touchpoint. Teams could read the page and get all the information - they would not get all the details from the video. I think that's OK, though. 
- In the video, we do state that it's a high-level overview, but we don't specifically say something like, "If you want more information, read this page." We could definitely add that to the script, though. Since it will be embedded into the page, I think it would be worth having a caption/text along the lines of: "Here's a really quick video overview! Want more details? Continue reading."
- Naomi makes a great point. I'm not sure that should go in the video itself? I think that reasoning should be on the page itself. What are your thoughts?

@allison0034 - You're also familiar with the script - what are your thoughts?

**Comment by rferguson13** [comment]
@allison0034 - Making this a separate comment so it's not lost, but here is [the slide deck](https://docs.google.com/presentation/d/1wX1cj4tKC1GW4ZHR0_TX9BxwRKR6O67uDUpLG7IDMlI/edit?usp=sharing)!

I added some animation, so it may be best to play the slideshow and click through. I can also synchronously walk you through it before I record to see what you think.

**Comment by rferguson13** [comment]
@allison0034 - [Here's a link to the video!](https://www.youtube.com/watch?v=exc0AZb01hA) Let me know what you think.

**Comment by allison0034** [comment]
Looks good!

**Comment by rferguson13** [comment]
@shiragoodman - Want to take a look?

**Comment by shiragoodman** [comment]
@rferguson13 - yes! This was on my to-do list for today but i didn't get it it. I will check it out first thing in the morning! Keep the ticket open for now :)

**Comment by shiragoodman** [comment]
WOW WOW WOW! @rferguson13 that was FANTASTIC! so beautifully put together, and you have a voice perfect for narration. This far exceeded my expectations. Even though it's 30 seconds over the 3 minute mark, it was still quick to consume, both entertaining and educational, and easy to follow along with. 10/10.

**Comment by shiragoodman** [comment]
you can close this ticket :)

**Comment by rferguson13** [comment]
Yay! I'm so glad you like it. I know it's a little over, but I didn't want to cut/read faster last minute. We can always edit it later once we have feedback.

**Comment by shiragoodman** [comment]
@rferguson13 also one last thing - can you make sure you move the video the the Platform Crew YouTube? Right now it looks like its associated with your personal YouTube account. LMK if you need help with this. You can complete this work in ticket #77282.

**Comment by naomimarcussen** [comment]
@rferguson13 I also want to chime in to say how impressed I was with this! Very professional voice-over and clear, concise communication. Can you do all of our videos?!
