### ISSUE TITLE
Create Verbiage for Info Box

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75027]
## Issue Description
Verbiage needs to be created for info box, related to ticket #74635, which will call out the sunsetting of tools Grafana, Loki & Prometheus, while redirecting users to [documentation on accessing Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog). User should also be instructed to direct further questions via #vfs-platform-support channel in Slack.

---
## Tasks
- [x] Draft language for info box
- [x] Review with team

## Acceptance Criteria
- [x] Language draft written
- [x] Team agrees to publish this version

### Verbiage suggested by Joe Tice/Reliability:

> _PLATFORM UPDATE Jan 2024 - As of January 2024 this system is no longer operational, we encourage teams to utilize Datadog, for logging, monitoring and alerting. Access to Datadog can be requested through..._

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Verbiage confirmed, closing ticket.
