### ISSUE TITLE
TEST [FOR TEMPLATE] - TO BE CLOSED

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#75024]
## Value Statement
**_As a_** user type
**_I want to_** job to be done
**_So that_** desired outcome(s)

---
### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

## Design
**Figma links**
- [Mobile](https://www.figma.com/file/4OMA8htpBSEfiRVM2qr5pA/BMT-Spec-Template?type=design&node-id=72-1730&mode=design&t=SPlJD36Qyq1NVsnv-4)
- [Desktop](https://www.figma.com/file/4OMA8htpBSEfiRVM2qr5pA/BMT-Spec-Template?type=design&node-id=72-1563&mode=design&t=SPlJD36Qyq1NVsnv-0)

<img width="414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--320f0331e2bdf5d3328c27d3083ded0ed3ffc483/Screenshot%202024-01-31%20at%2010.27.36%E2%80%AFAM.png" alt="Screenshot 2024-01-31 at 10.27.36 AM.png" />

## Engineering Notes
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
