### ISSUE TITLE
Pension Team Sprint 14 Plan: 01/31/2024—02/13/2024

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75022]
## Sprint 14: 01/31/2024—02/13/2024

**- Outages (PTO, holiday, or unplanned):** 
- Buddhima: 1/31-2/14
- Daniela: 2/2-2/16
- Maya, Wayne, Zack: 2/2
- Zack: 2/5
- Gretchen: 2/6
- Todd: 2/9

## Theme(s):

- Launch form to production for Canary testing phase
- Address any high-priority issues from Canary testing, as needed
- Monitor release data in Datadog, DOMO, Contact Center

## Notes:
- How might we update the Tampermonkey script that does not interfere with e2e testing?
 
## Goal(s):

**RESEARCH/DESIGN**

- [x] Create Pension form usability testing plan #73620
- [x] Move Pension designs to Figma #73188 - **Due date 1/23**
- [x] Document design debt for FE engineering #73621
- [x] Research backlog #74151
- [x] Identify solutions for Copy feedback from Staging Review #74494

**LAUNCH TO PROD / CANARY TESTING**
- Turn on/test flipper to production **on Jan 31**
- [x] Increase traffic to production for Canary testing #73630
- Address any high-priority issues, as needed
- [x] Increase traffic to production to 25% of traffic #73631 - _dependent on success of canary_

**LAUNCH MONITORING**
- [x] Notify Contact Center of release to product (Canary release) #73615
- [x] Daily monitoring of Pension MVP launch in GA/DOMO #73616
- [ ] Daily monitoring of Pension MVP launch in Datadog #73197

**PRODUCT**

- Request CAIA review for URLs #73179

**ENGINEERING**

**_Frontend_**

- [x] Audit web components versions and decide if we opt-out of upgrade for existing v1s **(by 2/9?)** #74170
- [x] Review feedback about Accessibility issues from Staging Review #74505
- [x] Update Confirmation page mailing address #75038
- Other various "fast-follow" frontend tickets

**Backend**

- [ ] Create a e2e solution for testing the PDF creation #72423
- Web form Q&A mapping to PDF testing #74919 - Cancelled/redundant to #72423
- [x] Dependent's Place of Birth is mapped incorrectly #74697
- [x] Improve the order of dependent children's addresses in Overflow #74994
- [ ] Letters in postal code are removed in PDF #74689
- [x] Date format in generated PDF should be updated #75005
