### ISSUE TITLE
Add COVID language for community urgent care providers (in VA's network)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7502]
## User Story or Problem Statement
How might we encourage Veterans to call community urgent care provider locations before visiting?

## Goal
Veterans will be advised to call to confirm hours of operations and availability of location to provide service before proceeding to facilities

## Objectives or Key Results this is meant to further
Objective 2: Deliver meaningful facility information 

---
## Tasks
- [ ] Add language (TBD) to search results card for Community urgent care providers (in VA's network) (both 17 and 20)

Current behavior:
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/e7ee3d32-6fa1-415d-8b06-52a6dd92cfd8)

## Acceptance Criteria
- [ ] When a Veteran searches **urgent care** + **community urgent care providers (in VA's network)**, search result cards include new language
- [ ] When a Veteran searches **community providers (in VA's network)**, the new language is not displayed and existing functionality is maintained. 
- [ ] When a Veteran searches **urgent care** + **VA urgent care**, the new language is not displayed and existing functionality is maintained. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by arickalewis1** [comment]
Here's my proposed language for the card. @peggygannon could you take a look at this for any edits that should happen?

"Before your visit, please call to verify that the facility is open and can provide the care you need."

**Comment by peggygannon** [comment]
@arickalewis1 @mmiddaugh Here's my recommendation for this language: 

Before going to a clinic for urgent care, please call the facility to confirm that it's open and able to provide the care you need.

**Comment by mmiddaugh** [comment]
@brangi please add text (approved by Peggy above)

> Before going to a clinic for urgent care, please call the facility to confirm that it's open and able to provide the care you need.

to bottom of search result cards for **community urgent care providers (in VA's network)**

![urgent care](https://user-images.githubusercontent.com/55411834/78391601-eb898a00-75a3-11ea-9ab5-cbee4e802400.png)
