### ISSUE TITLE
BE | Profile | Direct Deposit | Create PagerDuty service

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#75031]
## Background
Currently, there is no PagerDuty service for Lighthouse's Direct Deposit API.

Create a PagerDuty Service for Lighthouse: Direct Deposit API so that when a scheduled outage occurs, the Profile team can add a maintenance window to the Direct Deposit C&P area of the Profile to inform users of the outage.

## Tasks
- [x] Create a PagerDuty service for Lighthouse's Direct Deposit API in staging.
- [x] Create a PagerDuty service for Lighthouse's Direct Deposit API in production.

## Acceptance Criteria
- [x] Outline steps for adding PagerDuty service.
- [x] Test the PagerDuty service in staging (since the FE component is not created, make sure it shows up in the maintenance windows list being returned from vets-api).
