### ISSUE TITLE
BE | Profile | Disability Ratings | Create PagerDuty service

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#75039]
## Background
Currently, there is no PagerDuty service for Lighthouse's Veteran Service History and Eligibility (VSHE) API.

Create a PagerDuty Service for Lighthouse: VSHE API so that when a scheduled outage occurs, the Profile team can add a maintenance window to the Disability Ratings area of the Profile to inform users of the outage.

## Tasks
- [x] Create a PagerDuty service for Lighthouse's VSHE API in staging.
- [x] Create a PagerDuty service for Lighthouse's VSHE API in production.

## Acceptance Criteria
- [ ] Outline steps for adding PagerDuty service.
- [ ] Test the PagerDuty service in staging (since the FE component is not created, make sure it shows up in the maintenance windows list being returned from vets-api).
