### ISSUE TITLE
[CST] Opt out of V3 web component migration / Audit V1 web components

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#75035]
### Description
The Design System team has recently announced that on February 16th they will be upgrading all web-component to their V3 versions. If we would like to be able to use the existing versions (V1), then we will have to manually opt the components out individually. In order to evaluate what we want to do in response to this, we should determine what the actual effect on the UI would be if we were to do nothing. **Note:** We don't necessarily need to push any code changes, just evaluate what the effect will be in locally

### Engineering notes
This is only for the Claim Status Tool (`src/applications/claims-status` folder). Don't worry about updating components in EVSS folder.

### Background Context
[Slack message from #vfs-change-announcements](https://dsva.slack.com/archives/C03R5SBELQM/p1706549819394489)
<img width="1155" alt="Screenshot 2024-01-31 at 10 41 09 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/6f0ee6ee-b4d5-45c5-8a67-49750d2fea83">

### Tasks
- [x] Manually `uswds=false` flag to all web-component instances in CST
- [x] Create a spreadsheet that documents all instances of web-components that have not yet been updated to their V3 versions

### Acceptance Criteria
- [x] Identify which (if any components) are not utilizing V3 components as part of our design changes for new feature rollouts. 
- [x] Ensure that CST doesn't break due to V3 component migration
- [x] Update every component to set USDWS to false
- [x] Communicate with platform team why we're not migrating our components to V3

**Comment by pmclaren19** [comment]
Started an excel document here https://docs.google.com/spreadsheets/d/1ajKjN6dr-2PzpgEbfX1OqxAupvbqoHwqh7ml1m5a1Fo/edit?usp=sharing

**Comment by HeatherWidmont** [comment]
@samcoforma reviewing today

**Comment by HeatherWidmont** [comment]
@samcoforma did a code review & looks good. 

Not pushed to staging yesterday because pipeline is broken. Platform working on a fix.

**Comment by HeatherWidmont** [comment]
@samcoforma to validate today

**Comment by samcoforma** [comment]
Validated!

**Comment by HeatherWidmont** [comment]
This was estimated conservatively due to us not knowing what we'd find. Reflecting back on how much effort it actually took Peri estimated this was more of a 3
