### ISSUE TITLE
[FE, BE] My VA: Review GH CodeQL scanning policy change

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#75042]
## Background
An announcement was recently made about changes to the GH CodeQL scanning policy. We need to review the policy and our code base/repos to see how this will affect us. Top priority is understanding whether this is a breaking change for us.

## Tasks
- [x] Review announcement
- [x] Review our processes and repos to determine the impact (if anything) on us 
- [x] Attend the office hours scheduled for Thursday 2/1 at 1pm ET (see slack thread for link, also on team calendar)
- [ ] Discuss necessary steps/changes with Profile devs
- [x] Provide summary of findings and impact of change to frontend and backend
- [ ] Work with AJ to create follow-up tickets as needed

## Acceptance Criteria
- [x] Summary is posted in the comments of this ticket outlining the impact of this change (if any) on our workflow and systems
- [ ] We have follow-up tickets created to address any necessary changes (as needed)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Anyone
- _How can this work be validated?_ Summary is provided & follow-up tickets are created

## Resources
- [GH Discussion](https://github.com/orgs/department-of-veterans-affairs/discussions/5)
- [Team slack thread discussion](https://dsva.slack.com/archives/C909ZG2BB/p1706285846636569)
- [VFS all teams slack post about the change](https://dsva.slack.com/archives/CE4304QPK/p1706551200834699)

**Comment by ajakabcin** [comment]
Per discussion on 2/7 in refinements - No significant process changes for the team to account for. This will just be an additional scan that will occur against our PR's. Our existing tests and security measures (unit tests, linting, etc.) should catch these, but this additional scan will catch anything that sneaks through and set off alarms for us to address.
