### ISSUE TITLE
[dev task] NOD | Technical writeup describing manual evidence submission process

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#75045]
## Issue Description

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/71195 we worked with downstream systems to confirm that the evidence uploads manually re-submitted in https://github.com/department-of-veterans-affairs/va.gov-team/issues/70076 were successfully submitted. In addition to this, VA wants us to draft a technical writeup explaining this manual resubmission process.

---
## Tasks
- [ ] Draft technical write-up
- [ ] Get reviewed by Eng and Sade
- [ ] Send to VA

## Acceptance Criteria
- [ ] Write up explains, in sufficient detail, how we manually resubmitted the evidence submissions referenced above.

## Definition of Ready
- [ ] We know what to writeup (explanation of mapping)

## Definition of Done
- [ ] VA is satisfied with writeup

**Comment by saderagsdale** [comment]
@data-doge Can you drop a link to the WIP draft when available? John G. and Angeline from BVA may be looking for this to help them measure any risks they need to discuss.

**Comment by HeatherWidmont** [comment]
@data-doge will share a first draft with @saderagsdale in the ticket & get her feedback

**Comment by data-doge** [comment]
@saderagsdale Here's that draft https://docs.google.com/document/d/13Ywd8rfk5TAz3ldmWIF_qlf3-mBN_fBwApHldnSV1l0/edit?usp=sharing.

**Comment by HeatherWidmont** [comment]
Sade may have time EOD today to review this. Once it is approved it'll be sent to Bo, Jacob, & John Gosnell.

**Comment by saderagsdale** [comment]
Just reviewed. Sending now.

**Comment by HeatherWidmont** [comment]
We will leave this open while the folx at VA review

**Comment by saderagsdale** [comment]
I requested a meeting to review the document and clarify any next steps.

**Comment by HeatherWidmont** [comment]
Updated estimate with what was on the prioritization board (boo for that stuff not syncing on its own)
