### ISSUE TITLE
[Design] Nametag: Update nametag documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#75057]
## Background
We need to update our nametag documentation. We should follow the format of the authenticated menu documentation and treat the nametag like a product as opposed to something that lives under Profile. As part of this effort I've created a draft product/project outline for nametag that lives under the identify and personalization folder [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/nametag). 

We need to create FE documentation and separate use case documentation. We'll be able to leverage much of what is already written [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/nametag/README.md) but we should make sure it's updated to include the latest change we made to support multiple middle initials. ([70821](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70821))
 
## Tasks
- [x] Create FE documentation under the product outline for the nametag [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/nametag/nametag-FE-documentation.md)
- [x] Create use case documentation for the nametag under the product outline for the nametag [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/nametag/nametag-use-case-documention.md)

## Acceptance Criteria
- [x] Complete/updated FE documentation exists
- [x] Complete/updated use case documentation exists

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ PM
- _How can this work be validated?_ review documentation

## Resources
- [Original Nametag documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/nametag/README.md)
- [Example FE documentation - white card component implementation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-small-initiatives/my-va-white-card-component/white-card-component-FE-documentation.md)
- [Example use case documentation - education and training use cases](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/education-and-training-use-cases)

**Comment by mattmarino-adhoc** [comment]
Waiting on completion until we can determine any limits/other specs on middle initial usage that aren't currently documented elsewhere

**Comment by ajakabcin** [comment]
This looks great @mattmarino-adhoc ! Only things missing are links to the figma files in both docs - can you add those and then we're good to close out :)
