### ISSUE TITLE
zenhub ticket error

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#75052]
## Purpose
Consider how to retain the original asks of a ticket while allowing space for modification or additions

## Tasks
- [ ] Determine formatting/style guidance for making edits
   -  Confluence doc
- [ ] share w/ team and garner feedback
- [ ] enact changes

## Acceptance Criteria
- [ ] Guidance on how to alter tickets is aviailable
