### ISSUE TITLE
[View Payments] Opt out of V3 web component migration / Audit V1 web components

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#75051]
### Description
The Design System team has recently announced that on February 16th they will be upgrading all web-component to their V3 versions. If we would like to be able to use the existing versions (V1), then we will have to manually opt the components out individually. In order to evaluate what we want to do in response to this, we would like to opt our components out of this migration

### Engineering notes
This is only for the View Payments app (`src/applications/disability-benefits/view-payment-history` folder)

### Background Context
[Slack message from #vfs-change-announcements](https://dsva.slack.com/archives/C03R5SBELQM/p1706549819394489)
<img width="1155" alt="Screenshot 2024-01-31 at 10 41 09 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/6f0ee6ee-b4d5-45c5-8a67-49750d2fea83">

### Tasks
- [x] Manually add `uswds=false` to all web-component instances in the View Payments app locally (don't need to push the changes)
- [x] Create a spreadsheet that documents all instances of web-components that have not yet been updated to their V3 versions

### Acceptance Criteria
- [x] Identify which (if any components) are not utilizing V3 components as part of our design changes for new feature rollouts. 
- [x] Ensure that the View Payments app doesn't break due to V3 component migration
- [x] Update every component to set USDWS to false
- [x] Communicate with platform team why we're not migrating our components to V3

**Comment by HeatherWidmont** [comment]
@samcoforma to review

**Comment by HeatherWidmont** [comment]
Running into some issues, sounds like it may be a Platform thing. Can't merge until it gets through the pipeline.

**Comment by HeatherWidmont** [comment]
@jerekshoe to validate in parking lot
