### ISSUE TITLE
Establish formatting guidance for editing tickets

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#75055]
## Purpose
Consider how to retain the original asks of a ticket while allowing space for modification or additions.

## Problem Statement
We want to preserve the original asks in a ticket while allowing for flexibility as the ticket owner learns in the space and thinks changes should be made.  We will establish some simple formatting guidelines within the ticket to help identify when something is being changed, removed, or replaced.

## Tasks
- [x] Determine formatting/style guidance for making edits:  [Confluence doc](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2945744983/Editing+Tickets)
- [x] share w/ team and garner feedback

## Acceptance Criteria
- [x] Guidance on how to alter tickets is available
