### ISSUE TITLE
UX | Auth Menu Claims and Disability Rating | Synthesis

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#75059]
## Background 
Now that we've completed our analysis we're ready to synthesize our findings 

## Tasks 
- [ ] Write research summary
- [ ] Have the report peer reviewed
  

## Acceptance Criteria
- [ ] report has been shared with PM/PO
- [ ] we're able to share our findings with the sitewide team and OFCIO

**Comment by andaleliz** [comment]
this was addressed in another ticket.
