### ISSUE TITLE
[Research] Dot Indicator Research: Conduct research study

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#75065]
## Background
Conduct usability testing sessions for the dot indicator. Goal is to get these sessions scheduled and underway within sprint 30 and may carry over into sprint 31.

## Tasks
- [x] Ensure codepen is ready
- [x] Prep materials for collecting feedback/notes 
- [x] Conduct pilot session
- [x] Conduct sessions

**Comment by ajakabcin** [comment]
Marking this to carry over into next sprint as sessions continue next week :)

**Comment by ACParker89** [comment]
A secondary story will be created to encompass further testing for screen readers

**Comment by ajakabcin** [comment]
follow up ticket is #78944
