### ISSUE TITLE
[FE] Perform Accessibility Testing & Create Artifact

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75062]
## Description
As a team, we need to perform accessibility testing so that we can ensure our feature is ready for release. 

## Tasks
- [ ] Create an accessibility ticket/artifact using this [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [ ] Add the HCE-Checkin label to the accessibility ticket
- [ ] Associate the accessibility ticket with the appropriate feature Epic
- [ ] Attach the accessibility ticket to the collab cycle ticket for the feature Epic
- [ ] Complete & check-off each test in the ticket

**Comment by brianseek** [comment]
here is the link to the filled out ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/79046

**Comment by brianseek** [comment]
do we wait for feedback in the other ticket before closing this ticket?

**Comment by loripusey** [comment]
If we have done our testing & created the ticket I think we can close this one
