### ISSUE TITLE
Finalize updated guidance docs for Feature Request process

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#75066]
## Purpose
This work is the finalization of ticket [#72509](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/72509)

1. We need updated guidance for Platform Teams that makes their responsibilities clear in the Feature Request process.
2. We need updated guidance for the Service Design Team that makes our process and responsibilities clear in evaluating and following up on Feature Requests that are submitted.

We need to make sure these questions are answered, possibly by FAQ or within the content of the guide:
 **Some Slack questions from Platform team members:**
1. What if we decide that we don't want to implement the feature? 
2. Or if we can't implement it? 
3. Or if it's too challenging to implement? 
4. Do requests only move off this board if they're completed/implemented? 

Previous ticket's [thinking and planning work](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2897608724/Revisiting+the+Feature+Request+Process)

## Tasks
- [x] Draft an [[updated guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2946727981/redesigned+draft+Feature+request+process+-+User+guide+for+Platform+teams+v2)] that makes it clearer as to what Platform Teams are expected to do for the entire arc of a Feature Request 
- [x] SDT Review of [User Guide for Platform Teams](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2946727981/redesigned+draft+Feature+request+process+-+User+guide+for+Platform+teams+v2)
- [x] Make changes to guide based on team feedback
- [x] Draft an[ internal guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2950758401/Service+Design+Team+internal+guide+Feature+request+process+tasks) for SDT (within [FRP folder](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1746108441/Feature+Request+Process)) that makes the process clear for regular review of submissions and subsequent review of the board.
   -  What is the process/frequency for submission review?
   -  What is the process/frequency for board review?
- [x] SDT Review of [Internal User Guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2950758401/Service+Design+Team+internal+guide+Feature+request+process+tasks)
- [x] Make changes to guide based on team feedback
- [x] share updated process and documentation with Platform teams (Demo day?  Slack announcement?  Bryan share w/ PM's in Product CoP?)

## Acceptance Criteria
- [x] [User Guide for Platform team](https://vfs.atlassian.net/wiki/spaces/AP/pages/1909293082/Feature+request+process+-+User+guide+for+Platform+teams) is available
- [x] Internal Guide for SDT is available
- [x] Answers to Slack questions can be found in User Guide for Platform Teams
- [x] Updated process is shared

**Comment by gopixelsgo** [comment]
This ticket will continue into next sprint for completion of remaining tasks:

-  SDT Review of Internal User Guide
-  Make changes to guide based on team feedback
-  share updated process and documentation with Platform teams (Demo day? Slack announcement? Bryan share w/ PM's in Product CoP?)
-  Update ongoing FR ticket with reference to new internal guide
