### ISSUE TITLE
<Review of 686c/674 Form Updates> from <Benefits - Dependent Experience Team>

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#75068]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to start collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

**Note:** If you’re already partnering with us on an initiative, you don't need to fill out this request form. If you don’t have access to your initiative’s CAIA epic, post a message in the [#sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-acessibility-ia) slack channel and tag `@Terry Nichols` and `@Lily Strelich`.

## About your team

- **Team name**: Benefits - Dependent Experience
- **OCTO product owner:** Emily Theis
- **Product name:** 21-868c and 21-674 online form flow
- **Product manager:**  Laura Steele
- **Slack channel:** #benefits-dependents-management
- **Dedicated content writer on your team (if you have one):** none
- **Dedicated a11y specialist on your team (if you have one):** none
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Veterans are submitting online 686/674 claims that generate outdated pdf claim forms, are missing information, and/or contain information that is no longer required. Downstream systems (RBPS) need to offramp these claims for manual processing, which delays the Veteran's benefits. Our desired outcome: Veterans submitting online 21-686c and 21-674 claims can trust that their submissions include all the required information to ensure efficient processing.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
We have initial designs drafted, and we completed the Design Intent on 1/30/2024. We are currently working to incorporate feedback from Design Intent.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [x] [Design intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74958) (1/30/2024)
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** #74059 

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687976281975/2a9c6ca9ea6d955afa7977c777bbb72b15280903?sender=u934f98f179a86c76e6ee9592) 686c Form Simple Flow (and future changes)
- [Figma](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&mode=design&t=o5XCj8n60B1SAqFw-1)
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/dependents/Initiative-Brief-686-674-Form-Updates.md)
- [Form Tool Page](https://www.va.gov/view-change-dependents/)
- [About 21-686c](https://www.va.gov/find-forms/about-form-21-686c/)
- [About 21-674](https://www.va.gov/find-forms/about-form-21-674/)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA operations
- [ ] Initial Review - @coforma-terry and @strelichl 
```

```[tasklist]
### CAIA a11y tasks
```

```[tasklist]
### CAIA content tasks
```

```[tasklist]
### CAIA IA tasks
```

**Comment by steele-lm** [comment]
cc @ajialeilani and @jstrothman

**Comment by ajialeilani** [comment]
Hi @strelichl @coforma-terry I'm curious about what kind of timeline we can expect from the review. We should have finalized designs in Figma a week from now

**Comment by ajialeilani** [comment]
@strelichl 12-12:30 on 2/21 would be great—thank you. 

 If I have more specific questions before then. Can I ask them here or is it better to wait until office hours?

**Comment by steele-lm** [comment]
@ajialeilani Takeaways from CAIA kickoff:

- Send invite to CAIA for Midpoint review scheduled for 2/23.
- Create Content Source of Truth and post to SharePoint, so CAIA can review all text in one place.
- Confirm how the interview-style online form handles the additional/supplemental forms outlined in paper form.
- CAIA may have some feedback on areas outside the purple areas in Figma.

**Comment by ajialeilani** [comment]
@strelichl forwarded the invite to midpoint. Let me know if you don't see it for some reason.

**Comment by EvanAtCoforma** [comment]
Hey @steele-lm and @strelichl , the [accessibility review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76841#issuecomment-1960172797) for the Figma prototypes is complete. Please let me know if you have any issues with the feedback so I can provide clarification. Thanks!

**Comment by aprocik1** [comment]
Thanks for following up, @ajialeilani. Our goal is to start reviewing your form next week. We've talked about content sources of truth as a team with Beth and Danielle. For smaller projects, we're exploring Figma as a source of truth. Since this is a bigger project, we'd like to use a SharePoint document to record content recommendations for future reference. Let me know if that works for you.

**Comment by ajialeilani** [comment]
@aprocik1 Thanks for your update. That makes sense—it is a bit, meandering form. I'll have a Sharepoint doc ready for you by Monday.

**Comment by ajialeilani** [comment]
Hi @aprocik1 do ya'll have a template for a Sharepoint SoT? Something that covers error messages and other dependent states?

**Comment by ajialeilani** [comment]
Hi @aprocik1 @katherine-fung—regarding a hard deadline for this review, this is rather urgent due to the V3 changeover in May and other projects that stakeholders are eager to see implemented after this one. Given that it's our team's top priority, we're curious what would be realistic for you. We'll also meet with our front-end team soon and it's possible a more specific deadline will come out of that.

**Comment by katherine-fung** [comment]
Hi @ajialeilani @steele-lm @jstrothman, 

Our team has made content recommendations for the 686c/674 in the source of truth document: https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Dependents%20Management/content-and-screenshots/686c_674%20Content%20source%20of%20truth.docx?d=w2c65a672bc3948b3a36ff8047f571c11&csf=1&web=1&e=xox3UV 

Notes: 

- There are a few outstanding questions I have for SMEs. I've highlighted the relevant copy in aqua in the SOT, to note that we should return to this copy once we get clarification from SMEs about what the copy needs to ask. Let me know if you have any questions!  

- I made recommendations only to first version of the "introduction page (not authenticated)" in the Word doc. Please copy these recommendations over to other version of the introduction page for authenticated users, etc. 

- You'll see that I commented in the doc about needing static page content to provide information about what applicants need to submit in different use cases. We'll need to chat with Beth about how to best approach that static content. 

cc @aprocik1 @strelichl

**Comment by katherine-fung** [comment]
One more note @ajialeilani @steele-lm @jstrothman - when we share this with SMEs for review, could we ask them to focus on the accuracy of the copy? We've made specific choices here for plain language (i.e. the PDF uses the word "affidavit" and we're suggesting "signed statement" instead), active voice, and VA.gov style standards. We're happy to make changes to make copy more accurate, but it may save the SMEs time reviewing if they don't edit for style or voice.

**Comment by ajialeilani** [comment]
Thank you @katherine-fung! I second that approach.

**Comment by ajialeilani** [comment]
@strelichl @aprocik1 I've updated the Figma files with content from the source of truth with a few changes I'd ask you to review when you get the chance: 

- There are a few places I broke pages up into smaller sections to align more with one-thing-per-page guidelines. Do my headers still align with the SoT?
  - [Add child identification info](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=1326%3A206565&mode=design&t=mudQ828KmPhfareZ-1)
  - [Student list loop / ID info](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=1317%3A185333&mode=design&t=mudQ828KmPhfareZ-1) (Platform governance asked that list loop cards be kept shorter)
  - [Student income info](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=1326%3A207317&mode=design&t=mudQ828KmPhfareZ-1) (I also made the pension messaging a question that would show income questions conditionally)
- [Dynamic student's name in headers](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=1326%3A196966&mode=design&t=mudQ828KmPhfareZ-1)
    - This is so applicants can determine which student they're answering questions about in the event they're adding more than one student
    - Could also show Dynamic student's name as H3's and other headers as H4's
- Minor changes to [file upload](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=1326%3A210308&mode=design&t=mudQ828KmPhfareZ-1) pages based on [VADS pattern](https://www.figma.com/file/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?type=design&node-id=2988%3A63596&mode=design&t=FoNYRnYedcfRO7VI-1).
- I'm creating a [flow](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=1328%3A221215&mode=design&t=mudQ828KmPhfareZ-1) to help devs understand the logic for adding one or more children from our various groups. I'd love to get your eyes on it if you have a chance.

**Comment by ajialeilani** [comment]
Thanks, @aprocik1! One more thing—we were curious about the reason for aria-live-polite rather than alerts for conditional messaging about files that will need to be submitted. We know 527EZ uses alerts for similar messaging. Are we not doing the same mainly to avoid alert fatigue?

**Comment by jstrothman** [comment]
@aprocik1 @ajialeilani Here's an [example in Figma of the alerts we use in the Pension 527EZ](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2719-26402&mode=design&t=Uu0ERESuObwLm3oE-4)

**Comment by katherine-fung** [comment]
Hey @ajialeilani, I've reviewed most of these changes and they look good. 

I do have a few questions: 
1. [link to the Figma comment](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7?type=design&node-id=1291-95742&mode=design#784906268)
2. For the header "[Student’s name]’s income received in the year the school term begins," is this referring to the student's income in the year the CURRENT school term begins? I just realized on re-reading this may seem vague to some users, so I may tweak this to be more clear. 

Thanks! 

cc @aprocik1

**Comment by katherine-fung** [comment]
Hi @ajialeilani @jstrothman, 

Our guidance is continously evolving as we work on VA products. We learned a lot of lessons from the pension form and other projects since. After consulting with the a11y specialists on CAIA, we think the best solution here is to announce new information without using alerts, as you mentioned, to avoid alert fatigue. 

Here's the advice from one of our a11y specialists back in March: 

> "You can programmatically set focus to it using JavaScript so users are immediately directed to the new content and can hear it being announced. also add aria-live=polite to it. This attributes a good choice as it allows the screen reader to finish its current announcement before announcing the new content. No need for an alert imo" 

Let us know if you have any questions. Thanks! 

cc @aprocik1

**Comment by ajialeilani** [comment]
Thanks for looking these over @katherine-fung—

1. SSN and where was the child born should have been separated. I've made the correction and resolved the comment. 
2. That header in the PDF refers to question 11 " OFFICIAL BEGINNING DATE OF REGULAR TERM OR COURSE," which Kayce confirmed to be "Date of whatever term they started." So I understand the headings in financial info to be "First year you attended school" and "The following year." 
3. I'm still working on the flow. I'll ping you when it's ready.

**Comment by ajialeilani** [comment]
@katherine-fung @aprocik1 are either of you opposed to me updating the H1/breadcrumb to "File a claim to add or remove dependents on your VA benefits" and putting in a request with Lighthouse to have the title in the Claim Status Tool (eventually) align with that?

**Comment by ajialeilani** [comment]
Hi @katherine-fung @aprocik1 

I reviewed the confirmation and reminder emails that go out through VA Notify in connection with 686c/674. I've added changes to the bottom of the [Source of Truth doc](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Dependents%20Management/content-and-screenshots/686c_674%20Content%20source%20of%20truth.docx?d=w2c65a672bc3948b3a36ff8047f571c11&csf=1&web=1&e=xox3UV). 
I'll post them here as well with screenshots of the original content. 

Thanks!

### Confirmation email
[H1] We’ve received your claim to add or remove dependents on your VA benefits

Dear ((first_name)),

Your claim to add or remove dependents on your VA benefits has been submitted for review. You don’t need to do anything unless we send you a letter asking for more information. Once we process your claim, we’ll mail you a letter with our decision.

<p> You can also check the status of your claim online.

[Color link] Check the status of your claim online

<p> Note: It may take 7 to 10 days after you apply for your claim to appear online.

[card]
Application details:
Claim to add or remove dependents on your VA benefits (VA Forms 21-686c and/or 21-674)
Date submitted:
((date))
[end card]

Thank you,
VA

You’re receiving this email because you started an application on [VA.gov](http://va.gov/). Please don’t reply to this email. If you need to contact us, visit [va.gov](http://va.gov/) or call [800-827-1000](tel:8008271000). We’re here Monday through Friday 8:00 a.m. through 9:00 p.m. ET.

### Reminder email

[H1] You have an unfinished claim on [VA.gov](http://va.gov/)

Dear ((first_name)),

We’re writing to let you know that you have an application still in progress. Make sure you complete your application so we can properly process your request.

[Card]
Claim to add or remove dependents on your VA benefits (VA Forms 21-686c and/or 21-674)
[color link] Continue your claim </mark></span>
Application expires on ((date))
[end card]

Thank you,
VA

You’re receiving this email because you started an application on [VA.gov](http://va.gov/). Please don’t reply to this email. If you need to contact us, visit [va.gov](http://va.gov/) or call [800-827-1000](tel:8008271000). We’re here Monday through Friday 8:00 a.m. through 9:00 p.m. ET.

![image (24)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/67ca9a03-7e4e-4124-b708-dec78412adf6)
![image (25)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/c8814a3b-8682-4225-b9b1-9a56c6a382dd)

**Comment by ajialeilani** [comment]
Hi @katherine-fung @aprocik1 ,

Couple of questions about 21-674 that surfaced during PDF mapping: 

1. Can I add an "Other" with a conditional text field option to the benefit/program question to cover for if this list is not exhaustive: 
<img width="451" alt="Screen Shot 2024-05-23 at 11 08 29 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/b444d1b7-b3bf-4e94-8420-0a41795209b9">
<img width="463" alt="Screen Shot 2024-05-23 at 12 43 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/53453983-abf2-4739-9090-01a239baa081">

2. Can you confirm which question in the PDF this question is equivalent to if any?

> When did the student  enroll in the federal education program or school?

Screenshots for reference: 

<img width="654" alt="Screen Shot 2024-05-23 at 12 54 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/87484697-a01e-40ee-9b13-91d9e8624f9b">
<img width="979" alt="Screen Shot 2024-05-23 at 12 49 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/573709d5-52ca-4e32-8074-202d8331ba4d">

**Comment by katherine-fung** [comment]
Hi @ajialeilani! 

1. Yes, it's fine to add "Another program" as an option to that question. In the conditional field, we can just say, "Briefly list any other programs..." (I don't think VA.gov uses parentheses to indicate singular/plural - I could be wrong about this, but it's also just fine to use the plural). 

2.  Looking at this now, I'm actually not sure. It might be trying to ask the PDF question 9c "Date payments began." Is there another question in the online form that asks when payments began? If there is already a different question in the online form that asks when payments began, then I'm really not sure why we put "When did the student enroll in the federal education program or school?" question in the online form. (and we could probably remove it??)

**Comment by ajialeilani** [comment]
Thanks @katherine-fung. I'll add "Another program" with the conditional field copy without parentheses. And we do ask for date payments began on the page following the programs checkbox group, so I'll remove the "When did the student enroll..." question.

**Comment by ajialeilani** [comment]
Hi @katherine-fung,

Here are the latest updates to a [flow for adding one or more children](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=1308%3A181475&t=5R2Q6DTBILkYUDVu-1). Let me know if this is decipherable / aligns with your vision. 

cc @strelichl @aprocik1

**Comment by katherine-fung** [comment]
Hi @ajialeilani! The flow looks great, and aligns with the content source of truth. Thanks so much for working with us to implement the changes!!

**Comment by ajialeilani** [comment]
Hi @katherine-fung I added hint text to the school/program question (equivalent to 9A) to further distinguish it from the program/benefit question (equivalent to 9B) based on Brandi's feedback (pictured below). We were confused looking at this section during PDF mapping and concerned Veterans would be confused also. Let me know if this addition makes sense or if you think the labels are enough or if there are other opportunities to further clarify program/benefit vs. school/program. 

cc: @strelichl @aprocik1 
<img width="979" alt="Screen Shot 2024-06-07 at 11 40 42 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/30f4fbc9-cd14-41f8-a584-8251e0df68e0">
<img width="381" alt="Screen Shot 2024-06-07 at 11 36 43 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/af911e60-b4c8-446d-bd55-e0de33ee9bbf">
<img width="385" alt="Screen Shot 2024-06-07 at 11 36 27 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/dabd3330-5fc4-4dd2-b711-9cf9a5246f41">
<img width="890" alt="Screen Shot 2024-06-07 at 11 26 30 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/36579bcc-d7ed-4b14-8719-fd45f3786c75">

**Comment by katherine-fung** [comment]
Thanks for the clarification @ajialeilani! In that case, can we tweak the question too? 

What's the name of the federally funded school or program the student is enrolled in? 
[Hint text] This is the school or trade program the student attends

**Comment by ajialeilani** [comment]
Hey @katherine-fung ! I think that's an improvement. I'll update the mockups. Thank you!

**Comment by ajialeilani** [comment]
Hi @katherine-fung @strelichl - just wanted to check in to see if you'd gotten a chance to look at our [reminder and confirmation email updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75068#issuecomment-2127693657). If not, do you have an estimate of when you'd be able to review them? Many thanks for all your work on this!

**Comment by katherine-fung** [comment]
Hi @ajialeilani! I'm working on these emails today.

**Comment by ajialeilani** [comment]
Hi @katherine-fung @aprocik1 @strelichl - 

Our SMEs let us know that we need to include a "Remarks" section to 674 for form parity, which I've added [here](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=1924-80780&t=G6VFxi5vU5qlwQ7Z-1). Would love your review / any recommendations you can make as far as how to handle "Remarks" or how other forms do so. 

According to [the PDF](https://www.vba.va.gov/pubs/forms/VBA-21-674-ARE.pdf), the remarks section is specifically for section III overflow (which is already being captured), and if the student has school-related expenditures that could be deducted from their net worth (for Pension recipients). But it may be that we need to keep it more general to capture other Veteran remarks. 

Thanks!

**Comment by katherine-fung** [comment]
Hi @ajialeilani, 

I've reviewed the reminder email content in the SOT doc, and left recommendations there. I've also tweaked the confirmation email copy to use the word "request" instead of "claim" as I mentioned on Slack. 

https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B2C65A672-BC39-48B3-A36F-F8047F571C11%7D&file=686c_674%20Content%20source%20of%20truth.docx&action=default&mobileredirect=true

For context, our team hasn't finalized a template for reminder emails yet, and we're not sure of our timeline for doing so. But we wanted to get you the copy for this specific email. At some point in the future, once we have a template, we may revisit all the reminder emails for VA forms to make sure they align with the new template. 

Let me know if you have any questions! 

cc @aprocik1

**Comment by steele-lm** [comment]
@strelichl Thanks for reaching out! The launch of our phase 1 (backend) changes was delayed, so we're now tracking to have our phase 2 (front end) changes out sometime in the Sept/Oct time frame. How far out would you like to meet? I can stick a reminder on my scheduled to touch base at that point!

**Comment by ajialeilani** [comment]
Hi @strelichl —

We recently had to update our List & Loop patterns in our designs from the single page to the preferred multi-page pattern. These updates included some minor content changes, so we wanted to make you aware. Here are the pages where changes were made (content changes are mainly to H3 headers and button copy):

- [Spouse's former marriages](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=1207-19162&t=9Ty4uYYt4iQYVM33-1) and [Veteran's former marriages](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=1291-91839&t=9Ty4uYYt4iQYVM33-1)
- [Add one or more children](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=2694-70864&t=9Ty4uYYt4iQYVM33-1)
- [Add one or more students](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=2698-101620&t=9Ty4uYYt4iQYVM33-1)
- [Remove a dependent who has died](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=2761-114768&t=9Ty4uYYt4iQYVM33-1)
- [Remove a stepchild who left your household](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=1006-137667&t=9Ty4uYYt4iQYVM33-1)
- [Remove a child under 18 who got married](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=1007-140850&t=9Ty4uYYt4iQYVM33-1)
- [Remove a child between ages 18 and 23 who stopped attending school](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=1008-143468&t=9Ty4uYYt4iQYVM33-1)

cc @steele-lm

**Comment by aprocik1** [comment]
@ajialeilani, I think all of this work is complete. Can we close this ticket? Or, should we keep it open for any near term support requests you're expecting?

**Comment by ajialeilani** [comment]
Hi @aprocik1 I think we're keeping it open to sync on widget work a month out from launch. @steele-lm correct me if I'm wrong.

**Comment by aprocik1** [comment]
@ajialeilani, thanks for the update. Do you have an estimated launch date yet?

**Comment by ajialeilani** [comment]
Hi @aprocik1, we're hoping to launch before the holiday break (late December). 

We're ready to start work on alert language/experience to inform Veterans returning to their saved in-progress forms of the phase 2 updates ([Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97629)). Can we continue work on the alert in this ticket or should we start a new ticket for this work? 

cc: @steele-lm @strelichl

**Comment by ajialeilani** [comment]
If we are able to use this ticket, here's the [mockup](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=3607-35894&t=6VbyLPxmE0TkiFGp-1) for the post-launch alert (incorporated into the existing progress-saved alert).

**Comment by ajialeilani** [comment]
Hi @aprocik1 - 

We identified a need for another post-launch alert for Veterans with active sessions during the update who attempt to submit their form. 

In this instance, the submission will fail, and we'll redirect the Veteran to the intro page again and prompt them to review their entries with the updated form prior to attempting to submit again (similar to the alert for in-progress saved forms). 

Here is my [drafted language](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=4206-16299&t=scN1dJ4BnD5gAGCw-1) for that alert. This is an edge case,  but we still want to prepare for it. I'm also open to alternative alert placements, if you deem them more appropriate (review page, 404 style page, etc.)

**Comment by aprocik1** [comment]
@ajialeilani, great catch! I just left a recommendation and question for you in a [comment](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7?node-id=4144-8281#1086371464) in your Figma file. Thanks for flagging this.

**Comment by ajialeilani** [comment]
Hi @aprocik1 thanks for taking a look. Replied to your comments in [Figma](https://www.figma.com/design/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?node-id=4144-8281&t=IFdk4uPMbd2WOlr8-1). 

@Dene-human mentioned in [this thread](https://dsva.slack.com/archives/C07RB9N9M6J/p1736889590654959?thread_ts=1736888025.749039&cid=C07RB9N9M6J) that BP leads are working on a pattern to standardize how we handle update versioning. Not sure if that'll influence your recommendations. Thanks again!

**Comment by mistymg** [comment]
@marvolpe @va-agw Since you all are assigned to [this task](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/78?pane=issue&itemId=59437561&issue=department-of-veterans-affairs%7Cva.gov-team%7C80538) and it's related to this epic, I've assigned you to the epic.

**Comment by mistymg** [comment]
Closing out this old epic. We moved any still open tickets to a newer [epic](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/78?filterQuery=dependents&pane=issue&itemId=108786308&issue=department-of-veterans-affairs%7Cva.gov-team%7C108896)
