### ISSUE TITLE
Track recurring themes in Veteran feedback

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#75070]
## Task Description
The VAOS team wants to better understand how our work affects users, and what they value the most. We'll use two sources of qualitative feedback:
- Weekly Medallia Reports
- Regular User Research

From these we will identify recurring themes in feedback, and develop tools to track how responses that fit those themes change over time.

## Notes and References
- User feedback in Sharepoint (requires VA network)
- [Thematic analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/themes.md)

## Acceptance Criteria
- [ ] Thematic analysis of past user research is complete
- [ ] Medallia feedback is coded with themes
- [ ] A VAOS team member can easily see how often these themes come up every week.

## Deliverables
-

**Comment by outerpress** [comment]
Duplicate, closing
