### ISSUE TITLE
Identify recurring themes in Veteran feedback

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#75072]
## Task Description
The VAOS team wants to better understand how our work affects users, and what they value the most. We'll use two sources of qualitative feedback:
- Weekly Medallia Reports
- Regular User Research

From these we will identify recurring themes in feedback, and develop tools to track how responses that fit those themes change over time.

## Notes and References
- User feedback in Sharepoint (requires VA network)
- [Thematic analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/themes.md)

## Acceptance Criteria
- [x] Thematic analysis of past user research is complete
- [x] Medallia feedback is coded with themes
- [x] A VAOS team member can easily see how often these themes come up every week.

**Comment by outerpress** [comment]
Thematic analysis is complete, and themes were used as starting point for coding Medallia feedback (see Medallia feedback folder/analysis docs)
