### ISSUE TITLE
Change `/mdot/supplies` route to `/supplies`

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#7507]
## User Story or Problem Statement
As a backend developer, I need to modify the code to allow vets-api to successfully integrate with the DLC's API. Part of this work will require me to change some headers, along with add some new ones. I will also need to change the routes the MDOT::Client tries to make calls to, from `/mdot/supplies` to `/supplies`

## Goal
That all tests pass, that the API can successfully make calls using betamocks provided responses as the actual DLC API is not deployed in staging at this point in time.

## Tasks
- [x] Change API Endpoints from `/mdot/supplies` to just `/supplies`
- [x] Ensure API key is added to requests as a header called `va_api_key`
- [x] Ensure last four of SSN is added to requests as a header called `va_veteran_id`
- [x] Ensure veteran birth date is added to requests as a header called `va_veteran_birth_date`

## Acceptance Criteria
- [x] Calls successfully return data object that includes permanent_address, temporary_address (if the veteran has one) and an array of supplies that the veteran is eligible to order from.
---
