### ISSUE TITLE
Design | Burial | Form Component Audit

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#75079]
## Description
Announcement: https://dsva.slack.com/archives/C03R5SBELQM/p1705503589174489

_On February 16 all design system web components will default to their v3 variant. v3 will become opt out only. The design system team will be switching all web components to render their v3 variant automatically. If teams have a need to fall back to the original v1 variant, they will be able to do so by setting the uswds prop to false. However, v1 variants will eventually be fully retired and removed so opting out is discouraged._

Our forms will be opting out of the update. However, to prepare to eventually update, we need to document the components within each the form and identify the type of component and what version it is.

## Tasks

- [x] Identify the form components in the form
- [ ] Identify the owner of the component (Platform vs our team)
- [x] Identify the version of the component
- [ ] Identify if any customization has been made to the component

## Acceptance Criteria
- [ ] List of form components and related information posted in appropriate GitHub repository

**Comment by fiorella-io** [comment]
### v3 Components that are used in Burial designs:
- [Alert](https://design.va.gov/components/alert#examples---slim-alert---v3)
- [Card](https://design.va.gov/storybook/?path=/docs/components-va-card--default): for service periods and previous names
- [Button ](https://design.va.gov/components/button/#examples---v3)
- [Checkbox](https://design.va.gov/components/form/checkbox#examples---group---v3)
- [Radio button](https://design.va.gov/components/form/radio-button#examples---v3)
- [Privacy statement](https://design.va.gov/components/form/privacy-agreement#examples---v3): in the review page
- [Memorable date](https://design.va.gov/components/form/memorable-date#examples---v3): For date of birth. Our designs have Month as dropdown. I'll inquire with the DS team
- [Text input](https://design.va.gov/components/form/text-input#examples---v3)
- [Select](https://design.va.gov/components/form/select#examples---v3)
- [Progress bar segmented](https://design.va.gov/components/form/progress-bar-segmented#examples---v3): We are suing the default example
- [Process list](https://design.va.gov/components/process-list#examples---v3): Our designs has v1 but I change it to v3. This lives on our intro page

**Comment by steele-lm** [comment]
Thanks, @fiorella-io! Would it be helpful to create a doc in GitHub that lists all the design components and version? I don't know if that is potentially helpful for future component migrations or form updates.
