### ISSUE TITLE
Build, edit and publish careers Apply page in Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#75096]
## Issue Description

Continuing work from [72023](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72023):

[How to apply for Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/)

We need to build the page in Drupal, review, and publish.
---
## Tasks
- [x] Build Drupal page (Victoria)
- [x] Review (Megan/Sara)
- [x] Publish (Megan/Sara)
- [x] Send live page to State Department for QA (Randi)
- [x] Input any changes (Juliana)
- [x] Review 
- [x] Open ticket with PW to add Spanish toggle (Randi)

## Acceptance Criteria
- [x] Spanish page is live
- [x] Ticket for PW to create Spanish toggle has been created
---

**Comment by RLHecht** [comment]
@strelichl @ABeltran77 Here's the content back from State. This page is ready to be built in Drupal.



[LS-2024-0122945-SPA-FINAL_How to apply for Veteran Readiness and Employment.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14376517/LS-2024-0122945-SPA-FINAL_How.to.apply.for.Veteran.Readiness.and.Employment.docx)

**Comment by megzehn** [comment]
Update: I started building this page out for a Drupal training with @saratorres2 and Victoria: http://preview-prod.vfs.va.gov/preview?nodeId=66669

We'll pick it up again once they gain access to Drupal.

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2 @megzehn I picked from where we left, Megan, and completed the building of the Spanish page in Drupal. It is save and ready to review and publish. Please let me know if you have any questions or comments.

"Cómo tramitar la solicitud para el programa de Preparación y Empleo de Veteranos"

https://preview-prod.vfs.va.gov/preview?nodeId=66669

**Comment by juliana-jara** [comment]
Hi Randy. 
This page needs some updates. You can find the suggested changes and reasoning behind some of those [here](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2375096/[Notes-Juliana.docx](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2375096/Notes-Juliana.docx?d=w0d47536d1f55494abba85be00ac86021&csf=1&web=1&e=fSpY8w)?d=w0d47536d1f55494abba85be00ac86021&csf=1&web=1&e=fSpY8w).
Thank you and please let me know if you have any questions.

**Comment by juliana-jara** [comment]
Sorry! Not sure what happened with that one. Try this one: https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2375096/[Notes-Juliana.docx](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2375096/Notes-Juliana.docx?d=w0d47536d1f55494abba85be00ac86021&csf=1&web=1&e=qqami6)?d=w0d47536d1f55494abba85be00ac86021&csf=1&web=1&e=qqami6

**Comment by RLHecht** [comment]
Thanks! I added comments to this doc. let me know if you have questions!

**Comment by RLHecht** [comment]
You can go ahead and make these updates. Thank you!

**Comment by juliana-jara** [comment]
@RLHecht Changes have been made! https://prod.cms.va.gov/como-tramitar-la-solicitud-para-el-programa-de-preparacion-y-empleo-de-veteranos

**Comment by RLHecht** [comment]
Thanks! This page is now ready to publish once I notify the stakeholders. Then we can send the link to State to QA.

**Comment by RLHecht** [comment]
Just published this. Will send to State once it's live.

**Comment by juliana-jara** [comment]
@RLHecht Wondering if this ticket can be moved to "Validate"? Thanks!

**Comment by RLHecht** [comment]
@juliana-jara Here is the doc back from State. Can you review the QA changes they are suggesting and make them in Drupal? Let me know if there are any you disagree with or want to discuss. Thanks!

[LS-2024-0125469 -LQA Notes-es_v1__VA.gov VRE page.docx](https://github.com/user-attachments/files/20128512/LS-2024-0125469.-LQA.Notes-es_v1__VA.gov.VRE.page.docx)

**Comment by juliana-jara** [comment]
@RLHecht I made the edits and saved them as draft. Please note that the very first edit already looked like their suggestion (they wanted to adjust the capitalization of the H1 but it already looked the way they wanted it to look,.

**Comment by RLHecht** [comment]
I published these changes and opened the ticket with PW. Going to close this.
