### ISSUE TITLE
[Design] 10-10EZ User flows in Mural

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#75118]
## Issue Description
Alignment updates to the existing various wireframes, user flows and UX form documentation. 

In Mural, there is [brand new Platform guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md) on how to document product user flows.

User flows: 
- capture each data point in the form via an individual sticky note 
- show all conditionals and forks
- contains a key with elements defined
- account for all possible use cases and paths through the form including short form and unauth vs authenticated

We also have the existing source of truth mural flow that is screen captures - this can be deleted but make sure to download a copy to upload to github for archive and to capture all important notes (LOA etc)

- [NEW MURAL SOURCE OF TRUTH](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487613901/3f988d8dd69c59340e4b850ef5caf362fa490927?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks
- [x] Download and archive existing Mural and make sure everything needed is captured
- [x] Re-create main source of truth user flows for the EZ in Mural: 
- [x] Unauthenticated full form flow
- [x] Unauthenticated short form flow 
- [x] Authenticated full form flow
- [x] Authenticated short form flow
- [x] [Registration MVP flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487582087/34c3dab41845b8a2ca33afa97e05671703ca8395?sender=uadf1ed7fe7c76f0914967329)

## Acceptance Criteria
- A source of truth for all user flows and wireframes that have been updated to the newest guidance or migrated in Mural
---

**Comment by jessicastump** [comment]
- Learned that there will not be a wireframe library in Figma built by Platform / Design System team. The [user flow guidance can be found here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md).
- Going to repurpose this ticket to clean up the source of truth user flows in Mural and follow latest guidance. 
- [The work-in-progress board is started here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487613901/3f988d8dd69c59340e4b850ef5caf362fa490927?sender=uadf1ed7fe7c76f0914967329)

**Comment by jessicastump** [comment]
The archived user flow can be found in the [Figma archive file](https://www.figma.com/design/NyfaJz57FJNftF7fFxLvAP/10-10EZ-Archive?node-id=4-2&t=f4jjZEotZwSLJZsk-0) -- (we can upload to github if needed too?)

**Comment by jessicastump** [comment]
@hdjustice and @aagosto90 Before I close this ticket - can y'all take a quick look and check that I didn't miss anything here please? - [Link to new Mural user flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487613901/3f988d8dd69c59340e4b850ef5caf362fa490927?sender=uadf1ed7fe7c76f0914967329) - for auth and unauth and short form. I will move this to validate for now :)
