### ISSUE TITLE
[Design] 10-10CG User flows in Mural 

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#75125]
## Issue Description
Alignment updates to the existing various wireframes, user flows and UX form documentation. 

In Mural, there is [brand new Platform guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md) on how to document product user flows.

We also have the existing source of truth mural flow that is screen captures - this can be deleted but make sure to download a copy to upload to github/Figma as image for archive

---
## Tasks
- [x] Download and archive the existing [Mural content](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687288632872/0728ba8a597b439671741c573fbba777ad0dac16?sender=uadf1ed7fe7c76f0914967329), place image in github and/or Figma archive page
- [x] Re-create main source of truth user flows for the CG in Mural - [started here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687288632872/0728ba8a597b439671741c573fbba777ad0dac16?sender=uadf1ed7fe7c76f0914967329)
- [x] Make sure after July 1 updates go live, there is ONE source of truth user flow Mural 

## Acceptance Criteria
- A source of truth for all user flows and wireframes that have been updated to the newest guidance
---

**Comment by jessicastump** [comment]
Updated user flow for July updates have been added to the [same Mural board with a note](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687288632872/0728ba8a597b439671741c573fbba777ad0dac16?sender=uadf1ed7fe7c76f0914967329). PDF of current/soon to be archived user flow added to [github here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/ux-capture/ARCHIVED-1010%20CG%20User%20Flow_2024-07-01.pdf).
