### ISSUE TITLE
[Content] Create SMS Notifications for OH BT reminders and notifications

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#75127]
## Tasks

- [ ] Create the SMS notifications for OH BT reminders and notifications. Work with Ariel Hicks on some of the messages that are on the appt reminders side vs. day of BT-specific texts (which we're responsible for). ~Waiting to confirm which [userflow](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=306%3A2015&mode=design&t=hZyXrcNYRaQhlXRg-1) we're going with.~ 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75127?planning-poker) with Zenhub @kellysmith1008

**Comment by benbrasso-agile6** [comment]
Moved into validate. Set up meeting with Kristen, Ari and Justin to do a hand off.

**Comment by benbrasso-agile6** [comment]
Gonna close this

**Comment by benbrasso-agile6** [comment]
https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=749-7283&mode=design&t=isBsbcJsWe17YANT-4
