### ISSUE TITLE
Silence 'gsub' logs + Benefits Claims dashboard adjustments

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#75135]
## Issue Description
Some menial tasks post the most recent migrations
- Find a way to responsibly silence `gsub` logs, mostly likely through an external team
- Adjust Benefits Claims dashboard with some findings during the most recent rollout
- Fix percentages in the BC and ITF dashboards that seem to have broken recently

---
## Tasks
- [ ] Find a way to responsibly silence `gsub` logs, mostly likely through an external team
- [ ]Adjust Benefits Claims dashboard with some findings during the most recent rollout
- [ ]Fix percentages in the BC and ITF dashboards that seem to have broken recently

## Acceptance Criteria
- [ ] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
