### ISSUE TITLE
Add opt out of VA.gov analytics to Platform Orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75137]
## User Story
As a Platform team member, I want to ensure that all new VA.gov team members opt out of Google Analytics on their browsers and mobile devices so that their usage supporting the website is not tracked as an end user of VA.gov.

Assignee: @allison0034 
Peer Reviewer: @rferguson13 

## Description
All teams and individuals supporting VA.gov are asked to opt out of Google Analytics on their browsers and mobile devices to help ensure that their visits to the VA.gov website are not tracked. The Google Analytics tracking should only be for actual Veterans and end users of VA.gov. 

Although a [Slack reminder](https://dsva.slack.com/archives/CE4304QPK/p1706806826670899) is posted periodically on the #vfs-all-teams channel, new team members may miss it. To ensure that new team members are opting out, we want to add this step to the New VFS Team Member ticket as part of Platform Orientation. 

## Impacted Artifacts
[New VFS Team Member](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D) gh template

## Tasks
- [x] Add step to the General section of the New VFS Team Member ticket for opting out of VA.gov analytics. Include link to opt out page.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] New VFS team members are asked to opt out of va.gov analytics

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@rferguson13 I have requested your review on the PR.

**Comment by rferguson13** [comment]
@allison0034 - looks good!
