### ISSUE TITLE
Custom Survey Video Instruction 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#75141]
## Issue Description
As a User requesting a custom survey, I need an instructional video to assist in completing the request form so that I can choose the correct type of survey to collect feedback from identified URLs. 
## Tasks
- [ ] _Using the Intake form create a script to narrate how to complete the form 
- [ ] Choose editing software 
- [ ] Create a script 
- [ ] Create video intro 
- [ ] Record video 
- [ ] Edit video
- [ ] QA video
- [ ] Create thumbnail
- [ ] Embed video on intake form 
- [ ] Test usability 
- [ ] Publish Intake form with video 

## Acceptance Criteria
- [ ] **User requests a custom survey with instructional video**
  - The user wants to request a custom survey and needs an instructional video to assist in completing the request form.
  - The user needs the video to help them choose the correct type of survey to collect feedback from identified URLs.

- [ ] **Create script for video narration**
  - Using the Intake form, a script needs to be created to narrate how to complete the form.

- [ ] **Choose editing software**
  - The team needs to choose an editing software to create and edit the instructional video.

- [ ] **Create script for video**
  - A script needs to be created for the instructional video.

- [ ] **Create video intro**
  - An introduction needs to be created for the instructional video.

- [ ] **Record instructional video**
  - The instructional video needs to be recorded.

- [ ] **Edit instructional video**
  - The recorded video needs to be edited.

- [ ] **Perform QA on instructional video**
  - The instructional video needs to be tested for quality assurance.

- [ ] **Create thumbnail for video**
  - A thumbnail image needs to be created for the instructional video.

- [ ] **Embed video on intake form**
  - The instructional video needs to be embedded on the intake form.

- [ ] **Test usability of video on intake form**
  - The usability of the instructional video on the intake form needs to be tested.

- [ ] **Publish intake form with instructional video**
  - The intake form, including the instructional video, needs to be published.

**Comment by ATMiddleton** [comment]
Custom Survey Intake Form - #74620
