### ISSUE TITLE
[Content] Create (or version out) content for Need Help component

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#75163]
## Tasks

- [x] Create (or version out) content for Need Help component. (Decide if we need different content per page. E.g., Auth page vs. BT question pages vs. success page vs. error pages.) Waiting to confirm which [userflow](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=306%3A2015&mode=design&t=hZyXrcNYRaQhlXRg-1) we're going with. 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Added @ytsaoca to help with creating a component in MHV - Unified Appointments Library that we can apply to the frames.

**Comment by kellysmith1008** [comment]
Looked through our current need help pages and created a draft of proposed need help in figma. Tagged Bena nd Ya-ching in the file and will wait for them to respond.

**Comment by kellysmith1008** [comment]
Hahahaha - whoops! typo :)

**Comment by ytsaoca** [comment]
Created the component in the library. Has't publish it yet.
And we need to think about the naming :)
https://www.figma.com/file/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?type=design&node-id=482%3A2354&mode=design&t=Boi3LhQwx0rODZcS-1

**Comment by benbrasso-agile6** [comment]
@cgednalske you mind swapping to this in the frames showing Need Help in the OH Design page?

**Comment by benbrasso-agile6** [comment]
Done
