### ISSUE TITLE
[CST] Create design mock for closed claim in new V2 detail page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#75165]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to see that my claim has been closed and access my decision letter from the new V2 UI
**_So that_** I can view the status of my claim and decision

---
## Background Context

We need a mock up for what a closed claim looks like in the new [V2 detail pages UI](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74247). 

### New Feature
- [Epic Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74062)

## Design

Original DDL design
<img width="824" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5454b5ae5d193553bd2337cddb67539a56337695/Screenshot%202024-02-01%20at%203.14.31%E2%80%AFPM.png" alt="Screenshot 2024-02-01 at 3.14.31 PM.png" />

Current design (no letter)
<img width="1034" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5684a5e0a0d330ee834ac28adb0652441ff273b5/Screenshot%202024-02-01%20at%203.13.54%E2%80%AFPM.png" alt="Screenshot 2024-02-01 at 3.13.54 PM.png" />

## Engineering 
- Add here

## Out of scope
- Closed state for all claims. This mock will just be for disability compensation claims. 

## Open questions
- Add here

## Tasks
- [ ] Create new page for the mock in the [Evidence Submission spec](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-1&mode=design&t=B9mPX9jrrdJHZFII-11)
- [ ] 

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Product performs functional QA and verifies acceptance criteria was met
- [ ] Engineering identifies staging users required to test and shares account and credentials with product

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_
