### ISSUE TITLE
[CST] [Design] Create design mock for closed claim in new V2 detail page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#75166]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to see that my claim has been closed and access my decision letter from the new V2 UI
**_So that_** I can view the status of my claim and decision

---
## Background Context

We need a mock up for what a closed claim looks like in the new [V2 detail pages UI](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74247). 

### New Feature
- [Epic Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74062)

## Design

**Figma links:**
- [Closed Claim](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=1124-8264&mode=design&t=BNEC5JGv9uutVi23-0)

Original DDL design
<img width="824" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5454b5ae5d193553bd2337cddb67539a56337695/Screenshot%202024-02-01%20at%203.14.31%E2%80%AFPM.png" alt="Screenshot 2024-02-01 at 3.14.31 PM.png" />

Current design (no letter)
<img width="1034" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODhmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5684a5e0a0d330ee834ac28adb0652441ff273b5/Screenshot%202024-02-01%20at%203.13.54%E2%80%AFPM.png" alt="Screenshot 2024-02-01 at 3.13.54 PM.png" />

## Engineering 
- Add here

## Out of scope
- Closed state for all claims. This mock will just be for disability compensation claims. 

## Open questions
- Add here

## Tasks
- [x] Create new page for the mock in the [Evidence Submission spec](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-1&mode=design&t=B9mPX9jrrdJHZFII-11)

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Product performs functional QA and verifies acceptance criteria was met
- [ ] Engineering identifies staging users required to test and shares account and credentials with product

## Acceptance Criteria
- [x] _Design distinguishes closed state from open state in such a way that the user can clearly distinguish the two_
- [x] _Designs have been determined feasible by the engineering team_
- [x] _Designs meet site accessibility standards_

**Comment by SilkeDannVA** [comment]
Showing this at the cross-functional sync for feedback.

**Comment by skylerschain** [comment]
Reviewed at XFN Sync 3/23 with team for feedback.

Final designs are [here](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=1143-14986&mode=design&t=qJzOmnrltoOr1Z66-4).

**Comment by skylerschain** [comment]
Added Figma mocks to Design section. 

@davidakennedy Could you do an a11y check on [the proposed designs ](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=1124-8264&mode=design&t=BNEC5JGv9uutVi23-0)? I don't anticipate there will be any a11y issues given the nature of what we're doing here, but it'd be good to double check.

**Comment by davidakennedy** [comment]
I reviewed this design, and don't see any accessibility issues. @skylerschain and I chatted about me doing some light accessibility annotations for the headings, and asking the engineers how they use the annotations in a future parking lot discussion.
