### ISSUE TITLE
Update Style Guide with Hyperlink in heading guidance 

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#75187]
Our Style guide does not explicitly state that users should not put hyperlinks in their headings. In several places, our guide links out to other guides that say not to put hyperlinks in headings. But our guide should explicitly say it. Why? Well, for two reasons:

1. A users is unlikely to follow additional links when referring to our style guide for guidance. 
2. Our 26th Tip of the Sprint is about not putting hyperlinks in headings because it has been an issue our team has encountered lately while deploying pages. 

### TASKS

- [x] Determine language for guidance
- [x] Determine best location(s) in style guide for guidance
- [x] Update Style guide. 

### Definition of Done

- [x] Style guide now includes guidance not to put hyperlinks in headings.
