### ISSUE TITLE
Create reusable GHA partials for anything versioned in CI

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#75203]
## Issue Description
While updating the GitHub actions versions, it was painfully aware of how much repeated code we have for actions that require a versioning declaration. While creating a reusable partial wouldn't necessarily be less lines of code in the actions workflows, it would make it where we could manage the versions in one place instead of in what was as many as 32 places in some cases.

---
## Tasks
- [ ] Create reusable partials for GHA for any actions that require a version or sha declaration. These should contain input parameters that allow arguments to be passed to them accordingly.
- [ ] Replace all existing instances of these actions with the reusable partial and pass arguments accordingly
- [ ] Test all altered workflows to ensure functionality.

## Acceptance Criteria
- [ ] All workflow versioning is now managed in one place per action.
