### ISSUE TITLE
vets-website eMIS removal of externalService EMIS & EMISRedis descriptions

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#75204]
## Issue Description
Originally eMIS removal was part of one PR, however there were a number of E2E failures and the eMIS removal is now being broken apart into different PRs in an attempt to isolate where the errors are occurring and address those on an individual basis.

This ticket addresses specifically the removal of externalService EMIS & EMISRedis descriptions - see prior attempt here - https://github.com/department-of-veterans-affairs/vets-website/pull/27743/files

These are more likely to be causes some of the E2E errors seen here - https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/vets-website-cypress-reports/85a0596b-214e-47e3-970a-74a9e9dd90e8.html

## Tasks
- [x] Remove references to externalService EMIS in vets-website in a single commit each
- [x] Remove references to EMISRedis descriptions in a single commit each
- [x] Identity failures and the source
- [x] Log and troubleshoot any failures

## Acceptance Criteria
- [x] EMIS references stated above are removed and all CI tests pass

**Comment by rmtolmach** [comment]
My work to remove veteran-status in vets-api (https://github.com/department-of-veterans-affairs/va.gov-team/issues/75657) ended up needing vets-website changes. So my PR, https://github.com/department-of-veterans-affairs/vets-website/pull/27851, will cover the changes documented in this ticket.

In short, this ticket can be closed or converted to a different eMIS ticket.

**Comment by rjohnson2011** [comment]
Once @rmtolmach 's PR is in https://github.com/department-of-veterans-affairs/vets-website/pull/27851 this will be clear on how much is remaining for this ticket.

**Comment by jennb33** [comment]
@rjohnson2011 has a branch open for this currently. There was a spec failure and he is re-running when this is encountered.

**Comment by rjohnson2011** [comment]
The failing spec is located at `src/applications/personalization/profile/tests/e2e/account-security/downtime.cypress.spec.js` 
Currently commenting this out to pass specs while looking into if this can be modified for emis removal or if it is no longer relevant and can be deleted.

**Comment by rjohnson2011** [comment]
PR created here - https://github.com/department-of-veterans-affairs/vets-website/pull/28352
Awaiting review from frontend team before merging.

**Comment by rjohnson2011** [comment]
PR approved and merged.
