### ISSUE TITLE
vets-website eMIS removal of downtimeNotification components & remaining references

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#75205]
## Issue Description
Originally eMIS removal was part of one PR, however there were a number of E2E failures and the eMIS removal is now being broken apart into different PRs in an attempt to isolate where the errors are occurring and address those on an individual basis.

This ticket addresses specifically the removal of downtimeNotification components & remaining references - see prior attempt here - https://github.com/department-of-veterans-affairs/vets-website/pull/27743/files

These are the most likely causes of various E2E errors seen here - https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/vets-website-cypress-reports/85a0596b-214e-47e3-970a-74a9e9dd90e8.html

## Tasks
- [x] Remove references to downtimeNotification components in vets-website in a single commit each
- [x] Remove references to remaining eMIS references in a single commit each
- [x] Identity failures and the source
- [x] Log and troubleshoot any failures

## Acceptance Criteria
- [x] EMIS references stated above are removed and all CI tests pass

**Comment by rjohnson2011** [comment]
Started a branch to remove deprecated EMIS components in each separate commit to check for errors in the test suite. Currently passing specs by removing the external services emis downtime notification component and continuing the epic tasks.

**Comment by jennb33** [comment]
@rjohnson2011 idea is to connect the specs or remove them entirely. This will be coordinated with the FE team before proceeding.

**Comment by rjohnson2011** [comment]
PR approved, passing all specs & CI checks. Merged and closed! https://github.com/department-of-veterans-affairs/vets-website/pull/28497
