### ISSUE TITLE
[Design][Content] Create final frames with content for error pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#75206]
## Tasks

- [ ] Create final frames with content for error pages
- [ ] [Link expired / no LoROTA entry](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=388-1989&mode=design&t=tHPFTxTHDQAKH4DD-4)
- [ ] [Error / no token](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=388-2882&mode=design&t=tHPFTxTHDQAKH4DD-4) 
- [ ] [BTSSS service down / Know before ID auth](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=486-3071&mode=design&t=tHPFTxTHDQAKH4DD-4)

[Userflow](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=306%3A2015&mode=design&t=hZyXrcNYRaQhlXRg-1)

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75206?planning-poker) with Zenhub @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@cgednalske all of the error pages are on the page with content. Just need to work with @kellysmith1008 as she updates some of the content.

**Comment by kellysmith1008** [comment]
Will go through the error messages today for content validation

**Comment by cgednalske** [comment]
@benbrasso-agile6 @kellysmith1008 are we all set with this ticket? Looks like content was approved 👀

**Comment by kellysmith1008** [comment]
@cgednalske Give me through this afternoon - I'm still just double-checking that I've hit all the content and reviewed it. But it should be set to close by, let's say 1pm your time.

**Comment by kellysmith1008** [comment]
@cgednalske I left a few comments and I think you've addressed them all - I'm good to close this if you are!

**Comment by cgednalske** [comment]
Sounds good - closing! 🎉
