### ISSUE TITLE
Staging Review AMA/Decision Review Follow-on

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7521]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA2-releaseplan.md) 
- ~Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_~
- QA Test Plan -- [GitHub](#7636) ; [TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/262):
  - [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/52)
  - [Summary(Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/53)
- Link to your accessibility test cases:
  - Tze-chiu Lei has 2 A11y test-cases in [this QA Test Run](https://dsvavsp.testrail.io/index.php?/runs/view/264&group_by=cases:section_id&group_order=asc) \[see T2319 & T2320]
  - **TestRail** [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc) **OR**
  - **Markdown** [Github accessibility test cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/accessibility-test-cases-template.md)
- List of known issues (with links to tickets when applicable)

## Meeting attendees from **requesting team**
- Product Manager (required): Mickin Sahni
- DEPO product lead (required): Jen Lee (considering optional)
- Anyone else from your team who significantly contributed to the artifacts provided (required): Laura Walsh (considering optional)

## Scheduling
Preferred dates or times: 
- 4/7 ~3:30-5p ET~ 4-5p ET
- 4/8 2:30-3:30p, 4-5p ET

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by MickinSahni** [comment]
👋 @tzelei when you have a moment, looking for some help on these items from the list of prerequisite artifacts above before I submit it to @andreahewitt-odd & @meganhkelley. 


> Link to your product test cases/test plan in TestRail with test execution logs (learn more) for QA practice area review
Link to your Coverage for References and Summary(Defects) reports in TestRail for QA practice area review
Link to your accessibility test cases:
TestRail TestRail VSP accessibility test plan template OR
Markdown Github accessibility test cases template


Think we said the QA portion [would be covered here.](
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7153#issuecomment-605286119)

Is there anything else necessary?

**Comment by MickinSahni** [comment]
@jenstrickland for your awareness!

**Comment by meganhkelley** [comment]
Hey @MickinSahni apologies I'm just seeing this — what is your ideal scheduling for this review? Let me know and I'll get something on the calendar!

**Comment by MickinSahni** [comment]
@jenstrickland I preempted your sharing of spot-check feedback here with [AMA Pt. 2 "Critical/Serious" Accessibility Spot Check Items](#7637) so we can get it on the books asap. Feel free to add the other findings as/where you need.

**Comment by jenstrickland** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7637

**Comment by andreahewitt-odd** [comment]
Scheduled for 3/9 1:30 ET

**Comment by tlei123** [comment]
@MickinSahni , re. all the expected Staging-Review artifacts...

I've confirmed w/ @pjhill that -- taking a page from A11y's Must/Should/Consider stratification -- Regression Test artifacts are "Should" right now \[not "Must"]

For the others:

- Regular QA Test Plan is ready now, which includes the A11y Test Cases you listed in #6421 .
- Coverage for References and Summary(Defects) - should be ready by end of tmrw (Wed).  These are basically the results from my Test Runs.
- Accessiblity Test Plan template -- I'm gonna check w/ @jenstrickland about that, but at least I have the A11y case in my regular QA Test Plan.  I'll keep you posted.

**Comment by pjhill** [comment]
> @MickinSahni , re. all the expected Staging-Review artifacts...
> 
> I've confirmed w/ @pjhill that -- taking a page from A11y's Must/Should/Consider stratification -- Regression Test artifacts are "Should" right now [not "Must"]
> 
> For the others:
> 
> * Regular QA Test Plan is ready now, which includes the A11y Test Cases you listed in #6421 .
> * Coverage for References and Summary(Defects) - should be ready by end of tmrw (Wed).  These are basically the results from my Test Runs.
> * Accessiblity Test Plan template -- I'm gonna check w/ @jenstrickland about that, but at least I have the A11y case in my regular QA Test Plan.  I'll keep you posted.

Thanks Tze!  I'm excited to see your test execution reports.  It will be the first time we are going through the whole QA process up to the reporting stage for collab cycle, so I would love your feedback about how useful each of the artifacts is for your own development process.

Is [this](https://dsvavsp.testrail.io/index.php?/plans/view/262) the test plan that you're using @tzelei ?

**Comment by tlei123** [comment]
> Is [this](https://dsvavsp.testrail.io/index.php?/plans/view/262) the test plan that you're using @tzelei ?

Yes, @pjhill .  That's the correct Test Plan.

**Comment by tlei123** [comment]
Re. Coverages for References and Summary (Defects) TestRail reports...

I have just 1 test-case to retest tmrw (Wed) morning before generating these reports.  I just wanna double-check that the untested case-step wasn't just a network problem from this evening.

Will update the links above once the reports are generated on TR.

**Comment by tlei123** [comment]
@pjhill , AMADR2 test-runs completed, reports generated.

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/262)
- [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/52)
- [Summary \(Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/51)

**Comment by tlei123** [comment]
> @MickinSahni , re. all the expected Staging-Review artifacts...
> 
> I've confirmed w/ @pjhill that -- taking a page from A11y's Must/Should/Consider stratification -- Regression Test artifacts are "Should" right now [not "Must"]
> 
> For the others:
> 
> * Regular QA Test Plan is ready now, which includes the A11y Test Cases you listed in #6421 .
> * Coverage for References and Summary(Defects) - should be ready by end of tmrw (Wed).  These are basically the results from my Test Runs.
> * Accessiblity Test Plan template -- I'm gonna check w/ @jenstrickland about that, but at least I have the A11y case in my regular QA Test Plan.  I'll keep you posted.

re. A11y test plan template artifact: Per [quick Slack-chat](https://dsva.slack.com/archives/CQV81GBBM/p1586290673008100) w/ @jenstrickland & @1Copenut , we should be okay with the two A11y test-cases in my [regular QA Test Run for Content](https://dsvavsp.testrail.io/index.php?/runs/view/264&group_by=cases:section_id&group_order=asc) \[see T2319 & T2320].

**Comment by jenstrickland** [comment]
For reference, the urls to check — in the VA environment — are:

<hr>
1. Decision reviews and appeals —  [https://preview-prod.vfs.va.gov/preview?nodeid=3071](https://preview-prod.vfs.va.gov/preview?nodeid=3071)


2. After you request a decision review — https://preview-prod.vfs.va.gov/preview?nodeId=3008


3. Supplemental Claims — [https://preview-prod.vfs.va.gov/preview?nodeId=3011](https://preview-prod.vfs.va.gov/preview?nodeId=3011)


4. Higher-Level Reviews — [https://preview-prod.vfs.va.gov/preview?nodeId=3003](https://preview-prod.vfs.va.gov/preview?nodeId=3003)


5. Board Appeals — [https://preview-prod.vfs.va.gov/preview?nodeId=3029](https://preview-prod.vfs.va.gov/preview?nodeId=3029)


6. After a Board Appeal — [https://preview-prod.vfs.va.gov/preview?nodeId=3013](https://preview-prod.vfs.va.gov/preview?nodeId=3013)


7. Contested Claims — [https://preview-prod.vfs.va.gov/preview?nodeId=3030](https://preview-prod.vfs.va.gov/preview?nodeId=3030)


8. Fiduciary claims — [https://preview-prod.vfs.va.gov/preview?nodeId=3016](https://preview-prod.vfs.va.gov/preview?nodeId=3016)


9.  Insurance claims — [https://preview-prod.vfs.va.gov/preview?nodeId=3025](https://preview-prod.vfs.va.gov/preview?nodeId=3025
)


10.  FAQs — [https://preview-prod.vfs.va.gov/preview?nodeId=3004](https://preview-prod.vfs.va.gov/preview?nodeId=3004)


11. Get help with review request — [https://preview-prod.vfs.va.gov/preview?nodeId=3009](https://preview-prod.vfs.va.gov/preview?nodeId=3009)


12. Board hearings with a VLJ — [https://preview-prod.vfs.va.gov/preview?nodeId=3010](https://preview-prod.vfs.va.gov/preview?nodeId=3010)

**Comment by emilywaggoner** [comment]
Can someone who has functioning CAG access post screenshots of the pages in question? Having CAG trouble.

@jenstrickland @tlei123

**Comment by jenstrickland** [comment]
@emilywaggoner Will do. Incoming!

**Comment by jenstrickland** [comment]
1. Decision reviews and appeals — [https://preview-prod.vfs.va.gov/preview?nodeid=3071](https://preview-prod.vfs.va.gov/preview?nodeid=3071)

![Screen Shot 2020-04-08 at 3 18 24 PM (2)](https://user-images.githubusercontent.com/57469/78824447-5aa01d80-79ac-11ea-824e-f56d121b5c7d.png)

![Screen Shot 2020-04-08 at 3 18 31 PM (2)](https://user-images.githubusercontent.com/57469/78824457-5ecc3b00-79ac-11ea-8481-ce2fdb63b633.png)


![Screen Shot 2020-04-08 at 3 18 38 PM (2)](https://user-images.githubusercontent.com/57469/78824471-6390ef00-79ac-11ea-980a-c598ba2fee6b.png)

**Comment by jenstrickland** [comment]
2. After you request a decision review — https://preview-prod.vfs.va.gov/preview?nodeId=3008

![Screen Shot 2020-04-08 at 3 20 55 PM (2)](https://user-images.githubusercontent.com/57469/78824609-a357d680-79ac-11ea-8163-98020047a843.png)


![Screen Shot 2020-04-08 at 3 21 07 PM (2)](https://user-images.githubusercontent.com/57469/78824597-9e932280-79ac-11ea-98d3-cbe1df791a69.png)

**Comment by jenstrickland** [comment]
3. Supplemental Claims — https://preview-prod.vfs.va.gov/preview?nodeId=3011

![Screen Shot 2020-04-08 at 3 22 40 PM (2)](https://user-images.githubusercontent.com/57469/78824820-f9c51500-79ac-11ea-8cee-a2551fde3360.png)

![Screen Shot 2020-04-08 at 3 22 52 PM (2)](https://user-images.githubusercontent.com/57469/78824846-08133100-79ad-11ea-9a75-bf9861448a35.png)

![Screen Shot 2020-04-08 at 3 23 00 PM (2)](https://user-images.githubusercontent.com/57469/78824859-0d707b80-79ad-11ea-96ff-da110e533a38.png)

![Screen Shot 2020-04-08 at 3 23 10 PM (2)](https://user-images.githubusercontent.com/57469/78824868-12352f80-79ad-11ea-8947-577444fedea4.png)


![Screen Shot 2020-04-08 at 3 23 17 PM (2)](https://user-images.githubusercontent.com/57469/78824887-182b1080-79ad-11ea-8f89-12f59175e299.png)

**Comment by jenstrickland** [comment]
4. Higher-Level Reviews — https://preview-prod.vfs.va.gov/preview?nodeId=3003

![Screen Shot 2020-04-08 at 3 27 08 PM (2)](https://user-images.githubusercontent.com/57469/78825355-d51d6d00-79ad-11ea-8429-a2a0fbc68577.png)


![Screen Shot 2020-04-08 at 3 27 20 PM (2)](https://user-images.githubusercontent.com/57469/78825370-dbabe480-79ad-11ea-8afa-61bbe230488e.png)

![Screen Shot 2020-04-08 at 3 27 27 PM (2)](https://user-images.githubusercontent.com/57469/78825383-e0709880-79ad-11ea-9621-879117b75f9f.png)

![Screen Shot 2020-04-08 at 3 27 35 PM (2)](https://user-images.githubusercontent.com/57469/78825392-e6667980-79ad-11ea-9b34-1866b66d6425.png)

![Screen Shot 2020-04-08 at 3 27 45 PM (2)](https://user-images.githubusercontent.com/57469/78825404-ebc3c400-79ad-11ea-9ca7-07c0ddadeae3.png)

![Screen Shot 2020-04-08 at 3 27 54 PM (2)](https://user-images.githubusercontent.com/57469/78825413-f1210e80-79ad-11ea-9ba2-afd66d0cdbd4.png)


![Screen Shot 2020-04-08 at 3 28 01 PM (2)](https://user-images.githubusercontent.com/57469/78825428-f716ef80-79ad-11ea-8b81-ce42385ee203.png)

![Screen Shot 2020-04-08 at 3 28 05 PM (2)](https://user-images.githubusercontent.com/57469/78825439-fc743a00-79ad-11ea-9261-1f78162ae02b.png)

**Comment by jenstrickland** [comment]
5. Board Appeals — https://preview-prod.vfs.va.gov/preview?nodeId=3029

![Screen Shot 2020-04-08 at 3 35 21 PM](https://user-images.githubusercontent.com/57469/78826002-d26f4780-79ae-11ea-9e6c-6305284f5491.png)

![Screen Shot 2020-04-08 at 3 35 39 PM](https://user-images.githubusercontent.com/57469/78826009-d602ce80-79ae-11ea-8221-60578928126d.png)

![Screen Shot 2020-04-08 at 3 35 58 PM](https://user-images.githubusercontent.com/57469/78826021-d9965580-79ae-11ea-8553-d0988b81f290.png)

![Screen Shot 2020-04-08 at 3 36 16 PM](https://user-images.githubusercontent.com/57469/78826030-dd29dc80-79ae-11ea-9149-4d3a6e7f889e.png)

![Screen Shot 2020-04-08 at 3 36 31 PM](https://user-images.githubusercontent.com/57469/78826039-e155fa00-79ae-11ea-8f14-9d6bb1d23885.png)

![Screen Shot 2020-04-08 at 3 36 45 PM](https://user-images.githubusercontent.com/57469/78826051-e61aae00-79ae-11ea-8fe5-19c68c2c31c2.png)

**Comment by jenstrickland** [comment]
6. After a Board Appeal — https://preview-prod.vfs.va.gov/preview?nodeId=3013

![Screen Shot 2020-04-08 at 4 19 26 PM (2)](https://user-images.githubusercontent.com/57469/78829723-dbfbae00-79b4-11ea-9e15-6334e2977213.png)

![Screen Shot 2020-04-08 at 4 19 48 PM (2)](https://user-images.githubusercontent.com/57469/78829732-df8f3500-79b4-11ea-8bd6-dc398ecd0c1f.png)

![Screen Shot 2020-04-08 at 4 20 03 PM (2)](https://user-images.githubusercontent.com/57469/78829741-e322bc00-79b4-11ea-93f5-c4778255681b.png)

**Comment by jenstrickland** [comment]
7. Contested Claims — https://preview-prod.vfs.va.gov/preview?nodeId=3030

![Screen Shot 2020-04-08 at 4 23 27 PM](https://user-images.githubusercontent.com/57469/78830137-7a880f00-79b5-11ea-9a94-b1e9dedf296c.png)


![Screen Shot 2020-04-08 at 4 23 41 PM](https://user-images.githubusercontent.com/57469/78830153-81168680-79b5-11ea-939c-7b51990a0c35.png)


![Screen Shot 2020-04-08 at 4 23 57 PM](https://user-images.githubusercontent.com/57469/78830167-8673d100-79b5-11ea-9ffb-c41b7cdd65c3.png)


![Screen Shot 2020-04-08 at 4 24 16 PM](https://user-images.githubusercontent.com/57469/78830182-8b388500-79b5-11ea-8ae4-f00392fe200d.png)


![Screen Shot 2020-04-08 at 4 24 30 PM](https://user-images.githubusercontent.com/57469/78830198-8ffd3900-79b5-11ea-8048-4f7b8aaa9a29.png)

**Comment by jenstrickland** [comment]
8. Fiduciary claims — https://preview-prod.vfs.va.gov/preview?nodeId=3016

![Screen Shot 2020-04-08 at 4 26 48 PM](https://user-images.githubusercontent.com/57469/78830422-e8ccd180-79b5-11ea-8a9c-4275bc44977f.png)

![Screen Shot 2020-04-08 at 4 27 04 PM](https://user-images.githubusercontent.com/57469/78830429-eec2b280-79b5-11ea-8a5f-b1327294f0af.png)


![Screen Shot 2020-04-08 at 4 27 20 PM](https://user-images.githubusercontent.com/57469/78830442-f4b89380-79b5-11ea-8952-33e6aec71c60.png)

![Screen Shot 2020-04-08 at 4 27 34 PM](https://user-images.githubusercontent.com/57469/78830448-f97d4780-79b5-11ea-8215-971f05d10242.png)


![Screen Shot 2020-04-08 at 4 27 46 PM](https://user-images.githubusercontent.com/57469/78830458-fe41fb80-79b5-11ea-99dc-2a688f16d928.png)

**Comment by jenstrickland** [comment]
9. Insurance claims — https://preview-prod.vfs.va.gov/preview?nodeId=3025

![Screen Shot 2020-04-08 at 5 23 08 PM](https://user-images.githubusercontent.com/57469/78835207-c5a62000-79bd-11ea-8098-df2f49413b03.png)


![Screen Shot 2020-04-08 at 5 23 24 PM](https://user-images.githubusercontent.com/57469/78835218-ca6ad400-79bd-11ea-9936-ecc426e2c7d9.png)


![Screen Shot 2020-04-08 at 5 23 39 PM](https://user-images.githubusercontent.com/57469/78835238-d060b500-79bd-11ea-9e06-2860e0a18825.png)


![Screen Shot 2020-04-08 at 5 23 51 PM](https://user-images.githubusercontent.com/57469/78835250-d3f43c00-79bd-11ea-8f6a-dede334f6502.png)


![Screen Shot 2020-04-08 at 5 24 04 PM](https://user-images.githubusercontent.com/57469/78835262-d787c300-79bd-11ea-8d79-494618ad6b20.png)

**Comment by jenstrickland** [comment]
10. FAQs — https://preview-prod.vfs.va.gov/preview?nodeId=3004

![Screen Shot 2020-04-08 at 5 26 17 PM](https://user-images.githubusercontent.com/57469/78835455-33eae280-79be-11ea-9d71-f84e43d19f2e.png)

![Screen Shot 2020-04-08 at 5 26 32 PM](https://user-images.githubusercontent.com/57469/78835466-377e6980-79be-11ea-8c6d-06af39d623eb.png)

![Screen Shot 2020-04-08 at 5 26 45 PM](https://user-images.githubusercontent.com/57469/78835472-3a795a00-79be-11ea-8f48-af79b0b6c1e9.png)

![Screen Shot 2020-04-08 at 5 27 00 PM](https://user-images.githubusercontent.com/57469/78835479-3e0ce100-79be-11ea-834e-58265dd0f553.png)

![Screen Shot 2020-04-08 at 5 27 10 PM](https://user-images.githubusercontent.com/57469/78835488-4107d180-79be-11ea-9620-9a8588142a3f.png)

**Comment by jenstrickland** [comment]
11. Get help with review request — https://preview-prod.vfs.va.gov/preview?nodeId=3009

![Screen Shot 2020-04-08 at 5 28 49 PM](https://user-images.githubusercontent.com/57469/78835651-8b894e00-79be-11ea-838c-9a48e923d770.png)

![Screen Shot 2020-04-08 at 5 29 01 PM](https://user-images.githubusercontent.com/57469/78835660-8f1cd500-79be-11ea-818d-75ffa2eb1220.png)

![Screen Shot 2020-04-08 at 5 29 12 PM](https://user-images.githubusercontent.com/57469/78835663-9217c580-79be-11ea-9ba9-930a72c3c2ff.png)

![Screen Shot 2020-04-08 at 5 29 24 PM](https://user-images.githubusercontent.com/57469/78835674-9512b600-79be-11ea-97f9-26e7133ec4c4.png)

**Comment by jenstrickland** [comment]
12. Board hearings with a VLJ — https://preview-prod.vfs.va.gov/preview?nodeId=3010

![Screen Shot 2020-04-08 at 5 33 24 PM](https://user-images.githubusercontent.com/57469/78836029-3d287f00-79bf-11ea-9c29-72b8da272872.png)

![Screen Shot 2020-04-08 at 5 33 36 PM](https://user-images.githubusercontent.com/57469/78836037-40236f80-79bf-11ea-9de6-2afc08b7cf4a.png)

![Screen Shot 2020-04-08 at 5 33 52 PM](https://user-images.githubusercontent.com/57469/78836044-431e6000-79bf-11ea-870c-81793d492e49.png)

![Screen Shot 2020-04-08 at 5 34 02 PM](https://user-images.githubusercontent.com/57469/78836050-46b1e700-79bf-11ea-830b-ea850440edd4.png)

![Screen Shot 2020-04-08 at 5 34 14 PM](https://user-images.githubusercontent.com/57469/78836058-49acd780-79bf-11ea-8788-41f923f8a723.png)

![Screen Shot 2020-04-08 at 5 34 25 PM](https://user-images.githubusercontent.com/57469/78836063-4d405e80-79bf-11ea-8f3c-1960878475fa.png)

**Comment by emilywaggoner** [comment]
Thank you so much @jenstrickland!!

**Comment by MickinSahni** [comment]
Accessibility
- Aria attributes - accordion menus using incorrect attributes.  #7769 

Design
- no high-level design feedback

Content
- pending feedback

QA
- Resolving #7737 in this sprint and #7741 is mitigated.

IA
- Looks like screenshots are missing left nav, but the team is chasing this down with the CMS team

**Comment by jenstrickland** [comment]
Accessibility tickets still incoming. Will @MickinSahni when all in. 

Please @ me if the left nav reappears so I can do a spot check of pages that use it.

**Comment by peggygannon** [comment]
@MickinSahni @jenniferlee-dsva Just reviewed the screenshots. I have no additional content feedback or recommendations. I had reviewed this content in an earlier state. Thanks!

**Comment by mnorthuis** [comment]
Holding on IA feedback until the left nav is fully implemented. Still having issues accessing pages through CAG.  Please @ me when left nav is corrected.

**Comment by MickinSahni** [comment]
> Accessibility tickets still incoming. Will @MickinSahni when all in.
> 
> Please @ me if the left nav reappears so I can do a spot check of pages that use it.

Would those go on the spot-check ticket? Unless those are critical findings, we're not going to address pre-launch and i imagine @andreahewitt-odd @meganhkelley are going to want to close this epic out so it doesn't linger (i know i do).

**Comment by jenstrickland** [comment]
No, iirc we chatted about this previously. I'm putting spot check findings on the staging review. Most issues are for VSP. After I log them, I'll remove vsa-public-websites and vsa from those issues. I just need to log what issues are impacting which teams so I have a record.

The only ones you'd have to close before launch would be 508-defect-0 or 1. The rest can be addressed afterwards, as documented in the severity rubric. You're looking in good shape, honestly.

**Comment by MickinSahni** [comment]
> No, iirc we chatted about this previously. I'm putting spot check findings on the staging review. Most issues are for VSP. After I log them, I'll remove vsa-public-websites and vsa from those issues. I just need to log what issues are impacting which teams so I have a record.
> 
> The only ones you'd have to close before launch would be 508-defect-0 or 1. The rest can be addressed afterwards, as documented in the severity rubric. You're looking in good shape, honestly.

Oh gotcha. Removing the PW team label is what I was prob missing. Ok, Sounds good. Thanks, @jenstrickland.
