### ISSUE TITLE
Switch GitHub Actions from targeting versions to targeting specific SHAs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#75224]
## Issue Description
Right now our GitHub action references target versions, such as `actions/upload-artifact@v3`. After talking with Tim Cosgrove from CMS, it's come to my attention that this presents a vulnerability for us. The action will pull anything with that version number and could potentially force us to take on changes that are not compatible with our workflows. A specific sha would serve the same purpose as a lockfile, ensuring we don't get forced into an upgrade unless we want it.

---
## Tasks
- [ ] For any actions, GitHub supported or third party, change all `@v#` references to a sha of that version in the action's GitHub repository (example:         uses: department-of-veterans-affairs/action-inject-ssm-secrets@d8e6de3bde4dd728c9d732baef58b3c854b8c4bb)
- [ ] Test all workflows to ensure they still function properly and we are not getting new warnings.

## Acceptance Criteria
- [ ] All actions are locked in place and workflows still function correctly.

**Comment by CBonade** [comment]
PR open for review.
