### ISSUE TITLE
[QA] Urgent Care MVP - Test Run - Post-A11y-Changes

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#7522]
Execute Manual UI test-run(s) on Staging for VSA Facility Locator team's Urgent Care MVP, after accessibility-related changes are made.

**The following issues were created following 508 Accessibility check**
- [ ] [COLOR, COGNITION]: CONSIDER changing background of map attribution [#6892]
- [ ] [SCREENREADER]: 'Directions' links SHOULD have accessible names [#6894]
- [ ] [COGNITION]: Reading order SHOULD provide context between form and results [#7239]
- [ ] [SCREENREADER]: Upon Submit, focus MUST move to the context change notification [#7240]
- [ ] [MOBILE, ZOOM]: Content SHOULD fit within the viewport when zoomed to 400%. [#6184]
- [ ] [KEYBOARD, SCREENREADER]: Navigating by keyboard between the map and the search results[#6897]
- [ ] [SCREENREADER, KEYBOARD]: All elements that can be operated by a mouse MUST able to be operable by keyboard[#6911]
- [ ] [SCREENREADER]: Focus MUST move to notification of context change when new content is added[#7243]
- [ ] [KEYBOARD]: In Firefox Choose a VA facility type dropdown MUST be keyboard accessible[#7291]
- [ ] [SCREENREADER] Add semantic HTML for search results list[#5555]
- [ ] Sitewide, design system [AXE-CORE]: Heading levels SHOULD increase by one[#7244]
- [ ] [SCREENREADER]: aria-live="polite" MUST be removed from the search results container[#7288]

**VSA-QA Test Plan** ticket: 

## How to configure this issue
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Run(s) completed on Staging.
- [ ] Defects logged.
- [ ] Test Plan Report attached & linked.

**Comment by tlei123** [comment]
@mmiddaugh , please start populating the issues-list in the main Description as you open tickets to make post-A11y-Review changes.

I'll circle back in a few days and check-in w/ you to determine list completeness before assembling my 2nd Test Run.

Thanks much!
