### ISSUE TITLE
[CAIA General Support]:<Lighthouse-Pivot!><Updates to Connected Aps FAQ page>

### ISSUE THREAD

**Issue by Dmharris625** [department-of-veterans-affairs/va.gov-team#75233]
# CAIA General Collaboration 

`WIP`

Use this ticket to request general collaboration with the Sitewide Content, Accessibility, and Information Architecture (CAIA) team.

## About your team

- **Team name**: `VA Lighthouse - Team Pivot!`
- **OCTO-DE product owner:** `Peter Tebbenhoff (OIT)`
- **Product name:** `Connected Apps`
- **Product manager:**  `Greg Feliberty`
- **Slack channel:** `[connected_apps](https://join.slack.com/share/enQtNjU2MzE5Mjc5NTcwMy03OWY4YTA1MGQxODQ4MGM2YzQ3NDNhNjcwMDllMmU2YWE2NmU0M2JlZTExOWQ0ZDg3MmFiNTIxNWUyY2RlYzlj)`
- **Dedicated content writer on your team (if you have one):** `Darcy Duda and Joe Braun`
- **Dedicated a11y specialist on your team (if you have one):** `Insert name and/or GH handle`
 
## About your request
We'd like to update the [Connected Apps FAQ](https://www.va.gov/resources/connected-apps-faqs/) page to let Veterans know they can use [Login.gov](http://login.gov/) in addition to the other identity providers listed.

### Describe your project goals

`Ensure Veterans know they can use Login.gov as an identity provider to access Apps that use VA APIs.`

### What is your team working on?

`Updating the existing Connected Apps FAQ with update information.`

### Describe how you would like to collaborate with CAIA

__

`We need a few tweaks that we've already defined implemented, since we do not own the code but the VA.gov team does.`

## Type of Collaboration 
_Check all the types of collaboration you're requesting, below:_

### Content
- [ ] Creating new content 
- [x] Updating existing content 
- [ ] Translating content 
- [ ] Something else:  `insert type of collaboration`

### Accessibility
- [ ] Wireframes or prototypes review
- [ ] PDF review
- [ ] User research support
- [ ] Something else:  `insert type of collaboration`
### IA
- [ ] User flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and left nav placement
- [ ] Redirects
- [ ] Something else: `insert type of collaboration`
### Other
- [ ] Check this box if you're not sure what kind of support you need, and we'll schedule an introductory meeting to learn more about your project.

## Collaboration timeframe

We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Your timeline 
- [ ] Check yes, if this request is tied to a Congressional mandate or timeline?

### Will you release this new product incrementally (for example, release to 25% of users to start)?
- [ ] Yes
- [x] No

**Note: **If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages). Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.

- [ ] I acknowledge that if I change the roll out of this product to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines. 

### Description
**Describe where you are in your project's timeline.** 

`These tweaks have gone through UX approval on the Lighthouse side and are ready to be implemented now.`

## Collaboration cycle 
If you’re going through the collaboration cycle with the governance team, link to the ticket:
- **Ticket Number:** `xxxxxx`
- If you’re not going through the collaboration cycle, or you’re unsure, check here, and we can follow up: 
    - [ X] Not going through collab cycle

**Note**: We ask that you partner with us **before** scheduling your midpoint review, **to ensure** we can agree on a deliverable and that there's time for your team to make changes.  

### Phases Completed
**Check any phases you’ve already completed:**
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [X ] N/A
  
## Supporting artifacts
Please provide links to any supporting artifacts we might need to begin work. This can include your product outline, user flows, mockups and prototypes, draft content, etc.
- `Copy that needs to be added/ changed is highlighted yellow in the attached doc.
[Updates to connected apps to add login - Google Docs.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/14144337/Updates.to.connected.apps.to.add.login.-.Google.Docs.pdf)
`

## Next steps
- [ ] Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.
    - A member of the CAIA team will aim to respond to your Slack message within 24 hours to acknowledge receipt - should we need any additional information regarding your request we will reach out to you to confirm.
    - The CAIA Operations group will meet to go over the info in your request and then reach out if we have any questions.
    - Depending on the request, it may make sense to schedule a kickoff meeting to better understand how we'll partner with you!
- [ ] Please review the remaining next steps in the **VFS Team Tasks** section, listed below.

## TASKS

<br>

```[tasklist]
### VFS Team Tasks
- [ ] If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
- [ ] If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.
- [ ] If you are requesting content support, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### a11y Tasks
```

```[tasklist]
### Content Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75469
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83912
```

```[tasklist]
### IA Tasks
```

```[tasklist]
### CAIA Ops
```

**Comment by laurwill** [comment]
Hi @Dmharris625 , do connected apps require people to sign in with a **verified** account? Or will unverified ID.me, Login.gov, DS Logon, or MHV accounts allow them to share VA.gov profile info with apps?

**Comment by laurwill** [comment]
And one more Q! We noticed this [Find apps you can use page](https://www.va.gov/resources/find-apps-you-can-use/) still has an info alert from back in June 2023 saying the feature isn't working. Do you know if that issue will be resolved soon?

cc @RLHecht

**Comment by Dmharris625** [comment]
Hi @laurwill - 

The answer to your first question is yes - accounts must be verified.

The answer to your second question is that the alert is still relevant though we are hoping to be able to revert to the original content soon! In the meantime, we have a ticket in our backlog to update the copy that's there to provide more clarity about what's going on. We'll file another ticket when we have that ready for implementation.

Thanks!

cc: @gfeliberty

**Comment by Dmharris625** [comment]
Hi @laurwill  - it looks like this was never implemented -- is it possible to get an update? Thanks!

**Comment by laurwill** [comment]
Hi @Dmharris625 , I'm so sorry for the delay here! We have updates ready for your team's accuracy review. Drupal won't let us preview changes to live Q&A sections, so here are screenshots of the questions we're updating. 

Rather than adding Login.gov to the list of accounts, we've suggested removing the names of the 4 accounts. This way, we won't need to update the page again whenever sign-in options change. And when people select "Sign in to VA.gov," they'll see the current account options. 

We've also made some other small language updates to follow our style guide for [sign-in and identity content](https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification). Let me know if you have any questions or concerns about these updates!

<img width="644" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/111e36a3-8eab-4ef6-824a-854cf5e9ef20">

<img width="593" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/dcafd4d6-fb1e-4d8a-a2a8-45c178c55abb">

<img width="743" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/9f853969-be42-40b3-b081-2cb8537bc088">

**Comment by Dmharris625** [comment]
Thanks, @laurwill!

I'm ok with just removing the IDPs - agree that's more scalable.

I do have a couple of other questions/ concerns:

1.  For the question "How do I connect a third party app to my VA.gov profile?" can we use the copy: "When the app (or website) prompts you to verify your identity...." instead of "prompts you to connect to your VA.gov profile" We're making updates to our SAML proxy page and the copy will now have the headline "Verify your identity" not "login to va.gov"
2. For the question "What if I can't sign in..."' It's now reading strange to me that we're referring to frequently asked questions but it's not clear where those can be found // that they're available on the page linked in the next sentence. Can we keep the original copy and linking? 

Thanks!

**Comment by laurwill** [comment]
Hi @Dmharris625 , 
- For 1., can you share more about the screen you're updating and what that screen asks people to do? On VA.gov, we only use "verify your identity" to refer to the identity verification process through Login.gov or ID.me to get an LOA3 account. I know that "verify" is used to refer to other processes on other sites, like multi-factor authentication, but we're very careful about how we use it on VA.gov. 
- For 2., we have to change the link style because we no longer embed links midsentence. This is an accessibility improvement to our link style. How about we adjust to this, so that the link itself answers the question? The sentence before wasn't adding much.
<img width="663" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/3b64ad21-807c-447e-955a-d57f9eb96510">

**Comment by laurwill** [comment]
Hi @Dmharris625 ,
For 2., good point! I'll remove "or connected apps" from the question header.

For 1., would it be possible to see a complete sign-in flow for connecting to an app? I'm wondering why "verify your identity" would make more sense than "sign in to VA.gov" or "connect to your VA.gov profile" to a representative who's signing in on behalf of a Veteran. I think I may just need more context.

Apologies for the nitpicking here — my concern is that the H1 change on that screen to "Verify your identity" may conflict with how we use that term elsewhere on VA.gov. It looks like what they're actually doing on that screen is **signing in**, not going through the identity verification process. Is that correct?

Looping in @DanielleThierryUSDSVA here for the connection to sign-in and identity verification messaging.

**Comment by laurwill** [comment]
Whoops I read too quickly — for 2, I think the header should actually be "What if I can't sign in to VA.gov to connect or disconnect an app?" Let me know if you have any concerns with that wording. 

And another Q — is the reason you're suggesting "verify" here that they need to sign in with a verified account (LOA3) to manage connected apps? If so, we have different language we use to explain that requirement. (We'd say something more like "Sign in with a verified account," and then explain how to create a verified account if they don't already have one.)

**Comment by Dmharris625** [comment]
Hi @laurwill.

Many of our Vet Representative users are Veterans themselves so the copy around logging in to their VA.gov causes significant concern because it suggests to them they'll be accessing their own data vs. the data of the Veteran they're supporting. Veterans and VSOs will be seeing this page when they are connecting their application to their VA data (aka granting the app access) - not when they're logging into VA.gov to see their connected apps. They have to use one of the IDPs simply to verify who they are -- it tells us we can give the app access to the data they've given us permission to share.

We ran usability tests with both VSOs and Veterans with the copy I shared and it worked well - so we'll be moving forward with that for our SAML proxy page. 

Re: What if I can't sign in to VA.gov to connect or disconnect an app? I think this is conflating two different things. Disconnecting an app, I believe, will happen by logging into VA.gov through the website. Connecting an app happens through authenticating through the SAML proxy while in the app itself. I think the link only addresses the former. The question "what should I do if I no longer trust a connected app?" gives instruction for disconnecting.

Feel free to schedule time with me if you'd like to discuss further.

**Comment by laurwill** [comment]
Thanks Dana — I think this is why seeing the entire flow would be helpful here. Do you have a Figma file or another resource that shows the entire process for both connecting an app and disconnecting an app? It's hard for us to write accurate content around sign-in flows without seeing the whole experience.

**Comment by Dmharris625** [comment]
[Here's](https://www.figma.com/proto/MaoG0ye3SSnDxiErqP2taf/LDX-35038%3A-SAML-Proxy-Testing-Prototypes-(Mobile)?node-id=5957-528&t=IDYnlgvOuDdAGApb-1&scaling=min-zoom&page-id=5957%3A2) the flow in Figma for a Veteran-facing app.

Disconnecting an app has to happen through Va.gov, not the application, so the flow is separate:
- [Sign in to VA.gov](https://www.va.gov/?next=/profile/).
- Select your name, then Profile.
- Within your profile, select Connected apps.
- Find the site or app, and select Disconnect.

**Comment by Dmharris625** [comment]
Hi @laurwill just following up here - thanks!

**Comment by laurwill** [comment]
HI @Dmharris625 sorry for the delay here! Thanks so much for explaining the different flows for connecting and disconnecting, I get it now :)

I spoke with our OCTO content lead about the use of "verify" in that screen you linked — someone may reach out to talk more with you about that and how it relates to our other content about identity verification. 

I also left you a couple comments in Figma with these questions:
- If someone signs in using an LOA1 (unverified) account on [this screen](https://www.figma.com/proto/MaoG0ye3SSnDxiErqP2taf/LDX-35038%3A-SAML-Proxy-Testing-Prototypes-(Mobile)?node-id=5957-528&t=IDYnlgvOuDdAGApb-1&scaling=min-zoom&page-id=5957%3A2), do we prompt them to verify their identity through their account provider (Login.gov or ID.me)?
- There's no longer any way to verify a My HealtheVet account online. People have to start over by creating a Login.gov or ID.me account and verifying that account, instead. What happens if they sign in here with an LOA1 My HealtheVet account?

I'd also love to see the results of your study with accredited reps, if you have those handy! Our content on VA.gov always addresses our Veteran, service member, or family member audiences, but it's helpful to understand how non-Veteran audiences experience the site and tools as well. 

In the meantime, we can move ahead with accuracy changes to the static page, but we can't use the word "verify" on that page to describe the process of signing in. On VA.gov, we can only use "verify" to describe the identity verification process that turns an LOA1 account into an LOA3. 

Here's an update for the "What if I can't sign in" question that I think works for both flows (connect and disconnect). Let me know what you think!
<img width="525" alt="image" src="https://github.com/user-attachments/assets/be473aab-eb9b-46a0-a3e1-3c91352d2b82">

**Comment by Dmharris625** [comment]
Hi @laurwill 

The context for our SAML proxy is quite different because we have accredited reps who use it - many of whom may not actually have a VA.gov profile.

So to answer your questions:
` If someone signs in using an LOA1 (unverified) account on [this screen](https://www.figma.com/proto/MaoG0ye3SSnDxiErqP2taf/LDX-35038%3A-SAML-Proxy-Testing-Prototypes-(Mobile)?node-id=5957-528&t=IDYnlgvOuDdAGApb-1&scaling=min-zoom&page-id=5957%3A2), do we prompt them to verify their identity through their account provider (Login.gov or ID.me)?`
 
Yes, a non-identity verified account will automatically be prompted on the ID.me or [Login.gov](http://login.gov/) side to identity verify.

`There's no longer any way to verify a My HealtheVet account online. People have to start over by creating a Login.gov or ID.me account and verifying that account, instead. What happens if they sign in here with an LOA1 My HealtheVet account?`

To the above point, asking them to sign into their VA.gov account is misleading. Especially for those VSOs. Logging in in this way is not connecting data from their VA.gov profiles, it is merely telling us that they're really who they say they are so that we can provide their data (not data that's in their va.gov profile). We require LOA3 (identity verified) accounts as part of our sign-in process.

All of our comms were generated in conjunction with our technical team for accuracy so there are no concerns. It's been fully reviewed and approved by our product owners.

The issue with the final question is still that we're not asking the to sign in so the question itself will be confusing. For reference, this is like if you're signing into Zoom and it lets you log in using your Gmail account rather than with an email and password. You're not logging into Gmail at that time, you're just using it to prove to Zoom who you are. Perhaps we can say something like: "What if I can't connect to the app?".

[Here's our study](https://github.com/department-of-veterans-affairs/lighthouse-ux/blob/master/Developer%20Platform%20Research/2024-04-Usability-Test-SAML-Proxy-Redesign-Research/Research%20Report.md) with VSOs on the SAML proxy.

Please schedule time with me to discuss if you have further questions.

@dbrown-va

**Comment by laurwill** [comment]
Hi @Dmharris625 , thanks so much for making time to chat this morning. 

We agreed on calling this last question "What if I can't connect to an app," but I realized that's too similar to the first question in this section "What if I tried to connect to an app and got an error message." Would "What if I can't sign in to connect an app" work? (That's consistent with the use of "sign in" in the "How do I connect" question in the first section of the page.)

<img width="405" alt="image" src="https://github.com/user-attachments/assets/aeb53063-ac67-44ac-bd1a-2ebcc195304e">

The other option would be combining those 2 very similar questions to address both sign-in problems and error messages in the apps when trying to connect.

Happy to hop on a quick huddle again if that's easier!

**Comment by Dmharris625** [comment]
It doesn't solve the problem of not saying "sign in" but you're right, if we're going to change it there we should change it everywhere, so we can update to what you have above and consider further edits across the page in the future.

**Comment by laurwill** [comment]
Hi @Dmharris625 , is the change on that initial screen from "Sign in to your VA.gov profile" to "Verify your identity" already live? 

In that "How to connect" Q&A, I can change "your VA.gov profile" to "your VA data," but we can't change "sign in" to "verify your identity." The second screen in the new Figma flow you linked above does say "Sign in to ID.me," so this still seems accurate to me. 
<img width="383" alt="image" src="https://github.com/user-attachments/assets/6b59c326-4d83-4b09-8262-68b4ff4b56e0">

Here's the updated Q&A. I combined steps 1 and 2 so that we can at least avoid repeating the phrase "the app will prompt you to sign in." 
![image](https://github.com/user-attachments/assets/25040b7e-435e-4ba4-90bb-9646453c8bc4)

Let me know if this update works, and we can go ahead and publish!

**Comment by laurwill** [comment]
Just noting that I'm OOO this afternoon and tomorrow, but I'll pick this up on Monday morning when you've had a chance to review the last update. Thanks!

**Comment by Dmharris625** [comment]
That works! Thanks so much!

So to recap the questions we're updating:
1.  How do I connect a third-party app...
- change "VA.gov profile" to "VA data"
- remove reference to  the IDPs and combine as you have detailed
2. Can I stop sharing my VA information...
- remove reference to the IDPs
3. What if I can't sign in...?
- change to "What if I can't sign in to connect an app"?
- Change copy to "Get answers to frequently asked questions about signing in" (hyperlinked)

**Comment by laurwill** [comment]
Yep that covers the substantive changes! Just noting 3 other small style updates to links for awareness:

In "What should I do if I no longer trust a connected app?" changed email link from:
<img width="210" alt="image" src="https://github.com/user-attachments/assets/2a428d84-5963-400a-9249-347f6c071fee">
To:
<img width="342" alt="image" src="https://github.com/user-attachments/assets/9d031d43-d32f-47f2-a643-5bdc8c6fbb6f">

In "Where do I find apps?" changed link style from:
<img width="709" alt="image" src="https://github.com/user-attachments/assets/005ce0c5-d541-4db6-a26e-68100df2d393">
To:
<img width="737" alt="image" src="https://github.com/user-attachments/assets/51d20571-8e43-4f54-99eb-35d56437de68">

In "How are connected apps different" changed link style from:
<img width="673" alt="image" src="https://github.com/user-attachments/assets/a083cce6-f51f-4316-8477-55d440790a17">
To: 
<img width="660" alt="image" src="https://github.com/user-attachments/assets/9ec5364f-e99b-4528-be6e-a8b7062ef79f">

I think we've agreed on all the substantive changes now, so we'll go ahead and publish the updates. And of course let me know if you have any other questions or concerns. I'll confirm when the update is live. Thanks again for your patience and collaboration!

**Comment by Dmharris625** [comment]
Sounds good just want to make sure the rest of the answer to the "How are connected apps different..." will be included too

> Connected apps are designed by organizations outside of VA. These apps can receive only certain personal information, like your VA health or service records, that you tell us to share with them.

Thanks!

**Comment by laurwill** [comment]
Yes! Just cut off the screenshot too soon, that will still be there :)

**Comment by Dmharris625** [comment]
Ok, great, thanks!

**Comment by laurwill** [comment]
Hi @Dmharris625 , these updates are now live. Thank you again for your patience and collaboration on these — I'll close this out, and I'll follow up about the find apps page updates later today.

**Comment by Dmharris625** [comment]
Thanks so much!
