### ISSUE TITLE
EPIC - Datadog Browser Integration

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75231]
The problem we are trying to solve with the Datadog browser integration is that we are getting inconsistent logs between Datadog and Google Analytics. The thought is that by using Datadog instead of Google Analytics that we will be able to get more accurate logging information. The benefits will be twofold:

1. We get more accurate logs through the authentication flow (because backend doesn't use Google Analytics) 
2. We can deliver better information to Tom and others in leadership when they ask for information of authentication and the users. Example: How many verified users did we have in 2023, etc

```[tasklist]
### User Stories
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75242
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75245
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75250
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75249
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75255
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75256
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75258
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75689
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75697
```

**Comment by asg5704** [comment]
@LisaLindsey
