### ISSUE TITLE
Consider how Rep Status Widget information translates to Profile

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75246]
## Background
We have been working on our Representative Status Widget MVP on the ARM team, but have been hearing through research that Veterans also expect to see this information in their Profile, as well as in MyVA.  

After discussions with the Profile and MyVA PO, their guidance is to move forward with including representative information in the Profile.  Veterans were interested in the area of MyVA that had the claims cards, which seems to be stemming from the Claims Status team; will explore what that could look like at a future time (out of scope for now).

The structure of Profile appears to be one main page with high level cards, and each card points to a detail page.

## Tasks
- [x] Review account team's Figma space to understand existing design patterns
- [x] Create an area in Figma for Profile designs
- [x] Ideation of how the rep information could appear in the Profile -- both a card and a detail page
- [x] Review ideation with Profile team
- [ ] Incorporate any feedback from Profile into the designs
- [ ] Midpoint Review?

## Acceptance Criteria
- [ ] There is a design for including representative status information in the Profile, based on input from all interested parties

**Comment by oddball-lindsay** [comment]
Closing for now, can explore in more depth (with Profile feedback) when we're getting closer to that study.
