### ISSUE TITLE
Route Sentry/Datadog errors to Slack

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75251]
## Background
We have Sentry setup to flag errors associated with our product URLs.  As we approach the launch of Find 2.0, it'd be helpful to have any alerts route to our Slack channel `benefits-representation-management` so that we can be aware of any issues post-launch, triage accordingly, and take swift action to remediate any high priority issues.  

## Tasks
- [x] Confirm where Sentry alerts are being routed currently - email alerts are setup for Colin, Holden and Lindsay
- [ ] Implement alert routing to Slack channel `benefits-representation-management-notifications`

## Acceptance Criteria
- [ ] Whenever there is an error/issue associated with our Find 2.0 URLs, an alert will be sent to the Slack channel `benefits-representation-management-notifications`

**Comment by oddball-lindsay** [comment]
When we decide the logic, would be nice to see a test so we as a team understand what Sentry alerts look like prior to launch

**Comment by oddball-lindsay** [comment]
Set some rules based on other projects (if x error occurs at y frequency in z intervals, send notification to "vfs team")

Sent a request to include @oddball-lindsay's email for notification.  There is also a "vfs-arm" slack channel, will look a bit more into this.

**Comment by oddball-lindsay** [comment]
Expecting to see email alerts for just Colin and Holden, but additional work to get notifications to the rest of the team.

**Comment by oddball-lindsay** [comment]
Alerts to Slack seem like they require a Slack-Sentry integration.  We do have the option for email notifications, perhaps we can utilize Slack workflows?  An email notification that Slack can turn into a message -- will research.

**Comment by holdenhinkle** [comment]
Thank you Lindsay! Great info💪

**Comment by oddball-lindsay** [comment]
Created a couple of monitors in Datadog, leaving in Review while we experiment with this new setup over the next few days.
