### ISSUE TITLE
ARM team QA of Find 2.0 in Staging

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75252]
## Background
This is a placeholder for the ARM team's QA of Find 2.0 in Staging, before heading into Staging Review.
We can also request review from our CAIA a11y and content partners.

## Tasks
- [x] Ask the team to QA Find 2.0 in Staging
- [x] Collect any findings from team QA in [this Google doc](https://docs.google.com/document/d/17sbON_0yuFWUV6g8SjlIfri5uEjSSpMOmwUzVQEJ-RM/edit)
- [x] Create tickets to address findings

## Acceptance Criteria
- [x] The team has reviewed Find 2.0 in Staging and tickets have been created to address any findings

**Comment by oddball-lindsay** [comment]
i've ticketed everything that seems straightforward.  still remaining, which i will get to by EOD tomorrow:

- some a11y tickets from jamie that i have open qs for
- the name and location search funkiness that michael and janelle reported; i want to play around with this a bit more before ticketing
