### ISSUE TITLE
Discovery: How to selectively import stylesheet documents into stencil

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#75275]
## Description
We need to have a way to import .scss style sheets, specifically  into Stencil based web components. We also need to be able to switch which styles are either imported or applied depending on the custom component having the `uswds` property or not.  

## Details
Some  previous reserarch indicates that  the `styleUrls` field and `modes`  may lead to a solution.
[Related PR](https://github.com/department-of-veterans-affairs/component-library/pull/1038/)

## Tasks
- [ ] Determine how to import  a .scss stylesheet documents into a Stencil @Component decorator
- [ ] Determine how to import/switch-between multiple  .scss stylesheets
- [ ] Determine how to switch the import, or use alternate styles,  depending whether the web component  has the uswds property or not

## Acceptance Criteria
- [ ]  Can successfully import a .scss into the web component
- [ ]  Can switch between styles, so as to successfully handle uswds and v1 components
