### ISSUE TITLE
GIBCT - Upgrade AWS Database servers

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75284]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a backend developer
I would like to upgrade the AWS Database server environments
So that the server environments remain up to the current versions, providing stability and security to the systems and to the information therein, 
Therefore providing a stable and secure environment to the other systems that utilize the APIs. 

## Hypothesis or Bet
**If** we upgrade the AWS Database server environments and keep them at the current versions **then** we expect the systems to stay stable and protect the information that they convey.

## OCTO Objectives:
**Objective:**
This aligns with O2: Our platforms are the best way to deliver products at VA
**OKR**
This aligns with OKR1: Our platforms hit the "elite" level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.

## Definition of done

- [ ] A clear rollback plan is in place in case the upgrade encounters issues
- [ ] Upgrade plan is reviewed and approved by the database team and key stakeholders
- [ ] Clear announcements and communication is in place
- [ ] All critical applications and services connected to the database are tested and confirmed to be operational post-upgrade.
- [ ] The database is successfully upgraded in the production environment during the scheduled maintenance window.
- [ ] Immediate post-upgrade checks (e.g., database integrity, connectivity) are performed and pass without issue.
- [ ] All changes, including configurations and tuning, are documented.
- [ ] App owners are informed about the completion of the upgrade and any actions they need to take.
- [ ] Any minor issues are logged, and a plan for their resolution is in place.

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] devops
