### ISSUE TITLE
Bump crack gem to 0.4.6

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#75286]
### Description
Bump to 0.4.6. New version is officially Ruby 3 compatible

https://rubygems.org/gems/crack

### Tasks
- [x] Bump `crack` to 0.4.6
- [x] Merge to master

### Acceptance Criteria
- [x] `crack` is 0.4.6 in Gemfile.lock
