### ISSUE TITLE
Research: New DOMO Dashboard for Support Ticket Trends

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#75294]
## Description 

We want to source more granular metrics to show the following trends: 

- Response time trend (MoMYoY)
- Average days to close trends (MoM/YoY)
- Support ticket trends (YoY)

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Schedule a discussion with Johnny and Basil to see what is possible (Platform Analytics)
- [ ] Determine next steps with Platform Analytics 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
<img width="1114" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0102dfbc67f1ece358d0911d810187260b49395/Screenshot%202024-11-19%20at%203.15.18%20PM.png" alt="Screenshot 2024-11-19 at 3.15.18 PM.png" />

Filtering available to pull these metrics as needed. No work needed, closing.
