### ISSUE TITLE
Design scheduling experience when facility transitions to OH

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#75293]
## Task Description

User story: As a user at a VistA facility that is transitioning to Oracle Health, I need to know how to contact a the facility when I can’t schedule online.

Design the user flow and interactions for this user when:
- Scheduling a VA appointment
- Scheduling a VA Vaccine appointment
- Requesting a VA appointment

This does not apply to requesting Community care (as this is through HSRM)

## Notes and References

When a facility transitions from VistA to OH, they don't accept direct-schedule appointments or requests from VAOS for a few weeks before the switchover. This gives staff time to clear their queue and make sure no online requests are missed during the switchover.

For the Veteran who wants to schedule at this facility, this means they have to call to make an appointment.

## Acceptance Criteria
- [ ] User flow is mapped out
- [ ] Design spec for m/t/d screens is done
- [ ] A11y annotations are done
- [ ] Designs have been tested with accessibility testing checklist
- [ ] Devs have reviewed final spec
- [ ] Product has reviewed final spec
- [ ] Product has updated the copy docs
- [ ] Product has updated the feature docs

## Deliverables
-

**Comment by melissa-lefevre** [comment]
Here is the[ figma file](https://www.figma.com/file/YXN3Ydo1dm08UWfjofEGpG/Facility-transition-to-OH?type=design&node-id=0%3A1&mode=design&t=o8sX061Jw9BdBr23-1) I am working in
