### ISSUE TITLE
Automate Tier 2 Reassignment Mentions in Slack Bot

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#75298]
## Description 
At the moment, we manually reassign tickets to Frontend, Backend and DevOps. Once assigned, the ticket adds the applicable label (frontend, backend, devops) but in the Support Bot, it shows only Tier 1 names. We would like to make it more clear who the ticket is assigned to (both in Slack and GitHub) for easy tracking. 

The way that the names are pulled into the Slack Bot currently is by using the Slack user ID, which is stored in this spreadsheet: [Platform Support Teams](https://docs.google.com/spreadsheets/d/1k9P921Hdo654631HmX9WovGaYRIFAhO3QRg3EN3F9gI/edit#gid=0). 

To be able to automate the process, we will have to Automate On Support assignments in the [Platform Support Teams spreadsheet](https://docs.google.com/spreadsheets/d/1k9P921Hdo654631HmX9WovGaYRIFAhO3QRg3EN3F9gI/edit#gid=0) using Slack IDs (PagerDuty Data). Curt Bonade and I had a discussion about this, so we'll want to tap him for the work or to download the work to someone else.

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Sync up with Joe/Curt to determine when the work could be accomplished and to scope it out
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Not possible with GH API. Closing.
