### ISSUE TITLE
Automate Onboarding for Tier 2 Engineers (Onboarding Slack Materials and Calendar Invites)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#75303]
## Description 
We are looking to automate our onboarding process that we send right before a sprint here: 

We want to identify if we can use Pager Duty Tagging capabilities to send a message automatically that tags those on the the rotation in PagerDuty On Call Schedules.

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Identify what capabilities are available to accomplish this
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)

- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
