### ISSUE TITLE
Research: Auto Add Platform-Support-Support-Ticket Label to All Active Support Issues

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#75300]
## Description 
At the moment we have to manually add either the Platform-Support-Ticket to all support tickets in the Active Support Issues column. To avoid human error, we would like to automate this process. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify what the lift would be to accomplish this work and what the steps would be
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@IsaiahMW1 It turns out the sprint work we decided on for Upcoming Sprint wasn't relevant anymore. This will replace it and you can start on this next sprint!

**Comment by alyssagallion** [comment]
Resolved this on a call regarding configuration of GH projects. Closing!
