### ISSUE TITLE
[CST] Add `Source-App-Name` header to document uploads

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#75306]
### Background
We are using the metric `vets_api.statsd.api_rack_request` in DataDog to monitor traffic from the CST. In order to differentiate our traffic from the traffic of other applications, we are relying on a field called `source_app`. This field is populated from a header passed by vets-website called `Source-App-Name`. API calls using the `apiRequest` method from platform automatically send this header, but we are not using `apiRequest` for document uploads from CST so that field is coming back as 'not provided` in DataDog currently. We need to update the document upload code to supply this header when making the request to vets-api.

### Engineering notes
* There are two separate functions for document uploads currently (one for EVSS, one for Lighthouse). Make sure to update both functions
* The names of these functions are: `submitFiles` and `submitFilesLighthouse`
* The value for the `Source-App-Name` header is supposed to match the `entryName` from `manifest.json`. It's better to import `manifest.json` and get the `entryName` that way then it is to hardcode the value to `claims-status` in case we ever update the CST to have a different `entryName`value

### Tasks
- [x] Update `submitFiles` function to pass the `Source-App-Name` header
- [x] Update `submitFilesLighthouse` function to pass the `Source-App-Name` header

### Acceptance Criteria
- [x] All Document upload functions are passing the `Source-App-Name` header to vets-api with the value being derived from the `entryName` in `manifest.json`

**Comment by jerekshoe** [comment]
#### Update
Draft PR is out, will try and get this merged today. This is extremely low risk so there shouldn't be any issues merging this to production ASAP
