### ISSUE TITLE
Create a Tier 1 Schedule and Auto Assign Tickets Based on Schedule

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#75301]
## Description 

We currently manually add ourselves to GitHub tickets and do not assign Slack tickets formally in Slack (although everyone knows what day they are scheduled and what tickets are theirs). To avoid human error for adding names to things and to make communication on tickets more clear and transparent, we are aiming to automate ticket assignments based on a Tier 1 schedule. 

This would make our daily assignment obsolete or we would need to repurpose it.
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Determine what work needs to be done with Curt Bonade
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
