### ISSUE TITLE
Prototype for Debt Portal Study

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#75319]
## Description

Create Figma Prototype for upcoming Debt Portal study

Still needed: 
- Average number of copays Veterans have within 6 months
- Average number of overpayment debts Veterans have within 6 months

Scenario: Figma Prototype for upcoming research showing current summary page flow and updated summary page flow

Current
Email > Debt portal landing page > Debt and bills landing summary > Copay landing summary page

Consolidated (updated)
Email > Debt portal landing page > Debt and bills landing with cards for all copays and debt

## Tasks
- [x] Add mockups as needed
- [x] Create Figma prototype for current flow
- [x] Create Figma prototype for consolidated flow (all copays and debts displayed on one page)

## Acceptance criteria

- [x] Figma prototype for current flow
- [x] Figma prototype for consolidated flow (all copays and debts displayed on one page)

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
Moved to Validate @Tom-Davis @HeatherRienks

**Comment by Tom-Davis** [comment]
Closing as all work is complete.
