### ISSUE TITLE
Q1 2024 Improved Monitoring: Documentation on all Monitors and Alerts

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75329]
## Issue Description
Documentation on all Monitors and Alerts [on this confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends)

---
## Tasks
- [x] Documentation of monitors
- [x] Documentation of alerts

## Acceptance Criteria
- [x] All alerts and monitors that have been recently created are documented [in confluence](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends)
- [x] Front-facing dashboard that can be shared with VA POs
- [x] Customizable views

**Comment by rmtolmach** [comment]
Work has started on this page: https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends and will be updated as more alerts are created.

**Comment by rmtolmach** [comment]
Closing this ticket. The doc is created and the tickets for more alerting/monitoring have acceptance criteria to update the doc.
