### ISSUE TITLE
[FE/BE] What is causing the mailing and home address errors we are still seeing?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7532]
## Background

We launched the address validation feature on March 18 to 25% of users, to 50% on 3/25, and to 100% on 3/30. As of the week of 3/26 - 4/1, we saw a drop in the save failure rate for mailing addresses drop from ~20% to ~10%. This is significant and great, but we are still wondering why we are seeing mailing address error rates at about 10%.

As for saving failure rates for home addresses, that's stayed steady around 5% from pre to post-launch. While this is lower than the mailing address failure rate, we still don't know what is causing these errors. 

For both, we should investigate what is causing those errors. How else might we go about doing this? What can we answer with the tools we have now? What else might we do?

## Tasks

- [ ] Determine what we can do now to investigate the mailing address/home address error rate
- [ ] Look into this issue
- [ ] See what insights we can get from veterans who reported issues updating their addresses #6012
- [ ] Figure out what we know and what other investigation, if any, that we might need to do

## Acceptance criteria

- [ ] We have looked into these error rates to the best of our ability and determined next steps

**Comment by Samara-Strauss** [comment]
We can leave this open for now, but we are specifically looking into an issue with initializing VA profile here Ihttps://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/101

**Comment by Samara-Strauss** [comment]
Gonna close this. For at least some veterans, we have determined that there is an issue with the profile/contact info section not loading properly if they have multiple identities detected. This may be resolved as some of the SSOe work that won't allow people to log in if multiple identities are detected.

Otherwise, the error rate has dropped so low that I don't think we need additional investigation. It's 4% for mailing addresses, and 1% for home addresses. If this spikes, we can investigate but I don't think we need to put additional resources on this right now.

Closing.
