### ISSUE TITLE
Q1 2024 Improved Monitoring: CPU Monitors

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75333]
## Issue Description
CPU Monitors

---
## Tasks
- [x] Set up alerts and monitoring on CPU for bulk heads
- [x] Documentation updates on [on this confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends)

## Acceptance Criteria
- [x] [This confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends) is updated.

**Comment by jennb33** [comment]
@LindseySaari and @RachalCassity moving this to Current Sprint

**Comment by rmtolmach** [comment]
Keep in mind the new standards for using tags in datadog monitors. See documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards

**Comment by RachalCassity** [comment]
[PROD - Vets API CONTAINER - CPU USAGE](https://vagov.ddog-gov.com/monitors/203459?view=spans)

**Comment by RachalCassity** [comment]
[STAGING - Vets API CONTAINER - CPU USAGE](https://vagov.ddog-gov.com/monitors/203460?view=spans)

**Comment by RachalCassity** [comment]
[STAGING - Vets API - BULK HEAD - CPU USAGE](https://vagov.ddog-gov.com/monitors/203467?view=spans)

**Comment by RachalCassity** [comment]
[STAGING - Vets API - BULK HEAD - CPU USAGE](https://vagov.ddog-gov.com/monitors/203467?view=spans)

**Comment by RachalCassity** [comment]
[PROD - VETS API - BULK HEAD - CPU USAGE](https://vagov.ddog-gov.com/monitors/203459?view=spans)
