### ISSUE TITLE
Q1 2024 Improved Monitoring: External Service Monitors

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75331]
## Issue Description
External Service Monitors
---
## Tasks
- [x] Identity which external services Staging and Prod
- [x] Identity thresholds
- [x] Update docs [on this confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends)

## Acceptance Criteria
- [x] All External Services have an alert
- [x] Monitors are documented [on this confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends)

**Comment by rmtolmach** [comment]
Keep in mind the new standards for using tags in datadog monitors. See documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards

**Comment by RachalCassity** [comment]
Going through each External Service today (02/29/24)

**Comment by RachalCassity** [comment]
All monitors have been created for Staging and Prod.

**Comment by RachalCassity** [comment]
Need to export to Terraform
