### ISSUE TITLE
Q1 2024 Improved Monitoring: Bulk Head Monitors

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75330]
## Issue Description
Check Datadog

---
## Tasks
- [x] Check DataDog: current dashboards [here](https://vagov.ddog-gov.com/dashboard/sx7-di8-bpr/bulkhead-errors?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1708627061263&to_ts=1708630661263&live=true) and here for [analysis](https://vagov.ddog-gov.com/dashboard/jwa-xmg-aru/bulkhead-analysis?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1708627060846&to_ts=1708630660846&live=true)
- [x] Improve the scaling
- [x] External metric resource
- [x] Find dashboard of overhead of existing boards, see if they can be revamped
- [x] Validation of ticket
- [x] Update documentation [on this confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends) or link to the Support Responsibilities [dashboard](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities) or [here](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2466381827/Bulkhead+Pattern+for+Vets+API)

## Acceptance Criteria
- [x] Monitors are documented [on this confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends)
- [x] Work has been validated
- [x] Documentation is complete

**Comment by rmtolmach** [comment]
Keep in mind the new standards for using tags in datadog monitors. See documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards

**Comment by jennb33** [comment]
This might be done; @RachalCassity and @rmtolmach to review current work and validate what still needs to be completed.

**Comment by RachalCassity** [comment]
Going through Datadog metrics

**Comment by rmtolmach** [comment]
There might be a little bit of an overlap with the work I did in https://github.com/department-of-veterans-affairs/va.gov-team/issues/76695. I created [this dashboard](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1709583270702&to_ts=1709669670702&live=true) and two monitors. The monitors are linked on the dashboard and in the ticket if you need them for reference.
