### ISSUE TITLE
Adding copays/debts to Staging/Dev Users

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#75342]
## Description

In order to use our staging environment to illustrate how the Debt Portal functions in production for a Veteran we need to ensure that there is a dedicated user who has actual copays and/or debt attached to their account and has the most up to date features enabled.

Given: That the team needs to test or show other stakeholders our staging environment (and local environment if possible- talk to Front End!!)
When: And we need to show a user that has copays and/or debt
Then: We need to be able to have a specific user to use/test.

## Tasks
- [ ] Identify which staging user to add mock data to
- [ ] Identify what data needs updated
- [ ] Determine what API is used in staging or how the data is adjusted
- [ ] Determine if API above has the required data

## Acceptance criteria

- [ ] User has active copay applied to account
- [ ] ADD anything else here

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
See #65529 for reference.

**Comment by HeatherRienks** [comment]
Per 2/27/24 Retro, this is important to resolve. Let's aim to complete in S121.

cc: @denisecoveyduc @Tom-Davis

**Comment by kjsuarez** [comment]
1. On the staging env we source copays and debts from VBS's and DMCs staging endpoints respectively.
2. User 81 has both debts and copays

**Comment by kjsuarez** [comment]
[Relevant slack conversation](https://dsva.slack.com/archives/CSFV4QTKN/p1709851247285819)

**Comment by kjsuarez** [comment]
Update: User 81 now has an edipi on local, but full FSR path still fails with below error when trying to pull user's pciu_email. Further work required.
`Betamocks default response requested but none exist. Please create one at: [../vets-api-mockdata/evss/pciu/email/default.yml]. (IOError)`

**Comment by HeatherRienks** [comment]
Per Sprint Planning, @kjsuarez will create an additional ticket to follow up with needed work for this effort.

**Comment by kjsuarez** [comment]
Additional mockdata additions made [here](https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/462)
With the addition of edipi on user 81 and the above mockdata additions I was able to run a full FSR on user 81 locally.

**Comment by kjsuarez** [comment]
VBS confirmed that it would be trivial for them to add copay data for staging users. We just have to provide an edipi and any specific copay data we want and they'll handle the rest.
