### ISSUE TITLE
GA4: Form API Events Tracking

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#75346]
### Description
Online forms seem to have a standard set of API events, versioned by form but not really custom events. Instead of waiting for each form product team to transitions these events, it's much more efficient to do them all at the same time.

**Artifact(s):**

- Tracker document coming soon

### Tasks

- [ ]  Compile current list of all form API events (tracker document)
- [ ]  Map the dataLayer parameters for the events to GA4 fields/schema
- [ ]  Add events to GTM
- [ ]  Test/Preview GTM implementation on staging

Combined with **[Analytics Implementation or QA Support for Memorials Self-Service - Pre-Need#74273](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/74273)**

- [ ] New parameters added to APIs to account for this request

### Acceptance Criteria

 - [ ]  Events have been added to GTM and published for lower environments (dev + staging)
 - [ ]  Events have been added to GTM and published for production environment
 - [ ]  Events have been confirmed in GA4
 - [ ]  Re: 74273 - Comment has been made to MichelleDieudonne confirming the tracking, and closure of ticket.
