### ISSUE TITLE
Bump rgeo gem to 3.0.1

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#75341]
### Description
Bump `rgeo` to 3.0.1.

https://rubygems.org/gems/rgeo

### Tasks
- [ ] Bump `rgeo` to 3.0.1
- [ ] Merge to master

### Acceptance Criteria
- [ ] `rgeo` is 3.0.1 in Gemfile.lock
