### ISSUE TITLE
Research | Post-Launch Evaluation of Dependent Notification

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#75357]
## Issue Description
_As a researcher, I need to understand the effectiveness of the dependent verification notification emails._

---
## Tasks
- [ ] Identify what data we want to examine at post-launch
- [ ] Identify what data we expect to receive back (VA Notify, GA, custom reports, etc.)
- [ ] Identify the data we will cross-reference (open rate vs # of dependents)

## Acceptance Criteria
- [ ] Post-launch data evaluation plan is outlined in the [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/dependents/dependency_verification/annual-email/Release-Plan-Verification%20Email.md)
---
