### ISSUE TITLE
Q2 2024 Improved Monitoring: Error rates

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75350]
## Issue Description
Monitor error rates (4xx, 5xx, etc)

---
## Tasks
- [x] Create 4xx monitors
- [x] Create 5xx monitors
- [x] Create terraform files

**Comment by RachalCassity** [comment]
The following monitors were created:
[VETS API - STAGING - {{controller.name}} - High Errors Occurring](https://vagov.ddog-gov.com/monitors/203671?view=spans)
[VETS API - PROD - {{controller.name}} - High 500 Errors](https://vagov.ddog-gov.com/monitors/203472?view=spans)
