### ISSUE TITLE
[FE] Remove "Check out your new personalized homepage" footer banner

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7535]
## Background

We put up a "Check out your new personalized homepage" footer banner on the homepage way back when (probably in the transition between Vets.gov --> VA.gov) to lead people to My VA. This shouldn't have stayed up for 1.5 years — we can take it down.

**Addendum**: As of 4/21, it looks like the footer banner on the homepage is being used to inform people of a DS Logon outage. **Please do not remove the DS Logon alert**. We just need to make sure the "Check your personalized homepage" message **will not** come back after the DS Logon alert is removed. If the "Check out your new personalized homepage" message has been permanently removed by the new DS Logon alert, then there is nothing else to do in this ticket, and we can close it.

<img width="1279" alt="Screen Shot 2020-04-02 at 11 29 23 AM" src="https://user-images.githubusercontent.com/34068740/78268444-3210b300-74d6-11ea-89ee-01e3d83d6214.png">

## Tasks

- [ ] Confirm whether the "Check out your new personalized homepage" footer banner was permanently removed by the DS logon alert.
- [ ] If it was NOT removed, please make sure that the "Check out your new personalized homepage" footer banner will not come back once the DS Logon alert expires.

## Acceptance Criteria

- [ ] "Check out your new personalized homepage" footer banner will not come back after the DS Logon alert is removed.

**Comment by sanlouise** [comment]
PR merged, awaiting validation https://github.com/department-of-veterans-affairs/vets-website/pull/12317

**Comment by Samara-Strauss** [comment]
Since the message isn't currently live on VA.gov, I don't think there is any additional validation to do at this point.
