### ISSUE TITLE
Update Claim Status Tool to replace the button component with the va-button component

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#75352]
## Background Context
There are several places in claim-status folder where we use the `button` component. To follow the best design practices we should update these components to use `va-button`. 

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/75035 we did an audit of the claim status and listed which files had the `button` component.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

## Engineering 
- Add here

## Out of scope
- Add here
- 
## Open questions
- Is there any design work that needs to be done for this?
- Should we update for EVSS? **NO**

## Tasks
- [x] Update Expander.jsx
- [x] Update ClaimPhase.jsx
- [x] Update AddFilesFormOld.jsx
- [x] Update ClaimPhase.jsx
- [x] Update ClaimSyncWarning.jsx
- [x] Update ConsolidatedClaims.jsx
- [ ] Update Notification.jsx - (note on 2/23 - unable to update since this uses an icon within the button and va-button doesnt allow for that)
- [x] Update UploadStatus.jsx
- [ ] Update VaButtonGroupSegmented.jsx - (note on 2/23 - this is the evss and lighthouse toggle I think we can leave this as is)
- [x] Update AskVAPage.jsx

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Product performs functional QA and verifies acceptance criteria was met
- [ ] Engineering identifies staging users required to test and shares account and credentials with product

## Acceptance Criteria
- [ ] The claim-status folder doesnt have any files that are using the `button` component
- [ ] Button still functions properly and looks correct in the application after the correct button component is swapped in. Adjustments made if needed.

**Comment by pmclaren19** [comment]
Took a look at `src/applications/claims-status/components/ClaimPhase.jsx` and va-button is unable to do what button was doing where its a text button with an icon. Talked with Skyler about other approaches and we are thinking the best approach forward would be to remove the button and make it so the section cannot be minimized and is always expanded. Will discuss in Standup today!

**Comment by HeatherWidmont** [comment]
May have to re-estimate this based on how much refactoring has to go into each of the components

**Comment by pmclaren19** [comment]
@skylerschain @jacobworrell working this ticket in sections. These three files are ready for Design Q/A and Validation. https://github.com/department-of-veterans-affairs/vets-website/pull/28088

**Comment by pmclaren19** [comment]
@skylerschain did Design QA on the first pr! And is now doing design QA on the seconds pr. 

**Things to note:** 
There are currently no va web components that allow us to have icon buttons therefore I created this design ticket asking for that ability https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2526 .  Otherwise the following files will need to have the <button/> component...
- Notification.jsx
- VaButtonGroupSegmented.jsx

**Comment by HeatherWidmont** [comment]
@jacobworrell to validate today
