### ISSUE TITLE
DORA - Brainstorm metric tracking approaches

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#75367]
## Description
Initiate a brainstorming session to identify and evaluate different approaches for tracking DORA metrics effectively. The primary focus of this effort is to establish baseline tracking to help inform future work and measure impact. Ideally, this can be done in a way that it automated and reliable. The initial focus for our team is on Deployment Frequency, Lead Time for Changes. Another team will be focusing on Change Failure Rate, and Time to Restore Service.

---

## Tasks
- [x] Schedule and conduct a brainstorming session with reliability team members.
- [x] Document the planned approach is documented and sent to stakeholders for review

## Acceptance Criteria
- [x] A method is identified for tracking baseline DORA metrics
- [ ] A method is identified for tracking more complete DORA metrics

**Comment by JoeTice** [comment]
Initial brainstorming session conducted, more discussions will be needed in order to define long term strategy
