### ISSUE TITLE
DORA - Establish baseline tracking for lead time for changes

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#75369]
## Description
Determine the baseline metric for Lead Time for Changes to measure the efficiency of our development and deployment process.

## Tasks
- [x] Define the start and end points for measuring Lead Time for Changes.
- [x] Gather data on commit times and deployment times for a set period.
- [x] Calculate the average lead time from commit to deployment.

## Acceptance Criteria
- [x] A baseline average for Lead Time for Changes is established and documented.
