### ISSUE TITLE
DORA - Establish baseline tracking for deployment frequency

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#75368]
## Description
Establish a baseline for the Deployment Frequency metric to understand our current deployment practices and identify opportunities for improvement.

## Tasks
- [x] Identify and document the data sources for deployment information (e.g., GitHub Actions, Jenkins).
- [x] Develop a mechanism to extract and compile deployment data on a daily basis.
- [x] Calculate the average number of deployments per day over a defined period.

## Acceptance Criteria
- [x] A baseline average for Deployment Frequency is established and documented.
