### ISSUE TITLE
Bump http to 5.2.0

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#75370]
### Description
Bump `http` to 5.2.0

https://rubygems.org/gems/http

### Tasks
- [ ] Bump `http` to 5.2.0
- [ ] Merge to master

### Acceptance Criteria
- [ ] `http` is 5.2.0 in Gemfile.lock
