### ISSUE TITLE
Screen reader checklist: Update Zoom "share screen" instructions (Footer ticket #74557)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75385]
### Description
Zoom changed its share screen (and therefore, share sound) interface today (at least on MacOS):
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/5df95ea6-4b6c-40f6-8490-750fc62df69e)

The current Screen reader checklist says

> Tab or navigate past the “basic, advanced, and files” tab menu items and find “Share entire screen.” It should be the first item in the list of windows or applications to share. Use your space key to select it.

This is now incorrect. There doesn't appear to be a "Share entire screen" option - you start on the "Basic" tab, and the main desktop is selected by default. It also takes 10 tabs (from initial focus) to get to "Share sound", which might be worth adding to the screen reader section.

## Tasks

- [x] Verify procedure for Mac
- [x] Verify procedure for PC

## Acceptance Criteria

- [x] Procedures verified, ready to make update
- [x] Ticket has been created for the work

### Relevant URLs
[Research - Screen reader checklist](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-checklist)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Sitewide CAIA

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75385?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
@naomimarcussen this issue could related to Research & Design and we would love to have your input

**Comment by taylojill** [comment]
Hello @jknipes and @naomimarcussen. After re-reading the ticket, I think this is something I can take care of, but would be unable to check the interface on a MAC OS screen (assuming it may be different on a PC). Let me know if you would like me to update the instructions as requested.

**Comment by naomimarcussen** [comment]
@taylojill, Thank you for taking this on! You can reach out to @coforma-jamie for any questions or screenshots.

**Comment by coforma-jamie** [comment]
Here's what the share screen interface looks like on MacOS:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/e49a2b0e-5ace-41bb-a206-8ad3d4616a75)

When you hit "Share screen", focus immediately goes to the "Basic / advanced / files / apps" menu. Then you TAB a few times:
1. get out of the menu
2. get to the screen selection menu
3. the full-screen button
4. the four layout buttons (1 for each button)

Then you get to "Share sound," for a total of 8 TABs.

On "Share sound," you can press SPACE to select it, then TAB 5 times (through the down carat, "optimize" checkbox, "optimize" tooltip, "layouts and options" menu") to get to the "Share" button.

Here's a recording with key presses in the lower left: https://share.zight.com/nOuJv8gr

**Comment by taylojill** [comment]
Thank you @coforma-jamie! I'll reach out if I have any questions.

cc @jknipes

**Comment by taylojill** [comment]
Hi there @coforma-jamie - I rewrote the steps for setting up a screen share (tested on a PC). When I select Share screen, the focus immediately goes to the main desktop, see screen shot. I'll have to work with my teammate to test on a MAC. Please take a look at the rewrite and let me know what you think. <img width="987" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHVnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89c3451dac0642d021857cba90d74453147652eb/2024-04-29_15-22-16.png" alt="2024-04-29_15-22-16.png" /> <img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--389fbd48f204d73d39c527fcd2bb1a447f1b9410/2024-04-29_15-16-41.png" alt="2024-04-29_15-16-41.png" />

.

**Comment by taylojill** [comment]
Hi there! Yes, I think that may be the best solution @coforma-jamie. I'll rewrite and send you a draft for review. By the way, here's a link to the Confluence page in our draft space: [https://vfs.atlassian.net/wiki/spaces/PWD/pages/3120726031/Copy+of+Screen+reader+checklist](url)

**Comment by taylojill** [comment]
Great! Will this work!

![2024-04-30_15-05-55](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97645218/a18d392d-7672-46fd-86f6-f68ac3cdd4bb)

**Comment by coforma-jamie** [comment]
Item 2, `Tab to the "screen share" button and activate with your space bar`, also needs to say `"share" or `"share screen"` (since it differs between operating systems). Otherwise, I think this is spot on!

**Comment by taylojill** [comment]
Sounds good! I'll get the page updated and published! Thank you so much @coforma-jamie! Much appreciated.

cc @jknipes

**Comment by taylojill** [comment]
Page updated, ready for deployment.
