### ISSUE TITLE
[FE/BE] Should we use a different list to populate the "State" menu in the profile?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7539]
## Background

[Liz Lantz pointed out](https://dsva.slack.com/archives/C909ZG2BB/p1585681457127700) that our profile menu does not have states in the same order in the "States" menu we use in the profile as she saw in other "States" dropdowns in forms across VA.gov. According to Erik and Lihan, [this list](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/common/constants.js) is used in most other forms on VA.gov, while the profile uses [this list](https://github.com/department-of-veterans-affairs/vets-website/blob/eff2d5b91434906ccba6016c0ea6b6cfeaa0cab8/src/platform/forms/address/data/states.json).

We need to determine which list we should be using in the profile — is there a good reason to keep using the list we're using? Or should we switch so the order of the states in this dropdown matches what is used in other forms on VA.gov?

## Tasks

- [ ] Determine which list we should be using in the profile 
- [ ] Update the profile accordingly
- [ ] Test to make sure everything works (if the list is updated)

## Acceptance criteria

- [ ] Either determine that we do not need to change the list, OR determine that we do and update it/make sure it works

**Comment by Samara-Strauss** [comment]
Looks like this issue has already been taken care of. The list of states in the profile has been adjusted so that military base addresses (Armed Forces America, Armed forces Europe, Armed Forces Pacific) not appear in alphabetical order and not at the end of the list.
