### ISSUE TITLE
[Research] Create Conversation Guide

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75402]
## Related Documentation
- [MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/check-in-for-oracle-health.md#included-in-the-mvp)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the conversation guide for testing with users

## Tasks
- [ ] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [ ] Create conversation guide (template in research checklist above)

## Acceptance Criteria
- [ ] Review conversation guide with team (particularly product, Kristen, and Patrick)
- [ ] Post finalized conversation guide to GitHub folder

**Comment by benbrasso-agile6** [comment]
Reviewing

**Comment by benbrasso-agile6** [comment]
Convo is validated. @cgednalske you just have that last comment to resolve. Feel free to close this once it's in Git.

**Comment by cgednalske** [comment]
[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-02%20In-Person%20Travel%20Reimbursement%20Research%20for%20Oracle%20Health%20Facilities/conversation-guide.md) has been added to our GitHub research folder. Will share out to Kristen and Kay tomorrow along with the research plan. Closing this out!
