### ISSUE TITLE
[Research] Create Research Study Report

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75404]
## Related Documentation
- [MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/check-in-for-oracle-health.md#included-in-the-mvp)
- [Research plan and Conversation Guide]()
- Synthesis for this report completed in [ticket]().

## Description
A research report detailing findings and design recommendations from [research study name].

## Reference Materials
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)
- [Synthesis](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research/synthesis)

## Tasks
- [ ] Create research reports/readout documents of findings. 2 versions needed (Presentation and GitHUB Markup). Use this [report template](https://dsva.slack.com/archives/C0NGDDXME/p1629381608108300) and [GitHub Markup template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/sharing-research/research-findings-template.md)
- [ ] Conduct the [inclusive design analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/risk-documentation.md)

## Acceptance Criteria
- [ ] Post research report to GitHub as presentation and markup document
- [ ] Update the [research repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/wiki/Guidelines).
- [ ] Create necessary issues/tickets that address findings in coordination with Corey and Julie
- Schedule readout sessions with
    - [ ] Stakeholders (talk to Patrick about when to do this)
    - [ ] Team (either via Slack or Zoom meeting)
    - [ ] [Monday design/research sync](https://depo-platform-documentation.scrollhelp.site/research-design/Weekly-Design-+-Content-+-Research-Sync-Meeting.1938423884.html) (message Naomi Marcussen to get on the schedule)

**Comment by benbrasso-agile6** [comment]
@loripusey I need to close this ticket out, as in, document the takeaways quickly, and move it through (out) of the research ops flow. Can you tentatively add this to next sprint, so I can just get it out of the way?

**Comment by benbrasso-agile6** [comment]
Re ping on this comment above @loripusey

**Comment by loripusey** [comment]
@benbrasso-agile6 Add what to the next sprint? This closed ticket? Another new ticket? Can you just create the ticket you need? This back and forth is taking more time that if you just create the ticket you need.

**Comment by benbrasso-agile6** [comment]
Sure

**Comment by benbrasso-agile6** [comment]
Added to sprint goals

**Comment by benbrasso-agile6** [comment]
@cgednalske we need to do this report that Shane asked us about. I thought it made it into this sprint, but I guess it didn't. Anyways, if you wind up having time, there's: 

- This ticket
- Short term for referrals page for CC
- Long term for referrals page for CC
- Create research plan for the "check in with a staff member pilot" (which isn't quite ready to begin yet)

**Comment by benbrasso-agile6** [comment]
Could be good for Zach to start looking at the long term solution for CC. Lemme know if you think that's a good idea. @cgednalske

**Comment by cgednalske** [comment]
Which research report is this one for? Is it the previous unmoderated survey we did? The links aren't really leading anywhere specific so I can't quite tell. 

Yes I think it's a good idea for Zach to look at the long term CC solution!

**Comment by benbrasso-agile6** [comment]
Yeah, I need to edit all the research ticket templates at some point. 

Yes, it's the unmoderrated for the travel at OH facilities that we did in Optimal Workshop. 

I mentioned the short and long term referral page yesterday at UX Sync, but everyone was drawing a blank. I think maybe because it's been your focus. Can you check to see who has the short term ticket? And, do we have a long term ticket created yet?

**Comment by cgednalske** [comment]
Ok, sounds good about the unmoderated 👍 

Ciera has the short term ticket, and we don't have a long-term ticket yet. I can create that today. Do you think Ciera will still be working on the short term ticket? It seemed like she now has a bunch of design tickets.

**Comment by benbrasso-agile6** [comment]
Yes, I found the short-term ticket; thank you!

**Comment by benbrasso-agile6** [comment]
Agreed, re: she has a bunch of tickets. You might want to see if you want to grab that one.

**Comment by benbrasso-agile6** [comment]
I created this Slack Canvas that has links to our in progress work tickets - https://dsva.slack.com/docs/T03FECE8V/F07LYCUAWV6

**Comment by cgednalske** [comment]
[Research findings readme](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-04%20Unmoderated%20Content%20Evaluation%20for%20Multiple%20Facilities%20Selection%20in%20BT%20Oracle%20Health%20App/research-findings.md) created and added to the [repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/532) 👍  @benbrasso-agile6 feel free to make any additional changes when you're back.

**Comment by benbrasso-agile6** [comment]
Looks awesome, Christina. TYSM for doing that :)
