### ISSUE TITLE
[Research] Create Research Plan

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75401]
## Related Documentation
- [MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/Initiatives/check-in-for-oracle-health.md#included-in-the-mvp)
- Platform [research process](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Overview.1958740385.html) and [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/Research-Checklist.1958773011.html)

## Description
- Create the research plan, utilizing what research methodology, and what questions we plan to ask/get answers for during the study.
- Review Appointments research findings on OH to see what we can learn about, 1) any available online check in services for Veterans, and 2) any information about staff checking patients in or doing pre-registration for patients. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/appointments/research/2023-09-provider-based-scheduling-research/report.md

## Tasks
- [x] Create new folder for this specific test in this [overall research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research).
- [x] Create research plan (template in research checklist above)

## Acceptance Criteria
- [ ] Review research plan and conversation guide with team (particularly product, Kristen, and Patrick)
- [ ] Post finalize research plan to GitHub folder

**Comment by benbrasso-agile6** [comment]
@cgednalske I think one goal should be to understand Veteran's interest in checking in online (to give IVC that data).

**Comment by benbrasso-agile6** [comment]
@loripusey should this be high priority?

**Comment by loripusey** [comment]
Is this ticket a high priority? I think we need to be ready to conduct the on-site research a few weeks after we go live at the pilot site(s), but this ticket doesn't have to be done immediately.  I think we probably should understand whether Veterans want to check in on-line, though it sounds like the staff at OH facilities doesn't want that but it might help us to understand if we need to expand the product to accommodate those additional staff questions at OH facilities.

**Comment by benbrasso-agile6** [comment]
Yeah, it was marked as high priority for the sprint. Was just wondering if that was correct. Either way, should be fine to complete on time.

**Comment by benbrasso-agile6** [comment]
Yeah, I guess part of this research could be staff-facing, to understand their existing check in process, and whether online would help reduce workload.

**Comment by loripusey** [comment]
Yes, particularly because it seems like the OH staff does things way different.

**Comment by benbrasso-agile6** [comment]
Updated to include Melissa’s recent research report from going on site at Cerner facility

**Comment by benbrasso-agile6** [comment]
What we discussed today as far as priorities: 1a) UAT of BT with Veterans, 1b) What has staff heard about Veterans response to BT app, 2a) would Veterans be interested in being able to check in online, without having to wait inline, 2b) what's the current process for checking patients in and what would be challenges or advantages

**Comment by cgednalske** [comment]
@benbrasso-agile6 @loripusey a [research plan draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-02%20In-Person%20Travel%20Reimbursement%20Research%20for%20Oracle%20Health%20Facilities/research-plan.md) is complete in GitHub but will still need reviews and any resulting edits. Ok to carry this over?

**Comment by benbrasso-agile6** [comment]
Good w me. Since we're starting at sprint 1 next week, maybe do you want to adjust the points on this ticket for what work is left?

**Comment by benbrasso-agile6** [comment]
@cgednalske pls update points for what's remining so we can start fresh next sprint

**Comment by cgednalske** [comment]
👍 updated to 2 points

**Comment by benbrasso-agile6** [comment]
Validated 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-02%20In-Person%20Travel%20Reimbursement%20Research%20for%20Oracle%20Health%20Facilities/research-plan.md

**Comment by benbrasso-agile6** [comment]
@loripusey go ahead and take a look. We'll share with Kristen and Kay after @cgednalske and I find a moment to catch up.

**Comment by loripusey** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
@cgednalske check check if working

**Comment by benbrasso-agile6** [comment]
@cgednalske testing testing

**Comment by benbrasso-agile6** [comment]
Updated research plan based on convo with @cgednalske https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-02%20In-Person%20Travel%20Reimbursement%20Research%20for%20Oracle%20Health%20Facilities/research-plan.md

Closing ticket, but Christina will socialize to Kristen and Kay
