### ISSUE TITLE
Design | Update CH 36 (PCPG) Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#75406]
## Issue Description
_The Chapter 36 digital form (25-8832) is generating a pdf using an old version of the form from 2015. The digital form needs to be updated to align with the most recent version of the paper form._

Changes made to paper form:
- Moved instructions from the back of the form to the front
- Q10A: Added additional military departments. (Space Force, NOAA, USPHS)
- Q8: If the applicant is attending school or not. (Need to determine if they are attending a vet-success school, if so the - application is transferred to a contractor.)
- Q11: Character of discharge.
- Q16: Condensed to determine if child or spouse.
- Q20: Are they currently attending school?

[Additional Notes ](https://docs.google.com/document/d/1tZejPPUbRaDt162ZETL6_VJ2Ydi0zruV6zpPYlyHWgU/edit?usp=sharing)on form changes and requested enhancements

**Note:** The form number was updated in 2023 from 28-8832 to 25-8832.

[Old pdf](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_fill/forms/pdfs/28-8832.pdf)
[New pdf](https://www.vba.va.gov/pubs/forms/VBA-25-8832-ARE.pdf)

### Staging or Production Link
[Staging Link](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832/introduction)

### Prototype Link
[Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691434304975/3f0c405c820c184d21393b3bbd76324a5ee7c677?sender=u934f98f179a86c76e6ee9592)

### Test Users
vets.gov.user+24@gmail.com
[staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

---
## Tasks
- [ ] Review past research / SME interviews
- [ ] Create service blueprint
- [ ] Create an SME discussion guide
- [ ] Start conversations with OTED SMEs
- [ ] Update digital form to:
   - [ ] Add any new fields
   - [ ] Remove any depreciated fields
- [ ] Obtain CAIA approval

## Acceptance Criteria
- [ ] Wireframes for updated digital form

---

**Comment by fiorella-io** [comment]
3/11: Met with our SMEs
We got the following feedback:
- Remarks will not be included in our online form. It's used for additional service periods on the paper form. The online form will have the ability to add multiple service periods.
- We can use Branch of Service as a dropdown. We'll be combining Q10A and Q10B on the paper form
- For Q10B "Active,": we'll add the question "Are you currently on active duty?" on the Service Periods page. Based on the answer, we'll conditionally display "Projected separation date" and "Date separated from active duty"
- Our SMEs confirmed that we should ask for the "Character of discharge" and the "active duty" question for the most recent service period. 
- For the phone numbers in the form, our SMEs request that we can set a character count limit to US numbers to 10 characters, and include an international phone number that allows for more characters.

**Comment by fiorella-io** [comment]
On July 22, our Ch36 SMEs mentioned that it's OK to ask only about the latest/current service periods for military history. Designs were updated to reflect this: the list and loop multi-response pattern were removed. 

![image](https://github.com/user-attachments/assets/7b0cdf96-336d-4cd4-85b5-c6ca9c18dcc8)
