### ISSUE TITLE
BE CoP repo ownership 

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#75409]
### Background
There are some GitHub repositories the backend Community of Practice is connected to and ownership of repos needs to be defined. Clamav, for example. Ownership means being responsible for CodeQL vulnerabilities and pull requests. 

### Tasks
- [ ] Determine (and document in this ticket) which repos (besides vets-api) the BE CoP should own.
- [ ] Go over findings with CoP
- [ ] Add any extra responsibilities to the [Backend Support Responsibilities doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities).
