### ISSUE TITLE
Design | Profile | General Maint. | Update contact information Figma files to use radio buttons for military base addresses

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#75419]
## Background 

The design system recommends using radio buttons instead of drop downs when there are fewer than 7 options. We should update the military base address form accordingly. Both the `APO/FPO/DPO` and `State` dropdowns have fewer than 7 options.
<img width="512" alt="Screenshot 2024-04-25 at 8 09 57 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/ffd4b218-eb0a-433d-ab54-78d9e8907506">
<img width="506" alt="Screenshot 2024-04-25 at 8 09 53 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/a4d15659-a958-404a-9c18-4032ca4d81fe">

## Tasks 
- [x] update mobile and desktop designs for contact information so we use radio buttons instead of a dropdown menu
- [x] Share with PO/PM
- [x] Think about, and document, how we might validate this change with veterans. The DS team is asking teams to test this pattern. (💡 maybe behind a feature flag as an add-on to a UAT study?)
- [x] create a follow up ticket for FE (or alert FE to create one) 

## Acceptance criteria 
- [x] Figma files are updated
- [x] ready for FE development

**Comment by andaleliz** [comment]
Related to this work - the DS recently [published guidance on military bases in address forms](https://design.va.gov/patterns/ask-users-for/addresses#mailing-address---military-base), which doesn't use radio buttons. That makes sense if they're asking folks to test the pattern.

I recently created a new version of the mailing address form ([here](https://www.figma.com/file/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?type=design&node-id=291-5014&mode=design&t=aOKfs54ysEuBnUd3-11)) that reflects the pattern in the documentation. If we implement radio buttons, this would be the place to start.

**Comment by mtcA6** [comment]
Thanks for jumping on this. I do love how figma lets you call out all those details! Such an upgrade from sketch.

[Did you see the figma updates](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2480)? That's at least what I thought that ticket was. It looks like they approved the changes in figma but maybe not. How does one know?! 

Also, I checked in w/Thomas who kicked off the original thread in Slack and [he shared his figma file not sure if that helps or not. ](https://www.figma.com/file/PvD4V93eBOXyKwmBfIJk47/AVA-Component-library?type=design&node-id=198-286&mode=design&t=orYF8y2qpNZourkD-0) plopping that in here in case it's of use. 

And finally, regarding: 
> Think about, and document, how we might validate this change with veterans. The DS team is asking teams to test this pattern. (💡 maybe behind a feature flag as an add-on to a UAT study?)

I checked in w/ Matt Dingee and I don't think we need to put this behind a feature flag and test before launching. We should launch and monitor w/metrics and can certainly circle back and add this as a bonus question in a future study (do we track those somewhere? I can create a ticket to track those items if we don't). We should kick the tires on our analytics regime to ensure we're tracking the right things when we go to build and launch. Based on Matt's response it may make sense to split our metrics based on address type (ie. military base y/n)

<details><summary>screenshot of the convo w matt</summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/b41566a7-80ca-4d55-89c5-5764ca207681)

</details> 

I had the convo directly w/Matt and should have asked in the public thread. Will do that next time!

**Comment by andaleliz** [comment]
Those Figma files look super helpful and like this work is basically done! It makes me wonder why we even need to have our own version in our Figma files if it lives in so many other places.  

I know this ticket is assigned to Pam so I'll defer to her as to how she wants to move forward - but want to address the comment on testing and say that approach makes sense to me. "With veterans" translated to something more specific than analytics and anyone on the site but I agree that it seems very clear we're making an improvement here and it's low risk.

**Comment by pamela-drouin** [comment]
@mtcA6 @andaleliz launching & monitoring makes sense to me too! Doing a feature flag or UAT feels needlessly heavy-handed. 

I can just focus on updating the Figma files for Adam and then ping him here.
