### ISSUE TITLE
[ENG] 10-10EZ - BUG: Investigate validation errors on #create controller

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#75417]
## Background
As a result of changes made to the EZ form to utilize the Facilities API on the Facility Selection page, we are seeing validation errors on the #create controller in Datadog.  We have since turned off the feature toggle and need to investigate why this may be happening.

### Resources
- [Datadog APM traces](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Ahealthcare-application%20status%3Aerror%20resource_name%3A%28%22POST%20403%22%20OR%20%22V0%3A%3AHealthCareApplicationsController%23create%22%29&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=logs&traceQuery=&view=spans&start=1707148547841&end=1707234947841&paused=false)
- [Sentry errors](http://sentry.vfs.va.gov/organizations/vsp/issues/?query=is%3Aunresolved+hca&statsPeriod=24h)

## Tasks
- [x] Investigate errors along with changes recently implemented
- [ ] Determine root cause
- [ ] Determine possible solution(s)
- [ ] Review with team/PM prior to implementing solution to ensure there are no unknown conflicts
- [ ] Create ticket(s) for solution

## Acceptance Criteria
- Validation errors are investigated, root cause found and a possible solution is decided. A new ticket will be created to implement solution.

**Comment by jadon1979** [comment]
I met with Platform Support and they're stumped as well.  If it fails when vets-api is called then it should fail on the production console as well, but it does not.  I am creating a PR in an attempt to debug this.

**Comment by hdjustice** [comment]
@jadon1979 - Can you add points to this ticket when you have a moment?  Thanks!

**Comment by hdjustice** [comment]
The effort to begin using the LH Facilities API is on hold.  Determination discovered that we need to use our VASI number to get a key assigned with Lighthouse API.  Closing this ticket and will open another for steps to work with Lighthouse.
From Matt L:

> we need to apply for our own key to use.. which then means we would need to create our own endpoint that uses that key to access LH.
