### ISSUE TITLE
UX Transition off CIE

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#75423]
## Personal links
- [Airtable]([urlhttps://airtable.com/invite/l?inviteId=invg2JlWVnLfUhdX8&inviteToken=27306efd627750ecd9d9aa86ea1daac3df595926db822b70c5a63e724683adb7&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts])
- Guide to updating figma
- Existing murals in our private rooms
- Existing figma files in our private space
- Any other personal links that need to be sent to the team
- Any other resources as needed

## Description
As Kelly and Ya-ching transition off the CIE project, we need to make sure we have a centralized place to house all of their resources that need to be shared across the team

## Tasks
- [ ] Add resources with links to this ticket - either here in the body or below as comments
- [ ] Tag Ben on the ticket once team is aware

## Acceptance Criteria
- [ ] Resources and files are linked above or below in comments
- [ ] Resources have been shared with the team via this ticket

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75423?planning-poker) with Zenhub @kellysmith1008 @ytsaoca

**Comment by loripusey** [comment]
@benbrasso-agile6 Do we want to move these items out of @kellysmith1008 's google drive and into yours or mine?

**Comment by loripusey** [comment]
Great job documenting @kellysmith1008 !!

**Comment by benbrasso-agile6** [comment]
I think everyone has access to the one drive I have set up. Let me see if I can upload and share.

**Comment by benbrasso-agile6** [comment]
Oh, that product guides folder is the one we all have access to already
