### ISSUE TITLE
[Content] Create Content for SMS for VistA site that receives a "travel" text to 53079

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#75424]
## Description 

WHat happens if someone texts "travel" at a VistA site? 

Here's a message that VeText shows at VistA sites if someone texts "check in" for reference. 

> We now offer mobile check-in instead of the "I am here" process. Please go to the clinic waiting room. We'll send you a link to check in on your smartphone soon. In the future, text "check in" to 53079 when you arrive.

## Tasks
- [x] Create Content for SMS for VistA site that receives a "travel" text to 53079
- [x] Send to Justin at VeText

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [x] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75424?planning-poker) with Zenhub @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@jwowk when we (PCI, including VEText) release the online travel reimbursement feature to Oracle Health sites, we will want to add this VEText scenario into the VistA echeck-in responses. 

Let me know if you need anything else to track this work. cc @loripusey @brianseek @lee-delarm6 (in case this is CHIP work, and not VEText)

Veteran texts: 

> travel

VEText (or CHIP) response: 

>Online travel pay isn't available at your clinic.

> Here's how to file for reimbursement at https://va.gov/health-care/get-reimbursed-for-travel-pay/.

https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=1376-2172&mode=design&t=vmi0QNgAlBG82v2h-4

**Comment by benbrasso-agile6** [comment]
Updated based on @cgednalske feedback

**Comment by loripusey** [comment]
@brianseek Is this work that needs to be done on the CHIP side?

**Comment by brianseek** [comment]
@loripusey this would be a vetext thing
