### ISSUE TITLE
(Lauren) Demo/shadow deployment for Cheryl

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75431]
## Tasks
- [x] Coordinate with Cheryl your demo/shadow day
- [x] Account for additional time to provide her with context

## Acceptance Criteria
- [x] Cheryl will have shadowed how to do deploy

**Comment by jknipes** [comment]
Wednesday 4/17

**Comment by CherylEvans** [comment]
@jknipes @laucon Thank you, Lauren, and thanks to the entire PC team; I believe I'm ready to fly solo!
