### ISSUE TITLE
[CHIP] - Remove calls to vista during initiatePreCheckIn

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75446]
## Summary
Related to the emfile issues being worked on [here](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/75182), we can also help resolve this problem by reducing requests for vista tokens in the cache service from pre-check-in. 

The proposed solution here is to remove the vista appointment lookup that happens in initiatePreCheckIn. This would mean that we only store the stationNo, apointmentIENs, and patient auth info that comes from VEText in LoRota. The appointment fetching happens in refreshPreCheckIn already and would just continue to be the place where we call vista and save the appointment and demographic data to LoRota. This ties in with an old request to store less PII in LoRota until we need it. 

This should cut down the vista token requests significantly. We would only fetch the vista token in the pre-check-in flow when a patient clicks the link that would then kick off refreshPreCheckIn. Even if 100% of patients click their pre-check-in links, this would spread the usage out and reduce spikes, plus the requests to cache would go down by 50% since we are doing it once not twice.

## Tasks
- [ ] [CHIP] modify initiatePreCheckIn to only save data coming in from VEText and remove vista requests
- [ ] [CHIP] verify in staging that everything still works as expected end to end
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [x] not necessary

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
this work was never actually done, so this should move back to the product backlog and have the full points restored

**Comment by loripusey** [comment]
no longer needed; emfile errors have been fixed
