### ISSUE TITLE
[AWS DEVOPS] - IAM key permissions and rotation doc

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75443]
## Summary
We need to rotate the IAM keys in AWS every 60 days. The first step to doing this is requesting permissions from [Enterprise Cloud Solution Office (ECSO)](https://wfm.vaec.va.gov/servicedesk/customer/portal/2/create/52)

We also need to create a doc to outline the process. Here is [vetext's doc](https://github.com/department-of-veterans-affairs/vetext-devops/wiki/Rotating-IAM-Keys) for reference. We should also create a schedule and rotation for who does this work.

Here is the meeting recording of the vetext team doing the rotation with our team: https://drive.google.com/file/d/1owR-Pec3urKlulr3ysarHXER2bvbd7Ia/view?ts=65baa17b

[slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1706129749435889)

## Tasks
- [x] Brian has permissions
- [x] John has permissions
- [x] Kanchana has permissions
- [x] Gaurav has permissions
- [ ] Lee has permissions
- [x] Our playbook doc is created
- [x] Rotation schedule is set

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@loripusey / @anita-halici I added a recurring event to the cie-team calendar to Rotate the keys. It comes up every 60 days. During sprint planning when looking at the team calendar, if you see the event then add a ticket to the sprint. For now I figured that just who ever is on prod-support could do the task. We can revisit that if it seems like its the same person every time.  The next event lands on a Sunday (March 31) its probably fine to just have that happen on the Monday after or Friday before.

**Comment by brianseek** [comment]
Permissions request for whole team sent on 2/14/2024

**Comment by loripusey** [comment]
I'll go ahead and create tickets with dates on them to have in the backlog to pull in.

**Comment by loripusey** [comment]
@brianseek where are we with this ticket?

**Comment by brianseek** [comment]
still waiting on the permissions. I got a message that the request was approved, now waiting on fulfillment. The doc needs just a bit to be finalized. I got most of it done toward the end of yesterday. Lets roll this over until perms are secured

**Comment by brianseek** [comment]
link to doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/rotating-iam-keys.md

**Comment by brianseek** [comment]
thanks @loripusey!

**Comment by brianseek** [comment]
Everyone should have permissions now, waiting on confirmation from other developers. I tested and can confirm that I have access now

**Comment by brianseek** [comment]
Got confirmation from everyone except Lee who doesn't yet have access to AWS. Closing this ticket.
