### ISSUE TITLE
[UX, FE] 10-10EZ - Improvement: Remove Prefill alert from select pages

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#75445]
## Benefit to the Veteran
By removing the Prefill alert from some of the pages within the 10-10EZ form, the Veteran will not be annoyed or overwhelmed by seeing the alert present on every page.

## Background
We received some feedback from a VA colleague and Veteran on completing the 10-10EZ form.  Overall, the feedback was positive, but there was an "annoyance" reported about the Prefill alert that appears at the top of every page.
(the alert on the bottom of the pages will remain in place)

Now that the [exploration](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72871) has been completed, we need to gather a list of pages that display this alert, decide on which pages to keep and remove it from the other pages.

### Resources
- [Figma file](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-6399&mode=design&t=D1Oa8UPOpGw8ejsI-0) displaying the current pages with the alert in place
- [Comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61089#issuecomment-1922441039) on Figma migration ticket related to this work

## Tasks
- [x] Meet with UX to decide which pages to keep the alert, and which to remove
- [x] List the "remove" pages in this ticket
- [x] Remove the alert from those pages
- [x] Complete testing
- [x] Validate with team/PM
- [x] Launch into Production

## Acceptance Criteria
- Prefill alerts will be removed from select pages to reduce the cognitive load for Veterans.

**Comment by jessicastump** [comment]
Pre-fill alert shows on pages in staging when testing with users 3, 7 and 228. Reflected in Figma source of truth / production files. 

**Veteran information section**
- Birth sex (this is not the first page in the section and the first page in the section can not be prefilled, place of birth page)
- Race, ethnicity, origin (but have not seen it prefilled in staging before, so not sure it is needed)
- Mailing address
- Home address

**VA Benefits section**
- Disability Comp page (does this make sense? This page will only exist for Veterans who have a rating of up to 40% or No, 50+ skips this section) 
- Pension page

**Military service section**
- Last service branch, dates, character of service
- Service history (I have never seen this prefilled in staging before)

**Household section**
- Marital status (this should be the only page in this section)


**Insurance section**
- Was not showing for me on any pages when testing…

**Comment by jessicastump** [comment]
Recap per planning meeting 3/6: prefill alert will show once in the Veteran information section and the custom military service content version will also show on the last branch/dates page.

**Comment by longmd** [comment]
@jessicastump , do we want to look at doing our own alert with more generic messaging for that very first alert in the vet info section, then leave the platform military alert as is in that section?

**Comment by jessicastump** [comment]
Yeah, I think leaving the military alert content as is for now is good and only on the last service dates page. Interested to see if we can get more Veterans in research sessions to complete the form authenticated to see if they call these alerts out at all...

**Comment by longmd** [comment]
@jessicastump , that sounds great. What do you want to do with the content for the first alert? Do you want to go custom or leave it the canned message that is there now?

**Comment by longmd** [comment]
@jessicastump , perfect. If they're going away from that language, then it might just take care of itself. Otherwise we can always go our own route later. That's easy enough.

**Comment by longmd** [comment]
@jessicastump , this has been published and is ready for final sign-off. All my testing is working as expected.
