### ISSUE TITLE
Add Feature Toggle for Excluding Captain James A. Lovell from Online Scheduling

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#75454]
## Description
Add a feature toggle named `va_online_scheduling_booking_exclusion` to Staging and Production

---

## Tasks
- Add `va_online_scheduling_booking_exclusion` feature toggle

## Acceptance Criteria: 
- [x] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

---

**Comment by ldelacosta** [comment]
Feature toggle added. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cbae77da93d710b81ca363567e5d52b667b0c42/Screenshot%202024-02-13%20at%208.36.20%20AM.png" alt="Screenshot 2024-02-13 at 8.36.20 AM.png" />
