### ISSUE TITLE
Design Intent - IA Feedback - Benefits Non-Disability, Chapter 31/VR&E/28-1900, Form Updates

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#75451]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thank you for the detailed flows! I appreciate the error states and that you are addressing the flow that makes users go back to the wizard in order to pick back up a previously saved form.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- [ ] Title alignment: The form's H1, `<title>` tag and current H1 should be in aligment. Currently they're all a little bit different.

### Should

- [x] **Remove orientation slides:** It sounds like y'all are planning to remove these, which is good! The slides are easy to miss at the bottom of the form wizard, and don't really have an analog anywhere else on VA.gov. Ideally this would be replaced by a resources and support page, rather than duplicating info in a slide deck-like section.
- [x] **End of form exit:** Typically there's an exit hatch at the end of the form. I recommend adding a "Go back to VA.gov" action link on the final/confirmation page of the form.

### Consider

- [ ] We haven't seen the "do you plan to move within 30 days?" question and corresponding request for new address on other forms on VA.gov. Is this necessary for this form?
- [x] If the eligibility wizard stays around, you might reconsider the wording on the question “Did you receive a discharge status other than dishonorable?" It's hard to determine what it's asking. 

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [ ] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [ ] Add the Collaboration Cycle initiative epic

**Comment by fiorella-io** [comment]
Hi, @erinrwhite we have additional questions about some of your recommendations:

1.  Can we please have examples of the Must recommendation? Are you referring to the way the heading styles are coded?
2. For the Should recommendation - end of form exit, do we have design examples we should follow so we are consistent with other forms? Maybe you can point us to a form that's following this.

**Comment by erinrwhite** [comment]
@fiorella-io Yes of course!

1. Must recommendation - reading back over it, it sounds like a formatting suggestion but it's a content suggestion - I'm sorry it's unclear! The text of the `<h1>`, first segment of the `<title>` tag before `| Veterans Affairs` and the current page breadcrumb should be the same. They're all a little bit different now. Any questions, the CAIA IA's can steer you! @jennymayoco @kristinoletmuskat 

2. One example form with an exit is the [Request a Presidential Memorial Certificate](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247/confirmation). Many forms will have some other follow-up call to action beyond "Go back to VA.gov", but this is a good default. 

![Screenshot 2024-02-07 at 9 09 31 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/4b40eaae-efbf-48b9-9246-f1875f88e041)

**Comment by fiorella-io** [comment]
Thank you @erinrwhite for giving us an example form to follow.

For the Must recommendation, are you referring to all the information pages of the Ch 31 form? I did find a few pages where the breadcrumbs did not match (see screenshot). I don't know if our product team can update information pages. However, the actual form page, which our team will update, does match the breadcrumb

**Informational page:**
<img width="80%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/5835db79-5abd-4949-be7e-0f57c820da77">

**Ch 31 form page:**
<img width="80%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/07e3be80-f0c1-4755-a42a-1afbbd7247a7">

**Comment by erinrwhite** [comment]
@fiorella-io bingo, those Drupal pages will probably fall under CAIA's umbrella and is worth communicating with them about. For the form flow pages if your team is able to use the same text for all three items `<title>`, `<h1>` and breadcrumbs, that is preferred. Thank you!

**Comment by fiorella-io** [comment]
Updates:
- The Must feedback is in CAIA's backlog and CAIA will make sure all H1 will match the breadcrumbs on all information pages of this form
- Regarding the "Do you plan to move within 30 days?" question. Our SMEs want to keep this question because they want the claimant's latest address. We'll be meeting with them on 3/13 to see if, claimants who are moving, if we need their current address as well as their new address. We're trying to avoid claimants from typing two addresses if necessary.
