### ISSUE TITLE
Content updates to Connected Apps FAQ

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#75469]
## Issue description

Team requested updates to add Login.gov. We'll also make small style updates while we're in there. This page is set up as reusable Q&As, so we need to copyedit and publish each Q&A node separately.

Updated 7/23:
- [ ] https://prod.cms.va.gov/node/9623/latest 
- [ ] https://prod.cms.va.gov/node/8428/latest
- [ ] https://prod.cms.va.gov/node/8429/latest

No new changes since last copyedit:
- [ ] https://prod.cms.va.gov/node/9621/latest
- [ ] https://prod.cms.va.gov/node/8424/latest
- [ ] https://prod.cms.va.gov/node/8422/latest

---
## Tasks
- [x] Update page (Laura)
- [x] Copyedit & publish (Sara)
- [ ] Alert stakeholder (Laura)

## Acceptance Criteria
- [ ] Updates are live

**Comment by laurwill** [comment]
Hi @saratorres2 ,
Here's the page updates I chatted with you about. This is an interesting one, because the updates are to individual Q&A nodes on an FAQ page. This means we can't preview the changes, and you'll need to review in the "Latest version" tabs I've linked at top of ticket. You can also go to Revisions tab and compare revisions, if that's helpful!

The changes I made are to:
- Add Login.gov to the list of account types you can use to access connected apps
- Move links to their own line 
- Adjust other language to follow our style guide for [sign-in and identity content](https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification)

I'll send the changes to the product team for review before we publish, so for now your task is just to copyedit the changes in the linked nodes. There's no strict deadline here, so fine if this happens early next week. We can chat on Monday!

**Comment by saratorres2** [comment]
@laurwill All pages have been copy edited; no further changes needed at this point. It might be useful to add a line that says that "VA.gov profile" is an accepted usage on the [Sign in and identify verification](https://design.va.gov/content-style-guide/specific-topics-and-programs/sign-in-and-identity-verification)" page.

**Comment by laurwill** [comment]
Update here, I ended up removing the account types completely to make the content evergreen, per some updates in our sign-in widget work. I posted for the product team to approve in the intake. We can publish as soon as they respond!

**Comment by laurwill** [comment]
Hey @saratorres2 , we're ready to publish these updates now! I updated the top of this ticket to note that I made additional updates to 3 of the nodes per convo with product team in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75233). 

Could you re-copyedit the 3 updated nodes, and then publish all 6?

Let me know if you have questions!

**Comment by saratorres2** [comment]
@laurwill I've published edits to all 6 pages, but have not confirmed whether they are live yet.

**Comment by laurwill** [comment]
Confirmed! Closing out — thanks again Sara.
