### ISSUE TITLE
Talk with k15t about TOC and Smart link functionality not working

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#75466]
While working on [this page](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support) we learned that TOC are not supported in Scroll Viewport. We tried smart links instead. Those did not work either. 

The issue here is that both TOC and smart links work in Confluence...which is where we perform our deployment checks...and where all the teams build their pages. So everyone thinks that TOC and Smart links work, because they do in Confluence. But _come to find out_ they don't work in Scroll Viewport and therefore don't work on the Platform Website. 

This could be a LARGE issue because LOTS of pages use TOC and smart links. If these items are well and truly not viable options on Scroll Viewport then we will likely need to do a full audit of the Platform Website to find all pages with TOC and/or smart links. Make a list, and then go about fixing all of them. If however (and let's all hope this is the case) this is simply something that K15t can choose to support, then we simply must get them to see that they have to support this functionality. 

NOTE: here is K15t's response to TOCs (dated: Feb 6 2024) -- 

> Hi Jill,
The TOC macro is not supported in Viewport, see https://help.k15t.com/scroll-viewport/supported-macros-and-features
We disable Confluence’s table of contents macro by default because Viewport’s help center theme already comes with a global table of contents feature. You can enable it from Edit theme → Templates → Article → Table of contents
We deliberately disable the macro on your pages so that you don’t end up with any duplicates on the page. Our TOC feature has advantages over the macro, for example:
Once enabled, it’s automatically shown on all your articles. With the macro you have to insert it on all pages one by one
It’s visible even when the user scrolls down on a long page. In contrast, the macro is only visible if the user is on top of the page. That means, it’s easier for a user to navigate to specific sections, no matter where they are on the page.
Hope that help and clarifies why Viewport does what it does. The recommendation would be to get rid of the macro on your page and simply rely on the TOC that we generate for you on the right-hand site. If you still have concerns, please let us know!
Cheers,
Laura

### Context: 
Content Team's job is not to deploy and then check PW to see if page works after it is deployed. 
Instead, team checks to make sure within Confluence everything is operational. 
It is possible that the TOC viewed in Confluence _never appeared on PW_ but we would have expected a ticket to be raised long ago.

# Recent Changes rolled out to Platform Website:
(see features 1, 2, and 5 on [this slide deck](https://docs.google.com/presentation/d/1cqSmNiedHXWH-bAXfH6o3ozCvyY_pZUTJXHV6CMPv_k/edit#slide=id.g29f7cf82c1a_0_6))

- Pagination
- Vertical Search Filters
- Content Source Filter

## Questions

1. Are Smartlinks disabled as well? Disabled from Confluence by k15t?
Can k15t support the TOC macro, without further work on our end?
2. Are we forced to use the Help Center theme? Is it as simple as flipping a switch?
3. Did above changes to PW disable the macro?
4. Did k15t disable the macro in Confluence recently, after we have been using it all this time?
5. Will undoing above changes to PW correct the TOC issue?
6. How much work is involved in Content Team restoring TOCs at top of pages + smartlinks? Number of pages?
7. Can the work be performed in manageable increments over several sprints?

# Tasks
- [ ] Schedule call with k15t to Discuss options 
- [x] Discuss recent changes with Johnny Jesensky, including right-side menu. 
- [x] Determine amount of work necessary to restore TOCs

**Comment by jknipes** [comment]
[Guidance here](https://help.k15t.com/scroll-viewport/supported-macros-and-features)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75466?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
1. **Can k15t support the TOC macro, without further work on our end?**: _We don’t support the TOC macro, see https://help.k15t.com/scroll-viewport/why-does-the-table-of-contents-or-page-tree-macro- for a detailed explanation of why._
2. **Are we forced to use the Help Center theme? Is it as simple as flipping a switch?** _You are forced to use the help center theme as it’s the only theme available. Read more about the theme on https://help.k15t.com/scroll-viewport/the-help-center-theme . I’m not sure what you mean with ‘flipping a switch’. The help center theme is pre-selected for you when you create a Viewport site._
3. **Did our choice to turn on Pagination, Vertical Search Filters, and Content Source Filters disable the macro?** _No, those choices don’t influence the TOC macro_
4. **Will undoing above changes to correct the TOC issue?** _No, those choices don’t influence the TOC macro_
5. **Did k15t disable the TOC macro in Confluence recently, after we have been using it all this time?** _No, the TOC macro has never been supported in Viewport Cloud_
6. **How much work is involved in restoring TOCs at top of pages + smartlinks?**   _This is not possible._

**Comment by jknipes** [comment]
**Smartlinks**: Can we then make that text link to another section in the same page?
_Yes, you can. Read how on https://help.k15t.com/scroll-viewport/referencing-content-best-practices#ReferencingContent%E2%80%93BestPractices-Insertlinkstoarticlesectionsarticle-sections_

**Comment by jknipes** [comment]
@taylojill assigned you to this, since you initiated the first conversation with k15t, although we may already be able to close the ticket.

**Comment by BSmolensky** [comment]
I think we can close this ticket.

**Comment by jknipes** [comment]
Questions answered, moving to _Done_
