### ISSUE TITLE
Debt Letters: Debt Origin Content

### ISSUE THREAD

**Issue by mattpointzxer0** [department-of-veterans-affairs/va.gov-team#7547]
## User Story
As a Veteran who's been informed by the VA that I have incurred a debt, I need to be able to get in touch with someone at the VA that can explain to me the precise nature and origin of the debt, so that I can verify its validity before assessing my options.

## Goal
Once a Veteran has been alerted to the fact that the VA believes they owe a debt, we want Veterans to be able to quickly and easily get information about the origin and nature of the debt so that they can verify that it is legit and accurate. This will allow them to properly assess their options for resolving the debt. We will enable this by ensuring that the landing page has clear concise content providing Veterans the information and instructions they need (phone #s, links, etc) to verify a debt in the most efficient manner possible for their situation.

## Objectives or Key Results this is meant to further
- Increased traffic to calls-to-action?
- Decrease in response time to debt notifications?

## Tasks
-Spell out explanation of Debt Origin
-Provide contact information of who to contact
-Provide information on how to settle debt if there are no questions on origin of debt and the Veteran wants to settle 

## Acceptance Criteria
- [ ] _The information provided to the Veteran is correct for the type of deb letter mailed and type of debt incurred
- [ ] _All links provided are correct and functioning as expected
- [ ] _Content has been reviewed and approved by IA team 
- [ ] _preliminary 508 review passed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
