### ISSUE TITLE
Find VA Forms Search x Collab Cycle Plan

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7548]
## Reference docs:
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign)
- [Public Websites VSP Collaboration Cycle](https://docs.google.com/presentation/d/1V7tmk1yTZ9urJPPHuxL9fCsG1Yyd52X8/edit#slide=id.g7d56dbbfdb_1_131)

## Plan

- ~[ ] Define/Planning Kickoff-Intent~
- [x] Define Design intent --> #6710
- ~[ ] Discover Usability Testing Prep~ 
- ~[ ] Discover Research Plan Review~
- ~[ ] Discover IA Request~
- [x] Discover Analytics Request --> #7174 
- [x] Build Contact Center Review  --> #7703
  - [x] Product Guide
  - ~[ ] Product Video~
- [x] Build Privacy/Security Review 
- [x] Build Staging Review --> #8054 
  - [x] Release plan --> #8017
  - [x] Test Plan --> #6900 
- [x] Launch --> #5589
  - [x] Remove auth --> #8481 (June 8)
  - [x] Update Search Best Bet/Top Recommendation for Find VA Forms Search --> #7695 
  - [x] Redirect `/vaforms` to `/find-forms` --> [#5163](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5163) (June 29)
- [x] Post-launch
  - [x] Validate checkin (VSP)
  - [x] Validate/Launch Full A11y Review (VSP)
  

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)

## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team**

**Comment by MarciMcGuireGCIO** [comment]
MVP has been delivered; 508 results could take months, so I'm moving that deliverable out of this epic
