### ISSUE TITLE
[BE] Modify devops repo for travel claims secrets & VA Notify template IDs

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75497]
## Description
Modify `dev-settings.local.yml`, `staging-settings.local.yml`, `prod-settings.local.yml` in devops repo for adding travel claims API secrets & VA Notify template IDs

## Tasks
- [ ] [BE] **Modify `dev-settings.local.yml`**
- [ ] [BE] **Modify `staging-settings.local.yml`**
- [ ] [BE] **Modify `prod-settings.local.yml`**
- [ ] [BE] **Create AWS secure param store for dev/BTSSS**
- [ ] [BE] **Create AWS secure param store for staging/BTSSS**
- [ ] [BE] **Create AWS secure param store for prod/BTSSS**
- [ ] [BE] **Create AWS secure param store for staging/VANotify template IDs & secrets**
- [ ] [BE] **Create AWS secure param store for prod/VANotify template IDs & secrets**

## Acceptance Criteria
- [ ] Deployed to dev,staging,prod
- [ ] Tested on dev,staging,prod
