### ISSUE TITLE
How-to Apply Wizards x Collab Cycle Plan

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7549]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/README.md)

## Plan
- [x] **[Define] Kickoff-Intent** - 2020-08-07
- [x] **[Define] Design intent** - #(ticket)
- ~**[Discover] Usability Testing Prep** - #(ticket)~
- ~**[Discover] Research Plan Review** - #(ticket)~
- [ ]  **[Discover] IA Request** - #(ticket)
- [ ] **[Discover] Analytics Request** - #(ticket)
- [ ] **[Build] Contact Center Review** - #(ticket)
-   ~**[Build] Privacy/Security Review**~
- [ ] **[Build] Pre-Staging Review activities**
  - [ ] [Accessibility checklist in Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=staging-review-accessibility-checklist.md&title=%3CInitiative%3E+x+Staging+Accessibility+Checklist) - #(ticket)
  - [ ] [Compile QA test cases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=product-use-cases.md&title=%3CProduct%2FInitiative%3E+Use+Cases) - #(ticket)
  - [ ] [Release plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=product-release-plan.md&title=%3Cproduct%2Finitiative%2Ffeature%3E+x+Release+plan) - #(ticket)
  - [ ] Request QA test plan - #(ticket)
- [ ] **[Build] Staging Review** - #(ticket)
  - [ ] Resolve Staging Review findings - #(tickets)
- [ ] **Launch** - Date (and/or ticket)
- [ ] **[Validate] Post-launch checkin** - #(ticket)
  - [ ] Complete accessibility checklist in Prod - #(ticket if necessary)
- [ ] **[Validate] Launch Full A11y Review** - #(ticket)

## Acceptance Criteria
- Determine what's necessary/what's not and the associated timeline

## Reference
- [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)
- [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

## How to configure this issue
- [x] **Convert to an Epic**  
- [x] **Labeled with Team**

**Comment by johnhashva** [comment]
Closing this ticket (per @MickinSahni agreement) as the BAM teams are leading the Collab Cycle process for their individual Wizard efforts.   More [here.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/status_reports/status.md)
