### ISSUE TITLE
[BE] BTSSS Service Library Feature Flag

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75498]
## Description
Create BTSSS service library feature flag for integrating with new service library for submitting travel claims

## Tasks
- [x] [BE] **Create feature flag**

## Acceptance Criteria
- [x] Deployed to staging
- [x] Tested on staging

**Comment by randomsync** [comment]
added: check_in_experience_cerner_travel_claims_enabled
