### ISSUE TITLE
[BE] Implement token method in BTSSS Service Library

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75499]
## Description
Implement token method in BTSSS service library

## Tasks
- [ ] [BE] **Implement token method in Service class**
- [ ] [BE] **Add rspecs**
- [ ] 
## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
