### ISSUE TITLE
GA4: Perform Audit of BigQuery Views that are feeding Domo Reports

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#75509]
## Description
We need to determine and inventory the complete list of BigQuery views that are feeding our standardized Domo dashboards. We estimate the number of views to be between 50-70 views.

**Context:** This will be the list we need to do some transformation on to eventually get the GA4 data into a shape that the Domo reports can interrupt, minimizing the work we'll need to do within Domo itself.

<img width="195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelE1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b22cfbd234bd6a0cbf2a25da361572e14487a5ec/image.png" alt="image.png" />

## Tasks

- [ ] Pull list of BigQuery views 
- [ ] Filter to know which ones are tied to Domo dashboards
- [ ] 

## Acceptance Criteria

- [ ] List of views in BigQuery have been pulled and documented into a spreadsheet, attached to this ticket
- [ ] List has been confirmed/checked by one other member of the team.
- [

**Comment by johnny-jesensky-adhoc** [comment]
This is now a duplicate, closing this, as the work will be covered in [this ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/75520).
