### ISSUE TITLE
GA4: Create Github Template for VFS Teams to Input Custom Events

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#75513]
## Description
 We will be needing to audit the custom events and reports that VFS Teams and products are using. This is information that will be owned by the different VFS Teams, so we need to establish a way to formally request them from them. This ticket is to create and distribute Github Template, where teams can attach a spreadsheet with the following information:

- Team Name
- Product - should be linked to Product Directory, make sure name matches what's in directory https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory
- PoC
- Custom Events
- Event Type
- Level
- File URL
- Code Snippet
- Comments
- ~~Existing/Actively Used Reports - Domo, UA, Looker, etc.~~

**Business Case/Value Added:** This template will provide VFS Teams with a standardized form to take inventory of their custom events which will in turn, help us better estimate level of effort associated with each, and improve our workflow by putting these events directly on our Zenhub board. 

**Starting Artifact:** [TEMPLATE - Custom GA Events and Reports - [TEAM NAME HERE]](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit#gid=2087351809)

## Tasks
- [x] Create template in Github 
- [x] Create template in Sheets or Excel that can be attached to the GH template (similar to what we do for Form funnels) use starting artifact as a reference
- [x] Configure GH settings such as default assignee, labels, etc. to ensure template lands in our Team's Zenhub board
- [x] Test Github template to ensure working as expected.

## Acceptance Criteria
- [x] Github template has been tested to ensure it is functioning properly (assignees and labels are working, displaying on ZH board, etc.)
- [x] Github template has been shared with Andrea, and/or Dave for sign-off
- [x] **Template link has been shared with VFS Teams through the following:**
- [x] Team of Teams Meeting
- [ ] _vfs-all-teams_ Slack channel

### Template
- [Template Editing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-custom-event-request-(WIP).md)
- [VFS Facing Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D)

**Comment by johnny-jesensky-adhoc** [comment]
Need to create a separate task on the ID of report.

**Comment by johnny-jesensky-adhoc** [comment]
Github template form has been finalized, and announced in the VA.gov Team of Teams meeting on _**Tuesday, February 27, 2024.**_

Moving this to _**Done**_.

FYI @Blivaditis, @jestutt
