### ISSUE TITLE
Modify DST Staging Review process to upload issue tickets to vets-design-system-documentation repo

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75511]
## User Story
As a DST member, I want the issues Governance finds at component Staging Reviews to be documented in the vets-design-system-documentation repo opposed to the va.gov-team repo so that my team no longer has to transfer issues and is able to take action sooner.

As a Governance team member, I want to document DS component issues in the vets-design-system-documentation repo opposed to the va.gov-team repo so that DST is able to find the issues more easily and take action sooner.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description
While updating the "Next Steps for DST" section of the DST SR issue ticket template in the DrafingTemplate, @humancompanion-usds requested that Governance team create our issues in the vets-design-system-documentation repo opposed to the va.gov-team repo. This is so DST is able to find the issues more easily and is able to take action on correcting the issues sooner. 

The purpose of this ticket is to review all documents associated with the DST SR process to identify where changes need to be made to support this change.

**Note:** since we can no longer rely on the issue tickets and the Staging Review request ticket having a relationship via the Epic or Milestone, we'll need to think of a new way to connect tickets across repos. Shira's suggestion is to link to the Staging Review request ticket in the body of the issue ticket. This can be completed via the DraftingTemplate

## Impacted Artifacts
Everything within the [Design System Staging Reviews](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572025931/Design+System+Staging+Reviews) space, including:

_Text changes and questions noted in comments on each page_

- [x] [How to Request a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review)
  - Structural updates to this page for readability + 1 small text change
- [x]  [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)
- [x]  Design System Staging Review - During the Meeting _no updates_
- [x]  Design System Staging Review - After the Meeting _no updates_
- [x]  [How to Document Findings for a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572189697/How+to+Document+Findings+for+a+Design+System+Staging+Review#Reviewer-responsibilities-during-meeting)
- [x]  [Design System Drafting Template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2915926188/Design+System+Drafting+Template)
- [x]  High priority vs. priority vs. considerations _no updates_
- [x]  [How to generate Staging Review issue tickets - DST](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#DST-Drafting-Template)

## Tasks
- [x] Inform Carol Wong that this work has begun. If she plans to schedule a DST Staging Review, we want her to know that the docs (especially How to Request a Design System Staging Review) are being updated
- [x] Review all of the above Impacted Artifacts to identify which steps within which guidance docs are no longer applicable and/or in need of modification
   - For example, converting the Staging Review ticket to an Epic and creating the milestone are no longer needed.  
- [x] Since this is for DST only, feel free to make changes directly to the live guidance docs. No need for documentation drafts.
- [x] Shira will make changes to the DST DraftingTemplate

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Staging Review issue tickets for Design System components are documented in the vets-design-system-documentation repo 
- [x] Governance team's process for Design System Staging Reviews has been modified to reflect the change in repo
- [x] Governance team is no longer completing unnecessary steps for the Design System Staging Review 

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@shiragoodman Ah okay, thank you! I misunderstood. I'll revert those changes.

**Comment by erinrwhite** [comment]
@allison0034 ready for your review!

### Documentation updates

Text changes and questions are noted in comments on each page:

- [How to Request a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124196/How+to+Request+a+Design+System+Staging+Review)
  - Structural updates to this page for readability + 1 small text change
- [Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)
- [How to Document Findings for a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572189697/How+to+Document+Findings+for+a+Design+System+Staging+Review#Reviewer-responsibilities-during-meeting)
- [Design System Drafting Template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2915926188/Design+System+Drafting+Template)-
- [How to generate Staging Review issue tickets - DST](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#DST-Drafting-Template)

### Drafting template changes

@shiragoodman and I meet tomorrow to talk about changes to the [drafting template](https://docs.google.com/spreadsheets/d/1hMcbGxX95gxwEtqxDpJgdDzjeGXSRQxh6iiq9enYp44/edit#gid=727681601). I think all we will need to do is add a new field at the top of the drafting template to capture the URL of the collab cycle ticket. Then we can link to the CC ticket from each individual finding ticket.

For an illustration of how this will look, here is an [example DST staging review finding ticket](https://github.com/erinrwhite/stagingreview-mods/issues/17) that links back to this ticket (and text above this comment displays as "erinrwhite mentioned this issue"). 

Question: should we also plan to comment on the CC ticket and link to each of the findings tickets? Linking both ways? It would be time-intensive but would be another way to reinforce the connection.

**Comment by shiragoodman** [comment]
Awesome - thanks, @erinrwhite ! Looking forward to our chat today. Regarding your question, I think we probably first want to test it out. I don't want to make more work for us, and I'm hopeful since this change is being made for DST, a Platform team, that what we're doing will suffice. But let's test it out today to see how it works and see how visible the linkage is between finding ticket and the Staging Review request ticket.

**Comment by allison0034** [comment]
@erinrwhite changes look good so far! I did not resolve any of your comments in case you wanted to keep track.

**Comment by shiragoodman** [comment]
Thanks @erinrwhite ! Everything looks to be in order. @allison0034 lmk if you'd like me to review with you the changes that were made to the DraftingTemplate.

**Comment by allison0034** [comment]
@erinrwhite Drafting template and documentation look good!

**Comment by erinrwhite** [comment]
Thank you @allison0034 @shiragoodman ! Closing this one out.

**Comment by erinrwhite** [comment]
Ope! And posting to notify the team.
