### ISSUE TITLE
Medallia feature update - Add functionality to Medallia to allow subpaths to be recognized 

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#75521]
## Issue Description

Currently, Medallia's functionality limits URL recognition to explicit paths.  
As a Medallia user, I want the platform to recognize and process sub paths of specified URLs. 
We need to add the ability to allow sub paths for URLs so that I can gain deeper insights into customer behavior and preferences on those pages

---
## Tasks
- [x] Discovery - what is required for Medallia to support subpaths for URLs
- [x] Update Medallia survey JSON object to add for subpaths
- [x] Update `getSurvey` liquid filter to add functionality to recognize subpaths of a url
- [x] Update `getSurvey` unit tests
- [x] Q/A on review instance

## Acceptance Criteria

- [x] **Scenario 1: Medallia recognizes subpaths for specified URLs**
  - Given a URL that does not directly match an entry in surveyData.urls but is a subpath of an entry in surveyData.urlsWithSubPaths,
  - It should return the survey ID associated with the base subpath and the specific build type.

- [x] **Scenario 2: Medallia recognizes custom URL**
  - Given a valid URL that matches an entry in either surveyData.urls or surveyData.urlsWithSubPaths,
  - It should return the correct survey ID associated with the URL and build type.

- [x] **Scenario 3: Medallia handles Default Survey ID for Unmatched URLs**
  - Given a URL that does not match any entry in surveyData.urls or any subpath in surveyData.urlsWithSubPaths,
  - It should return a default survey ID

**Comment by aubreyarcangel** [comment]
Testing has been slow because we've been having issues with 1.) Medallia loading and 2.) issues with the review instance staying active. We've also been experiencing similar loading issues on staging, but it doesn't look like production has been impacted. 

I'll put in a ticket with vfs support if review instance issue persists
<img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69339b095643983941cebb327407cf4bb788dca7/Screenshot%202024-02-20%20at%205.00.24%20PM.png" alt="Screenshot 2024-02-20 at 5.00.24 PM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNktBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1a97229056ae37e4ff19161694004ed32d8e8fe/Screenshot%202024-02-21%20at%2010.26.26%20AM.png" alt="Screenshot 2024-02-21 at 10.26.26 AM.png" />

**Comment by ATMiddleton** [comment]
Update: 
@Anita Middleton
, my subpaths ticket is still not ready for review. I encountered some issues with the CI/CD build pipeline that were beyond the scope of my ticket. I made some minor changes this morning and I am waiting for the CI/CD process to complete and see if the issue still persists. If it does, I will have to raise a ticket with VFS platform support. Otherwise, it should be ready for review this afternoon, but likely will not be merged until at least Monday.
#1915 Medallia/75521 add functionality for subpaths
Note: Delete the description statements, complete each step. None are optional, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.
Summary
• (Summarize the changes that have been made to the platform)
• (If bug, how to reproduce)
• (What is the solution, why is this the solution)
• (Which team do you work for, does your team own the maintenance of this component?)
• (If using a flipper, what is the end date of the flipper being required/success criteria being targeted)

**Comment by ATMiddleton** [comment]
Aubrey Arcangel
  1:36 PM
@Anita Middleton
 status update: I received an initial PR review for the subpaths ticket, and and going to make a few changes from that feedback so we can get that work complete.

**Comment by ATMiddleton** [comment]
Incorporated feedback from PR review.  Requested 2nd review 2/29/24

**Comment by aubreyarcangel** [comment]
PR approved by team member of `vfs-public-websites-frontend` and awaiting 2nd PR from `va-platform-cop-frontend`
