### ISSUE TITLE
GA4: Data Mapping Prep - Create GA4 Views in BigQuery

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#75520]
### Description:
Currently, everything that feeds Domo is represented as a view within _vsp-sites_ in BigQuery. We need to determine which views are in fact being used by Domo, (out of the 50-70 views we currently have present), which we can use as the source of where we'll need to start our data mapping exercises.

The next portion of this task will be to map the attributes of the current UA data model to those within the new GA4 data model. 

**Note:** Some of this work will likely be dependent on custom events, so is just going to represent the **_initial_** mapping effort.

### Tasks:
- [ ] Perform a check/audit of all of the BQ views within vsp-sites, and identify the ones that are connected to a standardized Domo report.
- [ ] Record which views in a spreadsheet, or similar tracker, noting attributes
- [ ]  Review the list of custom dimensions defined in GA4 and map to the UA equivalent
- [ ] Create related views in BigQuery, that incorporate GA4 data
- [ ] Using UA views and new GA4 views, start initial mapping process.

### Acceptance Criteria:

- [ ] List of views in vsp-sites has been identified and documented in Analytics & Insights Team Confluence space, [GA4 Migration](https://vfs.atlassian.net/wiki/spaces/AT/pages/1928495134/GA4+Migration)
- [ ] New GA4 views will be created in BigQuery
- [ ] List of GA4 views, will be marked, (through use of BQ labels, a created list, or some other means)
