### ISSUE TITLE
[Copy] Improve copy for "We can't access your military information" message in the profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7553]
## Background

**Throwing this in the backlog. No immediate attention needed.**

While putting together build tickets for Profile 2.0, I noticed that the message we have if we can't load your military information doesn't really make sense re: what we tell users to do. Why are we are we telling them to change or correct their DD214 if they can't even see it? Isn't it more likely there is just a temporary problem with the profile that will fix itself, and we should tell them to come back later?

We should update this copy. We should determine 1) why it's most likely that military information didn't load, and then 2) we should figure out how to direct users.

![Military Information_Section won't load.jpg](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/c6700f50-586d-4e76-92b0-c9ccc92ab370)

## Tasks

- [ ] Determine why military information might not load
- [ ] Figure out how we should direct users (Come back later? Call the help desk for immediate attention? Both? Something else?)

## Acceptance criteria

- [ ] The "We can't access your military information" message has been updated to be more helpful and user friendly.

**Comment by tressaellen** [comment]
@peggygannon I totally agree with this! This was something that was in the old backlog - so we can include it in your larger content review if that is easier. I'll put together a ticket for each section of the profile with a link to the invision today - that might make it easier to track all of the content changes.

**Comment by peggygannon** [comment]
Hi, @tressaellen ok, sounds good. thank you!

**Comment by erikphansen** [comment]
@peggygannon  This error is due to an error connecting to the military info API. It's likely just a temporary glitch that will resolve itself if the user reloads the page. This situation is different from the "user not found in MVI/MPI" error which we handle differently. 

Finally, just for everyone's awareness, when this error happens the name of the military branch and branch badge in the header banner would not be shown since we cannot determine which branch they last served in.

**Comment by tressaellen** [comment]
@peggygannon I'm sifting through the updates you gave me for profile 2.0, and I didn't see anything for this alert. Do you have any suggestions?

**Comment by peggygannon** [comment]
Hello! @tressaellen here you go. 

Please let me know if this message below captures the correct message for this scenario?? per @erikphansen it seems like refreshing the page could resolve the error? 



**We can’t load your military information**
Please refresh this page to try again.

**Comment by tressaellen** [comment]
@peggygannon This is perfect - thank you!

**Comment by tressaellen** [comment]
![Screen Shot 2020-06-15 at 2.07.46 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/14450c7f-3b93-4de6-9c46-b943c1159c14)
