### ISSUE TITLE
[FSR Wizard] Move CodePen wizard to team version

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#75539]
## Description

For the wizard research, we'll need move the FSR wizard that was created under a personal CodePen account to a new Team account

Scenario: In common language describe the work or issue

Given: A veteran wants to fill out the FSR
When: A veteran wants to determine whether or not the FSR is for them
Then: A veteran will be able to click through the new wizard and get the answer they need

## Tasks
- [x] Move the collection and all it's files to the team account
- [x] Update all the links to match the team account URLs
- [x] Use the `/live` URL as the root URL now

## Acceptance criteria

- [x] Pens have been moved over
- [x] Links have been updated
- [x] Prototype has been QA'd

## Testing
- [x] Test logic and paths go to correct results

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Tom-Davis** [comment]
Closing as all work is complete.
