### ISSUE TITLE
Update README pages for all repos included in vets.gov-write team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75538]
## User Story
As a Governance team member supporting Platform Orientation, I want to ensure that all teams and individuals requesting access to Platform repos are funneled through the same process (ie Platform Orientation) so that there is less confusion for VFS teams.

Assignee: @briandeconinck 
Peer Reviewer: @rferguson13 

## Description
Governance team was recently made aware of the[ VA GitHub Handbook ](https://department-of-veterans-affairs.github.io/github-handbook/). This is the guidance that the VA GitHub admins use for everything related to the VA GitHub Organization. There is guidance in the handbook that communicates how VA teams can gain access to the various repositories within VA GitHub. This guidance differs from the guidance that the VA.gov Platform crew provides to the VFS teams. The VA.gov Platform crew guidance communicates that repo access is managed through the vets.gov-write gh team and the only path for being added to the vets.gov-write gh team is through Platform Orientation. The GitHub handbook guidance communicates that individuals should review the README for the repo they'd like to gain access to for guidance on how to gain access. Currently, we do not believe that any of the repos associated with the vets.gov-write team have this messaging within their README files.

### repos impacted

<img width="335" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/5502a1d5-5e02-45c8-9b32-6d1188d98c14">
<img width="374" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/962d6d97-4dcc-4191-bd3e-5ed69b49a73f">

## README text

Some quick notes on the thought process for the README text:
- The [VA GitHub Handbook](https://department-of-veterans-affairs.github.io/github-handbook/guides/onboarding/requesting-repo-access) doesn't specify what should be in the README, just that it should include "how to get access."
- The [repo for the GitHub handbook itself](https://github.com/department-of-veterans-affairs/github-handbook) does include a "Not a member of the repository, but want to request content changes, updates, additions?" section. This doesn't map exactly to "want to be added to this repo" but it's close enough to be a decent template.

After some back-and-forth with Rebecca, I've landed on:
> **Not a member of the repository and want to be added?**
> - If you're on a VA.gov Platform team, contact your Program Manager.
> - If you're on a VFS team, you must complete [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation) to be added to this repository. This includes completing your Platform Orientation ticket(s) in GitHub.

This should send everyone to the right place, and makes explicit that VFS team members need to complete the orientation ticket (which could get lost if we just point them to the Platform website page).

## Tasks
- [x] Since these repos are used by both Platform and VFS, there will need to be 2 paths. For Platform folks, they should be directed to contact their Program Manager. For VFS folks, they should be made aware that repo access is only given through Platform Orientation and then directed to Platform Orientation.
- [x] Review and update the README file for all repos impacted. 
      If the README already has guidance for how to gain access, do nothing. 
      If the README lacks guidance for how to gain access, provide instructions at the top of the page. Use a standard script for each repo.
   - ~~[ ] /betamocks **[read]**~~
   - ~~[ ] /breakers **[read]**~~
   - [x] /content-build
      - department-of-veterans-affairs/content-build/pull/1928 
   - ~~[ ] /covid19-chatbot **[archive]**~~
   - [x] /devops
      - department-of-veterans-affairs/devops/pull/14022 
   - [x] /gibct-data-service
      - department-of-veterans-affairs/gibct-data-service/pull/1029 
   - [x] /performance-dashboard
      - department-of-veterans-affairs/performance-dashboard/pull/4210
   - ~~[ ] /platform-console-api **[archive]**~~
   - [x] /platform-pst-console-ui-configuration
      - department-of-veterans-affairs/platform-pst-console-ui-configuration/pull/192 
   - [x] /react-jsonschema-form
      - department-of-veterans-affairs/react-jsonschema-form/pull/21 
   - [x] /va-adr
      - department-of-veterans-affairs/va-adr/pull/2 
   - ~~[ ] /va.gov-cms-devops **[archive]** **[read]**~~
   - [x] /va.gov-research-repository
      - department-of-veterans-affairs/va.gov-research-repository/pull/489 
   - ~~[ ] /va.gov-support-slackbot **[archive]**~~
   - [x] /va.gov-team
      - department-of-veterans-affairs/va.gov-team/pull/77042 
   - [x] /va.gov-team-sensitive **[private]**
      - department-of-veterans-affairs/va.gov-team-sensitive/pull/1527 
   - ~~[ ] /va.gov-vfs-teams **[archive]** **[read]**~~
   - [x] /vagov-content
      - department-of-veterans-affairs/vagov-content/pull/923 
   - [x] /veteran-facing-services-tools
      - department-of-veterans-affairs/veteran-facing-services-tools/pull/1024 
   - [x] /vets-api
      - department-of-veterans-affairs/vets-api/pull/15677 
   - [x] /vets-api-mockdata **[private]**
      - Already has repo access instructions 
   - ~~[ ] /vets-contrib **[archive]**~~
   - [x] /vets-json-schema
      - department-of-veterans-affairs/vets-json-schema/pull/845 
   - [x] /vets-website
      - department-of-veterans-affairs/vets-website/pull/28185 
   - ~~[ ] /vets.gov **[archive]**~~
   - ~~[ ] /vsp-infra-demo **[archive]** **[read]**~~
   - [x] /vsp-platform-revproxy
      - department-of-veterans-affairs/vsp-platform-revproxy/pull/158 
- [ ] All PRs merged

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance has addressed any gaps that may have existed for VFS teams to get repo access

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
FYSA @jknipes - I think there's some other guidance in the VA GitHub Handbook that may also be communicated on Platform Website. I'm not sure we want to write our own guidance on VA Github policies for Platform Website if/when there is already guidance in the handbook. Let me know if you'd like to discuss further.

**Comment by briandeconinck** [comment]
Quick questions for @shiragoodman: Looking at the [repos in the vets.gov-write team](https://github.com/orgs/department-of-veterans-affairs/teams/vets-gov-write/repositories):
- 5 repos have `Read` permissions for the team. `Read` has [some capabilities](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization) associated with it, but not the ability to make any code edits. Since these repos presumably have higher access requirements, should the message in their README file be different than the other repos?
- 8 repos are archived (either `Public archive` or `Internal archive`) and can't be edited even if you have `Write` permissions from vets.gov-write. Safe to skip those ones?

**Comment by briandeconinck** [comment]
Discussed at 2/26 Governance stand-up. PRs now opened for all repos, except:
- Archived repos
- Repos where vets.gov-write only has `read` permissions (because I can't do anything more than that!)

@rferguson13 Some of these (like va.gov-team) you might be able to review and merge. Others have specific code owners who have to merge the PR.

**Comment by briandeconinck** [comment]
End-of-sprint status! Six of 16 repos are waiting on codeowner review. Can't move these forward until an authorized reviewer gives the thumbs up.
- department-of-veterans-affairs/content-build/pull/1928
- department-of-veterans-affairs/devops/pull/14022
- department-of-veterans-affairs/va.gov-research-repository/pull/489
- department-of-veterans-affairs/vagov-content/pull/923
- department-of-veterans-affairs/vets-api/pull/15677
- department-of-veterans-affairs/vsp-platform-revproxy/pull/158

The rest of the PRs have either been reviewed by a codeowner (thank you to Ian!) or don't have any specific reviewer requirements. I'll work with Rebecca to merge those over the next day or two. Carrying over into the next sprint.

**Comment by rferguson13** [comment]
https://github.com/department-of-veterans-affairs/content-build/pull/1928 Was completed
