### ISSUE TITLE
[Design] Create 3 components in MHV - UA Library to use in Unified Checkin Figma File

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#75531]
## Tasks
- [x] Create Task card (new component) in MHV - UA Library to use in Unified Checkin Figma File
- [x] Create Appt details (needs new status) in MHV - UA Library to use in Unified Checkin Figma File
- [x] Create Appt list (needs new status) in MHV - UA Library to use in Unified Checkin Figma File
- [x] Publish
- [x] Switch components in Unified Checkin Figma file

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [x] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
@loripusey can we pull this in for @zach-park

**Comment by loripusey** [comment]
We can but we will be over capacity, we can look at in Sprint planning; I will go ahead and add it to the current sprint

**Comment by benbrasso-agile6** [comment]
@loripusey this will rollover; we have a bit more work after validation on https://github.com/department-of-veterans-affairs/va.gov-team/issues/75890 which is a bit more important

**Comment by zach-park** [comment]
The components are added, updated and published in [MHV - UA Library ](https://www.figma.com/file/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?type=design&node-id=482%3A163&mode=design&t=uWltUcfNwrGXvph4-1):
- Task card (new component) in [MHV - UA Library ](https://www.figma.com/file/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?type=design&node-id=482%3A163&mode=design&t=uWltUcfNwrGXvph4-1)
- Appt details (needs new status) in [MHV - UA Library](https://www.figma.com/file/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?type=design&node-id=482%3A163&mode=design&t=uWltUcfNwrGXvph4-1) 
- Appt list (needs new status) in [MHV - UA Library](https://www.figma.com/file/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?type=design&node-id=482%3A163&mode=design&t=uWltUcfNwrGXvph4-1)

The components are updated in the Unified Checkin Figma file.

**Comment by cgednalske** [comment]
It kind of comes back to the content discussion and where all that is housed. We started to talk about that with appointments, but it hasn't been the priority lately with everything else going on.

**Comment by benbrasso-agile6** [comment]
>I see what you mean, but I believe this has all the status component variations we need based on what we've been trying to do with this. Recall the goal being to avoid this being a place where we list out all content and instead just make sure to have the component types (where there is a checkmark vs. the clock icon for example). For example, the alert version of the status wouldn't need all variations listed out. They all use the same alert, so that would start to be just listing out content, which I think we wanted to avoid in the library.

I'm fine with that

**Comment by zach-park** [comment]
- Regarding the action lin to the task card, the VADS' task card seemed to work fine without any alteration so I only did the additional status (e.g., the status: You can check in starting at 4:15 p.m). But I can add the VADS' task card to the component so we can have both to choose from with in the component. 
- As for the missing statuses vs only having alert type (but update the content). I think we may need a discussion on which direction we want to go with. As of now, we actually have shown both cases in different components.

**Comment by benbrasso-agile6** [comment]
Want to chat about it at our UX Sync next week?

**Comment by cgednalske** [comment]
Agree, it seems like we use both approaches at the moment, so a discussion sounds good 👍

**Comment by zach-park** [comment]
I'll update the task card to include the action link for this ticket.

**Comment by cgednalske** [comment]
@benbrasso-agile6 this might also be another good reason for what you mentioned about having another library sync soon with Cierra

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske . Task cards is ready for review now. Thank you!

**Comment by cgednalske** [comment]
If for now we're adding all the content versions, do we need the "confirm your appointment" one as well? Also, where did that go in unified? It used to be a state shown along with Pre-check-in alerts, but I can't find it to link 👀

**Comment by cgednalske** [comment]
Probably just got deleted since it was just one card, but would be shown like the [check-in task card scenario section](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=0%3A272&mode=design&t=TkO2XWdU7zByqJFr-1).

**Comment by benbrasso-agile6** [comment]
> If for now we're adding all the content versions, do we need the "confirm your appointment" one as well? Also, where did that go in unified? It used to be a state shown along with Pre-check-in alerts, but I can't find it to link 👀

https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=551-18563&mode=design&t=RyQEhrsD5fyqkjT8-4

**Comment by cgednalske** [comment]
I see it in the list, but what about the related task card?

**Comment by benbrasso-agile6** [comment]
It won't be ever be a task card. E.g., the text message is always about reviewing your information.

**Comment by cgednalske** [comment]
Ooooh ya that's right! Because it would be the success alert instead right? Cool! False alarm. We're all good 👍

**Comment by zach-park** [comment]
> Ooooh ya that's right! Because it would be the success alert instead right? Cool! False alarm. We're all good 👍

Hi @cgednalske and @benbrasso-agile6 , I believe this ticket is ready to be closed. Please let me know if I missed anything on this ticket. Thank you!

**Comment by benbrasso-agile6** [comment]
I figured we'd meet on Tuesday and then close, if you're cool with that

**Comment by benbrasso-agile6** [comment]
Validated
