### ISSUE TITLE
Locate Mentions of Digital Service@VA to Office of CTO @ VA

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75530]
## Issue Description
VA has changed the name of their Slack work space to **Office of CTO @ VA**. 
Workspace is currently referenced in several places on Platform Website as **Digital Service@VA**. We need to locate and update all mentions to the new name.

---
## Tasks
- [x] Locate all mentions of Digital Service@VA on Platform Website
- [x] Create ticket to Update name of their Slack work space to **Office of CTO @ VA**.

## Acceptance Criteria
- [x] All references to VA Slack workspace have been identified
- [x] Work ticket created to update the name on all relevant PW pages.

## Links for Reference
- Slack thread [HERE](https://dsva.slack.com/archives/CL181NRJQ/p1707325341022889)
- Sample page on PW [HERE](https://depo-platform-documentation.scrollhelp.site/research-design/#Researchanddesign-SlackSlack)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75530?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75530?planning-poker) with Zenhub @CherylEvans

**Comment by taylojill** [comment]
After searching Confluence and Platform web site pages, I identified 3 mentions of "Digital Service@VA". I will create a ticket to get the pages updated with the new Slack channel name "Office of CTO @ VA"
[1.	https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools](url)
2.	https://vfs.atlassian.net/wiki/spaces/RD/overview
3.	https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240280/Onboarding

**Comment by taylojill** [comment]
New ticket created to change the name on three pages.

**Comment by jknipes** [comment]
Discovery is complete, moving ticket to _Closed_
