### ISSUE TITLE
NOD | Distinguish between NOD v1 and v2 logs.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#75546]
## Issue Description

In advance of our NOD v2 re-release it may be useful to distinguish between NOD v1 and v2 logs in DataDog.

**after launch deemed success**
- tear down the statsd counters, and remove them from DataDog.

---
## Tasks
- ~~Are we changing our contestable issues endpoint.~~ NO.
- ~~"" "" ""            s3 upload endpoint~~ NO.
- Update dashboards and monitors to use free DD statsD to show versions for LH claim submission endpoint
- Add new stats d counter `nod_evidence_upload.<version#>.queued`. Add before job enqueued.

## Acceptance Criteria
- [x] We can observe v1 and v2 appeal submissions in staging
- [x] We can observe v1 and v2 evidence submissions in staging
- [x] All monitors are unaffected by this

## Definition of Ready
- N/A. Ready now.

## Definition of Done
- [x] Acceptance criteria met.
- [x] Create follow-up ticket to tear this work down after successful launch.
- [x] Update https://github.com/department-of-veterans-affairs/va.gov-team/issues/64642

**Comment by data-doge** [comment]
Annie and I sketched out what this could look like here: https://github.com/department-of-veterans-affairs/vets-api/pull/15503/files

**Comment by anniebtran** [comment]
Update: waiting for Platform to approve PR so we can get it merged and into staging. I paired with Eugene to get the dashboards set up in DataDog and once the change is in staging we can test that the version distinction is present in the monitors

**Comment by anniebtran** [comment]
Follow up ticket created: https://github.com/department-of-veterans-affairs/va.gov-team/issues/76676
