### ISSUE TITLE
[BE] Modify Appointments Identifer Serializer to add IDIPI & appointment type field for OH appointments

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75543]
## Description 
Modify Appointments Identifer Serializer to add IDIPI & appointment type field for OH appointments

## Tasks
- [ ] [BE] **Modify Appointments Identifer Serializer to add IDIPI & appointment type field for OH appointments**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
