### ISSUE TITLE
[Design] Create Final Wireframes to handle selecting an appt for Veterans that might have appts at multiple facilities

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#75544]
## Tasks
- [ ] Create final wireframes to handle selecting an appt for Veterans that might have appts at multiple facilities. Related [Slack thread](https://dsva.slack.com/archives/C02GXKL8WM6/p1707321463352139) and [Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1707253719314269). 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75544?planning-poker) with Zenhub @kellysmith1008 @cgednalske

**Comment by benbrasso-agile6** [comment]
@cgednalske feel free to pair up with @zach-park on this one; he will need to catch up on the context of this work. @zach-park go ahead and review the slack threads mentioned in the task above.

**Comment by benbrasso-agile6** [comment]
https://dsva.slack.com/archives/C022AC2STBM/p1707924368526669

**Comment by benbrasso-agile6** [comment]
Reminder: All finished here? If so, let's provide Lori with the boards that have changed pls

**Comment by zach-park** [comment]
@benbrasso-agile6 , I believe this task is complete. Cc: @cgednalske

**Comment by benbrasso-agile6** [comment]
Thanks!
