### ISSUE TITLE
[BE] Modify Appointments Identifer Serializer to add IDIPI field based on appointment type

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75541]
## Description 
Modify Appointments Identifer Serializer to add IDIPI field based on appointment type

## Tasks
- [ ] [BE] **Modify Appointments Identifer Serializer to add IDIPI field based on appointment type**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
