### ISSUE TITLE
[BE] Update Client Class to handle IDIPI 

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75554]
## Description
Update Client Class to handle IDIPI 

## Tasks
- [ ] [BE] **Modify claims_data for switching between IDIPI & icn based on appointment type**
- [ ] [BE] **Modify `submit_claim` method parameters to receive appointment type**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
