### ISSUE TITLE
[BE] Integrate TravelClaimSubmissionWorker with BTSSS Service library

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75552]
## Description
Integrate TravelClaimSubmissionWorker with BTSSS service library behind the feature flag

## Tasks
- [ ] [BE] **Integrate `TravelClaimSubmissionWorker` with BTSSS service library behind the feature flag**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
