### ISSUE TITLE
Rated Disability - sanity check and resume migration

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#75564]
Pending Flashes and Special Issues discovery
Pending bug resolution from LH

## Issue Description
This item is to reassess Rated Disability once we get the go ahead after Lighthouse and Mobile testing. Sanity check RD functionality and then resume the migration at 5%

https://vagov.ddog-gov.com/dashboard/zc5-23v-wpq/benefits---dbex---evss-to-lh-rated-disability?from_ts=1689866014643&to_ts=1689869614643&live=true

Is 526 sending any special issues other than POW to EVSS, that will need to be replaced by Lighthouse.  

## Tasks
- [x] Revisit the RD dashboard for any necessary changes
- [x] Sanity check RD functionality for consistency on both sides
- [ ] Do a lean Canary (1 user)
- [ ] Raise traffic to 5%
- [ ] Test for special issues as they are discovered in the Flashes discovery ticket

## Acceptance Criteria
- [ ] Sanity checks pass and traffic is raised to 5%

**Comment by alatempa24** [comment]
Per [this thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1707497517637449) in DSVA Slack Rated Disabilities update is pushed to Lighthouse Staging today. Removing 'on hold' for sanity check for DBEX to resume when we have capacity.

**Comment by alatempa24** [comment]
TBD on date when this will be in production

**Comment by mchae-nava** [comment]
Audit and test ACs checked in [97336](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97336)
