### ISSUE TITLE
Increase traffic to production to 75% of traffic

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75568]
## Issue Description

**- This task is dependent on success of release to 50% of traffic testing release in production**

See the [release plan schedule in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?wid=0-1704481087285) for reference.

---

## Tasks

- [ ] Increased the online form traffic to 75%
- [ ] Monitor submissions via Datadog display and alerts
- [ ] Twice a week, provide `saved claim IDs` and `LH UUIDs` to stakeholders via Sharepoint

**Comment by vbellissimo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/75568?planning-poker) with Zenhub @mjknight50

**Comment by aplatt-coforma** [comment]
Approved: https://dsva.slack.com/archives/C05MS96P6P2/p1708633317227259
