### ISSUE TITLE
Shadow Research: Move documentation to Sharepoint folder

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#75560]
## Issue Description

- In order to better understand the end-to-end experience of filing for benefits, we conducted [Veteran Shadowing Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2023-11-Shadowing-Research). 

- All artifacts from the Shadow Research must be consolidated[ into one Sharepoint folder here.](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FDisability%20Benefits%20Experience%2FResearch%20and%20Design&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947)
---
## Tasks
- [ ]  Create a Shadow Research folder on Sharepoint
- [ ]  Add artifacts to the folder (what all needs to be here?)
- [ ]  Shannon is ready for us to delete the videos 

## Acceptance Criteria
- [ ] Artifacts are consolidated in the folder 
 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
Can this ticket be closed?
