### ISSUE TITLE
[BE] Modify SessionsController param for facility_type and statsd metrics in vets-api to support travel_claims standalone app

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75563]
## Description
Currently `check-in` and `pre-check-in` workflow metrics are collected from [statsd](https://github.com/department-of-veterans-affairs/vets-api/blob/ef7ee74bc38471c779b17e8f64a44ab283e364c6/modules/check_in/config/initializers/statsd.rb#L56-L60) based on the check-in type sent from front end.  

Since the standalone travel claims application going to use the same SessionsController (as in check-in and pre-check-in workflow), including the appointment type parameter to differentiate between `vista` vs `OH` appointments would prevent `check-in` and `pre-check-in` workflow metrics from getting impacted by travel claims application usage.

Enable `facility_type` as permitted_params in [sessions_controller](https://github.com/department-of-veterans-affairs/vets-api/blob/ef7ee74bc38471c779b17e8f64a44ab283e364c6/modules/check_in/app/controllers/check_in/v2/sessions_controller.rb#L36-L37) & modify [statsd](https://github.com/department-of-veterans-affairs/vets-api/blob/ef7ee74bc38471c779b17e8f64a44ab283e364c6/modules/check_in/config/initializers/statsd.rb#L56-L60) config to include travel_claims if appointment_type is `OH`

## Tasks
- [ ] [BE] **Modify SessionsController for facility_type parameter**
- [ ] [BE] **Modify statsd config for adding travel_claims as checkInType for OH appointments**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Verified SessionsController Create in staging<img width="1401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1iQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58482604580c64b1268435d51a2b47738143d253/image.png" alt="image.png" />

**Comment by kanchanasuriya** [comment]
Verified SessionsController Show endpoint
<img width="1358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03e4d76fa5dddc9eece075808d09838d0db235f2/image.png" alt="image.png" />
