### ISSUE TITLE
Design spec for cancelation flow

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#75565]
## Task Description

Create a dev spec for the cancelation flow changes that come out of usability testing. 
- [x]  M - Follow up with Laura and Misty about empty states. 
- [x]  M - Ally best practices of [unique heading for title ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md)(currently the date/time) 
- [x]  M - Accessibility Annotations
- [x]  C - Create design specs in a new design file
- [x]  C - Change Requests Icon.
- [x]  C - Add "details you shared" to canceled page
- [x]  C - Add scheduling facility to canceled page

## Notes and References
- Account for all cancelable appointment and request types.

## Acceptance Criteria
- [x] m/t/d screens
- [x] A11y annotations
- [x] User flows
- [ ] Product has updated copy docs
- [ ] Product has updated feature documentation.
- [x] Review with @outerpress 
- [x] Review with SME either in meeting or the slack channel

## Deliverables
[- Design Spec](https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2266%3A80307&mode=design&t=TQeDtvdO2CZhdapk-1)

**Comment by melissa-lefevre** [comment]
A descriptive title with the context of the appointment (e.g., in-person or phone appointment) will help users quickly understand the content of the page, aids navigation, and ensures accessibility for all users, aligning with WCAG guidelines. While the title is not required to be unique, it is best practice. 

Here is an excerpt of [G88: Providing descriptive titles for Web pages](https://www.w3.org/TR/WCAG20-TECHS/G88.html) rule : 

> The title of each Web page should:
> 
> Identify the subject of the Web page
> 
> Make sense when read out of context, for example by a screen reader or in a site map or list of search results
> 
> Be short
> 
> It may also be helpful for the title to
> 
> Identify the site or other resource to which the Web page belongs
> 
> Be unique within the site or other resource to which the Web page belongs

**Comment by outerpress** [comment]
See epic for related dev tix.

**Comment by outerpress** [comment]
@ldelacosta do you have separate tickets for documentation? How do you want to handle updating the feature docs/copy docs/etc

**Comment by outerpress** [comment]
@ldelacosta we're good to close this one on our end
