### ISSUE TITLE
Developer Docs Audit: Wave 3

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75586]
## Issue Description
Locate SMEs and Update Documents per [Update Wave 3](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit#gid=799240787) 

---
## Tasks
- [ ] Locate and Connect with SMEs for Front End documentation
- [ ] Update documentation per guidelines on [Google Sheet](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit#gid=799240787)

## Acceptance Criteria
- [ ] 66 Front End Developer Docs updated
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
