### ISSUE TITLE
SPIKE: Review logging and monitoring for errors

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75585]
## Issue Description
We need to create better, more consistent logging so that we have a better understanding of the health of online Pension form submissions.  
We also need to be more verbose with our logging so that we can track submissions end to end.

---
## Tasks
- [ ] Identify places where there are inconsistencies in error logging.   
- [ ] Identify where we should log in gradient:  error, warn, info
- [ ] Identify places where more verbose logging can be added.  Such as:
 "Starting XYZ... " 
"Finished XYZ... "
"Started upload.. "
"Finished upload... "
- [ ] Identify where logs need more detail so that the person reading it can make sense of it
- [ ] Identify any error or problematic states that logging might be missing

## Acceptance Criteria
- [ ] Next step will be to implement the changes.

**Comment by TaiWilkin** [comment]
### Suggested Tasks
- PensionClaimsController.show: add a `rescue` which logs then raises the error
- PensionClaimsController.create: replace `PensionBurial::TagSentry.tag_sentry` call with a pensions-specific tag
- PensionClaimsController.create: add `StatsD.increment("api.pension_claim.attempt")` when beginning a submission
- PensionClaimsController.create: when logging "Begin 21P-527EZ Submission", instead log "21P-527EZ submission to Sidekiq begun" `{ confirmation_number: claim&.confirmation_number, user_uuid, in_progress_form_id: in_progress_form&.id }`  to match other logs
	- Note: this is correctly an 'info' log
- PensionClaimsController.create: when logging "Submit 21P-527EZ Submission Failed for user_id: " instead log "21P-527EZ submission to Sidekiq failed" and pass `{ confirmation_number: claim&.confirmation_number, user_uuid, in_progress_form_id: in_progress_form&.id, errors: claim&.errors&.errors }`
	- Note: this is correctly an 'error' log (complete failure)
- PensionClaimsController.create:  When logging "Submit 21P-527EZ Submission Success" instead log "21P-527EZ submission to Sidekiq succeeded" and pass  and pass `{ confirmation_number: claim&.confirmation_number, user_uuid }`
	- Note: this is correctly an 'info' log
- PensionClaimsController.create: Add a `rescue` block which error logs "21P-527EZ submission to Sidekiq failed" (with `{ confirmation_number: claim&.confirmation_number, user_uuid, in_progress_form_id: in_progress_form&.id, errors: claim&.errors&.errors }`) and calls `StatsD.increment("api.pension_claim.failure")` then re-raises the error
- PensionBenefitIntakeJob.perform: Lighthouse::PensionBenefitIntakeJob Attempt" update to "Lighthouse::PensionBenefitIntakeJob submission to LH begun"
	- Note: this is correctly an 'info' log
- PensionBenefitIntakeJob.perform: "Lighthouse::PensionBenefitIntakeJob Upload" update to "Lighthouse::PensionBenefitIntakeJob sub
- PensionBenefitIntakeJob.perform: "Lighthouse::PensionBenefitIntakeJob Upload" update to "Lighthouse::PensionBenefitIntakeJob submission to LH attempted"
- PensionBenefitIntakeJob.perform: 'Lighthouse::PensionBenefitIntakeJob FAILED!' update to "Lighthouse::PensionBenefitIntakeJob submission to LH failed, retrying"
	- Note: this is correctly a 'warn' log (the job will be re-attempted)
- PensionBenefitIntakeJob.sidekiq_retries_exhausted: Test if the claim.confirmation_id can be logged here
- PensionBenefitIntakeJob.sidekiq_retries_exhausted: 'Lighthouse::PensionBenefitIntakeJob Exhausted!' update to "Lighthouse::PensionBenefitIntakeJob submission to LH exhausted!"
	- Note: this is correctly an 'error' log (complete failure)
- PensionBenefitIntakeJob.check_success: 'Lighthouse::PensionBenefitIntakeJob Succeeded!' update to "Lighthouse::PensionBenefitIntakeJob submission to LH succeeded"
- PensionBenefitIntakeJob.cleanup_file_paths: add a rescue block that logs "Lighthouse::PensionBenefitIntakeJob cleanup failed"
Please find additional notes attached. [logging_notes.md](https://github.com/department-of-veterans-affairs/va.gov-team/files/14437999/logging_notes.md)

**Comment by buddhima-coforma** [comment]
@TaiWilkin I started this epic and have been tracking some items there too FYI 
We haven't discussed them yet but can pull them in if it's easier for you
https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/77235

**Comment by buddhima-coforma** [comment]
@TaiWilkin yes let's do that. You can break them up in a suitable way. Thank you!

**Comment by TaiWilkin** [comment]
Tickets added to the Logging epic
