### ISSUE TITLE
Build and publish After You Request a Decision Review in Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#75591]
## Issue Description

We need to build the page in Drupal, review, and publish.

- [After you request a decision review](http://va.gov/decision-reviews/after-you-request-review/)
- [After you request a decision review_AB.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13957538/After.you.request.a.decision.review_AB.docx)

## Tasks
- [x] Build Drupal page (Victoria)
- [x] Review (Juliana)
- [x] Publish 
- [x] Send live page to State Department for QA (Randi)
- [ ] Input any changes (Juliana)
- [ ] Review and publish
- [x] Create ticket for PW to add Spanish toggle

<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

## Acceptance Criteria
- [x] Page is live
- [x] Ticket created for Spanish toggle

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2 This page is built in Drupal and ready to review and publish:
 http://preview-prod.vfs.va.gov/preview?nodeId=70811

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2 I need to do a few updates on the page. Please don't publish it yet. I will let you know when it's done and saved again in the draft. Thank you!

**Comment by moviedosoco** [comment]
@saratorres2 Changes were done and "Después de solicitar una revisión de decisión" page is saved in draft: http://preview-prod.vfs.va.gov/preview?nodeId=70811

Please check with Laura Willwerth before publishing to confirm that the EN version with the changes is ready to publish as well, so both pages can be published together. Thank you!

**Comment by RLHecht** [comment]
@juliana-jara Next step on this one is to review and copy edit the Spanish draft. There are a few stylistic changes saved as draft on the English page that I'm waiting to confirm we can publish. If we do we'll want to make those same changes on the Spanish page so that they align. I'll post here once I hear back. Thanks!

**Comment by juliana-jara** [comment]
Hi @RLHecht I compared the two pages and there are only some minor edits to tackle. You can [see them here](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2375591.docx?d=we5ab00d08bf14de6b0972de1bcc265ea&csf=1&web=1&e=W7slHf).

**Comment by RLHecht** [comment]
thanks! you can go ahead and update the Drupal page with these changes. Let's leave the hours in for the phone number. It should be added to the English page since our style is to always have hours with numbers. I can create a ticket for that.

**Comment by juliana-jara** [comment]
@RLHecht Changes saved as draft. I also called the phone number and added instructions on how to obtain help in Spanish.

**Comment by RLHecht** [comment]
@juliana-jara I did another pass through this page and made a few tweaks (changed a link now that we have a Spanish page live, fixed some spacing issues, etc.). I also capped Board Appeals and Supplemental Claims throughout since we have that in our glossary. Can you check all my changes and let me know if I introduced any errors or should fix anything? Once you're done I'll publish. Thanks! Here's the preview link: https://preview-prod.vfs.va.gov/preview?nodeId=70811

**Comment by juliana-jara** [comment]
@RLHecht  I compared your revision with mine and it looks like you changed everything that needed to be changed based on the Spanish Glossary. I think this page is ready.

**Comment by RLHecht** [comment]
Thanks! just published the page and will send out the link once it's live.

**Comment by RLHecht** [comment]
Page is live and QA sent.

**Comment by RLHecht** [comment]
@juliana-jara here is the QA back from State. Please input any changes and let me know if there's anything we don't want to do. Thanks!

[LS-2024-0125469 -LQA Notes-es_v1__VA.gov After you request a decision review.docx](https://github.com/user-attachments/files/20488577/LS-2024-0125469.-LQA.Notes-es_v1__VA.gov.After.you.request.a.decision.review.docx)

**Comment by RLHecht** [comment]
Thanks! I noted the breadcrumbs on the ticket for PW and I'll let State know about the instructions for getting help in Spanish. I think we can close this ticket!
