### ISSUE TITLE
Build and publish Board Appeals page in Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#75590]
## Issue Description

We need to build the page in Drupal, review, and publish.
- [Board Appeals](http://va.gov/decision-reviews/board-appeal/)
- [Board Appeals_AB.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13957536/Board.Appeals_AB.docx)

## Tasks
- [x] Build Drupal page (Victoria)
- [x] Review (Sara)
- [x] Publish (Sara)
- [x] Send live page to State Department for QA (Randi)
- [ ] Input any changes (Juliana)
- [ ] Review and publish
- [x] Create ticket for PW to add Spanish toggle
<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

## Acceptance Criteria
- [x] Page is live
- [x] Ticket created to add Spanish toggle

**Comment by RLHecht** [comment]
@ABeltran77 @strelichl Here is the content back from State. I know that we made changes to the English page so we may need to send new content out for translation before this page is ready. You may want to compare the two before building it out.



[LS-2024-0122945-SPA-FINAL_Board Appeals.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14376588/LS-2024-0122945-SPA-FINAL_Board.Appeals.docx)

**Comment by moviedosoco** [comment]
@RLHecht This is the prepped page with new content to send out for translation. 

[Board Appeals_mvo.docx](https://github.com/user-attachments/files/16395947/Board.Appeals_mvo.docx)

**Comment by RLHecht** [comment]
I sent this out for translation and marked it on the translation tracker.

**Comment by RLHecht** [comment]
@moviedosoco Here is the content back from State. This is ready to be built in Drupal. Thanks!

[LS-2024-0122945-SPA-FINAL_Board.Appeals New.docx](https://github.com/user-attachments/files/16599435/LS-2024-0122945-SPA-FINAL_Board.Appeals.New.docx)

**Comment by moviedosoco** [comment]
@RLHecht The page is built in Drupal. 

@saratorres2 The page 'Apelaciones ante la Junta' is ready to be reviewed and published:
https://preview-prod.vfs.va.gov/preview?nodeId=71556

Let me know if you have any questions. Thank you!

**Comment by RLHecht** [comment]
@juliana-jara This ticket is ready for you to review as well!

**Comment by juliana-jara** [comment]
Hi @RLHecht 
I found some issues with this page, mostly with the links. Several of them 403. There are also a couple periods missing, and the page needs the "On this page" Jump links. You can find more detailed information on the above [here](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Translation/Ticket%20%2375590/Review%20notes%20from%20Juliana%202025_04_21.docx?d=wc6b302800ccf442887833add62dd47fe&csf=1&web=1&e=crGLgA).

**Comment by juliana-jara** [comment]
@RLHecht Changes have been saved as draft.

**Comment by juliana-jara** [comment]
Hi @RLHecht this one is ready for you. Thanks!

**Comment by juliana-jara** [comment]
@RLHecht Just making sure you saw that this one has been updated and saved as draft.
Thanks!

**Comment by RLHecht** [comment]
I just published this page. Will send the live link to State for QA in a bit!

**Comment by RLHecht** [comment]
@juliana-jara Here is the content back from State. I think it's just that we shouldn't cap the H1, which in this instance we do because we cap Board Appeals in English throughout. 

[LS-2024-0125469 -LQA Notes-es_v1__Board Appeals page.docx](https://github.com/user-attachments/files/20349144/LS-2024-0125469.-LQA.Notes-es_v1__Board.Appeals.page.docx)

**Comment by juliana-jara** [comment]
@RLHecht They are right, prepositions are words that are not capitalized. In this case, because we are doing a translation of "Board Appeals", the translation needs a preposition that is not part of the name. It is the breadcrumbs that do need to be fixed to "Apelaciones ante la Junta". I have been poking around the CMS but I am not sure how to edit the breadcrumbs.

**Comment by juliana-jara** [comment]
@RLHecht They are right, prepositions are words that are not capitalized. In this case, because we are doing a translation of "Board Appeals", in this case, Apelaciones needs to be capitalized as it is the beginning of a sentence, than Junta also needs to be capitalized because it is part of the name of an organization. The translation needs a preposition that is not part of the name, so that is not capitalized. It is the breadcrumbs that do need to be fixed to "Apelaciones ante la Junta". I have been poking around the CMS but I am not sure how to edit the breadcrumbs.

**Comment by RLHecht** [comment]
thanks! Breadcrumbs are not something we can update and are automatically set. I do think it should show correctly when Public Websites sets up the left nav and the Spanish toggle but I'll put a note in that ticket to make sure they are aware.
