### ISSUE TITLE
[BE] Create Dashboard for Travel Claims App

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75599]
## Description
Create dashboard for the travel claims submission from Travel claims app for OH appointments

## Tasks
- [ ] [BE] **Create Dashboard**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75599?planning-poker) with Zenhub @kanchanasuriya @randomsync @lee-delarm6

**Comment by loripusey** [comment]
@kanchanasuriya We need to talk about this ticket, can you please set up a meeting with @benbrasso-agile6 myself and @brianseek

**Comment by kanchanasuriya** [comment]
I just sent an invite @loripusey, please let me know if that time is convenient for everyone to meet.

**Comment by loripusey** [comment]
Putting this back in the backlog, unless we are at a point where we can complete this work now, then let's not have it lingering in the sprint

**Comment by lee-delarm6** [comment]
Kay asked about this, so it's still on

**Comment by lee-delarm6** [comment]
Wait will OH is finished integrating before starting this ticket

**Comment by lee-delarm6** [comment]
https://dsva.slack.com/archives/C08HW046W6B/p174250460866593
