### ISSUE TITLE
GA4: Appointments Team - Custom Events (Validation)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#75593]
### Description
We have the list of custom events we will need to start mapping out for the Appointments Team (VAOS). This task is to set up the tracking for these events within GA4.

- **Custom Events:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/%5Bdraft%5Dvaos-analytics-definitions.md

Note that testing of GA4 events will need to be done with assistance from the Appointments Team 

### Tasks
- [ ]  Follow-up with Jeff Roof (and team) to review mapping
- [ ]  Add each component event to GTM
- [ ]  Follow-up with Jeff Roof (and team) to complete testing/preview GTM implementation
---

### Acceptance Criteria
- [ ]  Events have been added to GTM and published for lower environments (dev + staging)
- [ ]  Events have been added to GTM and published for production environment
- [ ]  Events have been confirmed in GA4

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt, could you help build out the tasks and AC fro this card when you have some downtime? Tried to get this started with a basic description.

**Comment by johnny-jesensky-adhoc** [comment]
Due to the dependency built within this ticket -- we are moving this to the _**On Deck/In Review**_ column. We will pull this into a sprint once we have confirmed we are able to validate with the Appointments Teams.

FYI @jestutt
