### ISSUE TITLE
Create Updated DOMO Dashboard

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#75605]
## Issue Description
_As a DOMO user, I need a dashboard that reflects the metrics of incoming Salesforce and AskVA cases, so I can clearly determine the volume of incoming cases and determine there are enough resources to manage the volume. 

---
## Tasks
- [ ] Identify case categories for tracking for Tier II, Tier III, Tier III EVSS 
- [ ] Create a grid displaying the number of daily incoming cases 
- [ ] Create a grid displaying the number of currently open cases 
- [ ] Create a grid displaying the number of daily closed cases
- [ ] Create a grid displaying the number of backlog cases
- [ ] Create a grid displaying the number of routed cases 
- [ ] Create a grid displaying the number of T3 EVSS cases 
- [ ] Create a grid displaying the number of T3 cases 
- [ ] Create a grid displaying the number of T2 cases
- [ ] Create a grid displaying Total AskVA cases 
- [ ] Create a grid displaying total AskVA daily incoming cases 
- [ ]  Create a grid displaying the number of currently open AskVA cases 
- [ ] Create a grid displaying the number of daily closed AskVA cases
- [ ] Create a grid displaying the number of backlog AskVA cases
- [ ] Create a grid displaying the number of routed AskVA cases 
- [ ] Determine that AskVA cases can be exported from Micorsoft Dynamics to a csv file
- [ ] Determine AskVA data reports can be automated for export to csv file 
- [ ] 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario 1: Identify case categories for tracking for II, Tier III, Tier III EVSS**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see the case categories for Tier II, Tier III, and Tier III EVSS displayed

- [ ] **Scenario 2: Create a grid displaying the number of daily incoming cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of daily incoming cases

- [ ] **Scenario 3: Create a grid displaying the number of currently open cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of currently open cases

- [ ] **Scenario 4: Create a grid displaying the number of daily closed cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of daily closed cases

- [ ] **Scenario 5: Create a grid displaying the number of backlog cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of backlog cases

- [ ] **Scenario 6: Create a grid displaying the number of routed cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of routed cases

- [ ] **Scenario 7: Create a grid displaying the number of T3 EVSS cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of T3 EVSS cases

- [ ] **Scenario 8: Create a grid displaying the number of T3 cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of T3 cases

- [ ] **Scenario 9: Create a grid displaying the number of T2 cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of T2 cases

- [ ] **Scenario 10: Create a grid displaying Total AskVA cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the total number of AskVA cases

- [ ] **Scenario 11: Create a grid displaying total AskVA daily incoming cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the total number of daily incoming AskVA cases

- [ ] **Scenario 12: Create a grid displaying the number of currently open AskVA cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of currently open AskVA cases

- [ ] **Scenario 13: Create a grid displaying the number of daily closed AskVA cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of daily closed AskVA cases

- [ ] **Scenario 14: Create a grid displaying the number of backlog AskVA cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of backlog AskVA cases

- [ ] **Scenario 15: Create a grid displaying the number of routed AskVA cases**
  - Given that I am a DOMO user
  - When I access the dashboard
  - Then I should see a grid displaying the number of routed AskVA cases

- [ ] **Scenario 16: Determine that AskVA cases can be exported from Microsoft Dynamics to a csv file**
  - Given that I am a DOMO user
  - When I attempt to export AskVA cases from Microsoft Dynamics
  - Then I should be able to export them to a csv file

- [ ] **Scenario 17: Determine AskVA data reports can be automated for export to csv file**
  - Given that I am a DOMO user
  - When I attempt to automate AskVA data reports for export to csv file
  - Then the reports should be successfully exported to a csv file

**Comment by ATMiddleton** [comment]
Closed and combined with #75604
