### ISSUE TITLE
Update MPI Page re: Mention of Grafana, Loki and Prometheus

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75600]
## Issue Description
[This page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847049/MVI) requires additional discovery in order to update regarding mention of Grafana, Loki, or Prometheus.

---
## Tasks
- [x] Perform discovery to determine how to update this page
- [x] Update page according to determination
- [x] Change it from MPI to MVI but also mention that it used to be called MVI or ""Master Veteran Index"
- [x] Delete the Monitoring section and both links beneath it.
- [x] Add a note under both Integration Endpoints and Trust Chains saying “You must have access to the internal VA network to access all the links below.”
- [x] Wait for Trevow Bosaw, Joe Niquette, and Mike King to write an update to the escalation process or the entire page
- [x] Figure out if the contacts history should be there.

## Acceptance Criteria
- [x] Page has been updated to reflect sunsetting of Grafana, Loki and Prometheus and redirect to Datadog documentation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Identity Team working on this page in current sprint

**Comment by jknipes** [comment]
All tasks completed, page deployed, moving to _Done_
