### ISSUE TITLE
Update EVSS Page re: Mention of Grafana, Loki and Prometheus

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75602]
## Issue Description
[This page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240213/EVSS) requires additional discovery in order to update regarding mention of Grafana, Loki, or Prometheus.

---
## Tasks
- [x] Perform discovery to determine how to update this page
- [x] Update page according to determination
- [x] Update the page with regards to changes involving Lighthouse, not just Grafana, Loki or Prometheus

## Acceptance Criteria
- [x] Page has been updated to reflect sunsetting of Grafana, Loki and Prometheus and redirect to Datadog documentation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@laucon please add your estimate to this ticket

**Comment by BSmolensky** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75602?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
Closing ticket and moving to _done_
