### ISSUE TITLE
Disaster Alert on the Debt Portal Overview page

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#75615]
## Issue Description
A Disaster Alert was placed on the Debt Portal Overview page some time ago by the Debt Management Center. Tracking discussions as to whether this alert is still needed or can it be removed. 

---
## Tasks
- [ ] @denisecoveyduc to discuss with the DMC and update the ticket with future information and next steps. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@josephrlee Could you drop a screenshot of this Disaster Alert here. Both expanded and not. (still figuring out Figma) Thank you!

**Comment by josephrlee** [comment]
@denisecoveyduc, here ya go!

![staging va gov_manage-va-debt_summary (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/42052ecd-9b6f-46e9-94a8-92c0058cfb94)
![staging va gov_manage-va-debt_summary (3)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/a51fb720-db63-463b-a422-3a6c2ed20aec)

**Comment by denisecoveyduc** [comment]
Perfect! Thanks @josephrlee I appreciate that!

2/8 update - reached out to DMC to discuss removing this Disaster Alert from the debt portal.

**Comment by denisecoveyduc** [comment]
As of 3/6/2025 there are no next steps for this issue.
