### ISSUE TITLE
Research and Scope Product Directory Work

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#75610]
## Description 
We are looking to create a comprehensive product directory which could be housed in the Atlas App or another tool. This ticket will house the research for identifying the best way to go about this. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify existing Product Directories
- [ ] Sync up with Erin to identify best way to represent the information 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
This directory is being worked on by several parties including the VA. Closing until further notice.
