### ISSUE TITLE
Create a Call Center Product Guide 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7561]
## Background
All applications on the Veteran-facing Services Platform include a phone number Veterans can call to ask questions about the application's functionality.

Before applications (or new features) launch on the Veteran-facing Services Platform, all teams must file a Contact Center Review issue that includes a Product Guide and Product Video. The VSP Contact Center team will review these materials and share with the relevant contact centers to ensure that Contact Center Representatives are prepared to answer questions about the new functionality.

## Timing
When the complete and final build is on staging and they are confident it's ready to launch
At least 2 weeks prior to the launch date for a new feature in an existing service

## Example Product/Call Center Guides
[Example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md#prepare-for-contact-center-review)

[Address validation call center guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/address-validation/Address%20validation%20call%20center%20guide.docx)
[Direct deposit call center guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/Direct%20Deposit%20Call%20Center%20Guide.docx)

## Tasks
- [x] Create a new folder in your team's Product folder called Contact Center. Store the Product Guide there.
- [x] Create plan/outline.
- [x] Review outline with team (Matt/Tressa/Samara).
- [x] Determine who is writing which sections.
- [x] Write first draft.
- [x] Edits and reviews.
- [x] Once copy is final, gather screenshots.
- [x] Submit final draft to Chante for feedback/edits.
- [x] Make updates.
- [x] Submit final copy.

## Acceptance Criteria
- [x] Product Guide has been created 
- [x] Product Guide has been added to teams folder on GitHub

**Comment by Samara-Strauss** [comment]
I know this isn't part of this sprint, but I'm getting some rough notes down of how I think this should be organized:

- Profile intro
- Personal and contact information
  - How to edit/update
  - Address validation (**Note**: We can probably include most of the existing guide and just update images, but we'll need to confirm that all copy is indeed still accurate and update accordingly)
  - Common errors
- Military information
  - Short overview of this section
  - Common errors
- Direct deposit (**Note**: We can probably include most of the existing guide and just update images, but we'll need to confirm that all copy is indeed still accurate and update accordingly)
  - How to edit/update
  - Common errors
- Account settings
  - How-to on each feature/Show different states
- Connected Apps
  - What it is
  - How to disconnect an app

**Comment by mshea0606** [comment]
@Samara-Strauss ok great!

**Comment by mshea0606** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Call%20Center

**Comment by mshea0606** [comment]
[Product Guide Outline](https://docs.google.com/document/d/18ohdH6QHgDNmtqshlkJYfYphqcHlo305rc-hQj-3Bc0/edit?ts=5ef355b0)

**Comment by mshea0606** [comment]
[Product Guide](https://docs.google.com/document/d/1XNHpYOP73so_bnnEjplx_zG_ybGarGenG2V0E6-N-CA/edit)

**Comment by mshea0606** [comment]
[Product Guide Format](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md)

**Comment by mshea0606** [comment]
[Slack convo re formatting] https://dsva.slack.com/archives/C909ZG2BB/p1593542213326500

**Comment by mshea0606** [comment]
[Product Guide - VA Profile.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4992139/Product.Guide.-.VA.Profile.docx)

**Comment by mshea0606** [comment]
[Product Guide - VA Profile.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4992171/Product.Guide.-.VA.Profile.docx)

**Comment by Samara-Strauss** [comment]
I reopened this because I left a few final comments on things. Some of the images need to be replaced, and I suggested deleting a few as well.

Also, I cropped and resized some images. 

- Mostly, I cropped images that were significantly longer than necessary, where the additional content lower on a page didn't provide meaningful context (eg. additional sections that weren't the focal point of the illustration; the footer).
- I did crop the top of some images, but only in cases where we were showing the breadcrumbs without the header. This was not being applied consistently — some images started at the name tag, others included the breadcrumbs. Since the breadcrumbs didn't provide meaningful context in most cases, I tool them out *only* when the header was not shown above. If the image included the full header, I did not crop the top of the image.

Let me know if you have questions. I'll take one final pass once the updates are made. Then, please attach this **as a PDF** to the contact center review request.

**Comment by Samara-Strauss** [comment]
Great work on this, y'all! I know this was a huge task, and you both rose to the occasion. Nice job!!
