### ISSUE TITLE
Update 7 Pages Mentioning Grafana, Loki, Prometheus

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75620]
## Issue Description
All Grafana tools are being sunset on Monday, 1/29/24.
This ticket relates to 8 documents relating to Prometheus will need to be updated. 
---
## Tasks
- [x]  Update 7 pages (Google Sheet lines 24, 25,27, 29, 31-34)
- [x]  Check for LB issues, notify person on deploy day
- [x]  delete info boxes when complete

## Acceptance Criteria
- [x] 7 Pages Updated

## Relevant Links:
[Google Sheet](https://docs.google.com/spreadsheets/d/1XzUOf1qbd6fYaDwXBTDDgFL7Qjfnpafi6BA4NyFnm8I/edit?usp=sharing)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
