### ISSUE TITLE
Create Product Video

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7562]
## Background
All applications on the Veteran-facing Services Platform include a phone number Veterans can call to ask questions about the application's functionality.

Before applications (or new features) launch on the Veteran-facing Services Platform, all teams must file a Contact Center Review issue that includes a Product Guide and Product Video. The VSP Contact Center team will review these materials and share with the relevant contact centers to ensure that Contact Center Representatives are prepared to answer questions about the new functionality.

## Timing
When the complete and final build is on staging and they are confident it's ready to launch
At least 2 weeks prior to the launch date for a new feature in an existing service

## Product Video Info
[Info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md#prepare-for-contact-center-review)

## Tasks
- [ ] Create a Product Video (with audio) that steps through the primary user flows.
- [ ] Create a transcript of the audio from the Product Video. The transcript must be a Word document or a PDF.

## Acceptance Criteria
- [ ] Product Video has been created 
- [ ] Product Video audio transcript has been added to teams folder on GitHub
