### ISSUE TITLE
Implement new flow of when DST issues are found at VFS Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75629]
## User Story
As a Governance team member, I want to implement the new flow of notifying DST of component issues at SR so that DST can be notified more efficiently and issues can be addressed quickly.

Assignee: @allison0034 
Peer Reviewer: @rferguson13 

## Description
In ticket #73845, Governance team documented the current flow of how DST is made aware of when design system component issues are found at Staging Review. Within that same ticket, Governance team also proposed a new flow that will ideally allow DST to made aware of the potential issue sooner, and removes some of the responsibility from the VFS team.

In this ticket, we will update the Staging Review guidance and documentation to reflect this change in flow. Since this change is being made mid-[pilot ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73800), all changes to guidance should be made to the documentation drafts (if applicable). Please connect with @erinrwhite to ensure the correct docs are updated.

After the docs are updated and all changes are made, Governance will sync with Design System team to demo the new process. 

*For any changes to the DraftingTemplate, please coordinate with @shiragoodman .

## Impacted Artifacts
[How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)
[Drafting template](https://drive.google.com/drive/u/0/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud)

## Tasks
- [x] Review the guidance to determine where changes need to be made. Add all impacted docs to Impacted Artifacts section above.
- [x] Update the DraftingTemplate
- [x] Once peer reviewed and approved, contact Carol on #platform-design-system Slack channel to schedule demo
- [x] For demo, include sample tickets 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have implemented a new process for informing DST of potential component issues found at Staging Review
- [x] Design System team has a defined process for reviewing potential component issues found at the Governance Staging Review

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at ~~Weekly Initiative Meeting~~ Demo with DST
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Status update: Started on this late in the sprint, not a ton of progress so far. Will carry into the next sprint and hopefully knock out by the end of the week.

**Comment by allison0034** [comment]
Created draft of [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3006038017/73845+-+Allison+-+How+to+document+findings+for+Staging+Review)

**Comment by allison0034** [comment]
Created draft of [drafting template](https://docs.google.com/spreadsheets/d/1y1el2FABpXFNbUFPwuGsHxSc8juT3jY1RH2wZIgIR7I/edit#gid=727681601).

**Comment by erinrwhite** [comment]
@allison0034 Looking good! One thing missing is that the new labels not showing up in the "labels" column on the generated tickets in the GH Upload tab. `Design system review: Yes` is showing up in the body of the ticket, though, which is useful.

**Showing up in body of ticket:**
<img width="311" alt="Screenshot 2024-03-07 at 1 35 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/b6a3cd00-2702-4759-86fe-a8d2f6da411e">

**Missing in list of labels:**
<img width="447" alt="Screenshot 2024-03-07 at 1 35 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/f9a2f0ef-c59d-48f5-8189-344f778b7a6b">

**Comment by shiragoodman** [comment]
@allison0034 let me know if you'd like me to address the issue @erinrwhite raised above.

**Comment by allison0034** [comment]
I am looking at it now tring to figure it out myself before I bug you!

**Comment by allison0034** [comment]
@erinrwhite I think I did it!

**Comment by allison0034** [comment]
@erinrwhite you can also check that the ticket ownership has been updated:
Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.

**Comment by allison0034** [comment]
@erinrwhite draft of of [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3006038017/73845+-+Allison+-+How+to+document+findings+for+Staging+Review) is ready for your review. I only added 1 line under Reviewer responsibilities during meeting. I made it similar to "out of scope work".

**Comment by erinrwhite** [comment]
@allison0034 The drafting template and the How to Document Findings page are both looking good!

**Comment by allison0034** [comment]
@erinrwhite I have replaced the drafting template and updated the how to doc. Do you want to peek at the live stuff and check the peer review complete box?

**Comment by erinrwhite** [comment]
@allison0034 All looking good! I have checked the peer review boxes. Last step is to demo with Carol then good to close!
