### ISSUE TITLE
Explore opportunities for component code checks at Staging Review 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75627]
## User Story
As a Governance team member, I want to verify that VFS teams are using the component code in Storybook and not writing their own code so that the VFS team can be informed of the issue at Staging Review and they can make the fix.

As a Governance team member, I want to define a process for how our team might be able to easily identify if/when a component is hand coded so that we can repeat the process consistently across all Staging Reviews.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
Governance team has seen VFS teams "hand code" Design System components into their products at the Collab Cycle Staging Reviews. What this means is that instead of copying the code from Storybook to use in their product, they're re-writing the code to make it appear as the same component. 

This is problematic because:

1. If changes are made to the component by DST, the hand-coded component in production will not be automatically updated. Also not in sync which created UX problems, which creates maintenance problems, can lead to bugs.
2. Component usage data across VA.gov is skewed

Governance team currently has a [VA Web components Bookmarklet ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2848391252/Highlight+VA+Web+Components+Bookmarklet)tool that allows us to see in Staging environment and in Production what components are being used within a page. The tool will highlight the component in a red dashed outline to indicate that this is a Design System component. See example below.
<img width="714" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a297e26eada896c1d72290fcdabad14a837dfe9/image.png" alt="image.png" />

### Questions to ask ourselves

- How might we build off this tool and/or modify this tool to help us identify when a product appears to be using the component but is not actually using the component? 
- How might we implement this process into our Collaboration Cycle Staging Review so that if/when this occurs, Governance team is able to consistently apply the appropriate Experience Standard? 
- What category and experience standard is this issue violating?
   -Shira's 2 cents: possibly a _Consistency_ category where _User encounters design components that are inconsistent or confusing._
   - Up to you to decide what category/issue makes the most sense
- How do we handle it if/when a VFS team shared, "the DS component is not an option for us because..."?
   - provided justification and provide plan for keeping up with updates to the inspo-component
- Is this something we want to measure within our QA standards?
- Can this process be supported by 1 Governance team member or should all be responsible?
- Can or should we introduce this check earlier in the process? Possibly at Midpoint Review?
   - what components are they planning on using? what are they not planning on using? for example, I want an accordion but not the accordion component
- If/when we do identify this issue and apply the Experience Standard at Staging Review, how should we classify the severity? (Question for you @humancompanion-usds  - should this always be launch-blocking or should we handle on a case-by-case basis?)
   - Per Matt on 2/12, not default launch-blocking. Need to tell the team what the risks are so they do prioritize the fix. Would like to handle on a case-by-case basis depending on maturity-level of the component.
   - Need to include V1 vs. v3 into the process as well. 

The purpose of this ticket is to propose how Governance can address the above problem. If there are multiple options, then propose multiple solutions. Governance team will decide as a team which solution is the most desirable and the solution will be implemented within another ticket.

## Impacted Artifacts
N/A

## Tasks
- [ ] Document proposal in the Confluence Governance/Ideas space for how we can implement this solution consistently at Staging Review
- [ ] Identify what artifacts may be impacted by the implementation of this process
- [ ] Answer the above questions

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have proposed a solution for implementing component code checks at Staging Review

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@briandeconinck draft is [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2983329825/Discovery+opportunities+for+component+code+checks+at+Staging+Review+-+75627)

**Comment by briandeconinck** [comment]
@it-harrison Left two comments that are maybe outside the scope of this ticket! Otherwise this looks great, I think you're good to close it out.

**Comment by shiragoodman** [comment]
I agree. Also looks good. If @humancompanion-usds has comments or concerns, we can address them in the implementation ticket - #76895.
