### ISSUE TITLE
Change deployment time of vets-api

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#75633]
### Summary
Vets-website deploy time is changing on May 1 and so we need to change vets-api to be at the same time for PROD and SANDBOX.

### Tasks
- [x] In the vps-infra-argocd repo's [chart.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml), search for the `sync_windows` section and update the `allow` to be 1pm ET ('0 13 * * 1-5')  for prod and sandbox.
- [x] Timing for the merge should be before 1pm (1300 hrs) eastern May 1
- [x] [Puma Backlog monitor](https://vagov.ddog-gov.com/monitors/116657) is muted every day at the daily deploy time. Change this to line up with the new time. You can [edit that in the Datadog UI here](https://vagov.ddog-gov.com/monitors/downtimes?q=creator%3A%22Kyle%20Matheny%22&id=7cab24d2-82fa-11ee-a5b1-da7ad0900007&sort=-start_dt).
- [x] Edit the **Vets API deploy check** workflow in DSVA Slack to trigger at 30 min prior to the new deploy time. All BE CoP members have the perms to edit this workflow.
- [x] Update Confluence [deploy doc](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1844641889/Deployments) and [friends](https://depo-platform-documentation.scrollhelp.site/search.html?l=&max=10&ol=&q=3pm&s=&start=0)

**Comment by rmtolmach** [comment]
This is delayed until further notice.

**Comment by rmtolmach** [comment]
Passing on to @JoeTice and team to manage. Thanks!

**Comment by ericboehs** [comment]
PR Merged.

Confluence pages updated:
- [Onboarding - Developer docs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240280/Onboarding)
- [Deployments - Developer docs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1844641889/Deployments)
- [Sync Windows Design Documentation - Platform Product Team](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2895806878/Sync+Windows+Design+Documentation)
- [Feature toggles guide - Developer docs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Feature+toggles+guide)
- [Console Services (Backend) - Support](https://vfs.atlassian.net/wiki/spaces/SUP/pages/2153906177/Console+Services+Backend)
- [Slack Channels for Platform Support - Platform Tech Support Team](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2510195011/Slack+Channels+for+Platform+Support)
- [Handling Deployment Failures - Platform Tech Support Team](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2583461932/Handling+Deployment+Failures)

**Comment by ericboehs** [comment]
Deploy went out at 1pm ET today!
