### ISSUE TITLE
Discovery: Investigate Leaked GC Service Account

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#75630]
### Description
This ticket is to determine the next steps for resolving the issue of a GoogleCloud service account that was leaked back in 2018. There has been an outstanding task to rotate those credentials, but there has not been any movement or success on that front. This is a priority for our ATO process, so this discovery ticket is being prioritized to bring a resolution, or definitive next steps to that ask.

**Background & Context**
- **Related Ticket:** https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/411
- **leaked cred ID:** vetsdotgovanaltyics@peerless-return-191720.iam.gserviceaccount.com
- **associated project/account ID:** `peerless-return-191720`
- **client_id":** "104454792282666945360"

<img width="779" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1e16c0677c93fc63eb071c9f008e156ba9e4bdf/image.png" alt="image.png" />

Context from Dave (2/8):

>  "_A little hot off the presses here: I'm sending you over an email with some context but the TL/DR is that we need to have a Spike done on the Google Cloud/Analytics accounts and access. We'll need to prioritize this work because it has implications on Platform's ATO work. Can you look into this a bit and begin to frame out a ticket. We'll probably need to figure out how to pull this into next sprint. Let me know if we need to find some time to discuss this in more detail._"

---
### Tasks

- [x] Understand full context and current state of Google Cloud leaked credentials as of February 2024.
- [x] If possible, connect with Michelle Dooley to learn the latest on past action taken by the Analytics & Insights Team.
**-  Determine the following information, or have a next step to find it**
- [ ] Where this (leaked) service account creds live or determine who the admins are - UNKNOWN
- [x] Document findings from ticket at the bottom of this card - Findings provided in bottom of the ticket. Additional information will be shared in PO sync on March 5. 
- [x] Create, another ticket as a follow-up to this, to action 

### Acceptance Criteria
- [x] Next steps, or recommended actions have been documented in this ticket, in the **Spike Findings/Next **Steps** section.
- [ ] Timeline of a potential resolution has been identified. - TIMELINE Unknown
---
### Spike Findings / Next Steps
Performed some initial discovery on this ticket which included the following:
- Connected with Michelle to determine the latest actions from the Analytics & Insights Team
- Connected with Kelly, and performed initial review of her ATO items.
- Reviewed history of ticket in the [related ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/411), to understand where this work was left off, and what roadblocks were encountered.

**Located resources to look into including the following:**
- [GCP Account and Resource Recovery Request
](https://support.google.com/cloud/contact/cloud_platform_access_recovery)
- [Deleting Keys](https://cloud.google.com/iam/docs/keys-create-delete#deleting )
- [Policy Troubleshooter](https://console.cloud.google.com/iam-admin/troubleshooter

**Resources Identified To Meet With**
- Connect with Kyle Matheny, to determine past progress he's made on contacting Google.
- If possible, connect with Karl Brown to confirm understanding and history behind this.

**Next Step**
- [ ] Refine, and then pull this new ticket ([Next Steps on Rotated GCP Account](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/77285)) into an upcoming sprint, which was created in backlog to work through some of these items/next steps identified in this spike.

**Comment by karlbrown-va** [comment]
Hi I just came across this as I was checking notes on the old ticket. IMO the biggest challenge is to somehow get google to help you contact the admins for the google cloud account where this particular credential lives. I think someone (Kyle?) tried in the past but didn't have much luck but maybe if you go higher up the chain at Google via ECSO contacts you will find someone who could help? AFAIK with Michelle we were able to remove all permissions from this credential to extant VA cloud analytics properties.

**Comment by johnny-jesensky-adhoc** [comment]
@karlbrown-va - Thanks for the additional information here. I've been tasked with figuring out how to fully resolve the `peerless-return-191720` GC account, so the extra context is helpful. I'll connect with Kyle Matheny to see just how far along he got in that process.

Do you know if anyone has formally submitted a [GCP Account and Resource Recovery Request](https://support.google.com/cloud/contact/cloud_platform_access_recovery) on this?

Additionally, given the long history with this ticket, (and the fact that I've mostly just gotten my information from the comments in the related ticket, along with a conversation with Michelle), I might look to schedule a very quick (~5-10min) call with you to confirm my understanding of this, if you would be open to it - let me know. Thanks.

**Comment by karlbrown-va** [comment]
Sure happy to chat. You can ping me on DSVA slack to coordinate a time. 

I do not know if anyone submitted a recovery ticket. I think people asked around and tried to find people who might remember or know who would have access to that 'peerless' account but no luck.

I do know that I tested the creds (You can do so with command line, I think I posted how to in the previous ticket) The creds still work, but I'm not able to determine if they give access to anything at all. I was able to test that they dont work for VA GA any more.

You might consider moving this whole ticket to sensitive repo
