### ISSUE TITLE
Create Oracle Health cancellation feature flag

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#75638]
## Issue Description
Create a VA online scheduling (vaos) backend feature flag for integrating new capability to route appointment cancellations for Oracle Health sites
[Feature flag documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

---
## Tasks
- [x] Create backend feature flag

## Acceptance Criteria
- [ ] Feature flag has been deployed to Staging environment
- [ ] Feature flag is visible in Flipper on Staging (https://staging-api.va.gov/flipper/features)
