### ISSUE TITLE
Roll new EKS nodes in Dev

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#75631]
### Description
EKS nodes are behaving strangely and need to be re-rolled to resolve the issue

---

### Tasks
- [x] Look into current behavior, verify that re-rolling is a valid solution
- [x] Re-roll EKS nodes in Dev

### Acceptance Criteria
- [x] EKS nodes are re-rolled and functioning as expected
