### ISSUE TITLE
Update appointment PUT requests to use VPG

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#75639]
## Issue Description
Update the appointments PUT request workflow to send requests to VetsAPI Patient Gateway (VPG) instead of vaos-service to enable support for updates at Oracle Health sites.

---
## Tasks
- [x] Update appointment controller to send requests to VPG

## Acceptance Criteria
- [x] Appointment updates are processed by VPG
- [ ] Changes have been deployed to staging

**Comment by anita-halici** [comment]
@simiadebowale this is the follow-up story that belongs to the appt cancellations [Apps OH Integration] Backend support for Oracle Health appointment cancellations - please have your team to review the code and let us know if this can be merged. cc @JRRoof

**Comment by anita-halici** [comment]
@JRRoof @simiadebowale any updates?

**Comment by simiadebowale** [comment]
@anita-halici - One of our BE engineers will review this today.

**Comment by anita-halici** [comment]
thanks! cc @devin-mccurdy
