### ISSUE TITLE
vets-api & vets-website: remove/replace **veteran status** eMIS

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#75657]
### Summary
This ticket came out of #72200. Removing the veteran status code has proved to be complex since changes also need to be made in vets-website at the same time.  

### Tasks
- [x] Prepare code changes in vets-api ✅ https://github.com/department-of-veterans-affairs/vets-api/pull/15393
- [x] Prepare code changes in vets-website 
- [x] Test locally by spinning up vets-api and vets-website locally and making sure login works (with joe's test user 5)

### Acceptance criteria
- [x] All references to eMIS veteran status in vets-api are gone and replaced, if needed. Corresponding changes in vets-website are also changed.

**Comment by rmtolmach** [comment]
- vets-api PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15393
- vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/27851

To do:
- [ ] re-record mock responses in vets-website.

**Comment by rmtolmach** [comment]
All tests are passing in both PRs 🎉 

**Note: vets-website PR needs to deploy before vets-api PR**

I am in the process of getting reviews for my vets-website PR.

**Comment by rmtolmach** [comment]
The PRs are in good shape. The only failing test in my vets-website PR is one that's failing on `main`. The FE CoP is working to resolve that, but in the meantime, I will close this ticket and I opened https://github.com/department-of-veterans-affairs/va.gov-team/issues/76033 to cover the rest.
