### ISSUE TITLE
Update Stats D page re: Prometheus and Grafana

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75650]
## Issue Description
Update [this page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847017/StatsD+Metrics) to reflect recent sunsetting of Prometheus and Grafana tools, update any links, and redirect users to appropriate tool(s), ie. Datadog.

---
## Tasks
- [x] Backend SME Reviews [page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847017/StatsD+Metrics)   
- [x] Content Team Update page and links as advised
- [ ] Confirm update with Clint Little

## Acceptance Criteria
- [ ] Page updated and ready for deployment on Platform Website 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
cc: @ericboehs

**Comment by jknipes** [comment]
Gia Antoniades provided guidance to update this document and we can close this ticket. Moving to _Done_
