### ISSUE TITLE
Place Info Box at Top of Pages re: Grafana, Loki, Prometheus

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75652]
## Issue Description
As temporary measure to updating pages, Team will place info box at top of 30 pages that reference monitoring tools.
---
## Tasks
- [x] 10 pages Lauren Thurs
- [x] 10 pages Fri Brian
- [x] 10 pages Jill Tues

## Acceptance Criteria
- [ ] Pages updated to show sunsetting of tools, redirect to Datadog
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Language for Info Box [HERE](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2946334869/TEMPLATE+FOR+GRAFANA+LOKI+PROMETHEUS+Pages)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75652?planning-poker) with Zenhub @BSmolensky @laucon @taylojill
