### ISSUE TITLE
Update Environments Page re: Mention of Grafana/Loki/Prometheus

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75674]
## Issue Description
Monitoring tools Grafana/Loki/Prometheus have been sunsetted on January 29th, 2024. 
Therefore, [This page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/603488279/Environments) in the Environments space of Platform Website requires editing in Multiple Sections. 
Grafana is mentioned 7 times on the page, in 4 sections.

---
## Tasks
- [x] Locate SME related to this page
- [x] Determine how to update the text 
- [x] Update page

## Acceptance Criteria
- [x] Tasks completed
- [x] Page has been updated
- [x] Deployed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75674?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
All tasks complete. Page updated and deployed. Ticket is good to close.
