### ISSUE TITLE
Value verses effort Prioritization 

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#75682]
## Task Description
Using the pain points discussed with the team, define the the most significant problems of the current state 

## Notes and References
-

## Acceptance Criteria
- [x] Slide deck with problem statements, why it is a problem, what value it would give the user if solved and a HMW statement.
- [x] Get feedback on draft
- [x] Schedule Prioritization matrix activity

## Deliverables
- Slide deck with problem statements, why it is a problem, what value it would give the user if solved and a HMW statement.
- Prioritization matrix activity
