### ISSUE TITLE
Design | Profile | Enhanced Military Info | Combine mocks

### ISSUE THREAD

**Issue by pamela-drouin** [department-of-veterans-affairs/va.gov-team#75694]
## Background
We need to update the Military Information mockup with enhanced military information with the Veteran Status Card mocks to make the mock as realistic as possible. 

## Tasks
- [x] Combine Figma files ([our current one](https://www.figma.com/file/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?type=design&node-id=0-180&mode=design) + [the UI content to be added](https://www.figma.com/file/UwSvhj9Yn5trM5L5W3UgH0/VA-Status---Wireframes?type=design&node-id=1046-214&mode=design&t=mBwzmNu5IYbTL8FV-0))
- [x] Update #73363 & #74208 to account for the UI addition
- [ ] Review w/ UX and PM

## Acceptance Criteria
- [ ] Ready for use in #74186

**Comment by pamela-drouin** [comment]
@mtcA6 will you add the relevant metadata that I missed? I will add the two Figma links 😄

**Comment by pamela-drouin** [comment]
Mocks (collapsed/expanded) are [in Figma](https://www.figma.com/file/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?type=design&node-id=10-6355&mode=design)

**Comment by pamela-drouin** [comment]
@mtcA6 @Samara-Strauss @andaleliz everything's been updated! Any last feedback before I close this?

**Comment by pamela-drouin** [comment]
@mtcA6 you did respond Friday -- thank you so much!

**Comment by mtcA6** [comment]
Oh weird, it must have been a stale page on my end!!!! I was going through my open tabs from Friday and I definitely didn't have a my message there, now I know to refresh.

**Comment by Samara-Strauss** [comment]
Not sure how I missed this -- looks great!
