### ISSUE TITLE
Schedule Call Center Review

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7569]
## Background
All applications on the Veteran-facing Services Platform include a phone number Veterans can call to ask questions about the application's functionality.

Before applications (or new features) launch on the Veteran-facing Services Platform, all teams must file a Contact Center Review issue that includes a Product Guide and Product Video. The VSP Contact Center team will review these materials and share with the relevant contact centers to ensure that Contact Center Representatives are prepared to answer questions about the new functionality.

## Timing
When the complete and final build is on staging and they are confident it's ready to launch
At least 2 weeks prior to the launch date for a new feature in an existing service

## Information
[Info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md#prepare-for-contact-center-review)

## Tasks
- [ ] follow process listed [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md) to create a ticket.
- [ ] make any requested changes if needed
- [ ] VSP team will close ticket once complete

## Acceptance Criteria
- [ ] Call center review has been requested
- [ ] Any requested changes have been made
- [ ] Call center review has been completed and ticket closed
