### ISSUE TITLE
[FE] Create e2e test scenarios

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#75708]
## Description
Create a list of e2e tests to test for all user scenarios expected within the travel only flow.

## Tasks
- [ ] Create user stories for every scenario to be used as titles for the end to end tests
- [ ] Add details to the ticket for creating the E2E tests.
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Ticket has been updated with list of tests to create

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75708?planning-poker) with Zenhub @brianseek @lee-delarm6

**Comment by wullaski** [comment]
Here's some error scenarios we could write tests for:

- I am a patient who has already filed for a claim today and have no other facilities to file a claim for
- I am a patient who has attempted and failed to validate more than 3 times
- I am a patient who has used a link with a UUID not found
- I am a patient who has encountered an error submitting a travel claim
- I am a patient who has answered no to travel vehicle
- I am a patient who has answered no to travel address
- I am a patient who encounters an error retrieving travel claim data
- I am a patient who attempts to access the app during a maintenance window

**Comment by brianseek** [comment]
Lets add:
- I am a patient who attempts to proceed from review page without checking the box to confirm
- I am a patient who attempts to click continue from facility selection without checking at least one facility
- I am a patient who decides to change an answer an uses the back button from the review page
- I am a patient who decides to change facility selection an uses the back to last screen link from the vehicle page
- I am a patient who clicks edit from the review page to change an answer or selection

@wullaski go ahead and add this full list to the e2e ticket. Review if you think it all fits in that ticket, if not add another ticket(s) to split it up. Then feel free to close this ticket when the work ticket(s) are good to go.

**Comment by wullaski** [comment]
We could also add what Lee has been working on:
- I am a patient who views the travel agreement page and goes back to complete filing a claim

**Comment by brianseek** [comment]
oh yeah, good call!
