### ISSUE TITLE
[FE] - Fetch appointment data with mocks

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#75706]
## Description

Create hook to fetch appointment data from new vets-api endpoint(TBD). Create mocks for local development.

Use same endpoint as day-of check-in, pass facilityType = OH as a param

Example payload:

```
{
      appointmentIEN: '1111',
      clinicFriendlyName: 'Endoscopy',
      clinicPhoneNumber: '555-555-5555',
      facility: 'Example Veterans/' Hospital',
      facilityAddress: {
        street1: "12345 Main St",
        street2: "Suite 100",
        street3: "Box #3",
        city: "Washington",
        state: "DC",
        zip: "20002"
      },
      stationNo: '530',      
      clinicCreditStopCodeName: '',
      clinicIen: '32216049',
      clinicLocation: '',
      clinicName: 'Endoscopy',
      clinicStopCodeName: 'Mental Health',
      doctorName: 'Dr. Smith',
      edipi: '22222',
      icn: '33333',
      kind: 'clinic',
      startTime: '2020-01-23T22:10:00.000+00:00',
      status: '2020-01-23T23:10:00.000+00:00',
}
```
Consider if we need a new reload wrapper
## Tasks
- [x] Create mocks using example payload
- [x] Create data fetching hook
- [x] Store data in Redux
- [x] Create UUID and modify mocks to show multiple appointments from multiple facilities
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [x] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75706?planning-poker) with Zenhub @wullaski @brianseek

**Comment by wullaski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75706?planning-poker) with Zenhub @lee-delarm6

**Comment by brianseek** [comment]
verified existing apps on stage after this re-work. Moving to closed
