### ISSUE TITLE
Portal Overall FE/BE Logic Shift and Code Cleanup

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#75716]
## Description
When the Portal was initially built the team consisted of all Front-end Developers, and as a result the logic was contained 100% in the Front-end code base. 

This initiative will be to decouple the Logic of the entire application so that the Front-end is a presentation layer only and the Logic/Calculations/Data will be contained in the Back-end code base that the Front-end can consume and display, but not manipulate.

There will be **3** epics contained under this Super Epic container.

**[1. Portal Overall FE/BE Logic Shift - Tech Discovery](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75729)**
This work will consist of discovery only.

**[2. Portal Overall FE/BE Logic Shift](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75735)**
This work will be the implementation of the discovery work in the first Epic.

**[3. Portal Overall Post Logic Shift Code Cleanup](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75740)**
This work will be the removal of the now obsolete Front-end logic code and any other cleanup related to this Logic transition.

## Definition of done

- [x] All Epics have completed their individual Definition of done criteria.
- [x] Documentation has been added to the individual Epics noting the work.
- [x] Testing has been completed and passed.
- [x] All tickets contained in the Epics and the Epics themselves under the Super Epic are closed.
- [x] The updates have been released to production.

## Scope of work:

- Discovery of every Calculation and or data point that is to be taken out of the Front-end code and moved to the Back-end.
- All logic that is related to data and calculations currently managed by the Front-end being migrated to the Back-end.
- Cleanup of the old logic that is no longer needed.

## Out of Scope:

Newly identified work that comes out of any research or enhancement opportunities. All that should still be collected and placed under the "New Ideas" tab in the [Planning/Priority document](https://docs.google.com/spreadsheets/d/1PjpLz_ywN7-Rx3CpQvvkJy_UADNv8gOc/edit#gid=907339630).

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

**Comment by Tom-Davis** [comment]
Closing as all work is complete and the release stages are being tracked in the quarterly release epic.
