### ISSUE TITLE
[FE] Create E2E tests

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#75711]
## Description
Create end to end tests for user flows through the travel only app.

## Tasks
- [ ] TBD
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75711?planning-poker) with Zenhub @brianseek @lee-delarm6

**Comment by brianseek** [comment]
I voted but lets hold off official pointing until we know the scope of the tests
