### ISSUE TITLE
[FE] Create method of checking if patient already filed and new page

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#75717]
## User Story
As a veteran, I do not want to be able to file a duplicate claim for the day.

When fetching appointment data check against what is stored in local storage. If there is a unique facility id for that day allow the veteran to file a claim for that facility by continuing through the app. Otherwise route them to an error message.

## Wireframes
- [Wireframes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=96-709&mode=design&t=ou29sgcCrc49kfAn-0)

![Screenshot 2024-02-08 at 3 45 11 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/d0114ca1-7aff-4650-8004-f7d6c63c0f0d)

## Tasks
- [ ] Create a method that takes the appointment payload and checks it against what is in local storage to see if there is a possibility to file a claim for that day.
- [ ] Create new page for already filed claims
- [ ] Route the user based on whether or not they can file a claim
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75717?planning-poker) with Zenhub @brianseek @lee-delarm6

**Comment by brianseek** [comment]
nothing to visually validate in this one with the page content moving to the error ticket. Moving to closed.
