### ISSUE TITLE
[CST] Show users without a participant ID an error message

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#75720]
### Background
We should show users that do not have a Participant ID some sort of message indicating to them that they do not have a Participant ID in MPI and that if they feel that this is in error they should reach out to the Call Center to get the issue sorted out.

### Context
The main requirements for users to be able to make successful calls to Lighthouse Benefits Claims are:
1) They must have an ICN
2) They must have a Participant ID

We have not seen issues with the first requirement, but we have received reports of users who have created claims, but are unable to view any of their claims in CST.

### Open Questions
If the user doesn't have a participant ID then we don't even allow them to access the claim status tool. Will we need to make changes to the frontend code so that we can determine when to show them a message?

### Tasks
- [ ] Determine what the message should looks like and what it's content should be
- [ ] Update the frontend code to allow us to determine when a user does not have a participant ID
- [ ] Update the frontend code to show a message when the user does not have a participant ID

### Acceptance Criteria
- [ ] We are showing a message to users who do not have a Participant ID that indicates to them that they should call the Call Center to get the issue sorted out

**Comment by jacobworrell** [comment]
@jerekshoe is this ticket still relevant?

**Comment by pmclaren19** [comment]
reviewed in eng refinement
