### ISSUE TITLE
Document Process to Reroll EKS Nodes

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#75727]
## Description
Earlier this week, there was a need to reroll EKS nodes, it would be beneficial to document this process, as well as some guidelines on when this process should be used.

## Tasks
- [ ] Write a version of the instructions
- [ ] Have a team member walk through and provide feedback
- [ ] Update as needed and move doc to the appropriate location

## Acceptance Criteria
- [ ] Document is written and reviewed
- [ ] Document is posted to the appropriate location

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/pso-documentation/blob/ba-75727/aws/instance-refresh.md
