### ISSUE TITLE
[UX] 10-10EZ OOUX Object Map

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#75725]
## Issue Description
As a Veteran, I want to easily submit an application for health care where the information (data) I provide is simple and streamlined into getting me placed into the VA health care benefits best for my situation.

- Utilize the OOUX methodology to create an object map for the 10-10EZ that helps document how the data of basic information, eligibility and prioritization placement work in the health care application process.

---
## Tasks
- [x] Working session to complete process and document via [Mural board here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707349991102/3fe097a1e3e00ff31c67e6f5b16e8432370bbac7?sender=uadf1ed7fe7c76f0914967329)
- [x] Invite UX and EZ team members to join in on working session
- [x] Document object map to use in other initiatives

## Acceptance Criteria
- [x] A Object Map for the EZ in the Mural source of truth folder
---

**Comment by hdjustice** [comment]
@katelyncai - Since you are working a bit on this, do you have a thought on estimating points for it?

**Comment by katelyncai** [comment]
> @katelyncai - Since you are working a bit on this, do you have a thought on estimating points for it?

I would give this a 5.

**Comment by hdjustice** [comment]
Consensus reached, 5 it is.  Thank you @katelyncai !

**Comment by katelyncai** [comment]
We've completed our OOUX workshops (mini ORCA process) for EZ and drafted an object map on [this MURAL board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707349991102/3fe097a1e3e00ff31c67e6f5b16e8432370bbac7?sender=ube02cc3d1108083a94f75471). Will discuss with @jessicastump the best path forward for keeping that documentation up to date and accessible.
