### ISSUE TITLE
[BE] Update Travel Claims Service Class to handle OH appointments

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#75728]
## Description
Modify travel claims service class to handle OH appointments vs vista appointments for sending appropriate patient identifier to BTSSS

## Tasks
- [ ] [BE] **Modify patient_icn method to read redis for appointment type & get the patient identifier**
- [ ] [BE] **Modify submit_claims method to send both appointment type & patient identifer to client interface**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@kanchanasuriya there was a note in the sprint goals that we no longer need this ticket; I'm closing it but if the note was incorrect please let me know
