### ISSUE TITLE
[FE] Error page scenarios and content

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#75722]
## User Story
As a veteran, I want to be presented with proper error messaging so that I know what went wrong.

## Wireframes
- [Wireframes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=96-709&mode=design&t=ou29sgcCrc49kfAn-0) 

## Tasks
- [x] Make sure errors are handled properly and with the correct wording according to the wireframes
- [x] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75722?planning-poker) with Zenhub @brianseek @lee-delarm6
