### ISSUE TITLE
Ask VFS teams to clarify scope boundaries and share where they'd like feedback

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75730]
## User Story
_As a Governance team member, I want VFS teams to communicate prior to the DI meeting the boundaries and scope of their product so that I am only providing feedback for areas they are able to control._

_As a Governance team member, I want VFS teams to communicate prior to the DI meeting the areas where they'd like additional feedback, or dedicated support so that I am able to focus my attention in those areas._

_As a Governance team member, I want VFS teams to share as much as they can prior to the DI meeting so that the time allotted for the DI meeting can be used wisely to discuss feedback._

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
In the Service Design research study, VFS teams shared that they received feedback on areas that are out of scope for the current feature and this sometimes can cause confusion for them.

> Feedback: Received feedback on more things than required/noted

The Governance team initial solution included adding clarity to our feedback guidance stating how VFS teams should be handling out of scope feedback. At the Governance Refinement meeting on 2/22, the team recognized that instead of communicating how VFS teams should handle out of scope feedback, maybe we need to address instead how VFS teams should be communicating the boundaries of their product/feature.

This issue came up again at the Midpoint Review on 2/23. The VFS teams spent 10+ minutes reviewing their changes, going one by one until it became too difficult for us to keep track of everything. This meeting would've gone much smoother had we asked for the VFS team to share ahead of time where they'd like specific feedback. [See Slack thread.](https://dsva.slack.com/archives/GNF5GSD9N/p1708707581169329)

The purpose of this ticket is to add 2 questions/requests to the Design Intent section of the CC Request ticket:
1. Please share the scope and/or boundaries of your feature.
2. Please share any areas you would like Governance to focus on within our review.

^These questions should be wordsmith'd and additional clarity should be added (if applicable).

## Impacted Artifacts
DI code block in [Collab Cycle Kickoff - Moderator Responsibilities ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[DI touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)

## Tasks
- [x] Before making any changes to the above impacted artifacts, first determine how these changes might be made.
   - These aren't artifacts, and typically artifacts have been the only thing we've asked for at a Design Intent.
   - Where and how would it make the most sense to include these 2 questions?
   - Are they required questions or should they only be answered by the VFS if applicable?
   - Does it make sense to include this information on the DI touchpoint page too?  Or is it overkill?
- [x] Once you've determined a solution, make the changes to the code block and the DI touchpoint page (if applicable).

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have given VFS teams the opportunity to clarify scope prior to the DI meeting.
- [x] We have given VFS teams the opportunity to share where they'd like us to focus prior to the DI meeting.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@allison0034 I made some changes to the [Design Intent page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2940698630/77282+-+Design+Intent+page); you can see my edits in purple. 

As for the GitHub ticket, here's what I was thinking:
- What is the scope and/or boundary of your product?
- Are there any areas you'd like the Governance Team to focus on in their review?

**Comment by allison0034** [comment]
@rferguson13 DI page looks great!

As far as the GH ticket, we know from user testing that the ticket is very overwhelming so I do not think we should add too much.

**Currently we have this...**

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far

**Instead maybe we try this...**

Required:
- User flow
  - [ ] Review all pages
  - [ ] I have specified which pages to review

Not required, but nice to have:
- Wireframes
  - [ ] Review all pages
  - [ ] I have specified which pages to review

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far

**Comment by allison0034** [comment]
One more idea, this would put the ownership on the VFS team for sure...

Required:
- [ ] User flow (**all pages are reviewed unless otherwise specified**) 

Not required, but nice to have:
- [ ] Wireframes (**all pages are reviewed unless otherwise specified**)

**Comment by rferguson13** [comment]
@allison0034 - I like the second one because it's clearer, but I wonder if teams will get tripped up because they won't know where to specify. Am I overthinking this?

**Comment by allison0034** [comment]
@rferguson13 each team is different, I don't think it is up to us to tell them where, if they prefer Figma fine, or maybe they want to use the Mural or this GH ticket. I think it is a personal choice.

**Comment by rferguson13** [comment]
@allison0034 Then I think the second option works best. We can always tweak it if need be.

@shiragoodman - What do you think? If you're good with it, then let's get it live.

**Comment by shiragoodman** [comment]
I like the 2nd option too, however it doesn't cover the question, "Are there any areas you'd like the Governance Team to focus on in their review?"

**Comment by shiragoodman** [comment]
I like that! @allison0034 what do you think?

**Comment by allison0034** [comment]
@rferguson13 I like it!

**Comment by rferguson13** [comment]
@allison0034 - [Updated this page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) with the above language. Can you take a look?
