### ISSUE TITLE
Portal Overall FE/BE Logic Shift

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#75735]
## Description
When the Portal was initially built the team consisted of all Front-end Developers, and as a result the logic was contained 100% in the Front-end code base. 

This initiative will be to decouple the Logic of the entire application so that the Front-end is a presentation layer only and the Logic/Calculations/Data will be contained in the Back-end code base that the Front-end can consume and display, but not manipulate.

This is Epic **2** of **3** needed to complete the work.

**[1. Portal Overall FE/BE Logic Shift - Tech Discovery](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75729)**
This work will consist of discovery only.

**2. Portal Overall FE/BE Logic Shift**
This work will be the implementation of the discovery work in the first Epic.

**[3. Portal Overall Post Logic Shift Code Cleanup](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75740)**
This work will be the removal of the now obsolete Front-end logic code and any other cleanup related to this Logic transition.

## Definition of done

- [x] All areas of logic identified in Epic 1/3 have been deactivated or commented out of the Front-end code.
- [x] All areas of logic identified in Epic 1/3 and deactivated in the task above have been created in the Back-end code.
- [x] Documentation related to the code to be removed in Epic 3/3 has been added or linked to this Epic.
- [x] Creation of new E2E tests.
- [x] Testing has been completed on the new Back-end code to ensure all data is presented exactly as it was prior to the Logic Shift.
- [x] Testing has been completed in relation to any calculations related to the Logic Shift.
- [x] Testing has been completed in relation to any downstream consumption related to the data contained in the Logic Shift.
- [x] Any Downstream systems have been notified that work has been done and while there are no expected changes that we ask for validation of that (to be attached to a ticket covering this request.
- [x] All tickets contained in this Epic are closed.
- [x] Any new opportunities identified in the Discovery work are placed under the "New Ideas" tab in the [Planning/Priority document](https://docs.google.com/spreadsheets/d/1PjpLz_ywN7-Rx3CpQvvkJy_UADNv8gOc/edit#gid=907339630).

## Scope of work:

- Migration of every Calculation and or data point that is to be taken out of the Front-end code and moved to the Back-end.

## Out of Scope:

- Planning any migration of code not related to the Logic shift (Identification is OK, but to be logged as noted below).
- Newly identified work that comes out of any research or enhancement opportunities. All that should still be collected and placed under the "New Ideas" tab in the [Planning/Priority document](https://docs.google.com/spreadsheets/d/1PjpLz_ywN7-Rx3CpQvvkJy_UADNv8gOc/edit#gid=907339630).

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

**Comment by Tom-Davis** [comment]
Closing as all work under this Epic is complete.

BE/FE please ensure the testing under the cleanup Epic 75740 includes downstream impacted groups to ensure a seamless upgrade - Thank you for all the hard work!

@kjsuarez @maxx1128 @digitaldrk @Dr-Pongo @OptionSelect @amponce
