### ISSUE TITLE
[FE] Store facility and datetime in local storage

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#75734]
## Description

When a travel claim is successfully submitted store the facility and time of the selected appointment. This is automatically selected if there is only one appointment or one facility. It is selected by the patient when there is more than one facility or appointment.

## Application flow

Get appointment data

When there is only one appointment or one facility we can set the "selected" appointment in redux.

If there is more than one facility the UI will change to make the user select a facility or appointment for filing the claim.

On a successful submission to BTSSS the selected appointment's facility and datetime will be stored in local storage.

If the user uses the same link to return to the app that day and attempt to file another claim the app will look over the payload and check if there is a unique facility to file a claim for.

Question: Does it need to be a specific appointment or can we use the first appointment for a facility?

## Tasks
- [ ] Use the useStorage hook during the POST to submit the claim to store the facility and datetime of the selected appointment
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75734?planning-poker) with Zenhub @brianseek @lee-delarm6

**Comment by lee-delarm6** [comment]
Facility = `stationNo`
time = `startTime`

**Comment by brianseek** [comment]
this work will happen in the hook
