### ISSUE TITLE
[CHIP] - High Severity security alert for lodash

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75743]
## Description
There is a high severity dependabot alert for CHIP. This seems related to dd-trace which is on v2. v2 is past EOL, we should look into updating dd-trace to v4 which supports our node version (v16)

While we are doing this we should also review and resolve the PRs from dependabot

## References
- [Alert](https://github.com/department-of-veterans-affairs/chip/security/dependabot/65)
- [dd-trace](https://www.npmjs.com/package/dd-trace)

## Tasks
- [x] Update dd-trace
- [x] migrate code using dd-trace as needed
- [x] confirm alert is resolved after push
- [x] review dependabot PRs and merge/resolve
- [ ] release to prod
- [x] Create or update unit tests
- [x] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75743?planning-poker) with Zenhub @brianseek @lee-delarm6 @wullaski

**Comment by brianseek** [comment]
This fix has been merged and the security alert closed itself after. This library update will be in the next CHIP release. This ticket can be closed before the end of the sprint. Leaving here since there is an on-going discussion about soe config.

**Comment by brianseek** [comment]
this is all sorted out...closing
