### ISSUE TITLE
Portal Overall Post Logic Shift Code Cleanup

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#75740]
## Description
When the Portal was initially built the team consisted of all Front-end Developers, and as a result the logic was contained 100% in the Front-end code base. 

This initiative will be to decouple the Logic of the entire application so that the Front-end is a presentation layer only and the Logic/Calculations/Data will be contained in the Back-end code base that the Front-end can consume and display, but not manipulate.

This is Epic **3** of **3** needed to complete the work.

**[1. Portal Overall FE/BE Logic Shift - Tech Discovery](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75729)**
This work will consist of discovery only.

**[2. Portal Overall FE/BE Logic Shift](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75735)**
This work will be the implementation of the discovery work in the first Epic.

**3. Portal Overall Post Logic Shift Code Cleanup**
This work will be the removal of the now obsolete Front-end logic code and any other cleanup related to this Logic transition.

## Definition of done

- [ ] All areas of logic identified in Epic 1/3 and moved to the Back-end in Epic 2/3 have been removed from the Front-end code.
- [ ] Removal of unnecessary E2E tests.
- [ ] Testing has been completed to ensure all the code that was Shifted continues to function soly relying on the Back-End.
- [ ] Testing has been completed in relation to any downstream consumption related to the data contained in the Logic Shift soly relying on the Back-End.
- [ ] All tickets contained in this Epic are closed.
- [ ] Any new opportunities identified in the Discovery work are placed under the "New Ideas" tab in the [Planning/Priority document](https://docs.google.com/spreadsheets/d/1PjpLz_ywN7-Rx3CpQvvkJy_UADNv8gOc/edit#gid=907339630).

## Scope of work:

- No longer relevant & now redundant code to be taken out of the Front-end code base.

## Out of Scope:

- Removal or altering any code not related to the Logic shift (Identification is OK, but to be logged as noted below).
- Newly identified work that comes out of any research or enhancement opportunities. All that should still be collected and placed under the "New Ideas" tab in the [Planning/Priority document](https://docs.google.com/spreadsheets/d/1PjpLz_ywN7-Rx3CpQvvkJy_UADNv8gOc/edit#gid=907339630).

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

**Comment by Tom-Davis** [comment]
Closing as all development work is complete
