### ISSUE TITLE
Product Success Tool - Prototype a data model for performance metrics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#7574]
## High Level User Story
How might we model where the different platform related data is sourced from so that VSP can understand who owns which metrics for roadmapping and how the data will be cut for visualization to end users (DEPO & VSP leadership).

## Hypothesis/(es)
**If** _we data model the performance metrics that have tooling being created_ **then** _we expect to understand who owns what and how all of the teams can create a cohesive vision to execute a performance dashboard_.

## Pain Points
- Platform Prioritized: info about how success is measured for VSP overall and for VSP initiatives is hard to find and/or non-existent.
- Platform Prioritized: VSP doesn’t regularly share updates on overall VSP metrics or initiative metics.cc
- Insights Feeback: Feedback on previous performance dashboards was positive, but usage was low. May have been audience

## Desired Outcomes
- If VFS teams get an error, it’s super hard to know if it's because of a bug, a trait about that user that has changed, or a system being down. How might we understand when teams have errors and where they are coming from so that we can triage and correct appropriately?
- Info about how success is measured for VSP overall and for VSP initiatives is hard to find and/or non-existent. How might we better understand how to track VSP success?
- VSP doesn’t regularly share updates on overall VSP metrics or initiative metics. How might we more easily share updates on VSP success?

## Goals
Conduct a design sprint to quickly test a data model so that there is a cohesive vision on VSP work distribution.

### Links
[Design Sprint Pre-Sprint Mural Board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1585071843990/7692b180df76ddab405155c072ed11615ab611d4)

### Product Outline
Platform Metrics Product Outline TBA
[Product Success Tool Product Outline](https://docs.google.com/document/d/1GuuhRXT8-NjEHdFHysNg1VA1o89Qr0_Mkrg46Q8kBeI/edit#)
[Product Success Tool Product Brief](https://docs.google.com/presentation/d/1sI32UbQRqpKqOhBT8lkUuOHgfD4UUkV2cd5Pzw1fP9w/edit#slide=id.g5ce1b6f7f4_0_19)

### VSP Objectives
`O4: All of the Platform's KPIs are easily measured and shared openly.`

### VSP Key Results
- KR1: At least 2 KPIs tracked by each VSP team (14 total).
- KR2: It takes < 1 hour to compile KPI reports
- KR3: KPI reporting is worked into sprint workflow

## KPIs
- Number of recurring users

**How we will track the KPIs** : Domo

## Definition of Done
- [ ] VSP has a refined roadmap
- [ ] Data model is created
- [ ] Outline for a Platform Dashboard is created

## We will know we're done when
- [ ] VSP teams have an aligned roadmap for performance metrics
- [ ] The design sprint readout is available to all VFS teams

**Comment by joanneesteban** [comment]
[Artifacts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/analytics-dashboard/design-sprint-24-2020)

This work will be continued with V1 of the Performance Dashboards.
