### ISSUE TITLE
Document pages that include PHI/PII

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#75744]
## Task Description

Document any pages where the app displays PHI/PII to the Veteran. This will be used when implementing DataDog RUM analytics to avoid accidentally capturing PHI/PII from production.

PHI/PII includes:
- Name
- Veteran email address
- Any free text field the Veteran could fill out (they may put SSNs in these)
- Veteran phone number

## Acceptance Criteria
- [x] Documented list of masking criteria including:
     - [x] Links to the relevant feature doc
     - [x] Short explanation of where exposure may occur

## Deliverables
[-  Spreadsheet (WIP)](https://docs.google.com/spreadsheets/d/15ZWRXU01XeO9Nao4RZbQUjRVmzevMXmagaldFMqmi-0/edit#gid=0)

**Comment by outerpress** [comment]
@simiadebowale @JRRoof what PII/PHI should we look for/document for DataDog? Here's what I'm thinking so far:
* Name
* Veteran email address
* Any free text field the Veteran could fill out (they may put SSNs in these)
* Veteran phone number
* ? what else

@ldelacosta what Feature should I add this to?

**Comment by outerpress** [comment]
Test comment

**Comment by ldelacosta** [comment]
@outerpress - I have added this ticket to [Feature] DataDog Implementation #63374. Let me know if you need anything else. Thanks!

**Comment by JRRoof** [comment]
@outerpress - Would it be possible to just mask numbers in the free text field?  Our are we worried about all content in these fields?

**Comment by outerpress** [comment]
@JRRoof probably the whole field since a Veteran could type their name or email address in there too.

But it also depends on what level of PII/PHI we want to scrub for. I think PII is more important - name, contact information, home address, ID#'s etc, since without those the PHI can't be connected to a specific person.

What do you think we should scrub?

**Comment by JRRoof** [comment]
@outerpress - Agreed, best thing to do is exclude the entire text fields.

**Comment by outerpress** [comment]
@JRRoof @ldelacosta @simiadebowale [first pass of fields to mask](https://docs.google.com/spreadsheets/d/15ZWRXU01XeO9Nao4RZbQUjRVmzevMXmagaldFMqmi-0/edit#gid=0).

**Comment by outerpress** [comment]
@ldelacosta @simiadebowale handing this off to y'all, feel free to close when you're done with it :)

**Comment by ldelacosta** [comment]
I'm going to close it and reference it in our working ticket. Thanks!
