### ISSUE TITLE
[FE] - Modify footer component to work with travel-claim app

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75749]
## Description
The footer component has some subtle changes needed for the travel-claim app. The scope of this ticket is to update the component to be able to display the content we need for travel-claim while also still working for the other apps.

## Wireframes
- [Wireframes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-4579&mode=design&t=4ej9QsaUUc2X59vr-0)

## Tasks
- [x] Make needed changes to footer component
- [x] implement footer into travel-app 
- [x] do a visual regression test to make sure other apps are not effected by changes
- [x] Create or update unit tests
- [x] Create or update e2e tests
- [x] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [x] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75749?planning-poker) with Zenhub @brianseek @lee-delarm6 @wullaski

**Comment by benbrasso-agile6** [comment]
Footer looks good
