### ISSUE TITLE
[FE] - Create travel intro page

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75745]
## Description
Create the new intro page for the travel claim app. This page utilizes the `va-process-list`, `va-process-list-item`, and `va-featured-content` components. Create the component in the shared components directory and the page wrapper in the travel directory. Also setup page in the router if not already there.

## Wireframes
- [Wireframes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=642-3804&mode=design&t=XEveKExW34rRJ9Z6-0)

## Tasks
- [x] Create component
- [x] Create wrapper
- [x] Add to routes
- [x] run axe scan on page
- [x] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75745?planning-poker) with Zenhub @brianseek @lee-delarm6 @wullaski

**Comment by brianseek** [comment]
@benbrasso-agile6 @cgednalske @zach-park This intro page is ready for validation. See screenshots below. Note the internal padding of the `va-process-list` is slightly different than what you have shown in Figma, resulting in a bit of an extra squeeze on text here. This is at 320px

<img width="165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef955e98bcebb0484fd59703b677cfe8af3d46ee/into-closed.jpg" alt="into-closed.jpg" />
<img width="100" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ac103233280bd9d832103b6914c70e05253c8d9/intro-open.jpg" alt="intro-open.jpg" />

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
@brianseek we added some [a11y markup to the Intro page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=642-3804&mode=design&t=EVBA4QKYniwwya0A-4) as a result of [a11y midpoint feedback](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/77000). 

Did you want to hit this in this sprint? Or wait until next sprint?

**Comment by brianseek** [comment]
lets add it to a new ticket and we can decide to pull it in later if we have capacity

**Comment by benbrasso-agile6** [comment]
Np, it's assigned to Lee for next sprint
