### ISSUE TITLE
[FE] - Create travel-claim success page

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75751]
## Description 
Create the new success page for the travel-claim app. Add the page component to the router.

## Wireframes
- [Wireframes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=599-2148&mode=design&t=Slvr48iRlKItEvZZ-0) 

## Tasks
- [ ] Create new page
- [ ] Add page to router
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75751?planning-poker) with Zenhub @brianseek @lee-delarm6 @wullaski

**Comment by wullaski** [comment]
@benbrasso-agile6 for validation here are screenshots of it locally. It will only show multiple facility scenario when you run locally.
![Screenshot 2024-02-28 at 12 27 06 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/a4f541dc-8260-4d9a-9402-a82ab02f5206)
![Screenshot 2024-02-28 at 12 25 12 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/feaa2f1a-41ea-4330-8afc-75549bfcce81)

**Comment by wullaski** [comment]
I noticed that "Claim[s] Submitted" is title case. This has already been merged but we can sneak a fix in on a later ticket.

**Comment by benbrasso-agile6** [comment]
I think @lee-delarm6 is working on Need Help content, but just noting here that the Need Help content isn't correct. Again, if Lee is handling that, that's totally fine. Just wanted to make sure.

**Comment by benbrasso-agile6** [comment]
Is the second screenshot for the scenario where someone selects more than 1 checkbox? If so, "claims" should be plural in the h1.

**Comment by wullaski** [comment]
Thanks @benbrasso-agile6! I'll create a ticket for those fixes.
