### ISSUE TITLE
[FSR] Checkbox and Checkbox group refactor to v3 web components

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#75752]
## Description

The current [CheckList.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/85229172d4c1295580a47738082bbdabeadb34a1/src/applications/financial-status-report/components/shared/CheckList.jsx) needs to be refactored to use the [USWDS Checkbox Group](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default) component. 

Checkbox instances

- [debt selection](https://github.com/department-of-veterans-affairs/vets-website/blob/99cc7eb2fc36c08d5bd20abec2ad05ced37a966f/src/applications/financial-status-report/components/debtsAndCopays/DebtCheckBox.jsx) 
- [copay selection](https://github.com/department-of-veterans-affairs/vets-website/blob/e66872a4d24eb0b552ac55ad4aa7400172fcd933/src/applications/financial-status-report/components/debtsAndCopays/CopayCheckBox.jsx)
- [Waiver agreement](https://github.com/department-of-veterans-affairs/vets-website/blob/27771f8adecbfb4b50c016b5039cd9c568cbd2a3/src/applications/financial-status-report/components/resolution/ResolutionWaiverAgreement.jsx#L70)

Scenario: In common language describe the work or issue

## Tasks
- [ ] Task one to complete the work in the description
- [ ] Task two to complete the work in the description
- [ ] Task three to complete the work in the description
- [ ] Verify the H3 content highlighting works for screen readers

## Acceptance criteria

- [ ] Item one from the description performs as described in the description
- [ ] Item two from the description performs as described in the description
- [ ] Changes are accessible 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
Here's my initial stab at creating a checkbox refactoring ticket (wanted to make sure this got documented and not just living in my headspace). I tried to find the main places where the custom checkbox component is referenced.

It definitely needs to be refined more (tasks, acceptance criteria, and testing bits still need to be added and estimated). 

cc: @Dr-Pongo @amponce @OptionSelect

**Comment by amponce** [comment]
The checkbox group refactor [PR ](https://github.com/department-of-veterans-affairs/vets-website/pull/30338)is up. I ended up breaking it into smaller parts.
In this PR, I focused on refactoring the shared checklist and I'll address the three specific checkbox instances

- debt selection,
- copay selection,
-  waiver agreement

in a separate PR to keep things more manageable. I had to update quite a bit more than expected in my current PR so adding those other sections seemed like a bad idea.

Note:
The new component has a fixed width that's super annoying, I think Joe is going to follow up with a css hack for now.

There's a separate issue opened for the design system team to address the widths
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2508 (
