### ISSUE TITLE
[FE] - Create travel submission hook for travel-claim app

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75754]
## Description
Create a new hook to handle our travel-claim submission. This hook should be able to borrow stuff from the travel hook in day-of check-in. As part of this work, also create the success and error response mocks.

This hook should do the following:
 - POST to the travel-claim endpoint in vets-api
 - Set the station and timestamp to localStorage
 - Mark the station submission as complete in context to facilitate reloading on the complete page
 - Handle error setting from the API

## Tasks
- [ ] See above
- [ ] Create mocks for success and error
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/75754?planning-poker) with Zenhub @brianseek @lee-delarm6 @wullaski

**Comment by brianseek** [comment]
content changes were validated in the travel-mileage ticket, no further UX validation needed, moving to closed
