### ISSUE TITLE
Reassigning Tickets to Reflect Correctly in Looker Dashboard

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#75789]
## Description 
At the moment, we have not consistently reassigned tickets to their respective CoP (i.e. Frontend, backend, frontend). As a result our Looker Dashboard metrics are a bit off, showing most tickets being assigned to Tier 1. Since this is not accurate, we will need to manually and retroactively update these metrics to ensure they reflect the truth of our team responsibilities. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

Each person will reassign tickets in the #vfs-platform-support ticket to the appropriate party. Each person will reassign one month of tickets from December 1st until now. They will be broken out by:

- [x] Anthony (December Tickets)
- [x] David (January Tickets)
- [x] Lindsay (February Tickets)
- [x] Brandon (March Tickets)
- [x] Brenden (April Tickets)
--- 

## Resources & Additional Info 
See attached Slack convo for additional context.<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53a937732a891fee026801c2f226b66de2d00686/Screenshot%202024-02-09%20at%201.21.00%20PM.png" alt="Screenshot 2024-02-09 at 1.21.00 PM.png" />

---

**Comment by alyssagallion** [comment]
@AnthonyWFlowers @lindsay-insco @bdech @bmatos312 @davidpetras Heads up that you are reassigning these in Slack!<img width="883" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fadf9d1678883800157d3f8005f1ab344a3cf2a6/Screenshot%202024-04-30%20at%2011.33.33%20AM.png" alt="Screenshot 2024-04-30 at 11.33.33 AM.png" />

**Comment by alyssagallion** [comment]
Project complete. Closing.
