### ISSUE TITLE
[Research] VA.gov Onboarding: Research Review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#75797]
## Background
To begin our work to create a solution for first time onboarding to va.gov we need to do a first round of research/discovery.

## Tasks
- [x] Review any past research conducted by other teams in this area within VA
- [x] Consult with the mobile team to see what they've learned or have done to solve for this on the app
- [x] Consult with health modernization teams (VHA Enrollment System, MHV cartography team?) to see what work they have done in this area (there work would understandably be specific to health care onboarding, but likely to find some helpful information there as well)

## Acceptance Criteria
- [x] Have an initial "lay of the land" in terms of existing research/knowledge at VA

**Comment by andaleliz** [comment]
@ajakabcin is it OK with you if we move the first task to a separate ticket? Happy to create it but just want to be able to scope things accordingly. I think the comparative analysis will be a 5, and this will be a 5 (without that task).

**Comment by ajakabcin** [comment]
definitely ok with me! I'll spin that up @andaleliz

**Comment by andaleliz** [comment]
Dropping a note here, [this insight from the mobile team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/post-launch-discovery/July%202023/Mobile%20App%20Retention/Research%20Findings.md#additional-insights) is an interesting angle to think about transitions veterans go through and the role digital tools can play in that.

**Comment by andaleliz** [comment]
Update: I've reviewed all the docs Samara provided, and got screenshots from the mobile team showing what they do for onboarding (which they feel leaves a lot to be desired, and said that their analytics show engagement with that they're doing for onboarding is very low).  Our [research repo has 19 studies](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues?q=is%3Aissue+label%3A%22VETJNY%3A+Getting+out+Military%22) with labels suggesting this could be relevant to our work so I'm going to look through those next.

**Comment by andaleliz** [comment]
@ajakabcin I was able to finish this up, and I think it's good to go. Looking at the AC for this ticket, I'm not sure this was really required BUT I felt it would a really helpful reference for our team moving forward. 

Once you take a look, lmk what you think and then we can share w/ Samara.  I'd be glad to review this with the team in our kick off too, so everyone is on the same page.

**Comment by andaleliz** [comment]
@ajakabcin have you had a chance to look this over yet? Curious if you have any feedback/edits before we send it to Samara. I think we'll need to carry this over to the next sprint since she hasn't seen it yet.

**Comment by ajakabcin** [comment]
hey @andaleliz no I'm sorry I haven't yet but agree we should carry to next sprint

**Comment by andaleliz** [comment]
@ajakabcin I'd love to get this closed out - when you have a chance to review, will you lmk? I think at this point Chante should be the one to give a final review before it can be closed. Do you agree?

**Comment by mattmarino-adhoc** [comment]
Hey @andaleliz, mind if we do a quick overview of your findings with the team in the near future? (Doesn't have to be this sprint)

**Comment by andaleliz** [comment]
Hi @mattmarino-adhoc! I'd be glad to. I was hoping to do that when we do the team kickoff so everyone is on the same page. AJ and I are going to regroup with Chante and Samara tomorrow to align on next steps.

**Comment by mattmarino-adhoc** [comment]
Awesome! Sounds great.

**Comment by andaleliz** [comment]
@Samara-Strauss and @clantosswett, [here's a link to the report we reviewed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/research-review.md) on our call today. Please let me know if you have any questions or want more details about anything!
