### ISSUE TITLE
Draft Script for Video To Be Embedded on Custom Survey Intake Form 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#75808]
## Issue Description
As a VSF team completing the Custom Survey Intake form I need a video describing the differences between the two survey options (Feedback button or intercept survey) and will aid in determining which survey will best suit the needs of my VFS product team.

---
## Tasks
- [x] _Create script
- [x] Create video and link
- [x] Determine placement of video link on form

## Acceptance Criteria

- [x] **Scenario: Create script  - Given the VSF team is completing the Custom Survey Intake form
  - When they need a video describing the differences between the two survey options (Feedback button or intercept survey)
  - Then a script should be created for the video

- [x] **Scenario: Create video and link**
  - Given the script for the video has been created
  - When a video is created based on the script
  - And a link to the video is generated
  - Then the video and link should be created

- [x] **Scenario: Determine placement of video link on form**
  - Given the video and link have been created
  - When determining the placement of the video link on the Custom Survey Intake form
  - Then the appropriate placement for the video link should be determined

**Comment by UXCamG** [comment]
[Script](https://docs.google.com/document/d/1PxIxmYRBaLexaQC-GQVIxulXDR6MTzxC0PRkqhpd-kE/edit?usp=sharing)

[Video placement](https://www.youtube.com/@platformcrew4065/videos)

**Comment by ATMiddleton** [comment]
Team review and then we can close ticket.

**Comment by starlow00** [comment]
Video sent to team for review, have received feedback.
