### ISSUE TITLE
[Epic] Implement Document Upload Polling Solution

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#75804]
## Acceptance Criteria
- [X] Add new LighthouseDocumentUpload model, migration and validations
- [X] Build service object to parse Lighthouse Status response
- [x] Build Update service for wrapping interaction with Lighthouse API, parsing service (started)
- [X] Hook into existing Lighthouse Benefits Document API client for querying new endpoint
- [x] Build chron job for kicking off update service
- [x] Set up and run tests to API interaction, run live and record with VCR

**Comment by NB28VT** [comment]
Work on this is on hold pending an ongoing investigation into handling Veteran communication/visibility for document failures in the current system.

While there are still some loose ends left on this, the core of this work is done and PRed in a draft [here](https://github.com/department-of-veterans-affairs/vets-api/pull/15964). More information in that PR

**Comment by lisacapaccioli** [comment]
Polling information (getting a status on the uploads after sent to LH to confirm if they make it to the eFolder) (this is before we migrate to LH) - maybe includes alerts/monitoring
