### ISSUE TITLE
Update search results header

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75816]
## Background
Noticing some discrepancies with the search results header:
1. The search radius reference is not reflecting the user selection - 50 miles is hard coded
2. The rep type reference is not matching the copy in the radio selections above
3. Content has a one-word difference from CAIA recommendation (CAIA has "and" before the rep name, Staging has "matches") and the rep type and search area are in quotations

CAIA recommendation
> for “[type of accredited representative]” and “[name of accredited representative]” within "[search area]" of “[address, city, state, or postal code]”

Current experience in Staging:
<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3229145a6a89162f6e0d3398920704a24b23dd54/image.png" alt="image.png" />

## Tasks
- [ ] Update search radius reference to reflect the user selection
- [ ] Update the rep type references to match the copy in the radio selections above, for all three rep types
- [ ] Update content to match CAIA recommendations (word swap and add quotations to search area and rep type)

## Acceptance Criteria
- [ ] Search results header accurately reflects the parameters selected above, and conforms with CAIA's content recommendations
