### ISSUE TITLE
Update Report modal copy, styling and behavior

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75813]
## Copy & Styling
**Desktop Design:**
<img width="277" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXROQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--456b68df004138bf73e3424bcbbf4172d5d6ca3e/image.png" alt="image.png" />
<img width="693" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2xOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0405daaa136ab8c589b59eb7f4a248d115180dfc/image.png" alt="image.png" />

**In Staging, desktop:**
<img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5KQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcb50c11cde32acec2f43eda174fb9e71f252962/image.png" alt="image.png" />
<img width="707" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ROQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18df6a87b0f534d84291c36bf4bf0ad4c41f8330/image.png" alt="image.png" />

**Mobile Design:**
<img width="163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6430eadb1a00ead3ea0e14c191b044ad10dd119/image.png" alt="image.png" />

**In Staging, mobile:**
<img width="171" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05PQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be69e3b1fd1448a03dfa01c4288ec89600313d0c/image.png" alt="image.png" />

## Behavior
- Launching the report modal on mobile (iOS Chrome 16.6.1) seems to reset scroll to the top of the screen which is disorienting. Doesn’t happen on desktop.
- In Safari, choosing "Other" in modal automatically moves focus to the Close modal button.  Focus should either a) stay on the checkbox or b) move to the "Describe the other information" input field.

## Tasks
Copy and Styling: 
- [x] Remove "Incorrect" from the address, phone and email checkbox labels
- [x] Double check the text size -  Top heading is h3 and others are h4 size
- [x] Update confirmation copy to “Thanks for reporting outdated information.” (late copy edit)
- [ ] Double check that the mobile modal is using the full content container width (seems like it might not be, as the Other input field is shorter than expected)

Behavior:
- [ ] When launching the report modal on mobile, do not reset the scroll to the top of the screen (experienced in iOS Chrome, not on desktop)
- [x] Update focus when "Other" is selected in the modal (experienced confusing focus behavior in Safari)

**Comment by cosu419** [comment]
For some weird reason, the modal component is inflating the computed font-size of all text contained within (including the list items, checkbox items, etc). I can override this, but if I update the checkbox items for instance, the checkboxes look kind of big by comparison. Here's how it looks with manual overrides of the default font sizes:

<img width="750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFpqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4baf12a5106b194b4f23f263bef6de39a713491/image.png" alt="image.png" />

**Comment by oddball-lindsay** [comment]
Need one additional PR to address the header font size to close this out

**Comment by oddball-lindsay** [comment]
@mtri can you please confirm the tasks that are currently unchecked are completed, and working as expected in Staging?

If so, feel free to close out this ticket :)

**Comment by mtri** [comment]
>  Double check the text size - Top heading is h3 and others are h4 size

Looks good!

>  Double check that the mobile modal is using the full content container width (seems like it might not be, as the Other input field is shorter than expected)

Still looks this way on mobile iOS Chrome.

**Comment by oddball-lindsay** [comment]
Removed the padding that was introduced, which got us halfway to the design expectation.  But there is some padding left on the right that comes with the modal.  

@cosu419 update from text input to text area.

**Comment by mtri** [comment]
Text area looks good and I think meets the needs of that box better than the original input.

Super small thing but is it possible to have padding on the right on desktop so that it doesn't stick into the same column as the close button and matches the left? The margin looks tight there now.

<img width="686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--683a5ec87f79c92b2725faebdb7553d6618ca70d/Find%20A%20VA%20Accredited%20Representative%20Or%20VSO%20Veterans%20Affairs%202024-02-27%20at%203.38.19%20PM.jpg" alt="Find A VA Accredited Representative Or VSO Veterans Affairs 2024-02-27 at 3.38.19 PM.jpg" />

**Comment by oddball-lindsay** [comment]
Doesn't seem to be an option to expand the container width.  Can tighten up the text area box, but that would involve constraining the horizontal width which is what we were trying to resolve.

Calling this good for now
