### ISSUE TITLE
[FSR] Review page error alert messaging Veteran Information chapter

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#75831]
## Description
Implement more helpful error handling on final review page for **Veteran Information Chapter**

#### Example of Review page error message that has been implemented:

 - [Review & submit validation error links #21252](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21252)
   - [PR #16431](https://github.com/department-of-veterans-affairs/vets-website/pull/16431)

[Design ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67811)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXV2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cd3b2646ea85276b3954036b778915de8cb63fe/image.png)

Given: Error handling isn't exactly clear on final review page
When: A veteran attempts to submit a form with an error
Then: Error alert links to set focus to the accordion where the error exists

## Tasks
**Confirm functionality for the following pages:**
 - [ ] `availableDebts`
 - [ ] `currentContactInformation` (examples should exist)
 - [ ] `spouseInformation`
 - [ ] `spouseName`

**Add required/validation for the following pages:**
 - [ ] `dependentCount`
 - [ ] `dependentAges`

## Acceptance criteria

- [ ] Error messaging on final review page for **Veteran Information Chapter** is clear and functioning as expected
- [ ] Works with current version of the form (post review navigation)

## Testing
- [ ] Complete manual testing
- [ ] Generate e2e/unit test for new functionality 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Per convo with Andrew and the screenshots below, between the default behavior not returning a helpful error for us to filter and allow them to navigate through, the user not being able to update the necessary data needed (because it is prepopulated and retrieved prior to entering the form), and the rest of the sections being optional: this ticket has no work that needs to be completed by FE. This was covering an edge case that the user basically should never encounter.

<img width="1507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54935c0ee55e688ae08286ac04d6d14dab70e9dd/image.png" alt="image.png" />

<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDdMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5c017883f6ebfaae2e13d73bc8087e757c35e59/image.png" alt="image.png" />
