### ISSUE TITLE
[FSR] Review page error alert messaging Household Income chapter

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#75832]
## Description
Implement more helpful error handling on final review page for **Household Income Chapter**.
There are a number of pages affected in this chapter, it may require spin off tickets to complete fully. 

[Design ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67811)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXV2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cd3b2646ea85276b3954036b778915de8cb63fe/image.png)

#### Example of Review page error message that has been implemented:

 - [Review & submit validation error links #21252](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21252)
   - [PR #16431](https://github.com/department-of-veterans-affairs/vets-website/pull/16431)

Given: Error handling isn't exactly clear on final review page
When: A veteran attempts to submit a form with an error
Then: Error alert links to set focus to the accordion where the error exists

## Tasks

**Confirm functionality for the following pages:**
 - [x] `editBenefitsEnhanced`
 - [x] `spouseBenefits`
 - [x] `spouseBenefitRecords`

**Add required/validation for the following pages:**
 - [x] `employmentQuestion`
 - [x] `enhancedEmploymentRecords`
 - [x] `employmentHistorySummary` - may need a big custom _override to check the conditions below, and link directly to this section for editing
   - [ ] `employmentWorkDates`
   - [x] `grossMonthlyIncome`
   - [ ] ~~`payrollDeductionChecklist`~~ (not required)
   - [ ] `payrollDeductionInputList` (conditionally required)
 - [x] `otherIncomeSummary`
 
 - [ ] `spouseEmploymentQuestion`
 - [ ] `spouseEmploymentHistory` - may need a big custom _override to check the conditions below, and link directly to this section for editing
   - [ ] `enhancedSpouseEmploymentRecords`
   - [ ] `spouseEmploymentWorkDates`
   - [ ] `enhancedSpouseGrossMonthlyIncome`
   - [ ] `spousePayrollDeductionInputList` 
 - [ ] `spouseOtherIncomeSummary`

 
**Note:** Stuff like payrollDeductionChecklist isn't required, but if it's filled out, then payrollDeductionInputList is required so we need to check that

## Acceptance criteria

- [ ] Error messaging on final review page for **Household Income Chapter** is clear and functioning as expected
- [ ] Works with current version of the form (post review navigation)

## Testing
- [ ] Complete manual testing
- [ ] Generate e2e/unit test for new functionality 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
Code review completed, ready to merge

**Comment by amponce** [comment]
New ticket created to cleanup error handler https://github.com/department-of-veterans-affairs/va.gov-team/issues/90457
