### ISSUE TITLE
[FSR] Review page error alert messaging Resolution Option & Bankruptcy chapters

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#75835]
## Description
Implement more helpful error handling on final review page for **Resolution Option & Bankruptcy Chapters**

[Design ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67811)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXV2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cd3b2646ea85276b3954036b778915de8cb63fe/image.png)

#### Example of Review page error message that has been implemented:

 - [Review & submit validation error links #21252](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21252)
   - [PR #16431](https://github.com/department-of-veterans-affairs/vets-website/pull/16431)

Given: Error handling isn't exactly clear on final review page
When: A veteran attempts to submit a form with an error
Then: Error alert links to set focus to the accordion where the error exists

## Tasks

**Add required/validation for the following pages:**
 - [ ] `resolutionOption`
 - [ ] `resolutionComment`
 - [ ] `resolutionWaiverCheck`
 - [ ] `resolutionComments` 

 - [ ] `bankruptcyHistory`
 - [ ] `enhancedBankruptcyHistoryRecords`

## Acceptance criteria

- [ ] Error messaging on final review page for **Resolution Option & Bankruptcy Chapters** is clear and functioning as expected
- [ ] Works with current version of the form (post review navigation)

## Testing
- [ ] Complete manual testing
- [ ] Generate e2e/unit test for new functionality 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Pulled in late to sprint ending 6/4/2024. We had finished up everything for that sprint and are technically working ahead!

**Comment by OptionSelect** [comment]
[thread here](https://dsva.slack.com/archives/CPE4AJ6Q0/p1717785587208879) details some of the trials and tribulations and restrictions dealing with this. So far this implementation is the best we can do regarding dynamic messaging and behavior.
