### ISSUE TITLE
[FSR] Review page error alert messaging Household Assets chapter

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#75833]
## Description
Implement more helpful error handling on final review page for **Household Assets Chapter**

[Design ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67811)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXV2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cd3b2646ea85276b3954036b778915de8cb63fe/image.png)

#### Example of Review page error message that has been implemented:

 - [Review & submit validation error links #21252](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21252)
   - [PR #16431](https://github.com/department-of-veterans-affairs/vets-website/pull/16431)

Given: Error handling isn't exactly clear on final review page
When: A veteran attempts to submit a form with an error
Then: Error alert links to set focus to the accordion where the error exists

## Tasks

**Confirm functionality for the following pages:**
 - [ ] `enhancedRealEstate`
 - [ ] `enhancedRealEstateRecords`
 - [ ] `vehicles`
 - [ ] `recreationalVehicles`
 - [ ] `recreationalVehicleRecords`

**Add required/validation for the following pages:**
 - [ ] `cashOnHand`
 - [ ] `cashInBank`
 - [ ] `monetaryValues`
 - [ ] `vehiclesSummary`
 - [ ] `otherAssetsSummary`

## Acceptance criteria

- [ ] Error messaging on final review page for **Household Assets Chapter** is clear and functioning as expected
- [ ] Works with current version of the form (post review navigation)

## Testing
- [ ] Complete manual testing
- [ ] Generate e2e/unit test for new functionality 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Per Planning, 1 pt of effort remains on this ticket.

**Comment by amponce** [comment]
I’ve completed error handling for all required items, but I’m seeing a strange result related to the vehicle records’ “automobile” array validation. I’m currently working on a fix and will send the PR to FE as soon as the issue is resolved. I’m also a little behind schedule due to an illness running through our household, so my hours are a little sporadic.
