### ISSUE TITLE
Pension Team Sprint 15 Plan: 02/14/24—02/27/24

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75844]
## Sprint 15: 02/14/24—02/27/24

**- Outages (PTO, holiday, or unplanned):** 
- **Emily:** 2/12 - 2/15 no meetings; 2/16 - 2/23 OOO
- **Daniella:** 2/14 - 2/16
- **Tai**: 2/16
- **Wayne**: 2/16
- **Zack**: 2/16
- **Everybody**: 2/19: Holiday (President's Day)
- **Vicky**: 2/23

## Theme(s):

- Increase release to production to higher traffic, high-priority issues, as needed
- Usability testing planning and pilot
- Design & engineering alignment on component audit & prioritization
- Implementing Intent to File experience
- Improving automated testing
- Improving monitoring

## Notes:
- 
 
## Goal(s):

**LAUNCH TO PROD**

- [x] Increase traffic to production to 50% of traffic #75566
- [x] Increase traffic to production to 75% of traffic #75568
- Address any bugs or high-priority items from release
- [x] Create Pension Reactivation Email Template #69764
- [ ] Prepare VA Notify Trigger and build notification code to send by 2/21 (tentative) #69766
- [x] Notify Contact Center of release to product (Canary release) #73615
- [x] Daily monitoring of Pension MVP launch in GA/DOMO #73616
- [x] Daily monitoring of Pension MVP launch in Datadog #73197

**RESEARCH**

- [x] Create Pension form usability testing plan #73620
- [x] Update research backlog by categories that zoom out potential priorities #75372

**DESIGN/FE ENGINEERING**
- [x] Document design debt for FE engineering #73621
- [x] Cross reference engineering web component audit with design audit findings #75396
- [x] Meet with VA stakeholders on Design Debt from MVP #76156

**ENGINEERING**

**_Form launch:_**

- [x] Update Intro page Process List to V3 component #76296
- [x] Gross Monthly Income responses should overflow in PDF only if more than 4 entries #76086
- [ ] Spike - Investigate the 401 errors in production #75632
- [x] Spike: Investigate prefill for Step 1 prior claim and VA file number #70482
- [x] Letters in postal code are removed in PDF #74689
- [x] POW announced as word by screen readers #74871 **(Updated but one more punctuation request from Katherine)**
- [x] Confirmation page UX improvements #74150
- [x] Military Branch selections on Review Page should only display selected branches #75888

**_Intent to file:_**
- [ ] Change ITF so that it is triggered at the start of the application #75583

**_Improving logging and monitoring:_**
- [ ] SPIKE: Review logging and monitoring for errors #75585

**_Improving testing:_**

- [ ] Write Cypress keyboard tests testing more possible interactions #75571
- Improving automated testing

**_Staging review Design/FE tech debt:_**

- [ ] [Content organization] Your page doesn't follow heading hierarchy. Headings aren't properly nested, and headings and/or labels aren't relevant to the page. (02.04.3) #73987
- [x] [Link and button labels] Button and link language isn't descriptive and/or their purpose isn't clear. (08.03.1) #73969
- [x] [Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.2) #73977
- [ ] [Content styleguide] The content isn't written consistently across static pages, tools, and devices. (05.03.2) #73972
- [x] [Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.4) #73975
- [x] [Content styleguide] The content has spelling, punctuation, or typo errors. (05.02.3) #73976
