### ISSUE TITLE
Create documentation for Base GA4 Implementation

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#75852]
### Description
This ticket is to create documentation within Confluence, on the Analytics & Insights Team space to the work done in our base implementation. 

- **Reference Document:** https://docs.google.com/document/d/1Mw8d2yRtuWEXX23ChGeCv51dJ7MJvrYgdY8dCXNBKtc/edit 

### Tasks

- After base GA4 implementation properties have been created, take the reference documents created [here](https://docs.google.com/document/d/1Mw8d2yRtuWEXX23ChGeCv51dJ7MJvrYgdY8dCXNBKtc/edit), and add them to the following:
- [x] Update existing documentation on GA4 migration in Confluence. (base configuration, audit info, etc.)
- [x] If needed, look to create a new place, or page.

### Acceptance Criteria

- [x] Confluence has been updated with progress on base implementation ([here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3048800290/GA4+Documentation+Properties))

**Comment by johnny-jesensky-adhoc** [comment]
Create a separate ticket to update our Google Analytics Implementation Request Github template. Work with @Blivaditis on making edits to those templates.

**Comment by johnny-jesensky-adhoc** [comment]
This ticket will be carried over into next sprint - the implementation of Web & Form Components took longer than expected, which ate into time to update our base documentation.

We will be rolling this one into the next sprint.

FYI @davidconlon, @jestutt, @jwoodman5

**Comment by johnny-jesensky-adhoc** [comment]
@Blivaditis -- added you as an assignee to help Jamie input this into our team's Confluence space. This should be ready to input later today.

FYI @jestutt

**Comment by Blivaditis** [comment]
The page has been created and updated in confluence, it now contains the information related to GA4 properties. The confluence page can be found in the ticket and is linked [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3048800290/GA4+Documentation+Properties).
