### ISSUE TITLE
[Rated Disabilities] Update discrepancy checks to account for latest changes

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#75855]
### Background
We need to update the discrepancy checks to account for the fact that the latest version of the Rated Disabilities endpoint from Lighthouse returns deferred ratings. We need to filter those out and check to see if we are still seeing any other is discrepancies. We can also remove the filtering of inactive ratings as those are no longer returned by Lighthouse

### Context
The Lighthouse team has pushed out new updates to the production service we are planning on using for Rated Disability data. When we turned the discrepancy checks back on, we noticed that they were detecting discrepancies between the Lighthouse and EVSS responses again. Upon further investigation, it became clear that the primary reason this was happening was because the new Lighthouse endpoint returns ratings that have a decision of 'Deferred', but the EVSS service does not.

### Tasks
- [x] Remove the filtering for inactive ratings
- [x] Add filtering to remove ratings with a `decision` of 'Deferred'
- [x] Update rspec examples to account for the changes above

### Acceptance Criteria
- [x] We are checking for discrepancies with Lighthouse and EVSS while excluding deferred ratings

**Comment by jerekshoe** [comment]
#### Update
The PR for this has been merged, I'm not sure if it made it into the daily deploy or not. Will close this once I have verified that it has deployed

**Comment by jerekshoe** [comment]
#### Update (2/12)
The PR was deployed as part of the daily deploy. Discovered that LH still returns inactive ratings, so adding back the logic to filter those out (thankfully I didn't remove it from the other controller). That PR will be moved out of draft after checks have finished and are passing

**Comment by HeatherWidmont** [comment]
Someone from another team will review this

**Comment by jerekshoe** [comment]
#### Update (2/13)
Merged the second PR and am closing this issue. If anything else comes up, then I will make a new issue
