### ISSUE TITLE
Design intent Collaboration - GIBCT Sec. 103 Update

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#7586]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [ ] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [ ] VSP <> **requesting team** design intent collaboration meeting completed
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/product-outline.md)
- [inVision mock-up](https://bahdigital.invisionapp.com/share/7NIADE8GMJ2#/296034999_Profile_-University_Of_California-Davis
) 

## Meeting attendees from **Booz Allen**
- Designer(s) (required): Cindy Cruz, Jen Jones, Amy Knox
- Product Manager (optional): Darrell Neel, Will McCormack
- DEPO design lead (required as applicable): Matt Self

## Scheduling
Preferred dates or times: 
Tues. 4/7, 10-11:30am, 2:30-3pm ET
Thurs., 4/9, 10-10:30am ET 

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Schedule 4/9 at 10am EST
