### ISSUE TITLE
Turn Off Pagination on Platform Website

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75862]
## Issue Description
As Platform Website's IA is intended to function as an encyclopedia, offering one article at a time, Content Team feels the Pagination feature should be removed, and returned to its previous state.

---
## Tasks
- [x] Confirm required steps on k15t's documentation about Scroll Viewport
- [x] Turn off Pagination feature

## Acceptance Criteria
- [x] Pagination feature will disappear from bottom of Platform Website's IA

---
### Original work ticket [71313](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/71313)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75862?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
Moved to current sprint because of available capacity.
