### ISSUE TITLE
Initial Review of Code Scanning Results

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#75868]
## Description
As part of the WASA scan request process, we were asked to have Code Scanning performed, the results surfaced a number of issues which we need to sort and triage in order to formulate a mitigation plan next sprint.

---

## Tasks
- [x] Create a Confluence page for the Code Scanning Results
- [ ] Conduct an initial scrub or results
- [ ] Make relevant teams aware of the code scanning issues

## Acceptance Criteria
- [ ] A Confluence page exists and has had an initial review
