### ISSUE TITLE
Update sort copy and component

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75867]
## Background

The sort component needs to be updated to v3, and copy should be updated to use sentence case. Eg. “First name” instead of “First Name”.

<img width="528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5355c0d235fdc673b0685ae081f2cf9f10479f51/image.png" alt="image.png" />

## Tasks
- [ ] Update sort component to v3
- [ ] Update sort component copy to use sentence case

## Acceptance Criteria
- [ ] Sort component matches design file and uses the most up to date v3 component
