### ISSUE TITLE
Collaboration Cycle for [Decision Reviews Team, Board Appeal (Notice of Disagreement) VA Form 10182, Request an Extension Feature (OMB Approved No. 2900-0674)]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#75865]
### VFS team name

Decision Reviews Team

### Product name

Board Appeal (Notice of Disagreement) VA Form 10182 (Formerly named: Request a Board Appeal VA Form 10182)

### Feature name

Request an Extension Feature (OMB Approved No. 2900-0674)

### GitHub label for team

Decision-Reviews-Team

### GitHub label for product

NOD

### Public DSVA Slack channel for VFS team

#benefits-decision-reviews

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

1/3/2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Product/request_an_extension_feature.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C5AGLBNRK/p1707761431554289)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent</summary>

##### VFS actions
- Navigate to reference link: [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
- [x] Schedule your Design Intent when ready:
   - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
      - The Governance team is responsible for inviting our team members, including our Product Owner, Product Manager, and practice area specialists. We also notify OCTO-DE practice area leads when we finalize meeting scheduling. 
   - Click "Schedule Event"
- [ ] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Design Intent` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts **ONLY** in the Design Intent artifacts section below at least two days before the scheduled Design Intent.  **Do NOT add artifacts to Comments section**
  
**Design Intent artifacts**

See Platform guidance on [Design Intent artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Design Intent meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

- [ ] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691599300063/42cd59780f131a0a61b149f7df8aa9c7f8ae83f6?wid=0-1692034265160) (required)
- [ ] Figma [wireframes](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-1719&mode=design) / [prototype](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691599300063/42cd59780f131a0a61b149f7df8aa9c7f8ae83f6?sender=ud193ce75f65a17a316ea6194)
- [ ] Staging pages: [Request an extension](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/extension-request), [Reason for extension](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/extension-reason), [VHA Denial](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/appealing-denial)
  
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Platform actions

* Accessibility
  * [ ] Feedback ticket attached
  * [ ] No feedback
* Design
  * [ ] Feedback ticket attached
  * [ ] No feedback
* IA
  * [ ] Feedback ticket attached
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode: 
  
##### VFS actions

- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Sitewide CAIA Intake Request
<details>
  <summary>Toggle Sitewide CAIA Intake Request</summary>

##### VFS actions
- [ ] Complete the [Sitewide CAIA intake request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-CAIA-intake-request.2124906551.html)
- [ ] Link to the Sitewide CAIA Intake Request ticket below

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:
- [x] Finalized design [prototype](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691599300063/42cd59780f131a0a61b149f7df8aa9c7f8ae83f6?sender=ud193ce75f65a17a316ea6194)
- [x] Figma [wireframes](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-1719&mode=design) / [prototype](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691599300063/42cd59780f131a0a61b149f7df8aa9c7f8ae83f6?sender=ud193ce75f65a17a316ea6194)
     - [ ] [Request an extension](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-2289&mode=design&t=m4UWtjKLspXf615T-4)
     - [ ] [Reason for extension](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-2133&mode=design&t=m4UWtjKLspXf615T-4)
     - [ ] [VHA Denial](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-1929&mode=design&t=m4UWtjKLspXf615T-4)
- [x] [Staging URL](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/) (User: vetsgov+test236@id.me)
  - [ ] [Request an extension](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/extension-request)
  - [ ] [Reason for extension](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/extension-reason)
  - [ ] [VHA Denial](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/appealing-denial)
 
**Content artifacts**
  
- [ ] Please include [a link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md#request-a-board-appeal-6) to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

**IA artifacts**

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C5AGLBNRK/p1707847416047549)
- [x] Meeting date/time: Friday, February 16, 2024 at 11:30 a.m. Eastern

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [ ] Feedback ticket attached
  * [x] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [ ] Feedback ticket attached
  * [x] No feedback
* [x] Update this ticket with the Zoom recording
  - [Midpoint review recording](https://oddball-io.zoom.us/rec/share/OyGO9QWoGG1j5A_vBlsBgKZ7yGWCp1RV6tSZwCLroAUV_wiZXVM2QlbojjJrOEKG.MBE3wbeBZg1Eredf)
  - Passcode: `%C8KP+cU`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Staging Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [ ] [Staging URL](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/) (User: vetsgov+test236@id.me, password is available in the [TUD](https://tud.vfs.va.gov/?page=4))
- [ ] Request an extension, reason for extension, VHA denial        
- [ ] Staging test user information         
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
  
**IA artifacts**
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/suites/view/6&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/5198)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/681)
- [x] [Summary(Defects) Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71283)
- [x] E2E tests (link to our [test folder](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/appeals/10182/tests))
- [x] Code coverage (snapshot below)  
```
yarn test:coverage-app appeals/10182
```

<img width="873" alt="Form 10182 test coverage: 100% Statements 312/312, 96.19% Branches 202/210, 100% Functions 81/81, and 100% Lines 305/305" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/b3ab1f7a-2fe1-49c9-af5c-b8642ee322c2">

<p />
<p />

  
**Accessibility artifacts**
  
- [ ] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76553).
  
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C5AGLBNRK/p1708013782178589)
- [x] Meeting date/time: Friday, February 23, 2024 at 2 p.m. Eastern

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/wSNO9e20CTzu2X3ei_DuGaXamTs5Hb88AkChBlFB-fj0TlRM7NFBTp8yGoYjTIT6.d09EvCCvOoX7WEii
  - Password: 7r@2@@sS
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] [Link to the Readiness Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1509)

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by eileen-coforma** [comment]
Hi @allison0034 is there a ticket for the design feedback we got during Staging Review? I found the ticket about the review and submit edit button for Midpoint Review, but I don't see anything about the negative margin for the textarea error state.
