### ISSUE TITLE
Explore & support FE Build/Deploy pipeline issues

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#75873]
## Description
On 2/5/24, we noticed that issues were happening that were causing problems for the FE build and deploy process. Due to this, we had to divert resources to focus on this and help to troubleshoot and manage it.

---

## Tasks
- [ ] Work to understand the current issues we're experiencing
- [ ] Work to identify root causes 
- [ ] Work to support daily deploys getting out in the meantime

## Acceptance Criteria
- [x] We are getting daily deploys out as much as possible
- [x] We are documenting what we know and have learned about the issues

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/2961473647/Troubleshooting+CI+Breakages+-+Feb+2024 Working document of what we've tried, what we know works, and what we know doesn't.
