### ISSUE TITLE
General styling updates

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75874]
## Background
**Vertical spacing**
Increase spacing after "Search" button...
<img width="488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1af4ea28f06c03ae39b5a9b12effa0013b9265e9/image.png" alt="image.png" />
...to match spacing after the "Note"
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDlPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44b75493097e8214faf0f8f19bb4901ead02e504/image.png" alt="image.png" />

**Container margins and spacing**
At all viewport sizes, the container margins for the page seem larger than other pages on Va.Gov. See a page like https://www.va.gov/find-forms/about-form-21-22/ This is leading to the content not aligning on the left with the navigation.
<img width="469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a999534a56fe9a6faeef76ec91049e0646740584/image.png" alt="image.png" />
vs.
<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd37a71b4f29cf322d6ec3f845180f3e1518915a/image.png" alt="image.png" />

Possible to float the content of the card to the left as opposed to centering on smaller viewports?
<img width="464" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cc34f1ebb1cce2f285783be9af034a2eae7b7d6/image.png" alt="image.png" />

The search results container is losing its height once results are cleared (also when applying new parameters or doing a completely new seaarch), causing the footer to flash when the page is reloading when applying new parameters or doing a new search.
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c738de4129fbd6c3eeb85bbb2628aa3a75578c16/image.png" alt="image.png" />

**Border**
Can we use the higher contrast black border card default? See https://design.va.gov/components/card#default---white-with-border
<img width="573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66389dbd3a27f1d87589325fdde7a37645c705e7/image.png" alt="image.png" />

## Tasks
Vertical spacing:
- [x] Increase space between "Search" and "Your search results" to be the same spacing as between the “Note: …” and the “Search for an accredited representative” header.

Container margins and spacing:
- [x] Double check the container margins for Find to ensure proper left-hand alignment (margins should match https://www.va.gov/find-forms/about-form-21-22/)
- [x] Maintain the search results container height when results are cleared
- [x] On smaller viewports, float the content of the card to the left (as opposed to center)

Border:
- [x] Update border on rep result cards to use a higher contrast black border (https://design.va.gov/components/card#default---white-with-border)

**Comment by oddball-lindsay** [comment]
Remaining: set the margin on the global container

**Comment by oddball-lindsay** [comment]
@mtri can you please confirm the tasks that are currently unchecked are completed, and working as expected in Staging?

If so, feel free to close out this ticket :)

**Comment by mtri** [comment]
>  Increase space between "Search" and "Your search results" to be the same spacing as between the “Note: …” and the “Search for an accredited representative” header.

Looks good!

>  Double check the container margins for Find to ensure proper left-hand alignment (margins should match https://www.va.gov/find-forms/about-form-21-22/)

Still seems off. I'm flipping back and forth between two tabs and noticing the position of the where the page starts and the position of the breadrumb. Using https://www.va.gov/find-forms/about-form-21-22/ as the example.

>  Maintain the search results container height when results are cleared

Looks good!

**Comment by cosu419** [comment]
Fixed the margin issue (not yet pushed). Changing the utility classes + element structure on the containers broke a lot of the child elements, so I had to de-prioritize this one while working on unit tests. 

Will update when this released!

**Comment by mtri** [comment]
Margin/container issue looks good!
