### ISSUE TITLE
[Research] VA.gov Onboarding: Comparative Analysis

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#75880]
## Background
As part of our early round of discovery To begin our work to create a solution for first time onboarding to va.gov we need to do a first round of research/discovery.

Many organizations in the private sector provide a new user onboarding flow that outlines key capabilities, common actions new users take, steps that similar users take, etc. We should conduct a comparative analysis to see how this is approached, with the goal of identifying how we might improve the VA.gov onboarding experience and potentially create our own "welcome" flow.

## Tasks
- [x] Gather "evidence" - screenshots - of public and private sector orgs' handling of "onboarding"
- [x] Analyze findings
- [x] Write up comparative analysis of existing onboarding processes in public and private sector

## Acceptance Criteria
- [ ] Report/readout of comparative analysis findings shared w/ team
- [ ] Ready for next steps

**Comment by andaleliz** [comment]
An excellent resource shared by the mobile team: https://www.useronboard.com/user-onboarding-teardowns/

**Comment by ajakabcin** [comment]
Moving to next sprint due to high priority direct deposit work.

**Comment by andaleliz** [comment]
@ajakabcin @clantosswett I've completed my analysis and [published it here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/comparative-analysis.md). 

Given what we talked about last week, I think we're good to close this out. I'm going to move the "present comparative analysis to team" AC to the kickoff ticket as I think it would make sense to do as part of that at this point, rather than a separate event.
