### ISSUE TITLE
[Design] Update margins for auto-layout and apply to Figma frames

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#75890]
## Tasks
- [x] Review spacing and padding on local or stg
- [x] Update spacing and padding in the content + need help + footer component
- [x] Determine where to put these guidelines
- [x] Update frames in production file
- [x] Update frames in unified check in Design page only

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by zach-park** [comment]
Assigned the ticket to myself.

**Comment by benbrasso-agile6** [comment]
Template for margins/padding looks good. Left a few comments.

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske , this task is ready to be validated.

**Comment by zach-park** [comment]
Spacing guideline (in the mhv library):
https://www.figma.com/file/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?type=design&node-id=633%3A2087&mode=design&t=F930A7zIxmJA5kLX-1

**Comment by cgednalske** [comment]
@zach-park From what I can tell, Production Check-in and Pre-check-in both look great. 👍

**Comment by cgednalske** [comment]
@zach-park The only thing I'm wondering about is that most content blocks seem to have 16px between them (outside of the content blocks). But content blocks above Need help often has it built in to the block itself. Could you provide some background for that difference? 👀

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske is this all complete and validated? Or still waiting for zach to make a few updates?

**Comment by zach-park** [comment]
> @zach-park The only thing I'm wondering about is the header and content block have 16px between them (outside of the content blocks). But other content blocks have it built in to the block itself. Could you provide some background for that difference? 👀
> 
> (Noticing that Unified seems to have the 16px outside of the blocks as well)
> 
> Note: if this is a spot where we're going to be flexible as long as the spacing is accurate, totally fine with that 😃

Hi @cgednalske , for some content blocks, I needed to add additional spacing to give them 40 px spacing.

**Comment by zach-park** [comment]
@cgednalske , would you mind leaving a quick comment on (or point me to) the ones you mentioned? Thank you!

**Comment by cgednalske** [comment]
It's probably easiest to discuss in UX sync if that's ok! 😃

**Comment by zach-park** [comment]
@cgednalske @benbrasso-agile6 , the auto layout settings for the content blocks are updated now so that they are consistent throughout the whole figma files. Top margin: 16 and bottom margin: 24. And they automatically set the content block spacing (e.g., 40 px) when whey are stacked now.

**Comment by benbrasso-agile6** [comment]
Nice! I'm good to close when you are, @cgednalske

**Comment by cgednalske** [comment]
Sounds great! Nice work @zach-park 🎉
