### ISSUE TITLE
Change SR Dashboard in Domo from fiscal year to calendar year

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#75891]
## User Story
As a Governance team member, I want to update the staging review dashboard to show calendar year opposed to fiscal year so that all platform guidance, etc. uses the same terminology.

Assignee: @erinrwhite 
Peer Reviewer: @it-harrison 

## Description
Platform Product Managers were made aware on 2/7/2024 that OCTO will now be communicating quarters using the calendar year, no longer the fiscal year. 

Aside from changes to ongoing initiatives, the only other place Governance needs to make changes is within the Staging Review dashboard in Domo. The purpose of this ticket is to update the labels in Domo.

FY24Q2 becomes CY24Q1
FY24Q1 becomes CY23Q4
etc.

## Impacted Artifacts
Staging Review dashboard

## Tasks
- [ ] Updated the labels in the dashboard to reflect the change from fiscal year to calendar year

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Staging Review dashboard in Domo reflects the calendar year by quarter

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@erinrwhite the first three transforms in [this dataflow](https://va-gov.domo.com/datacenter/dataflows/287/author) are in need of updating. Feel free to ask any questions - what I've done could be simplified / improved I'm sure.

**Comment by erinrwhite** [comment]
I think I need to be given access to the Staging Review dashboard in Domo - I'm not seeing it. @shiragoodman can you help with this?

**Comment by erinrwhite** [comment]
Request granted earlier this week; planning to start work first thing Monday.

**Comment by erinrwhite** [comment]
@it-harrison thank you for this! I should've known there'd be one more piece. I'll get this updated tomorrow and report back.

**Comment by erinrwhite** [comment]
@it-harrison I think this is working now! Can you review?

[SR dashboard](https://va-gov.domo.com/page/1340527018)
[updated data flows](https://va-gov.domo.com/datacenter/dataflows/287/author)

**Comment by it-harrison** [comment]
@erinrwhite - looks good!

**Comment by erinrwhite** [comment]
Thank you for the help @it-harrison !! Closing this one out.
