### ISSUE TITLE
Investigate BRD dashboard discrepancy

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#75906]
## Issue Description
This is a follow-up to our Evss-LH migration for BRD release plan ticket. During our DataDog dashboard creation for BRD, we discovered a discrepancy between the Disability Compensation Forms Controller logs and the requests coming into the EVSS BRD provider. We believe this is due to Redis caching at the controller level but we're unclear on why some requests aren't cached, and what might happen once we turn on the Lighthouse provider (like will those requests also get cached or will we be able to see them in the provider-level monitor?) This ticket is to clear up those questions. Should be timeboxed. 

---
## Tasks
- [ ] Test turning on Lighthouse BRD in staging and see logs come through
- [ ] Find BRD data in Redis
- [ ] Might need to ask Platform for help accessing Redis logs to review cache (something like `Redis.new(url: "Settings.redis.rails_cache.url").get("all_users:get_separation_locations"` was giving us nil)
- [ ] Ultimately answer: why do our service-level logs look the way they do?

## Acceptance Criteria
- [ ] Ensure that we can track (and understand) LH requests for separation_locations 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
