### ISSUE TITLE
2024 Q3 SUPPORT TRACKING

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75909]
OVERVIEW
This is an effort to track the level of Tier 2 and on call support being offered by platform technical teams.

ACTION ITEMS [LEAVE THIS EPIC OPEN]
If you are on Tier 2 support or on call and you are assigned a ticket:

 Make sure your name is listed under assignees
 Add your team's label under labels [our label is platform-product-team]

## OCTO Objective and OKR:
**Objective:** 
Our platforms are the best way to deliver products at VA
**OKR**
Our platforms hit the "elite" level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88096
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88791
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88793
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88749
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88799
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88812
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88709
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89017
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89044
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89051
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89241
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/3027
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89391
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89417
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89458
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89469
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89456
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88710
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89466
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89295
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89531
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89620
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89410
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89744
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18595
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18604
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18604
```

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18595
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18604
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18613
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18612
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18623
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18624
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18629
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/515
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18630#pullrequestreview-2331394708
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18627
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18634
- [ ] https://github.com/department-of-veterans-affairs/vets-json-schema/pull/937
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3113
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18554
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18637/
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18639
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3112
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18589
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18641
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18620/
- [ ] https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/540
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18621
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18636
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18652
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18651#pullrequestreview-2333514586
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/517
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18643
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18649
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18645
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18633
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18653
- [ ] https://github.com/department-of-veterans-affairs/devops/pull/14738
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3116
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3117
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18654
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18646
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18655
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18658/
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18571
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18663
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18659
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18650
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/1866
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18626
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18667
- [ ] https://github.com/department-of-veterans-affairs/vets-json-schema/pull/938
```

**Comment by jennb33** [comment]
10/1/2024 - Closing this Quarterly Epic.
