### ISSUE TITLE
Dockerize Application to spin up Next.js, DB Instance, Prisma Studio, Sinatra, etc

### ISSUE THREAD

**Issue by moanu404** [department-of-veterans-affairs/va.gov-team#75913]
This ticket is a product of the code review of our initial DB setup and data collection PR 
https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/pull/28

Instead of having to do a manual local setup of prisma and DB locally - its better to use docker  to spin up a Postgres resource, run the Next.js app, and run Prisma Studio.

With the new Sintara proxy app, we'll also want to deploy that as a containerized service.

We'll coordinate all the containers with a `docker-compose.yml`

Investigate, document and implement the way to do this.

**TODO:**
- [x] Next.js Dockerfile updates
- [ ] PostgresDB volume 
- [ ] Prisma Studio Dockerfile
- [x] Sinatra Dockerfile
- [x] Docker Compose for all containers to be orchestrated 

Definition of done: 
- able to run one docker compose command and everything works and runs locally.
- ready to deploy to LHDI

**Comment by mateoclarke** [comment]
We also want to roll in the Sinatra proxy server into this as well, noting above...

**Comment by moanu404** [comment]
already demoed this, needs some more polishing with time but will close this for now
