### ISSUE TITLE
2024 Q4 SUPPORT TRACKER

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75910]
OVERVIEW
This is an effort to track the level of Tier 2 and on call support being offered by platform technical teams.

ACTION ITEMS [LEAVE THIS EPIC OPEN]
If you are on Tier 2 support or on call and you are assigned a ticket:

 Make sure your name is listed under assignees
 Add your team's label under labels [our label is platform-product-team]

## OCTO Objective and OKR:
**Objective:** 
Our platforms are the best way to deliver products at VA
**OKR**
Our platforms hit the "elite" level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3134
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/524
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/523
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/522
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3128
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3133
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3129
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3131
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18734
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18726
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18719
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18718
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18717
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18716
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18713
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18710
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18725
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18732
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18708
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18679
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18709
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18704
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18702
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18727
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18745
- [ ] https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/542
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3138
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18739
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18728
- [ ] https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/543
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18751
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18752
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/526
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18759
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18760
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18733
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18758
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18658
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18571
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18663
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18659
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18650
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/1866
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18761
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18762
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18757
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18720
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3139
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18743
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18696
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3140
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3141
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18776
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18711
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18783
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18782
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3142
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18781
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18694
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18472
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18775
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3144
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18786
- [ ] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3145
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18768
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18753
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18769
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18791
- [ ] https://github.com/department-of-veterans-affairs/vets-json-schema/pull/943
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/527
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/528
- [ ] https://github.com/department-of-veterans-affairs/platform-atlas/pull/529
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18798
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18799
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18800
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18795
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18804/files
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18677
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18802
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18810
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18817
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18814
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18808
- [ ] https://github.com/department-of-veterans-affairs/vets-api/pull/18675
```

**Comment by LindseySaari** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3134

**Comment by AshleyGuerrant** [comment]
2024 Q4 is complete. Closing this epic out.

Tracking now in [#100386](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100386).
