### ISSUE TITLE
Update Pages Mentioning Grafana & Loki

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#75912]
## Issue Description
10 Pages on Platform Website that mention recently sunsetted tools Grafana & Loki require updates.

---
## Tasks
- [x] Locate SME for 10 pages
- [x] Confirm changes to be made
- [x] Update 10 pages, 2 at a time

## Acceptance Criteria
- [x] 10 Pages updated to reflect sunsetting of Grafana, Loki + redirecting user to Datadog where necessary.
---
### Relevant documentation 
[Google Sheet](https://docs.google.com/spreadsheets/d/1XzUOf1qbd6fYaDwXBTDDgFL7Qjfnpafi6BA4NyFnm8I/edit#gid=0) lines 13-22
Discovery Ticket [74640](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/74640)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@taylojill please add your estimate

**Comment by jknipes** [comment]
Listing pages for Lindsay Hattamer w/comments to address/resolve

**Comment by jknipes** [comment]
OOO 2/24-3/24, may require breaking out into several tickets

**Comment by jknipes** [comment]
Contributions from Gia moved this ahead.

**Comment by taylojill** [comment]
All pages updated per instructions via inline comments from Gia (engineer), and published 2/19/24

**Comment by jknipes** [comment]
Tasks completed, moving to _Done_
