### ISSUE TITLE
[FE] My VA C&A: Claims and appeals code and testing enhancements 

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#75917]
## Background
After writing unit tests in previous sprints, proposing some ideas for reducing code bloat - Just wanted to document some improvements for claims and appeals helpers. 

## Tasks
- [x] rename `/reducers/claimsV2.js` to `/reducers/claims.js`, update import paths
- [x] replace instances of `set` function in `/reducers/claimsV2.js` with [lodash/set](https://lodash.com/docs/4.17.15#set), instead of the `'@department-of-veterans-affairs/platform-forms-system/set'`
- [ ] update switch statement in `getStatusContents.jsx` to object
- [ ] then reduce amount of redundant unit tests
- [x] remove `shouldMockApiRequest` function from [/tests/helpers.unit.spec.js](https://github.com/department-of-veterans-affairs/vets-website/pull/27900/files/b2e2e6a6a82dceb8be0f47bc3fa5ab72296bb4dd#diff-6e1cbecb99b9c3ba9d0b50e646f285c92210f9be88a8244ab2136ec3d54d8502)
- [x] reorganize action names. [See Adam's comment](https://github.com/department-of-veterans-affairs/vets-website/pull/27900#discussion_r1486374958) 

## Acceptance Criteria
- [ ] Claims and appeals section code and tests are more streamlined and easier to maintain

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Dev
- _How can this work be validated?_ 
        - Make sure everything visually looks the same/functions properly on My VA
        - Make sure all tests pass

**Comment by allisonlu** [comment]
@ajakabcin 

still in progress, didn't get a PR up before the sprint end unfortunately. i'll update this to 2 points for sprint 33

**Comment by allisonlu** [comment]
@ajakabcin updated to 0 points! just need validation from a dev :)

**Comment by DanielMiller-agile6** [comment]
yep, looks like this is on main now 👍 

<img width="474" alt="Screenshot 2024-04-24 at 8 19 03 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/54035677/d8e73fdb-b508-4e3a-b8e3-df0ee988a347">
