### ISSUE TITLE
Update TE design documentation after addressing all 2nd midpoint review feedback

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#75927]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] update [documentation page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md) after all [2nd midpoint review feedback](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60140) has been addressed. 

## Acceptance Criteria
- [ ] Github page updated with current images and descriptions for existing decisions included
- [ ] Any additional key decisions added to Github page

**Comment by mengA6** [comment]
started updating the [github documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md) - added sections for MVP first release and second release, stubbed out an additional decision to write background for (removing "service-connected").

**Comment by mengA6** [comment]
Just realized that Github [automatically generates a table of contents / outline from the headings in the document](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/). This will be quite useful for [this somewhat large page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md). 

The current Github UI is different from that blog post documenting it. See screenshot:<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f91e0d08d728343fe7aced54f2a5dbf6d96c263/github%20outline.png" alt="github outline.png" />

**Comment by mengA6** [comment]
I've made most of the updates to [the Github page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md). need to break out some things like "changes made post midpoint" and "content updates from CAIA" sections.
