### ISSUE TITLE
Burial Updates | Intro Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#75953]
## Issue Description
_The online Burial 530 form is outdated and needs to have missing fields added and depreciated fields removed._

- [Figma file](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-Redesign-MVP?type=design&node-id=165%3A32381&mode=design&t=dBn2MeEj7z5W6I5O-1)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691512530884/67e3bc6677c8d17cf6fc8848319a6e40ebced1af?wid=0-1694615398728)
- Old form pdf
- [New form pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708a2c6535486d181b128af442f89e12b9bb5302/VBA-21P-530EZ-ARE.pdf)

---
## Tasks
- [ ] Make changes denoted in Sketch file for the Introduction Page 
- [ ] Ensure copy in online form matches Sketch file

## Acceptance Criteria
- [ ] Introduction Page design aligns with Sketch file
- [ ] Copy in online form matches Sketch file
- [ ] Fiorella signs off on changes in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---

**Comment by fiorella-io** [comment]
New comment from @aliyahblackmore for the intro page:
Make sure to remove "your" from "Learn more about requesting ~~your~~ military service records (opens in new tab)"


<img width="70%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/3b60f334-c4fd-4ecc-b2a8-1e702d8c2ec5">

**Comment by fiorella-io** [comment]
Content does not match Figma for the following:
- Breadcrumb
- Subtitle should only have the form name  
     - <img width="30%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/7bfbc33d-de88-4fa6-8a8b-09a212344368">
-  Process list
     - Step 1 mentions Board of appeals
     - Step 2 The link should go to [here](https://www.va.gov/records/get-military-service-records/).

**Comment by fiorella-io** [comment]
Accessibility issue after running Axe dev tools:
<img width="409" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/bbecacf6-77a6-47a9-8e2d-2a7341ed6b00">
