### ISSUE TITLE
Burial Updates | Confirmation Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#75957]
## Issue Description
_The online Burial 530 form is outdated and needs to have missing fields added and depreciated fields removed._

### Designs
- [Authenticated](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=948%3A48980&mode=design&t=6jtlalglGpLHL41Z-1)
- [Unauthenticated](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=952%3A50187&mode=design&t=6jtlalglGpLHL41Z-1)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691512530884/67e3bc6677c8d17cf6fc8848319a6e40ebced1af?wid=0-1694615398728)
- Old form pdf
- [New form pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708a2c6535486d181b128af442f89e12b9bb5302/VBA-21P-530EZ-ARE.pdf)

---
## Tasks
- [ ] Make changes denoted in Sketch file for the SubmissionPage 
- [ ] Ensure copy in online form matches Sketch file

## Acceptance Criteria
- [ ] Submission Page design aligns with Sketch file
- [ ] Copy in online form matches Sketch file
- [ ] Fiorella signs off on changes in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---

**Comment by aliyahblackmore** [comment]
Thanks @fiorella-io.

And as chatted in Figma comments, from my understanding, the "Need help" component at the bottom of the page should be the same across all of the screens in the form. So once you all get confirmation from SMEs on this change, it would need to be adjusted across the entire form.

**Comment by fiorella-io** [comment]
No need to get confirmation on the copy if it's in the Desing system

**Comment by fiorella-io** [comment]
@Midge-dev @DLarson-Oddball 
Match the content on Figma
- [Authenticated](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=948%3A48980&mode=design&t=6jtlalglGpLHL41Z-1)
- [Unauthenticated](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=952%3A50187&mode=design&t=6jtlalglGpLHL41Z-1)
