### ISSUE TITLE
[Data Definitions]: Allow for multiple example files in vet-json-schema

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#75952]
# Overview
vets-json-schema needs to allow for multiple 'example' files as they are called to be exported to dist
The current src/generate-schemas.js in vets-json-schema is only looking for a file called `example.js` to copy to dist

We have multiple fixtures and want them all to be exported and usable for cypress on vets-website.

We need to be careful here as to what this might break in other places.  If we have multiple files with different names, what are the implications?  How is this used downstream?

It may be necessary to have multiple folders such as done in:
HLR-get-contestable-issues-response-*

But ideally, we would want all fixtures in one folder.

Explore the idea of /dist/formName/fixturesHere

This may work work already and no changes are needed.

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

# Tasks
- [ ] See above

# Tasks
- [ ] - For testing, copy (don't delete the original) the files from vets-website: src/applications/pensions/tests/e2e/fixtures/data/*
- [ ] - Determine how best to change src/generate-schemas.js to allow for multiple files.
- [ ] - Assess risk of this change and how `yarn test` might react/skip files that are now differently named
- [ ] - Make sure that `yarn build` and `yarn test` still work properly after these changes are made.

**Comment by mjknight50** [comment]
This is done.  I think in the future we should revisit this so that you can have all fixtures in one folder:
src/examples/21P-527EZ/
    - file1
    - file2
    - etc

Instead of now, which is using multiple folder names:
src/examples/21P-527EZ-simple
src/examples/21P-527EZ-overflow
src/examples/21P-527EZ-kitchen_sink

But in the interests of being minimally invasive, the current approach is good.
