### ISSUE TITLE
[Data Definitions]: - Vets-api needs to handle the data definitions version on submission

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#75990]
# Overview
When a submission is received for pensions within vets-api, [the payload should include ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75963) the version number that the client has for data definitions.

My hope is that 99% of the time, the vets-api should have the latest version and vets-website is behind.

# Tasks
- [ ] - Before a submission can be validated against a schema or saved, the version number from the JSON payload should be compared to the [version number that the vets-api has](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75987).
- [ ] - If the version number is wrong, log an error in data dog
- [ ] - If the version number is wrong, send a 500 (?) and message back to the client telling them that the version is wrong
- [ ] - Evaluate the implications of various error message codes and what makes sense to use.

**Comment by mjknight50** [comment]
We've decided to now pursue at this time.
