### ISSUE TITLE
Audit to see which of our "components" are bespoke and not actually components

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#76005]
## Background Context

As the Platform team makes changes to design system elements (e.g. type scale), we've been warned that this might mess up any UI elements that are not officially components.

We should do an audit to see which of our UI elements are in fact bespoke (i.e. custom) and update those to components to avoid breakage now or in the future.

## Design

One UI element that we know is not an official component is the Evidence Request card:

<img width="1176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd3a253aebdb3ed7b8f620d04f097b9b181f2a62/Screenshot%202024-02-13%20at%2011.14.08%E2%80%AFAM.png" alt="Screenshot 2024-02-13 at 11.14.08 AM.png" />

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Identify UI elements that are not components
- [ ] Update them to V3 components wherever possible
- [ ] If a V3 component won't work for our purposes, discuss what to do with design
- [ ] If we need to file an experimental ticket for a new variant to meet our needs, design will do that

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Product performs functional QA and verifies acceptance criteria was met
- [ ] Engineering identifies staging users required to test and shares account and credentials with product

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_
