### ISSUE TITLE
[FSR] Remove deprecated code form previous form versions Household Income Chapter

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#76008]
## Description
Find and remove any deprecated code from the Household Income Chapter. 

We are working to deprecate the following feature flags now that the features are stable, and there are no more in progress forms that depend on the old functionality. Any page/functionality that relies on one of the following to be `false` can be safely removed. 

- `combined_financial_status_report_enhancements`
- `financial_status_report_streamlined_waiver`
- `financial_status_report_streamlined_waiver_assets`

## Tasks
- [ ] Find and remove any deprecated pages
- [ ] Find and remove any deprecated functionality specific to this chapter 
- [ ] Disable any previous form version tests impacted by this removal

## Acceptance criteria

- [ ] Household Income chapter is clean of deprecated form version code
- [ ] Current pages/version of the form is unaffected by these changes

## Testing
- [ ] Confirm current form version is unaffected regardless of feature flag status (should be hard coded until complete removal)

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Currently blocked, waiting on[ this PR to clean up feature flags](https://github.com/department-of-veterans-affairs/vets-website/pull/28078)

**Comment by Dr-Pongo** [comment]
This was blocked by the feature flag PR listed in a previous comment, but it's ready to go now! Still 3 points remaining!
