### ISSUE TITLE
[FSR] Remove deprecated code form previous form versions Household Assets Chapter

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#76017]
## Description
Find and remove any deprecated code from the Household Assets Chapter. 

We are working to deprecate the following feature flags now that the features are stable, and there are no more in progress forms that depend on the old functionality. Any page/functionality that relies on one of the following to be `false` can be safely removed. 

- `combined_financial_status_report_enhancements`
- `financial_status_report_streamlined_waiver`
- `financial_status_report_streamlined_waiver_assets`

## Tasks
- [x] Find and remove any deprecated pages
- [x] Find and remove any deprecated functionality specific to this chapter 
- [x] Disable any previous form version tests impacted by this removal

## Acceptance criteria

- [x] Household Assets chapter is clean of deprecated form version code
- [x] Current pages/version of the form is unaffected by these changes

## Testing
- [x] Confirm current form version is unaffected regardless of feature flag status (should be hard coded until complete removal)

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
PR https://github.com/department-of-veterans-affairs/vets-website/pull/28453
