### ISSUE TITLE
[FSR] Update FSR e2e tests AFTER code cleanup

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#76024]
## Description
Let's make sure our e2e tests are truly exhaustive after the removal of deprecated code and make sure there's no lurking form data structures from previous versions in our maximals/minimals. 

## Tasks
- [x] Confirm e2e tests run through each page and functionality 
- [x] Cleanup/confirm all deprecated form data structures have been removed 
- [x] Create any follow on tickets if the effort snowballs too much. 

## Acceptance criteria

- [x] FSR tests are free and clear of any previous version structures/functionality
- [x] All e2e tests are passing and happy
- [ ] Any additional tickets have been created 

## Testing
- [x] Do all the testing
- [x] But also confirm e2e tests are passing and there's no old flakey ones being skipped
- [ ] 
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
These changes have been merged and are good to go!
