### ISSUE TITLE
[CAIA A11y Research]: Debt Resolution, Debt Portal (End of Feb./Early March 2024)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#76030]
> [!NOTE]
> **High-Level Overview**: `Debt Resolution Team`
> - **Initial Kickoff**:
> - **Research Timeframe**: 2/21/2024  to 3/6/2024
> - **Time of Day:** 9 a.m. - 2 p.m. PT; and 10 a.m.- 2 p.m. PT
> - **Pilot**:  2/20/2024 at 1 p.m. ET with @eli-oat 
> - **Assistive Tech Users**: `ONLY 3` AT Users
> - **Artifacts Available**: `2/13/2024` in Figma
> - **Testing Environment:** `TBD` Figma?
> - **Assistive Tech Being Used**: Screen Readers; `Types - TBD`
> - **Task Lists**: See task lists for next steps/definition of done

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- @coforma-jamie
- @SarahKay8 
- @eli-oat (pilot)
- @sara-amanda 

</details>

## About the Team

<details><summary>Toggle to view information about the team.</summary>

- Team name: Debt Resolution
- OCTO-DE product owner: Denise Coveyduc
- Delivery manager: Heather Rienks
- Product manager: Tom Davis
- Researcher: Charlotte Cesana
- Designer/Researcher: Megan Gayle
- Designer: Joe Lee
- FE engineers: Andrew Rodiek, Brandyn Sullins, Aaron Ponce
- BE engineers: Kevin Suarez, Austin Smith
- Product/team Slack channel: #benefits-debt-resolution

### Do you have an accessibility champion?

No, but we are interested in training one!

</details>

<details><summary>Toggle to view more intake research ticket information</summary>

### Calendar checking

- [ ] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [ ] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

### When is the timeframe for your testing?

- 2/21 - 3/6 - Study can begin Wednesday 2/21.     
- 9am PT - 2pm PT: Tuesday, Wednesday  
- 10am PT - 2pm PT: Monday, Thursday, Friday  
- 3 max per day

We will only need an accessibility specialist available for three sessions.  

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

<details><summary>Toggle to view research timing information.</summary>

### Timeframe

- **Pilot Session**:`2/20 at 1PM ET`
- **Timeframe**: 2/21/2024 to 3/6/2024 (starting 2/21)

### Length of sessions

- **Session length:** `pending` minutes
- **Buffer time between sessions:** `pending` minutes
- **Maximum sessions per day:** `3`
</details>

###  Testing Schedule

We will only need an accessibility specialist available for `3` sessions.  

<details><summary>Toggle to view the AT testing session details</summary>

The following is the session time window as of 2/15/2024.
- Tuesday, Wednesday: 9 a.m. - 2 p.m. PT
- Monday, Thursday, Friday: 10 a.m. - 2pm PT:  

- Please enter the participants who are using assistive technology in table 1, along with the session times. 
- CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

</details>

#### Table 1: Participants

<details><summary>Toggle to view the AT testing schedule</summary>

P# | Sessions | Time Slots (ET) | CAIA A11ys Available
------------------|------------------|--------------|--------------
Pilot | `Feb` `20`, 2024 |  1 p.m. ET **_Pilot Session_** | @eli-oat 
P1 | `Feb` `21`, 2024 | `2:15PM ET` | @SarahKay8 
P2 | `Feb` `29`, 2024 | `1:00PM ET` | @coforma-jamie 
P3 | `Mar` `1`, 2024 | `3:15PM ET` | @coforma-jamie 

</details>

### Device & AT Combinations

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. Please toggle and use the following table 2, to enter the following information for each participant: Assistive tech, Skill level, Operating system, Browser and Device Type.

#### Table 2: Technology

<details><summary>Toggle to view the device and AT combinations for each participant.</summary>

**Participant Number** | Date of Research | **Assistive Tech** | **Skill Level** | **Operating System** | **Browser** |**Device Type** |
|------------------------|------------------|--------------------|-----------------|----------------------|-------------|-------------|
| _TBD_                   | `MONTH` `DAY`, 2024         | Jaws, NVDA, ZoomText, Dragon, etc.  `TBD`        | Novice, Intermediate or Advanced  `TBD`     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | Desktop, Mobile or Tablet `TBD` |
| _P #_                   | `MONTH` `DAY`, 2024        | Jaws, NVDA, ZoomText, Dragon, etc.  `TBD`        | Novice, Intermediate or Advanced  `TBD`     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | Desktop, Mobile or Tablet `TBD` |
| _P #_                   | `MONTH` `DAY`, 2024        | Jaws, NVDA, ZoomText, Dragon, etc.  `TBD`        | Novice, Intermediate or Advanced  `TBD`     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | Desktop, Mobile or Tablet `TBD` |
| _P #_                   | `MONTH` `DAY`, 2024         | Jaws, NVDA, ZoomText, Dragon, etc.  `TBD`        | Novice, Intermediate or Advanced  `TBD`     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | Desktop, Mobile or Tablet `TBD` |

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

## Supporting artifacts 

<details><summary>Toggle to view the supporting artifacts</summary>

- [Link to prototype for current flow](https://www.figma.com/proto/OiiDTTVTCf8j0GngRg0xxD/Combined-VA-Debt-Portal?type=design&node-id=192-19715&viewport=54,-986,0.25&t=EINFwT8EPigmh19P-0&scaling=min-zoom&starting-point-node-id=192:19715&show-proto-sidebar=1)
- [Link to prototype for revised flow](https://www.figma.com/proto/OiiDTTVTCf8j0GngRg0xxD/Combined-VA-Debt-Portal?type=design&node-id=152-16358&viewport=260,390,0.25&t=EINFwT8EPigmh19P-0&scaling=min-zoom&starting-point-node-id=152:16358&show-proto-sidebar=1)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/exploratory-2024/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/exploratory-2024/conversation-guide.md)
</details>

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket 2/15/2024 (Slack 2/14 at 2:04 p.m. c/o Megan Gayle)
- [x] **INITIAL MEETING:** Schedule meeting with team @coforma-terry - async via ticket
- [ ] **(OPTIONAL) FEEDBACK REQUESTED:** Review Conversation Guide
- [x] **PILOT SESSION: SCHEDULE** Pilot session with team. Tight turnaround/research starts next week - 2/20/2024 at 1 p.m. ET `SCHEDULED`
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76534
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available.
- [x] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean) as of 2/18/2024 only one of the three sessions have been added to the calendar with official invites. Holds are there for the rest.
- [x] **RESEARCH NOTES** Create CAIA notes document `Pending`
- [x] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support. `CAIA Outreach 2/15/2024 via internal Slack` - SK, Jamie and Sara to assist
- [x] **Review research folder and assets**
- [x] **Participate in research**  **Date Span:**`2/21/2024` and `3/6/2024` - `Specific Time Slots TBD`
- [x] **SESSION NOTES**: Create [CAIA notes document](https://docs.google.com/document/d/1wf-Y_dDLsl8g1PngWGCL01c7R-2zZmsOVv3odXGT1rY/edit?usp=sharing) for a11ys to use during the sessions
- [x] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [x] **Create/update the CAIA A11y Research Deliverable** since there was only one participant, we wrote a [comment with our findings](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76030#issuecomment-1971529621)
- [x] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
```

```[tasklist]
### VFS DEBT RESOLUTION TEAM Tasks
- [x] Tag @coforma-terry in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH)
- [ ] Schedule intial meeting with @coforma-terry and @sara-amanda
- [x] Schedule a pilot session with CAIA a11ys
- [ ] (OPTIONAL) Receive feedback on Conversation Guide for Screen Readers (if requested)
- [ ] **PROTOTYPE:** Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section
- [x] **SPECIFIC TIME SLOTS** See `Table 1` in the ticket above. Please provide ~date range~ and slots for AT sessions being planned.
- [x] CALENDAR: Updated with invites from Perigean 2/21/2024
- [ ] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in `Table 2` in the ticket above.
- [ ] **REVIEW:** [Figma has some documentation](https://help.figma.com/hc/en-us/articles/7810391964695-Accessible-prototypes-in-Figma) about their new, experimental accessibility mode. c/o Eli
- [ ] **INVITES:** Forward invites from Perigean to CAIA A11ys (@sara-amanda  or @coforma-terry)
```

**Comment by sara-amanda** [comment]
# Research Ticket Received

Hi, @mgleo! Just a quick note here to let you know that we received your research ticket.

## Next Steps
- [x] Ticket processed 2/15/2024
- [x] Temporarily, I placed holds on our [CAIA A11y Capacity calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York), for the date spans you provided.

### Initial Questions
- [ ] Do you happen to have **specific time slots** for your dates? I see you are needing support only for three sessions.
- [ ] Do you know the **assistive technology that will be used** in these three sessions? 
- [ ] Would you like to **schedule an initial meeting** with @coforma-terry to discuss your project?
- [ ] Would you like to **schedule a pilot session** to test your product with Assistive Tech, prior to your sessions? 

### Definition of Done
**In the task lists above**, we have outlined the remaining task items, relating to this ticket. 

All the best, 

Sara

cc: @coforma-terry @eli-oat @EvanAtCoforma @SarahKay8 @coforma-jamie

**Comment by coforma-terry** [comment]
Hey @mgleo - just wanting to follow up real quick as I know you're wanting to start your research on the 21st, are you able to answer any of Sara's questions above yet? 

Particularly we're interested in seeing if you are open to running a pilot session sometime before the 21st as we feel this could be hugely beneficial for your research? If so, please let me know asap and we can get this coordinated. Thank you so much! :)

CC: @sara-amanda

**Comment by mgleo** [comment]
Good morning @coforma-jamie and @sara-amanda 

Perigean has confirmed those 3 sessions with participants using screen readers are at these times:

2/21 at 2:15pm ET
2/29 1:00 PM ET
3/1 at 3:15pm ET

Let me know if you have not received invites.

Would any of these times work on Tues, 2/20 for a screen reader pilot?
12pm ET
1pm ET

4:30 ET

Also this is our first time using a Figma prototype, any advice, even async would be helpful: [Link to Figma prototype](https://www.figma.com/proto/OiiDTTVTCf8j0GngRg0xxD/Combined-VA-Debt-Portal?type=design&node-id=152-16358&viewport=463%2C-423%2C0.13&t=myI49v69BQb6stMj-0&scaling=min-zoom&starting-point-node-id=152%3A16358&show-proto-sidebar=1)

cc @charlottecesana

**Comment by coforma-terry** [comment]
Hey @mgleo - @eli-oat is available for a pilot at 1PM ET on the Tuesday - if this works for you, please just send Eli an invitation to the session.

Then @coforma-jamie is available to sit in on your research on the following dates:

- 2/29 at 2:15pm ET
- 3/1 at 3:15pm ET

We're looking at the 2/21 slot now - will update once we have someone. Thanks!

**Comment by mgleo** [comment]
Thanks, just sent an invite to you @eli-oat 

@coforma-jamie I just forwarded the session invites to you. The 2/29 screen reader session is at 1PM, does that still work for you?

cc @charlottecesana

**Comment by coforma-terry** [comment]
Oops, my bad - I should have put 1PM ET for the 2/29 session for Jamie. I believe that's fine, but will just let Jamie confirm.

For the 2/21 session this coming Tuesday at 2:15PM ET - @SarahKay8 will be available to cover that for you.

So just to recap:

**Pilot session:**
2/20 1PM ET - Eli will cover this for you.

**Research Session:**
2/21 at 2:15pm ET - @SarahKay8 will cover.
2/29 1:00 PM ET - @coforma-jamie  will cover.
3/1 at 3:15pm ET - @coforma-jamie will cover.

Thank you!

**Comment by coforma-jamie** [comment]
This is accurate! Thanks @coforma-terry!

**Comment by SarahKay8** [comment]
Hi @mgleo! May I get the invite for 2/21 @ 1pm? Email - Sarah.koomson@oddball.io

**Comment by eli-oat** [comment]
Hey ya'll -- I just got and accepted the invite for the pilot session. @coforma-jamie pointed out that your prototype is in Figma. Figma designs aren't usually screen reader accessible, unless special steps have been taken. 

During our session I can test your current set up to see if it works with VoiceOver and other similar screen readers. 

In the meantime, Figma has some [documentation about their new, experimental accessibility mode.](https://help.figma.com/hc/en-us/articles/7810391964695-Accessible-prototypes-in-Figma)

Feel free to reach me on DSVA slack, too, if you'd like to connect sooner.

**Comment by mgleo** [comment]
Hi @SarahKay8 The session with a participant using a screen reader on 2/21 is at 2:15pm ET, I just fwded you the invite. 

@eli-oat Thank you for the Figma documentation. The good thing about this study is that it is two parts so if screen readers cannot use the prototypes we will at least get feedback from them during the first part of the session where we are not asking them to use a prototype. Obviously, would be great to get their feedback on the second part as well! Looking forward to meeting with you.

**Comment by SarahKay8** [comment]
Hi @mgleo! Here are my findings for **P1 February 21, 2024 at 2:15 p.m. ET SK**

P# February 21, 2024 at 2:15 p.m. ET SK

**Participant Details**
**Skill level of user:** Advanced (User since 2020)
**Assistive Technology being used:** JAWS
**Internet Browser:** Chrome 
**Device Type:** Desktop Windows

### Introduction / Get to know the user
Served and is from Durham, NC. Active duty in Goldsboro. User returned back to civilian life when he retired in June 3, 2021. User is asked to finish this sentence - When I think about a financial hub i expect it to “accurately depict debt and what the debt is for”
User served in Air Force as a boom operator (inflight refueling specialist and had an accident in 2017 retired in June 2021 



Has not been on the VA.gov portal before 

### Assistive technology setup / issues
No issues sharing screen 

**Part 1: To understand the desirability of a holistic financial hub**

User complains that the dollar headers on each card is confusing and “lacks consistency” Dollar amount on copay card is just being read out as a heading with no context of what the amount is for 
Suggested recommendation - add _"for 3 copay bills"_ to dollar amount header to provide additional context for users navigating with a screen reader. 
![5C2663A7-EC7B-4696-BAB9-DDC2DAC96BAD_4_5005_c](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102324990/e4c5868d-6793-4a0a-8bfb-b731ce967f1b)


**Part 2: Immediately actionable feedback for debt portal**
First (current) version
When tabbing to each header “screen reader is saying” article. This is a good reminder to check the underlying structure. We have lots of article tags littered through this page. I wonder how useful/semantic that is from a screenreader standpoint.

JAWS is announcing “article” when tabbing to next header in figma prototype, could be an issue with how figma generates code or how elements are labeled in prototype

Second (new) version

Recommended fix - copy this pattern from FSR in order to provide additional context to users 

![7C6EBEE6-912F-4095-BE68-43EDD6E3A3AD_4_5005_c](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102324990/7cd3b72c-6f51-4464-b08a-12db04830103)


Link to Google Doc -[P1 Findings](
https://docs.google.com/document/d/1wf-Y_dDLsl8g1PngWGCL01c7R-2zZmsOVv3odXGT1rY/edit#heading=h.wd85oaayocpt)

**Comment by coforma-jamie** [comment]
The team had 1 screen reader session; the rest were cancelled because they reached their number of desired participants. Our findings are in the comment above. Thanks everyone!

**Comment by mgleo** [comment]
Thank you for attending the session and for your notes, @SarahKay8! We'll be making fixes to the cards on the debt portal.

@coforma-jamie, today's session has been canceled by the participant and the study will be closed out today. 

Thank you all for your assistance with this.

**Comment by josephrlee** [comment]
@SarahKay8 Thanks for the feedback, our team will spin up a couple of AT tickets to implement these changes!
