### ISSUE TITLE
Analytics for Form 526

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#76058]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez)

## High Level User Story/ies
As Product, I need to understand statistics for 526ex form submission and how long it takes to complete different parts of the form to inform and prioritize work around making the submission faster, easier and more accurate.

## Hypothesis or Bet
**If we understand how long the submission takes today, we can create better goals for improvement.
**If we understand how long the different stages in submission takes today, we can co-relate/validate that with our research outcome and focus our efforts where we may get the highest reduction in time

## OKR
_Which Objective / Key Result does this epic push forward?_

## Tasks
- [ ] - Figure out if and what is being tracked for 526ez submission today
- [ ] - Analyze the stats for information
- [ ] - Identify what else should be tracked for the information we need
- [ ] - Add those items to be tracked
- [ ] - Analyze the additional stats for more information

## Definition of Done
- [ ] Reviewed the existing tracking for form 526 ez
- [ ] Identified and added other points in flow to be tracked
- [ ] Reviewed new stats for information around speed and accuracy 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
