### ISSUE TITLE
Discovery: Some flashes not being sent to VBMS from va.gov

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#76051]
## Issue Description
It’s been reported that some flashes and/or special issues applied when claims are submitted by mail are not being applied to claims submitted via va.gov.  Below are the special and flashes and issues that are currently applied by mail automation; can you please confirm which of these we should expect to be applied (when applicable) when applications are submitted via va.gov?

**Special Issue Categories:**
Amyotrophic Lateral Sclerosis (ALS) [being sent]
Military Sexual Trauma (MST) [being sent]
Traumatic Brain Injury
C-123
Fully Developed Claim
Mustard Gas
Standard Processing Claim
PACT (PACT ACT)

**Flashes:**
Amyotrophic Lateral Sclerosis
Hardship
Homeless
If Homeless and Hardship are selected on 526EZ, only Homeless needs to be created
POW
Purple Heart
Terminally Ill
Medal of Honor
Death In Service
Emergency Care
Foreign Claim
 
**Flashes for BDD:**
GWOT Active Duty DoD
GWOT Active Duty Veteran Provided
GWOT Guard/Reserve DoD
GWOT Guard/Reserve DoD Veteran Provided

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Identify why these flashes are not reaching BGS/VBMS
- [ ] Fix the problem, if possible. If not, propose next steps to fix it.

### Findings: 
**A list of the flashes we attempt to set in the logic, and under which circumstances:**
- 'Homeless'
- 'Terminally Ill'
- 'Priority Processing - Veteran over age 85'
- 'POW'

**A list of the special issues defined in vets-json-schema under Rated Disabilities that COULD be sent from VA.gov to VBMS**
-     "ALS", 
-     "HEPC",
-     "POW", (the ONLY special issue currently set from VA.gov for new disabilities)
-     "PTSD/1",
-     "PTSD/2",
-     "PTSD/3",
-     "PTSD/4",
-     "MST",
-     "RRD"

EVSS only recognizes these special issues: ALS, HEPC, POW, PTSD_1, PTSD_2, PTSD_4, GWPAH, RRD and PACT. EMP is planned. (Not sure if the underscore for PTSD makes a difference versus a slash that the frontend sets now.)

For future RD migration, note that Lighthouse can accept special issues in V1 but not in V2. 

VA.gov is not determining special issues from any sort of data sent to third-parties. If that needs to change, we need to know because it'll take time for our vets-api mapper and for Lighthouse to support this. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tommasina-va** [comment]
Just noting that Emily recommended the definition of done of a ticket like this to be:

- a list of the special issues/flashes we attempt to set in the logic, and under which circumstances

- confirmation in staging end to end test (or by looking at a recent production example) whether those flashes are making it to VBMS.

**Comment by tommasina-va** [comment]
Noting that we're waiting on David Reis to help us look into flashes in Production. We did not see any issues with flashes making it into Staging VBMS. https://dsva.slack.com/archives/C04KW0B46N5/p1708547232361399

**Comment by zachgoldfine44** [comment]
Looks like the EVSS service used by VA.gov for 526 submissions restricts special issues to the list in [this thread](https://dsva.slack.com/archives/C1VBAHWQL/p1708026532007739?thread_ts=1708023898.273619&cid=C1VBAHWQL)

**Comment by zachgoldfine44** [comment]
Looks like the EVSS service used by VA.gov for 526 submissions restricts special issues to the list in [this thread](https://dsva.slack.com/archives/C1VBAHWQL/p1708026532007739?thread_ts=1708023898.273619&cid=C1VBAHWQL)

**Comment by tommasina-va** [comment]
Findings: we did not find any special issues sent from VA.gov in the last 90 days in production. We were expecting to see at least the POW special issue. More testing and discovery will be documented on this ticket: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/77175

**Comment by sethdarragile6** [comment]
@RakshindaAslam I think we already answered this on Slack, but just in case the answer is: yes. In other words, both. Yesterday I confirmed in production that the POW special issue submission I identified also sent a POW flash.
