### ISSUE TITLE
[FSR] Update FSR transform to remove deprecated calculations/functionality 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#76052]
## Description
We are working to deprecate the following feature flags now that the features are stable, and there are no more in progress forms that depend on the old functionality. Any functionality in the transform that relies on one of the following to be `false` can be safely removed. 

- `combined_financial_status_report_enhancements`
- `financial_status_report_streamlined_waiver`
- `financial_status_report_streamlined_waiver_assets`

## Tasks
- [x] Remove deprecated functionality from transform and helplers
- [x] Confirm existing functionality is unaffected
- [x] Update/remove unit tests affected by deprecation
- [x] Create any follow on tickets if the effort snowballs too much. 

## Acceptance criteria

- [x] FSR tests are free and clear of any previous version structures/functionality
- [x] All e2e tests are passing and happy
- [x] Any additional tickets have been created 

## Testing
- [x] Do all the testing
- [x] But also confirm e2e tests are passing and there's no old flakey ones being skipped
- [x] Confirm unit tests are passing and happy

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
In this PR we will focus on just removing the old tests that need to go, we will RENAME efsr- prefaced tests to not have the prefix in a separate PR. Doing them in the same PR will cause a weird looking git history that will make it very hard to review. Multi stage process is the way to go per convo with Andrew!
