### ISSUE TITLE
[CST] Remove Primary Alert from Overview Tab

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#76053]
## Value Statement
Users shouldn't see the primary alert on the Overview Tab as it has been replaced with a different alert that shows on the Status Tab

<img width="1354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3RVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6290988020b8e0a8e91f05e65deb065c43f94c15/Screenshot%202024-02-13%20at%2010.25.07%E2%80%AFAM.png" alt="Screenshot 2024-02-13 at 10.25.07 AM.png" />

---
### Bug
- Users should not see primary alerts on the Overview Tab

## Engineering 
- On `src/applications/claims-status/containers/OverviewPage.jsx` we will want to remove the component `NeedFilesFromYou`

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] Remove the primary alert from the overview tab

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Product performs functional QA and verifies acceptance criteria was met
- [ ] Engineering identifies staging users required to test and shares account and credentials with product

## Acceptance Criteria
- [x] The overview tab does not display primary alerts

**Comment by pmclaren19** [comment]
@skylerschain @jacobworrell this ticket is ready for Validation and Design QA.

**Comment by SilkeDannVA** [comment]
@skylerschain @jacobworrell , any update on this?
