### ISSUE TITLE
Update search result headings

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76059]
## Background
An accessibility check flagged the search result headings as confusing.  Right now, the heading structure is:

- H2 - Your search results
- H2 - We're updating our search tool
   - H3 - [person's name]

The person's name is listed under "We're updating our search tool," not "Your search results"!

This heading structure would make the heading associations clear:

- H2 - Your search results
   - H3 - We're updating our search results
   - H3 - [person's name]
   
Additionally, the search results header shouldn't be a real header.

## Tasks
- [ ] Please change "We're updating our search tool" to an `<H3>`. 
- [ ] The search results header "Showing 1-10" shouldn't be a true heading, please make it a `<p>` or similar. 

## Acceptance Criteria
- [ ] Headings in the search results are updated to provide a better a11y experience

**Comment by oddball-lindsay** [comment]
Duplicate
