### ISSUE TITLE
Discovery - analytics data for Benefits Disability Experience

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#76054]
### Issue Description

Understand how we can get clear analytics data that we can use to inform product & design decisions. We have [Domo and Google Analytics](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights), with funnels and various metrics defined in Domo. However, in some [investigation that Team 2 did in the Single Source of Truth Google Doc](https://docs.google.com/document/d/19Cfs8L1SmUaRUsWbOF35Y0BUsYz_c-QtlIltO6LEp3Y/edit), we realized that the data coming in does not make sense - for example, metrics that together should add up to 100% are not adding up to 100%. 

### Tasks
- [x] Define the MVP metrics we want to have available and correct (we already have a start on this from the [Single Source of Truth Google Doc](https://docs.google.com/document/d/19Cfs8L1SmUaRUsWbOF35Y0BUsYz_c-QtlIltO6LEp3Y/edit))
- [ ] Investigate the data coming into Domo - can it be corrected to make sense?
- [x] Investigate configuring other existing tools in our ecosystem (like Google Analytics) to capture the data we want
- [x] If this ends up being something we do at the team level rather than the Platform level, share our approach with other teams so that they can use it **shared and built with other teams working on the 526**

### Acceptance Criteria
- [x] MVP metrics defined
- [x] An approach defined to get corrected data
- [ ] Tickets created to correct the data (if needed)
- [ ] Approach shared with other teams (if the solution is not done Platform-wide)

**Comment by evelynhilbrichdavis** [comment]
["Want to know" analytics github page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/analytics/want-to-know.md) from the start of contract

**Comment by evelynhilbrichdavis** [comment]
Analytics Office Hours are Tues/Thurs 3:30-4pm. Will attend Tuesday!

**Comment by evelynhilbrichdavis** [comment]
@mengA6 Here is the documentation I've been creating that is largely synthesis of slack threads, google docs, etc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/analytics/MVP-Metrics-526.md

**Comment by evelynhilbrichdavis** [comment]
This work will carry into the next sprint. I will need to consult other researchers on the 526 (scheduled) and attend Office Hours again tomorrow before having a sense of approaches to correcting the data.

**Comment by evelynhilbrichdavis** [comment]
After conversations with Analytics and Insights Team, Contention Classification, and DBEX 2, we learned that achieving the results identified in this [MVP Metrics document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/analytics/MVP-Metrics-526.md) will not be a straightforward result from a single Office Hours conversation. 

Below are two possible approaches to improving our analytics capabilities. Further conversation is necessary to pick an approach based on bandwidth and desired outcomes. 

**Approach 1:** 
Create a new funnel that only includes pages that are seen by every user going through the flow (need to ask Analytics Team if this is done in Domo or GA. Drill down into exit rates for individual pages using CC Team’s method (using unique page views and previous page visited)
Outcome: Reliable exit rates (at a high level and then on page-by-page basis)
-Could start with most highly trafficked pages (or the area of our prioritization) 
Drawbacks: Highly manual + spend a lot of time setting up before migration to GA4

**Approach 2:** 
Work with Analytics and Insights Team to better understand existing metrics and find middle ground on our/their terms. This could include…
Pushing back against Platform/Domo definitions to try to align the numbers with the variables we want to use
Advocate for the team to build a custom edge use case  dashboard for 526 that could hypothetically be more tailored for the complexity and conditional logic of our form
Reorient our discovery to answer questions, rather than centering metrics. Go to Analytics Team with questions, then have them show us how to get the best answers OR help them change language in our dashboard to match our mental models (and MVP metric definitions) for what is happening. 
Outcome: Vary on intervention, but overall move towards finding shared understanding in numbers, even if we can’t get them to do exactly what we want.  
Drawbacks: Analytics Team has limited time as they manage other priorities.
