### ISSUE TITLE
Add insurance PDF to welcome kit page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#76064]
## Issue Description
VEO asked us to add the Getting started with your VA life insurance PDF to the [Welcome kit](https://www.va.gov/welcome-kit/) page. They've uploaded the PDF to the outreach library.

## Tasks
- [x] Add PDF to page (Randi)
- [x] Review (Megan)
- [x] Publish (Megan)
- [x] Notify stakeholder that changes are live (Randi)

## Acceptance Criteria
- [x] PDF is live on the page

**Comment by RLHecht** [comment]
This work is complete. FYSA @strelichl
