### ISSUE TITLE
Update GA Implementation Requests Template for GA4

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#76076]
### Description:
We will need to update our [analytics implementation request template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&projects=&template=analytics-google-analytics-implementation-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) as part of the move to GA4. 

### Tasks

- [ ] Determine requirements for updates
- [ ] Make updates to template
- [ ] Confirm updates are going through

### Acceptance Criteria

- [ ] Template has been updated with new GA4 relevant-infromation
- [ ] x
- [ ] x

**Comment by johnny-jesensky-adhoc** [comment]
After reviewing our Github request form in more detail -- won't need any changes for GA4 specifically. Might look to revisit as part of a larger forms audit after the GA4 migration -- closing this for now.
