### ISSUE TITLE
Facility Locators Dashboard: Final Data Load

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#76077]
### Description
Follow-up on Facility Locator Edge Case dashboard, to add additional chart types, and work with their team to add additional tracking fields in GA.

### Tasks

- [x] Load data to include all of 2023.
- [x] Load most recent data, for 2024.
- [x] Schedule recurring data load so dashboard remains up to date.
- [x] Remove/hide the _Facilities No Results Found_ chart
- [x] Send Michelle a message letting team know the dashboard is ready to be used.
---
### Acceptance Criteria

- [x] 2023 data has been loaded 
- [x] Data refresh cycle has been set-up

**Comment by johnny-jesensky-adhoc** [comment]
I built out this final ticket for the Facility Locators edge case dashboard we have been iterating through. The primary tasks here are around loading data back to beginning of 2023, and scheduling a recurring data refresh. and two - looking into needed tracking for no results found, and a search by facility type.

FYI @dorseypa1, @Blivaditis, @ChristineYoungZA
