### ISSUE TITLE
[CDP] VHA Payment History mock ups

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#76090]
## Description

In July, we will have the following information available for VHA:

**Payment information on medical copay**– (Understanding of when Veteran makes a payment (incremental or full) on medical copay
**Status of a medical copay debt** – (Understanding when a debt has been suspended/ referred to treasury/ put on a repayment plan)

For reference:
[Medallia Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_fsr/research/medallia_reports)
[Debt Portal Comparative Analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/research/comparative-analysis/debt-portal-comparative-analysis-12-2023.md)

## Tasks
- [x] Identify pages where payment history can be implemented
- [ ] Update mockups

## Acceptance criteria

- [ ] Pages on Figma are updated with payment information

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
This ticket will roll over again- need more information from SME's
-4/11/24- Meeting set up with VHA
-After 4/22 we will meet with VBA

**Comment by mgleo** [comment]
Rolling over as we are still reviewing the Data dictionary #82134

**Comment by HeatherRienks** [comment]
Closing this ticket as we will be focusing on VBA MVP as our first priority. Time spent on VHA efforts will be logged each Sprint in a "VHA Sprint xx" ticket
