### ISSUE TITLE
NOD | Complete E2E testing in production environment

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#76108]
## Value Statement
**_As a_** Veteran submitting an NOD with a request for extension caused by the infinite loop bug
**_I want to_** resubmit my appeal with confidence that the data is share will be received
**_So that_** I can adjudicate my claim decision.

---
## Test Notes and Links
This will be a friends and family test, with Veterans on the OCTO space.

See [NOD dashboard](https://vagov.ddog-gov.com/dashboard/tvp-imf-tb7/benefits-notice-of-disagreement?refresh_mode=sliding&view=spans&from_ts=1707845024385&to_ts=1708449824385&live=true), which now includes a section distinguishing between NOD v1 and v2 form and evidence submissions.

## Tasks
- [x] @saderagsdale Recruit testers with properly configured data (e.g. contestable issues)
- [x] @Mottie Whitelist testers in production
- [x] @saderagsdale Schedule testing session with the team
- [x] @rocio-desantiago @Mottie Check the forms in production (all required browsers and devices)
- [x] @saderagsdale Kickoff comms with Lighthouse, Centralized Mail Portal, Data Dimensions, Doma, and Board of Veterans Appeals
- [x] @saderagsdale @anniebtran Confirm how LH, CMP, BVA, will pass test results back
- [x] Go through test cases, check for these:
     - [x] @Mottie Generate errors on each step of the form to confirm they are logged in production DD instance
     - [x] @anniebtran document pass/fail criteria for each test case
     - [x] @data-doge Confirm that backend monitoring works (linked above), including: v1/v2 monitor, submission failure monitor, and others outlined in the [draft release plan](https://docs.google.com/document/d/1D6xga79F1_s3u5hgTUo1jJi0obiXpvL6THbhIIxRb50/edit)
     - [x] @saderagsdale Confirm test memos are added to eFolders for Robin, Rocio, and Joe

## Out of scope
- Code work for upstream evidence failures

## Definition of Ready 
- [ ] The feature satisfies all functional requirements
- [ ] The feature code is integrated into the lower environment
- [ ] Unit tests and component tests for the feature have been executed and passed
- [ ] Production test environment is configured to simulate the production environment as closely as possible
- [ ] Test data for the E2E tests have been prepared to cover various scenarios
- [ ] External systems that the feature relies on are configured in the production environment
- [ ] Test users for each test case are ready
- [ ] Test plan approved by involved teams and stakeholders
- [ ] Test documentation is ready for use

## Definition of Done
- [x] E2E test scripts are executed to verify the end-to-end functionality of the feature
- [x] The E2E tests meet the predefined passing criteria
- [x] Integration points with other systems or components are validated
- [x] Defects identified during E2E testing are addressed
- [x] E2E testing documentation, including test cases and results, is updated
- [x] Any test artifacts and data are cleaned up from the production test environment
- [x] Logs are ready, including #75546 
- [x] Test team signs off on the test phase
- [x] OCTO signs off on the test phase

**Comment by HeatherWidmont** [comment]
Will not be estimated

**Comment by HeatherWidmont** [comment]
Sade asked VBA what they need for the production test, waiting to hear back.

**Comment by saderagsdale** [comment]
Asked Zach to nudge BVA.

**Comment by saderagsdale** [comment]
@rocio-desantiago @Mottie @data-doge @anniebtran 

- All test date entered will only say "test"
- Do not choose real issues
- All pdfs will be labeled test (can include the type of validation being tested)
- pdfs cannot include any real data

**Comment by saderagsdale** [comment]
Asked Zach to nudge Tim Wagner.

**Comment by saderagsdale** [comment]
I sent an email to BVA again and asked the enablement folks to chime in w/ ideas.

**Comment by HeatherWidmont** [comment]
Recurring meetings scheduled in the afternoons this week to talk to other testers. We will likely go to production this week
