### ISSUE TITLE
Document how/where to update text of Experience Standards and descriptive tags

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#76106]
## User Story
_As a Governance Team member, I want to ensure that there is a clear way to add or update descriptive tags for use on Staging Review findings as our guidance in the Design System matures._

Assignee: @erinrwhite 
Peer Reviewer: @rferguson13 

## Description

With our new Experience Standards initiative, we will be adding/updating descriptive tags we apply to our Staging Review findings as new things are added to the Design System, Content Style Guide, and WCAG; as links are updated, etc. We should document how to make those updates, including which files need to be updated (Drafting Template, DST drafting template, any others?) and how. 

The current [VA.gov Experience Standards page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) on Confluence lists each place where the Experience Standards can be found. We recommend updating this page to include information about descriptive tags as well: where they are found, and how to update them.

This ticket is similar to #32362 but narrower, not addressing the larger process the Governance Team would need to undertake to evaluate, edit, add or remove Experience Standards. This ticket will only address how to make edits to the relevant files to ensure consistency.

## Impacted Artifacts

 - [VA.gov Experience Standards page on Confluence](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards)
 - Drafting Template?
 - Design System Drafting Template?

## Tasks
- [ ] Update [VA.gov Experience Standards page on Confluence](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) to add a section about adding/updating descriptive tags

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have documented operational guidance for Governance to follow if/when changes are made to the VA.gov Experience Standards and/or descriptive tags

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@erinrwhite this looks good. I added Acceptance Criteria. Let's discuss at refinement later today.

**Comment by erinrwhite** [comment]
@rferguson13 I have made some tentative, very awkwardly worded and perhaps overly detailed edits to the [confluence page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) -  your review is very welcome. Feel free to make edits directly, and/or if it's too much of a mess you can just tell me 😂

**Comment by rferguson13** [comment]
@erinrwhite Overall, this looks good! Made some minor changes and some suggestions.

**Comment by erinrwhite** [comment]
@rferguson13 thank you! I made the edits you suggested and tagged you in one follow-up comment. Ready for your next round (final?) review.

**Comment by rferguson13** [comment]
@erinrwhite Looks good to me! The changes you made make sense.

**Comment by erinrwhite** [comment]
Thank you @rferguson13 ! Closing.

**Comment by erinrwhite** [comment]
[Updated the doc today](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) following work on #76875 to add even more details, including how to delete descriptive tags.
