### ISSUE TITLE
Update Stats D page re: Prometheus and Grafana

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#76120]
## Issue Description
This is a ticket for the Platform Content team that needs to be complete by the end of the Sprint. Please review the details here, ticket [75650](https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/issues/gh/department-of-veterans-affairs/va.gov-team/75650)

---
## Tasks
- [ ] Confirm with @jknipes who Point of Contact is at the Content team
- [ ] Confirm with PoC the content that is to be updated is finalized
- [ ] Backend SME Reviews [page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847017/StatsD+Metrics)
- [ ] Content Team Update page and links as advised
- [ ] Confirm update with Clint Little

## Acceptance Criteria
- [ ] Page updated and ready for deployment on Platform Website
