### ISSUE TITLE
Identify or create local test users for scheduling workflow

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#76136]
## Issue Description
Search the existing VetsAPI mockdata and documentation to figure out if there is a local user that contains all of the necessary information to test the scheudling workflow.  If there is not, figure out what is needed to add them and begin the process.

---
## Tasks
- [ ] Search for a local mock user that has appointments and can be scheduled
- [ ] If no user is found, research the documentation and existing Github issues to determine how to get data added

## Acceptance Criteria
- [ ] One or more local users exist that can be used to test scheduling workflows
