### ISSUE TITLE
GA4: UA vs. GA4, (Key Differences)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#76131]
### Description
It will be important for teams to understand the core differences in functionality between UA and GA4, to prepare them for a post-GA4 world.

This ticket is to establish a demo for VFS Teams to show core differences in reporting, and things they can expect to see differently in the GA4 world.

---

### Tasks

- [ ] Prepare a list of topics to cover.
- [ ] Review breakout of topics.
- [ ] Repurpose one of our _Office Hours_ slots to serve as the _GA4 - What You Need to Know_
- [ ] Record meeting
- [ ] Share recording in the _#vfs-analytics_ Slack channel
- [ ] If needed, schedule a part 2

### Acceptance Criteria

- [ ] Meeting has been scheduled
- [ ] Meeting has been hosted

**Comment by johnny-jesensky-adhoc** [comment]
This will likely be covered as part of our GA4 training resources -- not need as it's own ticket. Closing.
