### ISSUE TITLE
Ticket for ticket making! 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#76147]
## Description
Carving out some time for ticket creation for the super epic: 
**[Portal PI1/24] Portal Overall FE/BE Logic Shift and Code Cleanup** [#75716](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75716)

Outline of the ticket ideas so far can be found in [the FE priorities tab here](https://docs.google.com/spreadsheets/d/1PjpLz_ywN7-Rx3CpQvvkJy_UADNv8gOc/edit#gid=1759466832). Let's get at least shell tickets created and we can refine them further once we have a more clear vision. 

## Tasks
- [x] Create tickets under [[Portal - PI1/24] Portal Overall FE/BE Logic Shift - Tech Discovery #75729](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75729)
- [ ] Create tickets under [[Portal - PI1/24] Portal Overall FE/BE Logic Shift #75735](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75735)
- [ ] Create tickets under [[Portal - PI1/24] Portal Overall Post Logic Shift Code Cleanup #75740](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75740)

## Acceptance criteria

- [x] Tickets created for [Portal - PI1/24] Portal Overall FE/BE Logic Shift - Tech Discovery [#75729](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75729)
- [ ] Tickets created for [Portal - PI1/24] Portal Overall FE/BE Logic Shift [#75735](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75735)
- [ ] Tickets created for [Portal - PI1/24] Portal Overall Post Logic Shift Code Cleanup [#75740](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75740)

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
