### ISSUE TITLE
[FE] Dot Indicator Research: Update prototype to include slim alert banner

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#76142]
## Background
After further investigation into the slim alert banner we decided it made sense to incorporate it into our upcoming study around the use of the dot indicator and badge on My VA.

## Tasks
- [x] Update prototype to include scenarios for the slim alert banner 
- [x] Review with Matt
- [x] Conduct internal walk-through

## Acceptance Criteria
- Prototype is updated to include slim alert banner

## Validation
- Matt to review prototype with Allison to confirm it meets needs of the study

**Comment by allisonlu** [comment]
My VA with a slim alert banner prototype ready for validation! This has been added to the [My VA collection](https://codepen.io/collection/oEmrJy) as well.

[https://codepen.io/allisonlu/full/NWJeYaV](https://codepen.io/allisonlu/full/NWJeYaV)

**Comment by allisonlu** [comment]
almost done with fixing the mobile menu, but i'll keep this at 2 points for sprint 31, in case we need to make any more updates
