### ISSUE TITLE
Draft content for pension reactivation email

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#76153]
## Issue Description

From Vicky Bellissimo, PM:
> We'd like your support to create an email that will be sent to veterans who had an in-progress form at the time the online Pension form was deactivated in November 2023. Now that the form is being released to a certain percentage of traffic, we'd like to prepare an email that will let them know that the online form is again. 
> [See launch release schedule in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?wid=0-1704481087285&sender=u9d01ee38af217e4877e75660).

We won't need a kickoff for this, but please let me know if any other touchpoint would be helpful.

---
## Tasks
- [x] Draft email (Katherine)
- [x] Review (A)
- [x] Share with stakeholder (Katherine)

## Acceptance Criteria
- [x] Content provided to stakeholder
---

**Comment by katherine-fung** [comment]
Hi @aprocik1, 

I've drafted this email for now, but waiting for the pension PM and OCTO design lead to confirm the CTA should be something like "Continue your online application for VA pension benefits." 

The context is that on November 8 2023, the product team took the pension form down and emailed the Veterans who had in-progress forms to say you can't apply online for the next few months. When the team releases the new form to 100% of users in a few weeks, they want to email all those folks to let them know the form is back up again. 

I've drafted the email copy based on the new copy we're using on the "How to apply" page (it's the "We updated our online pension form" info alert on this page: https://staging.va.gov/pension/how-to-apply/) 

Here's a screenshot of the draft for your review: 

![Screenshot (428)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/105367381/af1c7f81-8e87-4d4c-8057-2faa3105c163)

For reference, here's the ticket for the November email where we told Veterans the form isn't available (scroll to the bottom for the email copy): https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/62878

**Comment by aprocik1** [comment]
@katherine-fung, this email is good! Thanks for sharing context and relevant links.

I just want to confirm my understanding of the logistics: I think VA.gov typically saves in-progress forms for 60 days. Please correct me if I'm wrong! I'm assuming this is an exemption to that. Will all Veterans with in-progress forms started or edited within 60 days prior to November 8, 2023 receive this message?

**Comment by katherine-fung** [comment]
@aprocik1, 

Anyone who had a saved pension form as of November 8, 2023 will receive this message. 

Previously, your pension form would expire 60 days from the last time you updated it. But the engineering team has made a change, so that if you had a saved form as of November 8, 2023, your form will expire 1 year from the date which you started it. (I'm not sure what this means for folks who may have started the form more than a year ago and maybe kept updating it every 59 days for example - I'm not sure if there are any users who fit that scenario in the system).

**Comment by katherine-fung** [comment]
I provided the email copy to the product team for review in the [CAIA intake ticket](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/14?pane=issue&itemId=53017942).

**Comment by katherine-fung** [comment]
re-opening this ticket because the pension team had feedback to incorporate. 

Slack thread of feedback: https://app.slack.com/client/T03FECE8V/C06E83RNLQM

I'm sharing this updated copy with them. 

<img width="992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTJOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ae010ecacc5bbb4644388b6cac7208f4eaee058/Screenshot%20%28432%29.png" alt="Screenshot (432).png" />

**Comment by katherine-fung** [comment]
I provided the content to the product team in ticket #75872.
