### ISSUE TITLE
EVSS PCIU Migration: Step 6c: Remove PCIU from mockdata repo and betamocks in vets-api

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#76167]
## User Story
As a developer, I want to remove all references of PCIU to ensure Vets-API does not use PCIU, as we transition to VA Profile in preparation for the PCIU deprecation

## Issue Description
PCIU has been deprecated from vets-api and needs to be removed from [vets-api-mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata). Excluding `mock_data_table.md` (which is generated automatically), there are >50 instances of `pciu` in the mockdata repo. 

## Tasks
- [x] Remove `pciu` instances from [make_table.rb](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/make_table.rb)
- [x] Remove `evss/pciu*` files. This includes [pciu and pciu address here](https://github.com/department-of-veterans-affairs/vets-api-mockdata/tree/master/evss)
- [x] Remove any other PCIU instances.
- [x] [Update the mock data table](https://github.com/department-of-veterans-affairs/vets-api-mockdata?tab=readme-ov-file#update-the-mock-data-table).
- [x] Remove from betamocks. Can use [this draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19551) (work moved from [76167](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76167) to this ticket)
    - [x] [config/initializers/breakers.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/breakers.rb#L55)
    - [x] [docs/setup/betamocks.md](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/betamocks.md)

## Acceptance Criteria
- [x] PCIU is not longer referenced in the mockdata repo
- [x] Mockdata table is updated
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/19551 is merged
---

## Validation
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/19551 is merged and deployed.
- [x] https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/575 is merged and deployed.

**Comment by jennb33** [comment]
Per @RachalCassity, she has been working with Seth Darr. PCIU calls have been removed and implementation has been held up. Disability Benefits team is focused on the the 526 form, and it doesn't appear that we are overlapping.

**Comment by RachalCassity** [comment]
@jennb33 Moving this back to the backlog. Waiting for Benefits team to update all PCIU. This service is still being used, https://vagov.ddog-gov.com/metric/explorer?fromUser=false&start=1710951220628&end=1710954820628&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYAMwGIFCeGE4a+NoAxkrIIOoIulmWgWZxyhgAbjDIlYgaThjyEAB0GgieGlAtTRBOcMQIOpFoTlwI8k5GQe1OAKIAagDKS04ACgDCAJIAqgCCUFB2DRp4WTkaGsAAVDw9DVn4IggAFACUIDwAulSu7niYULhP6qAEYGJlBKfH4gdpYNC5UDyDAIhBDZRQHAwJxZQEaCBZJJoURwJxyRTKDLEqBEklOehMZQiNweNCffgQeyYLBkhS5EDEkRKb48Piw+TEhAbKTCGAoEQAtA8IA.

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note**: The dev. was on support during the current sprint, and did not have time to circle back to this work. This ticket will rollover to Sprint 16.

**Comment by rmtolmach** [comment]
I unlinked Ryan's work and added it to #73776. This ticket is for mockdata now.

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** The steps related to removing PCIU was regrouped with the lens of prefill & non-prefill work. THis new grouping will also allow more developers to work on the tickets simultaneously. As a result, the previously linked PR is no longer related to this work and the ticket description has been updated. This ticket will roll over to Sprint 18.

**Comment by rmtolmach** [comment]
>  Remove any other PCIU instances.

The remaining `pciu` references are `set-cookie: wss-pciu-services...` in four `evss/disability_form` yaml files. I think these are okay to leave since they're mocked responses.

Mockdata repo PR: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/575

**Comment by rmtolmach** [comment]
@AshleyGuerrant I removed the `blocked` label because 
1) The vets-api PR was only a documentation update.
2) The mockdata PR changes were non-breaking. Rachal showed me how to test, so we were confident merging wouldn't break anything. 

Moving this into Review.

**Comment by rmtolmach** [comment]
Reviewed by Rachal. Closing 🎉
