### ISSUE TITLE
EVSS PCIU Migration: Step 6 (a): Remove PCIU references from pre-fill

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#76168]
## User Story
As a developer, I want to remove PCIU, so that PCIU is completely removed from pre-fill..

## Issue Description

The EVSS PCIU service is no longer in use and its references within the pre-fill logic need to be removed. This cleanup will streamline the pre-fill process and ensure the codebase reflects the current state of services.

## Tasks
 in the following files:
- [ ] Remove PCIU in app/models/user.rb
- [ ] Remove PCIU in app/models/form_profile.rb
- [ ] Remove PCIU in spec/models/form_profile_spec.rb
- [ ] Remove PCIU in spec/models/user_spec.rb
- [ ] Remove PCIU in app/models/form_profiles/va_526ez.rb
- [ ] Remove flipper references: remove_pciu, :va_v3_contact_information_service, :remove_pciu_2
- [ ] Ensure tests are passing
- [ ] Test locally
- [ ] Test in staging

## Acceptance Criteria
- [ ] PCIU is removed from pre-fill logic

**Comment by LindseySaari** [comment]
@jennb33 After the meeting with Authenticated Experience, it will be a while before we take on this ticket. The migration work will come before this one, so we may want to create a discovery ticket to capture the work we completed this sprint. cc @RachalCassity

**Comment by jennb33** [comment]
7/8 - when these are removed, put them behind a flipper so that we don't lose everything associated upon removal.

**Comment by jwoodman5** [comment]
Testing locally now plus a PR is up for review.
