### ISSUE TITLE
Replace PCIU Email Address Validator

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#76165]
The PCIU Email Address Validator is used in multiple places. This validator should be moved to VAProfile email model.
The following should be moved to VaProfile Email Address
```
    class EmailAddress < BaseModel
      VALID_EMAIL_REGEX = /.+@.+\..+/i

      attribute :email, String

      validates(
        :email,
        presence: true,
        format: { with: VALID_EMAIL_REGEX },
        length: { maximum: 255, minimum: 6 }
      )
    end
```

## Tasks

- [x] Create a VAProfile Email Address Validator to replace EVSS::PCIU::EmailAddress::VALID_EMAIL_REGEX 

Replace the new validator in the following files:
- [x] [PrescriptionPreference](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/prescription_preference.rb)
- [x] [MessagingPreference](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/messaging_preference.rb)
- [x] [Vets360 Email](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/swagger/swagger/schemas/vet360/email.rb)
- [x] [VAProfile: Email](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/swagger/swagger/schemas/vet360/email.rb)

**Comment by jennb33** [comment]
@RachalCassity - should we break this into smaller tickets? @LindseySaari thinks this is a lot of work for 1 ticket, let's discuss.

**Comment by RachalCassity** [comment]
This is creating a email validator and just copying the code into the four files. Should be a 2.

**Comment by jennb33** [comment]
Per @RachalCassity, she has been working with Seth Darr. PCIU calls have been removed and implementation has been held up. Disability Benefits team is focused on the the 526 form, and it doesn't appear that we are overlapping.

**Comment by RachalCassity** [comment]
PCIU email address files will be removed after [Replaced PCIU::VALID_EMAIL_REGEX with VaProfile::VALID_EMAIL_REGEX ](https://github.com/department-of-veterans-affairs/vets-api/pull/16021) is merged
