### ISSUE TITLE
NOD and SC | Max filesize error content updates

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#76161]
## Value Statement
**_As a_** Veteran who has uploaded a large file that exceeds file size limits
**_I want to_** get clear instructions on how to fix the error
**_So that_** I don't get stuck at this step of the form.

---
## Background Context
Previously, there was work done to ensure max [filesize error](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74457) was shown for all files larger than 1000mb. 
This work brought to light that the content could use some clarification. Design (Eileen) collaborated with CAIA to get feedback and what the best message to show the Veteran is.

## Acceptance Criteria
- [ ] When a Veteran uploads a file that is over 100,000,000 bytes, they see the following error: `We couldn't upload your file because it's too large. File size must be less than 100 MB`

## Designs and Build Notes
What we currently have:
![Staging_Error_FIleSize_Mssgs](https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/11d5a5ca-cb83-403d-a0c9-69f3c1d9296b)

## Tasks
- [ ] Update file error message to `We couldn't upload your file because it's too large. File size must be less than 100 MB` for both NOD & SC
- [ ] Confirm same activity in Production due to previously seeing different behavior across local/staging.

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product

**Comment by rocio-desantiago** [comment]
@rocio-desantiago error messages approved by CAIA:

File is too large:
`We couldn’t upload your file because it’s too large. File size must to be less than 100 MB`

File is too small:
If we have to keep the delete file button, use the following:
`We couldn’t upload your file because it’s too small. Please delete this file. Try uploading a file that’s 1KB or more.`

If file is 0KB, is it possibly a blank file? If so, this is more accurate:
`The file you tried to attach is blank. Try attaching a different file.`

_Originally posted by @eileen-coforma in https://github.com/department-of-veterans-affairs/va.gov-team/issues/74457#issuecomment-1936004246_

**Comment by rocio-desantiago** [comment]
Investigating if we can remove enableShortWorkflow. Updated 3 years. May have been a feature flag that was never removed. One message shows up in localhost and the other shows up in Staging/Production.

```
const fileTooBigErrorMessage = enableShortWorkflow
        ? 'We couldn\u2019t upload your file because it\u2019s too large. ' +
          `File size must be less than ${fileSizeText}.`
        : 'We couldn\u2019t upload your file because it\u2019s too large. ' +
          `File size must be less than ${fileSizeText}.`;
```

**Comment by rocio-desantiago** [comment]
Quick pulse check: Are these file error messages meant to be for every form @eileen-coforma or would other forms potentially have different error messages for their users? I'd think we'd want to share error messages but just double checking for sanity.

**Comment by eileen-coforma** [comment]
It should be the same, since it's a generic error message about file size.

**Comment by HeatherWidmont** [comment]
@rocio-desantiago to add screenshots for the errors that show up & then will share with @Mottie to review PR later this week

**Comment by HeatherWidmont** [comment]
Rocio is rerunning some tests, may need to update one

**Comment by rocio-desantiago** [comment]
Okay this is awkward. As I had suspected - not because I clearly understand `enableShortworkflow` or if that's even the culprit of why this happens but a different message is showing up in staging than what I saw locally. @Mottie 👀

**Comment by rocio-desantiago** [comment]
Created new [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28525) to remove feature flag so that error messages do show up in staging/production and so that local environment buttons also match staging/production.

**Comment by rocio-desantiago** [comment]
Monitoring when it's available in staging in order to validate
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/

**Comment by rocio-desantiago** [comment]
Ready to validate 👀

**Comment by eileen-coforma** [comment]
Validated in parking lot
