### ISSUE TITLE
V0::AddressController: Remove reference_data_service settings

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#76172]
PCIU address is used to obtain or update user addresses.

Settings.evss.reference_data_service&.enabled is set to false for all environments. Looked at Coverband and this controller is not hit. File and any references should probably be deleted.

## Tasks
- [x] Remove app/controllers/v0/addresses_controller.rb
- [x] Remove spec/requests/address_request_spec.rb
- [x] Remove all reference_data_service references in config/settings.yml

**Comment by RachalCassity** [comment]
Waiting for PR approvals

**Comment by tpharrison** [comment]
@RachalCassity - I just started working on removing some PCIU controllers - https://github.com/department-of-veterans-affairs/va.gov-team/issues/76212.  I just want to make sure our work doesn't overlap.

**Comment by RachalCassity** [comment]
@tpharrison Please have a look at our epic: https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73776
