### ISSUE TITLE
ITF Discovery Research (cont)

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#76179]
Review existing research on ITF to assess the scope and impact of the challenge and inform a potential redesign.

##Task
- [x] Update Mural with additional information about ITF
- [x] Update ITF Discovery doc with feedback
- [x] Schedule a meeting with Digitalization/ Pension Teams (after ITF doc is finalized)
- [x] Schedule meeting with Team 1, Supplemental Claims, Pension, Decision Review, Supplemental Claims, Emily and Shannon to present ITF findings
- [x] Add ITF document to Github
- [x] Add readout video to Sharepoint and Slack channel
- [x] Meet with Sam to check out ITF Engineer Doc (Walkthur)

## Acceptance Criteria
- [x] Incorporate additional research from Slack, on-going studies into the Mural board 
- [x] Meet with the Digitalization Forms Team to understand how they are thinking about the digitalization of the ITF
- [x] ITF Summary is added to Github 
- [x] Review internally and get feedback from Team 1 and OCTO
- [x] Incorporate feedback from Team 1 & OCTO
- [x] Update Github and Sharepoint Links

**Comment by nnicholas7** [comment]
Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702916468731/19c22e5ea181ee7c1f49bc13676aab370dc3664b?sender=uffa03f837f92a7ba90498999

ITF Summary: https://docs.google.com/document/d/1cZ27S3DTLCrOwuvshq8ttHzYLIuFrt4SbUUMOuGuAM4/edit

**Comment by nnicholas7** [comment]
Pervious ticket: Discovery on 526 ITF User Experience #71739
https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/71739

**Comment by nnicholas7** [comment]
Update: Met with Digitalization and Pension teams to talk to them about ITF and what we have found so far. Great discussion that left us with more open questions and more things to add to the document. Currently updating the document. Sarah is looking to find a time to present to Team 1, OCTO, Supplemental Claims, Pension, Emily, Shannon, VF Forms, and Decision Review teams for this sprint

**Comment by nnicholas7** [comment]
Update: The ITF Research Summary can be found in the following places:
Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/Intent%20to%20file%20Research/ITF%20Research%20Summary.md
Sharepoint: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/Intent%20to%20file%20Research/ITF%20Research%20Summary.md

The readout will be held on this Thrusday and the recording link will be added to this ticket and Sharepoint once completed.

**Comment by nnicholas7** [comment]
Update 3/12/24
Update:  We completed the readout with folks from VBA, OCTO, Team 1,  Decision Review, and Pension teams present. Research and recording of this readout can be found on Sharepoint in the DBex folder.

Next Steps:  Incorporate comments from readout into the final draft of the document — then we’re done for now, pending prioritization!

**Comment by nnicholas7** [comment]
Update 3/14/24
Met with Sam to chat about his write up of the ITF error from an engineering standpoint. Link to doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/ITF_async_proposal.md.

Was able to get clarification on the on-going ITF and how it could be different from the major ITF error that happened Aug 2023.  We have shared this document with the Pension team (See Slack for documentation/sharing:(https://dsva.slack.com/archives/C04KW0B46N5/p1708112372077109).  

Next steps: Write an engineering ticket to track the frequency of the ITF error (logging) and determine what actually triggers the ITF error message.
