### ISSUE TITLE
Mobile Controllers: PCIU References

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#76174]
These controllers require the PCIU service but no calls to initialize the PCIU service. Should this be removed? Coverband shows no runtime. Need to reach out to Mobile team and see if these files can be removed.

## Tasks
- [x] Reach out to mobile team to see if these files are still relevant.
Delete files or replace PCIU calls with VAProfile:

- [x] [Mobile Email Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/app/controllers/mobile/v0/emails_controller.rb)
- [x] [Mobile Phones Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/app/controllers/mobile/v0/phones_controller.rb)

**Comment by RachalCassity** [comment]
Reached out to mobile team [here](https://dsva.slack.com/archives/C018V2JCWRJ/p1710956100861189)
