### ISSUE TITLE
[Spike] NOD and SC - Discovery around blank PDF and missing error message

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#76176]
## Value Statement
**_As an_** engineer
**_I want to_** research how blank PDF's is bypassing our minimum size errors
**_So that_** Veterans can get an error if they upload a blank PDF

---
## Background Context
While working on ticket #74457, we tested various files to confirm that error messages would show up and discovered that blank PDF's don't show an error. We want to research how this is happening so that we may prevent Veterans from uploading blank PDF's.

## Acceptance Criteria
- [ ] We discovered why Blank PDF's are passing through
- [ ] We have a solution to show an error when there is an attempted Blank PDF upload - this is proposed in a new ticket. New ticket should also have preferred error message for this type of upload attempt.

## Designs and Build Notes
Current behavior:
![BlankPDF_NoError](https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/15691264-c295-48b3-8201-ab7e30417c90)

## Tasks
- [ ] Research how to prevent blank PDF's from being uploaded

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product

**Comment by anniebtran** [comment]
Not sure if this ticket is still necessary. There's [been work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79406) to resolve the "blank images" downstream error and we haven't seen that error since the beginning of May. I'm not sure how common this use-case is, but seems like the PDF investigation and work to switch our PDF library that Derek did probably resolved most of these problems

**Comment by Mottie** [comment]
Shaun and Maurice will meet with Michael Hobson today
