### ISSUE TITLE
V0::Profile PCIU References

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#76173]
Email and phone PCIU info is being used for V0::Profile controllers. Coverband shows no requests being sent to these controllers.

## Tasks

- [x] Reach out to @department-of-veterans-affairs/vfs-authenticated-experience-backend to see if these files are still necessary.
Remove these files or replace PCIU references:
- [x] [V0::Profile::EmailsController](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/profile/emails_controller.rb)
- [x] [V0::Profile::PrimaryPhoneController](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/profile/primary_phones_controller.rb)
- [x] [V0::Profile::AlternatePhonesController](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/profile/alternative_phones_controller.rb)

**Comment by tpharrison** [comment]
@RachalCassity These files are no longer used by the Profile.  I can remove them.

**Comment by jennb33** [comment]
@tpharrison is this work complete? Please advise so that we can update our ticket accordingly. Thank you. cc: @LindseySaari @RachalCassity

**Comment by tpharrison** [comment]
@jennb33 Sorry - I just saw this.  I will be opening a PR to remove the 3 controllers by EOD today.

**Comment by jennb33** [comment]
Thank you, @tpharrison. Once they are approved, shoot me a note so that we can update the ticket. Much appreciated.

**Comment by tpharrison** [comment]
Hey @jennb33!  [PR was was approved](#15903) yesterday.

**Comment by jennb33** [comment]
thanks @tpharrison !
@LindseySaari I think we're good to close, since the PR was approved? LMK

**Comment by RachalCassity** [comment]
@jennb33 This task has been completed by Tom and his team.
