### ISSUE TITLE
[BE] 10-10EZ - TERA: Add a flag to the form indicating TERA questions have been answered

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76185]
## Benefit to the Veteran
The Veteran will be able to submit their 10-10EZ application with Toxic Exposure details, so that they may qualify for expanded or new benefits they may not otherwise qualify for.
Passing a Yes/No flag to ES will allow the Enrollment system to send the record to manual review process.

## Background 
On February 9th, we were advised that we should expect a push to have TERA questions on the EZ form by March 5th.  
Patrick advised that we should find a solution on VA.gov to store the TERA data input, even if it doesn't go anywhere right away.  This is very large RISK, as there is a 60-day limitation on PII in the VA.gov db.  Once the 60 days comes up, we have to write a job to delete the records.
The Enrollment system is currently scheduled for June to deliver the path for us to send TERA data.  The VES team may also be advised to deliver earlier than June, possibly an interim solution to receive a "TERA flag" from our online form that would indicate there are TERA questions being answered and the submission needs to be moved to a manual review process.

In an effort to meet the deadline, imposed due to the communications going out to Veterans to apply for health care and include their TERA responses in March, we want to look at sending a True/False flag to ES.  The design includes a Yes/No question, asking the Veteran if they want to provide the TERA information.   
Note: This question is not on the original Paper Form draft, this is a decision made for the Online form so that we can provide Veterans a way to opt-out of answering these questions.  This is especially important for Veterans who may have already answered similar questions within their disability claims process.

## Resources
- [Most recent TERA Draft 10-10EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/TERA%20draft%201-23-2024%20VA%20Form%2010-10EZ.pdf)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?fromVisitorModal=true&sender=u5ad49c107baa41137f271007)
- [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=450-19244&mode=design&t=GyO36RKAPEFgXEna-0)
- [Figma - User Flows](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=815-47477&mode=design)
- [Figma - TERA designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&mode=design)

## Tasks

- [ ] Review reference materials
- [ ] Meet with teammates (Jessica and Angela) for any details needed
- [ ] Set up for TERA Flag to be sent to ES
- [ ] Complete testing, as per usual code testing guidelines
     - Be sure to capture any notes or comments in this ticket
- [ ] Inform PMs and teammates that you have completed work and testing, so next steps can be outlined

## Acceptance Criteria
- The TERA flag is in place to send to ES to indicate whether the TERA questions were answered by the Veteran

**Comment by hdjustice** [comment]
This ticket is no longer needed
