### ISSUE TITLE
Bump flipper & related gems 

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#76186]
## Description

Upgrade [flipper](https://rubygems.org/gems/flipper) and related gems to latest

## Tasks

- [x] Upgrade flipper to v1.2.2
- [x] Upgrade [flipper-active_record](https://rubygems.org/gems/flipper-active_record) to v1.2.2
- [x] Upgrade [flipper-active_support_cache_store](https://rubygems.org/gems/flipper-active_support_cache_store) to v1.2.2
- [x] Upgrade [flipper-ui](https://rubygems.org/gems/flipper-ui) to v1.2.2

## Acceptance Criteria

- [x] flipper is latest in Gemfile.lock
- [x] flipper-active_record is latest in Gemfile.lock
- [x] flipper-active_support_cache_store is latest in Gemfile.lock
- [x] flipper-ui is latest in Gemfile.lock
