### ISSUE TITLE
Add Platform resources to Atlas

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#76189]
## Issue Description
Need to verify that Atlas checks the GHA for resources, then we need to add Platform resources to Atlas to make sure that resources are accounted for.

---
## Tasks
- [ ] Confirm owner 
- [ ] Verify Atlas checking GHA
- [ ] Check on GItHub handles
- [ ] Check on email
- [ ] 

## Acceptance Criteria
- [ ] Atlas will be updated with all correct and updated resources

**Comment by jennb33** [comment]
May have to adjust the **Team Member** table (review Platform versus VFS)

**Comment by rmtolmach** [comment]
>  Ask Platform leadership if we can migrate the confluence Platform roster to Atlas.

I asked Platform leadership in Slack: https://dsva.slack.com/archives/CJRQ85PQB/p1712002762786029 (however, Andrea is OOO this week and she might have the answer).

**Comment by jennb33** [comment]
Per Aparna on Sprint Planning 5/20/2024, this work can be de-prioritized and moved to a later date. @LindseySaari also noted that we need to add usability testing prior to this addition.
