### ISSUE TITLE
Research plan for Design Intent short video

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#76196]
## User Story
As a Governance team member, I want to define a research plan for the DI short video so that I can measure the success of the video and apply learnings to future short videos.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
In ticket #75014, Governance team will be recording an informational short video on the Design Intent for the DI touchpoint page. If the Design Intent short video is successful, then Governance team would like to implement short videos on all of the Collab Cycle touchpoint pages, and potentially expand this idea to Platform Orientation. 

The purpose of this ticket is to draft a research plan for the short video using the [Platform research materials. ](https://vfs.atlassian.net/wiki/spaces/DCP/pages/2480046097/Getting+started+with+research+for+the+Platform) The goal of the research should be to measure how impactful the video was for VFS teams wishing to learn about the Design Intent. We want to ensure that the research focuses more on the impact of the video than the DI touchpoint itself. We want to be able to apply these research findings to any future videos Governance records.

Please be sure to work with the assignee for #75014 as the recording of the video and the drafting of the research plan will take place in parallel. 

### Questions for consideration

- How will be measure the success of the DI short video?
- Who will be asked to [participate](https://vfs.atlassian.net/wiki/spaces/DCP/pages/2323120146/Recruiting+participants+for+Platform+research) in the research?
- What [methodology](https://vfs.atlassian.net/wiki/spaces/DCP/pages/1472888866/Platform+Research+Methods) aligns best to our research goals?
- How long do we intend to conduct our research?
- Will we take a more passive or active approach?
- How might we proactive in ensuring our findings can be applicable outside of the Design Intent?
- How might our research help benefit the Platform Content team?

## Impacted Artifacts
- [Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2969141250/Research+plan+Design+Intent+short+video)

## Tasks
- [x] Reach out to Platform Content to figure out what can be measured on a Platform Website page. traffic? time? scroll activity? 
- [x] Draft a research plan using the Platform research materials (linked above)
- [x] Save the research plan in the Governance/Research space on Confluence
- [x] Share with Governance team members for their review and input

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has drafted a research plan for measuring the success of the DI short video

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Reached out to Platform Content via [Slack](https://dsva.slack.com/archives/CL181NRJQ/p1708003986068909).

**Comment by allison0034** [comment]
Started [research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2969141250/Research+plan+Design+Intent+short+video)

**Comment by allison0034** [comment]
@erinrwhite this is still a WIP but I would love to get early feedback on the [research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2969141250/Research+Plan+for+Governance+team+Design+Intent+short+video) so far.

**Comment by erinrwhite** [comment]
@allison0034 I dig it! I had a couple questions on the plan, and a couple of comments on the mural flow about recruitment and measuring understanding.

Okay, this is kind of a wild idea - but based on our desired outcomes, could we also make this a quiz? (Maybe incorporate some prizes?) “Review this page and test your design intent knowledge” Whether this is part of the survey, or separate from the survey, I do not know.

True/false
- Design intent is a required touchpoint
- You're required to bring wireframes to the design intent
- Only the PM should attend the design intent
- [Any other falsehoods that folks might believe]

I know this is kinda out there, but we might get more engagement if it's gamified (and yes, I just said that 😞 )

**Comment by allison0034** [comment]
@erinrwhite that is an interesting thought. I am not sure that will prove the video is a good or bad thing tho compared to just reading, if we do a quiz I would want to also do a quiz on them just reading the page to prove that one is better than the other. Maybe we should ask the team? Also, side note, in user testing, quizzing can be a bit tricky because our test subjects know there is a right and wrong answer : (

**Comment by erinrwhite** [comment]
Another idea: should we include YouTube analytics in our research plan? It offers some pretty robust view stats, and we could triangulate this with the number of page views based on platform website stats in Domo. I'm not sure how we would define success, though - what a good goal would be. 10% of page viewers watching the video?

Some Youtube stats include:
- Number of views
- Average view duration
- Average percentage viewed

**Comment by allison0034** [comment]
The quiz idea is interesting and has some good points but it may need to be something for the future after a [discussion with the team](https://dsva.slack.com/archives/GNF5GSD9N/p1708525532236439).

@erinrwhite I am getting ready to begin creating the survey and got further after some of your suggestions, take a peak at the [research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2969141250/Research+Plan+for+Governance+team+Design+Intent+short+video) when you get a chance.

**Comment by allison0034** [comment]
I met with Erin and Shira and updated the plan. Now I have [reached out to Matt Dingee](https://dsva.slack.com/archives/GNF5GSD9N/p1708551262716309) to get his feedback.

**Comment by allison0034** [comment]
Started [survey](https://app.optimalworkshop.com/a/dj540s05/questions/surveys/87104/edit#/t/details)

**Comment by allison0034** [comment]
@erinrwhite I believe both the [survey](https://app.optimalworkshop.com/a/dj540s05/questions/surveys/87104/edit#/t/details) and [research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2969141250/Research+Plan+for+Governance+team+Design+Intent+short+video) are ready for review.

**Comment by allison0034** [comment]
@erinrwhite [research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2969141250/Research+Plan+for+Governance+team+Design+Intent+short+video) and survey are ready for your review. If you don't mind, check the [survey](https://app.optimalworkshop.com/a/dj540s05/questions/surveys/87104/edit#/t/details) for correct conditional logic. I used the [platform research login](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/design/tools/optimal-workshop.md).

**Comment by erinrwhite** [comment]
@allison0034 These are looking good to me! Two things for the survey:

1. I think folks might balk at these questions being required, and exit the survey. Should we let 'em off the hook?

 - Why would you or wouldn't you come back to rewatch the video?
 - Why didn't you watch the video?

2. I see an extra slash on the end of one answer:
<img width="655" alt="Screenshot 2024-02-26 at 10 28 46 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/8bea93ec-d705-4400-9cd1-9e3594aa3b4b">

**Comment by erinrwhite** [comment]
We could also share the [survey preview link](https://dj540s05.optimalworkshop.com/questions/6cgdagsa) with the rest of the team and see what they think.

**Comment by erinrwhite** [comment]
@allison0034 Sounds good! This is ready to roll.
