### ISSUE TITLE
[ENG] 10-10 forms - Improvements: Discovery on putting the 3 apps on CD pipeline

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76209]
Revisiting putting all 3 apps on the CD pipeline to isolate them away from CI and the OOB deploys.

#### Resources
- Platform page on [How to add your application to the allow-list](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list)

<details>
<Summary>Slack from Adrian with Header test - Expand for details</Summary>

- following the [platform site docs], the megamenu test passes:

```
acrollet@ECH-LT2856208:~/src/vets-website$ yarn cy:run --browser electron --spec src/platform/site-wide/mega-menu/tests/cypress/megaMenu.cypress.spec.js --env app_url=/health-care/apply/application
yarn run v1.19.1
$ cypress run --config-file config/cypress.config.js --browser chrome --browser electron --spec src/platform/site-wide/mega-menu/tests/cypress/megaMenu.cypress.spec.js --env app_url=/health-care/apply/application

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.17.3                                                                        │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v14.21.3 (/home/acrollet/.nvm/versions/node/v14.21.3/bin/node)                 │
  │ Specs:          1 found (megaMenu.cypress.spec.js)                                             │
  │ Searched:       src/platform/site-wide/mega-menu/tests/cypress/megaMenu.cypress.spec.js        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  megaMenu.cypress.spec.js                                                        (1 of 1)


  Mega Menu
    on desktop
      ✓ looks as expected unauthenticated - C12293 (231ms)
      - looks as expected authenticated - C12294
    on mobile
      - looks as expected unauthenticated - C12295
      - looks as expected authenticated - C12296
      - traps focus inside mega menu when opened - C12297


  1 passing (354ms)
  4 pending


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      4                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     megaMenu.cypress.spec.js                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  megaMenu.cypress.spec.js                 328ms        5        1        -        4        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        328ms        5        1        -        4        -  

Done in 20.62s.

```
</details>

<details>
<Summary>Slack from Adrian - simple-form imports (checking for isolation) - Expand for details</Summary>

- simple-forms imports one file from hca:

```
acrollet@ECH-LT2856208:~/src/vets-website$ yarn check-app-imports --app-folders hca
yarn run v1.19.1
$ node script/check-cross-app-imports.js --app-folders hca
Analyzing app imports...
{
  "hca": {
    "appsThatThisAppImportsFrom": {},
    "appsThatImportFromThisApp": {
      "simple-forms": {
        "filesImported": [
          {
            "importer": "src/applications/simple-forms/mock-simple-forms-patterns/pages/mockRadio.js",
            "importee": "src/applications/hca/components/FormDescriptions"
          }
        ]
      }
    },
    "platformFilesThatImportFromThisApp": []
  }
}
Done in 386.75s.
```
- so that will need to be copied or moved to platform, but then it should be easy to add this to the allow list
</details>

## Tasks
- [x] Reference the tests that Adrian ran for the 10-10EZ in the conversations above
- [x] Run the [Cross-app import checker](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list#Howtoaddyourapplicationtotheallow-list-Isolateyourapplication) with the application's folder name
     - Example: `yarn check-app-imports --app-folders APP_FOLDER_NAME`
     - If there are other applications importing from your app, you’ll need to have the imports removed. You can do so by reaching out to the team, or refactoring them yourself and having them review the changes.
- [x] [Pass the Header test](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list#Howtoaddyourapplicationtotheallow-list-Passtheheadertest)
     - Example: `yarn cy:run --spec src/platform/site-wide/mega-menu/tests/cypress/megaMenu.cypress.spec.js --env app_url=YOUR_APP_URL`
     - Replace YOUR_APP_URL with the your application's root URL path. This is found as rootUrl property of your application in the [application registry](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json).
- [x] [Add a Slack group for the app](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list#Howtoaddyourapplicationtotheallow-list-AddaSlackgroupforyourapp)
     - Allowed applications must have a Slack user group for the owners. This group will be notified when isolated application workflow runs fail in the main branch. 
     - Example: `{
  "rootFolder": "vaos",
  "slackGroup": "@vaos-fe-dev"
}`
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/190a5d53-382d-405d-bdf4-542f6626815f)

- [x] Create a PR to add the application to the allow-list
     - Release Tools team will review the PR
     - You can also [submit a support request](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1439138197) in the[ #vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel to get help with adding an application to the allow-list.

## Acceptance Criteria
-

**Comment by hdjustice** [comment]
@hdjustice - Add link from Adrian on the process

**Comment by longmd** [comment]
Cross-app imports and header tests have passed for the Health Care App.

**Cross-app test results:**

![Screenshot 2024-03-06 at 12 58 39](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/c92833ae-72e3-47f5-955d-e8fd9f771743)

**Header test results:**

![Screenshot 2024-03-06 at 13 00 57](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/79cb4e30-c3bb-4838-905c-93ee49b53338)

**Comment by longmd** [comment]
Cross-app imports and header tests have passed for the Caregivers App.

**Cross-app test results:**

![Screenshot 2024-03-07 at 14 50 14](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/b6123073-c594-4d34-b5b2-2e5e0eb68432)

**Header test results:**

![Screenshot 2024-03-07 at 14 54 43](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/2897a219-4d5b-4935-8244-b08e385119f9)

**Comment by longmd** [comment]
Adding a note here that since the EZR only has an authenticated path, we will not be enabling the automatic deploy to production. The application will still benefit from the faster build times and other devops benefits, but will still participate in the daily deploy in an effort to allow for additional testing time due to that authentication limitation.

**Comment by hdjustice** [comment]
Good point, thank you @longmd !

FYI @alexseelig @emily-brown34
