### ISSUE TITLE
EPIC | Profile | EDU CH33 DD Changes 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76202]
## Background

There is a pending system update requiring veterans to receive disability compensation and education benefit deposit into the **same** bank account. Currently we have UI components that allow separate bank account details. We need to consolidate the UI into one component serving both benefit types.

- Account details for Comp and Pen for Disability Payments passes from Lighthouse through to BGS 
- Account details EDU Benefits is sent directly to BGS 

## Important Artifacts 
- [outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/ch33-bdn-corpdb-migration) 
- [Mural Note Taking](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707938676024/48a9e34150b8a3058c8709b241373cb9515afee6?sender=uaa72d11015d3f7c704a64191)
- [Pre-migration User Flow](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=0-1&mode=design&t=PHWgrsxoEHDjP36q-0) 
- slack channel [#edu-direct-deposit-migration](https://dsva.slack.com/archives/C06JV0KHZNF)
- [QA Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/ch33-bdn-corpdb-migration/qa)
- [QA workbook](https://docs.google.com/spreadsheets/d/1rOD8w0YNTlfbefVK7t2RsWoYK_ui1gTkVhCXlJE5VDg/edit#gid=0)
- [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/ch33-bdn-corpdb-migration/release-plan/README.md)
- [Privacy and Security Review](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1625)

|Figma Page|Description|
|:--|:--|
|[EDU Migration Notice](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=142-8730&mode=design&t=JuuOAYyUZN5gcDIC-0)|Alert displaying from mid-March until 4/20 advising users of the pending migration|
|[EDU Downtime](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=234-1394&mode=design&t=JuuOAYyUZN5gcDIC-0)|Updated UI for EDU from blocking users from online updates, directs users to call|
|[Post Migration Single Form](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=239-9210&mode=design&t=JuuOAYyUZN5gcDIC-0)|After Ch33 benefits migrate to CorpDB, we'll have a new UI that uses one form to update EDU and C&P|

## Tasks 

```[tasklist]
### Collab Cycle (staging review and priv/secur only)
- [ ] #76630
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1625
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81338
```

<details><summary>Completed Work</summary>
<p>

## Basic Flow
This is our current understanding/expectation of what LH is going to do 
```mermaid
flowchart TD
    A[User Navigates to Direct deposit] -->|Get DD info from LH| B{Check C&P & EDU on Control Information}
    B -->|Only C&P Enabled| D[Display C&P Message] --> C[Display Direct Deposit Info]
    B -->|Only EDU Enabled| E[Display EDU Message] --> C[Display Direct Deposit Info]
    B -->|C&P & EDU Enabled| F[Display C&P and EDU Message] --> C[Display Direct Deposit Info]
    B -->|Neither Enabled| G[Display Not Enabled/Not Available Message] 
```

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/ad5ed69b-d490-4ff2-882b-f573cf3d00eb)

```[tasklist]
### Alert users to the change
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76334
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76478
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76714
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76715
```

```[tasklist]
### Doomsday, we don't support CH33 Changes
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76726
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76713
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76725
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76712
```

```[tasklist]
### Happy Path (we end up not needing downtime)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76711
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76724
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76716
```

```[tasklist]
### Single Unified Form  - Post Migration
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77466
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79315
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79305
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79307
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76722
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79248
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79249
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77516
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80210
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80306
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80982
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80818
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76723
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79412
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79250
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80207
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80413
```

```[tasklist]
### QA
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60571
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77249
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77250
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77251
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76720
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77252
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80973
```

```[tasklist]
### C&P Indicators
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86337
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87185
- [ ] #87214
``` 

```[tasklist]
### UAT
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76719
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80804
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83731
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80802
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80803
- [ ] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/534
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80805
```

</p>
</details> 

```[tasklist]
### Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86840
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72697
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87553
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87602
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79907
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87581
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88488
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80858
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80859
```

```[tasklist]
### Cleanup/Post-Launch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81436
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81366
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81367
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78214
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76721
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88484
- [ ] #89160
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80198
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81264
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91588
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89955
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81368
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91917
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89743
- [ ] #92457
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92636
```

**Comment by mtcA6** [comment]
## Notes from 2/21 Education direct deposit coordination for BDN to CorpDB

main question, can we support the cutover by the deadline of 4/20?

### LH 
- assumptions that we're not plugging into a new service 
- using the old service and ammending the service 
     - BGS mentioned the service that LH is using but I missed it

### BGS comments/timeline 
- the service that's being used by LH is targeting only CPL cases, needs to be opened for all addresses not just specific to CPL (not sure what CPL is) - Jinmay 
     - would go into production on the 13th 
- John Dell asking - when's the att signoff date: PIA due march 14th, ATT due March 21st < this is the date that changes need to be signed off approving testing, link test has to be completed for it to go into production on April 20th 
     - 13th of march is the earliest but maybe the 20th is when they could possibly push things  
- BGS is saying we can get started w/coding and testing 
     - LH is responding we need an additional indicator saying that it's an EDU or C&P payment 
     - BGS asking if we have a service that reads all pending claims 
     - LH said no 
     - BGS is saying BDN inquiry index thing is being decommissioned 

### BDN 
- service in bdn will continue to be available through april20th - cutover to point to the corporate database 
- at the point of conversion (ross riley) on april 28th when BDN is brought down and moved to corpDB. 
     - they will NOT distinguish between edu and cp payment addresses 
     - EFTs over to corp < not sure what EFTs are
     - only one payment address regardless  


Sprint for BGS Feb 26-Mar 8 - could start? > we need to determine the process on BGS that's going to flip an indicator, Jon "we know how to get this info" but what service will be used? 
- indicator because it as x because there is no bdn 
- need the indicator

**Comment by mtcA6** [comment]
@tpharrison did we coordinate with VA Notify to delete the old EDU email template?

**Comment by tpharrison** [comment]
@mtcA6 I'm pretty sure we can delete the template ourselves, but we haven't yet.  We were waiting until the BE CH33 files were removed, which they were earlier this week.  I will add this task to https://github.com/department-of-veterans-affairs/va.gov-team/issues/91880

**Comment by mtcA6** [comment]
These changes launched, closing out this ticket
