### ISSUE TITLE
NOD and SC | Behavior change for cancel button when file upload error

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#76218]
## Value Statement
**_As an_**Veteran who attempted to upload a large file that generated an error
**_I want to_** have clear instructions on what my options are
**_So that_** I don't get stuck in a confusing experience. 

---
## Background Context
Previously, there was work done to ensure max [filesize error](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74457) was shown for all files larger than 1000mb. 
This work brought to light that asking the Veteran if they're sure they want to delete an erroneous file goes against the idea of the `cancel` behavior.

## Acceptance Criteria
- [x] When a file upload generated an error, the Veteran is not asked to confirm whether or not they are deleting it (because there is nothing to delete).
- [x] When a Veteran cancels, the file is removed.

## Designs and Build Notes
What we currently have:
![CancelButton_Behavior](https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/643459e1-91fd-4373-94fd-eeef974f4ab7)

## Tasks
- [ ] Remove widget to confirm if user wants to delete an erroneous file
- [ ] Add unit tests

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product

**Comment by eileen-coforma** [comment]
I'm not sure if there's a design file that needs to be attached to this. Behavior is captured in AC.
