### ISSUE TITLE
BE | Profile | Remove Email and Phone PCIU Controllers

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#76212]
## Background
Coverband shows no requests being sent to these controllers:
- V0::Profile::EmailsController
- V0::Profile::PrimaryPhoneController
- V0::Profile::AlternatePhonesController

These files are no longer in use and need to be removed.

## Original Ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/76173

## Tasks
Remove the following:

- [x] Routes
  - [x] `resource :email, only: %i[show create]`
  - [x] `resource :primary_phone, only: %i[show create]`
  - [x] `resource :alternate_phone, only: %i[show create]`
- [x] Controllers
  - [x] `app/controllers/v0/profile/emails_controller.rb`
  - [x] `app/controllers/v0/profile/primary_phones_controller.rb`
  - [x] `app/controllers/v0/profile/alternate_phones_controller.rb`
- [x] Controller Specs
  - [x] `spec/requests/email_request_spec.rb`
  - [x] `spec/requests/primary_phone_request_spec.rb`
  - [x] `spec/requests/alternate_phone_request_spec.rb`
- [x] VCR cassettes 
  - [x] All cassettes in: `spec/support/vcr_cassettes/evss/pciu`
- [x] Swagger Docs (app/swagger/swagger/requests/profile.rb)
  - [x] `/v0/profile/email`
  - [x] `/v0/profile/primary_phone`
  - [x] `/v0/profile/alternate_phone`
- [x] .rubocop_todo.yml
  - [x] `spec/requests/email_request_spec.rb`
  - [x] `spec/requests/primary_phone_request_spec.rb`
  - [x] `spec/requests/alternate_phone_request_spec.rb`
- [x] Codeowners
  - [x] `spec/requests/email_request_spec.rb @department-of-veterans-affairs/vfs-authenticated-experience-backend @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group`
  - [x] `spec/requests/primary_phone_request_spec.rb @department-of-veterans-affairs/vfs-authenticated-experience-backend @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group`
  - [x] `spec/requests/alternate_phone_request_spec.rb @department-of-veterans-affairs/vfs-authenticated-experience-backend @department-of-veterans-affairs/`
