### ISSUE TITLE
[Design] 10-10EZ TERA Alert for intro page directing to paper form

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#76220]
## Issue Description
As a Veteran, I heard I qualify for health care due to my toxic exposure and I want to turn in my application with that information. Need clear direction if that is not available on the online EZ how I can do that.

---
## Tasks
- [x] Create alert for intro page
- [x] Discuss placement so alerts don't stack
- [x] Review with content
- [x] Make any changes
- [ ] Review with PM/PO

## Acceptance Criteria
- [ ] The content and UX direction is clear to pass along to FE.
---

**Comment by jessicastump** [comment]
[Draft for content review](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=615-123324&mode=design&t=ylCGkWiOekwXTCr9-4)

**Comment by jessicastump** [comment]
![Alert](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/8192ee27-c8b7-45af-97cd-a8bb86eda14b)

@hdjustice Here is the back-up alert if needed, also in Figma file.

**Comment by hdjustice** [comment]
Looks great!  I hope we don't have to use it, but so glad it is in place!

**Comment by jessicastump** [comment]
Yep! I will close this ticket then and _IF_ we do need it the FE ticket will need to be created
