### ISSUE TITLE
Provide for intentional ordering of chart in the Satisfaction Survey Domo dashboard

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#76222]
## Purpose
The order of the results are currently not consistent, and we want them to order from Strongly disagree --> Strongly Agree across each chart for easier uptake.

## Tasks
- [ ] Replicate the Beast Mode code work to manually adjust the results ordering in the chart
- [ ] Apply across each chart

## Acceptance Criteria
- [ ] Each chart lists the results as Strongly disagree --> Strongly Agree
