### ISSUE TITLE
[FE] 10-10EZ - Performance Monitoring: Update RUM config to track additional user properties

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76235]
## Background
It was brought to the team's attention from Josh Faulkner that he was seeing a dramatic and unusual decrease of submissions on the EZ form.  Upon further research, it was determined that the application itself was not displaying for authenticated users. Interestingly - the issue is not present in local, RI, Staging or any other environment except production. After further investigation, it seems to be happening for LOA3 users.  It was mentioned by Patrick that we could try to track Authenticated vs Unauthenticated/LOA3 vs LOA1

For Datadog RUM, we would like to track additional user properties to help with future debugging. None of these properties are PII. The list of user properties is as follows:
- Total Disability Rating
- Enrollment Status
- Logged in
- Login Service Provider (ID.me, Login.gov, etc)
- LOA

## Resources
- [Datadog User Session documentation](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#user-session)

## Tasks
- [ ] Identify state values to utilize to pass in as user session properties
- [ ] Initialize user session properties when Datadog RUM is initialized
- [ ] Validate with Data Analyst that user properties are coming through in RUM sessions

## Acceptance Criteria
- Additional user properties are available in RUM sessions

**Comment by jadon1979** [comment]
Patrick requested the following fields,
isSignedIn, loa, service provider (CSP; e.g., id.me, login.gov, dslogon, or mhv).
