### ISSUE TITLE
EVSS - PCIU Migration - 526ez Pre-fill - Missing mailing address investigation

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#76240]
## Issue Description
Upon starting the 526ez pre-fill PCIU migration at 10%, some instances of missing mailing address data started to appear. During the 3 weeks prior (when we first added logging), missing mailing addresses were extremely rare at around .05%. Since some occurrences of this happened a little prior to launch, we decided to let it run longer to determine if it was just an anomaly.  By the next morning, occurrences were up to 5% and all occurrences (besides 1 or 2) were from the flag ON state (VA Profile only). At this point, we rolled back completely, and since then absolutely no missing mailing address occurrences came in- even after a full day of running. 

All of this taken together seems to indicate that these were NOT coincidental, and that _somehow_ these extra PCIU calls are a band-aid for missing address information. One explanation (offered by Michael Harlow) was that there might be a latency between when address information gets updated within VA Profile versus PCIU Address. Searching The Slacks seems to suggest, however, that both systems pull directly from the Corp "table" (database?) for this information. This needs to be investigated more thoroughly.

Note: % of missing phone numbers was roughly the same at 12.88%, while % of missing emails was even _less_ than the flag OFF state at 4.88% (down from 8.62%) during this time frame.

This ticket is to determine
- why these missing mailing addresses occurred
- what the differences are between VA Profile and PCIU Address retrieval
- any possible fix, such as a change to how we call VA Profile for address information

## Tasks
- [ ] Use DataDog missing address occurrence logs to repro calls to PCIU_Address for relevant users (if possible)
   - [ ] If data is returned, this points more towards the latency issue theorized above
   - [ ] If NO data is still returned, use toward investigating why
- [ ] Reach out in slack to VA Profilers (Michael Richards) and EVSSers (Michael Harlow, Bonnie Craig) with specifics of the problem
- [ ] Reach out to Emily to see if 5% is perhaps acceptable (if no fix is apparent)

## Acceptance Criteria
- [ ] See above tasks

## Links
- [DataDog dash](https://vagov.ddog-gov.com/dashboard/qv6-xpd-7xg/benefits---dbex---evss-to-vaprofile-526ez-contact-info-pre-fill?index=%2A&overlay=events&refresh_mode=paused&view=spans&from_ts=1707757606661&to_ts=1707849076413&live=false)
- 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Worked with Aurora determine how to query PCIU and VA Profile [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/evss-pciu-migration-discovery.md#using-argo-production-terminal-to-call-pciu-and-va-profile). Using these new tools, put together this investigation [section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/evss-pciu-migration-discovery.md#missing-mailing-address-investigation), which I referenced in this [slack](https://dsva.slack.com/archives/C7TE0PFTL/p1708732310734809) to VA Profile, asking them "what's up? and don't say the sky..."
