### ISSUE TITLE
Creating process for categorizing/bucketing Platform Feedback item

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#76246]
###No longer needed.  We will be using the Experience Areas that Naomi proposed

## Purpose
Take past and present responses from Feedback Workflow and bucket them into categories used in Satisfaction Survey.  Ideally, individual feedback items would feed up or be connectable to Survey categories/themes

## Tasks
- [ ] Team discussion to identify what the themes/categories/bins should be
- [ ] Create guidelines for parsing feedback into a bucket, i.e. what determines what bucket an item goes into?
- [ ] Document guidance for parsing

## Acceptance Criteria
- [ ] User can use guidance to bucket a feedback item
