### ISSUE TITLE
[BE] Add facilityType parameter in PatientCheckIns Controller

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#76247]
## Description
Since the standalone travel claims application going to use the same PatientCheckInsController, including the appointment type parameter to differentiate between `vista` vs `OH` appointments would prevent `check-in` workflow metrics from getting impacted by travel claims application usage.

Enable `facility_type` parameter as permitted_params in [PatientCheckInsController](https://github.com/department-of-veterans-affairs/vets-api/blob/419b461dddda565bfa3cb1b6c8c3c50db421ae5d/modules/check_in/app/controllers/check_in/v2/patient_check_ins_controller.rb#L45-L48) & modify [statsd](https://github.com/department-of-veterans-affairs/vets-api/blob/419b461dddda565bfa3cb1b6c8c3c50db421ae5d/modules/check_in/config/initializers/statsd.rb#L19-L23)  to include `oh` facility_type GET call

## Tasks
- [ ] [BE] **Modify PatientCheckInsController for `facility_type` parameter**
- [ ] [BE] **Modify statsd config for adding `facility_type` OH appointments**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
<img width="1862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEdPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--172a859c4428745f02c943ac4365f33998d77cd2/image.png" alt="image.png" />
Verified in staging

**Comment by kanchanasuriya** [comment]
Verified the changes in staging.  Not being able to view the metrics in production, might be because of the call happening from postman.
