### ISSUE TITLE
[BE] Modify TravelClaimSubmissionWorker to pick TemplateIDs by facility_type

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#76255]
## Description
As a veteran, I want to be notified when I submit a travel claim during my visit to an Oracle Health site.

Details:
We will use different set of templates for notifying veterans from travel claims standalone app for OH facilities. Currently, `TravelClaimSubmissionWorker` uses one set of template ids for notifying veterans with success/failure/error messages in day-of checkin workflow.  Modify `TravelClaimSubmissionWorker` to pick template ids by `facility_type` from cache.

## Tasks
- [ ] [BE] **Modify perform method to read facility_type from redis**
- [ ] [BE] **Modify handle_response to pick template id based on facility type**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by randomsync** [comment]
do we have the template IDs available already? @kanchanasuriya

**Comment by kanchanasuriya** [comment]
> do we have the template IDs available already? @kanchanasuriya

Yes, we have template IDs from VANotify team.  I am adding them in Param store and yet to open PRs for yml changes in dev, staging & prod

**Comment by loripusey** [comment]
@kanchanasuriya @randomsync Is this one going to need to roll over? If so, how much work is left?

**Comment by randomsync** [comment]
I’m working on finishing the tests today so maybe one point will roll over
on us.

- Gaurav
