### ISSUE TITLE
[FE] My VA: web components v3 migration 

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#76257]
## Background

---
## Tasks
- [ ] add `uswds` flag to existing web components on `/dashboard/` and confirm that they look as intended
- [ ] see if any "bespoke" components can be componentized to VA web components 

## Acceptance Criteria
- [ ] components that have been migrated to v3 still match Figma mockups 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Designer _
- _How can this work be validated?_

## Resources
- optional: links, screenshots, etc.

**Comment by ajakabcin** [comment]
duplicate
