### ISSUE TITLE
GA4: Review & Inventory Tables that are Feeding Domo Reports

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#76258]
### Description
Audit and document the Domo datasets that are pulling in data via the Google BigQuery connector from the GA database.  

### Tasks

- Get a list of all Domo datasets that are fed via the Google BigQuery connector into a Google Sheets document listing the name of the dataset.
- For each row in the Google Sheets document, determine if the query in the settings of the dataset is accessing the GA table (or a dependent object in the vsp_sites schema) and mark it as _**Yes**_ or _**No**_
- For each entry that is marked as _**Yes**_ , create a list of the attributes in the query, noting whether or not the column is renamed in the query

---

### Artifact

- [Tracking Artifact](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=0&fvid=2002218633
)

### Acceptance Criteria:

- [x] All Domo datasets that are fed via the Google BigQuery connector identified and documented in our [Domo tracking artifact](https://docs.google.com/spreadsheets/d/1_sFDhS53qmUFg0qePiXDcKn67stzR9yt-ZTkGgrIcO0/edit#gid=0)
- [x] Whether or not each entry in the Google Sheets document document created is dependent on the GA table or vsp_sites schema, denoted by Yes, or **No** in _Column F_
- [x] For each dataset that is identified as being dependent on GA or the vsp_sites schema the attributes are listed in the document
- [x] Each relevant dataset has an entry in **Column G** for _**BigQuery UA Schema Reference**_

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 Thanks for building this out. **Can you assign this a point estimate?**

Also, you might want to connect with @Blivaditis, as [his ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/47699) also involves a tracker, and might be simpler to consolidate some of that tracking into [one document](https://docs.google.com/spreadsheets/d/1_sFDhS53qmUFg0qePiXDcKn67stzR9yt-ZTkGgrIcO0/edit#gid=0).

**Comment by johnny-jesensky-adhoc** [comment]
This was completed after dividing and conquering among most of the team. We still need to determine what steps we'll take on the datasets that were _Inaccessible_, which were likely deactivated due to inactivity.

We'll likely try to determine that answer in another sprint.

Moving this to _**Done**_.

FYI @Blivaditis, @dorseypa1, @ChristineYoungZA
