### ISSUE TITLE
[BE] Modify TravelClaimsController to permit facility_type parameter

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#76250]
## Description
Modify TravelClaimsController to permit facility_type parameter

## Tasks
- [x] [BE] **Modify TravelClaimsController to allow facility_type parameter**
- [x] [BE] **Modify statsd config**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by kanchanasuriya** [comment]
Validated the metrics in datadog
<img width="1751" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77aa9f4daa85a18a5de7e53423d7a625d582971f/image.png" alt="image.png" />
