### ISSUE TITLE
[Spike] Determine if it's possible to show when a 3P request has been closed in the CST Recent Activity section

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#76275]
## Background Context

Right now, when a 3P requests is closed, it simply "goes away." It would be great if we could keep the original 3P open update, and add a new update saying that the 3P request has been closed, so that there's a paper trail.

This ticket is to investigate how we might reconfigure Lighthouse to be able to make that happen. 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Product performs functional QA and verifies acceptance criteria was met
- [ ] Engineering identifies staging users required to test and shares account and credentials with product

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_
