### ISSUE TITLE
[FE] - Create appointment selection page for multi-facility and single facility page

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#76276]
## Description
Create new page components, and add to route. Both pages should set the appointment being filed for into context. For multi that will be the first appointment in the facility group(s) selected, for single it will be the first appointment in the array. 

## Wireframes
- [Wireframes-multi](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=1187-4729&mode=design&t=vloBjcIzfAoX9uEn-0)
- [Wireframes-single](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-6883&mode=design&t=vloBjcIzfAoX9uEn-0)

## Tasks
- [ ] Create single facility page
- [ ] Create multi facility page
- [ ] Save appointment(s) filing for in context as array
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@brianseek do we need this ticket anymore?

**Comment by loripusey** [comment]
@brianseek @wullaski do we still need this ticket? If so, please point.

**Comment by wullaski** [comment]
@loripusey this ticket is describing the original functionality. We can close this one.
