### ISSUE TITLE
Content edits on Toxic Exposure screens

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#76281]
## Issue Description

From Mike Eng:

> We are seeking a focused content review on some questions we will be updating in the disability benefits form as part of adding toxic exposure questions. There is [this screen](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=411-6431&mode=design&t=8OJjeOf2ZrzZEBwS-4) with the question "How is your condition related to your service?" and 4 radio button choices. Following from each of the 4 choices, there is another screen with questions customized to that radio button choice.
> 
> We know that there has been guidance to remove the word "please" in questions, so we have done that, and we also adapted the question text into current design system components, using "hint text" where it seems appropriate. We want to make sure we have interpreted this correctly and see if there are any other content edits you recommend before implementing these screens. @katherine-fung has given us content guidance in the past and is familiar with this work.
> 
> Asynchronous feedback would be most helpful. Figma comments would be best for detailed feedback on screens. Also tag @mengA6 in [benefits-disability-design](https://dsva.slack.com/archives/C053UDWMH7U) in Slack for anything more general.
> 
> Note that @mengA6 will be out of office 2/19 - 2/23 , so responses may come back after that.

**Screens:**
- [Condition follow up option 1](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=0-1132&mode=design&t=8OJjeOf2ZrzZEBwS-4)
- [Condition follow up option 2](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=699-7159&mode=design&t=8OJjeOf2ZrzZEBwS-11)
- [Condition follow up option 3](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=699-10665&mode=design&t=8OJjeOf2ZrzZEBwS-11)
- [Condition follow up option 4](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=699-11332&mode=design&t=8OJjeOf2ZrzZEBwS-11)

Assigning Katherine but feel free to add A if necessary!

---
## Tasks
- [x] Review content (Katherine)
- [x] Add comments and edits to Figma screens (Katherine)
- [x] Alert stakeholder feedback is ready to implement (Katherine)

## Acceptance Criteria
- [ ] Feedback provided to product team
---

**Comment by katherine-fung** [comment]
I delivered my recommendations to the product team in [ticket #75945](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/gh/department-of-veterans-affairs/va.gov-team/75945).

**Comment by mengA6** [comment]
Thank you very much @katherine-fung. We have one outstanding question for you about the use of "active" as in "My condition existed before I served in the military, but it got worse because of my active military service." Could you please reply in the [Figma comment thread](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK?node-id=929:8884&mode=design#707038795)? 

Otherwise I've incorporated you suggestions, with [one note about one I changed slightly for consistency](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK?node-id=929:8859&mode=design#707052304) (removed "service-connected")

**Comment by mengA6** [comment]
This is resolved with Katherine's reply. Thank you! Not sure if I should close the ticket, so I'll let you do that if it makes sense.
