### ISSUE TITLE
[Research] Dot Indicator Research: Conduct pilot sessions

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#76284]
## Background
We need to conduct the pilot sessions for the dot indicator study and address any issues that come up.

## Tasks
- [x] Conduct pilot session to check a11y/assistive technology (2/20 1pm et)
- [x] Conduct standard pilot session with (2/20 2:30 pm et)

## Acceptance Criteria
- [x] Pilot sessions are complete
- [x] Any issues are recorded and addressed (or additional tickets are created to address them)

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** Any team member
- **_How can this work be validated?_** ensure pilots are complete/any issues are addressed

**Comment by ajakabcin** [comment]
Pilot sessions conducted 2/23 and discussed with team - good to go!
