### ISSUE TITLE
[BE] My VA TMA: Update swagger documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#76293]
## Background
We need to update our swagger documentation for My VA

## Tasks
- [x] Familiarize with vets-api swagger documentation
- [x] Investigate ways to improve (e.g. hint text, types, docs, authenticated demo requests, etc)
- [x] Discuss with team on ways we currently use Swagger docs for api development & integration tasks

## Acceptance Criteria
- [ ] discussed with team and prioritized improvements
- [ ] follow up tickets are created (if any)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_    FE, BE
- _How will we know this is done?_   1. related PR(s) are merged to main (if any) 2. this ticket is resolved  3. follow up tickets are created (if any). progress and links to related PRs will be logged here

**Comment by DanielMiller-agile6** [comment]
@ajakabcin @tpharrison I think i'm going to start workin on this ticket since i'm blocked on datadog stuff till i can make time to drive to roseburg and reset PIV PIN, so I'm moving this into "ready" for now.  i added some descriptions and things, so let me know if this makes sense or anything should be added/changed, or we can discuss more at refinement before moving to "in progress" :)

**Comment by DanielMiller-agile6** [comment]
dropping this to 2 points for next sprint.  i still need to convert notes to tickets and chat with team on potential improvements.  the swagger docs are very large and each endpoint and supporting code kinda also needs to be investigated, so I decided to create new tickets for improvements per endpoint so we can prioritize which would be most helpful to improve or add additional documentation/types for.

The bigger improvements would probably require platform team to upgrade our node version, so that we could use something like the following with the openapi spec from vets-api: https://github.com/drwpow/openapi-typescript 

I'll write up additional details here when i finish tasks.

**Comment by DanielMiller-agile6** [comment]
wrote up a gdoc for team collab, but will add notes here as well upon closing this ticket, after discussing.
