### ISSUE TITLE
Decommission obsolete ArcGIS/facilities code 

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#76315]
## Issue Description
I am 99% sure (and awaiting [confirmation from the sitewide facilities team](https://dsva.slack.com/archives/C0FQSS30V/p1707952451495999) that a bunch of legacy code and infrastructure related to facility locator can be safely removed.

* The old facility locator implementation used to periodically pull bulk data from a set of ArcGIS REST endpoints and store them in a PostGIS database via the subclasses of `app/models/BaseFacility`. 
* It also periodically pulled data from some VA-specific datasources for access-to-care information, drivetime bands, and ETL in some data from files for cemetery information. All of these would operate on those model classes. 
* Current VA.gov facilities API controller is a pass-through to Lighthouse facilities API.
* I can find no uses of any of the `*Facility` or `*FacilityQuery` model classes other than specs and the aforementioned jobs.
* Some of the jobs (under `app/sidekiq/facilities`) are still running but appear to be uselessly updating the database that no active service is reading from. 

Once confirmed we can clean up all this code, plus remove at least one forward proxy configuration, and associated monitoring and pagerduty service. 

---
## Tasks
- [ ] Get concurrence from facilities team that this is dead code
- [ ] Remove `Facilities::*` references from `lib/periodic_jobs.rb`
- [ ] Clean up Facilities and FacilityQuery model classes, Facilities sidekiq jobs, and client adapter code under lib/facilties
- [ ] Remove obsolete facilities stanzas from settings.yml and application manifests (confirm all as unused outside of removed code)
- [ ] Ensure no references to arcgis as a mapped dependency in frontend downtime notifications (_it's in there, it was kind of spurious because there was no true runtime dependency on arcgis since the data was cached, but  this should be removed or updated to depend on the lighthouse facilities API_)
- [ ] Remove `arcgis` and `vha-access` forward proxy configurations
- [ ] Remove any synthetics or monitors from Datadog related to arcgis or vha-access upstreams
- [ ] Remove Pagerduty service for arcgis, and associated mapping in settings.yml and application manifests
- [ ] Remove any lingering references to arcgis or vha-access/access-to-care from Platform documentation website

## Acceptance Criteria
- [ ] Obsolete references to an unused service will be removed, eliminating some ongoing maintenance burden and cognitive load. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
Facilities team does believe this code is dead and could be removed. However: due to the important nature of the locator, this requires major testing pre-prod to ensure we don't disrupt the locator, just in case. My 2 cents: The Sitewide Facilities team should be involved in planning / code review, and required to perform QA regression pass before any related code can merge.

**Comment by jilladams** [comment]
This PR did get merged. I am not clear on how many of the remaining ACs that are unchecked may / may not have been included in that PR, so not sure if this is done / can close, or if the PR that merged was only a subset of everything this ticket wanted to do.

**Comment by rmtolmach** [comment]
I'm working on this task:
- [ ] Remove any lingering references to arcgis or vha-access/access-to-care from Platform documentation website

**Comment by rmtolmach** [comment]
>  I am not clear on how many of the remaining ACs that are unchecked may / may not have been included in that PR

@jilladams, the items checked off seem accurate to what's been completed, so the unchecked items still need to be done.
