### ISSUE TITLE
[Design] Replace Sketch links on My VA owned Github pages with Figma

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#76328]
## Background
As a designer, I want to ensure that our Github documentation includes up to date links to imported Figma files instead of Sketch ones so that stakeholders can still reference the associated visuals after Sketch usage is fully sunset. 

---
## Tasks
- [x] Search for all instances of Sketch files being included/linked in documentation in identity-personalization (Authenticated Experience) that pertain to My VA work
- [x] Open links and find the equivalent replacements in Figma
- [x] Document any issues that emerge so there is a record

## Acceptance Criteria
- [x] All Sketch links in identity-personalization (Authenticated Experience) that pertain to My VA work will be replaced with Figma ones (barring any specific issues, which will be documented)

## Validation
- Can be validated by Design team members or Product

**Comment by mattmarino-adhoc** [comment]
One link that cannot be updated: products/identity-personalization/profile/account-security/account-settings-V1/design/account-mvp.sketch (won’t open in Sketch 93 or import, data issue apparently - not sure what it should be)

**Comment by mattmarino-adhoc** [comment]
Some listings still appear in searcg even though links were replaced (do show up under master)

**Comment by mattmarino-adhoc** [comment]
@ajakabcin I'd like to close this out, and we'll add a new story for next week or after to resolve any lingering issues that came up from merges not happening on github.

**Comment by ajakabcin** [comment]
Sounds good - thanks @mattmarino-adhoc!
