### ISSUE TITLE
Rotate AWS Keys - July 29, 2024

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#76337]
## Summary
We need to rotate the IAM keys in AWS every 60 days. 

## Resources
[Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/rotating-iam-keys.md)
[Knowledge sharing meeting recording](https://drive.google.com/file/d/1owR-Pec3urKlulr3ysarHXER2bvbd7Ia/view?ts=65baa17b)

## Tasks
- [x] Create new keys
  - [x] CMS-service-account-1
  - [x] CMS-service-account-2
- [x] Update Secrets Manager
  - [x] tevi/cms_service_account_1/aws_access_key_id
  - [x] tevi/cms_service_account_1/aws_secret_access_key
  - [x] tevi/cms_service_account_2/aws_access_key_id
  - [x] tevi/cms_service_account_2/aws_secret_access_key
- [x] Alert #vetext-engineering channel
- [x] Update Github Repos
  - [x] [CHIP](https://github.com/department-of-veterans-affairs/chip/)
  - [x] [LoRota](https://github.com/department-of-veterans-affairs/lorota)
  - [x] [vista-api](https://github.com/department-of-veterans-affairs/octo-vista-api)
- [ ] Verify no old key usage
  - [ ] Wait 48 hours
  - [ ] Deactivate Keys - 7/31 11am PT
  - [ ] Wait 48 hours
  - [ ] Delete Keys - 8/2 11am PT
