### ISSUE TITLE
[ENG] 10-10CG - BUG: Investigate reports of the Review screen prohibiting submissions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76330]
## Benefit to the Veteran
By investigating this reported bug, we can potentially discover an underlying issue preventing Veterans and their Caregivers from submitting the form.

## Background
We received an email from the Veteran Support team (Contact center) informing us that Veterans reported issues with the Caregiver application recently, specifically on the Review screen.  There may be other issues reported, we are pending further information from Veteran Support on these.
See details below on the 2 we have so far:

>Occurred on 1/29/2024
>- Called in saying that she is having an issue filling out the Caregiver Application online saying that it came up red saying that the signature doesn’t match and must match previous entered name and she confirmed that it does match the name.
>- The caller stated that the system is displaying her name in red for the signature not matching either, but the name is correct there also.
>- Please reach out to the caller(spouse) to help with getting this corrected so she can submit the caregiver application online.

>Occurred on 1/29/2024
>- Caller is submitting application on VA.gov. Caller stated she was applying for caregiver and she got all information except the application will not load to submit. Caller stated that she has gone through the application and there are no missing fields. The form is VA Form 10-10CG and she has tried once but the application will not submit.

## Tasks
- [ ] Review logs from 1/29/2024 for any errors or anomalies
- [ ] Run a few tests on the application to reproduce the issues on the Review page
     - You can test in Staging & Production - unauthenticated
          - When testing in Prod, be very careful to use names like "Test User" or something along those lines
          - Most likely the application will not submit due to the test user not having an SSN in MPI, but just in case, be sure to indicate this is a test in some way (Name, Address, etc)
     - Try variations of the Veteran's name/Caregiver's name
          - spaces at the end or beginning
          - special characters
          - meeting the character length maximum
     - Take note of load times for the Review page
     - Other scenarios you may think of
- [ ] Document your findings in the comments of this ticket
- [ ] Discuss with PM on findings and possible next steps

## Acceptance Criteria
- Reported issues on the Caregiver application have been investigated and testing has been completed in an attempt to reproduce them

**Comment by Mitch-A6** [comment]
Attempted to investigate this, but unfortunately the underlying user session info was expired by the time I got access to it. 

We'll be able to revisit this if we get a newer instance of the problem.

**Comment by hdjustice** [comment]
Closing as an old ticket.  No further reports of this issue were received.  Any new issues will result in a new investigation ticket
