### ISSUE TITLE
Vet Center after hours

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7634]
## Problem Statement

How might we inform Veterans of the availability of the Vet Center Call Center for after hours care?

## Goal
Veterans are aware they can call after hours

## Objectives or Key Results this is meant to further
Objective 2: Deliver meaningful facility information

---
## Tasks
- [ ] Consider including this information on Vet Center Facility Detail pages

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This work will be incorporated in the Vet Center Taxonomy/Webpresence project.
