### ISSUE TITLE
DevOps Support Training - Sprint 47

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#76348]
## Description
Based on instructions provided via Slack, please demo and record the proper process for DevOps T2 Support to effectively perform SOCKS & AWS Access requests, Offboarding requests, and PR Reviews

## Tasks
- [ ] Demo & Record AWS & SOCKS access request process
- [ ] Demo & Record Offboarding request process
- [ ] Demo PR Review process

## Acceptance Criteria
- [ ] All tasks have been demoed
