### ISSUE TITLE
[Data Definitions] - Spike - Should vets-website should check version on login and/or onsave

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#76354]
# Overview
One way to mitigate issues with data definitions would be for the vets-website to check the version against vets-api as soon as the user logs in or on saving of the form.  These checks would minimize the chance that the user gets to the end and is out of sync with the latest data definition version.

```[tasklist]
### Tasks
- [ ] - Evaluate if a check  during login and/or onsave makes sense
- [ ] - What steps would we make the user take?
- [ ] - Create follow on ticket(s) for the front and back-end if appropriate
```

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76354?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by mjknight50** [comment]
We've decided to now pursue at this time.
