### ISSUE TITLE
Add operating status indicators to search results and facility detail pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7635]
### User Story
As a Veteran, I need to know when the hours of operations for a facility have been impacted by an emergency so that I can adjust my plan to visit. 

## Goals
Implement display of facility-level operating status and operating notes on search result cards and facility detail pages for VA facilities, only. 

There are four options for operating status:

1. Normal services and hours 
2. Facility closed
3. Facility Notice 
4. Limited services and hours

## Tasks
[Operating Status.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4447176/Operating.Status.zip)

Implement display of facility operating status and notes, based on Aricka's [designs](https://app.zeplin.io/project/5e8ca6e47e331bb99bdbdfb1/screen/5e8ca915f92f011fcb5d7661)  and API changes in [#7452](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7452)

- [ ] Add two new fields available through API for **VA facilities only** _(VA health, VA benefits, VA cemeteries and Vet Centers)_
     - operating status 
     - operating status notes 
- [ ] Add operating status indicators to correspond with the following three options for operating status 

![Facility closed](https://user-images.githubusercontent.com/55411834/78399997-2ba43900-75b3-11ea-964b-94a57b0140c0.png)

![liited services and hours](https://user-images.githubusercontent.com/55411834/78400012-3068ed00-75b3-11ea-8161-998fb54bc512.png)

![facility notice](https://user-images.githubusercontent.com/55411834/78400022-3363dd80-75b3-11ea-84af-55431d22de54.png)

- [x] Ensure facility names on search result cards which are linked to Facility Detail pages (or to Pittsburgh VAMC pages) are underlined to visually indicate they are links 
- [x] Change search result card background to white for contrast with operating status indicator
- [x] Add gray line separating cards in search result list
- [ ] Display appropriate operating status indicator on search result cards
- [ ] Add full text [warning alert](https://design.va.gov/components/alertboxes) box component with colored left bar and gray background containing operating status indicator on the facility detail page which will include:

1. appropriate operating status indicator at top of Facility Detail page under facility name
2. text from operating status notes under operating status indicator.
3. new sentence: (only if a website is available)

> Visit this location’s website to learn more about hours and services. (with linked website)

![image](https://user-images.githubusercontent.com/55411834/78723111-0e8ba500-78e8-11ea-8781-3cb50c8c7643.png)

## Acceptance Criteria

- [x] Operating status indicators are the full width and consistent with design system 
- [x] Alert box on Facility Detail page is consistent with design system, regardless of the background color for the operating status indicator
- [ ] "Visit this location’s website to learn more about hours and services." does not display if the facility does not have a website. 

When facility type = VA health, VA benefits, VA cemeteries or Vet Centers:
 - [ ] search result cards have a white background. 
 
**and** a facility's operating status is _Facility closed_, Facility Notice, Limited services and hours

- [ ] The _Facility closed_ indicator appears below the facility name on search result cards
- [ ] The _Facility closed_ indicator appears below the facility name on the Facility Detail page

**if** the operating status notes field is populated, 
- [ ] The text will appear below the  _Facility closed_ indicator 

---

When facility type = VA health, VA benefits, VA cemeteries or Vet Centers:
 - [ ] search result cards have a white background. 
 
**and** a facility's operating status is _Facility Notice_, Limited services and hours

- [ ] The _Facility Notice_ indicator appears below the facility name on search result cards
- [ ] The _Facility Notice_ indicator appears below the facility name on the Facility Detail page

**if** the operating status notes field is populated, 
- [ ] The text will appear below the _Facility Notice_ indicator 

--- 

When facility type = VA health, VA benefits, VA cemeteries or Vet Centers:
 - [ ] search result cards have a white background. 
 
**and** a facility's operating status is _Limited services and hours_

- [ ] The _Limited services and hours_ indicator appears below the facility name on search result cards
- [ ] The _Limited services and hours_ indicator appears below the facility name on the Facility Detail page

**if** the operating status notes field is populated, 
- [ ] The text will appear below the _Facility Notice_ indicator 

--- 

When facility type = VA health, VA benefits, VA cemeteries or Vet Centers **and** the facility operating status is "Normal services and hours": 
- [ ] search result cards have a white background. 
- [ ] existing functionality is maintained.
- [ ] no operating status icon appears on result card
- [ ] no operating status icon appears on Facility Detail page
- [ ] no text from operating notes field is displayed on Facility Detail page

---

When facility type = urgent care or community care providers (in VA's network):
- [x] search result cards have a white background. 
- [x] existing functionality is maintained.
- [x] no operating status icon appears on result card
- [x] no operating status icon appears on Facility Detail page
