### ISSUE TITLE
[Design] 1010 Forms Shared Content Figma Library

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#76362]
## Issue Description
As a Veteran, I want consistency between the forms when first applying and then updating my health care benefits.

As a Designer, I want a single source or truth to update form questions that are used across both the 10-10EZ and EZR Forms.

- [Link to Figma file created](https://www.figma.com/file/sxGu2QhRKtsUQqZLbSjWJO/FormContent?type=design&node-id=0-1&mode=design&t=tyvUYxu0uRBF1pyW-0)

---
## Tasks
- [x] Create a Figma file 
- [x] Move over existing content components that will need to be shared (TERA)
- [x] Create other content components that need to be shared
- [x] Publish as a library

## Acceptance Criteria
- [x] There is a shared library created of correct Form Content components and both the 1010 figma files reference these instead of using local content.
---

**Comment by jessicastump** [comment]
The main components that are shared between the forms have been added to this Figma library. There will be future tickets needed to utilize and sync up to this library for each of the product design files.
