### ISSUE TITLE
Update the DowntimeBanner

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#76370]
## Description
Context from [Slack thread](https://dsva.slack.com/archives/C04MM3WJN1E/p1707925270394559)

## Tasks
- [ ] Update the `DowntimeBanner` so that it also reads from the `maintenance_windows`
- [ ] The `statuses` should remain relatively the same, where we only check to see if our authentication dependencies have a `status` other than `active`
- [ ] In the `maintenance_windows`, parse the starting time so that the DowntimeBanner is displayed 1 hour before the `maintenance_window` begins for the current date.
    - [ ] For the `maintenance_window`, update the `va-alert` content so that it displays the `start` and `end` timeframe that the service could be down. (There might be an example of this in vets-website somewhere, might have to search and not re-invent the wheel)

**Comment by acaruso-oddball** [comment]
Thanks Riley!
