### ISSUE TITLE
COVID-19 Contact Center KM and Script Creation

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#7638]
## User Story or Problem Statement
As a contact center representative, I need information about COVID-19 so I can answer veteran questions with the correct information and messaging.

or

## Goal
A single source of truth for VA COVID-19 information that is available to all contact center representatives. 

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Receive training in the eGain km system
- [ ] Compile previously created COVID-19 information developed by contact centers
- [ ] Create approved content that is published in eGain

## Acceptance Criteria
- [ ] Completed COVID-19 content in eGain that is available to all contact centers.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Below are the KMs created for eGain distribution. Notification to the eGain team has been done and we are waiting for them to be pushed out to all contact centers:

[VA.gov.FAQs.Benefits.4.6.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4444587/VA.gov.FAQs.Benefits.4.6.docx)
[VA.gov.FAQs.Health.4.6.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4444588/VA.gov.FAQs.Health.4.6.docx)
[VA.gov.FAQs.NCA.4.6.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4444589/VA.gov.FAQs.NCA.4.6.docx)

**Comment by clantosswett** [comment]
The below documents are the next set of content we will be working off of in order to create new scripts/KMs

[KM5558CoronavirusCOVID19VASpecInfo.4.6.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4444597/KM5558CoronavirusCOVID19VASpecInfo.4.6.docx)
[VBA Covid 19 General Information.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4444598/VBA.Covid.19.General.Information.docx)
[VEO Call Center General Information.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4444599/VEO.Call.Center.General.Information.docx)
