### ISSUE TITLE
Find a Rep LIVE - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#76386]
## Issue Description
Live user testing of Find a Representative experience with mobile and assistive technology (AT) users.

## Tasks
- [ ] [Review AT documentation](https://depo-platform-documentation.scrollhelp.site/research-design/research-assistive-technology-sessions)
- [ ] Create GitHub research folder
- [ ] Split mobile vs AT specific content
- [ ] Create research plan
- [ ] [Review AT screeners](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions#Successfulscreenerquestions-AssistiveTechnology)
- [ ] Define screener questions
- [ ] Create conversation guide
- [ ] Submit all materials to team for review
- [ ] [Update CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74488)
- [ ] Create revisions Zenhub ticket

## Acceptance Criteria
- [ ] All materials ready for review

**Comment by oddball-lindsay** [comment]
Open questions to a11y team, waiting for response

**Comment by oddball-lindsay** [comment]
Kickoff with a11y on Thursday 2/29 at 10a ET to understand specifics to move forward

**Comment by oddball-lindsay** [comment]
Separate recruitment efforts for mobile and accessibility studies, but both will roll up to the same report

**Comment by oddball-lindsay** [comment]
Research plan mostly done, halfway through convo guide -- hoping to complete tomorrow for team review
