### ISSUE TITLE
VHA FSR Reason Investigation

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#76409]
## Issue Description
VHA reached out stating they are confused by the FSR reason they are seeing on one of the submissions that came across on February 1st. It turns out that combined FSRs munge together the fsr reasons for each debt/copay of both VHA/VBA. This means that vha could (and has) received submissions with FSR reasons that have nothing to do with them. 
From now on the backend should build FSR reasons from scratch based on the reason provided in each debt/copay on a vha/vba basis. 

**Slack Thread discussion:** https://dsva.slack.com/archives/G01KBHYEXV2/p1708010432911709
**Transaction ID:** `da163fc26a2b4d3b870e492a65aa3da1`

---
## Tasks
(For a combined FSR submission for debts with reasons: ["x", "y"] and copays with reasons: ["a","b"])
- [ ] vba fsrReason should be "x,y"
- [ ] vha fsrReason should be "a,b"
- [ ] vha will not inherit vba reasons and vice versa

**Comment by kjsuarez** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15617)

**Comment by HeatherRienks** [comment]
@kjsuarez - please provide more details here and I can relay them back to Aleena Mirza with Huron. 
Also would like to note the FSR reasons here so we have record of them for future use.

Thanks!
cc: @Tom-Davis

**Comment by kjsuarez** [comment]
VHA FSR reasons: 
- "waiver"
- "monthly"
- "compromise"

Details:
When the front end sends the backend a **combined** FSR submission, they populate the `fsrReason` field with all of the individual reasons from all of the vba debts and vha copays. The backend *should* be repopulating this value for each individual FSR. ie vba FSR only gets reasons for its debts and any vha FSRs only get reasons for their (station specific) copays. Our vba FSR logi was doing this, but not our vha FSR logic.

@HeatherRienks

**Comment by HeatherRienks** [comment]
@denisecoveyduc - FYI

*Discussed with Aleena in 2/23/24 VBS | VODA Sync and Denise followed up with email
