### ISSUE TITLE
[QA] 10-10EZ - TERA:  Complete QA with VES

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76408]
## Benefit to the Veteran
By completing QA using various use cases, we can ensure the new TERA section of the 10-10EZ will be accessible, easy to understand and functional for Veterans to fill out and submit to VA.

## Background
In an effort to quickly identify Veterans who have been exposed to toxic materials during specific time period and/or while deployed at specific locations, the HEC Stakeholders would like to have Toxic Exposure questions added to the 10-10EZ form.
This is intended to quickly identify these Veterans, so they can get the care they need.  It is also intended to providing Veterans a place to add the information so that this information is included in the Veteran's health record.  This information could qualify the Veteran for care they would not otherwise be able to receive. 

As part of adding new questions, we will be introducing new fields to the application.  The fields include Yes/No, Freeform text and Dates.

This ticket is to complete QA in Staging and validate data is flowing as expected to Enrollment System (VES).
Note: Ticket #74986 will cover QA of content and formatting

## Resources
- [Original TERA draft 10-10EZ with sticky notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Archive/TERA%20Draft%202023_10-10EZ.pdf) (May have to download to see sticky notes)
- [Most recent TERA Draft 10-10EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/TERA%20draft%201-23-2024%20VA%20Form%2010-10EZ.pdf)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?fromVisitorModal=true&sender=u5ad49c107baa41137f271007)
- [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=450-19244&mode=design&t=GyO36RKAPEFgXEna-0)

## Tasks

- [x] Reference the [TERA Use Case document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZ-Toxic%20Exposure%20(TERA)%20MVP.md) with assigned volunteers on specific use cases to test
- [x] Complete QA per the Use case document assignment
- [x] Document Test cases tested by you and results (Pass/Fail), including any details of importance and confirmations from VES team on End-to End testing
     - Note - our Staging environment is linked to VES SQA environment 
- [x] Document in this ticket of any conflicts or issues found
- [ ] PM will sign off and close this ticket once all test cases are completed
     - Note - If any bugs are found, the tickets for those bugs will include testing to confirm the fix, and that there are no other issues introduced with the fix
 
## Acceptance Criteria
- The 10-10EZ TERA questions have been tested within the full 10-10EZ form successfully with VES team engagement and success confirmation.

**Comment by hdjustice** [comment]
2/27/2024 - Completed QA with VES to validate End-to-End submission.  All tests were successful.  
QA continues on functionality.

**Comment by hdjustice** [comment]
Functionality findings:
- TERA questions are hidden for Veterans with 50% or higher disability rating.  
     - We should allow all Veterans to view this section for now.
     - Further research will be done to determine whether this should remain.
- The Start and End dates are not validating against each other
     - The End date can be earlier than the start date with no error message.

These findings have been shared with Matt Long

**Comment by hdjustice** [comment]
QA was completed with VES successfully, all changes were made and deployed.
