### ISSUE TITLE
Remove "fragments" from vagov-content, vets-website

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#7640]
The MegaMenu and homepage of va.gov are powered by Drupal in all environments. This means there are some stale files in vagov-content and unused logic in vets-website, so we have an easy opportunity to remove some tech debt.

### Tasks
- [x] Remove the `fragments` directory of vagov-content, https://github.com/department-of-veterans-affairs/vagov-content/tree/master/fragments
- [x] Remove the `apply-fragments` plugin from vets-website, https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/apply-fragments.js
- [x] Remove the function for creating the megamenu out of vagov-content from vets-website, https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/create-header-footer.js#L50

### Acceptance criteria
- [x] Unused code is deleted

**Comment by ncksllvn** [comment]
@MickinSahni This ticket is removing some tech debt related to Drupal and vagov-content. I'm not sure exactly which team should own it, but it shouldn't take long.

**Comment by MickinSahni** [comment]
👍 can you throw an estimate on it and we'll add it to this sprint if we can knock it out before tomorrow? @ncksllvn

**Comment by ncksllvn** [comment]
This is done but being tech debt there isn't an effect on the website. But we deleted a lot of unused code -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/b173552a-3b8d-4439-bc47-52b3cdce72f1)

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/4c17dbea-1d4f-4b66-af9c-b431e3e28d3c)
