### ISSUE TITLE
Bug - "Save" on VA medical records scrolls you back to the top of the section

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#76403]
## Issue Description
I noticed a small bug or usability issue as I fill out the 526. (Just filling it out in order to make sure I can get the latest screenshots of the banking info.)
On the VA medical records page, when you click "Save," it scrolls you back to the top of the section.
Expected behavior, per the Design System multiple responses pattern:
Once an initial item is saved it collapses down into a Card with, at minimum, an “Edit” button, and often, a “Remove” button.
The “Add another” button stays visible so that additional entries can be made.
The impact is that the user perceives they've missed a required field
Just sharing in case you want to log it for consideration--it's not major, but I tried clicking save 4 times thinking I was missing something. - Julie Strothman

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
-  Expected behavior, per the Design System multiple responses pattern:
Once an initial item is saved it collapses down into a Card with, at minimum, an “Edit” button, and often, a “Remove” button.
The “Add another” button stays visible so that additional entries can be made

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by freeheeling** [comment]
@RakshindaAslam This issue was also reported by the Veteran Support Team on Slack in #benefits-disability [here](https://dsva.slack.com/archives/C04KW0B46N5/p1705435531936429) on 1/16/24, with additional documentation and a video [here](https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/73690).

**Comment by mengA6** [comment]
Maybe related to [Address the "bounce-down" effect on certain screens within the 526#79755](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79755)
