### ISSUE TITLE
Datalayer for metrics tracking operating status on Pittsburgh VAMC pages. 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7641]
##  Problem Statement
How might we assess the value of COVID-19 alerts and operating status displays at a facility level?

## Goal
The ability to track COVID-19 alerts to confirm Veterans are able to get the information they seek

## Objectives or Key Results this is meant to further
-Objective 2: Deliver meaningful facility information

---

## Tasks
Add Datalayer Requirements as outlined in the [README](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7336) 
- For clicks within the banner, the event in the table below can be applied to the other links within the alert box not shown in screenshot as well if needed

- [ ] Add datalayer for clicks on links within the banner 
- [ ] Add datalayer for clicks on Facilities in 'Facility operating statuses' list 
- [ ] Add datalayer for clicks on Facility Notice Info Box

Interaction | Screenshot | Datalayer Requirements
------------ | -------------  | -------------
Clicks on links within the banner | ![image](https://user-images.githubusercontent.com/48527022/78252462-e1428f80-74c0-11ea-9ef2-864509dbeae3.png) | ```dataLayer.push({```<br>```'event':'nav-warning-alert-box-content-link-click',``` <br>```'alertBoxHeading': 'Help Limit the Spread of COVID-19 and other illnesses'```<br>```});```  | 
Clicks on Facilities in 'Facility operating statuses' list | ![image](https://user-images.githubusercontent.com/48527022/78252860-7f365a00-74c1-11ea-849a-75042f200476.png) | ```dataLayer.push({```<br>```'event':'nav-health-care-facility-click'});```
Clicks on Facility Notice Info Box | ![image](https://user-images.githubusercontent.com/48527022/78253647-b8bb9500-74c2-11ea-97a6-5da40613a021.png) | ```dataLayer.push({```<br>```'event': 'nav-info-box-click',```<br>```'infoBoxText': 'Facility Notice'});```

## Acceptance Criteria
- [ ]  The number clicks on the COVID-19 alert from any page in VA.gov can be tracked. 
- [ ]  The number clicks on Facilities in 'Facility operating statuses' list can be tracked. 
- [ ]  The number clicks on Facility Notice Info Box can be tracked. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@davidconlon FYI
