### ISSUE TITLE
Update Styling for Medallia 2.0 Surveys in Staging

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#76423]
## Issue Description
_As an Engineer User, I need to have styling for the first two Medallia 2.0 forms closely match the VA Design system. This will ensure that future surveys will have a consistent look and feel.

Forms being styled:
- Debt portal custom button survey (survey 29)
- VHA intercept survey (survey 41)

---
## Tasks
- [x] Match each form element to the VA Design system
- [x] Match hover and focus states on all elements
- [x] Q/A forms on both desktop and mobile

## Acceptance Criteria

- [x] Forms elements appear to match the VA Design system 
- [x] Forms work as intended
- [x] Forms appear correctly on mobile and desktop

**Comment by ATMiddleton** [comment]
In conjunction with #75845

**Comment by ATMiddleton** [comment]
VHA intercept and Debt portal.

@ATMiddleton will create tickets for IIR and AVS surveys for styling.
