### ISSUE TITLE
Migrate and update FMB hub page

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#76428]
## Issue description

There will also be changes to the existing family members landing page, OR creating a new landing page and redirecting the old one. This ticket will capture that decision and related work.

---
## Tasks
- [x] Derek - Clone Family member hub page under the new URL
- [x] Laura - Review page
- [x] Sara - Copyedit and prepub
- [x] Danielle - Send to SMEs for awareness
- [x] Publish - **Coordinated effort**
- [x] Kristin - set up redirect for new URL (ticket with sitewide pw)
- [x] Kristin - change mega menu title to the new H1 of the page

## Acceptance Criteria
- [x] Migrated hub page has the correct URLs and breadcrumbs in prod
- [x] Migrated hub page shows up correctly in left nav and megamenu

**Comment by kristinoletmuskat** [comment]
Started phase 1 IA work here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1712161697570

I'm connecting with Mikki tomorrow to ask some Qs then will get back to ya'll.

**Comment by kristinoletmuskat** [comment]
Hey hey done with the IA spec draft -- if ya'll could review it and lmk if you have any open Qs. I imagine Qs might come up as you start building the page too.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md

**Comment by d-beyer** [comment]
@kristinoletmuskat I'm just noticing that the crosslinks section of the IA spec doc and the "Content links by hub" section of the Mural don't always agree. I have been working on pages using the IA spec. Is one more authoritative than the other?

**Comment by kristinoletmuskat** [comment]
@d-beyer yes def use the IA spec

**Comment by laurwill** [comment]
@kristinoletmuskat following up about content changes needed. Here's my list so far:
- Clone hub page at new URL
- Change H1 to VA benefits for family and caregivers
- Change links to point to new subhub landing page for each benefit type
- Remove Employment link and blurb because ch 36 is now linked from Education subhub landing page
- Replace 2 burials links with link to burials subhub landing page
- Replace survivors pension and DIC links with link to new survivors comp subhub landing page
- Remove More resources section (2 links are covered on subhub landing pages, 1 is sunsetting)

And here are my open questions:
- Page currently separates family benefits from caregiver benefits — do we merge these and rely on the link and blurb for the health care and disability subhub landing page to direct caregivers to their benefits? Or do we want to keep caregiver benefits more prominent/findable on this page?
- Are we keeping the bolded "For spouses, children...." etc audience tags? Or relying on links and blurbs to clarify which audiences have benefits in which hubs? (And if we're keeping the bolded audience tags here, would we also use them on the subhub landing pages under individual page links & blurbs?)
- Are we keeping the "Help a Veteran find benefits" gray box at bottom?

**Comment by laurwill** [comment]
@d-beyer this main FMB hub page is also ready for you to clone and adjust using the [list of changes here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76428#issuecomment-2119468036). Let me know if you find more things we need to adjust here.

**Comment by laurwill** [comment]
Thanks @d-beyer ! I adjusted the H2 to reflect the merge and tweaked intro slightly, but I think mostly fine as is.

@saratorres2 this main family member hub page is ready for copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=69595

Noting I'm still trying to fix the phone number in the crisis line box—you can ignore that for now.

**Comment by saratorres2** [comment]
@laurwill Copy edits complete for this page. Did we decide to keep the boldface text below each hub blurb under H2 "Benefits for spouses, dependents, survivors, and caregivers" (rather than above the blurb)?

**Comment by laurwill** [comment]
Oohhhhh no I just forgot! Totally forgot to move it. I'll do that now :) Thanks for the reminder.

**Comment by kristinoletmuskat** [comment]
Confirmed working in prod.
