### ISSUE TITLE
Edit "Monitor Tagging Standards" -- OCTO Ticket #1 of 6

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#76431]
This is the first ticket generated from #76094. According to POC/SME Mike Chelen, this section of the [original document](https://vfs.atlassian.net/wiki/spaces/~642825999/pages/2861728279/Monitoring+and+Alerting+Best+Practices?atlOrigin=eyJpIjoiY2RmY2YyZDNiZWFjNDRmMGI0ZDBjYTMzMGIzNjhkY2UiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) is the farthest along on its journey toward deployment. As per our [conversation in Slack](https://dsva.slack.com/archives/D06JFRMQ7GF/p1708000481748819), I have instructed Mike to copy the section and create a new doc in the Platform Website Drafts Space so that he and I can edit it together. 

That doc now exists in the drafts space: [Monitor Tagging Standards](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2966388918/Monitor+Tagging+Standards). 

### TASKS

- [x] Format page for deployment
- [x] Edit Page for deployment
- [x] Flag any issues that need POC/SME expertise to fix
- [x] Fix all issues with page
- [x] Check for LBers. 
- [x] Move to its final home in the IA.
- [x] Deploy. 

### DEFINITION OF DONE

- [x] Page is live on Platform Website.

**Comment by BSmolensky** [comment]
First edit pass complete. I reformatted the page, changed some language, added some mandatory elements. Two issues found:

1. There is one special access link that needs either access-required language after it or the link needs to be replaced with a public link. 
2. I would like to add an additional resources section that can send users who have questions to get help. This is all new info so I think folks might have some questions. Waiting on SME advice on what to include here. 

Didn't hear from POC/SME today. Hopefully Monday or Tuesday of next week. Page is really closed to finished.

**Comment by BSmolensky** [comment]
I didn't hear back from POC in time for this page to get published this week. But, since this is a high-priority ticket, I did an off-cycle deployment at 9pm ET on Thur 2/22. The page is now live on the PW: https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards

**Comment by BSmolensky** [comment]
This ticket is now ready to close.

**Comment by jknipes** [comment]
Tasks completed, moving to _Done_
