### ISSUE TITLE
Managing Signal to Noise Ratio - OCTO Ticket #2.5 of 6

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#76435]
This is the second ticket generated from #76094. Once this section is ready, it will be moved to the Draft Space for editing. 

Doc now exists in the drafts space: https://vfs.atlassian.net/wiki/spaces/PWD/pages/3043164489/DRAFT+Managing+Signal+to+Noise+Ratio

### TASKS
- [x]  Fix all issues with page
- [x]  Check for LBers.
- [x]  Move to its final home in the IA.
- [x]  Deploy.

### DEFINITION OF DONE
- [x]  Page is live on Platform Website.

Related Ticket: [78823](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78823)

**Comment by BSmolensky** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/76435?planning-poker) with Zenhub @BSmolensky

**Comment by BSmolensky** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/76435?planning-poker) with Zenhub @taylojill

**Comment by jknipes** [comment]
Waiting on Subject Matter Expert for next steps

**Comment by jknipes** [comment]
ticket moved to backlog due to blocker, unable to get response from SME.

**Comment by jknipes** [comment]
@EWashb we had planned this work, which was worked on with Mike Chelen. We are currently blocked until we can connect with another SME.

**Comment by jknipes** [comment]
ZenHub auto-assigned to sprint 3/14-27, but we are not picking up this work for this sprint.

**Comment by acrollet** [comment]
@jknipes checking in on this, I believe the draft doc to be linked is here: https://vfs.atlassian.net/wiki/spaces/~642825999/pages/2861728279/WIP+Monitoring+and+Alerting+Best+Practices#Managing-Signal-to-Noise-Ratio

What do you need to be unblocked? Thanks!

**Comment by BSmolensky** [comment]
@acrollet - Joe is OOO today but we will meet on this as a team tomorrow and let you know. Thank you for your patience.

**Comment by acrollet** [comment]
@BSmolensky no worries and thank you!

**Comment by BSmolensky** [comment]
@acrollet - I am looking forward to working on this with you! Before I can work on it, however, I need you (or someone on your team) to move the doc to the [Platform Website Drafts](https://vfs.atlassian.net/wiki/spaces/PWD/overview) space. This way I can edit, comment on it, and eventually move it to its final home in the IA. 

The process that I worked out with Mike Chelen was as follows:

1. Someone moves the doc to the drafts space. 
2. I format the page
3. I edit the page
4. I flag any issues that need your expertise to fix
5. You and your team fix those issues (if there are any) 
6. Then I check the page for any [launch blocking issues](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page#Launch-blocking-issues.1) 
7. You and your team decide where in the IA this page should live.
8. I move it to that location in the IA
9. The final page gets deployed during our teams next deployment window. 

Please let me know if you have any questions about -- or changes to  -- this process. Please let me know when the page has been moved to the drafts section. And again, I look forward to working on this! Have a great night.

**Comment by BSmolensky** [comment]
Page is in the IA and is waiting to get deployed later today. Once deployed, this ticket is ready to close. 

Location of page: https://vfs.atlassian.net/wiki/spaces/pilot/pages/3043164489

**Comment by BSmolensky** [comment]
Page is now live on the PW: https://depo-platform-documentation.scrollhelp.site/developer-docs/managing-signal-to-noise-ratio

Ticket is good to close.

**Comment by jknipes** [comment]
Work is completed, moving to _Done_
