### ISSUE TITLE
Creating Effective Monitors - OCTO Ticket #3 of 6

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#76436]
This is the third ticket generated from #76094. Once this section is ready, it will be moved to the Draft Space for editing. 

**Specifically [Creating Effective Monitors doc](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3019243521/WIP+Creating+effective+monitors), linked from Monitoring at Alerting BP.**

**SME: Adrian Rollett**

- [x] Doc now exists in the drafts space: [Creating Effective Monitors doc](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3019243521/WIP+Creating+effective+monitors), linked from Monitoring at Alerting BP.**

### TASKS
- [x] Review page with SME 
- [x] Format page for deployment
- [x]  Edit Page for deployment
- [x]  Flag any issues that need POC/SME expertise to fix
- [x]  Fix all issues with page
- [x]  Check for LBers.
- [x]  Move to its final home in the IA.
- [x]  Deploy.

### DEFINITION OF DONE
- [x]  Page is live on Platform Website.

**Comment by BSmolensky** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/76436?planning-poker) with Zenhub @laucon

**Comment by BSmolensky** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/76436?planning-poker) with Zenhub @taylojill

**Comment by BSmolensky** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/76436?planning-poker) with Zenhub @BSmolensky

**Comment by jknipes** [comment]
cc: @acrollet

**Comment by BSmolensky** [comment]
I reached out to SME to determine the current state of the page. Once I hear back, I will begin work on editing, formatting, and flagging the doc -- all to prep of for deployment

**Comment by BSmolensky** [comment]
I have performed a style edit, copy edit, and formatting edit on the page. I have also flagged a few issues for the SME. Once I hear back from SME, I will make final changes, check the page for deployment and then move it into the IA for deployment.

**Comment by BSmolensky** [comment]
Page is final and approved by SME. Page has been moved to its home in the IA. Page will be deployed today. Once page is deployed, this ticket can be closed.

**Comment by BSmolensky** [comment]
This page is now live on the PW: https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-effective-monitors
This ticket can be closed.

**Comment by jknipes** [comment]
Closing ticket as _Done_ per previous comment
