### ISSUE TITLE
Metrics to support Left Nav update

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7643]
###  Problem Statement
How might we assess the success of the Left Nav upgrade?

## Goal
-Assess user traffic Pittsburgh VAMC Left Nav compared to "Top Tasks" and page content to determine if the Left menu supports navigation to the most frequently visited page content. 

## Objectives or Key Results this is meant to further
-Objective 3: Deliver a usable and accessible experience

---

## Tasks
Add Datalayer Requirements as outlined in the [README](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7336) 
- Presently in production, we have an event for ```nav-accordion-expand``` or ```nav-accordion-collapse``` event for where the left nav is capable of being expanded or collapsed. **We would like to deprecate that convention in place of ```nav-sidenav-expand``` and ```nav-sidenav-collapse``` wherever present within the Pittsburgh health care sections.** Please find the new examples within the table below in rows 4+5
- The event ```nav-sidenav``` should continue to be used for such content that occurs **on a direct click of a left nav content item that is not expandable or collapseable and not within a expandable or collapseable nav**
- The event ```nav-sidenav-child``` should be used for such nav components that are contained **within an expandable or collapseable nav component**. The variable ```'sidenav-dropdown-header'``` should populate with the dropdown header.

-[ ] Add datalayer for clicks on Left Nav Dropdowns - Expands
-[ ] Add datalayer for clicks on Left Nav Dropdowns - Collapses
-[ ] Add datalayer for clicks on Left Nav - Child
-[ ] Add datalayer for clicks on Left Nav - Content Only

Interaction | Screenshot | Datalayer Requirements
------------ | -------------  | -------------
Clicks on Left Nav Dropdowns - Expands | ![image](https://user-images.githubusercontent.com/48527022/78256205-37fe9800-74c6-11ea-8373-300a0cc5b237.png) | ```dataLayer.push({```<br>```'event':'nav-sidenav-dropdown-expand',```<br>```'sidenav-dropdown-header': 'About us'});```
Clicks on Left Nav Dropdowns - Collapses | ![image](https://user-images.githubusercontent.com/48527022/78256916-29fd4700-74c7-11ea-9f80-b8667574001b.png) | ```dataLayer.push({```<br>```'event':'nav-sidenav-dropdown-collapse',```<br>```'sidenav-dropdown-header': 'About us'});```
Clicks on Left Nav - Child | ![image](https://user-images.githubusercontent.com/48527022/78258934-f8d24600-74c9-11ea-9695-94224b21f703.png)) | ```dataLayer.push({```<br>```'event':'nav-sidenav-child,```<br>```'sidenav-dropdown-header': 'Locations'});```
Clicks on Left Nav - Content Only | ![image](https://user-images.githubusercontent.com/48527022/78259925-5024e600-74cb-11ea-8274-5b1eda85548a.png) | ```dataLayer.push({```<br>```'event':'nav-sidenav'});```

## Acceptance Criteria
- [ ]  The number of clicks on the Left Nav content can be tracked. 
- [ ]  The number of clicks on Left Nav accordions can be tracked. 
- [ ]  The number of clicks on Left Nav child pages can be tracked. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@davidconlon FYI
