### ISSUE TITLE
Reenable Unit Test Coverage Report S3 Uploads

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#76432]
## Issue Description
While troubleshooting the CI issues, we turned to parallelization by app as a temporary solution for unit tests. However this presented a problem with S3 uploads as not every app has unit tests. Trying to upload a file that doesn't exist results in an error that fails the workflow. This was not an issue prior as there was only one set of unit tests and there were always some to run. 

---
## Tasks
- [x] Adjust the S3 upload to use a conditional upload
- [x] Test to ensure this passes without issue in CI for all parallel processes

## Acceptance Criteria
- [ ] S3 uploads are flowing again with no errors in CI.

**Comment by CBonade** [comment]
While the test coverage uploads have been reenabled, the report now only shows the most recent upload because it was not designed to expect multiple results sets. We will need to come up with a solution (separate ticket) to combine the results while generating the coverage report. These single-app reports, though, are uploading successfully once again.
