### ISSUE TITLE
Add github handle and email to the User.from_omniauth method

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#76458]
### Summary

Github handle and email are now required for team members. Users are assigned to team members when they login via Github. Github handle and email should be included when searching for team members.

### Tasks

- [ ] Add email and github handle [here](https://github.com/department-of-veterans-affairs/platform-atlas/blob/master/app/models/user.rb#L27)
- [ ] Update spec files, [here](https://github.com/department-of-veterans-affairs/platform-atlas/blob/master/spec/models/user_spec.rb)
- [ ] Login and match a team member by email
- [ ] Login and match a team member by github handle

**Comment by RachalCassity** [comment]
@jennb33 This ticket has already been completed in a previous sprint. Closing now.
