### ISSUE TITLE
EPIC | Direct Deposit API Failures 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76474]
> [!Note]
> Previous work in #51900
> This will also likely impact our CH33 EDU DD Migration Work in #76202 

## Background
We're seeing ongoing issues with direct deposit backend systems. We saw similar failure rates when data was running through EVSS and now that we've migrated to Lighthouse we're continuing to see failures. 

The goal of this epic is to work through those failures/issues with BIS (formerly BGS)

## Tasks
```[tasklist]
### Issues List
- [ ] **Gotta take care of this one and find the answers!** we're at the mercy of BGS and LH to get us answers
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65736
- [ ] **Then these others can be worked on:**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/63876
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64357
```

**Comment by mtcA6** [comment]
we're not really seeing these errors the same way we were and I think it's best to spin up a new ticket later on if this is still a problem
