### ISSUE TITLE
Design | EDU CH33 Changes | Alert in hub and direct deposit page for CH33 Changes

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76478]
Add messaging to the profile that lets people know about the upcoming need to reconcile C&P and edu info

## Tasks 
- [x] identify the scenarios where to show the alert 
- [x] mock up the alerts 
- [x] get content approval 
- [x] review w/PO/PM 
- [x] move to validate for FE 

## Acceptance Criteria 
- [x] we have approved content and have landed on a design for displaying the required messaging.

**Comment by andaleliz** [comment]
@Samara-Strauss and @mtcA6 I was able to work w/ Danielle async this afternoon. What do you think about [this alert ](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=142-3867&mode=design&t=5wDiwik5CdmykUCi-11) for folks who have both DD types?

**Comment by Samara-Strauss** [comment]
@andaleliz question -- is this showing to everybody, or only people who receive both types of benefits? I think this is fine for people who receive both, but if everyone sees this message, they might get a little confused. In that case, it would  be helpful to clarify this message only applies to people who receive both comp & pen and edu benefits.

**Comment by andaleliz** [comment]
This is would show for people who receive **both** benefits. 

We won't show an alert for people who have _only_ edu, or _only_ c&P.

**Comment by andaleliz** [comment]
@mtcA6 I put the desktop and mobile mock-ups [here](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=142-8730&mode=design) and will migrate them into the appropriate spots in the Figma file once they're live.  Check out the snazzy "Ready for Dev" label Figma has! Talk about a Fancy Form ;)

**Comment by mtcA6** [comment]
@andaleliz did we want to show on the hub as well?

**Comment by andaleliz** [comment]
@mtcA6 ah yes, we did talk about that in planning. Thank you for reminding me! I'm working through that now with Adam.  The fact that MHV/DS Logon folks can't change anything in DD makes this more complicated than I initially realized. I'll report back!

**Comment by andaleliz** [comment]
@mtcA6 @Samara-Strauss and @adamwhitlock1 I have a couple of mock-ups for the hub, and am interested to know your thoughts. These have been reviewed and approved by Danielle, so we could move forward if we're all on the same page.

There are 2 scenarios on the hub to account for:

**1. People logged in with login.gov or ID.me**
   - The FE code on the hub page checks for DD information, so we could conditionally show an alert only to folks we know have both dd types.  The[ mock-up is here](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=150-10067&mode=design&t=1NWKTE7In3wx2IJL-11). 
   - Since the acct info is masked, and we can't check whether or not both accounts are already the same, I made the alert dismissible. It could be frustrating at a minimum, and triggering/stressful in a worse case, to continue to see this once a person has taken the action.

2. **People logged in with MHV or DS Logon**
  - The FE code on the hub page does NOT check for DD information, so we have to show an alert to everyone logged in with these credentials. 
  - We can't send them to the DD page directly from here, because that is a dead end for them.
  - Danielle and I wrote an alert that tells them changes are coming, and they need to sign in a different way. It's long. If we want to shorten, it we can remove the sentence "You must have a modern, verified account to update direct deposit information online.", but that means people won't understand why they can't just go to DD information.  [Here's a mock-up of the hub](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=156-2110&mode=design&t=1NWKTE7In3wx2IJL-11) for that one.  I also think we should replace [the current MHV/DS Logon](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=0-2&mode=design&t=1NWKTE7In3wx2IJL-11) alert for these folks with this updated one ([mock up](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=156-4480&mode=design&t=1NWKTE7In3wx2IJL-11)).

Let me know your thoughts, especially if they involve other scenarios I haven't accounted for :)

**Comment by mtcA6** [comment]
@andaleliz could we go through this on a call?

**Comment by andaleliz** [comment]
sure feel free to grab an open time.

**Comment by Samara-Strauss** [comment]
@andaleliz do you need any additional feedback, or did our meeting earlier cover it?

**Comment by andaleliz** [comment]
@Samara-Strauss the only additional feedback I need at this point is on the shortened, updated text.  Danielle felt the revision we had at the end of the meeting was confusing, and offered an alternative, which is in [this mock-up](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=156-2110&mode=design&t=1NWKTE7In3wx2IJL-11).

What do you think?

**Comment by mtcA6** [comment]
I feel like that's more confusing, they won't know (and we cant tell) if they have two bank accounts listed unless they log in.

**Comment by andaleliz** [comment]
More confusing than [the original, long text](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=150-10359&mode=design&t=1NWKTE7In3wx2IJL-11)?

**Comment by Samara-Strauss** [comment]
IMO the second copy is clearer, though it's still long and the whole thing is confusing in general. But I don't know that there is any way around that because what is happening behind the scenes requires a lot of dot-connecting and is inherently confusing.

Something about this still doesn't feel right. Are MHV or DS Logon users going to assume the receive payments they may not actually receive? Do we really feel like this is the least confusing path (acknowledging all paths feel unideal)? I need more time to think about this.

**Comment by andaleliz** [comment]
Is showing no alert related to direct deposit in the hub for mhv or DS
logon users reasonable?

Maybe we are making the situation worse than it would be otherwise for
them. they will still see the alert on the direct deposit page, and get
communications from other channels.

**Comment by andaleliz** [comment]
I sent a message last night via email that did not come through clearly, and deleted it.

What I was _trying_ to say, is for MHV/DSL folks maybe the least confusing path would be to show nothing on the hub page. The hub page is just one of many places they'll get this information, and from what I can tell so far, the comms send them directly to the DD page, where they'll still see something prompting them to sign in with a different credential if they ignore it every other place they encounter it.

Happy to jump on a call today to talk through options, if that's helpful.

**Comment by mtcA6** [comment]
@andaleliz not more confusing than the original, more confusing than the modified text we crafted together.

I agree, the more I think on it, the less I think we should show it, if the comms lead users to the DD page, they'll see the current messaging which should help lead them down the right path to allow them to modify things.

**Comment by Samara-Strauss** [comment]
I would be more than thrilled to *not* show messaging to DS Logon/MHV users on the hub page.

**Comment by andaleliz** [comment]
Wonderful.  On the DD page, for these users, I think we should post the latest version of the alert in [this mock-up](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=156-4480&mode=design&t=2tLWkThOw2NIynZv-11), instead of the [current sign-in alert](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=0-2&mode=design&t=2tLWkThOw2NIynZv-11).

My thinking there is if they somehow happen into the DD section, and see the current alert, they may not realize they really _should_ get with the modern creds and check on their DD information.

**Comment by andaleliz** [comment]
@mtcA6 I think this is ready for FE, if everyone is on board with what I've proposed.

**Comment by mtcA6** [comment]
Thanks Liz, I've updated [FE | EDU CH33 Changes | Build the new alert](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76715) and included that breakdown you shared above. 

@Samara-Strauss I'm closing this out, reopen if you have objections
