### ISSUE TITLE
Update and publish future education rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#76483]
## Issue Description

We need to publish several future education rates pages so that Veterans can check the rates for the upcoming school year. These pages include:

- Post-9/11 GI BIll
- Fry Scholarship
- STEM scholarship
- Transferred benefits
- VET TEC

As part of this work, we need to revert already created future rates pages to the state where we have specific rates listed. For STEM, transferred benefits, and VET TEC we need to create new future rates pages. We'll also need to add these pages to the left nav

## Tasks
- [ ] Add rates info to Post-9/11 GI Bill (Randi)
- [ ] Add rates info to Fry Scholarship (Randi)
- [ ] Create STEM Scholarship future rates page (Randi)
- [ ] Created Transferred benefits future rates page (Randi)
- [ ] Create VET TEC future rates page (Randi)
- [ ] Copyedit and publish Post-9//1 Biil page (Megan/Sara)
- [ ] Copyedit and publish Fry Scholarship (Megan/Sara)
- [ ] Copyedit and publish STEM Scholarship future rates page (Megan/Sara)
- [ ] Copyedit and publish Transferred benefits future rates page (Megan/Sara)
- [ ] Copyedit and publish VET TEC future rates page (Megan/Sara)
- [ ] Add new future rates pages to left nav (Megan/Sara)

## Acceptance Criteria
- [ ] All future rates pages are live and showing in left nav

**Comment by RLHecht** [comment]
@megzehn These pages are now ready for you! I'm attaching the source material I was given. Also note that there's a new category for preparatory courses that isn't on our current rates pages. I sent the content to our stakeholder and she approved the language we're using. Let me know if you have any questions!


[Ch33 UPDATED AY2024-2025  Updated Rates For D_Jamak Clifton.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/14434882/Ch33.UPDATED.AY2024-2025.Updated.Rates.For.D_Jamak.Clifton.pdf)

**Comment by megzehn** [comment]
Checking these off as I copy edit

- [ ] Copyedit Post-9//1 Bill page (Megan/Sara)
- [ ]  Copyedit Fry Scholarship (Megan/Sara)
- [ ]  Copyedit STEM Scholarship future rates page (Megan/Sara)
- [ ]  Copyedit Transferred benefits future rates page (Megan/Sara)
- [ ]  Add new future rates pages to left nav (Megan/Sara)

**Comment by RLHecht** [comment]
@megzehn Here are the MHA numbers that Tammy sent me: 
Online - 1177.50
Foreign - 2355.00

**Comment by megzehn** [comment]
@RLHecht confirming I reviewed and published these updates and added STEM and transferred benefits to the left nav. 

Thank you again for adding these!! Moving to validate. @strelichl, I'll add this to the capacity tracker and close it out on Monday.
