### ISSUE TITLE
[UXPin] Export prototypes and move them Debt Team Sharepoint

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#76487]
## Description

As a part of the migration of Sketch to Figma, our UXPin account has been sunsetted. So we'll need to export all the prototypes that were created in UXPin to the Debt Team's Sharepoint drive to archive them. 

Given: A designer or stakeholder needs to view an old prototype
When: A designer logs into the Debt Team's SharePoint
Then: A designer can view all the old UXPin prototypes 

## Tasks
- [x] Export all UXPin prototypes
- [x] Move them to [Debt Team sharepoint](https://dvagov.sharepoint.com/:f:/r/sites/vadebtresolutionteam/Shared%20Documents/UX%20Pin%20prototypes?csf=1&web=1) (Have to be logged into VA Netwrok to view these) 

## Acceptance criteria

- [x] All UXPin prototypes have been exported
- [x] All UXPin prototypes have been moved to Debt Team Sharepoint

## Testing
- [x] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
This is done! 

cc: @mgleo @charlottecesana 

@HeatherRienks, we can close our UXPin account now!

**Comment by josephrlee** [comment]
@Tom-Davis moving this to Validate now!

**Comment by Tom-Davis** [comment]
Closing as complete.
