### ISSUE TITLE
Phase Two Platform Support Analytics: Office Hours/Brandon

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#76502]
## Description 
We are looking to add the metrics that are in Looker into our DOMO dashboard.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify what the scope of adding the data from Looker into DOMO would look like 
- [x] Attend Platform Analytics office hours with any clarifications or questions (if there isn't enough time schedule a one-off call with Basil, Johnny and invite Curt Bonade as optional so he understands how we are moving forward since he is building out our Support Bot periodically)
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Reassigning due to unexpected volume of support tickets that took priority.

**Comment by AnthonyWFlowers** [comment]
Using slack reached out [here](https://dsva.slack.com/archives/CKCRMLGAC/p1739288188142229)

**Comment by alyssagallion** [comment]
Moved to next sprint since we need to attend office hours Thursday (next sprint).

**Comment by alyssagallion** [comment]
Data successfully pulled. Will create another ticket for asking Platform Analytics to pull information into our DOMO dashboard officially.
