### ISSUE TITLE
[bug] SC | Fix submission blocking with partial data

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#76516]
## What happened? 

After examining a validation error for Supplemental Claim in DataDog, we noticed that the Veteran was unable to submit a Supplemental Claim after partially adding a VA evidence location, then backing out and choosing not to include VA evidence. Upon submission, the error that shows up is related to missing data for the VA location. This appears to be a validation problem when partial data is provided. So we will need to remove the required schema fields if the Veteran chooses not to provide that type of evidence.

This may also occur when private evidence or upload evidence is partially added, then removed. So we need to test and include these situations.

- [DataDog RUM session](https://vagov.ddog-gov.com/rum/replay/sessions/626c231c-103d-4bd2-a46d-cd5e2e39dfaf?seed=c1b9c840-6970-4f3b-a407-93acd72bd0cf&ts=1708033993182)
- [DataDog save-in-progress error message](https://vagov.ddog-gov.com/logs?query=%22Validation%20issue%20not%20displayed%22%20%40service%3Abenefits---supplemental-claim&agg_q=%40application_id&agg_q_source=base&cols=service&event=AgAAAY2u49UCcs_ZMgAAAAAAAAAYAAAAAEFZMnU0LUxnQUFBeUl3amliT1pSTWdBQwAAACQAAAAAMDE4ZGFlZTQtMDVkMy00YWY1LWEyOTAtMGI2MWFjNmU0MzY3&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort_m=&sort_t=&stream_sort=%40session_id%2Casc&top_n=10&top_o=top&viz=stream&x_missing=true&from_ts=1707925094884&to_ts=1708097894884&live=true)

**Add the steps to reproduce the bug**:
1. Select the submit evidence option
2. Add add evidence
3. Page back and select "No" to evidence option

**Add a screen recording or photo**:

## How severe is the problem?
- [x] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP. 
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint. 

## What is the desired behavior?

1. When a user chooses the evidence option, then changes their mind and backs out, the action does not generate a blocking error that confuses them.
2. The schema doesn't block the user when they switch options after uploading evidence.
3. Logging captures an error if the user tries to skip uploading evidence after they select "Yes"

## Tasks
- [ ] Prevent generic validation error alert, when partial unnecessary data is included
- [ ] Remove required schema for VA evidence, if the choice to not include VA evidence is made
- [ ] Remove required schema for private evidence, if the choice to not include private evidence is made
- [ ] Remove required schema for upload evidence, if the choice to not include upload evidence is made
- [ ] Add or update unit and e2e tests
- [ ] Add tests & set up test data
- [ ] Tested in review instance and staging (after merge)

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by saderagsdale** [comment]
May have a PR pushed today.

**Comment by Mottie** [comment]
@sade & @eileen-coforma you can test this by:
- Start Supplemental Claim
- [Copy this save-in-progress data](https://raw.githubusercontent.com/department-of-veterans-affairs/vets-website/main/src/applications/appeals/995/tests/fixtures/data/partial-evidence-test.json) and paste it into the save-in-progress menu. It adds partial VA, private & upload evidence, then sets all the yes/no questions to "No". You can do the same thing by:
  - Choosing "Yes" on the provide evidence page
  - Partially fill out the evidence page
  - Navigate back without completing all required fields (uploads can leave off the document type selection)
  - Choose to keep the partial data in the modal
  - Choose "No" from the provide evidence page
  - Continue the above process for all 3 sections.
- Submission from the review & submit page will go through - you won't see the generic validation issue alert

**Comment by Sade** [comment]
Please stop using @Sade mention, I'm not part of this project...

**Comment by eileen-coforma** [comment]
Validated that:
If a user backs out of adding VA medical, private medical, and uploaded evidence, leaving partial data, they are able to move forward and submit if they select "no" for all evidence submissions.

**Comment by data-doge** [comment]
Robin hasn't seen any reoccurrences of this error since deploy yesterday. If that remains the case by next bug triage, we can probably close.

**Comment by HeatherWidmont** [comment]
Will check in during bug triage tomorrow
