### ISSUE TITLE
[CST] Update color of tab underline to `$color-gray-light`

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#76521]
## Background Context
The Platform team has been asking us to make the line in our [tab component](https://www.figma.com/file/lbRZz68qGRGTdUigcoJq3a/Local-BMT-Components?type=design&node-id=33-29&mode=design&t=nIWhZRRdoUhUes62-4) a bit darker. We should update it to `$color-gray-light` which also matches the color value used for our ListItem component. 

This will be better for color contrast and a11y.

## Design

<img width="1362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82ef1e93ae4af53c40764d878138fafdc4c3fb6a/Screenshot%202024-02-16%20at%205.11.38%E2%80%AFPM.png" alt="Screenshot 2024-02-16 at 5.11.38 PM.png" />

## Engineering 
- Update this line to `$color-gray-light` Hex code: #A9AEB1

## Tasks
- [ ] Update the line color for the tab component
- [ ] Design QA

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Product performs functional QA and verifies acceptance criteria was met
- [ ] Engineering identifies staging users required to test and shares account and credentials with product

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by pmclaren19** [comment]
@skylerschain @jacobworrell this ticket is ready for validation and Design QA.

**Comment by jacobworrell** [comment]
@pmclaren19 validated from my perspective

**Comment by skylerschain** [comment]
LGTM 👍
