### ISSUE TITLE
[Design] Stakeholder Interviews Prep

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7653]
## User Story or Problem Statement
As a designer, I need to prepare for stakeholder interviews so I can ask valuable, consistent questions to debt letter stakeholders in a timely manner.

## Goal
_What outcome(s) do we want to see?_
A solid plan for stakeholder interviews

## Tasks
- [x] Determine list of stakeholders we want to get more data from
- [x] Create a general conversation guide for stakeholder interviews
- [x] Upload stakeholder conversation guide to GH
- [x] Schedule stakeholder interviews

## Acceptance Criteria
- [x] Stakeholder conversation guide in GH
- [x] Scheduled stakeholder interviews

**Comment by rileyorr** [comment]
I've added [the conversation for Jodi and Dawn](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/jodi-and-dawn-conversation-guide.md) to GH.
