### ISSUE TITLE
Update Unit Test Coverage report to combine results

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#76537]
## Issue Description
The unit test coverage report was designed to assume one set of results. The problem with splitting the unit tests into parallel jobs now, is that the report will only display on the front end support dashboard for the last parallel job to finish which is only a partial results set. We need to move the coverage report generation to the unit test reporting stage and combine all the results artifacts before generating it, so it's a complete report.

---
## Tasks
- [ ] Combine unit tests results into one results file before generating coverage report
- [ ] Move coverage report generation to unit tests reporting stage of GHA
- [ ] Confirm that a complete coverage report generates regardless of how many processes unit tests is split into.

## Acceptance Criteria
- [ ] A complete coverage report of all apps makes it to S3 and the front end support dashboard for each unit test run
