### ISSUE TITLE
[Design] Call Center Interview Prep

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7654]
## User Story or Problem Statement
As a designer, I need to prepare for call center interviews so I can ask valuable, consistent questions to call center employees in a timely manner.

## Goal
_What outcome(s) do we want to see?_
A solid plan for call center interviews

## Tasks
- [x] Determine list of call center employees we want to get more data from
- [x] Create a general conversation guide for call center interviews
- [x] Upload call center conversation guide to GH
- [x] Schedule call center interviews

## Acceptance Criteria
- [x] Call center conversation guide in GH
- [x] Scheduled call center interviews

**Comment by rileyorr** [comment]
I've added [the conversation guide for the call center representative interviews](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/call-center-representatives-conversation-guide.md) to GH
