### ISSUE TITLE
[DA] 10-10EZ - TERA: Open Analytics ticket to update DOMO with new pages

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76543]
## Benefit to the Veteran
By updating the DOMO dashboard to include the new pages of the form, we can monitor what pages the Veteran is visiting and where they may be exiting the form.  This will inform us on where the Veteran may be experiencing pain-points within the application, and where we would need to focus improvement efforts.

## Background
As part of the TERA effort, we are building new pages for the Toxic Exposure questions.  We need to include these new pages in the DOMO page funnel, so that we can track traffic between them.

## Tasks
- [x] Gather a list of pages/URLs from start to finish within the application
     - Reference [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Analytics/KPI%20Dashboard%20Product%20Details%20Template%20-%2010-10EZ.xlsx) of existing pages
     - Step through the application in Staging to confirm URLs
     - Make any updates needed, outside of new TERA pages (has not been updated since before Household section update)
- [x] Open [Analytics request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&projects=&template=analytics-google-analytics-implementation-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D)
- [x] Link the Analytics request ticket here - **https://github.com/department-of-veterans-affairs/va.gov-team/issues/77078**

## Acceptance Criteria
- The analytics tracking will be updated for the 10-10EZ to include the new TERA pages.

**Comment by luis-simauchi** [comment]
URLs for TERA QUESTIONS:
/health-care/apply/application/military-service/toxic-exposure
/health-care/apply/application/military-service/radiation-cleanup-efforts
/health-care/apply/application/military-service/gulf-war-service
/health-care/apply/application/military-service/gulf-war-service-dates
/health-care/apply/application/military-service/operation-support
/health-care/apply/application/military-service/agent-orange-exposure
/health-care/apply/application/military-service/other-toxic-exposure
/health-care/apply/application/military-service/documents

**Comment by longmd** [comment]
@luis-simauchi , add the following URLs to your list as well... 

- /health-care/apply/application/military-service/other-toxins-or-hazards
- /health-care/apply/application/military-service/other-toxic-exposure-dates

**Comment by luis-simauchi** [comment]
https://docs.google.com/spreadsheets/d/1qbAH5h5Kb468iAAHVhCKtgJM5s4yhEAnG-Dtu6ac9fU/edit#gid=0

**Comment by luis-simauchi** [comment]
analytics issue ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/77078
