### ISSUE TITLE
[Design] Prep hearing aid batteries & accessories content page for usability testing

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7655]
## User Story or Problem Statement
As a Veteran interested in placing an order for hearing aid batteries and accessories, I need a centralized hub with information about ordering hearing aid batteries and accessories so I can determine if I qualify and learn about how to place an order.

## Goal
_An InVision prototype of the hearing and batteries and accessories content page to be used during usability testing_

## Objectives or Key Results this is meant to further
- _MDT usability testing_
---
## Tasks
- [x] _Set up an InVision prototype of the hearing aid batteries and accessories content page_
- [x] _Ensure the buttons link to [MDT’s form introduction page on staging](https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction)_
- [x] _Update [MDT's usability testing conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/conversation-guide.md) to include a link to the InVision prototype_

## Acceptance Criteria
- [x] _A testable InVision prototype of the hearing aid batteries and accessories content page is created_

**Comment by rileyorr** [comment]
The InVision prototype can be found [here](https://vsateams.invisionapp.com/share/4FWT41FGQKR). I've also updated the conversation guide with the link. Although, I'll remove the link if we end up testing with UXPin since this screen can be incorporated into that prototype.
