### ISSUE TITLE
[Accessibility]: Create onboarding presentation for new teammates

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#76567]
## Value Statement
**_As a_** designer
**_I want to_** create an onboarding presentation to supplement the Platform accessibility orientation
**_So that_** new teammates can get introduced to the team's accessibility specialists, ask questions and understand team accessibility processes.

---
## Background

The Platform team gives an [accessibility orientation that's broad and useful](https://docs.google.com/presentation/d/1rJLur5iIB0H47JVoTTUKd39U6TbvP12KbxICXgXNu0w/edit?usp=sharing). It doesn't provide the team's accessibility specialist with a chance to meet new teammates, describe internal team accessibility process, etc. A short, 15 minute presentation could cover those items.

## Acceptance Criteria
- [x] Presentation is finished and linked in the team folder.

## Tasks

- N/A

## How to Measure Success
_- Define the expected result and where to measure it._

- N/A

## Out of scope
- We won't cover anything already covered by the Platform orientation.

## Definition of Ready

- N/A
- 
## Definition of Done
- [x] Presentation is drafted.
- [x] Presentation is reviewed by at least one teammate and one accessibility specialist.
- [x] Onboarding meeting is scheduled with Peri and Derek.

**Comment by davidakennedy** [comment]
I have a [draft of the presentation](https://docs.google.com/presentation/d/1m5vEkLfsLuIUOZGUTUzrlo1r89QUKIZl/edit?usp=sharing&ouid=116153306533497696786&rtpof=true&sd=true). It's been reviewed by two accessibility specialists. Going to share with the team tomorrow.

**Comment by davidakennedy** [comment]
The meeting is scheduled for March 5.
