### ISSUE TITLE
[Accessibility]: Create accessibility cookbook topics and write first recipe

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#76568]
# Ticket Template

## Value Statement
**_As a_** accessibility specialist
**_I want to_** brainstorm topics for the accessibility cookbook and write the first recipe
**_So that_** the accessibility cookbook has a backlog of topics and gets the first one completed

---
## Background

@eli-oat created the [accessibility cookbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md) as a place to record solutions for all sorts of accessibility issues we run into in our day-to-day work. We need to start writing content to help it get off the ground.

## Acceptance Criteria
- [ ] New recipe is complete and uploaded to cookbook directory
- [ ] List of possible topics is uploaded to cookbook directory.

## Tasks

- N/A

## How to Measure Success
_- Define the expected result and where to measure it._

- N/A

## Out of scope

- DK will start with one complete topic and address future ones in different tickets.

## Definition of Ready

- N/A

## Definition of Done
- [x] One topic is completed, and added to the cookbook.
- [x] A backlog of topics os created for the cookbook and added.
- [x] A consistent "recipe" structure is followed. See cookbook.

**Comment by saderagsdale** [comment]
@davidakennedy Is this related to what we discussed for improving the onboarding experience for participants with screenreader needs?

**Comment by davidakennedy** [comment]
@saderagsdale No, this is different. This is for the cookbook work. For the work around the onboarding screen reader users to research, I'll make a different ticket.

**Comment by davidakennedy** [comment]
The [cookbook topics are here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook-ideas.md) and complete for now.

The first [topic on headings is here, in the cookbook\(https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md#headings-and-accessibility-best-practices).
