### ISSUE TITLE
[Design] MDT Usability Testing

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7657]
## User Story or Problem Statement
As a designer, I need to conduct usability tests so I can evaluate our product's first iteration.

## Goal
_What outcome(s) do we want to see?_
A list of findings to improve the product

## Tasks
- [x] Conduct usability sessions (Approximately 10)
- [x] Hold daily debrief sessions to discuss high level findings
- [x] Upload scrubbed usability notes to GH

## Acceptance Criteria
- [ ] Usability notes organized into GH
- [ ] Export of daily debriefing Mural board

**Comment by rebeccawalsh** [comment]
Find our participant notes in our study directory here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/medical-device-tool/research/usability-march20
