### ISSUE TITLE
Migrate endpoint to Facilities v1

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7658]
## Goal
complete Facility Locator transition to Lighthouse API 

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 

---

## Tasks
- [ ] Migrate Facility  locator front end to v1 Facilities VA API
- [ ] Create feature flag to control rollout

## Acceptance Criteria
- [ ] Data is maintained compared to vets API
- [ ] Release can be staged to percentage of users

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
