### ISSUE TITLE
Draft Updated DOMO Dashboard

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#76582]
## Issue Description
As a DOMO user, I need a dashboard that reflects the current status of all incoming cases so I can see trends over time. Cases should be categorized by date opened, date closed, current status, routed, routed to EVSS, backlogged, etc.  
---
## Tasks
- [x] Identify case categories for tracking for Tier II, Tier III, Tier III EVSS, and AskVA
- [x] Dashboard shall display the total number of daily incoming cases
- [x] Dashboard shall display the number of cases by date frequency
- [x] Dashboard shall display the number of currently open cases
- [x] Dashboard shall display the number of currently closed cases
- [x] Dashboard shall display the number of open backlog cases
- [x] Dashboard shall display the number of closed backlog cases
- [x] Dashboard shall display the number of routed cases
- [x] Dashboard shall display the number of cases routed to T3 EVSS
- [x] Dashboard shall display the number of cases routed to T3
- [x] Dashboard shall display the number of cases routed to T2 cases
- [x] Dashboard shall display Total AskVA cases
- [x] Dashboard shall display total AskVA daily incoming cases
- [x] Dashboard shall display the number of cases by date frequency

## Acceptance Criteria

 - [ ] **Scenario: Publish Updated DOMO Dashboard**
   - Given the DOMO dashboard is updated with the latest case data
   - When the dashboard is viewed by the user
   - Then the dashboard should display the total number of daily incoming cases
   - And the dashboard should display the number of cases by date frequency
   - And the dashboard should display the number of currently open cases
   - And the dashboard should display the number of currently closed cases
   - And the dashboard should display the number of open backlog cases
   - And the dashboard should display the number of closed backlog cases
   - And the dashboard should display the number of routed cases
   - And the dashboard should display the number of cases routed to T3 EVSS
   - And the dashboard should display the number of cases routed to T3
   - And the dashboard should display the number of cases routed to T2 cases
   - And the dashboard should display Total AskVA cases
   - And the dashboard should display total AskVA daily incoming cases
   - And the dashboard should display the number of cases by date frequency

**Comment by ATMiddleton** [comment]
Reviewed updated DOMO draft dashboard 2/29/24.

No additional changes after 3/4/24

Need to schedule final review.

**Comment by ATMiddleton** [comment]
Review scheduled for Thursday, 3/7/24

**Comment by ATMiddleton** [comment]
Conducted final review of the aesthetics of the dashboard and @newworld2616 will conduct a demo next week.
