### ISSUE TITLE
[Product] My VA: Submit 508 office audit request

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#76588]
## Background
We need to submit My VA for a 508 office audit.

## Tasks
- [x] Review prerequisites for submission
- [x] PM to submit audit request
- [x] Once ticket is submitted send a follow-up message to Martha Wilkes in the a11y help channel in slack
- [x] Perform any necessary follow-up tasks

## Acceptance Criteria
- [x] 508 audit request is submitted

---

## Resources
- [Platform guidance](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest)
