### ISSUE TITLE
[FE] Nametag banner: Fix aria issue flagged on nametag

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#76585]
## Background
Laura Flannery (a11y specialist on sitewide team) flagged an issue with the nametag banner for us:

> Currently the blue "My Information" section has been assigned an aria landmark role of "banner". However, this landmark should really be [reserved for the global header section](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role). There should also only be one banner landmark - which is what is currently being flagged when axe devTools is run on the page. It does make sense that you would want to call this section out to the user though so I might recommend using role="region" instead as this is [intended as a generic role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/region_role)

![Screenshot 2024-02-19 at 2 24 17 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/482a8310-299c-4027-b747-1290eebc5976)

[Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1708370768400369)

## Tasks
- [ ] Review feedback from Laura
- [ ] Update nametag component role attribute  
- [ ] Test (if possible ask Laura to check again)

## Acceptance Criteria
- [ ] The component is updated

**Comment by allisonlu** [comment]
@ajakabcin @laflannery ready for validation! 

a note for Laura: i decided to remove the role attribute altogether because the `<section>` element already has an implicit role of region 

to validate:
1. log on as any user with a Nametag (should be any LOA3 user on staging)
2. press **Cmd+Shift+C** and click on the Nametag component 

![Screenshot 2024-03-12 at 2 09 38 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/af923078-4f13-45dc-b353-f34aab957480)

3. confirm the `<section>` element doesn't have a `role` attribute

![Screenshot 2024-03-12 at 2 09 55 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/3590529e-4336-462c-9255-2e6ae953a19c)

**Comment by laflannery** [comment]
@allisonlu Thanks for tagging me, this looks good!

- axe error is gone:
![Screenshot 2024-03-12 at 2 54 05 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106678594/a2c9c304-83a3-4298-b928-1928d88e8377)
- Nametag shows in the list of landmarks:
![Screenshot 2024-03-12 at 2 55 30 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106678594/5827f905-5a04-4c0b-b5b6-c6c585ffd43c)
