### ISSUE TITLE
[CST] Update CODEOWNERS for EVSS claims services

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#76597]
### Background
The EVSS claims services are both assigned to the Authenticated Experience team. They should be assigned to Benefits Management Tools instead

### Engineering Notes
**NOTE:** We can remove the Authenticated Experience team from the files below as they aren't really CODEOWNERS.
Files that need to be reassigned to `department-of-veterans-affairs/benefits-management-tools-be`:
- `app/services/evss_claim_service_async.rb`
- `app/services/evss_claim_service.rb`
- `spec/services/evss_claim_service_async_spec.rb`
- `spec/services/evss_claim_service_spec.rb`

### Tasks
- [x] Confirm with the `vfs-authenticated-experience-backend` team that they would like to be removed as CODEOWNERS from the files listed above
- [x] Reassign the EVSS claim service files to `department-of-veterans-affairs/benefits-management-tools-be`

### Acceptance Criteria
- [ ] Benefits Management Tools is assigned as a CODEOWNER on EVSS Claim service source files
