### ISSUE TITLE
[Rated Disabilities] Update discrepancy checks to only allow certain decision statuses

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#76603]
### Background
We know that the Lighthouse rated disabilities endpoint can return a number of different `decision` values. EVSS only seems to return a subset of these, so we should create an allowlist and filter out any ratings that don't have `decision` values within that list

### Engineering Notes
- Controller to update:
  * `app/controllers/v0/rated_disabilites_discrepancies_controller.rb`
- [Lighthouse Docs](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility/docs?version=current)
- These are all of the possible decision values (not documented currently):
  * 1151 Denied
  * 1151 Granted
  * Service Connected
  * Pension
  * Deferred
  * Not Service Connected
  * Willful Misconduct
  * Voc Rehab Purposes
  * Chapter 17
  * 38 USC 109(c)
  * PEB Referred Proposed DES Not Service Connected
  * PEB Referred Proposed DES Service Connected
  * Proposed DES Service Connected
  * Proposed DES Not Service Connected
  * Active Psychosis/GW Mental
  * BIRTH - DENY
  * SPINA - DENY

- `decision` values that we should include in the allow list:
  * 1151 Granted
  * Not Service Connected
  * Service Connected

### Tasks
- [ ] Create an allow list for the decision values we want to allow for ratings
- [ ] Filter ratings to only include ones whose `decision` value is in the allow list

### Acceptance Criteria
- [ ] We are only checking for discrepancies with EVSS against ratings that have been filtered to only include allowed `decision` values
