### ISSUE TITLE
[Design] Usability testing prep 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7660]
## User Story or Problem Statement
Problem description. How might we prepare for usability testing?

## Goal
_Prepare a space to house notes/key takeaways and schedule debrief sessions after usability testing session days_

## Objectives or Key Results this is meant to further
- _MDT usability testing_
---
## Tasks
- [x] _Set up a Mural board to house notes/key takeaways from testing sessions_
- [x] _Schedule debrief sessions for every day there's a usability testing session_

## Acceptance Criteria
- [x] _Link to a Mural board_
- [x] _Debrief sessions are scheduled_

**Comment by rileyorr** [comment]
I've created a [Mural board](https://app.mural.co/invitation/mural/vsa8243/1586447001014?sender=riley5075&key=08b639cc-0221-4f26-8d68-42c0c4ee41ea) that includes an area for each session's notes and a section for key observations for each participant. I've also scheduled all the debrief sessions.
