### ISSUE TITLE
Adjust Appoint MVP designs based on unauth user test

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76613]
## Background
Anticipating the unauth user test will have findings that will require design updates.

## Tasks
- [ ] Review recommendations from research
- [ ] Update Appoint designs based on recommendations
- [ ] Review updates with the team
- [ ] Incorporate any feedback from the team into designs

## Acceptance Criteria
- [ ] Appoint designs have incorporated all user and team feedback and is ready for development.

**Comment by oddball-lindsay** [comment]
Start with some low hanging fruit that we can begin designing solutions for.  Can huddle with the team next sprint when dev is out of the pre-launch mindset.

**Comment by mtri** [comment]
Design exploration for the Intro page:

**Option 1: Introduction page pattern for prepare process list + show options for filling out the form**\
[Unauth](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2499%3A183957&type=design&node-id=2499-184766&viewport=354%2C583%2C0.25&t=8OmabPUIf1QDIJAm-1&scaling=min-zoom&mode=design)\
[Auth](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2499%3A183957&type=design&node-id=2630-200067&viewport=274%2C548%2C0.25&t=mvVOc4rDQpSTsPY5-1&scaling=min-zoom&mode=design)

**Option 2: Introduction page pattern for prepare process list + show options for filling out the form + alert about digital submission**\
[Unauth](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2499%3A183957&type=design&node-id=2589-199793&viewport=274%2C548%2C0.25&t=mvVOc4rDQpSTsPY5-1&scaling=min-zoom&mode=design)\
[Auth](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2499%3A183957&type=design&node-id=2561-193736&viewport=274%2C548%2C0.25&t=mvVOc4rDQpSTsPY5-1&scaling=min-zoom&mode=design)

[Slack Discussion](https://dsva.slack.com/archives/C05L6HSJLHM/p1709590571127259)

**Comment by mtri** [comment]
Design exploration for the Review –> Confirmation page flow:
> Consider moving the final page into actual steps of the experience

-   [Option 1 -- Include download, print, and sign your form as its own step before the final ask step. Show stepper](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2561%3A190215&type=design&node-id=2561-194635&viewport=246%2C537%2C0.25&t=F2pzAZKYXLR3OQQT-1&scaling=min-zoom&starting-point-node-id=2561%3A194635&show-proto-sidebar=1&mode=design).
-   [Option 2 -- Include download, print, and sign + ask your rep to submit as own steps. Show stepper](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2561%3A190215&type=design&node-id=2561-196239&viewport=246%2C537%2C0.25&t=F2pzAZKYXLR3OQQT-1&scaling=min-zoom&starting-point-node-id=2561%3A196239&show-proto-sidebar=1&mode=design).
-   [Option 3 -- Include progress stepper on confirmation page demonstrating it is another step in the process](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2561%3A190215&type=design&node-id=2561-197804&viewport=-1726%2C725%2C0.5&t=iRJSxEjZ7fOaYiUV-1&scaling=min-zoom&starting-point-node-id=2561%3A197802&show-proto-sidebar=1&mode=design).

[Slack Discussion](https://dsva.slack.com/archives/C05L6HSJLHM/p1709592563500599)

**Comment by mtri** [comment]
More intro page exploration:

[Slack Convo](https://dsva.slack.com/archives/C05L6HSJLHM/p1709928737353649?thread_ts=1709590571.127259&cid=C05L6HSJLHM)

[Option 3: Branching on intro page](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2499%3A183957&type=design&node-id=2888-98055&viewport=52%2C542%2C0.25&t=rvZte2NxrSFIsFGx-1&scaling=min-zoom&starting-point-node-id=2888%3A98055&mode=design)

[Option 4: Branching on landing page](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2499%3A183957&type=design&node-id=2885-83230&viewport=52%2C542%2C0.25&t=rvZte2NxrSFIsFGx-1&scaling=min-zoom&starting-point-node-id=2888%3A98055&mode=design)

[Option 5: Multiple process lists for different options on landing page](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=2499%3A183957&type=design&node-id=2854-182287&viewport=-2378%2C949%2C0.5&t=HrAFD3HGbOVrspPu-1&scaling=min-zoom&starting-point-node-id=2888%3A98055&mode=design)

**Comment by mtri** [comment]
Designs have been shared with A from CAIA.

All designs created for this task have been added to the [Design Links canvas](https://dsva.slack.com/docs/T03FECE8V/F06EBTZJH40) under the [Current Design Explorations](https://dsva.slack.com/docs/T03FECE8V/F06EBTZJH40?focus_section_id=temp:C:GDe41a0b363433c4fc0a6dfccd1a) heading
