### ISSUE TITLE
User support for search parameters

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7661]
## User Story or Problem Statement
As a Veteran, I need to know how to specify my location when searching in Facility Locator so I can successfully find the locations relevant to me.

The following suggestion was sent by the Office of Community Care: 

> if Veterans should only search for City, State or ZIP on the VA.gov Provider Locator, perhaps we institute a similar error message that OPTUM is using on their locator?

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/50cb1283-2d60-41c7-88a5-84ee44b995c3) 
---

## Goal
Veterans understand what search parameters should be entered for location

## Objectives or Key Results this is meant to further
-Objective 3: Deliver a usable and accessible experience

## Tasks
- [ ] Consider adding user support for search parameters

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@arickalewis1 fyi only
