### ISSUE TITLE
[FE] 10-10EZR: Autofill Alerts

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#76615]
## Issue Description
- Research has shown that Veterans do not want repetitive information and the Autofiller is shown on many screens/pages of the EZR.
- The ideal flow is to show the Autofiller Alert only at the beginning of each section and removed from every other page. 

---
## Tasks
- [x] Confirms the Autofill Alert exists on the following pages:
     - [x] Veteran Information: Mailing Page
     - [x] Household Information: Martial Status
     - [x] Insurance Information: Medicaid Eligibility
- [x] Remove Autofill early from all other EZR pages.

![Alert](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117132709/c7a56648-d6c9-46f7-8dc7-f6e172a6a28e)

## Acceptance Criteria
- [ ] Autofill Alert in Staging matches Figma mockups.

**Comment by mkerns1** [comment]
This PR has been merged and deployed to production.
