### ISSUE TITLE
[UX] 10-10EZR: Content Mismatch

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#76621]
## Issue Description
- The recent EZR Staging/Figma audit (#75154 ) found several pages on Staging and Figma did not match.
- UX to update the following to match Staging.

[Audit Spreadsheet](https://docs.google.com/spreadsheets/d/1rcyf0fKQfLzijeJb_00sserSBAhqaCS37tkQol7nZ04/edit?usp=sharing). 

---
## Tasks
- [x] Text mismatch; update "Finish this application later" to "Finish this form later"
- [x] Test mismatch; update the year "2022" to "2023"
- [x] AddInfo with Radio Button; rearrange AddInfo component and radio button to match Staging (in v3, AddInfo cannot be embedded between Question and Radio Button/checkboxes.

## Acceptance Criteria
- [x] Content in Figma matches Staging.
