### ISSUE TITLE
[FE] 10-10EZR: Content Mismatch

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#76620]
## Issue Description
- Staging content does not match Figma mockups.

---
## Tasks
- [x] Update Staging to match Figma mockups
    - [x] Veteran Info, Personal Info page; missing "Finish this form later" component.
    - [x] Veteran Info, Personal Info page; missing Autosave alert component.   
    - [x] Spouse Additional Info Page; missing "Required" label for the "Did you live with your spouse..." question.
    - [x] Spouse Additional Financial Support; missing "Required" label for the "Did you provide financial support" question.
    - [x] Spouse Additional Financial Support; missing '_addition info_' component and its content.

## Acceptance Criteria
- [ ] Content in Staging matches Figma mockups.

**Comment by IMHieuVo** [comment]
@dellerbie 
Section:
[Veteran Info Section](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0%3A2042&mode=design&t=6yV61R2KnLeSaTzO-1)
[Household Financial Information](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0%3A2265&mode=design&t=6yV61R2KnLeSaTzO-1)

Specific Pages:
[Personal Info page](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=542%3A7330&mode=design&t=6yV61R2KnLeSaTzO-1)
[Spouse Additional Info](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=533%3A26842&mode=design&t=6yV61R2KnLeSaTzO-1)
[Spouse Additional Financial Support](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=588%3A69306&mode=design&t=6yV61R2KnLeSaTzO-1)

**Comment by allanto-ah** [comment]
Moving back to In Progress. 

Two issues found:
1. The Finish this form later link and save in progress boxes are missing on the Veteran Info page.
<img width="1346" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8bd0373c12aed7d8907f7a70509c6a1ea7286eaa/Screenshot%202024-04-23%20at%201.31.39%E2%80%AFPM.png" alt="Screenshot 2024-04-23 at 1.31.39 PM.png" />

2. On the Household Financial Info page, there is an empty space where content is supposed to be there. 
<img width="1336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0tKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86c43ce8f8c700999cfc44ca74a8e9987aeb5d17/Screenshot%202024-04-23%20at%201.32.50%E2%80%AFPM.png" alt="Screenshot 2024-04-23 at 1.32.50 PM.png" />

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the changes have been made to match the Figma designs
