### ISSUE TITLE
Design Intent - IA Feedback - Benefits Non-Disability, CH 36/PCPG, Critical Form Updates

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#76631]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this project through the Collaboration Cycle!
- The flow is looking good. I appreciate the level of detail (and that y'all are dispensing with the wizard).

## Feedback
_Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes)._

- [x] **Must: if LOA3 authentication is required, provide meaningful errors for LOA1 users** This is something we've started to check on recently with teams who are creating authenticated experiences. Are users required to have LOA3 level access for this form (guessing no, but want to make sure). If so, please ensure that if folks log on and only have LOA1 account access there is a meaningful error message for those folks to know what to do to proceed. My VA does this currently and is a good example.

![Screenshot of verification requirement for My VA](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/3261908c-6fd5-45a4-978f-f60bdf6bc37e)

- [x] **Should: verify whether "remarks" field is needed** - There's a "remarks" field on the paper form, but it looks like it's just for overflow information from other questions. I haven't seen this before so wanted to make sure it didn't need to be on the digital form as well.    

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by sortizsh** [comment]
@Midge-dev will talk to the identity team and learn more

**Comment by fiorella-io** [comment]
Updates:
- Remarks will not be needed
- LO3 is not required for this form
