### ISSUE TITLE
Copy of Code Yellow Support: PACT Act: Create a list of endpoints

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#76657]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] Observe error trends before compared to during the surge
- [ ] Get list of endpoints from Aparna or Jeff at VA

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by jennb33** [comment]
Next steps: find the breakers dashboard and link to it in the BE Support documentation

**Comment by rmtolmach** [comment]
> Next steps: find the breakers dashboard and link to it in the BE Support documentation

Technically done, but I want to add more to the docs: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Breakers-dashboards

**Comment by rmtolmach** [comment]
Updated the doc. Done.
