### ISSUE TITLE
[CST] Make evidence submission a synchronous task

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#76660]
## Value Statement
**_As a_** user uploading a file via CST
**_I want to_** understand that my file has been received by the VA and attached to the claim, even if the file doesn't immediately show up in CST
**_So that_** I can rest assured knowing my file has been added to the claim and I can go about my business without feeling the need to re-upload the file multiple times

---
## Background Context
Right now @jerekshoe is seeing some users uploading the same file multiple times, and theorizes it might have to do with the language in this banner. The "Note: It may take a few minutes for your file to show here" line is buried, which might be why users miss it and think they need to upload the file again.

[More context in this Slack thread
](https://dsva.slack.com/archives/C056854SVT8/p1706288144959889?thread_ts=1706284907.017799&cid=C056854SVT8)

![Screenshot 2024-01-26 at 10 21 51 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/0064ade5-4b8f-4e13-ade7-a837e3699690)

## Acceptance Criteria

- [x] Create feature flag for synchronous task
- [x] Make this file upload a "synchronous task" to surface errors to end users more easily
- [ ] Test error states in staging to identify UI states

## Engineering Notes
- Add here

## Out of scope
- Add here

## Open questions
- How do we respond to maintenance windows or lack thereof? 
- Argument for using asynchronous jobs is that temporary issues don't prevent submissions necessarily and the user also has a more seamless experience; however, in the case when the job ultimately fails, there is a silent failure. How do we alleviate this tension? 
- Are there cases in which CST remains up but a downstream service is down for maintenance which allows users to still upload files? 
- Should we use 5103 as a test for the synchronous task approach? 
- What are the distribution of errors currently? Knowing this can help us understand better the potential value of using synchronous tasks. We can do this once LH makes their benefits updates. 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by jacobworrell** [comment]
we're going to resurface this for consideration after LH makes the benefits changes in their pipeline.

**Comment by pmclaren19** [comment]
@jacobworrell @jerekshoe please discuss this ticket with the enablement team and evaluate if we need to work this or not.

**Comment by pmclaren19** [comment]
There's two options that we can resolve this...

1. Update the success message so that the 'NOTE' section is in a separate paragraph and bolded (unless design has other ideas around making this more visible to users)
2. Make this a synchronous task. We will change the code so that we don't use sidekiq to make the API calls and when we get the returned data from the API if there is a success then we show the success message and if there is a failure then we show an error message.

@jacobworrell @skylerschain theres no clear clarification in this ticket as to which option you and design were hoping we'd do...or maybe you want us to do both? Please let us know!

**Comment by skylerschain** [comment]
#2 seems preferable to me
