### ISSUE TITLE
Update required fields for 21-22/21-22a

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76666]
## Background
Lighthouse has confirmed which fields on the 21-22/21-22a will be required to validate a POA request and establish POA through digital submission.

We originally had other ideas of what fields were required, so some updating needs to happen in the Appoint designs to match.

## Tasks
- [x] Require "Date of Birth" for Veteran/Claimant
- [x] No longer require "Phone number" for Veteran/Claimant
- [ ] Consider how to alert if no info is entered (modal?)

## Acceptance Criteria
- [x] The Appoint experience will require the minimum amount of form fields necessary to complete a request for POA.
- [ ] The Appoint experience still encourages user input of contact info

**Comment by mtri** [comment]
Changes made, left open in case anything needs to adjust based on our convo [here](https://dsva.slack.com/archives/C05L6HSJLHM/p1708470282764319)

**Comment by oddball-lindsay** [comment]
Keeping this in progress as we're discussing if we want to require phone, email, neither, both, etc. : https://dsva.slack.com/archives/C05L6HSJLHM/p1708470282764319

**Comment by oddball-lindsay** [comment]
Right now, we are not requiring either phone or email.  Consider ux where there is some type of confirmation/explicit action if the user does not want to put these in.  We are seeing that Veterans aren't reading, so content alone may not be the ideal solution; possibly a modal alert.

Will ideate on some early ideas, we can discuss these with A along with other content-related recommendations from research.

**Comment by oddball-lindsay** [comment]
Settling on: [Leave phone number required, but allow a checkbox that says I do not have a number as an option.](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2410%3A473666&mode=design&t=a9MkTsIElZ8ZqqZo-1) 

Since it feels like an extreme corner case that a person would have no contact information to enter, this feels okay, especially for MVP.

Will keep an eye on this behavior once Appoint launches so we know how often folks are not providing phone/email and decide if a further nudge ([by way of modal](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2410-473666&mode=design&t=UeA3M66rBqgNL7ci-11)) is needed to confirm the user would like to proceed without providing this information.

Slack discussion: https://dsva.slack.com/archives/C05L6HSJLHM/p1708470282764319
