### ISSUE TITLE
Global | Render saved page content

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#76675]
## Value Statement
**_As a_** Veteran saving a page from VA.gov
**_I want to_** be able to reopen it and view the content at a later date
**_So that_** review the saved page

## Background context

When a web page is saved from VA.gov (Command <kbd>⌘</kbd> + <kbd>S</kbd> or Control <kbd>Ctrl</kbd> + <kbd>S</kbd>), the page saves an HTML and folder with associated files. When you open the HTML page, it renders the VA.gov header & footer, but no content. Not showing any content makes the saved page not work as expected.

## Tasks
- [ ] Determine why the content isn't rendering
- [ ] Fix code to allow viewing saved page content
- [ ] Add tests

## Definition of Ready 
- [ ] The feature satisfies all functional requirements
- [ ] The feature code is integrated into the lower environment
- [ ] Unit tests and component tests for the feature have been executed and passed
- [ ] Production test environment is configured to simulate the production environment as closely as possible
- [ ] Test data for the E2E tests have been prepared to cover various scenarios
- [ ] External systems that the feature relies on are configured in the production environment
- [ ] Test users for each test case are ready
- [ ] Test plan approved by involved teams and stakeholders
- [ ] Test documentation is ready for use

## Definition of Done
- [ ] E2E test scripts are executed to verify the end-to-end functionality of the feature
- [ ] The E2E tests meet the predefined passing criteria
- [ ] Integration points with other systems or components are validated
- [ ] Defects identified during E2E testing are addressed
- [ ] E2E testing documentation, including test cases and results, is updated
- [ ] Any test artifacts and data are cleaned up from the production test environment
- [ ] Logs are ready, including #75546 
- [ ] Test team signs off on the test phase
- [ ] OCTO signs off on the test phase

**Comment by saderagsdale** [comment]
Low priority. Can wait until a later sprint.

**Comment by HeatherWidmont** [comment]
@Mottie will merge it in after prod deploy today & additional design review

**Comment by HeatherWidmont** [comment]
@Mottie "We'll merge this tomorrow after production deploy - production deploy won't get released at the normal time today."

**Comment by HeatherWidmont** [comment]
@Mottie will merge in after production deploy today & then validate
