### ISSUE TITLE
NOD | Clean up logging and monitoring post v2 launch

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#76676]
## Issue Description

Follow up to #75546 — This ticket covers cleaning up the dashboards (i.e. removing widgets, removing version data from the logs, etc.)

---
## Tasks
- [ ] Remove version specific monitors from DataDog dashboards
- [ ] Remove StatsD counter `nod_evidence_upload.<version#>.queued` from [AppealSubmission in vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/appeal_submission.rb#L44)

## Acceptance Criteria
- [ ] We no longer observe increments for the removed StatsD counter in DataDog
- [ ] Version specific monitoring is no longer visible in DataDog dashboards
- [ ] All other monitors are unaffected by changes

## Definition of Ready
- [ ] NOD Version 2 is fully launched (at 100%)

## Definition of Done
- [ ] Acceptance criteria met.

**Comment by anniebtran** [comment]
Logs in prod no longer have `version_number` in their payload — [example](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%40payload.form_id%3A10182%20&agg_m=count&agg_m_source=base&agg_t=count&cols=%40payload.user_uuid%2C%40http.status_code&event=AgAAAZJJqvhRtMUwMgAAAAAAAAAYAAAAAEFaSkpxd3ZSQUFCQWJ1U29vU2wxMXdBXwAAACQAAAAAMDE5MjQ5YWItMGRkYi00ZDMyLWI5MjktMTQ3ZWM0MWVkMGU0&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1726517733712&to_ts=1727813733712&live=true). Closing 🎉
