### ISSUE TITLE
[CDP & FSR] - List Data Points and Structure

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76679]
## Description

For CDP and FSR list all the related data points and objects associated with the submission and retrieval of necessary data for each application. This may include a sample object structure for each application.

## Tasks
- [ ] CDP data points and object listed
- [ ] FSR data points and object listed

## Acceptance criteria

- [ ] CDP data points and object listed
- [ ] FSR data points and object listed

**Comment by amponce** [comment]
FSR data structure documentation created: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/fsr-data-structure.md

CDP data structure documentation created: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/cdp-data-structure.md


Next steps
**Create discovery ticket** to determine the exact data being used in the combined debt portal, this might involve a more extensive audit and connecting with someone from the backend team.
