### ISSUE TITLE
[FSR] Plug in Endpoints from BackEnd and Replace FE Logic

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76688]
## Description

FE will replace their calculations with requests to BE endpoints to get the calculated data for use within FSR.

## Tasks
- [ ] Replace FSR calculations with BE endpoint request

## Acceptance criteria

- [ ] FE logic replaced

## Testing
- [ ] Confirmed that values are same prior to replacement as well as after
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

**Comment by OptionSelect** [comment]
Per convo with Andrew closing this one out. Covers basically the same as the individual tickets of implementing the endpoints which I have done.
