### ISSUE TITLE
[FSR] Define Desired Data Structure

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76680]
## Description

BE team confirms desired object structure for submission, as well as what is necessary to supply to each endpoint that FE team will be requesting to successfully navigate FSR.

## Tasks
- [ ] Submission object structure defined
- [ ] GET Endpoint structures defined

## Acceptance criteria

- [ ] Submission object structure defined
- [ ] GET Endpoint structures defined

**Comment by kjsuarez** [comment]
Dup of #76055
