### ISSUE TITLE
[FSR] - Use Assets New data BE data/calcs

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76692]
## Description

FSR implement new BE endpoint for Assets Calculation.

/v0/calculate_total_assets is the new endpoint.

## Tasks
- [x] Implement new request to endpoint and replace logic with received data.

## Acceptance criteria

- [x] GET request implemented, resulting data used in place of calculations

## Testing

- [x] Data is identical pre and post request update confirmed

**Comment by OptionSelect** [comment]
Just getting started implementing this!

**Comment by OptionSelect** [comment]
Still working on this! Got a good bit of it laid down.

**Comment by OptionSelect** [comment]
Per convos with Aaron and Andrew, work is unnecessary. Removed and killed PR.

"It's only used on those pages if streamlinedWaiverAssetUpdate is false, and we've had it defaulted to true for a while now. Plus the liquid asset calculation we replaced was only looking at cash in hand & cash in bank, and the API calculates total assets"
