### ISSUE TITLE
2024 Q1 PACT Act Support: Bulkhead Endpoints for Pact Act Submissions

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#76695]
## Objective
This initiative is critical for maintaining service quality and availability during the high-demand period of Pact Act submissions.

To enhance the resilience and reliability of our service during the upcoming round of Pact Act submissions, it is crucial to implement bulkheading for the involved endpoints. This initiative will involve isolating these endpoints into separate pods to ensure that any spikes in traffic or issues affecting one endpoint do not compromise the overall system's stability and performance.

## Tasks
- [x] Increase the `minReplicas` for the existing bulkheads: `vets-api-forms`, `vets-api-hca`, `vets-api-intent-to-file`
- [x] Test to ensure the isolated endpoints function as expected and that traffic is hitting all of the pods. 
- [x] gather dashboards for monitoring the bulkheads and add any alerts if necessary

## Acceptance Criteria

- [x] All critical endpoints involved in the Pact Act submissions are successfully isolated into separate pods.
- [x] The system demonstrates improved resilience and stability, with the ability to handle high traffic volumes without significant degradation in performance.
- [x] Comprehensive testing confirms that the bulkheaded endpoints meet all functional requirements and integrate seamlessly with the rest of the system.
- [x] Monitoring and alerting are in place, capable of promptly identifying any issues that arise within the isolated pods.
- [x] [Documentation](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends) is updated to accurately represent the new system architecture and operational practices.

**Comment by rmtolmach** [comment]
From conversation [in this thread](https://dsva.slack.com/archives/CMJ2V70UV/p1708617703570849), we learned that all the endpoints are the same for 1010ez submissions, so no additional bulkheads will need to be added. 

What we do need to do is increase the `minReplicas` for certain bulkheads. In [this commit](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/1c93675eb710ceac23b065376ea176ecc0269bac) we scaled them down after the PACT act surge. We'll need to scale them back up.

I'll update the tasks to reflect this new item.

**Comment by rmtolmach** [comment]
Draft PR for when we're ready to merge: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2717

**Comment by rmtolmach** [comment]
✅ merged the PR ^^ to increase minReplicas for impacted bulkheads.

**Comment by rmtolmach** [comment]
Testing: 
[This Datadog metric](https://vagov.ddog-gov.com/logs?query=pod_name%3Avets-api-intent-to-file-%2A%20OR%20pod_name%3Avets-api-hca-%2A%20OR%20pod_name%3Avets-api-forms-%2A%20&cols=host%2Cservice&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1687894962395&to_ts=1687895862395&live=true) filters logs based on the pod names matching the bulkheaded pods for PACT. Before the PR above was deployed, I could see from the **Host** facet that there were two pods for each bulkhead. 

After the deploy:
✅ Three pods for each bulkhead

**Comment by rmtolmach** [comment]
✅ Datadog dashboard: [PACT Act bulkheads (HCA, ITF, Forms)](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/intent-to-file-pact-act?fromUser=true&refresh_mode=sliding&view=spans&from_ts=1709245823927&to_ts=1709332223927&live=true)

On Monday I will create monitors for puma backlog, latency and errors from this dashboard. Datadog has a handy feature to jump start the creation of those monitors 🎉

**Comment by rmtolmach** [comment]
High error rate monitor: https://vagov.ddog-gov.com/monitors/203138?view=spans

High Puma backlog monitor: https://vagov.ddog-gov.com/monitors/203139?view=spans&live=2h

I've set them both up to email me, Rachal and Lindsey when they trigger.

**Comment by jennb33** [comment]
Can @rmtolmach repurpose [this](https://vagov.ddog-gov.com/dashboard/gfw-rwf-w5r/pact-act---second-cohort-9302023?fromUser=true&refresh_mode=sliding&view=spans&from_ts=1709394695769&to_ts=1709567495769&live=true) for this next round? @LindseySaari to take a look at this, or Rebecca to compare for "Intent to file"

**Comment by jennb33** [comment]
Need to add a Slack alert in addition to the monitors. Monitors may not be needed, but they will be helpful to have.

**Comment by LindseySaari** [comment]
@rmtolmach Those monitors look good. Only thing is that we may want to also send them to slack as discussed per standup

**Comment by rmtolmach** [comment]
Thanks for checking, Lindsey! I've updated the monitors to sent to the be-notifications channel as well. 

✅ Documentation updated https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends

Closing.
