### ISSUE TITLE
[FSR] - Use Income New data BE data/calcs

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76693]
## Description

FE implement the new BE endpoint for Income calculations and replace the front end calculations with the received data structure.

/v0/calculate_monthly_income is the endpoint for this request.

## Tasks
- [x] FE replace calculations with BE request

## Acceptance criteria

- [x] FE calculations replaced with BE request
- [x] Data is identical pre and post replacement

## Testing
- [x] Confirmed calculations to operate correctly

**Comment by OptionSelect** [comment]
Just began work on this one.
