### ISSUE TITLE
[FSR] - FE Rework Data Structure for BE Endpoints

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76691]
## Description

This ticket is in case we want to adjust our data structure as a FE team to better make use of the new BE endpoints.

## Tasks
- [x] FE team gets heads together to confirm new data structure
- [ ] If new structure decided upon, implement new structure

## Acceptance criteria

- [ ] FE team determined new structure if necessary and implemented

**Comment by Dr-Pongo** [comment]
Using this effort as a discovery ticket for a new structure and investigating default forms system implementation to eliminate some of the heavily customized pages for more rapid and sustainable development in line with platform standard practices. Taking some notes in a [working document  in the FE dev files](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/other/andrews-perfect-world.md).

**Comment by Dr-Pongo** [comment]
Created a BE discovery ticket (**[FSR] Prefill data investigation** [#84210](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/84210)) to see if we can clean up the prefill a bit! 

Discussed overall structure and ideas with FE team. Holding onto notes so we can hopefully make improvements in the future!
