### ISSUE TITLE
[FSR] - Use Expenses New data BE data/calcs

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76694]
## Description

FE implement the new BE endpoint for expenses calculations and replace the front end calculations with the received data structure.

Necessary endpoints for requests

/v0/calculate_monthly_expenses
/v0/calculate_all_expenses 

## Tasks
- [x] FE replace calculations with BE request

## Acceptance criteria

- [x] FE calculations replaced with BE request
- [x] Data is identical pre and post replacement

## Testing
- [x] Confirmed calculations to operate correctly

**Comment by OptionSelect** [comment]
Currently using the new endpoints locally. Form still submits and API returns same values as current transform calculations. Working on replacing variables now before PR.

<img width="1861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDg4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b96138667b87b1d62a398477aad8199543e2bd4/image.png" alt="image.png" />

**Comment by OptionSelect** [comment]
This may roll due to still fighting with updating the tests. This might end up requiring some back end intervention to update the value we receive so that cypress will allow us to mock the response and get it to pass.

**Comment by OptionSelect** [comment]
Also blocked by Backend needing to PR: [this branch](https://github.com/department-of-veterans-affairs/vets-api/compare/master...78475-adjust-fsr-calculators) because it is the calculations that will support the new behavior!

**Comment by OptionSelect** [comment]
PR is approved and ready to be merged, now working to coordinate with Kevin because this branch should be merged _after_ [this one](https://github.com/department-of-veterans-affairs/vets-api/compare/master...78475-adjust-fsr-calculators) so the behavior is supported

**Comment by OptionSelect** [comment]
Had to revert due to submission issues with timing from API response and updating the state in redux.

https://github.com/department-of-veterans-affairs/vets-website/pull/29232
