### ISSUE TITLE
[FSR] - Testing new endpoints and page generation

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76696]
## Description

FE & BE team will confirm on their sides that everything is working as expected.

## Tasks
- [ ] FE team to test individually and confirm with BE
- [ ] BE team to test individually and confirm with FE

## Acceptance criteria

- [ ] Both teams agree that everything is working as expected

**Comment by Dr-Pongo** [comment]
Endpoints for testing!
`/v0/calculate_monthly_expenses`
`/v0/calculate_all_expenses`
`/v0/calculate_monthly_income`
`/v0/calculate_total_assets`

**Comment by HeatherRienks** [comment]
@Dr-Pongo and @asmithgovcio - please share any updates here. Thanks!

cc: @Tom-Davis

**Comment by Dr-Pongo** [comment]
When trying to use the endpoints i'm seeing the following issues:
 - `/v0/calculate_monthly_income`: 
   - `"exception": "undefined method [] for nil:NilClass",` 
   - `"v0/fsr_form_transform/income_calculator.rb:23:in 'get_monthly_income'",`
 - `/v0/calculate_monthly_expenses`: 
   - `"exception": "undefined method 'pluck' for nil:NilClass"` 
   - `"v0/fsr_form_transform/old_expense_calculator.rb:75:in 'get_utilities'`
 - `/v0/calculate_all_expenses`: 
   - `"exception": "undefined method 'pluck' for nil:NilClass"` 
   - `v0/fsr_form_transform/old_expense_calculator.rb:75:in 'get_utilities'`
 - `/v0/calculate_total_assets`: 
   - `"exception": "undefined method 'gsub' for [#<ActionController::Parameters {} permitted: true>, #<ActionController::Parameters {} permitted: true>]:Array"` 
   - `v0/fsr_form_transform/old_expense_calculator.rb:75:in 'get_utilities'`

**Comment by Dr-Pongo** [comment]
Closing this ticket as complete with follow on tasks listed below: 
 - **BE** Adjust FinancialStatusReportsCalculationsController and services [#78475](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/78475)
 - **FE** [FSR] Test adjusted FSR calculation endpoints [#78508](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/78508)
