### ISSUE TITLE
[FSR] - Remove old endpoints from FE

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76697]
## Description

FE team will remove old endpoints from front end now that they are no longer being used.

## Tasks
- [ ] Old endpoints removed

## Acceptance criteria

- [ ] Old endpoints removed

## Testing
- [ ] Everything still works

**Comment by HeatherRienks** [comment]
May not be needed; team to discuss.

**Comment by OptionSelect** [comment]
Confirming that this needs to happen.

**Comment by OptionSelect** [comment]
Confirm that there's no work to happen here. We've got endpoints implemented recently and the only others that could be removed are needed to retrieve debts and copays.
