### ISSUE TITLE
Burial | Update URL

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#76700]
## Issue Description
_[CAIA has requested](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68984#issuecomment-1813052852) that the url for the burial 530 form be updated to align with VA design standards._

Current outdated url: www.va.gov/burials-and-memorials/application/530/

The URL should say `www.va.gov/burials-and-memorials/burial-allowance/apply-for-burial-benefits` 
**Apply for burial benefits** is our new title and it should match our breadcrumb and our URL
<img width="80%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/3b07f0ef-2fca-484e-93ab-a5346fe69f6e">

Supplemental claim example:
<img width="50%" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/65800469-e41b-46f0-bb7e-f8ba1aef592b">

---
## Tasks
- [ ] Update the URL to: www.va.gov/burials-and-memorials/burial-allowance/apply-for-burial-benefits
   - [ ] The old URL is: www.va.gov/burials-and-memorials/burial-allowance/application/530/
- [ ] Update breadcrumbs...
   - [ ] From: Home > Burials and memorials > Burial allowance > Review burial benefits application
   - [ ] To: Home > Burials and memorials > Burial allowance > Apply for burial benefits

## Acceptance Criteria
- [ ] URL appears as www.va.gov/burials-and-memorials/burial-allowance/apply-for-burial-benefits

---

**Comment by DLarson-Oddball** [comment]
Hey @steele-lm, can we get confirmation of the new URL: https://www.va.gov/burials-and-memorials/burial-allowance/apply-for-burial-benefits

The current "parent" breadcrumb uses this url: 
https://www.va.gov/burials-memorials/veterans-burial-allowance/
<img width="600" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/133443504/3cf0d6f4-e524-4840-bbb4-911ee697e2d4">

So, I was wondering if url should be to be more in line with the existing content? 
If so, the url would be:
https://www.va.gov/burials-memorials/veterans-burial-allowance/apply-for-burial-benefits

**Comment by steele-lm** [comment]
@fiorella-io Can you verify which url @DLarson-Oddball should use to update the burial form?

**Comment by fiorella-io** [comment]
@DLarson-Oddball I remember CAIA suggested that the breadcrumb, title, and URL should be the same. 

[URL parent]/apply-for-burial-benefits

**Comment by fiorella-io** [comment]
@DLarson-Oddball Copy edits from CAIA: 
- H1 on all pages of the form should be `Apply for a Veterans burial allowance`
- On the intro pages they recommend updating the H2 to `Follow these steps to apply for a burial allowance:`

**Comment by aliyahblackmore** [comment]
Hi all, just cross posting here: 

As mentioned on Slack, we should hold on these updates @fiorella-io @DLarson-Oddball @steele-lm 

Your SMEs shared **new** information about the use of "allowance" vs. "benefits" on the static page, and that conversation impacts the H1 of the form. 

I'll circle back here.

**Comment by aliyahblackmore** [comment]
**Cross posting from Slack:**

- Per the conversation on Teams with your SMEs, we'll just add "reimbursement" to the [static page ](https://www.va.gov/burials-memorials/veterans-burial-allowance/)H1. This is the H1 we'll use: `Veterans burial allowance and reimbursement `We're making this adjustment per SMEs/Jennifer's feedback on Teams. And we can publish this whenever the redirects happen (it sounds like that's after PW approves the PRs in their next sprint). [Figma comment](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB?node-id=165-32381#871775794)

- And for the form intro page header (the H1), we recommend adding "reimbursement" as well. So the header recommendation would be `Apply for a Veterans burial allowance and reimbursement`. This updated H1, per your initial question on Slack, aligns the header with the URL. And it's my understanding that this adjustment slightly impacts the breadcrumbs, but doesn't impact the new form URL recs from @jennymayoco. Mikki shared these breadcrumbs on Slack 7/11 @jennymayoco. I know that you have a separate IA ticket - so feel free to track this there as well.

**UPDATED BREADCRUMBS FROM MIKKI ( @jennymayoco ):**
[VA.gov](http://va.gov/) home > [Burials and memorials](https://www.va.gov/burials-memorials/)  > [Veterans burial allowance and reimbursement](https://www.va.gov/burials-memorials/veterans-burial-allowance/) > [Apply for Veterans burial allowance and reimbursement](http://www.va.gov/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez)

_**Just noting here that you all (the product team) should just share the intro page header with your SMEs. I assume that this is already part of your process, but just noting that here._ 

- And for the text under the H1 on the form intro page you all can add the form title "Application for Burial Benefits (VA Form 21P-530EZ)" [Figma comment](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB?node-id=165-32381#871785748)
- And also noting (you all may already have this as a step) that whenever the intro page header changes, that may impact the confirmation email. So I'd recommend taking a look to make sure the title/subject in the confirmation email match.

**Comment by fiorella-io** [comment]
@DLarson-Oddball, this is what the intro page should look like. The heading (#2) and application name changes (#3) are global. 
What changed:
1. Breadcrumb to `Apply for Veterans burial allowance and reimbursement `
2. H1 to `Veterans burial allowance and reimbursement `
3. Application name `Application for Burial Benefits (VA Form 21P-530EZ)`
4. H3 to `Follow these steps to apply for a burial allowance and reimbursement:`
5. link under check your eligibility to `Find out if you're eligible for a Veterans burial allowance and reimbursement`
![Image](https://github.com/user-attachments/assets/84c5565e-642e-459b-b490-39a0ba477a68)

**Comment by aliyahblackmore** [comment]
@fiorella-io a very small note! 

The form H1 should be `Apply for a Veterans burial allowance and reimbursement`

I'll double check my Figma comment :)

**Comment by aliyahblackmore** [comment]
**Cross posting some updates from Slack:** 

- 7/12 - SMEs shared that they'd like to move back to considering "Veterans burial benefits" as the header. A, Aliyah, and Jenny met with OCTO content lead to discuss this because using this H1 raises other concerns and challenges. 
- OCTO leads will follow up with us (content and IA) on Monday about a best next step. Aliyah will update the product team when we can an answer. 
- Aliyah flagged for the product team that it's best to hold on the URL/breadcrumb/form intro page H1 until we resolve the static page H1 conversation. 

fysa @aprocik1

**Comment by aliyahblackmore** [comment]
Hi folks!

Thanks again for your patience with us while we waited for some updates from our OCTO content and IA leads @steele-lm @fiorella-io @DLarson-Oddball. I'm using italics here only to show the updates.

- **We'll move forward with using this H1 on the static page - SMEs confirmed this on 7/16 (CAIA will make this update in Drupal):** 
_Veterans burial allowance and transportation benefits_

- **As a result, this is what the breadcrumb will now look like (cc: @jennymayoco):** 
_[VA.gov](http://va.gov/) home > Burials and memorials > Veterans burial allowance and transportation benefits> Apply for a Veterans burial allowance and transportation benefits_

- **And this is what the H1 of the form intro page will be:** 
_Apply for a Veterans burial allowance and transportation benefits_
**I also [tracked the related updates](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=165-32381&t=x1NKuXtqLw19K9bg-4) on the form intro page (i.e. to the H1, the H2 and the link text in step 1 of the process list)

Let us know whenever you all will have the breadcrumb and form intro page updates live and we can coordinate publishing the static page H1 update.

**cc:** @aprocik1

**Comment by DLarson-Oddball** [comment]
Hey @aliyahblackmore @fiorella-io, can y'all review this image containing the following updated components
- URL path
- Breadcrumbs
- Form H1
- Form H2
- Link text in Step 1

Let me know if you see anything amiss, thanks!

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/3b4e8f4d-7ec3-4c98-bc02-fee1852d80ba">

**Comment by aliyahblackmore** [comment]
Hi @DLarson-Oddball - I'm joining a meeting but I'll take a look at 3pm ET!

**Comment by aliyahblackmore** [comment]
Hi @DLarson-Oddball - back with a reply here.

- Here's the [Figma design ](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=165-32381&t=KUAFuElKgIt2TGJj-4)with **all** of the content adjustments (including the updated breadcrumbs). 
- And to your point, yes! The screen capture that you included above has the correct text right under the form intro page H1. I just clarified that with Fiorella in Figma. Attached is a screen capture from the Figma design.
![Screen Shot 2024-07-17 at 3 03 19 PM](https://github.com/user-attachments/assets/aef42244-f75a-4dda-88fe-2af164b61e14)

- And I believe that the URL path looks good. [Here's the ticket with the details](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88067#issuecomment-2221687072). @fiorella-io // @jennymayoco feel free to weight in on the URL.

**Comment by fiorella-io** [comment]
@DLarson-Oddball Make sure that for the authenticated intro page, the action link says, `Start the burial allowance and transportation benefits application`
<img width="702" alt="image" src="https://github.com/user-attachments/assets/acf719d5-62b0-4d04-aacf-9dfc7d99e282">

cc/ @aliyahblackmore

**Comment by fiorella-io** [comment]
@DLarson-Oddball Make sure that for the authenticated intro page, the action link says, `Start the burial allowance and transportation benefits application`
<img width="609" alt="image" src="https://github.com/user-attachments/assets/fde374e2-c50a-41e3-8ce6-82bdf9cb7df5">

cc/ @aliyahblackmore

**Comment by jennymayoco** [comment]
@fiorella-io @DLarson-Oddball something I want to flag is please ensure you update the title tags to match the h1. Also, if there's any updates on the URL or the redirect process, feel free to share it in the [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88067) so PW team has eyes on that as well. other than that, no additional comments on the URL or general ia feedback.
