### ISSUE TITLE
BE | EDU CH33 Changes | Integrate w/revised/ammended/expanded API

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76716]
## Background
Lighthouse will be adding an additional control flag to the Direct Deposit API GET response that will be used to determine if a user can add or update Direct Deposit for Education Benefits.

## Tasks
- [x] Map additional `isEduClaimAvailable` education direct deposit flag. 
- [x] Write specs and update swagger docs.

## Acceptance Criteria
- [ ] Test scenarios in staging: C&P, EDU, Both, None.

**Comment by mtcA6** [comment]
[waiting on a response from LH, see slack comment in this channel](https://dsva.slack.com/archives/C06JV0KHZNF/p1709562011853009)

**Comment by tpharrison** [comment]
Lighthouse responded and the flag that will be used to determine if a user has education benefits is `eduClaimInd`.

**Comment by mtcA6** [comment]
discussed w/Tom we're going to close this out since we're waiting on test users and will confirm this is funcitoning when we complete qa
