### ISSUE TITLE
Design | EDU CH33 Changes | Mock up our new use cases/user flow

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76711]
## Background 
Mock the various scenarios for our happy path with everything going smoothly 

Scenario 1 - doesn't have either benefit 
Scenario 2 - has edu 
Scenario 3 - has C&P 
Scenario 4 - has both 

## Tasks 
- [x] mock up the alerts 
- [x] get content approval 
- [x] review w/PO/PM 
- [ ] move to validate for FE 
- [x] add link for the mocks to the description for the upcoming FE ticket #77466

## Acceptance Criteria 
- [ ]  we've got new mocks and they are linked to the FE ticket

**Comment by andaleliz** [comment]
I reviewed the screen with the most changes with the team today, and we decided to proceed with the section heading style we currently have on the page (h3 w/ gray background) initially, and then explore cleaning up the page a bit with a different heading style. That would be work for a separate ticket.

I've outlined all the scenarios in [the user flow](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=347-7871&mode=design&t=IqFCCEPhlqqHC8uj-11) and have a few things I need to get reviewed by content (I was wrong in planning when I said there was nothing, womp womp).
- Label for "learn more" additional info component + link text
- Whether or not the fraud note belongs in a summary box when the only other thing on the page is an alert, such as [the downtime page](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=239-9457&mode=design&t=IqFCCEPhlqqHC8uj-11).

I'm hoping to get this content reviewed tomorrow so we can close this out the first half of the sprint.

**Comment by andaleliz** [comment]
@mtcA6 and @Samara-Strauss I got the content reviewed and approved today, and updated the user flow + all screens accordingly.

I have two changes to call out that are different from what we're doing today:
1. CAIA recommend removing the "learn more" eligibility links/content from the page. The reasoning being that if a person has made it to DD in profile, going to eligibility information is a weird turn to take in the user journey.  I agree with that, and would love to focus the page as much as possible on the primary task.  I've taken the additional info component out of the mock-ups, but if you feel strongly eligibility links belong in DD, I can add them back and revisit the language during next week's office hours.

2. I added the "view payment history" section to all states, after Travis pointed out that people may need this for historical or tax purposes. The bonus of this is that I think it'll remove some conditional logic from the FE code, which simplifies things.

One other note, for future:
- The content team is working on pages to address fraud and scams. Once those are live, we can update our fraud note summary box to a link that points to those pages, and simplfy the page even further. 

Please take a look and lmk if you're on board with what I'm proposing. Thank you!

**Comment by mtcA6** [comment]
Thanks Liz, you've done a ton of work super quickly 🎇 

Am I right in thinking we need to wait until next Thursday to review w/content folks and get things approved? Once approved can you link those to the FE ticket (I've added a task to the description above linking to the corresponding FE ticket) and close this out. 

1. Don't feel strongly, and I think you had said link click traffic was relatively low, is that right or am i misremembering with a different feature/component? 
2. cool dealio! 

- for the future content note about fraud, the fraud info should be closer to the bank account information rather than at the bottom of the page with the payment history. 

One additional thought came to mind, I'm going to schedule a message in slack for next week when Tom is back, curious to know if, in that first state (screen grab below), the payment history part will need to have it's own maintenance window alert and corresponding pager duty services so we don't send users to a non-working page.  
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/afeea1d8-53b9-4a22-bd44-246e3fc9aeff)

cc: @clantosswett

**Comment by andaleliz** [comment]
@mtcA6 everything is approved by content as-is, so I've gone ahead and added the link to the FE ticket and will close this out. I created a couple of desktop mock-ups for reference, as well. Once we get closer to this being live we can shore everything up.

>One additional thought came to mind, I'm going to schedule a message in slack for next week when Tom is back, curious to know if, in that first state (screen grab below), the payment history part will need to have it's own maintenance window alert and corresponding pager duty services so we don't send users to a non-working page.

Good idea to check with Tom. I'm fairly certain that is static content today, and I think that'd be the way to move forward with it as well. I'm all about not showing alerts unless we really need to.

**Comment by mtcA6** [comment]
@andaleliz what do you mean by: "I'm fairly certain that is static content today"

Are you referring to our content or the page we're sending users to?

**Comment by andaleliz** [comment]
I'm referring to our content. The box itself shows up conditionally based on if a person has payments, but the content inside the box doesn't change.  IMO, it wouldn't make sense to add code to make that box check on the status of the payment history tool and then report an alert on the DD page if the payment tool has a problem.  Maybe I misunderstood what you were suggesting though.
