### ISSUE TITLE
BE | EDU CH33 Changes | Remove legacy bgs calls

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76721]
## Background
Remove Vets-API endpoints to BGS CH33.

## Tasks
- [x] Remove CH33 Controller and routing.
- [x] Remove swagger docs for CH33 endpoint.

## Acceptance Criteria
- [ ] Test in staging.

**Comment by tpharrison** [comment]
These calls were removed, but the changes won't be merged until August:
- [PR that removes CH33 references](https://github.com/department-of-veterans-affairs/vets-api/pull/17785)
