### ISSUE TITLE
[FE] - multi facility and single facility pages

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#76727]
## Description
Create the pages to support multi facility and single facility travel-claims. Multi-facility will utilize the `va-checkbox` component with the `tile` property. Appointments will be shown grouped by facility (stationNo), and selected by facility. Multiple facilities can be selected. Eligible appointments will already be filtered in `checkInData.context.eligibleToFile` If a facility has already been filed for that day you will see it in `checkInData.context.alreadyFiled`, all appointments from the payload will still be in `checkInData.appointments`

Both pages should write the active facility(s) to `checkInData.form.data.travelClaims`:  so we (a) know which claims to send (b) know which facility(s) to store in localStorage at the end and so that we can (c) restore the active facility(s) in the case of a reload. Writing this data to the form object in checkInData we allow it to get saved to progress in localStorage automatically.
 example:
```
[
  {
     stationNo: [string],
     startTime: [string],
     multipleApts: [bool],
  }
]
```
For each station we are making a claim for include that station number, the startTime of the earliest appointment at that station, and if there are more than one appointment for today at that station. One array item per station the user selects.

Determine if both pages should live at the `travel-mileage` route and have logic to determine display, or if they should be separate routes and pages.

## Wireframes
- [Wireframes - multi](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=1300-6142&mode=design&t=kP55u2GJX2zPVmuo-0)
- [Wireframes - single](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-6883&mode=design&t=kP55u2GJX2zPVmuo-0)

## Tasks
- [ ] create page content for multi
- [ ] create page content for single
- [ ] capture active facility(s) in redux (context)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
This initial work is complete and merged. Updates from UX are in the PR relating to the submission hook. So leaving this here for just a bit until that is ready for screenshots.

**Comment by loripusey** [comment]
@brianseek please refer to the UX ticket for changes. If you need an additional ticket, let me know.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/77685

**Comment by brianseek** [comment]
<img width="159" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--784e0e0719f15644be3e24b5a0124cbb0cb3e9cd/localhost_3001_my-health_appointment-travel-claim__id%3D8379d4b5-b9bc-4f3f-84a2-9cb9983a1af0.png" alt="localhost_3001_my-health_appointment-travel-claim__id=8379d4b5-b9bc-4f3f-84a2-9cb9983a1af0.png" />

**Comment by brianseek** [comment]
<img width="159" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--784e0e0719f15644be3e24b5a0124cbb0cb3e9cd/localhost_3001_my-health_appointment-travel-claim__id%3D8379d4b5-b9bc-4f3f-84a2-9cb9983a1af0.png" alt="localhost_3001_my-health_appointment-travel-claim__id=8379d4b5-b9bc-4f3f-84a2-9cb9983a1af0.png" />

**Comment by brianseek** [comment]
<img width="142" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39bf161b7ee8f549bf138136c03b20cfcaa1301d/localhost_3001_my-health_appointment-travel-claim__id%3D8379d4b5-b9bc-4f3f-84a2-9cb9983a1af0%20%282%29.png" alt="localhost_3001_my-health_appointment-travel-claim__id=8379d4b5-b9bc-4f3f-84a2-9cb9983a1af0 (2).png" />

**Comment by brianseek** [comment]
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e968204277483c320a66c368757df0cba6d44be8/localhost_3001_my-health_appointment-travel-claim__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%283%29.png" alt="localhost_3001_my-health_appointment-travel-claim__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (3).png" />

**Comment by brianseek** [comment]
<img width="174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f762927f06c284d0ecc1fca1548f49cfedcbff0/localhost_3001_my-health_appointment-travel-claim__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%284%29.png" alt="localhost_3001_my-health_appointment-travel-claim__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (4).png" />

**Comment by brianseek** [comment]
here is the button order on wider screens. This applies to both pages
<img width="311" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab69d7e7189ffb0392c2ca36894f472504efd254/localhost_3001_my-health_appointment-travel-claim__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%285%29.png" alt="localhost_3001_my-health_appointment-travel-claim__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (5).png" />

**Comment by brianseek** [comment]
@benbrasso-agile6 / @zach-park This is ready for validation, see the screenshots in comments above.

**Comment by benbrasso-agile6** [comment]
GTG

**Comment by benbrasso-agile6** [comment]
@brianseek just got a change from CAIA to make the description field

`Select the appointments you want to file for`

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by brianseek** [comment]
🥹

**Comment by brianseek** [comment]
@cgednalske those changes will get picked up with the rest of the updates in 77013
