### ISSUE TITLE
BE | EDU CH33 Changes | Data dog updates to see EDU vs C&P updates

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76722]
## Background
We would like to track whether Direct Deposit information for a user is related to C&P or EDU.

## Tasks
Add the following metrics for "gets" and "updates" to direct deposit requests:
- [ ] C&P
- [ ] EDU
- [ ] Both C&P and EDU
- [ ] None

## Acceptance Criteria
- [ ] Verify metrics are being collected in staging.
- [ ] Verify metrics are being collected in prod.
- [ ] Adam and Tom to create an additional ticket to include the control information into the update request

**Comment by tpharrison** [comment]
Thursday, Mar 21st...

Reached out to David Lennon to verify logic needed to answer the following questions:

1. Should the user be able to manage their direct deposit information?
2. Is the direct deposit information related to EDU benefits?
3. Is the direct deposit information related to C&P benefits?

David directed me to Matthew McCollum.  Matthew is looking into it.

**Comment by tpharrison** [comment]
I was able to get started on this ticket, but felt it was better to break it up into 3 smaller tickets:
- #79248
- #79249
- #79250
 
Reduced to 1 point.
