### ISSUE TITLE
Team | EDU CH33 Changes | QA

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76720]
## Background 
this ticket is so we can run QA as a team 

- [QA spreadsheet](https://docs.google.com/spreadsheets/d/1rOD8w0YNTlfbefVK7t2RsWoYK_ui1gTkVhCXlJE5VDg/edit#gid=0)
-  [QA Defect Log ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/ch33-bdn-corpdb-migration/qa) 

## Notes to keep in mind
- staging users have been unstable, the users listed in the qa spreadsheet may not accurately reflect the test scenarios we thought they were originally supposed to reflect, we'll have to figure this out as a team because staging has been so chaotic as of late
- we may still need help staging EDU benefits (user 380 only has edu benefits) 
- [we should have plenty of C&P users here](https://docs.google.com/spreadsheets/d/1LUGAejfMpfE8N4A5bl0XYyTYwLCcZya30L4KACbouQw/edit#gid=0) by filtering on can update direct deposit == true and edu claim == false 
- We may not have a clear way to differentiate between users w/C&P and users w/ EDU. When we go to prod we should be able to see users who have C&P only but we won't be able to tell if a user has BOTH or just EDU benefits based on our most recent conversations around our the corp flags provided by LH. This is something we learned 4/10 and are discussing 4/11 
     - we may want to test a user with the edu claim flag turned on, turned off, and an account without access to direct deposit. That may be all we can test  

## Tasks 
- [x] run QA and generate an adverse findings report 
- [x] rerun QA after updates have been made
## AC 

- [x] we've completed QA and are ready to recruit for UAT (or we have an issue log capturing our outstanding problems)

**Comment by mtcA6** [comment]
moved to block, we can rerun QA when updates are made with Adam's latest PR. Estimating the soonest this will be unblocked is 4/17
