### ISSUE TITLE
Content updates to health care static pages 

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#76762]
## Issue description
We need to make updates to the [Eligibility for VA health care](http://preview-prod.vfs.va.gov/preview?nodeId=31) and [How to apply for VA health care ](http://preview-prod.vfs.va.gov/preview?nodeId=35)static pages in preparation for the inclusion of the toxic exposure questions.

---
## Tasks
- [ ] Update static pages (Aliyah) 
- [ ] Share with SMEs for accuracy review (Aliyah) 
- [ ] Copy edit (Megan)
- [ ] Publish

**Comment by aliyahblackmore** [comment]
I made updates to these static pages to align with the toxic exposure questions on the online 1010EZ form.

I did a review during the Danielle content meeting on 2/21. We'll plan to revisit these pages after the launch of the new questions as there are some other adjustment we can make to align with other style standards (i.e. statement headers)

**Eligibility for VA health care**
Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=31
- Under header "Is there anything that will make me more likely to get these benefits?" I added a point about exposure to toxins and hazards. This addition is aligned with the updates on the PDF version of the form - "toxic exposure activity (TERA)." The content adjustment avoids introducing a new term ("TERA") and includes more details about the types of exposures as they relate to VA health care.
- I added periods across the list, since the new point is two sentences. 


**How to apply for VA health care**
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=35
- In the featured content box, under "You'll need this information," I added content to the point about military discharge papers. 
- Prior to these updates, there was one point with two sentence but the other points didn't include periods. I added periods to all of the points in the list.
- I flagged with Danielle (2/21) that I'll plan to revisit this page after the 3/5 launch as there may be some other adjustment we can make to the featured content box (i.e. two lists)

**Comment by aliyahblackmore** [comment]
**Update here:** 

I shared the static page updates with SMEs. 

Still waiting on updates from product team on what'll happen to saved in in-progress forms. 

Last communication with product team was on 2/23.

**Comment by aliyahblackmore** [comment]
**Update here:** 

- **Eligibility page** - as of 2/23, Danielle was working on an alert that's schedule to go up at some point this week (reverted the page). I let Megan know that she can hold on copy editing the changes I made until I hear back from Danielle/Randi re: the alert.

**Comment by aliyahblackmore** [comment]
**Update here:** 

Randi published the PACT Act alert on the How to apply and Eligibility pages. I reverted both pages and let Megan know that they're ready for her to copy edit.

**Comment by aliyahblackmore** [comment]
This is still in progress. Megan will need to copy edit ahead of 3/5. 

Last communication with product team was on 3/1.

**Comment by megzehn** [comment]
Thank you @aliyahblackmore!!

Confirming I copy edited the changes, and all looks good there. 

I know we're planning on more updates to these pages after we launch this, so I'll note 2 other things we may want to address at that time:

- Breaking up [these lists](https://www.va.gov/health-care/eligibility/#-is-there-anything-that-will-ma) so there aren't more than 7 in a bullet
- Clarifying this line in How to apply for VA health care: "If you’re using a power of attorney, you’ll need to submit a copy of the Power of Attorney form along with your application."

**Comment by aliyahblackmore** [comment]
Confirming that these are published and I shared the live links with SMEs.

**Comment by aliyahblackmore** [comment]
@strelichl we can close this ticket!
