### ISSUE TITLE
[BE, FE] 10-10 EZ & EZR - Performance Monitoring: Update PagerDuty to remove the service dependency between the forms

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76791]
## Background
As a result of a late daily deployment which introduced a PR that impacted submissions and access to the 10-10EZ, authenticated Veterans were impacted overnight and into the next morning with not being able to access the form.
During the triage process, the team also decided to configure a maintenance window for the product to avoid confusion and frustration for end users.  However, because the maintenance windows are configured in terms of upstream dependencies, it was necessary to take both the 1010ez and 1010ezr applications offline, even though only the former was affected. 

We need to update PagerDuty so we can separate the EZ and EZR applications, and set independent maintenance windows.

> From Adrian:
>The MHV teams are [following this pattern](https://dsva.slack.com/archives/C018V2JCWRJ/p1706803015085569?thread_ts=1706802786.997869&cid=C018V2JCWRJ) with an umbrella PD service (called mhv_platform) that disables all apps, and individual services for each app
>
>![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/a0921dbf-c65d-4ad1-b94c-dac36ef29c25)

> 
>you have everything you need - the [docs are here](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-AddinganewPagerDutyservice), with the exception that they need to be updated to say to update the vets-api config in the manifest repo instead of the vets-api repo (I believe that [@Stephen Barrs](https://dsva.slack.com/team/ULY2TEZUK) has raised that)

## Tasks
- [x] Review the MHV document screenshot on how they separated their products in Pagerduty
- [x] Follow the instructions provided in the [Platform document](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-AddinganewPagerDutyservice) to create new, more granular services for the EZ and EZR
     - **EXCEPTION** the document has not yet been updated to state "**Update the vets-api config in the manifest repo**" instead of the vets-api repo
     - You will want to update the "manifest repo"
- [x] If you DO NOT have PagerDuty access, that is OK!  Heather and Alex do, and we can help with that part of this effort.
- [x] Reach out to Adrian Rollett for any questions or assistance
- [ ] Create a maintenance window for each application for testing (should be able to do this in Staging, but may also test after hours in Production)

## Acceptance Criteria
- The 10-10 EZ and EZR will be separated in Pagerduty so that we can set maintenance windows for each application independently.

**Comment by emily-brown34** [comment]
let's get some points on this ticket before it's closed out, please

**Comment by lihanli** [comment]
response from `/v0/maintenance_windows`
```json
{
  "data": [
    {
      "id": "210",
      "type": "maintenance_windows",
      "attributes": {
        "external_service": "",
        "start_time": "2024-03-20T06:00:00.000Z",
        "end_time": "2024-03-20T09:00:00.000Z",
        "description": ""
      }
    },
    {
      "id": "211",
      "type": "maintenance_windows",
      "attributes": {
        "external_service": "global",
        "start_time": "2024-03-20T06:00:00.000Z",
        "end_time": "2024-03-20T09:00:00.000Z",
        "description": ""
      }
    },
    {
      "id": "216",
      "type": "maintenance_windows",
      "attributes": {
        "external_service": "1010ez",
        "start_time": "2024-03-18T20:21:11.000Z",
        "end_time": "2024-03-19T00:21:10.000Z",
        "description": ""
      }
    },
    {
      "id": "217",
      "type": "maintenance_windows",
      "attributes": {
        "external_service": "1010ezr",
        "start_time": "2024-03-18T20:21:11.000Z",
        "end_time": "2024-03-19T00:21:10.000Z",
        "description": ""
      }
    }
  ]
}
```
