### ISSUE TITLE
Update Collaboration Cycle Kickoff and overview documentation

### ISSUE THREAD

**Issue by coforma-terry** [department-of-veterans-affairs/va.gov-team#76794]
## User Story
As a VFS team member, I want to know what is expected of me and my team, and what to expect overall in the Collaboration Cycle process, so that I can ensure my team is prepared.

Assignee: @erinrwhite @rferguson13 
Peer Reviewer: @allison0034 

## Description
In order to better prepare VFS teams for the Collaboration Cycle and to better educate them on who Governance and CAIA are and how we both provide support, the Platform Website/Collaboration Cycle pages need to updated so that they  reflect this information appropriately.

While CAIA focuses on transitioning their CAIA touchpoint page into an informational page on who they are and their process, Governance will work on updating other PW/Collaboration Cycle pages include the overview page, the kickoff page, and potentially others.

The pages should be revised to better communicate what VFS teams should expect in the Collaboration Cycle, and not just within the kickoff ticket. Review the notes from the weekly sync with CAIA for further details. 

Lastly, CAIA has asked that we make changes to how CAIA is defined in the [CAIA vs. Governance FAQ.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs#CollaborationCycleFAQ-PlatformGovernancevs.SitewideCAIA):

> Goal: Provides teams with the ongoing guidance, direct partnership, information, and resources needed to build exceptional products for Veterans and family members.
> Role: Partnership and guidance

**Note:** It is recommended that the proposed changes be reviewed with CAIA before any publishing occurs. We want to ensure that the tone, voice and language used by CAIA on our pages is consistent with the page they are working on updating. 

### Notes from weekly sync with CAIA
What is CAIA's role in the Collaboration Cycle and how is this communicated to VFS teams?

For the changes to the VFS Collaboration Cycle process we need to review and update the current documentation on the VFS platform website. We also want to update the supporting processes such as Slack workflows and the Collaboration Cycle Request ticket in Github, if applicable.

Here's what to expect when working in the Collaboration Cycle:
- How long do things take?
- Diff bw CAIA and Governance - point to CAIAs page
   - CAIA is there to support you get through the Collab Cycle
- sample flow/journey ?
- Before you kickoff, here's what you need to know.
- What collab cycle is and what it's not
- Who's responsible here? VFS and Governance
   - we're not here to PM for you! 
- roles and responsibilities (for both VFS and CC folks)
- FAQ page questions
- what frameworks we use for feedback (MSC vs. VA.gov Exp Std vs. QA stds)
- including CC Overview pages in scope
- Isn't kickoff considered a touchpoint? let's not have kickoff page do double duty
   - add kickoff page back to touchpoints and create a new page to communicate expectations
- Shira recommends we review the Service Design Research for feedback about CAIA.

## Impacted Artifacts
[Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
[Kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff)
[FAQ ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs)

## Tasks
- [x] Review current guidance
- [x] Create outline of proposed changes
- [x] Draft updated pages
- [x] Peer review
- [ ] Send to CAIA for review

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Updated PW pages reflect that CAIA is an integral part of the collaboration cycle 
- [x] Updated PW pages better prepare VFS teams for what to expect in the Collaboration Cycle

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.

### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by coforma-terry** [comment]
To do for Terry:
Draft out new CAIA page defining parameters of CAIA's involvement in the CC.
Some of this detail will be added to the Kickoff page!

**Comment by shiragoodman** [comment]
@coforma-terry I plan to use this ticket for managing my teams work/changes to the Platform Website pages. Would you mind creating your own ticket for tracking the work your team will be taking on?

**Comment by rferguson13** [comment]
For transparency: @erinrwhite and I have split the work accordingly:
- Erin is going to work on the Kickoff page
- I'm going to work on the Collab Cycle overview page

@shiragoodman, as we combed through these pages, we noted a few opportunities for improvement. However, this could lead to scope creep. We'll keep it to the impacted artifacts listed, but we may want to have a future ticket that addresses other pages (specifically, the [Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints) page)

**Comment by erinrwhite** [comment]
@rferguson13 

Quick updates to these documentation page organization in our drafts - I created a new "Collaboration cycle section landing page" which will replace the [current CC section landing page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) content with a list of child pages. I nested all our other page edits under it.

- [76794 - Collaboration cycle (section landing page)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054240236)
  - [76794 - Collaboration cycle overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview)
  - [76794 - Collaboration cycle kickoff](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436405/76794+-+Collaboration+cycle+kickoff)
  - [76794 Collaboration Cycle FAQ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054239764/76794+Collaboration+Cycle+FAQ)

**Comment by shiragoodman** [comment]
thank you both for tackling this! Just curious, Rebecca I believe you had suggested created a new kickoff page (that lives alongside the other touchpoint pages) since we're restructuring the current kickoff page to focus more on expectations and less on kickoff. Where did you 2 land on this? I like that idea, and I'm wondering if that's still something you plan to pursue. 

@erinrwhite @rferguson13

**Comment by erinrwhite** [comment]
@shiragoodman @rferguson13 We did indeed decide to peel off the Kickoff page to become a page in the touchpoints section, and to focus the kickoff page specifically on the kickoff itself. We plan to turn the [current "Kickoff" page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff) into a Collab Cycle overview page.

**Comment by shiragoodman** [comment]
excited to see the proposed changes! If you'd like to walk thru everything before you get too far, please let me know :)

**Comment by rferguson13** [comment]
@erinrwhite @shiragoodman [Here is a ROUGH draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview). Before I flesh out more of the content (especially in the later sections), I wanted to get some feedback from y'all. What do you think of the table?

**Comment by erinrwhite** [comment]
Updated the [kickoff touchpoint page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436405/76794+-+Collaboration+cycle+kickoff+request) and I think it's ready for your review @rferguson13

**Comment by rferguson13** [comment]
@erinrwhite - I made some quick suggestions. If you can't get to them by EOD today, let me know, and I'll make sure to get to it before the end of the sprint. 

@shiragoodman - Could you look at [this page, specifically the table?](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview) Erin has made a good suggestion regarding the table, but I'm worried that moving it from the Collab Cycle Overview page to the Touchpoint overview page will mean that there's not enough info on the CC overview page. Let me know what you think.

**Comment by erinrwhite** [comment]
@rferguson13 Copied over the [Touchpoints page into the drafts folder](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3067969538/76794+-+Touchpoints), and nested the Kickoff page under it as we plan to do in production

**Comment by rferguson13** [comment]
Ok! @allison0034 We're ready for your review!
- [Collaboration Cycle overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview)
- [Collaboration Cycle kickoff request](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436405/76794+-+Collaboration+cycle+kickoff+request)
- [Collaboration Cycle FAQ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054239764/76794+Collaboration+Cycle+FAQ) Only the CAIA section here.
- [Touchpoints](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3067969538/76794+-+Touchpoints)

**Comment by allison0034** [comment]
This looks great! I made a couple of suggestions.
One thing I am hung up on is [this page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) still existing. It looks like it is part of our collab cycle but it is not mentioned in the [touchpoints page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3067969538/76794+-+Touchpoints).

It also contradicts the instructions for CAIA on the [kickoff page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436405/76794+-+Collaboration+cycle+kickoff+request) (CAIA reaches out vs submit a CAIA intake request).

**Comment by rferguson13** [comment]
@shiragoodman What are your thoughts on @allison0034 's comment? It's true: the [current CAIA page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) is out of date; I was under the impression that they would rewrite it. In the meantime, should we delete the page to avoid confusion?

**Comment by shiragoodman** [comment]
@allison0034 @rferguson13  - you guys are both correct. CAIA is currently working on rewriting the CAIA touchpoint page. We will not be publishing any changes to the Platform Website until CAIA makes the changes to their page. We will also be moving their page from the Touchpoints heading to the main left nav. 

do not delete the page. When CAIA is done rewriting their page, we will review it alongside the pages we're making changes to in this ticket. They'll all get published together.

**Comment by rferguson13** [comment]
Thanks @shiragoodman 

With that in mind, @allison0034 - I'll remove the links to the existing CAIA page, knowing we'll need to link to their new page in the future. Then we can send this ticket off to them for review.

**Comment by allison0034** [comment]
Perfect!

**Comment by shiragoodman** [comment]
Draft pages communicated to CAIA [via Slack. ](https://dsva.slack.com/archives/G01DXP10GCA/p1712779106956599) Any changes to the draft document will be addressed in a separate ticket (still to be created). Closing.
