### ISSUE TITLE
Update Platform Orientation operational guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#76802]
## User Story
As a Platform team member supporting Platform Orientation, I want to view up to date guidance on Platform expectations for hosting Orientation Sessions so that I can host a session per the guidelines.

Assignee: @briandeconinck 
Peer Reviewer: @rferguson13 

## Description
The current operational guidance for Platform Orientation needs to be reviewed to remove any mentions of live sessions and updated to include guidance on when (and how) to record orientation sessions if/when they fall out of date.

## Impacted Artifacts
[Operational Guidance for Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Operational+Guidance+for+Orientation+Sessions)
[Roles and Responsibilities for Orientation hosts](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2595094717/Roles+and+Responsibilities+for+Orientation+hosts)
[Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)

## Tasks
- [x] Review all above artifacts and identify any instances where live sessions are mentioned
   - This could be Calendly, Zoom, Zoom host, attendees, participants, etc.
   - Ask yourself what information within the guidance is no longer relevant now that we're discontinuing the live sessions
- [x] Either remove the live session references or reword appropriately
   - For example, in the [General Orientation section](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Operational+Guidance+for+Orientation+Sessions#General-Orientation) of the Operational Guidance page, we can remove rows "When is it hosted", "How do people sign up", etc. because that is no longer relevant information.
   - On the Orientation Host/Zoom Host Guidance page, we refer to the Zoom host and the instructor. Is it still critical to make that distinction? Maybe. However since the session is no longer held live, the Zoom host and the instructor may be the same person. Use your best judgment.
   - Updated drafts:
      - [Operational Guidance for Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039330305/76802+-+Operational+Guidance+for+Orientation+Sessions)
      - [Roles and Responsibilities for Orientation Hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039363073/76802+-+Roles+and+Responsibilities+for+Orientation+Hosts)
      - [Orientation Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039330326/76802+-+Orientation+Host+Guidance) (renamed from Orientation Host/Zoom Host Guidance)
- [x] Add guidance for checking to see if the session is still relevant once per quarter
   - Platform Orientation hosts will only need to re-record at the top of the quarter if their session is out of date or requires new processes. 
   - Guidance for ensuring relevance included in [Roles and Responsibilities for Orientation Hosts > Orientation session materials](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039363073/76802+-+Roles+and+Responsibilities+for+Orientation+hosts#Orientation-session-materials)
- [x] Add guidance for (interim solution) adding referenced links to Description section of YouTube video (per note in ticket #77477)
   - If any of the current live sessions mention the slide deck, they will need to be re-recorded
   - Platform Orientation hosts should either refer to the Description of the YouTube video for links or to the New VFS Team Member ticket. 
   - Information about description links added in [Orientation Host Guidance > Uploading your recording and transcript to YouTube](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039330326/76802+-+Orientation+Host+Guidance#Uploading-your-recording-and-transcript-to-YouTube) and referenced in out-of-date guidance in [Roles and Responsibilities for Orientation Hosts > Orientation session materials](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039363073/76802+-+Roles+and+Responsibilities+for+Orientation+hosts#Orientation-session-materials)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Platform Orientation guidance for hosting orientation sessions has been updated to remove references to live sessions
- [ ] Platform Orientation guidance for hosting orientation sessions has been updated to include guidance on how to reference links and urls within the recording

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@rferguson13 I think this is ready for review. Draft updates:
- [Operational Guidance for Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039330305/76802+-+Operational+Guidance+for+Orientation+Sessions)
- [Roles and Responsibilities for Orientation Hosts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039363073/76802+-+Roles+and+Responsibilities+for+Orientation+Hosts)
- [Orientation Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039330326/76802+-+Orientation+Host+Guidance) (renamed from Orientation Host/Zoom Host Guidance)

Hope all of my edits make sense. Note that the ATO orientation is currently handled differently from the others so I didn't make any changes to that one on the operational guidance page.

**Comment by shiragoodman** [comment]
@rferguson13 let me know if you'd like me to review too

**Comment by rferguson13** [comment]
@briandeconinck Made some comments! Some out-of-date instructions will need to be updated; we no longer allow links to Google Slides, so we'll need to remove those portions and tell the session leaders where they can include links. I believe we agreed to add links to the YouTube video—is that correct, @shiragoodman?

**Comment by shiragoodman** [comment]
@rferguson13 yes and no. If the link is listed as something for the VFS team review in the New VFS Team Member gh ticket, then we should reference the ticket. However, if the link isn't included w/in the gh ticket, then we can add the links to the description section of the YouTube video. It might be a good idea to suggest a format/template for adding links to the description section.

**Comment by rferguson13** [comment]
@shiragoodman Ok! I made the updates I suggested. Want to take a quick look before I push them live?

**Comment by shiragoodman** [comment]
@rferguson13 I added 1 comment in response to your comment within [this doc.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3039363073/76802+-+Roles+and+Responsibilities+for+Orientation+Hosts)

Other than that, I think this is good to go! Please feel free to publish

**Comment by rferguson13** [comment]
@shiragoodman - All pages are updated! Good to close?

**Comment by shiragoodman** [comment]
Good to close!
