### ISSUE TITLE
Update Platform Satisfaction Survey references to new schedule

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#76808]
## Purpose
As an [action item ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2961604609/Brainstorming+session+improving+Survey+participation#Question-1%3A-How-might-we-make-it-easier-for-desired-personas-to-access%2C-absorb%2C-and-act-on-all-forms-of-feedback-that-Platform-collects%3F)from our brainstorming workshop, we're updating the Survey frequency from quarterly to semiannually. 

Would halving the frequency to twice a year heighten its perceived importance?
-Maybe 1st and 3rd quarters would be optimal
-it’s not like teams are pivoting priorities every single qtr.  It takes closer to ~6months for most items to be carried out
-it’s an easier ask, and doesn’t feel like “we just did this a few weeks ago”
-also speaks to the value/nature of the feedback we’re looking for in the Survey; it’s a gauge, not something providing specific details on a matter

## Tasks
- [ ] Share plan with Jason 
- [ ] Share plan with Naomi
- [ ] Locate any instance that refer to the Survey title as Quarterly and update them to Semiannual
- [ ] Announce this change at ToT (Bryan)

## Acceptance Criteria
- [ ] All references will reflect new frequency

**Comment by tayism** [comment]
@steel36 I discussed this with Naomi, and she let me know that OCTO may have different expectations on how frequently we should run the survey (it seems they'd like it more often than not).

How should we proceed?

**Comment by steel36** [comment]
@tayism Yes, she reached out to me about it yesterday.  I conveyed that beyond our own PO, we don't know of any "official" authority to appeal to on this.  We're scheduled to talk about it in our sync today.

**Comment by steel36** [comment]
Talked with Matt this morning.  Will discuss at standup today.

**Comment by steel36** [comment]
We're going to pause on this item and consider it in the future.  I'm moving it to the Icebox.
