### ISSUE TITLE
Update VFS-facing guidance on Platform Orientation

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#76803]
## User Story
As a new VFS team member, I want to follow the guidance on how to partake in a Platform Orientation session so that I can learn how the Platform provides support. 

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
This ticket will include updates to all VFS-facing guidance for Platform Orientation to remove references to any live orientation sessions and to add options for the VFS to reach out for support if needed (see ticket #76800).

We need to update the github template, delete all Calendly events for orientation sessions, and update Platform Website.

Note: do not publish changes to Platform website and/or merge any PRs. Those tasks will take place in ticket #76805.

## Impacted Artifacts

- New VFS Team Member template
- Calendly orientation sessions
- [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation) page on PW
- [Guidance for new teams and team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members)
   - [Platform Orientation user flows](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2091057177/Platform+Orientation+User+Flows)
- [Orientation sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)

## Tasks
- [x] Review the changes made to the [operational guidance](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76802) to familiarize yourself with the changes happening for Platform
- [x] Edit the GitHub ticket (New VFS Team Member) to remove actions asking the VFS team member to sign up for orientation - the new task should only ask them to view the recording
   - PR: #80292  
- [x] Create draft docs of the impacted PW pages and update them to remove all actions related to Calendly and/or signing up for a live session
   - [All documentation drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3069837332/76803+-+VFS-facing+orientation+updates)
      - [Draft Platform orientation](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3070787585/76803+-+Platform+Orientation)   
      - [Draft Orientation sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3072753665/76803+-+Orientation+Sessions)
      - [Draft Guidance for new teams and team members](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3072851975/76803+-+Guidance+for+new+teams+and+team+members) 
- [x] Add a row to each table (minus ATO) on the Orientation sessions page for VFS to reach out if they have questions and/or need support (see ticket #76800 for details).
   - [Draft Orientation sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3072753665/76803+-+Orientation+Sessions)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS team members are no longer asked to sign up for an orientation session
- [x] VFS team members are only directed to view the orientation session recordings
- [x] VFS team members have a Slack channel and/or Office hours for requesting support from Platform after viewing the orientations session.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck  - please review when you return from your OOO and let me know if you have any questions. Same for #76805!

**Comment by briandeconinck** [comment]
@shiragoodman This is ready for review, if you have time while Ian is out.

**Comment by shiragoodman** [comment]
@briandeconinck I added 1 comment to the Platform Orientation page. Otherwise everything looks great! I also approved your PR. We should be good to start #76805 😄

**Comment by shiragoodman** [comment]
@briandeconinck I also just added 1 more comment to the Orientation Sessions page

**Comment by shiragoodman** [comment]
Noting that I have also permanently deleted all Orientation Session events in Calendly. If a VFS team member tries to access a bookmarked link, they will now see this message:<img width="1198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0ZJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2ead03b71e27f507daaeea75a8fb236fb9517f5/image.png" alt="image.png" />

**Comment by briandeconinck** [comment]
Comments resolved. I'll start queuing things up to be published on Platform website!

**Comment by briandeconinck** [comment]
@shiragoodman Is this good to check off the last boxes and close? I think all that's left is in #76805.

**Comment by shiragoodman** [comment]
good to close!
