### ISSUE TITLE
Create guidance for PM assistance with Survey 

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#76810]
## Purpose
As an action item from our brainstorming workshop, we want to begin involving VFS ProdMgrs as leaders in the Survey process.

Ask PMs to have team members fill out the survey in an upcoming Daily Standup.
-Matt: Charles requires them to fill out any surveys he sent in the first 10 minutes of a meeting.
   -Can we do something similar?
-the PM leading the ask seems like a strong motivator

We're thinking 5 minutes for this Survey.

## Tasks
- [x] [Document](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3033858106/Assistance+from+VFS+PMs) and Determine how best to implement this:  (Slack ask?  ToT ask? other? all of the above? How best to identify relevant PMgrs.)
- [x] create template for message
- [x] Outline guidance for how to repeat this for each survey 

## Acceptance Criteria
- [x] Plan is documented
- [x] **How-to-launch survey document is updated**
