### ISSUE TITLE
[Design] MDT Usability 1 Synthesis

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7682]
## User Story or Problem Statement
As a designer, I need to synthesize data and create a readout document for MDT Usability Study 1 so I can share more in-depth findings with my team and stakeholders.

## Tasks
- [x] Synthesize data from usability sessions
- [x] Create a readout document in GH

## Acceptance Criteria
- [x] Synthesis artifact(s) uploaded to GH and linked in this ticket
- [x] Readout document written in GH and linked in this ticket

**Comment by rileyorr** [comment]
The [research readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/research-readout.md) has been added to GH.
