### ISSUE TITLE
Bug - Discovery for Checkbox 29 Veteran does not have a bank account 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#76834]
## Issue Description
One of VBA's Regional Offices is reporting that 526 applications for some Veterans submitted through VA.gov have box 29 checked, which is a box that states that the Veteran does not have a bank account that can receive electronic payments. However, the Veterans are currently in receipt of electronic payments and when the RO called the Veterans, the Veterans claim that they did not check that box when submitting their application. I am working with the RO to obtain file numbers of specific instances, but can we investigate to determine whether this is an issue with the system or user error?

This check box is not on the online form, so wondering what is happening. One hypothesis was that if no EFT info was given, the code would check the box, but those EFT fields appear to be required.

VBA - Andrew and David  via Shannon Ford
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Investigate how the checkbox for "Veteran does not have a bank account that can receive electronic payments" is getting checked
- [ ] Investigate the specific case supplied

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
