### ISSUE TITLE
UI updates to Find a Rep

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76840]
## Background
Some small discrepancies from Staging and the design files in Figma.  Not critical for UX, but nice to have when we get a moment.

Possible to match the spacing between the See associated organization dropdown and when there is only one organization shown?
<img width="406" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68c54aabe8fa33d441bae83a1b0a8f225265ca3d/image.png" alt="image.png" />

It looks like the space between the first two form inputs (location and search area) and the one after Search area (between search area and name) are slightly different. Can we make these consistent?
<img width="424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfec909d89a15090ef708c0a7467ed891929c480/image.png" alt="image.png" />

Use the big size variation for the Search button. (This wasn’t a linked component to the VADS system in Figma so it may have been unclear. Updated in Figma as well.) See https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary#big

## Tasks
- [ ] Match the spacing between the See associated organization dropdown and when there is only one organization shown
- [ ] Update the spacing between search area and name -- it should match the spacing between the first two form inputs (location and search area) 

## Acceptance Criteria
- [ ] Staging matches the Figma design files
