### ISSUE TITLE
[Design] Debt Letters MVP - SME Interviews

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7684]
## User Story or Problem Statement
As a designer working on the debt letters mvp, I need to interview relevant project stakeholders so I can ensure that we know critical product information.

## Tasks
- [x] Create question guide
- [x] Interview 2 SMEs (Noah and Chris)
- [x] Upload interview notes and executive summaries to GH

## Acceptance Criteria
- [x] Interview notes and executive summaries in GH and linked to this ticket

**Comment by rileyorr** [comment]
I've uploaded [the interview notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/notes/05272020-noah-and-chris.md) and included an executive summary.
