### ISSUE TITLE
Flipper Demo + Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#76850]
## Description 

Brandon learned how to [remove flipper toggles from Argo environments] and would like to show the team how to do the same. We also want to match our documentation to this.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Brandon to demo to David
- [x] David to update documentation
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Moved in favor of increased SOCKS requests.

**Comment by davidpetras** [comment]
Created a [new page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3362357305/Flipper+Toggle+Tier+1+Overview) for Tier 1 Support and placed it under "Handling Access Requests".

**Comment by alyssagallion** [comment]
Added a little callout in our Advanced Tier 1 Best Practices page [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2761326593#Flipper-Toggle) that points to you page. That way folks find it in search, by sorting through our hierarchy on the left or if they are in this advanced best practices page!
