### ISSUE TITLE
Explore removal of "Epics" in Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#76859]
## User Story
As a Governance team member, I want to remove Epics from the Collaboration Cycle so that they no longer cause issues for VFS teams.

As a Governance team member, I want to emphasize the use of milestones in the Collaboration Cycle so that VFS teams can easily rely on them to find all associated tickets.

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
Governance team introduced the use of the GitHub feature "Milestone" into the Collaboration Cycle process in order to help ensure our Staging Review findings tickets can be traced back to the Collaboration Cycle initiative they were created for. VFS teams have found our user of milestone to be very useful. 

Lately, we have asked ourselves what value the "epic" still has as "epics" are a feature of ZenHub. VFS teams have struggled with ZenHub and many teams have had a difficult time finding the child tickets (aka DI/MPR feedback tickets and SR finding tickets) after a Collaboration Cycle touchpoint. 

Is it still necessary for us to convert the Collaboration Cycle Request ticket to an epic when the milestone feature meets our needs?

## Tasks
- [x] In the Ideas section of the Governance team Confluence Space, document a proposal for how we might be able to remove epics. 
- [x] Identify which artifacts are impacted. 
- [x] Propose how we might communicate this change to VFS teams.
- [x] Identify how milestones will take epics place 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have documented a plan for how we might remove epics from the Collaboration Cycle
- [ ] We have documented a plan for how milestones could be used in place of epics

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@allison0034 I want to do a quick gut check [on this plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3027861571/76859+-+Explore+removal+of+Epics+in+Collaboration+Cycle) before I spend more time on this. Is this logic sound? I feel like I'm missing something.

**Comment by rferguson13** [comment]
@allison0034 - Test! Did you get a notification for this?

**Comment by rferguson13** [comment]
@shiragoodman - Question for you: We can't get rid of epics in our Governance team processes because it's needed for Platform reporting. When would we need epics for the Governance team re: the collab cycle? For completed tickets?

**Comment by rferguson13** [comment]
@shiragoodman - I'm not sure I'll word this clearly enough, but would we need to turn the Collab Cycle ticket title into an epic in order to create the completed ticket? Or is there a way where the "completed" ticket can be added to the support epic without converting that individual ticket into an epic?

**Comment by shiragoodman** [comment]
@rferguson13 so in Zenhub, tickets are either classified as "epics" or "issues" and the only real difference between the 2 is that an epic can have a child ticket while issues cannot. Both epics and issues can be child tickets.

We would not need to turn the Collab Cycle Request ticket into an epic for the completed ticket to be created. The completed ticket can exist and have the Collab Cycle milestone and the Collab Cycle Support epic (for sprint reporting). 

The "completed" tickets are currently created automatically via Github Actions. The trigger is adding the label `cc-kickoff`, `design-intent`, `midpoint-review` and/or `staging-review` to a ticket that already has the `CC-Request` label on it. [You can find more details here.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841280559/Guide+to+Automation+to+Create+Completed+Tickets+for+Collab+Cycle+Touchpoints) Tagging @it-harrison for his input here. I don't think that the Collab Cycle Request ticket needs to be an epic for the "completed" ticket to get created, however Ian would know for certain!

**Comment by rferguson13** [comment]
@shiragoodman @allison0034 Here's the [updated page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3027861571/76859+-+Explore+removal+of+Epics+in+Collaboration+Cycle) based on our discussion on 3/26. Let me know what you think!

**Comment by shiragoodman** [comment]
@rferguson13 this looks great! Thank you for making the changes. I think we are good to close. I'll work on creating the implementation tickets this upcoming sprint for us to make the changes next sprint.

@humancompanion-usds sharing with you for your input. Let us know if you have any concerns with our proposed changes. I do not think any of these changes will impact you and/or how you report up to your leadership.
