### ISSUE TITLE
[Design] Debt Letters MVP - Call Center Employee Interviews

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7685]
## User Story or Problem Statement
As a designer working on the debt letters mvp, I need to interview call center employees so I can take user feedback into account when designing without user discovery.

## Tasks
- [x] Interview (#) call center employees
- [x] Upload interview notes and executive summaries to GH

## Acceptance Criteria
- [x] Interview notes and executive summaries in GH and linked to this ticket

**Comment by rileyorr** [comment]
I have added [Julie's notes and executive summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/notes/julie.md) and [Dawn's notes and executive summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/notes/dawn.md) to GH. 

The [executive summary and transcripts for Brent](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/notes/contact-center-representative-1.md) and the [executive summary and transcripts for Curtis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/notes/contact-center-representative-2.md) have also been added to GH.
