### ISSUE TITLE
Address gaps in Descriptive Tags for Design System components and patterns 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#76875]
## User Story
As a Governance team member, I want to ensure all tags and references for DS components, patterns and templates are included in the DraftingTemplate so that Staging Review issues tickets are published with valid references for VFS teams.

Assignee: @erinrwhite 
Peer Reviewer: @briandeconinck 

## Description
There are a few Descriptive Tags, specifically with components and patterns, that are missing reference links. We also want to verify that all of the components and patterns are listed. Right now, we are aware that the form templates are not included. When we add them, they should be added alongside the Design System Patterns and we should change the title in the DraftingTemplate to Design System Patterns/Templates.

Note: We are excluding the missing WCAG reference links from this ticket bc they are part of the WCAG 2.2 enhancements via ticket #49681.

### Notes from team at Refinement
[Need help?](https://design.va.gov/components/form/need-help) is missing

https://design.va.gov/templates/

## Impacted Artifacts
- [x] [VA.gov Experience Standards - Source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009)
- [x] Drafting templates

## Tasks
- [x] Update the DraftingTemplate to include reference links for the missing DST components
- [x] Add full list of Design System Templates to the Descriptive Tags list
- [x] Update all other supporting docs for the VA.gov Experience Standards

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All DS components have reference links within the Descriptive Tags
- [x] All Design System Templates have been included within the Descriptive Tags
- [x] The Github Upload tab of the DraftingTemplate has been updated to reference Design System Patterns/Templates 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
I identified tags that needed to be added (below). Question @briandeconinck: we don't have tags for [Templates](https://design.va.gov/templates) and [Foundation](https://design.va.gov/foundation) - and I don't think we necessarily need them. What think?

- [Content](https://design.va.gov/content-style-guide)
    - error messages> system
    - error messages> engagement
    - error messages> access
    - plain language > standards
    - specific topics > payments and debts
    - specific topics > sign in and identity verification
- [Components](https://design.va.gov/components)
    - Banner > Maintenance
    - Banner > Official Gov
    - Banner > Promo
    - Button pair needs to be renamed to button group
    - Footer - add link
    - Footer > Minimal
    - Form > Autosave
    - Form > Need help?
    - Form > Penalty notice
    - Form > Prefill
    - Form > Statement of truth
    - Header
    - Language toggle
    - List
    - Summary Box

**Comment by erinrwhite** [comment]
@briandeconinck can you doublecheck my work on the [changes to the descriptive tags on our source of truth spreadsheet](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009)? I indicated additions or edits using a yellow highlight.

**Comment by briandeconinck** [comment]
Changes to the source of truth spreadsheet look good to me, and I agree with you on Templates and Foundation

**Comment by briandeconinck** [comment]
I've also added WCAG changes from #49681 into the source of truth sheet

**Comment by erinrwhite** [comment]
Okay @briandeconinck ready for your final review. 

- [Source of truth descriptive tags](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009)
- [Drafting Template descriptive tags](https://docs.google.com/spreadsheets/d/1fmlXKxR6qnwAhleYUOdBkrRS5y-6ioenoxA_Btd8MTg/edit#gid=605465842)
- [Drafting Template DST descriptive tags](https://docs.google.com/spreadsheets/d/1hMcbGxX95gxwEtqxDpJgdDzjeGXSRQxh6iiq9enYp44/edit#gid=605465842)
- I also added instructions for [how to delete descriptive tags](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) in our documentation.


## How we know it's done:
- [ ] The `Descriptive Tags` sheet content should be the same across all three spreadsheets (sans color formatting)
- [ ] All the columns with yellow headers in the `Findings` sheets of the drafting templates should have dropdowns that accurately reflect the tags in the `Descriptive Tags` sheets (no bleedover from other tag categories).

**Comment by briandeconinck** [comment]
Everything looks good to me! I think you're good to go @erinrwhite

**Comment by erinrwhite** [comment]
Thank you for the review @briandeconinck! Can you check the peer review box? 👍🏻  I'll close the ticket.

**Comment by briandeconinck** [comment]
I got so excited checking the boxes in your comment I forgot the box in the issue! 😄

**Comment by shiragoodman** [comment]
hey @erinrwhite and @briandeconinck  - sorry, catching up on old comments. Can you share why you don't think it's necessary for us to have labels for the Templates? I recall the conversation we had a while back re: Foundation, so no need to rehash that.

**Comment by erinrwhite** [comment]
@shiragoodman @briandeconinck It'd probably be good to document this, yes? 

My reasoning is:

- **Existing coverage:** many of the parts of the template content are already covered in the components and patterns sections, which are also the more actively maintained parts of the Design System.
- **Granularity of feedback at Staging:** Typically by the time a team gets to Staging Review, we are past the point in the review where we are suggesting that teams look at a template; it's more fine-grained feedback relating to a smaller component or pattern.

@briandeconinck would love to hear your take on this too.

**Comment by briandeconinck** [comment]
My thought process more or less matched Erin on existing coverage. If I flag something for the Forms > Review template, I'm probably going to be flagging one of the components on that page --- which already has a descriptive tag. Tagging for the template doesn't seem to add much value... unless it does from a Matt / tracking perspective?

**Comment by allison0034** [comment]
Discussing with the team via [Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1710443583099079).

**Comment by shiragoodman** [comment]
thank you @allison0034 !
