### ISSUE TITLE
Implement component code checks at Staging Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#76895]
## User Story
As a Governance team member, I want to verify that VFS teams are using the component code in Storybook and not writing their own code so that the VFS team can be informed of the issue at Staging Review and they can make the fix.

As a Governance team member, I want to implement the process for how our team will identify if/when a component is hand coded so that we can begin to repeat the process consistently across all Staging Reviews.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
In ticket #75267, Governance team devised a plan for introducing component code checks at Staging Review. In this ticket, the solution will be implemented.

Also, we need to define a name for the "custom code", or "hand-coded" or "imposter" components.  What name would we like to use going forward?

## Impacted Artifacts

- [How to complete a QA review for the Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)
- [Highlight VA Web Components Bookmarklet](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2848391252/Highlight+VA+Web+Components+Bookmarklet)
- Bookmarklet
- [Discovery: opportunities for component code checks at Staging Review - 75627](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2983329825/Discovery+opportunities+for+component+code+checks+at+Staging+Review+-+75627)
- [Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)

## Tasks
- [x] Make the V1 changes to the bookmarklet, as defined in the Discovery Doc
- [x] Update the Highlight VA Web Components Bookmarklet guidance accordingly to reflect the changes to the tool, including Last Update date
- [x] Update the How to complete a QA review for the Staging review touchpoint to include steps for checking custom components, V1/V3 usage, etc., as defined in the Discovery doc
- [x] Document a post for the Collaboration Cycle Change history page detailing the changes and the start date (immediately)
- [x] Announce changes to #vfs-change-announcements once Change History post is published

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has a process in place for identifying when VFS teams are not using out-of-the-box VADS components at Staging Review
- [x] VFS teams have been notified of the change to Staging Reviews

## Team Notification
- [x] Slack post on #platform-governance-team - just forward change announcement to governance team channel
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@humancompanion-usds we plan to fiag custom-components and V1 component use under `Consistency / User encounters a component or pattern that isn't considered a best practice` at Staging Review. We are wondering if you would like us to use descriptive tags so that we can get statistics when teams use these components (since `Consistency / User encounters a component or pattern that isn't considered a best practice` encompasses more than component usage).

**Comment by shiragoodman** [comment]
@it-harrison Matt likes "imposter components" :)

I talked to Matt at our 1:1 today and he would like us to track unique instances of when the imposter components are used. We will need to implement a new descriptive tag for these scenarios. Let me know if you'd like to discuss.

**Comment by shiragoodman** [comment]
@erinrwhite can help with the descriptive tag

**Comment by shiragoodman** [comment]
per Gov team refinement on 3/12, we want to ensure we communicate clearly and have consistent messaging around the new term, "imposter component." How might we ensure our change history post, change announcements, wording in the SR ticket and language in the SR meeting are all consistent?

**Comment by shiragoodman** [comment]
@rferguson13 FYI^

**Comment by erinrwhite** [comment]
Descriptive tag ideas:
- straightforward: `impostor-component`
- matching the format of tags for other design system components: `va-impostor`

Which [column in the drafting template](https://docs.google.com/spreadsheets/d/1fmlXKxR6qnwAhleYUOdBkrRS5y-6ioenoxA_Btd8MTg/edit?usp=drive_link) should the tag live in? My thought was to put it in the Design System Component column, but then we would not be able to select another item from that same dropdown, i.e. the actual design system component that is supposed to be there. We might consider adding a checkbox or yes/no for "Is this an impostor component?"

**Comment by it-harrison** [comment]
This will carryover due to need to update the bookmarklet in connection with the ongoing uswds v3 default switch in vetswebsite and need to hash out our strategy for adding descriptive tags to track violations.

**Comment by it-harrison** [comment]
new bookmarklet script (encoded): 
`javascript:%20(function%20()%20%7B%0A%20%20!(function%20()%20%7B%0A%20%20%20%20let%20e%20%3D%20document.getElementById(%27bookmarklet-component-highlight%27)%3B%0A%20%20%20%20if%20(e)%20%7B%0A%20%20%20%20%20%20e.outerHTML%20%3D%20%27%27%3B%0A%20%20%20%20%7D%0A%20%20%20%20e%20%3D%20document.createElement(%27style%27)%3B%0A%20%20%20%20e.id%20%3D%20%27bookmarklet-component-highlight%27%3B%0A%20%20%20%20e.innerText%20%3D%20%27%27%3B%0A%20%20%20%20%5B%0A%20%20%20%20%20%20%27va-accordion%27%2C%0A%20%20%20%20%20%20%27va-additional-info%27%2C%0A%20%20%20%20%20%20%27va-alert%27%2C%0A%20%20%20%20%20%20%27va-alert-expandable%27%2C%0A%20%20%20%20%20%20%27va-back-to-top%27%2C%0A%20%20%20%20%20%20%27va-banner%27%2C%0A%20%20%20%20%20%20%27va-official-gov-banner%27%2C%0A%20%20%20%20%20%20%27va-promo-banner%27%2C%0A%20%20%20%20%20%20%27va-breadcrumbs%27%2C%0A%20%20%20%20%20%20%27va-button%27%2C%0A%20%20%20%20%20%20%27va-button-pair%27%2C%0A%20%20%20%20%20%20%27va-card%27%2C%0A%20%20%20%20%20%20%27va-checkbox%27%2C%0A%20%20%20%20%20%20%27va-checkbox-group%27%2C%0A%20%20%20%20%20%20%27va-crisis-line-modal%27%2C%0A%20%20%20%20%20%20%27va-date%27%2C%0A%20%20%20%20%20%20%27va-featured-content%27%2C%0A%20%20%20%20%20%20%27va-file-input%27%2C%0A%20%20%20%20%20%20%27va-link%27%2C%0A%20%20%20%20%20%20%27va-loading-indicator%27%2C%0A%20%20%20%20%20%20%27va-memorable-date%27%2C%0A%20%20%20%20%20%20%27va-minimal-header%27%2C%0A%20%20%20%20%20%20%27va-modal%27%2C%0A%20%20%20%20%20%20%27va-need-help%27%2C%0A%20%20%20%20%20%20%27va-notification%27%2C%0A%20%20%20%20%20%20%27va-number-input%27%2C%0A%20%20%20%20%20%20%27va-omb-info%27%2C%0A%20%20%20%20%20%20%27va-on-this-page%27%2C%0A%20%20%20%20%20%20%27va-pagination%27%2C%0A%20%20%20%20%20%20%27va-privacy-agreement%27%2C%0A%20%20%20%20%20%20%27va-process-list%27%2C%0A%20%20%20%20%20%20%27va-progress-bar%27%2C%0A%20%20%20%20%20%20%27va-segmented-progress-bar%27%2C%0A%20%20%20%20%20%20%27va-radio%27%2C%0A%20%20%20%20%20%20%27va-search-input%27%2C%0A%20%20%20%20%20%20%27va-select%27%2C%0A%20%20%20%20%20%20%27va-sidenav%27%2C%0A%20%20%20%20%20%20%27va-summary-box%27%2C%0A%20%20%20%20%20%20%27va-table%27%2C%0A%20%20%20%20%20%20%27va-telephone%27%2C%0A%20%20%20%20%20%20%27va-text-input%27%2C%0A%20%20%20%20%20%20%27va-textarea%27%2C%0A%20%20%20%20%20%20%27va-statement-of-truth%27%2C%0A%20%20%20%20%5D.forEach(a%20%3D%3E%20%7B%0A%20%20%20%20%20%20const%20v3%20%3D%20%60%24%7Ba%7D%3Anot(%5Buswds%3D%22false%22%5D)%20%7B%20outline%3A%20dotted%205px%20orange%3B%20%7D%60%3B%0A%20%20%20%20%20%20const%20v3Label%20%3D%20%60%24%7Ba%7D%3Anot(%5Buswds%3D%22false%22%5D)%3Aafter%20%7B%20content%3A%20%22%24%7Ba%7D%20v3%22%3B%20color%3A%20%23fff%3B%20background-color%3A%20orange%3B%20padding%3A%203px%3B%7D%60%3B%0A%20%20%20%20%20%20const%20v1%20%3D%20%60%24%7Ba%7D%5Buswds%3D%22false%22%5D%20%7B%20outline%3A%20dotted%205px%20darkred%3B%20%7D%60%3B%0A%20%20%20%20%20%20const%20v1Label%20%3D%20%60%24%7Ba%7D%5Buswds%3D%22false%22%5D%3Aafter%20%7B%20content%3A%20%22%24%7Ba%7D%20v1%22%3B%20color%3A%20%23fff%3B%20background-color%3A%20darkred%3B%20padding%3A%203px%3B%7D%60%3B%0A%20%20%20%20%20%20e.innerText%20%2B%3D%20%60%24%7Bv3%7D%20%24%7Bv3Label%7D%20%24%7Bv1%7D%20%24%7Bv1Label%7D%20%60%3B%0A%20%20%20%20%7D)%2C%0A%20%20%20%20%20%20document.head.appendChild(e)%3B%0A%20%20%7D)()%3B%0A%7D)()%3B%0A`

not encoded:
```
javascript: (function () {
  !(function () {
    let e = document.getElementById('bookmarklet-component-highlight');
    if (e) {
      e.outerHTML = '';
    }
    e = document.createElement('style');
    e.id = 'bookmarklet-component-highlight';
    e.innerText = '';
    [
      'va-accordion',
      'va-additional-info',
      'va-alert',
      'va-alert-expandable',
      'va-back-to-top',
      'va-banner',
      'va-official-gov-banner',
      'va-promo-banner',
      'va-breadcrumbs',
      'va-button',
      'va-button-pair',
      'va-card',
      'va-checkbox',
      'va-checkbox-group',
      'va-crisis-line-modal',
      'va-date',
      'va-featured-content',
      'va-file-input',
      'va-link',
      'va-loading-indicator',
      'va-memorable-date',
      'va-minimal-header',
      'va-modal',
      'va-need-help',
      'va-notification',
      'va-number-input',
      'va-omb-info',
      'va-on-this-page',
      'va-pagination',
      'va-privacy-agreement',
      'va-process-list',
      'va-progress-bar',
      'va-segmented-progress-bar',
      'va-radio',
      'va-search-input',
      'va-select',
      'va-sidenav',
      'va-summary-box',
      'va-table',
      'va-telephone',
      'va-text-input',
      'va-textarea',
      'va-statement-of-truth',
    ].forEach(a => {
      const v3 = `${a}:not([uswds="false"]) { outline: dotted 5px orange; }`;
      const v3Label = `${a}:not([uswds="false"]):after { content: "${a} v3"; color: #fff; background-color: orange; padding: 3px;}`;
      const v1 = `${a}[uswds="false"] { outline: dotted 5px darkred; }`;
      const v1Label = `${a}[uswds="false"]:after { content: "${a} v1"; color: #fff; background-color: darkred; padding: 3px;}`;
      e.innerText += `${v3} ${v3Label} ${v1} ${v1Label} `;
    }),
      document.head.appendChild(e);
  })();
})();
```

**Comment by it-harrison** [comment]
Change log:

March X, 2024

* **Use of custom-coded components and V1 Design System web components may be flagged as violations at Staging Reviews* A custom-coded component that emulates the look and function of a Design System web component should be replaced with the Design System web component absent a legitimate technical reason why the Design System web component is inadequate. In addition, the V1 versions of Design System web components should not be used if there exists a V3 version that can meet the product's needs.

**Comment by shiragoodman** [comment]
@it-harrison re: the change log, I made some small tweaks to what you had written.

- **Effective immediately, use of imposter components and V1 Design System web components will be flagged as VA.gov Experience Standards violations at Collaboration Cycle Staging Reviews.**  An imposter component is one that emulates the look and function of a Design System web component and should be replaced with the Design System web component absent a legitimate technical reason why the Design System web component is inadequate. In addition, the V1 versions of Design System web components should not be used if there exists a V3 version that can meet the product's needs.

We also need to write a change announcement for the #vfs-change-announcements channel following[ this format. ](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2290352129/Slack+Change+Announcement+format)

I plan to ask Matt at our 1:1 today if he wants us to expand on the V1 messaging at all since the V1 components will be retired in May.

**Comment by it-harrison** [comment]
@shiragoodman @briandeconinck updated announcements:

tweaked change log:
* **Effective immediately, use of imposter components and V1 Design System web components will be flagged as VA.gov Experience Standards violations at Collaboration Cycle Staging Reviews.** An imposter component is one that emulates the look and function of a Design System web component and should be replaced with the Design System web component absent a legitimate technical reason why the Design System web component is inadequate. In addition, the V1 versions of most Design System web components should not be used if there exists a V3 version that can meet the product's needs. 

---

change announcement for #vfs-change-announcements

**Attention**: VFS teams

**Imposter Components and V1 Design System Components will be flagged at Staging Reviews**

Starting **March 18th, 2024**, Governance Team will flag as violations of the VA.gov Experience Standards any imposter components in VFS products. An imposter component is one that emulates the look and function of a Design System web component. In addition, Governance Team will flag the use of most V1 Design System components.

**Impact**: VFS teams should replace imposter components with the corresponding Design System web component absent a legitimate technical reason why the Design System web component is inadequate. V1 components should be replaced with the V3 counterpart if it exists.

**Documentation**: <link_to_change_history_post>

**Questions**: Reach out to the Governance team by filing a support request on #vfs-platform-support

**Comment by shiragoodman** [comment]
@it-harrison this looks good! I have 1 small suggestion to the change log - can you remove "most" and instead say, "In addition, the V1 versions of Design System web components, with a few exceptions, should not be used if there exists a V3 version that can meet the product's needs." Please make the same change to the Slack announcement too.

**Comment by shiragoodman** [comment]
@it-harrison is this ready to be closed? I know you had shared you needed to make some small changes to the bookmarklet. I'm not sure if that's complete.

**Comment by it-harrison** [comment]
@shiragoodman yes, closing now. Just wanted to give @briandeconinck a chance to weigh in if he found any issues.
