### ISSUE TITLE
Copy of DORA Metric Research and Baseline Calculation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#76906]
## Description 
This ticket will house the task of researching and developing a baseline calculation for Time to Restore Service. See [2023_final_report_sodr (2).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVNEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8136a5cb7d5203092bf7f58dfc66f268abb58aab/2023_final_report_sodr%20%282%29.pdf) For the guidelines we will be following. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks to Complete
_Steps to reach definition of done._ 
- [x] Document definitions of the metrics we are analyzing
- [x] Document the steps to pull the data or get to the finalized information
- [x] Identify and document challenges with pulling this data
- [x] Source data 
- [x] Calculate the metrics 
- [x] Present the findings both in this document and in a spreadsheet format
--- 

## Resources & Additional Info 

- [DORA Metrics Overview - Platform Support Team](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2946236529/DORA+Metrics+-+Platform+Support+Team)
- [OOB Deploys Used to Determine Time to Restore Service](https://docs.google.com/spreadsheets/d/1ubH_7G6-8X_nSGMDhGedjfVORs3mI8lhgEF6uyxHkUo/edit#gid=1258212134) 

---

**Comment by alyssagallion** [comment]
Work completed. See DORA Metrics Overview under Resources and Additional Information for more info.
