### ISSUE TITLE
[DA] 10-10CG - Performance Monitoring: Review existing monitors and update

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76902]
## Background
On Thursday afternoon, the Identity team reported an outage for authenticated Veterans due to a Vendor issue.  This appears on Datadog to be impacting the 10-10CG.  There were 503/504 errors, which may have hindered application progress and/or submissions.

We need to visit the existing monitors and alerts set for the 10-10CG form, and adjust or add as needed.  We should have been alerted to this occurrence, yet we did not receive any alerts.

>Joe Niquette
>:rotating_light:We are tracking an authentication outage for verified users on all externally facing VA systems. The outage is with a downstream service provider. As we have more updates we will announce them here :rotating_light:

## Tasks
- [ ] Review existing monitors for CG form
- [ ] Determine if any need to be adjusted
- [ ] Determine if any need to be added (what could we have had that would have alerted us to this issue?)
- [ ] Add/Adjust monitors and alerts
- [ ] Review with PM

## Acceptance Criteria
- The 10-10CG monitors and/or alerts are up-to-date and should capture any error patterns and anomalies.

**Comment by luis-simauchi** [comment]
reviewed with @hdjustice , the current monitor is only looking at form submission create actions instead of generic errors from the controller. We will  create another monitor to look at NON create errors as well.

**Comment by luis-simauchi** [comment]
new alert created
