### ISSUE TITLE
Document OCTO assistance w/ Satisfaction Survey participation

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#76975]
## Purpose
As an [action item ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2961604609/Brainstorming+session+improving+Survey+participation#Question-1%3A-How-might-we-make-it-easier-for-desired-personas-to-access%2C-absorb%2C-and-act-on-all-forms-of-feedback-that-Platform-collects%3F)from our brainstorming workshop, we'd like to solicit assistance from OCTO to direct their teams to take the survey.

Look to OCTO/Leadership for more support w/ Survey participation:
-now that capturing and acting on Feedback for Platforms is an Objective from Charles Worthington, we can look to OCTO or more support
-Maybe reach out via Matt to OCTO? We could give him a status report

## Tasks
- [x] Determine how to go about it:  (reach out to OCTO PO's directly regarding ? reach out via Matt? Might we need a list of current PO's? Create a messaging template?)
   - When during survey?
   - where to post?
   - what to say?
- [x] [Document approach](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3027468348/Status+Report+Assistance+from+OCTO-DE) within the Survey Launch document

## Acceptance Criteria
- [x] New approach is documented
