### ISSUE TITLE
Posting Platform Satisfaction Survey participation results in Slack

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#76974]
## Purpose
As an [action item ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2961604609/Brainstorming+session+improving+Survey+participation#Question-1%3A-How-might-we-make-it-easier-for-desired-personas-to-access%2C-absorb%2C-and-act-on-all-forms-of-feedback-that-Platform-collects%3F)from our brainstorming workshop, we'd like to post ongoing participation results by role.

Add a bit of gamification
-Should we share out participation results? (% of users?) (based on role)
-and makes it clearer to leads which group need prompting
-Could also help practice leads or CoP leads see if their group was not representing themselves well, allowing for a prompt
-Matt suggests showing the data, pitting groups vs groups. Post that in a Slack message and copy Kevin, Bill, etc.

## Tasks
- [x] Determine how to go about it: 
   - which group should we break metrics down by?
   - frequency 
   - where to post
- [x] Document approach in the page supporting [How to Launch Survey](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Quarterly+Platform+Services+Satisfaction+Survey)

## Acceptance Criteria
- [x] New approach is documented
