### ISSUE TITLE
[CST] Documents filed section

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#76991]
## Value Statement
**_As a_** veteran with a disability claim
**_I want to_** be able to see the documents that are associated with my claim
**_So that_** I have a clear sense of which documents are being used to determine my disability rating

---
## Background Context

As part of the V2 release, we want to update our the Documents Filed section of the CST Files tab to provide a more user friendly experience and better information for veterans.

## Design

**Figma links**
- [Documents Filed section within the Files tab](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-483&mode=design&t=CVUCP1U5gV5JVhSg-0)
- [Detailed spec of Documents Filed list items](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=966-7298&mode=design&t=CVUCP1U5gV5JVhSg-4)
- [Pagination](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=684-17672&mode=design&t=CVUCP1U5gV5JVhSg-0) (should follow same logic as Recent Activity section)

<img width="702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDJJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afa01ba63a39e4e0a007c3008def8fc4d00a9aa6/Screenshot%202024-02-23%20at%203.39.50%E2%80%AFPM.png" alt="Screenshot 2024-02-23 at 3.39.50 PM.png" />

## Engineering 
Tracked Item fields:
- FileName: trackedItems.documents.originalFileName
- Request Type: trackedItems.displayName
- Document type: trackedItems.documents.documentTypeLabel
- Received on date: trackedItems.documents.uploadDate
- Reviewed by date: trackedItems.receivedDate
- When status is INITIAL_REVIEW_COMPLETE || ACCEPTED then we show the reviewed by date
- When status is SUBMITTED_AWAITING_REVIEW then we show the text 'Pending review' 
- When the tracked item has a closedDate then we show the text 'No longer needed'
- Add logic so that if for some reason there is no trackedItems.documents.uploadDate then we use the trackedItems.date instead so that there is always a date

Additional evidence fields:
- FileName: supportingDocuments.originalFileName
- Request Type: 'Additional Evidence'
- Document type: supportingDocuments.documentTypeLabel
- Received on date: supportingDocuments.uploadDate
- Reviewed by date: there isnt one so this field will not be displayed

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] Design work to account for multiple files
- [x] Design work to account for various statuses
- [x] When there is no file name or date we show 'File name unknown' and we dont show the received on date

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [x] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with product
- [x] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria

- [x] There is a header that clearly indicates this section as distinct from other sections.
- [x] Requests are sorted by reverse chronological order (newest to oldest) by "Received on" date 
- [x] Should be behind feature flag cst_use_claim_details_v2
- [x] Pagination is included and the list should not require excessive scrolling, 10 items max.
- [x] Pagination is hidden if there's 10 items or less.
- [x] The Pagination design should be visually consistent with other pagination design approaches found elsewhere in CST
- [x] Users can see multiple files nested under the same request.
- [x] Users can see the date that the file is reviewed by VA
- [x] Users can see when a file is received.

**Comment by HeatherWidmont** [comment]
@pmclaren19 working on writing tests for all the logic today

**Comment by pmclaren19** [comment]
Merged in pr and verified in Staging. @skylerschain @jacobworrell please preform design qa and validation. 
You can use user vets.gov.user+30@gmail.com to test pagination for the Documents filed specifically this claim https://staging.va.gov/track-claims/your-claims/255920/files.
--


<br class="Apple-interchange-newline">

**Comment by HeatherWidmont** [comment]
@skylerschain to validate this today

**Comment by skylerschain** [comment]
LGTM 👍
