### ISSUE TITLE
[CST] Remove Details tab

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#76993]
## Background Context

As part of the V2 Claim Detail redesigns, the Details tab is no longer needed – all the information it provides is provided elsewhere in the tool. We need to remove it.

## Design

**Figma links**
- [Tabs + Core Screens](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-483&mode=design&t=CVUCP1U5gV5JVhSg-0)

**Screenshot**

<img width="654" alt="Screenshot 2024-02-23 at 4 11 11 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/cf5d6940-1f49-4aaa-9931-8a365d1b5c61">

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Remove Detail tab and its contents from the tab list for a claim
- [ ] This is behind the feature flag `cst_use_claim_details_v2`
- [ ] When feature flag `cst_use_claim_details_v2` is disabled, the Details tab still shows

**Comment by HeatherWidmont** [comment]
@skylerschain & @jacobworrell to validate
