### ISSUE TITLE
(Footer Ticket 76162)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#76992]
## Issue Description
Reference this GitHub ticket

---
## Tasks
- [ ] Review GitHub ticket
- [ ] Make changes to the page
- [ ] Confirm edits/changes with SME
- [ ] Prepare page for deployment
- [ ] Leave comment on Github ticket once page has been deployed

## Acceptance Criteria
- [ ] Changes have been made and reviewed by SME
- [ ] Page has been deployed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/76992?planning-poker) with Zenhub @laucon

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/76992?planning-poker) with Zenhub @BSmolensky

**Comment by taylojill** [comment]
After reading the Slack threads and messages, here's what I did:

1. I added a step (4) after step 3; "Add your new app to the vets-api statsd middleware configuration so it will be recognized and the source_app tag will be usable in Datadog."
2. I asked the following questions of the SME:
    - Is this the right location? 
    - Are there more details that should be added (links, screenshots, sub-steps, etc)?

I sent a link to the page in draft space and a pdf copy.

cc @jknipes

**Comment by taylojill** [comment]
SME approved of location and content, but he also said he had added an additional comment, which I could not find. I sent a follow-up question requesting help in finding/adding his comment.

**Comment by taylojill** [comment]
The comment was hidden under another comment! SME pointed me to location. Link added as requested. Page will be checked for launch blocking issues and prepared for deployment 5/14/2024.

**Comment by jknipes** [comment]
Work is complete, AC met, moving to _done_
