### ISSUE TITLE
[DevOps] Discovery on automating AWS IAM Key Rotation Process

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77015]
## User Story
As a DevOps engineer, I want to automate AWS IAM key rotation and its surrounding operations (notifications, monitoring, etc) to improve security, reduce toil, and reduce the risk of human error.

## Objective
The goal of this discovery is to explore and outline a strategy for automating the rotation of AWS IAM keys, currently a manual process as described in our [project documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/rotating-iam-keys.md).

## Tasks
- [ ] Determine and document hard requirements for this process; what is and is not achievable?
- [x] Determine blockers, if any.
- [x] Formulate a structure (see [below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77015#issuecomment-1964286954) for possible structure).
- [x] Determine where GHA workflows will be housed.
- [ ] Verify access levels required for GHA interaction with AWS; do we need to add additional IAM roles/policies to encompass these changes?
- [x] Determine whether Datadog AWS integration can be updated via API. Might need Terraform. If so, where does this go?
- [x] Consider limiting initial implementation to `CMS-service-account-1` to avoid entangling external teams.
- [x] Consider initial integrations with Slack so we have visible reporting when this process is occurring.
- [x] What documentation needs to be written?
- [x] What communication within the team needs to take place?
- [x] What communication with other teams needs to take place?
- [x] Is it worth implementing a "panic button" in the form of a workflow to reactivate deactivated tokens?

## Acceptance Criteria
- [ ] Per-task findings documented in this thread.
- [ ] Followup ticket(s) opened for implementation, if value permits 🙂

**Comment by ndouglas** [comment]
## Possible Structure
- GHA workflow that runs every 55 days:
  - jobs:
    - generate `CMS-service-account-1` access key
    - generate `CMS-service-account-2` access key
    - store `CMS-service-account-1` access key in Secrets Manager
    - store `CMS-service-account-2` access key in Secrets Manager
    - post a Slack message to `#vetext-engineering` re: `CMS-service-account-2` access key update
      - get input on tags, message content
  - Where's the best place for this?
- GHA workflow that runs every day:
  - jobs:
    - deactivate >=63-day-old access keys for `CMS-service-account-1`, `CMS-service-account-2`
    - delete >= 65-day-old access keys for `CMS-service-account-1`, `CMS-service-account-2`
    - check the last-used date for access keys >= 58 days old
      - if within the last 24 hours, post a message to Slack with the name of the account and (optionally) the access key ID
        - get input on channel, tags, message content
  - Probably house this with previous workflow.
- GHA workflow that runs every day:
  - jobs:
    - update Datadog with `CMS-service-account-2` access key
      - I'd have to play around with this, and it's a little extra complicated since I don't have tevi datadog access yet. 
      - Worst case there's still a manual step involved.
      - Not sure where to house this. Probably figure that out as I continue onboarding.
- GHA workflow that runs every day (in each of [CHIP](https://github.com/department-of-veterans-affairs/chip/), [LoRota](https://github.com/department-of-veterans-affairs/lorota), [vista-api](https://github.com/department-of-veterans-affairs/octo-vista-api-x)):
  - jobs:
    - update GitHub repository secret with `CMS-service-account-1` key

**Comment by ndouglas** [comment]
## Per-Task Notes

### Determine and document hard requirements for this process; what is and is not achievable?

Per VAEC policy, AWS IAM Access Keys should be rotated every 60 days. Warnings are sent out when keys are greater than 90 days old.

60 days doesn't appear to be a hard limit, so the numbers I've outlined above should be workable. If there is pressure to fit _within_ 60 days, they should be adjustable easily.

There's an existing DevOps repo at https://github.com/department-of-veterans-affairs/checkin-devops/ that I can use to house this stuff, I think.

### Determine blockers, if any

Technically, my threads [[1](https://dsva.slack.com/archives/C022AC2STBM/p1708955000879269)] [[2](https://dsva.slack.com/archives/C051S52N1C6/p1708959592347069)] in Slack attracted some broader engineer interest (at least to the point of a few emojis), but no objections were raised. 

Institutionally, none are apparent; Stephen Barrs (VA enablement team) gave my first thread a ❤️, so I'll count that as at least a qualified endorsement of the idea.

Unfortunately, access to the service accounts is restricted. I'm currently looking into getting access both for myself [1] and for a new service account [2].

[1] https://github.com/department-of-veterans-affairs/va.gov-team/issues/75443
[2] https://dsva.slack.com/archives/C02G6AB3ZRS/p1709055344835309

### Determine where GHA workflows will be housed



- Verify access levels required for GHA interaction with AWS; do we need to add additional IAM roles/policies to encompass these changes?
- Determine whether Datadog AWS integration can be updated via API. Might need Terraform. If so, where does this go?
- Consider limiting initial implementation to `CMS-service-account-1` to avoid entangling external teams.
- Consider initial integrations with Slack so we have visible reporting when this process is occurring.
- What documentation needs to be written?
- What communication within the team needs to take place?
- What communication with other teams needs to take place?
- Is it worth implementing a "panic button" in the form of a workflow to reactivate deactivated tokens?

**Comment by ndouglas** [comment]
I went as far as I could on this, and work moving forward will be a part of the AWS account migration process.
