### ISSUE TITLE
[FE] Placeholder for anything that was missed because of changing content/design

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#77013]
## Tasks
- [x] Review Figma wireframes to identify anything we missed
- [x] Fixed missing things
- [x] small change to the text that's bolded (in body text under the h1) for both multi and single facilities review pages:
    - [Wireframe for multi](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=1609-6521&mode=design&t=gNL52GxOpmUEyJHp-0)
    - [Wireframe for single](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=1585-1543&mode=design&t=4LUloQ0dhzbiP3ne-0)
- [x] Update text on validate page. We have `File a travel reimbursement claim if you’re eligible for health care travel reimbursement. First, we need your last name and date of birth to make sure it’s you.` Should be `First, we need your last name and date of birth to make sure it’s you.`
    - [wireframe](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=507-4579&mode=design&t=f4NGwTOQqcjPybvp-0)
- [x] Remove secondary action link from intro page and remove open in blank window from travel reimbursement eligibility link
    - [wireframe](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=642-3804&mode=design&t=f4NGwTOQqcjPybvp-0) 
- [x] Add `What you're claiming` to review page
    - [wireframe](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=1585-1543&mode=design&t=f4NGwTOQqcjPybvp-0)
- [x] Fix issue where `45MR` is getting appended to yes/no events on non day-of check-in pages including travel
- [x] Clicking `no` on travel question pages does not route to the proper page. Need to pass a "No" function
- [x] Add facilityType param to get session and other API requests for travel-claim only `facilityType=oh`
- ~Address a11y ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/77000~

**Comment by loripusey** [comment]
@brianseek @benbrasso-agile6 I added this ticket because I think that some of the content has shifted during the development; thought we needed a ticket to check what we have against the final wireframes to ensure we captured everything

**Comment by lee-delarm6** [comment]
Closing based on conversation with @brianseek and @benbrasso-agile6 , we've added a overarching summary title to the checkbox group which is read. This should cover the necessary description of the checkboxes

**Comment by brianseek** [comment]
Lets keep this open as an audit on the designs. There are still in-flight changes, like the changes to the review page and the intro page also has unaddressed updates

**Comment by brianseek** [comment]
@benbrasso-agile6 / @cgednalske / @zach-park This isn't merged yet. But if you want to get a jump start on validation, here are the screenshots[travel-app-screens.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVhpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01dbb673343dbe1f514c1b858680642994e9b588/travel-app-screens.zip)

if you want to see anything local the branch is `check-in/77013/remove-eyebrow`

**Comment by loripusey** [comment]
I compared the screenshots to the content in Figma, looks good to me. Are we ready to fully test in a local env yet @brianseek ?

**Comment by brianseek** [comment]
@loripusey sure! This isn't merged yet, but you can use this branch `check-in/77013/remove-eyebrow` and there are details in the readme here: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in#mock-uuids

and more here: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/travel-claim#how-to-run-locally

**Comment by loripusey** [comment]
I will give it a whirl, though if I fail, I may wait till Monday so it doesn't wreck my weekend :)

**Comment by loripusey** [comment]
Otherwise I may spend all day fretting and then be grumpy over the weekend

**Comment by brianseek** [comment]
@loripusey feel free to send a zoom for co-working if it gives you any trouble

**Comment by benbrasso-agile6** [comment]
![41foWPIDfSL _AC_UF1000,1000_QL80_](https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/ec6dc86c-6612-4c6b-80e1-0534fe982f42)

**Comment by brianseek** [comment]
This is merged and ready to be validated

**Comment by loripusey** [comment]
Validated against the TestRail test cases; @benbrasso-agile6 do you want to validate against the new Figma content with recent changes? I validated the zip file of screenshots against Figma last week but not sure if that accounted for recent changes

**Comment by benbrasso-agile6** [comment]
Yeah, I'll take a look at the zip

**Comment by benbrasso-agile6** [comment]
Nice work. That was a lot!

Noticed a couple small things: 
- On the address page, are we able to do a line break after street address (i.e., similar format in Demo questions)? 
- On the review page, on the validation error, can we bold the "By submitting..." sentence? I believe we're supposed to. 
- On the review page, are we able to do a line break after street address (i.e., similar format in Demo questions)?

**Comment by brianseek** [comment]
For the address formatting, there is a thread about that in slack that Lee started somewhere. In short, no not really. We only have a single text field for the address, so we have no idea where the street begins and ends.

On the error, the component takes care of all that and in this scenario it doesn't bold: https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default#forms-pattern-single-error

I'm not really sure the difference or what that means but the component is doing what is doing on purpose.

**Comment by brianseek** [comment]
looks like there was never a resolution on it: https://dsva.slack.com/archives/C02G6AB3ZRS/p1709585291986289

**Comment by brianseek** [comment]
it was kind of an all the breaks or none of them option

**Comment by benbrasso-agile6** [comment]
Consider these resolved. I'll update couple these in Figma. Thanks @cgednalske FYI, since you were a part of the address break convo. No action needed here.

**Comment by benbrasso-agile6** [comment]
Took care of these edits in Figma so we all stay synced up
