### ISSUE TITLE
Team Ideation session

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#77026]
## Task Description
Plan and facilitate an ideation session to generate ideas for the new scheduling flow. 

## Notes and References
-

## Acceptance Criteria
- [x] [Figjam board ](https://www.figma.com/file/OD3pg7CQSIjjlg3Ev6efyG/Scheduling-Ideation-workshop?type=whiteboard&node-id=0%3A1&t=DMG2cjVeyn2oey7r-1)
- [x] [Outline of session (for facilitator)](https://docs.google.com/document/d/1uch2Eyh9OMhuJ_QFS_hll44NK-XmdqmHbfIJBvKQsOM/edit?usp=sharing)
- [x] Invite team members (for week of March 4th)
- [x] Run session
- [x] Review ideas with Peter and Ciera after 

## Deliverables
- 

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
