### ISSUE TITLE
Add copy to Direct Deposit page that alerts user about single bank account req

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#77020]
## Issue Description

Related Slack thread: https://dsva.slack.com/archives/C06E83RNLQM/p1708959156208089 

- VA is in the process of telling Veterans about a change for those who currently have more than one bank account listed for disability compensation, pension, and education benefit payments
- The same account needs to be used for all of those benefits.
- This is described on VA.gov's Change your [VA Direct Deposit change](https://www.va.gov/change-direct-deposit/)
- "By April 20, 2024, you must have a single bank account for all VA benefit payments"

Helpful artifacts:

- Relevant screenshots in [this CH33 Migration CorpDB mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707938676024/48a9e34150b8a3058c8709b241373cb9515afee6?wid=0-1708092479343) (the bulk of that mural is related to changes needed for the VA.gov profile page) and in the [Benefits Portfolio SharePoint](https://login.microsoftonline.com/e95f1b23-abaf-45ee-821d-b7ab251ab3bf/oauth2/authorize?client%5Fid=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&response%5Fmode=form%5Fpost&response%5Ftype=code%20id%5Ftoken&resource=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&scope=openid&nonce=10E6A621777B4508E360D7213658B9508684149AFE1AF7F9%2D4484EB94DCA999625E8A3E9BE1B7C726CDC54610103EFA25ED93FDD491CE0CE7&redirect%5Furi=https%3A%2F%2Fdvagov%2Esharepoint%2Ecom%2F%5Fforms%2Fdefault%2Easpx&state=OD0w&claims=%7B%22id%5Ftoken%22%3A%7B%22xms%5Fcc%22%3A%7B%22values%22%3A%5B%22CP1%22%5D%7D%7D%7D&wsucxt=1&cobrandid=11bd8083%2D87e0%2D41b5%2Dbb78%2D0bc43c8a8e8a&client%2Drequest%2Did=18820fa1%2Da065%2D4000%2De987%2Df97c4a74a82c)

## User Stories
As a claimant,
I need to know that the direct deposit info I provide won't be used until after a decision is made on my claim, and only if an award is made.

As a claimant,
I need to know that if I already receive education payments, those will use the direct deposit info I list in this pension claim if and when I receive a pension award.  (Better wording needed!)

---
## Tasks
- [x] Design task to craft language based on what is in the [526 screenshots](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707938676024/48a9e34150b8a3058c8709b241373cb9515afee6?wid=0-1708092479343&sender=u9d01ee38af217e4877e75660) and what on the [Change your deposit info](https://www.va.gov/change-direct-deposit/) page.
- [x] Get sign off from CAIA/Katherine
- [ ] Incorporate new copy onto the existing Direct Deposit page on online Pension form
- [ ] Provide design/copy additions to engineering team

**Comment by gmaciolek** [comment]
Is the main point of the message to tell the user that they should check their VA.gov profile to make sure that they have the same account listed for all benefits? Or will we use the bank account they specify in their pension claim for all of their other benefit payments?

**Comment by gmaciolek** [comment]
Connected with Julie Strothman on this and she suggested I reach out to Danielle Theiry and Randi Hecht on the content. Randi had me make a CAIA ticket. We'll work with Katherine on this and she'll run things by Danielle to make sure the messaging is accurate: 

- [Figma link to draft design](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2146%3A2284&mode=design&t=z7ofhG2z9Fagu35q-1)
- [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77464)

**Comment by gmaciolek** [comment]
Updates:
Progress on this is dependent on CAIA ([ticket 77464](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77464))
- Met with CAIA on Wednesday 3/6 to kick off our collaboration on this work
- Katherine will work on this, but her time this week is allocated to other high-priority projects
- I'm waiting on an update from CAIA re: when Katherine can have the copy finalized in the designs
