### ISSUE TITLE
UX Scheduling ideation 

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#77039]
## Task Description
Generate sketches and lo-fi flows of possible scheduling solutions

## Notes and References
-

## Acceptance Criteria
- [x] Create a figma space to capture ideas. 
- [x] Generate flows that aim to solve the various problem statements

## Deliverables
- [Figma file](https://www.figma.com/file/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-ideation?type=design&node-id=0%3A1&mode=design&t=FhG4AnjnXFkUQZbY-1)

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by melissa-lefevre** [comment]
We have a design direction for the choose a location page. Closing ticket as I will be working on the specs and testing plan.
