### ISSUE TITLE
[CST Bug] Add Files Upload modal "icon button" not closing modal when clicked

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#77046]
## Value Statement
As a user of the CST, 
I want to be able to upload files and when I see the file upload status modal have the ability to close it
So that I can continue with my work.

---
## Background Context
@skylerschain found when uploading a file that he was unable to close the modal when selecting the 'x' icon button.
noted in comments on this ticket https://github.com/department-of-veterans-affairs/vets-website/pull/28131

<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNStOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3df02f9dde541ffac2563ff46200b9debef468b9/Screenshot%202024-02-22%20at%2012.27.56%E2%80%AFPM.png" alt="Screenshot 2024-02-22 at 12.27.56 PM.png" />

### Bug
- Go to the files tab in the CST
- Add a file for Additional Evidence and submit the file
- An upload status modal will appear for a few seconds and if you click the 'x' icon button to close the modal it doesnt work

## Outcome, Success Measure, KPI(S), and Tracking Link
When a user selects the 'x' icon it closes the modal

## Design
N/A

## Engineering 
- Looking at the files that have the modal AddFilesForm.jsx, AddFilesFormOld.jsx and UploadStatus.jsx it looks like we will probably want to create a prop around the modal being visible or not (EX: showUploadModal) and when the modal is closed the prop is set to false.
- In order to test might need to slow load time down to actually see the 'x' button.

## Out of scope
- Add here

## Open questions
- When a user selects the 'x' icon button do we expect the modal to close or do we expect the upload to be cancelled?

## Tasks
- TBD

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- When a user selects the 'x' icon of the UploadStatus Modal it closes the modal
- When you close  with 'x' upload still happens.

**Comment by HeatherWidmont** [comment]
@skylerschain is this something you'd like to validate? It goes super fast, Peri isn't sure if its worth validating. Please let us know 😄

**Comment by skylerschain** [comment]
This is more of a bug fix, so if it's working it doesn't need design validation 👍
