### ISSUE TITLE
Developer Setup with Binstubs

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#77053]
## Description
Implement and refine the `bin/setup` binstub to ensure a consistent developer setup across all development setups (native, Docker, hybrid).

## Tasks
- [ ] Implement bin/steup to facilitate setup across native, Docker, and hybrid development setups.
- [ ] Implement for Mac OS
- [ ] Document the usage of bin/setup

## Acceptance Criteria
- [ ] Local Settings
- [ ] Betamocks
- [ ] Sidekiq Enterprise 
- [ ] vets-api setup 
- [ ] Dependency setup
