### ISSUE TITLE
Add "None" option as default for product selection box in Product Directory template

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#77050]
## Issue Description
Currently, there's many cases of someone not setting a product, which results in it defaulting to the 10-10CG app (first one in the list) when making updates to the product directory, which may be incorrect. We'd like to have a placeholder entry of "None" at the top, so that way if it's submitted without a product being selected, at least it's more obvious that it's not an intentional 10-10CG change.

---
## Tasks
- [ ] Add 'None' option to the YAML GitHub issue template
- [ ] Ensure that the 'None' option is excluded from when the list is re-alphabetized
- [ ] Test to ensure the option is the default when creating a new issue

## Acceptance Criteria
- [ ] 10-10CG is no longer the default option for the request to Update a Product, replaced by "None"
