### ISSUE TITLE
Implement optional VPG routing

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#77066]
## Issue Description

Update the vaos module to send all requests that are currently routed to vaos-service to VetsAPI Patient Gateway (VPG), if the feature flag added in #77065 is set to true.

## Tasks
- [x] Update appointment controller to send requests to VPG if the feature flag is set to `true`

## Acceptance Criteria
- [ ] Appointment updates are processed by VPG
- [ ] Changes have been deployed to staging

**Comment by drewconnelly** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/15905
