### ISSUE TITLE
Review & submit - fix accordion error styling

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#77064]
## Value Statement
**_As a_**  Benefits Decision Reviews team member
**_I want to_** make sure the review & submit page shows the correct error state coloring
**_So that_** Veteran's can get a consistent experience across our forms

## Background Context

While conducting a test of our Notice of Disagreement form in production, it was noted that the accordions that contain an error were not changing their color to show the correct error background & outline border color

![Accordion header on review & submit page showing some information has changed. please review error message, but the background color is gray instead of light red](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/0e7ddff7-9d04-4d85-9b7c-1b60fe64d231)

<img width="627" alt="gray accordion header with red page error header - they should match" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/10522c6e-0778-43b8-b175-6bd5ba352018">

### Additional info
The styling to change the color already exists, but the color variable is now undefined:
<img width="876" alt="dev console inspecting the va-accordion-item with the css panel showing that --color-secondary-lightest is not defined" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/630c984a-d0a4-4ac7-a08a-f37cc27ef416">

If you inspect the `va-accordion`, you can see all the color definitions; they just aren't making it into the `va-accordion-item` shadow dom:
<img width="437" alt="dev console inspecting the va-accordion with the css panel showing a root definition with all of the css variables defined" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/8298da03-ade3-42f9-a4d5-dc0dc7ac78fc">

## Tasks
- [ ] Determine if this is a DR specific issue, or within platform code
- [ ] Fix accordion error background & border color
- [ ] Update unit tests
- [ ] Update designs

## Acceptance Criteria
- [ ] Accordion error state has a (light) red background
- [ ] Check mutiiple apps

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by data-doge** [comment]
Passed to the design system team here: https://dsva.slack.com/archives/C01DBGX4P45/p1709046112801519

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/77064?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010 @rsmithadhoc

**Comment by humancompanion-usds** [comment]
@caw310 and @micahchiang - This is a regression and a bad one. Please move this up. A month is too long for this to be addressed.

**Comment by caw310** [comment]
I will put this into sprint 51. If someone has time we can try to get it done in sprint 50.

**Comment by Mottie** [comment]
I'm going to pick this up. I found that the CSS variables aren't defined because they were switched to SCSS variables, and the v3 accordion is missing a `part` property on the header button and content.
