### ISSUE TITLE
Add VPG routing feature flag

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#77065]
## Issue Description
Create a VA online scheduling (vaos) backend feature flag for switching the routing of appointment requests from vaos-service  to VetsAPI Patient Gateway (VPG)
[Feature flag documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

---
## Tasks
- [ ] Create backend feature flag

## Acceptance Criteria
- [ ] Feature flag has been deployed to Staging environment
- [ ] Feature flag is visible in Flipper on Staging (https://staging-api.va.gov/flipper/features)
