### ISSUE TITLE
[DA] 10-10EZR - Review RUM sessions for proper review page masking

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#77068]
## Benefit to the Veteran
By ensuring all Datadog RUM sessions are properly masking the dynamically-generated review page, we can set the masking level of the replay sessions to be more helpful to the engineers for debugging, all the while ensuring no Veteran PII is being improperly stored or exposed.

## Background
Updates have been made to the review page components in the forms library in an attempt to properly mask data from the replay sessions and activity log. We need to review some sessions to ensure this is being properly masked so we can return the application to only form inputs instead of all text on screen.

## Tasks
- [ ] Using the staging instance, advance through the application to the review page and expand all accordions 
- [ ] Review session in RUM to ensure no response data is visible in the session
- [ ] Screenshot/Log either success or fail and report back to the PMs/Matt L

## Acceptance Criteria
- No question response data is revealed in RUM sessions, ensuring no PII will be improperly stored
