### ISSUE TITLE
Re-fetch Allow Lists in E2E and Unit Test Jobs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#77062]
## Issue Description
Currently, allow lists are fetched at the beginning of the CI workflow. Unfortunately this means that if we have to disable a test to get a workflow passing, that the entire workflow needs to be rerun as the allow list will still be in its prior state. It would be a definite improvement to the workflow if we can re-fetch the allow lists at the beginning of the testing steps, as this would allow us to just rerun the "failing jobs" when a rerun is needed, and have the updated allow list available. 

---
## Tasks
- [ ] Add steps to beginning of the unit test and e2e jobs to fetch allow list.
- [ ] Ensure that everything in these steps still runs appropriately.

## Acceptance Criteria
- [ ] Failing steps only can be rerun when needed for tests to pass after disabling a test.

**Comment by CBonade** [comment]
This is open for PR review!
