### ISSUE TITLE
Update artifact handling to unblock updates to upload-artifact and download-artifact

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#77070]
## Issue Description
Currently in GHA CI, we are uploading all artifacts from parallel processes as the same artifact name. What this has done prior, is allowed us to merge all results into one artifact zip. However, upgrading upload-artifact and download-artifact to v4 no longer supports this functionality. We need to rework artifacts to unblock the upgrade of these GitHub actions as they are currently outdated and causing warnings to appear on every workflow.

---
## Tasks
- [ ] Update artifacts to have unique naming conventions on upload.
- [ ] Find a way to download all artifacts at once (believe this can be done by directory).
- [ ] Update all download-artifact and upload-artifact actions to v4 and ensure the workflows still work correctly.

## Acceptance Criteria
- [ ] The warnings have gone away that are being thrown by upload and download artifact actions being out of date.
