### ISSUE TITLE
[CAIA A11y Research]: MHV on VA.GOV, Medical Records (April 2024)

### ISSUE THREAD

**Issue by AdeAjayii** [department-of-veterans-affairs/va.gov-team#77076]
> [!NOTE]
> **High-Level Overview**: MHV Medical Records
> - **Initial Kickoff/Sync**: Research Round 2 - Kick-Off Meeting c/o MR 3/20 @ 2 p.m. 
> - **Research Timeframe**: APRIL 2-9, 2024 APRIL 11 & 12, 2024 - **_(if needed)_** 
>     - **ADDED ON - EXTENDING TO: 4/15**
> - **Time of Day:** 10:00am–1:00pm;  or 3:00pm- 5:00pm
> - **2 Pilots (rescheduled)**: ~3/15~ 3/28 and 3/29 Pilot Ticket: **([78209](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78209))**
>     - **Pilot 1**: mobile (iOS Voiceover); **Pilot 2**: desktop (JAWS)
> - **Assistive Tech Users**: Scheduling: `15`; Anticipating: `8` to complete **(Number of AT Users)**
> - **Artifacts Available**: 2/26/2024 [Staging Link](https://staging.va.gov/my-health/medical-records/))
>     - "We will be asking our SR users to review a PDF during the session." 
>          - Per [Anne Costello Kennedy (DSVA Slack)](https://dsva.slack.com/team/U042LGJFRD5)
> - **Testing Environment:** `Staging` _DM (Ade Ajayi or Anne Kennedy Costello) on Slack for staging access._ Due to staging issues, `Allergies` will not be included in this round of testing. 
> - **Assistive Tech Being Used**: `Screen Readers` `Text Magnification` and `Voice Command` 
>     - **(AT Specifics - `TBD`)**
> - **Task Lists**: See task lists for next steps/definition of done
> - **NEW Slack Channel for the Study (as of 3/19):**  [2024-04-mr-on-vagov-usability-testing-round-2-at-users](https://dsva.slack.com/archives/C06QC4EEFS6)

## CAIA Assignee(s)

<details><summary>Toggle to view information about the CAIA Team.</summary>

- @sara-amanda 
- @SarahKay8
- @EvanAtCoforma 
- @coforma-jamie 
- @eli-oat 

### CAIA AVAILABILITY
Both @sara-amanda  and @EvanAtCoforma will be out of the office the week of April 1, 2024, @coforma-jamie is available to assist @SarahKay8, while we are OOO. @SarahKay8 and @sara-amanda may be OOO the end of the week of 4/8, for an Oddball Retreat.
</details>

## About the MHV Medical Records Team

<details><summary>Toggle to view information about the team.</summary>

- Team name: MHV on VA.GOV
- OCTO-DE product owner: Kaitlin Fink
- Product manager:Marci McGuire
- Designer: Lexi Wunder
- FE engineer:
- Product/team Slack channel: [mhv-medical-records](https://dsva.slack.com/archives/C03Q2UQL1AS)
- MHV a11y: Bobby Bailey
- Accessibility Slack Channel for MHV: [mhv-accessibility](https://dsva.slack.com/archives/C05QG2H510T)

</details>

<details><summary>Toggle to view more intake research ticket information</summary>

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### Calendar checking

- [X] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [ ] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 

### Research Plan Assistive Tech Details

> _For AT, we will schedule 15 Veterans for an expected completion rate of 8 usability sessions._

<details><summary>Toggle to view AT research recruitment information.</summary>
 
> **Primary criteria for screen-reader users (must-haves)**
> - At least 7 participants who `solely use screen-readers` to access digital content – Blind/visually impaired.
> - At least 5 participants who are `low-vision and use text magnifiers` to access all digital content.
> - At least 3 participants who `solely use voice control device` to access all digital content.

> - **Do you use Assistive Technology for accessing ALL digital content?**
>     - Yes – I need `Screen reader -  JAWS, Voiceover, NVDA, Talkback` to access ALL digital content (Recruit 5)
>     - Yes – I need `Voice Command` to access ALL digital content (Recruit 3)
>     - Some – I need a `text magnification` to access ALL digital content (Recruit 7)

</details>

<details><summary>Toggle to view research timing information.</summary>

The following [information has been pulled from the MHV Medical Records Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/2024-03-usability-testing-rd2-at/research-plan.md#timeline--assistive-tech-users) on 2/26/2024.

### Timeframe

- **Pilot Session**: Week of March ~11-15~ 25-29, 2024 time of pilot `2 Pilots with Actual SR Users`
- ~Pilot 1: March 15, 2024 at 11 a.m. Mobile (Talkback)~ `Rescheduled`
- ~Pilot 2: March 15, 2024 at 1 p.m. Desktop~ `Rescheduled`
- Pilot 1: Thursday, March 28, 3:30- 5 p.m.
- Pilot 2: Friday, March 29, 1 - 2:30 p.m and/or 3-4:30 p.m.
- **Timeframe**: `04`/`02`/2024 - `04`/`09`/2024
- **Additional Dates (if needed)**: `04`/`11`/2024 and 04`/`12`/2024 
    - **ADDED ON:** 4/15/2024

### Length of sessions

- **Session length:** `90` minutes
- **Buffer time between sessions:** `30` minutes
- **Maximum sessions per day:** `4`

</details>

###  Testing Schedule

- **Time range daily:** 10:00am – 1:00pm, 3:00pm to 5:00pm Eastern Time Zone
- **Dates**: April 2-15, 2024

CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 

Please toggle and use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

<details><summary>Toggle to view the AT testing schedule</summary>

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available
------------------|------------------|--------------|--------------|--------------|--------------|--------------
**Pilot 1** | Thursday, March 28, 3:30- 5 p.m. | SR User: VoiceOver | Mobile; iOS | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 / @EvanAtCoforma 
**Pilot 2** | Friday, March 29, 1 - 2:30 p.m and/or 3-4:30 p.m. | **Known**: SR User JAWS | **Known: Desktop**; Windows, MacOS `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 / @EvanAtCoforma 
P1 | April 2, 2024, 11 a.m. - 12:30 p.m.  | Magnifier | Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @coforma-jamie 
🛑 P2 `no-show` | April 2, 2024, 3-4:30 p.m. | ~~Voice command~~ | ~~Desktop; Windows, MacOS, iOS, Android, etc. `TBD`~~ | ~~Safari, Chrome, etc. `TBD`~~ | ~~Novice, Intermediate, Advanced `TBD`~~ | @EvanAtCoforma 
P3 | April 3, 2024, 11 a.m. - 12:30 p.m. | Magnifier | Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 
P4 | April 3, 2024, 3 -4:30 p.m. | Magnifier | Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma 
P5 | April 4, 2024, 10-11:30 a.m. | Magnifier | Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 
P6 | April 5, 2024, 10-11:30 a.m. | VoiceOver | Desktop; MacOS | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @SarahKay8 
P11 | **April 8, 2024,** **11 a.m. - 12:30 p.m.** | Voice command | Desktop | Edge | Advanced | @sara-amanda 
P9 | April 8, 2024, 3-4:30 p.m. | JAWS | Desktop; Windows | Chrome | Advanced | @sara-amanda 
P10 | April 9, 2024, 11 a.m. - 12:30 p.m. | JAWS | Desktop; Windows | Edge | Advanced | @coforma-jamie 
P8 | April 9, 2024, 3 p.m. - 4:30 p.m. | JAWS | Desktop; Windows | Chrome | Intermediate | @coforma-jamie  
🛑 P12 `participant didn't use AT, session ended` | April 11, 2024, 11 a.m. - 12:30 p.m. | Magnifier and Voice command | Mobile; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @EvanAtCoforma  
P13 | April 11, 2024, 3-4:30 p.m.  | Magnifier | Desktop; Windows | Chrome | Novice, Intermediate, Advanced `TBD` | @eli-oat 
P15 | April 15, 2024, 3-4:30 p.m.  | TalkBack | Mobile; Android | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @coforma-jamie 
P14 | April 15, 2024, 10 a.m.-11:30 a.m.  | VoiceOver | Desktop; MacOS | Safari | Novice, Advanced | @coforma-jamie 
P7 `RESCHEDULED` | April 12, 2024, 2-3:30 p.m. | JAWS | Desktop; Windows | Brave | Advanced | @EvanAtCoforma  
P16 `rescheduled` | April 16, 2024, 4-5:30 p.m.  | VoiceOver | Mobile; iOS | Safari | Novice | @coforma-jamie  

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.
</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

## Supporting artifacts 

<details><summary>Toggle to view the supporting artifacts</summary>

- [Product outline](Insert URL here between the parenthesis)
- [User flows](Insert URL here between the parenthesis)
- [Prototype or mockups](https://staging.va.gov/my-health/medical-records/)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/2024-03-usability-testing-rd2-at/research-plan.md)
- [Research conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/2024-03-usability-testing-rd2-at/conversation-guide.md)
- [Epics/issue that may be helpful](Insert URL here between the parenthesis)

</details> 

## Next Steps: Definition of Done

```[tasklist]
### CAIA A11Y Tasks
- [x] **INTAKE TICKET:** @sara-amanda to process intake ticket `2/26/2024`
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available. April 2-12 on Capacity Calendar as of 2/26/2024.
- [x] **RESEARCH NOTES** Create [CAIA notes document](https://docs.google.com/document/d/1KQwrg1E29fItkNMMXJYvUU9zX--XZLFgwnjDwKvWDsQ/edit?usp=sharing)
- [ ] **[Review research folder and assets](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/2024-03-usability-testing-rd2-at/research-plan.md)**
- [x] **INITIAL MEETING:** Schedule meeting with team to discuss research - attended 2/28/2024 **MHV Medical Records Design and Research Meeting**
- [x] **Slack** Join the New Slack Channel for the Study (Round 2) 3/19/2024 creation - [2024-04-mr-on-vagov-usability-testing-round-2-at-users](https://dsva.slack.com/archives/C06QC4EEFS6)
- [x] **Study Kick-Off Meeting:** Scheduled by the MR Team 3/20/2024 at 2 p.m.
- [ ] **(OPTIONAL) FEEDBACK REQUESTED:** Review Conversation Guide
- [x] **PILOT DATES:** ~3/15~ - 2 Pilots with Evan and SK (invites on capacity calendar) 3/28 and 3/29 (Rescheduled)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78209
- [x] **REMOVE CALENDAR HOLDS** Remove holds on A11y [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean)
- [x] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support.
- [ ] **Participate in research** **Date Span:**`04/02/2024` and `04/15/2024`
- [ ] **ITEMS TO WATCH FOR**: [Watch List Items During Research for A11ys](https://docs.google.com/document/d/1KQwrg1E29fItkNMMXJYvUU9zX--XZLFgwnjDwKvWDsQ/edit#heading=h.er3od04i7adm)
- [ ] **SESSION NOTES**: Write down notes in the [CAIA notes document](https://docs.google.com/document/d/1KQwrg1E29fItkNMMXJYvUU9zX--XZLFgwnjDwKvWDsQ/edit?usp=sharing) for a11ys to use during the sessions
- [ ] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [ ] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [ ] **Share the completed deliverable** with the project team via Slack: `Primary Team Slack` and `Ticket`
```

```[tasklist]
### MHV MEDICAL RECORDS TEAM TASKS
- [x] Tag @coforma-terry in Slack [#sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH)
- [x] **PROTOTYPE:** [Provide prototype to CAIA A11ys via this ticket in the supporting artifacts section](https://staging.va.gov/my-health/medical-records/) _DM (Ade Ajayi or Anne Kennedy Costello) on Slack for staging access._
- [x] **MEETING WITH CAIA A11YS:** Schedule initial meeting with @coforma-terry and @sara-amanda FYI - CAIA attended (SS; JB; and JKF) on 2/28/2024 **MHV Medical Records Design and Research Meeting**
- [x] **SCHEDULE PILOT WITH CAIA** (Recommended): Per Research Plan: Pilot will be week of `March 11-15, 2024`, Time `3/15/2024` - invite CAIA A11ys - DONE; 2 Pilots will be conducted with users of SR. `Rescheduled` **NEW DATES:** 3/28 and 3/29
- [ ] (OPTIONAL) Receive feedback on Conversation Guide for Screen Readers (if requested)
- [x] **DATES NEEDED** See `Table 1` in the ticket above. Please provide date range and slots for AT sessions being planned. (added starting 3/26)
- [ ] **ASSISTIVE TECH. INFO NEEDED:** Please provide the detailed AT the users will be utilizing during the research sessions in `Table 2` in the ticket above, when it becomes available. CAIA has noted as of 2/26/2024 the AT from recruitment c/o the Research Plan.
- [ ] **INVITES:** Forward invites from Perigean to CAIA A11ys (Sara or Terry)
```
```[tasklist]
### Related Tickets: Past PDF Review (Prior to Staging)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/58587
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66799
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67990
```

**Comment by sara-amanda** [comment]
Thank you! Received and will process cc: @coforma-terry

**Comment by sara-amanda** [comment]
# Research Ticket Received & Processed

Hi, @AdeAjayii ! Just a quick note here to let you know that we received your research ticket and it has been processed. Thank you!

## Next Steps
- [x] Ticket processed by CAIA 2/26/2024
- [x] Temporarily, I placed holds on our [CAIA A11y Capacity calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York), for the date spans you provided 4/2-4/9 (with the optional 4/11 and 4/12). 
- [ ] When official session dates and times are set, your team (or Perigean) can invite myself @sara-amanda and @coforma-terry and we can invite the CAIA A11y Capacity Calendar. Or, if you would like, [you can invite the calendar using this address](c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com), along with Terry and myself. 
- [ ] See initial questions, below. 

## Initial Questions
- [ ] **SYNC**: Would you like to **schedule an initial meeting** with @coforma-terry to discuss your project?
- [ ] **ASSISTIVE TECH**: Do you know the specific **assistive technology that will be used** in these 15 to 8 AT sessions? If not, just let us know, as soon as you get word from Perigean. That will help us prepare to best support your team, in advance of the pilot and sessions. 
- [ ] **PILOT PREP:** We see you have time reserved the week of March 11-15, 2024 for a pilot. We would love to participate as you test your product with Assistive Tech, prior to your sessions. We would just need the final time and invitation, when available. 
- [ ] **A11Y COVERAGE:** Based on our current A11Y Capacity Calendar, it looks like there is one study taking place at the same time as your study. We will do our very best to assist you in your sessions. Will @BobbyBaileyRB be joining any of your sessions? 

## Definition of Done
- **In the two task lists in this ticket (above)**, we have outlined the remaining task items, relating to this ticket for CAIA a11ys and your team. 
- We will update this ticket in the task list area, as we move forward. 

## About CAIA Research Support

[CAIA Accessibility Support -  View the CAIA A11y Services Menu](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/CAIA/accessibility#caia-accessibility)

<details><summary>Toggle to view details on CAIA Research Support</summary>

We can help you plan your research sessions, ensuring that they are equitable and account for important accessibility factors. We recommend a pilot session with a CAIA accessibility specialist before running your research sessions, to mitigate any potential accessibility-related issues. When it comes time to run research sessions, we can also provide limited technical support for research participants who use screen readers. We can also observe your assistive technology sessions through an accessibility-focused lens, documenting accessibility-related issues the user encounters. Note that we cannot provide extensive, on call, technical support during research sessions -- if you are worried about technical issues we recommend running a pilot session or two with CAIA specialists so that we can discuss ways to best support your needs.
</details>

_We look forward to partnering with your team!_ 

cc: @coforma-terry @artsymartha68

**Comment by sara-amanda** [comment]
## Related PDF Tickets
Good news! As we prep for user research with assistive technologies for MHV Medical Records, we can confirm that the PDFs have had a previous CAIA review. 

### PDFs for Medical Records 
- **Previously Reviewed**
    - Both @SarahKay8 and @EvanAtCoforma (and Angela) have previously reviewed PDFs for Medical Records, prior to them entering the staging environment.
        - PDFs were reviewed in **October 2023** (tickets: 66799 and 67990)
        - PDFs were initially reviewed in **June 2023** (58587)
        - _**Note**: CAIA tickets listed in this comment are currently archived._ 
- **PDF Updates/Changes**
    - If anything has changed since then, we would be happy to review them again, prior to the pilot. 
    - @BobbyBaileyRB  mentioned he could upload a few to staging if requested, @SarahKay8 @EvanAtCoforma 

### Task Lists

Please refer to the task lists in this ticket. 

- [Related Tickets: Past PDF Review (Prior to Staging)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77076#:~:text=RECORDS%20TEAM%20TASKS-,Related%20Tickets%3A%20Past%20PDF%20Review%20(Prior%20to%20Staging)
- [CAIA A11y Tasks](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77076#:~:text=Definition%20of%20Done-,CAIA%20A11Y%20Tasks,-Beta)
- [MHV Medical Records Team Tasks](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77076#:~:text=CAIA%20A11Y%20Tasks-,MHV%20MEDICAL%20RECORDS%20TEAM%20TASKS,-Beta)

cc: @artsymartha68 @coforma-terry 
@AdeAjayii @AnneCostello @SarahKay8 @EvanAtCoforma @coforma-jamie @BobbyBaileyRB

**Comment by sara-amanda** [comment]
# Pilot Session with CAIA

@AdeAjayii @AnneCostello - We see from your research plan, that you are looking to conduct a pilot the week of March 11-15, 2024. We would be happy to assist with that, so that assistive technology can be tested in advance of the actual study, in order to mitigate any accessibility, device or technology- related issues, that may arise. 

## Assistive Tech

The assistive tech being used is listed as: Screen Readers Text Magnification and Voice Command. When you know specifics from Perigean, if you can let us know. Knowing the primary AT being tested will help us to best prepare for the pilot session. 

## Scheduling

### CAIA Availability
Please find our availability below, for scheduling purposes. 
- @SarahKay8 (available all week)
- @coforma-jamie (available all week)
- @EvanAtCoforma (OOO March 11 and 12)
- We will want to also invite the [CAIA A11y Capacity Calendar ](c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com)

cc: @coforma-terry @alexiawunder

**Comment by sara-amanda** [comment]
@EvanAtCoforma @coforma-jamie 
Pilot Ticket Created [CAIA A11y Research - Pilot] MHV on VA.GOV, Medical Records (March 2024) #78209

**Comment by SarahKay8** [comment]
Hi @AdeAjayii! Are the participants testing on mobile and desktop or just desktop?

**Comment by AdeAjayii** [comment]
@SarahKay8 our first user at 11am will be using an Android phone, while the second pilot participant will be using a desktop. Thank you.

**Comment by SarahKay8** [comment]
@AdeAjayii Thank you!

**Comment by SarahKay8** [comment]
@AdeAjayii I'll be available

**Comment by sara-amanda** [comment]
@SarahKay8 and @AdeAjayii I have added temporary holds to the CAIA A11y Capacity Calendar for those dates/times. I will be OOO so thank you so much @SarahKay8 !

**Comment by sara-amanda** [comment]
## User Sessions

### Table Updated
[The table in this ticket has been updated](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77076#:~:text=Toggle%20to%20view%20the%20AT%20testing%20schedule) to reflect the [CAIA A11Y Capacity Calendar's invites c/o MHV: Medical Records ](https://calendar.google.com/calendar/embed?height=600&wkst=2&ctz=America%2FNew_York&bgcolor=%23ffffff&mode=WEEK&showTz=0&showCalendars=0&src=Y19mOTgyMzUwZmM3M2E4MTYyYTEwODhhYjE0ZDAwZGQzNzMzNWIyYjU1OWE2MGQ2YjY3ZWI4MDIxNDE2ZjgxYzJhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23616161)for this study. 

### Next Steps
- @AdeAjayii Do we have the participant numbers? 
    - If so, we can add update the table. 
- @AdeAjayii Do we know the technology and devices the users will be testing with yet? 
    - This will allow CAIA to prepare in advance for the sessions.

Thanks so much in advance!

cc: @coforma-terry

**Comment by sara-amanda** [comment]
## Rescheduled Session
### P7 
- **New date and time:** 2 p.m. ET on Friday, 4/12
- **a11y slot status:** `open slot`
- **AT:** JAWS (Desktop)

cc: @eli-oat @SarahKay8 @EvanAtCoforma @coforma-jamie

**Comment by coforma-jamie** [comment]
This study is closed as of Wednesday, April 16. We've reported our accessibility findings to the team during each session, but here's a compilation of our key findings that you can reference, @AdeAjayii:

## Possible bugs
- **Vitals history page**: During a JAWS session, it sounded like there might be empty `<H4>`s on the page. Worth a check! Please remove any empty headings if you find them.
- **PDF**: Navigation between pages within the PDF varied between users. Some had trouble getting to the next page while others go to it with no problem. May be a difference in experience with the AT, as the ones without issue were experts with their AT.

## Usability recommendations
- Use common names / plain language throughout for immunization titles and clinic locations. Examples:
   - **Locations**: Users didn't know what "YELLOW-PC-CLINIC" meant. There was another location, written in shorthand, that an SR attempted to decipher by going character-by-character before giving up.
   - **Vaccinations**: The "Zoster" shot for shingles was specifically called out. Participants wanted this called "Shingles vaccine" or similar, since "Zoster" isn't commonly known.
- **Immunizations page**: There's a spot where the words "go to your allergy records" are repeated twice - once as standard paragraph text, once as a link. Recommend either changing the red underlined text here, or adding the link to the paragraph:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/e94816ed-4788-449c-bcc8-73415ab9b252)
- **List pages (vaccinations, care summaries)**: 
   - In general, using assistive tech (screen readers in particular) adds time to tasks. As one participant said, “VoiceOver reads everything to you, even things you don’t want." Many participants asked for search filters on the various lists for ease of navigating, and to save time. Filters could include date, location, type of immunization, etc.
   - One SR user asked for pagination both above and below the main content, to avoid accidentally skipping it.
