### ISSUE TITLE
Conduct Practice Research Session for "View and update my representative/View payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7707]
## Goal
Before engaging with Perigean, we want to conduct a practice sessions with the internal team to gain insight as to how we might improve our research sessions.

## Tasks
- [ ] Conduct a mock research session with the internal team
- [ ] Establish what changes need to be made 

## Considerations
- Once this has been completed, schedule with Perigean and obtain some users to chat with.
- This may include a few questions regarding "View my payment history"

## Acceptance Criteria
- [ ] Feedback has been received and is documented in the research folder within the team's feature folder. 

### Next steps
- Schedule with Perigean
