### ISSUE TITLE
Upload password | Check PDF password on backend

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#77084]
## Value Statement
**_As a_**  Benefits Decision Reviews team member
**_I want to_** make sure we're only checking the PDF for a user password (encrypted)
**_So that_** the Veteran isn't blocked from uploading PDFs with only an owner password (read-only)

## Background Context

While conducting a test of our Notice of Disagreement form in production, it was discovered that PDFs can be locked using an owner password, but are still visible and accepted by VA. PDFs with a user password must be entered before the PDF is visible, so these files need to be unlocked prior to submission. Currently, our frontend checks PDFs for an encryption signature, which are present in both user and owner locked PDFs, so we can't differentiate these two types. The frontend would require a PDF library to better distinguish the difference; but Lighthouse already provides an API to check PDF, so these changes reflect our shift to use Lighthouse's API.

<img width="500" alt="add password button overlaps pdf password input" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/88ae900c-3c9a-48b0-9b30-617d41a2aea5">

We also need to update the behavior to check for PDF encryption on the backend. In this case, the PDF password input would be shown _after_ the backend returns a _missing user password error_. Once the password is provided, we show a successful unlock

<img width="543" alt="PDF file card showing the password has been added" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/67945fe4-eaaf-4b93-945c-86af176d9ac9">

## Tasks
- [ ] Update FileField to ask for a password _after_ uploading and the BE returning a missing password error
- [ ] Cleanup FileField and ShowPdfPassword components
- [ ] Update unit & e2e tests
- [ ] Update designs

## Acceptance Criteria
- [ ] Adequate spacing is added around the add password button
- [ ] Check spacing with add password button in an error state
- [ ] Checked in multiple apps (NOD & Supplemental Claims)

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by HeatherWidmont** [comment]
FE is now relying on the BE to get the password. This work is dependent on Annie's work. Robin will open a PR today, but can't merge until #74493 is done

**Comment by eileen-coforma** [comment]
Validated in parking lot. Works as intended.
