### ISSUE TITLE
Contact Info | Update success slim alert to v3

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#77080]
## Value Statement
**_As a_**  Benefits Decision Reviews team member
**_I want to_** make sure our web components using the v3 version
**_So that_** Veteran's can get a consistent experience across our forms

## Background Context

While conducting a test of our Notice of Disagreement form in production, it was noted that the success alert shown after updating contact info is still using the v1 slim alert

![Screenshot 2024-02-23 at 2 48 00 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/7ed45c03-d130-46ca-a8df-93c4a994cab0)

## Tasks
- [ ] Update contact info page success slim alert to v3
- [ ] Update unit & e2e tests
- [ ] Update designs

## Acceptance Criteria
- [ ] Using v3 success slim alert

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
