### ISSUE TITLE
[CST] v3 component migration

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#77095]
We need to migrate v1 components to v3 components. There are 6 components that need to be migrated to V3 in the Letters app. We need to remove the false prop for 14 components. We can beginning working this ticket after 2/16.

Here is a link to the [audit doc](https://docs.google.com/spreadsheets/d/1ajKjN6dr-2PzpgEbfX1OqxAupvbqoHwqh7ml1m5a1Fo/edit?usp=sharing).

---
### Steps

- [ ]  Any components that were updated as USWDS false that are not V3 components should have that prop removed.
- [ ]  Design and engineering test locally to confirm design fidelity of the migration before changes are merged

## Engineering 
- Add here

## Out of scope
- EVSS

## Tasks
- [ ] Update AppealHelpSidebar.jsx
- [ ] Update DurationCard.jsx
- [ ] Update Issues.jsx
- [ ] Update ClaimCard.jsx
- [ ] Update AddFilesForm.jsx
- [ ] Update AddFilesFormOld.jsx
- [ ] Update ClaimContentionList.jsx
- [ ] Update ClaimDetailLayout.jsx
- [ ] Update ClaimLetterListItem.jsx
- [ ] Update ClaimsBreadcrumbs.jsx
- [ ] Update ClaimsDecision.jsx
- [ ] Update ClosedClaimMessage.jsx
- [ ] Update EvidenceWarning.jsx
- [ ] Update StemAskVAQuestions.jsx
- [ ] Update WIP.jsx
- [ ] Update AdditionalEvidencePage.jsx
- [ ] Update AdditionalEvidencePageOld.jsx
- [ ] Update AskVAPage.jsx
- [ ] Update ClaimStatusApp.jsx
- [ ] Update DocumentRequestPage.jsx

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] All V1 components with a V3 version are migrated to that version of the component.
- [ ] All V1 components that do not have a V3 version do not have a prop set to false
- [ ] Post migration, the UI meets the BMT team's design and Ux standards.

**Comment by pmclaren19** [comment]
Team eng leads decided that we should not to merge this pr since it is the last day of our contract. We will merge next week if we get the contract, otherwise whoever picks up this contract will need to finish this work.

**Comment by pmclaren19** [comment]
Validated changes in Staging and looks good!
