### ISSUE TITLE
[UX] Create GA Custom Dashboard with widgets

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#77092]
## Tasks
- [ ] Create GA Custom Dashboard with widgets to track usage and interactions in travel pay for OH facilities app 
- [ ] Make available to team 

## AC
- [ ] Widgets are set up
- [ ] Available to team via direct link and email notification set up
