### ISSUE TITLE
[FE] Add GA events to API calls and customize values for component and navigation clicks

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#77091]
## Tasks
- [ ] [FE] Add GA events to API calls and customize values for component and navigation clicks (using the [Travel app tab in the GA events spreadsheet](https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=2075861504))
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
Sounds good. I'm going to unassign you and assign to me, as it might take a bit to validate. This up in staging on next deploy?

**Comment by benbrasso-agile6** [comment]
Oh wait, how would I validate? I'd also be fine validating in production.

**Comment by benbrasso-agile6** [comment]
Do these in the spreadsheet need to change to `travelClaim` or are they good as is? 


```
API Request - travel-claim-submit-travel-claim - started
API Request - travel-claim-submit-travel-claim - success
API Request - travel-claim-submit-travel-claim - failed
```

**Comment by brianseek** [comment]
those ones are good as is.

You can validate locally or wait for stage/prod. We should be able to play with it in stage next week, but you will need an engineer to setup lorota for you

**Comment by benbrasso-agile6** [comment]
Let's just close it. I switched the changes in the GA Dashboard I made.
