### ISSUE TITLE
[UX] Create GA Custom Dashboard with widgets

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#77093]
## Tasks
- [x] Create GA Custom Dashboard with widgets to track usage and interactions in travel pay for OH facilities app 
- [x] Make available to team 

## AC
- [x] Widgets are set up
- [x] Available to team via direct link and email notification set up

**Comment by benbrasso-agile6** [comment]
https://analytics.google.com/analytics/web/#/dashboard/yqkbRXcgQXKYTYs6ReQscg/a50123418w177519031p176188361/
