### ISSUE TITLE
Urgent care "Call first" wording suggestion from OCC

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7711]
## User Story or Problem Statement
How might we encourage Veterans to call community urgent care provider locations before visiting?

**Current behavior**

> Before going to a clinic for urgent care, please call the facility to confirm that it's open and able to provide the care you need.

**Suggested language from OCC (sent by email 4/6):** 

> Please call <insert number from PPMS> to confirm hours of operation, wait times, and ability to provide the care you require.

## Goal
Veterans will be advised to call to confirm hours of operations and availability of location to provide service before proceeding to facilities

## Objectives or Key Results this is meant to further
Objective 2: Deliver meaningful facility information 

---
## Tasks
- [ ] Consider wording suggestion from OCC and/or incorporate into future user research

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
