### ISSUE TITLE
[ANALYTICS] Create a process to convert/create .csv file from Data discovery files (Playbook, Facilities, caregiver) ready for load into Drupal Automation [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7712]
## Story
As a Public Affairs Officer, I need to know all of the items and areas of information needed for the upcoming VAMC-Upgrade, so I can easily provide that information to the VAMC-upgrade team.

## Goal
_Provide an easy to understand and easy to fill out/confirm spread sheet to the PAOs to provide pertinent information needed to complete the multiple layers of the VAMC-Upgrade_

## Objectives or Key Results this is meant to further
- _Increase System page completion each quarter_
- _Increase velocity overall through business optimization_

## Resources - Tools - Documentation
[VISN_4_Content_Stack](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[VA.gov_Medical_Center_Map_Moqup](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9)

## Tasks
_Complete the following tasks for this Story:_
- [ ] Process to create .csv file information from Playbook
- [ ] Process to create .csv file information from Facilities data
- [ ] Process to create .csv file from caregiver page information

## Acceptance Criteria
Items that must be validated to be fully accepted and story closed:
* Process to create .csv file information from Playbook
* Process to create .csv file information from Facilities data
* Process to create .csv file from caregiver page information
