### ISSUE TITLE
[VSOffs][Prototype] User Testing - Prep for sessions

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#77150]
## Description
Placeholder ticket for various Research Ops involved in preparing the ARF Design team for running user testing. Owner of this ticket will be responsible for assigning and ensuring QA for various Ops tasks. Note that all research documentation, including note taking templates, must reside in Sharepoint.

### Tasks
- [x] Create [Sharepoint folder](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/032024%20VSOR%20User%20Testing?csf=1&web=1&e=nBcDcq)
- [x] Once finalized, upload all study documentation to the folder: research plan, recruitment plan, conversation guide (in progress) 
- [x] Create [note taking Mural template](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711575270185/83b03fe96dcafe9f42b206e0dc3efbfd2457c1f2?sender=u8cf3f08a008c2b61ad621433) using the conversation guide
- [x] Create study-specific Slack channel: 2024-04-arp-vsor-user-testing
- [x] Invite ARF team to be observers/notetakers and add volunteers to the channel
- [x] If not enough people sign up as notetakers and observers, advertise the study in #benefits-portfolio 
- [x] Create EnjoyHQ project folder

### Leads or Collaborators
Lead: @uxrebecca 
Contributor: @RenataKeck 

### Resources
- [Research plan](https://docs.google.com/document/d/1RuSlR4fvNFXUWN1XtwG0zKmkGGgoQhvmAacQaYIWzL0/edit?usp=drive_link)
- [Conversation guide](https://docs.google.com/document/d/1VO5H0DBhPuTEetj068H6cstV2qn8qtRNk6ewxTT284c/edit#heading=h.dneu68fnw65f)
- [Sharepoint folder](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/032024%20VSOR%20User%20Testing?csf=1&web=1&e=nBcDcq)

## Acceptance Criteria
- [x] Documentation is in Sharepoint
- [x] EnjoyHQ project folder created
- [x] Slack channel created

**Comment by uxrebecca** [comment]
Slack channel created and posted to ARF OCTO channel first to get volunteer notetakers and observers.

**Comment by RenataKeck** [comment]
EnjoyHQ project created, Sharepoint documentation will be updated pending final review of conversation guide.
