### ISSUE TITLE
[VSOffs][Prototype] User Testing - Participant Mgmt

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#77153]
## Description
Placeholder ticket for all participant management related to the prototype v1 user testing study. Owner of this ticket will be responsible for assigning out and closing all tasks related to participant management.

### Tasks
- [x] Creating and managing a test sessions tracker spreadsheet, uploading to Sharepoint folder
- [x] Creating Zoom Scheduler for scheduling sessions with users (once Harold confirms we can use)
- [x] Sending recruitment messaging to participants from our panel via VA.gov email
- [x] Using the team Zoom account to add sessions to the schedule tracker and the study's Slack channel
- [x] Sending reminder and thank you emails to participants around sessions
- [x] Updating the participant panel

### Collaborators
Lead: @RenataKeck 
Contributor: @uxrebecca 

### Resources
- [Recruitment strategy](https://docs.google.com/document/d/1xEUIm-rtHxDJmdwJK4eNU8xqjkQusOmlI8gmNLP-0r8/edit) for the study
- [Sharepoint folder](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/032024%20VSOR%20User%20Testing?csf=1&web=1&e=nBcDcq)
- Team template
- [Study Slack channel](https://join.slack.com/share/enQtNjg5MjM5MzUxMDgwMS02Nzc5MGEyMGQ4OWRkM2Q5MzE5NGY5NGZkNzM5MTg0MTEzZmM0YzFlZTU0YzhjYTEwYTgyOWNkYmE3MDAyN2Q1)
- Participant panel

## Acceptance Criteria
- [x] Study sessions tracker spreadsheet has been completed for the study
- [x] Participant panel has been updated to reflect most recent round of testing
