### ISSUE TITLE
[AUTOMATION] Create and test script to load System Level HEALTH Service and Facility information  [Engineer]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7715]
## User Story or Problem Statement
As a Data Tech, I need an optimized way to set content into existing content fields from a .csv or .txt file, so I can reduce time in loading and completing page content in VAMC- Web page/nodes.

## Goal
_Implement required va.gov webpages_

## Objectives or Key Results this is meant to further
- _Increase pages/nodes completed in a quarter_

## Resources - Tools - Documentation
[Review System and facility spreadsheet](https://dvagov.sharepoint.com/:f:/s/VHADigitalMedia/vamc-upgrade-project/Ej33rnb0EAZDkvT2A-696qUBx40SHv8dOusH-nP810orTg?e=3JLBLQ)

## Tasks
_Load data into System and facility Health service content _
- [ ] Create migration/automation  of .csv file into System Level Health Service Content using Customized Health service playbook .csv file (start with one service)
- [ ] Migrate/automate of .csv Facility content for Health Service into drupal for the same health service uploaded at system level.
- [ ] work to migrate/automate multiple health service data loads. 
- [ ] Work to associate/migrate/automate multiple facilities to Health services
- [ ] Determine and document best Migration tool to be used and if there are any changes required in .csv file.

## Acceptance Criteria
_Validate outcome of pushing content to existing page_
* Create migration/automation  of .csv file into System Level Health Service Content using Customized Health service playbook .csv file (start with one service)
* Migrate/automate of .csv Facility content for Health Service into drupal for the same health service uploaded at system level.
* work to migrate/automate multiple health service data loads. 
* Work to associate/migrate/automate multiple facilities to Health services
* Determine and document best Migration tool to be used and if there are any changes required in .csv file.
