### ISSUE TITLE
[UX][Research] Migrate echeckin GA Custom Dashboard to GA4 Dashboard

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#77163]
## Tasks
- [ ] Migrate echeckin GA Custom Dashboard to GA4 Dashboard (Note: Time-boxed at a 5 pt.)
- [ ] Create new ticket after 5 pts are completed for any work that remains

## AC
- [ ] echeckin GA4 Dashboard is created and pulling in data
- [ ] New ticket created for follow-on work, if applicable

**Comment by benbrasso-agile6** [comment]
https://www.monsterinsights.com/how-to-create-ga4-dashboards-step-by-step/

**Comment by benbrasso-agile6** [comment]
https://www.semrush.com/blog/google-analytics-dashboard/

**Comment by loripusey** [comment]
[PCI GA4 Check-in Metrics](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/v08dnfMeRpi0OZRusDBV9w)
[PCI GA4 Pre-Check-in Metrics](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/fBTnZD1-T3SQ5HtcKHsT_A)
[PCI GA4 Travel Metrics](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/tPiLrf3xTV6yL_RPS8eFEA)
