### ISSUE TITLE
[UX][FE] 10-10EZ Toxic Exposure - Content additions to confirmation page

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#77164]
## Issue Description
As a Veteran who could now be eligible for health care due to toxic exposure, I want there to be consistency with options available online and with the paper form.

Add content to the form on the confirmation page about the path to submit a written statement.

[Link to Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=1784-28657&mode=design&t=aNlBZdTu2ZopQlMP-4)

---

## Tasks
- [x] [UX] Work with content to update designs for the EZ confirmation page
- [x] [UX] Once completed/approved tag FE/Matt
- [x] [FE] Update confirmation page 
- [x] [FE] Staging review/validate

---

## Acceptance Criteria
- Staging confirmation page is aligned with new content updates

**Comment by jessicastump** [comment]
Update am 2/28: We're just waiting on SMEs to answer one last question about "written statements" and the aligned content on the Confirmation page.

**Comment by jessicastump** [comment]
The final content updates have been made after HEC SMEs reply

**Comment by longmd** [comment]
@jessicastump , Just wanted to clarify that the "Go to health care application" action link that is currently following the "Go Back" paragraph is supposed to be removed?

![Screenshot 2024-02-29 at 11 34 33](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/62413215-4b84-473e-8b72-18db45956070)

**Comment by longmd** [comment]
@jessicastump , and wanted to check that we are adding this "Go to VA.gov" action link at the bottom now?
![Screenshot 2024-02-29 at 11 48 51](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/2e93a92d-77cc-4f67-84f6-187ee8605149)

**Comment by jessicastump** [comment]
@longmd Thank you for catching that!! Yes both action links should be there, the "Go to health care application" under status section was my miss in the Figma file and will correct right away. And yes, the last one stays - that was part of the confirmation template

**Comment by jessicastump** [comment]
@longmd Did a first run through staging and the only item noticed was the address on the confirmation page. see screen shot below. The address component line breaks are not formatting correctly. 
<img width="707" alt="Screenshot 2024-03-04 at 11 57 01 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/bea5eed1-067a-4971-ab0e-e805ee6c3f56">

**Comment by longmd** [comment]
@jessicastump , the formatting has been updated.
