### ISSUE TITLE
Check for two environmental variables

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#77174]
## Summary

If there is an environmental variable in the settings Yaml, then there should also be an environmental definition. 

Environmental variables have to be defined in the values.yaml in two different sections, [settings-local-secrets secrets](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/values.yaml#L671) and [settings.local.yml config map.](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/values.yaml#L1778).

Ex:
The HOSTNAME env variable is defined in secrets and in settings.local.yml:

L672:
```
        - name: hostname
          path: /dsva-vagov/vets-api/prod/hostname
          env_var: HOSTNAME
```
L1779:   `hostname: <%= ENV['HOSTNAME'] %> `

- All env_var names will be unique
- Think through edge cases

## Tasks 
- [ ] Create a github action to ensure the env_var and environmental variable are both present and match.
- [ ] Give a heads-up about the new workflow in Backend CoP Slack channel

## Acceptance Criteria
- [ ] GitHub Action is merged and validated to be working. 

---
### Validation steps
- Make a PR to the manifest repo changing one of the vets-api values.yaml files (any env). Make the following changes in one commit:
    - Add a new block (`name`, `path`, `env_var`) to the `settings-local-secrets` section
    - Delete a block from that same section
    - Modify a block from that same section
    - Add a new line to the `settings.local.yml` configMap section (something like `test: <%= ENV['TESTING_TEST'] %>`). Make sure this variable name is unique.
    - Delete a line from that same section.
    - Modify a line from that same section
- Once you create a PR with those changes, the **Validate values.yaml variables / validate-values** workflow should run, fail ❌ and post a comment to the PR listing all six of those variables you modified. The comment will look like this: 
![image](https://github.com/user-attachments/assets/22093b9c-fb84-4e66-8de1-aad4f4677d0f)
- Now, to test the success path, undo all of those changes AND make a commit where you add, modify and delete variables from BOTH sections i.e. if you delete this section:
```yaml
  - name: connected_apps_api_key
    path: /dsva-vagov/vets-api/sandbox/lighthouse/connected-apps/api_key
    env_var: CONNECTED_APPS_API_KEY
```
You also need to delete this line further down: `api_key: <%= ENV['CONNECTED_APPS_API_KEY'] %>`. 
- Once you push that commit, the **Validate values.yaml variables / validate-values** workflow should run and pass ✅. There will be no comment posted to the PR.

**Comment by rmtolmach** [comment]
I got something working on my branch: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3072. I will run through testing scenarios tomorrow and clean it up a bit.

**Comment by jennb33** [comment]
8/26 update: @rmtolmach was doing the testing scenarios and ran into a bug, which is being fixed. Then this will be tested again and if it passes we can proceed.

**Comment by rmtolmach** [comment]
Made some good progress today (see PR description). The PR will be ready for review tomorrow morning.

**Comment by rmtolmach** [comment]
I'm working on one final (hopefully!) edge case. I have it halfway resolved (for adding variables) but not for removed variables 😑

**Comment by rmtolmach** [comment]
PR merged. Closing. I will monitor the action over the next few days.
