### ISSUE TITLE
GA4: Data Mapping Prep: Pilot Creation of GA4 View in BigQuery

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#77173]
### Description:
As a way to prepare for our upcoming work outlined on [this card](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/75520). This task will involve creating a new _GA4 View_ for one of the BQ datasets that contain UA data outlined in [this document](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=0&fvid=2002218633).

### Tasks:
- [x] Identify a BQ view that leverages UA data
- [x] List the UA attributes used in the query
- [x] List the derived fields in the query
- [x] Map the UA attributes in and map to the GA4 equivalent (where possible and note any modifications needed)
- [x] Identify the attributes that do not have a GA4 equivalent 
- [x]  Rewrite the derived attributes to use the GA4 attributes
- [x]  Review  GA4 Session attributes/model and design a query to derive the session attributes for the view
- [ ] Create a separate, GA4 view in BigQuery, that incorporates GA4 data

### Acceptance Criteria:

- [ ] Single new GA4 views will be created in BigQuery
- [ ] GA4 views, will be labeled appropriately, (through use of BQ labels, a created list, or some other means)
- [x] Findings from piloting this process will be outlined in [this ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/75520), which will serve as the next steps.
- [x] Look to logically break out the work done in #75520 into separate tickets, or groupings

**Comment by dorseypa1** [comment]
The findings from this ticket are documented here.

https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=1389395802

**Comment by dorseypa1** [comment]
The pilot view chosen for this ticket is `vsp-analytics-and-insights.vsp_sites.vw_facilities_detail_last_week`

**Comment by johnny-jesensky-adhoc** [comment]
This ticket will carry over to the next sprint. This was partially a discovery task, and the complexity ended up being greater than we had originally planned. We accomplished some, but not all of what we needed for this task.

Current work is documented here: https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=1389395802

We're going to be more conservative next sprint around our BigQuery tickets, as we work through these first handful of data mapping exercises.

FYI @dorseypa1, @jwoodman5, @davidconlon

**Comment by johnny-jesensky-adhoc** [comment]
Per discussion with @dorseypa1 -- we are going to wait for Jamie to progress further in some set-up in GA4, before working on the standard KPI dashboard views. The next step on this will be subbing out some of the BQ Views in Domo -- captured in [this ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/79408) to be worked on next sprint.

Moving this to **_Done_**.
