### ISSUE TITLE
[UX][FE] 10-10EZ Toxic Exposure - Content changes to introduction page

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#77178]
## Issue Description
As a Veteran who could now be eligible for health care due to toxic exposure, I want there to be consistency with options available online and with the paper form.

Add content to the form on the Introduction page about questions around toxic exposure (under Step 2, Gather your info) and the change to the OMB time from 30 to 35 minutes.

[Link to Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=615-123324&mode=design&t=aNlBZdTu2ZopQlMP-4)

---

## Tasks
- [x] [UX] Work with content to update designs for the EZ introduction page
- [x] [UX] Once completed/approved tag FE/Matt
- [x] [FE] Update introduction page 
- [x] [FE] Staging review/validate

---

## Acceptance Criteria
- Staging introduction page is aligned with new content updates

**Comment by jessicastump** [comment]
There were some updates to the introduction page content as part of this review too. Mostly under Step 2 of the process list, the time under Step 3 and in the OMB component.
[Designs/content in Figma](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=615-123324&mode=design&t=9u5OEq3TJnAIxEvg-4) are ready @longmd

**Comment by hdjustice** [comment]
## Update
We have received the OMB/PRA approved final draft of the 10-10EZ form, submitted to approve the TERA questions being added.  The latest update is to the PRA content and the burden time (from 30 to 35 minutes).  We need to make updates to the Privacy Act modal to reflect this newly approved content.

#### Resources
- [Updated EZ paper form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/OMB_PRA%20Approved%20-%20VA%20Form%2010-10EZ_PACT%20Act%20-%20Sec%20103%20revisions_MAR%202024.pdf)
