### ISSUE TITLE
Require two approvals for vets-api-prod files in the manifest repo.

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#77172]
Ticket duped for Sprint 3; new ticket is [86298](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/86298)

## Summary

In the [manifest](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) repo, all files in the [prod directory](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/prod) need 2 BE CoP approvals going forward. This will reduce risks of shutting down production. Some mistakes to these files will break production.

## Tasks
- [x] Create instructions for users to follow (_or_ confirm that the instructions are accurate) - add this link to documentation in DevTools: https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Secretvalues
- [x] Create checklist for verification by user (no whitespaces, no tabs, newlines, etc)
- [x] Add this copy to the documentation: **IF YOU ARE UNSURE OF YOUR VERIFICATIONS, PLEASE HAVE SOMEONE ELSE CHECK; OTHERWISE PRODUCTION WILL BREAK**
- [x] Create a github action to require 2 approvals from BE COP
- [x] Tested new GitHub actions to get 2 approvals on files in the manifest repo

## Success Metrics
- [ ] That there are 2 BE CoP approvals created in GItHub actions

## Acceptability Criteria
- [ ] 2 BE CoP approvals created in GItHub actions

**Comment by jennb33** [comment]
Ticket duped for Sprint 3; new ticket is [86298](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/86298)
