### ISSUE TITLE
Discovery into special issues being sent from 526 via EVSS

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#77175]
**Issue Description**

EVSS sends 526 special issue identification on a rated disability. Do they need it back to send special issues to VBMS? 
How is LH setting special issues? What is needed from 526?
LH v2 submit does not accept special issue in the submission object
This might be relevant for new conditions and not a rated disability, as they would already have it.

---
## Tasks
- [ ] Ask in #evss-dev or #evss-prod / tag Bonnie Craig/  if EVSS sets any flashes or special issues based on any logic or if they just accept flashes & special issues from the submission system?

## Acceptance Criteria
- [ ] Document the list of special issues that LH needs to send to not break current functionality
- [ ] Identify what is needed from 526 for LH to send the special issues downstream 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Created this [wiki doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/special_issues_discovery.md) with notes and answers to the above
