### ISSUE TITLE
EVSS Migration - /generatePDF migration: Abstract references to EVSS /getpdf

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#77177]
## Issue Description
Abstract references to EVSS /getpdf

---
## Tasks
- [x] create a /generatePDF provider to be created by the ApiFactory
- [x] create flipper feature toggle to switch from EVSS to LH
- [x] fix failing unit tests by switching the feature toggle on/off

## Acceptance Criteria
- [x] Abstract references to EVSS
- [x] Maintain test coverage
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Related Issues
- [#57859](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57859)
