### ISSUE TITLE
Spike | Determine LOA level for Ch36/PCPG

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77179]
## Issue Description
_There are new Platform guidelines for forms with LOA3 authentication, so we need to determine what level of authentication the Chapter 36 (PGPG) 25-8832 uses._

This ticket related to Platform feedback received in #76631.

---
## Tasks
- [ ] Determine LOA level of 25-8832 form

## Acceptance Criteria
- [ ] Communicate level to Matt Dingee to add to [this document](https://dsva.slack.com/files/U03740NA3E3/F06LLLU3WHK/va_forms-all_digitized_forms_-_by_authentication_type.xlsx).
- [ ] If LOA3, create design and dev tickets to address Platform requirement outlined in #76631
---
