### ISSUE TITLE
Utilize Calendly for sharing Zoom info 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#77188]
## User Story
As a Governance team member, I want to ensure that all invites to Collab Cycle touchpoints include the Zoom information so that all VFS team members are able to easily join the meeting.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
Governance team has experienced ongoing and recurring issues with the Zoom information not being included in Collaboration Cycle invites/events. We thought we implemented a [solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73190)  in January, however several VFS teams have shared recently that they themselves and/or their leadership were unable to find the Zoom information in the meeting invite/event details. 

Calendly, our scheduling tool, does have the ability to share Zoom information. ~~There are a couple different ways in which this can be done. This ticket will look into how we might best use Calendly for sharing Zoom information~~*, implement the preferred solution and update our operational process to remove the step for adding Zoom information. 

*Since we have alternative hosts set up for all of our current Zoom meetings, we cannot use the built-in Zoom option that Calendly offers bc this option creates a new Zoom meeting for every occurrence, using the hosts account. It would be a huge inconvenience to add alternate hosts for every new meeting. Instead, we'll use the Custom option in Calendly, and we can/should utilize the existing Zoom events via the [Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings) doc.

## Impacted Artifacts
DI/MPR Calendly event
SR Calendly event
[Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)
[Collaboration Cycle Calendly guide](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide)
[Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
[Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
[Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)

Do we need to modify the automated messages in the Slack workflows?

## Tasks
- [x] Test Zoom and Calendly to have the link already in the invite
- [x] Update the documentation to reflect the change and copying the Zoom link into the invite is no longer needed.
- [x] Update [Collaboration Cycle Calendly guide](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide) with necessary info about how Zoom is in Calendly
- [x] Update Zoom in Calendly to have the link already in the invite
- [x] Archive [Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All Collab Cycle events scheduled through Calendly include the Zoom information
- [x] Governance team members no longer have to add the Zoom information to the meeting invite

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@erinrwhite I have updated [all drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2995028443/77188+-+Utilize+Calendly+for+sharing+Zoom+info+-+Allison). I think we can delete the Zoom info doc since I updated the Calendly guide. Take a peak and let me know your thoughts.

**Comment by allison0034** [comment]
Looking at Slack workflows I don't think any changes need to be made.

**DI**
Your review for Monday, February 26th 3:30 – 4:00pm ET is confirmed. Check off the VFS actions in the ticket, including:
If needed, add any additional VFS attendees, including accessibility and POs, to the invite on your calendar
Link all artifacts ONLY in the Design Intent artifacts section at least two days before the scheduled Design Intent. Do NOT add artifacts to Comments section
For Design Intents we require user flows
Note: We will reschedule the review if you do not provide artifacts at least two days prior. Please let us know if you have any questions.

**MPR**
Your review for 2/29/24, 3:30pm ET is confirmed. Please be sure to check off the VFS actions in the ticket, including:
[Synchronous reviews]: If needed, add any additional VFS attendees, including accessibility and POs, to the invite on your calendar.
[Asynchronous reviews]: No meeting will take place. Governance team members will provide feedback by EOD the next business day following the meeting.
Link all artifacts ONLY in the Midpoint Review artifacts section at least two days before the scheduled Midpoint Review. Do NOT add artifacts to the Comments section.
Specify which pages in the prototype are included or excluded from the review.
Note: We will reschedule the review if you do not provide artifacts or we don't know which pages are included in the review at least two days prior. Please let us know if you have any questions.

**SR**
Your review for 1:30pm ET, Thursday, March 21, 2024 is confirmed. Please link all artifacts at least four days before the scheduled Staging Review. Do NOT add artifacts to the Comments section.
Note: We will reschedule if you do not provide artifacts in the review at least four days prior. Please let us know if you have any questions.

**Comment by erinrwhite** [comment]
@allison0034 all the drafts are looking good! I had one small question about async midpoint reviews. We can definitely delete the [Zoom information for Collab Cycle meetings](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2454585540/Zoom+information+for+Collab+Cycle+meetings) page too.

**Comment by erinrwhite** [comment]
Also, +1, no changes needed to Slack workflow notifications.

**Comment by allison0034** [comment]
@erinrwhite this is ready for a final review. Please test both the [DI/MPR](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review?month=2024-03) and [Staging review](https://calendly.com/collaboration-cycle/staging-review?month=2024-03) Calendly links to make sure Zoom shows up and if you click the link it opens Zoom.

[Collaboration Cycle Calendly guide](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2017034292/Collaboration+Cycle+Calendly+guide)
[Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
[Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
[Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)

**Comment by erinrwhite** [comment]
It's showing up! Looking good.

A few things:

- [ ] Can you update our instructions on both of the scheduling pages to reference the exact slash-commands teams will need to use, instead of the older generic one? I also see that on the staging review scheduling page, we say we need 2 days' notice but we actually need 4.
<img width="447" alt="Screenshot 2024-03-04 at 11 33 04 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e404bc1a-6f59-4094-9b53-d7e06704d52d">
<img width="445" alt="Screenshot 2024-03-04 at 11 43 58 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e4ddc6d4-fe8a-4ff4-b7ee-33257a6a6150">

- [ ] On the staging review confirmation emails all the zoom info runs together into one line
<img width="832" alt="Screenshot 2024-03-04 at 11 45 47 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e8ba76ff-6a81-4903-9ff7-dda4428ae99c">

- [ ] Is it possible to not show the full zoom link on the Calendly reservation web page? I am worried that folks will find the link on the open web and then show up and zoom-bomb us.

**Comment by allison0034** [comment]
@erinrwhite where can I find the exact slash commands?

**Comment by allison0034** [comment]
@erinrwhite well duh... my brain has the Mondays : ( I was able to change the staging review statement but not the DI/MPR, there is a character limit. I think this is ready for a final review!

**Comment by erinrwhite** [comment]
Okay, one other small thing while we're updating Calendly:

Can we standardize the event titles and descriptions? No real preference let's just be consistent.

For DI or MPR, 
- the event title is "Design Intent" or "Midpoint Review"
- description contains the name of the touchpoint, the collab cycle ticket title, and **not** the URL

For SR,
- the event title is whatever the user lists as the collab cycle ticket title
- description contains the URL and title of the collab cycle ticket, but not the touchpoint name

**Comment by allison0034** [comment]
@erinrwhite yes! Screen shots below...

- <img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3l4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16e8369d98ee13872d2652f785dba7eab14705a8/Screenshot%202024-03-05%20at%208.45.15%E2%80%AFAM.png" alt="Screenshot 2024-03-05 at 8.45.15 AM.png" />
- <img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09a76e46b5c6d5092a066963ce4d111a9e28aab4/Screenshot%202024-03-05%20at%208.47.53%E2%80%AFAM.png" alt="Screenshot 2024-03-05 at 8.47.53 AM.png" />

**Comment by erinrwhite** [comment]
@allison0034 perfect! I think this one is good to close.

**Comment by allison0034** [comment]
@shiragoodman it may be a good idea to just go ahead and do the new Zoom meeting and I can update. Contacting support sounds annoying and time consuming : (

**Comment by erinrwhite** [comment]
@allison0034 +1 to a new event!

**Comment by shiragoodman** [comment]
Ok awesome. I created a new Zoom meeting. Looks like they have a new feature where you can schedule an event to be recurring and the occurrence to have "no fixed time" meaning it can take place at any time. Sounds like a perfect fit for what we need. I did have to choose an initial date/time, so that's why it still shows Monday at 3:30pm ET.

Invite is below, as well as a couple screenshots showing the settings I chose. Let me know if you need any changes made.

```
Shira Goodman is inviting you to a scheduled Zoom meeting.

Topic: Collaboration Cycle Meeting - Monday at 3:30pm ET
Time: This is a recurring meeting Meet anytime

Join Zoom Meeting
https://oddball-io.zoom.us/j/84098072750?pwd=W9aUZIxaYC02ge7ufKWInTATDpznM8.1

Meeting ID: 840 9807 2750
Passcode: 580205

---

One tap mobile
+13052241968,,84098072750# US
+13017158592,,84098072750# US (Washington DC)

---

Dial by your location
• +1 305 224 1968 US
• +1 301 715 8592 US (Washington DC)
• +1 309 205 3325 US
• +1 312 626 6799 US (Chicago)
• +1 646 876 9923 US (New York)
• +1 646 931 3860 US
• +1 689 278 1000 US
• +1 719 359 4580 US
• +1 253 205 0468 US
• +1 253 215 8782 US (Tacoma)
• +1 346 248 7799 US (Houston)
• +1 360 209 5623 US
• +1 386 347 5053 US
• +1 408 638 0968 US (San Jose)
• +1 507 473 4847 US
• +1 564 217 2000 US
• +1 669 444 9171 US
• +1 669 900 6833 US (San Jose)

Meeting ID: 840 9807 2750

Find your local number: https://oddball-io.zoom.us/u/kcLdrlKcgA
```

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/a9267c6d-0cf5-44a9-abfc-ae75cab1cc7f)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/aabced3b-2490-4511-a872-b9dd1b0b0e5e)

**Comment by shiragoodman** [comment]
ok i also updated the title to "Collaboration Cycle Meeting" - no more "Monday at 3:30pm ET" included in the title.

**Comment by allison0034** [comment]
@erinrwhite I updated the invite and the Calendly guide with the new Zoom. Want to give it one more check?

**Comment by erinrwhite** [comment]
@allison0034 tested creating new events and doublechecked the Calendly page. All clear from here!

**Comment by shiragoodman** [comment]
looks like the staging review Brian just scheduled is still using the old Zoom, but nbd. Thank you both for making sure this is right!

**Comment by erinrwhite** [comment]
@shiragoodman Yeah, I noticed their event was on the calendar when I was testing the newer zoom link scheduling flow. I think they scheduled during that brief window that we had the old link in there. Should still work, though!
