### ISSUE TITLE
[CST] SME interviews to refine content for accuracy (time estimates and process steps)

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#77186]
## Value Statement
**_As a_** designer trying to clarify the claims process for Veterans 
**_I want to_** work with disability claims subject matter experts to create accurate time estimates and descriptions for each claim steps 
**_So that_** I can provide Veterans with accurate time frames and description for steps and set appropriate expectations 

---
## Background Context

As result of the [Claim Contextualization research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-10-Claim-Contextualization/research-findings.md), we've learned that Veterans loved the idea of having time estimates as part of their claim in the claim status tool. It helped set expectations on how long an individual step will take. A few Veterans said this would reduce their need to contact VA with questions regarding length of time their claim will take to receive an update. With that being said, we have to ensure the time estimates we provide are as accurate as possible if Veterans will rely on this information to understand the present state of their claim. 

**Note**: We suspect this ticket might pass through multiple sprints due to scheduling constraints. 

## Design

**Figma links**

[Prototype](https://www.figma.com/proto/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=362-14557&t=gtvM5EjgNnHpUu3G-1&scaling=scale-down&page-id=362%3A14273&starting-point-node-id=362%3A14421&mode=design)

**Research findings**

- [Share out Slide deck](https://docs.google.com/presentation/d/1b2CWI4cUN7ZmPUE_XnXZuV-TivTjX6b05ymPnFyOXgw/edit?usp=sharing)
- [Research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-10-Claim-Contextualization/research-findings.md)
- [Content source of truth](https://docs.google.com/document/d/1r-LqmULHpBCQbk7-lYpsu2JvCC3twU4zC9zOqIf9N2w/edit#heading=h.wpg3kqtm4tzm)

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Possible SMEs to meet with
- Andrew Grey (* Our lead POC for CST)
- David Reis (* Recommended by Andrew)
- members of the legal team

## Design
- Add here

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Understanding that we have average time for the entirety of the claim, do we have a record of times for each step?
- in step 6, "your claim can be sent back to the rater in step 5
- in step 5 we say the final check is completed but that may not be true
- where we say "your claim has returned to this step.... can we put a date there? As to say, "your claim has returned to this date on May 12, 2024?"

## Tasks
- [x] Schedule meetings with the appropriate SMEs who can validate times and description 
- [x] create a directory to include record sessions and notes from the sessions
- [x] Update the content based on conversation

## Definition of Done
- [x] Create a deliverable to report times estimates from different SMEs and what our final judgement will be.

## Acceptance Criteria

- [x] Include accurate time estimates if possible (including those who had to repeat steps)
- [x] The content should accurately reflect the claims process.

**Comment by HeatherWidmont** [comment]
Discussing with Andrew Gray in the BMT/VBA weekly sync today

**Comment by HeatherWidmont** [comment]
Will discuss it with Andrew this Friday during the weekly sync. Gary will be OOO but has already set up the Mural board for Skyler to drive the conversation. Meeting will be recorded for Gary.

**Comment by HeatherWidmont** [comment]
Minor design & content updates to make in advance of Friday's meeting. 

After Friday's meeting Gary & Skyler will discuss if additional SME conversations need to happen with anyone or if this will be enough

**Comment by HeatherWidmont** [comment]
Minor design & content updates being tracked here: #77207

**Comment by HeatherWidmont** [comment]
Deeper dive with Andrew scheduled for Thursday

**Comment by HeatherWidmont** [comment]
@uxgary met with Laura who made some content updates, talked through some of the changes. Prepping for Thursday's meeting with Andrew

**Comment by SilkeDannVA** [comment]
@uxgary to scrub through the video and incorporate feedback

**Comment by SilkeDannVA** [comment]
Have the mural board with Andrew's responses. Video not yet found. Waiting for Heather's return.

**Comment by uxgary** [comment]
Completed the [session report in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2023-10-Claim-Contextualization/refinement-workshop-for-claim-contextualization.md); it contains answers to our opens questions and clarifies what happens at each step of the claims process. 

Additionally, I've included links to the session records, murals boards and other artifacts relevant to this work.
