### ISSUE TITLE
Stamp 686/674 pdfs with errors

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77195]
## Issue Description
_As a human processing 686/674 claims VA.gov set for manual processing, I need to understand why the claim was rejected by RBPS. VA.gov will stamp the pdfs produced by online 686 or 674 submissions with the error that caused the claim to be sent down the backup submission pathway (Central Mail)._

Needed:
- Language to be stamped on the pdf for each error
- Confirmation of stamp location

---
## Tasks
- [ ] Add stamp to 686 pdf that outlines the error(s)
- [ ] Add stamp to 674 pdf that outlines the error(s)

## Acceptance Criteria
- [ ] 686 pdfs set to manual processing include stamp of error(s)
- [ ] 674 pdfs set to manual processing include stamp of error(s)
---

**Comment by steele-lm** [comment]
Closing this ticket as it was never a fully formed request and other reporting mechanisms cover this info.
