### ISSUE TITLE
Remove file number/ssn logic

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77191]
## Issue Description
_Currently, in cases where a Veteran's file number does not match their ssn or their spouse's file number does not match their ssn, we display an alert to the Veteran directing them to contact the VA (see [#25452](https://github.com/department-of-veterans-affairs/vets-website/issues/25452)). After discussing with RBPS team (Linda Ciston) and OCTO stakeholders, it was decided to remove this logic check and alert and send the claim down the backup submission pathway (Central Mail) to be remediated by a human._

Follow-on work will be done to stamp ticket with the reason for the claim failure (file number and ssn do not match) in #77195 .

Important: The file/ssn mismatch error should still be logged, so it can be tracked for future root-cause remediation.

Research by Thomas Blackwell found that NOONE MPI data seems to be the culprit. While investigating errors, he noticed that MPI BIRL ID, BIS SSN, and BIS File Number all match. MPI SSN is the only difference.

---
## Tasks
- [ ] Remove logic in 686/674 online form flow that checks for matching file number and ssn (for Veteran and spouse)
- [ ] Retain logging of these errors
- [ ] Route claim directly to Central Mail for manual processing

## Acceptance Criteria
- [ ] Veteran no longer sees alert if file number and ssn do not match
- [ ] Claim is sent down backup submission pathway (Central Mail)
---

**Comment by steele-lm** [comment]
@tblackwe I created the this ticket to remove the file/ssn logic check. Let me know if any additional detail needs to be added. I also created #77195  to stamp the error(s) that caused the pdf to be set for manual processing to 686 and 674 pdfs.
