### ISSUE TITLE
Tear down utility-clamav-updater

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#77205]
## Summary

Previously, clamav's private mirror, utility-clamav-updater S3 bucket. This has been replaced with the [Sync Database to S3](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/actions/workflows/s3_sync.yml) github action in the vsp-infra-clamav repo. All clamav updater references and files should be removed from the [devops](https://github.com/department-of-veterans-affairs/devops) repo.

## Task
- [x] Delete ansible/build/roles/vets-api/deps/clamav/tasks/main.yml
- [x]  Delete ansible/build/roles/vets-api/deps/clamav/templates/freshclam.conf.j2
- [x]  Delete ansible/Dockerfiles/clamav-updater/freshclam.conf
- [x]  Delete ansible/Dockerfiles/clamav-updater/Dockerfile
- [x]  Delete ansible/deployment/config/vets-api/scan.conf.j2
- [x]  Delete ansible/Jenkinsfiles/clamav-update
- [x]  Remove "utility/clamav-updater" references in ansible/deployment/config/jenkins-vetsgov/seed_job.groovy
- [ ] Delete [Jenkins clamav updater job](http://jenkins.vfs.va.gov/job/utility/job/clamav-updater/) -- this has to be done last

**Comment by RachalCassity** [comment]
Devops PR is in draft. Will merge in a few days after GHA has successfully ran for awhile.
