### ISSUE TITLE
DevOps Support Training - Sprint 48

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#77216]
## Description
Based on instructions provided via Slack, please demo and record the proper process for DevOps T2 Support to effectively perform Offboarding requests, and PR Reviews

## Tasks
- [ ] Demo & Record Offboarding request process
- [ ] Review PR Review process/progress

## Acceptance Criteria
- [ ] All tasks have been demoed
