### ISSUE TITLE
[FE] My VA: audit bespoke components

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#77211]
## Background
After reviewing components in preparation for the v3 uswds component migration we decided it would be beneficial to review all of My VA's "bespoke" components to see what we could actually convert to v3 uswds components. This would give us more consistency and scalability.

## Tasks
- [x] Perform an audit of all “bespoke” components specific to My VA (non-v1 or v3)
- [x] Evaluation of those components to see if they can be converted to a VA design system component
- [x] Conduct side by side comparison 
- [x] Review with Matt

## Acceptance Criteria
- [x] We have a list of components that we think we can leverage from design system that we aren’t currently using

## Resources
- [design system roadmap (slack thread)](https://dsva.slack.com/files/U03740NA3E3/F06MF8GHABZ/design_system_fy23-24_roadmap_2024-03-04_22-50-24.png)

**Comment by DanielMiller-agile6** [comment]
dropping to 2 to account for some work so far. still want to talk with Allison o some things and look over a few more dashboard components first.

**Comment by DanielMiller-agile6** [comment]
we discussed audit findings in working session. new tickets will be created to address issues. Copy of report:

# MyVA Design System Styles and Component Audit

This doc identifies a few components, patterns, and/or styles within MyVA and compares them to VADS.  These are just the top few things I found that seemed like good short-to-mid term improvements.  For the most part, I think MyVA is already very well aligned with existing VADS standards.  These are mainly opportunities I found where we might be able to leverage more functionality from VADS, or perhaps contribute some of our code or styles.

## CTA Links in Cards
Priority: Medium-Low
Effort: Low

<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9b85ab27f123d8dbf1942c1aee26f6054d039b2/Screenshot%202024-04-04%20at%203.56.22%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 3.56.22 PM.png" />

These links inside of the various va-card elements we use on MyVA could be aligned more closely with VADS.  We are already using the global link styles here, but we could consider using the custom va-link element.  We may also need to use a different icon here going forward, since this is currently using a FontAwesome icon, which may be changing to use icons more similar to USWDS (which was forked from Material Icons).

Another option could be to use the “Action Link” from VADS here, which looks a bit different, but serves a similar purpose.  These links also use FontAwesome, but they might get updated for us whenever the DS team updates the patterns and components with future icons.

Storybook Docs for Link:
https://design.va.gov/storybook/?path=/docs/components-va-link--default

Storybook Docs for Link Action:
https://design.va.gov/storybook/?path=/docs/components-action-link--primary

## Section Links
Priority: Medium
Effort: Medium-High

<img width="1237" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d77fde2660d57a5cd582c9197e75744803142e5/Screenshot%202024-04-04%20at%203.57.52%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 3.57.52 PM.png" />

These section links appear to use custom MyVA styles and VADS util classes, even though this pattern is documented in the “Link - Collection” section of the design system documentation pages.  However, this pattern doesn’t appear to exist in Storybook documentation.  Maybe there’s an opportunity to check with the DS team here and see if we can help graduate this pattern into DS code and storybook docs. These links also use Font Awesome icons, so it could be a good time to revisit this anyhow.


VADS Docs for Section Link: https://design.va.gov/components/link/collection#section-links


## CTA Links in Benefit Application Draft Cards
Priority: N/A
Effort: N/A

<img width="1644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f324968b3703f7ce7c8c2de982c282aef04a6a2/Screenshot%202024-04-04%20at%2011.07.20%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 11.07.20 PM.png" />


This is not really an issue with these CTA links, but these are a bit different than the CTA links that show in some other cards on the MyVA page.  These ones look nice and have a subtle on-hover icon animation, so maybe these link styles could be reused across the board for MyVA, or added to the DS as a reusable Card CTA Link style.


## VADS Cards
Priority: Low-Medium
Effort: High

In VADS, a “Card” is basically just a visual wrapper with padding and optional border applied.  In USWDS, a “Card” has a lot more semantic meaning built into the pattern, so maybe we can look into this with the VADS team?  Also maybe an opportunity to get involved more with VADS & USWDS communities.

VADS Storybook Docs for Card: https://design.va.gov/storybook/?path=/docs/components-va-card--default

USWDS Docs for Card:
https://designsystem.digital.gov/components/card/
