### ISSUE TITLE
[Research] Dot Indicator Research: Prepare research materials pt 2

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#77217]
## Background
We need to prepare the materials that will be used to collect feedback during the dot indicator research study - specifically line up note-taking support and invite folks to observe.

## Tasks
- [x] Recruit note takers
- [x] Share schedule with team and other interested partners to allow them to join (AJ can assist with this too)

## Acceptance Criteria
- [x] All materials/resources needed to conduct research sessions are ready

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** Any team member
- **_How can this work be validated?_** ensure materials are prepared
