### ISSUE TITLE
Conduct a Parameter Audit for 686 Submission

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7722]
## Goal
We need to compare the optional fields we can see in the backend with what is being used by the frontend (according to the form) in order to ensure that we are only working with the necessary fields.

## Considerations
- Depending on how many areas or workflows, this might be broken into smaller sections
- This should involve some discussion with the FE
- While this may not have a ton of cognitive overhead, there is a fair amount to address
- Keep a running log of metadata that might need to be confirmed with stakeholders
- Additional pension question might have an impact

## Tasks
- [x] Make note of the optional fields that are not being used
- [x] Ensure those fields are not interfering with the submission process

## Acceptance Criteria
- [x] Fields are in alignment with what is required, optional, and on display on the frontend
