### ISSUE TITLE
Determine components in injected VA header & add sitewide public websites team as code owners

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#77221]
## Background Context

The sitewide public websites team should be added as a codeowner of _all_ components that are used within the injected header. An incident occurred where a change was made to `src/platform/forms/save-in-progress/FormSignInModal.jsx` to update the React Modal into a v3 `va-modal` web component. Unknown to the pull request reviewers, this component is used in the injected header. This caused a problem with the header that could only be detected locally by [running a local proxy rewrite](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) (instruction linked in current pull request)

## Tasks
- [ ] Build a list of all components that are used in the injected VA header
- [ ] Add the path of each component to the CODEOWNERS file, listing the sitewide public websites team as a reviewer
- [ ] Add a comment to each component indicating that it is used in the injected VA header, restrictions and testing requirements
- [ ] Ensure the sitewide public websites team is aware of these changes

## Definition of Done
- [ ] Changes made to indicated components add sitewide public websites team as a reviewer
- [ ] Post these changes in DSVA #vfs-engineers channel to increase awareness

## Acceptance criteria
- [ ] All tasks complete
