### ISSUE TITLE
[UX][Design] SPIKE: Appointment Detail Page UI Discovery

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#77232]
Based on [notification pattern discovery](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=246%3A6732&mode=design&t=LnjzSxVP33av3kUQ-1), we need to determine the answers to our [remaining questions](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=246%3A6732&mode=design&t=LnjzSxVP33av3kUQ-1) for how the Appointment Detail Page UI would work if possible action and status scenarios are incorporated. 

Run solutions by CIE UX and platform design folks.

**Pattern evaluation and review** 
- For alerts and statuses, which pattern better supports the number of different alerts and statuses we might have at any given point?

**Status UI**
- What status UI versions are permitted by platform?
- Unified version of status approved for appointment list - also ok elsewhere?

**Information sections within card**
- When/where should new sections be used? (Ex: should AVS and travel sections always be present, even when contents not available? Or appear only when information has become available?) 
- How do we determine what warrants a new section? (Ex: Clinical Orders could be a section that appears for Past Appointments)
- **Assumption**: appear when needed - following pattern already used in detail card where, depending on situation, sections are not always present

## Tasks
- [ ] Solidify pattern options and discovery background for Appointment Detail Page UI to share
- [ ] Sync with Appointments designers 
- [ ] Check with a11y specialists for any accessibility concerns
- [ ] Iterate on options based on feedback
- [ ] Share resulting pattern(s) with Kristen
- [ ] Create follow-up tickets (if needed)

## Acceptance Criteria
- [ ] Received and implemented feedback from Appointments designers
- [ ] Received and implemented a11y feedback
- [ ] Pattern option(s) have been reviewed by appropriate stakeholders (Kristen)
- [ ] Follow up tickets have been created (if needed)

**Comment by benbrasso-agile6** [comment]
@loripusey @cgednalske I thought this ticket was related to this Epic: Cross-Product Discovery - Complete Multiple Tasks

**Comment by loripusey** [comment]
Changed it, but we determine last sprint that we were done with Multiple Tasks and we closed the epic, does this mean that we are not done with the discovery work?

**Comment by benbrasso-agile6** [comment]
Could have been a miscommunication. I feel like it's part of Multiple Tasks, but I'll wait for @cgednalske to chime in.

**Comment by cgednalske** [comment]
Yes, this is part of Multiple Tasks. Is Kristen ok with us moving forward with this if we're done with the rest of this Epic for now? Last she mentioned was that we pause on this after some of that initial discovery.

**Comment by cgednalske** [comment]
Based on the priorities meeting, a good direction would probably be to share the discovery so far with Peter Cierra, and Melissa, then continue iterations based on their feedback. There's not much else to do until we meet with them. 

If that sounds good, I can change the tasks and AC.

**Comment by benbrasso-agile6** [comment]
Going to side-chat you real quick, Christina...

**Comment by benbrasso-agile6** [comment]
K, we synced. Go ahead and update and point please :)

**Comment by cgednalske** [comment]
Updated the tasks and AC 👍

**Comment by cgednalske** [comment]
Ready for validation @benbrasso-agile6 @loripusey @zach-park 

[Appointment details page discovery Figma file](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=246%3A6732&mode=design&t=JR4gXfbq2iH493jE-1)

**Discovery recap:** 

- This discovery explores different approaches for handling many appointment tasks. 
- All options are based on previous design direction from past appointments travel design discovery/work. 
- We met with Appointments UX to go over these, with most interest shown for the 3rd section (the section that includes three slight variations around "an appointment history/timeline"). 
- There were also a few follow-up questions documented at the bottom. 
- Check-in and Appointments will keep this on their radar as the Appointments detail page undergoes other changes.

**Comment by benbrasso-agile6** [comment]
LG TY
