### ISSUE TITLE
[CST] Decision letter available for open claim

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#77240]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to see a decision letter if it's available even if my claim is still open
**_So that_** I have access to my benefits information as quickly as possible

---
## Background Context

Sometimes a decision letter is available for certain contentions in a claim, even if the overall claim is still open (usually occurs if contentions were deferred). 

We had a design for this in the old version of the UI. We need to design and implement this for the V2 detail pages.

## Design

[FIGMA](https://www.figma.com/design/I91cBAB7dQD7AKayKO1JkX/CST---Decision-Letter-Available-for-an-Open-Claim?node-id=120-4655&t=CvAGl4qKupWF4LP8-4)

**Proposed UI**
<img width="641" alt="Screenshot 2024-06-21 at 3 16 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/523707a8-8573-4c2c-b599-bc9330c5f6de">

**Current UI**
<img width="399" alt="Screenshot 2024-02-27 at 7 24 16 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/0fed7768-1e27-45ae-9efd-9b106076b629">

## Engineering 

[From Peri](https://dsva.slack.com/archives/C056854SVT8/p1718980331020679?thread_ts=1718913175.400669&cid=C056854SVT8): "There is currently not any logic on the Status Tab that shows a link to the claims letter page or mentions a decision letter when A claim is opened OR when a claim has a decision letter sent.

The specific logic that we use to determine if a claim is opened is a helper function called `isClaimOpen()` that is passed in the following claim fields `claim.attributes.status` and `claim.attributes.closedDate`. The claim is considered opened as long as the status is not `COMPLETE` and the `closedDate` is null.
The specific logic that we use to determine if a claim has a `decisionLetterSent` is by looking at the claim field `claim.attributes.decisionLetterSent`."

## Out of scope
- Add here

## Open questions
- If possible we should apply this to all claim types that have decision letters in Claim Letters page. Is that feasible?

## Tasks
- [ ] _If a claim is open (as defined above) and a decision letter HAS been sent (as defined above), show the proposed design on the Status page for the claim_
- [ ] _Show the new alert until the claim is closed, at which point the standard close claim UI will replace it_
- [ ] _If a second decision letter becomes available, stack the second (newer) alert on top of the first so that Veterans can see that they have multiple decision letters available. If a third becomes available, place the third on top of the stack, and so on._
- [ ] Update `vets-api-mockdata` so that we have a claim that is opened and has decisionLetterSent: true

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Claims that are open and have a decision letter sent show the proposed design_
- [ ] _The "You have a decision letter for part of this claim" alert is shown until the claim is completely closed, at which point the [standard closed claim state](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?node-id=1149-11003&t=LVj5dOdQWgAy7efl-4) replaces it_
- [ ] vets-api-mockdata has an opened claim with a decisionLetterSent: true

**Comment by jacobworrell** [comment]
veterans who have decision letters for open claims can see them in the claim status tool claim letter section.

**Comment by skylerschain** [comment]
@jacobworrell True but they won't know to go there to look for it without some sort of notification. I think it's worth keeping a ticket open to add that.

**Comment by jacobworrell** [comment]
@skylerschain I believe they will see that alert for an open claim because the decisionLetterSent value will be True.

**Comment by jacobworrell** [comment]
@skylerschain a partially decided claim will show the same message as a closed claim directing them to the claim letters section of CST. Jerek and I investigated this and the message will show up for a claim that is still open. If you'd like a different message to show for partially decided claims, that might make sense, but I think the value prop for this ticket would need to change.

**Comment by skylerschain** [comment]
The value prop is the same:

_As a Veteran I want to know that I have a decision letter available for part of my claim even if the claim is still open so that I have an accurate understanding of my claim status_ 

Below is the message we show for closed claims, and this language definitely makes it sound like the claim is closed, which in this case it's not. So we need a different version for when some contentions are still being decided. The spec is [here](https://www.figma.com/design/I91cBAB7dQD7AKayKO1JkX/CST---Decision-Letter-Available-for-an-Open-Claim?node-id=109-4244&t=WLAUKzXFiqR6IHqC-4).

<img width="518" alt="Screenshot 2024-08-20 at 11 02 19 AM" src="https://github.com/user-attachments/assets/9be3cac1-690f-42b1-9eb9-00548ed6b50d">

**Comment by jacobworrell** [comment]
@skylerschain please update mock with correct position of alert.

**Comment by skylerschain** [comment]
Removed this from Tasks:
- [ ] _If a second decision letter becomes available, stack the second (newer) alert on top of the first so that Veterans can see that they have multiple decision letters available. If a third becomes available, place the third on top of the stack, and so on._

Reason: As [described in the spec](https://www.figma.com/design/I91cBAB7dQD7AKayKO1JkX/CST---Decision-Letter-Available-for-an-Open-Claim?node-id=152-2414&t=KmH7CH9QSoNP4OBH-4), there is no signal differentiation between when the Veteran has one decision letter and claim is open and when the Veteran has multiple decision letters and the claim is open. So UI treatment will be the same in both cases.

**Comment by jacobworrell** [comment]
@jerekshoe please review so we can merge

**Comment by jerekshoe** [comment]
@skylerschain The last sentence in the alert mentions that the copy of the decision letter in the mail should arrive within 10 days after the claim is closed, but in this case the claim isn't closed yet (and it may not be closed for a while). Should we have changed the copy there?

**Comment by skylerschain** [comment]
@jerekshoe Good catch. 

@samcoforma Can we update the last line of the [alert](https://www.figma.com/design/I91cBAB7dQD7AKayKO1JkX/CST---Decision-Letter-Available-for-an-Open-Claim?node-id=151-1750&t=Gok4CNsuDebWvDqr-4):

Before: 
> We’ll also send you a copy of your decision letter by mail. It should arrive within 10 days after the date we closed your claim, but it may take longer.

After: 
> We’ll also send you a copy of your decision letter by mail. It should arrive within 10 days, but it may take longer.

**Comment by skylerschain** [comment]
Hey what's the status of this ticket? Just came across it again and it's been in Code Review for a while.
