### ISSUE TITLE
Design | EDU CH33 Changes | Research Plan for UAT

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#77250]
## Background 
We need to test the post-migration UI with veterans that have Ch33 benefits, Ch33 & C&P, and just C&P. We want to ensure that users data saves properly for all three cases.

EDIT: we must validate using the dev tools that the API control flags are correctly rendering 

## Important Artifacts 
- [outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/ch33-bdn-corpdb-migration) 
- [QA Tests](https://docs.google.com/spreadsheets/d/1rOD8w0YNTlfbefVK7t2RsWoYK_ui1gTkVhCXlJE5VDg/edit?usp=sharing)
## Tasks 
- [x] Write research plan
- [x] Review/share with PM & PO

## Acceptance Criteria 
- [ ] Plan is ready to submit and kick off the research

**Comment by pamela-drouin** [comment]
@clantosswett & @mtcA6 I posted the [draft research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2024-04-direct-deposit-ch33-UAT/research-plan.md) -- would love for you both to take a look.

I'm looking for specific feedback around the following:
- The OCTO-DE objective: I couldn't find anything in the existing documentation that mentioned this, so additional POV would be great!
- Research goals -- am I missing anything?

**Comment by mtcA6** [comment]
@pamela-drouin this work would, I think, tie into:

OKR #1 is the following:
Objective #1: Work collaboratively across the health and benefits portfolios on high-priority FY2024 initiatives.
KR: At least 50% of our initiatives should support the major initiatives in the health and benefits portfolio.

Unfortunately this maintenance work that has been sort of foisted onto us. I'd assume the deprecation of the legacy payments system falls into a high priority 2024 (or longer) initiative.

**Comment by mtcA6** [comment]
Under the research questions it's important the API return the expected results. Not sure how you want to phrase that but it's critical that we see flags in the api response turned on or off based on their actual benefits. 

we MUST see these flags behaving as expected in the dev tools in order to effectively ensure the new backend has been structured correctly. 

@tpharrison did i phrase that clearly?

**Comment by tpharrison** [comment]
Yes.  We'll need to use the browser's developer tools to confirm that the control flags are properly set and align with our expectations.

**Comment by pamela-drouin** [comment]
Thanks @tpharrison and @mtcA6 -- that's something someone might have previously mentioned but I didn't see it in the initiative outline. I'm hearing this at just the right time: both to update the research plan, but more importantly, when I start the convo guide tomorrow! 😀

**Comment by tpharrison** [comment]
@mtcA6 @pamela-drouin Currently, when a user updates their direct deposit info, they receive an email confirmation.  The email confirmation will state whether the account updated was for C&P or edu benefits.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/653787/9a11ba50-85a5-4e60-80d8-0ba01642d522)

What do we want to show if a user has both C&P and edu benefits?  Should we just not specify?  Example:
> We’ll use your updated information to deposit any benefits you may receive.

**Comment by mtcA6** [comment]
I think we need to have that changed so it doesn't reference which item was updated.

**Comment by tpharrison** [comment]
You mean just remove it across the board?

**Comment by mtcA6** [comment]
I think so. The form won't distinguish between EDU or C&P in the UI, it'll say "Bank Information"
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/f3f043ee-95df-4016-8613-14be8426455d)
I don't think we need to distinguish in the email confirmation which benefit the update is for. 

I've updated the description of #77516 and tagged that so we talk about it during refinement

**Comment by pamela-drouin** [comment]
@mtcA6 I updated the research plan -- will you double-check the revised research goals and let me know if they're good to go?

**Comment by pamela-drouin** [comment]
@mtcA6 carry forward one point - just have one update to make to this and it'll be complete.

**Comment by pamela-drouin** [comment]
@mtcA6 this is now updated! Please let me know if there is anything else you would like changed. If not, this is ready to be closed. I'll leave it open for now.

**Comment by mtcA6** [comment]
The updated research goals look great! Closing this out!
