### ISSUE TITLE
AE Sprint 19 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7725]
## Order of priorities
1. Address validation: Final tickets
2. Profile 2.0: Conduct sessions and summarize research (If time, start on content review/IA work)
3. Profile 2.0: Build continues

###  Address validation
- [x] Change address update endpoint to use iso3 country code #6046
- [x] Stop using country name for VA profile contact information endpoint #5591
- [ ] Follow up with veterans to see if this feature resolves their issues saving addresses #6012 (Samara)
- [x] Request 508 Office Review #7735
- [x] Full Accessibility & 508 Office Audit [Address Validation] #8006

#### PM
- [x] Profile 2.0 epic grooming/What comes next with profile 2.0? #7222

#### Design
- [x] Conduct research sessions #2587
- [x] Create report and tickets #2588

-----------------------------------------------
[Design] Profile 2.0: Determine if there is any other content/links that needs to be updated as part of Profile 2.0 #5528
[Design] Profile 2.0: Review Sign in FAQ for any links/content that need to be updated #5527
[Design] Profile 2.0: Review Change your address content page for any links/content that need to be updated #5524
[Design] Profile 2.0: Review My VA for any links/content that need to be updated #5522
[Design] Profile 2.0: Review Direct deposit content page for any links/content that need to be updated #5525

#### Dev
- [x] Make reusable Profile 2.0 info table component #7554
- [ ] Account security #5356
- [ ] Direct deposit #5355
