### ISSUE TITLE
Complete New vets-website Runner Design doc

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#77253]
## Issue Description
We need to draw up a design doc to solicit feedback for our effort to overhaul the GHA runners for the front end. This should contain what our goals are as well as details of how we plan to build the solution from a technical viewpoint. This should be shared out at a minimum with the devops COP for feedback.

---
## Tasks
- [ ] Fill out goal we are trying to accomplish, in detail, with the runner overhaul.
- [ ] Fill out the planned technical approach to solving this issue
- [ ] Share document out for feedback with a larger audience
- [ ] Adjust goal/approach as necessary.
- [ ] Fill in details of solution in [this ticket](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/77254)

## Acceptance Criteria
- [ ] A design doc has been vetted by SMEs and we have an approach to move forward
- [ ] The ticket to create the runners contains all necessary details.

**Comment by JoeTice** [comment]
[Design document for approach to runners](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2982281229/Refactor+Self-Hosted+GitHub+Runner+Configuration)

**Comment by JoeTice** [comment]
Calling this document closed
