### ISSUE TITLE
[DevOps] Nate Douglas needs permission to administer the CMS service accounts.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77269]
## User Story
As a DevOps engineer, I need permission to administer the CMS service accounts so that, uh, I can administer them.

## References
- #74870
- https://dsva.slack.com/archives/C02G6AB3ZRS/p1706129749435889
- #77015
- #75443
- https://yourit.va.gov/va?id=ticket&table=sc_req_item&sys_id=e6ae1ad11b3cc2d4e9ac0dc2604bcb9d

## Tasks
- [x] [DevOps] Get GFE
- [x] [DevOps] Figure out what ePAS is and get on it
- [x] [DevOps] Request `vaec-cms` (`432896750513`) AWS access (`AWS-432896750513-adfs-project-administrators`)
- [x] [DevOps] Verify `vaec-cms` administrator access.
- [x] [DevOps] Request `vaec-cie` (`239516274380`) AWS access (`AWS-239516274380-adfs-project-administrators`)
- [x] [DevOps] Verify `vaec-cie` administrator access.

## Acceptance Criteria
- [x] I have the **powah** to administer the CMS service accounts.

**Comment by ndouglas** [comment]
Spoke to Tyler Mann and he straightened me out. I requested permission to the two groups I need.

**Comment by ndouglas** [comment]
Verified that I'm a member of the appropriate groups and can perform these tasks as needed.
