### ISSUE TITLE
Update runner labels in vets-website CI/Daily Deploy to use new runners

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#77260]
## Issue Description
Once the new runners are ready to go, the CI will need to be updated to use them appropriately. Each job declares a label of a runner to use and we'll need to make sure they're all updated to use our new, improved runners.

---
## Tasks
- [ ] Update runner labels to match new runners in the Daily Deploy and CI workflows.
- [ ] Ensure that all relevant workflows still run without error.

## Acceptance Criteria
- [ ] Both the CI and Daily deploy workflow use our new runners.

**Comment by JoeTice** [comment]
SPRINT 49 UPDATE - Work was done, but had to be reverted due to a deployment failure, anticipate this work will be finished in SPRINT 50

**Comment by CBonade** [comment]
This effort is cancelled due to security risks raised by GitHub. Will be pivoting all workflows off self-hosted runners in the near-future. Good to close this ticket.
