### ISSUE TITLE
[DevOps] Discovery on renaming `*.tfstate` files that are really `*.tf` files in `checkin-devops`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77268]
## User Story
~As a DevOps engineer, I want to shift `checkin-devops` Terraform projects to use an S3 backend rather than a local state backend to improve security and ability to work concurrently.~

This might be invalid; I saw `*.tfstate` files in the repository but it looks like they're `*.tf` files with the wrong extension, e.g. https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/terraform/applications/lorota/prod/lambda/lambda.tfstate . ಠಿ_ಠ 

See:
- https://github.com/department-of-veterans-affairs/checkin-devops/pull/144
- https://github.com/department-of-veterans-affairs/chip/issues/1691

As a DevOps engineer, I want file extensions to make sense so I know what is going on.

## Tasks
- [ ] [DevOps] Determine why this happened.
- [ ] [DevOps] Determine how to rename the files appropriately without causing problems.
- [ ] [DevOps] Rename the files appropriately.

## Acceptance Criteria
- [ ] Files have been renamed appropriately.

**Comment by ndouglas** [comment]
This might be invalid; I saw `*.tfstate` files in the repository but it looks like they're `*.tf` files with the wrong extension, e.g. https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/terraform/applications/lorota/prod/lambda/lambda.tfstate . ಠಿ_ಠ

**Comment by ndouglas** [comment]
Per [Slack discussion](https://dsva.slack.com/archives/C022AC2STBM/p1709138410792649) with Jeremy Britt, this was intentional:

>yeah, due to the automated pipelines applying upon merge we did this as a way to push WIP without causing real changes

>unfortunately, we were kinda in-between on some of the importing work when the contracts shifted

So this will likely need some care.

**Comment by ndouglas** [comment]
This can be dealt with as part of the AWS account migration.

**Comment by ndouglas** [comment]
This is not necessary moving forward.
