### ISSUE TITLE
Refactor Submission Process

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7726]
## Goal
Update endpoints and ensure requirements are in place for other services.

## Considerations
- List of overlapping service calls

## Tasks
- [x] Update endpoints for required services
- [x] Refactor the param formatting code to be tighter and simpler
- [x] Migrate code to new folder
    - [x] Migrate tests and point them to new folder

## Acceptance Criteria
- [x] All code migrated
- [x] All test passing
