### ISSUE TITLE
Publish DI video, kickoff research and announce changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#77282]
## User Story
Asa Governance team member, I want to execute my research plan on the DI short video so that I can measure the success of the video and apply it to other short videos for Platform.

Assignee: @rferguson13 @allison0034 
Peer Reviewer: @erinrwhite 

## Description
In tickets #75014 and #76196 Governance team recorded a short/informational overview video of the Design Intent, as well as documented a Research Plan for measuring the success of the video on Platform Website. In this ticket, we will publish the video to Platform Website, begin the research as documented in the plan and announce changes to VFS teams, as specified in the research plan.

## Impacted Artifacts
[Survey link](https://dj540s05.optimalworkshop.com/questions/6cgdagsa)

## Tasks
- [x] Publish the DI video to the DI touchpoint page. The video should be embedded into the page and not a link directing folks off the Platform Website. 
- [x] Publish a change history post
   - Shira's 2 cents: usually when we publish to the Change History page, we will also do a change announcement via Slack. I'm not sure that is necessary this time since there will be a change announcement announcing the research plan AND the video. 
   - Also with that said, I'm uncertain if we want to include the research in the Change History post on the Change History page, or if the change history post should just cover the DI video. It's up to the assignee(s) to decide.
- [x] Following the research plan, announce the research plan across Slack channels, within meetings (Design meeting, ToT) and wherever else specified.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The DI informational video has been published to Platform Website.
- [x] The research plan for measuring the success of the short/information video has begun.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@allison0034 - [Made a quick update](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2940698630/77282+-+Design+Intent+page) to the page to show where I think the video should be and some text to help users. Let me know what you think — is it enough?

**Comment by shiragoodman** [comment]
@rferguson13 I agree with your placement of the video on the page!

**Comment by rferguson13** [comment]
@shiragoodman - Do you think the text is good? Naomi wanted a clear distinction between the content in the video and the content on the page.

**Comment by shiragoodman** [comment]
@rferguson13 I made 1 comment, but otherwise I think it looks good!

**Comment by rferguson13** [comment]
@allison0034 - I think we can move on to phase 2 of this. Do I have/how can I gain access to Optimal Workshop?

**Comment by erinrwhite** [comment]
@rferguson13 [Optimal Workshop credentials here!](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/design/tools/optimal-workshop.md) we use the "Platform Research" login.

**Comment by rferguson13** [comment]
I did not! All good. I got to play around with a new tool :)

To recap:
- We have the survey.
- We like the text and video placement.

What's left to do:
- Link to the survey in both the article and the video (do you know how to link to the survey in the video?) 
- Publish the video and text on Platform.
- Create the Change History post

Is this correct?

**Comment by allison0034** [comment]
@rferguson13 yes I think that is it. What do you need me to do? I am not sure how to link the survey in the video.

**Comment by rferguson13** [comment]
Hrm, we may need to ask @shiragoodman, then. It says this in the research plan: "We will post a link to the survey in the YouTube video..."

We can move forward with the other two - it won't be published until Monday. Do you think we should go ahead even if we can't figure out the link to the Youtube video? We can always link it on the page itself.

**Comment by erinrwhite** [comment]
It looks like [we will not be able to add links to the video in Youtube](https://influencermarketinghub.com/clickable-links-youtube/) because we don't have enough subscribers :(

**Comment by rferguson13** [comment]
Oh bummer.

[I updated the text on the page and where we can link](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2940698630/77282+-+Design+Intent+page). What do y'all think @allison0034 and @erinrwhite ?

**Comment by erinrwhite** [comment]
@rferguson13 Looking good!

**Comment by rferguson13** [comment]
@allison0034 @erinrwhite - what do y'all think of this for the change log?

**The Governance Team has added a video to the Design Intent page.** In an effort to help VFS teams better understand this touchpoint, an informational video was added to the page.

**Comment by erinrwhite** [comment]
@rferguson13 Looking good to me. Maybe link out to the DI page from the text?

**Comment by rferguson13** [comment]
@erinrwhite @allison0034 - do y'all know how to embed a youtube video in confluence? I'm trying to use the Widget Connector macro and it doesn't look right.

**Comment by erinrwhite** [comment]
@rferguson13 innnnteresting. I had no idea how to do this. I had to track down an existing YT video on Platform website and backwards-engineer it. The [Platform Orientation page in Confluence](https://vfs.atlassian.net/wiki/spaces/GS/pages/edit-v2/1877344532) did it like this, looks like:

- Edit the page
- Put your cursor where you want the video to go
- Paste in the full URL to the YouTube video
- Select the link and some editing options should appear
- Select "Embed"

Crappy video embedded below!

https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/f7091eea-c11b-40c4-8541-80d2a33db69f

**Comment by rferguson13** [comment]
@erinrwhite - Wow, it really was that simple. I just pasted the link in. Who knew?!

Good call on the link. I'll add that.

With that...let's get this published!

**Comment by rferguson13** [comment]
Ok! @erinrwhite and @allison0034 - It's slated to be published today.

@allison0034 - the last bit is kicking off the research plan with the announcements. Do you want to take that on? We can also make sure we do this in the DI tomorrow.
