### ISSUE TITLE
Filter credential segments by user activity data

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#77289]
## Issue Description
As a stakeholder in Login.gov adoption, I need to see qualitative data regarding the trends of user credentials and credential segments.  I need to be able to filter these by how recently users were active (authenticated).

---
## Tasks
- [x] _Create a Domo to support a filter of credential segments base user last active date, i.e. when a user last authenticated with any credential_
- [x] _Update Login.gov adoption dashboard with a filter option_

## Acceptance Criteria
- [x] _Login.gov adoption dashboard updated with a filter option for last 3 years and option for no filter_

**Comment by sdickson-gt** [comment]
done
