### ISSUE TITLE
[CST] Details V2: Closed claim files +overview 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#77293]
## Value Statement
As a Veteran
I want to be able to see that my claim has been closed and access my decision letter from the new V2 UI
So that I can view the status of my claim and decision

---
## Background Context

Design work in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75166

## Design

**Figma links**

- [Closed Claim](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=1124-8264&mode=design&t=uPIfXxmgwRwStjBC-0)

|         | Current Design | New Design |
| ------- | ------ | ----- |
| Files Tab | ![Screenshot 2024-02-28 at 12 37 03 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/c9de4c07-be88-4bbb-a828-1b7b8b95f6d5) | ![Screenshot 2024-02-28 at 12 51 13 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/cf95ff1c-b9c7-4bb8-b9ad-6707cac215ea) |
| Overview Tab | ![Screenshot 2024-02-28 at 12 37 20 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/56a3282d-2671-477c-a0e9-49cc67bea4ee) | ![Screenshot 2024-02-28 at 12 51 27 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/5bc2ca9d-35a3-41bb-ad02-334772493c45) |

## Engineering 
- Add here

## Out of scope
- Add here

## Tasks

**Files Tab**
- [x] Add logic for Files tab when claim is closed then we show ClaimFileHeader,  AdditionalEvidencePage
- [x] Add logic to ClaimFileHeader so that the description text is different when a claim is closed
- [x] Add logic to AdditionalEvidencePage so that when claim is closed we show 'closed text'
- [x] Documents filed shows when claim is closed
- [x] Design Check

**Overview Tab**
- [x] The "Claims Decision" component is removed from this tab
- [x] The "Claim Complete" component is removed from this tab
- [x] The "Next Steps" section is removed from this tab
- [x] The Overview tab shows the timeline when the claim is closed
- [x] The timeline doesnt show the "Claims Decision" component under phase 5 when the v2 toggle is enabled
- [x] Design Check

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [x] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria

**Files Tab**
- [ ] The sub-header in the Files tab is different to account for the closed status
- [ ] "Additional evidence" section is shown with a claim is closed description
- [ ] "Documents filed" section is shown

**Overview Tab**
- [ ] The Overview tab shows the timeline. The claim should be in Step 5 "Closed." 
- [ ] The timeline no longer shows a payment section under the closed phase

**Comment by HeatherWidmont** [comment]
@samcoforma to do code review

@skylerschain to do the design check next week (this isn't a blocker for merging)

**Comment by pmclaren19** [comment]
@jacobworrell @skylerschain please validate/ perform design qa. You can do this by going to a closed claim in Staging.

**Comment by jacobworrell** [comment]
validated
