### ISSUE TITLE
[Support] Implement Analytics Tracking for Selection of STEM in Education Form 1995

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#773]
## User Story
As an education stakeholder, I need to track the number of form submissions for form 1995 that included the selection of the STEM scholarship to better understand its usage. Original issue tagged in [vets.gov-repo](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19269)

## Goal
Education has an understanding of percentage of forms that included the STEM selection

## Acceptance Criteria
- [x] Analytics-Insights team drafts requirements
- [x] Analytics-Insights creates custom dimension and updates Google Tag Manager
- [x] Analytics-Insights team validates on staging
- [x] Analytics team updates funnel with new steps
- [x] Publish GTM container
- [x] Add new tracking for form value custom dimensions (salary, activeDuty, calledActiveDuty, benefitsUsedRecently, edu-PursueTeaching, edu-StemApplicant, edu-undergradStem, preferredContactMethod) to Non-Prod and Prod Properties
- [x] Publish revised GTM container

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
Requirements provided to BAH in #19269

**Comment by nedierecel** [comment]
@jonwehausen @joanneesteban For your visibility, this is an implementation request in motion per the request of BAH team following the implementation of a new page that captures if applicants want to apply for the Edith Rogers STEM scholarship in Form 1995:

"Are you applying for the Edith Nourse Rogers STEM Scholarship?" in the form flow?
(https://staging.va.gov/education/apply-for-education-benefits/application/1995/benefits/stem)

Current Situation:
1. Requirements were provided to BAH
2. Discussion is in progress with Ad Hoc engineering surrounding the ability to add custom dimensions (additional application traits) to capture the selection --> since the form is built using the forms library, there is discussion on if/how to best implement

Next Steps:
1. Ad Hoc team will weigh in on the thread
2. We will pick back up the work in the upcoming sprint
3. The form funnel will also have to be updated in the test view and applied to the main view

**Comment by nedierecel** [comment]
@jonwehausen We should be able to test this by Tuesday. I will update this ticket with the right workspace and instructions to test.

**Comment by nedierecel** [comment]
@jonwehausen If you have time to QA today before noon, can you attempt a form submission on form 1995: https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction

Login is not required.

1. To validate, enter "Yes" to question 2 of 6 (this will be approx. the 3rd page of the form):
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/64235022-506f-45a3-aebd-f8346967ffc8)
2. For this test, you can enter other responses as you see fit.
3. Upon `--submission-success`, an extra dataLayer parameter is sent for the new custom dimension `edu-stem-applicant`. This value should match your response in the STEM question above.

**Comment by nedierecel** [comment]
@jonwehausen I did two test submissions, one with "Yes" and another entering "No". The former yielded the correct Custom Dimension in slot 49:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/c93de901-9e33-4ca3-abcf-0975919c3296)

The "No" value also was correct:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/f7e3dfd2-d22a-44ee-b4ff-80b15a711661)

**Comment by jonwehausen** [comment]
Hi @nedierecel , 

I received the same results. 

**Yes Scenario**

![image](https://user-images.githubusercontent.com/48527022/63031306-d54a8480-be81-11e9-8f51-0f757d477b1a.png)

**No Scenario**

![image](https://user-images.githubusercontent.com/48527022/63031588-32463a80-be82-11e9-8a78-b32494b37e2f.png)

**Comment by nedierecel** [comment]
Thanks @jonwehausen - I also created the custom dimension in Slot 49 in the Production property (to make sure I don't muddy up the placeholders you have for slots 50-52 in non-Production).

Next steps:
- [ ] (Me) Publish container to Prod
- [ ] (Me) Update funnel steps with new STEM step

**Comment by nedierecel** [comment]
The funnel has been updated and the new GTM container has been pushed to Production. I will have a follow-up chat with Amy in reviewing the funnel.

**Comment by nedierecel** [comment]
I am reopening this as I provided additional requirements for Form 1995 in this vets.gov-team issue https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19518

**Comment by nedierecel** [comment]
The container has been published with new changes to track form inputs. A report was delivered to the BAH team to show the breakdown of [submissions by STEM Scholarship applications](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20190815&_u.date01=20190828&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension49&_r.drilldown=analytics.eventLabel:edu-1995--submission-successful/).
