### ISSUE TITLE
[CST] [Claim Details V2] E2E Tests run and passed

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#77307]
## Background Context
We need to make sure that E2E tests exist, and are passing.

## Engineering 
The toggle "cst_use_claim_details_v2" needs to be turned on. There should be new V2 cypress e2e test files for these:
- _01.claim-status.v2.cypress.spec.js_
- _02.claim-files.v2.cypress.spec.js_
- _04.claim-ask-va.v2.cypress.spec.js_
- _06.claim-overview.v2.cypress.spec.js_

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] A user can navigate to their claim details of a closed claim
- [x] A user can navigate to their claim details of an open claim
- [x] A user that has the option to request a decision can go to the Files tab to do so and select "view details" button in the "Ask For Your Claim Decision" card
- [x] Once a user has selected "Ask For Your Claim Decision" they can check the checkbox and submit their claim
- [x] Once a user has selected "Ask For Your Claim Decision" they can select "Not yet - I still have more evidence to submit" button and they will be redirected to the status tab
- [x] A user that has tracked items can view recent activity
- [x] A user that has more than 10 tracked items gets pagination on recent activity page
- [x]  If there's a primary alert, a user can see that alert on the status tab and click "view details"
- [x] If there's a secondary alert, a user can see that alert on the status tab under "Recent Activity" section and click "add it here"
- [x] On the status tab, a user can click the "Overview of the process" link under the "What We're Doing" section
- [x] If there's a primary alert, a user can see that alert on the files tab and click "view details"
- [x] If there's a secondary alert, a user can see that alert on the files tab and click "add it here"
- [x] On the Files tab, a user can upload a file and submit it for review
- [ ] On the Files tab, a user can upload two files and submit it for review
- [x] On the Files tabs, a user can select the "Need To Mail Your Files?" action link, and it will show data
- [x] When a claim is closed, a user can see their timeline on the Overview tab
- [x] When a claim is open, a user can see their timeline on the Overview tab
- [x] On the Overview tab, under the third step a user can select the "Show past updates" button and see past updates
- [x] A user with more than 3 contentions can click "Show full list" button and see more contentions

## Definition of Done
- [x] Meets acceptance criteria
- [x] Passed E2E testing
- [x] Passed unit testing (80% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Engineering identifies staging users required to test and shares account and credentials with product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] There are cypress tests around "cst_use_claim_details_v2" toggle
- [ ] All tasks have been reviewed with confirmation that tests exist for each

**Comment by HeatherWidmont** [comment]
I added the template contents to this ticket, please feel free to edit as needed 😄

**Comment by samcoforma** [comment]
Updated this ticket to test for contentions cc: @pmclaren19

**Comment by samcoforma** [comment]
Also, I need to modify mock data to accommodate some tasks like "A user that has more than 10 tracked items gets pagination on recent activity page"

**Comment by samcoforma** [comment]
This one might not work yet due to Platform not updating the component to let it work: "On the Files tab, a user can upload two files and submit it for review"
