### ISSUE TITLE
[CST] Remove old claim cards

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#77311]
### Description
The new claim cards have been in production for a few months now, so we've determined that it's time to remove the old claim cards and the feature toggle

### Context
The feature toggle is here (to be removed): [cst_use_new_claim_cards](https://api.va.gov/flipper/features/cst_use_new_claim_cards)

These are the old components (to be removed):
* `src/applications/claims-status/components/appeals-v2/AppealListItemV2.jsx`
* `src/applications/claims-status/components/ClaimsListItem.jsx`
* `src/applications/claims-status/components/StemClaimListItem.jsx`

These are the new components (to be renamed):
* `src/applications/claims-status/components/appeals-v2/AppealListItemV3.jsx`
* `src/applications/claims-status/components/ClaimsListItemV3.jsx`
* `src/applications/claims-status/components/StemClaimListItemV3.jsx`

### Tasks
- [x] Remove the old card components and any associated tests
- [x] Rename the V3 card components to not include the `V3` moniker
- [x] Remove test files for the old card components
- [x] Update any other tests that were using the old card components
- [x] Rename the V3 card components files to not include the `V3` moniker
- [x] Remove the `cst_use_new_claim_cards` feature toggle from the frontend code
- [x] Remove the `cst_use_new_claim_cards` feature toggle from the backend code

### Acceptance Criteria
- [x] The old claim cards have been removed
- [x] The new claim cards do not include V3 in their names
- [x] The new claim cards do not include V3 in their file names
- [x] The `cst_use_new_claim_cards` feature toggle has been completely removed from `vets-website`
- [x] The `cst_use_new_claim_cards` feature toggle has been completely removed from `vets-api`

**Comment by jerekshoe** [comment]
#### Update
FE PR to remove the feature toggle from `featureFlagNames` just moved out of draft now, waiting on review from Platform before it can be merged. Once that is done a similar PR for BE will be put together

**Comment by jerekshoe** [comment]
Last PR merged, closing
