### ISSUE TITLE
[CDP] Deprecate legacy applications (due May 3, 2024)

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#77329]
## Description
- `src/applications/debt-letters`
- `src/applications/medical-copays`

These two applications have been deprecated since the Combined Debt Portal has been live, with all urls redirecting appropriately it's time to remove the applications from the code base! We will definitely want to coordinate with platform on application deprecation to make sure we don't miss anything.

***Per OCTO, the deadline to complete this work is May 3, 2024, so we will need to prioritize accordingly.**

## Tasks
- [ ] Keep platform in the loop so no one has a panic attack seeing a bunch of removed files
- [ ] Remove `debt-letters` and it's references
- [ ] Remove `medical-copays` and it's references

## Acceptance criteria
- [ ] `debt-letters` and `medical-copays` have been removed 

## Testing
- [x] N/A

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Pulled in lateish to current sprint.

**Comment by OptionSelect** [comment]
Cont build PR [here](https://github.com/department-of-veterans-affairs/content-build/pull/1953)

**Comment by OptionSelect** [comment]
Thread with auth exp team [here](https://dsva.slack.com/archives/C909ZG2BB/p1710262516202999)

**Comment by OptionSelect** [comment]
All involved teams have approved the changes, just fighting with CI/CD & waiting for post 2PM deploy of Content Build to merge the final 2 pr's
