### ISSUE TITLE
Respond to OCTO/VBA additions to 526ez core audit 

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#77354]
## Issue Description
The 526ez form gets updated when necessary. This epic covers the changes required on the digital 526ez form on va.gov to make it sync with the paper version.

The scope of this ticket includes  1) reviewing/addressing the additions Shannon made to the discrepancies list (lines 18-23) and 2) Clean up the tab that includes content represented on VA.gov but not paper form (as requested by David).

[Sharepoint documentation](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B3308EE26-A184-42ED-AFC0-44B1D20F12A6%7D&file=526%20paper%20sync%20audit%20.xlsx&action=default&mobileredirect=true)
---
## Tasks
- [x] Review Shannon's added line items
- [x] Determine if technical discovery needs to be done to investigate new discrepancies
- [ ] Clearly identify where VA.gov diverges from paper form within the 526

## Acceptance Criteria
- [x] Sharepoint spreadsheet is updated
- [x] Ticket created for further technical discovery (only if needed)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
In advance of OOO, a few notes: 
Shannon's additions at the bottom of the first tab for 526 are important and identify a couple of working assumptions/challenges of mine during audit.
1. A majority of the audit was conducted in staging-- differences in production might have been missed on ocassion
2. The Veteran Information section was hardest to audit because of preflling from the VA profile. 
3. In the ancillary forms, I assumed that all the Veteran information would be accounted for already by the core 526

Still outstanding:
1. @RakshindaAslam technical discovery must be completed for these additions
2. Review other ancillary audits for the VA.gov discrepancies (not needed for paper sync but requested by David)
3. Double check to make sure my assumptions didn't lead me to miss anything in anicllayr forms
@alatempa24

**Comment by evelynhilbrichdavis** [comment]
Closing this ticket without fully reviewing the digital to paper sync section of the audit since it is not included in the AC. I will create a new issue after our checkin with VBA tomorrow to determine what the most useful/pertinent next steps are for cleaning up and advancing the audit. 
With this ticket I also:
-Archived the Google spreadsheet and directed all traffic to the [Sharepoint file ](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B3308EE26-A184-42ED-AFC0-44B1D20F12A6%7D&file=526%20paper%20sync%20audit%20.xlsx&action=default&mobileredirect=true)
-Ensured that all comments/engineering notes transferred over to the Sharepoint doc
-Addressed Shannon's points and created a technical ticket for their review.

**Comment by evelynhilbrichdavis** [comment]
@alatempa24
