### ISSUE TITLE
Fix 'cannot overwrite table' warnings when building vets-API manifest

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#77350]
### Summary

There are warnings when templating the helm charts locally, in the vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests) repository. This could be fixed by replacing every hash with an array in the parent helm chart, [values.yaml](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/chart/values.yaml). This

Note: These warnings are not seen in ArgoCD. This is strictly a helm issue.

`coalesce.go:286: warning: cannot overwrite table with non table for vets-api.vets-api.clamav.volumeMounts (map[])`

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8d199afaffac8bf89d0108eb17553156f55383a/Screenshot%202024-02-28%20at%204.16.45%20PM.png" alt="Screenshot 2024-02-28 at 4.16.45 PM.png" />

### How to reproduce
```
# Go to vsp-infra-application-manifests
$ cd ../vsp-infra-application-manifests

# Go to the dev helm charts
$ cd apps/vets-api/dev

# Remove the charts directory and Chart.lock, if present.
$ rm -rf charts
$ rm Chart.lock

# Build the helm charts
$ helm dependency build
$ **Clear out terminal
$ helm template .
```

The warnings will be at the top of the manifests. 

## Tasks

- [x] Fix the warnings in dev
- [x] Fix the warnings in staging
- [x] Fix the warnings in sandbox
- [x] Fix the warnings in prod

**Comment by RachalCassity** [comment]
Staging successfully deployed. Closing ticket after Tuesday's deployment
