### ISSUE TITLE
Create monitor to detect HPA issues

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#77352]
### Summary
HPA was not working for for over a month before it was discovered. (Bug: https://github.com/department-of-veterans-affairs/va.gov-team/issues/76845). Create alert to notify us if something like this happens again.

### Tasks
- [x] find a metric to alert on
- [x] Figure out a good threshold to alert on (so it's not giving false alarms)
- [x] Create alert (in terraform if it's a Datadog alert)
    - [x] Make sure the alert is actionable (what steps need to be taken to resolve the alert?)

### Acceptance criteria
- [x] Alert has been tested
- [x] Alert is monitoring HPA, alerting when it goes beneath the threshold so that it can be repaired
- [x] Documentation is complete

**Comment by RachalCassity** [comment]
Monitors were created:
[VETS API - PROD - EKS IS NOT SCALING!](https://vagov.ddog-gov.com/monitors/116990?view=spans)
[VETS API - PROD - Check HPA Metrics](https://vagov.ddog-gov.com/monitors/203304?view=spans)
