### ISSUE TITLE
[DevOps] Discovery on `chip` repository and contents

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77369]
## User Story
As a DevOps engineer, I'd like to know what's in [`chip`](https://github.com/department-of-veterans-affairs/chip/) so that I can maintain and, where possible, improve it.

## Tasks
- [ ] [DevOps] Check out `chip` and carefully read through its contents.
- [ ] [DevOps] Determine the boundaries of my responsibilities.

## Acceptance Criteria
- [ ] `chip` has been 👀ed and findings have been documented in this thread.
- [ ] Followup issue(s) opened if appropriate to take action where advisable.

**Comment by ndouglas** [comment]
This is no longer really necessary; I've gained a passable understanding of how we work with this repository.
