### ISSUE TITLE
Update review tickets to include links to update review processes docs

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#77366]
## Purpose
the tickets that get repeated each sprint for both FRP review and Platform feedback need to be updated with the recent process change document links, as well as the addition of the Reference database

## Tasks
- [x] Update tickets for this sprint with process doc link
- [x] Update tickets for this sprint with Ref. database link
- [x] Create new tickets for this sprint

## Acceptance Criteria
- [x] Tickets reflect current processes
