### ISSUE TITLE
Understand the processes of the contact center team

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#77396]
## Description of UX Tasks
We know that the contact center team has two way conversations with veterans and sometimes on the subject of potential fraud. Is there anything we can leverage from their team or integrate with their team as we move forward with new fraud related notifications from our team?

## Tasks
- [ ] reach out to Kimberly from the Contact Center team
- [ ] understand their processes and if there is anything we can integrate with or leverage for our proposed notifications
- [ ] 

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Add finalized research to Github
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by claytonzook** [comment]
duplicate ticket
