### ISSUE TITLE
[FE] - Set up travel-claim app in pagerDuty

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#77393]
## Summary
Travel claim should get set up in pagerDuty so that we can put the app in maintenance mode.

## Tasks
- [ ] Add a service for stage and prod to pagerDuty: https://dsva.pagerduty.com/service-directory?direction=asc&query=&team_ids=PPW0SBU
- [ ] Add the external service to this list: `vets-website/src/platform/monitoring/DowntimeNotification/config/externalServices.js`
- [ ] Add the new `downtimeDependency` value for travel-claim to `vets-website/src/applications/check-in/components/layout/Wrapper.jsx`
- [ ] Add app abbr and id for staging in `devops/ansible/roles/review-instance-configure/vars/settings.local.yml`
- [ ] Add app abbr and id for prod in `vsp-infra-application-manifests/apps/vets-api/prod/values.yaml`
- [ ] Test downtime on stage
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [x] Read ticket details and verify that ACs are met
- [x] Review code in PR
- [x] Run branch locally
- [x] Check that new and updated translations use new keys
- [x] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/77393?planning-poker) with Zenhub @lee-delarm6 @wullaski

**Comment by wullaski** [comment]
@loripusey, @benbrasso-agile6  This is working on staging now and ready to be validated for content. I took a screenshot on staging with a maintenance window in place.
![Screenshot 2024-03-13 at 10 34 26 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/6d79b5a0-e3d4-49af-94b8-de5edd0d1ac9)

**Comment by loripusey** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
LG, @wullaski what's the url string so I can update in Figma?

**Comment by brianseek** [comment]
@benbrasso-agile6 there is no specific URL string, this will show on any page of the app when active
