### ISSUE TITLE
[FE] My VA: Custom events documentation for GA4 migration

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#77399]
## Background
With the migration to GA4 for analytics, the platform has requested we document our custom events in a spreadsheet. 

_The deadline on this is **April 5** so we should get it done asap within this sprint (sprint 32) to leave time in case we have issues._

## Tasks
- [x] Review analytics to identify custom events that we're using
- [x] Complete the attached spreadsheet with [all custom events](https://docs.google.com/spreadsheets/d/1i6QH2emLiQnJH_2qBSxOSUPUUSDopr37rIRtogUzL28/edit#gid=2087351809)
- [x] Complete this [form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D)
- [x] Attend analytics office hours for assistance as needed

## Acceptance Criteria
- [x] Form (below) and attached spreadsheet are completed and submitted to analytics team

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ review spreadsheet and form

## Resources
[Slack announcement for context](https://dsva.slack.com/archives/C1Q4294JJ/p1709064017751029) from Johnny Jesensky

> In preparation for the migration to Google Analytics 4 (GA4), we ask that all VFS Teams that leverage and track custom events in their products [complete this form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D), (along with its attached spreadsheet), no later than Friday, April 5. Detailed instructions on what information to include for each custom event can be found within the form. We are providing some additional information on this ask below.
> 
> **Why Is This Needed?**
> Universal Analytics (UA) properties will stop collecting data on events on June 30, 2024. In order to maintain data collection on a product's custom events, we need to ensure they are properly set-up within GA4 before that date.
> 
> **What Is Required From Me?**
> Please work with the front-end engineers on your team to identify, and list out custom events that you want tracked within GA4. Each event needs to be specified with information like event type, code snippet, file URL, etc. We have provided an example of what information to include on the form and attached spreadsheet.
> 
> **When Do I Need to Complete this Form?**
> Please complete this form as soon as you can, but no later than Friday, April 5. UA will stop collecting data on all events on June 30, 2024, so we are trying to ensure coverage within GA4 well before the cut-off date.
> 
> **Please reach out if there are any questions.** Additionally, teams are always welcome to join our team's Office Hours to discuss this in more detail. Thank you!

**Comment by allisonlu** [comment]
Issue submitted to the Analytics team:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/78832

**Comment by ajakabcin** [comment]
This is good to go - analytics team has our document! Great job @allisonlu thank you for handling this
