### ISSUE TITLE
Understand how our notification work can best fit in with BDPR communications around fraud

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#77392]
## Description of UX Tasks
On the BDPR team, Monica Rivera manages communications to veterans. Since they have existing language and avenues of contacting veterans we want to make sure that our notifications fold in well with what is already existing on their end.

## Tasks
- [x] connect with Monica on what language they use for their notifications
- [ ] sync with Adam Kinder so we are on the same page about what our team owns vs what their team owns, to make sure that we aren't doubling any efforts, and to make sure that our work aligns and folds nicely together
- [ ] understand what triggers the BDPR team is using for physical mailers about bank account or beneficiary changes, and anything else around this communication that would make sense to borrow from or piggy back on
- [ ] understand the current process for BDPR to work with the Veterans Support (fka Contact Center) team and if and how that might be affected by our team adding a new notification

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Add finalized research to Github
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
moved to jira, closing
