### ISSUE TITLE
Understand the processes of the contact center team

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#77401]
## Description of UX Tasks
We know that the contact center team has two way conversations with veterans and sometimes on the subject of potential fraud. Is there anything we can leverage from their team or integrate with their team as we move forward with new fraud related notifications from our team?

## Tasks
- [x] reach out to Kimberly from the Contact Center team
- [x] sync with Contact Center team (sched for March 6)
- [x] understand their processes and if there is anything we can integrate with or leverage for our proposed notifications
   - They can offer us a "shadow call" 1:1 with a veteran who calls in and needs fraud related help
   - but they mostly refer fraud type calls to BDPR
   - we should plan to create a playbook for them on what we'd want them to do with callers we send, as part of our roll out of any new notifications
   - When we direct folks with a notification, Contact Center team requests we send to Ask VA first since issues can be better tracked that route
- [x] [Otter notes from the convo](https://otter.ai/u/hYOiGvhBpI67tRXDxPO36MiO0zE?st=9bhF8obuX5QzCSrgoTM58_SQ8BbsMlfCwI3oT8rkrAKTk2iAVzcCFVxYOTwgOEKURqQjaOUQT5XFM-cQrbXLtt5z76CY2qq3TjI_elwcQvKYpszJwKagLrkec3ETs7In:0a6G-DNoE6a7Icj63KVLg2Jgfks&utm_source=shared_with_you_keywords&utm_campaign=shared_with_you_keywords&is_new_user=false&tab=chat&view=summary)
- [x] look over contact center data sent by Kim, and add to our [Fraud Reduction Notifications Mural](https://app.mural.co/t/oddballinternal7486/m/oddballinternal7486/1709058764550/6122e5571e28b17c72781cf20646550887475202?sender=u6c46f747a0483ea836054483)

## Acceptance Criteria
- [x] Documentation has been updated
- [x] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
