### ISSUE TITLE
Understand how we can leverage VA Notify for fraud related notifications

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#77403]
## Description of UX Tasks
VA Notify is a tool already in place for sending notifications to veterans. We want to understand how we can utilize it for fraud notifications

## Tasks
- [x] Understand VA Notify team's research around messaging and communicating with veterans
- [x] Create an [intake ticket for VA Notify](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77339)
- [ ] Steps for VA Notify (from their [Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#playbook)) _Note: we'll likely need to split these into various tickets_
   - [x] Submit the intake form
   - [ ] Kick-off with VA Notify
   - [ ] Have your technical team review the VA Notify API docs
   - [ ] Get access to the Self Service Portal
   - [ ] Budget approval for notifications
   - [ ] Create your notification content (Privacy Officer review required)
   - [ ] VA Notify submits a communication preference intake for your team (if applicable)
   - [ ] Please note, if you have a new communication preference your team will need to determine a plan to communicate this to veterans so they know a new notification is available to opt into.
   - [ ] SMS only: VA Notify requests applicable phone number(s)
   - [ ] Build your notification code to call the VA Notify API
   - [ ] Test your notification
   - [ ] Launch your notification
   - [ ] Evaluate business outcomes and make revisions as needed

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Add finalized research to Github
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
moved to jira, closing
