### ISSUE TITLE
[Configuration] Configure and test SOCKS connection for VAMC team for remote access [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7740]
## User Story or Problem Statement
As a VAMC team member, I need remote access through SOCKS, so I can directly connect to VA urls in a secure and unhindered manner

## Goal
_Perform initial page testing, review, testing and page creation _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Tasks
_Complete review of system and facility pages, first manual review and testing of links and then AXE test:_
- [x] Load git bash on new system and generate public key
- [x] submit request to have pub key entered into security
- [x] upload configuration to desktop
- [x] load chrome proxy on desktop
- [x] load agent on desktop
- [ ] test connection

## Acceptance Criteria
* Load git bash on new system and generate public key
* submit request to have pub key entered into security
* upload configuration to desktop
* load chrome proxy on desktop
* load agent on desktop
* test connection
