### ISSUE TITLE
Use a Pensions-specific Sentry tag

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#77413]
## Issue Description

Create a pensions-specific Sentry tag, then, in `PensionClaimsController.create`, replace the `PensionBurial::TagSentry.tag_sentry` call with it.

## Tasks
- [ ] Create a pensions-specific Sentry tag
- [ ]  In `PensionClaimsController.create`, replace the `PensionBurial::TagSentry.tag_sentry` call with a pensions-specific Sentry tag

## Acceptance Criteria

- [ ] We use a Pensions-specific Sentry tag

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77413?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel @danlim715 @scottsdevelopment

**Comment by mjknight50** [comment]
Opened a Spike to figure out how Sentry works and if the changes worked.
