### ISSUE TITLE
Add additional logs and metrics

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#77412]
## Issue Description

In order to more effectively catch and debug errors, add additional logs in `rescue` blocks, and add additional StatsD metrics.

## Tasks

- [x] PensionClaimsController.show: add a rescue which logs then raises the error
- [x] PensionClaimsController.create: add StatsD.increment("api.pension_claim.attempt") when beginning a submission
- [x] PensionClaimsController.create: Add a rescue block which error logs "21P-527EZ submission to Sidekiq failed" (with { confirmation_number: claim&.confirmation_number, user_uuid, in_progress_form_id: in_progress_form&.id, errors: claim&.errors&.errors }) and calls StatsD.increment("api.pension_claim.failure") then re-raises the error
- [x] PensionBenefitIntakeJob.cleanup_file_paths: add a rescue block that logs "Lighthouse::PensionBenefitIntakeJob cleanup failed"

## Acceptance Criteria

- [ ] rescue blocks will be added to methods in the Pension flow in locations where errors won't be caught by logs in a containing method
- [ ] important events will be counted by StatsD

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77412?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel
