### ISSUE TITLE
Make log structure consistent

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#77410]
## Issue Description

Update the logs to have, to the greatest extent possible, the same data and message structure.

Note: I have confirmed that the logging level of existing logs is correct (info for non-errors, warn for failed attempts that will retry, and error for errors on final/only attempts).

## Tasks

- [x] PensionClaimsController.create: when logging "Begin 21P-527EZ Submission", instead log "21P-527EZ submission to Sidekiq begun" { confirmation_number: claim&.confirmation_number, user_uuid, in_progress_form_id: in_progress_form&.id } to match other logs
- [x] PensionClaimsController.create: when logging "Submit 21P-527EZ Submission Failed for user_id: " instead log "21P-527EZ submission to Sidekiq failed" and pass { confirmation_number: claim&.confirmation_number, user_uuid, in_progress_form_id: in_progress_form&.id, errors: claim&.errors&.errors }
- [x] PensionClaimsController.create: When logging "Submit 21P-527EZ Submission Success" instead log "21P-527EZ submission to Sidekiq succeeded" and pass and pass { confirmation_number: claim&.confirmation_number, user_uuid }
- [x] PensionBenefitIntakeJob.perform: Lighthouse::PensionBenefitIntakeJob Attempt" update to "Lighthouse::PensionBenefitIntakeJob submission to LH begun"
- [x] PensionBenefitIntakeJob.perform: "Lighthouse::PensionBenefitIntakeJob Upload" update to "Lighthouse::PensionBenefitIntakeJob submission to LH attempted"
- [x] PensionBenefitIntakeJob.perform: 'Lighthouse::PensionBenefitIntakeJob FAILED!' update to "Lighthouse::PensionBenefitIntakeJob submission to LH failed, retrying"
- [x] PensionBenefitIntakeJob.sidekiq_retries_exhausted: 'Lighthouse::PensionBenefitIntakeJob Exhausted!' update to "Lighthouse::PensionBenefitIntakeJob submission to LH exhausted!" If possible, add the claim.confirmation_number to the log.
- [x] PensionBenefitIntakeJob.check_success: 'Lighthouse::PensionBenefitIntakeJob Succeeded!' update to "Lighthouse::PensionBenefitIntakeJob submission to LH succeeded"

## Acceptance Criteria

- [ ] The logs to have, to the greatest extent possible, the same data and message structure.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77410?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by mjknight50** [comment]
Include the current `user_uuid` when/if possible.
