### ISSUE TITLE
Revisit and update the research/design roadmap

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#77414]
### Description
In late February the Research and Design team updated our roadmap for March and April. (The roadmap will continue to be updated as we go, but having intentional planning time for this was helpful.) We should have an intentional planning session for the months of May and June.

### Output
- Update the roadmap (note that we might have shifted the roadmap tool from Mural to another tool by the time we start this ticket)
- Update the board to reflect the roadmap

### Leads or Collaborators
- Lead:
- Co-lead: 

### Resources
- Existing Research/Design roadmap in Google docs
- ARF Roadmap with Research/Design roadmap visualization at the bottom 

### Acceptance Criteria
- [ ] Roadmap is updated, in whatever tool we're currently using
- [ ] Board is cleaned
  - [ ] Done tickets are Closed
  - [ ] Tickets for upcoming sprint are pointed and assigned
  - [ ] Any collaboration tickets with engineering or partners are clarified (as we might need to ensure our timeline works with their timeline)
- [ ] Someone double checks that roadmap and board are in sync

**Comment by kristen101606** [comment]
With our contract closing, we've connected with our Enablement team and created a [Future Research Activities board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718980793805/b1c89e3110a00b235ee30bc04bab3cc96a33c696?sender=u2a4240a640b257ce33545495) (Mural). The incoming team can review these proposed research activities, grouped in order of priority, and assess which research efforts they want to begin. 

Proposed next steps are also listed on each of the work stream overview pages in Github: 
- [Proposed next steps for 21a](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/21a-digital-accreditation.md#proposed-next-steps)
- [Proposed next steps for 21-22](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/21-22-power-of-attorney.md#proposed-next-steps)
- [Proposed next steps for contact information updates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representative-facing/contact-information-updates.md#proposed-next-steps)
