### ISSUE TITLE
Edit: Archiving Daily Accessibility Scan Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#77429]
## Issue Description

The daily accessibility scan mentioned on [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content ) is no longer supported and was removed last. We (the Platform Content Team) added a note to this effect, however, there is no solid timeline for us to replace scanning within content-build. In fact, content-build is currently on the roadmap to be sunset by the end of the 2024 calendar year for next-build. 

Per the recommendation on [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82359) from CAIA Team, we have decided to archive the page.

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content 

---
## Tasks
- [x] Archive the Daily Accessibility Scan page

## Acceptance Criteria
- [x] Page has been archived
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/77429?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
cc: @laucon for instructions

**Comment by taylojill** [comment]
@jknipes - I identified two published pages that mention the Daily accessibility scan. When I return from PTO on Monday the 20th I'll remove those mentions and archive the page. Also, I received the Archive instructions from Lauren.

**Comment by jknipes** [comment]
works is complete, moving to _Done_
