### ISSUE TITLE
Burial | User Testing

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77421]
## Issue Description
_Review the Burial 21-530EZ form for any quality issues as an authenticated and unauthenticated user to ensure the form is functioning as intended._

---
## Tasks
- [ ] Any links, menus, input boxes, or controls are functional
- [ ] Error messages appear as expected
- [ ] Forward/backward navigation within the form works as expected
- [ ] Form saves as anticipated for authenticated users
- [ ] Test the form section as an authenticated and unauthenticated user and document and issues in [this spreadsheet](https://docs.google.com/spreadsheets/d/1pKE5rvUgoJe0vkh06W4EVCKL5ygXxgajCRa3nVTLARQ/edit?usp=sharing)
- [ ] Confirm all issues have been resolved

## Acceptance Criteria
- [ ] All user testing issues have been resolved
---
