### ISSUE TITLE
Staged Rollout of Find a Rep 2.0

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77437]
## Staged Rollout Schedule

Original schedule:
~1. Stage A: 10% of users on 3/11 (Monday)~
~2. Stage B: 25% of users on 3/13 (Wednesday)~
~3. Stage C: 50% of users on 3/18 (Monday)~
~4. Stage D: 100% of users on 3/20 (Wednesday) - monitor for any issues through 3/25 EOD (Monday)~

After realizing that users aren't getting to our landing page easily to make effective use of our % ramp up, we are changing our approach to increasing visibility:
1. Stage A: 10% of users on 3/11 (Monday) [Complete]
2. Stage B: 100% of users on 3/13 (Wednesday) + launch best bets for an initial boost to visibility
3. Stage C: Implement redirects on 3/18 (Monday) for an added boost to visibility
4. Stage D: Begin entry point work on 3/20 (Wednesday) so pages point directly to the Accredited Rep landing page

Before proceeding to the next stage, we'll want to consider any Sentry errors and examine user behavior for reporting outdated information, to determine if updates need to be made before increasing visibility.   

[Full release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/release-plan-find-a-representative-2.0.md)

## Tasks
- [x] 3/11: Roll out to 10% of users
- [x] 3/13: Roll out to 100% of users
- [x] 3/18: Implement redirects (https://github.com/department-of-veterans-affairs/va.gov-team/issues/69952)
- [ ] 3/20: Begin entry point work (https://github.com/department-of-veterans-affairs/va.gov-team/issues/67034)

## Acceptance Criteria
- [x] Find a Representative 2.0 is live on VA.gov for all users!
- [x] All traffic is pointing directly to the [accredited rep landing page](https://www.va.gov/get-help-from-accredited-representative/) and Find a Rep

**Comment by oddball-lindsay** [comment]
We're currently at 10% of auth users, in ~1 hr will be 10% of all users.  Landing page launching shortly through CAIA.

**Comment by oddball-lindsay** [comment]
The team is discussing if the staged rollout provides any value when there's no clear path for those x% of users to see our new product.

[Chatting with the team in Slack](https://dsva.slack.com/archives/C05L6HSJLHM/p1710268736038989) to determine if we can pivot to an approach where each stage ramps up visibility not through our feature toggle %, but by upping traffic through best bets, redirects, and entry points.

Going to call this "blocked" right now bc I'm hoping to hear from Kristin about if she's open to doing Best Bets earlier; hoping to hear back by tomorrow and find a path forward as a team by tomorrow's standup.

**Comment by oddball-lindsay** [comment]
That was short lived - Kristin confirmed she can do the Best Bets tomorrow which will be a nice first push to visibility.  I proposed this updated plan to the team + folks involved with redirects and entry points and hope to finalize that this week

Stage A: 10% of users on 3/11 (Monday) [complete]
Stage B: ~25%~ **100%** of users on 3/13 (Wednesday) + **launch best bets for an initial boost to visibility**
Stage C: ~50% of users~ **Implement redirects** on 3/18 (Monday) **for an added boost to visibility**
Stage D : ~100% of users~ **Begin entry point work** on 3/20 (Wednesday) **for max visibility**

**Comment by oddball-lindsay** [comment]
Closing this as all traffic is pointing to our Find page and landing page.  We can track the entry point work in that specific ticket  #67034
