### ISSUE TITLE
Burial | Set Up Domo KPI Dashboard

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77430]
## Issue Description
_In order to better understand how the Burial 530EZ form is serving users, we need to work with the Analytics Team to [create a Domo KPI dashboard](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide#Analyticscustomersupportguide-4.RequestaKPIDashboardinDomo)._

This task should quickly follow the launch of the updated 530EZ form.

---
## Tasks
- [x] Fiorella: Define the form funnel details within [this spreadsheet](https://docs.google.com/spreadsheets/d/1ptfQI71LP85un1kXfrwOwzwbl9VYKrjBVHxLCBlyAgQ/edit?usp=sharing)
- [x] Laura: Submit a [KPI dashboard request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-and-update-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+%26+KPI+dashboard+update+request+for+%5BTeam%5D)

## Acceptance Criteria
- [ ] Domo KPI dashboard for Burial 530EZ has been created

**Comment by steele-lm** [comment]
Ticket with analytics team: #80861

**Comment by steele-lm** [comment]
Ticket with analytics team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82436
