### ISSUE TITLE
Binstub User Testing 

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#77436]
## Summary 

In order to effectively gauge the usefulness and accuracy, user testing must be completed on the 3 binstubs. 

## Background

The introduction of binstubs, which are executable wrappers, is proposed as a solution to harmonize the development environment across different setup configurations. The primary objective of these binstubs is to standardize core development commands, such as setup, running applications, and executing tests. By ensuring uniformity in these processes, we aim to mitigate the discrepancies currently observed in testing outcomes.

## Compatibility 

`bin/setup` currently only supports Mac OS. However, `bin/setup --base` should work on Linux and Windows as well. 

## Tasks 

*Before running `bin/setup` make sure postgres is installed. This will be added to bin/setup in the future. 

Test the following

- [ ] `bin/setup`
- [ ] `bin/test`
- [ ] `bin/lint`
- [ ] `bin/info`
- [ ] `bin/help`

#### Base

`bin/setup --base`

- [ ] Checks current directory is `*/vets-api`
- [ ] Adds localhost authentication for id me certificates under `config/certs`
- [ ] Copies and renames `config/settings.local.yml.example` to `config/settings.local.yml`
- [ ] Clones `vets-api-mock-data` to sibiling directory
- [ ] Disables signed authentication requests in `config/settings.local.yml`
- [ ] BUNDLE_ENTERPRISE__CONTRIBSYS__COM is set in `bundle config`

#### Native/Hybrid/Docker

`bin/setup --native`

- [ ] `.developer-setup` is set to native
- [ ] dependencies in Brewfile are added 
- [ ] bundler 2.4.9 is installed 
- [ ] gems are bundled
- [ ] databases (development, test, parallel) are setup 
- [ ] clamav environment variables are set in `config/initializer/clamav.rb`
- [ ] pdftk is installed

`bin/setup --hybrid`

- [ ] `.developer-setup` is set to hybrid
- [ ] bundler 2.4.9 is installed 
- [ ] gems are bundled
- [ ] databases (development, test, parallel) are setup 
- [ ] apply database and redis setting to `config/settings.local.yml`
- [ ] clamav environment variables are set in `config/initializer/clamav.rb`
- [ ] docker-compose-deps.yml builds successfully

`bin/setup --docker`

- [ ] `.developer-setup` is set to docker
- [ ] docker-compose.yml builds successfully
- [ ] databases (development, test, parallel) are setup 
- [ ] clamav environment variables are set in `config/initializer/clamav.rb`

PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15464

### Test

- [ ] tests run locally like CI (`--ci`)
- [ ] tests run in parallel or not in parallel (`--no-parallel`)
- [ ] tests run with coverage report (`--coverage`)
- [ ] tests run with output to log (`--log`)
- [ ] tests run with setup preference
- [ ] tests run with specific files or folders

PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15629

### Lint

- [ ] lint with rubocop, brakeman, bundle-audit
- [ ] lint with only rubocop (`--only-rubocop`)
- [ ] lint with only brakeman & bundle-audit (`--only-brakeman`)
- [ ] lint without autocorrecting (`--dry`)
- [ ] lint with specific files or folders

### Info

- [ ] output version related info such as Rails version, Ruby version, etc

### Help

- [ ] output all commands and description
 
## Example Commands with Options

```
bin/setup --base      
bin/setup --docker
    
bin/test --ci
bin/test --no-parallel spec/models/account_spec.rb
bin/test --coverage --log
bin/test spec
      
bin/lint --dry --only-rubocop
bin/lint lib/forms/client.rb
```

## More Information

https://github.com/department-of-veterans-affairs/vets-api/blob/ebeba2c5d55735af57f63d9ebdd06e4a21534afe/bin/lib/vets-api/README.md
