### ISSUE TITLE
Spike: Provide additional detail on supporting documents page

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#77456]
## Description

On the supporting documents page, we ask for additional evidence in certain situations, but we don't provide any detail about what type of evidence to submit, what information to include, or how to submit it.

## Tasks
- [x] Account for scenarios that may not need supporting documents
- [x] Review other teams' solutions for submitting similar types of evidence (maybe the 526 form?)
- [x] Review supporting documents mentioned on web form vs pension paper form

Next ticket
- [ ] Prototype solutions
- [ ] Review content with Katherine/CAIA (also review #73979 with Katherine so it can be incorporated into the copy)
- [ ] Plan and create implementation tickets - split up where possible 

## Resources
The supporting documents page includes a section that says, "You'll also need to submit additional evidence depending on your situation" with 2 expanding accordion items:

<img width="254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3VoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71d7ed2495919b15f14a502b81d8231db83d1367/image.png" alt="image.png" />

## AC
The instructions account for different scenarios and user needs to successfully use supporting docs page (or pass through it)

**Comment by gmaciolek** [comment]
I'm rounding up information related to supporting documentation in [this Google Doc](https://docs.google.com/document/d/1MojDBRB1dKeqcKIs84QdB0_HD7Phi_bATLLcxWpW8KM/edit?usp=sharing).
