### ISSUE TITLE
[Accessibility]: Update Platform website pages with improved tips for research with screen readers

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#77457]
## Value Statement
**_As a_** designer and/or researcher
**_I want to_** clearer guidance for conducing research with assistive technology
**_So that_** assistive technology users can get set up during research sessions efficiently as possible.

---
## Background Context

- We want to update the existing screen reader research documentation with takeaways from our latest research sessions to help ourselves in the future and other teams across VA.gov.

Existing pages:

- [Research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users)
- [Screen reader checklist](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-checklist)

## Out of scope
- Creating any new pages 

## Tasks
- [x] Look at changing the page titles to better reflect some of the content available on the page
- [x] Add a note about the iOS screen getting stick in safe driving mode, and how to get it out of that.
- [x] Add a note about users getting stuck in the Zoom menu on iPads and how to get out of that.
- [x] Add a note about some iPads getting frozen when using Zoom, and advice for dealing with that.
- [x] Add some notes about when to pivot during an assistive technology session.
- [x] Add some more notes on how to prepare for sessions with screen readers.

## Definition of Done
- [x] New documentation reviewed by Eileen and Ruben.
- [ ] Documentation reviewed by at least one accessibility specialist.
- [ ] Content is updated on Platform website pages.

**Comment by davidakennedy** [comment]
Added first PR for page update to the "Research with assistive technology users" page. PR: https://github.com/department-of-veterans-affairs/va.gov-team/issues/78195

**Comment by davidakennedy** [comment]
Added another PR for splitting up the "Screen reader checklist" page and adding new content. PR: https://github.com/department-of-veterans-affairs/va.gov-team/issues/78266

**Comment by davidakennedy** [comment]
Noting that this is blocked, awaiting the Platform team to process and complete the PRs.

**Comment by saderagsdale** [comment]
@davidakennedy Any news on this one?

**Comment by davidakennedy** [comment]
@saderagsdale Nothing exciting. The team looked at both issues and added them to their backlog.

**Comment by saderagsdale** [comment]
@davidakennedy can we close, or do you wan to track it on a different swimlane?

**Comment by davidakennedy** [comment]
@saderagsdale I'm cool with closing. We did our part, it's just waiting in Platform's backlog. I put the PRs on my personal to do list to check in on regularly.
