### ISSUE TITLE
SC | Resolve authorization requirements for ITF creation

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#77455]
## Value Statement
**_As a_** Veteran
**_I want to_** create an ITF without an unnecessary 403 Forbidden error
**_So that_**

## Background Context
Based on investigations for https://github.com/department-of-veterans-affairs/va.gov-team/issues/72813, we found that the `403 Forbidden` errors we've seen from attempted ITF creations are likely coming from some [EVSS related code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/intent_to_files_controller.rb#L13) that might not be needed anymore because:
1) we've [fully migrated to using Lighthouse for ITF](https://dsva.slack.com/archives/C04KW0B46N5/p1696276912920519) and 
2) those restrictions were due to [needing specific values for the EVSS request header](https://dsva.slack.com/archives/C1VBAHWQL/p1678291501111909?thread_ts=1678226265.946689&cid=C1VBAHWQL), but Lighthouse doesn't require them

## Outcome, Success Measure, KPI(S), and Tracking Link
- [ ] Reduced number of `itf_creation_failed` 403 errors in Sentry/DataDog

## Acceptance Criteria
- [ ] A user that would fail this EVSS policy call (i.e. they're missing data that used to be used for creating an ITF through EVSS) is able to create an ITF without a 403 error

## Tasks
- [ ] Confirm technical approach with the right team (526?) — i.e. whether we can swap the EVSS policy check with the [Lighthouse policy check](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/policies/lighthouse_policy.rb#L4-L6)
  - ~Note: Double check with Lighthouse on the veteran data that their API requires (i.e. confirm if it's just participant id and icn)~ Need to have `participant_id`, `ssn`, `name`

## Definition of Ready 

- [ ] We've validated our solution approach for removing the EVSS restrictions (talk to Thomas and Sam)
- [ ] We've confirmed that the approach won't break anything 

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by anniebtran** [comment]
We are punting on this for now, going to keep this ticket open as a reminder to check on the other teams and see where they're at with this work

**Comment by anniebtran** [comment]
Last time I checked with Thomas Blackwell, I heard this is on Pension team's plate. Will follow up with them and check on how things are going

**Comment by anniebtran** [comment]
Talked to Lighthouse to confirm what requirements they need for ITF (compared to the existing EVSS policy that we are currently using):

> Our Intent to File service does not require the edipi or birls_id. However, both of those are required for the 526 submission.
Their identity must exist in MPI with a valid participant id, ssn, and name.


[Link to Slack thread](https://dsva.slack.com/archives/CE6UEJ6BZ/p1717100090559599)

**Comment by anniebtran** [comment]
Confirmed with Thomas that we don't need the `edipi` and `birls_id` for ITFs on 526, so I'll work on adding an updated policy to check for participant_id, ssn, and name as outlined by LH above

**Comment by anniebtran** [comment]
Validated that the most recent alerts from our ITF monitor that involve 403s are being triggered because of a user not meeting the updated criteria (often they are missing a participant_id). Gonna go ahead and close this ticket and if we need to update anything else to reduce the noise, we can open a new one
