### ISSUE TITLE
FE | EDU CH33 Migration | Build out Post-Migration States (mini Epic)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#77466]
## Background 
The goal of this mini-epic is to incorporate any UI changes for the post 4/20-5/15 downtime period. 

In other words, this ticket will result in a new UI that will only be reflected AFTER the CH33 migration to CorpDB is completed. 

## Mock ups
- [User flow and high fi mobile screens](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=347-7871&mode=design&t=IqFCCEPhlqqHC8uj-11)

## Tasks 
The toggle for this work is `profile_show_direct_deposit_single_form`

Scenario 1 - has access + add new dd info
- GIVEN a user that has C&P, EDU, or BOTH set to yes 
- AND they haven't entered DD information previously
- WHEN they navigate to the DD screen 
- THEN enable [the form for ADDING ](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=276-13270&mode=design&t=VjmrG2TjXdbNnoGm-4)
- AND no bank deposit info should be present

Scenario 2 - has access + edit dd info
- GIVEN a user that has C&P, EDU, or BOTH set to yes 
- AND they have entered DD information previously
- WHEN they navigate to the DD screen 
- THEN enable [the form for EDITING](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=347-7876&mode=design&t=VjmrG2TjXdbNnoGm-4)
- AND prior bank deposit info should already be present

Scenario 3 - doesn't have access
- GIVEN a user that doesn't have access to C&P or EDU benefits 
- WHEN they navigate to the DD screen
- THEN [disable the form and display the ineligible state](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=239-9463&mode=design&t=VjmrG2TjXdbNnoGm-4) 

### What is the LH behavior ([see slack thread](https://dsva.slack.com/archives/C06JV0KHZNF/p1710356444358989))

1. All existing control information checks (refer to API schema doc) are performed in addition to checking the eduClaimInd value (true, false). 
2. For  "can Update directdeposit" field = True: one of these indicators must be True:  "corpAvailInd" OR "eduClaimiInd," AND existing control information checks must be true.
3. The LH API response includes the "eduClaimInd" field (values are True, False).

- If **corpAvailInd = True** then we can assume a user has C&P benefits
- If **eduClaimiInd = True** then we can assume a user has EDU benefits

#### Swagger documentation for the LH behavior 

`canUpdateDirectDeposit`
boolean
example: true
Most control information elements in the GET response must be "true" for POST to be successful. However, with "isEduClaimAvailable" and "isCorpAvailable", the presence of either being true suffices for a successful POST, as they operate under an OR condition.

## What's the process today 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/b1f7d6ec-d855-4255-b81f-0007d9993dd3)

``` 
data: {
    id: '',
    type: 'hashes',
    attributes: {
      controlInformation: {
        canUpdateDirectDeposit: true,
        isCorpAvailable: true,
        isCorpRecFound: true,
        hasNoBdnPayments: true,
        hasIdentity: true,
        hasIndex: true,
        isCompetent: true,
        hasMailingAddress: true,
        hasNoFiduciaryAssigned: true,
        isNotDeceased: true,
        hasPaymentAddress: true,
      },
      paymentAccount: {
        name: 'BASE TEST - DISABILITY COMPENSATIONS',
        accountType: 'CHECKING',
        accountNumber: '*******5487',
        routingNumber: '*****1533',
      },
    },
  },

```

## Diffs Docuemnt  
- [direct deposit unification document where Adam audited the FE functionality](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a4d13d9a27115b8d771897d682073e6062a02b2f/products/identity-personalization/engineering/discovery/direct-deposit-unification.md) 

# Acceptance Criteria 

- [x] we've got new UI behind a feature flag for the post migration world
- [x] View payment information is visible on the DD page for all users regardless 
- [x] Copy is updated for the form with generic language 

### **MHV/DSLogon users** 
- [x] see identity verify alert with expanded information about credential retirement - UPDATE I added the content about credential retirement to the alert but did make it conditional on the retirement toggle.

### **Not eligible users** - 
- [x] we're using the `canUpdateDirectDeposit` control information
- [x] Do we still need to check other conditions like we are doing currently? `signInServicesEligibleForDD.has(signInService) && isInMVI && is2faEnabled` these may not really be needed if we determine that the control information is really where we should be looking regardless. If they aren't in MVI or dont have 2FA set up then maybe we should stop the request from even happening?
     - [x] ie. if 2FA isn't present we're not requesting DD information
- [x] The not eligible content needs to be outside of a ProfileInfoCard component and should just be in the page content.
- [x] Should NOT show the fraud summary box
- [x] no change to the fiduciary flag functionality  
 
### **Eligible users and currently enrolled users** summary of UI changes
- [x] Profile info card will have the title 'Bank account information'
- [x] Edit / placeholder info is the same as prior UI
- [x] Fraud summary box adds a heading and stays where it is in the original mocks below bank info and above the VA payment history card (this is based on Samara's guidance we should leave this right after the Bank Account information and should NOT move this)
- [x] Form edit state has slightly updated content: 'Please provide your bank’s routing number as well as your current account and type. '
- [x] Account number field now says: Account number (No more than 17 digits)
     - [x] reconfirm our validation rules an account number cannot be LESS than 4 or more than 17
     - [x] current from if a user tries to save with more than 17 it says please add an account number so lets make sure we fixed that
- [x] Aria label for the form wrapping div is set to `aria-label={`Edit bank account for ${sectionTitle.toLowerCase()}`}` so we need to make sure that is changed to be correct for single form
- [x] Error messages need a title added to the alert. I'm not sure if this was something that was added or was missed in previous UI iterations
- [x] #81557
