### ISSUE TITLE
[CDP] Wrap all cards in a ul and combine card title and amount to make cards for screenreader friendly

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#77460]
## Description

As a screenreader user, I need to be able to navigate the debt portal easily and understand the cards better. During the latest CDP study, a screenreader user got confused when navigating the CDP and reading the [debt cards](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76030#issuecomment-1971529621). The user was confused at the amount because it was in its own heading. Then the heading below showed the title:

```
    <va-card
      show-shadow
      class="vads-u-padding--3 vads-u-margin-bottom--3"
      data-testid={`balance-card-${id}`}
    >
      <h3
        aria-describedby={`copay-balance-${id}`}
        className="vads-u-margin-top--0 vads-u-margin-bottom--1p5"
        data-testid={`amount-${id}`}
      >
        {currency(amount)}
      </h3>
      <h4
        id={`copay-balance-${id}`}
        className="vads-u-margin-top--0  vads-u-margin-bottom--1p5 vads-u-font-weight--normal"
        data-testid={`facility-city-${id}`}
      >
        {facility} - {city}
      </h4>
``` 

We'll need to combine the amount and the title across all the parts of the portal (overview, copay list, debt list) pages. 

Based on the [VADS guidance](https://design.va.gov/components/card#accessibility-considerations) we'll also need to put the cards in a `ul` to give it more context. 

Given: A screenreader user navigates the combined debt portal
When: A screenreader user reads a debt card
Then: The card should contain the amount and the title of the debt on one line to give it proper context

## Tasks
- [x] Update all the cards in Figma to combine the amount and title
- [x] Updated CDP files to combine amount and title
- [x] Wrap each card (overview, debt card, copay card) in a list item and add a `ul` to wrap them

## Acceptance criteria

- [x] Figma screens are all updated
- [x] All cards are wrapped in an `li`
- [x] All cards titles and amounts are on one line

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@Tom-Davis @HeatherRienks, just created the a11y ticket for the debt portal based on the feedback we received from CAIA and our screenreader user participant. I put it in this sprint and put it under the ongoing maintenance epic and assigned it to myself. Does that all look alright? 

cc: @charlottecesana @mgleo

**Comment by HeatherRienks** [comment]
Looks good to me @josephrlee  :) Thanks for creating!
