### ISSUE TITLE
Remove orientation slide decks from Platform Website

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#77477]
## User Story
As a VFS team member using GFE or on the VA network, I want to be able to view the orientation materials so that I can complete all Platform Orientation tasks.

Assignee: @it-harrison 
Peer Reviewer: @erinrwhite 

## Description
Per recent direction from Platform leadership, anything stored within the Platform Google Drive folder should not be shared out because they cannot be accessed from the VA Network and/or any GFE. This means that the slide decks associated with Platform Orientation must be taken down from Platform Website and will no longer be made available to VFS teams. The slide decks are also shared via the orientation session recordings, so there should not be any knowledge gaps.

**Note:** per Governance refinement on 3/12, it was noted that sometimes orientation hosts reference the slide deck because of all the links to resources. As an interim solution, Governance team will add links to the Description section of YouTube, and/or reference the New VFS Team Member ticket if the links are already included there. This will be reflected in ticket #64117 (for re-recording the General Orientation and Collaboration Cycle orientation) and will be added to the operational guidance per ticket #76802.

## Impacted Artifacts
[Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)

## Tasks
- [x] Within each table, delete the row for Slick deck, including the deck itself
- [x] Publish the page to Platform website
- [x] Announce on #Platform-team channel for all Platform Orientation hosts that the slide decks have been removed from Platform Website since they are not available to any VFS and/or OCTO team members on GFE or the VA network
- [x] Coordinate with Shira since #64117 will be worked on in parallel

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The orientation slide decks are no longer accessible from Platform Website

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman - this is a [copy](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3030450180/Copy+of+Orientation+Sessions) of the orienation sessions page that I am updating

**Comment by it-harrison** [comment]
@erinrwhite - I have added links to slides to all of the YouTube description sections but ATO does not have a YouTube presentation. I'm not sure where to put the link...do you have any idea?

**Comment by shiragoodman** [comment]
@it-harrison don't worry about the ATO orientation slide deck. The ATO orientation is still scheduled adhoc. I met with the Platform Security team yesterday and talked to them about recording an orientation that can be viewed by all so they no longer have to do it on-demand, and ALL new VFS team members can view it (not just new teams).

**Comment by erinrwhite** [comment]
@it-harrison Changes are looking good here! All links from the YouTube videos to the slides are working. But question: should we add the links to the slide decks themselves, or add the individual links found within the slide deck, to the video descriptions? It might make sense to do both of these things so that folks who aren't on GFE can still access the slides, but everybody can access the links within the slides from the video description. cc @shiragoodman

**Comment by shiragoodman** [comment]
that's a good question... however I'm not sure Platform leadership would approve. The problem is that we're sharing Google Drive links with VFS/OCTO (AKA outside of Platform). Even though this would be shared via YouTube, and not Platform Website, we're still sharing them regardless.

**Comment by shiragoodman** [comment]
per discussion with Andrea, we cannot add the links to the YouTube description. IF we did want to share the slide decks, we would have to do it via Sharepoint.
