### ISSUE TITLE
Spike: Explore deployment information tracking in DataDog

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#77478]
## Issue Description
Context: https://dsva.slack.com/archives/CMJ2V70UV/p1708624702424259

Explore the possibility of having our deployment information moved (or additionally copied) to DataDog to allow for dashboards to be annotated based on deployment events. 

---
## Tasks
- [ ] Research the possibility of having our deployment information moved (or additionally copied) to DataDog
- [ ] Document findings

## Acceptance Criteria
- [ ] We've documented whether this effort is achievable or not. 
- [ ] If deemed achievable, a ticket has been created for implementation.
