### ISSUE TITLE
[Congressional] V11459509 Due 3/20/24 (Rep. Frillman) 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#77472]
## Issue Description
 The Veteran applied online for disability on the VA's website and  was prompt to enter a EAIPI - BIRLS ID code and was provided a toll free number 800.698.2414. The Veteran called and was told it was a VA mistake and was given a ticket # 11900602. Veteran was informed he would be contacted by a repair team via email but didn’t receive a response.
https://app.slack.com/client/T03FECE8V/C02BS78NYRM?selected_team_id=T1ZD0UBMZ

---
## Tasks
- [x] _What work is necessary for this story to be completed?_- [ ] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
FYI: The due date will change to the full 30 day turn around. Will update once it's been approved.

This is another EVSS.  They update the issues with EDIPI /BIRLS ID.
I'll get it to Jeremy and CC you.

Details have been sent to the EVSS group for review and resolution.

**Comment by Kimberley2023-CSM** [comment]
2/29/24 - Jeremy sent email notification of receipt of the Congressional.

**Comment by Kimberley2023-CSM** [comment]
**Update 3/6/24:** Issue was logged in Salesforce originally as case#11900602, EVSS has logged it internally as ETSHD-2462, for tracking and recording purposes of the congressional inquiry. We have resolved the veteran’s errors, and after multiple attempts to contact them, we just received a resolution confirmation email from them, and it is attached. We were also able to confirm in our log files.

Case closed!

**Comment by ATMiddleton** [comment]
Case Closed: EVSS was able to resolve issue. Veteran confirmed via. email that they are able to log into their account successfully. (edited)
