### ISSUE TITLE
Log types of evidence requests in DataDog

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#77493]
## Open Questions
- If we were to create better descriptions of these requests, how might we prioritize tackling them?
- Should we also log status of tracked items? Log tracked item id, and claim id.
---
## Tasks
- [x] Count and track types of evidence requests
- [x] Log tracked item it
- [x] Log claim id

## Acceptance Criteria
- [x] Evidence requests are logged
- [x] Tracked item id is logged
- [x] Claim id is logged
- [x] Evidence requests are visibly legible in a dashboard
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherWidmont** [comment]
@jerekshoe to review today

**Comment by samcoforma** [comment]
@HeatherWidmont This just got merged. What's left is for me to confirm that it's being logged and to create a chart representing the data.
