### ISSUE TITLE
Toxic Exposure Pages Remediation

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#77508]
## Overview
Toxic exposure pages were unexpectedly displaying in production prior to release, due to a [bug](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/77432) with the depends logic and reading the toggle. Investigate impact and any follow up needed.

[slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1709315220386059)

## Tasks
- [x]  Identify how many veterans saw the TE questions on the form
- [x]  Identify how many veterans during that time period actually input data into the toxic exposure fields and whether we've retained that data in the SavedClaim record in the DB - see if the veteran skipped, said no, or said yes and went through the remainder of the questions. 
- [x]  Prepare notes for timeline for postmortem of incident
- [x]  Summary of which TE pages were available during the incident, with screenshots, in order

## Acceptance Criteria
- [x] Complete tasks above
- [x] Save queries used above for future use
- [x] Create a wiki page to document

**Comment by christinec-fftc** [comment]
Unreleased pages that were viewable by veterans

1. /disability/file-disability-claim-form-21-526ez/toxic-exposure-conditions
The checkboxes of conditions here will depend on the new conditions the Veteran added earlier on in the form
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMittQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31551b31b2e44354e829d5bf17e1e9286025ea9a/image.png" alt="image.png" />

The bug was incorrectly showing this page for CFI (claim for increase), so some Veterans may have seen this (without any conditions)
<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM09tQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d7fa6fb50eebef4d2a7e01d08e9fcbe8312fcb8/image.png" alt="image.png" />

2. /disability/file-disability-claim-form-21-526ez/gulf-war-hazard-1990
If the Veteran selected any of their new conditions as related to toxic exposure, then they would have also seen this page
 <img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ltQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad1f17ab9c243f8a9a65c0338ef7f43c93ae649c/localhost_3001_disability_file-disability-claim-form-21-526ez_gulf-war-hazard-1990%20%281%29.png" alt="localhost_3001_disability_file-disability-claim-form-21-526ez_gulf-war-hazard-1990 (1).png" />

**Comment by tommasina-va** [comment]
Adding a to-do for later: check on whether or not we need to filter the toxic exposure condition names coming back in the payload params on DataDog.

**Comment by christinec-fftc** [comment]
Summary

- Wiki page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/toxic_exposure_remediation_research.md

- In Datadog, the `http.referer` was used along with a group by `uuid` to find how many Veterans viewed the TE pages. This was added to a [new dashboard](https://vagov.ddog-gov.com/dashboard/xyc-3md-hqm?fromUser=true&refresh_mode=paused&view=spans&from_ts=1709020800000&to_ts=1709366340000&live=false)
**How many Veterans viewed the TE pages: 7,034** 

- This next query was difficult to do in Datadog, so we moved to Argo. We wrote a small script to discover how many saved claims had TE data 
**How many saved (submitted) claims had a TE checkbox filled out:  5,842**

- This final query was also difficult to do in Datadog, so we created another, similar script
**How many in progress claims (as of yesterday afternoon 3/4/24) had a TE checkbox filled out: 1,483** 

Note: these last two numbers are slightly larger than the overall views. That is because Veterans sometimes submit more than one claim. Trying to de-dup the saved and in progress claims by uuid was a challenge.

**Comment by christinec-fftc** [comment]
Investigation completed at this time. We can reopen or create a new ticket if we need to dig into this further.

**Comment by christinec-fftc** [comment]
Digging up old pr's, it looks like the bug was present from 2/27/24 - 3/1/24
