### ISSUE TITLE
BE | EDU CH33 Migration | Confirm Email Behavior (VA Notify)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#77516]
## Background 
Currently, the C&P and EDU direct deposit forms are separate.  So when a user updates their direct deposit info, they receive an email confirmation stating that the account information was updated.  The email message specifies whether the update was for C&P or EDU.

These two separate direct deposit forms are being merged into a single form.  We need to make sure that users receive the correct email notification when direct deposit information is updated. [Original Message from slack](https://dsva.slack.com/archives/C909ZG2BB/p1709315427287269).

Both forms use their own VA Notify email template.

## Outstanding Questions
1. What do we want to show if a user has both C&P and edu benefits? Should we just not specify? Example:
> We’ll use your updated information to deposit any benefits you may receive. 

We think the email notification should just inform the user of the direct deposit update, but not specify whether it relates to C&P or EDU.

2. Does the existing template need to be changed?

Yes. Changes are necessary.

## Tasks
- [ ] Contact Melanie Jones (VA Notify Team) and review the template changes and how those are promoted to production.

## Acceptance Criteria 
- [x] Document the decision. -  w're creating a new template that is benefit agnostic 
- [x] Make sure this outcome is added to QA script for testing.
- [x] make sure this is added to the UAT convo guide/research plan
- [x] Create any necessary BE tickets.

**Comment by mtcA6** [comment]
@mtcA6 check in w/'Melanie Jones and Kyle w/VA Notify

**Comment by mtcA6** [comment]
I submitted ticket #80019 for va notify and initiated a conversation in the edu migration  slack channel.

**Comment by mtcA6** [comment]
we have the following stories in the backlog 
- #80210
- #80818
