### ISSUE TITLE
Clean up the widget pattern in the "static-pages" code

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#7751]
We have a single JavaScript bundle for handling the site-wide content experience, referred to as `static-pages`. There, we have a pattern defined for rendering widgets per-page, loading a widget's code only when the page contains an element for that specific widget. However, some of the widgets don't follow that pattern properly.

## Tasks
- [x] Convert the "social share links" to a typical widget
- [x] Convert the "alerts-dismiss-view" to a typical widget
- [x] Convert the "ics-generator" to a typical widget
- [x] Convert the "createMyVALoginWidget" to a typical widget
- [x] Consider restructuring the directory to reflect "widget creators" instead of having them spread out across various directories
- [x] Make sure all `data-widget-type` values are stored in the constant file, `widgetTypes.js`
- [x] Consider moving the CTA widget code from `platform/site-wide` into `static
- [x] There is a lot of repetition of registering widgets in `static-pages-entry`. We should consider whether we can create an iterator to enforce future widgets follow the correct pattern.

## Acceptance criteria
- [x] `static-pages` bundle is more maintainable
- [x] Tech debt has been reduced

**Comment by brianalloyd** [comment]
Plan to pull into sprint post react widget refactor effort [#25036](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7751)

**Comment by Rleahy22** [comment]
This should go out with the deploy on 9/2. It affects the following widgets but should have no impact:
social share links
alerts-dismiss-view
ics-generator
createMyVALoginWidget

**Comment by brianalloyd** [comment]
Completed, closing in support.
