### ISSUE TITLE
[EPIC] 10-10EZR: Add Military History to EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77527]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Veteran, I would liked to provide updates to my Service history so that the VA can check to see if I'm eligible for new/improved benefits based on the PACT Act.

As a Veteran, I would like to re-submit my service information so that it can be re-reviewed by the VA to determine if I am now eligible for healthcare/an increased Priority Group.

## Hypothesis or Bet
If we allow Veterans a place to self-report Service History online, then more Veterans will have access to the care they've earned. 

If we allow Veterans to provide TERA information online, then we will see a reduction in paper EZR forms submitted. 

**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

EZR TERA Questions EZR:
[Uploading... VA Form 10-10EZR (8).pdf]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
AS: Will start on this, the situation is evolving rapidly

## High Level User Story/ies
As a Veteran, I would like to update my Toxic Exposure (TERA) information online so that my Priority Group is reflective of my experience when I served.

As a Veteran, I need to be able to update my Toxic Exposure information online so that my Providers know to look for underlying health conditions related to my service. 

As a Vereran, I would liked to provide updates to my Service history so that the VA can check to see if I'm eligible for new/improved benefits based on the PACT Act.

## Hypothesis or Bet
If we allow Veterans to provide TERA information online, then we will more Veterans eligible for more VA Healthcare (rise in Priority Group).

If we allow Veterans a place to self-report Service History online, then more Veterans will have access to the care they've earned. 

If we allow Veterans to provide TERA information online, then we will see a reduction in paper EZR forms submitted. 

**If** _we make this change_ **then** _we expect this to happen_.

## OKR

1. Get more Veterans enrolled in VA care via expanded criteria outlined in the PACT Act
2. Reduction in paper 10-10EZRs
3. Increase in online 10-10EZR submissions (compared to 100% rollout without TERA)

_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

A Veteran can fill out the TERA questions and provide dates to their Toxic Exposure, and self-report updates to Military History. Both of these are used to update the Veteran's VES record and update their Priority Group and EHR record (where applicable). 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by hdjustice** [comment]
Closing this epic.  We can revisit if this is a requirement in the future.
