### ISSUE TITLE
AWS access for [Austin S]

### ISSUE THREAD

**Issue by ashin97** [department-of-veterans-affairs/va.gov-team#77525]
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Austin Shina

### Your Email

ashin97@live.com

### Team, Role, and Company of the target individual

VSO

### Product Manager (PM) name and email

ashin97@live.com Austin

### Product Owner (PO) name and email

ashin97@live.com Austin

### Desired AWS Access

I need access to the benefits API to assist veterans with claims

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

confirmed

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.
```[tasklist]
### Tasks
```
