### ISSUE TITLE
Research: Google Analytics Tracking for Pages with Links to Google Drive

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#77558]
## Issue Description
Research Vicky Bellisimo's method for tracking pages containing links to Google Drive documents. 

## Related Context:
Vicky said "But it may be something someone in the Platform Analytics team may know how to do. I remember I did it directly from Google Analytics. I think it was related to the “events” functionality and filtering the URLs based on the domain they were linking to."

---
## Tasks
- [x] Using Google Analytics, try to recreate path for monitoring pages with Google Drive links
- [x] Ask Vicky how she figured out how to find out which confluence documents have links to certain pages and if she could show you

## Acceptance Criteria
- [x] We will have a page on google analytics that tells us which documents have links to google drive
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@laucon please add your estimate for the work done. Please also refine as to any additional steps taken, and Acceptance Criteria for closing the ticket.

**Comment by jknipes** [comment]
All tasks complete, moving to _Done_
