### ISSUE TITLE
Review Platform Feedback instances and share

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#77561]
## Purpose
Review responses and follow processes to make sure they are viewable in Domo and communicated to relevant parties

## Tasks
- [x] Follow this [response parsing process](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2756476930/Parsing+Platform+Feedback+entries)
- [x] Use [this guide](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2987688314/Internal+Guide+Delivering+VFS+qualitative+feedback+to+Platform) to locate the applicable team and the included template to contact said team

## Acceptance Criteria
- [x] All responses have green checkmark emojis
- [x] Responsible team has been contacted
