### ISSUE TITLE
Content review request from Cartography Team, newsletter signup interaction

### ISSUE THREAD

**Issue by danbivins** [department-of-veterans-affairs/va.gov-team#77563]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

## About your team

-**Team name**: Cartography team
-**OCTO product owner**: Patrick Bateman
-**Product name**: MHV landing page
-**Product manager**: Wes Rowe
-**Slack channel**: mhv-on-vagov-cartography-team
-**Dedicated a11y specialist on your team (if you have one):**  Dan Bivins
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [x] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Our newsletter signup section has these issues:
- Once the user completes the newsletter sign up, there is no clear path back to VA.gov
- Security: the VAgov session remains active even after the form submission navigates the user to the GovDelivery website for newsletter signup. Leaving the VAgov tab open will help Veterans realize this behavior.
- A11y: the current single-field sign-up form on the MHV landing page is not materially honest about its function (navigating to a new page when selecting "Subscribe")
- A11y: The CTA button has inaccurate link text. The word "Subscribe" is not accurate - the email address provided by a user does gets added into the first form field on the GovDelivery signup page, but nothing is submitted in this process

To address these issues we are recommending: 
1. Remove the form field & button from the design. 
2. In its place, insert paragraph text underneath the H2 on the MyHealtheVet landing page to describe the newsletter and what value it provides the Veteran. 
3. Include a secondary action link that opens in a new tab to route the user to the GovDelivery page where they can sign up.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We've completed discovery and have crafted copy, but are now hoping for review and feedback.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.

### Current implementation
<img width="783" alt="Screenshot 2024-03-04 at 1 39 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10236001/f95177b9-ca1c-45f6-8610-43ea319d380e">
The image shows a heading that says "Subscribe to get My HealtheVet updates" with an Email address text field below and a "Subscribe" button below the input field.

### Proposed design
<img width="839" alt="Screenshot 2024-03-04 at 1 56 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10236001/12c435a1-ca17-4f98-8335-2fd2fbee46f5">
The image shows a heading that says "Subscribe to get My HealtheVet updates" with a line of text under that heading saying, "Get the updates you need to manage your health care by signing up for our biweekly newsletter." Underneath this text is a chevron icon pointing to the right and link text next to it saying "Subscribe to the MyHealtheVet newsletter (at GovDelivery.com)". The link would point directly to https://www.myhealth.va.gov/subscribe

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA operations
- [ ] Initial Review - @coforma-terry and @strelichl 
```

```[tasklist]
### CAIA a11y tasks
```

```[tasklist]
### CAIA content tasks
```

```[tasklist]
### CAIA IA tasks
```
