### ISSUE TITLE
[DevOps] Process Knowledge Share findings

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77567]
## User Story
As a DevOps engineer, I want to process the findings from knowledge shares with different discipline areas so that I can create an actionable plan for addressing their challenges.

This is a followup to:
- #77255
- #77256
- #77258
- #77259

This is blocked by:
- #77161
- #77265
- #77367
- #77368
- #77370

The aforementioned knowledge shares will hopefully provide me with a list of challenges faced by the team. Based on those, I should be able to define clear and achievable objectives and pair them with some metric that will help me measure the impact of improvements.

## Tasks
- [ ] [DevOps] Collate knowledge share outputs and list challenges.
- [ ] [DevOps] Define objectives based on those challenges.
- [ ] [DevOps] Select metrics that will reflect improvements.

## Acceptance Criteria

- [ ] Workflows and processes facing challenges have been documented in this thread, along with objectives to improve those workflows and processes and metrics that can reflect those improvements.
- [ ] Followup tickets have been opened to address automating data collection for relevant metrics.
