### ISSUE TITLE
[DevOps] Draft desired state for CIE product Datadog monitoring

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77564]
## User Story
As a DevOps engineer, I need a clearly defined desired state for Datadog monitoring so that I can identify deficits and move us forward.

Certain resources are on one Datadog instance, others are on the other, so I'd like to get a clear picture of what we're recording. 

Obv the answer here is record basic DevOps metrics, but I'm not quite sure yet how finely to slice our products; haven't looked at the current delivery mechanism, which I've heard involves SAM. So I might have several things to iterate on. It's better to get this done sooner rather than later.

## Tasks

- [ ] [DevOps] Achieve a good understanding of how current products are actually delivered and how that should be subdivided, if appropriate.
- [ ] [DevOps] Draft desired items per-deliverable and document in this thread:
  - [ ] metrics
  - [ ] monitors
  - [ ] alarms
  - [ ] dashboards
- [ ] [DevOps] Follow up by determining actual state from existing Datadog monitoring (see separate ticket).

## Acceptance Criteria

- [ ] List of distinct product deliverables has been determined, with a corresponding list of metrics, monitors, alarms, and dashboards for each.

**Comment by ndouglas** [comment]
I'm not going to have time for this; closing.
