### ISSUE TITLE
[DevOps] Discovery on actual state for CIE product Datadog monitoring

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77565]
## User Story
As a DevOps engineer, I want to determine the actual state of CIE product Datadog monitoring, so I can compare it with the actual state and move us forward.

Followup to #77564. I'm aware we already have some good application monitoring in place, and a dashboard that looks pretty good, but I'd like to figure out what else we have available.

## Tasks
- [ ] [DevOps] See what assets we have in the Tevi Datadog relevant to our products and document them in this thread.
- [ ] [DevOps] See what assets we have in the Vagov Datadog relevant to our products and document them in this thread.
 
## Acceptance Criteria
- [ ] Relevant assets from both Datadog instances have been documented in this thread.

**Comment by ndouglas** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/analytics#readme

**Comment by ndouglas** [comment]
I'm not going to have time for this; closing.
