### ISSUE TITLE
[DevOps] Baseline data collection for CIE DevOps improvements

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77570]
## User Story
As a DevOps engineer, I want to collect data about processes and workflows reflecting the status quo so that changes (specifically improvements) to those processes and workflows can be meaningfully evaluated.

The chief outcome from #77567 should be a collection of tickets detailing data that can be gathered in an automated fashion to reflect challenges to current processes and workflows. It's possible that those are already being tracked and we already have sufficient data to establish a baseline, but, if that is not the case, we should gather that data.

## Tasks

- [ ] [DevOps] For each metric, determine whether we currently have sufficient background data to reflect some reasonable approximation of a baseline.
- [ ] [DevOps] If not, determine what would constitute sufficient data and document it in this thread.
- [ ] [DevOps] Keep this ticket open to account for attention to this and maintain a list of those metrics so that they (and the things they represent) can be addressed as soon as possible, or open a copy each sprint and close the old one.

## Acceptance Criteria

- [ ] All metrics have a sufficient baseline of collected data available in Datadog to serve as a comparison for future action.

**Comment by ndouglas** [comment]
I'm not going to have time for this; closing.
