### ISSUE TITLE
🚢 Capture Fields Necessary to Automate Pension Eligibility Determinations in the 686c-674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7759]
# Add Mandated Pension Questions to 686c

## Description 
Pension LOB has mandated updates to BGS/ RBPS to enable simple processing of Pension applications via dependency claims. This presents several challenges, since the 686c does not ask questions about income or pension eligibility. 

This will have a few different parts, across domains that are all related. (See mini-epic for this: #7759)

## Considerations
- Helper text for context will be important.

## Outcomes
- When adding dependent, ask an additional (optional) question "Did this dependent have income in the last 365 days?"
_Could be slipped in as a `Yes` / `No` in that section_
- Ask a global (optional) question "Did the household have a total income ~~of less~~ greater than $XXX in the last tax year?"
_Needs more thought...Whole separate page? Include Veterans Info capture screen?_

### Design Tasks 
- [x] Design UX for these questions. Are they inline with existing questions or part of a new "Pension" section? Is there a gate that only shows these questions to eligible users?
- [x] Get final content for the questions and helper text
- [x] Determine which information collection can be leveraged for these questions and add it to the beginning of the application (with the 686c & 674 information collections)
### Frontend Tasks
- [x] Add questions and content to 686c-674 application
### Backend Tasks
- [x] Add fields to form submission (`VnpPtcpntRlnshpWebService::depHasIncomeInd` and `VnpBnftClaimWebService::netWorthOverLimitInd`)
### Product Tasks
- [x] Update call center docs
- [x] Technical and usability testing, or fold into UAT as needed

- [x] Design ticket: #8777
- [x] Frontend ticket: #8779
- [x] Backend effort: #8780
- [x] Product effort: #8783

## Acceptance Criteria
- [x] User can indicate that a dependent has no income
- [x] User can indicate that their household has less than a certain amount of income
- [x] Field results are transferred to RBPS

**Comment by ohgreatkate** [comment]
all tasks appear completed.
