### ISSUE TITLE
Generate Representative Status Widget

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77599]
## Background
It's time!  To start development of the [Representative Status Widget](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=1283-176978&mode=design&t=fP7jQlmtzbi0zHvZ-0)! 

To get started, we'll need to generate a new widget using the `widget` construct, similar to the creation of the React widget we made for the release of our Find a Rep landing page.

## Tasks
- [ ] Generate new widget using the `widget` construct
- [ ] Reply to this ticket with details of the new widget (name, path, etc.)

## Acceptance Criteria
- [ ] A new widget has been generated
