### ISSUE TITLE
Widget State: Authenticated / No Representative

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77601]
## Background

The Authenticated / No Representative state for the [Rep Status Widget](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2268-79606&mode=design&t=fP7jQlmtzbi0zHvZ-0).  

**A note on headers:**
1. The ideal default logic would be "one heading below it's parent", so the Widget can play nicely with heading structure no matter where it's placed
2. Allow for a custom heading level, to account for scenarios when the heading level may need to be manually set, depending on the surrounding context.  Examples:
   1. https://www.va.gov/health-care/get-medical-records/ - subsection under “Use VA Blue Button to manage your records online”
   2. https://www.va.gov/health-care/schedule-view-va-appointments/ - its in its own section, right under the H1 and subtitle

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzN1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cfb081326c1582d6a8adf9c0d320b1a47dcf512/image.png" alt="image.png" />

<img width="315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d202116882c76e54a3d77273bcbc279291ec94de/image.png" alt="image.png" />
<img width="309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2JQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37078ee90d4ab8fb3ff21dc3a0e6c5ac570bf650/image.png" alt="image.png" />

## Tasks
- [ ] Implement the design for the Authenticated / No Representative widget state
- [ ] Implement header logic
- [ ] Link to the forthcoming FAQ page, URL is `https://va.gov/va-accredited-representative-faqs`
- [ ] Connect this widget state to the appropriate backend response
- [ ] Update unit tests

## Acceptance Criteria
- [ ] As an authenticated user, I want to understand if I do not have representation, so that I can view FAQs and learn more about accredited representatives.

**Comment by cosu419** [comment]
For review purposes, I temporarily enabled this state in staging by default. It looks like the icons are still not displaying. 

<img width="1490" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWM4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--292b87966de8f568c461f8e75a335d1858b5a7c7/image.png" alt="image.png" />

[This ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2353) seems to be an outstanding issue.

**Comment by oddball-lindsay** [comment]
Asked about the icons in Slack: https://dsva.slack.com/archives/C0NGDDXME/p1712603063701469
