### ISSUE TITLE
Prepare for Chapter 36 design intent collaboration

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7760]
### Goal
Review and revise design direction for Chapter 36 screens, including Form 28-8832, ahead of design intent review.

### Considerations
- Mockups are comprehensive and include IA elements

### Tasks
- [x] Review current concept mockups with team
- [x] Incorporate feedback. revise mocks
- [x] Schedule design intent review (Jason)

### Acceptance criteria
- [x] Design intent review meeting scheduled with VSP

**Comment by sporeboy** [comment]
Revisions made to PCPG (Chapter 36) concept screens here: https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/
