### ISSUE TITLE
New endpoint: POA from Lighthouse + rep address

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77606]
## Background
To support the frontend of our [Representative Status Widget](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=1283-176978&mode=design&t=fP7jQlmtzbi0zHvZ-0) we will need to create a new endpoint in `vets-api` that:
1. Retrieves the active POA from Lighthouse 
2. Adds the corresponding address in instances where there is an active POA (individual or organization)
3. Sends the active POA and the corresponding address to the frontend

[Lighthouse API documentation](https://developer.va.gov/explore/api/benefits-claims/docs?version=current) (see the Power of Attorney section at the bottom) -- requires an ICN and a valid token.

The frontend request to the backend is being handled in https://github.com/department-of-veterans-affairs/va.gov-team/issues/77605  

## Tasks
- [x] Create a new endpoint in `vets-api`
- [x] Retrieve active POA from Lighthouse
- [x] When there is an active POA, add the corresponding address to the response
- [x] Send both the active POA and the corresponding address to the frontend
- [x] Reply to this ticket with details of the new endpoint (name, path, confirm logic, etc.)

## Acceptance Criteria
- [ ] When requested by the frontend, the backend will retrieve active POA from Lighthouse, add the corresponding address, and respond with both pieces of information, so that the frontend can display the appropriate widget state.

**Comment by holdenhinkle** [comment]
Lighthouse docs:

https://developer.va.gov/explore/api/benefits-claims/docs?version=current

Example response:
```{
  "data": {
    "type": "individual",
    "attributes": {
      "code": "A1Q",
      "name": "Firstname Lastname",
      "phoneNumber": "555-555-5555"
    }
  }
}
```

Type:
```
string
nullable: true
example: individual
Type of representative, organization or individual
```

I'm requesting Sandbox access to this endpoint...

**Comment by holdenhinkle** [comment]
```
√ poa_endpoint % curl -X GET 'https://sandbox-api.va.gov/services/claims/v2/veterans/1012667145V762142/power-of-attorney' \
--header 'accept: application/json'
{"errors":[{"title":"Not authorized","status":"401","detail":"Not authorized"}]}%                         √ poa_endpoint % curl -X GET 'https://sandbox-api.va.gov/services/claims/v2/veterans/1012667145V762142/power-of-attorney' \
--header 'Authorization: Bearer eyJraWQiOiJyOWtWMjlFRm9uWWY0LTJWTTZrY21YTkhyVlA1NWw4Z3luQ3pNZHF3dmxFIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmIwNERIbDBUTVhsbjZVV1hfME5iQjJjSGZXUkNjOUpTNmhsS3FhZXlaVTQiLCJpc3MiOiJodHRwczovL2RlcHR2YS1ldmFsLm9rdGEuY29tL29hdXRoMi9hdXNkZzdndWlzMlRZRGxGZTJwNyIsImF1ZCI6Imh0dHBzOi8vc2FuZGJveC1hcGkudmEuZ292L3NlcnZpY2VzL2NsYWltcyIsImlhdCI6MTcxMTA0NDA1MywiZXhwIjoxNzExMDQ0MzUzLCJjaWQiOiIwb2F0OWxtdzhsOXBNdWJvZTJwNyIsInNjcCI6WyJzeXN0ZW0vY2xhaW0ud3JpdGUiLCJzeXN0ZW0vY2xhaW0ucmVhZCJdLCJzdWIiOiIwb2F0OWxtdzhsOXBNdWJvZTJwNyIsImxhYmVsIjoiT2RkYmFsbEluY0hpbmtsZS0xNzExMDM1MTUzIn0.L34EuGKkEvHliohDyefgIg4uhQ0ktlY3U6dMCttovMLM3ekmoeJ9Q9dTmEgopOvgwR-aPCnK9Fx2EXmmVr1cJClmPj0oyMy4DQXHPfsl8XoeluXBNCh4PXAatcQRT1ved0nUImzYPkF4proJVTClOtE4e57hLhwuE1HGBxtEFm0fqrEc7FhNUhHhD4EfgY8w6S9ZpIWCAPTjyoQk2-dp2zl3Y9DTsbAf2eAs-LAAndHhfBV4xb4j3h8ovWOPFAffO20Yx8ivOhOV3n7FFnR_4K0qib6ByP3aIY3BzxtUsdlvIi6FRZ7DQL1CJkVFdWD_1SZrHhxCdz6nHTlzkP7G4Q' \
--header 'accept: application/json'
{"data":{"type":"individual","attributes":{"code":"067","name":"Tamara Ellis","phoneNumber":null}}}%      √ poa_endpoint % curl -X GET 'https://sandbox-api.va.gov/services/claims/v2/veterans/1012543145V762142/power-of-attorney' \
--header 'Authorization: Bearer eyJraWQiOiJyOWtWMjlFRm9uWWY0LTJWTTZrY21YTkhyVlA1NWw4Z3luQ3pNZHF3dmxFIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmIwNERIbDBUTVhsbjZVV1hfME5iQjJjSGZXUkNjOUpTNmhsS3FhZXlaVTQiLCJpc3MiOiJodHRwczovL2RlcHR2YS1ldmFsLm9rdGEuY29tL29hdXRoMi9hdXNkZzdndWlzMlRZRGxGZTJwNyIsImF1ZCI6Imh0dHBzOi8vc2FuZGJveC1hcGkudmEuZ292L3NlcnZpY2VzL2NsYWltcyIsImlhdCI6MTcxMTA0NDA1MywiZXhwIjoxNzExMDQ0MzUzLCJjaWQiOiIwb2F0OWxtdzhsOXBNdWJvZTJwNyIsInNjcCI6WyJzeXN0ZW0vY2xhaW0ud3JpdGUiLCJzeXN0ZW0vY2xhaW0ucmVhZCJdLCJzdWIiOiIwb2F0OWxtdzhsOXBNdWJvZTJwNyIsImxhYmVsIjoiT2RkYmFsbEluY0hpbmtsZS0xNzExMDM1MTUzIn0.L34EuGKkEvHliohDyefgIg4uhQ0ktlY3U6dMCttovMLM3ekmoeJ9Q9dTmEgopOvgwR-aPCnK9Fx2EXmmVr1cJClmPj0oyMy4DQXHPfsl8XoeluXBNCh4PXAatcQRT1ved0nUImzYPkF4proJVTClOtE4e57hLhwuE1HGBxtEFm0fqrEc7FhNUhHhD4EfgY8w6S9ZpIWCAPTjyoQk2-dp2zl3Y9DTsbAf2eAs-LAAndHhfBV4xb4j3h8ovWOPFAffO20Yx8ivOhOV3n7FFnR_4K0qib6ByP3aIY3BzxtUsdlvIi6FRZ7DQL1CJkVFdWD_1SZrHhxCdz6nHTlzkP7G4Q' \
--header 'accept: application/json'
{"errors":[{"title":"Resource not found","status":"404","detail":"Unable to locate Veteran's ID/ICN in Master Person Index (MPI). Please submit an issue at ask.va.gov or call 1-800-MyVA411 (800-698-2411) for assistance.","source":{"pointer":"/app/modules/claims_api/app/controllers/concerns/claims_api/targ√ p√ p√ p√ poa_√ poa_√ poa_end√ poa_√ poa_√ poa_√ p√ p√ p√ p√ poa_endpoint % 
```

**Comment by oddball-lindsay** [comment]
Creating a lighter service class within our own module to manage the connection to these endpoints

**Comment by holdenhinkle** [comment]
This is done (except for recording the VCR cassette).

New endpoint - `representation_management/v0/power_of_attorney`

Current routes for the `representation_management` engine:

```
Routes for RepresentationManagement::Engine:
v0_flag_accredited_representatives POST /v0/flag_accredited_representatives(.:format) representation_management/v0/flag_accredited_representatives#create {:format=>"json"}
        v0_power_of_attorney_index GET  /v0/power_of_attorney(.:format)               representation_management/v0/power_of_attorney#index {:format=>"json"}
```
