### ISSUE TITLE
Widget State: Authenticated / Error

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77604]
## Background

The Error state for the [Rep Status Widget](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2268-79606&mode=design&t=fP7jQlmtzbi0zHvZ-0).  This will be displayed for any errors (any non-success `200` instances), which we will track in Sentry.

**A note on headers:**
1. The ideal default logic would be "one heading below it's parent", so the Widget can play nicely with heading structure no matter where it's placed
2. Allow for a custom heading level, to account for scenarios when the heading level may need to be manually set, depending on the surrounding context.  Examples:
   1. https://www.va.gov/health-care/get-medical-records/ - subsection under “Use VA Blue Button to manage your records online”
   2. https://www.va.gov/health-care/schedule-view-va-appointments/ - its in its own section, right under the H1 and subtitle

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEh1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c41fe5d9534824b5ce5c43d87d8d82fbea99988/image.png" alt="image.png" />

<img width="422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52682e99024256a9123287820a7f51abe529cd57/image.png" alt="image.png" /> <img width="428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25WQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2696d3a1e076a36d5800aa7758eaef091da65cb/image.png" alt="image.png" />

## Tasks
- [ ] Implement the design for the Authenticated / Error widget state
- [ ] Implement header logic
- [ ] Link phone number
- [ ] Connect this widget state to the appropriate backend response
- [ ] Update unit tests

## Acceptance Criteria
- [ ] As a user seeking information regarding my representation, I want to understand when there is an error displaying my information, so that I can contact VA.gov Help Desk to report the issue.
