### ISSUE TITLE
See if DevEx can assist with test accounts for Widget QA

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77608]
## Background
We will required test accounts to QA each authenticated state of the Representative Status Widget:
1. Authenticated, no representation
2. Authenticated, individual representation
3. Authenticated, organization representation

Seems like the DevEx team may be able to help with these accounts.  Key players on DevEx are Charley Stran (Eng lead) and Jamie DeHaan (Delivery Manager).

## Tasks
- [x] Connect with the DevEx team leads to understand if/how they can help us
- [x] If possible, outline steps and timeline to receive test accounts from DevEx

## Acceptance Criteria
- [x] We need test accounts; reach out to DevEx to see if they can help with said test accounts.

**Comment by oddball-lindsay** [comment]
Started a conversation with DevEx: https://dsva.slack.com/archives/C05M78LBUQM/p1709755450557139

**Comment by oddball-lindsay** [comment]
DevEx seems to be able to help with our needs in the next few days -- quick turnaround.  While we'll be using the LH endpoint in our products, DevEx will generate test users directly from the Benefits Gateway Service that LH is calling

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekx1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42628b70b0dbf18881564467f4c5828fcdc548ef/image.png" alt="image.png" />

Source: Lighthouse Team Dash's [planning mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705440431964/42ea71b5405cda62ed44e95794facd94d8d266a0?sender=ubac5f0487f25bc4431288699)
