### ISSUE TITLE
Authenticated: Request active POA and address from the backend

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77605]
## Background
When a user is authenticated, we will need to send a request to the backend so that we can understand if the user has an active POA and if they do, what the representative's corresponding address is.  

This information will determine which Widget state to display:
1. No representative = Authenticated / No Representative widget state
2. Individual representation = Authenticated / Individual widget state
3. Organization representation = Authenticated / Organization widget state

The backend endpoint and response is being handled in https://github.com/department-of-veterans-affairs/va.gov-team/issues/77606

## Tasks
- [ ] Create a request to the backend to check for active POA
- [ ] Connect the possible backend responses to the appropriate widget states
- [ ] Confirm the contact information (name, address, phone, email) is displaying correctly

## Acceptance Criteria
- [ ] The frontend can call the backend, so that it can understand the user's POA status and display the appropriate widget state.

**Comment by oddball-lindsay** [comment]
Instead of one push to rig up all Widget states, we will be connecting each Widget state to the backend as we go.
