### ISSUE TITLE
Widget State: Unauthenticated

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77600]
## Background

The Unauthenticated state for the [Rep Status Widget](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2268-79606&mode=design&t=fP7jQlmtzbi0zHvZ-0).  

**A note on headers:**
1. The ideal default logic would be "one heading below it's parent", so the Widget can play nicely with heading structure no matter where it's placed
2. Allow for a custom heading level, to account for scenarios when the heading level may need to be manually set, depending on the surrounding context.  Examples:
   1. https://www.va.gov/health-care/get-medical-records/ - subsection under “Use VA Blue Button to manage your records online”
   2. https://www.va.gov/health-care/schedule-view-va-appointments/ - its in its own section, right under the H1 and subtitle

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHJ1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--581f4d8db18f510b843234e379f74346e0a46488/image.png" alt="image.png" />

<img width="315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c445a5c6c6c77e6d35f7adedaaf24a92923241e/image.png" alt="image.png" />

## Tasks
- [ ] Implement the design for the Unauthenticated widget state
- [ ] Implement header logic
- [ ] Connect this state to the unauthenticated experience
- [ ] Update unit tests

## Acceptance Criteria
- [ ] As an unauthenticated user, I want to see an easy way to sign in so that I can check if I have an accredited representative.
