### ISSUE TITLE
Widget State: Authenticated / Organization

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77603]
## Background

The Authenticated / Organization state for the [Rep Status Widget](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2268-79606&mode=design&t=fP7jQlmtzbi0zHvZ-0).  

**A note on headers:**
1. The ideal default logic would be "one heading below it's parent", so the Widget can play nicely with heading structure no matter where it's placed
2. Allow for a custom heading level, to account for scenarios when the heading level may need to be manually set, depending on the surrounding context.  Examples:
   1. https://www.va.gov/health-care/get-medical-records/ - subsection under “Use VA Blue Button to manage your records online”
   2. https://www.va.gov/health-care/schedule-view-va-appointments/ - its in its own section, right under the H1 and subtitle

<img width="1676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy91QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd431e7d34f657a516716a4257dc35f16c53f59a/image.png" alt="image.png" />

<img width="170" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1317e5075392d3df265d92782466877c47ff0647/image.png" alt="image.png" />

## Tasks
- [ ] Implement the design for the Authenticated / Organization widget state
- [ ] Implement header logic
- [ ] Link the address to Google Maps (like we do in Find a Rep search results)
- [ ] Link the phone number to the appropriate application
- [ ] Link to the forthcoming FAQ page, URL is `https://va.gov/va-accredited-representative-faqs`
- [ ] Connect this widget state to the appropriate backend response
- [ ] Update unit tests

## Acceptance Criteria
- [ ] As an authenticated user, I want to understand if I have Veteran Service Organization representation, so that I can easily contact them.
