### ISSUE TITLE
Widget State: Authenticated / Individual

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77602]
## Background

The Authenticated / Individual state for the [Rep Status Widget](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2268-79606&mode=design&t=fP7jQlmtzbi0zHvZ-0).  This state is for attorneys and claims agents (not VSO Representatives).

**A note on headers:**
1. The ideal default logic would be "one heading below it's parent", so the Widget can play nicely with heading structure no matter where it's placed
2. Allow for a custom heading level, to account for scenarios when the heading level may need to be manually set, depending on the surrounding context.  Examples:
   1. https://www.va.gov/health-care/get-medical-records/ - subsection under “Use VA Blue Button to manage your records online”
   2. https://www.va.gov/health-care/schedule-view-va-appointments/ - its in its own section, right under the H1 and subtitle

<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24de7a7abb780eb13c4ee33749a825ce09df8815/image.png" alt="image.png" />

<img width="170" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baf44801e5a47fe7046296b2a45da6ff92320fb5/image.png" alt="image.png" />

## Tasks
- [ ] Implement the design for the Authenticated / Individual widget state
- [ ] Implement header logic
- [ ] Link the address to Google Maps (like we do in Find a Rep search results)
- [ ] Link the email address to the appropriate application
- [ ] Link the phone number to the appropriate application
- [ ] Implement a download of contact information (name, organization, address, email, phone) as a `.vcf` for the download link 
- [ ] Link to the forthcoming FAQ page, URL is `https://va.gov/va-accredited-representative-faqs`
- [ ] Connect this widget state to the appropriate backend response
- [ ] Update unit tests

## Acceptance Criteria
- [ ] As an authenticated user, I want to understand if I have individual (attorney or claims agent) representation, so that I can easily contact them.

**Comment by oddball-lindsay** [comment]
The Attorneys and Agents data has the associated firm in the Address 1 field, and our address validator is not carrying that data over bc it's not a valid address.  

We may be able to utilize the Accreditation API to surface the firm, but cannot with the current handling of the Trexler File.

**Comment by oddball-lindsay** [comment]
Got merged to Staging, will test with our test users then close out

**Comment by cosu419** [comment]
camel case conversion is not working using 'X-key-inflection': 'camel', will try setting it explicitly
