### ISSUE TITLE
Update "Last updated [date]" language for claims list item claim cards

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#77621]
## Background Context

Currently we use the language "Last updated on [date]" in both the claim cards and the Status tab. This is meant to indicate when the Last Action was taken on the claim. (Last Action in this case = most recent thing shown in Recent Activity). 

But on the CST home page, we don't have access to the Last Action since we are not making that API call. So we need to figure out how that date should be framed, or if it should be there.

## Design

Current design

<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenF5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e00520da73f446711ca1d13e45b585796dbf310/Screenshot%202024-03-05%20at%209.52.46%E2%80%AFAM.png" alt="Screenshot 2024-03-05 at 9.52.46 AM.png" />

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenV5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b39ae0f676779e676ed7ec420e159734c7e4b41e/Screenshot%202024-03-05%20at%209.52.55%E2%80%AFAM.png" alt="Screenshot 2024-03-05 at 9.52.55 AM.png" />

## Engineering 
- Add here

## Tasks
Design:
- [x] Determine what the wording of "Last updated on [date]" should be on the claim card in CST home page
- [ ] Engineering is told what the language will be, ticket updated with language

Engineer:
- [ ] Engineers implement language

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Claim card `'Last updated on <DATE>'` now shows `'Moved to this step on <DATE>'`

**Comment by jacobworrell** [comment]
@skylerschain did we figure this out. I vaguely remember coming to a decision. Do we still need this ticket?

**Comment by skylerschain** [comment]
We still need to update the language on the claim card. I think the best visual experience here is to change "Last updated: [date]" to "Since [date]". 

@davidakennedy Do you see any a11y issues with this approach?

<img width="343" alt="ClaimCard" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/bbc4a9e3-a823-465c-b375-1303d3a4bc22">

**Comment by skylerschain** [comment]
We haven't tested this language yet. We can! The issue is that this page doesn't pull the "Last updated" that the details page pulls. It is only aware of the last step update, not the last update from our new Recent Activity section.

**Comment by skylerschain** [comment]
We're gonna go with "Last step change: [date]"

Rationale: It's different enough from the claim detail page "Last updated [date]" language but retains the information that's currently there (i.e. we're not removing anything).

**Comment by skylerschain** [comment]
Update: From [these options](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=1601-3879&mode=design&t=7TLaoJ2zP2kODlvg-4), we like "Last step change on [date]".

Looping in @laurwill to sign off on this or let us know if you have any strong feelings.

**Comment by laurwill** [comment]
Does this mean that the claim entered that step on that date?

**Comment by skylerschain** [comment]
@laurwill 

_Does this mean that the claim entered that step on that date?_
**Yes**

_Is this the only place we indicate when a claim moved from one step to another?_
**We also indicate it in Recent Activity**

**Comment by skylerschain** [comment]
Here's our latest proposal - I'd like to hand this over to engineers to update.  

Rationale for this: 
- We can't reference tracked item updates on this page, since we don't make that API call (for technical performance reasons). So "Last updated on [date]" won't work like it will on Status tab.
- We don't want to remove information that Veterans are accustomed to seeing on claim cards
- We are updating to "Moved to this step on [date]" - despite the imperfections :)

It's clear that the better solution would be to make the API call and show "Last updated on [date]" so I've created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new) to investigate if there's any chance of being able to overcome that technical hurdle.

<img width="454" alt="Screenshot 2024-04-23 at 10 35 53 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/75679db8-7c56-4ad3-bfad-1aec88e9b240">

**Comment by pmclaren19** [comment]
Updated the ticket description/ ac to include @skylerschain most recent comment. @jacobworrell

**Comment by pmclaren19** [comment]
verified in staging and looks good!
