### ISSUE TITLE
[DevOps] Triage internal dependents of CIE-owned resources in `vaec-cms`

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77651]
## User Story
Followup to #86930.

As a DevOps engineer, I need to process the dependent services and resources identified in #77641 and identify how each will or should be addressed in the migration process.

I'm expecting (though this is not confirmed) that most or all of these will be shifted (at least in terms of production switchover) simultaneously. If that is the case, then we have a longer transition period where we can test internal consistency. Regardless, though, we likely have some hardcoded account numbers, etc that will need to be migrated. That might involve additional work in terms of refactoring, etc, so that switchover is graceful and automatic and not a matter of crossing our fingers and merging an integration branch or something like that.

## Tasks

- [ ] [DevOps] Determine how each item output from #77641 will be addressed.
- [ ] [DevOps] Open a followup ticket for each item that requires some additional effort, i.e. that isn't expected to be handled automatically by some other process.

## Acceptance Criteria

- [ ] Followup ticket(s) opened for any item output from #77641 requiring additional deliverable effort.

**Comment by ndouglas** [comment]
I came into this project thinking that this would be editing of existing files, rather than rewriting the infrastructure completely. As a result, I don't believe this is actually essential.
