### ISSUE TITLE
[ENG] 10-10EZ - Bug: Investigate Invalid Date errors

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77658]
## Background
During monitoring of the application status after TERA launch on 3/5, we noticed some errors in the Datadog APM showing "Invalid Date" errors intermittently throughout successful submissions.

We need to investigate where this error is coming from and what is causing it.

#### Resources
- [Datadog APM traces](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Avets-api-sidekiq%20resource_name%3A%22HCA%3A%3ASubmissionJob%22%20&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=errors&traceQuery=&view=spans&start=1709574064873&end=1709660464873&paused=false)

## Tasks
- [ ] Check Datadog APM traces
- [ ] Investigate error and where the root cause may be
- [ ] Share with team/PM and talk thru solution

## Acceptance Criteria
- Root cause and possible solution have been determined to resolve the Invalid date error.

**Comment by hdjustice** [comment]
@Mitch-A6 - now that the root cause has been found, and ticket #77716 has been created, can you put a comment here on what was done/found and close this?

**Comment by Mitch-A6** [comment]
Lihan was able to identify this as being caused by submissions with TERA time frames that specified a year but no month. The server was unable to interpret that as a valid date, hence the error. 

Since the rollout of Lihan's fix in #77716, the issue has not recurred.
