### ISSUE TITLE
[DevOps] Discovery on network configurations in `vaec-cms` AWS account

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77662]
## User Story
As a DevOps engineer, I need to understand network configuration in `vaec-cms` so that I can work to protect against downtime, errors, etc in our products.

A lot of this should be covered or at least touched on in #77639, #77641, and #77645, and followup tickets from those tickets. I have a special interest in this area, however, as my understanding is that we currently have systems that lack feature parity across environments or cannot be tested in an automated fashion because of networking issues, and I would like to keep this in the front of my mind.

## Tasks
- [x] [DevOps] Learn about network configurations in `vaec-cms`, including:
  - [x] VPCs
  - [x] subnets
  - [x] security groups
  - [x] peering connections
  - [x] ???

## Acceptance Criteria
- [x] Details of all relevant network configurations are documented in this thread.
- [x] Followup ticket(s) opened to address specific details where needed and appropriate.

**Comment by ndouglas** [comment]
@olivereri completed the necessary parts of this work this sprint and made the necessary changes and created the appropriate infrastructure, which is declared and documented within the IaC of `checkin-devops`, `lorota`, and `chip`.
