### ISSUE TITLE
[UX] [Design] Create Userflow for Checking Eligibility in the Standalone Travel App

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#77666]
## User Story
As a Veteran, I want to file a travel claim and I expect that VA knows if I'm eligible or not, and provide a path to file a claim for both scenarios.

## Tasks
- [x] Review research (if applicable) to inform options
- [x] Create userflow (or userflow options)
     - [ ] For Travel app
     - [ ] For eCheck-in
- [ ] Review options with team
- [ ] Decide on a target option

### Who needs to review? Remove the ones that are not needed
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske assigned you both for now, whoever has time in the latter half of the sprint, take this ticket and remove the other. Or cowork is cool too. TY

**Comment by zach-park** [comment]
Hi @cgednalske , I'm ready to get started on this task and I will set up a zoom to start the co-work and discussion. :)

**Comment by cgednalske** [comment]
Awesome, sounds great! 🎉

**Comment by zach-park** [comment]
Ready for review, @benbrasso-agile6 @cgednalske

**Comment by benbrasso-agile6** [comment]
Zach is going to make a change, and then I'll validate in the morning. 

We have a question (that might not go answered immediately) that might make us tweak things, but I still think we can close this ticket in the morning. It will become more clear when we share out.

**Comment by benbrasso-agile6** [comment]
Validated

**Comment by benbrasso-agile6** [comment]
Will need to find time to discuss, @cgednalske is going to pose a question in Slack about this work
