### ISSUE TITLE
Veteran Support Template Update - Incorporating AVA verbiage

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#77670]
## Issue Description
_In order to lessen the amount of traffic being directed to Salesforce, our Veteran Support templates will be updated to include AVA messaging.  Informing users to use AVA to contact us if their VA.gov issue has not been resolved._

---
## Tasks
- [x] Review templates and determine which will have AVA guidance added._
- [x] Create AVA verbiage blurb._
- [ ] Get approval from Chante._
- [x] Update all necessary templates with appropriate verbiage._
- [ ] Provide updated templates to VEO for email builder._ 

## Acceptance Criteria
 - [ ] **Scenario: Update Veteran Support Templates with AVA Verbiage**
  - Given the Veteran Support templates are identified for updating
  - When AVA verbiage is added to the templates
  - Then all necessary templates are updated with appropriate verbiage
  - And the updated templates are provided to VEO for email builder
  - And approval from Chante is received
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Approved AVA verbiage, applied to relevant templates. Will confer with Chante as to final review before VEO submission. Will be complete before EOS.

**Comment by starlow00** [comment]
I have followed up with Chante. Will proceed based on her direction in the next sprint.
