### ISSUE TITLE
Veteran Support Template Update - Incorporating AVA verbiage

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#77671]
## Issue Description
_In order to lessen the amount of traffic being directed to Salesforce, our Veteran Support templates will be updated to include AVA messaging.  Informing users to use AVA to contact us if their VA.gov issue has not been resolved._

---
## Tasks
- [x] _Review templates and determine which will have AVA guidance added. _
- [ ] _Create AVA verbiage blurb. _
- [ ] _Get approval from Chante._
- [ ] _Update all necessary templates with appropriate verbiage._
- [ ] _Provide updated templates to VEO for email builder_ 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
AVA referral verbiage complete. I will review with Chante before submission to VEO/Sameer for Email Builder.
