### ISSUE TITLE
SC | Refactor VA & Private evidence components

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#77673]
## Value Statement

**_As a_** developer
**_I want to_** refactor the Supplemental Claim main evidence pages
**_So that_** tech debt is reduced and so that future developers have less duplicate code to maintain

## Background Context

While reviewing CodeClimate issues, the [VA evidence](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/components/EvidenceVaRecords.jsx) and [private evidence](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/components/EvidencePrivateRecords.jsx) have low maintainability scores (F). Due to:
- Increased cognitive complexity
- \> 250 lines of code
- Duplicate code shared between the two components
- Duplicate code shared with other apps (not fixable, unless we copy the common code into platform)

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Build evidence component with shared code in the shared/component folder 
- [ ] Update and add unit tests
- [ ] Ensure e2e tests still work
- [ ] Forms visual and function aspects have not changed

## Definition of Ready 

- View issues in Codeclimate
    - [ ] [VA evidence component](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/components/EvidenceVaRecords.jsx)
    - [ ] [Private evidence component](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/components/EvidencePrivateRecords.jsx)

## Definition of Done

- [ ] VA and private evidence share common code
- [ ] CodeClimate score has improved to at least B
- [ ] No visual change of pages
- [ ] No functional change of pages
- [ ] All unit tests passing
- [ ] All e2e tests passing
- [ ] Team sign off after validation
