### ISSUE TITLE
[BE] Handle Faraday::TimeoutError Exception TravelClaimSubmissionWorker

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#77678]
## Description
Currently, considerable amount of BTSSS requests timing out and `TravelClaimSubmissionWorker` sidekiq job dies handling while handling the exception to access `original_body` response.  [[Reference log](https://vagov.ddog-gov.com/dashboard/ftx-zzd-v9j?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1709575158596&to_ts=1709661558596&live=true)]

Modify the [rescue](https://github.com/department-of-veterans-affairs/vets-api/blob/f692860d00815e5eef97e8d2ea3069356a26c2b0/modules/check_in/app/services/travel_claim/client.rb#L66-L71) block in `travel_claims/client`,
- To rescue `Timeout::Error, Faraday::TimeoutError`
- Log error to sentry
- Create Faraday response with `500` http_status and relevant timeout error message

## Tasks
- [ ] [BE] **Modify `travel_claims/client` to rescue Timeout exception**
- [ ] [BE] **Modify `travel_claims/response` object to include timeout error**
- [ ] [BE] **rspecs**
- [ ] [BE]**Add vcr_cassettes for timeout exception**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
