### ISSUE TITLE
DR | Refactor contestable issue code

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#77679]
## Value Statement

**_As a_** developer
**_I want to_** refactor the Decision Review contestable issues pages
**_So that_** tech debt is reduced and so that future developers have less duplicate code to maintain

## Background Context

While reviewing CodeClimate issues, the [shared contestable issues component](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/shared/components/ContestableIssues.jsx) and [prototype contestable issues component](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/testing/components/ContestableIssuesWidget.jsx) have low maintainability scores (F). Due to:
- Increased cognitive complexity
- \> 250 lines of code
- Duplicate code shared between the two components

We should only need to update the prototype code to improve the score; but we could also reduce the code complexity and size of the file to make it more readable.

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Cleanup prototype contestable issues component and use shared contestable issues code in the shared/component folder
- [ ] Reduce complexity and reduce amount of shared code 
- [ ] Update and add unit tests
- [ ] Ensure e2e tests still work
- [ ] Forms visual and function aspects have not changed

## Definition of Ready 

- View issues in Codeclimate
    - [ ] [Shared contestable issues](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/shared/components/ContestableIssues.jsx)
    - [ ] [Prototype contestable issues](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/testing/components/ContestableIssuesWidget.jsx)

## Definition of Done

- [ ] Shared and prototype contestable issues component share common code
- [ ] CodeClimate score has improved to at least B
- [ ] No visual change of pages
- [ ] No functional change of pages
- [ ] All unit tests passing
- [ ] All e2e tests passing
- [ ] Team sign off after validation

**Comment by Mottie** [comment]
There is little I can do in the NOD prototype to reuse code from the shared folder. The prototype is rendering a unique H1 and includes hints for the checkboxes, so I think we're stuck with this duplicate code. Given that I've reached out to platform and they are discussing replacing Code Climate, I'm going to stop work on this, and move this ticket back into the product backlog.
