### ISSUE TITLE
Content updates on Spanish and Tagalog COVID-19 vaccines page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#77681]
## Issue Description
The CDC issued new vaccine guidance for older adults. We published the changes on the English page and now need to translate the content into Spanish and Tagalog. 

Randi sent a word doc with the changes for translation on 3/5. Once the translation comes back she'll post them in this ticket. 

## Tasks
- [ ] Add translated content to Spanish page
- [ ] Add translated content to Tagalog page
- [ ] Copyedit Spanish page
- [ ] Copyedit Tagalog page
- [ ] Publish Spanish page
- [ ] Publish Tagalog page

## Acceptance Criteria
- [ ] Spanish page is live with changes
- [ ] Tagalog page is live with changes

**Comment by RLHecht** [comment]
We got back the Spanish translation: 

[22861.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/14572526/22861.pdf)

I've updated the drupal page and it's ready for you @megzehn: http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by megzehn** [comment]
Thanks for adding the text, @RLHecht! I reviewed the changes on the Spanish page and published them.

**Comment by RLHecht** [comment]
@megzehn we got back the Tagalog translation and I updated the Drupal file. Could you review and publish? Thank you!

[22862_COVID-19 vaccines_Tagalog.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/14603723/22862_COVID-19.vaccines_Tagalog.pdf)

**Comment by RLHecht** [comment]
@megzehn i made the minor update to the Tagalog featured content. Can you review along with the other changes above and publish when you get the chance? Thank you! http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by megzehn** [comment]
Thank you @RLHecht!! I reviewed and published the Tagalog version.

And I made the minor tweak to the Spanish side (changing "a" to "your last") with help from @saratorres2.
