### ISSUE TITLE
[FE/BE] 10-10EZ - Improvements: Add validation for whitespace (no characters)

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77689]
## Background
Recent EZ and EZR submission failures have been due to Veterans entering spaces within the Insurance fields.  We have string validation but not whitespace.

We need to add the whitespace validation so that applications do not fail upon submission to ES.

## Tasks
- [x] Add validation for spaces only within the Insurance fields
- [x] Test with team/PM
- [x] Launch to production

## Acceptance Criteria
- Whitespace validation is implemented so that applications are not submitted to ES with the appearance of missing data.

**Comment by longmd** [comment]
@lihanli , I have merged the updated schema in the FE. Feel free to update the BE whenever you next get a chance.

**Comment by longmd** [comment]
@hdjustice , I have validated the schema update to not allow empty space as a value for the provider and policyholder names.

![Screenshot 2024-03-08 at 12 16 26](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/a41a555e-064c-4434-90da-2058160668fe)
