### ISSUE TITLE
NOD prototype | Refactor code

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#77688]
## Value Statement

**_As a_** developer
**_I want to_** refactor the Notice of Disagreement prototype testing config
**_So that_** tech debt is reduced and so that future developers have less duplicate code to maintain

## Background Context

While reviewing CodeClimate issues, the [NOD prototype code](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/code?q=src%2Fapplications%2Fappeals%2Ftesting&sort=maintainability) has low maintainability scores across a few pages (F and C).

We should refactor the code to use Decision Review shared code, _or_ set the "won't fix" setting because this code is not in production, with no plan to maintain it; and it may be deleted in the future.

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] Refactor and cleanup prototype code to use shared code in the shared/component folder
- [ ] Reduce complexity and reduce amount of shared code 
- [ ] No tests or e2e tests to update
- [ ] Forms visual and function aspects have not changed

## Definition of Ready 

- View [low score code in Codeclimate](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/code?q=src%2Fapplications%2Fappeals%2Ftesting&sort=maintainability)

## Definition of Done

- [ ] Prototype code has improved scores
- [ ] CodeClimate score has improved to at least B
- [ ] No visual change of pages
- [ ] No functional change of pages
- [ ] All unit tests passing
- [ ] All e2e tests passing

**Comment by Mottie** [comment]
I reached out to platform about improving these reports, and maybe excluding some code, e.g. the NOD prototype folders (for testing only), but given the problems, they are [considering finding a different code quality library](https://dsva.slack.com/archives/CBU0KDSB1/p1710856814716979?thread_ts=1710793502.145909&cid=CBU0KDSB1).
