### ISSUE TITLE
[UX] [Research] Generative research to better understand the need for standalone travel app for VistA Sites

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#77682]
## Tasks
- [x] Create semi-structured interview questions for Kristen and/or Kay. E.g., What's the problem we're solving? Knowing that Veterans use "check in" X amount, do we think they'd use "travel" X amount more? 
- [x] Meet with Kristen and/or Kay
- [x] Document discussion in Git 
- [ ] Create pros and cons and document in Git. E.g., will having a standalone travel app for VistA sites impact usage of eCheck-in, etc. 

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by cgednalske** [comment]
The [notes from our conversation with Kristen](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/travel-reimbursement/standalone-travel-web-app/discovery-interview-notes.md) have been added to GitHub - think we can close this out once validated!
@benbrasso-agile6 @loripusey @zach-park

**Comment by benbrasso-agile6** [comment]
LGTM, TY
