### ISSUE TITLE
[UX, FE] 10-10EZ - TERA: Update reapply button and content for specific ES statuses

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77694]
## Background
As TERA changes rolled out, we received feedback for certain statuses of Veterans that should and should not be allowed to reapply.  The list below indicates which kind of statuses should be allowed to reapply online:
- Rejected
- Not Applicable
- Closed Application
- Cancel/Declined

## Tasks
- [ ] Update Intro page logic to allow the statuses above to display the reapply button and content (TBD)
- [ ] Test with Team/PM
- [ ] Launch to production

## Acceptance Criteria
- Intro page logic is updated to allow specified statuses to reapply for health care

**Comment by jessicastump** [comment]
@hdjustice and @longmd Double confirming this status: Not Applicable 
[Danielle's notes in Slack](https://dsva.slack.com/archives/CMJ2V70UV/p1709667610051139?thread_ts=1709662008.571259&cid=CMJ2V70UV) call out this is for Non-Veterans, I was looking for this listed in our [Mural table](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683651181051/e0f47b9aaefbf78a3942df3028525cdc4336caff?wid=0-1701373991659&outline=open) during the call and could not find it...Do we have specific messaging for this one or does it map to a different status name?

**Comment by longmd** [comment]
@jessicastump , NA maps to active duty. We have a headline specific to them saying something to the effect of "We see you are still active duty" Then we just give them the button to Apply. There is no explanation. It wouldn't be a bad idea to have some sort of messaging maybe?

**Comment by jessicastump** [comment]
Got it, we do have content and designs listed for active duty, wanted to confirm that mapping. Thinking future state we could keep the FAQ content and add a Start Application button to the alert. [Figma page started for sorting out the FAQs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=2143-132513&mode=design&t=ZN3LLCT0lx9cKEHB-0)

**Comment by longmd** [comment]
I was hoping that just moving the start button to the alert and leaving those would be an option! I think that'll be MUCH cleaner, and it eliminates an accessibility issue with how this currently functions.
