### ISSUE TITLE
Get right Content URLs into Prod Dev Checklist

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#777]
- [ ] Move ROE docs into Onboarding folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Administrative/Onboarding

- [x] Update prod dev checklist w/correct content links:
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Launch%20Process/overview.md

- [x] Update old/obsolete pages in other repos by adding this text to the top "This document is now obsolete. Current version here: [link to current version]"

**Comment by peggygannon** [comment]
this is complete.
