### ISSUE TITLE
Burial | Frontend Migration

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77705]
## Issue Description
_Once v2 of the burial form is 100% released, authenticated users with in-progress v1 forms who start a new session will be directed to the start of the v2 form. They will see an alert on the form landing page indicating that the form has been updated, and their existing v1 form data will appear in the v2 version of the form. Authenticated users to maintain their active session after 100% release will stay in the v1 form._

User flow:
1. v2 form is fully released (100%)
2. Authenticated user:
   - Maintains active in-progress session: Stays in v1 of the form.
   - Creates new session: Starts over with v2 of the form with their migrated v1 data
3. Unauthenticated user:
   - Maintains active in-progress session: Stays in v1 of the form.
   - Creates new session: Starts over with v2 of the form with no migrated v1 data.

---
## Tasks
- [ ] Migrate/map v1 form data to the new v2 form
- [ ] Update redirect logic to still allow migration to v2

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
