### ISSUE TITLE
SPIKE | Confirm Profile Edit Behavior

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77703]
## Issue Description
_CAIA suggested that best practice is for profile changes (e.g. address) made within forms to write back to VA Profile. It's unclear whether any of our forms currently write back changes to VA Profile._

VA Profile info on the [Platform Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-profile) and in [Sharepoint](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB).

---
## Tasks
- [ ] Determine if forms write back to VA Profile when edits are made to profile information within the form.
   - [ ] 686/674
   - [ ] CH31/VRE/28-1900
   - [ ] CH36/PCPG/25-8832
   - [ ] COE/LGY/26-1800 

## Acceptance Criteria
- [ ] Document findings in this ticket
- [ ] Create follow on tickets to add read/write VA Profile behavior to forms missing it
---

**Comment by katherine-fung** [comment]
Just clarifying here - I don't know that application changes writing back to [VA.gov](http://va.gov/) profiles is a best practice! This is something y'all should confirm with the product side/profile team/form team/another team. I just need to confirm the behavior to provide accurate copy for the 28-1900 and the 686c.

**Comment by steele-lm** [comment]
No longer needed.
