### ISSUE TITLE
[CST][Discovery] Determine what is needed to make remediation possible for file uploads

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#77718]
### Background
Currently we rely on the retry capabilities of Sidekiq to automate the remediation of temporary issues that occur when users attempt to upload files via the Claim Status Tool. If a job were to fail due to a bug in our implementation or in Lighthouses for instance, we don't have any way to handle remediation because the metadata needed to manually re-upload the files is only stored in the Sidekiq dead queue, which has a temporary lifespan. We need to be able to store enough data to manually reupload failed uploads. We also should store enough data to be able to check the status of uploads that are accepted by Lighthouse to make sure they make it to the eFolder successfully

### Engineering notes
It seems that the most appropriate way to store these would be by adding a new table to the DB to store submissions. It also seems li

### Open Questions
- [ ] Do we need to worry about the size of table over time?
- [ ] How do we store the user credentials? LH will need the participant ID as a required field, but should we use another identifier instead

### Tasks
- [ ] Determine what fields need to be in the Database Table

### Acceptance Criteria
- [ ] We have determined what we need in order to remediate file upload failures in the future
- [ ] It is clear what ticket(s) need to be created to complete the work

### Acceptance Criteria
