### ISSUE TITLE
[BE] 10-10EZ - TERA: Update backend to accept the "year" independently for TERA dates

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77716]
## Background
As a result of a submission failure due to "Invalid Date", it was found that the Veteran was entering either a Month or a Year, but not both, causing a validation error.
We will update the backend to allow for either:
- Month and Year
- Year alone

## Tasks
- [ ] Update Backend to accept and send either a **Year** or **Month & Year** for TERA questions
- [ ] Test with Team/PM
- [ ] Launch to production

## Acceptance Criteria
- Veterans can enter a Year or Month/Year on TERA questions
