### ISSUE TITLE
Medical Copay Notification + Preferences

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#77726]
## MCP Email Communication + Preferences

**High Level User Story/ies**
As a Veteran, I want to receive an email when I have a new medical copay bill so that I can work to resolve this debt.

**Objective:**
- Establish email communication that is sent to Veteran when a new medical copay bill has been generated. 
- Establish the ability for the Veteran to set communication preferences to opt in/out of the email based on their preferences

**Problem Statement**
Currently, Veterans receive communication about a new medical copay bill through the mail. By establishing an email notification they will receive more timely information that they can act on quickly. 
In addition, notification preferences do not exist in the VA.gov profile for the debt related notifications.  Providing this functionality will enable Veterans to manage their preferences and therefore opt out of receiving these emails if they choose to do so. 

**What are the user goals?**
- receive email communication about a new medical copay bill
- to set their personal preferences regarding email communications for this type of notification

**Definition of done**
*What must be true in order for you to consider this epic complete?*

 - [ ] Email communications have been established in production 
 - [ ] Notification preferences are available in the VA.gov profile for the New Medical Copay notifications
 - [ ] Notify Steve Albers to remove filter from Benefits Sidekiq Death Queue which is currently filtering this
 feature from monitoring across the Watch Tower

**In Scope**
- Notification for new medical copay bill
- Collaboration with VA Notify team to establish notification

**Out of Scope**
- Notification for benefit overpayment debt

**Objectives and Key Results (OKRs)**
Add OCTO, Crew or Team OKRs as relevant

**What are the known risks?**
- Requires collaboration with VA Notify team to implement
- Given the volume of emails that are sent regarding new medical copay bills we need to ensure that plans are clearly communicated with VHA, HRC and other stakeholder groups who may be impacted by an increase in call volumes etc. 

**Contacts + Stakeholders**
*VA OCTO Product Owner:* Denise Coveyduc
*VA Business Stakeholder:* Robert Vitt - Debt Management Center (DMC)
*Implementation Team:* Debt Resolution/ Veteran Online Debt Access (VODA) 

**Reference links:**
- To be added as needed

**Monthly Initiative Updates:**
| Month | Update/Status notes  |
|------|--------|
| June 6, 2023| Email communication was established and launched into production |
|February 2024 |Due to an extreme influx in call volumes email communications were paused and are no longer being sent to Veterans.  |
| March 2024 | VAPO has established committee to align VHA stakeholders on strategy and approach for the V3 version of the medical copay notification that is sent to Veterans. Once the approach has been established we will update the production copy of this notification and monitor for continued feedback and iterations needed.  |
| May 2024 | Plan to reinstate email communications once payment history data is available and an updated balance showing recent payments can be presented in the debt portal experience. Ideally this will help to reduce Veteran confusion and prevent the bump in calls|

**Tasks (to be updated as needed)**
- [ ] VAPO to align stakeholders and solidify V3 copy
- [ ] Update V3 copy in production
- [ ] Reestablish notifications
- [ ] Establish Preferences for email
- [ ] Monitor feedback

**Comment by davidconlon** [comment]
This is dependent upon Lighthouse work being done. 
Expected that work to be completed FY2025Q1/Q2.
