### ISSUE TITLE
 Changes for VA direct deposit info for 526

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#77728]
On hold for Pension copy changes - @jstrothman / @shannonkford  

## Issue Description
By April 20, 2024, VA is effecting changes where a Veteran may only have one direct deposit bank account for receiving any applicable VA benefits payments. The updated messaging needs to be directed towards:
- Those who receive awards for an active claim -and- claims submitted before we add the message on the forms and
- Those who already receive a post-9/11 GI Bill edu payment

This ticket is to make copy changes for 526 to inform the Veterans of upcoming changes, relevant dates and call to action, if any.

---
## Tasks
- [ ] Get copy changes from Julie Strothman / Shannon Ford for the Pension Benefits
- [ ] Make updates, as necessary, for 526

## Acceptance Criteria
- [ ] The copy changes are updated on 526 pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @jstrothman @shannonkford @emilytheis

**Comment by RakshindaAslam** [comment]
Check if LH/BGS is making any changes to their endpoint and if 526 needs any testing. @sethdarragile6

**Comment by RakshindaAslam** [comment]
Closing this as it's a duplicate of #[77921](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/77921)
