### ISSUE TITLE
[Discovery] Logged-in homepage: Analytics review and report

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7772]
## Background

We asked the analytics team to pull a bunch of analytics for is in #6322. There's a full list in that ticket of what we were looking for and what we were hoping to learn.

We need to go through the data they sent along, document notable findings and insights, and share those out with the team.

## Tasks

- [x] Review analytics
- [x] [Document findings and insights](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md)
- [x] Share out with the team

## Acceptance criteria

- [x] Findings have been shared out to the team

**Comment by andaleliz** [comment]
Copying comment from Samara in Slack to GH for documentation/visibility. This is regarding a convo we had on 4/21 regarding expectations for this work:
> At a high level, we talked about the report covering some baseline stats, trying to address some of the product questions we outlined in the analytics ticket/overall research goals, and any other noteworthy insights we might find. This will probably be a group effort over time to make sense of the numbers, but the report itself will probably be quite simple and doesn't need to do any more than summarize what the numbers are telling us.

**Comment by Samara-Strauss** [comment]
@andaleliz @sshein I wanted to let you know I've started on the analytics report but it's not ready for feedback in any meaningful way. Still [here is the link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md) if you want to just see it so far. I'm gonna try to find a solid chunk of time next week to get this into shape, and I'll let you know when it's ready for feedback.

**Comment by Samara-Strauss** [comment]
@andaleliz @sshein the [analytics review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md) is finally ready for eyes! I am looking for feedback on:

- Overall format/structure/clarity.
- Whether the information included is helpful.
- Is anything missing?
- Any other feedback you have.

Thanks in advance!

**Comment by MickinSahni** [comment]
@andaleliz @sshein @Samara-Strauss @mshea0606 

Hey team, adding in a couple thoughts/questions:
- What infrastructure recommendations are we also making e.g. for flexible changes?
- What data do we have for conversions (in addition to page views) for e.g. the most popular tools?
- This hypothesis is based primarily on elevating currently high-traffic experiences. What recommendations do we make based on investments in areas _without_ much traffic/conversions or for benefits without as much Veteran usage?

**Comment by andaleliz** [comment]
@Samara-Strauss this is great! Nice job distilling **so many **analytics into something easy to digest. Feedback on your points below:

**Overall format/structure/clarity.**
Looks good and is clear to me overall.  There are a couple of sections missing a recommendation. I think that is intentional, as I'm not sure what recs would come out of that data but wanted to let you know just in case. Another comment on these further down...
- [People start on the homepage, the claim status tool, and the facility locator](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md#people-start-on-the-homepage-the-claim-status-tool-and-the-facility-locator)
- [As mentioned above, many people come to the homepage directly. They also come to the homepage through the sign in flow, and then through many of the site's most popular pages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/analytics/analytics-summary.md#as-mentioned-above-many-people-come-to-the-homepage-directly-they-also-come-to-the-homepage-through-the-sign-in-flow-and-then-through-many-of-the-sites-most-popular-pages).

**Whether the information included is helpful / Is anything missing?**
Overall, yes! I definitely think so, and I'm glad to have had the chance to read this before we get deeper into the user interviews.  

In the two sections I mentioned above above, it's not totally clear to me what we should do with that information for the purposes of this work. Does it mean we need to more prominently feature sign in CTAs on these pages, once we have an improved experience to offer? Thats interesting that people are going back to the homepage from claim status, Rx refills etc. Do you think that. suggests they aren't coming to complete only one task at a time, and are going to the homepage to start on Task 2?

I found myself wondering "xxMM out of how many total?" while looking at the numbers. 30MM visitors is more impactful if we know it's out of 34MM....or less so if it is out of 500MM.  It could be helpful to include some overall baseline numbers in the intro section where you list the reports.  Also might be helpful to clarify if you are talking about total pageviews or unique pageviews.

**Any other feedback you have.**
I did not know about using `<details>` as an accordion element - that is awesome.

>Top search terms on the modernized VA.gov only
The link to the report for search terms gives me a "no data for this view" message. Not sure if that is a permissions things or there is something funky with the URL.

**Comment by Samara-Strauss** [comment]
> People start on the homepage, the claim status tool, and the facility locator

I totally hear you on "why does this info matter?" There were a couple sections in this report that made me feel that way, too, namely landing page info.

IMO, the reason this particular metric matters is because we wanted to understand whether people start on the homepage or more often directly on tool pages. If people were more often starting in tools, it would have been helpful to understand when they go to the homepage and why. Since people are starting on the homepage, this helps gives us a frame of reference for user flows as we design. I've added some content in the report to clarify this, but let me know if you still think this stuff isn't important. If the report is stronger without it, I can take it out.

> As mentioned above, many people come to the homepage directly. They also come to the homepage through the sign in flow, and then through many of the site's most popular pages.

IMO, this is relevant because it shows that people re-orient themselves on the homepage throughout their session. But, I don't have a recommendation here, and if it feels like it's not that helpful, I can take this out. I've also clarified this in the report.

> I found myself wondering "xxMM out of how many total?" while looking at the numbers. 30MM visitors is more impactful if we know it's out of 34MM....or less so if it is out of 500MM.

I totally get what you're saying here — you want a frame of reference. But, besides for the metrics around how many users go to the homepage vs. My VA, there's not really an absolute cap for any of the metrics.

For example, the claim status pages received roughly 60 million views. The total amount of page views for all the top 25 pages is about 350 million views. But saying "oh, that's only about 13% of page views" isn't actually true because we don't have a number for total page views outside of the top 25. Furthermore, IMO, this metric isn't necessarily about a part to a whole — it's about comparing one part to another part. We get much more context when we see that 60 million views are happening for the claim status tool vs. only about 1.7 million for the disability hub. It shows us that people are coming her far more directly to manage their claims than they are to learn about the claims process.

Does this make sense? I guess the TL;DR is that since I reference page views a lot throughout the report, there aren't really reference metrics to give us meaningful percentage ratios.

> The link to the report for search terms gives me a "no data for this view" message. Not sure if that is a permissions things or there is something funky with the URL.

Great catch. According to Brian (our new analytics person), someone apparently needs to set up this  report before they can view it. I'm not sure why this is different than the other reports, so instead of linking to a report in the write-up, I've added a collapsible list of the top 25 search terms in that section of the document.

**Comment by sshein** [comment]
I love this. Really interesting across the board for me, and gives me a clearer idea of what veterans are doing on our site. "Login is the primary action taken from My VA." was an unexpected finding for me, but I guess makes sense! I guess more people are bookmarking MY VA than we thought.

**Comment by MickinSahni** [comment]
> > What infrastructure recommendations are we also making e.g. for flexible changes?
> 
> What do you mean by "flexible changes"?

By "flexible changes" I mean are we technically positioned to quickly iterate the tools/benefits we elevate? Since we're positioning this as a more useful (more trafficked) feature, more efficient changes to our homepage are warranted. Does that require infrastructure changes we need to parse with the Platform and/or CMS team? 

> > What data do we have for conversions (in addition to page views) for e.g. the most popular tools?
> 
> I don't know. We'd have to get the analytics team to pull more data for us. What do you recommend looking at? Tbh I wouldn't know where to start.

My thinking is conversion (and related funnel) data will help inform our design approach to those tools on our logged-in homepage. We can probably pose that question to the analytics folks—where are those most popular tools (by page views at least) failing right now? 

> > This hypothesis is based primarily on elevating currently high-traffic experiences. What recommendations do we make based on investments in areas without much traffic/conversions or for benefits without as much Veteran usage?
> 
> For benefits that have less usage, our job is to :
> 
> * Elevate them if we can detect people use them in some way.
> * Make sure they're findable for people who want to learn about them/take advantage of them.
> 
> None of the analytics I looked at suggested to me that we should hide any of the benefits in any way; instead, they just validated some assumptions that yes, the things we thought people were using most are indeed the things that are getting the most use. We'll still have to make sure people can learn about/find benefit information for less popular benefits because the veteran lifecycle of explore --> apply --> track --> manage repeats itself throughout their time with the VA. That cycle is never over.

Yep, makes sense; giving attention to benefits that are popular as well as to benefits that haven't gotten as much attention in the past. 

> Also, from a purely technical standpoint, we have fewer integrations related to less popular benefits. Example — I don't think we have a way to detect someone has applied for/been granted a certificate of eligibility for a VA home loan. Of course, I assume we'll get more of that over time, and that information should be treated just as any of the more popular information should be — if some one has an application in progress, we should show it on their dashboard. If an application has been accepted, we should notify them.

Yeah that's the cart before the horse rub. Do we _have_ technical information on those lesser used benefits we might want to elevate?

**Comment by Samara-Strauss** [comment]
> By "flexible changes" I mean are we technically positioned to quickly iterate the tools/benefits we elevate? Since we're positioning this as a more useful (more trafficked) feature, more efficient changes to our homepage are warranted. Does that require infrastructure changes we need to parse with the Platform and/or CMS team?

I still need some more clarity here. What I *think* you're saying is that if, for example, we put a claim status tool widget on the homepage and realize it's terrible and no one is interacting with it, are we in a position to make updates to the homepage in an iterative and quick fashion? The answer to that would be yes, assuming we have the team resources. *But* since you're asking about infrastructure, I feel like there is still something I am missing here. Happy to regroup in Slack or on a 5 minute call if that makes this easier to clarify.

> My thinking is conversion (and related funnel) data will help inform our design approach to those tools on our logged-in homepage. We can probably pose that question to the analytics folks—where are those most popular tools (by page views at least) failing right now?
> 
> Also, we'd look to conversion data (rather than view data alone) to understand how our iterations to the logged-in homepage are doing.

OK, I *think* I get this, but let me know if I am wrong — if the logged-in homepage can help people have a more meaningful interaction with a tool, then that would show that our logged-in homepage was moving/had moved in the right direction. An example of this might be if we had a claim status widget and more people uploaded required evidence as a result of this widget. Or, another example might be if more people went to view messages with their doctors via the logged-in homepage instead of going straight to MHV to do that (right now, most health care tools live on MHV, so most people go right to MHV to manage their health care). Am I getting that right?

Question: How would we measure success for information that might intentionally be "view only" and not have a paired interaction? One example I can think of is if we had a payment history widget — we might elevate the date/amount of your last payment so that you actually don't have to interact with the tool itself. In some ways, we'd almost want page views to go down. I'm not sure how to measure success of something like that so let me know if you have thoughts.

> Yeah that's the cart before the horse rub. Do we have technical information on those lesser used benefits, which we might want to elevate?

Yeah, I agree this is a known issue. We can't have data on tools if we don't have the tools in the first place. :) This is something I'm personally aware of, and our team will hopefully have only better information over time as we integrate more tools and are able to measure user behavior.

I do want to say that I'm not terribly worried about this right now insofar as we might secretly be missing something super popular. We know from the sheer numbers of veterans who receive health care/disability payments that those are the most popular benefits even without considering interactions with digital tools. Anecdotally speaking, they're also what comes up most in user research calls.

BUT that being said, veterans do mention other benefits in calls/session regularly! Younger veterans care a lot about the GI Bill from my own anecdotal observations. Many people want certificates of eligibility for home loans. For those who have a high disability rating, they want more information on vocational rehab. 

So, the TL;DR there is that yes, I'm aware our data can't give us a full picture if we don't have tools to measure in the first place. But don't worry, I haven't forgotten about our other benefits.

------

I think some of this discussion has moved more in the direction of how we want to set baseline data and set and measure OKRs and KPIs. I'm going to create a separate thread to start more formally having that discussion. This thread is specifically about the analytics overview I wrote and whether that's good to go or not. For better or worse, we had a lot of high-level data pulled and my intention was more to give myself and others a lay of the land as to what people are doing on VA.gov. I am totally game to write another, more targeted report that includes OKRs, KPIs, and baseline metrics for the logged-in homepage once we have those OKRs and KPIs set. That seems like a much longer/larger conversation than what I think we're going to do in this particular report. So, imperfect, or rather, more general as it may be, I think I want to call this particular report done unless anyone has any additional feedback to address.

**Comment by andaleliz** [comment]
@Samara-Strauss, I'm sorry I'm only just now replying to your last comment to me - all of your responses to my feedback make sense. No changes or updates from me :)

**Comment by MickinSahni** [comment]
Closing out this thread with my follow-up 😄 

> I think some of this discussion has moved more in the direction of how we want to set baseline data and set and measure OKRs and KPIs. I'm going to create a separate thread to start more formally having that discussion...

Sounds great. Looks like we have #9181 👍  

> I still need some more clarity here. What I think you're saying is that if, for example, we put a claim status tool widget on the homepage and realize it's terrible and no one is interacting with it, are we in a position to make updates to the homepage in an iterative and quick fashion? The answer to that would be yes, assuming we have the team resources. But since you're asking about infrastructure, I feel like there is still something I am missing here. Happy to regroup in Slack or on a 5 minute call if that makes this easier to clarify.


Exactly. Although traffic to the logged-in homepage is _relatively_ lower than other auth pages (if i'm remembering the analytics correctly) we're still likely to see statistically significant data quickly that we should react to (even if that reaction is to invalidate hypotheses). 

Preventing a team resource constraint should be in our scope. We don't want that to be tied down that way. We'll leave that constraining to the inevitable Business jostling that'll happen because of how successful we're going to be! 🎉 

>OK, I think I get this, but let me know if I am wrong — if the logged-in homepage can help people have a more meaningful interaction with a tool, then that would show that our logged-in homepage was moving/had moved in the right direction. An example of this might be if we had a claim status widget and more people uploaded required evidence as a result of this widget. Or, another example might be if more people went to view messages with their doctors via the logged-in homepage instead of going straight to MHV to do that (right now, most health care tools live on MHV, so most people go right to MHV to manage their health care). Am I getting that right?

✔️ 

>Question: How would we measure success for information that might intentionally be "view only" and not have a paired interaction? One example I can think of is if we had a payment history widget — we might elevate the date/amount of your last payment so that you actually don't have to interact with the tool itself. In some ways, we'd almost want page views to go down. I'm not sure how to measure success of something like that so let me know if you have thoughts.

Yeah I think this is a theme across VA.gov—it's not immediately clear what incremental impact changes to view items like payment history or content changes make. 

My stance is we should run through some sort of 5 why's exercise each time because there's _something_ we're trying to enable with view actions even if it's 2 or 3 degrees removed. Otherwise, why do it? That applies to things like flattening IA or improving language. 

>...BUT that being said, veterans do mention other benefits in calls/session regularly! Younger veterans care a lot about the GI Bill from my own anecdotal observations. Many people want certificates of eligibility for home loans. For those who have a high disability rating, they want more information on vocational rehab.

This is awesome and we need to bolster those anecdotes with quantitative data!
