### ISSUE TITLE
Create GA4 FAQ Document on Platform Website

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#77736]
### Description
We received a number of questions from a VFS Team about the GA4 migration in Office Hours on Tuesday (3/5). Namely, about custom events, reporting, tracking, etc.

We anticipate we might receive similar questions from other teams, and so want to publish a document on the PW with some common FAQs. This would likely be a living, breathing document, and one that will continue to evolve, but we want to work towards a feasible V1.

**Note**: We shouldn't invest excessive time in coming up with questions that haven't been asked.

**Artifact:** https://vfs.atlassian.net/wiki/spaces/PWD/pages/3006136321/WIP+-+GA4+Migration+FAQs 

---

### Tasks
- [x] Generate list of questions for FAQ document that we have heard from teams.
- [x] Generate answers to those questions
- [x] Review document
- [x] Publish to Platform Website
- [x] Share with VFS Teams on ToT, and vfs-all-teams Channel

### Acceptance Criteria
- [x] Full questions have bee documented that we have already been asked, with and answers have been generated.
- [x] Document has been published to the Platform Website
- [x] Teams have been notified/alerted of page through various channels, (ToT, & _vfs-all-teams_)

**Comment by johnny-jesensky-adhoc** [comment]
Page has been published and pinned to the vfs-analytics and platform-analytics Slack channels, and details added to Team of Team slide.

Marking this as _Done_.
