### ISSUE TITLE
[ENG] 10-10EZ - Facility selection: Discovery for onboarding to Lighthouse Facilities API

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77749]
## Benefit to the Veteran
By performing discovery on the steps and effort it will take to onboard/utilize the Lighthouse (LH) Facilities API, we will be able to determine how quickly we can implement and start using a more up-to-date Facilities list, rather than the static JSON file we use today.

## Background
The 10-10EZ refers to a static JSON file for the Facility selection page.  This list is outdated and inaccurate.  We need to switch to using the latest Facilities API, so that we can display the most accurate and up-to-date list of facilities for Veterans to choose from.
This will require us to onboard to Lighthouse Facilities API.  There is a process to follow for this, and we need to determine that process and the effort it will require.

#### Resources
- [Platform website - Dev Docs](https://developer.va.gov/explore/api/va-facilities)
- [Platform website - API Consumer onboarding ](https://developer.va.gov/onboarding)
- [Code.va.gov](code.va.gov) (must be on VA network to view this site)

## Tasks
- [x] Review resources
- [x] Reach out to Lighthouse team/Joseph Justice (channel #cms-lighthouse) to request information about onboarding to a Lighthouse API
- [x] Outline the process in the comments below
- [x] Determine and list the information needed for us to gather for the onboard request
- [x] Discuss with Team/PM on findings and next steps
- [x] Create ticket(s) for next steps

## Acceptance Criteria
- Onboarding steps and effort to Lighthouse Facilities API is outlined and we are ready to begin the process

**Comment by Mitch-A6** [comment]
- [ ] make updates for API v0 -> v1 (seems to be done already, but recheck for snake_case -> camelCase renames or any null/empty results we might rely on, which v1 drops) 
- [ ] test in Sandbox (my Sandbox API key request was instantly completed)
- [ ] ensure we're familiar with the data (we should be good aside from newer team members)
- [ ] [request access](https://developer.va.gov/onboarding/request-prod-access) to production Lighthouse API (should be quick since we had prod access before)
- [ ] expect contact from someone from team Marmoset to coordinate further onboarding information + API access / questions
- [ ] might not need a demo since facilities is open data
- [ ] Joseph Justice and Adam Stilton (Tech Lead) are good contacts, as is the Lighthouse channel in general (https://lighthouseva.slack.com/archives/CJ162GDDJ)

**Comment by hdjustice** [comment]
@Mitch-A6 - If you think this ticket is done, I am ok if you want to close it since we have created tix for the nxt steps.  I know we are still pending that answer from API@va.gov
