### ISSUE TITLE
Preparation for Inventory/Audit of Actively Used Reports from VFS Teams

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#77750]
### Description
We need a way to confirm which GA reports VFS Teams are actively using. While are able to uncover some of what they use in Domo, they will be able to provide the best input into their existing GA reports.

 GA tends to attach to the user. Dashboards have to be made public for other to see and Custom Reports are user specific only.

We got a number of questions on this from some teams after distributing the form, so it likely makes sense to get this sooner rather than later.

**Note & Expectations On This:** Our team won't be that we are recreating all of their GA reports for them, but will help teams know what reports will be impacted by the migration, and can work through office hours, training, etc. to recreate as much functionality as possible within GA4 interface.

Our team will _assist_ with the reporting transition, not lift and shift for them.

---

### Tasks
- Define what we mean by 'actively used' for VFS Teams, (whether that be daily, weekly, or monthly)
- [x] Identify best place for teams to audit their reports, (existing template, new template, etc.)
We are going to suggest teams use the existing template, but unhide the _Reports_ tab.
- [x] If needed, make changes to VFS Custom Event Audit Template, by adding a tab within the Excel file, and the Google Sheet
- [x] Determine if we are creating a new document, or editing the existing one.
- [ ] ~Distribute out form letting teams know that they can also inventory their reports.~
- [x] Determine what a suitable timebox is for this. -- Planning to give teams 3 weeks to submit this information.

### Artifact:
- https://vfs.atlassian.net/wiki/spaces/AT/pages/3028320257/WIP+-+GA4+Migration+Planning+-+Reporting+Updates+Guidance

### Acceptance Criteria

- [x] Method has been properly identified for requesting this information from teams.
- [ ] ~Form has been shared/distributed with VFS Teams.~ FORM WILL BE DISTRIBUTED TO VFS TEAMS AT A LATER DATE -- AFTER THE CUSTOM EVENTS DEADLINE.
- [ ] VFS Teams have been alerted of the change to the form through multiple channels, (ToT, vfs-all-teams, etc.)
- [x] Communicate timebox for this.

**Comment by johnny-jesensky-adhoc** [comment]
Drafting some guidance around this in this Confluence page - https://vfs.atlassian.net/wiki/spaces/AT/pages/3028320257/WIP+-+GA4+Migration+Planning+-+Reporting+Updates+Guidance.

**Comment by johnny-jesensky-adhoc** [comment]
Communication for this ask has been saved [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3028320257/WIP+-+GA4+Migration+Planning+-+Reporting+Updates+Guidance). For now, we will plan to communicate the ask _after_ the custom event audit, on **Tuesday, April 9,** and give teams up to 3 weeks to complete this information, by _**Friday, April 26.**_

The ticket initially involved distributing this out, but given we are still collecting responses on the custom events, we don't want to confuse the ask. Moving this to _**Done**_.
