### ISSUE TITLE
Create List of Pages Containing Links to Google Drive Docs

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#77758]
## Issue Description
We need to determine how many pages on Platform Website contain links to Google Drive, Docs, Sheets, and Slides. This work will inform how we approach removing those links.

---
## Tasks
- [ ] Research Platform Website for pages containing links to Google Drive docs, sheets, and slides.
- [ ] Create Google Sheet (internal) with URLs to all relevant pages 

## Acceptance Criteria
- [ ] Content Team will have created the Google Sheet
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
