### ISSUE TITLE
Research: Create List of Pages Containing Links to Google Drive Docs 

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#77759]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Links on Platform Website need to be viewable by all users. 
Therefore, we cannot include links to Google Drive on the Platform Website.
We need to determine how many pages on Platform Website contain links to Google Drive, Docs, Sheets, and Slides. This first step will inform how we approach removing those links.

---
## Tasks
 - Identify all pages on Platform Website containing links to Google Drive docs, sheets, and slides in 6 spaces:
- [x] **Getting Started**
- [x] **Developer Docs**
- [x] **Research & Design**
- [x] **Analytics & Insights**
- [x] **Collaboration Cycle**
- [x] **Support**
- [x] Fill-in [Google Sheet](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0) (internal) with URLs to all relevant pages on Platform Website

## Acceptance Criteria
- [x] All relevant pages for the above 6 spaces are listed on the [Google Sheet](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)

## Google Analytics Report identifying links to Google Drive [HERE](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w224573768p240292331/_u.date00=20230401&_u.date01=20240303&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension2&explorer-table.rowCount=2500&explorer-table.advFilter=%5B%5B0,%22analytics.customDimension2%22,%22PT%22,%22google%22,0%5D%5D&explorer-table-dataTable.sortColumnName=analytics.eventAction&explorer-table-dataTable.sortDescending=true/)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Pages have been identified, moving on to next step of discovering how to [handle non-Google drive links](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78528)

**Comment by jknipes** [comment]
As this was originally 2 tickets with a combined estimate of 8 points, and the decision was to assign the work to one team mate, we decided to combine the estimate into a single ticket of 8pts.
