### ISSUE TITLE
[FE][BUG] Check content in additional info accordions

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#77760]
## Wireframes 

- [Travel Mileage page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=1300-6142&mode=design&t=LEpOtuBYBiaPtItc-4)
- [Travel Vehicle page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-6853&mode=design&t=LEpOtuBYBiaPtItc-4)
- [Travel Address page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-8049&mode=design&t=LEpOtuBYBiaPtItc-4)

## Tasks
- [ ] [FE] Ensure content in additional info components is up to date based on wireframes. (If needed, these changes can also be added into eCheck-in app's additional info components.)
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
@loripusey

**Comment by brianseek** [comment]
these are current, closing
