### ISSUE TITLE
DR | Only prompt for password for PDFs that have User passwords (and ignore Owner password)

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#77776]
## Value Statement
**_As a_** Veteran
**_I want to_** receive an appropriate error message if I am unable to upload evidence
**_So that_** I can take the appropriate action

---
## Background Context
Follow-up to #69617 

Owner passwords on PDFs result in a read-only PDF that cannot be edited/modified. When a Veteran uploads a PDF, the frontend checks if the PDF has any password and requests it — regardless of if it's a USER password or OWNER password — before uploading the file to the backend. 

It is possible that the veteran has a PDF that is encrypted with an OWNER password but they don't actually know what that password is, so they attempt to guess what it would be and get an error when it's incorrect. I was able to replicate this scenario during E2E testing when I noticed I was prompted for a password for a read-only test upload and was only able to proceed if I entered the correct owner password.

According to [Lighthouse documentation of the "validations performed" on documents](https://developer.va.gov/explore/api/benefits-intake/docs?version=current), we only need to make sure the file doesn't have a user password (i.e. we can ignore owner passwords): 

> Document does not have a user password (an owner password is acceptable)

## Tasks
- [ ] Update code (frontend and/or backend) to only prompt for user password (not owner) on PDF uploads
- [ ] Add appropriate error logging for Datadog

## Acceptance Criteria
- [ ] When a user uploads a read-only encrypted PDF file, they do not see a prompt for a password
- [ ] When a user uploads a fully encrypted PDF file with a USER password, they do see a prompt for a password and see an error when that password is incorrect

---
## Definition of Ready 
- [ ] Determine technical approach (backend or frontend handles the logic for whether a PDF has a user or owner password — likely will be resolved by #77475)
- [ ] Determine how we want to confirm that the presence of an owner password does not affect documents downstream
- [x] [Test files](https://drive.google.com/drive/folders/1xdorqTvkMi1y9v80wUQzrM5QkxO1TswV) are available from E2E testing ("encrypted" = owner pw, "locked" = user pw)

## Definition of Done
- [ ] Successfully tested in staging
- [ ] Reach out to Veterans having this issue via Help desk

**Comment by Mottie** [comment]
Duplicate of #77084

**Comment by anniebtran** [comment]
This was completed as a part of the work to pull in Lighthouse's validate_document endpoint into our upload flow. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/77084

**Comment by anniebtran** [comment]
Closing since this is done already! 🎉
