### ISSUE TITLE
[Spike] [Board Appeals in CST] Investigate what shows up for closed Board Appeals in production

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#77788]
## Background Context

As part of [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74224) we looked at the UI in staging for a Board Appeal that was closed. 

This is what we found in staging:

<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHk3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1afab302c8d0343604409c3dbac76b7e3af0c0f1/image.png" alt="image.png" />

CaseFlow created this appeal for us, and so it's difficult to assess whether this is a one-off thing or the expected UI for all closed Board Appeals.

If it's the expected UI for closed Board Appeals, we should change it because it's confusing to tell the Veteran that the Board has made a decision on the appeal, while also saying `How long until a judge is ready for your appeal?` which implies that a decision has _not_ in fact been made.

It's also unclear if the content about remands in the `What happens next?` section is accurate.

## Design
TBD

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Work with CaseFlow to identify the various closed states of a Board Appeal
- [ ] Document what those closed states actually look like in production
- [ ] Make any language and/or other design changes necessary to improve the design and eliminating confusion
- [ ] Review our changes with someone from the Board of Appeals to make sure they are accurate
- [ ] (Longer term) Work with CaseFlow to identify and document all states of all appeals in Claim Status Tool

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The closed state of a Board Appeal claim has been accurately identified and documented
- [ ] The closed state of a Board Appeal claim has UI and language that makes sense given the state the appeal is in
- [ ] Plans have been created to work more closely with CaseFlow to identify UI states for appeals in CST, and ideally some way for the Benefits Management Tools team to create these states ourselves

**Comment by skylerschain** [comment]
Closed statuses with associated UIs can be seen [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714748626644/91d587cd82f27729eba6bcf07b92bb9b27aab5f4?wid=0-1715008038560).

Next steps: @skylerschain and @jerekshoe need to pair to figure out UI states for the "Take action" section of the page.
