### ISSUE TITLE
Usability testing with lo-fi prototypes

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#77799]
## Task Description
Coordinate and facilitate user testing for lo-fi concepts of a new scheduling flow for appointments for veterans.

## Notes and References
- Objective: Gather feedback on usability and user experience for the scheduling flow.
- Testing materials: Lo-fi concepts of the scheduling flow.
- Recruiting with Perigean

## Acceptance Criteria
- [ ] User testing sessions successfully coordinated and conducted.
- [ ] Recruitment of targeted veteran participants 
- [ ] Test scenarios executed with participants, and feedback obtained.
- [ ] Comprehensive notes taken during testing sessions.
- [ ] Insights derived from testing data synthesized into actionable recommendations.

## Deliverables
- Report or presentation summarizing the findings and recommendations from user testing.

---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by melissa-lefevre** [comment]
Closing this because[ this ticket](https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/84489) covers these tasks
