### ISSUE TITLE
NOD | Clean up obsolete rake tasks post v2 launch and remediations

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#77808]
## Value Statement
**_As a_** Developer
**_I want to_** keep the codebase clean and maintained
**_So that_** other/future developers don't get confused about code that is no longer necessary

---
## Background Context
- During the first attempt to release NOD v2, we realized there was some code missing to handle sending evidence uploads to Lighthouse which resulted in some remediation work (see [this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70237)) including writing a script to manually get those files sent over (see [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/14568)). This is a clean-up task to remove that script once we have finished releasing NOD v2.

- We also were asked to write a script to pull veteran contact info for sending out communications for the NOD infinite loop bug, but Cory ended up being able to pull the information for them, and we ended up not needing the script after all (it needed some fixes as well, so it currently doesn't function as expected). See links to the [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72921) and [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15043) for more context. So this script can also be removed.

## Tasks
- [ ] Remove [script](https://github.com/department-of-veterans-affairs/vets-api/blob/master/rakelib/fix_nod_evidence_submissions.rake) for manually pushing NOD v2 evidence to Lighthouse and its corresponding [test](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/rakelib/fix_nod_evidence_submissions_spec.rb)
- [ ] Remove [script](https://github.com/department-of-veterans-affairs/vets-api/blob/master/rakelib/contact_info_via_veteran_icn.rake) for pulling veteran contact info and its corresponding [test](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/rakelib/contact_info_via_veteran_icn_spec.rb)

## Acceptance Criteria
- [ ] No longer able to run those rake tasks from a console

---
## Definition of Ready 
N/A. Ready for pickup.

## Definition of Done
- [ ] Acceptance criteria is complete

**Comment by anniebtran** [comment]
Validated that the old rake tasks don't show up in the rake task list on staging and prod (`bundle exec rake --tasks`)
