### ISSUE TITLE
[UX, FE] 10-10EZ - TERA: Add UI validation to Month/Year date field

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77804]
## Background
As a result of a submission failure due to "Invalid Date", it was found that the Veteran was entering either a Month or a Year, but not both, causing a validation error.
In ticket #77716, we will update the backend to allow for either:
- Month and Year
- Year alone
We will update the Frontend to validate if a Month is entered, the user is expected to enter a Year as well.

#### Resources
- [Figma file](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=1289-43319&mode=design&t=v3uxl1U7N4cjSjZy-4)

## Tasks
- [x] Update Design to include UI error message 
- [x] Update Frontend to have on-screen validation error if user enters only a month
- [x] Test with Team/PM
- [x] Launch to production

## Acceptance Criteria
- Veterans can enter a Year or Month/Year on TERA questions

**Comment by jessicastump** [comment]
Content to use:

**Comment by longmd** [comment]
Screenshots of the updated validation:

**With error for month only:**

![Screenshot 2024-03-07 at 11 50 59](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/a7a64c51-fcce-4292-b409-3c500123a38a)

**No error for year only:**

![Screenshot 2024-03-07 at 11 56 48](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/59801b53-1286-4680-ba5f-57da028b4f82)

**Comment by longmd** [comment]
@hdjustice / @jessicastump , this is in staging. The above screenshots show the correct usage validation.

**Comment by jessicastump** [comment]
<img width="576" alt="Screenshot 2024-03-07 at 11 13 24 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/f3ba8796-d416-4400-9b71-4428cc85ccdd">

Would we want the new alert text to show in this use case - when a month is entered in the "end" field?

**Comment by jessicastump** [comment]
I think ideally what is showing would only show if the year entered for end date was before the start date. Just thinking through if there are any use cases where it would make sense to do the date range check first... if they see the month/year error first , then correct by inputing a year if that is before the end date, then would still see the service after date error next, correct?

**Comment by longmd** [comment]
@jessicastump , you are correct. If you like that better.. I'll just flip the order and we'll be good to go.

**Comment by longmd** [comment]
@jessicastump , the order has been corrected on this to show the month/year before showing the range.

![Screenshot 2024-03-08 at 11 52 38](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/a56994ef-e853-42d1-8d32-662acccb5137)

**Comment by jessicastump** [comment]
Looks good, thanks @longmd!
