### ISSUE TITLE
Build Initial Product Documentation for Loan Guaranty Application

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7781]
## Goal
As they relate to existing application features, we want to capture as much information about the known metrics, users, workflows, requirements and stakeholders and document them.

## Considerations
- Apply for VA Home Loan Certificate of Eligibility: Calculate my VA Home Loan benefit and apply for a Certificate of Eligibility. (This is an iFramed LGY-hosted application.)
- Apply for Specially Adapted Housing Grant: (Form 26-4555) Apply for Specially Adapted Housing benefits. (This is an iFramed LGY-hosted application.)  

## Tasks
- [x] Schedule and conduct a team, or at least with a few members of Design/Research, walk-through of the current feature and paper form(s)
- [x] Understand the functions and how they map to the user stories and experience seen in the [Epic](#)
  - Discuss research strategy for exploring pain points in its current use and where to focus analysis for potential improvements
- [x] Document in GH as an .MD file these findings for future reference

## Acceptance Criteria
- [x] An .MD file has been created in the [feature repo root](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/README.md) and includes the items above.

**Comment by jason-gcio** [comment]
Outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/README.md
Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19595
