### ISSUE TITLE
Document Plan for Updating Reports in Domo to GA4

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#77820]
### Description
We need to document out our current plan for testing/QA'ing our reports in Domo that use GA data that will need to be updated to incorporate GA4 data into them. Phil has a solid understanding of how this will be done, but in order to capture this knowledge, and make sure there is an understanding across the team, we should look to document these steps in Confluence.

**Location in Confluence:** https://vfs.atlassian.net/wiki/spaces/AT/pages/1928495134/GA4+Migration

---

### Tasks
The steps in this will likely involve documenting the plan for updating the reports, including the following:
- [ ] Outline how we will adjust/merge/union the UA and GA4 data sets
- [ ] Highlighting specifics on query changes
- [ ] Outline how we might go about testing the reports
- [ ] Outlining the specific plan for pushing the reports to 'Go-Live' with GA4 data

### Acceptance Criteria

- [ ] Page in Confluence has been created with an outline of everything include in the Tasks section of this ticket
- [ ] Confluence page has been updated and edits are published.

**Comment by johnny-jesensky-adhoc** [comment]
Johnny to connect with Phil on reworking some of the AC and Tasks associated with this.

**Comment by johnny-jesensky-adhoc** [comment]
We met to determine a QC process on, which has been built out in the form of tasks and AC in our QC tickets. We will look to document our QC process, and any changes to Confluence, specifically [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).

Closing this out, as is no longer needed as its own task.

FYI @ChristineYoungZA , @Blivaditis, @dorseypa1
