### ISSUE TITLE
Changes to PPMS query

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7782]
## Issue description
Due to changes to the Facility Locator functionality and to the PPMS query structure, we want to optimize our Community Care queries. This is also an opportunity to improve performance. 

- The FL no longer links to detail pages, making much of the requested data unnecessary. 
- The number of fields required by PPMS has changed. 

## Tasks
- Update query to send only data for required fields plus those which are desired for our needs

## Acceptance Criteria
- [ ] Updated query request 
- [ ] Determine list of items which are needed in the response (this will be evaluated in separate analysis issue)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
This issue is blocked pending PPMS release by Microsoft which was thought to have happened last month but which was shipped to Dev only, not to Prod

**Comment by mpelzsherman** [comment]
Is this still blocked?

**Comment by mmiddaugh** [comment]
![image](https://user-images.githubusercontent.com/55411834/94594978-67a91580-0247-11eb-964e-d7cdda0ff70d.png)
