### ISSUE TITLE
Figure out the existing Direct Deposit notifications

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#77834]
## Description of UX Tasks
VA Notify is a tool already in place for sending notifications to veterans. The Auth Exp team is managing notifications for Direct Deposit changes on an account. Our team is considering if it makes sense to take over managing those existing notifications as we add fraud related notifications - with the goal of having all fraud related notifications managed by the same team

## Tasks
- [x] reach out to Tom Harrison to see if we should take back over managing the VA Notify messaging for DD changes
   - the Auth Experience team manages this notification in vets-api. 
   - this team is open to a conversation around Identity teams taking over the responsibility  
- [x] sync internally about our feelings and align on what we want to with the DD notifications
   - As a team we seem to mostly be in favor of taking over these notifications
- [x] sync with Tom B about his feelings for us taking over these notifications
- [ ] sync with Tom H and Auth Exp team about the DD notifications
   - What are their feelings on handing this off to us?
   - What other discussions need to happen or what other assurances need to be made from either side?
   - What is the timeframe for a hand off?
   - What else do we need to know about this?
- [ ] Should we actually take this over or pass on to BDPR? (considering they have two other types of potential fraud related notifications they manage
- [ ] If taking over the notifications management for Dir Dep, we'll needs a set of tasks for implementation and who or what position on our team owns this (probably another ticket)

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Add finalized research to Github
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by claytonzook** [comment]
This is on hold for now

**Comment by parkerbees** [comment]
moved to jira, closing
