### ISSUE TITLE
[CST] Create a solution for when "Received on" date is in the future (e.g. BDD)

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#77832]
## Background Context

If you fill out submit a BDD a claim gets created in CST with a "Received on" date (`claimDate`) that is set to the EAOS date (end of service date for the Veteran). 

See thread for details: https://dsva.slack.com/archives/C056854SVT8/p1709770438207779

There are a few possible solutions to this. The most promising seems to be to check if the `claimDate` is in the future, and if it is, don't show the "Received on" date or show "Pending" (TBD exact design solution). 

## Design
- Add here

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] If a Veteran has a claim in CST that has a `claimDate` in the future, show something other than "Received on ___" on the claim card
- [ ] If a Veteran has a claim in CST that has a `claimDate` in the future, show something other than "Received on ___" in the claim details pages
- [ ] _AC_
