### ISSUE TITLE
Hardening of VAMC top task pages 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7783]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)

## High Level User Stories
- As a Veteran, I need my VAMC to have accurate and easy to navigate content so I can use the website to satisfy all my online goals.
- As a content producer, I want to be able to create content at the system or facility level so that I can provide localized information to Veterans.
- As a content producer, I want the editorial experience to be user friendly so that I can serve Veterans efficiently.
- As the VHA, I want national content to be maintained at the national level so that Veterans have a standardized experience.

## Hypothesis or Bet
**If**  we create a flexible, reusable content model with governance mechanisms  **then**...
- ...the editorial experience will be more efficient
- ...there will be fewer requests to CMS for support
- ...veterans will have a consistent end user experience
- ...the VAMC rollout process will scale

## Definition of done

National content areas for VAMC top task pages have been "hardened" and cannot be  customized at system or facility level. 
- [ ] Register for care [#7785]
- [ ] Make an appointment [#7799]
- [ ] Medical Records [#7798]
- [ ] Pharmacy [#7804]
- [ ] Billing/insurance [#7801]
- [ ] Policies [#7784]
- [ ] DAV [#7797]

### What must be true in order for you to consider this epic complete? 
- Governance
- Expansion of the existing content model 
- Creation of new content types 
- Editorial experience considerations

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by mmiddaugh** [comment]
Discovery: 
Hierarchy of roles/permissions (VHA -> VISN -> HC system)
Error table 
What is level of control for this page/content? (Nat'l vs VISN vs Health care system level)
What is authoring experience? (edit one node which filters down)
Using right content type for this page? (currently all using content type = detail)

Service exists with default permissions in place

Need **reusable** paragraph type(s)/blocks with unique permission at different granular control levels 

Start with policies...almost all content is National
Coordinate with Kevin
