### ISSUE TITLE
Set up GA4 tracking in Platform Website (VSP-VA.gov Documentation)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#77839]
### Description:
We currently capture analytics on the Platform Website. This tracking is done via Universal Analytics, and will need to be set up in GA4 so we can keep collecting metrics on the site.

**Notes:**
- This likely will just take a few days to set-up, given there are minimal custom events, and we have access to everything we need.
- This will fall lower in priority than our work done for VFS Teams within the new main GA4 properties we are actively setting up:

   - [GA4] VA.gov - Non Production - RESET
    - [GA4] VA.gov - Production - RESET

---

### Tasks

- [x] Create new GA4 property for Platform Website documentation
- [x]  Set up tracking in GTM
- [x] Confirm tracking in GA4
- [x] Separate ticket created to QC, and then append GA4 data onto Platform Website KPIs dashboard

### Acceptance Criteria:

- [x] Tracking has been set-up within GA4, and is capturing live events.
- [x] Platform Content Team has been alerted of the change

**Comment by johnny-jesensky-adhoc** [comment]
Platform Website tracking in GA4 in this newly created Property.  [VSP Platform Documentation Sites](https://analytics.google.com/analytics/web/#/p448451986/reports/intelligenthome?params=_u..nav%3Dmaui)

I alerted the PM of the Platform Content Team (Joe Knipes), of the implementation this morning.
<img width="523" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/147662408/1a0c6eeb-f7fb-4c07-8d20-82a658ce6684">


Moving this to _**Done.**_

FYI @jestutt
