### ISSUE TITLE
Medallia - Turn off A11y intercept survey for all VA Form 5655 URLs

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#77838]
## Issue Description
[Request](https://dsva.slack.com/archives/CNCEXNXK4/p1709673664601179?thread_ts=1709670200.552029&cid=CNCEXNXK4) to turn off Medalla sitewide A11y intercept survey on VA Form 5655 URLs.

```
/manage-va-debt/request-debt-help-form-5655/introduction
/manage-va-debt/request-debt-help-form-5655/veteran-information
/manage-va-debt/request-debt-help-form-5655/all-available-debts
/manage-va-debt/request-debt-help-form-5655/contact-information
/manage-va-debt/request-debt-help-form-5655/current-contact-information
/manage-va-debt/request-debt-help-form-5655/edit-mobile-phone
/manage-va-debt/request-debt-help-form-5655/edit-email-address
/manage-va-debt/request-debt-help-form-5655/edit-mailing-address
/manage-va-debt/request-debt-help-form-5655/spouse-information
/manage-va-debt/request-debt-help-form-5655/spouse-name
/manage-va-debt/request-debt-help-form-5655/dependents-count
/manage-va-debt/request-debt-help-form-5655/dependent-ages
/manage-va-debt/request-debt-help-form-5655/employment
/manage-va-debt/request-debt-help-form-5655/employment-question
/manage-va-debt/request-debt-help-form-5655/employment-records
/manage-va-debt/request-debt-help-form-5655/enhanced-employment-records
/manage-va-debt/request-debt-help-form-5655/employment-work-dates
/manage-va-debt/request-debt-help-form-5655/gross-monthly-income
/manage-va-debt/request-debt-help-form-5655/deduction-checklist
/manage-va-debt/request-debt-help-form-5655/deduction-values
/manage-va-debt/request-debt-help-form-5655/employment-history
/manage-va-debt/request-debt-help-form-5655/income/:index
/manage-va-debt/request-debt-help-form-5655/benefits
/manage-va-debt/request-debt-help-form-5655/your-benefits
/manage-va-debt/request-debt-help-form-5655/edit-benefits
/manage-va-debt/request-debt-help-form-5655/social-security
/manage-va-debt/request-debt-help-form-5655/social-security-records
/manage-va-debt/request-debt-help-form-5655/additional-income
/manage-va-debt/request-debt-help-form-5655/additional-income-records
/manage-va-debt/request-debt-help-form-5655/additional-income-checklist
/manage-va-debt/request-debt-help-form-5655/additional-income-values
/manage-va-debt/request-debt-help-form-5655/other-income-summary
/manage-va-debt/request-debt-help-form-5655/add-other-income
/manage-va-debt/request-debt-help-form-5655/spouse-information
/manage-va-debt/request-debt-help-form-5655/spouse-name
/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-question
/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records
/manage-va-debt/request-debt-help-form-5655/spouse-employment-work-dates
/manage-va-debt/request-debt-help-form-5655/spouse-gross-monthly-income
/manage-va-debt/request-debt-help-form-5655/spouse-deduction-checklist
/manage-va-debt/request-debt-help-form-5655/spouse-deduction-values
/manage-va-debt/request-debt-help-form-5655/spouse-employment-history
/manage-va-debt/request-debt-help-form-5655/spouse-employment
/manage-va-debt/request-debt-help-form-5655/spouse-employment-records
/manage-va-debt/request-debt-help-form-5655/spouse/income/:index
/manage-va-debt/request-debt-help-form-5655/spouse-benefits
/manage-va-debt/request-debt-help-form-5655/spouse-benefit-records
/manage-va-debt/request-debt-help-form-5655/spouse-social-security
/manage-va-debt/request-debt-help-form-5655/spouse-social-security-records
/manage-va-debt/request-debt-help-form-5655/spouse-additional-income
/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-records
/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-checklist
/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-values
/manage-va-debt/request-debt-help-form-5655/spouse-other-income-summary
/manage-va-debt/request-debt-help-form-5655/spouse-add-other-income
/manage-va-debt/request-debt-help-form-5655/dependents
/manage-va-debt/request-debt-help-form-5655/dependents-count
/manage-va-debt/request-debt-help-form-5655/dependent-records
/manage-va-debt/request-debt-help-form-5655/dependent-ages
/manage-va-debt/request-debt-help-form-5655/cash-on-hand
/manage-va-debt/request-debt-help-form-5655/cash-in-bank
/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer
/manage-va-debt/request-debt-help-form-5655/monetary-assets
/manage-va-debt/request-debt-help-form-5655/monetary-asset-checklist
/manage-va-debt/request-debt-help-form-5655/monetary-asset-values
/manage-va-debt/request-debt-help-form-5655/real-estate-assets
/manage-va-debt/request-debt-help-form-5655/real-estate-asset-records
/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-assets
/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-asset-records
/manage-va-debt/request-debt-help-form-5655/vehicles
/manage-va-debt/request-debt-help-form-5655/vehicle-records
/manage-va-debt/request-debt-help-form-5655/your-vehicle-records
/manage-va-debt/request-debt-help-form-5655/vehicles-summary
/manage-va-debt/request-debt-help-form-5655/recreational-vehicles
/manage-va-debt/request-debt-help-form-5655/recreational-vehicle-records
/manage-va-debt/request-debt-help-form-5655/other-assets
/manage-va-debt/request-debt-help-form-5655/other-asset-records
/manage-va-debt/request-debt-help-form-5655/other-assets-checklist
/manage-va-debt/request-debt-help-form-5655/other-assets-summary
/manage-va-debt/request-debt-help-form-5655/add-other-asset
/manage-va-debt/request-debt-help-form-5655/expenses-explainer
/manage-va-debt/request-debt-help-form-5655/household-expenses-checklist
/manage-va-debt/request-debt-help-form-5655/household-expenses-values
/manage-va-debt/request-debt-help-form-5655/utilities
/manage-va-debt/request-debt-help-form-5655/utility-records
/manage-va-debt/request-debt-help-form-5655/utility-bill-checklist
/manage-va-debt/request-debt-help-form-5655/utility-bill-values
/manage-va-debt/request-debt-help-form-5655/utility-bill-summary
/manage-va-debt/request-debt-help-form-5655/add-utility-bill
/manage-va-debt/request-debt-help-form-5655/repayments
/manage-va-debt/request-debt-help-form-5655/repayment-records
/manage-va-debt/request-debt-help-form-5655/credit-card-bills
/manage-va-debt/request-debt-help-form-5655/your-credit-card-bills
/manage-va-debt/request-debt-help-form-5655/credit-card-bills-summary
/manage-va-debt/request-debt-help-form-5655/installment-contracts
/manage-va-debt/request-debt-help-form-5655/your-installment-contracts
/manage-va-debt/request-debt-help-form-5655/installment-contracts-summary
/manage-va-debt/request-debt-help-form-5655/other-expenses
/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist
/manage-va-debt/request-debt-help-form-5655/other-expenses-values
/manage-va-debt/request-debt-help-form-5655/other-expenses-summary
/manage-va-debt/request-debt-help-form-5655/add-other-expense
/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer
/manage-va-debt/request-debt-help-form-5655/option-explainer
/manage-va-debt/request-debt-help-form-5655/resolution-option/:index
/manage-va-debt/request-debt-help-form-5655/resolution-comment/:index
/manage-va-debt/request-debt-help-form-5655/resolution-waiver-agreement/:index
/manage-va-debt/request-debt-help-form-5655/resolution-comments
/manage-va-debt/request-debt-help-form-5655/bankruptcy-history
/manage-va-debt/request-debt-help-form-5655/bankruptcy-history-records
/manage-va-debt/request-debt-help-form-5655/enhanced-bankruptcy-history-records
/manage-va-debt/request-debt-help-form-5655/review-and-submit
/manage-va-debt/request-debt-help-form-5655/confirmation

/manage-va-debt/
/manage-va-debt/summary
/manage-va-debt/summary/copay-balances
/manage-va-debt/summary/debt-balances
/manage-va-debt/summary/debt-balances/details/
/manage-va-debt/debt-balances/letters

Debt Portal pages with custom URLS:
manage-va-debt/summary/debt-balances/details/{selectedId}
manage-va-debt/summary/copay-balances/${selectedId}/detail
manage-va-debt/summary/copay-balances/${selectedId}/detail/statement
```
---
## Tasks
- [x] Put in a request to VSignals team
- [ ] Turn off the site wide A11Y survey on all the above URLs

## Acceptance Criteria
- [ ] VSignals team has acknowledged request has been filled
 - [ ] **Scenario: Turn off A11y intercept survey for all VA Form 5655 URLs**
  - Given the VSignals team has acknowledged the request
  - When the site wide A11Y survey is turned off on all the specified URLs
  - Then the A11y intercept survey should not appear on VA Form 5655 URLs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Can we also remove the intercept survey on the Debt Portal as well?
Here are the URLs:

https://va.gov/manage-va-debt/
https://va.gov/manage-va-debt/summary
https://va.gov/manage-va-debt/summary/copay-balances
https://va.gov/manage-va-debt/summary/debt-balances
https://va.gov/manage-va-debt/summary/debt-balances/details/
https://va.gov/manage-va-debt/debt-balances/letters

_Debt Portal pages with custom URLS:_
https://www.va.gov/manage-va-debt/summary/debt-balances/details/{selectedId}
https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail
https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/statement

**Comment by HeatherRienks** [comment]
Following

**Comment by ATMiddleton** [comment]
@aubreyarcangel will coordinate with Yasine.

**Comment by ATMiddleton** [comment]
The Medallia team is currently updating the platform and this ticket is being moved to "Upcoming Sprint" until the blocker is removed.

**Comment by ATMiddleton** [comment]
@aubreyarcangel - there is another team getting up to speed.  We are awaiting further information.

**Comment by ATMiddleton** [comment]
Still in holding pattern

**Comment by ATMiddleton** [comment]
Awaiting Vsignals engagement

**Comment by aubreyarcangel** [comment]
The Debt team has request to halt this work:
https://dsva.slack.com/archives/CNCEXNXK4/p1721245299064099?thread_ts=1709670200.552029&cid=CNCEXNXK4
