### ISSUE TITLE
Update Style Guide with Google Drive Link Rules

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#77830]
Our Tip of the Sprint this sprint will amplify r[ecent Slack message banning links to Google Drive on the PW](https://thesocompany.slack.com/archives/D04D5QZALGJ/p1709816283833029). This rule, however, is not in out Style guide. Before we can post the tip of the sprint, we need to update our style guide to reflect this rule. 

### TASKS

- [x] Complete [Verification Ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/77829). 
- [x] Identify new home for info in style guide
- [x] Write the new rule 
- [x] Put the new rule in the style guide

### DEFINITION OF DONE

- [x] Style Guide has been updated with new rule regarding Google Drive links on the PW.

**Comment by BSmolensky** [comment]
Style Guide is now updated with new Google Links rule. https://vfs.atlassian.net/wiki/spaces/AP/pages/621609007/Grammar+and+punctuation#Links-to-Google-Dive

**Comment by BSmolensky** [comment]
This ticket is ready to close.
