### ISSUE TITLE
Restore files from Loki/Cloudwatch

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#77840]
## Issue Description
In support of the Code Yellow effort, we'll need to assist with the restoration of old files from Loki & Cloudwatch logs. This task is critical in support of the Code Yellow initiative.

---
## Tasks
- [ ] Receive guidance from Kyle and/or engineering leadership regarding what is to be done
- [ ] Support as needed
- [ ] Validate correct results w/ Kyle

## Acceptance Criteria
- [ ] Missing files have been restored to the best of our abilities and have been validated as being sufficient.
