### ISSUE TITLE
Content model: VAMC "Policies" 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7784]
## Problem Statement
The Policy page is mostly national content (with some local content) and we want to move it so that it’s 
How might we change the structure of [Policies page content](https://www.va.gov/pittsburgh-health-care/policies/) so that
- some content can be reusable
- national content cannot be edited locally
- the risk of introducing errors is reduced
- the editorial experience is enhanced and efficient
- easy for national updates to be made once and cascaded down throughout the 143 system websites

<details>
<summary> Content mapping </summary>

![image](https://user-images.githubusercontent.com/55411834/94450854-014ec500-016b-11eb-86be-0df23705008c.png)

</details>

## OKR
Decrease the amount of national content which is locally editable 

## Acceptance Criteria
- [ ] National content areas are no longer editable at the system or facility level

## Definition of done

- [ ] Content structure changes
- [ ] Front end mapped to new data structure
- [ ] Pages render as expected 
- [ ] Editorial experience review with CMS
- [ ] Content model review with CMS
- [ ] Feedback session with VAMC upgrade team 
- [ ] Migration plan
- [ ] Testing plan

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
