### ISSUE TITLE
Further updating of Phase pages from SME feedback

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#77844]
## Purpose
Ongoing feedback from various SMEs require further updates and iterations of FDG Phase pages.

## Tasks
- [x] Identify SMEs 
- [x] Collect asynchronous feedback and comments
- [x] Revise pages based upon learnings

## Acceptance Criteria
- [x] Pages are updated based upon SME input
