### ISSUE TITLE
Launch New Veteran Support DOMO Dashboard 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#77873]
## Issue Description
As a Veteran Support team member, I need a DOMO dashboard that reflect current status of all Salesforce cases. 
---
## Tasks
- [ ] Review final DOMO dashboard 
- [ ] Confirm required data is present 
- [ ] Confirm dashboard reflects Open Cases 
- [ ] Confirm dashboard reflects Closed cases 
- [ ] Confirm dashboard reflects Backlogged cases 
- [ ] Confirm data can be manipulated by date range 
- [ ] Confirm dashboard reflects data overview 
- [ ] Confirm dashboard reflects graphical breakdown analysis 
- [ ] Confirm dashboard reflects closed cases analysis 
- [ ] Confirm dashboard reflects open cases analysis 
- [ ] Confirm all Veteran Support team members have access to dashboard
- [ ] Remove team access to old dashboard 

## Acceptance Criteria
 - [ ] **Scenario: Launch New Veteran Support DOMO Dashboard**
   - Given the DOMO dashboard is created for the Veteran Support team
   - When the dashboard is launched
   - Then the dashboard should display all Salesforce cases, including open, closed, and backlogged cases
   - And the dashboard should allow data manipulation by date range
   - And the dashboard should provide an overview of the data
   - And the dashboard should provide graphical breakdown analysis of the cases
   - And the dashboard should provide closed cases analysis
   - And the dashboard should provide open cases analysis
   - And all Veteran Support team members should have access to the dashboard
   - And the old dashboard access should be removed
   - 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Demo scheduled for 3/11/24

**Comment by newworld2616** [comment]
https://va-gov.domo.com/page/2073440432

**Comment by newworld2616** [comment]
Launched!
