### ISSUE TITLE
Create an Exception for IIR Survey in Medallia

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#77872]
## Issue Description
IIR URL uses the old CMS and doesn't present the correct properties to locate survey by assigned survey number.  An exception must be created to discover the assigned URL 

---
## Tasks
- [ ] write code for exception 
- [ ] Test new code 
- [ ] confirm new code recognizes appropriate URL 
-
## Acceptance Criteria
 - [ ] **Scenario: Create an Exception for IIR Survey in Medallia**
  - Given the IIR URL uses the old CMS and doesn't present the correct properties to locate survey by assigned survey number
  - When an exception is created to discover the assigned URL
  - Then the new code recognizes the appropriate URL
  - And the exception is successfully implemented in Medallia
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andreahewitt-odd** [comment]
@aubreyarcangel @ATMiddleton If this ticket is complete, can we check off the AC?

**Comment by aubreyarcangel** [comment]
@andreahewitt-odd checked off AC. Here's [the ticket](https://github.com/department-of-veterans-affairs/content-build/pull/2022) related to the work
