### ISSUE TITLE
Apply CAIA Recommendations for VHA Intercept Survey Styling 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#77870]
## Issue Description
_Apply CAIA recommendations to VHA Intercept Survey 
---
## Tasks
- [x] _Review recommendations 
- [ ] Apply styling updates 

## Acceptance Criteria
 - [ ] **Scenario: Apply CAIA Recommendations for VHA Intercept Survey Styling**
  - Given the CAIA recommendations are reviewed
  - When the recommendations are applied to the VHA Intercept Survey styling
  - Then the VHA Intercept Survey should have updated styling according to the CAIA recommendations
 
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
https://app.slack.com/client/T03FECE8V/C05NUG2QB9S?selected_team_id=T1ZD0UBMZ

**Comment by aubreyarcangel** [comment]
After [discussing this issue with the Medallia team](https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/78405), it was determined that there is no quick fix for the issues identified in the [a11y audit conducted by CAIA](https://docs.google.com/spreadsheets/d/1Z_xXH2WnyP0YWNCJFKs0duwgSIug9VNEmzWR9RzxSYM/).
