### ISSUE TITLE
[FE] Create e2e tests for failed scenarios

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#77876]
## User Story
Create e2e tests for failed flows through the travel claim app.

## Tasks
- [ ] Create or update e2e tests
  - [x] I am a patient who has already filed for a claim today and have no other facilities to file a claim for
  - [x] I am a patient who has attempted and failed to validate more than 3 times
  - [x] I am a patient who has used a link with a UUID not found
  - [x] I am a patient who has encountered an error submitting a travel claim
  - [x] I am a patient who has encountered an error but also a success while submitting a travel claim
  - [x] I am a patient who has answered no to travel vehicle
  - [x] I am a patient who has answered no to travel address
  - [x] I am a patient who decides to change an answer an uses the back button from the review page
  - [x] I am a patient who encounters an error retrieving travel claim data
  - [x] I am a patient who attempts to proceed from review page without checking the box to confirm
  - [x] I am a patient who attempts to click continue from facility selection without checking at least one facility
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/77876?planning-poker) with Zenhub @brianseek @lee-delarm6
