### ISSUE TITLE
Updates to request additional documentation for adopted children

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#77885]
## Issue Description
If a user has an adopted child, they're required to submit additional documentation. We need to update the form to inform the user both on the dependent child information page and on the supporting documentation page.

## User stories
As a veteran with an adopted child,
I need to understand/see if I am required to submit any additional information related to this,
so that I can have my Pension application processes properly.

As a veteran with an adopted child,
I need to understand/see if I am required to submit any additional information related to this,
so that I can have my Pension application processes properly.

---
## Tasks
- [ ] _Add a conditionally displayed alert to the "What is your relationship?" question on the dependent information page, if the answer is "They're my adopted child_
- [ ] _Update the supporting documents page to include a bullet item for adoption paperwork in the documents list, if the user selected “They’re my adopted child” for any dependent_
- [ ] _Update the bulleted documents list so that every items starts with a capital letter_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] 

## Resources
- [Figma design for dependent information page with new alert](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2292%3A32130&mode=design&t=QOHLUDM5jmheVlWo-1)
- [Design Zenhub ticket](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/76299) with additional context

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77885?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by gmaciolek** [comment]
<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--066f8d8b717704eb78805cec3bbb530e7bee9f35/Screenshot%202024-03-25%20at%205.14.48%E2%80%AFPM.png" alt="Screenshot 2024-03-25 at 5.14.48 PM.png" />

**Comment by gmaciolek** [comment]
Supporting documents page: add a bullet that conditionally displays if "They're my adopted child" is selected. Bullet should say, "Adoption papers or amended birth certificate"
<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOElLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d10836f08737bfdba1d7fc7e646b7c2aa78ff183/Screenshot%202024-03-25%20at%205.28.49%E2%80%AFPM.png" alt="Screenshot 2024-03-25 at 5.28.49 PM.png" />

**Comment by danlim715** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/28797

**Comment by aplatt-coforma** [comment]
Changes look good.
<img width="642" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36af8868ae18b752c337f863d073d817f6b08087/Screenshot%202024-04-09%20at%206.20.46%E2%80%AFAM.png" alt="Screenshot 2024-04-09 at 6.20.46 AM.png" />
