### ISSUE TITLE
DISCOVERY: Consolidate External Service Statsd Metrics

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#77891]
## Description
Currently, our Datadog integration for breakers metrics (leveraging the circuit breaker pattern middleware integrated into Faraday) introduces challenges due to the lack of wildcard filtering and/or tagging support. Previously, with Prometheus, we could utilize wildcards to dynamically generate graphs for each service, streamlining our monitoring process. However, with Datadog, metrics are received individually (see any of the [api_external_http_request metric](https://vagov.ddog-gov.com/metric/explorer?fromUser=false&start=1710172888023&end=1710176488023&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMgViBpOGPIQAHQaCJ4aUM2NEE5wxAg6kWhOXAjyTkZBbU4AogBqAMqLTgDCmD71anDdVcAAVDwgPAC6VK7ueJih4ReqVxgxpfHHZyBtWGg5oPIYXwiDZRQHAwJyZa4aCCZRJoURwJxyRTKdKwqAwuFOehMZQiNweNDHfgQeyYLAIhQ5ECwkRKU48PjveSwhCrKTCGAoERXNA8IA)s and how the service name is integrated into the metric name itself), requiring manual creation of graphs for our 54+ downstream services. This manual approach is cumbersome and inefficient, disrupting our workflow. 

[Our OpenMetrics configuration ](https://github.com/department-of-veterans-affairs/devops/blob/548d04d193eaf5428584ed78e01e8ec33919f5f9/ansible/build/roles/datadog/vars/vets-api.yml#L4) currently collects metrics by 'api*', and we suspect that this may be affecting how breakers metrics are grouped. Our intention is to improve the metrics configuration by enabling filtering based on service/tag, to facilitate more dynamic chart creation.

There is an additional [conversation here](https://oddball.slack.com/archives/C045LCF8WU8/p1709837590820059) regarding some of the details in early discussion.

## Tasks
- [ ] Evaluate our OpenMetrics Config
- [ ] Evaluate other options for metric grouping, sorting, tagging, etc. Research potential solutions within Datadog to group individual metrics effectively, allowing for dynamic graph generation similar to our previous setup with Prometheus.

## Summary
Prior to the Datadog migrations, External Services data could be computed from one metric, ex:`avg(api_external_service_up) by (service)`. This is no longer the situation in Datadog. Each external service generates 8 unique metrics.
<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--320aca759dd6a631316a2ee17f355a79e35817b8/Screenshot%202024-03-07%20at%201.47.49%20PM.png" alt="Screenshot 2024-03-07 at 1.47.49 PM.png" />

The goal is to reduce ~250 metrics to 8 metrics. Each metric can be filtered by `external_service`.
```
vets_api.statsd.api_external_http_request_failed{$env, $external_service}
vets_api.statsd.api_external_http_request_success{$env, $external_service}
vets_api.statsd.api_external_http_request_time.95percentile{$env, $external_service}
vets_api.statsd.api_external_http_request_time.avg{$env, $external_service}
vets_api.statsd.api_external_http_request_time.count{$env, $external_service}
vets_api.statsd.api_external_http_request_time.max{$env, $external_service}
vets_api.statsd.api_external_http_request_time.median{$env, $external_service}
vets_api.statsd.api_external_service_up{$env, $external_service}
```
## Acceptance Criteria
- [ ] Discovery document that provides a strategy for consolidating the External Services StatsD metrics that the Infra team has also weighed in on
- [ ] Discuss options with DevOps COP **_or_** (pref) aesync with @ph-One before the Sprint closes on 5/8/2024

**Comment by jennb33** [comment]
Per @Kshitiz-devops on 4/30: tried to push helm package to GHCR but we don't have package enable in github due to licensing. Will need to make changes so it can work with ECR and he will be doing that on 5/1

**Comment by jennb33** [comment]
@Kshitiz-devops is working with @ph-One on this ticket, @jennb33 editing ticket to make it a Discovery ticket not the actual work for now.

**Comment by jennb33** [comment]
Per @Kshitiz-devops, this ticket requires more time for digging so it needs to roll to Sprint 53. 
cc: @LindseySaari

**Comment by Kshitiz-devops** [comment]
https://docs.datadoghq.com/developers/dogstatsd/dogstatsd_mapper/ have more information on stasd metric and the changes to be made most probably in https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/f4049a7190beb66f0f49cc28b1980cc4af82c615/apps/datadog-agent/prod/values.yaml#L29

**Comment by rmtolmach** [comment]
We want to make sure a `terraform apply` in the devops repo will not override these settings.

Is this file being used anymore? https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/datadog/vars/vets-api.yml

Kshitiz will reach out to Kyle to ask some configuration questions.

**Comment by LindseySaari** [comment]
@jennb33 Did we make that ticket for applying this to prod and adjusting the charts?
