### ISSUE TITLE
Update Feature Toggles Guidance

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#77896]
## Issue Description
[This page](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-EnablinganddisablingfeaturesusingtheFlipperUI) on Platform Website needs to be updated to advise re: Setting `actor_type` to `cookie_id` ONLY AFFECTS THE FRONTEND, NOT THE BACKEND

Slack Support Thread:
**[HERE](https://dsva.slack.com/archives/CBU0KDSB1/p1709841966594159)**
---
## Tasks
- [x] Work with Holden Hinkle to update language 
- [x] Confirm accuracy with Holden Hinkle

## Acceptance Criteria
- [x] Updated page ready for deployment
- [x] Confirm Developer docs Platform page appears correctly after deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
cc: @holdenhinkle

**Comment by jknipes** [comment]
@BSmolensky & @laucon please add your planning poker estimates

**Comment by jknipes** [comment]
This ticket deprioritized in favor of [75172](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/75172)

**Comment by jknipes** [comment]
Moved to top of Backlog for an upcoming sprint

**Comment by CherylEvans** [comment]
@jknipes 
I contacted Holden on the Slack channel, and he initiated the issue.
My message ([link](https://dsva.slack.com/archives/CBU0KDSB1/p1711650215265199?thread_ts=1709841966.594159&cid=CBU0KDSB1)):
Hi Holden. I’m working on this issue (ZH ticket [77896](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/77896)). I created a draft of [this page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Feature+toggles+guide) (source page) in my PC repo and made the following changes:
Dev doc -> Infrastructure -> Feature toggles guide -> 2. Configure Flipper UI settings -> Percentage of Logged in Users -> 2nd Paragraph:
“If the feature toggle’s actor_type in config/features.yml is set to cookie_id rather than user, the feature instead applies to only a percentage of users for the duration of a cookie within a single browser, regardless of their logged in status.
Setting actor_type to cookie_id ONLY AFFECTS THE FRONTEND, NOT THE BACKEND.
This is useful when you need to apply a staged rollout that involves an unauthenticated user experience.”

Are you okay with this language edit? If not, let’s discuss more options.
Thank you, Holden. I look forward to talking with you soon!

**Comment by CherylEvans** [comment]
@jknipes Holden approved 3 changes/updates:

- Configuration Option language was changed from "Percentage of Logged-in Users" to "Percentage of Users."
- I added "Setting actor_type to cookie_id ONLY AFFECTS THE FRONTEND, NOT THE BACKEND." after the first sentence.
- 2 types of users and their descriptions were added and bolded for emphasis.

**Percentage of Users**
If the feature toggle's actor_type in config/features.yml is set to cookie_id rather than user, the feature instead applies to only a percentage of users for the duration of a cookie within a single browser, regardless of their logged in status.
Setting actor_type to cookie_id ONLY AFFECTS THE FRONTEND, NOT THE BACKEND. 
This is useful when you need to apply a staged rollout that involves an unauthenticated user experience.
**Logged-in Users**
Enable the feature for only a percentage of logged-in users. It will be applied to the same users each time they return to the site (even when they log out and back in) as long as you don’t change the percentage.
**Not Logged-in Users**
If the feature toggle’s actor_type in config/features.yml is set to cookie_id rather than user, the feature instead applies to only a percentage of users for the duration of a cookie within a single browser, regardless of their logged in status. This is useful when you need to apply a staged rollout that involves an unauthenticated user experience.

**Comment by CherylEvans** [comment]
Updates are migrated to the Developer docs [source page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Feature+toggles+guide).

**Comment by jknipes** [comment]
Page has deployed successfully, moving to _Done_
