### ISSUE TITLE
[UX/FE] Minor content change on Toxic Exposure opt in page

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#77907]
## Issue Description

From Danielle Thierry:
> Hi 10-10 team! With Aliyah out today, I'm dropping in to share a request for a minor content tweak from VHA on this screen of the online 10-10EZ:
> Change "during active duty training or service" to "...during training or active duty service"

<img width="428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a81df9bebd98af4a5ada8e67ed48d60f61a5290e/image.png" alt="image.png" />

---
## Tasks
- [x] Update design source of truth files
- [x] Update in development
- [x] Validate with PM
- [x] Push to production

## Acceptance Criteria
- [x] Content is updated 
---

**Comment by longmd** [comment]
@jessicastump , this has been completed and is on its way to staging. 

![Screenshot 2024-03-08 at 11 51 58](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/e7ef3cf5-a381-44aa-9081-01e05671e8ca)
