### ISSUE TITLE
Generate "tech debt" opportunities

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7790]
## Background
Given we have an opportunity to pay down "tech debt" 
I want to generate problem statements/opportunities before digging into solutions
so we have a better sense of what success looks like after we've resolved some of that debt.

## Tasks
- [ ] Generate ~5 "tech debt" problem statements/opportunity areas for Public Websites 
- [ ] Document those here or in the appropriate repo folder (we can chat about where makes sense)

## Acceptance Criteria
- [ ] The PW team has a better sense of tech debt that can be paid down

**Comment by kelsonic** [comment]
Generating tech debt in progress... ⚙️ 😉

**Comment by ncksllvn** [comment]
Biggest ideas for me -

1. Purge the template files from vets-website that have been deprecated since Drupal was implemented
1. Restructure the `src/site` directory to have a `templates` directory. Or maybe move the templates a directory above into `src/templates`. Not sure but we need a directory structure that clearly indicates that these are HTML fragments and Drupal layouts and not JavaScript code.
1. If Decision Reviews is in Drupal by the time we start this, then all hubs have been migrated. I wonder if we could consider migrating the whole repo back into vets-website at that point, since the content writers shouldn't have to look there anymore. I would love to do this because it's so confusing have vet-website/vagov-content/drupal all intertwined. 
1. A testing pattern for cross-domain redirects. I wrote a ticket for that somewhere. We could also probably figure out a way to speed up redirects by separating it out from the rest of the proxy-inject code.
1. Clean up the `static-pages` bundle, where we work a lot - https://github.com/department-of-veterans-affairs/va.gov-team/issues/7751.

**Comment by kelsonic** [comment]
Adding random ideas as I think of them:

1. Add `data-template-id` to liquid templates so that we can more easily find them on the dom when debugging.

**Comment by ncksllvn** [comment]
So the vagov-content repo is nearly done now that Decision Reviews is migrated...that means there isn't much left going on in vagov-content. I wonder if we can consider removing that as part of our tech debt sprint.

**Comment by MickinSahni** [comment]
@stephorkandatx getting this on your radar, there's a lot of great stuff here to groom!

**Comment by kelsonic** [comment]
Another tech debt opportunity: Change references to `homepage_banner` to `site_wide_banner` (or similar) as it's been expanding in scope as per [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8039)

**Comment by stephorkandatx** [comment]
@kelsonic and/or @ncksllvn is there a tech debt item here or https://github.com/department-of-veterans-affairs/va.gov-team/issues/7366 that you would want to do for this sprint?

**Comment by jilladams** [comment]
All items closed, A6 now managing PW tickets in CMS repo. Closing.
