### ISSUE TITLE
[BUG] Update vets-api-mockdata for closed claims

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#77912]
## Background Context
While testing things on closed claims found that our mock data is inaccurate. 

### Bug
Currently when a claim is closed the `claim.attributes.claimPhaseDates.lastestPhaseType` is showing `Complete` which is inaccurate. Additionally `claim.attributes.claimPhaseDates.previousPhases` is showing `phase1CompleteDate: null` which is inaccurate.

## Engineering Details

lighthouse/benefits_claims/show/006_ClosedClaim.yml

## Tasks
- [ ] `claim.attributes.claimPhaseDates.lastestPhaseType` should show `COMPLETE` for closed claims
- [ ] `claim.attributes.claimPhaseDates.previousPhases` should show `phase7CompleteDate: [NOT_NULL_DATE]` **(NOTE this date should match the phaseChangeDate and closeDate. The phaseChangeDate is located in claim.attributes.claimPhaseDates.)**

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The mock data is valid for closed claims

**Comment by pmclaren19** [comment]
@jacobworrell verified and we have already resolved this issue! So we can close this ticket.
