### ISSUE TITLE
Update content about single direct deposit account requirement

### ISSUE THREAD

**Issue by shannonkford** [department-of-veterans-affairs/va.gov-team#77921]
## Issue Description
VA is in the process of telling Veterans about a change for those who currently have more than one bank account listed for disability compensation, pension, and education benefit payments. The same account needs to be used for all of those benefits, starting April 20, 2024.

CAIA and the Pension team are working through changes to their direct deposit and review/confirmation pages to support this change. We should be able to re-use approved content (and design component) from pension, which is expected from CAIA **on 3/11**, in the 526 form. Desired date for production is **3/20/2024**.

### User stories
As a claimant, I need to know that the direct deposit info I provide won't be updated until after a decision is made on my claim, and only if an award is made.

As a claimant, I need to know that if I already receive education payments, those will use the direct deposit info I list in this 526 claim if and when I receive a disability award. 

### Design
in [Figma](https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=0%3A411&mode=design&t=857cgITlNMUBg7al-1)

### References: 

- VA.gov's [Change your VA Direct Deposit](https://www.va.gov/change-direct-deposit/) page
- [Slack discussion - initial creation of ticket](https://dsva.slack.com/archives/C06E83RNLQM/p1708959156208089)
- [Slack discussion - in progress questions](https://dsva.slack.com/archives/C053UDWMH7U/p1710512199691099)
- Pension's ticket [77020](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/77020)
- CAIA ticket [77464](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77464)
- Pension's [FIGMA files](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2146%3A2284&mode=design&t=z7ofhG2z9Fagu35q-1)
- Implementation tracked in [Update content about single direct deposit account requirement#78597](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78597)

---
## Tasks
- [x] Mock up info component on 526 direct deposit page and on confirmation page using approved content from pension (not minor changes may need to be made for the 526)
- [x] Review w/enabling team
- [ ] Hand-off to engineering for build

## Acceptance Criteria
- [ ] Above tasks are complete

**Comment by mengA6** [comment]
I looked into this to initially assess scope for implementation, given the desired date for production.

Based on what [the pension team designed](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2146%3A2284&mode=design&t=z7ofhG2z9Fagu35q-1) (there, only option 1 is relevant to our situation) and also considering our existing payment information screens, we should only need content changes and a new [alert component](https://design.va.gov/components/alert).

cc @christinec-fftc @RakshindaAslam @alatempa24

**Comment by mengA6** [comment]
Wait @shannonkford do we need to create logic to not accept another bank account if the user already has an active one for education or pension benefits?

**Comment by RakshindaAslam** [comment]
If we choose to not accept a new bank account, we would need to direct them to the location where they can change the account (I am guessing VA Profile). Or we accept the new account and let the user know that this will be updated as their primary account ( if we know that VBA will update it) .

**Comment by mengA6** [comment]
Right. @Shannonkford can you let us know the overarching approach for where the user can update / view that single bank account and how we should accommodate that within the 526?

**Comment by shannonkford** [comment]
@mengA6 We do not need to prevent them from creating an account.

**Comment by mengA6** [comment]
Notes on business logic

We clarified in [today's sync](https://dsva.slack.com/docs/T03FECE8V/F068SQT00MC?focus_section_id=temp:C:fcIdba99ab0d4b349269a2e6bd7e) that the future behavior will be: if a user has an existing bank account they're using for education benefits, and they add a bank account in the disability or pension application flow, that new bank account will override the bank account used for education benefits - but the accounts are not updated until the new claim is granted.

Also I verified in staging (under staging user 78) on the disability benefits flow that if a user has a bank account on file for disability benefits and clicks "New account", it seems the newly added account replaces the account already stored (within disability benefits). Screen recording attached.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ptQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--caa3dec341a78e75184275e6e0749c1a4c937205/Screen%20Recording%202024-03-15%20at%204.31.06%20PM.mp4)

**Comment by mengA6** [comment]
I have a first pass at this [in Figma](https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=0%3A411&mode=design&t=A1gGHgORxb7gEiGw-1). One question. There's a screen state where a user is already receiving disability benefits, then they add a new bank account on a new disability benefits application, replacing the current bank account. Here's the current state of that attached.

<img width="323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekxuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9600195c02ce4a534297bd6b399317696be58da6/Screenshot%202024-03-15%20at%205.04.44%E2%80%AFPM.png" alt="Screenshot 2024-03-15 at 5.04.44 PM.png" />

I think the content of that alert should be updated with this change, and I didn't see it in the pension team's work. Here's [my first pass at it](https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=3217-48110&mode=design&t=A1gGHgORxb7gEiGw-4), but it isn't great. Should we run this by CAIA?

**Comment by mengA6** [comment]
Made some updates in Figma showing current and existing screens, and I have an additional question ([asked in Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1710795591696749?thread_ts=1710512199.691099&cid=C053UDWMH7U)) about whether we should show the alert in the saved state as well as the "add account" edit state.

**Comment by jinaryu** [comment]
Made some updates in Figma in response to Shannon's comments ([link here to Figma frame](https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=3294%3A4457&mode=design&t=E4BW8NfNpxVJYfxB-1))

**Comment by mengA6** [comment]
Design is resolved with those updates from Jina! I just cleaned up [Figma](https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=0%3A411&mode=design&t=857cgITlNMUBg7al-1) and moved all the alternate options to another page.

**Comment by mengA6** [comment]
Implementation tracked in [Update content about single direct deposit account requirement#78597](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78597)

**Comment by mengA6** [comment]
Pending review from Christine per [this slack thread](https://dsva.slack.com/archives/C053UDWMH7U/p1711122820506429?thread_ts=1710512199.691099&cid=C053UDWMH7U)

**Comment by mengA6** [comment]
Closed the loop with Christine per [payment info sync](https://dsva.slack.com/docs/T03FECE8V/F068SQT00MC?focus_section_id=temp:C:fcIb3bf9833e6f54d05848c586d6) today.
