### ISSUE TITLE
Copy of Find a Rep LIVE - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#77927]
## Issue Description
Live user testing of Find a Representative experience with mobile and assistive technology (AT) users.

## Tasks
- [ ] [Review AT documentation](https://depo-platform-documentation.scrollhelp.site/research-design/research-assistive-technology-sessions)
- [ ] Create GitHub research folder
- [ ] Split mobile vs AT specific content
- [ ] Create research plan
- [ ] [Review AT screeners](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions#Successfulscreenerquestions-AssistiveTechnology)
- [ ] Define screener questions
- [ ] Create conversation guide
- [ ] Submit all materials to team for review
- [ ] [Update CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74488)
- [ ] Create revisions Zenhub ticket

## Acceptance Criteria
- [ ] All materials ready for review

**Comment by jfinnerty13** [comment]
https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/498
