### ISSUE TITLE
Staging Review: Updates to Caution Flags within the Comparison Tool

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7792]
## Steps to complete Staging Review: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline: _No product outline for this work because it was started before we moved over to the new VSP process._ 
   - Product Description: The changes implemented in the Comparison Tool are present on both the search results and profile pages of the tool. The updates make the caution flags more prominent and explanatory in an effort to better alert and inform users of the comparison tool to caution flags so that they are able to make the best decision regarding how to utilize their education benefits. 
- Link to release plan with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
   - [Caution Flag release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/caution-flags/CFreleasePlan.md) 
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
   - Navigate to https://staging.va.gov/gi-bill-comparison-tool (user does not need to be authenticated to review any of the updates we made in this effort)
   - Changes related to Caution Flags are available on both the Comparison Tool Search Results page as well as the Comparison Tool Profile page
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
   - Link to test execution logs: https://dsvavsp.testrail.io/index.php?/reports/view/56
   - Preconditions for testing requires utilization of the following files: [7151.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4456751/7151.zip)
   - Cross-Browser & Functional Test Plan: [GIBCT_ Caution Flag cross-browser testing - TestRail.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4456752/GIBCT_.Caution.Flag.cross-browser.testing.-.TestRail.pdf)
  -  Accessibility Test Plan: [https://app.zenhub.com/files/133843125/db665699-f759-4cb3-9b7b-ffc971310cdd/download](https://app.zenhub.com/files/133843125/db665699-f759-4cb3-9b7b-ffc971310cdd/download)
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
   - Link to coverage:  https://dsvavsp.testrail.io/index.php?/reports/view/56
   - Summary Defects: We do not currently log defects in test rail; all defects can be found in GitHub here: https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3A%22bug%22+and+label%3A%22bah-cautionFlag%22+
- Link to your accessibility test cases: 
  - Preconditions for testing requires utilization of the following files: [7151.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4456751/7151.zip)
  - **TestRail** [https://app.zenhub.com/files/133843125/db665699-f759-4cb3-9b7b-ffc971310cdd/download](https://app.zenhub.com/files/133843125/db665699-f759-4cb3-9b7b-ffc971310cdd/download)
- List of known issues (with links to tickets when applicable)
   - None

## Meeting attendees from **requesting team**
- Product Manager (required): @dneel-bah Darrell Neel
- DEPO product lead (required): @mattpointzxer0 Mat Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): 
@delli-gatti-michael Michael Delli-Gatti

## Scheduling
Preferred dates or times: Tuesday 04/14/2020 between 11AM - 12PM

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by meganhkelley** [comment]
Scheduled 4/14 @ 11:30 am — please take a look @desireeturner to confirm attendees look correct for your end.

**Comment by meganhkelley** [comment]
Also @desireeturner could you please update the description of the ticket here to be very specific about what the changes are that y'all are implementing, and what exactly folks are supposed to be reviewing? (I know folks have seen this before so hopefully they're aware, but always good to clarify! Also this will be helpful context in the absence of a product outline.) Thank you!

**Comment by desireeturner** [comment]
@meganhkelley Updated! All our documentation is included now. Please let me know if we missed anything or more information is needed.

**Comment by CrystabelReiter** [comment]
No feedback ticket needed. This is good to go from the VSP design side.

**Comment by peggygannon** [comment]
Hello @desireeturner I've reviewed this content earlier and provide the below feedback to the flags. I'm putting my feedback here again. This is feedback to align with VA.gov content style, I recommend we update the following update: 

1. The Department of Education has placed this school on Heightened Cash Monitoring **because of** financial or federal compliance issues. 

2. "Assigned receiver" term. Who is this? can we put this in plain language terms for users? 

3. This school's recertification application to participate in the Department of Education **federal student financial assistance programs** has been denied.
is this an official program name? I lowercase this b/c it sounds like a group of programs. 

4. This school's accreditation has been taken away and is under appeal, or the school has been placed on probation because it didn't meet acceptable levels of quality.

I changed "revoked" to taken away for plain language purposes


5. There may be a potential loss of program approval for this school.
changed lapse to "loss of" for plain language


6. Please lowercase the "g" in government in this header: 
School has settled its case with the U.S. Government

7. Please lowercase the "s" in state: 
School has settled its case with the State Attorney General

8. Post 9/11 GI Bill (CH33) benefits can't be used at this school as the school is not approved for them.
Please spell out Chapter 33

**Comment by dneel-bah** [comment]
Internal staging review item: When no link to school; text should not be linked and have a period at the end.

**Comment by dneel-bah** [comment]
Issues reported in this [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7792#issuecomment-613578422) addressed in #8082 .

**Comment by dneel-bah** [comment]
All attached issues have been closed out.  Closing this issue out as completed.
