### ISSUE TITLE
Update Sidekiq Monitors

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#77936]
## Summary

The current Sidekiq monitors alert on hard coded values. These monitors should be alerted using anomaly monitors.

## Tasks

- [x] Create Retry Alert
- [x] Create Enqueue Alert
- [x] Update terraform files
- [ ] Delete old monitors

**Comment by RachalCassity** [comment]
Pushed modifications to flooose/datadog-tags-octo-compliance, https://github.com/department-of-veterans-affairs/devops/pull/14073/files#diff-1288cd9a224713e1a02004dfe82bf2c1f7524dad5ae7f5d7717aea7c9bc71aa7.
