### ISSUE TITLE
Collaboration Cycle for [Veteran Facing forms , List and Loop, Reusable multi-page]

### ISSUE THREAD

**Issue by AdamOye** [department-of-veterans-affairs/va.gov-team#77934]
### VFS team name

Veteran Facing Forms 

### Product name

List and Loop

### Feature name

Reusable multi-page

### GitHub label for team

1-forms-audit-digitize

### GitHub label for product

List-Loop

### Public DSVA Slack channel for VFS team

veteran-facing -forms

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

Feb-20-2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

No

### Do you need to capture any additional analytics or metrics?

No

### Product outline

[Product Outline ](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/Multi-Page/Product%20Outline.md)

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

- Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C044AGZFG2W/p1710168180492829)
</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Staging Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] [Staging URL](https://staging.va.gov/mock-simple-forms-patterns/introduction)
- [x] [Documentation for developers](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/patterns/array-builder/README.md)
- [ ] Specify which pages are included in the review  - See documentation below, no log in or test users required     
- [x] [Documentation on what and how to test](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Design/list-and-loop.md)
- [x] [Figma files if you need static reference](https://www.figma.com/file/OxzngjwHg4n0oNSGHkwJ5Z/DSC---WIP---Pattern---Multi-page-List-and-Loop?type=design&node-id=1-128050&mode=design&t=XF9mmiaY2rhqsv2z-11)

  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts** - worked with Megan Zehnder in office hours for content changes directly in Figma Files
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
  
**IA artifacts** - not applicable
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
** Note this is a pattern not a form, so we are providing the Cypress tests and code coverage only. Ok from Matthew and pinged Ian not to do test rails 

- [x] [E2E tests Optional Flow](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/simple-forms/mock-simple-forms-patterns/tests/e2e/mock-array-builder.cypress.spec.js)
- [x] [Required Flow](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/simple-forms/mock-simple-forms-patterns/tests/e2e/mock-array-builder-required.cypress.spec.js)
- [x] [Code coverage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage)
- [x] [Known Issue](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1187)
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/81050).
  
##### Platform actions
- [ ] Slack thread with VFS team: https://dsva.slack.com/archives/C044AGZFG2W/p1714424144214339
- [ ] Meeting date/time: March 7, 2024 at 10.30 AM ET

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link ](https://oddball-io.zoom.us/rec/share/ZSkzuCdhrPUBRk0aU0Mow24zIZHMH4BqNAJ5gsiIX4g6GUf-xMLtjjnM0BVU3iOR.QBfi2BlOZlI4ZQsJ)
  - Password: z9gV$x9V
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

**Comment by AdamOye** [comment]
we are only going through staging review.

**Comment by AdamOye** [comment]
Update: Engineer has some clean up to do post QA testing. **Cancelling staging review to map out new plan**

**Comment by AdamOye** [comment]
new plan established, re-opening in prep of staging review
