### ISSUE TITLE
Burial | Confirmation Email | VA Notify Trigger

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77943]
## Issue Description
_The VA Notify team has requested a trigger that will initiate the confirmation emails we will be sending to Veterans who submit a 530EZ burial claim._

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
- [Forms Strike Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/form%20confirmations) can assist with setting up a confirmation email trigger

---
## Tasks
- [ ] Review VA Notify [API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#reviewing-our-api-docs) 
- [ ] Get access to the Self Service Portal
- [ ] Build notification code to call the VA Notify API for the burial form.
   - [ ] Notification should trigger an email to all users who successfully submitted a 530EZ form.
   - [ ] The default email address should be the email the user entered into the 527 form. If no email exists within the form, use their MyVA profile email.
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Determine alerting and error handling if email fails to deliver

## Acceptance Criteria
- [ ] A notification trigger that sends an email to users who successfully submitted 530EZ claims
- [ ] Logging and monitoring for failed sends

**Comment by steele-lm** [comment]
We discovered that the burial form has an existing confirmation email, so no trigger is needed.
