### ISSUE TITLE
Burial | Draft Confirmation Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77945]
## Issue Description
_The Burial 530EZ form does not currently send a confirmation email to individuals who submit a claim. An email needs to be drafted and a template needs to be created in VA Notify._

Trigger for email will be handled in this ticket #77943.

[Email Text example from Ch31 confirmation email](https://docs.google.com/document/d/1Q7ns4wmVe8tO2N4CtUvj_li9jGMVJRq6vMskAs0rVZw/edit?usp=sharing)

[Draft burial email copy](https://docs.google.com/document/d/1EYAcOxEPykMe2CMo7a7zU1Alw6HcHd_8CSnkBiqce2s/edit?usp=sharing)

---
## Tasks
- [x] Draft copy
- [ ] Confirm copy with VBA SME(s)
- [ ] Complete CAIA review
- [ ] Complete stakeholder review of final draft (Emily, Julie S., VBA SME)
- [ ] Create VA Notify Template

## Acceptance Criteria
- [ ] Approved email copy from VBA and OCTO
- [ ] Confirmation email template in VA Notify
---

**Comment by fiorella-io** [comment]
[Created draft copy](https://docs.google.com/document/d/1EYAcOxEPykMe2CMo7a7zU1Alw6HcHd_8CSnkBiqce2s/edit#heading=h.3y4dy4h8gm35). Sent SMEs the first draft requesting feedback.

**Comment by fiorella-io** [comment]
We got SME feedback on the confirmation email. [Here's the latest doc](https://docs.google.com/document/d/1EYAcOxEPykMe2CMo7a7zU1Alw6HcHd_8CSnkBiqce2s/edit). 
 
**Changes:**
- Removed the "What if my claim is denied and I disagree with the decision" section and description.
- Minor content tweaks for the "If you don't hear back from us..." at the end of the email.

**Comment by aliyahblackmore** [comment]
**Just tracking an update here from Slack:**

- @steele-lm confirmed that this confirmation email will start go out once the form is at 100%. 

- I'll turn back to the most recent SME feedback this week and will let @fiorella-io know when it's ready.
