### ISSUE TITLE
Update vets-website Feature Toggle Guide docs to reflect recent changes (Footer Ticket 77938)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#77942]
### Description
Code in vets-website effecting Feature Flags is being updated and will require a couple of changes to platform documentation.

## Tasks

- [x] Identify SME to confirm necessary changes
- [x] Verify with SME the suggested changes below

Once changes are merged to master, step 5 in the platform documentation's Feature Toggles Guide should read:

> **5. Add the feature toggle name to vets-website by updating featureFlagNames.json**
> ```json
> {
>  "showYourFeatureName": "app_name_then_your_feature_name"
> }
> ```

- [x] Update page per SME's instructions 
 
## Acceptance Criteria
- [x] Updated page is deployed

## SME:

- @CBonade 

### Related Footer Ticket
[77938](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/77938)

### Relevant URLs
Platform feature toggles documentation page & section
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-5.Addthefeaturetogglenametovets-websitebyupdatingfeatureFlagNames.js

PR with relevant code changes:
https://github.com/department-of-veterans-affairs/vets-website/pull/27459

**Comment by BSmolensky** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/77942?planning-poker) with Zenhub @laucon

**Comment by jknipes** [comment]
Related Footer Ticket 77938

**Comment by jknipes** [comment]
Page still needs to be updated per the original author

**Comment by jknipes** [comment]
Working to determine SME to review this update

**Comment by CBonade** [comment]
The change as far as the instructions looks good, however one suggestion I have is to include the file path for `featureToggles.json`, as even when I was verifying that these instructions were correct, it took me a few minutes to find it (and there are other feature-toggles folders that do not contain this file).

The file path should read: `src/platform/utilities/feature-toggles/featureFlagNames.json`.

Everything else is correct.

**Comment by taylojill** [comment]
Page updated as requested, see screenshot below. Notification sent to SMEs via [GitHub ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77938).
Page date stamped, checked for launch blocking, ready to publish.
<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2015699d72321892a309a3fd6954a9900aaa3fd/2024-05-15_15-12-17.png" alt="2024-05-15_15-12-17.png" />

**Comment by jknipes** [comment]
Work is complete, moving to _Done_
