### ISSUE TITLE
Burial | Update Info Alert

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77950]
## Issue Description
_The info alert that currently appears on the [form information page](https://www.va.gov/burials-and-memorials/application/530/introduction) needs to be updated to tell users that the form has been updated and they may see new questions. The updated info alert should appear to users completing the new version (v2) of the 530EZ form._

Copy for the alert (to be added by Fiorella once finalized).

<img width="657" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2pIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce5e7e400fd7551f31747014bf3f773cec9e79ff/image.png" alt="image.png" />

---
## Tasks
- [ ] Update info alert copy on the [form information page](https://www.va.gov/burials-and-memorials/application/530/introduction)
- [ ] Ensure it only appears to users who see v2 of the burial form

## Acceptance Criteria
- [ ] v2 info alert appears to users who see v2 of the burial form
- [ ] Fiorella signs off in staging
---

**Comment by steele-lm** [comment]
@DLarson-Oddball and @fiorella-io I drafted the ticket for updating the info alert, but feel free to refine if needed.

**Comment by steele-lm** [comment]
@aliyahblackmore Tagging you. 👍

**Comment by aliyahblackmore** [comment]
Thanks @steele-lm!

As we chatted, the alert will appear on the form intro page. And it'll appear for any authenticated users returning to their saved and in-progress forms after the 100% launch. 

Katherine and I chatted bout this a few weeks ago and to avoid two alerts on this page, we can place the content in the "saved in-progress" alert box.  [Here's an example of the placement on a different form](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=1675-115444&mode=design&t=apZ3q1k9eIHZipZ7-4).

I'll share the content for this form here and in Figma.
