### ISSUE TITLE
Zenhub Access Internal Process Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#77951]
## Description 
The Platform Support Team is taking over the Zenhub access process. We want to take the process documented [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2977366027/Zenhub+Onboarding+Offboarding+Auditing) and create a step by step process that works for our team.
---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add the process for adding Zenhub Access [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3010396198/Granting+Access+to+Zenhub)
- [x] Make sure to note that we are only owning access and not IT for Zenhub
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by AnthonyWFlowers** [comment]
@alyssagallion take a look I took some literary liberties with the wording- items in parenthesis may need confirming; including the names of the headings. Thank you.

**Comment by EWashb** [comment]
I have no issues with the documentation you've provided here.

**Comment by alyssagallion** [comment]
Internal documentation complete. Closing!
