### ISSUE TITLE
Burial | Update Info Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77955]
## Issue Description
_A widget that displays information specific to v2 of the burial 530EZ [form information page](https://www.va.gov/burials-and-memorials/application/530/introduction) needs to be created for users who see v2 of the form because the instructions for v2 of the form are different than those for v1. Users completing v1 of the form should NOT see the widget. Once v1 of the form is retired, the widget information will be permanently added to the information page._

---
## Tasks
- [x] Aliyah Blackmore to provide widget copy
- [ ] Create widget to display conditional copy on form information page
- [ ] Ensure that v1 form users do not see the widget
- [ ] Ensure that v2 form users see the widget

## Acceptance Criteria
- [ ] v1 form users do not see the additional copy
- [ ] v2 form users see see the additional copy
- [ ] Aliyah signs off in staging
---

**Comment by steele-lm** [comment]
@DLarson-Oddball and @fiorella-io I created the ticket to create a second version of the burial form's information page.

**Comment by steele-lm** [comment]
@aliyahblackmore Tagging you. 👍

**Comment by aliyahblackmore** [comment]
Thanks Laura! We're not creating an entirely new version of the page, but we're placing certain pieces of content inside of a widget so that certain users are seeing that content during the incremental launch. 

No need to add a screen capture of the form intro page here - I'll be providing the content for the widget. 

And as mentioned, I'll connect Dakota with engineers on the 1010 health apps team! 

Thanks for sharing this ticket.

**Comment by aprocik1** [comment]
@DLarson-Oddball, I'm filling in for Aliyah while they're out. Here's [the SharePoint document](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/EW23mGfUTihLj-qJkiDOG5gBKVBjNgP9CecV8quM_KDc-Q?e=z1XLpc) with the content needed for the react widget(s) on this page. Let me know if you have any trouble access it. Thanks for collaboration on this!

**Comment by aliyahblackmore** [comment]
@DLarson-Oddball I'm cross posting the notes from Slack here:

- As we chatted, [here is the updated SharePoint document](https://dvagov-my.sharepoint.com/:w:/r/personal/megan_zehnder_va_gov/Documents/Documents/React%20widget%20content%20for%20%E2%80%9CHow%20to%20apply%20for%20burial%20allowance_with%20copy%20edits.docx?d=w6798b76d4ed44b288fea899220ce1b98&csf=1&web=1&e=wg4R2d) with the two versions of the content for the incremental launch (users who can use the form vs. users who can't use the form) including the in between pieces of content (the content that comes between any sections that were updated).
- For the "burial-apps-status" react widget that is currently in Drupal for the content in the section "How do I apply?", you're going to confirm if we can take that content out of that separate react widget and just include a direct link to the form intro page [https://www.va.gov/burials-and-memorials/application/530/introduction]. If we need to leave that widget in for some reason, we can talk more about what needs to happen. It will likely mean that we need to adjust the content in that "burial-apps-status" widget and we can take that content out of the other widget (burials-v2-how-do-i-apply-widget).

We'll find another time to do the toggle on/off review once the content updates are ready. Our copy editor or managing editor will join that call.

Thanks for your continued collaboration on this.

**Comment by aliyahblackmore** [comment]
**Cross posting some updates here:**

- If the incremental launch date changes (currently April 5, 2024), engineer will update the day. 
- Dakota will get the PR merged (content that they put in the code)
- Once the PR is merged, we can add the code to our react widget component in Drupal
- A copy editor will reach out a day or two before the incremental launch to do the toggle on/off review


FYSA @DLarson-Oddball @steele-lm
