### ISSUE TITLE
Burial | Remove Info Alert Copy

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77959]
## Issue Description
_The info alert that currently appears on the [form information page](https://www.va.gov/burials-and-memorials/application/530/introduction) was updated in #77950 to tell users that the form has been updated and they may see new questions. Now that v2 of the form is fully launched, and no v1 users remain, the copy added to the info alert needs to be removed to avoid user confusion._

## Designs
- [Desktop](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=2333%3A42586&mode=design&t=VF5Jg5yzdR0YHzzM-1)
- [Mobile](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=2333%3A42648&mode=design&t=VF5Jg5yzdR0YHzzM-1)

<img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/9cc30f82-b47e-421e-9dd5-ea013eabc239" width="70%">

---
## Tasks
- [x] Update info alert copy on the [form information page](https://www.va.gov/burials-and-memorials/application/530/introduction)

## Acceptance Criteria
- [ ] Info alert appears with correct copy
- [ ] Fiorella signs off in staging
---
