### ISSUE TITLE
Burial | Remove v2 Info Page

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#77960]
## Issue Description
_A second version of the burial 530EZ [form information page](https://www.va.gov/burials-and-memorials/application/530/introduction) was created in #77955 because the instructions for v2 of the form were different than those for v1. Users completing v1 of the form saw v1 version of the information page, while v2 users saw v2 of the info page. Now that the burial form is fully launched, v1 of the info page needs to be retired, so users only see v2 of the page._

---
## Tasks
- [ ] Remove v1 of the information page, so all users see v2 of the info page

## Acceptance Criteria
- [ ] All burial form users see v2 of the info page
- [ ] Fiorella signs off in staging
---
