### ISSUE TITLE
Update to static pages for burial allowance form re-launch

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#77971]
## Issue description
Ahead of the MVP re-launch of the new 530 EZ online form questions, we need to make updates to the How to apply for a VA burial allowance page to align with the new form questions. 
[
Here's a link to their launch plan](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707410059042/66a7863edcd579a5bc8b4bd720f685a5d0724a49?wid=58-1707410148285&sender=u99393afd3329e0f2e2e87196)
 
For MVP we're only making updates to [the static page](https://www.va.gov/burials-memorials/veterans-burial-allowance/) that relate to missing information from the form or the changes that they made to the form.

**We'll make these updates:**
- In the section  "Is there a time limit for filing?" we'll update that section with information about the time limit for unclaimed remains.
- In the section "What documents do I need to send with my application" we'll update the content to align with the updated information on the [form intro page](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=165-32381&mode=design&t=0qVKrP1j0bWAPsNx-4).
- And we'll also need an info alert, similar to the [pension static page](https://www.va.gov/pension/how-to-apply/), that let's users know that there are updates on the form and new questions. 

And we also need to add the online form option the [About VA forms](https://www.va.gov/find-forms/about-form-21p-530ez/) page. 

Since this form is launching incrementally, we'll need to have the the product team add two versions of the content in a react widget. [This is their ticket for these updates.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77955)

---
## Tasks

- [x] Draft content
- [x] Share with SMEs (Aliyah)
- [x] Share two versions of content with engineer for incremental launch (A)
- [x] Review widget content with Engineer before PR merge
- [x] Add widget to page (Aliyah)
- [x] Review with engineer, copy edit and publish for incremental launch (Megan)
- [x] Ahead of 100% launch, add content (version 2) to page and delete widget.
- [x] Copy edit and publish (Megan) 
- [x] Share with SMEs

**Comment by aliyahblackmore** [comment]
**Update here:**

I shared the static page updates with their SMEs (via Teams) a few minutes ago. 
[Here's a link to the SharePoint document](https://dvagov-my.sharepoint.com/:w:/r/personal/aliyah_blackmore_va_gov/_layouts/15/Doc.aspx?sourcedoc=%7BAFF2EF8C-EFEB-4FA7-A44F-798C2B8C957A%7D&file=How%20to%20apply%20for%20a%20burial%20allowance%20static%20page%20updates.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=ALIYAH.BLACKMORE%40VA.GOV&ct=1710536832052&wdOrigin=OFFICECOM-WEB.START.REC&cid=e76c4162-287a-45ef-a840-48770a80f61d&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=e238729b-85e0-4dd4-9623-a24d9c4f556a)


Once SMEs confirm we the updates, I'll share the content with their engineer so that they can create a widget for the incremental launch.

**Comment by aliyahblackmore** [comment]
* SMEs reviewed the content for the How to apply page and I’m creating a SharePoint document with the two versions of the content to share with the engineers this week (insert link when ready).
* While I'm OOO - A will have Megan review the widget copy and then they can share the SharePoint document with their team in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77955) and tag Dakota.
* A can add the widgets to the page, if it’s ready before next Monday. And A and Megan can have the engineer toggle it on to do a review.

**Comment by aliyahblackmore** [comment]
@aprocik1 thanks for the coverage while I'm OOO.

As we chatted, SMEs reviewed these updates to the [How to apply for a burial allowance page ](https://www.va.gov/burials-memorials/veterans-burial-allowance/)ahead of the incremental launch.

[Here's the SharePoint document ](https://dvagov-my.sharepoint.com/:w:/g/personal/aliyah_blackmore_va_gov/ERMoLVj2IPpNis507dHT0u8Bigx-3b7jdR1fm2T2cf-lhw?e=vgB9tZ)

And here's an exported Word document version, in case there are any issues with SharePoint. 
[React widget content for “How to apply for burial allowance_word export_3.19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14661421/React.widget.content.for.How.to.apply.for.burial.allowance_word.export_3.19.docx)

- After you have Megan review this content, you can share the document with the engineer on the 530 product team.

- In terms of how the widget should work, as I mentioned, I believe the engineer has to decide whether the page will require multiple widgets or one widget. Can you confirm this with him?

- If the engineer decides to use one widget and want to place all of the content there, you'll just need to copy the current page content between "Am I eligible..." and "How do I apply?" For the version that will be visible for users who can see/use the updated form, you can just insert the new content and leave the other content as is.

**Comment by aprocik1** [comment]
@megzehn, can you copyedit [this SharePoint document](https://dvagov-my.sharepoint.com/:w:/r/personal/aliyah_blackmore_va_gov/Documents/React%20widget%20content%20for%20%E2%80%9CHow%20to%20apply%20for%20burial%20allowance.docx?d=w582d281320f64dfa8ace74edd1d3d2ef&csf=1&web=1&e=k892Hd)?

The first 3.5 pages under the header "Content for the users who can see the online form" will go into react widgets on the [How to apply for a Veterans burial allowance](https://www.va.gov/burials-memorials/veterans-burial-allowance/) page. The remaining pages under the header "Content for the users who can’t see the online form" should be the same content that's already on the published page.

The engineer asked for this SharePoint document by the end of this week. Please let me know if you don't have time to copyedit it by then. Thanks!

**Comment by megzehn** [comment]
Thanks @aprocik1 and Aliyah! 

I made [some light copy edits in this Sharepoint doc](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/EW23mGfUTihLj-qJkiDOG5gBnLjHBLNW2T_w2wOv0xR1xQ).

Let me know if there are any problems accessing the doc or questions about the tweaks.

**Comment by aprocik1** [comment]
Thanks, @megzehn! I accepted your suggested edits and shared this document with the engineer to build the react widget(s).

**Comment by aliyahblackmore** [comment]
Thank you both! @aprocik1 @megzehn 

Tracking here that I followed up with their engineer about when they'll have the code ready. Once we have the code in Drupal, engineer will toggle on so that Megan can do a review.

**Comment by aliyahblackmore** [comment]
**Update here:**

- Engineer [shared a link to the PR for this widget. ](https://github.com/department-of-veterans-affairs/vets-website/pull/28808/files#diff-d2019dfabc51f5421595f433360350e107db695a198de20f15441fcd5da06431)
- We met today to review and widget and he's going to make some adjustments to the widget copy to reflect the pieces of content in between the areas we updated.
- Engineer will follow up about the current widget on the page for the form link.

**Comment by aliyahblackmore** [comment]
Updates here:
- Engineer will make a few more style updates to react widget content and I'll take another quick look. I have some time tomorrow, in the early afternoon or on Monday.
- Our copy editor will do the toggle on/off review once the widget code is ready and in Drupal. 
- Engineer mentioned that he'll push the content changes production (changes won't be visible on [VA.gov](http://va.gov/) until we published the page with the widget code).
- Engineer confirmed that we CAN remove the "burial-apps-status" widget that's currently on the page and we can use the direct link to the [form intro page](https://www.va.gov/burials-and-memorials/application/530/introduction) for the action link "Apply for burial benefits."
- Incremental launch date is still TBD.
    
  
 Once I add the widget to the page, I'll need to make "What if I have more questions" a separate Page Specific Q&A group.

Last communication with team was on 3/28.

**Comment by aliyahblackmore** [comment]
**Updates here:** 

- If the incremental launch date changes (currently April 5, 2024), engineer will update the day.
- Engineer will get the PR merged (content that they put in the code)
- Once the PR is merged, we can add the code to our react widget component in Drupal
- A copy editor will reach out a day or two before the incremental launch to do the toggle on/off review

Last communication with engineer was 3/29.

**Comment by aliyahblackmore** [comment]
Hi @megzehn - welcome back!

A and I did one review with the engineer of both versions of the content and noted some updates to the widget version. And then I did a second review with their engineer after he made the changes.

The engineer shared the widget code with me and I added it to Drupal today. I just noted one last change about the spacing between the "Note" and header in the featured content box. Outside of that, everything else look good.

Do you have some time this week to do that toggle on/off review with him so that you can look at the content that users who can use the online form will see? 

[Here's the content doc for reference](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/EW23mGfUTihLj-qJkiDOG5gBnLjHBLNW2T_w2wOv0xR1xQ)

Let me know and I can connect you with their engineer!

**Comment by aliyahblackmore** [comment]
**Updates here:** 

- Megan and I met with Dakota last week and requested one last style update to the featured content box. 
- Dakota made the update. 
- Canary testing will start on April 15. Megan will publish the page (with the react widget) then.

**Comment by aliyahblackmore** [comment]
**Updates here:** 
- The react widget is already in Drupal and ready for @megzehn
- @megzehn will coordinate publishing with the product team on Monday 

Last communication with team was on 4/12.

**Comment by aliyahblackmore** [comment]
Update here: 

- SMEs need to approve updates to the "What documents do I need to submit?" section. Laura Steele confirmed on 4/29 that these updates are okay to go ut post-100%. If this plan changes and updates need to happen this week, Dakota will need to add these updates to the react widget.

[This is the SharePoint document I shared with SMEs](https://dvagov-my.sharepoint.com/:w:/g/personal/aliyah_blackmore_va_gov/EcMcY7v2HuFOpLNOFjH8AnkB-OELP16l2ZlhikH-J9TDAA?e=HWABRd)
[This is the SharePoint document from Megan/A with the react widget content for users who CAN use the V2 online form. ](https://dvagov-my.sharepoint.com/:w:/r/personal/megan_zehnder_va_gov/Documents/Documents/[%E2%80%A6]d=w6798b76d4ed44b288fea899220ce1b98&csf=1&web=1&e=PXgCCl)

If SMES have any feedback on the updated section, track updates ^ here and share with Dakota. And coordinate publishing timing with the form updates, because the form intro page now links out to the static page with more details about the types of supporting documents. Also, be aware that the react widget content is already in production - coordinate deployment timing with engineer because update will show once the deployment happens.

**Comment by aliyahblackmore** [comment]
**Update:** 

We received new information from SMEs today about death certificates and service-connected deaths. We may need additional adjustments to this page before 100%.

**Comment by megzehn** [comment]
Yay thank you @aliyahblackmore! 

Confirming I reviewed your changes and published them once the team confirmed they were at 100%

I also published the update to the form detail page!
