### ISSUE TITLE
API architecture diagram(s) for CST

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#77978]
## Description
We need to create a set of diagrams that makes it clear what the mapping between us and the external services we use is. We will probably need a separate diagram for all four of our applications as they all rely on different data sources currently.

## Notes
Our applications:
- Claim Status Tool
- Benefits Letters
- Rated Disabilities
- View Payment History

## Tasks
- [x] Create an Architecture Diagram for Claim Status Tool
- [x] Create an Architecture Diagram for Benefits Letters
- [x] Create an Architecture Diagram for Rated Disabilities
- [x] Create an Architecture Diagram for View Payment History

## Acceptance Criteria
- [x] Architecture Diagrams have been created for each application
