### ISSUE TITLE
Endpoints used throughout services documentation

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#77976]
## Description
We need to create documentation that lists all of the endpoints used by our applications

## Notes
Applications we need to create documentation for:
* Claim Status Tool
* Benefits Letters
* Rated Disabilities
* View Payment History

## Tasks
- [x] Create a document listing all of the endpoints used by the Claim Status Tool
- [x] Create a document listing all of the endpoints used by the Benefits Letters application
- [x] Create a document listing all of the endpoints used by the Rated Disabilities application
- [x] Create a document listing all of the endpoints used by the View Payment History application

## Acceptance Criteria
- [x] Documents listing all endpoints used have been created for each application
