### ISSUE TITLE
Copy of Research: Create List of Pages Containing Links to Google Drive Docs Pt. 1 of 2

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#77988]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Links on Platform Website need to be viewable by all users. 
Therefore, we cannot include links to Google Drive on the Platform Website.
We need to determine how many pages on Platform Website contain links to Google Drive, Docs, Sheets, and Slides. This first step will inform how we approach removing those links.

---
## Tasks
 - Identify all pages on Platform Website containing links to Google Drive docs, sheets, and slides.
- [ ] **Spaces**: Getting Started, Developer Docs, Research & Design
- [ ] Create [Google Sheet](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0) (internal) with URLs to all relevant pages 

## Acceptance Criteria
- [ ] Content Team will have listed all relevant pages on the [Google Sheet](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)

### Google Sheet w/ URLs:
[Here](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/77988?planning-poker) with Zenhub @laucon

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/77988?planning-poker) with Zenhub @BSmolensky

**Comment by jknipes** [comment]
@BSmolensky and @laucon please add your estimates to this issue

**Comment by jknipes** [comment]
**Combined work into single ticket 77759.**
