### ISSUE TITLE
IA Tracker: Updates to Online Application CH 31

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#77996]
### Description
The team is updating the online application for CH 31 so it is up to date with the PDF version

### Links

- Intake Ticket #75169 

### Team

- Team Name: Benefits - Non-Disability Experience
- Research/Design: Julie Pedtke, Fiorella Geedi
- Product Manager: Laura Steele
- Slack (_optional_): benefits-non-disability

### Timeline

Midpoint review has been scheduled for 3/12

### Work needed

- IA spec: Needed
- Feedback for product team: Needed

```[tasklist]
### IA deliverables
- [x] [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/ch-31-form-updates.md)
- [x] Feedback
```

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by jennymayoco** [comment]
Additional acceptance criteria
- [ ] listed entry points have been updated

**Comment by jennymayoco** [comment]
Question for the team: will the title tag be updated automatically so that it matches the H1?

**Comment by jennymayoco** [comment]
Entry point has been added to left nav so closing this ticket
