### ISSUE TITLE
Build life insurance landing page for FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#77993]
## Issue description

Mikki has stubbed out new pages required for the family member hub and will add links to this ticket:
*Note: the formatting and elements used in these are not necessarily final, they were simply a way to experiment with the content that we needed to represent.  

- Life insurance: http://preview-prod.vfs.va.gov/preview?nodeId=65664 

Per Mikki: The required pages to be linked to from each landing page is documented in the [family member hub mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1704984305251) - on the far right under "Final working structure"

---
## Tasks
- [x] Compare links on the stub page in Drupal to the updated [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md) and update Drupal to match IA design as needed (Derek)
- [x] Adjust all sections to use the "List of link teasers" style with linked H3 headers followed by blurbs (Derek)
- [x] Draft intro for the page and blurbs for each link on the page (Derek)
- [x] Review draft landing page (Laura)
- [x] Decide on H1 (Derek, Laura, Kristin)
- [x] Copyedit and prepub checklist (Sara)
- [ ] Send to SMEs (Danielle)
- [x] Publish **(coordinated effort)**

## Acceptance Criteria
- [x] The landing page is live on VA.gov

**Comment by laurwill** [comment]
@d-beyer please go ahead and build out this life insurance subhub landing page as well. 

@kristinoletmuskat for the CST link here, I'm trying to confirm with that team[ in this ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62248) whether decision reviews and appeals for life insurance claims will appear in CST. They recently confirmed that initial claims/applications for life insurance do not appear. Depending on the answer, we may want to remove the CST from the "Manage" section in this hub.

**Comment by d-beyer** [comment]
@laurwill -- I've finished drafting this page. It's ready for your review.

**Comment by laurwill** [comment]
@kristinoletmuskat removed claim status tool here too — life insurance claims don't show up there, apparently.

**Comment by kristinoletmuskat** [comment]
@laurwill great, updated ia spec and mural

**Comment by d-beyer** [comment]
@saratorres2 I've added the related links and they're ready for copyedit. Screenshot attached.
![Life-insurance-FMB-related-link-20240614](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141662117/29118409-affd-45f2-9ae6-a23c74a13e91)

**Comment by saratorres2** [comment]
@laurwill Copy edits of new related links section complete.

**Comment by kristinoletmuskat** [comment]
Confirmed page is live and working, closing this ticket.
