### ISSUE TITLE
GA4 Custom Event Audit (Financial Status Report) (due by April 5, 2024)

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#77997]
## Issue Description
In preparation for the migration to Google Analytics 4 (GA4), the Analytics Team is asking that all VFS Teams that leverage and track custom events in their products complete this form, (along with its attached spreadsheet), **no later than Friday, April 5, 2024.** Detailed instructions on what information to include for each custom event can be found within[ this form.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D)

---
## Tasks
- [ ] Complete tasks listed on form 
- [ ] Complete spreadsheet (attached to form)  

## Acceptance Criteria
- [ ] Form submitted to Analytics team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
Excel file with recordEvent paths https://drive.google.com/file/d/16HaUnsQ0pbDwFHQpDFlwhC92FlY0I7v_/view

**Comment by amponce** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79896
