### ISSUE TITLE
Content model: VAMC "Billing and insurance" 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7801]
## Problem Statement
How might we change the structure of [Billing and insurance page content](https://www.va.gov/pittsburgh-health-care/billing-insurance/) so that
- some content can be reusable
- national content cannot be edited locally
- the risk of introducing errors is reduced
- the editorial experience is enhanced and efficient

## OKR
Decrease the amount of national content which is locally editable 

## Acceptance Criteria
- [ ] National content areas are no longer editable at the system or facility level

## Definition of done

- [ ] Content structure changes
- [ ] Front end mapped to new data structure
- [ ] Pages render as expected 
- [ ] Editorial experience review with CMS
- [ ] Content model review with CMS
- [ ] Feedback session with VAMC upgrade team 
- [ ] Migration plan
- [ ] Testing plan

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc

**Comment by mmiddaugh** [comment]
Replaced by [Content model for facility nonclinical services to support Top Tasks #6341 (CMS epic)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6341)
