### ISSUE TITLE
Dive deeper into technical considerations for triggers

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#78028]
## Description of UX Tasks
Knowing that BDPR is already using triggers to notify for bank account changes and beneficiary changes, and that Auth Exp team manages notifications that are triggered by direct deposit change, the next low hanging fruit seems to be notifying based on a sign in that is different in IP or device fingerprint from what the user regularly uses.

## Tasks
- [x] sync with our team engineers to discuss further
- [ ] create a diagram of how this all might look

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Add finalized research to Github
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
moved to jira, closing
