### ISSUE TITLE
[Testing] HLR: User Acceptance Testing for Higher Level Review

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7802]
## User Story
After staging review we will be ready for UAT.

We will start with 1-2 initial users (Luke will break off separate stories for each user).

Edit: Since Luke will be doing all of the UAT for HLR, we will just use this single story for UAT testing.  Each session will be a long comment at the bottom.

## Tasks
- [x] Final test users and test script defined
- [x] Schedule UAT with Perigian

## Acceptance Criteria:
- [x] HLR UAT plan and convo guide
- [x] First two scheduled

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by chrvalla** [comment]
Internal UAT testing. Will continue to BDD claims that are successfully submitted. Then, 8 real users will be invited to go through BDD flow (and normal claim flow).

**Comment by chrvalla** [comment]
Internal UAT testing. Will continue to BDD claims that are successfully submitted. Then, 10 real users will be invited to go through BDD flow (and normal claim flow).

**Comment by luke-gcio** [comment]
UAT Notes 11/4 10:00 AM MT:

No show :(

**Comment by luke-gcio** [comment]
Reread the acceptance criteria - we did the first two already and did all the other work, taking full credit for this tory.  Other story for remaining UAT sessions.
