### ISSUE TITLE
[UX] 10-10EZ - Reg Only: Journey maps for sharing with HEC stakeholders

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#78033]
## Issue Description
After finishing all three registration stakeholder workshop sessions, we need to refine the journey maps and learnings from SMEs into a refined current state version and future state version for service-connected and mental health scenarios.

These will be shared in a follow-up meeting with HEC stakeholders along with early wireframes and will be sent in a shareable format. 

---
## Tasks
- [x] Finalize current and future state versions for each Registration Reason listed below
  - [x] Service Connected Only
  - [x] Mental Health Care 
- [x] Share with Kristen and other UXers in Monday design sync

## Acceptance Criteria
- [x] Current and future state journey maps are approved and ready to be shared with HEC stakeholders
---
