### ISSUE TITLE
Create Oracle Health appointment slot search feature flag

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#78057]
## Issue Description
Create a VA online scheduling (vaos) backend feature flag for toggling support for searching for appointment slots at Oracle Health sites
[Feature flag documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

---
## Tasks
- [ ] Create backend feature flag

## Acceptance Criteria
- [ ] Feature flag has been deployed to Staging environment
- [ ] Feature flag is visible in Flipper on Staging (https://staging-api.va.gov/flipper/features)

**Comment by drewconnelly** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15980
