### ISSUE TITLE
Create GA4 View in BigQuery for 'BQ - Standard Forms Engagement' (VA.gov Forms KPIs)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78058]
### Description:
We need to create a new view in BigQuery that combines UA and GA4 data. This will include mapping the attributes of the current UA data model to those within the new GA4 data model. 

For this card, the focus will be on the _**BQ - Standard Forms Engagement**_ dataset, which is the primary dataset behind the VA.gov Forms KPIs dashboard in Domo.

- **Domo Dashboard:** [VA.gov Forms KPIs]( https://va-gov.domo.com/page/447193050)
- **Dataset:** [BQ - Standard Forms Engagement](https://va-gov.domo.com/datasources/f256e93e-e0ff-4d69-bd69-404f98bc335b/details/overview)

---

### Tasks:
- [x] Leverage findings from [GA4 View pilot ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/77173).
- [x] Review the list of dimensions defined in GA4 and map to the UA equivalent
- [x] Create related views in BigQuery, that incorporate GA4 data.

### Acceptance Criteria:
- [x] New GA4 views will be created in BigQuery
- [x] New GA4 views, will be tagged or identified through some means, (through use of BQ labels, a created list, or some other means)

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 - this ticket will be carried over to next sprint, due to work done on the pilot view. https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/77173

**Comment by johnny-jesensky-adhoc** [comment]
Update -- after talking with @dorseypa1, this one is partially blocked until we get further along in some of the set-up within our new GA4 properties. We will be moving this to the backlog, and likely revisit after the following tickets are completed.

- [Stub out the GA4 versions of the base session level query needed for the BigQuery VIEWs and Domo queries](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/79408)
- [Stub out the GA4 versions of the base hit level query needed for the BigQuery VIEWs and Domo queries](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/79416)

FYI @jwoodman5, @davidconlon, @jestutt

**Comment by johnny-jesensky-adhoc** [comment]
We had a slight mix up on what we pulled into the current sprint, so we are removing this ticket into the current sprint, and swapping in [this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78123).

FYI @dorseypa1

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 -- finalized the following GA4-specific Views -- and related datasets are available in Domo.

> _Standard Forms Engagement, Standard Forms Funnel, Standard Forms Landing Page and Standard Forms User Completion have all been created._

BigQuery GA4 Views Created as part of this ticket.
- [vw_GA4_forms_engagement_last_week
](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&supportedpurview=project&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_forms_engagement_last_week)
- [vw_GA4_forms_funnels_last_week
](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&supportedpurview=project&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_forms_funnels_last_week)
- [vw_GA4_forms_landing_page_last_week
](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&supportedpurview=project&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_forms_landing_page_last_week)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/147662408/7e52897b-ec2e-42e4-bc38-53e91e5545c5)

Going to move this to _**Done**_.
