### ISSUE TITLE
Implement audit trail for repository settings changes

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#78053]
_Written by ChatGPT. Edited by @rmtolmach_ 

Currently, there is no audit trail for changes made to the repository's settings through GitHub's UI, specifically the branch protection rule settings. This lack of visibility poses risks, as modifications to settings can inadvertently break functionality or alter the repository's behavior without an easy way to identify or revert those changes. **The goal of this ticket is twofold**: to explore potential solutions to this problem and to implement a chosen solution to ensure an audit trail for repository settings changes.

### Problem Statement

When settings in the GitHub repository are changed directly through the UI, there is no automatic update or log of these changes. This situation has led to our [.github/settings.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/settings.yml) becoming outdated, as it does not reflect manual changes made in the UI. Without a reliable audit trail or a source of truth for these settings, troubleshooting and maintaining repository integrity becomes challenging.

### Potential Solutions

1. **Current `.github/settings.yml` Approach**: We have a settings file (`settings.yml`) that can programmatically change the repository's settings. However, changes made through the GitHub UI do not update this file, leading to discrepancies. This method currently does not serve as a reliable source of truth and requires reconsideration.

2. **Screenshot Documentation**: As a workaround for settings.yml being out of date, I (rebecca) saved a screenshot [in Confluence](https://vfs.atlassian.net/wiki/spaces/BCP/pages/2885582876/Vets-api+branch+settings) if we do need to compare current changes with a snapshot of past settings. This approach provides a visual history but lacks automation, scalability, and will also become outdated.

3. **GitHub Action with Workflow Trigger**: The most promising solution involves leveraging GitHub Actions triggered by `branch_protection_rule` events. This method would automate the notification process, informing relevant stakeholders (via Slack or another communication platform) of any changes to repository settings. The automation would enhance transparency and create a dynamic audit trail without manual intervention. [Link to those docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#branch_protection_rule).

### Tasks

1. **Discovery Phase**:

- [ ] Research the feasibility and potential limitations of using GitHub Actions triggered by `branch_protection_rule` events for creating an audit trail.
- [ ] Evaluate the pros and cons of the screenshot documentation method as a supplementary or interim solution.
- [ ] Assess the necessity and utility of the current `.github/settings.yml` file in light of potential automated solutions.

2. **Implementation Phase** (Contingent on Discovery Outcomes):

- [ ]  If the GitHub Action approach is viable:
    - [ ]  Develop a GitHub Action workflow that triggers on `branch_protection_rule` events.
    - [ ]   Configure the workflow to send notifications to a designated Slack channel or other communication platforms, detailing the changes made.
    - [ ]  Test the workflow thoroughly to ensure reliability and accuracy in reporting changes.
- [ ]  If decided, deprecate the use of `.github/settings.yml` in favor of the new automated solution, ensuring all stakeholders are informed of this change.

3. **Review and Documentation**:
- [ ]  Update [BE support documentation](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities) to reflect the new audit trail process, including any required steps for monitoring and reverting changes.
- [ ] Review the implementation with the CoP.

### Acceptance Criteria

- [ ] A reliable audit trail exists for tracking changes to the repository's settings.
- [ ] The chosen solution is as automated as possible, reducing the need for manual intervention and documentation.
- [ ] The CoP can easily access and review the history of settings changes.
- [ ] The repository's integrity and functionality are safeguarded against inadvertent changes.

**Comment by rmtolmach** [comment]
A command Eric uses to track status check changes:
```
curl -H "Authorization: token $GHCR_PAT" \
https://api.github.com/repos/department-of-veterans-affairs/vets-api/branches/master/protection/required_status_checks
```
