### ISSUE TITLE
DE/Research | Enhanced Military Info | Readout for VEO

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#78052]
## Background 
We ran research on MOS we need to prepare a deck and provide a readout to our VBA stakeholders regarding what we will be able to proceed forward with and what we won't be able to add into the profile

We can likely move forward with adding: 
- periodOfServiceTypeText (active/reserves/etc.)
- narrativeReasonForSeparationText
- characterOfDischargeText

We should likely NOT proceed with: 
- Units - We already advised VBA on 12/6/2023 that the data quality for units wasn't good enough to proceed
- militaryOccupations - based on usability explain why this isn't great 
- deployment locations start and end dates(no deployment data prior to 2001, )
     -  ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/8a24823d-d905-4cc6-a11f-ce69f6f5935d)
- training courses (not yet in the database i think) 
- Military awards and decorations (also not yet in the database) 

## Tasks 
- [x] draft a deck 
- [x] discuss as a team
- [ ] prep for presenting 

## Acceptance criteria 
- [ ] we have a deck and are ready to present to our VBA stakeholders about what we think we can move forward with in the profile

**Comment by mtcA6** [comment]
@pamela-drouin take a peek here and let me know your thoughts. I'm hoping we could present this sometime next week (early or late) depending on how long you think it'll take to pull things together

**Comment by pamela-drouin** [comment]
@mtcA6 @clantosswett @andaleliz @tpharrison @adamwhitlock1 @ACParker89 

Hi team! I have a [draft readout presentation](https://docs.google.com/presentation/d/1OBXqeNfeaI6-7a0BsxqB2y9qmJsSNpBx9l4Kud21EN4/edit?usp=sharing) ready for review. Anyone have bandwidth/availability to read through it? I am mainly looking for whether there are gaps in what I've included for the audience (VEO). Open to other suggestions as well. 

I'm happy to collect feedback here, or as comments in the deck. Thank you!

**Comment by andaleliz** [comment]
@pamela-drouin I started taking a look and realized I'm not sure if your primary goal is to have a deck to walk through in a presentation, or if you expect most of the content will be consumed async.  Generally, I feel like the slides are a bit too dense for a presentation, but if it the intention is to have people read them on their own, then that's probably ok.

If you can share w/ me your goals and/or how you plan to present this, I think I'll be able to provide more useful feedback. Thanks!

**Comment by pamela-drouin** [comment]
@andaleliz I was honestly hoping for the deck to serve both purposes, which I know is a tall order. I'd like the presentation to stand alone so it can be useful beyond the presentation itself. I can work on moving a bit more of the content into the speaker notes.

**Comment by clantosswett** [comment]
@pamela-drouin thanks for pulling this deck together. I made some comments on some of the slides but my major piece of feedback is that the findings need to be articulated clearer and be highlighted better. Right now it feels like we use data as findings rather than summarizing findings from the data. I'd be happy to chat through what some higher level findings are based on the research questions that we can then share data around to illustrate.

**Comment by pamela-drouin** [comment]
@clantosswett I appreciate your feedback so much! You summed up the issue I've been having in translating the findings into deck form, and sparked some inspiration. I'm going to work on the deck this morning and post an update here 🤓

**Comment by pamela-drouin** [comment]
@mtcA6 @clantosswett @ACParker89 @andaleliz -- I'm back with a [revised deck](https://docs.google.com/presentation/d/1OBXqeNfeaI6-7a0BsxqB2y9qmJsSNpBx9l4Kud21EN4/edit#)! I made significant structural revisions to the presentation. I emphasized the findings and made it more clear the where the evidence supports those findings. I also added emojis to the evidence tables for increased understandability.

I will continue to flesh out speaker notes while I await additional feedback. Thanks so much for everyone's input!

**Comment by andaleliz** [comment]
@pamela-drouin wow, what a tremendous amount of hard work you've put into all of this. THANK YOU! It's clear you've spent a lot of time thinking about how to most clearly present this very data-dense/complex research to our stakeholders.

I left comments in the deck changes to consider, but as always, take it or leave it! I trust your speaker notes and presentation skills and know if you didn't change a thing, VEO will walk away with a clear understanding of the research and our recommendations.

A couple comments I didn't make in the deck but want to call out here:
- love the emojis. That is a solid addition, and you might even consider making them bigger.
- I saw the Slack back and forth about the tables [in this thread](https://dsva.slack.com/archives/C909ZG2BB/p1711481747595859). I don't have strong feelings either way, but I agree that if you leave them where they are, you shouldn't spend much time on them. It'll be nice for people to know they are there, but I think if you spend a lot of time with them on screen, people will be trying to read whats on the slide vs listening to what you're saying. The non-table slides will do a good job of communicating the main point, esp. when supplemented by your spoken words.

**Comment by clantosswett** [comment]
Did my full review of the deck and left comments but really appreciate the updated structure and think it will help people digest the information during the presentation and beyond. Thank you for all your work on this! The scope of this research was large and I think it's displayed in a way that allows someone to get high level understanding and/or dive deep into the data. I'm looking forward to seeing it presented tomorrow and if you need anything else before then, don't hesitate to reach out.

**Comment by pamela-drouin** [comment]
@clantosswett thank you so much!! Your feedback was crucial in helping improve the structure. I really appreciate your time and keen eye!

**Comment by pamela-drouin** [comment]
This ticket is finally complete! I added a link to the research readout presentation to the research findings. The research readout presentation is in the same folder as the rest of the research files in Github.
