### ISSUE TITLE
Copy of Design | CH36 Form Updates

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78063]
## Issue Description
- Changes made and new fields added to paper form (see list). Online form only contains critical fields.
  * Moved instructions from the back of the form to the front.
  * Q10A: Added additional military departments. (space force, NOAA, USPHS)
  * Q8: If applicant is attending school or not. (Need to determine if they are attending a vet-success school, if so the application is transferred to a contractor.)
  * Q11: Character of discharge.
  * Q16: Condensed to determine if child or spouse. 
  * Q20: Are they currently attending school.
- Form name changes handled here #62284 
- [Additional Notes ](https://docs.google.com/document/d/1tZejPPUbRaDt162ZETL6_VJ2Ydi0zruV6zpPYlyHWgU/edit?usp=sharing)on form changes and requested enhancements.
---
## Tasks
- [x] Compare the online form against the updated paper form and determine if any existing online form fields need to be updated
- [ ] Create designs for any online form field updates.
- [ ] Create subsequent engineering ticket (if needed)

## Acceptance Criteria
- [ ] Wireframes for CH 36 form updates/additions.

**Comment by fiorella-io** [comment]
I created the 1st draft of the [COE designs](https://www.figma.com/design/I40qWfEd6F4CSPfDSMqGeQ/COE-2024-Updates?node-id=0-1&t=da7nch845NUGjwJe-1).

Blockers:
- The platform team is working on creating a new v3 file upload that incorporates a select component. [See thread](https://dsva.slack.com/archives/C01DBGX4P45/p1717421035858089?thread_ts=1717188410.903489&cid=C01DBGX4P45).
     - We need this component to be ready for our [Upload Documents page](https://www.figma.com/design/I40qWfEd6F4CSPfDSMqGeQ/COE-2024-Updates?node-id=107-50350&t=da7nch845NUGjwJe-1). 
- We need to identify who our SMEs are
     -  I had reached out to Colin Deaso and John Blakenship and scheduled a meeting on 5/23
     - We didn't have the right folks on the call - Steve Varlas, who Colin had identified as an SME, didn't make it
     - I emailed the group and attached a Word doc with questions on 5/23
     - After no response, I emailed the group again today 6/4

**Comment by fiorella-io** [comment]
@steele-lm Should this be closed or moved to the new team?

**Comment by steele-lm** [comment]
@fiorella-io This will be moved. Thanks!
