### ISSUE TITLE
Sunset Old DOMO Dashboard 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#78069]
## Issue Description
_As the updated DOMO dashboard is moved to production, the old dashboard needs to sunset. 
---
## Tasks
- [x] Compile a list of authorized Users 

- [x] Export Data 
- [x] Transform data to compatible format 
- [x] Disable access to dashboard
- [x] Schedule deactivation 
- [x]  Archive content

- [x]  Monitor transition 

## Acceptance Criteria

 - [x] **Scenario: Notify Users of upcoming sunset - No data will be lost**
    - Given there are users who use the old DOMO dashboard
    - When users receive a notification about the upcoming sunset
    - Then users are aware that the old dashboard will be deactivated
- [x] **Scenario: Export Data**
    - Given there is data in the old DOMO dashboard
    - When the data is exported
    - Then the data is successfully transferred to a compatible format
- [x] **Scenario: Transform data to compatible format**
    - Given the data is in an incompatible format
    - When the data is transformed to a compatible format
    - Then the data can be imported into the updated DOMO dashboard
- [x] **Scenario: Disable access to dashboard**
    - Given the old DOMO dashboard is still accessible
    - When access to the old dashboard is disabled
    - Then users cannot access the old dashboard
- [x] **Scenario: Schedule deactivation**
    - Given the old DOMO dashboard is still active
    - When the deactivation is scheduled
    - Then the old dashboard will be deactivated on the scheduled date
- [x] **Scenario: Archive content**
    - Given there is content in the old DOMO dashboard
    - When the content is archived
    - Then the content is stored securely and can be accessed if needed

- [ ] **Scenario: Monitor transition**
    - Given the transition to the updated DOMO dashboard
    - When the transition is monitored
    - Then any issues or concerns can be addressed and resolved promptly
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Completed 3/25/24
