### ISSUE TITLE
CH 36 | URL Redirects

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78077]
## Issue Description
_The form number for Chapter 36/PCPG recently changed from 25-8832 to 27-8832. URLs that include references to 25 need to be redirected to 27. The form number was also changed in October (from 28-8832 to 25-8832), so redirects implemented as part of that change need to be included._

- October pdf redirect (from 28 to 25): #67075
- October form flow redirect (from 28-85): #15219

---
## Tasks
- [ ] Redirect existing redirects to new url (28 to 27)
- [ ] Redirect current pdf url to new url (25 to 27)
- [ ] Redirect current form flow urls to new url (25 to 27)

### Original Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
[https://www.vba.va.gov/pubs/forms/VBA-28-8832-ARE.pdf](https://www.vba.va.gov/pubs/forms/VBA-28-8832-ARE.pdf) | [https://www.vba.va.gov/pubs/forms/VBA-25-8832-ARE.pdf](https://www.vba.va.gov/pubs/forms/VBA-25-8832-ARE.pdf)
https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/ | https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832

## Acceptance Criteria
- [ ] Link to pdf redirects to 27-8832
- [ ] Form flow redirects to 27-8832
- [ ] Redirects for 25-8832 redirect to 27-8832
---
