### ISSUE TITLE
Milestone 3: Review Instance Replacement Candidate

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#78084]
## Status
| Date       | Status         | Launch Date   | Notes                             |
|------------|----------------|---------------|-----------------------------------|
| 2025-6-20 | In Progress | TBD | Effort is being deprioritized, and schedule will be revisited based on staffing changes. Identity Routing approach has been defined and ticketed, remaining Milestone 3 tasks have been ticketed. Revproxy setup tickets have been completed, lifecycle management has been established, and build workflow automated, research plan has been completed.
| 2025-5-30 | In Progress | On Track (MS3 - July 2025) | Determining approach for RevProxy implementation with Preview Environments, defining dev credentials when postgress databases are created for PEs, add lifecycle rules, build/version/publish parent helm chart to ECR
| 2025-5-16 | In Progress | Behind Schedule (MS3 - July 2025) | Implementing RevProxy configurations for Preview Environments, establishing a permanent URL and control-plane location, developing auto-update functionality, beginning to establish datadog dashboard creation for success metrics, improving login by making CloudTrail events for SSM variable changes visible.
| 2025-5-1 | In Progress | Behind Schedule (MS3 - Q2 2025) | Working to finish Helm Chart and Param Store normalization, implementing auto-rebuild on code changes, and updates of environment status features. 
| 2025-4-18 | In Progress | Behind Schedule (MS3 - Q2 2025) | Working towards finishing the last of the Helm Chart Normalization, will be complete next sprint, collaborating with SRE to complete Param Store Normalization, setting up v.Next clusters and RevProxy for Preview Environments. |
| 2025-4-18 | In Progress | Behind Schedule (MS3 - Q2 2025) | Working towards finishing the last of the Helm Chart Normalization, will be complete next sprint, collaborating with SRE to complete Param Store Normalization, setting up v.Next clusters and RevProxy for Preview Environments. |
| 2025-4-3 | In Progress | Behind Schedule (MS3 - Q2 2025) | We've successfully added vets-api mock data, including functionality for pre-merge testing. Parameter store variation between environments has been reduced, enhancing test environment consistency with production. Additionally, we've onboarded Infra team staff into the Preview Environment project and completed all UX/UI designs.  |
| 2025-3-28 | In Progress | Behind Schedule (MS3 - Q2 2025) | We've increased staffing to accelerate our timeline. All required Milestone 3 features are now underway, including finishing Helm chart and param store normalization and cleanup. Started work on implementing authentication to support the use of mock data and staging test data, and planning and coordination of the UX/UI approach to Preview Environments in collaboration with the SRE team. Planning has begun for UAT testing to validate the replacement capabilities. |
| 2025-3-21 | In Progress | Behind Schedule (MS3 - Q2 2025) | Deployed reverse proxy integration for unified application routing, implemented secure self-hosted runners within SOCKS, transferred GitHub app ownership to VA org, working on detailing out the remaining work for Milestone 3 epic. |
| 2025-3-7 | In Progress | Behind Schedule (MS3 - Q2 2025) | We have completed the blocking portion of the param store normalization effort, the remaining cleanup will be conducted under Milestone 4. We are beginning on helm chart and docker image work for vets-api. Param store reviews have taken longer than anticipated and have delayed overall Milestone 3 progress. With that work completed, we're increasing staffing on this effort to accelerate the completion of Milestone 3. |
| 2025-2-24 | In Progress | On Track (MS3 - Q1 2025) | Completed alignment on approach changes to param store updates, finishing updates to UI/UX designs. Conducted technical deep dive with the team. |
| 2025-2-10 | In Progress | On Track (MS3 - Q1 2025) | Work ramped down this sprint due to key staff on T2 support rotation, will resume as planned next sprint. Had a meeting to discuss Identity team's concern with the implication of Param Store/Helm Chart normalization work. |
| 2025-1-24 | In Progress | On Track (MS3 - Q1 2025) | We are finishing up work on parameter store normalization, this sprint or next sprint. |
| 2025-1-13 | In Progress | On Track (MS3 - Q1 2025) | Milestone 3 is progressing. good progress made over the holiday sprints, continued work on helm charts. |
| 2024-12-18 | In Progress | On Track (MS3 - Q1 2025) | Milestone 3 is progressing. Helm chart normalization was moving forward more smoothly during the span of this sprint. |
| 2024-12-5 | In Progress | On Track (MS3 - Q1 2025) | Milestone 3 is progressing. The helm chart normalization work is progressing slower than anticipated due to the thoroughness of the reviews on the work. We'll bring other Milestone 3 work forward to fill the gaps. |
| 2024-11-22 | In Progress | On Track (MS3 - Q1 2025) | Milestone 3 in progress, initial param store normalization has been completed, and is waiting for helm chart normalization work to complete before it can be resolved. Helm chart normalization is beginning in sprint 15. |
| 2024-11-7 | In Progress | On Track (MS3 - Q1 2025) | Milestone 3 is progressing, param store normalization almost complete, should complete next sprint, no blockers |
| 2024-10-23 | In Progress | On Track (MS3 - Q1 2025) | Milestone 3 is progressing, param store normalization should complete next sprint, no blockers |
| 2024-10-09 | In Progress | On Track (MS3 - Q1 2025) | Param store normalization in progress|

## Product Outline
[Preview Environments Product Outline](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2424472954/Preview+Environments+-+Product+Outline)

## High Level User Story/ies
As a developer on the VA.gov platform, I need robust and flexible preview environments so I can efficiently test changes in a simulated production-like setting without impacting the live environment.

## Hypothesis or Bet
**If** _we enhance preview environments with additional features like standardized helm charts, parameter store normalization and override, authentication/use of mock and staging test data, and additional feature **then** we expect developers will be able to use preview environments effectively as a replacement for Review Instances, and Review Instances can begin to be sunset.
[Complete Feature List for Milestone 3](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3391848482/Milestone+3+Review+Instance+Replacement+Candidate)

## OKR
2023-Objective 2 - Enhance Platform technologies and processes to be agile and scalable to tolerate at least a 50% unexpected increase in VFS product development workloads and Veteran end-user usage. (Was not associated w/ a specific KR)
_(This applies to the Preview Environment effort overall)_

## Definition of Done
- [x] Preview Environments allow the selection of specific versions of vets-website and vets-api when they are created. 
- [x] Users can utilize mock data and/or staging test data in their preview environment
- [ ] Environments automatically expire, and resources are cleaned up accordingly
- [x] A unified Helm chart is used for both Production and Preview environments.
- [ ] Non-release containers and helm charts are cleared from ECR monthly.
- [x] Configuration defaults to Staging parameter store values unless overridden during creation.

### Success Metrics
- Number of Preview Environments created and utilized is greater than 5%
- Decline in negative comments about testing environments

## Projected Launch Date
We expect to complete this epic by Q2 2025.

**Comment by EWashb** [comment]
I know we covered this on Monday as perhaps slipping the original timeline of end of June. Can we get an updated expected delivery date for the review instance replacement? @JoeTice @jwoodman5 @davidpetras

**Comment by jwoodman5** [comment]
@EWashb We are working to get you something solid.

**Comment by jwoodman5** [comment]
@EWashb I believe the sprint that ends July 2nd is what was communicated as and "end of June/early July" target. This ends up being Sprint 4 OY2. I feel much better looking at a target of Sprint 5 OY3, which ends July 16th. Of course, we will keep you updated as we get closer and confidence increases.
