### ISSUE TITLE
Milestone 2: Usability Testing

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#78085]
## Description
Preview Environment Milestone 2 will provide a working MVP that allows the testing of unauthenticated experiences behind SOCKS. This epic focuses on the usability testing of that MVP to determine if it functions as expected, and how it might be improved for future iterations.

---

### Definition of Done
- [x] A research is created and reviewed
- [x] A conversation/moderator's guide has been written and reviewed
- [x] A pilot session has been done to validate that the Preview Environment can support usability testing
- [x] Usability testing sessions have been performed and responses/feedback has been synthesized
- [x] Tickets have been created based on feedback

### Success metrics
- Tracking number of Preview Environments that have been created
- Tracking the number of Preview Environments that have been accessed/used
