### ISSUE TITLE
Execution: DSVA Slack Profile Audit Bot

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78089]
## Description 

This ticket will house the task of executing on a DSVA Slack Profile audit to ensure everyone's is updated on both Platform and VFS teams.

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Outline the steps needed to complete for this ticket to be completed 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlasian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Reference for what is required in Slack Profile: https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile

**Comment by alyssagallion** [comment]
Not a priority. Closing.
