### ISSUE TITLE
Milestone 2: Preview Environment MVP behind SOCKS

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#78082]
## Description
Preview Environment Milestone 2 will provide a working MVP that allows the testing of **unauthenticated** experiences behind SOCKS. The intent of milestone 2 is a working iteration that functions and is ready to scale, while it still needs additional features to make it more directly helpful for users.

### Definition of Done
- [x] A user can create a preview environment with a specific version of Vets Website and Vets API
- [x] Anyone can access that preview environment behind SOCKS
- [x] A user can test an unauthenticated experience with a preview environment
- [x] Preview environments can be cleaned up when no longer needed

### Success metrics
~- [ ] Tracking number of Preview Environments that have been created~
_(Item will be added to Milestone 3)_
