### ISSUE TITLE
[FE][BUG][SPIKE] - research methods for unit testing DS checkboxes(and maybe other components)

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#78083]
## Description

Due to the shadow not rending in our unit tests, we can't unit test the onVAChange events from checkbox checks. This ticket is a spike to research how we might be able to do that in the future.

Reference: [slack thread](https://dsva.slack.com/archives/C03ECSBGSKX/p1695849715413279?thread_ts=1695838671.023759&cid=C03ECSBGSKX)

Example of test that won't work originally from `travelMileage.unit.spec.js`:
```
    This test is currently impossible due to shadowDOM
    describe('onCheck', () => {
      it('updates state on facility check', () => {
        const store = {
          eligibleToFile: [
            {
              stationNo: '500',
              startTime: '2021-08-19T13:56:31',
              facility: 'fac 1',
            },
            {
              stationNo: '600',
              startTime: '2021-08-19T13:56:31',
              facility: 'fac 2',
            },
          ],
        };
        const expectedStateValue = [
          {
            stationNo: '500',
            startTime: '2021-08-19T13:56:31',
            multipleAppointments: false,
          },
        ];
        const component = render(
          <CheckInProvider store={store}>
            <TravelMileage />
          </CheckInProvider>,
        );
        expect(component.getByTestId('[]')).to.exist;
        const checkBox = component.getByTestId('checkbox-500');
        // checkBox.__events.vaChange();
        // checkBox.__events.vaChange({ detail: { value: 'other' } });
        fireEvent.click(checkBox);
        expect(await component.getByTestId(JSON.stringify(expectedStateValue)))
          .to.exist;
      });
      it('updates state on facility un-check', () => {
      });
    });
```

## Tasks
- [ ] [FE] Research reliable testing methods

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
