### ISSUE TITLE
Update Test Plan, Coverage for Reverence and Summary (Defects) Report in TestRail for Representative Status Widget MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78096]
## Background
We need to create a Test Plan, Coverage for Reverence and Summary (Defects) Report in TestRail for our Representative Status Widget MVP.

> The **Test Plan** is basically a set of instructions that we write for proceeding through the UI flow, along with expected behaviors/results. To run a test is to manually step through those instructions, and then assign a pass/fail with any additional comments. You can also note any bugs/defects, which get compiled in the **Summary (Defects) Report**.

> The **Coverage for Reference Report** summarizes all the user paths, features etc, as well as which test cases pertain to which reference. So there could be a reference called "Reporting Outdated Information," and then test cases would be associated with that (eg clicking the button to trigger the modal, revealing the text input by checking "Other" checkbox, etc would each be tied to that reference) 

## Tasks
- [ ] Create a Test Plan to cover all states of the widget
- [ ] Create a Summary (Defects) Report to note any relevant bugs/defects that one may encounter in the Test Plan
- [ ] Create a Coverage for Reference Report summarizing all user pathways, features, etc., as well as which test cases pertain to which reference 
- [ ] Share link(s) to the Test Plan, Coverage for Reverence and Summary (Defects) Report (or instructions on how to view it) in the comments of this ticket, so Lindsay can include that in the Staging Review request

## Acceptance Criteria
- [ ] The Test Plan supports Representative Status Widget MVP
- [ ] The Summary (Defects) Report supports Representative Status Widget MVP
- [ ] The Coverage for Reference Report supports Representative Status Widget MVP
- [ ] The Test Plan, Coverage for Reverence and Summary (Defects) Report have been shared with Governance as preparation for Staging Review

**Comment by cosu419** [comment]
[Coverage for references:](https://dsvavsp.testrail.io/index.php?/reports/view/773)

[Summary Defects report](https://dsvavsp.testrail.io/index.php?/reports/view/774) - will need to re-run this once the download link is functioning properly.

**Comment by oddball-lindsay** [comment]
Thanks @cosu419 ! The Staging Review ticket asks for a link for a "Test Plan" as well, could I repurpose one of the links above for the Test Plan reference?

**Comment by cosu419** [comment]
This would be a better link for the test plan:

https://dsvavsp.testrail.io/index.php?/plans/view/5457

**Comment by cosu419** [comment]
New summary defects report link:

https://dsvavsp.testrail.io/index.php?/reports/view/783

**Comment by oddball-lindsay** [comment]
Thank you @cosu419!  Just added to the Staging Review information -- ready to close this out?

**Comment by cosu419** [comment]
Sounds good - closing
