### ISSUE TITLE
E2E Tests for Representative Status Widget MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78097]
## Background
E2E testing for Representative Status Widget MVP, as we prepare for Staging Review.

## Tasks
- [ ] Write E2E test for all widget states
- [ ] Share a link to our product's code, so Lindsay can include in the Staging Review request

## Acceptance Criteria
- [ ] End to end tests reflect all states of Representative Status Widget MVP
- [ ] All tests passing with adequate coverage

**Comment by cosu419** [comment]
[Test code here](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/static-pages/representative-status/tests) - should wait until my PR merges to send this out.

**Comment by oddball-lindsay** [comment]
The geolocation test is failing, perhaps the mapbox token is expired.  To get the PR merged, we may need to disable this test temporarily or create a separate ticket.  Might be worth retrying the test first.

**Comment by oddball-lindsay** [comment]
@cosu419 Looking back over our [Staging Review for Find a Rep](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71943), we had the same link for the E2E tests and Code coverage.  

<img width="1514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0NyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--293f20bf3d9e82a08a2ba04f2a8fdfd98b0d0a8c/image.png" alt="image.png" />

For this Widget release, would it be accurate to use your test code link above for "code coverage" too?
