### ISSUE TITLE
Add Widget to Find a Rep

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78091]
## Background
The launch of the Rep Status Widget will include adding it to our [Find a Representative page](https://www.va.gov/get-help-from-accredited-representative/find-rep/).  The widget should not be visible to users prior to launch, because it will be behind a feature flag.

Design with annotations: https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2059-92327&mode=design&t=3j7xuROAnQGG96x6-11

## Tasks
- [ ] Add widget code to Find a Rep as specified in the design link above
- [ ] Confirm that the feature flag is working as expected and Widget does not appear in production

## Acceptance Criteria
- [ ] When the Rep Status Widget is released, users on VA.gov will be able to see their current representative status before searching for new representation.

**Comment by oddball-lindsay** [comment]
The widget is already added to Find in Staging :)
