### ISSUE TITLE
Prepare for Contact Center Review | Representative Status Widget MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78098]
## Issue Description
As part of the collaboration cycle, we will need to go through a Contact Center Review. [The full Contact Center Review process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md).

---
## Tasks
- [x] Confirm with Engineering that the build is available in Staging
- [x] Create a Product Guide (must be a Word document with a linked Table of Contents)
- [x] Share Product Guide with team for review
- [x] Submit a a [Contact Center Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+kimberley2019&labels=contact+center%2C+collaboration+cycle%2C+collab-cycle-review&template=request-contact-center-review-template.md&title=Contact+Center+Review+for+%5BTeam+Name+-+Feature+Name%5D) (3-5 business days for Contact Center POCs to review, another 5 business days for overall Contact Center review)

## Acceptance Criteria
- [x] Product Guide has been completed
- [x] Contact Center Review ticket has been submitted

**Comment by oddball-lindsay** [comment]
First draft: [product-guide-representative-status-widget-1.0.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0diQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7930e0be802e16d777332df7556cab2619aed4d4/product-guide-representative-status-widget-1.0.docx)

Still need the Individual screenshot/figure, but open to feedback now.

**Comment by oddball-lindsay** [comment]
Individual state added in, uploaded guide to Github: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/product-documentation/representative-status-widget/contact-center

**Comment by oddball-lindsay** [comment]
Team says things look good, submitted the Contact Center review ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82124
