### ISSUE TITLE
ARM team QA of Rep Status Widget

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78093]
## Background
This is a placeholder for the ARM team's QA of the Representative Status Widget, before heading into Staging Review.
We can also request review from our CAIA a11y and content partners.

Test users: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv

## Tasks
- [x] Ask the team to QA the Rep Status Widget with all users/states in mind
- [x] Collect any findings from team QA in a Google doc, with notes on priority when possible (design and a11y findings)
- [x] Create tickets to address findings

## Acceptance Criteria
- [x] The team has reviewed the Rep Status Widget and tickets have been created to address any findings

**Comment by oddball-lindsay** [comment]
For testing individuals: if they have ICNs that work on the lower environments, @jvcAdHoc may have a way to get us what we need through LH.

**Comment by oddball-lindsay** [comment]
@cosu419 let's chat w the team in standup tomorrow about setting the Individual state in Staging.  

I've confirmed that we need a test users for Staging Review, so currently questioning if it's even worth the effort to manually set the state when we'll have to come back in with the test user anyway.  Perhaps your time is better spent on the other issues in the sprint backlog.

**Comment by oddball-lindsay** [comment]
Considering this "Blocked" until we have a test user for the Individual state

**Comment by oddball-lindsay** [comment]
We have our individual test users: 
vets.gov.user+33@gmail.com (line 5) has an attorney
vets.gov.user+108@gmail.com (line 7) has a claims agent

Left some feedback in our QA document and will ticket any outstanding items later today in case the team has additional findings.

**Comment by oddball-lindsay** [comment]
We have our individual test users: 
vets.gov.user+33@gmail.com (line 5) has an attorney
vets.gov.user+108@gmail.com (line 7) has a claims agent

Left some feedback in our QA document and will ticket any outstanding items later today in case the team has additional findings.
