### ISSUE TITLE
Migrate GIBCT to EKS

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#78105]
Currently, GI Bill Comparison Tool (GIBCT), a Rails application, is hosted on "BRD" infrastructure which is using the Amazon Linux 1 (AL1) OS distro. For future interoperability and to migrate off AL1s, GIBCT needs to be migrated to our modern platform operating on Kubernetes and EKS.

```[tasklist]
### Tasks
- [ ] Clean up Dockerfile
- [ ] Ensure all existing infra is in Terraform
- [ ] Write Helm chart & values
- [ ] Create GitHub Workflow to build/upload docker image to ECR
- [ ] Create GitHub Workflow to deploy to EKS
- [ ] Decommission old infrastructure
```

**Comment by JoeTice** [comment]
This effort is no longer necessary, as GIBCT/GIDS will now be migrated directly to AL2023. That work will be accounted for under this initiative: https://github.com/department-of-veterans-affairs/va.gov-team/issues/108078. This effort can be closed, pending leadership approval.
