### ISSUE TITLE
Redirect Request: About VA form 25-8832

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#78118]
## Notes
- See recent Jill's comments 

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/find-forms/about-form-25-8832/ | https://www.va.gov/find-forms/about-form-27-8832/

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78344
```

**Comment by kristinoletmuskat** [comment]
@RLHecht do you know when the new page will be live? I just wanted to check so we don't redirect to a 404.

**Comment by RLHecht** [comment]
I don't know if @strelichl has set up the ticket yet to change the form landing page url. Lily, can you tag Kristin in it once the page is live?

**Comment by jennymayoco** [comment]
I saw the new URL has been changed and that the page is now live. 

@FranECross @jilladams these are good to go! Some background on this, form number has been updated from 25-8832 to 27-8832 so the URL has been changed to reflect this. This form number was changed a few months ago so linking that [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14436) for reference

**Comment by FranECross** [comment]
Thanks, @jennymayoco ! I noticed that when I'm viewing the new page (27-8832), and I click the "Go to the online tool' link, it opens a page that still has 25-8832 as the title and in the url. Does that need to be changed, too?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/147188767/ae994334-ea0f-4453-899b-0a10d4eb0696)

**Comment by jennymayoco** [comment]
@FranECross thanks for flagging! the team has a [redirect request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78077) for the online form and the PDF they are implementing. We weren't able to redirect the PDF without assistance from a VBA forms manager and Jill and Dave Conlon were a part of that convo and led that comms, but I think the team is looking for support with the PDF redirect. I'm linking [the Slack thread](https://dsva.slack.com/archives/CE4304QPK/p1710367490703639?thread_ts=1687293546.830659&cid=CE4304QPK) with convo on this change and I looped you into the most recent comment

**Comment by jilladams** [comment]
After reviewing this in our engineering refinement, I think what we're saying here is: 
1. The redirect in this ticket is ready to implement, as is .(And we should try to do that soon. The old URL is 404ing today.)
2. The online tool contains the wrong form number and the team that owns the online form is working on that under https://github.com/department-of-veterans-affairs/va.gov-team/issues/78077. Public Websites doesn't have any responsibility here.
3. The PDF redirect also has to happen upstream somewhere else, and doesn't belong to Public Websites.

**Comment by jilladams** [comment]
Also noting there's an old redirect for this we need to account for: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L5465

**Comment by jennymayoco** [comment]
Hi @jilladams - that's correct to all the above! The product team will be implementing the redirect for the online form and we've also connected with them about working with their stakeholder for the PDF redirect.

Let me know if there are any questions.

**Comment by randimays** [comment]
This has been verified successfully in production:

- https://www.va.gov/find-forms/about-form-25-8832/ redirects to https://www.va.gov/find-forms/about-form-27-8832/
- https://www.va.gov/find-forms/about-form-28-8832/ (redirect added last year) redirects to https://www.va.gov/find-forms/about-form-27-8832/

Closing!
