### ISSUE TITLE
Create GA4 View in BigQuery for 'BQ - Standard Content Engagement' (VA.gov Content KPIs)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78123]
### Description:
We need to create a new view in BigQuery that combines UA and GA4 data. This will include mapping the attributes of the current UA data model to those within the new GA4 data model. 

For this card, the focus will be on the _**BQ - Standard Forms Engagement**_ dataset, which is the primary dataset behind the VA.gov Forms KPIs dashboard in Domo.

- **Domo Dashboard:** [VA.gov Content KPIs]( https://va-gov.domo.com/page/426422632)
- **Dataset:** [BQ - Standard Content Engagement](https://va-gov.domo.com/datasources/b677d6c5-5a79-41c8-a3a8-438fb769ffc3/details/overview)

---

### Tasks:
- [x] Leverage findings from [GA4 View pilot ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/77173).
- [x] Review the list of dimensions defined in GA4 and map to the UA equivalent
- [x] Create related views in BigQuery, that incorporate GA4 data.

### Acceptance Criteria:
- [x] New GA4 views will be created in BigQuery
- [x] New GA4 views, will be tagged or identified through some means, (through use of BQ labels, a created list, or some other means)

**Comment by johnny-jesensky-adhoc** [comment]
We had a slight mix up on what we pulled into the current sprint, so we are swapping this ticket into the current sprint, and removing [this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78058).

FYI @dorseypa1

**Comment by johnny-jesensky-adhoc** [comment]
New GA4 View created -- mapping work done in [this document](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=1589604846). 

**- GA4 View for Content Engagement:** [vw_GA4_content_engagement_last_week
](https://console.cloud.google.com/bigquery?q=search&referrer=search&page=table&p=vsp-analytics-and-insights&d=vsp_sites&t=vw_governance_github_tickets&project=vsp-analytics-and-insights&supportedpurview=project&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_content_engagement_last_week&pli=1)

We'll be continuing to use that artifact in our upcoming sprint for additional GA4 View tickets.

FYI @dorseypa1, @ChristineYoungZA, @Blivaditis
