### ISSUE TITLE
Copy of Create GA4 View in BigQuery for 'BQ - Standard Forms Engagement' (VA.gov Forms KPIs)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78136]
### Description:
We need to create a new view in BigQuery that combines UA and GA4 data. This will include mapping the attributes of the current UA data model to those within the new GA4 data model. 

For this card, the focus will be on the _**BQ - Standard Forms Engagement**_ dataset, which is the primary dataset behind the VA.gov Forms KPIs dashboard in Domo.

- **Domo Dashboard:** [VA.gov Forms KPIs]( https://va-gov.domo.com/page/447193050)
- **Dataset:** [BQ - Standard Forms Engagement](https://va-gov.domo.com/datasources/f256e93e-e0ff-4d69-bd69-404f98bc335b/details/overview)

---

### Tasks:
- [ ] Leverage findings from [GA4 View pilot ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/77173).
- [ ] Review the list of dimensions defined in GA4 and map to the UA equivalent
- [ ] Create related views in BigQuery, that incorporate GA4 data.

### Acceptance Criteria:
- [ ] New GA4 views will be created in BigQuery
- [ ] New GA4 views, will be tagged or identified through some means, (through use of BQ labels, a created list, or some other means)

**Comment by johnny-jesensky-adhoc** [comment]
GA4 View created here https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&supportedpurview=project&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_search -- moving this to _Done_.

QC is unblocked, and will be started.

FYI @dorseypa1
