### ISSUE TITLE
Create MHV Credential Segment Trending View

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#78135]
## Issue Description
VA leadership and MHV stakeholders needs to visualize the progress over time of the Secure Sign-in Transition on users with MHV credentials, so they can make decisions related to sunsetting MHV credentials

## Tasks

Configure Domo and Domo Workbench to load new datasets
- [x] update the transformation flow that generates summary indexes for trending views to include MHV dataset
- [x] upload past MHV datasets with snapshot dates
- [x] update past MHV datasets to be consistent in terms of headers, ID fields, excess whitespace removal, and single file versus multiple files.
- [x] create new visualization for MHV trend

## Acceptance Criteria
- [x] Secure Sign-in Adoption dashboard updated with MHV trending visualization

**Comment by sdickson-gt** [comment]
Working on trending report.  The MPI data has the credential overlap, record create data and last used date information, but MHV has the authoritative number of users and there is a significatn number of MHV credentials 
 not tracked in MPI and some users with MHV credentials unknown to MPI.
Based on that, have to design some workarounds including:
- remove the filter based on users' last active data for MHV data
- somehow address the MHV users which aren't correlated to MPI while still expressing an accurate trending representation
- properly handle the gaps between MHV datasets - up to 5 months (This isn't a problem to reconstruct trends with the MPI data since it contains the record created data and last used dates - but MPI doesn't have the complete picture for MHV)

**Comment by sdickson-gt** [comment]
This is complete
