### ISSUE TITLE
[Research] VA.gov Onboarding: Draft generative research plan and convo guide

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#78147]
## Background
Following Liz's [review of previous research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/research-review.md) we would like to pursue our own generative research study around va.gov onboarding.

### What we want to learn from this research

We have two main research goals:

1. What role does VA.gov have in onboarding people to VA?
2. What changes, if any, could we make to improve the experience of onboarding to VA through VA.gov?
  - What challenges do people have using VA.gov when they're using it for the first time?
  - Where does VA.gov fit within the mental model of people who are onboarding to VA?
  - What are the top questions transitioning service members have about VA?

## Tasks
- [ ] Create draft research plan
- [ ] Start draft of conversation guide
- [ ] Peer review
- [ ] Review with PM, PO

## Acceptance Criteria
- [ ] Draft research plan is created

**Comment by Samara-Strauss** [comment]
IMO, these are the key research questions:

- What role does [VA.gov](http://va.gov/) have in onboarding people to VA? This is the key question.
- What changes, if any, could we make to improve the experience of onboarding to VA through [VA.gov](http://va.gov/)?


This research is about both the website and the organization. It's (obviously) not just a usability test, but it's also not meant to get as big as "how can we solve all of transition for VA?"

**Comment by andaleliz** [comment]
@clantosswett, I reviewed my drafts with AJ and we're ready for your feedback! Here is the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/2024-03-onboarding-generative-research/research-plan.md) and the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/2024-03-onboarding-generative-research/conversation-guide.md).

Once we're all aligned on these docs, I'll share w/ Gene + team and offer to them to add questions/goals so we can support their work too.

#### Research plan notes
The words "onboarding" and "transition" are pretty loaded in our VA universe so I added a note of clarification to the research plan in hopes that people will be extra clear on our focus.

I really want to make sure we're talking to the right people, so I'm particularly interested in your thoughts on the [recruitment criteria](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/2024-03-onboarding-generative-research/research-plan.md#recruitment-criteria).  A couple notes on this:

- I feel like a year is too far so I capped the separation timing at 9 months.  
- The cognitive impairment is there to make sure we talk to folks who may have trouble processing large amounts of info, and complicated information 
- The education criteria is there to make sure we talk to folks who may not have the kind of experience people get with researching/processing complicated information that they do when they go through undergrad/grad programs. 

#### Convo guide notes
-  I don’t feel like I needed to be super rigid with it, since this is generative and will likely be very much informed by whatever the participant says.
-  During the last portion, I imagine it'll be natural for us to pull up the website and look at it together. I'm considering asking people who have never used the site before to do a screen share and show me how they'd look up something we talked about earlier. Any thoughts on that?

**Comment by clantosswett** [comment]
@andaleliz just reviewed and this looks really good! I liked the recruitment criteria and I don't have any additional feedback on that or the project plan. I think the one area that is a bit fuzzy to me is how we will handle participants who have never used VA.gov before. As you mentioned, we can pull up the site. I wish there was a way we could interview someone who was seeing the auth version of the site for the first time but in the end it's probably not necessary given the hurdles to completing the account creation process. 

Thank you for such a quick turnaround and let me know if there is anything else you need from me!

**Comment by andaleliz** [comment]
@clantosswett thank you for the feedback, and I'm glad you're happy with the docs overall.  That's a good point about participants who have never used the website before. I can think more about how to get the most out of those sessions, but I love the idea of interviewing someone as they went through the auth version the first time. 

We could add a screener question, that wouldn't disqualify folks, but would help us plan for people who are open to this. I think it'd be really valuable for this research, the identity team, and auth exp as a whole.

**Proposed screener:**

If you have never logged into VA.gov before, would you be willing to create an identity-verified account during the session and provide your feedback on the website after you have signed in? Creating an account is a 5-10 minute process that requires a form of government identification. Your response will not disqualify you from the study.
> Response options: radio buttons
> - No, I don’t want to create a VA.gov account during my session.
> - Yes, I’d be willing to create a VA.gov account during my session. 
>   *Note for perigean:* Please add 15 minutes to the session for participants who answer yes.

**Comment by andaleliz** [comment]
FYI, I'm going to submit the study under the name "TSM Engage with VA Generative Research" instead of "VA Onboarding Generative Research" because the term onboarding can be loaded. Internally, I already had one veteran ask for clarification on the study because they saw the word "onboarding" and assumed I was only interested in TAP training.  Perigean puts the name of the study in calendar invites and other things I think participants see so I want to avoid priming anyone.
