### ISSUE TITLE
Find a Rep LIVE - User Test - Mobile User - Revisions

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#78149]
## Issue Description
Live user testing of Find a Representative experience with mobile and assistive technology (AT) users.

## Tasks
- [ ] Update research plan
- [ ] Update convo guide
- [ ] Upload research plan and convo guide to GitHub
- [ ] Create GitHub Research Repo ticket
- [ ] Create GitHub recruitment ticket
- [ ] Create collab cycle + recruitment ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by oddball-lindsay** [comment]
Hoping to include testing of the landing page / Appoint intro page -- need a placeholder design link by Wednesday @mtri

**Comment by jfinnerty13** [comment]
Documents updated and ready for research collab once I have the prototype link - thanks!

**Comment by jfinnerty13** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-03-ARM-findarep-live-usertest
