### ISSUE TITLE
Find a Rep LIVE - User Test - AT Users - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#78150]
## Issue Description
Live user testing of Find a Representative experience with mobile and assistive technology (AT) users.

## Tasks

- [ ] Request research review
- [ ] Update user test to reflect collab cycle edits
- [ ] Set-up Enjoy HQ project
- [ ] Kick-off with Perigean
- [ ] Create sign-up sheet
- [ ] Transfer demographics to sign-up sheet & Excel
- [ ] Create folders & update guideline documents
- [ ] Create notetaker template
- [ ] Set up Slack channel w/ notetakers & observers
- [ ] Kick-off with notetakers
- [ ] Conduct pilot session
- [ ] Kick-off with observers
- [ ] Create debrief Mural
- [ ] Create conduct interview Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by oddball-lindsay** [comment]
Pilot session complete with some findings outlined here: https://dsva.slack.com/archives/C05L6HSJLHM/p1711382443533039

Kickoff with observers is next -- will need help tracking the tasks

**Comment by jfinnerty13** [comment]
https://dsva.slack.com/canvas/C06QVMQV97D canvas with all the info for recruitment week

**Comment by jfinnerty13** [comment]
Most recruitment complete - will continue to add in users but bulk of work is done so closing ticket.
