### ISSUE TITLE
Investigating reports of Non-Veteran waiver submissions for VHA

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#78168]
## Issue Description
VHA is reporting that non-veterans are submitting waiver requests.  That is a problem because non-Veterans are not eligible for waivers. VHA has provided an example of a non-Veteran submission that we need to investigate. Ultimately, we need to determine how to identify individuals who fall into this category and provide them with the appropriate messaging that align to the options they have in front of them. This will require further discussions with VHA but understanding what data we have access to will help define how we proceed

---
## Tasks
- [x] Investigate Transaction ID `06f160fe-2a88-440d-97f6-31e72320b821` What do we know about their status? Can we tell that this individual is a non-veteran?
- [ ] Identify what information in our data source would categorize a user as a Veteran or non Veteran. 

## Acceptance Criteria
- [ ] Summarize what we have identified from the particular submission
- [ ] Outline details that describe how we can distinguish non-veteran users in the future so we can determine how to prevent them from accessing the online FSR experience since they are not eligible.

**Comment by digitaldrk** [comment]
A few things moved on this ticket today:

1. Kevin and I paired on this, we found that the form submission we have with this transaction id is not a waiver.
2. I found I had not submitted a ticket for SOCKS access, [got one sent in](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85619) this should get me into Sentry, Jenkins, and then the ability to query these records
3. Kevin encouraged me to submit a question to the identity team, [I've submitted that on slack](https://dsva.slack.com/archives/CSFV4QTKN/p1718071718284729).

**Comment by digitaldrk** [comment]
Just got word that the team will look into it 'tomorrow' which is likely today :). I'll update here on what learn:

https://dsva.slack.com/archives/CSFV4QTKN/p1718078082296329?thread_ts=1718071718.284729&cid=CSFV4QTKN

**Comment by digitaldrk** [comment]
User is by all indication a veteran, we're looking into how this user might not be considered a vet. Latest hunch is the user entered a different SSN in the form from what is in their profile

**Comment by digitaldrk** [comment]
After the conversation today with the Identity team, I'm going to close this ticket and create a new one where we interface with the #accountexp-authexp slack channel.

Here's our learnings:
* There's no definitive way to determine whether the user is a veteran or not. We will talk to the #accountexp-authexp team about getting that sorted out
* The form submission we have with this transaction id is not a waiver, it was a compromise.
* That user was a veteran
* There may be a discrepancy between what the user entered and what we had in their profile

Link to the slack convo for your convenience:
https://dsva.slack.com/archives/CSFV4QTKN/p1718078082296329?thread_ts=1718071718.284729&cid=CSFV4QTKN

Link to new ticket about determining user is a veteran:
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/85743
