### ISSUE TITLE
Identify recordEvents for GA4 Migration

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78182]
## Issue Description

Due: Friday, April 5th

_The Platform and Analytics Team [has requested](https://dsva.slack.com/archives/CE4304QPK/p1710258944850399) that all VFS teams identify and inventory all recordEvent actions currently living in their codebase (aka custom events). This will ensure that these events are transitioned properly to GA4._

---
## Tasks
- [x] Inventory the following forms and fill out [this form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D) detailing what custom events exist.
   - [x] Chapter 36/PCPG 27-8832
   - [x] Chapter 31/VR&E 28-1900
   - [x] Dependents 21-686/674
   - [x] Burial 21P-530EZ
   - [x] COE/LGY 26-1800 

## Acceptance Criteria
- [ ] All recordEvent actions recorded in Github ticket
- [ ] Github ticket submitted
---

**Comment by zack** [comment]
I will be keeping track of the sheets here as I finish them:

**Dependents 21-686/674**
https://docs.google.com/spreadsheets/d/1Jl6sDqyUb0QYky-IEVrb6bCBYYxuB1bA77ZLb4oLocY/edit?usp=sharing

**Comment by zack** [comment]
@steele-lm done ^
