### ISSUE TITLE
Detailed design for success path and successful backup path of submission experience

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#78183]
## Issue Description
We are redesigning the submission experience so that Veterans know the status of their claim and understand any next steps. This ticket incorporates the design of touch points for Veterans who don't need to take additional action for their claim to fully submitted.  

**Updates include these touchpoints:**
1. Redesign of confirmation page (2 states)
2. (do this last) Appearance and behavior of in-progress forms after submission, per [Map future state solution for reducing duplicate submissions#82511](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/82511)
2. Redesign of loading screen
3. Add/redesign email notifications (3 messages)

**Context for design**
There are two main claim journeys represented in this redesign.
Path A: A claim cested in under 30 seconds 
Path B: A claim that takes longer than 30 seconds to cest, but is still successful 

The updated submission model has three statuses: Prepare, Send, Receive
Path A will include a confirmation page and two emails: claim “sending” and “received” 
Path B will include a confirmation page and three emails: claim “preparing,” “sending,” and “received”

Design details for additional touchpoints in [Happy path and Backup path in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?wid=0-1713217928067)

## Desired user outcomes
1. Address the uncertainty Veterans feel when they do not immediately receive a confirmation email after submitting the 526. 
2. Provide Veterans with timely and truthful information about claim submission.
3. Create a record of submission for Veterans to keep
 
See [feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f668515f53a7d1957d9ab92aba95ad43f647b311/products/disability/526ez/product/feature-briefs/Submission%20Experience.md#problem-or-opportunity) for the up-to-date problem statements of the larger initiative

## Working documents
1. [Figma file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f668515f53a7d1957d9ab92aba95ad43f647b311/products/disability/526ez/product/feature-briefs/Submission%20Experience.md#problem-or-opportunity)

---
## Tasks
- [x] Design mocks for touch points on the success path (described above) 
    - [x] incorporate [notes from sync with Evelyn](https://dsva.slack.com/docs/T03FECE8V/F068SQT00MC?focus_section_id=temp:C:fcI8b52553e87254b8da19ae3c90)
    - [x] Design "receipt" / open accordion of "information you submitted in your claim"
- [x] Make any relevant changes to how we describe the process in static page content, per [#83049](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/83049)
- [x] Consider web app messaging / inbox as a channel - coordinate with Benefits Management Tools and Authenticated Experience / My VA teams if necessary - not using for now. 
    - See [5/13/24 Veteran Digital User Experience Weekly Design Sync presentation](https://dsva.slack.com/archives/C0NGDDXME/p1715623664651469?thread_ts=1715605202.876099&cid=C0NGDDXME), p5
    - [Question to benefits management tools team](https://dsva.slack.com/archives/C04KHCT3ZMY/p1715703646924189) - they're not using it now, but might explore this Oct - Dec 2024. Authenticated Experience work on managing notifications will be tied to this. 
- [x] Align with Veteran Facing Forms team's work on [Show status of form submissions to users on My VA and confirmation page #1170](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170) / ensure we're not duplicating efforts.
    - [Asked in Slack](https://dsva.slack.com/archives/C06R2BZKT62/p1715290304559959)
- [x] CAIA Feedback -start the process - [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83554)
    - there are recent CAIA comments on Veteran Facing Forms team's Figma files for confirmation screens - [example](https://www.figma.com/file/XAtdtChFlfwsHRvc7i6Dmd?type=design&node-id=2022-2162&mode=design#795476332), from [Show status of form submissions to users on My VA and confirmation page #1170](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170)  
- [ ] Think about when to start Collaboration Cycle/ start Design Intent

## Acceptance Criteria
- [ ] Validated designs for ways to help Veterans keep track of their claims post-submission
- [ ] Share early designs with VBA

**Comment by mengA6** [comment]
@shannonkford tagging you for visibility on this going forward

**Comment by mengA6** [comment]
Need to update this based on [Submission + Post Submission Experience doc](https://docs.google.com/document/d/19H0ZQadc2iPJaK4qasgaLEdnTKbAfrFYH__VhbT_fl8/edit)

**Comment by mengA6** [comment]
[Figma file](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/Submission-Experience?node-id=0%3A411&t=teopQQR1Hw8HdP3Z-1) (in-progress)

**Comment by mengA6** [comment]
Had an in-progress discussion with Evelyn and need to incorporate [these notes](https://dsva.slack.com/docs/T03FECE8V/F068SQT00MC?focus_section_id=temp:C:fcI8b52553e87254b8da19ae3c90)

**Comment by mengA6** [comment]
This round of design is complete [in figma](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/Submission-Experience?node-id=0%3A411&t=xXNahkt60Wn0sOOX-1). There are a few variations, but I could use feedback and/or research to narrow them down.

Also I submitted this [CAIA intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83554).

**Comment by mengA6** [comment]
moved a portion of this ticket "Appearance and behavior of in-progress forms after submission, per Map future state solution for reducing duplicate submissions #82511" to [Detailed design for ancillary job failure in submission experience#82095](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/82095) since we should have the input from [Map solution for reducing duplicate submissions](Appearance and behavior of in-progress forms after submission, per Map future state solution for reducing duplicate submissions#82511) when we begin it.

**Comment by mengA6** [comment]
I created [Revise Detailed design for success path and successful backup path of submission experience#83764](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/83764) to capture narrowing down the variations created in this ticket and some additional next steps
