### ISSUE TITLE
Short term: stop silent ancillary job failures

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#78187]
## Issue Description

From [OCTO prioritization spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B32235514-459E-48F0-AC07-90B1676B0DD7%7D&file=526%20Prioritization%20Scoring%20-%20Feb%202024.xlsx&action=default&mobileredirect=true)

Reduce root cause errors with FE validation, etc. But also consider/implement user experience va.gov / front-end changes or email notification to notify when failures happen instead of them being silent.

See [feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Submission%20Experience.md) for problem statements of the larger initiative.

Related: [Design for deleting an uploaded file #63414](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/63414)

**Team Carbs is working on some aspects of this separate from this ticket**
---
## Tasks
- [x] Investigate scenarios under which silent evidence upload errors can happen and what information the system can get back about them
    - [x] Ask stakeholders who have relevant knowledge
    - [x] Investigate solutions / plans of other teams who have worked on similar issues
    - [x] Review logs?
- [ ] Explore options for validation to prevent some failures
- [ ] Design notifications for error cases we can't prevent with validation
    - [ ] Alerts
    - [ ] Emails, if appropriate

## Acceptance Criteria
- [ ] List of scenarios under which silent evidence upload errors can happen 
    - [ ] Stakeholders confirm the list is complete - to their knowledge
- [ ] Design to handle all known and anticipated cases of evidence upload failures

**Comment by mengA6** [comment]
@shannonkford tagging you for visibility on this going forward

**Comment by mengA6** [comment]
Need to update this based on [Submission + Post Submission Experience doc](https://docs.google.com/document/d/19H0ZQadc2iPJaK4qasgaLEdnTKbAfrFYH__VhbT_fl8/edit)

**Comment by lisacapaccioli** [comment]
@NB28VT Do you think we can close this?

**Comment by lisacapaccioli** [comment]
Handled through 81612 Document Upload Failure Notifications
