### ISSUE TITLE
[FSR] Update FSR to use new minimal header/footer and uswds segmented progress bar

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#78194]
## Description

Enter a detailed description of the work - gherkin syntax below is acceptable.

Given: A veteran requests help with their copay/overpayment debt
When: Views the FSR
Then: They should be able to see a focused version of the form with a simple header and footer and updated progress bar to match the USWDS

## Tasks
- [x] Update the [segmented progress bar](https://design.va.gov/components/form/progress-bar-segmented#examples---v3) to use the USWDS v3 version
- [x] Update the FSR to use the [minimal header](https://design.va.gov/components/header/header-minimal) and [footer](https://design.va.gov/components/footer/footer-minimal) across the form
- [x] Update the debt resolution library

## Acceptance criteria

- [x] Debt library header and footer component has been udpated
- [x] Each instance of the segmented progress bar and minimal header/footer components has been updated on the FSR figma file
- [ ] PO feedback received and any changes made from feedback 

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [X] Estimate Points
</details>

**Comment by josephrlee** [comment]
Design work has been done, but I need to annotate and document the changes better. 

Also, here is a [Slack convo on the minimal header](https://dsva.slack.com/archives/C01DBGX4P45/p1710359963697059) for reference. 

Also will need to bring FE in to have a conversation about feasibility. 

cc: @Tom-Davis @HeatherRienks @denisecoveyduc @mgleo @charlottecesana

**Comment by HeatherRienks** [comment]
@josephrlee - any updates on this ticket?

**Comment by josephrlee** [comment]
@denisecoveyduc, [can you take a look at this for your review](https://www.figma.com/file/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---Streamlined-Waiver?type=design&node-id=0-2355&mode=design&t=Emetq8S08M1RshV7-11):

It's just one screen, but the same pattern has been applied to the whole form except for the Intro page. I've added the minimal header/footer and changed all the previous `h3` questions to `h1s`. 

<img width="860" alt="Screenshot 2024-03-26 at 11 27 04 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/3646b451-c0fa-4fa0-92a4-b2017eaf00ec">

There's also [more guidance coming soon from platform](https://dsva.slack.com/archives/C01DBGX4P45/p1710361361867829?thread_ts=1710359963.697059&cid=C01DBGX4P45) on how to implement the "One thing per page" with the minimal header.
