### ISSUE TITLE
[FE] - Appointment sorting and timezone offset

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#78201]
## Summary
We are getting the timestamp for the start time in UTC from LoRota(which gets it form OH via vetext), we need to convert that to the TZ of the facility when we call the endpoint. The timezone is also in the payload from LoRota. 

This ticket is to create a utility that grabs the earliest appointment startTime from an array of appointments, then converts that to the offset of the timezone in the timezone field. Ideally this would be done when setting `facilitiesToFile` on the travel-mileage page. 

## Tasks
- [ ] create utility to find earliest time and convert to station tz
- [ ] utilize utility when setting the appointment/facility selection into redux
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
merged and moving to closed since there is nothing to validate from UX or product
