### ISSUE TITLE
Tech Discovery - Does 526 know when an uploaded file is deleted

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#78203]
## Issue Description
Originated from [Accessibility Feedback ticket: Delete button removes upload without user confirmation](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59263), which gave two recommendations:

Will the API return what is needed to implement the design?
  
Design in [Design for deleting an uploaded file](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/63414).
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Check if the current implementation allows for this update
- [ ] Identify external dependencies, if any
- [ ] Review need for design update
