### ISSUE TITLE
General copy edit of VA style guide

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#78236]
## Issue Description
We need someone to go through the full [content VA style guide](https://design.va.gov/content-style-guide/) and check for these things: 

- links work
- there's no passive voice
- language and formatting is consistent 
- no errors or omissions 

---
## Tasks
- [ ] Copy edit style guide (ST)
- [ ] Enter suggestions into a PR (ST)
- [ ] Review PR and merge (MZ/BP)

## Acceptance Criteria
- [ ] Copy edit is complete

**Comment by laurenvocke-va** [comment]
Closing this old ticket
