### ISSUE TITLE
NEW FOR 3/20/2024 UPDATE: Redis Update: Coordinate removal of downtime banner after Prod environment is complete

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#78264]
## Issue Description
Per Grace at CMS: 
Laura Willwerth from Sitewide CAIA is managing the adding and removal of banners. CMS ticket for 7am Wed [here](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3027238994/3+20+2024+Redis+Upgrade+Runbook)

---
## Tasks
- [x] The downtime banner is deployed successfully
- [x] The Redis upgrade to Prod environment needs to be completed within the allocated time window
- [x] The Sitewide CAIA team will remove the banner after 7am eastern time on Wednesday 3/20/2024

## Acceptance Criteria
- [x] The downtime maintenance banner will be removed after the upgrade in the PROD environment is complete.

**Comment by jennb33** [comment]
Confirmed with Sitewide CAIA that the downtime banner has been removed as of 10am on 3/20/2024 see Slack thread [here](https://dsva.slack.com/archives/C01K37HRUAH/p1710942751866489?thread_ts=1706631681.822679&cid=C01K37HRUAH)
