### ISSUE TITLE
Cheryl Evans: Shadow Content Teammate(s) for Weekly Deployment

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#78271]
Content Teammate Cheryl Evans will be added to the Content Daily Deployment rotation. As a new team member, Cheryl will shadow 1 or more current teammates on daily deployment to learn the process.
NOTE: Cheryl Evans OOO April 1-5, 2024
 
## Tasks

- [x] Assign days for Cheryl to deploy alongside teammates
- [x] Create 3 tickets, each for 1 day of deployment shadowing with a team mate
 
## Definition of Done

- [x] Cheryl ready to run deploy alongside teammate

**Comment by jknipes** [comment]
Create ticket for each shadowing session (4 tickets, incl 1 for each team member)

**Comment by jknipes** [comment]
Making this a scheduling ticket and reducing estimate to 3 points. 
Deployment shadowing with team members will be on tickets 75431, 66416, 79511
