### ISSUE TITLE
Restrict Write Access for Datadog Monitors Managed by Terraform

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#78293]
## Problem

Datadog monitors in the datadog UI have diverged from their specification in our Terraform Code. This leads to "dirty Terraforms", which makes it difficult for developers to wade through changes in the monitors, in search of the one(s) that they actually want to work on.

Datadog monitors can have [restrictions placed on who can edit them](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#restricted_roles). We should add these restrictions to our Terraform code

## Tasks

- Create a read-only monitor or synthetic, with write access limited to the admin role, or no write access at all. You may need to "copy as curl" an api request in order to query the [Roles API](https://docs.datadoghq.com/api/latest/roles/#list-roles). The following was used by me and may help you get started: 
    ```
    curl 'https://vagov.ddog-gov.com/api/v2/roles?' --compressed -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'x-web-ui-version: 35.29385900' -H 'Connection: keep-alive' -H 'Referer: https://vagov.ddog-gov.com/dashboard/gfw-rwf-w5r/pact-act-second-cohort-9302023?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1707570538289&to_ts=1710162538289&live=true' -H 'Cookie: _dd_device_id=wlclmm36ie; datadog-theme=light; __zlcmid=1IHmBl9IXgPIzWD; dogwebu=b0fc00e72576554259ada1cebdfd3da79118be2e; dogweb=60bc14d7215c8b7babff8894f55383255f63995b3dcb092299c447448eb8f38fbe1f4b04' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' -o roles.json
    ```
## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [ ] A monitor has been created that can only be changed by terraform, or **at most** be changed by an admin
- [ ] The monitor can continue to be updated and changed with Terraform
- [ ] The monitor can be cloned by anyone and the resulting clone can be edited by the person/role that cloned it
- [ ] Additional issues have been created for migrating all Terraform-managed monitors and synthetics to be write-only

**Comment by jennb33** [comment]
@LindseySaari to review this ticket today and hopefully close by 12:45pm today

**Comment by jennb33** [comment]
Per @LindseySaari this is approved and can be closed. cc: @flooose
