### ISSUE TITLE
Execute setup of Recent Updates or Announcements space of FDG

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#78295]
**This is on pause, as we're not sure of its utility currently.**

This is intended as a page where teams can post their updated processes or announce things.  It was identified by our PO, and from our own review of the FD process.  Essentially, it would be nice if there was a place where teams could see the latest updates/changes to processes or resources involved in digitizing a form.

The expectation is that Platform teams themselves would submit such updates to a page within the landing.

The information and finding from [this exploratory work](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/70995) should inform this page/space.

## Tasks
- [ ] Create initial version of page
- [ ] Brainstorm HMW make it easier for teams to loop in SDT/post updates
- [ ] allow for SDT review
- [ ] update page based on feedback

## Acceptance Criteria
- [ ] Page is ready for inclusion on landing
