### ISSUE TITLE
[CST] Determine content revisions for CST intro page language to accurately convey what's in CST

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#78306]
## Value Statement
**_As a_** person who has landed on the CST intro page for any reason
**_I want to_** be able to read the content on the page and know exactly which types of claims will show up in the CST
**_So that_** I know I can rely on it to check the status of these things and not rely on it for claims and applications it can't provide information for.

---
## Background Context

[The CST intro page](https://www.va.gov/claim-or-appeal-status/) says a bunch of stuff and some of it does not appear to be true. For example, it suggests veterans can check the status of VRE claims, but the data coming out of DD does not suggest that's an application type that shows in the tool. We've been provided a massive spreadsheet ( [clm lbl.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14588645/clm.lbl.xlsx) )of EP codes and their descriptions and we also can pull DD logs that show exactly what EP codes and descriptions are actually coming through in the CST product.

One hypothesis is that claims processed through VBMS are able to be shown in the tool (for appeals Caseflow), but claims processed in other systems are not. This makes sense based on what we know about how the services upstream from CST function and connect to BIS and VBMS. If this hypothesis is true, we could identify which claim/application types get adjudicated in other systems and rule them out as types that can show up in CST. 

We should rely on VBA SMEs to help us investigate this, specifically Andrew Gray.

## Design
- Add here

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Map DD EP code data to spreadsheet to identify the finite claim types that actually are showing to users
- [ ] Verify whether only claims processed in VBMS can technically show up in CST
- [ ] Identify which claim types mentioned on the intro page don't actually show up in CST 
- [ ] Identify claim types that show up in CST that are not mentioned on the intro page
- [ ] Discuss results with enablement team
- [ ] Make recommendations on content edits

## Definition of Done
- [ ] Meets acceptance criteria

## Acceptance Criteria
- [ ] We have determined which claim types can show up in CST with 95% confidence and have documented what they are.
- [ ] We have determined which claim types CAN'T show up in CST with 95% confidence and have documented what they are.
- [ ] Based on what we know can and cannot show, we make specific recommendations for how to revise the content on the CST intro page to be more accurate.
