### ISSUE TITLE
Audit GA Custom Events

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#78300]
## Description
We've been asked by the Analytics team to audit the Custom Google Analytics events that we are capturing in our applications. In order to facilitate this request, we have been given a Google Sheet to use as a template to fill out for each of our applications

## Notes
Applications we need to audit:
* Claim Status Tool
* Benefits Letters
* Rated Disabilities
* View Payment History

Google sheets for each application have been created [in this folder](https://drive.google.com/drive/folders/1MNugJaCAyOf4aY9jg066JHdaSu3OHfF0)

We should probably export all of the spreadsheets as xlsx files once we are done so that the Analytics team can view them

## Tasks
- [x] Audit the custom events in the Claim Status Tool and fill out [the spreadsheet](https://docs.google.com/spreadsheets/d/1U_qmcVsjakqxJ3cg4xFSd3uJj78S-guwagCV1UqAET8/edit#gid=2087351809)
- [x] Audit the custom events in the Benefits Letters application and fill out [the spreadsheet](https://docs.google.com/spreadsheets/d/1ZLnU-BJaHZetc_aEDxehr4PsS54JlvbgFEH9igF365I/edit#gid=2087351809)
- [x] Audit the custom events in the Rated Disabilities application and fill out [the spreadsheet](https://docs.google.com/spreadsheets/d/14A9nbxyK8HwknOxglBh6BGFOvt8d6DF3uI1oYSZ215U/edit#gid=2087351809)
- [x] Audit the custom events in the View Payment History application and fill out [the spreadsheet](https://docs.google.com/spreadsheets/d/1CbJJFT_Yp0_t5tI7o8rH6gSK-kHAZ0r77cqKwuiz1TQ/edit#gid=0)
- [x] Create a ticket using [this template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D) and attach the spreadsheet for each application

## Acceptance Criteria
- [x] Spreadsheets have been created for all applications listed above
- [x] A Github Issue has been opened using the template mentioned above

**Comment by jerekshoe** [comment]
Created the issue for the Analytics team [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78867)
