### ISSUE TITLE
GA4: Confirm Web & Form Components in GA4

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78309]
### Description:
This task was broken out from two other tickets, of setting up Web & Form Component Tracking. This is to ensure that everything set up from those two tickets is displaying as expected within GA4.

**Tracker Spreadsheet:** https://docs.google.com/spreadsheets/d/1_t71Ea-Sxi_hxvK2lswAkn1BUC-JniZic70KUUZF5I4/edit#gid=0

### Tasks:

- [ ] For each Web component, test in GA4 and indicate in Column I whether it is displaying
- [ ] For each Form component,test in GA4 and indicate in Column I whether it is displaying

### Acceptance Criteria:

- [ ]  All Web & Form Components have been confirmed within GA4.
- [ ]  Compile any identified new tracking opportunities for future consideration/work

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt - as discussed over Slack, adding this task as a QA measure to validate the set-up of both the Web & Form components within the GA4 interface.

I added in some tasks, and AC, but please refine and provide an estimate to this.

**Comment by johnny-jesensky-adhoc** [comment]
Confirmation and refinement for Web and Form Components will be an on-going effort, and continue to be worked on next sprint, in this refinement ticket --> [Timeboxed GA4 On-going Refinement & Documentation Ticket]( https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/79389.)

FYI @jestutt
