### ISSUE TITLE
Travel: Create Final Wireframes for Eligibility Check

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#78319]
## Tasks
- [ ] Perform "desk research" as needed, to inform the work. E.g., is there DS guidance to review? Are there past research findings to review? 
- [x] Create final wireframes with content for Standalone BT App w/ Eligibility BG Check
- [x] Create any needed markup into Figma Page or frames for heading annotations, aria label values, link paths and/or GA Event values

### Who needs to review? Remove rows that aren't needed for this work.   
- [x] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [x] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? If Yes, provide details in comments. 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by cgednalske** [comment]
@benbrasso-agile6 @zach-park here’s the draft list I had done for the changes needed for adding eligibility to travel-only:
- Intro page - remove eligibility background info (and reconfigure)
- LoROTA - add “check if it’s you and make sure you’re eligible”
- Need totally new page for "We don’t think you’re eligible because... file anyway?"
- Need two versions of confirmation page - eligible and not eligible

**Comment by benbrasso-agile6** [comment]
@zach-park just ping me and we can kick this one off together

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske . Initial wireframes are ready for review.
https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=2122%3A4192&mode=design&t=wiCR5sm7HYycAeL0-1

**Comment by benbrasso-agile6** [comment]
@cgednalske do you want to take a look for validation here? I know you saw it, but don't forget that we should compare this work to the work we did for [adding eligibility into eCheck-in](https://www.figma.com/file/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-Check-in?type=design&node-id=3347%3A295&mode=design&t=10o1rmrD1908AtDq-1) and ensure there's some consistencies, where appropriate.

**Comment by cgednalske** [comment]
👍 Added some comments!

**Comment by zach-park** [comment]
@cgednalske @benbrasso-agile6. The iterated version is available now on:
https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=2122%3A4192&mode=design&t=Z97cJbSTx9tM5V0K-1

**Comment by zach-park** [comment]
Request sent for FE engineering review.

**Comment by loripusey** [comment]
@zach-park do we need engineers to review this right now? It may be 9 mos. to a year before we implement this; if @benbrasso-agile6 or @cgednalske has looked at it then I would close the ticket

**Comment by zach-park** [comment]
Hi @loripusey , we informally reviewed it with our engineering team via slack channel asynchronously. UX team just finished the validation as a team, and the ticket is ready to be closed. Thank you!

**Comment by benbrasso-agile6** [comment]
Yep, good w closing
