### ISSUE TITLE
Usability Testing Prep - GIBCT, Sec 103

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#7831]
## Steps to complete Usability Testing Prep: 
- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/product-outline.md)
- [Link to prototype](https://bahdigital.invisionapp.com/share/7NIADE8GMJ2)
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/research/research-plan.md) and [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/research/discussion-guide.md)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- [Test cases/test plan in TestRail](https://dsvavsp.testrail.io/index.php?/suites/view/24&group_by=cases:section_id&group_order=asc)  _for QA practice area review_

## Meeting attendees from Booz Allen
- Product Manager (required): Darrell Neel
- DEPO product lead (required): Matt Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): Cindy Cruz, Jen Jones, Amy Knox, Desiree Turner, Will McCormack

## Scheduling
Preferred dates or times: 
April 14, 10am - 11:30am; 2-2:30pm

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by meganhkelley** [comment]
Scheduled for 4/14

**Comment by CrystabelReiter** [comment]
We discussed about using staging to test with screenreader users. If design isn't in staging by time of testing, feel free to use another section that replicates the same interaction. No feedback ticket needed. This is good to go from the VSP design side.

**Comment by peggygannon** [comment]
I've reviewed this content earlier and have no additional content feedback at this time. It's good to go from the VSP content side.
