### ISSUE TITLE
Discovery: Speedcurve

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7832]
Problem Statement
How might we maximize Speedcurve to evaluate Facility Locator's performance?

## Goal
Leverage the tool available
Provide feedback to VSP 
---
## Tasks
- [ ] Explore Speedcurve functionality
- [ ] Understand display options
- [ ] Evaluate notifications

## Acceptance Criteria
- [ ] Determine metrics for different searches, from the front end perspective
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
