### ISSUE TITLE
eCheck-in: Create Final Wireframes for Eligibility Check

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#78320]
## Tasks
- [x] Identify pages that need changes
- [x] Perform "desk research" as needed, to inform the work. E.g., is there DS guidance to review? Are there past research findings to review? 
- [x] Create final wireframes with content for only pages that need changes eCheck-in w/ Eligibility BG Check. (Created [Figma page](https://www.figma.com/file/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-Check-in?type=design&node-id=3347%3A295&mode=design&t=yxrz7Y7OlDxeGzSr-1) for this work.) 
- [x] Create any needed markup into Figma Page or frames for heading annotations, aria label values, link paths and/or GA Event values

### Who needs to review? Remove rows that aren't needed for this work.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [x] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [x] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? If Yes, provide details in comments. 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by zach-park** [comment]
@benbrasso-agile6 (Cc: @cgednalske ). Wireframe is ready for review:
https://www.figma.com/file/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-Check-in?type=design&node-id=3347%3A295&mode=design&t=1xpgIAoSKlGTggfY-1

**Comment by benbrasso-agile6** [comment]
Thanks Zach, will take a look tomorrow.

**Comment by benbrasso-agile6** [comment]
@zach-park looks good; made a few suggestions. Take a look in Figma. Also, forwarded you DS Office Hours invite for next Tuesday.

**Comment by zach-park** [comment]
Validated with @benbrasso-agile6. Next step: share with Design Office Hour with VA Platform team.

**Comment by zach-park** [comment]
**### VA Platform Meeting Note:**

**File BT page**

- _Recommendation:_ Unsure version: Consider the alert type to info. alert type so that it doesn’t alarm the user.

- _Suggestion:_ Screen reader: Mobile is fine, but for desktop, there is an edge case that the user may navigate through using the laptop keyboard (using the tab key to navigate). It may skip some content to the Yes/No (Skipping the middle part like the Alert component).

- _Suggestion:_ Content tweak to Consider changing the test of “Would like to…” to based on user’s eligibility instead of the same headers

**Confirmation page**

- Suggestion: The active link is fine. If a more prominent hierarchy is needed, an Action link is also possible.

- _Question:_ Content-related question from Alison: Do we work with KAIG(?) for content? - Alison said that she would reach out Ben to follow up.

**Comment by benbrasso-agile6** [comment]
Thank, Zach. I made this change:
File BT page
Recommendation: Unsure version: Consider the alert type to info. alert type so that it doesn’t alarm the user.
I'll catch Laura to talk about this one:
Suggestion: Content tweak to Consider changing the test of “Would like to…” to based on user’s eligibility instead of the same headers
Actually, I think I'm going to just tag her in Figma to see if we can get some quick eyes.
