### ISSUE TITLE
[UX][Research] SPIKE: Determine research to pursue 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#78323]
## Tasks
- [ ] Identify most value for researching/testing; keeping in mind that each of these may be its own mini research effort
    - Review page
    - Travel eligibility
    - Identify design patterns, userflows and/or concepts that we want to understand Veteran responses to. E.g., "edit" or "start over" link, etc. 
- [ ] Identify research type. E.g., usability w/ prototype. 
- [ ] Get feedback from appropriate stakeholder(s).

**Comment by cgednalske** [comment]
@loripusey @benbrasso-agile6 @zach-park this ticket is ready for validation

- [Discovery document](https://docs.google.com/document/d/1If6LEHPCkSNXppt5fsu2iUy5mLXbTuybcwOSPMkJ0GY/edit#heading=h.e1khg2se5xfy) around Check-in research ideas. (Below is the part of interest we're focusing on.) 
- Met with UX and Kristen and determined an unmoderated study is a helpful, lower-lift research approach to answer questions around Veterans' understanding of content on the multiple facilities page. 
- Other questions around eligibility and the review page editing can be incorporated into on-site research. 
- Next step: [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78654) for an unmoderated study


------
# Evaluate Veterans' understanding of content / instructions

- Multiple facilities page
- _(maybe Intro page or Confirmation page)_

## Format options: 

- **Moderated**: show 2 CodePen screens, asks questions
  - Accessible
  - Allows folks to open the additional info components and find that info

- **Moderated**: shows 2 design screens, ask questions
  - Not accessible

- [**Unmoderated**](https://www.youtube.com/watch?v=X-_97oL35fg): show facilities screen + questions, then confirmation screen + questions
  - Note: not sure if unmoderated is accessible
  - Takes up less UX time if we cannot be available for a full study
  - Could have a CodePen link for folks go through it themselves if they can't see the image

- **Any of the above**, but showing a short flow rather than individual screens
  - Facilities screen > placeholder for travel questions > Confirmation page

## Questions:
1.  Do Veterans understand if this is for mileage-only or receipts?
2.  Do Veterans understand what happens to the facilities they select vs. what they don't select? 
3.  Do Veterans understand how to file for the facilities not selected?
4.  Do Veterans understand when they can file using this tool and when they can use BTSSS?

## Example of unmoderated setup:

_We'll ask you to review some screens around filing for travel reimbursement.\
Please review the screens and answer the questions. The more information you include..._

_If you cannot view the image, select this link to review..... (CodePen)_

![](https://lh7-us.googleusercontent.com/duQTHzz8sxJCMq7hT_vlyxCOK8PmRerUVvNXagjdcOCXlU5VzEhuz-qLcnkTnm6v41JRsS5O-dHEbzyIxfAQt2XiVgg8YYQxfbfU2muZ5m22LI1eVQ6PRTdhfQGwPMX3FqfqMWaVdacPf-use4W0tDQ)

**Review facilities page questions** 

- _What type of claims can you file with this tool?_
  - _Claims including receipts_
  - _Mileage-only claims_
  - _Both_
  - _(+ comment box)_

- _What happens to the facility appointment that is selected?_ 
- _What happens to the facility appointments that are NOT selected?_
- _If you wanted to file a claim for the facility appointments (later) that are NOT selected, how would you do that?_

**Comment by benbrasso-agile6** [comment]
Oh, thanks for reminder. I was going to create the create study ticket too. LGMT, thanks Christina

**Comment by benbrasso-agile6** [comment]
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/79195
