### ISSUE TITLE
Add bank account summary information to confirmation screen

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#78346]
## Issue Description
We're adding an alert to the confirmation page to inform applicants that the bank account information they entered will be used for any education benefits they use as well. 

## User story
As a Veteran, I want to see what bank account information I entered on the confirmation screen so that I don't have to remember what I entered on a previous screen and I can easily double-check if I'm using a different account for education benefits.

---
## Tasks
- [ ] Explore how whether other form teams have implemented a solution for this
- [ ] Create updated design for confirmation page that includes a summary of what bank account information was provided in the form

## Acceptance Criteria
- [ ] Updated Figma design for confirmation page
- [ ] Approval from CAIA

**Comment by gmaciolek** [comment]
Made some updates to the [Confirmation page in Figma](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=3079%3A5253&mode=design&t=a9unfaq4YT5iYnPd-1)

Included a placeholder sentence in case we want to say something about how to double-check the account info for their education benefits or how to update bank account info. (I think we would need different language for the authenticated/unauthenticated version)

Adding to design sync agenda for Monday.

**Comment by gmaciolek** [comment]
The [Figma design for the confirmation screen](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=3079%3A5253&mode=design&t=Co8bJZ8DfB0IGQah-1) has been updated with changes. This is ready for an engineering ticket. 
Summary of changes:

- Added a n h3 for "Direct deposit account information"
- Updated the direct deposit alert title and copy
- Changed the alert title to an h4
- Added bank account information below alert plus some additional copy explaining where to view your direct deposit information

Developer note:
The Direct deposit account information heading and section should only display if the applicant provided direct deposit information. See note in the annotated Figma.
