### ISSUE TITLE
Backup 'Scheduling Settings' in Domo for UA-based datasets

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78348]
### Description:
This task is to ensure that all of the old UA queries are appropriately backed up. This will be crucial in advance of testing, in case we need to revert any changes.

**Document:** [GA4 migration - Domo datasets dependent on BQ](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=0
)

---
### Tasks:
- [x] For each dataset within Domo, record the following information
- [x] Update interval
- [x] On this day
- [x] Start between
- [x] Update method

<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDcrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47c05e26798c5760fc428c6ec9c3c77afc61fcb5/image.png" alt="image.png" />

### Acceptance Criteria:

- [x] All of the scheduling information has been captured in each data set, in this spreadsheet, (in Column J)

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 - this ticket is currently in our backlog, but imagine this would be a good pick-up for @Blivaditis or @ChristineYoungZA if they finish their current sprint work up early. 

Can you review the description, tasks, and acceptance criteria on this to reflect what exactly will be needed to back-up these queries within Domo?

**Comment by johnny-jesensky-adhoc** [comment]
JJ reviewed and confirmed back-ups for datasets with GA data that we can access -- moving this to _**Done**_.

FYI @ChristineYoungZA, @Blivaditis
