### ISSUE TITLE
Design discovery for adding additional context for sensitive questions

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#78357]
## Issue Description
We ask questions throughout the form that may seem intrusive or off-putting for applicants without adding additional information about how we use their responses/why we need the information.

Examples:
- What's the reason you're separated from your spouse?
- What's your relationship to your child?
- Have you ever been a prisoner of war?

---
## Tasks
- [ ] Review form questions and identify any potentially delicate/sensitive questions
- [ ] Cross-reference list of questions with insights from research/usability testing
- [ ] Explore design solutions for how to present information relating to why we need/How we use this information
- [ ] Review with Katherine/CAIA

## Acceptance Criteria
- [ ] List of delicate questions that we should add more information for
- [ ] Design prototype for how to display information in different scenarios e.g., when it's the only question on the page, when it's one of many, etc.
---
