### ISSUE TITLE
Add TIC Incident Management to Incident Playbook

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#78356]
## Description 
When issues with the TIC gateway occur, like increased latency or an outage, a significant disruption to vets-api and subsequently va.gov's functionality can occur. This is an immediate issue the team must respond to, and the resolution is to investigate with Network Edge Operations (NEO) on the VA-side.

The NEO team has recommended that in the future, in lieu of a SNOW incident ticket, we should contact the NEO directly via Teams to attempt to troubleshoot during the event. Ty Allinger has been pointed to as the POC, and we need to update the [Incident Playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook)

---

## Definition of Done
The Incident Playbook includes instructions for managing a TIC-related incident

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Verify process for TIC-related incidents
- [x] Update [Incident Playbook](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook) with information
- [x] Add launched item to the [Launched S
upport Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
<img width="1161" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlBhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cc3c112147df09e820cf8238f8f99e856774878/Screenshot%202024-03-13%20at%201.41.16%20PM.png" alt="Screenshot 2024-03-13 at 1.41.16 PM.png" />

---

**Comment by lindsay-insco** [comment]
Incident Playbook updated
