### ISSUE TITLE
Copy of CH36 Form Name Changes

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78359]
## Issue Description
- Form number changed from 28-8832 to 25-8832
- Ticket relates to other form updates in #61721 
- [Additional Notes ](https://docs.google.com/document/d/1tZejPPUbRaDt162ZETL6_VJ2Ydi0zruV6zpPYlyHWgU/edit?usp=sharing)on form changes and requested enhancements.

---
## Tasks
- [ ] Update CH36 form flow pages with new form number (from 28-8832 to 25-8832) based on documentation from #62284 
   - Places and documents where form 28-8832 was mentioned: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691071311991/35dcc1ac49a00c2c034905342f28643b97b39c26?wid=140-1691071382104
   - **Designs:** https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691071311991/35dcc1ac49a00c2c034905342f28643b97b39c26?wid=118-1691071382104 | [Sketch](https://sketch.com/s/d78c4168-3ef3-46e3-ab64-a674786182cb)
- [ ] Update [introduction page](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) with new form number (25-8832).
- [ ] Add language to the intro page stating that form 25-8832 was formerly 28-8832 (see [Sketch](https://www.sketch.com/s/d78c4168-3ef3-46e3-ab64-a674786182cb/p/1C43D9CF-316E-4568-91D9-E153514FB830/canvas))
- [ ] Update [apply pages](https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction) with new form number (25-8832)

## Acceptance Criteria
- [ ] All instances of 28-8832 have been changed to 25-8832 on CH36 intro page
- [ ] All instances of 28-8832 have been changed to 25-8832 on CH36 apply pages
- [ ] Language stating form number change added to intro page

**Comment by zack** [comment]
Compiling information I received from @DLarson-Oddball and @jerekshoe here:

In order to complete this task, we're going to need to take a number of steps:

1) Create a new schema in [vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema) for the new application.
1) Create a copy of [the application in vets-website](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vre/25-8832). Don't forget to update the [manifest.json](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vre/25-8832/manifest.json) file. I think this is where we'll want to update vets-website to point to the new vets-json-schema commit?
1) In [content-build registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), create a new entry for the new application.
1) Deploy content-build and make sure everything's working correctly.
1) Somewhere around here we'll want to change all of the references in vets-website, but I'm not exactly sure when that needs to happen. There are lots of references *outside* of the application to the form name, like test files, links, etc. See the changes in the PR in the note at the bottom of this comment.
1) Submit a [request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15219) to create a redirect so that anyone who goes to the old URL will be forwarded to the new URL. Make sure this works for in-progress forms.
   1) Note from Dakota: "We had issue with child pages not following the redirect initially, so it would be good to ensure child pages are covered as well when they roll out the second redirect."
1) The old application, schema, etc. can all be removed.

**NOTE**: There are still a large number of references to '28-8832' in the codebase and these will also need to be updated to the new for name '27-8832'. See a draft of this work here: https://github.com/department-of-veterans-affairs/vets-website/pull/28545.
