### ISSUE TITLE
Discovery: Mashup of Community Care/VA facilities in search results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7835]
## User Story or Problem Statement
As a Veteran, I want to see VA facilities and Community Care locations returned together as search results so I can find the location closest to me.

## Goal
See all search results returned in single list

## Objectives or Key Results this is meant to further
- Objective 2: Deliver meaningful facility information 
KEY RESULT: A user can find VA and Community urgent care providers with one search by June 30, 2020. 

---
## Tasks
- [ ] Evaluate options for returning results from PPMS and VA facilities together to single search by user 

## Acceptance Criteria
- [ ] Recommendation for best option to return results to user containing both Community care and VA facilities together **without adversely impacting performance**

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
