### ISSUE TITLE
DR | Inventory Google record event

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#78361]
## Value Statement
**_As a_**  Benefits Decision Reviews team developer
**_I want to_** inventory our `recordEvent` actions
**_So that_** platform has an accurate list of analytic events that need to be updated to GA4

## Background Context

[Platform requested all teams to inventory use of `recordEvent`](https://dsva.slack.com/archives/CE4304QPK/p1710258944850399)

> As part of the Google Analytics transition to GA4, we ask that all VFS Teams create and share an inventory of any and all recordEvent actions currently living in their codebase -- also known as custom events.
> - Why is this needed? Due to the nature of custom events, the only way to ensure these events are transitioned properly for GA4 is for teams to tell us about the events.
> - What do I need to do? An event inventory/audit template spreadsheet has been provided as part of this [Github Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D). Please download the spreadsheet and complete as much as you can, then submit it with the Github form. The same spreadsheet will be used to track progress and confirm your events in GA4. Instructions are provided within.
> - When is this due? We'd like for teams to submit the [Github form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D) no later than Friday, April 5. Forms submitted after this date will still be transitioned, but we risk gaps in metrics and reporting the closer we come to the 1 July 2024 UA cut-off date.

## Tasks
- [ ] Search Decision Review apps for `recordEvent`
- [ ] Record usage in spreadsheet
- [ ] Submit completed spreadsheet 

## Acceptance Criteria
- [ ] Review complete
- [ ] Spreadsheet submitted

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Spreadsheet submitted with acknowledgement

**Comment by Mottie** [comment]
Work done in #79710 - see attachments

**Comment by Mottie** [comment]
@saderagsdale We can close this ticket.
