### ISSUE TITLE
[Design] 10-10EZ - Reg Only: Feature prioritization matrix

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#78360]
## Background
After conducting a couple research sessions, getting a better understanding of how the staff works through the Reg Only process, and obtaining volumes of various Registration Only scenarios (Service Connected & Mental Health), we have a better idea of how we would like to approach adding the Reg Only path to the 10-10EZ.
We want to create a prioritization matrix for registration-only features so we can determine as a team what the MVP will look like and what other features we'd like to incorporate down the line. This will assist with roadmap planning and designing initial wireframes for registration.

- [Planning Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702079427539/3151e3fa9a7eed55d21d5e39cb981938c5d2484a?sender=uadf1ed7fe7c76f0914967329)
- [Figma blank page setup](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=86-36817&mode=design&t=JwZY1vr9IwWyhBez-0)
- [Wireflow exploration Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696891719955/7e17ac86124fb9dcc6322be634ccdc4e8eb00a0a?sender=uadf1ed7fe7c76f0914967329)

## Tasks
- [x] Create prioritization matrix Mural board - Angela
- [x] Populate proposed features as stickies on Mural - Angela
- [x] Workshop session with UXers to prioritize features
- [ ] Share with team and Kristen for feedback
- [ ] Incorporate any feedback

## Acceptance Criteria
- Prioritization matrix for the Reg Only pathway is completed and the team is ready to move on to MVP wireframes.
- MVP features have been outlined and approved by Kristen and team
