### ISSUE TITLE
Research: Connect Platform Support Responses Sheet to DOMO

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78368]
## Description 
We want to connect the Support Bot Spreadsheet to DOMO. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Research the exact steps we need to perform to integrate our Platform Support Responses Sheet to DOMO
- [ ] Create a new ticket for the execution of that work with those exact steps
- [ ] Divide the work between the two of you to accomplish the tasks (stories should be less than 5 points per ticket)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
duplicate of https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/78367
