### ISSUE TITLE
Update Review & Submit screen for toxic exposure

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#78372]
## Issue Description
per [Toxic Exposure: Gulf War Hazard 1990 Date Ranges#73848](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/73848), we learned that the review & submit screen at the end of the 526 flow has repetitive headings for the date range sections that are something like "Service after August 2, 1990" for each location. That is, the heading doesn't indicate the actual location like "Afghanistan".

How might we make the information more clear on the review & submit screen?

<img width="584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3piQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09562b1404d283fc9c5baccaaaf104e79fe44827/image.png" alt="image.png" />

---
## Tasks
- [x] Discuss with CAIA the approach to use - possibly from a previous version
- [x] Update design file
- [x] Review with team
- [x] Create implementation ticket or add it to an existing implementation ticket

## Acceptance Criteria
- [x] Above tasks completed

---

**Comment by mengA6** [comment]
cc @christinec-fftc so that you stay in the loop on this

**Comment by Kate-allbee** [comment]
Reached out to CAIA on 3/19 for help on this issue, their team is currently at capacity and communicated that they wouldn't be able to pick up the ticket till this week sometime. 
[Thread here](https://dsva.slack.com/archives/C01K37HRUAH/p1710890057586539)

They are nesting a ticket for this under the existing one. 
[Link Here ](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/71168)

**Comment by Kate-allbee** [comment]
Changes logged in [figma file here](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=1263%3A82673&mode=design&t=8tOFhAxI8dWg6SQN-1)

**Comment by Kate-allbee** [comment]
Slack thread confirming use of word hazard vs. other exposures
https://dsva.slack.com/archives/C01K37HRUAH/p1712262637695049
