### ISSUE TITLE
[Research] VA.gov Onboarding: Research Logistics & Kickoff

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#78374]
## Background
Liz drafted the research plan and convo guide in #78147. This ticket covers the next steps to kickoff the research.

## Tasks
- [x] Submit research plan
- [x] Meet with Perigean to discuss recruitment criteria
- [x] Confirm recruiting has been kicked off
- [x] Run pilot session
- [x] Make any updates that come out of pilot session
- [x] Create observer Mural board
- [ ] Complete any other steps needed to prepare while recruiting takes place

## Acceptance criteria 
- [x] we're ready to run the study
