### ISSUE TITLE
686 Updates | Sent test claim through staging

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78380]
## Summary
In order to launch phase 1 changes, we need to send test claims to downstream systems (CRM, Share, RBPS) to ensure 686 claims process as expected.

## Tasks
- [ ] Connect test environment to staging/LinkTest environment
- [ ] Send test 686 claim through LinkTest (maximal/kitchen sink)

## AC
- [ ] 686 test claim sent through LinkTest

**Comment by tblackwe** [comment]
We are setup by default in staging to send to linktest

This ticket is now to determine how to connect local or a staging review instance to linktest.
