### ISSUE TITLE
Spike | Map IDs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78386]
## Issue Description
_Across our forms, Veterans are shown several different types of IDs, but its unclear how/if these IDs are related and how to map them to each other and other common VA ID numbers. This spike will identify what IDs each form shows users and identify what IDs map to each other._

---
## Tasks
- [ ] Document what IDs each of the following forms shows the user (e.g. claim ID, submission ID, reference number):
   - Dependents 21-686c and 21-674
   - Chapter 31/VR&E/28-1900
   - Chapter 36/PCPG/25-8832
   - Burial 21P-530EZ
   - COE/LGY/26-1880
 - [ ] Map how each ID is related to other VA IDs (ssn, UUID, etc.)

## Acceptance Criteria
- [ ] A map of all form IDs and how they are related
---

**Comment by mjknight50** [comment]
Some initial work here:
https://docs.google.com/document/d/1qUt_bLTIeFAiN0jOsI0CHOEHX0d1iqgo2veorsyFUhI/edit
