### ISSUE TITLE
Research facility operating status 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7838]
## User Story 
As a Veteran, I need to know when a facilities access or services have been impacted by an emergency so that I can adjust my plan to visit.

## Goal(s)

- Collect Veteran feedback on the current facility operating status options in use on VAMC pages and displayed within the Facility Locator
- Assess Veteran understanding of the status options in use
- Assess Veteran understanding of additional details/info available in operating status notes

## Questions to consider
**Veteran journey**
- [ ] Do Veterans want to know if a location has altered access or availability during an emergency?
- [ ] How do Veterans expect to learn the information?
- [ ] What details do Veterans expect to learn about the change in facility availability?
- [ ] Are the operating status currently in use meaningful to Veterans? 
- [ ] Do the operating notes assist Veterans in understanding?
- [ ] Which category do Veterans expect to see when a facility is closed to in-person visits but offering services remotely (virtual or telehealth)?
- [ ] How can we best convey changes to facility/service availability resulting from urgent vs planned scenarios? 
- [ ] How can we best convey changes to facility/service availability which will be temporary vrs long-term? 

## Objectives or Key Results this is meant to further
- Objective 2: Deliver meaningful facility information 

---

## Tasks
- [ ] Determine best research method to collect this information quickly 
- [ ] Develop research plan (and conversation guide, if needed for method selected) to assess Veteran response to display of VA facility operating status

## Acceptance Criteria
- [ ] Approved research plan (and conversation guide, if appropriate)
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@davidconlon to assess Veteran feedback on the VAMC pages, should we be recruiting Veterans within the Pittsburgh health care system?
