### ISSUE TITLE
Reinstate BigQuery uploads for coverage data

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#78388]
## Issue Description
Had to remove this due to permissions errors while fixing the coverage report. Storing this data will help us automate code coverage requirements in the future so this should be reenabled as soon as we can to start tracking data again.

---
## Tasks
- [x] Reenable code coverage BigQuery data uploads
- [x] Correct any errors preventing the upload of data from taking place
- [x] Verify that data run in CI makes it to the appropriate table in BigQuery

## Acceptance Criteria
- [x] Data is being stored in BigQuery for Unit Test code coverage in each CI run.
