### ISSUE TITLE
Add PII Filter to Identity-Slackbot

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#78391]
# Description
In order to prevent users from exposing PII/PHI in the form inputs of the identity-slackbot, a PII filter should be applied to all user-supplied data.

# Tasks
- [x] research a reliable npm package to filter sensitive data
- [x] apply filter to all user input
- [x] add tests to cover filtering behavior
