### ISSUE TITLE
Converting to role based AWS access

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#78395]
## Description
Transition the current AWS access management to a role-based model. This involves creating AWS IAM roles with specific permissions for different operations within the GitHub Actions (GHA) workflows, enhancing security and scalability.

---

### Tasks
- [ ] Identify the minimum necessary permissions for each operation in the GHA workflows
- [ ] Create IAM policies that encapsulate these permissions
- [ ] Set up IAM roles and attach the created policies to these roles
- [ ] Update GHA workflows to assume the appropriate IAM roles when accessing AWS resources

### Acceptance Criteria
- [ ] IAM roles and policies are correctly defined and implemented
- [ ] GHA workflows successfully use role-based access when interacting with AWS resources
- [ ] No workflow has broader permissions than required for its operation

**Comment by pjhill** [comment]
This looks like general retrofitting of GHA workflow access control that is not limited to PE work, but is a prerequisite for being able to create the roles that make sense for managing PEs. So, when I read "GHA workflows use role-based access when interacting with AWS resources" -- I'm think that we are going to need to regression test some GHA workflows that are using AWS resources. Is the end state here to have the whole org's GHA workflows moved into this paradigm?

**Comment by IGallupSoCo** [comment]
My understanding is that this would be a complete replacement.  The goal was CI/CD efficiency, right?

Are there any hacky implementations in Platform GHA that may have trouble with this transition?
