### ISSUE TITLE
Round decimals in unit test coverage report totals line.

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#78390]
## Issue Description
On the unit test coverage report the totals line has a decimal that's not rounded.  For ease of reading, all numbers should be rounded to 2 decimal places on this report.
---
## Tasks
- [x] Implement rounding to two decimal places to all numbers on the unit test coverage report.
- [x] Publish a new report to test that the solution has taken accordingly.

## Acceptance Criteria
- [x] All numbers on the unit test coverage report are consistently formatted across the entirety of the report.
- [x] All numbers are rounded to two decimal places and easy to read.
