### ISSUE TITLE
Update how-to-launch survey page

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#78398]
## Purpose
Update the [how-to-launch page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Quarterly+Platform+Services+Satisfaction+Survey) as our process has changed and new pieces have been introduced (domo, survey leaderboard).

## Tasks
- [x] Update domo process
- [x] Update any messaging process
- [x] Update any additional survey leaderboard process
- [x] Update communicating + presenting results

## Acceptance Criteria
- [x] Page is updated
