### ISSUE TITLE
Medallia 2.0 A11y - Discuss accessibility audit recommendations with VSignals team

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#78405]
## Issue Description

As an engineer working with the VSignals team to implement the new Medallia setup, I want to collaborate effectively with the VSignals team to address the critical and major accessibility issues identified in [CAIA a11y audit](https://docs.google.com/spreadsheets/d/1Z_xXH2WnyP0YWNCJFKs0duwgSIug9VNEmzWR9RzxSYM/) of the first two forms in our new Medallia 2.0 setup (form 29 and 41). Our goal is to ensure that these forms are fully accessible and compliant with Platform accessibility standards.

---
## Tasks
- [x] Discuss removing `aria-required` attribute from H2s
- [x] Discuss submit/cancel button tab order (row 2)
- [x] Discuss adding alt text for VA logo on welcome and thank you pages

## Acceptance Criteria
 - [x] **Scenario: Discuss accessibility audit recommendations with VSignals team**
   - Given the VSignals team has reviewed the CAIA a11y audit for Medallia 2.0 forms 29 and 41
   - When the engineer collaborates with the VSignals team to address critical and major accessibility issues
   - Then the forms are fully accessible and compliant with Platform accessibility standards
   - 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
Met Wednesday March 27

**Teams**:
- Veteran Support Team
- VSignals team
- CAIA

**Attendees**:
Aubrey Arcangel -Engineer and support specialist on Veteran Support Team
Anita Middleton -PM, Veteran Support Team
Camille Green - UX, Veteran Support Team
Sarifa Khalilullah - Data analyist, Veteran Support Team
Yassine Ramadan - VSignals
Vlad CRAPATUREANU - VSignals
Todd Galen - VSignals
Karim Primo - Senior Analyst, Digital (Public Sector) at Medallia

Purpose: 
Meeting was to address issues found from the [a11y audit](https://docs.google.com/spreadsheets/d/1Z_xXH2WnyP0YWNCJFKs0duwgSIug9VNEmzWR9RzxSYM/edit#gid=0) done by the CAIA team on the Medallia 2.0 forms
