### ISSUE TITLE
Confirm whether we should allow future dates in date ranges for toxic exposure

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#78419]
## Issue Description
[Toxic Exposure: Gulf War Hazard 1990 Date Ranges #73848](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/73848) raised the question:

> 
> 1. Date component has an error validation when trying to put in a future date. Could this be a valid scenario for BDD + question 15D hazard exposures?
> <img width="587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ccde9a34ab798fd2ecc8120ab2fba279eae9b3d/image.png" alt="image.png" />
> --> Let's ask VBA if future date should be allowed
> 

---
## Tasks
- [x] Ask VBA whether a future date should be allowed - is there a valid case for that, in particular for BDD? Can ask at a future VBA sync.
- [ ] Comment in this ticket and on [Toxic Exposure: Gulf War Hazard 1990 Date Ranges #73848](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/73848) with the decision

## Acceptance Criteria
- [x] Tickets updated with decision
- [x] @christinec-fftc notified

**Comment by mengA6** [comment]
added question to [3/19 VBA sync agenda](https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#heading=h.5y9awfwjne3p)

**Comment by mengA6** [comment]
David Reis [confirmed in 3/19/24 VBA sync](https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#heading=h.5y9awfwjne3p) that we don't need to allow future dates.
