### ISSUE TITLE
Develop a Strategy for Automated Tests of the PE Control Plane

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#78412]
# Description
Given the attributes of the control plane to act as a REST API that is agnostic to the system consuming it, we should devise a means for developing automated tests that does not rely on a specific front-end experience to feed into the API. Possibilities include --
* Contract tests -- some difficulty here in that we won't have a "consumer" side of the equation to start with
  * Pact
* API tests
  * Postman
  * JMeter
  * Rest Assure
  * etc.

## Tasks
1. Examine the possible test methodologies that we can use to test this new API
2. After choosing a test methodology, survey the possible tools and create a capability / evaluation matrix
3. Meet with stakeholders to make a decision
4. Record the decision in Confluence

## Acceptance Criteria
- [x] We have selected a test methodology for automatically verifying the capabilities of the control plane API
- [x] We have recorded the decision in a decision log document in Confluence
- [x] We have selected a tool for creating the automated tests

**Comment by pjhill** [comment]
I created a Postman collection based on the Swagger documents that Patrick created. [<img src="https://run.pstmn.io/button.svg" alt="Run In Postman" style="width: 128px; height: 32px;">](https://app.getpostman.com/run-collection/15306072-19666fef-7d3f-48d2-b61a-dca56fa2ea92?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D15306072-19666fef-7d3f-48d2-b61a-dca56fa2ea92%26entityType%3Dcollection%26workspaceId%3Dfd818ef2-f77c-4122-8f45-1f84bb5eb7a3)

**Comment by pjhill** [comment]
Postman offers up the following snippet to get execution of the test collection going inside a GHA CI workflow --

```
name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "15306072-19666fef-7d3f-48d2-b61a-dca56fa2ea92" -e "15306072-aa90a95b-b4a3-477b-91ad-fc290f8fbcb1"
```

**Comment by pjhill** [comment]
Additionally, Postman can do performance testing. Simulating load from your local workstation in a few different methods --

- Fixed: Simulate 20 virtual users repeatedly running the collection, in parallel, for 10 minutes.
- Ramp Up: Simulate a fixed load of 5 users for 2:30 minutes. Then steadily increase the load to 20 users over the next 2:30 minutes and hold for 5 minutes.
- Spike: Simulate a fixed load of 2 users for 4 minutes. Then spike up the load to 20 users over the next 1 minute , and spike down the load from 20 users to 2 users over the next 1 minute and hold for 4 minutes.
- Peak: Simulate a fixed load of 4 users for 2 minutes. Then steadily increase the load to 20 users over the next 2 minutes and hold for 2 minutes, and then steadily decrease the load from 20 to 4 over the next 2 minutes, and maintain a fixed load of 4 users for 2 minutes.

**Comment by pjhill** [comment]
Environments can be configured within the Postman collection. For example, the `baseURL` can be linked to an environment. In this way, we can configure CI to target the appropriate control plane instance.

**Comment by pjhill** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3043787125/Test+Framework+for+PE+Control+Plane
