### ISSUE TITLE
[FE] 10-10EZR - Update importing the root URL of React apps in content links

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#78413]
## Description

With the 10-10EZR application getting isolated in CI builds, we need to protect ourselves from other React app URL changes. Currently all links to internal apps or external pages are hardcoded in the various link `href` values. For internal apps, we need to programmatically grab the root URL from a registry helper.

## Resources

- [Allow-list Documenation](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list)
- [Registry helper utility](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/registry-helpers.js)
- [Example of usage](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/rated-disabilities/components/MVIError.jsx)

## Tasks

- [ ] Get local environment set up
- [ ] Identify all links where we may be linking over to another `vets-website` React app
- [ ] Update link to grab the app URL from the registry helper utility
- [ ] Verify all links are correct

## Acceptance criteria

- All internal links are fetched with registry helper utility

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that all links that were updated are working as expected
