### ISSUE TITLE
[BE] Investigate on getting total execution time for OH travel claim submission

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#78427]
## Description
As part of [creating dashboard](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/75599) for OH travel claims, we also need to add the time to complete (from login to submit claim).  

## Tasks
- [ ] [BE] **Investigate on existing logs to calculate the completion time**
- [ ] [BE] **Modify existing CIE travel claims dashboard to show the completion time**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by randomsync** [comment]
We have looked through DD documentation exhaustively and the current features don't give us a way to provide aggregate metrics on the time differences between log statements grouped by an attribute (payload.uuid). We discussed this with the rest of the engineering team, and have come up with a better approach, which is to have website include the time as a parameter, which can be logged by vets-api and be used to provide aggregate metrics. This is a good low-cost approximation of the time it takes veterans to submit the travel claim from logging in.

Work tickets:
FE: https://github.com/department-of-veterans-affairs/va.gov-team/issues/79739
BE: https://github.com/department-of-veterans-affairs/va.gov-team/issues/79741
