### ISSUE TITLE
Midpoint Review - Design Feedback - Benefits Non-Disability, CH 36/PCPG, Critical Form Updates

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#78445]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions
- Take a look at the "Are you on active duty" and "Discharge" questions, I am not sure the discharge info should appear unless they are not on active duty.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: Use the new [address pattern](https://staging.va.gov/mock-form-patterns/mailing-address) (city and APO swap out when the user checks "I live on a United States military base outside of the U.S.")
- [x] Must: Add a "back to va.gov" secondary action link on the [confirmation page](https://design.va.gov/templates/forms/confirmation#back-to-vagov-link).

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic
