### ISSUE TITLE
Burial | Canary Testing Payload

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78473]
## Issue Description
_Compile json files for all burial form submissions during the canary testing period and provide them to the VBA to validate. The VBA will check the json files against the claim pdfs generated by VA.gov and flag any inconsistencies for remediation._

---
## Tasks
- [ ] Compile json of claims within testing period
- [ ] Send to VBA in a secure way to protect PII

## Acceptance Criteria
- [ ] json of burial submissions sent to VBA
---
