### ISSUE TITLE
Spike | Burial | Confirmation Email to Unauth Users

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78471]
## Issue Description
_Do we currently send confirmation emails for Burial 530EZ claims to unauthenticated users? If not, can we pull the email entered in the claim and send a confirmation email to that address?_

---
## Tasks
- [ ] Determine what email address the Burial confirmation email uses (VA Profile or claim email)
- [ ] Determine if unauthenticated users receive confirmation emails
   - [ ] If no, determine if we can send an email to the email address they entered in the form 

## Acceptance Criteria
- [ ] Document findings in this ticket
---
