### ISSUE TITLE
Deduplicate Platform Datadog monitors

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#78476]
## Issue Description
[It was brought to our attention](https://dsva.slack.com/archives/C30LCU8S3/p1710421769042939?thread_ts=1710356437.928689&cid=C30LCU8S3) that the High CPU utilization monitor already existed. Their alerting paths are slightly different. The new [monitor Rachal created](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/monitors/vets_api_prod_rds_high_cpu_utilization.json) alerts pager duty and the #oncall channel whereas the [monitor Kyle mentioned](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/monitors/aws_rds_cpu_utilization.json) does not alert. 

From Kyle: 
> it should not be sending to PD or #oncall. CPU and Memory metrics alone should  not be in [#oncall](https://dsva.slack.com/archives/C30LCU8S3) , they are informational at best, but certainly not actionable.

- [Platform (infra) monitors and alerts](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors-alerts?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1709816727056&to_ts=1710421527056&live=true) Dashboard

## Tasks
- [x] Delete the new monitor in Terraform and Datadog. 
- [x] Review the other monitors to check for other duplicates. 

## Acceptance Criteria
- [x] Duplicate monitors are consolidated or removed. 
- [x] Terraform is applied if necessary.

**Comment by jennb33** [comment]
Make sure to coordinate with @flooose on the Terraforms deletion process

**Comment by RachalCassity** [comment]
The duplicate alerts were created to ensure the devop alerts would not be modified. The alert should NOT alert oncall or pager duty. That was a foresight when first creating some of the duplicate alerts. Maybe we can update the new alert's message to alert the backend-cop for now so that actionable context is not lost.
Ex message:
`"message": "{{#is_alert}} RDS CPU Utilization has exceeded the threshold: {{threshold}}. Please view this dashboard to resolve any potential issues, https://vagov.ddog-gov.com/dashboard/jq8-w55-zzp?fromUser=true&refresh_mode=sliding&tpl_var_env%5B0%5D=eks-prod&view=spans&from_ts=1709129677000&to_ts=1709140477000&live=true. @slack-platform-cop-be-notifications {{/is_alert}} \n{{#is_warning}} RDS CPU Utilization has exceeded the warning threshold: {{warn_threshold}} @slack-platform-cop-be-notifications {{/is_warning}} \n{{#is_alert_recovery}} Pagerduty RDS CPU Utilization has recovered from alert state @slack-platform-cop-be-notifications{{/is_alert_recovery}}",`

**Comment by rjohnson2011** [comment]
Terraform applied and closed - https://github.com/department-of-veterans-affairs/devops/pull/14242

DD Monitor - https://vagov.ddog-gov.com/monitors/225331?view=spans
