### ISSUE TITLE
[UX] 10-10CG - Form Update: Update Designs with agreed changes

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#78497]
## Benefit to the Veteran
By updating the designs with the agreed-upon changes, we will be able to visually confirm the updates and have a source of truth to rely on for development. This will ensure we are aligned with the VA.gov design system and provide a consistent experience for Veterans & Caregivers.

## Background
The 10-10CG paper form was updated in February 2024, with plans to release to the public in June.
The stakeholders sent a copy of the updated form to our team for review and effort estimation. After reviewing the updated form against the existing paper form, we found that there are content changes and additional fields for "Mailing Address" of the Caregivers.

We need to work with the Content team and update the designs.

#### Resources
- [Form Updates GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Form%20updates%20(Feb%202024))
- [Updated form from stakeholders](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Form%20updates%20(Feb%202024)/VA%20Form%2010-10CG_02.28.2024.pdf)
- [Word document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Form%20updates%20(Feb%202024)/Draft%20with%20highlighted%20changes%20-%2010-10CG_02.28.2024.docx) with highlighted changes and notes on differences
- Notes from discussion with stakeholders **[TBD]**

## Tasks
- [x] [Figma page](https://www.figma.com/file/TxXD5bGUOhbHHWLb85GPjK/10-10CG?type=design&node-id=376-15166&mode=design&t=iJ7xEjqtCOv3EBCM-0) setup to annotate content changes between new paper version (JS)
- [x] Create new user flows in Mural to reflect changes around address and new page(s) - [Platform Guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md) (JS)
- [x] Review with team - walkthrough scheduled for Monday 4/22
- [x] Update Figma designs with detailed user flows and content updates
- [x] When updating the new screens in Figma, change over to using components from library VADS Templates, Patterns and Forms (both)
- [x] Open [Content intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81190) (JS) 

## Acceptance Criteria
- We have engaged and began working with the Content team.

**Comment by jessicastump** [comment]
Updated [user flows are in Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711491442696/6c33e417dbfd2cb893452606262192fcb79a579b?sender=uadf1ed7fe7c76f0914967329) - will work on updating the Figma file with the designs and detailed user flows.

**Comment by jessicastump** [comment]
Closing and moving content review process to [new ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81922)
