### ISSUE TITLE
[FE] 10-10CG - Form Update: Implement changes to UI

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#78499]
## Benefit to the Veteran
By implementing the content and field changes to the 10-10CG, we will be providing clarity to Veterans and Caregivers, as well as providing an opportunity for the Caregivers to input their mailing address, if different from their home address. 

## Background
The 10-10CG paper form was updated in February 2024, with plans to release to the public in June.
The stakeholders sent a copy of the updated form to our team for review and effort estimation. After reviewing the updated form against the existing paper form, and discussing changes with the stakeholders, we need to update the UI to reflect the content and field changes

#### Resources
- [Form Updates GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Form%20updates%20(Feb%202024))
- Design ticket #78497 
- [Figma Designs](https://www.figma.com/file/TxXD5bGUOhbHHWLb85GPjK/10-10CG?type=design&node-id=376-15166&mode=design&t=iJ7xEjqtCOv3EBCM-0)

## Tasks
- [x] Review designs
- [x] Update the form with the addition and removal of fields
- [x] Update any content changes
- [x] Review with the team

## Acceptance Criteria
- The 10-10CG UI has been updated
