### ISSUE TITLE
[BE] 10-10CG - Form Update: Add new fields to schema

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#78498]
## Benefit to the Veteran
By making updates to the schema to include the mailing address fields for Caregivers, we are providing the option for Caregivers to input this information, in case their mailing address is different from their home address.

## Background
The 10-10CG paper form was updated in February 2024, with plans to release to the public in June.
The stakeholders sent a copy of the updated form to our team for review and effort estimation. After reviewing the updated form against the existing paper form, we found that there are content changes and additional fields for "Mailing Address" of the Caregivers.

We need to make updates to the schema so that Caregiver mailing address information and County field input can be transmitted to MuleSoft/CARMA.

#### Resources
- [Form Updates GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/Form%20updates%20(Feb%202024))

## Tasks
- [ ] Review requirements with MuleSoft/CARMA teams
     - [ ] Mailing address fields for Primary & both Secondary Caregivers
     - [ ] County field for Veteran, Primary & both Secondary Caregivers (This will NOT be a "Required" field)
     - [ ] Suffix field in the Name section for Veteran, Primary & both Secondary Caregivers
- [ ] Update schema with these changes
     - Do not implement this yet, should be behind a feature flag
- [ ] Provide to CG team for their reference during development

## Acceptance Criteria
- The 10-10CG schema has been updated to include the new mailing address and County fields and has been provided to CG team for review.

**Comment by hdjustice** [comment]
Pending action item to obtain example

**Comment by Mitch-A6** [comment]
Sample updated schema for reference:
[10-10CG-schema.json](https://github.com/department-of-veterans-affairs/va.gov-team/files/14886392/10-10CG-schema.json)

**Comment by hdjustice** [comment]
Sample from Ranga on Suffix schema
```
"fullName": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "first",
        "last"
      ],
      "properties": {
        "first": {
          "type": "string",
          "minLength": 1,
          "maxLength": 30
        },
        "middle": {
          "type": "string",
          "maxLength": 30
        },
        "last": {
          "type": "string",
          "minLength": 1,
          "maxLength": 30
        }
      }
    },
```

**Comment by Mitch-A6** [comment]
Updated with suffix: 
[10-10CG-schema.json](https://github.com/department-of-veterans-affairs/va.gov-team/files/14889980/10-10CG-schema.json)

**Comment by hdjustice** [comment]
Schema updated and shared with CG team.  Further discussion needs additional updates, this will be done on ticketh #80742
