### ISSUE TITLE
[FE] 10-10CG - Form Update: Update JSON with changed Facility name

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#78506]
## Benefit to the Veteran
By updating the Facilities JSON file to change a Facility name from "Hunter Holmes McGuire Hospital" to "Richmond VA Medical Center", we will provide a consistent VA.gov experience for the Veteran, as well as display a familiar facility name to select in the 10-10CG form.

## Background
The 10-10CG form currently uses a static JSON file for the Facility selection page.  We are in the process of getting that switched over to using the API for a dynamic list of facilities that we will not have to maintain.  However, until that switch is completed, we need to make an update to the current JSON file.

#### Resources
- JSON File

## Tasks
- [x] Update the JSON file to change the Facility name from "McGuire Hunter Holmes VA" to "Richmond VA Medical Center"
- [x] Complete testing to ensure the facility name is displaying as expected in the form
- [x] Confirm that the facility information being sent downstream to MuleSoft/CARMA remains the same
- [x] Validate with PM/team

## Acceptance Criteria
- The JSON file has been updated so that the 10-10CG form displays the correct name for the facility.

**Comment by longmd** [comment]
@hdjustice , question: There are two entries in the VA medical facility list that reference the `Hunter Holmes McGuire` name. (Hunter Holmes McGuire 2 VA Mobile Clinic & Hunter Holmes McGuire Hospital). Does that name need changed for both entires?

So `Hunter Holmes McGuire Hospital` will become `Richmond VA Medical Center` and `Hunter Holmes McGuire 2 VA Mobile Clinic`?

Note: this is already a `Richmond 1 VA Mobile Clinic` entry. So 2 would stay 2, I assume? See the attached screenshot:

![Screenshot 2024-03-18 at 15 07 20](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/6f21cdc9-8b53-4525-83b0-1efef531b16d)

**Comment by hdjustice** [comment]
Oooo interesting.  I would assume the same, but let me as CG group.

**Comment by hdjustice** [comment]
I received a response from our CG stakeholders that they need to check with their PM/VISN.  Maybe we will have an answer by this Friday when we meet with them.

**Comment by longmd** [comment]
@hdjustice , I have verified the name change in the list. No changes were made to the data values sent in the payload, just the label that is displayed in the input. 

<img width="553" alt="Screenshot 2024-03-28 at 17 01 11" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/32635779-0e97-49bd-9d3e-a22759bc4162">

**Comment by Mitch-A6** [comment]
> @Mitch-A6 , can you create a PR to update the `vets-json-schema` package version in `vets-api`?
👍 
https://github.com/department-of-veterans-affairs/vets-api/pull/16139
