### ISSUE TITLE
Add Descriptive Tags for Design System Templates

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#78505]
## User Story
As a Governance team member, I want to ensure all tags and references for DS **Templates** are included in the DraftingTemplate so that Staging Review issues tickets are published with valid references for VFS teams.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman 

## Description
In a previous ticket #76875, we made sure that the Drafting Template contained references to all Design System components and patterns. We did not include Templates at the time, but will do so now.

When we add Templates, they should be added alongside the Design System Patterns and we should change the title in the DraftingTemplate to Design System Patterns/Templates.

In addition:

- this ticket will also address adding a question to the DraftingTemplate for imposter components per ticket #76895.
- this ticket will address adding descriptive tags for the VADS foundation. There should be a new column/field within the DraftingTemplate. 

## Impacted Artifacts

- VA.gov Experience Standards Source of Truth
- Drafting Template
- Drafting Template DST

## Tasks
- [x] Update descriptive tags in source of truth
- [x] Update descriptive tags and relevant columns in the Findings sheets of Drafting Templates

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Source of truth is updated
- [x] Drafting Templates are updated

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@shiragoodman I have added the new descriptive tags to the source of truth, and to the Drafting Templates. Both of the drafting templates' logic in the `Design System Pattern or Template` column needs to be updated to reflect the new rows. If you give me access to the protected ranges in the sheet, I can make an attempt at it! or I can leave this change to you.

**Comment by shiragoodman** [comment]
I can give you access. I have been considering removing all protections within the sheet anyways since it seems to be more problematic than it is helpful. I'll let you know once it's ready for you.

**Comment by erinrwhite** [comment]
@shiragoodman 

### Source of truth

- [ ] Updated [Source of Truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009) 👍🏻 

### Drafting template updates for your review


- [ ] [Drafting Template **draft version**](https://docs.google.com/spreadsheets/d/1HODfp7bdH0dmQa2CQV4bhRN9pGMAbiuzhXFNNB9EC4w/edit#gid=727681601)
  - **DescriptiveTags tab:** Added/updated descriptive tags, including 8 new rows (249-257) for DS Templates
  - **Findings tab:**
    - Updated columns W, X, Y, `Design System Pattern or Template` and hidden columns, to accommodate new rows in descriptive tags spreadsheet
    - Added "Is imposter component?" column and hidden label column
    - For hidden label columns, changed protections from "Restrict who can edit this range" to "Show a warning when editing this range"
  - **Reviewers** Changed protections from "Restrict who can edit this range" to "Show a warning when editing this range"
  - **GitHub Upload** 
    - Updated labels column to include va-imposter label when selected in Findings tab
    - Changed protections from "Restrict who can edit this range" to "Show a warning when editing this range"

- [ ] [Drafting Template - DST **draft version**](https://docs.google.com/spreadsheets/d/1SZeR6JW_3dS-ZgrJCpPhXSIJfGbZooz6VsmoNOAAmg8/edit#gid=727681601)
  - **DescriptiveTags tab:** Added/updated descriptive tags, including 8 new rows (249-257) for DS Templates
  - **Findings tab:**
    - Updated columns T, U, V, `Design System Pattern or Template` and hidden columns, to accommodate new rows in descriptive tags spreadsheet
    - Added "Is imposter component?" column and hidden label column
    - For hidden label columns, changed protections from "Restrict who can edit this range" to "Show a warning when editing this range"
  - **Reviewers** and **GitHub Upload** Changed protections from "Restrict who can edit this range" to "Show a warning when editing this range"

**Comment by shiragoodman** [comment]
Thanks @erinrwhite!

As for the ticket itself, I did add a line under Description stating that this ticket will also address adding a tag for imposter components. Thank you for including that in your work.

Source of truth looks good. I like that you've included the "Other tag" option to list out launch-blocking and imposter component. We should also add the Design System Review label per ticket #75629. Since we will always add both the Design System team label (`platform-design-system-team`) and the review label (`design-system-review`), Allison set up the DraftingTemplate to print out "platform-design-system-team,design-system-review" in the labels column of the Github Upload tab. I am not sure how you'd like this reflected in the source of truth.

I'm seeing a problem with the pattern/template label and pattern/template reference link columns (columns X and Y) in the Findings tab not populating correctly. I know why the problem is happening, but I think it might be best to sync with you to explain the problem and we can figure out a solution together.. since there's a few different ways we can solve this.

Let me know if you have time today to meet!

**Comment by erinrwhite** [comment]
@shiragoodman thanks for the helpful meeting today! I think this new formula will fix things up for us.

For your review:
[Drafting Template draft version](https://docs.google.com/spreadsheets/d/1HODfp7bdH0dmQa2CQV4bhRN9pGMAbiuzhXFNNB9EC4w/edit#gid=727681601)
[Drafting Template - DST draft version](https://docs.google.com/spreadsheets/d/1SZeR6JW_3dS-ZgrJCpPhXSIJfGbZooz6VsmoNOAAmg8/edit#gid=727681601)
- Added tag `design-system-review` to list of descriptive tags
- Updated Vlookup for `Design System Pattern or Template` column in the findings tab to use `FALSE` flag and do an exact text search

Updated [Source of Truth(https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009) 👍🏻
- Added tag `design-system-review` to list of descriptive tags

**Comment by erinrwhite** [comment]
Moved back to in-progress - per [discussion on Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1710946629937599) we will be adding in Design System Foundation to Source of Truth and Drafting Templates as part of this ticket.

**Comment by erinrwhite** [comment]
@shiragoodman ready for your review AGAIN! 😂 

Updated [Source of Truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009)

- Added Design System foundation tags to Descriptive Tags sheet

[Drafting Template draft version](https://docs.google.com/spreadsheets/d/1HODfp7bdH0dmQa2CQV4bhRN9pGMAbiuzhXFNNB9EC4w/edit#gid=727681601)
[Drafting Template - DST draft version](https://docs.google.com/spreadsheets/d/1SZeR6JW_3dS-ZgrJCpPhXSIJfGbZooz6VsmoNOAAmg8/edit#gid=727681601)
- Added Design System foundation tags to Descriptive Tags sheets
- Added columns in Findings tabs for Design System Foundation
- Updated GitHub upload to reflect new Foundation tags/links in body and labels

**Comment by erinrwhite** [comment]
Also, can we bump this ticket up to a 3? 😅

**Comment by shiragoodman** [comment]
thanks @erinrwhite . Yes, bump it to a 3. We've added on quite a bit.

I will review your updates in the morning!

**Comment by shiragoodman** [comment]
@erinrwhite awesome! Everything is working as expected. The only comment I have is to ask you to remove the permissions since this is now a document you own. It might also be a good idea to create a copy of the baseline DT for both VFS and DST in case someone accidentally overwrites one of the formulas.

We should be good to close this out once you make the changes.

**Comment by erinrwhite** [comment]
@shiragoodman Thank you! I had changed the protections "Restrict who can edit this range" to "Show a warning when editing this range". What do you think about the keeping the permissions as "Show a warning"? It would still show a warning if someone was trying to edit something, but would not restrict who can edit. I think it could be a handy protective measure but still allow everyone to edit if they actually intend to.

I like the idea of a backup - will do that. Let me know what you think about keeping the warnings.

**Comment by shiragoodman** [comment]
great idea @erinrwhite ! The warnings would be very helpful. Let's do that!

**Comment by erinrwhite** [comment]
Good deal.

Created [Backups of drafting templates](https://drive.google.com/drive/folders/1Q-2Vvhc8PXQJIZjiyytDktRK0wT_bhzI?usp=drive_link)

And updated drafting templates are now renamed and live
[Drafting Template](https://docs.google.com/spreadsheets/d/1HODfp7bdH0dmQa2CQV4bhRN9pGMAbiuzhXFNNB9EC4w/edit#gid=727681601)
[Drafting Template - DST](https://docs.google.com/spreadsheets/d/1SZeR6JW_3dS-ZgrJCpPhXSIJfGbZooz6VsmoNOAAmg8/edit#gid=727681601)

Closing!
