### ISSUE TITLE
[FSR] Test adjusted FSR calculation endpoints

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#78508]
## Description
Follow on for **[FSR] - Testing new endpoints and page generation [#76696](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/76696)**

After coordinating with the BE some more we had to make some adjustments to account for edge cases for these calculations. This ticket is to confirm we're getting valid responses before we dive into implementation for each one. 

## Tasks
- [x] Confirm `/v0/calculate_monthly_expenses` returns expected data
- [x] Confirm `/v0/calculate_all_expenses` returns expected data
- [x] Confirm `/v0/calculate_monthly_income` returns expected data
- [ ] Confirm `/v0/calculate_total_assets` returns expected data

## Acceptance criteria
- [x] `/v0/calculate_monthly_expenses` functioning as expected 
- [x] `/v0/calculate_all_expenses` functioning as expected 
- [x] `/v0/calculate_monthly_income` functioning as expected 
- [ ] `/v0/calculate_total_assets` functioning as expected 

## Testing
- [ ] Yes

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Ran into some issues while testing `/v0/calculate_total_assets`. Going to close ticket out now since testing is complete, and FE/BE will coordinate ticket(s) for fixing the problems
