### ISSUE TITLE
[FE] My VA BAD: configure forms 28-8832 and 26-1880

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#78504]
## Background
Fiorella Geedi and Laura Steele from the non-disability benefits team [informed us that two forms do not appear in the Benefit application drafts section](https://dsva.slack.com/archives/C909ZG2BB/p1710441317658929):
- form 28-8832
- form 26-1880

Initially, I thought it was because the form IDs weren't listed in the `VA_FORM_IDS` object in [/platform/forms/constants file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L3), but they indeed are (the list isn't numerically sorted).

Also noticed that the [documentation on the Platform site](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si#VAFormsLibrary-HowtosetupSaveInProgress(SiP)-MyVAPage) is out of date after Adam's [work to move the SIP constants](https://github.com/department-of-veterans-affairs/vets-website/commit/a493bc659e024e90b607e48b364742dd0dc2ef04) from dashboard helpers to platform constants.

---
## Tasks
- [x] meet with AJ to get more info about [this ticket from three sprints ago](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70284)
- [x] investigate why the two forms are not showing up on My VA
- [ ] Coordinate with Fiorella Geedi and Laura Steele to test/validate once done

## Acceptance Criteria
- [ ] forms 28-8832 and 26-1880 display correctly on My VA _OR_
- [ ] ~new ticket to address any issues that come from investigation (if not resolved within this ticket)~

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Dev, PM, tag Fiorella and Laura
- _How can this work be validated?_

## Resources
- PM ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/70284
- [Slack thread from Non-disability benefits team](https://dsva.slack.com/archives/C909ZG2BB/p1710441317658929)
- [SIP process technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0d8d47fbb9ade5e7050191fbc096b14d7514e47f/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)

**Comment by DanielMiller-agile6** [comment]
dropping to 1 for next sprint. need to finish testing, and got distracted a bit with discovery work this past sprint

**Comment by DanielMiller-agile6** [comment]
Fiorella Geedi verified changes on staging.
<img width="1378" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGRhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60b56b9ee35809d1a227643cd36902807811d8cc/image%20%281%29.png" alt="image (1).png" />
