### ISSUE TITLE
Copy of CH 31 Updates | Step 2: Contact Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78522]
## Issue Description
_The online Chapter 31/VR&E/28-1900 form is outdated and needs to have missing fields added and depreciated fields removed._

- [Figma file](https://www.figma.com/file/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--Redesign?type=design&node-id=276-19824&mode=design&t=uYBRL8zeUi3IrnbE-0)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684161597392/5c1f8869cf5d03b792c8b82cf19b39dc26c486c2?sender=u0e8ac1d6d7681bb7e1b80558)
- [Old form pdf - Nov 2019](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdac4f2d7481d97fa6fe4d9461d2549029a47711/28-1900_Nov2019.pdf)
- [New form pdf - Aug 2022](https://www.vba.va.gov/pubs/forms/VBA-28-1900-ARE.pdf)
- [Collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74141)

---
## Tasks
- [ ] Make changes denoted in the Figma file for Step 2
- [ ] Update unit test coverage

## Acceptance Criteria
- [ ] Step 2 design aligns with Figma file
- [ ] Copy in online form matches Figma file
- [ ] Fiorella signs off on changes in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---
