### ISSUE TITLE
Discovery: Policies for Links to GA, GTM, Chrome Store, Support

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#78528]
## Issue Description
In order to take action toward removing Google links from PW, we need to learn the current policies around links to Google Analytics, Google Tag Manager, Chrome Store and Google Support. 
GA and GTM require access permissions and VFS Teams and other contractors may block access to Chrome Store and Google Suppport.

---
## Tasks
- Reach out to Andrea Hewitt to learn policies. Specifically get answers about:
- [x] Links to google analytics pages
- [x] Links to Chrome store
- [x] Links to google support pages
- [x] Links to google tag manager
- [x] Big Query
- [x] Links to specific google calendars
- [x] The weird link we found in [Analytics customer support guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide)
- [x] Links to google search results

- [x] Add additional SMEs/Leadership to contact here if necessary

## Acceptance Criteria
- [x] Decisions have been made how to handle non-Google drive links

## Relevant Links
[Google Analytics](https://analytics.google.com/analytics/web/#/report/content-site-search-overview/a50123418w177519031p184624291/) example
[Google Support Page](https://support.google.com/accounts/answer/176347?co=GENIE.Platform%3DDesktop&hl=en) example
[Google Tag Manager](https://developers.google.com/tag-platform/tag-manager/datalayer) example
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
We have confirmed how to handle these links with Andrea, moving to _Done_
