### ISSUE TITLE
Edit Ticket: Accessibility Strategy Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#78532]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Modernized VA.gov Accessibility Strategy](https://depo-platform-documentation.scrollhelp.site/getting-started/modernized-va-gov-accessibility-strategy) contains links to Google Docs and Google Sheets. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

---
## Tasks
- [x] Identify SME to provide guidance for this page
- [x] Update the page according to guidance

## Acceptance Criteria
- [x] Updated page is ready for deployment

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Lauren discussed possibilities with Martha Wilkes, Brian Deconnick, Jamey Fay, Terry Nichols. Waiting to discuss with Shira Goodman. Working to confirm SME for guidance.

**Comment by jknipes** [comment]
work complete, moving to _done_
