### ISSUE TITLE
Discovery Ticket: Successful Screener Questions Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#78533]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Successful Screener Questions](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions) contains links to Google Docs. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

---
## Tasks
- [x] Identify SME to provide guidance for this page
- [x] decide whether to remove, replace or otherwise redirect users toward a new source.
 
## Acceptance Criteria
- [x] Page is ready to be updated

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Waiting next steps from Naomi Marcusson

**Comment by jknipes** [comment]
unable to complete due to being blocked by SME, moving to Backlog

**Comment by jknipes** [comment]
Per Naomi Marcussen, we are waiting on OCTO determining a space for these documents to live in Sharepoint

**Comment by jknipes** [comment]
Sprint assignment was added by automation. Removing date and keeping in Backlog pending decision by OCTO.

**Comment by jknipes** [comment]
issue is _blocked_, waiting on OCTO determining a space for these documents to live in Sharepoint

**Comment by jknipes** [comment]
@naomimarcussen has given guidance and we will proceed with Edit ticket 79194

**Comment by jknipes** [comment]
Closing this discovery ticket as _Done_
