### ISSUE TITLE
Discovery Ticket: Getting Started With Platform Analytics Insights

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#78547]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Getting Started With Platform Analytics Insights ](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights)contains links to Google Slides. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

---
## Tasks
- [x] Identify SME to provide guidance for this page
- [x] decide whether to remove, replace or otherwise redirect users toward a new source.
 
## Acceptance Criteria
- [x] Page is ready to be updated

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)

**Comment by jknipes** [comment]
Discovery is complete, moving ticket to _Done_

**Comment by jknipes** [comment]
Related work ticket [79199](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/79199)
