### ISSUE TITLE
Edit Ticket: Research, Synthesize and Share

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#78549]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Research, Synthesize and Share](https://depo-platform-documentation.scrollhelp.site/research-design/research-synthesize-and-share) contains links to Google Slides. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

## Discovery Ticket:
[79202](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/79202)
---
## Tasks
- [x] Update page according to guidance by SME
- [x] Move page into deployment space
- [x] Check for LBs

## Acceptance Criteria
- [x] Page is ready for deployment

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)

**Comment by jknipes** [comment]
unable to complete due to being blocked by SME, moving to Backlog

**Comment by jknipes** [comment]
Per Naomi Marcussen, we are waiting on OCTO determining a space for these documents to live in Sharepoint

**Comment by jknipes** [comment]
Sprint assignment was added by automation. Removing date and keeping in Backlog pending decision by OCTO.

**Comment by jknipes** [comment]
Issue is currently _blocked_, waiting on OCTO determining a space for these documents to live in Sharepoint

**Comment by jknipes** [comment]
Page was updated by SME, closing as _Done_
