### ISSUE TITLE
VAMC Alert Banner Text

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7854]
## Problem Statement
How might we ensure the alert banner text is concise and meaningful for Veterans?
- COVID alert banner on Pittsburgh health care pages is quite verbose, blocking the page content from being displayed when user arrives on the page. 
- Errors are easily introduced by content authors who may not be comfortable using digital medium
- Implementing character limits may not address core issue and may be too restricting for future alert needs

## Current behavior

![alert1.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/2da644b6-d61c-42e4-adce-ba69b469c55d)

![alert2.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/7a75323d-2a9d-4ed3-a8be-11208f884e06)

## Goal
Content authors are supported in authoring experience
Veterans have the information they need during an emergency

## Objectives or Key Results this is meant to further
- Objective 2: Deliver meaningful facility information 

---
## Tasks
Determine best authoring experience to deliver meaningful emergency content to Veterans, considering:
- [ ] Veteran audience
- [ ] Content author comfort using digital medium
- [ ] Need to quickly update content during emergency situations

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
