### ISSUE TITLE
Appoint a Rep v2: Digital Submission

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78553]
## Background
Our VA Enablement team is encouraging us to start ideating on the digital submission portion of Appoint a Rep asap.  This means it's time to start thinking ahead as to what Appoint v2 could look like, with the digital submission inclusion.

## Tasks
- [ ] Initial exploration of how Appoint v2 could support digital submission
- [ ] Iterate on designs based on team feedback

## Acceptance Criteria
- [ ] Appoint v2 designs are in Figma and ready for Design Intent

**Comment by holdenhinkle** [comment]
Will review A's comments from meeting earlier today.

**Comment by holdenhinkle** [comment]
Will review A's comments from meeting earlier today.
