### ISSUE TITLE
[FE] Back button on Review page should go back one page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#78552]
## Wireframes
- Back button on [Review page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=1585-1543&mode=design&t=hK471brtp6R8wgpF-4) should go back to the last page, not the beginning of the workflow

## Tasks
- [ ] [FE] Back button on [Review page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/LoROTA-Travel-Reimbursement-%7C-Check-in?type=design&node-id=1585-1543&mode=design&t=hK471brtp6R8wgpF-4) should go back to the last page, not the beginning of the workflow
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by benbrasso-agile6** [comment]
Tagging @loripusey so you don't log the same change

**Comment by benbrasso-agile6** [comment]
No longer an issue
