### ISSUE TITLE
Replace anomalous monitors

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#78563]
### Summary
It was brought to our attention by Kyle that [Anomaly Monitors](https://docs.datadoghq.com/monitors/guide/anomaly-monitor/) can be flakey and shouldn't be used. A number of new anomaly monitors were recently added to the Platform Product team. Find them by searching the devops repo for `anomalies` (not all of those are ours, though). We need to use a different metric in DataDog (we need a metric alert).

Anomaly monitors are based on learning what's considered "normal" behavior. In dynamic envs where normal is constantly changing (think external services in our case), anomaly monitors might generate a high rate of false positives, being too noisy for behavior that's expected.

### Tasks
- [x] Replace the Product Team's anomaly monitors with other metrics. 
- [x] Monitor the new metrics and adjust accordingly, making sure they're not too sensitive.
- [x] Once the metrics are in a healthy state, export the json to the devops repo so it can be saved in terraform. 

## Success Metrics
All of the anomaly monitors our team owns are `metrics` monitors and are being used (not muted).

### Acceptance criteria
- [x] Product team-owned anomaly monitors are replaced in datadog and terraform

**Comment by jennb33** [comment]
One monitor has been started, and due to support coverage, this ticket is being moved out to Sprint 52.

**Comment by rmtolmach** [comment]
We have this non-anomalous monitor: [VETS API - PROD - Check HPA Metrics](https://vagov.ddog-gov.com/monitors/203304?q=kube_deployment%3Avets-api-web&event_id=7540689185644143852&source=monitor_notif&view=spans&live=1d) and the anomalous monitor: [VETS API - PROD - EKS IS NOT SCALING!](https://vagov.ddog-gov.com/monitors/204953?view=spans) and they appear to do similar things. I think we can delete the the anomalous one and still have the same amount of coverage.

**Comment by jennb33** [comment]
Per @rmtolmach, there are about a dozen monitors left to replace.

**Comment by rmtolmach** [comment]
- :x: I deleted "VETS API - PROD - EKS IS NOT SCALING!" (id: `204953`) in the dd UI and I have a branch with it deleted in terraform as well. (deleting b/c [VETS API - PROD - Check HPA Metrics](https://vagov.ddog-gov.com/monitors/203304?q=kube_deployment%3Avets-api-web&event_id=7540689185644143852&source=monitor_notif&view=spans&live=1d) covers it).
- 👀 [VETS API - {{env.name}} - Clamav Errors](https://vagov.ddog-gov.com/monitors/215822?view=spans) (id: `215822`) can be deleted. I'm replacing it with a two Log monitors. One for a higher env (prod) and one for a lower env (staging). Unfortunately, Datadog doesn't support conditional thresholds for log monitors 😩 so I can't create one monitor to trigger on different thresholds based on environment. I will monitor these two new monitors before committing it to terraform. 
    - Prod: https://vagov.ddog-gov.com/monitors/230930?view=spans
    - Staging: https://vagov.ddog-gov.com/monitors/230932?view=spans
- 🤔 [VETS API - {{env.name}} - {{controller.name}} - High 500 Errors](https://vagov.ddog-gov.com/monitors/203472). I'm tempted to un-mute this one and keep it as-is. For the 80+ groups this monitor reports on, this monitor has been triggered _zero_ times in the past month. The anomaly detection might work for this situation. 
- [VETS API - {{env.name}} - {{controller.name}} - High 400 Errors](https://vagov.ddog-gov.com/monitors/203672) is a different story. I will work on it tomorrow.

**Comment by rmtolmach** [comment]
- Update on the 400 error monitor: Upon comparing the queries of the 500 and 400 error monitors, I noticed the 400 query used a different algorithm, so I updated it with the algorithm the 500 one was using. So they're both using `agile` now. I will monitor the 400 monitor to see if it stabilizes.  (i've also updated the terraform on my branch to match my change in the UI)
    - Since both the 500 and 400 monitors track controllers that the Platform doesn't own, we don't necessarily want to _alert_ on them, but it's good to be able to see if one controller is going haywire. So a possible solution to this is to take out the alerting component and just use it as informational. 
- There are two "High CPU Usage" monitors. One is by `kube_deployment` and one is by `container_name` (and then there is a third in the UI only–[High CPU Usage by pods](https://vagov.ddog-gov.com/monitors/205002?view=spans)–we might want to delete that one?). I spent some time today trying to come up with something new.

**Comment by rmtolmach** [comment]
Update on the [Prod](https://vagov.ddog-gov.com/monitors/230930?view=spans) and [Staging](https://vagov.ddog-gov.com/monitors/230932?view=spans) ClamAV monitors I created. The staging one seems fine. The Prod one triggers during the vets-api deploy at 1pm ET and then resolves itself. 

1. `WARNING: remote_cvdhead: Malformed CVD header (too short)`
2. `WARNING: DNS Update Info disabled. Falling back to HTTP mode.`
3. `WARNING: Cool-down expired, ok to try again.`

Those same three warnings occur during non-deploy times, only in smaller numbers. I think we're safe to ignore the errors. We can set up a recurring mute for deploy time for 30 min. 

### High CPU Usage
The query we're using is `avg:container.cpu.usage{kube_namespace:vets-api} by {container_name,env}` which is in nanoseconds. I'm unclear how many nanoconds means "high CPU usage". There's also `container.cpu.limit` which is in nanocores. I had initially thought that dividing `usage/limit` would give us a percentage, but dividing nanoconds by nanocores doesn't seem right.

🐕 [Datadog metrics explorer](https://vagov.ddog-gov.com/metric/explorer?fromUser=false&start=1715116065121&end=1715720865121&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMiZUggYojoAdJnyeE14GhjwwADWeABGcE6RvvIY2cgViBoAtBjyEDwABANYy8C1IvWN2iNRcBRwIhUU-UNOAvJoOFjq2zwgfKCjOSCxWABMicn1aRnZZT5QrFd6lGi5SrVLY7ETNVrtNA+cR9QbDV72CZwKYzeaLFZrDbnYZXG53Y4ICgwhpwvavI4nR7PCIHGLggDMPxS-zwWTewIgRUSH3KVWQGDAGia2igUoRBAgSIAXp5JCJgFABqINPURNloBSIMIdMsAJIAOWWAApZRUMLNphY8RBZvJtDgoLNPgBKAnrDVakQ6jB69gCbZGvTaJkAXSornceEwoXCGCRGFCIE63SU8bcqiTGDZOniTwooDTEAzyiRqnEiQTBcwxbi32ZjcLLawnPb+c7uQ+ZGWAHplh823GQDqsGgcqBxrOEAg3lAcDAnJlkxpBYkkXCnHJFMp0kioLvGk56ExlCJ82my0kIPZMFgDwo3nulDwYzw+FPruIADCUjCDAKAiEmaA8EAA) where I've been playing around.

Some options:
1. Delete the two we have in favor of [VETS API - PROD - RDS - High CPU Utilization](https://vagov.ddog-gov.com/monitors/225331). Is one monitor good enough or do we need one for all containers in vets-api?
2. Leave them as-is (alive but muted) so we're able to see them from the [Backend monitor dashboard](https://vagov.ddog-gov.com/dashboard/ebq-wxp-m4m/backend-platform-monitors?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1715708274459&to_ts=1715711874459&live=true).
3. Convert query to a metric monitor and use the same query but alert on a fixed (arbitrary?) amount of seconds. (But different containers have different limits so this makes it hard to choose a fixed number.)

**Comment by rmtolmach** [comment]
### High CPU Usage
The query we're using is `avg:container.cpu.usage{kube_namespace:vets-api} by {container_name,env}` which is in nanoseconds. I'm unclear how many nanoconds means "high CPU usage". There's also `container.cpu.limit` which is in nanocores. I had initially thought that dividing `usage/limit` would give us a percentage, but dividing nanoconds by nanocores doesn't seem right.

🐕 [Datadog metrics explorer](https://vagov.ddog-gov.com/metric/explorer?fromUser=false&start=1715116065121&end=1715720865121&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMiZUggYojoAdJnyeE14GhjwwADWeABGcE6RvvIY2cgViBoAtBjyEDwABANYy8C1IvWN2iNRcBRwIhUU-UNOAvJoOFjq2zwgfKCjOSCxWABMicn1aRnZZT5QrFd6lGi5SrVLY7ETNVrtNA+cR9QbDV72CZwKYzeaLFZrDbnYZXG53Y4ICgwhpwvavI4nR7PCIHGLggDMPxS-zwWTewIgRUSH3KVWQGDAGia2igUoRBAgSIAXp5JCJgFABqINPURNloBSIMIdMsAJIAOWWAApZRUMLNphY8RBZvJtDgoLNPgBKAnrDVakQ6jB69gCbZGvTaJkAXSornceEwoXCGCRGFCIE63SU8bcqiTGDZOniTwooDTEAzyiRqnEiQTBcwxbi32ZjcLLawnPb+c7uQ+ZGWAHplh823GQDqsGgcqBxrOEAg3lAcDAnJlkxpBYkkXCnHJFMp0kioLvGk56ExlCJ82my0kIPZMFgDwo3nulDwYzw+FPruIADCUjCDAKAiEmaA8EAA) where I've been playing around.

Some options:
1. Delete the two we have in favor of [VETS API - PROD - RDS - High CPU Utilization](https://vagov.ddog-gov.com/monitors/225331). Is one monitor good enough or do we need one for all containers in vets-api?
2. Leave them as-is (alive but muted) so we're able to see them from the [Backend monitor dashboard](https://vagov.ddog-gov.com/dashboard/ebq-wxp-m4m/backend-platform-monitors?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1715708274459&to_ts=1715711874459&live=true).
3. Convert query to a metric monitor and use the same query but alert on a fixed (arbitrary?) amount of seconds. (But different containers have different limits so this makes it hard to choose a fixed number.)

**Comment by rmtolmach** [comment]
I have created this new metric monitor: [VETS API - {{env.name}} - {{kube_deployment.name}} - {{container_name.name}} - High CPU Utilization](https://vagov.ddog-gov.com/monitors/232784?view=spans). I will watch it and modify it as needed. 
The query we (Chris, Lindsey and I) ended up with was:
```
(
avg:kubernetes.cpu.usage.total{kube_namespace:vets-api} by {container_name,env,kube_deployment} /
avg:container.cpu.limit{kube_namespace:vets-api} by {container_name,env,kube_deployment}
)* 100
```

**Still to-do:**
After we've vetted our new monitors in the UI, export them to terraform then get PR reviewed, merged, and tf applied.

**Comment by LindseySaari** [comment]
Keeping an eye on the monitor, it's live in the UI but the calculation seems like it's not correct

**Comment by rmtolmach** [comment]
> Keeping an eye on the monitor, it's live in the UI but the calculation seems like it's not correct

After many hours troubleshooting, the problem seemed to fix itself! The History graph and the Edit graph were _very_ different. I was messing around and changed the threshold from `85` to `20` and the monitor appeared to come to life. The two graphs were reporting the same numbers! 🎉 I've bumped the threshold to `80` and it's looking good. 
[Slack troubleshooting thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1715883025753539).

- [ ] add the be-notification channel back in to the alert.

**Comment by rmtolmach** [comment]
### SIDEKIQ Job queue size is high

This one used to be a metric monitor. I created a new temporary monitor in the UI to test the query: https://vagov.ddog-gov.com/monitors/233349?view=spans

**Comment by rmtolmach** [comment]
Almost done with this! 
To do:
- [ ] Get this small follow-up PR merged and applied https://github.com/department-of-veterans-affairs/devops/pull/14343
- [ ] Chris is figuring out the case of the duplicated monitors. [Slack thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1716301019208159?thread_ts=1716216549.159889&cid=C045LCF8WU8).

**Comment by rmtolmach** [comment]
All done!
As a reminder [VETS API - {{env.name}} - {{controller.name}} - High 500 Errors](https://vagov.ddog-gov.com/monitors/203472) and [VETS API - {{env.name}} - {{controller.name}} - High 400 Errors](https://vagov.ddog-gov.com/monitors/203672) were kept as anomaly monitors for the following reasons:
- They are relatively stable.
- They are muted but still show up on the [Backend monitor dashboard](https://vagov.ddog-gov.com/dashboard/ebq-wxp-m4m/backend-platform-monitors?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1715708274459&to_ts=1715711874459&live=true). This seems appropriate because the monitor alerts on controller not owned by Platform, so it's more informational.
