### ISSUE TITLE
Redirect Request | Ch 36/PCPG/25-8832 PDF

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#78560]
### Status
**[2024-03-19]** This may become a no-op. The PDF URLs need to change instead of doing a redirect. Will keep open for a while in case that changes.

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [x] Any day after an earliest possible date. **EARLIEST DATE: 3/15/2024**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.vba.va.gov/pubs/forms/VBA-25-8832-ARE.pdf | https://www.vba.va.gov/pubs/forms/VBA-27-8832-ARE.pdf

Please note that this url was previously redirected. The form number has changed twice in the last 6 months. The request to redirect the pdf from version 28-8832 to 25-8832 in October 2023 is #67075.

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by FranECross** [comment]
@chriskim2311 @randimays Just moved this new request to Stretch/Next Sprint. Not saying it should be pulled into the current sprint, but feel free to refine async and it's there in case you want to pivot or need something to pull in. Thanks! cc @jilladams

**Comment by jennymayoco** [comment]
Hi @steele-lm, looping back on this - unfortunately, we're not able to proceed with this redirect request. PDFs are on another server and so we recommend working with the stakeholder to update the PDF URL.

cc @mnorthuis for visibility

**Comment by FranECross** [comment]
@jennymayoco I've moved to our Blocked column and will hold until further notice. Thanks for the info!

**Comment by jennymayoco** [comment]
Hi @steele-lm, we are able to close this ticket? We won't be able to redirect this since it's a document PDF.

**Comment by steele-lm** [comment]
@jennymayoco Do I need to [reach out to Kevin Reid](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67075#issuecomment-1789086271) to implement this change?

**Comment by jennymayoco** [comment]
@steele-lm looping in @jilladams who helped with the first redirect. Jill, would Kevin Reid be a good contact to update the redirect? [Previous redirect for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67075)

**Comment by FranECross** [comment]
Closing per comments above; a redirect by the PW team won't be implemented.
