### ISSUE TITLE
BE | Profile | Direct Deposit | Identify PPIU Controller Traffic

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#78579]
## Background
Michael Harlow (EVSS) is still seeing traffic to EVSS's ` /wss-ppiu-services-web/rest/ppiuServices/v1/paymentInformation` endpoint (see this [thread](https://dsva.slack.com/archives/C03P6C3FYMR/p1710511187009039)).

In VA.gov, we're still seeing traffic to the PPIU endpoints which are used to view and update EDU direct deposit information.

We've confirmed that the VA.gov Profile does not make any calls to these PPIU endpoints.  I haven't been able to find any calls from other parts of VA.gov website or the VA mobile app.

As of yet, I haven't been able to determine where this traffic is originating from (there is no information in the request). 

#  Tasks
Determine where this traffic is originating from, by....
- [x] Reaching out to Joe Niquette who is usually reviewing DD logs for fraudulent reasons.  He may be able to help shed some light on where these requests are coming from.
- [x] Add a feature flag to the PPIU controller, that when switched on, will return an error message stating that the endpoint is going to be decommissioned.

## Acceptance Criteria
- [x] Identify where the PPIU traffic is coming from.

**Comment by tpharrison** [comment]
Sent out notifications in #benefits-portfolio and #benefits-engineering channels informing them of our intent to turn on the feature flag in production.

**Comment by tpharrison** [comment]
Turned on the feature flag on Mar 21, 5:20pm.  Reviewed the possibility that these requests are coming from a browser extension, but that doesn't seem to be the case.

All responses are returning 403s  - https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%40http.url_details.path%3A%2Fv0%2Fppiu%2Fpayment_information%2A%20&cols=host%2Cservice%2C%40http.status_code%2C%40payload.user_uuid&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=336994431213512540&storage=online_archives&stream_sort=time%2Cdesc&viz=stream&from_ts=1702581364262&to_ts=1702667764262&live=true
