### ISSUE TITLE
Additional Quality Check for Facility Locator Edge Case Dashboard

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78584]
### Description:
Need to review and QC the Facility Locators edge case dashboard that was delivered a few weeks ago. We received some feedback that there is missing data in a few different spots, making it unusable in its current form. 

**Message from Michelle:**

> "I'm sorry to report that the dashboard is missing expected data in some areas and appears to report incorrect data in others. I don't think it is usable in the current state.
> 
> The graph appearing under the What type of facilities are people searching for?` heading actually represents the number of times a user has clicked through from a search result to the corresponding facility page for more information, not what people are actually searching for. The expected data is the percentage of searches for each type of facility
> 
> VA health (all)
> Urgent care (all)
> Emergency care (all)
> Community providers in VA's network
> Community pharmacies in VA's network
> VA benefits
> VA cemeteries
> Vet Centers
> (I included a link to a similar GA search in an earlier comment)
> 
> Click through is itself a desirable metric but the graph seems to only capture the click throughs to modernized VAMC and Vet Center pages and does not include data for two facility types, which both follow the pattern of https://www.va.gov/find-locations/facility/ facility id
> 
> VA benefit facilities have a facility id which begins with vba, such as VA Regional Benefit Satellite Office at Thomas S. Foley U.S. Courthouse
> VA cemeteries have a facility id which begins with nca, such as Cheltenham Veterans Cemetery
> I do not think the data presented in the Search refinement block is correctly defined. It indicates 27 searches were refined and 5,679,171 searches were not. (DOMO filtered to show data for the month to date)
> 
> By comparison, this GA page shows the refinement rate varying from one facility type to another, across 341,751 searches and an average of 5.99% for the same time period.
> 
> screenshot from DOMO
> GA table
> Presenting the average rate of refinement would be more useful than the number of refined searches compared to searches without a refinement. Most useful would be the refinement rate per facility type, as shown in the GA table above.

---

### Tasks:

- [ ] Perform quality check of edge case dashboard. 
- [ ] QC data with team.
- [ ] Schedule meeting with Michelle to review changes.

### Acceptance Criteria:

- [ ] Changes to the dashboard have been made.

**Comment by johnny-jesensky-adhoc** [comment]
Closing as a duplicate of https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/76514.
