### ISSUE TITLE
[MVP] Copy updates - Find VA Forms Search

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7858]
## User Story or Problem Statement
As a Veteran or other user, I need accurate information when interacting with the Find VA Forms Search so I understand how to use the product.

### [Latest copy: VA-forms-slp-conversion-paths-110519-updated-041020.docx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-forms-slp-conversion-paths-110519-updated-041020.docx)

---
## Tasks
- [x] Update Drupal content - @jenniferlee-dsva 
- [x] Make "read more" link updates to blue cards - Nick or Kelson
  - [x] File a disability claim - 
    - https://www.va.gov/disability/how-to-file-claim/
  - [x] Apply for the GI Bill and other education benefits - 
    - https://www.va.gov/education/how-to-apply
  - [x] Apply for VA health care benefits - 
    - https://www.va.gov/health-care/apply/application/introduction

## Acceptance Criteria
- [ ] Find VA Forms - Search reflects the latest copy changes

---

![image](https://user-images.githubusercontent.com/13204473/79006488-4896ba00-7b27-11ea-82a3-fba64b7ab748.png)

**Comment by MickinSahni** [comment]
Related to convo in #6900

**Comment by jenniferlee-dsva** [comment]
The drupal copy has been updated and set to "publish" - should go out in Monday's regular deployment.

**Comment by ncksllvn** [comment]
This will go out today

**Comment by MickinSahni** [comment]
2020-04-13 PW Standup
- Can be validated after today's deploy
  - cc @tzelei for awareness since we know you're working on our test cases

**Comment by MickinSahni** [comment]
Hey @ncksllvn can you make another link change? [This is related](https://dsva.slack.com/archives/C52CL1PKQ/p1586908461492300) to the Direct Deposit page that was taken down. 

The **Change your direct deposit information** link needs to be changed:
* From: `/change-your-va-direct-deposit-and-contact-information` 
* To: `https://www.va.gov/change-direct-deposit/`

**Comment by tlei123** [comment]
@lwalsh617 , will these copy changes be reflected in your design-screens in InVision/Zeplin?

Please let me know.  Thanks much.

**Comment by jenniferlee-dsva** [comment]
Hi @tlei123 - the search page copydeck reflecting these updates are not in InVision. They are in the product repo referenced above: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-forms-slp-conversion-paths-110519-updated-041020.docx

**Comment by MickinSahni** [comment]
Couple notes:
- The **Get more records and documents online** link is incorrect on [_staging_](https://staging.va.gov/find-forms#manage-your-va-and-other-infor) according [to the latest copy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7858#issuecomment-614629086), but correct on [_prod_](https://www.va.gov/find-forms#manage-your-va-and-other-infor)
  - It should be `/records/get-military-service-records` and in staging it's `/records/`
  - Once we've confirmed the correct behavior, @stephorkandatx, we can open up a new ticket to capture this once or re-open this one  
- For "FF - Search MVP - A11y - ARIA-live", it looks like there's one (1) aria-live. But that looks to be specific to the breadcrumbs so maybe it's a sitewide problem, @ncksllvn @kelsonic?

**Comment by stephorkandatx** [comment]
@jenniferlee-dsva based on our call earlier today, we determined that there were a few discrepancies between what is set up in Drupal, and the last copy of the copy deck that was provided. 
Specifically, the two major differences were that "Request your medical record" had been removed ("Request your medical records, including DD214" is still set up) + "Get more records and documents online" was added. 

I generated a version of the copy doc to reflect these two changes + uploaded it to GH. I referenced what we have set up in staging & production as my guideposts for copy & links. Can you spot-check my work to make sure it's what is desired? They are at the bottom of the second page if that helps. 

Link at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-forms-slp-conversion-paths-110519-updated-042020.docx 

cc @tzelei when we get confirmation of these two changes, it will impact the test cases a bit.

**Comment by jenniferlee-dsva** [comment]
@stephorkandatx - thank you; i noticed it was also missing the 'more information' links, so i copy/pasted those in from Drupal page. It's uploaded to product folder here: 

[VA-forms-slp-updated-042020-so-jl.docx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/VA-forms-slp-updated-042020-so-jl.docx )

fysa @tzelei ^

**Comment by jenniferlee-dsva** [comment]
Oh - just noticing a couple minor points for correction ^ -- just so we're all on the same page for QA and source of truth:

There are actually 2 different `records `links: 
1/ Military records - this one says, 'Request your military records including DD214' and it links to the node ID 472 (will resolve to live page: https://www.va.gov/records/get-military-service-records/ )

2/ Get more records and documents online - this one links to node 79 (resolves to `https://www.va.gov/records/` )

^ They are both correct to have on the forms search page. I'm sorry I may confused us, @MickinSahni  @stephorkandatx @tzelei

**Comment by stephorkandatx** [comment]
Thanks @jenniferlee-dsva!
