### ISSUE TITLE
Redirect foreign programs page

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#78591]
## Description
Redirect this legacy page:

- [Information for Students Wishing to Attend Foreign Schools](https://www.benefits.va.gov/gibill/foreign_schools.asp)

To this modern page:

- [Foreign programs](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/)

## Tasks
- [x] JM: Share redirect plan with stakeholders
- [ ] Stakeholders: Approve redirect plan
- [x] JM: Open redirect ticket

## Criteria
- [x] IA opened redirect ticket

**Comment by jennymayoco** [comment]
Hi @aprocik1! Are we able to close this ticket since this set of links is being tracked in the redirect ticket as well as in the IA tracker?

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/fd680adc-3d60-4763-853e-667321eb5a3b)
