### ISSUE TITLE
Update content about single direct deposit account requirement

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#78597]
## Issue Description
VA is in the process of telling Veterans about a change for those who currently have more than one bank account listed for disability compensation, pension, and education benefit payments. The same account needs to be used for all of those benefits, starting April 20, 2024.

CAIA and the Pension team are working through changes to their direct deposit and review/confirmation pages to support this change. We should be able to re-use approved content (and design component) from pension, which is expected from CAIA **on 3/11**, in the 526 form. Desired date for production is **3/20/2024**.

### User stories
As a claimant, I need to know that the direct deposit info I provide won't be updated until after a decision is made on my claim, and only if an award is made.

As a claimant, I need to know that if I already receive education payments, those will use the direct deposit info I list in this 526 claim if and when I receive a disability award. 

### Design
in [Figma](https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=0%3A411&mode=design&t=857cgITlNMUBg7al-1)

### References: 
VA.gov's [Change your VA Direct Deposit](https://www.va.gov/change-direct-deposit/) page
[Slack discussion - initial creation of ticket](https://dsva.slack.com/archives/C06E83RNLQM/p1708959156208089)
[Slack discussion - in progress questions](https://dsva.slack.com/archives/C053UDWMH7U/p1710512199691099)
Pension's ticket [77020](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/77020)
CAIA ticket [77464](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77464)
Pension's [FIGMA files](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2146%3A2284&mode=design&t=z7ofhG2z9Fagu35q-1)

---
## Tasks
- [ ]  Update components and content as per mocks (total of 5 changes) - https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=0%3A411&mode=design&t=iHBzA1aKp0euVXsf-1
**1. Changes when no pre-fill**
1.1 Add content A to 'Add new bank account' view
1.2 Add content F to 'Payment Information' view
<img width="1115" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a34fc50365fd2ac7a56e8cd65449ef48c7e35c8e/image.png" alt="image.png" />

**2. Changes with prefil**
2.1 Add content E to initial 'Payment Information' view
2.2 Add content A to 'Add new bank account' view
2.3 Add content D to 'Payment Information' view. This displays after a second account has been added.
<img width="1072" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8303d662bcef207f561dc9dde030cce2996056ba/image.png" alt="image.png" />

## Front end tasks

- [ ] Ensure the page is styled according to design spec.
- [ ] Ensure the back end data from API is displayed in local and review instance
- [ ] Ensure unit tests are available.
- [ ] Ensure your code changes are covered by E2E tests
- [ ] Run axe checks using the Chrome or Firefox browser plugin
- [ ] Test for color contrast and color blindness issues
- [ ] Zoom layouts to 400% at 1280px width
- [ ] Test with 1 or 2 screen readers
- [ ] Navigate using the keyboard only

## Acceptance Criteria
- [ ] Above tasks are complete
- [ ]  Designer comments on this issue to approve page styling
- [ ]  Unit tests pass
- [ ]  E2E tests cover current code and regression
- [ ]  End-to-end tests show 0 violations.
- [ ]  The data returned matches API response (for given user or scenario)
- [ ]  All axe checks pass
- [ ]  All color contrast checks pass
- [ ]  All zoom testing passes
- [ ]  All keyboard checks pass
- [ ]  All screenreader checks pass
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mengA6** [comment]
We've made some design updates since the screenshot on this ticket, so that's out of date. Refer to [Figma](https://www.figma.com/file/xQpwHbmQq000y6udi20bYM/526-payment-information?type=design&node-id=0%3A411&mode=design&t=857cgITlNMUBg7al-1) for the up-to-date design
