### ISSUE TITLE
SLO for VA Teams

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#78607]
## User Story
As a VA Team, I would like to see metrics related to the status and performance of authentication services on VA.gov, so that I am provided with immediate, comprehensive information about the status VA.gov authentication services. Additionally, these metrics will provide us thorough understanding of the authentication service's performance and help create Service Level Agreements between OCTO Identity and VA teams

I would expect to see the following real-time monitors broken down by Authentication Broker and Credential Service Provider where applicable
- [ ] Up-time and down-time of VA.gov's authentication services
- [ ] Graph of historical performance data
- [ ] Average response times from the authentication services
- [ ] Metrics of authentication events 
    - [ ] Sign in / Login (attempts, success, failures)
    - [ ] Register / Sign up (attempts, success, failures)
    - [ ] Verify / "Identity verification" (attempts, success, failures)
    - [ ] Sign out (attemtps, success)
- [ ] Metrics of concurrent verified (LOA3/IAL2) and unverified (LOA1/IAL1) users using VA.gov
- [ ] Metrics of partner applications availability (VA.gov, My HealtheVet, eBenefits, VA Mobile, Oracle Health, VA OCC Mobile, Accredited Representative Portal*)
- [ ] Number of issues reported by users (as pertains to authentication events)

## Tasks
- [ ] Create tickets to address each of the following real-time monitor section and provide context as to which the Identity team can provide data for
    - [ ] For the metrics we cannot provide data for create a README.md as to why and why it would not benefit the Veteran

**Comment by jimcconnelly** [comment]
Closed - just a user story
