### ISSUE TITLE
UX | Profile | Maintenance | Account security user flow updates

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#78616]
## Background
We need to double check the user flow for account security.  The solution is probably just to add another fork/screen related to system outages, but need to do some more thinking on it. Here's the background:

1. We don't have a generic system down mock-up with nothing on the page but an alert, but there is one in production
2. The current user flow has a "is the system down" step that shows an alert with only "add MFA" in the account set up section. That alert would be shown if the call to vaProfile returned a status of ‘SERVER_ERROR’. That boils down to MPI not being available via va profile to get their whole profile information. Since the authentication layer (id.me etc) would still be functioning at that point, the account setup section would still be something we could access and show information around, so we need to determine whether or not we should add the "verify your account" prompt too (or at least capture it as a state in the docs)

In discussing this with Adam, he said:
>its almost like the left hand side of the flow should be two pronged itself for the No flow.
>- No, there is a system wide outage -> show everything is down/broken alert thingy (with no Account setup section)
> - No, the system returned a ‘SERVER_ERROR’ / mpi is down and we need to handle it dynamically -> show what you have right now in the flow for No

But as we solve for this, we also need to consider that LOA1 people aren't in MPI (at least we don't think so).

## Tasks

- [x] Determine if we need to add an additional screen with a system down alert and no account set-up section, and if it only applies to LOA3
- [x] Update the flow accordingly
- [ ] Add any helpful info to our use case docs

## AC

- [ ] Figma files are updated

**Comment by andaleliz** [comment]
@mtcA6 would it be preferred for me to pick this up next over the epic we talked about in planning today? I'm now seeing that this has a predicted sprint on it, for the next one, and I'd be able to work on this as easily as I could the other one.

**Comment by mtcA6** [comment]
I think this does make more sense to pick up next since it's a little more defined then the patterns ticket. 

Maybe we carve out some refinement time for discussing the patterns?

**Comment by andaleliz** [comment]
@mtcA6 sounds good to me, I will pick this up in the current sprint.

**Comment by andaleliz** [comment]
@adamwhitlock1 can you please take a look at the steps in the flow on [this page](https://www.figma.com/file/05k2PTmuDVgBj2HnzUZayg/Profile---Account-Security?type=design&node-id=0-1&mode=design&t=JIdy5Yz36W3c7Eop-11) and let me know if I've accurately captured whats in the description of the ticket? I left a couple of questions about specific screen aspects in the Figma file, but I want to make sure that overall the flow is accurately represented now.  Thanks!

**Comment by andaleliz** [comment]
Figma comments resolved; once I get confirmation the flow is accurate, I'll update the use case docs n close this out.

**Comment by adamwhitlock1** [comment]
Flow looks accurate now, thanks for resolving all the Figma comments.

Everything looks great Liz!

**Comment by andaleliz** [comment]
Thanks for taking a look Adam! 

Use case docs have been updated; closing this out.
