### ISSUE TITLE
Update Types of Link Page: Add new Google Link rules

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#78615]
New rules regarding links to Google on the PW need updating. Based on our Google Link audit and [subsequent Slack clarification conversation](https://thesocompany.slack.com/archives/C02LYB7QXS5/p1710522702513549) with leadership, only links to Google Drive are not allowed. All other links to Google are okay. Our "[Types of Links](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2737930708/Types+of+links)" page was updated recently with the new "No Links to Google Drive" rule. But we need to update it again with these recent additions. Our readers need this clarification since the rule is rather nuanced.

The Above Update [Took Place Two Sprints ago](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78613). The Style Guide now contains [a section on Google Drive links](https://vfs.atlassian.net/wiki/spaces/AP/pages/621609007/Grammar+and+punctuation#Links-to-Google-Dive). 

This ticket is strictly about adding a Note that the "Widget Connector" in Confluence is NOT a workaround. VA personnel still cannot see Google related items even if they are "embedded" into the PW page via the "Widget Connector." 

### TASKS

- [x] Draft Language to include widget guidance
- [x] Share with team for approval
- [x] Update page

### Definition of done

- [x] Page updated with new language.

**Comment by taylojill** [comment]
@BSmolensky provided the wording for the page. I added an info box with a Note.

**Comment by jknipes** [comment]
Work is completed
