### ISSUE TITLE
Video Recording: Getting Help from the Platform in Slack

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78628]
## Description 

In an effort to create accessible content for VFS Teams, we want to add video to each of our public facing articles. This ticket will house the task of recording a video for the following page: 

- [Getting Help from the Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack)

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Record an overview video recapping the content on the page (walk through step-by-step processes if it makes sense)
- [x] Notify Platform Content Team in their channel that video has been added
- [x] Verify Platform Content Team has reviewed the content and ensure it is published
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by AnthonyWFlowers** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/assets/161509257/dcc5ea2a-e9c3-47c9-bf40-5c046b4cbc77


https://github.com/department-of-veterans-affairs/va.gov-team/assets/161509257/c1f81eb9-fd0f-499f-97f1-87ae39cb16ae

**Comment by AnthonyWFlowers** [comment]
Content is confirmed updated live. 
@alyssagallion this should be good to close!
