### ISSUE TITLE
Video Recording: Incident Management Platform Site Page

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78629]
## Description 

In an effort to create accessible content for VFS Teams, we want to add video to each of our public facing articles. This ticket will house the task of recording a video for the following page: 

- [Incident Management](https://depo-platform-documentation.scrollhelp.site/support/incident-management)
---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Record an overview video recapping the content on the page (walk through step-by-step processes if it makes sense)
- [x] Notify Platform Content Team in their channel that video has been added
- [ ] Verify Platform Content Team has reviewed the content and ensure it is published
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by AnthonyWFlowers** [comment]
@alyssagallion Updated and added to Launched Support Docs
