### ISSUE TITLE
Video Recording: Support Best Practices

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78627]
## Description 

In an effort to create accessible content for VFS Teams, we want to add video to each of our public facing articles. This ticket will house the task of recording a video for the following page: 

- [Support Best Practices](https://depo-platform-documentation.scrollhelp.site/support/support-best-practices)

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Record an overview video recapping the content on the page (walk through step-by-step processes if it makes sense)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Assign to David when has access.

**Comment by AnthonyWFlowers** [comment]
Video recording and uploaded to Platform YT channel [here](https://youtu.be/m5kBulhj3cM)
Video added to "Support Best Practices Page"
One update to page adding a link to the "here" on sentence "Please, create a ticket following the steps outlined here"
Link is to the ticket creation knowledge page

**Comment by AnthonyWFlowers** [comment]
Moved to you Alyssa, thank you!
