### ISSUE TITLE
Add Videos to Platform Site Pages 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78626]
## Description 
In an effort to create accessible content for VFS Teams, we want to add video to each of our public facing articles. This includes:

- [Support Best Practices](https://depo-platform-documentation.scrollhelp.site/support/support-best-practices)
- [Getting Help from the Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack)
- [Incident Management](https://depo-platform-documentation.scrollhelp.site/support/incident-management)

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] All attached tickets are completed
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Tickets in backlog. Closing epic.
