### ISSUE TITLE
[FE] 10-10 EZ & EZR - Performance Monitoring: Update downtime notification services to remove the service dependency between the forms

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#78638]
## Background
As a result of a late daily deployment which introduced a PR that impacted submissions and access to the 10-10EZ, authenticated Veterans were impacted overnight and into the next morning with not being able to access the form.
During the triage process, the team also decided to configure a maintenance window for the product to avoid confusion and frustration for end users.  However, because the maintenance windows are configured in terms of upstream dependencies, it was necessary to take both the 1010ez and 1010ezr applications offline, even though only the former was affected. 

We need to add maintenance windows to each 10-10EZ and 10-10EZR forms.

> From Adrian:
>The MHV teams are [following this pattern](https://dsva.slack.com/archives/C018V2JCWRJ/p1706803015085569?thread_ts=1706802786.997869&cid=C018V2JCWRJ) with an umbrella PD service (called mhv_platform) that disables all apps, and individual services for each app
>
>![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/a0921dbf-c65d-4ad1-b94c-dac36ef29c25)

> 
>you have everything you need - the [docs are here](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-AddinganewPagerDutyservice), with the exception that they need to be updated to say to update the vets-api config in the manifest repo instead of the vets-api repo (I believe that [@Stephen Barrs](https://dsva.slack.com/team/ULY2TEZUK) has raised that)

#### Resources
- Comment from Lihan in BE ticket #76791
     - Frontend needs to add each maintenance window to each form https://github.com/department-of-veterans-affairs/va.gov-team/issues/76791#issuecomment-2004914826

## Tasks
- [x] Review the comment from Lihan in the BE ticket
- [x] Review the instructions provided in the [Platform document](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-AddinganewPagerDutyservice) to create new, more granular services for the EZ and EZR
     - **EXCEPTION** the document has not yet been updated to state "**Update the vets-api config in the manifest repo**" instead of the vets-api repo
     - You will want to update the "manifest repo"
- [x] Update the EZ and EZR frontend to reference the services in the Platform downtime component
- [x] Create a maintenance window for each application for testing in Staging

## Acceptance Criteria
- The 10-10 EZ and EZR will be separated in Pagerduty so that we can set maintenance windows for each application independently.

**Comment by longmd** [comment]
Both applications have been verified with the independent services. See screenshots below:

**EZR:**

![Screenshot 2024-03-21 at 16 00 37](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/cb855566-1d34-4ba9-9c6f-22cebc54465e)

**EZ:**

![Screenshot 2024-03-21 at 16 06 11](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/a3365132-d618-409a-b175-3aa0dc47474e)
