### ISSUE TITLE
[BE] Don't call CHIP refresh_appointments for Oracle Health sites

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#78648]
## Description
As a veteran, I want to be able to submit travel claims for Oracle Health site visits

Details:
For OH sites, we don't have any concept of check_in so we should not call CHIP's refresh_appointments endpoint

## Tasks
- [ ] [BE] **Modify lorota service check_in_date to not call the endpoint for OH facilities**
- [ ] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
