### ISSUE TITLE
[BE] Don't call CHIP set_echeck_started for Oracle Health sites

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#78647]
## Description
As a veteran, I want to be able to submit travel claims for Oracle Health site visits

Details:
For OH sites, we don't have any concept of check_in so we should not call CHIP's set_echeckin_started endpoint

## Tasks
- [x] [BE] **Modify patient check_ins controller to not call the endpoint for OH facilities**
- [x] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
