### ISSUE TITLE
SOCKS access for [Sean Midgley (new desktop access / old desktop access removal)]

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/va.gov-team#78679]
### Your Name

Sean Midgley

### Your Email

sean.midgley@oddball.io

### Your GitHub Handle

Midge-dev

### Your Role and Team

Frontend Engineer - Non-Disability Experience

### Product Manager (PM) name and email

Laura Steele laura.steele@coforma.io

### Product Owner (PO) name and email

Emily Theiss emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCVX9FL6yaZmotwqqAMOxXt/E8z8zPHs9DOMS3TN2BamtoA2ampAU485IMgADBbICA4ZQxY6oCMJEVjqtScVAYTj+V72BNaC6kFeuP2zyzjSZcWcoRpj+VqV03NAyQatQwUFcJPVE5yV+f548zXfeZNhw1RVv2n4KZMDrIRnevHbs8q1n1L1ECgkEqsV0xq/xe5c2o4Q3Dzwyt+5QR+E2R3uTwo99T1/C9ceG2L5aXtEUq6wZ43uECRYxmNl5tTNi4h/YaTnW6x+lQh6/A1HK2GyK+P9iEKMzvoEm0++eLAjGPgFgUAowl/IcpBpfA6XJ3/43JUbBwtPKprCWocwpiey/li9mLKJ6vJQfeA+XhyNsFxVE3vy/wsqw7TGBOn5OXsk06fWKhdCykXiBpPkGoVysgPWKBGlNfv15gvaqHlHslCe99Sz51EDz268DfNfYXDJ/iXCHoV48fLOnHMEXsataQedSEwIxCJVZWMin/9ATTuoo41ZQ4fgosW6loH6ms= midge@Dybbuk-Dev

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/2e58b1e6-6b86-4e0c-bb92-b767a3685f14)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/cc99c03d-f0da-4a03-99cc-986804f4fd5b)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by Midge-dev** [comment]
I'd like to request access removal from my old desktop as well please. Wasn't sure how to go about this. Tyvm!
https://github.com/department-of-veterans-affairs/va.gov-team/issues/71280
