### ISSUE TITLE
CMS deploy to be included in deployments page [Footer Ticket #82945]

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#78673]
## Issue Description
va.gov-cms code deploys the Drupal CMS, and currently there is no information regarding this on Platform Website.
Details on that deployment should be included on this page: 
https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments

### SME for documentation assistance:
 - @7hunderbird Tyler Bird
 - @MDomngz Marisa Dominguez
 - cc: @gracekretschmer-metrostar 
---
## Tasks
- [x] Reach out to CMS DevOps group, determine SME
- [x] Determine w/ CMS which sprint this ticket can be worked on
- [x] Update page with SME
- [x] Check for Launch Blocking issues

## Acceptance Criteria
- [x] Deployments page is updated and ready for Content Team daily deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/78673?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by taylojill** [comment]
Message sent to three identified SMEs via [original GitHub ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82945). Waiting for response.

**Comment by taylojill** [comment]
Follow-up message sent to SMEs and requestor via original GitHub ticket. Waiting for response.

cc @jknipes

**Comment by taylojill** [comment]
Follow-up message sent to SMEs via platform-content channel.

**Comment by michelle-dooley** [comment]
@taylojill - we will get back to you on this work after a couple sprints when we complete BRD/CMS Deployment overview. If you could provide some more details on what details you need more information on we may be able to provide some of that in the interim.

**Comment by taylojill** [comment]
Hi @michelle-dooley - our team received a request to add Drupal CMS deployment info to an [existing platform website page](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments), reference ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/82945). I added Drupal CMS to the table under the Automated deployment schedule heading, and was hoping to get the information to complete the table, see screenshot below. I assumed this was the best location, and that it would satisfy the request. Please let me know what you think.

cc @jknipes 

![2024-05-28_08-36-44](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97645218/c308e96f-f35e-48ed-aee8-d9fa4ced1b21)

**Comment by taylojill** [comment]
Per this [Slack message](https://dsva.slack.com/archives/CL181NRJQ/p1717096454281639?thread_ts=1716929567.423409&cid=CL181NRJQ), the CMS is [working this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82945) in their current sprint.

**Comment by taylojill** [comment]
va.gov-cms information added to table as requested. Updated page will publish by 5pm June 5, 2024.
