### ISSUE TITLE
Document useful queries for reports of outdated information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78696]
## Background
Add documentation to our [Product Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/launch-materials/product-playbook-incident-response-plan.md) for Find a Rep around how to run a query that will pull up a list of all reports of outdated information, as well as how to delete any reports.  This could be a section ‘Useful Queries for Flagged Rep Data’.

## Tasks
- [x] Document how to pull a list of reports of outdated information
- [x] Document how to delete a report of outdated information 

## Acceptance Criteria
- [x] Other teammates in the VA will be able to reference how to run a query, if they're interested in seeing how many reports of outdated information are coming from the Find a Representative product.
