### ISSUE TITLE
Copy of [Design] Create 3 components in MHV - UA Library to use in Unified Checkin Figma File

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#78701]
## Tasks
- [x] Create Task card (new component) in MHV - UA Library to use in Unified Checkin Figma File
- [x] Create Appt details (needs new status) in MHV - UA Library to use in Unified Checkin Figma File
- [x] Create Appt list (needs new status) in MHV - UA Library to use in Unified Checkin Figma File
- [x] Publish
- [x] Switch components in Unified Checkin Figma file

### Who needs to review? Check all that apply.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [x] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [x] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets
