### ISSUE TITLE
Investigate Approval Process for Platform Support Responses Edits

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78719]
## Description 
In order to reduce the chances of the [Platform Support Responses](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=0) being edited and resulting in Support Bot/Looker Data dashboards breaking, we need to investigate how to use the Google Sheet Approval process. In the event that someone makes a change to the spreadsheet, it would require approval before the change is made. This would reduce the chances of errors being made. 

Initial documentation found: https://support.google.com/drive/answer/9387535?hl=en&co=GENIE.Platform%3DDesktop

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify the workflow that someone would follow to request approval for edited information
- [x] Identify if there are any warning signs if something is about to be edited
- [x] Identify what the approval process looks like for any changes
- [x] Discuss options on standup with Alyssa and team
- [x] Implement approver process to the spreadsheet
- [x] Demo for the team 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by davidpetras** [comment]
- Google sheets does not provide an automated way to require an approval for edits, all approval requests have to be manually submitted.

- Instead the "Submissions" page has now been protected, which in turn will provide a warning when you make an edit to the page and will require you to acknowledge and confirm you want to make changes. 

- This will hopefully alleviate some of the issues occurring within looker when the document gets edited by reducing unwanted edits to the document.
  - This was tested and confirmed to not impact support bot
