### ISSUE TITLE
Discovery: Investigate Database Solution vs. Spreadsheet for Support Bot

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78720]
## Description 
We would like to investigate potential solutions that would replace the Support Bot in the future. One such idea has been a database. This ticket is intended to investigate options and document them here: [Phase Two Support Bot Storage: Spreadsheet to Database](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3033956393/Phase+Two+Support+Bot+Storage+Spreadsheet+to+Database)

Note: This is a research ticket, not an execution ticket. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ]Identify problems with current solution
- [ ]Identify needs for a solution in the future
- [ ]Identify potential solutions to replace the spreadsheet for future
- [ ]Document them all on the page listed above
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
