### ISSUE TITLE
Discovery: Update Style Guide: Embedded Video Thumbnail Caption Rule

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#78724]
As the Platform continues to pivot toward more video content, we need to shore up our guidance for videos. One issue that keeps coming up -- and therefore seems like a good candidate for our first video guidance update -- is embedded videos. 

Currently we are not asking creators to put captions on the video thumbnails but we do not have this rule in writing. I think we need to come to a consensus as a team on what our exact policy on embedded video thumbnail captions will be. 

## PEOPLE
If we need to ask Accessibility team questions, talk to Martha Wilkes and Jaime K Fay.

### TASKS

- [x] Contact Accessibility SME for guidance. 
- [x] Discuss embedded video thumbnail caption policy options as a team.
- [x] Come to a team consensus on our embedded video thumbnail caption policy

### Acceptance Criteria

- [x] PCT has had a through discussion of the pros and cons of video thumbnail captions.
- [x] PCT has come to a consensus about what that policy should be going forward.

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/78724?planning-poker) with Zenhub @CherylEvans

**Comment by BSmolensky** [comment]
After completing my research on this issue, I learned that it is impossible to add captions to embedded videos due to the way Confluence encodes embedded videos. However, I did learn that there are two ways to embed videos and they look very different from each other. 

So I am going to close this ticket and call it done. I completed a lot of discover here. I am also going to create a new ticket -- in keeping with the original spirit of this ticket -- to have the PCT team look at these two different ways of embedding videos and decide as a team which one we like better. Then update the style guide with that advice.
