### ISSUE TITLE
Determine how to make transition between date range screens apparent

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#78744]
## Issue Description
Originated from comment in [Toxic Exposure: Gulf War Hazard 1990 Date Ranges#73848](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/73848#issuecomment-2007799767)

I created this CAIA intake request to get a recommendation on the problem: 
[Accessibility Request from Disability Benefits team: focus element when transitioning between multiple date range screens #78730 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78730)

---
## Tasks
- [x] Coordinate with CAIA on a recommendation
- [x] Make design changes, if needed
- [ ] If the recommendation is larger in scope than just toxic exposure, make another design ticket - N/A
- [x] Communicate implementation to Christine - in ticket [Toxic Exposure: Make transitions between date range screens more apparent#79125](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79125)

## Acceptance Criteria
- [x] Above items completed

**Comment by mengA6** [comment]
updated design with [option 2 recommendation from CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78730#issuecomment-2008103253) and made implementation ticket [Toxic Exposure: Make transitions between date range screens more apparent#79125](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79125)
