### ISSUE TITLE
Move FAR controllers (and serializers) to new module, update search to use our new models/relationships

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#78745]
## Background
Before picking this up, will need to:

1. Recreate rep and org tables (and do some cleanup) https://github.com/department-of-veterans-affairs/va.gov-team/issues/80656
2. Create new reps, orgs, and org_reps models https://github.com/department-of-veterans-affairs/va.gov-team/issues/78732

After this, we will be ready to integrate with the OGC Accreditation API.

## Tasks
- [x] Move FAR controllers to new module
- [x] Move FAR serializers to new module
- [x] Update search to use new models/relationships
- [x] Need to confirm that serializers contain all attributes necessary for frontend
- [x] New feature flag find_a_representative_use_accredited_models added to flipper as needed. One could also remove the feature flag check or change it to the original flag. I thought having a separate one might be nice for testing in lower environments and providing the front end in production a safety switch - have the old and new integrations in the front end and let the feature toggle decide which endpoint the frontend uses.
- [x] Need to write specs for the serializers
- [x] Need to finish writing specs for the controller and remove/rewrite the 2 placeholder specs
- [x] Need to write a spec for find_with_full_name_similar_to added to the AccreditedIndividual model
- [x] Need to perform more local testing on search results to make sure new and old return the same subset of individuals. This will require creating duplicate data in local db for the new accredited_x tables and the old veteran_x tables.

## Acceptance Criteria
- [ ] Find a Representative controllers and serializers have been moved to our new module configuration, with some optimizations along the way.  
- [ ] The controllers will be available to use, but no data flowing in until we're connected to the Accreditation API

**Comment by oddball-lindsay** [comment]
Chat more to think about if we need to include information on if organizations can accept digital submission

**Comment by oddball-lindsay** [comment]
ID for join tables are not using UUID.  UUID would be consistent, but beyond that it doesn't seem to have significant impact (unsure currently if/who will reference this). Still, might as well explore and we can make the final call after we see what it looks like.

**Comment by oddball-lindsay** [comment]
Create a new join table, then update references.  Will pursue UUID (from discussion yesterday), but easier to do with the new table.

**Comment by oddball-lindsay** [comment]
After this model change, we'll drop the old join table.

**Comment by oddball-lindsay** [comment]
Find a Rep: search by rep type

Appoint MVP: search by rep name only (across all rep types)
Appoint v2: search by rep name AND organization name

Dev is currently working to support MVP, we'll need to add in the organization search functionality later for v2.

**Comment by jvcAdHoc** [comment]
EOD before vacation + back to LH update:

- [draft pr to add new controller and serializers](https://github.com/department-of-veterans-affairs/vets-api/pull/16861)
  - Need to confirm that serializers contain all attributes necessary for frontend
  - Need new feature flag `find_a_representative_use_accredited_models`. One could also remove the feature flag check or change it to the original flag. I thought having a separate one might be nice for testing in lower environments and providing the front end in production a safety switch - have the old and new integrations in the front end and let the feature toggle decide which endpoint the frontend uses.
  - Need to write specs for the serializers
  - Need to finish writing specs for the controller and remove/rewrite the 2 placeholder specs
  - Need to write a spec for `find_with_full_name_similar_to` added to the `AccreditedIndividual` model
  - Need to perform more local testing on search results to make sure new and old return the same subset of individuals. This will require creating duplicate data in local db for the new accredited_x tables and the old veteran_x tables.

**Comment by jvcAdHoc** [comment]
> Need to perform more local testing on search results to make sure new and old return the same subset of individuals. This will require creating duplicate data in local db for the new accredited_x tables and the old veteran_x tables.

One way to do this to get around making test data would be to compare the sql generated for the same request params for both controllers

**Comment by holdenhinkle** [comment]
Working on this (from Jon's notes above):

- [ ] Need to confirm that serializers contain all attributes necessary for frontend
- [ ] Need to write specs for the serializers
