### ISSUE TITLE
[Research] 10-10EZ - TERA : Conduct research sessions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#78751]
## Benefit to the Veteran
By conducting research sessions with Veterans, we will be able to receive real-time feedback about the Toxic Exposure questions, so we can make changes if needed to make them easier to understand and answer with confidence.

## Background
Now that we have completed research planning, which includes a Research Plan, a Conversation Guide, and Perigean recruiting criteria, it is time to conduct the research sessions with volunteer Veterans.

### Resources
- Research planning ticket #76314
- [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-plan.md)
- [Convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/conversation-guide.md)

## Tasks
- [x] Create signup sheet on Slack canvas for teammates to sign up and attend research sessions 
- [x] Attend kickoff call with Perigean (Friday March 22 at 2:30pm ET)
- [x] Forward invites to teammates for those sessions as scheduled
- [x] Conduct sessions
- [x] Organize notes for summarizing later

## Acceptance Criteria
- Research sessions for TERA questions will be completed with Veterans.

**Comment by jessicastump** [comment]
The [Slack sign up sheet can be found here](https://dsva.slack.com/docs/T03FECE8V/F06QX0E07U1) - will add to the DSVA 1010 channel once we have approval and the recruitment starts.

**Comment by jessicastump** [comment]
I think we can just add to the Mural for the session notes and synthesis - getting that all setup in the [Mural board here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709573584989/d47237729c87fee8ec55db12db994920c6f26f24?sender=uadf1ed7fe7c76f0914967329).
