### ISSUE TITLE
[FE] - Returning user with a good session skips loading page

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#78753]
## Summary
discover why the travel app skips users with a read.full session to the intro page and errors out. It should go to the loading page to call the patient_check_ins endpoint to fetch appointment data.

## Tasks
- [ ] add fix for returning users on travel
- [ ] Add e2e test for returning user
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
