### ISSUE TITLE
[Discovery] Logged-in homepage: Project Kickoff

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7875]
## Steps to complete Project Kickoff

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Overview

The authenticated experience team will be pursuing a redesign of the logged-in homepage with the full support and enthusiasm of the DEPO team behind us (note: the homepage will **not** be changing in its logged-out state). As part of this, we will also be retiring the existing My VA dashboard.

This redesign will allow us to provide a better personalized experience to logged in veterans on VA.gov by more effectively elevating status updates/alerts and tasks that are relevant to them right on their homepages. This redesign will also allow us to better support teams that build on VA.gov by giving us a place to feature tools, both new and existing, that are otherwise are currently buried in content hubs.

## Artifacts
- [Logged-in homepage product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/README.md)
- [Logged-in homepage epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6326)

## Meeting attendees from **requesting team**
- **Product Manager**: Matt Shea 
- **DEPO Product Lead**: Samara Strauss
- **Entire VFS team**: Liz Lantz, Tressa Furner, Erik Hansen, Lihan Li. Please also include Shawna Hein, as she's supporting Liz in this effort. 

## Scheduling
- **Preferred dates or times**: If possible, either the week of April 12 or April 19. Our team holds our stand-ups at 3:00 ET on Mondays, Thursdays, and Fridays. We could use that time slot for the kickoff since we already know people should be able to be there.

**Comment by jenstrickland** [comment]
@Samara-Strauss — Purely **consider** items, and no response is necessary. 😄 

- Technical: is a Progressive Web App (PWA) being explored?
- (if PWA) KPIs: how many users allow browser notifications? This may be something for user research.
- Foresee: fwiw, the recent implementations have accessibility issues (ticketed [#6980](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6980), [#5628](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5628), [#6340](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6340), [#6401](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6401], [#6377](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6377)); will update to Medallia “soon?” — so it may be a different satisfaction measuring tool by then, hopefully without accessibility issues.

**Comment by Samara-Strauss** [comment]
> Technical: is a Progressive Web App (PWA) being explored?

We hadn't talked about it, but this is definitely something to keep in mind. I'll add this to the product outline so we don't lose track. My guess is that that would not be our V1 approach but maybe something we could consider long term.

> Foresee: fwiw, the recent implementations have accessibility issues (ticketed #6980, #5628, #6340, [#6401](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6401], #6377); will update to Medallia “soon?” — so it may be a different satisfaction measuring tool by then, hopefully without accessibility issues.

Noted! Idk what the timeline is for Medallia, but if it's in the next 2 - 3 months, it'll definitely be in use well before homepage updates.
