### ISSUE TITLE
Copy of Onboarding Ticket: Phase One

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78756]
## Description 
This is the first phase of onboarding for a new Tier 1 support person. The source of the tasks is here: Anthony Flowers: [Onboarding Checklist](https://docs.google.com/spreadsheets/d/1PLrbnNH9vBSltgCqbrpQJT5W-6jfOAceJ5CbADREGhc/edit#gid=0).

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [x] 2-step verification for Gmail setup
- [x] OneLogin SSO
- [x] Login into Unanet and at the end of day make sure to bill your hours to your program
- [x] Add Oddball Holiday Calendar to your work calendar
- [x] Download Slack App (Windows)
- [x] Download Slack App (Apple)
- [x] Integrate Slack with Google Calendar
- [x] Fill out Slack Profile. Please follow the instructions in the notes column. 
- [x] Complete information in Paylocity (direct deposit, emergency contact, & W-4)
- [x] Complete Benefit Enrollment through EASE
- [x] Review Benefit Notices in Ease
- [x] Accountability Chart aka.Org Chart
- [x] Ensure that you are apart of the slack channel #oddball-it-helpdesk_interlaced

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Access to Jenkins
 Access to Prometheus
 Access to Sentry
 Access to Sidekiq
Access to Grafana/Loki

Above items were marked off but Anthony didn't need access. Closing.
