### ISSUE TITLE
Onboarding Ticket: Phase Three

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78759]
## Description 
This is the third phase of Platform Support onboarding. The tasks below are sourced from the Confluence Platform Tech Support Team page here: [Onboarding](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2697691253/Onboarding).

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [x] New hire reads through Platform Site 
- [x] New Hire Reads Through Confluence Documentation
       - [ ] Responsibilities by Specialty
       - [ ] Onboarding Checklist - Platform Support Team
       - [ ] Slack Channels for Platform Support
 - [x] New hire reads through [other Confluence Documentation ](https://vfs.atlassian.net/wiki/spaces/PTST/overview?homepageId=2425029665)
 - [x] New hire watches support channel to understand how tickets are handled

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@AnthonyWFlowers Starting on March 18, 2024.

**Comment by alyssagallion** [comment]
@AnthonyWFlowers Since this is ongoing and you've done it for a few weeks now, I'm going to close this!
