### ISSUE TITLE
Onboarding Ticket: Phase Four

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78766]
## Description 
This is the fourth phase of Platform Support onboarding.

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [x] New hire reads through [Platform Support confluence space](https://vfs.atlassian.net/wiki/spaces/PTST/overview?homepageId=2425029665)
- [x] New hire shadows with each person on the team
      - [ ] Lindsay Insco
      - [ ] Brandon Dech
      - [ ] Brendan Matos
- [x] New hire watches support channel to see how tickets are handled and asks any questions
- [x] Attend all meetings and ask questions as needed

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@AnthonyWFlowers Closing this since the shadowing is ongoing!
