### ISSUE TITLE
Copy of Onboarding Ticket: Phase Three

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78769]
## Description 
This is the third phase of Platform Support onboarding. The tasks below are sourced from the Confluence Platform Tech Support Team page here: [Onboarding](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2697691253/Onboarding).

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [ ] New hire reads through Platform Site 
- [ ] New Hire Reads Through Confluence Documentation
       - [ ] Responsibilities by Specialty
       - [ ] Onboarding Checklist - Platform Support Team
       - [ ] Slack Channels for Platform Support
 - [ ] New hire reads through [other Confluence Documentation ](https://vfs.atlassian.net/wiki/spaces/PTST/overview?homepageId=2425029665)
 - [ ] New hire watches support channel to understand how tickets are handled

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Created in error.
