### ISSUE TITLE
Onboarding Ticket: Phase Six

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78774]
## Description 
This is the sixth phase of Platform Support onboarding.

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [x] New hire works tickets and asks questions as needed 
- [x] New hire works first Incident Commander shift
- [x] Zoom training for IC - reach out to Alyssa to schedule
- [x] Onboarding complete after IC shift completed

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Scheduled for IC June 5th to 11th. Changed sprint time period.
