### ISSUE TITLE
BRD fix Flagging, verify log origin in staging

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#78798]
## Issue Description

Some strangeness has come up with the BRD logging; this ticket is to fix flagging and run a quick sanity check. Current plan state:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/Release%20Plans/DBEX%20Benefits%20Reference%20Data%20Endpoint%20Migration%20Release%20Plan

Regarding the odd provider-level logging behavior, the common thread appears to be @thread:puma srv tp". Puma is just a Heroku web server for rails, but an aggregation of all "puma" logs shows that only a small subset of our logs come from those threads. It's likely inquiring about the usage of a Heroku web server will reveal what side jobs are calling our service.
(This is mostly superficial, especially if we run a sanity check via staging or short prod run at low capacity (0.1% - 0.5%), but would be good to look into for knowledge, regardless)

---
## Tasks
- [x] Resolve BRD Flag no longer appearing in the Flipper dashboard
- [ ] (Optional) inquire/learn about puma logs, what jobs are run through Heroku
- [x] Run sanity check in staging using Flipper, compare against existing provider level logs accordingly
- [ ] (Optional) Run low volume Canary in prod (0.1% - 0.5%), compare against existing provider level logs accordingly

## Acceptance Criteria
- [x] Resolve BRD Flag no longer appearing in the Flipper dashboard
- [ ] DD metrics accuracy sufficiently verified

**Comment by sethdarragile6** [comment]
[Identified](https://agilesix.slack.com/archives/C04MJV66ZPC/p1710953661249569) the issue with the flag not appearing in the dashboard, it was absent from `features.yml`. I put [this fix](https://github.com/department-of-veterans-affairs/vets-api/pull/16029) in, will test when approved and merged.

**Comment by sethdarragile6** [comment]
PR was merged and deployed to Staging. Verified that the flag is now on the Flipper Admin page. Will now test on Staging before proceeding with the Canary+Prod launch. NOTE: made this comment on Thursday, forgot to hit the Comment button

<img width="1130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGY5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a537c41277fc79a36f6fc9c202f346b102120110/image.png" alt="image.png" />

**Comment by sethdarragile6** [comment]
Took a little doing, but I figured out how to test separation locations organically using user 99:

1. Yes to "Are you on active duty", then chose a recent anticipated release date to avoid BDD flow (i.e. April 8 2024)
2. Clicked Continue on Military service history
3. Entered a unit name for reserve and national guard information, clicked Continue
4. On Federal Orders, I chose Yes and entered a range, clicked Continue
5. Now we are on the separation location page!

When I first tried to type something in the location box (the flag was ON), nothing would populate in the dynamic dropdown. and you could not proceed to the next page
<img width="725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8922aa97893f34c4975d1f5a2d052330c2b477a/image.png" alt="image.png" />
When I switched the flag OFF, logged user 99 out, logged in in incognito mode, it worked
<img width="706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzBLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f21b65b84e2dce929ae8930a696a12e18890ecbf/image.png" alt="image.png" />
Thinking that maybe we have broken code on the LH side, I switched the flag back on and repeated the experiment. However, this time it WORKED, and it has ever since. At the time of the error, there was nothing obvious standing out in the browser console, and I couldn't tell from the dashbard if there were any corelated errors. 

The good news is, the LH requests were definitely tracked on the "LH Traffic" graph as expected. But I think perhaps the error reporting on the dash needs more work, it is showing (I think) _every_ error and is not useful.
