### ISSUE TITLE
[FE] Add back to last screen on /contact-information

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#78803]
## Description

It looks like when we released the [Have you arrived page](https://dsva.slack.com/archives/C03KQAUFVT6/p1710938196479859), the back to last screen link at the top of the /contact-information page not longer appears. I believe there's no reason it shouldn't. 

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHYyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de4c9660b518d1e83ed50ee8b8d42e2cfd08e07f/Screenshot%202024-03-20%20at%2010.13.56%E2%80%AFAM.png" alt="Screenshot 2024-03-20 at 10.13.56 AM.png" />

## Tasks
- [ ] [FE] Add back to last screen on /contact-information
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/78803?planning-poker) with Zenhub @lee-delarm6 @wullaski

**Comment by brianseek** [comment]
This has been merged and will be on stage and prod to validate soon. Also see screenshot:
<img width="150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzhLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef2bde6ca66b013c0a817500833a2e71f90137b8/localhost_3001_health-care_appointment-check-in_contact-information.png" alt="localhost_3001_health-care_appointment-check-in_contact-information.png" />

**Comment by brianseek** [comment]
@benbrasso-agile6 ^

**Comment by benbrasso-agile6** [comment]
LGTM
