### ISSUE TITLE
[CDP] Diary code discovery

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#78806]
## Description

We need to better understand the use of diary codes on the debt portal. These messages appear on the cards and on alerts on the debt portal. 

We need to determine whether a diary code should be a "informational" alert or a "warning" alert. [https://design.va.gov/components/alert](https://design.va.gov/components/alert)
**Informational alert (aka default):** Used to provide helpful information or something that warrants a user’s attention. Not used for negative consequences.

**Warning alert:** Used to warn a user, such as when there are negative consequences, or when something has gone wrong.

[Figma: Diary Codes](https://www.figma.com/file/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?type=design&node-id=0%3A10321&mode=design&t=URCEDJ53EN2at0fQ-1)

 Both the spreadsheet of original diary codes and our grouped version can be found in the VSA Team Sharepoint: 
        - [Original diary code spreadsheet](https://salientcrgt.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Debt%20Letters%20Master%20Codes%20and%20Transactions%20Catalog.xlsx?d=w50365d7002b248828873928f7b6a6c7f&csf=1&web=1&e=8xDirj) 
        - [Grouped diary codes spreadsheet](https://salientcrgt.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Debt%20Letters%20MVP/Iteration%203/Debt%20Portal%20Statuses%20V2.0.xlsx?d=web6d9eb5b68e4a89b8efb3b8ecbefc31&csf=1&web=1&e=T6iP8w)
  

Given: Users are given an inconsistent labels for diary codes on the Debt Portal
When: Cards, Alerts
Then: How can we improve the presentation of diary codes on the Debt Portal?

## Tasks
- [x] [Create spreadsheet](https://docs.google.com/spreadsheets/d/1h8CYQH9W7ka2llPsHX50MQ7Qy5uoKFsLmMtNlQ6eLfk/edit?usp=sharing) to analyze existing diary codes

## Acceptance criteria

- [x] [Spreadsheet created and filled out](https://docs.google.com/spreadsheets/d/1h8CYQH9W7ka2llPsHX50MQ7Qy5uoKFsLmMtNlQ6eLfk/edit?usp=sharing)
- [x] Discussion on diary codes started

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@denisecoveyduc , here it is!

**Comment by mgleo** [comment]
After speaking with @denisecoveyduc, I'm moving this ticket to Validate. @Tom-Davis @HeatherRienks 

Additional Diary Code work will continue on [#80146](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/80146)
