### ISSUE TITLE
[Frontend] Update the MDRT Confirmation screen 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7882]
## User Story or Problem Statement
How might we ensure the MDRT's staging UI match the InVision prototype?

## Goal
_Ensure the MDRT confirmation page includes the updated design elements and content_

## Objectives or Key Results this is meant to further
- _MDRT development_
---
## Tasks
- [ ] _Update the content on the confirmation page_
- [ ] _Update and add missing UI elements on the confirmation page_
[InVision prototype of the confirmation screen
](https://vsateams.invisionapp.com/share/MYVTQ79UGNP)
## Acceptance Criteria
- [ ] _Updates are incorporated that match the most recent confirmation page_
