### ISSUE TITLE
Update VFS member numbers in Atlas

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#78838]
## Purpose
It appears that some of the PM info in Atlas isn't accurate.  In order to give a reasonably accurate portrayal of the participation rate in the Satisfaction Survey, we need a headcount.

## Tasks
- [x] Investigate how Atlas compiles info
- [x] Gain necessary access to perform edits

## Acceptance Criteria
- [x] A plan is created to edit Atlas entries
