### ISSUE TITLE
EVSS PCIU Migration: Step 6d: DISCOVERY for vets-website PCIU removal

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#78839]
## User Story
As a developer, I want to remove all references of PCIU to ensure VA.gov no longer uses PCIU, as we transition to VA Profile in preparation for the PCIU deprecation.

## Issue Description
We're currently uncertain about the level of frontend work required to remove PCIU from vets-website and the extent of external assistance needed. This ticket should outline the scope of work and specify any tasks that require Platform's involvement in https://github.com/department-of-veterans-affairs/va.gov-team/issues/99359 and, if deemed necessary, write up any tickets for work needed for other teams.

The necessary work & owning team(s) will be reassessed based on the results of the discovery.

## Tasks
- [x] Evaluate what will need to be done to remove PCIU on the frontend (create discovery doc if necessary).
- [x] Evaluate if the above will cause any breaking changes (Consult with a FE engineer if necessary)
- [x] Write up Platform tasks in https://github.com/department-of-veterans-affairs/va.gov-team/issues/99359
- [x] Create other tickets for additional work, if necessary. A skeleton ticket for the Vets Website removal has [been created here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99359)
- [x] Communicate findings to team (+ FE team if necessary)

## Acceptance Criteria
- [x] Create a discovery doc, clearly outlining the specified findings and tasks
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/99359 is updated with tasks
- [x] Other tickets are created and linked to the epic.

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by RachalCassity** [comment]
Contact Information V2 has to replace PCIU in prod before PCIU references can be removed.

**Comment by AshleyGuerrant** [comment]
**Standup note:** Reassigning to @RachalCassity. 

@rjohnson2011 is working on an EVSS migration discovery in #99294 and the audit which is listing out all of the vets-api directories/components and their associated files is requiring much more effort than initially anticipated. Ryan will continue to focus on that during this sprint because the EVSS migration is also a high-priority initiative.

**Comment by RachalCassity** [comment]
Began discovery work in this confluence doc, [PCIU FE Discovery](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3747905544/PCIU+FE+Discovery)

**Comment by RachalCassity** [comment]
The PCIU variables in Vets-Website are imported from Vets-json-schema. These variables are hard-coded and not sourced from Vets-API or any external services. To avoid confusion in the future, the PCIU variables in both Vets-Website and Vets-json-schema will be renamed. No additional configuration is required.

As backend engineers, it was initially unclear how PCIU variables were imported into Vets-Website. While constants can sometimes be imported from external services outside of Vets-API and Vets-Website, that is not the case here. PCIU variables are hardcoded in the Vets-json-schema repository and then imported into Vets-Website. This discovery was completed within a day, so this ticket should be assigned a point value of 1 or 2.

**Comment by AshleyGuerrant** [comment]
**Sprint reporting note:** updating the estimated story points from a 5 to a 2, for the reasons listed in the comments above.
