### ISSUE TITLE
Update Platform Website documentation with Google Docs Links

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78844]
### Description
As part of the initiative to remove instances of Google Drive links on the Platform Website, we will be needing to update a couple of links on the _**Analytics & Insights**_ section.

Specifically, these two pages:

- [Analytics customer support guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide)
- [Getting started with Platform Analytics & Insights](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights)

Feedback from Platform Content Team:

> In Analytics customer support guide, in section 4, there are 2 problematic links.
> First in Section 4, it says “check Should I request a standardized KPI dashboard.” How do we fix this so that link isn’t there any more?
> Then in Section 4, Step 2, it says “You can use this Google Sheet or the attached Excel file below.” It sounds like we can just delete the link to the google sheet for this instance.
> In Getting started with Platform Analytics & Insights, there are 3 problematic links. These may all link to the same google slide, but I’m not 100% sure. How can we fix this document to get rid of the 3 links?
> In the intro at the top of the page it says “this page is meant to supplement the Platform Analytics & Insights orientation slide deck.”
> Then under the heading “What dashboards are available?” it says “view the Should I request a standardized KPI dashboard? slide in the Platform Analytics & Insights Orientation slide deck for more information.” So I think that’s 1 sentence with 2 links to the same google slide.

---

### Tasks
- [ ] For each suggestion, determine how to replace content with links to Google, or another alternative.
- [ ] Identify decks or resources on these pages that do live in Google, and keep a record of these resources.
- [ ] Links have been removed.
- [ ] Pages have been reviewed, and updated in Confluence.

### Acceptance Criteria

- [ ] **Analytics customer support guide** page has no links to Google resources
- [ ] **Analytics customer support guide** page is live on Platform Website
- [x] **Getting started with Platform Analytics & Insights** page has no links to Google resources
- [x] **Getting started with Platform Analytics & Insights** page is live on Platform Website

**Comment by johnny-jesensky-adhoc** [comment]
Per refinement, connect with Andrea on if we have a Sharepoint space within the Platform.
