### ISSUE TITLE
Replace ClamAV binary with ClamAV docker container

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#78841]
## Summary

The master branch uses clamav binary, but the k8s branch uses clamav docker container. In order to remove the k8s branch, the master branch needs to replace the binary for the docker image. 

## Tasks

- [x] replace binary and use docker container
- [x] update Dockerfile & related compose files to match k8s
- [x] update Makefile to work with new compose files

## Acceptance Criteria 

- [x] API works on Review instances
- [x] Testing works locally & on CI
- [x] Engineers can use Docker & Hybrid setups
