### ISSUE TITLE
Security & Privacy Review After-Actions

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7885]
Thanks for meeting today! We had a great long conversation, couple AIs that we'd like the team to make sure happen _eventually_ (not launch-blocking) and a couple we';d like to see happen _before launch_.

Eventually (not launch blocking):
- [x] Fetch SSOe SAML metadata (public key, etc.) from public endpoint rather than checked into devops repo
- [x] Find way to allow login during local development (localhost) without needing secret client key + cert configuration

Launch blocking:
- [x] Look into what kind of traffic SSOe is prepared to handle for launch (noting we have both logins + KeepAlive endpoint sessions) so we can have more confidence that the rollout of SSOe won't break the experience for Veterans
- [x] Look into ways we can measure how much add'l latency SSOe is adding to the login flow (coordinate with @annaswims on this)
- [x] Look into ways to distinguish (in reporting from vets-api) which identity broker (SSOe vs. ID.me) is at fault when there's a failure _(ask IAM to create a public status page?)_
- [x] Make sure rollout plan is starting small (recommended 1% since this is hitting all users) with metrics to compare before rolling out further
- [x] Version tags/labels on statsd metrics for SAML error responses
- [x] IAM contacts/escalation process is documented and checked in

Some of these are "look into" items, which means they don't necessarily have a pre-determined solution. If there's something achievable that makes sense / isn't too difficult, let's try to get it in for launch. If not, we can decide case-by-case whether they should be punted for launch.
