### ISSUE TITLE
Update Appoint MVP designs based on stakeholder feedback

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#78869]
## Background
After presenting our Appoint MVP designs to stakeholders in Compensation Services, we learned that we don't have the medical authorization quite right.  When a claimant is seeking benefits for themselves, then the medical authorizations pertain to them ...UNLESS the Veteran is deceased in which case the medical authorizations apply to the Veteran.

We discussed adjusting the radio options at the start of this flow to account for this logic, and also updating the medical authorizations screen to reflect the situation described above.

## Tasks
- [ ] Update Appoint MVP designs based on stakeholder feedback
- [ ] Review updates with the ARM team
- [ ] Schedule a meeting for review with stakeholders (CS, OGC, OPO)

## Acceptance Criteria
- [ ] Appoint MVP designs have been updated for accuracy and ready for a second round of stakeholder review

**Comment by mtri** [comment]
[Figma canvas view of content adjustments](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=3476-60782&mode=design&t=F1WFY92dDo5nf1bF-11)
[New question added after selecting I Am Not The Veteran](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=3459%3A164354&type=design&node-id=3488-181900&viewport=2411%2C771%2C0.5&t=lsL2FygQcofW44SD-1&scaling=min-zoom&starting-point-node-id=3476%3A60782&mode=design)

**Comment by mtri** [comment]
Discussing changes with A tomorrow

**Comment by oddball-lindsay** [comment]
We met with stakeholders today and received additional feedback.  That feedback is logged in https://github.com/department-of-veterans-affairs/va.gov-team/issues/80050.  

I think our next round of stakeholder review we can focus on the updates made in this ticket as well as the updates made from round 2 of review (https://github.com/department-of-veterans-affairs/va.gov-team/issues/80050).

@mtri ok to close this ticket?

**Comment by mtri** [comment]
Yep sounds good thanks!
