### ISSUE TITLE
Onboarding Ticket: Phase Two (David)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78873]
## Description 
This is the second phase of Platform Support onboarding. The source for this process is here: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1694796460913/9c127c1a097016b0cfbf26b609f5a0a6b623de61?sender=udc895e519e95151fc0244426

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [x] New hire fills out paperwork with their contractor POC
- [x] POC Requests That New Hire be Registered in USAccess/ &nbsp;Amber gets confirmation &nbsp;the new hire has been added
- [x] New hire goes for fingerprints / POC submit forms and add them tool
- [x] SAC Adjudication Favorable Decision is shared
     - [x] Access to GitHub
     - [x] Access to Zenhub
     - [x] Access to Confluence
     - [x] Access to DSVA Slack
     - [x] Access to Mural
     - [x] Access to DOMO
- [x] Equip Transmittal
     - [x] Access to PagerDuty
     - [x] Access to DataDog
     - [x] Access to Sentry
     - [x] Access to Sidekiq
- [x] Request PIV sponsorship
- [x] Get physical PIV card
- [x] Get added to all calendar invites

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by davidpetras** [comment]
Found [this](https://vfs.atlassian.net/wiki/spaces/PRT/pages/2920448109/Sunsetting+Prometheus+and+Grafana) while searching where/how to request access to certain applications. Checking off grafana/loki and prometheus as they appear to be sunset as of Jan 30th.

**Comment by davidpetras** [comment]
All tasks complete. Closing
