### ISSUE TITLE
Onboarding Ticket: Phase One (David)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#78872]
## Description 
This is the first phase of onboarding for a new Tier 1 support person. The source of the tasks is here: Anthony Flowers: [Onboarding Checklist](https://docs.google.com/spreadsheets/d/1PLrbnNH9vBSltgCqbrpQJT5W-6jfOAceJ5CbADREGhc/edit#gid=0).

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 

- [x] 2-step verification for Gmail setup
- [x] OneLogin SSO
- [x] Login into Unanet and at the end of day make sure to bill your hours to your program
- [x] Download Slack App (Apple)
- [x] Integrate Slack with Google Calendar
- [x] Fill out Slack Profile. Please follow the instructions in the notes column. 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@davidpetras I removed the Oddball related items since they don't apply to you and I'm closing this ticket. Thanks!
