### ISSUE TITLE
Add confirmation screen message about what will happen with bank accounts as we consolidate to a single bank account for education, disability, and pension benefits

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#78885]
## Issue Description
We are handling most of the policy change around consolidating to a single bank account for education, disability, and pension benefits in [Update content about single direct deposit account requirement#77921](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/77921). 

For this ticket, we should also add messaging to our post-submit confirmation screen about what will happen with the bank accounts. We can leverage [what the Pension team designed for this](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2355-8265&mode=design&t=oNavuNODlgKGpcxh-11).

Related to [Payment information screen: ability to submit a claim without a bank account and "required" text on payment information field labels #78592](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78592)
---
## Tasks
- [ ] Design confirmation screen update - consider all scenarios included in [Update content about single direct deposit account requirement#77921](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/77921)
- [ ] Bring FE Engineering into design discussions
- [ ] Review design with Shannon and get approval
- [ ] Create ticket for implementation

## Acceptance Criteria
- [ ] Above tasks completed

**Comment by mengA6** [comment]
Closing as duplicate of [Update content about single direct deposit account requirement#77921](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/77921)
