### ISSUE TITLE
Implementation - COVID FAQ Page - Datalayer + Tracking

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#7890]
# Analytics Implementation or QA Request

## Description
- Establish a dataLayer for the COVID FAQ Page at: va.gov/coronavirus-veteran-frequently-asked-questions

- Who is this request for?

    - Nick Sullivan, 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._

## Acceptance Criteria
- [ ] Verify dataLayer is in place for relevant events
- [ ] Verify tags have been converted to leverage the new DL structure
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@jonwehausen -

I was thinking either one event for both buttons and links (```...child-click```)

```
dataLayer.push({
'event': 'nav-frequently-asked-question-child-click',
'frequently-asked-question': 'What's going on with this?',
});
```

...or we we split it into two events:

1. ```nav-frequently-asked-question-link-click```
2. ```nav-frequently-asked-question-button-click```

**Comment by jonwehausen** [comment]
### DataLayer Requirements

Description of interaction | Screenshot |  DataLayer | 
------------ | ------------- | -------------
Click on **ANY** link within the content section (links within each FAQ) | ![image](https://user-images.githubusercontent.com/48527022/79122636-335b9e80-7d66-11ea-9f36-ba056a34828b.png) | ```dataLayer.push({```<br>```'event':'nav-covid-link-click',``` <br>```'faqText': 'What if I've been diagnosed with COVID-19 and need immediate aciton on my VA appeal?'```<br>```});``` <br> **Dynamically populate with the FAQ question each time**
Clicks on the jumplinks at the top of the page in the "On this page" section | ![image](https://user-images.githubusercontent.com/48527022/79122844-c694d400-7d66-11ea-9748-e673179c2ecd.png) | ```dataLayer.push({```<br>```'event':'nav-jumplink-click',```
Click on links in more information + helpful tools sections | ![image](https://user-images.githubusercontent.com/48527022/79123038-35722d00-7d67-11ea-9a8a-852aa2be3878.png) | ```dataLayer.push({```<br>```'event':'nav-linkslist',``` <br>```'links-list-header': 'Send a secure message'```<br>```'links-list-section-header': 'Helpful online tools'```<br>```});``` <br><br> - **Dynamically populate with the heading of each click** <br><br> - **Dynamically populate with the header of the links list section**

**Comment by jonwehausen** [comment]
### Other Tracking Changes Needed
- Remove UTM link on href on homepage banner 
![image](https://user-images.githubusercontent.com/48527022/79128513-a3bbed00-7d71-11ea-90ad-ec0ba1b9133d.png)
- Question element visibility?

**Comment by ncksllvn** [comment]
PR to remove UTM parameters from homepage banner, https://github.com/department-of-veterans-affairs/vagov-content/pull/650

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Questions? Comments?  Insults?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000262

**Comment by jonwehausen** [comment]
@bsmartin-ep Thanks for staging! Looks good! 

### Few things to update: 
> Let's change the taxonomy within `Navigation Action Lookup` to mirror what our existing one is: "Navigation - COVID - {{Click Text}} - {{Click URL}}" -- see tag "EV - COVID FAQ"
> Inserting the DL variable `DL - faqText` into the CD slot, replacing previous custom JS
> We also will want to PAUSE our existing click tag currently on the site at the time we publish this container

**Comment by bsmartin-ep** [comment]
@jonwehausen -

1. Updated in the container.
2. 77 via DL added to _Navigation Click_ tag
3. COVID FAQ tag paused.

Pause now, then delete the COVID FAQ tag (and it's unique triggers / CJ) later?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000262

**Comment by ncksllvn** [comment]
I think this will go today at least to Staging. Update -

> Click on ANY link within the content section (links within each FAQ)

I've limited this to just the Coronavirus FAQ page for now since the event name seems specific.

> Clicks on the jumplinks at the top of the page in the "On this page" section	

Also limited to just the Coronavirus page, because that content is typed in a WYSIWYG, so I couldn't get a good element selector for adding analytics.

> Click on links in more information + helpful tools sections	

This will be __global__ so please QA carefully. It will affect eh `Helpful online tools` and the `More information` sections because they use the same content model. They're both considered a list of teaser links.

> Click on homepage banner clicks	

This is limited to just the homepage for now, but the event seems generic enough, so we might want to apply it globally at some point.

**Comment by jonwehausen** [comment]
Thanks for the notice @ncksllvn -- those are great and what we were thinking as well (to just limit these items to the relevant pages called out initially) 

Haven't yet seen the DL within staging -- we will be sure to test thoroughly when available.

**Comment by jonwehausen** [comment]
### DL QA
cc: @ncksllvn @bsmartin-ep 

All DL test scenarios passed, thank you @ncksllvn!

Description | Screenshot | Status | Notes
------------ | ------------- | ------------- | -------------
Click on any link within a FAQ | ![image](https://user-images.githubusercontent.com/48527022/79866251-78a54f00-83aa-11ea-995e-50eb63958126.png) | ✔️ **PASSED** | This test scenario was performed on all links contained within FAQ content
Click on links within Helpful Online Tools section | ![image](https://user-images.githubusercontent.com/48527022/79866645-1862dd00-83ab-11ea-9207-050638e5398a.png) | ✔️ **PASSED** | This test scenario was performed on all links contained within the Helpful Online Tools sesction
Click on links within "More Information" section |![image](https://user-images.githubusercontent.com/48527022/79866860-6aa3fe00-83ab-11ea-8b3b-a5b2a0d4cd7d.png) | ✔️ **PASSED** | This test scenario was performed on all links contained within the"More Information" sesction
Clicks on jumplinks at top of page | ![image](https://user-images.githubusercontent.com/48527022/79867151-e00fce80-83ab-11ea-8772-d15007b3970f.png)| ✔️ **PASSED** | This test scenario was performed on all jumplinks at the top
Clicks on homepage banner links | ![image](https://user-images.githubusercontent.com/48527022/79867483-688e6f00-83ac-11ea-87a1-a22fe8ea85d8.png) | ✔️  **PASSED** | This test scenario was performed on all links on the COVID banner

**Comment by bsmartin-ep** [comment]
### Links List Event Action JS - 8080

Description | Screenshots |  Result
--- | --- | --- 
[COVID FAQ _More Information_](https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/) | ![image](https://user-images.githubusercontent.com/62304138/79871841-fa997600-83b2-11ea-9bc1-8c603971476a.png) ![image](https://user-images.githubusercontent.com/62304138/79872217-83181680-83b3-11ea-89c5-090b8e310a88.png) |  ✔️ **PASSED**
[Home Page _Links List_](https://staging.va.gov/])  | ![image](https://user-images.githubusercontent.com/62304138/79872769-33861a80-83b4-11ea-99b6-108420bf3481.png) ![image](https://user-images.githubusercontent.com/62304138/79872820-439dfa00-83b4-11ea-9913-52806b024777.png) |  ✔️ **PASSED**
[Benefits _Links List_](https://staging.va.gov/service-member-benefits/) | ![image](https://user-images.githubusercontent.com/62304138/79872965-7516c580-83b4-11ea-961a-6a985921bb8a.png) ![image](https://user-images.githubusercontent.com/62304138/79873021-895ac280-83b4-11ea-8072-3f705be135d6.png) | ✔️ **PASSED**

cc @jonwehausen

**Comment by ncksllvn** [comment]
One thing I found is that not all links-lists have headings, and in that case `link-list-header` will be empty. Is that okay? I don't have an example offhand.

**Comment by bsmartin-ep** [comment]
@ncksllvn -

We modified our links list JS to look for...

1. links-list-header (and links-list-section-header) if present
2.  Specific class names (.va-nav-linkslist-title, .hub-page-link-list__header) if present
3. Defer to the classic Click Text as a backup

**Comment by jonwehausen** [comment]
Published & Deployed 

Thank you @ncksllvn for your efforts here.
