### ISSUE TITLE
Create V1 of GA4 Reporting & Training Plan

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78918]
### Description
We will need to have a training strategy for VFS Teams to get familiar with GA4, know what to expect. Teams have been growing eager about the transition, so want to provide some more detailed guidance. This may include something along the lines of the following:

_Note - continue to make it clear we are working towards version 1s or drafts_

- GA4 Specific Office Hours for Questions
- What's New Decks/or Videos
- 101 Training Sessions

Right now, these are all just ideas, or in the form of backlog tickets, but this plan will be to codify a more detailed strategy for the next few months. 

---

**Tentative Timeline & Plan:**

**May 1st:** 
- GA4 Properties Available for VFS Teams
- Training Decks Updated with What's New?

**May 15th:** 
- GA4 Custom Reports Available
- Weekly GA4 Specific _**Office Hours**_ Begins

**June 1st:**
- KPI Reports in Domo Available

---

### Tasks
- [x] Consolidate list of potential GA4 training resources, decks, Platform Website docs, sessions.
- [x] Create more definitive timeline of what and when to roll out certain things.
- [ ] ~Talk with VFS Team members on what they might need.~ _User feedback will likely be gathered from a couple of pilot teams -- likely one from each crew, (Benefits, Health Tools, etc.)_
- [x] Communicate training strategy to VFS Teams

### Related Artifacts:
- [Issue: Analytics - VFS Report Inventory
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-UA-Reports.md&title=Reports+Using+GA+UA+Data%3A+%5BTeam+Name%5D)
- [WIP GA4 Migration: Training Plan & Timeline](https://vfs.atlassian.net/wiki/spaces/AT/pages/3027894309/WIP+GA4+Migration+Training+Plan+Timeline)

### Acceptance Criteria

- [x] Version 1 of a training plan has been drafted.
- [ ] ~Training curriculum has been shared to VFS Teams, or made available through some channel (Platform Website, Slack, etc.)~ _Training plan will be communicated at a later date, hope to gather feedback from a few pilot teams -- likely one from each crew, (Benefits, Health Tools, etc.)_

**Comment by johnny-jesensky-adhoc** [comment]
Baseline (i.e. V1 of training plan has been established and documented within Confluence [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3027894309/WIP+GA4+Migration+Training+Plan+Timeline). 

Additionally -- first reminder for VFS Audit of Reports that use GA UA data has been shared on the _vfs-analytics_ channel here. 

- https://dsva.slack.com/archives/C1Q4294JJ/p1712688413304769
- Resulted artifact in the form of a Github form is found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-UA-Reports.md&title=Reports+Using+GA+UA+Data%3A+%5BTeam+Name%5D).

Separate ticket identified through some of this work has been created [here](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/79980).

Next steps coming from this will likely involve putting together a visual to showcase the plan, establishing the topics and order of video trainings, and scheduling our GA4 Migration Office Hours. Moving this to **_Done._**
