### ISSUE TITLE
Post Atlas MVP/V1: Cleaning up Atlas Team Member Data

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#78915]
## Issue Description
While doing cleanup work, Rebecca pulled a list of users with duplicate usernames (which includes those without a username) and began cleaning up the data by grabbing their username from their Slack profile and add it to their Atlas profile. However, many of those resources don’t work here anymore but weren’t offboarded properly so an offboarding ticket has to be opened for them. This is blocking other Atlas work. 

---
## Tasks
- [x] List team members with duplicate github usernames 
- [x] Deduplicate users with matching usernames to someone else
- [x] For `nil` usernames, research each individual to find their GH username
- [x] Open offboarding ticket if they have clearly left the org

## Acceptance Criteria
- [x] No duplicate users in prod database
- [ ] dev database matches prod

**Comment by rmtolmach** [comment]
Generated list using the following commands in Argo terminal:
```
duplicated_usernames = ProductDirectory::TeamMember.unscoped.group(:github_username).having("count(*) > 1").pluck(:github_username)

duplicated_team_members = ProductDirectory::TeamMember.where(github_username: duplicated_usernames)

duplicated_team_members.each do |team_member|
  puts "First Name: #{team_member.first_name}, Last Name: #{team_member.last_name}, GitHub Username: #{team_member.github_username}"
end
```

**Comment by rmtolmach** [comment]
I went through the list of 58 users in Prod. I opened 15 offboarding ticket for users who'd permanently left the org. I updated about 18 users in the UI with their GH handle and then deleted the people who had already been offboarded or were being offboarded (using the commands below).

```
ProductDirectory::TeamMember.where(github_username: nil).count
=> 14
ProductDirectory::TeamMember.where(github_username: nil).destroy_all
ProductDirectory::TeamMember.where(github_username: nil).count
=> 0
```

I ran the command to get duplicated github usernames and it's returning this smaller list:
```
First Name: Anneliese, Last Name: LaTempa, GitHub Username: alatempa24
First Name: Antwuan, Last Name: Jones, GitHub Username: helpdeskanalyst79
First Name: Bo, Last Name: Altes, GitHub Username: baltes
First Name: Jacob, Last Name: Penner, GitHub Username: pennja
First Name: Jenna , Last Name: Gaze, GitHub Username:  jennagaze
First Name: John, Last Name: Luo, GitHub Username: JunTaoLuo
First Name: Jonathan, Last Name: VanCourt, GitHub Username: jvcAdHoc
First Name: Matthew, Last Name: Kelly, GitHub Username: mathisto
First Name: Nathan, Last Name: Wright, GitHub Username: nathanbwright
First Name: Porta, Last Name: Antiporta, GitHub Username: porta-antiporta
First Name: Rachal, Last Name: Cassity, GitHub Username: RachalCassity
First Name: Robert, Last Name: Brown, GitHub Username: rbrown-va
First Name: Shams, Last Name: Abbasi, GitHub Username: shams-abbasi
First Name: Test 1, Last Name: Member, GitHub Username: test
```
At first glance they don't appear duplicated, but all these individuals have one thing in common: there is a _deactivated_ user with the same github username. I think I will permanently delete these duped deactivated users listed above so we start with a clean database of no duped gh usernames.

**Comment by jennb33** [comment]
Next steps: copy prod into Dev.

**Comment by rmtolmach** [comment]
> Next steps: copy prod into Dev.

I will do this tomorrow

**Comment by rmtolmach** [comment]
The dev database has been cleaned up in regards to duplicate team members/individuals.
✅ I deleted 30 users in DEV that didn't have usernames. 
✅ I deleted the remaining 3 active users in dev that had duplicate usernames. 

❓ If we want parody between the dev and prod databases, we can create a new ticket for an upcoming sprint and assign it to Chris. If parody doesn't matter (it will become out of date as soon as users are added to prod anyway), we can close this ticket.
