### ISSUE TITLE
Clean Up Un-Applied BE CoP/Product Team Terraforms

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#78919]
## Problem

Updated 4/4: there are 400+ changes that need to be made. 

We have several un-applied changes changes in our terraforms similar to the following:
```
$ tf plan
...
# module.datadog_monitors.datadog_synthetics_test.default["vfs-staging-vba_documents-v1-upstream_healthcheck"] will be updated in-place
  ~ resource "datadog_synthetics_test" "default" {
        id              = "t6c-8mw-acc"
        name            = "vfs-staging:/services/vba_documents/v1/upstream_healthcheck"
      ~ tags            = [
            # (1 unchanged element hidden)
            "env:staging",
          - "team:platform",
          + "team:TT1",
        ]
        # (9 unchanged attributes hidden)

      ~ request_definition {
          ~ timeout                 = 0 -> 60
            # (8 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }
```

As discussed in [Slack](https://adhoc.slack.com/archives/C045LCF8WU8/p1710263030141579?thread_ts=1710262575.244389&cid=C045LCF8WU8), the `TT1` is no longer relevant. Instead, we want to replace this with `backend-cop` (or similar. Discuss with Lindsey Hattamer). The `timeout` change looks to be a new default from the [terraform module](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test). 

This was also discussed in the Slack thread above and the change to `60` is acceptable for us.

## Tasks

- [ ] Replace tags
- [ ] Apply terraforms
- [ ] Address other un-applied changes by either creating a story for them, fixing them in the context of this story, or addressing the appropriate owner of the monitor

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria

- [ ] The affected terraforms are clean in the terraform state
- [ ] Additional stories have been created, as needed.
