### ISSUE TITLE
Monitor PACT Act Spring 2024 Submissions

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#78917]
## Issue Description
This ticket is to monitor the DataDog dashboard created by the Platform Product team [here](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms?fromUser=false&index=%2A&refresh_mode=sliding&view=spans&from_ts=1710421711677&to_ts=1711026511677&live=true) for T1 and T2 folk to check daily, beginning on 3/21, and ensure that there is no unusual activity or issues. 

---
## Tasks
- [ ] Daily monitoring by Platform Product or T1/T2 Support teams for unusual activity
- [ ] Action by the appropriate team in the event of unusual or blocked activity 
- [ ] Reroute issues to appropriate team when they are found, if they can not be mitigated by Platform Product team
- [ ] Follow up with assigned team to ensure that the fix has been implemented 
- [ ] PLATFORM PRODUCT TEAM MAJOR RESPONSIBILITY IS TO MONITOR AND MAKE OTHER TEAMS AWARE

## Acceptance Criteria
- [ ] Any unusual activity will be flagged by Platform Product or T1/T2 Support teams and rerouted to the appropriate team for their immediate attention as soon as PACT Act submissions begin to roll in.

**Comment by jennb33** [comment]
@rmtolmach looked at the dashboard this morning and saw some more "Intent to file" errors (sometimes there are 12-30, the errors are in the hundreds in the last 2 days)

**Comment by jennb33** [comment]
Follow-up on the errors from 3/25: The lighthouse API was down, and that's what caused the errors. Otherwise we will continue to monitor this ticket, and it will roll into Sprint 50 (this was pre-determined)
