### ISSUE TITLE
Audit and Rename GA4 Properties

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#78912]
### Description
We have been hearing some questions, and hearing confusion on which GA properties are the most accurate to use now, versus which ones we'll be using in GA4. The current landscape of GA prosperities in its current state is confusing, for instance, we have multiple properties that mention production.

**Full List of GA Properties:** https://vfs.atlassian.net/wiki/spaces/AT/pages/3006136400/Google+Analytics+Properties

---

### Tasks

- [x] Audit list of GA properties...
- [x] Determine which GA4 properties we want to make clear users should NOT USE
- [x] If possible, rename GA4 properties for clarity
- [x] Determine which properties users should use NOW, and LATER (i.e. GA4 Properties)
- [ ] Send out communications to VFS Teams on updates, and which properties to focus on...

> Hi Teams, we have been hearing some confusion to on which properties to use. As of now, the most - Google is deprecated some features, going forward, we will be using the following GA4 properties..."

### Acceptance Criteria

- [x] GA properties have been updated, (with new names, or through some other means)
- [ ] Communications sent to VFS Teams alerting them of properties to use, or avoid

**Comment by jestutt** [comment]
@Blivaditis @ChristineYoungZA  Here's the [audit list](https://docs.google.com/spreadsheets/d/1xGnqazlrD6um625mqY5QkPQWYitihXgOcx2o9YXonbA/edit?usp=sharing). 

A few things: 
- I only added the Views for the VA.gov - Production Property so you'll need to add those for all the other UA Properties as you're checking for data collection
- For the items to be relabeled, I'll update the comments column when that's complete 
- All UA is marked as depreciating. I'm not sure yet if they will be auto-deleted or if the data will disappear one day but leave the Properties and Views

Let me know if there are any questions.

**Comment by jestutt** [comment]
<img width="808" alt="Screenshot 2024-04-05 at 12 34 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/9ecb07d1-f461-43a4-a276-6b845b21053f">

I added 'DEPRECIATED' to the old GA4 Properties that we'll be deleting by the end of April and 'COMING SOON' to what was previously the 'REST' Properties.  

@johnny-jesensky-adhoc I don't know that we need any communication about the Properties yet. We haven't had any questions about them in the last few weeks -- not since the convo that created this ticket -- and nothing has changed for the UA Properties -- of which we can't really be sure of which they are supposed to be using. The only thing we can really communicate is that we changed the GA4 properties and pointing out that no one should be using any of the VA.gov labeled GA4 Properties is likely to cause a Streisand effect.
