### ISSUE TITLE
[CAIA intake] 527EZ ITF copy

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#78928]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to start collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

**Note:** If you’re already partnering with us on an initiative, you don't need to fill out this request form. If you don’t have access to your initiative’s CAIA epic, post a message in the [#sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-acessibility-ia) slack channel and tag `@Terry Nichols` and `@Lily Strelich`.

## About your team

- **Team name**: `Pension benefits`
- **OCTO product owner:** `Sanja Bajovic`
- **Product name:** `Veterans Pension Benefits application`
- **Product manager:**  `Matt Reilly`
- **Slack channel:** [benefits-pension](https://dsva.slack.com/archives/C05MS96P6P2)
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

We've incorporated automatic submission of intent to file into the Pension form, when an applicant starts an application. 

* December 2023: The 526 disability team conducted research on intent to file to identify initial Veteran pain points and technical blockers. [[Findings]](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/Intent%20to%20file%20Research/ITF%20Research%20Summary.md)
* May 2024: We (on the 527 pension team) conducted a [VA.gov](http://va.gov/) audit to validate the current state – how intent to file was represented in the context of a Veteran’s claims journey. [[Findings]](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/research/2024-05%20Intent%20to%20File%20Audit.md)
* July 2024: Katherine helped us design the content for a prototype we’d test with Veterans. At the time, this was our best guess at what the ideal experience could be. [[Mural working board]](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713384778236/cb7811f7fc7d62be8ebfcf962519f055c9df98e6?wid=0-1724791584280) [[Prototypes in Figma]](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=2181-5007)
* October 2024: We tested the prototype with Veterans and documented our learnings. [[Findings]](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/research/2024-10%20Intent%20to%20File%20Comprehension/research-findings.md)
* **January 2025 to today:** We're proposing our latest drafts of content, informed by our research, as our front-end experience for automatic intent to file submission.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We've explored and drafted options for various intent to file scenarios. We don't have any hard deadlines, but our progress on this is blocked until we have finalized, approved copy.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] PO sync
- [ ] Midpoint review – TO BE SCHEDULED
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `[#106512](https://github.com/department-of-veterans-affairs/va.gov-team/issues/106512)`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Proposed experience on 527 Pension form](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=10163-241996&t=QiGjvk867ffPvGA3-4) 
- [Current experience on 526 Disability form](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=2181-5007)
- [Tested prototype for comprehension research](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/WIP---21P-527EZ---Pension-Benefits?node-id=2181-5007)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA a11y tasks
```

```[tasklist]
### CAIA content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79641
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88268
```

**Comment by katherine-fung** [comment]
Hi @gmaciolek, 

Thanks for your patience with this request! Our content recommendation is: 


> [Header] We've recorded a potential start date for your benefits
> 
> When you apply for pension benefits online, we automatically record your intent to file. This means we record the date you start your application as the potential start date for your benefits.
> 
> You may be able to get payments for the time between your potential start date and the date we approve your application.
> 
> You must submit your application by Thursday, March 6th, 2025 at 12:07 p.m. ET to keep your potential start date. Your potential start date resets one year after you start your application.
> 
> You don't need to do anything else right now. You can continue to fill out your application. 

Let us know if you have any questions. Thanks!

**Comment by katherine-fung** [comment]
@juliepedtke @jstrothman @l-sinreich,

I'm noting here that [per Slack](https://dsva.slack.com/archives/C06E83RNLQM/p1713896788375049?thread_ts=1713214661.040629&cid=C06E83RNLQM), I'm holding on this work until the product team circles back and confirms with CAIA the business requirements for the alert (including 1. what states of the alert you require, and 2. what information you need these alerts to provide to the user).

When you get back to us, Lily and A will slot the work in with our other priorities accordingly. Thanks. 

cc @aprocik1 @strelichl

**Comment by katherine-fung** [comment]
Noting that designer @echin393  and I spoke about the possible states of the ITF alert and what may happen in the backend for these states. She says that the team is still discussing what happens when a user returns to the form and their ITF has expired. She'll keep me posted about what they decide. When this is confirmed, she'll let me know and I'll return to this copy to refine it. I also let her know that I've drafted copy for some of the ITF alert states in [ticket 79641](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79641#issuecomment-2063705850). 

cc @aprocik1 @strelichl @juliepedtke

**Comment by echin393** [comment]
Thanks @katherine-fung! While the team is finalizing a couple policy questions, I gathered some initial considerations on these drafts:

**1. ITF start date not always the same as application start date**
>  This means we record the date you start your application as the potential start date for your benefits.

This statement is accurate for the first state (if the user has no previous ITF) but not the second state. 
If they have a previous ITF, or if we're unsure whether a previous ITF exists, we'll continue to hold any existing ITF start date, which may not be the application start date.

The language that 526 drafted is more accurate, but I also know we want to steer away from mentioning ITF because it creates confusion for veterans.
> **If you’ve already notified VA of your intent to file,** we’ll continue to hold that date as the potential start date for your benefits. 

**2. Potential payments with potential benefits**
> You may be able to get payments for the time between this date and the date we approve your application.

There is a possibility that VA rejects the veteran's application. I can see a challenge here where we want to motivate users to start the app, while also being transparent that **if** VA approves it, you **could** get retroactive payments, although that may not instill much confidence.  

**And a couple questions for my context on content standards:**
* Is it worth specifying pension benefits in the alert title? Or does it make for an excessively long title? 
* What is the rationale for bolding the potential benefits start date vs. the ITF expiry date, vs. bolding both?

**Comment by katherine-fung** [comment]
Hi @echin393, 

For #1, I can continue to refine this copy once we pick up this work again. 

For #2, we lead into this sentence by saying, "_If we approve your application_, the potential start date for your benefits is Wednesday, March 6, 2024.

You may be able to get payments for the time between this date and the date we approve your application."

I think the italicized phrase is sufficient to let the user know this only applies if VA approves your application. Let me know if you have other thoughts. 

And on the other questions: 

- I think we can specify "pension" in the header, and
- We should bold both of those dates, thanks for catching that. In this context, I think our standard practice is to bold generated content.

**Comment by echin393** [comment]
This is great! Thanks for the quick feedback.

**Comment by echin393** [comment]
Hi @katherine-fung , we’d like to get your feedback on the content for our upcoming research study: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713384778236/cb7811f7fc7d62be8ebfcf962519f055c9df98e6?wid=0-1724791584280

Directions are in the Mural board, but just to reiterate – the screenshots are from production (a mix of our current experience on Pension and the current ITF experience on 526), and we’d like to get your guidance on the proposed content and questions.
Feel free to provide the feedback either in this ticket or in the board directly. And if you have any questions or would like to discuss this over a call, let me know.

**Comment by katherine-fung** [comment]
Thanks @echin393 - I'll review the board the content this week. When do you need this feedback by? I think we should have a call to discuss these issues/questions, and others that might come up in my review. Or let me know if the below makes sense and we can discuss async here: 

- Is the 1.1 Introduction page showing what an authenticated user with a verified account sees? The menu at the top of the page suggests the user is signed in already. But the last 2 variants on the Mural board direct users to "use a verified account" or "sign in with an identity-verified account," which I would think they shouldn't see if they're already signed in, right?

- I see your question "We incorporated some of the content from the latest 
update to the intent to file resource page (linked) into the Variants below. Have these updates been informed by research?  (ex: Do Veterans know what 
an identify-verified account is, and if they have one)?" 

We would welcome any and all research about Veterans' understanding of verified accounts! We saw the need to add this detail to the resource page because technically, Veterans can start the pension form and the form won't submit an ITF on their behalf if they're not verified. It would be misleading to only say that starting a pension form automatically generates an ITF. We don't want people thinking that they submitted an ITF if they actually haven't. 

3. Related to the previous thought, can the messaging conditionally show only for users who have signed in with verified accounts? In this scenario, we don't have to mention verified accounts because the Veteran has already signed in with one. 

If someone signs in and their account isn't verified, I would think they would need more context or a link somewhere to learn more about verified accounts. I know you worked with @laurwill on the sign in widget copy, which mentions verified accounts. How does the widget copy explain verified accounts?

4. CAIA recommends staying away from the bolded content. It's potentially misleading, because the ITF/the application itself does eventually expire: 

An intent to file ensures that you don’t lose out on any benefits, **no matter how long it takes for you to complete your application or for us to process 
your claim.**

**Comment by echin393** [comment]
We don't have targeted deadlines for this research study, so I'll schedule a meeting for us to discuss next week, and feel free to move it further out if you find that you need more time. 

In terms of your questions:
1. Good catch – screen 1.1 assumes that the user is both authenticated and verified with LOA2/3, so an ITF can be established for them. I updated the use cases to clarify that we're referring to "unverified" as having level of access (LOA) 1, and "verified" as having LOA 2/3. The last two variants are outdated from before that assumption was made, so feel free to ignore them.

2. Thanks for clarifying! We're hesitating to mention identity at this point in their journey because we assume intent to file is already a complex concept for Veterans to grasp, but we'll include questions about identity verification in our conversation guide to validate how familiar Veterans are with the concept and how it might impact the usability of our flow.

3. Yes, we've confirmed with our engineering team that we'll know what the user's LOA is after they sign in. So if they're already verified, we won't need to introduce verification to them. 
Messaging for unverified accounts (or messaging about verification) is out of scope for this research study so that we can focus on how to best communicate the benefits of ITF. We're currently investigating complexity on the back-end for this scenario, and our solution will be informed by what we learn after the study is complete.

4. The bolded text being potentially misleading makes sense. I'll await your suggestions for next week but will workshop alternatives in the meantime. Feel free to ask more questions async if that's useful.

**Comment by katherine-fung** [comment]
(moving the last 3 comments over to [ticket #87027 for the intro page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87027))

**Comment by echin393** [comment]
Hi @katherine-fung! I believe I've addressed all your comments in MURAL so far, but let me know if I've missed any or if you'd like to discuss them further. 
I also wanted to inform you that we've successfully had our research study materials reviewed and have sessions scheduled for the week of October 7, so we're hoping to get any additional content recommendations by the end of the week.

**Comment by katherine-fung** [comment]
Thanks @echin393. I left one more comment here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713384778236/cb7811f7fc7d62be8ebfcf962519f055c9df98e6?wid=0-1727102190791

**Comment by aprocik1** [comment]
Hi @echin393! It seems like all the work on this ticket is complete. Can we close it?

**Comment by echin393** [comment]
Hi @aprocik1 ! Apologies for the late reply. Our initial ask involved drafting intent to file content for our MVP experience. But after a change in approach, we pivoted to testing the content with Veterans first, before implementing.

Now that we've completed that research, our next steps are to iterate and implement the new experience to production. Katherine mentioned that Monica Lee would work with us for this next stage, but should we create a new ticket for that work?

**Comment by aprocik1** [comment]
@echin393, thanks! Let's keep this ticket open and return to it when you're ready to collaborate on the next phase. Do you have a sense of when that may be? If not, that's okay. Feel free to tag me in a comment on this ticket and we'll get this into our workplan.

**Comment by echin393** [comment]
@aprocik1 We're finalizing our research readout this week, so I'm expecting to share our learnings with Monica within the next couple weeks. With holidays and outages coming up, we don't have strict deadlines, but I'd want to make sure she has the context she needs around this problem area!

**Comment by echin393** [comment]
Not complete, but closing in favor of tracking our new intake ticket #106629 . This ticket is linked to our new one to keep record of progress.
