### ISSUE TITLE
Discovery: Add Page to Developer Docs BP: No PII in URL Query Strings

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#78926]
## Issue Description
Per this [Slack thread](https://dsva.slack.com/archives/C01CJV0L9PS/p1710948909809799), language needs to be added to the best practices section of the Platform Website developers docs regarding not putting PII in URL query strings.

---
## Tasks
- [x] Identify SME(s) who will draft the language
- [x] Review ticket including all comments
- [x] Mikki Northuis: make contact and confirm she can assist
- [x] Create page in drafts space
- [x] Determine where in IA new page will reside

## SME: 
- Jonathan Kamens: See comments **below**.
- Mikki Northuis: see **Tasks**

## Acceptance Criteria
- [x] SMEs ready to begin writing guidance

Related edit Ticket
[79318](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/79318)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@JonathanKamensDVA thank you for volunteering to assist with this new page. We will schedule this work for an upcoming sprint and reach to you soon.

**Comment by JonathanKamensDVA** [comment]
Not volunteering exactly, this is what the taxpayers pay me for. 😉

**Comment by JonathanKamensDVA** [comment]
I think this is probably going to evolve into something a bit larger than just not putting PII into query strings. And it's not going to be just me involved in writing it on the engineering side, because I want to make sure whatever we decide to put down as best practices isn't going to unduly burden the development teams. When the time comes I will work with the content team to jointly figure out how to collect input from stakeholders.

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/78926?planning-poker) with Zenhub @BSmolensky @laucon

**Comment by jknipes** [comment]
@JonathanKamensDVA we are most likely picking this up for the upcoming sprint 3/28/24. In addition to yourself, it was suggested we reach out to Mikki Northuis for guidance on writing this document.

**Comment by taylojill** [comment]
Hello @JonathanKamensDVA. I'm a writer on the Platform content team and can assist in updating/writing and publishing documentation for the Platform web site. I just read through the detailed Slack thread. Have any decisions been made on how to update the documentation? I have some ideas about adding information boxes/notes as a short term solution. The long term solution sounds like more of a challenge! Please let me know how I can help! 

cc @jknipes

**Comment by JonathanKamensDVA** [comment]
Hi @taylojill can you drop an hour onto my calendar next week for us to discuss on Teams rather than trying to hash it out in GH comments? ;-) We probably won't need a whole hour, I suspect it'll be closer to a half hour, but let's reserve a whole hour if you don't mind just so we don't have to worry about cutting the discussion short.

**Comment by taylojill** [comment]
Sounds good @JonathanKamensDVA, will do!

**Comment by taylojill** [comment]
4/2/24 - Met with Jonathan via zoom to discuss way forward. I'll be creating a new page and will work with him to finalize.

**Comment by mnorthuis** [comment]
Hey all, please include me in this conversation and work.  I see my name listed but have not talked with anyone on this.  At the very least it seems we need to make an update to the URL documentation in the design system - would have thought this would be self-explanatory, but apparently not.  While you can include info in the platform documentation, this is really a standard that is set and documented within the design system and we don't want to duplicate that information.

**Comment by mnorthuis** [comment]
@JonathanKamensDVA I've been here over 8 and still get tripped up!   The [URL standards](https://design.va.gov/content-style-guide/url-standards) are currently buried in the content style guide, which is an issue I am working on - I want it moved into the components section.   We also have some additional documentation we want to add regarding URLs used in form flows.  I have a small section regarding parameters in there, but parameters haven't been something we have used much as of yet, so it's light. 
  Would love to beef that up.  URLs are currently governed by myself and the IA contractors working across teams.

**Comment by taylojill** [comment]
Hi there @mnorthuis. I met with @JonathanKamensDVA earlier this week and we discussed a coding best practices page to be placed under the [Code and build section on the Platform web site](https://depo-platform-documentation.scrollhelp.site/developer-docs/code-and-build). I created a draft page that I just shared with you and Jonathan via our platform-content channel. I also attached a PDF of the draft here. I'll be out of office tomorrow and return on Friday. Please provide feedback and let me know how I can assist. 
cc @jknipes 
[PWD-Draft Coding best practices for Personal Identifiable Information (PII)-030424-200824(1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3d5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd65de8a42bfcd5e0901d6b31be365b04c9431df/PWD-Draft%20Coding%20best%20practices%20for%20Personal%20Identifiable%20Information%20%28PII%29-030424-200824%281%29.pdf)

**Comment by jknipes** [comment]
@mnorthuis Thank you so much for working with us in writing this guidance! As the PM for this team, I apologize for not initially reaching out to you directly and inviting your input.

**Comment by jknipes** [comment]
Discovery completed, moving to _Done_
