### ISSUE TITLE
GH-Action to Monitor Configuration Drift in Terraform

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#78924]
## Problem

Configuration has made it difficult to work with our terraform. We need a GH-action, or similar that warns us when our terraform state is "unclean"

Ideally, the GH-action is written in such a way that it can be made progressively stricter as our terraforms get cleaner in the context of this epic and other efforts.

**Tasks**
- [x] Create a daily gh-action (or similar) to help identify "unclean" Terraforms (this may be blocked by the other tasks)
- [x] It should pick up on things that were manually **deleted** in the UI, i.e. if the Terraform wants to add the monitor again.
- [x] It should pick up on Terraforms that have manual **changes** in the UI, i.e. if the Terraform is not in sync with what's in the UI
- [x] Is it possible to pick up on Terraforms that are in the code, but not in the UI?

**Success Metrics**
- [ ] ADD SUCCESS METRICS HERE

**Acceptance Criteria**
- [ ] ADD ACCEPTANCE CRITERIA HERE

**Comment by LindseySaari** [comment]
Chris is working on getting a PR up and paired with Rebecca. Getting this in soon!
