### ISSUE TITLE
Facility level operating status QA Design Review

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7895]
## Problem Statement
How might we ensure that the developed UI for displaying facility level operating status is consistent with design spec? 

## Goal
Ensuring consistency between design spec and development before release

## Objectives or Key Results this is meant to further
Objective 2: Deliver meaningful facility information

## Tasks
- [ ] Review and compare the most up-to-date UI with design spec 
- [ ] Meet with the frontend engineer to review any needed changes
- [ ] Document meeting notes in this ticket
- [ ] Create tickets for FE as needed

## Acceptance Criteria
- [ ] Differences between development and design are documented and understood

**Comment by mmiddaugh** [comment]
Review complete. Feedback provided and completed.
