### ISSUE TITLE
QA Design Review: Left Nav upgrade

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7896]
## Problem Statement
How might we ensure that the developed UI to upgrade the Left Nav menu is consistent with design spec? 

## Goal
Ensuring consistency between design spec and development before release

## Objectives or Key Results this is meant to further
Objective 2: Deliver meaningful facility information

## Tasks
- [ ] Review and compare the most up-to-date UI with design spec 
- [ ] Meet with the frontend engineer to review any needed changes
- [ ] Document meeting notes in this ticket
- [ ] Create tickets for FE as needed

## Acceptance Criteria
- [ ] Differences between development and design are documented and understood

**Comment by mmiddaugh** [comment]
@rtwell I created this issue to document any findings for the review of Gibran's left nav development on 4/15. 
FYI

**Comment by mmiddaugh** [comment]
The following needed changes were observed during review meeting with Ryan, Aricka and Gibran:

**Changes needed for "you are there" page**
- [ ] Background for selected state is too dark. Please reference Zeplin for correct color value. 

![image](https://user-images.githubusercontent.com/55411834/79383093-d99fd380-7f21-11ea-8693-d0d9ee7e01c8.png)

- [ ] Menu element for the current page should not be clickable. 
- [ ] Menu element for the current page should not be collapsible. 
- [ ] Current page left bar, text, rule above and at terminus of section should all be 323A45, gray-dark. 
Expected behavior, seen in Zeplin:

![image](https://user-images.githubusercontent.com/55411834/79382143-4dd97780-7f20-11ea-98c9-db4537684d25.png)

**Changes needed for hover state**
- [ ] When moving over the menu in hover state, horizontal and vertical animation is observed. Animation should not be present. 
- [ ] Background color in hover state should be white. Current development seems to have very light gray background on hover element. 
Expected behavior, seen in Zeplin:

![image](https://user-images.githubusercontent.com/55411834/79382238-7497ae00-7f20-11ea-92f0-67d992410d9e.png)

**General changes needed:**

- [ ] Section header label ("Services and locations") should render at font size = 14. 
- [ ] Buffer on either side of rule at the bottom of the section should be the same when the section is expanded as when the section is collapsed. Current development seems to reduce padding between rule and nav text elements when open section. 
Expected behavior, seen in Zeplin:

![buffer](https://user-images.githubusercontent.com/55411834/79382662-1ddea400-7f21-11ea-81cc-db364d31e17c.png)

- [ ] Boundary box for hover, active and "you are there" states should overlay gray menu border, if possible. Should not be able to see gray border on each side of boundary box around the menu element. 
Expected behavior, seen in Zeplin:

![image](https://user-images.githubusercontent.com/55411834/79382935-92194780-7f21-11ea-8b8c-22a189892cdb.png)

@rtwell please confirm that I have accurately captured the feedback. Thank you!

**Comment by jenstrickland** [comment]
@mmiddaugh I notice a couple of these are the things I would like to help with. I know why the "animation" is happening. @brangi — let me know if you'd like to hop on a call, or if you can put into staging and I can provide code guidance from there.

**Comment by mmiddaugh** [comment]
These remaining changes will be completed in Sprint 20
