### ISSUE TITLE
Update Staging Review host guidance for imposter components/QA

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#78969]
## User Story
As a host of the Staging Review, I want to ensure that all feedback on the VA.gov Experience Standards is communicated at the appropriate section of the SR so that there is no confusion from VFS teams.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
Historically, QA has delivered their feedback first at Staging Review, covering the teams adherence to the QA standards. However, now that QA is also responsible to providing feedback on imposter components within the VA.gov Experience Standards, we need to ensure our host guidance is updated so they call on the QA lead to share Experience Standards feedback too.

Any feedback on imposter components should be shared alongside the VA.gov Experience Standards issues shared by the design, content, IA and a11y team members.

## Impacted Artifacts
[Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting)

## Tasks
- [x] Update the guidance to make it clear that the first part of the meeting is regarding adherence to QA standards, not all QA feedback
- [x] Update the guidance so that the host calls on the QA specialist during the VA.gov Experience Standards section of the meeting to share any findings (ie imposter components)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] At Staging Review, QA shares feedback on imposter components alongside the other VA.gov Experience Standards findings

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Created a [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3064365067/78969+-+Allison+Staging+Review+-+During+the+meeting). @rferguson13 I know you are not the peer reviewer BUT I think you could probably double check this.

**Comment by rferguson13** [comment]
@allison0034 @briandeconinck - I took a look, and this looks good to me.

**Comment by briandeconinck** [comment]
@allison0034 This all looks good to me, with one minor thing I noticed: [Past versions](https://vfs.atlassian.net/wiki/pages/viewpage.action?pageId=2808447039&pageVersion=8) of the script call our standards the `VA.gov Platform QA Standards` and the `VA.gov Experience Standards` but here they're just `VA Platform QA Standards` and `VA Experience Standards`.

Is this intentional? And if not does it matter? 🤷 Just something I noticed.

**Comment by shiragoodman** [comment]
I hate to nitpick, but we should specify "VA.gov" and not just "VA"

**Comment by allison0034** [comment]
@shiragoodman @briandeconinck yeah it kept making them links and was really annoying. I did not think the .gov part mattered, it is VA. But I can add it back in.

Also saying ".gov" is a bit weird... could you imagine saying Yeah, I search on Google ".com" instead of just Google?

**Comment by shiragoodman** [comment]
yea, I get it @allison0034.  but we need to be sure we make the distinction. We don't manage all of the site standards for the VA... only the VA.gov website. There's still plenty of VA webpages that are outside of scope for us, including the mobile app. We don't want to blur the lines and introduce confusion for VFS teams.

FWIW I bet the folks at Google have a different way of communicating Google the company from Google the search engine. Maybe they do say Google.com in their back channels???
