### ISSUE TITLE
Discovery on Sentry storage space 

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#78986]
## Issue Description
We bumped the storage space by 400GB in February up to 1TB and by March 21 there were already alerts that 80% had been reached. We need to determine why the storage space is being consumed so quickly and clear it back. 

In a self-hosted Sentry setup with an RDS instance, the RDS database typically stores event data, including error reports, stack traces, and any additional data attached to events.

---
## Tasks
- [ ] Discovery on why there are so many wild fluctuations in storage (from .5 GB to 8 GB within one day, see monitor on February 1)
- [ ] vets website
- [ ] vets API
- [ ] VDP
- [ ] GIDS
- [ ] Query system tables or views to retrieve information about table sizes, index sizes, and disk usage.

## Acceptance Criteria
- [ ] We will have a solution so that storage space isn't being so wildly used
