### ISSUE TITLE
Update VFS member numbers in Atlas (Episode II)

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#79013]
## Purpose
It appears that some of the PM info in Atlas isn't accurate.  In order to give a reasonably accurate portrayal of the participation rate in the Satisfaction Survey, we need a headcount.

## Tasks
- [x] Determine how to identify which entries need correcting
- [x] [Identify incorrect entries and correct](https://docs.google.com/spreadsheets/d/1_virEsteT5bnyOPYPKqpwWQT-tC0Z4pJJZtY-HtHVSI/edit#gid=643985190)

## Acceptance Criteria
- [x] Atlas is updated to reflect known VFS member numbers
