### ISSUE TITLE
Update payment history page w/ notififcation Q&A

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#79026]
## Description
We need to add a new Q&A to this modern page: [View your VA payment history](https://www.va.gov/va-payment-history/)

The Q&A should provide directions on how to opt-in to receive text message notifications for VA disability compensation and pension payments. To do so, a user has to follow these steps:

- Sign in to their VA.gov profile
- Navigate to the **Notification settings** page
- Navigate to the **Payments** section
- Check the **Notify me by text** box

## Tasks
- [x] KF: Draft and add the new Q&A in Drupal
- [x] AP: Review
- [x] AP: Share with stakeholders
- [x] Stakeholders: Review
- [x] AP: Share draft and launch date with MZ / ST
- [x] MZ, ST: Copyedit and publish

## Criteria
- [x] Published new Q&A on payment history page

**Comment by katherine-fung** [comment]
Hi @aprocik1, I've drafted the new QA for your review: 

http://preview-prod.vfs.va.gov/preview?nodeId=714 

 
![Screenshot (448)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/105367381/d974b1ff-06ad-41ff-a880-8b78a8e02d78)

**Comment by aprocik1** [comment]
@katherine-fung, thanks! This is great. I'll share it with stakeholders on the intake ticket.

**Comment by aprocik1** [comment]
Update: The product team and I met today to re-start this work. I've updated the draft content with SME feedback and we're planning to publish these updates next week.

**Comment by aprocik1** [comment]
Update: The product team approved this final content: https://prod.cms.va.gov/va-payment-history

@megzehn and @saratorres2, can you two copyedit and publish this page at the end of this week? I'm still waiting for final confirmation from the product team on the exact date. Thanks!

**Comment by aprocik1** [comment]
@megzehn, we just received approval from stakeholders to publish [this page](https://preview-prod.vfs.va.gov/preview?nodeId=714). This is the new Q&A: Can I get a notification every time I receive a recurring VA payment?

Let me know when this is published and I'll close the loop with stakeholders. Thanks a lot!

**Comment by megzehn** [comment]
Thank you @aprocik1! Confirming I reviewed and published the update.
