### ISSUE TITLE
[FE] - Check travel answers before submission

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#79020]
## Description
There is a minor exploit that a patient could do to submit travel without answering questions or agreeing to statement. If they get through the travel-mileage page and then manually go to `my-health/appointment-travel-claim/complete`, it will submit the selected claim(s). We should add a check to see if they answered yes to everything. If not redirect them back to the intro page. 

## Tasks
- [ ] add check for travel answers
- [ ] redirect users who haven't answered or answered no back to beginning
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/79020?planning-poker) with Zenhub @lee-delarm6 @wullaski

**Comment by loripusey** [comment]
I'm assuming we are adding this to the current sprint?

**Comment by brianseek** [comment]
@loripusey that is why I brought this up in slack, not sure if you want to shuffle things around and put it in this sprint...or just wedge it in with everything else.

**Comment by loripusey** [comment]
Let's go ahead and add it to this sprint; I'd like to be done with testing this sprint if possible; things are chaotic right now anyway
