### ISSUE TITLE
40-0247 Content changes: Step 10 (Review page)

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#79037]
## Issue Description
CAIA did another review of 40-0247 recently and asked for a few minor content changes.

There are two punctuation issues in the Statement of Truth component

---
## Tasks
- [ ] Update statement of truth content to correct two punctuation issues:
<img width="981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFlEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a1d927992fd9e9af070c96b6d8cb2e142e7e46e/image.png" alt="image.png" />

## Acceptance Criteria
- [ ] Add period to the end of this paragraph.
> I confirm, to the best of my knowledge, that the deceased has never committed a serious crime, such as murder or other offense that could have resulted in imprisonment for life, has never been convicted of a serious crime, and has never been convicted of a sexual offense for which the deceased was sentenced to a minimum of life imprisonment.
- [ ] Remove period from the end of the last sentence (checkbox confirmation)
> I certify that the information above is correct and true to the best of my knowledge and belief (*Required)
---
[Figma](https://www.figma.com/file/U95x4PNKGVtA25aBvBdzrO/Prod---40-0247---Presidential-Memorial-Certificate?type=design&node-id=84-20519&mode=design&t=5QSu8vPg2JKie0ae-11)
[Source of Truth change log](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/pull/1146/files)

**Comment by tbaker1026** [comment]
Confirmed period added and removed
<img width="1038" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d2be725934fb916f0ee67757ace39bba3dbe61a/2024-04-12_16-06-40.png" alt="2024-04-12_16-06-40.png" />
