### ISSUE TITLE
40-0247 Content changes: Intro page

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#79032]
## Issue Description
CAIA did another review of 40-0247 recently and asked for a few minor content changes.

---
## Tasks
- [x] Make 3 changes to the Introduction page:

<img width="706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aebe4d07adab0c4e330991fc705318cb32917b23/image.png" alt="image.png" />

## Acceptance Criteria
- [x] Under the first step in the process list, combine two sentences into one paragraph: 
> Not sure if the Veteran or Reservist is eligible? Check eligibility requirements for burial in a VA national cemetery.
- [x] In the second step in the process list, change the word "submit" to "upload" in this sentence:
> But to speed up the process, we encourage you to upload these documents if they’re available:
- [x] In the second step in the process list, remove the note about sending original documents
> Note: Don’t send original documents since we can’t return them.

**Comment by AdamOye** [comment]
@rachelshearerux

**Comment by rachelshearerux** [comment]
LGTM, thanks Jacob! 
<img width="497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWcyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c496907d15b1a130122a4c7cb2e0091035a3e68/image.png" alt="image.png" />
