### ISSUE TITLE
Add suggestion about how to order the conversation guide (Footer Ticket 78195)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79042]
### Description

Edit the [Research With Assistive Technology users page](https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users) in the research section of the Platform website to include a bullet on screen sharing.
**Context**: The Decisions Reviews team learned some lessons during recent research with screen reader users that may be useful to other teams.

Page:

For https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users

### Tasks: 

- [x] After the bullet: "Write assistive technology-specific screener questions", add another bullet:

* When planning your conversation guide, it can be a good idea to set up the screen sharing first after a few qualifying questions. This way, if you can't get the screen sharing working, you can choose to pivot the session. You could reschedule, cancel or pivot the session to suit your needs.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/research-design/research-with-assistive-technology-users

### Definition of Done: 

- [x] Bullet point has been added to the page
- [x] New text adheres to Style Guide
- [x] Checked for LBs
- [x] Page is ready for deployment

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79042?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
Work is complete, moving to _Done_
