### ISSUE TITLE
[UX] 10-10 CG Update designs in Figma

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#79040]
## Issue Description
Paper form updates need to be reflected in Figma design files as well as updating the components to most current libraries for the templates and patterns. 

VADS Templates, Patterns and Forms

---
## Tasks
- [ ] [Figma page](https://www.figma.com/file/TxXD5bGUOhbHHWLb85GPjK/10-10CG?type=design&node-id=376-15166&mode=design&t=iJ7xEjqtCOv3EBCM-0) setup to annotate content changes between new paper version
- [ ] Create new screens using components from library VADS Templates, Patterns and Forms
- [ ] Update all CG screens

## Acceptance Criteria
- [ ] The CG screens will use the latest library components and the content will reflect the recent paper form changes
---

**Comment by jessicastump** [comment]
Closing as this is a duplicate of ticket #78497
