### ISSUE TITLE
Title and content changes to the "Screen reader checklist" (Footer Ticket 78266)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79051]
### Description

Edits and changes to the [screen reader pages in the research section](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-checklist
) of the Platform website will need to be performed

Proposed Changes summarized:

 - Updates page titles to better reflect some of the content available on the page
 - Add a note about the iOS screen getting stuck in safe driving mode, and how to get it out of that.
 - Add a note about users getting stuck in the Zoom menu on iPads and how to get out of that.
 - Add a note about some iPads getting frozen when using Zoom, and advice for dealing with that.
 
#### Tasks
- [x]  Review [original Footer Feedback](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78266) ticket for details
- [x]  Make contact with David Kennedy (requestor) and Brian Deconinck as SMEs 
- [x]  Update page
- [x]  Check for LBs

 ### Definition of Done:

- [x] Page has been updated and is ready for deployment

**Comment by jknipes** [comment]
@taylojill this is the work ticket that was created in response to Feedback Footer ticket 78266

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79051?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by taylojill** [comment]
I reached out to SMEs (Davis Kennedy and Brian DeConnick) via our Slack channel regarding the updates I made. I'm waiting for feedback. Here's a summary of what I did:
- I kept the "Screen reader checklist" as a parent page to avoid broken links and added child pages with links to two new pages: **Preparing for research with screen readers** and **Screen reader instructions and troubleshooting during research**.
- I added links at top of the "instructions" page to three headings (Desktop screen readers, iOS VoiceOver, TalkBack Android)
- Regarding the "Research with assistive technology users" page, I added the bullet as requested (blue color font)
- I added one inline comment regarding possible "missing information"

**Comment by taylojill** [comment]
Still waiting for feedback, I sent a DM to both SMEs with the summary information above.

**Comment by taylojill** [comment]
Made contact with both SMEs. No questions or comments on content. I asked if it was okay to update pages and publish this week.

**Comment by taylojill** [comment]
@jknipes - I'm going to update and publish the new pages. One SME said the changes look good (Brian), the other said it all made sense (David). I sent pdf copies to David via Slack DM and have had no response. I'm going to update the pages and publish based on the feedback they provided.

**Comment by jknipes** [comment]
Thank you @taylojill !

**Comment by taylojill** [comment]
All pages updated, date stamped, and checked for blockers. Ready to publish!

**Comment by jknipes** [comment]
Work is completed, moving to _Done_
