### ISSUE TITLE
EVSS PCIU Migration: Step 5: Monitor Betamocks setup

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#79050]
### Summary
Per the [meeting on 8/19](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3158704141/EVSS+PCIU+Meeting+minutes), the Platform Product team will not be doing the work on this, that will be done by Authenticated Experience team. The Platform Product team will be monitoring the work. 
VAProfile Betamocks examples have not been recorded. Follow these [instructions](https://github.com/department-of-veterans-affairs/vets-api-mockdata?tab=readme-ov-file) to record the VAProfile::ContactInformation response.

### Tasks
- [ ] Monitor the Authenticated Experience team while the tasks are executed
- [ ] Add VAProfile to [make_table.rb](https://github.com/department-of-veterans-affairs/vets-api-mockdata/master/make_table.rb)
- [ ] Record VAProfile::ContactInformation::Email response and push changes to the [Vets-API mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata)
- [ ]  Add VAProfile::ContactInformation to [VetsAPI Betamocks Setup](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/betamocks.md):
```
# VAProfile::ContactInformation
- :base_uri: <%= "#{URI(Settings.vet360.url).host}:#{URI(Settings.vet360.url).port}" %>
  :endpoints:
  - :method: :get
    :path: "/demographics/demographics/v1/*/*"
    :file_path: "vet360/demographics/default"
```
- [ ] Update doc: [Betamocks Mockdata Example](https://vfs.atlassian.net/wiki/x/SoBnc)
- [ ] Review all Betamocks documentation and instructions

### Related issues
[VA Profile Mockdata](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/68412) can completed concurrently with this ticket.

**Comment by RachalCassity** [comment]
Reached out to Auth Exp for help in this[ slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1711372776331159)

**Comment by jennb33** [comment]
This ticket may be split and the remaining work will go into the next Sprint.

**Comment by RachalCassity** [comment]
@jennb33 This ticket should be moved to the next sprint. This work mirrors [VA Profile Mockdata solution ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/68412) and can be done concurrently.

**Comment by LindseySaari** [comment]
[Here is a doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/backend/recording_responses_locally.md) that provides steps for creating a Ruby script to record responses from the VA Pro Contact Info API.  


There are two more docs to assist in recording responses:
- [Authenticated Experience: Using Mock Data](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/developer/mock_data.md) - outlines some steps for setting up a local env with mock data.
- [Profile: Mocking Data for VA Profile Service History API](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/developer/mock_va_profile_service_history.md) - outlines steps for connecting local vets-api to staging APIs and recording mocks.

**Comment by RachalCassity** [comment]
Setup a remote branch in the vets-api. Waiting for the meeting with VA Profile to answer questions.

**Comment by RachalCassity** [comment]
This may have to be post-poned until the VAProfile version update has been completed. VAProfile V3 needs different credentials and might have different outputs.

**Comment by jennb33** [comment]
8/5 update: this needs to be reviewed for assignment to other VFS team.

**Comment by rmtolmach** [comment]
@jennb33 in the [meeting notes](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3158704141/EVSS+PCIU+Meeting+minutes) from yesterday, it was decided our team won't do this work but we'll pass it to the owning team.

**Comment by jennb33** [comment]
Thanks, @rmtolmach - I've updated the name and summary for this ticket to be more focused on the monitoring of the work

**Comment by jennb33** [comment]
10/10/2024: @rjohnson2011 has been researching the information to update the ticket. Documentation is clear. Will reach out in Slack if there are any issues.

**Comment by rjohnson2011** [comment]
Spoke with Tom Harrison (PM of Authenticated Experience) regarding this ticket. There is an initiative in place to replace Betamocks with an internal tool to record mock data in an upcoming sprint led by Charley Stran. We agreed it would be redundant and unnecessary to record these mock calls twice.

Relayed this into to Lindsey H and she also agreed this ticket is no longer relevant due to the upcoming internal tool to record mock calls.
