### ISSUE TITLE
Content Edits: Footer Ticket 78683

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79065]
### Description

- The Deployments page doesn't include information about when the devops/revproxy repo deploys. 
- Many teams use this repo for redirects, and it would be helpful to understand the deployment cadence.
- The Platform Devops COP are the SMEs who can help provide the information that should appear. 

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments
[Footer ticket 78683](https://github.com/orgs/department-of-veterans-affairs/projects/1463/views/1?filterQuery=78683&pane=issue&itemId=84087792&issue=department-of-veterans-affairs%7Cva.gov-team%7C78683)

## SME:

- Kshitiz Shrestha ("Sha-teez") (DevOps Support Tier 2, 11/1/24)

---
## Tasks
- [x] Connect with DevOps SME via vfs-platform-support request
- [x] Determine whether page update can be completed now or needs to be scheduled into future sprint
- [x] Update page if possible: [info here](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/tree/main?tab=readme-ov-file#deployment)
- [x] Create separate Edit ticket if necessary and assign to a sprint

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79065?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
[SME requested in Platform Support channel in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1730409698278749)

**Comment by BSmolensky** [comment]
After a lot of research and several attempts at possible fixes, I had to reach out the the SME for some advice. The two tables on the two pages provided different categories of information (different columns) and there was not easy way to square them. So, in the end, the solution is to copy the Rev Proxy Deployment info and paste the entire table into the Deployments doc. This will likely mean creating a new sub-section of the page, with intro and other helpful, contextualizing information.

**Comment by BSmolensky** [comment]
All tasks complete. Ticket ready to close.

**Comment by jknipes** [comment]
Closing as _done_
