### ISSUE TITLE
Get the user passed in

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79068]
## Description
Enhance the control plane to accept and process user information. This is necessary for attributing environment actions to specific users and for permissions management.

---

### Tasks
- [ ] Define the user data model for the control plane.
- [ ] Update API endpoints to accept user information in requests.
- [ ] Implement logic to store and utilize user information in the control plane.

### Acceptance Criteria
- [ ] User information is correctly passed and processed by the control plane.
- [ ] Actions in the control plane can be attributed to specific users.

**Comment by JoeTice** [comment]
SPRINT 50 UPDATE - IN PROGRESS: Will be completed in Sprint 51
