### ISSUE TITLE
Content Edits: Ticket 75519

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79061]
### Request type
Per ticket [75519](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75519), we need to add documentation to Platform Website regarding 
compatibility of file and folder names.

## Tasks
- [x] Review suggestions and linked conversations in ticket [75519](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75519)
- [x] Draft the new language 
- [x] Review with Clint Little for publication on PW
- [x] Check for Launch Blockers

## Acceptance Criteria
- [x] New guidance is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79061?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by CherylEvans** [comment]
@jknipes @little-oddball After reading the original ticket ([75519](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75519)) and the [Slack thread discussion](https://dsva.slack.com/archives/CE4304QPK/p1707171463655899), I think I may have a workable solution. I agree with Clint that it may not make sense to include the information in GH handbook. 

It makes sense to me to create a new page with the new content and move it to an appropriate location:

"When adding to our GitHub repositories, to avoid using file and folder names which aren't compatible with both Windows and macOS. I know it's tough because most of us are using only one or the other and also some of us upload files directory into repositories via the GitHub web interface rather than committing and pushing from our desktops.
In particular, please avoid the following:

file names containing question marks
names containing colons
names containing pipe symbols (|)
names ending with space
names ending with period
file paths longer than 256 characters, with a healthy margin for error since the limit on Windows includes the full path of each file starting with the drive letter, i.e., the path in the repository plus the path of the directory it's checked out into needs to be less than 256
Also, though it won't strictly speaking break the OS, it's a good idea to avoid file names starting with space."

I'll rework the content to comply with DSSG standards and place the page in an appropriate location. 

Please see my attached screenshot. 

Let me know what you think, and if need be, we can hop on a call.

<img width="1608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9879945dc904453a54ae6959de2f55635f55026/Ticket%2079061%20%28Content%20edits%20from%20ticket%2075519%29.png" alt="Ticket 79061 (Content edits from ticket 75519).png" />

**Comment by CherylEvans** [comment]
@jknipes @JonathanKamensDVA @little-oddball 
I’ve finished the first [draft ](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3258449923/79061+Cheryl+Draft+-+Adding+files+to+the+GitHub+repository)of the page I created for the new content.
Please feel free to make your comments directly to the confluence page. Thank you!!

**Comment by CherylEvans** [comment]
The new content page has been published. It is referenced on the Request Access to Tools page with a [link](https://vfs.atlassian.net/wiki/spaces/GS/pages/3258449923).
Closing ticket.
