### ISSUE TITLE
Discovery Ticket: Google Drive: Link destination incorrect (Footer Ticket 78811)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79066]
### Description

On the top of [this page](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/google-analytics-and-google-tag-manager#GoogleAnalyticsandGoogleTagManager-FrequentlyAskedQuestions), 
Check out our [answers to frequently asked developer questions](https://depo-platform-documentation.scrollhelp.site/wiki/pages/createpage.action?spaceKey=AT&title=Frequently%20Asked%20Questions%20for%20Google%20Analytics%20Developers) goes to a **404 - Page Not Found**.

## Tasks
- [x] Identify SME to provide guidance for this link
- [x] decide whether to remove, replace or otherwise redirect users toward a new source.
 
## Acceptance Criteria
- [x] Page is ready to be updated

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79066?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
Discovery is complete. Moving to _Done_

**Comment by jknipes** [comment]
work being done on ticket 79531
