### ISSUE TITLE
Research: Consider adding underline to link text on Platform website (Footer Ticket 76151)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79060]
### Description

- Should Content Team add underlines to all links on Platform Website?

### Tasks

- [ ] Research Accessibility guidance
- [ ] Research PW Style Guide

### Definition of Done
- [ ] Decision whether to update all links on PW
- [ ] Separate ticket created for the work

## Context from Footer Ticket: 
Links on the Platform website are dark blue with no default text decoration, while body text is black. It can be hard to quickly differentiate link text from regular body text. This presents obstacles for users scanning for links on the page, and could also make usability more difficult for users with difficulty differentiating colors. It would be a usability and accessibility improvement to convey that text is a link beyond the use of color - ideally by underlining links. I hope this will be considered for all links on the site, but especially links that are not part of navigation components (i.e. inline links in page content).

### Screenshot 
how inline text links are currently rendering (this is on the [Modernized VA.gov Accessibility Strategy](https://depo-platform-documentation.scrollhelp.site/getting-started/modernized-va-gov-accessibility-strategy) page):

![Screenshot 2024-02-13 at 4 38 16 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/1ffc28fe-3a72-4095-a170-bffd5eb78fb0)

**Comment by jknipes** [comment]
Closing this duplicate ticket, work is duplicated on 76566
