### ISSUE TITLE
[UX] Prepare eligibility userflow for VTP presentation 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79079]
## Tasks
- [x] Add in additional details needed into the [standalone text "travel" app userflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710791726585/8f9fed902def1a0b455ce1b5541f93444e91f615?sender=u37bb983bd3fc3cc00c7d3286) to be prepared to present to VTP office. E.g., decide on format (Mural, PDF, etc.), do any background or research findings need to be added, do any legends or labels need to be added, does the fidelity need to come up a bit for better comprehension, would it be helpful to see the flow for OH, VistA and eCheckin with eligibility in this one presentation, would it be helpful to structure the mural as an agenda, like challenge, solution, questions, next steps, etc. If needed, feel free to use anything created in the [userflow for VistA with eligibility](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711130372680/af42986654957f5cb47bf421ff89909c5595ecae?sender=u37bb983bd3fc3cc00c7d3286), which was created to understand if there would be a difference between OH and Vista, which there is not. 

### Who needs to review? Remove rows that aren't needed for this work.   
- [x] UX team
- [x] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? If Yes, provide details in comments. 
- [ ] Yes
- [x] No
      
## Acceptance Criteria
- [x] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/79079?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske assigned to both of you, you feel like tackling together? Or, feel free to unassign one person, if that's better.

**Comment by benbrasso-agile6** [comment]
I'm going to take this one based on our convo

**Comment by benbrasso-agile6** [comment]
@cgednalske @zach-park rdy for validation. Christina, when ready, post to check in channel for visibility and questions and comments. Should also seek advice from Kristen and Kay when they think is a good time to present this to VTP. E.g., should we wait until the BT team is further along with the check claim status tool? Or is it okay to schedule a presentation sooner? 

Mural - https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711130372680/af42986654957f5cb47bf421ff89909c5595ecae?sender=u37bb983bd3fc3cc00c7d3286

[Userflow for adding eligibility.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--daba7c74c111c9014b63cb2816bc51a7e1931dbd/Userflow%20for%20adding%20eligibility.pdf)

**Comment by benbrasso-agile6** [comment]
cc @loripusey

**Comment by loripusey** [comment]
Looks good

**Comment by benbrasso-agile6** [comment]
Will add in a recap about research completed per comment from Christina

**Comment by benbrasso-agile6** [comment]
@cgednalske made some changes, ready for validation

**Comment by cgednalske** [comment]
@benbrasso-agile6 awesome! Could we include the action takeaways in there too so there's a clear link to the final result? 👀

**Comment by benbrasso-agile6** [comment]
I thought I did? Or, would you want to change the heading "Research insights" to "Research takeaways"?

**Comment by benbrasso-agile6** [comment]
Oh, I see what you mean, one sec

**Comment by benbrasso-agile6** [comment]
@cgednalske recheck please https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711130372680/af42986654957f5cb47bf421ff89909c5595ecae?sender=u37bb983bd3fc3cc00c7d3286

**Comment by benbrasso-agile6** [comment]
Replied to your reply

**Comment by benbrasso-agile6** [comment]
Closing; @cgednalske you have an action item to surface in slack
