### ISSUE TITLE
DR | Update tags on all monitors

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#79072]
## Value Proposition

As the VA, I want the DR team to use our new tagging policy for monitors, so that we can better track the overall health of VA.gov.

## Background

In February, VA announced a new tagging policy for DataDog monitors. See https://dsva.slack.com/docs/T03FECE8V/F06K3KGT5G8. Eventually, we need to update our monitors accordingly. Please note that monitors now cannot be edited or created without specifying the new tags referenced in the policy. I have added the requisite tags to some, but not all, of our monitors. For `service`, I have been using `notice-of-disagreement`, `supplemental-claims`, and `higher-level-review`.

## Tasks
- [ ] Read and understand policy
- [ ] Add new tags to monitors

## Acceptance Criteria
- [ ] All monitors in https://docs.google.com/document/d/1QubK2pAkPKFaEhrFZwslyVgkG3VqUhmWOqj839mDEl0/edit are updated.

## Definition of Ready
N/A. Ready now.

## Definition of Done
- [ ] Acceptance criteria met.

**Comment by shaunburdick** [comment]
Finished, needs validation.
