### ISSUE TITLE
Consider approach and impact for changing Find a Rep search from GET to POST

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#79083]
## Background
The security team is concerned that we have location information in the URLs for Find a Representative -- both addresses and latitude/longitude coordinates.  [Original slack thread](https://dsva.slack.com/archives/C01CJV0L9PS/p1710948909809799)

Their recommendation is that we change how our Find a Rep gets search results from the backend -- a GET request instead of a POST request.  

This would be most involved in the **frontend**, where we'd need to remove the current logic that relies on parameters in the URL to retrieve search results from the backend through a GET request.  Instead, we'd need to put parameters into the body of a POST request.  

The **backend** work is much more straightforward, where we'd just change the type of request the backend is expecting.

This ticket is to hold space for fully defining that frontend and backend work, with some open questions to consider:
1. How does this impact the URL behavior of Find a Representative after a search is performed?  
2. How might we track search behavior if we can’t rely on the URL to determine parameter activity?
   1. In an initial discussion, Jamie Stutt in Analytics mentioned that location can still be tracked via a "PUT" event.  Another option, is that we can strip the location from the URL for Google Analytics, but still record an event.   Jamie is available to help if we would like to consult her further when the time comes.

## Tasks
- [ ] Answer open questions
- [ ] Outline a technical approach for both the frontend and backend, to shift our approach from GET to POST requests

## Acceptance Criteria
- [ ] The work to remove location information in URLs has been outlined, giving the ARM team an approach for mitigating PII concerns in the Find a Representative product.

**Comment by oddball-lindsay** [comment]
The Facility Locator team's approach to this issue is in this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17619

**Comment by oddball-lindsay** [comment]
Facility Locator is waiting for a response from Security to confirm their update is sufficient.  If it is, we can mirror their solution.  The solution work was handled in these PRs:

_TBD_

**Comment by oddball-lindsay** [comment]
The only other work is the FE integration with the POST endpoint, which is captured in this [draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30199)

**Comment by parkerbees** [comment]
Adding relevant links from my conversation with Holden: [previous facility locator work](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18128), [GET vs POST conversation](https://github.com/department-of-veterans-affairs/va-iir/issues/727#issuecomment-2136298330)
