### ISSUE TITLE
Issue with Sentry: Sentry failed due to spike of events

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79119]
## Issue Description
When there were significant spike of events earlier in March with Sentry, resulting in a failure of of the Sentry tool, multiple solutions were tried, including resetting the offset which didn't work. Later we deleted the offset and deleted the group from Kafka and added the group to Kafka and recycled the pods, which made it work.

The PR that started the issues in March is [here](https://github.com/department-of-veterans-affairs/vets-api/commit/92b4d011960458808bfd65f2074951ff3dc98d50)

<img width="606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd29JQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69a53843abafdac44fd8e0ff7af99d8515d46133/image.png" alt="image.png" />

This is showing 42.5% more than the four week average.

Both the mobile and identity teams were contacted regarding these issues, and they do not believe it to be an issue, but it is because Sentry is ingesting 3.3 million errors. MHV and Identity had started to started to track and report these JWT errors. It is important to note that these are not new issues, the teams just started to report them.

Sentry found SIX MILLION errors [here](http://sentry.vfs.va.gov/organizations/vsp/issues/250800/?project=1&query=is%3Aunresolved)

Mobile can’t force users to upgrade if there is an existing bug that a subsequent release has fixed said bug; they have to wait until the user downloads the upgrade. 

### Additional Context
Looks like mobile is [sending a nil auth header](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20status%3Aerror%20%40message_content%3A%22Access%20token%20JWT%20is%20malformed%20%3A%20%7B%3Aaccess_token_authorization_header%3D%3E%5C%22undefined%5C%22%7D%22%20&cols=host%2Cservice&event=AgAAAY52BfSZ-Qu7WgAAAAAAAAAYAAAAAEFZNTJCZ2Z4QUFCLWdBZGZOTlp4UHdBegAAACQAAAAAMDE4ZTc2MDYtMGI4YS00MGFmLWE3ZTgtNWZmMWFmZWYzZTZm&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sp=&storage=hot&stream_sort=desc&viz=stream&from_ts=1708784998911&to_ts=1711376998911&live=true), which aligns with what we see with not-signed-in
This is still an issue because it appears they fixed it but then something happened again on the 11th.

<img width="1742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0647c9a7c0e34a63afacb05005b175d954ab4478/Screenshot%202024-03-25%20at%2011.04.47%20AM.png" alt="Screenshot 2024-03-25 at 11.04.47 AM.png" />

---
## Tasks
- [ ] Identify the responsible party/team who is causing these logs
- [ ] Document the steps required to resolve the issue
- [ ] Responsible parties - inquire with teams around the additional logs

## Acceptance Criteria
- [ ] Sentry is a more stable environment with fewer crashes
- [ ] Documentation to resolve future issues is documented
- [ ] Sentry is running (even if storage and logs are not optimal - for now)

**Comment by jennb33** [comment]
There were more errors on Monday 3/25 going into Tuesday 3/26 but it autocorrected. 
This ticket will roll into Sprint 50.
