### ISSUE TITLE
Governance to re-check operational guidance and VFS-facing guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#79130]
## User Story
As a Governance team member supporting the move of PSIRR in the Collaboration Cycle, I want to identify which docs/guidance will be impacted so that I can ensure they do get updated.

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
Governance began work to support epic #52419 in spring of 2023. Much of the work was in draft state when the Platform Security team put this work on pause in order to prioritize the ATO renewal. We are now at a place where Platform Security is able to pick the work up again.

As a reminder, the goal of the epic is to move the Privacy, Security, Infrastructure, Readiness Review (PSIRR) touchpoint to earlier in the Collaboration Cycle, specifically post-Design Intent. This will hopefully encourage VFS teams to engage with the Platform Security team earlier in the process, ensuring issues are identified and able to be fixed earlier, and there is less risk with changes being made closer to launch.

In order to make those changes, Governance must review our operational process to identify where changes need to be made in our own process to support PSIRR moving to post Design-Intent.

The purpose of this ticket is to review the previously completed work for the changes made, identify which docs/guidance will need to be modified, and identify a list of current guidance docs (VFS-facing and operational, and github) that will require changes.

## Impacted Artifacts
See linked documents in the Tasks section

## Tasks
- [x] Review the documentation drafts from previous PSIRR work. Archive/delete any out of date drafts.
- [x] List which operational docs will be impacted by the PSIRR move
   - [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
      - Extensive changes made to this since the PSIRR draft was created
      - Archiving the [PSIRR kickoff responsibilities draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2615902252/56316+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) as out of date
      - Changes to be made to current guidance:
         - Remove "recommended" when describing touchpoints in all occurrences
         - Move PSIRR so that it's between Design Intent and Research Review in the touchpoint order list
         - Move PSIRR code block between Design Intent and Research Review, both combined code blocks and individual code blocks
         - Remove PSIRR task in post-staging VFS tasks in staging review code blocks
   - Design Intent - Moderator Responsibilities guidance no longer exists (broken into three pages), and I don't think any of the current pages reference PSIRR or need any updates. Archiving [PSIRR DI responsibilities draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2615902277/56316+-+Design+Intent+-+Moderator+Responsibilities)
   - Midpoint Review - Moderator Responsibilities guidance no longer exists (broken into three pages), and I don't think any of the current pages reference PSIRR or need any updates. Archiving [PSIRR DI responsibilities draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2615902302/56316+-+Midpoint+Review+-+Moderator+Responsibilities)
- [x] List which VFS-facing docs will be impacted by the PSIRR move.
   - As part of PSIRR work, each CC page on Platform website was touched to remove "recommended" and rephrase how we described the touchpoints. Instances where PSIRR is directly referenced also had some minor changes.
      - The following pages have been updated since the PSIRR work was done and will need to be touched --- but the archived drafts may still be useful when making new updates:
         - [Collaboration cycle](https://vfs.atlassian.net/wiki/spaces/CC/overview?homepageId=1524891996) - [archived CC draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327041/56317+-+Collaboration+cycle)
         - [Collaboration Cycle FAQ](https://vfs.atlassian.net/wiki/spaces/CC/pages/1864073263/Collaboration+Cycle+FAQ) - [archived CC FAQ draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327089/56317+-+Collaboration+Cycle+FAQ)
         - [Collaboration Cycle Kickoff](https://vfs.atlassian.net/wiki/spaces/CC/pages/1760493650/Collaboration+cycle+kickoff) - [archived CC Kickoff draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618359817/56317+-+Collaboration+cycle+kickoff)
         - [Resources](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources) - [archived Resources draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618359831/56317+-+Resources)
         - [Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints) - [archived Touchpoints draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327101/56317+-+Touchpoints)
         - [Design intent](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+intent) - [archived DI draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327113/56317+-+Design+intent)
         - [Sitewide CAIA](https://vfs.atlassian.net/wiki/spaces/CC/pages/2124906551/Sitewide+Content+Accessibility+and+Information+Architecture+CAIA+intake+request) - [archived Sitewide CAIA draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327134/56317+-+Sitewide+Content+and+IA+intake+request)
         - [Midpoint review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review) - [archived Midpoint review draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327175/56317+-+Midpoint+review)
         - [Analytics request](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782120453/Analytics+request) - [archived Analytics request draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327196/56317+-+Analytics+request)
         - [Contact Center review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782317061/Contact+center+review) - [archived Contact Center draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327213/56317+-+Contact+center+review)
         - [Staging review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review) - [archived Staging review draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327230/56317+-+Staging+review)
         - [Privacy, security, and infrastructure readiness review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782317101/Privacy+security+infrastructure+readiness+review) - [archived PSIRR draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327487/56317+-+Privacy+security+infrastructure+readiness+review)
      - The following pages haven't been touched since before May 2023, so the PSIRR drafts are still usable:
         - [Research review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781891143/Research+review) - [Draft Research review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327154/56317+-+Research+review)

**Update:** Per discussion at 4/18 stand-up, we'll only be touching pages that directly reference the PSIRR touchpoint. The updated language around recommended vs required touchpoints will be left for a future ticket.

With that, the following pages need to be updated:
- [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) (See notes above on required changes)
- [Collaboration cycle](https://vfs.atlassian.net/wiki/spaces/CC/overview?homepageId=1524891996) - [archived CC draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327041/56317+-+Collaboration+cycle)
- [Touchpoints](https://vfs.atlassian.net/wiki/spaces/CC/pages/1768423528/Touchpoints) - [archived Touchpoints draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327101/56317+-+Touchpoints)
- [Privacy, security, and infrastructure readiness review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1782317101/Privacy+security+infrastructure+readiness+review) - [archived PSIRR draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2618327487/56317+-+Privacy+security+infrastructure+readiness+review)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have identified which VFS-facing guidance will need to be modified to support moving PSIRR to post DI
- [ ] We have identified which operational guidance will need to be modified to support moving PSIRR to post DI
- [ ] We have archived old/outdated drafts of our operations/VFS-facing guidance changes

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Tasks section updated with links and discussion of the status of each page.

From the work that was done in May 2023...
- One draft can be kept as-is and rolled straight onto Platform website (Research Review touchpoint page hasn't been touched in the last year)
- Two draft changes to internal guidance can be discarded entirely --- the Design Intent and Midpoint Review moderator guidance has changed so substantially that the updates for the PSIRR work last year are no longer relevant and no changes are needed to the existing documentation
- 13 pages need to be touched in some way
   - Internal CC Kickoff guidance needs the most editing
   - VFS-facing Collab Cycle pages on Platform website mostly just need some light editing, mainly removing the word "recommended" and some minor changes whenever PSIRR is mentioned

**Comment by briandeconinck** [comment]
@it-harrison I think this is ready for review, but please let me know if any of my notes don't make sense

**Comment by shiragoodman** [comment]
thanks for your work on this @briandeconinck ❤️

**Comment by it-harrison** [comment]
@briandeconinck - looks good!

**Comment by shiragoodman** [comment]
per standup on 4/18, we will only be making changes to address the change in PSIRR, while previously we had planned to implement changes regarding recommended vs. required touchpoints. The latter will no longer be included in this change. @briandeconinck if you could please update the ticket to reflect this, I'd appreciate it!

**Comment by briandeconinck** [comment]
@shiragoodman Ticket updated to note that only four pages will need to be updated on this pass. Closing as complete, looking forward to making those edits when they're assigned to me 😆
