### ISSUE TITLE
UPDATE: Embed Page Footer Doc

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79141]
While assisting Dan Turner with a batch of developer docs, I noticed that his pages were missing the footer. So, I reminded him that he needed to include the footer and sent him a [link to the instructions on how to embed the footer](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro). Well, I read through it and the page needs and update. At a minimum, the images need to be updated to show the current page footer. But the wording and instructions could also use some freshening up. 

### TASKS

- [x] Read through [Embed Page footer doc](https://vfs.atlassian.net/wiki/spaces/AP/pages/1926955087/Embed+a+page+footer+with+the+Include+Page+macro)
- [x] Polish language (if you think it needs it)
- [x] Update images with screenshots that contain current footer

### ACCEPTANCE CRITERIA

- [x] Page has been updated

**Comment by jknipes** [comment]
This ticket may share issues with ticket 80354

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79141?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by BSmolensky** [comment]
Pages has been updated. Ticket ready to close.
