### ISSUE TITLE
Feasibility assessment of unauth financial hub and auth portal ideas

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#79151]
### Issue Description

**What details are necessary for understanding the specific work or request tracked by this issue?**

The Debt Resolution UX Team just wrapped up an exploratory study for the combined debt portal where one objective was to understand the desirability of a more comprehensive financial hub for Veterans and features that would be desirable. 

We received a positive signal for the desirability of different feature ideas including: 

Financial literacy, mobile, travel pay, financial resources, update dependents

While further research will happen to validate these feature ideas, the team will begin to think through the feasibility of these features. 

### Tasks

 **What work is necessary for this story to be completed?**
- [ ] Discussions with frontend team, CAIA, and others to discuss feasibility and partnering on these feature ideas
- [ ] Prioritization layer in terms of lift/feasibility

**Unauth:**
- [x] Review Debt portal exploration research to prioritize what to include
- [x] Create hub mockup 

**Auth:**
- [x] Review [2018 blue sky auth experience](https://vsateams.invisionapp.com/console/share/X3WBOA3QSWR)
- [x] Create low-fi mockup 

### Acceptance Criteria

 **What will be created or happen as a result of this story?**

- [ ] Discussions with frontend team, CAIA, and others to discuss feasibility and partnering on these feature ideas
- [ ] Prioritization layer in terms of lift/feasibility - compiled into a document
- [x] Unauth mockup created
- [x] Low-fi auth mockup created

 Attached to a Milestone (when will this be completed?)

**Comment by charlottecesana** [comment]
Update: The prioritization workshop will inform what feature ideas we would like to focus on in the next 2 fiscal quarters (Financial literacy, mobile, travel pay, financial resources, or update dependents). Once confirmed, we will initiate discussions with frontend and/or other teams. Megan has started thinking about the feasibility for the financial literacy piece.  @Tom-Davis @josephrlee @HeatherRienks @mgleo

**Comment by josephrlee** [comment]
We have begun to work on this and have drafted a [couple of concepts](https://www.figma.com/file/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?type=design&node-id=1434-19940&mode=design&t=ig7vXVWphavxCnnM-11) for @denisecoveyduc to share at her offsite this coming week. We will be holding off on further work until we hear updates from Denise's off-site on the future direction of this work.

cc: @HeatherRienks @mgleo @charlottecesana

**Comment by mgleo** [comment]
Low fidelity "blue sky" mock up for Authenticated experience:

<img width="773" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy8yQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b33b56c8c398103431c20af797364ed15ba2b68c/Blue-sky-auth-portal.jpg" alt="Blue-sky-auth-portal.jpg" />

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis Moved to Validate

**Comment by Tom-Davis** [comment]
Complete for now as priorities shifted and we will make a new ticket when this picks pack up. Closing.
