### ISSUE TITLE
Cancel April 2024 sessions and communicate to VFS

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#79168]
## User Story
As a Governance team member, I want to cancel the April orientation sessions so that Platform teams do not have to host and can instead refer VFS teams to the video recordings.

Assignee: @shiragoodman 
Peer Reviewer: @allison0034 

## Description
There are several orientation sessions scheduled in April 2024 that need to be cancelled. The purpose of this ticket is to cancel the April sessions, communicate to VFS teams that live sessions will no longer be offered, and direct them to the recording of the orientation sessions for reference. 

**Note:** this ticket is only for cancelling the live sessions scheduled for April, however we still need to update Platform Website and all VFS-facing guidance per ticket #76803. This work is planned for the following sprint March 28 - April 10.

## Tasks
- [x] Craft a message to communicate in all Calendly cancellation notices
   - Message: _Platform crew will no longer be hosting live orientation sessions as of April 2024. All new VFS team members will be asked to watch the recording of the latest session instead. Recordings can be found on the Platform Website Orientation sessions page: https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions. More information about the discontinuation of live orientation sessions will be shared soon via the #vfs-change-announcements channel on Slack. Thank you for your understanding._
- [x] Cancel the live sessions so no one else can sign up:
   - [x] Design & Research - April 1
   - [x] General Orientation - April 2
   - [x] Accessibility Orientation - April 5
   - [x] QA Orientation - April 10
   - [x] Analytics Orientation - April 18
   - [x] Design System orientation - April 19
   - [x] Front end orientation - April 23
   - [x] Back end orientation - April 24
 - [x] Cancel the existing events for the live sessions and copy/paste the message above into the cancellation reason text box in Calendly:
   - [x] Design & Research - April 1
   - [x] General Orientation - April 2
   - [x] Accessibility Orientation - April 5
   - [x] QA Orientation - April 10
   - [x] Analytics Orientation - April 18
   - [x] Design System orientation - April 19
   - [x] Front end orientation - April 23
   - Note: no one signed up for backend orientation so there's no event to cancel

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] April 2024 Platform Orientation live sessions have been cancelled

## Team Notification
- [x] Slack post on ~~#platform-governance-team~~ #platform-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Hey @allison0034  - I'm picking up this ticket last minute today in order to get the sessions cancelled by next week. Can you please review the message I drafted under the first task? Let me know if you think I should make any changes.

**Comment by allison0034** [comment]
@shiragoodman this looks good except I would link "Platform Website Orientation sessions page" rather than type out the url.

**Comment by shiragoodman** [comment]
I'm not sure if I can link it since it's through the modal in Calendly
<img width="283" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/2b0b28d3-851e-4c11-82e5-9a6e04310436">

**Comment by allison0034** [comment]
Oh gotcha! Then it is good as is!

**Comment by shiragoodman** [comment]
cool - I'll be finishing this ticket today then. You should receive the email when I cancel the Design & Research session.

**Comment by shiragoodman** [comment]
All sessions have been cancelled, and no one will be able to sign up for any sessions in April. @allison0034 lmk if there's anything I missed, otherwise I think this is good to close.
