### ISSUE TITLE
Develop submission model and success path for submit redesign

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#79178]
## Description
This ticket will establish a conceptual model for submission model at a conceptual level and apply it to the happy path for the submit experience redesign. This will inform the rest of the issues in [Improve submission user experience #78179](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78179).

Happy path channels / artifacts in scope for this might include:
1. Email message for happy path
3. Confirmation page
4. Pdf/print of confirmation page
5. Paper mail
6. Recommended touchpoint w/ Claims Status Tool
7. Recommended touchpoint w/ MyVA 
8. Recommended touchpoint w/ MobileApp

Begin this after [Desk research on the current state of claim submission and post-submission experience#79177](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79177)

## Working documents

1. [Conceptual model - Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?wid=0-1714144026398)
2. [list of artifacts](https://docs.google.com/spreadsheets/d/1zjWxQ1uu9Qm504BMcaTKek4_RqQWfJodjTMpgNNr_NI/edit#gid=0)

## Tasks
- [X] ID model for for submission concept and naming
- [X] Map future-state journey for success path (channels within our control are clearly defined)
- [ ] Identify where altered touch points are happening and what we want to convey with design changes. (to be detailed in later issues in [Improve submission user experience#78179](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78179))
- [ ] Consult engineer to assess basic feasibility/raise early concerns with design changes. 

**Coordination with other teams that factor into redesign:**
- [X] [Veteran Facing Forms Team's submission status work](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170) - ensure we are consistent with what they're doing
 - [x] Claim Status Tool future work](https://dsva.slack.com/archives/C04KHCT3ZMY/p1711641878963709?thread_ts=1711641594.321239&cid=C04KHCT3ZMY) - en sure we are consistent with what they're doing.
 - [x] Team 2 to incorporate their work into the same journey map
 - [x] [Veteran Facing Forms Team's to clarify our own scope](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170) on changes to our confirmation pages - per [Slack](https://agilesix.slack.com/archives/C04MJV66ZPC/p1712950176309139?thread_ts=1712948394.643759&cid=C04MJV66ZPC)

## Acceptance criteria
- [x] Submission model/naming conventions are set
- [X]  Future-state journey map created for success path (channels within our control are clearly defined)
      - [ ]  Other channels (eg. CST, MyVA, Mobile app) are potentially addressed; if not, create a new ticket to track the 
               work continued into the future. 
- [ ]  Sync with engineer to flag concerns with design changes

**Comment by mengA6** [comment]
See [notes in Discovery Sub/Post Thinking doc (highlighted in pink)](https://docs.google.com/document/d/19H0ZQadc2iPJaK4qasgaLEdnTKbAfrFYH__VhbT_fl8/edit#heading=h.e5jw3at35sm9)

**Comment by evelynhilbrichdavis** [comment]
Create a separate ticket for an engineer to conduct technical discovery on the points of redesign.

**Comment by evelynhilbrichdavis** [comment]
Failure paths have been removed from this ticket and moved to a separate one.

**Comment by evelynhilbrichdavis** [comment]
VFF team is working with Authenticated Experience to set a timeline to include [a "pending" tag ](https://www.figma.com/file/GeBhUvcQAbbGYdmDIS7bRN/Confirmation-%26-Status?type=design&node-id=39-15291&mode=design) for submitted claims on MyVA. 
We will incorporate this new feature in our plans unless we hear that plans for implementation change.

**Comment by evelynhilbrichdavis** [comment]
New status "pending" would start in MyVA but eventually move to CST so status name/labels are used consistently across service.  This would happen on a longer timeline, so we will want an interim plan that uses CST as it is now. 
A claim appears in CST 1-2 business days after EP is established.
[Same slack thread as above. ](https://dsva.slack.com/archives/C06R2BZKT62/p1713885767699989?thread_ts=1713799162.855579&cid=C06R2BZKT62)

**Comment by evelynhilbrichdavis** [comment]
Moving "Sync with engineer" AC to 81523

Assumption: VFF updates to MyVA (and CST) will be implemented after we complete submission work. Our redesign will make sure the feature fits into our improvements, but they won't block us from doing the work. @mengA6
