### ISSUE TITLE
Explore adding labels automatically and add labels

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#79170]
## User Story
As a Governance team member needing to update the labels on historical tickets, I want to explore the possibility of writing a script to automate the process so that I don't have to update the labels manually.

As a Governance team member who has written a script for updating historical ticket labels, I want to execute said script so that all of the historical SR findings tickets have been updated with the appropriate standard and category label.

Assignee: @it-harrison 
Peer Reviewer: @erinrwhite 

## Description
In order to get Domo updated sooner with our new standards information, Governance team wants to update the labels on historical Staging Review findings tickets. The only labels we'd want to add to these tickets are the new standard labels and the new category labels. No additional descriptive tags will be added. No existing labels should be removed.

Within this ticket, we will research the possibility of writing a script that will update the labels on all of the historical tickets for us, so this does not have to be done manually. 

Once the script is written, we will also execute the script within the work of this ticket to ensure that all historical SR tickets have been updated with the new standard and category labels.

There may be a few examples of old standards that do not map nicely to the new standards and must be handled on a case by case basis. Please refer to the mapping document for reference.

Lastly, all SR tickets opened in CY24-Q1 should be updated with the new standard and category labels, as well as with the new descriptive tags. This may require the assignee to reach out to Governance team members for their input. There is no need to update the format of the SR tickets - we only need to focus on labels. For CY24-Q1 tickets, we can remove labels. The goal is to ensure that all SR tickets for CY24-Q1 follow the new process for Experience Standards 2.0.

## Impacted Artifacts
[VA.gov Experience Standards source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=2089466616) - for referencing standards and category labels
[Mapping spreadsheet](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=471245366) - contact @erinrwhite for more information on this doc

## Tasks
- [ ] TBD

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have successfully written and executed a script to add the new the standard and category labels to all historical SR findings tickets.
- [x] We have verified that all SR tickets created in CY24-Q1 follow the new labeling format for Experience Standards 2.0.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Per standup on 4/3, we will only update tickets from 1/1/2023 and forward. Anything older will not need to be updated with new standard and category labels.

**Comment by it-harrison** [comment]
@shiragoodman before I run my script to update the old SR tickets with the new labels I want to mention that this will break [this card](https://va-gov.domo.com/page/1340527018/kpis/details/1670417616) and [this card](https://va-gov.domo.com/page/1340527018/kpis/details/1368137964)

**Comment by it-harrison** [comment]
@erinrwhite historical tickets have been updated with new standard and category labels. I am in the process of verifying CY24 tickets follow the new labeling format for Experience Standards 2.0.

**Comment by shiragoodman** [comment]
Old ES https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+HTML+markup+isn%27t+valid will need to be manually mapped. Please create a mapping document in Confluence and get help from @briandeconinck on which tickets map to which new ES (only category and standard). FYI @it-harrison

**Comment by erinrwhite** [comment]
@it-harrison Spot-checking here and not seeing the new standard or category labels applied for:

- [Old standard 03.03](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue03.03+) should have labels `exp-std-flow-interruption` and `Efficiency`
- [Old standard 04.13](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue04.13+) should have labels `exp-std-design-consistency` and `consistency`
- [Old standard 05.04](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue05.04+) should have labels `exp-std-voice-tone` and `credibility`

Here's our spreadsheet [mapping old standard labels to new standard labels](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=628171129) and the accompanying categories are in a separate [source of truth doc](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009). Would it be helpful for me to pull together one working sheet that has old labels and new standard+category labels all in one?

**Comment by shiragoodman** [comment]
moving into next sprint due to comments above ^

**Comment by it-harrison** [comment]
@erinrwhite - all labels should be applied (the script had not applied them to closed tickets the first iteration).

**Comment by it-harrison** [comment]
@briandeconinck - just a reminder on getting your feedback on this [mapping document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3074720013/Map+for+CY+2023+Markup+is+Invalid+09.01+tickets)

**Comment by briandeconinck** [comment]
@it-harrison Working on that this afternoon, thank you for the nudge!

**Comment by briandeconinck** [comment]
@it-harrison I've completed the mapping document

**Comment by erinrwhite** [comment]
@it-harrison Reviewing these labels - it's looking good for the most part! A few lingering to-dos here.

## Mis-applied labels
Checking against our [mapping spreadsheet](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=628171129):
- [Old standard 05.04](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue05.04+) should have category `credibility` instead of `comprehension`; standard OK
- [Old standard 11.08](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aclosed+label%3ACCIssue11.08) should have category `findability` instead of `usability`; standard OK
- [Old standard 05.01](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aclosed+label%3ACCIssue05.01) should have standard `exp-std-content-practices` instead of `exp-std-unexpected-interaction`; category OK
- [Old standard 02.06](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aclosed+label%3ACCIssue02.06) should have standard `exp-std-content-practices` instead of `exp-std-unexpected-interaction`; category OK
- [Old standard 05.05](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aclosed+label%3ACCIssue05.05) should have standard `exp-std-content-practices` instead of `exp-std-unexpected-interaction`; category OK

## We said we'd need to change these on a per-ticket basis
The issues for [09.01 have been mapped](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3074720013/Map+for+CY+2023+Markup+is+Invalid+09.01+tickets) by @briandeconinck. 

These standards remain:
- [old standard 11.16](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue11.16) needs category and experience standard labels
- [old standard 04.09](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue04.09) needs category and experience standard labels
- [old standard 02.04](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aclosed+label%3ACCIssue02.04) needs category and experience standard labels

@shiragoodman should we still plan to map the other standards by hand? I think most of them are in @briandeconinck's court - or was this another ticket in the initiative? 

## Need to select experience standard and category for these
These are standards we had no findings for as of last summer...but have since used!

- [old standard 04.06](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aclosed+label%3ACCIssue04.06) needs category and experience standard labels
  - Was: "Form labels aren’t positioned near the form input."
  - Erin's recommendation: "User doesn't have enough information to complete a task."  `exp-std-task-completion` `Comprehension`
- [old standard 04.11](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue04.11) needs category and experience standard labels
  - Was: "Components with the same functionality within a set of Web pages aren't consistent."
  - Erin's recommendation: "User encounters design components that are inconsistent or confusing. `exp-std-design-consistency` `Consistency`

**Comment by shiragoodman** [comment]
IIRC, most of the 00.00 issue tickets are created by Brian - and those are the ones I was referring to when I said they're on a case by case basis, and it might just make sense to do it manually. @briandeconinck FYI

**Comment by briandeconinck** [comment]
For the ones that I got tagged in on...
- [old standard 11.16](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue11.16) should be `exp-std-element-perception` `Comprehension`
- [old standard 04.09](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3ACCIssue04.09):
   - #43141 should be `exp-std-element-perception` `Comprehension`
   - Other tickets are older than 1/2023
- [old standard 02.04](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+is%3Aclosed+label%3ACCIssue02.04) should be `exp-std-flow-steps` `Findability`

All of the 00.00s are going to take me a bit longer to sort through...

**Comment by briandeconinck** [comment]
Okay, let's do this. For the [00.00 issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues?page=1&q=is%3Aissue+label%3ACCIssue00.00):

```
- #73994 `exp-std-flow-steps` `Findability`
- #73993 `exp-std-task-completion` `Comprehension`
- #73992 `exp-std-flow-steps` `Findability`
- #73990 `exp-std-form-integrity` `Credibility`
- #73579 `exp-std-content-va` `Consistency`
- #72161 `exp-std-task-completion` `Comprehension`
- #72160 `exp-std-element-perception` `Comprehension`
- #71480 `exp-std-task-completion` `Comprehension`
- #71223 `exp-std-flow-steps` `Findability`
- #70908 `exp-std-task-completion` `Comprehension`
- #70201 `exp-std-task-completion` `Comprehension`
- #70200 `exp-std-task-completion` `Comprehension`
- #70199 `exp-std-task-completion` `Comprehension`
- #70198 `exp-std-task-completion` `Comprehension`
- #67453 `exp-std-element-perception` `Comprehension`
- #67073 `exp-std-flow-steps` `Findability`
- #67070 -- one of the rare ones that's not mine!
- #66642 `exp-std-task-focus` `Efficiency`
- #66308 `exp-std-task-focus` `Efficiency`
- #66072 `exp-std-task-focus` `Efficiency`
- #64851 `exp-std-content-va` `Consistency`
- #64850 `exp-std-content-va` `Consistency`
- #64848 `exp-std-content-va` `Consistency`
- #64846 `exp-std-flow-completion` `Usability`
- #64843 `exp-std-element-comprehension` `Usability`
- #64835 `exp-std-task-focus` `Efficiency`
- #64785 `exp-std-element-comprehension` `Usability`
- #64782 `exp-std-task-completion` `Comprehension`
- #64657 `exp-std-task-completion` `Comprehension`
- #63680 `exp-std-form-integrity` `Credibility`
- #63470 `exp-std-safety` `Health and Safety`
- #63095 `exp-std-task-focus` `Efficiency`
- #61757 `exp-std-content-va` `Consistency`
- #61160 `exp-std-element-comprehension` `Usability`
- #61159 `exp-std-unexpected-interaction` `Usability`
- #61157 `exp-std-unexpected-interaction` `Usability`
- #60378 `exp-std-task-focus` `Efficiency`
- #60037` `exp-std-form-integrity` `Credibility`
- #60036 `exp-std-task-completion` `Comprehension`
- #59499 `exp-std-unexpected-interaction` `Usability`
- #59498 `exp-std-design-consistency` `Consistency`
- #59264 `exp-std-unexpected-interaction` `Usability`
- #59263 `exp-std-form-integrity` `Credibility`
- #56082 `exp-std-form-integrity` `Credibility`
- #56081 `exp-std-unexpected-interaction` `Usability`
- #56080 `exp-std-task-completion` `Comprehension`
- #55864 `exp-std-task-focus` `Efficiency`
- #55863 `exp-std-element-perception` `Comprehension`
- #55699 `exp-std-task-completion` `Comprehension`
- #55276 `exp-std-task-focus` `Efficiency`
- #55275 `exp-std-content-va` `Consistency`
- #54881 `exp-std-unexpected-interaction` `Usability`
- #54711 `exp-std-design-consistency` `Consistency`
- #54710 -- Not mine!
- #54709 `exp-std-unexpected-interaction` `Usability`
- #54708 `exp-std-repetition` `Efficiency`
- #54707 `exp-std-task-focus` `Efficiency`
- #54483 `exp-std-unexpected-interaction` `Usability`
- #54303 -- Not mine!
```

And I think that's everything since 1/1/2023! Three that aren't mine, everything else filed.

**Comment by briandeconinck** [comment]
I'm now re-reading @shiragoodman's comment that those might make sense to do manually. If it's possible for @it-harrison to magically apply those labels for me by script that would be great, otherwise I'll work on adding those labels by hand tomorrow.

**Comment by it-harrison** [comment]
@briandeconinck - thank you for your heroic effort on this! I can add the labels tomorrow.

**Comment by shiragoodman** [comment]
@shiragoodman emphasized _heroic_.

thank you @briandeconinck !I know this is tedious work. we appreciate you!

**Comment by erinrwhite** [comment]
WOW @briandeconinck @it-harrison big alley-oop! go team!

**Comment by it-harrison** [comment]
@shiragoodman @erinrwhite all labels have been applied except for the three `00.00`s that are not Brian's:
* 67070
* 54710
* 54303

**Comment by shiragoodman** [comment]
@erinrwhite @rferguson13 please take a look at the 3 above and manually add the appropriate category and standard label.

**Comment by rferguson13** [comment]
@shiragoodman - Should be good to go on [54303](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54303)

**Comment by erinrwhite** [comment]
All set with these last two! [67070](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6707) and [54710](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54710)

**Comment by erinrwhite** [comment]
@it-harrison just a few that didn't make it through - I got them updated by hand:

- 55699 `exp-std-task-completion` `Comprehension`
- 54708 `exp-std-repetition` `Efficiency`

Not on Brian's list but still needed to be updated:
- 52215: `exp-std-findability` `Findability`
- 52091: `exp-std-flow-steps` `Findability`

Should be all set to close!!
