### ISSUE TITLE
[Bug] Update the accept prop on the VaFileInput for the CST 

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#79174]
### Bug
**Steps to reproduce**

1. Go to the files tab on the CST
2. Make sure the toggle `cst_use_claim_details_v2 ` is enabled
3. Add a file that is not a pdf (EX: .txt or .jpg)
4. You'll get the error `This is not a valid file type`

![Screenshot 2024-03-25 at 11 34 47 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/77f22d82-f335-4075-a291-435d4d8ecb57)

**What is the bug?**
Found when updating the component from v1 to v3 that the the v1 version allows the `accept` prop  to have a list of file types with spaces `EX: accept=".pdf, .gif, .jpeg, .jpg, .bmp, .txt" ` while the V3 component does not allow this and will give the error `This is not a valid file type`  when you upload anything other than a .pdf . To fix you have to change the list to not include spaces `EX: accept=".pdf,.gif,.jpeg,.jpg,.bmp,.txt"`

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The File Uploader on the files tab accepts .jpg

**Comment by HeatherWidmont** [comment]
Cypress tests are failing, moving to blocked until Support Platform fixes it

**Comment by pmclaren19** [comment]
@jacobworrell validated in staging with the jpg you provided me and I was able to upload!
