### ISSUE TITLE
Submission experience: Discovery and Design Approach

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#79176]
## High Level User Story
As a UX team member, I need to access relevant existing knowledge about submission so I can outline a design approach that would create a better experience for Veterans. 

## Reference
see the containing epic

## Goals

1. Understand the Veteran submission experience currently. This includes other channels beyond the 526 such as email (VA Notify), MyVA, paper mail, etc. 
2. Diagram the backend processes of submission
3. Design approach to improving the experience at a high level so we can move on to detailed design

## Working documents

see the containing epic

## Definition of Done
 - [X] Desk research to understand current state of submission experience
 - [X] Connected with other teams doing similar work (Veteran-Facing Forms, CST, MyVA)
 - [X] High-level design of success path / conceptual model ready for detailed design work
