### ISSUE TITLE
Design | Account security | Rethink account set-up section

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#79182]
## Background

When we worked on #74053, Laura (CAIA) and Liz identified some concerns about how we're handling the account setup piece of the account security page. 

- The process list is wrong and misleading, since an ID.me user could set up MFA without verifying their identity.
- Laura let us know the rest of the site is adopting a strategy of not talking about MFA as a separate thing at all, and instead encouraging people to verify their accounts (which includes MFA as part of the process).
- Setting up MFA is not a separate step for login.gov; it's actually required for an LOA1 account.

These points and the following convos we had raised a few questions about the account security page. The answers to these questions should probably be driven by product:

1. Do we need to talk about MFA at all on the account security page for LOA1 users, if what we really want is for people to verify their accounts?
2. Is the confirmation for LOA3 users that they have completed the 2 steps a relic of time when account security was less mature? If so, do we still need to show LOA3 people this confirmation?
3. If we don’t need to talk about MFA, or show a confirmation of completed steps, do we need the account setup section at all?

If we decide we do still need the account setup section, we'll need to rethink aspects of the design (this can go into a separate ticket for design):
- For LOA1 users, we have two "verify your identity" CTAs going to the exact same place. Necessary?
- The process list is misleading, and we need to consider a different way to present this information, that we haven't already tried in a [previous iteration](https://www.figma.com/file/takD53OoltCjdlmGBwK3DH/Sketch-Archive---Authenticated-Experience?type=design&node-id=58-6&mode=design&t=0Wh6jP1x7NsKEYuP-11).

## Tasks

- [ ] Determine whether or not we need to show a confirmation of completed steps for LOA3 accounts
- [ ] Determine whether or not we need to talk about MFA on the page, and if so, under which conditions?
- [ ] Create a design ticket to update Figma files accordingly

## Acceptance criteria

- [ ] We've made decisions on the above and are ready to update designs.

**Comment by andaleliz** [comment]
Hey @mtcA6 I wrote up this ticket, and as I was doing so, it felt more like a product driven ticket vs a UX driven ticket. If you disagree, I can own this but otherwise I'm happy to weigh in and share opinions/pros/cons as needed.

**Comment by mtcA6** [comment]
@andaleliz thinking about this, I actually feel like the next step would be some sort of market research to see what things other account security pages do and if we could or should replicate those things to feed into whatever product decisions we make next. 

for now this can hang out in the backlog, but I'm going to check in w/Samara next week because the identity team might actually have something on their roadmap that could feed into what we do on this page.
