### ISSUE TITLE
Edit Ticket: Successful Screener Questions Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79194]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Successful Screener Questions](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions) contains links to Google Docs. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

Discovery Ticket: 
[78533](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78533)
---
## Tasks
- [x] [Read latest comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79194#issuecomment-2224061072) 
- [x] Update page according to guidance by SME (**Naomi Marcussen**) found in comments section
- [x] Review updated page with SME
- [x] Move page into deployment space
- [x] Check for LBs

## Acceptance Criteria
- [x] Page is ready for deployment

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
unable to complete due to being blocked by SME, moving to Backlog

**Comment by jknipes** [comment]
Per Naomi Marcussen, we are waiting on OCTO determining a space for these documents to live in Sharepoint

**Comment by jknipes** [comment]
Sprint assignment was added by automation. Removing date and keeping in Backlog pending decision by OCTO.

**Comment by jknipes** [comment]
Issue is currently _blocked_, waiting on OCTO determining a space for these documents to live in Sharepoint

**Comment by jknipes** [comment]
waiting on OCTO determining a space for these documents to live in Sharepoint

**Comment by jknipes** [comment]
@naomimarcussen mentioned recommend that instead of the links that say _**via this Google doc**_, we instruct users to submit a ticket (from the footer link) that goes to Platform Conent team and Robyn Singleton. Robyn can assess whether we should publish it as a recommended screener question or not

**Comment by jknipes** [comment]
Closing ticket as _Done_
