### ISSUE TITLE
Edit Ticket: Getting Started With Platform Analytics Insights

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79199]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Getting Started With Platform Analytics Insights ](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights)contains links to Google Slides. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

## Discovery Ticket
[78547](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78547)
---
## Tasks
- [x] Update page according to guidance by SME
- [x] Move page into deployment space
- [x] Check for LBs

## Acceptance Criteria
- [x] Page is ready for deployment

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)

**Comment by jknipes** [comment]
Work completed, moving to _done_
