### ISSUE TITLE
Decrease the Sentry RDS Storage

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79198]
## Issue Description
After the Sentry spike issue has been solved [with the Identity and Mobile teams?] the RDS storage can be decreased. This was increased due to the extreme storage required because of the issues (up to 6mm according to[ this Slack thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1711134858385029)) that are taking up space. 

---
## Tasks
- [ ] Investigate the Sentry Spike Issue by assessing the current storage in Sentry (see [this](https://vagov.ddog-gov.com/dashboard/w2n-vq9-v75/rds-sentry-freetotalused-storage-space?fromUser=false&fullscreen_end_ts=1723488297115&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1722883497115&fullscreen_widget=793808805161500&refresh_mode=sliding&view=spans&from_ts=1722883487167&to_ts=1723488287167&live=true) dashboard)
- [ ] Compare filtered to actual storage usage (volume)
- [ ] Decrease RDS storage
- [ ] Test as required
- [ ] Adjust monitors as necessary, once the findings between past and current storage usage has been established. 

## Acceptance Criteria
- [ ] Comparison of the past and current storage volumes to determine if the RDS needs to be decreased. 
- [ ]

**Comment by jennb33** [comment]
8/28 update: duplicating this ticket into [91712](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91712), due to DataDog access errors by @Kshitiz-devops.
