### ISSUE TITLE
[Research] Set up test in OptimalWorkshop 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79195]
## Tasks

- [x] Identify which type of test to set up in Optimal Workshop
- [x] Set up test in OptimalWorkshop 
- [x] Share preview of test for validation 
- [x] Add to research plan 

## AC

- [x] Test is available in OptimalWorkshop
- [x] Preview of test is validated by PO/DM, OCTO, UX
- [x] Added to research plan

**Comment by benbrasso-agile6** [comment]
@cgednalske If you can, why don't you try to get at least one of the tasks (?) set up in Optimal Workshop. Like, at least a space so I can see where we're working. And, I can finish this task. Just assign it to me when you're done doing what you can. TY

**Comment by cgednalske** [comment]
The survey has been set up in Optimal Workshop, with links added to the research plan. Here's a [preview link](https://dj540s05.optimalworkshop.com/questions/g) for the study. 

A remaining thing to check is if the separate study links successfully generated (which I don't think they did) and solidify those + make sure they're correct in the research plan. @benbrasso-agile6 will take over from here.

**Comment by benbrasso-agile6** [comment]
@cgednalske a [slack thread](https://dsva.slack.com/archives/C0216PL32HJ/p1712859409887009) in research ops about separate links for cohorts. Based on Brian's response, I don't believe we need them for this study. We'll have the participant IDs if we want to do cross-cohort answer comparisons.

**Comment by benbrasso-agile6** [comment]
[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-04%20Unmoderated%20Content%20Evaluation%20for%20Multiple%20Facilities%20Selection%20in%20BT%20Oracle%20Health%20App/research-plan.md)

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2024-04%20Unmoderated%20Content%20Evaluation%20for%20Multiple%20Facilities%20Selection%20in%20BT%20Oracle%20Health%20App/research-outline.md)

[Survey preview link](https://dj540s05.optimalworkshop.com/questions/facilities-selection-bt-oh)
