### ISSUE TITLE
[Research] Create Conversation Guide

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79209]
## Tasks
- [ ] Create the conversation guide for testing with users for unmoderated research 
- [ ] Add conversation guide into GitHub

## Acceptance Criteria
- [ ] Review conversation guide with team
- [ ] Post finalized conversation guide to GitHub folder
