### ISSUE TITLE
Implement Process for Alerting Teams to Outdated Pages in Content Slack Channel

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79204]
### Description
Teams using Confluence need to know about the oldest pages in their respective spaces on Platform Website, those in most need of an update. 
[Keep It Up To Date](https://vfs.atlassian.net/wiki/marketplace/discover/app/keep-it-up-to-date?requestDialogOpen=true&source=mpac) application has been identified as a simple tool, free of charge, for this purpose. 
Platform Content Team needs a process for alerting teams to these pages on a regular cadence via the Platform Content Channel in Slack.

### Tasks
- [X]  Create Draft Page for Teams in Confluence
- [x]  Format per PCT feedback
- [x]  Announce finished page in Team of Teams
- [x]  Demo finished page at End of Sprint Demo

### Acceptance Criteria
- [x]  First Announcement on #platform-team Slack channel scheduled for Monday following Demo
- [x]  Create Monthly/Sprint-wise Support ticket for posting link to Confluence Page 

## Relevant Links:
Slack Channel Link: [#platform-content](https://dsva.slack.com/archives/CL181NRJQ)
(Draft) Page on Confluence: [HERE](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3061743626/DRAFT+Keep+It+Up+To+Date+-+6+Spaces+on+Platform+Website)

**Comment by jknipes** [comment]
Work finished, ticket [81495](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81495) created. Moving to _Done_

**Comment by jknipes** [comment]
Work finished, ticket [81495](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81495) created. Moving to _Done_
