### ISSUE TITLE
Joe: Discovery - Identify Options for Date & Time Stamp on All Pages

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79203]
## Issue Description
In response to many requests from VFS Teams, Platform Teams and Leadership, identify affordable and easy-to-implement options for including a date and time stamp on all Platform Website pages.

---
## Tasks
- [x] 3 Options Identified
- [x] Review Options with Team
- [x] Review Options with Erika Washburn

## Acceptance Criteria
- [x] Solution has been identified for implementing this feature or Further Discovery Needed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Four options investigated:

1. [Keep It Up To Date App](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3051585551/DRAFT+Testing+Available+Tools+for+Date+Stamping#Keep-It-Up-To-Date-App%3A) - free download. works internally on Confluence. Can be configured to display top pages in the (6) deployment spaces older than (x) number of days. **_Does not render on Platform Website (PW_)**. Best used as a tool for alerting teams to update their content on PW. Maybe send out a Slack notice to specific channels on monthly cadence.
2. [Recently Updated Dashboard](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3051585551/DRAFT+Testing+Available+Tools+for+Date+Stamping#Testing-Recent-Updates-Dashboard%3A) (Confluence Element) - displays a custom list of recently updated content. _**Does render on PW**_. Could be used in top "expand" in each of the 6 spaces, or on future landing page.
3. Date Stamp - [Add A Date Using A Calendar](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3051585551/DRAFT+Testing+Available+Tools+for+Date+Stamping#Testing-Date-Stamp%3A) (Confluence Element). _**Does render on PW**_. This may be the best and easiest solution. This would require page authors to write "Last updated" and insert the date stamp manually each time a page is updated. Similarly, Platform Content Team can add missing date stamps to pages prior to daily deployment.

**Comment by jknipes** [comment]
Recently Updated Dashboard (Confluence app) will need to have links pointing to pages on PW, not Confluence. In each of the 6 spaces in PW, only a few pages receive updates in the course of a week. Therefore, it is believed we can choose 1 day per week to update the Recently Updated Dashboards (6) on PW.
However, links in the Dashboard **must link to pages on PW**, not Confluence.

**Comment by jknipes** [comment]
k15t is unable to verify whether **Handy Timestamp** will publish on PW via Scroll Viewport. 
Additionally, it is this PM's opinion that this is difficult to read at a glance in comparison to the Add A Date Using A Calendar element: 
<img width="515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0V5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc15e9f5c93d5ebbd3e41cfb3b9f385c5c193c84/Screenshot%202024-04-03%20at%2010.00.24%E2%80%AFPM.png" alt="Screenshot 2024-04-03 at 10.00.24 PM.png" />
