### ISSUE TITLE
Create Oracle Health patient eligibility feature flag

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#79217]
## Issue Description
Create a VA online scheduling (vaos) backend feature flag for toggling patient eligibility requests to route to VetsApi Patient Gateway (VPG) in support of Oracle Health appointment scheduling.
[Feature flag documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide)

---
## Tasks
- [x] Create backend feature flag - va_online_scheduling_enable_OH_eligibility

## Acceptance Criteria
- [x] Feature flag has been deployed to Staging environment
- [x] Feature flag is visible in Flipper on Staging (https://staging-api.va.gov/flipper/features)
