### ISSUE TITLE
[CHIP] Update AWS lambdas from node 14

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#79211]
## Summary
All of our CHIP lambda functions are in node 14, which is past EOL. AWS lambda has dropped support for it already. We need to update and test all functions.

Ref: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy

## Tasks
- [x] Update to a newer version of node
- [x] Test lambda functions on dev/stage
- [x] Release to prod
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [x] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/79211?planning-poker) with Zenhub @lee-delarm6 @wullaski

**Comment by brianseek** [comment]
This is released to prod, will let this ticket hang out here in validate for a few hours while I monitor things

**Comment by brianseek** [comment]
this is all looking good. Closing ticket
