### ISSUE TITLE
DR | [spike] Adding Lighthouse downtime service 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#79233]
## Value Statement
**_As a_**  developer that uses Lighthouse's APIs
**_I want to_** use be able to add Lighthouse as a downtime dependency
**_So that_** Veteran's are notified of the outage and prevented from using an app or form during maintenance

## Background Context

Lighthouse uses [StatusPage](https://valighthouse.statuspage.io/) for sharing API status and maintenance, but the VA has PagerDuty integrated into the platform maintenance banner and save-in-progress components. After starting a discussion in [platform support](https://dsva.slack.com/archives/CBU0KDSB1/p1711376507980269), we were unable to determine who would be responsible for adding this functionality. This may not be fully understood, but maybe the following items need to be added:

- Add all of [Lighthouse APIs](https://valighthouse.statuspage.io/) separately (currently 25) as an [external service](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/monitoring/DowntimeNotification/config/externalServices.js)
- Update vets-api (not sure where?)
- Update devops:
  - Maybe update [forward proxy config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-prod.yml)?
  - Maybe update [maintenance window variables](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/maintenance-window/vars/main.yml)?
- Maybe more?

## Tasks
- [ ] Determine where the new services are added
- [ ] Determine who owns the code, and who will add it
- [ ] Add Lighthouse services (all 25)
- [ ] Add tests
- [ ] Manually test
- [ ] Add downtime support to forms & apps that use Lighthouse services

## Acceptance Criteria
- [ ] New downtime services tested in staging
- [ ] Downtime services added to forms & apps

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by anniebtran** [comment]
This might be a duplicate of #78441

**Comment by saderagsdale** [comment]
@saderagsdale talk to Cory and find out who may know more.

**Comment by Mottie** [comment]
These are the instructions that we need to follow - [add a new service](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-AddinganewPagerDutyservice) - I have a pager duty account. Maybe I can work together with either Annie or Derek and get this set up.

**Comment by saderagsdale** [comment]
@Mottie will add a screenshot of the UI for @eileen-coforma to review.

**Comment by saderagsdale** [comment]
- Will have to work with Shaun on this. Lighthouse already has a status page app that is separate from VA Pager Duty. Will need to use data from the status page.

**Comment by anniebtran** [comment]
Might need API keys

**Comment by shaunburdick** [comment]
Created a request ticket for PagerDuty API Access: 
- #85987

**Comment by shaunburdick** [comment]
Made some good progress integrating with Status Page v2 API.
Continuing forward but there may be an issue with how large some of the windows are. I'm noticing they are nearly an entire day. Hopefully that get's paired down as the actual work get closer but that may put a hitch in the plan as we would be blocking submissions for whole days almost weekly:
```json
      "scheduled_for": "2024-06-17T20:00:00.000-04:00",
      "scheduled_until": "2024-06-17T21:00:00.000-04:00"
```
