### ISSUE TITLE
BE | EDU CH33 Changes | Include control info in update request

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#79249]
When a PUT (update) request is sent to Lighthouse's Direct Deposit Management API from VA.gov, we want to track whether the direct deposit information sent is related to comp and pen, or education benefits.  The email notification should state the appropriate benefits type as well.

In order to do this, control information must be included in the request.  Data will be posted similar to this:

```
{
  "control_information": {
    "can_update_direct_deposit": true,
    "is_edu_claim_available": true,
    "is_corp_available": true,
    "is_corp_rec_found": true,
    "has_no_bdn_payments": true,
    "has_identity": true,
    "has_index": true,
    "is_competent": true,
    "has_mailing_address": true,
    "has_no_fiduciary_assigned": true,
    "is_not_decease": true,
    "has_payment_address": true
  },
  "payment_account": {
    "name": "...",
    "account_type": "...",
    "account_number": "...",
    "routing_number": "..."
  }
}
```

## Tasks

- [x] Create a new direct deposit endpoint to accept control information parameters.
- [x] Hook in logic that determines if the account is related to C&P, EDU, BOTH, or NONE.

*Note: If the NONE shows up in the logs, this is cause for concern.*

## Acceptance Criteria

- [x] Add specs to test new behavior.

Staging tests:
- [x] Ensure updates work correctly.
