### ISSUE TITLE
BE | EDU CH33 Changes | Add Control Info Logic

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#79248]
## Background

When a request is sent to Lighthouse's Direct Deposit Management API from VA.gov, we want to track whether the direct deposit information returned is related to comp and pen, or education benefits.

## Tasks

- [x] Verify control info logic with Lighthouse.
- [x] Add logic that analyses the control information and determines whether it relates to C&P, EDU, BOTH, or NONE.

## Acceptance Criteria

- [x] Specs written for control information check.
