### ISSUE TITLE
[CDP] VHA- Expand "Pay online" component and add account number - Part 1

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#79257]
## Description

Given: A veteran wants to see their account number when being directed to pay.gov easily. Instructions for paying online should not be hidden. 
When: This is true when the account number is attached to the user and not to a singular debt.
Then: A veteran should be able to see their account number on the copay summary page and not just the copay detail page.

Guidance from Design System: [https://design.va.gov/components/accordion](https://design.va.gov/components/accordion)
**[Additional reasons to consider something else](https://design.va.gov/components/accordion#additional-reasons-to-consider-something-else)
Required content: If the majority of people need the content to accomplish the main task then it should not be hidden from view.**

This is part 1 of the work, once it's complete, then part 2 #79964 will be ready to be worked on. 

## Tasks
- [x] Expand "Pay online" accordion
- [x] Add Account number to all instances of "Pay online" component

**Current Copay Summary page:** 
<img width="751" alt="Screenshot 2024-03-26 at 11 29 55 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/183af115-056b-47f1-90e3-47d9d1fdfeb4">

**Current Copay Detail page:**

<img width="750" alt="Screenshot 2024-03-26 at 11 29 45 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/a6bb286a-6539-4354-bd10-12c30282f1e4">

## Acceptance criteria

- [x] Discuss Design System feasibility (should "Pay online" be in a accordion?)
- [x] Make updates where "Pay online" section exists on VHA side of Debt Portal
- [ ] Make small pull request for these updates once PO signs off on them

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@mgleo a tiny solution we can implement now is adding this prop `open="true"` to the **Pay online** item as the default for when the page loads, that way, the **Account number** will be visible as the user scrolls down.

**Comment by mgleo** [comment]
@josephrlee The account number doesn't appear on all pages right now so that could be updated as well since @denisecoveyduc has confirmed that the account number is attached to the user and not the bill. 

Logged in pages that do not show account number but link to pay.gov:
https://staging.va.gov/manage-va-debt/?postLogin=true
https://staging.va.gov/manage-va-debt/summary/copay-balances

**Comment by mgleo** [comment]
USWDS Accordion Guidance: 
https://designsystem.digital.gov/components/accordion/

**Comment by josephrlee** [comment]
@denisecoveyduc 

Here are screenshots of the proposed changes, if these look good, I can go ahead and implement them! 

Here's a summary of the changes I've made in addition to adding the account number and having the pay online accordion be open by default:

1. For the **Copay balances summary**, I added the account number
2. For the **HTML Statement page**, I added the other repeating content blocks (How to pay, how to get help, how to dispute) that are currently on the detail page.
 

| | Current | Proposed |
| -------- | -------- | ------- |
| **Copay balances summary pages** | ![Copay balances summary page before](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/460712d4-f9d7-443e-b794-0422eaea3679) | ![Copay balances summary page after](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/75706dc8-6ad4-4149-8f78-4a7e9d444399) |
| **Copay detail page** | <img width="750" alt="Copay-Detail-Before" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/baf07b96-0c82-4ce1-94af-8818eadb76d6"> | <img width="750" alt="Copay Detail After" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/36cb3e84-3c3f-4c1b-a537-d7bb1abadf5a"> |
| **Copay HTML statement page** | ![Copay HTML statement page before](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/66d873ea-34f2-4c73-9194-9a32f6494eba) | ![Copay HTML statement page after](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/3397a454-123b-41eb-b088-dfc3f35021af) |

**Comment by denisecoveyduc** [comment]
Hi @josephrlee The side by side comparison is most helpful thank you for taking the time to provide visuals. Looks great to me.  Can you confirm for me, did we hear from Veterans that they wanted to see this information on the Copay HTML Statement Page? It wasn't there before.

**Comment by josephrlee** [comment]
@denisecoveyduc Thank you!

**re: copay html statement page:** We did get feedback multiple times that veterans are having a hard time finding their account number from Medialla, but not specifically from this page.

**Comment by josephrlee** [comment]
I also made a subtle copy tweak for readability on the **Pay Online** accordion depending on if it's the copay balances summary or detail/statement page.
```
      <p>
          You will need to provide your account number to pay{' '}
          {isOverview ? 'the' : 'this'} debt online.
        </p>
```
**Summary page:** You will need to provide your account number to pay **the** debt online.
**Detail/statement page:** You will need to provide your account number to pay **this** debt online.
