### ISSUE TITLE
BE | Profile | Direct Deposit | Update logging for exceptions

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#79256]
## Background
We detected C&P direct deposit logging issues related to a Faraday gem update.

The postmortem that provides more detail can be [found here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2024/2024-03-22%20-%20Profile%20-%20CnP%20DD%20Logging%20Issue.md).

## Tasks
- [x] Update logging so that only the response `status`, and `body` are included.
- [x] Review changes with code owners.

## Acceptance Criteria
- [x] Verify the logs in staging.
- [x] Update postmortem
