### ISSUE TITLE
BE | EDU CH33 Changes | Log direct deposit control information

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#79250]
## Summary

When a request is sent to Lighthouse's Direct Deposit Management API from VA.gov, we want to track whether the direct deposit information sent is related to comp and pen, education benefits, both, or none.

## Tasks

Log the following for GET requests:
  - [x] Benefit Type (C&P, EDU, Both, None)
Log the following for PUT requests:
  - [x] Benefit Type (C&P, EDU, Both, None)

*Note: If the NONE shows up in the logs, this is cause for concern.*

## Acceptance Criteria

- [ ] Verify the above logs/metrics are being sent to Datadog in staging.
- [ ] Verify the above logs/metrics are being sent to Datadog in production.

**Comment by tpharrison** [comment]
When reviewing the new logs in Datadog staging, I'm seeing unexpected data being logged.  PII  is not an issue since it's being filtered out, but what I'm seeing doesn't align with what I was expecting to see.  I reviewed this another BE engineer and we weren't able to determine what is causing this.  

Adrian Rollett should be able to help with this.  He is OOO so I'll reach out to him Monday morning.  Until then, this ticket and

**Comment by tpharrison** [comment]
Scheduled a meeting Adrian on 4/30 @2:45 ET.
