### ISSUE TITLE
[FSR] Final cleanup and check for unused components

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#79271]
## Description
To wrap up the cleanup, let's go through and check for any orphaned components and pages that may have been left after removing the old FSR pages. Codeclimate may be helpful while running through this ticket! 

## Tasks
- [x] Check for unused components (`especially` in the shared folder)
- [x] Remove unused components
- [x] Check for unused pages (`/pages/index.js` and in `pages` folder in general)
- [x] Remove any unused pages

## Acceptance criteria

- [x] No unused pages/components/clutter left floating in the FSR after the cleanup
- [x] Form functionality is unaffected

## Testing
- [x] Do all the testing
- [x] But also confirm e2e tests are passing and there's no old flakey ones being skipped
- [x] Confirm unit tests are passing and happy

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Hiccups with the other ticketed work in this sprint caused us to be unable to get to this one during the targeted sprint.

**Comment by Dr-Pongo** [comment]
Pulling into sprint 123 since we wrapped up a bunch of other work! This will likely not be completed within the sprint and will roll into 124!

**Comment by Dr-Pongo** [comment]
Rolling into sprint 124 because it came in late!

**Comment by Dr-Pongo** [comment]
[Running into CI issues for unrelated tests ](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/8904166597/job/24453612328?pr=29474) :( Moving to blocked until problem is resolved

**Comment by Dr-Pongo** [comment]
CI is finally happy and the PR has been merged!
