### ISSUE TITLE
[Sitewide] Ensure all CST resources are up to date with v2 designs

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#79270]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to navigate VA.gov and see consistent information about claims and the Claim Status Tool across the entire site
**_So that_** it's clear to me what to expect from claims and the Claim Status Tool UI 

---
## Background Context

The page `Resources and support` > `How to check your VA claim, appeal, or decision review status online` explains how to check on claims in CST. It currently uses screenshots from the current UI to explain the user journey. 

https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/

When we roll out V2 updates, we need to ensure that we update those pages to be consistent with the new user experience. 

### New Feature
- Why are we doing this work?
- Epic Link

## Design

Current page that needs to be updated
<img width="522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73e89aa59f279141c5c6ea83018259b2c4e6c5d1/Screenshot%202024-03-26%20at%201.06.12%E2%80%AFPM.png" alt="Screenshot 2024-03-26 at 1.06.12 PM.png" />

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Update content on this page to ensure it matches new V2 experience_
- [ ] _Update images on this page to ensure they match new V2 experience_
- [ ] _Update any other content in the `Resources and support` section of VA.gov (or elsewhere on site) that needs to be updated match new V2 interface. Preliminary list of pages that need to be checked for content can be found [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697490182408/80d09fbace925f5b50a50232f66e90f773d68d00?wid=74-1697490261656&sender=u80fb5a3b8f7951f35d701197).

## Definition of Done
- [ ] All content related to CST across VA.gov has been checked and updated as necessary to ensure our references to (both in content and imagery) is consistent with the updated experience.

**Comment by skylerschain** [comment]
We should do this once Claim Phases has launched so that we can update all assets at once to the most up-to-date versions.

**Comment by pmclaren19** [comment]
@jacobworrell @skylerschain this is not a page that our team currently owns, this would be something that Sitewide would need to work.
