### ISSUE TITLE
Toxic Exposure - Add TE fields to Form526 vets JSON schema - Spike

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#79278]
## Issue Description
Add TE fields to Form526 validation (vets JSON schema) schema
Scope of this ticket - Add fields for "Add Conditions" and Gulf war 1990 

Current state - FE and BE use JSONSchema to validate
New state - FE needs to point to patterns to validate to decouple the JSON schema from FE changes
FE will need to make sure that the patterns match the JSON schema 

---
## Tasks
- [ ] Agree on the contract between FE and BE for schema validation - for ALL TE fields
- [ ] Add ALL TE fields to JSON schema (
- [ ] Verify that FE and BE validation schema matches

## Acceptance Criteria
- [ ] Add TE fields to JSON schema for "Add Conditions" and Gulf war 1990 (4/10: add ALL JSON fields to schema, where possible)
- [ ] ~~Ensure TE fields are represented in the form json column for form 526 submission record~~
- [x] Document on wiki all TE JSON fields, regardless of implementation in vets-json-schema (CONTRACT)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
From Sprint Review slide:

Looked into the possibility of using the existing BE claim validation (via vets-json-schema) to validate new TE fields
- Top-level JSON fields are static, but properties within those fields are dynamically generated by the FE
   - The “patternProperties” functionality of JSON Schema (draft 4) is meant to address this situation
      - Worked well in online schema validators (I used this one)
      - Wasn’t supported at all by the vets-json-schema infrastructure (posted to support about it here)
   - Best we can do: validation that the top-level JSON fields are objects. Period.
- Other interesting findings along the way
   - The 526 schema is built such that unknown/undefined properties are allowed to be passed in
   - This allows any old field to be saved to the form json field of the SavedClaim, however…
   - …the form json field of the Form526Submission is re-built/re-formatted, so unknown fields are stripped out 
- What this means for us
   - We’ll add this basic validation to vets-json-schema, but…
   - …unless platform provides a workaround/fix for handling dynamic properties in vets-json-schema, we will be “rolling our own”
   - Slack farming and archeology suggests that vets-json-schema is going the way of the do do anyway, with newer groups moving away from vets-json-schema in favor of their own validation solutions

**Comment by sethdarragile6** [comment]
A first draft of the FE/BE contract is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md and also contains questions/issues raised during internal team review (originally posed [here](https://lucid.app/lucidchart/645d8a16-22de-4971-9626-198da0483430/edit?invitationId=inv_f335ce12-6583-4396-8892-0c33e67c8b9e&referringApp=slack&page=Jh7r_XPk53A5)) (cc @aurora-a-k-a-lightning @christinec-fftc )

**Comment by sethdarragile6** [comment]
In light of the fact that we are reorganizing and streamlining the TE endeavor to work more from BE to FE, and the fact that we are working on further FE improvements to the contract- I recommend punting on the inference that we're adding fields to vets-json-schema at all at this point. We've pretty much decided that the FE was going to move on w/o regard to vets-json-schema, and that we might add it there purely for BE validation. However, it's not critical to the progress of the over all TE endeavor, so I'd recommend doing this work down the road: either retrofitting all the TE schema and validation into vets-json-schema at the end (when the dust has settled) OR adding to this schema on a _per page_ basis (gulfWar, conditions, etc) as it's been suggested that that is how our development plan will flow for TE. (cc @RakshindaAslam @aurora-a-k-a-lightning @christinec-fftc )
