### ISSUE TITLE
[FE, PM] My VA Bene App Drafts: SiP config enhancement familiarization

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#79297]
## Background
We are planning to improve the "save in progress" configuration process. A few months back we had a proposal for how to go about this found here. We need to review it and determine how we'll execute this.

## Tasks
- [x] Review [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)
- [x] Work with PM to create subsequent tickets
- [ ] PM to start collab cycle

## Acceptance Criteria
- [ ] We have an approach for executing the improvement
