### ISSUE TITLE
Find a Rep LIVE - User Test - AT Users - Conduct Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#79303]
## Issue Description
Live user testing of Find a Representative experience with mobile and assistive technology (AT) users.

## Tasks

- [ ] Complete interviews
- [ ] Manage interview day to day (team and recruiter coordination, debriefs, interviews, etc.)
- [ ] Download videos and transcripts
- [ ] Compile notes
- [ ] Upload notes, transcripts, and video to Sharepoint
- [ ] Upload notes and transcripts to EnjoyHQ
- [ ] Create analysis and reporting Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Just noting that there's nothing else I can do until we have more sessions which will be a few days
