### ISSUE TITLE
Edit: Add Page to Developer Docs BP: No PII in URL Query Strings

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79318]
## Issue Description
Per this [Slack thread](https://dsva.slack.com/archives/C01CJV0L9PS/p1710948909809799), language needs to be added to the best practices section of the Platform Website developers docs regarding not putting PII in URL query strings.

---
## Tasks
- [x] Work with SMEs to write document
- [x] Review final draft with SME
- [x] move page to Developer Docs deployment space
- [x] Deploy page

## SME: 

- Jonathan Kamens
- Mikki Northuis

## Acceptance Criteria
- [x] All tasks complete and page is deployed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
Starting first draft of new page in drafts space.

**Comment by taylojill** [comment]
I created a draft page and shared with Jonathan Kamens and Mikki Northuis via our platform-content channel. I also attached a PDF of the draft page. Waiting for feedback...
For details see: https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78926

**Comment by taylojill** [comment]
Page content approved by Mikki Northuis via platform-content channel. Waiting for review and approval by Jonathan Kamens.

**Comment by jknipes** [comment]
unable to complete during this sprint due to being blocked by SME, carrying over to next sprint

**Comment by taylojill** [comment]
Follow-up message sent to Jonathan Kamens requesting approval or change of new page content. Request sent through platform-content channel.

**Comment by taylojill** [comment]
Jonathan responded, he's extremely busy and will review page when he has a chance. Move ticket to the next sprint while we wait for his feedback.

**Comment by taylojill** [comment]
Jonathan provided two suggestions for updating the page. I updated per his suggestions and moved page to the space we agreed on in Developer docs, checked for launch-blocking issues, ready to publish.

**Comment by taylojill** [comment]
Per Slack thread message from Mikki Northius, I added the following sentence with a link to the page... "For more information on URLs, see [URLs - VA.gov Design System standards](https://design.va.gov/content-style-guide/url-standards)
Updated page to be deployed 4/18/2024

cc @jknipes
