### ISSUE TITLE
Find a Rep LIVE - User Test - Mobile Users - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#79321]
## Issue Description
Live user testing of Find a Representative experience with mobile and assistive technology (AT) users.

## Tasks

- [x] Request research review
- [ ] Update user test to reflect collab cycle edits
- [ ] Set-up Enjoy HQ project
- [ ] Kick-off with Perigean
- [ ] Create sign-up sheet
- [ ] Transfer demographics to sign-up sheet & Excel
- [ ] Create folders & update guideline documents
- [ ] Create notetaker template
- [ ] Set up Slack channel w/ notetakers & observers
- [ ] Kick-off with notetakers
- [ ] Conduct pilot session
- [ ] Kick-off with observers
- [ ] Create debrief Mural
- [ ] Create conduct interview Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Ready to submit to research collab cycle once I have the link to the prototype - thanks! @mtri for awareness

**Comment by jfinnerty13** [comment]
As caught up as I can be - waiting on kickoff with Perigean.

**Comment by jfinnerty13** [comment]
Wrapped up and sent team sign-up sheet.
