### ISSUE TITLE
Supporting documents form flow framework and design

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#79323]
**Description:**
The goal of this ticket is to develop a framework for form flow interactions when an applicant is required to submit additional forms or other documentation to ensure that applicants understand when, how and why they need to do so. Our current framework depends heavily on conditionally displayed alerts, often without enough information/detail for the applicant to understand specifically what to submit.

Also, on the supporting documents page, we reiterate what forms or documents need to be submitted, but there's not always a clear connection back to where we originally asked for that information and we don't always provide any detail about what type of evidence to submit, what information to include, or how to submit it (in particular, the required documentation for special monthly pension).

**Tasks:**
- Develop a new framework for form flow interactions when the applicant is required to submit additional documentation/forms that doesn't depend on conditionally displayed alerts.
- Apply the framework to the special monthly pension part of the form + conditionally displayed alert as an example
- Attend CAIA office hours to get feedback (also review #73979 with Katherine so it can be incorporated into the copy)
- Plan and create implementation tickets - split up where possible

**AC:**
- [ ] Content/design framework documented
- [ ] Special monthly pension flow + supporting documents page designs created
- [ ] Review with enablement team (Julie/Dene)

**Comment by buddhima-coforma** [comment]
@gmaciolek can we address [findings related to supporting docs](https://docs.google.com/document/d/1nI0g96Or0_sOsjnvyno9bzh_HxIuPt3n3Imb1tNIamw/edit#heading=h.vxtkpf8chd8) through this ticket too?

**Comment by buddhima-coforma** [comment]
Sounds good @gmaciolek. Do we also want a ticket to improve language and behavior on the upload docs page? 
cc @matt4su

**Comment by gmaciolek** [comment]
Yes, if there's not already a ticket for that, we should make one.

**Comment by aplatt-coforma** [comment]
Created #80276: Update copy and behavior of the upload supporting docs page as the follow on ticket to this one. 
@gmaciolek - if there's nothing else to do on this ticket, please close. Thanks!
