### ISSUE TITLE
Upgrade Debian in Container

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79337]
## Description
Upgrade the Debian version in the Docker container to the latest stable release to ensure security and compatibility with Kubernetes.

---

### Tasks
- [x] Identify the latest stable Debian version suitable for the application.
- [x] Update the Dockerfile to use the new Debian version.
- [x] Test the build process to ensure no issues arise from the Debian upgrade.

### Acceptance Criteria
- [x] Dockerfile is updated with the latest stable Debian version.
- [x] Application builds successfully with the updated Debian version.
- [x] All tests pass in both development and production configurations.

**Comment by ryan-mcneil** [comment]
Bumped production dockerfile to bullseye, and will have a PR ready to bump to bookworm. Will also have my `Dockerfile-new` file updated

**Comment by ryan-mcneil** [comment]
bullseye will hit production tomorrow, but due to Retreat, we'll merge bookworm (PR above) on Monday

**Comment by ryan-mcneil** [comment]
Update - merged to Staging today, so we'll hit prod tomorrow

**Comment by JoeTice** [comment]
SPRINT 50 UPDATE - IN PROGRESS: Testing will wrap up in Sprint 51

**Comment by ryan-mcneil** [comment]
Successful prod deploy :thumbsup:
