### ISSUE TITLE
Define approach for requesting Find search results via POST (instead of GET)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#79334]
## Background
When building Find a Representative, we mimicked the handling of the Facility Locator and other search experiences, in that we included the search parameters in the URL and then used that URL to call the backend for search results.  We are also leaning on the parameters in these URLs for tracking user search behavior.

Since that implementation, we've learned that there are some PII concerns with including the location in our Find URLs as well as downstream systems like Sentry and Datadog that will store these URLs for event tracking and monitoring.  

[In this Slack thread](https://dsva.slack.com/archives/C01CJV0L9PS/p1710948909809799), Platform Security recommends updating our logic to use a POST request instead of GET.  
- There are significant **frontend** considerations to transition our request from a GET using the parameters in the URL to a POST that includes parameters packaged into the body of the request.  
- There is a smaller **backend** considerations to expect a different type of request (POST vs. GET) from the frontend.

We also have some open questions as we outline the work to make this change:
1. How does this impact the URL behavior of Find a Representative after a search is performed?  
2. How might we track search behavior if we can’t rely on the URL to determine parameter activity?

This ticket is intended to hold space for investigating the open questions and outlining a development approach for this change, that we can address via individual tickets in upcoming sprints.

## Tasks
- [ ] Consider open questions and outline all technical tasks to make this change
- [ ] Ticket all technical tasks to make this change, place in Product Backlog

## Acceptance Criteria
- [ ] The team has a clear understanding of what work is required to address these PII concerns, so that the work can be incorporated in future sprints.

**Comment by oddball-lindsay** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/79083
