### ISSUE TITLE
Upgrade Ruby to 3.3

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79338]
## Description
Upgrade the Ruby version in the Dockerfile to 3.3 to take advantage of the latest features, performance improvements, and security patches.

---

### Tasks
- [x] Update the Ruby version in the Dockerfile to 3.3.
- [x] Test the application with the new Ruby version in a development environment.
- [x] Resolve any compatibility issues arising from the Ruby upgrade.

### Acceptance Criteria
- [x] Dockerfile specifies Ruby version 3.3.
- [x] Application functions correctly with Ruby 3.3 in all environments.
- [x] All existing tests pass with the updated Ruby version.

**Comment by ryan-mcneil** [comment]
No noticeable issues updating to ruby 3.3.0

Note: This required updating the Docker image to `3.3.0-slim-bullseye` (was at buster, which doesn't exist for 3.3.0), which did break the import of certs. I'm going to comment out the cert import, as that will be relevant in #79342.

**Comment by ryan-mcneil** [comment]
PR [here](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/1069). Cannot merge as it's tightly couple to updating bundler and docker image
