### ISSUE TITLE
Upgrade Bundler to 2.5

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79339]
## Description
Upgrade Bundler in the Dockerfile to version 2.5 to improve dependency management and build stability.

---

### Tasks
- [x] Update Bundler version in the Dockerfile to 2.5.
- [x] Ensure all dependencies are compatible with Bundler 2.5.
- [ ] Test the build process and application functionality with the updated Bundler version.

### Acceptance Criteria
- [x] Dockerfile uses Bundler version 2.5.
- [x] Application dependencies are correctly managed and installed with Bundler 2.5.
- [x] Application builds and runs successfully with no issues related to Bundler.

**Comment by ryan-mcneil** [comment]
Clean build when updating to 2.5.7

**Comment by ryan-mcneil** [comment]
PR [here](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/1069). Cannot merge as it's tightly couple to updating bundler and docker image

**Comment by ryan-mcneil** [comment]
PR [here](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/1069). Cannot merge as it's tightly couple to updating bundler and docker image

**Comment by ryan-mcneil** [comment]
PR [here](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/1069). Holding off on merge until feature work is complete
