### ISSUE TITLE
Migrate cronjobs to something compatible w/ K8s

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79341]
## Description
Migrate existing cron jobs to a Kubernetes-compatible scheduling method to ensure they are properly managed in the new environment.

---

### Tasks
- [ ] Identify all cron jobs running in the current environment.
- [ ] Convert cron jobs to Kubernetes CronJobs or an equivalent scheduling method.
- [ ] Test the migrated cron jobs to ensure they execute as expected in the Kubernetes environment.

### Acceptance Criteria
- [ ] All identified cron jobs are successfully migrated to Kubernetes CronJobs.
- [ ] Migrated cron jobs execute according to their schedules and complete their tasks successfully.
- [ ] Documentation is updated with details of the cron job migration and management in Kubernetes.

**Comment by ericboehs** [comment]
Turns out GIBCT doesn't have ant cronjobs even though they're using a cronjob manager ([whenver](https://github.com/javan/whenever)).
