### ISSUE TITLE
Update method for importing VA certs

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79342]
## Description
Update the method for importing Veterans Affairs (VA) certificates in the Dockerfile to ensure compatibility and security in the Kubernetes environment.
---

### Tasks
- [x] Review the current VA certificate import method.
- [x] Propose and implement an updated method suitable for Kubernetes.
- [x] Test the application to ensure it can successfully use the imported VA certificates.

### Acceptance Criteria
- [x] VA certificates are imported using a method compatible with Kubernetes.
- [x] Application securely communicates with necessary VA services using the imported certificates.
- [x] There are no security warnings or errors related to VA certificate usage.

**Comment by ericboehs** [comment]
I looked into this a bit with Ryan. I'm wanting to update the import scripts in [department-of-veterans-affairs/platform-va-ca-certificate](https://github.com/department-of-veterans-affairs/platform-va-ca-certificate) to look in ../ instead of /tmp (or maybe in addition to). [Trying to get push access](https://dsva.slack.com/archives/C04CYC4LMU6/p1712702416052109) now.
