### ISSUE TITLE
Make Dockerfile Development Friendly

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#79340]
## Description
Optimize the Dockerfile for development purposes to achieve slim builds and quick rebuild times without sacrificing functionality.

---

### Tasks
- [x] Review and implement best practices for Docker multi-stage builds.
- [x] Optimize layer caching strategies for development builds.
- [x] Test rebuild times and compare with current benchmarks.

### Acceptance Criteria
- [x] Dockerfile supports efficient development builds with optimized layer caching.
- [x] Rebuild times are significantly improved without losing build functionality.
- [x] Documentation is updated with instructions for development builds using the optimized Dockerfile.

**Comment by ryan-mcneil** [comment]
Perhaps we could have thought the criteria through better for this ticket.

This [PR](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/1092) has a new Dockerfile prepared for development (well, mostly). I'm not sure if we want to merge it at this time.

**Comment by ryan-mcneil** [comment]
AC met, but we'll keep this [PR](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/1092) in a DRAFT state until we're ready to swap out all CI pieces
