### ISSUE TITLE
Refactor logging and stats for 526ez prefill

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#79346]
## Issue Description

Currently, some [basic logging](https://github.com/department-of-veterans-affairs/vets-api/blob/b52ce0eca5ae63d5438536b761f44002c8402555/app/models/form_profiles/va_526ez.rb#L145) is in place to track missing address, phone and email information, as well as whether or not the PCIU removal flag is ON or OFF. This has given us valuable information, however there are 2 modifications that would make it MORE useful:

1. log counts of missing data from VA Profile AND VA Profile+PCIU, regardless of whether or not the flag is ON/OFF
2. log output replaced with statsd counts

This should help the dashboard load more efficiently, while also giving us running comparisons of missing counts with VA Profile-only vs VA Profile+PCIU- regardless of flag state.

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] Implement 1 & 2 from above, and remove old logging
- [ ] Update [DataDog dashboard](https://vagov.ddog-gov.com/dashboard/qv6-xpd-7xg/benefits---dbex---evss-to-vaprofile-526ez-contact-info-pre-fill?fromUser=false&refresh_mode=weekly&view=spans&from_ts=1711350000000&to_ts=1711493486776&live=true) to use the new metrics (but keep old graphs for historical reference, save off an "historical" copy)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
