### ISSUE TITLE
PTSD Design Work First Steps

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#79359]
A new 0781 will be released combining the current 0781 and 0781a forms into one form. We need to update the online experience within the 526 to reflected the new 0781 form.

See also: [PTSD Discovery Work](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/77615)

**Tasks**
- [x] Review [Design at VA](https://depo-platform-documentation.scrollhelp.site/research-design/design-at-va) page to learn about the Collaboration Cycle
- [x] Map out new 0781 form flow as a guideline to start building out new 0781 form flow in [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712613185792/a190e081af32a64ffde84897881c5ef21731ed4e?sender=u3672f0ffd2d02de8b0885285)
- [x] Meet with non-disability benefits designers to knowledge share from their experience updating pension form
- [x] Document questions/clarifications for VBA/OCTO along the way, and add these to our biweekly VBA sync agenda. 
- [x] Create Collab Cycle intake ticket
- [x] Create CAIA intake ticket

**Acceptance Criteria**
- [x] Work split up into tickets
- [x] [Collab cycle intake ticket created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80848)
- [x] [CAIA intake ticket created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80870)

**Comment by nnicholas7** [comment]
Jina will move forward with the PTSD design work as Nichole (ooo April 8-15) and Julie (ooo April 3-10) will be ooo.

**Comment by jinaryu** [comment]
Met with Fiorella (designer from non-disability benefits team) and got direction on how to structure form flow Mural. Created a new Mural here and will work on filling this out as the first step prior to starting designs in Figma. https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712613185792/a190e081af32a64ffde84897881c5ef21731ed4e?sender=u3672f0ffd2d02de8b0885285

**Comment by jinaryu** [comment]
Finished draft 1 of [VA Form 0781 Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712613185792/a190e081af32a64ffde84897881c5ef21731ed4e?fromVisitorModal=true&sender=u3672f0ffd2d02de8b0885285). Also noted questions for SMEs and design team. Will start building screens in Figma to help visualize flow

**Comment by jinaryu** [comment]
Started Figma [file](https://www.figma.com/file/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?type=design&node-id=2079%3A1122&mode=design&t=Ug7bdsoQ1DNYws4I-1)

**Comment by jinaryu** [comment]
created and submitted collab cycle ticket

**Comment by jinaryu** [comment]
created and submitted CAIA ticket
