### ISSUE TITLE
Toxic Exposure - Data Transformation #1 -  For contract between vets website and vets-api

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#79386]
## Issue Description
Front-end - Interface between the vets website and vets-api is fulfilled. 

Need to figure out of jSON schema will be used or an alternate way

https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/submit-transformer.js#L261
---
## Tasks
- [ ] Check the claim submission in staging
- [ ] Sanity check on the added TE data 

## Acceptance Criteria
- [ ] No data loss 
- [ ] All data is sent to BE in the correct format
- [ ] Identify what, if any, processing is needed on the front-end
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
closing duplicate
