### ISSUE TITLE
[Data] 10-10EZR TERA Questions: Tracking post launch data

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#79394]
As a stakeholder, I would like to know how many Veterans are using the 10-10EZR when it's online at 100%, and if they're answering TERA Questions, so that I have a good understanding of whether or not the EZR is being utilized. 

- [x]  Timeframes to report on: within the first 24h, first 1 week, first 1 month of The TERA questions launch

- [x] Track the following Success Metrics for each period of time:
- number of applications started
- How many sessions made it to TERA questions
- number of successful submissions
- number of failed submissions
- Average # of sessions to submission
- Start to submission ratio

- [x] Track the following Performance metrics for each period of time:

- Avg. Latency from controller & from external dependent resources
- Types of status codes present in errors
- Error rate
- Avg. time on page / form
- wish list item (user page flow funnel) 
- Number of submissions with filled out TERA Questions (as a percentage to total submissions)

**Success: We are able to share EZR usage metrics and TERA Question usage metrics to our POs (Kristen and Patrick), HEC, and anyone else who asks for them. **

**Comment by luis-simauchi** [comment]
link to the spreadsheet I am working out of

**Comment by luis-simauchi** [comment]
the first "24 hrs" of stats of EZR with tera questions
Timeframe: Apr 11, 12:00 am – Apr 12, 11:59 pm		
Metrics	
successful submission:	54	From DD	
Avg. Time on Page (per page): 0:00:51 From GA
Unique Pageviews = Sessions	85 From DD,	67 From GA
Errors: 0	
Error Rate %: 	0% (edited)

**Comment by luis-simauchi** [comment]
Timeframe: Apr 11, 12:00 pm – Apr 18, 11:59 am	
Metric	From DD
successful submission	351
total sessions	509
Avg. Time on Page	
Number of Sessions per User	
Errors	1
Error Rate %	0.196%
Start to Finish Ratio %	53%
Avg Session Duration	5 min 50 s
	
Error type	Notes
validation error 	error from DD comes up from a 500 error code in getting the Disability Rating under EVSS,  Sentry Log confirms that the submission didn't fit the format we were expecting. That tracks with EZR requiring veteranFullName and it being absent here

**Comment by luis-simauchi** [comment]
going to close this ticket out and open up a ticket for the monthly data download to share
