### ISSUE TITLE
[spike] DR | Continued Investigation of "blank images" and "invalid PDF content" downstream errors

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#79406]
## Background Context

Initial spikes completed here:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74511
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74503

This is a follow-up task to do more in-depth investigation of what is going on with PDFs that are causing the "Invalid PDF content, part content" and "blank images" errors. We discovered in the previous spikes that for both types of errors, it is likely that these PDFs are getting corrupted/blanked out in the process of our backend (vets-api) uploading the files to our S3 storage bucket. 

## Tasks
- [x] Check if validation endpoint detects the locked/corrupt pdfs correctly
- [x] Check with Cory on whether we can work with sample PDFs that have caused these errors in prod (i.e. should we be working with this PHI/PII?) and if exploring the SQS option for storing original payloads is a better option / something to do concurrently
  - [x] If Cory approves, work with Kimberley to get sample PDFs

## Definition of Ready
- [x] Whoever picks this up has access to our S3 bucket

## Definition of Done
- [x] Follow-up tickets for development tasks have been created

**Comment by dfong-adh** [comment]
Reached out to Cory on Slack regarding working with Kimberley to obtain sample PDFs.

**Comment by dfong-adh** [comment]
Reached out to Kimberley regarding contacting the veterans for evidence uploads.

**Comment by saderagsdale** [comment]
(Comms are in teams)

**Comment by dfong-adh** [comment]
Notes on a recent blank images PDF (error occurred on 2024-04-03 18:51:30 UTC):
* Single page document
* White text on white background
* Was able to highlight the text, then copy and paste the text into a text editor

**Comment by dfong-adh** [comment]
Provided list of veterans to Kimberley for review

**Comment by dfong-adh** [comment]
[Decision Review Original Evidence Payloads Storage - Initiative Brief
](https://docs.google.com/document/d/1t_AUN4JL0pjpbaytzoy6GZ7kw7ZkSjUfJmVVQGwswCo/edit)

**Comment by saderagsdale** [comment]
- Had a meeting with EMMS this morning. Leaning toward using the current functionality to move forward.

**Comment by dfong-adh** [comment]
Created implementation ticket #81205 to store unprocessed PDFs for comparison

**Comment by saderagsdale** [comment]
@dfong-adh do we need to keep this open?

**Comment by dfong-adh** [comment]
We can close this 👍
