### ISSUE TITLE
Content Tip of the Sprint (S450)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79405]
## Purpose
The Content team provides a new "content tip" every sprint with the #platform-content channel's audience. The purpose of this is to provide continuous style guidance and re-enforce content best practices for contributors of the Platform website.

## Tasks

- [x]  Pick a content tip idea from the style guide
- [ ]  Draft a content tip Slack post, similar to the first one posted on Thurs, Jan 5: https://dsva.slack.com/archives/CL181NRJQ/p1672938003050849
- [ ]  If needed, get feedback from rest of Content team
- [ ]  Copy and paste the team-approved announcement of our Tip of the Sprint in to the platform-content slack channel.
- [x]  Schedule for **Monday, April 1, 2024**

## Acceptance Criteria:

- [x]  A new content tip will be posted on #platform-content for this sprint.

**Comment by jknipes** [comment]
Topic will be: Table of Contents Macro

**Comment by jknipes** [comment]
Content Tip of The Sprint has been announced. Moving to _Done_
