### ISSUE TITLE
Create new copy docs for details redesign

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#79404]
## Task Description
Create copy doc for details redesign.

## Notes and References
- We're using a temporary copy doc to do the updates. Once that's complete we'll copy its content over the [current details copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md).

## Acceptance Criteria
- [x] Temp copy doc is complete
- [x] Current copy doc is updated with new copy
- [x] Temp copy doc is deleted

## Deliverables
-  [Updated details copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md).

**Comment by outerpress** [comment]
@ldelacosta @Cieramaddox I'm working on the first pass of the details page redesign copy docs here. Will handoff to you to finalize once that's done

**Comment by outerpress** [comment]
Need to run through moving the copy into Figma, which might make this work unnecessary.

**Comment by outerpress** [comment]
Adding #81639 as a blocker since that might replace this work

**Comment by outerpress** [comment]
@ldelacosta @Cieramaddox I updated the [appointment details copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md) I'll work on capturing everything here in Figma, but until that's done pls use this as the primary content reference
