### ISSUE TITLE
Alternative designs for Find search results, supporting rep names as focusable interactive elements

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#79418]
## Background
In our accessibility pilot for Find a Representative, it was discovered that the focus skips over the representative name in search results -- it goes right to the associated organizations.  

This is actually as expected, given the elements on the page, as tabbing should only shift focus to interactive elements (the name is not an interactive element, but the associated organizations is).  This was called out as a minor issue, and we'll have our accessibility study to understand if this is a more critical issue to solve for.

Finding a solution will be a design challenge -- are there interactive elements we can use to bring the name into focus?  

As an example, our accessibility partner suggested having search results as accordions.  We've also discussed this concept of a "detail page" for rep search results, so that could be another concept to explore.  

## Tasks
- [ ] Ideate alternative designs for search results, where the name is an interactive element
- [ ] Discuss designs with the team
- [ ] Iterate on designs based on team feedback

## Acceptance Criteria
- [ ] An alternative design for Find a Representative search results has been defined, that is more accessible to users with screen readers.

**Comment by oddball-lindsay** [comment]
duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/79419
