### ISSUE TITLE
2024 Q2 Monitor PACT Act Spring 2024 Submissions

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79410]
## Issue Description
This ticket is to monitor the DataDog dashboard created by the Platform Product team [here](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms?fromUser=false&index=%2A&refresh_mode=sliding&view=spans&from_ts=1710421711677&to_ts=1711026511677&live=true) for T1 and T2 folk to check daily, beginning on 3/21, and ensure that there is no unusual activity or issues. 

---
## Tasks
- [x] Daily monitoring by Platform Product or T1/T2 Support teams for unusual activity
- [x] Action by the appropriate team in the event of unusual or blocked activity 
- [x] Reroute issues to appropriate team when they are found, if they can not be mitigated by Platform Product team
- [x] Follow up with assigned team to ensure that the fix has been implemented 
- [x] PLATFORM PRODUCT TEAM MAJOR RESPONSIBILITY IS TO MONITOR AND MAKE OTHER TEAMS AWARE

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE: N/A

## Acceptance Criteria
- [x] Any unusual activity will be flagged by Platform Product or T1/T2 Support teams and rerouted to the appropriate team for their immediate attention as soon as PACT Act submissions begin to roll in.

**Comment by LindseySaari** [comment]
No unusual activity seen this sprint and we monitored closely. Closing this ticket and we will open another ticket for the next sprint and following sprints as needed.

**Comment by jennb33** [comment]
Reopened this ticket as it is the **quarterly** ticket for Q2 now.
