### ISSUE TITLE
Atlas V2: Discovery and Comparison work: Product Directory/Atlas

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79435]
## Issue Description
As Atlas V1 evolves to V2, there are some things that need to be established and baselined so that the work and intent going forward is understood by all stakeholders. It is important to remember that DataDog acts as Source of Truth for Service information/YAML. 

- Could we fold in the current state of Product Directory into future state of Atlas?
- How does CodeVA fit into the overall scheme of how Atlas and Product Directory could be when they combine?

---
## Tasks
- [x] Compare Atlas and the Product Directory in their current states 
- [x] Create a roadmap/information flow of each system's behavior and how they send and receive the information that populates each system. 
- [x] Identify stakeholders and their roles. 
- [x] Identify and validate who uses Atlas in current state.
- [x] Identify and validate who uses the Product Directory in current state.
- [x] Identify how users of Product Directory interact with the information in Product Directory in current state
- [x] Document groundwork for Product Directory/db design in Atlas

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [x] Final, accepted current state design document/information flow map of Atlas 
- [x] Final, accepted current state design document/information flow map of Product Directory
- [x] Roadmap of the work (if available) - N/A for atlas, checking for Product Directory 
- [x] SWOT of Atlas - current state
- [x] SWOT of Product Directory - current state
- [x] any other functional requirements for Atlas V2 (documented [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3035463704/2024+Atlas+Version+2+Functional+Technical+Requirements))
- [x] any other stakeholders for Atlas V2 (documented [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2951021703/2024+Atlas+Improvements+-+Stakeholders))

**Comment by LindseySaari** [comment]
@jennb33 I created [a document here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3148447766/Discovery+and+Comparison+Product+Directory+Atlas) for us to start with

**Comment by LindseySaari** [comment]
Continuing to work through the technical details around the product directory. I will have @jennb33 review when she returns on Monday and we will divide the document up where it makes sense

**Comment by LindseySaari** [comment]
@jennb33 Do you want to provide a "Roadmap of the work and a rough timeline" from the AC

**Comment by LindseySaari** [comment]
Going forward we will create a roadmap for the work. We were unable to identify roadmaps for the Product directory and Atlas v0. We saw evidence of an [Atlas roadmap here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2886926544/Roadmap+WIP) and then a mention of needing a roadmap [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2760671235/Product+Outline+Atlas+WIP) "It needs an identity and a roadmap"
