### ISSUE TITLE
[BE] 10-10EZ - Facilities API update: Apply for Prod access 

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#79439]
## Background
Now that we have set up our API to use LH Facilities API, we need to request access to API in Production

## Tasks
- [ ] Submit for prod access by submitting this [request form](https://developer.va.gov/onboarding/request-prod-access)
- [ ] Work with Marmoset team to answer questions and process the request
     - Someone from the Marmoset team should coordinate the onboarding/access
- [ ] Obtain key from Marmoset team coordinator & further instructions
- [ ] Incorporate key so that we can use the API in production
- [ ] Inform QA that this is ready for testing in Staging (ticket #79440 )

## Acceptance Criteria
- We have a prod access API key
