### ISSUE TITLE
Send Widget to CAIA for Landing Page inclusion

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#79433]
## Background
The launch of the Rep Status Widget will include adding it to our [accredited representative landing page](https://www.va.gov/get-help-from-accredited-representative/).  The widget should not be visible to users prior to launch, because it will be behind a feature flag.

Landing page designs: [desktop](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&type=design&node-id=456-168371&viewport=-1457%2C1672%2C0.13&t=aNfLF2kuoMnPoxpr-1&scaling=min-zoom&starting-point-node-id=456%3A168371&show-proto-sidebar=1&mode=design) and [mobile](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=0%3A19109&type=design&node-id=456-169444&viewport=-1457%2C1672%2C0.13&t=aNfLF2kuoMnPoxpr-1&scaling=min-zoom&starting-point-node-id=456%3A169444&show-proto-sidebar=1&mode=design).

We do not control the landing page -- that's owned by CAIA.  We'll need to send the widget code to CAIA so that they can include this in the landing page.  

## Tasks
- [x] ~Update code so that Colin can manually change the rep status states~ Create a React Widget that contains the Rep Status Widget, to manage the staged rollout on the landing page.
- [x] Send the Widget code to CAIA (A Procik) for inclusion on the landing page
- [x] Set a meeting with A Procik and Megan Zehnder to confirm that the widget is in place and each state (showing the Rep Status Widget vs. not showing it) is rendering as expected 
- [ ] Confirm that the feature flag is working as expected and Widget does not appear in production

## Acceptance Criteria
- [ ] When the Rep Status Widget is released, users on VA.gov will be able to see their current representative status on the landing page, before being introduced to the Find and Appoint processes.

**Comment by oddball-lindsay** [comment]
How to approach the different states?  Can consider a radio option to select a state to render.

**Comment by oddball-lindsay** [comment]
@cosu419 could you please prioritize the first task in this ticket, so that we might be able to pass CAIA our Widget code prior to our Weds meeting?

**Comment by oddball-lindsay** [comment]
Unsure if the effort of hardcoding each Widget state is worth it -- we are testing each state with our test users on Find Staging.  Asking CAIA if it's okay to proceed with just testing placement.  Conversation in Slack: https://dsva.slack.com/archives/C05L6HSJLHM/p1713804924704989

**Comment by oddball-lindsay** [comment]
In today's meeting, additional work was identified to support Drupal because it does not allow for dynamic content like our product pages do.  

We decided together to hold off on additional work needed to support the 1-week staged rollout.  Instead we will add the Representative Status Widget to the landing page when we are at 100% of our staged rollout, currently scheduled for 5/13.

A request did arise to remove the header and intro copy above the widget after we roll out -- CAIA will instead have this in the landing page.  Will create a separate ticket for that work.  

<img width="1306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1WQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37f9418e7412db1b450d4d5986a752ccf1742aab/image.png" alt="image.png" />
