### ISSUE TITLE
Create landing pages without manifest.json files

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7943]
## Problem Statement
The content build needs to create React application landing pages without access to the `manifest.json` files after it's moved out of `vets-website`.

## The Solution
The end goal is to put those landing pages in Drupal, but as a stopgap until that's possible, we'll create an `application-registry.json` which includes all the information the content build process will need to create the landing pages. This can be migrated over to the content build repo when that work is done.

## Goal
Isolate application dependencies from the content build so we can move the content build into its own repository.

---
## Tasks
- [ ] Create an `application-registry.json` and include all the data from all the `manifest.json` files
    - JSON is an array of objects
    - Each object contains the entire contents of a manifest file
      - Some properties may not be needed and can be excluded; I don't have a full list right now
- [ ] Modify the `createReactPages` Metalsmith plugin to use the `application-registry.json`
- [ ] Remove old properties from `manifest.json` files
    - This may just be `production` (not used right now anyhow) and `vagovprod`
- [ ] Find and update the documentation

Bonus points for making the value of `vagovprod` not implicit.

## Acceptance Criteria
- [ ] The applications that were in production are still in production
- [ ] The applications that were not in production are still not in production
- [ ] Application landing pages are created without using `manifest.json` files
