### ISSUE TITLE
[Design] Design system migration: Review impact of design system updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#79443]
## Background
Design system announced some upcoming changes ([slack thread](https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359)):
 

1. `va-icon` adoption: Font Awesome will be deprecated. We're working on guidance this sprint for how teams can migrate onto va-icon which will be shared out soon. We tentatively expect Font Awesome to be deprecated at the end of May, giving teams the whole month to adopt `va-icon`.
2. A new 640px breakpoint will be added to help va.gov re-align with USWDS v3. This will eventually replace the current 768px breakpoint. We'll provide a more concrete timeline for this, though we tentatively expect to remove the 768px breakpoint in early August.
3. Font size increasing to 16.96 on May 8 (if not already evaluated)

## Tasks
- [x] Review upcoming changes 
- [x] Document impact in comments
- [x] Work with AJ to identify tickets for follow-up work

## Acceptance Criteria
- [x] We understand the impact of the upcoming design changes

**Comment by mattmarino-adhoc** [comment]
Some initial takeaways:
* Need to document all icon usage on My VA, determine source of icon (all Font Awesome, any library dependencies, etc.)
* 640px breakpoint - we need to assess current state with My VA, but let's also see what dependencies we have with our partners (Benefits, Profile, etc.) and what their plans are to address the deprecation of 768px. 
* Font size shouldn't be a huge issue, but let's make sure we're utilizing font libraries across My VA

**Comment by mattmarino-adhoc** [comment]
Update on timeline for Item 1:
"Micha's post in #vfs-change-announcements from Monday is the current guidance:
va-icon adoption: Font Awesome will be deprecated. We're working on guidance this sprint for how teams can migrate onto va-icon which will be shared out soon. We tentatively expect Font Awesome to be deprecated at the end of May, giving teams the whole month to adopt va-icon.
Unfortunately, we can't realistically update every icon across the site in one PR and have it happen all at the same time (our CI can't currently handle it even if we could orchestrate it). Thus once we make the first change the clock will be ticking and we'll be trying to help teams get the icons changed as quickly as possible. Deadline will be June 5. (edited) 



Micah Chiang
:mega: Announcement: Upcoming Design System migrations :mega:
va-icon adoption: Font Awesome will be deprecated. We're working on guidance this sprint for how teams can migrate onto va-icon which will be shared out soon. We tentatively expect Font Awesome to be deprecated at the end of May, giving teams the whole month to adopt va-icon.
A new 640px breakpoint will be added to help VA.gov re-align with USWDS v3. This will eventually replace the current 768px breakpoint. We'll provide a more concrete timeline for this, though we tentatively expect to remove the 768px breakpoint in early August.
Thread in vfs-change-announcements | Mar 18th | View message"

**Comment by mattmarino-adhoc** [comment]
Expected impact of item 1:
I anticipate the impact to be minimal, with less than 25 icons to be replaced and apparently being sourced all from the same library. Where we may see any issue would be if there are icons on My VA that don't have an equal or equivalent in the icon library. With the deadline now being June 5, that will hopefully give us enough time to notify the platform design team of any gaps in icon coverage if they come up.

**Comment by mattmarino-adhoc** [comment]
Expected impact of item 2:
It's unlikely impact will be significant. One thing to consider though is how text might stack in a way it isn't currently, particularly in content-heavy cards on My VA.

**Comment by mattmarino-adhoc** [comment]
Expected impact of item 3:
Very minimal

**Comment by mattmarino-adhoc** [comment]
@ajakabcin let's sync tomorrow about this, but we will need:
* a design story for each of the 3 issues:
- [ ] Assessing icons available, updating Figma My VA file with icons, conferring with team as needed
- [ ] Updating Figma My VA file with new mobile breakpoint, attempting to get a sense of any possible problems with displaying content, conferring with team as needed
- [ ] Updating Figma My VA file with new font size

* a story for each of these 3 issues for engineering as well for implementation (if engineers think it makes sense to have more than that to break things out, that's fine by me too).

* It is possible that we may end up needing additional design and engineering stories beyond these (if there are gaps in icons available for 1, or issues with info being displayed on cards for 2) but for now these should sufficient.
