### ISSUE TITLE
[BE] Update appointments data serializer to handle ICN in appointments object

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#79457]
## Description
As a veteran, I want to be able to submit travel claims for Oracle Health site visits

Details:
For OH sites, we don't get ICN under demographics object. instead it's in appointments object. We need to update the serializer to serialize the ICN appropriately 

## Tasks
- [] [BE] **Modify appointments identifier serializer for OH facilities to get ICN from appointments object**
- [] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
