### ISSUE TITLE
[UX] Create new figma file for content and document variations of text messages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79459]
## Tasks

- [x] Create new Figma file in shared space that will be the SOT for content 
- [x] Share the link with Ciera and in appointments-ux channel

## AC

- [x] Figma file created
- [x] Shared with Ciera and appointments-ux

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/79459?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by benbrasso-agile6** [comment]
Marked as high priority, so we can talk about tasks 1 and 2 at the MHV Library call on Thursday, @zach-park

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske , MHV Content Library is created and added to the MHV workspace:
https://www.figma.com/file/enGXBfuvpWJOQp0onrWgHs/%5BDRAFT%5D-MHV---Unified-Appointments-Content-Library?type=design&node-id=0%3A1&mode=design&t=jUCYd1uINjJ2OO4s-1
