### ISSUE TITLE
QA Topic for Platform Support Bot

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#79463]
## Description

This ticket will house the task of adding a topic for QA (or a variation of that name) for post Orientation session questions owned by Governance. All requests submitted under this topic will be sent to Governance. See context here: https://dsva.slack.com/archives/C02RLAUM2LV/p1711551094640889
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Verify steps to add a new topic with Curt/Kerry
- [x] Add topic with agreed upon name 
- [x] Ensure that the topic routes to Governance Team 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
