### ISSUE TITLE
Remove DurationCard since it is no longer being used in the CST

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#79469]
---
## Background Context
4 years ago we hid the DurationCard due to covid
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10293
https://github.com/department-of-veterans-affairs/vets-website/pull/13359

On 3/27/24 I talked to Julie about whether we want to keep this code disabled, enable it or remove it entirely. After discussing she decided we should remove it entirely and if we decide we want to have it later on we can always bring it back.

## Tasks
- [ ] Delete DurationCard file
- [ ] Remove it from Docket
- [ ] Remove it from WhatsNext
- [ ] Delete DurationCard test file
- [ ] Remove it from Docket tests
- [ ] Remove it from WhatsNexts tests
- [ ] Remove comment in appeals-v2-helpers (lines 1212-1215)

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] DurationCard is no longer referenced in the CST

**Comment by pmclaren19** [comment]
Validated in Staging and looks good
