### ISSUE TITLE
Use Webpack to create js/ assets

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7946]
## Problem Statement
Currently, the Metalsmith build creates the assets found in `build/${buildtype}/js/`. As we transition the Metalsmith build to be responsible only for creating HTML files, we need to move the responsibility of creating the assets in `js/` into the application (Webpack) build.

This task will require some discovery to determine the best approach.

**Note:** This assumes Webpack is the right answer to this. If there's a better approach, we should do that.

---
## Tasks
- [ ] Figure out where the `js/` assets come from
- [ ] Replicate the process in the application build
    - The challenge here is that the normal Webpack build emits files at `build/${buildtype}/generated/`, but we'll need it to _also_ emit _some_ files at `build/${buildtype}/js/`
- [ ] Remove the Metalsmith plugin which adds `js/`

## Acceptance Criteria
- [ ] The Metalsmith build script no longer creates files in `js/`
- [ ] A full build still emits the appropriate files to `js/`

**Comment by billfienberg** [comment]
The `download-assets` Metalsmith plugin calls the `downloadFromLiveBucket` function when `assetSource === assetSources.DEPLOYED`, but I’m having trouble finding any situation where `asset-source` is `deployed`.

I see that a trimmed HEAD gets used to define a ref in the `Jenkinsfile`, but I can’t find any instances of `--assetSource=deployed`.

References:
- `asset-source` in the `content-build-help` file: https://github.com/department-of-veterans-affairs/vets-website/blob/ae9e2a3e11becb783dd379a4076ea5080beb6e43/script/content-build-help.js#L29-L34
- `download-assets` Metalsmith plugin: https://github.com/department-of-veterans-affairs/vets-website/blob/c6cd189cacbf81245bef43bf3a1c6953aefc73fe/src/site/stages/build/plugins/download-assets.js
- Repo search for asset-source: https://github.com/department-of-veterans-affairs/vets-website/search?q=asset-source&unscoped_q=asset-source
- Repo search for `assetsource`: https://github.com/department-of-veterans-affairs/vets-website/search?q=assetsource&unscoped_q=assetsource
- Repo search for `deployed`: https://github.com/department-of-veterans-affairs/vets-website/search?q=deployed&unscoped_q=deployed
- `Jenkinsfile`: https://github.com/department-of-veterans-affairs/vets-website/blob/master/Jenkinsfile#L16
- `common.groovy`: https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L220

**Comment by billfienberg** [comment]
## Example of an inline JS asset

The [`survey-tools.html`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/includes/survey-tools.html) [Twig template](https://twig.symfony.com/doc/3.x/templates.html) checks the `buildtype` variable, and [`includes`](https://twig.symfony.com/doc/3.x/tags/include.html) the corresponding [`staging`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/js/foresee/vagovstaging.js) or [`prod`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/js/foresee/vagovprod.js) JS asset. 

## Explanation

Since the content-build will continue using the Twig template to render the content of the JS asset file via `includes`, it's not necessary to create that JS asset via Webpack.

**Comment by meganhkelley** [comment]
From Bill: https://docs.google.com/spreadsheets/d/1Njhp1GRAzPhd67iIUzbTQtrnASUbLg36Vha52aymOA8/edit?usp=sharing 

This doc identifies all the usages of js assets. Once this documentation is finalized, we will be able to evaluate whether this ticket can be closed (unfinished) or must be completed.

**Comment by billfienberg** [comment]
## Table of JS asset usages

|  File in `src/site/assets/js` | Usages | Notes |
| --- | --- | --- |
|  src/site/assets/js/execute-axe-check.js | https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/inject-axe-core.js |  |
|  src/site/assets/js/incompatible-browser.js | • https://github.com/department-of-veterans-affairs/vets-website/blob/8f5a01aca08f40c04633a7c6560da3a7647077d0/src/site/includes/header.html#L109 <br>•  https://github.com/department-of-veterans-affairs/vets-website/blob/bd4ff75b66850296d4e546916f1e5f3b0176e340/src/platform/landing-pages/dev-template.ejs#L124<br>• https://github.com/department-of-veterans-affairs/vets-website/blob/854a224e1a9eaaedcb8a149d5f081991ae0f0584/config/webpack.config.js#L265 |  |
|  src/site/assets/js/record-event.js | • https://github.com/department-of-veterans-affairs/vets-website/blob/8f5a01aca08f40c04633a7c6560da3a7647077d0/src/site/includes/header.html#L34<br>• https://github.com/department-of-veterans-affairs/vets-website/blob/bd4ff75b66850296d4e546916f1e5f3b0176e340/src/platform/landing-pages/dev-template.ejs#L11<br>• https://github.com/department-of-veterans-affairs/vets-website/blob/854a224e1a9eaaedcb8a149d5f081991ae0f0584/config/webpack.config.js#L266 |  |
|  src/site/assets/js/static-page-widgets.js | • https://github.com/department-of-veterans-affairs/vets-website/blob/d36d1c27f62328143d188cee7dbcf26488eda603/src/site/includes/footer.html#L13<br>• https://github.com/department-of-veterans-affairs/vets-website/blob/58edf4784778488c183d7f5385a3a3cfb71375dc/src/applications/static-pages/tests/static-page-widgets.unit.spec.js#L3<br>• https://github.com/department-of-veterans-affairs/vets-website/blob/bd4ff75b66850296d4e546916f1e5f3b0176e340/src/platform/landing-pages/dev-template.ejs#L180<br>• https://github.com/department-of-veterans-affairs/vets-website/blob/854a224e1a9eaaedcb8a149d5f081991ae0f0584/config/webpack.config.js#L267 |  |
|  src/site/assets/js/foresee/vagovprod.js | https://github.com/department-of-veterans-affairs/vets-website/blob/c7c0ad0426566c51045becc22d422de351c9c7b3/src/site/includes/survey-tools.html#L3 |  |
|  src/site/assets/js/foresee/vagovstaging.js | https://github.com/department-of-veterans-affairs/vets-website/blob/c7c0ad0426566c51045becc22d422de351c9c7b3/src/site/includes/survey-tools.html#L9 |  |
|  src/site/assets/js/google-analytics/vagovdev.js | https://github.com/department-of-veterans-affairs/vets-website/blob/d36d1c27f62328143d188cee7dbcf26488eda603/src/site/includes/google-analytics.liquid#L10 |  |
|  src/site/assets/js/google-analytics/vagovprod.js | https://github.com/department-of-veterans-affairs/vets-website/blob/d36d1c27f62328143d188cee7dbcf26488eda603/src/site/includes/google-analytics.liquid#L30 |  |
|  src/site/assets/js/google-analytics/vagovstaging.js | https://github.com/department-of-veterans-affairs/vets-website/blob/d36d1c27f62328143d188cee7dbcf26488eda603/src/site/includes/google-analytics.liquid#L20 |  |
|  src/site/assets/js/vendor/uswds.min.js |  | Used by teamsites |

**Comment by billfienberg** [comment]
`src/site/assets/js/incompatible-browser.js` in the DOM on staging.va.gov

![image](https://user-images.githubusercontent.com/6130520/91587102-ee529600-e91b-11ea-816a-d7596205e225.png)

**Comment by billfienberg** [comment]
Closing this ticket after documenting which scripts are inlined and/or already used by Webpack.
