### ISSUE TITLE
Phase Two: Improve Yes/No Helpful Data in Support Responses Doc

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#79467]
## Description 
In each support ticket in the Slack #vfs-platform-support channel, we auto respond with documentation. Users can then note if the support article was helpful or not with a yes or no response. The data is then fed into [this spreadsheet in the Answer Analytics tab](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=1460450643).

If someone marks a 'no' as a response, we'd like to point them to this ticket to send feedback to the Platform Content Team. 
---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify steps to connect this [link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jknipes&labels=documentation-support%2C+platform-content-team%2C+pw-footer-feedback&projects=&template=platform-website-footer-feedback.md&title=) to the steps after a 'no' response is recorded.
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Duplicate ticket of: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/77806

Closing this one.
