### ISSUE TITLE
Desk research to understand disability submit experience 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#79462]
## Description
For both the 526ez and other relevant OCTO products, review the existing journeys and existing research / artifacts around submission and the post-submission experience.

## Task
- [x] Re scope to "Moment between when they hit submit and we establish claim in vbms", per [Emily in Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1712083884346289?thread_ts=1711719139.052369&cid=C053UDWMH7U)
- [x] **Review existing OCTO product research and design (include Slack channels, Github docs, Sharepoint content, relevant research share-outs). Research should include:**
    - [x]  Claims Status Tool **[@mengA6 starting here]**
        - [x]  Find time to [get clarifications from Julie Strothman](https://dsva.slack.com/archives/C053UDWMH7U/p1711744624160839?thread_ts=1711744000.264399&cid=C053UDWMH7U)
        - [x] Follow up with them on we learn re: when emails are triggered (moved this to a task in [Technical discovery to understand what emails Veterans receive for confirmation or failure of submission and when #79889](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79889))
        - [x]  Find existing paper mail notifications to Veterans after submitting a 526 - ask Disability Benefits Crew [OBA partners](https://dsva.slack.com/archives/C053UDWMH7U/p1711983227230689?thread_ts=1711744000.264399&cid=C053UDWMH7U), Andrew Gray and David Reis (on agenda for 4/2 VBA sync) - in progress. David to get back with info. [Pinged in Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1712326990191919)
    - [X] My VA portal (Auth Ex) **[@evelynhilbrichdavis starting here]**
    - [X] Past 526ez research findings **[@evelynhilbrichdavis starting here]**
    - [x] VA notify team
    - [x] Veteran Facing forms team - connect on their [Show status of form submissions to users](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170) work - Slack Channel: [#form-evidence-submission-status](https://dsva.slack.com/archives/C06R2BZKT62) @mengA6 

## Acceptance criteria
- [x] Relevant findings from existing research gathered for easy future reference
- [x] Touchpoints that cross product lines identified
    - [x] Communication established with other teams for easy collaboration

**Comment by evelynhilbrichdavis** [comment]
[The Mural Board for submit/post-submit discovery](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?sender=u56bc6ddb4215a92830844228)

**Comment by mengA6** [comment]
Got some [docs about the Claims Status Tool](https://dsva.slack.com/archives/C04KHCT3ZMY/p1711641878963709?thread_ts=1711641594.321239&cid=C04KHCT3ZMY) from Julie Strothman to review. Also of note, that team's contract is spinning down this week.

**Comment by evelynhilbrichdavis** [comment]
[Thread with Auth Ex Team (My VA). ](https://dsva.slack.com/archives/C909ZG2BB/p1711644069159019) 
They have some in-progress thinking right now but will be more ready to speak next week (4/1).

**Comment by mengA6** [comment]
Outstanding loose ends (also linked in the description)

1. David still awaiting info from another source on paper mail communications ([Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1712326990191919))
2. Emily to invite us to a new Slack channel to discuss [Veteran Facing Forms team's work on showing status of form submissions](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170), per [Slack](https://agilesix.slack.com/archives/C04MJV66ZPC/p1712254297126279?thread_ts=1712253850.377569&cid=C04MJV66ZPC)

**Comment by evelynhilbrichdavis** [comment]
On the agenda for VBA check-in for 4/16

**Comment by mengA6** [comment]
per [4/16 VBA sync](https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#heading=h.5y9awfwjne3p), David has an example of a letter acknowledging that a claim has been established but needs to redact PII from it before sending. We suspect this is sent before ancillary jobs complete, so it could be falsely saying a claim is established when it isn't fully so.

**Comment by mengA6** [comment]
We got a sample of the paper letter [in our working Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?wid=0-1713363417486) and some questions answered by David in [this Slack thread](https://dsva.slack.com/archives/C053UDWMH7U/p1712326990191919).
