### ISSUE TITLE
IA Tracker: Pension Form Sub-URLs

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#79488]
### Description

The Pension form was brought over to the modernized site and the sub-URLs were kept the same. These are out of date and so we  are making recommendations to the sub-URL structure.

#### Steps in process
- [x] Draft sub-URLs - *in progress*
- [x] Share with Mikki
- [x] Make edits as needed
- [x] Share with team

### Work needed

- List of sub-URLs

## Acceptance Criteria
- [x] Feedback is shared with product team in Intake Ticket.

**Comment by jennymayoco** [comment]
Moving to blocked as Mikki is currently drafting guidelines. Once done, we can review the proposed URLs alongside the doc

**Comment by jennymayoco** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1A7xJ2JESNNL-olJzMSkt9tN9-xY-foB8LD2D_I0o01Q/edit?gid=0#gid=0) has been shared with the team.
