### ISSUE TITLE
Update Style Guide with Supported and Unsupported Features

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#79497]
While working on the tip of the sprint about how the TOC macro in Confluence is not supported by Scroll Viewport -- and therefore doesn't appear on the PW-- I realized that there is no info in our style guide about it. 

We need to update the style guide to inform users that some Confluence features will not appear on the PW. 

### TASKS

- [x] Write new language
- [x] Find place for it on Style Guide
- [x] Put language in Style Guide
- [x] Be sure to provide links to relevant docs

### DEFINITION OF DONE

- [x] Style Guide contains info about Supported and Unsupported Features

**Comment by BSmolensky** [comment]
Style Guide has been updated: https://vfs.atlassian.net/wiki/spaces/AP/pages/622362663/Formatting+and+organization#Supported-and-Unsupported-Features

Ticket is ready to be closed.

**Comment by jknipes** [comment]
Moving to _done_
