### ISSUE TITLE
Audit Platform Website for Mention of Sketch tool

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79512]
## Issue Description
Use of the Sketch tool by Platform has been discontinued and is replaced by Figma. 
Platform Website contains several mentions of Sketch, including a [video](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome).
An initial search for Sketch yields [28 pages](https://depo-platform-documentation.scrollhelp.site/search.html?l=&max=10&ol=&q=sketch&s=&start=0).
Content Team will need to audit the website for all references to Sketch and potentially replace these with guidance on Figma 

---
## Tasks
- [x] Joe identify SME for guidance  
- [x] Identify all references to Sketch
- [x] Determine steps with SME for replacing references with Figma
- [x] Create an Edit ticket for the work

## Acceptance Criteria
- [x] All references to Sketch will be identified
- [x] Steps for replacing these references will be determined

## SMEs
@danbrady 
@babsdenney 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
cc: @babsdenney

**Comment by jknipes** [comment]
Plan this work for upcoming sprint beg. 5/9

**Comment by caw310** [comment]
@jknipes I don't think there should be too many mentions of Sketch on the platform site. DST usually keeps all VADS information on design.va.gov. If information is needed, @babsdenney or @danbrady can help with that.

**Comment by laucon** [comment]
I'm linking this spreadsheet here: https://docs.google.com/spreadsheets/d/1v1BaQ6hg1xCMXZCsQa1ERBIN1kvPui05Ct__8WsdoBs/edit#gid=0
