### ISSUE TITLE
(Jill) Demo/shadow deployment for Cheryl

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79511]
## Tasks
- [x] Coordinate with Cheryl your demo/shadow day
- [x] Account for additional time to provide her with context

## Acceptance Criteria
- [x] Cheryl will have shadowed how to do deploy

**Comment by jknipes** [comment]
Cheryl will shadow on Monday 4/15

**Comment by CherylEvans** [comment]
@jknipes @taylojill Thank you, Jill, for your very instructive training!

**Comment by taylojill** [comment]
You're welcome @CherylEvans!
