### ISSUE TITLE
How to Guide - DOMO Dashboard Access

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#79522]
## Issue Description
_As a User I need to have a way to request access and view the Veteran Support DOMO dashboard so I can view the data.
---
## Tasks
- [x] _Create How To Guide 
- [x] Review How To Guide 
- [x] Add to Veteran Support Canvas link on Slack channel 
- [ ] Content review for platform page
 
- [ ] 
## Acceptance Criteria
 - [ ] **Scenario: Requesting access to the DOMO dashboard**
   - Given the user is not yet granted access to the Veteran Support DOMO dashboard
   - When the user follows the How To Guide to request access
   - Then the user should receive instructions on how to request access and be able to view the dashboard
- [ ] **Scenario: Viewing the DOMO dashboard after access is granted**
   - Given the user has been granted access to the Veteran Support DOMO dashboard
   - When the user follows the How To Guide to access the dashboard
   - Then the user should be able to view the data on the dashboard
- [ ] **Scenario: How To Guide is added to the Slack channel and platform page**
   - Given the How To Guide is complete and reviewed
   - When the How To Guide is added to the Veteran Support Slack channel and platform page
   - Then the guide should be easily accessible for users to follow
- [ ] **Scenario: How To Guide is attached to a Milestone, Epic, and labeled with Team and Practice Area**
   - Given the issue is part of a larger project
   - When the issue is attached to a Milestone, Epic, and labeled with Team and Practice Area
   - Then the issue should be organized and easily identifiable within the project
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by UXCamG** [comment]
@starlow00 @newworld2616 I have created [a draft](https://docs.google.com/document/d/1sjW1m3TS3OO2ygWHB7istL-XqEWasMr4I1F4X_sGQ_g/edit?usp=sharing) for Salesforce dashboard.

**Comment by starlow00** [comment]
Draft reviewed, looks good with only minor changes for flow.
