### ISSUE TITLE
Atlas: Prod <-> Dev data parity

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#79536]
A prod db dump needs to be imported into the dev db. Terraform can do this during creation, but can it do it for an update, or does the RDS instance need to be recreated?

## Tasks
- [x] Research if import of Prod dump is possible
- [x] If Prod dump is not possible, recreate cluster
- [ ] Internal testing with Lindsey, Ryan or Rachal

## Success Metrics
- [ ] Informal comparison between dev and prod environments that will result in Internal testing is completed successfully

## Acceptance Criteria
- [ ] Testing is completed
- [ ] Dev environment is updated successfully

**Comment by flooose** [comment]
The following lines were temporarily added to the [aws_db_instance block](https://meet.google.com/tsi-cwqx-fjw?authuser=0&hs=122) to reseed the database:

```terraform
  restore_to_point_in_time {
    source_db_instance_identifier = "platform-atlas-prod"
    source_db_instance_automated_backups_arn = "arn:aws-us-gov:rds:us-gov-west-1:008577686731:snapshot:rds:platform-atlas-prod-2024-04-18-13-02"
  }
```

**Comment by jennb33** [comment]
@rmtolmach to review the Dev and Prod parity before 12:45pm so that we can close this ticket before the Sprint closes.

**Comment by rmtolmach** [comment]
@flooose based on the number of individuals, they don't seem to match
https://dev.va.gov/atlas/product_directory/team_members
https://www.va.gov/atlas/product_directory/team_members
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/39d52791-0402-4714-87f8-35f6ba3eb7ce)

**Comment by jennb33** [comment]
Final work was duplicated into ticket [81554](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/81554) and will be worked on in Sprint 53
