### ISSUE TITLE
[CST] Finding claim letters in CST

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#79548]
## Value Statement
**_As a_** veteran looking for official correspondence for an OPEN claim in CST
**_I want to_** be able to find the claim notification letters feature in CST
**_So that_** I can download development letters. 

---
## Background Context

The time has come to build the claim letters feature into the main CST information architecture. 

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- What's the state for when there's no letter available? 
- Do users get access to the claim letters section if there are no letters for them available? 
- What is the UI state for when there is a new notice (any notice)? 
- How to they to to the claim letter section under different scenarios (such as having a 5103 notice available)?

## Tasks
- [ ] _Determine success metrics for design approach_
- [ ] _Design ideation_
- [ ] _Cross functional team feedback and revisions_
- [ ] _Enablement team feedback_
- [ ] _CAIA feedback_
- [ ] _Design Revisions_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Any user with a letter in the claim letters section of CST can navigate to the letters section of CST_

**Comment by jstrothman** [comment]
Closing as we previously added a link in the claim status landing page to the claim letters.
