### ISSUE TITLE
[CST] [Technical Discovery] Determine what first-party evidence requests should get language updates 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#79547]
## Background Context

We now track data in DD on what evidence request information comes through in CST. We can see what the most popular first-party requests are. We need to conduct an analysis of the top requests and determine which are not providing enough information to the veteran to understand and/or take action on the request. 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Create a list of evidence requests from DD sorted by number of transactions_
- [ ] _Look at the top ten items and work with Enablement Team and VBA SMEs to determine what they are and the least strong descriptions_
- [ ] _Determine what CST should actually say for those specific requests_
- [ ] Create individual user stories for each request

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] User stories for each identified evidence request opportunity created and attached to the same epic this ticket is attached to.
- [ ] Each user story is sufficiently groomed to allow the team to size them with sufficient confidence

**Comment by jerekshoe** [comment]
These are the top 10 according to DataDog:
![Screenshot 2024-04-02 at 4 00 24 PM (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/28c8230f-9ada-4928-ae4e-b6543fc0bbca)

**Comment by jerekshoe** [comment]
Looks like the top 10 in order:
1) PMR Pending
2) HAIMS STR Request
3) Automated 5103 Notice Response
4) Attorney Fee
5) 21-4142/21-4142a
6) Proof of service (DD214, etc.)
7) PTSD - Need stressor details/med evid of stressful incdnt
8) Employment info needed - 21-4192 to veteran
9) RV1 - Reserve Records Request
10) Exam Request - Processing

**Comment by jerekshoe** [comment]
I created a claim for user 23 and started adding the top 10 tracked items from above to the claim here: https://staging.va.gov/track-claims/your-claims/600494815/files. I'm not sure how to get a Exam Request - Processing or Attorney Fee created currently and am going to add the top 2 tomorrow so that they were opened on different dates

**Comment by jerekshoe** [comment]
I was able to get 6 of the 10 tracked item types to show up for a claim in staging. The 4 I couldn't get are:
1) HAIMS STR Request - I was able to add it to the claim in VBMS, but it does not show up for the claim in staging
2) Attorney Fee - I was not able to find this tracked item type in VBMS
3) RV1 - Reserve Records Request - I was able to add it to the claim in VBMS, but it does not show up for the claim in staging
4) Exam Request - Processing - I was able to add this to the claim in VBMS by setting up an exam, but it does not show up for the claim in staging
