### ISSUE TITLE
Catch up on 2024 GH research archives

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#79560]
## Description of UX Tasks
UX team's research documents haven't all been making it into GH the past couple months. We want to take a moment to make sure all our work is stored/archived in [our team folder in GH](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research)

## Tasks
- [ ] [Request and Support process work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research/2024-01%20Identity%20Support%20Process)
   - [ ] readme filled: linked docs, timeline, background, and research goals
   - [ ] research plan
   - [ ] research findings
   - [ ]  supporting artifacts
- [ ] [SiS work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research/2024-01%20Sign%20in%20Service)
   - [ ] readme filled: linked docs, timeline, background, and research goals
   - [ ] research plan
   - [ ] research findings
   - [ ] supporting artifacts
- [ ] [SLO work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Research/2024-03%20Service%20Level%20Objectives)
   - [ ] readme filled: linked docs, timeline, background, and research goals
   - [ ] research plan
   - [ ] research findings
   - [ ] supporting artifacts

## Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
