### ISSUE TITLE
Copy of Map Upstream Services: Create Update Documentation of Services

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79570]
## Issue Description
We need a comprehensive list of the upstream services that Vets API makes call-outs to. Existing documentation and diagrams exist, but they're stale and outdated. The various sources of truth should be reviewed and an updated list needs to be created and documented. 

---
## Tasks
- [ ] Update FWD Proxy Configs existing documentation in ticket XX 
- [ ] Update REV Proxy Configs existing documentation in ticket XX 
- [ ] Update Rails Code existing documentation in ticket XX 
- [ ] Update Breakers GEM existing documentation in ticket XX 
- [ ] Update Monitors existing documentation in ticket XX 

## Acceptance Criteria
- [ ] Updated documentation and diagrams for Platform Product upstream services that can be shared to all VA Platform stakeholders.

**Comment by jennb33** [comment]
Talk to @LindseySaari about where this information should live, and add to the ticket, please inform @jennb33 as well.

**Comment by jennb33** [comment]
7/10 - this is in progress. Outdated code. Each individual files being adjusted as needed. Getting some new diagrams, more clearly defined and updated in 2024. Updated documentation. Should have diagram updated 7/10 and the documentation updated 7/11. Look at [this nightmare](https://vfs.atlassian.net/wiki/spaces/IET/pages/1947992080/Upstream+APIs+Diagrams) - very detailed. This is another [great diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/Updated%20External%20Service%20Topology.png).

**Comment by rjohnson2011** [comment]
Working on rewriting script for changes in CODEOWNERS and mapping top level directory to visualize via Graphviz.

**Comment by rjohnson2011** [comment]
Putting this on hold to work on higher priority ticket.
