### ISSUE TITLE
Copy of Map Upstream Services: Review FWD Proxy configurations

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79579]
## Issue Description
Because there is a need for an updated and comprehensive list of the upstream services that Vets API makes call-outs to, it is necessary to review the existing documentation and diagrams and updated or recreate the documents. 
They should be stored here (space **TBD**). 
The new documents should be reviewed by the cohort to ensure that there are no critical elements missing for FWD Proxy. 

---
## Tasks
- [ ] Review existing documentation for FWD Proxy Configs 
- [ ] Review existing diagrams for FWD Proxy Configs 
- [ ] Update existing documentation for FWD Proxy Configs 
- [ ] Update existing diagrams for FWD Proxy Configs 
- [ ] Archive existing documentation for FWD Proxy Configs; include URL in comments below
- [ ] Archive existing diagrams for FWD Proxy Configs; include URL in comments below

## Acceptance Criteria
- [ ] Updated documentation and diagrams for FWD Proxy Configs used Platform Product upstream services that can be shared to all VA Platform stakeholders.
