### ISSUE TITLE
Map Upstream Services: Review REV Proxy configurations

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79577]
## Issue Description
Because there is a need for an updated and comprehensive list of the upstream services that Vets API makes call-outs to, it is necessary to review the existing documentation and diagrams and update or recreate the documents. 
They should be stored here (space **TBD**). 
The new documents should be reviewed by the cohort to ensure that there are no critical elements missing for REV Proxy. 

Review [this document ](https://docs.google.com/spreadsheets/d/1cEBdUUqRW1cgVRLcbRUwOMhZewy9fRLU0gRGSITfuEc/edit#gid=803968964) for the particular data points that need to be captured for this Upstream Service. 

---
## Tasks
- [ ] Review existing documentation for REV Proxy Configs 
- [ ] Review existing diagrams for REV Proxy Configs 
- [ ] Update existing documentation for REV Proxy Configs 
- [ ] Update existing diagrams for REV Proxy Configs 
- [ ] Archive existing documentation for REV Proxy Configs; include URL in comments below
- [ ] Archive existing diagrams for REV Proxy Configs; include URL in comments below

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [ ] Updated documentation and diagrams for REV Proxy Configs used Platform Product upstream services that can be shared to all VA Platform stakeholders.

**Comment by jennb33** [comment]
Reviewed in Sprint Refinement meeting on 4/22/2024; it was determined that this ticket does not apply to the Upstream services because the Rev Proxy does not play a role in the Upstream services discovery.
