### ISSUE TITLE
Copy of Where should the FDG space exist within Platform Docs?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#79598]
## Purpose
Another tenent from our [own internal standards](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2210660360/How+to+Service+Design+Your+Tool+Service#1.-Make-it-easy-to-find-your-service) is findability.  Where is the best spot within Platform Docs IA for users to find this when looking, or wandering?

Let's also discuss this w/ Platform Content

## Tasks
- [ ] Consider location options
- [ ] Discuss options w/ team to filter toward a preferred option
- [ ] Document choices and reasoning
- [ ] Meet w/ PCT or PCT representative to discuss the Guide and recommend a location
- [ ] Record thinking and direction from PCT
- [ ] Review decision w/ PO that may have oversight of the intended space
  
## Acceptance Criteria
- [ ] choice documented
- [ ] PO signoff
