### ISSUE TITLE
Request to provide VBS with Swagger documentation for VODA endpoint

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#79592]
## Issue Description

Per 3/22/24 email from John Skarvelis (PM with VBS), they are requesting the following:

_"As part of our upcoming work on delivering the account summary fields for statements, the VBS team will need the swagger doc for the VODA endpoint. We will need this so that we can update our client and be able to send the information in the format that the VODA server expects. Please let me know if you have any questions.  Thanks!"_

---
## Tasks
- [ ] Create document for VBS to include VODA endpoint and email to John Skarvelis and team

## Acceptance Criteria
- [ ] Document has been created 
- [ ] VODA has confirmed that the information VGS is sending is in an acceptable format 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kjsuarez** [comment]
https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/medical_copays/sendNewStatementsNotifications
