### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#79596]
## Purpose
What resources would be helpful/useful to users?

We know a number of them exist in various locations across VA resources (Github, Confluence, Platform Docs, etc).  What are they, and which ones should we reference, or simply link to in a meaningful way?  The idea being that any useful existing resources get pulled under the FDG umbrella.

## Tasks
- [ ] Identify useful existent resources (paste in here)
- [ ] Identify useful non-existent resources
- [ ] Determine which to link to
- [ ] Determine which to build out further

## Acceptance Criteria
- [ ] Document findings
