### ISSUE TITLE
[UX/Team] 10-10EZR: Expand on designs for Review/Subtask and Choose Your Own Adventure and a proposal for MVP

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#79627]
As a Veteran, I would like to be able to update my information viewing as few screens as possible so that I can make the changes I need and not get bogged down reviewing things I don't need to change.

- [x] Flesh out the two designs Alex/Hieu discussed--one for Choose Your Own Adventure (CYOA), one for Review/Subtask (RS)
- [x] Come up with ways that these two designs can be implemented iteratively
- [x] Review the MVP/Iterative approach with team, and get feedback
- [x] Make tweaks as needed based on team feedback
- [x] **Success: We have designs for CYOA and RS fleshed out, and we have an idea for how we can implement them iteratively**

**AS Note:** Next step will be presenting these to Patrick.

**Comment by IMHieuVo** [comment]
[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710276256679/d5767a41a32940019281bfb50f883e1265e5c8bd?sender=ubf5503bf47b6eb1e92730053)
[Figma](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=1809%3A84420&mode=design&t=sghAvvhnrvAQHLHT-1)

**Comment by IMHieuVo** [comment]
Summary:

- The idealized flow: allows the user to upgrade any information they wish but there are (2) constraints preventing this from happening: 1) All information has to be reviewed/updated before submission per PRA Paper Reduction Act. 2) All information within the form has to be similar to EZR’s paper form. 
- Due to the constraints, a Veteran with a disability rate of 40% or under must go through at least 24 screens to update any of their information.
- In an attempt to reduce the Veteran’s burden while working under the constraints, we explored (2) possible flow options: Choose-your-own-adventure and Confirmation.
- Within the Choose-your-own-adventure flow, the user can choose any sub-section to update their information. One major drawback is that they still have to review the rest of the information despite going on the form for one thing (this is a potential pain point).
  - The Accordion pattern can be used as a reference point but still requires a custom pattern.
- Within the Confirmation flow, information is surfaced on section pages where the user can review, edit, and move forward as needed. While this flow still involves the user reviewing all of the information. Recommend this flow for EZR v2.
  - The Multi-page list and loop card that is already utilized in some sections is a good contender to be further developed. 
   - Does not require going through the collaboration cycle
   - Small and quick release since each section can be developed independently
   - Laborious process since Dev needs to manually validate all inputs in every section
