### ISSUE TITLE
DR | Unauthenticated start page sign in behavior

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#79637]
## Value Statement
**_As a_**  Veteran not logged in on the HLR/SC start page
**_I want to_** not see a modal regarding losing information when I attempt to log in
**_So that_** I don't get confused by the message

## Background Context

If you're not logged in and jump directly to the [Higher Level Review start page](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start) or [Supplemental Claim start page](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/start), then click the "Sign in" button in the header, you'll see a warning modal. The modal warns that you'll lose information even though you're not logged in. Demonstrated in this video:

https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/7cefe265-13d9-4f4c-b565-49558959ea95

It appears that the `start` path isn't included in the in progress form path helper, and can be fixed as follows:

~Update [src/platform/forms/helpers.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/helpers.js#L64-L74) as follows~:

```diff
 export function isInProgressPath(pathName, additionalNonFormPaths = []) {
   const trimmedPathname = pathName.replace(/\/$/, '');
   const nonFormPaths = [
     'introduction',
     'confirmation',
     'form-saved',
     'error',
+    'start',
     ...additionalNonFormPaths,
   ];
```

**Update**: Ignore the above, instead we need to add the `'start'` path to the form config `additionalRoutes` array. Changing the above would cause issues for forms that don't have a subtask/wizard start page

## Tasks
- [ ] Add 'start' to in progress path
- [ ] Update unit & e2e tests
- [ ] Update alert to use web component (maybe out of scope?)

## Acceptance Criteria
- [ ] Logging in from start page does not show the lose information modal
- [ ] All tests passing

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [x] Meets acceptance criteria
- [x] Code reviewed (internal)
- [x] Submitted to staging
- [x] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
Switching to a different approach to fixing it. Will add additional route for DR forms so as not to impact other forms.

**Comment by Mottie** [comment]
Ready to be tested in staging

**Comment by eileen-coforma** [comment]
Validated in parking lot
