### ISSUE TITLE
Discovery Vets API: Datadog Source Code Integration

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#79632]
## Description

Exploring alternatives to Sentry for error logging, we've discovered that Datadog offers the capability to view stack traces for error logs, similar to Sentry. ([See View Trace Details on this error log](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20status%3Aerror&cols=host%2Cservice&event=AgAAAY6K-Wp52dG7nAAAAAAAAAAYAAAAAEFZNkstVzk2QUFDLXpobzYwbjZqRVFCMQAAACQAAAAAMDE4ZThhZjktODA4Ni00YWRkLWE2YjMtNTNlYTJiYmJhY2Q1&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=4361684514522207690&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1711642186104&to_ts=1711728586104&live=true)). Additionally, Datadog provides an APM feature for source code integration. ([See missing link to repository here](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20service%3A%22check-in%22%20resource_name%3A%22CheckIn%3A%3AV2%3A%3APatientCheckInsController%23show%22%20host%3A%22i-0dc4e3bbf34a4fe16%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=194008368741708849&spanType=service-entry&spanViewType=errors&trace=d20b8e2965c37c2f&traceID=2132272697721308434&traceQuery=&view=spans&start=1711728584740&end=1711728644740&paused=true)). This feature could enhance error investigation by offering direct links to the relevant sections of the Vets API repository within the error logs. [See setup configuration.](https://vagov.ddog-gov.com/source-code/setup/apm) Integrating source code with Datadog's APM might be a valuable step to consider for improved error analysis and debugging.

## Tasks
- [ ] Evaluate Datadog's APM and Source Code Integration Feature
- [ ] Discover if any other application use this feature
- [ ] Create follow up ticket for implementation (if necessary)

## AC
- [ ] We've evaluated the Source Code Integration Feature 
- [ ] Follow up implementation ticket created

**Comment by Kshitiz-devops** [comment]
Detailed Steps for Ruby implementation:

Step 1: Update the Dockerfile
We'll start by adding build arguments to our Dockerfile. These will capture the Git repository URL and the current commit SHA. Add the following lines to your Dockerfile:

dockerfile

```
# Define build-time arguments for Git repository URL and commit SHA
ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA

# Set an environment variable that Datadog can use to tag telemetry
ENV DD_TAGS="git.repository_url:${DD_GIT_REPOSITORY_URL},git.commit.sha:${DD_GIT_COMMIT_SHA}"
```


These instructions set up build-time arguments which are then converted into an environment variable, DD_TAGS. This environment variable will store our version control information in a format that Datadog can use to tag telemetry data.

Step 2: Building the Docker Image
Next, we'll build our Docker image and pass in the necessary version control information as arguments. This is crucial for ensuring each image build can be accurately traced back to its codebase state. Use the following command in your terminal or CI/CD pipeline:

bash

```
docker build . \
 -t my-application \
 --build-arg DD_GIT_REPOSITORY_URL=<git-provider.example/me/my-repo> \
 --build-arg DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)
```

Replace <git-provider.example/me/my-repo> with the actual URL of your Git repository. The $(git rev-parse HEAD) command fetches the latest commit SHA from your repository, ensuring your build is tagged with the most recent codebase state.

Step 3: Deploy and Run
With the build complete, you can run your Docker container as usual. The environment variable containing the Git details is now embedded within the container.


Step 4: Validation in Datadog
Once application is deployed, log into Datadog to confirm that the telemetry data is being tagged correctly. We should see git.repository_url and git.commit.sha tags accompanying metrics, logs, and traces, which help in tracing issues back to their source changes.

**Comment by LindseySaari** [comment]
The steps detailed above look good and we can proceed with the implementation of this work! Nice job @Kshitiz-devops

**Comment by Kshitiz-devops** [comment]
After the change in code will need to complete steps in datadog to create github app: https://vagov.ddog-gov.com/source-code/setup/apm
