### ISSUE TITLE
Update ClamAV version

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#79631]
### Summary

Clamav Version 1.0.0-1.0.4 contain security vulnerabilities. The version should be upgraded to 1.3.0. This version is no longer supported, https://docs.clamav.net/faq/faq-eol.html. This might have something to do with `LibClamAV Warning: *** The virus database is older than 7 days! ***`

### Tasks

- [x] Test locally
- [x] Test in dev
- [x] Test in staging
- [x] Deploy to prod

**Comment by RachalCassity** [comment]
@jennb33 @LindseySaari 

ClamAV version was upgraded to 1.3.0. LibClamav errors have been fixed. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddff8fe3b5de222885442222c4ad61f04b0fb644/Screenshot%202024-04-01%20at%2011.12.22%20AM.png" alt="Screenshot 2024-04-01 at 11.12.22 AM.png" />

We are still seeing WARNING: `FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).` errors. I believe this is due to an existing freshclam.dat file

**Comment by RachalCassity** [comment]
Monitoring logs until the end of the sprint.
