### ISSUE TITLE
[CDP] Reported missing date on debt card

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#79636]
## Description
During a recent user test session we noticed the payment due by date was missing from the debt card. We have conditional rendering checks in place to prevent a catastrophic failure of the component, but we should see what went wrong here and try to test and make sure it's not happening to others. 

It could be helpful to make some unit tests for the components to make sure the components load the data after any component/styling updates. It could also be helpful to set up sentry logging in case the data we're expecting regularly fails to come through (like a missing date field). 

### Screenshots
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlFoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--651c35ba70d5157e504bc2a5f6c14e1fe611d0e7/image.png" alt="image.png" />

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlVoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa7dcede217c677c1b260f3ea961ebabf3345483/image.png" alt="image.png" />

### Notes so far:

- [Message that brought the bug to our attention](https://dsva.slack.com/archives/CPE4AJ6Q0/p1711649932782659)

- [Interesting comment ](https://github.com/department-of-veterans-affairs/vets-website/blob/029a4adb41afe7eac182490ad204c290d84a9c55/src/applications/combined-debt-portal/debt-letters/const/diary-codes/debtSummaryCardContent.js#L89)on _missing_ missing date functionality

**Some FE notes:**
>  The flow goes `debtCardSubHeading` calls `debtSummaryText` which uses `mostRecentHistory?.date`, to populate the `endDate` function we use in the` debtSummaryCardContent.js` to add x days to it to get the value there. Which comes from the `head(debt?.debtHistory)`. If it doesn't have a `debtHistory`  somehow this can theoretically happen

## Tasks
- [x] Investigate missing date
- [x] Determine LOE to generate some unit tests for the component & create tickets if necessary
- [x] Determine LOE to create Sentry logging to cover required fields for rendering debt/copay data

## Acceptance criteria

- [x] Date issue is fixed if it's a recurring issue
- [x] Necessary follow on work such as unit tests and sentry logging is accounted for

## Testing
- [x] Try and load debt cards and get date to not show up
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by amponce** [comment]
Draft PR is up

https://github.com/department-of-veterans-affairs/vets-website/pull/29510

### Todo

- Talk to design to figure out the best message for missing dates
- Follow up with kevin on Argo output for dates to see if we can identify any missing dates from `debtHistory`

**Comment by amponce** [comment]
I followed up with Kevin and Joe.

Joe will review the language with Denise and the Design team for situations where a date is not available.

Kevin is on standby to help us brute force an Argo query if needed. We're going to try an alternate route with Sentry to capture information specific to users without debt history to get a better understanding of the diary codes.

**Comment by josephrlee** [comment]
Here is a [slack thread](https://dsva.slack.com/archives/G01KBHYEXV2/p1714774734124819) for what the potential error message will be regarding the missing date.
