### ISSUE TITLE
[Design] 10-10EZ - Reg Only: MVP User Flow

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#79634]
## Background
After conducting a couple research sessions, getting a better understanding of how the staff works through the Reg Only process, and obtaining volumes of various Registration Only scenarios (Service Connected & Mental Health), we have a better idea of how we would like to approach adding the Reg Only path to the 10-10EZ.

The 1010 team originally proposed an MVP scope of handling all service-connected Veterans registration pathway. When sharing this with our PO on 3/27, he suggested scaling back much further to 10-40% only and driving that group to download, fill out, and mail in a paper application and check "registration only."

The team is in agreement that we can pull back the scope of MVP further but would still like to deliver a digital solution for registration. We are now iterating on a user flow to demonstrate what functionality will be present in the MVP version of registration. This ticket is to capture any versions we need to go through before the team and VA stakeholders are all on board with the revised approach.

- [Planning Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702079427539/3151e3fa9a7eed55d21d5e39cb981938c5d2484a?sender=uadf1ed7fe7c76f0914967329)
- [Figma early wireframes drafts](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=86-36817&mode=design&t=JwZY1vr9IwWyhBez-0)
- [WIP MVP user flow mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487582087/34c3dab41845b8a2ca33afa97e05671703ca8395?sender=ud5c82d652d231345efaf6060)

## Tasks
- [x] Meet and revise user flow to reflect team decision to focus on 10-40% SC registration - as low-lift as possible (AA & JS)
- [x] Review with team for feedback (AA & JS)
- [x] Incorporate any feedback adjustments (AA & JS)
- [x] Review with engineers for technical feasibility (AA & JS)
- [x] Review with Kristen for feedback (AA & JS)
- [x] Create a doc for Patrick comparing his recommended approach to the one we recommend with reasons why (AA & JS)
- [x] Share async with Patrick with option to schedule a meeting to review together (Emily?)
- [x] Incorporate any feedback adjustments from Patrick (AA & JS)

## Acceptance Criteria
- The user flow for the MVP of registration is finalized: Reviewed and approved by the 1010 team, Kristen McConnell, and Patrick Bateman, and designers can move on to wireframes

**Comment by jessicastump** [comment]
Started updating the [WIP User Flow Mural board here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487582087/34c3dab41845b8a2ca33afa97e05671703ca8395?sender=uadf1ed7fe7c76f0914967329) - wanted to capture what we chatted about in the weekly design sync with Kristen. Going with mvp 1.0 (an alert to register via other methods) with the HEC notes in the red bubbles. Goal - implement quickly and gather tracking via website analytics.  For the 2.0 user flows to investigate, working on cleaning that up too and adding notes about HOW we want to go about investigating that flow while data gathers on version 1.0.
