### ISSUE TITLE
Update Test User Dashboard guide

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79651]
During Platform Team Retro 49 it was mentioned that the [Test User Dashboard](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-user-dashboard-guide) is currently unsupported by Platform. We should add verbiage mentioning that this product is unsupported.

## Page on Platform Website:
[HERE](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-user-dashboard-guide)

## Suggested Guidance from SME (Clint Little)

- Notice can say "it is currently unsupported by Platform" or we just say "it is currently unsupported". 
- One additional note  "we know this is a need and an item is being actively worked"
### Experience Team Slack Channel: 
#ves-developer-experience-team

### Slack Thread

- https://dsva.slack.com/archives/C05M78LBUQM/p1715263297424389

## Tasks:

- [x] Contact Clint Little for guidance on composing the notice  (will this require a whole new page or just a box at the top of existing page?)
- [x] Reach out to Experience Team re: whether & how to mention their product in the notice
- [x] Based on Suggested Guidance, compose draft notice for top of page
- [x] Clint Little for approval (See Slack Thread)
- [x] Patrick Vinograd for approval (See Slack Thread)
- [x] Schedule page for deployment

## Acceptance Criteria:
- [x] Page is ready for deployment

**Comment by jknipes** [comment]
Duplicate ticket

**Comment by jknipes** [comment]
Per Shira Goodman:
Clint said that TUD is currently "unsupported by Platform", so I was  suggesting we add a note or something to [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-user-dashboard-guide) stating that this product is unsupported and to use with caution.

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79651?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79651?planning-poker) with Zenhub @CherylEvans

**Comment by jknipes** [comment]
Final estimate lowered to a 5, as the description of this issue has been updated to a reduced work load

**Comment by jknipes** [comment]
This ticket is currently in our Backlog pending approved language
cc: @little-oddball @patrickvinograd

**Comment by CherylEvans** [comment]
@little-oddball @patrickvinograd Good morning! I am working on this ticket and want to present my first draft of the language addition at the top of [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-user-dashboard-guide).

"The Platform doesn't currently support the VA.gov-maintained catalog of TUD users. We know a solution is needed and are quickly working towards one."

I recommend leading the page with this phrasing, possibly using italics or a bold font for emphasis.

Please provide your comments and suggestions, and I'll rework it as needed. Thank you!

**Comment by CherylEvans** [comment]
Slack thread with Clint and Peter's approval: [LINK](https://dsva.slack.com/archives/CL181NRJQ/p1716219022012879)

**Comment by CherylEvans** [comment]
@jknipes @little-oddball @patrickvinograd 
The Platform Website [TUD page](https://depo-platform-documentation.scrollhelp.site/developer-docs/test-user-dashboard-guide) now reflects the updated language.   
Thank you to everyone involved; closing ticket.
