### ISSUE TITLE
IA Tracker: VYE for GI Bill Benefits

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#79666]
### Description
Veterans utilizing education benefits through the MGIB-Active Duty (Chapter 30), MGIB Selected Reserve (Chapter 1606), Reserve Educational Assistance Program (REAP, Chapter 1607), or Veterans Retraining Assistance Program (VRAP) currently verify their benefits with WAVE. This does not apply to Post-9/11 benefits. WAVE is being replaced by this new form, Verify Your Enrollment (VYE). This a separate from the current VYE for Post-9/11 found at `www.va.gov/education/verify-school-enrollment/enrollment-verifications/`.

### Links

- Intake Ticket #68205 

### Team

- Team Name: Verify Your Enrollment (VYE)
- Designer: Ryan Gray
- Product Manager: Jason Wolf and Cassidy Beach
- Slack (_optional_): 

### Timeline

- Design Intent completed 10/19/23
- Midpoint Review completed 12/4/23
- Staging Review TBD, potentially in next month or two with launch goal of 5/2024

---

### Work needed

- IA spec: Needed
- Feedback for product team: Needed

```[tasklist]
### IA deliverables
- [x] IA spec
- [ ] Feedback
```

## Acceptance Criteria
- [ ] Feedback is shared with product team in Intake Ticket.

**Comment by jennymayoco** [comment]
Prelim questions for team with responses:
1. *I realize Post-9/11 VYE is on a different payment system based on what I learned from watching the collab cycle recordings, but are there plans to integrate this new VYE with the current tool for Post-9/11 benefits: www.va.gov/education/verify-school-enrollment/enrollment-verifications/? Is there a way to host both on the same URL? Or to show only 1 benefit depending on which one a Veteran is enrolled in? If not, Sitewide IA can work you all to update the URL in staging so it's correct and specific to this GI bill benefit. We'll also want to ensure there's content on the static page so Veterans can distinguish between which tool applies to them.*

     There are no plans to integrate the new VYE with the current tool for Post-9/11 that I am aware of. I do not believe there is a way to host Post-9/11 and Montgomery GI Bill on the same URL since they fall under different chapters (Post-9/11 is Chapter 33 and MGIB is Chapter 30). [The Verify School Enrollment page](https://www.figma.com/file/B3Ds72oQhBZG1EtfffbAYk/VYE-Wireframes?type=design&node-id=42%3A4775&mode=design&t=L5r7QwVf34Fbp3J5-1) (VYE- Wireframe 3, the top-left mockup) lists Post-9/11 benefits on the top of the page and when you scroll down you see MGIB benefits, then it breaks off depending on which link the user selects. Once the user logs in they will be able to see whether or not they have to verify their enrollment for VYE.

2. *Is this related to [form 22-8979 student verification of enrollment](https://www.va.gov/find-forms/about-form-va-form-22-8979/)? If so, we'll want to add an entry point to the [about VA form page](https://www.va.gov/find-forms/about-form-va-form-22-8979/) and we'll also want to reference the PDF on the [static page](https://www.va.gov/education/verify-school-enrollment/), which Sitewide Content team (part of CAIA) can support with updating content.*

    Users have to submit Form 22-8979 if there are errors in their enrollment.

3. *Can you tell me more about Benefits Manager and how this tool is related to that?*
  
    Your Benefits Profile in VYE allows users to update their banking and address information. This is separate from the Benefits Manager used by the rest of VA.gov because BDN, the payment system attached to WAVE, does not connect to the one used by VA.gov.

6. *Are we able to add comments to the Figma designs?*
     
    There is a comment section on the right side of the page in Figma. Our team has yet to use the feature, so you're more than welcome to try it. If it does not work I can be reached on Slack @ Cassidy Beach or email at [cassidy.beach@va.gov](mailto:cassidy.beach@va.gov).

**Comment by jennymayoco** [comment]
Shared [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/mgib-verify-enrollment.md) with team.

Last steps:
- [ ] Create redirect ticket for https://www.va.gov/resources/gi-bill-wave-faqs/
- [ ] Update best bets by removing WAVE references

Moving to validate

**Comment by jennymayoco** [comment]
Pulled top search terms for the [static page](https://www.va.gov/education/verify-school-enrollment/). Since the top terms are already in the h1 and is a keyword in the existing best bet, we don't have any additional recommendations at this time.

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/78f3e02a-5441-4c8c-b21a-2bf9a57c1685)
