### ISSUE TITLE
[SPIKE] [ENG] Review referral and WellHive API specs

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79687]
## Tasks

- [ ] Review [referral user guides](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/functionality/referral#referral-documentation-ccra-and-hsrm)
- [ ] Review [WellHive API specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/functionality/wellhive/wellhive-specifications.md#wellhive-specifications)
- [ ] Identify questions about referral user guides (that can directed at Michael, until we have a meeting with VHA/VA CTB SMEs) 
- [ ] Identify questions about WellHive API specs for Ryan at WellHive
-
## AC

- [ ] Review documentation
- [ ] Prepare questions and be ready to ask on Tuesday's meeting
