### ISSUE TITLE
[Design] Create hi-fi userflow with DS components of "scheduling" portion of userflow

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79688]
## Tasks

- [ ] Create hi-fi userflow with DS components of "scheduling" portion of userflow. E.g., let's get an idea of the decision tree and what components and data will be shown on each page. Start with the first step of the decision tree, e.g., select specialty, and end with complete page.

## AC

- [ ] "Scheduling" portion of userflow has been created
- [ ] Review and validate
