### ISSUE TITLE
Copy content build to a new repo

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7969]
## Description
To accomplish the goals outlined in the [Separate Content Build design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2020-04-09-separate-content-build.md), we need to copy the content build script into a new repositor

## Goal
A content build which stands by itself, without `vets-website`.

**Note:** This is just for copying the content build into a new repo. Setting up the deployments and removing the code from `vets-website` are captured in separate tickets.

---
## Tasks
- [x] Create a new repository under the VA org
    - Named `content-build` (unless you can think of a better one)
- [x] Copy the content build script and all its dependencies into it
    - Ideally keeping commit history
- [ ] Install all the appropriate dependencies
- [ ] Do all the re-jiggering required to successfully run the content build

## Acceptance Criteria
- [x] The repository is created in VA's GitHub org
- [ ] (Optional) The commit history is preserved
- [ ] The content build runs successfully

**Comment by meganhkelley** [comment]
From Bill: 
* content build repo exists
* dependencies can be run
* yarn-build can be run 

So that we're not leaving this open throughout the entire content build separation release, we will close this ticket now.
