### ISSUE TITLE
[UX] Create initial high-level userflow 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#79690]
## Tasks

- [ ] Iterate and create initial high-level userflow to understand the start and end of the CC direct scheduling userflow. (Utilize any [documentation in the CC Direct Scheduling Google Drive](https://drive.google.com/drive/folders/1veStOmMRxULvqIwP8nxDHk0BBOdrgrWp?usp=drive_link).) 
- [ ] Document any questions and assumptions (to confirm with OCTO and the business at a later time) 

## AC

- [ ] Review with team and get feedback
- [ ] Initial high-level userflow created

**Comment by benbrasso-agile6** [comment]
Let's meet to review this

**Comment by cgednalske** [comment]
Next step that @Cieramaddox is already working on can be low-fi wireframes / fleshed out userflow options - with what's all included in that depending on the answers to our questions today.
