### ISSUE TITLE
Discovery: Untracked Events GA4 Custom Event Audit (Financial Status Report) & (CDP)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#79713]
## Issue Description

This is a **follow up** ticket to review custom events throughout the FSR and CDP to verify we are sending up to date information to the analytics team.

#### Original Task (completed):
- In preparation for the migration to Google Analytics 4 (GA4), the Analytics Team is asking that all VFS Teams that leverage and track custom events in their products complete this form, (along with its attached spreadsheet), **no later than Friday, April 5, 2024.** Detailed instructions on what information to include for each custom event can be found within[ this form.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D)

---
## Tasks
- [x] Audit app for additional custom events to be created
- [x] Complete spreadsheet if updates are made 

## Acceptance Criteria
- [x] Add new custom event records if needed
- [x] Form submitted to Analytics team
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amponce** [comment]
## Analytics Update: Tracking Short vs. Long Form Paths

Problem: We’re not currently tracking how users end up on the short form or long form based on their income. Understanding this can really help us tweak the form to make it better for everyone.

Solution: Add recordEvent calls to catch when a user is directed to either form. This way, we can see the impact of income levels on form usage.

### Implementation 

- Event Name: form-path-determination
- Details to Track:
   - form-path-type (short, long, none)
   - form-path-label (streamlined-short, streamlined-long, streamlined-none)

Code Example:

```js
const trackFormPath = (formData) => {
  const isShortForm = isStreamlinedShortForm(formData);
  const isLongForm = isStreamlinedLongForm(formData);

  let eventType = 'none';
  let eventLabel = 'streamlined-none';

  if (isShortForm) {
    eventLabel = 'streamlined-short';
    eventType = 'short';
  } else if (isLongForm) {
    eventLabel = 'streamlined-long';
    eventType = 'long';
  }

  recordEvent({
    event: 'form-path-determination',
    'form-path-type': eventType,
    'form-path-label': eventLabel,
  });
};
```

### Next Steps:

- Integrate this tracking into the current logic.
- Test to make sure we’re catching the right data.
- Watch the data and adjust if we need to.

### Benefit: 

We’ll finally have clear data on how income affects form path choice. This will guide us to make smarter decisions for our users.
