### ISSUE TITLE
[spike] SC | Figure out process for SC failed evidence upload remediation

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#79725]
## Issue Description

We have a growing list of SC failed evidence uploads with no clear process for remediation. See:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/72199
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/73584
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74017
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74606
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75213
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77451
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79145

The goal of this ticket is to develop a remediation process to resolve the errors above and any future SC evidence upload errors.

Ideally, upon detecting such errors, and if such errors are transient, we could promptly re-submit the evidence on our end manually. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/79145. I'd like to know whether there are any good reasons why we couldn't do that. I'd also like to know at what point it becomes "too late" to simply re-submit evidence on our end manually. Surely, four hours wouldn't be "too late" (or, would it?). What about one day? Two days?

For non-transient errors or transient errors that are "too late" for manual resubmission, we will need a process.

## Tasks
- [ ] Figure out when is "too late" for manual re-submission. 
- [ ] Figure out manual resubmission process for non-transient errors and transient errors that are "too late" for manual resubmission.

## Definition of Ready
Ready now.

## Acceptance Criteria
- [ ] Tasks done.

## Definition of Done
- [ ] Acceptance criteria met.

**Comment by shaunburdick** [comment]
All sub tickets are closed.
