### ISSUE TITLE
Edit Ticket: Analytics Customer Support Guide

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#79727]
Government and VA users cannot view links to Google Drive on their work computers.
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Analytics customer support guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide) contains links to Google Slides.
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

**Tasks**

- [x] Update page according to guidance by SME
- [x] Move page into deployment space
- [x] Check for LBs

## Acceptance Criteria
- [x] Page is deployed

**Comment by jknipes** [comment]
Work is finished, moving to _Done_
