### ISSUE TITLE
[FE] Include a parameter for 'timeToComplete' in /travel-claims to indicate time taken for Veteran from auth to submitting travel claims

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#79739]
## User Story
As part of #78427, the backend team has been exploring how to report the time it takes for a veteran to submit the travel claim from the time they logged in. We are able to get the times by the uuid, but DD doesn't provide a way to aggregate those metrics. 

This ticket is for website to calculate that time and include that in a parameter, which website can log once the travel claims controller finishes. This time can then be used in DD to create dashboards with aggregated metrics.

- Set a start time when the user clicks submit on validation 
- Set a end time when the user completes the travel claim
- Subtract to get the time to complete in seconds 
- Pass timeToComplete as a parameter in the submit travel claim api call

## Tasks
- [ ] Pass timeToComplete to vets-api for logging a custom metric in datadog
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@randomsync this is merged and ready to test out.
