### ISSUE TITLE
[View Payments] Remove dependency on `moment.js`

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#79738]
### Background
We are using a library called `moment.js` to help with things like date formatting and date parsing. This library is no longer actively supported and their documentation recommends moving to a different library. We have been using another library called `date-fns` alongside `moment.js` that is still maintained

## Value proposition
* Platform has been discussing finding ways to push teams to move from moment to `date-fns`. This will help us avoid having to divert attention from other projects if and when they mandate that teams update their code
* `moment.js` is a fairly large library and it has been observed that us having it slows down page load times

## Considerations
Files that still include usage of `moment.js`:
* `src/applications/disability-benefits/view-payments/components/view-payments-lists/helpers.js`

### Tasks
- [x] Remove checks for date validity that use `moment.js` and replace them with an equivalent check using `date-fns`
- [x] Update instances where we format dates using `moment.format()`

### Acceptance Criteria
- [x] Any usages of `moment.js` in  the View Payments application have been replaced with `date-fns`

**Comment by jerekshoe** [comment]
### Update
Found an issue related to dates being off by a day depending on the users time zone. This was not introduced by the previous PR, but should be addressed as someone reached out to me to let me know that one of the tests around the `formatDate` function fails if ran on a computer on the West Coast.
