### ISSUE TITLE
[BE] Add 'timeToComplete' as a parameter to TravelClaimsController, and log it along with other incoming params

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#79741]
## User Story
The timeToComplete parameter indicates the time it takes for veterans to submit the travel claim from when they logged in. This will be logged in DataDog and allow us to report aggregate metrics.

## Tasks
- [ ] [BE] Update permitted_params for TravelClaimsController to include 'timeToComplete' parameter
- [ ] [BE] add a log statement to log the parameters

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
