### ISSUE TITLE
[Post-release] Remove content build script from vets-website

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7976]
## Description
Once the content deploy is set up and [working without `vets-website`](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7973), we can remove all that code.

**Note:** We'll need to consider the developer experience for folks working on the `static-pages` bundle who need the static content pages and Webpack. This may mean running two watch commands from separate terminals (and repos), but we'll need to keep it in mind.

## Goal
All content building code is removed from `vets-website`.

---
## Tasks
- [ ] All dependencies unique to the content build are removed
- [ ] All content build code is removed

## Acceptance Criteria
- [ ] The content build code is gone
- [ ] Everything else works as expected
