### ISSUE TITLE
BE | Profile | Direct Deposit | Update Direct Deposit Routing and Error Prefixes

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#79767]
## Background
This ticket covers two small changes to the direct deposit API.

1. The existing route for direct deposit is specific to C&P - `v0/profile/direct_deposits/disability_and_compensations`.  Update the route to - `v0/profile/direct_deposits`.
2. When an error is returned from a Direct Deposit update, the error code contains the following prefix - `cnp.payment`.

Update `cnp.payment` prefix to `direct.deposit`.

## Tasks
- [x] Add additional route - `v0/profile/direct_deposit`
- [x] Update `cnp.payment` prefix to `direct.deposit`.
- [x] Place the change behind the `profile_show_direct_deposit_single_form` feature flag.

## Acceptance Criteria
- [x] Test new route in staging.
- [x] Add spec to test change.
- [x] Test the following in staging:
  - [x] Ensure that error codes start with `cnp.payment` when flag is off.
  - [x] Ensure that error codes start with `direct.deposit` when flag is off.
