### ISSUE TITLE
[DevOps] Access to CHIP repository settings for Nate Douglas

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79776]
## User Story
As a DevOps engineer, I need access to the settings for the CHIP repository so that I can manage relevant configuration.

## Tasks
- [ ] [DevOps] Find out why I don't have access to CHIP repository settings.
- [ ] [DevOps] Get access to CHIP repository settings.

## Acceptance Criteria
- [ ] I can do review and update CHIP repository settings.

**Comment by ndouglas** [comment]
Saw this message in Slack at a fortuitous time:

<img width="492" alt="Screenshot 2024-04-02 at 12 10 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/98bedf1b-bfab-4daf-9223-47fb145260e4">

So I pinged Brian, who got that done quickly 🙂 

![Screenshot 2024-04-02 at 12 08 39 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/72ee76f0-d2fb-4515-91cc-f2b41b75edab)
![Screenshot 2024-04-02 at 12 08 50 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/d94f6795-58c0-4503-86c9-f640c6e7b87b)
