### ISSUE TITLE
[DevOps] Specify day-end-summary workflow requirements (in `checkin-devops`) in `requirements.txt`, rather than GHA workflow.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79787]
## User Story
As an engineer, I want to specify requirements for Python scripts in an idiomatic and environment-independent fashion so that I am able to develop functionality locally without having to copy and paste stuff from GitHub Actions workflows.

## Tasks
- [x] [DevOps] Add `requirements.txt` file to `checkin-devops`
- [x] [DevOps] Install requirements from there rather than by listing them individually in the GHA workflow.

## Acceptance Criteria
- [x] Script requirements are specified in `requirements.txt`
- [x] GHA workflow installs from `requirements.txt`
