### ISSUE TITLE
[DevOps] Simplify and refactor `CHIP` repository GHA workflows.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79788]
## User Story
As an engineer, I want to be able to test and validate CHIP lambda functionality locally so that I can find problems locally before deploying.

Currently, getting CHIP lambdas to run locally so that they can be tested with e.g. `sam local invoke` is... an unsolved problem. A lot of the logic for getting packages into the expected locations is housed only in GHA workflows, making them difficult to develop and test locally.

Additionally, there are tasks that split work unnecessarily, and that are duplicated across multiple workflows.

## Tasks
- [x] [DevOps] Identify core operations that actually need to occur to have a working set of lambdas on any given environment.
- [x] [DevOps] Factor those out into shell scripts that can be executed from any environment.
- [x] [DevOps] Modify GHA workflows to use common functionality where possible, including shared local actions.
- [x] [DevOps] Modify GHA workflows to use repository-hosted scripts rather than executing commands housed only in task definitions.

## Acceptance Criteria
- [x] GHA workflows share tasks via local actions where appropriate.
- [x] GHA workflow shell commands are housed in discrete scripts within the repository.
- [x] GHA workflows and local actions execute scripts rather than shell commands.
