### ISSUE TITLE
[DevOps] Plan rewrite of `CHIP` IaC as Terraform

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79797]
## User Story
As a DevOps engineer of taste and refinement, I want to rewrite the `CHIP` IaC in Terraform for improved reliability and predictability.

As a DevOps engineer aware that the Dev CHIP deployment is currently a smouldering ruin and the other environments cannot be rebuilt because they rely on EOL'ed versions of Node, I need to plan this operation in detail so that I can quickly achieve a workable, reliable platform.

## Tasks
- [x] [DevOps] Review dev template and:
  - [x] list resource types
  - [x] map resources to Terraform AWS provider resources
- [x] [DevOps] Provide details for implementation in followup Dev implementation ticket (#79798).

## Acceptance Criteria

- [x] Dev template has been reviewed and tasks populated in implementation followup ticket (#79798).

**Comment by ndouglas** [comment]
Distinct resource types:
- AWS::CloudWatch::Alarm
- AWS::DynamoDB::Table
- AWS::Logs::LogGroup
- AWS::Logs::MetricFilter
- AWS::Logs::SubscriptionFilter
- AWS::Serverless::Api
- AWS::Serverless::Function
- AWS::Serverless::LayerVersion

Terraform resources:
- [Cloudwatch Metric Alarm](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm)
- [DynamoDB Table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table)
- [Cloudwatch Log Group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group)
- [Cloudwatch Log Metric Filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_metric_filter)
- [Cloudwatch Log Subscription Filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_subscription_filter)
- [API Gateway API](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api)
- [API Gateway Resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_resource)
- [API Gateway Method](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method)
- [Lambda Function](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function)
- [Lambda Layer Version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version)
