### ISSUE TITLE
[DevOps] Dev implementation for `CHIP` IaC Terraform rewrite

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79798]
## User Story
As an engineer, I want to rewrite the Dev environment for the `CHIP` IaC in Terraform to deeply acquaint myself with the problem space.

Followup to #79797.

Distinct resource types:
- AWS::CloudWatch::Alarm
- AWS::DynamoDB::Table
- AWS::Logs::LogGroup
- AWS::Logs::MetricFilter
- AWS::Logs::SubscriptionFilter
- AWS::Serverless::Api
- AWS::Serverless::Function
- AWS::Serverless::LayerVersion

Terraform resources:
- [Cloudwatch Metric Alarm](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm)
- [DynamoDB Table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table)
- [Cloudwatch Log Group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group)
- [Cloudwatch Log Metric Filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_metric_filter)
- [Cloudwatch Log Subscription Filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_subscription_filter)
- [API Gateway API](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api)
- [API Gateway Resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_resource)
- [API Gateway Method](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method)
- [Lambda Function](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function)
- [Lambda Layer Version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version)

## Tasks
- [x] [DevOps] Create Terraform configuration.
- [x] [DevOps] Brief postmortem of Dev environment work to inform Staging (#79801) and Prod (#79802) followup tickets.
- [x] [DevOps] Review staging and production templates to see what further things need discovery.

## Acceptance Criteria

- [x] Postmortem in thread of things that were unanticipated
- [x] Staging implementation ticket (#79801) is updated with information outcomes from this ticket.
- [x] Production implementation ticket (#79802) is updated with information outcomes from this ticket.

**Comment by ndouglas** [comment]
This is blocked by #81919.

**Comment by olivereri** [comment]
# Mapping Resources for Conversion to Terraform

## Lambdas
19 Lambdas Make up  Check In Integration Point (CHIP)
| Function Name                                               | Path                                   | Method | CodeUri                                  | Role                                                                               | Request Params                                                                   |
| ----------------------------------------------------------- | -------------------------------------- | ------ | ---------------------------------------- | ---------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| project-chipAPI-token-${env}                                | /token                                 | POST   | src/token                                | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-openapi-${env}                              | /openapi                               | GET    | src/openapi                              | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-getShortUrl-${env}                          | /short-urls/{id}                       | GET    | src/urlShortener/getShortUrl             | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-shortenUrl-${env}                           | /actions/short-urls                    | POST   | src/urlShortener/shortenUrl              | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-initiateCheckIn-${env}                      | /actions/initiate-checkin              | POST   | src/initiateCheckin                      | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-initiatePreCheckIn-${env}                   | /actions/initiate-precheckin           | POST   | src/initiatePreCheckin                   | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-refreshPreCheckIn-${env}                    | /actions/refresh-precheckin/{uuid}     | POST   | src/refreshPreCheckin                    | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-checkVeteranIn-${env}                       | /actions/check-in/{uuid}               | POST   | src/checkIn                              | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-setPreCheckinStarted-${env}                 | /actions/set-precheckin-started/{uuid} | POST   | src/setPreCheckinStarted                 | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-preCheckin-${env}                           | /actions/pre-checkin/{uuid}            | POST   | src/preCheckIn                           | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-refreshAppointments-${env}                  | /actions/refresh-appointments/{uuid}   | POST   | src/refreshAppointments                  | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-confirmDemographics-${env}                  | /actions/confirm-demographics          | POST   | src/confirmDemographics                  | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-deleteFromLorota-${env}                     | /actions/deleteFromLorota/{uuid}       | DELETE | src/deleteFromLorota                     | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-vistaCache-${env}                           | N/A                                    | N/A    | src/vistaCache                           | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-authenticatedCheckIn-${env}                 | /actions/authenticated-checkin         | POST   | src/authenticatedCheckIn                 | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-authenticatedGetDemographics-${env}         | /actions/authenticated-demographics    | GET    | src/authenticatedGetDemographics         | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role | method.request.querystring.patientDfn<br>\- method.request.querystring.stationNo |
| project-chipAPI-authenticatedUpdateDemographicStatus-${env} | /actions/authenticated-demographics    | POST   | src/authenticatedUpdateDemographicStatus | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-setECheckInStarted-${env}                   | /actions/set-e-check-in-started        | POST   | src/setECheckInStarted                   | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |                                                                                  |
| project-chipAPI-initiateTravelClaim-${env}                  | /actions/initiate-travel-claim         | POST   | src/initiateTravelClaim                  | arn:${AWS::Partition}:iam::${AWS::AccountId}:role/project/project-chip-lambda-role |

**Comment by olivereri** [comment]
For API-Gateway to work properly VPC endpoints need to be created to allow network access to the API. VAEC Service Desk REQ26863340 has been created. Project teams don't have permissions to create these resources in AWS and require a ticket to be created.

**Comment by olivereri** [comment]
CHIP Lambdas have a transform section in the AWS SAM that isn't very obvious what it does:
```
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      apiKey: "{{resolve:secretsmanager:tevi/datadog/ramped/keys:SecretString:key}}"
      enableDDTracing: true
      enableEnhancedMetrics: true
      enableXrayTracing: false
      env: !Ref env
      extensionLayerVersion: 55
      logLevel: info
      nodeLayerVersion: 108
      service: !Ref ServiceName
      site: "ddog-gov.com"
      stackName: !Ref "AWS::StackName"
```

This adds Datadog created Lambda Layers to functions, but those layer resources don't appear in CloudFormation.  Terraform has a Lambda wrapper module to include them:
https://registry.terraform.io/modules/DataDog/lambda-datadog/aws/1.0.0

**Comment by ndouglas** [comment]
Nice, hadn't gotten that far yet.

**Comment by ndouglas** [comment]
This is essentially complete, and I'm closing #79801 and #79802 as well, since these tasks were completed in parallel. There is additional work to do here; we're under no illusions that this is perfect, but deficits can only be discovered as part of an audit process that we'll need to undertake separately.
