### ISSUE TITLE
[Letters] - Replace <button /> with <va-button />

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#79792]
## Background Context

There are linting errors with using <button /> we should update these instances to use <va-button />.

<img width="1151" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01xQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88caa8b77cf78389c8c5b6733e1c68d0ac127007/Screenshot%202024-04-02%20at%208.34.14%E2%80%AFAM.png" alt="Screenshot 2024-04-02 at 8.34.14 AM.png" />

<img width="612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1VxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e6efc30f67b9ae00b29a30f0a3eaaee66a02e8d/Screenshot%202024-04-02%20at%208.34.45%E2%80%AFAM.png" alt="Screenshot 2024-04-02 at 8.34.45 AM.png" />

## Engineering 
- Add here

## Tasks
The following components use <button />...

- [ ] DownloadLetterLink.jsx
- [ ] AddressSection.jsx

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The letters service doesnt use HTML buttons and uses va-buttons instead

**Comment by pmclaren19** [comment]
Found that there is a cypress test that is being skipped that we should figure out how to run, currently working on getting that to run since its been skipped for the last 22 months
