### ISSUE TITLE
[View Payments] Upgrade react-router to V6

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#79815]
### Background
The application is currently using react-router V3. The current latest version is V6. We need to update the application to use V6 so that we are not holding the rest of the platform back

### Tasks
- [x] Update entry to use the `startAppFromRouter` method instead of `startApp`
- [x] Update routes to conform to the new version

### Acceptance Criteria
- [x] The View Payments application is using react-router V6
