### ISSUE TITLE
[CST] - Add unit tests to the Claim status Tool  files in components and containers folders so each file is at 80% 

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#79845]
## Background Context
There are files in the CST that dont have a test file or do not have 80% test coverage. We should update these so that tests have 80% coverage.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Running `yarn test:coverage-app claims-status` and verifying each test file shows that it has 80% coverage.

## Out of scope
- EVSS files

## Open questions
- Should we add tests for code that will be deprecated with V2 changes

## Tasks
- [x] AddFileFormOld.jsx - 79.48%
- [x] AppealsUnavailable.jsx - 0%
- [x] AskVAToDecide.jsx - 0%
- [ ] ClaimSyncWarning.jsx - 66.66% - (component will be removed soon)
- [ ] ClaimsAppealsUnavailable.jsx - 0%
- [ ] ClaimsBreadcrumbs.jsx - 66.66% (unable to add a test clicking a route due to the shadow dom issues)
- [ ] ClaimsUnavailable.jsx - 33.33%
- [ ] FeaturesWarning.jsx - 0%
- [ ] NoClaims.jsx - 0%
- [ ] PhaseBackWarning.jsx - 0%
- [ ] VaButtonGroupSegmented.jsx - 18.18% - (component will be removed soon)
- [ ] AppealHelpSidebar.jsx - 60%
- [ ] AddFilesForm.jsx - 79.22%
- [ ] AdditionalEvidencePage.jsx - 67.5%
- [ ] AdditionalEvidencePageOld.jsx - 64.7%
- [ ] AppealInfo.jsx - 76.08%
- [ ] ClaimsStatusApp.jsx - 61.53%
- [ ] DetailsPage.jsx - 38.7%
- [ ] index.js (selectors) - 34%
- [ ] index.js (actions) 32%

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Each file in components folder has 80% test coverage
- [ ] Each file in containers folder has 80% test coverage
