### ISSUE TITLE
Adjust middle, end and "somewhere" Appoint MVP designs with CAIA collaboration

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#79842]
## Background
Unauth user testing led to UX changes necessary to the experience. We are collaborating with CAIA for content recommendations to finalize these changes.

[List of changes needed in Figma](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=3060-835430&mode=design&t=PuEe64HbHUOUXbJh-11)

This work will focus on the items under "Middle of the flow" "End of the flow" and "Somewhere".

Ultimately, this work is to support development of Appoint MVP, which is **scheduled to begin in May**.

## Tasks
- [x]  Review designs with CAIA
- [x]  Collaborate with CAIA on approach
- [x]  Fill in content recommendations and adjust designs accordingly

## Acceptance Criteria
- [x]  Appoint MVP designs have been updated, based on CAIA's most recent feedback (which in turn is based on findings from our unauthenticated study) and is ready for development.

**Comment by mtri** [comment]
Content recommendations have been added into Figma. For ongoing content iteration related to 21-22 VSO relationship and 21-22a authorization language see: [#80050](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/80050)
