### ISSUE TITLE
[CST] - Add 80% test coverage to V2 files 

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#79849]
## Background Context
There are files in the CST that dont have a test file or do not have 80% test coverage. We should update these so that tests have 80% coverage.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Running `yarn test:coverage-app claims-status` and verifying each test file shows that it has 80% coverage.

## Open questions
- Should we add tests for code that will be deprecated with V2 changes

## Tasks

- [x] AddFilesForm.jsx - 79.22%
- [x] AdditionalEvidencePage.jsx - 67.5%
- [x] AskVAPage.jsx
- [x] DocumentRequestPage.jsx
- [x] FilesPage.jsx
- [x] YourClaimsPageV2.jsx

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Each file in AddFilesForm.jsx has 80% test coverage
- [ ] Each file in AdditionalEvidencePage.jsx has 80% test coverage

**Comment by pmclaren19** [comment]
Did an audit of all of the files that were changed for V2 and there are a few other files that we need to add test coverage for that were missed 

- [ ] AskVAPage.jsx
- [ ] DocumentRequestPage.jsx
- [ ] FilesPage.jsx
- [ ] YourClaimsPageV2.jsx
