### ISSUE TITLE
[FSR] Change Type of work dropdown to radio button group

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#79856]
## Description

Need to refactor the Type of work dropdown question on the FSR since it has less then 7 options to be a radio button group to [follow DS guidance](https://designsystem.digital.gov/components/select/):
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/7dfa7917-b6ce-45be-b26c-2f881aec94d1)

Here's a [link to the figma file](https://www.figma.com/file/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---Streamlined-Waiver?type=design&node-id=218-10717&mode=design&t=PwEObws34hpnv5n5-11) and what it should look like:
<img width="443" alt="Screenshot 2024-04-02 at 5 10 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/3194d283-a904-4c81-b65b-b6b1f12ee5c2">

Given: A veteran fills out the FSR
When: They add an employment record
Then: They should be able to see the employment type in a radio button group easily instead of in a dropdown select menu

## Tasks
- [x] Change dropdown question to radio button question in code for both spouse and veteran
- [x] Ensure data still passes correctly

## Acceptance criteria

- [x] Type of work question for both spouse and veteran has been updated to radio buttons 
- [x] Update FSR type of work question to use [radio button component](https://design.va.gov/components/form/radio-button#default) 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@OptionSelect, happy to help with the review on this one from a design standpoint!
