### ISSUE TITLE
[DevOps] What is this Slack-Socket thing?

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79866]
## User Story
As an engineer, I want to understand why we're checking out an action from another repository and passing hand-escaped JSON around because surely there's a better way to do this.

## Tasks
- [ ] [DevOps] Figure out what the vsp-github-actions/slack-socket is.
- [ ] [DevOps] Figure out why we're using it.
- [ ] [DevOps] Figure out why we're escaping JSON by hand like barbarians.
- [ ] [DevOps] Figure out how to improve this situation.

## Acceptance Criteria
- [ ] I have achieved total awareness of this situation.
- [ ] Followup ticket(s) opened to fix this.

**Comment by ndouglas** [comment]
I hate this bot
