### ISSUE TITLE
[DevOps] What is this CHIP fortify thing?

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79861]
## User Story
As an engineer, I want to figure out what this CHIP fortify workflow is because it's undocumented and it's not immediately apparent what it is doing or why.

## Tasks
- [x] [DevOps] Figure out what the CHIP fortify thing is.
- [x] [DevOps] Document it in this thread.
- [ ] [DevOps] Open followup ticket(s) if appropriate to take further action.

## Acceptance Criteria

- [x] I've figured out what this is and what purpose it serves.
- [x] I've documented that information in this thread so I can make an educated decision about how to move forward.
- [ ] Followup ticket(s) opened if appropriate to take further action.

**Comment by ndouglas** [comment]
Per [this Slack conversation](https://dsva.slack.com/archives/C038C047X2P/p1701385702620279), we do not appear to use Fortify, nor do we appear to need it (as we use CodeQL where appropriate). Opened #87093 to follow up.
