### ISSUE TITLE
[DevOps] Look at refactoring `checkin-devops` Terraform-related GHA workflows.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79867]
## User Story
As an engineer, I want to refactor the Terraform-related GHA workflows in `checkin-devops` to improve reliability and maintainability.

## Tasks
- [ ] [DevOps] Determine what these inlined shell scripts are doing and why
- [ ] [DevOps] Determine why we're using locally triggered workflows instead of local actions
- [ ] [DevOps] Move the inlined shell scripts to an actual script in the existing `scripts` directory that can be tested
- [ ] [DevOps] Shift common functionality into a local action if possible
- [ ] [DevOps] Refactor Terraform workflows as necessary to achieve oneness with the divine

## Acceptance Criteria
- [ ] Nontrivial shell scripts exist within the repository rather than within a workflow
- [ ] Common workflow functionality is relocated to local actions if possible
- [ ] Testing confirms consistent behavior.

**Comment by ndouglas** [comment]
I think this should all be replaced with a Terragrunt configuration. I played with a larger-scale refactoring, but I don't feel great about it.

The workflows in their present form accept user input that's only incidentally and incompletely sanitized. I don't think this is an unacceptable security risk, given the permissions needed to run the tasks, but it's still a bit eh to me.

I don't really see much benefit to running the scripts that filter by changed directories, etc. That wouldn't be needed if there weren't a 2D matrix of directories with environments and apps, and I think Terragrunt's a better solution there.

As a result, I'm going to close this as completed and open a new ticket to handle a Terragrunt rewrite.
