### ISSUE TITLE
Update Wireframes for Unified Check-in Experience for Additional Supported Modalities 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#79862]
## Tasks

- [x] Identify what page the modalities should be added to. Either "Design" or maybe a sub page under "Design" for "Telehealth." Let's meet to discuss. 
- [x] Add components, states or pages for telehealth pages into Unified Figma file. Telehealth for pre-checkin and check-in are documented in the [Production Figma file](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=240%3A1520&mode=design&t=rtQKAfcJd9l4xHRT-1). 
- [x] Provide links to Lori for FE to use

## AC

- [x] States and/or pages for telehealth are added into Unified Figma file
- [x] Links provided to PO for FE to use

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/79862?planning-poker) with Zenhub @cgednalske

**Comment by cgednalske** [comment]
@benbrasso-agile6 I am pretty much guessing on my estimate for this one - not sure I am entirely up-to-speed on the requirements.

**Comment by benbrasso-agile6** [comment]
Will collab with @zach-park on this one

**Comment by benbrasso-agile6** [comment]
- [Pre-check-in CVT complete page](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=723-9514&mode=design&t=GRckhmogWi500ntu-4)
- [Pre-check-in VVC complete page](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=723-9336&mode=design&t=GRckhmogWi500ntu-4)
- [Pre-check-in CVT appt detail page](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=723-8899&mode=design&t=GRckhmogWi500ntu-4)
- [Pre-check-in VVC appt detail page](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=723-9033&mode=design&t=GRckhmogWi500ntu-4)

@loripusey for eng ticket for unified exp
