### ISSUE TITLE
Update Style Guide: Don't Use Widget Connector Macro

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79875]
## Issue Description
The [Links to Google Drive ](https://vfs.atlassian.net/wiki/spaces/AP/pages/621609007/Grammar+and+punctuation#Links-to-Google-Dive)section in the Content Style Guide needs to be updated to reflect guidance against using [Widget Connector Macro](https://confluence.atlassian.com/doc/widget-connector-macro-171180449.html) to display Google Slides and other apps from Google Drive. VFS Teams are unable to view Images and apps embedded with this macro.

---
## Tasks
- [x] Update [this section](https://vfs.atlassian.net/wiki/spaces/AP/pages/621609007/Grammar+and+punctuation#Cross-references-and-links) per the discovery from [Slack Thread](https://oddball.slack.com/archives/C02LYB7QXS5/p1711994271950179)

## Acceptance Criteria
- [x] Style guide will be updated with guidance regarding Widget Connector Macro
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/79875?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by taylojill** [comment]
Page updated with verbiage provided by @BSmolensky.

**Comment by jknipes** [comment]
Work completed, AC met, moving to _Done_
