### ISSUE TITLE
Modify .stylelint.json in vets-website to flag use of Formation sass color variables

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#79871]
## Issue Description
Recently in [79489](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/79489) all Formation color variables in `vets-website` were updated to use `css-library` variables. However, there is no `stylelint` rule to flag teams that use Formation color variables going forward. This goal of this ticket is to add a check to make sure teams do not use Formation color variables going forward.

---
## Tasks
- [ ] Modify [.stylelint.json](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.stylelintrc.json) in `vets-website` so that VFS teams cannot add Formation color variables.
## Acceptance Criteria
- [ ] Formation sass color variables are flagged in `vets-website`.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
