### ISSUE TITLE
Technical discovery to understand what emails Veterans receive for confirmation or failure of submission and when 

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#79889]
## Description

In order to improve the post-submission experience for Veterans filing for disability (from submission until a claim is established in VBMS with all documents uploaded), we must understand the current state of their experience. 

While design is building a [journey map of the current state of the experience](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?wid=0-1712154027855), we need technical support to understand how, when, and in what situations Veterans are receiving email notifications in the status quo. 

In scope:
- Email notifications from 526 workflow - [instructions to access in VA Notify](https://dsva.slack.com/archives/C04KW0B46N5/p1704909261861819?thread_ts=1695923106.824659&cid=C04KW0B46N5): connect to VA network, log into https://notifications.va.gov/ with your PIV.
    - [Failed Submission Notification](https://notifications.va.gov/services/5bda137e-689e-4532-b3d2-2c81c0324331/templates/7e7719cb-f2c8-4856-9733-825e25f39dd8)
    - [Form 526ez email confirmation](https://notifications.va.gov/services/5bda137e-689e-4532-b3d2-2c81c0324331/templates/0c1335fc-ca67-408a-b2ae-08b91ffaceba)
    - [526 EZ Application Reminder](https://notifications.va.gov/services/5bda137e-689e-4532-b3d2-2c81c0324331/templates/b9c6513b-efa2-45b7-9691-5c70925dc450)
    - Investigate any others within the scope of this journey

Created from [Desk research on existing OCTO product research and design - Part 1#79462](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79462)

Reference: [526EZ Process Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1663868736153/1040f1c6df6230104917bdff6e5e157264ef9153?sender=uc4ae3c86028c82b95c3c2980)

Note that David Reis is asking around looking into these processes for paper mail but not sure if that will answer all questions.
## Tasks

- [ ] Determine what triggers email notifications from when a Veteran starts a claim to when the claim is established/failed to establish/all submission efforts completed, all documents are uploaded/failed)  (Team 2 is working on upload failure notifications)
- [ ] Document this in the [journey map of the current state of the experience](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?wid=0-1712154027855) and/or discuss with @evelynhilbrichdavis, @mengA6 , @Kate-allbee 
- [ ] @mengA6 to share what we learn with Julie Strothman & Benefits Management Tools team

## Acceptance criteria
- [ ] Identify the conditions under which email notifications are sent out from 526
- [ ] Determine if the failed submission email is currently expected to go out. 
- [ ] Identify any other emails and conditions for trigger, if any, within the scope of this timeframe

**Comment by evelynhilbrichdavis** [comment]
Document upload presentation from Nathan here:
https://us06web.zoom.us/rec/share/Dfrb-dEOEti12QvxaiZHURSd-JnEMtMtke0r8TlCslLy9F05JWH54_tpasZoAPHf.kEwoiBFQzl8DXrJ4
Passcode: U1c&b5zd

**Comment by mengA6** [comment]
To accompany that presentation Evelyn mentioned, here's [the associated Mural: 526 Claim Submission - Polling](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704307770399/7ba4dac361cbc90633616ae0a476bf7ac0db94f2?sender=uc4ae3c86028c82b95c3c2980). Also see [Slack thread where Anneliese shared this](https://agilesix.slack.com/archives/C04MJV66ZPC/p1706289613791969?thread_ts=1706286593.259549&cid=C04MJV66ZPC).

I have some gaps in my understanding like

1. When in time (relative to claim submission) do these emails get sent?
2. What does the UI in vets.gov / mobile app show at the point when these emails are sent?

**Comment by mchae-nava** [comment]
- Process involves using a service called va_notify
- Via notifications.va.gov, create a new email template and note the template id
- In code, create an instance of the VANotify::Service, and send an email using the template id and the specific data you want merged into the outgoing email
- Usually wrapped in a sidekiq job
	- va_notify is reliable, but it IS a remote service, and using sidekiq is an easy way to get retries
	- Careful about eating exceptions, if `perform` returns without throwing an exception, sidekiq considers the job successful and it wont re-run it
	- log exception via handle_errors and re-raise it so sidekiq knows to retry the job again

- Example from 526, sidekiq job to send confirmation email: https://github.com/department-of-veterans-affairs/vets-api/blob/59c90f9173b2219adc[…]8cfb4799eae79f5bc/app/sidekiq/form526_confirmation_email_job.rb
- Failure email: app/sidekiq/form526_submission_failed_email_job.rb
- Reminder email: modules/va_notify/app/services/va_notify/in_progress_form_reminder.rb > modules/va_notify/lib/va_notify/in_progress_form_helper.rb > form526_reminder_email
	- Oddly enough, template id exists for a reminder email but it is not set in the settings.yml
- Ids saved in config/settings.yml, will be fake_template_id locally


- Failure email calls:
	- app/models/form526_submission.rb #410, Check if all steps are complete (workflow_complete_handler) and if not, send the failure email
	- app/sidekiq/evss/disability_compensation_form/submit_form526.rb #67, after exhausting backup submission attempts (no more unused birls)
	- spec/models/form526_submission_spec.rb, unit test exists to make sure failure email is sent properly

- Confirmation email calls:
	- app/models/form526_submission.rb #406, Check if all steps are complete (workflow_complete_handler) and if so, send the confirmation email
	- spec/models/form526_submission_spec.rb, unit tests exist to make sure confirmation email is sent with proper personalization

- Reminder email calls:
	- Called by modules/va_notify/app/services/va_notify/in_progress_form_reminder.rb, which is actually a shared module used to send reminders for multiple forms
		- 686c-674
		- 1010ez
		- 526ez
		- ‘generic’ message to cover forms that aren’t any of the above
	- Users a modules/va_notify/lib/va_notify/in_progress_form_helper.rb to get the proper ID based on the form calling the reminder module
	- Template id exists for 526 reminder email but it is not set in the settings.yml, not super consequential, but worth noting
	- The reminder module is called by modules/va_notify/app/sidekiq/va_notify/in_progress_forms.rb
		- Called periodically on the latest in progress form only
