### ISSUE TITLE
[FSR] Update full FSR flow to include 'Cash in' questions 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#79884]
## Description
The full FSR flow should include the _Cash in bank_ and _Cash on hand_ pages while removing the `Cash`, `Checking accounts`, `Savings accounts` from the `monetary-asset-values` page (`monetaryAssets` array in `checkboxSelections.js` since the values are being tracked with the new pages. 

Since this could effect in progress forms we should determine if it's necessary to shift this update behind a feature flag. This change should help with the review navigation implemenation

[Here is the updated user flow on Figma](https://www.figma.com/file/fbJtTnxh1q6Z3i1vPtvucq/Streamlined-Waiver-User-Flows?type=design&node-id=0%3A1&mode=design&t=JFOe2iUooQDEB9rg-1)

## Tasks
- [ ] Determine if this change needs to hide behind a feature flag
- [x] Update depends for 'Cash in' so the pages are included in the full FSR
- [ ] Update `monetaryAssets` array
- [ ] Update any relevant tests

## Acceptance criteria

- [ ] _Cash in bank_ and _Cash on hand_ questions are added to the full FSR path
- [ ] `monetary-asset-values` page no longer shows `Cash`, `Checking accounts`, `Savings accounts` as checklist items
- [ ] All tests are passing

## Testing
- [ ] Confirm changes wont interfere with in progress forms

Testing procedure:
1. Start a full FSR with no code changes & SiP 
2. Add changes to include new pages, and remove old items
3. Continue initial form
4. Attempt page navigation around monetary assets

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>
