### ISSUE TITLE
[FSR] Review Page Navigation ... review

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#79892]
## Description
After we update the monetary assets flow for the full FSR ([#79884](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/79884)), let's review the Review Page Navigation, and confirm it's ready to launch! [We last left off with some edge cases that were causing issues](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/73673), but those appeared to be fixed!

## Tasks
- [x] Test review navigation potential pain points:
  - [x] Switching from **Streamlined Short** to 
    - [x] Full FSR
    - [x] Streamlined Long 
  - [x] Switching from **Streamlined Long** to 
    - [x] Full FSR
    - [x] Streamlined Short
  - [x] Switching from **Full FSR** to 
    - [x] Streamlined Short
    - [x] Streamlined Long

## Acceptance criteria

- [x] Review navigation is fully functional and ready to go live
- **OR**
- [ ] Fix tickets have been created

## Testing
- [x] Yes (see Tasks)

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Per FE Sync, need to confirm that tix #79884 is completed, then will complete testing.

**Comment by OptionSelect** [comment]
Still blocked by [79884](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/79884) which is currently blocked by weird CI/CD issues that have been brought to platform's attention [here](https://dsva.slack.com/archives/CBU0KDSB1/p1713546463785819)

**Comment by Dr-Pongo** [comment]
Going to run through tests in staging now that all of the changes are in including the cash questions update!

**Comment by Dr-Pongo** [comment]
Ran through the tests listed here and everything seems solid! Coordinating with FE team on next steps for launch!

**Comment by HeatherRienks** [comment]
Woot!
