### ISSUE TITLE
[DevOps] Transfer ownership of `checkin-devops` repository from `vnce-avalanche` to `patient-check-in`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#79911]
## User Story
As an engineer, I want total control over `checkin-devops`. Total. Control.

## Tasks
- [ ] [DevOps] Open a PR to change mentions of `vnce-avalanche` team to `patient-check-in` team in CODEOWNERS.

## Acceptance Criteria
- [ ] Control over the repository has been transferred 
- or -
- [ ] I've been sternly admonished
