### ISSUE TITLE
[CST] [DataDog RUM] [Status Tab] Set up DataDog RUM PII Masking for CST Status tab

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#79929]
## Issue Description
We need to set up PII masking so that DataDog Real User Monitoring doesn't collect PII.

---
## Tasks
- [ ] Set up DD RUM data masking for PII on CST Status tab
- [ ] Set up masking for any PII that shows up in `<title>`
- [ ] Test CST Status tab is tested on staging to confirm that no PII is being logged. (You can use css to highlight what gets masked. Check the listed reference doc. **_Possibly use the Stylus browser extension rather than adding actual css to the code base._**)
- [ ] Manually check for any PII that may be within a shadow dom, and won't pick up CSS test styling.
- [ ] Mask any PII that appears within `message-aria-describedby`
- [ ] Mask contentions which are PII
- [ ] Mask filenames which can be PII

## Acceptance Criteria
- [ ] Using CSS, PII masking has been confirmed on staging for CST Status tab. (Post screenshots)
- [ ] Any PII in shadow doms have been noted and tested for masking.
- [ ] Masking has been set up for any PII that shows up in `<title>`
- [ ] Any PII within `message-aria-describedby` is masked
- [ ] Contentions are masked
- [ ] Filenames are masked
---
## How to configure this issue
- Reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/main/platform/analytics/setup-real-user-monitoring.md#privacy

**Comment by jacobworrell** [comment]
@samcoforma to duplicate this and other status tickets for listing page and documents details pages, files.

**Comment by samcoforma** [comment]
Updated ticket to note the need to mask filenames and contentions as called out by @jerekshoe

**Comment by samcoforma** [comment]
I'm closing this ticket as it's covered by: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80449
