### ISSUE TITLE
[CST] [DataDog RUM] [Status Tab] Set up basic DataDog RUM Settings in CST Status tab code

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#79928]
## Issue Description
We need to set up `datadogRum.init` for the CST Status tab, and put it behind a conditional to prevent it from loading on local environments.

---
## Tasks
- [ ] Setup `datadogRum.init` in CST Status tab
- [ ] Make sure it's behind a conditional to prevent loading on local environments

## Acceptance Criteria
- [ ] `datadogRum.init` is set up for CST Status tab
- [ ] It does not load on local environments
---
## How to configure this issue
- [Setup Real-User Monitoring (RUM) Dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/blob/main/platform/analytics/setup-real-user-monitoring.md)
