### ISSUE TITLE
Toxic Exposure - Data Transformation #2 - Save TE fields for future transformation

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#79935]
## Issue Description

The new TE fields being added on the UI need to be persisted to 526 submission record to allow the fields to be part of the 526 claim submission.

## Tasks
- [x] Add TE fields from Save Claim data into 526 submission record 

## Acceptance Criteria
- [x] The new TE fields are persisted to 526 submission record 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
