### ISSUE TITLE
Toxic Exposure - Schema for all TE fields to Form526 vets JSON schema

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#79938]
## Issue Description
Add TE fields to Form526 validation (vets JSON schema) schema
Scope of this ticket - The contract for all remaining fields being added as part of Toxic Exposure initiative

Current state - FE and BE use JSONSchema to validate
New state - FE needs to point to patterns to validate to decouple the JSON schema from FE changes

---
## Tasks
- [ ] Agree on the contract between FE and BE for schema validation
- [ ] Add TE fields to JSON schema
- [ ] Verify that FE and BE validation schema matches

## Acceptance Criteria
- [ ] Add TE fields to JSON schema

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
This work is being completed in "Toxic Exposure - Add TE fields to Form526 vets JSON schema - Spike"

**Comment by alatempa24** [comment]
Any updates to documentation will be handled as part of #80352 - this is no longer needed
