### ISSUE TITLE
[Rated Disabilities] Update discrepancy check to include debugging info

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#79937]
### Background
Currently the discrepancy checks produce a log in DataDog every time there is a difference in the number of rating returned by EVSS and Lighthouse (after filtering). The contents of the log only include the magnitude of the difference and doesn't indicate how many ratings each service returned. It also doesn't include the rating ids, which makes it difficult to do manual discrepancy checks. We need to include the number of ratings returned by both services and a list of rating ids returned by both

### Tasks
- [x] Update the logging to include the number of ratings returned by EVSS and Lighthouse
- [x] Update the logging to include the ids of the individual ratings from each service
- [x] Update the revision field to return 5

### Acceptance Criteria
- [x] We are able to determine how many ratings were returned by each service by looking at the log payload
- [x] We are able to determine which rated disabilities each service returned based on the ids in the log payload
