### ISSUE TITLE
[CST] [DataDog RUM] [Status Tab] Contact OCTO about setting up a DataDog RUM dashboard for CST Status tab

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#79936]
## Issue Description
We need to contact OCTO about setting up a DataDog RUM dashboard for CST Status tab

---
## Tasks
- [ ] Contact OCTO
- [ ] Provide them with metrics (how many users etc)
- [ ] Refer to this: https://github.com/department-of-veterans-affairs/va.gov-team/blob/main/platform/analytics/setup-real-user-monitoring.md#privacy

## Acceptance Criteria
- [ ] OCTO has been contacted and asked to set up a RUM dashboard for CST Status tab
---
## How to configure this issue
- [ ] Refer to this: https://github.com/department-of-veterans-affairs/va.gov-team/blob/main/platform/analytics/setup-real-user-monitoring.md#privacy
