### ISSUE TITLE
Update Redis for Sentry

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79947]
## Issue Description
Due to issues with the Sentry app, Chris has been speaking to Hector on the Platform Support team, and it was determined that the Redis upgrade for Sentry is worth a try. He also agreed though that it seems like the error is something from inside the Sentry App and the [Helm chart](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/fe5f7533394af7b57d8daa76c593145312099b44/apps/vsp-operations/sentry/values-sentry.yaml) for that hasn't changed.

The recommendation is to try the upgrade and if that doesn't work, then investigate the error a little more deeply, with a time box of 1-2 days. 

If the subsequent error investigation work is unsuccessful, a discussion needs to be held on whether Sentry should be kept and teams want to invest the energy to maintain it properly, or if the process should begin to sunsetting it. It also needs to be determined what would replace Sentry in its current state. Reference [79951](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/79951) for options due to Sentry's future deprecation. 

---
## Tasks
- [ ] Upgrade Redis instance in Sentry to solve the internal error
- [ ] If Redis upgrade in Sentry is unsuccessful, investigate error more deeply [timebox to 1-2 business days]
- [ ] If error investigation yields no further ideas, discuss options on keeping Sentry and what the investment is to keep the tool properly maintained
- [ ] What will replace Sentry if sunsetting it is the best option?

## Success Metrics
- [ ] Number of errors decreases

## Acceptance Criteria
- [ ] New version has been installed properly
- [ ] Testing is completed successfully

**Comment by jennb33** [comment]
During our investigation into Sentry's internal errors yesterday, we identified that these issues began on January 29. Further examination of the error logs revealed references to Redis, leading us to check our Sentry Redis setup in AWS. We discovered that an automatic update to the Redis version had occurred on January 29. According to a related GitHub issues, upgrading Redis from version 5 to 6.2.7 should resolve this issue mentioned both here and here
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0F2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51e2c703f985d37b52f1eea24c7c159e39bc15a8/Screenshot%202024-04-03%20at%208.55.25%20AM.png" alt="Screenshot 2024-04-03 at 8.55.25 AM.png" />

**Comment by AshleyGuerrant** [comment]
@flooose - is this ticket still relevant, given the in progress REDIS upgrade? Thanks in advance!

**Comment by flooose** [comment]
I don't think we should work on this unless we decide to keeps Sentry. There are a lot of upgrades necessary there and upgrading some parts of Sentry may turn into more upgrade work for something that we plan to deprecate. The story also goes back to April, 2024 and Sentry is still running.

**Comment by AshleyGuerrant** [comment]
@flooose - thanks for the additional context. I am going to close this ticket out as wont fix for now, and we can reopen/rescope it later if it is identified as a priority.
