### ISSUE TITLE
Implement Process for Adding Date Stamp to Pages

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#79948]
### Description
Teams using Platform Website need to see a date on each page indicating Last Updated.
**Add A Date Using A Calendar** is an element available in Confluence, that also renders in Platform Website via Scroll Viewport:

<img width="290" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0l6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc3b1dce2ba0e05f20d0121451381cc5f10ab22c/Screenshot%202024-04-03%20at%2010.50.31%E2%80%AFPM.png" alt="Screenshot 2024-04-03 at 10.50.31 PM.png" />

### **How date appears on PW:**
<img width="266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzh5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d90f91111eacb367f9f2b4eed7c76d19d5f50363/Screenshot%202024-04-03%20at%2010.46.24%E2%80%AFPM.png" alt="Screenshot 2024-04-03 at 10.46.24 PM.png" />

 

### Tasks
- [x]  Create Draft instructions page for process in Confluence
- [x]  Format per PCT feedback
- [x]   Announce new process in Team of Teams w/linked page
- [x]  Demo finished page at End of Sprint Demo

### Acceptance Criteria
- [x]  Schedule First Announcement on Content Slack channel for Tip of The Sprint 4/29

## Relevant Links
[Process Page in Confluence](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3065708550/Date+Stamp+Adding+a+New+Step+to+Creating+and+Updating+Pages+on+Platform+Website)

**Comment by jknipes** [comment]
Acceptance criteria changed as details and scope of work were updated

**Comment by jknipes** [comment]
work completed, acceptance criteria met. Moving to _Done_
