### ISSUE TITLE
Implement GA Events for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7994]
## Goal
Now that we have the names for the different events that fire within "View Dependents" so that we can better track what is happening within the feature and have granular visibility into its behavior.

## Tasks
- [x] Take the event names from the GA team in this ticket (#6830) and put them into the "View Dependents" feature
- [x] Helper gets pulled in from platform and names get dropped in

## Acceptance Criteria
- [x] Events fire with the appropriate names
- [ ] A PR with these changes has been merged
