### ISSUE TITLE
2024 Tool Audit: Discovery: DataDog Monitors

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79954]
## Issue Description
As the Platform Product Team,
We need a better inventory of our tools, versions and features that are used,
So that we can better manage and report on what is used and how

Assess the current Platform monitors, the potential groupings, determine which monitors are worth keeping. Determine who are the owners. Establish tagging standards. 

We are also being asked by @tayism for a 'cheat sheet' list of the tools, services, or processes your team owns or manages so that Oddball and AdHoc knows who to notify when pointed feedback comes in.

Examples include:
- feature request process
- ideas for platform
- feedback in slack; feedback survey; platform surveys; etc

Some previous work towards this effort was done in #81177

Please document all findings for the tool from the audit in **[this Google document](https://docs.google.com/spreadsheets/d/1g07HFgncUu5qP3EfN-PYzbRgnEXWkFZT54-49aauyuY/edit#gid=803968964)**

---
## Tasks
- [x] Document audit findings in [the Google document](https://docs.google.com/spreadsheets/d/1g07HFgncUu5qP3EfN-PYzbRgnEXWkFZT54-49aauyuY/edit#gid=803968964)
- [x] Review Terraforms and adjust if too noisy
- [x] Assess the current Platform monitors
- [x] Assess the potential groupings
- [x] Determine which monitors are worth keeping. 
- [x] Determine who are the owners. 
- [x] Establish tagging standards. 

## Success Metrics
- [x] Cleaner monitor standardization

## Acceptance Criteria
- [x] Adjusted Terraforms
- [x] Grouped and streamlined monitors, if needed
- [x] More clear list of who owns the monitors
- [x] Tagging standards
- [x]  Areas of improvement are documented in the [Google spreadsheet](https://docs.google.com/spreadsheets/d/1g07HFgncUu5qP3EfN-PYzbRgnEXWkFZT54-49aauyuY/edit#gid=803968964) 
- [x] Future work is ticketed

**Comment by rmtolmach** [comment]
I worked through the google spreadsheet today. Completed 4 of 7 sections.

**Comment by rmtolmach** [comment]
➡️ I completed the google spreadsheet. One outcome was https://github.com/department-of-veterans-affairs/va.gov-team/issues/85524

➡️ I created a [Confluence page](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3213525492/Tool+Audit+Datadog+monitors) to document findings related to this ticket. 

✅ tagging standards was done by OCTO. Documented here: https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-tagging-standards

✅ **More clear list of who owns the monitors**: Creating our own list will be time-consuming and become out of date almost immediately. I recommend using the filters available at https://vagov.ddog-gov.com/monitors/manage?order=desc to find monitors based on ownership traits like "created by", "team", or "service". See Confluence doc linked above for more info.

**Comment by rmtolmach** [comment]
PR for some monitor cleanup: https://github.com/department-of-veterans-affairs/devops/pull/14442. 

**Review Terraforms and adjust if too noisy**
Some noisy ones are owned by devops. I don't want to mess around too much with their monitors so I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/85719 for them to be followed up on.

**Comment by rmtolmach** [comment]
@flooose merged the devops PR and applied the terraform. I confirmed the monitors were updated in the UI ✅ 

Only thing left to do it pass on the follow-up ticket to devops.

**Comment by rmtolmach** [comment]
- One more PR! https://github.com/department-of-veterans-affairs/devops/pull/14453

**Comment by rmtolmach** [comment]
Chris applied the terraform and I confirmed the UI picked up the most recent changes 🎉 We're good to close now.
