### ISSUE TITLE
2024 Tool Audit: Discovery: Sentry

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#79951]
## Issue Description
As the Platform Product Team,
We need a better inventory of our tools, versions and features that are used,
So that we can better manage and report on what is used and how

Since the initial deployment of various tools and software in our stack back in 2018, there have been continuous development and upgrades in these technologies. However, a methodical review to leverage new feature sets introduced in subsequent releases has been lacking. This gap in our process has potentially led to missed opportunities for enhancing our systems' efficiency, security, and performance.

A prime example of this situation is Redis (ElastiCache), which despite being upgraded, may not fully utilize features introduced in newer versions such as Cluster mode - which would allow for high availability via automatic failover and replication. This scenario could very likely extend to other components of our stack, such as Postgres, among others. Additionally, the absence of historical documentation on decision-making processes further complicates our ability to assess historical decisions.

We are also being asked by @tayism for a 'cheat sheet' list of the tools, services, or processes your team owns or manages so that Oddball and AdHoc knows who to notify when pointed feedback comes in.

Examples include:
- feature request process
- ideas for platform
- feedback in slack; feedback survey; platform surveys; etc

Please document all findings for the tool from the audit in **[this Google document](https://docs.google.com/spreadsheets/d/1g07HFgncUu5qP3EfN-PYzbRgnEXWkFZT54-49aauyuY/edit#gid=803968964)**

---
## Tasks
- [x] Sentry continuously improves its error grouping algorithms, notifications, and integration capabilities.
- [x] Addressing any bug fixes - look at internal errors
- [x] Review and Delegate any high volume of errors to teams
- [x] Prep to get folks off of Sentry - do an audit of all the event volumes to Sentry 
- [x] Link to Patrick V's work on Vets API that has already started [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+sentry+author%3Apatrickvinograd+) - Incorporate this into 1 sheet for next steps
- [ ] Brainstorm 1 sheet layout and migration path
- [ ] This work will have to be done for vets-api and vets website
- [ ] Start on 1 sheet for FE, BE and Devops 

## Success Metrics
- [ ] Options for future replacements for Sentry

## Acceptance Criteria
- [ ] Sentry audit logs and event volumes are defined
- [ ] 1 sheet documentation for all all three areas of discipline has been started + additional projects
- [ ] Resource is identified for the FE/Vets Website

**Comment by LindseySaari** [comment]
Are there folks that are using it?
How are they using it
Make sure we have parity and that the features can translate to Datadog

**Comment by LindseySaari** [comment]
I've started a doc for the [Sentry Deprecation and Migration Discovery (Vets API)](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3095134389/Sentry+Deprecation+and+Migration+Discovery+Vets+API)

**Comment by LindseySaari** [comment]
Jennifer has so kindly broken this out into additional tickets

Vets API Sentry deprecation and migration discovery - 81000
Vets Website Sentry deprecation and migration discovery - 81001
Devops Sentry deprecation discovery - 81002
A Migration guide for Vets API - 81004
Platform will be responsible for migrating some of these things - so a Platform migration ticket will be necessary - 81006
We may even need a ticket to identify ownership of Platform Sentry items - 81007
Maybe a placeholder ticket to nudge VFS folks to migrate their things to Sentry - 81008
How to migrate PII scrubbing from Sentry to Datadog - 81010

Ror the ticket for this sprint, I'm going to work on the initial one page to lay the groundwork for the above tickets. I will have Kshitiz get a feel for the lay of the land in devops world and at minimum, we should identify a FE resource.

**Comment by LindseySaari** [comment]
I [asked for some help from the FE CoP](https://dsva.slack.com/archives/C04868KS69L/p1713544353447089) for the Vets Website portion of the migration/deprecation work.[ Sentry tool audit docs](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3095593227/Tool+Audit+Sentry) were created here.

**Comment by LindseySaari** [comment]
[The Sentry tool audit directory and corresponding docs](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3095593227/Tool+Audit+Sentry) are in a good place for the next round of research. There's a space for the Vets API, Vets Website and Infrastructure research and discovery. There exist other projects in Sentry that are actively receiving events. We will need to identify owners and assist with the deprecation path as well. The ground work for the next phase of work is in place.
