### ISSUE TITLE
[spike] DR | PDF decryption issue

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#79961]
## Background Context

This is a task to perform an in-depth investigation of alternative tools to decrypt PDFs. `vets-api` currently uses `pdftk` to perform PDF decryption, which has not been updated for over 10 years and thus does not support the newer PDF standard which allows files to be encrypted with AES-256. 

## Tasks
- [x] Investigate alternatives to PDFTK that support newer encryption methods
  - [x] `qpdf`
  - [x] `HexaPDF`
- [x] Request feedback from backend COP regarding centralization and best team to handle this
- [x] Create a spike for frontend investigation (#82670)

## Definition of Ready
- [ ] Whoever picks this up has access to our S3 bucket

## Definition of Done
- [ ] Follow-up tickets for development tasks have been created
- [x] Time box 5 hours max

**Comment by dfong-adh** [comment]
Comment from sprint review:
> Cory did a [write up on an alternative](https://gist.github.com/CorySohrakoffUSDS/a8c4784f4a08eb2bed562c7324746839) for the CST team

**Comment by saderagsdale** [comment]
- Shaun talking to Cory tomorrow (may pull in Steve) to ask if this can go to the platform team.

**Comment by dfong-adh** [comment]
Will sync with Shaun and post an update

**Comment by dfong-adh** [comment]
Backend COP meeting on Monday (9:15) - to discuss the best way to handle this ticket with platform.

**Comment by saderagsdale** [comment]
@dfong-adh Hey! Any good news from COP?

**Comment by dfong-adh** [comment]
COP slack thread with discussion: https://dsva.slack.com/archives/C0460N83Y9G/p1714615111455679

**Comment by saderagsdale** [comment]
Ask Cory to follow up with CoP (or Steve).

**Comment by dfong-adh** [comment]
Created a plan doc: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/architectural-decision-records/pdf-decryption-support-plan.md

**Comment by dfong-adh** [comment]
Support request: https://dsva.slack.com/archives/CBU0KDSB1/p1715961923509259

**Comment by dfong-adh** [comment]
> Platform however is not currently available own this feature request.

**Comment by dfong-adh** [comment]
Created #83503 as a followup task.
