### ISSUE TITLE
[CDP] VHA- Expand "Pay online" component and add account number - Part 2

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#79964]
## Description

Given: A veteran wants to see their account number for a copay bill
When: They look at their copay detail and copay HTML statement pages
Then: They should clearly be able to see their account number and be able to pay their copay bill from the HTML statement page

<details>
  <summary><strong>Current Copay Summary page:</strong></summary>
  <img width="751" alt="Screenshot 2024-03-26 at 11 29 55 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/183af115-056b-47f1-90e3-47d9d1fdfeb4">
</details>

<details>
  <summary><strong>Current Copay Detail page:</strong></summary>
  <img width="750" alt="Screenshot 2024-03-26 at 11 29 45 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/a6bb286a-6539-4354-bd10-12c30282f1e4">
</details>

<details>
  <summary><strong>Current HTML Statement page:</strong></summary>
  <img width="793" alt="Screenshot 2024-04-04 at 4 57 24 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/dea8f0a3-a914-4506-bcbc-c3734a0b9174">
</details>

This is part 2 of the updates to make the account number more accessible. [Part 1 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79257) needs to be completed first. 
## Tasks
- [x] In the **How to pay your copay bill** section, move pay online accordion out of an accordion on the copay summary and copay detail pages
- [x] Add Account number to [HTML statement page](https://www.figma.com/file/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?type=design&node-id=117-27779&mode=design&t=NEe2DYKOWGCt3FlE-11) and how to pay options.

## Acceptance criteria
- [x] Part 1 has been completed #79257
- [x] Pay online section has been moved out of the accordion and is the default method
- [x] HTML statement has the account number on the page and ways to pay

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@denisecoveyduc, here's the part 2 of the account number ticket we talked about in our design sync earlier this week.

cc: @mgleo @charlottecesana @HeatherRienks @Tom-Davis

**Comment by josephrlee** [comment]
@Tom-Davis @HeatherRienks @mgleo I'm bringing this ticket into the current sprint since the work for Part 1 was finished really quickly.

**Comment by Tom-Davis** [comment]
@josephrlee will this impact any planned sprint work? We really want to make sure we have little to no rollover at the end of the sprint.

**Comment by josephrlee** [comment]
@Tom-Davis, sorry for not responding sooner. This won't block any other work, as we've been in a little bit of planning limbo on the other current tickets, which we chatted through and got some more answers about during today's design/research sync.

**Comment by josephrlee** [comment]
@denisecoveyduc, here are the updated designs for the Pay Online section, if these look good, I can go ahead and implement them! 

Here's a summary of the changes I've made in addition to adding the account number and having the pay online accordion be open by default:

1. For all the pages, I moved the pay online section out of the accordion into its own content block.
2. For the **HTML Statement page**, I added the account number at the top below the **balance activity**. 

| | Current | Proposed |
| -------- | -------- | ------- |
| **Copay balances summary pages** | ![Copay balances summary page before](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/75706dc8-6ad4-4149-8f78-4a7e9d444399) | ![Copay balances summary page after](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/e847cf73-473f-446b-91fe-f029820bc438) |
| **Copay detail page** | <img width="750" alt="Copay-Detail-Before" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/36cb3e84-3c3f-4c1b-a537-d7bb1abadf5a"> | <img width="750" alt="Copay Detail After" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/5a0c34cb-e0c7-4ac0-b967-7cdd6331a1fe"> |
| **Copay HTML statement page** | ![Copay HTML statement page before](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/3397a454-123b-41eb-b088-dfc3f35021af) | ![Copay HTML statement page after](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/0924b76a-4977-4bdd-ac80-a0659364432e) |

cc: @mgleo @charlottecesana @HeatherRienks @Tom-Davis

**Comment by denisecoveyduc** [comment]
Thanks @josephrlee Looks great! Please proceed to implement.
