### ISSUE TITLE
Burial | List of Form URLs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#79977]
## Issue Description
_In order to request a KPI dashboard from the Platform Analytics Team, we need to provide them a list of form urls. Laura started compiling a list of urls, but it may not be comprehensive._

---
## Tasks
- [ ] Compile a list of Burial form urls and add them to [this sheet](https://docs.google.com/spreadsheets/d/1ptfQI71LP85un1kXfrwOwzwbl9VYKrjBVHxLCBlyAgQ/edit?usp=sharing)
- [ ] Indicate on the sheet if they are conditionally seen by the user

## Acceptance Criteria
- [ ] [Sheet ](https://docs.google.com/spreadsheets/d/1ptfQI71LP85un1kXfrwOwzwbl9VYKrjBVHxLCBlyAgQ/edit?usp=sharing)contains list urls and denotes if they are conditionally seen
---

**Comment by DLarson-Oddball** [comment]
@steele-lm I checked the form and added 2 lines. Also checked the box for one conditionally rendered page. Thanks!
