### ISSUE TITLE
Implement GA Events for "Submit 686"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7999]
## Goal
Now that we have the names for the different events that fire within the actual 686 application form itself so that we can better track what is happening within the feature and have granular visibility into its behavior.

## Considerations
- This ticket is to put the names in, we will need to test once the form submits, captured in [#7560](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8705)

## Tasks
- [x] Take the event names from the GA team in this ticket (#7560) and put them into the 686 application form

## Acceptance Criteria
- [ ] Events fire with the appropriate names
- [ ] A PR with these changes has been requested
