### ISSUE TITLE
Refresh Domo Data Dictionaries w/ GA4 Changes

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#79996]
### Description
With the new GA4 data model being different than UA, we will need to update our data dictionaries to reflect some of the GA4 calculations.

---

### Tasks
- From findings based on GA4 data model, look to update the following data dictionary pages.
- [x] [Data dictionary: VA.gov Forms KPIs](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-forms-kpis)
- [x] [Data dictionary: VA.gov Search KPIs](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-search-kpis)
- [x] [Data dictionary: VA.gov Content KPIs
](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-content-kpis)

- For each table, add a new column titled **How is this different than GA4?**
- Include the cut-over date for GA4 in the column
- Indicate the refresh/cycle
- Due to nature of GA4 vs UA, you can expect this..
- Describe any notable changes in metrics/data -- (e.g. counts appear to be higher, lower, in GA4 based on etc, etc.)
- Make decision on whether to keep, temporarily remove, or re-write the _**How should I use this column?**_
- Validate new terms with Jamie and Team before publishing.

### Acceptance Criteria
Data dictionary pages on Platform Website have been updated with a review, a GA4-changes column, and a team review, for the following Platform Website data dictionary pages

- [x] Forms KPIs
- [x] Search KPIs
- [x] Content KPis

**Comment by dorseypa1** [comment]
It is too early to refine this ticket.  We an additional ticket(s) between this ticket and the GA4 Discovery: Research on Key Events within GA4 ticket that involves defining how the metrics are determined intr-team before we can share how our users can understand them in the reports.

**Comment by ChristineYoungZA** [comment]
The data dictionary draft website has been updated, the differences column needs to be reviewed by Jamie.

**Comment by johnny-jesensky-adhoc** [comment]
We plan to review these definitions and changes a final time before we publish. We want to make sure that the information is accurate, as we expect them to be heavily reference with the transition to GA4. 

This is carrying over into next sprint, likely to be published sometime in the next couple of weeks.

FYI @jwoodman5, @davidconlon, @raywangoctova, @ChristineYoungZA

**Comment by johnny-jesensky-adhoc** [comment]
Adding myself as an assignee to help get this over the finish line while Christine is out.

**Comment by johnny-jesensky-adhoc** [comment]
Page edits published on Platform Website today, July 17, 2024. We will continue to monitor for feedback.

- [Data dictionary: VA.gov Forms KPIs
](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-forms-kpis)
- [Data dictionary: VA.gov Search KPIs](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-search-kpis)
- [Data dictionary: VA.gov Content KPIs
](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-content-kpis)

Marking this as _Done_.

FYI @ChristineYoungZA
