### ISSUE TITLE
[PM] 10-10EZ - Submission fail Notifications: Attend any discussions with VA Notify

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#79997]
## Background
We currently use GovDelivery to email Veterans when their application fails all submission retries.  We need to move this function to VA Notify, as the target state system for emails to Veterans.  This will allow us better control over the messaging, while also aligning our product with target state initiatives.

## Tasks
- [x] Attend meetings with VA Notify
- [x] Take notes & save in the [Meeting Notes folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Submission%20Failure%20email%20notifications/Meeting%20Notes)
- [x] Document any decisions made

## Acceptance Criteria
- Team meets with VA Notify team to confirm understanding of our needs and commits to collaborating and providing information and support where needed.
