### ISSUE TITLE
Create Veteran Support GitHub Automation Page/Office Hours 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#80004]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

Creating a Platform Page for Veteran Support. VFS teams will gain visibility to our product and service. 

## High Level User Story/ies

As a VFS team, I need to know how to submit a data requests, create Medallia surveys, and how to view Salesforce Dashboard. 

## Hypothesis or Bet

**If the Veteran Support team creates a platform page, then we make our services visible to all VFS teams.

## OKR

- Increase in qualitative data requests
- Number of views by report/dashboard published
- Number of reports/dashboards published

### To complete this epic: 
- [x]  We will add an automated Git Hub ticketing system to our Slack Channel 
- [x]  We will create office hours for teams to join weekly 
- [x]  We will develop content required for the platform page

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by UXCamG** [comment]
Setup syncs with Brian Deconinck to discuss GH automated ticketing in Slack, and also Naomi Murchinson to discuss setting up office hours/ platform page content requirements.

**Comment by starlow00** [comment]
I audited the Veteran Support repository intro text and links. Also updated Tier 3 definition and process page text (attached).

We likely want approval before pushing the updates through on the Tier 3 page. I took the old material and merged it with a more recent version put together by @Kimberley2023-CSM 

Kimberley, since you wrote the latest that appears in our Teams folder, can you please review the attached?

[Defining Tier 3 SRT 04112024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bab423f5c13ede9cd79817368778ef7964811fa/Defining%20Tier%203%20SRT%2004112024.docx)

**Comment by UXCamG** [comment]
We have office hours every Wednesday from 3:30 pm EST.

**Comment by UXCamG** [comment]
We have office hours every Wednesday from 3:30 pm EST.

**Comment by starlow00** [comment]
@Kimberley2023-CSM et al: I forgot to mention that the Word doc with the new Tier 3 process language will be outward-facing on our team's GitHub (if that wasn't already apparent). You included a diagram of a "tier funnel" in your original document that might actually be good to keep in the outward-facing content. This is something to consider when you do your review for next week. Thanks!

**Comment by Kimberley2023-CSM** [comment]
@starlow00 this update looks great.  Very simple and to the point.  I appreciate your tackling of this and approve it.

**Comment by UXCamG** [comment]
Automated GitHub ticketing has been created for data requests, and product guide reviews.  There will be an additional ticketing processes for custom survey in-take requests upon its completion. 

Office hours were set up on Calendly. We have standing meeting on Wednesday at 3:00- 3:30pm EST .

**Comment by starlow00** [comment]
Veteran Support content review complete/approved as noted by @Kimberley2023-CSM.
