### ISSUE TITLE
[BUG] VaSelect shows two select options

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#80016]
## Background Context
Where we updated va-select V1 component didn't have a 'Select' option and we had to add that to the list of options. Where as the va-select V3 component has that field added as a part of the component so we dont have to add a 'Select' option to the list of options. 

V1 Component 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTQyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c2627c2847fa5c1cfa895a871aca32f08efc243/Screenshot%202024-04-04%20at%2010.55.43%E2%80%AFAM.png" alt="Screenshot 2024-04-04 at 10.55.43 AM.png" />

V3 Component 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTgyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31c72b8c2a2c8582fbca86981db1ed240023c815/Screenshot%202024-04-04%20at%2010.56.40%E2%80%AFAM.png" alt="Screenshot 2024-04-04 at 10.56.40 AM.png" />

### Bug
The va-select components that we updated to V3 need to have the 'Select description' option removed from the list of options. 
<img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlEyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81fde1ed44736fc2d5674d152697093cefb5bfc4/Screenshot%202024-04-04%20at%2010.58.25%E2%80%AFAM.png" alt="Screenshot 2024-04-04 at 10.58.25 AM.png" />

## Tasks
Update the following files
- [ ] AddFilesFormOld
- [ ] AddFilesForm

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The va-select web components no longer have two select options and only have the default select that is a part of the V3 component

**Comment by pmclaren19** [comment]
verified in staging and looks good!
