### ISSUE TITLE
Review and analysis of dashboards that use UA data from Github Form

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#80021]
### Description
When we send our the Github form requesting teams to identify their dashboards, we'll want to devote time to review the submissions, and take inventory of the types of reports we are seeing.

This information on the VFS reporting landscape will help us identify what types of reports teams are generally dependent on, so we can work to prioritize our custom our training and guidance.

[Artifact](https://docs.google.com/spreadsheets/d/1xDWAyKt-2lS5RsRhXBk5EA08-RM3qomJi1EqTjQ48sE/edit#gid=0)
---

### Tasks
- [x] Review VFS Reporting Inventory from Github form submissions on Zenhub 
- [x] Assessment of what percentage of reports are being flagged as UA dashboards, Domo, Looker, etc.
- [x] Share findings with team to identify reporting training and update strategy.
- [x] Add commonly used metrics and dimensions used in reports.

### Acceptance Criteria

- [x] Reports have been reviewed.
- [x] An artifact that shows the percentage of reports for each reporting platform (Domo, Looker, etc)

**Comment by johnny-jesensky-adhoc** [comment]
JJ to build this out.

**Comment by johnny-jesensky-adhoc** [comment]
Moving this to _Done_. Will be creating a follow-up task for this.

https://dsva.slack.com/archives/C01S78V4AUA/p1714575601325959?thread_ts=1714408405.221269&cid=C01S78V4AUA

FYI @ChristineYoungZA, @Blivaditis
