### ISSUE TITLE
[FE] My VA Ben App Drafts: Simplify the SiP configuration (pt 1) - data collection etc.

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80031]
## Background
Following up from Angela's work on the benefit application drafts section documentation [60510](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510), it was determined that the current process to configure a form as "save in progress" (SiP) is not as streamlined as it could be.

[Additional context](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510#issuecomment-1658652021)

We are breaking this work into three parts:
- _part 1: data collection and communication with other teams_
- part 2: implementation and testing ([#80036](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80036))
- part 3: documentation updates ([#80037](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80037))

## Tasks
- [x] Determine what meta data we're pulling from each existing form configured as SiP to My VA
- [ ] Determine if we can use a feature flag for this

## Acceptance Criteria
- [ ] Create or update Benefit Application Drafts FE documentation with findings/data points

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_

## Resources
- [Technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)
- [SiP enabled form table (via AJ)](https://docs.google.com/spreadsheets/d/1kra-6J4y3qJxthaS1s4IPgrNLAB7a0qq3a5_m1KDiKM/edit#gid=0)

**Comment by allisonlu** [comment]
we can reduce this to 3 points for sprint 35!

**Comment by allisonlu** [comment]
## Metadata 

Metadata that is needed (and/or being utilized)

### in the [`ApplicationInProgress` card](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/benefit-application-drafts/ApplicationInProgress.jsx):
- Form ID (e.g. 10-10D, 10-10EZ)
- Casual/common name (e.g. application for champva benefits, health care benefits)
- Form link (e.g. /10-10D)
- is SiP enabled (e.g. true)

### in [`/dashboard/helpers.jsx` file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/helpers.jsx):
`presentableFormIDs` function
- FORM_BENEFITS

`isSIPEnabledForm` function
- FORM_TITLES
- SIP_ENABLED_FORMS
- TRACKING_PREFIXES

---

## Feature flag

I'm not sure if we're able to use a feature flag for this, but let's check w Adam on Monday

**Comment by ajakabcin** [comment]
Allison confirmed that we will be able to do a feature flag for this - closing!
