### ISSUE TITLE
[FE] My VA Ben App Drafts: Simplify the SiP configuration (pt 2) - implementation & testing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80036]
## Background
Following up from Angela's work on the benefit application drafts section documentation [60510](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510), it was determined that the current process to configure a form as "save in progress" (SiP) is not as streamlined as it could be.

[Additional context](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510#issuecomment-1658652021)

We are breaking this work into ~three~ five parts (as of 5/9/24):
part 1: data collection and communication with other teams (#80031)
_part 2: implementation and testing_
part 3: documentation updates (#80037) 
part 4: cleanup and reduce (#82798)
part 5: remove and convert (#82817)

## Tasks
- [x] Open PR on `vets-api` for new feature flag: https://github.com/department-of-veterans-affairs/vets-api/pull/16700
- [x] Create a new object in **platform/forms/constants.js** that contains the necessary meta data (collected in previous ticket)
- [x] Write unit and e2e tests if needed
- [ ] Validate and request validation/testing from other form team owners 

## Acceptance Criteria
- [ ] all the necessary metadata is in a `MY_VA_SIP_FORMS` array of objects that appears in this [platform/forms/constants.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js) file

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_

## Resources
- [Technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)

**Comment by allisonlu** [comment]
I _may_ be overthinking this... so I will continue working on this on Monday after our meeting w Adam

## idea 1: keeping `VA_FORM_IDS` as-is, creating new `MY_VA_FORMS` object

To improve, I want to create `MY_VA_FORMS` by mapping through `VA_FORM_IDS`, and adding metadata properties. The downside of this approach is if a team wants to add a new form, they (or someone on My VA) will have to add it in two places: `VA_FORM_IDS` and `MY_VA_FORMS`.

```
export const MY_VA_FORMS = new Set([
  {
    id: VA_FORM_IDS.FORM_10_10D,
    benefit: 'application for champva benefits',
    title: 'application for champva benefits (10-10D)',
    description: 'application for champva benefits application (10-10D)',
    link: '', // will check with Adam about this property
    trackingPrefix: '10-10D-',
    isSipEnabled: true,
  },
  ...
]);
```

## idea 2: edit `VA_FORM_IDS` completely with an object shape similar to the above

This will require updates to `/platform/forms/helpers.js` in addition to `/dashboard/helpers.jsx`, so we will need code reviews from the Platform team. But we will need to edit in one place.

```
export const VA_FORM_IDS = new Set([
  {
    name: 'FORM_10_10D',
    id: '10-10D',
    benefit: 'application for champva benefits',
    title: 'application for champva benefits (10-10D)',
    description: 'application for champva benefits application (10-10D)',
    link: '',
    trackingPrefix: '10-10D-',
    isSipEnabled: true,
  },
  ...
])
```

**Comment by allisonlu** [comment]
wrapping up for this ticket now. we can update to **2 points** for sprint 36

**Comment by ACParker89** [comment]
@DanielMiller-agile6 - validation

**Comment by allisonlu** [comment]
## to validate:

**on staging:**
- confirm that `my_va_enable_new_sip_config` feature flat shows up on [staging feature flag UI](https://staging-api.va.gov/flipper/features)
- toggle it on and make sure there are no visible breaking changes 

**in the code:**
- confirm that all the new code has indeed been [merged into the `main` branch](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L292)

**Comment by allisonlu** [comment]
@ajakabcin 

keeping this ticket open/in validate for sprint 37 and giving it 1 point for testing purposes, once #83536 gets resolved

**Comment by allisonlu** [comment]
closing this as #83536 has been resolved (@ajakabcin and i validated in staging with Tricia today with success!)
