### ISSUE TITLE
[FE] My VA Ben App Drafts: Simplify the SiP configuration (pt 3) - documentation updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80037]
## Background
Following up from Angela's work on the benefit application drafts section documentation [60510](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510), it was determined that the current process to configure a form as "save in progress" (SiP) is not as streamlined as it could be.

[Additional context](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510#issuecomment-1658652021)

We are breaking this work into ~three~ five parts (as of 5/9/24):
part 1: data collection and communication with other teams (#80031)
part 2: implementation and testing (#80036) 
_part 3: documentation updates_ 
part 4: cleanup and reduce (#82798)
part 5: remove and convert (#82817)

We know we'll need to update the developer documentation around SiP configuration [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si#VAFormsLibrary-HowtosetupSaveInProgress(SiP)-MyVAPage), but we should also look at the documentation around digitizing forms [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/a-guide-to-digitizing-va-forms) and consider proposing an update there as well. That piece can be supplemental/a separate ticket if needed.

## Tasks
- [x] Draft updates to platform developer documentation around SiP configuration
- [x] Update instances of `getAppUrl` to `getAllFormLinks` in the second bullet under "[My VA Page](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si#VAFormsLibrary-HowtosetupSaveInProgress(SiP)-MyVAPage)"
- [x] Submit to Platform for updating 

## Acceptance Criteria
- [x] Documentation is updated on the platform site.

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Confirm documentation is updated

## Resources
- [Technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)

**Comment by ajakabcin** [comment]
@allisonlu rethinking the workload here for you - I'm going to pull this out of the sprint and if you end up with bandwidth we can bring it back in
cc @ACParker89

**Comment by allisonlu** [comment]
Opened up a PR for Platform: https://github.com/department-of-veterans-affairs/va.gov-team/issues/86759

It seems to be added to their old backlog, so I'll check back in a few days to see if anyone has addressed it.

**Comment by allisonlu** [comment]
PR has been acknowledged and added to their backlog 😊 

I will consider this blocked until the updates are made

**Comment by ACParker89** [comment]
@ajakabcin moving this to blocked and we will need to 
roll to sprint 40 as a 1 pt story

**Comment by allisonlu** [comment]
Changes are now live on the Platform docs!

https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si#VAFormsLibrary-HowtosetupSaveInProgress(SiP)-MyVAPage

**Comment by ajakabcin** [comment]
Confirmed documentation is updated!
