### ISSUE TITLE
Sync AWS Maintenance Windows with PagerDuty

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80030]
## Description
Our tools regularly undergo maintenance. Maintenance windows within AWS include various operations, including software updates, security patches, and system upgrades  (planned and unplanned - example: a CVE patch). However, these maintenance activities are not currently reflected in PagerDuty, leading to potential alert fatigue and unnecessary escalations during planned downtimes. To streamline our incident management process and reduce noise for oncall folks, we need a solution to automatically sync AWS maintenance windows with PagerDuty maintenance windows.

This ticket is intended to capture maintenance window events and plan for automation for PagerDuty.

## Tasks
- [ ] Research integration options - How do we integrate this with Pagerduty
- [ ] Develop the necessary configurations required to support the automatic syncing of maintenance windows
- [ ] Document the integration process. Ensure that the team is aware of how to schedule maintenance windows in AWS with the new syncing process in place.

## Success Criteria
- [ ] That there is a path forward with synching AWS Maintenance Windows with PagerDuty, _or_ that it is determined that it is not possible to do so. 

## Acceptability Criteria
- [ ] A maintenance window scheduled in AWS automatically creates a corresponding maintenance window in PagerDuty
- [ ] Updates or cancellations to AWS maintenance windows are reflected in PagerDuty
- [ ] Documentation is provided and up to date

**Comment by jennb33** [comment]
This is the command that @rjohnson2011 is running:
**aws ssm describe-maintenance-windows --output json > maintenance_windows.json**

**Comment by jennb33** [comment]
@rjohnson2011 is working with @LindseySaari and @Kshitiz-devops 
This may need a credential for PagerDuty in order to link it to PagerDuty, @rmtolmach may be an admin that can help

**Comment by jennb33** [comment]
Duplicated by [85083](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/85083) for 1 story point in Sprint 2
