### ISSUE TITLE
Add "ask users for a single response" pattern to descriptive tags

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80043]
## User Story
As a Governance team member, I want to be sure that the DraftingTemplate lists all descriptive tags so that I'm able to add them to SR issue tickets when applicable. 

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
There's a [new pattern](https://design.va.gov/patterns/ask-users-for/a-single-response) in the VA Design System that we must add to our descriptive tags to ensure it can be flagged in future Staging Reviews if applicable.

Please be sure to follow the [VA.gov Experience Standards guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) for maintaining our VA.gov Experience Standards and descriptive tags. 

## Impacted Artifacts
DraftingTemplate - both VFS and DST
[VA.gov Experience Standards guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags)

## Tasks
- [x] follow the VA.gov Experience Standards guidance for adding a new descriptive tag

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The new descriptive tag has been added to all applicable VA.gov Experience Standards guidance. 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
FYSA @erinrwhite

**Comment by it-harrison** [comment]
@briandeconinck this is ready for review

**Comment by briandeconinck** [comment]
@it-harrison This looks good to me! Feel free to close it out
