### ISSUE TITLE
Full Accessibility & 508 Office Audit [Address Validation]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8006]
## Steps to complete the Full Accessibility & 508 Audit: 
- [X] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *Address Validation*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts when you request a full review_
- Access information for the tool or feature in staging _
[staging credentials](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/authenticated-experience/test-credentials.md)
- Link to your accessibility test plan:
  - **TestRail** [Address Validation Test Plan](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&group_id=58) 
## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

**Comment by 1Copenut** [comment]
@jenstrickland I'm removing myself from this one. I've got a few other commitments this week, but please let me know if you need an extra hand or have items you'd like to discuss.

**Comment by jenstrickland** [comment]
@1Copenut Beat me to it. Just been on calls. I'm all good.

**Comment by jenstrickland** [comment]
Sent to VA 508 Office for review on April 15, 2020. When their report arrives, will update.

**Comment by Samara-Strauss** [comment]
Great! Thanks @jenstrickland. We'll keep an eye out for that review. Just out of curiosity, do they have an average turn-around time, or is it hard to say? I'm wondering if we should plan for results in a couple days, a week, longer, etc.

**Comment by jenstrickland** [comment]
@Samara-Strauss the turnaround time varies from a couple of days to a couple of weeks, depending on the workload in the office.

**Comment by Samara-Strauss** [comment]
Got it. Thank you for letting me know!

**Comment by jenstrickland** [comment]
The VSA 508 Office didn't find anything new!
They did find the gnarly JAWS+IE11 issue, and I let them know it's a sitewide issue.
Great job! :tada:
