### ISSUE TITLE
Copy of Add Landing Page + Table on Research & Design Spaces

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80063]
## Issue Description
For uniform appearance and consistent experience across all spaces in Platform Website, we need to add a landing page with table to the Research & Design space.

---
## Tasks
- [ ] Add landing page to Research & Design space
- [ ] Create table on landing page with 4 sections: **Last Updates**, **Research and Design**, **Research at VA** and **Design at VA**
- [ ] Create new page: **Last Updates,** 1st page in IA and before Research and Design 
- [ ] add Last Updated list to the page using Confluence element `/update`
- [ ] Link each page to its respective section in the table

## Acceptance Criteria
- [ ] Landing page and table with links are functional and there are no LBs
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
landing page and table created May 24, 2024. Closing as _done_.
