### ISSUE TITLE
Addition of general "call first" language to top of Facility Locator page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8008]
## User Story or Problem Statement
How might we encourage Veterans to 
1- call facilities before visiting
2- inquire about remote service options

## Goal
Veterans will be generally advised to call before visiting facilities to confirm hours of operations and remote service options 

## Objectives or Key Results this is meant to further
Objective 2: Deliver meaningful facility information 

### **Current behavior**

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bbc4250d-931c-4010-b30a-25e40f57c67f)

### **Expected behavior** 

The text added to results of urgent care + community care providers search will be maintained. (recently added in [#7502](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7502))

---
## Tasks
- [ ] Replace top text paragraphs with the following version:  

> Find one of VA's more than 2,000 health care, counseling, benefits, and cemeteries facilities, plus VA's nationwide network of community health care providers.
> 
> **Coronavirus update**: Many VA and community provider locations have changing hours and services due to COVID-19. For your safety, please call before visiting any location to ask about getting help by phone or video.
> 
> **Need same-day care for a minor illness or injury?** Select Urgent care under facility type, then select either VA or community providers as the service type.
> 

- [ ] When a Veteran searches urgent care + community urgent care providers (in VA's network), search result cards include the following text (as existing functionality)
> Before going to a clinic for urgent care, please call the facility to confirm that it's open and able to provide the care you need.

## Acceptance Criteria
- [ ] When a Veteran arrives on Facility Locator landing page, the new language is displayed above the search boxes.

**Comment by mmiddaugh** [comment]
Language will need to be approved by COVID task force before implementation

**Comment by davidconlon** [comment]
@brangi @mmiddaugh attached is the final language.
Hopefully self-explanatory of "This is what it is" to "This is what it should be".

[https://app.zenhub.com/files/133843125/831651b4-fdcd-4110-baa3-d1591bcda6d2/download](https://app.zenhub.com/files/133843125/831651b4-fdcd-4110-baa3-d1591bcda6d2/download)

**Comment by mmiddaugh** [comment]
Text substituted in description of issue
