### ISSUE TITLE
2024 Sentry Deprecation

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80122]
## Product Outline
The Sentry tool will be deprecated. The 90 day notice of migrating the errors to DataDog is effective as of 4/5/2024. 

## High Level User Story/ies
As a developer on the VA Platform,
We need to migrate errors from Sentry to DataDog, 
So that errors are captured properly and Sentry can be safely deprecated with no gaps. 

## Hypothesis or Bet
If this change is made, then Sentry can be deprecated and removed with no issues and errors missed.

## OKR
O1. Our digital experiences are the best way to access VA health care and benefits
OKR3. All new products have a faster transaction time than those they replaced

## Definition of done
Error information from Sentry is migrated to DataDog, tested for completeness, and Sentry tool is deprecated. 
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80160
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82531
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90707
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79198
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91711
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91712
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86067
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80154
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80157
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81006
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81007
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81008
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81010
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/81039
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79609
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65929
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65587
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65927
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79947
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87171
```

**Comment by LindseySaari** [comment]
We will need to [take the Discovery from this ticket ](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/79951)to start the deprecation process. Keep in scope that we will need to analyze both the Vets API project and the Sentry project.

**Comment by AshleyGuerrant** [comment]
Hi @LindseySaari & @flooose - is this epic still relevant? Thanks in advance!

**Comment by AshleyGuerrant** [comment]
@flooose - thanks for the additional context. I am going to close this ticket out as wont fix for now, and we can reopen/rescope it later if it is identified as a priority initiative.
