### ISSUE TITLE
Finalize couple userflow options 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#80123]
## Tasks

- [ ] Finalize couple of userflow options
- [ ] Provide impact/feasibility of each 
- [ ] Based on impact/feasibility of each, identity a "Best Bet"
