### ISSUE TITLE
Static Landing Page for 686 Changes from eBenefits

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8012]
## Why you're here
- Content support for static public website pages
- Content support for authenticated application or tools
- For specific copy editing tasks
- Support for redirects that have **first been vetted by the VSP IA team**
- Engineering support for implementation of REACT sign in widgets

## Steps to complete intake request
- [x] Submit this request when VSA Public Website team intervention is required
- [x] Provide detailed information of your request to help us understand our role in completing your request 
- [x] Link to this issue in #vsa-public-websites in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Background
*Provide a background of your tool/functionality:*
Form 21-686c/674 is the form that allows a Veteran to add, remove or change their dependents and how they would be attached to an award or benefit.  We have included the View portion of this application to have a significantly different call out for the Veteran in order to make a more present and informed decision on what steps to take next.

The current landing page redirects Veterans to the legacy eBenefits site and does not reference the View portion of what we are providing, but there is a great deal of important information that has been preserved and reworked into the proposed landing page.

We have almost completed the rebuilding of the application for the Form 21-686c/674 and would like to modify the landing page so that we can better represent the functionality a Veteran will experience.  Most of this is some rearrangement and addition of words but closer to launch we will request the addition of some HTML around the first and second login widget, that we will provide below, that will allow Flipper to adjust traffic redirects for a graduated, controlled rollout.
- We would like this link: [/disability/add-remove-dependent](https://www.va.gov/disability/add-remove-dependent/) changed to reflect the content on this mockup and made to this url: [/view-change-dependents/](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/).  Please note that the `disability` hub has been removed; this will simply be off the root.
  - This is supported by IA in [this recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md)
  - The tool page is being updated in staging to reflect this: `/disability-benefits/new-686/` - to be updated to: `/view-change-dependents/add-remove-form-686c/` per [#8108](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8018)
- HTML to replace first login widget/section:
```diff
<div data-widget-type="view-dependents-CTA" id="view-dependents-CTA"></div>
```
- HTML to replace second CTA widget/section:
```diff
<div data-widget-type="686UnauthContentBlock" id="686ContentBlock"></div>
```
[Image: Code to replace second widget](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/images/VA_View_Dependents_Screens_W3_html.jpg)

### Request Type
*Select all applicable and provide details behind your request* 

- [ ] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * Word document with draft if available, or link to the URL where the draft content appears:
      * < link > 
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * < design context >
   * Scope: How many screens? (Or messages, etc.) 
      * < scope > 
      
      
- [x] **Content support for a static public website page**
   * Is this to update existing static content? 
      * Yes
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * Yes
   * Provide a list of URL/s that need to be reviewed or updated. 
      - We would like this link: [/disability/add-remove-dependent](https://www.va.gov/disability/add-remove-dependent/) changed to reflect the content on this mockup and made to this url: [/view-change-dependents/](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/).  Please note that the `disability` hub has been removed; this will simply be off the root.

- [ ] **New URL or Redirect Requests**
   * Have you vetted this request by the VSP IA team?
      * < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * Link to VSP IA Redirect Request ticket
      * < Github issue link >
      
   
- [ ] **Implementation of REACT sign in widgets**
   * Full spec including different states and behaviors
      * If needed 
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*

* We hope to have a first version in production by **May 6, 2020**, but realize that that date might change

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: eBenefits
- DEPO product owner: Steve Kovacs (@ steve-gov / @ stevek)  
- Product manager: Jason Wolf (@ jason-gcio / @ jason)   
- Designer: James Adams( @ sporeboy / @ Jim Adams)  
- FE engineer: Jesse Cohn ( @ cohnjesse / @ Jesse Cohn)  
- Product/team Slack channel: #vsa-ebenefits  
  

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by jason-gcio** [comment]
Here is a link to the mock up we were working with: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/ in case it helps.

**Comment by cohnjesse** [comment]
Here is the HTML for the first flipper component 
```
<div data-widget-type="view-dependents-CTA" id="view-dependents-CTA"></div>
```

**Comment by jason-gcio** [comment]
@stephorkandatx - had a quick question on this...when its all ready to go, can we keep in draft to review it and time our release with it hidden?

**Comment by stephorkandatx** [comment]
@lunascoop can you confirm that we will be able to keep this in draft form/"hidden" until eBenefits team is ready to release?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @stephorkandatx @jason-gcio. Not sure if the question above was answered yet, as I know @lunascoop was out on Friday. Yes, we can keep the page as a draft in Drupal until the tool is ready so that they can launch together. We'll just need to coordinate timing for when we publish the new page and redirect the existing page's url, so please just keep us informed on timing. Thanks!

**Comment by jason-gcio** [comment]
Great, thank you @DanielleThierryUSDSVA - we will definitely stay in touch with timing.

**Comment by jason-gcio** [comment]
@lunascoop - I think we can close this ticket? I am just going around cleaning things up...
