### ISSUE TITLE
[CDP] VBA Diary codes (statuses)- Suggestions and Questions

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#80146]
## Description

We need to better understand the use of diary codes on the debt portal. These messages appear on the cards and on alerts on the debt portal. 

Understanding the diary codes will allow us to create a status delineation to surface a different type of alert (informational or alert, color-coded depending on severity) depending on the time based progression of the debt and level of severity (from first notice of money owed, to becoming a debt, to being sent to collections, and treasury).  [First layer]

Secondly, understanding the diary codes and mapping these to the correct alert will allow us to recommend the best action or actions to the Veteran based on the level of their debt situation. The experience will be more dynamic and tailored. [Second layer]

**[Spreadsheet: Diary Codes](https://docs.google.com/spreadsheets/d/1h8CYQH9W7ka2llPsHX50MQ7Qy5uoKFsLmMtNlQ6eLfk/edit?usp=sharing)** Currently being worked on

[Figma: Diary Codes](https://www.figma.com/file/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?type=design&node-id=0%3A10321&mode=design&t=URCEDJ53EN2at0fQ-1)

**Previous spreadsheet links for reference only:** 
Both the spreadsheet of original diary codes and our grouped version can be found in the VSA Team Sharepoint: 
        - [Original diary code spreadsheet](https://salientcrgt.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Debt%20Letters%20Master%20Codes%20and%20Transactions%20Catalog.xlsx?d=w50365d7002b248828873928f7b6a6c7f&csf=1&web=1&e=8xDirj) 
        - [Grouped diary codes spreadsheet](https://salientcrgt.sharepoint.com/:x:/r/sites/VSATeam/Shared%20Documents/Design%20%26%20Research/Benefits%20%26%20Memorials%202/Debt%20Letters%20MVP/Iteration%203/Debt%20Portal%20Statuses%20V2.0.xlsx?d=web6d9eb5b68e4a89b8efb3b8ecbefc31&csf=1&web=1&e=T6iP8w)
  

Given: Users are given an inconsistent labels for diary codes on the Debt Portal
When: Cards, Alerts
Then: How can we improve diary codes on the Debt Portal?

## Tasks
- [x] Identify which are shown in the portal (indicate those that we don't show - for transparency)
- [ ] Identify what proposed changes we have, based on what we know - then they can react and course correct but we can likely make some assumptions to unify the messages across the card and component
- [x] Identify what question we have for the diary code that we don't understand or have enough context on.
- [ ] Denise will reach out to Bob for additional information
## Acceptance criteria

- [x] All diary codes identified
- [ ] Questions defined
- [ ] Proposed changes defined

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Questions for SMEs

1. We would like to ask for information about the consequences of benefit overpayment debt being unpaid. 
2. What does the collection action look like should a Veteran not pay by the deadline (30 days upon receiving the first debt letter)? 
3. What happens to the Veteran when the debt is sent to the treasury? 

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by mgleo** [comment]
@HeatherRienks @Tom-Davis This can be brought in for Sprint 123

**Comment by HeatherRienks** [comment]
Thank you @mgleo!

**Comment by mgleo** [comment]
[Diary Codes Spreadsheet](https://docs.google.com/spreadsheets/d/1h8CYQH9W7ka2llPsHX50MQ7Qy5uoKFsLmMtNlQ6eLfk/edit?usp=sharing)

Questions:
- Are we providing accurate information to the users when considering VAMS codes? 
- What information can we provide to users when the code indicates the bill has been sent to Dept of Treasury?

**Comment by HeatherRienks** [comment]
Diary Codes Meeting set up for Tuesday, 5/14/24 at 2:30pm ET with Bob Vitt, Denise, and team.

**Comment by charlottecesana** [comment]
Added details about what we are trying to achieve, and questions for SMEs to this ticket.

**Comment by HeatherRienks** [comment]
Per Sprint Planning, we will close this ticket and create a follow up ticket
FYI @Tom-Davis
