### ISSUE TITLE
[DESIGN] Complete Appointments Notifications List Pattern

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#80158]
## Background

For the notification list pattern, initial discovery has been completed. Some components and logic have been confirmed and tested in other studies/initiatives, while others still need to be explored and solidified. As we apply this to referrals, the pattern needs to stay scalable to apply to work for any surfaced notifications anywhere (also outside of appointments).

### Notification pattern discovery:
- [Resulting pattern](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=182-3268&mode=design&t=p52fdBYhEibfRCB6-0)
  - "Things to do" and "things to know" (or completed things) are both included in notifications
- [Card UI explored so far](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=182-3268&mode=design&t=p52fdBYhEibfRCB6-0)
  - Featured task card is confirmed and tested. 
  - Secondary cards (smaller cards for notifications list) have not been solidified
  - "Review all notifications" component to surface all notifications has not been solidified
- [Remaining questions](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=182-3268&mode=design&t=p52fdBYhEibfRCB6-0)
  - Are notifications dismissible? Removable? (Research is conflicted) 
  - What are the differences in UI between "to-do" and "complete"?
- [Logic questions](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=182-3268&mode=design&t=p52fdBYhEibfRCB6-0)
  - How do "to do" action notifications move within the list once they've been completed?
 
### Notification pattern applied to referrals: 
- [Demonstration of how this pattern would apply to referrals](https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?type=design&node-id=101-4539&mode=design&t=OGYEXi8Svb19nU8U-0)
- **Remaining question**: How specific to referral notifications vs. appointment notifications do we go in this MVP to allow the pattern to remain scalable (when other types of notifications are added, such as Pre-Check-in)?

## Tasks

- [ ] Review results of discovery and example of pattern applied to referrals
- [ ] Determine 2 types of scalable UI for smaller "secondary card" (or list item) - for use on the appointment list
  - [ ] Action item
  - [ ] "To know" or "completed" item
- [ ] Solidify logic around what happens to an Action item in the notifications list once completed
- [ ] Determine if/how list elements should be removable or dismissible
- [ ] Create finalized pattern of notification list page applied to referral situation

## AC
- [ ] Discovery reviewed
- [ ] Components confirmed and applied to a referrals scenario
