### ISSUE TITLE
Create a Conversation Guide for 686 Submission Usability Session

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8015]
## Goal
We want to create a consistent conversation guide that encompasses the guidance of approved methods and all the components for the users we will be communicating with.

## Considerations
Conversation guides are usually incorporated into Research Plans but because they are large enough, we seperate them.  Both are considered deliverables.

## Task
- [ ] Coordinate with Shawna on some of the questions to ask in the conversation guide
- [ ] Document a conversation guide to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-convo-guide.md)):
  - Intro
  - Warm up Questions
  - Navigation
  - Priorities
  - Features
  - Post Interview
  - Thank you and Closing
  
## Acceptance Criteria
- [x] Conversation Guide has been sent to Shawna for review

**Comment by sporeboy** [comment]
Most feedback incorporated. Potential logged-in Veteran workflow added here: https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/screen/a21303f7-0ce5-45f1-82ef-251652c20c36/8832-Applicant-Info-LoggedIn-1

**Comment by sporeboy** [comment]
Convo guide initial draft is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-usability-staging-0520/686-usability-staging-convo-guide.md

**Comment by sporeboy** [comment]
Continuing to refine tasks steps and questions in light of shifting design and development issues around 686.
