### ISSUE TITLE
Copy of 2024 Sentry Deprecation: Migrate all uses of log_exception_to_sentry to Datadog

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80157]
## Issue Description
The Sentry tool will be deprecated. The 90 day notice of migrating the errors to DataDog is effective as of 4/5/2024.
This is work that is already in flight with @patrickvinograd 's team, with [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65929) 

## Tasks
- [ ] Migrate all uses of log_exception_to_sentry to Datadog 
- [ ] Test new connection of log_exception_to_sentry to Datadog 

## Acceptance Criteria
- [ ] va-api uses of log_exception_to_sentry is migrated to Datadog successfully

**Comment by LindseySaari** [comment]
We may bump the effective date out a bit. OCTO stakeholders are discussing cost implications regarding Datadog vs Sentry and we are waiting for feedback

**Comment by jennb33** [comment]
Blocked because Patrick's ticket is also blocked.
