### ISSUE TITLE
Burial | Update Success Polling

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80164]
## Issue Description
_The burial form is currently polling the Central Mail API for submission success, which is preventing the form from completing submission on the FE. The polling needs to be updated to poll the Benefits Intake API._

---
## Tasks
- [x] Move success polling from Central Mail to Benefits Intake

## Acceptance Criteria
- [x] Burial form successfully polls Benefits Intake API for submission confirmation
- [ ] FE of form submits and shows confirmation screen
---

**Comment by steele-lm** [comment]
@tblackwe and @Midge-dev

**Comment by micahaspyr** [comment]
Needs to check for both CM and BI when returning a status

**Comment by micahaspyr** [comment]
I've got a draft PR up for the polling status fix.  I still need to fill out the rest of the ticket description but I have the tests passing locally.
