### ISSUE TITLE
2024 Sentry Deprecation: Identify any Sentry/Slack Alerts that need to be migrated

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80160]
## Issue Description
The Sentry tool will be deprecated. The 90 day notice of migrating the errors to DataDog is effective as of 4/5/2024.
This is work that is already in flight with @patrickvinograd 's team, with [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65929) 

## Tasks
- [x] Identify any Sentry/Slack Alerts that need to be migrated
- [x] Confirm with stakeholders the identified Sentry/Slack Alerts that could migrate to DataDog
- [x] Document current alerts
- [x] Create any tickets or tasks for follow up with

## Success Metrics
- [ ] _Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [x] Sentry/Slack Alerts are documented for migration to Datadog

**Comment by jennb33** [comment]
This work will also benefit the Tools Audit work

**Comment by LindseySaari** [comment]
Scoping this to Vets API, Vets Website and the GIDS project. There are other projects and those are [called out here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3099787681/Sentry+Audit+Project+Ownership)

**Comment by LindseySaari** [comment]
Current Slack <> Sentry alerts have been identified and documented in the respective Sentry discovery documentation per project. Owning teams will be responsible for migrating these alerts and guidance will be provided in the migration guide.
