### ISSUE TITLE
Burial | Add helper text to currency field

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80168]
## Issue Description
_The Design System is working to release a currency pattern, in the meantime, the pattern available to use does not support decimals or the $ symbol. We need to add helper text to the FE, so users know they cannot enter either._

---
## Tasks
- [x] @fiorella-io to work with CAIA (if needed) to draft language.
- [ ] @Midge-dev to add helper text to FE

## Acceptance Criteria
- [ ] User sees helper text when entering a monetary value into a field asking for currency
---

**Comment by fiorella-io** [comment]
@Midge-dev 
Hint text: Enter an amount with numbers only. Don't include symbols or special characters like "$," commas, or periods.
<img width="70%" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bbd2be8b95f922132a523e756494a5cd9a9760f/image.png" alt="image.png" />

Error (if we can update it): You entered a character we can't accept. Remove symbols or special characters like "$," commas, or periods.
<img width="70%" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e86918f449301c75206700e184a58951bb8d1bc/image.png" alt="image.png" />

**Comment by DLarson-Oddball** [comment]
@steele-lm Code for this issue has been merged.
