### ISSUE TITLE
Test Addition of Latest Updates Page to Developer Docs

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80161]
## Issue Description
We need to test the addition of a Latest Updates page in one of the Platform Website spaces to ensure functionality and best positioning in the IA.

---
## Tasks
- [ ] Add page to Developer Docs in Confluence
- [ ] Using `/update` command, generate list of updated pages 
- [ ] Add section to table on 1st page of Developer Docs space
- [ ] Add link to the Update page in the new section of the table
- [ ] Update and check for Launch Blockers
- [ ] Deploy 

## Acceptance Criteria
- [ ] New Updates page and link will be operational
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
cc: @taylojill deploying Monday 4/8
