### ISSUE TITLE
IA Tracker: Medical Supply Ordering page

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#80187]
### Description
Veterans are having a hard time finding the CPAP form. We want to pursue the creation of a unified medical device ordering page so that we can surface that link as an entry point on the hub page and mega menu. This should increase traffic to 

### Links

[- [Intake Ticket #]](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/26?pane=issue&itemId=58126536)

### Team
- Designer: Jasmine Y.

### Timeline
- no rush or mandate but veterans are having a hard time finding CPAP

### Work needed

- IA spec: Needed

```[tasklist]
### IA deliverables
- [x] IA spec: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712349672737/42d77ae33ad84086e68e98d4a06b8daa33303fc8?sender=ua67f17f1c416a96ea04d2476
- [x] IA spec in github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/unified-medical-supplies-ordering.md
```

## Acceptance Criteria
- [ ] IA spec is shared with product team in Intake Ticket.

**Comment by kristinoletmuskat** [comment]
Created mural draft of spec, need content and Sara S feedback before I put it into github

**Comment by kristinoletmuskat** [comment]
Got feedback from Mikki, waiting for feedback from content/Sara

**Comment by kristinoletmuskat** [comment]
Priority update: this is in our content backlog, but we're waiting to see if we can get a content person from VHA to step in and work on this. Danielle is looking into that.

**Comment by kristinoletmuskat** [comment]
Confirmed that the content work is done, so closing this out!
