### ISSUE TITLE
Upgrade to Zenhub Access Request Process

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#80186]
## Description 
We want to move the process for requesting access to Zenhub (currently in #zenhub-information channel) to the #vfs-platform-support channel since the Platform Support Team manages this channel. This will help us track tickets more easily and identify volume consistently. 

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Request approval from Erika
- [x] Request approval/run idea by Andrea and Jason 
- [x] Outline items needing to complete here
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Process approved by @EWashb The Zenhub-Information channel will now be simply informational, technical troubleshooting questions will be directed at Zenhub, and we will handle both onboarding and offboarding Zenhub requests. 

_Note: We are working on an automation that will check for any inactive users in the event that a user has offboarded and we weren't informed. Something that Andrea noted was an issue historically. More of a back-end item, but wanted to lump this all together! You can view the work for that task [here](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/80962). _
