### ISSUE TITLE
[CST] Remove components that were related to EVSS

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#80194]
## Background Context
With the removal of EVSS we no longer need these 3 components.
 - ClaimSyncWarning.jsx
 - VaButtonGroupSegmented.jsx

## Out of scope
- Add here

## Tasks
Remove the following files and and the uses of them
- [x] ClaimSyncWarning.jsx
- [x] VaButtonGroupSegmented.jsx

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] ClaimSyncWarning.jsx no longer appears in the CST
- [ ] VaButtonGroupSegmented.jsx no longer appears in the CST
