### ISSUE TITLE
BE | Profile | Direct Deposit | Stop outbound traffic to EVSS

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#80207]
## Summary
There is still a small amount of PPIU traffic between VA.gov and EVSS.  We have denied requests to our PPIU endpoint, but traffic that bypasses this endpoint is still going to EVSS.

There is a PPIU policy that all services should use to authorize the request before making the outbound call.

This ticket will update the policy to deny access.

## Tasks
- [ ] Update PPIU Policy
- [ ] Update dependent specs

## Acceptance Criteria
- [ ] Notify the benefits teams that may be affected in the #benefits-engineering channel.
- [ ] Check traffic in Datadog.

**Comment by tpharrison** [comment]
As of now, no.  I'll discuss this at our LH meeting on Friday.  Changes are ready to deploy, but I just want to confirm with everyone on the call before merging.  Thanks!

**Comment by mtcA6** [comment]
As in it's been resolved? or as in they no longer care about it?

**Comment by tpharrison** [comment]
Michael Harlow said he said he saw 1 record in the past 24 hours but isn't concerned and considers it a closed issue.
