### ISSUE TITLE
BE | Profile | Direct Deposit | Update email notification

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#80206]
## Summary
Currently, when a user updates their direct deposit info, they receive an email notification stating their direct deposit details was updated.  The email specifies the benefit type that the direct deposit is related to (either C&P or EDU). 

Moving ahead, users will only deal with one direct deposit account. Therefore, the email notification should only state that their direct deposit info was updated without specifying the benefit type.

The email templates and notifications are sent using VA Notify.

## Tasks
- [ ] Add a new VA Notify template for direct deposit in staging.
- [ ] Add a new settings entry (devops repo).
- [ ] Update the email notification logic in vets-api (using a feature flag).

## Acceptance Criteria
- [ ] Test notification in staging.
