### ISSUE TITLE
VRE | Watch Officer Alerts

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80211]
## Issue Description
[VRE API errors monitor](https://vagov.ddog-gov.com/monitors/186965?q=%2A&sp=&view=spans&live=1w):
- 5 alerts with a few retriggers for the past week. These are capturing non-200, non-401 status code traffic from the v0/veteran_readiness_employment_claims controller.
- 7 of the cases for this week are 422 status codes (invalid data) and 2 are 401 (unauthorized).
- Should both of these status codes be considered as errors for the VRE APIs? 

---
## Tasks
- [ ] Determine cause of alerts
- [ ] Determine if status codes should be considered errors for VRE API

## Acceptance Criteria
- [ ] Follow on tickets for mitigation created (if needed)
---

**Comment by micahaspyr** [comment]
I'm trying to find the related logs to these errors but nothing comes up when searching them.  I think these errors are fairly insignificant though, as we do not see them in any great amount.
