### ISSUE TITLE
BE | Profile | CH33 Direct Deposit | Update email notification

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#80210]
## Summary
Currently, when a user updates their direct deposit info, they receive an email notification stating their direct deposit details was updated.  The email specifies the benefit type that the direct deposit is related to (either C&P or EDU). 

Moving ahead, users will only deal with one direct deposit account. Therefore, the email notification should only state that their direct deposit info was updated without specifying the benefit type.

The email templates and notifications are sent using VA Notify.

## Tasks
VA Notify:
- [x] Add a new VA Notify template for direct deposit in staging.

VSP Infrastructure Repo:
- [x] Update `values.yml` for staging, and prod.

DevOps Repo:
- [x] Update `settings.yml` for dev, staging, and prod.

Vets-API Repo:
- [x] Update `settings.yml`.
- [x] Update the email notification logic in vets-api.

## Acceptance Criteria
- [x] Test notification in staging.

**Comment by tpharrison** [comment]
Pull Requests:
- https://github.com/department-of-veterans-affairs/devops/pull/14223
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2805

**Comment by tpharrison** [comment]
Generic email notification working in staging...
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/653787/c0317cbd-34d0-49a0-b916-fd61a0d6ca22)

@mtcA6 @adamwhitlock1
