### ISSUE TITLE
Groom eBenefits Metrics for Product Success Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8022]
## User Story or Problem Statement
How might we understand the requirements for adding eBenefits KPIs to Domo so that when we start building on Domo, we can share which metrics we can add, which metrics will have a BigQuery or a GTM dependency, and how we can proceed with building?

## Goal
Determine efforts and sources of provided KPIs.

---
## Tasks
- [ ] Determine data sources for each KPI
- [ ] Determine dependencies for KPIs (BigQuery or GTM)

## Acceptance Criteria
- [ ] VSP Analytics has sources & dependencies for provided KPIs

---

## Links
[eBenefits KPIs](https://docs.google.com/spreadsheets/d/1Grqhf21aolAHy_-Son-VahCN59qRI-w3EtOPFjGbCSo/edit#gid=359689327)

**Comment by joanneesteban** [comment]
eBenefits: Waiting on OKRs/Outcomes. May have to reach out for more clarification.

**Comment by joanneesteban** [comment]
@bsmartin-ep follow up with Jason W on which pages each of the KPIs is on.

**Comment by bsmartin-ep** [comment]
@joanneesteban -

I asked Jason W about the pages...

> **Me:**
> The data you want for these would be located on www.ebenefits.va.gov at this point, correct?  You're looking for data before 686 gets moved to va.gov?
> 
> **Jason Wolf:**
> Yes, I would love to know what people are getting into eBenefits for, what forms are being submitted and how many. Seeing the 686 in there currently would be great

Looking at the eBen GA, our options are - of course - pretty limited compared to the modernized tools.

We have basic metrics like pageviews...

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/

...some of which have a _feature_ query parameter that looks interesting...

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/explorer-table.filter=feature=&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=100/

Events are a bit limited. We have Outbound Link and PDF tracking 

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p178604270/

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Based on Jason's request - and the limited data available on eBen - here are my suggested datasets:

Metrics | Data Set | Drill Down
:---|:---|:---
Bounce Rate | GA Base Metrics (Bounces, New Users, Pageviews, Revenue, Session Duration, Sessions) | n/a
Top Pages | GA Custom Report (Pages, Pageviews) | n/a
Top _Feature_ Pages | GA Custom Report (Pages, Pageviews) | [Page contains _feature=_](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.filter=feature=&explorer-table.plotKeys=%5B%5D/)
Top Outbound Links | GA Custom Report (Outbound Link Events) | n/a/
Top PDF Downloads | GA Custom Report (PDF Downloads) | n/a

Look OK?  

1. Think I should combine the last two into one big _All eBen Events_ dataset then drill down?  Don't really see a [ton of events in GA](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22ebenefits.va%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=50&explorer-segmentExplorer.segmentId=analytics.eventLabel/).
2.  We also have nav and 404 events. Think I should include them?

**Comment by bsmartin-ep** [comment]
Hi @jason-gcio -

Based on your request and the limited data available on eBen - here are my suggested datasets and the data in Google Analaytics.

Is there anything else - such as a specific URL - that you would want to track?

Metrics | Data Set | Drill Down | Google Analytics report
:---|:---|:---|---
Bounce Rate | GA Base Metrics (Bounces, New Users, Pageviews, Revenue, Session Duration, Sessions) | n/a | [link](https://analytics.google.com/analytics/web/#/report/content-overview/a50123418w177519031p178604270/)
_Add or Remove Dependents_ Pages | GA Custom Report (Pages, Pageviews) | Page contains _/ebenefits/vdc?target=/wssweb/wss-686-webparts/dependent.do_ | [link](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Febenefits~2Fvdc%3Ftarget=~2Fwssweb~2Fwss-686-webparts~2Fdependent.do%22,0%5D%5D/)
Top Pages | GA Custom Report (Pages, Pageviews) | n/a | [link](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25/)
Top _Feature_ Pages | GA Custom Report (Pages, Pageviews) | Page contains _feature=_ | [link](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&explorer-table.filter=feature=/)
Top Outbound Links | GA Custom Report (Event Labels, Categories, Actions, Total) | Event = Outbound Link | [link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.filter=Outbound%20Link%20Clicked&_r.drilldown=analytics.eventCategory:Interactions&explorer-segmentExplorer.segmentId=analytics.eventAction/)
Top PDF Downloads | GA Custom Report (Event Labels, Categories, Actions, Total)  | Event = PDF Download | [link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p178604270/explorer-segmentExplorer.segmentId=analytics.eventLabel&_r.drilldown=analytics.eventAction:PDF%20Downloaded%20-&explorer-table.plotKeys=%5B%5D/)

**Comment by bsmartin-ep** [comment]
@joanneesteban / @amycesal -

Do you want to run these past Jason or should we start building in DOMO?

Metrics | Data Set | Drill Down | Google Analytics report
:---|:---|:---|---
Bounce Rate | GA Base Metrics (Bounces, New Users, Pageviews, Revenue, Session Duration, Sessions) | n/a | [link](https://analytics.google.com/analytics/web/#/report/content-overview/a50123418w177519031p178604270/)
_Add or Remove Dependents_ Pages | GA Custom Report (Pages, Pageviews) | Page contains _/ebenefits/vdc?target=/wssweb/wss-686-webparts/dependent.do_ | [link](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Febenefits~2Fvdc%3Ftarget=~2Fwssweb~2Fwss-686-webparts~2Fdependent.do%22,0%5D%5D/)
Top Pages | GA Custom Report (Pages, Pageviews) | n/a | [link](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25/)
Top _Feature_ Pages | GA Custom Report (Pages, Pageviews) | Page contains _feature=_ | [link](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&explorer-table.filter=feature=/)
Top Outbound Links | GA Custom Report (Event Labels, Categories, Actions, Total) | Event = Outbound Link | [link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p178604270/explorer-table.plotKeys=%5B%5D&explorer-table.filter=Outbound%20Link%20Clicked&_r.drilldown=analytics.eventCategory:Interactions&explorer-segmentExplorer.segmentId=analytics.eventAction/)
Top PDF Downloads | GA Custom Report (Event Labels, Categories, Actions, Total)  | Event = PDF Download | [link](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p178604270/explorer-segmentExplorer.segmentId=analytics.eventLabel&_r.drilldown=analytics.eventAction:PDF%20Downloaded%20-&explorer-table.plotKeys=%5B%5D/)

**Comment by joanneesteban** [comment]
@bsmartin-ep @amycesal it's only one metrics right now, but we'll also be tracking their 5 star CSAT (on ForeSee) for one of their KPIs.

**Comment by bsmartin-ep** [comment]
@amycesal / @joanneesteban 

A first pass.  Let me know what you think.

https://va-gov.domo.com/page/177811372

**Comment by joanneesteban** [comment]
@bsmartin-ep Thanks! The data looks good, and it'll be good for EBN to have. 

@amycesal you can hold off on visualization for dashboard arrangement.

I'm going to work with Mickin on these Objectives.

**Comment by joanneesteban** [comment]
@bsmartin-ep 

These metrics are good to go, with the added:

**View/Update Dependents**
- Time to Complete 686

**View Payment History**
- % of View Payment History traffic - historical & new/EBN & VA.gov
- Time to View My Payment History (historical baseline was 1 minute)

(CC: @amycesal )
Resources for their desired Veteran Outcomes:
- [View/Update Dependents](https://docs.google.com/spreadsheets/d/1Grqhf21aolAHy_-Son-VahCN59qRI-w3EtOPFjGbCSo/edit#gid=359689327)
- [View Payment History](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/README.md#kpis)

**Comment by joanneesteban** [comment]
For top pages & features, I think those will be useful, but perhaps in a separate category from prioritized KPIs. @amycesal what are your thoughts in terms of visualization around that?

**Comment by bsmartin-ep** [comment]
@joanneesteban -

> **View/Update Dependents**
> - Time to Complete 686

If they are looking for a GA metric for this one, I don't think we have an accurate one.  We have an _Avg Time on Page_ for the primary 686 URL:

![image](https://user-images.githubusercontent.com/62304138/84775219-ecc83180-afac-11ea-806d-6eb92bb6606d.png)

...but that is probably inflated like this metric usually is.  When it's moved to va.gov, we should be able to do the normal DIFFing we do on _start_ and _submit_ events on modern apps.

-----
> **View Payment History**
> - % of View Payment History traffic - historical & new/EBN & VA.gov

No problem.  We can see what % of total URLs are the _Payment History_ URL.  Think they would be most interested in total % of pageviews or sessions?

![image](https://user-images.githubusercontent.com/62304138/84775524-55171300-afad-11ea-82b3-ed4a6db357fd.png)

------
> - Time to View My Payment History (historical baseline was 1 minute)

Do you know where they got the 1 minute baseline?  I didn't see any citations in the docs and a quick search of Granafa wasn't helpful.

**Comment by jason-gcio** [comment]
We estimated 1 minute based on research sessions with Veterans - it is a relatively simple view task.
