### ISSUE TITLE
Groom IA metrics for Product Success Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8023]
## User Story or Problem Statement
How might we understand the requirements for adding Information Architecture KPIs to Domo so that when we start building on Domo, we can share which metrics we can add, which metrics will have a BigQuery or a GTM dependency, and how we can proceed with building?

## Goal
Determine efforts and sources of provided KPIs.

---
## Tasks
- [ ] Determine data sources for each KPI
- [ ] Determine dependencies for KPIs (BigQuery or GTM)

## Acceptance Criteria
- [ ] VSP Analytics has sources & dependencies for provided KPIs

---
[IA KPIs](https://docs.google.com/document/d/1862x-PQJ0X3UAGH_DpNvlcHOjsU3Too4vzx4OmLvx5I/edit)

**Comment by joanneesteban** [comment]
Waiting on team to give confirmation that these are completed.

**Comment by bsmartin-ep** [comment]
@joanneesteban - 

I added my comments / questions to their KPI doc...

https://docs.google.com/document/d/1862x-PQJ0X3UAGH_DpNvlcHOjsU3Too4vzx4OmLvx5I/edit?usp=sharing

**Comment by joanneesteban** [comment]
@joanneesteban 
Groom the ForeSee metrics. May bring in @Kimberley2019 or @clantosswett to help with potential Contact Center metrics

**Comment by joanneesteban** [comment]
Putting IA KPIs in backlog until that team is ready to set KPIs.

**Comment by joanneesteban** [comment]
See #8559
