### ISSUE TITLE
Update dashboard with support and helpdesk data

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#80243]
## Issue Description
Update dashboard to show trend of help desk tickets to be able to correlate with SSiT campaign announcements and related activity.
---
## Tasks
- [x] Investigate new help desk data
- [x] Implement datafeed
- [x] Create visualizations of support tickets by ticket type and by CSP

## Acceptance Criteria
- [x] Dashboard updated with support tickets by ticket type and by CSP

**Comment by sdickson-gt** [comment]
dashboard updated

**Comment by SophiaPhilipMO** [comment]
@SophiaPhilipMO to review

**Comment by skirkman16** [comment]
EVSS may not be included but @sdickson-gt will look into this
