### ISSUE TITLE
Determine Feasibility of Domo for Phased Rollouts

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8024]
## User Story or Problem Statement
How might we  determine the feasibility of switching Google Analytics dashboards to Domo?

## Goal
Determine criteria and efforts for GA dashboards vs. Domo so we can better strategize the Product Success Tool.

---
## Tasks
- [ ] Document criteria for GA dashboards
- [ ] Document criteria for Domo dashboards
- [ ] Document efforts for both dashboards

## Acceptance Criteria
- [ ] VSP understands criteria and efforts for both dashboards
---
[Domo vs. GA Documentation](https://docs.google.com/document/d/1pLX3luIUHP26d0gxIKhTjDAIKlElSw6cHo0_wi5E8to/edit)

**Comment by joanneesteban** [comment]
Some discovery work is being done in Q4 2020. Will need to do a bit of technical discovery around how often Domo can update. Closing this issue to clean up the board.
