### ISSUE TITLE
Connect Domo to ForeSee

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8025]
## User Story or Problem Statement
As a VFS team member, I need to see ForeSee in my analytics on the Product Success Tool so I can have the more holistic view of my product.

## Goal
Connect the CX and Feedback Surveys to Domo.

---
## Tasks
- [ ] Connect ForeSee API to Domo for CX surveys
- [ ] Connect ForeSee API to Domo for Feedback surveys

## Acceptance Criteria
- [ ] VFS teams can have automated product feedback survey data on Domo
- [ ] VFS teams can have automated qualitative (open ended) survey data on Domo
---
*Note that these API connections will be short-term solutions until we can set up and connect BigQuery

**Comment by joanneesteban** [comment]
When Medallia is live, we will add historical ForeSee data to BigQuery. Closing this ticket.
