### ISSUE TITLE
Copy of Find a Rep LIVE - User Test - Mobile Users - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#80267]
## Issue Description
Live user testing of Find a Representative experience with mobile and assistive technology (AT) users.

## Tasks

- [x] Request research review
- [ ] Update user test to reflect collab cycle edits
- [ ] Set-up Enjoy HQ project
- [ ] Kick-off with Perigean
- [ ] Create sign-up sheet
- [ ] Transfer demographics to sign-up sheet & Excel
- [ ] Create folders & update guideline documents
- [ ] Create notetaker template
- [ ] Set up Slack channel w/ notetakers & observers
- [ ] Kick-off with notetakers
- [ ] Conduct pilot session
- [ ] Kick-off with observers
- [ ] Create debrief Mural
- [ ] Create conduct interview Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by oddball-lindsay** [comment]
Seeking at least 1 co-moderator for each session: https://docs.google.com/spreadsheets/d/1MJB_o5qDzjHY9NYnGriGV_SQ1AVmfi7_itcT5Iiq8ho/edit#gid=774291617

**Comment by oddball-lindsay** [comment]
Final mobile test today, there was some PII to clean up
