### ISSUE TITLE
My VA311 IVR Content and Process Review 

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#8026]
## User Story or Problem Statement

How might we manage the MyVA311 COVID-19 IVR content so it remains relevant and useful for veterans calling this number.

## Goal
_What outcome(s) do we want to see?_

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [x] Review and update current COVID-19 content recorded on the MyVA311 IVR
- [x] Record and publish new content to IVR.
- [x] Create a process that streamlines review and updates to MyVA311 IVR content

## Acceptance Criteria
- [x] Centralized document for reviewing COVID-19 content for MyVA311
- [x] Process for reviewing IVR metrics for COVID-19 content on the MyVA311 IVR
- [x] Identify POC responsible for managing content review/update process. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
We are using the sharepoint to make edits to the IVR as necessary. Pete Smith is the POC for making the necessary changes to the document and the IVR and also provides metrics multiple times per week on the IVR usage.

https://dvagov.sharepoint.com/:w:/r/sites/TelCareNowNetwork-IPT/_layouts/15/Doc.aspx?sourcedoc=%7BF4F69D92-EF4D-4317-803E-2783DD551B0A%7D&file=MYVA311%20FAQ%20Script%20Final%20Draft.docx&action=default&mobileredirect=true
