### ISSUE TITLE
[CST] Remove `getTrackedItemId` helper

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#80266]
### Background
During the EVSS-to-Lighthouse migration, a helper was created that could take a EVSS or Lighthouse tracked item and return the id of the tracked item. Since we are not relying on EVSS for claim details anymore this helper can be removed.

### Engineering notes
To get the id of a Lighthouse tracked item, the `id` field can be used (for EVSS it was the `trackedItemId` field)

### Tasks
- [x] Replace instances of `getTrackedItemId()` with `item.id` or `trackedItem.id`
- [x] Remove the `getTrackeditemId` method from `helpers.js`
- [x] Delete tests related to the `getTrackedItemId` helper

### Acceptance Criteria
- [x] The `getTrackedItemId` helper has been removed from the claims-status application
