### ISSUE TITLE
[UX][FE] 10-10EZ Toxic exposure other text field hint and error text

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#80265]
## Issue Description
Recently during a usability session, a participant had issues with the Other toxic exposures open text field questions/page. They were entering multiple toxins separated by a comma.

**NEW content** (Provided via Aliyah via Slack on 4/3/24
Hint text: If you're listing multiple toxins or hazards, list them without commas or any other special characters
Error: You entered a character we can't accept. Remove any special characters like commas or dashes. 

**NOTE**
When the Enrollment System (VES) is updated to take special characters in the other field, this temp new content can be removed. 

---
## Tasks
- [x] (UX) Update designs and source of truth docs (Figma and Mural) to match update
- [x] (FE) Update code to align with new hint and error text messages
- [x] Test and validate changes are made and correct

## Acceptance Criteria
- The error and hint text are updated on the Other exposures field.
---

**Comment by jessicastump** [comment]
[Figma link](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=2922-45151&mode=design&t=eW5OhmvoRzOisuen-0) showing hint/error text placed

**Comment by longmd** [comment]
Hint text and validation messaging have been updated. See below.

![Screenshot 2024-04-15 at 12 48 04](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/1691c821-e6ef-4d82-8d25-1bf190bf5b4c)
