### ISSUE TITLE
Address findings for gaps in FDG

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#80262]
## Purpose
Using this [findings doc](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3057418248/FDG+gap+analysis), enact the recommended additions identified.

Dan is the SME for additional details as he worked on the earlier ticket.

## Tasks
- [x] In [“Understand the form/Best practices”](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2924609560/Phase+I+Before+starting+digitization+work#Check-form-freshness): Ask stakeholders if current PDF is up to date or will be revised
- [x] In [“Document contacts/Additional details”](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2924609560/Phase+I+Before+starting+digitization+work#Document-contacts): Use PCO Contact List to help identify form owners
- [x] In [“Draft content/Best practices”](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2965766145/Phase+III+Initial+digitization#Draft-content): Review the questions in the print form and start revising to meet VA plain language standards
- [x] In [“Build mockups/Best practices”](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2970943489/Phase+IV+Design+feedback+and+testing#Build-mockups): Include how the user’s path may branch, depending on the form’s logic

## Acceptance Criteria
- [x] Phase I Best Practices:  stakeholder approval of current pdf
- [x] PCO Contact list guidance is present
- [x] Phase III Best Practices questions meet plain language standards
- [x] Phase IV Best Practices include how the user's path may branch
