### ISSUE TITLE
Discovery: Adding ngrok to suite of testing tools for local development (Footer Ticket 80225)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80275]
### Description

The Public Websites team uses **ngrok** for local development when traditional methods are down (CI issues, SOCKS blockers, etc.).
The team wrote up some documentation on how to use **ngrok** when running `vets-website` and `content-build` locally. 
This information will be helpful for other teams, and could be included in the list of testing tools for local development.

### Tasks
- [ ] Joe Knipes contact a Front End SME to review suggested documentation for value & relevancy
- [ ] SME review documentation
- [ ] Make determination on whether to add documentation to Platform Website
- [ ] Create Edit ticket to write the page

### Acceptance Criteria
- [ ] All Tasks completed

### Relevant URLs

Public Websites team docs for `ngrok`: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17306#issuecomment-2043002447

Various `ngrok` documentation links are included in this write-up.

**Comment by jknipes** [comment]
Per Jill Adams on ticket 17306:
_This could / maybe should become a part of **FE** dev tools, https://depo-platform-documentation.scrollhelp.site/developer-docs/tools_

**Comment by jknipes** [comment]
Edit ticket created, no need for discovery or estimation on this ticket. Closing ticket.
