### ISSUE TITLE
[Research] Conduct Remote Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#80278]
## Description
We need to conduct the research study for the Discovery - Multiple Selection of Appointments.

## Tasks
- [ ] Get a list of participants from Perigean
- [ ] Coordinate with Perigean to run the tests
- [ ] Monitor the results
