### ISSUE TITLE
[Research] Synthesize Research

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#80280]
## Tasks
- [ ] Decide on analysis methodology (affinity diagramming, etc.)
- [ ] Involve appropriate team members in analysis activity/meetings
- [ ] Review all participant study results
- [ ] Do analysis

## Acceptance Criteria
- [ ] Post synthesis documents to GitHub
- [ ] Write top-line summary (optional if daily summaries were sent out)

**Comment by benbrasso-agile6** [comment]
@cgednalske I'm thinking of closing the synthesis ticket, re: https://docs.google.com/spreadsheets/d/1rrkORjs03ooEPHnIcYmvb_yJL7vwci5rylDVIySpFOE/edit#gid=0

Anything else you were thinking as far as breaking the data down? I think the level of experience is probably the most valuable. I can dig into if there's different percentages of each of those 3 groups in the presentation ticket. 

Thoughts?

**Comment by cgednalske** [comment]
@benbrasso-agile6 what about the analysis of the synthesis? Is that part of this ticket too?

**Comment by benbrasso-agile6** [comment]
It can be. But, that's also then the meat of the presentation imo.

**Comment by benbrasso-agile6** [comment]
I'll move this back and work on more of the analysis

**Comment by benbrasso-agile6** [comment]
@cgednalske for validation https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715965696451/66115023065835cadd05eeb75a64cb066975362e?showAddTemplatePopup=true
