### ISSUE TITLE
IA Tracker: Updating URL for Post-9/11 GI Bill Statement of Benefits TOOL TOOL TOOL!

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#80295]
### Description
We are updating the URL for the static page that links to Statement of Benefits tool and so we will also need to update the tool URL. We need to work with the product team that manages this tool to update the URL and coordinate a redirect as well.

Current URL | New URL
---- | ----
https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status | https://www.va.gov/education/check-post-9-11-gi-bill-benefits/status

In addition to updating the URL, the education team working on this tool will also update links on the page. Currently, there is a broken link on the auth side that needs to be updated so that it points to the new link of the [static page](https://www.va.gov/education/check-post-9-11-gi-bill-benefits) . [Slack convo for context
](https://dsva.slack.com/archives/C01K37HRUAH/p1715701313803759?thread_ts=1715700637.586959&cid=C01K37HRUAH)

### Links

- IA tracker for static page URL #80294 

### Team

- Team Name:
- Designer:
- Product Manager:
- Slack (_optional_): 

### Task List
- [x] Connect with product team
- [ ] Create a backlog ticket for product team
- [x] Team creates redirect ticket

## Acceptance Criteria
- [ ] Tool URL has been updated.
- [ ] Old URL redirects to the new URL
- [ ] Link to static page within tool is updated with new URL

**Comment by jennymayoco** [comment]
There isn't a team currently working on this

**Comment by kristinoletmuskat** [comment]
@strelichl we still need this ticket but don't have a product team to do it. So do you think blocked makes sense? Or icebox?

**Comment by scjwalker** [comment]
Slacked with Cassidy Beach from WEAMS Public/SOB/YRT about the needed URL change.
Requested that the team get the change in their backlog, and that I get notified:
- when they have a tentative date
- on go-live date.

**Comment by scjwalker** [comment]
This has become a renaming effort. The IA work ticket tracking the effort is [96262](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96262). I'm closing this ticket, since that one's being used now.
