### ISSUE TITLE
Move Collab Cycle swim lane mural to VA Mural account

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80310]
## User Story
As a VFS team member, I don't want to see "archived" messages on resources I'm being directed to because it makes me unsure if I can trust the resource or not.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
The Oddball Mural account has been deactivated since all VA contactors are now asked to use the VA Mural instance. While our [Collaboration Cycle Swim lane mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1686676305244/4fb520e97c488d1fd053d93c6497e09ab0880207?sender=u0574179b1d97118ccc0e3591) is still accurate, there is an "archived" message that appears on the mural, which could introduce trust issues with VFS teams if they're uncertain if it's accurate or not. In addition, just because this mural is accurate now, it does not mean it will always be. The purpose of this ticket it to relocate the mural board from Oddball to VA mural and update the link on the Platform Website. 

## Impacted Artifacts
[Collab Cycle swim lane mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1686676305244/4fb520e97c488d1fd053d93c6497e09ab0880207?sender=u0574179b1d97118ccc0e3591)
[Collab Cycle swim lanes diagram on Confluence](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2710864175/Collaboration+Cycle+Swim+Lanes+Diagram)

## Tasks
- [x] If you have not already done so, you will need to create a VA Mural account.[ Instructions ](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Mural)are available on Platform Website. 
- [x] For [tips for transferring boards](https://oddball.slack.com/archives/C06S193U9FT/p1712621391405709), view the #temp-mural-transition channel on Oddball Slack. 
- [x] Transfer the board as-is from Oddball mural to VA mural. No other changes are needed at this time.
- [ ] Update the link in 2 places:
   - [x] On the live [Collaboration Cycle Overview page.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) 
   - [x] On the revised/draft Collaboration Cycle Overview page. Coordinate per ticket #76794. Coordinate with Erin and Rebecca.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Collaboration Cycle swim lane mural has been moved to the VA mural account and no longer includes an "archived" message.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Per Naomi:

> Tip for transferring boards from the Oddball - VA.gov to VA - Department of Veterans Affairs workspaces
> I don't know about others, but I kept encountering boards that say they've been archived with no ability to copy/paste. BUT, I just discovered you can "unlock" the board by first downloading it (click the download icon in the top left nav), and the board then becomes editable. From here you can copy and paste into a board opened in a different browser logged in to your VA account.

**Comment by allison0034** [comment]
I have a Mural account, however this board is archived. I am not seeing a download option, still investigating.

**Comment by allison0034** [comment]
I was able to move the Mural, new link is [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713545938981/37e39668eee6d6756e56b687f9c7851632340258?sender=u870c8d9c6b47768924793768).

**Comment by allison0034** [comment]
I also moved the [custom track flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713468662718/732552903c217c1df1e77c417c76946e7b174e81?sender=u870c8d9c6b47768924793768) and [orientation workflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713546571381/115e7c951d9f93c77e3129c40c8d4cdf2527bcb5?sender=u870c8d9c6b47768924793768).

**Comment by allison0034** [comment]
@erinrwhite @rferguson13 I have moved the collab cycle swim lanes mural to the VA account. There is a task "Coordinate per ticket #76794. Coordinate with Erin and Rebecca." Does anything else need to be done for that ticket?

**Comment by erinrwhite** [comment]
@allison0034 @rferguson13 I think that all we'll need to do is link to this mural from the updated [CC overview page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview) - but the mural will also need to be updated to accurately reflect CAIA's role

**Comment by shiragoodman** [comment]
@erinrwhite good call out. At this time, let's just move the mural as-is and we'll focus on updating it per CAIA's role later on.

@allison0034 thank you for moving the other 2 murals! you rock.

**Comment by allison0034** [comment]
@erinrwhite I don't see the swim lane linked on your page. We should probably add it.

**Comment by allison0034** [comment]
@briandeconinck I am just pending @erinrwhite @rferguson13 adding a link to their overview page in their ticket, otherwise you can peer review the current over page.

**Comment by erinrwhite** [comment]
Thank you @allison0034! Link added to the new [Collab Cycle overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview) page, and I also added in language about Mural per Cheryl's request in slack. @rferguson13

**Comment by briandeconinck** [comment]
@allison0034 This looks good to close out!
