### ISSUE TITLE
Add Direct deposit bank account summary information to confirmation screen

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#80313]
## Issue Description
We're adding an alert to the confirmation page to inform applicants that the bank account information they entered will be used for any education benefits they use as well. 

## User story
As a Veteran, I want to see what bank account information I entered on the confirmation screen so that I don't have to remember what I entered on a previous screen and I can easily double-check if I'm using a different account for education benefits.

---
## Tasks
- [x] Front end only

## Acceptance Criteria
- [x] Form is updated to match the designs
- [ ] ~Needs Staging Review so keep behind feature flag/flipper~

## Resources
The [Figma design for the confirmation screen](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=3079%3A5253&mode=design&t=Co8bJZ8DfB0IGQah-1) has been updated with changes. This is ready for an engineering ticket.

Summary of changes:
- Added a  h3 for "Direct deposit account information"
- Updated the direct deposit alert title and copy
- Changed the alert title to an h4
- Added bank account information below alert plus some additional copy explaining where to view your direct deposit information

## Developer note:
The Direct deposit account information heading and section should only display if the applicant provided direct deposit information. See note in the annotated Figma.

**Comment by aplatt-coforma** [comment]
@matt4su - created this ticket as the implementation ticket for #78346. Adding to product backlog column to include in next sprint

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/80313?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Feature demo by Todd:
https://www.loom.com/share/1aaa9772ff23486288628cd3530c606b?sid=b909509e-72ae-4454-8b08-006418c01db5
