### ISSUE TITLE
Remove practice areas from Collaboration Cycle Office Hours info

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80311]
## User Story
As a VFS team member, I want to sign up for the appropriate office hours so that I can get help from Platform with my teams product.

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
Per PO decision, Governance team will no longer use Collaboration Cycle Office Hours to discuss design, accessibility, IA, or content issues. Instead, VFS folks are encouraged to join the design office hours. The messaging on the[ Collaboration Cycle Office hours signup on Platform Website](https://depo-platform-documentation.scrollhelp.site/support/office-hours) still lists the practice areas so we need to remove them.

## Impacted Artifacts
[Collaboration Cycle Office hours on Platform Website](https://depo-platform-documentation.scrollhelp.site/support/office-hours)

## Tasks
- [x] Remove the language "practice areas that regularly attend" and all PA's that are listed from the table

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Collab Cycle office hours on Platform website no longer lists the practice areas 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@allison0034 - Since this was straightforward, I went ahead and removed the information. It should be published today (April 11). We can check on it once you're back.

**Comment by allison0034** [comment]
Looks good!
