### ISSUE TITLE
Developer Documentation Point to URL standards on design.va.gov/

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80323]
## Issue Description
Per [this Slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1712174986356779), review Developer Docs for instances where URL standards found on design.va.gov should be called out and linked to [this page.](https://design.va.gov/content-style-guide/url-standards)

[An initial search pulls up 56 Developer Docs](https://depo-platform-documentation.scrollhelp.site/search.html?l=&max=10&ol=&q=url&s=developer-docs&start=0) where URLs are mentioned

---
## Tasks
- [x] Starting with Developer Docs search, identify only the pages where URL standards and link should go
- [x] Contact SME with potential pages and request help in identifying pages where link can be added

## Acceptance Criteria
- [x] List of pages to be updated has been created
- [x] Page(s) updated

**SME**: Mikki Northuis
**Slack Thread**: [HERE](https://dsva.slack.com/archives/CL181NRJQ/p1712174986356779)
## Relevant Links
[URL Standards](https://design.va.gov/content-style-guide/url-standards) 
[Using Parameters in URLs](https://design.va.gov/content-style-guide/url-standards#guidelines-for-parameters-in-urls)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/80323?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/80323?planning-poker) with Zenhub @CherylEvans

**Comment by jknipes** [comment]
@jknipes Review in next Sprint Planning, come to a consensus on estimate score

**Comment by taylojill** [comment]
Mikki replied via [this Slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1719416873147059?thread_ts=1719340071.469889&cid=CL181NRJQ). She will review the pages I suggested and get back to me. We will not create a new page, only link out to VADS page if it makes sense.

**Comment by taylojill** [comment]
Mikki (SME) has been OOO for two days. I'm still waiting to connect with her.

**Comment by jknipes** [comment]
Progress on this ticket has been blocked, waiting confirmation to move forward from SME. Unable to complete in this sprint. Moving to Backlog.

**Comment by taylojill** [comment]
I received feedback from Mikki via [this Slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1719340071469889) on 7/3/2024 and will update one page by adding a link to the URL standards page located on design.va.gov. Page checked for blockers and date stamped, ready to publish.

**Comment by jknipes** [comment]
work is complete moving to _Closed_
