### ISSUE TITLE
CT-103: Add information regarding PL115-407 Section 103 to the Comparison Tool Profile Pages 

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8032]
As a Comparison Tool user, I need to know which institutions are compliant with PL115-407 Section 103, so that I can make informed decisions about where to use my education benefits.

## Assumptions:
1. The stories linked to this EPIC have been agreed upon by reps from OIT, DEPO and EDU.
2. This work follows the [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request).

## Acceptance Criteria
1. All linked stories have been implemented and tested.

## VSP Collaboration Cycle.
- [x] Project Kickoff - #7131
- [x] Design Intent Collaboration - #7586
- [x] Usability Testing Prep - #7831 
- [x] Research Plan Review - #7400
- [x] ~Information Architecture (IA) Request~ - N/A
- [x] Analytics Request - #8959 
- [x] ~Contact Center Review~ - N/A
- [x] Staging Review - #9158 
- [x] ~Privacy and Security Review~ - N/A
- [x] Full Accessibility and 508 Office Audit - #9870 
- [x] Post-launch Check-in - Submitted via vfs-all-team on 07/28

## Supporting Artifacts
1. [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/product-outline.md)
