### ISSUE TITLE
[CST] [DataDog RUM] [Claim List] Set up basic DataDog RUM Settings in CST

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#80333]
## Issue Description
We need to set up `datadogRum.init` for the CST, and put it behind a conditional to prevent it from loading on local environments.

---
## Tasks
- [x] Setup `datadogRum.init` in CST
- [x] Make sure it's behind a conditional to prevent loading on local environments

## Acceptance Criteria
- [x] `datadogRum.init` is set up for CST
- [x] It does not load on local environments
---
## How to configure this issue
- [Setup Real-User Monitoring (RUM) Dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/blob/main/platform/analytics/setup-real-user-monitoring.md)

**Comment by pmclaren19** [comment]
Putting back into 'In Progress' so that @samcoforma can write unit tests for test coverage
