### ISSUE TITLE
Document Form Update Process

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80347]
## Issue Description
_To ensure consistency and best practices, we need to document the approach and process we took to updating the Burial form while the existing form remained live._

---
## Tasks
- [ ] Document user experience
- [ ] Document engineering workflows/stages
- [ ] Define major stage gates
- [ ] Identify best practices
- [ ] Document overall process

## Acceptance Criteria
- [ ] Documentation on updating a live form that can be leveraged by other VA teams (i.e. Platform documentation)

**Comment by DLarson-Oddball** [comment]
@steele-lm Updated docs to add information for vets-website & clarified order of events in cleanup!
