### ISSUE TITLE
Platform Atlas - Calculate VFS Staff

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80348]
### Description
Support team needs to know how many VFS staff we have Jan 1 2023 to March 30 2023 versus Jan 1 2024 to March 30 2024 in order to show the ratio of support people to onboarded VFS people. 

### Tasks
- [ ] Run report per the attached image (in Slack chat between Lindsey and Alyssa)

## Success Metrics
- [ ] That a report has been generated for Alyssa in Support

### Acceptance Criteria
- [ ] Report for 2023 and 2024 on VFS staff in Atlas

<img width="1709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dac6d4c3eb1335a8b5e66e33b9ac2722a3fa2450/image.png" alt="image.png" />

**Comment by jennb33** [comment]
As of 4/25/2024 - there are 128 resources out of 500 in Atlas that don't have a start date. Idea is to go to Support team and request that they provide us with the dates that those resources started, then we can backfill that information.

**Comment by jennb33** [comment]
@rmtolmach 's GitHub Onboarding query: https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+onboarding+label%3Aplatform-orientation+created%3A2024-01-01..2024-03-31+

GitHub Offboarding query: https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3Aoffboarding+created%3A2024-01-01..2024-03-31+

**Comment by jennb33** [comment]
Kyle's beautiful code in Slack [here](https://adhoc.slack.com/archives/C0459AQ5GBT/p1714042789047319?thread_ts=1714042608.664869&cid=C0459AQ5GBT)

**Comment by jennb33** [comment]
Per @RachalCassity: You should be able to import the users after all the data is complete. In Atlas, not GitHub, you should not have to fill in the dates manually. Please reach out if I can help with the spreadsheet format

**Comment by jennb33** [comment]
I asked Alyssa in Support how often that team would anticipate running this report:
"wondered if your team will want to be pulling this kind of query on a regular basis, and if so, how frequently will you want to pull it? Monthly? Quarterly?"
Her response was as follows: "Honestly, we've only pulled it once before and so I'd say once a year? Maybe twice?" I'm asking her if that's because Atlas is still a fairly new product, but at this time I don't see that they will need a query for this request at this time; it might still be good to empower this team to pull their own reports of this nature. 
Attn: @rjohnson2011 @LindseySaari

**Comment by rjohnson2011** [comment]
Data for missing VFS staff start dates is complete in this spreadsheet - https://docs.google.com/spreadsheets/d/1AVxWPZqLFBcoA6veJU08Fu5nQq21cv2GN1SOp2FXm6U/edit#gid=0

Opening up new ticket for the import to Atlas and run query portion.
