### ISSUE TITLE
Toxic Exposure - Data Transformation #3 - Gulf War Hazards

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#80352]
## Issue Description
The scope of this ticket is to transform the vets-website data structure into Lighthouse structure -  toxicExposure.gulfWarHazardService object

As a Veteran I want to submit a disability compensation claim inclusive of any time I spent in the Gulf War or after 9/11/01 so that I can ensure any TE conditions I have that resulted from my time in these locations is considered during review of my application.

The outcome of this work is that the completed 526 will include any data the Veteran entered regarding the Gulf War (section 15b in the paper version).

https://developer.va.gov/explore/api/benefits-claims/docs?version=current

Notes - https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/72816
FE has Gulf war data coming from two pages:
- Gulf war 1990 
- Gulf war 2001
The data transformation needs to be pulled in from both those objects.
An object maybe missing if the page is not visited
---
## Tasks
- [ ] Add toxicExposure.gulfWarHazardService object attribute to Requests::Form526 DTO class
- [ ] Update Form526ToLighthouseTransform to transform Gulf War Hazard service 
- [ ] Update Form 526 to LH transform
- [ ] Update Unit test to check for toxicExposure.gulfWarHazardService for diff scenarios

## Acceptance Criteria
- [ ] Form526ToLighthouseTransform has the toxicExposure.gulfWarHazardService object
- [ ] If Veteran selects "None of these options", set NO
- [ ] If veteran selects at least one gulf war location, set gulfWarHazardService.servedInGulfWarHazardLocations to YES. 
- [ ] If veteran does not select any locations, send Null
- [ ] Do not populate gulfWarHazardService.serviceDates - confirm with the VBA check in notes that no date is being populated in 15 B, C and D
- [ ] Changes to JSON schema are documented

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
