### ISSUE TITLE
Edit Ticket: Steps for 'Downtime Notifications' page (content edits for #73181)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80354]
### Context
Suggested content edits from [footer ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73181) 

### Description

>"Please review the list order here: https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-Formslibraryapplications
> 
> It appears that (3)(a)(c) should really be (3)(b), and that (3)(b) should be (3)(b)(a) and (3)(c) should be (3)(b)(b). That is, one of the optional parameters for `downtime` is `requiredForPrefill`, and that parameter can take arguments of `true` or `false`.
> 
> If this isn't the case, the list should be revised to make the usage of downtime more clear."

### Tasks
- [x] Confer w/ Brian Smolensky re: any SME that has been contacted
- [x] Reach out to Front End CoP in Slack for SME to review this page
- [x] Determine whether suggested changes should be made
- [x] Update page accordingly
- [x] If page is updated, confirm accuracy with the SME
- [x] Check page for launch-blocking issues

### Acceptance Criteria
- [x] Page is up-to-date and is ready for deployment

**Comment by jknipes** [comment]
Duplicate ticket, Date removed. Will schedule edit for an upcoming sprint

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/80354?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
Work is completed, moving to _Done_
