### ISSUE TITLE
[ENG] 10-10CG - BUG: Investigate issue "ActionController::InvalidAuthenticityToken: Can't verify CSRF token authenticity"

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#80361]
## Background
Veterans & Caregivers who have submitted the 10-10CG form are given the option to download their completed form for their records.  Occasionally, an applicant will try to download the form, but is not able to.  The error we are seeing is `ActionController::InvalidAuthenticityToken: Can't verify CSRF token authenticity`.  
We need to find the root cause of this error.  When it does come up, it seems to happen alot within the same day to multiple applicants.

### Resources
- [Datadog APM logs](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Acaregiver-application%20-status%3Aok&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=true&historicalData=true&messageDisplay=inline&query_translation_version=v0&sort=desc&spanType=service-entry&traceQuery=&view=spans&start=1712598741287&end=1712685141287&paused=false)
- [Sentry Log](http://sentry.vfs.va.gov/organizations/vsp/issues/6196/?environment=production&project=3&query=is%3Aunresolved+actioncontroller&statsPeriod=1h)
- [DD APM Log 4/23/24](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Acaregiver-application%20-status%3Aok&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=2404468230651322133&spanType=service-entry&timeHint=1713867178738&trace=AgAAAY8KccLyQVYFAAAAAAAAAAAYAAAAAEFZOEtjZEFJQUFDa0Zienc1NVVCSjBBQwAAACQAAAAAMDE4ZjBhZDMtYmRmOS00YjZjLTk4ZmItZjVhNDc1MmViM2M1&traceID=662789aa000000000240cc5cae10a4c5&traceQuery=&view=spans&start=1712670561574&end=1713880161574&paused=false)
- [Nov 2023 Slack convo](https://dsva.slack.com/archives/C0310PNS7TQ/p1701190165719319)
- [March 2024 Slack convo](https://dsva.slack.com/archives/C0310PNS7TQ/p1709395624967029)

## Tasks
- [ ] Investigate error and what actions/events may cause this to happen
- [ ] Discuss with teammates or other resources within VA.gov space, if needed
- [ ] Once there are some ideas on root causes and/or resolutions, discuss with the team on next steps

## Acceptance Criteria
- A Determination of the issue and possible cause is found & discussed with the team

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that users can download the 10-10CG form in PDF without issues. The loading spinner appears after the user clicks the link to download the file.

**Comment by hdjustice** [comment]
Looks like this [error is still logging](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20service%3Acaregiver-application%20-status%3Aok&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=true&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=errors&traceQuery=&view=spans&start=1715690100487&end=1716294900487&paused=false).  We will monitor over the next couple days
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/5267f9a0-d215-4721-971b-143e713a7a88)

**Comment by hdjustice** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/6dec66cb-b6d2-4c00-8d8e-07b9be45715d)
