### ISSUE TITLE
SPIKE | COE | Fix Staging Environment

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80368]
## Issue Description
_As part of a COE API Key update, it was discovered that the staging environment for COE is not working. _

---
## Tasks
- [ ] Determine why the staging environment is not functioning

## Acceptance Criteria
- [ ] Document why the staging environment is not functioning
- [ ] Create follow-on tickets to complete the work
---

**Comment by tblackwe** [comment]
Entrypoints for the application:
https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/lgy/coe
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/coe_controller.rb

**Comment by va-albers** [comment]
Zach did a successful staging test on April 10.
