### ISSUE TITLE
[Design] My VA Component Audit: Review secondary links

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80376]
## Background
Daniel performed an audit of all custom components in use on My VA and found a few areas we should review to adopt VA design system components that also align with USWDS. This ticket is to review the secondary links or "link lists" My VA.

[Daniel's notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77211#issuecomment-2045802841):
**Priority:** Medium
**FE Effort:** Medium-High
<img width="1075" alt="80376 screenshot" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/f02e946a-6784-406f-a947-ddf916a170ca">

These section links appear to use custom MyVA styles and VADS util classes, even though this pattern is documented in the “Link - Collection” section of the design system documentation pages. However, this pattern doesn’t appear to exist in Storybook documentation. Maybe there’s an opportunity to check with the DS team here and see if we can help graduate this pattern into DS code and storybook docs. These links also use Font Awesome icons, so it could be a good time to revisit this anyhow.

## Tasks
- [x] Review findings
- [x] Explore options in VADS
- [x] Mock up option(s)
- [x] Review/share with team and discuss next steps for implementation

## Acceptance Criteria
- [x] We have options for updating the secondary links/link lists on My VA

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** PM
- **_How can this work be validated?_** design options are reviewed

## Resources
- [VADS Docs for Section Link](https://design.va.gov/components/link/collection#section-links)

**Comment by mattmarino-adhoc** [comment]
Did not meet with VADS, discussed with them on Slack instead. We have decided to leave the secondary links as-is for the time being, while the icons used with them will be updated with va-icon adoption.
