### ISSUE TITLE
[Design] My VA Component Audit: Review CTA links in cards

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80371]
## Background
Daniel performed an audit of all custom components in use on My VA and found a few areas we should review to adopt VA design system components that also align with USWDS. This ticket is to review the CTA links in cards on My VA.

[Daniel's notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77211#issuecomment-2045802841):
**Priority:** Medium-Low
**FE Effort:** Low
<img width="1084" alt="80371 screenshot" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/bfcb13fe-bcc8-491f-94d8-ca14889b2c68">

These links inside of the various va-card elements we use on MyVA could be aligned more closely with VADS.  We are already using the global link styles here, but we could consider using the custom va-link element.  We may also need to use a different icon here going forward, since this is currently using a FontAwesome icon, which may be changing to use icons more similar to USWDS (which was forked from Material Icons).

Another option could be to use the “Action Link” from VADS here, which looks a bit different, but serves a similar purpose.  These links also use FontAwesome, but they might get updated for us whenever the DS team updates the patterns and components with future icons.

_Per discussion with team, icon and fontawesome work will be done separately._

## Tasks
- [x] Review findings
- [x] Explore options in VADS
- [x] Mock up option(s)
- [x] Review/share with team and discuss next steps for implementation

## Acceptance Criteria
- [x] We have options for updating the CTA links within cards on My VA

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** PM
- **_How can this work be validated?_** design options are reviewed

## Resources
- [Storybook Docs for Link](https://design.va.gov/storybook/?path=/docs/components-va-link--default)
- [Storybook Docs for Link Action](https://design.va.gov/storybook/?path=/docs/components-action-link--primary)

**Comment by mattmarino-adhoc** [comment]
As previously discussed we are going to use the Active link style for cards. The My VA file, as well as the Auth. Exp. library file, should reflect this.
