### ISSUE TITLE
[PM] Review updated authenticated experience team documents

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8038]
## Background

I updated a bunch of the docs in our [team folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/authenticated-experience) and would like you to review them for accuracy, content, etc. and provide feedback.

## Tasks

- [x] Review the [team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/charter.md) and provide feedback
- [x] Review the [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/product-outline.md) and provide feedback
- [x] Review the [roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap.md) and provide feedback

## Acceptance criteria

- [x] Matt has reviewed all the docs and sent feedback to/discussed feedback with Samara.

**Comment by mshea0606** [comment]
Documents have been reviewed and  OKRs added to product outlines.
