### ISSUE TITLE
[CST] Update "Last updated: [date]" so that it always shows most recent Recent Activity update

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#80389]
## Value Statement
**_As a_** Veteran
**_I want to_** see the latest update to my claim in the "Last update" timestamp
**_So that_** I know how up-to-date my claim is and that it's being worked on

---
## Background Context

Currently, the "Last updated: [date]" string is not necessarily aligned with the last update in the Recent Activity section. 

The design goal is that "Last updated" includes the most recent update in Recent Activity, regardless of what type of update that is.

## Screenshots
Staging user: vets.gov.user+23@gmail.com
Link to claim: https://staging.va.gov/track-claims/your-claims/600494815/status

<img width="925" alt="Screenshot 2024-04-10 at 12 22 38 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/3af9ad40-fafe-4820-99ff-8495fe3df0d3">

---

<img width="843" alt="Screenshot 2024-04-10 at 12 22 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/092cfdbc-919a-4cbd-8b26-9988fdfd59c6">

Last updated
<img width="1070" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2hKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2821b1b3eb4a1052a2e746bff302a4c833674e6b/Screenshot%202024-04-09%20at%205.08.55%E2%80%AFPM.png" alt="Screenshot 2024-04-09 at 5.08.55 PM.png" />

## Engineering 
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _The "Last updated" timestamp matches the most recent activity update in the Recent Activity section in the Claim details Status tab_
