### ISSUE TITLE
Implement approach to user pass-in

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#80392]
## Description
This ticket outlines the need to implement an approach for passing user information into the system, ensuring secure and efficient user authentication and data handling.

---

### Tasks
- [x] Define the method for user pass-in.
- [x] Implement the user pass-in functionality.
- [ ] Test the user pass-in process.

### Acceptance Criteria
- [x] User pass-in method is clearly defined and documented.
- [ ] User pass-in functionality is implemented and working as expected.
- [ ] The user pass-in process has been thoroughly tested.

**Comment by patrick-black-oddball** [comment]
Implementing user pass in as follows:

- The calling application will pass in it's authentication token and two parameters
- - "Auth-method" = the authentication system used by the upstream system i.e. "GitHub" or "Slack"
- - "Auth-User" = the authenticated user that triggered the requested call.

The combination of these two inputs will be used to allow displaying the originating requestor.

Note - the passed in users will not be used for authorization purposes - instead they will be meta data for later display.
