### ISSUE TITLE
Conduct Inventory of K8s branch

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#80394]
## Description
Carry out a detailed analysis to identify the differences between the Kubernetes (k8s) branch and the master branch. This will inform the strategy to consolidate changes and streamline branch management.

---

### Tasks
- [x] Create a Confluence page documenting each variance between the k8s branch and master.
- [x] Formulate a comprehensive plan to merge or eliminate the k8s branch, minimizing disruption.

### Acceptance Criteria
- [x] A Confluence page listing all variances between k8s branch and master is available.
- [x] A detailed action plan for reconciling the branches is documented.

**Comment by stevenjcumming** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3111682051/k8s+to+master+merger
