### ISSUE TITLE
BE | Profile | Direct Deposit | Update Datadog Dashboards

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#80413]
## Background
The Direct Deposit C&P and EDU forms are being combined into one form. The Auth Experience Profile team wants to add/update Datadog dashboard components to enhance our ability to analyze and monitor direct deposit traffic.

## Tasks
- [x] Add dashboard components that display traffic for new DD endpoint.
- [ ] Add error-rate monitor for new DD endpoint.
- [x] Add dashboard component that displays Lighthouse direct deposit errors.
- [ ] Add dashboard component that displays control information for GETS.
- [ ] Add dashboard component that displays control information for PUTS (adds/updates).

## Acceptance Criteria
- [ ] Review components with team.
