### ISSUE TITLE
Watch Officer | Error Rate of API Calls

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80418]
## Issue Description
_The week of April 1, we have had 17 cases in the last week where the error rate went over 30% for 686/674 API calls.  With the exception of a large window over the weekend (Sunday 3 pm ET - 7 pm - likely caused by the VBMS maintenance window) - do we need to be looking into [these errors](https://vagov.ddog-gov.com/monitors/184283?q=%2A&sp=&view=spans&live=1w)?_

---
## Tasks
- [x] Determine cause of errors
- [x] Create follow-on tickets as needed
- [x] Respond with outcome in [Slack thread](https://dsva.slack.com/archives/C0547Q0K0LF/p1712718016231139)

## Acceptance Criteria
- [x] Next steps for errors determined
---

**Comment by micahaspyr** [comment]
When looking into the error rates, I noticed that once the job is retried, Rails.logger.warn tracks the warning and states 'VBMS::SubmitDependentsPdfJob failed, retrying...'
That is to be expected

But, then the   "send_error_to_sentry(e, saved_claim_id)" is also called.  Not only does it send an error to sentry but it ALSO sends the Rails.logger.error message.  This means that two things are being simultaneously logged.  One is a warning that states the job is being retried which is good, normal behavior.  The other sending the error to sentry not only sends to sentry, but also logs a rails error.  THat's not the behavior we want and we should get rid of the "send_error_to_sentry" statement as we're trying to move away from sentry anyhow. We've ran into this type of issue before on another background job and removing that statement fixed the monitoring issue.

In the end, these errors are not truly critical and can be ignored as normal warnings

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/d6431c11-a461-45f4-ab34-728474a9e9e0)

**Comment by va-albers** [comment]
Hi @micahaspyr - thanks for this info, and noting the double logging of errors in this case.  I did a check on the 4 messages included in this and it seems like it is the `BGS::DependentService failed!` message that is causing most of these errors.  I added four tiny graphs to [the dashboard](https://vagov.ddog-gov.com/dashboard/vad-969-xqc/benefits-dependents-686674) that show the breakdown.  Given this does the description above apply?  Thanks!

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/119101230/7cabd54b-b188-4a7b-99be-316eb1152fb4)

**Comment by va-albers** [comment]
I did a review of one of the recent errors with this error message type [here](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20service%3A%22dependent-change%22%20resource_name%3A%22V0%3A%3ADependentsApplicationsController%23create%22%20host%3A%22i-06f1c6940ac8964ee%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=4084398516055586941&spanType=service-entry&trace=ba8aee3f38421dff&traceID=1213431978343155347&traceQuery=&view=spans&start=1713798384848&end=1713798444848&paused=true) - this one gives an error of "A problem has been detected with the upload token provided."

**Comment by micahaspyr** [comment]
@va-albers that's correct.  I focused on non-maintenance based errors (which seem to be the major problem) since those based on downtime are already accounted for. We can't do anything about maintenance windows so I considered that outside of what we can specifically do.

**Comment by va-albers** [comment]
Hi @micahaspyr - to follow up on "We can't do anything about maintenance windows" 
- do you know if we do a lookup on the PagerDuty EVSS Maintenance windows to display a message to users telling them that the system is temporarily unavailable?  It would seem like that would be one potential way to avoid having failures during maintenance windows.
- also it appears that the "Backup Submission Rate successful" monitor is close to, but does not exactly match, the "Backup Submissions Successful"  monitor, suggesting that these failures may be routed successfully through Central Mail?  If that is the case then we should arguably stop showing this metric and show one for failed CentralMail submissions instead.

**Comment by sanjabaj2** [comment]
Reopening the issue as it has lots of context and there are still open discussion points. Once we agree on the next steps, we cam create new issues for actual work stemming from this discussion.

**Comment by micahaspyr** [comment]
@va-albers dependents no longer uses Central Mail as errors are routed to the Lighthouse Benefits Intake API.  

- I'll have to look at the PagerDuty EVSS Maintenance Window query but I'm wholly unfamiliar with it
- Checking backups being sent to BI (instead of CM) those submissions look to be successful.  Since we don't use CM we can check for the Lighthouse Benefits Intake submission failures moving forward.

**Comment by micahaspyr** [comment]
@va-albers we do not do maintenance window checks on any of the non-disability forms as there is a backup pathway for our submissions.  That being said, coe/lgy submissions do not have a backup path so a maintenance window check may be useful if possible.
