### ISSUE TITLE
Staging Review short video for touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80427]
## User Story
As a VFS team member with an upcoming Staging Review meeting scheduled, I want to know what is expected of me and my team prior to the meeting so that I can ensure we are prepared.

As a VFS team member with an upcoming Staging Review meeting scheduled, I want to know what to expect in the meeting so that my team can be prepared and get the fullest value from the 30 minute meeting.

As a VFS team member who just completed a Staging Review meeting, I want to know what is expected of my team post-meeting so that I can be sure my team takes the appropriate action.

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
Governance team understands that people learn and absorb information in different ways - some people prefer to read text, some people prefer to hear and/or see it explained, and others might learn best from experience. While we can't currently support the latter, we are betting that introducing a short 2-3 minute video into existing context will better help VFS teams understand what is expected of them and what to expect within the process. This will hopefully result in less confusion with the VFS, less questions asked within office hours and support channels, and greater understanding of Platform processes.

We have already created a short video for the Design Intent. We also completed research on the video and plan to use the [findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3059908610/Design+Intent+short+video+Research+Findings) from the research to create a video for Staging Review that meets teams expectations. 

The purpose of this ticket is to draft a script, prepare a visual aid, record a video and embed the video within the Staging Review touchpoint page. 

Governance team reviewed the [Pain points, Recommendations, and Opportunities](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2809626855/Pain+points+Recommendations+and+Opportunities) documented by Service Design team during their DI research study. Several of their findings should be taken into consideration while working on this ticket for Staging Review, including:

- DI prep: Long process
- DI prep: Lots to absorb
- Documentation: Context around the documents and expectations is not as clear
- DI Review Meeting: What to expect

### Questions to answer in the video
As a VFS team member, I want to know...

- When should I schedule a Staging Review?
- How do I schedule a Staging Review?
- What should my team do to prepare for the Staging Review?
- What are the Staging Review requirements?
- Where can I go to ask questions ahead of time?
- Who should be included at the Staging Review?
- What should I expect during the SR meeting?
- What should I expect after the SR meeting?

## Impacted Artifacts
SR touchpoint page

## Tasks
- [x] Write SR script
- [x] Prepare visual aid
- [x] Record the video
- [x] Embed the video into the SR touchpoint page

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have recorded an informational video about the Staging Review and embedded it into the Staging Review touchpoint page on Platform Website

## Team Notification
- [X] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
Ok! I need to stop tinkering. @allison0034 - [Here is my proposed video script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3148808241/80427+-+SR+Short+Video+Script). It's currently clocking in at around 3:30, I need to shave a bit off of it. I listed the requirements, but that section takes the longest to read, so we may need to cut more. I also avoided any mention of the scheduling process (calendly and Slack) because that may be changing soon. Go at it!

**Comment by allison0034** [comment]
This looks great, I can only see one thing we could possibly cut.

**Comment by rferguson13** [comment]
Thanks @allison0034! @shiragoodman - Do you want to take a look before I record? [Here's the page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3148808241/80427+-+SR+Short+Video+Script).

**Comment by shiragoodman** [comment]
thanks @rferguson13 ! yes, I will take a look today.

**Comment by shiragoodman** [comment]
@rferguson13 I provided a few comments. I think my comments might also impact the SR touchpoint page, so please take a look and let me know if you'd like to discuss further. Thank you! Overall, it looks great!

**Comment by rferguson13** [comment]
Status update:
- The script is written, the raw audio has been recorded, and the slide deck has been made.
- What's left to do: Clean up the audio, record the slide deck, then put it all together. Once completed and approved, post the video.

**Comment by rferguson13** [comment]
This will carry over to the next sprint. I had some technical difficulties, but they're resolved now. It's close to being done.

**Comment by rferguson13** [comment]
@allison0034 Here ya go! [Here's a link to the video](https://youtu.be/pZBXFnFPaRw).

**Comment by allison0034** [comment]
This looks good to me. There is some slight static, but it isnt terrible. One thing, if we do change anything with Slack workflows or scheduling we need to check the screen shot in these videos.

**Comment by rferguson13** [comment]
@allison0034 @shiragoodman Is the static bad enough that I should try and tinker with it?

**Comment by shiragoodman** [comment]
No, I don't think so.

**Comment by rferguson13** [comment]
Posted the video. It should be deployed today!
