### ISSUE TITLE
Prep for meeting w/ Naomi to discuss Conf. Database as intended tool for Insights

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#80421]
## Purpose
We've identified Confluence's new Database feature as a strong candidate for our intended move to a 1-stop shop for Feedback & Insights.

Let's meet w/ Naomi to discuss her learnings and thoughts over what might be important features/views/capabilities to include for our various stakeholder groups.

## Tasks
- [x] Identify a viable timeslot for team
- [x] Schedule session w/ Naomi
- [x] Prep Mural board (if needed)

## Acceptance Criteria
- [x] Meeting is scheduled
- [x] resource readied
