### ISSUE TITLE
Update the Staging Review script

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80424]
## User Story
As a Governance team member, I want to communicate the goal of the SR meeting so that all attendees are aware of the meeting purpose and the meeting structure.

As a Governance team member, I want to shorten the time it takes to communicate the goals of the SR meeting so that our time in the meeting can be used more efficiently.

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
The Staging Review script (which introduces the purpose of the meeting) is old, potentially outdated, and very long. Many of the VFS teams we meet with have heard the script many times before.

The purpose of this meeting is to update and revise the Staging Review script. The script goals remain the same as they were previously - review where the VFS team failed to meet both QA standards and VA.gov Experience Standards, offer time for questions/discussion, and explain next steps. However in addition to meeting the same goals, we now have a new goal to shorten character count so that it takes significantly less time to read each Staging Review meeting. 

## Impacted Artifacts
[Staging Review touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
[Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting)

## Tasks
- [x] Draft a new script
- [x] Ensure changes made to the script are aligned with the DI script, if/when applicable
- [x] Share with Governance team members for review and feedback

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The SR script has been shortened to roughly half the length it currently is
- [x] The SR script still communicates the goals of the meeting and shares next steps
- [x] The SR script is to-the-point, with no duplication of content, and written in plain language
- [x] The SR script is easy to read for Governance team hosts
- [x] We have published the new script to the operational guidance for Staging Review

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@allison0034 - This is ready for your review: [Update the Staging Review script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3092807702/80424+-+Update+the+Staging+Review+script)

**Comment by allison0034** [comment]
@rferguson13 looking much better! I made a few suggestions and then I took a look at the new DI script to try to align and made an option 2 for you to look at. Just a suggestion : )

**Comment by rferguson13** [comment]
@allison0034 - I love Option 2. Just made one quick edit to it. Share with the team now?

**Comment by rferguson13** [comment]
@briandeconinck - One quick question for you. Then this should be good to go.

**Comment by rferguson13** [comment]
@shiragoodman @briandeconinck @allison0034 - Added to the closing script. Let me know what you think and we can get this updated :)

**Comment by shiragoodman** [comment]
@rferguson13 I am good to go with Option 2, but just remember to delete the last bullet since it is now part of the closing script.
