### ISSUE TITLE
Re-design VFS-facing Staging Review guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#80426]
## User Story
As a VFS team member, I want to clearly understand what is expected of me and what I should expect from the SR meeting so that I can be prepared and ready.

Assignee: @rferguson13 
Peer Reviewer: @allison0034 

## Description
In the research completed by Service Design, it was observed that the Design Intent touchpoint page on Platform Website is overwhelmed with information, making it difficult for VFS team members to easily obtain relevant information from the page. This is shown in [key insights](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2816475137/Research+Findings+Design+Intent+Experience+Study#Key-Insights) 2, 3, and 6. We assume that the problems encountered by VFS teams re: the Design Intent, are also applicable to the Staging Review page. 

Changes were made to the Design Intent via ticket #73513. Within this ticket, we'd like to make changes to the SR touchpoint page that align with the changes made to the DI page.

The purpose of this ticket is to redesign the Staging Review touchpoint page and the Staging Review section of the CC Request ticket to better meet the needs of VFS teams. 

**Note:** In a later ticket, Governance will be recording a short video for the SR touchpoint page that explains the purpose of the SR and walks through the process.. aka the audio version of the content on the page. 

**Update 4/24:** Please be sure to add the Research Findings as a Staging Review artifact per ticket #74774. Ticket #74774 will be closed and all work will be included within this ticket.

## Impacted Artifacts

- [Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
- SR section of the Collab Cycle Request gh ticket via the [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Design-Intent-code-block) - single code block and individual code block for SR

## Tasks
- [x] Review the changes that were made to the DI page. Identify and document a list of improvements (ie requirements) that should be made to the SR touchpoint page as well
- [x] Peer review requirements
- [x] Once requirements are reviewed, propose redesign of the touchpoint page. Ensure all requirements are met.
- [x] Modify the SR section of the CC Request template to align with the touchpoint page
   - this will mostly be to ensure language aligns. We will not be redesigning the layout of the CC Request within this ticket.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have redesigned the Staging Review touchpoint page to reduce quantity of content, eliminate duplicative content, and make it easier for new VFS team members to understand SR expectations
- [x] We have published the revised page to the Platform Website

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Both #81178 and #81179 include updates to the SR Touchpoint Page and the Collab Cycle Kickoff - Moderator Responsibilities doc. Please be sure to coordinate with the assignees of those tickets to ensure changes are not being overwritten.

**Comment by rferguson13** [comment]
Ok @allison0034 ! Here's my draft of the new [Staging Review guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3119022108/80426+-+Staging+Review). I look forward to your feedback!

**Comment by shiragoodman** [comment]
reminder to add the "Last Updated" to the page before publishing!

**Comment by allison0034** [comment]
@rferguson13 this is looking SOOOO much better. I do feel like it is still overwhelming and there is a ton of info on this page. I made some comments on some thing that we may be able to delete, I would try to focus on critical info and not repeating things, I think that will help a little.

**Comment by rferguson13** [comment]
@allison0034 Thank you for your edits. I've gone through them. I also added a table of contents to the top to make it a little easier for teams to navigate the page. However, I wonder if there are any sections we can cut or redirect to? I'm thinking the "artifacts" section is long and overwhelming; could we make a separate page for it and link to it? Just some thoughts.

**Comment by allison0034** [comment]
@rferguson13 interesting idea of linking out to another page. You may want to ping Erin. Artifacts are important and something the VFS team gets wrong a lot so I worry about removing them from the main page. Of course, I also wonder how often teams come back to this page. I made a couple more comments, these are all just suggestions on how to trim the fat, feel free to ignore if they don't make sense.

**Comment by rferguson13** [comment]
@erinrwhite @shiragoodman What are your thought on splitting out the [artifacts section](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3119022108/80426+-+Staging+Review?focusedCommentId=3126853654#What-artifacts-will-be-needed?) into its own page? It could live as a child page with the other SR-related pages.

**Comment by rferguson13** [comment]
@allison0034 Ok! Based on your notes/Erin's feedback, [here's my newest draft of the page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3119022108/80426+-+Staging+Review). Let me know what you think.

**Comment by allison0034** [comment]
@rferguson13 looks good!

**Comment by rferguson13** [comment]
@allison0034 Woohoo! Just updated the page. It will hopefully go live this afternoon.

**Comment by shiragoodman** [comment]
hey @allison0034 and @rferguson13  - I just reviewed the updated page on Platform Website and noticed a couple things that I think we might want to change.

1. I only see 1 reference to the VA.gov Experience Standards and the QA Standards, and it's not where I expected to find it. I do actually agree with where it's written, but I think it might be helpful to reference it again in the "What sort of feedback can teams expect?" section.
2. Speaking of that section, we need to make some updates to the language. I don't know if it's documented anywhere, but we don't use the term "feedback" (or try not to) when referring to issues found at Staging Review. This is bc feedback sounds like it's optional, or potentially subjective. At Staging Review, we have documented actual issues, or findings, that must eventually be fixed by the VFS team. 

Could you take some time to id where we should make these language updates? Also, please let me know if you disagree with me and would like to discuss in person. Thank you!

**Comment by rferguson13** [comment]
@shiragoodman Thanks for the feedback! I've gone ahead and made some edits [here](https://vfs.atlassian.net/wiki/spaces/CC/pages/1810137181/Staging+review). Does this cover it?

**Comment by shiragoodman** [comment]
@rferguson13 changes look good. I added 1 comment - please take a look!
