### ISSUE TITLE
[PM, FE, BE] My VA TMA: Coordinate on next steps for testing improvements

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80439]
## Background
Tom and Daniel have been doing some technical discovery around ways to improve mocking the BE. I'd like to schedule some time this sprint to capture findings and/or next steps into the backlog so we can execute on those improvements over time.

## Tasks
- [x] Schedule time for AJ, Daniel and Tom to meet and discuss findings
- [x] Document next steps - AJ to create tickets

## Acceptance Criteria
- [ ] Additional tickets in the backlog for improving mocking the BE

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ BE dev
- _How will we know this is done?_ there are additional tickets for improvements

## Resources
- [Betamocks Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/betamocks)

**Comment by ajakabcin** [comment]
scheduled time for us to connect on Monday 4/22

**Comment by ajakabcin** [comment]
We met yesterday, Tom and Daniel are going to discuss next steps in further detail together and circle back with me. Good to close this

**Comment by tpharrison** [comment]
@ajakabcin Daniel and I are meeting tomorrow morning.
