### ISSUE TITLE
[BUG][CST]- If logic is checking if the claim exists when we should be checking that the claim attributes exists

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#80434]
## Background Context
Need to update the following files if logic to fix a bug:

- ClaimStatusPage
- FilesPage
- OverviewPage
- StemClaimStatusPage

### Bug
When writing tests found that there was code in several files that checked if the claim existed and if it did then it would hit the first if. This causes issues if the claim doesnt have any attributes because an exception gets thrown on the claimDate not existing.

Old Code:

` 
if (claim) {
      const claimDate = formatDate(claim.attributes.claimDate);
      const claimType = getClaimType(claim);
      const title = `Details Of ${claimDate} ${claimType} Claim`;
      setDocumentTitle(title);
    } else {
      setDocumentTitle('Details Of Your Claim');
    }
`

New Code:

`
if (claim.attributes !== undefined) {
      const claimDate = formatDate(claim.attributes.claimDate);
      const claimType = getClaimType(claim);
      const title = `Details Of ${claimDate} ${claimType} Claim`;

      setDocumentTitle(title);
    } else {
      setDocumentTitle('Details Of Your Claim');
    }
`

## Tasks

- [ ] ClaimStatusPage
- [ ] FilesPage
- [ ] OverviewPage
- [ ] StemClaimStatusPage

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] When an empty claim is passed in there is no exception thrown and the claim goes to the second if statement

**Comment by pmclaren19** [comment]
While working this also found that we needed to update our code for each of these files to account for the claim or claim attributes being null or an empty object. If the claim or claim attributes are null or an empty object then we show the alert ClaimsUnavaliable.
