### ISSUE TITLE
DR | Replace usage of moment.js

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#80433]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to use VA.gov on an old mobile device
**_So that_** I can file a Decision Review form

---
## Background Context

Using moment.js within our Decision Review forms increases the memory usage of the apps. We need to replace usage of Moment because the library is deprecated and is very large. Switching to the [date-fns](https://date-fns.org/) (date functions) library is the current recommendation.

## Acceptance Criteria
- [ ] All instances of `moment` usage have been replaced within our DR forms
- [ ] Ensure we don't have any one-off issues with dates that don't include a time
- [ ] Update unit tests
- [ ] All tasks complete
- [ ] All tests passing

## Designs and Build Notes

N/A

## Out of scope
- Add here

## Open questions
- What problems have been encountered in the past with this conversion?
- How do we check prod for changes / breaks?

## Tasks
- [ ] Replace all instances of `moment` usage within our DR forms
- [ ] Ensure date formatting template strings are updated
- [ ] Update unit tests 
- [ ] Update e2e tests

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@Mottie Validate in parking lot?

**Comment by Mottie** [comment]
@shaunburdick to help validate

**Comment by shaunburdick** [comment]
✅  Reviewed linked PRs. Approved by other members of team as well as outside
✅  Searched `src/applications/appeals` for references to moment, zero found

✅ LGTM
