### ISSUE TITLE
Rehydrate FSR form 5655 from past submissions BE logic work

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#80458]
## Issue Description
When resubmitting form 5655 we want to relieve the users requirement to populate every form field every time a submission is made. We will provide the ability to use field data from prior full or partial submissions for new or repeated form fields on the new submissions. 

Note: Work is starting with BE logic prior to designs, however FE will need to wait for both designs and priority updates. 

## Tasks (to be updated as needed)
- [ ] BE logic creation

## Acceptance Criteria
- [ ] Logic for users to populate known information sourced from prior FSR submissions for new submissions is complete.

## Definition of Done
- [ ] Complete BE development
- [ ] Review BE code as a handoff for new hires
- [ ] Conduct QA testing

**Comment by Tom-Davis** [comment]
All Back End work is complete - closing
