### ISSUE TITLE
[PM] My VA Form Status: Documentation updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80457]
## Background
We have officially kicked on engagement with the Veteran Facing Forms team on the initiative to elevate form status on My VA and on the confirmation page. We are going through collab cycle in partnership with the Veteran Facing Forms team and design intent is scheduled for Thursday, 4/18 at 1:30 pm ET. 

We need to do some documentation updates/prep to set the rest of the team up for success.

## Tasks
- [x] Review documentation below (outlines, proposed designs, LH documentation, etc.)
- [x] Create outline for My VA team space
- [x] Create space for technical discovery documentation
- [x] Capture all open design, UX, research and technical questions we have

## Acceptance Criteria
- [ ] Documentation is written/updates

## Resources
- [Veteran Facing Forms team outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Product%20Outline%20Confirmation.md)
- [Proposed designs (figma)](https://www.figma.com/file/GeBhUvcQAbbGYdmDIS7bRN/Confirmation-%26-Status?type=design&node-id=39-15291&mode=design&t=YGPLhyZ8XkJq0USk-0)
- [Outline on the DE project board (from Matt D)](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170)
- [Lighthouse API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- [Collab Cycle Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80272)

**Comment by ajakabcin** [comment]
Draft outline created [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/benefit-application-drafts-forms-submission-status/README.md)

**Comment by ajakabcin** [comment]
Will continue to add info to the outline as project develops but this is done for now
