### ISSUE TITLE
[PM] My VA Bene Apps: SiP documentation updates

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80462]
## Background
Following up from Angela's work on the benefit application drafts section documentation [60510](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510), it was determined that the current process to configure a form as "save in progress" (SiP) is not as streamlined as it could be. We need to do some documentation updates to set the rest of the team up for success as we start the technical effort.

[Additional context](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510#issuecomment-1658652021)

## Tasks
- [x] Create/update project outline
- [x] Submit collab cycle request
- [x] Communicate upcoming change to team owners of existing SiP configured forms (note that there's nothing for them to do other than be aware of the change) -- _consult with Chante on best approach_

## Acceptance Criteria
- [ ] documentation is updated and relevant forms teams are aware of upcoming change

## Resources
- [Technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)

**Comment by ajakabcin** [comment]
duplicate

**Comment by ajakabcin** [comment]
Communicated updates in ToT and in vfs all teams slack today - will provide updates once we're ready to release. This should not impact existing SiP configured forms.
