### ISSUE TITLE
[CST] Update decision letter alert for appeals decision letters

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#80464]
## Background Context

https://github.com/department-of-veterans-affairs/va.gov-team/issues/74224

We are adding Board appeals decision letters to the Claim Letters page, so we need an alert similar to the alert for initial claims that informs the Veteran that a decision has been made on the appeal and links to the Claim Letters page.

## Design

[Spec in Figma](https://www.figma.com/file/v0y52xy4CvefxkYDqzXlnn/Decision-Letters-for-Appeals?type=design&node-id=1209-8643&mode=design&t=NxJekKt9LRh3dSSW-4)

<img width="1512" alt="AppealsPage" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/01f88613-efca-4668-ba8d-3491e2c33369">

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Add a blue alert that tells Veteran that their appeal decision has been made_
- [ ] _Include a link in the blue alert to the Claim Letters page_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _When a Board Appeal decision has been made, the blue alert shows up under "Curren Status" in the Status tab_
- [ ] _Clicking the "Get your appeal letters" link takes the user to the Claim Letters page_

**Comment by jerekshoe** [comment]
@skylerschain these are screenshots of what a board appeal looks like in the 2 different 'closed' states (`bva_decision` and `post_bva_dta_decision`)
#### bva_decision
<img width="500" alt="Screenshot 2024-04-18 at 3 33 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/de22660b-f6c7-4d4c-9742-45b51f0952c9">

#### post_bva_dta_decision
<img width="500" alt="Screenshot 2024-04-18 at 3 32 57 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/bdea7651-8b48-4593-ae0b-415b4de62b36">

**Comment by jerekshoe** [comment]
This is what it would look with a few tweaks:
<img width="500" alt="Screenshot 2024-04-18 at 3 42 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/bf36caa0-f9bc-4b11-88b6-21b0549f7f09">

**Comment by jerekshoe** [comment]
Note: The arrow on the left would be difficult to get rid of as it's rendered at a higher level than the code that controls what shows to the right of it

**Comment by skylerschain** [comment]
@jstrothman Wanted to loop you. Take a look at Jerek's screenshots above.

It looks like we'll need to update our [design proposal](https://www.figma.com/file/v0y52xy4CvefxkYDqzXlnn/Decision-Letters-for-Appeals?type=design&node-id=1209-8643&mode=design&t=EBi83x0eRtEgWRAY-4) slightly assuming we want to keep all or most of this information in the UI.

**Comment by skylerschain** [comment]
Next steps: @skylerschain to create a new mock incorporating the "issues" as shown in Jerek's most recent screenshot.

**Comment by skylerschain** [comment]
Updated **Design** section with most recent mocks. 
cc: @jstrothman

**Comment by skylerschain** [comment]
Next steps here are for @skylerschain and @jerekshoe to capture screenshots of various UI states to show board team.
