### ISSUE TITLE
[CST] Update language in Claim Letters page to account for appeals letters

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#80468]
## Background Context

https://github.com/department-of-veterans-affairs/va.gov-team/issues/74224

We need to update the Claim Letters page header to include reference to "appeals" and we need to create a new subheader for appeals in the letters list.

**Note:** There is one other update to this page that needs to be made, which is the update to the header and subheader language. That change is captured in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74223).

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

[Spec in Figma](https://www.figma.com/file/v0y52xy4CvefxkYDqzXlnn/Decision-Letters-for-Appeals?type=design&node-id=1209-8593&mode=design&t=vM77GB6pVdw3Ub9H-11)

![ClaimLettersPage@2x](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/0644b23e-f4ba-401c-bc54-04b8d1e8e174)

## Engineering
- The breadcrumb change the header change should be behind the `cst_include_ddl_boa_letters` feature toggle
- need to replace "Board Of Appeals Decision Letter" language on subheader with no language.

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Update the page header to include reference to Appeals (see spec)_
- [ ] _Create new subheader `Appeal decision letter` to be used for appeals in the letters list_
- [ ] Update docTypeToDescription so that the types are using 'sentence style' 
`EX:   
  27: 'Appeals decision letter',
  704: '5103 notice',
  706: '5103 notice',
  858: '5103 notice',
  184: 'Notification letter',` 

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria

- [ ] _The Claim Letters page now includes references to appeals in the header_
- [ ] _Appeal decision letters in the list have a subheader `Appeal decision letter`_
- [ ] _Appeal decision language added to header description language_
- [ ] _Header and breadcrumb change is behind cst_include_ddl_boa_letters feature toggle_
- [ ] _The letter types show in 'sentence style'

**Comment by skylerschain** [comment]
@uxgary is right that this should include the change to the breadcrumb. Update image above with that change included.

**Comment by skylerschain** [comment]
We should hold off on putting this into production until we've resolved questions we discussed with the board folks yesterday.
cc: @jstrothman

**Comment by pmclaren19** [comment]
Verified these changes in Staging and that the feature flag works.
