### ISSUE TITLE
[task] NOD | Feature Definition and Content Approvals: Downloadable Copy of Submission

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#80475]
## Value Statement
**_As a_** product team
**_We want to_** get approval for the solution approach
**_So that_** we can create user stories and kickoff delivery work. 

---
## Test Notes and Design Links
- [Feature Requirements Doc](https://docs.google.com/spreadsheets/d/1FAuDEKlZ99iWdWKyDNQCfCYMose4AGmsNCnSSMk5WNw/edit#gid=1539283867)
- [Design](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=831%3A76228&mode=design&t=igxNySzyPuhKCkuM-1)
- [Content](https://docs.google.com/document/d/1cJhU6XtAepRIRMCA_PecLHZQr2vGhrELr4Sesm6fHAU/edit?usp=sharing)

## Tasks
- [x] Get approval for MVF features
  - [x] Create FE/BE tickets
- [x] Get approval for content
  - [x] With CAIA
  - [x] With BVA (send to JG)
- [x] Get approval with DST
  - [x] Create experimental tickets (if required)
  - [x] Attend Design Council meeting
- [x] Connect with Forms team
  - [x] Setup meeting with Forms team
  - [x] Determine what aspect of the [show status](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170) work can be incorporated to our release 
- [x] @saderagsdale Get average time to generate PDF from Lighthouse (Michael Hobson is the contact)

## Definition of Ready 
- [x] Secondary prioritization completed
- [x] Date scheduled
- [x] Stakeholders and attendees added
- [x] Materials prepared

## Definition of Done
- [x] Opportunities sequenced
- [ ] @saderagsdale Outcomes and success measures defined
- [ ] Data analysis setup on DataDog/Domo/VBA business dashboard

**Comment by saderagsdale** [comment]
@eileen-coforma will prep a slide with open questions and content they'll need to review. Will also setup time with Shaun to show design intent

**Comment by eileen-coforma** [comment]
Will review features to prioritize for MVF during product huddle

**Comment by eileen-coforma** [comment]
Will be sharing MVF design with Julie during today's Benefits Tools Design Sync.

**Comment by saderagsdale** [comment]
Team will add details needed in the requirements doc by EOD Tuesday.

**Comment by eileen-coforma** [comment]
Restarted a CAIA request: #67354
Started an experimental design ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2767

We'll meet with the forms team to discuss the work they're doing that can overlap with our confirmation page changes.

**Comment by davidakennedy** [comment]
I covered most of this in the feature requirement doc, but also wanted to drop my full accessibility notes here for archive purpose, in case we needed them in the future for reference:

## Requirement

Requirement: While download link is loading, the user is shown a loading indicator (general or progress bar).

The loading indicator will inform the Veteran of whether or not the content is still loading.

## Recommendation

Use the loading indicator. Don't autofocus it. Suggested visible label and message: Generating your PDF. This may take a minute.

Why: This is how we currently handle similar loading scenarios across VA.gov. It meets WCAG criteria and is fairly simple.

- [Related WCAG compliance information](https://www.w3.org/WAI/WCAG22/quickref/?showtechniques=413#status-messages).

## Other options explored

- Moving the HTML of the submitted form higher than the PDF link: Eileen and I talked about this, but it goes against what we heard Veterans want during research.
- Managing focus when the link populates: This wouldn't work well because we'd have to shift focus without the Veteran initiating it. It would be disruptive since we don't know where on the page the user would be at the time the link loads in.
- Including an ARIA live region with the [loading indicator](https://design.va.gov/components/loading-indicator): The ARIA live region would announce when the PDF link becomes available. The loading indicator doesn't do that, but still lets Veterans know when something doesn't load. The announcement wouldn't help in this case because: The Veteran hasn't initiated the loading. They also wouldn't be able to take action from a live region to access the link. They would need to explore the page.

**Comment by saderagsdale** [comment]
@eileen-coforma will meet with forms team next tuesday to determine if anything should be incorporated from their work.

**Comment by saderagsdale** [comment]
> Get approval for content

@eileen-coforma to keep this one from spinning, we can ask Julie to nudge BVA.

**Comment by saderagsdale** [comment]
Checked in with Michael on my two items. Will work on the outcomes and indicators today.

**Comment by eileen-coforma** [comment]
@saderagsdale I still need to send the content to BVA. I was under the impression that we should get the edits back from CAIA before getting a final lookover by BVA. Should it be the other way around?

**Comment by saderagsdale** [comment]
@eileen-coforma Thanks for clarifying! Nope that sounds good.

**Comment by eileen-coforma** [comment]
Attended DSC meeting. Doesn't sound like any blockers, seems like they'll be adapting our design. No official approval noted yet.

**Comment by Mottie** [comment]
Front end work is still in progress:
- Pull request with code changes awaiting review
- Still need to write unit tests for the above code changes.

**Comment by eileen-coforma** [comment]
Met with Katherine to discuss content edits and give extra context about research and feature. She says she'll have it to A (for final edits) by EOD today.

**Comment by eileen-coforma** [comment]
CAIA is done with review. Sending it to Amy Lucyx to ask for content review.

**Comment by eileen-coforma** [comment]
John sent some feedback over, but mentioned that there's more that would be ready EOD tomorrow.

**Comment by eileen-coforma** [comment]
[Board Appeal - Downlodable copy of submission confirmation content - board feedback 5.23.24.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15470563/Board.Appeal.-.Downlodable.copy.of.submission.confirmation.content.-.board.feedback.5.23.24.docx)

Initial feedback (without Angie's latest feedback)

**Comment by eileen-coforma** [comment]
If necessary, scheduled a meeting with BVA to review the feedback that was given. Include John G. Angela D. and Jeff G. in that meeting. Also include Julie S. and Sade for support.

**Comment by skylerschain** [comment]
@jstrothman and I met to discuss the comments and [made a new iteration of the mocks](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1347-10608&t=i5khCnAttU8DKA4N-4) with new content. There is still one outstanding question about how to frame the time estimates for how long each type of appeal will take.

**Comment by eileen-coforma** [comment]
Received feedback on BVA to use docketing letters as basis for 'what to expect next' section. Remove timeline estimation.

**Comment by eileen-coforma** [comment]
Added BVA's feedback to mock. This work is done, pending LH endpoint for ENG work to continue.
