### ISSUE TITLE
DR | Q3 Roadmap Sequencing

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#80470]
## Value Statement
**_As a_**product team
**_We want to_** have the next 3-6 months of opportunities prioritized based on Veteran value relative to OCTO and business outcomes
**_So that_** We know where to focus our design and development efforts. 

---

## Definition of Ready 
- [x] Secondary prioritization completed
- [x] Date scheduled
- [x] Stakeholders and attendees added
- [x] Materials prepared

## Definition of Done
- [x] Opportunities sequenced
- [ ] Outcomes and success measures defined
- [ ] Data analysis setup on DataDog/Domo/ VBA business dashboard
