### ISSUE TITLE
Troubleshooting issues w/TIC or Platform 

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#80474]
## Description 
On 03/21/24 there was a major incident that increased latency significantly and ultimately impacted the ability for the revproxy to work appropriately for vets-api and lighthouse api. This issue had disabled the ability for Veterans to login to va.gov, access many benefit forms, search for VA locations, and more. This issue mimic issues with the TIC and it is not always apparent where the root issue is stemming from which delays resolution.

In this incident, Kyle Matheny from the Platform Infrastructure team had instructed users in the original incident thread on how to very quickly and simply troubleshoot if the root. of the issue is the TIC or not. 

I will give a brief overview of how these issues appear in Datadog for new team members, how to determine if the root is from the TIC, and how to contact the appropriate team if it is related to the TIC. 

---

## Definition of Done
_What must be done to officially complete this task?_

One document regarding the errors seen in this incident and how to troubleshoot will be created. Team members will confirm that they understand how to triage. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Document what an issue like the above incident looks like for Tier 1 ICs to use while on rotation
- [x] Document Tier 1 of how to determine root cause (TIC/No TIC)
- [ ] Schedule meeting re: Incident Commander tasks and common problems seen
- [x] Walk through with team 
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@lindsay-insco Hey! I moved this to current sprint. Thanks!

**Comment by lindsay-insco** [comment]
Complete. Shared with team
