### ISSUE TITLE
DORA - Have metrics output daily to Confluence

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#80479]
## Description
Need to have DORA metrics output daily to confluence, updating the historical data that's there.

## Tasks
- [ ] Output daily numbers to Confluence
- [x] Update the Confluence page

## Acceptance Criteria
- [ ] Accurate numbers are being output to Confluence once per day

**Comment by JoeTice** [comment]
This ticket has been closed at this effort has been deprioritized
