### ISSUE TITLE
DORA - Create user guide

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#80480]
## Description
The intent for a DORA user guide was twofold:
- We need to have a basic user guide to help people understand what they see on the Confluence page for DORA metrics
- We need to have a guide that will allow someone to come in and gather updated numbers on a regular basis.

## Tasks
- [ ] Draft user guide documentation
- [ ] Have teammates review and provide input
- [ ] Finalize user guide

## Acceptance Criteria
- [ ] A user guide is available on Confluence

**Comment by JoeTice** [comment]
SPRINT 52 STATUS: IN PROGRESS - This task is in progress, but additional time was spent on ticket 81594. Additionally Ben was sick for a few days, so this task will rollover into Sprint 53. Task will be completed in Sprint 53.

**Comment by JoeTice** [comment]
SPRINT 53/1 STATUS: DEPRIORITIZED - This task has not been completed, and priorities have shifted, we are deprioritizing this task and will resume it in the future

**Comment by JoeTice** [comment]
SPRINT 53/1 STATUS: DEPRIORITIZED - This task has not been completed, and priorities have shifted, we are deprioritizing this task and will resume it in the future
