### ISSUE TITLE
Create Footer web-component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#80493]
## Description
As part of the VA Design System to USWDS v3, the DST needs to remove the dependency on Formation. The team has already built web components to replace the React components but there are still a few remaining React components that need to be replaced with a web component version. 

As part of this epic, we create a footer web-component

## Details
There are the areas of work that are to be done as part of this epic: 
- Build web components for footer
- Deprecate React component library [Plan for deprecation](https://vfs.atlassian.net/l/cp/86bgiY8p)
- Update Forms library with web-components [See discovery ticket for details](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1375)  

## Tasks
- [ ] Add or update footer component design in Figma
- [ ] Build web component for footer
- [ ] Have an accessibility review for footer web component
- [ ] Add guidance on design.va.gov for footer web component

## Acceptance Criteria
- [ ] Footer component design is in Figma
- [ ] Web component for footer is available for use
- [ ] Footer web component has gone through staging review
- [ ] There is guidance on design.va.gov for footer web component
