### ISSUE TITLE
Epic: Create header web-component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#80490]
## Description
As part of the VA Design System to USWDS v3, the DST needs to remove the dependency on Formation. The team has already built web components to replace the React components but there are still a few remaining React components that need to be replaced with a web component version. 

As part of this epic, we create a header web-component

## Details
There are the areas of work that are to be done as part of this epic: 
- Build web components for header
- Deprecate React component library [Plan for deprecation](https://vfs.atlassian.net/l/cp/86bgiY8p)
- Update Forms library with web-components [See discovery ticket for details](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1375)  

## Tasks
- [ ] Add or update header component design in Figma
- [ ] Build web component for header
- [ ] Have an accessibility review for header web component
- [ ] Add guidance on design.va.gov for header web component

## Acceptance Criteria
- [ ] Header component design is in Figma
- [ ] Web component for header is available for use
- [ ] Header web component has gone through staging review
- [ ] There is guidance on design.va.gov for header web component
