### ISSUE TITLE
Veteran Representative Experience - Executive Summary

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#80509]
## Issue Description
Consolidation of Veteran and caregiver interviews to encompass the representative experience focusing on three parts;
1. Motivation for getting a representative
2. Search process for getting a representative
3. Representative engagement

Executive summary should include:
* Summarized approach
* High level key insights
* Identified 'hot' topics
* How might we statements
* Actions and future actions on research

## Tasks
- [ ] Meet with stakeholders to identify sections to keep from journey report
- [ ] Meet with team to identify completed, in progress, and future feature ideas and updates based on research
- [ ] Update deck with edits
- [ ] Send to team for review
- [ ] Create ticket for revisions

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
https://docs.google.com/presentation/d/1rJ60E3KMFMb0VWprntmWofEdP1sT2urk29abHppl-U8/edit?usp=sharing

First draft sent to Lesley and Jenn and set up time to discuss

**Comment by oddball-lindsay** [comment]
Request from enablement to present at the upcoming Accredited Reps Crew sync for awareness.

But we'd still like input from Jen/Lesley on items to prioritize for the top portion of the deck (if anything).  This deck will be for Jen to share-out to other teams/departments for quick context related to our work.

**Comment by oddball-lindsay** [comment]
Heading towards an ARM+ARF collaboration.

**Comment by jfinnerty13** [comment]
Meeting with ARF Friday on next steps
