### ISSUE TITLE
[FE] My VA Form Status: Frontend technical discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#80504]
## Background
We have officially kicked on engagement with the Veteran Facing Forms team on the initiative to elevate form status on My VA and on the confirmation page. We are going through collab cycle in partnership with the Veteran Facing Forms team and design intent is scheduled for Thursday, 4/18 at 1:30 pm ET. We need to do some technical discovery/strategic planning around implementation.

This ticket is to write up the FE implications and options of this work.

## Tasks
- [ ] Review documentation below (outlines, proposed designs, LH documentation, etc.)
- [ ] Connect with VFF team devs on connecting to LH to pull form status
- [ ] Reach out to Lighthouse with additional questions as needed
- [ ] Create write up in GH to outline technical approach

## Acceptance Criteria
- [x] We have proposed technical approach(es) for implementation 

## Resources
- [Veteran Facing Forms team outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Product%20Outline%20Confirmation.md)
- [Proposed designs (figma)](https://www.figma.com/file/GeBhUvcQAbbGYdmDIS7bRN/Confirmation-%26-Status?type=design&node-id=39-15291&mode=design&t=YGPLhyZ8XkJq0USk-0)
- [Outline on the DE project board (from Matt D)](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170)
- [Lighthouse API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- [My VA outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/benefit-application-drafts-forms-submission-status/README.md)
- [Collab Cycle Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80272)

**Comment by ajakabcin** [comment]
@allisonlu here's [space](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/benefit-application-drafts-forms-submission-status/technical-discovery.md) for the tech discovery!

**Comment by allisonlu** [comment]
---
### Currently on My VA - Benefit application drafts section 

- [Frontend documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md#my-va-benefit-application-drafts-frontend-documentation)
- [Backend documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/saved_applications/backend_documentation.md)

To determine if a user has any saved froms and which ones, we check [if the user profile has any `savedForms` in their Redux state](https://github.com/department-of-veterans-affairs/vets-website/blob/c9ce33748c7bdd99f3b196f7a248225c84f178cc/src/applications/personalization/dashboard/components/benefit-application-drafts/ApplicationsInProgress.jsx#L90-L94) 

where 

```
const selectProfile = state => selectUser(state)?.profile || {};

const selectUser = state => state.user;
```

---

### Changes and effort needed
#### Feature flag - 2 points total
  - open PR on `vets-api`
  - set up feature flag on `vets-website`

#### ApplicationInProgress component (card) - 11 points total
- add a [Tag web component](https://design.va.gov/storybook/?path=/docs/components-tag--default-story) for each of the statuses: Pending, Received, Error. Default tag content will say "Draft".
  - pull in web component and tweak to match design - 2 pts
  - determine how to pull in statuses from API response - 3 pts

(more in-depth info about statuses on [Benefit intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current))

For the following tasks, we need to determine if it is feasible to grab the dates and next steps from the API response.
1. **Pending** - 3 pts
   - add "Submtitted on" date - when user submitted it
   - add "Received on" date - when application arrives at Central mail/VBMS?
   - add "Next step" 
   - add additional info web component with a process list
     - steps may be different for all forms and each status
2. **Received**
- no mockup available right now
3. **Error** - 3 pts
   - create error alert if status === `Error`, which means "form submissions did not make it"
   - may or may not make this dismissible 

#### BenefitApplicationDrafts component (section) - 2 points total
- change section heading to "Benefit applications"
- change layout to two-columns (one column for card, one column for secondary CTA links)
- secondary CTA link for resources and support link w definitions of statuses
- maybe: organize cards by statuses under their own headings. ([Figma conversation](https://www.figma.com/file/GeBhUvcQAbbGYdmDIS7bRN?type=design&node-id=149-2062&mode=design#775409022))
- may need to update [BE documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/saved_applications/backend_documentation.md) because in addition to health care applicatiosn, we also include disability and non-disability forms

**Comment by ajakabcin** [comment]
fantastic @allisonlu - I'm going to drop this into the technical documentation space I made. Thank you!
