### ISSUE TITLE
2024 Q2 Monitor PACT Act Spring 2024 Submissions

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80513]
## Issue Description
This ticket is to monitor the DataDog dashboard created by the Platform Product team [here](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms?fromUser=false&index=%2A&refresh_mode=sliding&view=spans&from_ts=1710421711677&to_ts=1711026511677&live=true) for T1 and T2 folk to check daily, beginning on 3/21, and ensure that there is no unusual activity or issues. 

---
## Tasks
- [x] Daily monitoring by Platform Product or T1/T2 Support teams for unusual activity
- [x] Action by the appropriate team in the event of unusual or blocked activity 
- [x] Reroute issues to appropriate team when they are found, if they can not be mitigated by Platform Product team
- [x] Follow up with assigned team to ensure that the fix has been implemented 
- [x] PLATFORM PRODUCT TEAM MAJOR RESPONSIBILITY IS TO MONITOR AND MAKE OTHER TEAMS AWARE

## OKRs
O1. Our digital experiences are the best way to access VA health care and benefits
OKR 4 No transactions accepted by our products have a fatal error. 

## Acceptance Criteria
- [x] Any unusual activity will be flagged by Platform Product or T1/T2 Support teams and rerouted to the appropriate team for their immediate attention as soon as PACT Act submissions begin to roll in.

**Comment by alyssagallion** [comment]
@jennb33 Do you need anything from Platform Support on this? Thanks!

**Comment by jennb33** [comment]
@alyssagallion are there any reports on responses or spikes after the lastest PACT Act release that are of note for the team? I don't think we need any additional support at this time, and I'm still getting comfortable with the PACT Act and what was to be expected. Any helpful info you have, I'd love to see! Many thanks -

**Comment by alyssagallion** [comment]
@lindsay-insco @bdech Have you noticed anything on the above?
