### ISSUE TITLE
IA Tracker: Update H1 for GI Bill® School Feedback Tool

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#80512]
### Description
We are updating the H1 for this tool and will need to work with the product team. This work is part of the 2023 IA audit.

Current H1 | New H1
--- | ---
GI Bill® School Feedback Tool | Submit GI Bill® School Feedback

### Team

- Team Name:
- Designer:
- Product Manager:
- Slack (_optional_): 

### Tasklist
- [ ] Connect with the product team
- [ ] Create backlog ticket for team

## Acceptance Criteria
- [ ] H1 is up to date

**Comment by jennymayoco** [comment]
Moving to blocked until there's a product team that's working on this tool

**Comment by kristinoletmuskat** [comment]
@strelichl we still need this ticket but don't have a product team to do it. So do you think blocked makes sense? Or icebox?

**Comment by artsymartha68** [comment]
I found a few other accessibility issues on this page. 

1. There is a skipped heading level. "Prepare" is currently a H5, it should be H3. 
![Image](https://github.com/user-attachments/assets/6dc513a6-a874-4eac-970c-a1c5aacd3ff3)
2. While you're on this page, please remove the table for all these complaint types. Tables should only be used for data, not text layout like this. A simple list should suffice.
3. Reformat the small caps sentence, "TO FILL OUT THIS FORM YOU NEED TO". This is not standard per the VA Design System. No need to yell, plain text formatting should suffice, maybe bold if needed. ![Image](https://github.com/user-attachments/assets/c8dec67d-04eb-4fdd-8a7e-213b2e514b43)
