### ISSUE TITLE
Update documentation for `disable_ddl_transaction!`

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#80522]
## Issue Description
`disable_ddl_transaction!` should be used sparingly–only when necessary. Let's mention this on the [vets-api database migrations page](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-Indexes) of the platform website. If `disable_ddl_transaction!` is used, but the migration fails, the migration will be partially complete, leaving things in a failed state. We'd like to avoid that if possible!

Docs: https://api.rubyonrails.org/v5.2/classes/ActiveRecord/Migration.html#method-c-disable_ddl_transaction-21

ChatGPT notes: When you run a migration, Rails begins by opening a database transaction. It then executes all the commands in the migration file. If everything executes successfully, Rails commits the transaction, making all the changes permanent in the database. However, if any command in the migration fails, Rails will roll back the transaction, undoing any changes made up to that point in the migration. This behavior ensures that your database schema remains consistent and doesn't end up in a partially-updated state. However, not all database operations can be run inside a transaction. Some database commands, particularly certain types of DDL (Data Definition Language) operations like creating or dropping indexes on very large tables, can't be executed inside a transaction because they lock the table and prevent other operations from proceeding. In these cases, you need to use `disable_ddl_transaction!` in your migration to tell Rails not to wrap this migration in a transaction. This allows each command in the migration to be committed to the database independently.

## Tasks
- [x] Update [the **Indexes** section](https://vfs.atlassian.net/wiki/spaces/pilot/pages/689832034/vets-api+database+migrations#Indexes) in Confluence to make it clear when to use and when not to use `disable_ddl_transaction!`.
- [x] Have a teammate review the changes. 

## Success Metrics
VFS teams can clearly understand when to use `disable_ddl_transaction!` in their migrations. 

## Acceptance Criteria
- [ ] Confluence page is updated and reviewed. 
- [ ] Any changes requested by the content team have been made.
- [ ] [Platform website page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/689832034/vets-api+database+migrations) is published.
---

## Validation
1. Go here: https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-Indexes
2. Compare the changes made in Confluence: https://vfs.atlassian.net/wiki/spaces/pilot/pages/689832034/vets-api+database+migrations to the changes on the platform website linked in step 1.
3. This work is validated if these confluence changes are deployed to platform website 🎉

**Comment by rmtolmach** [comment]
Edits have been made. See [the diff here](https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=689832034&selectedPageVersions=16&selectedPageVersions=17). Next: get page reviewed.

**Comment by rmtolmach** [comment]
✅ reviewed by Lindsey.
I or someone else can validate after the platform website deploy today.
