### ISSUE TITLE
FE | General Maint | Errant words in a Profile URL should load Profile Hub

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#80536]
## Background 
if someone adds a bunch of bogus stuff at the end of a URL we should expect the page to default to the profile hub.

testing resulted in a blank page.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/a010bce4-9ae1-4609-8087-18227d33f51d)

I loaded https://staging.va.gov/profile/direct-deposit 
Then typed in blah blah and hits enter resulting in: https://staging.va.gov/profile/direct-deposit%20blah%20blah

[Slack Message](https://dsva.slack.com/archives/C053JC66YHF/p1712753059426399?thread_ts=1712753059.426399&cid=C053JC66YHF)

## Tasks 

- [x] Adjust ProfileBreadcrumb component to gracefully fallback to use the Profiel Hub route when a url is requested that doesn't match the valid profile routes.
- [x] Add unit test to cover this case
- [x] if a small fix lets implement, if we need a new ticket then lets create a new ticket and adjust the AC

## Acceptance Criteria 
- [ ] the profile hub is now loading when errant words are inserted into the url (eg. https://staging.va.gov/profile/direct-deposit%20blah%20blah)

**Comment by mtcA6** [comment]
just tested this w/user 161. Navigated to direct deposit w/in the profile and typed in blah blah blah at the tail end of the url and it redirected to the hub.
