### ISSUE TITLE
Staging Review Find VA Forms Search MVP

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#8054]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline ([linked here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign))
- Link to [release plan - completed and linked here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/soft-launch/release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- **Access information for the tool or feature in staging _do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
  - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/find-forms-creds
- Link to your product test cases/test plan in TestRail with test execution logs ([linked here](https://dsvavsp.testrail.io/index.php?/plans/view/105))
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
- Link to your accessibility test cases:
  - **TestRail** [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/plans/view/105) **OR**
  - **Markdown** [Github accessibility test cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/accessibility-test-cases-template.md)
- List of known issues (with links to tickets when applicable)

## Meeting attendees from **requesting team**
- Product Manager (required): Steph Orkand
- DEPO product lead (required): Jen Lee
- Anyone else from your team who significantly contributed to the artifacts provided (required): Mickin Sahni

## Scheduling
Preferred dates or times: 4/21/2020

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by meganhkelley** [comment]
Scheduled 4/22 to allow 48 hour review turnaround

**Comment by meganhkelley** [comment]
Credentials for review: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/public-websites/find-forms-creds 

@stephorkandatx (moving convo from Slack) — can you please explain for reviewers why you've provided credentials in both staging and prod, and which folks should use for review?

**Comment by stephorkandatx** [comment]
@meganhkelley I removed the creds for staging, and left the creds for production per our discussion. The credentials for production are good to use. Thanks

**Comment by mnorthuis** [comment]
@stephorkandatx has the team discussed the sorting order of the results?  Not sure if there is a solution, but a search for "10-10" results in the most important/relevant result to be shown half way down page 2 of the results behind many forms that are 10-#####.

This is not a blocker, just a question.  No other IA feedback.

**Comment by stephorkandatx** [comment]
@ncksllvn do we have control over the sort order of the results or do we show in the order returned from the API?

**Comment by ncksllvn** [comment]
We do have control over the sort order, but there isn't a "weight" or indicator of how popular a form is. We can sort by form number or form title, ascending or descending.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - per your comment above: 
>We do have control over the sort order, but there isn't a "weight" or indicator of how popular a form is. We can sort by form number or form title, ascending or descending.

Great idea. I didn't know we had control over that! I think that would be a nice enhancement to add, now that we have fully redirected the mvp search experience. 

I'll close this ticket, since we actually completed this a while ago, and  create another backlog ticket for the feature enhancement.
