### ISSUE TITLE
FDG v1.1 release

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#80541]
## Purpose
Items for 1.1 release of FDG

## Tasks
- [x] Identify current list of features that can be moved to v1.1 release
- [x] research and execute those features
- [ ] launch update
- [ ] communicate update/changes

## Acceptance Criteria
- [ ] v1.1 is released
- [ ] v1.1 is communicated
