### ISSUE TITLE
Update va-input (VAInput) from V3 to V1 

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#80560]
## Value Statement
**_As a_** user using at CST
**_I want to_** be able to upload multiple files at a time when on the files tab
**_So that_** I dont have to upload files multiple times.

---
## Background Context

The VaInput component is currently being worked on and is not ready to go live since we cant upload multiple files with the V3 version of the component. We need to roll back to the V1 version.

Created [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79156) ticket for the work and will plan to reactive the V3 version once the listed platform tickets are done.

## Engineering 
Will need to update AddFilesFormOld and AddFilesForm

## Tasks
- [ ] AddFilesFormOld
- [ ] AddFilesForm

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] va-file input for CST uses V1 version and not V3 version of the component

**Comment by pmclaren19** [comment]
Tested/verified in Staging and looks good!
