### ISSUE TITLE
Refactor to Common Schemas (Part 2 of 2)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8056]
## Goal
We use one small generic schema file and import other items as needed, but other forms use a massive schema file and we need to convert our schema to look like that.

## Considerations
- Refactoring to use the common definition for full name means we need to hide the suffix on workflows where it isn't needed. This includes: reportStepchildNotInHousehold, addChild/additional-information. 
- Update `uiSchema` for address component to reflect changes to enums for countries and states.
- Update `reportDivorce` workflow to support new enum value for `explanationOfAnnullmentOrVoid`.
- Update all property names in `vets-website` to reflect new, generic property names in `vets-json-schema`.
## Tasks
- [ ] Change schema imports in form page files (15-20 files) to reference schema file in vets-json-schema repo
- [ ] make sure all unit tests still pass and make adjustments as needed

## Acceptance Criteria
- [ ] A PR has been merged that commits these changes
