### ISSUE TITLE
Implement Flipper Component for 686 (Part 1 of 2)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8057]
## Goal 
Part of the launch process involves gating a piece of the landing page to either allow traffic to pass through to "View Dependents" where Veterans can continue on and use the new form, or go back to the legacy EBN 686 form application.

A second Flipper component will remove the CTA for direct, authenticated access (in blue) until after we are ready for that.  [Noted in another ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8068)

## Considerations
- The front end HTML code will be shared with PubWeb for when the landing page gets built out.

## Tasks
- [x] Build some HTML code to be embedded into the landing page
- [x] Adjust Flipper to allow for traffic to arrive at the different designated destinations.

## Acceptance Criteria
- [ ] Flipper has been configured and tested for the 686 launch
