### ISSUE TITLE
Implement recommendations to flatten level 4+ child pages in benefit hubs, in the nav

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8060]
## Goal
* Reduce L4+ content down to max of 3 levels
* Get users to any benefits hubs content in a couple clicks/taps

**Repo:**
(contains the Audit completed in #5236)
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/header-footer-and-navigation/page-nav

**Pittsburgh side nav research findings:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/left-nav/research-findings.md

## Objectives or Key Results this is meant to further

- Objective 3: Deliver a usable and accessible experience
KEY RESULT: By mm/dd/yr (launch of this work), Veterans can access benefit hubs content within 4 clicks or less from the nav
---
## Tasks
- [x] Implement the recommended changes, reviewed and confirmed as part of #8049 
-- Changes will span the list of Hubs below (that contain L4+ pages)

## Acceptance Criteria
- [x] Recommended changes from the page audit are implemented
- [x] Benefits hubs content is simplified to max 3 levels

List of Hubs containing  Level 4 and 4+ child pages:
- [x] Health care
- [x] Disability
- [x] Education
- [x] Pension
- [x] Careers
- [x] Burials
- [x] Records
- [x] Housing
- [x] Life insurance
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
Work for this element was completed in separate ticket via Public Websites team.  Closing out in support.
