### ISSUE TITLE
Implement left nav design updates, for benefit hubs

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8062]
## User Story or Problem Statement
As a veteran, I need the navigation elements to assist me in navigating and locating content within the benefit Hubs so I can find what I am looking for more easily.

## Goal
Incorporate the new nav design into benefit hubs (including hover, active, and open left nav element states?) to minimize clicks and confusion for users

## Objectives or Key Results this is meant to further
- Objective 3: Deliver a usable and accessible experience
KEY RESULT: By mm/dd/yr (launch of this work), Veterans can access benefit hubs content within 4 clicks or less from the left nav
---
## Tasks
- [ ] Implement left nav consistent with the updated design for VAMC Pittsburgh #7212 

## Acceptance Criteria
- [ ] Update with relevant AC from #7212
- [ ] ? Does this need to be implemented hub by hub? If so, separate into multiple tickets or keep together? 
- [ ] Content of all benefit hubs is navigable, accessible

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by MickinSahni** [comment]
Blocked by L4 flattening work

**Comment by FranECross** [comment]
@MickinSahni @stephorkandatx Is this old ticket still valid, or may I close it? Thanks!
