### ISSUE TITLE
Datadog Incident Management Documentation

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#80637]
## Description 
To better communicate during major incidents Datadog has an incident management tool that can more rapidly collect screenshots and timelines and documentation on how to best utilize it should be created. 

---

## Definition of Done
Confluence documentation on how to use Datadog's incident management tool in regards to the current Platform incident toolkit will be created and demonstrated to the team

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Create documentation
- [ ] Demonstrate to team
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@lindsay-insco Hey! Is this a duplicate of the ticket we put in the upcoming sprint or a separate task?

**Comment by lindsay-insco** [comment]
Duplicate
