### ISSUE TITLE
Move mvp of FDG to Platform Docs - (soft launch)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#80630]
## Purpose
Let's put the space into Platform Docs and view how things render once they cross over.

## Tasks
- [x] Identify pages that should be involved in transfer (add to checklist below)
    - [x] Initial landing page
    - [x] Phase pages
    - [x] Forms Library page
    - [x] References page
- [x] clear any comments/temporary notes from pages
- [x] verify that links work as PCT guidance recommends
- [x] verify that [Last Update entry](https://vfs.atlassian.net/wiki/spaces/AP/pages/3065708550/Date+Stamp+Adding+a+New+Step+to+Creating+and+Updating+Pages+on+Platform+Website) is accurate on each page
- [x] Move/copy pages to: Develop Docs, last position on left rail (Note: waiting on high rez images from Nicole)
- [x] Use Scroll Viewport to review each page for launch blocking issues
- [x] Evaluate their presence on Platform Docs the next day

## Acceptance Criteria
- [x] Pages are live in Developer Docs space, accessed as the last item on the left rail

**Comment by twoangstroms** [comment]
Finding some confusing messages when testing pages using Scroll Content Quality. Some of the content looks formatted properly and recommended content is the same as existing, and external links are valid (resolve to live pages) but baffle Scroll Content Quality. Will connect with PCT to hash out. 

<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODMzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc3d81807347989e44f0437744a6e395f41295d8/Screenshot%202024-05-20%20at%204.04.28%E2%80%AFPM.png" alt="Screenshot 2024-05-20 at 4.04.28 PM.png" />

**Comment by twoangstroms** [comment]
Closed late by user error
