### ISSUE TITLE
[CST] Increase code coverage to 85% for Claim Status Tool service

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#80631]
## Background Context
After the Staging Review for the Claim Status Tool V2 changes we were told that we need to increase test coverage for the entire service and not just the files that we touched. Our current test coverage is the following for the current CST service
<img width="1626" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3hVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--927a8bde4285269bb10359b0706cb5aa8c1fd305/Screenshot%202024-04-11%20at%2012.17.45%E2%80%AFPM.png" alt="Screenshot 2024-04-11 at 12.17.45 PM.png" />

We need to increase this coverage for each of these 4 sections (note it changes every time we add or make updated to a file/test).

Running yarn `test:coverage-app claims-status` shows the test coverage

## Outcome, Success Measure, KPI(S), and Tracking Link

Test Coverage is currently 
- Statements (80.35%)
- Branches (76.8%)
- Functions (81.21%)
- Lines (80.2%)

## Tasks
Test coverage is 85% or higher for the following areas

- [ ] Statements (80.35%)
- [ ] Branches (76.8%)
- [ ] Functions (81.21%)
- [ ] Lines (80.2%)

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Test coverage is 85% or higher for the CST
