### ISSUE TITLE
PgHero cleanup

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#80648]
## Issue Description
PgHero (http://pghero-prod.vfs.va.gov/) is reporting some slow queries and, occasionally a long-running query.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/54c65bb9-cb17-4c5b-8e08-6c9252e41e9b)

Some of the slowest and/or most frequently called queries should be addressed. We will want to report significant findings to the teams that own the related code. 

## Tasks
- [x] investigate the yellow alerts in PgHero
- [ ] Fix issues or pass along findings to relevant teams
    - [ ] Link conversations, tickets, or PRs as comments in this issue.

## Success Metrics
The info in PgHero has been analyzed and acted upon.

## Acceptance Criteria
- [ ] Teams have been notified
- [ ] links to slack threads or tickets created from this are linked in the comments of this issue
- [ ] PG Lockout is created for extended run queries
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by RachalCassity** [comment]
[Uploading... Screenshot 2024-05-02 at 10.57.46 AM.png]

**Comment by rmtolmach** [comment]
## Invalid Indexes
> These indexes exist, but can’t be used. You should recreate them.
1. `index_flipper_features_on_key` added in https://github.com/department-of-veterans-affairs/vets-api/pull/15656
2. `index_flipper_gates_on_feature_key_and_key_and_value` also added in https://github.com/department-of-veterans-affairs/vets-api/pull/15656
3. `index_ivc_champva_forms_on_form_uuid` added in https://github.com/department-of-veterans-affairs/vets-api/pull/16721

**Comment by rmtolmach** [comment]
## Duplicate Indexes
> These indexes exist, but aren’t needed. Remove them for faster writes.

1. On accreditations               
`index_accreditations_on_accredited_individual_id (accredited_individual_id)`
is covered by               `index_accreditations_on_indi_and_org_ids (accredited_individual_id, accredited_organization_id)`

2. On async_transactions               
`index_async_transactions_on_transaction_id (transaction_id)`
is covered by               `index_async_transactions_on_transaction_id_and_source (transaction_id, source)`

3. On va_notify_in_progress_reminders_sent               `index_va_notify_in_progress_reminders_sent_on_user_account_id (user_account_id)`
is covered by  `index_in_progress_reminders_sent_user_account_form_id (user_account_id, form_id)`

These are all composite indexes. Since the composite index can serve the same queries as the single-column index, the single-column index is redundant and can be dropped. First, we can check some usage stats to see how often the individual index is used. If it's low, or unused, we can drop it.

**Comment by rmtolmach** [comment]
## Suggested Indexes
> Add indexes to speed up queries. 

1. CREATE INDEX CONCURRENTLY ON in_progress_forms (form_id, created_at)
2. CREATE INDEX CONCURRENTLY ON saved_claims (type, id)

We could generate a new migration for these two (or have the owning VFS team do it). Based on the stats in PgHero, we wouldn't save _that_ much time, but maybe it's still worth it?

**Comment by rmtolmach** [comment]
## Slow Queries
> Slow queries take 20 ms or more on average and have been called at least 100 times.

There are 8 of these currently. The biggest offender is a call to the `vba_documents_upload_submissions` table which takes an average of 3 seconds!

**Comment by rmtolmach** [comment]
## High Number of Connections
> 1124 connections
> [Use connection pooling](https://www.craigkerstiens.com/2014/05/22/postgres-and-connection-pooling/) for better performance. [PgBouncer](https://wiki.postgresql.org/wiki/PgBouncer) is a solid option.

Recently, we went from 6 workers and 3 threads per worker to 6 workers and 8 threads per worker (so 48 available per pod). This could have been a cause for the high number of connections, but based on the fact that this number is similar to the number pasted in the screenshot of the description, I'm guessing the change had no impact and this is just an issue we've had for a long time.

❓ How many free database connections do we have?

**Comment by rmtolmach** [comment]
## Long Running Queries
- it should be 5 minutes, but it's 21 days. - Update the statement_timeout in terraform. Reach out to Kshitiz and Chris to make sure they haven't done this already.
- Some teams run queries in EC2 instance and they stay open. Specifically, forms teams.

**Comment by rmtolmach** [comment]
**End of week update:**
- While working on the **Invalid Indexes**, there were some duplicate key errors during the migration. [Slack thread](https://adhoc.slack.com/archives/C045LCF8WU8/p1719594458627849). This is still in-flight. 
- See the comments above for the items left to do. I can do them when I'm back if they're not completed this sprint.

**Comment by jennb33** [comment]
This ticket has been duped for Sprint 5 as [87373](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87373), at 5 story points, in case the work is not completed in Sprint 4.

**Comment by rjohnson2011** [comment]
Merged this PR which resolves high number of connections error threshold issue Rebecca noted above -> https://github.com/department-of-veterans-affairs/devops/pull/14501

**Comment by jennb33** [comment]
Closing this ticket for Sprint 4, any additional work can be completed in Sprint 5, when @rmtolmach is back in office. TY @rjohnson2011 !

**Comment by rjohnson2011** [comment]
Merged and closed this PR which is bringing down the slow query by .8ms ->https://github.com/department-of-veterans-affairs/vets-api/pull/17377

Logs/Details in the PR
