### ISSUE TITLE
[CDP] VBA- Expand "Pay online" component and add file and payee number

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#80653]
## Description

**Given:** A veteran wants to see their **File Number** and **Payee Number** when being directed to pay.va.gov easily. Instructions for paying online should not be hidden. 
**When:** This is true when the **File Number** and **Payee Number** is attached to the user and not to a singular debt.
**Then:** A veteran should be able to see their **File Number** and **Payee Number** on the overpayment summary page and not just the overpayment detail page.

<details>
  <summary><strong>Current Overpayment Summary page:</strong></summary>
  <img width="751" alt="staging va gov_manage-va-debt_summary_debt-balances" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/9d276514-e7ba-4472-8ed6-ec0718497ac8">
</details>

<details>
  <summary><strong>Current Overpayment Detail page:</strong></summary>
  <img width="750" alt="staging va gov_manage-va-debt_summary_debt-detail" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/e4edf8b3-ce88-4c16-9636-87fc2b01bb5b">
</details>

## Tasks
- [x] Expand the "Pay online" accordion
- [x] Add the **File Number** and **Payee Number** to all instances of "Pay online" component
- [x] Understand what information should be constant on the **Pay Online** (File Number, Payee Number, Person Entitled, Deduction Code)

## Acceptance criteria

- [x] Make updates where "Pay online" section exists on VBA side of Debt Portal
- [ ] Make small pull request for these updates once PO signs off on them

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@denisecoveyduc @HeatherRienks @mgleo @Tom-Davis @charlottecesana, I just created the VBA version of this ticket and kept it on this sprint.

**Comment by mgleo** [comment]
@josephrlee 

> *File Number:
> *Payee Number:
> *Person Entitled:
> *Deduction Code:

Wanted to flag that VBA needs all four numbers in order to pay on [pay.va.gov](https://www.pay.va.gov/index.cfm?action=step1).
Adding only two of the required numbers on the summary page will cause confusion. Maybe there can be a note to view the details page or their statement to access the four account numbers needed?

**Comment by HeatherRienks** [comment]
Keeping VHA ticket in the Backlog as our MVP is focused on VBA work

**Comment by josephrlee** [comment]
Marking this as closed as it will be handled in 1.5 Payment History updates that are being made to the site! Tickets #86971 and #86969 are the tickets that will take care of this work. 

cc: @HeatherRienks @Tom-Davis @denisecoveyduc @mgleo @charlottecesana
