### ISSUE TITLE
Recreate rep and org tables (and do some cleanup)

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#80656]
## Background
The migration that had all of our new rep/org tables failed due to a lock issue in production. We had to rollback that PR and create a few migrations to clean up the tables that were created.

## Tasks
- [ ] Rollback the PR that had the migration
- [ ] Create clean-up migrations
- [ ] Create new migrations

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
Convo about migration failure in prod - https://dsva.slack.com/archives/C0460N83Y9G/p1712773802175839

**Comment by holdenhinkle** [comment]
Revert PR - https://github.com/department-of-veterans-affairs/vets-api/pull/16285

**Comment by holdenhinkle** [comment]
@jvcAdHoc will get this PRs merged, starting on Monday.

**Comment by oddball-lindsay** [comment]
Need platform's approval on the PRs above and will need to sequence deploys.  Create accredited_individuals table #16295 PR should be ready to go, will ping the team.

**Comment by oddball-lindsay** [comment]
Checking later today to confirm the table does indeed exist
