### ISSUE TITLE
[Project] Research GH Projects for sprint management

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#80667]
## Value Statement
**_As a_** Team Contributor
**_I want to_** easily manage our work daily
**_So that_** they can focus on adding value

---
## Outcome, Success Measure, KPI(S), and Tracking Link
- Example project with example views to be evaluated by the team

## Design
- Add here

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Create an individual ticket to represent each sprint, to be shared with stakeholders
- [ ] Create a GH Project with various views to be evaluated

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Individual ticket to represent each sprint_
- [ ] _GH Project with various views_

**Comment by shaunburdick** [comment]
Sprint Test Ticket: #80417

**Comment by jacobworrell** [comment]
@shaunburdick are we able to close this ticket?

**Comment by shaunburdick** [comment]
Yep!
