### ISSUE TITLE
Burial | Add FDC Information within Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80661]
## Issue Description
_Add additional FDC program information because the 530 online form design doesn't address Veterans "seen at non-VA facilities" and the required documents for a claim to be considered fully developed._

## Design
- [New supporting document page](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=1799%3A37607&mode=design&t=pdEfXIcLSHs7RnX1-1)
    - Itemized transportation receipt should only appear on this page IF the claimant has selected “Transportation costs of transporting the Veteran’s remains to the final resting place” as a benefit on step 4:
- New updated copy for the [Additional documents page](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=1796%3A32949&mode=design&t=pdEfXIcLSHs7RnX1-1)
- New alerts in the FDC screens
     - When ["Yes" is selected](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=1826%3A46060&mode=design&t=pdEfXIcLSHs7RnX1-1)
     - When ["No" is selected ](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=1826%3A50212&mode=design&t=pdEfXIcLSHs7RnX1-1)
     - Updates to the [Intro page](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?type=design&node-id=1859%3A61149&mode=design&t=pdEfXIcLSHs7RnX1-1)
- Updated Confirmation page
     - Add a new section "How can I submit supporting documents," added a date stamp to the success alert. 
     - [Authenticated](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=1826%3A40878&t=pjtCSDmyXWvXjasE-1)
     - [Unauthenticated](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=2489%3A27682&t=pjtCSDmyXWvXjasE-1)

---
## Tasks
- [x] Add a new Supporting document page with logic
- [ ] Add text explaining additional documents to the Additional Documents page
- [x] Add conditional alerts to the FDC page
- [x] Add content updates to the Intro page
- [x] Add content updates to the Confirmation page

## Acceptance Criteria
- [ ] Information on the FDC page aligns with FDC information in the pdf
---

**Comment by fiorella-io** [comment]
These are suggestions from @aliyahblackmore:

- Possibly move the FDC program page before the upload screens. _I need to check the Pension flow in production. When I created the [Pension flow last year](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?wid=31-1692377011261), the FDC page was after the upload screen._ 
- Add a new page with this question "Was the Veteran receiving care at a non-VA health facility at the time of their death?" after the "Where did the Veteran’s death happen?" page. 
     - If they answer "Yes" to this new question, they'll see an upload screen that asks them to submit the supporting documents.

cc/ @steele-lm we can discuss these changes with the team during standup

**Comment by fiorella-io** [comment]
I just had someone on the Pension team confirm that the FDC page appears after uploading documents, and I checked on staging too, so we don't need to move the FDC page from where it is now. @aliyahblackmore. I'll add this on Figma too.

**Comment by aliyahblackmore** [comment]
Hi @fiorella-io - clarifying my suggestion in Figma. This suggestion is based on the pension form flow in staging.

- My recommendation was not to move the FDC screen ahead of the upload screens. 

- The recommendation is to add screens earlier in the flow that ask the user to upload the supporting documents if the Veteran was seen at a non-VA facility. In the pension form, the FDC question comes after the user is asked to upload the supporting documents.

@aprocik1 FYSA

**Comment by fiorella-io** [comment]
I did notice this page that appears before the Upload screens that mentions "faster decision on your claim." which we can consider including. 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/88830824-b22a-41fe-8851-f317c2f56805)

**Comment by fiorella-io** [comment]
@aliyahblackmore Thank you for clarifying that! Is this ^^ the page you are referring to?

**Comment by aliyahblackmore** [comment]
@fiorella-io do you have some time to chat more next week after the design flow?

**Comment by fiorella-io** [comment]
Met with Aliyah and Julie S, to brainstorm the best way to add the "seen at non-VA facilities" evidence, VA Form 21-4142 and VA Form 21-4142a to the Burial form. 

**Proposed solution:** 
- Add a "Supporting documents" page before the "Death Certificate" upload page on Step 5 that will conditionally show all the types of evidence the claimant will need to upload on the following screens, which will include "seen at non-VA facilities" evidence information. This follows the Pension form flow. 
- Add additional information to the "Additional documents" page mentioning the "seen at non-VA facilities" evidence information
- Add a warning alert to the "Transportation allowance" page informing claimants that they would need to upload additional evidence on Step 5.

**Comment by aliyahblackmore** [comment]
**And tracking two other updates here (tracked via Slack and Figma as well):**

- Once Fiorella shares the design updates with me, I'll confirm with SMEs how they're defining "seen outside of VA." 
- The form intro page will need content about the additional documents for Veterans "seen" outside of VA.
- Since the FDC question will remain for their MVP relaunch, the confirmation screen (like the pension form) would need information on how to mail in supporting documents. I flagged that I recommend this happens before MVP launch, but that I'll leave it up to their team to determine if this is launch blocking or not.

**Comment by aliyahblackmore** [comment]
**Update here:** 

I just shared these design/content updates with SMEs for their accuracy review/approval. This is still in progress.

**Comment by aliyahblackmore** [comment]
**Update here:** 

We're still waiting for SME approval on these updates. This is still in progress. 

@steele-lm confirmed today (4/29 via Slack) that it's okay for these updates to go out post-100%.

I'll be OOO May 1-6. If there are any changes to this plan, please chat via Slack or tag @aprocik1.

**Comment by aliyahblackmore** [comment]
**Update here:** 

SMEs shared feedback on content around documents. I'm making some updates and I'll re-share with SMEs for their approval. This is still in progress.

**Comment by aliyahblackmore** [comment]
**Cross posting here from Figma:** 
- I made initial content adjustments (4/30) to the [updated FDC flow designs ](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=1799-37607&t=1DIsNZZBTmFmUFBG-0)that the product team decided to move forward with. I'm in the process of making additional adjustments based on new information from SMEs.
- On 5/6 and 5/7, SMEs shared via Teams that medical records or authorization for VA to retrieve medical information is only an optional document if the applicant is claiming a burial allowance for a service-connected death.
- Given this new information for SMEs, the form flow should be updated with conditional logic to decrease cognitive load and increase clarity. Currently, all users see information about medical records, but the information is only necessary for users who select "service-connected burial allowance." Because the product team previously decided to leave the flow as it is, the team should decide when and how they will update the flow based on the new SME information from this week.
  - **One suggestion** - if someone selects that they're claiming a burial allowance for a service-connected death, later in the flow the supporting documents are shown conditionally and they're shown an upload screen for the medical records/an authorization for release of records. On the confirmation screen, details about medical records are shown conditionally. The designers and product team should determine how to integrate some sort of conditional logic in to the form flow and determine when this can happen.
  - And because there aren't any questions about medical records on the PDF version of the form, the product team needs to confirm how any additional flow updates would impact the back end.
  
  
 cc @fiorella-io @steele-lm

**Comment by aliyahblackmore** [comment]
**Update:**

This is still in progress. I have to share recent updates with SMEs.

**Comment by aliyahblackmore** [comment]
**Update:**

This is still in progress. I have to share the most recent updates with SMEs. I put this on hold while addressing the death certificate adjustments this week.

**Comment by aliyahblackmore** [comment]
**Update here:**

This is still in progress. I shared the FDC/medical records content updates with SME today. I'll make any necessary adjustments here based on their feedback.

**Comment by aliyahblackmore** [comment]
Cross posting: 

SMEs gave the okay on a version of the medical records information. I'll track the changes in Figma next week. This isn't ready yet.

**Comment by aliyahblackmore** [comment]
**Cross posting:** 

I tracked the updates that the SMEs approved in Figma. I'll check in with the product team when I'm back on 7/8 about coordinating timing for when they'll turn these form updates on and when we'll publish the related VA.gov page updates.

**Comment by aliyahblackmore** [comment]
**Update here:** 

- I tracked updates to content on form[ intro page ](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=1859-61149&t=sCq2SSAASMCUsJPe-4)(with link to the static page with list of supporting docs), [new supporting docs summary screen](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=1799-37607&t=sCq2SSAASMCUsJPe-4) (similar to pension form), and [upload screen are tracked ](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=2345-9589&t=sCq2SSAASMCUsJPe-4)in Figma in alignment with the SME feedback/accuracy review/approval on 6/5 about the content related to claims for an allowance for service-connected deaths and (optionally) submitting medical records.

- The [other screens that ask about faster claims processing](https://www.figma.com/design/jpJQSCKiGegacdW4RH5uQB/Burial-530-2024-Updates-MVP?node-id=1826-42133&t=sCq2SSAASMCUsJPe-4) - the product team confirmed that they're aligning that question/content with what's in the pension form.

Product will confirm if these updates will happen before the other H1/breadcrumb/form URL updates.

**fysa** @aprocik1
