### ISSUE TITLE
[CST] Add motion and pre_docketed to `getStatusContents` helper

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#80669]
### Background
We are using a helper function called `getStatusContents` that gets the content to display under the `Current Status` section of the appeal details page. We use a switch statement to account for all of the statuses that we are aware of currently, and the default statement covers any unknown statuses and logs those values to Sentry. We have identified two statuses that were previously unknown, and in order to help find more, it makes sense to add cases for those statuses. 

### Related Issue(s)
- department-of-veterans-affairs/va.gov-team/issues/80665
- department-of-veterans-affairs/va.gov-team/issues/80647

### Engineering Notes
They should return the same content as the default case does which is:
```jsx
contents.title = 'We don’t know your status';
contents.description = (
    <p>We’re sorry, VA.gov will soon be updated to show your status.</p>
);
```

### Tasks
- [x] Add case for 'motion' to the switch statement
- [x] Add case for 'pre_docketed` to the switch statement

### Acceptance Criteria
- [ ] The `motion` and `pre_docketed` statuses no longer log messages to Sentry
- [x] The `motion` and `pre_docketed` statuses return the same values as the default case

**Comment by jerekshoe** [comment]
I looked in Sentry and the claims-status app hasn't generated any messages related to unknown appeal statuses since April 12th (the day the PR was merged). I did find that the dashboard is still logging Sentry messages as they have a copy of the code that they are using, so I won't be able to prevent any messages about these 2 unknown statuses appearing in Sentry, but claims-status is not generating them anymore
