### ISSUE TITLE
Don't include hashes in asset file names

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#8067]
## Problem Statement
We're currently using the manifest Webpack emits to replace all references to application assets in the HTML to the filenames with the hashes. Once we move the content build out of `vets-website`, it will no longer have access to Webpack's manifest, so we can't use it to update the references.

The solution is to no longer use the hashes in the filenames, but rely on the `Cache-Control` header for cache busting.

---
## Tasks
- [x] Remove the hashes on the filenames in the Webpack config
- [x] Update the templates to use `href` or `src` properties instead of `data-entry-name`
- [x] Remove the `processEntryNames` Metalsmith plugin

## Acceptance Criteria
- [x] The applications assets are still loaded

## Impact to Customers
- Application assets will no longer have hashes in the filename. This should not impact teams since our recent Cache-Control: no-cache work removed those from assets already. If an unknown issue occurs, please let us know.
