### ISSUE TITLE
Make consent of electronic correspondence specific to this claim

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#80673]
## Issue Description
Finding from 526 Paper Form Sync Audit ([Sharepoint link](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/80671))

Checkbox on #11 ("I agree to receive electronic correspondence from VA in regards to my claim")
The language referred to here exists on the form that takes in the email address at the time of creating the account on VA.gov and is not specific to this claim. 

Scope - 
The scope of this ticket includes making the consent specific to this claim, adding back in the checkbox on #11 from the paper form.

---
## Tasks
- [ ] Evaluate section 01 of the digital form to confirm best location for checkbox consent.
- [ ] Create mocks in figma for new checkbox consent language
- [ ] Update [Mural flow diagram] with new mocks once added (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?invited=true&sender=e1c05cf2-696e-4c36-a0ec-98a472ee6ebd)

## Acceptance Criteria
- [ ] New mock completed for addition of this checkbox language
- [ ] Design reviewed with engineers
- [ ] New mock added to mural diagram
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
