### ISSUE TITLE
[CST] Ensure that `| Veterans Affairs` is included in all page tab titles

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#80672]
### Background
We are setting the value of `document.title` in various places throughout the app. All page title slugs must include `| Veterans Affairs` and there are several places in the code where we are setting `document.title` without including it. We have a helper called `setDocumentTitle` that takes a string and appends `| Veterans Affairs` to the end before setting the value of `document.title` so we should be using that everywhere we want to set the title slug.

### Engineering notes
Components that are not using the `setDocumentTitle` helper currently:
- AdditionalEvidencePage
- AdditionalEvidencePageOld
- AskVAPage
- ClaimEstimationPage
- DocumentRequestPage
- StemClaimStatusPage
- YourClaimLetters

### Tasks
- [ ] Update the `AdditionalEvidencePage` component to use `setDocumentTitle`
- [ ] Update the `AdditionalEvidencePageOld` component to use `setDocumentTitle`
- [ ] Update the `AskVAPage` component to use `setDocumentTitle`
- [ ] Update the `ClaimEstimationPage` component to use `setDocumentTitle`
- [ ] Update the `DocumentRequestPage` component to use `setDocumentTitle`
- [ ] Update the `StemClaimStatusPage` component to use `setDocumentTitle`
- [ ] Update the `YourClaimLetters` component to use `setDocumentTitle`

### Acceptance Criteria
- [ ] We are using the `setDocumentTitle` helper in all places where we update the value of `document.title`
