### ISSUE TITLE
[Epic] Personalized Career Planning and Guidance Program (PCPG) aka Chapter 36 (25-8832)

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#80683]
## Issue Description

This epic will house work related to Benefits Non-Disability Experience team around Chapter 36. Chapter 31 work is captured here: #80506

The tickets are organized by intake:
**Intake title as task list title**
- intake ticket
- associated child tickets (linked to this epic, not nested under intake ticket)
```[tasklist]
### PCPG (Chapter 36) Form Updates
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77805
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80327
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78277
```

```[tasklist]
### Static Page Updates for Burial, PCPG, VR&E, COE Forms
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77810
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77971
```

**Comment by mnorthuis** [comment]
closing product-specific epics
