### ISSUE TITLE
Complete implementation of Section 2 into 526 form

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#80687]
## Issue Description
Finding from 526 Paper Form Sync Audit: Row 04 ([Sharepoint link](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B3308EE26-A184-42ED-AFC0-44B1D20F12A6%7D&file=526%20paper%20sync%20audit%20.xlsx&action=default&mobileredirect=true))

Section II: Change of Address is absent from 526 online but looks partially coded. Proposal: Complete Implementation

Scope - 
The scope of this ticket includes designing a solution for veteran to update/change their address

---
## Tasks
- [ ] Evaluate current address section of form, look to proposal from VBA
- [ ] Design a solution for Veteran to update their address 

## Acceptance Criteria
- [ ] Mock that demonstrates how Veteran is able to change their address
- [ ] Design reviewed with engineers
- [ ] New mock added to mural diagram
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
