### ISSUE TITLE
Collaboration Cycle for Veteran Facing Form - Form Upload

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#80689]
### VFS team name

Veteran Facing Forms

### Product name

Form Upload

### Feature name

Document Upload

### GitHub label for team

1-forms-audit-digitize

### GitHub label for product

document-upload

### Public DSVA Slack channel for VFS team

veteran-facing-forms

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>
### When did/will you start working on this product/feature?

4/2/2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Product%20Outline%20File%20Upload.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.
Kickoff Slack Thread with VFS team: [Kickoff thread](link)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712956678497/a6c9c95e6dafa6eb641566aec68c8fc6c74fced6?sender=u2dd1818fc590a5b2e62f8183)

Not required, but nice to have:
- [ ] [Wireframes](https://www.figma.com/file/jnxB6t5V4xgv1WcIL71Qgz/DSC%3A-PDF-Upload?type=design&node-id=1%3A21&mode=design&t=68vdTPMmRw5j43Wc-1) **Older version**
- [ ] New figma project: [DSC: PDF Upload](https://www.figma.com/file/jnxB6t5V4xgv1WcIL71Qgz/DSC%3A-PDF-Upload?type=design&node-id=30%3A16707&mode=design&t=68vdTPMmRw5j43Wc-1)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [x] [Design Intent Slack thread with VFS team](https://dsva.slack.com/archives/C044AGZFG2W/p1713206446318809)
- [x] Meeting date/time: Friday, April 19, 2024 at 2:00 ET
  
##### Governance Team actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/WToHhLi_1BbpmmnoIIzGObFfYMzG18D7S2Iybv01DpzwgUggAkMq40fFYUjlaGZl.yZqF9-i2sX65_88n)
  - Passcode:`W4#s$X@D`
- Accessibility
  - [x] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [x] No feedback
- IA
  - [x] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  
</details>

### Architecture Intent
<details>
  <summary>Toggle Architecture Intent instructions</summary>

##### VFS team actions
- [ ] Review [Architecture Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent) to understand what this touchpoint involves.
- [ ] Schedule your Architecture Intent (with at least 2 business days lead time from now):
  - Open the [Calendly Architecture intent calendar](https://calendly.com/collaboration-cycle/architecture-intent)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [x] Link all artifacts in the `Architecture Intent artifacts for review` section below at least two business days before the scheduled Architecture Intent. Please don't add artifacts in the comments section.
  
**Architecture Intent artifacts for review**

[See guidance on Architecture Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent#ArchitectureIntent-Whatartifactswillbeneeded?) Feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] Fully completed [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md)
  - [Veteran Facing Forms Form Upload architecture intent meeting document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/collaboration-cycle/architecture-intent/checklist/Veteran%20Facing%20Forms%20-%20Form%20Upload%20Tool%20-%2012112024.md)
- [ ] [User data flow diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712956678497/a6c9c95e6dafa6eb641566aec68c8fc6c74fced6), if your application accepts data from a user.

##### Platform Team actions
- [x] Meeting date/time: **Dec 16, 2024 at 4:30pm ET**

##### Platform Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Mobile Engineering feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback
- Security feedback
  - [ ] Feedback ticket attached to milestone
  - [ ] No feedback  

##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] [Finalized design prototype or mockup](https://www.figma.com/file/jnxB6t5V4xgv1WcIL71Qgz/WIP%3A-Form-Upload?type=design&node-id=215-25718&mode=design&t=CwsZconqFQi9K6hq-0)
- [x] Page to review: [🟢 MVP Form upload flow with standard header/footer](https://www.figma.com/design/jnxB6t5V4xgv1WcIL71Qgz/Form-Upload?node-id=0%3A1&t=4LFfNNjZuv8PVVRQ-1)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Research%20plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Conversation%20guide.md)
 
**Content artifacts**
  
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

**IA artifacts** N/A will be on Find a form About Page

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C044AGZFG2W/p1715200912832829)
- [x] Meeting date/time: May 13th at 3:30pm ET

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [ ] No feedback
* Content
  * [x] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/HzhWoLggljtyMd_pM_8tFjGsL3h3DPV_fMThNIn9t9iVlh7UKoIc5Ur9PGiv772E.1f65Ft2S2mOfDNGC)
  - Passcode: `pKZ5hNV*`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

### Staging Review

<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

**### [FORM UPLOAD ARTIFACTS
](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/Supporting%20Artifacts.md)**
Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [ ] **URL(s) to review the product**
  - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
  - List pages, sections of pages, and/or user flows impacted by this work.
- [ ] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search)
  - If the primary entry point is not a page on VA.gov, include information about how to view it. Reach out to `@platform-governance-team-members` on Slack with any questions.
- [ ] **Test users and scenarios** (when applicable)
  - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a .md file in the va.gov-team-sensitive repository. 
  - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
- [ ] **Link to Sitewide CAIA intake ticket**, if applicable.
- [ ] **Completed accessibility testing artifact:** see [instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
- [ ] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
  - [ ] Regression test plan
  - [ ] Test plan
  - [ ] Coverage for References
  - [ ] Summary (Defects) reports
  - [ ] E2E tests
  - [ ] Code coverage
  - [ ] Endpoint monitoring playbook
  - [ ] Logging silent failures

**Not required, but nice to have artifacts**
- [ ] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth.
- [ ] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec.
  
##### Platform actions
- [x] ~~[Slack thread with VFS team
](https://dsva.slack.com/archives/C044AGZFG2W/p1734019628032969)~~ [new Slack thread](https://dsva.slack.com/archives/C044AGZFG2W/p1735849566202109)
- [x] Meeting date/time: ~~03:30pm - Thursday, January 9, 2025~~ Thursday 1/16 at 1:30pm ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/EtLZZv0yvmM3Ame-uMR8lEhKQIdANJ-aZo2xN7uGZQCjDWmRmIRDfcFco37c2eIP.QRmQQn2Y0_ivoJvE)
  - Password: `V2&9Pwj.`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
- [ ] [Complete Collaboration Cycle feedback survey](https://ows.io/qs/gb1dfnkl)

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by rachelshearerux** [comment]
Hi friends, I just updated the wireframe link in this ticket to point to a new figma project space. We're looking forward to your review! 

New figma project: [DSC: PDF Upload](https://www.figma.com/file/jnxB6t5V4xgv1WcIL71Qgz/DSC%3A-PDF-Upload?type=design&node-id=30%3A16707&mode=design&t=68vdTPMmRw5j43Wc-1)

**Comment by shiragoodman** [comment]
@tbaker1026 FYI I have added the Architecture Intent section to this ticket

**Comment by DonMcCaugheyUSDS** [comment]
Thanks for participating in today's architecture intent meeting.  Here is my feedback:

- consider prefilling email from the veteran's profile
- investigate what happens to repeated or abandoned file uploads
    - ensure that uploaded files are promptly cleaned up
- work with design system team to improve file upload component so it can easily retain state in complex, multi-view forms

@JonathanKamensDVA do you have any additions?

**Comment by JonathanKamensDVA** [comment]
We discussed the potential for fraud of forms we may not be able to anticipate in advance, enabled by the fact that the current implementation allows users to upload forms on behalf of other people. We decided we don't know for certain whether this will be a problem, so initially we're going to approach it in data-collection mode, by logging to Datadog whenever someone modifies the identification metadata when uploading a form. The data itself should not be logged because it's PII, but an identifier that associates the log entry with the form upload in question should be logged, so we can look at the data in the database if necessary. Once the feature has been live for a while we will evaluate the data we are getting from this logging to determine whether further action is warranted/needed; we may also look into setting up an anomaly alert in Datadog to alert us if there's a sudden spike in the amount of these logs messages that warrants investigation.

**Comment by Thrillberg** [comment]
> - consider prefilling email from the veteran's profile

Resolved here: https://github.com/department-of-veterans-affairs/vets-website/pull/33627

> - investigate what happens to repeated or abandoned file uploads
>   - ensure that uploaded files are promptly cleaned up

Tracked here: https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&filterQuery=-status%3AIcebox%2CEpic%2C%22Collab+Cycle%22&pane=issue&itemId=92379398&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1945

> - work with design system team to improve file upload component so it can easily retain state in complex, multi-view forms

Tracked here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3634

>logging to Datadog whenever someone modifies the identification metadata when uploading a form.

Resolved here: https://github.com/department-of-veterans-affairs/vets-api/pull/20030

**Comment by tbaker1026** [comment]
This went live on 2/28/2025 - closing collab cycle ticket
