### ISSUE TITLE
DR | Update Review & Submit error alert to v3

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#80680]
## Value Statement
**_As a_** Veteran attempting to submit a Decision Review on VA.gov
**_I want to_** see consistent error alerts when receiving form feedback
**_So that_** I have the same up-to-date instructions available across all forms. 

---
## Background Context
- As part of the update to USWDS 3.0, error alerts have changed to have a colored background. The alert for the review and submit page does not have this style.

<details>
<summary> Current form review your request error message on SC / NOD / HLR</summary>
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUZaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1349361294ec0cf469983389dd0b5513d425ff0a/Screenshot%202024-04-12%20at%202.07.49%E2%80%AFPM.png" alt="Screenshot 2024-04-12 at 2.07.49 PM.png" />
</details>

## Acceptance Criteria
- [x] When there is an error on the review page on NOD, it shows the updated error v3 alert component.
- [x] When there is an error on the review page on HLR, it shows the updated error v3 alert component.
- [x] When there is an error on the review page on SC, it shows the updated error v3 alert component.

## Designs and Build Notes
Error alert:
[FIGMA](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=140-41943&mode=design&t=wTyan66lehjOBJef-11)

## Out of scope
- Error message

## Tasks
- [ ] Update alert in platform code
- [ ] Add/update unit tests
- [ ] Check review errors rendering content inside
- [ ] Check e2e tests

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@Mottie will drop in tasks.
