### ISSUE TITLE
Implement Flipper Component for 686 (Part 2 of 2)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8068]
## Goal 
The second Flipper component will remove the CTA for direct, authenticated access (in blue) until after we are ready for that. 

## Considerations
- The front end HTML code will be shared with PubWeb for when the landing page gets built out.

## Tasks
- [x] Build some HTML code to be embedded into the landing page
- [x] Configure Flipper to show or hide the blue section

## Acceptance Criteria
- [ ] Flipper has been configured and tested for the 686 launch
