### ISSUE TITLE
5/27 Veteran Representative Experience - All Hands Presentation

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#80700]
## Issue Description
Consolidation of Veteran and caregiver interviews to encompass the representative experience focusing on three parts;
1. Motivation for getting a representative
2. Search process for getting a representative
3. Representative engagement

All Hands should include:
* Journey ONLY
* Trim 'search' section

## Tasks
- [ ] Confirm content with Shannon
- [ ] Share with Shannon
- [ ] Update deck with edits

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Sent deck to Shannon for review https://docs.google.com/presentation/d/1AjpsQbEL6HxwMkKjnEJHVzG-zIzRfo--OYKVSEv7SS0/edit?usp=sharing 

Closing - not seeing a lot of changes needed as there was some back and forth previously.
