### ISSUE TITLE
6/3 Present at Design All Hands - Find a Rep AT Focus

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#80701]
## Issue Description
Topic TBD

## Tasks
- [ ] Decide on a topic
- [ ] Send to team
- [ ] Make slim deck (15 - 20 mins)
- [ ] Present

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Deck updated to 15 - 20 min preso of Find a Rep findings https://docs.google.com/presentation/d/1HUOCTDZiGfEa5mXY_i4hGIY3FMbOrfjGbX_5OGVDTPs/edit?usp=sharing
