### ISSUE TITLE
Toxic Exposure - implement in FE changes to the JSON schema for TE fields

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#80718]
## Issue Description
During the course of determining the FE to BE contract for new TE fields, some renaming and refactoring will be required. For example:
- the FE will now send all new TE fields in a parent JSON node called `toxicExposure`
- change herbicideLocations/gulfWar1990Locations to herbicideDetails/gulfWar1990Details

---
## Related docs

- Related [ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79278)
- [FB/BE contract](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md)
- 

## Tasks
- [ ] Refactor FE to send JSON according to changes above
- [ ] Update unit/e2e/etc tests

## Acceptance Criteria
- [ ] FE will send the BE form JSON according to the new [contract](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
