### ISSUE TITLE
Add Google Analytic unique event code to CST for Claim Cards, Alerts, and Submit Files

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#80722]
We want to track the conversion funnel from the claim list page all the way to the submit files page.

## Tasks
- [x] add GA event code to Claim Cards "View details" link
- [x] add GA event code to Claim Details/Status "View details" links
- [x] add GA event code to Submit Files submit button

**Comment by samcoforma** [comment]
@jacobworrell Can I close this?

**Comment by jstrothman** [comment]
@jacobworrell  If we haven't, can you ask analytics folks if we need to update them about custom events we add between the audit request and the switch to GA4?
