### ISSUE TITLE
[DevOps] Add error handling to day-end-summary script.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#80733]
## User Story
As an engineer, I want to handle errors returned from the Datadog API so that 1) we're aware of what those errors are, and 2) the Slack webhook doesn't fail silently.

## Tasks
- [x] [DevOps] Add error handling to the day end summary script.
- [x] [DevOps] Send a message to the channel when something fails.
- [x] [DevOps] Parameterize the workflow so that we can test against `#check-in-experience-devops-test`.

## Acceptance Criteria

- [x] Script dumps errors to stdout.
- [x] Workflow sends a message to the channel if the script or any other workflow operation fails.
- [x] Workflow channel is a parameter so we can test the script manually.

**Comment by ndouglas** [comment]
Added `EOD_SUMMARY_TEST_SLACK_WEBHOOK_URL` secret in `checkin-devops` to point to a webhook URL for posting to `#check-in-experience-devops-test`.
