### ISSUE TITLE
526 Paper Form Sync: Make consent of electronic correspondence specific to this claim

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#80737]
## Epic Description
Finding from 526 Paper Form Sync Audit: Row 16 ([Sharepoint link](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B3308EE26-A184-42ED-AFC0-44B1D20F12A6%7D&file=526%20paper%20sync%20audit%20.xlsx&action=default&mobileredirect=true))

Checkbox on Question 11 ("I agree to receive electronic correspondence from VA in regards to my claim")
The language referred to here exists on the form that takes in the email address at the time of creating the account on VA.gov and is not specific to this claim. 

Scope - 
The scope of this ticket includes making the consent specific to this claim, adding back in the checkbox on question 11 from the paper form.

---
## Tasks
- [ ] Evaluate section 01 of the digital form to confirm best location for checkbox consent.
- [ ] Create mocks in figma for new checkbox consent language
- [ ] Update [Mural flow diagram] with new mocks once added (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?invited=true&sender=e1c05cf2-696e-4c36-a0ec-98a472ee6ebd)

## Acceptance Criteria
- [ ] Consent is specific for this claim
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
