### ISSUE TITLE
Update Platform Roster from sitewide-CMS GitHub

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80748]
Duped for Sprint 3 [86280](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/86280) with 1 story point to complete. 

## Issue Description
Sitewide Web Facilities brought to Product Platform's attention via [Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1712874205738459) the fact that the membership on [this page](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-sitewide-cms) was incorrect for the following reasons: 

1. CMS is now a Platform team, so sitewide-cms is old / incorrect naming
2. Edmund is on CMS team. Other CMS folks are not in this group.
3. Laura is on Sitewide. Other Sitewide folks are not in this group.

Per Erica Washburn, the decision was to add those CMS members to the [Platform roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster) now.

## Tasks
- [x] Deprecate sitewide-cms Github team
- [x] Move those folks from sitewide over to the [Platform Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] Delete entries from Atlas
- [x] Investigate if we are missing something in onboarding/offboarding? It could be that the initial import from the roster spreadsheet was incorrect - inquire with on/off boarding procedures with the support team
- [x] Review Atlas for references to siteside-cms and update accordingly

## Success Metrics
- Jill Adam's request has been satisfied

## Acceptance Criteria
- [x] [Platform roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster) will be updated with CMS team info and correct
- [x] sitewide-cms Github team will be deprecated
- [x] Atlas references to siteside-cms is updated accordingly

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by RachalCassity** [comment]
@jennb33 CMS team was updated [here](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster#CMS-(Community-of-Practice)). Some team members could not be found in confluence. 
Team Member Data: https://docs.google.com/spreadsheets/d/1ISlwAR_ewG6Ky2FvYDTqftaQofI1i6hCTo4CLyVbp7Q/edit?usp=sharing

**Comment by RachalCassity** [comment]
The initial roster had the sitewide cms users.[Uploading... Screenshot 2024-06-13 at 12.09.23 PM.png]

**Comment by RachalCassity** [comment]
Please check the Platform Roster

**Comment by rmtolmach** [comment]
Reviewing 👀 
I can't see the screenshot from Rachal's comment, so maybe she shared the same thing I'm talking about here. But the CMS people were already on the Platform roster [here](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster#Platform-Content-Management-System-(CMS)-Team). They are pulled in from the [CMS Team Home page](https://vfs.atlassian.net/wiki/spaces/PCMS/overview). I see @RachalCassity, you added the team in the [CoP section](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster#CMS-(Community-of-Practice)). 
See screenshot of the table of contents for what I'm talking about:

![Screenshot 2024-06-17 at 2 37 50 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/0a2ca8fe-d9e1-48bf-9766-9d661b0061f8)


CMS members can be edited from the [CMS Team Home page](https://vfs.atlassian.net/wiki/spaces/PCMS/overview) and that gets pulled into the Platform roster.

---
For the github teams:
1. Can we delete [vfs-sitewide-cms](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-sitewide-cms)? Is there any negative impact to Atlas if this is deleted?
2. [platform-cms](https://github.com/orgs/department-of-veterans-affairs/teams/platform-cms) and [vfs-cms-team](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-cms-team) exist.

**Comment by RachalCassity** [comment]
@rmtolmach I am not seeing these teams exist in Atlas. I am not removing a github team. I think that should be the project manager. @jennb33 thoughts?

**Comment by RachalCassity** [comment]
@rmtolmach I was supposed to move the roster over? I guess they can clean it up. This is not our jurisdiction and I was trying to help.

**Comment by jennb33** [comment]
let's not delete anything or remove any GitHub teams unless specified. These were the only instructions from Erica Washburn (in the original Slack message). Please do not do any additional work. Thanks @RachalCassity @rmtolmach  cc: @LindseySaari

**Comment by rmtolmach** [comment]
@jennb33 @RachalCassity The original ask in the [Slack message](https://dsva.slack.com/archives/CT4GZBM8F/p1712874205738459) is for the removal of this github team:
https://github.com/orgs/department-of-veterans-affairs/teams/vfs-sitewide-cms.

**Comment by jennb33** [comment]
I have sent a comms to Erica Washburn re: confirming the work, [here](https://dsva.slack.com/archives/CT4GZBM8F/p1718722496523769) and next steps.

**Comment by jennb33** [comment]
Per Michelle Dooley, Program Manager for Sitewide CMS, CMS is not its own COP so I'm confirming with her now in [this Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1718722496523769) where CMS should be placed.

**Comment by jennb33** [comment]
@RachalCassity - I got edits for this ticket; Michelle Dooley had some corrections, as follows ([these](https://dsva.slack.com/archives/CT4GZBM8F/p1718736430991789?thread_ts=1718722496.523769&cid=CT4GZBM8F) were in [this Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1718722496523769))

We should probably have Michelle sign off on her edits as well, so I will make a copy of this ticket for the next Sprint. Thank you!
cc: @rmtolmach and @LindseySaari 

- leave CMS as experience team
- remove CMS CoP
- I added some people to the appropriate CoPs but I don't know how to make it look like the others!!?
- And for some reason the Product Managers table isn't updating based on the updates I made to the Product CoP

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHB6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--102be0acdeda5b59d7abfe90e9c7444c980e591a/image.png" alt="image.png" />

**Comment by rmtolmach** [comment]
I fixed #3.

**Comment by jennb33** [comment]
Closing this ticket, as [86280](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/86280) is the dupe ticket to continue the work in Sprint 3
