### ISSUE TITLE
[Epic] 21-526EZ (App for Disability + Related Compensation Benefits)

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#80749]
## Issue Description

This epic will house work related to the 526EZ from multiple teams:
- Disability Experience Team 2
- Disability Benefits - Employee Experience Team
- Disability Benefits Experience Team 1
- Content Classification

The tickets are organized by intake:
**Intake title as task list title**
- intake ticket
- associated child tickets (linked to epic, not nested under intake ticket)
```[tasklist]
### Disability Experience Team 2: 526 ez application tool
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65444
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65855
```

```[tasklist]
### Disability Benefits - Employee Experience Team: 21-526EZ, Max CFI
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69856
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71240
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70750
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69999
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74019
```

```[tasklist]
### Benefits Disability Experience 526 EZ: Toxic Exposure Screens
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72033
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/72012
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78831
```

```[tasklist]
### Toxic Exposure, from Disability Benefits Experience Team 1
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76281
```

```[tasklist]
### Contention Classification Team - New Conditions Page (Form: 21-526EZ)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76707
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76766
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76919
```

```[tasklist]
### Contention Classification work on 526 EZ conditions list
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68416
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69002
```

```[tasklist]
### Updates to PTSD and MST questions in 526EZ
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80870
```

```[tasklist]
### Collaboration Cycle: Add 5103 to 526ez
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82160
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82804
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82809
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82814
```

```[tasklist]
### Collaboration Cycle for Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/60140
```

**Comment by mnorthuis** [comment]
closing product-specific epics
