### ISSUE TITLE
Sandra's Onboarding Checklist

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8074]
### Get access to tools

[Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)

- [x] Slack
- [x] Github

### Docs to review

**Authenticated experience docs**

- [x] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/charter.md)
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/product-outline.md#north-star-objectives)
- [x] [Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap.md)

**General docs**

- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/README.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/code-of-conduct.md)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md)
- [x] Review the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to learn the syntax for formatting documents in GitHub
- [x] [VSA Team Structure](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit)
- [x] [Trying out tools as a Staging User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)

### Folks to meet with

**Authenticated experience team**

- [x] Intro with Samara (VA team lead)
- [x] Intro with Matt Shea (PM)
- [x] Intro with Tressa (PM)
- [x] Intro with Erik (PM)
- [x] Intro with Lihan (PM)
- [x] Intro with Andrea
- [x] Intro with Trevor (Mon)
- [x] Intro with Paul Short

**Comment by Samara-Strauss** [comment]
Hey, is this actually complete? I know I haven't had a 1:1 with Sandra. @sanlouise have you gotten to meet individually with folks to get intro'd to the team?

**Comment by mshea0606** [comment]
@Samara-Strauss Sandra is setting up time with the team. She accidentally thought the standup meeting intro was intro's. She's had actual intro's with myself, Erik, Andrea, Trevor, and Paul Short so far.

**Comment by Samara-Strauss** [comment]
Awesome, thanks for letting me know! I've got a chat on the books with Sandra for later this week. Looking forward to it!!

**Comment by sanlouise** [comment]
@mshea0606 Can you move this to Closed since I had all 1-on-1s? Thanks!

**Comment by mshea0606** [comment]
@sanlouise closed
