### ISSUE TITLE
Manually create a CSV file for rates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8075]
## User Story or Problem Statement
As a stakeholder/SME updating rates for pages in VA.gov, I need a way to easily update and share updated rate information so I can get VA.gov rates updated in a timely and repeatable manner.

## Problem:
Currently static tabular information is extremely manual and tedious to maintain and keep up-to-date. The information content team receives from SMEs do not map to the Veteran-centered modern organization of tables.

See attached example of rates information that stakeholders use to update table data:
example-pension-rates-raw-table.docx

## Goal

Manually create a CSV file for rates. Each table on a page will need to be represented by a worksheet tab, in a consolidated CSV file. 
Note: this file will be shared with SMEs for them to update the rate information, and then return it to us for upload, going forward.

We will need to provide SMEs with this, as well as provide walkthrough/initial briefing of how to use, in time for them to do their work and update rates by the end of the year. The timing of that - perhaps Q3? - will likely be contingent on when the rates need to begin updating. Most rates switch over on December 1, so we will want to share this work with SMEs as soon as we can so they can use this process to replace how they are currently doing their work.

---
## Tasks
- [ ] Create CSV files for rates (do we need to create a ticket for each page, or hub?)

## Acceptance Criteria
- [ ] There is a CSV file for rates, for every page that contains rates
- [ ] CSV file contains worksheet tabs that represent each table found on the page
- [ ] CSV files are accessible, shareable for SMEs to access, fill out, save, and share

**Comment by MickinSahni** [comment]
Creating CSVs in other tickets. Considering duplicate.
