### ISSUE TITLE
DR | Review base font size changes

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#80768]
## Value Statement
**_As a_** Decision Reviews team member
**_I want to_** verify the formation change to base font size doesn't break our forms
**_So that_** I fix any problems prior to the change getting implemented in staging & production

## Background Context

See [font size change announcement](https://dsva.slack.com/archives/C5HP4GN3F/p1713194188063379).

> The design system team will be working on a series of pull requests within the next couple weeks to bump the base font size of vets-website from 10px to 16px.
>
> What this means is that we'll be scaling down all rem values across the repository so computed pixel values remain unchanged, and no visual difference is introduced. Eventually, in a second step, we will be bumping all values slightly, so computed pixel values increase by ~.96 pixels, but we suspect that will introduce little if any change.
>
> Our ask from all of you is that when PRs come up and your team is tagged as a code owner review, please check the pull request, specifically the review instance, and give your application a quick once over to make sure it still looks the same.

### Review instance

To find the review instance:
- Ensure you have your SOCK proxy enabled
- Go to [PR #26606](https://github.com/department-of-veterans-affairs/vets-website/pull/26606)
- Scroll down until you find the "This branch was successfully deployed" section
- Use the "Show environments" link (it's really a button)
    <img width="921" alt="Screenshot 2024-04-15 at 4 10 11 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/0b032c7c-633a-4939-bd82-2302fef304b2">
- Now use the "view deployment" button (it's really a link)
  <img width="872" alt="Screenshot 2024-04-15 at 4 13 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/1a320787-83ce-4abf-acac-9263949babcb">
- You will see what appears to be the VA.gov homepage
- Log into a user (you may to try several before one works)
- Navigate to our decision review apps

## Acceptance Criteria

- [ ] Base font size change does not break any of our layout
- [ ] Base font size change maintains appropriate margins & padding around and between components
- [ ] Base font size change does not break web components (modals, alerts, additional info, etc)

## Tasks
- [ ] Review all Supplemental Claim pages
- [ ] Review all Higher-Level Review pages
- [ ] Review all Notice of Disagreement pages
- [ ] Note discrepancies between design & layout in review instance

## Design and Build Notes
- [Supplemental Claims Figma](https://www.figma.com/file/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?type=design&node-id=0%3A4265&mode=design&t=SFXERNlzZkBZlWHz-1)
- [HLR Figma](https://www.figma.com/file/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?type=design&node-id=0%3A6044&mode=design&t=FswuCCfeyzHpfqbu-1)
- [NOD Figma](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0%3A8569&mode=design&t=GMTShBLETYL8WYU6-1)

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
[The DST reported the following](https://github.com/department-of-veterans-affairs/vets-website/pull/26606#issuecomment-2062304824):
> Work is currently paused until next sprint. DST is planning on focussing on this next sprint starting April 24th.

**Comment by Mottie** [comment]
I have completed a preliminary review of these changes locally; but I feel like there is some CSS that we need to clean up before this merge is completed.

**Comment by Mottie** [comment]
I pulled in the changes locally and found a few problems - I [added a comment to the main pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26606)

**Comment by Mottie** [comment]
Re-verified that the issues I reported were fixed. I think we can close this ticket.
