### ISSUE TITLE
526 Paper Form Sync: Add link to 5103 equivalent language

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#80767]
## Epic Description
**Finding from 526 Paper Form Sync Audit: Row 09** ([Sharepoint link](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B3308EE26-A184-42ED-AFC0-44B1D20F12A6%7D&file=526%20paper%20sync%20audit%20.xlsx&action=default&mobileredirect=true))

Digital form is missing link to the 5103 equivalent language
Goal is to do the same notification as the [evidence needed page](https://www.va.gov/disability/how-to-file-claim/evidence-needed/), with a little more detail on the intro page, and first page of evidence sections. 

Will eventually be connected to work in [81617](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/81617)

Scope - 
The scope of this ticket includes designing a solution to add this link to the 526 Intro page and the first page of the Evidence section for policy/compliance reasons.

[Figma Link for design mocks
](https://www.figma.com/file/igOOQi5BOTgQQJYA9X2G3M/5103-equivalent-language?type=design&node-id=0%3A411&mode=design&t=drMGqlASJOQRGJfx-1)

_"We’re required by law to tell you what evidence you’ll need to provide to support your disability claim. The information on this page ([link](https://www.va.gov/disability/how-to-file-claim/evidence-needed/)) is a summary of evidence requirements (called “section 5103 notice”). You can review the official evidence requirements in VA Form 21-526EZ ([direct link to PDF](https://www.va.gov/find-forms/about-form-21-526ez)). Section 5 on pages 3-8."_

---
## Tasks
- [x] Evaluate destination to include 5103 link on form, look to proposal from VBA & OCTO (Intro Page and Evidence Page)
- [x] Design mocks for including link to 5103 equivalent and new language
- [x] Review mocks with Shannon before Design Intent
- [x] Review content links with CAIA (Office hours scheduled 4/30/24)

## Acceptance Criteria
- [x] Designs have been mocked and reviewed with Shannon prior to design intent
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kate-allbee** [comment]
[Slack thread with additional info ](https://dsva.slack.com/archives/C04KW0B46N5/p1713990479971919)

**Comment by Kate-allbee** [comment]
[Figma Link for Design work](https://www.figma.com/file/igOOQi5BOTgQQJYA9X2G3M/5103-equivalent-language?type=design&node-id=34%3A73279&mode=design&t=drMGqlASJOQRGJfx-1)
