### ISSUE TITLE
Toxic Exposure - re-pipe EVSS API call to NOT generate a pdf

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#80776]
## Issue Description
Send a Form526 to receive a `claim_id`, but do not generate the PDF to send to VBMS.
This is the "autoCestPDFGenerationDisabled" story.

Does this be added to the TE feature flag?

---
## Tasks
- [ ] send claim and in all of its glory to EVSS to receive claim_id
- [ ] but ensure the call to EVSS does **_not_** generate the 526 PDF
- [ ] testing needs to be done in staging, A/B testing with the flag on and off

## Acceptance Criteria
- [ ] when EVSS is called to submit a claim,`claim_id` is received by vets-api, but the pdf is not generate nor sent to VBMS
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
per Emily we will not take this technical approach for the TE MVP release. Moving this to the icebox & will close after MVP release.
