### ISSUE TITLE
Toxic Exposure - [Lighthouse API] generatePdf hook up

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#80773]
## Issue Description
Make sure vets-api can call LH's /generatePdf endpoint and receive a 526 PDF filled out as expected.
https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current

---
## Tasks
- [x] create LH benefits-claims service#generatePdf method
- [ ] save pdf in temporary storage for later use
- [ ] update Form526 to LH Transformation Service if necessary

## Acceptance Criteria
- [x] vets-api can generate a 526 PDF with LH's /generatePdf endpoint
- [ ] generated Pdf is in on local file system
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
We have the following [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16411) out which
1. Allows us to overload the submission service to generate a PDF
2. Strips out certain special characters (like \n and \r) which were causing an issue downstream in the PDF generation service ([thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1713298304700009))
3. Adds `system/526-pdf.override` API scope to BC calls, which is needed for PDF generation ([thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1713469011121339))
