### ISSUE TITLE
Add Question 4 from paper form to Digital

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#80775]
## Epic Description
Finding from 526 Paper Form Sync Audit: Row 02 [Sharepoint Link](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B3308EE26-A184-42ED-AFC0-44B1D20F12A6%7D&file=526%20paper%20sync%20audit%20.xlsx&action=default&mobileredirect=true)

Question # 4 from the paper form "Have you ever filled a claim with VA?" is currently not in the digital 526 flow. 

Scope - 
The scope of this ticket includes adding this question to the digital form 

## Acceptance Criteria
- [ ] Question added to the form
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
