### ISSUE TITLE
Update: Style Guide Checklist with Google Drive Language

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#80794]
Recently, we updated our list of launch blocking issues to include links to Google Drive (etc.). Our [Style Guide Checklist ](https://vfs.atlassian.net/wiki/spaces/AP/pages/2438856880/Style+Guide+Checklist)-- which we share with all attendees of our Orientations -- has [a section dedicated to hyperlinks](https://vfs.atlassian.net/wiki/spaces/AP/pages/2438856880/Style+Guide+Checklist#Hyperlinks)...and that section needs to be updated to include language on links to Google Drive (etc.) 

### TASKS

- [x] Draft Language for Google Drive links 
- [x] Get team approval
- [x] Update Style Guide Checklist section on Hyperlinks with that new language. 

### DEFINITION OF DONE

- [ ] Style Guide Checklist section on hyperlinks now contains language on Google Drive links.

**Comment by BSmolensky** [comment]
This ticket requires the creation of new language.

**Comment by jknipes** [comment]
work completed, moving to _done_
