### ISSUE TITLE
Update "Create a new Platform website doc" with Date Stamp as new LB

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#80796]
PW documents that do not have a "Last Updated" date stamp on them will now be considered a Launch Blocking issue. We need to update our [external list of Launch Blocking Issues ](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page#Launch-blocking-issues)to include this change. 

### TASKS

- [x] Draft language for new launch blocking issue
- [x] Get team approval
- [x] Update Launch Blocking list with new language

### DEFINITION OF DONE

- [x] Our external list of Launch Blocking issues on the Create a new Platform website doc page now includes language about how no Date Stamp is a LBer.

**Comment by BSmolensky** [comment]
This update will now include using the "include page" function in Confluence to include the Launch Blocking master list page. This way, the list on this page will automatically update when we update the Master List. Saving tons of time in the future.

**Comment by BSmolensky** [comment]
Updated LB List can be found here: https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page#Launch-blocking-issues

**Comment by BSmolensky** [comment]
This ticket can be closed.

**Comment by jknipes** [comment]
Work is finished, moving to _Done_
