### ISSUE TITLE
Audit Confluence for Mentions of Launch Blocking Issues 

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#80798]
To get deployed, all PW pages will now need to include a "Last updated" date stamp on them. All mentions of Launch Blocking issues on Confluence should be updated to reflect this change. We know of three places where Launch Blocking issues are discussed: 

1. Our Internal Deployment Instructions
2. Create a new Platform Website doc
3. Style Guide Checklist
4. Master LB List

We need to make sure that there are not any other mentions of our LB issues elsewhere on Confluence. Why? Because we don't want users referencing outdated documents when they edit/create pages for the PW. Therefore, we must audit Confluence to find any other mentions of LB issues. And then edit those pages, if they exists. 

### TASKS

- [x] Make a list of Confluence pages that mention or include our LB issues (other than the three mentioned above) 
- [x] Create edit tickets for each additional page (if necessary) 

### DEFINITION OF DONE

- [x] All pages containing language outlining our LB issues have been located. 
- [x] Edit tickets created (if necessary)

**Comment by jknipes** [comment]
`launch-blocking` vs. `launch blocking`

**Comment by CherylEvans** [comment]
@jknipes Multiple links connect to Platform pages instead of linking to the Confluence source documentation. I performed an audit to find which links on the page were incorrectly linked to Platform pages vs. Confluence pages by doing the following: Open page -> (E.G., https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) -> Right-click anywhere on the page and select INSPECT -> A developer panel will open up on the right side of the page -> Use Control F (Mac) or whatever 'FIND' function keys for your particular computer's OS -> type what you are searching for on the page (taget="_blank"). It will return every instance of the attribute on the page. Because code can be very touchy, I recommend searching for one word only and not the whole string (target). The up/down arrow will point you to every attribute instance. This tells you which links are tied to Platform pages (incorrect) and which links are tied to Confluence pages (correct).

**Comment by jknipes** [comment]
Work has been completed, moving to _Done_
