### ISSUE TITLE
Update "Style Guide Checklist" with Date Stamp as new LB

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#80797]
PW documents that do not have a "Last Updated" date stamp on them will now be considered a Launch Blocking issue. We need to update our [Style Guide Checklist](https://vfs.atlassian.net/wiki/spaces/AP/pages/2438856880/Style+Guide+Checklist) to include this change. 

### TASKS

- [x] Draft language for Style Guide Checklist (language should include link to "how to" doc)
- [x] Get team approval of language
- [x] Decide where on the page it should live
- [x] Update page with new language

### DEFINITION OF DONE

- [ ] Our Style Guide Checklist now includes language about including the Date Stamp on PW docs

**Comment by BSmolensky** [comment]
This update will now include using the "include page" function in Confluence to include the Launch Blocking master list page. This way, the list on this page will automatically update when we update the Master List. Saving tons of time in the future.

**Comment by BSmolensky** [comment]
Page updated. Ticket ready to close.

**Comment by BSmolensky** [comment]
Closing Ticket.
