### ISSUE TITLE
[DA] 10-10EZ - Reg Only MVP: Analytics updates

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#80832]
## Benefit to the Veteran
By updating our analytics, such as adding new events and updating the DOMO funnel, we can monitor the user flow through our application and determine where Veterans are being prompted for the Registration process, leaving the form, downloading a blank PDF form or selecting to go back to the previous page and move through the enrollment process.  This will help us understand user behavior and determine how many Veterans are registering, and where Veterans might be struggling.

## Background
We need to update the DOMO URL funnel with the flow of pages, including any new pages created (??). We may also need to submit a GA ticket to add any custom events not already baked into the form components.

## Tasks
- [x] Determine if there are any custom events that need tracking
     - Reference comments below
- [x] Determine if there is an update needed to the DOMO URL funnel
- [x] If either of these have updates needed, open a [GA/DOMO request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+collab-cycle-review%2C+collaboration-cycle%2C+gtm&projects=&template=analytics-google-analytics-implementation-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D)

## Acceptance Criteria
- Analytics are being updated with the latest changes due to the new Reg Only user flows

**Comment by luis-simauchi** [comment]
Reg only users would have to call in after clicking though on the form

**Comment by luis-simauchi** [comment]
Reg only users would have to call in after clicking though on the form

**Comment by hdjustice** [comment]
Goal - Veterans are registering or enrolling
- capture answer (radio button)
- page flow/funnel
     - answer register, see information box/page, then they go back and select enroll - expect this to be most common
     - answer register, see information box/page, then they exit the form
     - answer register, see information box/page, then they perform site search
- Veterans coming from site or external to access the form

**Comment by luis-simauchi** [comment]
question posed by Lois 
-  Are there call center volumes that we could request to assess the interest levels for registration only?

**Comment by emily-brown34** [comment]
discuss with HEC, will make an agenda item

**Comment by luis-simauchi** [comment]
Determine if there is an update needed to the DOMO URL funnel?
-- We will but is for one page

**Comment by hdjustice** [comment]
@luis-simauchi - do we need another ticket for this one to submit the analytics ticket?
