### ISSUE TITLE
[Design] 10-10EZ - Reg Only MVP: Design Updates

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#80831]
## Benefit to the Veteran
By updating the 10-10EZ designs to reflect the proposed user flow and displaying alerts in a timely and logical manner, we will reduce confusion and burden for the Veteran completing the application for only their service connected care (registration).

## Background
As part of the Reg Only MVP, we want to reorganize the pages for Authenticated and Unauthenticated users, so that they are prompted with the Registration alert early and avoid completing too much of the form before being redirected to call the Health Enrollment center.
We also want to address the alerts on the pages, including Short Form alerts, so that they display appropriately.

## Tasks
- [x] Update the user flows for Authenticated and Unauthenticated users (for all disability rating) in the source of truth Mural and Figma files
- [x] Update and draft pages and alerts to display in the appropriate parts of the flow
- [x] Open content ticket for review of new alert messaging and question in flow - [Content Request from 10-10 Health Apps - Registration Only #67133](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67133)

## Acceptance Criteria
- Designs are updated and ready for content review process

**Comment by jessicastump** [comment]
Detailed user flows added to the [Registration MVP Mural board here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487582087/34c3dab41845b8a2ca33afa97e05671703ca8395?wid=0-1713996138334&outline=open) for the 10-40% disability rating group.

**Comment by jessicastump** [comment]
MVP User Flows with two options and showing alert clean-up for SC over 50%
- [mvp user flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487582087/34c3dab41845b8a2ca33afa97e05671703ca8395?sender=uadf1ed7fe7c76f0914967329)
- [figma designs with drafted alert content](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=3025-106249&mode=design&t=L5TgC5z1rWG3Hpqd-0)

**Comment by jessicastump** [comment]
Closing this ticket and [opened content review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81928)
