### ISSUE TITLE
Update MHV trend for dashboard to accurately reflect historical credential totals

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#80838]
## Issue Description
Update MHV trending view on dashboard to more accurately reflect historical MHV credentials.  As currently implemented, the historical month totals do no include users when they become inactive.  This in effect gives the impression that MHV credential adoption is slightly higher than actual. 

Instead, it should show the total credentials that were correct for at any historical snapshot.  
---
## Tasks
- [x] Reimport historical data and track inactive dates
- [x] Update transformations to merge with MPI data and account for inactive dates

## Acceptance Criteria
- [x] Dashboard updated with trending which accurately reflect historical credential totals

**Comment by skirkman16** [comment]
reimporting data with inactivity flag.

**Comment by SophiaPhilipMO** [comment]
Given this update are we good to close or will this carry over to next sprint @sdickson-gt

**Comment by sdickson-gt** [comment]
good to close
