### ISSUE TITLE
Get dsva-vfs-developers IAM group managed by Terraform

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#8083]
## User Story or Problem Statement
As a OPS team member, I need IAM groups managed by Terraform.

## Goal
IAM group dsva-vfs-developers managed in Terraform and containing CloudWatch read access for log viewing.

## Objectives or Key Results this is meant to further
- Proper management of resources
---
## Tasks
- [ ] Manage group and IAM policy attachment(s) in Terraform
- [ ] Include CloudWatch read access

## Acceptance Criteria
- [ ] IAM group dsva-vfs-developers being managed in Terraform going forward
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
