### ISSUE TITLE
[FE] 10-10EZ - Migrate all FontAwesome icon usage to va-icon

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#80850]
## Description
The Design System Team will be deprecating the use of FontAwesome icons on June 8, 2024. In an effort to get ahead of this deprecation, we need to migrate all icon usage to `va-icon`.

## Resources

- [Design System Va-Icon documentation](https://design.va.gov/components/icon)

## Tasks

 - [x] Identify all icons used and verify there is an equivalent for `va-icon`
 - [x] Consult UX for alternatives if icon is not available
 - [x] Replace FontAwesome implementation with `va-icon`

## Acceptance Criteria

- Our application is not utilizing deprecated components/patterns
