### ISSUE TITLE
Provide GA Universal Analytics (UA) data - Due 4/26/24

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#80852]
## Description

As part of the Google Analytics transition to GA4, we ask that all VFS Teams **create and share an inventory of their actively used reports that use Universal Analytics (UA) data**. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

**Note:** This is a separate ask and form from the [custom event audit](https://dsva.slack.com/archives/C1Q4294JJ/p1711559198840669) -- though should be much simpler.

- **What do I need to do?** Follow the instructions on [this Github form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-UA-Reports.md&title=Reports+Powered+by+UA%3A+%5BTeam+Name%5D), and include the name, URL link, platform, and brief description of any actively used reports that use Google Analytics UA data. We are defining "actively used reports" as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.
- **When is this due?** We'd like for teams to submit this form **no later than Friday, April 26**.
This information is needed for us to identify the best ways to assist teams with transitioning their GA reporting.

Questions? Please post any questions to the #vfs-analytics Slack channel. Additionally, feel free to join our team’s Office Hours, (every Tue & Thu @ 3:30pm ET), to discuss this in more detail. Thank you!

---
## Tasks
- [x] Audit app for Universal Analytics (UA) data
- [x] Complete the referenced spreadsheet 

## Acceptance Criteria
- [x] Form submitted to Analytics team

**Comment by Tom-Davis** [comment]
@HeatherRienks & @amponce here is the new ticket we need to account for related to the new GA update request. Due April 26th, so we need to pull it in accordingly. (Needs pointed)

**Comment by HeatherRienks** [comment]
@Tom-Davis @amponce  - It seems like we should consider pulling this into S123 if it's due on 4/26. Sprint 123 ends on 4/23, so that only gives us a few days. Let's discuss tmrw!

**Comment by Tom-Davis** [comment]
I think that is a logical ask - @amponce do you have any thoughts on what you would like to put back into ready so we have a point for point trade and nor overload the team (and we can always pull it back in if things progress quickly).

**Comment by amponce** [comment]
Domo Link to 5655 Financial Status Report - **https://va-gov.domo.com/page/447193050**


Add to ticket:
## Reporting Information:
| Report Name | URL Link | Reporting Platform  | Description |
| ----------- | ----------- | ----------- | ----------- |
|From 5655 - Financial Status Report|https://va-gov.domo.com/page/447193050|Domo| Our team uses this report to analyze trends for our KPIs.|

**Comment by OptionSelect** [comment]
Reports submitted [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81147), hopefully we provided everything but worst case we have some time to work with them in order to get them what they need!
