### ISSUE TITLE
[FE/UX] 10-10EZR - Migrate all FontAwesome icon usage to va-icon

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#80851]
## Description
The Design System Team will be deprecating the use of FontAwesome icons on June 8, 2024. In an effort to get ahead of this deprecation, we need to migrate all icon usage to `va-icon`.

## Resources

- [Design System Va-Icon documentation](https://design.va.gov/components/icon)

## Tasks

 - [x] Identify all icons used and verify there is an equivalent for `va-icon`
 - [x] Consult UX for alternatives if icon is not available
 - [x] Look into new sizing guidelines
 - [x] Replace FontAwesome implementation with `va-icon`

## Acceptance Criteria

- Our application is not utilizing deprecated components/patterns

**Comment by mkerns1** [comment]
**### Initial Findings on FontAwesome Icon Usage in 10-10EZR**

**Investigation Summary:**
I conducted an initial search to identify how many instances of FontAwesome icons (specifically the "fa" class) are currently being used in the vets-website ezr repo. The search results indicate that there are 2 occurrences of the "fa" class in one file, namely DependentList.jsx.

**Details:**

File: DependentList.jsx
Instances:
className="fas fa-chevron-right vads-u-margin-left--0p5"
className="fas fa-times vads-u-margin-right--0p5"
