### ISSUE TITLE
New Public Websites team member VSP Orientation

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#8086]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [ ] Each team member has completed each item in the orientation checklist below.

## Onboarding Checklist

- [x] Attend general orientation meeting
- [ ] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md)
- [ ] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [ ] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [ ] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [ ] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md)
- [ ] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [ ] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [ ] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/digitalmodernizationstrategy.pdf)
- [ ] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/the-new-va.gov-briefing-2019-07.pdf) documentation
- [ ] Review the [Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) documentation
- [ ] Review the [Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809)
- [ ] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [ ] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md)
  - [ ] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [ ] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [ ] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md)
- [ ] [Process for when a teammate leaves](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/contractoroffboarding.md)
- [ ] Engineers: Attend breakout session @Clark-W-Griswold @thilton-oddball 
- [ ] PM, Designers and Content Writer(s): Request content and IA intro (wait on Stephanie to schedule) @meganhkelley 
- [ ] Full team: Request KPI workshop with analytics team (wait on Stephanie to schedule) @joanneesteban 
- [ ] PM Request 508 intro (wait on Stephanie to schedule) @1Copenut 

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [ ] Assign the issues to individual(s) to complete
- [ ] Label the issues appropriately ( `orientation`, `[your-team-name]`)
- [ ] Attach the issues to this Epic

**Comment by johnhashva** [comment]
@andreahewitt-odd  I'm all set with these.
 - [X] Attend general orientation meeting
- [X]  Request Access to Tools
- [X]  Review the Guidelines for Working Safely in an Open Source Repo
- [X]  Review the Norms for Using Tools
- [X]  Review the Code of Conduct
- [X]  Review the Platform Principles
- [X]  Review the Norms for Communication
- [X]  Review the GitHub Markdown Cheatsheet to learn the syntax for formatting documents in GitHub
- [X]  Review the Digital Modernization Strategy
- [X]  Review the Web Brand Consolidation documentation
- [X]  Review the Collaboration Cycle documentation
- [ ]  Review the Collaboration Point Tracker
- [ ]  Designers: Review Design & Research Onboarding Documentation
- [ ]  Process for when a teammate leaves

**Comment by wesrowe** [comment]
Outdated onboarding documentation
