### ISSUE TITLE
Copy of Map Upstream Services: Review REV Proxy configurations

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80873]
## Issue Description
Because there is a need for an updated and comprehensive list of the upstream services that Vets API makes call-outs to, it is necessary to review the existing documentation and diagrams and updated or recreate the documents. 
They should be stored here (space **TBD**). 
The new documents should be reviewed by the cohort to ensure that there are no critical elements missing for REV Proxy. 

---
## Tasks
- [ ] Review existing documentation for REV Proxy Configs 
- [ ] Review existing diagrams for REV Proxy Configs 
- [ ] Update existing documentation for REV Proxy Configs 
- [ ] Update existing diagrams for REV Proxy Configs 
- [ ] Archive existing documentation for REV Proxy Configs; include URL in comments below
- [ ] Archive existing diagrams for REV Proxy Configs; include URL in comments below

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [ ] Updated documentation and diagrams for REV Proxy Configs used Platform Product upstream services that can be shared to all VA Platform stakeholders.

**Comment by AshleyGuerrant** [comment]
Hi @LindseySaari - is an effort like this still relevant given the current state of things after all of the EVSS discoveries & learnings?
