### ISSUE TITLE
[EPIC] Disability Benefits: adding 0781 to 526EZ - PTSD and MST questions

### ISSUE THREAD

**Issue by jinaryu** [department-of-veterans-affairs/va.gov-team#80870]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to start collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

**Note:** If you’re already partnering with us on an initiative, you don't need to fill out this request form. If you don’t have access to your initiative’s CAIA epic, post a message in the [#sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-acessibility-ia) slack channel and tag `@Terry Nichols` and `@Lily Strelich`.

## About your team

- **Team name**: Disability Benefits Experience Team 2 (Carbs)
- **OCTO product owner:** Emily Theis
- **Product name:** 21-526EZ
- **Product manager:**  Sarah Ortiz Shields
- **Slack channel:** [#benefits-disability-design](https://dsva.slack.com/archives/C053UDWMH7U)
- **Dedicated content writer on your team (if you have one):** N/A
- **Dedicated a11y specialist on your team (if you have one):** N/A
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [x] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Forms 0781 and 0781a for claiming PTSD or MST as service-connected conditions are embedded into the 526ez form flow. These forms are in the process of being updated and combined into one new form for claiming PTSD, MST, and other mental health conditions resulting from traumatic events. The current experience for claiming PTSD/MST is long and retraumatizing. Our shadowing research revealed many usability issues with this section of the form, and observed that it can double the time it takes a Veteran to submit a claim. We first want to update the online 526 experience to reflect the changes to the 0781 and 0781a forms. We anticipate that these updates address many of the usability issues we identified, and that future enhancements can be documented and added to the backlog to be prioritized according to OCTO's framework.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [x] Yes
- [ ] No
- [ ] I’m not sure 

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

I am working on wireframing and mapping out the new online 0781 flow (this is an iterative process as we are validating the flow with VBA stakeholders). The updated paper form 0781 will be released June 21. 

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. Just submitted collab cycle ticket

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **[#80848](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80848)**

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Update%20PTSD%200781%20to%20be%20aligned%20with%20new%20form%20version.md)
- [Figma file](https://www.figma.com/file/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?type=design&node-id=3%3A54997&mode=design&t=g4RkKP34AY937WRv-1)
- [VA Form 0781 Flow - Active](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712613185792/a190e081af32a64ffde84897881c5ef21731ed4e?fromVisitorModal=true&sender=u3672f0ffd2d02de8b0885285)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
- [ ] Annotations to be added to the Figma File prior to a11y Design Review #83191
- [ ] Initial meeting to discuss research with users of AT
- [ ] Inclusion of users of AT in research for MVP if possible (staging discussed in KO call 5/15)
```

```[tasklist]
### CAIA a11y tasks
- [x] Review [CC Feedback from Brian D. in CC Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81971) from `4/29/2024`
- [x] Attend Kickoff Meeting Sara and Evan `5/15/2024`
- [x] Conduct Design Review once Figma Annotations are added by Jina on `5/17/2024`
- [x] [Deliverable for the Design Review in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/Deliverables/Benefits%20Disability%20Experience%20526EZ/202405-Design-Review-Disability-Benefits-526EZ-PTSD-MST.md) c/o Evan and Sara `6/4/2024`
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83191
- [ ] Meeting to discuss research `TBD` @evanatcoforma
- [ ] Participate in research for the MVP  @evanatcoforma
- [ ] Assist with Midpoint Prep `TBD`  @evanatcoforma
- [ ] Assist with Staging Artifact `TBD` @evanatcoforma
```

```[tasklist]
### CAIA content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83565
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83253
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91289
```

```[tasklist]
### CAIA IA tasks
```

**Comment by aprocik1** [comment]
@jinaryu, thanks for this request. I know you're working with VBA stakeholders to finalize the form flow. Do you know when your Figma designs will be ready for our review?

Our content team is working on many other priorities right now. We can add this to our list and follow up with our expected timeline.

**Comment by jinaryu** [comment]
@aprocik1 design intent is scheduled for Monday (4/29) so form flow probably won't be finalized until end of next week at the earliest. ballpark estimate I'm thinking week of May 13th, but I will keep you posted. And yes please let me know your expected timeline so we can coordinate. thank you! :)

**Comment by jinaryu** [comment]
Hi @aprocik1 ! I have [wireframes](https://www.figma.com/file/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?type=design&node-id=2079-1122&mode=design) ready for review. We were wondering if we could schedule a kickoff call to inform y'all of where we are and get on the same page re: how to move forward. I understand that y'all are busy right now so let me know your thoughts! 

cc: @juliepedtke

**Comment by aprocik1** [comment]
@jinaryu, are you available for a 30 minute kickoff on Wednesday 5/15 from 12-1 pm ET? Everyone on CAIA reserves that time for kickoffs, so I know we're available. If that doesn't work for you, please provide some alternative times.

@strelichl, can you send a calendar invite and Zoom link to everyone when we land on a time?

Thanks to both of you!

**Comment by jinaryu** [comment]
@aprocik1 Yes! 12:30PM EST works for me. 

@strelichl Could you also add the following people to the meeting invite? Thank you!
nichole.nicholas@coforma.io
julie.pedtke@coforma.io
Shannon.Ford1@va.gov

**Comment by kristinoletmuskat** [comment]
Hi hi, just adding the IA notes from kickoff:

1. Consider removing references to the 0781 form number within the 526 flow. We know from research we want this section to be distinct from the rest of the form (users should be clear when they are starting and ending this series of questions), but users don't need the additional cognitive burden of trying to understand they're in a form-within-a-form. 
2. Team will also need to manage updates to 2 About a Form pages for 0781 and 0781a. A is looking into whether CAIA can make these changes, or whether public websites needs to be involved. But the product team should manage the timing of these changes.

**Comment by kristinoletmuskat** [comment]
We are also in the process of developing standards for sub-URLs and would love to take a look at the suburls for these screens once you have the content finalized!

**Comment by jinaryu** [comment]
Annotations are done! ([legend here](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2226%3A6943&t=5dMnUmMbYamJA3Qf-1)) Wanted to list out again here all the screens for review, by Figma section:

- [ ][ Intro](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2595%3A20780&t=5dMnUmMbYamJA3Qf-1)
- [ ] [Event details](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2595%3A20780&t=5dMnUmMbYamJA3Qf-1)
- [ ] [Behavior changes](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2846%3A25271&t=5dMnUmMbYamJA3Qf-1)
- [ ] [Treatment details](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2846%3A37663&t=5dMnUmMbYamJA3Qf-1)
- [ ] [Supporting documents](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2595%3A73397&t=5dMnUmMbYamJA3Qf-1)
- [ ] [Support alert component](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2226%3A6445&t=5dMnUmMbYamJA3Qf-1)

Thanks CAIA team! Appreciate your collaboration with us on this :)

**Comment by jinaryu** [comment]
@kristinoletmuskat took a first pass at URLs and added them next to the Figma frames (link to one of them [here](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2961%3A29584&t=H0AWCB3U8Gt0nX1A-1) ) 

I had 2 questions, both listed in the corresponding frames. Would love to hear your thoughts! Thanks

**Comment by katherine-fung** [comment]
Hi @jinaryu, I'm going to start the content review of these designs earlier than anticipated, though I may step away from it if there are new developments with the 2 other projects we mentioned during our kick off call. I just want to note that any comments I'm leaving in the Figma file this week aren't final and still require A's review. 

cc @juliepedtke @nnicholas7 @shannonkford @aprocik1

**Comment by kristinoletmuskat** [comment]
Hey @jinaryu! I see those URLs, I have a few contextual questions and I think it might make sense to grab like 15 minutes to hash it out. I just sent an invite for this afternoon (you looked free on your cal) but feel free to reach out on slack if that doesn't work. 

Just jotting down some suburl ideas for when we chat:
.1: /mental-health-form-781/ (we put 'form' before the form number. Added mental health so its more human readable but I can be convinced that's too long)
.2: /mental-health-form-781-upload/ (remind me why we aren't uploading the form on this page?)
.3: /mental-health-support/ (this isn't part of the form technically right? this is like an added thing? Maybe we don't need form number?)

**Comment by katherine-fung** [comment]
@jinaryu @nnicholas7 @juliepedtke is there any research you can share that inform the draft content, or should inform the recommendations, for the PTSD/MST screens? 

cc @aprocik1 @strelichl

**Comment by juliepedtke** [comment]
Hi @katherine-fung ! There's lots of indirect research behind this. We reviewed past studies in [this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710425395956/4f0a397015bbcaadd1a421ed60e8d8e185cf1b12?wid=7-1710425509284), and have a summary at the top of the findings and principles we kept in mind for this redesign. There's also a section where we've laid out the previous form versions and what's been changed/added/removed.

We're currently planning research on the new designs - likely first a concept test pre-launch, accessibility testing in staging, and usability testing post-launch.

**Comment by EvanAtCoforma** [comment]
# Accessibility Design Review
## General Recommendations
For annotations, provide fieldset and legend annotations for the radio button groups to avoid any confusion in the development phase. The group label (the main question) and all the radio buttons within the group would be wrapped within the "fieldset" annotation. The group label and any hint text if available would be wrapped within the legend annotation.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129999082/685f18a3-06aa-403a-ada4-7830a0b27a3a)

## Screen Recommendations
### 0.1 - Option to Fill Out 0781
There is a significant amount of information on this page that a user would need to read/navigate through before getting to the main question for this screen. We are recommending to break down this screen into two separate screens, as this will assist in minimizing mental fatigue as the user navigates through the content. 

#### Screen One
The first screen could be a Yes/No radio button question asking if the veteran feels that they have a mental health condition and refer to the traumatic event and mental health additional info components. One of the additional components could be broken down into heading and body text (possibly the traumatic event component) to avoid additional tap stops prior to the mental health condition radio button question. 

#### Screen Two
The second screen would contain the "Would you like to provide a statement on your mental health conditions?" radio button question, along with the five-part process list. The list can be ordered before since it is static text and wont affect the tab order. 

### 4.2 - Upload Supporting Documents
The "How to upload files" text has the visual appearance of a heading, though is not annotated as a heading level. Also, the importance of a user knowing how to upload a file is high enough for a heading level to be designated to the text programmatically. Consider making this text a h3/h4 depending on the finalized heading hierarchy on the screen.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129999082/baf396da-3729-4abf-8f3c-9811321a6c5a)


Please reach out to me via Slack if you need more clarification about any of the recommendations above. Thanks!

cc: @jinaryu | @juliepedtke | @coforma-terry | @strelichl | @sara-amanda

**Comment by jinaryu** [comment]
@EvanAtCoforma thanks for the feedback! made the following changes:

- added fieldset and legend annotations for all fieldsets
- (0.1) I will follow up with you on Slack about this one
- (4.2) changed it to h4

**Comment by jinaryu** [comment]
**Notes from sync on additional forms option :**

- What is the primary task/mental model for a user filling out the 526?
  - Is it to fill out separate forms or submit one 'disability payments' package?
  - If the latter, ideally instead of forms going through individually, they'd go through as a "package"
- How does this work on the backend?
  - Will 0781, 4142 be a separate PDF and also show up separately in CST? Or as part of a "claim package"
  - How are buddy statements treated in the system? - mostly, treated as evidence.
  - only if you upload evidence for a specific claim in CST, it gets attached. Otherwise, it's shown separately
- CST requests
  - backend user creates request "i need your 4142 or buddy statement" this is how we create packages in CST
- IA problem - packages exist and aren't reflected cohesively
  - myVA - no sense of packages there
- Next steps
  - 686c has a pathway to go to 674 - look at this example
  - Kristin will raise this to Mikki and get back to team
  - Jina will bring this back to 526 team
  
  
![Screenshot 2024-06-13 at 10 35 16 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141759567/5e59c374-f9ad-4bc5-a75a-f46e927cb836)

**Comment by katherine-fung** [comment]
I'm tracking CAIA recommendations that haven't been implemented, in case we need to come back to them or refine them after user testing or syncing with OCTO's CAIA leads (this work relates to broader questions about form-within-form experiences, which are captured in ticket #88750).

Noting here that the product team has made several updates to the 0781 designs since CAIA first delivered our recommendations via the "[CAIA recommendations](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=3967-21045&t=5H4AnZAp6eLF0cbk-0)" Figma page on 6/24. Some of the recommendations here apply to those later updates. 

I'm also noting that we provided earlier recommendations for how to show when Veterans are completing the 0781 form online, while in the 526 form. We need more guidance on this from CAIA's OCTO leads, and will update the product team when we know more. 

cc @jinaryu @juliepedtke @nnicholas7 @rubensun @shannonkford @DanielleThierryUSDSVA @aprocik1 

| CAIA recommendation  | CAIA notes |
| ------------- | ------------- |
| **Avoid redundancies in the 0781 questions and the broader 526 form**.   |  |
| 1. Don't ask Veterans how they want to submit their medical records from private health care providers more than once. [Link to CAIA comment in Figma](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg?node-id=4612-126705#857047034)  | The 0781 designs currently ask how Veterans want to submit their medical records. The Veteran can then upload the records, or learn that they'll need to authorize the release of their records later on in the application. The broader 526 asks this question again. <br><br>Flow A: [first question](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-120368&t=5H4AnZAp6eLF0cbk-0), [second question ](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-126705&t=5H4AnZAp6eLF0cbk-0)<br>Flow B: [first question](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4696-79240&t=5H4AnZAp6eLF0cbk-0), [second question](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4696-84797&t=5H4AnZAp6eLF0cbk-0)<br><br>We think that the entire 526 flow should only ask this question once. i.e. if someone indicates that they've received treatment from private health care providers, we should tell them we're going to ask them how they want to submit the records later on, instead of asking this question twice.   |
| 2. Provide a single evidence section where Veterans upload the documents in the 0781 checklist, followed by other evidence. [Link to CAIA's original 6/24 recommendation](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=3967-21045&t=5H4AnZAp6eLF0cbk-0)  | We're aware that changes to the 526 are out of scope for this work. Also noting the trauma informed CoP group's recommendation to keep all the 0781 questions together within the 526. <br><br>But we're flagging that a single section for uploading evidence would help avoid redundancies around uploading evidence. Presenting multiple opportunities for Veterans to upload evidence - even if we try to distinguish between the types of evidence they should upload in each section - is tricky, because a single supporting document may count as supporting evidence for both a mental health condition and another condition the Veteran is claiming. <br><br>The two 0781 flow options currently offer these paths: <br><br>Flow A: Veterans see screens to identify and/or upload supporting documents about their mental health. After completing the 0781 questions, there are a few other screens, and then a "Supporting evidence" step where Veterans have to answer whether they have evidence to review, and identify the types of evidence. <br><br>- If Veterans have indicated they have evidence or medical records in the 0781 questions, they shouldn't have to answer the questions on [this screen](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-126754&t=CAB0iU1WYkWkcwaF-0). <br><br> - We believe a single evidence upload section would also decrease the need for Veterans to rely on the information alert to tell Veterans what evidence they've already uploaded earlier in the form.  <br><br>Flow B: Veterans see the "Supporting evidence" step to identify and/or uploading supporting documents for their entire claim. They may upload documents related to their mental health conditions. In "Step 4: Additional forms," Veterans see the 0781 questions about supporting documents related to mental health conditions. <br><br> - We've outlined our concerns about redundancy and alert fatigue (or content blindness) in [this Figma comment](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg?node-id=4546-69555#868334697). 
| **Follow the ["one thing per page"](https://design.va.gov/patterns/ask-users-for/a-single-response#design-principles) design principle**.   |  |
| 3. The team should reconsider the screen ["Permission to get your private medical records,"](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-122738&t=CAB0iU1WYkWkcwaF-0) which currently has more than one thing per page. If the team updates this screen, it may also need to update the "Mental health treatment" flow in the 0781 questions.  | This screen currently conditionally tells Veterans who had private health care providers they'll need to complete the 4142 later, and then asks the question "Do you have another --- to add?" <br><br>I've only seen the option to add another item on summary pages for list-loop responses, according to the design system. If Veterans who select private health care providers can't actually add an item in the list loop pattern, it may better to remove "a private healthcare provider" from [the checklist](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-120279&t=CAB0iU1WYkWkcwaF-0) that initiates the list-loop pattern. <br><br> Consider the [recommendation here](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg?node-id=4612-120279#875067169) (link to Figma comment) instead.  |
| **Explore alternatives to help Veterans understand their progress through a subform**   |  |
| 4. The product team should explore alternatives besides "Section X of Y" in subheaders to show progress through a subform.   | ["Section X of Y"](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-115038&t=5H4AnZAp6eLF0cbk-0) adds cognitive load alongside the stepper numbers. We haven't checked the use of the word "section" elsewhere in the 526, so it's possible the broader form may use the word "section" in different contexts.<br><br>We've noted the product team's comment that at least one testing participant has responded positively to the subheader so far. But we encourage the team to explore alternatives to helping Veterans understand their progress through the long 0781 subform - if this is currently out of scope, then later on.   |
| **Limit the form's reliance on information alerts and notes. Look for other ways to clarify flows where possible. Be cautious of alert fatigue/content blindness. **   |  |
| 5. Ask whenever there's an information alert or note in the 0781 questions: is there another way we can clarify this for Veterans, besides using an alert or note?  | One example of a place to update this is the note on the [conditional screen for "Behavioral changes"](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-119753&t=5H4AnZAp6eLF0cbk-0) if Veterans choose that they experienced traumatic events related to combat only. Here's [CAIA's recommendation for removing this note](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=4612-119753&t=YDfs7fH7YGkhLJMW-0).

**Comment by aprocik1** [comment]
Hey @rubensun! I know we've been collaborating on this work via Figma and Slack. If all the work is completed, can we close this ticket? Or, should we keep it open for any remaining near term support request?

**Comment by rubensun** [comment]
As we're going through engineering handoff we're identifying some areas that may need refinement.
If you're ok with us handling those separately, I'm good to close this out, however we will likely need at least another pass at a select set of screens / states.

**Comment by aprocik1** [comment]
@rubensun, thanks for the heads up. Let's keep this ticket open and use it to track those upcoming requests.

**Comment by rubensun** [comment]
Per @EvanAtCoforma 
Destructive actions performed will require post-action confirmations.
No additional support is needed at this time.

https://dsva.slack.com/archives/C053UDWMH7U/p1740409461881659?thread_ts=1738352995.287179&cid=C053UDWMH7U

**Comment by rubensun** [comment]
We have a few additional questions. I'm going to keep the ticket open until we complete our implementation work.

**Comment by rubensun** [comment]
We have a number of destructive action confirmations in our form that look something like this.

![Image](https://github.com/user-attachments/assets/fef51189-a965-4fcc-acdb-11453aa73ba8)

Here’s our understanding of how these alerts should behave:
### Steps to Confirming the Action

- User changes selection on the form page with option that would result in the destructive action.
- User hits continue
- (the modal fires)
- User presses yes to confirm the action
- User moves on to the subsequent page.

### Steps to Dismissing the Action

- User changes selection on the form page with option that would result in the destructive action.
- User hits continue
- (the modal fires)
- User presses no to cancel the action
- User returns to form page with focus on the continue action
- The user is free to change their responses before continuing.

What we wanted to confirm was the placement of the destructive action alert — on the subsequent page following the action being committed above the H2.

[See prototype](https://www.figma.com/proto/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=16649-63399&viewport=-5520%2C7357%2C1.05&t=o4ZQSyDkwnbkvKqq-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=16649%3A63399&show-proto-sidebar=1).

**Comment by coforma-jamie** [comment]
@rubensun the flow is really zoomed out and unusable :( what should I do? 

![Image](https://github.com/user-attachments/assets/5816e727-1f81-452d-9ebb-06ca841bf2a2)

**Comment by coforma-jamie** [comment]
@rubensun, thanks for helping me properly access the prototype! To summarize our conversation:
- For this pattern to be accessible, move focus to the alert (instead of the progress bar) after the user clicks "Yes, skip VA Form 21-0781" in the modal. This ensures that SR and keyboard users are immediately made aware of the results of the destructive action.
- In terms of usability, I think the placement is probably fine, but you might want to validate with users. I can think of two options for placement:
   1. Where you have it. Benefit - it moves users along more quickly
   2. On the previous screen, above "Finish this application later." Benefit - it gives users more control over their next steps (do they want to change their mind? Or take a break from filling out the form?)

**Comment by mistymg** [comment]
Closing out this epic. Juliana and Danielle addressed staging review findings (and I've added that ticket under this epic).
