### ISSUE TITLE
Copy of Map Upstream Services: Review EVSS

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80874]
## Issue Description
Because there is a need for an updated and comprehensive list of the upstream services that Vets API makes call-outs to, it is necessary to review the existing documentation and diagrams and updated or recreate the documents. 
They should be stored here (space **TBD**). 
The new documents should be reviewed by the cohort to ensure that there are no critical elements missing for EVSS 

Review [this document ](https://docs.google.com/spreadsheets/d/1cEBdUUqRW1cgVRLcbRUwOMhZewy9fRLU0gRGSITfuEc/edit#gid=803968964) for the particular data points that need to be captured for this Upstream Service. 

## Tasks
- [ ] Review existing documentation for EVSS 
- [ ] Review existing diagrams for EVSS
- [ ] Update existing documentation for EVSS
- [ ] Update existing diagrams for EVSS
- [ ] Archive existing documentation for EVSS; include URL in comments below
- [ ] Archive existing diagrams for EVSS; include URL in comments below

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [ ] Updated documentation and diagrams for EVSS used Platform Product upstream services that can be shared to all VA Platform stakeholders.
