### ISSUE TITLE
Copy of Map Upstream Services: Review Vets 360* (now VA-Profile)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80880]
## Issue Description
Because there is a need for an updated and comprehensive list of the upstream services that Vets API makes call-outs to, it is necessary to review the existing documentation and diagrams and updated or recreate the documents. 
They should be stored here (space **TBD**). 
The new documents should be reviewed by the cohort to ensure that there are no critical elements missing for Vets 360* (now VA-Profile)

Review [this document ](https://docs.google.com/spreadsheets/d/1cEBdUUqRW1cgVRLcbRUwOMhZewy9fRLU0gRGSITfuEc/edit#gid=803968964) for the particular data points that need to be captured for this Upstream Service. 

## Tasks
- [ ] Review existing documentation for Vets 360* (now VA-Profile)
- [ ] Review existing diagrams for Vets 360* (now VA-Profile)
- [ ] Update existing documentation for Vets 360* (now VA-Profile)
- [ ] Update existing diagrams for Vets 360* (now VA-Profile)
- [ ] Archive existing documentation for Vets 360* (now VA-Profile); include URL in comments below
- [ ] Archive existing diagrams for Vets 360* (now VA-Profile); include URL in comments below

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [ ] Updated documentation and diagrams for Vets 360* (now VA-Profile) used Platform Product upstream services that can be shared to all VA Platform stakeholders.
