### ISSUE TITLE
Copy of Map Upstream Services: Create and Update Documentation of EVSS

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#80883]
## Issue Description
We need a comprehensive list of the upstream services that Vets API makes call-outs to. Existing documentation and diagrams exist, but they're stale and outdated. The various sources of truth should be reviewed and an updated list needs to be created and documented. 

---
## Tasks
- [ ] Update EVSS existing documentation in ticket [80873](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/80873) 
- [ ] Review and Update any topology graphs in va-gov-sensitive
- [ ] Review and Update Confluence and Platform Website facing docs
- [ ] Update contact info for each service

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptance Criteria
- [ ] Updated documentation and diagrams for Platform Product upstream services that can be shared to all VA Platform stakeholders.
