### ISSUE TITLE
Update Slack Reminder and Calendly for Office Hours

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80896]
## Issue Description
Zoom link used in Slack Reminder and Calendly RSVP does not work and needs to be replaced.

---
## Tasks
- [x] Delete Slack Reminder for Office Hours in #platform-content channel
- [x] Create new reminder with updated working link
- [x] Update Calendly RSVP with working link

## Acceptance Criteria
- [x] Users will be able to join Zoom Office Hours using both the Slack Reminder and Calendly RSVP

## Screen Shots
<img width="781" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE5vQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efa6475c59d4b7553aaae1a3710bc3085b217f9c/Office%20Hours%20Reminder%20Slack.png" alt="Office Hours Reminder Slack.png" />

<img width="621" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a1263ad214ea1d261328b4898dab59ae3eb85ce/Screenshot%202024-04-16%20at%205.42.45%E2%80%AFPM.png" alt="Screenshot 2024-04-16 at 5.42.45 PM.png" />

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Work has been completed, moving to _done_
