### ISSUE TITLE
Announce New Date Stamp Process in Slack

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80899]
## Issue Description
A new process of adding a date stamp to new and updated Platform Website pages will be announced in the proper channel in Slack. 
Language should include "one-sprint grace period"

---
## Tasks
- [x] Compose message announcing this feature and pointing to [this page](https://vfs.atlassian.net/wiki/spaces/AP/pages/3065708550) for guidance
- [x] Post message in Slack channels 

- #vfs-change-announcements 
- #platform-team channel 

## Acceptance Criteria
- [ ] Date Stamp process will be announced in both Slack channels with instructions for adding this element
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/80899?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
Draft completed and shared with team. Awaiting feedback.

**Comment by BSmolensky** [comment]
After some discussion, we have decided to only post this announcement in the Platform-Teams channel. That post has been scheduled for 2pm today, April 25th. If it turns out that we need to post it in the VFS-Change-Announcement channel then we can copy and paste it there too.

**Comment by jknipes** [comment]
Work is completed, moving to _Done_
