### ISSUE TITLE
Can We Make Team Members Alternate Hosts in Zoom Office Hours Event? 

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80897]
## Issue Description
Currently only Joe Knipes can host Content Office Hours in Zoom. Need to change permissions to allow Brian Smolensky, Lauren Conrad, Jill Taylor and Cheryl Evans as alternate hosts, when Joe Knipes is not signed on to the meeting.

---
## Tasks
- [x] Test whether we can update Zoom permissions to allow alternate hosts:
 
## Acceptance Criteria
- [x] Determine whether everyone on Platform Content Team will be able to host Office Hours event in Zoom
- [x] Determination and Discovery notes added in comments section of this ticket
---

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Choices are:

1. create new Zoom meeting from scratch and add the alternative hosts
2. login to Zoom as an admin and enable co-hosting
Joe is not a Zoom admin, so we may have to go with choice #1

**Comment by jknipes** [comment]
![Screenshot 2024-04-23 at 3 46 10 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/f1fc2c44-47f5-4206-b2ab-59523792aa93)

**Comment by jknipes** [comment]
Determination: we are currently unable to schedule a future meeting allowing for alternate hosts.
