### ISSUE TITLE
Board Appeal Options Clarification

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#8090]
## User Story or Problem Statement
As a Veteran considering a Board Appeal, I need clear, high-level descriptions  of the three different options available to me so I can decide which to explore in greater detail. 

## Goal
Make it easier to identify and differentiate between Direct review, Additional evidence submission, and Hearing request. Then follow with details on options and timing. 
**See suggested copy from AMO and Board in attached Word document:** [https://app.zenhub.com/files/133843125/d7ead9ff-2a9f-4a63-b796-0a800aeea119/download]

---
## Tasks

- [ ] Alert platform team (May require 508 review, but not a full collaboration cycle. Scope is copy-only changes to just 3 pages.)
- [ ] Copy updated in Drupal and preview links circulated internally (Laura)
- [ ] Copy approved internally (Jen)
- [ ] Copy reviewed/edited (Randi)
- [ ] Preview links provided to platform team--508 review only (Laura)
- [ ] Preview links emailed to SMEs (Laura)
- [ ] Pages approved by SMEs (Fred Somers, AMO; Elizabeth Murphy, Board)
- [ ] Sign-off from platform team
- [x] Pages published (Randi):
          - [ ] Board appeals:  preview-prod.vfs.va.gov/preview?nodeId=3029
          - [ ] Contested claims:  preview-prod.vfs.va.gov/preview?nodeId=3030
          - [ ] Fiduciary claims:  preview-prod.vfs.va.gov/preview?nodeId=3016

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
Content updated on three pages:
- [ ] Board appeals:  preview-prod.vfs.va.gov/preview?nodeId=3029
- [ ] Contested claims:  preview-prod.vfs.va.gov/preview?nodeId=3030
- [ ] Fiduciary claims:  preview-prod.vfs.va.gov/preview?nodeId=3016
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lwalsh617** [comment]
@RLHecht @jenniferlee-dsva 
Could you please review content on the [Board appeal Drupal preview page](preview-prod.vfs.va.gov/preview?nodeId=3029), which I revised per feedback from Elizabeth Murphy and the Board? 
They want to leverage this same copy on the contested claims and fiduciary claims pages. Once we're happy with this page, I'll apply to those two pages. Thank you!
**Please note:** Board had asked us to change "Evidence Submission" to "Additional Evidence Submission." However on Form 10182, it is "Evidence Submission" so I did not make this change as I wanted to match the form.

**Comment by jenniferlee-dsva** [comment]
Hi Laura - I'm not able to upload my comments here, so I will Slack it to you on the PW channel.

**Comment by DanielleThierryUSDSVA** [comment]
Sure! @lwalsh617 I don't have Drupal access yet. Would you mind uploading a pdf of the page? Also, when do you need feedback by? Thanks!

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @DanielleThierryUSDSVA @RLHecht - I made Jen's edits. 
Danielle, I attached a PDF of the page here, along with SME feedback and Jen's feedback for reference. Thanks!
![preview-prod vfs va gov_preview_nodeId=3029 (1)](https://user-images.githubusercontent.com/53535663/80022449-13d11e00-84aa-11ea-9cee-0ebe7d48b0ae.png)
[Changes to Board Appeals-jl-comments.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4518700/Changes.to.Board.Appeals-jl-comments.pdf)
[AMO and Board reccos on Board Appeal content.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4518701/AMO.and.Board.reccos.on.Board.Appeal.content.docx)

**Comment by RLHecht** [comment]
@lwalsh617 I did a copy edit on the Drupal page for this. I changed references to "VA" throughout to "we," put in a few contractions and did some plain language fixes in a few places. Let me know if you have any questions!

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @RLHecht -- I took the copy from the Board Appeal page (thanks for the editing, Randi!) and cut-and-pasted to the contested claims and fiduciary claims pages per SME requests. Here are the Drupal preview links:
Contested Claims:  http://preview-prod.vfs.va.gov/preview?nodeId=3030
Fiduciary Claims: http://preview-prod.vfs.va.gov/preview?nodeId=3016
@stephorkandatx -- can you advise on next steps with platform team? I think all that they require is a look by Jennifer Strickland for any 508 issues that are a result of these content changes? 
Thanks, All!!

**Comment by lwalsh617** [comment]
Hey @jenniferlee-dsva - Thanks for the quick turn! The link to the fiduciary program is not new. It's actually on the site now. Fiduciary claim refers to an application to act as a Veteran's fiduciary. (If it referred to any claim filed by a fiduciary, that would mean, for one thing, the Supplemental Claim option would not be available for any type of claim.)

**Comment by lwalsh617** [comment]
@jenstrickland - Copy has been edited per SME requests on the following 3 pages so am sending them your way for 508 review:
- [ ] Board Appeals: preview-prod.vfs.va.gov/preview?nodeId=3029
- [ ] Contested Claims: preview-prod.vfs.va.gov/preview?nodeId=3030
- [ ] Fiduciary Claims: preview-prod.vfs.va.gov/preview?nodeId=3016
@stephorkandatx FYSA

**Comment by jenstrickland** [comment]
@lwalsh617 — I treated this as a 'casual' spot check, instead of an official review, thought it would be more helpful. If it is helpful for me to document the items for the three pages in issue tickets, let me know.

I did not include in the list the previously documented CMS template issues for these three items, as they are global issues to remediate.
- Aside must not be contained in another landmark
- Ensure landmarks are unique
- All page content must be contained by landmarks
- The heading "Can I request a Board Appeal" is an h3, but is not preceded by an h2. (component issue)
- The heading "Mark your calendar" is an h3, but is not preceded by an h2 — on both Contested Claims and Fiduciary Claims. (component issue)


<hr>

1. Board Appeals
    - I love the changes on the top part of this page. Very clear, and reads well in screen readers.
    - **Consider:** Under 3 Submit your appeal form, there are three options for submitting the appeal form. It would be helpful if these were presented as a list, so people using screen readers or those on mobile devices will recognize there is a list of three options. Does the CMS interface offer this functionality? If not, we can hop on a call to brainstorm a solution, looking at what's available in the interface. Let me know! 😄 
    - **Consider:** There's a paragraph just before What happens next? Consider placing this above the subway list for cognition.
    - **Should:** Option 1, 2, and 3 are coded as h4, but directly follow an h2 and are not preceded by an h3.

<hr>

2. Contested Claims
    - **Consider:** Under 3 Submit your appeal form — same as above
    - **Consider:** There's a paragraph just before What happens next? Consider placing this above the subway list for cognition. — same as above
    - **Should:** Option 1, 2, and 3 are coded as h4, but directly follow an h2 and are not preceded by an h3. — same as above

<hr>

3. Fiduciary Claims
    - **Should:** In the small grey box at the bottom, "Fiduciary and beneficiary programs" is an h4, but directly follows an h2 and not preceded by an h3. (Possibly a component issue, but I'm not sure)

<hr>
**Definition of Done**
- The Consider items would greatly improve the experience for screen reader users and those with cognitive impairments, reduce the possibility for error.
- The Should items really should be fixed, but may be addressed in the next two sprints, as they are a 508-defect-2 severity level.
- PM / content / design acknowledge feedback, document decisions made
- Accessibility specialist reviews and closes ticket

**Comment by lwalsh617** [comment]
Here's a link to a Slack thread in which Jen provided some clarification around dev-related feedback:
https://dsva.slack.com/archives/D013C0CJ0AY/p1588786425001500

**Comment by jenniferlee-dsva** [comment]
The items that she mentions above are component issues are not items we can fix for this. Accessibility needs submit those as global issues to be fixed at the component level in the  Design System. @lwalsh617 @stephorkandatx  

> (The heading "Can I request a Board Appeal" is an h3, but is not preceded by an h2. `(component issue)`
The heading "Mark your calendar" is an h3, but is not preceded by an h2 — on both Contested Claims and Fiduciary Claims. `(component issue)`

**Comment by jenstrickland** [comment]
Those issues are already ticketed as component level issues and assigned appropriately. Some are exclusive to the CMS template components, though, and will be the responsibility of Public Websites.  All are already ticketed.

**Comment by lwalsh617** [comment]
@RLHecht -- These pages are ready to publish. You copy edited them already. No changes have been made since your comment ^^^^^^^^^. Thanks!
preview-prod.vfs.va.gov/preview?nodeId=3029
preview-prod.vfs.va.gov/preview?nodeId=3030
preview-prod.vfs.va.gov/preview?nodeId=3016

**Comment by RLHecht** [comment]
@lwalsh617 These three pages are published! Moving to validate.

**Comment by RLHecht** [comment]
These pages are now live on the site. Closing ticket. FYSA @lwalsh617 @stephorkandatx
