### ISSUE TITLE
Change Internal Links to Open in Same Tab [Footer Ticket 80169]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#80917]
### Description
Each of the links on [this page](https://depo-platform-documentation.scrollhelp.site/research-design/) open new tabs (4/5/24). This is the opposite of behavior on VA.gov. The result on Platform Website is that users end up with several tabs after just a few clicks.
We need to determine the scope of work to update internal links on Platform Website.

## Tasks
- [x] Update links on [Research & Design page](https://depo-platform-documentation.scrollhelp.site/research-design/)
- [ ] Determine method for auditing PW for internal links opening in a new tab

## Acceptance Criteria
- [x] Research & Design page internal links updated to open in original tab
- [ ] Audit method determined
- [ ] Tickets created for Audit

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/research-design/

Slack Thread: [HERE](https://dsva.slack.com/archives/CL181NRJQ/p1712334837246499?thread_ts=1712062799.765229&cid=CL181NRJQ)

## Related ticket
[77453](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77453)

## Related research
[Comments section below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80917#issuecomment-2070004187)

**Comment by laucon** [comment]
I don't know if I should vote on this because it feels more like an epic than a task

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/80917?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by laucon** [comment]
Three things:
A. I looked at google analytics and it looks like there is no way to do this audit using google analytics. It's too big and complex.
B. Here is a list of steps we can do to complete this audit. Note that every 3 steps are connected. So steps 1, 2, & 3 are connected and then steps 6, 7, and 8 are connected and so on until step 19 which is separate.

    

1. Manually audit Getting Started docs for internal links
2.     See and write down which internal links in Getting Started docs open in new tabs
3.     Fix the problematic internal links in Getting Started docs
4.     Manually audit Research and Design for internal links
5.     See and write down which internal links in Research and Design docs open in new tabs
6.     Fix the problematic internal links in Research and Design docs
7.     Manually audit Analytics and Insights for internal links
8.     See and write down which internal links in Analytics and Insights docs open in new tabs
9.     Fix the problematic internal links in Analytics and Insights docs
10.     Manually audit Collaboration Cycle docs for internal links
11.     See and write down which internal links in Collaboration Cycle docs open in new tabs
12.     Fix the problematic internal links in Collaboration Cycle docs
13.     Manually audit Support docs for internal links
14.     See and write down which internal links in Support docs open in new tabs
15.     Fix the problematic internal links in Support docs
16.     Manually audit Developer docs for internal links
17.     See and write down which internal links in Developer docs open in new tabs
18.     Fix the problematic internal links in Developer docs
19.     Create new rules for how to link to internal docs and add those to a LB list or something

C. It sounds like Jill, Brian, and I have all worked on this ticket to some degree, so maybe we should assign it to the 3 of us so that we all get credit for having worked on it.

**Comment by laucon** [comment]
@jknipes I've been thinking about it a lot and if we're absolutely certain that the accessibility team would like all internal links to open in the same tab and still want that even if we can't do that with external links, then it might make sense to literally just go through docs manually and just change links one by one. As opposed to doing any pre-planning steps of figuring out which docs have those links.

Also, I think that almost all the links to other Platform docs within Research and Design need to be changed. There are very, very few internal links within Research and Design that are already correct. And any of the internal links inside Research and Design that are correct are internal links I might have added as part of an edit within the last month. Developer Docs might be more of a mixed bag.

**Comment by jknipes** [comment]
Recently announced plans by k15t to correct the behavior of **all** links has caused the team to pause work on this project: 
>Laura Parraga Gonzalez (K15t) commented:
HI Joe,
All links will open in the same tab after our improvement is implemented. No matter if they are internal, external, point to your Confluence, to the Viewport site or to any other website.
We are aiming to include the issue in our next release, hopefully at the beginning of next month.
Cheers,
Laura

cc: @EWashb

**Comment by jknipes** [comment]
Content Team has tested and verified behavior of all links. No further work needed. Closing this ticket as completed.
cc: @EWashb
