### ISSUE TITLE
Permanently Remove Veterans Choice Program from About VA menu

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8092]
## Goal 

- Permanently remove the Veterans Choice Program from the menu 
Note: it was temporarily disabled by Jen Lee, so it won't show in About VA Menu to users  - screenshot below

![image](https://user-images.githubusercontent.com/63361321/79494310-68772380-7fe8-11ea-87c9-0fd666c60096.png)

---
## Tasks
- [ ] permanently remove Veterans Choice Program from Drupal/CMS

## Acceptance Criteria
- [ ] Veterans Choice Program is not visible to users in the About VA Menu
- [ ] Veterans Choice Program is removed from Drupal

**Comment by MickinSahni** [comment]
@jenniferlee-dsva to confirm if is complete/can be closed.

**Comment by jenniferlee-dsva** [comment]
Looks like already completed. Closing. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/50878f75-b0fd-4362-8c27-4856b88c2113)
