### ISSUE TITLE
Language for timeliness of appointment wait time and satisfaction score data

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8093]
## User Story or Problem Statement
How might we accurately represent the timeliness of appointment wait time and satisfaction score data on Facility Locator and VAMC pages?

## Goal
Clearly and accurately present timeliness of:

- Veteran-reported Satisfaction Scores
- Appointment wait times
- Available services

## Objectives or Key Results this is meant to further
- Objective 2:  Deliver meaningful facility information 

## Current behavior: 

The following appear on facility detail pages within Facility Locator and on Pittsburgh VAMC pages:
- Veteran-reported Satisfaction Scores 
> Current as of June 20th, 2019
> Veteran-reported satisfaction scores come from the Consumer Assessment of Health and Systems survey, which measures satisfaction of nearly 150,000 Veterans across the U.S. every 6 months.

- Appointments
> Current as of April 2020

Services
> Services current as of April 16, 2020

![satisfaction.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/491ebc01-821e-4853-b3d0-fcd2e2998665)

![services.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/770ad32e-0ed6-47b5-8c79-23ac552355d0)

![appointment wait times.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bce16561-682f-44eb-9a94-e133f5c6d7d4)

![vamc wait times.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/fbe4f7a3-d680-40ba-b327-672020ae4c13)

---

## Tasks

Determine **Veteran friendly plain language** to present timeliness of wait times and satisfaction scores and include the link to FAQs for:

**Veteran-reported Satisfaction Scores** 
- Satisfaction is measured by surveying Veterans using the Consumer Assessment of Health Providers and Systems (CAHPS) Clinician and Group version 3.0. This is an industry standard survey used across healthcare. The numbers we report are the percent of Veterans saying "Always" or "Usually" to the following questions:
Urgent Care: In the last 6 months, when you contacted this provider's office to get an appointment for care you needed right away, how often did you get an appointment as soon as you needed?
Routine Care: In the last 6 months, when you made an appointment for a check-up or routine care with this provider, how often did you get an appointment as soon as you needed?
- Access scores reported here are for clinical encounters between October 2018 – March 2019 (edited) 
- VAMC pages currently have link to (https://www.accesstocare.va.gov/)

> "Learn more about Veteran satisfaction with access to care"

**Appointments**
- wait time data is updated weekly, based on a rolling 30 day average

**Services**
-refreshed nightly

## Acceptance Criteria
- [ ] content team approved recommendations for Veteran friendly plain language for the timeliness of appointment wait time and satisfaction score data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
