### ISSUE TITLE
Look into issue with some VSOfficers having more than one rep number

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#80935]
## Background
@jfinnerty13 noticed that a VSOfficer appeared twice in the search results. It turns out that rep has two different rep numbers. And it appears others do too. We need to look into this further.

Slack thread - https://dsva.slack.com/archives/C40B45NJK/p1713361371497449

Example search:
- VSO, ZIP 29526

Tiffany Ballen-Glover is the rep that's listed twice. So is Perry Williams. Chances are others must have more than one rep number too.

## Tasks
- [x] Ask Randy Trexler about this
- [x] Communicate to team that we'll have to update our search response to account for this

## Acceptance Criteria
- [ ] We have a clear understanding of what is going and what kind of next-steps are needed.

**Comment by oddball-lindsay** [comment]
There's a recent thread started by Jon in Teams, may be related

**Comment by holdenhinkle** [comment]
Randy responded:

There is an issue with reps having more than one registration number. He thinks this is a mistake. Here ran a query to see how prevalent this is and gave me the following numbers:
Reps that have...
2 registration numbers: 332
3 registration numbers: 7
4 registration numbers: 1

**Comment by holdenhinkle** [comment]
Notes from a DM convo with Jon:


Jonathan VanCourt
  11:29 AM
I can't think of a way to check that other than some sort of group by with first + middle + last in the query. Trying to do that in ruby for every search would be a real hit to efficiency (edited) 
11:30
What's the impact, 3-5% of individuals?
:+1:
1

11:32
We could do a super manual thing one time to add a multiple_registration_numbers boolean flag and just exclude those from the query results (edited) 
:thinking_face:
1



Holden Hinkle
  1:01 PM
What if we create a new table with the following columns:
registration_number
accredited_individual_id
The existing accredited_individuals table will only have once instance of each rep, no matter if that rep has more than one registration_number.
When we run a query join on the two tables. That would be efficient.
1:02
Now that we know reps can have more than one account, there’s a big problem with flagging rep’s bad contact info, and with a rep updating only one of their accounts.


Jonathan VanCourt
  1:13 PM
The existing accredited_individuals table will only have once instance of each rep, no matter if that rep has more than one registration_number.
The accredited_individuals table would have one entry per registration_number if the API returns one entry per registration_number
