### ISSUE TITLE
Investigate EVSS DocumentUpload error

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#80949]
## Issue Description
Investigate this DataDog alert: [EVSS::DocumentUpload has exhausted its sidekiq queue](https://vagov.ddog-gov.com/incidents/258)

`EVSS::DocumentUpload a9fc32373b1771c0ff050d57 died with error [{"key"=>"EVSS_15005", "text"=>"We were unable to complete your upload because the content of your file did not match the file extension. Please verify that the file extension is valiad with the file content. If you still have problems, call the VA at 1-800-827-1000 (711, if you use a TDD) for assistance. When you call, provide the following erro code: EVSS_15005.", "severity"=>"ERROR"}].`

---
## Tasks
- [x] Investigate cause of alert
- [x] Determine possible remediation approach
- [x] Create a remediation ticket to fix/handle the bug/error

## Acceptance Criteria
- [x] There is a remediation ticket that determines how to handle the error

**Comment by jerekshoe** [comment]
I determined that there are cases where the user can upload files where the extension is one of the accepted ones, but the content in the file would indicate that it should have a different extension. We should be checking for this in vets-api and returning an error synchronously.

**Comment by jerekshoe** [comment]
One example I found in prod was a document that had an extension of TXT, but the contents of the file was HTML. I was able to create a test file that reproduces the issue as well
[html.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/15097718/html.txt)
