### ISSUE TITLE
Identify Off-Boarding Tasks to Take On 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#80954]
## Description 
This ticket has been solely created to identify what off-boarding tasks we would need to take on, what the lift would be, and set sprints to the tasks needing to be accomplished (new tickets will need to be completed for these).
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify what tasks exist and if we should take them on
- [x] Write out the tasks and what is involved in taking them over [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3095625856/Offboarding+Task+Takeover) 
- [x] Discuss items on sprint planning so we can work them into our sprints 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
<img width="993" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2wvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77d74409cffe022453646292f77eed9d94253428/image.png" alt="image.png" />

**Comment by bdech** [comment]
PR to update off-boarding template

https://github.com/department-of-veterans-affairs/va.gov-team/pull/73005

**Comment by bdech** [comment]
Tier 1 Offboarding Responsibilities doc has been started [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3105554515/Tier+1+Offboarding+Responsibilities)

It's a shell at the moment, but will start filling with info starting with the next sprint.
