### ISSUE TITLE
Update Off-boarding To Include Zenhub Off-boarding Task

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#80951]
## Description 
The Platform Support Team has taken on the task of off-boarding zenhub users. Crurently, we are notified about off-boarded users in the #zenhub-information channel. However, some folks have fallen through the cracks if we are not notified. Therefore, we are adding a task to the off-boarding template to ensure the person is removed every time they are off-boarded. 

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Update the template [here](https://github.com/department-of-veterans-affairs/va.gov-team/pull/80933) 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Template has been updated here: https://github.com/department-of-veterans-affairs/va.gov-team/pull/80933

We are having ongoing discussions about taking on more onboarding tasks here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/80954
