### ISSUE TITLE
Research: Automate Zenhub Off-Boarding Notifications 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#80962]
## Description 
This ticket is allocated to only the research of automating off-boarding notifications. The goal is to use a script or other automation to identify when a user has offboarded. The Platform Support Team would then be notified and we would remove their access. 
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify if the task is technically feasible 
- [x] If technically feasible, identify the steps needed to accomplish the task
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Channel already created, closing! 

CC: @bdech
