### ISSUE TITLE
Portal Releases 2024 (April, May, June)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#80961]
## Issue Description
A quarterly epic to track releases and updates.

If a release ticket is required, it can be included under this epic allowing the original work Epic to close as all development items are closed.

## Tasks
- Note epics and super epics that release and close.
- [x] (S)Epic #[67970](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67970) [IA - PI1/24] Debt Portal Information Architecture Redesign - **Will close but no code release**
- [x] (S)Epic #[69652](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/69652) [FSR 3.0 - PI1/24] FSR/SW Form data lifecycle & Code cleanup
    - **Release Dates**
    - [X] Monday 05/06/24 - 10%
    - [X] Wednesday 05/08/24 - 25%
    - [X] Thursday 05/09/24 - 75%
    - [x] Monday 05/13/24 - 100%

- [x] Bug #[83421](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/83421) [FSR] Review page missing values
    - **Release Date**
    - [X] Monday 05/20/24

## Acceptance Criteria
- [x] At the end of quarter (~ June 26, 2024) this epic should be closed. 
---

**Comment by Dr-Pongo** [comment]
### Review page navigation release schedule:
| Date | Percentage |
| --- | --- |
| Monday 05/06 | `10%` |
| Wednesday 05/08 | `25%` |
| Thursday 05/09 | `75%` |
| Monday 05/13 | `100%` |

**Comment by Tom-Davis** [comment]
Closing - new releases will be recorded in the next quarters release Epic.
