### ISSUE TITLE
Burial | Auto Fill Profile Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#80975]
## Issue Description
_As an authenticated user of the burial form, I want my profile information auto-filled on the burial form. I also want any changes I make to my profile info in the form to write back to my VA.gov profile._

---
## Tasks
- [ ] Pull in profile information for authenticated users
- [ ] Allow profile changes to write back to VA profile
- [ ] Update front end to include language about profile edits writing back to VA profile. See [here](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated).

## Acceptance Criteria
- [ ] Profile info auto-fills for authenticated users
- [ ] Profile changes made within the burial form write back to VA profile
- [ ] The front end includes language alerting the user about the profile update behavior
---
