### ISSUE TITLE
Design | Profile | Direct Deposit | Add alert to tell users their account may be overridden if they have an open application in progress

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#80985]
## Background

If a user has an open claim, or pending edu benefit application, once it is approved, VA will override any DD info in their profile with whatever account information is in the application.

This means that if a user updates their DD info while VA is evaluating their application, it could be reverted back to something outdated without them really knowing.

For now, we need put an alert on the DD page (for all users) that informs people this could happen. Ideally, we'll also tell them what they can do about it but at the time of writing this ticket, we're not sure if they have any recourse.

### related artifacts/links
- [slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1713966702240269?thread_ts=1713366073.342689&cid=C909ZG2BB)
- [meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/meeting-notes/dd-account-override-sync.md) 
- [figma thread](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG?type=design&node-id=375-8435&mode=design#759588367)

## Tasks

- [x] [Get answer from Julie about what steps a veteran may be able to take](https://dsva.slack.com/archives/C909ZG2BB/p1713966702240269?thread_ts=1713366073.342689&cid=C909ZG2BB)
- [x] Create mock-up and review content with Laura
- [x] discuss outcomes w/PM and PO 
- [ ] create a ticket for FE work linking to Figma files
- [ ] link the design updates in the output section of this ticket 

## AC

- [ ] Veterans are aware that changes to their DD info in the profile may be overridden once their application is approved if a different account was used on the claim.

## Output 
- Link the final figma decision here

**Comment by mtcA6** [comment]
@andaleliz thoughts on the size of this effort?

**Comment by andaleliz** [comment]
Weird, I estimated it as a 5, seems like it's not showing up though. Do you see it on your end?

**Comment by andaleliz** [comment]
Moving to blocked since we can't move forward until we hear from Julie

**Comment by mtcA6** [comment]
@andaleliz i didn't realize you had picked this up in this sprint

**Comment by andaleliz** [comment]
@mtcA6 I didn't, since there's nothing we can do to move forward. Just trying to set us up so we can move forward in the next one.

**Comment by mtcA6** [comment]
@andaleliz in talking w/BGS about how to design the C&P indicators, they said the account information is input upfront before the claim is approved. I'm working to track down the gentleman that John Dell pulled in on the call who works in the C&P business line. I didn't catch his name.

**Comment by andaleliz** [comment]
@mtcA6 I'm not totally clear on the implications of what you shared in your last comment. Does that mean VA.gov bank account numbers would NOT get overwritten if a claim adjudicator entered a different account number than what was in the profile?

On a different note, I got guidance from Julie today so I can move forward once I get the green light from Travis.

>If they are not yet in receipt [of the benefits they've applied for] it would be best to contact the VA Call Center to provide that info over the phone.

**Comment by andaleliz** [comment]
@mtcA6 have heard any more that might help us move forward with this?

**Comment by mtcA6** [comment]
I spent some time chatting w Scott Fagan today and throughout the week about the process. Since it's manually managed the update may or may not be made it really depends on who is processing the claim.  

I think it's okay to proceed w/the copy changes we talked about but we do need to monitor from the backend when those values change so we can trigger an alert to the veteran that will prompt them to check the direct deposit information.

**Comment by andaleliz** [comment]
Sharing an update: I got the content reviewed and approved, but we're waiting to hear back as to whether this is a legitimate use case or not.

**Comment by andaleliz** [comment]
We've determined to leave this alone on the website.  Latest info from Julie [here](https://dsva.slack.com/archives/C909ZG2BB/p1718122213073289?thread_ts=1713366073.342689&cid=C909ZG2BB) and below:

>I've gotten conflicting information that leads me to believe the account used by claims processors varies, i.e. some use what's in the claim they're reviewing and some would use the latest set of payment instructions which may be payment instructions already in the system updated by the Veteran through VA.gov,
