### ISSUE TITLE
Staging Review for Facility operating status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8099]
## Steps to complete Staging Review: 

- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Notes
- DEPO and the COVID task force are expecting this enhancement to be released to production as soon as it is approved by the Facilities team. Implementation has already been impacted by a delay in data availability from CMS. Risk is low for this implementation as it is unauthenticated and a display for facility detail, not entirely new functionality. Any identified defects will be addressed iteratively. 
 - Usability testing is planned to evaluate workflow [#7520](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7520)

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- [x] [Facility-Level Alert Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-level-alerts/feature-brief.md)
- [x] Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-level-alerts/release-plan.md) 
- [x] Access information for the tool or feature in staging: (https://staging.va.gov/find-locations)
- [x] Link to your product test cases/test plan in TestRail with test execution logs ([learn more] [Facility level operational status test cases/test plan] (https://dsvavsp.testrail.io/index.php?/plans/view/245)
- [x] Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/62) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/63) reports in TestRail _for QA practice area review_
- [x] Link to your accessibility test cases:
  - **TestRail** [Facility operating status: accessibility sub-section ](https://dsvavsp.testrail.io/index.php?/suites/view/7&group_by=cases:section_id&group_id=81&group_order=asc) 
- [x] List of known issues: The following issues are not related to this particular work and were already known. Accessibility testing in staging confirmed they are still present
      - [#6184] content accessibility with zoom
      - [#5288] Previously identified during staging review of Urgent care MVP
      - [#3978] Previously identified during acessibility review for Mapbox

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): 
   - **Aricka Lewis**
   - **Gibran Rodriguez**

## Scheduling
Async

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by mmiddaugh** [comment]
Hi Megan, of those times, the best time is  4/21 at 11:30 Eastern

**Comment by mmiddaugh** [comment]
![image](https://user-images.githubusercontent.com/55411834/80030186-18470800-84a5-11ea-8a98-45cba85df7ad.png)

Created https://github.com/department-of-veterans-affairs/va.gov-team/issues/8299 for heading finding

@andreahewitt-odd @meganhkelley artifacts complete

**Comment by meganhkelley** [comment]
Thanks @mmiddaugh! 

Artifacts for this team's "staging review" (work is in prod) are complete, please have feedback documented by EOD Friday 4/24.
@pjhill @tzelei @jenstrickland @1Copenut @CrystabelReiter @emilywaggoner @peggygannon @mnorthuis

**Comment by meganhkelley** [comment]
Actually @mmiddaugh we're having trouble accessing the update to review — you've put a staging link here, but I thought you had said this would be in production for review? Can you please clarify?

**Comment by jenstrickland** [comment]
Team, use this url for review: 
https://www.va.gov/find-locations/?address=Washington%2C%20DC&context=Washington%2C%20District%20of%20Columbia%2C%20United%20States&facilityType=benefits&location=38.895%2C-77.0366&page=1&serviceType&zoomLevel=4

**Comment by peggygannon** [comment]
Hello @meganhelley @mmiddaugh I did an earlier content review on the Facility status. I have no additional content feedback on them. thx!

**Comment by CrystabelReiter** [comment]
@mmiddaugh This looks great from the VSP design side. No additional design feedback needed.
