### ISSUE TITLE
FE | Profile | Maintenance | Update cancel changes modal header

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#80994]
## Background
Laura from CAIA called out that the "Are you sure?" heading in our modals are outdated and instead we should say "Cancel changes?"

## Task

- [ ] Update the FE code to reflect the new header language in the component
- [ ] Let design know when this is going out so we can update Figma to match. 

## AC

- [ ] We're using the latest content in our cancel changes confirmation modal

**Comment by adamwhitlock1** [comment]
This has been deployed and can be validated on staging @mtcA6 

<img width="551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a377c6cc01cd452f983a3f3afc9dc0fbf8acd636/Screenshot%202024-05-07%20at%201.25.57%E2%80%AFPM.png" alt="Screenshot 2024-05-07 at 1.25.57 PM.png" />
