### ISSUE TITLE
Copy of 2024 Sentry Deprecation: Identify any Sentry/Slack Alerts that need to be migrated

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#81006]
## Issue Description
The Sentry tool will be deprecated. The 90 day notice of migrating the errors to DataDog is effective as of 4/5/2024.
This is work that is already in flight with @patrickvinograd 's team, with [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65929) 

## Tasks
- [ ] Identify any Sentry/Slack Alerts that need to be migrated
- [ ] Confirm with stakeholders the identified Sentry/Slack Alerts that could migrate to DataDog
- [ ] Migrate the identified Sentry/Slack Alerts to Datadog 
- [ ] Confirm that the Sentry/Slack Alerts were migrated to DataDog by testing

## Success Metrics
- [ ] _Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] Sentry/Slack Alerts are migrated to Datadog successfully and documented as such
