### ISSUE TITLE
Copy of 2024 Sentry Deprecation: Vets API Sentry to DataDog migration

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#81007]
## Issue Description
The Sentry tool will be deprecated. The 90 day notice of migrating the errors to DataDog is effective as of 4/5/2024.
This is work that is already in flight with @patrickvinograd 's team, with [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65929) 

## Tasks
- [ ] Refer to the approved Vets-API deprecation and migration discovery ticket for context ([81000](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/81000)) and Migration Guide for Vets-API ([81004](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/81004))
- [ ] Migrate the Vets-API Sentry to Datadog 
- [ ] Confirm that the Vets-API Sentry content was migrated to DataDog by testing

## Success Metrics
- [ ] _Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] Vets-API Sentry migrated to Datadog successfully and documented as such
