### ISSUE TITLE
VYE tool: Review

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#81012]
## Description
We need to review the new verify your enrollment (VYE) tool. Review notes from Mikki:

> I would suggest you plan to move forward with the profile page for now. With that page, we should review their page and modify the title so it is not labeled as a "profile". We also need to look at content additions to the Direct deposit and Change contact info pages to indicate that changes to those things for MGIB benefits should be done within the education tool.

I think Mikki is referring to these pages:

- [Change your VA direct deposit information](https://www.va.gov/change-direct-deposit/)
- [Change your address in your VA.gov profile](https://www.va.gov/change-address/)

**Resource:** [VYE tool wireframes](https://www.figma.com/file/B3Ds72oQhBZG1EtfffbAYk/VYE-Wireframes?type=design&node-id=42-4845&mode=dev) (Figma)

## Tasks
- [x] KF: Draft recommendations
- [x] AP: Review recommendations
- [x] KF: Share recommendations with product team

## Criteria
- [x] Content recommendations have been shared with product team

**Comment by katherine-fung** [comment]
Noting here that I just requested access to the Figma file for review.

**Comment by aprocik1** [comment]
@katherine-fung, I think we can:

- Simplify the response options to "yes" and "no" without "this information is..."
- Remove the "if you select no" content on the first screen, since it appears on the second
- Soften the note by removing the penalties (correct me if I'm wrong--you probably know more about this then me)

<details>
<summary>Here some edits to consider:</summary>

## Screen 1
Is this enrollment information correct?

- [ ] Yes
- [ ] No

**Note:** It's against the law to withhold information or provide incorrect information about your enrollment. (See 18 U.S.C 1001). Learn more about our privacy policy

## Screen 2: If no
You said your enrollment information for [generated month and year] isn't correct.

You'll need to contact your School Certifying Official (SCO) to update your enrollment information. Then, you'll need return to this tool to verify your updated information.

You can use our GI Comparison Tool to search for your school and find your SCO.

Use the GI Comparison Tool to find your SCO 
</details>

**Comment by katherine-fung** [comment]
Thanks @aprocik1! 

In light of what the team told us today about not including a "No" option (which after some reflection, I think staging review will flag as an issue to address, even if not launch blocking), do you think this copy makes sense in the current design? 


> Is this enrollment information correct?
> 
> [ ] Yes
> 
> **Note:** If the enrollment information on this page isn't correct, you'll need to leave this tool and contact your School Certifying Official (SCO) to update your enrollment information. Then, you'll need return to this tool to verify your updated information.
> 
> You can use our GI Comparison Tool to search for your school and find your SCO.
> 
> [Use the GI Comparison Tool to find your SCO](https://www.va.gov/education/gi-bill-comparison-tool/)
> 
> It's against the law to withhold information or provide incorrect information about your enrollment. (See 18 U.S.C 1001).

**Comment by aprocik1** [comment]
@katherine-fung, I think this content is fine for post-staging MVP. I'm curious to see if this is deemed launch-blocking. 

One edit: "GI Bill Comparison Tool"

And one musing: I wonder if we should change this to a statement instead of a question. Like this:

> - [ ] This enrollment information is correct
> 
> Note: If the enrollment information on this page isn't correct...

**Comment by katherine-fung** [comment]
Thanks @aprocik1! This is the content recommendation we'll give them for the version of the tool that doesn't require a "No" option. I've also updated the copy about penalties based on [the penalty notice in the style guide](https://design.va.gov/components/form/penalty-notice), and Slack conversation with Laura and Megan about how to proceed with it. 

> Is this enrollment information correct?
> 
> [ ] This enrollment information is correct
> 
> **Note:** If the enrollment information on this page isn't correct, you'll need to leave this tool and contact your School Certifying Official (SCO) to update your enrollment information. After they update your information, you'll need return to this tool to verify your updated information.
> 
> You can use our GI Comparison Tool to search for your school and find your SCO.
> 
> [Use the GI Comparison Tool to find your SCO](https://www.va.gov/education/gi-bill-comparison-tool/)
> 
> According to federal law, there are criminal penalties, including a fine and/or imprisonment for up to 5 years, for withholding information or for providing incorrect information (See 18 U.S.C. 1001).

**Comment by aprocik1** [comment]
Update: I left an update in the intake ticket saying that we can't complete our request because the Figma file is outdated.
