### ISSUE TITLE
[CST] We should add the "In Progress" label to decision review cards

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#81015]
## Background Context

We currently show the "In progress" label for initial claims that are in progress, but not for decision reviews. 

https://dsva.slack.com/archives/C056854SVT8/p1713365277295809

## Design

Current
<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU51QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3860ffc45ed7d7298c576eb3327147bc02e54c15/Screenshot%202024-04-17%20at%2010.45.55%E2%80%AFAM.png" alt="Screenshot 2024-04-17 at 10.45.55 AM.png" />

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Add "In progress" label to the card for decision reviews that are in progress in CST home page_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by skylerschain** [comment]
@jacobworrell Did this get worked?

**Comment by jacobworrell** [comment]
@skylerschain it did not
