### ISSUE TITLE
[EPIC] IA Tracker: Edu Migration

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#81024]
### Description
To track IA work to support Education Legacy Migration

### Links

- #78591 

### Timeline + Status

Batch 1: #82806 | Completed 🟢 
Batch 2: #85453 | Completed 🟢 
Batch 3: In progress 🟡  (no ticket because redirect was a PDF)

## Tasks
- [ ] Send email to stakeholders
- [ ] Get approval
- [ ] Confirm with PW team that we are good to move forward with redirect

**Comment by jennymayoco** [comment]
#### Batch 1 Tasks
- [ ] Send email to stakeholders
- [ ] Get approval
- [ ] Confirm with PW team that we are good to move forward with redirect

**Comment by jennymayoco** [comment]
https://www.benefits.va.gov/GIBILL/FGIB/VetTecTrainingProviders.asp (and all casing) | https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/ | 
-- | -- 


For this redirect from batch #1 - we are holding on implementing a redirect until September 30, 2024. From ticket notes :"Stakeholders feel that the legacy page can be redirected later this year with minimal impact."

**Comment by jennymayoco** [comment]
#### Batch 2 Tasks
- [ ] Send email to stakeholders
- [ ] Get approval
- [ ] Confirm with PW team that we are good to move forward with redirect

**Comment by jennymayoco** [comment]
Got the go ahead from Derek that batch 3 is ready to go - 
#### Batch 3 Tasks
- [ ] Send email to stakeholders
- [ ] Get approval
- [ ] Confirm with PW team that we are good to move forward with redirect

**Comment by jennymayoco** [comment]
Last redirect for this migration and batch 3:
Current URL | Redirect Destination or New URL | Status
-- | -- | --
https://benefits.va.gov/benefits/factsheets/education/pc.pdf | https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/ | Stakeholder reviewing

**Comment by jennymayoco** [comment]
Email update from Tammy: they are reviewing the content on this page `https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/`. In the meantime, they are okay with redirecting the PDF to a new R&S the Content team is working on.

**Comment by jennymayoco** [comment]
New R&S page might be published by EOW pending stakeholder updates.

**Comment by kristinoletmuskat** [comment]
Closing this ticket because the PDF redirect is in place
