### ISSUE TITLE
[PM, Research] VA.gov Onboarding: Team outreach

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#81027]
## Background
As we've worked on onboarding things, we've been approached by other teams who are working on similar initiatives. We already know VES is working on an onboarding/transition initiative. IIR reached out to us, and the VES Research Portfolio team let us know that a benefits discovery engine is likely in the works. We need to figure out who is working on what related to onboarding and how this all fits together.

---
## Tasks
- [ ] Identify teams working on onboarding / transition initiatives
- [ ] Identify teams working on solutions we've brought up as ideas to improve the transition experience
- [ ] Meet with these teams and understand the status of their work

## Acceptance Criteria
- [ ] We feel like we have a solid grasp on who is doing what in this landscape, and how we can work together.

**Comment by andaleliz** [comment]
@ajakabcin how do you feel about closing this out? I feel like we've completed as much as we can with this, and the ball is not in our court anymore based on the update we got from Chante yesterday.
