### ISSUE TITLE
Reproduce old Mural content in new VA Space

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81029]
## Purpose
The move from the Oddball Mural space to the VA Space means that all of our Mural boards are now archived.  

We'd like to have edit access to a number of these for future use.  We'll need to identify which boards we need, then copy their content into new boards in the new VA space, one at a time.

## Tasks
- [ ] Compile list of boards we feel like we need (note: we can always transfer a board later if we have a link)
- [ ] Make sure the SD "room" is set up in the new VA space
- [ ] Manually copy board content for each board

## Acceptance Criteria
- [ ] All boards in list have new counterparts in a SD room within the VA Mural space
