### ISSUE TITLE
Generate PDFs for Disability Rates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8103]
## User Story or Problem Statement
As a user of VA.gov, I need to be able to access rates from prior years, so that I can review previous data.

We are limiting the number of years we represent historical rates data, down to 3. For this year, we will display an archived copy of 2019 (effective rate Dec. 1, 2018), and links to 2 PDFs - one for rates effective Dec. 1, 2017 (ie the 2018 year rates?), and one for rates effective Dec. 1, 2016 (ie the 2017 year rates?)

Confirm the appropriate years are being targeted with this work during grooming

## Tasks
- [ ] Create PDFs of the Rates for Disability, for 2018 and 2017 (from the legacy pages)
- [ ] House PDFs in Drupal (if this is an issue, let's work through a different solution)
- [ ] PDFs become accessible to the user on the Disability Rates, marked as the year they represent (2018 or 2017)
- [ ] Links to legacy pages at the bottom of Disability Rates for 2018, 2017, 2016, 2015, etc. are all removed (no longer needed when the PDFs are available)

## Acceptance Criteria
- [ ] Disability Rates PDFs for 2018, 2017 are housed in Drupal
- [ ] 2018 Disability Rates PDF (generated from the 2018 legacy rates page) is accessible on Disability Rates, under Historic Rates
- [ ] 2017 Disability Rates PDF (generated from the 2017 legacy rates page) is accessible on Disability Rates, under Historic Rates
- [ ] Clicking the 2018 Rates PDF (Rates Effective Dec. 1, 2017) will make the PDF available/downloaded/downloadable for the user (talk to team about the default action)
- [ ] Clicking the 2017 Rates PDF (Rates Effective Dec. 1, 2016) will make the PDF available/downloaded/downloadable for the user (talk to team about the default action)
- [ ] The links to the current Historic Rates for 2018, 2017 PDFs are housed on the pages under Historic rates
- [ ] Links to rates pages on the legacy site are removed under Historic Rates

**Comment by stephorkandatx** [comment]
Closing this - we are moving away from the PDF strategy
