### ISSUE TITLE
SPIKE | 686 Updates | Scope Schema Updates

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81045]
## Issue Description
_We will be updating the 686/674 form flow to replace depreciated v2 design patterns with new v3 patterns and align the online form flow with the most recent 686 and 674 pdfs. Before starting form updates, we need to determine the scope of schema updates needed, so we can effectively plan for the first release._

---
## Tasks
- [ ] Determine all vets-json-schema definitions needed
- [ ] Determine if the form needs new schema
- [ ] Determine if the form can use an existing schema

## Acceptance Criteria
- [ ] Understand vets-json-schema definitions needed
- [ ] Understand if new schema is needed
- [ ] Understand if form can use existing schema
---
