### ISSUE TITLE
686 Updates | v2 Flipper

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81048]
## Issue Description
_Configuring flipper to toggle between v1 and v2 of 686/674 form flow._

---
## Tasks
- [ ] Configure flipper
- [ ] Merge and confirm it's working as expected
- [ ] Test flipper in staging and below

## Acceptance Criteria
- [ ] Flipper toggles between v1 and v2 of form flow
---
