### ISSUE TITLE
Add step to sign up for VA Mural to Governance Onboarding

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#81046]
## User Story
As a new team member on Governance, I want to ensure I have access to the necessary tools so that I'm able to do my job correctly.

Assignee: @briandeconinck 
Peer Reviewer: @shiragoodman 

## Description
Platform no longer has a dedicated Oddball/Adhoc Mural account. Instead, all teams supporting Platform are asked to create mural boards using the VA Mural instance. We should add this step to our onboarding so any future new team members are all set to provide support. 

## Impacted Artifacts
[Governance onboarding doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding)

## Tasks
- [x] Add a step for creating a VA Mural account
   - [New section for Mural](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding#Mural)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] New Governance team members are instructed to create a VA Mural account

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
added to sprint 4/22

**Comment by shiragoodman** [comment]
@briandeconinck this is up to date. Feel free to edit the onboarding doc directly. Thanks!

**Comment by briandeconinck** [comment]
@shiragoodman Ready for review! [New onboarding section for Mural](https://vfs.atlassian.net/wiki/spaces/PPST/pages/1953169694/Onboarding#Mural)

**Comment by shiragoodman** [comment]
@briandeconinck added 1 comment. Otherwise looks good! you can close this out

**Comment by briandeconinck** [comment]
Closing as complete!
