### ISSUE TITLE
Create Clamav Error Alert

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#81047]
### Summary
Previous anomaly ClamAV monitors were no longer working. The existing ClamAV monitor should be replaced with a log monitor.  Each pod should not have more than 10 warnings per day, depending on weekends and deployment time.

Monitor Type: Logs
Search Query: service:clamav status:error
Rollup: 1 day
Method: Avg
Alert: > 6
Aggregation: Simple Alert

Normal ClamAV Warning Behavior over the weekend
<img width="1098" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE56QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e4d55615393c9a7e946ff4de8d365d247d2013a/Screenshot%202024-04-18%20at%2011.14.45%20AM.png" alt="Screenshot 2024-04-18 at 11.14.45 AM.png" />

ClamAV Avg Warnings Over the weekend
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWR6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22f8af9d930ef5b7470ca680260bf9a94f9d9d19/Screenshot%202024-04-18%20at%2011.21.14%20AM.png" alt="Screenshot 2024-04-18 at 11.21.14 AM.png" />

### Tasks

- [ ] Create monitor in UI
- [ ] Create terraform file
- [ ] Ensure terraform was successful

**Comment by rjohnson2011** [comment]
Finished creating DataDog monitor & alert. Tested out alert in platform-cop-be-notifications support channel
https://dsva.slack.com/archives/C039HRTHXDH/p1716993253782609

Built out corresponding terraform file and created PR -> https://github.com/department-of-veterans-affairs/devops/pull/14375

**Comment by jennb33** [comment]
From Stand-Up on 5/29/2024:
- lower threshold to 5
- remove alerting mechanism from Ryan's monitor
- Adjust composite monitor to account for Ryan's monitor

**Comment by jennb33** [comment]
@rmtolmach noted that we need to verify that the alerts are going to go off, @rjohnson2011 is verifying that the alerts will go off at the appropriate time.

**Comment by rjohnson2011** [comment]
Terraform applied and merged -> https://github.com/department-of-veterans-affairs/devops/pull/14375
