### ISSUE TITLE
Distribute offboarding duties to Tier 1 support

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#81053]
## Issue Description
Offboarding is mostly the responsibility of the DevOps CoP, but many steps in the offboarding tickets don't require the specialized knowledge or permissions of a DevOps engineer. They are items the Tier 1 Support team can do. 

## Tasks
- [x] Brandon to discuss with Alyssa
- [x] Rebecca to bring up with Clint
- [x] Rebecca to bring up at the DevOps CoP meeting
- [x] Meet with Tier 1 to walk through the steps.
- [x] Where required, grant elevated access to the tools (and invite to private slack channel)
- [x] Edit [the documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member) (and maybe [this doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2425552908/DevOps+Support+Responsibilities), too).
- [x] Put up PR to edit the offboarding template (see the AC section of commit https://github.com/department-of-veterans-affairs/va.gov-team/commit/a71b0df1d6cde02f217087f5d910867e7c0b6542. Or https://github.com/department-of-veterans-affairs/va.gov-team/pull/73005).
- [x] Merge offboarding template

## Success Metrics
Tier 1 knows how to process offboarding tickets and DevOps support isn't confused about the change. 

## Acceptance Criteria
- [x] All tasks are checked off
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
Talked to devops cop on 4/18. They were all for it. Moving ahead!

**Comment by rmtolmach** [comment]
Meeting set up for Thursday 4/25

**Comment by rmtolmach** [comment]
Brandon grouped Tier 1 offboarding instructions here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/3105554515/Tier+1+Offboarding+Responsibilities. DevOps instructions are in their same spot.

**Comment by rmtolmach** [comment]
Met with Tier 1. Handoff done!
