### ISSUE TITLE
Update IC documentation with DataDog Instructions

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#81068]
## Description 
Following the most recent string of major incidents, OCTO-DE has asked the team to look into using DataDog incident management for communication and post-mortem purposes. The team will need to update the documentation to support this. 

---

## Definition of Done
DataDog Incident Management walkthrough completed and document reflects major steps necessary
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Update IC Playbook
- [x] Discuss updates with team
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Unplanned sick time, unable to get to work. Will put in backlog for now.

**Comment by alyssagallion** [comment]
Closed duplicate ticket. And moved this into current sprint to replace it.

**Comment by alyssagallion** [comment]
@lindsay-insco Can you document where you are at on this ticket here? Thanks!

**Comment by lindsay-insco** [comment]
https://vfs.atlassian.net/wiki/spaces/PTST/pages/3166405005/Datadog+Incident+Management Document approved by team, added to spreadsheet, and published.
