### ISSUE TITLE
Off-Boarding Responsibilities Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#81078]
## Description 
We were able to define the tasks needed to take on more responsibilities during the off-boarding process. You can see additional information on what we found [here](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/80954). 
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add pages to update here
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
https://vfs.atlassian.net/wiki/spaces/PTST/pages/3105554515/Tier+1+Offboarding+Responsibilities
