### ISSUE TITLE
[FSR] - Implement Expenses Endpoint Response for Streamlined Calculation

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#81070]
## Description

Update streamlinedDepends.js calculations to use back end responses in order to determine streamlined vs full fsr status.

## Tasks
- [ ] calculateDiscretionaryIncome function uses BE response for SW/FSR logic
- [x] transform calculations untouched so that FE still calculates for submission

## Acceptance criteria

- [ ] calculateDiscretionaryIncome function uses BE response for SW/FSR logic
- [x] transform calculations untouched so that FE still calculates for submission

## Testing
- [ ] Logged in and able to submit SW and Full FSR
- [ ] All tests pass

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

**Comment by OptionSelect** [comment]
Might have put this one into the wrong epic, I noticed it didn't have one but didn't want it to be missed in planning!

**Comment by OptionSelect** [comment]
Pulled in late into current sprint.

**Comment by OptionSelect** [comment]
Still working on this. Been fighting back end run issues. 

[Platform support thread here](https://dsva.slack.com/archives/CBU0KDSB1/p1715096689164909?thread_ts=1715088080.233049&cid=CBU0KDSB1)

**Comment by OptionSelect** [comment]
Rolled because it was pulled in late and back end was broken temporarily. We're close to finishing this one up!

**Comment by OptionSelect** [comment]
PR up awaiting review.
