### ISSUE TITLE
IPP - Create a flow alternative pathways post MPI search

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#81071]
As a Proofing Agent, I need an alternative pathway if I cannot find the Veteran on MPI. Needs to be acknowledged before we collect and verify real PII in Pilot 2 (late July).

## Tasks

- [x] Meet w/ Porta in identity AMA to capture flow on 4/26
- [x] share flow with design team async or in a huddle on 5/1
- [x] follow up w/ Porta on 5/3 to review flow (and possible script) before adding it to service blueprint

## AC
- [x] create a user flow

**Comment by skirkman16** [comment]
Next steps for ticket: 

- add details of the flow to the service blueprint
- create guidelines for scripts or steps that Proofing Agents will to follow to work around this issue
