### ISSUE TITLE
Follow up w/ PCT about what space the FDG should be put in

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81079]
## Purpose
There remains some unanswered questions about where the space should go, largely due to the lack of having a space for overarching organizational guides or items such as the FDG.

PCT may need to check w/ other SMEs or stakeholders on permissions for ideas we'd like considered.  In the meantime, we'll need somewhere to put it for our soft launch.

-Dan mentioned possibility of clickable links within each card on Platform Docs site.  Said that was a format that might be possible.  Do we know if this is indeed an option?

## Tasks
- [x] Reach out to PCT to establish when we'd want to hear back on where to put this thing
- [x] Present findings to PCT
- [x] Get their suggestion on what is viable for now:  
- PCT agreed w/ options provided by SDT
- [x] Team review and direction decision on location
- SDT decided to put landing in Developer Docs space, as the light item on the left rail, due to lack of a strong location option.

## Acceptance Criteria
- [x] A space is agreed upon

**Comment by twoangstroms** [comment]
This will roll over to next sprint to give PCT time to confer and get back to us
