### ISSUE TITLE
[Design] Adjust large icon appointment card component in the MHV Library Figma file

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81089]
## Tasks

- [ ] Adjust large icon appointment card component in the MHV Library Figma file. The reason for adjusting it is because we needed to make some changes for the pre-check-in detail page for VVC, CVT and Phone. The following links are detached components. So, we'll want to adjust the component in MHV Library Figma file first. 
     - [pre-check-in in person detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-17716&mode=design&t=Yv8SXWdB9JWa2PMh-4)
     - [pre-check-in phone detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-20615&mode=design&t=Yv8SXWdB9JWa2PMh-4)
     - [pre-check-in CVT detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=2053-5236&mode=design&t=Yv8SXWdB9JWa2PMh-4)
     - [pre-check-in VVC or video at home detail page](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-22891&mode=design&t=Yv8SXWdB9JWa2PMh-4)
- [ ] Redo those 4 appointment detail pages using the updated component from MHV Library Figma file. 

## AC

- [ ] Component in MHV Library is updated
- [ ] Frames are updated in Production Figma file for pre-check-in appointment detail pages

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/81089?planning-poker) with Zenhub @zach-park
