### ISSUE TITLE
[CDP] Manage VA Debt Redirect While Logged In Does Not Stay on Landing Page

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#81085]
## Description
After logging in and attempting to navigate back to the landing page through the breadcrumbs by clicking Manage Va Debt, we are temporarily sent there before being bounced back into the summary page by the redirect logic.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2wwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a7bb0e2b604ef71bbf455d05dd608791b90435b/Screen%20Recording%202024-04-18%20at%202.48.31%20PM.mov)

## Tasks
- [ ] Prevent re-nav from landing page for logged in user attempting to go to landing page

## Acceptance criteria

- [ ] Re-nav prevented or confirmed cannot be done by higher powers (VFS-Frontend/Platform etc)

## Testing
- [ ] Log out and make sure post log in landing page sends to summary
- [ ] Click manage va debt and make sure we aren't sent back to summary after visiting landing page

**Comment by OptionSelect** [comment]
Redirect initially implemented by [this pr] (https://github.com/department-of-veterans-affairs/vets-website/pull/28830/files)

**Comment by OptionSelect** [comment]
Question thread posted for guidance from greater FE team [here](https://dsva.slack.com/archives/C5HP4GN3F/p1713546469159299).

**Comment by OptionSelect** [comment]
Platform support thread created [here](https://dsva.slack.com/archives/CBU0KDSB1/p1713803555617409)

**Comment by OptionSelect** [comment]
Re-reached out in both of my threads to see if anyone has any final thoughts before we move forward under the assumption that this behavior is not something our system is able to account for and reversing the authenticated redirect boolean.

**Comment by OptionSelect** [comment]
Per convo with Megan (and lack of responses in platform thread) repurposing to remove breadcrumb as our serviceable solution.

**Comment by HeatherRienks** [comment]
Thanks for the updates!
