### ISSUE TITLE
[ANALYTICS] Initiate Planning meeting regarding VISN-19 analytics approach [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8108]
## User Story or Problem Statement
As a BA, I must have a full understanding of areas of research and data mining, so I can better understand the LOE and approach of using the data for automation and input.

## Goal
_Perform initial page testing, review, initial Accessibility scan with AXE-Coconut _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Tasks
_Complete review of VISN-19, Systems and clinics and estimate ROM:_
- [ ] Rocky Mountain VISN Review
- [ ] Systems that will be reivewed
- [ ] Clinics and level of data available
- [ ] Determine approach in data collection and level and process to proceed.

## Acceptance Criteria
* Rocky Mountain VISN Review
* Systems that will be reivewed
* Clinics and level of data available
* Determine approach in data collection and level and process to proceed.
