### ISSUE TITLE
Add missing application saved message 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#81090]
## Value Statement
**_As a_** Veteran
**_I want to_** be confident that my form is saved on every change
**_So that_** I don't have to worry if I lose internet connection

## Background Context

With the previous form progress bar, a message "Your application will be saved on every change. Your application ID is #" was visible at all times below the progress bar.

Previous:
<img width="746" alt="Your application will be saved on every change. Your application ID is 23 - this is shown below the older form progress bar" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/3e499e7b-5358-4051-b22a-7c58150dcbfa">

With the progress bar web component, there isn't any extra content below.

Current:
<img width="705" alt="progress bar with step x of y showing only" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/4093f6d7-1f7e-4de1-937a-fb01c604cae3">

This _shouldn't_ need to make any changes to the `va-segmented-progress-bar` itself, just the code that renders the progress bar.

If we do [add the in progress message below the web component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/FormNav.jsx#L149-L158), the spacing is a bit off
<img width="707" alt="Your application will be saved message appears with lots of spacing below the progress bar web component" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/136959/72afce16-31a4-41be-be15-564952728e1e">

```diff
      {!hideFormNavProgress && (
+       <>
          <va-segmented-progress-bar
            total={chaptersLengthDisplay}
            current={currentChapterDisplay}
            uswds={v3SegmentedProgressBar}
            heading-text={chapterName ?? ''} // functionality only available for v3
            name="v3SegmentedProgressBar"
            {...(v3SegmentedProgressBar ? { 'header-level': '2' } : {})}
          />
+         {inProgressMessage}
+       </>
      )}
```

## Design and Build Notes

<img width="975" alt="Screenshot 2024-05-20 at 4 31 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/f28022c8-5b71-4a90-b921-6a7830222fc2">

There should also be a 32px space between this item and the heading below it.

## Acceptance Criteria
- [ ] Content reviewed by CAIA
- [ ] Saved on every change message with application ID message is restored
- [ ] All tests passing

## Tasks
- [ ] Add back the saved on every change message with application ID
- [ ] Add/update unit tests
- [ ] Update e2e tests

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Conversation started with Platform, Forms team might pick up this work instead https://dsva.slack.com/archives/C01DBGX4P45/p1713548605291229

**Comment by eileen-coforma** [comment]
@saderagsdale @Mottie Design and design notes have been added to the ticket.

**Comment by Mottie** [comment]
Simple forms team is prioritizing this work in their sprint.

**Comment by shaunburdick** [comment]
Not planned
