### ISSUE TITLE
[CONTENT] Review and determine best strategy for writing and cloning content over future VISNs [Content]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8109]
## User Story or Problem Statement
As a Content writer, I must have a full understanding of areas of writing, so I can better understand the LOE and approach of using the data for automation and input.

## Goal
_Perform initial review of future SYSTEM writing _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Tasks
_Complete review of VISN-19, Systems and clinics and estimate ROM:_
- [x] Rocky Mountain VISN Review
- [x] Systems that will be reivewed
- [x] Clinics and level of data available
- [x] Determine approach in data collection and level and process to proceed.

## Acceptance Criteria
* Rocky Mountain VISN Review
* Systems that will be reivewed
* Clinics and level of data available
* Determine approach in data collection and level and process to proceed.
