### ISSUE TITLE
[QA] 10-10EZ - Reg Only MVP: Validate all content & formatting

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#81104]
## Benefit to the Veteran
By validating the UI content and format changes, we can confirm that the Veteran experience will be consistent with VA.gov and our intended design.

## Background
As part of the Reg Only MVP, we want to reorganize the pages for Authenticated and Unauthenticated users, so that they are prompted with the Registration alert early and avoid completing too much of the form before being redirected to call the Health Enrollment center.
We also want to address the alerts on the pages, including Short Form alerts, so that they display appropriately.

We need to validate that the content and format changes have been made to align with the designs.

#### Resources
- [Reg Only GH folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Registration)
- Design ticket #80831  
- [Figma Designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=86-36817&mode=design&t=yrvuA6rkae2fq2d7-0)

## Tasks
- [x] Review all screens against design files, looking for:
     - Typos
     - Extra spaces, and space around components
     - Content & field alignments to the page
     - Missing content
     - Unintentionally added content (ex: double words)
- [x] Document any findings in the comments
- [x] Determine if a new ticket is needed for the findings

## Acceptance Criteria
- The 10-10EZ content and format has been reviewed and all findings addressed (if any)

**Comment by allanto-ah** [comment]
@longmd Issue 1:

For Authenticated users, on the new register only pages, I don't see the saved in progress alert, but in Figma, it shows that there is. Should we be seeing the saved in progress for the new register only pages?

<img width="1461" alt="Screenshot 2024-08-28 at 9 16 01 AM" src="https://github.com/user-attachments/assets/d4ba2061-3e49-4cfa-92a4-ebc209e4d548">

**Comment by longmd** [comment]
@allanto-ah , we should not. Where those pages live for auth users, there is no option for SIP. That didnt get pulled all the way out of Figma.

**Comment by allanto-ah** [comment]
@longmd Issue 2:

On the page where the user selects if they want to register or enroll in full benefits package, in the collapsible drop-down link, there seems to be line breaks (according to Figma) that are missing between the sentences (shown in red arrows in screenshot).

<img width="1455" alt="Screenshot 2024-08-28 at 9 05 57 AM" src="https://github.com/user-attachments/assets/998bd37d-dd48-4fe3-bc3f-289ccce11a8b">

**Comment by longmd** [comment]
The reported issue has been updated and validated in the PR referenced above.
