### ISSUE TITLE
Add Who, What, Why Format to "Summary of Request" on Tickets to Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#81106]
## Description 
We recently noticed that a lot of ticket submissions are either missing information or there is too much information provided by ticket submitters. To reduce the overwhelm or to increase the information provided, we want to add a requirement in our documentation that each person provide the:

- Who
- What
- Why

Writing structure for each ticket. 
---

## Definition of Done
All tasks below must be complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Set up a chat with Alyssa to discuss the scope and any questions you may have on this ticket
- [x] Update the [Getting Help from the Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack#GettinghelpfromthePlatforminSlack-Step2:Enteryoursupportrequest) documentation with an overview of who, what, why structure ([specifically number 3 of this section](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack#GettinghelpfromthePlatforminSlack-Step2:Enteryoursupportrequest))
- [x] Add a step to Support Best Practices (and any other related documentation) noting that we are asking for this information so that Tier 1 folks know to reiterate this message in tickets when it is not provided
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Work complete. Closing!
