### ISSUE TITLE
[FE] 10-10EZ - Reg Only MVP: Update UI with new content and alert

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#81103]
## Benefit to the Veteran
By updating the 10-10EZ to reflect the proposed user flow and displaying alerts in a timely and logical manner, we will reduce confusion and burden for the Veteran completing the application.
The Veteran will be better informed about the actions to take to Register for service connected care only, rather than enrolling in the full VA health care benefits package.

## Background
As part of the Reg Only MVP, we want to reorganize the pages for Authenticated and Unauthenticated users, so that they are prompted with the Registration alert early and avoid completing too much of the form before being redirected to call the Health Enrollment center.
We also want to address the alerts on the pages, including Short Form alerts, so that they display appropriately.

### Resources
- [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487582087/34c3dab41845b8a2ca33afa97e05671703ca8395?sender=uadf1ed7fe7c76f0914967329) (v2 option)
- [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=3025-106249&mode=design&t=dP0IHGHa1YNy0FY8-0)
- [UX github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Registration/ux)

## Tasks
- [x] Determine best approach for conditional displays of the Compensation question and Enroll/Register question
     - [x] Document the decision
- [x] Update the UI to reflect the user flow for Authenticated and Unauthenticated users
- [x] Update alerts to display in the appropriate pages

## Acceptance Criteria
- UI is updated and ready for QA testing

**Comment by hdjustice** [comment]
need corresponding Cypress ticket

**Comment by longmd** [comment]
@aagosto90 , @hdjustice , do either of you have an issue of doing a small initial iteration to perform the content and formatting updates for the personal information page and release that ahead of adding the other pages here? I think that would be a good update to have out there while the rest of this is under development.

**Comment by hdjustice** [comment]
@longmd I have no concerns with that.  Do you want me to write up a ticket for it?

**Comment by longmd** [comment]
@hdjustice , I don't think we need one. It would just be its on PR on this one.

**Comment by longmd** [comment]
@aagosto90 , [here is the Review Instance link for your review](http://8992ad2ab6be3d9559642350ff53c46c.review.vetsgov-internal/health-care/apply-for-health-care-form-10-10ez/).

**Comment by longmd** [comment]
@hdjustice / @luis-simauchi , do we have any interest in adding a GA event to make it easier to track how many folks hit the Reg Only path and get the alert?

**Comment by hdjustice** [comment]
Yes, actually.  That would be great.  Do you want another ticket for that?

**Comment by longmd** [comment]
No need... just working through creating the reusable components for these and thought we might want that added in to those.

**Comment by longmd** [comment]
@allanto-ah , just noting that there is nothing to validate just yet. I'm going to do the Cypress test task, then we can do all validation in the QA ticket.
