### ISSUE TITLE
Tier 1 to Tier 2 Support Escalation Documentation Update

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#81110]
## Description 
This ticket will house the task of documenting how tickets are escalated from Tier 1 to Tier 2 to match our current best practices. [The updates will be made to this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2645098900/Tier+1+to+Tier+2+Support+Escalation).

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Review the current documentation on our escalation process
- [ ] Identify gaps and update the verbiage to match the process we now follow
- [ ] Update screenshots to ensure they match the current process
- [ ] Send to the Tier 1 team to review 
- [ ] Publish changes 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
During this sprint, we realized that similar content was displayed on the Support Best Practices page. To reduce duplicate work, we updated the existing page and this page is no longer needed. Closing ticket!

CC: @AnthonyWFlowers
