### ISSUE TITLE
Copy of [FE] Add Translations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#81126]
## Tasks
- [ ] Add the following translated SPANISH content to the appropriate json file     
      -  [Q1 2024 - SPA-FINAL_2024-03-27_15-14-51.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/15011623/Q1.2024.-.SPA-FINAL_2024-03-27_15-14-51.pdf)
      - **NOTE: numbers 122 - 126 were not in the product at the time the info was sent to the State Department, so, the keys may not be what they are in the product now**
- [ ] ~~Add the following translated TAGALOG content to the appropriate json file~~
- [ ] Generate SPANISH screenshots for workflow documents to submit to the State Department
- [ ] ~~Generate TAGALOG screenshots for workflow documents to submit to the State Department~~

**Comment by loripusey** [comment]
duplicate
