### ISSUE TITLE
Create Launch Blocking Issue Master Page

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#81123]
Right now, we have our LB issues listed on a few pages. That means that anytime we want to change or tweak our LB issues, we need to make updates to several different pages. This is more work than necessary. 

The Solution: Create a Master List page for Launch Blocking Issues and use the "include page" function in Confluence to embed that master list into the pages where we would like to include our list of LB issues. This will make it is that when we make future edits to our LB issues list, we will only need to update one page. All the other pages will update automatically. 

### TASK LIST

- [x] Creat LB Page
- [x] Edit Language
- [x] Get team approval
- [x] Finalize page 

### DEFINITION OF DONE

- [x] New Launch Blocking Issue page exists in the PCT Confluence space.

**Comment by BSmolensky** [comment]
A DRAFT of this page is here: https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3101163521/LAUNCH+BLOCKING+ISSUES

**Comment by jknipes** [comment]
Work is complete, moving to _Done_
