### ISSUE TITLE
Explore using CDW to access Consult Factors db table to find approved referrals

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81122]
## Tasks

- [ ] Explore using CDW to access Consult Factors db table to find approved referrals. If found, identify what fields and values are available in the approved referrals. Related [Slack thread](https://dsva.slack.com/archives/C06SQ48B205/p1713387030197699). 

## AC

- [ ] Access to CDW and db table where CC approved referrals are
- [ ] Identify what fields and values are available in the approved referrals

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/81122?planning-poker) with Zenhub @lee-delarm6 @simiadebowale

**Comment by lee-delarm6** [comment]
In order to point, want to know if the exploration includes verifying this is a valid path, or if it includes a working connection to CDW data

I assumed it was verifying, now we have to connect with it. I'd suggest a more detailed technical ticket which @simiadebowale and I can create today, with some help from@shanemelliott who connected to it in vettext and might have some docs and pointers! 😁

**Comment by benbrasso-agile6** [comment]
Yeah, you could split the work into two tickets. Definitely. E.g., close this one out prior to check-in's sprint end.

**Comment by benbrasso-agile6** [comment]
Nice, let's close it and do you want to start stubbing out the next one we'll need? If you need help with getting a ticket created, let me know and I can help.
