### ISSUE TITLE
Audit and update the Confluence documentation for Medallia

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#81146]
## Issue Description
_Audit and update the Confluence documentation for Medallia

https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/Medallia+Product

---
## Tasks
- [x] _Review Confluence content 
- [x] Audit content for accuracy 
- [x] Edit descriptions to reflect any updated processes
- [x] Publish updated content 

## Acceptance Criteria
 - [x] **Scenario: Review and update Confluence documentation for Medallia **
  - Given the Confluence documentation for Medallia
  - When the documentation is reviewed and updated for accuracy
  - Then the updated content should be published and attached to the appropriate milestone, epic, and labels
  - 
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@ATMiddleton will compile all Medallia pages and provide a summary to @clantosswett for auditing.

**Comment by ATMiddleton** [comment]
1.	Medallia Product - Medallia Product - Contact Center - Confluence (atlassian.net)
•	Product outline for Medallia

2.	How to use Medallia data in DOMO - How to use Medallia data in DOMO - Analytics and insights - Confluence (atlassian.net)
•	Created for users to view and analyze survey data captured via Medallia.  Includes definitions of the kinds of surveys available and available filters for data ratings. 

3.	Medallia Events - Medallia Events - Analytics and insights - Confluence (atlassian.net)
•	Medallia interactions collected in Google analytics 

4.	Medallia Protocol - Medallia Protocol - Contact Center - Confluence (atlassian.net)
•	For VSP & DEPO who need to understand how user feedback is received. 

5.	Medallia User Surveys Overview (WIP) - Medallia User Surveys Overview (WIP) - Contact Center - Confluence (atlassian.net)
•	Available survey definitions with samples

6.	Medallia Implementation Process - Medallia implementation process - Contact Center - Confluence (atlassian.net)
•	Implementation process; instructions to access request and forms to create surveys

7.	How to request a Medallia survey - How to request a Medallia survey - Contact Center - Confluence (atlassian.net)
•	Instructions to complete a Zenhub form.

8.	Medallia button relocation validation - Medallia Button Relocation Validation - Contact Center - Confluence (atlassian.net)
•	Documentation of the relocation of the feedback button from the sidebar to the bottom of the main content area on VA.gov and includes previous research. 

9.	Medallia – Bottom of main design proposal - Medallia - Bottom of Main Design Proposal - Contact Center - Confluence (atlassian.net)
•	Documentation of issues address with previous Medallia designs and revised designs. 

10.	Medallia – (Ryan Smith) - Medallia - Getting started - Confluence (atlassian.net)
•	Serves as reference for open and restricted fields in Medallia.

**Comment by ATMiddleton** [comment]
Chante has started the update - additional time is required.

**Comment by clantosswett** [comment]
I have updated the main confluence pages for VSignal surveys. This includes the following pages:

- [Product Guide](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1794015358/VA.gov+Digital+Surveys)
- [How to request a digital survey](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1793556578/How+to+request+a+VSignals+survey+on+VA.gov)
- [VA.gov Surveys CSAT Scoring](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1855357416/VA.gov+Surveys+CSAT+Scoring)
- [VSignals Digital Surveys on VA.gov Readme](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1765113923/VSignals+Digital+Surveys+on+VA.gov)

The following still needs to be done and will be captured in subsequent tickets that will be place in the backlog and upcoming sprints:

- Add page that lists out all VA.gov surveys that includes the questions, link to the survey if possible, but if not, include screenshots of the survey.
- Organize "working" documents to a separate section.
- Validate information with Aubrey for targeting parameters
- Add pre-approved questions to [How to request a digital survey](https://vfs.atlassian.net/wiki/spaces/Contact/pages/1793556578/How+to+request+a+VSignals+survey+on+VA.gov)
