### ISSUE TITLE
Update the Engineering Support Product Confluence Page

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#81152]
## Issue Description
_Audit and update the Confluence documentation for Veteran Support Engineering
---
https://vfs.atlassian.net/wiki/spaces/Contact/pages/2807431673/Engineering+Support+Product

## Tasks
- [x] _Review Confluence content 
- [x] Audit content for accuracy 
- [x] Edit descriptions to reflect any updated processes
- [ ] Publish updated content 

## Acceptance Criteria
 - [x] **Scenario: Review and update Confluence documentation for Engineering Support Product**
  - Given the Confluence documentation for Engineering Support Product
  - When the documentation is reviewed and updated for accuracy
  - Then the updated content should be published and attached to the appropriate milestone, epic, and labels

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
1st Draft 
[Engineering Support - Confluence.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN25xQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a43b36ef4dcab31d0a74727bd61b9ebd02fde9d/Engineering%20Support%20-%20Confluence.docx)

**Comment by ATMiddleton** [comment]
@aubreyarcangel will allert @starlow00 upon completion for final review.

**Comment by starlow00** [comment]
I reviewed and posed a question. Aubrey may still need to add material at his review.
See https://docs.google.com/document/d/1fvu-4z7eevI9Rm6jETHAg4AFktkWjaaUc9fedbddW8E/edit?usp=sharing

**Comment by ATMiddleton** [comment]
Hi,

I made some edits to the file.  Please review and provide feedback.

Thanks.

Best regards,

Anita
Product Manager
305-522-2306

**Comment by ATMiddleton** [comment]
Looks good.
*Steven Tarlow *(he/him/his) | Consultant: Content/Technical Writer


The So Company <http://thesocompany.com/>

*We make the government better.*
Timezone: PT
***@***.***
*SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member*

**Comment by starlow00** [comment]
Suggested that Aubrey's addition serve as a sub-page. Added a breadcrumb/link to the intro that should lead to the URL for the Medallia Tool Survey Setup (sub-page title).

**Comment by aubreyarcangel** [comment]
@starlow00 added  new section "Adding new always-on custom surveys' and your sub-page link at top suggestion
