### ISSUE TITLE
Post MVP EZR updates to static page and (still tbd) form alerts

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#81156]
## Issue description
The 1010EZR form launched to 100% on 4/18. The product team determined last month, after meeting with Sara from MHV, that they would make the form intro page auth only **after** their launch. 

Once their team makes their intro page auth only we'll need to add a sign in widget to the How to update your VA health benefits information static page. And on the [About form page](https://www.va.gov/find-forms/about-form-10-10ezr/), as previously discussed with Laura and Mikki, we'll need to link to the static page for access to the sign in widget (we can't add sign in widgets to the About form page).

We may also need to make some content adjustments to the current alerts on the EZR form users who are no longer enrolled in VA healthcare. The product team previously determined that for their MVP, the EZR would tell them that they can't use the form and include a link to the 1010EZ form. And once the users gets to the online 1010EZ form, the alert on that screen tells them why they're not enrolled and gives them next steps (i.e. apply for healthcare again). In a post MVP iteration, based on product team decisions, we may need to adjust the alerts on the EZR form.

---
## Tasks for static pages
- [ ] Add sign in widget to static page
- [ ] Change link on About form page
- [ ] Copyedit
- [ ] Publish

## Tasks for post-MVP EZR form
- [ ] (TBD) Adjustments to alerts

**Comment by aliyahblackmore** [comment]
This work in on pause until we confirm a few IA/content pieces.

**Comment by aliyahblackmore** [comment]
Moving to to "Blocked" for now as this is part of the larger sign in widget work that Laura in working on.
