### ISSUE TITLE
Design | Profile | Maintenance | Mock-up active saving state when removing information

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#81160]
## Background
With the new modal updates Adam is working on for removing information (#75892) , we need to create mockups to reflect the saving state in the read-only mode instead of in the modal.

Adam and I discussed using the slim info alert in place of the current blue text that shows, since the blue text isn't part of the design system.

## Tasks

- [x] Create a component in the auth experience pattern library for the various states for the update status when a person removes their information: saving, success, error
- [x] Update the figma files where we have the remove modal to use the component

## AC

- [ ] Figma mocks across editable profile sections reflect the new flow for removing info (this might only be contact info)

**Comment by mtcA6** [comment]
@andaleliz can you say more about what the saving state in the read only mode is? is it something new that doesn't exist? 
or is this essentially a cleanup ticket to update our mocks to match what Adam is doing on the FE?

**Comment by andaleliz** [comment]
@mtcA6 it's a clean up ticket to match what is happening on the FE

**Comment by andaleliz** [comment]
@adamwhitlock1 the Contact info Figma mocks have been updated to reflect the slim alert in place of what we have today.  
<img width="748" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/eb60f8b0-7782-4340-b2b2-3bc4eead05ad">

I updated the Personal information and direct deposit files to make sure the success/error messages are using the new slim alert.  Would the blue "save in progress" state apply there too? I assume so but wanted to double check.

**Comment by andaleliz** [comment]
@adamwhitlock1 one other question - does that `save in progress` message show for edits other than removing info? E.g. if they just made an update and it's taking a while for the API to respond?

**Comment by adamwhitlock1** [comment]
Yep, confirmed that most contact information fields will show a similar thing when it takes longer than about 5 seconds to save a field.

![Screenshot 2024-04-26 at 8 43 43 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/afd0d022-fce1-4f11-a913-4daabc6e0f75)

**Comment by andaleliz** [comment]
Thank you! Do you know if this also applies to pending changes for personal information + direct deposit? I would think so but just want to confirm.

**Comment by adamwhitlock1** [comment]
Its kind of a strange situation. This type of thing only happens for certain scenarios because of the way the API works for the fields related to Email, Phone, and Address. Basically just the contact info.

The rest of the api calls are 'single request' types of calls that resolve in reasonable timeframes, so this type of loading state for an extended wait time was not built into those parts of Profile.

**Comment by andaleliz** [comment]
@adamwhitlock1 I got CAIA's approval today on the following message:
>We’re saving your changes. Stay on this page.

The "stay on this page" guidance is there to make sure people see any errors that might happen. 

[Here's the mock-up](https://www.figma.com/file/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?type=design&node-id=288-5192&mode=design&t=XYMjHjPMoLzofCe5-11)

@mtcA6 I'm not sure if there is already a related FE ticket or not, so I'll move this to validate for ya.  Ready to close out otherwise.

**Comment by mtcA6** [comment]
@adamwhitlock1 I thought this was just to make sure the figma files matched the FE. Is the only change this shortened language?:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/2002bc58-e251-4a62-b680-33f13e885765)

Can you create whatever FE ticket you might need?

**Comment by mtcA6** [comment]
I see it was done as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/80994
