### ISSUE TITLE
Monthly Qualitative Data Request - Financial Status Report Form - May 2024

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#81162]
## Issue Description
Monthly processing of Qualitative Date for Financial Status Report Form 
---
## Tasks
- [x] _Complete data request monthly 
- [x] Deliver via VA.gov email 

## Acceptance Criteria
 - [x] **Scenario: Complete data request monthly**
  - Given the monthly data request is due
  - When the data is collected and processed
  - Then the data should be complete and ready for delivery
- [x] **Scenario: Deliver via VA.gov email**
  - Given the data is complete and ready for delivery
  - When the data is sent via VA.gov email
  - Then the email should be sent successfully and received by the intended recipient
- [x] **Scenario: Attached to a Milestone**
  - Given the issue is part of a larger project
  - When the milestone is set for the project
  - Then the issue should be attached to the milestone
- [x] **Scenario: Attached to an Epic**
  - Given the issue is part of a larger body of work
  - When the epic is created for the body of work
  - Then the issue should be attached to the epic
- [x] **Scenario: Labeled with Team**
  - Given the issue is assigned to a specific team
  - When the team is selected for the issue
  - Then the issue should be labeled with the team
- [x] **Scenario: Labeled with Practice Area**
  - Given the issue is part of a specific practice area
  - When the practice area is selected for the issue
  - Then the issue should be labeled with the practice area
- [x] **Scenario: Labeled with Type**
  - Given the issue is categorized by its type
  - When the type is selected for the issue
  - Then the issue should be labeled with the type
---
**### Data Type Requested**
User Surveys
### Data Source Type
Medallia
### Date Range Start
the first day of the month 
### Date Range End
last day of month
### Product Name(s)
Financial status report form
### Product Description
This form is for Veterans or service members who need help with debt related to VA benefit overpayments or health care copays.
### Survey URL(s), key term(s), case category or type
Custom survey (survey a Veteran sees after they submit the financial status report form))
va.gov/manage-va-debt/request-debt-help-form-5655/confirmation
Please share monthly data reports for the first day of the month to the last day of month, shared on the first day of the next month.
Thank you!
### File Delivery Format
One file, different tab for each term/URL
### Word Cloud
Yes
### VA Email Address(es)
charlotte.cesana@va.gov, denise.coveyduc@va.gov, megan.crigger@va.gov, joseph.lee9@va.gov
### Add Assignee and Labels
If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
See #75741 for reference

**Comment by ATMiddleton** [comment]
Completed for May 2024
