### ISSUE TITLE
Remove "epic" language and add "milestone" language

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#81178]
## User Story
As a VFS team member, I want to see consistent language in use across Collab Cycle documentation so that it's easy for me to follow along and not get confused.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
Per the [Confluence doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3027861571/76859+-+Explore+removal+of+Epics+in+Collaboration+Cycle) Rebecca put together, there are several documents that mention Epics (where Epic should be removed) and also several that do not mention Milestones (where Milestones should be added). 

**Note:** This ticket does not include making any updates to GitHub ticket templates, including the code blocks for kickoff.

## Impacted Artifacts
Remove mention of Epics:

- ~~Collaboration Cycle Kickoff - Moderator Responsibilities~~ See **Note** above. This doc will be edited in ticket #81179.
- How to generate Staging Review issue tickets 
- Generate Staging review issue tickets - workaround 
- *Anatomy of a Staging Review Issue ticket 

Add mentions of Milestones:

- *Collaboration Cycle FAQ 
- *Midpoint review 
- *Staging review 
- [Design Intent - During the Meeting ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775973945/Design+Intent+-+During+the+Meeting)
- ~~[Design Intent - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775253404/Design+Intent+-+After+the+Meeting)~~ (We do not need to add anything here, it is in the feedback ticket already)
- [Midpoint Review - During the Meeting (Synchronous) ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous)
- ~~[Midpoint Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790686759/Midpoint+Review+-+After+the+Meeting)~~ (We do not need to add anything here, it is in the feedback ticket already)
- ~~How to document feedback for a Midpoint Review~~ (We do not need to add anything here, it is in the feedback ticket already)
- [Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting) 

*Signifies that this is a VFS-facing doc (aka lives on Platform Website)

## Tasks
- [x] For all VFS-facing docs mentioned above, make documentation drafts in the Governance space. Edit docs appropriately to remove mention of Epics and replace with Milestone. 
- [x] For all operational docs, feel free to edit docs directly to remove mention of Epics and replace with Milestone. 
- [x] After VFS-facing docs have been peer reviewed and approved, publish to Platform Website

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All guidance documentation has been updated to remove references of Epics and add references to Milestones

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@shiragoodman can you confirm that the staging review issues are automatically added to the milestone since that is in the drafting template? We do not need directions on adding it after the staging review issues are created correct?

**Comment by allison0034** [comment]
@rferguson13 if you have time I would love you to look at the last FAQ on [this page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3124363272/Copy+Collaboration+Cycle+FAQ) about Milestones, feel free to edit directly on the page.

**Comment by shiragoodman** [comment]
> @shiragoodman can you confirm that the staging review issues are automatically added to the milestone since that is in the drafting template? We do not need directions on adding it after the staging review issues are created correct?

Correct @allison0034 .

**Comment by rferguson13** [comment]
@allison0034 That looks good to me. Simple and to the point.

**Comment by allison0034** [comment]
@shiragoodman when looking at adding something to the [Design Intent After Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775253404/Design+Intent+-+After+the+Meeting), what exactly are we wanting to add? I am not sure why we would mention milestones here.

**Comment by allison0034** [comment]
@briandeconinck drafts for [Platform Website](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3124953093/Allison+-+81178) are ready for your review. Hopefully I can move them to get published on Monday if you approve.

**Comment by rferguson13** [comment]
@allison0034 We don't have "Add the milestone to your DI feedback ticket" in our instructions. We know this step and we do it, but it's not documented.

**Comment by shiragoodman** [comment]
@allison0034  - see Rebecca's response above. Hope that answers your question!

**Comment by allison0034** [comment]
@rferguson13 we do, it is in our ticket instructions.<img width="1110" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0MxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5005b2741be28f82fe654b291e8434a9e373dec7/Screenshot%202024-05-03%20at%204.28.10%E2%80%AFPM.png" alt="Screenshot 2024-05-03 at 4.28.10 PM.png" />

**Comment by allison0034** [comment]
@briandeconinck all internal operational docs are ready for your review and linked in the artifacts section above.

**Comment by briandeconinck** [comment]
@allison0034 Left some comments in the Platform website drafts

**Comment by briandeconinck** [comment]
@allison0034 During the Meeting docs for DI and MPR look good, but I'm not seeing any changes made to the Staging one. Was the closing script supposed to match?

**Comment by allison0034** [comment]
@briandeconinck sorry I forgot to mention Rebecca is handling that in a ticket, here is [her draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3119022108/80426+-+Staging+Review).

**Comment by allison0034** [comment]
@briandeconinck can you check off the Peer review section and I will close?

**Comment by briandeconinck** [comment]
@allison0034 Done!
