### ISSUE TITLE
Edit code blocks, kickoff process and github feedback template to explicitly mention milestone

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#81179]
## User Story
As a VFS team member, I want to be able to find feedback and findings tickets by following the guidance in the gh tickets so that my team is able to take action in making appropriate changes to our product.

Assignee: @it-harrison 
Peer Reviewer: @rferguson13 

## Description
We have learned through working with VFS teams that they tend to follow the guidance in the gh tickets first before viewing any information on Platform Website. With that said, we need to update our Collab Cycle Feedback ticket template (used for DI and MPR) and our Collab Cycle Request template (which is generated using the code blocks in the Collaboration Cycle Kickoff - Moderator Responsibilities doc). In addition, any operational guidance in the Collaboration Cycle Kickoff - Moderator Responsibilities doc will also need to be updated to remove epics and replace with milestones

## Impacted Artifacts
[Collab Cycle Feedback ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+collaboration-cycle&projects=&template=collab-cycle-feedback.md&title=Name+of+Collab+Touchpoint+-+Practice+Area+Feedback+-+Name+of+Project)issue template
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] In the Collab Cycle Feedback template, remove the checkbox item under 'Governance team actions' for adding to the epic. Submit change as a PR and send to peer reviewer for approval.
- [x] In the Collab Cycle Kickoff - Moderator Responsibilities doc, a few changes are needed.
   - [x] Add a step for linking the Milestone in the body of the Collab Cycle Request ticket, preferably at the top where it is easy to see, before VFS Product Information. Content can/should say something like, "Please view the [Milestone](milestone.com) for all feedback and findings tickets associated with this Collaboration Cycle initiative." Or something like that. Feel free to wordsmith.
   - [x] For both the DI and MPR codeblocks, change the language in the After Meeting/Platform Actions section. Currently the feedback section looks like this:
<img width="384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWlHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4101b88aa731a7ff4fbc3af2a07fee8e9edb3857/image.png" alt="image.png" />
   - [x] Instead of "feedback ticket attached", change the content so that it directs the VFS team view the milestone to locate the feedback tickets. 
- [x] Lastly, review all operational guidance in the Collab Cycle Kickoff - Moderator Responsibilities doc, outside of the code blocks, to see if there's any other areas where epics are mentioned and milestones are not. If so, make the appropriate changes. 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All github templates associated with the Collab Cycle have been updated to remove mention of epics and reference milestone instead

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@rferguson13 this is ready for review
* [update](https://github.com/department-of-veterans-affairs/va.gov-team/pull/82366) to Collab Cycle Feedback template
* [draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/edit-v2/3128164353?draftShareId=191c5fb2-2cf2-4d67-8ee0-69e2bade5848) of modified Collaboration Cycle Kickoff - Moderator Responsibilities

**Comment by rferguson13** [comment]
@it-harrison - This looks good to me!
