### ISSUE TITLE
Create Page for Platform Content Creation in Relation to Platform Support

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#81171]
## Description 
While combing through older "Saved for Later" threads in Slack, I noticed that Joe Knipes provided a loose outline for creating, editing, and submitting requests for content (see attached screenshot). We are going to create and update a page that outlines this process in the following locations:

- [Creating Content on Platform Site for Platform Support Support Team](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3100803374/Creating+Content+on+Platform+Site+for+Platform+Support+Team?atlOrigin=eyJpIjoiYTEzMTI1ZWRmNmQ4NGE1NDk0MDEzZGNkYTBiNmQ5ZTIiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) (specific context is for how our team operates around these procedures) 
- [Advanced Support Best Practices (Tier 1) - Platform Content Submissions Section](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Platform-Content-Team-Submissions)

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Add content steps to [this page](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3100803374/Creating+Content+on+Platform+Site+for+Platform+Support+Team?atlOrigin=eyJpIjoiYTEzMTI1ZWRmNmQ4NGE1NDk0MDEzZGNkYTBiNmQ5ZTIiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) 
- [x] Verify with Dan Turner, Johnny Jesensky and Joe Knipes that the process is still the same and there are no edits (we have had recent conversations with them about the feedback to content creation pipeline) 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Content created, approved by Joe Knipes on Content Team, and will be presented at Platform Demo.
