### ISSUE TITLE
Migrate CHAMPVA content page into FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#81184]
## Issue Description

Move CHAMPVA content into hub, launch CHAMPVA form in new home (no left nav needed yet)
Note from Mikki: The CHAMPVA content can be moved in either this phase or the next, but needs to be done when the CHAMPVA form is launched

## Tasks
- [X] Laura - Clone CHAMPVA page in Drupal. Only URL is changing in phase 1, to va.gov/family-and-caregiver-benefits/health-and-disability/champva/
- [X] Kristin - coordinate with product team to launch their new form(s) into the family member hub
- [X] Kristin - create PW redirect ticket for static pages: [TICKET](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83558)
  - [X] CHAMPVA page
  - [X] [Family caregiver benefits page](https://www.va.gov/health-care/family-caregiver-benefits/) (this will redirect to new health subhub)
- [ ] Kristin - tell PW once the new page is live and we're ready to implement redirect
- [ ] Derek/Kristin - find crosslinks pointing to old links and change them to point to the new one (ex: hub pages, static drupal pages, and tools)
- [ ] Kristin - make sure the right node (http://preview-prod.vfs.va.gov/preview?nodeId=68990) is showing up in the right spot in left nav
- [ ] Kristin - if needed, coordinate changes to crosslinks in tools with teams.
- [ ] Kristin - update sitemaps

## Acceptance Criteria
- [ ] CHAMPVA static page and form have the correct URLs and breadcrumbs in prod
- [ ] CHAMPVA static page and form show up correctly in left nav
- [ ] [Family caregiver benefits page](https://www.va.gov/health-care/family-caregiver-benefits/) is redirecting to health and disability subhub
- [ ] CHAMPVA static page shows up correctly in health and disability subhub page

**Comment by laurwill** [comment]
@kristinoletmuskat same thing here — we're working on the page content for CHAMPVA that will go in phase 2, but is this phase 1 ticket more IA work than content work? Seems to involve coordination with the product team on launching the form with the correct URLs, etc. Can you help fill in steps and assignments here, or should we find a time to sync to define these better?

**Comment by kristinoletmuskat** [comment]
@laurwill just added some tasks and ACs here, and am coordinating with the CHAMPVA team behind the scenes to launch into family member hub.

**Comment by laurwill** [comment]
@d-beyer I cloned the CHAMPVA page to test out that process — it turns out the cloned page will match the published version, not the draft changes from the node we cloned. So for all pages we're planning to migrate from other hubs into FMB hub, we should clone first and then make all draft updates in the new node.

Here's the node for the new CHAMPVA page: http://preview-prod.vfs.va.gov/preview?nodeId=68990
I only updated the H1, intro, and blue feature box to match new draft. Can you update the rest of the page to match the content in this document? [CHAMPVA main page updates.docx](https://dvagov-my.sharepoint.com/:w:/r/personal/danielle_thierry_va_gov/Documents/Community%20care%20R%26S%20pilot%20shared%20folder/Working%20content%20drafts/CHAMPVA%20main%20page%20updates.docx?d=w3e9df0a1f0ee4410af638ea0943ff54e&csf=1&web=1&e=k5Dn2i)

**Comment by laurwill** [comment]
@d-beyer disregard previous comment. I was mixing up 2 separate phases. 

- I cloned the CHAMPVA page to test out that process — confirming that the cloned page will match the published version. Here's the node for the new CHAMPVA page to launch in phase 1: http://preview-prod.vfs.va.gov/preview?nodeId=68990
- If we somehow get SME approval for the planned updates to this page in time for phase 1, we can publish the updated version. If not, we'll publish the existing content at the new URL, and publish updates in phase 2.

**Comment by laurwill** [comment]
Also noting that for a lot of these pages where we're changing URL only, we'll have 2 pages with same H1 in Drupal. So let's just be aware of which node is the old URL and which is the new URL, and be careful to open and edit the right one.

**Comment by kristinoletmuskat** [comment]
@laurwill can we close this one?

**Comment by laurwill** [comment]
Yep, this is complete! Migrated page is live
