### ISSUE TITLE
Set up best bets for Phase 1

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#81187]
## Tasks
- [x] Update for PCAFC static page
- [x] Update for CHAMPVA static page
- [x] Add for family member hub

## Acceptance Criteria
- [x] All 3 best bets are validated in va.gov/search
---

**Comment by kristinoletmuskat** [comment]
Validated in prod, so closing
