### ISSUE TITLE
Review and publish of CAIA/kickoff/overview pages

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#81189]
## User Story
As a Governance team member, I want to understand how the updated pages will work together to communicate the roles of both teams within the Collaboration Cycle so that VFS teams have a clear understanding before beginning engagement.

Assignee: @erinrwhite 
Peer Reviewer: @rferguson13 

## Description
In ticket #76794, Governance team updated the Collaboration Cycle Overview page and the Collaboration Cycle Kickoff page. Minor changes to the FAQ page were also proposed. Simultaneously, CAIA team worked on updating the language and messaging on their page, which will no longer be included under the Touchpoints heading/hierarchy. Draft of CAIA's updated page can be found in the[ comments section below.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81189#issuecomment-2091505923)

The purpose of this ticket is to review all page changes together to ensure that consistent language, tone and voice are used throughout. We will also determine where the new CAIA page will live since it will no longer be included in the Touchpoints section. After Governance team approval, the pages will be published to Platform Website.

## Tasks
- [x] Transfer [CAIA draft page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81189#issuecomment-2091505923) to Confluence Documentation Drafts.
- [x] Review CAIA page for grammatical and formatting errors. Feel free to make changes to language so that the page flows with other modified pages within the Collaboration Cycle section of Platform Website.
- [x] Review CAIA page alongside Kickoff and Overview pages. Ensure all pages use consistent language, tone and voice.
- [x] Review comments from CAIA team members on Overview and Kickoff pages (see [Slack thread](https://dsva.slack.com/archives/G01DXP10GCA/p1712779106956599)). Make changes as you see fit. Follow up with Governance team members with any concerns/questions.
- [x] Determine where CAIA page should live in left side navigation of Collaboration Cycle section of PW
- [x] Identify if there are any other pages on Platform Website that link to the CAIA touchpoint page. If so, the url will need to be updated (I think?)
- [x] Once approved by Peer Reviewer, publish CAIA page, overview page, kickoff page and FAQ page changes to Platform Website.
- [x] Once published, update links in [Collab Cycle GitHub ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The updated CAIA, overview, kickoff and FAQ pages for Collaboration Cycle have been published to Platform Website.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
[CAIA VFS CC Page Rewrite.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abda4f2cce53e40a9b2e40e63bda45d325d51c70/CAIA%20VFS%20CC%20Page%20Rewrite.docx)
Updated CAIA page created by CAIA

**Comment by erinrwhite** [comment]
@shiragoodman Did Terry say whether the video is complete/posted, or should I leave that section out for now?

**Comment by erinrwhite** [comment]
[CAIA page is up and ready for review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3148152836/Content+Accessibility+and+Information+Architecture+support-+CAIA) @rferguson13!

Also would like your feedback on this reorganization of the collab cycle section of platform website:

## Current IA for [CC section of Platform website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)

 - Collaboration Cycle section landing page
   - Collaboration cycle kickoff
   - VA.gov experience standards
   - Must, Should, and Consider Framework for Feedback
   - Touchpoints
     - Design intent
     - Sitewide Content, Accessibility, and Information Architecture (CAIA) intake request
     - Research review
     - Midpoint review
     - Analytics request
     - Contact center review
     - Staging review
     - Privacy, security, infrastructure readiness review
   - Resources
   - Collaboration Cycle FAQ
   - Contact us
   - Change history

## Draft IA for CC section of Platform website

 - [Collaboration Cycle section landing page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054240236/76794+-+Collaboration+cycle+section+landing+page) `NEW` (will just be a list of child pages)
   - [Overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview) `NEW`
   - [Touchpoints](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3067969538/76794+-+Touchpoints) `UPDATED`
     - [Kickoff](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436405/76794+-+Collaboration+cycle+kickoff+request) `UPDATED and MOVED`
     - Design intent
     - Research review
     - Midpoint review
     - Analytics request
     - Contact center review
     - Staging review
     - Privacy, security, infrastructure readiness review
   - [Content, accessibility, and information architecture support - CAIA](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3148152836/Sitewide+CAIA+Content+Accessibility+and+Information+Architecture) `UPDATED, NEW TITLE and MOVED`
   - VA.gov Experience Standards
   - Must, should, and consider framework for feedback
   - [FAQs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054239764/76794+Collaboration+Cycle+FAQs) `UPDATED and NEW TITLE (was Collaboration Cycle FAQs)`
   - Resources
   - Contact us
   - Change history

**Comment by rferguson13** [comment]
@erinrwhite Just to be clear, is the CAIA page what they wrote about themselves? I want to clean it up a bit but also not step on any toes.

**Comment by rferguson13** [comment]
@erinrwhite I love that reorg. It's much clearer.

**Comment by shiragoodman** [comment]
@erinrwhite Terry has recorded the video and shared it with me. Let me try and share it with you via Slack.

**Comment by shiragoodman** [comment]
@erinrwhite i shared it on the #platform-governance-team channel on Slack

**Comment by erinrwhite** [comment]
> @erinrwhite Just to be clear, is the CAIA page what they wrote about themselves? I want to clean it up a bit but also not step on any toes.

@rferguson13 Yes! The CAIA page is (mostly) what they wrote about themselves. I put comments on spots where there are notable content edits. Any other edits from me are formatting changes. Compare to original doc [CAIA VFS CC Page Rewrite.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abda4f2cce53e40a9b2e40e63bda45d325d51c70/CAIA%20VFS%20CC%20Page%20Rewrite.docx)

**Comment by erinrwhite** [comment]
## ✔️ Review comments from CAIA team members
_Review comments on Overview and Kickoff pages (see [Slack thread](https://dsva.slack.com/archives/G01DXP10GCA/p1712779106956599)). Make changes as you see fit. Follow up with Governance team members with any concerns/questions._

Updated these pages, noting CAIA's edits in comments (not a lot!)

- [Overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview) NEW
- [Kickoff](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436405/76794+-+Collaboration+cycle+kickoff+request)
- [FAQs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054239764/76794+Collaboration+Cycle+FAQs)

## ✔️ Identify Platform website pages linking to CAIA page
 _Identify if there are any other pages on Platform Website that link to the CAIA touchpoint page. If so, the url will need to be updated_

I *believe* this link will still work if we keep the Page ID of the CAIA page the same (use/rename/move the existing page rather than creating new).

- [Research and design - overview](https://depo-platform-documentation.scrollhelp.site/research-design/)

**Comment by erinrwhite** [comment]
@rferguson13 Love the changes you made to the CAIA page! Everything else is ready for your review. I am thinking we plan to have these changes queued up to publish on Monday. That'll allow a day or so for sweep-up after if needed. Does that feel okay to you?

Pages to move over (following [new IA hierarchy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81189#issuecomment-2107926696) outlined in previous comment):

 - [Collaboration Cycle section landing page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054240236/76794+-+Collaboration+cycle+section+landing+page) `NEW` (will just be a list of child pages)
 - [Overview](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436353/76794+-+Collaboration+cycle+overview) `NEW`
 - [Touchpoints](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3067969538/76794+-+Touchpoints) `UPDATED`
 - [Kickoff](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054436405/76794+-+Collaboration+cycle+kickoff+request) `UPDATED and MOVED`
 - [Content, accessibility, and information architecture support - CAIA](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3148152836/Sitewide+CAIA+Content+Accessibility+and+Information+Architecture) `UPDATED, NEW TITLE and MOVED`
 - [FAQs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3054239764/76794+Collaboration+Cycle+FAQs) `UPDATED and NEW TITLE (was Collaboration Cycle FAQs)`

**Comment by rferguson13** [comment]
@erinrwhite - Sounds good! I'll tackle these today/tomorrow to make that deadline.

**Comment by shiragoodman** [comment]
I plan to take a look too! Thank you both for working on this. Looking forward to seeing where we're at.

**Comment by shiragoodman** [comment]
@erinrwhite sorry for the delay. I provided some comments this morning on your documentation drafts. Please let me know if you have any questions. Thank you for working on this!

**Comment by erinrwhite** [comment]
@shiragoodman all good! I incorporated changes based on your feedback into the draft docs and the platform website pages.

Changes made in [Collab Cycle space on confluence](https://vfs.atlassian.net/wiki/spaces/CC/overview?homepageId=1524891996), awaiting publishing this afternoon.

**Comment by erinrwhite** [comment]
Programming note: once pages are published we will likely need to update some of the hyperlinks in the [Collab Cycle GitHub ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml).

**Comment by shiragoodman** [comment]
Thanks @erinrwhite . Can you include that work (updating links in the gh ticket template) as part of this ticket?

**Comment by erinrwhite** [comment]
@shiragoodman done!

**Comment by erinrwhite** [comment]
@rferguson13 @shiragoodman [pages published!](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) will do a full review in the morning, but I am already seeing some clarifying edits I'd like to make now that the pages are in Scroll Viewport. Also seeing a few double-instances of the page footer 😩 

I'll also take a look at the CC Ticket template tomorrow 👍🏻

**Comment by erinrwhite** [comment]
@rferguson13 @shiragoodman I think we're all set?

### page updates

Made a few changes to the [collab cycle pages](https://vfs.atlassian.net/wiki/spaces/CC/overview?homepageId=1524891996) to be published this afternoon:

- removed double footer on touchpoint page
- updated links on several pages to use internal Confluence links rather than hard-coded links to platform website, to ensure link consistency and durability and keep them opening in the same window
- moved specific information about kickoff scheduling, including link to ticket creation and slack workflow command, to the kickoff page. Since this link is very complex and changes regularly we want to have it only in one place if possible


### Collab cycle request ticket update

- CC ticket template Pull request ready for review #83568 
- [Code blocks in moderator docs](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities) updated with new CAIA URL

**Comment by shiragoodman** [comment]
> - updated links on several pages to use internal Confluence links rather than hard-coded links to platform website, to ensure link consistency and durability and keep them opening in the same window

@erinrwhite do you mind if I ask where? Platform Content team may block us for this. Platform Website pages should not link to anything internal.

**Comment by shiragoodman** [comment]
got it! Thank you for clarifying 😄

**Comment by shiragoodman** [comment]
@erinrwhite Joe Knipes mentioned this at Team of Teams today and will be presenting on it at Platform end of sprint demo tomorrow. Good timing for us!

**Comment by erinrwhite** [comment]
[CC pages updated](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
Ticket template changes merged - #83568


Ready for final review and checkboxes @rferguson13 thank you!
