### ISSUE TITLE
Migrate PCAFC content page and app into FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#81183]
## Issue Description

Notes from Mikki:
- Move [PCAFC content page](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/) and application into new placement (no left nav needed yet)
- The [PCAFC FORM](https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction) URL does not need to be updated in order to "hook it up" in this new structure, the breadcrumb will need to be updated however. 

---
## Tasks
- [x] Derek - Clone PCAFC static page in Drupal on a new node with a new URL. Nothing else about the page is changing.**va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/**
- [x]  Derek - Clone [PCAFC static SPANISH page](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers-esp/) in Drupal on a new node with a new URL. Nothing else about the page is changing.**va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp/**
- [x] Kristin - coordinate with product team to set up new form at **va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg/** [TICKET](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81299)
- [X] Kristin - create PW redirect ticket for static page: [TICKET](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83558)
- [x] Kristin - create PW ticket for spanish toggles on PCAFC SPANISH static page [TICKET](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84625)
- [x] Kristin - tell PW once the new pages are live and we're ready to implement redirects
- [x] Kristin - find crosslinks pointing to old links and change them to point to the new one (ex: hub pages, static drupal pages, and tools). Create a separate backlog ticket if needed.
- [x] Kristin - if needed, coordinate changes to crosslinks in tools with teams.
- [x] Kristin - update sitemaps

## Acceptance Criteria
- [x] PCAFC static page
        - [ ] Has correct URL in prod
        - [ ] Has correct breadcrumbs in prod
        - [ ] Shows up correctly in the left nav
        - [ ] Shows up correctly in the health-and-disability subhub page
- [x] PCAFC SPANISH static page
        - [ ] Has correct URL in prod
        - [ ] Has correct breadcrumbs in prod
        - [ ] The toggle is working correctly
- [x] PCAFC FORM
        - [ ] Has correct URL in prod
        - [ ] Has correct breadcrumbs in prod
        - [ ] Shows up correctly in the left nav
---

**Comment by laurwill** [comment]
@kristinoletmuskat can you help fill in the next steps for this ticket? This looks like IA work more than content. 

We need to document:
- Steps for "migrating" this page and who does each step
- Steps for getting breadcrumbs updated on form and who coordinates that with product team

cc @strelichl — there are several tickets that are currently assigned to you and Derek, but look more like IA work or a combo of content and IA work. Let's aim to have these all fully built out and reassigned as needed by the end of this week.

**Comment by kristinoletmuskat** [comment]
NOting the the notes from Mikki in this ticket differ from the plan we confirmed with her (to have the PCAFC represented in the left nav and fully migrated into this space). I can talk to her about that tomorrow.

**Comment by d-beyer** [comment]
Cloned and updated URL: [Cloned PCAFC static page](https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers)

**Comment by kristinoletmuskat** [comment]
@d-beyer just added that we'll have to clone the spanish page as well -- I added an item for that up top, and added the ACs.

**Comment by d-beyer** [comment]
Cloned Spanish page and updated URL: [Cloned Spanish PCAFC static page](https://prod.cms.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers-esp)

**Comment by kristinoletmuskat** [comment]
We have a separate ticket for the spanish toggles, so closing this one out.
