### ISSUE TITLE
Add assignee to SR Experience Standards issue tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#81186]
## User Story
As a VFS Product Manager, I want to be assigned the issue tickets that are created at Staging Review so that I am able to assign them to my team for resolution.

Assignee: @briandeconinck 
Peer Reviewer: @erinrwhite 

## Description
In the research findings from the Design Intent research completed by Service Design, one of the [key insights ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2816475137/Research+Findings+Design+Intent+Experience+Study#Key-Insights )was that VFS teams would prefer to be tagged on Design Intent issue tickets so that it is easier for them to locate the ticket post- meeting for action. We are assuming that the same is also true for Staging Review.

We will make this change with both the VFS Staging Review process and the DST Staging Review process.

## Impacted Artifacts
DraftingTemplate 2.0
DraftingTemplate 2.0 - DST
[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
[Design System Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling)
[How to generate Staging Review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)

## Tasks

_**Note** Before any changes can be made to the DraftingTemplates, we must address the permission issues. Shira has still been experiencing errors in the Github Upload tab. She has to contact the On Support person who created the DraftingTemplate for the SR and ask that they give her edit permissions in order for the upload to take place. Is there a way we can copy/paste the baseline DT and ensure everyone has permissions to edit while still protecting cells with complex/fragile formulas? @erinrwhite let's have a meeting to figure this out (since you're the owner of the baseline DTs)_

**In the SR- Scheduling doc:**
- [x] Edit the instructions in 'Step 2: Create the DraftingTemplate' for adding the assignee name (aka their gh username) to the assignee column in the first row of the GitHub upload tab. 
   - The assignee should be the teams Product Manager. This is usually the person who created the Collab Cycle Request ticket.
   - [Instructions added to Step 2 of SR scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling#Step-2%3A-Create-the-Drafting-Template)

**In DraftingTemplate 2.0 DST:**
- [x] Add Carol Wong's github username` @caw310 ` to the assignee column in the first row of the Github Upload tab.
   - [Instructions added to Step 2 of DST SR scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling#Step-2%3A-Create-the-Drafting-Template) 

**In the How to Generate SR Issue tickets doc:**
- [x] Add a step for the person to verify the assignee name. This person should be the teams Product Manager. Include instructions to verify with Shira if you are uncertain who the PM is. 
   - [Instructions added to Step 2 of How to Generate](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#Step-2%3A-Review-integrity-of-data) 
- [x] Add a step for the person uploading to copy the assignee name to all applicable rows in the Github Upload tab
   - [Instructions added to Step 3 of How to Generate](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#Step-3%3A-Download-and-edit-CSV) 

**Misc:**
- [x] Review all other Impacted Artifacts that have not yet been modified and verify that no additional changes are needed.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Product Manager is automatically added as the assignee of all Staging Review issue tickets in github for all future Staging Reviews

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@erinrwhite Ready for review. 
- [Instructions added to Step 2 of SR scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling#Step-2%3A-Create-the-Drafting-Template)
- [Instructions added to Step 2 of DST SR scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572124161/Design+System+Staging+Review+-+Scheduling#Step-2%3A-Create-the-Drafting-Template) 
- [Instructions added to Step 2 of How to Generate](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#Step-2%3A-Review-integrity-of-data) 
- [Instructions added to Step 3 of How to Generate](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#Step-3%3A-Download-and-edit-CSV) 

I'm pretty sure there's nowhere else that needs to be updated but please let me know if you think of something I missed!

**Comment by shiragoodman** [comment]
@erinrwhite  yea, I considered that solution. @briandeconinck and I talked about it and I explained why I set it up like this... aka no changes to Findings tab needed. I will make changes to the DT tomorrow so that it auto populates the assignee in every row of the Github Upload tab, when applicable.

**Comment by briandeconinck** [comment]
@erinrwhite Good to check off the peer review box?

**Comment by erinrwhite** [comment]
@briandeconinck Yes! Just checked - thank you for the follow-up.

**Comment by briandeconinck** [comment]
Thank you!

**Comment by shiragoodman** [comment]
@briandeconinck I never added a formula for the assignee to autofill in the appropriate rows of the Github Upload tab. Does this still need to be done? LMK and I can work on it.
