### ISSUE TITLE
Daily Case Review Instructions 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#81191]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _Create daily case reporting
- [ ] Review case details
- [ ] Update Case owner accordingly
- [ ] Forward response templates according to case type
- [ ] Document actions taken
- [ ] Close cases 

## Acceptance Criteria
 - [ ] **Scenario: Daily case review instructions**
  - Given the issue has a title and description
  - When the tasks and acceptance criteria are configured
  - Then the issue should be attached to a milestone, labeled with team and practice area, and labeled with type
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
[Daily Case Review Process.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce437072d26633bf2dbfb686ca6a6e98947fb332/Daily%20Case%20Review%20Process.docx)

**Comment by clantosswett** [comment]
@ATMiddleton @Kimberley2023-CSM can you share the link to the sharepoint site where this now resides? Thanks!
