### ISSUE TITLE
Build health care and disabilities landing page for FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#81201]
## Issue Description

Mikki has stubbed out new pages required for the family member hub and will add links to this ticket:
*Note: the formatting and elements used in these are not necessarily final, they were simply a way to experiment with the content that we needed to represent.

- Health care and disabilities: http://preview-prod.vfs.va.gov/preview?nodeId=65069

Per Mikki: The required pages to be linked to from each landing page is documented in the [family member hub mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1704984305251) - on the far right under "Final working structure"

---
## Tasks
- [x] Compare links on the stub page in Drupal to the updated [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md) and update Drupal to match IA design as needed (Derek)
- [x] Adjust all sections to use the "List of link teasers" style with linked H3 headers followed by blurbs (Derek)
- [x] Draft intro for the page and blurbs for each link on the page (Derek)
- [x] Review draft landing page (Laura)
- [x] Decide on H1 (Derek, Laura, Kristin)
- [x] Copyedit and prepub checklist (Sara)
- [x] Send to SMEs (Danielle)
- [x] Publish **(coordinated effort)**

## Acceptance Criteria
- [x] The health-related benefits landing page is live on VA.gov
---

**Comment by laurwill** [comment]
@kristinoletmuskat IA question on this landing page. The IA doc has these 2 links:
- Spina Bifida: https://www.va.gov/disability/eligibility/special-claims/birth-defects/
- Children of women vietman veterans: https://www.va.gov/COMMUNITYCARE/programs/dependents/cwvv/index.asp

The VA.gov page we're linking to for Spina Bifida is actually about both of those programs, even though it doesn't include the name of the CWVV program. And we'll be replacing that VA.gov page and the legacy pages for each program with 2 new pages in this family member benefit hub. 

Did you consider linking to the live VA.gov page for both programs until the migrated pages for each program are live?

**Comment by kristinoletmuskat** [comment]
@laurwill Good call, so just to confirm, we can remove the link crossed out in this screenshot, yes?

![Screenshot 2024-04-24 at 3 22 27 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/3b704648-9aa7-48a5-ad5d-a34fcf4ea110)

**Comment by laurwill** [comment]
I think so, yes — see if this looks right to you:

For phase 1 launch of this landing page, we'll combine spina bifida and cwvv into a single link to the existing page:
- Benefits for birth defects linked to Agent Orange: https://www.va.gov/disability/eligibility/special-claims/birth-defects/

For phase 2 launch of the full health care & disability section, we'll replace that combined link with 2 separate links to the newly migrated pages for each program:
- Spina bifida: [new URL in FMB]
- CWVV: [new URL in FMB]

**Comment by kristinoletmuskat** [comment]
Sounds good! I will update the IA spec.

**Comment by d-beyer** [comment]
Hi @laurwill , I've finished a [rough draft of this landing page](preview-prod.vfs.gov/preview?nodeId=65069). 

Some notes and questions:
- The "Coaching into Care" legacy page says that it's being retired. Should we be linking to that then?
- The "Finding a CHAMPVA provider" legacy page basically links off to non-VA provider finders since the program doesn't have a limited provider list. In the new CHAMPVA FAQ, we don't link to any way to find providers. This leads me to think that maybe we shouldn't link to this legacy page here either.
- The landing page draft came with a related links section that I didn't see represented in the IA spec. Should that stay?
- I've got some broad style questions about how we're revising this to family members.
	- I tried to use "you" whenever possible, but there were one or two instances when it seemed awkward. I'm curious if there are blurbs you think should be reframed.
	- Should I be removing references to a program being for "Veterans and family members" since we're talking _specifically_ to family members?
	- Sort of a general question, when does aligning the source material with an existing modern page override localizing it to a page like this?
	- How do we want to handle the CHAMPVA abbreviation on this page (or other long abbreviations)?

I think I can do successive landing pages more quickly now that I've done this one and worked out the process for it. Happy to talk through any feedback or changes with you next week!

**Comment by d-beyer** [comment]
@kristinoletmuskat Yes, sorry, that component is labelled "Related links" in the drupal back-end. There were two links already in the draft of the health care landing page -- "Decision reviews" and "Get help from an accredited representative".

**Comment by laurwill** [comment]
Thanks for flagging these questions @d-beyer ! 
- Agree with your assessment that the links to "Coaching into Care" and "Finding a CHAMPVA provider" don't seem useful. Let's suggest removing these. I also think the income limits tool is not relevant here.
- For the style questions, I tried editing to make most of the blurbs single-sentence CTAs starting with "Find out" or "Learn" etc. Seeing the amount of content on the page, wanted to see how much we can trim.
- I think we can mostly frame around family members and drop "Veterans and family members" from descriptions in this context. May be case by case.
- For the Q about aligning existing modern page vs localizing content to this page, I think the answer here is that we actually need to create 3 additional benefit detail pages for family member versions of existing pages. But that will happen in phase 2, I think.
- Spell out CHAMPVA and other long program names once per page, then use abbreviation

Questions for @kristinoletmuskat :
- Should we always be following IA spec over Mural? Derek flagged 2 links in Mural and not in IA spec (MHV and claim status tool) and you confirmed we shouldn't include them. 
- Can we remove these 3 links?
     - Coaching into Care — program ended in April 2024, site is now just links to other resources
     - Finding a CHAMPVA provider — the answer is that there's no such think as a CHAMPVA provider and you can just go to whoever, so we're addressing this in a Q&A on the FAQ page for CHAMPVA.
     - Income limits tool — I think this is only relevant for Veterans applying for VA health care. What's the use case for family members?
- We're migrating the legacy CHAMPVA CITI page as a section of the CHAMPVA FAQ, rather than a standalone page. Does that affect the decision to include it as a link here? Or will we just update the URL to point to that section of the FAQ? (FAQ is also linked on this landing page)
- Additional services and Helpful tools sections: the nested H3s look a little funky on the page with the link teaser setup. 
      - Would we want to consider bumping these up to H2s? (So it would go Get benefits, Other benefits, Helpful tools, Manage benefits, More resources)
      - Or distributing "other benefits" into "more resources"? And "helpful tools" into "manage benefits" or "other resources"?
      - Could also consider using the gray "Related resources" box for overflow — I removed this for now since I think it wasn't intended to be here, but let's discuss!
- Can you confirm that we're linking to existing versions of Camp Lejeune, mental health services, and dental program pages in Veteran hubs for phase 1 launch, and creating family member versions for phase 2?

**Comment by kristinoletmuskat** [comment]
Hey hey @laurwill and @d-beyer 

1. We should be using the IA spec over mural, but I do want to try to have them aligned (because I'm so visual I need the mural to understand what's going on). However, I don't see those 2 links in the mural! (MHV and claim status tool). I think MHV would still not make sense (assuming it's just for veterans). 

2. I think we can remove those 3 links, but let me ask Mikki at our meeting on Wednesday 5/15 and get back to you to confirm. 

3.  I think we can move the legacy link to CITI and just keep the FAQ. We don't need to deep-link to that section of the FAQ. Let me double check with Mikki.

4. Could you paste a screenshot of those funky H3s? I'll talk this through with Mikki too, thanks for the suggestions!

5. Yes, confirmed that for mental health, lejeune, and dental, we're linking out for phase 1, and building the family member pages in phase 2.

**Comment by laurwill** [comment]
Screenshot of funky looking H3 section for "Additional services." 
<img width="659" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/54d8245d-7338-438b-ab7e-a4a9b5866f37">

**Comment by laurwill** [comment]
Oh also, the TRICARE page that's first in that "Additional benefits" section is an R&S page, because it's about a DOD benefit and not a VA benefit — are we putting R&S pages/non-VA benefits in the "Get benefits" section for family member hub?

**Comment by laurwill** [comment]
Also noting we tried removing the blurbs in the "Manage" section and just doing links — Danielle said she discussed that with Mikki as an option for trimming length/words from these landing pages. I think it's fine?

@d-beyer couple other notes:
- I saw a few links to VA.gov pages that have the url instead of the node linked  — can you do a pass and make sure all the modernized pages are linked as node IDs?
- For the next landing page, keep an eye on where we might need to adjust the blurb from the Veteran hub for family member-specific framing. One I tweaked in this page was mental health services — we can't reuse the Veteran blurb there because mental health services for family members are more geared toward supporting the Veteran and coping with how the Veteran's mental health conditions affect the family member. Let me know if you want to chat through how to reframe any in the next one!
- I also changed one of the link texts to align with the H1 of the legacy page instead of the H1 of the future migrated page. Hopefully most will be close enough that we don't have to change them after we migrate, but the "Getting care through CHAMPVA" H1 is far enough from "Frequently asked questions about CHAMPVA" that I thought better to change.

**Comment by d-beyer** [comment]
@laurwill Thanks! I updated the urls.

**Comment by kristinoletmuskat** [comment]
Following up with Mikki on the TRICARE and I'll get back to you!

**Comment by kristinoletmuskat** [comment]
No concerns on that H1. Lmk when finalized and I'll update the places where that breadcrumb appears in our documentation.

**Comment by kristinoletmuskat** [comment]
Hey ya'll, I know we noted somewhere that we might want to redirect this [healthcare for family ](https://www.va.gov/health-care/family-caregiver-benefits/)page to our new health hub -- Mikki flagged that this page has a lot of paragraphs of content. We wanted to make sure that we had parity in content with the new hub page before we migrate this stuff over. If not, we can move this work to phase 2!

@laurwill does the healthcare for family page have enough content parity that we can redirect? Or not yet?

@aprocik1 @d-beyer

**Comment by laurwill** [comment]
@kristinoletmuskat the H1 for this page is now "Health-related benefits for family and caregivers" but the URL is still health-and-disability. Is that okay, or does the URL change?

**Comment by laurwill** [comment]
Hi @saratorres2 , I adjusted the instructions here after our sync with Megan on Friday — the link situation is so wonky for this launch that we'll handle checking links separately from your copyedit. Let me know if you have any questions as you start on this batch!

@d-beyer (and @kristinoletmuskat for when you're back from OOO), I discussed a couple things with Danielle on Friday about this landing page:
- We confirmed that we don't want to frame this subhub as "disability" benefits because the compensation for caregivers and children of Veterans with birth defects is very different from VA disability comp for Veterans. So the H1 change to "Health-related benefits" is helpful here.
- But we realized that H1 change also changes the URL, so I'll start a chat to confirm with Mikki this morning. That will also mean that URLs for the online forms in this section will change. 
- We decided not to rush the new TRICARE page for phase 1 launch. We'll link out to TRICARE site for now and replace the link with our new page as soon as it's ready.

**Comment by saratorres2** [comment]
@laurwill Copy edits complete. There is an open question about the current H1, "Health-related benefits for family and caregivers," so it would be good to confirm the H2s before publishing.

**Comment by kristinoletmuskat** [comment]
Just noting that Laura and I are going to talk about how to move forward with potential H1 change tomorrow -- @d-beyer I added you to invite too

**Comment by laurwill** [comment]
@d-beyer new related links to add: 
Survivor Dependency and Indemnity Compensation (DIC)
Aid and Attendance or Housebound benefits for survivors
Accelerated benefits for terminally ill policyholders
VA home loan programs for surviving spouses

**Comment by d-beyer** [comment]
@laurwill I added the related links.

**Comment by d-beyer** [comment]
@saratorres2 I've added the related links and they're ready for copyedit. Screenshot attached.
![Health-FMB-related-link-20240614](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141662117/451eaba6-33d3-474a-ae80-c60f1a760a50)

**Comment by saratorres2** [comment]
@laurwill Copy edit of new related links section complete.

**Comment by kristinoletmuskat** [comment]
Confirmed live in prod, closing out.
