### ISSUE TITLE
[CAIA General Support]: IIR - Error Messaging Review

### ISSUE THREAD

**Issue by emcruer** [department-of-veterans-affairs/va.gov-team#81202]
# CAIA General Collaboration 

`WIP`

Use this ticket to request general collaboration with the Sitewide Content, Accessibility, and Information Architecture (CAIA) team.

## About your team

- **Team name**: IIR
- **OCTO-DE product owner:** Jeff Barnes
- **Product name:** Veteran Status Card
- **Product manager:**  Pete Egan / Kat Kufalk
- **Slack channel:** [iir-product-teams-public](https://join.slack.com/share/enQtNzAxNjY2OTEwODQ5Ni1jZGFmZDNmMGE0OTgyNzc5NWEwNmM5YjE4YTg2MzU2NzE0NGYwODcwOWJkOTI2ZGIwMjQ4OTY4NzE4NTE3ZGVh?recommended_build_version=1713485245&build_manifest_last_modified=1713487640)
- **Dedicated content writer on your team (if you have one):** None
- **Dedicated a11y specialist on your team (if you have one):** None
 
## About your request.  
The Veteran Status Card MVP is live under Profile > Military Information, but there are errors a user might encounter when trying to download and use the card. None of the errors have any messaging for the user, so we'd like approval on the proposed messaging so we can match the triggers to the appropriate front end response. There's no change to the product or any changes to how the user interacts with it, just feedback on the action they've taking where previously none existed.

### Describe your project goals

1. Provide feedback for users attempting to access the Veteran Status Card.  

### What is your team working on?
_For example, you may be launching a new form, page, or product, or updating an existing one._

We are working on understanding the potential errors that occur and then providing the user with feedback, whether it's a system failure, ineligibility or a data mismatch.   

### Describe how you would like to collaborate with CAIA

_For example, you may need content collaboration to ensure a form is plain language or guidance to plan accessibility testing on a new tool._

We would love feedback on the messaging and how we're instructing users, particularly as there is some sensitivity around discharge status that should be communicated with clarify and thoughtfulness.

## Type of Collaboration 
_Check all the types of collaboration you're requesting, below:_

### Content
- [x] Creating new content (we have proposed content, but it does not yet exist live anywhere)
- [ ] Updating existing content 
- [ ] Translating content 
- [ ] Something else:  `insert type of collaboration`

### Accessibility
- [x] Wireframes or prototypes review (we will display the mockups of the messages)
- [ ] PDF review
- [ ] User research support
- [ ] Something else:  `insert type of collaboration`
### IA
- [ ] User flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and left nav placement
- [ ] Redirects
- [ ] Something else: `insert type of collaboration`
### Other
- [ ] Check this box if you're not sure what kind of support you need, and we'll schedule an introductory meeting to learn more about your project.

## Collaboration timeframe

We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Your timeline 
- [ ] Check yes, if this request is tied to a Congressional mandate or timeline?

### Will you release this new product incrementally (for example, release to 25% of users to start)?
- [ ] Yes
- [ ] No

**Note: **If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages). Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.

- [ ] I acknowledge that if I change the roll out of this product to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines. 

### Description
**Describe where you are in your project's timeline.** 
_For example, you may be drafting content, planning or synthesizing research, waiting on an SME review, or scheduling your MVP launch date. Add dates for any upcoming milestones._

This MVP product is live, and next we need to provide more accurate messaging. 

## Collaboration cycle 
If you’re going through the collaboration cycle with the governance team, link to the ticket:
- **Ticket Number:** `xxxxxx`
- If you’re not going through the collaboration cycle, or you’re unsure, check here, and we can follow up: 
    - [x] Not going through collab cycle

**Note**: We ask that you partner with us **before** scheduling your midpoint review, **to ensure** we can agree on a deliverable and that there's time for your team to make changes.  

### Phases Completed
**Check any phases you’ve already completed:**
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
  
## Supporting artifacts
Please provide links to any supporting artifacts we might need to begin work. This can include your product outline, user flows, mockups and prototypes, draft content, etc.
- [Figma Mockups](https://www.figma.com/file/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?type=design&node-id=0%3A1&mode=design&t=cwGzqHCJEQEEo03l-1) 
- We're having trouble replicating this on staging at the moment and are in the process of requesting new staging users.  

## Next steps
- [ ] Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.
    - A member of the CAIA team will aim to respond to your Slack message within 24 hours to acknowledge receipt - should we need any additional information regarding your request we will reach out to you to confirm.
    - The CAIA Operations group will meet to go over the info in your request and then reach out if we have any questions.
    - Depending on the request, it may make sense to schedule a kickoff meeting to better understand how we'll partner with you!
- [ ] Please review the remaining next steps in the **VFS Team Tasks** section, listed below.

## CAIA Deliverables
This section is where the CAIA team will link to the deliverables (if any) for the work done in support of this request. 

<br>
<br>

## TASKS

<br>

```[tasklist]
### VFS Team Tasks
- [ ] If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
- [ ] If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.
- [ ] If you are requesting content support, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### a11y Tasks
```

```[tasklist]
### Content Tasks
```

```[tasklist]
### IA Tasks
```

**Comment by emcruer** [comment]
Sounds good! Thank you!

**Comment by emcruer** [comment]
![Integrated Desktop 1280 - MVP - Error discharge mismatch](https://github.com/department-of-veterans-affairs/va.gov-team/assets/15392100/24265b97-7d7e-4507-8f3e-115b37e8bb71)
![Integrated Desktop 1280 - MVP - Error discharge status](https://github.com/department-of-veterans-affairs/va.gov-team/assets/15392100/fc1530dd-4041-4f0e-9801-b04bf9d29043)
![Integrated Desktop 1280 - MVP - System Error](https://github.com/department-of-veterans-affairs/va.gov-team/assets/15392100/db12f384-25c2-4a8c-a141-9a2cef5172b5)

**Comment by emcruer** [comment]
@laurwill Tagging you here, per the request! I'm back with more (but different!) error messages. The Veteran status card is available for download under military information. We've got three errors that need to be added:

1) System failure / card just not downloading 
2) Ineligible due to discharge status. A card is available to people with specific (honorable) discharge statuses. If a user doesn't meet this criteria and has a less than honorable discharge or dishonorable discharge, then they cannot download the card. 
3) Mismatch information. We don't have a discharge status that says they are eligible, but we don't have one that says they're ineligible either, so they need to contact DMDC to see if a correction needs to be made. 

I signed up for Office Hours at the next available slot which is 4/30, I believe.

**Comment by laurwill** [comment]
Hi @emcruer , I had a minute to review these and suggested edits in the Figma, and also left you a few questions. We may be able to wrap this up async, but also tagging in @aprocik1 here for awareness — A is filling in for me in office hours today, so they can help you wrap this up if needed!

**Comment by emcruer** [comment]
@laurwill Belatedly following up to close things out and thank you for all your help! I think we're good on this messaging and we really appreciate the feedback. If you're all good, too, we can close this one!

**Comment by laurwill** [comment]
Great thanks Liza! Closing out :)
