### ISSUE TITLE
DR | Store Unprocessed Evidence Submission PDFs

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#81205]
## Background Context

This is a followup to #79406.

[Decision Review Original Evidence Payloads Storage - Initiative Brief
](https://docs.google.com/document/d/1t_AUN4JL0pjpbaytzoy6GZ7kw7ZkSjUfJmVVQGwswCo/edit)

After further investigation into 'blank images' and 'invalid PDF content' errors, we will store unprocessed PDFs in S3 (with corresponding logs to allow for correlation between files).

## Tasks
- [ ] Store original (unprocessed) evidence PDFs in S3
- [ ] Add logging for the encryption state of evidence PDFs
- [ ] Persist PDF passwords

## Definition of Ready
- [ ] Whoever picks this up has access to our S3 bucket
- [ ] Determine how user passwords can be stored for encrypted evidence PDFs

## Definition of Done
- [ ] Existing evidence processing is not affected
- [ ] Unprocessed evidence files are stored in S3
- [ ] Logging added for the encryption status of evidence files (and additional fields if necessary)
- [ ] Unprocessed files are compared and validated against PDFTK decryption

**Comment by saderagsdale** [comment]
Possible AC:
- No existing data in negatively impacted
- We are logging before and after for parity
- Passwords are stored securely

Open questions:
- How long can we retain this data?
- @shaunburdick is working with Cory to find out a final answer. Will reach out to Jonathan Kamens (security lead working with ATO).

**Comment by saderagsdale** [comment]
Ticket not ready until we know more about password storage.

**Comment by dfong-adh** [comment]
Password storage discussed with Cory during Sprint Review - we can handle user passwords like other PII/PHI.

**Comment by dfong-adh** [comment]
Data retention policy is 60 days after positive confirmation of successful transmission to target system. See [Slack thread](https://dsva.slack.com/archives/C01CJV0L9PS/p1713806179805339) for details.

**Comment by dfong-adh** [comment]
PR for logging encryption status of evidence files: https://github.com/department-of-veterans-affairs/vets-api/pull/16545

**Comment by dfong-adh** [comment]
PR for storing evidence file data: https://github.com/department-of-veterans-affairs/vets-api/pull/16589

**Comment by saderagsdale** [comment]
@dfong-adh Hey Derek! Should this be moved to the `In Progress` pipeline, or `Validate` so we can test the AC?

**Comment by dfong-adh** [comment]
Sorry about that - moving this to `In Progress`.

**Comment by saderagsdale** [comment]
Review the sprint demo and see if the enablement team is okay with closing the ticket.

**Comment by dfong-adh** [comment]
This has been validated in staging and enabled in production. Followup tasks in #83132.

**Comment by shaunburdick** [comment]
Adding @kaipyroami just for historical visibility that the functionality to collect data was added as well as links to ticket for it's eventual removal.
