### ISSUE TITLE
Create tickets for Conf. Database as intended tool for Insights

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81209]
## Purpose
Following our discussion, establish the new tickets to get us where we're trying to go

## Tasks
- [x] Determine next steps from discussion session
- [x] Create new ticket work

## Acceptance Criteria
- [x] Next steps are captured in new ticket work
