### ISSUE TITLE
[CST] Provide better 5103 Notice "request" experience

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#81212]
## Value Statement
**_As a_** veteran receiving a 5103 Notice first person request in CST
**_I want to_** understand what that request means and what I need to do
**_So that_** I have access to evidence request information, can make an informed decision about whether I should waive my right to submit additional evidence, and have a direct on ramp to submit a 5103 waiver if I choose to do so. 

---
## Background Context

5103 Notices are one of the most common first party requests that appear in CST. Currently, there is an inadequate description of what these requests really mean. Veterans who file their initial claim on VA.gov (526EZ) have likely already submitted a 5103 waiver, but many who have filed through other routes have not. In some cases the 5103 development letter contains only boilerplate and is informational about the VA's duty-to-assist and the veteran's option to waive their right to submit additional evidence and possibly get their claim decided faster as a result. In other cases, the 5103 letter contains specific language about evidence that could be submitted to enhance the strength of their claim. 

Given the above and known technical constraints, 5103 request descriptions could include two distinct action items: 

1. download your 5103 notice letter from the CST claim letters section of CST
2. submit a 5103 waiver if you have no other evidence to submit. 

In addition to the action items, the description should clearly convey what the notice means, why they are receiving the message, and what the possible value of submitting a 5103 waiver is or isn't. 

<img width="401" alt="Screenshot 2024-04-23 at 11 23 33 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/91f5c0a3-9494-44e5-bae9-f34ac1f49771">

## Outcome, Success Measure, KPI(S), and Tracking Link
- More 5103 waivers submitted through CST
- More 5103 notices downloaded through claim letters section

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- If someone uploads a 5103 waiver, does the 5103 notice go away once that waiver is processed?
- If someone uploads a 5103 waiver, does the Ask for your claims section of CST go away? 
- 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] 5103 Request language clearly explains what a 5103 notice is.
- [ ] 5103 Request language clearly explains what a 5103 waiver is and in what scenarios it can be valuable to submit one.
- [ ] 5103 Request provides a path for a user to get access to their 5103 claim letters.
- [ ] 5103 Request provides a path for a user to be able to submit a 5103 waiver

```[tasklist]
### Tasks
- [ ] Remove feature flag cst5103UpdateEnabled and clean up code
```
