### ISSUE TITLE
[Design] My VA Form Status: Investigate claim application status display types

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#81227]
## Background
The My VA team continues to work with the VFF team on claim application statuses. As part of that effort, the My VA team needs to examine the variety of ways statuses can be displayed, and any potential changes that should be considered.

---
## Tasks
- [x] List the status differences
- [x] Document any considerations/alterations of what has been proposed by the VFF team
- [x] Explore opportunities for ways to improve the display of status on cards on My VA

## Acceptance Criteria
- [x] Documentation
- [x] Any new Figma mockups

## Validation
- Who can validate this ticket? PM

## Resources
- [VFF Figma file](https://www.figma.com/file/XAtdtChFlfwsHRvc7i6Dmd/WIP---Status-Project?type=design&node-id=0-1&mode=design&t=a88q3nuETL0Xchnw-0)

**Comment by mattmarino-adhoc** [comment]
There are only 3 possible statuses:
1. Pending: The form was submitted via VA.gov
2. Received: The form submission made it through Benefits Intake API and Central Mail, arriving safely in VBMS (or whatever the system of record happens to be)
3. Error: The form submission did not make it.

**Comment by mattmarino-adhoc** [comment]
For submission errors, we are considering two additions to the cards on My VA:
1. Tags having unique styling for errors - a red color as well as copy indicating action is required
2. An alert embedded in the card

**Comment by mattmarino-adhoc** [comment]
In addition, we may use this as an opportunity to flip the heading and the eyebrow text, for the sake of accessibility

**Comment by mattmarino-adhoc** [comment]
Extent of exploration captured in [VFF Figma file](https://www.figma.com/file/XAtdtChFlfwsHRvc7i6Dmd/WIP---Status-Project?type=design&node-id=0-1&mode=design&t=a88q3nuETL0Xchnw-0)

**Comment by mattmarino-adhoc** [comment]
Extent of exploration captured in [VFF Figma file](https://www.figma.com/file/XAtdtChFlfwsHRvc7i6Dmd/WIP---Status-Project?type=design&node-id=0-1&mode=design&t=a88q3nuETL0Xchnw-0)

**Comment by mattmarino-adhoc** [comment]
<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2E1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9980213bb5baa329411187591613b7cd58fbb49/Screenshot%202024-05-06%20at%203.27.10%E2%80%AFPM.png" alt="Screenshot 2024-05-06 at 3.27.10 PM.png" />


<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2k1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb9af2af08f2e610180eda5a27a2a3ad01311dea/Screenshot%202024-05-06%20at%203.26.32%E2%80%AFPM.png" alt="Screenshot 2024-05-06 at 3.26.32 PM.png" />

Current draft state of new benefit application cards
