### ISSUE TITLE
Design | Profile | Military Information | Incorporate veteran status card into Mil Info Figma file

### ISSUE THREAD

**Issue by pamela-drouin** [department-of-veterans-affairs/va.gov-team#81221]
## Background
The veteran status card UI content needs to be incorporated to the Military Information Figma file.

##  Todos

- [x] Copy content from the [VA Status Figma wireframes](https://www.figma.com/file/UwSvhj9Yn5trM5L5W3UgH0/VA-Status---Wireframes?type=design&node-id=86-446&mode=design&t=1tVp3xhOv7ltpK16-0) and paste everything to the [Profile team's Military Information Figma file](https://www.figma.com/file/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?type=design&node-id=1%3A6319&mode=design&t=Fuc3ci4o0vHdbeWS-1)
- [x] Update user flow
- [x] Make sure the veteran status card shows up on both mobile and desktop Figma pages

## A/C
- [x] veteran status card is now in the figma files

**Comment by pamela-drouin** [comment]
@mtcA6 the pointer section is not showing up on the right sidebar for me for some reason, but I'd estimate this ticket as a 3

**Comment by pamela-drouin** [comment]
Mobile and Desktop [mocks](https://www.figma.com/file/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?type=design&node-id=0-1&mode=design) are now updated
