### ISSUE TITLE
[Spike][CST] Provide better descriptions for PMR requests

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#81244]
## Value Statement
**_As a_** veteran receiving a Private Medical Record (PMR) request
**_I want to_** understand my options in ensuring that these requests are met
**_So that_**  the VA has the private medical information needed to decide my claim fairly

---
## Background Context

There is some confusion about whether these are first party requests at all (they're currently coming through as such). They are TECHNICALLY requests for private medical physicians/institutions to provide records, but it's currently unknown what the expected role veterans should anticipate playing in ensuring these requests are met.  Nevertheless, currently, they represent the biggest proportion of evidence requests in CST. 

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- What is a reasonable expectation in terms of veteran responsibility to make sure these documents get submitted?
- Does the VA want veterans to play an active role in ensuring these documents get uploaded even though they are technically requests for private physicians? 
- How does the VA pursue these requests right now? 
- What does the VA's duty-to-assist look like in practice as it relates to collecting these records? 
- How does this request relate to 21-4142 waiver allowing VA to track down personal records? 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Veteran is able to understand their relationship to a PMR request (if there's something for them to do in relation to it, they know what that is).
- [ ] PMR request title is clear and helps the claimant understand what it is.
- [ ] Description of PMR request explains clearly what it is and why it's important to their claim
- [ ] Description of PMR request provides advice on how the veteran can help fulfill the request and ensure the evidence is submitted
