### ISSUE TITLE
[CST] Link to Claim Letters page from VA Disability Compensation page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#81245]
## Background Context

See [original ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79846) and [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81061) for more details.

We want to add a way to navigate to the Claim Letters page from `va.gov/disability/`

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

[View in Figma](https://www.figma.com/file/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation?type=design&node-id=1268-3914&mode=design&t=8MnQMrVK6qbvdiTG-11) - WIP NOT YET FINAL

Proposed

<img width="457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5d46216654737405c45bc153dd3ef83e52aee20/Screenshot%202024-04-22%20at%2011.16.13%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 11.16.13 AM.png" />

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _In the "Manage your disability benefits" section of the `VA Disability Compensation` page, add a link to the claim letters page with some body text below explaining what the claim letters page does_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by jstrothman** [comment]
Similar to the [issue for adding a Claim Letters link to the VA benefits letters & documents](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81243), the Disability Comp page has a link to `Check your claim, decision review, or appeal status` but the link doesn't mention getting your claim letters. This work can be addressed by having a conversation to make a recommendation to the unauthenticated content team.
