### ISSUE TITLE
SPIKE | Dependent Card Info

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81240]
## Issue Description
_As a user, when I view my "view dependents" page on VA.gov, I want to understand more information about my dependents, so I can accurately verify them._

CURRENT CARD:
<img width="421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0YvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21b441d6ecc6a4e3fac66b01bed9d2404bfe3d5d/image.png" alt="image.png" />

IDEAL CARD:
<img width="550" src="https://github.com/user-attachments/assets/d2aa002c-7f24-4802-ac9e-b41baf4b78cc" alt="image.png" />
[Figma file](https://www.figma.com/design/bvj72inycD0iZkuCbjYTWL/Dependent-Verification-MVP?node-id=210%3A12530&t=0K9ybqS2Qs2iMvfP-1)

Related engineering ticket: #87272
- We can utilize the service through bgs `bgs.people.find_dependents` for a few of these details as well as information returned by `bgs.diaries.read_diaries`.

---
## Tasks
- [x] Research if we can add what benefit each dependent is on (e.g. API)
   - **find_dependents.award_ind** (is this the correct value?)
- [x] Research what options can be pulled in for the current "relationship" value that is displayed (e.g. child, spouse, etc.)
   - (**find_dependents.ptcpnt_rlnshp_type_nm**)
- [ ] Research if we can add the status for each dependent (e.g. student, child incapable of self-support, etc.)
- [ ] Research if we can add the date the dependent was added to the benefit.
- [x] Research if we can add the date a child will be removed from a benefit bc they turn 18 or leave school
   - In **read_diaries.dependency_dec** get the **award_effective_date** for the element that has the **person_id** of the dependent and a **dependency_decision_type** of "T18" (Also possibly T23 or SCHATT[School Attendance Terminates])

## Acceptance Criteria
- [x] Determine if we can add what benefit each dependent is on (e.g. API)
- [x] Determine what options can be pulled in for the current "relationship" value that is displayed (e.g. child, spouse, etc.)
- [ ] Determine if we can add the status for each dependent (e.g. student, child incapable of self-support, etc.)
- [ ] Determine if we can add the date the dependent was added to the benefit.
- [x] Determine if we can add the date the dependent will be removed from the benefit.
---

**Comment by steele-lm** [comment]
Swagger documentation: https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#

**Comment by ajialeilani** [comment]
You can find the current iteration of potential improvements [here](https://www.figma.com/design/bvj72inycD0iZkuCbjYTWL/Dependent-Verification-MVP?node-id=210%3A12530&t=0K9ybqS2Qs2iMvfP-1) in the Figma verification playground. 

![Enriched card](https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/3f8182ab-f3d3-4737-8c8c-6f6bcb7047e3)


Possible improvements pictured here: 

- Type of benefit the dependent is on (Disability, pension, DIC)
- Non-relationship dependent descriptions (e.g. student, permanently incapable of self-support)
- Planned date of automatic removal based on dependent's 18th or 23rd birthday and messaging giving context to this
- Link out

Other possible improvements not pictured here

- Active/inactive label to indicate whether the dependent is currently or was formerly listed as a dependent on the Veteran's benefits. The cards on Your VA Dependents appear under headers that make this clear, but including the information on the card might allow us to use the cards elsewhere out of this context
- Information about other benefits: Healthcare benefits, GI Bill, etc. This would involve a lot of collaboration with other teams to see if this even makes sense to try to implement, but it's on our radar.

**Comment by steele-lm** [comment]
Tyler uncovered that these values are associated with Dependents:
"Dependency Established", "Spouse"
"Eligible Minor Child", "Minor Child"
"Turns 18", "Not an Award Dependent"
"School Attendance Begins", "School Aged Child"
"School Attendance Terminates", "Not an Award Dependent"

**Comment by ajialeilani** [comment]
Have we confirmed that the dependents listed here are related to disability compensation, pension, and DIC? The subhead copy on the published page still only says disability comp.

**Comment by ajialeilani** [comment]
From David Reis:

I’d like to see info about when the dependent added to the award. (Sometimes a Veteran will divorce a spouse and remarry the same spouse, for example, so processors would need to know if the most recent time they became a dependent has been recorded as well as the lapse between). 

This information lives in VBMS. May not yet be in an API.

**Comment by ajialeilani** [comment]
David Reis also suggested that reward type might not be a useful addition, because Veterans can only have one type of benefit at a time, and they (hopefully) know which one it is.

**Comment by evansmith** [comment]
@steele-lm @mjknight50 

We will want to confirm these attributes with the BGS/RBPS teams to make sure they mean what I am interpreting, but here is what I've got so far:

`Date dependent was added to benefit`: Through the BGS::Service find_dependents method there is an attribute `:begin_dt` nested in dependent. Additionally, through the DependencyVerificationService, within the dependency_decs there is an `:award_effective_date`. I was using staging data and those dates were not the same. I would be curious to learn which one would be best.

`Date dependent was removed from benefit (for inactive dependents)`:  Through the DependencyVerificationService, within the dependency_decs there is an `:award_effective_date` and if the `dependency_decision_type` is either T18 or SCHATTT
then it could possibly be inferred that award_effective_date is the removal of this dependent. 

`Benefit dependent was added to (pension or disability)`: I have not been able to find this one yet. There is an award_type on the dependency_dec, but I am not sure what it translates to. This would be a good follow up for BGS/RBPS. 

`Reason dependent was removed from benefit`: This is included as part of the dependency_decs in the DependencyVerificationService. There is a `:dependency_decision_type` and `:dependency_decision_type_description`, one is a code like T18 or SCHATTT and one is a slightly more descriptive text like "School Attendance Terminates"

**Comment by steele-lm** [comment]
@evansmith I created a spike (#109338
) for the LSS team to work with RBPS to confirm if the data fields you uncovered communicate the correct information.
