### ISSUE TITLE
[CST] Navigate to Claim Letters page from Letters app

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#81243]
## Background Context

See [original ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79846)

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

[View in Figma](https://www.figma.com/file/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation?type=design&node-id=1250-3973&mode=design&t=8MnQMrVK6qbvdiTG-11) - WIP NOT YET FINAL

WIP Design
<img width="428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31d841909277d66f564387bf912fcde03ec375bd/Screenshot%202024-04-22%20at%2011.09.48%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 11.09.48 AM.png" />

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Do we want to include an alert towards the top of the page?

## Tasks
- [ ] _Add an alert in the "What types of claim letters can I download using this tool?" section that informs users that if they're looking for claim letters they should go to the Claim Letters page. Include a link to the page in that alert body text._
- [ ] _Add a link to the "What if I want to download a letter or document that isn't available in this tool?" section of the Letters app that links to the Claim Letters page_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by pmclaren19** [comment]
@skylerschain we cant see these images please update before we work on this
