### ISSUE TITLE
BE | Profile | Direct Deposit | Post migration clean up

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#81264]
## Background
I want to clean up direct deposit vets-api code after the migration is complete so that the code base is more streamlined and intuitive.

##  Tasks
- [x] Remove unused feature flags
- [x] Update naming conventions
- [x] Update logging
- [x] Remove legacy code
- [ ] Remove old templates
