### ISSUE TITLE
Setup/finalization of the FDG Related Resources page

### ISSUE THREAD

**Issue by gopixelsgo** [department-of-veterans-affairs/va.gov-team#81260]
## Purpose
In the _Identify what related resources should be included on the FDG - #69448_ ticket we finalized the resources that will be useful to users, and the best format for presenting them. 

This is where we'll continue formatting and finalizing [that page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3096281089/Next+steps+for+FDG+Related+Resources).

## Tasks
- [x] Setup and place [page](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3096281089/Related+Resources+for+Forms+Digitization) in the appropriate location in the FDG
- [x] Finalize and link sub-sections for each resource
- [x] QA - check all links

## Acceptance Criteria
- [x] Related Resources page content and format finalized
- [x] Page is placed in the appropriate location within the FDG
