### ISSUE TITLE
[CST] [BUG] VAFileInput unable to add a file that was previously removed

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#81265]
## Issue Description
In the file upload forms in the CST, when a file is added to be uploaded, but then removed, you can't re add the file. You can only add a file with a different name. 

https://github.com/department-of-veterans-affairs/va.gov-team/assets/105806934/a5a38472-1024-4256-95fe-f2e6385f5f21

Cause may be in the chain of redux actions or on the VaChange event. 
---
## Tasks
- [ ] Determine cause of bug and fix it

## Acceptance Criteria
- [ ] A user can add a file, remove it, and re-add the same file
---
## How to configure this issue
- [ ] Test form at `/track-claims/your-claims/{CLAIM_ID}/files`
- [ ] Test form at `/track-claims/your-claims/{CLAIM_ID}/document-request/{*}`
- [ ] Add a file, remove it, then try to add a file again

**Comment by jerekshoe** [comment]
I think this might be roughly what is happening: https://stackoverflow.com/questions/26634616/filereader-upload-same-file-again-not-working. From what I can tell it works fine as long as you upload a different file than the one that was removed. I'm guessing it's because the value of the `input` gets set to the path of the file that had just been uploaded (and subsequently removed) so when attempting to upload the same file, the value of the input doesn't change and the input in the shadow DOM's `onChange` doesn't get triggered

**Comment by pmclaren19** [comment]
> I think this might be roughly what is happening: https://stackoverflow.com/questions/26634616/filereader-upload-same-file-again-not-working. From what I can tell it works fine as long as you upload a different file than the one that was removed. I'm guessing it's because the value of the `input` gets set to the path of the file that had just been uploaded (and subsequently removed) so when attempting to upload the same file, the value of the input doesn't change and the input in the shadow DOM's `onChange` doesn't get triggered

@jerekshoe , yea yesterday I pair with @samcoforma on this and we had the same findings! I also took a look at the component in Storybook and it appears to do the same thing... so this might be a bug on the platform design since of things. Going to double check our logic to make sure there isnt anything on ourside they we cant change but otherwise ill reachout to platform design about this!

**Comment by pmclaren19** [comment]
Been investigating with the team and we think that this is a platform design issue that will require them to update the VaFileInput component. Reaching out to them to see if this is something they are aware of and can fix.

**Comment by pmclaren19** [comment]
Talked to platform they created a bug ticket for this [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2780) and asked that we crate the pr for it and fix it!

**Comment by pmclaren19** [comment]
Created a pr [here](https://github.com/department-of-veterans-affairs/component-library/pull/1135) and merged. Talked to @jamigibbs and vets-website will have this change this Wednesday or Thursday. Once its merged ill verify all looks good and then close!

**Comment by pmclaren19** [comment]
The change has been merged into vets-website! Verified locally and in staging that this was working and this bug is now resolved.

**Comment by pmclaren19** [comment]
Verified in staging and looks good!
