### ISSUE TITLE
[Design] Create hi-fi mock ups

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81287]
## Tasks

- [ ] Create hi-fi mock ups at tablet-size based on [low-fi user flows](https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?type=design&node-id=75%3A1321&mode=design&t=nuTCnJXda47uFsi4-1)
- [ ] Through creating the hi-fi mock ups, identify gaps of new pages we'll need to create that we didn't account for 

## AC

- [ ] Completed hi-fi mock ups
- [ ] Identified gaps of new pages we'll need to create that we didn't account for
