### ISSUE TITLE
[DA, FE] 10-10CG - Improvements: Update URLs to align with VA.gov standards

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#81299]
## Background
While reviewing the latest form updates for the 10-10CG, we discussed updating the current URLs to a more meaningful URL that also aligns to VA.gov standards. 

Reference [URL Standards in the Content Style Guide](https://design.va.gov/content-style-guide/url-standards)
- [URLs must be structurally accurate](https://design.va.gov/content-style-guide/url-standards#urls-must-be-structurally-accurate)
- [URLs for 10-10CG]

## Tasks
- [ ] URLs are updated
- [ ] Redirects are requested/submitted
- [ ] Analytics ticket is submitted to update URLs in Domo and GA

## Acceptance Criteria
- 10-10CG URLs are updated to VA.gov standards

**Comment by kristinoletmuskat** [comment]
Hey @hdjustice, were hoping to implement this redirect around 6/13. I wanted to check on whether that timeline feels doable for you all. We will have to have the new URLs live before we can publish the redirect.

**Comment by hdjustice** [comment]
Hi @kristinoletmuskat, our engineer @longmd is out until next week, and we have at least one high priority item that needs immediate attention.  I can chat with Matt on Tuesday to see if that is doable for us.

**Comment by kristinoletmuskat** [comment]
ok cool @hdjustice. If we don't have time to create the new URLs, ideally we could at least adjust the breadcrumbs (otherwise a user trying to get back to the new family member hub would have a tough time). 

We also updated our launch date -- if you had time to do the URLs, they would need to be in production by Monday 6/17. If just the breadcrumbs, those would need to be in production by Tuesday 6/18 after 3pm.

The new breadcrumbs would be:

VA.gov home > [Family and caregiver benefits](va.gov/family-and-caregiver-benefits/) > [[Health and disability H1 TBD](va.gov/family-and-caregiver-benefits/health-and-disability/)] > Apply for the Program of Comprehensive Assistance for Family Caregivers

**Comment by hdjustice** [comment]
Hi @kristinoletmuskat - Matt and I chatted about this and the work has begun!  We should have no issue meeting the delivery date

**Comment by kristinoletmuskat** [comment]
Hey @hdjustice, I wanted to check whether ya'll had communicated this upcoming change to your VA partners? Add if not, could ya'll do that? Do you have any concerns about their reaction? Or could we support in any way?

**Comment by hdjustice** [comment]
Hi @kristinoletmuskat - We have a meeting with our Caregiver stakeholders this Friday and we will be informing them of the update.  Not sure on their reaction, but we will report back anything that comes out of the conversation.

**Comment by kristinoletmuskat** [comment]
Hey @hdjustice, just confirming whether you confirmed these changes with your stakeholders?

**Comment by kristinoletmuskat** [comment]
Hey @hdjustice -- Just checking in on the URL -- I went to [va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg/](url), but it seems to be redirecting to the old URL of https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction?

**Comment by longmd** [comment]
Hi, @kristinoletmuskat . What you're seeing is intended behavior at the moment. Without getting too in the weeds, our React app is deployed to two different page routes, but it only recognizes one as its root home. 

Once all the redirects go to prod and all the routes are available, we can tell it that its root home is the new URL and it won't change the URL bar. While it looks like from the URL bar it's redirecting.. it's just internally correcting itself for where it thinks is home.

**Comment by kristinoletmuskat** [comment]
Hey @longmd -- our redirects are now merged according to[ this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83558), but this form is still going to the old URL. Is there something ya'll need to do on your end? Feel free to coordinate directly with Chris Kim in the linked ticket if you need!

**Comment by longmd** [comment]
@kristinoletmuskat , yup! We just have one minor update to tell the app where its new home is. I have that queued up to go out here in just a little bit.. I will follow up when that has been updated.

**Comment by longmd** [comment]
@kristinoletmuskat , the root URL has been been updated. You should be all good to go.

**Comment by kristinoletmuskat** [comment]
Verified in prod! Closing this ticket.
