### ISSUE TITLE
[Spike] [CST] Investigate UI for non disability compensation claims - V2

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#81304]
## Background Context

Currently we use the same UI for non disability compensation claims that we use for disability compensation claims. This is due to the current technical architecture. 

Regardless of whether or not we can parse out these claim types and create bespoke UIs, we should investigate what non disability compensation claims will look like in V2 (Status and Overview tabs in particular) to see whether or not there are major user experience issues.

We should probably not launch [Claim Phases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71293) until we've done this due diligence.

(Updated) claim types accessible in CST as seen on [CST home page](https://staging.va.gov/claim-or-appeal-status/):

<img width="787" alt="Screenshot 2024-04-24 at 4 26 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/85cf4f73-0f12-4547-b17e-e56d0ebcc811">

## Design
- Add here

### Enablement team (if needed)
@jstrothman 

## Assumptions
- Working assumption: When UI gets updated for one claim (disability compensation) it gets updated for all claims.

## Out of scope
- Add here

## Open questions
- What happens during the "rating" steps for claims that don't require a rating? Andrew mentioned that those steps get "skipped". What does this look like on the front end?
- How might we remove unnecessary UI states for claims that don't go through all the same steps as a disability compensation claim?
- How are VBMS claim statuses handled for non-disability comp claims? Are they the same?

## Tasks
- [ ] Identify the different classes non disability compensation claim types
- [ ] Work with Andrew to document the process for each of these classes of claim type
- [ ] Document what the V2 UI looks like for each of these claim types
- [ ] Identify and document any major user experience issues
- [ ] Determine what UI could or should be for these different classes of claim type

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Non disability comp claim types have been identified
- [ ] Screenshots have been produced for what the Status and Overview tabs look like in V2 for these claim types
- [ ] Glaring user experience issues (if any) have been documented for further consideration
- [ ] UI proposals for different classes of claim types have been created
