### ISSUE TITLE
[xcred VSOs][Prototype] User Testing - Participant Mgmt

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#81312]
## Description
Placeholder ticket for all participant management related to the prototype v1 user testing study. Owner of this ticket will be responsible for assigning out and closing all tasks related to participant management.

### Tasks
- [ ] Creating and managing a test sessions tracker spreadsheet, uploading to Sharepoint folder
- [ ] Creating Zoom Scheduler for scheduling sessions with users (once Harold confirms we can use)
- [ ] Sending recruitment messaging to participants from our panel via VA.gov email
- [ ] Using the team Zoom account to add sessions to the schedule tracker and the study's Slack channel
- [ ] Sending reminder and thank you emails to participants around sessions
- [ ] Updating the participant panel

### Collaborators
Lead: @RenataKeck 
Contributor: @uxrebecca 

### Resources
- [Recruitment strategy]
- [Sharepoint folder]
- Team template
- [Study Slack channel]
- Participant panel

## Acceptance Criteria
- [ ] Study sessions tracker spreadsheet has been completed for the study
- [ ] Participant panel has been updated to reflect most recent round of testing

**Comment by kristen101606** [comment]
We didn't get to this research before the end of the contract. Future teams can reference the [Future Research Activities Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718980793805/b1c89e3110a00b235ee30bc04bab3cc96a33c696?sender=u2a4240a640b257ce33545495) and create tickets for the research they want to run first.
