### ISSUE TITLE
[Epic] My VA form statuses & form confirmation page updates (collab with Auth Experience & Veteran Facing Forms)

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#81317]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to start collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

**Note:** If you’re already partnering with us on an initiative, you don't need to fill out this request form. If you don’t have access to your initiative’s CAIA epic, post a message in the [#sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-acessibility-ia) slack channel and tag `@Terry Nichols` and `@Lily Strelich`.

## About your team

- **Team name**: Authenticated Experience & Veteran Facing Forms
- **OCTO product owner:** Matthew Dingee & Chante Lantos-Swett
- **Product name:** My VA form status
- **Product manager:**  Tricia Baker & Anastasia Jakacin (AJ)
- **Slack channel:** veteran-facing-forms
- **Dedicated content writer on your team (if you have one):** `Insert name and/or GH handle`
- **Dedicated a11y specialist on your team (if you have one):** Jeana Clark
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

We are partnering with Authenticated experience team to display the status of the forms on My VA and also updating the confirmation page to show more detail.  
We need assistance with content for the status taxonomy (nomenclature) and what to display to the user. Assistance on the confirmation page on next steps after the user completes the form.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We are going to do usability research planning targeting research plan to be completed by end of April

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [x] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** [`80272`](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/80272)

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Supporting artifact <name>](https://va.gov) `placeholder link`

 [x] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712670304475/d2f331ee0056d49ca12e46a4dba093783cedb16e?sender=ud94436ff2bf5d5ce166a5253)

- [x] [Wireframes](https://www.figma.com/file/XAtdtChFlfwsHRvc7i6Dmd/WIP---Status-Project?type=design&node-id=0-1&mode=design&t=MKFqASkX60vIs8eX-0)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [x] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA a11y tasks
- [ ] **PENDING** Future work, VFS Team doing discovery work as of 4/24/2024
- [x] Attend KO Call 4/24/2024 (Jamie and Sara)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83382
```

```[tasklist]
### CAIA content tasks
- [x] Attend KO Call 4/24/2024 (Laura/Lily)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83810
```

```[tasklist]
### CAIA IA tasks
- [ ] **PENDING** Future work, VFS Team doing discovery work as of 4/24/2024
```

```[tasklist]
### CAIA Ops Tasks
- [x] Hold Kickoff Meeting 4/24/2024
- [x] [Kickoff Meeting Notes Doc](https://docs.google.com/document/d/1KU3_qcYWTIaByfMakkC4oIjjUqB_UroYaTKshW0S8_s/edit?usp=sharing)
- [ ] **PENDING** Future work, VFS Team doing discovery work as of 4/24/2024
```

```[tasklist]
### Related CC intakes
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/80272
```

**Comment by laurwill** [comment]
Hi @jeana-adhoc @mattmarino-adhoc , 
I know there's still some discovery happening around the statuses, but wanted to document some of the questions and concerns we've talked about in syncs, slack, and figma over the past week or so, and also share where I'm at in my current thinking about the content here. cc @aprocik1 

## Distinction between "claims" and "benefit applications"
- This is a false distinction. There are claims in both sections, applications in both sections, and supporting forms that are neither claims nor applications in the "benefit applications" section. A more accurate way to rewrite the "Claims and appeals" and "Benefit applications" headers in [this My VA screen](https://www.figma.com/file/XAtdtChFlfwsHRvc7i6Dmd/WIP---Status-Project?type=design&node-id=149%3A2062&mode=design&t=D6GWYJvYtBnPmxTM-1) would be "Forms that show up in the claim status tool" and "Forms that don't show up in the claim status tool"
- This is a long-standing problem. You all aren't creating this confusing distinction around "claims" vs "applications," but this work will require us to confront this confusion.
- One option is to ditch these 2 sections and create new sections for **Draft online forms,** **Submitted online forms**, and **Claims, applications, and requests you can track in the claim status tool**

## New statuses in My VA and how they line up with statuses in CST
- We started a Mural here to map out how these statuses might relate: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714748484848/30f2f68ec5e59229ea0014cbc574e3e372ffbe2e?wid=0-1714748539102
- We have a couple different ideas going — for the purposes of this note I'm using "Submitted" instead of "Pending," but that might change.
- Initial claims in CST start with "Claim received" status and then move to "Initial review," but decision reviews and appeals don't include a "Received" step — they go directly into a review step. So to make these new My VA statuses line up logically across both initial claims and decision reviews in the CST, we may have to also adjust the CST statuses.
- At least one type of form (Board Appeals) has an "intake" process involving VA staff that happens between submission and receipt in the CST. So in a very real way, we have received that form and have already started processing it before these new statuses would mark it "Received." 
- One option is to ditch the "Received" status in My VA. I think the big added value in these new statuses comes from a "Submitted" status (to give the user a record of their submitted forms) and the error messages. 
- The way I'm translating "Received" is "The thing you assumed already happened when you hit the submit button has now, in fact, happened. The form you submitted was actually submitted, and we actually have it in our system." The status change to "Received" doesn't give the user any information about how long it will take us to process the form. It just means "there was not an error." Is this correct?
- Instead of asking users to monitor their My VA screen to make sure the form changes from "Submitted" to "Received," can we trigger a direct notification to the user when there's an error? 

## Supporting forms as standalone forms vs attachments to a claim in CST
I think we need to better understand how supporting forms appear in My VA vs when they're just one of several documents VA uses to decide a claim we're tracking in CST. I'm imagining this possible order of events. Is this possible? 
- Veteran submits a 526EZ (disability claim)
- That claim goes from "Draft" to "Submitted" to "Received" in the new My VA statuses
- Then it shows up in the CST as "Received" and goes through a process list of 4 more statuses (7 in upcoming changes)
- In step 3 of that CST process list "evidence gathering," VA decides we need private medical records to support this disability claim
- VA tells the Veteran to submit this "authorization to release medical records" form so we can get the records
- Veteran submits this authorization form online, and we show them a process list with TBD steps on the confirmation page
- Then this authorization form appears in My VA and goes from "Submitted" to "Received." That's the end of the statuses we show for this form.
- At the same time, back in the CST, this form appears as a document attached to the original disability claim (maybe, we'd need to confirm). The CST doesn't track the status of this form independently, but continues tracking the status of the disability claim.

## Process list on confirmation page
- When we have enough information to provide a more specific "What to expect next" list for different forms, we'll need to talk about how this list relates to the process list in CST.
- Could we wait to add any sort of process list until we have specific information? Right now we have 3 steps:
         - The first step isn't a "what to expect" step. It's the submission step, which already happened.
         - The second step is asking the Veteran to monitor My VA to make sure the "submit" button did what they assumed it would do. Is there any way to put this burden back on VA by triggering direct communication off the error message, instead of asking Veterans to do this? 
         - The third step is a placeholder because we don't have the specific next steps for VA
- One option is to go back to the current language we use in "What to expect" content on confirmation pages: "We'll review your form and contact you if we need more information." And then add any specific info we know about, like "We'll send you a letter in the mail with our decision. It can take up to 6 weeks to get a decision." Would this approach make sense until we can do more tailored versions?

**Comment by laurwill** [comment]
Updates from our sync just now:
- Another meaning/value of "Received" status is that now the Veteran can contact a call center, etc, and VA staff will be able to see the submitted form in VBMS or another back end system
- Question: Can we send a second confirmation email when we receive the form?
- We discussed possibly testing a version with a more transparent explanation of the lag time between submission and receipt
- We discussed the burden of "check for status updates" on the Veteran and potential ways to avoid that burden, like notifying Veterans every time there's a post-submission error
- User testing may include a card sort of different status label options and other terms
- Laura will keep working with Matt and Jeana on a prototype for user testing — we discussed the many open content and product questions we'll need to answer before implementing this work, but the goal is to get an MVP version in front of Veterans for feedback

**Comment by laurwill** [comment]
Hi @mattmarino-adhoc @jeana-adhoc , summarizing here the initial content updates we made yesterday for the planned MVP launch of this feature on 7 forms only, and outstanding content concerns about the MVP that I want to document and return to post launch. (And @jeana-adhoc I still need to update the confirmation page content, I'll slack you about that). Apologies in advance for this github novel, I know you've heard and discussed a lot of this with me several times. And thank you both so much for your collaboration and your patience with my many content questions!

**Changes to feature content in My VA section:**
- Changed "submitted" status to "submission in progress" 
- Changed next step on submitted cards from "we'll prepare your form for review" to "we'll confirm that we've received your form"
- Drafted content for the "if you can't find your application or form" accordion

### Content concerns with MVP launch on 7 forms
- We didn't specifically test the scenario of launching post-submission statuses on a small subset of forms, so we don't know how Veterans will interpret the "submission in progress" status showing up on some but not others
- By adding "submission in progress" and "received" statuses only to certain forms, we're implying that any forms people submitted online that disappear after they hit submit were **not** actually submitted or received
- We're hiding the explanation of this confusing situation in an accordion, and we're also showing the confusing explanation to everyone who visits My VA, not only to people who submitted one of these 7 forms (I looked at this with @DanielleThierryUSDSVA and we made some edits, but not sure this explanation will be enough)
- We're placing the post-submission cards in the same section with the draft cards, which makes it harder to explain the weirdness of only 7 forms persisting after submission
- I think there's a very good chance that people who submit one of these 7 forms **and** another form that's not in the MVP will see one form persist in a submitted state, see the other form disappear after submission, and assume that we lost one
- We aren't able to offer any useful information about what happens to other forms after submission. I thought that we could now say we are catching all submission failures, but if that is not the case, all we can say is "if your submitted form doesn't appear here, that doesn't mean we didn't receive it." Since it also doesn't mean we **did** receive it, we're introducing ambiguity about the status of all other submitted forms without offering any clear next step of reassurance.
- Value of showing the "submitted but not received" status, especially on these 7 forms, is still a bit unclear to me. 
      - This feature calls into question the reliability of the "submit" button and introduces the accurate but wacky situation where we are submitting the form to ourselves in the backend for 10 days and don't know if we'll succeed. And then we put the burden on the Veteran to monitor for status changes to make sure it didn't fail.
      - If and when we're confident that we're actually catching all submission failures, we don't need to introduce this concept at all — we can rely on direct communication about failures, use "Submitted" as a single post-submission status in My VA that means "you hit submit and we received it unless we tell you otherwise", and show error alerts on forms we fail to receive.
      - We're already confident we're catching all submission failures on the 7 MVP forms (I think? or else we wouldn't be able to show these statuses, right?), so it now occurs to me that in a way, we're launching the feature on the only 7 forms that people don't need to monitor the submission status of.

**Content options we discussed that aren't in MVP, that we'd like to return to post-launch:**
- Split the submitted forms into a separate section from draft forms, at least until we show post-submitted status on all online forms
     - **Note:** This is just an interim suggestion until we're able to address the larger concern of how these forms interact with forms that show up in CST. I think the ideal state we discussed is that My VA would have 1 section for all draft forms and 1 single section for all submitted forms that shows the full process from submission through processing through final decision/action.
- If not different sections, split the "if you can't find" accordion into 2 accordions to make it slightly clearer
- Consider showing only "Submitted" and "Action needed" statuses and rely on direct communication about failures

### Other remaining broader content concerns with this status feature
- Connection to forms that appear in CST is unclear. At least some of the 7 forms in MVP may also appear as uploads on claims or applications we show in CST. If and when we add post-submission statuses on forms that do appear in CST, we'll need to confront how all the various statuses line up together.
- Terminology issues around use of claims, applications, and forms — we'll track in a content brief

**Comment by coforma-jamie** [comment]
@jeana-adhoc and @mattmarino-adhoc, checking in on this ticket. Do you think we can close this out? Is this live? :)

**Comment by jeana-adhoc** [comment]
Yes - We can close this. This is live.
