### ISSUE TITLE
Styling Updates for Widget

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81333]
## Background
Michael caught some small styling updates that need to be addressed for our Widget MVP, ideally prior to launch.

## Tasks
- [x] **Auth no rep, Auth individual, Auth organization (3 states)**:  Implement the [standard drop shadow](https://design.va.gov/storybook/?path=/docs/components-va-card--with-drop-shadow) around the status card
- [x] **Error (1 state)**: Seems to be some additional padding being added to to the <p> tag that isn’t on the default alert in storybook. This is throwing off some of the vertical rhythm and adding some additional padding below the final `<p>` tag in the error alert.  See screenshots below for additional context.

In Find a Rep Staging (actual):
<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3VDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4906643ce3d94ab481275d4da4517f8694d52413/image.png" alt="image.png" />

vs. Storybook (expected):
<img width="1594" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f81f6db31061edfe30560ab5330c449edfec53d2/image.png" alt="image.png" />

## Acceptance Criteria
- [x] The design of our Rep Status Widget aligns with our designs, and the most up-to-date VADS patterns.

**Comment by mtri** [comment]
Looks good!
