### ISSUE TITLE
Remove feature toggle code from NoK/EC

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#81337]
### User story

As a Cartography team member, I want to remove feature toggle and logic from the NoK/EC code, so that the code is simpler for future dev and maintenance.

### Notes
- Prereq: feature has been at 100% of users for 2 weeks. (Went to 50% on 4/22/24)
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-health-care-contacts/release-plan/release-plan-mvp-mar-2024.md

### Tasks:

- [x] Remove feature toggle from `vets-api`
- [x] Remove feature toggle from `vets-website`
- [x] Merge changes and wait for changes to propagate to envs.
- [x] Run `Flipper.remove(:profile_contacts)` in development (dev-api.va.gov).
- [x] Run `Flipper.remove(:profile_contacts)` in staging (staging-api.va.gov)
- [x] Run `Flipper.remove(:profile_contacts)` in sandbox (sandbox-api.va.gov
- [x] Run `Flipper.remove(:profile_contacts)` in production (api.va.gov)

## Acceptance criteria

- The [steps for removing a feature toggle](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles) from vets-api and vets-website have been completed
- Feature toggle and associated code removed from vets-api and vets-website repositories

**Comment by radavis** [comment]
To verify this work, visit `{dev-,sandbox-,staging-,_}api.va.gov/flipper`, press CTRL+F (CMD+F) and search for `profile_contacts`. No results should be displayed.

**Comment by radavis** [comment]
Checking `{dev,staging,sandbox}-api.va.gov/flipper` shows no occurrences of `profile_contacts`.

However, `api.va.gov/flipper` shows `profile_contacts`.

Wait until deploy and re-request removal.

**Comment by allanto-ah** [comment]
@radavis I still see this feature toggle in the production environment, api.va.gov. Is this expected?

<img width="1995" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47cb9369fb511f8faa1fefb6f6dc568c9807f442/Screenshot%202024-07-09%20at%208.36.46%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 8.36.46 AM.png" />

**Comment by radavis** [comment]
@allanto-ah, This is definitely not expected behavior. I filed a support request for this issue as it seems there's something happening that is adding `profile_contacts` and `mhv_landing_page_enabled` feature toggles to the database after it has been removed from the codebase and database.

**Comment by allanto-ah** [comment]
@radavis 

The feature toggle is still showing in production environment, api.va.gov

<img width="1699" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlRkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--929b3070b9e75378f492b682b076a1c838d20d0c/Screenshot%202024-07-15%20at%208.54.58%E2%80%AFAM.png" alt="Screenshot 2024-07-15 at 8.54.58 AM.png" />

**Comment by wesrowe** [comment]
Friends, I seem to recall that in 2023 my team tried to remove a bunch of feature flags and ran into this same problem. I would advise asking Platform whether this is a known issue.

**Comment by allanto-ah** [comment]
@wesrowe Yeah, Richard has already reached out to Platform in regards to these: [link](https://dsva.slack.com/archives/CBU0KDSB1/p1720808510081399). It seems to be something that works sometimes and not all the time. He was able to get it to work for [81709](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/81709), but seems like it didn't work for this one.

**Comment by radavis** [comment]
Looks like I missed a line...

department-of-veterans-affairs/vets-website#30949 removes `profile_contacts` toggle from `featureFlagNames.json`

**Comment by carlosfelix2** [comment]
Checked and the `profile_contacts` toggle has been remove from staging and prod.

**Comment by allanto-ah** [comment]
Environment: Staging, Production

Verified that the EC/NoK is still being shown as expected. No regression issues.
