### ISSUE TITLE
Initial Download: Support Bot Takeover (Brandon)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#81335]
## Description 
Historically, Kerry Powell and Curt Bonade have owned the work related to the Support Bot upgrades. We are working to have an internal SME to reduce the load on both engineers (Brandon Dech). 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Alyssa to reach out to Joe Tice to discuss borrowing Curt for a Zoom call to discuss
- [ ] Identify what it would take to move the work back to our team 
- [ ] Establish level of effort needed from Curt to make the transition and determine if there is bandwidth
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Had to move meeting to next sprint. Moving ticket as a result to the upcoming sprint. Meeting will be on May 22.
