### ISSUE TITLE
Support Request via Wrong Slack Channel 

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#81343]
A support request came in, not via the support channel, but via our own Platform Content Channel on Slack. But due to the the nature of the issue, the requestor should have used the support channel. Since they did not. I am creating a ticket for it. 

Here is the slack thread for reference: https://dsva.slack.com/archives/CL181NRJQ/p1713815936723179

Requestor asks if Scroll Viewport/PW can support png images and/or graphics within tables and within table headers. To answer this request, we will have to create a test page in the test space, making sure that the test page includes a table. Then we will need to attempt to put an image in the table and another image in the table header. Then we will need to "deploy" the test page via the Sandbox. Then check to see if the images appear where and how they should appear. 

### TASKS:

- [x] Create test page in Test Space
- [x] Add table to test page
- [x] Add image to table cell
- [x] Add image to table header cell
- [x] Save changes to test page
- [x] "Deploy" test page via Sandbox
- [x] Verify Changes translate to live page
- [x] Make any adjustments, if necessary
- [x] Communicate findings to requestor

### DEFINITION OF DONE

- [x] Requestor has definitive answer as to whether or not PW can support images within table cells and table header cells.

**Comment by BSmolensky** [comment]
**Findings**: PW can, indeed, support images within both table cells and table header cells.

**Comment by BSmolensky** [comment]
**_NOTE_**: Requester was instructed to contact an accessibility specialist to determine if there are any accessibility issues with embedding pics in tables.

**Comment by BSmolensky** [comment]
All tasks complete. Ticket is ready to close.

**Comment by jknipes** [comment]
Work is complete, moving to _Done_
