### ISSUE TITLE
Evaluate ITF endpoint

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81358]
# Overview
In order to make a better informed decision on the ITF solution, we need to know more about the current LH Benefits Intake API.

some dashboards that might help:
https://vagov.ddog-gov.com/dashboard/ipg-v6d-c59/benefits-dbex-evss-to-lh-intent-to-file?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1713274764331&to_ts=1713879564331&live=true

https://vagov.ddog-gov.com/dashboard/9c7-45v-3fx/benefits-intent-to-file?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1713274779351&to_ts=1713879579351&live=true

# Tasks
- [x] - How long does an average ITF take?
- [x] -  How many errors are happening per ____ ?
- [x] - What type of errors are we getting?
- [x] - Which error cases should we consider edge cases?

**Comment by danlim715** [comment]
In the past 3 months, the average latency for the `type` (`get`) endpoint is as follows. The P95 average is 2.47 seconds and Pmax average is 11.78 secs, with the absolute worst response times peaking at 85.4 seconds. The `submit` (`post`) endpoint is pretty similar with an average P95 latency of 2.90 seconds, Pmax average of 10.6 seconds, and the worst response times peaking at 94 seconds. There are a handful of times where both endpoints experienced a huge amount of latency ranging from 22 seconds to an absolute peak of 94 seconds. The most recent of these huge latency spikes occurred on April 13, with `type` peaking at 51.81 seconds and `submit` peaking at 45.04 seconds.

In the past 3 months, the average number of hits to the API is 10,700~ hits per day, with about 8,295.54 being successful (200), 2,376 being 404s, and the rest (60ish hits) being misc error codes (401, 422, 500, 502, 503). These misc error codes seem to be the edge cases, as they're happening very infrequently compared to the 404s that are occurring.

**Comment by sanjabaj2** [comment]
This is just a clarifying note for anyone looking at this ticket later. 
https://dsva.slack.com/archives/C04KW0B46N5/p1709249886905999?thread_ts=1709244254.468629&channel=C04KW0B46N5&message_ts=1709249886.905999

Aurora Hampton
hi~ :)
if this is the Intent to File GET endpoint, then this is somewhat normal if the Veteran does not have an ITF on file.
vets-api returns a 404 to indicate that they need one created. (edited) 

So, 404s are not errors but a normal responses where there is no ITF on file.
