### ISSUE TITLE
Cost Reduction Strategy for Datadog Metrics in Vets API by filtering breakers endpoint Tags

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#81352]
## Description

We monitor Vets API downstream services utilizing breakers middleware via various custom metrics in Datadog, such as `vets_api.statsd.api_external_http_request_VAProfile_MilitaryPersonnel_success` However, we've encountered a significant cost issue due to the `endpoint` tag associated with these metrics. Specifically, there are over 25,000 unique values for the endpoint tag example (above), primarily because some VA Profile and other downstream service endpoints incorporate unique identifiers like ICN into the URI.
 
example:
```
endpoint:/profile-service/profile/v3/2.16.840.1.113883.3.42.10001.100001.12/1005079124_5eni_5e200dod_5eusdod,
endpoint:/profile-service/profile/v3/2.16.840.1.113883.3.42.10001.100001.12/1005110188_5eni_5e200dod_5eusdod,
endpoint:/profile-service/profile/v3/2.16.840.1.113883.3.42.10001.100001.12/1005114884_5eni_5e200dod_5eusdod,
etc
```

Given Datadog's pricing structure of $6 per 100 endpoints, the cost implication is substantial approximately $1,500 for 25,000 endpoints. This is because we incur charges for each unique combination of metric and tag values. 

Other endpoints exist with this same tagging structure. To address this, we've explored the ['Usage' feature under Metrics in Datadog](https://vagov.ddog-gov.com/metric/volume?sort=-volume_total). After discussions with Steve Albers, we've agreed on removing the endpoint tags from high cost metrics. We need to review and identify other endpoint tags that could be removed or modified to optimize costs. This initiative will be communicated with the OCTO team to ensure alignment and transparency in managing our Datadog expenses. 

When we encounter unlimited unique endpoints, they do not provide any useful or additional insights to us as developers. [These are the breakers boards](https://vagov.ddog-gov.com/dashboard/lists?q=breakers) that reference these metrics. If we decide to filter out the endpoints, we could instead display a chart for the entire service rather than breaking it down by individual endpoints. 

The primary purpose of displaying data by endpoint is to assist with debugging. This allows us to identify and communicate specific issues within a given endpoint directly to the developers on the downstream services. Without this level of detail, downstream services can become a bit of a black box and difficult to effectively communicate when problems arise. In the case of unlimited unique endpoints though, the endpoint granularity does not provide a level of data that's useful.

## Tasks
- [x] Review breakers endpoints with high amounts of tags
- [x] Review where/if the breakers endpoint tags are used in Dashboards or Monitors
- [x] Ping Steve Albers to remove tag you'd identified as high cost (if applicable)
- [x] Adjust necessary dashboards and monitors

## AC 
- [ ] Any high cost breakers metrics with endpoint tags are removed
- [ ] Breakers dashboards and alerts still display/function as before

**Comment by stevenjcumming** [comment]
@va-albers Endpoint tag values to remove:

```
/profile-service/profile/v3/...
/demographics/demographics/v1/...
/api/vetext/pub/mobile/push/preferences/client/...
/communication-hub/communication/v1/...
/vaos/v1/patients/xxx/appointments/...
```

It's likely that more can be removed, but considering there are 100k+ tag value. It would be difficult to identity others without initial pruning.

**Comment by stevenjcumming** [comment]
Related Boards:

Breakers External Services - Median Requests
VSP - External Services Dashboard

**Comment by stevenjcumming** [comment]
No adjustments to Dashboards are needed
