### ISSUE TITLE
[Spike] [CST] Investigate if there's any way to make faster API call on CST home page for "Last updated" date

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#81375]
## Value Statement
**_As a_** Veteran
**_I want to_** see the "Last updated" date on claim cards on the CST home page
**_So that_** I can more easily see the latest timestamp at a glance, without having to go into the claim to see that information.

---
## Background Context

Right now we don't make the API call required to show this date due to load times that it would add to the CST home page. Is there any way to solve this? This is user functionality that it would be great to provide.

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

Current design (shows "Last moved to" as a workaround)
<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGVHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a558db45759175df5daf66c57bfd4ee083e0f7f9/Screenshot%202024-04-23%20at%2010.35.53%E2%80%AFAM.png" alt="Screenshot 2024-04-23 at 10.35.53 AM.png" />

Current Status tab (shows "Last updated" which we want to also show on the claim card)
<img width="982" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7742524a9f03dc52ea10dc5b0279deae14a59fc/Screenshot%202024-04-23%20at%2010.42.57%E2%80%AFAM.png" alt="Screenshot 2024-04-23 at 10.42.57 AM.png" />

What we would like to show on claim card
<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1HQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67aae6c79c55c9c790571a48f106ebac043eb12f/Screenshot%202024-04-23%20at%2010.43.24%E2%80%AFAM.png" alt="Screenshot 2024-04-23 at 10.43.24 AM.png" />

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Is there any way to make this API call faster so CST home page load times don't have to suffer as a result of making it?

## Tasks
- [ ] _Discuss with engineering to document the current situation_
- [ ] _Assess who we might need to speak to in order to resolve this_
- [ ] _Document a request (if needed)_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_
