### ISSUE TITLE
Selected Tribal Land Does not populate the pdf

### ISSUE THREAD

**Issue by evansmith** [department-of-veterans-affairs/va.gov-team#81372]
## Issue Description
selecting the tribal land option in the new 530V2 form does not populate the pdf. This is because it adds in the form data into the `tribalLandLocation` object instead of the cemeteryLocation object.

---
## Tasks
- [ ] Make sure selecting tribal land populates both the checkbox and the additional information fields.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
