### ISSUE TITLE
[UX] 10-10EZR: Present Patrick the EZR V2 Flow option

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#81412]
As a team member, I would like to present the potential EZR v2 option to Patrick so that he has an understanding of how this could be implemented and potentially how long it will take.

---
## Tasks
- [x] Create a deck/graphic that describes both the EZR v2 potential flows and their advantages and challenges
- [x] Review with team
- [x] Modified the presentation based on feedback

## Acceptance Criteria
- [x] Success: We present the flow to Patrick and Lois
