### ISSUE TITLE
Create Documentation Around Sentry Escalation from Tier 1 to Tier 2 or Other Team

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#81411]
## Description 
This ticket will house the task of writing out documentation around Sentry monitoring. 

_Note: Platform Support Team is only responsible for being aware of high priority issues, not resolving them. This task goes to Tier 2, Clint Little, or a particular team dependent upon the situation. _ 

Process:

- [ ] Check once a week on Fridays
- [ ] Identify any alerts that have high velocity (for example, over 10k views in a short period of time)
- [ ] Create a ticket to alert either Tier 2 or applicable team (identify ways to identify who it belongs to)
- [ ] Add label "Platform-Support-Ticket"
- [ ] Assign ticket to that person or team 
- [ ] Notify Alyssa/Clint in a DM that there is an issue and the status
- [ ] Remove label "platform-tech-team-support"
- [ ] Suggest user/team who stores info in Sentry to move into DataDog

---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [ ]  Add steps above to the [Advanced Support Best Practices Doc Here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1)
- [ ]  Add responsibility to Tier 2 responsibility docs ([Frontend](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630975664/Front-end+Support+Responsibilities), [Backend](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084), [DevOps](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2425552908/DevOps+Support+Responsibilities))
- [ ]  Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
