### ISSUE TITLE
Discovery: Communication with NEO

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#81419]
## Issue Description
Following a post-mortem on the 2024-03-21 Latency Issue and numerous previous incidents, the Platform team has discovered that communication with the Network Edge Operations team which manages the TIC gateway could be improved. Communication back-and-forth in a more efficient manner would benefit both the NEO and Platform team during incidents and assist all in coming to a resolution sooner. Discovery of a possible POC or more agreed-upon process would be a major step towards closing this overall gap. 

## Tasks
- [ ] Current outline of communication process and timeline to reply discovered
- [ ] Reach out about any possible POC attempted

## Acceptance Criteria
- [ ] A clear path of communication between the NEO and Platform team is agreed upon if possible and communicated. 
---

## Additional Information
- Following multiple SNOW tickets with the NEO team, the Platform Support team has discovered the PoC name Ty Allinger, a NEO engineer who may be responsive within Microsoft Teams.
