### ISSUE TITLE
Toxic Exposure - Data Transformation #3 - Add Conditions

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#81426]
## Issue Description
The scope of this ticket is to transform the vets-website data structure into Lighthouse structure for the disabilities array

https://developer.va.gov/explore/api/benefits-claims/docs?version=current

Notes - https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/72816

Conditions from the FE are processed as such:
> for any new conditions that were selected on the toxic-exposure-conditions page, disabilities[n].isRelatedToToxicExposure flag is set to true 
> if disabilities[n].isRelatedToToxicExposure is set for any new conditions, toxicExposure object is included in submit
> if veteran selects a TE condition, but does not fill out any of the TE questions, make sure we send empty object and submit does not fail LH validation
> use the selected radio button's labels from the new-disabilities/add page to set on the disabilities[n].exposureOrEventOrInjury OR [n].secondaryDisabilities[m].exposureOrEventOrInjury
> -if "I'm not sure" is selected on any pages, do not include in submission

We need to convert the Form526Submission form_json to include `isRelatedToToxicExposure` with the Form526TransformToLighthouse service.

---
## Tasks
- [ ] add "isRelatedToToxicExposure" to LH transform service in disability conversion
- [ ] create mapping between "cause" field (NEW, SECONDARY, WORSENED, etc.) to radio button labels in the front end

## Acceptance Criteria
- [ ] generated Form 526 2022 PDF has column 2 filled out
- [ ] generated Form 526 2022 PDF has 15A checked

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
