### ISSUE TITLE
Design | Profile | Direct deposit VYE/Montgomery GI | Verify your enrollment integration

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#81434]
## Background

Another contracting team reached out to us last week (below), and we need to explore options that prevent 2 profiles from existing on VA.gov.  Ideally, this will be a short term situation, being resolved in December when BDN sunsets and educational chapters 30, and 1606 benefits use DGIB and VA Profile address information. just like our current direct deposit forms.

>we are creating an application that allows users who are enrolled in educational chapters 30, and 1606 to verify their monthly enrollment status online. This new tool is called Verify Your Enrollment (VYE). One of the special cases for this application is that we had to create our own direct deposit and address forms, which I understand goes against the current initiative of combining the education/compensation ACH/Address forms . The short reason why is that we connect to the database BDN that is unable to utilize the current VA profile address or direct deposit.
I am looking to gain some insight into the effort it would take to move these two forms that our team has created into the VA profile section. To see the current forms we have created you can go here in staging (https://staging.va.gov/education/verify-your-enrollment/) and click on the link "Manage your benefits profile". I am sure there are questions so please ask away.
*Just as a note, the intent is that these forms are only live until December. At that time we should be able to connect with DGIB instead of BDN. Once we do that we will delete our direct deposit/ address forms and use what is available in the VA profile since DGIB will be connected to those services.

## Tasks

- [x] Explore ways this could work. Initial thoughts are that we add back a second section to the DD page in VA.gov profile, that is hooked up to BDN, and use the sub-task flow for the address piece.  VYE tool would just link to our profile
- [x] Get approval from Mikki
- [x] Review w/ Profile team
- [ ]  Make recommendations to VYE team

## AC

- [x] We have a clear proposal on how we can streamline the number of places Veterans need to go to update their DD and address information

**Comment by andaleliz** [comment]
@mtcA6 ticket for next sprint, FYI

**Comment by andaleliz** [comment]
Update for the day:
- Jason confirmed paper checks are still a thing for MGIB. If we couple bank info w/ address info in the DD sectin of profile, that may be a confusing experience for some folks who get paper checks
- chatting w/ Mikki to get her thoughts on the matter and use those to inform the ideas I bring back to the team (hopefully by Monday at the latest)

**Comment by andaleliz** [comment]
Update for the day:
- Worked w/ Mikki this AM to align on recommendations
- Met w/ Profile team minus Pam and Adam to align
- Reached out to VYE team to request they schedule a meeting for us to all sync Monday or Tuesday next week.

[This is the approach](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=1152-3417&mode=design&t=rj4wuzrinyfs8enb-11) we're recommending;[ this is a plan B](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=1040-5971&mode=design&t=rj4wuzrinyfs8enb-11) if the first option is not technical feasible or desirable for some reason we don't know about yet.

**Comment by andaleliz** [comment]
Shared our recommendations with VYE team this afternoon; they're going to regroup + check in w/ Tom and Adam as needed.
