### ISSUE TITLE
Update Platform Content Team Submissions Section of Advanced Support Best Practices 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#81435]
## Description 

While combing through older "Saved for Later" threads in Slack, I noticed that Joe Knipes provided a loose outline for creating, editing, and submitting requests for content (see attached screenshot). We are going to create and update a page that outlines this process on the "[Advanced Support Best Practices (Tier 1) - Platform Content Submissions Section](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Platform-Content-Team-Submissions)" in Confluence. 

---

## Definition of Done
All tasks are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Work with Joe Knipes to determine how the content should be laid out on the [Advanced Support Best Practices page here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Platform-Content-Team-Submissions). 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
