### ISSUE TITLE
Design + FE | Profile | Maintenance | Document loading button states

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#81436]
## Background
 In response to, staging review feedback #81368 for our Ch33 work, we realized that the saving/loading state of `va-button` isn't a thing. We're going to submit an experimental design request, but first we need to document what we're doing and think about guidance.

## Task

- [x] Figure out if there are other patterns out there we need to consider being used on VA.gov
- [x] Evaluate what we're doing today and mock-up any recommended changes
- [x] Write out some use case docs about when to use which pattern (right now we have 2, this may not be needed if we only need 1)
- [x] Submit an experimental design request

## AC

- [x] Experimental design request has been submitted

**Comment by andaleliz** [comment]
@adamwhitlock1 I created this ticket, though not totally sure how much FE work there is on it now. One immediate question I have for you is if you know where we're using the button variation that has the loading indicator? I know the `processing update...` one exists in connected apps, so I can reference that.

If you have any thoughts/tasks/AC we should consider now, please feel free to add to the description! I'll def be leaning on you for input too.

FYI @mtcA6 I created this ticket and replied on the staging review ticket that triggered this. Hoping to close that one in favor of this one. I can work on this in the next sprint or the following. LMK if you have a preference.

**Comment by adamwhitlock1** [comment]
I will add some details and code references to this ticket. 
Thanks @andaleliz for getting this started.

**Comment by andaleliz** [comment]
@adamwhitlock1 this is the ticket where any screenshots would be helpful. No design files exist for these states for me to work from, unfortunately.

**Comment by mtcA6** [comment]
>re:  @mtcA6 I created this ticket and replied on the staging review ticket that triggered this. Hoping to close that one in favor of this one.

the guidance as i understand it is, staging review tickets shouldn't be closed until the issue is resolved, the issue in this case we're not using a design system component and have an imposter. So, in this case, unfortunately, I think we have to wait until the component is updated to use a design system component before we can close that other ticket.

**Comment by adamwhitlock1** [comment]
Okay so we have two versions of buttons that are currently used for indicating that an action is in process:

A gray disabled button with loading indicator that rotates slowly. (oof the contrast on the icon with the gray background is almost nonexistent 😬  )
![Screenshot 2024-04-25 at 12 18 06 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/58314c38-ba0a-4830-bc16-494402620663)

Code for the loading button is here: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/loading-button/LoadingButton.jsx

One thing that is important to note, that I just discovered, is that the existing loading button is using a non-design system icon aka a font-awesome icon, so it definitely needs to be updated sooner than later with an acceptable icon or text replacement.

Specifically just within the connected apps we show a text based loading button while an app is being removed:
![Screenshot 2024-04-23 at 11 23 26 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/c6ca6763-838c-46c2-b86e-9771ab82d721)

Code for this button is here: https://github.com/department-of-veterans-affairs/vets-website/blob/6643b0a509ddb13b7fe438e37e0b52dd94b45e2d/src/applications/personalization/profile/components/connected-apps/ConnectedAppDeleteModal.jsx

The connected app loading button is using the va-button web component, so it is in line with the design system recommendations, and doesn't _necessarily require_ any changes.


I guess my personal recommendation from an engineering perspective would be to use the text version that says something along the lines of the 'Processing change...' and using that in place of the icon. That would be the lowest lift and wouldn't require any additional work from the design system team until they provide a better solution / recommendation.

**Comment by mtcA6** [comment]
also just now seeing Shira's comment saying something similar, didn't see that till just now

**Comment by andaleliz** [comment]
@adamwhitlock1 thanks for the screenshots and your thoughts on this - I agree with you about the text based option for the reasons you shared, and for accessibility reasons.  

One idea just occurred to me - what if the button was just replaced with text instead of disabling the button and changing the label?   Does that change anything wrt to LOE on the FE? (How many acronyms can I use in a question?!)

There might be some a11y problems with that I'm not immediately thinking of with that approach, but I wonder if it might be clearer overall. Disabled buttons can be controversial in our world :) and I think it would reduce the visual design considerations needed to account for all the possible different background types (e.g. the gray on this yellow background isn't great but maybe it's fine w/ blue or white), and states for if a primary or secondary button is being disabled/processing.

**Comment by adamwhitlock1** [comment]
@andaleliz Glad you agree on the text based version being the best way forward in general.

I think it would be best to have the button in a true disabled state, because otherwise it could be clicked on and fire off another update, which we don't really want. When the button is disabled it doesn't emit events when clicked, so functionally that is what we want. 

I guess I could 'semi-disable' the button via code so it doesn't look disabled and basically ignore any potential clicks that do happen while the update is technically ongoing, but I'm not sure that would be a better solution than dealing with a truly disabled button for a11y. The LOE is relatively low, and I could whip up a MVP and evaluate pretty quickly for that.

I definitely hear you from the design aspect where the disabled gray doesn't provide much contrast or visual clarity in certain situations like the light yellow bg colors.

**Comment by andaleliz** [comment]
@adamwhitlock1 I noticed the `cancel` button disappears in both examples.  

Is that because the user _can't_ cancel it while the call is being made, and removing that button is better than disabling both? If not, can you share more about why that happens please? Thanks!

**Comment by andaleliz** [comment]
Created a [ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2792) which will be reviewed on 5/23.
