### ISSUE TITLE
Design | Service History API

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81430]
## Issue Description
_We need to determine the best approach for pull in a Veteran's Service History through the Service History API. [Here is an example](https://docs.google.com/document/d/19mWZbv8ygTcj7Rif0u5NDlfMDSJaG-G-5VCXzPeBwFM/edit?usp=sharing) of what is done on the Chapter 33 form._

Spike that determined what fields are available: #68092

---
## Tasks
- [ ] What is the approach for unauthenticated users? It looks like Chapter 33 requires those users to manually enter.
- [ ] What is the approach for authenticated users that have service history on their record?
- [ ] What is the approach for authenticated users that do not have service history on their record (Chapter 33 displayed an alert)?

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by fiorella-io** [comment]
Synced up with Julie P. and Laura. 

To do:
- [ ] - Create a feature brief under Burial (COE and 
- [ ] - Sync up with Micah and capture how Vet's API works
- [ ] - Connect with the profile / authenticated experience (#accountexp-authexp) to understand what information can be stored, and updated.

**Comment by fiorella-io** [comment]
The Profile team connects to a different API “Profile Service V3 API” and has the military history among other types of information from the Veteran. Based on [this Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1718118473113269?thread_ts=1699383805.245829&cid=C909ZG2BB), the information should be the same. 

Outstanding questions:
- How is it that we prefill some of the information in the profile and not the military history? 
- Are our forms not fully connecting to the “Profile Service V3 API.” 
- Does “Profile Service V3 API” does not have that information? and 
- If the Veteran provides that information (by filling out our form), where can we save it so they don't have to re-enter it on another form? It looks like APIs are read-only information, and there might not be APIs that provide add/update functionality 
- How can we verify the information that the Veteran has entered? After the benefit they apply is approved?

**Comment by fiorella-io** [comment]
Updates:
- COE: Since only the Veteran is accessing this form, we can prefill all military history once we link to the Profile V3 API
- Ch 36 PCPG: We will only prefill the military history if the Veteran is filling out the form. 
- Burial: Further discovery is needed, such as:
     - Understanding the processors' journey
     - Tracking relationship with the Veteran
     - Tracking pages with the most drop-off
     - Tracking how many submissions have uploaded a DD214
     - Tracking the military history step 

On 7/11, we decided first to conduct Burial's usability testing and understand the processors' journey and then decide on our next approach.

**Comment by fiorella-io** [comment]
Updates:
On 7/18, we decided to ask our COE and Ch 36 PCPG SMEs and build a case as to why we should only require the claimant's latest service period.

To do:
- [ ]  Schedule a short meeting with Ch 36 PCPG SMEs, including our OCTO folks
- [ ] Use the COE's sync meeting  in August to discuss

**Comment by fiorella-io** [comment]
On July 22, our Ch36 SMEs mentioned that it's OK to only ask about the latest/current service periods for military history. When we prefill military history to this form, it can follow the 1010ez form: When the claimant gets to the Military history page, show the Service Period page filled in. [Draft designs](https://www.figma.com/design/DEnVQXRrNvwJ3UkKkYYJ1Q/Ch-36-PCPG-2024-Updates?node-id=941-41311&t=HviTOerGWa6gVdg8-1).

![Image](https://github.com/user-attachments/assets/45b5712f-e1d3-45c4-a58a-f1d46d845e5f)

**Comment by fiorella-io** [comment]
Should this be moved to the new team?
