### ISSUE TITLE
DR | Update missing personal information error

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#81440]
## Value Statement

**_As a_** Veteran
**_I want to_** make sure the VA has my personal information
**_So that_** I can take advantage of the pre-fill on VA.gov to submit digital forms from my account

---

## Background Context

Currently, the Supplemental Claims form shows an error when the Veteran's required identifying information is incomplete. Incomplete means the account is missing the Veteran's first name, last name, SSN, and DOB.

Currently, the error only encompasses SSN and DOB. We want to include first and last name in the alert, as well as expand this to the other two decision review forms (NOD and HLR).

## Acceptance Criteria

- [ ] When a Veteran with an account that's missing identifying info such as first and last name, SSN, and DOB, the error is shown and the Veteran is prevented from started the form.

## Designs and Build Notes

- [FIGMA (for SC)](https://www.figma.com/file/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?type=design&node-id=0%3A619&mode=design&t=xICey6wqHyfFQg8A-1)

### Enablement team (if needed)
@jstrothman 

## Out of scope

- Other error messages

## Open questions

- Add here

## Tasks

- [ ] Confirm that logic for requiring first and last name are added to the error
- [ ] Update error messaging

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by saderagsdale** [comment]
@eileen-coforma Couple of design questions that'll help me understand the AC. 

> We want to include first and last name in the alert, as well as expand this to the other two decision review forms (NOD and HLR).

Is this saying the alert is missing from the other two forms, or just the first and last name in the alert?

> Currently, the Supplemental Claims form shows an error when the Veteran's required identifying information is incomplete. Incomplete means the account is missing the Veteran's first name, last name, SSN, and DOB.

Have we validated if it's possible to start any of the forms without a valid first and last name? If not, I think Robin could look at the logic on the FE.

**Comment by Mottie** [comment]
I [asked the identity team about this](https://dsva.slack.com/archives/CSFV4QTKN/p1716227359020019?thread_ts=1716227266.736879&cid=CSFV4QTKN), and it appears that having an LOA3 level doesn't mean the full name is populated:

> no, last name is always included but first name is not as there are individuals with a single name.

**Comment by Mottie** [comment]
After [raising this issue with Lighthouse](https://dsva.slack.com/archives/CKUCFQAHJ/p1716227820542319), we discovered that Lighthouse does require a file number/SSN, first name, last name & date of birth. The identity team informed us that the Veteran's first name is not available if they only have a single name. After some investigation, Lighthouse reported that our backend could pass an empty string as the first name.

So this ticket requires:
- Frontend work to prevent starting the form is the Veteran's last name is not saved in their profile
- Backend work to submit an empty string if the Veteran does not have a first name

**Comment by eileen-coforma** [comment]
Looking for Julie's approval/validation in[ this thread](https://dsva.slack.com/archives/C06V3RU6HA9/p1716496031016369?thread_ts=1716232842.881179&cid=C06V3RU6HA9)

**Comment by jstrothman** [comment]
@eileen-coforma Looks good to me!

**Comment by saderagsdale** [comment]
Note from Eileen: We can copy the pattern from SC. 

Robin will have PR open sometime today.

**Comment by Mottie** [comment]
Worked merged in, but not yet available in staging. It might be easiest to review these changes in a parking lot tomorrow or next Monday.

**Comment by shaunburdick** [comment]
Validated with @skylerschain in parking lot
