### ISSUE TITLE
[Engineer] Initiate Planning Session for Deployment of VISN-19 Systems, Facilities, Nodes, and Health Services [Engineer]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8144]
## User Story or Problem Statement
As a BA, I must have a full understanding of areas of research and data mining, so I can better understand the LOE and approach of using the data for automation and input.

## Goal
_Determine schedule, dependencies, and priority of Automation deployment _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Tasks
_Complete review of VISN-19, Systems and clinics and estimate ROM:_
- [ ] Rocky Mountain VISN Review 
- [ ] Deployment planning for automation 
- [ ] Association to Facilities
- [ ] Dependencies for automation, i.e. BA Health Services files.

## Acceptance Criteria
* Rocky Mountain VISN Review
* Deployment plan by priority - document
* List of Systems, facilities, and nodes to be created
* Dependencies and schedule to automate.
