### ISSUE TITLE
Service level coding

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#81459]
## Tasks

- [ ] Create service level function in existing file `vaos/v2/mobile_facility_service` to get referrals based on patient ICN. Should be named something like `get_referrals_by_patient_icn`, passing ICN along and retrieving whatever is in MFS (end data actually CDW)
- [ ] Create controller endpoint, POSSIBLY ( @simiadebowale ) in `vaos/v2/appointments_controller` (waiting for confirmation)
- [ ] Write rspec tests to cover new function

## AC

- [ ] Passing patient ICN to this endpoint should retrieve the correct referrals data expected
- [ ] Handling any errors
- [ ] Massaging data to fit any front end requirements
- [ ] Make sure new tests pass

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/81459?planning-poker) with Zenhub @lee-delarm6 @simiadebowale
