### ISSUE TITLE
[Design] Redo the Card component in the MHV UAE Library in Figma

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81462]
## User Story
In introducing virtual care modalities to pre-check-in and check-in, it introduced a need to ensure we were presenting information to Veterans consistently across PCI and Appointments. As a result, some information on our appointment detail pages changed, which means we need to redo the Card component in the MHV UAE Library in Figma. 
 
- [Appt detail page for CVT appt in eCheck-in](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-15824&mode=design&t=siM8lna9mIlVrU81-4)
- [Appt detail page for in-person appt in eCheck-in](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=2175-7536&mode=design&t=siM8lna9mIlVrU81-4)
- [In person in pre-check-in](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-17716&mode=design&t=siM8lna9mIlVrU81-4)
- [Phone in pre-check-in](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-20615&mode=design&t=siM8lna9mIlVrU81-4)
- [CVT in pre-check-in](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=2053-5236&mode=design&t=siM8lna9mIlVrU81-4)
- [VVC in pre-check-in](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-22891&mode=design&t=siM8lna9mIlVrU81-4)

## Tasks
- [ ] Redo the Card component in the MHV UAE Library in Figma

### Who needs to review? Remove rows that aren't needed for this work.   
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  

### Does Check-in PO need links or content for f/u tickets? If Yes, provide details in comments. 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
checking...

**Comment by benbrasso-agile6** [comment]
@zach-park was this also rdy for validation?

**Comment by zach-park** [comment]
@benbrasso-agile6 , not yet. I think Lori moved it to the following sprint...

**Comment by benbrasso-agile6** [comment]
How did you update the detail pages without first updating the component? Are they all just detached now?

**Comment by benbrasso-agile6** [comment]
Small updates. Validated.
