### ISSUE TITLE
June Medallia Feedback Report

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#81469]
### Issue Description

Monthly reporting on Medallia satisfaction data.
Monthly reports can be found in this folder

### Tasks

What work is necessary for this story to be completed?

- [ ]  Request monthly data for FSR
- [ ] Request monthly data for the debt portal
- [ ]  Review data reports
- [ ]  Extract meaningful data to include in a report
- [ ] Document on Github

### Acceptance Criteria

What will be created or happen as a result of this story?

- [ ]  Request data reports
- [ ]  Review data reports

**Comment by HeatherRienks** [comment]
Dupe- this was created in error, closing ticket.
