### ISSUE TITLE
[Design] My VA Component Audit: Update Figma files & documentation based on icon updates/assessment

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81466]
## Background
Follow-up from Matt's assessment in [79443](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79443). The latest update from design system regarding adoption of `va-icon`[here](https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359) :

> Micah Chiang
> :mega: Announcement: Upcoming Design System migrations :mega:
> - va-icon adoption: Font Awesome will be deprecated. We're working on guidance this sprint for how teams can migrate onto va-icon which will be shared out soon. We tentatively expect Font Awesome to be deprecated at the end of May, giving teams the whole month to adopt va-icon.
> - A new 640px breakpoint will be added to help [VA.gov](http://va.gov/) re-align with USWDS v3. This will eventually replace the current 768px breakpoint. We'll provide a more concrete timeline for this, though we tentatively expect to remove the 768px breakpoint in early August.

This ticket is to make the necessary documentation updates - in Figma and our FE documentation.

## Tasks
- [x] Update Figma files with new icons/fonts 
- [ ] Update FE documentation to remove references to Font Awesome and replace with appropriate font and icon style

## Acceptance Criteria
- [ ] Updates to Figma and documentation are complete

## Resources
- Design system announcement regarding upcoming changes ([slack thread](https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359)):

**Comment by mattmarino-adhoc** [comment]
It appears some icons in Figma have not been updated/replaced with VA-icon equivalents. I will follow up with the design system team on Monday.
