### ISSUE TITLE
[Design] My VA Component Audit: Update Figma files with new font sizes

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81465]
## Background
Follow-up from Matt's assessment in [79443](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79443). 

> Design system announcement:
> - As of May 8 we will be increasing the font size to 16.96. If you have a
> component that is not our web component, your component could break so
> move to use the DS web component.

This ticket is to make the necessary documentation updates - in Figma and our FE documentation - to handle to updates to font size.

## Tasks
- [x] Update Figma files with new font size
- [x] Remove erroneous symbols in local library and associated mockups
- [x] Update FE documentation as needed

## Acceptance Criteria
- [x] Updates to Figma and documentation are complete

## Resources
- Design system announcement regarding upcoming changes ([slack thread](https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359)):

**Comment by ACParker89** [comment]
@ajakabcin roll into 39

**Comment by mattmarino-adhoc** [comment]
Was not addressed this sprint

**Comment by ajakabcin** [comment]
@mattmarino-adhoc going to move this to sprint after this (sprint 42) bc you have a lot already to work through this sprint

**Comment by mattmarino-adhoc** [comment]
All the font updates are complete. Documentation is complete. Many symbol variances were cleaned up/removed, but more work will have to be done in the future.
