### ISSUE TITLE
Link to COVID-19 FAQ chatbot (Facility Locator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8147]
## Problem Statement
How might we inform Veterans visiting the Facility Locator about the option of using the COVID-19 FAQ chatbot before they call their facility directly?

## Goal
Veterans using the Facility Locator understand a COVID-19 FAQ chatbot is available

## Objectives or Key Results this is meant to further
- Objective 2: Deliver meaningful facility information 

## Current behavior

> Find one of VA's more than 2,000 health care, counseling, benefits, and cemeteries facilities, plus VA's nationwide network of community health care providers.
> 
> **Coronavirus update:** Many VA and community provider locations have changing hours and services due to COVID-19. For your safety, please call before visiting any location to ask about getting help by phone or video.
> 
> Need same-day care for a minor illness or injury? Select Urgent care under facility type, then select either VA or community providers as the service type.

---
## Tasks
- [ ] Insert the following text to the paragraph beginning **"Coronavirus update"** above the search box on Facility Locator main page

> For answers to questions about how COVID-19 may affect your VA health appointments, benefits, and services, use our [VA coronavirus chatbot](/coronavirus-chatbot). 

- [ ] Implement a link to [/coronavirus-chatbot] with the words "VA coronavirus chatbot" 
- [ ] Ensure users of assistive devices are made aware of link to VA coronavirus chatbot and can activate it with the keyboard. 

## Acceptance Criteria
- [ ] Veterans visiting the Facility Locator home page will see the following text displayed above the search boxes:

> Find one of VA's more than 2,000 health care, counseling, benefits, and cemeteries facilities, plus VA's nationwide network of community health care providers.
> 
> **Coronavirus update:** For answers to questions about how COVID-19 may affect your VA health appointments, benefits, and services, use our [VA coronavirus chatbot](/coronavirus-chatbot). Many VA and community provider locations have changing hours and services due to COVID-19. For your safety, please call before visiting any location to ask about getting help by phone or video.
> 
> Need same-day care for a minor illness or injury? Select Urgent care under facility type, then select either VA or community providers as the service type.
- [ ] The words "VA coronavirus chatbot" are displayed as a link.
- [ ] Users of assistive devices are made aware that "VA coronavirus chatbot" is an actionable link and can activate it by keyboard
- [ ] Veterans can visit /coronavirus-chatbot by clicking on link within paragraph.
- [ ] AXE scans are successful.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Analytics request in [#8148]

**Comment by mmiddaugh** [comment]
This work has been implemented by another team.
