### ISSUE TITLE
[FE] My VA Component Audit: Migrate to `va-icon` in code

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81474]
## Background
This ticket is the FE/implementation portion of #81466 which is handling the design and documentation side of migrating off of Font Awesome.

[Technical guidance from Matt D](https://dsva.slack.com/archives/C03R5SBELQM/p1713905374318579?thread_ts=1710776364.414359&cid=C03R5SBELQM):
> As discussed the goal is to switch from FontAwesome icons to USWDS icons. Using va-icon is one way to achieve that. Another is to use the SVGs directly, which we provided.

Further questions should be directed to `#platform-design-system` team slack.

## Tasks
- [x] Confer with Matt on appropriate icons to switch to (va-icon) (see his documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-design/va-icon%20library%20upgrade.md))
- [x] Implement new icons (will involve several file changes)
- [ ] Test
- [ ] Move to validation

## Acceptance Criteria
- [ ] Font Awesome is no longer being used on My VA/icons are updated correctly

## Validation
- [ ] Who will validate this work? Matt
- [ ] How can this be validated? Review implementation and confirm icons are correct 

## Resources
- Design system announcement regarding upcoming changes ([slack thread](https://dsva.slack.com/archives/C03R5SBELQM/p1710776364414359))
- [Guidance from Matt D](https://dsva.slack.com/archives/C03R5SBELQM/p1713907929400059?thread_ts=1710776364.414359&cid=C03R5SBELQM)

**Comment by sterkenburgsara** [comment]
Noting here for your team that we have filed the following tickets with VADS to make changes to the `va-icon` library: 
* Medications: remove the `medications` icon and import the `pill` icon from the Google material design library instead ([VADS ticket here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2811))
* Appointments: two icons are listed in the mapping for appointments. Appointments team has a preference for the `calendar_today` icon, so we will move forward with that on our team. Filed a ticket to remove the other icon `event_available` ([VADS ticket here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2816))

**Comment by allisonlu** [comment]
Since the DST has not implemented something similar to the function of [font awesome's stacking icons](https://docs.fontawesome.com/web/style/stack), i have not tried to build something new for the circular underlays for secondary link CTA icons (see screenshots in the [pull request description](https://github.com/department-of-veterans-affairs/vets-website/pull/30125))

**Comment by allisonlu** [comment]
@ajakabcin 

for sprint 38 planning, this can be updated to 1 point, if the above comment isn't an issue. 

if it is, i will connect with @mattmarino-adhoc when I get back to see how much work it will take to work with DST to implement that

**Comment by mattmarino-adhoc** [comment]
Secondary links conversation: https://dsva.slack.com/archives/C0NGDDXME/p1717521553002179

**Comment by ajakabcin** [comment]
As discussed in planning we're good to leave the icons without the circular underlays. Matt is going to follow up with design separately though to see if there's been any further thought or discussion around use of the underlays with `va-icon`.

**Comment by mattmarino-adhoc** [comment]
It looks like we are good to proceed without the underlays.

**Comment by ACParker89** [comment]
roll to 39 @ajakabcin (1pt)

**Comment by allisonlu** [comment]
- @mattmarino-adhoc confirmed icons without blue backing is fine
- going to hold off on merging the PR until we get more guidance on recommended size of icons 
- at this time, we're **not** going to submit the dot indicator to DST as a `va-icon`

**Comment by allisonlu** [comment]
@ajakabcin @mattmarino-adhoc 

ready for validation! it's on staging, but i'm having connection issues with prod rn

**Comment by mattmarino-adhoc** [comment]
@allisonlu I can take a look on Friday if you're around - will you be here?

**Comment by allisonlu** [comment]
i was able to check my account on va.gov and it doesn't seem like the updates are live on prod yet. i wanted to check again on staging, but staging is currently down :(

![www va gov_my-va_](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/61cad11f-289b-4bf0-a983-1928d3c9f8c7)

**Comment by allisonlu** [comment]
can confirm the icon updates are on prod now!

![www va gov_my-va__postLogin=true](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/237bf050-1b1c-4abf-8019-ef5406b52dbd)

**Comment by ajakabcin** [comment]
Confirmed on staging and prod
