### ISSUE TITLE
Content style guide: Add page on destigmatizing language around substance use

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#81489]
## Story

As a VA content creator, policy maker, provider, or other personnel, I need to know how to write and speak about substance use in a way that does not create stigma for the Veterans I serve.

### Additional background

We are working with the VA Office of Mental Health and Suicide Prevention and a cross-government group to provide the guidance needed to destigmatize language across VA content.

## Tasks

- [x] Meet with Office of Mental Health and Suicide Prevention to advise on strategy (Danielle)
- [x] Create list of terms to use and avoid and review with cross-gov SMEs (Office of Mental Health and Suicide Prevention)
- [x] Review list of terms to use and avoid and provide content recommendations (Danielle)
- [x] Create SharePoint doc approach to style guide section (Danielle)
- [ ] Build out style guide section as a subpage to the health content section (Megan)
- [ ] Get final VA clearance on terms to use and avoid (Office Mental Health and Suicide Prevention)
- [ ] Make any final edits to section (Megan, Danielle)
- [ ] Review PR and publish (Megan, Laura, Danielle)

**Comment by DanielleThierryUSDSVA** [comment]
@megzehn @laurwill This is the page I mentioned that is going to be a subpage of the health content section. Here's the [Word doc(https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EYJEtplFx7pJnJ9Hi-ZlRO4BGBs9xH3xHA1opTXBlkzcqA?e=U5GrsW). We can start building this out and just wait for final clearance. There is some time pressure around this one, so we'll want to keep it moving. Thanks!

@strelichl

**Comment by megzehn** [comment]
Update: @DanielleThierryUSDSVA confirmed that we have clearance on this page with a minor edit. I updated [the PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2769) and let @humancompanion-usds know that it's ready to go live after he reviews the page formatting.

**Comment by megzehn** [comment]
The page is live!

**Comment by megzehn** [comment]
Added ticket to capacity tracker; closing.
