### ISSUE TITLE
Recruit Usability Testing Moderator

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#81487]
## Description
Identify and confirm a moderator for the upcoming Milestone 2 Usability Testing Sessions of the Preview Environment.

---

### Tasks
- [x] Identify potential moderators with appropriate experience
- [x] Confirm availability and willingness to participate

### Acceptance Criteria
- [ ] A moderator for the Usability Testing Sessions has been identified and confirmed

**Comment by JoeTice** [comment]
We'll be conducting an initial walkthrough on 5/7/24

**Comment by JoeTice** [comment]
We'll be conducting an initial walkthrough on 5/7/24
