### ISSUE TITLE
Migrate PCIU data 

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#81493]
### Summary

VAProfile should completely replace PCIU. These [User Contact logs](https://vagov.ddog-gov.com/logs?query=%22User%20Vet360%20Contact%20Info%22%20env%3Aeks-prod%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1713318517000&to_ts=1713923317000&live=true) reveal that there is data that needs to be merged.

### Tasks

- [ ] Create a task to migrate PCIU data to VAProfile
- [ ] Monitor logs to ensure the data was successful
- [ ] Alert teams that PCIU data has been merged with VAProfile

### Definition of done
- [ ] PCIU data has migrated over
- [ ] [User Contact logs](https://vagov.ddog-gov.com/logs?query=%22User%20Vet360%20Contact%20Info%22%20env%3Aeks-prod%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1713318517000&to_ts=1713923317000&live=true) do not have false data entries.
