### ISSUE TITLE
Support: Post Keep It Up To Date Notice in Slack - Monthly Recurring

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#81495]
## Issue Description
Teams using Confluence need to know about the oldest pages in their respective spaces on Platform Website, those in most need of an update. 
[Keep It Up To Date](https://vfs.atlassian.net/wiki/marketplace/discover/app/keep-it-up-to-date?requestDialogOpen=true&source=mpac) application has been identified as a simple tool, free of charge, for this purpose. 
Platform Content Team needs to alert teams to these pages on a regular cadence via the Platform Content Channel in Slack.

---
## Tasks
- [x] Schedule post for first Tuesday of every month on #Platform-Content channel in Slack

## Acceptance Criteria
- [x] A notice to check the Keep It Up To Date page in Confluence will be posted in PCT channel in Slack on the first Tuesday of every month.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
Post is scheduled. Once it actually does post, this ticket will be ready to close.

**Comment by BSmolensky** [comment]
Reminder posted. Moving to Done.
