### ISSUE TITLE
Create and deploy temporary front end for Preview Environments

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#81496]
## Issue Description
Preview Environments are ready for usability testing and need a basic front end form that can be used for the testing. Styling and format are not specified as this front end is intended to be temporary and will be replaced later. The front end form should be able to do the following:

- Find an Environment by tags
- Create a new environment
- List all environments
- Find an environment by name
- Delete an environment

---
## Tasks
- [x] Create a basic front end experience that will allow a user to interact with preview environments.
- [x] Add components for Find an Environment by tags
- [x] Add components for create a new environment
- [x] Add components for find an environment by name
- [x] Add components for delete an enviroment

## Acceptance Criteria
- [x] A front end for performing various functions has a component framework laid out and is ready to be connected to the API.

**Comment by CBonade** [comment]
Most features integrated without real functionality tied to them due to missing API pieces. Awaiting progress from back end/devops, will likely miss sprint deadline as a result. Shouldn't be a problem to finish next sprint.
