### ISSUE TITLE
Resolve flipper gem breaking change

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#81501]
## Issue Description
There was a breaking change in a flipper gem update. This ticket is to make the necessary changes to our flipper code and test the fix. See comments in https://github.com/department-of-veterans-affairs/vets-api/pull/16396

## Tasks
- [x] Fix the code in `lib/flipper/views/layout.erb`. Look [here](https://github.com/flippercloud/flipper/pull/853/files#diff-283cc728fe0d3d9dd980e7955440bfb4aa2a1aa490abe7bd41d37e107c3ad140) to see how it can be changed. 
- [x] Get tests in `spec/requests/flipper_request_spec.rb` to pass.
- [x] Test changes in UI locally
- [x] Get PR reviewed and merged
- [x] Once deployed, validate changes in  flipper UI.

## Success Metrics
The flipper gem is updated. 

## Acceptance Criteria
- [x] The gem is updated
- [x] Flipper works as it should
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
1. Navigate to flipper in all of the environments: [dev](https://dev-api.va.gov/flipper/features), [staging](https://staging-api.va.gov/flipper/features), [sandbox](https://sandbox-api.va.gov/flipper/features), and [prod](https://api.va.gov/flipper/features) and ensure the navigation part of the page works (the Features and Docs links).

**Comment by rmtolmach** [comment]
@bkeepers, that's quite alright! 😄 
You can take a look at our customization in [this directory](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/flipper) and also view our UI at https://dev-api.va.gov/flipper/features.

**Comment by rmtolmach** [comment]
I have a new branch where I updated the flipper gem. Tests were failing, as expected, but then when I replaced the breadcrumb section in layout.erb, the page loads and the tests pass 🎉 
Now I am re-working the UI to make it look good again. **Previous view**, thanks to breadcrumbs:
<img width="372" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/cbb57a2b-8264-4748-9fc6-22cfc7ec6661">

**New view:**
<img width="151" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/9681ee86-55b4-4265-94ce-aaa56e419b6d">

Those docs link to the official flipper docs, which we don't want. We _could_ link to our [internal docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) if we think that would be helpful.

**Comment by rmtolmach** [comment]
- PR: https://github.com/department-of-veterans-affairs/vets-api/pull/17159

**Comment by rmtolmach** [comment]
Follow-up PR to fix something found during validation: https://github.com/department-of-veterans-affairs/vets-api/pull/17166

**Comment by rmtolmach** [comment]
Follow-up PR merged and it looks good 🎉  https://dev-api.va.gov/flipper/features
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/8a0df63c-cfab-48a5-acd2-9fa13c60fc56)
