### ISSUE TITLE
Different unit test coverage standards on different pages

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#81508]
### Description

We have different coverage standards of 75% and 80% on different pages on the website. The numbers should be made consistent. :-) 

I believe the higher number should be chosen, but it's probably best to check with the collab cycle team to be sure, since they enforce code coverage standards during staging review.

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/unit-tests
- https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO engineering

-------

_Ticket updated for Governance team action_

Assignee: @erinrwhite 
Peer Reviewer: @it-harrison 

## Description
See details above. Unit test coverage not consistently communicated at 80% across Platform Website.

## Tasks
- [ ] Fix [Frontend testing/unit tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/unit-tests) page to state that 80% is the coverage requirements

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Platform Website consistently communicated that the unit test coverage requirement is 80%

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by jknipes** [comment]
@shiragoodman would you be able to confirm the correct unit test coverage standards, and Content Team will update these pages?

**Comment by erinrwhite** [comment]
@it-harrison 

Can you check behind me? There are actually two pages where this needed to be updated (I think!)

[Unit tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/unit-tests) - first paragraph under first heading

[Frontend testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-testing) - third bullet under "unit tests" heading

**Comment by it-harrison** [comment]
@erinrwhite -- looks good! sorry for delay in review!

**Comment by erinrwhite** [comment]
thank you @it-harrison! Closing
