### ISSUE TITLE
Draft Plan for Improved DORA metric tracking

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#81502]
## Description
Develop an initial plan for enhancing DORA metric tracking across the platform. This plan should detail proposed methods, tools, and processes to effectively measure and analyze DORA metrics, aligning with strategic objectives to improve operational practices.

---

### Tasks
- [x] Draft an initial plan outlining the scope, objectives, and methods for improved DORA metric tracking
- [x] Present the draft plan in Confluence to platform stakeholders for review and feedback

### Acceptance Criteria
- [x] Initial plan has been drafted and is available for review
- [x] Plan has been shared w/ stakeholders for review

**Comment by ben-allen-oddball** [comment]
https://docs.google.com/document/d/1l7wMj0K8_m0Pu7ABZ6YZ-7HJnEXl7CCA5opLn1xNTO4/edit

**Comment by ben-allen-oddball** [comment]
Suggestions:



1. DORA metrics require a significant amount of data to be gathered, stored, index and analyzed.  Gathering the data each run can take hours if not maintained in a persistent store.  We are also not good citizens of the GitHub API and other sources of data because daily we pull years of data.
    1. I suggest we deploy an AWS RDS Postgres instance to store this data and only collect the delta daily.  This would speed up the processing time from hours daily to only a minute or so.
    2. I have identified a few tools which are very lightweight and free.  There would be a possibility to even make this process realtime where webhooks from GitHub actions, pager duty, Argo CD would be feed the data when an applicable event has occurred.
2. I believe we are quite weak in our incident tracking which determines MTTR and Failure rate.  Right now we are only identifying out of band deploys and making a presumption that the out of band deployment was because of a failure.  When frequently these are not.  We also frequently live with some failed deployments until the next deployment window, in which case we have no data.
    3. I suggest we gather data from smoke testing, manual incident creation, pager duty, etc.
    4. Ideally we would use a single record for incident recording.  I suggest we use GitHub issues to record issues against the product and scrape the data.  The DORA metrics are fairly simple in this regard.  The basic requirements for Failure calculation and MTTR is failure start time and failure resolved time.  It would be better if we could also identify a commit or release where this was introduced to production.
        1. If we leveraged Github Issues our existing tooling could automatically open issues.  PagerDuty, DataDog, Smoke Testing could open issues against a product.
        2. Support teams, product owners and the support bot could also open incidents against products.
3. Vets-API metrics are not accurate because the deployment is on a schedule in Argo CD.  The data is not easily queryable and lacks extensive historical data.
    5. One suggestion is to disable the schedule and have a github action trigger the Argo Sync job.  This would not change the deployment at all but would allow the data to be collected in an identical manor to other GHA deployments.
        3. Reference implementation: [https://github.com/marketplace/actions/argocd-sync-action](https://github.com/marketplace/actions/argocd-sync-action)
    6. An alternative solution would be to enable the sync hooks within ArgoCD.  These could trigger github actions or feed directly into the database if we implemented a persistent data store.
        4. [https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/)

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3140321285/Dora+Metrics+-+Next+Steps
