### ISSUE TITLE
Refine Presentation of DORA Metrics

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#81500]
## Description
In order to improve the output for readability/understandability by non-technical OCTO stakeholders, we would like to streamline the presentation of the data.

**NOTE - DUE 4/25**

---

### Tasks
- [ ] Review DORA metric outputs in Confluence w/ Joe, Clint, Eric
- [ ] Identify improvements
- [ ] Implement those improvements

### Acceptance Criteria
- [ ] Suggested presentation improvements have been identified and implemented

**Comment by JoeTice** [comment]
This ticket was no longer valid as it was unecessary
