### ISSUE TITLE
Incorporate technical ideas and knowledge into future-state of failure paths in the submission experience

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#81523]
## Description
This ticket will build off Nathan's technical discovery in order to plan for solutions for submit work.

As a result of this work, we will be ready to do (or refine) a high-level journey mapping of failure paths before moving onto more detailed design per [Map future-state solution for failure paths in the submission experience #81418](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/81418)
 
## Tasks
- [x] Work with Nathan and OCTO to refine possible scenarios (invite Nichole & Julie as optional)
- [x] Identify dependencies that could slow or impact work (For example, the timeline for the new "pending" tag in MyVA from VFF)
- [] Identify 2-3 options for long-term solution, informed by technical perspective

## Acceptance criteria
- [x] Options for long-term solution documented and understood by team

**Comment by mengA6** [comment]
We scheduled time with Nathan for this: "Mapping out future submission experience" on Monday, 5/6/24

**Comment by evelynhilbrichdavis** [comment]
Moved AC for #79178 to sync with an engineer to this ticket so we don't need to add more resources to it.

**Comment by evelynhilbrichdavis** [comment]
Solutioning that OCTO + engineering said was feasible:
1. Usable tracking numbers for all submissions
2. Send Veterans a digital copy of the file that needs to be resubmitted (with possible longer term goal of a generated pdf)
3. Re quick-submit: Simple forms team is working on an accessible upload option we could use to replace mail
3. Be clear about the cause for the failure. Front-end validation normally covers everything, so it’s typically downstream problems. 
4. Any status update we want to give-- we will have pizza tracker variety
5. Failsafe needs to be less manual in the long term

Ideas to stay away from:
1. Add status touch points that alert Veterans when the new files have been added to the eFolder post-failure

Things to add:
1. Resubmission: Consider duplicates and the Veteran experience with trying to resubmit In Progress Forms 
2. Lock the IPF once it is submitted so it can't be jammed

**Comment by evelynhilbrichdavis** [comment]
To unblock us, OCTO created tickets to 
1. Understand technical side of resubmission and duplication (What do Veterans see in terms of an IPF? Can they return to a form if the submission failed? When can they resubmit?)
2. Understand what creates the error on the failure state in the UI

**Comment by evelynhilbrichdavis** [comment]
As for validating our happy path:  Emily confirmed that we could notify Veterans of their status at any step in the process. Since the high level design passes feasibility since it is comprised of additional and modified communications.
