### ISSUE TITLE
[FE, PM] My VA: Custom reports documentation for GA4 migration

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81529]
## Background
With the migration to GA4 for analytics, the platform analytics team has requested we document our custom reports in a spreadsheet. This is similar to what we were asked to do with our custom events in #77399 

_The deadline on this is **April 26**._

Announcement from Analytics team posted in Resources section.

## Tasks
- [x] Follow instructions in [this GH issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-UA-Reports.md&title=Reports+Powered+by+UA%3A+%5BTeam+Name%5D).
- [x] Complete & submit the form
- [ ] Consult with PM, devs and PO to make sure all reports are captured
- [x] Attend analytics office hours for assistance as needed

## Acceptance Criteria
- [x] GH issue is submitted to Analytics team

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ review form

## Resources
- [example completed issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80397)
- [Slack announcement for context](https://dsva.slack.com/archives/C1Q4294JJ/p1712688413304769) from Johnny Jesensky

> Attention: VFS PMs & Delivery Leads 

> As part of the Google Analytics transition to GA4, we ask that all VFS Teams create and share an inventory of their actively used reports that use Universal Analytics (UA) data. These reports may include a dashboard in GA or Domo, a Looker report, a direct link into a filtered UA interface report, or some other way tool.

> Note: This is a separate ask and form from the [custom event audit](https://dsva.slack.com/archives/C1Q4294JJ/p1711559198840669) -- though should be much simpler.

> What do I need to do? Follow the instructions on [this Github form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-UA-Reports.md&title=Reports+Powered+by+UA%3A+%5BTeam+Name%5D), and include the name, URL link, platform, and brief description of any actively used reports that use Google Analytics UA data. We are defining "actively used reports" as reports that are actively collecting data, and are consistently accessed daily, weekly, or monthly over the last 6 months.

> When is this due? We'd like for teams to submit this form no later than Friday, April 26.

> This information is needed for us to identify the best ways to assist teams with transitioning their GA reporting.

> Questions? Please post any questions to the [#vfs-analytics](https://dsva.slack.com/archives/C1Q4294JJ) Slack channel. Additionally, feel free to join our team’s Office Hours, (every Tue & Thu @ 3:30pm ET), to discuss this in more detail. Thank you!e to join our team's Office Hours to discuss this in more detail. Thank you!

**Comment by DanielMiller-agile6** [comment]
submitted form with 2 MyVA specific reports, but didn't find much else that we need to call out.  Let me know if anything looks like it might be missing:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/81703

**Comment by DanielMiller-agile6** [comment]
for fun, i also grabbed an export of the "My VA 2.0" report from Jan. 1, 2019 till today... neat to see how many vets have relied on MyVA over that time :)

[Analytics All VA.gov Website Data [Production] My VA 2.0 20190101-20240424.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1dXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--814a3c7ae9f5aa79f0fc35e380a6a3bfc7b664ae/Analytics%20All%20VA.gov%20Website%20Data%20%5BProduction%5D%20My%20VA%202.0%2020190101-20240424.pdf)
