### ISSUE TITLE
Copy of Service level coding

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81528]
## Tasks

- [ ] Explore using CDW to access Consult Factors db table to find approved referrals. If found, identify what fields and values are available in the approved referrals. Related [Slack thread](https://dsva.slack.com/archives/C06SQ48B205/p1713387030197699). 

## AC

- [ ] Access to CDW and db table where CC approved referrals are
- [ ] Identify what fields and values are available in the approved referrals
