### ISSUE TITLE
Spec out work with MFS team to create endpoint to connect to CDW

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81527]
## Tasks

- [ ] Spec out work with MFS team to create endpoint to connect to CDW
- [ ] Patient endpoint to get referral data should take an ICN
- [ ] Have MFS team create referral endpoint to grab necessary data from CDW including (roughly)

- Veteran name or unique id
- Referral number
- Start date
- Expiration date
- Referring VA facility
- Referring VA facility phone (although, we can probably get that from somewhere else if needed)
- Speciality/type of care of referral
- Veteran's preferred facility (if available, or maybe this is stored elsewhere)
- Veteran's preferred facility location (if available, or maybe this is stored elsewhere)
- Veteran's preferred provider (if available, or maybe this is stored elsewhere)

## AC

- [ ] MFS team has an endpoint we can access to pull said data for a patient based on their ICN
