### ISSUE TITLE
[FE] My VA Bene App Drafts: Configure VA Form 21P-530

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81525]
## Background
Similar to what was reported to us in #78504 , Fiorella let us know that another form is not appearing properly in My VA's Benefit Application Drafts section. We need to investigate why it's not appearing there, check the configuration, and make necessary updates so that the form will appear there.

**Note**: I confirmed the form **is** listed in the `VA_FORM_IDS` object in [/platform/forms/constants file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L3)

## Tasks
- [ ] Investigate why the form is not showing up on My VA
- [ ] Implement fix/update configuration so form does appear as a draft 
- [ ] Add form 28-8832 and form 26-1880 to TRACKING_PREFIXES object 
- [ ] Coordinate with Fiorella Geedi and Laura Steele to test/validate once done

## Acceptance Criteria
- [ ] Form 21P-530 is configured properly to appear as a draft on My VA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Fiorella/PM
- _How can this work be validated?_ Create a draft of form 21P-530 and confirm it appears on My VA

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1713196571545659?thread_ts=1710441317.658929&cid=C909ZG2BB)
- Previous ticket: #78504

**Comment by allisonlu** [comment]
bumping up to 3 points because form 21P-530 is listed in both the `VA_FORM_IDS` and `SIP_ENABLED_FORMS` objects, and i can't reproduce the issue on my local (i.e. i _am_ able to see this form in the BAD section), so i need to do more prying
