### ISSUE TITLE
ITF -- Implement ITF on vets-website

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#81534]
# Overview
Make the changes to the vets-website to call the API on the start of the form and again before submission.

## Task
- [ ] - Make a synchronous call to the ITF endpoint upon  start of the form
- [ ] - If an ITF is received, save it to either in_progress or intent_to_files in the database (I'll leave this to your judgement)
- [ ] - If no ITF is received, try again to make a synchronous call before submitting the form.

### ITF API is working

1. As a veteran when I start the 527 form for the first time, I want to have that date recorded as my ITF date and shown the expiration date (1 year from date).
2. As a veteran when I start the 527 form and already have an existing ITF date, I want to be alerted that I already have an ITF and be shown the expiration date.
3. As a veteran when I start the 527 form and have an expired ITF date (over 1 year old), I want to be alerted that I had an expired ITF, that my ITF has been updated and shown the new expiration date (1 year from date)

### ITF API is NOT working at form start

1. As a veteran when I start the 527 form and the ITF API is not available, I want to be alerted that the service is down but we will continue to try.
2. As a veteran who did not get an ITF date established upon the start of the form due to the API service being down, I want to have that my in-progress date recorded as my ITF date.

### ITF API is NOT working at form start nor at submission

1. As a veteran who did not get an ITF date established upon the start of the form due to the API service being down and the API service is still down during submission, I want to have my in-progress date recorded as my ITF date on the generated PDF.

**Comment by mjknight50** [comment]
Closing in favor of other tickets
