### ISSUE TITLE
Remove outdated EBS snapshots

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#8153]
## User Story or Problem Statement
As a cost-efficient engineer, I need outdated EBS snapshots terminated so I can sleep at night.

## Goal
Reduce the number of EBS snapshots to the minimum we actually need.

## Objectives or Key Results this is meant to further
- Reduce EBS snapshots to just the last 30 days unless a snapshot is deemed absolutely necessary.
---
## Tasks
- [ ] Remove outdated EBS snapshots from 2016-2019 and ones from 2020 that are older than 30 days and no longer needed.

## Acceptance Criteria
- [ ] All existing EBS snapshots no more than 30 days of age unless absolutely necessary.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jsev-io** [comment]
Found 1502 Snapshots Older than 3-27-2020
![image](https://user-images.githubusercontent.com/63133731/80383193-45aeff80-8871-11ea-9688-7009c24fa7c0.png)

**Comment by jbritt1** [comment]
😢

**Comment by wyattwalter** [comment]
So a lot of those are old AMI's that were untagged when the project first started. There's some existing tooling here, but a lot of it focuses only on things that are within our control. We also share an account with Caseflow, so we'll have to sort out their things. Regarding old AMI's, we have:

- [cleanup-deregistered-ami-snapshots](https://github.com/department-of-veterans-affairs/devops/blob/master/utilities/remove_old_snapshots/cleanup-deregistered-ami-snapshots.py) looks for EBS snapshots that were created by the AMI creation tool where the AMI has been deregistered. This is run regularly by Jenkins and seems to be clean right now with nothing it wants to delete.
- [remove_old_amis](https://github.com/department-of-veterans-affairs/devops/blob/master/utilities/remove_old_amis/cleanup.py) deletes AMI's older than X when we create new ones for an "app". This one is targeted and won't go cleaning up AMIs for anything besides that app. It's called at the end of a AMI creation automatically.

Those two tools have a gap where they're not covering things that were created early on outside of the existing tooling and we might have to manually go through them a bit to find patterns and get them cleaned up. Fortunately, they're not being automatically created, so it should be a limited set. If we can go after the AMI list, then we can use the first tool listed above to cleanup their snapshots.

There's also snapshots created by the deployment pipeline which are supposed to be getting cleaned up. I don't see any leaking there offhand, but we'll have to see what it looks like if we can get rid of the noise from the AMIs.

For the Appeals stuff, we will have to work with them to get them deleted as they don't belong to our project, but we can make recommendations there.
