### ISSUE TITLE
Toxic Exposure - Add custom BE validation for Add Conditions (stretch)

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#81542]
## Issue Description
This story is a subset of a larger story, [79938](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79938) Toxic Exposure - Schema for all TE fields to Form526 vets JSON schema, currently targeted for the Iteration #4. Because the Add Conditions JSON from the FE (`toxicExposureConditions`, see [contact](https://github.com/department-of-veterans-affairs/va.gov-team/blob/7dc5fc5151efece0b2eb3f2fce7bf80290f41960/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md)) generates dynamic properties, it was found on an earlier ticket that our currently implementation of JSON Schema on the BE can not handle it. Therefore, some sort of custom validation (at the submit_all_claim level) should be in place to cover that gap.

---
## Tasks
- [ ] Add custom validation of the `toxicExposureConditions` FE node

## Acceptance Criteria
- [ ] The `toxicExposureConditions` FE node is validated before the claim is saved, returning an error to the caller if it fails
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
This is a nice to have  - moving to Post MVP epic
