### ISSUE TITLE
[CST] Update document uploads to not accept files where extension does not match content

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#81549]
### Background
When uploading files to EVSS, the files extension must match the expected extension based on it's contents. If it does not match, EVSS will throw an error, causing the upload to fail silently. We need to implement a check in vets-api to ensure that the mimetype of the file and the extension match one another

### Value proposition
When this scenario happens, a silent failure occurs as the user is shown a notification indicating that their upload was successful, even though it won't be. We don't have a check in place to prevent this and EVSS will always reject these files

### Engineering notes
- This file reproduces the issue: [html.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/15097728/html.txt)
- This check needs to happen before we kick off the sidekiq job so that we can ensure that the user sees an error message explaining what went wrong

### Tasks
- [x] Create a check in vets-api to ensure that the mimetype of the file and the extension match
- [x] Write specs to test that this functionality works

### Acceptance Criteria
- [x] When a file whose contents do not match the extension is uploaded to vets-api, an error is returned that the user can see

**Comment by jerekshoe** [comment]
The PR for this just got merged 30 minutes ago or so, I will check on Monday or Tuesday to see that it is working as expecte d in Staging
