### ISSUE TITLE
BE | Auth Exp | Endpoint Documentation

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#81540]
## Background
Create a document that outlines all of the My VA and Profile endpoints.

## Tasks
- [x] Document all My VA endpoints
- [x] Document all Profile endpoints

## Acceptance Criteria
- [ ] Document complete and added to sensitive repo.

**Comment by DanielMiller-agile6** [comment]
i added a page for our team's github documentation, but we can improve, reorganize, or better combine with a broader "auth exp" doc page(s) later. questions and feedback welcome :)

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/vets-api-endpoint-dependencies.md

**Comment by ajakabcin** [comment]
this is complete from the My VA side - handing off over to Profile cc @mtcA6
