### ISSUE TITLE
BE | Auth Exp | Setup New Mock Repo

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#81550]
## Tasks
- [ ] Create new mock repo prototype.
- [ ] Create a mock endpoint.
- [ ] Setup local environment on our local machines.

## Acceptance Criteria
- [ ] Test the mock endpoint locally.
