### ISSUE TITLE
Add unit tests for actions/index.js so that we have proper test coverage

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#81568]
## Background Context
Currently `src/applications/claims-status/actions/index.js` is not fully tested and shows test coverage as this
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58acb918793ddac4a5f39b59e64a76591086c5ad/Screenshot%202024-04-24%20at%2011.32.17%E2%80%AFAM.png" alt="Screenshot 2024-04-24 at 11.32.17 AM.png" />

when running the command `yarn test:coverage-app claims-status` 

We need to increase test coverage here by writing tests for submitFiles() and submitFilesLighthouse()

## Outcome, Success Measure, KPI(S), and Tracking Link
- Test coverage is at 80% of above for the four areas

## Engineering 
- Add here

## Tasks
- [ ] Add tests for submitFiles()
- [ ] Add tests for submitFilesLighthouse()

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] `src/applications/claims-status/actions/index.js` has test coverage above 80% for the four test areas
- [ ] submitFiles() is tested
- [ ] submitFilesLighthouse() is tested

**Comment by jacobworrell** [comment]
@jerekshoe @samcoforma is this work that needs to be done still or can I close this ticket?
