### ISSUE TITLE
First Click Test on location of FDG

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81577]
## Purpose
Naomi recommended that we do a short research lap using a [First Click Test](https://www.optimalworkshop.com/learn/first-click-testing-101-an-intro-to-first-click-testing/) to determine where users might gravitate toward on the main Platform Docs page if asked to look for a Forms Digitization guide.

This is supposed to be a capability of Optimal Workshop.

We'd set up a version of the main page and then see where people go.

Documenting process and findings [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3122266145/First-click+testing+of+Platform+Docs+site)

## Tasks
- [x] Prep test page
- [x] Publicize/recruit
- [x] Synthesize/interpret results
- [x] Make recommendations to SDT
- [x] Share w/ Platform Content

## Acceptance Criteria
- [x] Data is recorded
- [x] Study is written up
