### ISSUE TITLE
[Design] Badge Indicator Research: Experimental design familiarization

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81575]
## Background
Since we completed our usability study on the dot/badge indicator we have decided to proceed with implementation of the badge on My VA for unread messaged (replacing the current dot indicator). We conducted this research in part because it was needed for the experimental design process to ultimately get the badge indicator into the design system. 

## Tasks
- [x] Review previous experimental design documentation on dot indicator
- [x] Consult with design system team to determine whether we can pick up where we left off or if a new cycle is needed

## Acceptance Criteria
- [x] Experimental design process is back in motion

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Experimental design process is underway

**Comment by mattmarino-adhoc** [comment]
New cycle is needed for the badge indicator experimental submission. Timeline on next steps is TBD - VFF related work may delay things.
