### ISSUE TITLE
Update Widget copy after launch

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81585]
## Background
We misunderstood the design intention and the header/description above the representative status was not supposed to be part of the Representative Status Widget.  Instead, it was intended to be hard-coded above the Widget.  This means after the Representative Status Widget launches to 100% we'll want to update it so this content is not in the Widget itself.

<img width="776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ef95c1fd07437f8bd7bfb9b83f3fb8abe8b5d93/image.png" alt="image.png" />

Additionally, [we have guidance from CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809#issuecomment-2074840549) to update the copy when the Widget is loading to "Loading your information" as some users won't have accredited representative information. (Currently the copy is "Loading your accredited representative information")

## Tasks

- [ ] Remove the header/description from the Rep Status Widget code
- [ ] Update the loading copy for the Rep Status Widget to "Loading your information"

## Acceptance Criteria
- [ ] The Rep Status Widget maintains alignment with CAIA's content recommendations.

**Comment by oddball-lindsay** [comment]
@oddball-lindsay will check with CAIA on when we're good to merge this.
