### ISSUE TITLE
[FE] My VA Form Status: Set up feature flag

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81598]
## Background
We need to establish a feature flag in coordination with Veteran Facing Forms team for this work. Daniel completed the vets-api portion of this work in [82683](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82683), for reference. The flag ID is `my_va_lighthouse_uploads_report`

## Tasks
- [x] Consult with VFF team to see if they have already started this work, and if we should have one flag or two for our coordinated effort
- [x] Open PR on `vets-api`
- [ ] Set up feature flag on `vets-website`

## Acceptance Criteria
- [ ] We have a feature flag set up to begin development of the feature

## Resources
- [Technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/technical-discovery.md#technical-discovery-forms-submission-status)

**Comment by ajakabcin** [comment]
rolling to next sprint

**Comment by allisonlu** [comment]
@ajakabcin 

just opened a PR for this ticket, i don't expect any feedback on it so i'll point this as a 0 for sprint 37!

**Comment by allisonlu** [comment]
@DanielMiller-agile6 

can you help validate? 🤠 

- [ ] confirm that you see the feature flag in [featureFlagNames.json on `main`](https://github.com/department-of-veterans-affairs/vets-website/blob/1579897ddf7a2d684932d7684d40f0d3cedbcfaa/src/platform/utilities/feature-toggles/featureFlagNames.json#L135)
