### ISSUE TITLE
Temporary copy of Production Content-build for usability testing of preview environments

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#81597]
to allow early adopters of preview environments to test with the most recent content from content-build, ensure the files in the content-build NFS used by preview environments is properly updates so that new preview environments will reference the latest production copy of content-build code.

### Tasks
- [x] Update the data transfer job to source off the content-build production S3 bucket
- [ ] Ensure that the helm charts create appropriate routing of content build to the NFS

### Acceptance Criteria
- [x] New preview environment instances display the latest production content-build content
