### ISSUE TITLE
Update Allow List Slack notice when no tests are disallowed

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#81593]
## Issue Description
Currently, our Slack notice for the allow list is the same whether there are tests disallowed or not. The problem with that, is that it tags the whole channel to get their attention. For many weeks now, we've had no tests disallowed, but this causes extra noise that hits everyone on platform. We should only be tagging the channel when there's tests disallowed.

---
## Tasks
- [x] Update Allow List weekly status update to only tag the channel if either e2e or unit tests have at least 1 test disabled.
- [x] Remove any irrelevant text when there are no tests disabled. We probably don't need all the fluff text, just "There are no E2E or Unit tests currently disabled" will suffice.

## Acceptance Criteria
- [x] A streamlined experience has been created for the weekly allow list update notification, with minimal noise for platform team members.

**Comment by CBonade** [comment]
This is completed. The new message when there are no tests disabled reads: 

"There are currently no disallowed E2E or Unit tests. Thank you, teams, for all your great work!"
