### ISSUE TITLE
Document Pattern & Best Practices for Helm Chart, app build and Deployment for small green field applications

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#81594]
Create a confluence page with best practices targeting a developer creating a code, a helm chart, terraform, and build & deploy scripts for a new / green field deployment. The format could be tutorial based, or template/best practice based

### Tasks
- [x] Create Example Build & Publish pipeline scripts
- [x] Create TF Plan pipeline script
~- [ ] Create Example deploy pipeline scripts~ moved to a separate ticket
- [x] Create Example Helm Chart
- [x] Create example terraform
- [x] Create Confluence documentation

### Acceptance Criteria
- [x] An example repo with 'current' best practices for a new project
- [x] A confluence page with step by step instructions on creating a new project based on the example repo
- [x] A confluence page with helm chart, terraform and workflow "best practices" for new developers

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/DO/pages/2774040862/Helm+Chart+Best+Practices
https://vfs.atlassian.net/wiki/spaces/DO/pages/3121053820/Atomic+Repository+Concepts+and+practices
