### ISSUE TITLE
Profile | Update contact info edit pages 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#81600]
## Value Statement

**_As a_** developer using contact information edit pages
**_I want to_** update form elements to web components
**_So that_** I don't lose styling when formation is removed

---

## Background Context

Update contact info edit pages to switch from plain form elements to using web components. Also, adjust error messages to remove "Please" as CAIA recommends changing these to "You must"

## Acceptance Criteria
- [x] All contact info edit pages are using web components
- [x] User has an unchanged experience, but sees the latest styling
- [x] All tasks complete
- [x] All tests passing

## Designs and Build Notes

- [FIGMA](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-688&mode=design&t=5Y2HChjjmmbfayGu-0)

## Open questions

- Add here

## Tasks
- [x] Edit phone page uses web components
- [x] Edit email page uses web components
- [x] Edit address page uses web components
- [ ] Update error messages to use "You must"
- [ ] Update unit tests
- [ ] Update e2e tests

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Bumping this work to 3 story points as I discovered there are at least 21 e2e tests that need updating

**Comment by Mottie** [comment]
The PR is ready to merge, but I'm going to wait until Monday 5/13/2024; because 13 is my lucky number. 😄 Actually, Adam Whitlock will be OOO until then, so since this code involves his team, it'd be better to have him available if any issues show up.

**Comment by Mottie** [comment]
Ready for validation in staging

**Comment by eileen-coforma** [comment]
Update error messages to remove "please" on:
- Phone number
- Email
- Address (Country)

**Comment by saderagsdale** [comment]
@Mottie fixes to make:
- Check error messages on HLR, SC, and NOD for any areas that still say "please"

**Comment by Mottie** [comment]
Ready for validation in staging.

**Comment by eileen-coforma** [comment]
@Mottie The "please" have been removed and replaced with "you must"

I did notice this weird margin issue with the errors. Do we need a separate ticket for this?

<img width="535" alt="Screenshot 2024-05-21 at 5 27 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/0fcbd82b-642a-4c46-845b-8ec31d3a7692">

**Comment by Mottie** [comment]
Top margin fix of error messages is now available for testing in staging.

**Comment by eileen-coforma** [comment]
Validated. Also, you shared this in sprint review, so it's done.
