### ISSUE TITLE
Support: Unit Test Stress test crashing

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#81602]
## Issue Description
It seems the unit test stress test is crashing in an edge case when too many files are changed in one application within one PR. This started happening with the batch of unit test stress test changes that were introduced in this sprint. It only impacts a small subset of users, but currently there are approx. 5 people waiting for this to be fixed to merge their work.

---
## Tasks
- [x] Diagnose what is causing the unit test stress test to crash under these conditions.
- [x] Correct the issue and stress test it to ensure that it functions correctly.
- [x] Notify outstanding support threads that the issue is resolved.

## Acceptance Criteria
- [x] The CI pipeline can once again support PRs with multiple files changed in one application.
