### ISSUE TITLE
Discovery: Document Existing GIBCT Deployment Process

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#81614]
### Description
In order to effectively migrate GIBCT to EKS, we should thoroughly understand the current deployment process. To do this, we should gather all files related to the Jenkins deployment, and note all pipelines, webhooks, monitoring, etc to confirm nothing is overlooked as we move to replicate it in Helm/GAs.

### Tasks
- [x] Add a section to [GIBCT EKS Migration](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3089334312/GIBCT+EKS+Migration) for gathering resources (namingly "Existing Deployment Process")
- [x] Outline the flow of deployments for various environments
- [x] Create a list of what actions are already in GAs, and what need to be replicated
- [x] Create a list of environment variables, certs, etc that must be accounted for
- [x] Begin a list of all obsolete files to be removed after service is completely migrated (to be added to if more are discovered)

### Acceptance Criteria
- [x] Thorough discovery has been completed, collecting and documenting all relevant resources as defined above.
