### ISSUE TITLE
[CAIA intake]Form Upload

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#81623]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to start collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

**Note:** If you’re already partnering with us on an initiative, you don't need to fill out this request form. If you don’t have access to your initiative’s CAIA epic, post a message in the [#sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-acessibility-ia) slack channel and tag `@Terry Nichols` and `@Lily Strelich`.

## About your team

- **Team name**: Veteran Facing Forms
- **OCTO product owner:** Matthew Dingee
- **Product name:** Document Upload
- **Product manager:**  Tricia Baker
- **Slack channel:**veteran-facing-forms
- **Dedicated content writer on your team (if you have one):** `Insert name and/or GH handle`
- **Dedicated a11y specialist on your team (if you have one):** `Insert name and/or GH handle`
 
## About your initiative
There is a current tool called QuickSubmit that we were going to point users to so they can upload a handwritten PDF but there are accessibility issues with it.  This is a tool that allows a user to upload a PDF from the Find a Form about page.  There will be three different treatments to the About Page. 
- PDF only version
- PDF and an online form version
- PDF where backed into another larger form - i.e. 21-0966 is part of the 526 but we also have a stand alone version of it
We are working with sitewide on this Fran Cross & Dave Conlon and will create a react widget to place on the About (Detail) page - only certain forms will have the upload option

### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [x] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?
Review Source of truth for content changes

`Tell us briefly about your work and the outcomes you’re aiming to achieve.`

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Wireframes & research

`Enter your description here`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [x] Design intent 
- [x] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:**[80689](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80689)

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.

[Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/tree/main/Forms/DocumentUpload_FindaForm/Sources%20of%20truth)
[Figma Files](https://www.figma.com/file/jnxB6t5V4xgv1WcIL71Qgz/DSC%3A-PDF-Upload?type=design&node-id=1-21&mode=design&t=czAVB7GmayNRRDw7-0)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA operations
- [x] Initial Review - @coforma-terry and @strelichl
```

```[tasklist]
### CAIA a11y tasks
- [x] Staging Artifact Support `TBD`
- [x] Research with AT? Is Jeana supporting that and assisting in the design?
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85573
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85447
```

```[tasklist]
### CAIA content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85538
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/100775
```

```[tasklist]
### CAIA IA tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90793
```

**Comment by tbaker1026** [comment]
**A. Can point to a specific form or forms**
These we can handle the English version by pointing users to the About form page or pages (and we can work on getting Español versions)
[VA Survivors Pension (ESP version)](https://www.va.gov/pension/survivors-pension/)
[About VA DIC for spouses, dependents, and parents (ESP version)](https://www.va.gov/disability/dependency-indemnity-compensation/)
[Veterans headstones, markers, and medallions](https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/)
[How to apply for a VA pension as a Veteran](https://www.va.gov/pension/how-to-apply/)
[Burial in a private cemetery](https://www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/)

**B. Do not point to a specific form, or are unclear about which form or forms they might be pointed to**
These we cannot handle, at least not right now. We're not yet able to handle ANY VA form ala QuickSubmit. We can handle specific VBA Compensation and Pension forms that can be submitted via the Benefits Intake API. When Premal's IVC Forms team gets VHA forms working through Pega then we MAY be able to handle SOME VHA forms through that mechanism. We cannot (and probably should not attempt to) handle rando document that may or may not be a VA generated PDF. I would recommend that we STOP pointing users at QuickSubmit from these pages. The QuickSubmit UI does not meet our accessibility standards. If there are specific forms we can point to then we could shift traffic towards the new tool once it has shipped.
[Upload evidence to support your disability claim](https://www.va.gov/disability/upload-supporting-evidence/)
[How to change your legal name on file with VA](https://www.va.gov/resources/how-to-change-your-legal-name-on-file-with-va/)
[How to apply for the GI Bill and related benefits (ESP version)](https://www.va.gov/education/how-to-apply/)

**C. Point to QuickSubmit but have, or will soon have, a superior online experience**
When a user can apply online I would not recommend pointing toward PDF upload (neither QuickSubmit nor this new tool) as it provides a sub-par experience.
[Presidential Memorial Certificates](https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/)
[Get help from a VA accredited representative or VSO](https://www.va.gov/get-help-from-accredited-representative/)

**D. Points to a specific form but requires additional documentation that is not part of the PDF form.**
We cannot handle these, at the moment. We'll do an audit to see how many forms have this requirement (we were aware of this category but I didn't realize this form was one of them)
[Get paid back for test fees](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/)

**Comment by laurwill** [comment]
Hi @tbaker1026 @jeana-adhoc @rachelshearerux , 
Thanks for talking about this work with me and @megzehn this week! Noting here some questions from that chat and a couple more I had while reviewing this intake. 

**How will the find-a-form uploader relate to & communicate with the claim status tool?**
- Many forms that seem to fit the use case for this find-a-form uploader are supporting forms for VA claims that appear in the claim status tool. This page lists some of these additional forms: https://www.va.gov/disability/how-to-file-claim/additional-forms/
- I believe Veterans can currently upload these forms in the claim status tool by going to the open disability claim and selecting the Files tab. That screen allows Veterans to upload any document they want to submit in support of their claim, including supporting forms. 
- If a Veteran uses the find-a-form uploader to submit one of these forms, will that uploaded form appear in the claim status tool attached to the related claim? 
- I think you said you were planning to reach out to the CST team to learn more about this connection — have you all been in touch with them about overlap between these products? If a Veteran can use either this feature or the claim status tool to upload a form, which will we recommend? 

**How will we confirm receipt or communicate status of these uploaded PDFs?**
- This work is creating a new way for Veterans to submit VA forms online through VA.gov. I think you said in our sync that there's no current plan to show these uploaded PDFs in My VA with the new post-submission statuses. 
- Will there be any way for Veterans to track the status of forms they submit through this feature in find-a-form?
- The confirmation screen in Figma looks identical to an online form confirmation screen, so this might create an expectation that these forms will appear in either My VA or the claim status tool once VA receives them in the backend. If that's not the case, how will we make it clear what "submitted" means here? 
- How will we handle post-submission errors/failures for these PDF uploads? I'm assuming the same type of "silent failures" are possible here, where a Veteran uploads a PDF, gets a success message, and then our backend system loses the form and it never gets into a queue for processing. Is that possible?

**How will this project categorize PDF forms with optional or conditional supporting documents?**
- All 5 pages listed in "A. Can point to a specific form or forms" either always or sometimes require supporting documents along with the PDF form. 
- Many forms we work on either suggest but don't require that the applicant upload supporting docs, or require supporting docs only for certain scenarios/applicant types. 
- If a form has optional or conditionally required supporting docs, will you allow upload through this feature? 

Happy to sync again if it's easier to discuss on a call!

**Comment by rachelshearerux** [comment]
@laurwill, @tbaker1026 and I met to talk through these questions. 

I've compiled our Q&As in the GH folder for this project [here.](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/DocumentUpload_FindaForm/CAIA%20Questions%20%26%20Answers.md)

**Comment by laurwill** [comment]
Hi @rachelshearerux , I left comments in the Figma file with a few questions and suggested content edits. I'm not sure if we did IA work on this yet, so I'll check in on that on Monday. 

My biggest remaining question is about tracking the form post-submission. The designs currently list SSN, file number, and zip code as info we'll "include" with the form so that they can track it. Is this the info we pull from their profile to tie the form to the correct person? How can they track the form exactly — do they need to call a number to ask about the status?

**Comment by kristinoletmuskat** [comment]
Hi @rachelshearerux  and @tbaker1026 , here is the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/find-a-form-upload.md) and [IA mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723739688312/66816378c17c92835f7a65108057fc255226cb10?sender=ua67f17f1c416a96ea04d2476) updated based on yesterday's conversation among Mikki, Tricia, and Matt. 

Could y'all take a look and let me know if you have any questions or clarifications?

Also, are you planning a staged rollout for this feature, or rolling out to 100% of users at once?

**Comment by tbaker1026** [comment]
@kristinoletmuskat - we will have this on at 100% but only for two forms to start so we can monitor traffic.

**Comment by tbaker1026** [comment]
@mnorthuis Here is the original ticket for Form Upload.  
**Changes:**
URL:  /find-forms/upload/#/introduction
/find-forms/upload/21-0779/introduction

**Introduction page:**
- We will add a link so users can return to the about page

**Upload Page:**
- We will create a static Drupal content page with instructions on how to use the tool
- No index page so it does not show up in search

**Comment by mnorthuis** [comment]
@tbaker1026 I updated Kristin's IA spec document to reflect changes related to our conversation per above.  Please let me know if you have any questions.  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/find-a-form-upload.md

@DanielleThierryUSDSVA This is the project requiring a new Drupal tool landing page we spoke about.

**Comment by jeana-adhoc** [comment]
@mnorthuis - We're working on the `<title>` tag for forms that use this form upload method.

Currently form title tags are generated with static content. So, it would be easiest for all forms that are under the url path `/find-forms/upload/[full form number]/*.*` to have the `<title>Form upload | Veteran Affairs</title>`

We're thinking this is possible based on the exception in [VADS](https://design.va.gov/content-style-guide/title-tags#exception-2--forms-and-subtasks)

> [Title tags - VA.gov Design System](https://design.va.gov/content-style-guide/title-tags#exception-2--forms-and-subtasks)
> On [VA.gov](http://va.gov/), title tags are pulled from the H1 (the page title), so it’s especially important to use the primary keyword or phrase in the page title.
> 
> Each page in the flow should have the plain language form or task name as the title tag. This may be different from the H1.
> - Example: Income Limits | Veterans Affairs

We would consider "Form upload" the task name.

If the the title tag needed to be this, `<title>Upload VA Form 21-0779 | Veteran Affairs</title>` in order to match the `H1`, we'd have to do some js to update the title after we receive it, and figure out where to call that from static content, we can't provide the number, since this particular form is dynamic

Is this an acceptable `<title>` tag, `Form upload | Veteran Affairs` ? 

Thanks

**Comment by mnorthuis** [comment]
Technically you need to match the H1 of the form to meet standard. This would ensure the unique title tag a11y requirement for each instance of this flow.  The exception is once in a flow the title tag can stay consistent - so a user could have multiple form flows open in multiple tabs and each would be uniquely named, but we don't support them opening different pages in a single flow in separate tabs because that could create submission issues. 

We also have to be careful that the form flow title tag is diffentiated from the drupal parent page which will likely be something like "Upload VA forms".

**Comment by tbaker1026** [comment]
@mnorthuis Here are some sample URLS now in staging
[Request for Nursing Home Information in Connection with Claim for Aid and Attendance](https://staging.va.gov/find-forms/upload/21-0779/introduction)
[Improved Pension Eligibility Verification Report (Surviving Spouse with No Children)](https://staging.va.gov/find-forms/upload/21P-0518-1/introduction)
[VA Form 21P-0516-1 Improved Pension Eligibility Verification Report (Veteran with No Children)](https://staging.va.gov/find-forms/upload/21P-0516-1/introduction)

**Comment by coforma-jamie** [comment]
> [!NOTE]
> ## Accessibility Digital Experience (DE) Ticket Status Update
> Accessibility DE is OCTO’s new accessibility team. We’re working on a new intake process. In the meanwhile:
> - This ticket has been moved to validate and will be closed on the Accessibility DE pipeline (only).
> - This ticket will remain “open” until the work from content and IA is completed.
> 
> If you need additional accessibility support, contact the Accessibility DE team on [#accessibility-help](https://dsva.slack.com/archives/C8E985R32).
> **Thank you for working with the accessibility team!**

**Comment by mnorthuis** [comment]
Hi @tbaker1026 The URLs look ok except that there should not be upper case letters.  Our URLs are all lower case. 

So this URL:  https://staging.va.gov/find-forms/upload/21P-0518-1/introduction
should be: https://staging.va.gov/find-forms/upload/21p-0518-1/introduction

**Comment by tbaker1026** [comment]
@mnorthuis will open a ticket to lower case the p - thank you

**Comment by mnorthuis** [comment]
Work for this product launch is complete.
