### ISSUE TITLE
GitHub Workflows Update for k8s & master Merger 

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#81621]
## Summary

The final step for merging k8s into master (from the `vets-api` perspective) is to update the build and deploy workflows. 

## Tasks
- [x] Separate the build.yml workflow into two separate workflows
     - [x] test, lint, & security 
     - [x] build & publish (related to docker images)
 - [x] Update deploy workflow to deploy to non-prod environments
 - [x] Remove any duplicate workflows (only need to run unit tests once)

## Acceptance Criteria

- [x] Master is automatically deploy to non-prod environments
- [x] Unit Tests, Linting, & Security Checks run on pushes
- [x] Docker images are created/updated for PRs and master
- [x] the k8s branch isn't needed for deployment

**Comment by stevenjcumming** [comment]
Status Update: Waiting on PR Review

**Comment by stevenjcumming** [comment]
Status Update: Make updates based on reviews. Looking for more reviews from other teams

Target Merge Date: 5/14/24

**Comment by ericboehs** [comment]
For context, the merge date was coordinated in Monday's BE CoP meeting.

**Comment by JoeTice** [comment]
SPRINT 52 STATUS: IN PROGRESS - This work has been completed, but we're leaving this open to allow sufficient time for engineers to review and make changes to their code that may be impacted by this change. We will plan to close this on 5/14/24.
