### ISSUE TITLE
Design + FE | Profile | Direct deposit | Update content in downtime notification

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#81626]
## Background
We learned yesterday that in the EDU downtime alerts we should direct users to the EDU call center at [888-442-4551](tel:8884424551)

## Task

- [ ] Update content in current downtime alert mock-ups to reflect this new phone number
- [ ] Get approval from CAIA
- [ ] Implement on FE
- [ ] ... more FE tasks ...

## AC

- [ ] The downtime alerts direct users to the EDU call center for EDU DD needs in Figma and in code

**Comment by andaleliz** [comment]
@mtcA6 here is the ticket per your message yesterday.  

@adamwhitlock1 figure that it's easier to just work from the same ticket since this is fairly small, but feel free to create your own if you disagree.

**Comment by adamwhitlock1** [comment]
@andaleliz Here is what I have for when the entire page is brought down via the `profileHideDirectDeposit` toggle:

![Screenshot 2024-04-25 at 12 21 49 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/66175a69-fc88-4cf0-ab5e-306480ea1578)

**Comment by andaleliz** [comment]
@adamwhitlock1 perfecto, this is so helpful. Thank you!

**Comment by adamwhitlock1** [comment]
I have a branch 'ready' with these changes. Do we need to remove the start and end time sections of the alerts, or just the end time? @mtcA6 what do you think?

Here is where I'm at currently.

<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNCtWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8bd22c225b81fd8377a4f05535087ce4d36a600/Screenshot%202024-04-25%20at%204.44.08%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 4.44.08 PM.png" />

**Comment by andaleliz** [comment]
@adamwhitlock1 Laura said that the start/end times in the mock-ups align w/ what they have on content pages, fwiw.

I'm waiting to hear back from her on the content in the alert when we have to bring down the whole page. The design piece will be complete once I hear back.

**Comment by andaleliz** [comment]
@adamwhitlock1 Laura responded to this and the content in the mock-up is good to go. I split up the [edu-only downtime](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=234-4876&mode=design&t=9iLLHAOmKSDYMXWd-11) and [the complete downtime](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=1199-4604&mode=design&t=9iLLHAOmKSDYMXWd-11) into two sections, hopefully that's easier to wrangle now that the desktop screens are there too.

**Comment by adamwhitlock1** [comment]
@mtcA6 This is ready to validate in staging. I turned the whole direct deposit page off for user 380 and it looks like this:

<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--287ba2d847e59a0fc6c254cb2a21bf66d4a2e7e4/Screenshot%202024-04-30%20at%204.20.34%E2%80%AFPM.png" alt="Screenshot 2024-04-30 at 4.20.34 PM.png" />

**Comment by mtcA6** [comment]
Great! Only issue I see is one errant comma for the GI benefits part: 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/3e243d5c-13ab-4aac-b202-eea5957b3b02)

I also checked the edu downtime one and that's looking good as well 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/e76ffcf0-caf5-4984-b7db-032493a1ceef)

@adamwhitlock1 can you confirm if this one in prod?

**Comment by adamwhitlock1** [comment]
@mtcA6 good catch on the extra comma. I'll fix that up here shortly.

Yep the edu downtime alert is live in prod now.
