### ISSUE TITLE
[Epic] Chatbot

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#81622]
This epic will house work related to VA Chatbot.

The tickets are organized by intake:
**Intake title as task list title**
- intake ticket
- associated child tickets (linked to epic, not nested under intake ticket)

```[tasklist]
### Chatbot Benefits: Micro-Services
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78614
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79014
```

```[tasklist]
### VA Chatbot: Prescription Skill Feature
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/64157
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66249
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/65945
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67309
```

```[tasklist]
### Global Chatbot Work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66755
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73543
```

**Comment by SarahKay8** [comment]
Confirmed with virtual agent team this is okay to close 

@anitadewitt-va @sara-amanda

**Comment by mnorthuis** [comment]
no remaining content and IA work for this effort.
