### ISSUE TITLE
AE - Sprint 20 (4/22-5/5)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8164]
# Order of priorities

## Project Work
1. Implement analytics tag for My VA health chat alert
2. Profile 2.0: Design updates from user testing; content review; IA plan and review
3. Profile 2.0: Continue build
4. Profile 2.0: Analytics planning
5. Address validation: Follow-up with veterans to see if they are still having issues saving their addresses
6. PM: Review team docs

## Non-project work
1. Onboarding Sandra Hallie 

## Covid-19
- [x] Implement analytics tag for My VA health chat alert #8033

### Design
- [x] Review content pages/My VA dashboard for any needed updates #5518
- [x] Review My VA for any links/content that need to be updated #5522
- [x] Review Change your address content page for any links/content that need to be updated #5524
- [x] Review Direct deposit content page for any links/content that need to be updated #5525
- [x] Review Sign in FAQ for any links/content that need to be updated #5527
- [x] Determine if there's any other pages we might have missed in this list above #5528
### Tickets that came out of usability testing:
 - [ ] [Design] - Update email address mocks #8229
- [ ] [Design] Create mocks for new mobile view (name tag) #8231

Stretch goal: Content/IA - IA review (VSP cycle)****

### Build 
- [x] Add visible character limits to Profile fields #8199
- [x] Create a new side-nav component #7256
- [ ] Connected apps #5357
- [ ] Direct deposit #5355
- [x] Profile 2.0 breadcrumbs do not show current section #8586

### Analytics
- [x] Re-Evaluate Analytics #7470 (Matt) (add updated KPIs to product outline)
- [x] [Analytics] Put together analytics plan #8182
- [ ] [Analytics] - Submit request for review (Ticket will show up when created)

## Address validation
- [ ] Follow up with veterans to see if this feature resolves their issues saving addresses #6012

## PM
- [x] Review updated authenticated experience team documents #8038
- [x] Sandra's onboarding checklist #8074
- [ ] Determine what staging users we need/should use for Profile 2.0 QA #8284

## Monitoring, maintenance, bug fixes, hardening, 508
- [x] Profile addresses missing comma between 2nd and 3rd street address lines #7498
- [x] Profile contact info edit modal should scroll to error alert when it appears #6634
- [x] [FE] Remove "Change your contact information..." modal that shows when users go to the profile #7537
- [x] [FE] Remove "Check out your new personalized homepage" footer banner #7535
- [x] [FE] The profile fails to show the international postal code for an international address #7525
- [x] [FE] Profile mailing address handles international addresses poorly #7493
- [x] Profile contact info edit modal should scroll to error alert when it appears #6634
