### ISSUE TITLE
Update Page Footer links

### ISSUE THREAD

**Issue by taylojill** [department-of-veterans-affairs/va.gov-team#81651]
## Issue Description
Users of Platform Website are increasingly requesting that internal links open in the same tab, rather than opening a new tab. As part of an effort to correct this across the website, we should update the Feedback Footer links page in Confluence so that these links work correctly on Platform Website.

---
### Tasks
- [x] Update Page Footer links to point to Confluence pages: [https://vfs.atlassian.net/wiki/spaces/SUP/pages/1807909029/Page+footer](url)

### Definition of done
- [x] Page footer is deployed globally with updated links
 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
### Tasks
- Update Page Footer page links to point to Confluence pages: [https://vfs.atlassian.net/wiki/spaces/SUP/pages/1807909029/Page+footer](url)

### Definition of done
 - Page footer is deployed globally with updated links

**Comment by taylojill** [comment]
Updated three links (#2-4) under Help and feedback footer to point to Confluence pages.

**Comment by jknipes** [comment]
Work is completed, moving to _Done_
