### ISSUE TITLE
Onboarding Sandra Hallie

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8167]
## Background
Sandra started with GCIO last week 4/16/20. Matt will be getting her up to speed and assist her with any account creations and learning/onboarding material.

## Tasks
- [x] Provide Org Chart
- [x] Review Team Charter
- [x] Review Product Outlines
- [x] Review Team meetings and ceremonies
- [x] Review how the sprint process works
- [x] Provide helpful powerpoint documents from onboarding guide
- [x] Ensure set up on Github/Zenhub
