### ISSUE TITLE
Sign in experience, front end, onboarding

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#81676]
## Description of UX Tasks
As our team prepares to take ownership of the sign in experience front end, we want to gain understanding of this product and where it currently stands.

## Tasks
- [x] Review [Mikki's audit for account creation and sign-in flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/discovery/account-creation-and-singn-in-flow-audit.pdf)
- [x] Review [latest content updates made by CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76785) -- Note: we should not offer feedback on their changes at this time
- [x] Review discussion on a signing in with a verified account vs unverified (MHV basic) [in slack](https://dsva.slack.com/archives/C0581MN69TJ/p1710444352578229)
- [x] review [error messages for sign in](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/error-messages/sign-in-error-handling.md)
- [x] review [troubleshooting error messages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a080cd1dd0794ad802780ea59cdf68c6cf8edadf/products/identity/Troubleshooting_logging/troubleshooting_signin.md)
- [x] meet with CAIA
   - sync scheduled for 5/2
   - Is there an existing inventory on sign in widgets? If not we need a new task/ticket for this work
   - Has usability research been done on these widgets?
- [x] meet with Mikki and/or Danielle if it would be helpful
   - [Mikki Mural on sign in flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707497060514/1b011002bf25fbfe1f1c832c0566296ed86c0bb9?sender=u2aba00c97ab77c6ec1573123)
   - [Mikki Google sheet on sign in flows](https://docs.google.com/spreadsheets/d/1p0LV9q0hv8RCE-6r6PuiA454RE8PqC-K1QIt8QNsduQ/edit?usp=sharing)
- [x] maneuver through various VA.gov pages to test and understand the sign in flows
   - focus on most used experiences and those we know require add'l security, like checking claim status, payment history, health tasks, changing address in profile and changing direct deposit in profile.
- [x] Review VA Design system for [alerts](https://design.va.gov/components/alert#sign-in-or-tool-prompt)
   - note that VA DS page for [signed out vs. signed in](https://design.va.gov/templates/signed-out-vs-signed-in#cta-required-to-continue))pages was not showing V3, at last check
- [x] Pull Medallia survey info that relates to sign in 
   - [request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82577)
   - pull out findings from data
- [x] Pull Support request data from My411 VA support
   - [request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82569)
   - pull out findings from data  
- [x] [Draft summary of insights](https://docs.google.com/document/d/1J0SM9rtLBQLaRB7ZjvoYtIglihtT8PbRyM5sFfsIYfE/edit) and findings
- [ ] present at demo

## Definition of Done
- UX/content team has a foundational understanding of this new (to us) product

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Add finalized research to Github
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asg5704** [comment]
Just a couple of notes from briefly reading the audit

- The "new homepage" has the "Create an account" which just opens up the Modal
  - Our team did not work with the "new homepage" team on this work
  - We also have two CSP's (Login.gov and ID.me) that users can create accounts with which is why it opens the modal. If we only had singular CSP to create accounts with this would be a different story.
- The "Identity verification flow" on the verify page when trying to start the "verification process" the user has to sign in again
  - This is on purpose in an effort to mitigate fraud attempts in case a user's account is compromised.
- The "sign in CTA for starting forms"
  - Our team has never managed this CTA nor which forms require an LOA1/LOA3 account (its been owned by a combination of platform and platform-forms)
- Different "sign in flows" based on where a user is
  - Some of these flows are different on purpose or were a requirement by specific teams (as recommendations from user research). An example is the AuthExp team in which if a user was on the homepage when they signed in, they would land on the `/my-va` page after authentication finished. Another example is with the Education forms team, a user starts on a static page but is redirected to a different page to start the education form to fill out.

**Comment by kdmeg-bluetiger** [comment]
@claytonzook  - I added some [notes](https://www.figma.com/board/0YKeTCwBJKc47UU5WBliIL/Sign-in-experience?node-id=9-66&t=rmR2NQLqW8M5k6wF-4) on how to run content comprehension testing if we decide to test a concept that more clearly delineates the role of the CSP vs the role of VA.gov.
