### ISSUE TITLE
[CST] [ENG]Update the date shown in "Last updated" timestamp in Status tab of disability compensation claims

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#81672]
## Value Statement
**_As a_** Veteran
**_I want to_** see when the very latest update to my claim was made, including tracked item updates
**_So that_** I know when the last meaningful action on my claim was taken 

---
## Background Context

Right now, the "Last updated: [date]" section of the Status tab for disability comp claims is not pulling the most recent date. The most recent date also includes tracked item and file upload updates. 

Assumption:

- The current phase date will never be more recent in time than the latest tracked item in recent activity.

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk9VQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba5266b018f6f9b47aee6d610d4aee0f4b8fa36c/Screenshot%202024-04-25%20at%203.16.00%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 3.16.00 PM.png" />

The design intent is that the "Last updated" date matches the date of the most recent item in the "Recent Activity" list. 

<img width="1002" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d220ed01a7daf1c0cbacad3365a29036b2812ff/Screenshot%202024-04-25%20at%203.16.31%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 3.16.31 PM.png" />

### Example where dates are not aligned
<img width="500" alt="Misaligned dates" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13838621/c768342a-8c46-4c04-ac0b-95a4695d2503">

### Enablement team (if needed)
@member of team

## Engineering 
- The `Last updated:` date currently comes from `attributes.claimPhaseDates.phaseChangeDate` which only tells us the last time the claim changed phases. Other things such as tracked items being opened / closed / updated and documents being uploaded will show up in the recent activity section, which is why the dates may not be aligned
- We will want to update the logic on `ClaimStatusHeader.jsx` so that it is pulling in the most recent date
- The date shown for tracked items will need to use logic like the current RecentActivity.jsx 
`  const getTrackedItemDateFromStatus = item => {
    switch (item.status) {
      case 'NEEDED_FROM_YOU':
      case 'NEEDED_FROM_OTHERS':
        return item.requestedDate;
      case 'NO_LONGER_REQUIRED':
        return item.closedDate;
      case 'SUBMITTED_AWAITING_REVIEW':
        return getOldestDocumentDate(item);
      case 'INITIAL_REVIEW_COMPLETE':
      case 'ACCEPTED':
        return item.receivedDate;
      default:
        return item.requestedDate;
    }
  };`

## Tasks
- [ ] _Update "Last updated" so that it's pulling the most recent available date (this should match the most recent item in the "Recent Activity" feed_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The "last updated" date should match the most recent date in the "Recent Activity" list.

**Comment by pmclaren19** [comment]
Merged to Staging. Tested in Staging and looked good. The only thing I noticed was some weirdness with this claim on user 23 https://staging.va.gov/track-claims/your-claims/600495716/status but the logic doesnt look accurate. I dont think its possible to have a claimDate on 8/11/24 and a phaseChangeDate and phase1CompleteDate in the past on 4/12/24. @jerekshoe @jacobworrell @skylerschain LMK your thoughts. 
![Screenshot 2024-07-24 at 10 08 45 AM](https://github.com/user-attachments/assets/5dd8bce6-5e9f-4eb9-aa68-42c9a175712a)

**Comment by pmclaren19** [comment]
Discussed this in parking lot today with the team. This occurs with BDD claims aka claims with claim type code : `400PREDSCHRG`. It is expected that the claim date would be in the future for these, while the other phase dates would be in the past. (Occurs when someone files for a claim for something but they have no been discharged yet so the claim date is set to their discharge date.) 

This is definitely something that we will want to investigate. @jacobworrell is going to do some investigation of this with Jerek and Andrew and will make a ticket if necessary.
