### ISSUE TITLE
[CDP] VBA- Fix missing this page icons and make pay online accordion item expanded

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#81679]
## Description

After updating the icons in the On This Page component, I discovered an issue with the VBA On This Page component. The new `va-icons` were missing and I also saw a missing `.` on the `va-alert` in the detail page. Also, the Pay Online method in the accordion needs to be changed to open. 

| | |
| ------- | ------ |
| Debt Summary  | ![staging va gov_manage-va-debt_summary](https://github.com/department-of-veterans-affairs/vets-website/assets/1631062/df49c8ab-d5de-42b3-afb4-a66ef89aa05c) |
| Debt Detail | ![staging va gov_manage-va-debt_summary_debt-balances_details_79612301872](https://github.com/department-of-veterans-affairs/vets-website/assets/1631062/0e4b3e2e-f4e7-4cee-a6bd-f61a33c61d4f) |

## Tasks
- [x] Fix the missing icons on the on this page component
- [x] Add a missing period in the alert box on the detail page.
- [x] Make the pay online option default to open

## Acceptance criteria
- [x] Missing icons are present
- [x] Missing period has been added
- [x] Pay online accordain item has been set to open

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
