### ISSUE TITLE
Update EZR static page sign-in widget with final content

### ISSUE THREAD

**Issue by katelyncai** [department-of-veterans-affairs/va.gov-team#81690]
## Issue Description
CAIA is discussing content for the sign-in widget on the static page (previously lived on the intro page) for EZR. When we receive final content from Aliyah and folks, we'll want to reflect that in the Figma file.

---
## Tasks
- [ ] Monitor and participate in discussion with CAIA as needed
- [ ] Update the [Figma file](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=2711%3A51590&mode=design&t=b6SLYu5EPIJD77qU-1) to reflect final content for sign-in widget on static page
- [ ] _Success:_ Figma is the source of truth for how the Static page looks in production with updated sign-in widget content.
