### ISSUE TITLE
[spike] Determine course of action for primary phone numbers

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#81705]
## Value Statement

**_As a_** Veteran

**_I want to_** be able to choose which number I want to use as my primary number

**_So that_** VA has the best number to contact me with

---

## Background Context

In our Supplemental Claim form, we show both the home & mobile phone on the contact information page. Immediately after that page is a question asking if either the home of mobile phone is a primary phone number. Currently in the NOD form, we only show the mobile phone assuming that the Veteran has a mobile phone. They may already be using the same number for both the home & mobile phone, but we still want to give them a choice.

As Mottie started working on adding a primary phone question to NOD, he encountered a few concerns.

But some background first:

- All of the contact info page code used to live in each of our app's folders.
- NOD & HLR only required a mobile phone number
- Supplemental Claims used to require a home OR mobile phone number, but not both.
- When the code was generalized, and moved into platform, supporting a requirement of home OR mobile became very complicated, so it was made to require BOTH home and mobile
- In anticipation of adding a primary phone page to NOD, a https://github.com/department-of-veterans-affairs/vets-website/pull/29234 - that's working fine, but not yet merged. 

The concern was noted after working on NOD:

- When adding a home phone to the contact info page, we're now locked into the requirement of having both a home & mobile phone defined in their profile
- If the Veteran has an in-progress form, they won't know about the requirement until they try to submit - good thing is that the accordion chapter and page within will highlight and a message stating that the primary phone isn't defined will be visible; so maybe we need to add a redirect back to the contact info page?
- If we add a redirect, should it go the primary phone page if they do have both home & mobile numbers? Or should it go to the contact info page if the home number is missing?
- If we add a redirect, we'll need to add a feature flag so we can test and limit usage until everything is validated

With these concerns, I think we need to further investigate and discuss them before proceeding with implementation. That, and this extra work would change the work estimate.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Best course of action has been decided for this issue
- [ ] Level of effort has been determined

## Designs and Build Notes

- [FIGMA Contact info](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=705-10716&mode=design&t=JtldjKm6CJ5SPkIU-11)
- [FIGMA Primary phone number](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-689&mode=design&t=GMTShBLETYL8WYU6-11)

### Enablement team (if needed)
@ enablement team if needed

## Out of scope

- Code work to add primary number

## Open questions

- What's the lift to allow validation for users to have _either_ a mobile _or_ home phone number?
- What should the pattern be if a user only has one phone number? Do we still show the primary number page?
- What's the risk of requiring users to have **both** a mobile _and_ home phone number?
- How do we surface this new question for in-progress form?
   -  Redirect?
   -  Show on review and submit page?

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
The preferred scenario is still the following:
-  If available, the contact page shows both home & mobile phone numbers
-  Home phone number can be edited after clicking 'edit' link
- Mobile phone number can be edited after clicking 'edit' link
-  Veteran must choose between home and mobile phone number for their primary phone
-  If only one phone number is defined within the Veteran's profile, primary phone number defaults to that number

If form is in progress:
- On review and submit page, show required primary phone number as error. Show warning alert that notifies users can add a home phone number if desired

Open questions:
- What are the limitations for adding a validation for either phone numbers?
- Does this method pose less or more risk for in-progress forms than doing a redirect back to the question?
