### ISSUE TITLE
Update link color within Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8170]
## Problem Statement
How might we bring the Facility Locator UI closer to compliance with the Design system?

The link color currently used for directions and phone numbers needs to be updated to be consistent with the Design system. 

## Goal
Design consistency across VA.gov

---
## Tasks
- [ ] Update links for phone numbers and direction within the Facility Locator front end to use [_color TBD_]. 

## Acceptance Criteria
- [ ] Phone numbers displayed within Facility Locator search results use [_color TBD_]. 
- [ ] Phone numbers displayed on Facility Locator detail pages use [_color TBD_]. 
- [ ] Direction links displayed within Facility Locator search results use [_color TBD_]. 
- [ ] Direction links displayed on Facility Locator detail pages use [_color TBD_]. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
