### ISSUE TITLE
Prometheus deploy to vagov-dev broken for multiple weeks

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#8171]
## User Story or Problem Statement
Prometheus deploy to vagov-dev is broken with errors pertaining to date formatting on the "Remove snapshots older than 30 days" step. Multiple attempts were made to resolve the issue, but have had no success at this time. The job in question can be found at http://jenkins.vfs.va.gov/job/deploys/job/prometheus-vagov-dev/ and the various breaking errors can be observed per job there. 

## Goal
To get this job working again.

---
## Tasks
- [ ] Get job back in working order
- [ ] [Optional] Possibly do some discovery on a better option for automated removal of ebs snapshots > 30 days

## Acceptance Criteria
- [ ] Job is working once again
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
