### ISSUE TITLE
Add CC question to Platform Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81710]
## Purpose
There currently isn't a question in the Survey about Collab Cycle.  Given that it is an interaction point for so many VFS users, it seems like a needed addition

Discussed during Sprint review:  https://vfs.atlassian.net/wiki/spaces/SDT/pages/3116236801/Sprint+Review+-+4+25+24#Dan%3A

## Tasks
- [ ] Work w/ Shira & Governance for a suitable question
- [ ] Add the question to the Survey for future use

## Acceptance Criteria
- [ ] Survey is updated with additional question
- [ ] 

# No longer needed. Absorbed into [this ticket](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/66969)
