### ISSUE TITLE
[task] SC | Gather form update requirements

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#81723]
## Value Statement

**_As a_** product team

**_I want to_** gather the requirements for the 0995 form updates, and understand which part of the form updates are relevant to the VA.gov online form

**_So that_** we can make specific updates to the VA.gov 0995 form

---

## Background Context

There's been an update to the paper 20-0995 Supplemental Claim form. The new form contains changes to the instructions and new sections within the form fields. The form updates are essentially complete, and have been sent to OMB for approval. Before we get started on the design, we need to identify which sections are relevant to the online form, and what our business stakeholders need with these updates.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [x] New sections have been identified for the online form
- [x] SMEs have been Identified for review of this work
   - Kayce White
   - Monica Willis (OAR)
   - Elysabeth Hepworth (214 Quality)
   - Michael Hobson (LH)
- [ ] Stakeholder requirements have been captured
  - [ ] The impact that the business logic has on claim development is captured
  - [ ] The meaning of content is clear
- [ ] Align with OCTO stakeholders on the work

## Designs and Build Notes

- [MURAL](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714484854529/9d8878c66064362f8bdaed6531bcfb43fa8064f6?sender=ud193ce75f65a17a316ea6194) - Current form screens + updated PDF changes

### Enablement team (if needed)
@jstrothman 

## Out of scope

- Add here

## Open questions about form changes

**Regarding Option for VBA to notify VHA about certain upcoming events during the claim and or appeal process**
- What happens when a notification is sent to VHA? 
  - Who / what type of role at VHA would have access to this information? 
  - How will the healthcare provider use this indicator?
  - What is the indicator suppose to do for the Veteran or VHA?
  - Does having the indicator mean not having to revisit traumatic events with VHA? If so, how?
- How is the notification sent to VHA, what system will receive it?
  - Or is it that VHA ultimately notifies VA health care providers of the events?
- How does this impact the Veteran (if it does/doesn't benefit the Veteran)?
  - Why a Veteran might want to consider giving this consent? 

## Tasks

- [x] Set meeting with SMEs to go through form changes
- [x] Capture update requirements
- [ ] Align on scope of work

## Definition of Ready
- [ ] Final approved form is available
- [x] List of collaborating SMEs are identified
- [x] Mural board for facilitation is ready
- [x] Session scheduled with for SMEs and enablement team

## Definition of Done
- [ ] Requirements captured
- [ ] Scope defined
- [x] SMEs identified

**Comment by jstrothman** [comment]
SSoT for form changes is in the [VAF20-0995 Revision IPT Teams channel files](https://teams.microsoft.com/l/channel/19%3Aogpw-jKeHzEv2w_uGY-G4Ay6IsDen5J7npgUZOaNodE1%40thread.tacv2/General?groupId=eebaaf97-87a1-4b69-b72c-f4751782bc50&tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf)
[02-28-24 Copy from IPT Files in Benefits Portfolio SharePoint](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/Supplemental%20Claims/2024%200995%20updates?csf=1&web=1&e=uMFxjA) -- folder includes highlighted changes

**Comment by eileen-coforma** [comment]
@saderagsdale 

**Questions about scope**
- Are we including the unauthenticated pages within the scope of this? I assume so, but given the dependence on the content team (and possible inability to embed cuz of overload), do we want to take suggesting changes on as part of the updates?
- Do we need an initiative brief for this work, and should it be included within this AC?

- Is this [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714484854529/9d8878c66064362f8bdaed6531bcfb43fa8064f6?sender=ud193ce75f65a17a316ea6194) enough to get the conversation started?

If so, I'm ready to discuss, but may need more time if I'm also breaking down the unauthenticated page.

**Comment by eileen-coforma** [comment]
First session completed on 5/15 up to MST question
Second session scheduled for this afternoon.

**Comment by eileen-coforma** [comment]
Sent an email to Kayce to follow-up on the VHA (MST) notifications and set up an SME meeting.

**Comment by eileen-coforma** [comment]
Meeting completed. Work will continue on a separate ticket.
