### ISSUE TITLE
Appoint a Rep Digital Submit - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#81720]
## Issue Description
User testing of Appoint a Representative Digital Submission flow.

## Tasks
- [ ] Create GitHub research folder
- [ ] Create research plan
- [ ] Define screener questions
- [ ] Create conversation guide
- [ ] Submit all materials to team for review
- [ ] Create revisions Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Shared with team for review - https://drive.google.com/drive/folders/17eEA7QJHmF45_u-kCdeeVWIZEruPKuix?usp=sharing

**Comment by jfinnerty13** [comment]
And ticket created
