### ISSUE TITLE
Troubleshoot BigQuery for completed reviews in a quarter

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#81730]
## User Story
As a Governance team member, I want to fix the bug in Domo so that the correct metrics can be communicated to OCTO.

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
The Quarterly Highlights section of the  Staging Review Dashboard in Domo is not currently displaying the correct count of Staging Reviews completed for CY24Q1. The card displays 3, however there should be 11 (see below).
<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0eb801632c861fc749cfa93d8291a5682277a109/image.png" alt="image.png" />

### Staging Review completed tickets for CY24Q1

- #78171
- #77145
- #76981
- ~~#76319~~ This "completed" ticket was created in error. There has not been a Staging Review for this work.
- #76050
- #75244
- #74007
- #73699
- #73603
- #79245
- #78970

Note: Ticket #74086 should not count towards this total since it is a DST SR, however it also was completed in CY24Q1.

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] The Staging Review Dashboard in Domo displays the correct number of completed Staging Reviews from CY24Q1

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman there is an issue with the BQ table missing recent data. I have filed an issue with support.

**Comment by shiragoodman** [comment]
thank you @it-harrison ! Can you link the issue you filed here? I am moving this to In Progress.

**Comment by shiragoodman** [comment]
Also I sized it as a 1. Assuming that once the BQ table is fixed, this will resolve itself. If not, please lmk.

**Comment by it-harrison** [comment]
slack support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1714160849153819

**Comment by it-harrison** [comment]
The current Big Query table has been added to confluence: https://vfs.atlassian.net/wiki/spaces/PPST/pages/3128426542/BigQuery+table+query

**Comment by shiragoodman** [comment]
@it-harrison please be sure to check the SR dashboard after 2pm ET today to validate that the data has been updated correctly. ty!

**Comment by shiragoodman** [comment]
This ticket will move into the next sprint as the BigQuery issues are not yet resolved. We are continuing to work with Analytics and Insights. Slack thread linked above has recent updates.

**Comment by it-harrison** [comment]
Johnny with Analytics resolved the Biq Query issues
