### ISSUE TITLE
[Backend] Establish Connectivity with DMC Test Environment

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#8174]
## User Story or Problem Statement
As a backend engineer, I need to establish connectivity with the DMC so that vets-api and the DMC's APIs can communicate with one another.

## Goal
That communication is established and viable between the DMC and vets-api.

## Tasks
- [x] Work with DMC team and VFS DevOps to establish connectivity between DMC and vets-api.
- [ ] Setup fwdproxy to DMC API

## Acceptance Criteria
- [x] Connectivity is established between DMC and vets-api

**Comment by leahkeeler** [comment]
## Story 
As a BE deb I need to be able to connect to API endpoint 

##tasks
Connect to endpoint
Get API key

**Comment by camerontesterman** [comment]
This is blocked until a forward proxy is setup by DevOps team to establish connectivity.

**Comment by camerontesterman** [comment]
@lihanli is working with devops team to setup fwdproxy.

**Comment by lihanli** [comment]
@camerontesterman @leahkeeler devops says that because the DMC API uses an irregular port setting up the forward proxy could take a long time
