### ISSUE TITLE
Content review from Authenticated Experience Profile team

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#81748]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

## About your team

- **Team name**: Authenticated Experience Profile
- **OCTO product owner:** Chante Lantos-Swett
- **Product name:** VA.gov Profile
- **Product manager:**  Travis Cahill
- **Slack channel:** #accoutexp-authexp
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

We're trying to improve clarity and consistency in the VA.gov profile in two areas:

1. We have a message across editable sections of the profile (direct deposit, contact information, personal information) that we display if an API response is taking a long time to respond.  Instead of an endless spinner, we're currently using a couple variations of a message in a format that's not part of the design system. We're moving to a design system component (slim alert, info state), and would like to come up with a message we can use across all sections, and that works when a person is updating OR removing information.  My proposed message is 

> We’re in the process of saving your changes. You’ll see the update in your profile soon.

2. Laura W. is aware of this one: we recently learned that if a person provides bank account information via a benefit application form, and it is different from what is in their VA.gov profile, the bank account info will be overridden in their VA.gov profile with the bank information they provided previously when the application is approved.  There are 2 things we'd like reviewed as part of this work, both of which are indicated with a comment in Figma on [this page](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=1158-6054&mode=design&t=rj4wuzrinyfs8enb-11).

 - An alert to tell people that this may happen, and what they can do
 - Some intro text at the top of the page for clarity about which benefits this direct deposit page is for, and better alignment with what the mobile app is doing.

## Collaboration timeframe

ASAP because the account override situation is happening today and not great.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
These are small updates to products that are already launched

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Supporting artifact <name>](https://va.gov) `placeholder link`

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA operations
- [ ] Initial Review - @coforma-terry and @strelichl 
```

```[tasklist]
### CAIA a11y tasks
```

```[tasklist]
### CAIA content tasks
```

```[tasklist]
### CAIA IA tasks
```

**Comment by andaleliz** [comment]
Adding some resolutions that came out of the meetings I've attended:
1. "We’re saving your changes. Stay on this page." is the language we'll use for the first item
2. The "potential DD override" problem needs some more tweaking; Liz and Laura will continue w that async.
3. We landed on "saving" for the processing button label in profile, but talked about that the design system allows for flexibility on the button label and won't be that prescriptive.
