### ISSUE TITLE
[bug][CST] Documents filed sorting issue

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#81756]
## Background Context
@jerekshoe found while on user 23 that the documents filed section did not appear to sort the tracked items/ supporting documents  by date correctly. After investigating we found that this was because there were tracked items that had multiple documents, and these documents had varying dates. (It is possible for a user to upload multiple documents to a given tracked item at different dates - this was not a scenario that we had accounted for in our original design/implementation).

<img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--646e060c4c07000365c1ab4c5b0ee6783ad4a8cd/Screenshot%202024-04-26%20at%204.11.18%E2%80%AFPM.png" alt="Screenshot 2024-04-26 at 4.11.18 PM.png" />

### Bug

You can reproduce this bug by going into Staging user 23 https://staging.va.gov/track-claims/your-claims/600494815/files

**Solution:**
We can update the logic in DocumentsFiled.jsx so that we sort the data so that if a given tracked item has documents, we sort on the first document date.

## Out of scope
- May need to rethink design here to account for the above scenario

## Tasks
- [ ] Update that date of the tracked item that is set in DocumentsFiled.jsx

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Documents Filed are ordered by the most recent tracked item/tracked item document/supporting document

**Comment by pmclaren19** [comment]
verified changes on user 23 in staging and looks good!
