### ISSUE TITLE
Identify Source of Domo Data Discrepancy for Pension Team

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#81752]
### Description
This ticket is to account for the work to identify the discrepancy in account between the vets-api database and Domo for the _Form_ submissions for the Pensions 527 form. We've validated that the numbers within GA and BigQuery are matching, and as expected. We need to determine what is happening to the submission counts within Domo that is causing the mismatch.

**Relevant Slack Threads:**
- https://dsva.slack.com/archives/C01S78V4AUA/p1712935494857429
- https://dsva.slack.com/archives/C01S78V4AUA/p1711733802738939
- https://dsva.slack.com/archives/C1Q4294JJ/p1711731958171209

### Tasks

- [ ] Identify the source of issue within Domo that is causing the mismatch.
- [ ] Document findings in ticket.
- [ ] Report back to Matt Reily, and the Pension Team on our findings.
---

**Comment by johnny-jesensky-adhoc** [comment]
Has been handled via Office Hours and Slack -- marking as Done.
