### ISSUE TITLE
Heuristic evaluation of debt portal

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#81755]
**What details are necessary for understanding the specific work or request tracked by this issue?**
The heuristic evaluation workshop is an opportunity for the UX team to:

Collaborate creatively as a team
Learn about or refresh your knowledge of usability heuristics and practice design thinking
Become familiar with the debt portal and/or enhance present understanding
Think about possible usability improvements within current constraints

This will be a 2 part UX workshop

Part 1: Evaluator assignments and async completion of heuristic evaluations
Part 2: UX team workshop to talk about findings

### Tasks

**What work is necessary for this story to be completed?**

- [x] Individual heuristic evaluation assignments
- [ ] Complete individual heuristic assignments (3-4 heuristics per person)
- [ ] Final compilation, discussion, and action items (tickets to make changes)

### Acceptance Criteria

 **What will be created or happen as a result of this story?**

- [x] Create individual heuristic evaluation assignments
- [ ] Individual heuristic assignments completed (3-4 heuristics per person)
- [ ] Final compilation, discussion, and action items (tickets to make changes)

**Comment by denisecoveyduc** [comment]
As we move into planning for our next quarter I am wondering what the UX team is thinking about the benefits of this ticket at this point? I am thinking it may not be needed. @charlottecesana @mgleo @josephrlee cc: @Tom-Davis

**Comment by charlottecesana** [comment]
@denisecoveyduc I agree. We are past that point.

**Comment by charlottecesana** [comment]
@Tom-Davis please let me know if it is ok to close this ticket!

**Comment by Tom-Davis** [comment]
@charlottecesana yes, let's go ahead and close this (I will since I am here). Thank you!
