### ISSUE TITLE
[Backend] Create DMC Backend Service Scaffolding

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#8175]
## User Story or Problem Statement
As a backend developer, I need to provide a backend service for connecting with the DMC to extract relevant data to generate a "debt letter" for the veteran.

## Goal
Documentation that explains the DMC Backend Service code.

## Objectives or Key Results this is meant to further
The DMC backend service will allow for the creation of API endpoints that will allow users to get information related to debt letters when they are released.

## Tasks
- [ ] Create Service class
- [ ] Create Config class & Faraday connection
- [ ] Create Breakers initializer
- [ ] Create Response class
- [ ] Update `settings.yml`

## Acceptance Criteria
- [ ] DMC Service will be created

**Comment by jsev-io** [comment]
Credential added to credstash
