### ISSUE TITLE
Content for uploading Supporting Documents on 10-10EZR

### ISSUE THREAD

**Issue by katelyncai** [department-of-veterans-affairs/va.gov-team#81764]
# CAIA Content Child Ticket

## Issue description
On the 10-10EZR form, we are adding the option for Veterans to upload supporting documents or evidence relevant to any toxic exposures they made have. This helps VA to process Veterans' forms quickly, and helps Veterans get the health care I've earned by potentially moving them to a higher priority group.
<br>
<br>
- On 04/26/24, met with @aliyahblackmore during weekly 1010 team content sync to review. Aliyah advised to open request intake ticket
- cc @alexseelig 

## About your team

- **Team name**: 10-10 Health Enrollment Team
- **OCTO product owner:** Patrick Bateman
- **Product name:** 10-10EZR Health Benefits Information Update form
- **Product manager:**  Alex Seeling
- **Slack channel:** #1010-health-apps 
- **Dedicated content writer on your team (if you have one):** Aliyah Blackmore
- **Dedicated a11y specialist on your team (if you have one):** N/A

### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

We need to make some updates to the online form to align with the new paper form and program updates.

### What's the nature of your initiative and desired outcomes?

We need to add the ability to upload Supporting Documents online to align with the 10-10EZR paper form and to streamline the process of submitting TERA data online.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [x] Yes
- [ ] No
- [] I’m not sure
- This effort relates to increased health care benefit access for toxic exposed Veterans under the PACT Act.

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

- The 10-10 Health Apps team released an MVP version of the new TERA (toxic exposure risk activity) questions added to the 10-10EZR form to 100% of users in mid-April 2024. Supporting Documentation is a post-MVP enhancement to add next. Currently, this effort is in the initial discovery/wireframing phase. We will alert our CAIA partners when designs are ready for content.

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.

- [Figma discovery and designs for content review; currently WIP](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=2593%3A33986&mode=design&t=iGQnTRSrbtYuOhLS-1) 

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`. We’ll reply within 24 hours to acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.

- [ ] Review the remaining next steps in the **VFS team tasks** section here.

## Tasks

<br>

```[tasklist]
### VFS team tasks
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well.<br> [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work. <br> [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team. <br> [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next. <br> [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).
```

```[tasklist]
### CAIA operations
- [ ] Initial Review - @coforma-terry and @strelichl 
```

```[tasklist]
### CAIA a11y tasks
```

```[tasklist]
### CAIA content tasks
```

```[tasklist]
### CAIA IA tasks
```

**Comment by aliyahblackmore** [comment]
**Just cross posting this link:** 

Hieu shared last week that I should share any content feedback/updates in this Figma section
https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=3049-66842&t=XNH5NhYCNByI8pUw-0

**Comment by aliyahblackmore** [comment]
**Cross posting updates here:** 
I wrapped up my content feedback/adjustments on the Figma designs. 
- The content adjustments are aligned with the information the product team shared in the Figma. And the largest change here is moving "What you were exposed to, when/where/type of activity..." out of the bulleted list and pulling those details into a section that describes them as types of information that may be in a supporting document. Again, that's because they aren't document types, but a document may have those types of details in them.
- also tracked an adjustment on the [form intro page](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=3050-71775&t=aiG9zS5esdSiqBhb-4). And I'm jumping in Drupal right now to adjust the static page (it'll mostly match what's in the upload screen).
- And I flagged for Katelyn that the PDF version of the form doesn't mention the other supporting documents, only that they can submit a written statement. Their team is aware and confirmed that users who use the PDF can also submit any of the other supporting documents. And just flagging here that as long as the PO and stakeholders are aware that the PDF and online form don't have the same list of supporting documents, that's okay! cc: @alexseelig. 


I'm sharing the static page updates with SME tomorrow.

**cc** @IMHieuVo @katelyncai @strelichl

**Comment by aliyahblackmore** [comment]
I just sent the static page updates to HEC SMEs

**Comment by aliyahblackmore** [comment]
Hi folks @katelyncai @IMHieuVo @alexseelig

**Closing the loop here with updates:**

- Supporting document updates are live in the form and the VA.gov page updates are also live! 
- I shared a link to the live page with HEC SMEs.
- Re: the saved and in-progress alert and user expectation - Hieu shared in our content sync (6/21) that the "Continue to form" button drops users wherever they left off in their last session (i.e. that could after any new questions). The product team/engineers previously confirmed in the 1010EZ TERA work  that the form functionality was that users would be dropped at the start of the form  - that way they're seeing any new questions or updates. The EZR updates are meant to match the EZ.  Hieu will circle back on this!

**Comment by aliyahblackmore** [comment]
@strelichl 

We are okay to close this!
