### ISSUE TITLE
Identity Slackbot Security Revisions

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#81762]
## Description
In order to improve the information security of the data passed through the identity-slackbot, several changes should be made. 

## Tasks
- [x] Update Argo production deploy to include new identity support team & issue ticket repository environmental variables
```env
PRODUCT_SUPPORT_TEAM=jimcconnelly,kingbmike
ENGINEER_SUPPORT_TEAM=joeniquette
ISSUE_TICKET_REPO=identity-slackbot
```
- [x] The GitHub repository to host issue tickets should be switched to `va.gov-team-sensitive`
  - [x] install identity-slackbot app on `va.gov-team-sensitive`
  - [x] uninstall identity-slackbot app on `va.gov-team`
  - [x] move relevant Github templates from `va.gov-team` to `va.gov-team-sensitive`
- [x] create & document human review process of all incoming tickets for PII with remediation steps
  - [x] [engineering issue intake form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Support%20Process/engineer-support-process.md) updated with PII remediation steps
  - [x] [product issue intake form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Support%20Process/Product%20Support%20Process.md) updated with PII remediation steps 
- [x] update "Data pull" issue ticket to use default posting behavior - Github ticket
  - [x] confirm Slackbot posts only the following data to Slack on issue creation
      * slack user name
      * issue type
      * link to github issue

**Comment by bramleyjl** [comment]
I have [re-opened the original issue ticket](https://github.com/department-of-veterans-affairs/github-user-requests/issues/20511#issuecomment-2083536855) to have the slackbot installed on `va.gov-team` to request that it be uninstalled from there and installed on `va.gov-team-sensitive` instead.
