### ISSUE TITLE
[DESIGN] Discovery on latest MHV notifications work

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81765]
## Background
We believe we're up to speed with the exploration MHV has done so far on notifications (hub pattern / link to), but we need to make sure to sync with them on their latest as we confirm our own patterns, namely around the component that will be used to link to the list of notifications. 

We think this [older Figma discovery around linking to/calling out notifications](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=0-6758&mode=design&t=ES1om3ShSV65q1iW-0) is still the latest.

## Tasks
- [ ] Sync with MHV designers & MyVA (Liz) & Misty/Lauren to determine the latest on "review/manage all notifications" patterns they've explored and any other relevant info
- [ ] Document the latest in this ticket and anywhere else needed (Figma, Slack, etc.)

## AC
- [ ] We have a clear understanding of where MHV is at with notifications
- [ ] We have documented any new findings where needed

**Comment by cgednalske** [comment]
## Discovery findings so far: 
(I'm waiting to hear back from an MHV designer to confirm. Will close out the ticket if I get that confirmation. If not, I'll add the a new comment with updated info.)

### MHV
The latest exploration around surfacing items/notifications remains the same ([Figma file](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=0-6758&mode=design&t=oDESmvt90s0FtLja-0)). This exploration can continue to give us ideas for how we might lead Veterans to their notifications, or create a more omni-present indicator for the notifications hub. 
Link to file


### MyVA
The MyVA team recently completed research around surfacing items ([findings for dot indicator/slim alert study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/research/2024-03%20Dot%20Indicator%20and%20Slim%20Alert%20Usability%20Study/Research%20Findings%20for%202024-03%20Dot%20Indicator%20and%20Slim%20Alert%20Research%20Study.md)). Findings point towards using the badge component to indicate to Veterans there are new items to view. This component will come in handy if we want to callout that there are NEW notifications to review, but we'll need to determine if this will work with our notifications pattern overall and provide value for the pilot. 
<img width="455" alt="Screenshot 2024-05-03 at 1 02 00 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/9d4bed68-4f21-4b0d-931c-b48571c458fd">


**Another item of note:** Findings also had a callout around looking into an global component of some sort that could surface the fact that there are items that need to be viewed and could be omni-present through the site.

> **Recommendation 3:** notifications that matter most for Veterans should be elevated more than just these methods - something high-level (top of page, alert banners, navigation, etc.) that is displayed immediately to users when they've been authenticated. This could be a persistent presence for users that lives in top-level navigation, appearing on all pages beyond just My VA. This would present a set of challenges for implementation, but this research study has shown that the notification types tested were not what users were saying they noticed first.
> 
> _See Finding 3: The majority of participants cited the next appointment card in the Health Care section of My VA as the first thing that stands out to them, not the dot indicator nor the badge indicator (8 of 15 participants, of 11 actually assessing them)._

This also points to a card of some sort possibly being a good direction for us, as we want to make sure that the notifications hub/list is easily discoverable by Veterans.


**There has not been any more exploration from either team around a notifications center, list, or hub.**

**Comment by benbrasso-agile6** [comment]
Move to closed?

**Comment by cgednalske** [comment]
Ya, let's close this. 95% sure this is done. There might be another final confirmation that comes through, but I don't think we need to wait for that.
