### ISSUE TITLE
[Design] Create wireframes for Appointment Notifications card statuses

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81768]
## Background
We need to solidify the card UI we want to move forward with and test for the Appointments Notification list page (currently called the secondary card). The featured card is confirmed, but the secondary card is not and will likely be a smaller version of the featured card, which uses the DS card component). 

[Card UI explored so far](https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-card-collection-%7C-Check-in?type=design&node-id=182%3A3268&mode=design&t=aacAvqGTwYJFieU2-1):
  - **Confirmed:** Featured card
    - Featured task card is confirmed and tested. 
    - Uses the DS card component
    - [Featured card was added to the MHV Figma Library](https://www.figma.com/file/ktX3at2KixnYf2G6MoBSuC/MHV---Unified-Appointments-Library?type=design&node-id=482%3A1417&mode=design&t=oIgVaSQoPsgLRATq-1)
  - **Still needed:** 2 versions of the secondary cards 
    - 1 for actions needed, and 1 for completed actions or updates
    - These are the smaller cards on the notification page 

## Tasks
 - [x] Explore different UI options for notification cards (action and non-action)
 - [x] Review options with CC team
 - [x] Decide on a direction
 - [x] Update in Figma files

## A/C
  - [x] UI direction determined for secondary notification cards (action and non-action)
  - [x] Figma updated

**Comment by cgednalske** [comment]
The following is where we've landed with the card UI and logic to test out during research:
[Latest UI for notification cards](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=663%3A55700&t=ooeaqPRQYTLw5R0y-1)
[Latest logic for notification cards](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=809%3A49012&t=ooeaqPRQYTLw5R0y-1)

**Note:** We will update the filter/sort system based on Ciera's filter work in #82659, along with any content changes as we work through content with Laura.
