### ISSUE TITLE
[Design] Create wireframes for Appointment Notifications card statuses

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81769]
## Tasks

- [ ] Create wireframes for Appointment Notifications card statuses

## AC

- [ ] Review with MHV folks
- [ ] Review and addressed feedback from CC team
