### ISSUE TITLE
Content review from Cartography team 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#81779]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

## About your team

- **Team name**: Cartography team 
- **OCTO product owner:** Patrick Bateman 
- **Product name:** MHV on VA.gov 
- **Product manager:**  Wes Rowe 
- **Slack channel:** mhv-on-vagov-cartography-team

### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What details are necessary for understanding the specific work or request tracked by this issue?

As part of the MHV to VA.gov migration effort, we want to provide important information to Veterans on the MHV to VA.gov landig page. 

For the integration, we want to:

- make the transition of MHV to [VA.gov](http://va.gov/) clear to the Veteran on the MHV to VA.gov landing page 
- make it clear to the Veteran that they can still go back to the MHV national portal experience and remain there to get all their tools if they choose, that has not changed yet
- help the user understand what is on [VA.gov](http://va.gov/) today as a "try me" and what is coming soon but not currently available on [VA.gov](http://va.gov/) and you will be directed back to MHV classic or MYVAHealth
- help a user understand what the future, integrated experience will be, including OH
- get users excited and interested in all the MHV things they can do on [VA.gov](http://va.gov/) now. 
- Continuing to drive them to the Phase 1 experiences to give us feedback 

User story: As a Veteran who is visiting the mhv on va.gov landing page for the first/second time, I want to know what's new on mhv on VAgov and why without having to seek out this information, so that I am inspired to trust the VA with my health.

[Potential designs (Figma here)](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=1674%3A19983&mode=design&t=C3w6vy2MYQO1dALS-1)

![V1 current messaging - desktop](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/d81730b4-f14d-4b5c-8666-ff6115cfa1d7)

![V1 current messaging - desktop](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/3d718f66-98aa-4c2a-a376-3554f07110f0)

---
## Tasks
```[tasklist]
- [ ] _What work is necessary for this ticket to be completed? Examples:_
- [ ] Assess stakeholder request
- [ ] Draft content
- [ ] Review
- [ ] Share with stakeholder
- [x] Update page
- [ ] Copyedit
- [ ] Publish
- [ ] Alert stakeholder
```

## Acceptance Criteria
```[tasklist]
- [ ] _What will be created or happen as a result of this story? Examples:_
- [ ] Updated content is live on the site
```

## How to configure this issue
```[tasklist]
- [x] **Attach to an Epic** (what body of work is this a part of?)
- [x] **Label with Originator/Team** (product team or stakeholder requesting support)
- [x] **Labeled with Open Date**
- [x] **Labeled with Estimate** (level of effort expected for this ticket)
- [x] **Assignee name added to each task they will complete (if known)**
- [x] **Open date and target date (if known) updated**
```

## Ticket Tasks
_Complete these steps to configure this ticket._

```[tasklist]
- [x] Ensure ticket is linked to Epic
- [x] Add Originator/Team name
- [x] Add Opened Date
- [x] Add Estimate
- [x] Add label(s) for discipline(s) involved in work
```

**Comment by jonathanjnelson** [comment]
[Updated designs ](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=1844%3A35667&mode=design&t=2pMUfgoT64TajbJl-1)

**Comment by wesrowe** [comment]
Launched! Thanks and this can close.
