### ISSUE TITLE
Convert "Manage your VA and other information online" section to link teasers

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8177]
We are implementing analytics for Find VA Forms work, and hit a snag with the initial set-up (captured in #7691 ). 

From an investigation that Nick and Beth took, this is what was found:
The Helpful online tools section is currently WYSIWYG content.
If we convert it to a content model in Drupal, it will inherit analytics work that is being implemented elsewhere.

## Goal
 - The "Manage your VA and other information online" sections on the Find VA forms page have analytics, able to track
---
## Tasks
- [x] Leave the heading and the paragraph below it as a WYSIWYG
- [x] Convert the links to "list of link teasers" content model in Drupal
- [ ] Confirm the DataLayer Requirements are met

Note: When this occurs, it will inherit the analytics work that Nick is implementing in #7890 
If this does not occur, it will be difficult, if not impossible, to attach selectors to the WYSIWYG content  

## Acceptance Criteria
- [ ] Links in this section are converted to the list of link teasers content model in Drupal
- [ ] When converted, we can test that they are being tracked via analytics work from #7890
---
Note for Steph:  when this is completed, alert Jon Wehausen so that this section can be incorporated into the Find Forms dashboard

**Comment by jenniferlee-dsva** [comment]
^ I have updated the component form factor change in Drupal, per 8135 reference.

**Comment by RLHecht** [comment]
@stephorkandatx  can this be closed? This is part of the Find a VA Form we published last week I think.
