### ISSUE TITLE
Copy of Service level coding

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81774]
## Tasks

- [ ] Create service level function in existing file `vaos/v2/mobile_facility_service` to get referrals based on patient ICN. Should be named something like `get_referrals_by_patient_icn`, passing ICN along and retrieving whatever is in MFS (end data actually CDW)
- [ ] Create controller endpoint, POSSIBLY ( @simiadebowale ) in `vaos/v2/appointments_controller` (waiting for confirmation)
- [ ] Write rspec tests to cover new function

## AC

- [ ] Passing patient ICN to this endpoint should retrieve the correct referrals data expected
- [ ] Handling any errors
- [ ] Massaging data to fit any front end requirements
- [ ] Make sure new tests pass

**Comment by benbrasso-agile6** [comment]
gonna close this until we need it
