### ISSUE TITLE
Document business rules around calculating drive time, etc. 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81776]
## Tasks

- [ ] Based on meeting with Access Standards, document business rules around calculating drive time, etc., in Git repo 

## AC

- [ ] Page in Git hub created
- [ ] Reviewed with engineers
