### ISSUE TITLE
Generate & Deliver Monthly Domo Report for April 2024

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#81787]
### Description
We deliver these monthly reports to an audience of OCTO each month on the 8th. This ticket is to track the completion, QA check, and delivery of these reports.

> **What:**
> VEO, DMC & OMB stakeholders receive the Monthly VA.gov Summary.
> 
> **When:**
> Due by midday EST on the 8th of the month.
> 
> **Who:**
> Send via Slack to @Chris Johnston @Erica Robbins [GovCIO_VetsPS] @Lacey @Julia Badillo on the #vfs-analytics channel (see example)
> 

### Tasks

- [x] Check data (Data is up to date as of the last day of the previous month)
- [x] Check content
- [x] Export Dashboards as PowerPoint
- [x] Review data & content (Data is up to date as of the last day of the previous month, Labels show on charts, etc.
Redo title slides and section titles

- [x] Change dashboard titles to, "VA.gov Monthly Metrics – month year"

- [x] Go through slides and move section titles to appear directly above appropriate section (Domo will often put them at bottom of last chart of previous section in PowerPoint export)

- [x] Rename the file

- [x] Send the file to the appropriate stakeholders

### Acceptance Criteria
- [x] Report has been downloaded to a PPT format
- [x] Report has been QA'd, using the guidance provided in [this Confluence page](https://vfs.atlassian.net/wiki/spaces/AT/pages/2001928499/Updating+Recurring+Reports)
- [x] Report has been sent to Chris, Erica Robbins, Lacey, and Julia on the #vfs-analytics channel

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA -- I created this ticket for the April monthly report. Please pick this up once we are in May if you have available bandwidth.

**Comment by johnny-jesensky-adhoc** [comment]
Injecting this into the current sprint, as it needs to be delivered by May 8.

FYI @ChristineYoungZA

**Comment by johnny-jesensky-adhoc** [comment]
Report has been QC'ed, and delivered to the relevant stakeholders in the #vfs-analytics channel -- moving this to _Done_.

- https://dsva.slack.com/archives/C1Q4294JJ/p1715013091265579

FYI @ChristineYoungZA
