### ISSUE TITLE
Make Nutrition, Podiatry, Caregiver support fields visible to front end

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8178]
## User Story 
As a Veteran, I want to know which facilities offer Nutrition and Podiatry services  so I can select the best location to visit. 

This data originates from CDW and have been added to Facilities API and is already being passed through by backend

Example: 

```
{
    "data": {
        "id": "vha_675GA",
        "type": "va_facilities",
        "attributes": {
            "name": "Viera VA Clinic",
            "facility_type": "va_health_facility",
            "classification": "Health Care Center (HCC)",
            "website": "https://www.orlando.va.gov/locations/Viera.asp",
            "lat": 28.255238570000074,
            "long": -80.739071129999957,
            "address": {
                "mailing": {},
                "physical": {
                    "zip": "32940-8007",
                    "city": "Viera",
                    "state": "FL",
                    "address_1": "2900 Veterans Way",
                    "address_2": null,
                    "address_3": null
                }
            },
            "phone": {
                "fax": "321-637-3515",
                "main": "321-637-3788",
                "pharmacy": "877-646-4550",
                "after_hours": "877-741-3400",
                "patient_advocate": "321-637-3534",
                "mental_health_clinic": "321-637-3788",
                "enrollment_coordinator": "321-637-3527"
            },
            "hours": {
                "monday": "730AM-430PM",
                "tuesday": "730AM-430PM",
                "wednesday": "730AM-430PM",
                "thursday": "730AM-430PM",
                "friday": "730AM-430PM",
                "saturday": "Closed",
                "sunday": "Closed"
            },
            "services": {
                "other": [],
                "health": [
                    "Audiology",
                    "Cardiology",
                    "DentalServices",
                    "Dermatology",
                    "Gastroenterology",
                    "MentalHealthCare",
                    "Nutrition",
                    "Ophthalmology",
                    "Optometry",
                    "Orthopedics",
                    "Podiatry",
                    "PrimaryCare",
                    "SpecialtyCare",
                    "Urology"
                ],
                "last_updated": "2020-04-13"
            },
            "satisfaction": {
                "health": {
                    "primary_care_urgent": 0.74000000953674316,
                    "primary_care_routine": 0.82999998331069946
                },
                "effective_date": "2019-06-20"
            },
            "wait_times": {
                "health": [
                    {
                        "service": "Audiology",
                        "new": 1.817073,
                        "established": 1.100719
                    },
                    {
                        "service": "Cardiology",
                        "new": 18.0,
                        "established": 6.644067
                    },
                    {
                        "service": "Dermatology",
                        "new": 0.454545,
                        "established": 0.0
                    },
                    {
                        "service": "Gastroenterology",
                        "new": 27.32,
                        "established": 3.533333
                    },
                    {
                        "service": "MentalHealthCare",
                        "new": 10.439024,
                        "established": 2.362156
                    },
                    {
                        "service": "Ophthalmology",
                        "new": 24.5,
                        "established": 4.0
                    },
                    {
                        "service": "Optometry",
                        "new": 63.3,
                        "established": 10.405405
                    },
                    {
                        "service": "Orthopedics",
                        "new": 22.5,
                        "established": 5.029411
                    },
                    {
                        "service": "PrimaryCare",
                        "new": 9.96875,
                        "established": 0.600461
                    },
                    {
                        "service": "SpecialtyCare",
                        "new": 16.32771,
                        "established": 4.220381
                    },
                    {
                        "service": "Urology",
                        "new": 82.0,
                        "established": 9.88
                    }
                ],
                "effective_date": "2020-04-13"
            },
            "mobile": false,
            "active_status": "A",
            "operating_status": {
                "code": "NORMAL"
            },
            "visn": "8"
        }
    }
}
```

## Goal
Podiatry and Nutrition services are displayed on the relevant Facility Detail pages. 

## Objectives or Key Results this is meant to further
- Objective 2: Deliver meaningful facility information 

---
## Tasks
- [ ] Make Podiatry visible as a service to Facility Locator front end
- [ ] Make Nutrition visible as a service to Facility Locator front end
- [ ] Make Caregiver support visible as a service to Facility Locator front end

## Acceptance Criteria

**Podiatry**
- [ ] When Veteran selects VA health as facility type in a Facility Locator search, Podiatry is available in service type drop down.  
- [ ] When Veteran selects VA health as facility type **and** Podiatry as service type, the results list contains facilities which offer Podiatry. 
- [ ] When Veteran selects VA health as facility type **and** Podiatry as service type **and** clicks on a location in the search results list, Podiatry is listed displayed as a service on the facility's detail page. 

**Nutrition**
- [ ] When Veteran selects VA health as facility type in a Facility Locator search, Nutrition is available in service type drop down.  
- [ ] When Veteran selects VA health as facility type **and** Nutrition as service type, the results list contains facilities which offer Nutrition. 
- [ ] When Veteran selects VA health as facility type **and** Nutrition as service type **and** clicks on a location in the search results list, Nutrition is listed displayed as a service on the facility's detail page. 

**Caregiver support**
- [ ] When Veteran selects VA health as facility type in a Facility Locator search, Caregiver support is available in service type drop down.  
- [ ] When Veteran selects VA health as facility type **and** Caregiver support as service type, the results list contains facilities which offer Podiatry. 
- [ ] When Veteran selects VA health as facility type **and** Caregiver support as service type **and** clicks on a location in the search results list, Podiatry is listed displayed as a service on the facility's detail page. 

Shawnee Petrosky  2 hours ago
^Example

Shawnee Petrosky  2 hours ago
We do not have satisfaction scores for podiatry/nutrition at the moment. We are also not exposing wait times for nutrition/podiatry
(edited)

Dave Conlon  2 hours ago
Is that from PROD data/endpoint? (edited) 

Peter Branam-Lefkove  2 hours ago
It's the same in prod and sandbox

Dave Mazik:spiral_calendar_pad:  2 hours ago
@Shawnee Petrosky We should probably have documented this in release notes (as well as the oper status changes).  Thanks @Andrew F for reminding me of this.
:+1:
1

Dave Conlon  1 hour ago
@Michelle Middaugh ^^ These services are not populating Facility Locator.
See: https://www.va.gov/find-locations/facility/vha_675GA
VA.govVA.gov
Find VA Locations
Find a VA medical center, clinic, hospital, national cemetery, or VA regional office near you. You can search by city, state, postal code, or service. You'll get wait times and directions.

Michelle Middaugh  < 1 minute ago
)

**Comment by mmiddaugh** [comment]
Maybe solved by switching over to Lighthouse

**Comment by mmiddaugh** [comment]
visible on staging - thank you!
