### ISSUE TITLE
[Design] Replace appt detail card components in Production Figma file

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81795]
## Tasks
- [ ] Replace appt detail card components in [Production](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=2%3A1305&mode=design&t=BUXnOZ91s3TVCUBE-1) with the updated MHV Library appt card component
- [ ] Make sure content in existing appt detail pages do not change when the component is replaced 

### Who needs to review? Remove rows that aren't needed for this work.   
- [ ] UX team

## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/81795?planning-poker) with Zenhub @zach-park

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske  Production Figma file is ready for validation.

**Comment by benbrasso-agile6** [comment]
@zach-park I don't understand what was changed for this ticket. What was changed?

**Comment by zach-park** [comment]
@benbrasso-agile6 I replaced all cards that weren't using the MHV Component Library.

**Comment by benbrasso-agile6** [comment]
Alright, let me look through this a bit

**Comment by benbrasso-agile6** [comment]
In hindsight, I think we moved out the wrong ticket, but that's alright.

**Comment by zach-park** [comment]
Yes, I think we create probably and close this ticket then create another one for it next sprint.
