### ISSUE TITLE
Research plan for recent locations analytics

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#81790]
## Task Description
Create a research plan for collecting analytics around the "Sort by recent locations" feature release. 

## Notes and References
-

## Acceptance Criteria
- [ ] Research plan is in GH in[ this folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/research)

## Deliverables
- [Recent locations analytics plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2024-05-Recent-locations-analytics.md)

---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by ldelacosta** [comment]
Removed the blocker [#81136](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/81136). cc: @melissa-lefevre

**Comment by melissa-lefevre** [comment]
Jeff and I met and discussed next steps. We will need to set up a meeting with Corey to go over the metrics we want to track. Meanwhile he is looking into data dog to see if we can find the current time on page so that we have data to compare.

**Comment by melissa-lefevre** [comment]
I made a [spike ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85722)for these metrics.  We can go over them at the review on Wednesday.
