### ISSUE TITLE
Update 'Design System Components' page on Platform Website

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#81800]
### Description
As part of our work on the GA4 migration, we've been identifying pages on the Platform Website that need updating. This page on [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/design-system-components), was identified as one that was out of date.

Jami Gibbs of the DST Team when ahead and made substantial edits to the page -- outlined in this [Google Doc](https://docs.google.com/document/d/1rnM6J6z-CHZDH7URpw-ORHnibvqPbn3MjdpgD0Tlrs8/edit). This ticket is use these edits to update the content on the Platform Website.

### Tasks

- [x] Review edits to Design System Components, as written by Jami Gibbs [here](https://docs.google.com/document/d/1rnM6J6z-CHZDH7URpw-ORHnibvqPbn3MjdpgD0Tlrs8/edit)
- [x] Edit content on Platform Website -- content should be updated [here](https://vfs.atlassian.net/wiki/spaces/APM/pages/1840808040/Design+System+Components).
- [x] Ensure there are no launch blocking issues -- reference this page to ensure Platform Website quality standards are being met -- https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3101163521/LAUNCH+BLOCKING+ISSUES

---

### Acceptance Criteria

- [x] Content has been reviewed
- [x] Content has been updated on the Platform Website

**Comment by johnny-jesensky-adhoc** [comment]
Per stand-up -- we'll hold off on adding this to the Platform Website until we've validated it's the right level of information.

Johnny and @jestutt to discuss this in sync on 4/30.

**Comment by johnny-jesensky-adhoc** [comment]
Page has been updated, https://vfs.atlassian.net/wiki/spaces/APM/pages/1840808040/Design+System+Components -- waiting for updates to be published to the Platform Website. Will confirm once it has been pushed, and move this to _Done_.

FYI @ChristineYoungZA

**Comment by johnny-jesensky-adhoc** [comment]
Content has been published to Platform Website -- moving this to _Done_.

- https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/design-system-components

FYI @ChristineYoungZA
