### ISSUE TITLE
[FSR] Update unit tests post deprecation

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#81804]
## Description
There may be a few dangling unit tests that are tied to previous version of the form dangling still. Let's identify those for removal, and create a list of any areas we can improve our test coverage for other components/helpers that are out there. 

## Tasks
- [ ] Identify and remove unit tests that are no longer applicable. 
- [ ] Identify and ticket areas for improvement for unit test coverage.

## Acceptance criteria

- [ ] No unnecessary/out of date unit tests are hanging around anymore
- [ ] (optional) Tickets created for new testing opportunities

## Testing
- [ ] Yeah that's the idea

Testing procedure:\
Be sure to run all the unit tests!

`yarn test:unit --app-folder financial-status-report --log-level=error`

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
