### ISSUE TITLE
[FSR] Feature flag cleanup discovery

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#81813]
## Description
Just over 60 days ago we defaulted some FSR feature flags to true now they have been live for some time and the features are solid! In progress form deprecation is now 60 days from creation, so let's confirm we don't have any in progress forms with the following set to `false` before we start removing the functionality from the FE

[Ticket defaulting flags to true](https://github.com/department-of-veterans-affairs/vets-website/pull/28078)

### Feature flags for removal
- `combined_financial_status_report_enhancements` 
  - (most of the functionality is already gone, just need to do the final bit of cleanup)
- `financial_status_report_streamlined_waiver`
- `financial_status_report_streamlined_waiver_assets`

## Tasks
- [x] Confirm there are no in progress forms with any of the above set to `false` 
- [x] Create FE ticket to deprecate feature flag functionality 

## Acceptance criteria

- [x] Feature flags have been cleared so we can start dismantling old functionality 
- [x] Follow on tickets have been created (bug work, or FE deprecation) 

## Testing
- [x] N/A

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by maxx1128** [comment]
I've checked all of the 5655 In Progress Forms in the production (1789 total) and checked all their data for the above feature flags. I can confirm that there are none with any of the above feature flags set to `false`.

![Screen Shot 2024-06-14 at 11 05 45 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10790736/b2102770-e22a-4fde-8e18-a00e67b1a3f3)

I believe the next step is to create tickets to remove the flags on the front-end.

**Comment by maxx1128** [comment]
The follow-up tickets have been created as needed, so I'm marking this as closed.
