### ISSUE TITLE
[FSR] Deprecating confirmation email feature flag

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#81823]
## Description
While doing some FE cleanup we found some dangling unused references to `fsr_confirmation_email` feature flag. It looks like the functionality has been removed from the FE, so let's confirm it's no longer being used in the BE and let's remove the references from the FE and the flag entirely

[Platform feature toggles guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide). Can work backwards for removal 

## Tasks
- [ ] Confirm flag is no longer necessary and unused on BE
- [ ] (optional) Create ticket to remove unnecessary functionality from BE 

## Acceptance criteria

- [ ] `fsr_confirmation_email` functionality has been confirmed no longer necessary and removed

## Testing
- [ ] No BE or FE tests/functionality failing after removal

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by amponce** [comment]
After discussing with Derek, it appears that a new ticket needs to be created for the backend cleanup portion of the work. I’ll close this task and provide a link to the new ticket.
