### ISSUE TITLE
Put together analytics plan

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8182]
## Background
We would like to put together a plan for how we would like analytics to be set up. For example, how certain KPI's will be calculated, what will/will not be included in the data, and other similar factors

[Analytics Needs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/analytics/Analytics%20needs%20for%20profile%202.0.md) 

[KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account#kpis)

## Tasks
- [ ] Work with Joanne and Jon to determine how to combine data analytics from numerous sources into one dashboard.
- [ ] Create Analytics Plan

## Acceptance Criteria
- [ ] Analytics plan has been created
- [ ] Analytics plan has been reviewed with Samara

**Comment by Samara-Strauss** [comment]
Hey! [Here are my initial thoughts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/analytics/Analytics%20needs%20for%20profile%202.0.md). Let's discuss after you've had a chance to review the KPIs and formulate some thoughts on what we need.

**Comment by mshea0606** [comment]
@Samara-Strauss sounds good!

**Comment by joanneesteban** [comment]
Thanks for sharing! As we think about putting together a plan for a dashboard on Domo, would you mind sharing which Objective (OKR) your KPIs above are linked to?

**Comment by mshea0606** [comment]
@joanneesteban Yes, I will put that together and send it over to you.

**Comment by Samara-Strauss** [comment]
@mshea0606 something to keep in mind — we may have a bunch of different sets of KPIs/OKRs since there are different products in the profile. For example, KPIs for the profile overall will be different than the KPIs we have for the direct deposit feature (which shouldn't be changing from what they are now). We should make sure to get @joanneesteban and team clear documentation on overall profile KPIs as well as any KPIs that are tool-specific so we don't lose access to important metrics.

**Comment by Samara-Strauss** [comment]
@joanneesteban @jonwehausen question for you — I have some questions around what we'll show in Domo vs. Google Analytics given that we already have some dashboards for the profile that are already in great shape. Namely:

1. Are all dashboards being moved over to Domo? Or is some staying in the GA dashboards? Either way, how do we determine what goes where?
2. Would we leave some things like the [direct deposit dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p187673796/) and the [address validation dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/arWBC7_-SkK3WHQuJQHQoQ/a50123418w177519031p176188361/) in the GA interfaces, or is the expectation that we'd now show this stuff in Domo? For the record, those dashboards are great and I only have a couple small tweaks I need with either of them.

Are these questions you think you can answer here, or would it be helpful to have another 15 – 30 minute regroup? I'm happy to meet if that's the easiest way to discuss our strategy.

**Comment by mshea0606** [comment]
@Samara-Strauss Joanne and I were able to discuss the topics you mentioned this afternoon.

1. The goal is to eventually move GA dashboards over to DOMO but the Analytics team is still working on what that looks like. 

2. Our current dashboards will remain in GA but could eventually be built in DOMO if needed. (They would still be available in GA even if moved to DOMO). 

The plan is to put the additional dashboards we are making for profile 2.0 in GA with the option to move this over to DOMO in the future if desired. We can make the changes mentioned in your doc to the address validation and direct deposit dashboards and build other GA dashboards for the rest of the requested metrics.

**Comment by Samara-Strauss** [comment]
Awesome, thank you for letting me know! I don't think I have any other questions right now.

**Comment by mshea0606** [comment]
@Samara-Strauss ok great! Closing this.
