### ISSUE TITLE
Contact Center Review for [Benefits Non-Disability - Burial Benefits 21P-530EZ]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81826]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
VA Form 21P-530 (Application for Burial Benefits) enables eligible individuals to apply for compensation to help cover burial, funeral, and transportation costs. The online interview-style form was several versions behind the pdf form, so updates were made to remove depreciated fields, add new fields, improve user flow, and address significant accessibility issues. See [readme](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/README.md) for more info about the form and [initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/530-initiative-brief-2024-updates.md) for more info about the interview-style online form updates.

### Launch Date
- Canary Launch: April 19, 2024
- 25% launch to authenticated users: April 24, 2024
- 50 % launch to authenticated users: April 30, 2024
- 75% launch to authenticated users: May 2, 2024
- 100% launch to all users: Week of May 6, 2024

### Version Number
Version 1

### Product Guide
- [21P-530EZ Product Guide](https://docs.google.com/document/d/1GPNbnQpxTU2DBNLu6-5f2jdpT8Lb6MG0/edit?usp=sharing&ouid=116533835964476411407&rtpof=true&sd=true)
- Note that we are waiting for two additional screenshots to add to the guide, but there location and description is marked within the guide.

### Product Video
- none

### Product Video Transcript
- none

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by steele-lm** [comment]
cc @fiorella-io

**Comment by starlow00** [comment]
The draft looks good. Submitting to VEO for review.

**Comment by starlow00** [comment]
VEO accepts the guide as is. Please use the attached copy for future versions. Thank you!
[VA Form 21P-530EZ Burial Benefit Form Product Guide SRT 04302024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUcxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--378c1923ad48124d6ba5e67d80737680d6de3b86/VA%20Form%2021P-530EZ%20Burial%20Benefit%20Form%20Product%20Guide%20SRT%2004302024.docx)
