### ISSUE TITLE
Dataset Request -- (Mason Crane)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#81839]
### Description
This ticket is to track the work needed to grant Mason Crane access to a dataset within Domo -- using [this](https://va-gov.domo.com/datasources/1fcd5fbe-add0-4fb2-a387-e302919df2b0/details/settings?userId=558928891) as a reference point.

The requirements of the new dataset: 
1. Need all of the columns within the dataset, [BQ - VANotify_GA_Landing_Pages
](https://va-gov.domo.com/datasources/1fcd5fbe-add0-4fb2-a387-e302919df2b0/details/settings?userId=558928891).
2. Will need the following new columns added.
- Event Category
- Previous Page Path
- Page Views
3. Perhaps most importantly, Mason needs a self-service way to add and remove URLs as needed, which will likely be needed on the BigQuery side due to the way we traditionally restrict data flowing to Domo as a way to manage costs on both the BQ and Domo side. These URLs might extend beyond the root URL paths we see from most teams -- example provided:

> Then the added complexity is that I am looking for all information for the following URLs, and then in theory would need to add or remove URLs over time:
> So where the page is like = [va.gov/school-administrators/](http://va.gov/school-administrators/)
> or like = [va.gov/education/gi-bill/post-9-11/](http://va.gov/education/gi-bill/post-9-11/)
> or like = [va.gov/profile/military-information/](http://va.gov/profile/military-information/)
> or like = [va.gov/performance-dashboard/](http://va.gov/performance-dashboard/)
> eventually will need to add more to this
> 

### Tasks

- [x] Confirm requirements on dataset with Mason.
- [ ] Phil to help with either the creation of the dataset, and/or necessary BigQuery access for Mason to add/remove URLs.

---

### Acceptance Criteria

- [ ] New dataset has been created.
- [ ] Mason has access to dataset and ability to add/remove URLs.

**Comment by johnny-jesensky-adhoc** [comment]
Hey @MasonOddball  -- I chatted with @dorseypa1 on your ask this afternoon around your dataset request. To help streamline things a bit -- I created this Github ticket to map out your requirements as I understand them, and have a way to track the work done on your ask. After talking with Phil, and from the nature of your requirement of adding/removing URL paths on an ongoing basis, (that might evolve over time), we'll likely need to configure or grant you access on the BigQuery side. I'll leave it to Phil to find best next steps on this.

@Mason Crane -- let me know if any of the requirements are off. **Also, can you remind me the timing on this from your end?**

Phil is pretty heads down on some work in BigQuery for our GA4 migration this sprint, so his time is very valuable at the moment. It sounds we might be able to give you something to work off of w/o too much effort, but a sense of timing on your end will help.

**Comment by johnny-jesensky-adhoc** [comment]
Moving the assistance of this to Office Hours, and our normal support model. Closing.
