### ISSUE TITLE
[ENG] Create connection with EPS service

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81837]
## Tasks

- [ ] Reach out to Michael
- [ ] Create connection with EPS service

## AC 

- [ ] Connected with service

**Comment by benbrasso-agile6** [comment]
Not doing
