### ISSUE TITLE
Audit All Form Emails

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81848]
## Issue Description
_We recently discovered that the two emails that Chapter 31 (VRE) is generating contained an invalid link `tel:+1711`. We need to update it to `tel:711` as TTY services do not use a country code. The updates to the VRE emails have been made, but we need to audit our other forms to determine what emails they are sending and confirm the link is correct._

---
## Tasks
- [ ] Compile a list of emails sent by the following forms:
   - [ ] 686/674
   - [ ] PCPG/CH36
   - [ ] COE
   - [ ] Burial
- [ ] Determine if the telephone number link is valid (`tel:711` not `tel:+1711`)

## Acceptance Criteria
- [ ] Telephone link is functioning
---

**Comment by steele-lm** [comment]
Audit and updates were completed as part of the zero silent failure initative.
