### ISSUE TITLE
Review OCTO / PO role type view w/ suitable SMEs

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81844]
## Purpose
Let's show the OCTO / PO view to a few SMEs to get their take and learn what else might be useful to them

## Tasks
- [x] Identify suitable/available SME
- [x] Schedule initial chat w/ SME to convey purpose of artifact
- [x] Share with SME, allow them to discuss and/or complete async
- [x] Collect [feedback/notes](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3218112513/Feedback+Review+OCTO+PO+role+type+view+w+suitable+SMEs)
- [x] Repeat for 2-3 SMEs
- [x] Discuss learnings w/ SDT Team
- [x] make adjustments based on decisions

## Acceptance Criteria
- [x] Feedback from SMEs is recorded
- [x] Decisions made from SDT discussion
- [x] this view reflects learnings

**Comment by twoangstroms** [comment]
Carrying over to next sprint due to last-minute feedback and holiday

**Comment by twoangstroms** [comment]
Note that a good portion of the learnings resolve to content needed for a landing page, as will be addressed in an upcoming ticket. Adding links to these findings into that ticket body.
