### ISSUE TITLE
Create the distinct Role based views for the Insights Repository

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81843]
## Purpose
We want to create unique views that are tailored to each type of role that might utilize the **Insights repository.**

[Roles](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2968322421/Considering+Conf.+Databases+for+our+Big+Board+of+Insights#How-might-this-new-unified-view-be-used-by-different-personas%3F) identified:  
-OCTO / PO
-Platform Leadership
-Platform team member

## Tasks
- [x] Review [Insights Repository](https://vfs.atlassian.net/wiki/spaces/SDT/database/3120759313) and how to create views
- [x] Generate user stories for each role to better understand what datapoints are needed
- [x] Set up view for each of the 3 role types
- [x] adjust views to contain the data that would be most interesting to the given role type
- [x] also consider other data relationships that might be valuable to include and add

## Acceptance Criteria
- [x] 3 views exist, named by role
- [x] each view contains relevant data types and relationships
