### ISSUE TITLE
[BE] 10-10CG - Improvement: Reduce form timeout from 600

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#81842]
#### April 2024 
While investigating Invalid CSRF token issues on the EZ and CG forms with the Platform team, it was discovered that the CG form timeout threshold was set at 600, when it should be 120 for any app on vets-api.  See conversation below for context.

<details>

<Summary>Conversation with Rachal Cassity (Platform team)</Summary>
 
- This original conversation started with looking into the CSRF errors, which still persist as of 11/2024
 
>- **Rachal Cassity**
>     - @Heather Justice I noticed the form_10_10cg timeout was set to 600. This could be causing many issues. Timeouts should not exceed 120 in vets-api
>
>- **Heather Justice**
>     - oh interesting.. how long is that, like 10 minutes?
>
>- **Rachal Cassity**
>     - Yeah..
>```
>def create_submission_v2(payload)
>        with_monitoring do
>          res = do_post('v2/application/1010CG/submit', payload, config.settings.async_timeout)
>          raise RecordParseError if res.dig('record', 'hasErrors')
>
>          res
>        end
>      end
>```

</details>

#### January 2025
Due to some recent 504 responses we are getting from Mulesoft (~8 so far on 1/8), we want to return to looking at reducing the timeout from 600.  This may be causing duplicate submissions to Mulesoft, which is happening after the 504 responses and vets-api retries.
- Initial finding from Brandon
     - I do see logs matching those times where our sidekiq job retried submission after receiving a 504 response. I'll take a look at why that may be happening. Looks like we are getting a 504 response, but that that request does end up creating it in mulesoft is my guess, while vets-api thinks it failed and needs to retry. The retries are pretty quick early on (with an exponential backoff) so that's why they are right after each other. I'll keep looking to see what we can do to prevent this

## Tasks
- [ ] Confirm the value that is ideal for the timeout
- [ ] Update timeout value
- [ ] Perform backend testing to catch any issues
- [ ] Touchbase with PM prior to launch to prod
- [ ] Launch to production

## Acceptance Criteria
- 10-10CG form timeouts are updated to avoid long timeouts and duplicate submissions

**Comment by hdjustice** [comment]
during review of the timeout, a past ticket was found where we increased the timeout time.  More research is needed to confirm why we did this.

**Comment by coope93** [comment]
I originally pulled this as it looked like a fairly simple update, but I think we may want to do some further investigation as to why it was originally updated to ensure we don't have any regressions. Actually updating the value is pretty simple.

**Comment by hdjustice** [comment]
Thanks @coope93  Looking into this a bit more, it seems that this timeout was implemented as part of the Mulesoft integration, and I believe (from old slack convos) that it allows for calls to Mulesoft during retries to give time for a response, but capped at 10 minutes

- Slack convo with Patrick and Lihan - [7/15/2022](https://dsva.slack.com/archives/CMJ2V70UV/p1657894319338519) in #1010-health-apps channel

**Comment by hdjustice** [comment]
I think maybe we don't change this unless we or the platform team says it is causing an issue with something else.  We have had this in place for over a year and it doesn't seem to have any adverse affects.  
I originally created this ticket because I thought it might resolve or help with the CSRF errors, and was advised by platform group that 600 was alot.

**Comment by coope93** [comment]
@hdjustice I think that makes sense. My concern was in looking further into it there were some other repos that were going to need updated (Example that https://github.com/department-of-veterans-affairs/devops/pull/11922 was updated when it was set to 10 minutes), and I wanted to make sure we took the time to know what all is going on. Since this was set as a low priority I thought it made sense to hold up on it. I think waiting til we _really_ have nothing to do or are told by platform to update it makes the most sense 👍 .

**Comment by hdjustice** [comment]
Thanks @coope93 - closing the ticket

**Comment by hdjustice** [comment]
reopened due to some duplicate submissions that may be caused by the long timeout

**Comment by coope93** [comment]
So after more discovery, we do not want to change this timeout to 120. [slack thread with more context](https://dsva.slack.com/archives/C05Q6411HPF/p1736523062190569). The ALB timeout is currently 360s, so it could make sense to update this timeout to match that timeout since we will return gateway timeout errors if we go past that 360s, but we don't want to go below that amount. In looking at our logs, the longest requests I have seen for the 1010 CG have been about 180s (~3 minutes), so I think we want to ensure we are at least above that value. It could make sense to set this to 360s to match, but honestly as long as we are above that it's probably fine 🤷 .

**Comment by hdjustice** [comment]
@coope93  Does it matter having a longer timeout if the ALB timeout is shorter?  
Sure we could match it, but does it really matter?  I am inclined to not mess with it unless it is causing an issue.

**Comment by coope93** [comment]
The only concern with having our timeout longer is that a request will never go that long, since it would run into the ALB timeout  first. So for clarity updating it could be helpful, but realistically now that the ALB is updated it should never take that long since we have yet to hit a 6 minute timeout on the ALB. We only had the issue since the ALB timeout was 60 seconds. So it's probably fine to leave it as is at 10 minutes.

**Comment by hdjustice** [comment]
Ok, let's leave it for now, close this ticket, and if we run into an issue, we will have this history.
