### ISSUE TITLE
Create process for how the Feedback Repository gets updated

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81847]
## Purpose
Consider/create process for updating the artifact on a regular basis.  Look for opportunities for automation.

- We want to:
  - ensure that supporting processes minimize manual references or processes
  - attempt to minimize any duplication of data or data entry
  - attempt to consolidate all related sources/artifacts within Confluence

## Tasks
- [x] create a flow for how the Feedback Repository gets populated with new entries
- [x] discuss flow with team
- [x] make any needed adjustments
- [x] document process

## Acceptance Criteria
- [x] visual flow of process is created 
- [x] process is documented 
- [x] "automations" are tested/documented
