### ISSUE TITLE
[FE] My VA Forms Status: Benefit Intake API familiarization

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81851]
## Background
As part of the work to add forms status (or forms submission status) to My VA we need to modify the existing "ApplicationInProgress" component card we use for draft applications to include each of the discussed statuses. We will need to pull in the statuses from the Benefit intake API, and we need to familiarize ourselves with that API so we know to how bring in the statuses.

## Tasks
- [x] Review [benefit intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- [x] Discuss Tom's work to understand the endpoint he created
- [x] Consult with VFF team to ensure alignment between My VA and confirmation page (and notifications?)
- [ ] Consult with Lighthouse as needed (they own the benefit intake API)
- [ ] If additional implementation tickets are needed work with PM to create

## Acceptance Criteria
- [x] We know how to pull in the status from the API response - strategy documented in the ticket and added to the [tech discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/technical-discovery.md#frontend)
- [ ] Additional implementation tickets are created as needed

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Dev
- _How can this work be validated?_ Conversation/review with dev

## Resources
- [Benefit intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- [FE technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/technical-discovery.md#frontend)

**Comment by allisonlu** [comment]
@ajakabcin 

no progress on this ticket for sprint 37. for sprint 38 planning, let's keep this at 3 points

**Comment by allisonlu** [comment]
@ajakabcin 

rolling into next sprint 40 as 2 points!

**Comment by allisonlu** [comment]
closing this ticket. waiting on Tom's documentation for the new API endpoint
