### ISSUE TITLE
[FE] My VA Forms Status: Create Action Needed status (2 of 3)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81854]
## Background
As part of the work to add forms status (or forms submission status) to My VA we need to modify the existing "ApplicationInProgress" component card we use for draft applications to include each of the discussed statuses. This ticket is to create the **action needed** status.

## Tasks
- [ ] Leverage previous constructed data elements from received status work
- [ ] create error alert if status === `Action Needed`, which means "form submissions did not make it"

## Acceptance Criteria
- [ ] We can render a submitted application in the "action needed" state 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Work with VFF team to submit a digital form and manually trigger error (non-system error)

## Resources
- [Benefit intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- [FE technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/technical-discovery.md#frontend)
- [Figma file for Action Needed](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=1241-24411&t=wMaSLViFgo0tTuvc-4)

**Comment by ajakabcin** [comment]
@mattmarino-adhoc to add figma file to Resources section

**Comment by ajakabcin** [comment]
I'm going to close this out since validation will need to take place in coordination with VFF. We'll track testing and validation in the next sprint via #91654
