### ISSUE TITLE
[FE] My VA Forms Status: Create "Submission in Progress" status (3 of 3)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81852]
## Background
As part of the work to add forms status (or forms submission status) to My VA we need to modify the existing "ApplicationInProgress" component card we use for draft applications to include each of the discussed statuses. This ticket is to create the **submission in progress** status.

## Tasks
- [ ] Set up `my_va_form_submission_statuses` feature flag on `vets-website`
- [ ] Pull in web component for pending status and tweak to match designs
- [ ] Pull in statuses from API response
- [ ] add "Submitted on" date - when user submitted it
- [ ] add "Next step"
- [ ] add additional info web component with a process list

## Acceptance Criteria
- [ ] We can render a form on My VA in the "submission in progress" status

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Works for VFF to create a form and "submit" confirm it appears as pending on My VA

## Resources
- [Benefit intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- [FE technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/technical-discovery.md#frontend)

**Comment by ajakabcin** [comment]
bumping to sprint 43 while we wait for content to be finalized

**Comment by ajakabcin** [comment]
I'm going to close this out since validation will need to take place in coordination with VFF. We'll track testing and validation in the next sprint via #91654
