### ISSUE TITLE
[FE] My VA Forms Status: Create Received status (1 of 3)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81853]
## Background
As part of the work to add forms status (or forms submission status) to My VA we need to modify the existing "ApplicationInProgress" component card we use for draft applications to include each of the discussed statuses. This ticket is to create the **received** status.

## Tasks
- [x] Set up `my_va_form_submission_statuses` feature flag on `vets-website`
- [x] add API endpoint to mock server and add mock data 
- [x] coordinate with Tom to add `received` to the API response (so that we can trigger the status and display the "received" date, that is the date the the application/form arrived at central mail/vbms)
- [x] Make updates to Draft card
- [x] Make sure multiple forms (Draft and Received) can appear in single column
- [x] Change title of section to "Benefit applications and forms"
- [x] Change layout to single column

## Acceptance Criteria
- [ ] The code for rendering a status card in received status exists
- [ ] Section title is updated in staging
- [ ] "Draft" tag exists for draft form cards in staging
- [ ] Single column structure exists on staging

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member; dev to validate code
- _How can this work be validated?_ Ensure feature flag is turned on in staging only, validate criteria in AC section

## Resources
- [FE technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/technical-discovery.md#frontend)

### Backend
- [Benefit intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- [form `submission_statuses` API docs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/form-status/backend_documentation.md) (sensitive)

### Design
- [Figma file for received status](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=1236-25098) 
- [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/FE-documentation-MVP.md#form-status-card---received)

**Comment by mattmarino-adhoc** [comment]
Draft card includes the "Draft" tag

**Comment by DanielMiller-agile6** [comment]
I made some fixes to the PR and got it merged today.  More details are on PR and git commits.  Verified that this is working on staging with toggle "on". Verified that "prod" flag is turned off.

<img width="488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVIzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5ccc1389a5bd861798e04601e2b7e00a74c74ce/Screenshot%202024-08-21%20at%2011.52.06%E2%80%AFAM.png" alt="Screenshot 2024-08-21 at 11.52.06 AM.png" />
