### ISSUE TITLE
[FE] My VA Forms Status: Update name/structure of Benefit Application Drafts section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81856]
## Background
As part of the work to add forms status (or forms submission status) to My VA we need to modify the existing Benefit Application Drafts section on My VA to better reflect and manage the additional form statuses we'll be displaying.

## Tasks
- [ ] change section heading to "Benefit applications and forms"
- [ ] change layout to single column

_previous tasks_
- [ ] change layout to two-columns (one column for card, one column for secondary CTA links)
- [ ] secondary CTA link for resources and support link w definitions of statuses
- [ ] maybe: organize cards by statuses under their own headings. ([Figma conversation](https://www.figma.com/file/GeBhUvcQAbbGYdmDIS7bRN?type=design&node-id=149-2062&mode=design#775409022))

## Acceptance Criteria
- [ ] Section heading is updated
- [ ] Section structure is updated to single column

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Log into staging and confirm section heading and structure are updated

**Comment by ajakabcin** [comment]
Closing - this was addressed in #81853
