### ISSUE TITLE
[BE] My VA Forms Status: Update BE technical documentation for Benefit Apps section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81860]
## Background
We maintain documentation for implementation purposes, but we also maintain technical documentation that explains "how the page works" - i.e. how do forms appear there, are there specific configurations etc. We need to review our existing BE technical documentation for the Benefit Applications section (currently named "[Saved applications](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/saved_applications/backend_documentation.md)" in our BE documentation in the sensitive repo.)

## Tasks
- [x] Review/familiarize yourself with existing documentation
- [x] Tom and Daniel to meet and go over changes for knowledge transfer/share
- [x] update [BE documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/saved_applications/backend_documentation.md) (because in addition to health care applications, we also include disability and non-disability forms) or combine with [this](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/form-status/backend_documentation.md)
- [x] Include forms status functionality changes
- [x] Update [architecture diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/Technical-diagrams/My-VA-architectural-diagram.md) (update benefit applications section)

## Acceptance Criteria
- [x] Updated BE documentation exists that captures current state of the Benefit applications and forms section on My VA

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_

## Resources
- [My VA BE documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/backend_documentation.md)

**Comment by ajakabcin** [comment]
@tpharrison I think you already did this but can you confirm? Thank you! cc @DanielMiller-agile6

**Comment by DanielMiller-agile6** [comment]
Updated docs.  Includes links to Allison's FE docs along with Tom's BE architecture docs.
