### ISSUE TITLE
[Design] My VA Forms Status: Create FE documentation (for implementation)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81863]
## Background
We need to create the FE documentation for the implementation of the forms status work on My VA. This documentation is critical for both implementation purposes and for understanding how our features work over time. This will be a _new_ version of FE documentation for the Benefit Applications section on My VA.

We should use this opportunity to update any one-off design updates that have been made over the last few months (for example):
- #71031 

## Tasks
- [x] Create FE documentation in GH under the forms status project ([here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/FE-documentation-MVP.md))
- [x] Review with PMs and devs
- [x] PM to link to main documentation

## Acceptance Criteria
- [x] FE documentation is created and reviewed with team (this can be a draft state but should be in Github)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Dev
- _How can this work be validated?_ Read documentation, ensure it covers what is needed for implementation

## Resources
- [Latest version of FE documentation for the Benefit Application Drafts section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/applications-FE-documentation.md#my-va-benefit-application-drafts-frontend-documentation)

**Comment by mattmarino-adhoc** [comment]
Not ready for ticket yet

**Comment by ajakabcin** [comment]
@mattmarino-adhoc this is already slated for sprint 41 (this coming sprint), the pipeline was mislabeled sorry about that!

**Comment by mattmarino-adhoc** [comment]
Reviewed by Allison, closed out
