### ISSUE TITLE
Copy of Staged Rollout of Find a Rep 2.0

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81879]
## Staged Rollout Schedule

Original schedule:
~1. Stage A: 10% of users on 3/11 (Monday)~
~2. Stage B: 25% of users on 3/13 (Wednesday)~
~3. Stage C: 50% of users on 3/18 (Monday)~
~4. Stage D: 100% of users on 3/20 (Wednesday) - monitor for any issues through 3/25 EOD (Monday)~

After realizing that users aren't getting to our landing page easily to make effective use of our % ramp up, we are changing our approach to increasing visibility:
1. Stage A: 10% of users on 3/11 (Monday) [Complete]
2. Stage B: 100% of users on 3/13 (Wednesday) + launch best bets for an initial boost to visibility
3. Stage C: Implement redirects on 3/18 (Monday) for an added boost to visibility
4. Stage D: Begin entry point work on 3/20 (Wednesday) so pages point directly to the Accredited Rep landing page

Before proceeding to the next stage, we'll want to consider any Sentry errors and examine user behavior for reporting outdated information, to determine if updates need to be made before increasing visibility.   

[Full release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/release-plan-find-a-representative-2.0.md)

## Tasks
- [x] 3/11: Roll out to 10% of users
- [x] 3/13: Roll out to 100% of users
- [x] 3/18: Implement redirects (https://github.com/department-of-veterans-affairs/va.gov-team/issues/69952)
- [ ] 3/20: Begin entry point work (https://github.com/department-of-veterans-affairs/va.gov-team/issues/67034)

## Acceptance Criteria
- [x] Find a Representative 2.0 is live on VA.gov for all users!
- [x] All traffic is pointing directly to the [accredited rep landing page](https://www.va.gov/get-help-from-accredited-representative/) and Find a Rep

**Comment by oddball-lindsay** [comment]
zenhub stuplicate
