### ISSUE TITLE
Staged Rollout of Representative Status Widget 1.0

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#81878]
## Staged Rollout Schedule

1. Stage A: 10% of users on 5/13 (Monday)
2. Stage B: 50% of users on 5/15 (Wednesday)
3. Stage C: 100% of users on 5/20 (Monday)
4. Stage D: Add the Representative Status Widget to the Accredited Rep landing page (managed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/67034)

Before proceeding to the next stage, we'll want to consider any Sentry and Datadog errors, to determine if updates need to be made before increasing visibility.   

[Full release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/release-plan-representative-status-widget-1.0.md)

## Tasks

- [x] Stage A: 10% of users on 5/13 (Monday)
- [x] Stage B: 50% of users on 5/15 (Wednesday)
- [x] Stage C: 100% of users on 5/20 (Monday)
- [x] Stage D: Add the Representative Status Widget to the Accredited Rep landing page (Alert CAIA in https://github.com/department-of-veterans-affairs/va.gov-team/issues/67034)

## Acceptance Criteria
- [x] Representative Status Widget is live on the [Find a Representative page](https://www.va.gov/get-help-from-accredited-representative/find-rep/) for all users!
- [x] CAIA has been alerted to add the Representative Status Widget to the [accredited representative landing page](https://www.va.gov/get-help-from-accredited-representative)

**Comment by oddball-lindsay** [comment]
From Colin for Stage A:
> Staged rollout has begun and Representative Status Widget is now live for 10% of authenticated users. This seems to be the standard approach for staged rollouts, but tomorrow we'll be updating the availability to encompass 10% of cookie sessions. In the meantime, anyone with a va.gov login has a small chance of viewing their POA in prod

**Comment by oddball-lindsay** [comment]
Pushed to 10% of authenticated users on Monday 5/13, but today (5/14) realized we had an env check preventing the widget from loading in production.  PR to fix that: https://github.com/department-of-veterans-affairs/vets-website/pull/29740

**Comment by cosu419** [comment]
Merged above fix in a separate PR: https://github.com/department-of-veterans-affairs/vets-website/pull/29778

**Comment by oddball-lindsay** [comment]
Oops thanks @cosu419 !

**Comment by oddball-lindsay** [comment]
As of 5:27p ET yesterday 5/15, Kayla said "60 requests so far, all 200s".

Some errors are coming through - some 404s and 422s.  
- LH is looking into the 422 scenario and participant IDs vs. ICN.  
- Seeing some POA codes returned from BGS that contain `-` (not the expected POA code) which is throwing a 404.  LH is aware and thinking about updates needed.

**Comment by oddball-lindsay** [comment]
From the recent OCTO+Lighthouse sync:
> 422 error coming up when a participant ID is not available - 0.01% of traffic is typical, but there has been more than this from this service/feature (5%) when we were at 50%.  Hope is things will level out when the feature hits 100%, keeping an eye on this and should look into if it remains at 5%.

**Comment by oddball-lindsay** [comment]
The Widget made it's way to the landing page 🎉 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142453186/d83a02b7-fb84-4d92-99a7-43b7a3ef8f04)
