### ISSUE TITLE
[DevOps] Create service accounts for `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#81885]
## User Story
As an engineer, I need to create service accounts within `vaec-cie` to enable further progress.

Looking through the IAM policies attached to my role, it seemed ... inconclusive as to whether I would be able to create service accounts or not, and I didn't want to attempt it until we'd had our kickoff meeting for the migration.

Eric suggests that it will not be possible for me to create service accounts. Which makes sense.

Since these service accounts are essential for further progress, I need to create them or, if I can't, raise the issue so that I can have them created on my behalf.

## Tasks
- [ ] [DevOps] Create service account for CHIP/LoROTA/VistA API operations (replacing CMS-service-account-1)
- [ ] [DevOps] Create service account for VeTEXT Datadog (replacing CMS-service-account-2)
- [x] [DevOps] Do not create a service account to replace CMS-service-account-3.

## Acceptance Criteria
- [ ] Two service accounts exist with relevant permissions

**Comment by ndouglas** [comment]
Blocked on this until Monday apparently.


![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/5dede8e0-61a6-4688-8abd-fc908cb4e79c)

**Comment by ndouglas** [comment]
This is blocked by #82615.

**Comment by ndouglas** [comment]
Found a way around the problem; this ticket is no longer necessary.
