### ISSUE TITLE
Burial | Update Confirmation Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#81894]
## Issue Description
_Updates have been made to the existing confirmation email that is sent once a burial form is submitted. The updates related to submitting additional documents (FDC program) are still under SME review, but the remaining updates can be made._

CAIA review request: #78035
- [Google doc](https://docs.google.com/document/d/1EYAcOxEPykMe2CMo7a7zU1Alw6HcHd_8CSnkBiqce2s/edit)
- [Sharepoint](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Non-disability%20Benefits/Burial/Design%20Artifacts/Burial_21P-530EZ%20Confirmation%20Email-Draft-1.0.docx?d=w54eb63d64b974104afe2f960bea55870&csf=1&web=1&e=tt9GWS)

---
## Tasks
- [x] Confirm non-FDC updates are good-to-go with SMEs
- [x] Make non-FDC updates to email in VA Notify

## Acceptance Criteria
- [x] Burial claim confirmation email copy has been updated
---

**Comment by fiorella-io** [comment]
Currently blocked on 3 items:
- Add the claimant's last name
- Add the list of uploaded files
- Conditional show the link to the CST tool to only authenticated users

I'm still waiting for the final copy of a section of the email

**Comment by fiorella-io** [comment]
@steele-lm we might need an engineering ticket to add #2 and #3. Let's see what we hear back from the VAnotify channel

**Comment by sortizsh** [comment]
We cannot add claimant's last name due to PII 
File names are also conditional since they can have PII within the file name

526 team has an approach, discuss with them (Nathan)

**Comment by fiorella-io** [comment]
We got the final copy!🎉 I've added links to this ticket

**Comment by steele-lm** [comment]
Open question: How to show "check your status" link to only those who have claims submitted and are authenticated.

**Comment by fiorella-io** [comment]
Another open question is how to add a list of uploaded documents. [I had mentioned it earlier](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81894#issuecomment-2110591973)

**Comment by steele-lm** [comment]
@fiorella-io I thought we landed on not including a list of documents bc the file names might reveal PII?

**Comment by fiorella-io** [comment]
Ohh, that's right!

**Comment by steele-lm** [comment]
Blocked: Need to figure out how to add the "check your status" link to the confirmation email sent to to users who submitted claims authenticated.

**Comment by fiorella-io** [comment]
I published the new Burial email confirmation copy to production after Renu's (Privacy officer) approval. Since the original confirmation email also included a link to the CST tool, we included it in this new update. The Pension Burial team can conditionally show this link in the future.
