### ISSUE TITLE
Daily Qualitative Data Request 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#81904]
## Issue Description
Daily pull of DOMO data for:
va.gov/my-health/secure-messages
va.gov/my-health/secure-messages/new-message
va.gov/my-health/secure-messages/inbox
va.gov/my-health/secure-messages/drafts
va.gov/my-health/secure-messages/sent
va.gov/my-health/secure-messages/trash
va.gov/my-health/secure-messages/folders

---
## Tasks
- [x] Query DOMO data base daily 
- [x] Forward data to Anne Costello 
- [ ] 

Acceptance Criteria
## Acceptance Criteria
 - [x] **Scenario: Daily Qualitative Data Request**
  - Given the daily pull of DOMO data is implemented
  - When the data is pulled for the specified URLs
  - Then the data should be forwarded to Anne Costello
- [ ] **Scenario: Configuration of the issue**
  - Given the issue is attached to a Milestone
  - When the issue is attached to an Epic
  - Then the issue should be labeled with the appropriate Team and Practice Area
  - And the issue should be labeled with the correct Type
  - 

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
