### ISSUE TITLE
[BE] My VA Forms Status: Document and Standardize Error Responses

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81901]
## Background
Identify and standardize form submission errors for My VA page.

Here is the list of known errors (subject to change):

- Security
  - (401) Authentication
  - (403) Authorization
- Environmental
  - Client Based
    - (413) Payload too large
    - (429) Rate limit reached
  - Server Based
    - (500) Server Error  
    - (502) Service Unavailable
    - (504) Bad Gateway
- Business
  - (400) Invalid or missing list of GUIDs
  - (422) Upload rejected by upstream system. Processing failed and upload must be resubmitted
  - (422) Status not available.

> Note that for the current iteration of the Benefit Application Drafts section, the data for saved applications is gathered from the same API as the main user call. Therefore, there are [no errors](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-application-drafts-use-cases.md#edge-cases) (currently) specific to just this section. If the main user call fails, the entire My VA page displays an error, in which case we follow the behavior outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/system-cant-connect-to-MPI.md), for a full page error.

FE portion of this work is handled in #83395 

## Tasks
- [ ] Work with FE and design to identify the types of system errors that can occur.
- [ ] Standardize the responses for known errors.
- [ ] Document the list of known errors.

## Acceptance Criteria
- [ ] BE is able to handle and parse list of known errors to consistent standard.

## Validation
- Documentation complete.
- BE tests cover list of errors.
- Review with team.

## Resources
- [BE technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/technical-discovery.md#backend)
- [Benefit intake API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)

**Comment by tpharrison** [comment]
Ran into some automated code check issues.  I'll need to spend some time reviewing.
