### ISSUE TITLE
Publicize new Insights Repository

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#81900]
## Purpose
We'll want to socialize the new Insights Repository once it's ready for consumption.

## Tasks
- [ ] Write up a new page in Confluence explaining the new offering, how it is to be used, and how it is derives its info.
- [ ] Socialize the IR on Slack
- [ ] Socialize the IR on Demo day
- [ ] Socialize the IR in CoPs

## Acceptance Criteria
- [ ] The new IR is known by OCTO, Leadership, and Platform teams
