### ISSUE TITLE
Update QA operational guidance at SR

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#81906]
## User Story
As a QA specialist supporting Collaboration Cycle, I want to ensure I have the correct guidance for flagging imposter components so that I am not identifying issues that the VFS team is unable to fix.

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
At a recent SR, an imposter component issue ticket was opened for the `va-button` component. However, the va-button component that was used by the VFS team was actually a pattern/template from the Forms Library. Governance PO Matt Dingee [commented on our Slack page](https://dsva.slack.com/archives/GNF5GSD9N/p1714156065336689) stating the `va-button` and the `va-link` should never be flagged as an imposter component, whether within a Forms Library pattern/template or not, because they are not true components and are very unlikely to break.

The purpose of this ticket is to update the imposter component guidance within the QA operational guidance at Staging Review so that button and links are excluded.

## Tasks
- [x] Update the QA Operational guidance at SR to specify that Governance team should not flag as imposter components:
   - [x] Buttons that do not use the `va-button` component
   - [x] Links that do not use the `va-link` component, 
   - [x] Any Forms Library pattern/template that does not use the `va-button` or `va-link` components

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team QA operational guidance at SR has been updated to reflect what does not qualify as an imposter component

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman this is ready for review - I updated the [process section](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint#Process) of the document.

**Comment by shiragoodman** [comment]
@it-harrison change looks good! I had 1 comment that was a bit out of scope, but otherwise this is approved. Thanks!
