### ISSUE TITLE
Delay to Vets-API ELB during deployments 

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#81916]
## Issue Description

As developers and users, 
We need deployments to go smoothly and without significant delay
So that the deployments do not hang up other deployments and delay other users of the Vets-API. 

It was brought to the team's attention back in January ([here](https://dsva.slack.com/archives/CBU0KDSB1/p1706631322227849)) that there have been delays that happen during deployment. While it is expected that requests to the vets-api ELB, during deployments, may take up to 180s we may need to partner with the Lighthouse team to reduce timeouts and failures and try to create a solution that will minimize these. Considering the duration of the timeouts applied for external services, there will be some request timeouts for a minute or so.

## Tasks
- [ ] Review current logs (see Slack thread)
- [ ] Troubleshoot what could be causing the timeouts and failures during the daily deployment
- [ ] Document the timeouts and failures, see if there is a common thread
- [ ] Meet with Lighthouse team (Beau Grantham?) to ideate on solutions for minimizing timeouts and failures
- [ ] Test ideas for minimizing timeouts and failures

## Success Metrics
- [ ] That the root cause of the delays and timeouts are identified
- [ ] That a solution is created and successfully tested to limit delays and timeouts during the daily deployment

## Acceptance Criteria
- [ ] That there will be a viable and better solution that has fewer failures and timeouts in the daily deploy for the Vets-API ELB
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by LindseySaari** [comment]
We discovered a pattern related to the 504 logs:

You can see the 504 is actually being passed back up the chain from the fwdproxy (we call Lighthouse through the fwdproxy). 

[Traefik 504s](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Atraefik%20%40http.status_code%3A504&agg_m=count&agg_m_source=base&agg_t=count&analyticsOptions=%5B%22line%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice%2C%40http.status_code%2C%40http.url_details.path&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=paused&sort=time&spanID=3021207900023491397&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1716396077570&to_ts=1716399980901&live=false) => [Vets API 504s](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20pod_name%3Avets-api-lighthouse-%2A%20%40http.status_code%3A504%20&agg_m=count&agg_m_source=base&agg_t=count&analyticsOptions=%5B%22line%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice%2C%40http.status_code%2C%40http.url_details.path&fromUser=true&messageDisplay=inline&refresh_mode=paused&sort=time&spanID=3021207900023491397&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1716396060000&to_ts=1716399960000&live=false) => [fwdproxy 504s](https://vagov.ddog-gov.com/logs?query=service%3Afwdproxy%20%40http.status_code%3A504&agg_m=count&agg_m_source=base&agg_t=count&analyticsOptions=%5B%22line%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice%2C%40http.status_code%2C%40http.url_details.path&fromUser=true&messageDisplay=inline&refresh_mode=paused&sort=time&spanID=3021207900023491397&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1716396077570&to_ts=1716399980901&live=false)

Essentially the request goes from `Lighthouse => Traefik => Vets API => Fwdproxy` and the Fwdproxy is returning a 504 back up the chain

**Comment by jennb33** [comment]
In DSU discussion 5/30, if this ticket is not completed by the end of the Sprint (6/5/2024), then it needs to go to DevOps COP. 
Lighthouse thought they needed more servers. That was tried, and was not a successful strategy. 
@RachalCassity and @flooose are going to continue to try their strategies, including working with Hector, then we will determine next steps for this ticket.

**Comment by jennb33** [comment]
Please see this notebook for the 502/4 issues: https://vagov.ddog-gov.com/notebook/3799/five-hundreds

**Comment by jennb33** [comment]
This ticket was duped for Sprint 2, new ticket is [84627](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/84627)
