### ISSUE TITLE
Create CC app within vets-website

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#81933]
## Tasks

- [x] Create new app pages within `vaos/referral-appointments` (new folder)
- [x] Connect existing page with a simple link
- [x] Create skeleton pages for use (3 to 4 at least)

## Testing

- [x] Ensure new tests are added for functionality
