### ISSUE TITLE
[FE] 10-10EZ - Replace use of Moment with Date-Fns 

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#81938]
## Description
`Moment.js` was a popular date formatting and validation library that has sense been deprecated. The use of this library increases memory usage, and thus decreases overall performance of the apps. We need to replace Moment with the accepted alternative (and current platform recommendation) of [date-fns](https://date-fns.org) (date functions).

## Tasks

- [x] Identify all usage of Moment.js within the application
- [ ] Replace usage with the `date-fns` equivalent
- [ ] Update all unit and cypress testing as required
- [ ] Validate all date formatting and automated test results

## Acceptance criteria

 - All date formats display as intended
 - Application performance is not hindered by use of deprecated and resource-heavy libraries
