### ISSUE TITLE
Support Request: Tests to stress test variable has gotten too long and breaks GHA workflow

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#81940]
## Issue Description
GitHub actions workflows environment variables and output variables have a character limit that is being exceeded in certain cases with the TESTS_TO_STRESS_TEST variable. This needs to be converted to being written to a file, archived as an artifact, and then downloaded where needed and read in the applicable files.

---
## Tasks
- [ ] Change TESTS_TO_STRESS_TEST from an output to being written to a file.
- [ ] Archive the file after creation
- [ ] download it where TESTS_TO_STRESS_TEST is needed
- [ ] Change scripts as needed to read the file instead of referencing the variable

## Acceptance Criteria
- [ ] TESTS_TO_STRESS_TEST no longer breaks the GHA workflows.
