### ISSUE TITLE
[FE] My VA Forms Status: Create prototype for usability study

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81959]
## Background
In preparation for our joint usability study with the VFF team, we need to build our prototype. We'll likely be using codepen for this (will confirm in meeting on 5/6).

**Prerequisites:** 
- [ ] Design alignment between My VA and VFF (or narrowed to finite options)
- [ ] Alignment with VFF on tool for prototype (preferably codepen)

## Tasks
- [x] Review research plan with Matt as needed to make sure we know what's needed in the prototype
- [x] Review existing codepen artifacts to see if there's anything we can repurpose
- [x] Set up codepen for the study
- [x] Coordinate with VFF so they can incorporate their part of the study into the prototype
- [x] Conduct a walk-through with Matt and Jeana for validation

## Acceptance Criteria
- [x] Prototype is ready for study

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Designer
- _How can this work be validated?_ Review prototype across My VA and VFF

## Resources
- [Research plan](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Product/Form%20Status/Research/research-plan.md)
- [Figma mockups](https://www.figma.com/file/GeBhUvcQAbbGYdmDIS7bRN/Confirmation-%26-Status?type=design&node-id=39-15291&mode=design&t=YGPLhyZ8XkJq0USk-0)
- [CodePen collection](https://codepen.io/collection/oEmrJy)

**Comment by allisonlu** [comment]
all the prototypes have been added to this [Forms status Codepen collection](https://codepen.io/collection/eJoQJG?grid_type=list)

**Comment by ajakabcin** [comment]
Walk through scheduled for tomorrow afternoon (5/21) at 2pm et.
