### ISSUE TITLE
[Research] My VA Forms Status: Prep for + execute UAT

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#81967]
## Background
We need to put finishing touches on UAT artifacts and conduct internal/informal UAT on the forms status work in partnership with the VFF team.

## Tasks
- [x] Review and update artifacts
- [x] Conduct UAT session (Thursday, 10/9)
- [x] Record all findings

## Acceptance Criteria
- [ ] Sessions are conducted/complete

## Validation
- _Who can validate this ticket?_ any team member
- _How can this work be validated?_ confirm UAT is complete

[UAT Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/forms-status-on-My-VA/UAT)

**Comment by mattmarino-adhoc** [comment]
Removed pilot sessions from ticket (redundant)

**Comment by ajakabcin** [comment]
thanks @mattmarino-adhoc just fyi this is for UAT not the usability study

**Comment by mattmarino-adhoc** [comment]
Artifacts updated, but conversation guide and tasks needs to be updated further. Completion of this ticket will happen by EOW.

**Comment by mattmarino-adhoc** [comment]
Unfortunately we experienced failures that indicate we are not ready for release. Specifically, the Intent to File form both: did not have a link to My VA appearing on the Confirmation page, nor did a status card appear on My VA. According to Jeana, there are apparently issues specific to Intent to File that could be causing both of these problems, but we need to discuss further and ensure that they aren't isolated to this one form. AJ has sent out a meeting invite for later today (10/9) to discuss our options, but at the very least it seems like pulling Intent to File from MVP is probably a good course of action.
