### ISSUE TITLE
[FE] 10-10EZ - TERA - Remove feature toggle conditional logic

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#81972]
## Description
Once the TERA section has been live for 61 days (to clear any in-progress forms), we need to remove all conditional logic for the TERA enabled feature flag. Since this is a permanent part of the form, we do not need the feature flag logic any longer. Starting May 5, 2024, we will be at the 61+ day mark and can complete this work.

## Tasks
- [x] Remove conditional logic from the app
- [x] Remove reference to feature toggle from platform registry in `vets-website`
- [x] Remove reference to feature toggle from `vets-api`

## Acceptance criteria

- TERA section is a permanent member of the Health Care Application
