### ISSUE TITLE
[DevOps] Verify what ports are in use in `vaec-cms`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#81998]
## User Story
As an engineer, I need to determine what ports are in use in `vaec-cms` so that I can determine whether an ESECC process needs to take place.

ESECC is needed for non-80/443 ports.

## Tasks
- [x] [DevOps] Figure out how I can find which ports are actually being used.

## Acceptance Criteria

- [x] I've determined which ports are actually in use.
- [x] If a non-HTTP(S) port is in use, I've relayed that information to Shalom et al to ensure the ESECC process moves forward.

**Comment by ndouglas** [comment]
@olivereri You mentioned an ESECC for Vista API; is that because we're using a non-HTTP(s) port or for some other reason? Wanna make sure I don't lose that thought.

**Comment by olivereri** [comment]
I don't always catch the emails generated by Github issues. But yeah, you got it.

**Comment by olivereri** [comment]
We can rely on ESECC  BPE spreadsheets to inform the ports used in `vaec-cms` besides 80/443.

TCP 18100 - 18141
TCP 24900 - 24999
TCP 9000 - 9100

Anything else is going to be internal to the AWS account such as Memcache and RDS Security Group rules.

I don't think we'll need to inform Shalom about the ports, we'll be able to leverage existing ESECC RFCs to open up ports.
