### ISSUE TITLE
Add visible character limits to Profile fields

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8199]
## Background
We want to make sure to note the character limit on the field itself so users know. On other fields on our site this kind of thing is noted as parenthesis after the label, e.g. like this "Street address (35 characters max)"

[Reference ticket-cap street address lines to 35 char #12265](https://github.com/department-of-veterans-affairs/vets-website/pull/12265#issuecomment-615533840)

![123.png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/90aa64c1-83fe-4327-b24b-e4dd8a0daff3)

## Tasks
- [x] Design: Provide any necessary design specs
- [x] FE: add visibled character limit to fields within profile

## Acceptance Critera
- [x] Visible character limits exist on the profile fields

**Comment by Samara-Strauss** [comment]
@tressaellen @erikphansen 

- Tressa should provide design for this first (even though it's pretty straightforward).
- I'll leave it up to y'all to decide whether you want to address this for profile 1.0 or if you just want to incorporate this into 2.0.

@mshea0606 

- Can you please add this ticket to next sprint? It should be a quick one to knock out.

**Comment by mshea0606** [comment]
@Samara-Strauss - This has been added to S20 objectives

**Comment by sanlouise** [comment]
@mshea0606 @tressaellen 

There must be other places on the website where we use form fields with character limits, should we talk about a site-wide implementation? 

Also, there are other ways to handle character limits dynamically, like how [Google Material Design](https://material.io/components/text-fields) does it. Would it be worth considering adding a similar dynamic character limit count instead so the user can see when they have exceeded the max limit?

**Comment by erikphansen** [comment]
@sanlouise That's certainly a good idea but outside the scope of this change. Ideally, at the very least, we'd have an option to automatically add `(XX characters maximum)` to the field label if `maxLength` is set, similar to how `(*Required)` is added if the field is required. Honestly this probably wouldn't be _too_ hard to implement. You could bring this up in the #vfs-platform-support channel since it would be a change to the form system and that's "owned" by the VSP Platform team.

**Comment by Samara-Strauss** [comment]
Looks great!
