### ISSUE TITLE
Create a user flow for accepting and onboarding non VA staff as Proofing Agents

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#82017]
## Context
Right now we are training MHV Coordinators, who have level IAL3 assurance through their PIV cards, to become Proofing Agents. In the future we would like to open up this role to those who work at other sties that are available to a Veteran (VSO's, veteran volunteer sites, etc. How might we identify and onboard those without prior IAL3 assurance to gain access to MPI and our IPP application?

## Tasks

- [ ] create flow in a pair
- [ ] present to design team in design weekly
- [ ] show flow to Porta in identity AMA
- [ ] show flow to Carnetta Scruggs for validation

## AC

- [ ] create a user flow that captures how non VA staff may be onboarded as a Proofing Agent
- [ ] include how we might identify a site and staff who can authorize Proofing Agent access
- [ ] add flow to future state service blueprint
- [ ] document flow in future state document
