### ISSUE TITLE
Consider and create other views for the Insights Repository

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#82015]
## Purpose
We want to create [additional views](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3117908292/Closing+the+Loop+on+Feedback+-+how+we+get+there#What-we-need-to-do-now-to-get-this-accomplished) that surface important metrics or Status updates.  these may use the Card or Board formats.

## Tasks
- [x] [Consider what types of views](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3169190002/Other+views+for+the+Insights+Repository) might be important for a user
- [x] Setup view(s)
- [x] adjust views to contain the data that would be most useful
- [x] also consider other data relationships that might be valuable to include and add

## Acceptance Criteria
- [x] Considered views are available
- [x] each view contains relevant data types and relationships
