### ISSUE TITLE
Covid-19 Chatbot Contact Center Review

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#8202]
## User Story or Problem Statement
As a contact center manager and representative, I need to know where the new chatbot feature exists and how it works so I can be prepared to answer veteran and user questions about it. 

## Goal
All VA contact centers have the necessary training materials to prepare their contact center representatives to understand the functionality of the Chatbot and answer any questions users might have about it. 

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [x] Hold demo meeting with Chatbot team
- [x] Receive access to testing site for chatbot
- [x] Receive screen grabs for error messaging for chatbot issues

## Acceptance Criteria
- [x] Completed Chatbot demo video that is uploaded to VA youtube channel
- [x] Published Chatbot product guide.
- [x] All training materials sent to the covid-19 contact center group. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Provided all necessary training documents and demo videos to VA contact centers for chatbot. 

Product Guide: 
[Covid19.Chatbot.Product.Guide.4.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4546151/Covid19.Chatbot.Product.Guide.4.23.docx)
[Covid19.Chatbot.Product.Guide.4.22.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4546152/Covid19.Chatbot.Product.Guide.4.22.pdf)

Demo Video: https://thoughtworks.zoom.us/rec/play/u5Ytfrv-q2g3GNKXswSDCv5_W9Xuevms2ice_aBeyBy1WiEGMVD3M7RDM7EoF7607cAU2eYYmC2zEdLo?startTime=1587496042000&_x_zm_rtaid=kFurCJPAShm7HJLWZgLq8A.1587497511188.f628c65e2554f2cf89c77c443624ae0d&_x_zm_rhtaid=433
