### ISSUE TITLE
Document for 'Use This Not That' for Commonly Used Metrics in Google Analytics

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#82030]
### Description
_This was a product of a workshop on 4/30._ 

Based on how commonly tracked certain metrics are used within Universal Analytics, there are likely instances of those metrics differing from UA to GA4, as well as an opportunity to help teams know what they should be paying attention to going forward, (versus what they might have been tracking that wasn't telling the entire story).

This document should essentially accomplish telling teams -- some common metrics in GA4 to pay attention to, and what they mean, as well as examples of metrics that might be misleading, that could likely be avoided.

### Tasks

- [ ] Draft out structure of page.
- [ ] Identify metrics we'll want to recommend tracking.
- [ ] Identify metrics that we recommend avoiding, or not paying attention to.
- [ ] Draft out page.
- [ ] Identify within the Platform Website's IA where would be the best place to upload this content.
- [ ] Upload to Platform Website.

---
### Acceptance Criteria

- [ ] Tracking metrics have been identified.
- [ ] Page has been written.
- [ ] Page has been uploaded to the Platform Website.

**Comment by Blivaditis** [comment]
A first step of this card would be to identify the most common (priority) metrics used in the GA powered reports submitted by teams. With that information we can prioritize which metrics to include in this document.

**Comment by AdamOye** [comment]
Closing: Outdated.
