### ISSUE TITLE
Copy edit live Eligibility for VA disability benefits page in Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#82032]
## Issue description
Tracking questions and corrections for page. The next step will be to make changes in Drupal and publish.

---
## Tasks
- [x] Review and track errors (Victoria)
- [x] Review (Randi)
- [x] Review (Sara)
- [x] Update page in Drupal (Sara)
- [x] Copyedit (Sara T)
- [x] Publish (Sara T)
- [ ] Batch questions and changes and share with State Dept for review

## Acceptance Criteria
- [x] Updated content is live on the site

**Comment by moviedosoco** [comment]
Hi @RLHecht this is ready for review. Please see the link below. Thank you.
https://docs.google.com/document/d/1ATlfWPK0QxPp1Ye2rwkD6WjU59XGzlyNAERdhhjo4og/edit#heading=h.gean2mqw18p3

**Comment by saratorres2** [comment]
Copy edits published and ready for State Dept review.

**Comment by moviedosoco** [comment]
@RLHecht As we agreed, this ticket can be closed.
