### ISSUE TITLE
[Frontend] MDT - Editing address does not update data in redux

### ISSUE THREAD

**Issue by bradl3yC** [department-of-veterans-affairs/va.gov-team#8203]
## User Story:  
As a veteran I would like the ability to update my address and have the update saved. 

## Problem: 
With the current implementation of the address card, editing an address does not result in any state change. 

## Tasks
- [ ] _Refactor code on page so the address is updated in redux 
- [ ] _QA completed and passed

## Acceptance Criteria
- [ ] _Address is updated in redux when the change is made in UI

**Comment by bradl3yC** [comment]
being addressed in https://github.com/department-of-veterans-affairs/vets-website/pull/12295
