### ISSUE TITLE
FE + BE | Profile | Maint Period Alerts | Check coverage

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#82051]
## Background
To minimize user impact, we want to add and schedule maintenance windows whenever we are aware of upstream outages that will affect the Profile.

## Tasks
Review the Profile and identify existing and missing maintenance windows.
 - [ ] Identify sections of the profile that are covered by a maintenance window.
 - [ ] Identify sections of the profile that are not covered by a maintenance window.
 - [x] Add document that outlines Profile maintenance windows.
 - [ ]  Create tickets for adding missing maintenance windows.

## Acceptance Criteria
 - [ ] Document and review findings with team.

**Comment by mtcA6** [comment]
@tpharrison do you think this is something Nick could start to tackle to gain familiarity w/the profile codebase?

**Comment by tpharrison** [comment]
Yes - @ariperez is already working on a similar ticket for the My VA team.  Nick may want to reach out to him.

**Comment by tpharrison** [comment]
Notes:
- The config file that stores the list of services in vets-website - `src/platform/monitoring/DowntimeNotification/config/externalServices.js`

**Comment by tpharrison** [comment]
Created a [maintenance windows spreadsheet](https://docs.google.com/spreadsheets/d/1ApEzV8z7NGXs3kNw2HSCjTAb96b4R26Cw9E0TyASw14/edit?gid=39041782#gid=39041782) that can be used to map FE components to maintenance window services.

**Comment by mtcA6** [comment]
Chatted w Tom, adjusting this down to a 3 since we did some work on this already
