### ISSUE TITLE
Handle multiple exposure durations - test through BE

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#82087]
## Issue Description
As a Veteran I want to submit a disability compensation claim inclusive of any dates and locations of potential exposure so that I can ensure any TE conditions I have that resulted from multiple exposures are considered during review of my application.

Reference: [contract](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f2a20b188cd637f53768df1e75683364ab0316ed/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md)
---
## Tasks
- [x] Method to transform Gulf War Hazard details object into Lighthouse Toxic Exposure multiple exposures array
- [x] GulfWar1990, GulfWar1990Details
- [x] GulfWar2001, GulfWar2001Details

## Acceptance Criteria
- [x] Lighthouse generated PDF populates 15E
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Disability-Experience-63dbdb0a401c4400119d3a44/issues/department-of-veterans-affairs/va.gov-team/82087?planning-poker) with Zenhub @christinec-fftc @aurora-a-k-a-lightning @mchae-nava @michael-wojcik @sethdarragile6

**Comment by aurora-a-k-a-lightning** [comment]
dsva slack thread with a sample of the current state of 21-526EZ PDF:
Toxic Exposure 15A, 15B, 15E
https://dsva.slack.com/archives/C04KW0B46N5/p1715790126518869

[form526-2024-05-14 231653 UTC.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2prQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80868d269d5f95f2e6f7fdf9a6fd0addaf700fa6/form526-2024-05-14%2023%EF%80%BA16%EF%80%BA53%20UTC.pdf)
