### ISSUE TITLE
UX team works on infographic for VA News and Digital VA blog post

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#82107]
### Issue Description

**What details are necessary for understanding the specific work or request tracked by this issue?**

An infographic or visual was needed for VA News and DigitalVA blog post on the Streamlined Waiver. 

### Tasks

 **What work is necessary for this story to be completed?**
The UX team

- [x] Calculated a % of the incoming FSR copay applications that are routed to the Streamlined Waiver path
- [x] Coordinated with VA stakeholders on the best way to display this data
- [x] Created an infographic showcasing the 90% and the last page of the SW path 

 **What will be created or happen as a result of this story?**

The UX team

- [x] Calculated a % of the incoming FSR copay applications that are routed to the Streamlined Waiver path
- [x] Coordinated with VA stakeholders on the best way to display this data
- [x] Created an infographic showcasing the 90% and the last page of the SW path

**Comment by HeatherRienks** [comment]
Confirmed with @denisecoveyduc that this has been completed!

**Comment by denisecoveyduc** [comment]
Thanks for everyone's hard work on this one!
