### ISSUE TITLE
Figure out why tagging commits duplicates when automated

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#82110]
## Issue Description
Automating the tagging of commits seems to eventually result in a duplicate tag. The attempt to fetch the "latest" tag results in the 2nd-latest being pulled, and therefore it tries to increment the tag to a tag that already exists. This causes an error that repeats itself until the newest tag is deleted. This results in us having to manually set up the deployment to successfully have a tag to go out on, or having the deploy take a much earlier commit.

---
## Tasks
- [x] Diagnose the cause of the duplicate tag
- [x] Fix the issues to where the tagging works correctly, automated.,

## Acceptance Criteria
- [x] The daily deploy can now go out reliably without worrying about a tagging error.

**Comment by CBonade** [comment]
This has been corrected and is now working as expected.
