### ISSUE TITLE
Investigate lowering AppealsApp 401 Error

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#8212]
## User Story or Problem Statement
How might we lower Appeals Status 401 Errors?

## Goal
Lower 401 Unauthorized errors if possible.

## Background
This error is thrown about [3k times per week](http://grafana.vfs.va.gov/d/000000035/appeals-status?panelId=6&fullscreen&orgId=1).  This error indicates that the user is not authenticated (logged in) before a request to the AppealApp is made from vets-api. In my mind, this is similar to someone jiggling a handle before using a key to unlock a door. It doesn't indicate a problem, just that the user attempted to do something before logging into the service. My only concern here is that we are:
1. possibly presenting users with an option they can't access (unnecessarily frustrating the user)
2. making unnecessary calls to the AppealsApp.

Came out of discovery for https://github.com/department-of-veterans-affairs/va.gov-team/issues/7476
---
## Tasks / Acceptance Criteria
- [ ] Investigate source of errors
- [ ] Fix if relevant

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
My first thought that it's when people bookmark the status page and come back later. But it's looking like that's not it. I tried pasting a URL in an incognito window and I was redirected to the sign in modal without any API requests.

**Comment by annaswims** [comment]
also a result of this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/21207
