### ISSUE TITLE
Generate SLO documentation from template for external services

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#8213]
## User Story or Problem Statement

As an engineer I need to understand if a given service is performing at or below expected performance. 

## Goal

Each major external service has a document outlining SLI, SLO and error budgets as well as any key caveats. These documents are centralized and easily discovered by engineers.

## Objectives or Key Results this is meant to further

O4: All of the Platform's KPIs are easily measured and shared openly
---
## Tasks
- [x] Generate a template in Markdown 
- [x] Inject SLI and SLO data into doc for each service
- [x] Get peer review and merge into documentation folder

## Acceptance Criteria
- [x] Docs exists in the request-timing folder for each service

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
Script and template used in initial `v0.1` documentation is found on [this branch](https://github.com/department-of-veterans-affairs/devops/pull/new/kfrz/slo-docs-draft) in `devops` repo. Subject to change. 

Docs for each service SLO are in [product folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/external-service-monitoring#external-service-performance-monitoring).
