### ISSUE TITLE
[CDP] Review Data Dictionary

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#82134]
## Description

Review data dictionary

## Tasks
- [x] Review data dictionary emailed on 05/01
- [x] Compile list of questions

## Acceptance criteria

- [x] Data dictionary reviewed
- [x] List of questions compiled

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
Data Dictionary Spreadsheet: https://docs.google.com/spreadsheets/d/1JvXUWK8LlcgTksdIvm5VY7NdXyTWd5TDOZpRhsGS8ao/edit?usp=sharing

**Comment by josephrlee** [comment]
Just finished adding all the screenshots and various questions. 

cc: @mgleo @charlottecesana @HeatherRienks

**Comment by mgleo** [comment]
[Data Dictionary spreadsheet](https://docs.google.com/spreadsheets/d/1JvXUWK8LlcgTksdIvm5VY7NdXyTWd5TDOZpRhsGS8ao/edit?usp=sharing) was created and discussed with VHA API team. Sharepoint version of the spreadsheet was sent to Brian Tomlin and Sergio Falcon for their review.
Additional tickets will be created to continue work on this.

@Tom-Davis @HeatherRienks Moved to Validate

**Comment by Tom-Davis** [comment]
Closing as complete.
