### ISSUE TITLE
[DevOps] Create Check-In Experience document for console-created custom resources.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82144]
## User Story
As an engineer, I want to create a document to track the resources I create on-the-fly in AWS so that I can review, audit, and discuss the resources that don't exist in an IaC form.

Include:
- tags

Document:
- CF stacks we need for roles/policies/etc.
- S3 buckets for TF state
- DynamoDB tables for TF state
- etc

## Tasks
- [x] [DevOps] Create a new document in this repository that can be augmented as needed with resources.

## Acceptance Criteria
- [x] Document is created and linked appropriately.
- [x] Document contains current custom resources.
