### ISSUE TITLE
Discovery Research Epic : How might we improve customer satisfaction

### ISSUE THREAD

**Issue by UXCamG** [department-of-veterans-affairs/va.gov-team#82167]
## Background

As the number of users signing into VA.gov for health and other benefits services, there is a need to re-evaluate the approach to providing support to users of VA.gov. In particular, there are a few problems that VA.gov technical support presents:

1. Signing in is the major driver of support issues on VA.gov. While some of these are problems caused by systems managed by VA, the vast majority are related to third party credential providers. Each contact center wants to limit the number of wrong issues coming to their helpdesk and right now we don't have a process in place that gets Veterans the answer they need as quickly as possible.

2. As health related tools start making their way to VA.gov, we are in a gray area of not knowing which groups support which tools on VA.gov. HRC is responsible for MHV support but will they also be MHV on VA.gov support? And if yes, how do we ensure that Veterans get to the right call center for help and don't get frustrated trying to determine which group can support their questions.

3. Through our work solving Veteran issues, we know many of the most recurring user and system generated issues (i.e. user = lost MFA method vs. system = missing information error message). While we have done a decent job of documenting these issue and creating the necessary processes for the Veteran Support Team, VEO Tier 1 Contact Center, and EVSS helpdesk, we could do more to keep more groups updated on these types of errors so that no matter where a user is looking for support, for these known issues, they should be able to find the right answer.

4. HRC was set up to be in charge of support for the Health and Benefits App but does not have a Tier 3 process in place for getting these issues resolved. We need to figure out how to work with other contact centers to get Tier 3 VA.gov technical issues to Veteran Support.

Given the extent of these issues, we believe it is time to do some research to understand what a better phone support experience would look like for users of VA.gov and for the support groups that are managing these issues coming through. We have assumptions of what that process that might look like but we want to validate our assumptions with research internally and externally so we can start making changes to enhance the experience for support groups and users of VA.gov.

Note: While there are certainly things we could do in many places, including new digital tools on VA.gov, we are going to be focused on the phone support experience because that is still where the majority of VA.gov technical support issues come through.

## High Level User Story
As a Tier 2/3 support team, we need to improve customer and employee satisfaction. Our goal is to ensure that our employees (i.e. support agents) and our Veterans are satisfied with our processes, communications, products, and services provided from our contact centers to our Veterans. 

## Hypothesis or Bet
If we conduct research and gather feedback and information from VA support group and users of VA.gov we will be able to identify ways to improve our VA.gov Technical Support processes that will help users get answers to their questions and improve the support experience. 

## Goals
What outcome(s) do we want to see?   

- [x]  Discover how we might interweave tier 1/2/3 processes and communication 
- [x] Identifying areas of opportunity and insights in tier 1/2/3 processes and communication
- [x]  Improved/Enhanced learning materials for tier 1/2/3 agents.
- [ ]  Plans to test a product that will help increase customer satisfaction 

## Issues to create within this Epic

- Develop workshop details in Figma. 
- Share workshop link with support teams. 
- Schedule moderated sessions with Tier 1,2,3 team members
- Conduct and moderate workshops with Tier 1,2,3 managers and agents 
- Synthesize the results of the workshops in Figma 
- Share workshop findings link with Veteran Support team members 
- Design a low fi/high fi prototype in Figma based on findings. 
- Create research plan for concept test of prototype
- Recruit for research sessions/Schedule research sessions
- Create conversation guide for concept test
- Conduct Discovery Research Sessions 30 min conversations. 
- Discovery Synthesis - should be conducted as a team, led by designer. 
- Discovery Research Readout 

## OKR
_Which Objective / Key Result does this epic push forward?_

## How to configure this issue
- [ ] **Labeled with `discovery` and `research` and `team-name`**

**Comment by clantosswett** [comment]
I created an epic for this work but didn't realize this one existed! I am going to close that epic and have added some things here to consolidate into one place. cc: @UXCamG

**Comment by clantosswett** [comment]
@UXCamG and @ATMiddleton I went through the list of issues that were tied to this ticket and remove many of the ones that were in the icebox and kept three open ones that are currently being worked. Once those are closed, let's make sure to close this issue and [start fleshing out this epic for future](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96486) work.

**Comment by UXCamG** [comment]
Now that we know the improvements that we are planning to implement, I have begun desk research on how we might implement and communicate these improvements across teams.  My recommendation is that we focus on a phased approach to organizational change management as we want to effectively keep a pulse check on these improvements and to communicate the changes across teams.

**Comment by clantosswett** [comment]
Plans to discuss during meeting with @ATMiddleton and @UXCamG.

**Comment by ATMiddleton** [comment]
Sub Issues and incomplete tickets migrated to #96486
