### ISSUE TITLE
Data Dictionary Exploration 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#82166]
## Issue Description
Access the CXI data for inclusion/migration of AskVA data to DOMO to complete the Veteran Support dashboard. 

## Tasks
- [x] Obtain access to CXI
- [x] Obtain access to PATS-R data 
- [x] Obtain data dictionary

- 
## Acceptance Criteria
 - [ ] **Scenario: Accessing CXI data**
  - Given access to CXI
  - When obtaining CXI data
  - Then the data should be available for inclusion/migration of AskVA data to DOMO
- [ ] **Scenario: Obtaining PATS-R data**
  - Given access to PATS-R data
  - When obtaining PATS-R data
  - Then the data should be available for inclusion/migration of AskVA data to DOMO
- [ ] **Scenario: Obtaining data dictionary**
  - Given a data dictionary
  - When obtaining the data dictionary
  - Then the data dictionary should be available for inclusion/migration of AskVA data to DOMO
- [ ] **Scenario: Including AskVA data in DOMO**
  - Given AskVA data
  - When including AskVA data in DOMO
  - Then the data should be successfully integrated into DOMO for the Veteran Support dashboard
- [ ] **Scenario: Configuring the issue**
  - Given the issue is configured with a Milestone, Epic, Team, Practice Area, and Type
  - When configuring the issue with appropriate labels
  - Then the issue should be properly organized and categorized for tracking progress
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Lantos-swett, Chanteclaire E. (she/her/hers)
9:20 AM (1 hour ago)
to Joshua, me, Sarifa, Anita, Sarifa, aubrey@thesocompany.com

Hi Josh,

 

My name is Chante and I manage the Veteran Support Team within the Office of the Chief Technology Officer. Our team was recently given access to CXI and specifically to PATS-R data because we are hoping to use PATS-R data to visualize our team’s work as it relates to resolving issues within the VA technical support queue in Ask VA. We have been able to get into CXI and see the data but we currently don’t have a data dictionary and are not sure how to find what we are looking for. I was given your name as someone who might be able to help us make sense of the data. Is this something you might be able to help us with? If yes, I would be happy to set up a time for us to meet and discuss.

 

Thank you in advance for your help and I look forward to learning more soon!

 

Best,

Chante

**Comment by newworld2616** [comment]
Hello Josh,
Thank you for sharing the data dictionary. I have attached the file sample which we pull from Salesforce for our DOMO dashboard. The file includes the file layouts for the data we  need for AVA (ask VA) from PATSR.

 

Best Regards,
Sarifa.

**Comment by newworld2616** [comment]
Lantos-swett, Chanteclaire E. (she/her/hers)
​
Khalilullah, Sarifa O. (oddball Inc);
​+3 others
​
​
​
​
Middleton, Anita T.;
​
aubrey@thesocompany.com
​
Hi Josh,

 

Just to add a bit more detail, the Veteran Support team has a dashboard that visualizes our handling of veteran/customer issues that come through the MyVA411 tier 1 contact center group. This is managed through Salesforce and so the spreadsheet Sarifa shared are the fields we are pulling from salesforce to visualize things like number of cases our team receives, how long those cases are open (how long it takes for us to resolve them), breakdown of the types of cases based on categories/topics/etc, whether or not we are resolving those cases within the identified SLA. I think most of the fields are self-explanatory but I’ve added some description below in case you can provide some help in understanding how we might map that to the data dictionary you shared. But if there are others we could meet with to discuss, also happy to reach out and have that conversation. Thanks!

 

VACX Case: The case identifier (in salesforce it is a string of numbers)     

VACX Case Owner: The group that owns the case

Subject: Short description of the case

Date/Time Opened        

Case Category  

Case Type          

Status: Is the case open, close, in progress, follow up, etc             

SLA Status: Was the case resolved within the SLA            

Age: How long it took for the case to be closed.

SLA Business Days          

Case Outcome: How the case was resolved         

Date/Time Closed          

Last Activity Date/Time

**Comment by ATMiddleton** [comment]
@newworld2616 @clantosswett @ATMiddleton met with Christopher Clemens, Shelby Carl and Tamara Kanteman to discuss viewing and including/tracking AskVA CXI data on Veteran Support DOMO dashboard. 

We were able to determine where we can find relevant AskVA data and defined column headings.

Relevant data can be found on the "Inquiry (iris_inquiry tab)"

Christopher will share a static excel spreadsheet link in Te3ams chat for now for @newworld2616 analysis.  Afterward we can have access to the real time file to include data on the existing DOMO dashboard.

**Comment by clantosswett** [comment]
Closing this issue because we were able to get data dictionary.
