### ISSUE TITLE
 Sprint 20: Logged-in homepage discovery

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8216]
### Order of priorities

1. Finish research review
2. Plan user research/kickoff recruiting

### Logged-in homepage discovery

- [x] Review documents and document insights #7265
- [x] Create research plan #7269
- [x] Create card sort #8230
- [x] Create co-design with veterans exercise #8232
- [x] Create conversation guide #7270
- [x] Kick-off recruiting #7273
