### ISSUE TITLE
QC Initial Domo Report -- Standard Content Engagement KPIs

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#82170]
### Description
This ticket is account for QC'ing the Standard Content KPIs dashboard with the newly create GA4 view. Focus on QC'ing the metrics specifically for changes in the naming conventions, confirm beast modes/charts are functioning and if they aren't identify what is the cause of the issue. 

**Note:** this dashboard is made up of 15 cards, powered by two GA datasets (and one medalia), and uses 12 beast modes. All of that information and more and be found in [this document](https://docs.google.com/spreadsheets/d/1_sFDhS53qmUFg0qePiXDcKn67stzR9yt-ZTkGgrIcO0/edit#gid=721881515). 

### Tasks

- [x] Create duplicate dataset and cards. Once Phil creates new view, route duplicate cards to new view. 
- [x] Follow up with Phil for any changes that need to be made to the dataset. 
- [x] Doing column per column comparison between the UA and the GA4 Views
- [x] Look for and document differences in variable names, formatting, etc.
- [x] Check if event labels, categories, actions -- etc that are used within BeastModes -- we might have to derive this
- [x] Copy report -- Save As -- use new GA4 Dataset -- 
- [x] Set permissions of copied report so it's just available by our team.
- [ ] If we pass these checks -- we can plan to certify that the reports are fresh.
- [x] If data issue, or discrepancy is found, mark in ticket and notify team.
- [x] Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
---

### Acceptance Criteria

- [x] Report has been copied -- using the new GA4 view.
- [x] Notes from QC or potential changes to ETLs have been documented on [this page](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
- [x] All data issues have been flagged, and if needed, another ticket has been created for them. 
- [ ] If data is looking good -- we need to flag as fresh.

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA, @Blivaditis -- can y'all take a pass at adding in tasks on what might be needed to QC Domo reports -- starting with the Content KPIs.

**Comment by Blivaditis** [comment]
Notes from QC: the only metrics missing between the GA4 dataset and the UA one are **product description and page name**. Additionally Christine and I commented in the[ QC record](https://docs.google.com/spreadsheets/d/1oaoXivzL854woEIUzgsPReoKW55Spz2p4S5WI_u_QHQ/edit#gid=0) artifact identifying which additional metrics are needed to recreate beast modes/charts.

**Comment by Blivaditis** [comment]
I think we should make a new ticket highlighting what changes need to be made.

**Comment by Blivaditis** [comment]
ETL has been created, making a new dataset which powers three charts, further testing may be needed. All cards (besides scroll depth) have been converted to the GA4 dataset and are populating with data. The new dataset is producing significantly higher Hits and interactions than its UA counterpart, will look into further for possible solutions. 

 **Theory:** unnecessary events are tracking causing inflated #s

**Comment by johnny-jesensky-adhoc** [comment]
Most of the QC has been completed -- we found a few things we need to validate, and tweak upstream -- that work will be captured as part of [this separate validation ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/83786). 

FYI @ChristineYoungZA, @Blivaditis
