### ISSUE TITLE
Tidy up GA4 View Working Document

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#82172]
### Description
We need to clean up this document so it's up to date, and can serve as the source of truth for our progress on BQ view updates.

- https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=1482641246

Basil and Christine to help with this.

---

### Tasks

- [ ] Christine, Basil, and Phil to connect on the best way to organize the information.
- [ ] Clean-up spreadsheet.

### Acceptance Criteria

- [ ] Spreadsheet has been reviewed, and updated.
