### ISSUE TITLE
 ITF -- Run synchronous check of ITF

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#82179]
# Overview
When in doubt about requirements, always use the [mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1714050769683/e4dffd0f80fc8aca04a773dbe53c0d40fd5f2dde?wid=70-1714662280565) as the source of truth.

This ticket represents the work needed to kick off the synchronous call to retrieve the ITF.   This is a GET to 
`veterans/{veteranId}/intent-to-file/{type}`
https://developer.va.gov/explore/api/benefits-claims/docs?version=current

## Task
- [ ] - Hide work behind a flipper where necessary
- [ ] - Write code for the synchronous API call
- [ ] - Limit execution to 5 seconds (?)
- [ ] - Display corresponding screens as shown in [mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1714050769683/e4dffd0f80fc8aca04a773dbe53c0d40fd5f2dde?wid=42-1714662280565) based upon result

**Comment by danlim715** [comment]
Official change request has been opened with Lighthouse as per this conversation thread in the Lighthouse Slack Workspace in the api-benefits-claims channel:

<img width="662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3573eb124de8dcf17847bbee8e053e31221f5363/image.png" alt="image.png" />

**Comment by aplatt-coforma** [comment]
Based on refinement today, we are going to close this ticket since the V0 does not include front end changes and we won't need retrieve the ITF date.
