### ISSUE TITLE
Discovery work on bundling

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#82184]
Explore the starting point for the flow

## Tasks

- [ ] Add link to discovery space
- [ ] Sync on this either in design sync or separate sync (30 min)

## AC

- [ ] document how Veterans create appointments and how they receive messages regarding appointments
- [ ] add in details to user flow to explain the starting points and contact points between VA and Veterans
- [ ] state explicitly how our application would tie in with appointment bundling
- [ ] add to future state document
