### ISSUE TITLE
Create First Draft of Contact Center Product Guide for View/Modify Dependents (21-686c)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8218]
## Goal
The Contact Center requires documentation on our feature in the event that anything happens, they can review the expected behavior and either resolve the issue immediately or escalate as appropriate.

## Tasks
- [x] Review the [Collaboration Cycle component of the Contact Center Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#contact-center-review)
- [x] Review the [Contact Center Review instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
- [x] Using the [Contact Center Product Guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/self-service-product-guide-template.md), create a first draft 

## Acceptance Criteria
- [x] A first draft of the Contact Center Product Guide has been created for View/Modify Dependents (21-686c) and linked in the feature folder's contact center folder.  (See comment below)

### Next Steps
- Refine guide doc
- Walkthrough full application
  - Make notes for script
- Write transcript
- Record video
  - Record voice over

**Comment by jason-gcio** [comment]
First draft here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/call-center/Product-guide.md
