### ISSUE TITLE
Test Platform Feedback workflow

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#82192]
## Purpose
We haven't seen any responses via this workflow in April.  We've noticed that there appear to be "workflow errors".

Let's investigate to see if there's an issue.

## Tasks
- [x] Try out the workflow
- [x] verify that a result is received.

## Acceptance Criteria
- [x] Confirm that there is or isn't an issue.

**Comment by twoangstroms** [comment]
Though there seems to be zero documentation beyond [this](https://slack.com/help/articles/360055655493-View-workflow-activity-in-Workflow-Builder) about error messages in Slack workflows, these do not seem to be blocking submissions.

I tested this by

1. Entering test text into the feedback workflow and submitting (result: test feedback appeared where it should)
2. Entering test text into the feedback workflow and not submitting (result: refreshing the activity log in Workflow Builder showed the "Awaiting user action/Collect info in a form is awaiting user action"" error status, see images below). Odd: This means a user can't get past the workflow feedback modal window to access Slack channels!
3. Canceling out of the feedback workflow modal window (result: the "Workflow error/Collect info in a form — User closed form without completing" error status).

<img width="675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenZNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0696023a40282eb8fc9f290cd199078d65c6683/Screenshot%202024-05-09%20at%201.35.47%E2%80%AFPM.png" alt="Screenshot 2024-05-09 at 1.35.47 PM.png" />

**Comment by gopixelsgo** [comment]
Interesting. So it sounds like Steps 1 and 3 had outcomes and messaging we'd expect. 
And 2, if I understand correctly, instead of allowing the user to click somewhere outside of the modal and treat that as "close/cancel" as most UI patterns allow, it's a perpetual modal takeover? And in the interim, the error messaging in the Workflow Builder is "Awaiting user action/Collect info in a form is awaiting user action". So at some point a non-submitter might choose to get away from this modal takeover via the escape of their choice (but not the Close button), and that's why the error messaging stays the same in the Workflow Builder, right?

**Comment by twoangstroms** [comment]
That seems to be a totally valid conclusion! Not that you'd know it from Slack documentation. I might file a bug report with them.
