### ISSUE TITLE
Review platform team role type view w/ suitable SMEs

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#82191]
## Purpose
Let's show the platform team view to a few SMEs to get their take and learn what else might be useful to them

## Tasks
- [x] [Identify SMEs](https://vfs.atlassian.net/wiki/spaces/~622b8dc89c3cce0069503238/pages/3225059347/Platform+Insights+Repository+-+SME+feedback+tracker) and [prep for collab + feedback ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3213262857/Platform+Insights+Repository+Reviewing+role+types+w+SMEs)
- [x] Schedule initial chat w/ SME to convey purpose of artifact
- [x] Share with SME, allow them to discuss and/or complete async
- [x] Review their notes
- [x] Repeat for 2-3 SMEs.
- [x] Discuss [learnings](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3240361997/Collective+Feedback+Review+platform+team+role+type+view+w+suitable+SMEs) w/ SDT Team
- [x] make adjustments/note next steps based on decisions

## Acceptance Criteria
- [x] Feedback from SMEs is recorded
- [x] Decisions made from SDT discussion
- [x] this view/next steps reflect learnings

**Comment by gopixelsgo** [comment]
This ticket will roll over to allow time for additional PM feedback sessions.

**Comment by gopixelsgo** [comment]
I updated the following Task wording:
- "make adjustments based on decisions" is now "make adjustments/note next steps based on decisions" 

and Acceptance Criteria wording:
- "this view reflects learnings" is now "this view/next steps reflect learnings"

The reason is that since we are [still gathering feedback](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/81845) from another group (Platform Leadership), and it doesn't make sense to update what they are actively reviewing. The feedback so far has raised some new questions to consider before adjustments can be decided (listed [here](https://vfs.atlassian.net/wiki/spaces/SDT/pages/edit-v2/3240361997#Action-items-from-review)) and there may be other considerations once we hear from the last group.
