### ISSUE TITLE
[SPIKE] How can Veterans access referrals for past appts? 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#82197]
## Tasks

- [ ] Identify options for how Veterans can or want to NAVIGATE to access a referral for a past appointment, upcoming appointment or new referral that needs to be scheduled.
- [ ] Once navigated to that referral, identify options for how Veterans can or want to review it. E.g., just a PDF or a page with content and a PDF (sort of like AVS, for example). 

## AC

- [ ] Document initial thoughts via desk research 
- [ ] Share with team 
- [ ] Create wireframe ticket as next step, if needed
