### ISSUE TITLE
Consider regular backup of database(s)

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#82199]
## Purpose
How might we backup the data should Conf. fail to retain it? 

## Tasks
- [x] [Research topic ](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3166404623/Platform+Insights+Database+backup+protocol)(is this info readily available yet?)
- [x] Learn how to back up/export the database (export is all we've got)
- [x] establish a frequency
- [x] Document process for backup

## Acceptance Criteria
- [x] [Documentation established for how to backup](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3166404623/Platform+Insights+Database+backup+protocol), including frequency guidance
- [x] Confluence space/[Google Drive space established](https://drive.google.com/drive/folders/1VIUsS4edEYiKK0LwdePqBTOx6Pp7gRSs) for housing this
