### ISSUE TITLE
Discuss structure of Insights database 

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#82198]
## Purpose
We need to iron out the coarse IA of the database structure.  

- Essentially, do we want one main database fed by all 3 main feedback types, or do we want to maintain 3 unique databases that feed up to the main one?
  - What are the strengths of each approach?
  - What are the cons?

- Should there be separate Confluence pages for each Qtr's data?  (this would allow for presentation-level items to be posted and shared)

## Tasks
- [x] Schedule team workshop
- [x] prep [artifact for meeting](https://vfs.atlassian.net/wiki/spaces/SDT/whiteboard/3154247681)
- [x] Team workshop
- [x] Capture takeaways:  Decided that we'll put all data into one database

## Acceptance Criteria
- [x] Documented takeaways
