### ISSUE TITLE
IA Tracker: Community Care Appointment scheduling

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#82200]
### Links
- [Overview](https://docs.google.com/document/d/1oeGRJPBvtIF1yr9pQuq6h67XnW8zOl7B0R3tqR-aenA/edit) 
- [81267](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/26?pane=issue&itemId=60595299)

### Work Required
- [ ] Determine my role vs Sara’s role
- [ ] Figure out how to collab with CAIA
- [ ] URLs that fit within the larger structure
- [ ] Entry point clarity for diff circumstances
- [ ] Referral object needs a better title and better information hierarchy
- [ ] Add comments to figma about workflow confusion

**Comment by kristinoletmuskat** [comment]
Realized this is actually Sara's work! I left a few comments in the figma though.
