### ISSUE TITLE
[UX, FE] 10-10EZ - TERA - Remove special characters explanatory text for other toxic exposures field + update error

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#82212]
## Description
During TERA usability research, we uncovered a bug where a user tried to enter multiple other toxic exposures separated by a comma and kept getting an error with no clear explanation as to why. We identified that this was because of the comma so CAIA helped us write a line of text to explain to Veterans how to avoid that error by not entering special characters, but we ultimately want Veterans to be able to enter whatever characters help them best explain their other toxic exposures.

Once VES is ready to accept some special characters for the "other toxic exposures" field, we can remove the text that we added to help Veterans avoid errors due to special characters. The VES team says they will be implementing this change in June 2024 (likely around the 6/10 release date) so once we have confirmation from them that the system can accept special characters, we should remove the extra text that we added to that question.

VES will only accept these 4 special characters: `. ? ! ,` so we will still need an error for any other special characters. That error should read: "You entered a character we can't accept. Remove any special characters other than these: . ? ! ," (Design to verify this with CAIA)

## Tasks
- [x] Update designs on hint text and error text (specifically when entering other characters that are not acceptable)
- [x] Get approval from CAIA on new error text
- [x] Confirm with VES that their system is ready to accept special characters for other toxic exposures
- [x] Remove text on other toxic exposures form field that says "If you're listing multiple toxins or hazards, list them without commas or any other special characters"
- [x] Remove error state that would occur if special characters were entered that says "You entered a character we can't accept. Remove any special characters like commas or dashes."
- [x] Verify that the field is accepting the following characters without any errors: . ? ! , (including end-to-end with VES/Josh F)
- [x] Create an error state for any special characters other than the 4 that VES can accept that reads: `You entered a character we can't accept. Remove any special characters other than these: . ? ! ,`
- [x] Merge update

## Acceptance criteria

- The "Other toxic exposures" field no longer has text stating not to use special characters and it accepts the following special characters without any errors: . ? ! ,
- There is a new error state implemented for any special characters that VES cannot accept.

**Comment by emily-brown34** [comment]
waiting on other changes from VES before we can make this change. let's check back in with them though and see if this is done/when it will be done @aagosto90

**Comment by hdjustice** [comment]
Meena confirmed the additional punctuation was implemented for the TERA "Other" freeform text field!   We should be able to make whatever changes we need to allow for the four items (period, comma, question mark and exclamation mark).

> Yes we have implemented the change to allow some punctuation for the “Other” freeform text field. Following is the regex that we are using ^[a-zA-Z0-9,.?! ]*$ and it should now allow the following period, comma, question mark and exclamation mark.

**Comment by aagosto90** [comment]
Here is the [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=4435-46569&t=P8ToTzh13XozgLoK-1) with the updated design for this other toxic exposures field. We should remove the current hint text and if the user enters a character other than the 4 that VES can accept, we should show the error message in this mockup which has been written and approved by CAIA.

**Comment by hdjustice** [comment]
Testing in RI, confirmed only the four acceptable punctuation is allowed on UI, all others trigger an error message (one example of error message below)
![image](https://github.com/user-attachments/assets/262749ac-ef2e-47c7-83d3-ac88b8001c90)
![image](https://github.com/user-attachments/assets/2faad6cb-c756-4ae6-acd4-fc93cf67c39f)

**Comment by hdjustice** [comment]
Ok to launch!

**Comment by longmd** [comment]
New CAIA-approved error message: `You entered a character that we can't accept. You can use only these characters: . , ! ?`
