### ISSUE TITLE
Update "Getting Help from Platform in Slack" 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#82215]
## Description 
Our Getting Help from Platform in Slack page is outdated to the current process. We will need to update the page. 

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Update page to reflect newest process for submitting a support ticket
- [x] Identify and update other processes that are inaccurate
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
David is already updating the same page with other information in this ticket:

https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/81106

Created this ticket to capture the update of the rest of the page.

**Comment by alyssagallion** [comment]
Work complete. Closing.
