### ISSUE TITLE
Add SR Requirements to Calendly sign up

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#82226]
## User Story
As a Governance team member, I want to be sure VFS teams are meeting SR requirements before scheduling their SR so that we do not have to go through the cancelling/rescheduling process bc they weren't ready.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
VFS teams will sometimes jump the gun a bit and schedule their Staging Review before the product or team is fully ready for the Staging Review. In order to deter this type of behavior, Governance team is betting that by adding the SR requirements to the Calendly sign up for SR, and ask teams to validate that all requirements are met, that teams who are not ready will not proceed with the scheduling. We are hoping that this will lead to less cancellations and rescheduling of Staging Review touchpoints.

## Impacted Artifacts
[Staging Review Calendly event](https://calendly.com/event_types/71688608/edit?return_to=%2Fevent_types%2Fuser%2Fme)

## Tasks
- [x] Explore options in Calendly to see where it might be best to include the SR requirements
- [x] Implement the SR requirements into the [Staging Review Calendly event](https://calendly.com/event_types/71688608/edit?return_to=%2Fevent_types%2Fuser%2Fme). Ensure that VFS teams validate that all requirements are met before scheduling the event
- [x] Test the sign up process with your peer reviewer

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] VFS teams are asked to validate that all SR requirements are met before they can schedule a SR in Calendly 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@erinrwhite there is only 1 place we can add these requirements and it is the details section. I have added it and added another question for them to confirm. Can you [test it out](https://calendly.com/collaboration-cycle/staging-review?month=2024-05&date=2024-05-23) please?

**Comment by erinrwhite** [comment]
@allison0034 confirmed! Looking good!

**Comment by allison0034** [comment]
@erinrwhite thank you! Is it ok to close?
