### ISSUE TITLE
Generate an accessible PDF of the completed 21-22/21-22a for a user to download

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82223]
## Background
When a user completes our Appoint a Representative process, they will have digitally completed a 21-22 or 21-22a form.  At this point, we would like to give them an option to download their completed form.

The backend will need to generate a PDF for download, based on the input received from our Appoint a Rep process.  Some things to consider for this form download:
1. PDFs are typically flattened before a download, which causes them to be inaccessible to those using assistive technology.  How might we generate a PDF that maintains accessibility to all?
   1. Here is a [PDF audit for accessibility](https://drive.google.com/file/d/15JZ6vSoehU22LYvweWNfirkKskPrbFPI/view?usp=sharing) using Adobe's accessibility check tool, which gives an idea of what to watch out for.
   2. Here is some [guidance on accessible PDF generation](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/platform/pdf) if we end up generating the PDF from scratch.
2. PDFs will contain PII which comes with security risks.  How can we maintain security of PII when generating the form and also after the form has been downloaded?  Encryption has been floated as a potential idea.
   1. ~~We may be able to address this with memory, or a "Temp file" in Ruby~~ We'll proceed with the Ruby `Tempfile`.

### Implementation Details
- We have cases where the UI doesn't quite match the form field, for example form [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf) Field 21 is an open input but the UI will present checkboxes for the user to select ([related frontend ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83965)).  In this case, we'd want to populate the open input field with the specific conditions the user authorized/checked, separated by a comma.   Examples:  
   - `Alcoholism and alcohol abuse records, drug abuse records, HIV records, Sickle cell anemia records.` (all selected)
   - `Alcoholism and alcohol abuse records, drug abuse records.` (some selected)
   - `No, they can't access any of these types of records.` (none selected)
- Include a cover page for the form, that reiterates the [next steps](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4311-284570&t=SUzKtJJzHhGy38Ph-4)

## Tasks

- [x] Reach out to other VA developers to understand how PDF generation has been handled in the past and any existing standards around this process
- [x] Understand if other forms that are writing on top of an existing form will work for multi-page forms (are they working with the whole object or individual pages?)
- [x] Analyze the blank PDF and determine what the keys are inside of the PDF to understand what values we can fill in
- [x] Document what keys are inside the 21-22/21-22a PDFs (and what values we can fill in)
- [x] Add blank forms to our vets-api repo
- [x] Get data to populate the request, from the PDF generation endpoint (https://github.com/department-of-veterans-affairs/va.gov-team/issues/82841)
- [x] Build the PDF within a Ruby `Tempfile`
- [x] Generate PDF and send it back to the user
- [x] Fill in dummy/test data to ensure the process works
- [ ] Verify the accessibility of generated PDFs (can lean on our CAIA accessibility partner, Jamie Klenetsky Fay)

## Acceptance Criteria
- [ ] When a user downloads a completed form from the frontend UI, the backend will securely serve up an accessible PDF.

**Comment by oddball-lindsay** [comment]
Notes from Josh:

Looking around the project it looks like we might be using a software package that takes an existing PDF form and allows you to programmatically fill in the data before a download.  If that is the case this ticket probably gets easier and would be a 5.

As far as the ticket goes, there will probably need to be more detail.  I think the first step might be reaching out to other VA oddballers to see how they've handled PDF generation and if they're using that package that fills out existing PDF forms.  If that is the case we should use that to download a different filled out form from the site and check to see if it is accessible.

For the second question we have to worry about the PII in two different places, our api server and the storage of the file we present for download for the user.  Protecting the data on the server shouldn't be a problem, we can write out the PDF to a tempfile that can be deleted as soon as it is uploaded to storage.  The storage also might not be an issue.  If we typically generate files during a web request and serve it to the user immediately then we don't have to store it anywhere and it is not a problem.  If we generate the PDF in a background job and upload it to a place it can be downloaded security is a good idea.  Encryption is a good place to start.  We could also use download links that expire quickly but that depends on how our cloud storage is set up.  There might be more possibilities but they depend on how our cloud storage is set up.

**Comment by oddball-lindsay** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/85497 for

**Comment by oddball-lindsay** [comment]
@opticbob added in some linked resources for accessible PDFs in the description up top :)  

Here's the [Slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1720465582739029) where these resources were offered, if you end up having any questions!

**Comment by opticbob** [comment]
We are going to proceed using a `Tempfile` to generate the PDF.  You can find a slack discussion where we get approval to use that method [here](https://dsva.slack.com/archives/CBU0KDSB1/p1720622127948249)

**Comment by opticbob** [comment]
### 2122 Keys

|Key|Max Length|Type|
|---|---|---|
|"form1[0].#subform[0].VAFileNumber[0]"|"9"|"Text"|
|"form1[0].#subform[0].VeteransFirstName[0]"|"12"|"Text"|
|"form1[0].#subform[0].VeteransLastName[0]"|"18"|"Text"|
|"form1[0].#subform[0].VeteransMiddleInitial1[0]"|"1"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_FirstThreeNumbers[0]"|"3"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_SecondTwoNumbers[0]"|"2"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_LastFourNumbers[0]"|"4"|"Text"|
|"form1[0].#subform[0].DOBmonth[0]"|"2"|"Text"|
|"form1[0].#subform[0].DOBday[0]"|"2"|"Text"|
|"form1[0].#subform[0].DOByear[0]"|"4"|"Text"|
|"form1[0].#subform[0].VeteransServiceNumber_If_Applicable[0]"|"9"|"Text"|
|"form1[0].#subform[0].TelephoneNumber_IncludeAreaCode[0]"|nil, "Text"|
|"form1[0].#subform[0].InsuranceNumber_s[0]"|nil, "Text"|
|"form1[0].#subform[0].Claimants_FirstName[0]"|"12"|"Text"|
|"form1[0].#subform[0].Claimants_LastName[0]"|"18"|"Text"|
|"form1[0].#subform[0].Claimants_MiddleInitial1[0]"|"1"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_NumberAndStreet[0]"|"30"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ApartmentOrUnitNumber[0]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_City[0]"|"18"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_StateOrProvince[0]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_Country[0]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[0]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_LastFourNumbers[0]"|"4"|"Text"|
|"form1[0].#subform[0].Claimants_EmailAddress_Optional[0]"|nil, "Text"|
|"form1[0].#subform[0].Relationship_To_Veteran[0]"|nil, "Text"|
|"form1[0].#subform[0].TelephoneNumber_IncludeAreaCode[1]"|nil, "Text"|
|"form1[0].#subform[0].EmailAddress_Optional[0]"|nil, "Text"|
|"form1[0].#subform[0].Name_Of_Service_Organization[0]"|nil, "Text"|
|"form1[0].#subform[0].Name_Of_Official_Representative[0]"|nil, "Text"|
|"form1[0].#subform[0].Job_Title_Of_Person_Named_In_Item15A[0]"|nil, "Text"|
|"form1[0].#subform[0].Email_Address[0]"|nil, "Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_NumberAndStreet[1]"|"30"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ApartmentOrUnitNumber[1]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_City[1]"|"18"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_StateOrProvince[1]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_Country[1]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[1]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_LastFourNumbers[1]"|"4"|"Text"|
|"form1[0].#subform[0].DateAppt[0]"|nil, "Text"|
|"form1[0].#subform[0].DOBmonth[1]"|"2"|"Text"|
|"form1[0].#subform[0].DOBday[1]"|"2"|"Text"|
|"form1[0].#subform[0].DOByear[1]"|"4"|"Text"|
|"form1[0].#subform[1].V_R_And_E_FILE[0]"|nil, "Button"|
|"form1[0].#subform[1].EDU_FILE[0]"|nil, "Button"|
|"form1[0].#subform[1].LG_File[0]"|nil, "Button"|
|"form1[0].#subform[1].Insurance_File[0]"|nil, "Button"|
|"form1[0].#subform[1].REVOKED_Reason_And_Date[0]"|nil, "Text"|
|"form1[0].#subform[1].Drug_Abuse[0]"|nil, "Button"|
|"form1[0].#subform[1].I_Authorize[0]"|nil, "Button"|
|"form1[0].#subform[1].Alcoholism_Or_Alcohol_Abuse[0]"|nil, "Button"|
|"form1[0].#subform[1].Infection_With_The_Human_Immunodeficiency_Virus_HIV[0]"|nil, "Button"|
|"form1[0].#subform[1].sicklecellanemia[0]"|nil, "Button"|
|"form1[0].#subform[1].I_Authorize[1]"|nil, "Button"|
|"form1[0].#subform[1].SignatureField1[0]"|nil, "Signature"|
|"form1[0].#subform[1].SignatureField1[1]"|nil, "Signature"|
|"form1[0].#subform[1].DateSigned[0]"|nil, "Text"|
|"form1[0].#subform[1].DateSigned[1]"|nil, "Text"|
|"form1[0].#subform[1].DateSent[0]"|nil, "Text"|
|"form1[0].#subform[1].Date_Acknowledged[0]"|nil, "Text"|
|"form1[0].#subform[1].DateRevoked[0]"|nil, "Text"|
|"form1[0].#subform[1].SocialSecurityNumber_FirstThreeNumbers[1]"|"3"|"Text"|
|"form1[0].#subform[1].SocialSecurityNumber_SecondTwoNumbers[1]"|"2"|"Text"|
|"form1[0].#subform[1].SocialSecurityNumber_LastFourNumbers[1]"|"4"|"Text"|

**Comment by opticbob** [comment]
### 2122a Keys

|Key|Max Length|Type|
|---|----------|----|
|"form1[0].#subform[0].RelationshipToVeteran[0]"|nil|"Text"|
|"form1[0].#subform[0].International_Telephone_Number_If_Applicable[0]"|nil|"Text"|
|"form1[0].#subform[0].Telephone_Number_Area_Code[0]"|"3"|"Text"|
|"form1[0].#subform[0].Telphone_Middle_Three_Numbers[0]"|"3"|"Text"|
|"form1[0].#subform[0].Telephone_Last_Four_Numbers[0]"|"4"|"Text"|
|"form1[0].#subform[0].International_Telephone_Number_If_Applicable[1]"|nil|"Text"|
|"form1[0].#subform[0].E_Mail_Address_Optional[0]"|nil|"Text"|
|"form1[0].#subform[0].Veterans_First_Name[0]"|"12"|"Text"|
|"form1[0].#subform[0].Veterans_Last_Name[0]"|"18"|"Text"|
|"form1[0].#subform[0].Veterans_Middle_Initial[0]"|"1"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_FirstThreeNumbers[0]"|"3"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_SecondTwoNumbers[0]"|"2"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_LastFourNumbers[0]"|"4"|"Text"|
|"form1[0].#subform[0].Veterans_Service_Number_If_Applicable[0]"|"9"|"Text"|
|"form1[0].#subform[0].Date_Of_Birth_Month[0]"|"2"|"Text"|
|"form1[0].#subform[0].Date_Of_Birth_Day[0]"|"2"|"Text"|
|"form1[0].#subform[0].Date_Of_Birth_Year[0]"|"4"|"Text"|
|"form1[0].#subform[0].Veterans_Service_Number_If_Applicable[1]"|"10"|"Text"|
|"form1[0].#subform[0].MailingAddress_City[0]"|"18"|"Text"|
|"form1[0].#subform[0].MailingAddress_ApartmentOrUnitNumber[0]"|"5"|"Text"|
|"form1[0].#subform[0].MailingAddress_NumberAndStreet[0]"|"30"|"Text"|
|"form1[0].#subform[0].MailingAddress_ZIPOrPostalCode_LastFourNumbers[0]"|"4"|"Text"|
|"form1[0].#subform[0].MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[0]"|"5"|"Text"|
|"form1[0].#subform[0].MailingAddress_Country[0]"|"2"|"Text"|
|"form1[0].#subform[0].MailingAddress_StateOrProvince[0]"|"2"|"Text"|
|"form1[0].#subform[0].Telephone_Last_Four_Numbers[1]"|"4"|"Text"|
|"form1[0].#subform[0].Telephone_Middle_Three_Numbers[0]"|"3"|"Text"|
|"form1[0].#subform[0].Telephone_Number_Area_Code[1]"|"3"|"Text"|
|"form1[0].#subform[0].Claimants_Last_Name[0]"|"18"|"Text"|
|"form1[0].#subform[0].Claimants_Middle_Initial[0]"|"1"|"Text"|
|"form1[0].#subform[0].Claimants_First_Name[0]"|"12"|"Text"|
|"form1[0].#subform[0].MailingAddress_City[1]"|"18"|"Text"|
|"form1[0].#subform[0].MailingAddress_ApartmentOrUnitNumber[1]"|"5"|"Text"|
|"form1[0].#subform[0].MailingAddress_NumberAndStreet[1]"|"30"|"Text"|
|"form1[0].#subform[0].MailingAddress_ZIPOrPostalCode_LastFourNumbers[1]"|"4"|"Text"|
|"form1[0].#subform[0].MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[1]"|"5"|"Text"|
|"form1[0].#subform[0].MailingAddress_Country[1]"|"2"|"Text"|
|"form1[0].#subform[0].MailingAddress_StateOrProvince[1]"|"2"|"Text"|
|"form1[0].#subform[0].Last_Name[0]"|"18"|"Text"|
|"form1[0].#subform[0].Middle_Initial[0]"|"1"|"Text"|
|"form1[0].#subform[0].Name_Of_Individual_Appointed_As_Representative_First_Name[0]"|"12"|"Text"|
|"form1[0].#subform[0].Specify_Organization[0]"|nil|"Text"|
|"form1[0].#subform[0].Claimants_Date_Of_Birth_Month[0]"|"2"|"Text"|
|"form1[0].#subform[0].Date_Of_Birth_Day[1]"|"2"|"Text"|
|"form1[0].#subform[0].Date_Of_Birth_Year[1]"|"4"|"Text"|
|"form1[0].#subform[0].E_Mail_Address_Optional[1]"|nil|"Text"|
|"form1[0].#subform[0].RadioButtonList[0]"|nil|"Button"|
|"form1[0].#subform[0].RadioButtonList[1]"|nil|"Button"|
|"form1[0].#subform[1].SocialSecurityNumber_FirstThreeNumbers[1]"|"3"|"Text"|
|"form1[0].#subform[1].SocialSecurityNumber_SecondTwoNumbers[1]"|"2"|"Text"|
|"form1[0].#subform[1].SocialSecurityNumber_LastFourNumbers[1]"|"4"|"Text"|
|"form1[0].#subform[1].Provide_The_Name_Of_The_Firm_Or_Organization_Here[0]"|nil|"Text"|
|"form1[0].#subform[1].Provide_The_Names_Of_The_Individuals_Here[0]"|nil|"Text"|
|"form1[0].#subform[1].MailingAddress_City[2]"|"18"|"Text"|
|"form1[0].#subform[1].MailingAddress_ApartmentOrUnitNumber[2]"|"5"|"Text"|
|"form1[0].#subform[1].MailingAddress_NumberAndStreet[2]"|"30"|"Text"|
|"form1[0].#subform[1].MailingAddress_ZIPOrPostalCode_LastFourNumbers[2]"|"4"|"Text"|
|"form1[0].#subform[1].MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[2]"|"5"|"Text"|
|"form1[0].#subform[1].MailingAddress_Country[2]"|"2"|"Text"|
|"form1[0].#subform[1].MailingAddress_StateOrProvince[2]"|"2"|"Text"|
|"form1[0].#subform[1].Telephone_Number_Area_Code[2]"|"3"|"Text"|
|"form1[0].#subform[1].Telephone_Middle_Three_Numbers[1]"|"3"|"Text"|
|"form1[0].#subform[1].Telephone_Last_Four_Numbers[2]"|"4"|"Text"|
|"form1[0].#subform[1].International_Telephone_Number_If_Applicable[2]"|nil|"Text"|
|"form1[0].#subform[1].E_Mail_Address_Of_Individual_Appointed_As_Claimants_Representative_Optional[0]"|nil|"Text"|
|"form1[0].#subform[1].SignatureField1[0]"|nil|"Signature"|
|"form1[0].#subform[1].SignatureField1[1]"|nil|"Signature"|
|"form1[0].#subform[1].AuthorizationForRepAccessToRecords[0]"|nil|"Button"|
|"form1[0].#subform[1].RelationshipToVeteran[1]"|nil|"Text"|
|"form1[0].#subform[1].Date_Signed_Month[0]"|"2"|"Text"|
|"form1[0].#subform[1].Date_Signed_Day[0]"|"2"|"Text"|
|"form1[0].#subform[1].Date_Signed_Year[0]"|"4"|"Text"|
|"form1[0].#subform[1].Date_Signed_Month[1]"|"2"|"Text"|
|"form1[0].#subform[1].Date_Signed_Day[1]"|"2"|"Text"|
|"form1[0].#subform[1].Date_Signed_Year[1]"|"4"|"Text"|
|"form1[0].#subform[1].AuthorizationForRepActClaimantsBehalf[0]"|nil|"Button"|
|"form1[0].#subform[1].Checkbox_I_Authorize_VA_To_Disclose_All_My_Records_Other_Than_As_Provided_In_Items_20_And_21[0]"|nil|"Button"|
|"form1[0].#subform[1].Checkbox_I_Authorize_VA_To_Disclose_All_My_Records_Other_Than_As_Provided_In_Items_20_And_21[1]"|nil|"Button"|
|"form1[0].#subform[2].LIMITATIONS[0]"|nil|"Text"|
|"form1[0].#subform[2].SocialSecurityNumber_FirstThreeNumbers[2]"|"3"|"Text"|
|"form1[0].#subform[2].SocialSecurityNumber_SecondTwoNumbers[2]"|"2"|"Text"|
|"form1[0].#subform[2].SocialSecurityNumber_LastFourNumbers[2]"|"4"|"Text"|
|"form1[0].#subform[2].SignatureField1[2]"|nil|"Signature"|
|"form1[0].#subform[2].SignatureField1[3]"|nil|"Signature"|
|"form1[0].#subform[2].Date_Signed_Month[2]"|"2"|"Text"|
|"form1[0].#subform[2].Date_Signed_Day[2]"|"2"|"Text"|
|"form1[0].#subform[2].Date_Signed_Year[2]"|"4"|"Text"|
|"form1[0].#subform[2].Date_Signed_Month[3]"|"2"|"Text"|
|"form1[0].#subform[2].Date_Signed_Day[3]"|"2"|"Text"|
|"form1[0].#subform[2].Date_Signed_Year[3]"|"4"|"Text"|

**Comment by opticbob** [comment]
**Example of generating a PDF with fake data:**

<img width="877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9TQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bf9fcf38c65daf0e4ddc3cd81a1c2ca763207d1/Screenshot%202024-07-11%20115052.jpg" alt="Screenshot 2024-07-11 115052.jpg" />

**Comment by oddball-lindsay** [comment]
@opticbob Our CAIA accessibility partner just shared this resource [How to create an accessible PDF](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/create-accessible-PDF.md).

You might already be covered with the initial accessibility documentation in the issue description, but sharing for a double check!

**Comment by opticbob** [comment]
@oddball-lindsay The page with Next Steps includes contact info from the find a rep search result.  

On the 2122 we don't have access to that data in the current schema, we just have the VSO name.

On the 2122a we have the full Representative contact details so we could generate the next steps page.

What do you want me to do for the 2122?  Sending the data we need to generate this page will require some more work on the front end.  I'm not sure how difficult that would be to do so, but that data should be close at hand because it will be displayed on the page.

**Comment by opticbob** [comment]
### 2122 Keys In Use

|Key|Max Length|Type|
|---|---|---|
|"form1[0].#subform[0].VAFileNumber[0]"|"9"|"Text"|
|"form1[0].#subform[0].VeteransFirstName[0]"|"12"|"Text"|
|"form1[0].#subform[0].VeteransLastName[0]"|"18"|"Text"|
|"form1[0].#subform[0].VeteransMiddleInitial1[0]"|"1"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_FirstThreeNumbers[0]"|"3"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_SecondTwoNumbers[0]"|"2"|"Text"|
|"form1[0].#subform[0].SocialSecurityNumber_LastFourNumbers[0]"|"4"|"Text"|
|"form1[0].#subform[0].DOBmonth[0]"|"2"|"Text"|
|"form1[0].#subform[0].DOBday[0]"|"2"|"Text"|
|"form1[0].#subform[0].DOByear[0]"|"4"|"Text"|
|"form1[0].#subform[0].VeteransServiceNumber_If_Applicable[0]"|"9"|"Text"|
|"form1[0].#subform[0].TelephoneNumber_IncludeAreaCode[0]"|nil|"Text"|
|"form1[0].#subform[0].InsuranceNumber_s[0]"|nil|"Text"|
|"form1[0].#subform[0].Claimants_FirstName[0]"|"12"|"Text"|
|"form1[0].#subform[0].Claimants_LastName[0]"|"18"|"Text"|
|"form1[0].#subform[0].Claimants_MiddleInitial1[0]"|"1"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_NumberAndStreet[0]"|"30"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ApartmentOrUnitNumber[0]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_City[0]"|"18"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_StateOrProvince[0]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_Country[0]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[0]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_LastFourNumbers[0]"|"4"|"Text"|
|"form1[0].#subform[0].Claimants_EmailAddress_Optional[0]"|nil|"Text"|
|"form1[0].#subform[0].Relationship_To_Veteran[0]"|nil|"Text"|
|"form1[0].#subform[0].TelephoneNumber_IncludeAreaCode[1]"|nil|"Text"|
|"form1[0].#subform[0].EmailAddress_Optional[0]"|nil|"Text"|
|"form1[0].#subform[0].Name_Of_Official_Representative[0]"|nil|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_NumberAndStreet[1]"|"30"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ApartmentOrUnitNumber[1]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_City[1]"|"18"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_StateOrProvince[1]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_Country[1]"|"2"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_FirstFiveNumbers[1]"|"5"|"Text"|
|"form1[0].#subform[0].Claimants_MailingAddress_ZIPOrPostalCode_LastFourNumbers[1]"|"4"|"Text"|
|"form1[0].#subform[0].DOBmonth[1]"|"2"|"Text"|
|"form1[0].#subform[0].DOBday[1]"|"2"|"Text"|
|"form1[0].#subform[0].DOByear[1]"|"4"|"Text"|
|"form1[0].#subform[1].Drug_Abuse[0]"|nil|"Button"|
|"form1[0].#subform[1].I_Authorize[0]"|nil|"Button"|
|"form1[0].#subform[1].Alcoholism_Or_Alcohol_Abuse[0]"|nil|"Button"|
|"form1[0].#subform[1].Infection_With_The_Human_Immunodeficiency_Virus_HIV[0]"|nil|"Button"|
|"form1[0].#subform[1].sicklecellanemia[0]"|nil|"Button"|
|"form1[0].#subform[1].SocialSecurityNumber_FirstThreeNumbers[1]"|"3"|"Text"|
|"form1[0].#subform[1].SocialSecurityNumber_SecondTwoNumbers[1]"|"2"|"Text"|
|"form1[0].#subform[1].SocialSecurityNumber_LastFourNumbers[1]"|"4"|"Text"|

**Comment by opticbob** [comment]
### 2122a with Next Steps page

<details>
[2122a.PDF](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmo3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c03b201c8f10ad372937de2cef7142cec6e4496/2122a.PDF)
</details>

**Comment by oddball-lindsay** [comment]
Next steps page is good to go, can explore higher fidelity visuals (to better match the frontend) in a future ticket.

**Comment by opticbob** [comment]
Update:
Currently writing tests that directly compare correct PDFs and that match specific values within the PDFs.

**Comment by opticbob** [comment]
Update:
I'm fixing the final two tests on this ticket and it'll be ready for review.
