### ISSUE TITLE
[CST] Allow Veterans to submit multiple files at different times for the same 1P request

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#82239]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to submit files at different times for the same 1P request
**_So that_** if I add something and then decide later to add something else, I can do that -- OR if I add a file and I want to "save" my progress so that I can return later to add another file, I can do that.

---
## Background Context

Currently, when a user uploads files for a 1P request and clicks "Submit files for review", the request is closed and the status is changed to `SUBMITTED_AWAITING_REVIEW` and in the UI the request is closed and the user can no longer access it to add more files.

<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenl4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cdf3da10cfcfcdad09820d216e072aec2e5ae94/Screenshot%202024-05-02%20at%205.34.11%E2%80%AFPM.png" alt="Screenshot 2024-05-02 at 5.34.11 PM.png" />

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- How long do Veterans have to add more evidence to a tracked item? Can they do it once the status changes to `INITIAL_REVIEW_COMPLETE`?

## Tasks
- [ ] _Define a user experience that allows Veterans to add files in multiple sessions_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by skylerschain** [comment]
@jacobworrell Moving this to "New issues" so that we can refine it. We should discuss whether this is still relevant.
