### ISSUE TITLE
UX & UI changes needed for TE rollout: finalize with input from CAIA and create implementation tickets

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#82236]
## Overview
See [Identify UX & UI changes needed for TE rollout#81457](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/81457) for the first part of this. 

This ticket captures next steps after getting guidance from CAIA

- [x] incorporate [guidance from CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82234#top) on content
- [x] May need to adjust approach based on [engineering discussion of how to handle versioning for in-progress forms](https://dsva.slack.com/archives/C04KW0B46N5/p1714153244391809?thread_ts=1714153221.485989&cid=C04KW0B46N5)
- [x] Meet with Engineer to discuss creating discovery or implementation ticket
    - [x] [Toxic Exposure 1.1: Add Alert to Review and Submit Page#85579](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85579)
    - [x] Resume saved application / "continue your application" alert
- [x] sync with team Carbs - might be already working on it? - [notified Carbs UX team members in Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1714489693574319?thread_ts=1713994170.557709&cid=C053UDWMH7U)
- [x] 

===

[Working section in Figma](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=1887-13143&mode=design&t=38YJW9bnENaMgmsi-11)

## Acceptance Criteria
- [x] incorporate [guidance from CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82234#top) on content
- [x] Meet with Engineer to discuss creating discovery or implementation ticket

**Comment by mengA6** [comment]
While the engineering approach for versioning in-progress forms still needs to be sorted out, I moved this to in progress since [CAIA just started providing content guidance](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82234#top). There's still more I need them to clarify.

**Comment by Kate-allbee** [comment]
[Discovery ticket created](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85695)

[Implementation ticket created](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85579)
