### ISSUE TITLE
[HCD] Document errors in one location

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#82249]
## Value Statement

**_As a_** team member

**_I want to_** have one place to check existing and proposed error messages

**_So that_** I can QA our products more efficiently

---

## Background Context

Right now, error messages are spread across various sources, from Github developer docs, to Github CSoT (and in within different areas of the CSoT documents), to multiple screens in FIGMA. There isn't one clear working source of truth for our error messages. Determining one best place to document errors will make it easier for the team to develop and QA our products.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] A single CSoT is created for each of our forms
- [ ] All current error messages are captured within the CSoT
- [ ] Teammates (developers), collaborators (CAIA), and stakeholders (enablement team) are able to access to the CSoT

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@jstrothman 

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] Decide on the best way to document and display error messages

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] CSoT is created and up-to-date with our error messages
- [ ] Access to CSoT is available to relevant parties

**Comment by anniebtran** [comment]
(ignoring for now)
