### ISSUE TITLE
Implement Backup Submission Flow 526 Lighthouse Submissions

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#82245]
## Issue Description
When 526 is cutover from using EVSS to Lighthouse APIs, our current mechanism for generating a PDF in backup submissions will no longer function. The Backup submission needs to implement an alternate path based on the Primary submission target API

---
## Tasks
 - [ ] Implement backup submission that generates PDF using code added by PR [#16411](https://github.com/department-of-veterans-affairs/vets-api/pull/16411) Ticket #80773
 - [ ] implement spec tests new backup submission path
 
## Acceptance Criteria
 - [ ] Backup submission updated to support diverging PDF generation
 - [ ] 100% Passing spec tests
 - [ ] 90% testing line coverage of new code
 

Breadcrumbs:
- [Benefits Claims Service Implementation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_claims/service.rb) 

- [Disability Compensation Claims Documentation](https://developer.va.gov/explore/api/benefits-claims/docs?version=current)

**Comment by SamStuckey** [comment]
[It looks like the flipper logic is all in place in the backup submission processor](https://github.com/department-of-veterans-affairs/vets-api/blob/ef27d077f57735b8a01ac4131d0816024e459b5a/lib/sidekiq/form526_backup_submission_process/processor.rb#L346).  I think all we need to do here is implement the logic you've linked above in [this API provider factory](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/disability_compensation/providers/generate_pdf/lighthouse_generate_pdf_provider.rb).  TL;DR @aurora-a-k-a-lightning did the hard stuff, we just need to flesh out the API provider and test.

**Comment by tblackwe** [comment]
nice. ty for the analysis Sam

**Comment by SamStuckey** [comment]
WIP DRAFT PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/16876

**Comment by SamStuckey** [comment]
HAND OFF: @tblackwe is taking this over due to an increased code yellow work load

**Comment by SamStuckey** [comment]
[For posterity this slack thread has a bunch of useful context about how to test](https://dsva.slack.com/archives/C04U3EDUR3M/p1717626674780609)
