### ISSUE TITLE
Unbound - Conduct Initial Risk Assessment

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#82250]
## Description
In previous discussions, it has been expressed that with both the rollout of the AL2 version of Unbound, and the rollout of the Unbound vulnerability fix, there is a risk of a potential outage when these updates are made. We need to understand this risk in more detail in order to ensure that we take proper precautions to mitigate those risks, and if unavoidable, inform all relevant parties of the risks and expectations.

---

## Tasks
- [x] Conduct team discussion to determine the following answers
  - [x] Will these updates cause a risk of an outage to production or key production resources/services?
  - [x] Will these updates cause a risk of an outage to platform or key platform resources/services?
  - [x] Will there be any interruption to services that Veterans normally interact with on the site?
  - [x] Is there any risk for outages with external services and the flow of data to/from those systems?
- [ ] If YES to any of those questions - Create ticket to Document a Risk Mitigation Strategy

## Acceptance Criteria
- [ ] Discussion has taken place and team has agreed that there is no risk, or a risk mitigation strategy ticket has been created

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/devops/blob/52bcf3c708f1fe7c62fdaf5a6ca1dc0b40be85b9/ansible/applications/config/default.yml

Create:
https://github.com/department-of-veterans-affairs/devops/blob/52bcf3c708f1fe7c62fdaf5a6ca1dc0b40be85b9/ansible/applications/config/unbound.yml
