### ISSUE TITLE
Discovery Spike: Optimize Looker Dashboard for Mobile Team

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#82253]
### Description
This task is to outline the work needed to reduce the high cost, and slow performance of the Mobile Team's Looker report. The costs associated with the Looker report have increased in recent months, so this has become a larger priority. 

More background on this issue can be found here: 
- [BiqQuery Governance Plan & Cost Controls](https://vfs.atlassian.net/wiki/spaces/AT/pages/2983821313/BiqQuery+Governance+Plan+Cost+Controls)

**Looker Dashboard**
- [Flagship Mobile Monthly Report](https://lookerstudio.google.com/reporting/e28cd59a-b2e5-4f29-8ae4-a4eea6d23f9c)

This ticket is primarily to break out the work needed to address this, which will mostly involve data engineer/data pipeline work in BigQuery.  

_Meeting scheduled with Don McCaughey on Wednesday, August 28th._

---

### Tasks

- [x]  Outline required tasks needed to move the Mobile Team's Looker report off of the raw GA4 table, (which is the root cause of performance and cost inefficiencies).
- While general high-level tasks are known -- the goal of this ticket is to break out as many actionable steps as possible.
- [x] Identify metrics, (cost, performance, etc.), that we can measure the success of this work before changes were made, and _after_. 
 - Likely candidates include monthly costs tied to report, bytes processed, job duration, etc.
- [x] Review steps, any mobile-team dependencies, and confirm with Ray and Mobile Team.
- [x] If possible, identify realistic timeline of when changes could be implemented and live.
- [x] Create Github tickets needed for follow-up work.

**Key Next Steps**
- Created stubbed-out queries that point to Mobile GA4 table.
- Build a new base table for them to query.  
- They will rewrite the queries that power their reports using the new base query.  (columns names will be kept the same as what they are using now to make it easier for them to make the transition).
- Meet with Mobile Team to walk them through the above.

### Acceptance Criteria

- [x] Data engineering tasks identified for optimization.
- [x] Github tickets created for future work created and refined. -- New Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/93505
- [x] Success metrics have been identified, and documented.

**Comment by johnny-jesensky-adhoc** [comment]
Metrics to report on the dashboard that we can identify from BigQuery's job explorer.

Can determine a monthly average of the following, using a job label 
- looker_studio_datasource_id: 20942740-f529-4e4c-9bfc-26e7b3cd9bd7
- requestor: looker_studio
- looker_studio_report_id: e28cd59a-b2e5-4f29-8ae4-a4eea6d23f9c

**Metrics**
- Bytes Processed, (might be able to use this to determine the cost)
- Duration of jobs (ms)
- Total Slot time (ms)

**Comment by johnny-jesensky-adhoc** [comment]
This ticket is going to roll into the next sprint. Phil was out for a good chunk of this sprint, and needed to prioritize helping with the audit, and a few other checks in BigQuery.

This remains a top priority, so will continue to be the focus next sprint.

FYI @jwoodman5, @dorseypa1

**Comment by johnny-jesensky-adhoc** [comment]
Hi @raywangoctova  -- I just connected with Phil on this, so wanted to provide an update on where we are with this:

- We're aiming to have new stubbed out queries in BigQuery that the Mobile Team can leverage by the end of this week, (targeting _Friday, September 30th_). These queries would essentially be able to replicate how we pull in GA4 data from our own VA.gov Properties -- which will provide them a smaller, more efficient, and ultimately less expensive, way to pull in the GA data they need to power their Looker report.
- As a next step, we have time scheduled with some of their team _next_ _**Wednesday, October 3rd.**_ The goal for that time is to walk through the queries we have built, and outline what steps they'l need to take to hook these queries and tables up to power their Looker report.

Please let us know if you have any questions. I have included you on the follow-up meeting with Mobile next week. 

FYI @dorseypa1

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 -- FYI, I created a new ticket for us to work with Mobile to implement some of the work around them subbing our their queries that will point to our new table/view for them.

- [Implementation of Looker Enhancements with Mobile Team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93505)

We will very likely pull this into next sprint.
