### ISSUE TITLE
Update Form name for 'Form 40-0247 - Presidential Memorial Certificate'

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#82252]
### Description
This task is to update the name of the 40-0247 form in BigQuery from - 'Form 40-0247 - Github Issue Tickets' to 'Form 40-0247 - Presidential Memorial Certificate'. Given the changes will need to be done in BigQuery -- this will likely be a Phil task.

- Request in Github comment -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76372#issuecomment-2085673201

---

### Tasks

- [x] Update name of form in BigQuery
- [x] Confirm form name update is showing up in Domo
- [x] Reply back to team letting them know the name change has been completed.

### Acceptance Criteria

- [x] Form name reading,, **Form 40-0247 - Presidential Memorial Certificate'** in Domo.

### Reviewer
- Basil or Christine

**Comment by dorseypa1** [comment]
We actually have the form name as 'Form 40-0247 - github issue tickets', the 0427 of this ticket is 0247 in the original.  Can someone confirm which is correct?

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1  - Yes -- let me confirm, may have been a typo on my part.

**Comment by dorseypa1** [comment]
Also, the description is still 'Github Issue Tickets'.  Should that be changed to 'Presidential Memorial Certificate'?

**Comment by dorseypa1** [comment]
I updated the title.  If you decide that the definition also needs to be updated let me know.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks Phil -- yes, I would imagine so. I'll pull this into the current sprint, as the lift was so light and the work, (apart from validation), is pretty much done.

FYI @dorseypa1

**Comment by johnny-jesensky-adhoc** [comment]
@CatherineHughes202, @tbaker1026 Hi both -- confirming that we have renamed the form named to read **'Form 40-0247 - Presidential Memorial Certificate'** on the Forms KPI dashboard as requested -- thanks!

<img width="1111" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/147662408/761552c9-dc97-4588-b11a-ed27837209a3">

FYI @dorseypa1
