### ISSUE TITLE
Collaboration Cycle for [IIR, Veteran New Account Flow within Authenticated Experience, Welcome Pathway V1]

### ISSUE THREAD

**Issue by oddballpete** [department-of-veterans-affairs/va.gov-team#82257]
### VFS team name

IIR

### Product name

Veteran New Account Flow within Authenticated Experience

### Feature name

Welcome Pathway V1

### GitHub label for team

IIR

### GitHub label for product

tbd

### Public DSVA Slack channel for VFS team

#iir-product-teams-public

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

April 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://docs.google.com/document/d/1gbBknW1NDSGFqCZLEQrrlrCCwhTHolrTw6Ef3Vfg_R0/edit?usp=sharing

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C05RJS5DANT/p1714748068392679)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [x] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [x] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [x] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715019181472/206d1983971576ee7696c1984666185a2fbff545?sender=u82254af9423cfa236f383306)

Not required, but nice to have:
- [ ] Wireframes

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [x] [Design Intent Slack thread with VFS team](https://dsva.slack.com/archives/C05RJS5DANT/p1715271793947539)
- [x] Meeting date/time: May 14th at 3:30pm ET
  
##### Governance Team actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/t6UqwnpAEAfWiVwWYspzz2FN0hV8d31s7DrJVXT_opdTlFy-uUwdxHyvRdeg_miM.a8JNOA9Zlf4pLof6)
  - Passcode: `^90jX$LS`
- Accessibility
  - [x] Feedback ticket attached
  - [ ] No feedback
- Design
  - [x] Feedback ticket attached
  - [ ] No feedback
- IA
  - [x] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [ ] [Finalized design prototype or mockup](https://www.figma.com/design/CertVj7cu66kFv9TnseR30/Veteran-Onboarding?node-id=300-11104&t=Ow7esQ4gUlPtOyqr-0)
- [ ] Specify which pages are included in the review: Prototype (Design Ticket # 803)
- [ ] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/research%20plan%202024.md)
- [ ] [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-onboarding/conversation%20guide.md)
 
**Content artifacts**
  
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
- [ ] [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83402)

**IA artifacts**

- [ ] Please include a [link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83402) to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C05RJS5DANT/p1720545927149979)
- [x] Meeting date/time: ~~Monday, July 22, 2024 at 3:30PM ET~~ Tuesday, July 30, 2024 at 3:30 p.m. ET

##### Platform actions

* Accessibility
  * [x] Feedback ticket attached
  * [x] No feedback
* Content
  * [ ] Feedback ticket attached
  * [ ] No feedback
* Design
  * [x] Feedback ticket attached
  * [ ] No feedback
* IA
  * [x] Feedback ticket attached
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/TQ39pB6g7daHck3pdJVz4Xpxbxfpby5OxucXECzI7as51BdLaMpH-oF9i_OaZRyW.K3rLofOUgRmt4LWx
  - Passcode: *q@gu9qi
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/93876](url)

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/93963](url)

</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

#### Required artifacts
  - [x] **URL(s) to review the product**
    - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
    - https://staging.va.gov
    - https://staging.va.gov/my-va/welcome-va-setup/review-information/contact-information
    - https://staging.va.gov/my-va/welcome-va-setup/review-information/contact-information/edit-mobile-phone
    - https://staging.va.gov/my-va/welcome-va-setup/review-information/contact-information/edit-email-address
    - https://staging.va.gov/my-va/welcome-va-setup/review-information/contact-information/edit-mailing-address
    - https://staging.va.gov/my-va/welcome-va-setup/review-information/confirmation
    
    - List pages, sections of pages, and/or user flows impacted by this work.
    - When a net new LOA1 user logs in they will be greeted with a Welcome to MyVA modal that gives them an idea of what they can expect from MyVA. This can be dismissed and will not show again due to the 'user creation date' at `initial sign in` being tracked under Profile.
    - When an authenticated LOA3 user lands on MyVA they will be prompted with the 'You have missing contact info' (if applicable) and the link to the form where they can edit their mobile phone, email address, and mailing address.

  - [x] **Drupal or Staging URL for updated primary entry point**: the main way Veterans will access the tool through site navigation (not search)
  https://staging.va.gov

  - [x] **Test users and scenarios (when applicable)**
    - Store [test user information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md), passwords, and tasks in a `.md` file in the va.gov-team-sensitive repository. 
    - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/welcome-to-myva-test-users.md
    - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
    
  - [x] **Link to Sitewide CAIA intake ticket, if applicable.**
  https://github.com/department-of-veterans-affairs/va.gov-team/issues/95524
  https://github.com/department-of-veterans-affairs/va.gov-team/issues/95525
  - [x] **Completed accessibility testing artifact**: [see instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).
  https://github.com/department-of-veterans-affairs/va.gov-team/issues/95851
  - [ ] **QA Artifacts**: artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
    - [x] Regression test plan - we will disable the feature toggle, `veteran_onboarding_show_to_newly_onboarded` if any issues arise
    - [x] Test plan - enable feature toggle `veteran_onboarding_show_to_newly_onboarded` for X% of users, increasing to 100%
    - [X] Coverage for References - Functionality verified with test users
    - [X] Summary (Defects) reports - N/A 
    - [ ] E2E tests
    - [x] Code coverage - no new backend functionality is required
    - [x] Endpoint monitoring playbook - there are no new endpoints this code interacts with.
    - [x] Logging silent failures - this code does not introduce any new backend interactivity with the site, no chance for a silent failure

##### Platform actions
- [x] Slack thread with VFS team: https://dsva.slack.com/archives/C05RJS5DANT/p1731616360702219
- [x] Meeting date/time: **Dec 5, 2024 at 3.30 PM ET**

#### Not required, but nice to have artifacts
  - [ ] **Content source of truth**: link to CAIA Content feedback, such as a content source of truth.
  - [ ] **Information Architecture spec**: link to CAIA IA feedback, such as an IA spec.
##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/WBtxLNpC8ObM84u0bdo7HGMYBDM9ySz8c84vzZRdFyQz4STeUsZB2mVc3U-aADs.aB7KtnDuDiwf6EVk)
  - Password: `Lb+SSjP3`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [x] Share ServiceNow ticket number here: ______
- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
[https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1965](url)
#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by KKufalk13** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715019181472/206d1983971576ee7696c1984666185a2fbff545?sender=u82254af9423cfa236f383306

**Comment by shiragoodman** [comment]
@KKufalk13 please be sure to link artifacts in the ticket where specified, and not in the comments. My team may not see if if it's only available in the comment section.

**Comment by erinrwhite** [comment]
Went ahead and added the link into the ticket ahead of our call today @shiragoodman @KKufalk13

**Comment by AdamKing0126** [comment]
The new functionality is enabled for the following users.  Please find the passwords in [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)
vets.gov.user+0@gmail.com
vets.gov.user+1@gmail.com
vets.gov.user+30@gmail.com
vets.gov.user+31@gmail.com
vets.gov.user+32@gmail.com
