### ISSUE TITLE
[CONTENT]  Update Health Service Library with content related to External Hyperlinks [Content]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8225]
## User Story or Problem Statement
As a Content writer, I must have a full understanding of areas of writing, so I can better understand the LOE and approach of using the data for automation and input.

## Goal
_Perform update of Health Service Library to include external (National) hyperlinks and improved writing _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Tasks
_Complete review of VISN-19, Systems and clinics and estimate ROM:_
- [ ] Update HSL content with new language for Hyperlinks
- [ ] Update any needed language for final copy
- [ ] Provide list of Hyperlinks to be used in code.
- [ ] Upload final copy into Google drives.

## Acceptance Criteria
* Update HSL content with new language for Hyperlinks
* Update any needed language for final copy
* Provide list of Hyperlinks to be used in code.
* Upload final copy into Google drives.
