### ISSUE TITLE
Move to new FMB form intro page: Apply to use transferred education benefits

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#82261]
## Description
We need to move this page from the Veteran benefit hub to the family member benefit hub: [Apply to use transferred education benefits](https://www.va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/introduction)

## Tasks

- [x] KOM: [Find product team ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93259)
- [ ] Product team: create a ticket in their backlog for the URL/breadcrumb change
- [ ] KOM: Create redirect ticket
- [ ] DB, KOM: Align on date for redirect
- [ ] KOM: Confirm crosslinks direct to new URL
- [ ] KOM: Confirm new URL, navigation, and crosslinks

## Criteria

- [ ] Correct breadcrumb, left navigation, and URL
- [ ] Crosslink from the Veteran left navigation directs to the new family member page
- [ ] All links in Drupal are updated to direct from old node / URL to new node / URL

**Comment by aprocik1** [comment]
Update from 8/19 weekly sync with OCTO: Mikki is working with the product team to determine our scope of work for this form intro page. Here are possible options: 

- No scope: The product team won't "move" their form intro page into the FMB hub right now
- Small scope: The product team will update the breadcrumb and URL
- Large scope The product team will update the breadcrumb and URL, in addition to the H1 and process list pattern

**Comment by kristinoletmuskat** [comment]
We've been unable to find the product team that owns this, so it's gonna go into the backlog.

**Comment by kristinoletmuskat** [comment]
Actually, icebox!

**Comment by kristinoletmuskat** [comment]
We found the product team -- Clay Holcomb from the My-Education-Benefits team, from AFS (contractor name). We are holding off on asking them to make this change for now until the issues with the duplicate 5490 are resolved.

**Comment by mnorthuis** [comment]
Form was moved
