### ISSUE TITLE
[IA] Logged-in homepage: Create an inventory of logged-in tools on VA.gov

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8226]
## Background

We need an inventory of the logged-in tools available on/planned for VA.gov for a couple of reasons so we can make sure we are accounting for all tools and tasks as we rethink the logged-in homepage and navigation.

## Tasks

- [ ] Review [Mikki's inventory](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/Mikki's%20tools%20list_4.21.20.xlsx)
- [ ] Review [Steve's eBenefits migration roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/roadmap.md) to make sure we account accordingly for features that are in the pipeline
- [ ] Create updated inventory that accounts for all existing and projected logged-in tools

### What to includes in the spreadsheet

- Product/Feature Name
- Description
- Auth/Unauth (I realize the focus of this issue is a "logged-in tools" inventory, but looking at Mikki's spreadsheet, it seems there are some tools considered unauth that we'll want to give some thought to)
- Phase (eg. Explore, apply, track, manage)
- Related benefit, if applicable, or location (eg. profile)
- Current URL (we can use **Not Live** if it's something in progress)

## Acceptance criteria

- [ ] Completion of logged-in tool inventory

**Comment by andaleliz** [comment]
@Samara-Strauss, I'd like to better understand what information will be most helpful to the team for this inventory list. At this stage, it feels like the primary purpose of this work is #2 listed in the description.  Based on Mikki's spreadsheet, I'm thinking a table (spreadsheet?) with the following columns would be helpful:

- Team
- Product/Feature Name
- Description
- Auth/Unauth
- Phase (love this, esp. as we consider the onboarding experience)
- Hub/Grouping
- Current URL (we can use **Not Live** if it's something in progress)

Thoughts?

Her list looks to be very comprehensive, which is great news for us. I wish this kind of inventory could live in a single place for all to access...

**Comment by Samara-Strauss** [comment]
> Her list looks to be very comprehensive, which is great news for us. I wish this kind of inventory could live in a single place for all to access...

Ditto. Maybe someday we'll have a tool that will allow us to do that!

> At this stage, it feels like the primary purpose of this work is #2 listed in the description.

Yes, this is so we know what tools we need to account for based on whatever benefits someone has. There are a lot, so we need to make sure everyone is working from the same frame of reference for this project.

> I'm thinking a table (spreadsheet?) with the following columns would be helpful:

I think this looks good!

- What is "phase?"
- URL: We should include features that live on MHV and eBenefits and not only the VA.gov tools. 
- Perhaps this overlaps with URL, but I would be interested in a category that defines whether we have an integration with tool data on VA.gov or not. Example: We have an integration with prescription info even though prescriptions don't live on VA.gov. On the contrary, we don't (yet) have a payment history integration, so we could only link to that info instead of showing a payment widget.

**Comment by andaleliz** [comment]
> What is "phase?"
It speaks to phases in the user journey (taking this from Mikki's spreadsheet).  Not a 1:1 but in her sheet options are: Explore, Apply, Support, Manage, Track.

An integration column makes a ton of sense. I'll need some guidance to track this info down once I get started on this - will be sure to reach out when I'm ready.

**Comment by Samara-Strauss** [comment]
Re: phase — got it! Sorry, I prob glossed over that when I looked at Mikki's spreadsheet!

Re: the integration stuff — this should be pretty easy to tell on some level. Basically, if we have a widget or tool for the information, we have an integration that supports it. There's almost a 1:1 relationship between tools/statuses that live on VA.gov and data with which we have an integration, but not 100%. Secure messages and prescriptions are the notable exceptions.

**Comment by andaleliz** [comment]
Got it, that makes sense.  I don't think this will take too long to complete once there is time to focus on it.

cc @sshein for awareness

**Comment by Samara-Strauss** [comment]
@andaleliz I've moved this out of the requirements for this discovery activity, though if there was time for it, that would be great :)

**Comment by Samara-Strauss** [comment]
Gonna keep this ticket but remove it as part of the logged-in homepage redesign. I think what we actually need for V1 is a solid understanding of the functionality we know we're putting on the new LIH, which is essentially some of the stuff that lives on My VA now. I'm going to create another ticket for an audit that focuses on that information so Tressa will know what information to consider in her designs.

**Comment by Samara-Strauss** [comment]
Old ticket, no longer applicable. Closing.
