### ISSUE TITLE
Move OCTO feedback after Governance feedback at DI and MPR meetings

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#82276]
## User Story
As an OCTO practice area lead, I want to focus more on why teams made the decisions they did with their product and less on the elements of the product itself so that Governance team can take the lead on providing UI feedback.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
At the 5/3 1:1 between @humancompanion-usds and @shiragoodman , Matt suggested that OCTO feedback at Design Intent and Midpoint Review be shifted to the end of the meeting. This would allow Governance practice area specialists for design, a11y, IA and content to share their feedback first.

As OCTO Design Lead for Platform, Matt would like to begin to shift his role in these meetings so that he is asking the team why the team decided on _this_ design, and ask they what they're not covering in the overall experience... ie service design. Governance team has been instructed by Platform leadership to not question the experience, and instead focus more on the UI the team has chosen. However, as an OCTO lead, Matt is able to question the veteran experience and why decisions were made. 

## Impacted Artifacts
[Design Intent - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775973945/Design+Intent+-+During+the+Meeting)
[Midpoint Review - During the Meeting (Synchronous) ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous)

## Tasks
- [x] Update the instructions so that OCTO leads (not just Matt  - any Platform/Practice Area lead for OCTO) are called on last, after all Governance team members have provided their feedback.
   - [Updated Design Intent step 5](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775973945/Design+Intent+-+During+the+Meeting#Step-5:-Practice-area-feedback)
   - [Updated Midpoint Review step 5](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous#Step-5%3A-Practice-area-feedback) 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team members provide their feedback before OCTO-DE leads provide feedback at both Design Intent and Midpoint Review

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@allison0034 This is ready for review!
- [Updated Design Intent step 5](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous#Step-5%3A-Practice-area-feedback)
- [Updated Midpoint Review step 5](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous#Step-5%3A-Practice-area-feedback)

**Comment by allison0034** [comment]
My only comment is to add in that it doesn't have to go in that specific order, it can be dealer choice or if a practice area has questions they should go first.

**Comment by briandeconinck** [comment]
Updated! Let me know if this looks good to close out.

**Comment by allison0034** [comment]
Looks good!
