### ISSUE TITLE
[BE] My VA Forms Status: establish connection with POST /uploads/report endpoint

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#82288]
## Background
We need to set up the backend for the forms status work on My VA. We need to ensure that the user endpoint can include statuses along with the array of drafts that it fetches. This ticket is to establish a connection with the `POST /uploads/report` endpoint from vets api and expose the new vets api endpoint to the frontend. 

Documentation/swagger and BE analytics will also be needed for this but will be separate tickets.

## Tasks
- [x] setup new vets-api endpoint that can be called to make the lighthouse request on FE's behalf
- [ ] code & unit tests
- [ ] integration tests
- [x] verify if SiP form IDs we receive from `GET /v0/user` match those expected by lighthouse `POST /uploads/report` endpoint params
- [ ] **IF** IDs don't match, document ideas/plan to obtain matching IDs from lighthouse

## Acceptance Criteria
- [ ] Endpoint is connected but behind a feature flag (prod and staging)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_: Tom, BE CoP
- _How can this work be validated?_ : automated testing, code review, event logging & analytics

**Comment by DanielMiller-agile6** [comment]
dropping to 2 for next sprint. still learning about some stuff, but getting there :). this may have been a bit larger than I estimated too, but PR will be up early next sprint

**Comment by DanielMiller-agile6** [comment]
screenshot of openapi schema for endpoit 200 response:
<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0g5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49e64acf0bc13560ab58437c844ec17a825b10b6/Screenshot%202024-05-21%20at%201.28.59%E2%80%AFPM.png" alt="Screenshot 2024-05-21 at 1.28.59 PM.png" />

**Comment by DanielMiller-agile6** [comment]
screenshot of request body definition from openapi schema
---
<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2o5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be64958d0a6b59d718680c322105739833bea45b/Screenshot%202024-05-21%20at%201.33.51%E2%80%AFPM.png" alt="Screenshot 2024-05-21 at 1.33.51 PM.png" />

**Comment by DanielMiller-agile6** [comment]
screenshots got too hard lol.  here's just the JSON snippet for the definitions i'm using for testing (from latest openapi spec as of 5/21/24 1:40pm PT)
```
   "/uploads/report": {
      "post": {
        "tags": [
          [
            "VBA Documents"
          ]
        ],
        "responses": {
          "200": {
            "description": "Upload status report retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "data"
                  ],
                  "properties": {
                    "data": {
                      "$ref": "#/components/schemas/DocumentUploadStatusReport"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request - invalid or missing list of guids"
          },
          "401": {
            "description": "Authorization information not provided",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "No API key found in request"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Invalid authorization",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "You cannot consume this service"
                  }
                }
              }
            }
          },
          "413": {
            "description": "Payload too large",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Request size limit exceeded"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ErrorModel"
                      }
                    }
                  }
                }
              }
            }
          },
          "429": {
            "description": "Too many requests",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "API rate limit exceeded"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "data"
                  ],
                  "properties": {
                    "title": {
                      "description": "Human readable title description.",
                      "type": "string",
                      "example": "Internal server error"
                    },
                    "detail": {
                      "description": "Human readable error detail. Only present if status = \"error\"",
                      "type": "string",
                      "example": "Internal server error"
                    },
                    "code": {
                      "description": "Unambiguous status code. Only present if status = \"error\"\n\n* `DOC101` - Invalid multipart payload provided - not a multipart, or missing one or more required parts.\n* `DOC102` - Invalid metadata - not parseable as JSON, incorrect fields, etc.\n* `DOC103` - Invalid content - not parseable as PDF. Detail field will indicate which document or attachment part was affected.\n* `DOC104` - Upload rejected by upstream system. Processing failed and upload must be resubmitted. Detail field will indicate nature of rejection.\n* `DOC105` - Invalid or unknown id\n* `DOC106` - File size limit exceeded. Each document may be a maximum of 100MB.\n* `DOC107` - Empty payload.\n* `DOC108` - Maximum dimensions exceeded. Height and width must be less than 78 in x 101 in.\n* `DOC201` - Upload server error.\n* `DOC202` - Error during processing by upstream system. Processing failed and upload must be resubmitted. Detail field will provide additional details where available.\n",
                      "type": "string",
                      "example": 500
                    },
                    "status": {
                      "description": "Unambiguous status code. Only present if status = \"error\"\n\n* `DOC101` - Invalid multipart payload provided - not a multipart, or missing one or more required parts.\n* `DOC102` - Invalid metadata - not parseable as JSON, incorrect fields, etc.\n* `DOC103` - Invalid content - not parseable as PDF. Detail field will indicate which document or attachment part was affected.\n* `DOC104` - Upload rejected by upstream system. Processing failed and upload must be resubmitted. Detail field will indicate nature of rejection.\n* `DOC105` - Invalid or unknown id\n* `DOC106` - File size limit exceeded. Each document may be a maximum of 100MB.\n* `DOC107` - Empty payload.\n* `DOC108` - Maximum dimensions exceeded. Height and width must be less than 78 in x 101 in.\n* `DOC201` - Upload server error.\n* `DOC202` - Error during processing by upstream system. Processing failed and upload must be resubmitted. Detail field will provide additional details where available.\n",
                      "type": "string",
                      "example": 500
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Get a bulk status report for a list of previous uploads",
        "operationId": "POST:/uploads/report",
        "description": "Due to current system limitations, data for the `/uploads/report` endpoint is cached for one hour.\\n\\nA request to the `/uploads/{id}` endpoint will return a real-time status for that GUID, and update its status in `/uploads/report`.\\n\\nThe `updated_at` field indicates the last time the status for a given GUID was updated.",
        "security": [
          {
            "apikey": []
          }
        ],
        "requestBody": {
          "description": "List of GUIDs for which to retrieve current status",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DocumentUploadStatusGuidList"
              }
            }
          }
        }
      }
    }
```

**Comment by DanielMiller-agile6** [comment]
I was able to use the lighthouse sandbox api to test out the endpoint I'm using and verified where these IDs come from finally!  We will likely need to make another small-ish update in order to ensure MyVA has access to these ID values when it loads the list of forms.  Looks like any forms supporting "status" observability must have first called the `POST /uploads` method in order to gerate and like this uuid, so those are the IDs we will need to provide to our list of `savedForms` on MyVA. Example curl output from console:

---

<img width="1580" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a024203bd3ae7c2e05dec4fb3d904f5eb1cfe7c/Screenshot%202024-05-22%20at%209.23.11%E2%80%AFAM.png" alt="Screenshot 2024-05-22 at 9.23.11 AM.png" />

**Comment by DanielMiller-agile6** [comment]
also, here's an example curl w/ multiple (2) IDs. appears the main slice of these successful response objects in the array will be:
```
uiState = normalizeById(resp.data.map(d => ({
  id: d.id,
  status: d.attributes?.guid || '',
}))
```
---

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fd65b4e0de9d3e964bbbcdf59207c6e27689706/Screenshot%202024-05-22%20at%209.50.13%E2%80%AFAM.png" alt="Screenshot 2024-05-22 at 9.50.13 AM.png" />

**Comment by ACParker89** [comment]
@DanielMiller-agile6 will follow up on the report endpoint on Slack with the VFF team.

**Comment by tpharrison** [comment]
After some discovery work, it has been decided that creating a ticket for each related form will be easier to manage and monitor progress.  Any tasks contained in this ticket will be addressed in one or more of the individual tickets.
