### ISSUE TITLE
[Design] - Update email address mocks

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8229]
## Background
Users are unsure what email address was represented in the Personal and Contact Information section (contact vs log-in).  Users also expected log-in information to live in Account security.

This is based on [Combine Profile and Account Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/cpaa-research-findings.md) 

<img width="440" alt="pc-edit email address" src="https://user-images.githubusercontent.com/58752772/80001098-74406b00-846a-11ea-9683-93839e8006ac.png">

## Tasks
- [x] Propose new email address design in Account security section
- [x] Propose new email address design in Personal and contact information section
- [x] Review any new copy with Peggy
- [x] Update email address in mocks

## Acceptance Criteria
- [x] All mocks have been updated 
- [x] Copy has been approved

**Comment by tressaellen** [comment]
Here is the proposed updates for handling email address in profile 2.0.  If we decide to go this route - I'll need some help from content to look over the 'Does this update the email I use to sign in?' FAQ.

![Screen Shot 2020-05-01 at 10.47.21 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/6d2216ac-2bfb-467e-941a-98945dec0088)![Screen Shot 2020-05-01 at 10.47.27 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/cd6db569-c0f8-4fc8-a9f5-3b580057d98d)![Screen Shot 2020-05-01 at 10.47.33 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/63be8789-f090-4d4c-8602-6bd5605b5141)![Screen Shot 2020-05-01 at 10.47.40 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/6646f92d-3dca-4f33-8233-27991748a4b1)

**Comment by tressaellen** [comment]
Hi @peggygannon could you give some suggestions for this copy (anything with a red box around it) for the updated email address designs?

<img width="873" alt="Screen Shot 2020-05-04 at 12 04 06 PM" src="https://user-images.githubusercontent.com/58752772/81008483-7b1e9480-8dff-11ea-918b-7f2e6441427c.png">
<img width="928" alt="Screen Shot 2020-05-04 at 12 04 49 PM" src="https://user-images.githubusercontent.com/58752772/81008489-7e198500-8dff-11ea-9796-a29d469e405e.png">

**Comment by Samara-Strauss** [comment]
I'm confused by the screenshots above and what updates you intend to make. Below, I wanted to share what I had been picturing when we met and discussed these updates a few weeks ago:

**Personal Information**

Instead of having the collapsible FAQ, we should have the same info in a gray box at the bottom of this page similar to what we show on the direct deposit page.

![Personal info suggestion](https://user-images.githubusercontent.com/34068740/81008991-d3668e00-8e21-11ea-8ce2-bedd60e80d03.jpg)
**Account settings*

- We don't know what email address they use to sign in since there are three possible credentials. Instead, in the Sign in email section, we basically need the same FAQ content we have currently on the personal & contact info page. 
- Also, having the sign in email address section below the terms & conditions seems like the wrong place. I would imagine that the sign in email address section is more important than the T&C. Can you move those up?

![Account settings suggestion](https://user-images.githubusercontent.com/34068740/81009158-1aed1a00-8e22-11ea-97d7-7a50eb4c07f4.jpg)

Let me know if you have any questions or if you think this is the totally wrong direction. Happy to discuss and figure out what works.

**Comment by tressaellen** [comment]
Ah, I think that this makes total sense - I didn't realize that we wouldn't be able to know which email address they use to sign in. I had originally had the grey box instead of the FAQs in account security, but then it was too many stacked boxes. But this works much better! I'll update and drop in screenshots shortly.

**Comment by tressaellen** [comment]
Also @Samara-Strauss, in the personal and contact information - I'd like to add a line in the grey box along the lines of, 'Updating this email address does not update the email you use to sign in. To update the email addres...' Thoughts?

**Comment by tressaellen** [comment]
<img width="510" alt="Screen Shot 2020-05-04 at 12 41 04 PM" src="https://user-images.githubusercontent.com/58752772/81011500-9213b580-8e04-11ea-84a4-b91289f6f433.png">
<img width="360" alt="Screen Shot 2020-05-04 at 12 41 10 PM" src="https://user-images.githubusercontent.com/58752772/81011508-93dd7900-8e04-11ea-8eca-ba2e52d330af.png">

**Comment by Samara-Strauss** [comment]
> Also @Samara-Strauss, in the personal and contact information - I'd like to add a line in the grey box along the lines of, 'Updating this email address does not update the email you use to sign in. This email address is used solely for contact purposes.' Thoughts?

I think that's a good idea. Maybe we want to say something like "The email address above is used for the VA to contact you. To change the email address you use to sign into VA.gov..." so that people know what the email address on this page is used for.

Also, this box is shown in blue here, but the one one the direct deposit page is gray. Should these callout boxes be blue or gray? We should be consistent across the profile.

**Comment by Samara-Strauss** [comment]
ALSO, should the box on the Personal & Contact info page have a heading?

**Change the email address you use to sign into VA.gov**

"The email address above is used for the VA to contact you. To change the email address you use to sign into VA.gov..."

**Comment by tressaellen** [comment]
Yep! I think the heading helps a lot. @peggygannon could you help us with the right wording for the heading and the first line or two of this? 

<img width="795" alt="Screen Shot 2020-05-04 at 1 03 33 PM" src="https://user-images.githubusercontent.com/58752772/81013509-b6bd5c80-8e07-11ea-8c20-abda5ed2e95b.png">

**Comment by tressaellen** [comment]
@Samara-Strauss as far as the blue vs grey box - Erik said that the component for this type of style/messaging uses the blue box so that is what we will be using for all of these.

**Comment by Samara-Strauss** [comment]
Got it, thanks for letting me know!

**Comment by peggygannon** [comment]
Hi, @tressaellen am beginning to take a look at these now. And I have some followup questions:

1. I only need to recommend new header and first 2 lines of copy for the email content?  should  ignore the boxes with the red outline at top of issue? 

2. and if you need recommendation on the first line or two of the content. Is the rest of the content in the blue box correct? 


3. Will this email header/blue box live in both Contact information and Account information pages in profile?

**Comment by tressaellen** [comment]
HI @peggygannon , thanks for taking the time to look at this.

1. Yes - just ignore the boxes with the red outline at the top.  We just need messaging for the header and then a line or two basically explaining that the email address listed is for contact purposes only and changing this will not change the users log in email.

2.  The rest of the content is pulled directly from the previous mocks, so there shouldn't need to be any changes there.

3.  The blue box will live in contact information, and then just the "To update the email address you use to log in..." content will live in 'Sign in email address' section in Account security.  If you have any updates on the phrase 'Sign in email address', that would be helpful as well.  I'll attach a screenshot.
<img width="360" alt="Screen Shot 2020-05-04 at 12 41 10 PM" src="https://user-images.githubusercontent.com/58752772/81227555-126b1f80-8f99-11ea-98aa-8eba0637b4c5.png">

**Comment by peggygannon** [comment]
Hello, @tressaellen Please see content recommendation below. 

Please note, per VA.gov style, we should be using "sign in" not "log in" when talking about signing in. 



**Do you want to change the email address you use to sign in to VA.gov?**
VA uses the above email address to contact you only. If you update this contact email address, it won’t change the email address you use to sign in to VA.gov.

To change the email address you use to sign in to VA.gov……. 



Your sign-in email address
To update the email address you use to sign in to VA.gov, go to the account where you manage your settings and identity information. Any updates you make there will automatically update on VA.gov.

**Comment by tressaellen** [comment]
Thanks @peggygannon! Just a few questions:

- The line "To change the email address you use to sign in to VA.gov" - should this be some kind of title? 
- "Your sign-in email address", are you envisioning this as a link?

**Comment by Samara-Strauss** [comment]
> Do you want to change the email address you use to sign in to VA.gov?
> VA uses the above email address to contact you only. If you update this contact email address, it won’t change the email address you use to sign in to VA.gov.
> 
> To change the email address you use to sign in to VA.gov…….
> 
> Your sign-in email address
> To update the email address you use to sign in to VA.gov, go to the account where you manage your settings and identity information. Any updates you make there will automatically update on VA.gov.

I just want to confirm that we will show the links off to DS Logon/MHV/ID.me below this. I think that's necessary to clarify "go to the account where you manage your settings and identity information."

**Comment by peggygannon** [comment]
Yes @Samara-Strauss sorry, i should have added those in my commit. Those links should still stay!

**Comment by tressaellen** [comment]
@peggygannon does this look correct?

**Do you want to change the email address you use to sign in to VA.gov?**
VA uses the above email address to contact you only. If you update this contact email address, it won’t change the email address you use to sign in to VA.gov.

To update the email address you use to sign in to VA.gov, go to the account where you manage your settings and identity information. Any updates you make there will automatically update on VA.gov.

[Link]
[Link]
[Link]

**Comment by peggygannon** [comment]
Hi, @tressaellen  just one more tweak.. adding "email" to the last sentence. This is to be clear that we're talking about email updates (not general updates. This is what we have in the current messaging right now. 

To update the email address you use to sign in to VA.gov, go to the account where you manage your settings and identity information. Any email updates you make there will automatically update on VA.gov.

[Link]
[Link]
[Link]

**Comment by mshea0606** [comment]
@tressaellen @peggygannon @Samara-Strauss Re-opening this ticket per our convo in sprint planning about users still being slightly confused

**Comment by tressaellen** [comment]
Hi @peggygannon , we're re-opening this issue to address the continued confusion around contact vs log-in email address. I've attached a screenshot with some added copy that might work - I would love your thoughts/any changes. cc/ @Samara-Strauss and @mshea0606 

![Screen Shot 2020-05-21 at 9.52.50 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/74e68038-216f-48ad-b679-e53d1990fce8)

**Comment by Samara-Strauss** [comment]
@tressaellen what specifically was confusing to the research participants? Was it the copy? Anything we should consider changing with the design? I realize this is just confusing no matter what so we may be limited in a great solution.

**Comment by Samara-Strauss** [comment]
Also, FWIW, I like the update you made!

**Comment by tressaellen** [comment]
@Samara-Strauss people still expected that changing the email address on P&C information would change the email address that they used to sign-in. Nobody even noticed or read the content in the blue box.  I'm open to ideas on ways to update it so it's not confusing, my thought was just to try to add some things that hopefully they won't miss (e.g. changing 'email address' to 'contact email address', adding some text in the actual 'email address' box)

**Comment by Samara-Strauss** [comment]
Got it. That totally makes sense. I think this is going in a good direction and is the best fix for something that is inherently confusing and we can't *really* fix without fundamentally changing how log-in on VA.gov works.

**Comment by peggygannon** [comment]
@tressaellen Here are my recommendations for the email content. Please let me know your thoughts!

1. 
**Contact email address**
This is the email we’ll use to contact you. To update the email you use to sign in to your account, [go to Account security](/link to account security screen).

By adding the link to the Account security screen, we could then remove the blue box under Contact email address component. (as per user research, participants didn't notice or read the content in this blue box) 

2. On the Account security screen
Please be sure we're using sign in (not log in), in this content. This is to adhere to our content style guide. 

**Sign-in email address**
To update the email address you use to sign in, go to the account where you manage your account settings and identity information. Any email updates you make there will automatically update on VA.gov. 

[links]
[links]
[links]

**Comment by tressaellen** [comment]
Hi @peggygannon - I love the idea of removing the blue box since no one looked at it. I'm hesitant to add a link to a link (Account security > ID.me), that feels redundant. I tried adding the full messaging in the box, but it's too long. Do you think there's a way to simplify that messaging at all? My thought is to remove the line 'Any email updates you make there will automatically update on VA.gov.' and then possibly see if we can add that to the ID.me side of things when they actually update the email.  I'd love your thoughts.

<img width="330" alt="Screen Shot 2020-05-26 at 10 45 50 AM" src="https://user-images.githubusercontent.com/58752772/82938321-178b1100-9f3e-11ea-8674-42cb007fac0d.png">

**Comment by peggygannon** [comment]
Hi, @tressaellen Here is a recommendation to simplify the messaging. 

To update the email you use to sign in, go to your account where you manage your settings. 

A couple of questions: 

--this assumes that anyone who sees Profile 2.0  already has an account? (sorry, that may be a dumb question.. ha!!) 
 Just wondering if a link to one of these accounts (to ID.me, DS LOGON or MHV) will always be underneath this message? 

--Do we want to simply this message that also appears on the Account security screen?

**Comment by Samara-Strauss** [comment]
> To update the email you use to sign in, go to your account where you manage your settings.

This is nitpicky, but could we say "go to the website where you manage your settings" instead of "go to the account..."? "Account" to me sounds like it could be another VA.gov account, or maybe another page on VA.gov. "Website" IMO more clearly communicates that you have to leave our site to manage your login credentials.

**Comment by tressaellen** [comment]
I agree with Samara about "Account" vs "Website". So that would make the messaging:

To update the email you use to sign in, go to the website where you manage your settings.

And @peggygannon you're totally fine - ask all the questions! 

1. In order for a user to sign in and view their profile they'd have to create an account, yes.
2. I think it'd be a great idea to simplify the messaging that appears on the Account security screen as well.  I think in general, the less wordy these messages are then there's a higher chance people will read them. Could we just use this simplified version on the Account settings page as well? It might make sense to include the 'Any email updates you make there will automatically update on VA.gov.' on Account security as well. 
<img width="331" alt="Screen Shot 2020-05-27 at 8 03 03 AM" src="https://user-images.githubusercontent.com/58752772/83044577-d56ed780-9ff0-11ea-80ff-ef4c9a8e2122.png">
<img width="330" alt="Screen Shot 2020-05-27 at 8 04 26 AM" src="https://user-images.githubusercontent.com/58752772/83044582-d7389b00-9ff0-11ea-94a7-bb33035dbeaa.png">

**Comment by peggygannon** [comment]
HI, @tressaellen Yes, this update looks good. Thx!

**Comment by sshein** [comment]
haha sorry to do this but I'm still so confused. "Go to the website where you manage your settings" is confusing because SOME of your settings ARE managed here where you are... can it be "To update the email you use to sign in, go to the website where you manage your login information." ? or something like that?

**Comment by tressaellen** [comment]
Good point @sshein , I think that works and is more clear.
<img width="657" alt="Screen Shot 2020-05-28 at 2 48 44 PM" src="https://user-images.githubusercontent.com/58752772/83201620-59f54f00-a0f2-11ea-9764-230a9f2865d2.png">
