### ISSUE TITLE
Domo Data QCs -- Wave 1b & Wave 2 (KPI dashboards)

### ISSUE THREAD

**Issue by ChristineYoungZA** [department-of-veterans-affairs/va.gov-team#82315]
### Description
This ticket is account for QC'ing the next wave of Domo dashboards. This QC process should match the following steps we've been using for the KPI dashboards.

> -  Create duplicate dataset and cards. Once Phil creates new view, route duplicate cards to new view.
> -  Follow up with Phil for any changes that need to be made to the dataset.
> -  Doing column per column comparison between the UA and the GA4 Views
> -  Look for and document differences in variable names, formatting, etc.
> -  Check if event labels, categories, actions -- etc that are used within BeastModes -- we might have to derive this
> -  Copy report -- Save As -- use new GA4 Dataset --
> -  Set permissions of copied report so it's just available by our team.
> -  If we pass these checks -- we can plan to certify that the reports are fresh.
> -  If data issue, or discrepancy is found, mark in ticket and notify team.
> -  Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).

### Tasks
The following Domo reports/dashboards have been QC'd

**Wave 1:** 

- [x] [KPIs - Health Care Application](https://va-gov.domo.com/page/980067552)
- [x] [VAOS KPIs](https://va-gov.domo.com/page/1769944412)
- [x] [Online Caregiver Application - KPIs](https://va-gov.domo.com/page/1905395623)
- [x] [VA Notify KPIs](https://va-gov.domo.com/page/2040841289)
- [x] [Profile KPIs](https://va-gov.domo.com/page/1834995012?userId=1539186973)
- [x] [MyVA KPIs Report](https://va-gov.domo.com/page/1167851935)
- [x] [VA Chatbot KPIs](https://va-gov.domo.com/page/939649897)

**Wave 2:**

- [x] [Combined Debt Portal KPIs](https://va-gov.domo.com/page/1976847942)
- [x] [KPIs - Authenticated Experience - Profile 2.0](https://va-gov.domo.com/page/492918243)
- [x] [Site-wide Homepage-Engagement KPIs](https://va-gov.domo.com/page/80919003)

---

### Acceptance Criteria

- [x] Initial QCs have been completed for the all of the above Domo dashboards in Wave 1b.
- [x] Initial QCs have been completed for the all of the above Domo dashboards in Wave 2.

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA, @Blivaditis  -- given your progress on the other dashboards you QC'd so far this, I'm going to add this to the current sprint.

I gave it a 3, given we had already made some progress, and is split work between both of you, but feel free to adjust the estimate.

**Comment by johnny-jesensky-adhoc** [comment]
Reports and datasets have been QC'd, with our findings logged on [this Confluence page](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/Data+QC+Mapping+Findings+Log). There are a few outstanding items will be covered in #86340. 

FYI @dorseypa1, @ChristineYoungZA, @Blivaditis
