### ISSUE TITLE
Enable GitHub App - Control Plane Integration 

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#82312]
## Description
This ticket involves integrating the GitHub App behind `prt-preview-manifest` into the `prt-preview-control` repository. 

As of 5/3/24 prt-preview-manifest doesn't have a GitHub so https://github.com/patrick-black-oddball/prt-preview-manifest-prb is used as a substitute

### Tasks
- [x] Integrate the GitHub App with `workflow_dispatch`
- [x] Add App integration to `create`, `update`, `destroy` controller actions
- [x] Connect `create`, `update`, `destroy` to their respective mock workflows

### Acceptance Criteria
- [x] `create` and `update` action starts the `mock-deploy-environment` workflow
- [x] `destroy` action starts the `mock-destroy-environment` workflow

### Future Considerations
- Add `private_pem` to AWS param store
