### ISSUE TITLE
[Analytics] Enable travel claim by station widget to show past 1 year of metrics

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#82313]
## Tasks

Currently, the [Travel Claims Submission by Station Number widget](https://vagov.ddog-gov.com/dashboard/eax-4m7-3de/check-in-travel-claims-stakeholder?fromUser=true&refresh_mode=sliding&view=spans&from_ts=1712340145323&to_ts=1714932145323&live=true) can only show 1 months work of data because it's measuring logs. Facilities are interested in seeing the past 1 year. [Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1714757306149789). 

- [ ] Ensure metrics can be tracked by station number in order to review past 1 year of submissions
- [ ] Reconfigure widget to show past 1 year, similar to the Claims Created Successfully (past 1 year) widget

## AC

- [ ] Widget for station numbers are tracking past 1 year of submissions
- [ ] Widget and DD dashboard are updated
- [ ] Reply to [Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1714757306149789)

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/82313?planning-poker) with Zenhub @kanchanasuriya
