### ISSUE TITLE
[Design] Create mocks for new mobile view (name tag)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8231]
## Background
Users liked the 'name-tag' area, but the military badge is taking up too much space in the mobile view.

This is based on [Combine Profile and Account Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/cpaa-research-findings.md) 

<img width="165" alt="Screen Shot 2020-04-21 at 9 29 17 AM" src="https://user-images.githubusercontent.com/58752772/80001866-5b848500-846b-11ea-9f86-cf9f4f85a38c.png">

## Tasks
- [x] Propose new 'name tag' design for mobile view
- [x] Update name-tag in mobile mocks

## Acceptance Criteria
- [x] All mocks have been updated

**Comment by tressaellen** [comment]
Here is the new name-tag design (sans military badge), and with the appropriate H1 added.

<img width="332" alt="Screen Shot 2020-05-01 at 9 14 13 AM" src="https://user-images.githubusercontent.com/58752772/80832084-7c01bd00-8b98-11ea-8701-a205cb5ce9ba.png">

**Comment by Samara-Strauss** [comment]
My opinion: I think you can remove the "Your profile" header. It doesn't add anything visually. I realize this may be needed for screen readers, so if it is, is there a way we can make this visible to screenreader devices but not to people viewing the profile?

**Comment by tressaellen** [comment]
Yes exactly, I don't think it works there either - this was the conversation that I've been having with Jen Strickland, we're going to use the profile navigation header as the H1 for screen readers so we can remove 'Your profile' from this band in desktop and mobile.

**Comment by Samara-Strauss** [comment]
Ah, got it! Thanks for letting me know!

**Comment by tressaellen** [comment]
H1 'Your profile' has been removed.  We will (most likely) be using the header for the navigation as H1. 

<img width="328" alt="Screen Shot 2020-05-05 at 10 33 38 AM" src="https://user-images.githubusercontent.com/58752772/81106656-7242c700-8ec2-11ea-8bc0-ea98939edd6f.png">

**Comment by Samara-Strauss** [comment]
Nice! This looks awesome!

**Comment by tressaellen** [comment]
Since we are removing the H1 from the 'nametag' area - the desktop view will have to be updated as well.
<img width="647" alt="Screen Shot 2020-05-06 at 8 08 51 AM" src="https://user-images.githubusercontent.com/58752772/81200812-f489c480-8f70-11ea-84e0-33d26423f29c.png">
