### ISSUE TITLE
QC Initial Domo Report - VA.gov Forms KPIs

### ISSUE THREAD

**Issue by ChristineYoungZA** [department-of-veterans-affairs/va.gov-team#82334]
### Description
This ticket is account for QC'ing the Standard Forms KPIs dashboard with the newly created GA4 view. Focus on QC'ing the metrics specifically for changes in the naming conventions, confirm beast modes/charts are functioning and if they aren't identify what is the cause of the issue. 

### Tasks

- [x] Create duplicate dataset and cards. Once Phil creates new view, route duplicate cards to new view. 
- [x] Follow up with Phil for any changes that need to be made to the dataset. 
- [x] Doing column per column comparison between the UA and the GA4 Views
- [x] Look for and document differences in variable names, formatting, etc.
- [x] Check if event labels, categories, actions -- etc that are used within BeastModes -- we might have to derive this
- [x] Copy report -- Save As -- use new GA4 Dataset -- 
- [x] Set permissions of copied report so it's just available by our team.
- [x] If we pass these checks -- we can plan to certify that the reports are fresh.
- [x] If data issue, or discrepancy is found, mark in ticket and notify team.
- [x] Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
---

### Acceptance Criteria

- [x] Report has been copied -- using the new GA4 view.
- [x] Notes from QC or potential changes to ETLs have been documented on [this page](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
- [x] All data issues have been flagged, and if needed, another ticket has been created for them. 
- [ ] If data is looking good -- we need to flag as fresh.

**Comment by johnny-jesensky-adhoc** [comment]
Performed initial QC of GA4-powered Forms KPI Dashboard. Report created [here](https://va-gov.domo.com/page/1134446671). Findings have been documented in this ticket, as well as on our Confluence page -- [Data QC & Mapping Findings & Log](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/Data+QC+Mapping+Findings+Log).

Remaining validation/refinement work has been documented in this separate ticket -- #83786. 

FYI @Blivaditis, @ChristineYoungZA, @dorseypa1
