### ISSUE TITLE
Domo Data QCs -- Wave 3

### ISSUE THREAD

**Issue by ChristineYoungZA** [department-of-veterans-affairs/va.gov-team#82336]
### Description
This ticket is account for QC'ing the next wave of Domo dashboards. This QC process should match the following steps we've been using for the KPI dashboards.

> -  Create duplicate dataset and cards. Once Phil creates new view, route duplicate cards to new view.
> -  Follow up with Phil for any changes that need to be made to the dataset.
> -  Doing column per column comparison between the UA and the GA4 Views
> -  Look for and document differences in variable names, formatting, etc.
> -  Check if event labels, categories, actions -- etc that are used within BeastModes -- we might have to derive this
> -  Copy report -- Save As -- use new GA4 Dataset --
> -  Set permissions of copied report so it's just available by our team.
> -  If we pass these checks -- we can plan to certify that the reports are fresh.
> -  If data issue, or discrepancy is found, mark in ticket and notify team.
> -  Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).

### Tasks
The following Domo reports/dashboards have been QC'd
- [ ] KPIs - QA Standards
- [ ] Corona Virus Vaccination
- [ ] VA.gov VA Notify KPIs
- [ ] VRE/28-8832
- [ ] Comparison Tools
- [ ] VAOS
- [ ] Spanish FAQ
- [ ] EDU Benefits/1995
- [ ] Terms & Conditions
- [ ] Exploratory Analytics
- [ ] Content Usage
- [ ] Products Dashboard

---

### Acceptance Criteria

- [ ] QCs have been completed for the all of the above Domo dashboards.
