### ISSUE TITLE
[Design] Design Mobile Sub Navigation

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8233]
## Background

This ticket is related to #8234 

Specifically in mobile, participants had a difficult time finding the 'profile menu', and in general were confused about the mobile navigation.

This is based on [Combine Profile and Account Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/cpaa-research-findings.md) 

<img width="165" alt="Screen Shot 2020-04-21 at 9 29 17 AM" src="https://user-images.githubusercontent.com/58752772/80001866-5b848500-846b-11ea-9f86-cf9f4f85a38c.png">

## Tasks
- [x] Research other mobile navigation methods across VA.gov
- [x] Propose new mobile navigation method for profile
- [x] Review any new copy with Peggy
- [x] Update new mobile navigation in profile mocks

## Acceptance Criteria
- [ ] Copy has been approved
- [ ] All mocks have been updated

**Comment by tressaellen** [comment]
Here are the screenshots for the updated mobile. And here is the [mobile nav research.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/mobile-navigation-research.md)

<img width="166" alt="Screen Shot 2020-05-26 at 10 55 20 AM" src="https://user-images.githubusercontent.com/58752772/82939174-6f764780-9f3f-11ea-9db7-b54c32aef3f9.png">
<img width="166" alt="Screen Shot 2020-05-26 at 10 55 26 AM" src="https://user-images.githubusercontent.com/58752772/82939184-71400b00-9f3f-11ea-8b94-96ce4c45f951.png">
