### ISSUE TITLE
GA4 Domo Data QC -- All VA.gov Summary

### ISSUE THREAD

**Issue by ChristineYoungZA** [department-of-veterans-affairs/va.gov-team#82342]
### Description
This ticket is account for QC'ing the [All VA.gov Dashboard](https://va-gov.domo.com/page/1030131175) dashboard with the newly create GA4 views/datasets. Datasets that have been QC'd will be checked.

### Datasets & Views
- [ ] [BQ Product Form Events by Day](https://va-gov.domo.com/datasources/87b86c11-397b-4320-b632-d87896b5c4fd/details/overview)
- [x] [[Output} - All VA logged in users](https://va-gov.domo.com/datasources/e2e825f6-2a92-45cb-99e7-9d58c0b268aa/details/overview), ETL - Is powered by [BQ - Logged in Compared](https://va-gov.domo.com/datasources/99730988-96f0-495e-93de-6cd332283414/details/overview), GA4 [dataset](https://va-gov.domo.com/datasources/3bbccb7c-c4ae-4dce-a5ef-928b1e02fe48/details/data/table) and [ETL dataset](https://va-gov.domo.com/datasources/193cd94f-2012-4519-bfdd-697f682326dd/details/data/table)
- [x] [BQ - Standard Search](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/overview)
- [ ] [[OUTPUT] Select Va.gov & Vets.gov Events By Month - BQ](https://va-gov.domo.com/datacenter/dataflows/58/details#datasets) 
- [ ] [GA4 BQ - Product Form Events by Day ](https://va-gov.domo.com/datasources/3f12ae3f-e89f-4b26-a5a0-3a4af00551f6/details/overview)
- [x] [GA4 - BQ Standard Forms Engagement](https://va-gov.domo.com/datasources/fcc7deb6-7311-4d3b-b7d7-33ff167df0cb/details/overview)
- [x] [View of BQ - Records Letter Download](https://va-gov.domo.com/datasources/eaceeef6-8d2a-4fec-9516-880f3336d1ac/details/overview), [GA4 Dataset](https://va-gov.domo.com/datasources/d9fdf5b6-8132-4838-aeed-21338c9587a9/details/overview)
- [x] [BQ - VAOS Events](https://va-gov.domo.com/datasources/b1a085f4-b988-49d7-b283-aa3ec7c30acc/details/overview), [GA4 Dataset](https://va-gov.domo.com/datasources/b1a085f4-b988-49d7-b283-aa3ec7c30acc/details/data/table)
- [x] [BQ - Vaos User Completion all VA](https://va-gov.domo.com/datasources/4e391ee5-8310-4116-86cf-76c2384e70ae/details/overview), [GA4 Dataset](https://va-gov.domo.com/datasources/55a4ddc0-9243-4b75-baaf-17e5b69eef3a/details/data/table)
- [x] [[Output] Standard search exits](https://va-gov.domo.com/datasources/58293f6f-8d89-43cf-a54b-1e796d3f3c4a/details/overview), [GA4 dataset ](https://va-gov.domo.com/datasources/d236eb08-3887-4299-989b-fc48a188e48e/details/overview)
- [x] [BQ - Standard Search Refinment](https://va-gov.domo.com/datasources/7555e592-8bdb-4770-beae-08004d5490c0/details/overview), [GA4 dataset](https://va-gov.domo.com/datasources/68aea952-decf-4bec-9fc2-2991b58eceef/details/data/table)
- [ ] [[OUTPUT] Monthly PV, Users for All, WBC, Vets by Month](https://va-gov.domo.com/datasources/92a43417-0f9e-4ed7-bcdd-9eb290b471a9/details/overview), ETL powered by two datasets and a historical excel file load, one of two datasets is live [GA4 BQ - All VA - PVs, Sessions, Users, Bounces by Month](https://va-gov.domo.com/datasources/9b846e12-2133-4af6-aff5-cc9d7ef3beef/details/overview)
- [x] [BQ - Facility locator pageviews by day](https://va-gov.domo.com/datasources/49a759eb-dfcc-4e00-8251-67e84b3e4f5c/details/overview), [GA4 Dataset ](https://va-gov.domo.com/datasources/49a759eb-dfcc-4e00-8251-67e84b3e4f5c/details/data/table)
- [x] [BQ - Resources & Support Pageviews](https://va-gov.domo.com/datasources/464201c2-6e26-45d4-b9d6-0ba6ca377df8/details/overview),[ GA4 Dataset](https://va-gov.domo.com/datasources/6869be18-2af6-44f4-9877-582d3f183e52/details/overview)
- [x] [[output] all va logged in users](https://va-gov.domo.com/datasources/e2e825f6-2a92-45cb-99e7-9d58c0b268aa/details/overview), [GA4 dataset powering ETL - Login Events by day](https://va-gov.domo.com/datasources/739bce02-3449-4294-bdfa-d7660d130f19/details/data/table), [ETL link ](https://va-gov.domo.com/datasources/e30ac374-4ee1-41bc-8baa-eba89d2cb390/details/data/table)
- [x] [BQ - profile details](https://va-gov.domo.com/datasources/86cbef9e-c473-4e62-b6c8-be7448f1c961/details/overview), [GA4 dataset ](https://va-gov.domo.com/datasources/872cb69d-194e-45ad-b039-65cb50433a24/details/data/table)
- [ ] [BQ - Claims users by month](https://va-gov.domo.com/datasources/42d302a8-0483-4e6d-a868-fcf28e8c92f5/details/overview)

### Tasks

- [x] Create duplicate dataset and cards. Once Phil creates new view, route duplicate cards to new view. 
- [x] Follow up with Phil for any changes that need to be made to the dataset. 
- [x] Doing column per column comparison between the UA and the GA4 Views
- [x] Look for and document differences in variable names, formatting, etc.
- [x] Check if event labels, categories, actions -- etc that are used within BeastModes -- we might have to derive this
- [x] Copy report -- Save As -- use new GA4 Dataset -- 
- [x] Set permissions of copied report so it's just available by our team.
- [ ] If we pass these checks -- we can plan to certify that the reports are fresh.
- [x] If data issue, or discrepancy is found, mark in ticket and notify team.
- [x] Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
---

### Acceptance Criteria

- [x] Report has been copied -- using the new GA4 view.
- [x] Notes from QC or potential changes to ETLs have been documented on [this page](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
- [x] All data issues have been flagged, and if needed, another ticket has been created for them. 
- [ ] If data is looking good -- we need to flag as fresh.

**Comment by johnny-jesensky-adhoc** [comment]
Initial QC has been performed by @Blivaditis -- [here](https://va-gov.domo.com/page/460669845). Findings from QC have been documented on these artifacts.

- [Data QC & Mapping Findings & Log](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/Data+QC+Mapping+Findings+Log)
- [GA4 Domo QC Record](https://docs.google.com/spreadsheets/d/1oaoXivzL854woEIUzgsPReoKW55Spz2p4S5WI_u_QHQ/edit#gid=1044752152)

We will be combining the follow-up items into a master list to remediate, and action on findings. Moving this to Done for now.

FYI @ChristineYoungZA, @dorseypa1
