### ISSUE TITLE
[Design] Mobile navigation documentation

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8234]
## Background

[Mobile Navigation Markdown Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/mobile-navigation-research.md)

This ticket is related to #8233 

Specifically in mobile, participants had a difficult time finding the 'profile menu', and in general were confused about the mobile navigation. Mobile subnavigation should be clearer for the entire logged in experience - this is two-tier solution. First, there should be a short term fix specific to the profile (#8233) followed by a more involved long term solution based on previous research and more comprehensive mobile navigation needs.

This is based on [Combine Profile and Account Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/cpaa-research-findings.md) 

<img width="165" alt="Screen Shot 2020-04-21 at 9 29 17 AM" src="https://user-images.githubusercontent.com/58752772/80001866-5b848500-846b-11ea-9f86-cf9f4f85a38c.png">

##Research Document

[Mobile Navigation Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/mobile-navigation-research.md)

## Tasks
- [x] Research other mobile navigation methods across VA.gov
- [x] Compile all research into a markdown document
- [x] Share with appropriate parties (if applicable)

## Acceptance Criteria
- [x] Markdown document has been created

**Comment by tressaellen** [comment]
All findings will be stored here [Mobile Navigation Markdown Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/mobile-navigation-research.md)
