### ISSUE TITLE
Discovery: Archiving Daily Accessibility Scan Page [Footer Ticket 82123]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#82359]
### Description

Per Erika Washburn: The daily accessibility scan mentioned [on this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content) is no longer supported and was removed last. 
Platform Content Team added a note to this effect, however, there is no solid timeline for us to replace scanning within content-build. In fact, content-build is currently on the roadmap to be sunset by the end of the 2024 calendar year for next-build. 
With this in mind, we may want to consider archiving this page altogether. 

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content 

### Possible SMEs

- Naomi Marcusson
- CAIA Team
- Shira Goodman/Governance

---
## Tasks
- [x] Determine SME for deciding whether to archive  this page
- [x] Consult with SMEs and make determination
- [x] Create Edit ticket if necessary, for the work

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by artsymartha68** [comment]
I agree, let's archive it since we aren't doing this anymore.

**Comment by jknipes** [comment]
We are adding this ticket to the current sprint to document the work.
@artsymartha68 Thank you for your input as a member of the CAIA Team, we appreciate you advising on this issue!
Per the recommendation, we are closing this discovery ticket and opening an Edit ticket for the archiving of this page.
