### ISSUE TITLE
[CST] 8 phase claim graphic

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#82368]
## Value Statement
**_As a_** veteran with a compensation claim checking the Overview section of CST
**_I want to_** get an overview of the claim process that clearly tells me how many steps there are and which steps can repeat
**_So that_** my expectations about what can happen in the claims process are managed, especially when it comes to understanding that the process is non-linear. 

---
## Background Context

8 phase claim stepper design is below. Section should include a header and boilerplate text. 

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVc0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1043d610761fcf403ef4e5e9434192574f8617c4/Screenshot%202024-05-06%20093335.png" alt="Screenshot 2024-05-06 093335.png" />

## Design
- We (engineering) will need an individual image for each state that the stepper can be in
- full designs can be seen[ in Mural.](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713276576012/25e677b1d846aff3bea16fc9175e473d5e509888?sender=u7b04181b0deced23bce71680)
- [Figma file](https://www.figma.com/file/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=1835-8610&mode=design)

### Enablement team (if needed)
@member of team

## Engineering notes
- Instead of using the `claim.attributes.status` field, we should use `claim.attributes.claimPhaseDates.latestPhaseType` to get the current status of the claim
- We will need to make is so that the correct image shows based on the phase that the claim is currently in
- There is a constant function called `getStatusMap` that returns a map will all 8 of the statuses
- These are the possible statuses:
  - CLAIM_RECEIVED
  - UNDER_REVIEW
  - GATHERING_OF_EVIDENCE
  - REVIEW_OF_EVIDENCE
  - PREPARATION_FOR_DECISION
  - PENDING_DECISION_APPROVAL
  - PREPARATION_FOR_NOTIFICATION
  - COMPLETE

## Open questions
- Are there designs for this work in Figma?
- What icons are we using for this work?

## Tasks
- [x] Create 8 distinct svg graphics 
- [x] Add the following behind the `cst_claim_phases` feature flag
  - [x] Add the "Overview of the claim process" header
  - [x] Add the subtext under the header
  - [x] Add the claim phase stepper images with logic to determine which image to show based on the current claim status

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] The new header subtext and diagram is behind the `cst_claim_phases` feature flag.
- [x] There is a header calling out that this is an "Overview of the Claim Process"
- [x] There is a new header subtext when  `cst_claim_phases` is enabled saying there are 8 phases and that phases can move forwards and backwards between phases 3-6. 
- [x] A graphic is present with each of the claim phases represented numerically that also depicts the non-linearity of the claim process. 
- [x] The graphic highlights the claim phase a claimant is actually on (when a claimant is in phase 3, the number 3 highlights).

**Comment by uxgary** [comment]
![Step 1](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/3ff18e09-c836-4b4b-9f52-33cd55e766c9)
![Step 8](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/e9d88526-4fd7-4e69-a30e-abc5f0c77dce)
![Step 7](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/be4f8672-446a-44f9-9ac5-04c524c62dc2)
![Step 6](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/68ec96e9-a54b-4906-add9-018d77645648)
![Step 5](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/e4af61c8-cce8-48c8-8abd-c56191a94dc1)
![Step 4](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/14a1bb90-0366-4947-8973-d7c09a427830)
![Step 3](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/39a48143-236b-4bd6-b6e1-a781a51aa011)
![Step 2](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/46093f75-c28b-4655-8362-237e8e9968f1)

**Comment by uxgary** [comment]
I've created individual SVGs for each step. Not sure where to save the files for download. Which ever engineer that picks up this ticket, please reach out so I can send them over. The images in figma can be on in the page called, [For ENG team](https://www.figma.com/file/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=1883-36157&mode=design)

**Comment by pmclaren19** [comment]
@uxgary please review for design QA and then assign to @jacobworrell once you have approved!

**Comment by uxgary** [comment]
I just reviewed it thank you. The graphic looks great. I just realized we didn’t put a task for accessible labels. I've created a separate ticket for those things, [Accessible labels for icons used 8 phase claim overview page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82952).
