### ISSUE TITLE
Refine Contact Center Product Guide Documentation for View/Modify Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8236]
## Goal
The Contact Center requires documentation on our feature in the event that anything happens, they can review the expected behavior and either resolve the issue immediately or escalate as appropriate.

## Tasks
- [x] Refine the first draft of the contact center product guide documentation
  - [x] Address items in "`[  ]`"s
- [x] Implement screenshots

## Acceptance Criteria
- [x] The first draft of the contact center product guide has been revised and link noted in GH feature folder

**Comment by jason-gcio** [comment]
uploading via LFS

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/view-and-update-dependents/contact-center/Dependency%20Claims%20(21-686c)-Contact%20Center%20Product%20Guide.pdf
