### ISSUE TITLE
[CST] Create feature toggle for expanded claim phases release

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#82361]
---
## Background Context
We need a feature toggle to put behind all feature development for claim phase work. 

Design vision for that work can be seen[ here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713276576012/25e677b1d846aff3bea16fc9175e473d5e509888?sender=u7b04181b0deced23bce71680).

## Engineering notes
- Feature toggle name: `cst_claim_phases`

## Tasks
- [ ] Create a PR for vets-api to add the feature toggle
- [ ] Create a PR for vets-website to add the feature toggle

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] We have the ability to hide pieces of content related to the claim phase release
