### ISSUE TITLE
Write Transcript for Contact Center Product Guide Video for View/Modify Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8237]
## Goal
The Contact Center requires documentation on our feature in the event that anything happens, they can review the expected behavior and either resolve the issue immediately or escalate as appropriate.  This includes a video walkthrough and voice over of the feature.

## Tasks
- [x] Walk through the full application
- [x] Create notes for the script
- [x] Write the transcript

## Acceptance Criteria
- [x] The transcript has been saved in the team GH folder's feature's contact center folder.

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/view-and-update-dependents/contact-center/21-686c-contact-center-walkthrough-video-transcript.md
