### ISSUE TITLE
[CST] [ENG] Claim Card updates on the main CST page

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#82376]
## Value Statement
**_As a_** Veteran visiting the claims home page to review my in progress and closed claims,
**_I want to_** see key information at a glance about my claims
**_So that_** I can see pertinent information like current step and brief description without seeing the full claim details

---
## Background Context
As part of improving the claim phase experience, we aim to increase transparency on the background process of claims. To start, we are expanding the claims steps from 5 to 8 steps and providing a brief description about each step. Additionally, we are providing claims updates so Veterans can have a better sense of where they are in the claims process. 

For additional information see resources listed below: 

- [Collaboration Cycle for Benefits team 1, Claim status tool , Claim Phase Experience](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71293#top)
- [Figma file](https://www.figma.com/design/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?node-id=1911-36561&t=ouEH8MXj79IYrcze-4)
- [Overview page (figma)](https://www.figma.com/design/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?node-id=1835-9127&t=c5B0ZffrBJ0wnsgV-4)
<br>
<img width="419" alt="Screenshot 2024-05-06 at 12 23 53 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/6608da0d-936d-465f-82d4-219a8223166e">

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- [Epic Link, Expand Claim Phases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82360)

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Ensure revised mocks are ready for engineers
- [Figma file](https://www.figma.com/file/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=1835-8610&mode=design) for visual reference
- [Figma file for CST home page claim card](https://www.figma.com/design/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?node-id=1911-36561&t=S0VM9s4Mfe7DqUtl-4)

### Enablement team (if needed)
@member of team

## Engineering notes
- Make sure that the claim cards call the helper function isDisabilityCompensationClaim to determine if the 8 phase steps should show or not

## Out of scope
- Add here

## Open questions
- This ticket description/ac/mocks are hard to understand. What are we wanting to accomplish with this ticket?

## Tasks

- [x]  Make a request with LH so that the claims list api returns the field claim.attributes.claimPhaseDates.latestPhaseType
- [x] Update vets-api-mockdata so that lighthouse/benefits_claims/index/default.yml has the field claim.attributes.claimPhaseDates.latestPhaseType
- [x] Update vets-api-mockdata so that lighthouse/benefits_claims/index/default.yml has the field claim.attributes.claimTypeCode
- [x] _the step should match the accordion name in the overview page (ie. Step 2 of 8: Initial review, Step 3 of 8: Evidence gathering etc)
- [x] _link inside the claim card should read "Details"_
- [x] _Add the date the claim moved to a step (ie. "Moved to this step on December 28, 2023")_
- [x] isDisabilityCompensationClaim() should be called to verify the claimTypeCode as well as the feature flag cst_claim_phases

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ]  LH api call for Claims List returns the field `claim.attributes.claimPhaseDates.latestPhaseType`
- [x] vets-api-mockdata for file `lighthouse/benefits_claims/index/default.yml` has the field `claim.attributes.claimPhaseDates.latestPhaseType`
- [x] Update vets-api-mockdata so that `lighthouse/benefits_claims/index/default.yml` has the field `claim.attributes.claimTypeCode`
- [ ] _The component in the "Your claims, decision reviews, or appeals" section matches the details in the mocks_
- [ ] Phase titles conform to the new 8 step phase process; when a claim is in phase x it shows that the claim is in phase x. 
- [ ] The name of the step the claim is in matches exactly the name of the the claim phase step on the Overview page.
- [ ] The claim  cards only shows the 8 steps language when claim is a disability claim and no other claim types
- [ ] Behind cst_claim_phases feature flag

**Comment by pmclaren19** [comment]
@uxgary This ticket is missing some details. I cant tell here what it is that you are specifically wanting us to change. Can you please add detailed tasks to note what you expect to be changed within this ticket? Looking at the screen shots and mocks you added it there are no specifics called out as to what you are wanting to change other than I see the #8 now.

**Comment by uxgary** [comment]
updated

**Comment by pmclaren19** [comment]
Started working this ticket and found that the api call that we use to currently get the status from only provided the 5 steps and not the 8 steps; claim.attributes.status. In order to get the 8 steps we will have to make a request to lighthouse to return claim.attributes.claimPhaseDates.latestPhaseType to us in the api call. Will work with @jerekshoe to make this request to lighthouse. This will also require us to update the vets-api-mockdata for lighthouse/benefits_claims/index/default.yml so that it has access to the new field that LH will return.

Will add tasks/ac for these two things!

**Comment by pmclaren19** [comment]
LH Request noted here to Kayla W https://dsva.slack.com/archives/C04KHCT3ZMY/p1717083330841159

**Comment by pmclaren19** [comment]
@jacobworrell  updated ticket tasks/ac to include calling the helper function isDisabilityCompensationClaim()

**Comment by pmclaren19** [comment]
Updating the tasks and a/c to also include adding the claimTypeCode to the vets-api-mockdata since this field is required inorder to determine if 5 or 8 steps should show

**Comment by pmclaren19** [comment]
Merged prs for vets-api-mockdata and also merged the vets-website pr to implement this change. I tested and verified the change in Staging and it looks good. Closing ticket but @skylerschain and @jacobworrell please feel free to validate and let me know if you notice anything off!
