### ISSUE TITLE
Fix errors in E2E and Unit Test Stress Test overnight jobs

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#82378]
## Issue Description
The overnight E2E stress test and Unit Stress Test jobs are consistently failing. This is resulting in flaky tests not being disabled without manual intervention, which is causing our CI to be more flaky than desired. These checks need to be diagnosed for errors, and corrected. These should also be checked for self-hosted runners and have those switched to GitHub runners.

---
## Tasks
- [x] Diagnose errors with E2E and Unit Test overnight stress test jobs.
- [x] Correct any errors that are stopping these checks from finishing accordingly
- [x] Move any self-hosted runner declarations to the equivalent GitHub runners that are used in CI.

## Acceptance Criteria
- [x] The E2E Stress Test and Unit Test Stress Test jobs are succeeding as expected.
