### ISSUE TITLE
[CST] Claim phases 5-8 accordion items

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#82377]
## Value Statement
**_As a_** veteran checking the status of my compensation claim
**_I want to_** see a clear description of each of the last four claim phases and understand where I am in the process
**_So that_** I know what to expect next and understand what actions I can take to help my claim get a timely and favorable decision.

---
## Background Context
This ticket represents one half of the claim phases that will ultimately need to be presented in an accordion. Design screenshots are below: 

![Screenshot 2024-05-06 101141](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838260/04336b04-7595-4b45-8ecc-6f9c58ad42a7)

![Screenshot 2024-05-06 101213](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838260/80f74d64-6fec-4fdf-8fd5-0f3093e1947e)

## Related Issue(s)
- department-of-veterans-affairs/va.gov-team/issues/82370

## Design
- [Figma file](https://www.figma.com/file/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=1835-8610&mode=design)
- [Figma link for accordion](https://www.figma.com/design/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?node-id=2162-5612&t=S0VM9s4Mfe7DqUtl-4)
- [Content doc including status page blurb and overview tab](https://docs.google.com/document/d/1WfWCfoQgKoMBg835VP7j_ptXmqb2o3RVme2u5dMOEr8/edit?usp=sharing)
- Design determines what the visual indicator (icon) will be for phase 8. 

### Enablement team (if needed)
@member of team

## Engineering notes
- See "Engineering notes" section in related ticket above for notes

## Open questions
- Can we get a link to the design added to the design section?
- Where does the "Go to the status page for this claim" link go?
- What does the timeline look like when we are on step 8?

## Tasks
- [x] Add step 5 with subtext
  - [x] Add the banner with icon + text
- [x] Add step 6 with subtext
  - [x] Add the banner with icon + text 
- [x] Add step 7 with subtext
- [x] Add step 8 with subtext
  - [x] Add the "Go to the status page for this claim" link
  - [x] "Go to the claim letters page" link should navigate to the claim letters page
  - [x] When step 8 is current step, icon should be a green checkmark
- [x] Make sure the current phase has the 'Your claim is in this step' text.
- [x] Add logic so that the accordion item that matches the current step is open when the user navigates to the 'Overview' tab
- [x] Add unit tests
- [x] Add cypress tests for the claim phase stepper

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria

- [x] Will be behind the expanded claim phases feature toggle.
- [x] Each claim phase "step" will be represented as an item in the same accordion used in ticket #82370 and will expand all and collapse all according to the functionality described in that ticket.
- [x] Each accordion item corresponds to a claim phase or "step" and will have a title, visible in both the collapsed and expanded state, that calls out what the claim phase is.
- [x] If the user has already completed a step in the claim phase process, there will be a visual representation that indicates this step has been completed and this will be visual in the collapsed and expanded states.
- [x] If the user is presently in the claim phase "step" there will be visual indicator visible in both the expanded and collapsed state. 
- [x] When a user navigates to the Overview tab the current phase "step" will be expanded and there will be content telling them the date they entered that phase. 
- [x] The expanded state of Step 5, the "Rating" phase will have a description of what that phase is. 
- [x] The expanded state of Step 6, the "Preparing Decision Letter" phase will have a description of what that phase is. 
- [x]  Step 5 and Step 6 will indicate that this particular step can repeat when in the expanded state. 
- [x] The expanded state of Step 7, the "Final Review" phase will have a description of what that phase is.
- [x] The expanded state of Step 8, the "Decision Letter Available" phase will have a description of what that phase is.
- [x] Step 8 will also include a link to the claim letters section of CST so they can download their decision letter.
- [x] When Step 8 is current step, icon should be a green checkmark
- [ ] There are cypress tests for the claim phase stepper
- [x] Behind cst_claim_phases feature flag

**Comment by pmclaren19** [comment]
Updated ac/ tasks to account to writing cypress tests @jacobworrell .

**Comment by pmclaren19** [comment]
The design hadn't factored in how we wanted step 8 to look with the claim was closed. Discussed with the team in slack https://dsva.slack.com/archives/C056854SVT8/p1716499618319909 and we are going to make it so that when a user is on step 8 the checkmark icon appears for that step. Updating AC and tasks to reflect this @jacobworrell

**Comment by pmclaren19** [comment]
Noticed that the link in Step 8 said `Go to the status page for this claim` and was supposed to send users to the status tab but given the description text it seems like it would be better suited if it took users to the claim letters page. 

Discussed in slack [here](https://dsva.slack.com/archives/C056854SVT8/p1717085253677319) and [here](https://dsva.slack.com/archives/C056854SVT8/p1717010933049219).

After talking with @uxgary we will change the text from `Go to the status page for this claim` to `Go to the claim letters page`. Gary has updated designs!

**Comment by uxgary** [comment]
I wanted to note that in step 7, the content states that this step can revert back to step 3 if more evidence is needed or if more evidence is added. I will create a new ticket so we can update the steps diagram

**Comment by pmclaren19** [comment]
Updated ticket ac and tasks to reflect the link change in step 8

**Comment by pmclaren19** [comment]
@uxgary please review for qa design.

**Comment by pmclaren19** [comment]
Per conversations yesterday with @uxgary we are renaming step 8 to no longer say 'Decision decided' and to instead say 'Claim decided'. Gary has updated all designs. I will make a new pr for this change.

**Comment by uxgary** [comment]
Reviewed, this passes.
