### ISSUE TITLE
Convert remaining output variables around testing to JSON files to avoid future issues with test suite growth

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#82381]
## Issue Description
We've seen two separate incidents of CI throwing errors because of an output variable getting too long where it exceeds the maximum character length allowed for an environmental variable in GHA. We need to evaluate these variables and be proactive about converting any more that may need this solution applied (the e2e tests list is already one that I feel confident will need it).

---
## Tasks
- [x] Evaluate CI variables around testing and see which outputs may be vulnerable to hitting a max character limit in the future
- [x] Convert any vulnerable outputs to storing their data in JSON files and passing via artifact upload/download
- [x] Test all altered jobs for stability and reliability.

## Acceptance Criteria
- [x] Future risk of CI breaking due to environment variable length being exceeded has been mitigated.
