### ISSUE TITLE
Content and UI audit of appeal states in CST

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#82386]
## Background Context

**TO DO SPRINT 59:** Resolve comments in ongoing [Board Appeal Page Content](https://docs.google.com/document/d/14gAFM2tuQWE3OdqUP0wqP1DSnRzDrhDRgeLmoB2YaTE/edit) doc

-----------

BVA and the team want a better understanding of the various UI states we are currently showing to Veterans for in CST for board appeals. It has been a long time since BVA has seen or provided input on the CST appeal experience and there are things that we will likely need to change to ensure Veterans are seeing the correct information.

[This ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80464) surfaced some content that needs to be revised, but that is only showing one possible UI state.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- [WIP Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714748626644/91d587cd82f27729eba6bcf07b92bb9b27aab5f4?sender=u80fb5a3b8f7951f35d701197) showing all available statuses and screenshots related to them.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0M0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23a6ce7d2c09c061f4e193fdc10083e975667acb/Screenshot%202024-05-06%20at%2011.26.19%E2%80%AFAM.png" alt="Screenshot 2024-05-06 at 11.26.19 AM.png" />

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Capture screenshots of all possible UI states for board appeals in CST_
- [ ] _Sync with BVA to review these_
- [ ] _Incorporate any BVA feedback on how content should change_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_

**Comment by jacobworrell** [comment]
@skylerschain @uxgary is this a duplicate ticket, do we still need to build out additional UI states into the app map?

**Comment by skylerschain** [comment]
Next steps: Update [doc](https://docs.google.com/document/d/14gAFM2tuQWE3OdqUP0wqP1DSnRzDrhDRgeLmoB2YaTE/edit) based on review feedback from @amylai-va and @jstrothman.

**Comment by jacobworrell** [comment]
@skylerschain please size this ticket so we can get into the next sprint.
