### ISSUE TITLE
Record Contact Center Product Guide Video and Voiceover for View/Modify Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8238]
## Goal
The Contact Center requires documentation on our feature in the event that anything happens, they can review the expected behavior and either resolve the issue immediately or escalate as appropriate. This includes a video with voiceover.

## Tasks
- [x] Record full application walkthrough with notes to inform the voiceover
- [x] Revise voiceover transcript
- [x] Record voiceover

## Acceptance Criteria
- [x] A video has been edited and shared with the team, link entered into relevant Contact center Documentation

**Comment by jason-gcio** [comment]
uploading via LFS

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/view-and-update-dependents/contact-center/686%20Walkthrough%20Video%20Contact%20Center.mp4
