### ISSUE TITLE
Determine IA Approach, Redirects, (new) URLs for L4+ Benefit Hubs Updates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8239]
## Goal
Big goal for this initiative: Reduce level 4+ content down to max of 4 levels (there is a review of the hubs + recommendations taking place in #8049 )
Goal for this ticket:
Recommend IA approach to the changing of this content
Recommend new URLs as/if needed
Recommend the approach to redirects as/if needed

The specific recommendations will be available in the page audit. In #8049 the page audit + initial recommendations will be reviewed and finalized. 

**Repo:**
(contains the Audit completed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/5236)
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/header-footer-and-navigation/page-nav

---
## Tasks
- [ ] Based on the recommendations approved by Danielle (or perhaps in collaboration with the recommendations as they are reviewed?) provide a recommendation of IA, URL, redirect approaches to the shifting content
- [ ] Ensure that finalized recommendations are saved, and made available so the team can implement

Note: Because we are minimizing the amount of levels for the content structure, content could:
* be shifted from its current level to L4 or higher
* be added to another section as L4
* be consolidated with another piece of content that is already L4 or higher
* be consolidated with another piece of content and then shift to L4 or higher
* be removed

## Acceptance Criteria
- [ ] Recommendation for IA approach to the L4+ benefit hubs updates is available
- [ ] Necessary URLs that are new and needed are outlined so the team can implement
- [ ] Redirects that are needed are outlined so the team can implement

Level 4 and 4+ child pages have been identified and inventoried for each benefit hub:
- [ ] Health care
- [ ] Disability
- [ ] Education
- [ ] Pension
- [ ] Careers
- [ ] Burials
- [ ] Records
- [ ] Housing
- [ ] Life insurance
---
## How to configure this issue
- [ ] **Attached to a Milestone**
- [x] **Attached to an Epic**
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by stephorkandatx** [comment]
@mnorthuis we are queuing a ticket to review and solidify recommendations on how to adjust Benefit hubs pages that are L4+ (L4, L5, etc). so that there is a max of 3 levels to navigate. 

We will want to review the IA - how to handle this shifting/consolidated/removed?/etc. content - so that we are following the right approach, are setting up new URLs correctly (if needed), handling redirects correctly.

We have an initial audit + initial recommendations readily available to give a sense of changes, but I imagine having the final recommendations would make the IA work clearer to work through. We plan to have the recommendations solidified within the coming sprint. Both the recommendations + the IA would come before implementation work. 

Is this something that we could incorporate into the next sprint? Is this a body of work that would be better split up by the hubs vs having all in one ticket?

cc @meganhkelley

**Comment by mnorthuis** [comment]
@stephorkandatx  I will definitely put this into our next sprint, which starts 4/30. I would like to be able to work through this in collaboration with @DanielleThierryUSDSVA.

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis @stephorkandatx @lwalsh617 As I'm creating the life insurance rewriting restart issues, I am noting that the original IA recommendations for those pages will likely change based on this initiative. For example: The original url for the SDVI rates pages was /life-insurance/options-eligibility/s-dvi/premium-rates/. That will need to change to avoid the depth of pages. Just adding a general note here as well so this need for shifting is clear across the different initiatives. Thanks!

**Comment by mnorthuis** [comment]
@stephorkandatx 

I have reviewed the audit at a high level along with @DanielleThierryUSDSVA 

My original understanding of this work was to focus on trying to keep content to 4 levels or less, but it looks as though I misunderstood and the ask is to go down to max 3 levels?

There are a couple of questions/comments around this:
- What is driving this ask and what is the goal of "flattening"?
- We can't force the IA to a specific number of levels, but we can review the content strategy and structure of the content (IA) to reevaluate what we currently have in place to determine if there is a different way to approach content. For example, some of the deeper sections pre-date Danielle and I on Vets.gov and were built prior to content strategy and IA roles, and could benefit from a review and _possible_ restructure.  
- In reviewing the audit, there is a bit of inconsistency and inaccuracies in what is being counted as level 4 or 5 content, so we need to firm up on what areas of the IA/content we want to review.

Let Danielle and I know if you want to talk through this - I'm thinking that is likely the case.

**Comment by stephorkandatx** [comment]
@mnorthuis seeing this now.
The original request was to reduce the level 4+ content down to max of 3 levels. I'll ping @jenniferlee-dsva to speak more to the goal of flattening the benefit hubs content to ensure I am not missing or misconstruing discussions and goals.

Related: when this work is completed, we have a desire to adopt the new left navigation currently on VAMC Pittsburgh. They did research with users, and I'd need to pull up their findings to get the specific wording but they found that users have a difficult time finding content that is "deeper" within the site. With the new left nav they have a goal to help users find their content and tool within a couple clicks.

Based on your note regarding possibly restructuring some of the older sections as well as the call-out over what is considered a level 4 or 5 piece of content, it may be best to talk through this together and determine what the next step is for this effort. I will check calendars.

**Comment by mnorthuis** [comment]
Thank you @stephorkandatx . 

I do want to reinforce that the working directive should not be to force the IA to a set number of levels.  We can work towards keeping a shallow IA (which I/we always have), but the amount of content and how its written impacts the overall depth of the IA.  We should not be moving a page out from level 5 and up to level 2 just to keep a shallow IA - the goal should be to review pages in that hierarchy to see if they can be written differently to reduce depth.  If they ultimately cannot be, then the area stays at 5 levels.  

Also, the VAMC left nav design does allow up to 4 levels, and there are currently options for content that goes beyond that or content that we don't want to represent in the left nav.  And we can (should) look at design and UX enhancements to accommodate the level of content we have in the benefit hubs.   

There is a TON of content in the benefit hubs sitting at level 4. 

Here is a page where the left nav of the VAMC sites goes to 4 levels: https://staging.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/psychology-internships-and-fellowships/

**Comment by stephorkandatx** [comment]
Updated request to say we are trying to bring content to 4 levels (or less) per conversation on 5/14/2020. Epic updated to reflect this as well.
