### ISSUE TITLE
[CST] Claim updates in the recent activity

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#82417]
## Value Statement
**_As a_** Veteran checking on my claim progress,
**_I want to_** have a see a chronological list of activity regarding my claim
**_So that_** I can know what specific actions has been within the process. 

---
## Background Context
As part of improving the claim phase experience, we aim to increase transparency on the background process of claims. To start, we are expanding the claims steps from 5 to 8 steps and providing a brief description about each step. Additionally, we are providing claims updates so Veterans can have a better sense of where they are in the claims process. 

For additional information see resources listed below: 

- [Collaboration Cycle for Benefits team 1, Claim status tool , Claim Phase Experience](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71293#top)
- [Figma file](https://www.figma.com/file/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?type=design&node-id=1835-8610&mode=design) for visual reference

<br>
<img width="339" alt="Screenshot 2024-05-06 at 11 37 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/68d516f9-517a-4f50-91ad-353775af383e">

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- [Epic Link, Expand Claim Phases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82360)

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Ensure revised mocks are ready for engineers

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _The component in the "Recent activity" section matches the style in the design
- [ ] _"Recent activity" displays plain language information about actions taken on the claim
- [ ] _AC_
