### ISSUE TITLE
EKS Upgrade Testing Plan: Create new channel for EKS testing alerts

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#82426]
## Description
We plan to establish a new Slack channel in DSVA (OCTO?) specifically for our EKS automation alerts testing suite. Existing channels are currently overwhelmed with notifications, making it challenging to track and address specific issues efficiently. By creating a dedicated channel for EKS alerts (ex: synthetic test failures and logs), we aim to streamline our monitoring process. This focused environment will allow us to quickly identify and resolve issues, ensuring that important alerts are not overlooked amongst the general channel noise.

## Tasks
- [x] Create New Slack Channel for **EKS Upgrade Testing Alerts**
- [x] Advertise this new channel to all involved parties (Reliability and Infra)
- [x] Add channel as an integration to Datadog

## AC
- [x] New channel is created
- [x] Involved parties are aware of new channel
- [ ] Channel is added to Datadog <> Slack Integration

**Comment by jennb33** [comment]
Slack alert in Platform Tech team: <img width="1423" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekFaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b1ea576642af6febf0853f9231bc620bdf0266c/image.png" alt="image.png" />

**Comment by jennb33** [comment]
Slack alert to those members not in Platform Tech team channel: <img width="1412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenNaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5161b48f5105a626434723d8961d0233d0b2887d/image.png" alt="image.png" />
