### ISSUE TITLE
Platform Atlas - Calculate VFS Staff

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#82432]
### Description
Part 2 to [original ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/80348) involving filling out null VFS staff start dates. 

This portion of the ticket imports the spreadsheet to Platform Atlas and runs the query.

Support team needs to know how many VFS staff we have Jan 1 2023 to March 30 2023 versus Jan 1 2024 to March 30 2024 in order to show the ratio of support people to onboarded VFS people. 

### Tasks
- [x] Run bulk import of spreadsheet for start dates. 
- [x] Run report per the attached image (in Slack chat between Lindsey and Alyssa)

## Success Metrics
- [x] That a report has been generated for Alyssa in Support

### Acceptance Criteria
- [x] Report for 2023 and 2024 on VFS staff in Atlas

<img width="1709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dac6d4c3eb1335a8b5e66e33b9ac2722a3fa2450/image.png" alt="image.png" />

**Comment by rmtolmach** [comment]
@RachalCassity to take over since Ryan is on Support this sprint.

**Comment by RachalCassity** [comment]
@alyssagallion 
staff_active_2023 = 389
staff_active_2024 = 671
```

irb(main):002> staff_active_2024 = ProductDirectory::TeamMember.where("start_date is NOT NULL AND start_date <= ?", "03/30/2024").where("end_date is NULL OR end_date > ?", '1/1/2024').size
=> 671
irb(main):003> staff_active_2023 = ProductDirectory::TeamMember.where("start_date is NOT NULL AND start_date <= ?", "03/30/2023").where("end_date is NULL OR end_date > ?", '1/1/2023').size
=> 389
```

**Comment by RachalCassity** [comment]
@LindseySaari @jennb33 Reported 2023 and 2024 results in this [slack thread](https://dsva.slack.com/archives/C02RLAUM2LV/p1715361863233289)
Closing this ticket.
