### ISSUE TITLE
Preserve secondary disability relationship to its primary during backend processing

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#82435]
## Issue Description
[Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1714155410545919)

When selecting the "SECONDARY" option for a disability in the 526EZ app, the UI makes you explicitly select the primary disability that the disability is related to- along with the normal description text. However, when the user clicks to submit the form, instead of _preserving_ that relationship for the backend to process, the front end resets the secondary disability to `cause = "NEW"` and adds the text "Secondary to XXX" to its `primaryDescription` field (where XXX its primary disability). 

The result on the backend of this is that, when the API request is being formed (in [DataTranslationAllClaim](https://github.com/department-of-veterans-affairs/vets-api/blob/9d5142768f653a7e1646968f3f4089ba109df4d9/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L49)), the disability is treated as just another primary disability, and the special [code](https://github.com/department-of-veterans-affairs/vets-api/blob/9d5142768f653a7e1646968f3f4089ba109df4d9/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L501) to form the parent/child relationship between it and its primary in the API request is **always ignored**. 

This has been seemingly status quo since the code was written 5 years ago, and presumably working "well enough" because the VSRs can still see this primary/secondary relationship in the "Secondary to XXX" text. So when the front end is "fixed" to preserve the relationship in the API request, it is currently unknown what the downstream effects will be. Some chatter on [this thread](https://dsva.slack.com/archives/C5AGLBNRK/p1523312270000371) suggests that these relationships are generally flattened and/or lost during processing in upstream systems, but it's also possible that some important processing might be missing as a result of this lacking relationship. Consequentially, it would be recommended to gate this frontend "fix" with a feature flag, so that its impact can be carefully studied on Staging before releasing to Production.

<img width="613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWk1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cc15d1adfb3fac4d7b200772f3c2921b386dfa6/image.png" alt="image.png" />

---
## Tasks
- [ ] Add flipper flag-gated "fix" to frontend submit transformer to send secondary disabilities with cause = "SECONDARY"
- [ ] Test backend with new FE fix to ensure the API request is still being successfully formed

## Acceptance Criteria
- [ ] 526ez submitted with primary/secondary relationship preserved, producing a valid PDF in the VBMS eFolder

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
