### ISSUE TITLE
[DevOps] Eric Oliver's Magical PAS Mystery Tour

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82439]
Just collecting some access things for Eric:

## Tasks
- [x] GFE
  - [x] Admin access to GFE
- [x] PAS 2.0
  - [x] VA PAS Users
  - [x] CyberArk
  - [x] `vaec-cms` access
  - [x] `vaec-cie` access

## Acceptance Criteria
- [ ] Eric has access to all of the above and whatever I've forgotten.

**Comment by olivereri** [comment]
Following documentation here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/team/onboarding.md

**Comment by olivereri** [comment]
Also, I reached out to Lauren Ernest and she has submitted an application for a GFE.

**Comment by olivereri** [comment]
ePAS request #4840572 submitted

**Comment by olivereri** [comment]
Required TMS training completed and sent to COR.
