### ISSUE TITLE
[DevOps] Eric Oliver CIE access stuff

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82440]
Some non-vaec access stuff for Eric.

## Tasks
- [x] full flipper access see e.g. https://github.com/department-of-veterans-affairs/va.gov-team/issues/82414
- [x] `vets-api` terminal access see e.g. https://github.com/department-of-veterans-affairs/va.gov-team/issues/82415
- [x] elevated privileges on:
  - [x] [CHIP API](https://github.com/department-of-veterans-affairs/chip)
  - [x] [LoROTA API](https://github.com/department-of-veterans-affairs/lorota)
  - [x] [checkin-devops](https://github.com/department-of-veterans-affairs/checkin-devops/)
  - [x] [cie-staging-scheduler](https://github.com/department-of-veterans-affairs/cie-staging-scheduler/)
- [x] member of [patient-check-in](https://github.com/orgs/department-of-veterans-affairs/teams/patient-check-in)

## Acceptance Criteria
- [ ] Eric has access to all the above.

**Comment by olivereri** [comment]
Flipper: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82594
Vets-api Terminal: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82595

@ndouglas Since you have elevated access to the CHIP, LoROTA, checkin-devops, and cie-staging-scheduler repositories can you elevate my access, or is there a formal process?

**Comment by ndouglas** [comment]
Yep!

Added to:
- CHIP
- LoROTA
- checkin-devops

I don't have admin access to `cie-staging-scheduler`. @brianseek is the one to ask there.

Also, you need to be a member of this team (I'll amend the ticket): https://github.com/orgs/department-of-veterans-affairs/teams/patient-check-in and I can't add you there.

**Comment by brianseek** [comment]
Just added both of you to https://github.com/department-of-veterans-affairs/cie-staging-scheduler
