### ISSUE TITLE
Address event issues for Find a Rep Analytics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82489]
## Background
The Analytics team is helping us to setup tracking for our Find a Representative product and noticed some issues with our events:
1. When I initiate the first search, an extra, incomplete `far-search-results` fires before the real (?) `far-search` and `far-search-results` events.
2. The `search-filters-list` variables for the `far-search` event aren't formatted correctly -- it's normal language instead of the dashed version, ex "Type of accredited representative instead" of the expected `representative-type`.
3. `far-search-results-change` is not firing at all. Instead, a new `far-search` and `far-search-results` events pair fires when the filters are changed and nothing fires on sort.
4. The `far-search-results-click` and `far-search-results-outdated` events do not have any values in the `search-results-total-count`, `search-results-total-pages`, `search-result-position` and `search-result-page` variables.

Screenshots are in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70420#issuecomment-2096289352) for additional context.

## Tasks
- [ ] Remove the extra, incomplete `far-search-results` event that fires before the "real" `far-search` and `far-search-results` events.
- [ ] Update the `search-filters-list` variables to use the dashed formatting
- [ ] Update `far-search-results-change` to ensure it's firing as expected
- [ ] Ensure the `far-search-results-click` and `far-search-results-outdated` events are connected to the `search-results-total-count`, `search-results-total-pages`, `search-result-position` and `search-result-page` variables

## Acceptance Criteria
- [ ] All of our events are setup properly so that Analytics can complete the implementation in Google Tag Manager.

**Comment by oddball-lindsay** [comment]
Some of these may be related to bugs in the component library.  Will need to dig in to find out / be sure.
