### ISSUE TITLE
Kubernetes on Codespaces for Development

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#82499]
A reproducible way to test Kubernetes deployments for non-devops (e.g. engineers w/o the ability to spin up new k8s clusters in AWS) is not readily available. Having this would allow simple testing of new helm charts. Kubernetes also requires a lot of resources so a non-local dev env is desirable. GitHub Codespaces satisfies these needs.

## Tasks

- [x] Determine best approach to running Kubernetes (k8s vs k3s vs minikube)
- [ ] Connectivity to remote cluster is established
- [ ] Stubbed-chart is applied and tested (e.g. nginx "Hello World")
- [ ] Documentation written on accessing cluster

## AC

- [ ] A per-developer Kubernetes cluster can be provisioned in Codespaces 
- [ ] The Kubernetes Codespace is available for testing new manifest/chart development
- [ ] Steps to create this cluster are provided

## Resources

- https://github.com/cse-labs/kubernetes-in-codespaces
- https://medium.com/@armamini/kubernetes-on-github-codespaces-3851163411f3

**Comment by ericboehs** [comment]
I'm having permission issues between minikube and docker. Should just be about a day's worth of work once I get that fixed (assuming other issues don't arise).

**Comment by ericboehs** [comment]
I'm deprioritizing this one as it's not blocking the GIDS work. Some prod issues need to be focused on. Will reopen w/ a new ticket to debug the issue I'm stuck on here.
