### ISSUE TITLE
[CST] [ENG] Deprecate "Ask for your claim decision" experience

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#82491]
## Background Context

As part of the update 5103 work, we will be deprecating the "Ask for your claim decision" experience, which includes: 
- The blue alert
- The subsequent "Ask for your claim decision" page
- The confirmation

The functionality to be able to submit the 5103 waiver will be incorporated into the new 5103 alert.

Current UI for "Ask for your claim decision" alert 👇

<img width="1319" alt="Screenshot 2024-05-06 at 3 50 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/5645752f-ea44-421b-b09f-584f1f35d80c">

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
[Figma for updated 5103 request](https://www.figma.com/file/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-and-5103-alert?type=design&node-id=2-11&mode=design)

### Enablement team (if needed)
@jstrothman 

## Engineering 
Put behind feature flag `cst_5103_update_enabled`

## Out of scope
- This only includes the removal of "Ask for your claim decision" UI. For 5103 work, see other tickets in this epic.

## Open questions
- Add here

## Tasks
- [ ] Remove blue "Ask for your claim decision" alert on the Files Tab
- [ ] Remove "Ask for your claim decision" page
- [ ] Remove confirmation that shows up after user clicks Submit on the "Ask for your claim decision" page
- [ ] Remove any other logic associated with the "Ask for your claim decision" experience
- [ ] Put behind feature flag cst_5103_update_enabled. (above things are hidden when ff is enabled)

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The 'Ask for your claim decision' page no longer appears
- [ ] The 'Ask for your claim decision' route no longer works
- [ ] The 'Ask for your claim decision' banner no longer appears on the files tab
- [ ] The page, route, and banner are behind feature flag `cst_5103_update_enabled`. (hidden when ff is enabled)

**Comment by pmclaren19** [comment]
Updated ticket ac during Eng Refinement.

**Comment by jerekshoe** [comment]
It's possible that we don't want to deprecate this experience quite yet, as there are 2 different tracked items asking for the 5103 waiver notice response, Automated 5103 Notice Response and 5103 Notice Response. The first (Automated 5103 Notice Response) is associated with Custom 5103 Notice Response letters and the second (5103 Notice Response) is associated with Standard 5103 Notice Response letters. Currently only the Automated 5103 Notice Response tracked items shows up in CST in an open state (the 5103 Notice Response tracked item only shows up after it has been marked as closed or received), but users will still get a letter in the mail asking them to submit the 5103 Notice response regardless. Worth consideration I think

**Comment by skylerschain** [comment]
@jerekshoe Is there a reason we don't show the 5103 Notice Response tracked item in CST until it's closed?

**Comment by jerekshoe** [comment]
BGS doesn’t treat it as a first or third party request so Lighthouse isn’t able to return it to us until the tracked item shows up in the list of closed / received tracked items they get from BGS

**Comment by skylerschain** [comment]
So if we do nothing here will this "Ask for your claim decision" banner ONLY show up for Standard 5103 notices? And the 1P alert will show up (but not the banner) for Automated 5103 Notice?

**Comment by jstrothman** [comment]
>Currently only the Automated 5103 Notice Response tracked items shows up in CST in an open state (the 5103 Notice Response tracked item only shows up after it has been marked as closed or received), but users will still get a letter in the mail asking them to submit the 5103 Notice response regardless. 

@jerekshoe Does the 5103 Response Notice show up in Claim Letters?

@skylerschain From your understanding, _should_ the 5103 Notice Response show up as a 1P request? In the claim letters? If yes, should we add this to our requests for Lighthouse?

**Comment by skylerschain** [comment]
Yes I think it should show up in CST as a 1P request, since we are asking for the Veteran to do something (review the letter and submit the waiver or more evidence). So yes, I think we should add it to our BGS requests.

**Comment by jacobworrell** [comment]
closing as this ticket is no duplicative with work that will effectively deprecate the old 5103 experience
