### ISSUE TITLE
Update Ticketing Best Practices Page for Accuracy to Current Process

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#82490]
## Description 
This ticket will house the task of updating the Ticketing Best Practices doc [here.](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Ticketing+Best+Practices)

---

## Definition of Done
All tasks below are complete

---

## Tasks 
_Steps to reach definition of done._ 

- [x] Decision making process to make onboarding easier for tier 1
- [x] Link CoP on CoP escalation section of ticketing best practices 
- [x] Figure out a place for a section on if someone’s slack profile is missing info (Atlas App)
- [x] Labeling Overview: platform-support-ticket and platform-sprint-work
- [x] Add: https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/2870903148/Locating+Labeling+Access+Requests
- [x] [Add this doc to the documentation](https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/2870903148/Locating+Labeling+Access+Requests) 
- [x] Add any changes to the process in the doc
- [x] Add the [process listed here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426110021/PM+Support+Responsibilities#Tier-2-Support-Rotation-Admin-Tasks) to the Ticket Best Practices doc
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
<img width="717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFAyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0a322f7ddb225ab3aed6ed69dac21eacbac0f33/image.png" alt="image.png" />

I have created a doc for this, but have yet to place it anywhere. I don't feel it fits in ticketing best practices, but that can be something we discuss.

Here is the [doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3168665663/VFS+Team+Members+Empty+Slack+Profiles)

**Comment by bdech** [comment]
This [doc](https://vfs.atlassian.net/wiki/spaces/~71202042a6fc1723834684baa014f88ab016aa/pages/2870903148/Locating+Labeling+Access+Requests) has been updated to include up-to-date information on New VFS Team/Team Member requests, as well as Offboarding requests.

**Comment by bdech** [comment]
<img width="524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGIyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b220127899d7c4470c6f61519fc65ec7d78c8d05/image.png" alt="image.png" />

^ This section has been updated and includes respective links to each CoP.

<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFgyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01e120f4e62a7a766e0430a52a1e5100af0d5b81/image.png" alt="image.png" />

**Comment by bdech** [comment]
<img width="487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUgyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e49b55357340ec871be3ce95766a5008940dd1ef/image.png" alt="image.png" />

This section has been added to the Ticketing Best Practices doc
<img width="1028" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVQyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--954f010f6e6843483639aaba535217c8dbeebb39/image.png" alt="image.png" />
