### ISSUE TITLE
Copy of Develop submission model and success path for submit redesign

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#82511]
## Description
This ticket will establish a conceptual model for submission model at a conceptual level and apply it to the happy path for the submit experience redesign. This will inform the rest of the issues in [Improve submission user experience #78179](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78179).

Happy path channels / artifacts in scope for this might include:
1. Email message for happy path
3. Confirmation page
4. Pdf/print of confirmation page
5. Paper mail
6. Recommended touchpoint w/ Claims Status Tool
7. Recommended touchpoint w/ MyVA 
8. Recommended touchpoint w/ MobileApp

Begin this after [Desk research on the current state of claim submission and post-submission experience#79177](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/79177)

## Working documents

1. [Conceptual model - Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?wid=0-1714144026398)
2. [list of artifacts](https://docs.google.com/spreadsheets/d/1zjWxQ1uu9Qm504BMcaTKek4_RqQWfJodjTMpgNNr_NI/edit#gid=0)

## Tasks
- [X] ID model for for submission concept and naming
- [X] Map future-state journey for success path (channels within our control are clearly defined)
- [X] Identify where altered touch points are happening and what we want to convey with design changes. (to be detailed in later issues in [Improve submission user experience#78179](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78179))
- [ ] Consult engineer to assess basic feasibility/raise early concerns with design changes. 

**Coordination with other teams that factor into redesign:**
- [X] [Veteran Facing Forms Team's submission status work](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170) - ensure we are consistent with what they're doing
 - [x] Claim Status Tool future work](https://dsva.slack.com/archives/C04KHCT3ZMY/p1711641878963709?thread_ts=1711641594.321239&cid=C04KHCT3ZMY) - en sure we are consistent with what they're doing.
 - [x] Team 2 to incorporate their work into the same journey map
 - [x] [Veteran Facing Forms Team's to clarify our own scope](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1170) on changes to our confirmation pages - per [Slack](https://agilesix.slack.com/archives/C04MJV66ZPC/p1712950176309139?thread_ts=1712948394.643759&cid=C04MJV66ZPC)

## Acceptance criteria
- [x] Submission model/naming conventions are set
- [X]  Future-state journey map created for success path (channels within our control are clearly defined)
      - [ ]  Other channels (eg. CST, MyVA, Mobile app) are potentially addressed; if not, create a new ticket to track the 
               work continued into the future. 
- [ ]  Sync with engineer to flag concerns with design changes

**Comment by pacerwow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Disability-Experience-63dbdb0a401c4400119d3a44/issues/department-of-veterans-affairs/va.gov-team/82511?planning-poker) with Zenhub @mengA6

**Comment by pacerwow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Disability-Experience-63dbdb0a401c4400119d3a44/issues/department-of-veterans-affairs/va.gov-team/82511?planning-poker) with Zenhub @evelynhilbrichdavis

**Comment by pacerwow** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Disability-Experience-63dbdb0a401c4400119d3a44/issues/department-of-veterans-affairs/va.gov-team/82511?planning-poker) with Zenhub @Kate-allbee

**Comment by pacerwow** [comment]
It would be useful to know where the outcomes of this ticket will live once we have our learning. Could we/should we use the Feature Brief?

**Comment by mengA6** [comment]
@evelynhilbrichdavis linked to the findings about the current state of duplicate submissions in [this comment on the UX discovery ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/83163#issuecomment-2121149119). Later, it could be good to move this to either the [feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Submission%20Experience.md) or a standalone github page [like what we have for Toxic Exposure](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/toxic-exposure.md))

**Comment by mengA6** [comment]
Curently tracking the design work to reduce duplicate submissions in a task in [Detailed design for ancillary job failure in submission experience#82095](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/82095)

**Comment by mengA6** [comment]
Moved design work to reduce duplicate submissions to [Detailed design to reduce duplicate submissions#84154](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/84154) since we are talking about it as a separate stream of work
