### ISSUE TITLE
Create accessibility cookbook recipe

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#82538]
## Value Statement
**_As a_** accessibility specialist
**_I want to_**  write the second recipe for the accessibility cookbook
**_So that_** the accessibility cookbook has another recipe completed.

---
## Background

We created the [accessibility cookbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md) as a place to record solutions for all sorts of accessibility issues we run into in our day-to-day work. We need to start writing content to help it get off the ground.

## Acceptance Criteria
- [ ] New recipe is complete and uploaded to cookbook directory

## Tasks

- N/A

## How to Measure Success
_- Define the expected result and where to measure it._

- N/A

## Out of scope

- N/A

## Definition of Ready

- N/A

## Definition of Done
- [ ] One topic is completed, and added to the cookbook.
- [ ] A consistent "recipe" structure is followed. See cookbook.
- [ ] One accessibility specialist has reviewed the content.

**Comment by davidakennedy** [comment]
[Draft if When to use ARIA in the Cookbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md#when-to-use-aria-draft).

**Comment by davidakennedy** [comment]
This work is completed. I got feedback from @coforma-jamie and other specialists. The article is in the [same spot in the cookbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md#when-to-use-aria).
