### ISSUE TITLE
686 Phase 1 | Add and Remove Fields in 674

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#82536]
## Issue Description
_The online 686/674 form flow is outdated and needs to have missing fields added and depreciated fields removed or updated._

- [Figma file](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=911%3A41001&mode=design&t=cl1b0VMuzly75W3g-1)
- [Form Flow](https://app.mural.co/t/coforma8350/m/coforma8350/1693342568662/de8a4eb202d07e4802e1be45fe7f6a8f5d02128e?sender=u934f98f179a86c76e6ee9592)
- [Collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74059)

OLD 686: [686C-674.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98e91ac128750b96cc74a17fe22746478893b712/686C-674.pdf)
NEW 686: [VBA-21-686c-ARE.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9pQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a06d0f0e8261b8951122c837e810e54d41dba3c8/VBA-21-686c-ARE.pdf)

OLD 674: [21-674.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7f2146c13d3500f3a7fb167db8fdef6a5004682/21-674.pdf)
NEW 674: [VBA-21-674-ARE.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdd0cb68e93b81bd1d8bfa5b8f01132dc808534c/VBA-21-674-ARE.pdf)

---
## Tasks
- [ ] Add "Is the school accredited? y/n" question
- [ ] Add international phone number
- [ ] Remove 8A, 8B, 10B, 10C, 10D, 11B, 11C, 11D (see [notes on old pdf](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690311086208/96d5f59b299912bc8c69542e6943d5b2213b9c72?wid=0-1701373901961))
- [ ] Update language of "Is tuition and/or allowance for student's education or training being paid for by..." question to [this](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=291%3A44398&mode=design&t=AYTz3J1dLqTZfmmU-1)
- [ ] Update unit test coverage

## Acceptance Criteria
- [ ] "Is the school accredited? y/n" question has been added
- [ ] International phone number has been added
- [ ] Questions 8A, 8B, 10B, 10C, 10D, 11B, 11C, 11D from pdf (see [notes on old pdf](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690311086208/96d5f59b299912bc8c69542e6943d5b2213b9c72?wid=0-1701373901961)) have been removed
- [ ] Language of "Is tuition and/or allowance for student's education or training being paid for by..." question has been updated to [this](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=291%3A44398&mode=design&t=AYTz3J1dLqTZfmmU-1)
- [ ] Ajia signs off on page updates in Staging
- [ ] Unit tests and E2E tests are updated, passing, and meeting standards
---
