### ISSUE TITLE
Copy of Discovery Vets API: Datadog Source Code Integration

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#82530]
## Description

Exploring alternatives to Sentry for error logging, we've discovered that Datadog offers the capability to view stack traces for error logs, similar to Sentry. ([See View Trace Details on this error log](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20status%3Aerror&cols=host%2Cservice&event=AgAAAY6K-Wp52dG7nAAAAAAAAAAYAAAAAEFZNkstVzk2QUFDLXpobzYwbjZqRVFCMQAAACQAAAAAMDE4ZThhZjktODA4Ni00YWRkLWE2YjMtNTNlYTJiYmJhY2Q1&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=4361684514522207690&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1711642186104&to_ts=1711728586104&live=true)). Additionally, Datadog provides an APM feature for source code integration. ([See missing link to repository here](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20service%3A%22check-in%22%20resource_name%3A%22CheckIn%3A%3AV2%3A%3APatientCheckInsController%23show%22%20host%3A%22i-0dc4e3bbf34a4fe16%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=194008368741708849&spanType=service-entry&spanViewType=errors&trace=d20b8e2965c37c2f&traceID=2132272697721308434&traceQuery=&view=spans&start=1711728584740&end=1711728644740&paused=true)). This feature could enhance error investigation by offering direct links to the relevant sections of the Vets API repository within the error logs. [See setup configuration.](https://vagov.ddog-gov.com/source-code/setup/apm) Integrating source code with Datadog's APM might be a valuable step to consider for improved error analysis and debugging.

## Tasks
- [ ] Evaluate Datadog's APM and Source Code Integration Feature
- [ ] Discover if any other application use this feature
- [ ] Create follow up ticket for implementation (if necessary)

## AC
- [ ] We've evaluated the Source Code Integration Feature 
- [ ] Follow up implementation ticket created

**Comment by jennb33** [comment]
Dupe ticket
