### ISSUE TITLE
[CST] Create feature flag for 5103 work and removal of ask your claim decision

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#82537]
## Description
Create new feature flag called `cst_5103_update_enabled` - this flag will be used to enable to 5103 alert work and to hide the ask your claim decision work

## Tasks

- [ ] Add `cst_5103_update_enabled` to vets-api
- [ ] Add `cst_5103_update_enabled` to vets-website

## Acceptance Criteria
- [ ] The feature flag `cst_5103_update_enabled` exists
