### ISSUE TITLE
Setup Initial Boilerplate Code for Endpoint

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#82554]
## Technical Architecture
The backend architecture for this new form was designed with the following assumptions:
- Upon veteran submission, we want to immediately send the completed 0969 PDF to VBA as a saved claim using the benefits intake API.
- Each submission of the 0969 form would not have any knowledge of any additional benefit(s) the veteran has applied for already or will apply for in the future.

[API Architecture Documentation](https://docs.google.com/document/d/1VpFXr5NdXNgwHyYCZ1LBFqytNEC4IqUkLNTt0aZzlcw/edit)
---
## Tasks
- [ ] Create a new route for submission requests. 
- [ ] Requests should be posted to the v0/form0969 endpoint

## Acceptance Criteria
- [ ] Submissions are successfully posted to the v0/form0969 endpoint

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/82554?planning-poker) with Zenhub @danlim715 @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/82554?planning-poker) with Zenhub @scottsdevelopment

**Comment by TaiWilkin** [comment]
Some questions:
- The architecture doc and the acceptance criteria list the endpoint as `v0/form0969`, but the architecture doc lists the controller as IncomeAndAssetsClaimsController. Ruby uses the controller name to generate the endpoint, which in this case would be `/v0/income_and_assets_claims`. Do we want to use `Form0969Controller` for the controller name, or use `/v0/income_and_assets_claims` for the endpoint?
- Should I add the new endpoint to Swagger as part of this ticket, or will we be covering that in a separate issue?
