### ISSUE TITLE
Create json schema for Form 0969

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#82561]
## Technical Architecture
The backend architecture for this new form was designed with the following assumptions:
- Upon veteran submission, we want to immediately send the completed 0969 PDF to VBA as a saved claim using the benefits intake API.
- Each submission of the 0969 form would not have any knowledge of any additional benefit(s) the veteran has applied for already or will apply for in the future. 

[Vets-API Architecture documentation ](https://docs.google.com/document/d/1VpFXr5NdXNgwHyYCZ1LBFqytNEC4IqUkLNTt0aZzlcw/edit)

---
## Tasks
- [ ] Review PDF form to assess all fields and data types
- [ ] Create preliminary schema that can be use
- [ ] Review with FE to feedback
- [ ] Add tests to validate

## Acceptance Criteria
- [ ] A schema is created that can be used initially for the scaffold development
