### ISSUE TITLE
[Tool] Update 5103 request to have a confirmation when the Veteran submits the 5103 response waiver

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#82578]
## Value Statement
**_As a_** veteran receiving a 5103 Notice first person request in CST
**_I want to_** understand what that request means and be able to take action to submit the 5103 response waiver
**_So that_** I understand what is being asked of me and can either add evidence or submit the waiver, enabling a faster claim adjudication process

---
## Background Context

**This ticket is specifically scoped to the confirmation after the Veteran submits the 5103 waiver via the 5103 1P alert** Other tickets in the epic handle other aspects of this user experience.

Current UI 

N/A

## Outcome, Success Measure, KPI(S), and Tracking Link
- More 5103 waivers submitted through CST
- More 5103 notices downloaded through claim letters section

## Design
- [Figma](https://www.figma.com/file/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-and-5103-alert?type=design&node-id=2-11&mode=design)

### Enablement team (if needed)
@jstrothman

## Engineering 
- Put behind feature flag `cst_5103_update_enabled`

## Out of scope
- 1P alert on Status and Files tab
- Document Request page for 5103 1P alert
- Recent Activity update

## Open questions
- 

## Tasks
- [ ] Finalize language for confirmation
- [ ] Finalize mock showing where this confirmation shows up for the Veteran

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] End user has a better understanding of what a 5103 notice is from the 5103 alert in the Status and Files tabs

**Comment by skylerschain** [comment]
Duplicate of #82580
