### ISSUE TITLE
[CST] [DESIGN] [ENG] Update Document Request page with new 5103 waiver submission experience

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#82575]
## Value Statement
**_As a_** veteran receiving a 5103 Notice first person request in CST
**_I want to_** understand what that request means and be able to take action to submit the 5103 response waiver
**_So that_** I understand what is being asked of me and can either add evidence or submit the waiver, enabling a faster claim adjudication process

---
## Background Context

We need a new 5103 waiver submission experience, so we're updating the waiver request page. This ticket is just for the new waiver form experience section of the page.  We're skipping "V2" and going right to "V3" so we can allow users to submit a waiver from the evidence request page itself.

Current UI for this page 👇

<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--269dd022df1e1bbe9928c43c96d6d3d4a26ab7a8/Screenshot%202024-05-07%20at%203.00.37%E2%80%AFPM.png" alt="Screenshot 2024-05-07 at 3.00.37 PM.png" />

## Outcome, Success Measure, KPI(S), and Tracking Link
- More 5103 waivers submitted through CST
- More 5103 notices downloaded through claim letters section

## Design
- [Figma](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-and-5103-alert?node-id=1699-18198&t=ihxrPINq7bDO71qY-4)

## Design Screenshot
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/105806934/b80b3b46-7867-46af-90e0-d589c7972cae)

### Enablement team (if needed)
@jstrothman

## Engineering 
- Put behind feature flag `cst_5103_update_enabled`
- We will want to use the `item.displayName` where it equals 'Automated 5103 Notice Response' to determine that it is a 5103 Notice
- Assume we'll have to create unique fields for description used on alerts and document request pages for this use case. 
- Assume that we're building future-forward architecture that can be used for other evidence request use cases.
- If the user doesn't click the checkbox, they shouldn't be able to submit the evidence waiver. @skylerschain what does the error message look like in this case?
- Ask For Your Claim Decision uses the same logic as this form

## Out of scope
- 1P alert on Status and Files tab
- Recent Activity update

## Open questions
- We assume that you shouldn't be able to submit the form if the checkbox isn't checked?
- Where does the user go after submitting this form?
- What should the confirmation message say?

## Tasks
Design:
- [x] Finalize Design and Language for new 5103 form experience
- [x] Design an error message if someone tries to submit the form without checking the checkbox
- [x] Determine where the user is taken after submitting the form
- [x] Design a confirmation message after form submission

Eng:
- [x] Document Request page shows new `5103 waiver form` that includes...
  - [x] header - `If you don’t have more evidence to submit`
  - [x] description
  - [x] checkbox
  - [x] submit button
- [x] If the checkbox is checked, the user should be able to submit the form which calls this API endpoint: `/v0/benefits_claims/{claimId}/submit5103`
- [ ] Add Cypress tests for this new functionality
- [x] Add logic so that we hide associated track item alert once waiver is submitted. evidenceWaiverSubmitted5103 = true, then we hide the alert if it has the type automated 5103 notice response.
- [x] Logic needs to be added to the files needed component

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Behind 5103 feature flag.
- [ ] There is a header for the waiver section distinguishing it from other sections on the page and making clear what the section is for.
- [ ] There is a brief description under the header elaborating on the value proposition for submitting a waiver.
- [ ] There is a checkbox that verifies the person is done adding evidence in support of their claim
- [ ] The waiver cannot be submitted unless the box is checked. 
- [ ] There is submit button and, when clicked, a fully filled out 5103 waiver is submitted to VA on the person's behalf. 
- [ ] After submitting waiver, there is some kind of confirmation that the form was successfully sent. 
- [ ] When the waiver gets submitted, we hide the associated tracked item alerts on the status and files tabs.

**Comment by pmclaren19** [comment]
Updated ticket with eng tasks per eng refinement.

**Comment by jacobworrell** [comment]
This ticket has been vertically slice, so has changed significantly, Here are the old ENG notes for posterity: 

- Eng:
- [ ]  Document Request page shows new `If you do have more evidence to submit` section that includes...
    - [ ] header - `If you do have more evidence to submit`
    - [ ] content
    - [ ] link called `upload it in the Files section of the Claim Status Tool` that links to the files tab
- [ ] Put behind feature flag `cst_5103_update_enabled`
- [ ] Document Request page shows new header `5103 notice response`
- [ ] Document Request page shows new all of the new content
- [ ] Document Request page shows new `Download letter link` that does the following...

**Comment by skylerschain** [comment]
Answers to Open Questions above - @pmclaren19 @samcoforma : 

**We assume that you shouldn't be able to submit the form if the checkbox isn't checked?**
> Correct, working on finalizing an [error state](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=1871-4457&t=44ULxttEUlNNUFBe-4) in the spec for if they click Submit without checking the box.

**Where does the user go after submitting this form?**
> The user is taken to the Files tab, where [they see a confirmation message](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=1871-4205&t=44ULxttEUlNNUFBe-4) that the waiver was submitted.

- What should the confirmation message say?
> See above

**Comment by pmclaren19** [comment]
Hey @skylerschain @jacobworrell this ticket is merged and in Staging. Feel free to validate with user 23 or to create a claim with a 5103 notice in VBMS and then to test. If you test with user 23 I just ask that you dont try to submit the evidence waiver until after demos so that have a user to demo; since I still dont have access to VBMS to create new users and I had to ask Jerek to create these for me.

**Comment by skylerschain** [comment]
Hey @pmclaren19 was able to QA and it looks good! A couple things:

#### 1. The green confirmation banner is currently showing up at the top of the page, but if you look at [the spec](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=1871-4205&t=G3dUHmQ7u8WZ3VRc-4) it should go in the Claim Files section, underneath the header and subheader and above the "Additional evidence" section.

**Current**
<img width="972" alt="Screenshot 2024-06-25 at 3 56 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/06e0c6f1-b675-4f1e-85f2-97fab876a21b">


**Should be**

<img width="381" alt="Screenshot 2024-06-25 at 3 55 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/ad3f5a21-7307-4ce9-bdab-7af36139575f">

Also I think we discussed not needing that "X" button on the confirmation banner, since it will go away on refresh. It's not a big deal either way. 

#### 2. Is it possible to remove the 1P alert from the confirmation page? It's a big confusing, plus I'm worried users might interact with it and end up submitting the waiver a bunch of times. 

<img width="1017" alt="Screenshot 2024-06-25 at 4 00 04 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/a1fe1384-cc83-4df1-abea-7dfab9a297a7">

**Comment by pmclaren19** [comment]
> Hey @pmclaren19 was able to QA and it looks good! A couple things:
> 
> #### 1. The green confirmation banner is currently showing up at the top of the page, but if you look at [the spec](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=1871-4205&t=G3dUHmQ7u8WZ3VRc-4) it should go in the Claim Files section, underneath the header and subheader and above the "Additional evidence" section.
> **Current** <img alt="Screenshot 2024-06-25 at 3 56 55 PM" width="972" src="https://private-user-images.githubusercontent.com/95102058/342906764-06e0c6f1-b675-4f1e-85f2-97fab876a21b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDYwMjUsIm5iZiI6MTcxOTM0NTcyNSwicGF0aCI6Ii85NTEwMjA1OC8zNDI5MDY3NjQtMDZlMGM2ZjEtYjY3NS00ZjFlLTg1ZjItOTdmYWI4NzZhMjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjODU5OTg2ZjRhYWY0NTQ1YTg1Y2QxN2VlNjk2MzkxOWZmMGRiNDIyOGYwNDQ3ZTgzNWY4ZjJmYmYxMDYwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TRJY6jvtoopM01T6XSyZObX2488X-39mk_9CIqO98hg">
> 
> **Should be**
> 
> <img alt="Screenshot 2024-06-25 at 3 55 49 PM" width="381" src="https://private-user-images.githubusercontent.com/95102058/342906461-ad3f5a21-7307-4ce9-bdab-7af36139575f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDYwMjUsIm5iZiI6MTcxOTM0NTcyNSwicGF0aCI6Ii85NTEwMjA1OC8zNDI5MDY0NjEtYWQzZjVhMjEtNzMwNy00Y2U5LWJkYWItN2FmMzYxMzk1NzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OTY4MDM2YzBkZGMzY2Q2NTQ2OTAyMzBjOTVkNjg1Y2QxNjQ2OTY4ZjhiYmJhZjcxNzBiYjg1Y2Q3MjI5ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5PIuJr4vgCE2I-nZhlPagEXu4mHkYpNbOYsOZq5lHSc">
> Also I think we discussed not needing that "X" button on the confirmation banner, since it will go away on refresh. It's not a big deal either way.
> 
> #### 2. Is it possible to remove the 1P alert from the confirmation page? It's a big confusing, plus I'm worried users might interact with it and end up submitting the waiver a bunch of times.
> <img alt="Screenshot 2024-06-25 at 4 00 04 PM" width="1017" src="https://private-user-images.githubusercontent.com/95102058/342907745-a1fe1384-cc83-4df1-abea-7dfab9a297a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDYwMjUsIm5iZiI6MTcxOTM0NTcyNSwicGF0aCI6Ii85NTEwMjA1OC8zNDI5MDc3NDUtYTFmZTEzODQtY2M4My00ZGYxLWFiZWEtN2RmYWI5YTI5N2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZGM2NzkyMzY4ZjM4ZWI5OWJmODY0NWUyZTBjYTg5ZmFhODdkMjQ1M2IxYzgzZTliZDkxMTljNWExN2NiYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NuNmIwpcG5OWbHty3-1Na2KSDBmZxmNgw2YxVUwrmd4">

Hey @skylerschain,

So for your first question regarding where the confirmation message is appearing. I had to add special if logic saying when the feature flag is enabled then we set the confirmation header and message to what your design had. If it is a hard requirement that we also change the position of where the notification shows up and also remove the x, it would affect all other notifications that occur due to how that component is rendered and Im not sure we want to do that. We could add if logic using the feature flag to not show the close button ('x') but that would be a lot of work for such a small thing so what to make sure we really deem that necessary.

For your second question the p1 alert does get removed. If you refresh your page it should remove the alert. It takes some time for it to call the backend code and then update the frontend so that is why it doesnt happen asynchronously and you have to refresh.

LMK your thoughts also happy to have a larger conversation around this in a meeting!

**Comment by pmclaren19** [comment]
Met with @skylerschain to discuss these two topics. 

1. @skylerschain is going to create a new ticket to change where we put this notification; understanding that it would be moving the location of the notification for all things (EX: Upload a Doc from the Doc Request page, Ask VA, Upload Doc from files page, 5103 request, ect). We will then refine with the team/enablement team and see what everyone thinks about changing the placement of the notification.
2. Currently when a user submits their evidence we send a request to vets-api and then eventually we get data back that its been updated --- Once the data is updated a page refresh will remove the primary alert; this is an asynchronous process. @skylerschain would like to make this a synchronous process but this likely would require us to have a loading page of some sort that would wait to get a response back from vets-api. Skyler is going to reach out to @jerekshoe about this to get more information and if we do decide to move forward with this idea it would require us to update both the 5103 notice and all other document requests types when evidence is uploaded. 

Ticket is good to close for now and new tickets will be created/worked for the above work as needed.

**Comment by skylerschain** [comment]
Realized it's probably easier to just tag @jerekshoe into this ticket. 

Jerek, we're wondering what the loading time would be to make that asynchronous call? I would like to not show the confirmation screen until the original 1P alert has gone away (otherwise it feels broken). If the Vets API lag time is what it is, how long do we think that would be? If not a few seconds, a loading screen might be a preferred solution.

**Comment by jerekshoe** [comment]
Kinda hard to say, one of the issues is that it’s not just asynchronous on our side (when we move to LH it will actually be synchronous) but it’s also async on the LH side as well (doubtful we will get them to change that) so it may or may not actually be done when we get a success response back from LH. Most of the time it should be pretty quick though

**Comment by skylerschain** [comment]
I think if "most of the time it should be pretty quick" we should try to use the loading indicator.

I wonder if we could also throw a "This is taking longer than normal. Come back in a couple of minutes." message after a certain amount of time if it's taking too long.

**Comment by skylerschain** [comment]
@jerekshoe Is this the same issue described in this ticket? https://github.com/department-of-veterans-affairs/va.gov-team/issues/76660

If so we can link to this conversation in that ticket. If not, I'll create a new ticket.
