### ISSUE TITLE
IA Guidance:  VA.gov home page template

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#82570]
## IA standards request
Define the template layout and criteria for placement of content or links on the home page. 

Goal:
Establish documented guidance on the design of the home page, usage of the template, and clear criteria for what content or links can be added to the home page and where it would go.  This will provide information for teams to review before coming to IA to request a home page link or addition. Documentation should also include description of each section on the home page and ownership/approval process. 

* It is yet TBD if this documentation should live in the VA design system, as we do not want teams using this template for other purposes. 

Source(s) of information
- [Product documentation)]https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/home-page/initiatives/2022-home-page-redesign-initiative)
- [Home page rubric](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/home-page/initiatives/2022-home-page-redesign-initiative/homepage-content-rubric.md)

### Tasks
- [x] Review/analyze existing documentation and implementation - IA 
- [x] Establish scope of effort and where guidance lives - IA
- [x] Draft revised standard - Kristin
- [x] Review with Mikki  - Kristin
- [x] Review with Erin - Kristin
- [x] Format for publishing (if going into VADS) - Erin
- [x] Final review and approval by Mikki - Erin/Mikki
- [x] Publish - Erin/IA
- [ ] Communicate out to teams - IA/Mikki

### Acceptance criteria

- [ ] Clear guidance for placement and inclusion of content or links on the home page is clearly defined and approved by IA lead, Sitewide design lead, and home page PO
- [ ] Home page template including design specs, IA of page, and usage and content guidance is published in the VA design system
- [ ] New template on VADS is communicated out to teams

**Comment by mnorthuis** [comment]
@erinrwhite This one can be started when you are available.  It may be helpful to sync with Kristin and Jenny on the hub page template work they are doing so we can use consistent language and approach.

**Comment by erinrwhite** [comment]
@mnorthuis Got it - thank you!

**Comment by kristinoletmuskat** [comment]
@erinrwhite and I met and decided:

1. We're going to use the same general template for home page as we did for the existing benefit hub page, aka this structure: https://design.va.gov/templates/hub
2. Kristin is going to take the first draft of this guidance in Mural (same location as benefit hub [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?sender=ua67f17f1c416a96ea04d2476))
3. Incorporate home page rubric into mural, using branching logic to make it clear what happens if the answers are yes/no to these questions: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/home-page/initiatives/2022-home-page-redesign-initiative/homepage-content-rubric.md
4. Figure out difference between general content placement criteria and these rubrics -- should they live together? Separate?
5. Placement of this guidance will be in VADS --> templates (where the hub page guidance lives today)

**Comment by mnorthuis** [comment]
For #4, the content placement criteria doesn't impact the template guidance - that criteria indicates where full content should live in the IA.  For the template guidance, that should just focus on the rubric used to identify links for each section.

**Comment by shiragoodman** [comment]
FYI - this is a slide currently in the General Orientation slide deck. I thought it may be helpful.
<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUl3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e56a2473dafdf42ea7d5bb7a21adbf3e0088a45/image.png" alt="image.png" />

**Comment by kristinoletmuskat** [comment]
Hey @shiragoodman for some reason that image isn't working for me! Could you try re-uploading?

**Comment by shiragoodman** [comment]
<img width="713" alt="WebBrandConsolidation_slide" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/e2c4a72b-f615-4c16-838b-0758fa424fb2">
@kristinoletmuskat let me know if this is better

**Comment by kristinoletmuskat** [comment]
@erinrwhite ready for your first round of review in this mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?wid=0-1717086070879

FYI @mnorthuis and @shiragoodman your feedback is also welcome. When creating guidance for the benefit hub template, we found it easier to first use this diagram in mural to clarify the guidance internally. Once we're on the same page in the mural (comments, stickies, etc), I will migrate this content to a google doc for final review.

**Comment by kristinoletmuskat** [comment]
Hi @mnorthuis, here is the draft of the [home page standards](https://docs.google.com/document/d/1-QMEykV4P_wNI4jhDvy1eICzP1EhBxXoU8eS0Ypcer4/edit?tab=t.0). I've included the [word attachment](https://github.com/user-attachments/files/17320549/Home.Page.Template.docx) as well for you to circulate with your OCTO folks. 


There are a few areas where we hadn't finalized character count, which I noted with comments. There were also a few questions I had that are also in comments! In case it makes sense to resolve those in the google drive version before circulating with OCTO.

FYI @erinrwhite

**Comment by mnorthuis** [comment]
@kristinoletmuskat I have moved the guidance to a sharepoint doc for review and collaboration within OCTO, and sent links out for review. 


https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/IA/Standards/Home%20page%20guidance%20for%20VADS.docx?d=w69f2bb4012964aa1aba48016dc43a53e&csf=1&web=1&e=fZdSOr

**Comment by mnorthuis** [comment]
@kristinoletmuskat @erinrwhite The homepage guidance has been reviewed and approved and is ready to publish on VADS!

https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/IA/Standards/Home%20page%20guidance%20for%20VADS.docx?d=w69f2bb4012964aa1aba48016dc43a53e&csf=1&web=1&e=mpIwPD
