### ISSUE TITLE
[Documents to Lighthouse] Update service to pass participant ID instead of File number

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#82592]
### Background
Lighthouse is updating the Benefits Documents API to accept participant ID instead of File number as the primary user identifier. We need to update the code in vets-api to account for this change

### Tasks
- [ ] Update the service to pass the current users participant ID instead of the file number
- [ ] Update specs to account for this change

### Acceptance Criteria
- [ ] Our integration with the Lighthouse Benefits Documents API is passing the participant ID instead of the file number
