### ISSUE TITLE
Contact and confirm Usability Test Participants

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#82606]
## Description
Will need to schedule Usability Testing Sessions based on number of respondents, and both their schedule and Naomi's schedule.

---

### Tasks
- [ ] Review schedules
- [ ] Propose/confirm times
- [ ] Schedule zoom calls

### Acceptance Criteria
- [ ] We have scheduled and conducted 6-8 usability testing sessions based on the pre-defined scenario
- [ ] (Stretch) Conduct 1-3 additional sessions with teams providing their own branches for testing
