### ISSUE TITLE
[DevOps] Open SNOW ticket for OIDC role for `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82617]
## User Story
As a DevOps engineer, I need a good IAM policy to attach to an OIDC role that we can request from VAEC.

This will involve us (Eric and me) determining what role GitHub will play in its interactions with AWS in the future, especially given the VAEC Team's concerns about the `vaec-cms` process, so it's not a trivial copypasta of existing policies.

## Tasks
- [x] [DevOps] Eric and Nate need to meet and determine what to ask for.
- [x] [DevOps] Document our requirements (as an actual policy?).
- [x] [DevOps] Open a ticket.

## Acceptance Criteria
- [x] SNOW ticket has been opened to request an OIDC role with appropriate access.

**Comment by ndouglas** [comment]
Duplicate of #81919, which was already completed.
