### ISSUE TITLE
[DevOps] Compile/create existing authorization/documentation for our use of VAEC AWS access keys within Datadog.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82615]
## Description
We've been asked by VAEC/PD Team to review/provide documentation of our authorization to use Datadog, specifically the way in which we're using access keys for IAM accounts in Datadog, etc.

## Tasks
- [x] [DevOps] Figure out why we're doing things this way, precisely
- [x] [DevOps] Request information from ECSO/VAEC Security Team as to whether this sort of documentation is required.

## Acceptance Criteria
- [x] I've requested information from everyone who might have relevant input.

**Comment by ndouglas** [comment]
Opened thread [here](https://dsva.slack.com/archives/C022AC2STBM/p1715180103525099) to ask Kay and Stephen.

**Comment by ndouglas** [comment]
Shalom suggested we ask Catherine Lyon for documentation on this.

**Comment by ndouglas** [comment]
She didn't really have anything. I think I'm going to have to ask ECSO directly.

**Comment by ndouglas** [comment]
Emailed ECSO to ask whether we need additional documentation or authorization for this.

**Comment by ndouglas** [comment]
Based on conversations with engineers and other key personnel, we do not have any kind of written authorization or other documentation for this, the reason being that our current actions follow established policies. I've reached out to ECSO for clarification on whether our pattern requires any kind of POA&M or other authorization moving forward. If I receive a response, and that response indicates that I need to take any specific kind of action, I'll create a followup ticket to address that.
