### ISSUE TITLE
[DevOps] Determine and document key personnel for Check-In Experience.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#82616]
## Description
We've been requested to update our documentation for:
- System Steward
- ISO
- ISSO

I've asked Patrick Bateman. He said to ask Kay and Stephen.

## Tasks
- [x] [DevOps] Figure out who these people are.
- [x] [DevOps] Provide that information to Shalom.

## Acceptance Criteria
- [x] Correct, updated list of key personnel is reported to Shalom.

**Comment by ndouglas** [comment]
Opened thread [here](https://dsva.slack.com/archives/C022AC2STBM/p1715179774575899) to ask Kay and Stephen.

**Comment by ndouglas** [comment]
Stephen responded, and I passed the information to Shalom in Teams.

**Comment by ndouglas** [comment]
@loripusey @anita-halici Brought this tiny ticket in to account for some of the running around and pinging people 🙂
