### ISSUE TITLE
Update "Which experience standards are violated most frequently?" card with new standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#82621]
## User Story
As a viewer of the Staging Review Dashboard, I want to see the new Experience Standards reflected in the cards so that I can trust the data and use it for decision making.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
In the "Which experience standards are violated most frequently?" card in the Staging Review Dashboard, the data in the card is currently reflective of the old Experience Standards. AKA 11 categories and 91 standards. The new Experience Standards only have 7 categories and 22 standards. In addition to that, the data is also divided into launch-blocking issues vs. non-launch blocking issues

By updating the card to reflect the new standards, we are simplifying the card, making it easier for the user to drill down to the data they need.

The card should continue to be filtered by quarter, with only the 4 most recent quarters of data included. CY23Q2-CY24Q1.

## Impacted Artifacts
[VA.gov Experience Standards](https://design.va.gov/about/experience-standards/)

## Tasks
- [x] Modify the "Which experience standards are violated most frequently?" card to reflect the new categories and new standards  (see VA.gov Experience Standards page above).
   - Note: data set should remain the same, we're just sorting by different values now
- [x] verify that the card reflects the 4 recently completed quarters 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The "Which experience standards are violated most frequently?" card in the Staging Review dashboard reflects the new VA.gov Experience Standards
- [x] The "Which experience standards are violated most frequently?" card is filterable by the 4 most recent completed quarters
- [x] Users can drill down from category to standard in the "Which experience standards are violated most frequently?" card, and view by launch-blocking vs. non-launch-blocking

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Please be sure to follow along with ticket

**Comment by shiragoodman** [comment]
This ticket is blocked by #81730. We were able to begin the work and make the changes to Domo, however we are unable to verify that the changes are correct bc the dataset is still incorrect.

FYSA @humancompanion-usds

**Comment by it-harrison** [comment]
@briandeconinck this is ready for review: https://va-gov.domo.com/page/1340527018

**Comment by briandeconinck** [comment]
@it-harrison This looks good to me!
