### ISSUE TITLE
[BE] 10-10EZ: Query vets-api DB for % of users who leave the form, return to SIP and submit

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#82629]
## Background
As part of our research on page drops within the household/financial section of the 10-10EZ, we would like to see if there is there any way to determine % of users who leave and then come back via Save-In-Progress and finish.  
We believe a vets-api query is needed to gain this information.  

The lookback timeframe is at least 60 days.

## Tasks
- [ ] Determine what kind of query (queries) can be used to pull the information we need
     - This can include collaborating with other engineers across VA to assist
- [ ] Run the query(ies) and calculate the data against the need - % of users who leave and then come back via Save-In-Progress and finish
- [ ] Share data with PM/team

## Acceptance Criteria
- We have been able to pull the data needed to answer our question of "what portion of users leave, but also return to their saved form and submit?"
