### ISSUE TITLE
Address ambiguity of "the airspace above any of these locations" on summary screens and review & submit screen

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#82620]
## Issue Description
On some of the toxic exposure location screens, there is an option of "the airspace above any of these locations". When shown on the location screen alongside the other locations listed, it is clear. However, when shown on the summary screens and the review & submit screen, it is potentially unclear which locations it is referring to. A stakeholder pointed this out in a live PR review.

[example Figma screen](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=1236-54963&mode=design&t=jOFJC57khSvNuPpw-11)

<img width="108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b452b601c71e42a6263d07f0422e0c234aef834/11%20Locations%202%20Checked.png" alt="11 Locations 2 Checked.png" />

<img width="121" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59e1fb8f2ff1898de2fcdf4990e127550f93d8cc/Intermediary%20summary.png" alt="Intermediary summary.png" />

<img width="339" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--471d0e04ea5701bab480071a67190b7c5e6d8f5f/Screenshot%202024-05-08%20at%2010.55.55%E2%80%AFAM.png" alt="Screenshot 2024-05-08 at 10.55.55 AM.png" />

---
## Tasks
- [ ] Determine whether this is a problem for users or assume that it is
- [ ] Design / content updates to provide clarity
- [ ] Get signoff from engineering on feasibility
- [ ] Create ticket for implementation

## Acceptance Criteria
- [ ] Team aware of changes to be made
- [ ] Mockups up to date
