### ISSUE TITLE
Update "What are the most violated Experience Standards by practice area?" card with new standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#82622]
## User Story
As a viewer of the Staging Review Dashboard, I want to see the new Experience Standards reflected in the cards so that I can trust the data and use it for decision making.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
In the "What are the most violated Experience Standards by practice area?" card in the Staging Review Dashboard, the data in the card is currently reflective of the old Experience Standards. AKA 11 categories and 91 standards. The new Experience Standards only have 7 categories and 22 standards. 

The card should continue to be filtered by quarter, with only the 4 most recent quarters of data included. CY23Q2-CY24Q1.

**Note 5/22:** The card appears to be reflective of the new standards, however no Governance team member has made any updates yet. It's possible the updates came due to the A&I Big Query updates. 

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The "What are the most violated Experience Standards by practice area?" card in our Domo dashboard reflects the revised Experience Standards

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison did you already start making updates to this card? It's looking much better in Domo.

**Comment by it-harrison** [comment]
@shiragoodman - no, didn't touch that one yet!

**Comment by it-harrison** [comment]
@briandeconinck - this is ready for review. I didn't change anything - the queries don't reference the updated experience standards so it didn't need updating.

**Comment by briandeconinck** [comment]
Looks good to me!
