### ISSUE TITLE
Implement IA Feedback for Missing 5103 Link & Claim Certification 

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#82644]
## Epic Description

Implementing IA feedback from Design intent meeting for [Collaboration Cycle for 5103 link / Claim certification
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82160)

Scope - 

[IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82512)
**Must:** remove (opens in new tab) from links on intro page We only advise opening links in a new tab once users are inside a form flow, so the links on the intro page should open in the same tab. 

 **Consider:** updating content/link placement within alert to support scanning In the current alert/info box, both links are placed next to each other. To support quick action, you might update the text to break out each individual action, something like:

**Consider:** work with CAIA on an HTML version of evidence tables Echoing feedback from design, it would be ideal if the information we're asking Veterans to review was formatted as accessible HTML. CAIA team might be able to steer you to the best place to include this information - perhaps as a Resources and Support page.

---
## Tasks

- [x] Get consensus around the link rules for opening in a new tab (CAIA & Erin White)
- [x] Update mocks with Must feedback
- [x] Evaluate consider feedback and update mocks accordingly 

## Acceptance Criteria

- [x] Essential feedback is implemented
- [x] Mocks reviewed with Stakeholders

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kate-allbee** [comment]
- Updated Designs with: 

- Implementing Accessibility feedback: Link text describing the intended use case should help guide the user and hopefully minimize confusion
- Can link to the direct page of the PDF (page 5). VS. telling them to download the link. 
- Will need to use aria labels for linking to a direct page
- Saying “section 5” is misleading because it could imply the section within the form
- “review official evidence requirements” matches what’s currently on the evidence needed page.
- No need to include the note about filling out the pdf if the link text is clear that we’re not asking them to download the pdf. 
- Reviewed and approved by Shannon
