### ISSUE TITLE
[DESIGN] Create wireframes for filtering options

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#82659]
## Background:

Based on feedback from design office hours, we need to explore options for creating a contained filtering page (modal or otherwise) for accessibility purposes. This also makes way for the addition of future filtering additions.

[Filtering explorations (link to Figma)]()

## Tasks
- [ ] Explore different options for a scalable filtering behavior
- [ ] Review options with CC team
- [ ] Decide on a direction
- [ ] Update in Figma files

## A/C
- [ ] Behavior for filtering determined
- [ ] Figma updated

**Comment by benbrasso-agile6** [comment]
Closing this ticket, and we'll create a new one for next sprint as a result of office hours feedback
