### ISSUE TITLE
Design | Profile | Profile design patterns | Section containers

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#82669]
## Background

There are a few problems with the sections in profile.  [Here's the Mural board reference](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710440765471/4454ab2df1da3b010ebb972b54b838b466a7a4f9?wid=1-1710525486507).
1. The margin between sections varies from page to page. Sometimes its on a margin-bottom declaration, others it's a margin-top
2. The padding is different on desktop and mobile, which adds (unnecessary?) complexity to maintenance
3. we're not using the va-card component on profile pages, but we are on the hub page.

## Tasks
- [ ] UX to evaluate how profile uses a list vs a card vs a section, and when content should just be on the page alone. 
- [ ] Gain alignment
- [ ] UX and FE should collaborate to determine if it makes sense to use the va-card component for all cards (sections?), and if so, what variations on the existing card component we might need for profile. 
  - Our heading w/ gray background is a desirable contribution as a card variation for the design system, so contributing that back through the experimental design process could be a separate ticket if we get to that point.
- [ ] UX and FE should collaborate on vertical spacing tokens and possibly contribute this back to DST

## AC
- [ ] We have guidance on when we use cards vs sections
- [ ] We've decided whether or not we need to use the `va-card` component, and submitted to the design system accordingly
- [ ] We have a plan for if/how we're going to use vertical spacing tokens, and contributed that back if needed.

**Comment by jfinnerty13** [comment]
With us updating as we go are you ok if we close this ticket out @mtcA6 ?
