### ISSUE TITLE
Remove the "My" from all VA311 references, so it just reads "VA311"

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8267]
In a review, we were informed by the VA311 team that there was a change to move away from using "MyVA311" and to just use "VA311". 

## Goal
- Find and update any instances of "MyVA311" to instead read as "VA311" on the site

---
## Tasks
- [ ] Review, investigate the site for where we have used "MyVA311"
- [ ] Update any place we have used "MyVA311" to instead be "VA311"

## Acceptance Criteria
- [ ] No instances of "MyVA311" remain on the site (that we have control over), and have been changed to "VA311"
---
Known places we currently have MyVA311 on the site:
* "Contact Us" in the header
* Some of the "Ask Questions" modules on hubpages

**Comment by stephorkandatx** [comment]
@ncksllvn I am seeing "MyVA311" on the 'ask questions' section for the Disability Hub. Is this a section we have control over, requires updates in Drupal, or some other mechanism?
![image](https://user-images.githubusercontent.com/63361321/80832615-98aaee80-8bb2-11ea-91f5-194f6205b138.png)

**Comment by stephorkandatx** [comment]
The remaining item is in Drupal, and would be a content change. @beeyayjay to confirm

**Comment by beeyayjay** [comment]
It is a content change. It can be edited from benefits hub page in the "Right Rail" section in the right rail or by editing the content directly  (content type: Support Service).

**Comment by stephorkandatx** [comment]
Thank you @beeyayjay for checking! I have created #8851 to capture the content part of this ticket. I have validated the other change made by FE so will close this out
