### ISSUE TITLE
[BE] My VA Forms Status: create vets-api feature flag

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#82683]
## Background
We need to set up a backend feature flag for vets-api ahead of connecting to `POST /uploads/report` endpoint form vets api and expose the new vets api endpoint to the frontend. 

## Tasks
- [x] check in w/ Tom
- [x] determine protocol for new vets-api endpoint
- [x] link to platform documentation
- [x] ~FE and~ BE flag created

## Acceptance Criteria
- [x] feature flag is available for use (or alternative method is working as suggested by protocol or BE CoP)
- [x] feature flag is turned OFF
- [x] new vets-api endpoint release plan is understood

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_: Tom, BE CoP (for code review). we can verify flipper ourselves
- _How can this work be validated?_ : Feature flags are available for use on staging (https://staging-api.va.gov/flipper/features). Plan for new endpoint release is understood.  If alternative plan becomes necessary, we'll follow up on validation options.

**Comment by DanielMiller-agile6** [comment]
there were a couple of docs, but I'll most likely be using these to start with:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/README.md

There is another tutorial about setting up a "module" for new endpoints, but that may not be our best option at the moment, since MyVA doesn't have a module, and we tend to use endpoints created by other teams when aggregating dashboard content.  We'll likely start with a "service" for making the lighthouse request (following similar patterns as other files in vets-api), and then work on the vets-api controller and new endpoint.

Here's a slack thread i was pointed to for more information:
https://dsva.slack.com/archives/CBU0KDSB1/p1702311554281399

**Comment by DanielMiller-agile6** [comment]
BE feature flag PR: https://github.com/department-of-veterans-affairs/vets-api/pull/16765

**Comment by DanielMiller-agile6** [comment]
BE feature flag/toggle/flipper id added in vets-api PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/16765

**Comment by DanielMiller-agile6** [comment]
dropped to 0. validated new flipper/flag/toggle.  Alison has another ticket for the FE toggle, so this ticket is just handles the vets-api piece for new flag we can use for our form status work

**Comment by ajakabcin** [comment]
Confirmed with Daniel we're good to close this out.
