### ISSUE TITLE
[BE] My VA Forms Status: Update swagger documentation for new Submission Statuses endpoint

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#82687]
## Background
We need to create/update swagger documentation for the `GET /v0/my_va/submission_statuses` endpoint

## Tasks
- [ ] determine steps for adding swagger docs for vets-api endpoint
- [ ] process for updates is understood
- [ ] code and PR

## Acceptance Criteria
- [ ] new swagger docs are available (or in PR)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_: BE CoP, Tom, MyVA
- _How can this work be validated?_ : check that new endpoint doc is accessible once available

**Comment by ACParker89** [comment]
@DanielMiller-agile6 will update notes/ac

**Comment by DanielMiller-agile6** [comment]
verified new docs are deployed and appear on https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference
