### ISSUE TITLE
[CDP] Aria Va-Row Attribute Missing Breaking Tests

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#82689]
## Description
Per [slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1715188371024709) brought up by Peter Hill, a CDP medical copays cypress test is breaking due to a lack of aria attribute. We need to add this to satisfy the test.

## Tasks
- [x] Add missing aria attribute

## Acceptance criteria

- [x] Missing attribute added
- [x] All tests pass

## Testing
- [x] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

**Comment by OptionSelect** [comment]
Rather than missing attribute added, removed unnecessarily previously added attribute that was causing breakage.
