### ISSUE TITLE
[BE] My VA Forms Status: Set up BE analytics for reports endpoint

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#82686]
## Background
We need to set up BE analytics tracking the `GET /v0/my_va/submission_statuses` endpoint to ensure it's functioning properly.

## Tasks
- [x] meet with Tom for knowledge transfer
- [x] Add dashboard widget in Datadog
- [x] Add monitors (traffic, and error) in Datadog
- [x] Add link to logs in Datadog

## Acceptance Criteria
- [x] We'll be able to monitor successful calls and failures on this endpoint

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_: Tom, BE CoP
- _How can this work be validated?_ : ...

**Comment by ajakabcin** [comment]
@tpharrison to add tasks

**Comment by ajakabcin** [comment]
moving to next sprint - waiting for Dan's access to come through

**Comment by ajakabcin** [comment]
@DanielMiller-agile6 rolling to next sprint

**Comment by DanielMiller-agile6** [comment]
added monitor for GET submission statuses:
https://vagov.ddog-gov.com/monitors/278048

added widgets to My VA dashboard:
https://vagov.ddog-gov.com/dashboard/4dk-pwd-mni/authenticated-experience-my-va?refresh_mode=sliding&live=true

added links to PROD and STAGING logs to channel canvas (staging log is temporary till feature toggle is removed):
PROD: https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%40http.url_details.path%3A%2Fv0%2Fmy_va%2Fsubmission_statuses%2A%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40http.status_code%2C%40payload.user_uuid&fromUser=true&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=336994431213512540&storage=hot&stream_sort=%40payload.user_uuid%2Cdesc&viz=stream&from_ts=1702581364262&to_ts=1702667764262&live=true

STAGING: https://vagov.ddog-gov.com/logs?query=env%3Aeks-staging%20%40http.url_details.path%3A%2Fv0%2Fmy_va%2Fsubmission_statuses%2A%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40http.status_code%2C%40payload.user_uuid&fromUser=true&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=336994431213512540&storage=hot&stream_sort=%40payload.user_uuid%2Cdesc&viz=stream&from_ts=1702581364262&to_ts=1702667764262&live=true

**Comment by DanielMiller-agile6** [comment]
we may need a future task to learn how to setup a new "tag" for My VA.  Currently, we're reusing the "profile" tag.  Neither Tom or I had the ability to create a new one, so this may require a platform support ticket.  Not critical, but could be a new task for a future sprint.
