### ISSUE TITLE
Design | Profile | Profile design patterns | Determine consistent approach to null states

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#82688]
## Background
We handle a "null" state in different ways. [Here are some examples on a Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710440765471/4454ab2df1da3b010ebb972b54b838b466a7a4f9?wid=0-1710529802202). Let's figure out how we can make this consistent across profile.

## Tasks
- [ ] UX to explore design treatments that might satisfy all the use cases on the Mural board.
- [ ] Run a quick comparative analysis
- [ ] Explore design options. At a minimum, we need to update null state on Military info to be plain text, and evaluate connected apps to see where we can do this, given the intro text on that page.

## AC

- [ ] We're ready to incorporate into existing null states where possible across the profile.

**Comment by jfinnerty13** [comment]
@mtcA6 we can probably remove this one considering all the styling work we're doing.
