### ISSUE TITLE
Add edit environment components to PE test front end

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#82699]
## Issue Description
When building out the initial test front end for Preview Environments, one feature that was left out of the list was the ability to edit an existing environment. This should be able to be initiated from the list of environments and pre-populate all fields with the existing information, only requiring a user to make the changes they wish to make.

---
## Tasks
- [x] Add edit button to list of preview environments.
- [x] Tie edit button to pre-populated environment creation interface, allowing users to edit environments.

## Acceptance Criteria
- [x] Users can easily edit an existing preview environment from the front end user interface.

**Comment by CBonade** [comment]
Edit icon has been added to the table and the "Create environment" drawer has been repurposed to be pre-populated with environment data if edit is selected.
