### ISSUE TITLE
Create Usability Testing User Guide

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#82695]
## Description
In order to conduct usability testing with our test users we need to create a guide that will help us share all the relevant information for using Preview Environments.

---

### References
- [PE User Documentation Outline](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3105980562/Preview+Environment+User+Documentation+Outline)
- [Research Guides](https://vfs.atlassian.net/wiki/spaces/DCP/pages/2480046097/Getting+started+with+research+for+the+Platform)

### Tasks
- [ ] Meet w/ Patrick to get a walk through of the planned approach for usability testing. 
     - Scenario 1 - Participant will be provided a link to an existing Preview Environment, and given an unauthenticated scenario to test
     - Scenario 2 (Optional) - If a team has an unauthenticated experience of their own that they'd like to test, They can used that to spin up their own Preview Environment to test their scenario,
- [ ] Draft an outline for the user guide based on this - it should ultimately end up in Google Docs, as most participants may not have access to Confluence, and we don't want to post to Platform Website yet.
- [ ] Draft content based on the outline, share w/ team for review
- [ ] Finalize document based on feedback

### Acceptance Criteria
- [x] Draft version of the Preview Environment user guide has been shared for review
- [x] Draft version of the document is finalized based on feedback, and a link is available for sharing.

**Comment by pjhill** [comment]
Working on the guide here -- https://docs.google.com/document/d/1nFLZ-TUpCELD_QHPwZ57AAd-3Iuxz6inRXJGH90PWAQ/edit?usp=sharing

**Comment by pjhill** [comment]
Waiting on feedback

**Comment by pjhill** [comment]
Reviewed the guide with Eric, Joe, Curt, and Steven. Incorporated comments / feedback.
