### ISSUE TITLE
Clayton | DOMO data setup and orientation

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#82697]
## Description of UX Tasks
I have DOMO access, but no data was populated. Now that Josh M is preparing to roll off the contract, I want to be sure I have access to the data he's been working with in DOMO for Contact Center and our contact's MFA Github Support Dashboard

## Tasks
- [x] submit ticket to Platform support to get Contact Center data added to my view
- [x] Get an invite to MFA contract data
- [x] look through and get familiarized with the data from both sources
- [x] have Josh walk me through MFA Support Dashboard

## Definition of Done
- Clayton has access to Contact Center data in DOMO
- Clayton has access to our contact's MFA Github Support Dashboard in DOMO
- Clayton has walked through and gotten familiarized with the data in preparation to take over DOMO tasks from Josh M

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
