### ISSUE TITLE
Update content on MR temp landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#82708]
### User story

As a Cartography team member, I want to update the temp MR landing page, so that it's caught up to stakeholder feedback.

### Notes
- [PR to see current state](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/vets-website/29583)

### Tasks:
Master figma file has been updated - [see here](https://www.figma.com/design/HnaBQQwuyjxM7ycFrTCozl/TEMP---Medical-records-landing-page?node-id=605-1861&t=4j9W5rPstIYF0g44-0)
- [ ] Update breadcrumb: leverage breadcrumb component which should wrap to mobile version below 480 px
- [ ] Adjust "coming soon" tag placement to come _after_ the H1 (will wrap onto another line on mobile)
- [ ] Remove text from very last sentence in the grey box that says "view your lab and test results." 
- [ ] Update link text in the grey box to read: ~"Go back to the previous version of medical records"~ "Go back to the previous version of My HealtheVet"

## Acceptance criteria

- [ ] MR temp landing page is updated to match the master [Figma file here](https://www.figma.com/design/HnaBQQwuyjxM7ycFrTCozl/TEMP---Medical-records-landing-page?node-id=605-1861&t=4j9W5rPstIYF0g44-0)

**Comment by sterkenburgsara** [comment]
@radavis ready for handoff! I spelled out the updates in a task list above, but please reach out with any questions :-)

**Comment by sterkenburgsara** [comment]
I just changed link text on that big primary action link from "go to the previous version of medical records" to "go to the previous version of My HealtheVet" in order to match Jonathan's landing page work. Sorry! Can you update to match?

**Comment by brea11y** [comment]
Accessibility review complete. Everything looks great and I experienced no screen reader issues.
