### ISSUE TITLE
[CDP] VHA - Remove account number from overview page on Pay Online component 

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#82704]
## Description

After a conversation with @kjsuarez, the UX team learned that the account number a veteran has is not persistent across locations and that it is indeed unique to each location, so this ticket is to revert a portion of part 1 #79257 that was initially conducted on this work. 

## Tasks
- [x] Remove the account number from the Copay Summary page of "Pay online" component

## Acceptance criteria
- [x] The account number only appears on the copay detail and statement pages. 

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
