### ISSUE TITLE
Connect PE test front end to API

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#82700]
## Issue Description
While the front end has components laid out for all functionality, the API was not quite ready for connecting the pieces to actually perform the desired functions. Once the API changes are ready, the front end components will need to be connected to those routes and appropriate actions need to be implemented for response handling.

---
## Tasks
- [ ] Connect all front end components to the API.
- [ ] Handle any actions that need to be taken after responses return from the API.

## Acceptance Criteria
- [ ] The components on the front end can now interact with real data and endpoints.

Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/82773

**Comment by CBonade** [comment]
This issue is still blocked for the time being as the API is not allowing requests due to the routes not being secure. Steven is actively working to find a solution to this, but until this is resolved, this ticket is not workable.

**Comment by pjhill** [comment]
PR with some working requests to the API has been merged -- https://github.com/department-of-veterans-affairs/platform-pe-test-fe/pull/6
