### ISSUE TITLE
Figure out deployment solution for test PE front end

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#82701]
## Issue Description
The first quick attempt to deploy via GitHub pages did not work as expected. Troubleshoot this deployment and if it does not work, find an alternate solution. A top candidate for an alternative would be hosting the build in S3.

---
## Tasks
- [x] Troubleshoot GitHub pages deployment method
- [x] (tentative) Decide on an alternative deployment method and implement as necessary.

## Acceptance Criteria
- [x] The PE front-end deployment method is decided.
- [x] A ticket is created to implement the deployment.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/82819 Ticket is here to implement this solution
