### ISSUE TITLE
SC | File upload name word wrap

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#82749]
## Value Statement

**_As a_** Veteran

**_I want to_** be able to know what files I've uploaded

**_So that_** I can keep track of the evidence I'e provided

---

## Background Context

On SC, when there's a long file name, there's an overflow, instead of wrapping.

Evidence summary
<img width="1208" alt="Screenshot 2024-05-09 at 11 11 32 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/4a693f3f-9f31-43d5-affa-8104b3ec6cfe">

Review
<img width="725" alt="Screenshot 2024-05-09 at 11 29 03 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/40520934-08a4-4291-9234-f163b1fdadca">

## Acceptance Criteria

- [ ] When a user uploads a file with a long file name, the filename will wrap, so the user can see all the characters within the filename.
- [ ] The user can see the full file name on the evidence summary page
- [ ] The user can see the full file name on the review page without having to scroll

## Designs and Build Notes

Filename will wrap to the width of the form panel.
<img width="510" alt="Screenshot 2024-05-09 at 11 33 07 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/111457818/0a9cb415-26be-482d-a205-4a24ddd241f3">

### Enablement team (if needed)
@jstrothman 

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@saderagsdale Pulling this into the current sprint since I refined it with Robin and he needs work.

**Comment by Mottie** [comment]
Work complete, ready to be validated in staging

**Comment by eileen-coforma** [comment]
Validated in staging 🎉
