### ISSUE TITLE
BE | Profile | Mock Repository

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#82753]
## Background
Finish prototype for new mock repository.

## Tasks
- [x] UI tasks:
  - [x] Navigation for all components
  - [x] User Mock Assignments
  - [x] Request Log
 
- [ ] Routing and Dispatching
  - [x] Handle PUT requests
  - [x] Handle POST requests
  - [x] Handle body params 
 
- [x] Add mock responses
  - [x] Contact
  - [x] Demographic
  - [x] Direct Deposit
 
## Acceptance Criteria
- [x] Test Locally
- [x] Schedule Profile Demo
- [x] Schedule VES Demo
