### ISSUE TITLE
Adjust GitHub workflows to respond to Control Plane calls

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#82768]
## Issue Description
The Preview Environment Control Plane Application requires the ability to call the following workflows in https://github.com/department-of-veterans-affairs/prt-preview-manifest:
- [deploy-environment](https://github.com/department-of-veterans-affairs/prt-preview-manifest/blob/main/.github/workflows/deploy-environment.yaml)
- [destroy-environment](https://github.com/department-of-veterans-affairs/prt-preview-manifest/blob/main/.github/workflows/destroy-environment.yaml)
- [mock-deploy-environment](https://github.com/department-of-veterans-affairs/prt-preview-manifest/blob/main/.github/workflows/mock-deploy-environment.yaml)
- [mock-destroy-environment](https://github.com/department-of-veterans-affairs/prt-preview-manifest/blob/main/.github/workflows/mock-destroy-environment.yaml)

Because the github app is not yet approved for the prt-preview-manifest repo, the calls to the prt-preview-manifest workflows will be routed through the https://github.com/patrick-black-oddball/prt-preview-manifest-prb repo's app.
The 4 workflows in the prt-preview-manifest-prb repository will need to route calls to the corresponding workflows in prt-preview-manifest

This is a temporary work around until we are ready to create the prt-preview-manifest app as part of Milestone 3.

---
### Tasks
- [x] create a credential for access to the prt-preview-manifest repo's workflows
- [x] adjust the workflows in prt-preview-manifest-prb to utilize the github API to call the workflows in prt-preview-manifest

### Acceptance Criteria
- [ ] When the control plane attempts to call the four workflows in prt-preview-manifest-prb, the corresponding prt-preview-manifest workflows are triggered.
