### ISSUE TITLE
[Board Appeals in CST] Board Appeals App Map 

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#82778]
## Background Context

We want to understand the various UI states for Board Appeals in CST.

Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/77788

Some subset of UI states can be found in the existing [App Map](https://www.figma.com/file/y27KDDtZLBDSVZmAjXdbJn/CST-App-Map?type=design&node-id=0-86&mode=design&t=iYlA5HSkNkSY5PM6-4), but it's not fully comprehensive.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- [New section of App Map for Board Appeals](https://www.figma.com/file/y27KDDtZLBDSVZmAjXdbJn/CST-App-Map?type=design&node-id=533-103&mode=design&t=Oxbzn0mYT7YqUJXa-11)

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks

Specific states we want to show include: 
- Current Status
- What happens next?
- How long until a judge is ready to hear your appeal?
- Place in line

- [ ] Design and eng collaborate to produce states, possibly in coworking session.

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _States are captured_
- [ ] _Review with team_
- [ ] _Review with BVA_

**Comment by jacobworrell** [comment]
@skylerschain @jerekshoe @uxgary @samcoforma @pmclaren19 during this sprit, please slice this ticket into chunks that can fit within this and future sprints.

**Comment by pmclaren19** [comment]
Discussed this ticket as a team @skylerschain and @jerekshoe will be working and discussing this ticket moving forward. They are planning on spending 2 points per sprint on this ticket (2, 1 hour working sessions per sprint) where they will discuss the current states of appeals and the other tasks regarding the board of appeals app map. They will create a figma file for this and add their findings to it.

**Comment by skylerschain** [comment]
**5/31**

@jerekshoe and I met to start on this. We added all variations of content based on status for the "Current Status" section. [See doc](https://docs.google.com/document/d/14gAFM2tuQWE3OdqUP0wqP1DSnRzDrhDRgeLmoB2YaTE/edit). 

We will meet again next week to continue with the rest of the sections of the page.

**Comment by skylerschain** [comment]
Full page content audit is complete:

https://docs.google.com/document/d/14gAFM2tuQWE3OdqUP0wqP1DSnRzDrhDRgeLmoB2YaTE/edit#heading=h.h6l4aov6jtbp
