### ISSUE TITLE
[FE] My VA Ben App Drafts: Simplify the SiP configuration (pt 4) - cleanup + reduce

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#82798]
## Background
Following up from Angela's work on the benefit application drafts section documentation [60510](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510), it was determined that the current process to configure a form as "save in progress" (SiP) is not as streamlined as it could be.

[Additional context](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510#issuecomment-1658652021)

We are breaking this work into three parts:
part 1: data collection and communication with other teams (#80031)
part 2: implementation and testing (#80036)
part 3: documentation updates (#80037) 
_part 4: post-staging launch cleanup_

---
## Tasks
- [ ] cleanup previous feature flag work
- [ ] update `FORM_BENEFITS`, `FORM_TITLES`, `FORM_DESCRIPTIONS`, and `TRACKING_PREFIXES` to be reduced objects of `MY_VA_SIP_FORMS`

## Acceptance Criteria
- [ ] some code is removed from platforms/forms/constants.js

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ @DanielMiller-agile6
- _How can this work be validated?_ tbd

## Resources
- [Technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)
- [SiP enabled form table (via AJ)](https://docs.google.com/spreadsheets/d/1kra-6J4y3qJxthaS1s4IPgrNLAB7a0qq3a5_m1KDiKM/edit#gid=0)

**Comment by allisonlu** [comment]
PR is merged, and is currently on staging. will be on prod after tomorrow's deploy.

@DanielMiller-agile6 can you help validate that this code has made it to the `main` branch?

**Comment by ajakabcin** [comment]
Moving to next sprint for validation only. @DanielMiller-agile6 let's reestimate for the validation effort
