### ISSUE TITLE
[FE] My VA Ben App Drafts: Simplify the SiP configuration (pt 5) - remove and convert

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#82817]
## Background=
**Note: this is low priority because this enhancement work after required work is completed**

Following up from Angela's work on the benefit application drafts section documentation [60510](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510), it was determined that the current process to configure a form as "save in progress" (SiP) is not as streamlined as it could be.

[Additional context](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60510#issuecomment-1658652021)

We are breaking this work into five parts (as of 5/9/24):
part 1: data collection and communication with other teams (#80031)
part 2: implementation and testing (#80036)
part 3: documentation updates (#80037) 
part 4: post-staging launch cleanup (#82798)
_part 5: remove and convert_

---
## Tasks
- [ ] remove `FORM_BENEFITS`, `FORM_TITLES`, `FORM_DESCRIPTIONS`, `TRACKING_PREFIXES`, `SIP_ENABLED_FORMS` constants
- [ ] (optional) convert `verifiedSavedForms` (found in [components/benefit-application-drafts/ApplicationsInProgress.jsx file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/components/benefit-application-drafts/ApplicationsInProgress.jsx)) into a `useVerifiedSavedForms` hook 

## Acceptance Criteria
- [ ] previous object code is removed from `platforms/forms/constants.js`

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ @DanielMiller-agile6
- _How can this work be validated?_ tbd

## Resources
- [Technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/sip_process_improvements.md)
- [SiP enabled form table (via AJ)](https://docs.google.com/spreadsheets/d/1kra-6J4y3qJxthaS1s4IPgrNLAB7a0qq3a5_m1KDiKM/edit#gid=0)
