### ISSUE TITLE
[Research] 10-10EZ - Short Form expansion: Discovery on including Post-9/11 Veterans for Short Form flow

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#82827]
## Benefit to the Veteran
By looking into including Post-9/11 Veterans in the current Short Form flow, we may discover a population of Veterans who qualify for "Enhanced Eligibility" for up to 10 years after discharge, and would benefit by filling out the minimal information needed to qualify.  

## Background
As more service members become Veterans, specifically those that served in the Post-9/11 era in Operation Enduring Freedom (OEF) in Afghanistan or Operation Iraqi Freedom (OIF) or Operation New Dawn (OND) in Iraq, there is an opportunity to expand the Short Form flow.  These Veterans qualify for enhanced eligibility for up to 10 years after their discharge date.  

We need to do some thinking around how we can identify Veterans and Veterans can identify themselves, so that they can be directed thru the short form flow.  We also should consider messaging for this, but need to think about whether it is needed, and if so, where it should be displayed.

#### Resources
- [Post-9/11 short form GH Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Adding%20Post-9_11%20to%20Short%20Form)
- VA.gov page - [Eligibility for transitioning active-duty service members and recent combat Veterans](https://www.va.gov/health-care/eligibility/active-duty/#enhanced-eligibility-for-retur)

## Tasks
- [ ] Research other Post-9/11 references across VA.gov pages and apps
- [ ] Research language on explaining the eligibility for Post-9/11 Veterans
- [ ] Outline findings and considerations
- [ ] Share with the team
- [ ] Outline next steps

## Acceptance Criteria
- Research on Post-9/11 Veterans is complete, findings/considerations shared with the team and we have next steps ready to go.
