### ISSUE TITLE
Research the forms library defaults for the summary/review page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82839]
## Background
We're trying to understand what is supported by default within the forms library logic, with relation to the final summary/review page.

Are we able to rely on default logic to display conditional information, based on the user's input?  And if not, what additional logic will we need to implement to support our experience?

## Tasks
- [ ] Research the forms library defaults for the summary/review page
- [ ] Outline in a comment below, regarding any additional work outside of the default that we need to be mindful of 

## Acceptance Criteria
- [ ] We have a clear understanding of what the forms library defaults for the summary/review page.

**Comment by cosu419** [comment]
The review page is rendered from the uiSchema. Its route is added automatically by the forms library. 

There are a couple config options related to the review page:

`preSubmitInfo` - additional information to be displayed on the Review page.
`reviewPageTitle` - customizable title if it veers from the form title

**Comment by oddball-lindsay** [comment]
Are we able to rely on default logic to display conditional information, based on the user's input? 

Two UI schemas, one for each form.  The conditional logic will be in the form config, with a one-line check to verify the form -- this will determine which UI schema to import for the review page.
