### ISSUE TITLE
GovDelivery Log Messages in CI

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#82835]
## Summary

GovDelivery logs a unnecessary messages from the request and response for the CI. Causing hundreds of lines useless log messages. If there is an error the test will fail so there's no need for info logs. 

In order to reduce the log output in CI the request/response messages are suppressed. 

```
I, [2018-05-30T18:18:56.000000 #20]  INFO -- response: Status 200
I, [2018-05-30T18:18:56.000000 #20]  INFO -- response: date: "Wed, 30 May 2018 18:17:56 GMT"
server: "Apache/2.2.15 (CentOS)"
x-frame-options: "SAMEORIGIN"
x-xss-protection: "1; mode=block"
x-content-type-options: "nosniff"
etag: "W/\"6112d22f31b736a3002f590517cb2e81\""
cache-control: "max-age=0, private, must-revalidate"
x-request-id: "82b2f861-4370-4db2-955c-aa0dd56ad102"
x-runtime: "0.026356"
x-served-by: "stg-xactweb3.ep.gdi"
connection: "close"
transfer-encoding: "chunked"
content-type: "application/json;charset=utf-8"
strict-transport-security: "max-age=31536000"
```

## Tasks

- [x] suppress GovDelivery::TMS::Client logs if CI=true

## Acceptance Criteria 

- [x] GovDelivery::TMS::Client doesn't logs if CI=true
- [x] GovDelivery::TMS::Client logs if CI=false or not present
