### ISSUE TITLE
Setup mock authentication for testing as we go

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82837]
## Background
To be able to simulate what we're seeing in Staging so that we aren't dependent on PRs merging (and the 24 hour delay) to confirm development locally.

There are some examples that exist for us to reference.

## Tasks
- [ ] Reference examples
- [ ] Add mock files to our Appoint app
- [ ] Create methods to simulate the login modal behavior

## Acceptance Criteria
- [ ] We are able to simulate the authenticated state of Appoint a Representative locally
