### ISSUE TITLE
Establish redux state structure and form config of the application

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82838]
## Background
Some pages of Appoint a Representative will have conditional language and pathways based on:
- if the user is a Veteran or a non-Veteran claimant.  
- if the user chooses a VSO (21-22) or an attorney or claims agent representative (21-22a).
- if the user is authenticated or unauthenticated.

To support the dynamic nature of this user experience, we will need to establish a redux state structure of the application.  Some of the logic can be added as we go, but there is value in an initial, foundational setup.

High level outline of the conditional pathways: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?sender=ubac5f0487f25bc4431288699

Part of the conditional pathways is to show when users have existing representation appointed.  We talked about also including the "activePOA" in the redux state structure to support the ability to show this information on a conditional basis.

## Tasks
- [ ] Identify all the potential properties (including activePOA), based on the conditional scenarios listed above
- [ ] Creating actions and action creators associated with the different possible updates

## Acceptance Criteria
- [ ] Initial redux actions are all setup and ready to be built upon.

**Comment by cosu419** [comment]
Moving this back in progress - looked into another multi-form implementation (21-4142 and 21-4142a) where the form type is tied to the form config (rather than the state store). This is a simpler/more maintainable approach.
