### ISSUE TITLE
Forms Digitization Guide: Determine IA on Platform Website

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#82832]
## Issue Description
The Forms Digitization Guide will need a home on Platform Website. 
Discussions between Design Service Team and Platform Content Team place the Guide in Developer Docs.
<img width="558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDM3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1439925089ef6681ae91b087e0d1c2c22aec5225/Screenshot%202024-05-15%20at%2011.03.59%E2%80%AFAM.png" alt="Screenshot 2024-05-15 at 11.03.59 AM.png" />
  

9 Docs were placed in the Dev Docs section of the PW. Those docs required lots of review to get right. 
### TASKS

- [x] Review all 9 pages
- [x] Make notes on all 9 pages for SME
- [x] Edit  9 pages for content
- [x] Edit 9 pages for formatting
- [x] Flag issues
- [x] Check all 9 pages for LB
- [x] Deploy all 9 pages

### ACCEPTANCE CRITERIA

- [x] All nine pages are live on the PW

---

## Acceptance Criteria
- [ ] Users will be able to find Forms Digitization Guide on Platform Website

### Relevant Artifacts:

- [Phases of Forms Digitization](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2900951393/Phases+of+forms+digitization)

- [Where shall we house the FDG?](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3063971861/Where+shall+we+house+the+FDG)

- Search Results for "[Forms](https://depo-platform-documentation.scrollhelp.site/search.html?l=&max=10&ol=&q=forms&s=&start=0)"

## SMEs:

- Dan Turner
- Naomi Marcussen
- Bryan Ivie

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
All nine pages check. LB issues communicated to SME via [this slack thread.](https://dsva.slack.com/archives/CL181NRJQ/p1716246727180049)

**Comment by jknipes** [comment]
cc: @twoangstroms @steel36 @naomimarcussen

**Comment by jknipes** [comment]
This work was started early, we are factoring it into Sprint 2, 5/23/24

**Comment by jknipes** [comment]
work is completed, moving to _Done_
