### ISSUE TITLE
Determine what staging users we need/should use for Profile 2.0 QA

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8284]
## Background
We need to determine what staging users an be used for different functionality within profile 2.0. For example the various levels/states of the "Account Security" screen.

### Tasks
- [ ] Determine what staging users we should use for profile 2.0
- [ ] Create any staging users if needed 

### Sections
- [x] Account test cases
- [ ] Profile test cases
-  [X] Identity verified vs not verified (Not verified = user 350, Verified =user 36)
-  [X] [Direct deposit - staging users/test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/test-users.md) 
- [X] Military Info staging users/test cases - N/A
- [ ] Connected apps staging users/test cases
- [x] 2FA verified
- [x] Non 2FA verified  (you can create your own in staging)
- [ ] Terms and conditions accepted
- [ ] Terms and conditions NOT accepted

### Other info
user 350 is LOA1
LOA1 is NOT identity verified
LOA3 is ID verified

**Comment by mshea0606** [comment]
Use cases and staging users have been added to this google sheet

https://docs.google.com/spreadsheets/d/1-dU7C4i6FeCCK6L4SdljwhQ8TjMuZrgsblt9SPiBWRg/edit#gid=1570304628
