### ISSUE TITLE
New endpoint for searching for a representative/organization

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82840]
## Background
At the beginning of the Appoint a Representative experience, users will be searching for a representative or organization by name.  After a representative is selected, we will need to pass all of that representative information to the frontend.

- **Individual representatives** should return address, email and phone.
- **Organizations** should return address and phone (organizations don't have email).

I imagine most search results will be individual representatives OR organizations, but because we don't have a distinct filter for users to indicate if they're searching for an individual or organization there is a small possibility of a search query pulling up individuals AND organizations.  

**Example**: searching "Dale" or "Graham" could bring up individual representatives named "Dale" or "Graham", but the VSO "Dale K. Graham Veterans Foundation" could also come up.

## Approach
We would like to use our new tables and new module, but there's a bit of trickiness because the Accreditation API isn't available yet and so we can't currently populate our new tables.

We can still do this work, populate the tables locally and verify the endpoint functionality.  Then wait for the Accreditation API to be ready so we can then start using the new tables and get this endpoint fully up.

## Experience
We don't have a ticket yet for the frontend experience of this representative/organizational search experience, but here are the designs to help visualize our end goal.  Prototypes are linked to see the interaction, and screenshots are for quick reference.

[Empty search + search results for an **individual**](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-148434&t=V9tziqHiwSiRqoCN-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=455%3A148692&show-proto-sidebar=1):
<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b747b555defd73df22bfc6ccf0580a7f8f57319/image.png" alt="image.png" />

Search results for an **organization**:

<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d01daf18f373f4a4cac2f83357c43504ee523c7/image.png" alt="image.png" />

## Tasks
- [x] Create the new endpoint in our new module
- [x] Test the endpoint locally to ensure representative names return expected search results
- [ ] Document the new endpoint in swagger docs
- [ ] Anything else?

## Acceptance Criteria
- [ ] The endpoint has been created and is functioning locally as expected, ready for testing in VA.gov Staging when we get access to the Accreditation API Staging environment. 
- [ ] 

Notes:

- We'll need to implement fuzzy search across the org reps and individual reps;;
- We'll query the names of the individual reps and the reps within an org.  The user will be looking for a representative that they've already been in contact with.
- The fuzzy search will return a mix of individual reps and org reps
- Does/can the fuzzy search incorporate any kind of score?
- We'll need to sort in the most intuitive way we can think of.  Find a rep uses distance but that won't make sense when returning orgs in the mix.  We'll have to see if the `pg_trgm` extension can order results by the `word_similarity `score.
- Because we want the individual rep results to be returned along with VSOs we'll need to query both tables and combine those results.  This might be one big SQL query or one query for the `AccreditedIndividual` model and one for the `AccreditedOrganization` model and combining those results in ruby.
- Both of those models live in the top level vets-api `app/models` folder.

**Comment by opticbob** [comment]
Daily Update

- The first pass at sorting individuals and orgs together in one results list is done
- The serializer is next on the list

**Comment by opticbob** [comment]
Daily Update

- Simplified architecture by using the existing `OrganizationSerializer`
- Added a spec for the new `IndividualSerializer`
- Writing a spec for the query that sorts the individual and org results

**Comment by opticbob** [comment]
Daily Update

- Finishing request specs
- Personal review before requesting review

**Comment by oddball-lindsay** [comment]
Rep names we can use for testing -- these had more than 10 matches in our Find a Rep experience, where the trigram threshold is set to 0.5.

1. Jeremy Miller
2. Michael Reeve
3. Eric Taylor

@opticbob added a task up above so we remember to test locally with these names :)

**Comment by opticbob** [comment]
To test our query I loaded in 14.5K actual representative names as `AccreditedIndividual`s into my local database.  The common names listed above returned 100+ results with a trigram threshold of `0.5`.  We only want to show 10 max and we're not going to paginate so I tested turning that threshold up.

At `0.7` those names had the following number of results:
Jeremy Miller: 1
Michael Reeve: 6
Eric Taylor: 1
William Bible: 1

We also tested the shortest name on the list at 5 characters including a space and the two longest names at 31 characters including a space.  All of those tests returned the one desired result.

With all of those results we're comfortable setting the trigram threshold to `0.7`.  See all the details in slack [here.](https://dsva.slack.com/archives/C07FKH4NH35/p1723487033473599)

**Comment by opticbob** [comment]
Daily Update

- Researched different trigram thresholds as written up above, settled on a value of `0.7`
- Adjusted tests to account for the new threshold value
- Cleaned up to prepare for review

**Comment by oddball-lindsay** [comment]
@opticbob could you please share the official name of the new endpoint?  I've been calling it `the Appoint a Representative “rep/org search” endpoint` but there's gotta be a more specific/succinct way to say that.

**Comment by holdenhinkle** [comment]
He named it 'accredited_entities_for_appoint'

**Comment by opticbob** [comment]
That PR for the postgres extension will need to be merged before the main PR for this ticket.

**Comment by opticbob** [comment]
Daily Update

- Going to ping support for review of the migration PR
- Addressing @jvcAdHoc 's feedback
