### ISSUE TITLE
Create and publish new FMB benefit detail page: Educational and career counseling (VA Chapter 36) for family members

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#82858]
## Description
First, we need to create and publish the new FMB version of this existing benefit detail page: [Educational and career counseling (VA Chapter 36)](https://www.va.gov/careers-employment/education-and-career-counseling/)

Then, we need to update the existing benefit detail page to focus exclusively on Veterans.

## Tasks

<details>
<summary>Step 1: New family member page</summary>

- [ ] DB: Draft page in Drupal (with support from AP, as needed)
- [ ] DB: Share page with BP
- [ ] BP: Share page with SMEs
- [ ] DB: Share page with MZ
- [ ] MZ: Copyedit and publish

</details>

<details>
<summary>Step 2: Existing Veteran page</summary>

- [ ] DB: Update page in Drupal (with support from AP, as needed)
- [ ] DB: Share page with BP
- [ ] BP: Share page with SMEs
- [ ] DB: Share page with MZ
- [ ] MZ: Copyedit and publish

</details>

## Criteria
- [ ] We've published the new FMB page
- [ ] We've published updates to the existing Veteran benefit page

**Comment by aprocik1** [comment]
Update: Danielle and Mikki made these decisions in yesterday's FMB weekly meeting:

1. We will create a family-facing page for dental insurance, even though the content is nearly identical to the Veteran-facing page. We will monitor the success of the family-facing page using analytics.
2. We won't create a family-facing page for Chapter 36, since the content is nearly identical to the Veteran-facing page. We may create a family-facing page in the future, depending on the success of the family-facing page for dental insurance.

For now, I'm moving this ticket to blocked. If we decide not to create a family-facing page at all, we can close this ticket.

**Comment by aprocik1** [comment]
Update: These two Chapter 36 pages already exist on VA.gov:
- [Educational and career counseling (VA Chapter 36)](https://www.va.gov/careers-employment/education-and-career-counseling/): This is a Veteran-facing page
- [Employment benefits for dependent family members](https://www.va.gov/careers-employment/dependent-benefits/): This is a family-facing page

We'll move the family-facing page to the FMB hub. That work is being tracked in #83547.

**Comment by aprocik1** [comment]
I'm closing this ticket. The remainder of this work is being tracked in #83547.
