### ISSUE TITLE
Create and publish new FMB benefit detail page: Edith Nourse Rogers STEM Scholarship for family members

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#82857]
## Description
First, we need to create and publish the new FMB version of this existing benefit detail page: [Edith Nourse Rogers STEM Scholarship](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/)

Then, we need to update the existing benefit detail page to focus exclusively on Veterans.

## Tasks

<details>
<summary>Step 1: New family member page</summary>

- [ ] DB: Draft page in Drupal (with support from AP, as needed)
- [ ] DB: Share page with BP
- [ ] BP: Share page with SMEs
- [ ] DB: Share page with MZ
- [ ] MZ: Copyedit and publish

</details>

<details>
<summary>Step 2: Existing Veteran page</summary>

- [ ] DB: Update page in Drupal (with support from AP, as needed)
- [ ] DB: Share page with BP
- [ ] BP: Share page with SMEs
- [ ] DB: Share page with MZ
- [ ] MZ: Copyedit and publish

</details>

## Criteria
- [ ] We've published the new FMB page
- [ ] We've published updates to the existing Veteran benefit page

**Comment by aprocik1** [comment]
Update: Danielle and Mikki made these decisions in yesterday's FMB weekly meeting:

1. We will create a family-facing page for dental insurance, even though the content is nearly identical to the Veteran-facing page. We will monitor the success of the family-facing page using analytics.
2. We won't create a family-facing page for the STEM scholarship, since the content is nearly identical to the Veteran-facing page. We may create a family-facing page in the future, depending on the success of the family-facing page for dental insurance.

For now, I'm moving this ticket to blocked. If we decide not to create a family-facing page at all, we can close this ticket.
