### ISSUE TITLE
Collaboration Cycle for Transition Experience, tbd, V1 Transition Experience

### ISSUE THREAD

**Issue by nkontrabecki** [department-of-veterans-affairs/va.gov-team#82863]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1301) for all feedback and findings tickets associated with this Collaboration Cycle initiative.

### VFS team name

Transition Experience

### Product name

Transition Experience MVP v1

### Feature name

V1 Transition Experience

### GitHub label for team

transition-experience

### GitHub label for product

transition-experience-MVP

### Public DSVA Slack channel for VFS team

#ves-transition

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

May 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Both

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Unsure

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/vet-transition-support

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.
Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C06C7RS27GD/p1715355788426939)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [X] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1716219020147/013c6f25f45e35963469c7bb7a94b66e1402f663?sender=uba527cafb8ded20512886129)

Not required, but nice to have:
- [X] [Wireframes](https://www.figma.com/design/Y72reZ0Qt9xteezdnLbBDW/Wireframes-for-v1?node-id=0%3A1&t=l90aXJCrJfAktf1O-1)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [x] [Design Intent Slack thread with VFS team](https://dsva.slack.com/archives/C06C7RS27GD/p1715625704260119)
- [x] Meeting date/time: **Friday, May 24, 2024 at 2:00PM ET**
  
##### Governance Team actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/HNkdixvhDWWXV70fBQEVlWlmaKKM-ZIRkwztoaCcWR4bD7bNQi6uOkz3m64SR3SK.llJFqX4Yo-73350T)
  - Passcode: `$PG.2BhD`
- Accessibility
  - [x] Feedback added to milestone
  - [ ] No feedback
- Design
  - [x] Feedback added to milestone
  - [ ] No feedback
- IA
  - [x] Feedback added to milestone
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

**11/15/2024 Mid Point Review artifacts follow:**
- [X] [Updated User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731449057856/95f82d015d5fb85454261ac99fba1e7e5a218452?sender=u82df846ee309a69c4f0d1792)
- [X] [Finalized design prototype or mockup](https://www.figma.com/design/4J2vqMA2VY6wqgcjvhF2aT/v2-Prototype-Design?node-id=0-1&node-type=canvas&t=1dW0CivCpObQfhMF-0) Please refer to the 2 pages labeled: "Desktop Mockups" and "Mobile Mockups" 
- [x] Specify which pages are included in the review: **All pages of our product**
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/research/2024-10-user-testing-v2/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/research/2024-10-user-testing-v2/conversation-guide.md)

**Content artifacts**

[CAIA intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802)

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

Feedback included as comments in Figma

- [ ] None received

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
- [x] [Link to the CAIA intake form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802) and [Link to the IA feedback from our Design Intent meeting](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83999)

**7/11/2024 Mid Point Review artifacts follow:**
- [x] [Finalized design prototype or mockup](https://www.figma.com/design/DNy6D8ELfTQW1g3EK7yJu5/Mid-Fidelity-Prototype-for-v1?node-id=2643-7998&t=Q4dUcfCm5ja3SRpf-0)
- [x] Specify which pages are included in the review: **All pages of our v1 product**
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/research/2024-02-discovery/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/research/2024-02-discovery/conversation-guide.md)
 
**Content artifacts**

[CAIA intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802)
  
- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
- [x] None received

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
- [x] [Link to the CAIA intake form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802) and [Link to the IA feedback from our Design Intent meeting](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83999)

Note: As documented in the comments on the IA feedback ticket, we are not including a "Skip" button per the team's original recommendation, due to development challenges. With the IA team's agreement, we are leaving all questions except one as "optional," so the user can skip questions by not answering them.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C06C7RS27GD/p1716411335425739)
- [x] Meeting date/time: July 11, 2024 at 3:30 p.m. ET

##### Platform actions

* Accessibility
  * [x] Feedback added to milestone
  * [ ] No feedback
* Content
  * [x] Feedback added to milestone
  * [ ] No feedback
* Design
  * [x] Feedback added to milestone
  * [ ] No feedback
* IA
  * [x] Feedback added to milestone
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/d-ZhTjwjXmxf9jntGuC91jlZdojR3O4FJjfgT0jWYNPGXW9olmb0Q84fycuJr-Tc.Hatm3CO7Zc0jxPds)
  - Passcode: `3%p2vxn2`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [ ] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below

</details>

### Staging Review v1
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided. **unauthenticated experience does not required test user accounts**
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] [Staging URL](https://staging.va.gov/benefit-eligibility-questionnaire/introduction)
- [x] Specify which pages are included in the review  
[Complete the benefit eligibility questionnaire-Introduction](https://staging.va.gov/benefit-eligibility-questionnaire/introduction)
[Complete the benefit eligibility questionnaire-goals](https://staging.va.gov/benefit-eligibility-questionnaire/goals)
[Complete the benefit eligibility questionnaire-time served](https://staging.va.gov/benefit-eligibility-questionnaire/service/time-served)
[Complete the benefit eligibility questionnaire-current](https://staging.va.gov/benefit-eligibility-questionnaire/service/current)
[Complete the benefit eligibility questionnaire-separation](https://staging.va.gov/benefit-eligibility-questionnaire/separation)
[Complete the benefit eligibility questionnaire-discharge](https://staging.va.gov/benefit-eligibility-questionnaire/discharge)
[Complete the benefit eligibility questionnaire-disability](https://staging.va.gov/benefit-eligibility-questionnaire/disability)
[Complete the benefit eligibility questionnaire-GIBill](https://staging.va.gov/benefit-eligibility-questionnaire/gi-bill)
[Complete the benefit eligibility questionnaire-review your entries](https://staging.va.gov/benefit-eligibility-questionnaire/review-and-submit)
[Complete the benefit eligibility questionnaire-your benefits and resources](https://staging.va.gov/benefit-eligibility-questionnaire/confirmation)

- [x] Staging test user information - Unauthenticated experience. Does not require test user information.    
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

[Midpoint Review - Content Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88266)
  
**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

[CAIA Intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802)
[Midpoint Review - IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88203)
[Additional IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82863#issuecomment-2225679668)

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] Regression Test Plan - Not Required. New product launch.
- [x] [Test Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/VTS%20V1%20MVP%20Test%20Cases.xlsx)
- [x] Traceability Reports - The test cases documented and executed in the test plan cover all user stories.
- [x] [E2E Test Participation](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/benefit-eligibility-questionnaire/tests/e2e/benefit-eligibility-questionnaire.cypress.spec.js)
- [x] [Unit Test Coverage](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/Unit%20Test%20Coverage.png)
- [x] End Point Monitoring - Not required because we do not have any endpoints
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92960). 
- [x] For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

  
##### Platform actions
- [ ] [Slack thread with VFS team](https://dsva.slack.com/archives/C06C7RS27GD/p1726227114949259)
- [ ] Meeting date/time: 01:30pm ET Thu, Sep 26, 2024

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/1QFqwjjINCRgAHEktHvvOn8fKyAg41uIg29sIzR8JJla1rti9nuwjijn9m8CIcCT.ukVM5V8B_isRmmYn)
  - Passcode: `HE%d&60Q`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [x] Link to the Readiness Review ticket below
[Readiness Review Transition Experience, Unauthenticated, MVP V1 #1897](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1897)

[Short term POAM created](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1911)

#### Platform actions
- [x] Privacy, security, infrastructure readiness review is complete

</details>

### Staging Review v2
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [x] [Staging URL](https://staging.va.gov/discover-your-benefits)
- [x] Specify which pages are included in the review  
[Discover your benefits](https://staging.va.gov/discover-your-benefits)
[Discover your benefits-Introduction](https://staging.va.gov/discover-your-benefits/introduction)
[Discover your benefits-goals](https://staging.va.gov/discover-your-benefits/goals)
[Discover your benefits-time served](https://staging.va.gov/discover-your-benefits/service/time-served)
[Discover your benefits-current](https://staging.va.gov/discover-your-benefits/service/current)
[Discover your benefits-completed](https://staging.va.gov/discover-your-benefits/service/completed)
[Discover your benefits-separation](https://staging.va.gov/discover-your-benefits/separation)
[Discover your benefits-discharge](https://staging.va.gov/discover-your-benefits/discharge)
[Discover your benefits-disability](https://staging.va.gov/discover-your-benefits/disability)
[Discover your benefits-GIBill](https://staging.va.gov/discover-your-benefits/gi-bill)
[Discover your benefits-review your entries](https://staging.va.gov/discover-your-benefits/review-and-submit)
[Discover your benefits-confirmation](https://staging.va.gov/discover-your-benefits/confirmation)
[Discover your benefits-review and submit](https://staging.va.gov/discover-your-benefits/review-and-submit)
[Discover your benefits-view all benefits](https://staging.va.gov/discover-your-benefits/confirmation?allBenefits=true)

- [x] Staging test user information - Unauthenticated experience. Does not require test user information.    
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

[Midpoint Review - Content Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88266)
  
**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.

[CAIA Intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802)
[Midpoint Review - IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97318)

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] Regression Test Plan - Not Required. New product launch.
- [x] [Test Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/VTS%20V2%20Test%20Cases.xlsx)
- [x] Traceability Reports - The test cases documented and executed in the test plan cover all user stories.
- [x] [E2E Test Participation](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/discover-your-benefits/tests/e2e/discover-your-benefits.cypress.spec.js)
- [x] [Unit Test Coverage](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/CodeCoverageReport.JPG)
- [x] End Point Monitoring - Not required because we do not have any endpoints
- [ ] Logging silent failures
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97750#issuecomment-2498414633). 
- [x] For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

##### Platform actions
- [x] [Slack thread with VFS team
](https://dsva.slack.com/archives/C06C7RS27GD/p1730754054236889)
- [x] Meeting date/time: 02:00pm - Friday, December 6, 2024 (Eastern Time - US & Canada)

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/45K1opvV19qav7eMCKBEpP_QSWhIiY8yW0XCT8KmoEmpuRCg073wdeHf_iveAyiV.2qEcY6xwdoMuZqQ-) 
  - Password: `Y9!%TmQ^`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [x] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [x] Share ServiceNow ticket number here: _RITM13176104_____
REQ36476402 - 508 group reviews and works with customer to fulfill request.

- [x] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Midpoint Review v2
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [X] [Updated User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731449057856/95f82d015d5fb85454261ac99fba1e7e5a218452?sender=u82df846ee309a69c4f0d1792)
- [X] [Finalized design prototype or mockup](https://www.figma.com/design/4J2vqMA2VY6wqgcjvhF2aT/v2-Prototype-Design?node-id=0-1&node-type=canvas&t=1dW0CivCpObQfhMF-0) Please refer to the 2 pages labeled: "Desktop Mockups" and "Mobile Mockups" 
- [x] Specify which pages are included in the review: **All pages of our product**
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/research/2024-10-user-testing-v2/research-plan.md)
- [x] [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/vet-transition-support/research/2024-10-user-testing-v2/conversation-guide.md)

**Content artifacts**

[CAIA intake](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802)

- [ ] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.

Feedback included as comments in Figma

- [ ] None received

**IA artifacts**

- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-caia-intake-request) feedback you received, including an IA review document or intake form.
- [x] [Link to the CAIA intake form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83802) and [Link to the IA feedback from our Design Intent meeting](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83999)
 
##### Platform actions
- [x] [Slack thread with VFS team
](https://dsva.slack.com/archives/C06C7RS27GD/p1730907671846339)
- [x] Meeting date/time: 11:30am - Friday, November 15, 2024 (Eastern Time - US & Canada)

##### Platform actions

* Accessibility
  * [x] Feedback added to milestone
  * [ ] No feedback
* Content
  * [x] Feedback added to milestone
  * [ ] No feedback
* Design
  * [x] Feedback added to milestone
  * [ ] No feedback
* IA
  * [x] Feedback added to milestone
  * [ ] No feedback
* [x] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/play/kBOJNaiPpXgt2bWWWxaRLL69FRAIGYmRVfvboMe7CqPgArfizK1REfLcFcmSki8CfHJQX8SOnBiodGG8.miCt_rZHAf4V-fwi?autoplay=true&startTime=1731688245000
  - Passcode: `W=8X2TCg`
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

[

**Comment by rtwell** [comment]
+1 to @artsymartha68 comments. I suspect the search results page will be the most revealing on smaller screens because there is so much stuff pushing the search results (the thing that is most important) down the page. 

Also +1 to what i believe @erinrwhite suggested regarding H2s and dropping the accordions altogether — generally speaking, it'd be nice if all search results on VA.gov delivered a very similar experience. There are many search tools, and i would think no matter which of them a user decides to use, they would expect them behave similarly — maybe not exactly the same depending on the needs, but similar. Dropping the accordions def gets us nearer to that unified experience.

**Comment by nkontrabecki** [comment]
@artsymartha68  The team is working on the mobile mock ups. What is the recommended review process once we are ready for your team to review and provide feedback? @cora-goldston-bah

**Comment by artsymartha68** [comment]
If @briandeconinck doesn't have the time to take another look, I may be able to help a bit (but I'm nowhere near as good as Brian!). Just reach out on slack. Hopefully struggling with the small mobile screen will help you streamline the workflow and content you're presenting.

**Comment by nkontrabecki** [comment]
@briandeconinck  and @artsymartha68 Our team started the mobile web  Figma Mock ups. We are still working on the Results page portion. Please review the mobile version and provide feedback on what we have accomplished to date. As soon as we have the Results page completed, I will let you know. [VTS Mobile Web Figma](https://www.figma.com/design/DNy6D8ELfTQW1g3EK7yJu5/Mid-Fidelity-Prototype-for-v1?node-id=2963-10117&t=WKcXwLwIbUVLKmVS-0)

**Comment by artsymartha68** [comment]
This is really shaping up! You broke out the questions to “one thing at at time” and reduced the content to its core. This is so difficult design-wise but really makes a big difference, especially for the folks who will be using this questionnaire.

**Comment by nkontrabecki** [comment]
VA 508 Office audit is requested and completed. 1 defect to be addressed in a future iteration. Thank you
