### ISSUE TITLE
Make app code compliant with ESLint prefer-stateless-function rule

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#8286]
## Background

The [`prefer-stateless-function`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md) ESLint rule is already a part of one of our plugins, but we currently have it turned off. Leaving it turned on would help simplify some React components

We have had two PRs which make the platform code compliant with [prefer-stateless-function]

- https://github.com/department-of-veterans-affairs/vets-website/pull/12224
- https://github.com/department-of-veterans-affairs/vets-website/pull/12293

## Next steps

We currently have 67 errors with this rule turned on across the following apps:

- `claims-status`
- `disability-benefits`
- `facility-locator`
- `gi`
- `hca`
- `id-card-beta`
- `letters`
- `personalization`
- `post-911-gib-satus`
- `static-pages`
- `validate-mhv-account`
- `vaos`
- `veteran-id-card`

We need to fix those existing issues before this rule can be turned back on in the main linting setup, though we _could_ still add it to the additional-linting job that Circle runs.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Where possible, convert existing app code to use functional stateless React components

## Acceptance Criteria
- [ ] `prefer-statless-function` can be turned on without breaking anything
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by meganhkelley** [comment]
@jhonnyoddball can you provide an update on the progress you made with this when you were working on it a few months ago? Thanks!

**Comment by jhonnyoddball** [comment]
@meganhkelley `prefer-stateless-function` is currently active in our `.eslintrc` file. After running 
`yarn lint:js` locally, there are no issues with this rule. I would say there's no additional work to be done with this rule.
