### ISSUE TITLE
[CAIA Intake] <Benefits Non-Disability>: <COE Form Updates>

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#82884]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Benefits - Non-Disability Experience 
- **OCTO product owner:** Emily Theis / Ryan Powers
- **Product name:** Certificate of (Loan) Eligibility (COE), 26-1880
- **Product manager:** Laura Steele
- **Slack channel:** #benefits-non-disability
- **Dedicated content writer on your team (if you have one):** none
- **Dedicated a11y specialist on your team (if you have one):** none
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [x] Updating existing unauthenticated content on VA.gov
- [x] Something else: Updating confirmation email

### What's the nature of your initiative and desired outcomes?

The current online COE form is using an outdated version of the paper form. It's missing new fields and generating an old version of the form pdf. It also contains v1 components that need to be updated to v3.

Desired Outcome: Veterans submitting online form 26-1880 have a positive experience and can trust that their submissions include all the required information to ensure efficient processing.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
We are current updating the form flow and starting conversations with our VA SMES. We are targeting a December 2024 launch of this form.

### Will you release this new product incrementally (for example, release to 25% of users to start)?
- [x]  Yes
- [ ]  No
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [x]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** [#82822](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82822)

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/apply-for-home-loan-COE)
- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/apply-for-home-loan-COE/initiative-brief-2004-COE-updates.md)
- [Form Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710194001946/6515464c5bd118903f111a4ec876c8d5ee8766a6?sender=u934f98f179a86c76e6ee9592)
- [VA.gov form tool entry page](https://www.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by steele-lm** [comment]
@strelichl Thanks for reaching out. @fiorella-io has been trying to connect with the correct SMEs, but it's been challenging, so we had to push back the Design Intent (date TBD). I would like to have all the design/content updates finalized by the end of July or early August.

**Comment by steele-lm** [comment]
@strelichl Thanks for checking in. We are still making some content tweaks. We had Design Intent for COE on 6/18, and we have a meeting with a new (to us) set of SMEs on 7/2 to answer some outstanding questions. I believe @fiorella-io may have content ready to review around the week of 7/8.

**Comment by jennymayoco** [comment]
Hi @steele-lm @fiorella-io! I'll be the IA person assigned to this work. I've been reviewing the designs and have some follow-up questions, which I'll drop in Figma. 

Just a heads up, our Content team is currently on other product team work so please expect a content review to come later.

cc @strelichl  @NaomiPMC

**Comment by jennymayoco** [comment]
@fiorella-io, I added some comments in the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710194001946/6515464c5bd118903f111a4ec876c8d5ee8766a6?sender=u79ee90295fdb006d7f463212) as well.

More generally, I see there's a few new pages. Happy to provide support if you've mapped that out or share recommendations for the sub-urls!

**Comment by aprocik1** [comment]
Hi @steele-lm, thanks for your patience. I'll be the content specialist working on this project. Can you provide a link to your most up-to-date Figma file? And can you confirm that the content in the file is ready for my review? I know Jenny provided some recommendations and you all were working to confirm final details with SMEs. Thanks!

**Comment by fiorella-io** [comment]
Hi @aprocik1! Happy Friday! Here's the [Figma file](https://www.figma.com/design/I40qWfEd6F4CSPfDSMqGeQ/COE-2024-Updates?node-id=0-1&t=iVc9Gdvp34XBT2pn-1). I'll set up a kickoff meeting next week to go over what a COE is, our scope, the flow, what we've done, discussion documents between our SMEs, and ways of working. I'm looking forward to working together!

**Comment by scjwalker** [comment]
In a 9/23 meeting with the product team and Dené Gabaldón, CAIA learned that the COE work is likely to pause briefly. I worked with @aprocik1 and @coforma-jamie to document the CAIA work done to-date. We've documented everything [in this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721063206782/0a167c4478308698551a3de3a9bdf320cfb34298?wid=0-1727383030686), with the aim of being able to pick up where we left off.

You'll notice four sections in the Mural:
- [CAIA COE deliverables as of 9.27.2024](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721063206782/0a167c4478308698551a3de3a9bdf320cfb34298?wid=0-1727456570705) - this is a list of the CAIA work that's completed or in-process.
- [CAIA recommendations for COE](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721063206782/0a167c4478308698551a3de3a9bdf320cfb34298?wid=2-1727199649046) - these are recommendations outside of the form itself, to support the service-design and help achieve navigation that is consistent with other benefits. ** <- this one is worth a look by folks thinking about roadmap and technical estimates.**
- [Draft online form flow with content](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721063206782/0a167c4478308698551a3de3a9bdf320cfb34298?wid=0-1725458525195) - this form content is likely ready to be picked up by a team development the form, though if significant updates are made outside the form, this may need updates to keep everything consistent.
- [IA Spec Draft](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721063206782/0a167c4478308698551a3de3a9bdf320cfb34298?wid=136-1726587682798) - this information is generally ready to create an IA Spec in GH. I'm pausing it  rather than making the GH ticket, in case future changes require an update to the spec.

**Comment by aprocik1** [comment]
Recording this update from Sam:

> Dené just responded that the work is still paused, and will be moving to the IRR team over the next month. There's no new launch date so far.
>
> I let her know that CAIA won't expect this to come through before the end of the year. And that they should let us know if it's looking otherwise!
>
> [Here's the convo](https://dsva.slack.com/archives/C057W3N9K2S/p1730822740096559)

I'm moving this ticket to blocked for now.

**Comment by laurenvocke-va** [comment]
@VCM86 to check on this

**Comment by steele-lm** [comment]
@VCM86 My team handed off the maintenance of this form to the IIR team. @kingbmike is Content support still needed for COE/LGY form updates?

**Comment by VCM86** [comment]
Hi @kingbmike! Checking in on this ticket and Laura's question from last week. Does your team need Content & IA support, or is it okay to close out this ticket? Thanks!

**Comment by kingbmike** [comment]
Hi @VCM86.  It would be ok to close out this ticket.  My apologies as I thought I had responded to this, but there must have been another one in question as well that I replied to.  Thank you.
