### ISSUE TITLE
[Frontend] Review Page - Batteries, Accessories 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#8289]
## User Story or Problem Statement
As a veteran I would like the ability to review my orders  on the order review page. If the information is incorrect I would like the ability to edit them from the review page. 

## Goal

Snow the selected hearing aid and/or accessories on review page and have the ability to edit 

---
## Tasks
- [ ] _Functionality to view - edit  batteries/accessories in review page 

## Acceptance 
- [ ] _for a test user, the selection of hearing aid batteries, accessories that are chosen on product selection page should be reflected on the review page. 
- [ ] _for a test user, the batteries and accessories displayed on the review page should have an edit option and once edited the choices should be reflected on the review page.
