### ISSUE TITLE
Audit Top VFS Submitters

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#82897]
## Description 
This ticket will house the task of analyzing the top submitters of tickets to the VFS Platform Support Slack Channel.
---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Make a copy of the [Platform Support Responses doc ](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=604576535)
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc]
- [ ] Create a pivot table or other visual representation of the top submitters (up to the top 25)
- [ ] Create a separate tab and add that list with the PM for each to identify if this is an individual issue or team issue (it may be a non issue altogether!)
- [ ] (https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Work is being done in these two tickets instead:

https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/83610

https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/83612

Closing duplicate.
