### ISSUE TITLE
Create KPIs and ensure business alignment

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#82894]
## Tasks

- [x] Grab Appointments KPIs that Jeff did last quarter
- [x] Chat with Peter, Jeff, Lauren and Leah about KPIs
- [x] [Fill out KPIs and establish baselines](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling#measuring-success)
- [x] Share with team and Kay 
- [x] Prepare to share with business, when ready, to get feedback

**Comment by benbrasso-agile6** [comment]
Closing. Documentation above and meeting scheduled to discuss implementation.
