### ISSUE TITLE
Accessibility Audit: Higher Level Review

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#82890]
Regular audit of Higher Level Review. A list of issues will be created to be resolved below in this epic.

**Note**: One issue is that we don’t have mock users with claims that are within a year, so we won’t be able to test contestable-issues.

[URL for testing](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996).

User: `[vetsgov+test236@id.me](mailto:vetsgov+test236@id.me)`

## Automated testing

- [x] Run axe checks on every page or unique state (required)
- [x] Run WAVE or other automated testing tools if time allows

## Keyboard testing

- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [x] All elements under focus have a visible focus indicator
- [x] The order of [Tab] stops made sense and was appropriate for completing tasks

## Color contrast and colorblind testing

- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1 contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

## Zoom testing

- [x] No functionality has been hidden or removed from the page. (Example: a button that is visible on desktop but hidden on a mobile device will likely be hidden at high zoom.)
- [x] Nothing overlaps. (Example: text getting covered up by other elements.)
- [x] No horizontal scrolling. (Exceptions: data tables, charts, and images.)

## Screen reader testing

- [x] Chrome + JAWS
- [x] Firefox + NVDA
- [x] Safari + VoiceOver
- [ ] iOS Safari + VoiceOver (time and device permitting)

## Feedback framework
❗️ Must for if the feedback must be applied
⚠️ Should if the feedback is best practice
✔️ Consider for suggestions/enhancements

**Comment by davidakennedy** [comment]
Status update: Done with automated testing and keyboard testing.

**Comment by davidakennedy** [comment]
Status update: Completed color contrast, colorblind and zoom testing.
