### ISSUE TITLE
Banner text length

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8290]
## Problem Statement
How might we limit the amount of text used within a banner displayed on VAMC pages?
Is VAMC system banner alert it's own content type?
In other words if we made changes to this would said changes be limited just to the VAMC product or would it be a train wreck because it's a global, reusable component?
In a parallel manner, If this is not our own sandbox, is there a way to restrict this to, say, 300 characters, that will keep that guardrail limited to just the VAMC product?
And while I'm on a roll: I think we should, for the backlog, think about the workflow in this area as well.
Looking at how this was built, should a VAMC continually be updating the same node with each alert (which I think triggers the GovDelivery) or should s/he be creating a new node for each alert.  What's the right workflow? (I can think of cases for both)

## Background: 

- The banner is it's own content type: admin/structure/types/manage/full_width_banner_alert 
- There is a limiting mechanism on each banner "node" to target the system(s) where it should appear. 
- It is possible to clone the original and target the new system on the newly cloned banner node (as opposed to just adding on additional systems on the original banner node). 
- Previous functionality included a "show more" collapsible kind of mechanism for longer text. 

## Goal
Prevent banners from becoming excessively long and forcing regular page content "below the fold"

## Objectives or Key Results this is meant to further
- Objective 3: Deliver a usable and accessible experience

---
## Tasks
- [ ] Identify options for allowing flexibility and "self-goverance" for banner text while preserving user functionality and easy viewing of main page content

## Acceptance Criteria
- [ ] [TBD]
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing as duplicate
