### ISSUE TITLE
[Design] [Pre-Check in] Pull Wireframes into Our Figma Files

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#82909]
## Description
We had an OIG/Congressional request come in to add some medication-related content to appointment notifications and detail pages for all appointment types on all channels. This impacts the mobile app, VA.gov web appointments, email reminders, text message reminders/pre-check-in, MHV Classic, and My VA Health portals. The objective is to remind Veterans to be ready to talk about any medication, supplement, vitamins, etc that they have been prescribed or are taking from any provider, VA clinic, or local store. 

## Content
[Final approved content](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EZ1cVb_w1MZEod5kMVhU6dwBrMJD5C56RAwbfSerVCgqhg?e=tyTF62)

## Tasks
- [x] Add [Peter's pre-check-in wireframes](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32909&t=HYVa0mv4dSCnnRxz-4) into the pre-check-in "[Design](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-Check-in?node-id=72%3A19372&t=qUU7qysnqLmlW4Zu-1)" page
- [ ] Create any needed annotations using the Annotation Library components to, 1) let team members and stakeholders know what has changed, and, 2) what, if any, heading annotations, aria label values, urls, link paths and/or GA Event values need to be documented. 

### Who needs to review? Remove rows that aren't needed for this work.   
- [ ] CAIA (or content and a11y SME)
- [ ] Shared support, e.g., Angela Fowler (a11y) and Sara Sterkenburg (IA)
- [ ] Platform design (e.g., office hours or post in #platform-design-system)
- [ ] Other health app teams for cross-platform consistencies. E.g., Appointments, Mobile App, Kristen McConnell, etc. 
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)
     
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] Give Lori the specific wireframe links in the Design page in the pre-check-in file

**Comment by loripusey** [comment]
@benbrasso-agile6 Do we need this ticket?

**Comment by benbrasso-agile6** [comment]
Yes. Did I see you asked Zach to pick this ticket up? Maybe it's a duplicate. These tasks are more updated based on what we need vs the other ticket, if it was in fact a duplicate.

**Comment by loripusey** [comment]
Not a duplicate; however, there is a similar ticket in the Appts team's epic, so I don't know what the difference is.
https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/84542

**Comment by loripusey** [comment]
@benbrasso-agile6 at some point we need to move these UX tickets out of our board and into the UX board.

**Comment by benbrasso-agile6** [comment]
> @benbrasso-agile6 at some point we need to move these UX tickets out of our board and into the UX board.

Np, I'll talk to @outerpress and @anita-halici about getting that set up

**Comment by benbrasso-agile6** [comment]
> Not a duplicate; however, there is a similar ticket in the Appts team's epic, so I don't know what the difference is.
https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/84542

Sounds good. Yeah, I just saw you asked Zach to point the ticket; not start it. But, yes, we still need this ticket.

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-FE-UX-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/82909?planning-poker) with Zenhub @zach-park

**Comment by benbrasso-agile6** [comment]
FYI, I believe this is going through Design Intent right now

**Comment by loripusey** [comment]
Design Intent is Friday 6/14. I am the only one from our team that was invited and was going to suggest Zach attend but he is out for the rest of the week. In lieu of that, I invited @brianseek to attend because it conflicts with a Dr. appt that I have and I likely won't be there. If @benbrasso-agile6 or @cgednalske need to be there I can add you.

**Comment by benbrasso-agile6** [comment]
Sounds good. I'm familiar with the design work. It will be a low lift for design + engineering. Well, minus whatever the plan is for where the content is living. I haven't been part of those recent conversations.

**Comment by benbrasso-agile6** [comment]
@zach-park how's this ticket coming along?

**Comment by zach-park** [comment]
@benbrasso-agile6 , check-in portion is ready for validation (Apologies for the slow progress...):
In-person and CVT: 
https://www.figma.com/design/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-PCI?node-id=0-1&t=dqWiDXxVwvzuNxDu-1

**Comment by benbrasso-agile6** [comment]
@zach-park https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32909&t=3fN9AjrmHfTdzE1k-4

https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI?node-id=13-32909#892176887

**Comment by zach-park** [comment]
@cgednalske @benbrasso-agile6 , ready for validation:
https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=276-22919&t=4ds0uLmL5OAL63e6-1

**Comment by benbrasso-agile6** [comment]
I think this is good, here was myessage to @loripusey that I left on the wrong ticket

Validated - https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=276-22919&t=2x2nLc7aAiWiHRNp-4

@loripusey, I think the engineers have the previous link from Peter's work - https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32909&t=Mz6JMmlPKGMDfmSH-4

But, if you want to edit the wireframes link in FE ticket to Zach's file, that would be good - https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=276-22919&t=2x2nLc7aAiWiHRNp-4
