### ISSUE TITLE
Copy edit live 'Eligibility for VA health care' page in Spanish

### ISSUE THREAD

**Issue by moviedosoco** [department-of-veterans-affairs/va.gov-team#82903]
## Issue description
Tracking questions and corrections for page. The next step will be to make changes in Drupal and publish.

---
## Tasks
- [x] Review and track errors (Victoria)
- [x] Review (Randi)
- [x] Batch questions and changes and share with State Dept for review
- [x] Update page in Drupal (Sara T)
- [x] Copyedit (Sara T.)
- [x] Publish (Sara T.)

## Acceptance Criteria
- [x] Updated content is live on the site

## Configure this issue
- [ ]   #80097

**Comment by moviedosoco** [comment]
All right. Thank you @RLHecht.

**Comment by saratorres2** [comment]
Updates published, along with additional content added in [ticket #83196](url) [](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/15?pane=issue&itemId=63055054)

**Comment by saratorres2** [comment]
Closing ticket.

**Comment by moviedosoco** [comment]
@saratorres2 I replaced the word 'Iraq' with 'Irak' in Drupal to follow State's recommendation. Please review and publish. Thank you!

**Comment by moviedosoco** [comment]
This ticket is completed and good to close.
