### ISSUE TITLE
Finish remaining GA4 Views in BigQuery - Group 3

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#82935]
### Description
This ticket is to account for finishing the remaining GA4 views within BigQuery. This ticket should ensure we have GA4 Views for ALL of our views that are referenced within Domo.

### Tasks
Each of the GA4 Views has been created:
- [x] vw_myva_user_comparisons
- [ ] ~vw_profile_api_requests~ **No Domo dataset associated with the BigQuery VIEW**
- [x] vw_profile_detail
- [ ] ~vw_profile_hits_detail~ **No Domo dataset associated with the BigQuery VIEW**
- [ ] ~vw_profile_search~ **No Domo dataset associated with the BigQuery VIEW**
- [x] vw_search
- [x] vw_vanotify
- [x] vw_vanotify_landing_pages

--- 

### Acceptance Criteria

- [x] All GA4 Views have been created in Google BigQuery
- [x] Card has been commented on with links to each of the GA4 views in Google BigQuery.
- [x] Names of new GA4 Views have been documented on this ticket.

**Comment by johnny-jesensky-adhoc** [comment]
GA4 Views created in BigQuery -- linking below.

- [vw_GA4_myva_users_comparisons_last_week](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_myva_users_comparisons_last_week)
- [vw_GA4_profile_detail_last_week
](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_profile_detail_last_week)
- [vw_GA4_search](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_search)
- [vw_GA4_vanotify_last_week
](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_vanotify_last_week)
- [vw_GA4_vanotify_landing_pages_last_week
](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_sites!3svw_GA4_vanotify_landing_pages_last_week)

Moving this to _**Done**_.

FYI @dorseypa1
