### ISSUE TITLE
[CST][ENG] Accessible labels for icons used 8 phase claim overview page

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#82952]
## Value Statement
**_As a_** Veteran using assistive technology to review my claims online
**_I want to_** received accessible feedback when icons are used to communicate important status
**_So that_** I can be abreast on my claim status.

---
## Background Context
In the overview page for disability claims (presently), we use icons and a diagram to communicate claim status to Veterans. We want to add accessible labels to each icon with meaning so that Veterans using assistive technology doesn't missout on those updates. 

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- [Epic Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82360)

## Design
The claims process diagram,  accordion-header check marks and accordion-header flag needs accessible labels.  The repeat icon is decorative because we have plaintext and the messaging isn't dynamic.

<img width="960" alt="Screenshot 2024-05-13 at 12 32 34 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/aad8a94f-2d14-41fb-ab36-5977bd3a296d">

For in context annotations, [check out the Figma file for details](https://www.figma.com/design/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?node-id=1739-3132&t=hssFFnEFnXxfLvsA-0).

Annotations include:

**Label for the process image SVG**:** "Your current step is [number] of 8 in the claims process. Steps 3 through 6 can be repeated."

[number] changes depending on the current step.

The markup should be:

```html
<svg role="img" ...>
  <title>Your current step is [number] of 8 in the claims process. Steps 3 through 6 can be repeated.</title>
  [design code]
</svg>
```

**Label for green checkmarks**: "Completed"

```html
<svg role="img" ...>
  <title>Completed</title>
  [design code]
</svg>
```

**Label for flag with circle**: "Current"

```html
<svg role="img" ...>
  <title>Current</title>
  [design code]
</svg>
```

**Label for arrows forming circle**: N/A - This is a decorative image. See markup for more.

```html
<svg aria-hidden="true">
  [design code]
</svg>
```

### Enablement team (if needed)
@member of team

## Engineering Tasks

- [x] - Add a title to the svg aka step diagram - "Your current step is [number] of 8 in the claims process. Steps 3 through 6 can be repeated."
- [x] - Add a title to the green checkmarks: "Completed" - use the srtext thats on the [va-icon ](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default)
- [x] - Add a title to the  flag with circle**: "Current"  - use the srtext thats on the [va-icon ](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--default)

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Step diagram has accessibility text that is dynamic based on the step you are currently on
- [ ] Steps with the green checkmark icons has srtext of "Completed"
- [ ] A Step with the flag icon has srtext of "Current" 
- [ ]  Behind cst_claim_phases feature flag
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by pmclaren19** [comment]
@davidakennedy this is now in Staging! Please validate and let me know if you have any questions!
