### ISSUE TITLE
Generalize schema property names

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#8296]
## Description
In order to accommodate existing pre-fill code, we need to generalize some of our schema property names, which will also make them more reusable. 

For example, renaming `countryName` to `country` allows Lihan to use what he already has, instead of writing some new code to mutate the name `countryName` into `country`

## Considerations
- This should be completed before #8056
- _list to be attached_
- Unit tests in vets-json-schema need to be updated. 

## Tasks
- [ ] update all property names
- [ ] update all unit tests in `vets-json-schema`

## Acceptance Criteria
- [ ] The schema property names are updated to be more generalized and a PR has been merged

**Comment by lihanli** [comment]
hey after looking at the code i don't think there is any renaming needed for the address because the fields are too different and i wouldn't be able to reuse the existing code even if the fields were renamed (`country` is supposed to be the iso3 code while `countryName` is the full name, `postalCode` has been split into `zipCode` and `internationalPostalCode`, etc). thanks for the help.

**Comment by micahchiang** [comment]
Thanks @lihanli. I'm reopening this ticket because I still have to do some property renaming for some of the other fields we're using.
