### ISSUE TITLE
Determine where we can use info we already know about the Veteran to eliminate irrelevant toxic exposure questions

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#82970]
## Issue Description
Health Enrollment team's research ([Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md#research-findings-for-10-10ez-toxic-exposure-questions-usability-study) / [PDF slide deck](https://dsva.slack.com/archives/C0NGDDXME/p1715622985565069?thread_ts=1715605202.876099&cid=C0NGDDXME)) found, among other things, that "Veterans would like to see more customization in the toxic exposure questions based on what VA already knows about them or what they answered previously".

Key quotes:

> 

    P6: "I don’t know when Agent Orange stopped being used but I feel like this question could be eliminated based on some of the previous ones."

    P5: "If I clicked Southwest Asia in Gulf War during that timeframe, Spain and Greenland would have nothing to do with the Southwest Asia [response]. These cleanup response efforts would not coincide with what I clicked."

    P4: "For example, if I tell you that I've only been in Montana my entire career, then you could pretty much stop asking questions after that because it would be very unlikely that I was exposed to any of this stuff."

---
## Tasks
- [ ] Check back with Health Enrollment team about whether / how they've been able to use existing knowledge to eliminate irrelevant questions
- [ ] Check with product and engineering about whether we want to pursue this path
- [ ] Check with OCTO about whether we want to pursue this path
- [ ] Bring to VBA and determine what questions we can eliminate, in which cases
- [ ] Design updates to screens
- [ ] Create implementation tickets and flag them to product and engineering
- [ ] Update contact center as appropriate, to be aware of changes (note the timeline for them to go into production)

## Acceptance Criteria
- [ ] Designs updated with agreed-upon logic
- [ ] Team able to begin implementation of the updates
