### ISSUE TITLE
[FE] - Details check-in button skips flow

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#82974]
## Summary
In our current new landing page (unified) code, the check-in button on the appointment details page skips all questions pages and jumps right to complete. This ticket is to updated that button to function just like the one on the appointments page does.

## Tasks
- [ ] [FE] Update details check-in button function
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/82974?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
@loripusey / @benbrasso-agile6 / @zach-park This is ready to validate, it updates the button on details to use actionlink and fixes a broken flow when clicked from the details page
<img width="215" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGp3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a78476cccd3681e98dc7cc362f6578bcc6460263/localhost_3001_health-care_appointment-pre-check-in__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%282%29.png" alt="localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (2).png" />
<img width="227" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG53QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7b20c3c1e676e431a6f7f58a8d94acfa8d7792b/localhost_3001_health-care_appointment-check-in_appointment-details_0001-0001%20%282%29.png" alt="localhost_3001_health-care_appointment-check-in_appointment-details_0001-0001 (2).png" />

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by zach-park** [comment]
LGTM too. Thank you!

**Comment by brianseek** [comment]
Thanks UX friends!
