### ISSUE TITLE
DR | Fix incorrect timezone submission

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#82982]
## Value Statement
**_As a_**  developer that uses Lighthouse's APIs
**_I want to_** make sure we're not passing a timezone of `Etc/Unknown`
**_So that_** Lighthouse doesn't reject the submission

## Background Context

We received a [422 unprocessable entity alert from DataDog](https://dsva.slack.com/archives/C05UPRR0HK3/p1715559455045739) for our Higher-Level Review form. After investigation, we determined that the Veteran's submission set a timezone of `Etc/Unknown`. On the frontend we use the following code to determine the timezone

```js
Intl.DateTimeFormat().resolvedOptions().timeZone
```

But the value of `Etc/Unknown` is not a valid timezone according to the [tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

## Tasks
- [ ] Add check for `Etc/Unknown` timezone and return a valid timezone
- [ ] Update HLR, NOD & Supplemental Claim to use common timezone utility
- [ ] Add unit tests

## Acceptance Criteria
- [ ] Prevent submitting `Etc/Unknown` timezone
- [ ] All tests passing
- [ ] Veteran is able to submit their HLR

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Work has been merged in, but Veteran has not completed submission of their form - [reached out to contact center support](https://dsva.slack.com/archives/CNCEXNXK4/p1715878228949929) (via Cory) to inform the Veteran.

**Comment by eileen-coforma** [comment]
@Mottie Anything for us to review here, or are we keeping this open until Veteran resubmits. If so, should that be part of the AC?

**Comment by Mottie** [comment]
[The Veteran was able to submit their HLR](https://dsva.slack.com/archives/C05UPRR0HK3/p1716218420509709?thread_ts=1715559455.045739&cid=C05UPRR0HK3). We can't tell if the frontend change to provide a fallback timezone or if the Veteran changed the timezone on their computer. Either way, I think we can safely close this ticket.
