### ISSUE TITLE
508 finding: facility operating status skips level on detail page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8299]
**Note: The facility operating status display uses the alert component from the design system.**

## User Story or Problem Statement
As a keyboard or screen reader user, I need the webpage to have meaningful heading so that I can successfully navigate to the area I need. 

Found on scan: 
Heading for facility operating status skips level on facility detail page

![heading level skipped on detail page](https://user-images.githubusercontent.com/55411834/80034284-66f7a080-84ab-11ea-8bb6-5cc95be772ca.png)

## Goal
Equivalent experience for keyboard and screen reader users

## Objectives or Key Results this is meant to further
- Objective 3: Deliver a usable and accessible experience

---
## Tasks
- [ ] Resolve skipped heading level on Facility detail page operating status alert

## Acceptance Criteria
- [ ] The Facility detail page page does not skip levels when displaying the facility operating status. 
- [ ] All other functionality is maintained.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Submitted this to the design system 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/184

**Comment by mmiddaugh** [comment]
@ethanteague I think you asked me for URLs related to this issue... 
https://www.va.gov/find-locations/facility/vha_688GB (Facility Locator)

For VAMCs, you may need to view it on: 
http://vamcupgrade.web.demo.ci.cms.va.gov/pittsburgh-health-care/operating-status/

**Comment by ethanteague** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12445
