### ISSUE TITLE
Test postman files for Accreditation API

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#82993]
## Background
OGC has provided us with the postman files that include all of the endpoints and necessary configurations (including the API keys to hit them) to access the Accreditation API lower environments.  We would like to test these out to confirm we have everything we need.

## Tasks
- [ ] Figure out how to get the postman files transferred to local machine OR if the government machine has the necessary dev tools -- **Did ARF have any opportunity to test postman files on a local machine, and could we follow their approach?** 
- [ ] Confirm postman files are behaving as expected

## Acceptance Criteria
- [ ] Confirm we can hit the Accreditation APIs and they're functioning as expected

**Comment by oddball-lindsay** [comment]
Need to get the GFE re-imaged to access postman files within the VA network

**Comment by holdenhinkle** [comment]
Was able to email the postman json files using the encryption feature in Outlook. Successfully imported them into Postman. However, I'm getting an error when trying to hit the accreditation endpoints all the environments:

`Error: getaddrinfo ENOTFOUND url_goes_here`

I posted in Teams asking Randy about it.

**Comment by oddball-lindsay** [comment]
Currently receiving a "not authorized" when trying to hit the endpoints in CAG, with the Staging environment.  Checking with Charley for tips on functionality.

**Comment by holdenhinkle** [comment]
Alex Prokop suggested that I submit a support request with Platform - https://dsva.slack.com/archives/CBU0KDSB1/p1717091951946309

**Comment by holdenhinkle** [comment]
Kyle A. Matheny
  7 minutes ago
My guess is that you may need to put in an ESECC request 
@Holden Hinkle
 to allow us to talk with that domain over that port -- the owner of the domains should put in a request for who is allowed access to make calls to them

ESECC info - https://github.com/department-of-veterans-affairs/devops/blob/master/docs/ESECC-Public-URL-process.md

https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration

**Comment by oddball-lindsay** [comment]
Pausing these efforts, as we first need to submit an ESECC request for requests within vets-api to be able to hit this combination of subdomain + port number.

**Comment by oddball-lindsay** [comment]
Need to address https://github.com/department-of-veterans-affairs/va.gov-team/issues/88288 before we can test

**Comment by oddball-lindsay** [comment]
Yes, let's just proceed with reviewing API swagger docs. This is done!
