### ISSUE TITLE
Discovery: Update Style Guide: Embedded Video Option

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#83009]
After completing the discovery on [this ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/78724), I learned that there are two ways to embed videos into Confluence/PW. The first is through the Widget Connector macro and the second is through directly pasting the youtube url into the body text. 

The results of each are VERY different. As a team, we must decide which option we would like to advice teams to use when embedding videos in their content. 

### TASKS

- [x] Create Test Page to illustrate difference
- [x] Deploy it via Sandbox to make sure the differences in Confluence translate to the PW.
- [x] Get the team to vote on which video embedding option they like best. 
- [x] Reach a consensus. 

### Acceptance Criteria

- [x] PCT has had a through discussion of the pros and cons of video embedding options.
- [x] PCT has come to a consensus about what that policy should be going forward.

**Comment by BSmolensky** [comment]
This ticket is ready to close.

**Comment by BSmolensky** [comment]
Link to slack voting: https://thesocompany.slack.com/archives/C02LYB7QXS5/p1715781960373969
