### ISSUE TITLE
Discovery on CXI and Ask VA Data

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#83020]
## Issue Description
Conduct a discovery spike on CXI and determine how to access Ask VA data that would be relevant for the DOMO dashboard. 

---
## Tasks
- [x] Set up meeting with Ask VA data owners to learn more about finding and utilizing data
- [x] Explore CXI 
- [x] Conduct analysis of Ask VA data 

## Acceptance Criteria
- [x] Next step documentation to determine path forward for bringing Ask VA data into dashboard.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Veteran Support and CXI team met 6/10/24

Reviewed field mapping and confirmed parameters .
