### ISSUE TITLE
Update AAR V1 and V2 w/ SME feedback

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#83029]
## Description

> @aprocik1 following up with specifics of Appoint v2, we have a [summary of what needs your attention](https://dsva.slack.com/archives/C065KP8MRHA/p1715610210887419?thread_ts=1715609481.726949&cid=C065KP8MRHA) from @mtri
> 
> We also received a bit of content-related feedback in today's stakeholder design review; content updates around this could apply to our MVP as well:
> 
> - Medical authorizations: Update body copy (above the bullets) to “may need to access certain medical records” and consider ending after the “to help you.” No need to have additional copy after that.
> - What to expect next: Stakeholders emphasized avoiding confusion that the appointment will happen automatically after submitting (the rep still needs to agree).
> 
> Timing wise, re-iterating that we will need updated copy ideally by 5/27. We do have Midpoint Review scheduled for this Friday 5/17 if you'd like to try and get Governance's input by then, but currently we're not planning to request content feedback during our Midpoint Review.

## Tasks
- [x] AP: Review SME feedback and provide recommendations in Figma comments
- [x] AP: Update content sources of truth to match recommendations in Figma comments

## Criteria
- [x] Content recommendations have been provided to the product team

**Comment by aprocik1** [comment]
Here's the summary of recommendations from Michael:

Intro page – [Since a user has to be signed in to take advantage of digital submission](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=3717-80885&viewport=10710%2C-11202%2C0.5&t=Au240rmURNvtLPiR-1&scaling=min-zoom&starting-point-node-id=3717%3A80893&mode=design):
- In the intro process list: “If you’re signed in and appointing an accredited VSO representative who can digitally sign your form, you can submit it to them at the end of our online tool.”
- In the unauth sign in alert (widget): “If you’re appointing an accredited VSO representative who can digitally sign your form, you can submit it at the end of our online tool.”

Select a representative:
- ["Enter the name of the accredited representative or Veteran Service Organization you'd like to appoint" search input label](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=3717-80877&viewport=10710%2C-11202%2C0.5&t=Au240rmURNvtLPiR-1&scaling=min-zoom&starting-point-node-id=3717%3A80893&mode=design)

[Appointing a rep that has already been appointed](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=4521-226012&viewport=10710%2C-11202%2C0.5&t=Au240rmURNvtLPiR-1&scaling=min-zoom&starting-point-node-id=3717%3A80893&mode=design):
- Contact alert language
- The note will only appear when appointing a VSO representative.

[Appointing a Veteran Service Organization that has already been appointed](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=4521-226012&viewport=10710%2C-11202%2C0.5&t=Au240rmURNvtLPiR-1&scaling=min-zoom&starting-point-node-id=3717%3A80893&mode=design):
- Occurs after selecting a VSO on an individual with multiple VSOs that matches the currently appointed VSO.

[Print only available alert when selecting a rep](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=4528-261760&viewport=8380%2C-17681%2C0.5&t=OIqJhH2wR1MUXNLa-1&scaling=min-zoom&starting-point-node-id=3717%3A80893&mode=design)
- Occurs when selecting an attorney or claims agent or VSO representative that only has VSOrgs that will accept print submission.

[Print only available alert when selecting a VSO](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=4878-151874&viewport=8380%2C-17681%2C0.5&t=OIqJhH2wR1MUXNLa-1&scaling=min-zoom&starting-point-node-id=3717%3A80893&mode=design)
- Occurs when selecting a Veteran service organization that only accepts print on the select a VSOrg page.

[Unauthenticated print interstitial](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=4452-370943&viewport=8380%2C-17681%2C0.5&t=OIqJhH2wR1MUXNLa-1&scaling=min-zoom&starting-point-node-id=3717%3A80893&mode=design)
- Will display for all selections on unauthenticated since digital submission is not available.
- Since the user can't sign in midflow, this probably shouldn't mention sign in even though the reason it is showing is they are not signed in.
- Occurs after selection of an attorney, claims agent, or single accredited VSO rep.
- Occurs after selection of an organization for a cross accredited VSO rep.
- This page may or may not be necessary since we have content up front and at the end of the flow about this now.

[Download a copy of your form for your records](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=4615-202534&viewport=5299%2C-13115%2C0.5&t=tGIVgntVbvdiP2J0-1&scaling=min-zoom&starting-point-node-id=3717%3A80893)
- Page functions exactly like p[rint-fill download your form page](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&type=design&node-id=4615-195277&viewport=5299%2C-13115%2C0.5&t=tGIVgntVbvdiP2J0-1&scaling=min-zoom&starting-point-node-id=3717%3A80893), but the framing of the content is a bit different.

**Comment by aprocik1** [comment]
@oddball-lindsay and @mtri, here are my recommendations:

- Intro page: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=3717-80885#802905532), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=3717-80885#802896762)
- Select a rep: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=3717-80877#802917575), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=5500-628636#802921805)
- Appoint a rep that's already appointed: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4521-226012#802926835), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4521-226012#802944989)
- Appoint a VSO that's already appointed: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=5208-261881#802950462), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4521-226012#802938259)
- Print only alert for reps: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4528-261760#803030425)
- Print only alert for VSOs: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4879-159320#803019994), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4878-151874#803007473)
- Print interstitial: I don't think this screen is necessary, since we have related content in alerts throughout the flow, as well as at the beginning and end of the flow
- Download for digital submit: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4615-202534#803047232)

After we align on these recommendations, I'll update the relevant content sources of truth.

**Comment by oddball-lindsay** [comment]
Thanks @aprocik1!  I left some replies to your comments for us to discuss.  One thought I had that applies to multiple comments is what we call "digital submission" in Veteran-facing language.  Happy to discuss that [in the Figma comment](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=3717-80885#802905532) or in this thread.
>  I'm also wondering if "digitally sign your form" is correct 🤔 the Veteran/claimant won't be signing -- just submitting.  And the receiving rep won't be signing either -- just accepting the request.
> 
> What about "digitally accept your request" instead?

Also @mtri what are your thoughts on removing the Print interstitial from the flow?  If users struggle with understanding the flow ends in a print/download in testing, then that could guide us to adding the screen back in.

**Comment by mtri** [comment]
> Also @mtri what are your thoughts on removing the Print interstitial from the flow? If users struggle with understanding the flow ends in a print/download in testing, then that could guide us to adding the screen back in.

Removing the print interstitial makes sense to me since we'll have supporting content that says you need to be signed in to take advantage of digital submission in the form.

The upcoming test currently only tests the digital submission flow, but if we want to confirm this we could ask about understanding of the intro content and having access to the feature.

**Comment by aprocik1** [comment]
@oddball-lindsay and @mtri, thanks! I reviewed your responses by comments in the Figma file. Here's where we're landing:

- Intro page: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=3717-80885#802905532), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=3717-80885#802896762)
- Select a rep: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=3717-80877#802917575), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=5500-628636#802921805)
- Appoint a rep that's already appointed: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4521-226012#802926835), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4521-226012#802944989)
- Appoint a VSO that's already appointed: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=5208-261881#802950462), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4521-226012#802938259)
- Print only alert for reps: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4528-261760#803030425)
- Print only alert for VSOs: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4879-159320#803019994), [comment 2](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4878-151874#803007473)
- Print interstitial: I don't think this screen is necessary, since we have related content in alerts throughout the flow, as well as at the beginning and end of the flow
- Download for digital submit: [Comment 1](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4615-202534#803047232)

**Comment by aprocik1** [comment]
@oddball-lindsay and @mtri, thanks for your quick review, and thanks for the clarity on the VSO / VSO rep distinction.

I just updated all my comments with a variation of this content: "Appoint a VSO that can digitally accept your form." And I updated our [final state content source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EUgSr7Fu0MlBuyDQVyv4fdYBsERsAUPlpATfw-Ev-1yFDQ?e=9IL5vM)--this includes the landing page, intro page, and confirm screens. You'll need to update those pages and screens in the Figma file.

If these updates seem good to you, I'll update our other content sources of truth to match my recommendations.

**Comment by oddball-lindsay** [comment]
These updates look good to me, thanks for the quick adapt and update!  I'll let @mtri have the final 👍 for being ready to update the content source of truth :)

**Comment by mtri** [comment]
Looks good to me! I will bring it into Figma.

I have one other small question on the relationship between the digital submission language on the Find search and Appoint VSO selection [here](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c?node-id=4879-159320#803019994)

Thanks again!

**Comment by aprocik1** [comment]
Great! I'll update our sources of truth to match my comments by the end of the week. Thanks!

**Comment by aprocik1** [comment]
Note: I updated these sources of truth with the recommendations we aligned on in Figma and this ticket:
- [AAR V1](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EZEW15_B_ZlMnxSTps9Tt8cBci2c-iWZTidg0IM4Pk2jMw?e=kyPqpb)
- [AAR V2](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EUgSr7Fu0MlBuyDQVyv4fdYBsERsAUPlpATfw-Ev-1yFDQ?e=oXuaHM) (final state source of truth)

**Comment by oddball-lindsay** [comment]
@aprocik1 my apologies for only realizing this now, but in our designs Appoint v1 is intended to be without digital submission and Appoint v2 is with that digital submission feature enhancement.  

The [AAR V1](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EZEW15_B_ZlMnxSTps9Tt8cBci2c-iWZTidg0IM4Pk2jMw?e=kyPqpb) isn't quite accurate for "v1" as the Step 2 content has mentions of digital submission.

I don't think it's an urgent need as designs are actively pursuing v2 so we can still use this document for reference, but at some point for recording our evolution (and aligning with design files) it'd be helpful to have two distinct documents -- v1 _without_ mentions of digital submission in Step 2, and v2 _with_ those mentions in the doc today.

**Comment by aprocik1** [comment]
@oddball-lindsay, thanks for flagging this. I just cleaned up our content source of truth folder and all the documents within it. Let me know if you find any other inconsistencies.

https://dvagov.sharepoint.com/:f:/s/SitewideCAIA/EpKqFTllvlxOkDwz2iFgveAB9PjkKVIrJu_TUAkQPbsU0g?e=8SLJwh

**Comment by oddball-lindsay** [comment]
Thank you @aprocik1!  🙏
