### ISSUE TITLE
Access to SOCKS for Lighthouse employees

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#83023]
### Summary
Currently, users that need SOCKS access have to go through the Platform Orientation. Lighthouse Engineers and engineers from other services should not have to go through Platform Orientation. 

We need to ensure that the SOCKS access template has an option for a Lighthouse resource.

There may be some training updates that need to be shared with the DevOps CoP and the Support team. 

## Slack Thread
- [Access to SOCKS for Lighthouse Engineers](https://dsva.slack.com/archives/CBU0KDSB1/p1715030438257559)

## Tasks
 - [x] Find out if there is a Lighthouse roster that can be checked.
 - [x] Review and modify [SOCKS access issue template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&projects=&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D)
 - [x] Update `.github/workflows/pst-amt-roster-check.yml` (devops repo)
 - [x] Updated Platform Website [documentation](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-PrerequisitesPrerequisitesforSOCKSProxyconfiguration)
 - [x] Update this [internal documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#SOCKS-Access-Request-(adding-SSH-public-keys))
 - [x] Share changes with the DevOps CoP and the Support team–they're the ones that process the access requests.

## Acceptance Criteria
 - [x] There is a path forward for LH SOCKS access 
 - [x] Platform Website [documentation](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-PrerequisitesPrerequisitesforSOCKSProxyconfiguration) is published with the updates.
 - [x] Relevant parties notified of changes

## Validation
- create new [SOCKS access ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&projects=&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D) with the following:
    - remove the three default labels so the infra alerts channel doesn't get spammed
    - Fill out the fields with an _invalid_ name, email, gh handle (i.e. of someone who is not on either the Platform Roster or in Atlas)
    - Put in a _valid_ public ssh key (you can use the one used in https://github.com/department-of-veterans-affairs/va.gov-team/issues/90982)
    - check the box saying you're on a Lighthouse team
    - All other fields can be filled out however you want (they don't matter for testing)
- Once the issue is created, after a couple minutes, you should see the `Lighthouse` label added and a comment posted ("I see you checked the box saying you are on a Lighthouse Team...").
- Change the name, email AND github handle to someone active in [Atlas](https://www.va.gov/atlas/product_directory/team_members?filter_by=first_name&filter_type=includes&filter=&commit=Filter).
- After a minute, a comment should be posted about how they were found in Atlas
- And then a minute later, a SOCKS PR to the devops repo will be linked in the SOCKS request. 
- If all that happens: SUCCESS!
- ⚠️ Close the SOCKS PR.

**Comment by jhouse-solvd** [comment]
@jennb33 @RachalCassity - You might consider updating [this](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-PrerequisitesPrerequisitesforSOCKSProxyconfiguration) and related documentation as part of the AC. 

If I can provide any useful info/background/etc as you're working through this, please don't hesitate to reach out. Once you've got a new template working, I'll be happy to help amplify messaging and share with folks on the Lighthouse side so they know how to request SOCKS moving forward.

**Comment by jennb33** [comment]
@shiragoodman and @alyssagallion heads-up that we will be reaching out to coordinate this work, as it might involve some process changes.

**Comment by shiragoodman** [comment]
@jennb33 you are I are on the same page. We have an[ initiative ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85562)planned for later this year to remove the "onboarding" tasks from Platform Orientation. Would love to talk with you soon as I think there's some small incremental changes your team could make that we could pivot on later.

**Comment by rmtolmach** [comment]
**My recommendation: Unless there's a Lighthouse roster we can check (see # 1 below), we can implement the quick fix (# 2) while # 3 is in the works. # 3 might ultimately solve the problem, but I we shouldn't wait on it. See deets below.**

After reading this ticket and the Slack thread, I had a few thoughts:
1. Is there a different roster we can check instead of Atlas? A Lighthouse roster? @jhouse-solvd - do you know?
2. As a quick fix, we could add a checkbox to the [SOCKS template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&projects=&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D) asking if they're Lighthouse. If the Lighthouse box is checked, Tier 1 or 2 Support can add them to Atlas (maybe after checking to make sure they're in Slack? or a member of the va.gov-team repo?)
3. In the initiative Shira linked above, it sounds like there are some changes coming to the [New VFS Team Member Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D). This template is 1) how a person is added to Atlas and 2) confusing/not exactly appropriate for a Lighthouse eng to be filling out. So it's possible that the changes to the template make it so it's more appropriate for LH to filling it out?

**Comment by rmtolmach** [comment]
> ❌ The attached ssh key failed to validate

That action runs if it sees "SOCKS access" in [the title](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/pst-amt-sock-kickoff.yml#L27) 😄 So I changed the title.

**Comment by rmtolmach** [comment]
I have a proposed commit that would fulfill # 2 from above: https://github.com/department-of-veterans-affairs/va.gov-team/commit/382ad06abf4628cbeecc0b41062d032c1d375288. But I'm meeting with Jesse House tomorrow morning. Jesse is on LH + used to be the Platform infra manager, so I'm sure between the two of us, we can figure out the best path forward!

**Comment by rmtolmach** [comment]
I have a couple PRs up for this work:
- https://github.com/department-of-veterans-affairs/va.gov-team/pull/90881
- https://github.com/department-of-veterans-affairs/devops/pull/14627

Monday I will work on testing them. I will probably need to merge the template change before I can test the workflow

**Comment by rmtolmach** [comment]
✅ I updated the [internal documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools).

**Comment by rmtolmach** [comment]
✅ Platform website updates. [See diff here](https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=1821081710&selectedPageVersions=57&selectedPageVersions=58).

I tested and modified the devops PR until it was working as desired. It's been reviewed by Chris, and Lindsey will review it on Wednesday. 

I will share updates with the devops CoP on Thursday.

**Comment by rmtolmach** [comment]
I shared changes with the devops CoP today. @flooose ran through the validation steps. closing!
