### ISSUE TITLE
Discovery: Veteran experience for event page on VAMC 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8302]
## Problem Statement
What is the best experience for Veterans related to the display of facility events?
- Current events are displayed at the healthcare system level

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/d7dafdaa-f9bf-4a03-9d80-b388967807c0)

## Objectives or Key Results this is meant to further
- Objective 2: Deliver meaningful facility information 

---
## Tasks
Determine best user experience for VAMC events, including the following
- [ ] What to display when there are no upcoming events at facility level

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@jilladams to consider bringing over to new repo
