### ISSUE TITLE
Handle multiple exposure durations - test through BE -15C

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#83034]
## Issue Description
As a Veteran I want to submit a disability compensation claim inclusive of any dates and locations of potential exposure so that I can ensure any TE conditions I have that resulted from multiple exposures are considered during review of my application.

Reference: [contract](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md)
---
## Tasks
- [ ] Method to transform Herbicide Hazard details object into Lighthouse Toxic Exposure multiple exposures array
- [ ] `herbicideDetails`
- [ ] `otherHerbicideLocations` and its dates

## Acceptance Criteria
- [ ] Lighthouse generated PDF populates 15E with 15C's data
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Local testing against LH PDF generation successful (see screenshot below). Draft PR [created](https://github.com/department-of-veterans-affairs/vets-api/pull/16941).

<img width="776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3683565d15846254caf1c564b24e0ac287916d47/image.png" alt="image.png" />

**Comment by sethdarragile6** [comment]
Successful stage test
<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG93QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e51c8d033cea603af3a23e3dd8e946f2034eede4/image.png" alt="image.png" />
