### ISSUE TITLE
Copy of Handle multiple exposure durations - test through BE

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#83035]
## Issue Description
As a Veteran I want to submit a disability compensation claim inclusive of any dates and locations of potential exposure so that I can ensure any TE conditions I have that resulted from multiple exposures are considered during review of my application.

Reference: [contract](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f2a20b188cd637f53768df1e75683364ab0316ed/products/disability/526ez/implementation/toxic_exposure_fe_to_be_contract.md)
---
## Tasks
- [ ] Method to transform Gulf War Hazard details object into Lighthouse Toxic Exposure multiple exposures array
- [ ] GulfWar1990, GulfWar1990Details
- [ ] GulfWar2001, GulfWar2001Details

## Acceptance Criteria
- [ ] Lighthouse generated PDF populates 15E
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
