### ISSUE TITLE
Handle multiple exposure durations - test through BE -15D

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#83046]
## Issue Description
As a Veteran I want to submit a disability compensation claim inclusive of any dates and locations of potential exposure so that I can ensure any TE conditions I have that resulted from multiple exposures are considered during review of my application.

---
## Tasks
- [ ] Method to transform Other Exposure Hazard details object into Lighthouse Toxic Exposure multiple exposures array
- [ ] `otherExposureDetails`
- [ ] `specifyOtherExposures` and its dates

## Acceptance Criteria
- [ ] Lighthouse generated PDF populates 15E with Other Exposure details
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Successful local test against LH

<img width="753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac4169c5e845e8c67bcbd1e5c36ff4317baf6b12/image.png" alt="image.png" />

**Comment by alatempa24** [comment]
[Bug logged with Lighthouse in this thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1718150280961289)

**Comment by sethdarragile6** [comment]
Example from Staging
[526ez Jesse Grey - 15D dates.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0f5f5659c18bfddb79da226b9d2585206ad9802/526ez%20Jesse%20Grey%20-%2015D%20dates.pdf)
