### ISSUE TITLE
Toxic Exposure - Data Transformation #3 -Herbicide

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#83054]
## Issue Description
The scope of this ticket is to transform the vets-website data structure into Lighthouse structure - 

As a Veteran I want to submit a disability compensation claim inclusive of any time I spent exposed to herbicides so that I can ensure any TE conditions I have that resulted from my time in these locations is considered during review of my application.

The outcome of this work is that the completed 526 will include any data the Veteran entered regarding Herbicides (section 15c in the paper version).

---
## Tasks
- [x] Add herbicides object attribute to Requests::Form526 DTO class
- [x] Update Form526ToLighthouseTransform to transform herbicides service
- [x] Update Form 526 to LH transform
- [x] Update Unit test to check for herbicides for diff scenarios

## Acceptance Criteria
- [x] Form526ToLighthouseTransform has the herbicides object
- [x] If Veteran selects "None of these options", set NO
- [x] If Veteran selects "I'm not sure", remove from transmitted data
- [x] If Veteran selects at least one herbicides location, set herbicides to YES.
- [x] If Veteran selects "other locations" text field, set herbicides to YES, ~~and send data to 15E.~~ (to be done on subsequent ticket)
- [x] If Veteran does not select any locations, send Null
- [x] Do not populate herbicides dates - confirm with the VBA check in notes that no date is being populated in 15 B, C and D
- [x] Changes to JSON schema are documented

Out of scope but need to look into:
- Regex for "other locations" text field & validation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michael-wojcik** [comment]
Yesterday, I paired with @aurora-a-k-a-lightning and @sethdarragile6 to make sure my backend development environment is up and running locally in order to be able to pair on this ticket and subsequent related back-end tickets for the TE work.
