### ISSUE TITLE
Toxic Exposure - Data Transformation #3 -Hazards

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#83059]
## Issue Description
The scope of this ticket is to transform the vets-website data structure into Lighthouse structure -

As a Veteran I want to submit a disability compensation claim inclusive of any time I spent exposed to herbicides so that I can ensure any TE conditions I have that resulted from my time in these locations is considered during review of my application.

The outcome of this work is that the completed 526 will include any data the Veteran entered regarding Hazards (section 15d in the paper version).

---
## Tasks
- [ ] Add hazards object attribute to Requests::Form526 DTO class
- [ ] Update Form526ToLighthouseTransform to transform hazards service
- [ ] Update Form 526 to LH transform
- [ ] Update Unit test to check for hazards for diff scenarios

## Acceptance Criteria
- [ ] Form526ToLighthouseTransform has the hazards object
- [ ] If Veteran selects "None of these options", set NO
- [ ] If veteran selects at least one gulf war location, set hazards to YES.
- [ ] If veteran does not select any locations, send Null
- [ ] Do not populate hazards dates - confirm with the VBA check in notes that no date is being populated in 15 B, C and D
- [ ] Changes to JSON schema are documented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
