### ISSUE TITLE
Resolve CI Log Warning for expect not_to raise specific error

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#83058]
## Summary

There's a warning in the CI code checks log for expect not_to raise specific error. It's generally a bad practice to test if a specific error is not raise. 

```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass, message)` risks false positives, since literally 
any other error would cause the expectation to pass, including those raised by Ruby (e.g. `NoMethodError`, 
`NameError` and `ArgumentError`), meaning the code you are intending to test may not even get reached. 

Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. 
This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. 
Called from /app/modules/va_forms/spec/sidekiq/form_builder_spec.rb:110:in `block (4 levels) in <top (required)>'.
```
## Tasks
- [x] resolve these warnings for the below tests

## Acceptance Criteria 

- [x]  No warning for `modules/mobile/spec/sidekiq/legacy_pre_cache_claims_and_appeals_job_spec.rb`
- [x]  No warning for `modules/mobile/spec/sidekiq/pre_cache_claims_and_appeals_job_spec.rb`
- [x]  No warning for `modules/va_forms/spec/sidekiq/form_builder_spec.rb`
