### ISSUE TITLE
Toxic Exposure - Data Transformation #3 -Hazards

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#83061]
## Issue Description
The scope of this ticket is to transform the vets-website data structure into Lighthouse structure -

As a Veteran I want to submit a disability compensation claim inclusive of any time I spent exposed to hazards so that I can ensure any TE conditions I have that resulted from my time in these locations is considered during review of my application.

The outcome of this work is that the completed 526 will include any data the Veteran entered regarding Hazards (section 15d in the paper version).

---
## Tasks
- [ ] Add hazards object attribute to Requests::Form526 DTO class
- [ ] Update Form526ToLighthouseTransform to transform hazards service
- [ ] Update Form 526 to LH transform
- [ ] Update Unit test to check for hazards for diff scenarios

## Acceptance Criteria
- [ ] Form526ToLighthouseTransform has the hazards object
- [ ] If Veteran selects "None of these options", set NO
- [ ] If veteran selects at least one hazard, set hazards to YES.
- [ ] If other hazards field is populated, set hazards to YES
- [ ] If Veteran does not select any locations, send Null
- [ ] Do not populate hazards dates - no date is being populated in 15d
- [ ] Changes to JSON schema are documented

Open question: Confirm with OCTO if we are checking the checkboxes for 15d.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aurora-a-k-a-lightning** [comment]
found an issue with the Lighthouse submit endpoint where sending `null` value for `toxicExposure.additionalHazardExposures.exposureDates` is causing a 500 internal server error to be returned from the endpoint.
same workaround can be used as herbicide for now: 
send an empty object `{}` instead of `null` for this attribute

**Comment by sethdarragile6** [comment]
local test against LH successful! As we are doing with the herbicide questions, we'll be sending the "other" description with its dates (and other hazard option dates) to the overflow in the next story

<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--294ce8b382d1cba095c5febac9ba08d82f3c17e6/image.png" alt="image.png" />

**Comment by sethdarragile6** [comment]
successfully stage tested
[526ez Jesse Grey - 15D.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67f46bdf2117c48ff8841750dadf6bf15873fc3e/526ez%20Jesse%20Grey%20-%2015D.pdf)

<img width="1144" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a77987699f81998115de9cb7b009c6124126ca0c/image.png" alt="image.png" />
[526ez Jesse Grey - 15D.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c533243be90b8e261eb5d647e5bfa7ac885f233b/526ez%20Jesse%20Grey%20-%2015D.pdf)
