### ISSUE TITLE
[spike] DR | Initialize & use DataDog RUM on pages outside our forms 

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#83078]
## Value Statement
**_As a_** Benefits Decision Reviews team member
**_We want to_** see DataDog Real User Monitoring on pages outside our forms
**_So that_** analyze and determine the flow leading into and out of our form

## Background Context

Currently, our DataDog Real User Monitoring is initialized _after_ the user starts the form. You won't see pages external to the form, which includes the introduction and confirmation pages.

We would also want to include this list of static pages directly related to our decision review forms:

### Benefit hub detail pages:
- https://www.va.gov/decision-reviews/
- https://www.va.gov/decision-reviews/supplemental-claim/
- https://www.va.gov/decision-reviews/higher-level-review/
- https://www.va.gov/decision-reviews/board-appeal/
- https://www.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing/
- https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/
- https://www.va.gov/decision-reviews/after-you-request-review/
- https://www.va.gov/decision-reviews/contested-claims/
- https://www.va.gov/decision-reviews/insurance-claims/
- https://www.va.gov/decision-reviews/fiduciary-claims/
- https://www.va.gov/decision-reviews/legacy-appeals/
- https://www.va.gov/decision-reviews/legacy-appeals/priority-review/
- https://www.va.gov/decision-reviews/get-help-with-review-request/
- https://www.va.gov/decision-reviews/clinical-appeals/
- https://www.va.gov/decision-reviews/family-caregiver-program-reviews/

### R&S pages in the decision reviews category:
- https://www.va.gov/resources/choosing-a-decision-review-option/
- https://www.va.gov/resources/decision-reviews-faqs/
- https://www.va.gov/resources/hearing-coordinators-for-the-board-of-veterans-appeals/
- https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/
- https://www.va.gov/resources/requesting-a-virtual-hearing-for-a-board-appeal/
- https://www.va.gov/resources/vas-duty-to-assist/
- https://www.va.gov/resources/what-your-decision-review-or-appeal-status-means/

Also note this [Slack discussion with Steve Albers](https://dsva.slack.com/archives/C05SGJEAJ65/p1715622003711909)

## Tasks
- [ ] Investigate how to add and initialize DataDog RUM sessions on the aforementioned static pages
- [ ] Determine the approximate number of page visits, so we can determine a cost estimate of these RUM sessions

## Acceptance Criteria
- [ ] A clear path to adding DataDog RUM sessions to static pages has been determined
- [ ] Create a development ticket for the work

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Current progress:

I've collected a list of entity IDs and current template for each listed path:


| EntityId | Template | Path |
|---|---|---|
| 3071  | [landing_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/landing_page.drupal.liquid) | decision-reviews |
| 3011  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/supplemental-claim |
| 3003  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/higher-level-review |
| 3029  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/board-appeal |
| 3010  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/board-appeal/veterans-law-judge-hearing |
| 3013  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/board-appeal/after-board-appeal-decision |
| 3008  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/after-you-request-review |
| 3030  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/contested-claims |
| 3025  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/insurance-claims |
| 3016  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/fiduciary-claims |
| 3102  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/legacy-appeals |
| 3103  | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/legacy-appeals/priority-review |
| 57215 | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/clinical-appeals |
| 57308 | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | decision-reviews/family-caregiver-program-reviews |
| 62667 | [page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page.drupal.liquid) | get-help-with-review-request |
| 23290 | [support_resources_detail_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_resources_detail_page.drupal.liquid) | resources/choosing-a-decision-review-option |
| 50010 | [support_resources_detail_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_resources_detail_page.drupal.liquid) | resources/decision-reviews-faqs |
| 64063 | [support_resources_detail_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_resources_detail_page.drupal.liquid) | resources/hearing-coordinators-for-the-board-of-veterans-appeals |
| 8520 | [step_by_step.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/step_by_step.drupal.liquid) | resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online |
| 53778 | [support_resources_detail_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_resources_detail_page.drupal.liquid) | resources/requesting-a-virtual-hearing-for-a-board-appeal |
| 49994 | [support_resources_detail_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_resources_detail_page.drupal.liquid) | resources/vas-duty-to-assist |
| 9626 | [support_resources_detail_page.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_resources_detail_page.drupal.liquid) | resources/what-your-decision-review-or-appeal-status-means |

From my current understanding:
- For each of the above unique templates, we need to build a new template that can `include` the original.
- At the bottom of each new template, add a script tag that [loads in and initializes DataDog](https://docs.datadoghq.com/real_user_monitoring/browser/#cdn-sync).
- We'll need Steve Albers to provide the cleint token and application ID for these pages
- Once these pages are built, we'll need to get access to CMS, or have someone from CMS to go to each page (path or entityID?) and update the template.

Open questions:
- I don't know how DataDog will behave if it is initialized & possible re-initialized on each of these pages separately.
- How do we use a feature flag for this work, if needed?

**Comment by Mottie** [comment]
After chatting with @dsasser this is our plan of action:
- I will get @saderagsdale to contact the Fran Cross to get this work added to that team's sprint work.
- I will get the DataDog initialization code from Steve Albers, with sample rate percentages
- I will then open a PR in the `content-build` repo to:
  - Create an `includes` file with the DataDog initialization code, and
  - Update these 4 liquid templates to include a conditional block which "includes" the DataDog file: `page.drupal.liquid`, `landing_page.drupal.liquid`, `step_by_step.drupal.liquid`, and `support_resources_detail_page.drupal.liquid`
- Once that PR is open, let the `#sitewide-public-websites` team know. And when they have time, they will start their CMS work to add a flag to each template.
- Some additional work will get done to add a CMS-side feature toggle (not related to `vets-api` feature toggles)
- After that, someone from CMS will update each entity ID page to use this flag
- And I will likely need to update the `content-build` PR to match the flag & feature toggle

**Comment by Mottie** [comment]
This work is blocked until we can do the following - after speaking with Steve Albers on Friday, we need to:
- Collect the page view analytics and share them with him on the page with the most traffic. A ballpark number would be sufficient. This will be included in his report and determine the initial RUM session rate value (percentage of sessions to be recorded) 
- Discuss masking the search input on the support resource pages. Steve mentioned that some users include searches for PII & PHI unintentionally; but we should ask the search team to make sure.

**Comment by saderagsdale** [comment]
- Steve needs an estimate of the busiest page to determine the percentage of sessions to record. He'll then write a report and give us the initialization code.

**Comment by Mottie** [comment]
@saderagsdale I updated the [previous comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83078#issuecomment-2117944739) with the analytics I found - it looks like the [decision-reviews](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.dateOption=last30days&_r.drilldown=analytics.pagePath:www.va.gov~2Fdecision-reviews~2F&_r.tabId=explorer/) page is the clear winner with about 70,700 views/month

**Comment by Mottie** [comment]
I [reached out to Steve Albers today](https://dsva.slack.com/archives/C05SGJEAJ65/p1717096984715949?thread_ts=1715622038.156719&cid=C05SGJEAJ65). He'll be in Denver at offsite next week, but will try to get work on this finished tomorrow.

**Comment by Mottie** [comment]
On hold until we determine who requested and will monitor these RUM sessions

**Comment by va-albers** [comment]
RUM code block & configuration has been set up & script was sent to @Mottie

**Comment by jilladams** [comment]
Folks on this ticket reached out to Public Websites to request a CMS feature toggle to enable this work, tracked here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18409. We think we can accommodate that in our current sprint, but will help if y'all can provide info on hard time requirements, on that ticket. I've commented over there and tagged @Mottie

**Comment by dsasser** [comment]
@Mottie the [CMS change](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18409) to add the Feature Toggle has been deployed. We can flip this on for you when you are ready to test.

**Comment by Mottie** [comment]
@dsasser Let's do it!

**Comment by jilladams** [comment]
@Mottie (cc @dsasser ) I went ahead and enabled the toggle in prod, just now. Not 100% certain if it'll be usable immediately, but certainly by tomorrow morning that will also propagate down to lower envs for testing, if that applies for you.

**Comment by Mottie** [comment]
@jilladams & @dsasser I totally forgot that I have a [PR that hasn't been merged in yet](https://github.com/department-of-veterans-affairs/content-build/pull/2093). I think it needs the toggle name updated/added? So we've prematurely enabled the toggle. Sorry!

**Comment by Mottie** [comment]
This is the [DataDog dashboard for the static pages](https://vagov.ddog-gov.com/rum/performance-monitoring?query=%40session.type%3Auser+%40application.id%3A133801ec-0b13-4a6f-9689-bd937a1ddf27&fromUser=true&tab=overview&from_ts=1722527532478&to_ts=1722613932478&live=true), but I'm not seeing any data yet 🤔

**Comment by anniebtran** [comment]
@Mottie  thought script was getting blocked but it wasn't (was using Brave browser). Will test today

**Comment by Mottie** [comment]
[DataDog monitor is now active on Decision Review static pages](https://vagov.ddog-gov.com/rum/performance-monitoring?query=%40application.id%3A133801ec-0b13-4a6f-9689-bd937a1ddf27%20%40session.type%3Auser&filters=%5B%22env%22%2C%22service%22%2C%22version%22%2C%22%40session.type%22%2C%22%40geo.country%22%2C%22%40device.type%22%2C%22%40usr.email%22%5D&fromUser=false&tab=overview&from_ts=1722436685819&to_ts=1723041485819&live=true)
