### ISSUE TITLE
Finalize Appoint v2 and Find v3 designs for user testing

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83091]
## Background
Updating our designs based on Midpoint Review feedback, and preparing for user testing.

Reference: [Design Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83389), [IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83434), [Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83546), [Content Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83586)

## Tasks
- [x] Update prototype designs based on Midpoint Review feedback -- see Figma comments (original tickets above for reference)
- [x] Connect with Research for final feedback
- [x] Final prototype updates and stress testing to prepare for user testing
- [x] Final design updates for non-prototype screens

## Acceptance Criteria
- [x] Find v3 and Appoint v2 designs have been updated based on Midpoint feedback, and are ready for user testing.

**Comment by oddball-lindsay** [comment]
Note to self, for things to discuss with Janelle when she's back next week:
1. The new Find a Rep definition -- A has adjusted based on Jonathan's feedback, but we still don't have Christa's official approval
2. The intro and confirmation pages raised concerns with OGC (Nathan) that users may not understand this will be submitted to the VSO and NOT VA.  Can we evaluate user expectations to see if this is a valid concern?
3. Awaiting Governance's input on where to put the digital submission indicator on Find a Rep -- inside or outside of the additional component?  This may guide how we indicate this in the Appoint fuzzy search.

**Comment by oddball-lindsay** [comment]
Not too concerned with the rep replacement changing from a yellow alert to a grey card -- this tested fine in the past.

**Comment by oddball-lindsay** [comment]
Open challenge: what does "Continue" button do, when selecting a representative?  As that's the main action on the page.

**Comment by oddball-lindsay** [comment]
Error state setup to solve for the "Continue" button challenge.  Small updates for remainder of designs and annotations.
