### ISSUE TITLE
Identifier status for new copay and benefit overpayment notifications

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#83103]
## Issue Description
Confirm that identifiers are being sent to VA Notify for two email notifications being sent 
1) New Benefit Overpayment 
2) New Medical Copayment

Melanie Jones from VA Notify can provide more information.
---
## Tasks
- [x] Confirm, are we sending identifiers to VA Notify for  the above two email notifications
- [x] If yes, add not to ticket and tag Denise
- [x] If not, establish tickets to implement identifies for these two notifications

## Acceptance Criteria
- [x] Confirmed status of identifiers for these two email confirmations. 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@denisecoveyduc will ping Melanie Jones for more info

**Comment by denisecoveyduc** [comment]
Hi @mjones-oddball  The debt team is looking for a bit more information on this one and I thought I'd add some context to the ticket for everyone. 

In a conversation that you and I had regarding setting up preferences for a Veteran you mentioned that the debt team needed to check to ensure that  "identifiers" are being sent to VA Notify. 

Could you provide more information about what VA Notify needs so that the debt team can ensure that info is being sent to you in preparation for the preferences setting.

**Comment by mjones-oddball** [comment]
@denisecoveyduc In order for VA Notify to look up the Veteran's contact info and notification preferences in VA Profile we need to confirm that a recipient_identifier is being sent in the notification request body for the applicable notification use cases. I believe the overpayment notification sends a BIRLSID, but I'm not sure if you all are sending us an identifier for the copay email vs sending the email address directly. 

Supported ID types are below:
- ICN
- PID (participant id)
- EDIPI
- BIRLSID (also known as file number)
- VAPROFILEID

Sample email request body:
{
    "template_id": "{{email-template-id}}",
    "recipient_identifier": {
        "id_type": "BIRLSID",
        "id_value": "123456"
    }
}

**Comment by HeatherRienks** [comment]
FYI @maxx1128 @kjsuarez @digitaldrk 

cc: @Tom-Davis

**Comment by digitaldrk** [comment]
@denisecoveyduc ,

Kevin and I went through the code. Here's what I/we can tell you.

1. We are for sure sending ICN for New Medical Copayment, [it is commented out](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/copay_notifications/new_statement_notification_job.rb#L47) (link for my own reference)
2. We can't find _anywhere_ in the code base where New Benefit Overpayment is being sent. We [see the template id in vets api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L396). Looking at the template in the VANotify on the VA network, we can see that something is firing the template.

## Follow up
We should probably find out who/what is firing off the New Benefit Overpayment template

**Comment by digitaldrk** [comment]
Added a follow up ticket for #84611
