### ISSUE TITLE
[UX] Figma Standards update - Naming, Component for current projects

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#83123]
## Issue Description
With the UX team working on different ongoing projects, it is important to keep a cohesive approach in naming convention, content management, and note usage for clarity and collaboration with other UXers, Content, and Engineers.

---
## Tasks
- [x] Left Panel: Remove all icons used for Figma migration but keep ⚠ (exclamation mark) for now.

Specific pages: 
- [ ] Update the TERA mockups
- [x] Update the NOK/EC mockups
- [x] Update the EZR v2 Contact Info mockups

What to update in the mockups:
- Rename the frame/component (diamond) title to a common name to match Content component (ex: placebirth)
- Update content component
   - Whole content container:  Min width: 300px, Max width: 600 px
   - Text containers wider- max width 460px
   - No padding on the side for content components
- Provide a Note for each view/mockup
  - Title with a common name (eg: placebirth)
  - Additional Detail: conditional + helpful info
  - Code: URL

**Comment by IMHieuVo** [comment]
I left the TERA mocks within the working file as is but updated all the TERA mocks within the Production Pages.
