### ISSUE TITLE
DR | Validate Unprocessed Evidence PDFs with Processed PDFs

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#83132]
## Background Context

This is a follow-up to #81205.

Both unprocessed and processed evidence attachments are currently being stored in S3 along with the user password in a table so we can validate the PDFTK process for errors (via a manual unlock process). Once this validation step is complete, we will drop the records from the table and remove the code related to storing unprocessed PDFs and passwords.

## Acceptance Criteria

- [x] Unprocessed files are compared and validated against PDFTK decrypted files

## Tasks

- [x] Check for encrypted files in S3 and compare the unprocessed files using the user provided password with the processed files (PDFTK decrypted)
- [x] Collect 5 samples to determine if there's one or more causes. If one, close the effort. f more, consider collecting more samples.

## Definition of Ready

- [x] Whoever picks this up has access to our S3 bucket
- [x] Sufficient quantity of unprocessed files are available in S3
- [x] Whoever picks this up has access to production console

## Definition of Done

- [x] We have validated the PDFTK process for errors 
- [x] Summary/spreadsheet of comparison between unprocessed and processed files

**Comment by shaunburdick** [comment]
Adding @kaipyroami just for future visibility

**Comment by dfong-adh** [comment]
Over the period of May 16 to June 4, 10 encrypted PDF evidence attachments were unlocked and processed by PDFTK. All of the decrypted (unlocked) PDF attachments opened with no issues. They were compared with the unprocessed (locked) PDFs and no differences were noted between the PDFs.

**Comment by dfong-adh** [comment]
Another 9 encrypted PDF evidence attachments uploaded between June 4 to June 5 were verified to not have any issues.

**Comment by dfong-adh** [comment]
Data will be collected until the end of June.

**Comment by dfong-adh** [comment]
No issues with two PDFs processed on June 18 and June 19.
