### ISSUE TITLE
[FSR] Discovery: Experimental / Dev options for testing Pt 2

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#83139]
## Description
This is a follow on to this previous ticket, but the main idea is that it would be really nice to be able to have a dev version of the FSR where we have some more wiggle room with playing outside of using a feature flag.

There's been some investigation into bypassing login for local devs, but it would be helpful to have an unauth version of the form we can use and share for testing maybe on the dev.va.gov environment instead of staging.

There are existing variables/functions we can leverage to determine what environment the application is currently being run in, so maybe we can leverage these to load a separate form schema where we can have experimental pages and versions of the form strictly for testing purposes.

Another option would be to maybe swap between entire `formConfig`s at the App level. 

## Tasks
- [ ] Test swapping between entire forms based on a feature flag. 
- [ ] Coordinate with platform to see if this functionality could be supported with updates on their side
- [ ] Create follow on tickets as necessary

## Acceptance criteria

- [ ] More testing has been conducted
- [ ] Coordination with platform to see if they can assist
- [ ] (Optional) Follow on tickets have been created

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] ~~Testing defined~~
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
