### ISSUE TITLE
Old launch configurations need to be scrubbed

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#8314]
## User Story or Problem Statement
Reaching soft limit of 300 launch configurations, a good portion of the current ones are old.

## Goal
Only necessary launch configurations remaining.
## Objectives or Key Results this is meant to further
Better housekeeping
---
## Tasks
- [ ] Remove old, unnecessary launch configurations

## Acceptance Criteria
- [ ] Only necessary launch configs remaining
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
