### ISSUE TITLE
Sprint Capacity Document Updates

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83157]
## Description 
We are looking to improve the insights into our sprint capacity using this document: [Sprint Capacity - Platform Support - 2024](https://docs.google.com/spreadsheets/d/1Rn1mtSIdS30_hvTAv6tKVJJ8aWFpdNeFHCb7Q4mZvp8/edit#gid=1192473983). 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Update Q2 2024 Tab
- [ ] Review with Jason
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Updated. Closing.
