### ISSUE TITLE
FE | Profile | General Maint| Font Awesome Retirement

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83169]
## Background
[slack thread with dates](https://dsva.slack.com/archives/C909ZG2BB/p1715705531070029)

> [!Caution]
> This is due no later than 6/19

Font awesome is being retired, we need to locate and update the couple of places in profile where we use that font. 

## Tasks

- [ ] Evaluate the Profile codebase to identify instances of the font awesome icons being used
- [ ] Make sure things like the loading button icon have been addressed.
- [ ] Use equivalent va-icon component in their place and visually verify that no layout changes or sizing issues occur
- [ ] Update any tests

## Acceptance Criteria 
- [ ] we no longer have font awesome in any profile code

**Comment by mtcA6** [comment]
@adamwhitlock1 is this just a visual validation? are there specific location in the profile we should check? 

cc: @ACParker89

**Comment by adamwhitlock1** [comment]
I put some screenshots of the icon changes in the PR that you can use to visually check this out. I'm going to spin up one more PR for this today to fix the loading icon to replace it with just text.

**Comment by adamwhitlock1** [comment]
I think we can close this, as the icons that we could remove have been pulled out. We have the other ticket to resolve the loading button issue so that one will close out the remaining work.
