### ISSUE TITLE
Understand current state of user experience of an in progress form becoming a submitted claim

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#83163]
## Issue Description
When a Veteran submits a claim, it is possible for them to re-submit the same claim, resulting in duplicate copies of the same claim. We need to better understand the current user experience of how an IPF (In Progress Form) becomes a submitted claim. 

Following this discovery, we will be able to come up with solutions to reduce duplicate submissions to minimize Veteran confusion and downstream burden for claims processing.  
Related technical discovery to understand the current state: Investigate vet experience at submit (IPF?) #82474. 

## Tasks
- [x] Find out the scenarios in which Veterans can resubmit an IPF on staging
- [x] Take screenshots/video that show what Veterans see and what they can do
- [x] Identify if there is a way to know frequency of these errors by asking Aurora

## Acceptance Criteria
- [x] Document the Veteran experience submitting duplicates
- [x] Identify pain points that lead to/are associated with duplicate submission

** This is a first pass and may not be inclusive of all scenarios ** 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
Regarding frequency of duplicate problem: Aurora ran the numbers for the last 30 days (April 16-May 16 2024). Out of 55,251 unique users, 4,988 of them submitted more than one time in 30 days. This means 9% of users submitted "duplicates" at an average of 1.3 duplicates per Veteran. 

We are working from the assumption that most Veterans would not create net new submissions within a 30 day period, although it is possible that they forgot a condition and went back to add it. That said, we do know that the current user experience is confusing; it's easy to create duplicates when the IPF is still open and Veterans want to be sure they submitted.

**Comment by evelynhilbrichdavis** [comment]
Linking to my explanation of how duplicates happen vis a vis the In Progress Form post-submission: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82474#issuecomment-2118157694

**Comment by evelynhilbrichdavis** [comment]
[Video demos in DSVA slack channel ](https://dsva.slack.com/archives/C053UDWMH7U/p1716236330858649)
[Updated section in Submission Research Findings to address Duplicates/IPF](https://docs.google.com/document/d/15GAoSNIlhfXOkz8dKGUtZU0wVk2VHGMdmMJ_sPKmah4/edit#heading=h.k3x6knxck41s)
