### ISSUE TITLE
[QA, FE] 10-10 EZ & CG: Create test case scenarios to cover URL changes and redirects validation

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#83172]
## Benefit to the Veteran
By outlining testing and validation steps on URL changes and redirects, we will ensure the Veteran and their families can access the forms and pages they need to within VA.gov, without running into a blocker or causing confusion, so that they can perform their tasks quickly and easily.

## Background
The 10-10EZ form URL needed to be updated to align with VA.gov standards.  The URL was updated and redirects were put in place on 5/6/2024.  on 5/13/2024, an issue was found that the link on the Find a Form page within VA.gov was returning a `404` error, instead of redirecting to the new URL and the form.
This issue was brought to the team by Adrian Rollett, Platform team engineer.  Adrian implemented a fix on the regex to ensure the child page URLs were also redirected properly.  

A [postmortem document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/hdjustice-postmortem-redirect404/Postmortems/2024/2024-05-13%20Find-a-form%20returning%20404%20for%2010-10EZ%20after%20redirect.md) was created and this ticket was opened to ensure our team outlines a comprehensive validation process/steps to complete in the various environments, so that we don't run into this issue going forward.  This process should include a reference to check the regex.

### Resources
- [Postmortem document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/hdjustice-postmortem-redirect404/Postmortems/2024/2024-05-13%20Find-a-form%20returning%20404%20for%2010-10EZ%20after%20redirect.md) with full explanation on the issue, resolution and next steps
- [Original Redirect Request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80756)
- [Out of Band (OOB) PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82928) submitted by Adrian Rollett for the fix

## Tasks
- [ ] Create an outline of steps to follow when testing a URL change and redirect
     - Include teams to engage (Public Websites, CAIA)
     - Include various scenarios to test (google search, VA.gov search, bookmarks, etc)
     - Include reviewing regex for any issues
- [ ] Validate with PM/team engineers 
- [ ] Publish in GH engineering folder, copies in EZ, EZR and CG folders

## Acceptance Criteria
 -A comprehensive outline for testing and review is created and shared with the team.

**Comment by allanto-ah** [comment]
@hdjustice Created some test cases to cover URL changes and redirects. Let me know if I am missing anything or something needs to be changed. Thank you!

[url-changes-test-cases.pdf](https://github.com/user-attachments/files/16997865/url-changes-test-cases.pdf)

**Comment by hdjustice** [comment]
The test cases are great, thank you Allan!  this will be very helpful if/when we ever have to change the URLs again
