### ISSUE TITLE
New Content Task Ticket - Profile - Notification Settings for Debt Resolution Team 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83177]
# CAIA Content Child Ticket

## Issue description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Debt Resolution Team is looking to add notification settings into the VA.gov Profile. 

Currently we have: Health Care, Board of Veterans’ Appeals, and Payments. 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/ce436eca-b2de-4619-80a9-693d2355c030)

There are two main types of notifications that we have to add, 1) Medical Copay and 2) Benefit Overpayments. Should these be added into one of the current sections or should they go on their own into another grouping 

Medical Copay - they have new copayment they need to pay, a notice is sent only once 
Benefit Overpayment - an alert for a new overpayment 

Option 1
- Health Care
     - Medical Copay
- Payments
     - Benefit Overpayment

Option 2 
- Debts
     - Medical Copay
     - Benefit Overpayment

Option 3 
any other idea CAIA has about these groupings and notifications 

---
## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [ ] Assess stakeholder request
- [ ] Draft content
- [ ] Review 
- [ ] Share with stakeholder
- [ ] Update page
- [ ] Copyedit
- [ ] Publish
- [ ] Alert stakeholder

## Acceptance Criteria
_What will be created or happen as a result of this story? Examples:_
- [ ] Updated content is live on the site
- [ ] Product has launched
- [ ] Feedback has been shared with stakeholders

## Configure this issue
- [ ] _Attach to an Epic (what body of work is this a part of?)_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_

**Comment by mtcA6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/83243 closing this out since i've submitted a different ticket
