### ISSUE TITLE
Create Sandbox Env in AWS for testing Terraform

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#83182]
## Issue Description

At the moment, [Non-Devops] Engineers do not have an environment to test the application of terraform or play around with configuration without potentially breaking something others are using. We should spin up a new environment (account?) and create a (hopefully simple) process for engineers to gain access to it.

## Tasks
- [ ] Create Environment/account for users to test terraform application, AWS resources, etc.
- [ ] Determine/document process for engineers getting access to this environment

## Acceptance Criteria
- [ ] Engineers can request/gain access to Sandbox with limited road blocks

**Comment by ben-allen-oddball** [comment]
This is not possible.  Because of access control constraints and having only a single AWS account, this is not possible.  I suggest starting a campaign to have a "dev" or "lab" AWS account spun up for this effort.  In the past I have been able to programmatic spin up new AWS accounts with Terraform.  We tied them to the same billing account and even bootstraped all the standard things (IAM, Groups, Roles, tie to github, private runners, logging, default networks, peering, etc).

This approach also allowed for the lab type accounts to be completely destroyed on a cadence and re-provisioned.  Which kept the environment clean and embraced the fact that the end users should be automating their deployments.
