### ISSUE TITLE
 Create V3::ProfileInformation Service

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#83186]
## User Story
As the developers responsible for backend work on the EVSS PCIU migration,
We want to create the V3::ProfileInformation Services configuration and responses,
So that we can perform the necessary migration of PCIU from the current EVSS environment.

## Issue Description
In this ticket, the objective is to create the V3::ProfileInformation Service's configuration and responses.

## Tasks
- [ ]  Configure V3::Profileinformation service
- [ ]  Configure V3::Profileinformation response (try to add duplicate methods used from other services in this response, if you can)
- [ ]  Configure V3::Profileinformation's configuration
- [ ]  Configure V3::Profileinformation redis

## Success Metrics
- [ ]  V3::Profileinformation service environment is created and configured
- [ ]  V3::Profileinformation response environment is created and configured (try to add duplicate methods used from other services in this response, if you can)
- [ ]  V3::Profileinformation's configuration environment is created and configured
- [ ]  V3::Profileinformation redis environment is created and configured

## Acceptance Criteria
- [ ] The V3::ProfileInformation service is configured, readying the next steps for PCIU migration. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
There has been a lot of coordination between Rachal and Tom regarding how the user workflow works, how data is saved, etc

**Comment by jennb33** [comment]
6/27 stand-up update: per @LindseySaari we have started to condense the methods into the V3 profile

**Comment by jennb33** [comment]
7/1: May need to engage with the Authenticated Experience to do some of this work, they are aware.

**Comment by jennb33** [comment]
7/3: @RachalCassity is splitting up the PRs because there are so many of them. We might be able to pass this off to to AuthExperience

**Comment by RachalCassity** [comment]
PRs:
1) Service: https://github.com/department-of-veterans-affairs/vets-api/pull/17397
2)Transactions: https://github.com/department-of-veterans-affairs/vets-api/pull/17398
3) Redis: https://github.com/department-of-veterans-affairs/vets-api/pull/17400
