### ISSUE TITLE
 Replace V2::ContactInformation with V3::ProfileInformation

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#83187]
## Summary
In this ticket, the objective is to replace all V2::ContactInformation requests with V3::ProfileInformation. This work has to be done behind a feature flipper for testing purposes.
Example:
`VAProfile::ContactInformation::Service.new(@current_user)`
to
`VAProfile::ProfileInformation::Service.new(@current_user)`

## Tasks
- [ ] Create Feature Flipper
- [ ] Replace V2::ContactInformation calls in Vets-API Controllers
- [ ] Replace V2::ContactInformation calls in Vets-API Concerns
- [ ] Replace V2::ContactInformation calls in Vets-API Models
- [ ] Replace V2::ContactInformation calls in Vets-API Sidekiq Jobs
- [ ] Replace V2::ContactInformation calls in Vets-API Modules
- [ ] Replace V2::ContactInformation calls in Vets-API Rake Tasks
- [ ] Replace V2::ContactInformation calls in Vets-API Spec Tests
- [ ] Add Rails logs to each method inside VAProfile::ContactInformation Service to ensure all requests have stopped before tearing down the service

## Acceptable Criteria
- [ ] Auth Experience Team completes testing

**Comment by jennb33** [comment]
8/5 update: @RachalCassity has a PR pending for the VCR and spec load. Once the PR is approved, then the other PRs can go forward?

**Comment by LindseySaari** [comment]
VCR cassettes PR is approved and working forward when time allows

**Comment by jennb33** [comment]
Due to support work, this ticket has been duped as [90625](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/90625) for work in Sprint 8
