### ISSUE TITLE
*Upgrade V1::ContactInformation::Service to V2::ProfileInformation::Service

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#83181]
## Summary

V2::ProfileInformation is a service that pulls data from multiple VA::Profile services currently being used in Vets-API. Upgrading to V2::ProfileInformation will reduce the number of requests and simplify the Vets-API infrastructure. The only objective for this epic is to complete the V2::ProfileInformation upgrade.

## Tasks
- [x] [Create V2::ProfileInformation Service](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/83186)
- [x] [Replace V1::ContactInformation with V2::ProfileInformation](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/83187)
- [ ] [Teardown V1::ContactInformation Service](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/83190)

## Future initiative
- [x] [EVSS PCIU Migration: Remove calls to PCIU in global Pre-fill](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73776)

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83186
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87644
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87645
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89718
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83187
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90625
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91488
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83190
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86485
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86487
```

**Comment by AshleyGuerrant** [comment]
Epic cleanup: Currently, work is not in progress on this epic because this epic is stale and no longer relevant. Closing out.

cc @jwoodman5
