### ISSUE TITLE
Merge VaProfile services into V3::ProfileInformation

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#83183]
## User Story
As the engineers working on the EVSS PCIU migration objective,
It is is important that the v2::ContactInformation is updated to v3::ProfileInformation
So that the [EVSS PCIU migration](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73776) work can be completed

## Summary
V3::ProfileInformation is a service that pulls data from multiple VAProfile services currently being used in Vets-API. Upgrading to V3::ProfileInformation will reduce the number of requests and simplify the Vets-API infrastructure. The objective for this epic is to replace each applicable service to use V3::ProfileInformation. The following services can be merged into V3::ProfileInformation:
- VaProfile::Communication
- VAProfile::Demographics
- VeteranVerification::DisabilityRating
- VaProfile::HealthBenefit
- VaProfile::MilitaryPersonnel

## OKR
O1. Our digital experiences are the best way to access VA health care and benefits
OKR 3: All new products have a faster transaction time than those they replaced

The services were derived from this list of Va::ProfileInformation data
```
- contactInformation
- militaryPerson.transferOfEligibility
- benefitAwardInformation
- communicationPermissions
- demographics
- disabilityRating
- healthBenefit
- militaryPerson.adminDecisions
- militaryPerson.dentalIndicators
- militaryPerson.militaryOccupations
- militaryPerson.payGradeRanks
- militaryPerson.prisonerOfWars
- militaryPerson.militaryServiceHistory
- militaryPerson.militarySummary
- militaryPerson.militarySummary.customerType.dodServiceSummary
- personAttributes
- militaryPerson.adminEpisodes
- genderIdentityTraits
- militaryPerson.retirements
- militaryPerson.separationPays
- militaryPerson.retirementPays
- militaryPerson.combatPays
- militaryPerson.unitAssignments
- militaryPerson.medalsAndAwards

## Tasks
- [ ] Merge VaProfile::Communication
- [ ] Merge VAProfile::Demographics
- [ ] VeteranVerification::DisabilityRating (Maybe? Not sure who owns this)
- [ ] Merge VaProfile::HealthBenefit
- [ ] Merge VaProfile::MilitaryPersonnel

## Success Metrics
- [ ] Number of requests to Vets-API have been reduced after the merge of all profiles by X%
- [ ] Vets-API infrastructure is simplified (**_how was it simplified? Process?_**)

## Acceptability Criteria
- [ ] All profiles have been merged
- [ ] All profiles have been tested and validated post-merge
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86484
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86485
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86486
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86487
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86483
```
