### ISSUE TITLE
Update Spanish eligibility for VA health care page with new content

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#83196]
## Issue Description

We made content changes to the English version of our [Eligibility for VA health care](https://www.va.gov/health-care/eligibility/) page. We need to get this content translated and then add to Drupal page and publish.

## Tasks
- [ ] Send new content to State Department (Randi)
- [ ] Update English page in Drupal (Victoria)
- [ ] Copyedit (Sara)
- [ ] Publish (Sara)
- [ ] Send live page to State for QA (Victoria)

## Acceptance Criteria
- [ ] Page is live with new content

**Comment by RLHecht** [comment]
This content was sent to State on 5/15 and added to the tracker.

**Comment by RLHecht** [comment]
Here is the content back from State. @saratorres2 this is additional content that was missing. Thanks!


[LS-2024-0122945- SPA-FINAL-Eligibility for VA health care additional Spanish content.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15394475/LS-2024-0122945-.SPA-FINAL-Eligibility.for.VA.health.care.additional.Spanish.content.docx)

**Comment by saratorres2** [comment]
Updates made by @saratorres2 @moviedosoco @RLHecht

**Comment by RLHecht** [comment]
we got back the QA for this and there are no changes. @strelichl i think this ticket is good to close.
