### ISSUE TITLE
 Teardown V2::ContactInformation Service

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#83190]
## Summary

V2::ContactInformation Service should not be receiving any requests. Rails logs, made in [Replace V2::ContactInformation with V3::ProfileInformation](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/83187), should not be present Datadog logs. All associated files should be removed:

## Tasks
- [ ] Remove [ContactInformation Directory](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/va_profile/contact_information)
- [ ] Remove [Contact Information Redis](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/va_profile_redis/contact_information.rb)
- [ ] Remove [Tests](https://github.com/department-of-veterans-affairs/vets-api/tree/master/spec/lib/va_profile/contact_information/)
- [ ] Remove [VCRs](https://github.com/department-of-veterans-affairs/vets-api/tree/master/spec/support/vcr_cassettes/va_profile/contact_information)
