### ISSUE TITLE
Copy edit live 'How to apply for VA health care' page in Spanish

### ISSUE THREAD

**Issue by moviedosoco** [department-of-veterans-affairs/va.gov-team#83202]
## Issue description
Tracking questions and corrections for page. The next step will be to make changes in Drupal and publish.

---
## Tasks

- [x] Review and track errors (Victoria)
- [x] Review (Randi)
- [ ] Batch questions and changes and share with State Dept for review
- [ ] Update page in Drupal (Victoria)
- [ ] Copyedit (Sara T.)
- [ ] Publish (Sara T.)

## Acceptance Criteria
- [ ] Updated content is live on the site

## Configure this issue
- [ ]     #80097

**Comment by moviedosoco** [comment]
@RLHecht This is ready for your review. Please see the link below. Thank you!

https://docs.google.com/document/d/1DUqHEjNlb-5-EfeM8M1Aqob5jYZkfxKl_IALUxQkwqU/edit

**Comment by RLHecht** [comment]
Thanks @moviedosoco These changes all look good. This is ready for next steps!

**Comment by RLHecht** [comment]
Doc references is a google doc from previous team that we can't access. Going to close this ticket and will eventually open a new one to continue any work.
