### ISSUE TITLE
[FE] - Canceled appointments in upcoming list

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#83225]
## Summary
When an appointment in the upcoming appointments list has a canceled status, show with ~~strike out~~ styling.
<img width="455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--126d9416a4ca0c74750b741b0dde9d3c4bef63e4/Screenshot%202024-05-15%20at%203.43.17%E2%80%AFPM.png" alt="Screenshot 2024-05-15 at 3.43.17 PM.png" />

## Wireframes
- [Wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=977-59422&t=68mCdiY9vGnUf1qz-0)

## Tasks
- [ ] [FE] apply style to canceled appointments
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/83225?planning-poker) with Zenhub @wullaski
