### ISSUE TITLE
[FE] - Remove chevrons from mixed modality message

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#83224]
##Summary
Remove the inline chevrons from the mixed modality message text that is seen on error pages and anywhere else it is used.

<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4de4380be6ebec38a46ab72ff40c9e01deb49e9c/Screenshot%202024-05-15%20at%203.37.14%E2%80%AFPM.png" alt="Screenshot 2024-05-15 at 3.37.14 PM.png" />

## Wireframes
- [Wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=1039-8310&t=68mCdiY9vGnUf1qz-0)

## Tasks
- [ ] [FE] remove chevrons
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/83224?planning-poker) with Zenhub @wullaski

**Comment by zach-park** [comment]
LGTM. Thank you!
