### ISSUE TITLE
[FE][bug] - Setting and getting pre-check-in complete is broke for unified

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#83223]
## Summary
It seems like both setting and getting pre-check-in complete from session is broke. It is probably not getting `app` sent to the hook properly.

<img width="1686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e2facbc8427752c570efface1be815a1d164b97/Screenshot%202024-05-15%20at%203.32.42%E2%80%AFPM.png" alt="Screenshot 2024-05-15 at 3.32.42 PM.png" />

## Tasks
- [ ] [FE] fix set and get for pre-check-in
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/83223?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
This ticket was fixed by https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/82974

Closing.
