### ISSUE TITLE
[FE] pre-check-in - Remove your appointment is on [timestamp] on confirmation

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#83222]
## Summary
Remove the Remove `Your appointment(s) are on Month Day, Year.` text after the H1
<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3prQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3e4b91e4b4f62c595b8b844d678d6fc01da4533/Screenshot%202024-05-15%20at%203.27.34%E2%80%AFPM.png" alt="Screenshot 2024-05-15 at 3.27.34 PM.png" />

## Wireframes
- [Wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=937-28573&t=fRxLxE3zbsCOjHhD-0) 

## Tasks
- [ ] [FE] Remove text from confirmation page
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/83222?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
PR ready for when next sprint starts

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 this one is ready to validate. See screenshot.
<img width="141" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--879f122dc512b0923445056a78c3c167b962ba95/removed-timestamp.png" alt="removed-timestamp.png" />

**Comment by benbrasso-agile6** [comment]
LGTM, @zach-park, John is working on a separate ticket that you'll want to review, where he's adding in the `Your appointments` h2 below the h1

**Comment by zach-park** [comment]
LGTM too. Thank you! 

For @benbrasso-agile6 , noted about John's ticket!
