### ISSUE TITLE
[CST] [ENG] Create status page and overview alerts for when claims revert to a previous step

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#83244]
## Value Statement
**_As a_** Veteran checking on my claim
**_I want to_** see a visual cue when my claim reverts to a previous step
**_So that_** I am aware of this action and 

---
## Background Context
Due to the cyclical nature of the disability claims process, we want to have a way to point Veterans' attention a messaging that their claim has moved to a previous step. 

### New Feature
-[ Epic Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82360)

## Design

**Note**:  An alert is displayed when the Veteran logs in for the first time since their claim has reverted. It disappears for subsequent logins.

<img width="1205" alt="Screenshot 2024-05-17 at 1 23 07 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/4b1f7126-5c9e-4906-9480-846f235bdb3a">

## Engineering 
- On `ClaimTimeline.jsx` we use the `claim.claimPhaseDates.currentPhaseBack` field to determine if a claim is phased back and check to see if the current phase is 6. 
- Looking at our current claim data there is no way to tell what the previous phase was, in order to only show the information alert at the initial phaseback.

## Open questions
- When the user is on step 4,5,6 and the claim has been reverted to a previous step, do we still show this alert on step 3 or are we only showing this alert on step 3 when step 3 is the current step? - **answered in comment below**
- How do we determine that a claim has been reverted in the code?
- Do we have mock data currently around this scenario? If not will need to do that as well. 
- Looks like we are hiding the text that says "step may repeat" on all steps? , can someone please confirm this - answered in comment below

## Tasks
- [ ] Add the information alert on CST home page on the claim card
- [ ] Add the information alert to the status page status page, under the What we are doing section
- [ ] Add the information alert to the overview page under the step where the claim reverted to when the `claim.claimPhaseDates.currentPhaseBack` field is set to true.
- [ ] Whatever the current step is, hide the 'Step may repeat' text for the given step

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria

- [x] The Status tab of the selected claim will display an information alert under the 'What we're doing" section
- [x] The Overview tab will display an information alert under the step where the claim reverted to when the `claim.claimPhaseDates.currentPhaseBack` field is set to true. (ie if the claim reverted to step 3 and the `claim.claimPhaseDates.currentPhaseBack` field is true, the alert will show in step 3, if the claim reverted to step 4 and the field was true, then the alert would display in step 4.)
- [x] The 'Step may repeat' text is hidden on the step where the claim reverted to. (ie. if the claim reverted to step 3, the other steps 4,5,6 will still have the message box "step may repeat"
- [x] Behind cst_claim_phases feature flag

**Comment by uxgary** [comment]
**Response to open question**: 

- When the user is on step 4,5,6 and the claim has been reverted to a previous step, do we still show this alert on step 3 or are we only showing this alert on step 3 when step 3 is the current step?
This alert is intended to show on the step the claim was returned to. In theory, if the claim went back to step 2, the alert would show there. In the mock we showed step 3 because, that's a common thing. But say if the claim was at step 6, and went back to step 4, the alert would show on step 4. 

- Looks like we are hiding the text that says "step may repeat" on all steps? , can someone please confirm this
We not hiding the massage for all steps, just on the step where the new alert is temporarily display. It's removed because it might be redundant to have an alert telling a veteran their claim has revert and below that having a message box that reads there's a potential the step can repeat. Essentially, this alert is temporary, just for the first log in so veterans can be aware their claim did return to a previous step. When veterans return for subsequent sessions, the alert ("we moved your claim back to this step...") should  disappear and the UI goes back to normal showing the message this ("this step may repeat...")

Just a reminder, I noted: An alert is displayed when the Veteran logs in for the first time since their claim has reverted. It disappears for subsequent logins.

**Comment by pmclaren19** [comment]
Thanks for the additional information. These things weren't noted in the ticket or the mocks so I will update the ticket tasks/ ac to reflect this.

**Comment by pmclaren19** [comment]
Met with @samcoforma  and @uxgary Looking at our current claim data there is no way to tell what the previous phase was, in order to only show the information alert at the initial phaseback. Therefore this design may or may not be possible. We will need to hold off on pointing this until we can confirm with @jerekshoe on if this is indeed possible or if we need to change the design.

**Comment by uxgary** [comment]
when thinking about feature flags, this work stems from component used in the evidence submission project. We maybe using the feature flag used in that work to keep the features together.

**Comment by pmclaren19** [comment]
Spoke in parking lot about how we want to handle this alert with @uxgary @samcoforma @jerekshoe . 

Moving forward we will display this alert on steps (3-6) when the field `claim.claimPhaseDates.currentPhaseBack` is set to true and we will hide the 'Step may repeat' text. After the phase moves forward, lighthouse will set this field `claim.claimPhaseDates.currentPhaseBack` back to false and when this occurs, this alert will be hidden and the 'Step may repeat' text will be shown again.

**Comment by jerekshoe** [comment]
One thing to note with this is that when we get the list of claims, lighthouse doesn't include the attribute to indicate whether the claim is currently phased back or not. We only get that attribute when we pull the details for an individual claim
