### ISSUE TITLE
[Team] 10-10EZR: Sprint 125 Error Tracking

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#83240]
As a Veteran, I would like to update my information online via the 10-10EZR and have it saved to my VA record so that I don't have to print out a form and mail it in

- [ ] **Success: Errors for Sprint 125 have been reviewed, Veterans have been contacted for failed submissions, and fixes have been proposed.**

**Comment by mkerns1** [comment]
## Issue: 1010EZR Submission Job Failure

### Summary:
An 1010EZR submission job has failed with no retries left.

### Details:

Notification Triggered: Datadog alert for 1010EZR submission job failure
Notification Timestamp: Friday 5/17/24 at 12:52 PM

### Next Steps:

- [ ]  Investigate the root cause of the submission failure.
- [ ]  Review the retry mechanism and ensure it's properly configured.
- [ ]  Implement fixes as necessary to prevent future occurrences.
- [ ]  Update the ticket with findings and resolutions.

**Comment by JoshingYou1** [comment]
After investigating, I'm not sure what  caused the error on 5/14/2024 at 4:50pm UTC. It was not a `SchemaValidationError`, DOB and full name were both present, and according to Josh F., there were no recent submission errors in VES with an ICN that matched the failed submission's ICN. With all of that being said, the submission, prior to post-filling, did not contain the `veteranDateOfBirth` field. We added a DD logger to increment each time a form was missing DOB, and sure enough the times match up. Here's the DD data:
<img width="1755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC94QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04ef41cfed80faac667767639d66d0779de8e003/Screen%20Shot%202024-05-17%20at%204.15.57%20PM.png" alt="Screen Shot 2024-05-17 at 4.15.57 PM.png" />

Since the DOB WAS present in the `PersonalInformationLog` data, we know that our post-fill code is in fact working as intended. The other strange part about this error is that in Sentry, the response body doesn't make sense. Here's what it logged:
<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVB4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8141dad2a51b34feea73f020831f45e624db155f/Screen%20Shot%202024-05-17%20at%204.20.53%20PM.png" alt="Screen Shot 2024-05-17 at 4.20.53 PM.png" />
`letter_destination` and `letters` comes from Lighthouse code that can be found here: https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/letters_generator/service.rb#L57

What should be the next course of action here?

**Comment by JoshingYou1** [comment]
## Issue: 1010EZR Submission Job Failure

### Summary:
An 1010EZR submission job has failed with no retries left.

### Details:

Notification Triggered: Datadog alert for 1010EZR submission job failure
Notification Timestamp: Friday 5/21/24 at 12:44 PM EST

### Next Steps:

- [x]  Investigate the root cause of the submission failure.
- [x]  Send HEC email
- [ ]  Review the retry mechanism and ensure it's properly configured.
- [ ]  Implement fixes as necessary to prevent future occurrences.
- [x]  Update the ticket with findings and resolutions.

**Comment by JoshingYou1** [comment]
Based on the DataDog logs, a schema validation error occurred. However, no specific information was provided as to which field(s) failed validation. In addition, no Sentry logs were generated, which is really bizarre. In the DB logs, DOB and full name were present. The next course of action will mostly like be to increase the details of our error logs by logging each and every validation error.
