### ISSUE TITLE
Epic Governance/Oversight | Profile | Profile Completion - Contact Info

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83258]
## Background
We're dusting off our blue sky designs from several years ago and the concept of profile completeness is particularly salient given the "Onboarding" work that is occurring on multiple fronts. 

The IIR team specifically called out profile completeness as a component of onboarding new users to the site. Through this epic we want to explore what that could look like. 

## Important Artifacts
- [2016 blue sky designs](https://vsateams.invisionapp.com/console/share/X3WBOA3QSWR/600536835)

<details><summary>screen grabs of bly sky as invision is being retired</summary>
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/04bcbf65-3e33-445c-8944-bb9f26bdaf65)

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/528c37ef-957f-4be6-b41a-c3841fedad7f)

</details> 

- [Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/profile-completion/README.md)
- [Story on the Digital Experience Project Board](https://github.com/department-of-veterans-affairs/digital-experience-products/issues/940)

### IIR artifacts 
- [collab cycle for the IIR onboarding page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82257)
- [IIR onboarding analysis mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712608107388/80dc1be20f9ee63ac894c536ccd20d5b1cc172e1?sender=uaa72d11015d3f7c704a64191)
- [user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715019181472/206d1983971576ee7696c1984666185a2fbff545?sender=uaa72d11015d3f7c704a64191)
- [figma for midpoint](https://www.figma.com/design/CertVj7cu66kFv9TnseR30/Veteran-Onboarding?node-id=300-11104&t=Ow7esQ4gUlPtOyqr-0)
- [latest mural 8/28](https://www.figma.com/design/CertVj7cu66kFv9TnseR30/Welcome-to-My-VA?node-id=300-11104&t=4JY656zoEPXkyy8j-0)

## Tasks 

```[tasklist]
### IIR Collab Cycle
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82257
``` 

```[tasklist]
### Design/Discovery
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83262
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83263
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/84031
``` 

```[tasklist]
### Engineering
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83264
```

**Comment by ACParker89** [comment]
- Thinking through use case:  could this pop up whenever someone navigates to profile if it is not complete with the option to opt out for that instance (time out for X days, months?) 
- Future feature- how can this be incorporated with tutorial videos? 
- Possible tasks create a user story map? 
- Design vs. what is feasible? Can we meet early to determine this? (bring in FE,FS early for learning opportunity)

**Comment by mtcA6** [comment]
This launched in Feb 2025

**Comment by mtcA6** [comment]
[Closing this epic and creating a new one for the next phase of this work which will focus on completion/update of notification settings ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/104625)
