### ISSUE TITLE
[DevOps] Create folder for CIE DevOps documentation.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#83256]
## Description
We Two DevOps need a place to store our documentation.

## Tasks
- [x] [DevOps] Create a folder for DevOps documentation.
- [x] [DevOps] Move existing documentation that is relevant into that folder.

## Acceptance Criteria
- [x] Folder created.
- [x] Any pertinent documentation exists within that folder.
- [x] Folder is linked from team documents.

**Comment by ndouglas** [comment]
Added here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/devops
