### ISSUE TITLE
Design | Profile Completion | Desk Research

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83263]
## Background 
With efforts toward increasing Veteran onboarding experiences, Profile completion is a component that can be used in the future to increase this experience. We are considering this an MVP to help build a foundation that could be expanded upon.  

We know we want to target contact information as "completeness" for our MVP.

## Tasks 
- [x] Get up to speed with what IIR and VES are planning and how profile completeness fits in
- [x] Talk to the mobile team to see what, if anything, they've done in this space
- [x] Review previous comparative analysis we've done on profile completeness
- [x] Identify various scenarios we need to account for

## Acceptance Criteria
- [x] Ready to move forward w/ design

**Comment by andaleliz** [comment]
I've finished looking into this, sharing some notes:
- The clearest relationship between this and IIR is that IIR's UX will link to the profile w/ some kind of CTA to complete it. Likely would not include a progress bar since we're not loading all the related APIs at that time
- VES's UX is unauth at this time, so it doesn't really make sense, IMO, to take that into consideration for this MVP for now
- I don't think we need to be concerned with LOA1 users for this work, since all they can see is the account security page until they verify
- The mobile team hasn't done anything related to profile completeness
- Scenarios we need to account for (probably others, but these have come to mind so far), all of which impact LOA3 users
  - Missing all contact information
  - Missing some contact information
  - Exiting the flow immediately 
  - Exiting after entering some information
  - Error states
