### ISSUE TITLE
Adjust breakers boards and alerts to account for metric adjustments

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#83287]
## Description 
As a follow-up to the metric tagging adjustments [outlined in this ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/77891), we need to create a subsequent ticket to update the breakers boards to reflect these changes. To avoid a visibility gap, these boards must be prepared in advance. This will ensure that they are fully operational before we implement the Datadog mapper configuration in production

## Tasks
- [ ] Adjust [existing breakers boards ](https://vagov.ddog-gov.com/dashboard/lists?q=breakers)to account for new tagging scheme
- [ ] Adjust any external service [monitors](https://vagov.ddog-gov.com/monitors/) based on these metrics
- [ ] Verify boards are functional (against lower env metrics already flowing in)
- [ ] Make annoucement in ToT for other teams that are possibly dependent on alerts @jennb33 

## AC
- [ ] Existing breakers boards are adjusted and ready for when the mapper changes are applied to production
- [ ] Monitors are adjusted
- [ ] ToT slide accounts for the announcement around the change

**Comment by jennb33** [comment]
@LindseySaari Which ToT meeting should this be announced at? I'm thinking 6/4 then again on 6/11. Thoughts? I don't want to announce too prematurely. This is in the 6/6-6/19 Sprint, so we can give other teams a head's up on when it's going to happen, then when the work is in flight. LMK, thanks!
