### ISSUE TITLE
[FE] Add privacy act statement modal to appointments page

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#83281]
## Summary
Add the privacy act link and modal to the appointments list page under the accordion.

## Wireframes
- [Wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-|-Check-in?node-id=961-51636&t=OkAPU4MNmdiID5tG-0) 

## Tasks
- [ ] [FE] Add the modal
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/83281?planning-poker) with Zenhub @brianseek
