### ISSUE TITLE
Apply Datadog external metric mapper changes to prod

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#83288]
## Description

As a continuation of the work outlined in ticket in #83287 and #83285, we must deploy the new external metric statsd mapper configuration to production. Before proceeding, we need to ensure that all mappers have been applied and the Datadog charts and monitors updated accordingly. Everything must be confirmed and thoroughly verified to ensure readiness prior to transitioning to the production environment.

## Tasks
- [X] Mapper is applied to production
- [X] Mapper changes are verified 
- [X] Charts are verified 
- [x] Any documentation is updated

## AC
- [X] Mapper is successful tagging the external service metrics appropriately
- [x] Charts and monitors are adjusted
- [x] Documentation is adjusted
