### ISSUE TITLE
[DESIGN] Create CodePen Prototype(s) for Research

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#83297]
## Background
We plan to pursue moderated research that combines usability testing and concept testing. 

## Task
- [ ] Confirm prototype needs with UX team
- [ ] Create prototypes for research, tentatively
  - [ ] Scheduling flow clickable prototype in Figma for usability testing: Text reminder -> Scheduling flow
  - [ ] Appointment list -> Notifications list screens for concept testing

## AC
- [ ] Prototypes have been created and shared with the team
- [ ] Prototype links have been added to research materials

**Comment by benbrasso-agile6** [comment]
@cgednalske try to flesh out what might get accomplished for this ticket for next sprint, so we're breaking it into smaller chuncks, if needed. Doesn't need to be 100% accurate. Then, we can point on Tuesday.

**Comment by benbrasso-agile6** [comment]
@cgednalske I think I'm going to stub out a ticket to clean up CodePen prototype based on Midpoint Review feedback and A11y walkthrough. So, feel free to close this ticket when ready.

**Comment by benbrasso-agile6** [comment]
@cgednalske ready to close?

**Comment by benbrasso-agile6** [comment]
https://app.zenhub.com/workspaces/appointments-cc-direct-scheduling-660abc13699bfa00195d685a/issues/zh/338
