### ISSUE TITLE
Customize GA4 GUI Reports - First Group

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#83313]
### Description
This task is for us to begin customizing the GUI reports for VA.gov. This first round will help us gain an understanding of what can be done with the GUI reports as well as provide examples for teams. 

While the existing team UA reports may influence how GUI reports are created, we are not trying to duplicate or replace the old dashboards:
- Log of Reports Powered by GA: https://docs.google.com/spreadsheets/d/1xDWAyKt-2lS5RsRhXBk5EA08-RM3qomJi1EqTjQ48sE/edit#gid=0

---

### Tasks
**In Non-Production Property:** 
- [ ] Update base forms to remove ecommerce metrics
- [ ] Session attribution (where traffic comes from)
- [ ] Email campaigns (subset of attribution) 
- [ ] Forms

**Update Production Property:**
- [ ] Update base forms to remove ecommerce metrics
- [ ] Session attribution (where traffic comes from)
- [ ] Email campaigns (subset of attribution) 
- [ ] Forms

### Acceptance Criteria

- [ ] GA4 Non-Production Property is updated
- [ ] GA4 Production Property is updated

**Comment by johnny-jesensky-adhoc** [comment]
We're going to swap this out into next sprint, as it better aligns with our training timing, and we've spent more time validating this sprint than expected. Queued up for next sprint.

**Comment by raywangoctova** [comment]
@johnny-jesensky-adhoc Why did we prioritize this work? If we are not duplicating old reports, is this for replacing or fulfilling requests for new reports?

**Comment by jestutt** [comment]
@raywangoctova  I pushed for this one. Tracking in UA was all about fitting the majority of your tracked information into the default fields and GUI reports. GA4 is less default and more customized and while it's not a replacement for the UA Dashboard reports customizing GUI for high-level business needs -- email campaigns -- and to elevated dimensions where some of the commonly referenced information now lives -- DLE names that used to live in the UA Event Action. 

Also, Teams will eventually ask about this and we need to know the practical capabilities are and have some examples to point to.

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- tried to grab screenshots for validation purposes of this in our GA4 Production Property. Feel free to add additional ones. 

_Session attribution set-up_
![image](https://github.com/user-attachments/assets/6b7a4c92-519c-41ba-a9ce-a89247961636)

_ECommerce options removed_
![image](https://github.com/user-attachments/assets/db79e29c-c3b9-4e04-b100-a882e8937ffd)
