### ISSUE TITLE
[CAIA Intake] Benefits Decision Review: Supplemental Claims (VA-20-0995) form updates

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#83316]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Benefits Decision Reviews
- **OCTO product owner:** @amylai-va 
- **Product name:** Supplemental Claims
- **Product manager:**  
- **Slack channel:** [#benefits-decision-reviews](https://dsva.slack.com/archives/C5AGLBNRK)
- **Dedicated content writer on your team (if you have one):** 
- **Dedicated a11y specialist on your team (if you have one):** @davidakennedy 
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [x] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

`Tell us briefly about your work and the outcomes you’re aiming to achieve.`

The Supplemental paper form is being updated, and we want to get the digital form to match. Paper form should be done by June.

## Collaboration timeframe
**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

We started in our current sprint (5/8-5/21), and want our content POC to be closely aligned, so we're inviting early for possible collaboration.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [ ] No
- [x] I’m not sure

Form updates include a mandated inclusion of VBA to VHA notification consent for Veterans claiming conditions due to personal traumatic events involving MST. Multiple forms require this update, including: 526ez and 0781. Updates also include optional homelessness questions also on the 10207.

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

Form is already in production, but there will be new screens added as a result of this update. We are in the initial discovery with SMEs for update requirements.

### Will you release this new product incrementally (for example, release to 25% of users to start)?
- [x]  Yes
- [ ]  No
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [ ]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Form Audit MURAL](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714484854529/9d8878c66064362f8bdaed6531bcfb43fa8064f6?sender=ud193ce75f65a17a316ea6194) - What we're using to discuss changes with SMEs
- [FIGMA](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=0%3A1&t=NATulJ2TO94MKDmQ-1) - What's in production and in progress design. Focus will be on the new sections, indicated with yellow circle and IN PROGRESS tag.

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [x] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88995
```

**Comment by eileen-coforma** [comment]
Tagging @bethpotts and @jstrothman for visibility, since we've been in discussion about a content POC.

**Comment by kristinoletmuskat** [comment]
Noting that Eileen mentioned there might be new pages and suburls in this form that IA could review, but the form itself isn't moving locations. @eileen-coforma when you have ideas for those new urls we'd love to take a look! Feel free to tag me here when ready and we can go over them in like a 15 min call. I know that might be many weeks away.

**Comment by aprocik1** [comment]
Hi @eileen-coforma, thanks for this request. I know you're working to finalize the PDF form by June--the end of this week. Some of our content team members are at Code for America, so we have limited capacity this week. If there's something you'd like to start collaborating on right now, I'm available to meet tomorrow 5/29 or Friday 5/31 from 10-2 pm ET. Or, if you'd prefer to wait for a kickoff meeting with our whole team, we're available to meet Thursday 6/6 from 3-5 pm ET or Wednesday 6/12 from 12-1 pm ET. What do you think?

**Comment by jstrothman** [comment]
@aprocik1 Thank you -- Eileen is unexpectedly out this week. I'd love to take you up on the offer to take a look at one aspect of the updates tomorrow: specifically where we ask questions related to a separate form, which we submit on the back-end. We want to ensure the Veteran is aware that an additional form is being submitted on their behalf. (Related issue: #83774 )
I'm available at 10am -- should I send you an invite?

**Comment by jstrothman** [comment]
As of 5/29/2024, OMB approved the updated Supplemental Claim VA Form 20-0995!
This means we no longer have a concern about late-breaking changes

**Comment by aprocik1** [comment]
Hi @jstrothman, feel free to follow up here when you're ready for us to align on next steps, whether that be scheduling a kickoff or moving forward in the review we started last week. I know you're at an offsite this week, so take your time. There's no rush on our end--I just didn't want to lose sight of this.

**Comment by katherine-fung** [comment]
Hi @eileen-coforma @jstrothman, 

I'm checking in to see if this work is ready for CAIA to review. 

If it's ready for us, can you please confirm the latest designs for us to review? 

I saw the homelessness questions in the Figma file linked above. Did Danielle Thierry work on this copy with you? If not, these questions are related to another conversation she's having with the VA Homeless Programs Office, so we'll want to give her a heads up about them. For context, what's the purpose of adding these questions? I know in the HLR design, there's a single screen that asks Veterans if they're homeless or at risk and Eileen had said this info would be used to expedite the HLR if Veterans answer yes. But I notice that the SC design has additional questions about homelessness.

**Comment by jstrothman** [comment]
@katherine-fung Re the homelessness questions:
Danielle is aware of these new questions being on the 0995. On 4/24, she shared with me a screenshot of these same questions being implemented on the [20-10207 Priority processing in support of a claim (figma)](https://www.figma.com/design/DA6OjFz20kUa9ecElv9zPE/Prod---20-10207-Priority-Processing?node-id=602-71837&t=MF9eAKEEV10gTSgr-4). (@eileen-coforma I realize now I didn't share that info with you at the time.)

I believe the amended questions are based on VEO research, and that VBA intends to use the updated versions on all benefits forms that ask about homelessness.

**Comment by eileen-coforma** [comment]
@katherine-fung 
The SC work is not ready for review yet. We expect for it to be ready by early next week. Some of our designs also depend on the meeting we have this Friday with SMEs to clarify content surrounding the VHA Notifications question (also related to the 0781 work you've been involved in)

When it is ready, I will leave links to the Figma pages with new proposed designs.

**Comment by katherine-fung** [comment]
Hi @eileen-coforma,  

I've provided most of CAIA's recommendations in Figma comments. 

There are still a few outstanding issues. 

1. How should forms make people aware that they have to fill out another form? We still need to standardize this pattern on intro pages and potentially on the subform page itself (in the case of Supplemental Claims, this screen: https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1058-35856&t=TBi1B5OIfmoPBjuO-0). I discussed this with Danielle and have some ideas to discuss with A when they're back next week. 

2. A and I will discuss this together when they're back next week: "Can we standardize how we talk about 'VA facility or provider' v. 'VA hospital or clinic' v. 'military treatment facility' v. 'military hospital or clinic' etc.? I think we should try to be consistent with this language, especially if these terms have specific meanings. Maybe we match everything to the check boxes in question 22A on the PDF. What do you think?" 

3. @eileen-coforma - The stakeholders for the VHA notifications content haven't responded to my questions about their edits in the Word doc. Do you want to follow up with them, since you've been communicating with them?

**Comment by eileen-coforma** [comment]
Thanks @katherine-fung Are the recommendations finalized, or should I wait for A's edits/approvals?

1. We have already implemented the OMB information for both forms in the introduction, referenced the embedded form within the non-VA evidence question, and changing the relevant pages' subheaders to include the embedded form numbers.
- If there are other suggestions, it may be out-of-scope, for the update itself.

2. If we want to match the form, we can simplify it by following 22B "Treatment facility"

3. Yes! I can reach out about it. I keep forgetting by the time I manage to log into CAG. I think she was also on PTO for a bit.

**Comment by katherine-fung** [comment]
@eileen-coforma we should have these finalized by Monday. 

1. After discussing with Danielle and Laura, I put a [recommendation here](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A?node-id=0-546#881208828) for the 4142 details on the intro page. It's a minor content tweak (delete the current H2, and replace it with another H2 slightly lower on the page). We want to avoid this header "Details for forms within this application" and nesting SC and 4142 under it because: 
- there's inconsistencies across products for how we refer to "forms," "applications," and "claims" 
- it suggests that there's a parent application that SC and 4142 are part of, whereas SC is the actual application and 4142 is an additional thing to fill out. 

If this is out of scope for this update, can we come back to it as part of creating/implementing form-within-a-form patterns (based on the SC and 0781)? 

2. Noted! I'll discuss this with A on Monday. 

3. Thank you!

**Comment by katherine-fung** [comment]
@eileen-coforma A and I finalized the recommendations for point #2. 

You can implement the recommendations in these comments: 

https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A?node-id=0-2532#878499914 

https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A?node-id=0-2532#878467299 

https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A?node-id=0-2532#893232661

**Comment by eileen-coforma** [comment]
@katherine-fung thank you!

**Comment by aprocik1** [comment]
Hi @eileen-coforma! I'm following up on Lily's question from August. Can we close this ticket? Or, are you still waiting to launch these updates?

**Comment by laurenvocke-va** [comment]
@DanielleThierryUSDSVA to check on this

**Comment by mistymg** [comment]
Hi @amylai-va! I don't believe the creator of this ticket (Eileen) is on the Decision Reviews team anymore. This is an old intake ticket from the former CAIA team. It's unclear if there was anything else needed for this work. Or if we can close it out. Not sure if you can help but any insights would be appreciated!
