### ISSUE TITLE
Sync BE with Platform for Incident Response

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8332]
## Goal
In the event of an outage or disruption, we need fast and definitive answers on whether a service is degraded, how its degraded, escalation paths, customer messaging etc, so that we can have make informed decisions and have a clear path forward ahead of time.

## Tasks
- [x] Find the right person/ people to talk to on Platform
- [x] Schedule a meeting with them and eBenefits BE Team
- [x] Establish the best monitoring tool(s), gain access if needed
- [ ] Codify the different outcomes that monitoring can produce for each applicable service
- [ ] Discuss the escalation paths as needed
- [ ] Establish customer messaging to be used: where and when does it appear? how is it deployed?

## Acceptance Criteria
- [x] Document [here in GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/incident-response.md) the results from this meeting for further development and use.
