### ISSUE TITLE
DR | Review use of "please" in our forms

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#83324]
## Value Statement
**_As a_**  decision reviews team member
**_I want to_** make sure our use of the word "please" is appropriate
**_So that_** we can ensure we match the content recommendations

## Background Context

After reviewing the use of "please" within our decision reviews forms, not including content or error messages provided by sources outside our forms, this list was compiled:

### All DR

- Need help footer: 'If you have questions or need help filling out this form, please call us at...'

### SC

- SiP restart (loading indicator message): 'Please wait while we restart the application for you.'
- SiP expired: 'Your saved VA Form 20-0995 (Supplemental Claim) application (20-0995) has expired. If you want to apply for VA Form 20-0995 (Supplemental Claim), please start a new application.'
- SiP not found: 'Please start over to apply for VA Form 20-0995 (Supplemental Claim).'
- not signed in: 'Please sign in again to continue your application for VA Form 20-0995 (Supplemental Claim).'
- ITF: 'Please wait while we check to see if you have an existing Intent to File.'
- ITF error: 'We’re sorry. Your Intent to File request didn’t go through because something went wrong on our end. For help creating an Intent to File a Claim for Compensation, please call Veterans Benefits Assistance at...'
- submission error alert: 'We’re sorry. We’re working to fix the problem, but it may take us a while. Please try again tomorrow.'
- Confirmation: 'If you requested a decision review and haven’t heard back from us yet, please don’t request another review. Call us instead.'

### HLR

- SiP restart (loading indicator message): 'Please wait while we restart the application for you.'
- SiP expired: 'Your saved Higher-Level Review application (20-0996) has expired. If you want to apply for Higher-Level Review, please start a new application.'
- SiP not found: 'Please start over to request a Higher-Level Review'
- not signed in: 'Please sign in again to continue your request for Higher-Level Review'
- Intro text: 'If you need help requesting a Higher-Level Review, you can contact a VA regional office and ask to speak to a representative. To find the nearest regional office, please call...'
- Contestable issues additional info: 'To learn more about decision review options, please visit our...'
- Informal conference call you: 'First we’ll call you to schedule the informal conference. Please indicate your availability by providing a preferred time for a call.'
- Informal conference call rep: 'First we’ll call your representative to schedule the informal conference. Please indicate their availability by providing a preferred time for a call.'
- Confirmation: 'If you requested a decision review and haven’t heard back from VA yet, please don’t request another review. Call VA at...'

### NOD

- Filing deadlines: 'Please understand that by listing any issues currently pending in the old system,'

Note that these NOD messages don't use please:
- SiP restart: no subtask to show message
- SiP expired: 'Your saved Board Appeal request has expired. If you want to request a Board Appeal, start a new request.'
- SiP not found: 'Start over to apply for a board appeal'
- not signed in: 'Sign in again to continue your request for a board appeal'

We need to evaluate this list and bring up content revisions with CAIA. 

## Tasks
- [ ] Review usage of "please" within our forms
- [ ] Remove list items that don't need to be addressed
- [ ] Compile remaining items and discuss with CAIA
- [ ] Update content source of truth & designs
- [ ] Make updates in our forms
- [ ] Update tests as needed

## Acceptance Criteria
- [ ] Usage list reviewed & updated within our forms
- [ ] All tasks completed
- [ ] All tests passing

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by shaunburdick** [comment]
Ready for content review @eileen-coforma

**Comment by shaunburdick** [comment]
List has been updated. If this hasn't been updated before the form updates are complete, the list will need review by @eileen-coforma

**Comment by shaunburdick** [comment]
Blocked by our own work to update the forms.
