### ISSUE TITLE
Implement Benefits Claims Validate Endpoint for Testing Purposes

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#83342]
## Issue Description

---
## Tasks
- [ ] Create Validate Endpoint for Claims API
- [ ] Write a script that submits X number of existing claims against validate endpoint to see if they would have passed

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lisacapaccioli** [comment]
Closing as a duplicate
