### ISSUE TITLE
Update Get Access to Tools Page: Remove GitHub link and Update GitHub page  [Footer Request 82291]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83344]
## Issue Description

- Platform Website [guidance for Zenhub access](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) needs to be updated, as the GitHub link shows out-of-date Onboarding information. 
- The link at the bottom of the paragraph points to [this GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/zenhub.md).
- That github doc is out of date and Platform Support Team now administers Zenhub licenses per [this announcement
](https://dsva.slack.com/archives/CE4304QPK/p1714146847917589)
### SME: Platform Support Team

---
## Tasks
- [x] Remove this line altogether from the PW page: "For additional information, see details and orientation on Zenhub."
- [x] Deprecate GitHub page per [these instructions](https://vfs.atlassian.net/wiki/spaces/CIT/pages/1397194753/Deprecate+a+page+in+GitHub)
- [x] GitHub instructions should link back to the [PW page](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools) for guidance on ZenHub

## Acceptance Criteria
- [x] GitHub page is deprecated
- [x] Platform Website has been updated to remove the link to the deprecated GitHub page
- [x] Platform Website page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/83344?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
Guidance [outlined here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82291#issuecomment-2116007620) could replace the [GitHub file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/zenhub.md#zenhub-onboarding) language.

**Comment by jknipes** [comment]
Per @alyssagallion we are deprecating the GitHub page and removing the link from Platform Website.

**Comment by jknipes** [comment]
work has been completed, moving to _Done_

**Comment by CherylEvans** [comment]
@jknipes The User Story is satisfied, and the AC has been met. Closing.
