### ISSUE TITLE
Setup Domo Dashboard for Find a Rep Performance

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83360]
## Background
We have been asked to create a framework for our Domo Dashboard for Find a Rep performance, so Mason knows what information we're interested in seeing.

## Tasks
- [ ] Set up a dashboard outline using text cards
- [ ] Share with Mason, to replace text cards with real data

## Acceptance Criteria
- [ ] A dashboard outline has been created in Domo, to help guide which metrics we're looking to track and how we'd like that laid out.

**Comment by oddball-lindsay** [comment]
Here's the outline, can adjust later: https://va-gov.domo.com/page/1897961687
