### ISSUE TITLE
GitHub personal access token for SOCKS access [Footer Ticket 82831]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83372]
## Issue Description
[The docs for configuring the SOCKS Proxy](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-PrerequisitesPrerequisitesforSOCKSProxyconfiguration) should be updated.  
Under "Prerequisites for SOCKS Proxy configuration":

> If you don’t have git configured on your computer, create a GitHub Personal Access token with at least "repo" scope permissions using [these instructions](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token).

GitHub now has [two different types of personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#types-of-personal-access-tokens), fine-grained and classic. The above instructions seem to be talking about the classic token, but I believe that GitHub is trying to push more folks to using the fine-grained option as it is the more secure option.

It will be helpful to provide a bit more guidance on which option is preferred by the Platform Team, and to tell users how they should configure their token, such as:
* a suggested expiration date, based on input from security folks (this would be helpful for either token type)
* if fine-grained is preferred:
  * which repositories the token needs access to (rather than providing access to all repositories)
  * which repository permissions are needed
  * which account permissions are needed

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy

---
## Tasks
- [x] Connect with Christopher Floess/Jennifer Brown
- [x] Edit page to include new guidance on GitHub personal access token
- [x] Check for Launch Blocking issues

## Acceptance Criteria
- [x] Page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laucon** [comment]
I believe this is done and that the edits made cover all the issues presented in the ticket. The document now tells users which type of token they should use (classic; not fine-grained). And since it's not fine-grained, the issues listed under "if fine-grained is preferred" are not applicable. And I think that mentioning how the token will be used for a very short time, which we did in the document, covers the part about an expiration date.

**Comment by jknipes** [comment]
Work is finished, moving to _done_
