### ISSUE TITLE
Updates to Downtime notifications page [Footer Ticket 79082]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83375]
## Issue Description
Per the instructions in [ticket 79082](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79082) we need to update this page

---
## Tasks
- [x] Make changes to page as described in footer ticket
- [x] review with SME for accuracy
- [x] check page for Launch Blocking issues

## Acceptance Criteria
- [x] Updates made and page ready for deployment

## SME
 - @acrollet 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by CherylEvans** [comment]
@Adrian Rollett @jknipes 
I am working on ticket [83375](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/83375) regarding making the updates from ticket [79082](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79082) (Updates to Downtime notifications page)
Here is my [Draft](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3192356876/Cheryl+Draft+83375+79082+-+Copy+of+Downtime+notifications+2) page with the updates you requested. Once you review and approve the changes, I’ll publish the page. Thank you!

**Comment by CherylEvans** [comment]
@acrollet @jknipes I made the changes to the source page. The updates will be published when we run SVP at 3:30 PM ET.

**Comment by CherylEvans** [comment]
@acrollet @jknipes Platform page is updated successfully; closing ticket.
