### ISSUE TITLE
[DevOps] Fix Dependabot PR permissions errors in `chip` repo.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#83377]
## Description

e.g.

```
Run aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
  with:
    aws-region: us-gov-west-1
    audience: sts.amazonaws.com
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

Might be better just to roll this into the AWS account migration.

## Tasks
- [x] [DevOps] Figure out why this is happening.
- [x] [DevOps] Fix it.

## Acceptance Criteria
- [x] Dependabot PRs run all tests successfully.

**Comment by ndouglas** [comment]
Fixed. No need for Dependabot to do anything with AWS credentials, and that (access to secrets) was what caused the problem.
