### ISSUE TITLE
Add a new feature flag for CC direct scheduling implementation.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#83383]
## Item Description
We will need to create a feature toggle for CC direct scheduling implementation.

---

## Tasks
- Add `va_online_scheduling_cc_direct_scheduling` feature toggle

## Acceptance Criteria: 
- [ ] The toggle is created for VAOS CC direct scheduling

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated
---
