### ISSUE TITLE
Write script for bulk uploading CSV file to GitHub issue tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83388]
## User Story
As a Governance team members, I want to have a reliable and consistent way of transforming the CSV file generated from the DraftingTemplate to actual Staging Review issue tickets so that I can take on this task as part of my on-support work and no longer have to rely on my PM.

Assignee: @it-harrison 
Peer Reviewer: @shiragoodman 

## Description
For the last 2+ years, Governance team has generated the Staging Review issue tickets in bulk by running a script called CSVTools in command line node.js. Unfortunately, the script is no longer maintained, so when @shiragoodman tried to train the rest of Governance team on how to do it, she was unsuccessful.

However, Governance team member @it-harrison believes there is an alternate path we could take that would involve writing a script that reads a CSV file and uses date to hit the Github API to create new issues. Per Ian, "This script could be a CLI tool but with minimal extra work it can be a small desktop app that makes it easier and more stable to use."

In order for all Governance team members to be able to support the creation of SR issue tickets, in this sprint we will explore utilization of the GitHub API to create an alternative path.

## Tasks
- [x] Write a new script
- [x] Test it
- [x] Verify it works for other Governance team members
- [x] Document how the script works, how to maintain it, addressing bugs, etc.
- [ ] ~~Document instructions for the Governance team to follow to upload the CSV file in order to create the issue tickets~~ Removing this from scope. If solution works, we will update the Governance team guidance for creating issue tickets in a later ticket.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have an alternate path for creating Staging Review issue tickets in bulk from the CSV file generated from the DraftingTemplate

## Team Notification
- [x] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@shiragoodman I have finished a draft of the tool. To use, visit this [folder](https://drive.google.com/drive/folders/1FjdXmf07RsRF0kKoYtyu6XbMyoFB-O8g) on our Team's Google Drive and choose the folder that corresponds to your OS/Architecture (I know you are on windows and there is only one option for that). For windows, download the `.exe` and run it. There will be some security warnings because the app does not have any official approval from Microsoft or Apple.

After you start the app you will need to add your GH token (adding the token should persist across opening and closing the app, but it's not working yet). Then choose a file. You will only be able to open `csv` files...but on windows you may need to have a `.CSV` files (extension in caps).

**Comment by shiragoodman** [comment]
thanks @it-harrison . I'm going to give this a try today. I'll let you know if I run into any issue or if I have questions. Thanks!

**Comment by shiragoodman** [comment]
@it-harrison what is the status of this? I saw you completed some more test runs this morning. Are you able to share the doc you created on the app and how to maintain it? ty

**Comment by it-harrison** [comment]
@shiragoodman, @erinrwhite, @rferguson13, @allison0034, @briandeconinck 
I have updated the app to take into account feedback from the demo: 
* milestone url / copy url feature included
* better error reporting for parsing errors and github issue creation errors
* DST SR review toggle added
* validated that uploading real csv data from drafting template works
* tested uploading 70 tickets in one csv successfully (caveat: there _is_ a GH rate limit that kicks in if you upload more than 20 tickets in a short period of time, eg on the order of a few seconds. I built in some "sleeps" that _should_ circumvent this.)

Access the app for your OS/Arch combo here: https://drive.google.com/drive/folders/1FjdXmf07RsRF0kKoYtyu6XbMyoFB-O8g

**Note for Mac users**: unzip the folder and then open the app from its contents.

**Comment by it-harrison** [comment]
This issue will carry over for gov team members to test the app

**Comment by erinrwhite** [comment]
I was able to install and test the app! Created issue #85569 and removed all tags after ticket was generated.

**Comment by shiragoodman** [comment]
Per @erinrwhite at standup:

> Only advice I have is for Mac users: you need to have admin on your machine to install the app, and you might need to follow the steps to “add an app from an unidentified developer" https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by shiragoodman** [comment]
@it-harrison, per standup, please work on a maintenance doc for this app. We need to know what it is, what it's used for, how its maintained. We should also come up with a name for it since it'll be a tool that works alongside the DraftingTemplate. LMK if you have any questions.

**Comment by shiragoodman** [comment]
@allison0024 @briandeconinck as I said in standup, please help verify that this tool is working for you and you are able to complete a bulk upload. In short, these are the steps you need to complete:
1. Download the CSV file from a recent Staging Review (possibly contention classification on 6/4?)
2. Edit the CSV to remove the labels and the milestone. We don't the VFS team to be notified and we don't need our data skewed with additional labels. Add the `governance-team` label in it's place. 
3. Following the instructions in Ian's app, run the upload with your CSV file.
4. Verify that the gh issue ticket was created successfully. 
5. Share your test ticket in the comments of this ticket. (see Erin's post above).

please let me know if you have any questions or run into any issues. Please try and have this completed by EOD 6/12.

**Comment by it-harrison** [comment]
@shiragoodman: I have created a [guide](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3221946370/Guide+to+the+Drafting+Template+Issue+Uploader) to using the app

**Comment by erinrwhite** [comment]
@it-harrison I went through and added some additional info in the comments based on my installation experience, hopefully helpful!

**Comment by shiragoodman** [comment]
Thank you for creating the guide @it-harrison, however it isn't exactly what I had in mind. Don't sweat it - I think we have what we need to move forward and I appreciate the effort. FWIW, I was looking more for a technical spec on the tool you built and less of a how to guide. I'll take responsibility here - I don't think my ask was very specific.

I added a couple comments to the guide, and I also retested the tool. It worked on the first try. The only thing of note is that my test file didn't have a milestone. The milestone url that was generated gave a 404. It's clearly not a big problem - I'm just glad to see that it worked w/o a milestone. 

This is going to be very helpful moving forward! Thank you for all of your effort.

**Comment by allison0034** [comment]
@it-harrison I get this when I try to run the app.<img width="496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fdbbfa6b730ea6f11ccded2e49ca1f487bdc7872/Screenshot%202024-06-12%20at%2010.42.50%E2%80%AFAM.png" alt="Screenshot 2024-06-12 at 10.42.50 AM.png" />

**Comment by allison0034** [comment]
Erin helped and I was successful with the upload!

**Comment by shiragoodman** [comment]
@briandeconinck You're the last team member who needs to test and verify that the tool works for you. Please let me know when you're able to get this done. Thank you!

**Comment by briandeconinck** [comment]
Commenting here for end-of-week status -- Still not working on my machine (Windows), Ian is troubleshooting!

**Comment by shiragoodman** [comment]
@briandeconinck @it-harrison - what is the status of this app working on Brian's machine? I'd like to get this ticket closed out ASAP. thank you.

**Comment by briandeconinck** [comment]
Update: My issues were (at least in part) the result of user error... My test CSV file wasn't correctly formatted, still unclear why it generated the errors that it did --- but I'm now clear on what I was doing wrong and the tool works as intended!
