### ISSUE TITLE
[FE] My VA Forms Status: System error handling

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#83395]
## Background
We need to be able to handle system errors on the frontend. The BE aspect of this work is being handled in #81901.

Note that for the current iteration of the Benefit Application Drafts section, the data for saved applications is gathered from the same API as the main user call. Therefore, there are [no errors](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-application-drafts-use-cases.md#edge-cases) (currently) specific to just this section. If the main user call fails, the entire My VA page displays an error, in which case we follow the behavior outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/system-cant-connect-to-MPI.md), for a full page error.
 
## Tasks
- [x] Team discussion on error states (8/29 at 2pm et)
- [x] Work with BE and design to identify the types of system errors that can occur (see #81901, and updated [BE documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/form-status/backend_documentation.md))
- [x] Determine technical approach for handling system errors in this section
- [x] Work with AJ or Alex to create additional ticket(s) for implementation as needed

## Acceptance Criteria
- [x] We know how we'll implement handling system errors on the frontend

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_: Dev and Design
- _How can this work be validated?_ : Tom, Daniel, Allison and Matt can confirm how we'll handle system errors on the FE

**Comment by ajakabcin** [comment]
Summary from our discussion today

1. system error scenarios as outlined by Tom in [81901](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81901) and in [BE docs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/form-status/backend_documentation.md) (handled as: standard "in section" error message)
2. account for partial failures in FE logging (so we're capturing what is failing when) while presenting the user with the standard total page failure message
3. handle 296 errors with standard full page error
4. if submission forms fail in any capacity (i.e. we can't pull a status but we know there are forms to show) default to standard "in section" error message

**Comment by ajakabcin** [comment]
Closing this out - subsequent tickets created to handle error implementation:

- #92130 
- #92131
