### ISSUE TITLE
Breakout Something Else and Other Data in Looker

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83396]
## Description 
At the moment a majority of our work is classified as "Something Else" or "Other". We'd like to know if there are trends that could establish new topics and allow us to have more granular data.

You can use this spreadsheet to identify trends: https://docs.google.com/spreadsheets/d/1ED42gcy2akssAYUIPaYhOySeEyRZ9Hh02gzslVR2H5s/edit#gid=333744496

Analyzing October 1st to May 14th when the data was pulled.

---

## Definition of Done
All tasks below are complete

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify the best way to sort for Something Else and Other tickets
- [x] If no other way, we can sort current tickets by Something Else Topic here: https://docs.google.com/spreadsheets/d/1ED42gcy2akssAYUIPaYhOySeEyRZ9Hh02gzslVR2H5s/edit#gid=333744496
- [x] Identify the best way to sort the data that would allow us to create additional topics 
- [x] Document findings here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/3166502936/Findings+Something+Else+Category+in+Looker

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by davidpetras** [comment]
Complete
