### ISSUE TITLE
Document Tier 1/Tier 2 support process for Product Directory 

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#83407]
## Issue Description
As support for the product directory is handed over to OCTO, a support category will be created with Anne Kerr as the tier 2 for that category. We need to ensure that Tier 1 understands when they need to point to documentation, vs when they need to escalate a request to Anne. A document needs to be written to explain the processes on the product directory and what decisions should be made given the nature of the request:

Request an update to an existing product -> Point to GitHub issue form for update requests.

Request a new product addition -> Collect a product name and a path to the code in vets-website, then Escalate to Tier 2 with those details included.

Request a new type of information be tracked -> Inform them that the product directory is currently not developing any new features as there is no engineering team assigned to it. 

Request a field not on the GitHub issue form be changed -> Inform the customer that these fields are updated automatically from the code and are not user-generated.

---
## Tasks
- [x] Write up document explaining the decision-making process for Tier 1 support.
- [x] Send document to Alyssa

## Acceptance Criteria
- [x] A document is officially added that explains the responsibilities of Tier 1 and Tier 2 support for the product directory.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/PTST/pages/3168993322/VFS+Product+Directory+Platform+Support+Tickets Document is here in support's documentation. Category and team have been added to the support bot.
