### ISSUE TITLE
Diagnose and fix Unit Test Stability review triggering erroneously

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#83408]
## Issue Description
There are numerous accounts of the Unit Test Stability Review running in circumstances when it should be skipping. This results in the checks running, but not running any tests, and therefore the reporting fails as there are no results. While this is not blocking any merges, it still raises a lot of questions from engineers that may not understand this is not blocking them. The conditions under which this workflow runs should be examined for any gaps.

Example of this taking place: https://dsva.slack.com/archives/C04868KS69L/p1715893013529389

Another example: 
https://github.com/department-of-veterans-affairs/vets-website/pull/29784

---
## Tasks
- [x] Investigate why the unit test stability review is triggering when there are no tests needing to be verified.
- [x] Correct any conditional statements that are not functioning properly.

## Acceptance Criteria
- [x] The unit test stability review no longer runs when not necessary.

**Comment by CBonade** [comment]
The root of the problem seemed to be stemming around the changing of src/platform files, where tests for those directories were being selected, however, the actual stability review was set to only stability check unit tests in the src/applications directory. This lead to it not skipping the check (because platform tests WERE selected) but then the actual test runner script was skipping them when it got to them, resulting in nothing being done.
To ensure this was fixed, I tested it by forcing a change (that i backed out before merge) on an scss file in the site-wide folder under src/platform and it successfully got a bunch of unit tests to run.
