### ISSUE TITLE
SC | General cleanup & fix flaky e2e test

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#83404]
## Value Statement
**_As a_**  member of the decision reviews team
**_I want to_** clean up the Supplemental Claim code
**_So that_** I can reduce future maintenance

## Background Context

After reviewing the design system work to change the base font size, I noticed:
- Some margins/padding that needed tweeking
- Some unused CSS that needs to be cleaned out
- A persistently flaky e2e tests that only fails on first run

To fix:
- Review the [design of the evidence summary page](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=0-2532&t=tpygwkLv7Duqy9BH-0). Specifically look at the spacing between the text and the edit/remove button.
- The evidence uploads needs a "Delete" button (not "Remove")
- CSS for non-web components needs to be removed
- Flaky e2e test ends up being a url check of `add-issue?index=`, but the `?index=` isn't present when adding a new issue - ended up splitting out the maximal e2e test since it takes a lot longer to run than the other 3 combined.

## Tasks
- [ ] Fix spacing on evidence summary page
- [ ] Fix "Delete" uploaded file button text
- [ ] Remove unused CSS
- [ ] Fix flaky maximal e2e test
- [ ] Check unit tests

## Acceptance Criteria
- [ ] Evidence summary page matches design
- [ ] All tasks complete
- [ ] All tests passing
- [ ] E2E test is _less_ flaky

## Definition of Ready 
- [ ] Devs have access to Pager Duty as needed for implementation
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
