### ISSUE TITLE
Consolidate /submit and Toxic Exposure feature flag

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#83405]
## Issue Description
Currently there are two separate feature flags for Toxic Exposure work and the Lighthouse /submit migration:
- disability_compensation_lighthouse_submit_migration
- disability_526_toxic_exposure

We want to consolidate these feature flags for the release of the 2022 526ez form / Toxic Exposure 1.0 release.

---
## Tasks
- [x] check unit tests have the correct feature flag name - disability_526_toxic_exposure
- [ ] check [flipper disable list in platform docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)
- [ ] run flipper remove command in Argo for each environment (production included)

## Acceptance Criteria
- [x] remove disability_compensation_lighthouse_submit_migration
- [x] disability_526_toxic_exposure is the only feature flag for the /submit migration and TE release
- [ ] the flag does not appear in https://api.va.gov/flipper/features
- [ ] e2e test in staging
---

Notes:
- either team could do this, but T-rex may have more knowledge to do this but inform team 2 the work is done?
- which one do we want to keep? do we want to keep the feature name or functional name? maybe Toxic Exposure flag since it's used in the front end
- effort could be low - find & replace name of the flag we want to keep - unit tests will need to be updated with the correct flag name or else they will break
- if we don't do this work we will have 2 separate flags to maintain. value add: simplify logic, only have one feature flag for the release. if we have 2 flags during the rollout using % with 2 versions of the form, each flag would get different users assigned.
- this could /should be done before we test the iteration 4 e2e test
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
-

**Comment by sethdarragile6** [comment]
Flipper flag `disability_compensation_lighthouse_submit_migration` removed in dev, sandbox, staging and prod, via [these instructions](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles)
