### ISSUE TITLE
Schedule and Host Meeting with Curt and Kerry on PR Bot Plan

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83413]
## Description 
This ticket will house the task of running our PR bot plan by engineers who have handled the Support Bot. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Alyssa to send a group chat to set up meeting
- [ ] [Brenden to write out exact workflow for PR Bot](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3166076958/PR+Bot+Workflow)
- [ ] Discuss plan for PR bot with Curt and Kerry to establish if there are any red flags
- [ ] If good to proceed, move onto this ticket: 
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
