### ISSUE TITLE
Create Spreadsheet for Storage of PR Bot Data

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83414]
## Description 
This ticket will house the task of creating a spreadsheet that will house PR Bot responses to tickets that have not met PR requirements for submission. It will be a similar storage system to this: https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit?pli=1#gid=0

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

- [ ] Gain access token from SNOW ticket
- [ ] Test PR Bot 
- [ ] Add any other tasks here that Curt/Kerry might have mentioned on the previous call to this list [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/83413)
- [ ] Create spreadsheet that stores PR data based on feedback from Curt/Kerry

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Duplicate ticket. Resurrecting this task with more complete AC here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/94262
