### ISSUE TITLE
Binstubs For Running Server & Managing Docker Containers

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#83411]
## Summary 

In addition to setup, testing, and linting. Developers will need to be able to run the API locally for testing and development. Some developer need to manager the docker setup for developing the website. 

## Related Issue

- https://github.com/department-of-veterans-affairs/vets-api/pull/16781
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74660

## Tasks 
- [ ] Create a binstub for starting the rails server (locally)
- [ ] Use foreman & Procfile to start the processes required for running the server 
- [ ] Create a binstub for managing docker containers such as building and rebuilding
- [ ] Add documentation for "Running Binstubs" 

## Acceptance Criteria 
- [ ] `bin/dev` starts the rails server for native, hybrid, docker 
- [ ] `bin/docker` can build, clean, setup for ci, run db and bundle commands 
- [ ] each binstub has a help message
- [ ] documentation is added for "Running Binstubs"

### bin/dev

bin/dev sets up and starts the development environment based on the configuration specified in the .developer-setup file. The following configurations are supported:

- native: Starts the web and job processes
- docker: Starts the docker process (docker-compose up)
- hybrid: Starts the web, job, and deps (clamav postgres redis) processes

### bin/docker 

- Prune and rebuild Docker images
- Stop and build Docker images without cache
- Stop all running Docker containers
- Start Docker containers in the background
- Start the Rails console
- Bundles ruby gems
- Prepares the database for development and test environments
- Prepare docker environment to run bin/test --ci
- Display this help message
