### ISSUE TITLE
Draw up design-doc-type document describing move to Redux Toolkit

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#83427]
## Issue Description
The Front End COP wants to convert the current React redux structure to using Redux Toolkit, as is recommended officially by Redux as the best way to do it. In order to make this switch, we need to detail a document with what the changes are and why we want to make them, and get it over to our OCTO PO for approval. The document should contain everything in the notes in [this thread](https://dsva.slack.com/archives/C04868KS69L/p1715884705334819), as well as any relevant images or examples we want to provide.

---
## Tasks
- [x] Draw up document explaining the switch we want to make to Redux Toolkit.
- [x] Present to Jeff Keane for approval.

## Acceptance Criteria
- [x] Our request for a different approach to redux has been submitted for approval.
