### ISSUE TITLE
[FSR] Review page missing values

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#83421]
## Description
A number of fields on the final review page are showing blank or incorrectly. This could be related to the recent review navigation changes. 

| Veteran Information Chapter | Asset Chapter | Expenses Chapter | 
| --- | --- | --- | 
| <img width="578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b45267755d1af83d59909a01c1c771c3b2efecc9/image.png" alt="image.png" /> | <img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmp4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3788846ab16d3334584ac83203137c83e1cd3dd1/image.png" alt="image.png" /> | <img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm54QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc844a66bc8a16270fd446c7302be5bc3d70dffd/image.png" alt="image.png" /> |

## Tasks
- [x] Identify root cause of visual bug
- [ ] Disable `financial_status_report_review_page_navigation` feature flag if necessary
- [ ] Fix visual issue
- [ ] Create follow on ticket to generate e2e test that will confirm review page functionality 

## Acceptance criteria

- [ ] Review page is displaying correctly 

## Testing
- [ ] Run through FSR with the conditions listed below

Testing procedure:
To recreate: run through a full FSR with the following conditions:
 - No spouse
 - 0 dependents
 - No vehicles
 - No recreational vehicles
 - No credit card bills
 - No installment contracts

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
We currently have  issues with components using the old import format `YesNoField and example: (import VaTextInputField from 'platform/forms-system/src/js/web-component-fields/VaTextInputField';)`. These components needed to be updated to use the new `yesNoUI `from `platform/forms-system/src/js/web-component-patterns `and corrected import statements to ensure proper functionality.


Update to Use `yesNoUI`: Change components to use `yesNoUI `from web-component-patterns.
Correct Imports: Update import statements to correctly import modules from assets.

Change from the old Yes/No UI field to use yesNoUI from web-component-patterns.
```javascript

// pages index.js
import { vehicles } from './assets/vehicles';

// vehicles.js (example for vehicles component)

import { yesNoUI } from 'platform/forms-system/src/js/web-component-patterns';

const title = 'Do you own any cars or other vehicles?';

export const vehicles = {
  uiSchema: {
    'ui:title': () => (
      <>
        <legend className="schemaform-block-title">
          <h3 className="vads-u-margin--0">Your cars or other vehicles</h3>
        </legend>
      </>
    ),
    'ui:options': {
      forceDivWrapper: true,
    },
    'view:hasVehicles': yesNoUI({
      title,
      enableAnalytics: true,
      required: true,
      uswds: true,
    }),
  },
  schema: {
    type: 'object',
    properties: {
      'view:hasVehicles': {
        type: 'boolean',
      },
    },
  },
  review: data => ({
    [title]: data['view:hasVehicles'] ? 'Yes' : 'No',
  }),
};
```
Correct Import Statements:

Update import statements in index.js to ensure proper module import.
```javascript

// index.js
import { vehicles } from './assets/vehicles';

export {
  vehicles,
  // other exports...
};
Update Usage in Configuration:

Correctly reference updated modules in the configuration file.
javascript
Copy code
// householdAssetsChapter.js
import { vehicles } from '../../pages'; // Correct import for vehicles

const formConfig = {
  householdAssetsChapter: {
    title: 'Household assets',
    pages: {
      vehicles: {
        path: 'vehicles',
        title: 'Vehicles',
        uiSchema: vehicles.uiSchema,
        schema: vehicles.schema,
        depends: formData => !isStreamlinedShortForm(formData),
      },
      // Other pages...
    },
  },
};

export default formConfig;
```

This update involves changing components to use the new yesNoUI pattern and correcting import statements to ensure proper functionality across the application. This affects all components using the old format, not just the vehicles module.

**Comment by amponce** [comment]
One more thing to note:  we still need to figure out required fields and the schema currently does not match what we had before so that also needs to be fixed
