### ISSUE TITLE
Exploration: EKS+Terraform+Helm

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#83437]
## Issue Description
Dive into documentation and some small tutorials to help make sense of both some of our existing Terraform patterns, and investigate patterns/best practices for using Helm and Terraform

## Tasks
- [ ] [This Terraform/EKS Tutorial](https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks)
- [ ] [This Terraform/Helm Tutorial](https://developer.hashicorp.com/terraform/tutorials/kubernetes/helm-provider)
- [ ] Analyze and understand patterns used in [prt-preview-manifest](https://github.com/department-of-veterans-affairs/prt-preview-manifest/tree/main/terraform)

## Acceptance Criteria
- [ ] Finish tutorials and have a greater general understanding of Terraforming EKS and Helm

**Comment by ryan-mcneil** [comment]
Duplicate Ticket (Thanks, Zenhub)
