### ISSUE TITLE
Implement PDF Generation for Lighthouse Submissions

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#83430]
## Issue Description

When 526 Data Submission to Lighthouse API is implemented, we need to generate PDFs using the Lighthouse GeneratePDF endpoint. 

---
## Tasks
 - [ ] Identify the code that requests and submits the form PDF for 526EZ
 - [ ] Update the code to conditionally generate PDF using the code introduced by [#16411](https://github.com/department-of-veterans-affairs/vets-api/pull/16411) Ticket #80773
   - Condition driven off of submission endpoint indicator implemented by [PR #16693](https://github.com/department-of-veterans-affairs/vets-api/pull/16693) Ticket #81830
 - [ ] implement spec tests 
 
## Acceptance Criteria
 - [ ] PDFs created for primary submission path by Lighthouse when submission endpoint is Lighthouse
 - [ ] 100% Passing spec tests
 - [ ] 90% testing line coverage of new code
 

Breadcrumbs:
- [Benefits Claims Service Implementation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_claims/service.rb) 
- [Comment from Aurora Hampton](https://dsva.slack.com/archives/C04KW0B46N5/p1715970238182679?thread_ts=1715970009.310009&cid=C04KW0B46N5) 
- [Disability Compensation Claims Documentation](https://developer.va.gov/explore/api/benefits-claims/docs?version=current)

**Comment by tblackwe** [comment]
@SloopKoning Can you please pickup this ticket?

**Comment by SloopKoning** [comment]
If the 5,518 ruby files in the `vets-api` repo here are the files that have the key phrases 526 and submit that are not migrate, swagger and spec:
./app/sidekiq/evss/disability_compensation_form/submit_form526_cleanup.rb
./app/sidekiq/evss/disability_compensation_form/submit_form526_all_claim.rb
./app/sidekiq/evss/disability_compensation_form/submit_form526.rb
./lib/sidekiq/form526_backup_submission_process/submit.rb

**Comment by tblackwe** [comment]
We had some communications confusion which led to me erroneously creating this ticket.
Under the current plan (Lighthouse Synchronous Endpoint) we do NOT need to implement calls to the generatePDF endpoint for primary submissions. It will only be used for backup submissions, which is captured by ticket #82245 

Closing this ticket as it is not needed. TY for the work and due diligence @SloopKoning
