### ISSUE TITLE
Exploration: Terraforming EKS

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#83438]
## Issue Description
Spend some time get a better understanding of patterns/best practices for terraforming EKS, and use newfound knowledge to better analyze current TF patterns so that it can be applied to GIDS

## Tasks
- [ ] Tutorial: [Terraform EKS cluster](https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks)
- [ ] Analyze patterns used in Terraforming [Preview Envs](https://github.com/department-of-veterans-affairs/prt-preview-manifest/tree/main/terraform)

## Acceptance Criteria
- [ ] Tutorial complete
- [ ] Has a better understanding of existing Terraform
