### ISSUE TITLE
SNOW Onboarding and Discovery

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#83447]
## Issue Description
There is a VADOTGOVDEVOPS queue in SNOW (Service Now) that receives issues related to VA.gov usage by Veteran VA employees and employees who are assisting Veterans. There isn't a great process or system in place for handling these issues, including determining if more queues are needed for specific groups with the Office of the CTO. Therefore, the Veteran Support Team will do the necessary discovery work to determine how to handle VA.gov Technical Support issues that come in through SNOW and create recommendations for new OCTO queues. 
---
## Tasks
- [x] Request SNOW access for @Jcorcoran9 and set him up as backup queue manager
- [x] @Jcorcoran9 review and research SNOW instance to determine processes for handling issues
- [x] @clantosswett determine initial recommendation for CTO queues 

## Acceptance Criteria
- [x] @Jcorcoran9 has access to SNOW and is set up as backup queue manager
- [x] Completed review of SNOW with any necessary follow up questions answered
- [x] Final recommendation on new CTO SNOW queues and socialization with the relevant groups
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Requested SNOW access for @Jcorcoran9. Will wait a few days before following up on request.

**Comment by clantosswett** [comment]
Scheduled a meeting with OCTO POCs to discuss which groups should have their own queues set up in SNOW. Meeting scheduled for 5/29.

**Comment by Jcorcoran9** [comment]
Spoke to @Kimberley2023-CSM about addressing issues within snow.  We will meet next week to identify any additional steps. If any are needed they will be in a new ZenHub ticket.
