### ISSUE TITLE
Refine previous PCIU tickets

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#83458]
A new plan was initiated after meeting with Authenticated Experience team. Product and AE team agreed on how to approach the VaProfile::ContactInformation upgrade and PCIU teardown. 

### Tasks
- [x] Create epic for creating new V3 service
- [x] Refine replacing PCIU tickets
- [x] Create epic for PCIU teardown

**Comment by LindseySaari** [comment]
Since we have the refinement session on our calendars for Wednesday, it's probably safe to check the box and close this ticket out @RachalCassity @jennb33
