### ISSUE TITLE
Ensure all orientation sessions include referenced links in YouTube description

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83457]
## User Story
As a VFS team member, I want to be able to access the links referenced in the orientation session so that I can learn more about the process. 

Assignee: @rferguson13 @erinrwhite @it-harrison @briandeconinck @allison0034 
Peer Reviewer: see assignments below

## Description
_This issue has been opened per Platform Website feedback ticket #82685._

The purpose of this ticket is to review the orientation videos that are currently shared on Platform Website/YouTube. If there is any mention of links, we need to ensure that the link is shared in the YouTube description.

## Impacted Artifacts
All YouTube videos

## Tasks

> assignee / peer reviewer

- [x] View the orientation session recordings
   - [x] General Orientation - @rferguson13 / @erinrwhite 
   - [x] Accessibility Orientation - @it-harrison / @allison0034 
   - [x] QA Orientation - @briandeconinck / @rferguson13 
   - [x] Design & Research Orientation - @erinrwhite / @briandeconinck 
   - [x] Design System Orientation - @briandeconinck / @erinrwhite 
   - [x] Analytics Orientation - @allison0034 / @it-harrison 
   - [x] Frontend Orientation - @erinrwhite / @allison0034 
   - [x] Backend Orientation - @allison0034 / @it-harrison 
- [ ] If any link is mentioned, add the title of the link/page/document and the url to the YouTube description. It should look like this:
   - Page name: www.viewthispage.com

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All links mentioned in orientation sessions videos are available via the YouTube description

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@shiragoodman I am wondering if we can just link to Platform website for the areas that have pages out there. I know for design, everything we talk about in that slide and links should be on [Platform website](https://depo-platform-documentation.scrollhelp.site/research-design/).

**Comment by allison0034** [comment]
Or at the very least add that link : )

**Comment by allison0034** [comment]
@shiragoodman do you have a link you can put in this ticket on how to edit the YouTube decription?

**Comment by allison0034** [comment]
@it-harrison Analytics and Backend should be updated with links. Please peer review.

**Comment by shiragoodman** [comment]
> @shiragoodman I am wondering if we can just link to Platform website for the areas that have pages out there. I know for design, everything we talk about in that slide and links should be on [Platform website](https://depo-platform-documentation.scrollhelp.site/research-design/).

@allison0034 yes, please link out to Platform Website in the YouTube description. Everything linked should be publicly available (eg Platform Website or VADS), OR it should be only accessible to those with permissions (eg GitHub links)

**Comment by shiragoodman** [comment]
> @shiragoodman do you have a link you can put in this ticket on how to edit the YouTube decription?

@allison0034 not sure I follow. Are you asking for instructions on how to update the YouTube description?

**Comment by erinrwhite** [comment]
@briandeconinck:
 - I reviewed [Design System and Forms Library orientation](https://www.youtube.com/watch?v=ZsAcoAfs4cU) - looking good 👍🏻 
 - [Research and design orientation](https://www.youtube.com/watch?v=WrM2t6wQvSw) is ready for your review

@allison0034 
 - [Frontend orientation](https://www.youtube.com/watch?v=M-pPhWzltYM) ready for your review

**Note:** I had good luck finding the Google Drive files for these orientation sessions and copy/pasting links from there rather than hunting them down. It is worth a search in your Google Drive to save some time. cc @rferguson13 @it-harrison

**Comment by allison0034** [comment]
@erinrwhite Frontend looks good!

**Comment by it-harrison** [comment]
@allison0034 Analytics and BE look good!

**Comment by briandeconinck** [comment]
@erinrwhite Research and design looks good, except for the [very last link of the presentation](https://youtu.be/WrM2t6wQvSw?feature=shared&t=1880) which I didn't see in the video description -- the "slack workflow" link, which I'm honestly not sure what it links to. @allison0034 any idea what that link is for?

**Comment by erinrwhite** [comment]
@briandeconinck Yeah, I left that one out because I didn't think it was valid anymore! But I might be wrong 😬

**Comment by erinrwhite** [comment]
@briandeconinck Added a link to the vfs-platform-support channel!

**Comment by briandeconinck** [comment]
@erinrwhite Works for me!

**Comment by rferguson13** [comment]
@erinrwhite - General orientation is ready for review. It's a bit of a doozy...

**Comment by erinrwhite** [comment]
@rferguson13 reviewed [General Orientation](https://www.youtube.com/watch?v=PNuy0YmrXlI)! there were a couple links missing (CAIA, #vfs-platform-support) that I went ahead and added in. All others looking good. 👍🏻

**Comment by rferguson13** [comment]
@briandeconinck - QA orientation looks good.

**Comment by it-harrison** [comment]
@allison0034 - a11y is ready for your review!

**Comment by rferguson13** [comment]
@it-harrison - I covered for Allison. Looks good! Just added the links to the Slack channels.
