### ISSUE TITLE
[DevOps] Create `terragrunt`-based GHA workflow in `checkin-devops`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#83467]
## Description
These should replace the current Terraform workflows, but for the time being should live alongside them.

## Tasks
- [x] [DevOps] Add new `terragrunt.yml` workflow.

## Acceptance Criteria
- [x] `terragrunt.yml` workflow exists:
  - [x] on pull request, checks format, verifies, and plans
  - [x] on workflow dispatch, checks format, verifies, and plans
  - [x] on master, runs apply 
  - [x] on workflow dispatch, checks format, verifies, plans, and applies if enabled

**Comment by ndouglas** [comment]
This is in place now and working correctly.
