### ISSUE TITLE
EVSS Report Data Review 

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#83465]
## Issue Description
EVSS has a large backlog and it is unclear how many of the issues can only be resolved them or if there are issues that were routed incorrectly that the Veteran Support Team can help with. We will conduct a review of EVSS open issues to determine how we can best support the team in tackling their backlog.
---
## Tasks
- [x] Analysis of EVSS open tickets in Salesforce
- [x] Reporting out to Chante and EVSS leadership on the results of the analysis

## Acceptance Criteria
- [ ] Reporting out to Chante and EVSS leadership on the results of the analysis
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by newworld2616** [comment]
[EVSS Open CasesNew.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2I3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a187ecc3d27beb9bb1894c9e1bc12efbb6ad1bb/EVSS%20Open%20CasesNew.xlsx)

**Comment by newworld2616** [comment]
Hello @clantosswett , I have attached the excel sheet that has three tabs that has all EVSS open cases. I chose the start date from 01/01/2024- 05/20/2024 for the open cases. There is also Pivot table that gives overview of the case categories and case types. Let me know if you have any questions. Thank you!

**Comment by clantosswett** [comment]
@newworld2616 Thank you for doing this so quickly. I am going to share with the EVSS team. Could you also pull this same report but include case descriptions as well and share with me over teams since it might include PII? Thanks!

**Comment by newworld2616** [comment]
@charlottecesana, sure thing, I will share the data via teams. Thank you!
