### ISSUE TITLE
Create JWT for GitHub App and Trigger Workflow 

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#83470]
## Issue Description

A .pem file is used by the GitHub Apps (associated with prt-preview-manifest-prb repo) to authenticate the Control Plane and allowing the Control Plan to trigger workflows such as deploy-environment within the prt-preview-manifest-prb repo. The content of the .pem file is sensitive and should be securely stored and accessible to the Control Plane

---

Currently this is only working withe local development and needs to be done on the control plane server. 

### Related/Dependent Issue

- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82773

### Tasks

- [ ] Update the Github::Workflow#private_key method to use the certificate generated in the related issue

### Acceptance Criteria

- [ ] A valid JWT is generated using the certificate 
- [ ] A workflow is triggered using the generated JWT
