### ISSUE TITLE
[DevOps] Rename `terraform` to `terraform-cms` in `checkin-devops`

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#83471]
## Description
... with appropriate other renaming operations.

## Tasks
- [x] [DevOps] Rename `terraform` to `terraform-cms`.
- [x] [DevOps] Change workflows to target `terraform-cms` only.

## Acceptance Criteria
- [x] Things still work.

**Comment by ndouglas** [comment]
This is in place now and working correctly.
