### ISSUE TITLE
Required BGS Field Mapping for 686 Submission

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8349]
## Goal
Several fields that were recently uncovered that need to be triaged and addressed so that there is a better chance of completion for a submitted payload.

## Tasks
- [x] Ensure the list of fields is totally complete
- [x] Look for repeated fields
- [x] Identify any optional fields
- [x] Share in this ticket for the team
- [x] Consider scheduling a time for FE and BE to get together

## Acceptance Criteria
- [x] The list of fields has been triaged and addressed

**Comment by digitaldrk** [comment]
## Dependent type
FE options:
* SPOUSE
* MINOR CHILD (UNDER 18 YEARS OLD
* STEPCHILD
* ADOPTED
* CHILD INCAPABLE OF SELF-SUPPORT
* 18-23 YEARS OLD AND IN SCHOOL
​
### Question
What do we do with:
* DEPENDENT PARENT
	* No option in BGS ( we get errors for using anything other than (spouse, child, guardian)
* CHILD INCAPABLE OF SELF-SUPPORT
	* No option in BGS ( we get errors for using anything other than (spouse, child, guardian)
​
1. dependent_type PDF options:
	1. SPOUSE
	2. MINOR CHILD (UNDER 18 YEARS OLD [sic]
	3. STEPCHILD
	4. ADOPTED
	5. DEPENDENT PARENT
	6. CHILD INCAPABLE OF SELF-SUPPORT
	7. 18-23 YEARS OLD AND IN SCHOOL
​
​
BGS call (vnp_ptcpnt_rlnshp_create)
* Field
	* ptcpnt_rlnshp_type_nm
		* options
			* Spouse
			* Child
			* Guardian
​
* family_rlnshp_type_nm
	* options
		* Estranged Spouse
		* Spouse
		* Ex-Spouse
		* Biological
		* Stepchild
		* Adopted Child
		* Other
	
​
## Marriage History
Currently, we get the current spouse's and veteran's marriage history. Should we create a participant, person, and relationship between the "X's" and the vet/spouse?

```
    "veteran_marriage_history": [
      {
        "start_date": "2007-04-03",
        "start_location": {"state": "AK", "city": "Rock Island"},
        "reason_marriage_ended": "OTHER",
        "reason_marriage_ended_other": "Some other reason",
        "end_date": "2009-05-05",
        "end_location": {"state": "IL", "city": "Rock Island"},
        "full_name": {
          "first": "Sansa",
          "middle": "Bigfoot",
          "last": "Stark",
          "suffix": "III"
        }
      }
    ]
```

```
"spouse_marriage_history": [
      {
      "start_date": "2008-03-03",
    "start_location": {"state": "IL", "city": "Rock Island"},
    "reason_marriage_ended": "DEATH",
    "end_date": "2010-03-04",
    "end_location": {"state": "IL", "city": "Rock Island"},
    "full_name": {
      "first": "Clovis",
      "middle": "Nigel",
      "last": "The Cat",
      "suffix": "Sr."
    }
  }
]
```

## reason_marriage_ended_other
In `vnp_ptcpnt_rlnshp_create` we have these options for marriage type code:
	* Death
	* Divorce
	* Other
​
BUT FE is sending this if ‘other’ is chosen:
“reason_marriage_ended_other”: “Some other reason”,
​
## Current spouse reason for separation
FE sends reason for separation. We don’t know where to put this. Would it be ‘Other’ in `marage_trmntn_type_cd` ?
```
    "does_live_with_spouse": {
      "spouse_does_live_with_veteran": false,
      "current_spouse_reason_for_separation": "Other",
      "address": {
        "country_name": "USA", # Done
        "address_line1": "2037 29th St", # Done
        "city": "Rock Island", # Done
        "state_code": "IL", # Done
        "zip_code": "61201" # Done
      }
```
​
​
## Marriage type
FE sends something like this:
```
"current_marriage_information"=>{"date"=>"2020-01-01", "location"=>{"state"=>"CA", "city"=>"Slawson"}, "type"=>"CEREMONIAL"},
```
​
Where do we put ‘type’ and then type other?
​
## When adding a child
### marriage end date
We don’t have a home for: `date_marriage_ended` Should we use `end_dt` in `vnp_ptcpnt_rlnshp_create`?
​
Options FE sends:
* Declared Void
* Annulled
* Other
ex.
```
"previous_marriage_details": {
          "date_marriage_ended": "2018-03-04",
          "reason_marriage_ended": "Death" # DONE
        },
```
​
​
### What do we do with ‘person child lives with’?
Should we create a person and a relationship with the child and this person?
```
        "child_address_info": {
          "person_child_lives_with": {
            "first": "Bill",
            "middle": "Oliver",
            "last": "Bradsky"
          },
​
```
​
## Adding step child
Should we create a person and a relationship with the child and this person? (Like adding child)
```
 "who_does_the_stepchild_live_with": {
          "first": "Adam", # Not using this
          "middle": "Steven", # Not using this
          "last": "Huberws" # Not using this
        },
​
```
​
## 674
In the `school_information` what do we do with `training_program`? There’s `course_of_study` but that is taken in the `program_information` object
​
```
"school_information": {
      "name": "My Great School", # DONE school curnt_school_nm
      "training_program": "Something amazing",
      "address": {
Collapse
