### ISSUE TITLE
Reduce burden by easing resubmission

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#83500]
As a Veteran I want to resubmit my claim electronically, so that I can resubmit my claim easily and quickly. Having a choice between paper and electronic submission makes resubmission more accessible for me.

## Acceptance Criteria
 - [ ] **Scenario: User can easily resubmit claim electronically**
  - Given a user has submitted a claim
  - When the user wants to (or has to) resubmit their claim
  - Then the user should be able to easily access the resubmission process online
- [ ] **Scenario: Resubmission process is quick and efficient**
  - Given a user has submitted a claim
  - When the user wants to resubmit their claim electronically
  - Then the resubmission process should be quick and efficient, allowing the user to complete it within a short amount of time
- [ ] **Scenario: User receives confirmation after resubmitting claim**
  - Given a user has submitted a claim
  - When the user resubmits their claim electronically
  - Then the user should receive a confirmation message or email after successfully resubmitting their claim
