### ISSUE TITLE
DR | Update PDF decryption library

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#83503]
## Value Statement

**_As a_** Veteran
**_I want to_** upload AES-256 encrypted password-protected PDFs without an error
**_So that_** they can be used for evidence submission

---

## Background Context

Platform is currently unavailable to take ownership over updating the PDF decryption library in use.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/architectural-decision-records/pdf-decryption-support-plan.md
https://gist.github.com/CorySohrakoffUSDS/a8c4784f4a08eb2bed562c7324746839

- This is not a type of silent failure, just a FE submission blocker.
- CMP doesn't accept encrypted submissions, so we are currently decrypting files. However, AES-256 is not supported by the existing library (and it does not appear to be actively maintained).
- Open Question: What percentage of evidence submissions error because of this? (not a blocker just curious for impact measurement purposes) @dfong-adh 

## Acceptance Criteria

- [x] Password-protected PDFs using newer encryption methods can be opened/decrypted
- [x] Verify there are no significant differences using the new library for the decryption process compared with PDFTK
- [x] Feature flag so we can switch between old and new encryption methods
- [x] Add helper method for PDF decryption code

## Out of scope

- Replacing all existing usages of pdftk

## Tasks

- [x] Add `HexaPDF` gem to `vets-api`
- [x] Create helper method that calls HexaPDF for decryption
- [x] Use helper method in DR evidence attachment flow

## Definition of Ready

- [x] Clear value description
- [x] Testable acceptance criteria
- [x] We have sample files available for testing
- [x] Solution approach approved by enablement team and platform
- [x] Estimated to fit within the sprint

## Definition of Done

- [x] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [x] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [x] Code reviewed (internal)
- [x] Submitted to staging
- [x] Team approved production verification process
- [x] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
> Open Question: What percentage of evidence submissions error because of this? (not a blocker just curious for impact measurement purposes)

May 7 – May 28
Total evidence uploads: 18405
Encrypted count: 26
Successful decryption: 13
Failed decryption due to AES-256 encryption: 13

**Comment by dfong-adh** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/16989

**Comment by dfong-adh** [comment]
PR has been merged. Next step is to enable flag and validate in staging.

**Comment by dfong-adh** [comment]
Validated in staging - will enable flipper in production on Monday and monitor for any issues.

**Comment by dfong-adh** [comment]
Flag has been enabled in production

**Comment by dfong-adh** [comment]
June 10: 0 encrypted files uploaded after flag has been enabled as of 5:30 PM Pacific
