### ISSUE TITLE
Discovery: Investigate Use Cases for Test Profiling Tools

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#83501]
## Issue Description
One of the biggest things I took from RailsConf was the potential use of implementing of Test Profile Gems to help improve the efficiency of our test suite. I would like to play around with a few of the options out there ([vernier](https://github.com/jhawthorn/vernier), [test-prof](https://github.com/test-prof/test-prof), others?), and present the various options and some examples of what inefficiencies it reveals

## Tasks
- [ ] Investigate/document features of various Test Profilers
  - [ ] Vernier
  - [ ] Test-prof
- [ ] Run profiler against all/some of test suite, noting areas for improvement

## Acceptance Criteria
- [ ] Present findings to Backend CoP
