### ISSUE TITLE
Update Experience Standards to include "pattern" where we already include "component"

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83504]
## User Story
As a Governance team member, I want to ensure our standards are clear and concise, so that there's no room for interpretation or potential gaps from the VFS perspective.

Assignee: @allison0034 
Peer Reviewer: @rferguson13 

## Description
While preparing for the Staging Review for Pension Benefits on 5/10, Governance team members noted that we use the word "component" within the language for our Experience Standards, but we fail to mention "pattern." In order to ensure our standards work for all the potential problems we can encounter with VFS products on VA.gov, the purpose of this ticket is to expand the wording in any standard that mentions "component" to mention both "component" and "pattern."

This includes:

- User encounters consistent, clear design components
- User encounters up-to-date design components
- User experiences predictable interactions with components

> [!WARNING]  
> This ticket should be worked on alongside ticket #83502 as they both include changes to the same key guidance docs.

## Impacted Artifacts
[VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards)

## Tasks
- [x] Review the [Updating Experience Standards and descriptive tags](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) guidance first
- [x] Update the language for the 3 identified Experience Standards (add "pattern" wherever component is) and share with peer reviewer for feedback
- [x] Once approved by peer reviewer, follow guidance for making changes to Source of Truth, DraftingTemplate, as well as DST versions of same docs
- [x] Contact @humancompanion-usds for publishing changes to VFS-facing guidance on VADS

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All VA.gov Experience Standards use consistent language for patterns and components

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@rferguson13 this change has been made in both [drafting templates ](https://drive.google.com/drive/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud)and [VA.gov Experience Standards source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=2089466616). Once you approve I will ask Matt to update DS.

**Comment by humancompanion-usds** [comment]
A PR would be most welcome!

**Comment by rferguson13** [comment]
@allison0034 - Looks good!

**Comment by allison0034** [comment]
@humancompanion-usds I created a [PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2898) and ready for your review.

**Comment by allison0034** [comment]
This will move into the next sprint while waiting for Micah to trouble shoot the PR fail.

**Comment by allison0034** [comment]
Merge successful.
