### ISSUE TITLE
Update Descriptive tag list

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83502]
## User Story
Asa Governance team member, I want to be able to tag the appropriate descriptive tag for VADS components at Staging Reviews so that we are able to track trends and patterns with misuse of components.

Assignee: @allison0034 
Peer Reviewer: @rferguson13 

## Description
DST had a Staging Review on 5/17 for the `va-button-icon` component. In order to ensure we can tag this component correctly in the future if it's ever misapplied or misused at a Staging Review, we must add it to our list of descriptive tags.

At the Governance refinement on 5/20, it was also noted that there may be other changes to the components, patterns or content style guide in the VADS. This ticket will also include verifying those page changes to determine if descriptive tag updates are necessary.

### Notes from refinement

- Multi-response pattern?
- Content Style guide changes?
   - expanding on pages? not adding pages. Just adding clarification

## Impacted Artifacts
- [Both drafting templates](https://drive.google.com/drive/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud)
- [Experience standards source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009)

## Tasks
- [x] Review/verify changes to the multi-response pattern and any changes to the content style guide. If page titles have changed, or any major changes to the guidance has occurred, share on #platform-governance-team channel for team awareness. Once confirmed, list components, patterns, or content style guide pages below, then edit the Descriptive tags as specified.
   - Add Destigmatizing language in substance use and Neutral and inclusive language to content style guide
   - Move URLs from content style guide to components
   - Add button-icon to components
- [x] Review the [Updating Experience Standards and descriptive tags](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) guidance to understand what steps are necessary for making updates
- [x] For the `va-button-icon` component, and potentially others, follow the guidance for adding the new descriptive tag

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The descriptive tags used in the Staging Review process are up to date and accurate

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
We do not call out variations of multiple responses so that one should be fine.

**Comment by allison0034** [comment]
Content style guide additions:

- Destigmatizing language in substance use
- Neutral and inclusive language

Content style guide removal:

- URLs

**Comment by allison0034** [comment]
Met with Erin and walked thru how to add descriptive tags. Also, per Erin URLs needs to move to components.

**Comment by allison0034** [comment]
@rferguson13 all impacted artifacts are ready for your review.

**Comment by rferguson13** [comment]
@allison0034 In the DST drafting template, it looks like the "Design System Component" column is missing for me. Can you double-check that?

**Comment by allison0034** [comment]
@rferguson13 we do not use that column for DS reviews since we are reviewing individual components.

**Comment by rferguson13** [comment]
@allison0034 My bad! This looks good, then!
