### ISSUE TITLE
Execution: Auto Add Platform-Support-Support-Ticket Label to All Active Support Issues

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83509]
## Description 
At the moment we have to manually add either the Platform-Support-Ticket to all support tickets in the Active Support Issues column. To avoid human error, we would like to automate this process. 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Use the steps outlined in this previous ticket to execute on the labeling process listed in the title of this ticket
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Was able to knock this out while configuring GH projects board. Closing!
