### ISSUE TITLE
Update VFS-facing guidance re: new QA standard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83519]
## User Story
As a Governance team member, I want to update all VFS-facing guidance on the QA standards so that when published, VFS teams are aware of the impact to their teams.

Assignee: @it-harrison
Peer Reviewer: @briandeconinck

## Description
In ticket #83521, Governance team drafted a new QA standard re: endpoint monitoring. In this ticket, we will make changes to VFS-facing guidance in preparation for launch.

How do we want to handle the Staging Review/QA artifact section of existing Collaboration Cycle Request tickets?

**Note:** No changes will be published within this ticket

## Impacted Artifacts
[Staging Review touchpoint page - QA artifacts section](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review#Stagingreview-QAartifacts*)
Staging Review code block (on [CC Kickoff - Moderator Responsibilities page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities))

## Tasks
- [x] Create documentation drafts of all impacted artifacts
- [x] Make appropriate changes per new QA standard
   - side note: the way the QA standards are listed/bulleted in the code block differs from how they're written on the SR touchpoint page. We should align them both so that they are consistent.
- [x] Share with peer reviewer
- [x] Are there any other guidance pages impacted by this new QA standard that have not been addressed in this ticket or within #83521? (if yes, let Shira know so estimate can be adjusted)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have updated all VFS-facing guidance impacted by the new QA standard

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@briandeconinck - this ticket is ready for review
[Draft Staging Review touchpoint page - QA artifacts section](https://vfs.atlassian.net/wiki/spaces/PPST/pages/edit-v2/3275063297?draftShareId=c50d208e-96a0-413c-a308-28ad97c97c07)
[Draft Staging Review code block (on CC Kickoff - Moderator Responsibilities page)](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3274014761/83519+-+Cycle+Kickoff+-+Moderator+Responsibilities)

**Comment by briandeconinck** [comment]
@it-harrison this looks good to me!
