### ISSUE TITLE
BE | Profile | Fix Vets-API swagger errors

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#83513]
## Background
There are 14 errors in the vets-api swagger docs for profile related endpoints.

## Tasks
- [ ] Fix 5 structural errors
- [ ] Fix 9 semantic errors

## Acceptance Criteria
- [ ] Errors are no longer reported in swagger documentation in (staging and prod).
