### ISSUE TITLE
Update operational guidance for IA at Design Intent and Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83516]
## User Story
As an IA on Governance team, I want to ensure that the operational guidance I follow for Design Intent/Midpoint Review includes recommendations for the VFS team if/when the product includes an application/form so that we are nudging VFS teams to be thinking about the veteran experience post submission of the form.

Assignee: @erinrwhite 
Peer Reviewer: @briandeconinck 

## Description
In the Collab Cycle, we are seeing more forms and applications come though, without much thought from the VFS team on what happens next for the Veteran after the application is submitted. In order to nudge VFS teams to begin thinking about the full experience for the Veteran, and what comes next after the submit button is selected, Governance team will modify our IA operational guidance at both Midpoint Review and Design Intent to 1) check to see if this scenario is applicable to the VFS product 2) include verbal feedback (if synchronous) asking appropriate conversations about the Veteran flow and the Veteran experience and 3) include written feedback in the Collab Cycle Feedback ticket under the appropriate section (must, should, consider, or thoughts/questions). 

How might we encourage VFS teams to design for the full Veteran experience?
How might we ensure VFS teams are modifying their scope to include form status?

## Tasks
- [x] Update the IA guidance for DI and MPR to include a recommendation for if/when the product is a form/application and no form status information has been included in the flow.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Our IA operational guidance has been modified so that we provide appropriate guidance to VFS teams if/when their product designs do not reference the full user experience

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@briandeconinck ready for you! I added comments in the pages to indicate where changes were made.

[Guidance for Design intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2601025548/How+to+complete+an+Information+Architecture+IA+review+for+Design+Intent)

[Guidance for Midpoint review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2492727325/How+to+complete+an+Information+Architecture+Midpoint+review+for+Review)

**Comment by briandeconinck** [comment]
@erinrwhite This looks good to me!

**Comment by erinrwhite** [comment]
Thanks @briandeconinck! closing.
