### ISSUE TITLE
[CDP] VBA Payment History mock ups

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#83514]
## Description

As part of the payment history work for VBA, we need to create mockups that clearly show a debt's given payment history based on the data defined in #83617.

Given: A veteran wants to see their most recent payment history
When: A veteran looks at their copay bill in the CDP
Then: They should be able to see clearly what their payment history is for a given copay.

## Tasks
- [x] Create mockups for payment history on overpayment summary page
- [x] Create mockups for payment history on overpayment detail page

## Acceptance criteria

- [x] Mockups created

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/83514?planning-poker) with Zenhub @mgleo

**Comment by mgleo** [comment]
[Figma link](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=359%3A9076&t=F7vL3g18l66bH2la-1)

Created new ticket: #84646
Moving this ticket to Validate @HeatherRienks @Tom-Davis

**Comment by Tom-Davis** [comment]
Closing - V2/final mockups will be addressed in the subsequent ticket.
