### ISSUE TITLE
Explore potential triggers/notifications for when an event is scheduled in Calendly

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83511]
## User Story
As a Governance team member, I want to explore options for being automatically notified when a Calendly event is scheduled so that the VFS team is no longer has to be responsible for notifying us via Slack workflow.

Assignee: @briandeconinck 
Peer Reviewer: @rferguson13 

## Description
At the weekly initiative meeting on 5/20, Governance team discussed potential solutions for our Calendly/Slack scheduling problems. The team agreed that ideally the VFS team will have 1 step to complete for scheduling a Collab Cycle touchpoint - scheduling in Calendly. The team also agreed that the solution must include some kind of notification/trigger for when the event is scheduled so that Governance team knows to take action. 

The purpose of this ticket is to explore what potential triggers/notifications could occur.

How might the Governance team be notified if/when a Collaboration Cycle Design Intent, Midpoint, and/or Staging Review is scheduled via Calendly?

**Note**: This ticket excludes the Collaboration Cycle Kickoff. Since the kickoff does not use Calendly, another solution, via another ticket, will have to be defined.

## Tasks
- [x] Identify possible solutions and explore feasibility for Governance team to be notified when a new Calendly event is scheduled. Solutions already discussed:
   - Email notification ~(Shira auto forwards all Calendly event emails)~ **Edit:** No need for Shira auto-forwards, can just get emails straight from Calendly
   - Google Calendar to Slack integration
   - Full Governance team is granted Calendly accounts **Edit:** Focusing on Slack integration this would provide rather than email notifications
- [x] Save doc in the Ideas folder of the Governance team space on Confluence. Format document similarly to [Research opportunities for improving notification workflow ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2833220014/69401+-+Research+opportunities+for+improving+notification+workflow)
   - [Potential notifications for new Calendly events](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3194650766/83511+-+Potential+notifications+for+new+Calendly+events) 
- [x] Share with Governance team for review and feedback. 
- [x] Finalize approach at Weekly Initiative Meeting

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team has a solution for being notified of when a new Collab Cycle Calendly event is scheduled

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Quick comment that I'm behind schedule on writing up my notes on notification options. I think I'll be able to finish that work tomorrow morning, but depending on when I finish it and Rebecca's meeting schedule it may carry into the next sprint for PR.

**Comment by shiragoodman** [comment]
@briandeconinck no biggie. This work can carry into the next sprint. As stated at standup on Monday, I'd like to use the 6/10 Weekly Initiative Meeting to walk through your proposed solutions with the rest of the Governance team. Once the team has been informed, we can decide together which approach is best. Thanks for the update!

**Comment by briandeconinck** [comment]
@rferguson13 [Potential notifications for new Calendly events](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3194650766/83511+-+Potential+notifications+for+new+Calendly+events) is ready for your review.

As noted above, this will carry into the next sprint. We'll be discussing options at the weekly initiative meeting on 6/10.

**Comment by rferguson13** [comment]
@briandeconinck - Nice work on this; this research is thorough. I think we'll have a good discussion on Monday.

**Comment by briandeconinck** [comment]
Noting for @shiragoodman that I've added a [brief note to the Confluence page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3194650766/83511+-+Potential+notifications+for+new+Calendly+events#Outcome) on the outcome of the team's discussion and our Calendly explorations. I think this is in a good place to close.

**Comment by shiragoodman** [comment]
I agree that this is in a good place to close. Thanks @briandeconinck !
