### ISSUE TITLE
AutoSSO - Ensures users stay on VA.gov when using MHV USiP AutoSSO

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#83522]
## Tasks
- [ ] In the `checkAutoSession` function when the user isn't logged in but has a session, verify the `authReturnUrl` in session storage is not an external application like MHV, My VA Health, etc.
    - [ ] If it's external, remove it before calling the `login({ policy: 'custom' })`
    - [ ] If it's internal, leave it as it is
