### ISSUE TITLE
Filing a BDD claim with CFI only

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#83523]
Discovered this issue while performing manual end to end testing on stage

**Steps to reproduce**
1. Start a new BDD claim
2. Fill out only required fields for each page. When getting to the `claim-type` page, only select the checkbox for Claim For Increase - "One or more of my rated service-connected conditions has gotten worse"
3. Fill out remaining required pages and submit the claim

**Expected**
- After step 2 above, Veteran should be prompted to select one or more rated disabilities 
- Fill out remaining required pages and submit the claim
- Claim is successfully submitted 
[related slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1717159172158369)

**Actual**
- User is not prompted to specify rated disabilities on the `diabilities/rated-disabilities` page. In the depends clause, it only displays the page if 1. claiming an increase and 2. not a BDD claim
- This causes a submission failure because there are no disabilities selected for the claim
<img width="875" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem4zQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9cfaef3ebb506370e2df5078d03cea4b97fe8836/image.png" alt="image.png" />

**Initial open questions**
- Should Veteran be prompted for which of their rated disabilities to include in the BDD + CFI claim? (fyi, looks like the depends logic noted above has been in place ~4 years). --> answer is yes
- If not, what is the alternative to fulfill submission requirements? 

**Tasks**
- [x] Update `disabilities/rated-disabilities` page to display for BDD claims
- [x] Update any automated tests (unit or e2e)
- [ ] Once merged and deployed to staging, test with VBMS UAT to verify the BDD + CFI claim is submitted successfully and pdf is marked appropriately  ('BDD Program Claim' is selected on question 1 and section V has appropriate disabilities)

**Comment by alatempa24** [comment]
[Started thread to answer our open questions in DSVA Slack](https://dsva.slack.com/archives/C04KW0B46N5/p1717159172158369)

**Comment by sethdarragile6** [comment]
Merged and stage tested User 54 successfully
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92405130/8a2d5122-f9f5-4b77-8460-cf1ceeeee1db)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92405130/cdbcaa6d-cbc0-4131-85ba-0f43a08560c3)
