### ISSUE TITLE
Modify post-meeting tasks for DST SR to create ticket for updating Descriptive Tags

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83525]
## User Story
As a Governance team member, I want to ensure that as new components/patterns are added to VADS, that Governance team has a process in place for ensuring our descriptive tags stay up to date.

Assignee: @rferguson13 
Peer Reviewer: @erinrwhite 

## Description
A Design System team Staging Review was held on 5/17 for the `va-button-icon` component. Since this is a new VADS component, it has only been recently added to VADS and is not included in the Staging Review Descriptive tags for potential future use at a VFS team Staging Review.

The purpose of this ticket is to add steps to the Design System Staging Review - After the Meeting guidance to ensure that the new component get's added to the Descriptive Tags.

## Impacted Artifacts
[Design System Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2827943956/Design+System+Staging+Review+-+After+the+Meeting)

## Tasks
- [x] Create a documentation draft of the impacted artifact
- [x] Include a step for verifying label with Carol and/or Design System team. The new label for the new component may not exist in the va.gov-team repo, but it likely already exists in the vets-design-system-documentation repo (check [Labels](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/labels))
- [x] Reference [Updating Experience Standards and descriptive tags](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) in After the Meeting guidance. 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Design System Staging Review - After the Meeting guidance includes steps for creating a new descriptive tag, if applicable
- [x] A new descriptive tag is created following a DST Staging Review

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
[Documentation draft created](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3181543425/83525+-+Erin+-+Design+System+Staging+Review+-+After+the+Meeting)

**Comment by rferguson13** [comment]
@shiragoodman Quick clarification question: what is the end result of this ticket? Is the person on support creating/adding the new descriptive tag? Or are they creating the ticket to add the new descriptive tag, which will be picked up in later sprint work?

**Comment by shiragoodman** [comment]
@rferguson13 that's a good question, and honestly, I don't have a preference. As a person on-support, what would you prefer?

**Comment by rferguson13** [comment]
@erinrwhite - [I could use your help on this](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3181543425/83525+-+Erin+-+Design+System+Staging+Review+-+After+the+Meeting). I added some steps, but is this too simple? I also have a question for you on confirming the component label with DST.

**Comment by erinrwhite** [comment]
Thanks @rferguson13 - took a look and commented. The edits are looking good!

**Comment by rferguson13** [comment]
@erinrwhite Thanks for your comments! I made some tweaks based on your suggestions. Take a look when you get the chance :)

**Comment by erinrwhite** [comment]
@rferguson13 this looks great! One final optional change I'd recommend is to make this step 5, after all the updates to the CC ticket are done.

**Comment by rferguson13** [comment]
@erinrwhite - Done. Shall I move this out of drafts?

**Comment by erinrwhite** [comment]
@rferguson13 absolutely!!

**Comment by rferguson13** [comment]
@erinrwhite - Here we go! Final check, then let's do a post and close this out.

**Comment by erinrwhite** [comment]
@rferguson13 All set! Boxes checked!
