### ISSUE TITLE
Edit: React Router Guidelines Page [Footer Ticket 82912]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83529]
## Issue Description

- The [React Router Guidelines](https://depo-platform-documentation.scrollhelp.site/developer-docs/react-router-guidelines) page needs to be updated to include a section on intentionally producing a 404 page in response to a specific situation.

---
## Tasks
- [x] Review Footer Ticket [82912](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82912) for context
- [x] Reach out to requestor to collaborate on drafting page update

## Acceptance Criteria
- [x] Page will be updated to include new sections
- [x] Page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
Page updates made as requested. I sent a pdf copy of the updates to the requestor, waiting for feedback/approval.

**Comment by taylojill** [comment]
Page content approved by Carlos Felix via Slack DM on 6/11/2024. 
Here's what I did:
- Updated active page as requested
- Added missing page footer
- Checked for blockers
- Date stamped

Ready to publish!

**Comment by jknipes** [comment]
work is complete, moving to _done_
