### ISSUE TITLE
Draft new QA standard on endpoint monitoring

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83521]
## User Story
As a Governance team member, I want to draft a new QA standard for endpoint monitoring so that VFS teams will be held accountable for the functionality of their product/service.

Assignee: @it-harrison
Peer Reviewer: @briandeconinck

## Description
It has been noticed that many VFS teams do not keep an eye on their endpoints, ensuring that the product/service they own on VA.gov is functioning as intended. In order to help nudge VFS teams in the right direction, Governnace team has decided to add a new Quality Assurance standard to the [Platform QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) so that we may help hold VFS teams accountable for the success of their product. 

**Note:** No changes will be published as part of this ticket. 

### Notes from 6/3 refinement
What is the QA standard with regards to monitoring endpoints?
How do we verify it has been met?

Something that can be vetted and verified in a systematic way. Something they know we're checking.

## Impacted Artifacts
[How to complete a QA review for the Staging review touchpoint ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)
[QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards)
[QA Collab Cycle Findings for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging%2C+qa-standards&projects=&template=collab-cycle-qa-findings-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product)

## Tasks
- [x] Draft a new QA standard (in alignment with the existing standards) for endpoint monitoring
   - Are there specific artifacts the VFS team will need to share with us?
   - Are we able to locate this information on our own if the VFS team does not provide anything?
   - Would we require the VFS team to create a new artifact to measure success?
   - How would we measure whether the new QA standard has been met?
   - Is this a launch-blocking issue if not met?
   - Do we need to draft guidance for how this standard can/should be met?
- [x] Propose how the QA representative on Governance will test/validate this standard (likely will impact the [How to complete a QA review for the Staging review touchpoint ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)guidance) 
- [x] Share new standard and proposed validation with peer reviewer for input
- [x] Once peer reviewer approves, share with @humancompanion-usds for approval

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have drafted a new QA standard for endpoint monitoring
- [x] We have proposed how the new QA standard will be validated by Governance

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@shiragoodman will share recording of walkthrough with Nate, Kyle, Matt etc. from ~4 weeks ago.

**Comment by shiragoodman** [comment]
This issue has moved into the next sprint, awaiting peer review.

**Comment by shiragoodman** [comment]
Also, please be aware that Matt's approval/input is required for this ticket. Please share with him as soon as the peer review is completed. thank you!

**Comment by briandeconinck** [comment]
@it-harrison This looks good to me, besides the comment from Shira on the PR about template updates. I think this is good to go.

**Comment by shiragoodman** [comment]
@it-harrison I think this is good to close out. You have completed/met all acceptance criteria. Per guidance from @humancompanion-usds, we are putting this initiative on pause until we receive feedback from OCTO engineers.
