### ISSUE TITLE
Separation Locations page is broken when Lighthouse BRD flag is on in Staging

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#83527]
## Issue Description
When following the BDD flow in the 526ez application on Staging with the [disability_compensation_lighthouse_brd](https://staging-api.va.gov/flipper/features/disability_compensation_lighthouse_brd)  flag turned ON, the automatic "dropdown" of locations does not populate. Because the user is required to enter something from that list, they are then blocked from proceeding with the application.

<img width="471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDczQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfb7db2303957a0aae921d0702ea357020113a2c/image.png" alt="image.png" />

Turning the flag to OFF fixes the issue almost instantly. Curiously, even when you turn the flag back ON at this point, the dropdown will continue working for everybody. Perhaps some sort of "server-wide cache" gets populated at the first successful visit (to EVSS) but then is cleared again with the next deployment?

---
## Tasks
- [ ] Determine why initial LH calls to BRD are failing, and why switching the flag OFF and ON again seems to fix it

## Acceptance Criteria
- [ ] Seperation locations autosuggest "dropdown should populate consistently upon deploy

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
