### ISSUE TITLE
Create Product Documentation for VRE (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8353]
## Goal
Another feature we want to queue up is "Apply for VRE benefits (CH31)" and we want to start with some initial product documentation and a collaboration cycle kickoff.

## Tasks
- [x] Research how the application currently works and if there are any stakeholders
- [x] Document those findings in the feature folder's feature outline

## Acceptance Criteria
- [x] The feature outline has been started [here in the feature folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31) 
- [x] The collaboration cycle has been requested for scheduling
