### ISSUE TITLE
5103 Language and Claim Certification: Intro page and Supporting Evidence page

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#83534]
As a Veteran I want to be able to view any information that the VA is required to tell me by law in regards to supporting evidence. The info component needs to be updated on both the Intro Page and the Supporting Evidence Page

## Reference: 
- [Figma designs](https://www.figma.com/design/igOOQi5BOTgQQJYA9X2G3M/(526ez)-5103-equivalent-language?node-id=6120-2272&node-type=canvas&t=GPPZqhr5ohy1CemL-0)
- [Alert designs in Figma](https://www.figma.com/design/igOOQi5BOTgQQJYA9X2G3M/5103-equivalent-language?node-id=0%3A411&t=FyBquviFOgI4Bkhh-1)
- Use `info`/default style `va-alert` library component: https://design.va.gov/components/alert
- ~~Link to specific page in the PDF (page 3), can be done via the `page` parameter in the linked url, e.g.`"#page=3"`~~
    - We should now use the HTML link to 5103: https://www.va.gov/disability/how-to-file-claim/evidence-needed/
- For the intro page, ~~embed alert into the process list: https://design.va.gov/components/process-list~~ place the alert after the "if you don't think this is the right form for you" text

## Tasks
- [x] Intro page: add and remove alerts; content, markup and styling changes as needed to sync with the mocks
- [x] Supporting evidence (orientation) page: Add alert
- [x] Develop behind environment check (dev and below for now until Submission Experience staging review is complete)

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] **Scenario: Notify Vets about required evidence**
  - Given a user is logged in
  - When the Veteran views the 526 intro page - they will see link for 5103 to open in a new tab
  - And when the Veteran views the [Supporting evidence page](21-526ez/supporting-evidence/orientation) 
  - The user should see an alert component containing a link to the official requirements of the evidence they are required to submit to support their disability claim
  - And the user should be able to click on the link to view more details about it
- [ ] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by pacerwow** [comment]
Related to work in [#80767](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/80767)

**Comment by mchae-nava** [comment]
<va-alert status="info" visible uswds>
<h3 className="vads-u-font-size--h3 vads-u-margin-top--0">Notice of evidence needed</h3>
        <p className="vads-u-font-size--base">
          We’re required by law…
        </p>
      </va-alert>

Link: <a className="vads-u-font-size--base" href={PDF_URL}>
Review official requirements on VA Form 21-526EZ (PDF)</a>

**Comment by mchae-nava** [comment]
```
<li>
            <h3>Prepare</h3>
            <h4>To fill out this application, you’ll need your:</h4>
            <ul>
              <li>Social Security number (required)</li>
            </ul>
            <p>
              <strong>What if I need help filling out my application?</strong>{' '}
              An accredited representative, like a Veterans Service Officer
              (VSO), can help you fill out your claim.{' '}
              <a href="/disability-benefits/apply/help/index.html">
                Get help filing your claim
              </a>
            </p>
          </li>
          <li>
            <h3>Apply</h3>
            <p>Complete this Mock form form.</p>
            <p>
              After submitting the form, you’ll get a confirmation message. You
              can print this for your records.
            </p>
          </li>
          <li>
            <h3>VA Review</h3>
            <p>
              We process claims within a week. If more than a week has passed
              since you submitted your application and you haven’t heard back,
              please don’t apply again. Call us at.
            </p>
          </li>
          <li>
            <h3>Decision</h3>
            <p>
              Once we’ve processed your claim, you’ll get a notice in the mail
              with our decision.
            </p>
          </li>
```

**Comment by mchae-nava** [comment]
@aurora-a-k-a-lightning or @christinec-fftc 

Couldn't get to finishing this due to 97221, but here's the summary of where I'm leaving off:
- Branch name is dbex/83534-5103-language-and-claim-certification
- PR: https://github.com/department-of-veterans-affairs/vets-website/pull/33239
- Added the info components and preliminary unit tests

TODO:
- I matched the existing 'disability rating' info component styling on the intro page. The Figma mocks have a different styling on them for existing components, so I wanted to double check which was the correct one
- Double check unit tests if more should be added
- Accessibility considerations

**Comment by pammicmac** [comment]
sorry if i messed with this ticket too much, i'm experimenting with a [sprint report](https://va-reports.boehs.com/sprints/191) and this ticket is missing from it, so i was trying to troubleshoot. hopefully all the settings are still right and this didn't disappear for anyone!

**Comment by christinec-fftc** [comment]
@pammicmac thanks for fixing it. i can see it on the board and in the report now so hopefully all is well
