### ISSUE TITLE
[CDP] Create a Prototype for VBA Payment History

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#83539]
## Tasks
- [x] Create a prototype for Desktop and Mobile
## Acceptance criteria

- [x] Prototype has been created
- [x] Prototype has been QA'd

## Testing
- [x] Test logic and paths go to correct results
- [ ] Test with screen reader to make sure the prototype is accessible 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
@josephrlee @mgleo - what do you estimate the LOE (in terms of points) on this effort?
cc @Tom-Davis

**Comment by HeatherRienks** [comment]
Discussed this ticket in Design Sync on 6/17/24; we will be moving this ticket to blocked for now, based on the feedback we received in the Friday,6/14/24 Design Intent meeting.

**Comment by josephrlee** [comment]
Due to design intent feedback requiring us to rework our mockups significantly, this ticket has been blocked until mockups have incorporated design [intent](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/86013) [feedback](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/85992) [blockers](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/86147). 

Also, we presented [updated designs](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2052-14439&t=5J0tS1C1sfftyV4M-11) at design office hours and got asked to rework them some more. 

Will tackle a couple of paths, here is a summary of the notes from office hours:

> Summary page two links on Cards:
> 
> - Check details
> - Resolve
> 
> Check details would contain payment history, debt letters
> Resolve would contain ways to pay, request help, dispute
> 
> Or
> 
> Reorg page and move debt letters down, payment info up  --seems there would still be hierarchy issues
> 
> Erin stated: IMO, Transaction details, debt letter history, and download debt letters should be moved down the page, and Pay/Request help/Dispute should be bumped up

cc: @mgleo @HeatherRienks @Tom-Davis @denisecoveyduc @charlottecesana

**Comment by josephrlee** [comment]
Here is a link to the collection on CodePen: https://codepen.io/collection/gYJrvO

Marking this as closed, we have a follow-up ticket #87519 for any changes we need to make after our pilot studies.

cc: @mgleo @HeatherRienks @Tom-Davis @denisecoveyduc @charlottecesana
