### ISSUE TITLE
Update Teamsite Docs [Footer Ticket 83412]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83544]
## Issue Description
The allow list on Teamsite docs needs to be updated. 
Suggested changes from ticket [83412](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83412) are below.

## SME:

- @barbarello 

---
## Tasks
- [x] Review Footer Ticket [83412](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83412) for details
- [x] Locate DevOps SME via #vfs-platform-support channel
- [x] SME makes changes to page per suggested language 
- [x] Content Team check for launch blocking issues

## Acceptance Criteria
- [x] Page is updated
- [x] Page is ready for deployment
---

## Suggested Changes
Instructions for devops allow lists reference outdated code: The commit examples linked from https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview#TeamSiteoverview-Considerationswheneditingandtestingtheallowlist are pointing at a commit hash version of the file. Links from that doc =

1. https://github.com/department-of-veterans-affairs/devops/blob/c5687fc1b483eaea17a1191eb41440fb560d01d6/terraform/environments/dsva-vagov-prod/main.tf#L277
2. https://github.com/department-of-veterans-affairs/devops/blob/c5687fc1b483eaea17a1191eb41440fb560d01d6/terraform/environments/dsva-vagov-prod/main.tf#L290

That code has been significantly refactored in master. 

TeamSite CORS allowed origins for `bucket-prod-va-gov-assets` and `bucket-preview-va-gov-assets` are now part of the vets-api module, so docs should instead point to https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-prod/main.tf#L274 in `master` branch, and instruct users to add new domains to `local allowed_origins`. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
cc: @barbarello
