### ISSUE TITLE
Content Edit: Getting access to DataDog (77264)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83552]
## Issue Description

In Footer ticket [77264](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77264), author states:

In the documentation for getting access to DataDog, the `vanotify-va-datadog` is listed as the default application to request access for. I believe that this is causing confusion, as many VFS developers primarily require `vagov-va-datadog` access, and (I've seen a few help requests in Slack from people who asked for the incorrect hosting location. It would be helpful to have information in the access request documentation describing what each hosting location is used for, and direct users to identify the ones that are relevant to them, instead of listing one host as a default.

### Solution
We need to add **information on which hosting locations are for which purpose**

#### Relevant URLs
- https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog
---
## Tasks
- [ ] Make changes according to Description
- [ ] Check for launch blockers
- [ ] Check for Style Guide violations
- [ ] If found, create separate ticket in Current Sprint for Style guide work
- [ ] if bandwidth permits, fix violations now 
- [ ] if unable to fix violations now, move the new ticket to Backlog

## Acceptance Criteria
- [x] All tasks completed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/83552?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
cc: @EWashb

**Comment by taylojill** [comment]
Per this [Slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1744998309626829), the vanotify-va-datadog reference was removed in a previous update. I checked the page and the reference has been removed. Brandon Dech (SME) recommends closing this ticket.
cc @jknipes

**Comment by jknipes** [comment]
"this was corrected at some point in the past because I no longer see any mention of the `vanotify-va-datadog` instance. Currently on that article, it only lists the `vagov-va-datadog` instance, which is the instance majority of users will be seeking access to."

**Comment by jknipes** [comment]
This work was brought into the current sprint due to available capacity. Planned tickets completed earlier than expected.

**Comment by jknipes** [comment]
cc: @little-oddball @JoeTice
