### ISSUE TITLE
Update Product Documentation for Loan Guaranty Application

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8355]
## Goal
Another feature we want to queue up is "Loan Guaranty Application" and we want to start with some initial product documentation and a collaboration cycle kickoff.

## Tasks
- [ ] Research how the application currently works and if there are any stakeholders
- [ ] Document those findings in the feature folder's feature outline

## Acceptance Criteria
- [ ] The feature outline has been updated [here in the feature folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE)
- [ ] The collaboration cycle has been requested for scheduling

**Comment by steve-gov** [comment]
Dupe of #7781
