### ISSUE TITLE
Implement Pre-Fill Functionality in vets-api for Forms 21-22 & 21-22a

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83555]
## Background

As part of our Appoint a Rep MVP, we would like to make use of the form pre-fill functionality.  Research to implement this functionality was done in #66168 with the following findings:

> Form pre-fill for the vets-api backend is thoroughly explained here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/prefill_setup.md. An example PR that runs through all the necessary additions is here: department-of-veterans-affairs/vets-api#5391.

**Open Questions**
1. Are our form URLs already determined?
2. Do we already have form names that map to our form numbers like vre_readiness: ['28-1900']?

## Tasks
- [x] Check in with the team to identify answers to the questions above
- [x] Two prefill classes, one each for 21-22 and 21-22a.  These prefill classes need a metadata method that includes that we want to enable prefill, a version, and a return URL.  The return URL is the first page of the form.  Example: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va_0993.rb.
- [x] Two form profile mappings that define what fields we want prefilled and where that data comes from.  Example: `config/form_profile_mappings/28-1900.yml`.
- [x] Add the two forms to `app/models/form_profile.rb`.  They need to be defined under `ALL_FORMS` and `FORM_ID_TO_CLASS`.
- [x] Add a definition of our form with `prefill: true` to `config/settings.yml`
- [x] Add two tests to `spec/models/form_profile_spec.rb` to cover each form

## Acceptance Criteria
- [ ] Pre-fill has been implemented in vets-api for our Appoint a Representative product, so that authenticated users do not have to enter any information that already exists in their VA Profile.

**Comment by cosu419** [comment]
8/8 update: two outstanding PRs that must merge in sequence. The [first](https://github.com/department-of-veterans-affairs/vets-api/pull/17901) has been approved but checks are timing out. Once those pass, the second will need to be re-reviewed.
