### ISSUE TITLE
Copy of [CDP] VBA Payment History mock ups

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#83559]
## Description
Create mockups based on understanding of data available.

## Tasks
- [ ] Create mockups for payment history on overpayment summary page
- [ ] Create mockups for payment history on overpayment detail page

## Acceptance criteria

- [ ] Mockups created

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
@josephrlee  @mgleo - I think this ticket might be a duplicate that can be closed? If so, please feel free to close it ;)

**Comment by mgleo** [comment]
Duplicate issue. Closing ticket.
