### ISSUE TITLE
Review 526EZ for MST and PTSD (21-0781) updates

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#83565]
## Description
VA Forms 21-0781 and 21-0781a have been updated. We need to review those updates in the 526EZ online form.

## Resources
- [Intro](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2595%3A20780&t=5dMnUmMbYamJA3Qf-1)
-  [Event details](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2595%3A20780&t=5dMnUmMbYamJA3Qf-1)
-  [Behavior changes](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2846%3A25271&t=5dMnUmMbYamJA3Qf-1)
-  [Treatment details](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2846%3A37663&t=5dMnUmMbYamJA3Qf-1)
-  [Supporting documents](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2595%3A73397&t=5dMnUmMbYamJA3Qf-1)
-  [Support alert component](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2226%3A6445&t=5dMnUmMbYamJA3Qf-1)

**Note:** Anthony asked Jina to confirm the screens to review in comments in the Figma file.

## Tasks
- [x] KF: Draft recommendations
- [x] AP: Review recommendations, as needed
- [x] KF: Share recommendations with product team

## Criteria
- [x] Our content recommendations have been shared with the product team

**Comment by katherine-fung** [comment]
I'm currently working on this, and have synced with @aprocik1. I'll reach out to the product team next week to set up a meeting to address outstanding questions.

**Comment by katherine-fung** [comment]
Hi @aprocik1, 

I've finished leaving comments throughout the Figma file: https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=2079-1122&t=v2yIvGOwjcN0cRTt-0 

In some areas, I used comments to suggest how the flow might change. If anything needs clarification, please let me know. Thanks!

**Comment by aprocik1** [comment]
@katherine-fung, thanks for sharing your recommendations. I think you're recommending some great improvements to the content and flow. I replied to your questions in the Figma file via comments. Let me know if you'd like to collaborate on anything else.

**Comment by katherine-fung** [comment]
Thanks @aprocik1! I've sketched out the CAIA recommendations we discussed with a11y and IA last week. Can you review these screens and let me know what you think? 

https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=3964-1122&t=WztKGtZ6POBzOUjG-0 

The sections with a yellow border are new sections/content that are different from the product team's design.

I've also left comments with questions that I'd love to get your thoughts on.

**Comment by aprocik1** [comment]
@katherine-fung, this looks great! I quickly skimmed it, but I think the content and flow make sense. I responded to some of your comments and questions. Let me know if you want me to return this or if you want to process together. Thanks for bringing so much more clarity to this form!

**Comment by katherine-fung** [comment]
@strelichl for your awareness, I've been working with @aprocik1, IA and a11y to re-work the flow of these questions within the larger 526 form to address a number of issues we see. I'm meeting with the product team later today to present our recommendations. The level of effort on this ticket has increased due to this work.

**Comment by aprocik1** [comment]
Update: The product team has continued to ask Katherine for copyedit recommendations that are indicative of larger updates needed to the form flow. We asked the product team to clarify their scope of work in this [Figma comment](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg?node-id=4696-81708#868334697).

**Comment by katherine-fung** [comment]
@aprocik1 can you take a look at this comment and help us decide where this line about VSOs being available to help with your application should live in the 0781? 

https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg?node-id=6887-87970#927225584

**Comment by aprocik1** [comment]
@katherine-fung, thanks for flagging this here. We shouldn't include the accredited representative information in the body copy of [this screen](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=6887-87970&t=441AaylGv6XnZ6LU-4). The accredited representative appointment process isn't immediate and the help that an accredited representative can offer is very different than the other bullets in this list (911, emergency room, VA medical center).

We don't have a standard pattern for how accredited representative content appears in products--because this content appears in many products, in many different ways, and because we can't make direct edits to this content on our own. That said, a number of product teams have moved this content to the "need help" section. This is what I would recommend for this product:

> ## Need help?
> **If you have trouble using this online form,** call us at 800-698-2411 (TTY: 711). We’re here 24/7.
> 
> **If you need help gathering your information or filling out your form,** you can appoint a VA accredited representative.
>  
> [Get help filling out a form](https://www.va.gov/get-help-from-accredited-representative/)

**Comment by aprocik1** [comment]
Update: I've reviewed the product team's opt out / opt in design and left recommendations in their Figma file. This work is ongoing.

**Comment by aprocik1** [comment]
Update: I'm still working with the product team to finalize their designs.

**Comment by aprocik1** [comment]
Update: I'm continuing to work with the product team to finalize the content for their designs.

**Comment by aprocik1** [comment]
Update: I'm continuing to work with the product team to finalize these content for their designs.

**Comment by aprocik1** [comment]
Hey @rubensun! I know we've been collaborating on this work via Figma and Slack. If all the work is completed, can we close this ticket? Or, should we keep it open for any remaining near term support request?

**Comment by hermonica** [comment]
Update: The product team said they might have more content requests soon.

**Comment by mistymg** [comment]
Closing this task out but added it to epic 80870. Will check in on the epic to see if there is more content work needed.
