### ISSUE TITLE
[CDP] VBA Payment History userflows

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#83560]
## Description

As a part of the payment history work for VBA, we need to come up with an updated userflow to guide our design process for what screens and decisions we need to take into account.

Given: A veteran wants to see their most recent payment history
When: A veteran looks at their copay bill in the CDP
Then: They should be able to see clearly what their payment history is for a given copay.

## Tasks
- [x] Review [existing userflows](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=0-5771)
- [x] Update userflows to create a more streamlined experience 

## Acceptance criteria

- [x] Userflows have been reviewed and updated 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/83560?planning-poker) with Zenhub @mgleo @charlottecesana

**Comment by josephrlee** [comment]
We've met as a team internally and have [updated the user flows](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1748-12691&t=BkCDV2iiN4BvvyGv-11). I still have some minor edits, but this is good to be closed out. 

@Tom-Davis , moving this to Validate for now to be closed.

cc: @HeatherRienks @mgleo

**Comment by Tom-Davis** [comment]
Closing as complete

**Comment by josephrlee** [comment]
Here is a [link to the updated userflows](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1748-12691&t=BkCDV2iiN4BvvyGv-11).

Also, here is a screenshot of them:
<img width="688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjg5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29849faf696d9191c5a676b16bc376caefb75878/image.png" alt="image.png" />


cc: @mgleo @charlottecesana @denisecoveyduc
