### ISSUE TITLE
Engineering | Profile | Mockingbird | Add mock responses

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#83571]
## Background
Some mock responses need to be added to the new mock repo.

## Tasks
- [ ] update address (mailing, home)
- [ ] update email
- [ ] update phone (home, mobile, work)
- [ ] update preferred name
- [ ] update gender identity
- [ ] update notification settings

## Acceptance Criteria
- [ ] the above actions are working locally.
- [ ] mock responses are added to seed file.
- [ ] code changes committed to repo.

**Comment by tpharrison** [comment]
@mtcA6 
There are some changes that should be made in the tool that will simplify adding mocks so it makes sense to hold off on this for now.  @ACParker89 and I chatted about this briefly.

New mock repo tickets will be added shortly.

**Comment by mtcA6** [comment]
Ok is there another story I should add into the sprint? I ~removed~ this one from the sprint 37 description

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
