### ISSUE TITLE
[DevOps] Create IAM Policy allowing GH role to create IAM Policies.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#83570]
## Description
This manually-updating CloudFormation templates whenever I find a new permission I need is for the birds. Rather, I should create a policy capable of creating policies, attach that, and then define everything else in Terraform.

## Tasks
- [ ] [DevOps] Figure out what permissions are necessary for this.
- [ ] [DevOps] Create the policy.
- [ ] [DevOps] Describe it in the template.

## Acceptance Criteria

- [ ] We can define our own policies in Terraform.

**Comment by ndouglas** [comment]
This is in place now and working correctly.
