### ISSUE TITLE
Exploration: Terraforming Helm

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#83596]
## Issue Description
Spend some time get a better understanding of patterns/best practices for terraformingHelm, and use newfound knowledge to better analyze current TF patterns so that it can be applied to GIDS

## Tasks
- [x] Tutorial: [Terraform Helm](https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks)
- [x] Analyze patterns used in Terraforming [Preview Envs](https://github.com/department-of-veterans-affairs/prt-preview-manifest/tree/main/terraform)

## Acceptance Criteria
- [x] Tutorial complete
- [x] Has a better understanding of existing Terraform
