### ISSUE TITLE
SPIKE [FE] Update OH Travel Application for Single and Multiple Station Scenarios

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#83604]
## Description
During our meeting with the BTSSS API team on 5/21/2024, the following was determined 
- Create tickets to support Update OH Travel Application for Single and Multiple Station Scenarios
- --- 
- Logic to calculate travel claim reimbursements for Veterans when they have appointments at multiple facilities on the same day is complicated. It was decided that we should refer the Veteran to the BTSSS portal to file claims when this scenario (edge case) arises.

- Logic to determine for which appointment to submit a claim when the Veteran has multiple appointments at a single facility on the same day is complicated. We should allow the Veteran to choose the appointment for which they want to submit a claim for that facility.

## Wireframes
[Wireframes](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=3583-1984&t=AmQACJgGbgv5pAKU-0)

## Tasks
- Create FE tickets for the wireframes and this functionality:
    - Update OH Travel to refer the Veteran to the BTSSS Portal when they have appointments at multiple stations on the same day
    - Update OH Travel to allow the Veteran to choose the appointment for which to file when they have multiple appointments at a single facility on the same day
- Begin working the FE tickets and pull into the sprint if time allows

**Comment by brianseek** [comment]
Working with @wullaski a bit a head of the UX wires. I think we will need the design before we can fully ticket things. So making an initial list here now.

Tickets:
 - [ ] convert local storage to store single timestamp
 - [ ] compare timestamp to today and redirect to error if already filed
 - [ ] remove redux context work for alreadyFiled and eligibleToFile

**Comment by brianseek** [comment]
First ticket for under the hood refactor: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/84508

**Comment by wullaski** [comment]
@loripusey I added these tickets to the backlog for the content updates
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85599
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85600
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85597

**Comment by loripusey** [comment]
Can I close this now @wullaski ?

**Comment by wullaski** [comment]
@loripusey yes
