### ISSUE TITLE
Research: Updating PR Template with PR Requirements Check

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83606]
## Description 
We have received quite a few PR review requests that are lacking the following requirements before review: [Before You Submit a Pull Request](https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval#Submittingpullrequestsforapproval-BeforeYouSubmitaPullRequest).

Before a pull request is reviewed, the following criteria must be met:

- A team member is required to review and approve your pull request
- All required checks need to pass
- If you are having trouble passing your checks, Platform Support can help
- The Platform Support Team cannot see Jira tickets
- You need to put your Jira information in the PR body in the form of a screenshot, by copying and pasting the info, or by making a GitHub issue to link

We are building a PR bot that will automatically note when someone hasn't passed these checks, but in the meantime we'd like to update the PR template so that each VFS Team Member has a checklist to match our process.

This ticket will house the task of researching if that is helpful or possible.

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Reach out to Clint to identify if there is benefit to pursuing this task (i.e. do we want to wait for the PR bot or would this be helpful in the interim)
- [ ] If this is something we want to pursue, what items would need to be updated, what work would need to be completed, etc.
- [ ] If we are pursuing this, create tickets for executing the work in the backlog
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
PR Bot work will make this ticket irrelevant. Closing!
