### ISSUE TITLE
Replace ActiveModelSerializers (AMS) with JSON:API Serializers

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#83609]
## Summary

Replace ActiveModelSerializers (AMS) with JSON:API Serializers

The above two gems perform the _exact_ same task. Both serialize an object into the JSON:API specification. Besides being completely unnecessary, having two gems is a bad developer experience. This requires engineers to learn two different approaches and can also cause confusion on which one to use. There are other benefits to using just JSON:API Serializers including reduce application load times and increased performance. 

## Blocking Epic

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83601

## Tasks

- [x] Catalog each module with AMS serializers
- [x] Replace any AMS serializer with a JSON:API serializer
- [x] Remove `active_model_serializers` gem
- [x] Add documentation to communicate change and prevent AMS's reappearance 

## Acceptance Criteria

- [x] "Replacement" Tickets for each module and the root app exist
- [x] No serializer is an AMS serializer 
- [x] The AMS gem is not in the Gemfile
- [x] Documentation exists

**Comment by JoeTice** [comment]
This epic has been completed and is now closed
