### ISSUE TITLE
Add tests for ActiveModel::Serializer serializers

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#83601]
## Summary

In order to replace ActiveModelSerializers (AMS) with JSON:API Serializers, all ActiveModel::Serializer serializers need a unit test. 

## Tasks

- [x] Catalog each module with AMS serializers

## Acceptance Criteria

- [x] "Add Tests" Tickets for each module and the root app exist
- [x] All AMS serializers have a unit test
