### ISSUE TITLE
[CDP] VBA Payment History data discovery and definition

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#83617]
## Description

As a part of the payment history work for VBA, we need to understand what data we need to be able to display payment history details for a veteran's overpayment debt.

Given: A veteran wants to see their most recent payment history
When: A veteran looks at their copay bill in the CDP
Then: They should be able to see clearly what their payment history is for a given copay.

## Tasks
- [x] Review salesforce screenshot emails from Christina
- [x] Review previous teams [data definitions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/expected-data.md#proposed-additions).
- [x] Meet with DMC team and come to a shared understanding of what data fields can be added to the existing debts API

## Acceptance criteria

- [x] Data points have been agreed upon internally with our product team
- [x] Data points have been validated by SME's and stakeholders

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
Adding screenshot and message for more context:

![salesforce dmc screenshot](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/e6a9b45b-2cfb-4378-a4e8-46395fc2bc10)

> Here is a full image of our fields for Fiscal Transactions from a UI/UX prospective, I would strongly recommend only using the first three fields (Date, Description and All Fiscal Activity) to reduce confusion.  The remainder of the data (Payment Applied, Offset Applied, Debt Increase, Interest Activity and Admin Activity) are to categorize data for internal auditing, I have DMC employees that struggle with the meaning of this data and based on the source and debt type, it can mean different things that can be confusing.  Please let me know if you need anything else.

**Comment by josephrlee** [comment]
For the MVP, we'd like to add these fields to the API:

## Proposed additions:

- Balance-related info:
   - Amount paid
   - Interest / fees accrued
   - Balance
- Payment history
  - Date payment was made
  - Payment amount
  - Payment method

cc: @mgleo @charlottecesana

**Comment by digitaldrk** [comment]
Here' some mapping maybe (based on the payload I showed):
"Date payment was made" => `transactionDate`
"Payment amount" => `transactionTotalAmount` (?)
"Payment method" => `paymentType`

**Comment by josephrlee** [comment]
We met today as an internal team and drafted questions for the DMC folks to follow up on before Thursday's meeting. 

Once we meet on Thursday, we should be able to close this ticket out. There's about 1 point left.

cc: @HeatherRienks @Tom-Davis @mgleo

**Comment by HeatherRienks** [comment]
Per Standup on 6/14/24, we are moving this to blocked. We need help from Christina Siedow (DMC) to add more descriptive data (of what was originally sent - more human readable). @denisecoveyduc  will reach out to Christina regarding timing of this effort.

**Comment by HeatherRienks** [comment]
@denisecoveyduc @josephrlee @mgleo @charlottecesana @Tom-Davis  - let's discuss this tmrw in our Design Sync.

**Comment by josephrlee** [comment]
This work has been satisfied; once we get an updated spreadsheet from Christian at DMC, we will create a follow-up ticket to work on better messaging for the Hines/Transaction codes. 

cc: @Tom-Davis @HeatherRienks
