### ISSUE TITLE
Identify Top Teams and Submitters of PRs That Don't Meet 24 Hour Requirement

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83612]
## Description 
We'd like to reduce the volume of tickets we receive requesting PR reviews since we check our queues at least once every 24 hours. This will help us reduce noise in the support channel. 

We can use this data: https://docs.google.com/spreadsheets/d/1R_Vf2mmeVPQ0YIpLGTgna8PcJG2gcccdsk8fBGZRLd8/edit#gid=0

---

## Definition of Done
All tasks below are complete.

- [x] January 2024 - Lindsay 
- [x] February 2024. - Brandon 
- [x] March 2024 - Brenden 
- [x] April 2024 - Anthony 
- [x] May 2024 - David

---

## Tasks 
_Steps to reach definition of done._ 
- [ ]  Identify top teams who submit PR review requests within 24 hours of requesting for review (ensure that they are not valid requests)
- [ ]  Identify top individuals who submit PR review requests within 24 hours of requesting for review (ensure that they are not valid requests)
- [ ]  Report the metrics and results in the comments below
- [ ]  Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@lindsay-insco Lindsay to identify best way to pull data on 5/31.

**Comment by EWashb** [comment]
I think an outcome of this work is to identify those having issues and direct them to our policies and best practices. I'm sure this is frustrating on their side too and we want to make sure that we are alleviating their pain along with ours. Thanks for looking deeper into this.

**Comment by alyssagallion** [comment]
Paused for now. May be resurrecting PR Bot which will run a script for this.

**Comment by bdech** [comment]
Google Sheet I created for Feb 2024 analytics https://docs.google.com/spreadsheets/d/1_rWjvPEuW6snxp5U6AtcROJrHLFudtBM7vPBjIIVcXA/edit#gid=0

**Comment by bdech** [comment]
For the month of February, there was a total of 17 PR support requests that were outside of the 24 hour window. The table and image below represents that data. The left column of the table shows the team, and the right column shows the respective total. <img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJ0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50da08ac3f4cc9733237b4bc7e232f6816081342/image.png" alt="image.png" />

**Comment by lindsay-insco** [comment]
I am not a google graph/sheets master BUT the PR spreadsheet would NOT let me pull 2024 data - only up to summer 2023 SO I went through slack and my data is [here](https://docs.google.com/spreadsheets/d/1PdU3OqsgPlA8dzBH4-ptlNZ3nn_--VhWzB2t_wkNSp0/edit?usp=sharing)

113 total PRs
18 PRs did not meet the 24 hour window 

6 - Pensions (Matthew Knight - This was the month Pensions was trying to relaunch ASAP)
3 - MHV (Stephen Barrs, Larry Crochet, Matthew Wright 1 each)
3 - MBMS (All Michelle Dieudonne Yenyo)
2 - Veteran Status (Liz Townsend)
2 - Sitewide Facilities (Randi Mays)
1 - Benefits (Oren Mittman)
1 - CMS (Eric Oliver)

**Comment by AnthonyWFlowers** [comment]
I created my in Numbers for Mac so had to export to Google [HERE](https://docs.google.com/spreadsheets/d/15mOKzerwCwp7Fbt0bFRBaDaw6JhptWH-oOk41FC_xjo/edit?usp=sharing)- let me know if that is a problem. I have attached file but also attached screenshots of the data. 
<img width="521" alt="Screenshot 2024-06-18 at 9 49 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/161509257/a550c345-f57c-4a5d-8bec-1315f992e174">
<img width="833" alt="Screenshot 2024-06-18 at 9 50 11 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/161509257/7afddb6b-0b24-4f9f-bc43-c4e2fba225ea">

**Comment by davidpetras** [comment]
Results for May 2024, there were 22 PR's not meeting the 24hr requirement.

<img width="621" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU55QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea5f6be35318e561c0ac46b17015ddf4edd454bc/Screenshot%202024-06-18%20at%2010.52.03%E2%80%AFAM.png" alt="Screenshot 2024-06-18 at 10.52.03 AM.png" />
<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVp5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5b250947b758605e3ce42a98254bedd49200e45/Screenshot%202024-06-18%20at%208.09.44%E2%80%AFAM.png" alt="Screenshot 2024-06-18 at 8.09.44 AM.png" />

**Comment by bmatos312** [comment]
[]https://docs.google.com/spreadsheets/d/1RLOJqnDAXDd9CBJbq2uS-_5YG4qUJ1e071BtrqgWKU0/edit#gid=0url) Checklist here
<img width="967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXR6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7690a3355fe339af180fa9cc216a5fbac8554f65/Screenshot%202024-06-18%20at%201.44.55%E2%80%AFPM.png" alt="Screenshot 2024-06-18 at 1.44.55 PM.png" />

**Comment by davidpetras** [comment]
google drive [link](https://drive.google.com/file/d/1E-y6Qs1ytEWB-e4f24l5L6tTHRrI0qBu/view?usp=drive_link)
