### ISSUE TITLE
Identify Top Submitters for OOB Deploys

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83610]
## Description 
To reduce the volume of OOB deploys, we'd like to identify and educate those that are sending in requests for OOBs unnecessarily. For example, some teams may be moving too quickly while doing their work resulting in an unnecessary OOB deploy.

We can use this document to pull the top submitters: https://docs.google.com/spreadsheets/d/19l2oLh2oMsbmuIgJwn6zoIk6z5OvAmER5TBYOQnb41I/edit?usp=sharing

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Sort data to identify who the top teams who submit OOB deploys are
- [x] Sort data to identify who the top individuals who submit OOB deploys are
- [x] Provide the metrics in the comments below
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
Made a copy of the spreadsheet, and added column 'VFS Team'
https://docs.google.com/spreadsheets/d/1qh57M2om_D9e2MaBGV32N0wcN82Go4BckgwC3FUCMyg/edit#gid=0

**Comment by bdech** [comment]
Pivot Table includes a column of each VFS team, and a column for total OoB per VFS Team

https://docs.google.com/spreadsheets/d/1qh57M2om_D9e2MaBGV32N0wcN82Go4BckgwC3FUCMyg/edit#gid=173383550

<img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c79822cc57db5bca7b22dcf7d5266f5b88f70724/image.png" alt="image.png" />

**Comment by bdech** [comment]
Pivot Table 2 breaks down the total number of OoB by the submitter

https://docs.google.com/spreadsheets/d/1qh57M2om_D9e2MaBGV32N0wcN82Go4BckgwC3FUCMyg/edit#gid=2107735730

<img width="1793" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b61b902a1aa65a521ae1293ef26daaa727ef44bf/image.png" alt="image.png" />

**Comment by bdech** [comment]
Made some edits to the data.

Separated out Public Websites from Public Facilities. Also, some OoB `submitted by` fields did not have a person
