### ISSUE TITLE
Outline Process for P1 Incidents (Watchtower)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83630]
## Description 
Currently we don't have any documentation in the Platform Support Confluence space that outlines the process for P1 incidents in Watchtower (which we handle). We need to create documentation around our responsibility. 
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Determine where a page should live for this topic with Brandon Dech/Lindsay Insco
- [x] Type out the exact process that we follow for this type of incident
- [x] Review with the team to ensure we haven't missed any details 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Removed sprint from ticket, accidentally added. Should be in the backlog.

**Comment by alyssagallion** [comment]
@bmatos312 Closed! When you get a chance, please copy and paste the Confluence page :)
