### ISSUE TITLE
Collaboration Cycle - Simplify scheduling process

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#83637]
## Problem Statement 

Governance team has struggled to uphold a process for VFS teams to schedule touchpoints in the Collaboration Cycle. The current process has several problems (for details, see ticket #82636) and a new solution must be introduced in order to ensure that Governance team can schedule touchpoints consistently and reliably.

## Hypothesis or Bet

- If we introduce a solution that maintains the features of the existing solution that both work well and are reliable, then both Governance and VFS will continue to benefit and rely on those features.
- If we introduce a solution the both reduces steps and removes duplication in steps that VFS teams are asked to complete, then VFS teams will have a better experience with Collaboration Cycle scheduling and will have more time to do important work.
- If we build a solution that removes dependencies on unreliable tools, then VFS teams and Governance team should experience no frustration with the process.

## We will know we're done when... ("Definition of Done")
- [x] Our revised process still includes the creation and sharing of a Slack thread in the VFS team channel for dedicated discussion with the VFS team on the product/touchpoint.
- [x] Our revised process asks VFS teams to complete only 1 step to schedule a touchpoint.
- [x] Our revised process guarantees that older tickets reference up to date instructions for the VFS to follow.
- [x] Our revised process no longer asks VFS teams to engage with an unreliable tool (ie Slack workflows)

## Known Blockers/Dependencies 
Governance has several dependencies, or limitations, in which our solution must fit. Please see [Current Limitations ](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3162308616/82636+-+Scheduling+Solutioning+Workshop#Current-Limitations)section of our Scheduling Solution workshop for a full list of limitations.

## Projected Launch Date
* When do you expect to be completed rolling out this initiative*

<details><summary>Toggle launch checklist</summary>

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by shiragoodman** [comment]
Definition of done has been fully met. All changes have been launched as of August 13, 2024. This is complete.
