### ISSUE TITLE
[Design, PM] Design system updates: visual QA post-typography changes

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#83635]
## Background
Design system will be making updates to typography as follows:

- 5/22: root change change from 10px -> 16px (we need to do visual QA)
- 6/5: base font size increases from 16px ->16.96px (we need to do visual QA starting 5/22 for 1 sprint)

We need to perform visual QA of My VA to ensure everything looks ok. 

## Tasks
- [x] Perform visual QA of My VA 
- [x] Identify any issues with changes in typography and report them to Design System 
- [x] If changes are need to My VA code, work with PM to identify needs

## Acceptance Criteria
- We know the impact of the typography changes

**Comment by mattmarino-adhoc** [comment]
Appears that it is still 16px for My VA on Staging (user 23), let's discuss on June 10th @allisonlu 

<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bc95a908b43748a6b8d97d56f38c1e24796f448/Screenshot%202024-06-06%20at%2010.00.55%E2%80%AFAM.png" alt="Screenshot 2024-06-06 at 10.00.55 AM.png" />
