### ISSUE TITLE
Identity Support Bot Research for Our Support Bot

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83656]
## Description 
We recently worked with the Platform Identity team to create a support bot for their team that would mirror ours. They have since created a version that we think might inspire some changes for us. We'd like to dive into the documentation to identify what tidbits we can use for ourselves!

---

## Definition of Done
All tasks complete below. 

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify which features we could leverage from the Identity Support Bot with Curt Bonade
- [ ] Create tickets for the work we would want to accomplish and attach them to the Platform Support Bot Phase Two epic
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Moved to backlog and forgot to remove sprint. Not part of planned sprint work.

**Comment by alyssagallion** [comment]
Identify if the team is still using the bot.

**Comment by alyssagallion** [comment]
Identity Bot is no more. No need to replicate. Closing.
