### ISSUE TITLE
Revamp Quarterly Survey questions

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#83659]
## Purpose
In an effort to improve how we measure and improve the satisfaction of our internal VFS users, some adjustment to the questions asked in the Quarterly Platform Services Satisfaction Survey is needed.
 
<img width="1058" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW45QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d136f44a56b14cee82848e2846f6f1c2c78c107/6821a001-0d0d-42d0-a6ae-9ccb5b1315db.png" alt="6821a001-0d0d-42d0-a6ae-9ccb5b1315db.png" />

[research?] [Related ticket on connecting w/ Platform teams](https://app.zenhub.com/workspaces/platform-service-design-61bcbaf174a70100154e22e7/issues/gh/department-of-veterans-affairs/va.gov-team/66969)

[Service Blueprint: Platform Services and Feedback Strategy](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712619961851/3829c86ba7797e393308a5b9dffd9fca1eabb041?sender=uff5bfe5bb2f0b77b02c90266)

## Tasks
- [x] Discuss with team the results of recent Platform Teams ask regarding these questions (6/11/24)
  - Watch for any double-barrel questions
- [x] Draft new set of questions for the survey
- [x] Decide on optimal questions for each team and document for Q2 survey use
- [x] Create space to share with Leadership/PO

## Acceptance Criteria
- [x] Proposed survey questions are readied for Q2
