### ISSUE TITLE
Document Current Pain Points for Platform Support by VFS Teams, Tier 2 and Tier 1 Needs

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83655]
## Description 
We've noticed there may be a few frustrations related to support for VFS Teams as well as Tier 2 and Tier 1 agents. We are working to document this feedback to identify solutions and improve workflows for all sides. All documentation is here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/3158802435?draftShareId=c34dbf63-5ef1-488b-ace6-ae6c3bf8c711

---

## Definition of Done
_What must be done to officially complete this task?_

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Document feedback for each party
- [x] Identify any metrics to support any of these claims
- [x] Send to Jason 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
