### ISSUE TITLE
Identify If We Should Increase Our PR Review SLA 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83650]
## Description 

We've recently seen a large increase in VFS staff being added to teams and as a result an increase in PR reviews. Namely, we saw an increase of 13% increase WoW in PR Review requests (despite us having an SLA of 24 hours to review the tasks). Now, we'd like to analyze the following:

- If we are currently meeting our SLA from a Tier 2 perspective
- How many requests for review are within the 24 hour period resulting in an unnecessary additional amount of work
- Identify if the Tier 24 hour SLA is still reasonable or if it can be increased

---

## Definition of Done
All tasks below are complete

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify if we are currently meeting our SLA from a Tier 2 perspective
- [ ] Identify how many requests for review are within the 24 hour period resulting in an unnecessary additional amount of work
- [ ] Identify if the Tier 24 hour SLA is still reasonable or if it can be increased
- [ ] Create tickets to execute on the change if one is necessary 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Metrics here will shape this decision: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/83612

Conversation with leadership as well.

**Comment by alyssagallion** [comment]
No need to pursue. We have changed language to 3 business days (same amount of time but reframed).
