### ISSUE TITLE
2024 Q3 Security Review June -September 2024

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#83676]
## Issue Description
OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

OCTO-DE teams periodically review user access to ensure that access is limited to users who currently need to access the systems and applications and that those users have the appropriate permissions.

Platform Security initiates each review cycle and application owners are responsible for executing the process for each application that they own. Once complete, application owners document the results of the access review and send the artifacts to Platform Security to document in eMASS as evidence.

## Tasks
- [x] Complete security review for Atlas

## Success Metrics
- [x] All inventory for Platform Product team is reviewed for security issues as outlined in [Security Access Review Process](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2987917734/Access+Review+Process) document and in the [Security Access Review Inventory](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2986115091/Access+Review+Inventory) document
- [x] All dates are met as outlined in [Security Access Review Rollout Plan](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3133177925/Access+Review+Rollout+Plan+-+Iteration+1) 
- [x] Security issues that are discovered are logged into the [Access Review Template](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3172205458/Sample+Access+Review+Template) 

## Acceptance Criteria
- [x] Security review completed for Atlas

## Objectives and OKRs
- Objective 2: Access reviews of all systems administered by OCTO are completed every 90 days
- OKR 4: Access reviews of all systems administered by OCTO are completed every 90 days 

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
