### ISSUE TITLE
[FE] My VA Forms Status: Support usability study

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#83673]
## Background
We will need FE support during the forms status usability study to update the prototype for each participant and provide general FE support as needed. 

## Tasks 
- [ ] Codepen familiarization for Daniel
- [ ] Ensure prototype is ready for the study
- [ ] Work with Matt and Jeana to ensure prototype is updated with participants info for each session
- [ ] Ensure back-up if unable to attend (Allison to make sure Daniel is up to speed with codepen)

## Acceptance Criteria 
- We provide FE support during the usability study

**Comment by ACParker89** [comment]
@ajakabcin roll into 39

**Comment by allisonlu** [comment]
closing this ticket as studies are complete 🎉
