### ISSUE TITLE
Improved scaling and resource consumption

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#83694]
## Issue Description
_To be completed after https://github.com/department-of-veterans-affairs/va.gov-team/issues/72438_

Traefiik's round-robin routing does not account for the actual load or processing capacity of each server and it may not distribute requests optimally if some requests are significantly slower than others. We could potentially identify some more of these resource-intensive or latent requests and their endpoints and isolate them into a bulkhead.

When 30% of our threads are in use, it triggers a scale of the pods. We need to do discovery on this, because it doesn't make sense to have 70% availability and there is still a backlog. It can be optimized by using Traefik to allow the use of more bulkheads.

## Tasks
- [x] Investigate and document the top latent endpoints in vets-api
- [x] Investigate and document why we scale at 30% of threads being used. 
- [x] Investigate and document how long we have before scaling if we've just scaled.

## Success Metrics
We have an understanding of when and why we scale and a path for improvement.

## Acceptance Criteria
- [x] All tasks are done
- [x] New tickets created, if necessary. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
To validate this, I'd like @LindseySaari to make sure nothing else needs to be done for this ticket.

**Comment by jennb33** [comment]
8/5 update: alert @LindseySaari when this ticket gets picked up, as she is doing some endpoint work. cc: @Kshitiz-devops and @rmtolmach

**Comment by rmtolmach** [comment]
These two pie charts show the 95th percentile of spans (a single operation or unit of work within vets-api) broken down by Kubernetes deployment, service, or resource. 
- [APM pie chart 1](https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20container_name%3Avets-api-web&agg_m=%40duration&agg_m_source=base&agg_q=service%2Cresource_name&agg_q_source=base%2Cbase&agg_t=pc95&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&historicalData=true&messageDisplay=inline&query_translation_version=v0&sort=desc&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&spanType=all&step=auto&top_n=10%2C10&top_o=top%2Ctop&view=spans&viz=sunburst&x_missing=true%2Ctrue&start=1722957566901&end=1723043966901&paused=false) is by service and resource.
- [APM pie chart 2](https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20container_name%3Avets-api-web&agg_m=%40duration&agg_m_source=base&agg_q=kube_deployment%2Cservice%2Cresource_name&agg_q_source=base%2Cbase%2Cbase&agg_t=pc95&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&historicalData=true&messageDisplay=inline&query_translation_version=v0&saved-view-id=2171&sort=desc&sort_m=%2C%2C&sort_m_source=%2C%2C&sort_t=%2C%2C&spanType=all&step=auto&top_n=10%2C10%2C10&top_o=top%2Ctop%2Ctop&view=spans&viz=sunburst&x_missing=true%2Ctrue%2Ctrue&start=1722957741036&end=1723044141036&paused=false) is by Kubernetes deployment, service, and resource.

Based on this data, the following are the spans currently taking the longest amount of time (taken from chart 2):

| Kubernetes Deployment › Service › Resource                                              | Count | Share  |
|------------------------------------------------------------------------------------------|-------|--------|
| vets-api-appeals › higher-level-review › V1::HigherLevelReviews::ContestableIssuesController#index | 60.5s | 9.87%  |
| vets-api-web › debt-resolution › V0::MedicalCopaysController#index                       | 59.6s | 9.72%  |
| vets-api-vaos-endpoint › mhv-appointments                                               | 55.0s | 8.97%  |
| vets-api-vaos-endpoint › vets-api-net-http                                              | 55.0s | 8.97%  |
| vets-api-vaos-endpoint › vets-api › VAOS::V2::AppointmentsController#create              | 55.0s | 8.97%  |
| vets-api-mobile › vets-api-net-http › PUT                                               | 55.0s | 8.97%  |
| vets-api-mobile › mobile-app › Mobile::V0::AppointmentsController#index                  | 55.0s | 8.97%  |
| vets-api-mobile › mobile-app › Mobile::V0::AppointmentsController#cancel                 | 55.0s | 8.97%  |
| vets-api-mobile › vets-api › Mobile::V0::AppointmentsController#cancel                   | 55.0s | 8.97%  |
| vets-api-mobile › vets-api › Mobile::V0::AppointmentsController#index                    | 55.0s | 8.97%  |
| vets-api-appeals › claims-shared                                                        | 30.2s | 4.93%  |
| vets-api-appeals › disability-application                                               | 20.2s | 3.30%  |

**Comment by rmtolmach** [comment]
**Why we were scaling at 30% threads in use:**
The HPA isn't super reactive for us (it takes some time before it scales) so we need some breathing room between when we realize we need to scale and when the scaling actually occurs. For Appeals, mobile, and VAOS, we do scale at 30%. We have to account for the various behaviors within vets-api.

The benefit of scaling at a higher percentage is that it's cost-saving–we don't have to use as many resources. 

**Background on bin/is_ready**
[bin/is_ready](https://github.com/department-of-veterans-affairs/vets-api/blob/master/bin/is_ready) runs every 5 seconds. It checks if the pod is greater than 60% in use, and if so it marks it as not ready (but doesn't remove it). Once it's back below the 60% threshold, it's released and can be used again. The HPA was originally looking at all pods and considering not ready pods to be ready, but with the bin/is_ready script, we're only scaling on what's available.

**Comment by LindseySaari** [comment]
Keeping this in review until end of sprint while keeping an eye on the backlog
