### ISSUE TITLE
Veteran Identification Information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83719]
## Issue Description

The Veteran Identification Information page will be available to:
1. Authenticated and unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.
  2. If the user is a **Veteran**, the `h2` should reference "Chapter 2".  If the user is a **non-Veteran** the `h2` should reference "Chapter 3".
  3. Input field designs
     1. Auth Veterans, prefill fields if information exists in their profile. The h3 should read "Your identification information".
     2. Unauth Veterans. The h3 should read "Your identification information".
     3. non-Veterans (auth and unauth). The h3 should read "Veteran's identification information".

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 2: Social Security Number (xxx-xx-xxxx)
   - Field 3: VA File Number (if applicable)
   - Field 5: Veteran's Service Number (if applicable)
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    - Field 2: Social Security Number (xxx-xx-xxxx)
    - Field 3: VA File Number (if applicable)
    - Field 5: Service Number (if applicable)

**URL**: `/veteran-identification`

**Previous paths**: 
1. `/veteran-contact-mailing`  

**Next paths**: 
1. `/veteran-service` (21-22a)
2. `/authorize-medical` (21-22)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-229300&t=23Wigz7X7PSKDgF8-0&scaling=min-zoom&page-id=5138%3A422026), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-229301&t=23Wigz7X7PSKDgF8-4)

<details><summary>Screenshots</summary>

<img width="324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWYrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aff9e239b1102b25ebdf715ecc4b3effae9ca9bb/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Veteran Identification Information page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Veteran Identification Information page has been implemented, with the specs outlined above.

**Comment by mtri** [comment]
Looks good other than:

- The progress stepper chapter H2 should change based on non-Veteran vs Veteran
Veteran: "Your information"
Non-veteran: "Veteran's information"

**Comment by mtri** [comment]
One more edit – 
- Add "You must enter a Social Security number or VA file number. In most cases, your Social Security and VA file numbers are the same." below the h3. [Design viewable here ](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=455%3A76935&node-id=455-145436&viewport=5943%2C-788%2C0.38&t=GOF9JuC2Xs7cacai-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=456%3A171489)

(Sorry, due to a Figma configuration issue the iteration of the screen linked in the description did not show the text layer.)

**Comment by cosu419** [comment]
Ready for review @mtri

**Comment by mtri** [comment]
Looks good!
