### ISSUE TITLE
Kick off for VA Notify

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83718]
## Background

<img width="1810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88a25f9aa1315805bef65ec203ec96d514175f2e/image.png" alt="image.png" />

After a user downloads their completed form (`appoint-rep/download` page) and clicks "Continue":
1. **All users** will be routed to the final page in the flow, titled "your next steps" (`appoint-rep/next-steps`).
2. **Authenticated users with an email on file** will receive an email notification, confirming the form completion and reiterating next steps.

Content for the email notification has been [provided by CAIA](https://dvagov.sharepoint.com/:w:/r/sites/SitewideCAIA/_layouts/15/Doc.aspx?sourcedoc=%7BC3079214-7C45-4B47-B72C-F8AD962F23CF%7D&file=2.3%20ARM%20AAR%20V1%20tool%20email%20content.docx&action=default&mobileredirect=true), but in order to send out this email notification, we need to partner with the VA Notify team.

Open questions: 
1.  Who is our Privacy Officer to review our email notification content?  ~Marvis Harvey~  ~Rochelle Foxworth~  Gina Siefert
2.  Can we include a completed PDF in this email notification for re-download?  We could store the PDF itself, or the information to generate the PDF.
3.  What system will kick off the notification? Please note the system should be inside the VA or have an ATO. (ex., BVA hearing reminders are kicked off from Caseflow) Will create a request in vets-api that will create a Sidekiq job to engage VA Notify's code to send out the email notification.
4.  Would we prefer to provide contact information for the recipients or should VA Notify look this up by Veteran ID? If by ID, please let us know what identifier is used in your system.  (ex., VAPROFILEID, PID, BIRLS, ICN, etc.) The Sidekiq job should be able to provide the email address, so we will provide contact information.

VA Notify resources:

1. [VA Notify playbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#playbook)
2. [VA Notify intake form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=bevnobev%2C+mjones-oddball&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D)
3. #va-notify-public Slack channel is available for questions about the API 

## Tasks
- [x] Answer open questions
- [x] Submit a [VA Notify Intake Form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=bevnobev%2C+mjones-oddball&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D) and request a kick off call -- include dev representation on the call
- [x] Schedule a kick off call
- [x] Outline next steps for the ARM team to make email notifications a reality (could be similar to the [General Steps](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#general-steps) in the VA Notify Playbook)

## Acceptance Criteria
- [x] The ARM team has presented their need for email notifications to VA Notify, and has a grasp on what remaining tasks are required to make this a reality for our MVP.

**Comment by oddball-lindsay** [comment]
Intake ticket for VA Notify: https://github.com/department-of-veterans-affairs/va.gov-team/issues/84313

**Comment by oddball-lindsay** [comment]
Including a download link in the email notification, that confirms form completion and reiterates next steps:
1. We could consider a download link, it would need to point to a place for a user to sign in and then they can download the form.  
2. Burials team is including a link, where a user will then sign in to view the form AND sign the form.
3. Patient check in has users enter pieces of info to validate their identity, without needing a full sign in.  This would likely need a different endpoint, but we can use the same code for generating the PDF.  
4. We could also consider a temporary pass code that's sent to the email, unsure if this is something that exists with VA today.

Locating a Privacy Officer for approval of our notification content:
1. Perhaps Parker knows, or can ask our contract COR.
2. Can also try the Privacy collab cycle stuff to see if they have a contact.
3. Patrick Bateman from the OCTO side can also speak from the collab cycle perspective.

Next steps when we're ready to move forward:
1. Get onboarded to VA Notify's self-service portal, which has self-service documentation for using the APIs.
   1. Send a list of users' VA emails, that require access to the self-service portal.  Login will be with PIV.
   2. Get API key to the Staging/Production environment.  
   2. Build our email notification and trigger, referencing templates and the API documentation.
   3. There's a reusable model in vets-website.
2. The Strike Team (Samantha Jennings is the PM) can help us if we get stuck. 
   1. They can also help us with the actual build of the notification content and trigger, would need 2-4 weeks (1-2 sprints) of lead time.  
3. Intake ticket is fine for ongoing collaboration.

**Comment by oddball-lindsay** [comment]
Connected with Holden and we might as well request access to the self-service portal now. Will see who on the team would like access. 

As for the download link in the email notification, we're not sure the work is worth the return and are leaning towards saving this for future iteration (not MVP).  Will run this by the team and see what they think.

**Comment by oddball-lindsay** [comment]
No word from the Privacy Officers I reached out to, asking Parker and also Platform Security if they have any recommendations.  

Also asked the team who wants access to the self-service portal.

Open question: Do we want VA Notify's help building out the trigger?

**Comment by oddball-lindsay** [comment]
Secured a Privacy Officer and received core team access to VA Notify's self-service portal!  We also have a good idea of what's needed to engage VA Notify if we do decide to accept their offer to help -- mentioned over in the intake ticket:
> we would need the notification template ids from Staging and Production and the personalizations you are wanting to pass. We would also have to know when you anticipate releasing this and coordinate the release together. We could set up weekly meetings, in order to plan how we can accommodate this seamlessly, especially in regard to the staged rollout/feature flag piece.

Will pursue additional work in separate, more specific tickets.  Our order of operations seems to be:
1. Meet with Privacy Officer to get sign-off on email content
2. Decide if we want to include the download link in this first iteration
3. Decide if we want VA Notify's help
