### ISSUE TITLE
Veteran Service Information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83720]
## Issue Description

The Veteran Service Information page will be available to:
1. 21-22a form ONLY 
2. Authenticated and unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users

Content is dynamic based on:
1. If the user is a **Veteran**, the h2 should reference "Chapter 2". If the user is a **non-Veteran** the h2 should reference "Chapter 3".
3.  Input fields designs
     1. Auth Veterans, pre-select the branch of service if information exists in their profile. The h3 should read "Your service information".
     2. Unauth Veterans. The h3 should read "Your service information".
     3. non-Veterans (auth and unauth). The h3 should read "Veteran's service information".

The information collected on this page will be routed to the forms as follows:
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    - Field 6: Branch of Service (Multi-select checkboxes)

**URL**: `/veteran-service`

**Previous paths**: `/veteran-identification` 

**Next paths**: 
1. `/authorize-medical`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-229393&t=23Wigz7X7PSKDgF8-0&scaling=min-zoom&page-id=5138%3A422026), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-229394&t=23Wigz7X7PSKDgF8-4)

<details><summary>Screenshots</summary>

<img width="317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTcrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--077ac9bc13ff6deebeb7984332987ea70df9d156/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Veteran Service Information page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Veteran Service Information page has been implemented, with the specs outlined above.

**Comment by mtri** [comment]
- Currently this page is showing for 21-22. This page should only show for the 21-22a.

- The progress stepper chapter H2 should change based on non-Veteran vs Veteran
Veteran: "Your information"
Non-veteran: "Veteran's information"

**Comment by cosu419** [comment]
Ready for review @mtri 

> Currently this page is showing for 21-22. This page should only show for the 21-22a.

Going to punt on this because there's an in progress ticket where we actually set the form type (ie I'm phasing out the dummy screen that currently toggles 21-22 vs 21-22a). Will make a note of this in that ticket.

**Comment by mtri** [comment]
If displaying/hiding this page based on the form type is covered by another ticket, I think we're set here. Looks good!
