### ISSUE TITLE
Appoint a Rep Digital Submit - User Test - Collab Cycle + Recruit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#83732]
## Issue Description
User testing of Appoint a Representative Digital Submission flow.

## Tasks

- [ ] Request research review
- [ ] Update user test to reflect collab cycle edits
- [ ] Set-up Enjoy HQ project
- [ ] Kick-off with Perigean
- [ ] Create sign-up sheet
- [ ] Transfer demographics to sign-up sheet & Excel
- [ ] Create folders & update guideline documents
- [ ] Create notetaker template
- [ ] Set up Slack channel w/ notetakers & observers
- [ ] Kick-off with notetakers
- [ ] Conduct pilot session
- [ ] Kick-off with observers
- [ ] Create debrief Mural
- [ ] Create conduct interview Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by oddball-lindsay** [comment]
Shane is reviewing the plan/convo guide even though Michael is still editing -- Shane seems okay with that.  Targeting recruitment sooner rather than later.

**Comment by jfinnerty13** [comment]
All tasks completed - closing ticket.
All documentation can be referenced in our Slack channel: https://dsva.slack.com/archives/C06QVMQV97D
