### ISSUE TITLE
Tip of The Sprint: Embedded Video Best Practice

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83739]
## Issue Description

- Best way to embed video is to paste the link directly into the body text. 

---
## Tasks
- [x] Draft Tip of The Sprint
- [x] Review draft with PC Team
- [x] Schedule ToTS for Tues 5/28/24 in #platform-content channel in Slack

## Acceptance Criteria
- [x] Tip of The Sprint posted
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
Post Scheduled. Once posted, this ticket can be closed.

**Comment by jknipes** [comment]
Tip has been posted, movin to _Done_
