### ISSUE TITLE
Mock Data Rework

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#83735]
## High Level User Story/ies
As a product development team, we are confident that the mock data we have for our staging users represents all of the use cases across the debt portal experience. 

## Definition of done
- [ ] The debt resolution team has a clear understanding of the mock data associated with each staging users
- [ ] The debt resolution is comfortable that all use cases are captured by the mock data we have available across the staging users they use. (Any necessary updates to mock data repo has been made to make this statement true) 
- [ ] [Staging User Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/staging-users-debtproducts.md) to clearly articulate the mock data captured within the variety of staging users the debt team uses has been updated and is clear to anyone looking to interpret this information.

**Comment by Tom-Davis** [comment]
Closing this Epic as the work is completed - if we require additional data changes we can create a new epic under the then current quarterly SEpic.
