### ISSUE TITLE
[Discovery][Event Bus] Determine what administrative tasks need to be completed

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#83737]
### Background
We need to determine what administrative tasks are required for us as a new application running in the VA ecosystem. It's safe to assume that we will need to create all of these artifacts and have them approved by the appropriate parties, but it is worth checking to make sure that we need all of these:
* ATO (Authority to Operate)
* PTA / PIA
* VASI ID
* eMASS ID
* WASA Scan
* ESECC
* Corp DB Data Access request

###  Event bus documentation
https://department-of-veterans-affairs.github.io/ves-event-bus-developer-portal/administrative-requirements/

### Tasks
- [x] Determine if we need a new ATO
- [x] Determine if we need a new PTA / PIA
- [x] Determine if we need a new VASI ID
- [x] Determine if we need a new eMASS ID
- [ ] Determine if we need a new ESECC
- [ ] Determine if we need a new WASA Scan
- [ ] Determine if we need to fill out a Corp DB Data Access request

### Acceptance Criteria
- [ ] It is clear to us what new artifacts need to be created / approved by the appropriate parties and those requirements are documented and new tickets created.

**Comment by jerekshoe** [comment]
#### Findings
> ATO
We should be able to work with platform security to update the existing one for VA.gov

> PTA / PIA
Same as above, we should be able to work with platform security to update the existing one for VA.gov

> VASI ID
Should be able to use the same one as VA.gov
