### ISSUE TITLE
Update Style Guide to Include Internal Links Opening New Tabs

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83745]
## Issue Description
After 2 sprints, any internal links opening in new tabs will become a launch blocker.
We need to add this to our list of Launch Blockers in Confluence, so no pages containing links with this behavior will be deployed.

---
## Tasks
- [ ] Draft language for the style guide
- [ ] Review with PC Team
- [ ] Add language to Style Guide

## Acceptance Criteria
- [ ] Internal Links guidance will be added to the Style Guide
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/83745?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
Recently announced plans by k15t to correct the behavior of **all** links has caused the team to pause work on this project: 
>Laura Parraga Gonzalez (K15t) commented:
HI Joe,
All links will open in the same tab after our improvement is implemented. No matter if they are internal, external, point to your Confluence, to the Viewport site or to any other website.
We are aiming to include the issue in our next release, hopefully at the beginning of next month.
Cheers,
Laura

**Comment by jknipes** [comment]
Content team has verified that k15t has corrected the links behavior and it is no longer necessary to add this to the Style Guide. Closing ticket as complete.
cc: @EWashb
