### ISSUE TITLE
[CST] [DataDog RUM] Confirm that RUM logging looks correct on staging

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#83751]
## Issue Description
Enable RUM logging for CST on staging via `cst_use_dd_rum` feature flag. Check that RUM and Session Replays look correct in DataDog for staging CST.

---
## Tasks
- [x] Enable `cst_use_dd_rum` feature flag on staging
- [x] Confirm that RUM logging and session replays are showing up correctly for CST in DataDog
- [x] Confirm that no PII is being logged

## Acceptance Criteria
- [x] RUM logging looks correct in DataDog
- [ ] Session replays look correct in DataDog
- [x] No PII is being logged to DataDog

**Comment by samcoforma** [comment]
Marked as closed because all PII issues were resolved, but re-opening it for now as I investigate consistent replay css rendering issues
