### ISSUE TITLE
Structural data discovery: Health services/Location and contact info

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8375]
## Problem Statement
How might we improve the content editorial experience for facility specific services?

## Current behavior
- The current manual process of entering data for facility-level service descriptions is not efficient or scaleable. (For example: VISN 4 had 49 facilities, each with 40-70 health services) 
- Much of the content is repeatable and may be converted to structured data with fields for content entry 

![location and contact info](https://user-images.githubusercontent.com/55411834/80224985-b521b680-8607-11ea-9bc8-97a83ee728f4.png)
 
## Goal
Content structure which improves entry/migration and makes data searchable

## Objectives or Key Results this is meant to further
- Objective 2: Deliver meaningful facility information 

---
## Tasks
- [ ] Determine the right approach for refactoring/structural data for VAMC facility specific service descriptions, considering:

- [ ] What content can be pre-populated from health service level to health system level?
- [ ] Drupal vs automation?
- [ ] Tech debt resulting from the approach
- [ ] Ability to make the data searchable for display by other VA.gov apps
- [ ] Ability to make the data visible to Google (schema.org tags)

## Acceptance Criteria
- [ ] Recommendation for approach to refactoring VAMC facility specific service descriptions
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
May be irrelevant because Service Location paragraph type made this better

**Comment by jilladams** [comment]
We think this is outdated entirely except for: schema.org which may or may not be in another ticket.
