### ISSUE TITLE
Revise Detailed design for success path and successful backup path of submission experience

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#83764]
## Issue Description
Following from [Detailed design for success path and successful backup path of submission experience#78183](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78183), we have multiple design variations that we need to whittle down and refine to move forward.

**Updates include these touchpoints:**
1. Redesign of confirmation page (2 states)
2. Redesign of loading screen
3. Add/redesign email notifications (3 messages)

**Context for design**
There are two main claim journeys represented in this redesign.
Path A: A claim cested in under 30 seconds 
Path B: A claim that takes longer than 30 seconds to cest, but is still successful

The updated submission model has three statuses: Prepare, Send, Receive
Path A will include a confirmation page and two emails: claim “sending” and “received” 
Path B will include a confirmation page and three emails: claim “preparing,” “sending,” and “received”

Design details for additional touchpoints in [Happy path and Backup path in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711478063212/5b744d81f239e5ae30aaf28ff98414a9dc3c7e72?wid=0-1713217928067)

## Desired user outcomes
1. Address the uncertainty Veterans feel when they do not immediately receive a confirmation email after submitting the 526. 
2. Provide Veterans with timely and truthful information about claim submission.

Out of scope
3. Create a record of submission for Veterans to keep
 
See [feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f668515f53a7d1957d9ab92aba95ad43f647b311/products/disability/526ez/product/feature-briefs/Submission%20Experience.md#problem-or-opportunity) for the up-to-date problem statements of the larger initiative

## Working documents
1. [Figma file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f668515f53a7d1957d9ab92aba95ad43f647b311/products/disability/526ez/product/feature-briefs/Submission%20Experience.md#problem-or-opportunity)

---
## Tasks
- [x] align on a submission model
- [x] design touchpoint for "Human-centered reference number for Veterans w/o claim ID"
- [x] narrow down design variations with stakeholder feedback - [slack thread](https://dsva.slack.com/archives/C053UDWMH7U/p1716322278224809?thread_ts=1715891584.684699&cid=C053UDWMH7U)
- [x] write text for preserving the ideas while we put this ticket on hold - written in [feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Submission%20Experience.md#working-solution)
- [ ] refine a smaller subset of design variations with stakeholder feedback
- [ ] check smaller subset of design variations for engineering feasibility (postponing, @pacerwow to find time with engineers to review this as well as other aspects of the epic - [slack thread](https://agilesix.slack.com/archives/C04MJV66ZPC/p1717431405046449?thread_ts=1717430195.188259&cid=C04MJV66ZPC))
- [ ] start Collaboration Cycle/ start Design Intent - after we figure out our release plan / phasing

## Acceptance Criteria
- [ ] Internally validated designs for ways to help Veterans keep track of their claims post-submission
- [ ] Share early designs with VBA

**Comment by mengA6** [comment]
re: 

> design touchpoint for "Human-centered reference number for Veterans w/o claim ID"

I think we don't actually want to do this, since later we will provide a claim ID. It's something to check on in research / internal investigation, but I think another reference number will add confusion more than it will assist with anything (assuming the Veteran can get support to identify the claim by date initiated / submitted).

**Comment by mengA6** [comment]
I wrote up the on-hold design work in the [feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Submission%20Experience.md#working-solution). With this, we can put it on hold

**Comment by alatempa24** [comment]
@mengA6 I have a curiosity if we can segment out the remaining tasks in a new ticket so we can close this one? That way we have a clear start/stop for a new sprint when we come back here. What are your thoughts?

cc @pacerwow

**Comment by pacerwow** [comment]
Curious if this can be closed. I believe we've addressed the remaining tasks in other tickets. @mengA6 @alatempa24

**Comment by mengA6** [comment]
sorry I missed your earlier comment @alatempa24 . Yes, closing this. We should capture any relevant work in tickets we will create for future iterations.
