### ISSUE TITLE
Socialize FDG launch

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#83768]
## Purpose
Let's share the site out to VFS teams.

## Tasks
- [x] Announce FDG's availability in Slack
- [x] Announce in ToT
- [x] Announce in WklyShip
- [x] announce in brag book
