### ISSUE TITLE
SC | Add new homelessness questions

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#83772]
## Value Statement

**_As a_** Veteran who is homeless and at risk of being homeless

**_I want to_** have the option to let VA know my current living situation

**_So that_** my claim may be processed in a timely manner

---

## Background Context

- Part of the 20-0995 paper form update expands the homelessness question, so we can capture more details about the Veteran's living situation. We want to build the pages and functionality for the form. There will be another ticket for exact content updates.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] New screen added to capture whether or not Veteran is homeless or at risk of being homeless
- [ ] If yes, show new screen that includes optional question and checkbox selection to explain the Veteran's living situation
- [ ] If Veteran answers 'another reason not listed', show an optional screen that includes a textarea input that allows Veteran's to explain their situation
- [ ] New screen added to optionally capture point of contact's name and telephone number. Phone number validation is included

## Designs and Build Notes

- [FIGMA](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=546%3A9026&t=nwR0gyXxvABhNFIX-1)

### Enablement team (if needed)
@jstrothman 

## Out of scope

- Exact content and content approval
- Section ordering

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Marked as blocked until Lighthouse provides an updated submission endpoint.

**Comment by shaunburdick** [comment]
Will need to check with Michael Hobson, if the API adds support for new fields and they default to blank, will that "mean" something as apposed to it not being filled out.

**Comment by jstrothman** [comment]
> Will need to check with Michael Hobson, if the API adds support for new fields and they default to blank, will that "mean" something as apposed to it not being filled out.

I recommend checking with our OBA SME, Andrew Gray--he is familiar with how claims processors interpret submitted information, and this question is more of a processing question than a technical one

**Comment by eileen-coforma** [comment]
I will reach out to Andrew

**Comment by shaunburdick** [comment]
> > Will need to check with Michael Hobson, if the API adds support for new fields and they default to blank, will that "mean" something as apposed to it not being filled out.
> 
> I recommend checking with our OBA SME, Andrew Gray--he is familiar with how claims processors interpret submitted information, and this question is more of a processing question than a technical one

Sorry for any misunderstanding. This was a note to remind me to check in with Michael in our next meeting. This is both a process and a technical one. I need to know what LH will do if we do not send a response to those questions. With that knowledge, we can then check with Andrew to see how that would be interpreted. No response is different to an empty response, so they might be handled differently.

**Comment by anniebtran** [comment]
Closing because when we're done with prototype testing, we'll just shift it over. Using #90568 to cover remaining work
