### ISSUE TITLE
DR | PDF Attachment Page Validation 

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#83782]
## Background Context

This is a spike task regarding validating PDF pages to better detect issues with PDFs similar to how EMMS validates PDF files.

## Tasks
- [x] Scope work to implement page-level validation of PDF attachments

## Definition of Ready
- [ ] Examples of multi-page PDFs with a single corrupt page available
- [ ] #83503 complete

## Definition of Done
- [ ] Follow-up tickets for development tasks have been created

**Comment by dfong-adh** [comment]
Summary of spike findings:

`pdf-reader` (gem already in use) can be used to parse PDF files. If a PDF is malformed, an exception will be thrown.

Example:
```ruby
reader = PDF::Reader.new(file)
reader.pages # PDF::Reader::MalformedPDFError thrown
```

**Comment by dfong-adh** [comment]
Followup ticket: #85749
