### ISSUE TITLE
BE | Profile | Military Information | Add Period of Service Type

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83780]
## Background
Period of service type needs to be added to the profile.

## Tasks 
- [x] Map service type code and text to response.
- [x] Document list of reference values for service type.
- [x] Add specs.

## Acceptance Criteria 
- [x] The military information page returns period of service in staging.

**Comment by tpharrison** [comment]
Have reviewed the BE code and realized that the service type code is already being mapped (but not the text)...
```
# lib/va_profile/models/service_history.rb
personnel_category_type_code: episode['period_of_service_type_code']
```

I added this mapping a couple of years ago, but I'm not sure why I named it `personnel_category_type_code `.

Here are the records I see in VADIR.
| Code | Text                                             |
| ---- | ------------------------------------------------ |
| A    | Active Duty - Obsolete                           |
| G    | Guard                                            |
| R    | Regular                                          |
| V    | Reserve                                          |
| Z    | Unknown or Not Applicable                        |
| DVN  | DoD provided a NULL or blank value               |
| DVU  | DoD provided a value not in the reference table  |
| CVI  | Value is calculated but created an invalid value |
| VNA  | Value is not applicable for this record type     |

There is a prefill form that uses a different mapping, so I have to clarify code/text mappings with another engineer before I make the changes.

Once the code/text values are verified, I'll add them to the FE ticket for reference.

**Comment by mtcA6** [comment]
Weird so there isn't a basic "Active Duty" any longer?

**Comment by tpharrison** [comment]
Not sure.  That's what I have to verify.

**Comment by tpharrison** [comment]
The values that I listed above are from the wrong table.

Here are the correct lookup values from the `personnel_category` table (which is where I got the name originally).
| Code | Text
| ---- | ------------------------------------------------------------ 
| A    | Active duty member                                           
| B    | Presidential Appointees of all Federal Government agencies   
| C    | DoD and Uniformed Service civil service employee, except Presidential appointee 
| D    | Disabled American veteran                                    
| E    | DoD and Uniformed Service contract employee                  
| F    | Former member (Reserve service, discharged from RR or SR following notification of retirement eligibility)
| H    | Medal of Honor recipient                                     
| I    | Non-DoD civil service employee, except Presidential appointee 
| J    | Academy student                                              
| K    | Non-appropriated fund DoD and Uniformed Service employee (NAF) 
| L    | Lighthouse service                                           
| M    | Non-federal Agency civilian associates                       
| N    | National Guard member                                        
| O    | Non-DoD contract employee                                    
| Q    | Reserve retiree not yet eligible for retired pay ("Grey Area Retiree") 
| R    | Retired military member eligible for retired pay             
| T    | Foreign military member                                      
| U    | DoD OCONUS Hires                                             
| V    | Reserve member                                               
| W    | DoD Beneficiary, a person who receives benefits from the DoD based on prior association, condition or authorization, an example is a former spouse 
| Y    | Service affiliates                                           
| DVN  | DoD provided a NULL or blank value                           
| DVU  | DoD provided a value not in the reference table              
| CVI  | Value is calculated but created an invalid value             
| VNA  | Value is not applicable for this record type
