### ISSUE TITLE
Profile: Sprint 38 (6.5.2024-6.18.2024)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#83787]
## Sprint Links
[Previous Sprint ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75223) 
[Next Sprint ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/)

## PTO
- Tom OOO week of 6/16 
- Liz's last day 6/14

## Sprint Goals
- Deploy the military info period of service type text (active vs inactive) 
- Liz's transition - ensuring that we have a clean and clear path forward on any items 
- Support the MHV notification preference roll out with initial mapping 
- Privacy/Security statements for VA Profile 
- Privacy/Security disclaimers for notification preference page 
- Profile completeness research docs 

## Military Info 

**FE**
- [x] - #83581
 
**BE**
- [x] - #83780

## Maintenance Period Alerts

**FE/BE**
- [ ] ~-#82051~ moved to backlog, Tom and Adam were not able to complete 

## General 

**Design**
- [x] -#80985
- [x] -#85100
- [x] -#85101

**FE**
- [x] -#82509
- [x] -#83169
- [x] -#83636
- [x] -#83776

## Swagger Docs 

**BE**
- [ ] ~-#83513~ not completed in sprint moving to backlog 

## CH33 Edu DD Updates 

**Design**
- [x] -#81368 - the design component for this was approved. we can't close this story out yet until the experimental component is created by the design system team but the work we intended to complete by presenting this was completed in this sprint

## Onboarding 
**DM/FS**
- [x] -#84415
- [ ] #85544
- [ ] ~https://github.com/department-of-veterans-affairs/va.gov-team/issues/85874~ moved to backlog

## Privacy and security 
- [x] #85603

**Comment by ACParker89** [comment]
@asiisii
