### ISSUE TITLE
[EPIC] OCTO Health: Deprecate coronavirus research registration tool

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#83785]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: OCTO Health
- **OCTO product owner:** Patrick Bateman
- **Product name:** Coronavirus research registration tool
- **Product manager:**  Patrick Bateman
- **Slack channel:** https://dsva.slack.com/archives/C02BTDTEPNH (but best is to just DM Patrick)
- **Dedicated content writer on your team (if you have one):** N/A
- **Dedicated a11y specialist on your team (if you have one):** N/A
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  Turning something off :tada:

### What's the nature of your initiative and desired outcomes?

Turn off https://www.va.gov/coronavirus-research/. 

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

Not urgent to get it turned off, but sooner would be better.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
Turn it all off at once.

 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [ ]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Tool in production today](https://www.va.gov/coronavirus-research/)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Terry Nichols`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [x] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85820
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/91753
```

**Comment by kristinoletmuskat** [comment]
Hey hey @batemapf, when we deprecate a page we always put in a redirect so that the old url doesn't 404 (like if a user has it bookmarked). Do you know where it might make the most sense to redirect this one?

**Comment by batemapf** [comment]
Maybe https://www.va.gov/coronavirus-veteran-frequently-asked-questions/?

**Comment by batemapf** [comment]
...alternatively https://www.research.va.gov/for_veterans/

**Comment by kristinoletmuskat** [comment]
Noting that we'll also need to remove entry points to this link (like this one in the screenshot below on https://www.va.gov/health-care/covid-19-vaccine/)

![Screenshot 2024-05-22 at 2 53 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/1f29870e-8a26-44d4-835e-1a875e4ab71d)


Of the top of my head, I'm thinking redirecting to [the research.va.gov site p](https://www.research.va.gov/for_veterans/) might make more sense, since someone bookmarking this link I would say would be primarily interested in research opportunities vs covid-related information.

**Comment by kristinoletmuskat** [comment]
@strelichl I think we can implement the redirect with public websites and then put the actual drupal page deprecation in the content backlog (since the team is super stretched). I can create the redirect ticket tomorrow. 

@batemapf I'm assuming your team owns the tool code for https://www.va.gov/coronavirus-research/volunteer/sign-up -- I'm not sure if we do anything to take old code down other than redirecting it? Do you know?

(note for myself) Will also need to redirect the tool url and all child pages: https://www.va.gov/coronavirus-research/volunteer/sign-up

**Comment by kristinoletmuskat** [comment]
@batemapf do you have approval from stakeholders that would manage these pages? Or anyone we need to notify?

**Comment by stephenBarrs** [comment]
@kristinoletmuskat the OCTO Health Engineering team (we work with @batemapf) will remove the old code once the redirect is in place.

**Comment by kristinoletmuskat** [comment]
Whoops I just closed this! But see we still need to deprecate.

**Comment by megzehn** [comment]
Hi @strelichl, I opened a ticket to find and remove entry points. I need Randi's help, but once she gives me a list of the nodes on Drupal, then it should be a quick task.

**Comment by stephenBarrs** [comment]
The redirect ticket is closed so I am commenting here. I still see the links for the related apps working in staging and production: 
https://www.va.gov/coronavirus-research/volunteer/sign-up
https://www.va.gov/coronavirus-research/volunteer/update/update-form?id=123456abcd

**Comment by kristinoletmuskat** [comment]
Thank you @stephenBarrs , we must have missed those for some reason. I'll open a new redirect ticket for those.

**Comment by kristinoletmuskat** [comment]
Here is the redirect ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92835
