### ISSUE TITLE
Toxic Exposure - [Discovery] Form 21-526EZ PDF as a supporting document - polling for status

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#83799]
## Story
As a steward of the Form 21-526EZ workflow, I would like to know the status of the Form 526 PDF submission to the eFolder when going through the primary path.

## Goal:
We need a method to inform the vets-api system of the status of the Form 526 PDF as a supporting document of the established claim.

## Context:
With the migration to the Lighthouse synchronous submit endpoint, Lighthouse returns after a claim is established and returns a claim id from VBMS representing the established claim.
However, this does not ensure that the Form 526 PDF that was generated in the process got submitted along with the claim being established.
If we were to utilize the Lighthouse synchronous submit endpoint, we would not know if the generated Form 526 PDF made it into the eFolder for the Veteran in VBMS.

## Tasks
- [x] How do we trigger another job after we get the claim id (submitted_claim_id) back from LH?
- [x] How often do we "poll" the claim using the `benefits_claims/service#get_claim`. i.e. is this like the `SubmitForm526Job` with the exponential back-off?
- [x] When do we stop "polling"? i.e. different conditions such as "the Form526 PDF label is in the get_claim response"
- [x] Do we need to record the status from Lighthouse in the vets-api Form526Submission record? (this would involve adding another column in the db)
- [x] What metrics need to be in place for us to monitor success? Failure? Do we need to set up an alert? i.e. when the 48 hour retry from Lighthouse is up?

## Acceptance Criteria
- [ ] Discovery is documented [somewhere here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/evss-to-lighthouse-migration)

**Comment by alatempa24** [comment]
Per Kayla, The documentTypeLabel should come back as VA 21-526 Veterans Application for Compensation or Pension, from [this DSVA Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1716382860499509).

**Comment by mchae-nava** [comment]
Posting current (unfinished) notes as a status update. Plan on finishing today

	•	How do we trigger another job after we get the claim id (submitted_claim_id) back from LH?
	⁃	Ideally synchronicity allows this to be as simple as “when we get the submitted_claim_id
	⁃	Can mirror how we queue backup submission jobs (`queue_central_mail_backup_submission_for_non_retryable_error is a good reference)
	⁃	Should make use of a unique job id (a la backup) for monitoring purposes
	•	 How often do we "poll" the claim using the benefits_claims/service#get_claim. i.e. is this like the SubmitForm526Job with the exponential back-off?
	⁃	Question is answered by how we expect server load to fluctuate with time, and how quickly we can reasonably expect the data
	⁃	From 5/21 meeting with LH: “The document upload can take up to an additional 15-20 seconds. Lighthouse will keep retrying for up to 48 hours in case of a planned outage. After 48 hours, LH recommends the 526 polls for status to ensure the 526 PDF is included in supporting documents for the claim, using the getclaim endpoint with the claim ID. This retry is only for the PDF generation.”
	⁃	The Best Case means we poll minutes after submission
	⁃	Worst case, after two days
	⁃	We can compromise and implement two polling periods
	⁃	Based on our EVSS submit metrics (https://vagov.ddog-gov.com/dashboard/mqg-msb-htb/benefits---dbex---evss-to-lh-submit?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1714573665033&to_ts=1717165665033&live=true), activity follows a constant, predictable distribution
	⁃	However, in August 2023, there was a spike of roughly x2 traffic
	⁃	Options for two polling periods:
	⁃	Fixed interval backoff is useful when constant, predictable activity is expected. Not ideal for us.
	⁃	Linear incremental backoff can help us prevent constant failure during outages by reducing the number of polls we make over time
	⁃	Fibonacci backoff is less aggressive than exponential but has a similar effect of reducing concurrency as more retries are attempted
	⁃	Randomized jitter may be ideal in a high concurrency environment where we add a random number to incremental delays
	⁃	Adaptive backoff will make use of concurrency reports to add a certain amount of backoff. This is for a “smart” solution, likely overkill since we never reach volumes high enough for this to matter
	⁃	We ideally want to have a moderate volume of pings hitting the “best case period” and then use exponential of fibonacci backoff during the “worst case” period
	⁃	1st period “best case” polling with linear backoff, 2nd period “worst case” polling with fibonacci/exponential backoff
	⁃	1st period polls for a short (hours) amount of time with a medium volume of pings, 2nd polls for an extended period (day+) with similar volume
	⁃	Single polling period with fibonacci/exponential backoff
	⁃	Single polling period using a similar algorithm to backup. The risk is that this is a lower volume of pings, and can miss out on “best case” submissions, meaning Veterans on average will be waiting longer than expected. Fibonacci alleviates this somewhat.
	•	 When do we stop "polling"? i.e. different conditions such as "the Form526 PDF label is in the get_claim response"
	⁃	Ideally we would make use of certain conditionals to determine whether polling should start
	⁃	valid claim_id
	⁃	success of submission job
	⁃	We should also establish retryable and non-retryable criteria for when polling is in flight
	⁃	Can likely use the same criteria as other jobs
	⁃	Rate limits (429 errors) are still in effect
	⁃	While most likely retyable nowadays, can be non-retryable if volumes are extremely high < likely won’t happen based on historical data
	⁃	Outages (503) are retryable
	⁃	Errors with submission and invalid claim ids are non-retryable
	•	What metrics need to be in place for us to monitor success? Failure? Do we need to set up an alert? i.e. when the 48 hour retry from Lighthouse is up?
	⁃	Consider using aasm (act_as_state_machine)
	⁃	May help prevent some crossed wires between jobs, makes job status apparent and reportable, failure states more easily monitored
	⁃	Should make use of a unique job id (a la backup) for monitoring purposes, which can be reported in logs
	⁃	Alerts follow a pattern:
	⁃	Alert when non-retryable error is reported
	⁃	Alert when returnable attempts are used up
	•	Do we need to record the status from Lighthouse in the vets-api Form526Submission record? (this would involve adding another column in the db)
	⁃	

- The job itself:
	- Can be confirmed in VBMS by LH Benefits intake API
		- https://staging-developer.va.gov/explore/api/benefits-intake/docs?version=current
	⁃	Should make use of a unique job id (a la backup) for monitoring purposes
	⁃	Should ideally comprise of two separate polling periods, first to hit best case scenarios, and one to poll two days after in the event of LH failures
	⁃	At a minimum should make use of a job id and logging to DataDog
	⁃	Can use state machine to make error states more defined

**Comment by mchae-nava** [comment]
Making a note to self to post notes in DSVA slack and scope for follow up ticket

**Comment by aurora-a-k-a-lightning** [comment]
@mchae-nava unformatted notes right back at'cha
```
notes about mark's notes

How do we trigger another job after we get the claim id (submitted_claim_id) back from LH?
- "Can mirror how we queue backup submission jobs (queue_central_mail_backup_submission_for_non_retryable_error is a good reference)"
-- how is this method a good reference? we don't see this used anywhere
--- is this part of the manual backup submission process?
-- shouldn't we perform this in the ancillary_jobs trigger?
--- app/models/form526_submission.rb:419 
----like here?
- "⁃ Should make use of a unique job id (a la backup) for monitoring purposes"
-- if we make use of what is currently in place for creating jobs, there are logs set up to capture this already
--- follow the chain in the `JobTracker#with_tracking` method. 
---- there is a `log_info` method that has the job_id as part of the message output

How often do we "poll" the claim using the benefits_claims/service#get_claim. i.e. is this like the SubmitForm526Job with the exponential back-off?
- How does the Sidekiq retry interval work?
-- how much control do we have over the Sidekiq retry intervals?
--- is what we currently have in the codebase now for our regular ancillary/backup job retries good enough for the PDF polling?
--- how does Team 2's (Nathan's) document polling work?
---- should we use the same thing here?
---- is it in the codebase yet?
---- this is actually different than DOcuments, so it may not work

Two fastest options for MVP:
1. use sidekiq as it is with the retry set approxamtely over 48 hours
-- do we need to wait, let's say, 1 minute, before kicking off this job?
--- because we have to account for the time for Lighthouse to get the PDf in there, which they said is 15 - 20 seconds, to... whatever...
2. if the job does not get a favorable response (that the supporting document isn't there) trigger another of the same job
-- we would choose an interval to try the job again
-- problem: we would have to know when 48 hour is up
--- you can see that from the submission or form526jobstatus created at
3. recursive polling with the same job (wait <an interval> then try the benefits_service#get_claims method again, check the repsonse, repeat) 
--- we can make it stop from the submission or form526jobstatus created at 





When do we stop "polling"? i.e. different conditions such as "the Form526 PDF label is in the get_claim response"

We should continue polling:
-- if the response from benefits_claims#get_claim supporting documents section does not include documentTypeLabel: VA 21-526 Veterans Application for Compensation or Pension
-- how do you trigger a "retry" in sidekiq without the job "failing"?
--- sidekiq may perform a retry based on Job status column in the Form526JobStatus record
--- we may have to set the Form526JobStatus.status to `Form526JobStatus::STATUS[:retryable_error]` by looking at the response from Lighthouse for the supporting document
--- this will trigger the retry process*

* this is an assumption from looking at the code


- we should stop polling:
-- FAIL: if there is a "non-retryable" error from benefits_claims#get_claim
--- maybe if the claim doesn't exist?
---- question for Lighthouse?	
-- SUCCESS: when the response from the benefits_claims#get_claim the supporting document section includes documentTypeLabel: VA 21-526 Veterans Application for Compensation or Pension
-- ???: if this supporting document is not in the list after 48 hours, what do we do?
--- ping Lighthouse? who do we ping?
---- who is in charge of the benefits-documents endpoint?
----- this would have to be "super manual": do we recreate the PDF with generatePDF, and then send through the LH's Documents upload service

What metrics need to be in place for us to monitor success? Failure? Do we need to set up an alert? i.e. when the 48 hour retry from Lighthouse is up?
- aasm: need lesson in what this is
- what can trigger alerts? and from where?
-- emails? 
-- slack?
-- datadog? can it look at the metrics every so often? where can it send it to? 
--- slack, emails? 
---- do we need to create a rake task for this?


Do we need to record the status from Lighthouse in the vets-api Form526Submission record? (this would involve adding another column in the db)
(this wasn't answered)
- most likely not
-- we can use the Form526JobStatus(es) to query if a submission's 526 made it or not
--- query by `form526_submission_id` || `job_id`, `job_class` and `status`

Summary:
1. we need a new job class
  a. i.e. something like "Form526PDFPolling < Job" (naming things is hard)
  b. look at `SubmitForm526 < Job` as a reference
	i. we want things like `wrap_with_logging`, `sidekiq_retries_exhausted`, `perform`
	ii. def perform end_time = Time.now+48.hours; while(Time.now < end_time) response = benefits_claims.get_claim(submitted_claim_id); #check response status; form526_pdf = response.body['supportingDocuments'].find{|d| d.label == "VA 21-526 Veterans Application for Compensation or Pension"'; if (form526_pdf.present?) # do stuff else #try again; end; end
2. we trigger the new job in the `perform_ancillary_jobs` method (here app/models/form526_submission.rb:419)
3. polling interval: 
	a. we need to understand Sidekiq options
	b. can Team 2's Document polling solution be used here?
		i. where is this in the code?
	c. MVP: we use what we have now (exponential backoff over 48 hours)
4. alerting: we need to understand what avenues or patterns already established to alert team members.
5. for MVP, is getting a script or playbook together for an engineer to run every (so often? days? hours?) that checks for failed "Form526PDFPolling < Job"s, get the list and remediate a viable option?
```
