### ISSUE TITLE
Create New VFS Member and/or Team Template for Lighthouse

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83796]
## Description 
We have received an uptick in tickets for a new VFS Team or member to be added but they belong to Lighthouse. Unfortunately, our template does not align with the Lighthouse process so we want to investigate creating one. 

---

## Definition of Done
_What must be done to officially complete this task?_

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Identify what steps need to be completed
- [ ] Write out steps here
- [ ]  Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by GWright321** [comment]
Steps to onboard a new Lighthouse team member:

1. Duplicate the [markdown](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?template=orientation-epic.md) file from the New VFS Team Member Template in GitHub.
2. Create a new branch in GitHub for this update.
3. Convert the markdown template to [YAML](https://github.com/GWright321/Test/issues/new?assignees=&labels=Lighthouse+Onboarding&projects=&template=Lighthouse_Onboarding.yml&title=Onboarding+of+%5Bindividual%5D) format (pending Leadership approval)
4. Modify the content to suit Lighthouse team members.
5. Add a checkbox for verifying the Lighthouse team member, linking it to the Confluence document that contains the Lighthouse [roster](https://confluence.devops.va.gov/pages/viewpage.action?spaceKey=VAExternal&title=Who%27s+Who+-+API+Lighthouse+Program).
