### ISSUE TITLE
Create/Update Platform Site Page for Onboarding Requirements/Access Requirement Prerequisites

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#83795]
## Description 
We've received an increased volume in tickets where folks are asking for access they can't receive because pre-requisites have not been met. We need to create a page to ensure that 

https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1694796460913/9c127c1a097016b0cfbf26b609f5a0a6b623de61?sender=udc895e519e95151fc0244426

Add to this page? https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Zenhub

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Alyssa to ask Erika/Andrea if there are any issues with creating a page like this
- [ ] Alyssa to discuss with Joe Knipes if we should put the content on the existing page or if we want to create a new one
- [ ] Create page in Confluence with step-by-step process or use the existing one above if we think it makes sense 
- [ ]  Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Sending for review in this ticket next sprint: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/87327
