### ISSUE TITLE
[DevOps] Discovery on `dev` implementation for `lorota` IaC Terraform rewrite

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#83792]
## Description

Resource Types:
- AWS::ApiGateway::ApiKey
- AWS::ApiGateway::UsagePlan
- AWS::ApiGateway::UsagePlanKey
- AWS::CloudWatch::Alarm
- AWS::CloudWatch::Dashboard
- AWS::Logs::SubscriptionFilter
- AWS::Serverless::Api
- AWS::Serverless::Function
- AWS::Serverless::LayerVersion
- AWS::Serverless::SimpleTable

## Tasks
- [x] [DevOps] Create new resources in `vaec-cie` corresponding to the resources in `vaec-cms`.
- [x] [DevOps] Open up followup tickets to address next stages of this work.

## Acceptance Criteria
- [x] LoROTA is deployed and running in `dev`.

**Comment by ndouglas** [comment]
I believe this is up and running everywhere, although I might need to fix some bugs or other issues, and I'll need to review 1:1 equivalence with `vaec-cms`.
