### ISSUE TITLE
[Documentation] Request to update authenticated experience folder change-address

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8381]
## Background

This ticket is *not* urgent.

I would like to do two things:

- Rename the [change-address folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/change-address) to "contact-information" to be more inclusive of all of the pieces of contact information we support.
- Move the [change-address folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/change-address) under the [profile folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile) since that's where contact info lives on VA.gov, and since contact info is the flagship product of the profile.

## Tasks

- [x] change-address folder is renamed to contact-information
- [x] contact-information is then moved to live under the profile folder

## Acceptance criteria

- [ ] Renaming/move is completed

**Comment by gmaciolek** [comment]
Hello, I'm doing some ticket cleanup for issues with the documentation-support label. Is this still something you need assistance with?

**Comment by Samara-Strauss** [comment]
This was already done and it looks like it was never closed out. Sorry about that.
