### ISSUE TITLE
[CDP] Fix link to FSR on VHA pages

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#83817]
## Description

Given: A veteran wants to request a FSR from a copay page in the debt portal
When: The veteran clicks on the get help link in the content
Then: The veteran should be routed to the FSR 

[Slack discussion](https://dsva.slack.com/archives/G01KBHYEXV2/p1716417485099279)

## Tasks
- [x] Update link on [Get Help component](https://github.com/department-of-veterans-affairs/vets-website/blob/6c6023bcef9d262122855cf5b822c557cbcd9e87/src/applications/combined-debt-portal/medical-copays/components/FinancialHelp.jsx#L32-L36) to go to FSR.

## Acceptance criteria

- [x] Get help link has been updated to go to the FSR

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [x] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [X] Estimate Points
</details>
