### ISSUE TITLE
[Design] 10-10EZR User flows in Mural

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#83816]
## Issue Description
Alignment updates to the existing various wireframes, user flows and UX form documentation. 

In Figma, the wireframes/flows are not converted to Figma components and the platform team has not plan to develop a high-level wireframe library for Figma. These are the last pages left to-do for the Figma migration. 

In Mural, there is [brand new Platform guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md) on how to document product user flows.

Work-in-progress [EZ wireframe in Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487613901/3f988d8dd69c59340e4b850ef5caf362fa490927?sender=ubf5503bf47b6eb1e92730053)that we can use as a reference.

---
## Tasks
- [x] Determine with team - what is useful in the Figma archive (screen capture) and a plan going forward for using Mural.
- [x] Re-create main source of truth user flows for the EZR in Mural
- [x] Coordinate with EZ/CG team to share resources

## Acceptance Criteria
- [x] A source of truth for all user flows and wireframes that have been updated to the newest guidance
---

**Comment by IMHieuVo** [comment]
[EZR Userflow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694028488812/91947e4f4f9f8536af5a6609e54fced964d3505f?sender=ubf5503bf47b6eb1e92730053)
