### ISSUE TITLE
Add ethnicity Field to 40-10007 Form

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#8382]
## User Story or Problem Statement
As a backend developer, I need to add an ethnicity string field to form 40-10007.

## Goal
The field is added.

## Objectives or Key Results this is meant to further
Adds an ethnicity field to the 40-10007 form.

## Tasks
- [x] Form is updated to include the new field.
- [ ] Tests are updated to account for the new field.

## Acceptance Criteria
- [ ] Form is updated to include the new field, tests are passing.

**Comment by camerontesterman** [comment]
Tests will not pass because EOAS currently does not accept `ethnicity` as a field during the POST.
