### ISSUE TITLE
[Design] Profile: Create confirmation email for when contact information is updated on VA.gov

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8383]
## Background

One of the things that fraudsters do before they hack people's direct deposit information is change a user's contact information. They do this so that any correspondence re: direct deposit then goes to the fraudster, and then the user doesn't know their information has been compromised until it's too late.

We can't stop fraudsters, but we can confirm with veterans that their contact info has been updated so that if they, the veteran, weren't the one making the update, they can get in touch with the VA and have their account locked right away.

## Tasks

- [ ] Figure out all uses cases for this email
- [ ] Work with content to get email copy set 

## Acceptance criteria

-  [ ] Email copy is complete

**Comment by andaleliz** [comment]
Discussed with @DanielleThierryUSDSVA; she'll share some examples here from COVID emails to start from.

**Comment by andaleliz** [comment]
Example from direct deposits here:
https://app.zenhub.com/workspaces/vanotify-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/notification-api/366

**Comment by andaleliz** [comment]
@Samara-Strauss what is the process to launch a new email template? From the issue linked above, and the AC in this ticket, it looks like we provide copy to Todd and he handles the design work. Does VA Notify handle the logic or do our devs?

Use cases I've identified so far:
- user updates, adds, or removes contact information in one section of profile
- user updates, adds, or removes contact information in multiple sections of profile

I can't think of a reason we need to break those out by update, add or remove.

It would be great if there was a way to group multiple changes so that the user would only get one email. I'm thinking through the scenario where someone changes multiple things in one session. E.g.
- updates their home address
- removes their home phone number
- updates their email address

Each one of those is a separate form (and API call I'm guessing), but I don't know that we'd want to send them 3 separate emails for each thing they changed. I think it'd be better if we could send an email that says something like the copy below (have not run this by Danielle, FYI).  But not sure if that's possible, or if that's a question for @erikphansen or someone on the VA Notify team.

Thoughts?

----

Your contact information changed

We're sending this email to confirm that you updated the following contact information in your VA.gov account profile:
- home address
- home phone number
- email address

If you didn't make this update, please call us right away.

Call 800-827-1000 (TTY: 800-829-4833). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. We can help you take the steps you need to protect your bank account information and prevent fraud.

Go to your VA.gov profile

—
You’re getting this email because you made a change to your information on VA.gov.

Please don’t reply to this email. If you need to contact us, go to https://www.va.gov.

**Comment by Samara-Strauss** [comment]
> what is the process to launch a new email template? From the issue linked above, and the AC in this ticket, it looks like we provide copy to Todd and he handles the design work. Does VA Notify handle the logic or do our devs?

If I recall correctly, we reach out to VANotify and let them know there is an email we want to send, and we work with them to get that set up. And yes, I think the last one we did involved some minimal work from Lihan, but nothing crazy.

> Each one of those is a separate form (and API call I'm guessing), but I don't know that we'd want to send them 3 separate emails for each thing they changed. I think it'd be better if we could send an email that says something like the copy below (have not run this by Danielle, FYI). 

I would check in with VANotify about this. I agree sending multiple emails isn't ideal if people update multiple fields, but I am unsure if there's a way to program this so we only send one per session. My guess is there's not, but you should talk to someone on VANotify who can speak more directly to how things work.

Otherwise, the email copy looks good to me!

**Comment by andaleliz** [comment]
@Samara-Strauss thanks - I'll reach out in the #va-notify channel, and create a ticket for content review.

**Comment by Samara-Strauss** [comment]
Sounds good!!

**Comment by andaleliz** [comment]
Content review tracked here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25344

**Comment by andaleliz** [comment]
Submitted VA Notify request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25360

**Comment by ajakabcin** [comment]
This can be closed as subsequent work is tracked in #25360 and #25865
