### ISSUE TITLE
[Design] Logged-in homepage: Notifications audit

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8384]
## Backgrounds

We need to figure out what kind of status updates/alerts that we could show on a new logged-in homepage. We should first focus on the data we already have access to, but we could also include updates we'd like to show if we decide that's a good use of time.

## Tasks

- [ ] Create audit of notification/status updates/alerts we could show on VA.gov today.
- [ ] If time, note additional alerts we'd like to show.

## Acceptance criteria

- [ ] Audit is complete.
