### ISSUE TITLE
[task] HLR | Update form designs to match form updates

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#83861]
## Value Statement

**_As a_** Veteran

**_I want to_** submit the most up-to-date Higher Level Review form

**_So that_** I won't be at risk of having the form returned to me for using an expired form

---

## Background Context

The HLR paper form was updated April 30, 2024. Updates are mostly within instructions and content of the form to simplify and adapt more plain language.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria
- [x] Designs files are updated
- [x] Updates meet requirements
- [x] Designs reviewed by enablement

## Designs and Build Notes

- [FIGMA](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=0%3A1&t=d7uRs6ERaqDspLVp-1)

### Enablement team (if needed)
@jstrothman

## Out of scope
- Development work

## Open questions
- Add here

## Tasks
- [x] Update [introduction page](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=324-14994&t=nruvpawBv5LfPATd-0)
- [x] Update [homelessness question](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=163-29654&t=mZVtMhslidI6xSGR-11)
- [x] Update [AMA question](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=163-29946&t=6sU6H9E8QK6VkOty-11)
- [x] Update [informal conference question](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=325-8622&t=6sU6H9E8QK6VkOty-11)
- [x] Update [call times for informal conference](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=157-35741&t=mZVtMhslidI6xSGR-11)
- [x] Update [call times for representatives](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=157-36035&t=mZVtMhslidI6xSGR-11)
- [x] Update [review and submit page](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=395-37711&t=73M8jW9Bjmex2rNO-11)
- [x] Determine if we want to add a "Written statement" page
  - No, we do not want to tackle that for this update.

## Definition of Ready
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by enablement/stakeholders

**Comment by skylerschain** [comment]
We decided to punt on the "Written statement" page for now for two reason:

1. This opens up a bag of worms in that Veterans could potentially submit information that invalidates their HLR, thus derailing the process for them. We want to investigate the potential user value of this further before deciding to add something like this, given that risk.
2. There will need to be engineering work done to be able to add text into the form, since that text field is not currently in the paper version. So this will not be trivial if/when we decided to add it.

**Comment by eileen-coforma** [comment]
Updates from Shireen's email:

1.     (First attachment) Do we still need to ask Veterans to opt into the new decision review process? If so, do you see any issues with defaulting Veterans to be opted in, and give them the option to instead opt out if they choose to do so? We think doing this will reduce friction and confusion for Veterans when filling out the HLR online.
The opt-in verbiage was removed from the form on September 13, 2022. At that time, we removed what was Section V and item #18 from the form which were related to opting in and replaced the opt-in box with language to the form. This was done for consistency with changes made to VA Form 10182 and was considered a customer friendly change, since it reduced the burden on the claimant.
The language in what was the new Section V was updated to read: “If you are responding to a Statement of the Case (SOC) or a Supplemental Statement of the Case (SSOC): By submitting this form, I agree to participate in the modernized review system for the following issues decided in a SOC or SSOC. I am withdrawing the eligible appeal issues listed in 18A in their entirety, and any associated hearing requests, from the legacy appeals system. I understand I cannot return to the legacy appeals system for the issue(s) withdrawn.”
The opt-in selection should be removed and replaced with the above language.
2.     (Second attachment) The second attachment shows the page describing to Veterans why their issues might not be eligible to for HLR. Would you mind taking a look at that and letting me know if those all still look accurate and up-to-date? We are specifically wondering if the COVID-19 extension mentioned in bullet #1 still applies.
Per Policy Letter 20-02, covid exceptions ended on June 9, 2023. Please remove the covid extension verbiage.
You can remove the bullet “The issue or decision isn’t in our system yet….” as long as the they can add manually add issues.
The bullet about contested issues can stay: “You and another surviving dependent of the Veteran…. “
Can you please provide more context regarding when the two yellow bullets are provided.
The bullet, “You’re requesting a review of a Board…” should be mapped in response to someone requesting a decision review which is an appeal to the Board
The bullet, “You’re requesting a review of a Higher-Level Review decision…” should be mapped when someone has requested a HLR of a HLR.
Please edit this wording to: “If you disagree with a Higher-Level Review decision, the available options for review are a supplemental claim or appeal to the Board of Veterans’ Appeals. Current regulations prohibit a Higher-Level Review of a Higher-Level Review decision.”
Can you please verify if the “coronavirus FAQ page” listed is still active? If not, please remove the sentence, “To learn more about how COVID-19 may affect claims or appeals, please visit our coronavirus FAQ page.
3.     (Third attachment) Lastly, we want to confirm that the “reasons for disagreement” we are allowing Veterans to choose from look correct to you. The current options provided are:
a.     “The service connection”
b.    “The effective date of award”
c.     “The evaluation of my condition”
Please retain the three options and allow the claimant to select more than one of the options as is currently allowed
In the “something else”, please remove “Explain in a few words” and replace with: “Described your disagreement briefly here. Please note that new evidence cannot be considered under the Higher-Level Review

**Comment by eileen-coforma** [comment]
CAIA Recommendations have been implemented in the design. Looking to Julie for approval to start work.

**Comment by eileen-coforma** [comment]
@Mottie What is this draft PR connected to the task ticket? I thought you connected it to the eng ticket.

**Comment by eileen-coforma** [comment]
NVM. I see you also connected it to the ENG ticket. I'll close this then.
