### ISSUE TITLE
21-4138, PP subtask - Remove logic that conditional displays list of non-housing hardships 

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#83877]
### Background
In the subtask for priority processing requests, we want to explain to users whether or not they qualify for priority processing. 

Earlier designs followed the digitized 10207 flow, where the list of non-housing issues you see is dependent on the selection you made from the list of housing risks. 

We want to update this logic for two reasons:
1. Unlike the actual priority processing request, we want to inform users if they may not qualify. In order to do this, we need to provide a mechanism for them to tell _us_ they're not experiencing anything from the VAs list of qualifying circumstances.
2. It will simplify the engineering lift to no longer conditionally reveal one list of hardships vs. the other. 

### Change
- [ ] Remove logic that leads to an `optional` list of non-housing risks
- [ ] Update logic so that two selections of "None of these apply to me" leads to the "you probably don't qualify" endpoint. From there, these folks are encouraged to describe their situation va 21-4138. 

### Resources
[Figma](https://www.figma.com/design/w2tRlZ5qJSOF968XoWzBRg/WIP%3A-21-4138---Submit-a-statement-to-support-a-claim?node-id=786%3A239173&t=TpyqKIThGwgDwWVV-1)

### Definition of done
- [ ] No matter what you select on the housing risk page, you should then see a list of other hardships, including the option "None of these situations apply to me". 
- [ ] If you select "None of these situations apply to me." from BOTH lists, you should NOT see the "you may qualify" page that recommends submitting a priority processing request via 20-10207

**Comment by rachelshearerux** [comment]
This work is replaced by [this ticket (#83877)](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/83877), updating the logic to remove conditionally displaying the option/required hardship list.

**Comment by rachelshearerux** [comment]
Thanks, Jacob, looks great! 


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3effa730bc90bf951c9a3557b2fdd69d3b50044e/PP%20logic%20updated.mov)
