### ISSUE TITLE
[FE] My VA Health: time zone bug on health appointments

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#83887]
## Background
We heard from the health applications team yesterday that they're seeing an issue with timezones on My VA.

From Stephen Barrs in [slack](https://dsva.slack.com/archives/C053JC66YHF/p1716408793437529):

> I have not had time to trace through and see how this vaos-timezones file is being used, but I do see that some of the Hawaii CBOCs have specific entries while others do not.  The CBOC associated with the appointment below has siteID 459GC which is not included in the vaos-timezones file.  The appointment in MyVA displays ten hours after the correct time, which coincides with GMT, so it is likely that because there is no entry for 459GC the timezone is not being applied.  This may also be true for [other CBOCs in HI,](https://www.va.gov/pacific-islands-health-care/locations/) but am not sure.
> Here is the screenshot of the issue:
> ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/f7430827-d9e7-4c9b-a609-0a1fa3f982a4)

## Tasks
- [x] Investigate Stephen's findings
- [x] Figure out difference between Community Care and VA appointment types
- [x] Figure if we need to include HST in [TIMEZONE_LABELS](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/personalization/dashboard/utils/date-formatting/timezone.js#L67-L74)
- [x] Determine resolution
- [x] Implement fix
- [x] Test/validate 

## Acceptance Criteria
- Appointment time zones are reflect that time the user in which the user is located

**Comment by allisonlu** [comment]
@ajakabcin 

I haven't been able to sync with Stephen Barr on this get find a staging user with this timezone. I will find a time to connect when I get back from PTO. 

for sprint 38 planning, let's keep this at 3 points

**Comment by allisonlu** [comment]
- AJ contacted the Appointments team to see if they are able to find a staging user with a Hawaii timezone ([Slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1718206321256699))
- Marcy Nadeau inquired about how we determine a user's timezone
- I created a [markdown file on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/engineering-docs/frontend-determining-time-zone.md) for comprehensive documentation (and for future reference)

**Comment by ajakabcin** [comment]
@allisonlu moving this to blocked until we hear back from the appointments team about a Hawaii test user. cc @ACParker89

**Comment by ajakabcin** [comment]
going to keep this in blocked but also remove it from next sprint - if a test user comes through we'll re-assess, otherwise can hold until following sprint

**Comment by allisonlu** [comment]
@ajakabcin 

updating to 1 point for sprint 42, waiting on a PR review from Platform!

**Comment by allisonlu** [comment]
- [pinged Jeff Roof on Slack](https://dsva.slack.com/archives/CMNQT72LX/p1722627981346179?thread_ts=1718206321.256699&cid=CMNQT72LX) that this fix is ready for validation 
- we will have to log in as staging user **patient999** on Monday to finish validation

**Comment by allisonlu** [comment]
Jeff confirmed it is working!

@ajakabcin if we would like to have another person validate, here are instructions:

1. log in as patient999@id.me on staging
2. note the time on the Next appointment card
3. click **Schedule and manage your appointments** to navigate to /my-health/appointments 
4. make sure the time of the first appointment listed matches the one in the Next appointment card on My VA
