### ISSUE TITLE
Update Page: VCR-Debugging (Footer Ticket 77027)

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#83889]
## Issue Description
[This page]( https://depo-platform-documentation.scrollhelp.site/developer-docs/vcr-debugging) on VCR Debugging requires an update per Footer Ticket [77027](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77027). Suggested changes are detailed below. We need to connect with the Platform Product Team to create approved language to update this page.

### SME: 

- Rebecca Tolmach/Platform Product Team or Ryan McNeil Platform Reliability team.

---
## Tasks
- [x] Review suggested changes below  
- [x] Product Team draft update with Content Team
- [x] Content Team check for Launch Blockers

## Acceptance Criteria
- [x] Page is updated with approved changes
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Suggested Changes:
The [VCR Debugging](https://depo-platform-documentation.scrollhelp.site/developer-docs/vcr-debugging) page should offer more information about testing with VCR.  There's no platform documentation explicitly about this.  What I'd like to change, is to modify the introductory paragraph, and break it into two, while also adding a bit more basic info.  Currently:

> VCR debugging
[VCR](https://github.com/vcr/vcr) can be a great way to record HTTP interactions in a controlled environment and
replay those interactions during tests. We don’t want to make actual HTTP requests during a test scenario, so VCR
helps us get around that. Sometimes VCR seems to work out of the box, but sometimes it takes trial and error to get a
test to recognize cassettes. Below are some errors and possible resolutions.

Proposed Change:

> VCR in Unit Testing
[VCR](https://github.com/vcr/vcr) can be a great way to record HTTP interactions in a controlled environment and
replay those interactions during tests. We don’t want to make actual HTTP requests during a test scenario, so VCR
helps us get around that.
>
> To record a VCR cassette, you must make a successful network request.  First, obtain the proper credentials to make
the request.  For example, to obtain credentials for the lighthouse sandbox api, fill out [this form]
(https://developer.va.gov/support/contact-us).  
>
> Modify `settings/test.yml` to include the necessary credentials.  To avoid the potential of committing sensitive
information into version control, use an environment variable, eg `<%= ENV['CLIENT_ID'] %>`.  Wrap your test's
network request in a call to use_cassette, e.g., `VCR.use_cassette("path/to/cassette/to/record/200_response.yml`.  
>
> When you run your unit test, the network call will execute and the response will be recorded.  The next time you run the
test, it will run the recorded response instead of making the external call.  Note that if you follow TDD, you'll need to
remember to delete that recorded response after each failure (else the failure will simply be replayed, no matter what
changes you make to your code).
> 
> VCR debugging
Sometimes VCR seems to work out of the box, but sometimes it takes trial and error to get a test to recognize
cassettes. Below are some errors and possible resolutions.
... rest of the document

**Comment by jknipes** [comment]
Waiting to see if this needs to be scheduled into a future sprint with Product Team

**Comment by jknipes** [comment]
This ticket is being handled by Platform Product Team, related to ticket 77027

**Comment by jknipes** [comment]
ZenHub automatically added this ticket to the 2 most recent sprints, but the work is still on hold pending availability of the SME

**Comment by ryan-mcneil** [comment]
Didn't quite finish the docs, but I'll knock them out first thing in the next sprint. In progress doc [here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/edit-v2/2893611114)

**Comment by ryan-mcneil** [comment]
@laucon alright, I've submitted a solid overhaul of the [page](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2893611114/Testing+with+VCR) in question. Let me know if (when) something needs to be fixed! Thanks!

**Comment by jknipes** [comment]
Hey @ryan-mcneil , @laucon has checked the document, It has no launch blocking issues. It will be deployed on Tuesday 9/3. Thank you for working on this!
