### ISSUE TITLE
Changes to pre-check-in confirmation pages when demos don't need to be reviewed

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#83890]
## Tasks

Based on upcoming medication review additions, we need to make some changes to have that content fit easier into our pages. 

Changes includes: 

- [ ] Don't take user to Appointments page; take user to [complete page](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=1195-15761&t=PsaSljLKsayWHFtY-4)
- [ ] h1 uses `Your information is up to date`
- [ ] h2 is added `Your appointments`
- [ ] Ensure the appointment times are semantic h3's, but can be styled as h2's
- [ ] When a user DOES have to do demos, the change that needs to be made to the [complete page](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?node-id=961-54015&t=PsaSljLKsayWHFtY-4) is adding the `Your appointments` h2 and adjusting the appointment times to h3's

**Comment by benbrasso-agile6** [comment]
@loripusey this prob needs to get picked up for next sprint

**Comment by loripusey** [comment]
@wullaski are these changes being made to the new landing page?

**Comment by wullaski** [comment]
@loripusey yes the PR is for the unified branch

**Comment by loripusey** [comment]
Do we have screenshots for this so we can validate? @wullaski

**Comment by wullaski** [comment]
@loripusey, Here's a screenshot with the new content on the complete page
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/7aa3ea33-dc5a-4e56-998b-fd32e65c4cc8)
And the markup:
![Screenshot 2024-06-10 at 1 52 54 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/663aa3c5-889c-4783-b06f-d27634dc73e5)

**Comment by benbrasso-agile6** [comment]
Screenshots of completion page when user DOES have to review demos?

**Comment by loripusey** [comment]
@wullaski ^^^^

**Comment by wullaski** [comment]
@benbrasso-agile6 Here's the screenshot of the completion page when you do have to review demos and I answered no to a question which currently how the first accordion item will display. Are we removing that functionality?
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/f53b8780-8216-42d0-a73b-9b13f6107399)

**Comment by benbrasso-agile6** [comment]
I believe we changed that a few sprints ago. That is, there's no longer if/then logic for when specific accordions display. They're always all present.

**Comment by benbrasso-agile6** [comment]
When user reviews their demos, on complete page, h1 should be 

`You’ve successfully reviewed your contact information`
