### ISSUE TITLE
Initial revisions and improvements to the FDG

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#83917]
## Purpose
Based on our first passes, and Matt's feedback, here are revisions to consider and execute.

## Tasks
- [x] identify SMEs for feedback
- [x] schedule with SMEs
- [x]  initial FDG content is heavy on how the Forms team works, light on other approaches (i.e. when to pause and get something in front of Users (possibly after DI and before Midpoint), etc).  Are there any steps we should include from the practices of other teams?
- [x] make sure that Discovery is advised. (Discuss w/ Shane Strassberg: where should this go? When does it happen? Shira may be able to advise as well)
- [x] document where gaps can be filled in FDG Phases
- [x] document plan for writing and placing content in these gaps (example: working with Allison Christman to include guidance when a team needs to use the Experimental Design Process)
- [x] draft content for the main landing to ask users to inform the content via feedback:  “if this doesn’t reflect your experience, please let us know so that we can make it more accurate or at least more comprehensive/inclusive”

## Acceptance Criteria
- [x] copy for each of the above items is added/altered

**Comment by twoangstroms** [comment]
Carrying over due to holiday
