### ISSUE TITLE
686 | Tag database records as handled

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#83924]
## Issue Description
_Follow the model of 526 and tag DB records that were handled as handled, so future people know that these were remediated in a batch process and are not sitting untouched._

Per Thomas: We don't have a mechanism for this as is. We need to add a column to the SavedClaim table and then update it.

---
## Tasks
- [ ] Add a column to the SavedClaim table
- [ ] Update column to indicate record has been handled

## Acceptance Criteria
- [ ] DB records that were handled are marked as handled
---

**Comment by mjknight50** [comment]
I don't see this as an issue anymore.
