### ISSUE TITLE
[DISCOVERY] Editorial process: Stories/Events

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8393]
## Problem Statement
How might we make the creation/editing of stories and events more user friendly for content editors?

## Goal
Content editors can anticipate how their additions/edits will be rendered on the page
- Content editors need to identify the feature story/event
- Content editors need to understand the display order for stories/events

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Determine appropriate editorial experience for stories/events

## Acceptance Criteria
- [ ] Recommendations for changes to editorial experience for stories/events
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
