### ISSUE TITLE
Updated Widget state mapping for LH error codes

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83943]
## Background
It appears that some of the non-200 responses from Lighthouse (500 and 422) can be mapped to our "No Representative" state.

We've also discovered that non-Veteran claimants do not have the appropriate identifier to retrieve their active representative status from Lighthouse.  In these instances, we can show this updated error message, [recommended from CAIA](https://dsva.slack.com/archives/C01K37HRUAH/p1716325353369569?thread_ts=1715790703.090809&cid=C01K37HRUAH).  According to our stakeholders, users should be able to call the standard MyVA411 number to obtain information regarding their claim or representation.

> We can't check if you have an accredited representative
> We're sorry. Our system isn't working right now. Try again later.
> If it still doesn't work, call us at 800-698-2411, ext. 0 (TTY:711).  We're here 24/7.

## Tasks
- [ ] Connect `500` and `422` to the "No Representative" Widget status
- [ ] Introduce a new error state for the non-Veteran claimant users

## Acceptance Criteria
- [ ] The Representative Status Widget has more refined states, based on newly uncovered scenarios.
