### ISSUE TITLE
Update content pages/My VA links

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#8395]
## User story

As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. 

Related to Epic #5518

## Tasks
DESIGN
- [x] Update My VA account link #8400
- [x] Update subway map and link in Change Address page #8420
- [x] Update link in Change your VA direct deposit information section #8419

FRONTEND
- [x] [FE] "Build updated manage your profile" section #8573

**Comment by tressaellen** [comment]
@mshea0606 here is the epic for all of the created tickets.

**Comment by mshea0606** [comment]
@tressaellen Thanks!

**Comment by Samara-Strauss** [comment]
Should have closed this a while ago. Work is done!
