### ISSUE TITLE
Set up clientside routing to render app in staging

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#83955]
## Issue Description
The app has been generated but it needs an entry in our clientside routing to get built in staging. We also need to associate at least one of the form pages with a URL in our URL scheme. 

---
## Tasks
- [ ] Add appoint to the route file in the devops repo 
- [ ] Set up form routing so that our URLs are valid routes in staging

## Acceptance Criteria
- [ ] Can navigate to Appoint a Rep route(s) in staging

**Comment by cosu419** [comment]
Moving this to in review. Authorization for Certain Medical Records screen will be the first testable route.
