### ISSUE TITLE
[DESIGN] Determine which Unified Check-in alert scenarios should switch to confirmation page format

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#83953]
## Background
Following our change to the success confirmation page when contact information does not need to be checked in Pre-check-in (discussed with Peter for [Medication Review work](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=146-3613&t=2EAw0OIG8CLKJzT6-1)), we need to take a look at the rest of the alert scenarios in Unified Check-in to see if it make sense to change any of these other scenarios to the confirmation page. 

Alert scenarios to review:

[Link to section in Unified Check-in Figma file](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=0%3A272&t=x59TvGK2e6DWqbeF-1)

<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDBQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6446b30dee270d855da9db6a6fa11ab0398cba1d/Screenshot%202024-05-24%20at%2012.33.26%E2%80%AFPM.png" alt="Screenshot 2024-05-24 at 12.33.26 PM.png" />

## Tasks
- [ ] Review success message change
- [ ] Review alert scenarios and determine approach
- [ ] Share findings with UX team and document decision
- [ ] Create follow-up ticket for next design steps

## AC
- [ ] Decision made for how we'll handle different alerts
- [ ] Follow-up ticket made to reflect any design changes needed

**Comment by cgednalske** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/83953?planning-poker) with Zenhub @benbrasso-agile6 @zach-park
