### ISSUE TITLE
Copy of Authorization for Access Outside VA Systems

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83969]
## Issue Description

Here, we ask users if they authorize certain individuals to access records outside of VA systems. If users authorize access, they will be asked to specify which individuals a following page (https://github.com/department-of-veterans-affairs/va.gov-team/issues/83968).

The Authorization for Access Outside VA Systems page will be available to:
1. Veteran and Non-Veteran users
2. Authenticated users and unauthenticated users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 3".  If the user is a **non-Veteran** the `h2` should reference "Chapter 4".
   2. If the user selects a **VSO** for representation, they will see 
      1. "VA Form 21-22" at the top of the page.  
      2. "This accredited VSO may need to access..." in the top description content.
      3. The 21-22 Field 19 legal content in the accordion.
   3. If the user selects an **attorney/claims agent** for representation, they will see 
      1. "VA Form 21-22a" at the top of the page.
      2. "This accredited attorney may need to access..." OR "This accredited claims agent may need to access..." in the top description content.
      3. The 21-22a Field 20 legal content in the accordion.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 19: Authorization for Representative's Access to Records Protected by Section 7332, Title 38, U.S.C. (checkbox)
   - Field 20: Limitation of Consent (checkboxes for each medical condition -- select all or none on this step, based on user input)
 
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 20: Authorization for Representative's Access to Records Protected by Section 7332, Title 38, U.S.C. (checkbox)
   - Field 21: Limitation of Consent (open input -- note all or none of the conditions on this step, based on user input)

URL: `/authorize-medical`

Previous paths: 
1. `/veteran-contact-information` (21-22 auth Vetearn) - **TBD**
2. `/veteran-mailing -address` (21-22 unauth Veteran) - **TBD**  
3. `/veteran-service` (21-22a unauth Veteran OR 21-22a non-Veteran) 
4. `/veteran-identification` (21-22 non-Veteran)

Next paths: 
1. `/authorize-address` (for users that authorize access to "all" or "none")
2. `/authorize-medical/select` (for users that authorize access to "some")

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs 
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216513&t=5syFaUqtBipJf7nq-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216513&t=5syFaUqtBipJf7nq-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=5373-214330&t=5syFaUqtBipJf7nq-4)

<details><summary>Screenshots</summary>

<img width="176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c678b47b4ada880f759050e2d59030a0a13e1225/image.png" alt="image.png" />

<img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1RQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16989b209b503ecc3f6e62234c794c412834b3c8/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Authorization for Access Outside VA Systems page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A (non-functional?) Authorization for Access Outside VA Systems page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
It would help our testing if we include a temporary dummy page with two radio groups - one for a Veteran/Non-veteran, and one for 21-22 vs 21-22a. Then we can expect all dynamic content to actually be dynamically rendered from the start.

**Comment by cosu419** [comment]
It would help our testing if we include a temporary dummy page with two radio groups - one for a Veteran/Non-veteran, and one for 21-22 vs 21-22a. Then we can expect all dynamic content to actually be dynamically rendered from the start.

**Comment by cosu419** [comment]
@mtri This is ready for review. The radio group is not yet dynamic (it references "accredited representatives" rather than vso/attorney/claims agents), this is a stubborn issue that I'm going to defer on solving until I have some time at towards the end of the sprint.

**Comment by mtri** [comment]
@cosu419 

• Remove the extra "We’ll save your application after every change." below
<img width="1202" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDUwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e923ac3fecaa2c78ba54a22af1c6118da8cef725/Fill%20Out%20Your%20Form%20To%20Appoint%20A%20VA%20Accredited%20Representative%20Or%20VSO%20Veterans%20Affairs%202024-06-18%20at%205.18.15%20PM.jpg" alt="Fill Out Your Form To Appoint A VA Accredited Representative Or VSO Veterans Affairs 2024-06-18 at 5.18.15 PM.jpg" />


• I'm doublechecking with the DST about this line on the top of each page since I've seen it on some forms and templates and absent from others. We may be able to remove it and rely on the typical auto-save alert that shows up.

• It looks like the radio button component (the buttons and the label) is displaying too large. Compare:
<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHgwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e25ddeb88397fe159742e0d6d4007987cfbe6ae7/Find%20and%20Appoint%20a%20Representative%202024-06-18%20at%205.16.17%20PM.jpg" alt="Find and Appoint a Representative 2024-06-18 at 5.16.17 PM.jpg" />

**Comment by cosu419** [comment]
Regarding the radio button, the smaller sized radio group comes from a deprecated implementation (`'ui:widget'`). The larger radio group is the `'ui:webComponentField'` implementation as recommended in the docs. It might be better to just adjust the smaller radio groups to match the recommendation (making them appear larger). 

But that leaves the issue of plain text copy appearing smaller relative to the radio groups... tentatively I can adjust this globally so we have consistency between `<p>` text font-size and `webComponentField` font-size, but it may need to be raised as an issue with the design team.

**Comment by mtri** [comment]
> • I'm doublechecking with the DST about this line on the top of each page since I've seen it on some forms and templates and absent from others. We may be able to remove it and rely on the typical auto-save alert that shows up.

Noting this is being worked on: https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1407

Important note from that ticket:
> Because of the redundancy of this alert, and the green success alert at the bottom of the form, we should show this text only on the first step page of the form.

**Comment by mtri** [comment]
Some additional clarification on that text from [this thread.](https://dsva.slack.com/archives/C01DBGX4P45/p1719325122876029?thread_ts=1718748632.547239&cid=C01DBGX4P45)
> The message should always display on step 1 which would include a user returning to an in progress form.

**Comment by oddball-lindsay** [comment]
Caught a typo in demo today -- need to fix the word "systems": 

<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek9QQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7e64e7add4b2274d92212523d5a2c18f91aae73/image.png" alt="image.png" />

**Comment by oddball-lindsay** [comment]
Typo should be fixed

**Comment by mtri** [comment]
Everything looks good here.
