### ISSUE TITLE
Authorization for Address Change

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83966]
## Issue Description

The Authorization for Address Change page will be available to:
1. Veteran and Non-Veteran users
2. Authenticated users and unauthenticated users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 3".  If the user is a **non-Veteran** the `h2` should reference "Chapter 4".
   2. If the user selects a **VSO** for representation, they will see 
      1. "VA Form 21-22" at the top of the page.  
      2. "This accredited VSO may need to access..." in the top description content.
      3. The 21-22 Field 21 legal content in the accordion.
   3. If the user selects an **attorney/claims agent** for representation, they will see 
      1. "VA Form 21-22a" at the top of the page.
      2. The 21-22a Field 20 legal content in the accordion.
      3. The relevant representative type in the description and above the radio options.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 21: Authorization to Change Claimant's Address (checkboxes)
- [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 22: Authorization for Representative to Act on Claimant's Behalf to Change Claimant's Address (checkboxes)

URL: `/authorize-address`

Previous paths: 
1. `/authorize-address` (for users that authorize access to "all" or "none")
2. `/authorize-medical/select` (for users that authorize access to "some")

Next paths: 
1. `/review` (21-22)
2. `/authorize-inside-va` (21-22a)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs 
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216519&t=5syFaUqtBipJf7nq-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216519&t=5syFaUqtBipJf7nq-4)

<details><summary>Screenshots</summary>

<img width="192" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f94c7672dde5d4c85e03a5dc686978d37f067908/image.png" alt="image.png" />

<img width="279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWtRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--107d8cbebeb90958f84c14f6ec9f9bf91e05b572/image.png" alt="image.png" />

<img width="715" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1c31cde71d2d69b56f058d4da55c63fd5d293d8/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Authorization for Address Change page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Authorization for Address Change page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
PR merged earlier than expected - this now is ready for review in staging @mtri

**Comment by mtri** [comment]
Other than the breadcrumb spacing mentioned on https://github.com/department-of-veterans-affairs/va.gov-team/issues/83964, this looks good!
