### ISSUE TITLE
Authorization for Certain Medical Records - Select

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83965]
## Issue Description

Users are asked if they authorize access to certain medical records and can provide authorization to all, some, or none (https://github.com/department-of-veterans-affairs/va.gov-team/issues/83964).  If users authorize some records, they will be asked to specify which records on this page.

The Authorization for Certain Medical Records - Select page will be available to:
1. Veteran and Non-Veteran users
2. Authenticated users and unauthenticated users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 3".  If the user is a **non-Veteran** the `h2` should reference "Chapter 4".
   2. If the user selects a **VSO** for representation, they will see 
      1. "VA Form 21-22" at the top of the page.  
      2. "You've authorized this accredited VSO to access..." in the top description content.
   3. If the user selects an **attorney/claims agent** for representation, they will see 
      1. "VA Form 21-22a" at the top of the page.
      2. The relevant representative type in the top description content.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 20: Limitation of Consent (checkboxes for each medical condition -- reflect the user's selection)
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 21: Limitation of Consent (open input -- reflect the user's selection)

URL: `/authorize-medical/select`

Previous paths: 
1. `/authorize-medical`

Next paths: 
1. `/authorize-address` 

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs 
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216517&t=5syFaUqtBipJf7nq-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216517&t=5syFaUqtBipJf7nq-4)

<details><summary>Screenshots</summary>

<img width="231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--470a62c9d33dc05a48fc2853651c2a1d03b8cee3/image.png" alt="image.png" />

<img width="769" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--645ea38076d486415fb391ebddffb214a32b85d9/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Authorization for Certain Medical Records - Select page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Authorization for Certain Medical Records - Select page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
@mtri This is ready for design review at https://staging.va.gov/get-help-from-accredited-representative/appoint-rep

**Comment by mtri** [comment]
- Add space between the "You've authorized this accredited [attorney, claims agent, Veterans Service Organization (VSO)] to access some of your medical records." and the checkbox list component. From Figma:
<img width="791" alt="Screenshot 2024-06-10 at 4 51 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/2244100/06c72785-9f70-486e-9774-a2a5160986f3">
<br>
<br>
<br>
- Remove space below the "Select the types of records they can access" label. It looks like some extra space is being added. [In the checkbox group component in storybook the label is much closer to the checkboxes.](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default)

**Comment by cosu419** [comment]
This is ready for review @mtri

**Comment by mtri** [comment]
Spacing looks good! Thanks!

– Looks like the same thing may be happening on the component size for the checkmark box as on the radio button component on the [Authorization for Access Inside VA Systems #83969](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83969#issuecomment-2177184090). The label and checkmark text size seems strangely large.

– When a page can't advance without a selection or text input on a component, we should have the (Required*) on the label. For each authorization step, the label on the question should have the red (Required*) mark. I'll update the designs in Figma to reflect this too. 

Checkbox in storybook:
<img width="538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHQrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b18707830edb074a3daa461e08c6e63739f9fdda/Screenshot%202024-06-20%20at%203.56.25%20PM.png" alt="Screenshot 2024-06-20 at 3.56.25 PM.png" />

(Currently locked out maybe due to a push so don't have a screenshot handy of what's up on the page currently)

**Comment by mtri** [comment]
Everything looks good here.
