### ISSUE TITLE
Authorization for Access Outside VA Systems

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83967]
## Issue Description

Here, we ask users if they authorize certain individuals to access records outside of VA systems. If users authorize access, they will be asked to specify which individuals a following page (https://github.com/department-of-veterans-affairs/va.gov-team/issues/83968).

The Authorization for Access Outside VA Systems page will be available to:
1. Veteran and Non-Veteran users
2. Authenticated users and unauthenticated users
3. 21-22a form ONLY

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 3".  If the user is a **non-Veteran** the `h2` should reference "Chapter 4".
   2. If the user selects an **attorney/claims agent** for representation, they will see 
      1. The relevant representative type in the description and above the radio options.

The information collected on this page will be routed to the forms as follows:
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 19b: Authorization for Disclosure to Affiliated Personnel (checkbox)

URL: `/authorize-outside-va`

Previous paths: 
1. `/authorize-inside-va`

Next paths: 
1. `/authorize-outside-va/names` (for users that select "Yes")
2. `/review` (for users that select "No")

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs 
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-239829&t=5syFaUqtBipJf7nq-0&scaling=min-zoom&page-id=5138%3A422022&starting-point-node-id=1848%3A239830), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1848-239829&t=5syFaUqtBipJf7nq-4)

<details><summary>Screenshots</summary>

<img width="171" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7882a54675571ffa0c486231e3e873a52c4e588/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Authorization for Access Outside VA Systems page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Authorization for Access Outside VA Systems page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
update: perhaps hold off on review until my next PR merges, as it will impact this screen @mtri

**Comment by mtri** [comment]
Everything looks good here.
