### ISSUE TITLE
Authorization for Access Outside VA Systems - Names

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83968]
## Issue Description

Users are asked if they authorize certain individuals to access records outside of VA systems (https://github.com/department-of-veterans-affairs/va.gov-team/issues/83967).  If users authorize access, they will be asked to specify which individuals on this page.

The Authorization for Access Outside VA Systems - Names page will be available to:
1. Veteran and Non-Veteran users
2. Authenticated users and unauthenticated users
3. 21-22a form ONLY

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 3".  If the user is a **non-Veteran** the `h2` should reference "Chapter 4".
   2. If the user selects an **attorney/claims agent** for representation, they will see 
      1. The relevant representative type in the description and above the radio options.

The information collected on this page will be routed to the forms as follows:
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 19b: Authorization for Disclosure to Affiliated Personnel (open field - reflect user's input)

URL: `/authorize-outside-va/names`

Previous paths: 
1. `/authorize-outside-va`

Next paths: 
1. `/review`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs 
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4497-77640&t=5syFaUqtBipJf7nq-0&scaling=min-zoom&page-id=5138%3A422022&starting-point-node-id=1848%3A239830), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4497-77640&t=5syFaUqtBipJf7nq-4)

<details><summary>Screenshots</summary>

<img width="232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e144fe6733f125538ed63c63e87abdef1fe891f2/image.png" alt="image.png" />

</details>

---
## Tasks
- [ ] Create the Authorization for Access Outside VA Systems - Names page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Authorization for Access Outside VA Systems - Names page has been implemented, with the specs outlined above.

**Comment by mtri** [comment]
Everything looks good here.
