### ISSUE TITLE
Authorization for Certain Medical Records

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#83964]
## Issue Description

Here, we ask users if they authorize access to certain medical conditions.  Users can authorize all, some, or none.  If users authorize some records, they will be asked to specify which records on a following page (https://github.com/department-of-veterans-affairs/va.gov-team/issues/83965).

The Authorization for Certain Medical Records page will be available to:
1. Veteran and Non-Veteran users
2. Authenticated users and unauthenticated users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 3".  If the user is a **non-Veteran** the `h2` should reference "Chapter 4".
   2. If the user selects a **VSO** for representation, they will see 
      1. "VA Form 21-22" at the top of the page.  
      2. "This accredited VSO may need to access..." in the top description content.
      3. The 21-22 Field 19 legal content in the accordion.
   3. If the user selects an **attorney/claims agent** for representation, they will see 
      1. "VA Form 21-22a" at the top of the page.
      2. The 21-22a Field 20 legal content in the accordion.
      3. The relevant representative type in the description and above the radio options.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 19: Authorization for Representative's Access to Records Protected by Section 7332, Title 38, U.S.C. (checkbox)
   - Field 20: Limitation of Consent (checkboxes for each medical condition -- select all or none on this step, based on user input)
 
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 20: Authorization for Representative's Access to Records Protected by Section 7332, Title 38, U.S.C. (checkbox)
   - Field 21: Limitation of Consent (open input -- note all or none of the conditions on this step, based on user input)

URL: `/authorize-medical`

Previous paths: 
1. `/veteran-contact` (21-22 auth Vetearn)
2. `/veteran-contact-mailing` (21-22 unauth Veteran)  
3. `/veteran-service` (21-22a unauth Veteran OR 21-22a non-Veteran) 
4. `/veteran-identification` (21-22 non-Veteran)

Next paths: 
1. `/authorize-address` (for users that authorize access to "all" or "none")
2. `/authorize-medical/select` (for users that authorize access to "some")

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs 
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216513&t=5syFaUqtBipJf7nq-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216513&t=5syFaUqtBipJf7nq-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=5373-214330&t=5syFaUqtBipJf7nq-4)

<details><summary>Screenshots</summary>

<img width="176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c678b47b4ada880f759050e2d59030a0a13e1225/image.png" alt="image.png" />

<img width="256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4f461a8c08396f9f583ec508192199a3d6931d3/image.png" alt="image.png" />

<img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1RQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16989b209b503ecc3f6e62234c794c412834b3c8/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Authorization for Certain Medical Records page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Authorization for Certain Medical Records page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
It looks you need to log in with a test user to view the form in staging - guessing there's some safety measure in staging/prod preventing users from skipping ahead in the form. Not sure why logging in is required, I'll need to look into disabling that for the unauth experience. So to review in staging, you tentatively need to log in and nav to `staging.va.gov/get-help-from-accredited-representative/appoint-rep`, then proceed through the flow. 

Having done that, everything looks good except the `additional-info` component isn't importing correctly. 

I also assumed the "We'll save your application after every change" would appear on its own (similar to "Finish this application later"), but apparently that needs to be added manually?

Both are pretty minor, will keep this ticket open and attach it to my next PR.

**Comment by cosu419** [comment]
Update - unauthenticated is now working for me.

**Comment by cosu419** [comment]
@mtri This is ready for design review at https://staging.va.gov/get-help-from-accredited-representative/appoint-rep

No major disclaimers, except that "Veterans Service Organization (VSO)" is currently hardcoded.

**Comment by cosu419** [comment]
@mtri "We'll save your application" should show up only when authenticated, correct. 

Will include the space adjustment in my next PR (might hold off on breadcrumbs for the purposes of this particular ticket)

**Comment by cosu419** [comment]
Breadcrumbs + accordion spacing are merged. If everything looks good you can close this ticket @mtri

**Comment by mtri** [comment]
Thanks! 

Accordion spacing looks good!

The vertical space above and below the breadcrumb doesn't appear to be consistent with other forms.
For Desktop:
- Our form:
<img width="1889" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3abae435bcc40923f1051d444d7afe5f075bb8aa/Screenshot%202024-06-11%20at%204.18.47%20PM.png" alt="Screenshot 2024-06-11 at 4.18.47 PM.png" />


- From 527ez:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ZWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--531fd9137cf9d35beb0694db5ea4d84b987a53f0/Screenshot%202024-06-11%20at%204.15.12%20PM.png" alt="Screenshot 2024-06-11 at 4.15.12 PM.png" />

I noticed the breadcrumb internal horizontal spacing is also different from a lot of the breadcrumbs on the site, but after some investigation, it appears ours aligns with the breadcrumb as it is in [the VADS documentation](https://design.va.gov/components/breadcrumbs). 

I was trying to figure out why other pages like the 10-10ez and [the hubs](https://staging.va.gov/health-care/) look to have different breadcrumb styling (different spacing, chevron is shown instead of arrow on mobile). Any thoughts?

**Comment by oddball-lindsay** [comment]
Let's figure out what the expectation is, and then we can rally around that.
