### ISSUE TITLE
Appoint a Rep Digital Submit - User Test - Conduct Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#83979]
## Issue Description
User testing of Appoint a Representative Digital Submission flow.

## Tasks
- [ ] Complete interviews
- [ ] Manage interview day to day (team and recruiter coordination, debriefs, interviews, etc.)
- [ ] Download videos and transcripts
- [ ] Compile notes
- [ ] Upload notes, transcripts, and video to Sharepoint
- [ ] Upload notes and transcripts to EnjoyHQ
- [ ] Create analysis and reporting Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by oddball-lindsay** [comment]
Moving forward with the search results experience, where we show cards as the search result.  No longer pursuing our "fuzzy search" design for this study.
