### ISSUE TITLE
Report of Outdated Information evaluation

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#83980]
## Issue Description
Evaluate information users are entering in ‘Other’ field to determine if we should keep or add in additional pre created options.

## Tasks

- [ ] Request data from @holdenhinkle 
- [ ] Analyze information in Sharepoint
- [ ] Create a one pager for Sharepoint
- [ ] Send out findings and recommendations

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
First draft of report in review https://docs.google.com/document/d/1fKP6esWHB7pfClR5A7lkQvoOmAv8u7O1CKsOhmJCSpE/edit?usp=sharing

**Comment by jfinnerty13** [comment]
Completed and closed - will present next Tuesday at demo
