### ISSUE TITLE
Create Platform Site Documentation Around Access Dependencies

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#84016]
## Description 
We recently had some feedback on a retro noting the following: 

_Unnecessary noise around access. There isn't a clear bullet point list about what access you can request and when. It might be worth looking into creating some sort of public document on the Platform Website around this. Example: You can't request a license to Zenhub until you receive your va.gov email. You cant obtain access to Atlas, and vets.gov-write until you meet this criteria._

This ticket will explore the proposed documentation. You can see the current onboarding process [here](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1694796460913/9c127c1a097016b0cfbf26b609f5a0a6b623de61?sender=udc895e519e95151fc0244426). 
---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [ ] Create a draft of what we would be putting on the Platform Site [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/3184754910?draftShareId=7957193a-ac21-4753-a7cb-67f8c8d054a7) 
- [ ] Send documentation to Tier 1 team to identify any gaps
- [ ] Send documentation to Alyssa to review with leadership
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Duplicate ticket of what is here: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/83795

Closing this one.
