### ISSUE TITLE
[Epic] Reimagining VA.gov Technical Support

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#84017]
## Background

As the number of users signing into VA.gov for health and other benefits services, there is a need to re-evaluate the approach to providing support to users of VA.gov. In particular, there are a few problems that VA.gov technical support presents:

1. Signing in is the major driver of support issues on VA.gov. While some of these are problems caused by systems managed by VA, the vast majority are related to third party credential providers. Each contact center wants to limit the number of wrong issues coming to their helpdesk and right now we don't have a process in place that gets Veterans the answer they need as quickly as possible. 
2. As health related tools start making their way to VA.gov, we are in a gray area of not knowing which groups support which tools on VA.gov. HRC is responsible for MHV support but will they also be MHV on VA.gov support? And if yes, how do we ensure that Veterans get to the right call center for help and don't get frustrated trying to determine which group can support their questions.
3. Through our work solving Veteran issues, we know many of the most recurring user and system generated issues (i.e. user = lost MFA method vs. system = missing information error message). While we have done a decent job of documenting these issue and creating the necessary processes for the Veteran Support Team, VEO Tier 1 Contact Center, and EVSS helpdesk, we could do more to keep more groups updated on these types of errors so that no matter where a user is looking for support, for these known issues, they should be able to find the right answer. 
4. HRC was set up to be in charge of support for the Health and Benefits App but does not have a Tier 3 process in place for getting these issues resolved. We need to figure out how to work with other contact centers to get Tier 3 VA.gov technical issues to Veteran Support. 

Given the extent of these issues, we believe it is time to do some research to understand what a better phone support experience would look like for users of VA.gov and for the support groups that are managing these issues coming through. We have assumptions of what that process that might look like but we want to validate our assumptions with research internally and externally so we can start making changes to enhance the experience for support groups and users of VA.gov. 

*Note:* While there are certainly things we could do in many places, including new digital tools on VA.gov, we are going to be focused on the phone support experience because that is still where the majority of VA.gov technical support issues come through. 

## High Level User Story/ies
As a user of VA.gov, I need to know how to get answers to my VA.gov questions so I can fix my problems and use VA.gov to manage my benefits.

As someone who provides support to Veterans and users of VA.gov, I need to know how to answer questions about VA.gov or route issues correctly so I can ensure Veterans and other beneficiaries can get answers to their questions accurately and efficiently.

## Hypothesis or Bet
If we conduct research and gather feedback and information from VA support group and users of VA.gov we will be able to identify ways to improve our VA.gov Technical Support processes that will help users get answers to their questions and improve the support experience. 

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

- [ ] Review previous research on support (Chante to provide
- [ ] Completed workshop sessions with identified VA support groups
- [ ] Completed user/veteran research on VA.gov technical support process
- [ ] Recommendations on front end changes to the technical support process
- [ ] Recommendations on back end changes to the VA.gov technical support process
- [ ] Roadmap for implementing recommended changes

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by clantosswett** [comment]
Closing this because it is duplicative of the epic created by Camille.
