### ISSUE TITLE
[UX + Content] 10-10EZ Toxic Exposure User Flow Updates

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#84020]
## Issue Description
Now that research synthesis for 10-10EZ TERA questions is complete and we've identified next steps as team, the UX team will work on suggested content updates and work with CAIA to finalize content to address concerns that came up in testing.

- [Slack thread with team follow-up items](https://dsva.slack.com/archives/CMJ2V70UV/p1714151834266889)
- [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy)

---
## Tasks
- [x] Send email to HEC to verify dates of TERA questions (for branching logic)
- [x] Create/update 10-10EZ user flow to show conditional logic
- [x] Get sign-off from Lois and Patrick on changes
- [x] Meet with developers to discuss changes and create FE ticket(s)

## Acceptance Criteria
- User flow updates for TERA questions have been finalized and updates are ready for dev
---

**Comment by aagosto90** [comment]
[Shell FE/BE ticket created here](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/86350)
