### ISSUE TITLE
[UX] 10-10EZ - Facility Selection: Evaluate dynamic search options on EZ

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#84027]
## Background
While we prepare to start updating the Facility Selection page, we are aware of usability issues on this page overall, some feedback received in past Veteran interviews that expressed some pain points or confusion about the page and its current design.

We want to evaluate the current design past research and future CG dynamic search design with the hopes of identifying opportunities to improve and align for a consistent experience.

## Tasks
- [x] Desk research to gather past insights, from other teams via repo or Enjoy HQ, analytics or survey feedback
- [x] Draft user flow options of how the questions on the page today would work with dynamic search added
- [x] Draft designs for dynamic search and other pages
- [x] Work with data analyst for data related discovery questions
- [x] Collaborate with engineers esp learnings from cg and what differences exist on ez side
- [x] Review at UX sync and/or team sync

## Acceptance Criteria
- Determine a design direction of how dynamic facility search will flow on the EZ

**Comment by jessicastump** [comment]
[Figma page started here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3831-40050&t=ofojGl9kqpzA7M4a-0) with exploration and [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717792007491/6c4a62cc037aa751acade917131f29077fe4483b?sender=uadf1ed7fe7c76f0914967329) with very rough user flows

**Comment by jessicastump** [comment]
@luis-simauchi - tagging you here to tie in/link to the data ticket you mentioned creating today during ux sync :) 
Also as mentioned during UX sync, this was tabled last week but I hope to pick it up again this week.

**Comment by jessicastump** [comment]
Discussed as a team and [Mural board here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720636135631/20c44b67060152d2f8b0b1c961fb7f51c6d39bad?sender=uadf1ed7fe7c76f0914967329).
Will begin work on designs to look at a phased approach to start with only zip code search and build up to the option of suggesting facilities based on address Veteran used in application.
This will be covered in ticket [Design] 10-10EZ - Facility Selection: Create new Facility search & selection design #57772
