### ISSUE TITLE
Test WellHive API connection

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#84021]
## Tasks

- [ ] Get authorization to access
- [ ] Get access to Sandbox
- [ ] Prove out calling and returning list of providers. E.g., CC providers (network), Physical therapy (or any) (specialty)
