### ISSUE TITLE
[SPIKE] 4 hours - Discuss or find out how to access to patient preferences (preferred provider)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#84026]
## Tasks

- [ ] How might we get access to preferred provider for a patient/referral? E.g., believe data is saved in HSRM/CCRA for each referral. Might discuss with Kay. It's possible this information is also attached to the referral in CDW. 
- [ ] What field has if the Veteran has selected self-scheduling so we know they're opted into self-scheduling? 
- [ ] Preferred provider, indicated direct scheduling, CC group/location, booking note

**Comment by anita-halici** [comment]
@simiadebowale @lee-delarm6 - I noticed this task rolled over to the next sprint, what is left to be done in this ticket?

**Comment by lee-delarm6** [comment]
@anita-halici We didn't get started on this until this sprint due to the mid-sprint other work. It will be addressed in this sprint, most likely this week!

**Comment by benbrasso-agile6** [comment]
Get all approved CC Consults for PT at sites X and Y that have not been scheduled using VistA API X. VEText could make this available to us, and then VistA RPC would be used to get consult data from VistA API X. No MAP CDW Service right now; too many hoops. 

Consult example sent to VA emails 

VistA RPCs are somewhere in: 
https://vivian.worldvista.org/dox/PackageComponents.html
https://vivian.worldvista.org/vivian-data/8994/8994-351.html

While waiting for Shane and Stephen to return after July 15, we could begin mocking this based on the data in the email that Stephen forwarded to Simi and Ben.

**Comment by benbrasso-agile6** [comment]
@simiadebowale I just documented some notes in the above comment. After you finish poking around, let me know if/when you want to switch to creating mocks, and we can create separate tickets for that work next sprint.

**Comment by benbrasso-agile6** [comment]
Wait for shane; toss in Githuh @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
Added into git repo - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/community-care-direct-scheduling/functionality/referral/readme.md#integration-plan
