### ISSUE TITLE
Collect ideas around changes to deployment conveyor belt

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#84049]
## Issue Description
The deployment conveyor belt has for a long time resulted in all changes going to production whether they've been reviewed or not in a stable environment. The idea is to find a way to change the flow from VFS team to production in a way where teams can still have the ability to iterate and push to a testing environment on their schedule, but to have platform approval or some other way to guarantee that code deploys are reviewed in dev/staging before being moved to production. We want to shift to where deployments are deliberate as opposed to automatic/unintentional. We'd also like to get to a place where we can deploy a hotfix without having to drag along everything else with it.

The elimination of the conveyor belt has been a discussion that's gone on for years however we haven't had a route to get the support behind it we need to move it forward. Jeff Keene, our PO, has shown great interest in pursuing this venture and can be an advocate for us to finally make some movement on this. We need to distill our feedback into a document that he can shop around to get support for from the VFS POs and otherwise, so we can make the necessary improvements.

---
## Tasks
- [x] Create a document that lists the problems we're trying to solve
- [x] Hold any meetings necessary to get feedback from all team members with ideas. 
- [x] Decide on a preferred strategy to update the VFS -> Production code cycle to eliminate the conveyor belt
- [x] Collect all feedback into a design document to present to Jeff Keene

## Acceptance Criteria
- [x] A planned approach has been decided on and submitted for approval to OCTO.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/~842400322/pages/3210444836/Conveyor+Belt+Deployments
