### ISSUE TITLE
Fix Drag-and-Drop Handling and Add Custom Validation Example for <va-file-input>

### ISSUE THREAD

**Issue by nickjg231** [department-of-veterans-affairs/va.gov-team#84044]
## Issue Description
There is currently an issue with `<va-file-input>` where drag-and-dropped files are not treated the same as files selected through the file input interface. The file input interface directly interacts with the OS and can block certain file types. When files are dragged and dropped, this validation is not handled automatically and thus needs to be managed separately.

Additionally, we are adding a new example to Storybook to demonstrate to users how to implement custom validation on a file, as requested by Dan.

---
## Tasks
- [ ] Update logic inside of `<va-file-input>` to handle drag-and-dropped files similarly to files selected through the input interface.
- [ ] Add an example to Storybook showcasing custom validation on a file.

## Acceptance Criteria
- [ ]` <va-file-input>` properly handles and validates drag-and-dropped files.
- [ ] A new example is available in Storybook demonstrating how to implement custom validation on a file
