### ISSUE TITLE
Discovery: Make plan to automate vets-website code freezes

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#84057]
## Issue Description
We need to research a way to automatically disable and reenable the deploy workflows for vets-website and content-build, to avoid the reliance on engineers to remember to turn them on and off at holiday times. These should be able to be configured from a singular source for when to turn off and back on and happen automatically at the right times. Additionally, automated messaging should hit the frontend COP channel notifying the channel of when the workflows have been turned off or on.

---
## Tasks
- [x] Research a solution to automating the disabling and reenabling the daily deploy workflows for vets-website and content-build.
- [x] Research a way to set up the holiday calendar for these actions to take place at the right dates and times.
- [x] Create any tickets necessary to complete this work.

## Acceptance Criteria
- [x] Tickets exist as needed to implement these changes into our workflows.

**Comment by LindseySaari** [comment]
Working on documenting a process for what's best here. @KerryMin Please reach out to myself and @ph-One. We have a Code Freeze GHA and a sync window approach on the backend.

**Comment by AshleyGuerrant** [comment]
**Standup note**: a 2025 Q1 epic will be created to track tech debt. This ticket will be added to it.
