### ISSUE TITLE
5103 Language and Claim Certification: Implement Claim Certification / Signature Component

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#84062]
As a Veteran, I want to sign ("certify") my form 526 digitally, as this is what I do in the paper form and I want all of the same sections of the paper form present in the digital form.

Background:
The online form is missing the online equivalent to Section IX: Claim certification and signature. It's important to VBA that this be included in the digital form. 
![Image](https://github.com/user-attachments/assets/e5c20b36-777b-4b9c-ad01-0008ae77b89b)

## Reference
- [Figma designs](https://www.figma.com/design/vGmWQ20fJewxOvx3cuofpe/(526ez)-Signature-Component?node-id=123-2197&node-type=canvas&t=7G4ACVmLnk9NrP9Q-0) 
- Certification/Signature: can use existing [Statement of Truth component](https://design.va.gov/components/form/statement-of-truth) (v3): with [preSubmitInfo](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-form-config-options#VAFormsLibrary-FormConfigOptions-preSubmitInfo) 
- Access `fullName` via props: ![Image](https://github.com/user-attachments/assets/95b92a79-4bfa-4f7b-bdf2-4110ebddc7a1)

## Tasks
- [x] Add in Claim Certification and Signature component using Platform's Statement of Truth Component
- [x] Use existing `fullNamePath` validation for the text input (comes from `form.data`). 
- [x] Refer to [claim certification mapping for reference](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZ3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b7c2a842919cb47867d43f6b4b2b6e0eadfca53/5103%20claim%20certification%20mapping.pdf)
- [x] Enable alerts for unchecked claim certification on the signature component
- [x] Enable alerts for unmatched signature name on the signature component
- [x] Ensure error displays with expected name when input name does not match configured name ([example in screenshot](https://github.com/department-of-veterans-affairs/vets-website/pull/24255))
- [x] All work should be behind a staging environment check

## Front end tasks
- [x] Ensure the page is styled according to design spec. 
- [ ] Ensure the back end data from API is displayed in local and review instance
- [x] Ensure unit tests are available. 
- [x] Ensure your code changes are covered by E2E tests
- [x] Run axe checks using the Chrome or Firefox browser plugin
- [x] Test for color contrast and color blindness issues
- [x] Zoom layouts to 400% at 1280px width
- [x] Test with 1 or 2 screen readers
- [x] Navigate using the keyboard only

## Acceptance Criteria
 - [x] **Scenario: Claim Certification / Signature Component**
  - Given the digital form is missing Section IX: Claim certification and signature
  - When the online form includes the Claim Certification/Signature component
  - When Language about Box 1 is changed to have parity with the reintroduced FDC question
  - When this work is controlled by an environment check (same environment check as #83534)
  - Then this section of the paper form is present in the digital form
  - [ ] Designer comments on this issue to approve page styling 
  - [ ] Unit tests pass
  - [x] E2E tests cover current code and regression
  - [ ] End-to-end tests show 0 violations.
  - [ ] The data returned matches API response (for given user or scenario)
  - [x] All axe checks pass
  - [x] All color contrast checks pass
  - [x] All zoom testing passes
  - [x] All keyboard checks pass 
  - [x] All screenreader checks pass

**Comment by christinec-fftc** [comment]
- the difference in links between the Needs Evidence and Privacy Policy is obvious. Let's consider filing a design system improvement to support icon links for opening in new tab
- concern about the expected name not being announced without going directly to the error message. We may want to file a platform issue for this
