### ISSUE TITLE
Full transform on backend Part 5 (MISC, Personal Data)

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-team#84076]
## Description
This ticket is dependent on https://github.com/department-of-veterans-affairs/va.gov-team/issues/81058

We want to take a JSON string like [this](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/spec/fixtures/pre_submission_fsr/pre_transform.json) as input and reliably generate an output string like [this](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/spec/fixtures/pre_submission_fsr/post_transform.json).
This process currently happens on the FE around [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/utils/transform.js).

This effort has already been started on branch `81058-backend-full-transform-pt4-misc`.

This ticket is for handling the following FSR elements that need to be transformed:

`personalData`

## Tasks
- [ ] Task one to complete the work in the description
- [ ] Task two to complete the work in the description
- [ ] Task three to complete the work in the description

## Acceptance criteria

- [ ] Implement functions to generate the sections of the FSR that don't correspond to the income, assets, or expenses sections of an FSR from an [untransformed fsr data packet](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/spec/fixtures/pre_submission_fsr/pre_transform.json).

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [ ] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by maxx1128** [comment]
I started this ticket near the end of the sprint and am currently in the middle of creating the basic functionality, so it will carry over to next sprint.
