### ISSUE TITLE
[Documentation] Request to move more files from vets.gov-team to va.gov-team repo for authenticated experience team

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8409]
## Background

[Copy/pasted from this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/product-management/April%202020_Files%20to%20move%20from%20vets-team%20repo.md)

When we originally were moving files from the vets.gov-team repo to the va.gov-team repo, I didn't understand that files were being duplicated and not moved permanently. I thought adding files to va.gov-team would remove them from the old repo, and I wanted to make sure the historical records were preserved. Therefore, a lot of stuff that should have gotten moved didn't because I didn't understand the actual outcome. Now that I understand that files will be duplicated and not removed, I'd like to move some of the files that we still need and are still relevant to the new va.gov-team repo.

| Please move all Vets.gov-team files under this folder...| ...to this VA.gov-team repo folder | Notes |
|----|----|----|
| vets.gov-team/Products/Identity/Personalization/Account/ | va.gov-team/products/identity-personalization/profile/account-settings-V1 | |
| vets.gov-team/Products/Identity/Personalization/Dashboard/ | va.gov-team/products/identity-personalization/logged-in-homepage/my-va/ | |
| vets.gov-team/Products/Identity/Personalization/Personalization 2.0/ | va.gov-team/products/identity-personalization/personalization 2.0/ | Some of the files in the older personalization folder have been moved already, but I would like anything that is not already there to be moved over. |
| vets.gov-team/Products/Identity/Personalization/Profile/Design/ | va.gov-team/products/identity-personalization/profile/profile-V1/design | | 
| vets.gov-team/Products/Identity/Personalization/Profile/MHV Profile/ |va.gov-team/products/identity-personalization/profile/profile-V1/mhv-profile/ | | 
| vets.gov-team/Products/Identity/Personalization/Profile/Vet360 UAT/ | va.gov-team/products/identity-personalization/profile/profile-V1/2018-vet360-uat/ | | 
| vets.gov-team/Products/Identity/Personalization/Notifications/| va.gov-team/products/identity-personalization/notifications/2018-notifications-work/ | |
| vets.gov-team/Products/Identity/Personalization/Recommendations/ | va.gov-team/products/identity-personalization/logged-in-homepage/my-va/2018-find-va-benefits/ | |

## Tasks

- [ ] Regroup with Samara if you have questions
- [ ] Move vets.gov-team folders to va.gov-team repo

## Acceptance criteria

- [ ] All folders have been moved to the va.gov-team repo

**Comment by billfienberg** [comment]
The first row of the table is done. 

All of the files from https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Identity/Personalization/Account have been moved to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-settings-V1.

**Comment by billfienberg** [comment]
The fourth row of the table is complete. All of the files from https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Identity/Personalization/Profile/Design have been migrated to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/profile-V1/design

**Comment by billfienberg** [comment]
The fifth row of the table is done. 

All of the files have been migrated from https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Identity/Personalization/Profile/MHV%20Profile to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/profile-V1/mhv-profile.

**Comment by Samara-Strauss** [comment]
Thank you so much for all of this! Everything looks good to me!

**Comment by billfienberg** [comment]
All of the files have been migrated. I just need to add the last of the deprecation messages, and the ticket should be ready for QA.

**Comment by Samara-Strauss** [comment]
Thank you!!

**Comment by billfienberg** [comment]
The last of the deprecation messages should be done. This is ready for QA.

**Comment by Samara-Strauss** [comment]
This looks great! It's ready to close from my end unless there are other things you need to do.
