### ISSUE TITLE
[DevOps] Copy Datadog API key from `vaec-cms` to `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84117]
## Description

Key: `tevi/datadog/ramped/keys`

## Tasks
- [ ] [DevOps] Create new SecretsManager entry for Datadog API key in `vaec-cie`.
- [ ] [DevOps] Document [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/devops/vaec-cie-migration/non-iac-resources.md).
- [ ] [DevOps] LoROTA application has permission to access.

## Acceptance Criteria
- [ ] Value is added appropriately.
- [ ] Value is documented appropriately.
- [ ] Value is accessible.

**Comment by ndouglas** [comment]
All necessary work for this was done in #84166; there's no meaningful difference between the two keys.
