### ISSUE TITLE
[V0] ITF -- Add ASYNC get

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#84114]
# Overview
When in doubt about requirements, always use the [mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1714050769683/e4dffd0f80fc8aca04a773dbe53c0d40fd5f2dde?wid=39-1716924696673) as the source of truth.

This ticket represents the work needed to do the async job to retrieve the ITF.   This is a GET to 
`veterans/{veteranId}/intent-to-file/{type}`
https://developer.va.gov/explore/api/benefits-claims/docs?version=current

Create a new table for queue exhaustion
```
 create_table "intent_to_file_queue_exhaustion", force: :cascade do |t|
      t.string "veteran_id" # This is a PK
      t.string "form_type" # 21p-527EZ, etc.
      t.datetime "created_at", null: false
      t.index ["veteran_id"], name: "index_intent_to_file_queue_exhaustion_veteran_id"
    end

```
## Task
- [ ] - Hide work behind a flipper
- [ ] - Write code for the asynchronous API call
- [ ] - Handle queue exhaustion

**Comment by matt4su** [comment]
Note: temporary for V0, would have to be revisted for V1

**Comment by mjknight50** [comment]
This can be closed.
There was a time when we considered doing an async GET first to retrieve the ITF before we tried to do the POST (which creates one).   Now that we know that duplicates are handled properly and that the oldest one is still respected, we don't need to worry about duplication, which is what this ticket would have addressed.
