### ISSUE TITLE
[DevOps] Create relevant environment variables/config/whatever for Datadog to run in LoROTA.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84119]
## Description

e.g.

```yaml
    enableDDTracing: true
    enableEnhancedMetrics: true
    enableXrayTracing: false
    env: !Sub '${EnvType}'
    extensionLayerVersion: 55
    logLevel: info
    nodeLayerVersion: 108
    service: "lorota"
    site: 'ddog-gov.com'
    stackName: !Ref "AWS::StackName"
```

## Tasks
- [ ] [DevOps] Figure out how Datadog needs to be configured to run with Lambdas configured by Terraform.
- [ ] [DevOps] Ensure we provide configuration/values matching above.

## Acceptance Criteria
- [ ] LoROTA Lambdas are configured appropriately to report metrics and other information to Datadog.

**Comment by ndouglas** [comment]
This should be done, it's just not verified yet.
