### ISSUE TITLE
Remove obsolete VAOS feature toggle from production

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#84111]
## Task Description

The following obsolete feature toggles have been removed from VAOS codebase (vets-website and vets-api). These feature toggles still need to be deleted from the production database as described [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles). This issue tracks the eventual request for VA platform to perform the necessary actions.

See the list of feature toggles to remove in Notes and References:

## Notes and References

Here is the full list of feature toggles to remove:
- `va_online_scheduling_physical_location`: #80772 and https://github.com/department-of-veterans-affairs/vets-api/pull/17009
- `va_online_scheduling_request_flow_update`: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64029
- `va_online_scheduling_GA4_migration`: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82973
- `va_online_scheduling_status_improvement`: https://github.com/department-of-veterans-affairs/va.gov-team/issues/55085

## Acceptance Criteria
- [ ] The listed feature toggles have been removed from the production environment

## Deliverables
- 

---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by Bren22va** [comment]
Feature flag clean-up

**Comment by JunTaoLuo** [comment]
I filed a Platform support ticket and it has been completed. I checked the production flipper page and it looks like all four toggles have been removed. Moving to validate for validation by another set of eyes before closing.

**Comment by ldelacosta** [comment]
Validated and no issues to report. Closing out the ticket. cc: @JRRoof @Bren22va
