### ISSUE TITLE
[DevOps] Evaluate CHIP API usage, plan, limits, etc.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84128]
## Description
CHIP access to LoROTA is planned and metered. Are these numbers sufficient to cover future growth? Do we have alarms that will signal when we might approach or exceed these limits? Are they necessary? Are they appropriate? Inquiring minds want to know.

## Tasks
- [ ] [DevOps] Check the `vaec-cms` stats for the CHIP access usage and find what we can find.
- [ ] [DevOps] Determine what sort of monitoring and alerting we do have and can have in place to track usage.
- [ ] [DevOps] Determine a plan of action if necessary.
- [ ] [DevOps] Open up followup ticket(s) to address.

## Acceptance Criteria
- [ ] Topics researched
- [ ] Followup ticket(s) opened as necessary to address areas of concern.

**Comment by ndouglas** [comment]
I flat-out do not think that usage plans are necessary. At present these are uncapped to prevent issues from occurring.
