### ISSUE TITLE
[DevOps] Copy hashing salt from `vaec-cms` to `vaec-cie` or create new salt.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84122]
## Description
Probably copying this is more safe from a consistency point of view, but consistency may not be necessary if we do a switchover overnight, etc.

## Tasks
- [x] [DevOps] Determine whether this can be copied over.
- [x] [DevOps] If possible, copy it over. If not, create a new salt.

## Acceptance Criteria
- [x] New salt(s) exist in `vaec-cie`.

**Comment by ndouglas** [comment]
Perhaps these should be rotated as well?
