### ISSUE TITLE
[DevOps] Recreate LoROTA DynamoDB with TTL rule matching current.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84123]
## Description
LoROTA DynamoDB is configured in deployment to remove expired records using a TTL configuration. However, this was never recorded in the Infrastructure-as-Code, so this isn't currently configured in the `vaec-cie` IaC. This should be added.

## Tasks
- [x] [DevOps] Determine configuration in place in `vaec-cms`.
- [x] [DevOps] Comment out table block in IaC and replace environment variable reference with a dumb string.
- [x] [DevOps] Deploy to all `vaec-cie` environments.
- [x] [DevOps] Replace table block, including TTL configuration, and repair environment variable references.
- [x] [DevOps] Deploy to all `vaec-cie` environments.

## Acceptance Criteria
- [x] DynamoDB TTL is configured in all `vaec-cie` environments.

**Comment by ndouglas** [comment]
So per this:
- https://dsva.slack.com/archives/C04G3EY2F5W/p1686543809242819
- https://dsva.slack.com/archives/C038C047X2P/p1681476474614209

and after checking manually, I see that TTL is indeed enabled in DynamoDB and the existing Cleanup Lambda is not useful and has no reason for existing.

**Comment by ndouglas** [comment]
This is in place now.
