### ISSUE TITLE
[DevOps] Evaluate `vets-api` API usage, plan, limits, etc.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84130]
## Description
Similar to #84128. `vets-api` has a monitored API key for LoROTA. Is this reliable, sufficient, etc?

## Tasks
- [ ] [DevOps] Investigate the `vets-api` API usage.
- [ ] [DevOps] Open up followup ticket(s) to address any concerns.

## Acceptance Criteria
- [ ] API usage has been investigated.
- [ ] Followup ticket(s) opened to address any concerns.

**Comment by ndouglas** [comment]
I flat-out don't believe this is necessary or a good idea. At present these are completely uncapped to prevent issues.
