### ISSUE TITLE
Domo Dataset Updates for GA4 - Priority Wave 1b

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#84138]
### Description
This ticket is to account for updating the Domo datasets that reference the UA data table in BigQuery -- 176188361. There are 74 total datasets that meet this criteria, so we will be starting with the ones that power are most critical dashboards.

- All VA.gov Dashboard
- Monthly VA.gov Summary
- VA.gov Performance Dashboard

Complete list of datasets can be found [here](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=0&fvid=2002218633).

---

### Tasks
Each of the datasets in Domo have been updated with a GA4 equivalent Views has been created:

**All VA.gov Summary**
- [x] [BQ - Product Form Events by Day](https://va-gov.domo.com/datasources/87b86c11-397b-4320-b632-d87896b5c4fd/details/overview)
- [x] [BQ - Logged In Compare
](https://va-gov.domo.com/datasources/99730988-96f0-495e-93de-6cd332283414/details/data/table)
- [x] [BQ - Standard Search](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/overview)
- [x] [BQ - Records Letter Downloads](https://va-gov.domo.com/datasources/6ec00bab-98a0-4ea6-b7ec-6ac721dbb33e/details/overview)
- [x] [BQ - VAOS Events 
](https://va-gov.domo.com/datasources/b1a085f4-b988-49d7-b283-aa3ec7c30acc/details/overview)
- [x] [BQ - VAOS User Completion for All VA
]( https://va-gov.domo.com/datasources/4e391ee5-8310-4116-86cf-76c2384e70ae/details/overview)
- [x] [BQ - All VA - PVs, Sessions, Users, Bounces by Month](https://va-gov.domo.com/datasources/b9b232d0-0a8f-45cb-a1c4-a828418cd261/details/overview)
- [x] [BQ - Modernized - PVs, Sessions, Users, Bounces by Month 
](https://va-gov.domo.com/datasources/6d0dd635-41bf-4ee4-9866-c49e8d701870/details/overview)
- [x] [BQ - Facility Locator pageviews by day
](https://va-gov.domo.com/datasources/49a759eb-dfcc-4e00-8251-67e84b3e4f5c/details/settings)
- [x] [BQ - Resources & Support pageviews](https://va-gov.domo.com/datasources/464201c2-6e26-45d4-b9d6-0ba6ca377df8/details/overview)
- [x] [BQ - Profile Detail 
](https://va-gov.domo.com/datasources/86cbef9e-c473-4e62-b6c8-be7448f1c961/details/overview)
- [x] [BQ - Claims users by month](https://va-gov.domo.com/datasources/42d302a8-0483-4e6d-a868-fcf28e8c92f5/details/overview)

**VA Performance Dashboard**
- [x] [BQ - All Product Post-911 Events by Day](https://va-gov.domo.com/datasources/d8c0ad4e-1698-4e27-9107-64ece0a3807f/details/overview)
- [x] [BQ - Claims Events by day](https://va-gov.domo.com/datasources/a8be940b-5929-46e6-874b-0ed0c77c016b/details/overview)
- [x] [BQ - Login Events by Day](https://va-gov.domo.com/datasources/9fd960c4-fabf-46fe-98bb-9be6d532c14f/details/settings)
- [x] [BQ - Records Letter Downloads](https://va-gov.domo.com/datasources/6ec00bab-98a0-4ea6-b7ec-6ac721dbb33e/details/overview)
- [x] [BQ All VA Total Users: For Performance Dashboard](https://va-gov.domo.com/datasources/3f789788-3088-44aa-ab1a-7beefe3085c0/details/overview)
- [x] [BQ - Product Form Events by Day](https://va-gov.domo.com/datasources/87b86c11-397b-4320-b632-d87896b5c4fd/details/overview)

**Monthly VA.gov Summary**
- [x] [BQ - Claims Events by day](https://va-gov.domo.com/datasources/a8be940b-5929-46e6-874b-0ed0c77c016b/details/overview)
- [x] [BQ - Login Events by Day](https://va-gov.domo.com/datasources/9fd960c4-fabf-46fe-98bb-9be6d532c14f/details/settings)
- [x] [BQ - Form Events by Date and Device Category
](https://va-gov.domo.com/datasources/7c6bed43-1daa-43bb-bfcf-e44fd6b78958/details/settings)
- [x] [BQ - Records Letter Downloads](https://va-gov.domo.com/datasources/6ec00bab-98a0-4ea6-b7ec-6ac721dbb33e/details/overview)
- [x] [BQ - All VA - PVs, Sessions, Users, Bounces by Month](https://va-gov.domo.com/datasources/b9b232d0-0a8f-45cb-a1c4-a828418cd261/details/overview)
- [x] [BQ - Modernized - PVs, Sessions, Users, Bounces by Month 
](https://va-gov.domo.com/datasources/6d0dd635-41bf-4ee4-9866-c49e8d701870/details/overview)
- [x] [BQ - Facility Locator pageviews by day
](https://va-gov.domo.com/datasources/49a759eb-dfcc-4e00-8251-67e84b3e4f5c/details/settings)
- [x] [BQ - Standard Search](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/overview)
- [x] [BQ - Monthly Unique Users by LOA
](https://va-gov.domo.com/datasources/d32a7f4b-7916-4194-917f-d45722b2ea62/details/settings)
- [x] [BQ - Profile Detail 
](https://va-gov.domo.com/datasources/86cbef9e-c473-4e62-b6c8-be7448f1c961/details/overview)

---

### Acceptance Criteria

- [x]  New views/queries have been written to reference GA4 data. 
- [x] Dataset has been marked as updated in the dataset log [here](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=0&fvid=2002218633).
