### ISSUE TITLE
Spike: Postman test runs internal to EKS cluster

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#84143]
# Description
Given that EKS cluster resources are not inherently accessible from outside the cluster without significant additional work, we will create a spike solution that avoids the issue by using Postman to retrieve the test definition from a repo available to the cluster deployment workflow or from the Postman cloud service.

## Tasks
- [x] Create a Postman collection containing at least one test that verifies a well-used `vets-api` endpoint
- [ ] Experiment with running the Postman test inside a test EKS cluster by retrieving the test collection from a repository
- [ ] Experiment with running the Postman test inside a test EKS cluster by retrieving the test collection from Postman Cloud service

# Acceptance Criteria
- [x] A spike that executes at least one Postman test on a test cluster is available
- [ ] A document describing the spike solution is in Confluence

**Comment by IGallupSoCo** [comment]
I've tried using the mock auth setup that was built for local and dev testing, which seems to be a dead end.  I'm going to work on capturing the calls made to pass through the mocked auth UI that's accessible on dev.

**Comment by IGallupSoCo** [comment]
I tried working with Postman Interceptor to capture the request flow that could lead to mocked authentication in dev.va.gov, which is the only active environment where it is possible to use.  

I can retrieve a session ID while running the calls and their pre/post scripts manually, but I am unable to capture the cookies needed to actually succeed at the mock authentication.  Given the importance of being able to reach authenticated endpoints alongside those that require none, I am am concluding that this effort is not a valid path forward for the Product Team's initiative.

**Comment by IGallupSoCo** [comment]
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Product%20Documentation/va_identity_postman.json
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/service_account.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/endpoints/token.md

Reopening while I explore these docs to see if we may have some options for this approach after all.

**Comment by IGallupSoCo** [comment]
With some help from Lindsey and the the Identity Team, I am able to retrieve data from an authenticated endpoint from my terminal by building this call from a set of 8 steps:

<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHR0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ff4a170bbd4a7986c50b1bd6b24db778fcbe3dc/Screenshot%202024-06-17%20at%2012.03.45%E2%80%AFPM.png" alt="Screenshot 2024-06-17 at 12.03.45 PM.png" />

**Comment by IGallupSoCo** [comment]
Next:  Develop the Postman scripts that can replicate these steps

**Comment by IGallupSoCo** [comment]
I am closing this ticket out as a success.  The suite is running in the Postman desktop app and with Newman CLI:
<img width="1072" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDUwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--117a6bfb1c015fff2a23a72a74e7c3e0b337dfdc/Screenshot%202024-06-18%20at%204.20.59%E2%80%AFPM.png" alt="Screenshot 2024-06-18 at 4.20.59 PM.png" />
<img width="712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHgwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fe175174de66c43851302e30d6bcea4a1e29a3a/Screenshot%202024-06-18%20at%204.16.34%E2%80%AFPM.png" alt="Screenshot 2024-06-18 at 4.16.34 PM.png" />

If the Product Team and Peter all agree that this is worth pursuing, I can continue developing the suite to test more endpoints, both authenticated and not, as well as developing the deployment jobs that would be necessary to automate these tests.
