### ISSUE TITLE
Detailed design to reduce duplicate submissions

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#84154]
## Product Outline
[Feature brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Submission%20Experience.md)

## Problem statement
Veterans sometimes submit duplicate claims because Veterans aren't sure if the claim went through. This requires additional effort on the part of VSRs and the organization to identify and manage and respond, and it will delay the Veteran's claim processing.

## Hypothesis or Bet
**If** _we address messaging and build safeguards through how we handle in-progress forms after submission_ **then** _we expect the number of duplicate submissions to reduce.

## Related
1. [Add duplicate submissions to the Submission Experience user story map#82511](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/82511)
2. [Understand current state of user experience of an in progress form becoming a submitted claim](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/83163)

## Tasks
- [ ] Design mockups for 
    - [ ] appearance and behavior of in-progress forms after submission 
    - [ ] any elements that need to change in other touchpoints
- [ ] Make any relevant changes to how we describe the process in static page content, per #83049
- [ ] Align on design approach with OCTO
- [ ] Check with engineering on feasibility of approach
- [ ] Share early designs with VBA
- [ ] Begin collaboration cycle for this stream of work

## Acceptance criteria

- [ ] Internally validated designs for ways to help Veterans keep track of their claims post-submission
