### ISSUE TITLE
Drupal audit: por favor/favor de in Spanish pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#84165]
> [!WARNING]
> Do not use this ticket unless directed to do so by the CAIA team.

## Issue description
On English pages, we have been removing the word "please" and need to do the same on our Spanish pages. We need to do a content search in Drupal for places where we have "por favor" or "favor de" and delete.

## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [x] Do Drupal content search (Victoria)
- [x] Update Drupal pages with changes (Victoria)
- [ ] Review changes (Sara)
- [ ] Publish page (Sara)

## Acceptance Criteria
_What will be created or happen as a result of this story? Examples:_
- [ ] Pages are live with changes

**Comment by moviedosoco** [comment]
@saratorres2 These are the live pages where "por favor" and "favor de" have been deleted in Drupal. 
1. [Preguntas frecuentes sobre el coronavirus: lo que necesitan saber los veteranos](https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/) (5)
2. [Vacunas contra el COVID-19 en VA](https://www.va.gov/health-care/covid-19-vaccine-esp/) (2)

**Comment by juliana-jara** [comment]
@RLHecht I deleted two "por favor" and "favor de". Here's the draft: https://prod.cms.va.gov/node/14580/latest

**Comment by RLHecht** [comment]
Thanks @juliana-jara! I just reviewed and published that one. Can you check the other one in this ticket to see if those changes all look good? [Vacunas contra el COVID-19 en VA](https://www.va.gov/health-care/covid-19-vaccine-esp/) 

You'll want to look at it in the revisions view so you can see what's changed since the last time we published. We can go over this if you're not sure how to do it!

**Comment by juliana-jara** [comment]
@RLHecht The [Vacunas contra el COVID-19 en VA](https://prod.cms.va.gov/health-care/covid-19-vaccine-esp) page does not have any "por favor" or "favor de".

**Comment by juliana-jara** [comment]
Hi @RLHecht Is it OK if we close this ticket?

**Comment by RLHecht** [comment]
yep, this is good to close. Thanks!
