### ISSUE TITLE
Staging Review [Yellow Ribbon MVP]

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8416]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline ([link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/yellow-ribbon-mvp-product-brief.md))
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Access information for the tool or feature in staging  https://staging.va.gov/education/yellow-ribbon-participating-schools/
- Link to your product test cases/test plan in TestRail with test execution logs [test plan](https://dsvavsp.testrail.io/index.php?/plans/view/213)
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/72) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/plans/defects/213) reports in TestRail _for QA practice area review_
    - [Tze's test-runs](https://dsvavsp.testrail.io/index.php?/reports/overview/8)
- Link to your accessibility test cases:
  - **TestRail** [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/plans/view/105) **OR**
  - **Markdown** [Github accessibility test cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/accessibility-test-cases-template.md)

Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.
- [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) (required)
- [X] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) (recommended)
- [X] Conduct axe browser scan, and document or address issues found (required)
- [X] Ensure end-to-end tests - including the axe check, pass (required)
- [ ] Add keyboard end-to-end tests in CI/CD test runs (recommended)
- [X] Conduct axe-coconut browser scan, document or address issues found (recommended)
- [ ] Test with [WAVE tool](https://wave.webaim.org/) (recommended)
- [X] Check color pairing for proper contrast (required)
- [X] Check for colorblindness issues (required)
- [X] Zoom to 200% and confirm readability, no info cut off, etc (required)
- [X] Repeat for 300% (required)
- [X] Repeat for 400% (required)
- [X] Navigate all pages and core functionality with keyboard only (required)
- [X] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox (required)

Known issues, documented in this comment from the [a11y spot check review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7344#issuecomment-609955111).

## Meeting attendees from **requesting team**
- Product Manager (required): Stephanie Orkand
- DEPO product lead (required): Jen Lee
- Anyone else from your team who significantly contributed to the artifacts provided (required): Kelson Adams

## Scheduling
Preferred dates or times: afternoon of May 6, morning of May 7? Will likely require discussion

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by stephorkandatx** [comment]
Ignore comment above, discussion in Slack worked through my question

**Comment by meganhkelley** [comment]
Scheduled for 5/7

**Comment by stephorkandatx** [comment]
@meganhkelley Almost all artifacts have been updated and attached. The test runs were started today, and reports will be generated tomorrow early afternoon.

**Comment by mnorthuis** [comment]
Reviewed the tool, all looks good. 

Will need to see the static content work to review entry points once that is available:
- hub page
- left nav
- yellow ribbon page

Redirect work is in progress.

**Comment by meganhkelley** [comment]
Product feedback — as mentioned on the meeting, no response or validation is required here. Thanks!

Product Outline: 
- What is your hypothesis of how this work will impact your KPI (# of people visiting YR pages per month), and why? 

Release plan: 
- What are your results from moderated production testing? Did you identify/fix any bugs?
- Who will be able to access your tool during unmoderated production testing — you mention only people with a link, but will that just be y’all or will you be releasing to actual end users? 
- Are you doing a phased rollout to end users? If no, why? (How might we think about doing phased rollouts in the future when the rollout is just redirecting links?)
- During unmoderated production testing, you note “when the tool has been verified” — what are you looking for to verify the tool? List those steps and/or metrics.
