### ISSUE TITLE
[DevOps] Copy Tevi Datadog secrets from `vaec-cms` to `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84166]
## Description
I don't believe these are referenced by IaC right now outside of `terraform-cms/datadog` in `checkin-devops`, and that's just establishing them, not really using them in any way. Would presumably be useful as a part of #83403 though.

## Tasks
- [x] [DevOps] Copy secrets to `vaec-cie`.

## Acceptance Criteria
- [x] Secrets exist in `vaec-cie`.
- [x] Secrets are documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/devops/vaec-cie-migration/non-iac-resources.md).

**Comment by ndouglas** [comment]
Note, referring to `tevi_datadog_terraform_api_key` here. #84117 refers to `{{resolve:secretsmanager:tevi/datadog/ramped/keys:SecretString:key}}`. Why? Are these different? Are they managed differently?
