### ISSUE TITLE
Spanish translation Irak vs. Iraq

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#84163]
> [!WARNING]
> Do not use this ticket unless directed to do so by the CAIA team.

## Issue description

We currently use both Iraq and Irak on our Spanish pages and need to choose one for consistency. Both are correct so we need to discuss with State to hear what their guidance is and so we can establish a standard for VA.gov. 

[Spanish word list for documentation](https://docs.google.com/document/d/13VcCEyF16UnA8Y1iOQobCKoRELN9VkQf7mr1-iCyRwo/edit)

## Tasks

- [x] Send email to State to start discussion (Victoria)
- [x] Finalize decision and document in Spanish word list (Victoria, Sara, Randi)
- [x] Open ticket for Drupal content audit (Victoria)

## Acceptance Criteria
- [x] Final decision is established and documented in Spanish word list

## Configure this issue
- [ ] _Attach to an Epic (what body of work is this a part of?)_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_

**Comment by moviedosoco** [comment]
@RLHecht I sent the email to State on June 3rd.

**Comment by moviedosoco** [comment]
@RLHecht As per State's response, we should follow the recommendation from Fundeu and RAE, and use **Irak** across all the Spanish pages on VA.gov.
It's added to the Spanish words list.

**Comment by moviedosoco** [comment]
Ticket is completed and good to close.
