### ISSUE TITLE
Investigate Options for Disabling Req Body in Faraday Error Handling

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#84176]
## Issue Description

As described in an [issue](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1658) raised by Jonathan Kamens, a Faraday Upgrade a few months back opened the door for PII to potentially get logged in Production. We should investigate potential solutions, and implement one of them.

Potential solutions:
* As Jonathan mentioned: An automated linter to ensure include_request: false in future PRs (+ Ryan's PR)
* A monkey patch to Faraday
* A PR to Faraday to change the default (this comment suggests they'd consider it)
* Perhaps a way to inject a Faraday middleware that sets the option to false

---
## Tasks

- [x] Investigate potential solutions listed above, noting any findings here.

## Acceptance Criteria
- [x] Appropriate solution has been determined
- [x] Solution has been communicated in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1658
- [x] Tickets created to address issue based on approach decided

**Comment by ryan-mcneil** [comment]
Findings:

* `vets-api` has a `RaiseError` class defined that is overriding the middleware associated with the default Faraday middleware `:raise_error`, and it is clearly confusing some devs working within the project
* The use of this class prevents us from using the original method we considered of adding the `include_request: false` option to the middleware (which wouldn't have been an efficient way, anyway).
* Implementing our own middleware doesn't seem to be effective, as it would require us to replace current middleware with a new custom middleware AND require developers to use it in the future. If anyone failed to use the new middleware, and use the standard Faraday middleware, they wouldn't receive the default functionality we are attempting to implement
* The simplest way forward seems to be monkey patching the Faraday::Response::RaiseError middleware `initialize` method to implement the required default option.

**Comment by ryan-mcneil** [comment]
Tickets Created:
* #84394
* #84397
