### ISSUE TITLE
One VA Debt Letter - Web

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#84175]
## Summary
**Objective:**
Establish a PDF that allows Veterans to see both benefit overpayment debts and medical copayments on the same document. 

**Problem Statement**
In response to the legislative requirement set in the [Veterans Benefit Transition​ Act of 2018 (year 7)​](https://www.congress.gov/115/plaws/publ407/PLAW-115publ407.pdf) this initiate is focused on establishing a standard letter format that summarizes any active debts (benefit overpayments and medical copays) the Veteran has with VA.

**Why is this Important**
- Comply with  [Veterans Benefit Transition​ Act of 2018 (year 7)​](https://www.congress.gov/115/plaws/publ407/PLAW-115publ407.pdf)
- Provide Veterans with a standard format for individuals indebted to VA 

**Solution (Bet)**
Provide Veterans with the ability to view, download and save a PDF copy of the letter template in a single format that summarizes benefit overpayment debts and medical copayments. The letter will include all necessary information for the Veteran to understand why they have the debt, summarize the current balance owing and provide information should they have questions. 

**Results or Impact**  
 -  Number of PDF views and downloads
-   User feedback and satisfaction rates

**Objectives and Key Results (OKRs) Alignment**
 - **OCTO OKR 01.1** Improve satisfaction with our web and mobile products by 5 points

**Known risks or challenges**
- Current design system does not define requirements for print materials
- PDF, HTML or other implementation formats will require investigation for feasibility

**Reference links:**
 - [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/one_va_debt_letter/product%20outline.md)
  - *QA Test Plan:*  [Link TBD](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)
-   [Release Plan:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/one_va_debt_letter/Release_Plan.md)
- Draft One VA Debt Letter Provided by Debt Management Center  [VA 1 Debt Letter OnlineMVP Draft 01 02 2025.docx](https://github.com/user-attachments/files/18881342/VA.1.Debt.Letter.OnlineMVP.Draft.01.02.2025.docx)
- [User Data Flow Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1743525738910/3f3eeef385afbf2f77fb6e62d0db524bc4edf138)
- [Datadog Debts](https://vagov.ddog-gov.com/dashboard/shm-nr4-75f?fromUser=false&refresh_mode=paused&view=spans&from_ts=1744676895134&to_ts=1744849695134&live=false&tile_focus=7532675980075440)
- [Datadog Copays](https://vagov.ddog-gov.com/dashboard/shm-nr4-75f?fromUser=false&refresh_mode=paused&view=spans&from_ts=1744676939869&to_ts=1744849739869&live=false&tile_focus=5484730537707928)
- [One Debt Letter Widget](https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/6re-uzp-kx3)

# Development Tracking

## Monthly Initiative Updates
|Month|Status Notes  |
|--|--|
| February 2025 | Initiative Kickoff & Discovery; PO sync completed and progressing with development. |
|April 2025 | Phased release stared on April 23; reached 100% on April 30th. Communicated to all stakeholders. In first week 1.23 downloads + 1209 pageviews. Continuously monitoring feedback and metrics going forward. |

## Collaboration Cycle Tracking
|CC Event| Information  |
|--|--|
| Kickoff |Feb 3, 2025 - #104021   |
| PO Sync | March 5, 2025 |
| Design Intent | March 17, 2025 |
| Architecture Intent| April 10, 2025 |
| CMS Request |  |
| Research Review |  |
| Midpoint Review | April 4, 2025 |
| Analytics Request | April 10, 2025 |
| Contact Center Review |  |
| Staging Review| April 17, 2025 |
| Privacy and Security Review | April 22, 2025 |

## Release Tracking
*Detailed Release Strategy and Plan information can be found on Product Outline. This is for quick reference of release dates.* 
|Release Event| Information  |
|--|--|
| Target Launch Date| April 25, 2025 |
|Go/No-Go Meeting | April 22, 2025 (Details below) |
| Start Staged Launch - 33% | April 23, 2025 |
| 2nd Staged Launch - 66% | April 28, 2025 |
| Full Launch complete - 100% | April 30, 2025  |

**Go/No-Go Meeting Details:**
- Date: April 22, 2025 
- Attendees: Development team, VA PO and DMC Stakeholders
- Outcome: Confirmed deployment April 23, 2025/ 9am EST

## Definition of done
*What must be true in order for this super epic to be considered complete?*
**Product Completion:**
- [x] PDF document successfully consolidates and presents both types of debt in a single structured format
- [x] Veterans can generate and download the document from the portal without issues
- [x] The document is a close reflection of the proposed format that mirrors the existing medical copay statements that are being mailed to Veterans today. 

**Deployment, Documentation & Monitoring**
- [x] QA Test plan is complete
- [x] Release plan is complete
- [x] Product Outline is complete
- [x] Post launch monitoring plan and critical issues have been resolved
- [ ] [Recently Shipped Slides](https://dvagov.sharepoint.com/:f:/r/sites/vadebtresolutionteam/Shared%20Documents/4_Product/Recently%20Shipped?csf=1&web=1&e=Zz3eXD) are complete
- [ ] Metrics have been established + Domo/Google Analytics Dashboards/Reports are available/updated
- [x] Follow-up tasks for enhancements or fixes have been created in backlog

**Comment by Tom-Davis** [comment]
Closing as all work is complete and 30 day metrics are available.
