### ISSUE TITLE
Monthly Find a Representative post-launch metrics (May 2024)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84184]
## Tasks
- [ ] ~Create a summary document in Github for storing monthly metrics~
- [x] Create a folder in Sharepoint for storing raw data from the Contact Center
- [x] Request metrics from the Contact Center for 4/14 - 5/31
- [x] Grab GA metrics for 4/14 - 5/31
- [x] Create a summary spreadsheet of GA metrics
- [x] Add Contact Center and GA metrics in Sharepoint

## Acceptance Criteria
- [ ] Documentation has been setup for monthly ARM insights, and the most recent months' metrics have been logged.

**Comment by oddball-lindsay** [comment]
Can we use these Domo Dashboards? 

1. [Salesforce Issues](https://va-gov.domo.com/page/130739792) (Seems to be the MyVA411 data)
2. [Medallia Report](https://va-gov.domo.com/page/825663825)

**Comment by oddball-lindsay** [comment]
Request from contact center: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/84524 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/84525

**Comment by oddball-lindsay** [comment]
Contact Center Medallia export for 4/14-5/30 includes:
- 39 VFS Questionnaire responses
- 11 Intercept survey responses

The Contact Center Domo dashboard for 4/14-5/30 reports:
- 38 VFS Questionnaire responses
- 8 Intercept survey responses

**Comment by oddball-lindsay** [comment]
Leaning towards a spreadsheet of Google Analytics insights that we store in Sharepoint and update on a Monthly basis until we have a performance dashboard in Domo.

For high level Medallia survey trends, the Domo report is good enough.  But we can still pull monthly qualitative exports, remove PII, then store in Sharepoint.

**Comment by jfinnerty13** [comment]
WIP: https://docs.google.com/spreadsheets/d/16Tr3nVdRHTteverx5yoBoBV32s0wvUrtW4-Daoi4hEE/edit?usp=sharing
