### ISSUE TITLE
[DevOps] Migrate `octo-vista-api` to use OIDC provider on `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84180]
## Description
Follow up to #86814.

This currently uses access keys, which is a no-go going forward. 

We need to configure this to use an OIDC provider.

Let's do this in `checkin-devops`' IAM module rather than in a separate TF template.

## Tasks
- [x] [DevOps] Determine what permissions are needed.
- [x] [DevOps] Create appropriate IAM Role and IAM Policy with specified permissions.
- [x] [DevOps] Configure repository and workflows to assume role in `vaec-cie`.

## Acceptance Criteria
- [ ] `octo-vista-api` can build deploy resources as needed within `vaec-cie`.

**Comment by olivereri** [comment]
## List of files needing credential updates

[.github/workflows/certificates.yml](https://github.com/department-of-veterans-affairs/octo-vista-api/blob/65b707b7db7158f743a28e7e1893eaaa10388a46/.github/workflows/certificates.yml#L12)

[.github/workflows/wildfly.yml](https://github.com/department-of-veterans-affairs/octo-vista-api/blob/65b707b7db7158f743a28e7e1893eaaa10388a46/.github/workflows/wildfly.yml#L19)

[.github/workflows/build-vista-api.yml](https://github.com/department-of-veterans-affairs/octo-vista-api/blob/65b707b7db7158f743a28e7e1893eaaa10388a46/.github/workflows/build-vista-api.yml#L21)

[.github/workflows/update-datadog-image.yml](https://github.com/department-of-veterans-affairs/octo-vista-api/blob/65b707b7db7158f743a28e7e1893eaaa10388a46/.github/workflows/update-datadog-image.yml#L15)

[.github/workflows/deploy-vista-api.yml](https://github.com/department-of-veterans-affairs/octo-vista-api/blob/65b707b7db7158f743a28e7e1893eaaa10388a46/.github/workflows/deploy-vista-api.yml#L46)

**Comment by ndouglas** [comment]
Doesn't actually do anything, but it works...

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/080a44a3-e905-45f2-b13a-60f86757a14d)
