### ISSUE TITLE
[DevOps] Coordinate any `vista_api` endpoint changes with VSECS app/Clinician Workflow API

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84185]
## Description
See [here](https://dsva.slack.com/archives/C02G6AB3ZRS/p1717011093471059).

This will need to be coordinated with VSE Clinical Staff/Clinician Workflow API.

How do these people hit our endpoints?

Can we get example payloads/requests/responses?

Are they hitting something hardcoded that we can refactor to a DNS name?

If so, where would that DNS name be housed?

What are their needs for functional parity across different environments?

Can we get code from them or some reasonable facsimile of a code path or workflow that simulates what and where they expect us to be present?

## Tasks
- [x] [DevOps] Determine who these people are.
- [x] [DevOps] Discuss migration with them, figure out a timetable for changes and how to manage them.
- [x] [DevOps] Goals are:
  - [x] to be able to automate our changes without requiring action on their end, a heads-up at most
  - [x] to know when we aren't meeting their needs to shorten the feedback cycle during development
  - [x] to know when we're breaking things they rely on
  - [x] to know how to fix deficits in our platform

**Comment by ndouglas** [comment]
1. Is this the best way to talk to you/your team? This is the only VA Slack I'm in, but I'm also in Teams, etc.
1. Have CW's requests to Vista API changed significantly since the product was migrated to a different team? (IOW, how much can I rely on the archived codebase [to which I do have access] to inform what I need to do to provide an MVP architecture your team can validate?)
1. Does your team have a wishlist or any feature requests that I can implement on the infrastructure level (I don't yet understand the application itself well enough to make promises) to make your team's lives easier/more informative/less stressful/etc?
1. Are you just hitting the Vista API LB directly, or is your team using any other services in our account that you know of? (IIRC I think there's an SQS queue you might be reading things from.)
1. Eventually (don't know when) I'm going to need to supply you with different addresses, different credentials probably, that sort of thing. Is there anything you would like me to keep in mind as I plan this process? My goal is to make as many changes as possible completely transparent to your team, but I figure there will be some manual action required. When and how that is done, how we prepare for it, how we do it, how much advance notice you want, what sort of recovery processes I develop, etc, is all up in the air and I welcome your input.
1. One of the things I'm working on right now is implementing system tests that exercise the application as deployed in the infrastructure. The goal is for me to have full confidence in the new system before I ask your team to test. I don't understand Vista API, don't understand Clinician Workflow, and don't understand how the two work together. I can learn some of that from the archived code, but in the meantime if you could ELI5 a list of tests that I could implement, that would give me an idea of a) how complicated these interactions are, b) how much work will be involved in practical terms to get this functional, etc.
1. My understanding is that currently your team is just interacting with the production Vista API. Is that correct? Would it be helpful to be able to interact with the staging Vista API or other lower environments?

For the sake of discussion re: system tests:
> We have an application, LoROTA, that basically acts as a key-value store for PHI/PII that ensures that information never leaves the cloud. It's more-or-less a CRUD app, so I designed the following tests:
>- we can authenticate successfully with a given level of access
>- we can create valid data
>- we can't create invalid data (and error propagation and status codes are returned appropriately)
>- we can retrieve data we've created
>- we can't retrieve nonexistent data (and error propagation... blah blah blah)
>- we can update data we've created
>- we can't make invalid updates to valid data (...)
>- we can't update nonexistent data (...)
>- we can delete data we've created
>- we can't delete non-existent data

**Comment by ndouglas** [comment]
Ryan Lemire at CW says they _need_ to be migrated to their internal replacement for the Vista API dependency by October. Consequently, I have one fewer thing to worry about.

**Comment by ndouglas** [comment]
Reached out to Steve Alcocer, who pointed me to Steve Mammay.
