### ISSUE TITLE
Document 1 week post-launch metrics to Widget release plan

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84181]
## Background
The release plan has a section to log post-launch metrics for a holistic overview of our launch and related usage.  We can log the error statues from Datadog, and any insights from the contact center.

## Tasks
- [x] Request MyVA411 and Medallia from the Contact Center
- [x] Document 1 week post-launch metrics to the [Rep Status Widget release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/release-plan-representative-status-widget-1.0.md).

## Acceptance Criteria
- [x] The release plan has documented metrics for 1 week after launch

**Comment by oddball-lindsay** [comment]
MyVA 411: https://github.com/department-of-veterans-affairs/va.gov-team/issues/84202

Medallia Surveys: https://github.com/department-of-veterans-affairs/va.gov-team/issues/84203
