### ISSUE TITLE
Toxic Exposure - EVSS to LH `transform`  service: empty `treatment['startDate']` causes errors

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#84199]
## Story
The question was posed:
> should a treatment value (nested in the 526 form at form['form526']['form526']['treatments']) always have a startDate?
🤔

Sending a `null/nil` value for `startDate` from vets-website to vets-api for an item in the `treatments` list should be allowed, but the `EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform#transform` method is blowing up.

This [line of code here](https://github.com/department-of-veterans-affairs/vets-api/blob/f3b600a43613deb08f2dd1b6008f012831529164/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L174) is the culprit
Why?
When parsing a `nil` date to be in a certain format, ruby no likey. 💎😡

Lighthouse's submit endpoint(s) allow for this attribute to be nullable - need to check if it is also allowed to be an empty string. (i have a feeling it won't)

## Question
Should we look for other places where optional fields are not parsing correctly in our LH transformer? 🤔

## Tasks
- [ ] enhance `EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform#transform` to not blow up when sending a `nil` empty string `startDate`
- [ ] enhance `EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform` unit tests to account for `nil` or empty string `startDate`

## Acceptance criteria
With the `disability_526_toxic_exposure` feature flag on:
- [ ] submitting a claim with null or empty `treatments` objects from vets-website does not blow up 🚫💥

references:
- [Slack thread](https://dsva.slack.com/archives/C053U7BUT27/p1717015993433529)
- Lighthouse docs (POST /veterans/{veteranId}/526): https://developer.va.gov/explore/api/benefits-claims/docs?version=current
- https://github.com/department-of-veterans-affairs/vets-api/blob/f3b600a43613deb08f2dd1b6008f012831529164/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L174

<img width="991" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bac557b8927b6bdac9cb82b8f3a88d5718e7839/image.png" alt="image.png" />

**Comment by SloopKoning** [comment]
Here is the test data that I used to find this problem. The following JSON for form526 was what I used to file this problem.

This file is pretty printed.

[form526_pretty.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6854831ab50135b74dbd9f2133ebb5498eda6fe6/form526_pretty.json.txt)

This file is not pretty printed:

[form526.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3688a1c1770475c09ffdd837a07d59a8c5d3a07/form526.json.txt)

**Comment by tblackwe** [comment]
In running the Validation Script we have uncovered a few more issues
 - `undefined method '[]' for nil:NilClass -- /app/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:173:in 'transform_service_information'`
   - Form526Submission.id = 1246
   - created_at = 2024-05-28 03:04:11.010697000 +0000
   - 
 - `undefined method '[]' for nil:NilClass -- /app/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:481:in 'convert_approximate_date'`
   - Form526Submission.id = 1245
   - created_at = 2024-05-28 02:25:44.710640000 +0000
   - 
- tbd
  - Form526Submission.id = 1238
  - created_at = 2024-05-20 18:38:29.355686000 +0000
  -

**Comment by tblackwe** [comment]
- `undefined method '[]' for nil:NilClass -- /app/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:481:in 'convert_approximate_date'`
   - Form526Submission.id = 1245
   - created_at = 2024-05-28 02:25:44.710640000 +0000
   - [form526.1245.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0a6c285af9de0046e45f03d69913594adcb2626/form526.1245.json.txt)

**Comment by tblackwe** [comment]
- Validation Failed - Account number for the direct deposit.
  - Form526Submission.id = 1229
  - created_at = 2024-05-17 17:22:22.001616000 +0000
  - [form526_error_1229.hash.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca0a52d54edea3c5c8584b4f7939af879ef0c4c1/form526_error_1229.hash.txt)
  - 
[form526.1229.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54ed866d7767857de4afcf2e41df2c419b8b65cb/form526.1229.json.txt)

**Comment by aurora-a-k-a-lightning** [comment]
fixing the treatmentData issue as a part of #71773 since it was blocking :)

**Comment by tblackwe** [comment]
Ran a Production Validation test, which came up with several new issues. Because it was production I cannot share form JSON.
In priority Order:

 1. undefined method `[]' for nil:NilClass -- /app/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:187:in `transform_service_information'
 2. Response Status Code '422' - The property /directDeposit/accountNumber did not match the following requirements: `{"description"=>"Account number for the direct deposit.", "pattern"=>"^(?:[a-zA-Z0-9]{4,17})?$", "type"=>["string", "null"], "maxLength"=>14, "nullable"=>true, "example"=>"123123123123"}` -- /app/lib/lighthouse/service_exception.rb:37:in send_error'
 3. Response Status Code '422' - `Each treatment begin date must be after the first activeDutyBeginDate.` -- /app/lib/lighthouse/service_exception.rb:37:in `send_error'
 4. Response Status Code '422' - The property /veteranIdentification/mailingAddress/state did not match the following requirements: `{"description"=>"State for the Veteran's current mailing address.", "type"=>"string", "pattern"=>"^[a-z,A-Z]{2}$", "example"=>"OR"} `-- /app/lib/lighthouse/service_exception.rb:37:in `send_error'
 5. Response Status Code '422' - The property /veteranIdentification/mailingAddress/addressLine1 did not match the following requirements: `{"description"=>"Address line 1 for the Veteran's current mailing address.", "type"=>"string", "pattern"=>"^([-a-zA-Z0-9'.']([-a-zA-Z0-9'.' ])?)+$", "maxLength"=>20, "example"=>"1234 Couch Street"} `-- /app/lib/lighthouse/service_exception.rb:37:in `send_error'
 6. Response Status Code '422' - The property /treatments/0/center/city did not match the following requirements: `{"description"=>"City of treatment facility.", "type"=>["string", "null"], "pattern"=>"^$|^([-a-zA-Z'.' ])+$", "example"=>"Portland", "nullable"=>true} `-- /app/lib/lighthouse/service_exception.rb:37:in `send_error'
 7. `undefined method `icn' for nil:NilClass` -- /app/app/models/form526_submission.rb:528:in `lighthouse_service'
 8. Response Status Code '422' - The property /disabilities/0/name did not match the following requirements: `{"description"=>"Name of the disability. The /disabilities endpoint on the [Benefits Reference Data API](https://developer.va.gov/explore/benefits/docs/benefits_reference_data?version=current) may be used to retrieve possible disability names.", "type"=>"string", "pattern"=>"^$|([a-zA-Z0-9\"\\/&\\(\\)\\-'.,# ]([a-zA-Z0-9(\\)\\-'.,# ])?)+$", "example"=>"PTSD (post traumatic stress disorder)", "maxLength"=>255} `-- /app/lib/lighthouse/service_exception.rb:37:in `send_error'
 9. Response Status Code '422' - The property /directDeposit/financialInstitutionName did not match the following requirements: `{"description"=>"Provide the name of the financial institution where the Veteran wants the direct deposit.", "maxLength"=>35, "type"=>["string", "null"], "nullable"=>true, "example"=>"Some Bank"}` -- /app/lib/lighthouse/service_exception.rb:37:in `send_error'
 10. Response Status Code '422' - The property /serviceInformation/servicePeriods did not match the following requirements: {"description"=>"Identifies the Service dates and Branch the Veteran served in.", "type"=>"array", "minItems"=>1, "uniqueItems"=>true, "items"=>{"type"=>"object", "required"=>["serviceBranch", "serviceComponent", "activeDutyBeginDate", "activeDutyEndDate"], "properties"=>{"serviceBranch"=>{"description"=>"Branch of service during period. The /service-branches endpoint on the [Benefits Reference Data API](https://developer.va.gov/explore/benefits/docs/benefits_reference_data?version=current) may be used to retrieve list of possible service branches.", "type"=>"string", "maxLength"=>1000, "example"=>"Air Force"}, "serviceComponent"=>{"type"=>"string", "description"=>"", "enum"=>["Active", "Reserves", "National Guard"]}, "activeDutyBeginDate"=>{"description"=>"Date started active duty.", "type"=>"string", "pattern"=>"^(?:[0-9]{4})-(?:0[1-9]|1[0-2])-(?:0[1-9]|[1-2][0-9]|3[0-1])$", "example"=>"2018-06-06"}, "activeDutyEndDate"=>{"description"=>"Date completed active duty.  If in the future, 'separationLocationCode' is required.", "type"=>"string", "pattern"=>"^(?:[0-9]{4})-(?:0[1-9]|1[0-2])-(?:0[1-9]|[1-2][0-9]|3[0-1])$", "example"=>"2018-06-06"}, "separationLocationCode"=>{"description"=>"Location code for the facility the Veteran plans to separate from. Required if 'servicePeriod.activeDutyEndDate' is in the future. Code must match the values returned by the /intake-sites endpoint on the [Benefits reference Data API](https://developer.va.gov/explore/benefits/docs/benefits_reference_data?version=current).", "type"=>["string", "null"], "nullable"=>true, "example"=>"98283"}}}} -- /app/lib/lighthouse/service_exception.rb:37:in `send_error'

**Comment by sethdarragile6** [comment]
@tblackwe @pacerwow I consolidated these findings to ticket #[86252](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/86252). Closed this ticket since the original treatmentDate issue has been fixed.
