### ISSUE TITLE
Investigate errors from Retrieve Active POA service

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84205]
## Background
As of 5/29, we have received the following statuses from Lighthouse (Benefit Claims API's Retrieve Active POA service).  

Total: 13.7k
200: 12.4k = 90.5%
500: 484 = 3.5%
422: 483 = 3.5%
401: 178 = 1.3%
404: 122 = .9%
504: 42 = .3%

We are hoping to understand what scenarios lead to these non-200 statuses.  From there, we can refine the experience for these scenarios with more relevant/accurate messaging. 

## Tasks
- [x] Understand the scenarios that lead to these non-200 statuses -- both on a technical level, and a "real world" scenario

## Acceptance Criteria
- [x] We understand what scenarios lead to these non-200 statuses
- [x] We have a plan for updating messaging, based on these scenarios

**Comment by oddball-lindsay** [comment]
The team agrees that users returning the `422` status should see the "No representative" state.

Still unsure about the `500` status -- this is related to a missing ICN, and occurs before the LH request is made from vets-api.  LH does not see these.  From what we know from Identity, this could be Veterans or non-Veteran claimants -- anyone who has not verified their identity on VA.gov to become a LOA3 user.  So likely these are all LOA1 users.    

To do for the `500` investigation:
- I will check with Identity (Damian?) to understand the process behind an ICN being created
- Lighthouse is seeing if they have any connections with MPI to better understand this scenario

**Comment by oddball-lindsay** [comment]
Users simply need to verify their identity, after which they are LOA3 and have an ICN.  We discussed introducing a second error state for `500` users, encouraging them to verify their identity.
