### ISSUE TITLE
[FSR] Prefill data investigation 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#84210]
## Description
After an [FE effort](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/76691) to organize and rework the in progress form data we discovered an opportunity for improvement utilizing the [prefill data](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill). [Our current prefill info](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va_5655.rb) is able to provide some veteran contact information and personal data, but maybe there's a way we can use prefil to populate debts & copays? 

## Tasks
- [ ] Investigate prefill functionality to see if we can get more helpful information loaded into the form w/o more FE calls
- [ ] Coordinate with FE to see if there's any other helpful info we can pull from profile data or elsewhere
- [ ] Decide if this effort is worth continuing and create tickets accordingly 

## Acceptance criteria

- [ ] Prefill has been investigated
- [ ] (optional) Tickets have been created to continue work

## Testing
- [x] N/A if non development work

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
