### ISSUE TITLE
[DISCOVERY] Editorial process: Event content

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8422]
## User story 
As a content producer who is unfamiliar with Drupal, I want the process for adding event content to be user-friendly so that I am efficient. 

## Goal
- Content editors can anticipate **how** their additions/edits will be rendered on the page
- Content editors can anticipate **where** the content additions/edits will be rendered on the page
- Content editors need to identify the feature event
- Content editors need to understand the display order for events
- Content editors need to understand how their new content is interrelated to other pages and content 

## Objectives or Key Results this is meant to further
- Decreased support requests to CMS 
---
## Tasks
Determine appropriate editorial experience for events, based on the following:
- [ ] Value of this content block to Veterans
- [ ] Value of this content block to the Business    

## Acceptance Criteria
- [ ] Recommendations for changes to editorial experience for events
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
Consider with single source of truth for events epic, related to #13213.
