### ISSUE TITLE
[DISCOVERY] Editorial process: News release content

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8423]
### User story 
As a content producer who is unfamiliar with Drupal, I want the process for adding news release  content to be user-friendly so that I am efficient. 

## Goal
- Content editors can anticipate **how** their additions/edits will be rendered on the page
- Content editors can anticipate **where** the content additions/edits will be rendered on the page
- Content editors need to understand the display order for news releases
- Content editors need to understand how their new content is interrelated to other pages and content 

## Objectives or Key Results this is meant to further
- Decreased support requests to CMS 
---
## Tasks
Determine appropriate editorial experience for news releases, based on the following:
- [ ] Value of this content block to Veterans
- [ ] Value of this content block to the Business    
 
## Acceptance Criteria
- [ ] Recommendations for changes to editorial experience for news releases

**Comment by jilladams** [comment]
Closing with Michelle input, in favor of future iterations / specific research, at which time we'll re-eval the editor experience.
