### ISSUE TITLE
Create Datadog Synthetic Tests to Monitor Medallia Surveys

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#84249]
## Issue Description
As a Team that manages veteran feedback,
I want to implement Datadog synthetic tests to monitor our Medallia survey platform,
so that I can ensure the surveys are functioning correctly and issues are detected and resolved promptly.
---
## Tasks
- [x] Create a synthetic test for VFS Survey
- [x] Create a synthetic test for Search Survey
- [x] Create a synthetic test for Chatbot Survey
- [x] Create a synthetic test for VHA A11y Survey
- [x] Create a synthetic test for Debt Portal Survey
- [x] Create a synthetic test for ORMDI Survey
- [x] Create a synthetic test for A11y Sitewide Survey

## Acceptance Criteria
 - [x] **Scenario: Create synthetic tests for Medallia surveys**
  - Given the Datadog synthetic tests are implemented
  - When all always on and intercept surveys are monitored using these tests
  - Then the tests should detect any issues with the surveys and report them in Datadog
  
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
submited request for write permission in datadog liquid tests

**Comment by aubreyarcangel** [comment]
<img width="1077" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHFaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea89246404b89cf503fd7680b85fb01c0443d316/Screenshot%202024-06-27%20at%2010.37.19%20AM.png" alt="Screenshot 2024-06-27 at 10.37.19 AM.png" />
Synthetic tests can be found [here](https://vagov.ddog-gov.com/synthetics/tests?query=team%3Avfs-contact-center&from_ts=1719413199735&to_ts=1719499599735&live=true)
