### ISSUE TITLE
[Design] My VA Forms Status: Create design(s) to handle errors

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#84256]
## Background
As part of the work to add forms status (or forms submission status) to My VA we need to be able to handle various system errors such as 

1. Network request fails - no status available (unknown downtime)
2. API request for statuses fails with documented error code
3. Maintenance window (known downtime)

Not applicable for this work is if the main user call fails, which is [handled by full page error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/system-cant-connect-to-MPI.md). The current iteration of the Benefit Application Drafts section, the data for saved applications is gathered from the same API as the main user call. Therefore, there are [no errors](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases/benefit-application-drafts-use-cases.md#edge-cases) (currently) specific to just this section. If the main user call fails, the entire My VA page displays an error, in which case we follow the behavior outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/system-cant-connect-to-MPI.md), for a full page error.)

## Tasks
- [x] Work with FE and BE to identify the types of system errors that can occur
- [x] Create designs for these errors using the [warning alert component](https://design.va.gov/components/alert#warning-alert) - [Figma designs](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=1010-53914&t=c31iajIZhNLerbxy-1)

## Acceptance Criteria
- [x] We have designs for errors

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ PM
- _How can this work be validated?_ Confirm we have designs for errors

## Resources
- Error handling for [claims and appeals](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/claims-and-appeals-use-cases/claims-api-down.md) (for reference)
- Error handling for outstanding debts for reference (probably most similar to what we'll need here): [debt API error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/outstanding-debts-use-cases/debts-API-error.md); [debts _and_ copays API error](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/outstanding-debts-use-cases/debt-and-copay-error.md)

**Comment by mattmarino-adhoc** [comment]
Met on 6/7 with AJ and Tom to review errors in scope, possible scenarios

**Comment by mattmarino-adhoc** [comment]
Handling of error scenarios: 
1. Section alert if network request fails
2. Section alert if API request fails
3. Section alert if scheduled downtime
- Need to also address possible alert at top of page when downtime is expected

**Comment by mattmarino-adhoc** [comment]
https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=1010-53914&t=c31iajIZhNLerbxy-1

**Comment by mattmarino-adhoc** [comment]
Removed earlier comment with link that is no longer accurate: https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-1&t=ViIoFdvCDhuLP1Ra-1
