### ISSUE TITLE
Update styling issues with Medallia v2 surveys

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#84253]
## Issue Description
There are a few elements that need style updates that must be fixed on the new v2 surveys.

---
## Tasks
- [x] Add margin to the bottom of OMB compliance paragragh
- [x] Adjust link color in crisis header language

## Acceptance Criteria
- [x] OMB paragraph spacing is fixed
- [x] Link color in crisis header matches VA.gov link color
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
waiting on PR review

**Comment by aubreyarcangel** [comment]
I combined this ticket with [ticket 84257](https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/84257)
