### ISSUE TITLE
Remove old/unused Medallia code 

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#84257]
## Issue Description
Given the new Medallia v2 update, there is some code that is no longer in use. Go through `vets-website` repo and remove unused Medallia code.
---
## Tasks
- [x] Determine what Medallia code is no longer in use with v2 update
- [x] Remove unused Medallia code

## Acceptance Criteria
 - [x] **Scenario: Remove old/unused Medallia code**
  - Given the new Medallia v2 update
  - When the developer identifies and removes unused Medallia code from the repo
  - Then all instances of the old Medallia code should be removed, and the repo should be updated with only relevant Medallia v2 code
- [x] **Scenario: Determine what Medallia code is no longer in use**
  - Given the new Medallia v2 update
  - When the developer reviews the codebase to identify unused Medallia code
  - Then a list of all unused Medallia code should be created and provided as input for the GraphQL mutation
- [x] **Scenario: Remove unused Medallia code**
  - Given the new Medallia v2 update
  - When the developer removes the identified unused Medallia code from the repo
  - Then all instances of the old Medallia code should be removed, and the repo should be updated with only relevant Medallia v2 code
  
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
I'm combining this with ticket [#84253](https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/84253)

**Comment by aubreyarcangel** [comment]
I want to call out this file `/src/platform/site-wide/medallia-feedback-button.js`

I am pretty sure it's some workaround javascript from before the Medallia button was moved to the bottom of `<main>` content. Before removing it, I want to confirm with the VSignals team once they get stood up in a few weeks.
