### ISSUE TITLE
[Design] Replace sketch links on My VA use cases with figma links

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#84268]
## Background
Follow up from [76328](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76328): As a designer, I want to ensure that our Github documentation includes up to date links to imported Figma files instead of Sketch ones so that stakeholders can still reference the associated visuals after Sketch usage is fully sunset. We missed a few links in the initial round of updates so this ticket is to update the last few:

|My VA section | Use case (location of links)| Links that needs updating|
|---|---|---|
| Benefit payments | [User has received a payment from VA in the last 60 days via direct deposit or paper check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases/has-recent-payments.md) | [Desktop mockup of direct deposit payment](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/222D00A6-3BFD-4D99-9FCB-A9CE2766E78A) & [Mobile mockup of direct deposit payment](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/1CA9530C-0A0F-4CF6-9597-D76F83143B45)| 
| Benefit payments | [User has received a payment from VA in the last 60 days via direct deposit or paper check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases/has-recent-payments.md) |[Desktop mockup of mailed paper check payment](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/1FEFF140-7526-42A2-9D64-959E152ED415) & [Mobile mockup of mailed paper check payment](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/38CB47EF-6A94-44CD-B0F8-F6FE999C933D)|
| Benefit payments | [No payments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases/no-recent-payments.md) | No payments in the last 60 days - [Desktop mockup for no recent payments but has received payments before](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/977354F4-360B-4287-B9CD-CE28DC8444A0) & [Mobile mockup for no recent payments but has received payments before](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/95A46294-248D-407C-8557-8C6A35C02315) |
| Benefit payments |  [No payments](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases/no-recent-payments.md) | No payments ever - [Desktop mockup for no payments ever](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/B0DF2025-E29C-48D0-8230-6BC8D2FAA5EA) & [Mobile mockup for no payments ever](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/FE8BFAEA-9A71-4AB6-A35F-9BE18A63B3CF)|
| Benefit payments | [The payments API is down and we can't display any payment information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/benefit-payments-use-cases/payment-API-error.md) | [Desktop mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/268A4DAB-EB9D-49B5-AA3F-FEDBDB797E4A) & [Mobile mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/D56012A2-DBE1-49DD-A5D5-95D01ABB4DFA)|
| Outstanding Debts | [User has outstanding overpayment debts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/outstanding-debts-use-cases/overpayment-debts.md) | [Desktop mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/E5951AEA-0F34-4DE1-9C1F-EFD06B89483B) & [Mobile mockup](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/FE1C40BC-5688-46E8-8E23-982C2BC71CE3)|

## Tasks
- [x] Replace links with equivalent from Figma
- [x] Document any issues that emerge so there is a record

## Acceptance Criteria
- [x] All Sketch links in My VA use cases are replaced with Figma ones (barring any specific issues, which will be documented)

## Validation
- Can be validated by Design team members or Product

**Comment by mattmarino-adhoc** [comment]
@ajakabcin Please take a look, ready to close

**Comment by ajakabcin** [comment]
Looks great thank you!
