### ISSUE TITLE
Update Sign In Error Message Documentation

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#84262]
## Issue Description

After completing the sign in error message audit, we will update Veteran Support documentation to ensure we have the correct information for handling sign in error messages and are pointing people to the correct resources for understanding sign in error messages. 

---
## Tasks
- [ ] Update Veteran Support Documentation with new details and information

## Acceptance Criteria
- [ ] Updated Veteran Support Documentation
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
@chante has identified multiple sign in errors.

**Comment by ATMiddleton** [comment]
@ATMiddleton, @starlow00 and @Kimberley2023-CSM will review during 1:1 9/19/24 - @clantosswett is optional
