### ISSUE TITLE
Choose Your Own Adventure Training Modules 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#84266]
## Issue Description
Drafting target modules for Case Handling. 
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Changed the previous name of the ticket to avoid potential trademark issues.

**Comment by starlow00** [comment]
Prototypes complete/attached. Will use this model for many other self-directed modules for targeted Salesforce and Ask VA case types (of which there are many).
https://docs.google.com/presentation/d/1872M1OgU__XfiBX3COoClFrMkfOkLmvrv0n8Uuo-AuM/edit?usp=sharing
https://docs.google.com/presentation/d/1872M1OgU__XfiBX3COoClFrMkfOkLmvrv0n8Uuo-AuM/edit?usp=sharing
