### ISSUE TITLE
Publish Veteran Support Newsletter 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#84267]
## Issue Description
_Publication of Veteran Support 1st Newsletter 
---
## Tasks
- [x] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Awaiting Chante's go-ahead for publication.
Have discussed Medallia survey material for the next edition (will document in a separate ticket, next sprint).

**Comment by starlow00** [comment]
Followed up with @clantosswett for sign-off.

**Comment by ATMiddleton** [comment]
Must establish a distribution list. 
@chante will add to the distro list.

**Comment by Kimberley2023-CSM** [comment]
VEO, ID.me, Login.gov, MHV, NCC, HRC, EVSS

**Comment by clantosswett** [comment]
Reviewed the newsletter with a few small edits but I think it set and good to go. I'll write up a list of names and send over email + the introductory message in the email we will send to those folks. Let's plan to send this first thing on Monday 6/17!

**Comment by clantosswett** [comment]
Hi all, 

See below for the suggested introductory email for the partner newsletter as well as a list of names to send this to. @starlow00 please take a look for any edits or updates. 

For this initial newsletter, I'd like to just include internal VA stakeholders but for the next one we will be sure to include login, id.me and MHV/DS Logon partners as well. 
------------------------------
Hello all,

Attached is the first ever Veteran Support Team newsletter! Veteran Support is part of the Office of the CTO and is responsible for the coordination of support and resolution of VA.gov technical issues. We have worked with many of you over the years and moving forward, our plan is to provide more communication and transparency on the work we are doing and regular updates on new features and tools on VA.gov. 

We hope this information will give you the knowledge and resources to prepare your own contact centers for questions that may come to them and establish the correct processes and documentation to ensure Veterans are helped accurately and efficiently.

Because this is a new initiative, we would love to hear your feedback on this newsletter and what would be helpful to see in future editions. Additionally, if you know of other individuals or teams that could benefit from this information, please respond to me and Steven Tarlow so we can include them on the distribution list.

As always, thank you for your partnership and collaboration in serving Veterans. We look forward to finding ways to improve this work together!

Best,
Chante
---------------------------------
Torres-Hill, Brenda, HRC Brenda.Torres-Hill@va.gov; 
Yount, Regina, VBAVACO Regina.Yount@va.gov; 
Unger, Todd A. Todd.Unger@va.gov; 
Brown, Marlee R. (VEO) Marlee.Brown@va.gov; 
jeremy.haas@va.gov; 
Dale.Beehler@va.gov; 
Mickey, John S. John.Mickey@VA.GOV

**Comment by starlow00** [comment]
Sign-off from Chante obtained, will prepare for distribution to the above parties on the morning of Monday, 6/17.
