### ISSUE TITLE
Analyzing the CXI Data for inclusion in DOMO

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#84261]
## Issue Description
Analyze the CSI data for inclusion in DOMO 
---
## Tasks
- [x] Gap analysis of CXI data for inclusion in DOMO
- [ ] Data field mapping 
- [ ] 

## Acceptance Criteria
 - [ ] **Scenario: Analyzing the CXI Data for inclusion in DOMO**
  - Given the CXI data is available
  - When a gap analysis of the data is performed for inclusion in DOMO
  - Then the acceptance criteria should be met, including data field mapping and configuration
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by newworld2616** [comment]
I will be reviewing the AVA fields with Steven Tarlow. We have identified AVA fields; we need to validate it with the CXI team.

**Comment by ATMiddleton** [comment]
6/10/24 - Veteran Support team met with Christopher Clemes to review and confirm data mapping fields.

**Comment by newworld2616** [comment]
Analyses complete.
