### ISSUE TITLE
ARM: Update "About VA Form" pages

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#84285]
## Description
We need to add the link to the AAR online tool on these pages:
- [About VA Form 21-22](https://www.va.gov/find-forms/about-form-21-22/)
- [About VA Form 21-22a](https://www.va.gov/find-forms/about-form-21-22a/)

## Tasks
- [x] AP: Update pages in Drupal
- [x] AP: Share with MZ
- [x] MZ: Copyedit and publish
- [x] MZ: Alert public websites about these updates

## Criteria
- [x] Updated pages have been published

**Comment by aprocik1** [comment]
Reference [this task ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67034#issuecomment-2598916833) for the current status of this work.

**Comment by RLHecht** [comment]
These pages have been published. Closing ticket. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
closing because this ticket never closed
