### ISSUE TITLE
Analyze How Many OOB Deploys Are Redirects vs. Other Categories

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#84281]
## Description 
This ticket will house the task of analyzing the percentage of OOB deploys that are redirects vs. other categories. Initial OOB deploys analysis is here: https://docs.google.com/spreadsheets/d/19l2oLh2oMsbmuIgJwn6zoIk6z5OvAmER5TBYOQnb41I/edit?usp=sharing
---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify the best way to identify redirects vs. other categories
- [x] Visually represent the data so we can share with leadership 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
Based on data in given spreadsheet the PRs I could confirm were redirect requests were marked. 

You can find the spreadsheet and info [here](https://docs.google.com/spreadsheets/d/1jpRPpz_Sxd0WC-7BHJWVHWXtX9WIqOS9SZ3u3ULgJ5M/edit?gid=883256311#gid=883256311)

Image also attached

<img width="1296" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGltQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67689484fddffbbf2ed329dce07df856a8942941/Screenshot%202024-07-01%20at%2010.50.06%20PM.png" alt="Screenshot 2024-07-01 at 10.50.06 PM.png" />

**Comment by lindsay-insco** [comment]
Updated graphic!
