### ISSUE TITLE
[DISCOVERY] Editorial process: Situational updates and operating status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8430]
### User story 
As a content producer who is unfamiliar with Drupal, I want the process for adding situational update and facility operating status content to be user-friendly so that I am efficient. 

![image](https://user-images.githubusercontent.com/55411834/80257227-a8b85080-863d-11ea-80a2-ef6819a97a3e.png)

![image](https://user-images.githubusercontent.com/55411834/80257299-c71e4c00-863d-11ea-9f00-561fc6504cb0.png)

![image](https://user-images.githubusercontent.com/55411834/80258646-f8e4e200-8640-11ea-9307-33797dee1743.png)

## Goals
- Content producers understand the intended use for:
  - Banner
  - Situational update
  - Situational information
  - Facility operating status and notes

- Content producers can anticipate **how** their additions/edits will be rendered on the page
- Content producers can anticipate **where** the content additions/edits will be rendered on the page
- Content producers need to understand the display order for news releases
- Content producers need to understand how their new content is interrelated to other pages and content 

## Objectives or Key Results this is meant to further
- Decreased support requests to CMS 
---
## Tasks
Determine appropriate editorial experience for news releases, based on the following:
- [ ]  Value of each content block to Veterans (Banner, Situational update, Situational information, Facility operating status and notes)
- [ ] Value of each content block to the Business (Banner, Situational update, Situational information, Facility operating status and notes) 

## Acceptance Criteria
- [ ] Recommendations for changes to editorial experience for news releases

**Comment by davidmpickett** [comment]
Research in 2022 around COVID-19 status found that editors still are unclear on disntinctions between the use cases for these various tools
