### ISSUE TITLE
Toxic Exposure: Other locations and exposures validation freezes page

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#84311]
## Overview

Regular expression from [Lighthouse API docs](https://developer.va.gov/explore/api/benefits-claims/docs?version=current) is used on the `herbicide` and `additional-exposures` pages in an effort to prevent submission failures and allow Veterans to get error messaging guidance to update the input appropriately. However, in some cases, e.g. editing long strings 200+ chars freezes the page. 

Tested it out on regex tester and there seems to be 'catastophic backtracking'. This could cause performance issues on the front end and back end.

https://regex101.com/r/sGDaEQ/1
<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01sQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d2a4d1ddf4443cf5a86e277bfeb7ab9552e9ecd/image.png" alt="image.png" />
## Steps to reproduce
1. On the `/toxic-exposure/herbicide` page, enter a long string close to the max for 'Other locations not listed here'. 
Example
```Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam luctus nisi augue. Donec id luctus nisi. Nullam at lacus a erat mollis dictum in quis ipsum. Ut eget tincidunt nibh. Fusce posuere sit amet ex nec condimentum. Fusce tempor aliquet vel.```
2. Hit backspace twice and then try space bar

**Expected**
user is able to edit the string

**Actual**
browser/page freezes. hard refresh does not recover the page

## Tasks
- [x] Reach out to LH team to get updated, performant regex ✅
New regex is in [LH docs](https://developer.va.gov/explore/api/benefits-claims/docs?version=current) `pattern: ^([-a-zA-Z0-9'.,&# ])+$`
-  [x] Update regexes used on `herbicide` and `additional-exposures` pages
-  [x] Update regexes used on backend or update AC in appropriate ticket(s) #83945
-  [x] Updated error message content based on #81986
New error message is `You entered an invalid character in the text field. This field only allows letters, numbers, hyphens, apostrophes, periods, commas, ampersands (& symbol), number signs (# symbol), and spaces.`
-  [x] Update unit tests to verify new error handling and error message display

## Acceptance Criteria 
- [ ] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by michael-wojcik** [comment]
This updated regex should perform as expected: `^[-a-zA-Z0-9'.,&#]+( [-a-zA-Z0-9'.,&#]+)*$`

This new regex will make sure there are no leading or trailing spaces, and no double spaces within the string.

See this example: https://regex101.com/r/AJkzty/1

**Comment by alatempa24** [comment]
[Thread started with Lighthouse in DSVA Slack](https://dsva.slack.com/archives/C02CQP3RFFX/p1717173416237919)

**Comment by michael-wojcik** [comment]
The original problematic regex was introduced 3 years ago in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15490/files#diff-e2d97cb8a106bc1c3b39ebfb9fdd7c47da925809cc7e8d439526ad151824848eR29-R38

Note: This same issue will affect the regex listed there for `city: ` as well, so a similar fix should be added for that regex as well. I've created a Draft PR to address both the new issue in `src/applications/disability-benefits/all-claims/pages/toxicExposure/herbicideLocations.js` as well as the old, original regex code in `src/applications/financial-status-report/constants/index.js`: https://github.com/department-of-veterans-affairs/vets-website/pull/30108

**Comment by christinec-fftc** [comment]
Got updated regex from LH team today (updated in docs). Removed 'blocked' label

**Comment by alatempa24** [comment]
Added dependency of #81986 content for error included in the scope of this ticket.
