### ISSUE TITLE
Adjust Preview Environments to Use Preexisting Database Cluster

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#84321]
This will be a slight variation the production deployment pattern of Vets API (we will want to have production match this pattern in the future), but for build speed purposes we can utilize a 'pre-built' RDS Postgres cluster (serverless) for new preview environment instances - greatly reducing the build time needed for preview instances.

## Tasks
- [x] Move the serverless RDS cluster terraform to a separate terraform state and GitHub workflow to manage the preview environment Postgres clusters (i.e. a workflow that will create/update multiple Postgres clusters (or varied versions) that can be selected in the future based on the desired versions)
- [x] Adjust the terraform for when new preview environments are created such that a database is created for the specific instance of Vets API, on the appropriate cluster based on the version

## Acceptance Criteria
- [x] Github pipeline successfully builds RDS clusters
- [x] Preview Environment's builds create a database in the pre-existing Preview Environment RDS cluster

**Comment by patrick-black-oddball** [comment]
All requirements for the ticket are complete - but the branch has not been merged because vets-api database load is not successfully loading with the child database.
