### ISSUE TITLE
Initial discovery to understand the problem space for building a low code form builder 

### ISSUE THREAD

**Issue by Jones-Morgan** [department-of-veterans-affairs/va.gov-team#84323]
In order to build a low-code tool, we need to build a shared knowledge and identify gaps in our knowledge to identify a list of requirements for the form engine. 

(add another Epic that includes defining a list of requirements and prioritizing for MVP)

Using previous research done by the Forms team, I will gather a list of requirements for the Form Builder/Engine: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1648470464897/82c3c59c0470a28c54feeea05f3026e86be01594?sender=ubc553bc5b8296f2753108499
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86086
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86087
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85704
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85705
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/84701
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85693
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/86122
```
