### ISSUE TITLE
Find alternative to trilom/file-changes-action for pull request workflow in vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#84320]
## Issue Description
The action trilom/file-changes-action is used to get a list of changed files and some information about them in [the pull request workflow in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/pull-request.yml). This is one of the actions that needed to be upgraded from node v12 in https://github.com/department-of-veterans-affairs/va.gov-team/issues/74668. Unfortunately, this action has not been updated since 2020 and there is no update that fixes this. We can take one of two approaches here:

1) find an alternative action that does the same functionality, rework args/output as necessary. (likely quicker).
2) write our own check for files changed to get all relevant information that doesn't require an action (likely future-proof).

---
## Tasks
- [x] Decide which method makes more sense to implement based on the complexity of what is taking place.
- [x] Implement the selected method to update this functionality and drop the outdated action.
- [x] Test the workflow to ensure all still works as expected.

## Acceptance Criteria
- [x] The pull request workflow in vets-website no longer gives node v12 warnings.
- [x] The trilom/files-changes-action is no longer relied upon
