### ISSUE TITLE
Form Submission Updates/Polling

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#84332]
## Value Statement

**_As a_** Veteran

**_I want to_** be confident that my submission is monitored

**_So that_** any issues with their submission will be addressed in a timely manner

---

## Background Context

- Currently, once the NOD/CS/HLR form is submitted, it is passed downstream. If something happens to the submission downstream, we rely on a daily email or logs to notify that there was an issue. This can cause items to be missed.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Create a process which monitors submissions (from the table created in #84329) and updates the status based on the downstream responses
- Once the status is considered a success, set a 59 day timestamp to schedule for deletion/long term storage

## Acceptance Criteria

- [ ] A process/job polls downstream services for the status of submitted forms
- [ ] The process updates the form records with any changes
- [ ] In Process/Success/Failure statuses are defined
- [ ] Once complete, if a success, set the `delete_date` timestamp to be 59 days from now

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- The creation of the submission table, handled via #84329
- The deletion/long term storage of the submission, handled via #84348 

## Open questions

- What defines a success/failure? It should be in the [LH Developer docs](https://developer.va.gov/explore/api/decision-reviews/docs?version=current)
   - Convert them to the integer status, create a Enum, add documentation
- How often do we poll and how? Cron, once an hour

## Tasks

- [ ] Design a job that runs periodically, checking the status of any in progress submission
- [ ] Update any submissions who's status has changed
- [ ] Determine if the submission was a success and mark it for future deletion/storage

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
PR ready for review: https://github.com/department-of-veterans-affairs/vets-api/pull/17752

**Comment by eileen-coforma** [comment]
Still in code review.

**Comment by anniebtran** [comment]
More validation, once it's good, we'll enable in prod

**Comment by dfong-adh** [comment]
There were errors in staging due to JSON schema validation failures. Creating a PR to address the incorrect schema in vets-json-schema and another PR to update vets-api to use the new schema.

**Comment by dfong-adh** [comment]
PR to update vets-json-schema https://github.com/department-of-veterans-affairs/vets-json-schema/pull/924 merged

**Comment by dfong-adh** [comment]
PR to update vets-api for schema changes in review https://github.com/department-of-veterans-affairs/vets-api/pull/17880

**Comment by dfong-adh** [comment]
PR merged and being validated in staging

**Comment by dfong-adh** [comment]
No issues observed in staging.

**Comment by anniebtran** [comment]
Will enable in prod today

**Comment by dfong-adh** [comment]
Some job errors seen in prod - flags disabled until better error handling is added

**Comment by dfong-adh** [comment]
PR to address job errors: https://github.com/department-of-veterans-affairs/vets-api/pull/18053

**Comment by dfong-adh** [comment]
#18053 merged

**Comment by dfong-adh** [comment]
Flag reenabled in production
