### ISSUE TITLE
Binstubs Readme

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#84340]
## Summary

The [Binstubs README](https://github.com/department-of-veterans-affairs/vets-api/blob/sjc-running-binstubs/docs/setup/binstubs.md) need an "Introduction" & "How-To" guide for new users to binstubs.

## Tasks

- [ ] Update README for how to use binstubs
    - [ ] Include a section for troubleshooting for setup
    
## Acceptance Criteria

- [ ] Binstubs documentation is more complete.
- [ ] The readme includes a section on how to use the binstubs to resolve common problems.
