### ISSUE TITLE
[FE] - switch to new minimal header

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#84342]
## Description

The new minimal header is now ready to use. 

https://dsva.slack.com/archives/C5HP4GN3F/p1717100222282099

Update all three of our apps to use it in content-build registry

## Tasks
- [x] [FE] update day-of
- [ ] [FE] update pre-check-in
- [x] [FE] update travel
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
This is merged and ready to validate during the next prod deploy. So maybe save validation for Monday @zach-park and @cgednalske
