### ISSUE TITLE
EADR - vets-api & Datadog log updates

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#84351]
# Issue Description
In order to deliver the appropriate external data metrics to VA leadership, the following changes to `vets-api` Rails log & Datadog metrics should be made. Datadog widgets and boards should also be updated.

- The affected logs & metrics should all be updated to ensure they include `client_id` and `type` attributes.
- The `sign_in` object that is generated in both SSOe & SiS should be updated to include `client_id`
- SSOe logs & `sign_in` object should be updated to use SiS terminology: `client_id` over `application`, `type` over `credential_used` || `service_name`
- EADR widgets in Datadog should all be filtered to only vets-website & VA mobile clients

### "Active Users" - success only
  - SSOe log:
    - `LOGIN_STATUS_SUCCESS` - has `context` (type), `client_id` will be populated by `sign_in` object change, `icn` to be added
  - SiS log: 
    - `[V0::SignInController] callback` - success only, includes `type`, `client_id`, `icn`
    - `[V0::SignInController] refresh` - covers SiS mobile users that haven't re-authenticated, includes `client_id`, `type` & `icn` to be added
### "Total Authentications" - success only
  - SSOE metric:
    - `auth_login_success` StatsD metric - includes `context` (type), `client_id` will be populated by `sign_in` object change
  - SiS metric:
    - `api_sis_callback_success` StatsD metric - includes `type`, `client_id`
### "Credential Usage - Total Authentications" - success only
  - SSOE metric:
    - `auth_login_success` StatsD metric - includes `context` (type), `client_id` will be populated by `sign_in` object change
  - SiS metric:
    - `api_sis_callback_success` StatsD metric - includes `type`, `client_id`,

# Tasks
### SiS
- [x] Include `type`, `icn` in `/refresh` log payload

### SSOe
- [x] Update SAMLTracker to use `vaweb` instead of a null value for its default `application` (client_id) value
- [x] include `client_id` in UserIdentity `sign_in` object
- [x] include `icn` in `LOGIN_STATUS_SUCCESS` log
- [x] update `auth_login_success` Datadog log tag `context` to standard CSP `type`

### Datadog
- [x] Update widgets to match Datadog query definitions above

#### Documentation
- [x] update [query documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/External%20Auth%20Data%20Reporting/Working_docs/Queries_for_data.md) to reflect the update queries & log/metric generation locations in `vets-api`.

**Comment by bramleyjl** [comment]
`api_auth_new` has been updated with [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17298) and the `type` tag is now showing up on it in staging.

**Comment by bramleyjl** [comment]
## Updates to StatsD Metrics
  - 'api_auth_login_success'
  	- context => type
  - 'api_auth_login_failure'
  	- context => type
  - 'api_auth_latency'
  	- context => type
  - 'api_auth_new'
  	- context => type
  - 'api_auth_saml_request'
  	- context normalized to string from 'authn' array
  	- client_id
  - 'api_auth_saml_response'
  	- client_id
  - 'api_auth_saml_callback'
  	- type
  	- client_id

**Comment by bramleyjl** [comment]
Query documentation has been updated.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/External%20Auth%20Data%20Reporting/Working_docs/Queries_for_data.md
