### ISSUE TITLE
Create QR Code for Debt Portal

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#84364]
## Issue Description
Using this open source tool (https://pypi.org/project/qrcode/) establish a QR Code for the debt portal that points to   https://www.va.gov/manage-va-debt/

---
## Tasks
- [x] Generate QR Code
- [x] Tag @denisecoveyduc once complete

## Acceptance Criteria
- [ ]QR code has been created and is ready to use. 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by digitaldrk** [comment]
<img width="370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW92QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea4ce7f60eeb48a50775c26d9eb06b63391b1589/manage_va_debt_qr_code.png" alt="manage_va_debt_qr_code.png" />

**Comment by digitaldrk** [comment]
@denisecoveyduc ☝🏻

I ended up using the Python library that was spec'd to be on the safe side.

**Comment by denisecoveyduc** [comment]
This is SO exciting! Thank you @digitaldrk  I was able to pull the file just fine. Will send it over to VHA and if they have any questions as they work to integrate it into the paper statements I will let you know.  WOO HOO!!!

**Comment by digitaldrk** [comment]
Ah, that's great! Yes, do let me know if I can provide info.
