### ISSUE TITLE
[CST] [ENG] Updates for description text in the claim phase stepper and where we're doing section (steps 2 and 7)

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#84366]
## Background Context
While working the claim phase experience tickets we have come across some changes that we need to make to our initial design. 

### Bug
1. We need to update the content description on the Overview Page for step 2 to no longer show the text `If basic information is missing, we’ll contact you to gather that information.` and to instead show `If information is missing, we’ll contact you.`
2. We need to update the description on the Overview Page for step 7 to no longer have the text `If we need more evidence or you submit more evidence, your claim will go back to Step 3: Evidence gathering.`
3. We need to update the description on the Status Page for step 7 to no longer have the text `If we need more evidence or you submit more evidence, your claim will go back to Step 3: Evidence gathering.`

## Design

<img width="1643" alt="Screenshot 2024-05-31 at 2 01 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/3cdb4933-6bdf-449c-9e44-196ff7f8c08b">

[Content doc](https://docs.google.com/document/d/1WfWCfoQgKoMBg835VP7j_ptXmqb2o3RVme2u5dMOEr8/edit?usp=sharing)

## Tasks

- [ ]  We need to update the description on Overview Page for step 2 to no longer that the text `If basic information is missing, we’ll contact you to gather that information.` and to instead show `If information is missing, we’ll contact you.`
- [ ] We need to update the description on Overview Page for step 7 to no longer have the text `If we need more evidence or you submit more evidence, your claim will go back to Step 3: Evidence gathering.`
- [ ] We need to update the description on the Status Page for step 7 to no longer have the text `If we need more evidence or you submit more evidence, your claim will go back to Step 3: Evidence gathering.`

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ]  The description for step 2 on the Overview Page no longer shows the text `If basic information is missing, we’ll contact you to gather that information.` and to instead show `If information is missing, we’ll contact you.`
- [ ] The description for step 7 on the Overview Page no longer shows the text `If we need more evidence or you submit more evidence, your claim will go back to Step 3: Evidence gathering.`
- [ ] The description on the Status Page for step 7 no longer shows the text `If we need more evidence or you submit more evidence, your claim will go back to Step 3: Evidence gathering.`

**Comment by pmclaren19** [comment]
Merged to staging! @uxgary @jacobworrell please validate.

**Comment by pmclaren19** [comment]
@uxgary validated!
@jacobworrell please validate.
 FYI staging doesnt have test data where there is a claim in every step so you can validate the overview tab for step 2 and 7 but the status tab can only be validated by referring to the screen shots from my [pr](https://github.com/department-of-veterans-affairs/vets-website/pull/30123) for this work
