### ISSUE TITLE
Toxic Exposure - Form 21-526EZ PDF as a supporting document - polling for status job implementation

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#84389]
## Story
As a steward of the Form 21-526EZ workflow, I would like to know the status of the Form 526 PDF submission to the eFolder when going through the primary path.

## Goal:
We need a method to inform the vets-api system of the status of the Form 526 PDF as a supporting document of the established claim.

Link to notes and proposed options for implementation: https://dsva.slack.com/archives/C04KW0B46N5/p1717516393733889?thread_ts=1717516384.179439&cid=C04KW0B46N5

**Summary:**
1. The job feasibly exists as a manual command that kicks off polling (not called automatically to start)
- Including a playbook for running and comments in the job itself
- Include a remediation plan
- Should be the first step anyways to test
2. Implement metrics 
Can be done concurrently with 1, 2, or 3

## Context:
With the migration to the Lighthouse synchronous submit endpoint, Lighthouse returns the response after a claim is established and returns a claim id from VBMS representing the established claim.
However, this does not ensure that the Form 526 PDF that was generated in the process got submitted along with the claim being established.
If we were to utilize the Lighthouse synchronous submit endpoint, we would not know if the generated Form 526 PDF made it into the eFolder for the Veteran in VBMS.

## Tasks
- TBD

## Acceptance Criteria
- [ ] Updated plan with stakeholders
- [ ] Async polling solution implemented for release 1.0 
- [ ] Remediation plan in place

## Out of scope
- [ ] automating polling job (follow on story)
- [ ] optimizing polling times (nice to have - can be post-MVP)

**Comment by mchae-nava** [comment]
Link to notes and proposed options for implementation: https://dsva.slack.com/archives/C04KW0B46N5/p1717516393733889?thread_ts=1717516384.179439&cid=C04KW0B46N5

**Comment by aurora-a-k-a-lightning** [comment]
# notes:

- response from lighthouse benefits_claims#get_claim(<claim id>) endpoint
-- supportingDocuments has the documentTypeLabel "VA 21-526 Veterans Application for Compensation or Pension"
```
{"data"=>
  {"id"=>"600513460",
   "type"=>"claim",
   "attributes"=>
    {"claimTypeCode"=>"020SUPP",
     "claimDate"=>"2024-06-07",
     "claimPhaseDates"=>{"phaseChangeDate"=>"2024-06-07", "currentPhaseBack"=>false, "latestPhaseType"=>"UNDER_REVIEW", "previousPhases"=>{"phase1CompleteDate"=>"2024-06-07"}},
     "claimType"=>"Compensation",
     "closeDate"=>nil,
     "contentions"=>[{"name"=>"Bowel (Increase)"}, {"name"=>"asthma (New)"}],
     "decisionLetterSent"=>false,
     "developmentLetterSent"=>false,
     "documentsNeeded"=>false,
     "endProductCode"=>"020",
     "evidenceWaiverSubmitted5103"=>false,
     "errors"=>[],
     "jurisdiction"=>"National Work Queue",
     "lighthouseId"=>nil,
     "maxEstClaimDate"=>"2024-12-11",
     "minEstClaimDate"=>"2024-09-23",
     "status"=>"INITIAL_REVIEW",
     "submitterApplicationCode"=>"VBMS",
     "submitterRoleCode"=>"VBA",
     "supportingDocuments"=>
      [{"documentId"=>"{9cd66b81-6695-4d47-ab09-b60c06de2ea6}",
        "documentTypeLabel"=>"VA 21-526 Veterans Application for Compensation or Pension",
        "originalFileName"=>"Janet_Moore_600513460_526EZ.pdf",
        "trackedItemId"=>nil,
        "uploadDate"=>"2024-06-07"}],
     "tempJurisdiction"=>"Wichita",
     "trackedItems"=>[]}}}

```

**Comment by sethdarragile6** [comment]
PR merged to main and deployed to staging, where it is currently being tested. Because there are a plethora of submission that have either a) failed with a non-retryable error (rows 3-5) or b) are so old that their claims have already been cleared out (rows 1-2), this makes it easy to test for the exhaustion scenario- with the catch that we still have to wait 48 hours before we see the job status set to 'pdf_not_found'.

<img width="1198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3F4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba4afafa81830b44e124730129a350306a51a5b7/Screenshot%202024-07-03%20152213.png" alt="Screenshot 2024-07-03 152213.png" />

The below job status record was the result of running the job for a more recent and successful submission

<img width="538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0N5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91adbfb4a2b4d13f6dc1d63b9d51c3d7269a7c2e/Screenshot%202024-07-03%20150623.png" alt="Screenshot 2024-07-03 150623.png" />

Come Friday afternoon, we should know whether or not the exhaustion scenario was successful or not!

**Comment by sethdarragile6** [comment]
Successful stage test of the 48.hour limit being reached

<img width="857" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkc2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--055a1db6ae928d5f61232dcac5b56a3f3a8f6f8e/image.png" alt="image.png" />

**Comment by alatempa24** [comment]
How will we get this into the upload? We need to reach out to Carbs for manual uploading of the file.
