### ISSUE TITLE
Heuristic evaluation of debt portal (July, August, September)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#84385]
## Issue Description
Perform a full heuristic evaluation of the debt portal to help inform areas of strength/weakness/improvement

---
## Tasks
- [ ] Plan for an internal evaluation
- [ ] Plan for focus groups
- [ ] Perform focus group studies
- [ ] Refine the findings into areas and levels of that could become projects
- [ ] Report out findings

## Acceptance Criteria
- [x] All the research is complete
- [x] All the research is compiled/documented
- [x] All the research is presented
- [x] All the research is recorded where both the VA and team can access
---

**Comment by Tom-Davis** [comment]
Closing as work for the quarter is complete.
