### ISSUE TITLE
Monkeypatch Faraday::Response::RaiseError to change default behavior

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#84394]
## Issue Description
As determined in #84176, The best solution to the new Faraday Behavior described in [this issue](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1658) is to monkeypatch the `Faraday::Response::RaiseError#initialize` method to change the default value of the `include_request` option to `false`

---
## Tasks
- [x] ~~Monkeypatch Faraday gem~~ Determine solution for our problem via feature PR to `faraday`
- [x] Test thoroughly
- [ ] ~~A TODO item is added to remove the patch in the case that our requested default behavior is implemented by Faraday maintainers.~~ (added TODO to follow up ticket)

## Acceptance Criteria
- [ ] ~~Patch has been applied to Production~~
- [x] Follow up tickets created

**Comment by ryan-mcneil** [comment]
As I began working on a patch, we decided it would make more sense to approach it as a feature to the Faraday Gem. I have a working solution locally, but need to do a couple of things that will carry over into the next sprint:

* [Apply Faraday feature PR as Monkeypatch](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/85133)
* [Create PR to Faraday for monkeypatch in Vets API](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/85135)
