### ISSUE TITLE
[FE] - Remove old feature flags

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#84396]
## Summary
`check_in_experience_pre_check_in_action_link_top_placement`
`check_in_experience_travel_logic` Already removed in vets-website, but needs to be removed from vets-api
## Tasks
- [ ] remove `check_in_experience_pre_check_in_action_link_top_placement` in vets-website
- [ ] remove `check_in_experience_pre_check_in_action_link_top_placement` in vets-api
- [ ] remove `check_in_experience_travel_logic` in vets-api
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
no further validation needed, closing
