### ISSUE TITLE
Change name of vets-api RaiseError class for clarity

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#84397]
## Issue Description
As discovered in #84176, we have a Faraday middleware named `RaiseError` that essentially adds a prefix to exceptions/error messages raised from failed Faraday requests.

The problem is that Faraday also implements a `RaiseError` middleware that has different functionality. Both are registered under the symbol `:raise_error`, and because the one in our code takes precedence, the standard Faraday method is overridden. There is at least one case (not counting myself or Eric) where a developer has mistaken this `raise_error` middleware with the standard one, as they attempted to pass an option that had zero effect. There are some other issues here that will be addressed in other tickets, but the simple task here is to just rename this class for clarity.

---
## Tasks
- [x] Rename Vets API `RaiseError` class
- [x] Examine all 30+ cases to confirm no side effects (perhaps the default was given precedence in some other way?)

## Acceptance Criteria
- [x] Error name change is deployed to production
