### ISSUE TITLE
Create spreadsheets of rate tables to become new format/process for entering/updating tables in Drupal

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#8440]
duplicates epic #9385 so closing this. 

## Problem Statement

Original:
Problem description. How might we create an easier template for stakeholders to use every year when their rates update, that can be a CSV file, and then be uploaded directly into Drupal, reducing potential for manual errors and speeding the retirement of TeamSite pages?

**Update:** CSV files are too cumbersome to send to stakeholders. New proposed solution is a spreadsheet with tabs for each table, in order of appearance on the page. Stakeholders to fill these out when rates change. When we get them back, we will break up the tabs into individual CSV files, and then upload into Drupal. Anne

## Goal
_New template/process for VA stakeholders to fill out each year, that can be handed off to Public Websites and be uploaded into Drupal in the correct formatting_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ x] _Anne created draft of sample Disability Rates spreadsheet, with tabs that align to each table on the page. _
- [ x] _Beth, Danielle, Randi review during Content meeting._ 
- [ ] _Anne to update visual presentation of each tab to be more readable._ 
- [ ] _Anne and Danielle to meet to decide meeting/presenting to stakeholders, when and how._
- [ ] _Evangelize with all VBA stakeholders who oversee rates tables, as well as CMS team

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

Related tickets:
Disability rates tables: 
DIC rates tables: #9676

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA @beeyayjay @stephorkandatx @RLHecht  FYSA
NOTE: ZenHub won't allow me to upload the Excel-CSV file. Will reach out to Nick/Kelson to find workaround.

**Comment by AnneHurley** [comment]
Per @beeyayjay - see attached Zip file with each of the individual rates tables from the main disability compensation page, https://www.va.gov/disability/compensation-rates/veteran-rates/

Each is a ,CSV file, which can be tweaked to be even more user-friendly in its appearance when sent to stakeholders to update. 

@beeyayjay considering ways to retain formatting (bold, etc.) in files; otherwise we will do after files are back and uploaded into Drupal. 

@stephorkandatx  and @jenniferlee-dsva  FYSA and for you to review to see if this is looking like you want it to. [Zip file of main Disability rates tables]
(https://app.zenhub.com/files/133843125/acd223e2-3184-4f42-a02c-9f7359267e2a/download)

**Comment by AnneHurley** [comment]
@beeyayjay and I met with @swirtSJW - Steve is taking the question to the CMS team to discuss what would be best practice for stakeholders making some updates vs. our team owning them. 
@stephorkandatx  and @jenniferlee-dsva  and @DanielleThierryUSDSVA FYSA

**Comment by AnneHurley** [comment]
Sample of one file folder of individual rates that go on a single web page. Each spreadsheet = one table on the page. 

Included with each page's 'bundle" is a key to what the charts are and what the names of the spreadsheets are. 

Stakeholders would fill out each spreadsheet and send them back as a bundle, and then we would convert each spreadsheet to a CSV file and upload to Drupal. 

[Zip file of disability rates tables for stakeholder plus key](https://app.zenhub.com/files/133843125/993e1927-0191-49ac-8f4e-fb1ad872349d/download)
@jenniferlee-dsva @beeyayjay @DanielleThierryUSDSVA @stephorkandatx @lwalsh617  FYSA and for content meeting 5/18 demo

**Comment by AnneHurley** [comment]
Anne and @DanielleThierryUSDSVA  to meet with Sandy Tadeo for presentation on 5/28
