### ISSUE TITLE
Governance offboarding for Rebecca Ferguson

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84446]
## User Story
As the Governance team Product Manager, I want to make sure I identify all important tasks for offboarding Rebecca so that I am able to find proper coverage and ensure no responsibilities are dropped.

Assignee: @rferguson13 
Peer Reviewer: @shiragoodman 

## Description
Rebecca's last day is June 14. The purpose of this ticket is to identify all documents, processes, distribution lists, etc. where she must be removed.

## Tasks
- [ ] Identify places where Rebecca's name needs to be removed from internal documentation & platform website (replace with TBD where applicable) -
   - [x] [Contact Us page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1764524036/Contact+us)
   - [x] [Orientation slide decks](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)
   - [x] [Design Intent slide for beginning of meeting](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23db8d1d252_0_248)
   - [x] [Governance team homepage on Confluence](https://vfs.atlassian.net/wiki/spaces/PPST/overview)
   - [x] [DraftingTemplate](https://docs.google.com/spreadsheets/d/1zabutKbKQnZMb3A2hxs-OaB7q6j8DWw1xcFaCfFDIVw/edit#gid=654390984)
   - [x] [On Support document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2454093924/On-Support+guide)
   - [x] Design Intent distribution list
   - [x] Midpoint Review distribution list
   - [x] Staging Review distribution list
   - [x] Collaboration Cycle Calendar
   - [x] Governance team distribution list (for auto-forwarding Zoom recordings)
   - [x] @platform-governance-team-members Slack group

- [ ] ~~Complete platform offboarding ticket~~
   - Andrea will take care of this
- [ ] Uninvite Rebecca from:
   - [x] Governance standup
   - [x] Planning
   - [x] Retro
   - [x] Refinement
   - [x] Weekly Initiative Meeting
   - [ ] Collab Cycle timeblocks - N/A
   - [x] CC office hours
   - [ ] anything else?
  
## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have offboarded Rebecca from her responsibilities and tasks for Governance team

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@shiragoodman - Two quick questions/notes:

- We don't have orientation slide decks anymore. So I'm marking that as complete.
- Should I add Cheryl's name to the drafting template for now?

**Comment by shiragoodman** [comment]
@rferguson13 all good with you marking the slide decks complete. And yes, please add Cheryl's name to the DraftingTemplate. Thank you for thinking of that!
