### ISSUE TITLE
Investigate auto login loop for 526EZ

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#84476]
## Description
During one of the Sign in experience discovery research (see [IA and technical issues, section B](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2024-04%20FE%20Sign%20in%20Flows/Front%20end%20sign%20in%20flow%20-%20discovery%20research.md#2-ia-and-technical-issues) UX mentioned there was a sign in loop occuring for the Disability Compensation ([Form 21-526EZ](https://www.va.gov/disability/file-disability-claim-form-21-526ez/start))

- Verify with each auth broker (both SSOe and SiS)
- Verify with unverified (LOA1) and verified (LOA3) users
- Verify with a minimum of ID.me (other CSPs are optional)

## Tasks
- [ ] Investigate if a sign in loop for 526EZ application on VA.gov exists (check if there is an infinite loop)
- [ ] If there is a infinite loop, determine where it is occuring and fix it
- [ ] If there is NOT an infinite loop, feel free to update in UX discovery research document, section B to state that there was no auto looping sign in bug.

**Comment by acaruso-oddball** [comment]
When testing with Login.gov and ID.me test users on on staging said error was not present. 

When testing with DSLogon test user, I encountered the following. User encounters two MFAs. The first MFA is with DSLogOn and when completed received this message:  "Authentication complete. Don't forget to Log Off. You will need to close your browser and tabs when done to protect your PII." User is then redirected to an ID.me MFA page that displays as the third step of a sign in process with the heading "Complete your sign in". User then has to enter MFA code before returning to the initial page on staging.VA.gov this behavior may be what folks are alluding to.

**Comment by asg5704** [comment]
@acaruso-oddball you can close this whenever. Thanks

**Comment by asg5704** [comment]
@acaruso-oddball you can move this over to Ready for PM review or Closed column when you're ready

**Comment by asg5704** [comment]
@acaruso-oddball Can you please move this over to Ready for PM review or Closed column?
