### ISSUE TITLE
[CST] [DataDog RUM] Turn on RUM logging in production and monitor daily

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#84482]
## Issue Description
We need to enable RUM logging in production for CST and monitor it daily. We need to address any PII or rendering issues that come up. Team should start to gain insights from session replays.

---
## Tasks
- [x] Turn `cst_use_dd_rum` feature flag on in production
- [ ] Monitor DD RUM logs and session replays daily
- [ ] Share out session replays with the team (schedule a meeting) to gain insights
- [x] Fix any PII issues if they come up
- [ ] See if the session replay renders are loading properly (an early session replay video didn't have all the CSS loaded in the beginning of the video)

## Acceptance Criteria
- [x] `cst_use_dd_rum` is turned on in production
- [x] PII is confirmed NOT logged
- [ ] Session replay meeting has been scheduled with team
- [x] Session replay render issues have been investigated and improvements made if possible
---
## How to configure this issue
- [ ] https://vagov.ddog-gov.com/rum/sessions?query=%40application.id%3A75bb17aa-34f0-4366-b196-eb11eda75425%20%40type%3Asession&agg_m=count&agg_m_source=base&agg_t=count&cols=&fromUser=true&viz=stream&from_ts=1716838323989&to_ts=1717443123989&live=true

**Comment by samcoforma** [comment]
Just set it to 5% via `cst_use_dd_rum` feature toggle in production.
