### ISSUE TITLE
Add guidance about using the SR issue ticket as a working ticket to the FAQ page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84485]
## User Story
As a VFS PM, I want to know what is acceptable for me when it comes to taking action on a SR issue ticket so that I can direct my team appropriately. 

Assignee: @erinrwhite
Peer Reviewer: @allison0034

## Description
VFS PMs have asked Governance on several occasions if it's ok to use the Staging Review issue ticket as a ticket for the VFS team to work off of when resolving the identified issues. Yes, it is ok. However, we ask that VFS teams do not remove any of the labels added by Governance and do not remove the ticket from the associated milestone. It is also perfectly acceptable for the VFS team to create their own ticket and just link/reference the Staging Review issue ticket. Whatever is best for the team is fine with Governance.

We should be communicating this information to VFS teams in a couple different ways. 1. It should be included in the Next Steps for the VFS Team section of the Staging Review issue ticket. 2. It should be included as a frequently asked question on the Collab Cycle FAQ page. 3. Should it also be included in the Anatomy of a Staging Review issue ticket page on Platform Website?

The purpose of this ticket is to add the question to the FAQ page. The Next Steps for the VFS team (via ticket #84486) and potentially the Anatomy of a Staging Review issue ticket page will be updated in other tickets.

## Impacted Artifacts
[FAQs](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs)

## Tasks
- [x] Draft a question and a response based off of the information in the description.
- [x] Once peer reviewed, publish changes to Platform Website

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have added a frequently asked question providing guidance on using the SR issue ticket as a working ticket

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@allison0034 [First draft ready for your review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3216244781/84485+-+Erin+-+SR+ticket+process+for+VFS+teams)

**Comment by allison0034** [comment]
@erinrwhite looks good!

**Comment by erinrwhite** [comment]
Thank you @allison0034 this should publish out to Platform website this afternoon. I'll comment again once it's published for final review 👍🏻

**Comment by erinrwhite** [comment]
[Page published on platform website](https://vfs.atlassian.net/wiki/spaces/CC/pages/1864073263/FAQs#After-Staging-Review%2C-should-I-create-new-tickets-for-my-team-to-work-on-each-finding%2C-or-can-I-use-the-tickets-that-Governance-Team-created%3F) and ready for review @allison0034 !

**Comment by allison0034** [comment]
Looks good!

**Comment by erinrwhite** [comment]
thanks @allison0034 closing!
