### ISSUE TITLE
OH Hi-fi Prototype for research

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#84489]
## Task Description
Create a polished hi-fi prototype for Veterans to usability test in research sessions

## Notes and References
-

## Acceptance Criteria
- [x] OH scheduling paths are included
- [x] OH request path is included
- [x] PID alternatives are included
- [x] Emergency health care alerts
- [x] Recently visited question included
- [ ] Notification work?
- [x] Mobile
- [ ] Tablet
- [x] Desktop

## Deliverables
-

**Comment by outerpress** [comment]
@melissa-lefevre could you add links and close if this is done? (I think it is - you'll want to create a separate ticket for synthesis)
