### ISSUE TITLE
Make prt-github-workflows Available to Public Repos

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#84483]
## Issue Description
As work was started on #80300, it was quickly realized that Public repos could not access workflows from Private repos (explicitly called out in the table [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-to-reusable-workflows)). Something needs to be done (perhaps just adjusting the repo privacy from private to public) so that we can use these workflows as intended.

Useful link: [Prerequisites for requesting a public repository](https://department-of-veterans-affairs.github.io/github-handbook/public-repositories-at-the-va)

---
## Tasks
- [x] Fulfill req's to change prt-github-workflows privacy to public (link above)
- [x] Submit request to VA Admins to adjust privacy

## Acceptance Criteria
- [x] Public repos such as [gibct-data-service](https://github.com/department-of-veterans-affairs/gibct-data-service) can successfully run workflows as intended.

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/github-user-requests/issues/22447

**Comment by ben-allen-oddball** [comment]
Per @JoeTice 
Eunice García is the COR, she's out on military leave till next Monday... I'd suggest typing up a Confluence doc for justification that covers:
This is what we want to change and why
Share that w/ Clint, so he can help facilitate any convo or approval that's needed there
I haven't had direct interactions with her yet, but word on the street is she's very by-the-book, so will likely want some documented justification to refer back to.

**Comment by ben-allen-oddball** [comment]
Request to make the repository was denied.  We are moving the standardized actions to https://github.com/department-of-veterans-affairs/vsp-github-actions
