### ISSUE TITLE
Set up Github integration in Slack for CC-request label (ie Kickoff)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84493]
## User Story
As a Governance team member, I want to be notified of new Collab Cycle Kickoffs so that I can take the appropriate next steps.

Assignee: @it-harrison
Peer Reviewer: @briandeconinck

## Description
When Governance team first began using the Collaboration Cycle Request ticket (ie 1 ticket to rule them all), there was concern that we'd overlook when VFS teams submitted the ticket as part of Collab Cycle Kickoff. To remedy that, we set up a Slack/GitHub integration on the #platform-collaboration-cycle channel that notified us if/when a va.gov-team ticket was created with the `CC-Request` label. See [example. ](https://dsva.slack.com/archives/G01DXP10GCA/p1697555576206349)We have since retired the notification, but would like to bring it back on the #platform-governance-team channel to serve as the trigger for Governance team members to kickoff the Kickoff workflow.

**Note:** The purpose of this ticket is just to reestablish the notification in Slack. Governance will define actionable next steps in ticket #84494.

## Tasks
- [x] Create notification from GitHub in #platform-governance-team channel if/when a va.gov-team issue ticket is opened with both the `CC-Request` and `collaboration-cycle` labels
   - notification should ONLY be for when the new ticket with these labels is opened, not when the ticket is closed and/or modified.
- [x] Test that integration is working as expected

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team is notified by Github in Slack when a Collab Cycle Kickoff occurs

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison, moving this to in progress. Please provide an update on status by EOD. thank you!

**Comment by it-harrison** [comment]
@briandeconinck using `/github subscribe department-of-veterans-affairs/va.gov-team issues +label:CC-Request` notifications are sent to a channel when an issue with `CC-Request` is opened...but also when that issue is closed. I don't see a way to notify only on creation (without using a Github Action).  Do you know if it is possible?

**Comment by shiragoodman** [comment]
@it-harrison I _thought_ we had this set up formerly on the #platform-collaboration-cycle channel. Originally it was both issue-created and issue-closed actions, but I thought we changed it so it was only issue-open... but maybe not.

**Comment by it-harrison** [comment]
@shiragoodman from what I have read and tested (and what is indicated in our [docs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2294448280/Managing+GitHub-to-Slack+Notifications#Activity-included-with-issue-notifications)) it will always notify on issue close. But I could look into writing a Github Action to get around that limitation.

**Comment by shiragoodman** [comment]
Thanks @it-harrison . For now, let's just leave it. If it becomes a problem where the notifications are too frequent, then we can look into it.

**Comment by it-harrison** [comment]
@briandeconinck the notification has been re-established in #platform-governance-team

**Comment by shiragoodman** [comment]
This ticket is awaiting peer review and has moved into the next sprint.

@briandeconinck FYI

**Comment by briandeconinck** [comment]
Looks good, I think you can close this out @it-harrison!
