### ISSUE TITLE
Launch changes to Collab Cycle scheduling

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84496]
## User Story
As a VFS team member participating in the Collaboration Cycle, I want to be made aware of all changes to the process that may impact my experience.

Assignee: @it-harrison 
Peer Reviewer:  @erinrwhite 

## Description
Governance team is almost ready to launch our changes to our scheduling and kickoff workflows for Collaboration Cycle. This ticket will cover:

- publishing all of the VFS-facing guidance (per ticket #88162)
- publishing all operational guidance  
   - with the exception of the operational changes to the Collaboration Cycle Kickoff- Moderator Responsibilities (see ticket #88161 for more details)
- running the script to update open Collab Cycle Request tickets (per ticket #84495)
- writing change history post and change announcement
- archiving/deleting the old Slack workflows

Please coordinate with the assignee for ticket #88170 as change announcements, change history posts and the publishing of shared drafts pages should be aligned.

Note from refinement 7/25: There may be a potential delay in Governance response or after-hours response post Calendly scheduling, which means the message on the VFS team channel doesn't occur until then (aka not right away). Do we want to include this in our change announcement? 

## Tasks
- [ ] Draft change announcement following [Platform guidelines ](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2290352129/Slack+Change+Announcement+format)
- [ ] Draft [change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history) post for Platform Website
- [ ] Ensure Last Updated date on all PW pages is updated to current date
- [ ] Run script to update existing CC tickets with new workflow

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have published our changes to the Collaboration Cycle scheduling workflows
- [x] We have notified VFS teams of the change in process
- [x] We have deleted the old Slack workflows so that VFS teams can no longer use them
- [x] We have updated old Collab Cycle tickets with updated scheduling instructions

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison @erinrwhite I realized yesterday that I forgot to include archiving/deleting the old Slack workflows so that VFS teams can no longer use them. I believe we all, as editors, have the permissions to do this but tagging @briandeconinck just in case. I have updated the description and the acceptance criteria.

**Comment by allison0034** [comment]
@it-harrison draft of change history page can be found in [this folder](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3350429697/Copy+of+Change+history+2)

**Comment by shiragoodman** [comment]
I just recognized that our Calendly sign up questions will need to change. Since we're so close to launch, I am just going to remove the questions now. In Design Intent & Midpoint review Calendly event, I will be removing this checkbox:

- I understand that I must notify the Platform Governance team in my team's public Slack channel via the appropriate Slack slash command (/collab cycle) at least 2 business days in advance that I have scheduled this event.

In the Staging Review Calendly event, I will be removing this checkbox:

- I understand that I must notify the Platform Governance team in my team's public Slack channel via the appropriate Slack slash command (/collab cycle staging review) at least 4 business days in advance that I have scheduled this event.


Please let me know if you have any questions or concerns!

**Comment by it-harrison** [comment]
:mega: Attention: VFS teams

VFS Teams no longer need to make use of a Slack workflow to notify Platform Governance team of their intention to participate in a Collaboration Cycle touchpoint.

On 8/12/2024, Governance Team has modified its Collaboration Cycle scheduling process such that VFS teams only need to schedule their touchpoints in Calendly to notify the Governance Team. 

Impact:  VFS teams should be able to schedule their touchpoints more easily, with fewer steps.

Documentation:  Each Collaboration Cycle Request ticket has been updated to reflect this change. See also, [Change History](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history).

Questions:  Please post any questions in thread or reach out to Governance Team via #vfs-platform-support

**Comment by erinrwhite** [comment]
Draft [change history page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3350429697/Copy+of+Change+history+2) looking good 👍🏻 

For Slack post above - it looks good. Should we encourage folks to reach out to us via #vfs-platform-support, or by tagging `@platform-governance-team-members` in their team channel? @shiragoodman

**Comment by erinrwhite** [comment]
Also @it-harrison perhaps we add more detail to both the change history page and the slack announcement to the effect of:

"On 8/12/2024, Governance Team modified its Collaboration Cycle scheduling process such that VFS teams only need to schedule touchpoints in Calendly to notify the Governance Team. **A member of the Governance Team will acknowledge and verify the touchpoint with the team within a business day.**

> Note from refinement 7/25: There may be a potential delay in Governance response or after-hours response post Calendly scheduling, which means the message on the VFS team channel doesn't occur until then (aka not right away). Do we want to include this in our change announcement?

**Comment by erinrwhite** [comment]
Platform website [change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history) is updated, as are touchpoint pages 👍🏻

**Comment by it-harrison** [comment]
slack announcement: https://dsva.slack.com/archives/C03R5SBELQM/p1723645359014069

**Comment by shiragoodman** [comment]
I deleted the old Slack workflows this morning.

**Comment by erinrwhite** [comment]
@it-harrison [Kickoff page on platform website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff) updated! This one should be good to close
