### ISSUE TITLE
Write script to update instructions in Collab Cycle Request tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#84495]
## User Story
As a VFS team member about to schedule a Governance touchpoint, I want to be able to rely on the guidance in my CC Request ticket so that I can schedule seamlessly with minimal to no issues. 

Assignee: @it-harrison
Peer Reviewer: @briandeconinck

## Description
Part of our acceptance criteria for this initiative is to ensure that the guidance within the Collaboration Cycle Request tickets be updated to reflect the current process for scheduling. When Governance team last made updates to the scheduling process, we did not update the existing Collaboration Cycle Request tickets. This was a mistake as we still had many people still follow the old process which was challenging for us to pivot from. We will not be making this same mistake this time around.

In order to lighten the load and reduce the amount of manual work for Governance team, we will write a script that will automatically update the guidance in the existing Collaboration Cycle Request tickets so that if/when VFS teams schedule a DI, MPR or SR, their ticket is up to date and can be fully relied on.

This is only applicable to open tickets. Closed tickets do not need to be modified.

Current guidance for MPR:
<img width="1118" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJ4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fcd0ee1b1df68686ee7230a29f1ccecbac6fcf4/image.png" alt="image.png" />

**Please note that we will NOT be executing the script at this time. The script will be executed at a later date when we launch the new scheduling process.**

## Tasks
- [x] Determine how the Before MeetingVFS Actions will differ for the 3 touchpoints:
   - [x] Design Intent
   - [x] Midpoint Review
   - [x] Staging Review 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have written a script to update the instructions within the Before Meeting/VFS Actions section of the Collab Cycle Request ticket for Design Intent, Midpoint Review and Staging Review

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison @briandeconinck please read through the ticket and emoji respond on this ticket to confirm that you understand the ticket and don't have any questions. If you do have questions, please comment! ty.

**Comment by shiragoodman** [comment]
We will wait to execute the script until we begin working on ticket #84456.

**Comment by briandeconinck** [comment]
This looks great @it-harrison! When we determine the final wording for the touchpoint scheduling instructions, we just need to update [helpers.py](https://github.com/it-harrison/ticket-body-update/blob/master/helpers.py), correct?

**Comment by it-harrison** [comment]
Script will be updated when final text of touchpoint actions published.
