### ISSUE TITLE
GA4 Domo Data QC -- Monthly VA.gov Summary

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#84509]
### Description
This ticket is account for QC'ing the [Monthly VA.gov Summary](https://va-gov.domo.com/page/1314425343) dashboard with the newly create GA4 views/datasets. 

### Datasets & Views
- [[OUTPUT] Select Va.gov & Vets.gov Events By Month - BQ](https://va-gov.domo.com/datasources/d3331b50-92fc-4952-95fd-0916a0d7ca3d/details/overview?userId=853813555)
- [BQ - Records Letter Downloads](https://va-gov.domo.com/datasources/6ec00bab-98a0-4ea6-b7ec-6ac721dbb33e/details/overview)
- [[OUTPUT] Monthly PV, Users for All, WBC, Vets by Month](https://va-gov.domo.com/datasources/92a43417-0f9e-4ed7-bcdd-9eb290b471a9/details/overview)
- [BQ - Facility Locator pageviews by day](https://va-gov.domo.com/datasources/49a759eb-dfcc-4e00-8251-67e84b3e4f5c/details/overview)
- [BQ - Standard Search](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/overview)
- [[Output] - Monthly users by LOA](https://va-gov.domo.com/datasources/8e81aae1-9a1f-4bc6-b163-718ebd439373/details/overview)
- [BQ - Profile Details](https://va-gov.domo.com/datasources/86cbef9e-c473-4e62-b6c8-be7448f1c961/details/overview)

### Tasks

- [x] Create duplicate dataset and cards. Once Phil creates new view, route duplicate cards to new view. 
- [x] Follow up with Phil for any changes that need to be made to the dataset. 
- [x] Doing column per column comparison between the UA and the GA4 Views
- [x] Look for and document differences in variable names, formatting, etc.
- [x] Check if event labels, categories, actions -- etc that are used within BeastModes -- we might have to derive this
- [x] Copy report -- Save As -- use new GA4 Dataset -- 
- [x] Set permissions of copied report so it's just available by our team.
- [ ] If we pass these checks -- we can plan to certify that the reports are fresh.
- [x] If data issue, or discrepancy is found, mark in ticket and notify team.
- [x] Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
---

### Acceptance Criteria

- [x] Report has been copied -- using the new GA4 view.
- [x] Notes from QC or potential changes to ETLs have been documented on [this page](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).
- [x] All data issues have been flagged, and if needed, another ticket has been created for them. 
- [ ] If data is looking good -- we need to flag as fresh.

**Comment by johnny-jesensky-adhoc** [comment]
Initial QC has been performed by @ChristineYoungZA -- [here](https://va-gov.domo.com/page/1314425343). Findings from QC have been documented on these artifacts.

- [Data QC & Mapping Findings & Log](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/Data+QC+Mapping+Findings+Log)
- [GA4 Domo QC Record](https://docs.google.com/spreadsheets/d/1oaoXivzL854woEIUzgsPReoKW55Spz2p4S5WI_u_QHQ/edit#gid=1044752152)

We will be combining the follow-up items into a master list to remediate, and action on findings. Moving this to Done for now.

FYI @Blivaditis,  @dorseypa1
