### ISSUE TITLE
Implement alternative solution for actions/create-release

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#84503]
## Issue Description
The action actions/create-release is no longer maintained by GitHub. It currently is running on an outdated version of Node. We need to either locate another action that does this same function, or create the release via alternate means (GitHub API, etc).

---
## Tasks
- [x] Find alternative way to create releases that does not contain an outdated version of Node.
- [x] Implement the decided upon method
- [x] After merging, monitor the daily deploy to ensure that it goes off successfully with the new strategy in place.

## Acceptance Criteria
- [x] The create-release functionality no longer results in a Node version warning.

**Comment by CBonade** [comment]
https://oddball.slack.com/archives/C0498A63YGM/p1717000964173959 devops recommendation

**Comment by JoeTice** [comment]
Ticket is paused due to Curt's PTO
