### ISSUE TITLE
Implement update to treosh/lighthouse-ci-action@v9 to v11 and resolve error that results from it.

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#84506]
## Issue Description
When attempting to update treosh/lighthouse-ci-action@v9 to v11, the workflow errors out due to some formatting not being supported with the new version. We need to do this update as this action is running on an outdated version of Node. We need to do the update and then troubleshoot how to make our workflow adapt to the new version.

---
## Tasks
- [ ] Implement update to treosh/lighthouse-ci-action@v9 to v11.
- [ ] Diagnose and resolve error that results from the update.
- [ ] Run workflow a few times to ensure stability and functionality is still operational.

## Acceptance Criteria
- [ ] The treosh/lighthouse-ci-action no longer gives a warning about the node version.

**Comment by IGallupSoCo** [comment]
I started on a path to create a ["primed" branch](https://github.com/department-of-veterans-affairs/vets-website/compare/main...treosh-lighthouse-upgrade) that would upgrade the lighthouse action call to use v11 instead of v9.  I am noting it here and putting that on hold after reviewing the work with Curt.

We are instead moving forward on creating a custom version of the Lighthouse v11 logic that will live in the [vsp-github-actions repo](https://github.com/department-of-veterans-affairs/vsp-github-actions/tree/replace-lighthouse-action) and attempt to fix the random Lighthouse CI failures.  It will remain in use until the node upgrade for `vets-website` is successful, then will revisit the upgrade branch linked above.  Ideally, we return to using a modern version of the Lighthouse action in order to be able to avoid maintaining a custom action for security and stability purposes.

**Comment by IGallupSoCo** [comment]
Further exploration of the Lighthouse CI's logs suggests that the error initially being seen when this ticket was created, back in June 2024, has been resolved changes to some associated code, which remains unidentified at present.

The remaining errors in the most recent CI job failures seem to be largely related to pages where an unauthenticated user would be redirected to the root va.gov page, with a login modal present on the page and the initially targeted page in the URL as a query:

`{
    "lighthouseVersion": "9.6.8",
    "requestedUrl": "https://www.va.gov/education/download-letters/letters",
    "finalUrl": "https://www.va.gov/education/download-letters/letters",
    "fetchTime": "2025-01-24T13:12:27.899Z",
    "gatherMode": "navigation",
    "runtimeError": {
      "code": "FAILED_DOCUMENT_REQUEST",
      "message": "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_ABORTED)"
    },`

This may simply be the result of out of date assertions or authentication techniques being used, as these links are to the production instance of va.gov.

**Comment by IGallupSoCo** [comment]
The changes remain unclear.  For the time being, I will list some examples of the failures within the Lighthouse CI workflow and close this ticket:

`{
    "lighthouseVersion": "9.6.8",
    "requestedUrl": "https://www.va.gov/education/verify-school-enrollment/mgib-enrollments",
    "finalUrl": "https://www.va.gov/education/verify-school-enrollment/mgib-enrollments",
    "fetchTime": "2025-01-24T13:14:46.141Z",
    "gatherMode": "navigation",
    "runtimeError": {
      "code": "FAILED_DOCUMENT_REQUEST",
      "message": "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_ABORTED)"
    },`

The requested URL gets redirected here: `https://www.va.gov/?next=%2Feducation%2Fverify-school-enrollment%2Fmgib-enrollments`

`{
    "lighthouseVersion": "9.6.8",
    "requestedUrl": "https://www.va.gov/education/check-remaining-post-9-11-gi-bill-benefits/status",
    "finalUrl": "https://www.va.gov/education/check-remaining-post-9-11-gi-bill-benefits/status",
    "fetchTime": "2025-01-24T13:12:33.433Z",
    "gatherMode": "navigation",
    "runtimeError": {
      "code": "FAILED_DOCUMENT_REQUEST",
      "message": "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_ABORTED)"
    },`

That requested URL gets redirected here: `https://www.va.gov/?next=%2Feducation%2Fcheck-remaining-post-9-11-gi-bill-benefits%2Fstatus`

This is an example of a redirect without any auth required:

`  {
    "lighthouseVersion": "9.6.8",
    "requestedUrl": "https://www.va.gov/family-and-caregiver-benefits/education-and-careers/transferred-gi-bill-benefits/apply-form-22-1990e",
    "finalUrl": "https://www.va.gov/family-and-caregiver-benefits/education-and-careers/transferred-gi-bill-benefits/apply-form-22-1990e",
    "fetchTime": "2025-01-24T13:15:34.108Z",
    "gatherMode": "navigation",
    "runtimeError": {
      "code": "ERRORED_DOCUMENT_REQUEST",
      "message": "Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 403)"
    },`

Redirects to here: `https://www.va.gov/family-and-caregiver-benefits/education-and-careers/transferred-gi-bill-benefits/apply-form-22-1990e/introduction`

**Comment by IGallupSoCo** [comment]
So ultimately, this is a matter of test assertion failure, which may or may not be a QA responsibility going forward.
