### ISSUE TITLE
[FE] - Re-factor OH travel app to be not grouped by facility

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#84508]
## Summary
Refactor current app to not group things by facility and allow for single selection of one specific appointment.

** this refactor is for functionality and not UX, the end result is just a jump start for when we get wires.

## Tasks
- [ ] [FE] refactor
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski Is this going to be complete today or need to roll over?

**Comment by wullaski** [comment]
@loripusey the work is done for this ticket and it's in a good place to start on the content changes once the wireframes are approved.

**Comment by loripusey** [comment]
don't we have other tickets for the remainder of the work? meaning, we can close this one?
