### ISSUE TITLE
Implement update to treosh/lighthouse-ci-action@v9 to v11 and resolve the error that results from it

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#84510]
## Issue Description
When updating treosh/lighthouse-ci-action@v9 to v11 due to a Node outdated warning, an error resulted that prevents the successful running of the workflow for the daily lighthouse scan. The error seems to be centered around formatting of an argument that is no longer supported. We need to implement this update and then diagnose and resolve the error in our workflow to move to the newest version.

---
## Tasks
- [ ] Implement the update from treosh/lighthouse-ci-action@v9 to v11
- [ ] Diagnose and resolve the error that results from the update when running.
- [ ] Test the workflow multiple times for stability.

## Acceptance Criteria
- [ ] The daily lighthouse scan workflow completes successfully.
- [ ] The daily lighthouse scan workflow no longer gives a warning about the version of node used by its actions.

**Comment by ericboehs** [comment]
Closing as dupe of 84506
