### ISSUE TITLE
Present "fuzzy search" to the Design System Council

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#84521]
## Background
We are exploring a "fuzzy search" where a user types into a search box and search results appear as the user types.  This is not part of the design system, so we will need to follow the "experimental" process and present this concept to the design system council on 6/6.

## Tasks
- [ ] Connect with Content Classification to understand how they structured their presentation
- [ ] Present our fuzzy search design to the Design System Council
- [ ] Receive and document feedback from the Design System Council

## Acceptance Criteria
- [ ] Our "fuzzy search" for Appoint a Representative has been presented to the Design System Council and we understand if this is a concept we can move forward with.

**Comment by oddball-lindsay** [comment]
Moving forward with the search results experience, where we show cards as the search result. No longer pursuing our "fuzzy search" design for this study.
