### ISSUE TITLE
Tech Debt | Add Veteran/User Info to Saved Claim 

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#84546]
# Tech Debt | Add Veteran/User Info to Saved Claim 
## Description
Currently, our SavedClaim model does not persist any data about the submitter or when the claim was started. 
As a Code Yellow responder, I want to be able to track metadata about a claim, so that I can more easily remediate/research failed claims.

## Tasks
 - [x] Add optional UserAccount foreign key to SavedClaim
 - [x] Add optional In Progress Form Creation Timestamp to SavedClaim (already addressed)
 - [x] Update Codeowners for SavedClaim to include teams
   - non-disability
   - dependents
   - pension
   - 10-10
   - Education Benefits
   - disability
 

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario: Tech Debt | Add Veteran/User Info to Saved Claim**
  - Given the SavedClaim model does not currently persist user or veteran information
  - When the tasks are completed as described in the issue description
  - Then the SavedClaim model should include optional fields for a UserAccount foreign key, a Veteran ID, and an In Progress Form Creation Timestamp
 - [ ] Unit tests have been updated and pass
 - [ ] Change is approved by all affected teams

**Comment by tblackwe** [comment]
removed Veteran ID from requirements, we will only persist UserAccount data.

**Comment by mjknight50** [comment]
Moving this to backlog as we need to address logging and monitoring issues first.

**Comment by mreed101** [comment]
Work being done on the following branch vabc/jr/user-info-to-saved-claim-84546

**Comment by mreed101** [comment]
@micahaspyr Does the scope of this ticket include populating the user_account association and the "in-progress form creation timestamp" fields with actual data or is the expectation simply to add the necessary migrations and schema changes to support these fields?

If data population is required:
- What is the expected data source for populating these fields?
- Please note that saved_claim already has a form_start_date that might be equivalent to the requested in progress form timestamp being requested

If data population is not required:
- Are there any steps we should take to ensure these fields do not disrupt existing functionality such as setting default values?

**Comment by mjknight50** [comment]
If saved_claim already has form_start_date, I can't think of a scenario where that would be different than the IPF create time.

**Comment by mreed101** [comment]
Per my conversation with Thomas, I will not be adding an optional field to capture in progress timestamp. form_start_date appears to capture this data already.

Response from Thomas is below.

> The problem I was trying to solve is that SavedClaim doesn't keep any information about the veteran and when they started filling in the claim.

**Comment by mjknight50** [comment]
@mreed101 or @micahaspyr - What are we waiting on with this?  Is there more work to do?

**Comment by steele-lm** [comment]
Needs review before sending to Platform.
