### ISSUE TITLE
Create instructions wireframes for VAHB App

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#84543]
## Task Description
Complete mockups for prep instructions that include medication review

## Notes and References
- [Project folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/projects/2024-05-medication-language-update)

## Acceptance Criteria
- [x] Mockups are complete
- [x] VAHB team has approved mockups
- [x] Dev tickets have been created

## Deliverables
- [Component overview](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32639&t=i7ZsGuqPq3w40iGu-4)
- [VAHB mockups](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/Appointments-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=3169-3473)

**Comment by outerpress** [comment]
@wavelaurenrussell @mistymg I'm using this ticket to track design work for the medication wording/preparation instructions - when we sync up let's chat about how y'all track work and see what makes the most sense across teams.

**Comment by outerpress** [comment]
I don't think I've noted this here, the design work is done. This is on hold until the new mobile dev is trained up/ready to pick up the work.

**Comment by outerpress** [comment]
CIE mobile dev has picked up the work so closing
