### ISSUE TITLE
VFS internal DNS delegated to VSP 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8455]
## User Story or Problem Statement
We on the VSP-Operations need to assume a bit more control of an internal zone for the new infrastructure recommit. 
---
## Tasks
- [x] Meet with member(s) of Appeals team who has/have been through a similar process to get some "lessons learned" from their experience.
- [x] Look into the service Appeals team is using for inbound DNS queries.
- [ ] Create and implement all IaC pieces through Terraform.
- [ ] Setup automation for new DNS service to fit within the BRD.
- [ ] File change request with VA IT to get the desired zone delegated to us.
- [ ] Ensure all above pieces are in place and intended functionality is present. 

## Acceptance Criteria
- [ ] Desired internal zone is delegated to us and we have infrastructure in place to handle/route inbound DNS queries. 
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
