### ISSUE TITLE
Vets API: Alert if dev/staging deploy is delayed with GHA

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#84577]
Dev and staging environments auto-deploy with each commit (CD). Sometimes there are issues that hang up the deploy but this does not always mean a "failed" sync as pods may be stuck progressing (e.g. db/migrate).

There are several ways to trigger an alert like this but after talking with the Backend CoP, a simple GitHub Action seemed like a good trade-off between effort and delivered value. The primary goal is to be alerted of issues before they make it to the daily deployment.

## Tasks

- [x] Create a GitHub action that alerts if the deployed SHA differs from master's sha for >30 minutes
- [x] Add the existing Slack integration seen in other Actions
- [x] Test the alert by lowering the difference delay to 1 minute

## Acceptance Criteria

- [ ] An alert appears in the BE CoP Notifications channel if the latest master commit isn't deployed within 30 minutes.

**Comment by ericboehs** [comment]
A [test notification](https://dsva.slack.com/archives/C039HRTHXDH/p1718122104560309) was successful and the workflow is [running every 10 minutes](https://github.com/department-of-veterans-affairs/vets-api/actions/workflows/deploy_delay_notifications.yml?query=branch%3Amaster).
