### ISSUE TITLE
Domo Dataset Updates for GA4 - Priority Wave 1b (KPI dashboards)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#84587]
### Description
This ticket is to account for updating the Domo datasets that reference the UA data table in BigQuery -- 176188361. There are 74 total datasets that meet this criteria, so we will be starting with the ones that power are most critical dashboards.

- [MyVA KPIs Report](https://va-gov.domo.com/page/1167851935)
- [VA Notify KPIs](https://va-gov.domo.com/page/2040841289) 
- [Online Caregiver Application - KPIs](https://va-gov.domo.com/page/1905395623)
- [KPIs - Health Care Application](https://va-gov.domo.com/page/980067552)
- [Profile KPIs](https://va-gov.domo.com/page/1834995012?userId=1539186973)
- [VA Chatbot KPIs](https://va-gov.domo.com/page/939649897)
- [VAOS KPIs](https://va-gov.domo.com/page/1769944412)

Complete list of datasets can be found [here](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=0&fvid=2002218633).

---

### Tasks
Each of the datasets in Domo have been updated with a GA4 equivalent Views has been created:

**MyVA KPIs Report**

- [x] [BQ - my VA sessions and comparissons](https://va-gov.domo.com/datasources/414f6558-2f16-4327-815e-7f32acfacd10/details/overview)
- [x] [BQ - MyVA API requests by status](https://va-gov.domo.com/datasources/ba47c9e9-61c8-4823-8867-dd80b55c7831/details/overview)
- [x] [BQ- all MyVA Events by day](https://va-gov.domo.com/datasources/4e9a3037-79cf-43de-bd89-9aadf24a0d41/details/overview)
- [x] [BQ - MyVA navigation clicks by LOA](https://va-gov.domo.com/datasources/f1593f5f-ea15-483d-ae63-80faca1c92ce/details/overview?userId=853813555)
- [x] [BQ - Standard Search](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/data/table)
- [x] [BQ - All MyVA Users, Pageviews and Events ](https://va-gov.domo.com/datasources/bdc0655a-8fbd-41a5-8919-9b79d9fc780b/details/overview?userId=853813555)

**VA Notify KPIs**
- [ ] [~BQ - VANotify~](https://va-gov.domo.com/datasources/58f2d9d7-3058-4080-85b1-5dc938b49ea7/details/overview) - NOT FOUND ON SPREADSHEET
- [x] [BQ - VANotify_GA](https://va-gov.domo.com/datasources/cb5d68ed-14ca-4431-a6c1-7893c5882154/details/overview)
- [x] [BQ - VANotify_GA_Landing_Pages](https://va-gov.domo.com/datasources/1fcd5fbe-add0-4fb2-a387-e302919df2b0/details/overview)

**Online Caregiver Application - KPIs**

- [x] [BQ - All Caregivers Events by Day](https://va-gov.domo.com/datasources/99fdb5c9-b98e-49a1-bdb0-249496fc5a35/details/overview)
- [x] [BQ - Open Funnel - Caregivers 10-10cg](https://va-gov.domo.com/datasources/015db778-ddbf-4bb7-9558-02db484ee20c/details/overview)
- [x] [BQ - Caregivers 10-10cg AVG time to complete](https://va-gov.domo.com/datasources/5d56f3db-f5d0-4bea-a931-1fe21340eae7/details/overview)

**KPIs - Health Care Application**
- [x] [BQ - Entrance Data for Health Care Pages by Date 
](https://va-gov.domo.com/datasources/c8baf7a5-a1f9-4638-b606-626d4487b28c/details/overview)
- [x] [BQ - Form Events by Date and Device Category ](https://va-gov.domo.com/datasources/7c6bed43-1daa-43bb-bfcf-e44fd6b78958/details/overview)
- [x] [BQ - Open Funnel - 1010EZ HCA Step Completion by User](https://va-gov.domo.com/datasources/639a822f-575c-4bb2-92e0-29e18e932562/details/overview)

**Profile KPIs**

- [x] [BQ - Profile Detail](https://va-gov.domo.com/datasources/86cbef9e-c473-4e62-b6c8-be7448f1c961/details/overview)

**VA Chatbot KPIs** 
- [x] [BQ - Chatbot Hits](https://va-gov.domo.com/datasources/13c5d5c4-66af-4b5a-9123-1be484fe96e6/details/overview)

**VAOS KPIs Performance**
- [x] [BQ - Vaos Events](https://va-gov.domo.com/datasources/b1a085f4-b988-49d7-b283-aa3ec7c30acc/details/overview)
- [x] [BQ- Vaos Scheduling Frequency](https://va-gov.domo.com/datasources/bd0a5bf7-c10d-4e0c-b62a-3ac34a530f16/details/overview)
- [x] [BQ - Vaos events with error](https://va-gov.domo.com/datasources/b011e0d7-8293-473c-868d-902d22f8e372/details/overview)
- [x] [BQ - VAOS - Community Care - Scheduling Completion Rate by day](https://va-gov.domo.com/datasources/3e4f81eb-b663-44df-a885-b01e4f77fe7b/details/overview)
- [ ] [~BQ - VAOS - Express Care - Scheduling Completion Rate by day~](https://va-gov.domo.com/datasources/9a40e17e-2d19-4fd6-938c-145d702b8a0a/details/overview) -  NOT FOUND ON SPREADSHEET
- [x] [BQ - VAOS - Request - Scheduling Completion Rate by day ](https://va-gov.domo.com/datasources/816b36ad-43ee-4347-b63b-2bda019d1dda/details/overview)
- [ ] [BQ - VAOS Success Events with type of care](https://va-gov.domo.com/datasources/f372cafa-f2de-434e-a5cd-b243354c7adb/details/overview)
- [ ] [~BQ - Health Care pages - pageviews, users~](https://va-gov.domo.com/datasources/8bdb8c58-ce75-4c4f-8b9f-aa35553fdbdd/details/overview) - NOT FOUND ON SPREADSHEET
- [x] [BQ - VAOS - Logged in vs VAOS start by day](https://va-gov.domo.com/datasources/e8f108ef-c296-457f-b8f2-463f50b06518/details/overview)

**KPIs - Debt Mangement**
- [x] BQ - Debt Letters - PVs, Bounces by Device Category by Day 

---

### Acceptance Criteria

- [x]  Domo datasets have been updated to reference new GA4 table.
- [x] Dataset has been marked as updated in the dataset log [here](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=0&fvid=2002218633).

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 -- given you're quick progress on these, officially adding this to the current sprint, given most of these are already _Done_.

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 -- The GA4 Versions of these have all been accounted for and created, though there are a few we are refining/tweaking a few, but going to mark this as _**Done**_ as we have the datasets created, which is what this was meant to address.

FYI @Blivaditis, @ChristineYoungZA
