### ISSUE TITLE
DR | Increase retries on Evidence Upload Sidekiq job

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#84597]
## Value Statement

**_As a_** developer

**_I want_** sidekiq jobs to retry enough times

**_So that_** it does not exhaust too soon before a service outage/issue (e.g. AWS) is resolved.

---

## Background Context
After talking to Steve and Emily, we found out that we should have a higher number of retries set for our SubmitUpload Sidekiq job — it's currently set to 5 but was recommended that we set it to something higher like 13 so that they don't exhaust too soon before an issue or outage is resolved.

Related to an issue we had where there was an issue with AWS and we had failed evidence uploads: https://github.com/department-of-veterans-affairs/va.gov-team/issues/72199

## Acceptance Criteria

- [x] Sidekiq job for evidence uploads retry more than 5 times (13 was suggested value)

## Open questions

- Add here

## Tasks

- [x] Update [SubmitUpload Sidekiq job](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/decision_review/submit_upload.rb#L13) to use 13 retries instead of 5
- [x] Check for other places where our retries are set too low (could also update as a part of this ticket if the lift is low enough)

## Definition of Ready

- [x] Clear value description
- [x] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by shaunburdick** [comment]
13 works for me based on the [backoff table](https://github.com/sidekiq/sidekiq/wiki/Error-Handling):
```
 # | Next retry backoff | Total waiting time
 -------------------------------------------
 1 |       0d 0h 0m 20s |       0d 0h 0m 20s
 2 |       0d 0h 0m 26s |       0d 0h 0m 46s
 3 |       0d 0h 0m 46s |       0d 0h 1m 32s
 4 |       0d 0h 1m 56s |       0d 0h 3m 28s
 5 |       0d 0h 4m 56s |       0d 0h 8m 24s
 6 |      0d 0h 11m 10s |      0d 0h 19m 34s
 7 |      0d 0h 22m 26s |       0d 0h 42m 0s
 8 |      0d 0h 40m 56s |      0d 1h 22m 56s
 9 |       0d 1h 9m 16s |      0d 2h 32m 12s
10 |      0d 1h 50m 26s |      0d 4h 22m 38s
11 |      0d 2h 47m 50s |      0d 7h 10m 28s
12 |       0d 4h 5m 16s |     0d 11h 15m 44s
13 |      0d 5h 46m 56s |      0d 17h 2m 40s
14 |      0d 7h 57m 26s |        1d 1h 0m 6s
15 |     0d 10h 41m 46s |     1d 11h 41m 52s
16 |      0d 14h 5m 20s |      2d 1h 47m 12s
17 |     0d 18h 13m 56s |       2d 20h 1m 8s
18 |     0d 23h 13m 46s |     3d 19h 14m 54s
19 |      1d 5h 11m 26s |      5d 0h 26m 20s
20 |     1d 12h 13m 56s |     6d 12h 40m 16s
21 |     1d 20h 28m 40s |       8d 9h 8m 56s
22 |       2d 6h 3m 26s |    10d 15h 12m 22s
23 |      2d 17h 6m 26s |     13d 8h 18m 48s
24 |      3d 5h 46m 16s |      16d 14h 5m 4s
25 |     3d 20h 11m 56s |     20d 10h 17m 0s
```

**Comment by dfong-adh** [comment]
#17083 merged
