### ISSUE TITLE
[CAIA Intake] VA Health and Benefits app: Better MHV access error messaging

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#84607]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: VA Health and Benefits app
- **OCTO product owner:** Rachel Han
- **Product name:** VAHB health tools 
- **Product manager:**  TBD
- **Slack channel:** [#va-moble-app](https://dsva.slack.com/archives/C018V2JCWRJ)
- **Dedicated content writer on your team (if you have one):** @mistymg 
- **Dedicated a11y specialist on your team (if you have one):** n/a
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Update error message content on VAHB for health tool users who do not have access to VAHB health tools because of an MHV access issue. Should be done in coordination with similar work happening on VA.gov.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

Need to work with SMEs to identify: (1) exactly when/why users would see message; and (2) what the correct message should be.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [ ]  No
- [x] Not applicable
 
 *Note: **If you check yes, we’ll reach out to discuss details about the content in the react widget. We use these widgets to display entry points for new products to a certain percentage of users who visit our static pages. Please refer to this [GitHub reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for dynamic content.
 
- [ ]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as there is additional work involved that may impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Slack convo](https://dsva.slack.com/archives/C018V2JCWRJ/p1717515106004699)
- [Original ticket filed and then closed](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8785) in favor of this ticket.
- This is current state. One immediate change needed is removal of reference to "Advanced" accounts, which no longer exist. Additional edits are likely necessary.
  - ![image003](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7645362/6f55ba7f-2139-414a-9b6d-ce1dd5d4549d)

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92628
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92630
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92629
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92631
```

**Comment by DanielleThierryUSDSVA** [comment]
@strelichl Let's chat about this one in our Thursday sync. Thanks!

**Comment by laurwill** [comment]
@mistymg can you link the screenshot of the full screen here? Thank you!

**Comment by mistymg** [comment]
@laurwill Here you go! The external link takes Veterans [here](https://www.myhealth.va.gov/web/myhealthevet/upgrading-your-my-healthevet-account-through-in-person-or-online-authentication).
![Screenshot 2024-06-13 at 10 54 57 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102106810/92037488-eabd-4f9e-afac-a88d66a18a6e)
![Screenshot 2024-06-13 at 10 55 02 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102106810/5a7fc1e0-4445-4524-9400-f0b510ce6407)

**Comment by sterkenburgsara** [comment]
@batemapf Does the app have the exact same access logic/requirements as VA.gov? // cc @mistymg

**Comment by laurwill** [comment]
Okay, based on [this very long slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1720797975361669) with mobile app team, I'm about 90ish% sure that we should replace this screen with a mobile version of this ["Register your account with My HealtheVet" alert](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2857-6321&t=Ka68Py6kygCavGds-1). 
- Mobile only allows LOA3 access, so it can't be a verification issue. This must be how mobile prompts people to connect to their health info in MHV.
- If this is the situation, then we'll also need a version of the ["You don't have access" alert](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2681-10675&t=Ka68Py6kygCavGds-1) that will show to people who have connected to MHV but actually cannot use SM. @mistymg is there already a screen like that in mobile, do you know?
- We'll need to make similar changes to a similar screen in the prescriptions feature on mobile.

**Comment by mistymg** [comment]
@laurwill I'm confused about your 2nd bullet. Is the "You don't have access" alert like saying the Veteran isn't enrolled in VA health care?

**Comment by sterkenburgsara** [comment]
@mistymg "you don't have access" means that the user is not registered to any VA health facilities (they've never had an appointment), so they don't have health data yet (we don't give them access to the health apps until they do).

**Comment by DanielleThierryUSDSVA** [comment]
@laurwill and I have synched up on this. I think the path you're heading towards with the 2 alerts breaking down the broader access issue vs. the more technical connection to MHV is right. But I want to bring in the identity team as well to discuss and for broader awareness/alignment. If it's helpful, we could have a call with the folks on this ticket to talk through this.

@Samara-Strauss @blacktm @parkerbees @claytonzook @charlye-bluetiger

**Comment by parkerbees** [comment]
@DanielleThierryUSDSVA the Identity team would certainly be happy to jump on a call to discuss.

**Comment by sterkenburgsara** [comment]
@laurwill have you already synced with mobile app team to share the alerts that were approved by Identity & just merged into VADS? Let me know how I can help!

**Comment by laurwill** [comment]
Hi all, I'm OOO this week but I talked with @mistymg on Friday about next steps here. If you all want to sync this week, here's what we need to confirm. We know mobile sends people to web sign-in modal and then returns them to the app. We're not sure if all subsequent steps in the sign-in flow (like "verify your identity") technically happen inside mobile or on web, but either way mobile will need to account for these steps in the sign-in flow and make sure they're implemented correctly: 

1. Sign in (mobile sends people to web for this, shouldn't need to do anything different here)
2. If not verified, serve a verify alert
     2a. If using Login.gov or ID.me, serve this [verify alert](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=13356-1783&t=6Mj4MrskGjWwa7gH-1)
     2b. If using MHV, serve this ["use a different account" alert](https://www.figma.com/design/afurtw4iqQe6y4gXfNfkkk/VADS-Component-Library?node-id=13356-1783&t=yRUdf8ckiEHfM2iq-1)
3. If not registered, serve this ["Register your account with My HealtheVet" alert](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2857-6321&t=Ka68Py6kygCavGds-1)
4. If verified and registered and still no access to health tools, serve a version of this ["You don't have access" alert](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2681-10675&t=Ka68Py6kygCavGds-1)

Also noting that Misty found this additional screen with outdated sign-in content (mentions deprecated knowledge-based verification option). This is also unusual in that it seems to appear before the sign-in step, so we're presenting this large piece of content to people with verified accounts, too. @DanielleThierryUSDSVA should we try to prioritize a full audit of sign-in content in the mobile app, to make sure we find and update all of these outdated screens?
![image](https://github.com/user-attachments/assets/f4e18215-7986-4735-8177-a9a9e1b30da9)

**Comment by mistymg** [comment]
@DanielleThierryUSDSVA Happy to chat today about what next steps should be. Admittedly, I'm still not super clear on our sign in and verification process on mobile app. (I do know that the screen shot above is just shown for first-time sign in...and the CTA still just takes you to a sign in screen.)

**Comment by sterkenburgsara** [comment]
Update:[ In this slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1725471837392789), Don McCaughey shared that VAHB does not have any scenario where user with LoA1 accounts can use the app. There is no identity verification flow for any sign-in credential - users need to have an LoA3 from the get-go. 

This eliminates the need for 2/4 alerts we linked above. I posed a question about current state error messaging/alerts for users who are not known by the MHV-API and may need the MHV registration alert, as well as question about folks who have no data & no facilities in their profile and may need the "no access" alert. I will update when I get responses. 

// cc @laurwill

**Comment by sterkenburgsara** [comment]
Hey all, [spinning up an IA-specific ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92401) under this one to document user flows for all the LoA1 sign-ins to see what errors spin up / where in that situation.

**Comment by DonMcCaugheyUSDS** [comment]
@mistymg @laurwill When a VAHB mobile user signs in, we show the va.gov `/sign-in` page in a web view ([staging version here](https://staging.va.gov/sign-in/?oauth=true)).  The mobile user goes through the auth flow and any intermediate verification and warning flows **in this web view**.  The mobile team **does not** manage this page or its content.  I'm assuming this belongs to the identity team.

If any content changes need to be made to the sign in flow, they need to be made on va.gov, not in the VAHB mobile app.  (Hopefully the `/sign-in` page is mostly shared with va.gov so these changes can be done in one place for both modes.)

**Comment by DonMcCaugheyUSDS** [comment]
For secure message errors, you can view the current mobile [error message text here](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/0cd616bc27cb23fffecfc10d9a97d28567e4755c/VAMobile/src/translations/en/common.json#L990) (keys beginning with `notEnrolledSM`).

**Comment by DonMcCaugheyUSDS** [comment]
For the mobile sign-in LOA gate screen, you can view the [current text here](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/0cd616bc27cb23fffecfc10d9a97d28567e4755c/VAMobile/src/translations/en/common.json#L924) (keys beginning with `loaGate`).

**Comment by laurwill** [comment]
Thank you @DonMcCaugheyUSDS ! I searched the JSON file and it looks like the Rx and SM error screens are the only place we reference upgrading to premium, so that's good. 

Updates on this work:
- I created 4 tickets to track 4 distinct pieces of work: fixing the API error, fixing the "no access" errors in SM and Rx, fixing the sign-in LOA gate screen, and determining if we need any additional sign-in related screens or errors in mobile app. 
- I escalated the API error ticket to the identity team in the identity-support slack channel, since Don confirmed that this error is handled in the web-based authentication flow. 
- I'm now building out the 3 other tickets, which all capture work needed inside the mobile app itself.

**Comment by mistymg** [comment]
Confirmed all of Laura's subtasks/tickets related to this work were completed. Closing ticket.
