### ISSUE TITLE
VRE | Tech Debt | Refactor Veteran Information 

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#84604]
# Tech Debt | Veteran Readiness | Refactor Veteran Information 
Follow on ticket to #84546

Forms that do not require authentication: Burial 530EZ, Pension 527EZ, Chapter 36/PCPG, any others?

## Description
As a Veteran, I'd like to be able to logout after my claim is submitted, without causing an error that prevents my claim from being process

## Tasks
 - [ ] Add UserAccount, Veteran, and In Process Form information to Saved Claim at creation time
 - [x] Migrate `veteranInformation` in SavedClaim.form_json from the sidekiq job to the controller
 - [x] Remove `User` model https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/vre/submit1900_job.rb

**Comment by micahaspyr** [comment]
@steele-lm in this ticket, the second and third checkmarks are no longer applicable as it was fixed when @evansmith refactored the code to pass a struct object into the Submit1900Job.
