### ISSUE TITLE
Mockup an interstitial page during sign in that encourages CSP migration

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#84617]
## Description of UX Tasks
Charles has asked for a mockup of how we might, from a UX standpoint, downplay and/or further discourage folks signing in with DSL/MHV. One idea is to have an interstitial page that folks signing in with DSL/MHV would see that encourages them to create and/or sign in using IDme or LIG.

## Tasks
- [x] consider what is needed here
- [x] figure out if and how much of a previous mockup we can reuse or iterate 
- [x] Either starting from previous mockups or from scratch, create a mockup in Figma for an interstitial page that reinforces the need to migrate to a modern CSP
- [x] present to Samara/Tom

## Documentation
- [interstitial mockups](https://www.figma.com/design/lylonhqrQlunWjmEztIxGv/Sign-in-Modal-Feedback-Desktop?node-id=21-293&t=WpnEsdrCb70aokWu-0) from our team from 2 years ago, which didn't get implemented at the time
- [prior research from our team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-04%20Proactive%20CSP%20Migration/2023-04%20Proactive%20CSP%20Migration%20research%20findings.md) that might apply here

## Definition of Done
- Create a mockup of an interstitial
- discuss with and hand off to Samara

## Acceptance Criteria
- [x] Documentation has been updated
- [x] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
