### ISSUE TITLE
Mockups to downplay DSL/MHV on the sign in page.

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#84616]
## Description of UX Tasks
Charles has asked for a mockup of how we might, from a UX standpoint, downplay and/or further discourage folks signing in with DSL/MHV on the sign in modal and USiP. Legacy CSPs would still need to be available, but this UX would further reinforce comms plans around needing to migrate.

## Tasks
- [x] consider possible ways to make this UI change
- [x] figure out if and how much of a previous mockup we can reuse or iterate
- [x] Either starting from previous mockups or from scratch, create 1-3 mockup in Figma for how we might give less preference to legacy credentials (MHV/DSL)

## Documentation
- [current mockups in Figma](https://www.figma.com/design/skWgD0gHYGlKSoLdH097OX/USiP-and-sign-in-modal---deemphasize-DSL%2FMHV?node-id=0-1&t=ba2MdAFSEJCQxJoM-0)

## Definition of Done
- Create up to 3 mockup variations
- discuss with and hand off to Samara

## Acceptance Criteria
- [x] Documentation has been updated
- [x] Reviewed by UX Team
- [ ] Reviewed by PMs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
