### ISSUE TITLE
Delay to Vets-API ELB during deployments (dupe 1)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#84627]
Sprint 3 ticket is [86347](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/86347) to continue the work. 

DUPLICATE OF [81916](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81916), because the work is still in progress 

**HIGH PRIORITY**

## Issue Description

As developers and users, 
We need deployments to go smoothly and without significant delay
So that the deployments do not hang up other deployments and delay other users of the Vets-API. 

It was brought to the team's attention back in January ([here](https://dsva.slack.com/archives/CBU0KDSB1/p1706631322227849)) that there have been error responses that occur during the Vets API deployment reported from the Lighthouse team. Some Lighthouse requests call out to Vets API and they see error responses returned for a short window that aligns with the Vets API deployment. While it is expected that the vets-api ELB during deployments, may take up to 180s, we may need to partner with the Lighthouse team to reduce timeouts and failures and try to create a solution that will minimize these. The problem could lie on any where from Kong to the traefik layer in the stack. The potential problem area is depicted in this graph:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1sQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffc0a116b7857cf53ff963991ceedb7f2b29d7be/image%20%2816%29.png" alt="image (16).png" />

## Tasks
- [X] Review current logs (see Slack thread) - Rachal has a list of the current endpoints (could they be put into their own bulkheads?)
- [ ] Troubleshoot what could be causing the timeouts and failures during the daily deployment
- [ ] Document the timeouts and failures, see if there is a common thread
- [ ] Meet with Lighthouse team (Beau Grantham?) to ideate on solutions for minimizing timeouts and failures
- [ ] Test ideas for minimizing timeouts and failures

## Success Metrics
- [ ] That the root cause of the delays and timeouts are identified
- [ ] That a solution is created and successfully tested to limit delays and timeouts during the daily deployment

## Acceptance Criteria
- [ ] That there will be a viable and better solution that has fewer failures and timeouts in the daily deploy for the Vets-API ELB
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
The notebook - https://vagov.ddog-gov.com/notebook/3799/five-hundreds - is a centralized view of what is being reviewed and when changes are made, they are captured here.

**Comment by jennb33** [comment]
This is showing some improvements from the deploy on Friday (from 80 to 50 errors) per @LindseySaari

**Comment by jennb33** [comment]
On 6/11, after thinking that we had a solution on 6/10, all the errors bounced back. Team is reaching out to Hector for a strategy reset on 6/12.
Checking the Puma backlog, even after the memory bump there was no resolve. 
It's only the appeals pods that are throwing the errors.

**Comment by LindseySaari** [comment]
@flooose and I met with Hector to discuss some potential testing avenues:
1. Potentially load testing a lower environment (staging) - We could break out a bulkhead for one or more lighthouse routes (potentially a healthcheck - because we would need to simulate an authenticated state or form params, etc), pause the autosync, run the load test and observe Puma backlog behavior
2. We could look at things at a packet level to capture more detailed request details around timeouts. Observation at a packet level could rule out a number of things and could boil down to something as simple as a timeout tweak. 
3. Make a ticket for stabilization windows - Could we benefit from more fine tuning for our HPA scaling stabilization (up and down)

**Comment by LindseySaari** [comment]
Doing some more network analysis, the retransmits shoot up significantly during deploys: https://vagov.ddog-gov.com/network?query=%28client_kube_deployment%3Avets-api-appeals%20OR%20server_kube_deployment%3Avets-api-appeals%29%20&cols=sent_vol%2Crcvd_vol%2Ctcp_r%2Crtt%2Crtt_v%2Ctcp_l%2Ctcp_e_raw%2Ctcp_c_raw%2Ctcp_e%2Ctcp_c&filter_from=1&filter_to=2287796339&netviz=sent_vol%3A%3A%2Ctcp_r_pct%3A%3A%2Crtt%3A%3A&refresh_mode=paused&showGraphs=true&showRQ=true&from_ts=1718124900000&to_ts=1718126700000&live=false

**Comment by LindseySaari** [comment]
Plan of Action:
- [Test the CPU bump PR tomorrow](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2902)
- If unsuccessful, we will adjust the helm chart to set memory requests: 8 limit: 12 on appeals pods only
- During all of this, continue to investigate the TCP retransmit errors and monitor all charts and the notebook

**Comment by jennb33** [comment]
There will be new configurations released today per @LindseySaari 
Been following the small pod philosophy, which doesn't follow the K8s reccs.

**Comment by jennb33** [comment]
Ticket for Sprint 3 is [86347](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/86347)
