### ISSUE TITLE
Adjust breakers boards and alerts to account for metric adjustments

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#84649]
Duplicate of ticket [83287](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/83287)

## Description 
As a follow-up to the metric tagging adjustments [outlined in this ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/77891), we need to create a subsequent ticket to update the breakers boards to reflect these changes. To avoid a visibility gap, these boards must be prepared in advance. This will ensure that they are fully operational before we implement the Datadog mapper configuration in production

## Tasks
- [x] Adjust [existing breakers boards ](https://vagov.ddog-gov.com/dashboard/lists?q=breakers)to account for new tagging scheme
- [x] Adjust any external service [monitors](https://vagov.ddog-gov.com/monitors/manage?q=external%20service%20team%3APlatform&order=desc) based on these metrics. 
    - [x] Make changes [in terraform](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/external_services_monitors.yaml)
- [x] Verify boards are functional (against lower env metrics already flowing in)
- [x] Make annoucement in ToT for other teams that are possibly dependent on alerts @jennb33 

## AC
- [x] Existing breakers boards are adjusted and ready for when the mapper changes are applied to production
- [x] Monitors are adjusted
- [x] ToT slide accounts for the announcement around the change

**Comment by jennb33** [comment]
This work will be announced at the 6/11/2024 ToT

**Comment by jennb33** [comment]
Slide from 6/11/2024 Team of Teams, announcing the change: [Slide 6.11.24 Platform Product Team.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3hNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e623ec166ac6bc3fadc092f8d87996a98d26fbe/Slide%206.11.24%20Platform%20Product%20Team.pdf)
