### ISSUE TITLE
[CDP] Finalize VBA Payment History mock ups - Phase 1

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#84646]
## Description

As part of the payment history work for VBA, we need to create mockups that clearly show a debt's given payment history based on the data defined in #83617.

Given: A veteran wants to see their most recent payment history
When: A veteran looks at their copay bill in the CDP
Then: They should be able to see clearly what their payment history is for a given copay.

## Tasks
- [x] Meet with Stakeholders 06/06/24
- [x] Finalize mockups for payment history on the overpayment summary page
- [x] Annotate mockups for handoff

## Acceptance criteria

- [x] Mockups refined and finalized
- [x] Mockups have been annotated for a11y and dev handoff. 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
Additional use cases have been added to the Payment History mockups:

- [Paid off debt](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1993-41891&t=XBI9XpwoFsjO9TPe-11)
- [Benefit offset
](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-31768&t=XBI9XpwoFsjO9TPe-11)
- [Referred to treasury](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-32264&t=XBI9XpwoFsjO9TPe-11)

**Comment by mgleo** [comment]
Phase 1 mockups are complete and have been annotated for FE Handoff [#86212](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/86212)

Phase 2 mockups: We received additional feedback from Platform during Design office hours on 06/18 and will be updating these mockup

**Comment by Tom-Davis** [comment]
@amponce I believe the 1.0 versions are complete and the 2.0 are being revised. @josephrlee @mgleo can you please confirm?

**Comment by mgleo** [comment]
@Tom-Davis @amponce 
That is correct. Phase 1 is complete [#86212](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/86212)

Phase 1 MVP: Overpayment summary page and detail page:
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-17591&t=yCqrWzggTvn2bMBb-1

**Comment by josephrlee** [comment]
I think this ticket can be closed. I relabeled it just pertain to phase 1. 

Here are the finalized versions ready for dev-handoff now: https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-17591&t=h63cmiDoQmXmMEeH-11 

I'll create a phase 2 version of this ticket now.

cc: @mgleo @charlottecesana @Tom-Davis @HeatherRienks @denisecoveyduc
