### ISSUE TITLE
Identify Revproxy vs. Nonrevproxy Related OOB Deploys

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#84643]
## Description 
We are identifying how many OOB deploys were Revproxy vs. Non-Revproxy related. 
---

## Definition of Done
All tasks below are completed. 
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Lindsay to separate OOBs submitted by sitewide facilities team which are revproxy and not revproxy.
- [x] Lindsay to communicate that in this ticket and with team
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
Of the 26 Sitewide OOB requests pulled :

- 17 are redirects / revproxy
- 9 are emergency OOBs
