### ISSUE TITLE
[ANALYTICS] Recreate Data Collection Document to be as Kick-off and Data Automation Document [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8465]
## Story
As a PAO and Drupal engineer, I need a data collection document that is easy to review and make confirmations, so the data can easily be automated into data loading in the Drupal system.

## Goal
_Provide an easy to understand and easy to fill out/confirm spread sheet to the PAOs to provide pertinent information needed to complete the multiple layers of the VAMC-Upgrade_

## Objectives or Key Results this is meant to further
- _Increase System page completion each quarter_
- _Increase velocity overall through business optimization_

## Resources - Tools - Documentation
[VISN_4_Content_Stack](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[VA.gov_Medical_Center_Map_Moqup](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9)
[VISN-19 Rocky Mountain VISN](https://www.va.gov/directory/guide/region.asp?ID=1019)

## Tasks
_Complete the following tasks for this Story:_
- [ ] Review/Compare Data collection documents against required drupal data load.
- [ ] Modify document to reduce/eliminate/align: Data points, Data redundancies
- [ ] Process to create .csv file information from Playbook
- [ ] Process to create .csv file information from Facilities data
- [ ] Process to create .csv file from caregiver page information

## Acceptance Criteria
Items that must be validated to be fully accepted and story closed:
* Process to create or an updated .csv file information from Playbook
* Process to create or an updated .csv file information from Facilities data
* Process to create or an updated .csv file from caregiver page information
