### ISSUE TITLE
STS documentation updates

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#84671]
## Tasks

- [x] more basics on public/private key & encryption basics?
- [x] further clarity on `Authorization: Bearer <token>` format.
- [x] how to validate STS/regular tokens via `https://staging-api.va.gov/sign_in/openid_connect/certs`
- [x] integrate https://github.com/department-of-veterans-affairs/va.gov-team/pull/88069#pullrequestreview-2175018955
  - [x] update `/token` documents to remove end-user & STS information, link to corresponding `/token` document
  - ~~[ ] pull STS auth postman into main identity postman~~

**Comment by parkerbees** [comment]
@bramleyjl it looks like this was moved to "in progress" a month ago - is this still actively being worked? Thx.

**Comment by bramleyjl** [comment]
@parkerbees some of this is covered in the recent updates @rileyanderson made to [split STS auth into its own section](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/Authentication%20Types/Service%20Account%20Auth%20(STS)) in the documentation.

I'm reviewing this and #72793 to see what still should be done and working on them as my main item today.

**Comment by parkerbees** [comment]
Fantastic - thanks, @bramleyjl ! I appreciate the update.
