### ISSUE TITLE
Document Facility Locator design specs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8467]
## User Story or Problem Statement
How might we document the design specifications for Facility Locator as a reference for current and future work?

## Goal
Documentation of size, format, font and color specs used on Facility locator search page and in Facility detail pages

---
## Tasks
Add to [Punchlist document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/design/facility-locator-punchlist.md) for layout of Facility Locator search page indicating 

- [ ] Components
- [ ] Fields
- [ ] Styling
- [ ] Font sizes 
- [ ] Color specs
- [ ] Reference to design system components where applicable
- [ ] Indicate where current implementation is inconsistent with VA.gov or design system
- [ ] Expected behavior
- [ ] Other pertinent design specs

Add to [Punchlist document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/design/facility-locator-punchlist.md) for layout of Facility Locator detail pages indicating 

- [ ] Components
- [ ] Fields
- [ ] Styling
- [ ] Font sizes 
- [ ] Color specs
- [ ] Reference to design system components where applicable
- [ ] Indicate where current implementation is inconsistent with VA.gov or design system
- [ ] Expected behavior
- [ ] Other pertinent design specs

## Acceptance Criteria
- [ ] All design specs are documented for facility search page and detail page layouts
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@thejordanwood Do you feel like the Sketch library covered this? Maybe something to think about as the new designs are finalized - how to make sure they are fully documented
