### ISSUE TITLE
Document design specs for VAMC left Nav 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8468]
## User Story or Problem Statement
How might we document the design specifications for VAMC left navigation menu as a reference for current and future work?

## Goal
Documentation of size, format, font and color specs used on VAMC left navigation menu 

---
## Tasks
Create document with layout of VAMC left navigation menu indicating 

- [ ] Height and width of all components
- [ ] Height and width of all padding 
- [ ] Height and width of all fields 
- [ ] Font sizes 
- [ ] Color specs
- [ ] Reference to design system components where applicable
- [ ] Indicate where current implementation is inconsistent with VA.gov or design system
- [ ] Other pertinent design specs

## Acceptance Criteria
- [ ] All design specs are documented for VAMC left navigation menu

**Comment by davidmpickett** [comment]
If this is in Skethc, then we're good @thejordanwood ?

**Comment by thejordanwood** [comment]
@davidmpickett  This is the [VAMC Sketch file](https://www.sketch.com/s/8bda90fd-99e8-4761-9210-3a24282eb811), but it appears that the left side nav is slightly different than what's on VAMC pages right now. The side nav in the Sketch file shows the current design that's [in the design system](https://design.va.gov/storybook/?path=/docs/components-sidenav--default-story), which doesn't align with [VAMC pages](https://www.va.gov/new-york-harbor-health-care/health-services/). 

I've explored some other Sketch files and can't find where the new side nav originated. I would have to ask around/ do more research to figure this out.
