### ISSUE TITLE
Discovery for VA-facing form “Employment History” requirements

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-team#84701]
In order to understand how forms are built, create a Veteran-facing form for Employment History using the standard form patterns and components created by the VA forms team.

Initial form is [Employment History](https://www.figma.com/design/3oVfjCBgqfwBN6CJB75kox/Form%3A-VBA-21-4140-ARE-Employment-Questionaire?node-id=22-6294&t=Gx2cjC79eh72jqrr-1):

### Acceptance criteria
- [ ] A figma design file for [Employment History](https://www.figma.com/design/3oVfjCBgqfwBN6CJB75kox/Form%3A-VBA-21-4140-ARE-Employment-Questionaire?node-id=22-6294&t=Gx2cjC79eh72jqrr-1):  that includes the standard layout and structure defined by the VA-facing forms team 
- [ ] [A list of questions/assumptions](https://docs.google.com/spreadsheets/d/19iNEGGWyOLxSiZUmfrkovaVp_qiZS-djJ4STFzmq-qM/edit#gid=0) 
   - [ ] Identify form elements, if any, that do not fit into any current standard forms patterns and may require customization
   - [ ] Questions/assumptions around the attributes for form patterns and components editors will need to manage within the form engine 
   - [ ] Additional editor experience questions that may impact how editors will interact with a form engine in Drupal

### Tasks
- [ ] Review VADS components, Veteran-facing form patterns and design files form forms already digitized to understand
- [ ] Mockups of Veteran facing forms using current patterns in the VADS for personal id and contact information
- [ ] Cross compared with the[ Multiple page list and loop pattern ](https://www.figma.com/design/OxzngjwHg4n0oNSGHkwJ5Z/DSC---WIP---Pattern---Multi-page-List-and-Loop?node-id=534-60060&t=JSfV2mLmmk0wVAbR-1)recommended by Matt to see if this pattern will work for the employment certification section
- [ ] Ongoing sources of information
   - [ ]  Intro discussion with VA-facing forms team
   - [ ] weekly with Matt Dingee
   - [ ] Async discussions on Slack form engine channel
```
Additional info/potential questions
- Criteria to determine if list and loop pattern meets feature, usability and technical requirements?
- Criteria to determine if a form pattern meets the specific needs of this form 
- Documentation?

**Comment by cjterdi** [comment]
Not sure if the details about the Employment history form should be in it's own story?
