### ISSUE TITLE
[BE] Modify travel_claims/client to add claim_status api call

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#84754]
## Description
Add claim_status api method in travel_claims/client class

Note: Define `claim_status` api with below parameters,
```
token
patient_icn
appointment_start_date
appointment_end_date
```

## Tasks
- [x] [BE] **Implement claim_status api method**
- [x] [BE] **Add rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
