### ISSUE TITLE
[BE] Implement claim_status method in travel_claims/service 

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#84755]
## Description
Implement claim_status method in travel_claims/service 

Note: Calculate the appointment end date from the TravelClaim::Service.appointment_date  

## Tasks
- [ ] [BE] **Implement claim_status method**
- [ ] [BE] **Calculate appointment end date from TravelClaim::Service.appointment_date** 
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
