### ISSUE TITLE
[DESIGN] SPIKE: Explore how to add VAOS appointment list to landing page

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#84751]
## Background

Our landing page pivot, if the direction is approved, will show VeText (Today's) appointments instead of the VAOS (Upcoming) appointments as we work to get the VAOS list data.

We know how the VeText list will be added ([Designs](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1353-37282&t=ft0ylg17iVdtvjQS-1)). For the next step, we need to determine how VAOS appointments will be integrated once that list is ready. 

Something to consider is if/how to keep the CTA and status capabilities of the VeText (Today's) appointments while adding the ability to view all upcoming VAOS appointments.

Options:
	• VAOS (Upcoming) appointments replacing VeText (Today's) appointments 
	• VAOS (Upcoming) appointments are added along with VeText (Today's)

[Preliminary design options](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1353-38165&t=ft0ylg17iVdtvjQS-1)

## Tasks
- [ ] Review options and add any new ones
- [ ] Review with UX and FE
- [ ] Decide on direction

## AC
- [ ] Options reviewed with UX and FE
- [ ] Direction decided and documented
