### ISSUE TITLE
[BE] Move statsd metrics & vanotify template ids to common constants class

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#84758]
## Description
Move [statsd metrics & vanotify template ids](https://github.com/department-of-veterans-affairs/vets-api/blob/560e166ba0b4c016a6b09270910f20c920b0e4f9/modules/check_in/app/sidekiq/check_in/travel_claim_submission_worker.rb#L12-L40) to common constants class

## Tasks
- [ ] [BE] **Create new class for defining statsd metrics & vanotify template ids**
- [ ] [BE] **Modify `travel_claim_submission_worker` to use the constants from new class**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
duplicate, closing
