### ISSUE TITLE
[BE] Create new worker for travel claim status check to call claim_status api

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#84763]
## Description
Create new worker for travel claim status check to call claim_status api

## Tasks
- [ ] [BE] **Create new travel claim status check worker with `uuid` & `appointment_data` parameters**
- [ ] [BE] **Read icn, station_no and facility_type from redis**
- [ ] [BE] **Build TravelClaim::Service class with check_in_session and appointment_date**
- [ ] [BE] **Call claim_status method in travel_claim/service class**
- [ ] [BE] **Log error message in worker if there are more than one claim_status received, to monitor in dashboard**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
