### ISSUE TITLE
Address content changes to FDC question

### ISSUE THREAD

**Issue by Kate-allbee** [department-of-veterans-affairs/va.gov-team#84766]
## Epic Description
As a Veteran, I want to be able to understand clearly the difference between a fully developed claim and a standard claim process. 

Finding from 526 Paper Form Sync Audit: Row 04 [Sharepoint Link](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B3308EE26-A184-42ED-AFC0-44B1D20F12A6%7D&file=526%20paper%20sync%20audit%20.xlsx&action=default&mobileredirect=true)

Revisiting the FDC question which was recently brought back into the 526 form flow. 

Scope - 
The FDC question fulfills Box 1 from the PDF, however the two experiences are different in information presented: 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDg0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0dd22f20960f25362fec3745a8aaafd3e023f65/image.png" alt="image.png" />

<img width="1287" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUE0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42fae3e611c9fd01a048c022d4107570438072b4/image.png" alt="image.png" />

How can we bring these two experiences into parity, and give the Veteran a better understanding of Fully Developed Claim Program vs. Standard Claim Program? And how can we make sure the information presented on the FDC question is most relevant to this part of the form?

## Tasks
- [ ] Evaluate link destinations of the FDC question
- [ ] Evaluate a change in content to show information about the Standard Claim Process more up front
- [ ] 

## Acceptance Criteria
- [ ] Parity between the paper and digital experience of this question

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
