### ISSUE TITLE
QA design staging review: Left Nav

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8476]
## Problem Statement
How might we ensure that the developed UI to upgrade the Left Nav menu is consistent with design spec? 

## Goal
Ensuring consistency between design spec and development before release

## Objectives or Key Results this is meant to further
Objective 2: Deliver meaningful facility information

## Tasks
- [ ] Review and compare the most up-to-date UI merged to staging with design spec 
- [ ] Meet with the frontend engineer/ PM to review any needed changes
- [ ] Document meeting notes in this ticket
- [ ] Create tickets for FE as needed

## Acceptance Criteria
- [ ] Differences between development and design are documented and understood
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@rtwell Design changes now available in staging: https://staging.va.gov/pittsburgh-health-care/

**Comment by rtwell** [comment]
**On desktop:**

1. It looks like some items in the Nav are getting underlined—none of them should be underlined. 
2. When a user is on a parent page (e.g. "Locations"), that page should no longer be clickable (because the user is on that page).
3. Every parent section should have a rule at the beginning and end of the section when they are expanded [as seen here](https://zpl.io/25v59DW).
4. When i click a parent page that I am not on, the menu expands for a second before the entire page loads—it should load the page first.
5. Section titles "SERVICES AND LOCATIONS", "NEWS AND EVENTS", and "ABOUT VA PITTSBURGH" should not be interactive. 
6. Borders for all states should should overlay the border for the nav, on staging the borders are inset.

**On mobile**
All visual references for mobile can be [viewed on Zeplin](https://app.zeplin.io/project/5e625bf558043e13a45e4737/dashboard?seid=5e7bac810cd7198ffc0d5c94).

1. The entire nav is flush left with the viewport—it should be centered
2. The hover state remains present when I scroll—there should be no hover state on mobile
3. “More in this section” is still present at the bottom of the Nav
4. On page load, the navigation should be collapsed
5. Whenever I click a link in the side nav to navigate to a page, there is a blink of dark color on-tap. The desired behavior is to only display the “on-click” state.
6. When collapsed on mobile, the side nav should appear below the H1 on the page.

We'll need another round of review/polish once these changes are implemented. @mmiddaugh  

I suspect I'll need to alter the "section" design, be we can tackle that afterwards.

**Comment by ethanteague** [comment]
@mmiddaugh @rtwell @brangi 
I've pushed fixes for mobile items 1-4.

Wrt #5: When inspecting the style for click (active state), the background color isn't changing. I think what might be happening here is that the border is a bit too thick / dark, and is creating a feeling of background appearance change. Maybe we should have a play with lightning up the the active state border?

Wrt #6: This is a biggie. We have a a couple dozen places (templates) that would need to be refactored to move the h1 above the sidebar nav, in addition to refactoring styles. I tried implementing a hack to move the h1 above the nav on page load in mobile state, but this creates a jarring jump when the h1 moves right as the page completes loading. Fwiw, my hack solution looks like this: 
```
/**
 * Adds event handler to move mobile sidebar nav below h1.
 */
const mobileMediaQuery = window.matchMedia('(max-width: 767px)');

export function headerNavSwitch() {
  const header = document.getElementsByTagName('h1')[0];
  const mobileNav = document.querySelector('.va-sidenav');

  if (mobileMediaQuery.matches) {
    header.after(mobileNav);
  }

}

document.addEventListener('DOMContentLoaded', headerNavSwitch);
```

So, I just wanna confirm that #6 is a must do before we go down this road - gonna require us to take our time to get this right.

**Comment by rtwell** [comment]
for Mobile #5: what you are not seeing (i think) is on a mobile device (i.e. not using desktop and inspecting) the hover state is appearing as I tap and scroll, which is not the desired behavior. does that make sense?

Mobile #6: we can keep the placement (above the h1) for now.
