### ISSUE TITLE
[BE] Check for success & failure status from claim status api

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#84764]
## Description
Check for success & failure status from claim status api in claim status check worker

**Successful statuses:**
[`Approved for Payment`,`Claim Paid`,`Claim Submitted`,`In Manual Review`,`In-Process`,`Submitted for Payment`,`Saved`]

**Failure statuses:**
[`Appeal`,`Closed with No Payment`,`Denied`,`Fiscal Rescinded`,`Incomplete`,`On Hold`,`Partial Payment`,`Payment Canceled`]

## Tasks
- [ ] [BE] **Handle the claim_status api response**
- [ ] [BE] **Implement logic to identify claim status from above status**
- [ ] [BE] **Notify veterans with appropriate error messages based on the status**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@kanchanasuriya are we finishing this today?

**Comment by kanchanasuriya** [comment]
> @kanchanasuriya are we finishing this today?

Yes Lori, have a couple of PR comments to address & push the changes
