### ISSUE TITLE
[BE] Update travel claim submission worker to enqueue claim status job on BTSSS timeout

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#84765]
## Description
Update travel claim submission worker to enqueue claim status job on timeout

## Tasks
- [ ] [BE] **Remove vanotify call sending sms for longer than expected to veteran**
- [ ] [BE] **Update travel claim submission worker to enqueue claim status job on timeout**
- [ ] [BE] **rspecs**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by loripusey** [comment]
@randomsync @kanchanasuriya will this be completed by end of sprint or be rolled over?
cc: @anita-halici
