### ISSUE TITLE
Engineering | Profile | Mockingbird | Clone Mock Response

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84777]
As a user, I want the ability to clone a mock response from any other mock user in the system to a mock user that is assigned to my team, so I don't have to create a mock response from scratch.

## Background

Initially mock responses could be shared by multiple mock users.  After further consideration, it will simplify management if each mock user has it's own set of mock responses, and provide the ability to copy mock responses between them.

## Tasks

- [ ] Add UI for cloning a mock response.
- [ ] Record the mock response source.

## Acceptance Criteria

- [ ] User can clone a mock response from a mock user assigned to a different team.
- [ ] User can clone a mock response from a mock user assigned to same team.
- [ ] The details of the mock response show which mock response it was copied from.

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
