### ISSUE TITLE
Engineering | Profile | Mocking Bird | Add API Authentication

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84773]
## Background

As an administrator, I want to authenticate API requests, so that only authorized clients may use the tool.

Each user or team will get an access key which is available to them from the website.  They will need to include this key in the header of any request sent to the tool.  Any requests that don't have a valid key will be rejected.

## Tasks

- [ ] Add API authentication (needs more detail).
- [ ] Add API key infrastructure.
- [ ] Add API key management for a user.
- [ ] Add API key expiration?

## Acceptance Criteria

- [ ] A user is able to view, add, remove access keys.
- [ ] A user is able to copy an access key.
- [ ] A user is authenticated if their request contains a key.
- [ ] Instructions are provided for adding the key to vets-api outbound requests.

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
