### ISSUE TITLE
Engineering | Profile | Mockingbird | Team Endpoint Assignments

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84776]
## Background

As a user, I want to be able to assign endpoints to my team, so it is easier to understand the endpoints we are responsible for testing.

This will also provide a team dependency map by API endpoint.

### Tasks

- [ ] Build UI for assigning endpoints to a team.
- [ ] Build UI for viewing assignments by team.
- [ ] Build UI for viewing assignments by endpoint.

### Acceptance Criteria

- [ ] Users can assign endpoints to their team.
- [ ] Users can view assignments by team.
- [ ] Users can view assignments by endpoint.

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
