### ISSUE TITLE
Engineering | Profile | Mockingbird | Simplify Routing Rules

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84771]
## Background

As a developer, I want to simplify the routing rules, so that the system will be able to find any new mock responses without the need for code updates.

Initially, a mock response could be shared by multiple mock users, which required more complex routing logic.  Mock responses can no longer be shared; instead they can be easily copied or cloned between mock users.

## Tasks

- [ ] Update models and relationships.
- [ ] Update seed data.
- [ ] Update routing logic.
- [ ] Update affected controllers.
- [ ] Update affected views.
- [ ] Update specs.

## Acceptance Criteria

- [ ] Write specs for all existing endpoints.
- [ ] Document how incoming requests are processed.

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
