### ISSUE TITLE
Engineering | Profile | Mockingbird | Add Teams

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84774]
## Background

As a user, I want specific mock users to be assigned to my team, so that they aren't unexpectedly changed by someone outside of our team during testing.

This feature will help organized managing mock users.  Each user will be assigned to a team.

## Tasks

- [ ] Build Team model
- [ ] Build Team UI for managing teams
- [ ] Seed data

## Acceptance Criteria

- [ ] User can manage teams (view, add, update, delete)

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
