### ISSUE TITLE
Engineering | Profile | Mockingbird | Relay and Record Logged Request

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84779]
## Background

As a user, I want the ability to forward a request to staging, so that I can view and save the response.

The tool will log all incoming requests.  A user should be able to view any request, forward it to another environment such as staging, view the results, assign it to an endpoint and a mock user, and finally save it.

## Tasks

- [ ] Build UI for viewing team requests.
- [ ] Build UI for forwarding request to staging.
- [ ] Build UI for viewing results, and assigning a mock user and endpoint.
- [ ] Build save functionality

## Acceptance Criteria

User can:
- [ ] Viewing all team requests.
- [ ] View request detail.
- [ ] Forward request to staging.
- [ ] Viewing results, and assigning a mock user and endpoint.
- [ ] Save request.
