### ISSUE TITLE
Team | Profile | Mockingbird | Setup Instructions

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84770]
## Background

As a user, I want access to instructions documenting how to install the tool, so I can configure a local VA.gov instance with minimal effort.

## Tasks

- [ ] Add instructions to the README file of the repository so that provides steps for installing locally. 
- [ ] Include contacts to call for setup help?

## Acceptance Criteria

- [ ] Review with team.

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
