### ISSUE TITLE
[Design] Higher Level Review: Changes from AMO Meeting

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#8477]
### Description

Per our last meeting with AMO, some changes to the HLR designs need to be made. As a designer, I need to make these changes and upload them to Invision so they can be viewed by our team and AMO.

### Tasks

- [x] All 'Need help?' footers have been changed to whatever our standard is for this section
- [x] Contested Issues - 'didn't see the issue you were looking for?' has the new COVID-19 language (provided by AMO)
- [x] Contact info - address and basic contact info has been changed to view only in the design

### Acceptance Criteria

- [x] the above tasks have been satisfied
- [x] Changes have been made in Sketch
- [x] Changes have been pushed to Invision

**Comment by kevinstachura** [comment]
Changes can be viewed here: https://vsateams.invisionapp.com/share/W5U21BDFTQK
