### ISSUE TITLE
Engineering | Profile | Mockingbird | Add User Authentication

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#84772]
## Background
As an administrator, I want to users to have to authenticate, so that only authorized users may use the tool.

Adding user authentication will provide other benefits such as: team assignment, mock user ownership, and usage statistics.

## Tasks

- [ ] Determine authentication mechanism (email, Github, etc).
- [ ] Add authentication (add more detail).
- [ ] Add invitation feature (might need to be in another story).

## Acceptance Criteria

- [ ] Unauthenticated user cannot use the system (all requests are redirected to login page).
- [ ] User can sign in with proper credentials and use the system.

**Comment by tpharrison** [comment]
VES Experience team added mocking to their tool, so no further development is needed.
