### ISSUE TITLE
VSP Review of Caregivers 1010CG Prototype

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#8479]
## Steps to complete Staging Review: 

- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline [Caregivers Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/release-plan.md)
- [Link to prototype](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens) 

## Meeting attendees from **Caregivers**
- Product Manager (required): **Alayna**
- DEPO product lead (required): **C.C. Gong**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Justin Linn, Kevin Mircovich, Jonathan Nelson, Patrick Sanders**

## Scheduling
Preferred dates or times: Already scheduled!

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by meganhkelley** [comment]
Per conversation with Caregivers team — this Staging Review has been changed to a Prototype Review (prototype linked in body of issue). The team will complete an actual staging review later on (timeline TBD, will be set by 5/1). 

Reviewers — please document feedback in tickets attached to this epic as usual.

Reviews will be completed by content, design, and accessibility. 

IA I am checking with Mikki, and QA I am checking with Peter and Tze.

Staging link (still in development!) for reference: [Staging Link](https://staging.va.gov/caregivers/)

**Comment by meganhkelley** [comment]
Update: As part of this review, Tze will work with the team to provide QA feedback on the development that is in progress. Mikki will provide IA feedback on the prototype.

**Comment by mnorthuis** [comment]
IA feedback:
- This form will not live within the Health care hub, so the breadcrumb in the prototype is incorrect.  Breadcrumb and URL info is provided in the IA info: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/caregiver-10-10cg.md

**Comment by meganhkelley** [comment]
Product feedback (no required action, recommendations only): 

KPIs: 
- "How many applications are successful vs. unsuccessful" — how do you define success?
- "Qualitative metrics" — do you have an expectation of when/how this will be gathered? 

Business value: 
- Application processing time and rejection rate (?) — could these also be KPIs? Do you have baselines here? 

Please reach out to @joanneesteban for additional support on KPIs as needed! 

Lastly, in your [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md), don't forget to include actual screenshots along with the links.

**Comment by peggygannon** [comment]
Content feedback is capture in this ticket:  

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8565
