### ISSUE TITLE
Standardize definition, tracking and documentation of VSP Products

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#8482]
- [x] Assemble comprehensive, point-in-time List of Products
- [x] Define more clearly when something is a "Product" and when it is something else (an "Initiative", etc.)
- [x] Define minimum expectations, including templates, for Product documentation in `/platform/products`

**Comment by rroueche** [comment]
Initial draft list, meta data up for discussion! But here's a starting point: https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0
