### ISSUE TITLE
Staging Review [VAMC Left Nav]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8485]
## Steps to complete Staging Review: 

- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [X] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- [x] [Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-left-nav-enhancement-feature-brief.md)
- [x] Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/fe-templates/left-nav/release-plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- [x] Access information for the tool or feature in [staging](https://staging.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/)
  - This area is unauthenicated - no user credentials are needed. 
  - https://staging.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
- [x] Link to your product test cases/test plan in [TestRail](https://dsvavsp.testrail.io/index.php?/plans/view/225) and [#8743](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8743) _for QA practice area review_
- [ ] Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_

Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.
- [x] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) (required)
- [x] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) (recommended)
- [x] Conduct axe browser scan, and document or address issues found (required):
   - **AXE noted a contrast error for design system component**
- [ ] Ensure end-to-end tests - including the axe check, pass (required)
- [ ] Add keyboard end-to-end tests in CI/CD test runs (recommended)
- [x] Conduct axe-coconut browser scan, document or address issues found (recommended): 
**- AXE coconut noted landmark issue for footer and landmark role needed for transportation area of page (separate from left navigation menu)**
- [x] Test with WAVE tool (recommended): 
**- Passed**
- [x] Check color pairing for proper contrast (required): 
**- Passed**
- [x] Check for colorblindness issues (required): 
**- Passed**
- [x] Zoom to 200% and confirm readability, no info cut off, etc (required) 
- [x] Repeat for 300% (required) 
- [x] Repeat for 400% (required)
**- Comment left for Jennifer.** 
- [x] Navigate all pages and core functionality with keyboard only (required)
**- Passed**
- [X] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox (required)
**- Comment left for Jennifer.** 
- [x] Known Issues
   - [Breadcrumb logic for some content types](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1238)

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO product lead (required): **Dave Conlon**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Gibran Rodriguez, Engineer**
**Ryan Thurlwell**

## Scheduling
Preferred dates or times: 
- Tuesday, May 12 at 11 - 11:30 ET 
- Thursday, May 14 at 2 - 2:30 ET
- Friday, May 15 at 2 - 2:30 ET
- or...is async an option? 

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by mmiddaugh** [comment]
![wave contrast for left nav](https://user-images.githubusercontent.com/55411834/81125232-cf577080-8ef4-11ea-921b-1ca61ff3b245.png)

![wave errors for left nav](https://user-images.githubusercontent.com/55411834/81125237-d2526100-8ef4-11ea-8b73-963f1176f5ea.png)

**Comment by mmiddaugh** [comment]
@jenstrickland....I noted the following during my staging pre-review testing but am not sure if these are serious defects. 

- When zoomed to 200% or higher, the left nav menu moves above the page content. 
- The menu items are off center within the outside border and the border is flush with the left side of the page. This also impacts the focus halo. All content is still visible and can be navigated by keyboard but the aesthetics are just not as good. 

![image](https://user-images.githubusercontent.com/55411834/81345082-140a1580-9075-11ea-8036-e63301d7f1e5.png)

![image](https://user-images.githubusercontent.com/55411834/81345270-64817300-9075-11ea-8202-0ee106e156fe.png)


 - NVDA does not read the headings of the sections (ie ABOUT VA PITTSBURGH). The list and number of items are announced but if the parent is expanded, the child pages are visible on screen but not announced unless they are active. What is the expected behavior for this navigation?

**Comment by jenstrickland** [comment]
- Regarding the focus outline **should** appear around all sides of the focused content, and would be a 508-defect-3 in the current state where the left side is cut off.

- I just pulled it up in NVDA + Firefox and it read the level 2 headings for Services and Locations, News and Events, and About VA Pittsburgh. 

I do see that the `aria-current="page"` isn't yet on the active link in the nav list, yet.

**Comment by mmiddaugh** [comment]
Thank you, @jenstrickland, I'll have Ethan and Gibran take a look!

**Comment by meganhkelley** [comment]
@mmiddaugh product feedback — as I mentioned, no validation of changes required:

- Your Feature Brief link above is broken 
- Re: your release plan, are you planning a soft rollout? If not, why? We do recommend using a soft rollout plan using a feature toggle (improvements to release plan guidance coming soon!)

**Comment by mmiddaugh** [comment]
@meganhkelley sorry about the broken link. Please try this one: 
[Feature Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/fe-templates/left-nav/vamc-left-nav-enhancement-feature-brief.md)

Regarding soft launch: I think this release was viewed as a bit of a soft launch as it will not affect all VAMC websites (or users) - only the Pittsburgh health system users. We also planned to go full launch mode because 
- Pittsburgh stakeholders have been waiting on this upgrade. Phasing the release has not been part of the conversation to this point. 
- this left nav is a dependency for future VAMC rollouts by the VAMC upgrade team
- it's an enhancement to existing functionality which is based on usability feedback 
- it's low risk for users (ie: it's not a form which might have errors or similar fail)

Having said all of that, we're aware of the Feature toggle. We discuss it as a team routinely but just haven't found the right opportunity to apply it to a release.

**Comment by mnorthuis** [comment]
IA Feedback:

1) For some L3 content that is hidden in the left nav, the left nav is still displayed on the page but the left nav no longer has a "you are here" indicator.   Examples: 
  - https://staging.va.gov/pittsburgh-health-care/women-veteran-care/ 
  - https://staging.va.gov/pittsburgh-health-care/internships-fellowships/forms/
FYI, these URLs do not reflect that these are L3 pages - their breadcrumbs are accurate but URLs are not

2) The "Home" portion of the breadcrumb disappears on some pages, but not all.  For example, it is not shown Health services and Locations pages, but does appear on Events and About us. 

3) The L2 options in the left nav do not have hover states when they are expanded to show L3 items, but they do have hover states there are no L3s to show.
  - Example of no hover state on "About us" https://staging.va.gov/pittsburgh-health-care/about/
  - Example of hover state on "Policies" https://staging.va.gov/pittsburgh-health-care/policies/

4) For content that is at the top level of the VAMC site, and not part of a "spoke", there is no "You are here" indicator in the left nav.  The left nav should be designed to accommodate this, or it should be removed, or the IA should be reviewed for these pages. 
- Example: https://staging.va.gov/pittsburgh-health-care/make-an-appointment/

**Comment by rtwell** [comment]
I concur with 1, 2, and 4.

for 3: when a user is on a page, that page in the side nav should not be clickable or have a hover state (because the user is on that page). I believe this is how the main nav on VA.gov currently behaves. in the examples you gave, "About us" is correct, and "Policies" is incorrect.

**Comment by mmiddaugh** [comment]
@mnorthuis @rtwell 
Followup question: 
For L3 content hidden from the left nav - is the expectation that 

1. the left nav is no longer displayed or 
2. that it is displayed and has the you are here" indicator? 

What is the recommended resolution for the content that is at the top level of the VAMC site and not part of a "spoke"? there is no "You are here" indicator in the left nav. 

1. Design the left nav to accommodate "you are here" 
2. Remove the content?
3. Or review the IA? 

The resolution of these issues currently blocks our move to Prod so I appreciate your guidance for "now" and "later" approaches if appropriate.

**Comment by mmiddaugh** [comment]
@mnorthuis and @rtwell  in addition to the questions above, one more for you:
Regarding the "Home" breadcrumb: should the user be taken all the way back to VA.gov landing page or to home for Pittsburgh?

**Comment by mnorthuis** [comment]
"Home" should take you to va.gov home page.   The "Pittsburgh health care" option goes back to the health care system primary page.

**Comment by mnorthuis** [comment]
@mmiddaugh @rtwell were the issues above ever discussed?

My preference would be to always keep the left nav on the page, but not sure if @rtwell has other ideas here...

**Comment by rtwell** [comment]
I think we're having the same convo in two places:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9380
