### ISSUE TITLE
Complete design for "Give Vet clear expectations of claim status"

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#84850]
As a team member, I want to finalize the design, taking into consideration technical feasibility, for giving Veterans clear expectations of claim status, so that I can implement the improvements into the 526 form experience.

## Acceptance Criteria
Scenario: UI changes that improve UX are not finalized with consideration given to feasibility
* Given the designs are not finalized
* Then finalize designs, with consideration given to technical feasibility of implementation

## Tasks
- [x] Develop user flow
- [x] Create wireframes (if needed)
- [x] Determine engineering feasibility for design direction - captured in [Technical Discovery for "Give Vet clear expectations of claim status"#85955](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85955)
- [x] Review design with OCTO - [scheduled for 6/21](https://dsva.slack.com/archives/C053UDWMH7U/p1718223085300419)
- [x] Incorporate edits from Midpoint review, Figma comments, [slack](https://agilesix.slack.com/archives/C04MJV66ZPC/p1718893865902949?thread_ts=1718887314.314119&cid=C04MJV66ZPC)
- [x] Complete high fidelity design
- [x] Accessibility annotations on design
- [x] Make ticket for us to create CAIA intake request on content, after VFF research findings come in (per [plan in Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1718992973715589?thread_ts=1718654600.232579&cid=C053UDWMH7U)) -  Incorporate VFF research findings and CAIA feedback into design for Timely and Truthful Submission #87563 

## Working material

[page in Figma](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/Submission-Experience?node-id=5626-129729)

## Background and additional context
* In scope: For **all scenarios** in which we would reflect something unique in the UI of confirmation page, work directly related to "Give Vet clear expectations of claim status" as described in the [Submission Experience user story map ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715268744654/29695ef6a1327d51f1b2daaa0f26a3f09cb7fedd?wid=0-1653594055660&sender=ubd79255de28cd574d7575469)
* Out of scope: All work unrelated to "Give Vet clear expectations of claim status", as described in the [Submission Experience user story map ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715268744654/29695ef6a1327d51f1b2daaa0f26a3f09cb7fedd?wid=0-1653594055660&sender=ubd79255de28cd574d7575469)
* Guidance on user flows [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
* 

## Proposed Design Changes
Related user story: [Set expectations for what will happen when I click submit](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85444)
As a Veteran I want language on the review and submit page that explains what will happen next so that I have clear expectations about what will happen.

Acceptance Criteria:
Copy update on review and submit screen that gives Veterans next steps for the submission process

---
Related user story: [Feel confident that VA is trying to submit your claim](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85449)
As a Veteran, while I wait for my submission to process, I want to feel confident that something is happening while the submission screen loads. 

Acceptance Criteria
- Copy is updated to be be more timely & truthful
- A countdown timer is added to help the Veteran understand how long it will take to process their submission (30 seconds)
- [Possible/maybe] Adding a visual to show the steps to submission that are happening while the screen loads

---

Related user story: [Receive truthful confirmation that claim has succeeded or failed in UI and email](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85451)
As a Veteran, I want information on my submission as soon as I submit my claim. I expect to receive information on the screen and through email as a record that I can keep. 

Acceptance Criteria
- Design changes to confirmation page
    - Content update to change how we use the word submit and describe the status
    - Move supporting content into accordions
    - Update “What happens next” language to set timeline including when it shows up in the Claim Status Tool
     - Set expectations for two emails (one now, one when submission is complete)  
- Add a new email 
    - Option: Send at the point the record of submission is created in the backend 
    - If successful: No PII/PHI allowed: Date claim was initiated, claim ID, Veteran name, and the “What happens next” 

---

Related user story: [Veteran receives email that claim is received](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/83367)
As a Veteran I want to receive an email from VA when they receive my claim so that I am not confused and left wondering if it was received or if VA just forgot to tell me.

Acceptance Criteria
- Updates to existing email 
    - Do not send email until it is available in the Claims Status Tool 
    - Question on feasibility, not sure if the API is common 
- Update content to match the new submission model (language not yet finalized) 
- Add content about the Claim Status Tool

**Comment by alatempa24** [comment]
Volunteers during sprint planning to help with engineering feasibility - @mchae-nava @christinec-fftc @michael-wojcik

**Comment by mengA6** [comment]
(note to self) vets.gov.user+12@gmail.com has an appeal waiting to be sent to a judge

**Comment by mengA6** [comment]
Asked question about current state of My VA / CST [in Slack](https://dsva.slack.com/archives/C06R2BZKT62/p1718217377796739)

**Comment by evelynhilbrichdavis** [comment]
@mengA6 Can we close this ticket this sprint?

**Comment by mengA6** [comment]
I don't think so. Part of it is accessibility annotations, and I don't think we're ready for that until OCTO's review

**Comment by mengA6** [comment]
for future reference: [Collab Cycle Github Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86117)

**Comment by mengA6** [comment]
Completed midpoint review today. See [Midpoint review milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1326). I'm making some design edits and still awaiting for the accessibility feedback ticket.

**Comment by mengA6** [comment]
Accessibility feedback from midpoint review is in. Still need to address this and some other midpoint review feedback in [the milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1326)

**Comment by mengA6** [comment]
addressed all midpoint review feedback and began accessibility annotations. Should complete this ticket today.

**Comment by mengA6** [comment]
added accessibility annotations [in Figma](https://www.figma.com/design/qyTtKDOTHZPGU59PAfqVhq/Submission-Experience?node-id=5626-130309&t=uGovwdnyFekoxCbu-11)

**Comment by mengA6** [comment]
created  Incorporate VFF research findings and CAIA feedback into design for Timely and Truthful Submission #87563  which will follow this work.
