### ISSUE TITLE
[DevOps] Migrate to Datadog Lambda Extension

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#84957]
## Description
Currently, we're using the Datadog Log Forwarder for general log forwarding. That's fine, but for working with Lambdas, we can benefit from migrating to the [Datadog Lambda Extension](https://docs.datadoghq.com/serverless/aws_lambda/configuration/?tab=datadogcli#migrate-to-the-datadog-lambda-extension).

## Tasks
- [ ] [DevOps] Figure out what is involved in this.
- [ ] [DevOps] Implement whatever IaC is needed to support this.

## Acceptance Criteria
- [ ] Datadog Lambda Extension is supported in `vaec-cie`.
- [ ] Followup ticket(s) opened to support this for each project we have with Lambdas.

**Comment by ndouglas** [comment]
See #86844.

**Comment by ndouglas** [comment]
This was done as a part of the CHIP and LoROTA migrations, but there are some after effects (see #86844).
