### ISSUE TITLE
Concepts ready for scheduling improvements/OH scheduling research

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#84970]
## Task Description

High-level concepts are ready to be prototyped. 

## Notes and references
- [Hypotheses and tasks to test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2024-05-oh-scheduling/hypotheses.md)

## Acceptance Criteria

The following high-level concepts are ready to be moved to hi-fidelity for testing:

- [x] [Oracle Health integration via TOC route](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2509-37009)
- [x] [Oracle Health integration via the “express lane”](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2875-75972)
- [x] [PID improvements](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2598-5816) #82542
- [x] [Tailored and timely urgent medical need alert](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2875-90867) - #60407
- [x] [Notifications on Appointment list page](https://www.figma.com/design/l0z1BKCuXysZeFLIUr2TSB/Notifications-Concept-%7C-Appointments-FE?node-id=1-2)
- [x] Sort by Recent locations

## Deliverables
- [File with concepts](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2001-22465&t=boPeug1P5V3fd2zv-1)

**Comment by outerpress** [comment]
@melissa-lefevre I think this is done but there's one that's not checked off. Can you confirm?
