### ISSUE TITLE
Update the Midpoint Review script

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#85047]
## User Story
As a Governance team member, I want to communicate the goal of the MPR meeting so that all attendees are aware of the meeting purpose and the meeting structure.

As a Governance team member, I want to shorten the time it takes to communicate the goals of the MPR meeting so that our time in the meeting can be used more efficiently.

Assignee: @rferguson13
Peer Reviewer: @erinrwhite

## Description
The Midpoint Review script (which introduces the purpose of the meeting) is old, potentially outdated, and very long. Many of the VFS teams we meet with have heard the script many times before.

The purpose of this meeting is to update and revise the Midpoint Review script. The script goals remain the same as they were previously - have the team share updates since DI, or review product if DI was skipped, Governance team provides feedback and answers questions, and next steps are shared. However in addition to meeting the same goals, we now have a new goal to shorten character count so that it takes significantly less time to read each Midpoint Review meeting. 

## Impacted Artifacts
[Midpoint review touchpoint ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
[Midpoint Review - During the Meeting (Synchronous)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous)

## Tasks
- [x] Draft a new script
- [x] Ensure changes made to the script are aligned with the DI script and SR script, if/when applicable
- [x] Share with Governance team members for review and feedback

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The MPR script has been shortened to roughly half the length it currently is
- [x] The MPR script still communicates the goals of the meeting and shares next steps
- [x] The MPR script is to-the-point, with no duplication of content, and written in plain language
- [x] The MPR script is easy to read for Governance team hosts
- [x] We have published the new script to the operational guidance for Midpoint Review

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rferguson13** [comment]
@erinrwhite - [New Midpoint Review script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3212837321/85047+-+Update+the+Midpoint+review+script) ready for your review!

**Comment by erinrwhite** [comment]
@rferguson13 yes!! SO short. Some comments on the doc for you - one is just a suggestion you can take or leave.

**Comment by rferguson13** [comment]
@erinrwhite Great suggestions. I changed the DI script to reflect the order we give feedback in. One final look-through and we should be good to go.

**Comment by erinrwhite** [comment]
@rferguson13 looking good to share with the rest of the team! 👍🏻

**Comment by rferguson13** [comment]
@erinrwhite - All has been updated. Our[ internal page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639) has the new script and wrap-up. [The MPR Platform page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review) is set to go on Monday. We can either close this out today or you can close it on Monday.

**Comment by erinrwhite** [comment]
Thank you, @rferguson13 ! I will wait for the page to publish Monday and close out the ticket then.

**Comment by erinrwhite** [comment]
[Page on platform website updated](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) 👍🏻 

Closing! thank you @rferguson13 ! Missing you already!
