### ISSUE TITLE
Screenshare Midpoint Review script

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#85048]
## User Story
As a VFS team member partaking in Midpoint Review, I want to see the script that Governance is reading so that I can follow along because I am a visual learner.

Assignee: @allison0034
Peer Reviewer:  @it-harrison

## Description
At the beginning of each Design Intent, Midpoint Review and Staging Review, Governance team reads out a script to ensure that all attendees understand the purpose of the touchpoint, and to ensure we're all on the same page going into the meeting. While the oral reciting of the script is valuable, it was proposed that we also screenshare the script so that individuals who learn best by reading, and not hearing, can ensure they're following along as well.

## Impacted Artifacts
[Midpoint Review - During the Meeting (synch)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous)
[Google Slides - Touchpoint intro screens](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g1f80545f40e_0_0)

## Tasks
- [x] Create a slide, similar to the Design Intent slide, that includes the MPR script as well as Governance team member photos 
- [x] Update operational guidance so that instructions to the Governance MPR host are clear
   - Ensure MPR guidance is in alignment with the DI and SR

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team screenshares the script in the Midpoint Review meeting

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Created slide

**Comment by allison0034** [comment]
@it-harrison both artifacts under the Impacted Artifacts section are ready for your review.

**Comment by it-harrison** [comment]
@allison0034 - looks good to close!
