### ISSUE TITLE
Re-design VFS-facing Midpoint Review guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#85049]
## User Story
As a VFS team member, I want to clearly understand what is expected of me and what I should expect from the MPR meeting so that I can be prepared and ready.

Assignee:  @erinrwhite
Peer Reviewer: @allison0034

## Description
In the research completed by Service Design, it was observed that the Design Intent touchpoint page on Platform Website is overwhelmed with information, making it difficult for VFS team members to easily obtain relevant information from the page. This is shown in [key insights](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2816475137/Research+Findings+Design+Intent+Experience+Study#Key-Insights) 2, 3, and 6. We assume that the problems encountered by VFS teams re: the Design Intent, are also applicable to the Midpoint Review page. 

Changes were made to the Design Intent via ticket #73513 and changes were made to the Staging Review via ticket #80426. Within this ticket, we'd like to make changes to the MPR touchpoint page that align with the changes made to the DI and SR pages.

Please be sure to use the findings from ticket #86339, refining the MPR artifacts, when redesigning the MPR page.

The purpose of this ticket is to redesign the Midpoint Review touchpoint page and the Midpoint Review section of the CC Request ticket to better meet the needs of VFS teams. 

**Note:** In a later ticket, Governance will be recording a short video for the MPR touchpoint page that explains the purpose of the MPR and walks through the process.. aka the audio version of the content on the page. 

## Impacted Artifacts

- [Midpoint Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)
- MPRR section of the Collab Cycle Request gh ticket via the [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Design-Intent-code-block) - single code block and individual code block for MPR

## Tasks
- [x] Review the changes that were made to the DI page and SR page. Identify and document a list of improvements (ie requirements) that should be made to the MPR touchpoint page as well
- [x] Peer review requirements
- [x] Once requirements are reviewed, propose redesign of the touchpoint page. Ensure all requirements are met.
- [x] Modify the MPR section of the CC Request template to align with the touchpoint page
   - this will mostly be to ensure language aligns. We will not be redesigning the layout of the CC Request within this ticket.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have redesigned the Midpoint Review touchpoint page to reduce quantity of content, eliminate duplicative content, and make it easier for new VFS team members to understand SR expectations
- [x] We have published the revised page to the Platform Website

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Recommended structure of new page, to match [new SR page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) and [new DI page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent):

- What's the purpose of Midpoint Review?
  - Review formats: Synchronous and Asynchronous
- Preparing for the Midpoint Review
  - When should the Midpoint Review be scheduled?
  - What artifacts will be needed?
    - Required artifact
    - Not required, but nice to have
  - How to schedule the Midpoint Review
  - Who should schedule the Midpoint Review?
  - Who should attend the Midpoint Review?
- What happens during the Midpoint Review meeting?
  - Meeting format
  - Agenda
- What sort of feedback can teams expect?
- After the Midpoint Review Meeting
- Help and feedback

@allison0034 gut check on this information flow?

**Comment by allison0034** [comment]
@erinrwhite this looks good. One suggestion, I don't know that synchronous vs asynchronous belongs under "purpose". It might belong under "preparing"?

**Comment by erinrwhite** [comment]
[First round of draft page complete](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3287449601/85049+-+Erin+-+Midpoint+review), doing another readthrough before I send off for review

**Comment by erinrwhite** [comment]
@allison0034 [Draft MPR page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3287449601/85049+-+Erin+-+Midpoint+review) ready for review when you're back in office!

**Comment by allison0034** [comment]
@erinrwhite Looks great!

**Comment by erinrwhite** [comment]
Updated individual and whole code block for MPR on [CC kickoff instructions page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities). Code also copied below:


### Midpoint Review

<details>
  <summary>Toggle Midpoint Review</summary>

#### Before meeting
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 
**Midpoint Review artifacts**
See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.
**Required artifacts**
- [ ] Design prototype or high-fidelity mockup
  - Specify which pages are included in the review
- [ ] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), link to CAIA intake ticket. 
**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:
#### After meeting
##### Platform actions
* Accessibility
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode: 
##### VFS actions
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
</details>

**Comment by allison0034** [comment]
@erinrwhite that looks correct. Will the spacing issues be fixed in the ticket?

**Comment by erinrwhite** [comment]
@allison0034 thank you for catching that! That was a pasting error on my part...correct code below:

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
#### Before meeting
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [ ] Design prototype or high-fidelity mockup
  - Specify which pages are included in the review
- [ ] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), link to CAIA intake ticket. 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
 
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

#### After meeting
  
##### Platform actions

* Accessibility
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode: 
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

**Comment by allison0034** [comment]
Yes, that fixed it!

**Comment by erinrwhite** [comment]
[Ticket code updated on CC kickoff page
](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

[MPR page on Platform Website updated](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)

think this is ready for final eyes and your check on the peer review box! @allison0034

**Comment by allison0034** [comment]
Box checked! @erinrwhite

**Comment by erinrwhite** [comment]
thanks @allison0034 ! Closing...
