### ISSUE TITLE
[CST][ENG][BUG] - Resolve Console Log errors

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#85059]
## Background Context
@samcoforma brought up that he noticed console log errors on local host. 
1. The first error was a warning about <p> cannot be a descendent of <p>
<img width="1064" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk03QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2165e3f20b4be80bd53f53a2ddf627c76654ead7/Screenshot%202024-06-05%20at%208.52.57%E2%80%AFAM.png" alt="Screenshot 2024-06-05 at 8.52.57 AM.png" />
2. The second was a prop validation error on the Claim Detail Files tab
<img width="1064" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/105806934/d7dc8b6b-5c58-4590-b0e8-681a41369b1e" alt="Screenshot of Files tab prop validation error" />
3. The third was a prop validation error on the Overview tab 
<img width="1064" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/105806934/8fecbcf6-da37-46e8-8f96-fc4bd3324ac5"  alt="Screenshot of Overview tab prop validation error" />

### Bug
Steps to reproduce
- Go to the status tab and you'll see error #1. We just need to change the first <p> to a <span>
- Go to the files tab and you'll see error #2. We just need to make the removeFileName prop not required
- Go to the Overview Tab and you'll see error #3. We just need to change currentClaimPhaseDate to require a string instead of a number

## Outcome, Success Measure, KPI(S), and Tracking Link
- Above console log errors do not appear

## Tasks
- [ ] On FilesNeeded.jsx change the first <p> to a <span>
- [ ] On the RemoveFileModal.jsx change the removeFileName prop to not required
- [ ] On the ClaimPhaseStepper.jsx change the currentClaimPhaseDate prop to a string

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Console log errors for <p> cannot be a descendent of <p> no longer appear

**Comment by pmclaren19** [comment]
validated in staging looks good!
