### ISSUE TITLE
Analyze office hours data

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#85060]
## User Story
As a Governance team member, I want to review Design office hours data so that CAIA and Governance can determine if it makes sense to merge/align office hours.

Assignee: @allison0034
Peer Reviewer: @erinrwhite

## Description
There is an assumption that VFS teams are going to both Governance and CAIA office hours and asking similar questions. We'd like to align/merge our office hours, however before we do, we'd like to review the existing Design office hours data to see if VFS teams have concerns that require them to attend both teams office hours.

The purpose of this ticket is to pull Design office hours data from April 1 to present and capture team, individual, date, description of support, associated Collab Cycle ticket (if applicable), and Collab Cycle status (if applicable). We will then compare this data with the data CAIA is pulling from their office hours log to see if there are trends.

## Impacted Artifacts
- [Design Office hours data](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3213328409/Design+Office+hours+data)

## Tasks
- [x] In the Governance/Tracking folder in Confluence, create a new doc that captures Design Office hours data from April 1 to present.
- [x] Be sure to capture team, individual, date, description of support requested, associated Collab Cycle ticket (if applicable), and Collab Cycle status (if applicable).
- [x] Notify Shira when complete so that she can share with CAIA.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have captured metrics on the Design Office hours from April 1 to present

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Created [document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3213328409/Design+Office+hours+data)

**Comment by allison0034** [comment]
Note: Matt recently merged Design System ands Figma office hours into Design Office hours.

**Comment by allison0034** [comment]
Continuing to add data to the doc.

**Comment by erinrwhite** [comment]
Thanks @allison0034 ! Looking good to go. I found a couple of the related Collab Cycle tickets and added the links. Looking forward to our analysis of these 👀

**Comment by shiragoodman** [comment]
@coforma-terry @strelichl Sorry, meant to share this with you sooner! Allison created an analysis of our office hours. I don't have the link to the office hours spreadsheet you shared, but thought I'd pass this along. Any chance you can compare it to your own spreadsheet to see if there's overlap? Please lmk. We can discuss at our next sync.
[PPST-Design Office hours data-030724-151530.pdf](https://github.com/user-attachments/files/16087123/PPST-Design.Office.hours.data-030724-151530.pdf)

**Comment by shiragoodman** [comment]
@NaomiPMC FYI^
