### ISSUE TITLE
[CDP] Bug - Veteran not enrolled in healthcare alert on copay balances

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#85064]
## Description
We need to update the alert on the `/copay-balances` page to the same warning that appears on the summary page when a veteran is not enrolled in healthcare. Currently it's showing as an error message as if the endpoint failed, but it should be a warning message. Examples below.

On the summary page we [check for a 403 response ](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/combined/components/Balances.jsx#L29) and surface the warning message, so we should probably do the same on the [copay specific page](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/medical-copays/containers/OverviewPage.jsx). 

[Here's the PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21548) where we implemented the warning the first time, looks like `vets.gov.user+3@gmail.com` is a good test case locally and on staging according to [this test case](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/use_cases.md#use-case-d---veteran-is-not-enrolled-in-healthcare)

Given: A veteran is not enrolled in healthcare
When: That veteran navigates directly to `/manage-va-debt/summary/copay-balances`
Then: That veteran should see the "Not enrolled in healthcare" alert message instead of the error message

### Summary page warning
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE03QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab25b2e075f2d1c77f54b87fe95fa898664a295b/image.png" alt="image.png" />

### Current copay error 
This should be changed to warning message to match summary page 
(while not effecting the `renderOtherVA` functionality)
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHc3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83970853bfb8824db1756858e4fc9f4b6ac5d563/image.png" alt="image.png" />

## Tasks
- [ ] Implement warning message on copay balances page to indicate when a veteran is not enrolled in healthcare
- [ ] Double check with BE that any 403 we get means the veteran is not enrolled in healthcare
- [ ] Run and update e2e tests (that may be temporarily skipped, so you'll need to unskip to run)

## Acceptance criteria

- [ ] Messaging is consistent for copay balances page and summary page
- [ ] 403 is the correct condition for showing veteran is not enrolled in healthcare

## Testing
- [ ] Warning message appears if copay response is 403
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Bumping to a 5 as we may need to update some tests and may have some cross training involved!
