### ISSUE TITLE
Update guidance for creating SR issue tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#85069]
## User Story
As a Governance team member, I want to have clear concise directions on how to publish Staging Review findings tickets so that VFS teams can be made aware of the issues we found.

Assignee: @erinrwhite
Peer Reviewer: @shiragoodman 

## Description
In ticket #83388, @it-harrison defined a new way for Governance team to bulk upload issue tickets at Staging Review. This new method is an app for your desktop that utilizes the csv file created from the DraftingTemplate.

Now that the app is working as expected, Governance team needs to modify the [How to generate SR issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets) guidance so that it reflects the steps necessary with the new app.

Currently the guidance covers:

- verifying the content within the DraftingTemplate is complete
- creating the CSV file from the DraftingTemplate data
- saving the CSV file properly on your local machine
- running the bulk upload using node.js 
- verifying the issue tickets were created in the correct repo
- notifying the Governance team of the issue tickets created

Some things that are currently missing:

- archiving the DraftingTemplate file and/or folder within Google Drive
- locating the QA Standards ticket

The purpose of this ticket is to restructure and better organize the existing guidance, while also incorporating use of the new upload tool created in ticket #83388.

**Note:** There should be no indication in this guidance of who is completing these steps. We plan to eventually task the On Support person with creating the SR issue tickets and notifying the team, however we still need to determine how Shira can be informed/notified of the tickets so she can monitor them for updates/questions from the VFS team.

## Impacted Artifacts
[How to generate SR issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets) 
[How to generate DST SR issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2983493633/How+to+generate+DST+Staging+Review+issue+tickets)

## Tasks
- [x] update How to generate SR issue tickets documentation
- [x] update How to generate DST Staging Review tickets documentation
- [x] fold in documentation about the uploader tool

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have restructured the guidance so that is clear, easy to follow, easy to step away from and return knowing where you left off, and flows similarly to our other touchpoint guidance.
- [x] We have incorporated use of the new bulk upload tool 

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@shiragoodman docs ready for your first review!

- [How to generate Staging Review tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3226468364/85069+-+Erin+-+How+to+generate+Staging+Review+issue+tickets)
- [How to generate DST Staging Review tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3226664961/85069+-+Erin+-+How+to+generate+DST+Staging+Review+issue+tickets)
- [How to use the bulk issue uploader](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3221946370/85069+-+How+to+use+the+bulk+issue+uploader)

**Comment by shiragoodman** [comment]
@erinrwhite I added comments to all 3 docs. Thank you for organizing this! Let me know if you have any questions about my comments.

**Comment by erinrwhite** [comment]
thank you @shiragoodman ! I think I got all of the feedback addressed. Please do one more-read through and then I can move the documentation over:

 - [How to generate Staging Review tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3226468364/85069+-+Erin+-+How+to+generate+Staging+Review+issue+tickets)
 - [How to generate DST Staging Review tickets](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3226664961/85069+-+Erin+-+How+to+generate+DST+Staging+Review+issue+tickets)
 - [How to use the bulk issue uploader](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3221946370/85069+-+How+to+use+the+bulk+issue+uploader)

**Comment by shiragoodman** [comment]
@erinrwhite the changes look good! I tagged you in 1 comment re: a very minor issue. Feel free to publish to their forever home on Confluence. thank you!

**Comment by erinrwhite** [comment]
@shiragoodman thank you for the fast and thorough review! Reviewing now.

**Comment by erinrwhite** [comment]
We're live! @shiragoodman closing this ticket - can you check the peer review boxes when you have a chance? 

 - [How to generate staging review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)
 - [How to generate DST staging review issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2983493633/How+to+generate+DST+Staging+Review+issue+tickets)
 - [How to use the bulk issue uploader](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3239870645/How+to+use+the+bulk+issue+uploader)

**Comment by shiragoodman** [comment]
done - thank you @erinrwhite !
