### ISSUE TITLE
[Tech Debt] Claims: Remove secondary disability translation

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#8507]
## Goal
Cleaner translation class for Disability compensation saved claim

In the disability compensation < saved claim model we [translate disabilities](https://github.com/department-of-veterans-affairs/vets-api/blob/4817e431cbd276935809b3c813e8c2f4fd2e0bdd/app/models/saved_claim/disability_compensation.rb#L19). This includes code to[ translate secondary disabilities](https://github.com/department-of-veterans-affairs/vets-api/blob/4817e431cbd276935809b3c813e8c2f4fd2e0bdd/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L460).  However this code is no longer needed, as all secondary disabilities are instead translated to primary disabilities and given "service relevance" field with text like "caused by x disability".  Removing unused code will increase readability.

---
## Tasks / Acceptance Criteria
- [ ] Remove un-needed secondary disabilities translation

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by edmangimelli** [comment]
never got around to this one 😞

**Comment by lihanli** [comment]
@annaswims should the `newSecondaryDisabilities` attribute be removed from the schema too? there's frontend code that references that attribute
