### ISSUE TITLE
Refinement: Transition UA Transaction Events to GA4 Key Events

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#85085]
### Description
Ensure that existing transaction events are being captured in GA4 and tagged as Key Events (similar to conversion Goals in GA). Will use the 'Transaction' events in All VA.gov Website Data [Production] as guide (see [transaction-events_20240101-20240531.xlsx](https://github.com/user-attachments/files/15594063/transaction-events_20240101-20240531.xlsx)).

---

### Tasks
- [ ] add any non-custom events that have not been implemented in GA4 yet
- [ ] update existing events as needed so the Key Events label can trigger using the GA4 Event Name

### Acceptance Criteria
- [ ] all Transaction events from UA are captured in GA4 and marked as Key Events
