### ISSUE TITLE
527EZ: Review form for usability improvements V1

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#85080]
## Description
We need to review these pieces of the form:
- Intro screen
     - Don’t include eligibility information additional info component on the intro page—to keep the page slim and ensure that we can edit the eligibility information on this page in Drupal: [Eligibility for Veterans Pension](https://www.va.gov/pension/eligibility/)
     - Remove bullets for supporting documents (because they’ll be prompted in the form flow)
     - Remove the “(*Required)” indicators
- “Income and assets” section
- "Health and employment information" section
- “Supporting documents” section
    - Do we have a standard content pattern for presenting upload options within the form flow v. on the confirm screen?
    - Standardize "supporting documents" as a term throughout the form flow.
- Confirm screen

## Resources
- [Request 1](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4147-11726&t=92YnXgqG4XDN4EM9-4) (Figma)
- [Request 2](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4138-26063&t=rhWu6zrySaVgwsJp-4) (Figma)
- [Request 3](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4762-115913&t=FNmVz03T75d5iSil-0) (Figma)

## Tasks
- [x] AP: Draft recommnedations
- [x] AP: Share recommendations with product team

## Criteria
- [x] Content recommendations have been shared with product team

**Comment by aprocik1** [comment]
### Income and assets

We need to know if you and your dependents have over $25,000 in combined assets.

We consider this information when we determine your eligibility for Veterans Pension benefits. If you and your dependents have over $25,000 in combined assets, you may still be eligible.

<details>
<summary>Who we consider a dependent</summary>

**A dependent is:**

- A spouse (**Note:** We recognize same-sex and common-law marriages)
- A parent, if you’re directly caring for them and their income and net worth are below a certain amount
- An unmarried child (including an adopted child or stepchild) who meets one of the eligibility requirements listed here

**To be considered a dependent, one of these must be true of an unmarried child:**

- They're under 18 years old, **or**
- They're between the ages of 18 and 23 years old and enrolled in school full time, **or**
- They became permanently disabled before they turned 18

</details>

<details>
<summary>How we define assets</summary>
Assets are all the money and property you or your dependents own. Don’t include the value of your primary residence or personal belongings such as appliances and vehicles you or your dependents need for transportation.

</details>

Do you and your dependents have over $25,000 in combined assets?
- [ ] Yes
- [ ] No

<details>
<summary>Warning alert: If yes</summary>

You’ll need to submit an Income and Asset Statement in Support of Claim for Pension or Parents' Dependency and Indemnity Compensation (VA Form 21P-0969).

We’ll ask you to upload this form at the end of this application. Or you can send it to us by mail.

[Get VA Form 21P-0969 to download (opens in new tab)](https://www.va.gov/find-forms/about-form-21p-0969/)

</details>

**Comment by aprocik1** [comment]
### Supporting documents

On the next screen, we’ll ask you to submit supporting documents and additional evidence for your claim. If you upload all this information online now, you may be able to get a faster decision on your claim.

You'll need to complete these supporting documents:

- An Examination for Housebound Status or Permanent Need for Regular Aid and Attendance (VA Form 21-2680)
[Get VA Form 21-2680 to download (opens in a new tab)](https://www.va.gov/find-forms/about-form-21-2680/)
- A Request for Nursing Home Information in Connection with Claim for Aid and Attendance (VA Form 21-0779)
[Get VA Form 21-0779 to download (opens in a new tab)](https://www.va.gov/find-forms/about-form-21-0779/)
- An Income and Asset Statement in Support of Claim for Pension or Parents' Dependency and Indemnity Compensation (VA Form 21P-0969)
[Get VA Form 21P-0969 to download (opens in a new tab)](https://www.va.gov/find-forms/about-form-21p-0969/)

And you’ll need to gather certain additional evidence depending on your situation.

<details>
<summary>If you have any dependent children who you adopted</summary>

You'll need to submit copies of one of these documents:

- Adoption papers, **or**
- Amended birth certificate

</details>

<details>
<summary>If you receive Social Security disability payments</summary>

You’ll need to submit additional evidence of your disability.

You can submit copies of these private medical treatment records:

- Doctor’s reports
- X-rays
- Medical lab or test results

Or, you can submit copies of these federal and state records:

- Your military medical records
- Your military personnel records
- Any Social Security Administration or other federal or state medical treatment records
- Any treatment or personnel records from your National Guard or Reserve unit that support your claim (if you’ve served in either of these branches)

</details>

<details>
<summary>If you need the help of another person for daily living</summary>

You’ll need to submit additional evidence that shows at least one of these is true for you:

- You need another person to help you perform daily activities, like bathing, feeding, and dressing, **or**
- You have to stay in bed—or spend a large portion of the day in bed—because of illness, **or**
- You’re a patient in a nursing home due to the loss of mental or physical abilities related to a disability, **or**
- Your eyesight is limited (even with glasses or contact lenses you have only 5/200 or less in both eyes, or concentric contraction of the visual field to 5 degrees or less)

</details>

<details>
<summary>If you're housebound and you live independently</summary>

You’ll need to submit additional evidence that shows at least one of these is true for you:

- You have a single, permanent disability that’s rated as 100% disabling, and this means you’ll always need to be in your home or another living space most of the time, **or**
- You have a single, permanent disability rated as 100% disabling and at least one other disability rated as 60% or more disabling

</details>

**Comment by aprocik1** [comment]
[Figma file design reference](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4147-11888&t=D6BK2dSvclMf7c7J-4)

### Submit your supporting documents
You can submit your supporting documents using any of the options listed on this page.

**Note:** If we receive your claim and we need additional documents, we’ll ask you to submit them. If you don’t respond within 30 days of our request, we may decide your claim with the information that’s available to us.

You can submit your supporting documents right now by uploading them online as PDFs.

[Button] Upload

Or, you can submit your supporting documents later in one of these 2 ways:

#### Option 1: Through the Claim Status Tool

#### Option 2: By mail

**Comment by aprocik1** [comment]
[Figma file design reference](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4608-44134&t=Y5HAtBTqCmVqzV4j-4)

### Your Veterans Pension application
[No changes to the success alert or featured content box.]

#### If you need to submit your supporting documents
If you didn't already submit your supporting documents and additional evidence, you can submit them in one of these 2 ways:

##### Option 1: Upload your documents online using the Claim Status Tool
It may take 7-10 days for your pension claim to appear in the Claim Status Tool. After your pension claim appears, you can upload your documents in the **Files** tab.

[Link] Use the Claim Status Tool to upload your documents

##### Option 2: Mail us copies of your documents
Don't send us a printed copy of your pension claim. We already have it. And don't send us your original documents. We can't return them.

Mail us copies of your documents to this address:

[Address block]
Department of Veterans Affairs
Pension Intake Center
PO Box 5365
Janesville, WI 53547-5365

**Note:** If we asked you to complete any supporting documents, you should keep a copy of them for your records.

**Comment by aprocik1** [comment]
Introduction screen ([Figma file](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4817-47795&t=9TTmxHCG3o5IoW0g-4))

Use our online tool to fill out and submit your application for Veterans Pension benefits. If you're a wartime Veteran and you're at least 65 years old, or if you have a permanent and total disability, you may be eligible for monthly payments. Your income and net worth will need to be within certain limits.

**Note:** A Veterans Pension is different from a military retirement pension.

[Link to new R&S page] Learn about the different types of pensions

### Check your eligibility
Check our eligibility requirements before you apply. If you think you may be eligible, but you're not sure, we encourage you to apply.

Find out if you're eligible for Veterans Pension benefits

### Gather your information
Here's what you'll need to apply:
- Your Social Security number or VA file number
- Your military history
- Your employment history
- Your marital status and prior marital history
- Financial information about you and your dependents

We may also ask you for this information:
- Information about your spouse’s prior marriage
- Information about your dependent children

[Note for Michael: I'm removing mention of the supporting documents from this section. We're prompting Veterans to submit only the documents that are relevant to them throughout the form flow.]

### Start your application
We’ll take you through each step of the process. It should take about 30 minutes.

<details>
</summary>What happens after you apply</summary>
We'll process your application for Veterans Pension benefits and send you a letter in the mail with our decision.

We may request for more information to process your application and make a decision. If we request more information, you’ll need to respond within 30 days. If you don't, we may decide your claim with the evidence that's available to us.

**Comment by aprocik1** [comment]
About form page ([Figma file](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4430-25743&t=9TTmxHCG3o5IoW0g-4))

### When to use this form
Use VA Form 21P-527EZ to apply for Veterans Pension benefits. If you're a wartime Veteran and you're at least 65 years old, or if you have a permanent and total disability, you may be eligible for monthly payments. Your income and net worth will need to be within certain limits.

**Comment by aprocik1** [comment]
Health screens 1, 2, 3, and 4 ([Figma file](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4084-14917&t=1SF9kPEfpeviRGKx-4))

### Health and employment (screen 1)
#### Tell us your age

Are you at least 65 years old?
[Hint] Your answer to this question will help us determine if you're eligible for Veterans Pension benefits.
- [ ] Yes
- [x] No

### Health and employment (screen 2)
#### Tell us about any Social Security or Supplement Security payments

Do you receive Social Security Disability Insurance or Supplemental Security Income?
[Hint] Your answer to this question will help us determine if you're eligible for Veterans Pension benefits.
- [ ] Yes
- [x] No

### Health and employment (screen 3)
#### Tell us about any medical conditions

We need to know about any medical conditions that prevent you from working.

<details>
<summary>How we define a medical condition that prevents you from working</summary>
A medical condition is an illness or injury that affects your mind or body. It doesn't have to be service connected.

If your medical condition prevents you from working, both of these must be true:

- Your medical condition is reasonably certain to continue throughout your lifetime, **and**
- Your medical condition makes it impossible to be gainfully employed

</details>

Do you have a medical condition that prevents you from working?
[Hint] Your answer to this question will help us determine if you're eligible for Veterans Pension benefits.
- [ ] Yes
- [ ] No

### Health and employment (screen 4)
#### Submit additional evidence

Based on your answer, you’ll need to submit additional evidence about your medical condition.

We’ll give you instructions for submitting your additional evidence at the end of this application.

**Comment by aprocik1** [comment]
Updated: I added an additional accordion to submission screen 1 for "seriously disabled" children.

**Comment by aprocik1** [comment]
Update: I updated the content for the intro screen and proposed a new additional info component in step 2 (based on product team request).

**Comment by aprocik1** [comment]
Update: I returned to this ticket to incorporate some governance feedback from midpoint review. I'll keep this ticket open for now, in case I need to return to it again.
