### ISSUE TITLE
LOA1 Widget State for 500 status

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#85092]
## Background
We are receiving a `500` status when requesting the active POA for ~3.5% of users.  This is related to the users not having an ICN -- these are LOA1 users who have not yet verified their identity. But because we cannot display the representative status, these users currently see our error state.

The team has discussed introducing a new LOA1 state to our Rep Status Widget, to guide these users to verify their identity.  

Implementation notes:
- There are 2 active variations, depending on if the LOA1 user is logged on with ID.me, or Login.gov. 
   - Please take a look or implement the `<VerifyAlert />` that is in the `src/platform/user/authorization/components/VerifyAlert.jsx`
- To determine a user's level of authentication, we should be able to use the `isLOA1 user` [frontend helper method](https://github.com/department-of-veterans-affairs/vets-website/blob/0879d6d826548550157d0a65e8a6b7c796e30795/src/platform/user/selectors.js#L15)
- Would it be a bad idea to add the pundit callback to PowerOfAttorneyController as well? The advantage there would be avoiding unnecessary calls to Lighthouse even if the frontend changes.
   - From OCTO leadership: Most apps in vets-api use Pundit to scope access and we should adopt this approach for consistency. Examples:
   - The Document Upload controller implements it here:
https://github.com/department-of-veterans-affairs/vets-api/blob/25f41ccd9a5d1ea185c2ba45c3baaa5ec92f715c/app/controllers/v0/documents_controller.rb#L6
   - Here is how it is implemented in the feature that collected rated disabilities: https://github.com/department-of-veterans-affairs/vets-api/blob/25f41ccd9a5d1ea185c2ba45c3baaa5ec92f715c/app/controllers/v0/rated_disabilities_controller.rb#L8

## Designs

1. [Standalone state](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=13016-114162) 
2. [example on Appoint a Rep](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=12774-720792)

**Note**: The first, larger alert (with both Login.gov and ID.me buttons) can be disregarded as it's being phased out -- soon users will only be able to login with these options.

## Tasks
- [ ] Confirm that 500, 503 and 504 statuses are all stemming from a missing ICN.
- [ ] Introduce a new LOA1 state, for the 500 status
- [ ] If applicable, also include the LOA1 state for the 503 and 504 statuses.
- [ ] Confirm the new state is serving up as expected ([LOA1 test user stored here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accredited-representation-management-poa.csv), but we might need to check with Identity for add'l test users if that doesn't work).

## Acceptance Criteria
- [ ] Users who do not have an ICN are encouraged to verify their identity, so that we can connect to their records and display any appointed representation.

**Comment by oddball-lindsay** [comment]
Approach for checking LOA1 will be:
1. Use the frontend helper to determine if a user is LOA1. And if they are, we don't need to call vets-api which in turn calls the LH API for the rep status.
2. Implement the pundit strategy as a backup, in case an LOA1 users gets past the frontend helper.

But our implementation will be:
1. First implement the backend pundit strategy and merge in.
2. Then implement the frontend helper.

**Comment by oddball-lindsay** [comment]
Curious if the 5% 403 errors are indicative of anything - can look at history to see if this is out of the ordinary. This is LOA3 users that don't have an ICN or PID.

Activity is showing only 1 422 and 0 500s, which is feeling good for our new strategy.

**Comment by oddball-lindsay** [comment]
@mtri to test in Staging, @MDomngz to test in Production.

**Comment by mtri** [comment]
Used lindsay.li-smith+loa1@oddball.io which appears to be functioning properly.

Unable to test the [login.gov](https://design.va.gov/patterns/help-users-to/sign-in#verify-with-logingov) or [login with another account variations](https://design.va.gov/patterns/help-users-to/sign-in#verify-with-logingov).

The only thing I see is the alert is not using curly apostrophes. This appears to be in the documentation as well. I’ll flag to the DST.

**Comment by oddball-lindsay** [comment]
@MDomngz do you login with Login.gov? Or ID.me? I wonder if we can test the other login pathway with your login in Production 🤔

**Comment by oddball-lindsay** [comment]
Hoping to close this out - LOA1 looks good with for my production ID.me account. Here's the LOA1 status on Find a Rep:

![Image](https://github.com/user-attachments/assets/04085aa3-859a-4d47-9d94-ac87306f4e2f)

I also made an LOA1 account with Login.gov, here's the LOA1 status on Appoint a Rep:

![Image](https://github.com/user-attachments/assets/fa63dff9-3eb8-4a5c-a436-c7872b2a61e7)
