### ISSUE TITLE
[Design] My VA Forms Status: Finalize content on error states

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#85112]
## Background
Matt created the designs for handling errors in #84256 . We need to get content reviewed/approved and our documentation updated (if not already done).

## Tasks
- [x] Work with content to get approval on error copy
- [x] Coordinate with VFF to make sure any error language they may have on the confirmation page aligns with ours
- [x] Finalize copy in FE documentation

## Acceptance Criteria
- [x] Copy is approved and documentation is updated

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ PM
- _How can this work be validated?_ Confirm we have finalized copy

**Comment by mattmarino-adhoc** [comment]
Discussion with CAIA happened this sprint, but since the next steps of our form submission research and related decisions are tied to this work, we will not have a resolution until next sprint.

**Comment by mattmarino-adhoc** [comment]
Was not addressed in Sprint 41 due to work on form status blocking it

**Comment by mattmarino-adhoc** [comment]
Link to relevant screens with content: https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-1&t=zFPuzADZzm6p0CLh-1

**Comment by ajakabcin** [comment]
hey @mattmarino-adhoc the link above looks like it's linking to some "Post MVP" designs - [these](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-1&t=H7nMdSPVaoHS36d1-1) are the system errors, correct?

**Comment by mattmarino-adhoc** [comment]
@ajakabcin that does indeed have system errors for MVP too - this is a more direct link: https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=1302-28909&t=HqzBWh1aYg5G4WmO-0
