### ISSUE TITLE
Update link on Deployments page

### ISSUE THREAD

**Issue by taylojill** [department-of-veterans-affairs/va.gov-team#85122]
## Issue Description

- Per [this Slack request](https://dsva.slack.com/archives/CL181NRJQ/p1717615850036169?thread_ts=1716929567.423409&cid=CL181NRJQ), a link in Automated deployment schedule table on the [Deployments page](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments) is incorrect.

---
## Tasks
- [x] Update link as requested in Slack thread
- [x] Check page for blockers
- [x] Add date stamp
- [x] Prepare for deployment

## Acceptance Criteria
- [x] Page link is updated
- [x] Page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
Updated link as requested in Slack thread. Page checked for blockers and date stamped. Ready for publishing.

**Comment by jknipes** [comment]
work is complete, page is deployed, moving to _Done_
