### ISSUE TITLE
[BE] 10-10CG - Improvements: Exploration on OAuth 

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#85120]
## Background
Mule DTC is planning to implement OAuth2.0 for securing APIs deployed in Mule GovCloud.

Currently the Mule APIs are secured with Client ID/Client Secret mechanism and want to move to OAuth2.0 (using Okta as Identity Provider).
VA application authenticates against Mulesoft API. Today we use appid and apptoken to perform the authentication. Mule team has determined that moving to Oauth 2.0 will enhance security. So this is just a more secure method to authenticate to gain access to the API.

Will likely need to set up a new backend integration with dtc-va.okta-gov.com endpoint, if it doesn’t already exist
https://dtc-va.okta-gov.com/oauth2/ause1x1h6Zit9ziQL0j6/v1/token?scope=read&grant_type=client_credentials

**This ticket is for exploration on what tasks are needed to complete this change, including confirming whether the dtc-va.okta-gov.com endpoint exists in VA.gov integrations today.**

##Tasks
- [x] Review how the 10-10CG form authentication is set up today with Mulesoft API
- [x] Check with other VA.gov applications on how their OAuth is set up
- [ ] Determine if the dtc-va.okta-gov.com endpoint exists in VA.gov integrations (with vets-api)
- [x] Determine the tasks needed and level of effort for this change
- [ ] Review with PM/team for next steps

## Acceptance Criteria
- We have determined what steps are needed to complete the change to use OAuth with Mulesoft (Mule DTC).

**Comment by coope93** [comment]
We will need to update any vcr cassettes used in specs that are calling the caregiver endpoint. This will increase scope of implementing the change.

**Comment by coope93** [comment]
I'm waiting to here confirmation, but I'm guessing we will use the Client Credentials Grant flow. More info for using that with Okta [here](https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/).

**Comment by coope93** [comment]
Created the following tickets to implement these changes: 
- [Update `MuleSoftClient` to use OAuth 2.0 flow](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/86423)
- [Update Form1010cg Service to use new OAuth 2.0 Flow](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/86425)
- [Test New Authorization](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/86430)
