### ISSUE TITLE
Apply Faraday feature PR as Monkeypatch

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#85133]
## Issue Description
What started as a simple monkeypatch in #84394, led to the decision to submit a feature PR to the Faraday Gem. This ticket will take the work that was started in #84394, and finish work associated with vest-api. This includes taking the code in the in-progress `faraday` branch (will link when available, see #XXXXX) and monkeypatching it into vest-api, confirming the tests that were written in the previous ticket still pass, confirm ALL tests still pass, and deploy to production

---
## Tasks
- [x] Copy respective classes from local `faraday` branch and monkey patch into vets-api
- [x] Confirm (and possibly expand upon) new specs testing implementation of new default option.
- [x] Confirm ALL specs still pass
- [x] Test in dev/staging
- [x] deploy to production
- [x] create #TODO to remove patch if Faraday PR is accepted

## Acceptance Criteria
- [x] Feature is deployed to production

**Comment by ryan-mcneil** [comment]
Support prevented me from working on this at all. Moving to next sprint.
