### ISSUE TITLE
Create PR to Faraday for monkeypatch in Vets API

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#85135]
## Issue Description
Following up on #84394, the work tested on a branch to `faraday`, needs to be formally submitted to the gem via PR (details on contributing to `faraday` [here](https://github.com/lostisland/faraday/blob/main/.github/CONTRIBUTING.md). 

---
## Tasks
- [x] `faraday` repo is forked and code from local branch is copied into fork.
- [x] Add specs to thoroughly test new feature
- [x] Update `/Docs` as needed
- [x] Submit PR and cross fingers

## Acceptance Criteria
- [x] PR has been submitted
