### ISSUE TITLE
Sentry configuration for Facilities team

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8514]
## Goal
Sentry configuration for Facilities team

## Background
The Veteran-facing Services Platform (VSP) utilizes Sentry as a tool to track errors related to VA.gov applications. Sentry allows teams to discover, triage, and prioritize errors in real-time.

Veteran-facing services (VFS) teams are responsible for configuring and managing their own Sentry teams, managing alerting rules, and monitoring their application’s data. These management rules give VFS teams more responsibility in relation to Sentry alerting and error ownership.

---
## Tasks
Follow documentation for Sentry configuration found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-configuration.md)
- [ ] Configure the SOCKS proxy. 
- [ ] Create a new team with designated Sentry administrator 
- [ ] Provide the name of designated Sentry administrator in the #vfs-platform-support Slack channel to request access
- [ ] Add team members to your Sentry team. 
- [ ] Determine list of ownership rules (paths and urls) for monitoring 
- [ ] Provide owership rules to a VSP engineer in the #vfs-platform-support Slack channel

## Acceptance Criteria
- [ ] New team is created based on the naming and structuring conventions
- [ ] Sentry administrator is designated and communicated to #vfs-platform-support Slack channel
- [ ] Ownership rules are determined and communicated to #vfs-platform-support Slack channel
- [ ] Process is communicated to Facilities team
- [ ] Apropriate team members join #vfs-sentry-alerts channel 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lihanli** [comment]
this should be done now, `vfs-facilities` team has been created in sentry

**Comment by mmiddaugh** [comment]
Thank you @lihanli!

**Comment by mmiddaugh** [comment]
@lihanli will you please connect with @darkbushido regarding the details?
