### ISSUE TITLE
Pry bug in bin/test

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#85169]
## Summary 

Pry console is not loading for bin/test 

<img width="579" alt="Screenshot 2024-06-06 at 8 24 23 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134282106/6695296f-be79-4e98-ad27-914ffe5082a2">

## Tasks
- [x] Investigate root cause
- [x] Figure out a bug fix
- [x] Test the fixeroo

## Acceptance Criteria

- [ ] ~pry console loads during `bin/test --no-parallel`~ not possible
- [x] Users can interactively debug when using bin/test without parallel

**Comment by stevenjcumming** [comment]
It's not possible for the shell commands to support `pry`, so debugger is offered as an alternative. This will still allow users to interactively debug via bin/test

https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-ge
