### ISSUE TITLE
HLR: Review form updates

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#85174]
## Description
The Higher-Level Review (HLR) PDF form has been updated. As a result, the online form has been updated to match.

We need to review the online form updates and provide content recommendations.

## Resources
- [Figma file](https://www.figma.com/file/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?type=design&node-id=0%3A1&mode=design&t=UXbQ55kq5dfnizv7-1): This is the content source of truth for this project.
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714761005965/cf4071f13c521f01c515757de3ab6e3e87ba22ba?sender=u80fb5a3b8f7951f35d701197): The screens with pink stickies and links to Figma are ready for content review. The screens without links to Figma are a work-in-progress.

## Tasks
- [x] KF: Draft recommendations (with support from AP, as needed)
- [x] KF: Share recommendations with product team

## Criteria
- [x] Content recommendations have been shared with the product team

**Comment by aprocik1** [comment]
@katherine-fung, I just reviewed your document and left some preliminary suggested edits. I also created a react widget content task ticket on the intake ticket.

@strelichl, can you follow up with the product team to schedule a react widget kickoff meeting? Or, can you place this on your timer to do so closer to their incremental launch date?

Thanks to both of you!

**Comment by katherine-fung** [comment]
Thanks @aprocik1! I've provided a content recommendation and tagged you on 
that last outstanding chunk of content (the legalese about the Veteran's authorization to move from the legacy appeals process to the modernized decision review process). Can you let me know what you think? 

https://docs.google.com/document/d/1OZcdssks9WrtSCLK60ywdXxpOy-lautYuVcFlADNRhU/edit#heading=h.yncbsr134lr4 

I know the approach will ultimately depend on the SMEs and how closely they believe they need to follow the PDF, but I'll reference this for support: https://design.va.gov/templates/forms/#legalese-vs-plain-language

For context, here is my discussion with Eileen about this content: https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A?node-id=163-29946#843610731 

I think a link to a page explaining the difference between the modernized decision review and legacy appeals processes might be helpful here too, but I don't think a page like this exists on the modernized VA site.

**Comment by aprocik1** [comment]
Update: Katherine and I reviewed these edits together in a meeting. She's shared her recommendations with the product team. I'm moving this ticket to validate, but keeping it open for now, in case the product team needs us to return to it.

**Comment by katherine-fung** [comment]
Noting here that the product team had questions for us that we've since answered and provided other content recommendations for. 

- They've implemented our recommendation to split the "Option to request an informal conference" screen into 2. 
- We've provided copy for the intro page about written statements based on SME feedback. 
- We let the team know they can proceed with MST info on the intro page, but we still need to develop an approach for this info across relevant VA forms.  

I'll leave this ticket open for now but I believe the team has provided all its feedback to our round of recommendations, and that we can close this ticket soon. 

cc @aprocik1 @strelichl

**Comment by aprocik1** [comment]
Update: I asked Eileen these questions about the MST requirement on the form intro page:

1. What's the goal of adding this information? Why is it required and who determined this requirement?
2. What other forms is this information required for? Or, who can we ask to find this out?
3. Why is this information required for the Higher-Level Review and Supplement Claims forms? Is it also required for the Board Appeals form?
4. Why are we providing users with information about VHA coordinators, instead of VBA coordinators?
5. Why are we placing this information on the form intro page? Can we consider placing it within the form flow?

Here's the link to the comment: https://docs.google.com/document/d/1OZcdssks9WrtSCLK60ywdXxpOy-lautYuVcFlADNRhU/edit?disco=AAABOQS7Jso

**Comment by bethpottsVADEPO** [comment]
@aprocik1 and @katherine-fung Other than the widget, has there been talk (either with the product team or amongst yourselves) of other revisions to the static page? What I'm gettin at, Katherine, is whether in the course of this product work you were tackling any updates to the HLR static page to align with updates we've made over the last year to the Board Appeals and SC pages? I'm assuming the answer to this is no. But I wanted to check to be sure.

**Comment by katherine-fung** [comment]
@bethpottsVADEPO I'm confirming that we haven't been updating the HLR static page as part of this ticket. 

The HLR static page work was happening in ticket #48533. Can you take a look at ticket #48533 and confirm whether it's ok to continue that work? cc @aprocik1 @strelichl @laurwill

**Comment by katherine-fung** [comment]
I'm talking with the SME Shireen Lackey about incorporating her feedback on the content. This conversation is happening in Outlook. I'm keeping the product team updated in intake ticket #82516.

**Comment by katherine-fung** [comment]
The product team has incorporated our content recs, and Shireen's feedback. 

I noted a few questions in the intake ticket #82516 and how the team has addressed them.
