### ISSUE TITLE
`product_name` Not Available for Some MDOT Test Users

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#8521]
## User Story or Problem Statement
Betamocks isn't providing `product_name` field for some supplies for some MDOT users

## Goal
`product_name` field should return the product name in the supplies array.

## Tasks
- [ ] Add the field in betamocks
- [ ] Test and verify field is viewable

## Acceptance Criteria
- [ ] Field is added to appropriate supplies in mdot betamocks test responses.
