### ISSUE TITLE
[Backend]`prescribed_date` field in betamocks should return a date for MDOT test responses

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#8522]
## User Story or Problem Statement
Betamocks isn't providing `prescribed_date` field for some supplies for some MDOT users. This field should be present for supplies which have a device_name set, as this denotes the date when the device was prescribed by a physician.

## Goal
`prescribed_date` field should return the product name in the supplies array.

## Tasks
- [x] Add the field in betamocks
- [x] Test and verify field is viewable

## Acceptance Criteria
- [x] Field is added to appropriate supplies in mdot betamocks test responses.
