### ISSUE TITLE
[DISCOVERY] Identify MVP: VAMC Detail page content hardening 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8527]
## User Stories

- As a content producer, I want to be able to create content at the system or facility level so that I can provide localized information to Veterans.
- As a content producer, I want the editorial experience to be user friendly so that I can serve Veterans efficiently.
- As the VHA, I want national content to be maintained at the national level so that Veterans have a standardized experience.

## Goal(s)
- Consistent end user experience across multiple VAMCs
- Serve content producers by creating a flexible, reusable content model with governance mechanisms 
- Improve the editorial experience
- Reduce support requests to CMS

## Editorial experience

Content producers should be able to 
- [ ] add content within their governance level
- [ ] view national content 
- [ ] view who can edit national content
- [ ] view how and where their content will render
- [ ] anticipate how content changes will impact deployment and blast notifications to Veterans

## Tasks
**For "Detail/Top Task pages"** 
1. Make an appointment
2. Register for care
3. Pharmacy and prescription refills
4. Request your medical records
5. Billing and insurance
6. Contact us
plus:
1. DAV Vans: transportation for Veterans
2. Policies

**and Health service detail page nodes**

1. Caregiver support
2. Mental health care
3. Suicide prevention
4. Homeless Veteran care
5. LGBT Veteran care
6. Minority Veteran care
7. Women Veteran care
8. Returning service member care

- [ ] Determine value and intention of each content block for Veterans
- [ ] Determine value and intention of each content block for Business
- [ ] Determine appropriate governance level (national? system? facility?)
- [ ] Identify new content types (based on “governance sandwich” pattern) 
- [ ] Identify content types which need expansion
- [ ] Determine approach for Related Links (need to be partially localizable?)
- [ ] Determine approach for national template 
- [ ] Identify SEO opportunities (schema.org?)
- [ ] Consider tech debt incurred by implementation 
- [ ] Identify risks to scaling, performance, etc.
- [ ] Identify areas for MVP 

## Acceptance Criteria

VAMC system editor at the local level can:

- [ ] add local content
- [ ] view national content 
- [ ] view who can edit national content
- [ ] cannot edit national content 
- [ ] view how and where localized content will render
- [ ] anticipate how content changes will impact updates/deployment and blast notifications to Veterans

VHA editor at the national level can:

- [ ] view all versions of these pages from all VAMC systems in one spot (Dashboard)
- [ ] find and interact with national detail page content 
- [ ] can bulk edit national content
- [ ] can easily access and add a token
- [ ] can view informational errors about tokens
- [ ] view how and where national content will render
- [ ] anticipate how content changes will impact update/deployment and blast notifications to Veterans
