### ISSUE TITLE
Internment language for NCA operating status alert

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8530]
## User Story or Problem Statement
How might we use facility operating status displays to direct Veterans to contact a cemetery directly for special internment information during times of adjusted operating status?

## Goal
- Add NCA specific language to NCA facility operating status alerts Veterans are directed to contact a cemetery directly 

---
## Tasks

![cemetery alert addition.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/0c557d53-04c7-4de6-a133-25a1c8e24410)

- [ ] Add specific language to NCA facility operating status alerts to FL detail pages when **facility type = cemetery and operating status = "Closed", "Notice" and "Limited Services and Hours"** 

> TBD

- [ ] _If the proposed language references a website, the language will only display when the website is available_
- [ ] _If the proposed language directs the Veteran to call, the language will only display when a phone number is available_
- [ ] _If the proposed language references a website, the website will be an actionable link for sighted and non-sighted users and users of assistive technology_
- [ ] _If the proposed language directs the Veteran to call, the phone number has the visual appearance and functionality of a link_
- [ ]  _If the proposed language directs the Veteran to call, the phone number is actionable for devices with calling capability_
- [ ] Any phone numbers and website links displayed within Facility Locator will be accessible to users with assistive technology_

## Acceptance Criteria

- [ ] Phone numbers and website links displayed within Facility Locator will be accessible to users with assistive technology.

Given a Veteran views the Facility Detail page for a **cemetery** with an operating status of **"Closed", "Notice" or  "Limited Services and Hours"**
- [ ] The Veteran can view the operating status for the facility
- [ ] the status displayed on the detail page is consistent with the status displayed on the search results card for that facility
- [ ] the [TBD] additional language is displayed
- [ ] _if the proposed language references the website, the language will only display when the website is available_
- [ ] _If the proposed language directs the Veteran to call, the language will only display when a phone number is available_

Given a Veteran views the Facility Detail page for a **cemetery** with **"Normal"** operating status 
- [ ] **No** operating status is displayed on the facility's detail page or search results card 
- [ ] The newly additional language is **not** displayed

Given a Veteran views the Facility Detail page for a **VA health, VA benefit or Vet Center location** with an operating status of **"Closed", "Notice" or  "Limited Services and Hours"**
- [ ] The Veteran can view the operating status for the facility
- [ ] the status displayed on the detail page is consistent with the status displayed on the search results card for that facility
- [ ] the newly added language is **not** displayed
- [ ] Existing functionality is maintained

Given a Veteran views the Facility Detail page for a **VA health, VA benefit or Vet Center location** with **"Normal"** operating status 
- [ ] **No** operating status is displayed on the facility's detail page or search results card 
- [ ] The newly additional language is **not** displayed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Blocked pending language from NCA and Task Force

**Comment by davidconlon** [comment]
@brangi @mmiddaugh here is the language

If the status is not normal and the facility type is cemetery we want the language to be:

            For more information about the cemetery, including interment, visit our cemetery website. 

where "cemetery website" is hyperlinked text to the cemetery's website.
