### ISSUE TITLE
Update Refresh Cycle of UA Data Sets from 'Replace' to an 'Append'

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#85319]
### Description
As part of our work on the GA4 migration, we are looking to update any BQ datasets that use UA GA data that currently use a `Replace`, to an `Append`. This will ensure that once we cut-over to GA4 data, the existing UA data will be safe, and unchanged.

This will also have the added benefit of being more efficient on the BigQuery side of things.

---

### Tasks

- [x] Identify datasets that use a `replace` for their refresh cycle [here](https://docs.google.com/spreadsheets/d/10cPFUERAQCgzawjo7ZQmyjaC8B2Wjqrl3g9zNlvDzD4/edit#gid=1589604846)
- [ ] For any that use a replace, update to an append, so we can verify that data is still flowing
- [x] Mark new dataset refresh schedule on the spreadsheet.
- [x] If possible, document any savings, or reductions in BigQuery data processing costs from changes

### Acceptance Criteria

- [x] All datasets will that contain UA GA data will have their fresh cycle updated from an append to a replace.

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1, adding this card into the current sprint -- finished out the other two tasks you were assigned.

- #84587
- #84138
