### ISSUE TITLE
[CST][ENG] Update the 'Submit evidence now' link in the claim phase stepper 

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#85380]
## Background Context
In step 3 of the claim phase stepper we have a link that uses the text 'Submit evidence now' and it directs a user to the files tab. In an effort to be consistent throughout cst we should change this to match the text used on the new 5103 notice on the document request page that says 'Upload your evidence here'.

**Current Design:**
<img width="1156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67b040702cad656b64197ecbce61c5d366b5b2e4/Screenshot%202024-06-06%20at%2011.44.05%E2%80%AFAM.png" alt="Screenshot 2024-06-06 at 11.44.05 AM.png" />

**Reference to 5103 Notice ont eh Doc Request Page:** 
<img width="964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHBEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ce1896d7b38044cc9258541b6a96f8412ac45a5/Screenshot%202024-06-06%20at%2011.47.09%E2%80%AFAM.png" alt="Screenshot 2024-06-06 at 11.47.09 AM.png" />

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

## Tasks
- [ ] Update the link text to be 'Upload your evidence here

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Step 3 on the claim phase stepper uses the link text 'Upload  your evidence here' in stead of 'Submit evidence now'

**Comment by uxgary** [comment]
the[ figma file](https://www.figma.com/design/bWELjWsVqkf3BDx0PXqqam/Claim-Contextualization?node-id=1835-8794&t=LC8oq97EtyJGZvsz-4) has been updated. 

<img width="450" alt="Screenshot 2024-06-06 at 3 34 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/6ec330f3-bcdb-412f-89af-fb84cdcfcab3">

**Comment by pmclaren19** [comment]
This has been moved to Staging and looks good!
