### ISSUE TITLE
[CST][ENG] Update breadcrumb indentation 

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#85386]
## Background Context
Found that there are several pages in the CST where the breadcrumbs are not in alignment with the content on the page. This may be a wrapper issue. We should update the alignment of the breadcrumbs for the Claim Page, Claim Estimation Page, Document Request Page, Appeals Page and Stem Scholarship Pages

Claim List Page where breadcrumbs are in alignment:
![Screenshot 2024-06-24 at 2 04 45 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/06bfb455-bfad-4435-920b-5f11deff38a2)

Current Pages that have breadcrumb indentation issues:
![Screenshot 2024-06-24 at 2 04 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/044f8027-7182-40c2-bdca-7725e0b30e67)

![Screenshot 2024-06-24 at 2 42 46 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/4494364c-cb57-42df-beda-c2e0ed398cc5)

<img width="964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1pEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f490059be8431bf6bc7595270f4e30a3143a6b70/Screenshot%202024-06-06%20at%2011.47.09%E2%80%AFAM.png" alt="Screenshot 2024-06-06 at 11.47.09 AM.png" />

<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2xEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b72490911aeeed98c7b3f9340b0962276ca4aeac/Screenshot%202024-06-06%20at%2012.42.39%E2%80%AFPM.png" alt="Screenshot 2024-06-06 at 12.42.39 PM.png" />

<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6b1f60d6305fc1c0c3cd4d9678e9a89386d2f57/Screenshot%202024-06-06%20at%2012.43.36%E2%80%AFPM.png" alt="Screenshot 2024-06-06 at 12.43.36 PM.png" />

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Update the breadcrumbs on the claim page
- [ ] Update the breadcrumbs on the claim estimation page
- [ ] Update the breadcrumbs on the appeals page
- [ ] Update the breadcrumbs on the stem edu page
- [ ] Update the breadcrumbs on the doc request page

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The breadcrumbs on the claim page are in alignment with the page content
- [ ] The breadcrumbs on the claim estimation page are in alignment with the page content
- [ ] The breadcrumbs on the appeals page are in alignment with the page content
- [ ] The breadcrumbs on the stem edu page are in alignment with the page content
- [ ] The breadcrumbs on the doc request page are in alignment with the page content

**Comment by pmclaren19** [comment]
Verified in Staging and looks good!
