### ISSUE TITLE
[Epic] Pension

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#85381]
## Issue description

This epic will house work related to pension forms/from the pension team.

The tickets are organized by intake:
**Intake title as task list title**
- intake ticket
- associated child tickets (linked to epic, not nested under intake ticket)
```[tasklist]
### Pension benefits form: Direct deposit content
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77464
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77913
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77898
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77900
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/77800
```

```[tasklist]
### Pension benefits form: Intent to file content
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/78928
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79641
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/87027
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88267
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/88268
```

```[tasklist]
### Pension benefits form: Usability improvements
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82734
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85080
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/84252
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/85129
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/66842
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/67037
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/84084
```

```[tasklist]
### ITF 21-0966 Form
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74328
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/73412
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82301
```

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/48371
```

**Comment by mnorthuis** [comment]
closing product-specific epics
