### ISSUE TITLE
[BE] Monitor dashboard for more than one claim_status from BTSSS API

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#85391]
## Description
Monitor [travel claims dashboard](https://app.ddog-gov.com/sb/f327ad72-c02a-11ec-a50a-da7ad0900007-3a95d2603bfb8826abb8aa81a04efd03) for claim_status response for more than one claim status,

Note: Can only be done when all the tasks in [epic](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/84750) gets completed & merged to production

## Tasks
- [ ] [BE] **Monitor [dashboard](https://app.ddog-gov.com/sb/f327ad72-c02a-11ec-a50a-da7ad0900007-3a95d2603bfb8826abb8aa81a04efd03) for multiple claim_status response**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
