### ISSUE TITLE
Rep Status Info in Profile and MyVA

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#85459]
## Background
Our Representative Status Widget has launched!  We've met with the Profile and MyVA teams previously and they both agreed this makes sense to include in their products -- it's time to start thinking more seriously about that collaboration.  

Previously we discussed:
1. Adjusting our Rep Status Widget states to match profile patterns ([early designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2462-162679&t=DqfFgxI5L5ZmvPKf-0))
2. Including a link from MyVA to the Profile information ([early designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2712-175511&t=DqfFgxI5L5ZmvPKf-0))

## Tasks
- [x] Update designs as needed, as it's been a while since we last thoguht about this concept
- [x] Meet with Profile to get their feedback
- [x] Meet with MyVA to get their feedback
- [x] Consult CAIA for feedback
- [x] Adjust designs based on feedback
- [x] Final review with with Profile and MyVA

## Acceptance Criteria
- [x] We have designs for including representative status in the Profile and MyVA areas of VA.gov, with those team's input, and are ready to present to Governance for their review.

**Comment by oddball-lindsay** [comment]
Profile:

1. Update hub design to include the Personal Healthcare card, then request content and IA review from CAIA.
2. Consider a different pattern for the error state.
3. No additional UX Research is needed at this time.

Liz shared these links for reference:
1. https://www.figma.com/design/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?node-id=0-121&t=hUWG2oO8lbMnhS1L-0
2. https://www.figma.com/design/zb5ecY9yMnupiLjaH9UmSc/Profile---Military-Information?node-id=0-158&t=xRB50AiKVZHzS5Qx-0

MyVA:

- The card/section design doesn't make sense -- too much information for this screen
- Suggestion: add a link to the list on the right of the "Claims and Appeals" section, or possibly in the card itself; the link would point to the rep info in Profile.  "Need help with something?" was thrown out, but we can consult CAIA as well.
- The link could be enough for a first iteration in MVP, let's keep talking about this one!

Screenshot of Profile hub with the Personal health care card:
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4c03d1e135f12a7fbd02c5dd87e17c5dc62458a/image.png" alt="image.png" />

**Comment by mtri** [comment]
[Engaged CAIA on the intake ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809#issuecomment-2174517658)

**Comment by mtri** [comment]
Conversations with CAIA and team have led to adding the representative type to the [Representative Status Widget](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1283%3A176978&node-id=1411-386887&t=7YMfC0fGyY4YaizE-0&scaling=min-zoom&content-scaling=fixed) and to [the profile page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6939-285692&t=7YMfC0fGyY4YaizE-11).

Profile design is in finalizing steps with a couple questions to CAIA.

**Comment by mtri** [comment]
Figma links:

[Profile hub](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=7455-109980&t=ZceQFAL7y5VpUUMj-11)
[Profile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=7528-75290&t=ZceQFAL7y5VpUUMj-11)
[myVA](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=7455-113186&t=ZceQFAL7y5VpUUMj-11)

Next steps to validate with profile team and then bring to Midpoint.

**Comment by oddball-lindsay** [comment]
@oddball-lindsay ask in auth-exp how Profile and MyVA would like to review designs (synchronous vs. async)

**Comment by oddball-lindsay** [comment]
Midpoint Review is scheduled! https://github.com/department-of-veterans-affairs/va.gov-team/issues/86934
