### ISSUE TITLE
[DevOps] Try to move `vaec-cie` Terragrunt system away from `mise`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#85464]
## Description
Currently, `terragrunt-action` relies on `mise` under the hood. After some aggravation, I adopted `mise` to install `npm`, but I don't like relying on it and we should eliminate it if and when possible.

Unfortunately, attempts to install `npm` like a normal person failed with strange errors in the `terragrunt` action script. I'm busy enough debugging my own crap code, I don't really have the time to debug anyone else's. So that brought me to using `mise`.

## Tasks
- [x] [DevOps] Figure out how to use `apt` or `snap` or whatever to install `npm`.
- [x] [DevOps] Eliminate the uses of `bash` in `lorota` Terraform `null_resource` `local-exec` provisioners and other places where it is needed currently.

## Acceptance Criteria
- [x] We don't use `mise` anywhere.

**Comment by ndouglas** [comment]
I did this when I removed `terragrunt-action`.
