### ISSUE TITLE
[BE] 10-10EZ - Improvements: Add a new statsD value for synchronous submissions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#85478]
## Background
While troubleshooting some validation errors with the 10-10EZ, Brandon suggested we try to differentiate between synchronous and asynchronous submissions, which could assist with troubleshooting and error identification.

## Tasks
- [x] Add a new statsD value for synchronous submissions
- [x] Perform testing to ensure the submission tracking is working as expected for both sync and async submissions
- [x] Review with PM before closing

## Acceptance Criteria
- Additional submission tracking is in place to differentiate between synchronous and asynchronous submissions

**Comment by allanto-ah** [comment]
This is completed. Closing
