### ISSUE TITLE
Discovery for 80225

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#85483]
### Description

- The Public Websites team uses **ngrok** for local development when traditional methods are down (CI issues, SOCKS blockers, etc.).
- The Public Websites team wrote up some documentation on how to use **ngrok** when running `vets-website` and `content-build` locally. 
- We need to determine whether this tool will be allowed for use and where the information can fit in our IA.

### Tasks
- [x] Read Public Websites team docs (below in Relevant URLs)
- [x] Reach out to Randi Mays (Public Websites Team) to discuss the new page using these docs

### Acceptance Criteria
- [x] Confirmed whether to create this new page

### Relevant URLs

Public Websites team docs for `ngrok`: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17306#issuecomment-2043002447

Various `ngrok` documentation links are included in this write-up.

**Comment by CherylEvans** [comment]
@jknipes Verified with SME @randimays that Ngrok is not authorized for use. 
I did create a draft of [How to use grok for testing local development builds](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3210969089/Cheryl+Draft+-+85097+-+How+to+use+ngrok+for+testing+local+development+builds), before I was informed the tool wasn't authorized.
