### ISSUE TITLE
Redesign Covid-19 Dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8549]
## User Story or Problem Statement
How might we redesign the covid-19 dashboard so that we can better align with our user's need and condense the dashboard for better readability?

**Pain Points:**
- There are too many metrics on the dashboard & it has become more of a database
- It's difficult to scroll and wayfind
- It's difficult to understand the holistic picture
- It's difficult to understand which parts of the dashboard are used for product decisions

**Original User Story:**

As a healthcare decision maker, in order to prevent VA system overload and covid spread at medical centers, I need to:

- direct patients to self-service information and chat tools
- divert in-person appointments to telehealth
- quickly scale telehealth appointments
- triage new appointment requests through the above

As a VHA decisions maker, I need to be able to:
- monitor longitudinal problems
- use available VA.gov user metrics to get ahead of triaging and scheduling issues
- monitor telehealth usage fairly regularly.

## Goal
Redesign the [covid-19 dashboard](https://va-gov.domo.com/page/1872052027) to be easier to use.

## Objectives or Key Results this is meant to further
O2: Customers use qualitative and quantitative user data to build and iterate on VFSs.
				
---
## Tasks
- [x] Kevin to meet with Analytics & Insights team after meeting with VA stakeholders
- [ ] Brainstorm ideas for redesign
- [ ] Prioritize ideas based on feasibility and user goals
- [ ] Communicate with stakeholders
- [ ] Redesign dashboard

## Acceptance Criteria
- [ ] Stakeholders can more easily use the dashboard for its intended purpose
- [ ] Stakeholders know there has been a redesign

## Nice to Have
- Use this discovery as a case study for scaling dashboards in Domo to rollouts and performance metrics

**Comment by joanneesteban** [comment]
### Initial Ideas

- Creating subpages on the dashboard and hyperlinking a table of contents to the subpages
![image](https://user-images.githubusercontent.com/48964695/80600496-7a01f780-89fa-11ea-8e44-7168d382a76d.png)
- Exploring VA Tableau options
- Collaborating with Front End Tools to pull the charts into a webpage

**Comment by joanneesteban** [comment]
## Question for DEPO

- Who is the product owner?

**Pain Point:** It's difficult to understand how to prioritize work on the dashboard without understanding who the primary stakeholder is/what the primary user story is.

**Comment by KevinMHoffmanUSDS** [comment]
@joanneesteban Thanks for this question! I'm going to say it's @leahbannon for now, but we can discuss/revisit. 

A few high level questions I'd love to explore:

* What is the overall percentage of manual vs. automated data being displayed (e.g. percentage of charts)
* Do we want to consider multiple, cross linked dashboards?

**Comment by amycesal** [comment]
Hey @KevinMHoffmanUSDS a little insight into what is pulled manually vs. automatically for each data source 

| Manual  | Automatic  | 
|---|---|
|11 sources | 7 sources |
| - Veterans Crisis Line<br>- VA311<br>- National Call Center<br>- Health Resource Center<br>- Veterans Experience Office<br>- Health Enrollment Center<br>- VETtext<br>- Annie Text Message<br>- MHV Response<br>- VAOS monthly usage<br>- Social media themes  | - VA COVID-19 Chatbot<br>- VA.gov Coronavirus FAQ page<br>- VA.gov homepage<br>- Coronavirus alert banner<br>- Overall VA.gov mentrics<br>- PublicHealth.va.gov Information<br>- mentalhealth.va.gov/coronavirus  |

Most of the automatic sources have multiple charts pulled from them (like amount of users and bounce rate), but some of the manual source do too, like MHV. The charts pull automatically from the source, so the level of effort is really on updating the source. 
Hopefully that's helpful.

**Comment by joanneesteban** [comment]
Hi Kevin & Amy! 

> Do we want to consider multiple, cross linked dashboards?

This might be our most feasible avenue given the hyperlinking constraints on Domo. Another thought is that we could have the table of contents & summary as the rollup "dashboard" that links to the sub-dashboards. 

>How might we organize content to support the genres of decisions that people make? E.g. data/charts that support understanding behaviors around content, vs channels, vs single product efforts (e.g. chatbot) etc.

It would be helpful to know what decisions users have already made by using the dashboard, and if we can get which metrics helped them with those decisions, that would be a bonus.

**Comment by KevinMHoffmanUSDS** [comment]
Posting notes here from my discussion with Lauren and Leah. Action items are at the top.

## Action Items

- [ ] Create two separate dashboard views, one focused on content, and one focused on health tools. Each should have a statement of purpose. Here's an example. "Covid-19 Content Usage Dashboard. This dashboard collects data about the usage of content supporting Veterans through the Covid-19 pandemic. It is intended to support making the most impactful decisions about what kinds of content should be used and how that content should be distributed across multiple channels and tools. Quantitative data  that represents user behaviors should be used to guide decisions about where content will be the most effective. Other kinds of data, such as summaries of categories or anecdotal data from social media should inform how to examine behavioral data, but should not guide decisions about content 
- [ ] Consider high level framing language (and labels throughout charts) around "Behaviors" vs. "Anecdotal/Summary/Other Data" Behaviors Data should guide decisions, Anecdotal data should guide how to discuss and look at Behavioral data. 
- [ ] Articulate a roadmap for handoff so that the Analytics team is no longer involved in weekly analysis of meaning of data, report creation, etc. 

## Notes

* Lauren - I need to share this out in various forms 
	We have to share this out a fair bit
	Putting the data into a format that’s shareable - how can we make that easier
	There are definitely issues that we are monitoring - floods of calls to different contact centers, how intense or normal those calls are, traffic to different pages, engagement with those pages, health of a lot of the health tools that we are pointing Veterans to

Content piece, themes out of social media, themes out of call centers, links that is being engaged with, really telling for us to go back recommend additional content, prioritizing different kinds of content, 

I support the potential division of content use cases and health tools use cases

* Manual entry - we are definitely getting things, all kinds of inputs because the integrity of data monitoring varies widely, some people send us an email/ppts/CSV files, etc. It’s very hodgepodge - heard nothing about the Google solution, curious how it works

Leah:  Decisions and sources of data that are interesting, worrying about astroturfing, e.g. the playbook - only 8 percent of people think of businesses - is this a valid reflection of things? Is it a vocal minority? Astroturfed, gets into my larger anxiety, are we falsely implying correlation. 

Social media - the ones I just got this week, people pushing back on the idea of 4th mission, previously there was bullet points around opening certain things “Political appointees at the VA might say ‘I really care a lot’”

When we talk about the top topics from the call centers, that could be a similar problem, It may not affect the vast majority of people, it’s the vocal minority

We export it - parts of it go to different people, different places

We don’t want to give all of Congress, all of OMB, anyone who have to have visability of the dashboard

Supporting Congressional reporting

VEO - there is someone in VEO that Chante has been working with that is pulling together the metrics, provide that person with access

My pull of everything on Friday is going out to support a bunch of people with the same stone

Group of people is interested in these pieces of data, etc. 

Groups of people that have specific dashboard views

Joint task force has used it to say “these are impactful ways to do outreach, these are less impactful ways.” Has helped from the trend of using the VA.gov Coronivirus page, not well used, people don’t go to it, or stay there very long

Helped them be more willing to be more open to not driving content to that page, the other tools are performing

Universe of things I’m aware of with how the data is being used, and the things that I’m not aware of. A complete picture of the Veteran Facing Content team, what they are doing - different pieces of the puzzle. Some value in a full summary. 

I don’t know that specific dashboard would be useful, I don’t know all the different use cases, they appreciate seeing the full deck each week. 

What they are pulling together are PPTs, Word documents, if they can take a slide and reuse that it’s easier than figuring out how to download things. 

I’ve had to explain how screen grabs work, tech savvy is low. 

Lauren: It’s been enormously successful to have data, Charles looks at it daily, I look at it daily, sometimes I need to be a jerk to people, leaning on this data helps me be a jerk with cause. It’s been really helpful, the PPT PDF extract seems like it’s working, now it’s working pretty well. That is hopefully easier, even if they didn’t have to do that, they wanted me to do it, I can do that if it works. 

I’m open to a content focused one and a health tools performance dashboard. It makes sense to separate those two, we are using the data in slightly different ways. That’s a definitely worth pursuing. 

Leah: Can we remove social media in the dashboard? 

Lauren: part of the reason I’m using it, “we’re hearing this from Veterans” when VA says this, this prevents the “social media” discussion, the report shows - it becomes a source of truth for disambiguating arguments that are anecdotal

The stuff recently with the masks, between that, hearing it in a couple of other places, we know that there was a policy around employee PPE, no one was creating content for Veteran facing masks, knowing it’s popping up for Vets, I was able to bring that up. 

Framing it appropriately, I use it in two different ways… how could we frame data sets as “anecdotal?” 

Behaviors Data should guide decisions, Anecdotal data should guide looking at Behavioral data.

**Comment by joanneesteban** [comment]
## Next Steps for VSP Analytics & Insights
[Mural Source](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1589831736245/4b6fc587889e8d4acd6206f6502398c0eb38c235)

NOW
- Set up meeting with Danielle & Jenn for Content

NEXT
- Set up meeting with Patrick, Lauren, & Charles for Health Tools

FUTURE
- Set up meeting with VEO for contact center materials

THINK ABOUT
- VEText decisions with Clarice
- New tool decisions with DEPO

**Comment by joanneesteban** [comment]
Covid Dashboard "redesigned" Sprint 28. Closing this issue.
