### ISSUE TITLE
Documentation for DataDog mapper

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#85510]
## Issue Description
As a follow-up for ticket [83288](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/83288), documentation for the DataDog Mapper was needed for this work. 

## Tasks
- [x] Create the documentation for DataDog Mapper in order to ensure that if this event or issue happens again, the team can reference what was done to troubleshoot and fix the event and either re-create it to fix again, or use another strategy that was not used previously. 

## Success Metrics
- [x] Documentation is completed and clear for those who will want to reference it in the future. 
- [x] Documentation is finalized and archived

## Acceptance Criteria
- [x] Final, approved documentation for the DataDog mapper solution.
- [x] Documentation draft can be found in Confluence [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3210477598/Datadog+Mapper)
- [x] Final technical documentation can be found in GitHub here (**link to come**)
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
@flooose will take a peek for review

**Comment by Kshitiz-devops** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/datadog-agent/README.MD
