### ISSUE TITLE
Analytics & Insights: Optimize GA4 Events to Reduce Billable Hit Count

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#85525]
## Epic Description
Our team manages our GA4 Account, and Properties. We only have a set amount of prepaid hits for our GA4 account, which is 6 Billion.

With Mobile's growth, which accounts for over 1/3 of our monthly hit count, and with more tracking added to our VA.gov Properties -- we are running through these hits at a much faster rate than anticipated. 

The cost for every million events that we are over is $20, ($20,000 for every billion).

This epic is to account for both identifying where certain events are firing when they don't need to be, or in some cases firing twice for the same event. We need to optimize our tracking to ensure we aren't incurring billable events when we don't need to be.

This epic also includes some cost projections and analysis our team is running.

### Status:
| Date | Status | Launch Date  | Notes |
| ----- | ------ | ------------------------- | ------ |
| 8 November 2024 | _Done_ | On Track | Our team performed some work optimizing header events this past sprint -- we are going to continue building out projections for Mobile and Web's growth. |
| 17 October 2024 | _Done_ | On Track | Our team does _not_ manage hits/events set-up by the Mobile Team -- this gives us limited ability to directly optimize, and plan for their GA4 hits/events. |
| 27 January 2025 | _Done_ | On Track | Projections for remainder of year established. |
| August 2025 | Complete | Q3 | [Phase 1 Dev: Budget Burn Rate Visualization] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/115637) |
| August 2025 | Complete | Q3 |[ [Budget Burn Rate chart] ](https://docs.google.com/spreadsheets/d/1q5s3YQunMuNynERzxL5fdHtbRCGoYkho46sSWy7S8Sk/edit?gid=1216784722#gid=1216784722)

### High Level User Story
As a member of the Platform Analytics & Insights Team, I want to make sure our GA hits and events are set-up in a way that is optimal, so that we aren't generating unnecessary, or redundant events, and we don't run through our prepaid amount of hits too quickly.

### OKRS
1. Our platforms are the best way to deliver products at VA
- Our platforms power twice as many interactions compared to last year

### Hypothesis or Bet
If we devote time to remediating our GA4 events, we won't incur hits when we don't need to be, making us more efficient against our prepaid amount.

### We will know we're done when... ("Definition of Done")

- [ ] We have a defined strategy for forecasting the growth of Mobile's events.
- [ ] Areas of VA.gov where multiple events are firing for the same interaction have been reduced.
- [ ] Projections have been created for when we will go through our prepaid events.

---

### Launch Date
September 2024

### Projected End Date
Ongoing -- targeting January 2025

### How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by raywangoctova** [comment]
@johnny-jesensky-adhoc Can we narrow the scope of the work for this issue to only GA4? How about the other two bullets on BigQuery and Domo as separate issues?

**Comment by AdamOye** [comment]
| August 2025 | In-work | Q3 | [Phase 1 Dev: Budget Burn Rate Visualization] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/115637) |

**Comment by AdamOye** [comment]
| August 2025 | Complete | Q3 |[ [Budget Burn Rate chart] ](https://docs.google.com/spreadsheets/d/1q5s3YQunMuNynERzxL5fdHtbRCGoYkho46sSWy7S8Sk/edit?gid=1216784722#gid=1216784722)
