### ISSUE TITLE
Datadog release discovery

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#85524]
## Issue Description
Datadog releases new features and functionality many times per month. Some of it is relevant to us, some of it isn't. It would be good to read through the new releases periodically and report on any updates or features that are relevant to monitoring VA.gov. 

**Release page for DD Govcloud: https://vagov.ddog-gov.com/release-notes**

Thoughts:
- Review the release notes quarterly? Monthly? Recently, there have been 3-4 releases per month, so a monthly cadence might be more manageable? 
- Report findings during Platform Demo? CoP meetings? Slack message (with or without screenshots or a video, if necessary)?
- An epic (`Datadog Release Radar`? 😄) could be created with tickets assigned to sprints throughout the year. 
- I think reviewing the release notes and sharing findings should be no more than a `3` amount of work (i.e. I don't think we should spend much time on this, but we do want occasional eyes on the new releases and to share what we learn).

## Tasks
- [ ] Look at [Release Notes](https://vagov.ddog-gov.com/release-notes) page and determine a what cadence reviewing the updates makes sense
- [ ] Determine how we want to deliver these findings (it can always be changed later if we find a better forum for delivery).
- [ ] Create an Epic with tickets inside covering the next 6-12 months of future releases.

## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] New tickets are created and placed in an Epic and assigned sprints based on the determined cadence.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
