### ISSUE TITLE
Determine Feasibility of Automating Contact Center Reports

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8552]
## User Story or Problem Statement
How might we automate monthly contact center reports so that we can alleviate our manual work and introduce contact center information data to VFS teams quicker?

## Goal
Understand how feasible it is to automate this report. Understand how that report may be designed.

---
## Tasks
- [x] Meet to discuss automation options
- [ ] Document findings & share out with team

## Acceptance Criteria
- [ ] Findings are shared with team to put into roadmap

**Comment by Kimberley2019** [comment]
Meeting was held on 4/30/2020 with all assignees including Amy.
The following are the action items:
- [x] @Kimberley2019 to provide Jon the recording of monthly report training with Chante and I.
- [ ] @clantosswett send Jon and Brian the most recent issues spreadsheet.
- [ ] @Kimberley2019 Create a markdown file of the monthly reporting steps to provide to Jon and Brian.

**Comment by Kimberley2019** [comment]
Here is a brief of the Contact Center Reporting documentation.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/monthly-report.md

**Comment by jonwehausen** [comment]
## Update 5.11

Thank you @clantosswett and @Kimberley2019 in your patience on this request. 
cc: @joanneesteban 

### Logistics 
After watching the video on the process, here's what we've setup: 
- [Here's a raw dataset](https://va-gov.domo.com/datasources/5f033e5c-f6d4-46e0-b684-b89f4cbc41b4/details/overview) that can house all of the issues
- There's a DOMO ETL attached to the raw spreadsheet that automates the "tiering" based on status in the raw speadsheet (_These can be adjusted accordingly_)
   _- Resolved = Tier 1_
   _- Follow Up = Tier 2_ 
   _- Escalated = Tier 3_
 - Staged an example table for the ["Contact Center Summary"](https://va-gov.domo.com/kpis/details/1913521488) that does the totaling of each business line and tier
 - Staged an example table of the ["IRIS Issue Breakdown" report](https://va-gov.domo.com/kpis/details/493861966). 
- Staged an example table of the ["WHVAH Issue Breakdown" report](https://va-gov.domo.com/kpis/details/577383189)
- We could create and mirror these for the remaining breakdown pages
- Created a[ seperate mockup dataset for NCC](https://va-gov.domo.com/datasources/bc5e0dc6-ebfd-4fb0-862f-9a73856377c3/details/data/table) since video mentioned don't typically receive regularly. Would like to confirm with you all if necessary


### Process Flow (Month-Over-Month Changes)
- Each month you can go into the raw dataset and add the latest data for that month
- Once the webform is updated, the ETL to do the tiering will kick-off automatically and each table will update 
- To filter each table on the breakdown reports a monthly basis to be the relevant data for that month, here's what I'm thinking: 
  - **We would need to go into each chart in analyzer and adjust the "DATE_CREATED" to be the new month date range** -- [here's the IRIS example
](https://va-gov.domo.com/analyzer?pageId=-100000&cardid=493861966)
![image](https://user-images.githubusercontent.com/48527022/81614362-f5c25380-93ad-11ea-80fd-00c88378ff58.png)
- If we get you guys setup with a dashboard page then you could also export to PDF if that's part of your process for delivery

### A couple things to consider
- We may not be able to get the DOMO tables in exactly the same format/visualization in which you have been delivering them in Excel simply due to DOMO visualization limitations. 
- We'll have to talk more in-depth about certain data points you guys inconsistently retrieve data for and determine how this affects the automation

**Comment by joanneesteban** [comment]
Grooming metrics is done! Will cont working in [9026](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/9026)
