### ISSUE TITLE
Remove Code Climate from vets-website CI

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#85534]
## Issue Description
Code Climate is set up in vets-website CI and fails on many workflows for reasons we don't really agree with restricting developers on. While our original goal was to adjust how restrictive it was being, we were unable to locate the owner of our account for code climate. As such, the only recourse we have is to remove the GitHub integration entirely from the GitHub side. This will allow us to get a realistic picture of if a PR is passing CI or not from the overall PR list.

Steps taken to inquire about who owns this account:

1. Inquired with Clint Little.
2. Inquired with remaining members of the former Platform Release Tools Team.
3. Inquired with Andrea Hewitt.

---
## Tasks
- [x] Remove code climate app from having access to vets-website.
- [x] Ensure that PRs can still merge unobstructed and that errors are only showing for things we care about.
- [x] Document the reasoning for removal in appropriate document (Code climate documentation or CI documentation).

## Acceptance Criteria
- [x] We can now get a clear picture of the status of outstanding PRs from the overall PR list.
- [x] The reasoning behind the removal is documented in either existing code climate documentation, or as a part of front end CI documentation.
---
