### ISSUE TITLE
[CST] Create Active Link Component and replace areas in the code where its used

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#85537]
## Background Context
In an effort to clean up our code based we should create a new component for links that are using the Link import from `react-router-dom-v5-compat` (react router link) so there is one source of truth and its easier to use these types of links.

## Investigation
These are the following files in claims status tool that are using this link
- AddFilesFormOld.jsx
- AskVAToDecide.jsx
- ClaimPhase.jsx
- ClaimsDecision.jsx
- ClosedClaimMessage.jsx
- FilesNeededOld.jsx
- FilesOptionalOld.jsx
- NeedFilesForYou.jsx
- AppealNotFound.jsx
- Automated5103Notice.jsx
- FilesNeeded.jsx
- FilesOptional.jsx
- ClaimLetterSection.jsx
- ClaimPhaseStepper.jsx
- ClosedClaimAlert.jsx
- RecentActivity.jsx
- WhatWeAreDoing.jsx
- ClaimCardLink.jsx
- appeals-v2-helpers.jsx

### New Feature
Why are we doing this work?
- Clean up code

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Engineering 
Component name should be `Link`

Props should include the following: 
- Text: string (this will be the link text)
- All current props that the react router link has access to

## Tasks
- [ ] Create new component Link

Update all usages of Link to use the new Link component
- [ ] AddFilesFormOld.jsx
- [ ] AskVAToDecide.jsx
- [ ] ClaimPhase.jsx
- [ ] ClaimsDecision.jsx
- [ ] ClosedClaimMessage.jsx
- [ ] FilesNeededOld.jsx
- [ ] FilesOptionalOld.jsx
- [ ] NeedFilesForYou.jsx
- [ ] AppealNotFound.jsx
- [ ] Automated5103Notice.jsx
- [ ] FilesNeeded.jsx
- [ ] FilesOptional.jsx
- [ ] ClaimLetterSection.jsx
- [ ] ClaimPhaseStepper.jsx
- [ ] ClosedClaimAlert.jsx
- [ ] RecentActivity.jsx
- [ ] WhatWeAreDoing.jsx
- [ ] ClaimCardLink.jsx
- [ ] appeals-v2-helpers.jsx

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] New component called Link exists
- [ ] All react router links are replaced to use this new componet
