### ISSUE TITLE
Content Edits for #85403

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#85535]
## Issue Description
Content Edits according to 85403

## Tasks

- [x] Review https://github.com/department-of-veterans-affairs/va.gov-team/issues/85403
- [x] Make content updates to the website accordingly
- [x] Prepare page for deployment

## Acceptance Criteria

- [x] Page is updated with current information

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/85535?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by CherylEvans** [comment]
@jknipes [Page](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog) updated with the correct link for the [Okta account creation ticket](https://jira.devops.va.gov/servicedesk/customer/portal/1/create/1233).
Once deployed, I'll review the changes and close this ticket.

**Comment by CherylEvans** [comment]
Page deployed via SVP, link updated. Closing ticket.
