### ISSUE TITLE
Schedule Domo Datasets to Append GA4 Data in BigQuery

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#85549]
### Description
Once we have finalized our data QCs, we will start to append GA4 data on top of the existing UA data in our Domo datasets that power our reports.

This will be done in a series of waves, based on impact and priority. The timing on waves can be found [here](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3213885442/GA4+Migration+Domo+Report+Updates). 

---

### Tasks

- [x] For Wave 1, schedule daily datasets to append GA4 data in the week of **July 1 - July 5**
- [ ] ~For Wave 2, schedule weekly datasets to append GA4 data on **July 8 - July 12**~
- [ ] ~For Wave 3, schedule monthly datasets to append GA4 data on **July 15 - July 19**~
- [x] Confirm GA4 data has appended with relevant fields in Domo.

### Acceptance Criteria

- [ ] ~All~ Wave 1 UA-driven datasets tied to prioritized Domo dashboards have been scheduled to `append` with GA4 data.

**Comment by johnny-jesensky-adhoc** [comment]
We completed an initial wave of pushes, but we are still waiting on some QC items before pushing the rest -- to best capture the work completed, I broke this out, and moved the remaining tasks into this ticket, which we'll work on next sprint.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/87674

FYI @dorseypa1
