### ISSUE TITLE
Collaboration Cycle - Discovery for bringing the mobile app into Collaboration Cycle

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#85548]
## Status
_Update each sprint until completed_
| Date | Status | Launch Date | Notes |
| ----- | ------ | ------------------------- | ------ |
| 12/18/2024 | In progress | On track | Met with mobile app SMEs. Planning final exercise for confirming process changes. |
| 12/4/2024 | In Progress | On-track | Met with OCTO-DE leads, planning to sync with Mobile App team next. |
| 11/20/2024 | In Progress | On-track | Questions grouped and prioritized, ready for OCTO-DE to answer in next sprint |
| 11/6/2024 | In Progress | On-track | More findings than expected, so we'll need to add a task for prioritizing unknowns |

## Problem Statement 
Governance has been informed that soon, VFS teams will begin building the mobile app version of their products, and not just the web version. Up to this point, the Flagship Mobile team is the only team that has built on the mobile app. As more and more Veterans are using the mobile app each day, it is important that Governance team begin enforcing standards via the Collaboration Cycle for all mobile app products and services. However, the current Collaboration Cycle process, including Kickoff, Design Intent, Midpoint Review, Staging Review, the VA.gov Experience Standards and the QA Standards, are only intended to cover web, and not mobile.

The goals of this initiative are to determine where our process and/or defined standards need to be modified so that the Collaboration Cycle can support mobile app products. 

How might we identify the gaps in coverage or knowledge from web to mobile for the various practice areas?
How might we modify our VA.gov Experience standards for mobile coverage?
How might we modify our QA Standards for mobile coverage?
How might we determine if any process changes are necessary?

Artifacts from OCTO:

- [Roadmap](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714496264267/055358e22d282e0147c8908764c196f501901172?sender=b22e125b-e7c7-44ab-adf8-72bdf9d7678a) for bringing Mobile App into VA.gov Platform
- [Mobile App Design System](https://department-of-veterans-affairs.github.io/va-mobile-app/) 

### Notes from refinement 6/13

- What is the mobile app used for?
- What is the plan if/when the components differ?
- How do we test on the mobile app without mobile devices?
- "we don't know what we don't know" "this is squishy"
- Test, demo, play around with the mobile app in demo mode
- Review their documentation
- Go in blind or walk through from the team?
- In case anyone wants to play with demo mode...
   1. Download and open the app
   2. Tap on the VA logo 7 times
   3. Enter password `Zhuzh-it`
- The do have robust IA documentation (plus!)
- Possibly approach it like a DST SR

### Notes with Matt 6/14

- North star: any team can work across modalities (web or mobile)
- will take a while to get there
   - teams don't have expertise
   - teams struggling to find mobile engineers-
 -  want to have a team pilot, but having a hard time finding folks to support on the contracting side
 -  no timeline as of yet
 -  important, but not a fire drill

### Notes from Refinement 8/22

- in Mobile app, they have headings but no heading levels. In mobile we have gesture controls - this doesn't exist on the web. Not sure how extensively current mobile app implements said gestures
- Keyboard interaction might also differ.
- It is possible that web and mobile content might differ.
- For IA, how different operating systems behave differently w/ built in navigation. For example IOS and Android have different back buttons that behave differently.
- Some things are consistent from web to mobile, such as testing for the happy path and documenting user flows.
- All QA standards should apply, but E2E testing would be different. Mobile app would not have cypress testing.
- We have to get up to speed on what the standards are for a mobile app. What are the native things to an app? What are the differences between web and app?
- We need to have a conversation about devices. Is the expectation that we test on both android and ios? do we only need to test on 1? 
- Is the decision of whether something gets built for the app going to part of PO sync? YES
- Tools: What do we need to have?
- Education: What do we need to know?
- Process mods: What do we have to do?

## Hypothesis or Bet
If we complete research on the differences between web development and mobile development, then we'll understand how our process and/or standards need to change in order to support mobile.

If we document a plan for how we'll modify Collaboration Cycle to support mobile, then we'll be prepared for when VFS teams begin bringing mobile products through Collaboration Cycle.

If we educate ourselves on mobile development, then we'll have the confidence to give VFS teams guidance on building a mobile product that meets our defined standards.

## We will know we're done when... ("Definition of Done")
- [ ] We have determined what additional education may be needed for our practice area specialists.
- [ ] We have identified which VA.gov Experience Standards are not applicable to mobile.
- [ ] We have identified which QA Standards are not applicable to mobile.
- [ ] We have documented where the gaps are for mobile coverage in our VA.gov Experience Standards.
- [ ] We have documented where the gaps are for mobile coverage in our QA Standards.
- [ ] We have identified if our process for supporting the Collaboration Cycle Kickoff needs to be modified.
- [ ] We have identified if our process for supporting the Design Intent needs to be modified.
- [ ] We have identified if our process for supporting the Midpoint Review needs to be modified.
- [ ] We have identified if our process for supporting the Staging Review needs to be modified.
- [ ] We have determined if our practice area specialists will need access to additional tools and/or resources

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
January 2025

## Launch Checklist
<details>
  <summary>Toggle Launch Checklist</summary>

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

</details>

**Comment by shiragoodman** [comment]
@humancompanion-usds Planning. No timeline is currently set, but have availability to begin in September.

**Comment by shiragoodman** [comment]
Notes from Governance team at 10/3 Refinement:

- Concerns from Mobile app team about the coding standards when mobile becomes applicable at Arch Intent
- Need to connect with Matt on the future of the Mobile App team.
- Maybe we don't need the mobile team, but maybe just an example of a mobile product? like IIR today?
- Native mobile a11y and web a11y are fundamentally diff things. code level "stuff" that's different. No preference on whether that happens within the research or outside of it, it's happening. 
- Should we invite the mobile app team to sit in on touchpoints?
- Let's introduce a 3rd prong to our research for questioning the mobile app team and understanding their experience.

**Comment by humancompanion-usds** [comment]
@shiragoodman - Let's discuss tomorrow getting input from @rachelhanster before 11/18. We can also discuss how we are involving the mobile team in this discovery work as well.
