### ISSUE TITLE
Determine Process Flow for the Covid Dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8555]
## User Story or Problem Statement
How might we flesh out our process for updating the covid dashboard so that we can understand who owns what and grab better context for the information we're adding to the dashboard?

## Goal
Storyboard our process for updating the covid dashboard.

## Tasks
- [ ] Create storyboard
- [ ] Meet as team to discuss
- [ ] Agree on final solution
- [ ] Readout

## Acceptance Criteria
- [ ] VSP understands how to update the covid dashboard

**Comment by joanneesteban** [comment]
## List of Things
_All the things_

### Additional Pain Points
- Who should own which part of the process and how do we make sure there isn't a single point of failure? (documentation on how-to)
- What do we do when we receive data with no context?
- If there are multiple people who own a part of the process, how do we communicate that it's been done?
- What's our timeline for getting things done?
- Is there a better way to communicate with our teammates when things are completed so that they can get started? How do we better swarm?

## Draft Process
**1. Get data:** 
- reach out to stakeholders and get raw data
- Let Leah know which metrics we're missing (@joanneesteban before 1pm ET Thursdays)

**2. Groom data:** 
- what does the data mean? 
- is it in a format we can add to Domo? 
- which parts of the data do we need? 
- which parts of the data can we leave out? 
- is the data even essential for users to make decisions?

**3. Connect data:**
- connect the data to Domo (or BigQuery???)
- is it connected through API? Or do we need to manually add it via Webform?
- make sure the data is added consistent with our naming convention (@joanneesteban to add tags to the naming convention documentation)
- is this where we add metrics to the WIP section?

**4. Scrub Data**
- clean the data formatting & ensure the metrics are defined

**5. Visualize Data**
- choose how the data would be best visualized for the problem we're trying to solve
- build charts from existing data
- add charts to appropriate place in the dashboard

**6. Synthesize Data**
- analyze the different metrics to share insights
- summarize the analysis

**7. Report Data**
- export to PDF or PPT
- QA export for cleanliness, up to date data, readability (including: does each slide make sense on its own?)
- share with appropriate stakeholder by due date
- be ready and prepared for any follow up questions

**Comment by joanneesteban** [comment]
**Other Note**

Naming & Structure for Domo dashboards

**Comment by joanneesteban** [comment]
## Updates from 5/7/20 Meeting

1. [Mural Board ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1588869654736/1016c93b9f51bc33c49b1d404c716730b052ed90) with Process
2. [Proposed documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/covid-dashboard-process.md) for adding data
3. Proposed synthesis re-structuring. Waiting to hear back.

**Comment by joanneesteban** [comment]
New process in Mural board. Closing this issue.
