### ISSUE TITLE
HLR & SC | Fix subtask scrolling

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#85554]
## Value Statement
**_As a_** Veteran
**_I want_** the page to scroll to bring the focused content into view
**_So that_** I don't have to find the target

## Background Context

The subtask component does not correctly scroll the header or content into view when switching pages.

![subtask scrolling all the way to the top of the page which puts the focused header at the bottom which potentially could be offscreen](https://github.com/department-of-veterans-affairs/vets-website/assets/136959/3fa68d96-d815-4c78-a497-17aa0bc41e8d)

## Acceptance Criteria
- [ ] Focused content is in the view port after switching pages
- [ ] All tests passing

## Tasks
- [ ] Add scroll element at top of subtask page
- [ ] Focus on new scroll element
- [ ] Update e2e tests as needed

## Definition of Ready 
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
