### ISSUE TITLE
Platform Orientation - Split out orientation from onboarding tasks

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#85562]
## Status
| Date | Status | Launch Date | Notes |
| ----- | ------ | ------------------------- | ------ |
| 12/5/2024 | Complete | On-track | New process launched 12/3/2024 |
| 11/20/2024 | In Progress | On-track | Work almost complete, on track to launch next sprint |
| 11/6/2024 | In Progress | On-track | Wrapping up ticket redesign, beginning flow and PW updates this upcoming sprint |

## Problem Statement 

Governance team would like to split the Platform orientation tasks from the Platform Onboarding tasks. 

Currently, when VFS teams participate in Platform Orientation, they are asked to complete both educational tasks (ie orientation tasks) as well as onboarding tasks (ie required tasks for access to tools, services). The orientation tasks are intended to help them educate them on the processes, practices, rules and overall "way we do things" when building on the VA.gov Platform. The onboarding tasks are so that the new team member can gain access to Platform products, tools and services, including GitHub repos, Atlas, and other tools that are Atlas-dependent.

We'd like to separate the onboarding tasks from the orientation tasks and create 2 separate processes because we have encountered several challenges when tying the 2 together including non-VFS team members being asked to complete the Platform Orientation process (even though they're not VFS) in order to gain access, issues with closing the ticket since the VFS owns it but Platform takes action on it, VFS teams thinking they need validation from Platform on the orientation tasks which is not necessary, and other minor issues. 

Governance would like to simplify the onboarding tasks to make it more clear who needs to complete the ticket and who takes action once submitted.

Governance would like to move the orientation tasks to Platform Website, as they are not tracked by Platform and there is no need for an issue ticket to be created, however we'd still like to give VFS teams the option if that is preferred.

How might we separate the 2 sets of tasks from one another without causing churn for VFS teams?
How might we ensure VFS teams are still completing the orientation/education tasks now that they won't be part of a ticket?
How might we improve the support process for Platform Support so that there's less tickets in limbo?

### Notes from refinement 6/13

- For someone who has to wait as a new hire, having checkboxes in a ticket and watching things feels like progress
- Doesn't necessarily need to be in a GH template, but VFS teams members still might find a task valuable
- Have language for PM or whomever, "here's what we recommend" 
- Need to have guidance on the PW page
- Each team might have their own onboarding
- Being clear from the beginning that this onboarding is for VA.gov _Platform_

## Hypothesis or Bet

- If we split orientation tasks from onboarding tasks, then Platform Support will have a cleaner and smoother process for providing support to VFS teams.
- If we split orientation tasks from onboarding tasks, then anyone will be able to easily access the orientation tasks without opening a ticket.
- If we split orientation tasks from onboarding tasks, then we will make it clear for VFS teams which tasks are required to be completed before Platform can provide support. 

## We will know we're done when... ("Definition of Done")
- [ ] All orientation tasks are easily accessed from the Getting Started section of the Platform Website.
- [ ] The current New VFS Team Member ticket (name may change) is scoped to just the tasks that VFS teams are required to complete and the 2 follow up tasks for Platform.
- [ ] The Platform Support team has modified their operational process for providing support to the New VFS Team Member ticket.
- [ ] We have communicated the difference between onboarding and orientation (or whatever preferred terms we use) and it is reflected appropriately on the Platform Website 
- [ ] The landing page for Platform Orientation and the page with the links to the 2 templates have been modified to reflect our current process.
- [ ] The change in process has been communicated to VFS teams via Slack, Team of Teams and other appropriate venues.

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
January 15, 2025

<details>
  <summary>Launch Checklist</summary>

### Guidance 

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platform initiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1912569976/Platform+Product+terminology?atlOrigin=eyJpIjoiM2VmNzY2MTZkZWE4NGY2NmJmNjk2YWIwMmJhMGZiZmYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

</details>

**Comment by shiragoodman** [comment]
@humancompanion-usds Planning. Current timeline has this work beginning 9/12, and expected to complete 11/7. This will require collaboration with the Platform Support team, as well as other Platforms teams involved in the current Platform Orientation. Current guidance on Platform Website re: Platform Orientation has been in place since July 2022.

**Comment by shiragoodman** [comment]
@alyssagallion @jknipes here is the initiative I have written up so far. Please take a look and let me know if you have any questions. I'd be interested in chatting soon to ensure that we're in alignment on the proposed changes. ty!
