### ISSUE TITLE
Phone number audit on debt portal and eFSR

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#85566]
## Issue Description
In Medallia feedback we have heard that some of the phone numbers listed on the debt portal and/or FSR pages may not be accurate. We want to do an audit to verify that all phone numbers listed are accurate. 

## Tasks
- [x] Front End team to provide a fixed list of current phone numbers that currently exist. Then, cross-check all phone numbers listed across the debt portal and FSR
- [x] Call the phone numbers listed to verify their accuracy
- [x] Confirm and/or adjust per findings

## Acceptance Criteria
- [x] A document confirming the accuracy of the phone numbers listed or recommending the appropriate phone numbers

---

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Dr-Pongo** [comment]
Going to hijack this ticket to look into two questionable numbers listed in the combined debt portal:
- `8888274817` in `src/applications/combined-debt-portal/medical-copays/components/Modals.jsx`
  - Pay VA? Seems sus "By Phone: Contact VA at"
- `8662602614` in `src/applications/combined-debt-portal/medical-copays/components/StatementAddresses.jsx`
  - Address change stuffs? "If your address has changed, call"

**Comment by josephrlee** [comment]
I did an audit and found the numbers we currently have between the two apps:

| Label               | Number                              | Location |
| ------------------- | ----------------------------------- | -------------- |
| DMC (Overpayments)  | [800-827-0648](tel:+18008270648)  | Both FSR and CDP multiple pages |
| DMC (International) | [+1-612-713-6415](tel:+16127136415) | Both FSR and CDP multiple pages |
| HRC (Copay bills)   | [866-400-1238](tel:+18664001238)    | Both FSR and CDP multiple pages  |
| MyVA 411            | [800-698-2411](tel:+18006982411)    | Both FSR and CDP  multiple pages |
| Pay Copay Bill | [888-827-4817](tel:+18888274817) |  CDP Copay Detail page |
| Copay Address change | [+1-866-260-2614](tel:+18662602614) | CDP Copay HTML statement page |

cc: @charlottecesana @mgleo

**Comment by josephrlee** [comment]
@denisecoveyduc, the only number that I'm not sure about is the Copay Address change number: 8662602614

`8662602614` in `src/applications/combined-debt-portal/medical-copays/components/StatementAddresses.jsx`
 "If your address has changed, call us"

It's currently listed on these two other VA pages: https://www.va.gov/hines-health-care/contact-us/, https://www.va.gov/chicago-health-care/billing-and-insurance/ 

They are both Chicago-based VAMS; why would an address change for your copay go only to these two Chicago-based VAMS instead of something at the national level or the HRC number?

Can you help us verify this number? Thanks!

cc: @Dr-Pongo @mgleo @charlottecesana

**Comment by denisecoveyduc** [comment]
As per discussion over slack we have determined that the mockdata for the staging user is not showing an HRC Phone number in the Chicago, IL area and therefore the phone number needs to be updated to more accurately reflect the production experience.

In production, if a Veteran wanted to change the address shown on their statement they would call their Health Resource Center (HRC ) depending on where they live. 

I hope that helps @josephrlee @mgleo

**Comment by josephrlee** [comment]
After more discovery, the Change Address number is hard-coded and needs to be updated to pull from the station number. 

A FE ticket will be needed to implement this. 

cc: @Dr-Pongo @denisecoveyduc

**Comment by josephrlee** [comment]
After further conversation with @denisecoveyduc, we'll close this ticket and create two new tickets. 

1. One to go into this next sprint to hide the change address line with the incorrect number
2. A future backlog ticket to figure out the correct number to display and then implement the correct dynamic phone number

I'll update this ticket once I've created the new tickets. 

cc: @Tom-Davis @dhill802 @charlottecesana @mgleo @Dr-Pongo
