### ISSUE TITLE
Add GA4-related text to Domo Dashboards & Cards

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#85570]
### Description
Because we are making changes to the underlying datasets feeding our Domo reports, we'll want to communicate this to our users that the reports/cards may contain a combination of both UA _and_ GA4 data, and when exact the switch happens.

This will likely be done in the form of updated text at the top of the reports, as well as card-specific notes/cards indicating why something might be higher/lower around the time of the switch.

---

### Tasks

- [x] For all Domo reports that we'll be updating -- add text to the top of the report, something akin to the following

> **Note:** This report had historically used Universal Analytics (UA) as a data source, which was officially sunset by Google on July 1, 2024. The last day this report contains data from UA is on June 30, 2024. Any data present after June 30th uses data collected from Google Analytics 4 (GA4).
> 

- [ ] For specific cards/metrics that are going to be off due to Google's measurement protocol changes, indicate on the card, or with a text field of the change. -- might look to push to data dictionaries.

So far, this includes:
- Content KPIs - Avg Clicks -- was poorly defined, flag as something to revisit.
- Search KPIs -- Refinement Rate -- no longer available in GA4

### Acceptance Criteria

- [x] Reports updated with generic UA + GA4 data source text, as outlined above.
- [ ] Specific cards with large jumps/changes include an asterisk with a note.

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA -- I confirmed the text is on all our priority dashboards -- for future reference, **_please be sure to spot check and QC your own work_** -- some dashboards were initially missed, and the ones that had it had grammatical issues on the text. 

Moving to _Done_.
