### ISSUE TITLE
[CST] Update file uploader UI on Document Request page to match what's on the Files tab

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#85574]
## Value Statement
**_As a_** Veteran
**_I want to_** see the same type of file upload pattern on all tabs
**_So that_** the user experience is consistent and intuitive

---
## Background Context

Right now we have a slightly different implementation of the "File upload" pattern for Document Request pages than we do on the Files tab itself. We want to update the Document Request page version to use what we currently have on the Files tab.

Current Files Tab UI
<img width="866" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ae15e7701047ffcc1775fe124b0ee71245839ff/Screenshot%202024-06-10%20at%2011.01.52%E2%80%AFAM.png" alt="Screenshot 2024-06-10 at 11.01.52 AM.png" />

Current Document Request UI
<img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDVOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff17a05bcbf8b086fc50de05e279acdeef1b0537/Screenshot%202024-06-07%20at%201.35.57%E2%80%AFPM.png" alt="Screenshot 2024-06-07 at 1.35.57 PM.png" />

## Design
- [FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=1924-1810&t=Ag1UPKg0cOSGsa2S-4)

### Enablement team (if needed)
@member of team

## Engineering 
- The component `DocumentRequestPage.jsx` uses the component `DefaultPage.jsx` which uses the component `AddFilesFormOld.jsx` for uploading files. We should just need to replace the component `AddFilesFormOld` with `AddFilesForm`. 

## Out of scope
- No other changes other than what's specified in the mock should be made to the Document Request (DR) page

## Open questions
- Do we want to put this behind the feature flag cst_use_claim_details_v2 like we do for the files tab?

## Tasks
- [ ] Replace the component `AddFilesFormOld` with `AddFilesForm` on the `DefaultPage.jsx`
- [ ] put this behind the feature flag `cst_use_claim_details_v2`
- [ ] add cypress tests

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _All the design changes highlighted in the Tasks section are implemented to match the spec_
- [ ] _There is no discernible difference between the file upload experience in the Files tab and the file upload experience on the Document Request page_
- [ ] This is behind the feature flag `cst_use_claim_details_v2`

**Comment by pmclaren19** [comment]
@skylerschain - The component `DocumentRequestPage.jsx` uses the component `DefaultPage.jsx` which uses the component `AddFilesFormOld.jsx` which gives users the ability to upload files. We should just need to replace the component `AddFilesFormOld` with the updated upload component `AddFilesForm`. Do we want to put this behind a feature flag like we did for the files tab? If so maybe we just use the same feature flag cst_use_claim_details_v2. @jacobworrell thoughts?

**Comment by pmclaren19** [comment]
Validated locally changing the feature flags `cst_use_claim_details_v2` and `cst_5103_update_enabled` from disabled/enabled and then testing on user 23 on the 5103 notice and on user 46 with a regular primary alert (21-8049 For Net Worth) and looked good! @skylerschain lmk if you have any questions or concerns!
