### ISSUE TITLE
Build and publish 'VA Dental Insurance Program (VADIP)'  page in Spanish.

### ISSUE THREAD

**Issue by moviedosoco** [department-of-veterans-affairs/va.gov-team#85585]
## Issue description
We need to build this page in Drupal, review it, and publish. 

---
## Tasks
_What work is necessary for this ticket to be completed? Examples:_
- [ ] Assess stakeholder request
- [ ] Draft content
- [ ] Review 
- [ ] Share with stakeholder
- [ ] Update page
- [ ] Copyedit
- [ ] Publish
- [ ] Alert stakeholder

## Acceptance Criteria
_What will be created or happen as a result of this story? Examples:_
- [ ] Updated content is live on the site
- [ ] Product has launched
- [ ] Feedback has been shared with stakeholders

## Configure this issue
- [ ] _Attach to an Epic (what body of work is this a part of?)_
- [ ] _Label with Originator/Team (product team or stakeholder requesting support)_
- [ ] _Label with Open Date_
- [ ] _Label with Estimate (level of effort expected for this ticket)_
- [ ] _Add assignee name to each task they will complete (if known)_
