### ISSUE TITLE
Clean up PII entered in 'other' field in the Flag Reps FAR feature

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#85587]
## Background
_What background/context has led to this work?  What problem are we trying to solve?_

## Tasks
- [x] Update other values in vets-api prod DB with 'Reacted'
- [x] Remove rep data from DOMO
- [x] Delete XLS files containing rep data from my VA OneDrive account 

## Acceptance Criteria
- [x] The above tasks have been completed

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
This was completed 6/7/24, afternoon.
