### ISSUE TITLE
Forms Discovery Research Epic

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#85594]
## High Level User Story
As a _____, I need _____ so I can _____.

## Goals
_What outcome(s) do we want to see?_ 

## Issues to create within this Epic

```
- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

## How to configure this issue
- [ ] **Labeled with `discovery` and `research` and `team-name`**

## Acceptance Criteria
> 

 - [ ] **Scenario: Research plan creation**
  - Given the Discovery Research Epic is created
  - When the team creates a research plan
  - Then the research plan should outline the goals, issues, and timeline for the project
- [ ] **Scenario: Recruitment and scheduling of research sessions**
  - Given the Discovery Research Epic is created
  - When the team recruits participants and schedules research sessions
  - Then the sessions are conducted with the appropriate participants at the right time
- [ ] **Scenario: Creation of a conversation guide**
  - Given the
