### ISSUE TITLE
Draft a Information Architecture KPI Dashboard

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8559]
## User Story or Problem Statement
As VSP, I need to track my IA KPIs so I can understand if my efforts restructuring VA.gov's IA is a success.

## Goal
Design a Product Success Tool on Domo for IA.

---
## Tasks
- [ ] Amy - Create skeleton dashboard so we can start adding data
- [ ] Joanne - look into ForeSee data that can be helpful
- [ ] Kimberley - look into contact center data that can be helpful
- [ ] Brian - GTM implementation related to IA KPIs
- [ ] Brian - Connect GA to Domo

## Acceptance Criteria
- [ ] Users can see their KPIs on the Product Success Tool
---
## Resources

Requirements Issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8023

IA KPIs: [link](https://docs.google.com/document/d/1862x-PQJ0X3UAGH_DpNvlcHOjsU3Too4vzx4OmLvx5I/edit)

**Comment by joanneesteban** [comment]
In the effort to hold ourselves (VSP) to our own standards, I met with Megan & Mikki on 5/13/20 & went over [mapping the KPIs back to OKRs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/product-success-tool-request.md) for a dashboard on Domo.

Mikki is going to start to do this work, and then we will regroup on Wednesday, May 20th. 

@bsmartin-ep @amycesal hold off on doing additional work on this until then. We may end up just switching this over to making a custom dashboard on Google Analytics.

**Comment by joanneesteban** [comment]
Re-writing our Sprint 26 objective for this as:

**Product Success Tool - Expand for All VA.gov Products:**
Collaborate with VSP Content & IA team to refine IA objectives and build out metrics reports or dashboard as appropriate.

**Comment by joanneesteban** [comment]
## Next Steps

*Met with IA on next steps for these metrics*

- Mikki & Megan will get back to us on if they have prioritized KPIs for IA. We can build a KPI dashboard on Domo if/when this happens
- @bsmartin-ep to share Google Analytics links of the requested metrics to IA (can hyperlink the IA metrics Google Doc)
- @bsmartin-ep to open dependency for segmentation of some of the metrics
- @bsmartin-ep , @amycesal , @joanneesteban to meet about Domo process ( @joanneesteban will send meeting invite)

**Comment by joanneesteban** [comment]
@bsmartin-ep how's the GA links or GA dashboard going for this?

**Comment by bsmartin-ep** [comment]
@joanneesteban  - Here's the WIP dashboard....

https://analytics.google.com/analytics/web/?authuser=0#/dashboard/TI6mlpsEQ1msDIwLYFEkdg/a50123418w177519031p184624291/

I think this covers the metrics, but I still need to build the segments for these...


- Overall site traffic - new and repeat visitors, auth and unauth visitors
- Breadcrumb engagement - percent of user sessions where user interacts with element
- Left nav engagement - percent of user sessions where user interacts with element

**Comment by bsmartin-ep** [comment]
@joanneesteban -

I think this is ready for review.  It should load data for All, WBC, and the product views, but the report links are pointing to the WBC view.

https://analytics.google.com/analytics/web/?authuser=0#/dashboard/TI6mlpsEQ1msDIwLYFEkdg/a50123418w177519031p184624291/

### Segments

Description | Segment and Location
:---- | :----
All| All > _All Users_
Mobile and Tablet Traffic | All > _Mobile and Tablet Traffic_
New Users | All > _New Users_
Returning Users| All > _Returning Users_
Logged in / Authenticated | Shared > _VA<span/>.gov - Session - Authenticated - LOA Present_
Bot Logged in / Not Authenticated | Shared > _VA<span/>.gov - Session - No LOA Present [Veteran Not Logged in]_
Breadcrumb engagement | Shared > _Sessions with nav-breadcrumb event_
Left nav engagement | Shared > _Sessions with nav-sidenav event_
Users that enter on home page | Shared > _Sessions with the home page as landing page_

cc @jonwehausen

**Comment by joanneesteban** [comment]
Liani, Content & IA PM, is determining new KPIs. Will open a new issue when that comes in.
