### ISSUE TITLE
[Testing Ticket] Font Normalization from Design System changes 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#85609]
## Description
The Design System team will be making font normalization changes. We will need to review their changes in review instance and make sure there are no major issues in the Appointments application. 

[Key dates:](https://dsva.slack.com/archives/C03R5SBELQM/p1717618603508049)
When: June 6th - 25th
June 6th - June 12th: initial QA window (review instance will remain unchanged)
June 13th - 17th: DST to address any feedback, update review instance
June 18th - 25th: Final review window
June 26th: [PR to be merged](https://github.com/department-of-veterans-affairs/vets-website/pull/30089).
What: Normalization for all typography elements (paragraphs, labels, lists, links) using source sans pro to 16.96px
Impact: 0.96px increase to elements listed above on [VA.gov](http://va.gov/)
The ask: Similar to the first typography PR, we would like teams to access their applications using [our review instance](http://d8405876e5ef9883fc31154f07802640.review.vetsgov-internal/) and make sure content flow looks normal.
If everything looks good, approve the PR
If something needs to be addressed, please leave a review comment on the [package.json file](https://github.com/department-of-veterans-affairs/vets-website/pull/30089/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R261), stating what team you are from, a screenshot of the content that needs to be addressed, and a link to the manifest.json file of your application in vets-website. Please thread any additional comments to your original top level comment on the package.json file.
 (edited)

---

## Task

- [x] ~Validate the changes in Review Instance~ Unable to use RI. Download the PR to local environment to capture screenshots
- [x] ~Send screen shots of the latest changes from Review Instance to the Appointments UX team~ 
- [x] Document any issues found while testing 

## Acceptance Criteria

Use the same AC as previous test base font ticket #82658. 
For each of the pages below please provide 2 full page screenshots, one each at 320 px wide and > 800 px wide:

- [x] Appointments Landing page with upcoming appts
- [x] Past appts list 
- [x] Pending appts lis
- [x] Request calendar
- [x] Request calendar with weekends

Please also test each of those pages at 200, 300, and 400x text zoom. Only provide screenshots of the zoom levels if something looks broken.

### Design Assets
N/A 

## Definition of Done
- [x] Tasks are completed 
---

**Comment by outerpress** [comment]
@jenniemc here's a folder you can use to drop screenshots: https://dvagov.sharepoint.com/:f:/s/HealthApartment/EjRNEsqZdSRGmgPiIa27mZoBZxh_Ki4k-rGTXnbrxfZJ_Q?e=MfvIJe

**Comment by jenniemc** [comment]
@outerpress, @ldelacosta 
- All images are captured in the local environment and not in the review instance. 
- All the screenshots (pre-redesign) are stored in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design/screenshots
- There are no observable errors when viewed at 100x, 200x, 300x and 400x.
### One notable difference 
At 320px mobile view, this is the screen capture in the local environment to test the font normalization. The number which follows the pending link is forced to the next line. 

![Screenshot 2024-06-17 at 11 18 30 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/16f7895e-d452-4226-a85f-020fdcc7be08)
---
Using Judy Morrison on staging (non font normalization test). The number is in the same line as pending link

![Screenshot 2024-06-17 at 11 14 39 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/ec55054e-31dd-4f9f-9ea4-2144a7894d70)

**Comment by outerpress** [comment]
@jenniemc at the bottom of the alert in the screenshot below the link to contact your local VA medical center is off the page. Is that due to this change?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2536801/6dae4fb7-09d4-47bf-9e2c-ebfbf77870d5)

**Comment by outerpress** [comment]
@jenniemc @ldelacosta other than my question above, the screenshots look good! Let me know when you want me to review any more.

**Comment by jenniemc** [comment]
@outerpress, Good catch! The text is off the page happened prior to the Font Normalization test.

**Comment by jenniemc** [comment]
@outerpress @ldelacosta , Redesign screenshots are added to the folder for review. Nothing out of the ordinary was observed. Please note the Visit Summary displays in the past appointment redesign even when the flag was turned off.

**Comment by outerpress** [comment]
@jenniemc thanks, this looks good to me!  @ldelacosta I'll work with you to get tickets together for the two items noted in the comments, but you can close this one.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.

**Comment by outerpress** [comment]
@ldelacosta I filed #86993 for the issue where the text is breaking out of the viewport

**Comment by outerpress** [comment]
@ldelacosta and #86999 for the issue where pending is breaking from the number of reqs.
