### ISSUE TITLE
OH Direct schedule using Patient-Provider relationships

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#85605]
## Task Description

Based on conversations with Appothesource, Oracle health, and OCTO leads create a direct scheduling user flow. Use this diagram as a tool to communicate the logic of the flow in order to determine what UI is needed to DS an OH appointment. 

## Notes and references
- If there are parts of the logic that need more definition from the business, OH, or Appothesource, continue to ask for that information and add to the diagram as you get answers. 

## Acceptance Criteria

- [x] A user flow diagram is made
- [x] Using the example of TOC "Nutrition and food" go through the checks with Tia at OH and Brad at Appothesource to understand how this TOC handles scheduling with established versus any providers. 
- [x] Create UI for the new pages needed for this flow
- [x] Add new pages to the Prototype to test with Veterans

## Deliverables
-[User flow](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2980-18211&t=hUETyBLPH5kQCHXw-1)

**Comment by melissa-lefevre** [comment]
## Task Description

Based on conversations with Appothesource, Oracle health, and OCTO leads create a direct scheduling user flow. Use this diagram as a tool to communicate the logic of the flow in order to determine what UI is needed to DS an OH appointment. 

## Notes and references
- If there are parts of the logic that need more definition from the business, OH, or Appothesource, continue to ask for that information and add to the diagram as you get answers. 

## Acceptance Criteria

- [ ] A user flow diagram is made
- [ ] Using the example of TOC "Nutrition and food" go through the checks with Tia at OH and Brad at Appothesource to understand how this TOC handles scheduling with established versus any providers. 

## Deliverables
-[User flow](https://www.figma.com/design/2GyMzzLIpqN5mkYzXlwQ87/Scheduling-improvements-workspace-%7C-Appointments-FE?node-id=2980-18211&t=hUETyBLPH5kQCHXw-1)
