### ISSUE TITLE
Copy of Discovery: dsva-vagov-rails-cache

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#85606]
## Problem

In order to reduce or even remove the need for downtime during future Redis upgrades of this cluster, we need to do discovery on whether or not the clusters will rebuild themselves if there is data loss. If this cache simply consists of things that the Rails framework caches, then we should be able to forego backups and take advantage of zero/near-zero downtime upgrades of these clusters.

## Questions to be answered

- [ ] Are the contents of this cluster really just Rails framework-caches?
- [ ] Given that we have one cluster, but many pods, how do the pods know which of the contents are their caches?
- [ ] Given that we have one cluster, but many pods, how do the behave if the data is suddenly gone?
- [ ] Do we write anything to the cluster independent of the Rails framework?
- [ ] What changes would have to be made to make this cluster truly ephemeral (if any)?

## Tasks
- [ ] 

## Success Metrics
- [ ] ADD SUCCESS METRICS HERE

## Acceptability Criteria
- [ ] ADD A/C HERE
