### ISSUE TITLE
Kick-off: 5901 VA.gov Needs

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#85613]
## Issue Description
Prepare for OGC kick-off by reviewing current materials and developing a list of questions for OGC.

We have a meeting with OGC on July 1 to explore what their expectations are and what they believe to be required to meet these expectations.

## Tasks
- [x] Evaluate existing materials listed in comments
- [x] Create shared list of questions in Slack Canvas
- [ ] Send list to team to review prior to OGC
- [ ] Stretch goal: If OGC can provide the entry point for how users are to report to FTC that'd be super helpful

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
1. Make some sense of this https://www.va.gov/OGC/docs/Accred/HowtoFileaComplaint.pdf esp looking at what happens at the FTC links and think about how we could do it better, esp for B and
2. Develop any specific questions you have about D (like what sort of final decision documentation they have now and where it is saved)?

Law being referred to: https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title38-section5901&num=0&edition=prelim

Identified questions
1. Why are pensions complaints a different flow from non pensions complaints?
2. Do they want to keep the "yes/no involve law enforcement?" option?

**Comment by oddball-lindsay** [comment]
Regarding B and the FTC links:
Outlined screenshots of the FTC experience in [this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718054883670/f07453a2eaabef4a086d8b39a9fb54b62472ea62?sender=ubac5f0487f25bc4431288699) - first pass is p basic, just to see the different nuances.  Can clean up pathways if we want a distinct user flow.  Also curious though if there's a particular path that should be used for reporting accredited reps.

My initial qs on D are:
Does anything exist today, that provides final discipline decisions for violations?
Who manages that content (ie if we move to VA.gov who is the SME to approve that version)

**Comment by oddball-lindsay** [comment]
@mtri please review Canvas and add any questions you might have for discovery around this tool and process: https://dsva.slack.com/docs/T03FECE8V/F077KUNB41Y

Not urgent, just need before July 1

**Comment by mtri** [comment]
Added my questions to the canvas.
