### ISSUE TITLE
Claimant Type (Veteran vs. non-Veteran)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#85623]
## Issue Description

The Claimant Type page will be available to:
1. Veteran and Non-Veteran users
2. Authenticated users and unauthenticated users
3. 21-22 and 21-22a forms

Content is not dynamic.

The claimant type will be used to guide the user flow, but does not route to any fields in the 21-22/21-22a forms.

URL: `/claimant-type`

Previous path: `/introduction`
Next path: `/representative-select`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs 
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-217020&t=2z97c2u48omR2vdi-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-217020&t=2z97c2u48omR2vdi-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2070-153281&t=2z97c2u48omR2vdi-4)

<details><summary>Screenshots</summary>

<img width="178" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjFQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfead5f6d50211700eaa56cf371b4ffa8b1e9b8a/image.png" alt="image.png" />

<img width="745" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjlQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cb63bac0c7ecb88d25c7b97de60a7fe64f9d831/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Claimant Type page based on the designs above
- [ ] Set up the proper logic for displaying the page in the Appoint flow
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Claimant Type page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
Assigning to @mtri for review

**Comment by mtri** [comment]
- The "Tell us who you are" heading is missing
- Noting this page will not display the process bar since the number of steps changes depending on if you are the Veteran vs. if you are not the Veteran

Other than that, looks good!

**Comment by cosu419** [comment]
Thanks @mtri - wondering if you were drawing from any existing form apps as far as this screen goes? I ask because the default pattern seems to be that once the user passes the "Introduction" page, they have entered the tabbed form flow. So those pre-amble type screens (eg determining eligibility to fill out the form) typically happen before the Intro page. 

It is possible (and straightforward) to make this page part of the form flow while still excluding it from the actual form submission. If we do want to implement this as is, I suspect there are some workaround options available - just wanted to check whether it's been implemented somewhere before I explore further.

**Comment by cosu419** [comment]
This is ready for review @mtri - note that the size discrepancy between the buttons is a bug in the shared component. Will ask someone from the design system team about that.

<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccb706c02ac4b70094530a7e342c6f979bf2dd24/image.png" alt="image.png" />

**Comment by mtri** [comment]
Looks good!
