### ISSUE TITLE
Toxic Exposure - Form 21-526EZ PDF as a supporting document - automating polling for status job 

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#85624]
## Story
As a steward of the Form 21-526EZ workflow, I would like to know the status of the Form 526 PDF submission to the eFolder when going through the primary path.

## Goal:
We need a method to inform the vets-api system of the status of the Form 526 PDF as a supporting document of the established claim.

Link to notes and proposed options for implementation: https://dsva.slack.com/archives/C04KW0B46N5/p1717516393733889?thread_ts=1717516384.179439&cid=C04KW0B46N5

7/12:
"Instead, maybe it makes sense to tweak the polling job to
check the submission.created_at date
if it's more than 2 days old and the PDF is missing, update the job status to pdf_not_found immediately and exit the job"

## Context:
With the migration to the Lighthouse synchronous submit endpoint, Lighthouse returns after a claim is established and returns a claim id from VBMS representing the established claim.
However, this does not ensure that the Form 526 PDF that was generated in the process got submitted along with the claim being established.
If we were to utilize the Lighthouse synchronous submit endpoint, we would not know if the generated Form 526 PDF made it into the eFolder for the Veteran in VBMS.

## Tasks
- Create alerting for defined error cases
- Have job call Exponential backoff 
- Call in handle_ancillary_jobs

## Acceptance Criteria
- [x] Automating polling implementation
- [x] Figure out ways to monitor/test this locally
- [ ] Document test results
- [x] Check the submission.created_at date, if it's more than 2 days old and the PDF is missing, update the job status to `pdf_not_found` immediately and exit the job
- [x] Feature Flag

## Out of scope
- [ ] optimizing polling times (nice to have - can be post-MVP)

**Comment by mchae-nava** [comment]
If time allows, consider another follow-up for automated remediation and improving polling intervals

**Comment by mchae-nava** [comment]
Some local issues after pulling latest. Will fix, test one more time, and then write up
