### ISSUE TITLE
[Automation] Update .csv file structure for Facilities, System and Facility Health services, and Staff profiles [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8562]
## User Story or Problem Statement
As a Engineer,  I must have a clearly defined .csv structure and cross reference, so I can clearly create the Migration script for Automation of data load. 

## Goal
_Perform initial page testing, review, initial Accessibility scan with AXE-Coconut _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Chrome AXE-Coconut](https://chrome.google.com/webstore/detail/axe-coconut-web-accessibi/iobddmbdndbbbfjopjdgadphaoihpojp/related?hl=en)
[Chrome AXE](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd/related?hl=en-US)

## Tasks
_Complete creation of .csv files and a cross reference for each file to the Drupal node and fields:_
- [x] System Health Services
- [x] Facility Health Services
- [ ] Facilities
- [ ] Staff profiles
- [ ] Cross reference for each of the above items to the corresponding Drupal node and fields.

## Acceptance Criteria
* System Health Services
* Facility Health Services
* Facilities
* Staff profiles
* Cross reference for each of the above items to the corresponding Drupal node and fields.

**Comment by SgardnerPMP** [comment]
System health Services and Facility Level Health Services DRAFT provided to CMS for review and input.

**Comment by swirtSJW** [comment]
@SgardnerPMP  I noticed one issue of data jumping rows in due to commas within the content.
![image.png](https://images.zenhubusercontent.com/5dcda45425f6cc0001763cb5/00332719-b468-4296-9e05-35ea2cee06ae)

When you export, choose the option to wrap cell contents in quotes.

**Comment by swirtSJW** [comment]
On the facility health services spreadsheet, I think the references to /node/3066 are going to break when they hit the front end.
Don't we want to reference the full path of `/wilkes-barre-health-care/campus-map`?
