### ISSUE TITLE
[Business Optimization] Develop and present draft Tracking graph for current an global project goals [PM]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8563]
## User Story or Problem Statement
As a Stakeholder,  I must have a clear graphic of the full level of work and what has been complete so far and what is remaining, so I can understand the Level of Effort and timeline.

## Goal
_Perform initial page testing, review, initial Accessibility scan with AXE-Coconut _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Tasks
_Complete creation of graphic using Google Charts or graphics to_
- [ ] Track current tasks in flow
- [ ] Upcoming tasks in flight
- [ ] Global goals still outstanding
- [ ] Break Graphs into VISNs, SYSTEMS, Tasks Per System, and as many rubrix as possible.

## Acceptance Criteria
* Track current tasks in flow
* Upcoming tasks in flight
* Global goals still outstanding
* Break Graphs into VISNs, SYSTEMS, Tasks Per System, and as many rubrix as possible.
