### ISSUE TITLE
Build and publish 'VA dental care' page in Spanish

### ISSUE THREAD

**Issue by moviedosoco** [department-of-veterans-affairs/va.gov-team#85641]
## Issue description
We need to build this page in Drupal, review it, and publish:  [VA dental care](https://www.va.gov/health-care/about-va-health-benefits/dental-care/)

- [Pre-publishing checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/checklists/prepublishing-checklist.md#additional-checks-for-translated-articles)
## Tasks

- [x] Build page in Drupal (Victoria)
- [x] Review (Sara)
- [x] Publish (Sara) 
- [x] Send live page to State Dept. for QA (Randi)
- [x] Input any changes (Victoria)
- [x] Review (Sara)
- [x] Publish with Spanish toggle (Sara)

## Acceptance Criteria

- [x] Page is live 

## Configure this issue
  - [ ]  #51141

**Comment by moviedosoco** [comment]
@RLHecht I add here the translation back from State. 
[SPA-VA dental care.docx](https://github.com/user-attachments/files/16397204/SPA-VA.dental.care.docx)

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2 This page is ready to be reviewed and published. 
'Cuidado dental de VA': http://preview-prod.vfs.va.gov/preview?nodeId=71008

**Comment by saratorres2** [comment]
@moviedosoco This page has been published and is live. https://www.va.gov/health-care/about-va-health-benefits/dental-care-esp/

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2 This Spanish new page was sent for QA on 9/9/24.

**Comment by RLHecht** [comment]
@moviedosoco here's the QA back from State:

[LS-2024-0122945-LQA Notes-es_v1__VA dental care.docx](https://github.com/user-attachments/files/17131171/LS-2024-0122945-LQA.Notes-es_v1__VA.dental.care.docx)

**Comment by moviedosoco** [comment]
@RLHecht The QA was implemented in the page.

@saratorres2 The _Cuidado dental de VA_ page is ready to be reviewed an republished. 

Thank you!

**Comment by saratorres2** [comment]
I've copy edited and published updates to this page. @RLHecht I'll check the live page later this afternoon to make sure that changes went live and everything looks good, but in the meanwhile we can open a Public Websites ticket to set up the toggle. (If you want, I can shadow you on this!)

**Comment by RLHecht** [comment]
Closing this ticket. Will open up a ticket for PW to create the Spanish toggle.
