### ISSUE TITLE
[UX] EZ/CG - Draft UX Documentation Standards

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#85694]
## Issue Description
Draft a document that accounts for the UX processes and documentation needs that have been evolving but are not written down in a central source like github. This ticket is to document what we as a UX team have been doing and what we would like to move towards in terms of the ux process. 

- [UX Retro Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709744287345/b4e1721b91ff249571787e3e267a42ba9c4de18d?sender=ud5c82d652d231345efaf6060)

---
## Tasks
- [ ] In the UX-admin folder update the readme file to contain high-level info - where we work, how we work, what we do, who we are, etc.
- [ ] Create a new file and draft what a decisions workflow and/or ux workflow looks like (content, dev, Platform integration)
- [ ] Draft a documentations standards example / resource 
- [ ] Update/evolve team mural: [_Reference - Research Landscape_](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697039977149/b8a5ea90748703093cdcb405b84463e515cfea2a?sender=uadf1ed7fe7c76f0914967329)
- [ ] Working session with UX team (and Lois?) to review make adjustments

## Acceptance Criteria
- A living document setup is started that outlines the UX process and resources today
---
