### ISSUE TITLE
[Design] - LOA1  Profile design

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8570]
## Background
We realized we need to create a profile design for users who are LOA1 and hide certain features of the profile

From Slack:
Right now, LOA1 users can view the account settings page to verify their identities, add 2FA, and see info on how to update their sign-in email address. But for the profile, they can't view it at all because we don't know they are who they say they are. That's great and works for an approach where profile and account are two separate pages.
However, we can't take the same approach with Profile 2.0 and just hide the whole profile from LOA1 users because they still need to see the options to verify their identity, add 2FA, and update their sign in email addresses. This means we need an LOA1 version of the profile which is basically the account settings stuff only.

## Tasks
- [x] Create design for LOA1 profile users
- [x] Design alert (if needed)
- [x] Design copy for alert (if needed)

**Comment by peggygannon** [comment]
Hi, @tressaellen Is this issue ready for me? let me know if you've got a design yet for LOA1 users, or if there is copy I can write now to help inform the design?

**Comment by tressaellen** [comment]
@peggygannon, I don't have the design ready for this one - I'll let you know when I do.

**Comment by tressaellen** [comment]
Since we are now going to be using the navigation header as H1 in the profile we can't remove the navigation block completely from this page. I personally prefer the 'grayed-out' version, because then the user could see the pages they could potentially could view- BUT this might not be A11y friendly/possible to do from a dev standpoint. Thoughts? @erikphansen @sanlouise @Samara-Strauss 
![Screen Shot 2020-05-08 at 9.12.17 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/0235a301-a8d0-4376-8c63-801c23137d24)

![Screen Shot 2020-05-08 at 9.12.10 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f1d6fb0b-bebf-4856-96e2-7f3ce94cbfd5)

**Comment by erikphansen** [comment]
I also prefer the grayed-out version. I do wonder if we should even show the Direct Deposit menu item though. We try to only show that item if we know they user has DD or is eligible to set it up. But if the user doesn't have 2FA set up, we won't even _check_ to see what their DD status is.

**Comment by erikphansen** [comment]
The profile header will still show the full name and last branch of service, correct?

**Comment by tressaellen** [comment]
Update - chatted with Jen about this - the disabled text in the side-nav is not a11y friendly, so it looks like we will be going with this option.  And yes  - the profile header will still show the full name and last branch of service, but can now be sized down quite a bit (yay!).

![Screen Shot 2020-05-08 at 10.42.06 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/5db5cfce-6ccf-478c-ac16-bd770de394cb)

**Comment by Samara-Strauss** [comment]
I am fine with this design, but I don't think the block at the top of the page should say "We can't access your profile." They did access it by virtue of being on this page. 

Also, it's not accurate to mention 2FA as part of the profile upgrade. If they only add 2FA and do not verify their identity, they can *not* view the rest of the profile. The only way to view the rest of the profile is if they verify their identity.

That content block should encourage them to verify their identity to get access to the other profile features.

Here's a screenshot of what we have now for the profile if you are LOA1. We absolutely do not need to duplicate this design, but I do think it does a good job of letting people know what's up:

<img width="697" alt="Screen Shot 2020-05-08 at 4 36 08 PM" src="https://user-images.githubusercontent.com/34068740/81447199-33bf3d80-914a-11ea-8ef5-7bd4588ea850.png">

**Comment by tressaellen** [comment]
@Samara-Strauss @mshea0606 Here's an updated LOA1 screen. 

<img width="271" alt="Screen Shot 2020-05-11 at 12 26 03 PM" src="https://user-images.githubusercontent.com/58752772/81608348-9b5fcd80-9382-11ea-9e26-64f27370308c.png">

**Comment by Samara-Strauss** [comment]
This looks good to me! Per our convo in Slack, we are talking about whether we should bring some of the "How will VA.gov verify my identity?" info to this page. That decision is up to you, but it could be helpful so people don't have to go to the FAQ if they have questions.

**Comment by tressaellen** [comment]
The "How will VA.gov verify my identity?" drop down definitely does **not** work in the alert box (I can include screenshots if need be). I propose removing the Identity verification line from the overall grid and putting an actual button in the alert box.  The "How will VA.gov verify my identity?" dropdown can live under the alert box.  

Overall, I still think the cleanest option would be to remove the dropdown completely and have it live in the secondary 'Verify your identity' page, but this option should still work well.
<img width="1148" alt="Screen Shot 2020-05-11 at 3 45 31 PM" src="https://user-images.githubusercontent.com/58752772/81622846-8f820480-939e-11ea-9b04-9a029a75fd3c.png">
<img width="1097" alt="Screen Shot 2020-05-11 at 3 45 18 PM" src="https://user-images.githubusercontent.com/58752772/81622840-8bee7d80-939e-11ea-98fc-41fc6f093643.png">

**Comment by Samara-Strauss** [comment]
This works for me!

**Comment by sshein** [comment]
should it be "verify your identity to view your complete profile"? Since as samara said they are viewing their profile? @tressaellen

**Comment by tressaellen** [comment]
@ss

**Comment by peggygannon** [comment]
@tressaellen Yes, that header would work!
