### ISSUE TITLE
[FE + BE] My VA: Maintenance Period Alerts - Check coverage

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#85711]
## Background
To minimize user impact, we want to add and schedule maintenance windows whenever we are aware of upstream outages that will affect My VA.

## Tasks
Review the My VA dashboard and identify existing and missing maintenance windows.
- [ ] Identify sections of the MyVA that are covered by a maintenance window.
- [ ] Identify sections of the MyVA that are not covered by a maintenance window.
- [ ] Add document that outlines My VA maintenance windows.
- [ ] Create tickets for adding missing maintenance windows or any additional cleanup needed

## Acceptance Criteria
- [ ] Document and review findings with team.

**Comment by tpharrison** [comment]
@ajakabcin Ari and I have decided that the forms status work may not be a good fit given Ari's limited time on the team, so I'm going to pick up the tickets and Ari will work on this ticket (if you agree).

cc/ @mtcA6 @ACParker89

**Comment by ajakabcin** [comment]
I'm going to close this ticket as Ari and I worked to break this ticket out further. That work will be tackled next sprint.

**Comment by ajakabcin** [comment]
Follow-up tickets:
* #88434
* #88435
* #88436

**Comment by mattmarino-adhoc** [comment]
## Conditions to account for when downtime is happening:

### Claims and appeals
- Warning alert, NO links in any scenario [Figma](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-279&t=5awh2m2zTAdQYg5R-1)

### Health care
- All services are scheduled for downtime
  - No links, alert warning [Figma](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-279&t=5awh2m2zTAdQYg5R-1)
- Appointments are scheduled for downtime
  - No appointment cards, links still visible
  - _Note: messages may get its own downtime handling with a slim alert, but that will be after badge indicator release_

### Outstanding debts
- Only learn about VA debt link is visible, alert warning [Figma](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-266&t=5awh2m2zTAdQYg5R-1)

### Benefit payments
- No links, alert warning

### Benefit applications and forms
- No links, alert warning
