### ISSUE TITLE
Copy of Modals: Implement Delete Modals: Create a new modal component for deleting objects in Atlas

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#85714]
## User Story
As the owners of the Atlas application, 
We need to improve users ability to delete objects in Atlas by creating a modal component, 
So that the application is a more helpful, user-friendly tool overall and will be used more broadly by more VA internal teams. 

## Issue Description
As part of improving user experience and enhancing functionality, we need to implement modals for deleting and editing objects in the application. Currently, the process of deleting and editing objects lacks a user-friendly interface, and adding modals will help streamline these actions.

These 8 objects need modals on their new, show, edit, index pages.
<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2013ff8bef15b630cbc2a64846a1083fa43355a9/image.png" alt="image.png" />
## Tasks
- [ ] Determine what the best modal component would be for UX/UI users
- [ ] Create a new modal component in Atlas for deleting objects
- [ ] Test new modal component in lower environments
- [ ] Make any adjustments if testing reveals errors
- [ ] Retest as necessary
- [ ] Deploy to PROD environments

## Success Metrics
- [ ] New modal component in Atlas for deleting objects is stood up for users

## Acceptance Criteria
- [ ] Functional modal component for deleting objects exists in the Atlas application
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
