### ISSUE TITLE
Adjust noisy Datadog monitors

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#85719]
## Issue Description
While working on a Datadog monitor audit (https://github.com/department-of-veterans-affairs/va.gov-team/issues/79954), I noticed a few monitors that I didn't feel comfortable modifying, but that need some attention. These are both in Terraform.
1. [Platform - AWS Application Load Balancer % of HTTP 4xx Responses](https://vagov.ddog-gov.com/monitors/101715?view=spans) - this is very noisy. Occurs almost every day, often multiple times per day. I noticed it only happens overnight, so I [scheduled a recurring downtime](https://vagov.ddog-gov.com/monitors/downtimes?q=active%3Atrue%20automuted%3Afalse&id=3d1caa4e-2821-11ef-8661-da7ad0900007&sort=-start_dt) as a band-aid for the noise. Some things to consider with this monitor: evaluate the query to see if it needs adjusting, or find the root cause of the `4xx` responses. Make it actionable (what action should someone take if this alert triggers?). Is the notification routing appropriate?
2. [Platform - Forward Proxy Health Check Failures](https://vagov.ddog-gov.com/monitors/108772) is noisy. It alerts dozens times a day (b/c there are so many proxies to alert on). Evaluate the query to see if it needs adjusting, or investigate the failures. Make it actionable. Add `"ManagedBy:Terraform"` tag. 

## Tasks
- [ ] Adjust `Platform - AWS Application Load Balancer % of HTTP 4xx Responses` and update the Terraform. 
- [ ] Adjust `Platform - Forward Proxy Health Check Failures` and update the Terraform. 

## Success Metrics
Alerts are meaningful and actionable. 

## Acceptance Criteria
- [ ] Terraform is applied
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
- [ ] [Platform - AWS Application Load Balancer % of HTTP 4xx Responses](https://vagov.ddog-gov.com/monitors/101715?view=spans)  and [Platform - Forward Proxy Health Check Failures](https://vagov.ddog-gov.com/monitors/108772) have the changes applied from the Terraform. 
- [ ] These alerts aren't spamming #oncall or #devops-alerts.
