### ISSUE TITLE
Update copays in betamocks so dates are current (within past 6 mo)

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#85710]
## Description

When this feature flipper is enabled (http://localhost:3000/flipper/features/medical_copays_six_mo_window), copays don't show because they are outdated in Betamocks, and that makes it hard to test the portal.

Given: A designer/engineer needs to see copays in local/staging 
When: A designer/engineer looks at the debt portal
Then: They should see copays without having to disable the `medical_copays_six_mo_window` feature flipper

## Tasks
- [x] Update copay dates in betamocks to be recent (within the past 6 mo)

## Acceptance criteria

- [x] Copays display in the CDP without having to disable the feature flipper

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
