### ISSUE TITLE
Mock up VA Notify email notifications

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#85720]
## Background
We have [email notification content from CAIA](https://dvagov.sharepoint.com/sites/SitewideCAIA/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FSitewideCAIA%2FShared%20Documents%2F2%2E0%20Product%20work%2FAccredited%20representation%20management%20%28ARM%29%2FContent%20source%20of%20truth%2FEmail%20content&viewid=fd0991b9%2D7a3c%2D4731%2Dba07%2D4c0856c8311a) for:
1. Confirming the completion of a digital form-fill and reminding of next steps (MVP)
2. Confirming the digital submission and remind of next steps (v2)
3. Appointment has been accepted (v2)
4. Appointment has been declined (v2)

We also have access to the VA Notify self-service portal, to view existing email notification templates.  In the portal, you can also kick off a test email to yourself.  To access the self-service portal links below, you must be on the VA Network and signed in with PIV.
- staging.notifications.va.gov (Production)
- notifications.va.gov (Production)

## Tasks
- [ ] Put together mock-ups of the three email notification types outlined above, based on the existing email notification template designs (see the self-service portal for examples)
- [ ] Consult Research for any additional needs for a user test around notifications
- [ ] Confirm with ARM/ARF designers/researchers that designs and related content is ready for testing

## Acceptance Criteria
- [ ] Research has the materials they need to conduct a notifications test.

**Comment by oddball-lindsay** [comment]
Can do the mock ups directly in VA Notify Staging
