### ISSUE TITLE
[Spike] Metrics in GA4 and RUM for Location page

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#85722]
## Background/Request
VA Online Scheduling allows Veterans who are logged into VA.gov to schedule and manage their appointments.

The VAOS team released a feature for users to search facilities by recent locations. The "Sort by" field will default to "recent locations" in order to surface relevant facilities for Veterans and limit the amount of searching through irrelevant options.  

### Goal
Track whether the default "Sort by" field is changed from "Recent locations" to a different option by users along with time on page. 

### Requirements to Consider

---

## Tasks

  In GA4 and, where applicable RUM, track: 

- [ ] - The amount of time on page before and after implementing the change. 
- [ ] - If the "Sort by Recent locations" is being clicked on to change the default from "Sort by Recent locations" to something else. 
- [ ] - If the user does change the drop down from "recent locations", what are they changing it to?

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/85722?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by Bren22va** [comment]
Melissa to update to reflect GA instead of Data Dog

**Comment by melissa-lefevre** [comment]
I updated the ticket to use GA4 and RUM instead of Data Dog.

**Comment by jenniemc** [comment]
@melissa-lefevre , Can you please clarify the second task question?

- [ ] If the "Sort by Recent locations" is being clicked on to change the default from "Sort by Recent locations" to something else.

**Comment by jenniemc** [comment]
>  Q: The amount of time on page before and after implementing the change.

A: Presently we do not track the amount of time users spend on the facility selection page. Upon addition of “recent location” sort option we can add a tracker for time spent on the facility page.

> Q:  If the user does change the drop down from "recent locations", what are they changing it to?

A: We can record the final sort type selected when user clicks the continue button. In addition, we can also include how much time the user spends on the facility page. 

Suggested event name: "vaos-facility-[sortMethod]-selected"
accompanying name: "minutes-spent-on-facility-page" or "seconds-spent-on-facility-page"

**Comment by melissa-lefevre** [comment]
@jenniemc to clarify 

> If the "Sort by Recent locations" is being clicked on to change the default from "Sort by Recent locations" to something else.

What I am looking for is if the user changes the default (sort by recent locations) to somethign else. You answer this in your following comment. 

> We can record the final sort type selected when user clicks the continue button. In addition, we can also include how much time the user spends on the facility page.

That is perfect. I just need to know 1. How many users changing the drop down to something else and 2. What are they changing it to?

**Comment by jenniemc** [comment]
> 1. How many users changing the drop down to something else

We cannot track the number of users. However, in Goggle analytic tool, you can tally up the event name  `vaos-facility-recentLocation-selected` and see how many times it comes per day

**Comment by ldelacosta** [comment]
No additional details are needed. Closing out the ticket.
