### ISSUE TITLE
[DESIGN] Complete all documentation and hold handoff meeting for landing page pivot

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#85723]
## Background

Landing page logic for the pivot needs to be clearly documented for engineer, followed by a discussion/handoff to work through any questions

## Tasks
- [ ] Document landing page logic, including for CTAs/statuses/detail pages/etc.
- [ ] Share with engineers
- [ ] Hold FE/UX discussion/meeting for handoff

## AC
- [ ] Documentation complete
- [ ] Designs and documentation shared with engineers
- [ ] Handoff discussion/meeting complete and questions resolved

**Comment by cgednalske** [comment]
@wullaski @loripusey @zach-park @benbrasso-agile6 

Here's the [Figma page for the finalized landing page pivot](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1440-31468&t=FNgHx8yHTgEQz8jU-1), reviewed with @wullaski last week. We decided John will work directly from this page, rather than trying to incorporate these designs into Priority 1 (which might be confusing), but he'll let UX know if that preference changes. 

This follows the same design decided on by the team and reviewed with Kay and Kristen, with the only change being to also include the list in pre-check-in, without the CTAs/statuses in the list. 

If this looks good, we're ready to close the ticket out.
