### ISSUE TITLE
SPIKE: Search and Wizard Tracking Analytics Gap Analysis

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#8572]
# SPIKE: Analytics Gap Analysis 

## Description
- Perform a gap analysis of John's document [here](https://docs.google.com/document/d/1h3gRzoUM3FEMrTgimLx42OFK0LrKDV1b64bUxMeFri0/edit?usp=sharing) and determine: 
  - What we currently have solid tracking for
  - What can we report on well today
  - How are we measuring
  - What could be improved
  - What would be a brand new implementation
- As part of this analysis, this may include but is not limited to: 
  - Generating ad-hoc custom reports to determine what data we currently have
  - Testing within GTM/GA existing tracking
  - Identifying best implementation measure to meet the fold of what is being requested

- Who is this request for?
    - John Hasimoto

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@bsmartin-ep to do audit of search, @jonwehausen to do audit of wizard

**Comment by jonwehausen** [comment]
Hi @johnhashva , 

Thank you for your patience on this request. 

Please see [this document](https://docs.google.com/document/d/1GGnEqXngG2I0Y5USAWdGE_C0B0GwqJLJH5SFPWl22pg/edit?usp=sharing) with our assessment of both Search and Wizards. In here, we provide insight into what is available today, some example reports, and what we would need to do for further analysis. 

Let us know if you would like for us to setup a time with you to review live, we're happy to do that if needed and can discuss next steps.

**Comment by johnhashva** [comment]
@jonwehausen  thanks to you and the team for this.  will review closely today -- and very likely want to schedule a conversation next week, assuming availability, to discuss next steps.

**Comment by bsmartin-ep** [comment]
Closing. Related tickets:

Search:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9333
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9332

Wizard:
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/9510
