### ISSUE TITLE
[CST][ENG] Remove confusing sentence in file uploader experience

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#85738]
## Background Context

Right now in the the `AddFilesForm` component, it says:

"Please only submit evidence that supports this claim. **You’ll need to scan your document onto the device you’re using to submit this application, such as your computer, tablet, or mobile phone. You can upload your document from there.**"

We should remove the part that is bolded above. It refers to an application, but we are showing this content on the Files tab and in the Document Request page (not part of an application).

By removing the sentence, the content will read: 

"Please only submit evidence that supports this claim. To submit supporting documents for a new disability claim, please visit our (Link)_How to File a Claim page_."

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

This should be updated anywhere this text shows.

#### BEFORE
<img width="1142" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk5WQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e6aaf1d1371facd7e9a496e9649ff4293fccf5c/Screenshot%202024-06-11%20at%204.52.42%E2%80%AFPM.png" alt="Screenshot 2024-06-11 at 4.52.42 PM.png" />

#### AFTER
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d7789c236a9cbf06cfe633a43f8cef40b97d8a4/Screenshot%202024-06-11%20at%205.02.34%E2%80%AFPM.png" alt="Screenshot 2024-06-11 at 5.02.34 PM.png" />

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Other content updates to the File uploader experience, which may come later based on content recommendations.

## Open questions
- Is there anywhere the `AddFilesForm` component exists, but this text does _not_ show?

## Tasks
- [ ] _Remove the sentence "You’ll need to scan your document onto the device you’re using to submit this application, such as your computer, tablet, or mobile phone. You can upload your document from there." from `AddFilesForm.jsx`
- [ ] _Update the sentences so that they are combined to say "Please only submit evidence that supports this claim. To submit supporting documents for a new disability claim, please visit our (Link)_How to File a Claim page_." on the `AddFilesForm.jsx`

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _The AddFilesForm component no longer has the sentence "You’ll need to scan your document onto the device you’re using to submit this application, such as your computer, tablet, or mobile phone. You can upload your document from there."
- [ ] The AddFilesForm component now shows the sentence "Please only submit evidence that supports this claim. To submit supporting documents for a new disability claim, please visit our (Link)_How to File a Claim page_."

**Comment by pmclaren19** [comment]
@skylerschain this is now in Staging. Just validated and looks good! LMK if you have any questions or concerns!
