### ISSUE TITLE
[FE] "Build updated manage your profile" section

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8573]
related ticket: [[Design] Combine My VA profile/account links #8400](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8400)

Epic #8395
Related to ticket #5522

## Background
As a person trying to access my VA.gov profile/settings, I may be accessing my profile from another part of VA.gov and need links to the profile/settings to work correctly and content to be accurate so I don't get lost. Currently there are links to account and profile from my VA.gov, these need to be combined into a single link to profile.

![Screen Shot 2020-04-24 at 9.12.22 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b9786fc2-89e5-4632-a1e3-18dfc551000c)

## Tasks
- [ ] Build updated 'Manage your profile' section

## Acceptance Criteria
- [ ] Updated 'Manage your profile' has been built.
- [ ] This section has been built and reviewed by Tressa.
