### ISSUE TITLE
DR | Add additional PDF Validation

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#85749]
## Value Statement

**_As a_** Veteran

**_I want to_** upload evidence files and be immediately notified if there is a problem processing my evidence file

**_So that_** I can upload a different evidence file

---

## Background Context
This is a followup task to validate uploaded PDFs to better catch PDF errors before sending these files to CMP. The goal is to catch errors on the front instead of silently failing after submission to CMP.

# 83782

## Outcome, Success Measure, KPI(S), and Tracking Link
- Reduction in `Upstream status: Errors: ERR-EMMS-FAILED, Corrupted File detected.` errors from CMP

## Acceptance Criteria

- [ ] PDFs are validated before being accepted as evidence

## Out of scope
- Add here

## Open questions
- What is the acceptable performance hit for small and large PDFs?
- What is the possibility of false positives and how should they be handled?

## Tasks

- [ ] Use `pdf-reader` to parse uploaded files and check if an exception is thrown
- [ ] If an exception (`PDF::Reader::MalformedPDFError) is thrown, return an error to the frontend

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
