### ISSUE TITLE
Privacy Officer approval of email notification for Appoint MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#85745]
## Background
We've identified a Privacy Officer to partner with us on approval of our Appoint MVP email notification -- their name is Gina Siefert.  

This ticket is to track the collaboration with Gina, with the goal of getting approval of our MVP content.  I'm still curious about their thoughts on including a PDF download link in the email notification.

## Tasks
- [x] Meet with a Privacy Officer and receive feedback
- [x] Meet with Jonathan Kamens from Platform Security
- [ ] Reconnect with Privacy Officer and to understand next steps
- [ ] Act upon any next steps

## Acceptance Criteria
- [ ] Our email notification content has been approved by a Privacy Officer and is ready to be implemented via VA Notify.

**Comment by oddball-lindsay** [comment]
How Privacy Officer Gina Seifert feels okay about the download link in the email notification:
- No issues with providing this to authenticated users
- Concerned with providing this to unauthenticated users, but acknowledges that this is not a digital submission and is open to the idea of a "one time password"
- Recommends connecting with Jonathan Kamens to discuss our email notification content, including the download link

Also shared information about Privacy:
- https://department.va.gov/privacy/wp-content/uploads/sites/5/2023/12/FY24VeteransFacingServicesPlatformVagovVFSPVagovPIA.pdf
- https://department.va.gov/privacy/

Thinking I can verify with Jonathan Kamens that we are compliant with these policies.

**Comment by oddball-lindsay** [comment]
Jonathan recommended an approach for a secure form download link, and indicated that he doesn't think the rest of our email content will bump up against those Privacy policies that Gina referred to.

https://dsva.slack.com/archives/C01CJV0L9PS/p1718391727708629

**Comment by oddball-lindsay** [comment]
No response, will follow up with Gina.

**Comment by oddball-lindsay** [comment]
Missed an email from Gina on 

> I do not see a problem with the automatic email you plan to send.  It does not contain PHI.

I think we're good to go
