### ISSUE TITLE
Review confirm and reminder emails

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#85759]
## Description
The product team's request to review the confirm and reminder emails is in this comment on the intake ticket: [Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75068#issuecomment-2127693657)

## Tasks
- [x] KF: Draft recommendations
- [x] KF: Share recommendations with product team

## Criteria
- [x] Content recommendations have been shared with the product team

**Comment by katherine-fung** [comment]
Hi @aprocik1, 

My recommendations for the confirmation email are the end of the Sharepoint source of truth: https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Dependents%20Management/content-and-screenshots/686c_674%20Content%20source%20of%20truth.docx?d=w2c65a672bc3948b3a36ff8047f571c11&csf=1&web=1&e=irXdha

I haven't left recommendations for the reminder email. The copy follows a template that CAIA want to discuss with the VA Notify team about tweaking. The plan is to discuss this at the forms style huddle on 6/13.

**Comment by aprocik1** [comment]
@katherine-fung, thanks for sharing these updates. I left a small number of suggested copyedits. Feel free to accept or reject as you see fit.

**Comment by katherine-fung** [comment]
Thanks @aprocik1. 

I've let the team know that we've edited the confirmation email, and the reminder email is pending our team's edits to the reminder email template.

**Comment by katherine-fung** [comment]
Hi @aprocik1 @laurwill, 

After we're back from break, could you one of you review and finalize the email template for form reminder emails? https://docs.google.com/document/d/1wapWm7B-zYqmWFfs7igERlH4YSebzHV4SN3LBA2Mvlo/edit

I want to send the 686c team back copy for their reminder email (that team is planning to launch their form in Aug/Sept). Thank you!

**Comment by katherine-fung** [comment]
Based on our discussion in content sync on 7/8/24, I've gone ahead and sent the product team copy for the reminder email. I've also let them know that we haven't finalized a template for reminder emails and that at some point in the future when we have a template, we may revisit the email copy to make sure it aligns with the new template. 

Let's keep this ticket open for now in case the team has any questions. For now, our work on this ticket is done. 

cc @aprocik1 @strelichl

**Comment by aprocik1** [comment]
Update: I've moved this ticket to validate for now. We can keep it open for another week or two before closing it as complete.
