### ISSUE TITLE
PW Link Update Slack Announcement

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#85769]
The K15t Link update -- ALL links on the PW now open in the same tab -- needs to be announced on Slack. 

### TASKS

- [x] Draft announcement
- [x] Get team approval
- [x] Schedule announcement in the #platform-team slack channel

### Acceptance Criteria

- [x] Slack announcement posted

**Comment by jknipes** [comment]
[Slack announcement posted](https://dsva.slack.com/archives/CJRQ85PQB/p1718298003568809), moving to _Done_
