### ISSUE TITLE
Toxic Exposure: multipleExposures/exposureDates - Submit fails when beginDate and endDate are nil

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#85775]
## Issue Description
When submitting to Lighthouse's submit a TE application with blank begin and end dates for `toxicExposure/multipleExposures/exposureDates`, there is a bug on the LH side wherein they return 500 Bad Request.

```
        "multipleExposures": [
          {
            "exposureDates": {
              "beginDate": null,
              "endDate": null
            },
            "exposureLocation": "Other toxic exposures not listed here",
            "hazardExposedTo": null
          }
         ]
```

Slack thread: https://dsva.slack.com/archives/C02CQP3RFFX/p1718150280961289

---
## Tasks
- [ ] If a fix is reported as ready, validate 
- [ ] If a fix is _not_ ready, implement workaround: remove `exposureDates` node entirely if dates are blank
- [ ] Fix code when populating hazards into `multipleExposures` such that `hazardExposedTo` is populated with the exposure description instead of `exposureLocation` (the example above has it incorrect)

## Acceptance Criteria
- [ ] Lighthouse bug fix or workaround verified
- [ ] Hazard description populated in `hazardExposedTo` instead of `exposureLocation` within the `multipleExposures` array
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
That's better... (generated locally)
<img width="756" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFIvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f7a46dd2e2b4d05637981f9b39e0f8aa35ee7a8/image.png" alt="image.png" />

**Comment by sethdarragile6** [comment]
Confirmed in staging
<img width="656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk9KQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7183d1549648d99b3a14cd3abf79e358ec0f90f/image.png" alt="image.png" />
