### ISSUE TITLE
Audit wording for wait times post-submission

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#85786]
## Value Statement

**_As a_** Veteran

**_I want to_** have my expectations of submission timelines be accurately and consistently set

**_So that_** I know how long I should expect my submission to take before I can see its status in the Claim Status Tool

---

## Background Context

- See Ticket #85780

## Outcome, Success Measure, KPI(S), and Tracking Link

- All notifications post-submission set an accurate expectation of timeline to prevent re-submitting claims or reaching out for support prematurely

## Acceptance Criteria

- [ ] _All post submission notifications (both page and email) set the expectation that it may take 7-10 days for a claim to show in the various systems after submission_

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [x] _Audit wording of post submission pages for:_
   - [x] _Supplemental Claim_
   - [x] _Higher Level Review_
   - [x] _Board Appeal (Notice of Disagreement)_
- [x] _Audit wording of all Email Confirmation notifications_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
All of the wording in our confirmation pages say 7-10 days.

All of the wording in Lighthouse's confirmation emails say something different:
Board Appeal: 3 business days
Supplemental Claims: 24 hours
Higher Level Review: 24 hours

I left [a thread](https://dsva.slack.com/archives/C5AGLBNRK/p1719948066884429) in our decision-review channel to discuss next steps. This task can be considered closed.
