### ISSUE TITLE
Allow commonly-used (but currently-forbidden) characters in free text form fields - Implementation (PLACEHOLDER)

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#85808]
## Issue Description
In a previous story (#[85803](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85803)), we determined which fields to expand validation for, and got an answer from Lighthouse when they can implement. Once they've implemented the expansion, we need to change the front end (and possibly the backend) to allow this new validation.

---
## Tasks
- [ ] Change validation message(s) on affected fields
<img width="313" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDliQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5fab3bfb32b7534ae6ba2f81485d30f32ca3f5f/image.png" alt="image.png" />
- [ ] Change frontend validation regex to allow new characters (probably a copy/paste from the LH spec)
- [ ] Change backend validation regex, if applicable (i.e. `vets-json-schema`)

## Acceptance Criteria
- [ ] Implement new expanded validation

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
