### ISSUE TITLE
Allow commonly-used (but currently-forbidden) characters in free text form fields - Discovery (PLACEHOLDER)

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#85803]
## Issue Description
In certain form fields of the 526ez application, current validation disallows you from entering some commonly used punctuation. For example,

- parenthesis (())
- so called "smart quotes" (copy/pasted from other docs)

This story is to explore and decide upon 
- a more complete list of characters/punctuation we would like to allow
   - would any of our research/interviews help with this?
- which specific form fields along with their corresponding LH submit request fields would need to be modified

Once decided, we will ask Lighthouse about the feasibility of these modifications, their timeline, etc before moving onto the implementation story

[Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1718048668499149)

<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzViQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a9519790469191ebc10bec725a6fc2dbc01a4ec/image.png" alt="image.png" />

---

## Tasks
- [ ] _What will be created or happen as a result of this story?_
- [ ] 

## Acceptance Criteria
- [ ] Determine which characters from which form fields we'd like to allow
- [ ] Report to Lighthouse our request via slack

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
Closing as a duplicate
