### ISSUE TITLE
FE discovery for Implement Claim Certification / Signature and Supporting Evidence Alert Component

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#85822]
## Issue Description
In order to implement #84062 and #83534 the claim certification / signature component,  we need to do some FE discovery.

---
## Tasks
- [x] Watch design intent video (and midpoint 6/13) - in Collaboration Cycle Ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82160)
- [x] Do some tech discovery on how to implement this - do we have all the [library components](https://design.va.gov/) we need? Check [platform documentation](https://depo-platform-documentation.scrollhelp.site/). Are there any platform changes needed to implement this? How would we hook in to add these things?
   - [x] Intro page
   - [x] Review & submit page
- [x] May need to break up #84062 and #83534 to complete implementation

## Acceptance Criteria
- [x] High level plan of how to build #84062 and #83534 implementation of claim certification/signature component
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
@alatempa24 add the collab cycle ticket link

**Comment by christinec-fftc** [comment]
Was able to watch design intent and midpoint recordings and skim the mocks. Here's my 2 cents and questions

Confirming it looks like we can do the FE work in 2 tickets, but it would be good to re-refine based on what we learned from midpoint. A little fuzzy on some of the AC bullets in the stories. One thing I saw missing in AC's that is in the figmas is we need to link specifically to page 3 of the pdf.

It looks like we should be able to use the existing [alert](https://design.va.gov/components/alert) and [statement of truth](https://design.va.gov/components/form/statement-of-truth) components, adding in an input field for the full name and possibly [preSubmitInfo](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-form-config-options#VAFormsLibrary-FormConfigOptions-preSubmitInfo). Will leave it to @mchae-nava to confirm.

**Questions**
1.  For all 3 pages (intro, supporting evidence and review and submit), do we plan on adding heading annotations to the mocks for the steps and alert titles? This would be super helpful to make sure we address the a11y concerns from midpoint.

2. Looks like LH has a field for `claimantCertification`. On the BE, are we already marking this flag? It is required so assuming yes? On the FE, there is currently a field called `privacyAgreementAccepted`. Is it ok for us to reuse this field or do we need the ability to distinguish between the privacy agreement only vs claim certification?
 
3. For the 'Your full name' required field, do we need to do any validation on it? In terms of chars, length or comparing against an existing field. Also, Does this value need to be stored and submitted(doesn't seem like it, but just checking)

4. As noted above, can we please review the stories as a team one more time before starting the tickets?

**Comment by mchae-nava** [comment]
This was started in earnest 6/18, due to being absent, the sprint ending, and Juneteenth

**Comment by mchae-nava** [comment]
ZH does not like code block formatting, so will be posting and editing below to try and get it to render properly

Design Intent
https://github.com/department-of-veterans-affairs/va.gov-team/issues/84062
https://github.com/department-of-veterans-affairs/va.gov-team/issues/83534
“our intention was to add the claim certification Section 9, from the paper form onto the review and submit page for them to review, and then in this as well add the same content that we're using on the additional info components over here.”
Include a download link for PDF - for compliance and policy reasons
Question raised: is it better to display the information directly than linking to the PDF?
Better for screen readers
Way to specify what section is read by screen readers?
Way to display only relevant sections of the PDF?
Content of info component intended to match 1:1 the content of the paper form
“if they've ever put in any claim before, like the the Va. Will already have their dB. 214, their military service records all of that stuff”
But Veteran can’t see what the VA already has, in terms of evidence


Midpoint Review after Feedback
Info component would be both on the intro page and supporting evidence page
Still prefers linking to an HTML page - is there a leaner substitute for this?
Some way to make the info presented more lean? Headers?
Claim Certification on Submit page
Need to use v3 components
Need implementation for:
Alert component
Intro page process list
Certification/Signature
Link to specific page of PDF
Or leaner alternative
Accessibility considerations for anything implemented for PDF
Implementation
Alert component (“Notice of evidence needed”)
Can use existing va-alert component: https://design.va.gov/components/alert
Specifically refer to “Informational style (a.k.a. default)”; section link not working in documentation
`status=“info”`, `uswds=true`
Code: ```     <va-alert status="info" visible uswds>
<h3 className="vads-u-font-size--h3 vads-u-margin-top--0">Notice of evidence needed</h3>
        <p className="vads-u-font-size--base">
          We’re required by law…
        </p>
      </va-alert>```
Link: ```<a className="vads-u-font-size--base" href={PDF_URL}>
Review official requirements on VA Form 21-526EZ (PDF)</a>```
Process list
Can use existing va-process-list component: https://design.va.gov/components/process-list
Use default icons, h3 sizes, `uswds=true`
```<va-process-list uswds>
          <li>
            <h3>Prepare</h3>
            <h4>To fill out this application, you’ll need your:</h4>
            <ul>
              <li>Social Security number (required)</li>
            </ul>
            <p>
              <strong>What if I need help filling out my application?</strong>{' '}
              An accredited representative, like a Veterans Service Officer
              (VSO), can help you fill out your claim.{' '}
              <a href="/disability-benefits/apply/help/index.html">
                Get help filing your claim
              </a>
            </p>
          </li>
          <li>
            <h3>Apply</h3>
            <p>Complete this Mock form form.</p>
            <p>
              After submitting the form, you’ll get a confirmation message. You
              can print this for your records.
            </p>
          </li>
          <li>
            <h3>VA Review</h3>
            <p>
              We process claims within a week. If more than a week has passed
              since you submitted your application and you haven’t heard back,
              please don’t apply again. Call us at.
            </p>
          </li>
          <li>
            <h3>Decision</h3>
            <p>
              Once we’ve processed your claim, you’ll get a notice in the mail
              with our decision.
            </p>
          </li>
Certification/Signature
For certification: https://design.va.gov/components/form/statement-of-truth
Comes out of the box with a text field (signature) and checkbox, which has content that can be edited via `label`, `checkboxLabel`, `inputLabel`, `header`
```<StatementOfTruth content={{ 
label: veteranLabel,
              	text: veteranSignatureContent,
            }} />```
Make sure `inputMessageAriaDescribedby`, `inputError`, `checkboxError` are also set
It doesn’t appear any validation is done on the name entered, however, statement of truth is saved as a signature field, which can include both the name entered and the checkbox status:
```"statementOfTruthCertified": true,
"statementOfTruthSignature": "John Edmund Doe",```
In some instances, an additional `SignatureCheckbox` is used
 ```<SignatureCheckbox
          fullName={formData.veteranFullName}
          label={representativeLabel}
          signatures={signatures}
          setSignatures={setSignatures}
          showError={showError}
          submission={submission}
          isRepresentative
          isRequired
        >```
Link to specific page of PDF (or leaner alternative)
If using a URL (implied by content language), we can use the `page` parameter in the linked url `"#page=3"`
Otherwise, can generate a separate PDF that only contains page 3, for example
General Accessibility
Components already account for color, contrast, keyboard interactions, and screen readers
`claimantCertification`
This is a required field that I believe comes from the `veteranSignatureContent`
We would likely want a separate field to keep track of the privacy agreement, as this comes from a specific signature field
`privacyAgreement` is a separate checkbox component - does not necessarily need to be reused due to the presence of both the checkbox in StatementOfTruth and SignatureCheckbox components
Does anything need to be broken out?
The above code snippets will most likely be sufficient to cover our use cases
Accessibility is largely accounted for out-of-the-box via component library, with the only variable being accessibility concerns around the linked PDF
Validation of signature components on the backend, especially if we want to add validation to the signature name field would be worth breaking out once the frontend components have been implemented

**Comment by mengA6** [comment]
I created [Create accessibility annotations for claim certification / signature component mockups#87041](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/87041) to follow up on the earlier comment.

**Comment by christinec-fftc** [comment]
linking [doc](https://docs.google.com/document/d/1Kb31CEDtuKSiGm53NzA9XwEpuemSAkkFt84RIsiNJrc/edit) with Mark's findings

**Comment by christinec-fftc** [comment]
Notes on a possible mapping for platform's current statement of truth component which resides in `src/platform/forms/components/review/PreSubmitSection.jsx`

<img width="1431" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d0fb7a4ff4ed0f0c2a1dbf6f47fce20d6887a52/image.png" alt="image.png" />
