### ISSUE TITLE
[UX/FE] 10-10CG Last round of content edits post SME clarifying questions

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#85827]
## Issue Description
There were some outstanding stakeholder questions that surfaced during post-SME review and work on the static page on VA.gov. This ticket is to capture all those 

---
## Tasks
- [x] Gather all content SME questions and review at meeting Friday 6/14
- [x] Update Aliyah via Figma comments of what content changes are accurate to keep
- [x] Document changes to implement in this ticket and the Figma designs
- [x] Update staging with final content edits

## Acceptance Criteria
- Staging and the Figma design files contain all the final comments/SME approved and ready for final QA.

**Comment by jessicastump** [comment]
@longmd  - placeholder ticket that will be used to capture the last round of content edits on the CG updates.

**Comment by jessicastump** [comment]
Per CG email: 

>  If the Veteran and their caregiver(s) plan to use VA forms 21-22 and 21-22a as supporting documentation for another person signing on behalf of the Veteran, these forms would need to be completed and signed by the Veteran and their representative prior to submitting their online application. Then, the applicants would need to upload the form (when applicable) during the application submission process or provide the form to CSP staff during application processing (if they choose not to upload it during their online submission). There is not an approval process for the 21-22 and 21-22a forms. These forms are effective on the date they are signed and fully completed by the Veteran and their representative.

Friday a sentence was removed after the bulleted list of VA forms - mentioned decision letter. 

[Figma designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=376-15166&t=MqvD0HF3kgJ45IXZ-0) are accurate with what needs to be in staging.

Adding here and will update [ux weekly sync notes]https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/ux-team/design-weekly-sync-agenda.md) - Lois pointed out on the IVC forms that use a flow in that they allow the rep to state they have completed one of these forms and not upload the doc and it is asked as the first step in the form, not the last. Talked about opening a ticket to organize and prioritize all the remaining future items and possible UX debt that came from these July updates.

**Comment by jessicastump** [comment]
@longmd - tagging here in case that sentence/paragraph mentioned above is in dev/staging setup, to remove. That is the only last SME change (others are static page updates and Aliyah is handling those).

**Comment by jessicastump** [comment]
And just noticed Aliyah snuck in an **addition** on the intro page step 2:

> Or you'll need to upload a document showing you have authority to fill out and sign applications on behalf of the Veteran.
- Changed "two" to "2" on the add a secondary caregiver screens / questions
- She also flagged the URL on the intro page for "Learn more about the documents to submit" and how that could change with the family benefits hub URL work going on

Figma is updated and ... that is it!! All comments in Figma closed out :)
