### ISSUE TITLE
[Design] Update App Map V2 as source of truth for CST UI

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#85852]
## Value Statement
**_As a_** VA Benefits employee
**_I want to_** have a single source of truth for the latest CST UI
**_So that_** I know what the latest CST UI is

---
## Background Context

The App Map started as a project to document screenshots of the current implementation in staging. [App Map V2](https://www.figma.com/design/y27KDDtZLBDSVZmAjXdbJn/CST-App-Map?node-id=0-344) will serve as a source of truth for the UI, so that we can see in Figma what the latest designs are and they remain up-to-date and synced to our component library.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

<img width="1130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjljQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29dbd4d334f9ff5d24a1b2ba99d2958575204dec/TOC.png" alt="TOC.png" />

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Create new page structure for App Map_
- [ ] Move source of truth files from "Evidence Submission" to "App Map" Figma file_
- [ ] Sync any components to the Local Benefits Tools library that need to be synced_
- [ ] Ensure all library updates are incorporated
- [ ] Update CST ticket template so that the Definition of Done includes **'Design has updated App Map in figma'**

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _App Map V2 is the single source of truth for CST UI_
- [ ] _The App Map is easy to navigate, understand, and reference_
- [ ] _Documentation exists for how to maintain the App Map V2 going forward_
- [ ] _CST ticket template has a Definition of Done task of  **'Design has updated App Map in figma'**
- [ ] _Mocks in App Map V2 are linked to Local Benefits Tools library whenever possible_

**Comment by skylerschain** [comment]
The source of truth for CST V2 will be the [CST V2](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---V2-(Evidence-Submission)?node-id=0-1&t=W9vRsEFqlCyS5KPW-0) Figma file.
