### ISSUE TITLE
[Eng] Implement updates to HLR form content

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#85851]
## Value Statement

**_As a_** Veteran

**_I want to_** submit the most up-to-date Higher Level Review form

**_So that_** I won't be at risk of having the form returned to me for using an expired form

---

## Background Context

The HLR paper form was updated April 30, 2024. Updates are mostly within instructions and content of the form to simplify and adapt more plain language.

[Design updates are captured in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83861)

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] _Necessary content updates to HLR form have been implemented_
- [ ] _New form content is reviewed by enablement team stakeholders_

## Designs and Build Notes
[FIGMA](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=0-1)

**Updates added 7/11**

Content has been updated for the Request an Informal Conference pages, which includes one new screen.
[DESIGN](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=586-32815&m=dev)

The introduction content has also been updated.
[DESIGN](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=560-16887&m=dev)

Confirmation page removed inaccurate sentence about scheduled exams.
[DESIGN](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=782-41892&t=t91H6aweTTsj4lkx-11) (does not need to be behind a feature flag)

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] Update content on Information page ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=560-16887&m=dev))
- [ ] Update content in homelessness question ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=163-29654&m=dev))
- [ ] Update issues for review ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=586-32814&m=dev))
- [ ] Update content on the Request an informal conference page ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=586-32815&m=dev))
- [ ] Update content on the Review and submit page ([Spec](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=395-37711&m=dev))
- [ ] Update content on the Confirmation page [[Spec]](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=782-41892&t=t91H6aweTTsj4lkx-11) (does not need to be behind a feature flag)

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Can be checked in 'Review Instances' but might be moving to Codespaces, depending on what team decides.

**Comment by eileen-coforma** [comment]
Eileen to write up some of the content / flow that happened after extra CAIA recommendations.

**Comment by eileen-coforma** [comment]
Content has been updated for the Request an Informal Conference pages, which includes one new screen.
[DESIGN](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=586-32815&m=dev)

The introduction content has also been updated.
[DESIGN](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=560-16887&m=dev)

**Comment by eileen-coforma** [comment]
Forgot to add the confirmation page update. It's to remove a single sentence: _If VA schedules any exams for you, be sure not to miss them._

This doesn't need to be behind a feature flag, since it's inaccurate in PROD right now.

**Comment by eileen-coforma** [comment]
Work has been separated into multiple PRs because code has increased from feature flags.

**Comment by eileen-coforma** [comment]
@Mottie I made an updated to the 'Need Help' on the introduction. CAIA finally gave us the link language.

**Comment by Mottie** [comment]
Still working on unit tests. Hopefully PR will be ready today or tomorrow

**Comment by Mottie** [comment]
@eileen-coforma HLR content updates are now available for review in staging. I've just enabled the feature toggle.

**Comment by eileen-coforma** [comment]
@Mottie 

My bad. These are mistakes/content changes from my design file that got directly moved over.

**Intro** 

- Step 1: 21-0996 should be 20-0996
- Step 3: Additional Info: Remove 'If we schedule any exams for you, be sure not to miss them.' 

**Conference availability** for both Me and Accredited representative
- Change "We'll make two attempts to call you." to "We'll make two attempts to contact you."
- Change "Evening hours" to "Afternoon hours"

**Comment by anniebtran** [comment]
@eileen-coforma to validate

**Comment by eileen-coforma** [comment]
There's a pretty bad [memorable date error bug](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3113) that platform team needs to fix, but nothing we can do about it. Just keep an eye out for the fix.

**Comment by eileen-coforma** [comment]
Found bug. Made ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/90112

**Comment by anniebtran** [comment]
Separate tickets are created to cover any additional fixes/work, so closing this in favor of those
