### ISSUE TITLE
Encourage LOA1 users to verify their identity and unlock digital submission

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#85855]
## Background
We have uncovered that authentication covers two levels: LOA1 and LOA3.  LOA3 users will be eligible for digital submission, but LOA1 users will need to verify their identity if they want to unlock the digital submission in Appoint v2.

This means we will need additional messaging for LOA1 users.  Thinking we need to introduce a decision point where we ask LOA1 users if they want to verify their identity to unlock digital submission, or proceed down the form-fill process that ends in print/download.

[Here are some examples of the LOA1 experience](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707507504743/416bbf09f639569b08eda27e932984dd50ba02bc?wid=0-1717630697518) where a user is encouraged to verify their identity (which upgrades them to LOA3).

## Tasks
- [x] Create a design for this LOA1 decision point
- [x] Share with team for feedback
- [x] Adjust based on team's feedback
- [x] Discuss next steps with the team (midpoint review? include in a future user test?  right to dev?)

## Acceptance Criteria
- [x] Our Appoint v2 experience has a decision point for LOA1 users, where they have the opportunity to unlock digital submission.

**Comment by mtri** [comment]
[Initial designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=7238-105035&t=7YMfC0fGyY4YaizE-11)

To update based on [Slack convo here](https://dsva.slack.com/archives/C05L6HSJLHM/p1718982488263429).

**Comment by oddball-lindsay** [comment]
Designs are gelling, but we'll chat with Janelle tomorrow to confirm.

**Comment by oddball-lindsay** [comment]
Next step - ask for Midpoint async review
