### ISSUE TITLE
Run recruitment for study for Timely and Truthful Submission

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#85869]
## Issue Description

Note: 526 Submission Status research study will address the Epic Timely and Truthful Submission.

Initiate the recruitment process so that we can run a study to evaluate the clarity of the new submission model (loading screen, confirmation pages, emails). 

As a result of this work, we will have our participants scheduled and the study can begin. 
Required research materials are in #85134 and #85781

## Tasks
- [x] Communicate w/ Perigean throughout recruitment period
- [x] Prepare sign up sheet for research sessions and distribute 

## Acceptance Criteria
- [x] Recruitment is complete
- [x] Sign-up is shared on slack
- [x] Participants are recruited and scheduled for study

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by evelynhilbrichdavis** [comment]
@alatempa24 I split out this ticket to include the recruitment work explicitly. It also includes setting up and managing the sign up sheet. We might find that this work falls between two sprints-- dependent on timeline of prototype.
