### ISSUE TITLE
Talk database encryption with Steve Albers and Clint Little

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#85861]
## Background
Talk database encryption with Steve Albers and Clint Little.

## Tasks
- [x] Find out who should be part of this conversation
- [x] Schedule meeting
- [x] Have meeting
- [x] Document next steps

## Acceptance Criteria
- [x] The above tasks have been completed

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
Scheduled meeting with Steve Albers, Alex Prokop and Clint for Tuesday morning.

**Comment by holdenhinkle** [comment]
I had a really good meeting with Steve Albers and Clint Little this morning about database encryption. Lots of good action items came out of the meeting. Steve asked that I post the notes in the team-sensitive repo. 

Here’s the link - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/shared_notes/db_encryption.md
