### ISSUE TITLE
Design | Profile | Maintenance | Add personal health contacts to profile components and mock-ups

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#85867]
## Background
We don't have Personal health care contacts (DEFINITION AND EXAMPLE OR LINK: TK)  represented in the [Profile Figma files](https://www.figma.com/design/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?node-id=0-444&t=Z8ZcHvJM2lO049br-0).  We should add it across the board so it's represented correctly. 

There are very few files that include the expanded mobile menu, so this primarily impacts desktop files.

You can back into the Personal Health Care Contacts page by logging in w staging user 202. 

Personal healthcare contacts should be the third item on the hub and also in the left nav. 

<details><summary>screengrab</summary>

![image](https://github.com/user-attachments/assets/63f661b6-d5e3-421b-abc6-0ac37ee6a861)

</details> 

## Tasks

- [x] Review https://www.figma.com/design/OVc7YyBq4Fr5mJhcHWlMrc/Profile---Personal-health-care-contacts?node-id=0-444&t=zF1Pkt3x9sKjI97y-0

- [x] Request edit privileges

- [x] Add personal health care contacts to the [profile menu symbols](https://www.figma.com/design/Byfu9NRKXCtXN3DuMYguKI/Authenticated-Experience-Pattern-Library?node-id=190-1022&t=V7S9Q0oEQ9KazlAF-11) and publish changes

- [x] Request edit privileges

- [x] Update the auth library across profile files and double check that nothing got messed up :)
  - Hub
  - Personal info
  - Contact info
  - Military info
  - Account security
  - Direct deposit
  - connected apps
  - Notification settings

It'd be great to update the Personal health care contacts Figma files (LINKS: TK) to use the updated component too (if it's not already; it's possibly already using our symbol), but we're technically not responsible for maintaining those.  

## AC
Figma files include personal health care files

**Comment by twoangstroms** [comment]
I updated the main component in the Authenticated Experience Pattern Library and updated to the individual files, moving the "highlight" group. I noticed that the component wasn't in use in one of the files, so added that and deleted the individual elements. Ready for review.

**Comment by twoangstroms** [comment]
Asked another designer to validate that I could change master component without affecting other files negatively

**Comment by twoangstroms** [comment]
Reviewed by another designer and okayed

**Comment by mtcA6** [comment]
could you add the personal healthcare contacts to the mobile menu too seen here? 
https://www.figma.com/design/Byfu9NRKXCtXN3DuMYguKI/Authenticated-Experience-Pattern-Library?node-id=190-1022&t=BfEAG09Yc3lWg3yI-4

**Comment by twoangstroms** [comment]
Done

**Comment by twoangstroms** [comment]
@mtcA6 Can we close this?
