### ISSUE TITLE
Payment History VBA Pre-MVP 1.0 - FE Unit tests

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#85886]
## Description
To be completed with or after **Payment History VBA Pre-MVP 1.0 - Implement page(s) [#85887](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/85887)**. 

Write unit tests for new payment history table to confirm data and fallback/error messaging is displaying correctly. 

## Tasks
- [x] Write unit tests to confirm data will display correctly
- [x] Write unit tests to confirm any necessary fallback data is displaying correctly 
- [x] Confirm appropriate error logging is being conducted for failures 

## Acceptance criteria

- [x] New designs are covered by unit tests
- [x] Appropriate error logging is complete

## Testing
- [x] Yeah that's the idea

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
Docs link to: [transaction codes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/Transaction_Code_Mappings.md)

Currently, Max has a PR that includes a YAML file, which allowed me to generate a mock JSON object. We realized that it still needs a few code variations that show a decrease in balance.

JSON object from the YAML file:

```json
{
  "debts": [
    {
      "fileNumber": "796121200",
      "payeeNumber": "00",
      "personEntitled": "TJONES",
      "deductionCode": "71",
      "benefitType": "CH33 Books, Supplies/MISC EDU",
      "diaryCode": "100",
      "diaryCodeDescription": "Pending payment",
      "amountOverpaid": 0,
      "amountWithheld": 0,
      "originalAR": 166.67,
      "currentAR": 120.40,
      "debtHistory": [
        {
          "date": "09/18/2012",
          "letterCode": 100,
          "description": "First Demand Letter - Inactive Benefits - Due Process"
        }
      ],
      "fiscalTransactionData": [
        {
          "debtId": 328331,
          "transactionFiscalSource": "MR_FISC_TRX_HIST",
          "transactionFiscalCode": "04P",
          "transactionDescription": "Increase To AR",
          "transactionExplanation": "Increase To AR",
          "transactionDate": "06/06/2024",
          "transactionTotalAmount": 0.65,
          "offsetAmount": 0,
          "offsetType": null,
          "paymentType": null,
          "hinesCode": null,
          "transactionPrincipalAmount": 0,
          "debtIncreaseAmount": 0.65,
          "transactionInterestAmount": 0,
          "transactionAdminAmount": 0,
          "transactionCourtAmount": 0,
          "transactionMarshallAmount": 0,
          "transactionFiscalYear": null
        }
      ]
    },
    {
      "fileNumber": "796121200",
      "payeeNumber": "00",
      "personEntitled": "TJONES",
      "deductionCode": "72",
      "benefitType": "CH33 Housing EDU",
      "diaryCode": "608",
      "diaryCodeDescription": "Full C&P Benefit Offset Notification",
      "amountOverpaid": 0,
      "amountWithheld": 321.76,
      "originalAR": 321.76,
      "currentAR": 50.0,
      "debtHistory": [
        {
          "date": "09/18/2012",
          "letterCode": 100,
          "description": "First Demand Letter - Inactive Benefits - Due Process"
        }
      ],
      "fiscalTransactionData": [
        {
          "debtId": 328332,
          "transactionFiscalSource": "MR_FISC_TRX_HIST",
          "transactionFiscalCode": "04P",
          "transactionDescription": "Increase To AR",
          "transactionExplanation": "Increase To AR",
          "transactionDate": "06/06/2024",
          "transactionTotalAmount": 0.65,
          "offsetAmount": 0,
          "offsetType": null,
          "paymentType": null,
          "hinesCode": null,
          "transactionPrincipalAmount": 0,
          "debtIncreaseAmount": 0.65,
          "transactionInterestAmount": 0,
          "transactionAdminAmount": 0,
          "transactionCourtAmount": 0,
          "transactionMarshallAmount": 0,
          "transactionFiscalYear": null
        }
      ]
    },
    {
      "fileNumber": "796121213",
      "payeeNumber": "00",
      "personEntitled": "STUB_M",
      "deductionCode": "44",
      "benefitType": "CH35 EDU",
      "diaryCode": "080",
      "diaryCodeDescription": "Debt referred to Treasury for Cross servicing",
      "amountOverpaid": 26000,
      "amountWithheld": 0.0,
      "originalAR": 100,
      "currentAR": 110,
      "debtHistory": [
        {
          "date": "04/11/2013",
          "letterCode": "080",
          "description": "Debt referred to Treasury for Cross servicing"
        },
        {
          "date": "12/19/2014",
          "letterCode": "681",
          "description": "Account returned from Treasury Cross Servicing. Account is at TOP.  TOP offsets will be applied to account as Federal funds become available."
        },
        {
          "date": "12/11/2012",
          "letterCode": "510",
          "description": "Demand letters returned.  Unable to verify address with third party.  Account forced to TOP and/or CS."
        },
        {
          "date": "10/17/2012",
          "letterCode": "212",
          "description": "Bad Address - Locator Request Sent"
        }
      ],
      "fiscalTransactionData": [
        {
          "debtId": 328333,
          "transactionFiscalSource": "MR_FISC_TRX_HIST",
          "transactionFiscalCode": "04P",
          "transactionDescription": "Increase To AR",
          "transactionExplanation": "Increase To AR",
          "transactionDate": "06/06/2024",
          "transactionTotalAmount": 0.65,
          "offsetAmount": 0,
          "offsetType": null,
          "paymentType": null,
          "hinesCode": null,
          "transactionPrincipalAmount": 0,
          "debtIncreaseAmount": 0.65,
          "transactionInterestAmount": 0,
          "transactionAdminAmount": 0,
          "transactionCourtAmount": 0,
          "transactionMarshallAmount": 0,
          "transactionFiscalYear": null
        }
      ]
    },
    {
      "fileNumber": "796121299",
      "payeeNumber": "00",
      "personEntitled": "STUB_M",
      "deductionCode": "44",
      "benefitType": "CH35 EDU",
      "diaryCode": "811",
      "diaryCodeDescription": "Debt referred to Treasury for Cross servicing",
      "amountOverpaid": 0.0,
      "amountWithheld": 0.0,
      "originalAR": 100,
      "currentAR": 1800,
      "debtHistory": [
        {
          "date": "12/19/2018",
          "letterCode": "681",
          "description": "Account returned from Treasury Cross Servicing. Account is at TOP.  TOP offsets will be applied to account as Federal funds become available."
        },
        {
          "date": "10/17/2020",
          "letterCode": "212",
          "description": "Bad Address - Locator Request Sent"
        }
      ],
      "fiscalTransactionData": [
        {
          "debtId": 328334,
          "transactionFiscalSource": "MR_FISC_TRX_HIST",
          "transactionFiscalCode": "04P",
          "transactionDescription": "Increase To AR",
          "transactionExplanation": "Increase To AR",
          "transactionDate": "06/06/2024",
          "transactionTotalAmount": 0.65,
          "offsetAmount": 0,
          "offsetType": null,
          "paymentType": null,
          "hinesCode": null,
          "transactionPrincipalAmount": 0,
          "debtIncreaseAmount": 0.65,
          "transactionInterestAmount": 0,
          "transactionAdminAmount": 0,
          "transactionCourtAmount": 0,
          "transactionMarshallAmount": 0,
          "transactionFiscalYear": null
        }
      ]
    },
    {
      "fileNumber": "796121200",
      "payeeNumber": "00",
      "personEntitled": "AJOHNS",
      "deductionCode": "74",
      "benefitType": "CH33 Student Tuition EDU",
      "diaryCode": "117",
      "diaryCodeDescription": "Pending payment",
      "amountOverpaid": 0.0,
      "amountWithheld": 475.0,
      "originalAR": 2210.9,
      "currentAR": 1000,
      "debtHistory": [
        {
          "date": "04/01/2017",
          "letterCode": "608",
          "description": "Full C&P Benefit Offset Notification"
        },
        {
          "date": "11/18/2015",
          "letterCode": "130",
          "description": "Debt Increase - Due P"
        },
        {
          "date": "04/08/2015",
          "letterCode": "608",
          "description": "Full C&P Benefit Offset Notification"
        },
        {
          "date": "03/26/2015",
          "letterCode": "100",
          "description": "First Demand Letter - Inactive Benefits - Due Process"
        }
      ],
      "fiscalTransactionData": [
        {
          "debtId": 328335,
          "transactionFiscalSource": "MR_FISC_TRX_HIST",
          "transactionFiscalCode": "04P",
          "transactionDescription": "Increase To AR",
          "transactionExplanation": "Increase To AR",
          "transactionDate": "06/06/2024",
          "transactionTotalAmount": 0.65,
          "offsetAmount": 0,
          "offsetType": null,
          "paymentType": null,
          "hinesCode": null,
          "transactionPrincipalAmount": 0,
          "debtIncreaseAmount": 0.65,
          "transactionInterestAmount": 0,
      "transactionAdminAmount": 0,
      "transactionCourtAmount": 0,
      "transactionMarshallAmount": 0,
      "transactionFiscalYear": null
    }
  ]
}]
}```

**Comment by amponce** [comment]
Moving this to blocked as we wait for the pages’ implementation to be merged, as well as the final mock data for the vet-api to be merged.

**Comment by amponce** [comment]
Had a conversation with Derek today, and it looks like we need to have @maxx1128  adjust the fiscalTransactionCode in the mock data to support balance increase and decrease messages. @Tom-Davis

**Comment by amponce** [comment]
I've updated the PR with the new BE data and move the ticket to review @Tom-Davis @HeatherRienks
