### ISSUE TITLE
Payment History VBA Pre-MVP 1.0 - Confirm data mapping (BE -> Design)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#85884]
## Description
Confirm data mapping between designs and what we receive from BE so all of the appropriate data is in the right place (and we have access to it). This could also be a good time to confirm some fallback cases and ensure everything we try to access will exist.

## Tasks
- [x] Coordinate with design and BE to confirm mapping data from BE to the design specs
- [x] Answer any questions and investigate potential edge cases

## Acceptance criteria

- [x] Data mapping from BE to design is confirmed

## Testing
- [x] N/A 

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by amponce** [comment]
It appears that some design updates are in progress based on feedback from last week. Here is the related ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/84646

Payment History mockups:

[Paid off debt](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1993-41891&t=XBI9XpwoFsjO9TPe-11)
[Benefit offset](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-31768&t=XBI9XpwoFsjO9TPe-11)
[Referred to treasury](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-32264&t=XBI9XpwoFsjO9TPe-11)

I've opened a thread with the BE team to get up to speed on the data that will be available to the frontend.

**Comment by mgleo** [comment]
Hi @amponce 
Here are the current designs for Phase 1:
[#86212](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/86212)

Phase 1 MVP: Overpayment summary page and detail page:
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-17591&t=yCqrWzggTvn2bMBb-1

**Comment by amponce** [comment]
Nice to have vs reality:

```json
{
  "debtDetails": {
    "type": "Post-9/11 GI Bill debt for books and supplies",
    "status": "fully paid off",
    "currentBalance": "$0.00",
    "originalOverpayment": "$200.00",
    "totalPaid": "$230.00",
    "totalFeesInterest": "$30.00",
    "lastPaymentDate": "June 8, 2020",
    "nextPaymentDue": "N/A"
  },
  "transactions": [
    {
      "transactionCode": "04Q"
      "date": "June 8, 2020",
      "description": "Partial payment of $40.00", 
      "amount": "-$40.00"
    },
    {
      "transactionCode": "04Q"
      "date": "May 8, 2020",
      "description": "Partial payment of $100.00",
      "amount": "-$100.00"
    },
    {
      "transactionCode": "04Q"
      "date": "April 8, 2020",
      "description": "Partial payment of $50.00",
      "amount": "-$50.00"
    },
    {
      "transactionCode": "04Q"
      "date": "March 8, 2020",
      "description": "Partial payment of $20.00",
      "amount": "-$20.00"
    },
    {
      "transactionCode": "08Q"
      "date": "February 8, 2020",
      "description": "Late fee",
      "amount": "$15.00",
      "details": "Interest and administration costs were charged because of a previously unpaid bill."
    },
    {
      "transactionCode": "04Q"
      "date": "January 8, 2020",
      "description": "Partial payment of $20.00",
      "amount": "-$20.00"
    },
    {
      "transactionCode": "08Q"
      "date": "December 8, 2020",
      "description": "Late fee",
      "amount": "$15.00",
      "details": "Interest and administration costs were charged because of a previously unpaid bill."
    },
    {
      "transactionCode": "08Q"
      "date": "November 8, 2020",
      "description": "Overpayment for Post-9/11 GI Bill debt for books and supplies",
      "amount": "$200.00"
    }
  ]
}
```
```json
[
  {
    "file_number": "string",
    "payee_number": "string",
    "person_entitled": "string",
    "deduction_code": "string",
    "benefit_type": "string",
    "amount_overpaid": "string",
    "amount_withheld": "string",
    "debt_history": [
      {
        "date": "string",
        "letter_code": "string",
        "status": "string",
        "description": "string"
      }
    ]
    "transaction_payment_history":  [
	{
          "transactionFiscalSource": "FHOF_FISC_TRX_HIS",
          "transactionFiscalCode": "08P",
          "transactionDescription": "Decrease A/R amount in CARS only",
          "transactionExplanation": "Comes from Hines Recon. Due to transaction imbalance between BDN and CARS. BDN amount is lower than CARS.",
          "transactionDate": "06/16/2018 12:00:00 AM",
          "transactionTotalAmount": "200.00",
          "offsetAmount": "200.00",
          "offsetType": "TOP",
          "paymentType": "ACH",
          "hinesCode": "08A",
          "transactionPrincipalAmount": "200.00",
          "debtIncreaseAmount": "2000.00",
          "transactionInterestAmount": "0.00",
          "transactionAdminAmount": "0.00",
          "transactionCourtAmount": "0.00",
          "transactionMarshallAmount": "0.00",
          "transactionFiscalYear": "2018",
          "user": "USER NAME"
          },
          {
          "transactionFiscalSource": "FHOF_FISC_TRX_HIS",
          "transactionFiscalCode": "08P",
          "transactionDescription": "Decrease A/R amount in CARS only",
          "transactionExplanation": "Comes from Hines Recon. Due to transaction imbalance between BDN and CARS. BDN amount is lower than CARS.",
          "transactionDate": "07/16/2018 12:00:00 AM",
          "transactionTotalAmount": "150.00",
          "offsetAmount": "200.00",
          "offsetType": "TOP",
          "paymentType": "ACH",
          "hinesCode": "08A",
          "transactionPrincipalAmount": "150.00",
          "debtIncreaseAmount": "1500.00",
          "transactionInterestAmount": "0.00",
          "transactionAdminAmount": "0.00",
          "transactionCourtAmount": "0.00",
          "transactionMarshallAmount": "0.00",
          "transactionFiscalYear": "2018",
          "user": "USER NAME"
        }
     ]
  }
]

"debt_letters": [
    {
    "document_id": "string",
    "doc_type": "string",
    "type_description": "string",
    "received_at": "string"
   }
]
```

**Comment by amponce** [comment]
Up to date design

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/e139a7e9-0d9d-40a0-a725-26cb32d4b81f)

**Comment by mgleo** [comment]
Hi @amponce, the Date, Description, Amount table is up to date on the screenshot you shared above. 
However, the items above and below the table are a part of Phase 2 MVP. The Phase 2 MVP will be a part of our research study but may not be implemented.

Here is the Phase 1 MVP: Overpayment summary page and detail page:
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-17591&t=yCqrWzggTvn2bMBb-1
<img width="836" alt="Screenshot 2024-06-21 at 9 40 32 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/3f0b0f3f-b771-4478-8c9f-4a49206e11f2">

**Comment by amponce** [comment]
Added the transaction codes and descriptions to our frontend docs with JSON mappings

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/Transaction_Code_Mappings.md

**Comment by amponce** [comment]
TODO: Follow up with Christine - Add fallback message in case a transaction mapping fails.

**Comment by josephrlee** [comment]
@amponce Here are the updated screens with all the annotations:

[Summary page](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2039-21548&t=JRJaqvWLlFs3WQBA-11): 
<img width="1423" alt="Screenshot 2024-06-24 at 4 57 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/ed0792f3-a770-4cd1-90d7-b4407bd168b2">

[Detail page](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-16864&t=JRJaqvWLlFs3WQBA-11): 
<img width="1380" alt="Debt detail table transaction history" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/f692f305-e711-40e9-a9c5-8e58b19341a5">

cc: @mgleo @HeatherRienks
