### ISSUE TITLE
Payment History VBA Pre-MVP 1.0 - Create feature flag

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#85880]
## Description

Create a feature flag to hide the new section for Payment History behind during development. There should be a corresponding PR in the vets-api repo as well as vets-website.

New pattern exhibited in Andrew's latest feature flag PR's should be used. Toggle structure. Examples below:
[vets-website pr](https://github.com/department-of-veterans-affairs/vets-website/pull/30334)
[vets-api pr](https://github.com/department-of-veterans-affairs/vets-api/pull/17107) 

## Tasks
- [ ] Feature flag pr created: vets-website
- [ ] Feature flag pr created: vets-api

## Acceptance criteria

- [ ] Both PR's created and merged
