### ISSUE TITLE
Editorial enhancement: Staff profiles 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8589]
## User Story or Problem Statement
How might we make entering staff profiles more efficient for content creators?

Current workflow of entering staff profiles and populating coordinators for service pages (ie: caregiver coordinators and patient advocates) is not efficient

## Goal
Efficient method to load for staff profiles and populate coordinator and advocate fields 

## Objectives or Key Results this is meant to further
- Objective 4: Deliver an efficient editorial experience

## Tasks
- [ ] TBD: this is a placeholder issue

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
Not clear what specific inefficiencies where being referenced here. Will check is still relevent
