### ISSUE TITLE
Create landing/explainer page for Feedback Repo

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#85903]
## Purpose
We need a page for folks to be directed to that explains the FR, leads them to it, and also may link to explanatory documentation.

Note:  FDG landing may provide a good example of how to approach this.

## Tasks
- [x] brainstorm needed features of landing (summary, link to IR, how-to-use documentation)
- [x] include findings and recommendations from prior tickets [1](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3218112513/Feedback+Review+OCTO+PO+role+type+view+w+suitable+SMEs), [2](https://vfs.atlassian.net/wiki/spaces/~622b5b63932f0f00716bdfd6/whiteboard/3233611783)
- [x] draft new landing
- [x] design lead review
- [x] update as needed

## Acceptance Criteria
- [x] Landing page is ready for launch
