### ISSUE TITLE
Updating Offboarding Tasks in Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#85908]
## Description 

We need to update our documentation to match our process for off-boarding. If these steps exist, we can just point to them in our documentation below:

- [Tier 1 Support Support Responsibilities](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3094839491/Tier+1+Support+Responsibilities#Access-Requests[hardBreak])
- [What We Can Help With](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support) 

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Sync up with Brandon to identify what off-boarding tasks our team is responsible for (if don't know already)
- [x] Add steps to working an off boarding ticket or links to the steps if they exist to both documents listed in the description above
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
