### ISSUE TITLE
VRE V1B | Consolidate "must" and "may" review pds into parent folders

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#85975]
## Issue Description
_The V1B "must" and "may" review pdf batches were previously provided as individual zip folders where each pdf was contained in its own folder. The VBA has requested that the pdfs be consolidated into two parents folders: one for the "must" batch and one for the "may" batch._

---
## Tasks
- [ ] Update the script and re-export the V1B files

## Acceptance Criteria
- [ ] Upload "must" folder with pdf files to VA SharePoint
- [ ] Upload "may" folder with pdf files to VA SharePoint
---
