### ISSUE TITLE
AskVA Data Validation in DOMO

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#85979]
## Issue Description
As a data analyst, I want to ensure the accuracy and reliability of our customer database. Therefore, I need a robust data validation process to identify and correct any inconsistencies or errors.
---
## Tasks
- [x] Determine acceptable data formats, ranges, and constraints 
- [x] Data profiling - generate summary statistics 
- [ ] Compare data against expectations
- [ ] Validate data accuracy 
- [ ] Validate data relationships 
- [ ] Validate data manually 
- [ ] 

## Acceptance Criteria

 - [x] **Scenario: Determine acceptable data formats, ranges, and constraints**
  - Given the data validation process is being implemented
  - When determining acceptable data formats, ranges, and constraints
  - Then the appropriate rules should be established for each field in the customer database
- [x] **Scenario: Data profiling - generate summary statistics**
  - Given the data validation process is being implemented
  - When generating summary statistics for the customer database
  - Then the mean, median, mode, minimum, and maximum values should be calculated for each field
- [ ] **Scenario: Compare data against expectations**
  - Given the data validation process is being implemented
  - When comparing the data against established expectations
  - Then any discrepancies or inconsistencies should be identified and flagged for further investigation
- [ ] **Scenario: Validate data accuracy**
  - Given the data validation process is being implemented
  - When validating the accuracy of the customer database
  - Then any inaccurate, incomplete, or duplicate records should be corrected or removed
- [ ] **Scenario: Validate data relationships**
  - Given the data validation process is being implemented
  - When validating the relationships between different fields and records in the customer database
  - Then any inconsistencies or errors in these relationships should be identified and resolved
 - [ ] **Scenario: Validate data manually**
   - Given the data validation process is being implemented
   - When manually validating the customer database
   - Then any errors or discrepancies found during manual review should be corrected or flagged for further investigation

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by newworld2616** [comment]
<img width="1689" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzE5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8610f256f0d27b104975a0c842dac2ae09a3b286/image.png" alt="image.png" />
<img width="1787" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEY5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3381a56783919ae1cb31a18fdda781330ecd7556/image.png" alt="image.png" />
[Uploading... image.png]
We have meeting with CXI team to Validate the AVA DOMO data.

**Comment by ATMiddleton** [comment]
Sarifa Khalilullah
  10:31 AM
HI Mason, I have shared the PBI link on VA teams


Mason Crane
  10:39 AM
Thank you for that! I had to request access, so if someone could grant that for me, that'd be great!


Sarifa Khalilullah
  10:40 AM
I think, you could submit through the page and they will approve it quickly.


Mason Crane
  10:40 AM
That's exactly what I did :slightly_smiling_face:
:+1:
1



Mason Crane
  11:08 AM
To download the workbook to PBI desktop I need to be a "contributor" at least for the workspace. Is this something I can be granted?


Anita Middleton
  12:01 PM
Chris just informed me that everyone should be good to go.


Mason Crane
  12:59 PM
so I am still unable to download the workbook:
image.png
 
image.png
12:59
I may need more elevated permissions, or if someone could download the workbook as a pbx, and send it to me, that'd work as well


Chris Clemens
  1:01 PM
was added to the conversation by Anita Middleton
.


Anita Middleton
  1:02 PM
Hey Chris,
Please forgive the back and forth, but, would it be possible to download the workbook as a pbx and post here for the team.  As Mason stated above, elevated permissions may be required.


Chris Clemens
  1:11 PM
@Mason Crane
 I bumped you up to Admin - hopefully that works.  I can put you back to Contributor once you have what you need


Mason Crane
  1:14 PM
Chris, do you see an option to download the PBI workbook?
1:14
I'm now worried its my actual account, my PBI license that is stopping me
1:14
image.png
 
image.png


1:15
i have a "free" account and I wonder if that is keeping me from being able to download the workbook
1:15
there should be something under file, or export that gives you the ability to download the workbook
1:16
hmm, I am backdooring my way through the data source, vs the app. Please hold
1:21
Okay, I was able to download the file, and sent it to 
@Sarifa Khalilullah
 as well. However, the problem we are having now is that the file is using a live connection, which isn't allowing me the ability to download the data and determine how things are being calculated:
image.png
 
image.png


1:22
However, Sarifa, you can see the tables being used, and the calculations as well:
image.png
 
image.png


1:22
So my advice would be to dig into these tables, see the fields and calculations, and make sure you're mapping everything the same way with your pulls (edited) 
:+1:
1

1:23
Thank you 
@Chris Clemens
, we "should" be good for now. If it doesnt hurt to leave me as an admin while we continue digging, but i'll let you be the judge of that.
:+1::skin-tone-2:
1



Chris Clemens
  1:24 PM
that's a big file  - it may die here
1:24
Something like this?
Binary
 

AVA Prod.pbix
Binary




Mason Crane
  1:38 PM
That's perfect Chris. 
@Sarifa Khalilullah
, if you download that and open with PBI, it has the tables/data logic. It shows where the data is coming from. For example, Ods email is coming from a sql database called:
image.png
 
image.png


1:39
the "Item" is the table, under navigation. So there is a table called inquiry_action living on that cloudapi.net database
1:39
@Chris Clemens
, do you know who owns that server?


Chris Clemens
  1:40 PM
I do not


Mason Crane
  1:41 PM
To understand the true source systems, our next task would be to determine who owns that server, and then how they are ingesting the information, to confirm its the same sources that the CXI data that AVA is using for Domo
:+1:
1

1:41
sorry, can you confirm, we are using CXI's AVA data in Domo, 
@Sarifa Khalilullah
?


Sarifa Khalilullah
  1:42 PM
Yes, it is CXI from Azure


Mason Crane
  1:42 PM
Perfect, so I'd reach out to your contact(s) within CXI and ask them if they know about that server, best case they are the owners


Sarifa Khalilullah
  1:43 PM
Chris was assisting us with the CXI


Chris Clemens
  1:43 PM
Ha. now you're in trouble
:smile:
2



Mason Crane
  1:43 PM
Someone you can reach out to is Nicholas Pizzuti
1:44
he manages the datapipelines for ingestion of CXI, he is a good 2nd step
1:44
1st step was you Chris haha
:eyes:
1

New


Chris Clemens
  9:41 AM
@Sarifa Khalilullah
 the pbix is up above in this thread

Downloaded opened database with PBI, it has the tables/data logic. It shows where the data is coming from. For example, Ods email is coming from a sql database called.  Additional access is required and Nick

**Comment by ATMiddleton** [comment]
6/26/24 - Email to Nicholas Pizzuti requesting assistance with identifying server owner for continuation. 

Will create a new ticket for completion
