### ISSUE TITLE
Onboarding Documentation Training Modules 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#85976]
## Issue Description
Creation of step-by-step instructions including screenshots for Salesforce, Service Now, and AskVA. This will take multiple sprints to complete. For 6/16-6/29/2024 sprint, discovery and prototype for AVA module are the goal. Prototype will be used to create modules for SF, SNOW, and more AVA topics.
---
## Tasks
- [ NA ] Document and capture step-by-step instructions for Salesforce (Later sprint)
- [ NA ] Document and capture step-by-step instructions for Service Now (Later sprint)
- [x] Document and capture step-by-step instructions for AskVA
- [x] Discovery for Training Modules 

## Acceptance Criteria

 - [x] **Protype for training modules complete.
 
---
## How to configure this issue
- [ x] **Attached to an Epic** (what body of work is this a part of?)

**Comment by ATMiddleton** [comment]
Will add training modules upon completion 
https://docs.google.com/document/d/1w69RkZtBAlUUkT5dPF7Lx2k8I11mMEuVlGDfFapow2g/edit

**Comment by ATMiddleton** [comment]
Will extend beyond current sprint.  A new ticket will be created to document progress.

**Comment by starlow00** [comment]
Discovery and AVA prototype complete for this sprint. May alter further for page color variance in future modules.

https://docs.google.com/presentation/d/17_lCgJBdqAIWrqDZCcmynE4f44T7JcrgtJHte7WSB6M/edit?usp=sharing
