### ISSUE TITLE
Decide on approaches to implement for Toxic Exposure alerts announcing new questions to Veterans with in-progress forms

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#85977]
## Issue Description
Following from [UX & UI changes needed for TE rollout: finalize with input from CAIA and create implementation tickets#82236](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/82236) and [Toxic Exposure 1.1: Discovery for SiP and Review and Submit Alerts#85695](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85695), decide on approaches to implement and make / adjust implementation tickets accordingly.

---
## Tasks
- [ ] Decide whether to show modified "Save in Progress" alert, and if so, how to approach where the links go
- [ ] Decide on where to add the alert on the "Review and Submit" page, balancing engineering effort noted against [design system guidance for placement of alerts](https://design.va.gov/components/alert#placement). Might need OCTO guidance on this.

## Acceptance Criteria
- [ ] team and OCTO aligned on approach
- [ ] Implementation tickets up to date with chosen approach

**Comment by mengA6** [comment]
See discussion [here in Slack](https://agilesix.slack.com/archives/C04MJV66ZPC/p1718910829649329?thread_ts=1718902962.121789&cid=C04MJV66ZPC)
