### ISSUE TITLE
[TOU] MHV add sync query

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#86009]
## Description
Update TermsOfUse component to parse a new query parameter `synchronous=true`

Reference [Slack thread](https://dsva.slack.com/archives/C06JLV08D32/p1718312856109819)

## Tasks
- [x] Parse `synchronous` query parameter
- [x] Add `sync=true` if `synchronous` exists and the value is true
- [x] Create an MHV TOU user flow Figjam
- [x] Add documentation of new error code, etc.

**Comment by asg5704** [comment]
Closing. Joe mentioned we might not need the `sync` property.
