### ISSUE TITLE
[CONTENT]  Review and update Health Services Library using new guidelines and input [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8600]
## User Story or Problem Statement
As a Veteran Web user, I need to have clear and correct health services descriptions, so I can get the appropriate level of support provided by the VA.

## Goal
_Efficient and clear content describing local Health Service provided_
_Reduce click through of pages for Veterans_

## Objectives or Key Results this is meant to further
- _Reduced click through of pages in finding the correct resource._

## Resources - Tools - Documentation
[List of 95 Health Services](https://drive.google.com/drive/search?q=95%20health%20services)
[System level health services library](https://drive.google.com/drive/folders/13ZTUm1U40BsC5MQcgGulcZ_DxvJAkDIQ)

## Tasks
_Tasks that must be complete on Health Service Library:_
- [x] Update all System Health Services to the latest guidelines 
- [x] There should only be one primary description for each Health Service with no more than six (6) bullets
- [x] Language must be followed by correct URL to be added to Hyperlink for each Health Service if required

## Acceptance Criteria
_The following items must be provided to Product Manager for review and placement into HSL:
* Update all System Health Services to the latest guidelines 
* There should only be one primary description for each Health Service with no more than six (6) bullets
* Language must be followed by correct URL to be added to Hyperlink for each Health Service if required
