### ISSUE TITLE
[FSR] Feature Flag Removal (vets-website)

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-team#86014]
## Description

This ticket is a ticket opened after the [Feature Flag Cleanup Discovery.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81813) All of the feature flags for forms have been confirmed to be `true`, so the feature flags themselves are ready to be removed on the front-end side.

### Feature flags for removal

- `combined_financial_status_report_enhancements` 
- `financial_status_report_streamlined_waiver`
- `financial_status_report_streamlined_waiver_assets`

## Tasks
- [x] Remove the above three feature flags and any usage of them in the front-end (they are all currently `true`)

## Acceptance criteria

- [x] Feature flags have been removed
- [x] Tests still pass

## Testing
- [x] N/A

**Comment by maxx1128** [comment]
I forgot to close this before with the pull request! My apologies, I'm closing it now.
