### ISSUE TITLE
[FSR] Feature Flag Removal (vets-api)

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-team#86012]
## Description

This ticket is a ticket opened after the [Feature Flag Cleanup Discovery.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81813) All of the feature flags for forms have been confirmed to be `true`, so the feature flags themselves are ready to be removed on the backend side.

### Feature flags for removal

- `combined_financial_status_report_enhancements` 
- `financial_status_report_streamlined_waiver`
- `financial_status_report_streamlined_waiver_assets`

## Tasks
- [ ] Remove all above feature flags from `config/features.yml`.

## Acceptance criteria

- [ ] Feature flags have been removed
- [ ] Tests still pass

## Testing
- [x] N/A

**Comment by maxx1128** [comment]
End of sprint update: I have two pull requests open that are awaiting review. Once they're merged, then this ticket will be good to close.
