### ISSUE TITLE
Appoint a Rep Digital Submit - User Test - Analysis & Reporting

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#86033]
## Issue Description
User testing of Appoint a Representative Digital Submission flow.

## Tasks
- [ ] Analyze interview findings
- [ ] Create report
- [ ] Create ideation workshop based on findings
- [ ] Review report with key stakeholders
- [ ] Conduct ideation workshop for recommendations
- [ ] Create share-out and filing tickets

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
@oddball-lindsay do we have an epic for Appoint V2 I should be tagging?

**Comment by oddball-lindsay** [comment]
There is now 😅 added it to this ticket!

**Comment by jfinnerty13** [comment]
Out for team review due noon Thursday
https://docs.google.com/presentation/d/1L0nHduYVfuG2WHHsa7RXGrg3GR_dXg7VjFseOHRSt74/edit?usp=sharing
