### ISSUE TITLE
Include a form download link in the Appoint email confirmation

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86051]
## Background
We are planning to send an email confirmation after a user completes the Appoint a Representative experience.  This will confirm form completion on VA.gov and reiterate next steps.

We've also considered including a download link, but this will require additional work to ensure the link remains secure.

## Tasks
- [ ] Setup another table to save data for forms that are no longer in progress
- [ ] Replace user data if the user completes a new form
- [ ] New endpoint to access the new table
- [ ] New frontend page and URL on VA.gov for downloading outside of Save in Progress
- [ ] URL should only be available for a limited amount of time (i.e. 72 hours) then time out
- [ ] Authenticated users must login to access the URL
- [ ] Unauthenticated users must verify their identity (Security recommends 2-factor auth to the phone number they provided)

## Acceptance Criteria
- [ ] We have created a download URL that can only be accessed via a secure manner, and is only available for a specific amoutn of time before the content behind the URL times out.
