### ISSUE TITLE
[Cleanup] Internal cleanup of "BUTLER, PA" Part 1 System and facility pages in Devshop [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8606]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing, review, initial Accessibility scan with AXE-Coconut _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Chrome AXE-Coconut](https://chrome.google.com/webstore/detail/axe-coconut-web-accessibi/iobddmbdndbbbfjopjdgadphaoihpojp/related?hl=en)
[Chrome AXE](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd/related?hl=en-US)

## Tasks
_Complete validation and Clean up of Part 1:_
- [ ] Test lines 1 through 11
- [ ] Test lines 28 through 46
Sites included in Butler are: 
- [ ] Butler VA Medical Center
- [ ] Sergeant Joseph George Kusick Community Living Center and Domiciliary
- [ ] Armstrong County VA Clinic
- [ ] Clarion County Va Clinic
- [ ] Cranberry Township VA Clinic
- [ ] Lawrence College VA Clinic
- [ ] Michael A. Marzano Dept. of VA Outpatient Clinic
- * Document completion of changes using spreadsheet listed above_
- [ ] Inform PM that changes have been made and sight can be reloaded in Devshop.

## Acceptance Criteria
* All pages must have been documented in Spreadsheet
* AXE testing must be screenshot and loaded into Spreadsheet for Accessibility and 508 teams
*  PM is informed that changes have been made and sight can be reloaded in Devshop.
