### ISSUE TITLE
Change Intro page, sub-text, and form title for 686

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#8607]
[Original list of changes or additions from design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0420.md)

## Description
This is one part of the content updates that need to be made to the 686 before launch.

## Tasks
1. Change page subtext ( text under the title ) to match mockups. On the Introduction page we need to update the subtext near the top to be `Equal to VA Form 21-686c (Application Request to Add And/Or Remove Dependents) and/or Equal to VA Form 21-674 (Request for Approval of School Attendance)` as shown in the mockups. Update: Completed on intro page, but not on any other page.

~~1. Change the form title. Throughout the form we need to change the form title to be `Add or remove dependents from your VA benefits` as shown in the mockups.~~ Update: Completed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12496)

~~1. Change the `signed in` text on the introduction page to be `Note: Since you’re signed in to your account, we can prefill part of your application based on your account details. You can also save your form in progress and come back later to finish filling it out.` as shown in the mockups.~~ Update: Completed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12496)

~~1. Change green button text on Introduction page to be `Add or remove a dependent` as shown in the mockups.~~ Update: Completed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12496)

## Acceptance Criteria
- [x] **Introduction** and **Confirmation** page sub-text has been updated 
- [x] The form title has been updated
- [x] The 'signed-in' text on the Introduction page has been updated
- [x] The green button on the Introduction page has been updated
