### ISSUE TITLE
[CST] Update headers for 686c/674 claims to "Request to add or remove a dependent"

### ISSUE THREAD

**Issue by ajialeilani** [department-of-veterans-affairs/va.gov-team#86080]
## Value Proposition

As a veteran with a 686c or a 674 dependency claim, I want the title for these claims in CST to give me a clear idea of what these claims are, so that I can more easily identify them in the UI and navigate to the correct claim details to check my status. 

## Background

We're keeping the plain language version of the title for the 686c/674 online tool, "Request to add or remove a dependent" and would like to update how these claims are labeled in the CST. Now that claimTypeCode has been added to our index response, we should be able to make this update without going through Lighthouse. 

https://design.va.gov/content-style-guide/title-tags

Current state: 

![Screenshot 2024-07-29 090719](https://github.com/user-attachments/assets/8b5d20c1-723d-4e71-a53d-0f3ec816fdab)
![Screenshot 2024-07-29 090629](https://github.com/user-attachments/assets/ec5a571c-6c2d-4eef-8c96-e839d07950ec)

## Eng Notes
-    The title that we pass into `ClaimCard.jsx` from `ClaimsListItem.jsx` will need to be updated to change the text from "Claim for dependency" to "Request to add or remove a dependent". Will want to update the method getTitle() so that there is an if statement accounting for the given claim type
- The `claimTitle()` logic will need to be updated on `ClaimDetailLayout.jsx` so that there is an if statement accounting for the given claim type

## Open Questions
- What is/are the claim type(s) that we want to add this logic for?
- Should we be updating the breadcrumbs for the cst tabs?
- Should we be updating the browser tab title for the cst tabs?
- Are there other references to the claim type code in CST that we need to account for?

## Tasks
- find the EP codes and claim labels for these dependency requests

## Acceptance Criteria

- [ ] On the claim listing page, change the claim card title from "Claim for dependency" to "Request to add or remove a dependent" for all 686c and 674 claims in CST. 
- [ ] On the claim detail page, change the title from "Your dependency claim" to "Your request to add or remove a dependent"
- [ ] The breadcrumb should be changed to "Status of your request to add or remove a dependent" for each tab (files, status, overview) and doc request pages
- [ ] The browser tab should be "{tab name} of {date} your request to add or remove a dependent | Veterans Affairs"

**Comment by ajialeilani** [comment]
Hi @jacobworrell just wanted to make sure this made it into the right pipeline.

**Comment by jacobworrell** [comment]
@ajialeilani acknowledging receipt of this ticket, we'll take a look and get it into a future sprint. Thanks!

**Comment by pmclaren19** [comment]
Reviewed and added some updates to tasks, questions and ac during eng refinement.

**Comment by jerekshoe** [comment]
@jacobworrell do you know what EP codes are associated with 686c and 674 claims?

**Comment by LouisFettet** [comment]
So it doesn't get lost, we're talking through the claim type / end-product codes in [this Slack thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1724258841098039). Will post an update here once we reach a conclusion.

In the meantime, I've made some adjustments to the front-end locally:
* claim list page card title: <img width="659" alt="Screenshot 2024-08-22 at 9 10 39 AM" src="https://github.com/user-attachments/assets/9ec2d3b5-048b-493e-bb24-6075ed28c47f">
* claim detail page heading and breadcrumb: <img width="697" alt="Screenshot 2024-08-22 at 9 11 09 AM" src="https://github.com/user-attachments/assets/f1753f8e-c0d7-4149-99ab-8ad115c6f80b">
* claim detail page document title (browser tab title): <img width="697" alt="Screenshot 2024-08-22 at 9 34 28 AM" src="https://github.com/user-attachments/assets/f7e7f4eb-f59d-45d3-b656-546b78d46c36">

A couple of notes on the above:
* I didn't take screenshots of the title variations for the different tabs on the detail page, but they follow the same rules as normal. On the "Files" tab the title changes to `Files for...` and on the "Overview" tab the title changes to `Overview of...` (both for the breadcrumb and the document title).
* The document title (browser tab title) provided in the issue description used `Sentence case` but I used `Title Case`, adhering to the [guidance for Title tags](https://design.va.gov/content-style-guide/title-tags).

@ajialeilani I have a couple of clarifying questions for you to make sure I'm handling all of this correctly:
1. The new title is a bit too long to be fully displayed in the breadcrumbs and the document title (browser tab title). This is only an "issue" visually; screen readers will still read out the full title. Should we try to shorten the title a bit so that it fits in these areas, or do you think it's fine as-is?
2. The document title (browser tab title) reads a little off to me with the placement/inclusion of "Your" in the following: `Status of August 21, 2024 Your Request to Add or Remove a Dependent | Veterans Affairs`. I feel like it would be cleaner as one of the following, but I'd like your input on whether we should change it or leave it as-is:
    1. Move the "Your": `Status of Your August 21, 2024 Request to Add or Remove a Dependent | Veterans Affairs`
    2. Drop the "Your": `Status of August 21, 2024 Request to Add or Remove a Dependent | Veterans Affairs`
    
cc @jerekshoe @jacobworrell

**Comment by ajialeilani** [comment]
@LouisFettet I'm seeing the appeal of "dependency claim" now. I'm leaning towards dropping the "Your" if we're trying to find more room. Let me see if we we can come up with a shorter alternative. Thank you for your work so far!

**Comment by LouisFettet** [comment]
Hi @ajialeilani, just checking in; any updates on the breadcrumb and browser tab titles?

**Comment by ajialeilani** [comment]
Hi @LouisFettet —I think we may be waiting to review a video of a call with your team from Thursday morning mentioned [here](https://dsva.slack.com/archives/C0547Q0K0LF/p1724348127636419?thread_ts=1724340296.824269&cid=C0547Q0K0LF). 

We've discussed "Request for dependent updates” which would keep with our plain language goals, move the word "dependent" up, and shorten the title. I would want to run a change like that past CAIA before committing, though.

**Comment by LouisFettet** [comment]
Thanks @ajialeilani! Sounds like we'll leave the breadcrumbs as-is (using the "request to add or remove a dependent" language), but should we move or drop the "Your" in the browser tab title?

**Comment by ajialeilani** [comment]
Yes, let's drop it. Thanks, @LouisFettet!
