### ISSUE TITLE
FSR Expenses Checklist Component 

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#86084]
## Issue Description
The current [CheckList.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/85229172d4c1295580a47738082bbdabeadb34a1/src/applications/financial-status-report/components/shared/CheckList.jsx) needs to be refactored to use the [USWDS Checkbox Group](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox-group--default) component.

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Update expenses checklist to reference refactored code

## Acceptance Criteria
- [x] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression

**Comment by amponce** [comment]
On stage we're still showing the old expenses checklist which didn't prompt the new value field after selecting an expense like rent or mortgage. I thought I missed something but realized that that page was replaced and when I was checking locally I didn't see it so I never tested those checkboxes. The PR is up and FE is reviewing now
