### ISSUE TITLE
Mock Auth documentation & Postman

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#86085]
## Description
https://dsva.slack.com/archives/CSFV4QTKN/p1718381127150169

## Tasks
- [x] add mock auth support to SiS postman collection
- [x] [update postman documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/postman.md#mocked-authentication)
- [x] [update mock auth documentation to link to postman](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Mocked%20Authentication#mocked-authentication-with-va-identity-postman)
