### ISSUE TITLE
Introduction page subway map updates

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#8609]
[Original list of changes or additions from design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/text-revisions/686-punch-list-0420.md)

These are some of the content updates that need to be made for the form 686 before launch

## Tasks

1. Change header to `Follow the steps below to apply to add or remove a dependent` as shown in the mockups.

2. Update `Prepare` section to new text as shown in the [mockups](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design).

3. Update `Apply` section to new test as shown in the [mockups](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)

4. Update `VA review` section to `We process applications in the order we receive them. We may contact you if we have questions or need more information.` as shown in mockups.

5. Update `Decision` section to `You’ll get a notice in the mail once we’ve processed your claim.` as shown in the mockups.

6. Change the `<h4>` tag for `Follow the steps below...` to be an `<h2>` with the styling of an `<h4>` for 508 so that the heading levels go down by 1

## Acceptance Criteria

- [x] The Introduction page header has been updated
- [x] The `Prepare`, `Apply`, `VA Review`, and `Decision` sections on the Introduction page have been updated
- [ ] The `<h4>` on the Introduction page has been updated
