### ISSUE TITLE
Profile: Sprint 39 (6.19.2024-7.2.2024)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#86102]
## Sprint Links
[Previous Sprint ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83787) 
[Next Sprint ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86914)

## PTO
- Tom OOO week of 6/16 

## Sprint Goals
- For Asiisii to feel more comfortable deploying code at the VA 
- Make progress on anything ch33 related so we're ready for UAT next sprint.

# Tickets

### PM
- [ ]  #85845

### FE 
- [x] ~#86293~ kicking because of Ch33 needs

### FE
- [x] #32963
- [x] #63112

## New Team Member Onboarding 
- [x] #85544
- [ ] #86992

### FE 
- [x]  ~#74837~ kicking this out in favor of ch33 toggle work 

## Ch33 
- [x] #86840
- [ ] ~#87185 (added after sprint start likely to roll~ - swapping w/ #86337)
- [x] #86337
- [ ] #87214 (added after sprint start likely to roll)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/79907 (added 7/1 planned to roll) 

### BE
- [ ] https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/15

### BE 
- [ ] #87184
