### ISSUE TITLE
[Cleanup} Internal cleanup for "ERIE, PA" Part 1 System and facility pages in Devshop [VAMC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8610]
## User Story or Problem Statement
As a Veteran Web user, I must have full accessibility a compliance to my web applications and tools, so I can use the VAMC system pages in any GUI, UE, including mobile and reader environments.

## Goal
_Perform initial page testing, review, initial Accessibility scan with AXE-Coconut _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Chrome AXE-Coconut](https://chrome.google.com/webstore/detail/axe-coconut-web-accessibi/iobddmbdndbbbfjopjdgadphaoihpojp/related?hl=en)
[Chrome AXE](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd/related?hl=en-US)

## Tasks
_Complete validation of issues and clean up of Erie Part 1:_
- [ ] Testing Line 1 through 11
- [ ] Testing Line 28 through 46
* Lines are highlighted in Green
*Sites included in Erie:
- [ ] Erie Medical Center
- [ ] Ashtabula County VA Clinic
- [ ] Crawford County VA Clinic
- [ ] McKean County Va Clinic
- [ ] Venango County VA Clinic
- [ ] Warren County VA Clinic
- * Document completion of changes using spreadsheet listed above_
- [ ] Inform PM that changes have been made and sight can be reloaded in Devshop.

## Acceptance Criteria
* All pages must have been documented in Spreadsheet
* AXE testing must be screenshot and loaded into Spreadsheet for Accessibility and 508 teams
*  PM is informed that changes have been made and sight can be reloaded in Devshop.
