### ISSUE TITLE
Refinement: Correct Taxonomy for API Call Events

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#86155]
### Description
Not all of the "API Call" events in UA use the `api_call` dataLayer event name and were not transitioned into GA4 as `api_call` events. Using UA to identify all historical "API Call" events, we'll correct the mislabelling. 

_Note that some link click events had been grouped into the "API Call" events. Since these are not api server calls interactions, these will not be relabeled as `api_call`._

---

### Tasks
- [ ] identify all "API Call" events using UA
- [ ] update GA4 event tracking as needed 

### Acceptance Criteria
- [ ] GA4 api_call events align to historic "API Call" events in UA (_with previously noted exception_)

**Comment by johnny-jesensky-adhoc** [comment]
This ticket is going to be carried over into next sprint. Some of our final implementation tasks and custom events took longer than expected to implement, so this is a carry over.

FYI @jestutt, @jwoodman5, @davidconlon, @raywangoctova

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt  -- I'm currently tracking around > 150 different api_call events in GA4 -- can you validate if there are still some from the UA set-up that we'll need to relabel/reclassify?

![image](https://github.com/user-attachments/assets/a8d6a1b9-eaa1-4de3-99ea-54d0b9f5966d)
