### ISSUE TITLE
Transition GTM Triggered Events to GA4

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#86163]
### Description

Not all tracking events are triggered by dataLayer event pushes (e.g. web/form components and custom events). Others are solely created in GTM, mostly using HTML and CSS as triggers. These events need to be transitioned.  

---

### Tasks

- [ ] review UA and GTM to identify these events
- [ ] implement the identified events for GA4

### Acceptance Criteria

- [ ] identified events have been implemented for GA4

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- were these all transitioned, or do need to create a follow-up ticket to validate/confirm all have been moved over?
