### ISSUE TITLE
Style all "New" and "Coming soon" tags same shade of blue

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86176]
### User story

As a Veteran, I want tags throughout MHV portal to be the same color.

### Notes
- Kaitlin noticed during launch party on MHV Home

Florence commented below:
Correct color info for both tags:

- vads-color-primary
- #005ea2
- uswds-system-color-blue-60v
- $color-vads-color-primary

Possible tasks:
- Check tag colors across portal
- Verify correct color for tags

## Acceptance criteria

- UXers verify the correct color name
- "coming soon" and "new" tags are same color of blue throughout portal (either we fix or ticket if wrong on non-Cartographer pages)
- QA review

```[tasklist]
### Tasks
- [x] UXers verify the correct color name
- [ ] Devs identify "coming soon" and "new" tags that will be changed by us and those that require a ticket for other teams
- [x] Devs make appropriate changes
```

**Comment by fmccaf1** [comment]
Correct color info for both tags:

vads-color-primary
#005ea2
uswds-system-color-blue-60v
$color-vads-color-primary

**Comment by radavis** [comment]
Instances of `usa-label` in vets-website:

- src/applications/claims-status -- not part of the MHV portal
- src/applications/personalization/profile -- component only shown in development
- src/applications/mhv-landing-page -- addressed with department-of-veterans-affairs#30959
- src/applications/vaos -- tag/label for Canceled appointments
- src/applications/verify-your-enrollment -- tag/label for date benefits were last Updated

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the "New" and "Coming soon" tags are the same shade of blue: #005ea2 (0, 94, 162 - RGB)
