### ISSUE TITLE
R&D roadmap

### ISSUE THREAD

**Issue by djones2113** [department-of-veterans-affairs/va.gov-team#86180]
- [x] Develop initial roadmap for team feedback
- [x] Incorporate feedback into main product roadmap
- [x] Develop a separate R&D focused roadmap with additional detail
- [x] Solicit feedback on R&D focused roadmap
- [x] Further define sprint-level activities for the roadmap

**Comment by djones2113** [comment]
The R&D focused roadmap lives on the [product planning Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=0-1718667719481).
