### ISSUE TITLE
Find a Rep: VSO = Veteran Service Organization

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86184]
## Background
We have some lingering pieces of content where VSO is referencing the old Veteran Service Officer term.  All of these need to be updated to Veteran Service Organization.

Specific changes are **bolded** in the tasks below.

## Tasks
- [x] Update first sentence in VSO definition to "An accredited Veterans Service **Organization** (VSO) representative can help..."
- [x] Update third paragraph in VSO definition to "Accredited VSO representatives work for **organizations** like the American Legion..."
- [ ] Update empty state reference to "Accredited Veterans Service **Organization** (VSO)"
--------
- [x] Bonus point for empty state -- add in a space between the "named" and the user input reference

<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekp2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0305d658eaadc07971665a6153bbe3f5b17ebee1/image.png" alt="image.png" />

## Acceptance Criteria
- [x] The word "Officer" should no longer be on the Find a Rep page.

**Comment by oddball-lindsay** [comment]
@cosu419 the changes are looking accurate on Find a Rep!  But I realized I gave you bad directions for that third task :(

I had you update the empty state from "Accredited Veteran Service Officer (VSO)" to "Accredited Veteran Service Organization (VSO)":
<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46adf57e0ed813df01695ec325e9e1145192625e/image.png" alt="image.png" />

...but actually this should match the radio button and be "Accredited VSO representative" -- so sorry!
<img width="753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzZxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64b1d355024d57e5c793f471b89ff024671dc170/image.png" alt="image.png" />

**Comment by oddball-lindsay** [comment]
Looks good @cosu419 !

<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65ab29ae1fd6a9a04ad7c4bb18a20a1f5ac49a43/image.png" alt="image.png" />
