### ISSUE TITLE
Remove outdated View your VA payment history page from live site

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#8618]
## User Story or Problem Statement

As a Veteran, I need to be able to get to the correct page so I can view my payment history. Currently we are pointing to two pages with similar URLs:
- /view-your-va-payment-history/
- /va-payment-history/

/va-payment-history/ is the correct URL

## Goal

Delete - /view-your-va-payment-history/ from Drupal so it is removed from the live site.

## Objectives or Key Results this is meant to further
- Single source of truth for viewing your payment history
---
## Tasks
- [x] Delete node ID 297 from Drupal (/view-your-va-payment-history/ )
- [x] Check that no pages link to outdated page and if so, update to correct page

## Acceptance Criteria
- [x] Page no longer showing on live site
- [x] All links point to correct page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@kevwalsh Is there a way to tell if there are any other live pages pointing to node ID  297? We want to delete this page but avoid broken links. Or is the only way to delete it and then get the alerts?

**Comment by RLHecht** [comment]
This page has been archived. Moving to validate. Will also confirm there are no other pages linking to this page. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
The outdated page is no longer showing on the live site. Closing ticket.
