### ISSUE TITLE
Test Merge of UA + GA4 Data on a Dataset

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#86198]
### Description
Before we schedule the appending of GA4 data on top of existing UA datasets, we want to try this out on a few specific reports and datasets, before scheduling the append on our live reports.

This task will be to test out the process, and ensure our findings work.

---

### Tasks

- [x] Identify dataset that we will be testing the append on.
- [x] Append GA4 data on top of an existing UA dataset.
- [x] Review the dataset, and test on existing test report -- QC Test
- [x] Document findings, or lessons learned, and incorporate into other scheduled appends

### Acceptance Criteria

- [x] Test dataset exists that has a blend of UA data _and_ GA4 data
- [x] Findings will be documented if any issues, or problems emerge

**Comment by johnny-jesensky-adhoc** [comment]
@dorseypa1 -- tested the append of UA and GA4 data on a test dataset, [GA4 BQ Standard Content Engagement
](https://va-gov.domo.com/datasources/26af1919-d97a-401f-a5b4-86cb020d3095/details/data/table).

Initial QC of the report [VA.gov Content KPIs - QC Test](https://va-gov.domo.com/page/1383636480) performed. Will continue to monitor.

Moving this to _**Done**_.
