### ISSUE TITLE
Content Update on Download VA Letters - reported to PW team

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8619]
Content support for static public website pages

Andrea Schneider noticed that on this page https://www.va.gov/records/download-va-letters/  there was content about adding an effective date. 
She remembered that EVSS made this change about a year ago, so that the date automatically shows on letters now.
Because of that change, this content is no longer needed. 

**Task**
- [x] Remove the outdated content from the Download VA Letters page - remove the effective date content

**Acceptance Criteria**
- [x] On visiting the Download VA Letters page, there is no content about adding an effective date
- [x] No other changes to the page are made

Steps needed to complete this work now:
- [x] Review ask (Beth P.)
- [x] If changes needed- Anne to do

**Comment by AnneHurley** [comment]
@RLHecht  - This is ready for your review/publish. After that, Beth or I can send Andrea the URL. thanks!

http://preview-prod.vfs.va.gov/preview?nodeId=471
@bethpottsVADEPO  @stephorkandatx FYSA

**Comment by RLHecht** [comment]
@AnneHurley this was reviewed and looks OK. I also updated the phone number on the bottom to put in the aria label as well as linked the TTY number. Publishing page and moving to validate. FYSA @bethpotts

**Comment by AnneHurley** [comment]
@RLHecht  Thanks and great re the phone number. @bethpottsVADEPO  Would you like to send Andrea the stakeholder the URL to say we are done? I'm happy to do that as well just LMK.

**Comment by AnneHurley** [comment]
Slack sent to @AZSchneider, @bethpottsVADEPO , @stephorkandatx  This is now live. Closing issue.
