### ISSUE TITLE
Design | Appointment Reminders PHI/PII | designs showing the opt in permission for PII/PHI for appointment reminders

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#86208]
## Background 
We need to incorporate an additional set of checkboxes into the notification settings for users to opt in or out of receiving PHI/PII in their appointment reminders. 

- Additional context for the work can be found on the epic #58797 
- [VA Profile Notification Settings in Figma](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=1-12888&t=SKN5JeTzkLNrBRqP-0)
- [Desktop and Mobile with MHV Notifications](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=0-629&t=SKN5JeTzkLNrBRqP-0)
- in this ticket we're noodling on what the design should be fore the content ticket #85845
- [content/ia thread ](https://dsva.slack.com/archives/C01K37HRUAH/p1718224154276019)
- [caia mural for PHI/PII messages](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717604095056/bd084ed3c2489d65a706390af98124b7057be182?wid=0-1718307687319&sender=uaa72d11015d3f7c704a64191) 

Work was begun before a11y and technical constraints were known. Artifacts in Figma are there for discussion and illustration.

See comments for these constraints. 

There are not existing VADS patterns for this kind of interaction, so work will need to be done to create a bespoke pattern. 

Working Figma file on page titled ["Desktop - PHI/PII Notifications After Design Intent"](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=736-2743&node-type=canvas&t=ZEjNwZ1dobCi0fZS-0)

#### Comment from previous designer 
> I know I won't be working on this, but fwiw, I think it will be most clear to people if the PII/PHI option is a secondary step or something layered on top of the overall permission.  E.g. first they indicate they want to be notified and then we ask if they want to have PII included.
> _Originally posted by @andaleliz in https://github.com/department-of-veterans-affairs/va.gov-team/issues/58797#issuecomment-2161424266_

## Tasks 
- [x] tbd by design 
- [x] document a11y constraints
- [x] document technical constraints 
- [x] Review internally with FE 
- [x] Connect AE FE/ MHV BE to discuss functionality
- [ ] review w/PO and PM 
- [x] [create FE ticket once the design work is completed ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92656)
- [x] think through if we need usability testing (convo w caia folks etc) <checking this off because design intent advised we do need to go through usability testing[TC]

## Acceptance Criteria 
- [x] we have [updated mocks for desktop](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=736-2743&node-type=canvas&t=ZEjNwZ1dobCi0fZS-0) and [mobile](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=769-17487&node-type=canvas&t=nT0y3dZ1Ey4VmaTX-0)
- [x] [FE ticket for completing the work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92656) 

~OR~

- ~[ ] Summarize the conclusion/learnings for potential shareout to stakeholders~
- ~[ ] Document in GH what the conclusions are including meeting notes, possible designs, POCs, Etc.~
- ~[ ] put this back into the backlog for future work~

**Comment by ACParker89** [comment]
@twoangstroms - do you have an update on this ticket? Is it in progress?

**Comment by twoangstroms** [comment]
Not in progress yet but will this week. Revamping ILER based on actual info from stakeholders has been a lot.

**Comment by ACParker89** [comment]
This story is a sprint priority, so that development can begin in the next sprint. If you'd like we can set up a call and chat through the tasks tomorrow. Can we have this completed by Wednesday before planning so that they can jump into it?

**Comment by twoangstroms** [comment]
@ACParker89 @mtcA6 Does this ticket include deleting the text "Manage your health care email notifications on My HealtheVet" [in this design](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=251-8520&t=SKN5JeTzkLNrBRqP-0)? Because it seems that adding the ability to manage notifications here obviates managing them on MHV, but I don't know the plans and needs of the stakeholders regarding this.

**Comment by mtcA6** [comment]
Take a look at the MHV tabs and not the current/prod designs 

![image](https://github.com/user-attachments/assets/970c674c-39d0-4744-a7ea-5fea24edeabb)

**Comment by twoangstroms** [comment]
Thanks. I couldn't tell which were in play/last updated.

**Comment by mtcA6** [comment]
@twoangstroms we keep the prod ones up to date/ in step w production since we link to those from our documentation for use cases. 

The other in flight items that are behind feature flags are in the other tabs. We migrate that work to the prod tabs when we launch the features.

**Comment by twoangstroms** [comment]
Ready for review by @mtcA6 and @ACParker89 Link: https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=484-9987&m=dev

**Comment by twoangstroms** [comment]
Review, iteration, and talking with CAIA will have this ticket rolling to next sprint

**Comment by mtcA6** [comment]
cool, thanks for these! I'd say toss that out there on #85845 and get Laura to opine.

**Comment by ACParker89** [comment]
Agree with Travis on getting them to give some feedback! Thank you Dan!

**Comment by twoangstroms** [comment]
Documenting a11y constraints:

- VADS does not allow disabled state in cdsadsaheckboxes nor in radio buttons 
- do not use suds

**Comment by twoangstroms** [comment]
Documenting technical constraints:

- label headers are determined by the back end and cannot be created [as here](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=572-12347&t=tLEG8tBT0vKVpGFp-0)
- checkboxes/radio buttons are determined by the back end so the front end has to match number and action (though not in text/naming)

**Comment by ACParker89** [comment]
@tpharrison @asiisii @mtcA6 - planning to discuss this Wednesday in order to discuss BE capabilities to tie in with Design possibilities

**Comment by mtcA6** [comment]
Trav, Dan, and Autumn Atchley to meet, Travis to schedule a meeting next week.

@clantosswett, I'll set this for maybe Tuesday hopefully we can get an answer back on the timeline from MHV. I think there's still value in us meeting even if the urgency does taper off.

**Comment by mtcA6** [comment]
Response regarding MHV's priority on this:

Chante said:
>@ Travis Cahill as expected, the [VA.gov](http://va.gov/) appointments team has not deprioritized the PHI/PII included notifications work. I told them we can let VA profile know but that they might want/need to regroup with MHV folks to get on the same page. I also told them some kind of timeline, even if it is notional (i.e. FY25Q1) would be helpful for us and VA profile. In the meantime, I'll let Mike and Barbie know that the [VA.gov](http://va.gov/) appointments team still has this work as a priority and that we will likely need to have another conversation with the various groups to determine when this work is needed by.

there is a call scheduled for Monday, that will focus mainly on the timeline not the functionality.

**Comment by mtcA6** [comment]
- The collab cycle ticket is here: #91788 - the recording is linked there 
- Here's the design feedback: #92020

**Comment by mtcA6** [comment]
@twoangstroms here's the accessibility feedback - https://github.com/department-of-veterans-affairs/va.gov-team/issues/92376

**Comment by twoangstroms** [comment]
Updated in [Desktop - PHI/PII Notifications After Design Intent](https://www.figma.com/design/e6JEtrwZCInKk9SjZktx2T/Profile---Notification-Settings?node-id=736-2743&node-type=canvas&t=ZEjNwZ1dobCi0fZS-0)

**Comment by mtcA6** [comment]
@asiisii could you create the FE ticket that's needed to actually implement the design Dan shared? I need you to be deeply critical of the designs here and think about what you genuinely need when you go to build this on the FE. If we need more info from design we should make sure we get that now

@twoangstroms some thoughts: 
1. can we combine/reduce the number of working tabs related to PHI/PII in the figma file?
2. do you have mobile designs, I've heard stated before we're mobile first and should consider mobile ahead of desktop.
3. in you coordinating with @mattmarino-adhoc on best practices, I think when we get to a finalized design it would be great to break down the design with notes and details similar to what [was done here](https://www.figma.com/design/05k2PTmuDVgBj2HnzUZayg/Profile---Account-Security?node-id=124-1858&node-type=canvas&t=wPD23GdE7Jp4pumQ-0)
4. once you've got mobile designs, I think this ticket is good to close - if we need to rework wording then we can create a new ticket for a future sprint but I think we won't really be able to make more progress here until we get data from VA Profile (PoC Autumn) 


Related to PHI/PII work but not related to the AC of this ticket, [we've expressed the desire to submit the final design through the experimental design process](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91755), I think it would be informative to look at a prior example here because I don't know that our designs are going to meet the level of scrutiny that process requires. The below example was approved and we're waiting for it to be built by the design system. 
- [save in progress / loading button](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2792)
- [figma for save in progress /loading button pattern](https://www.figma.com/design/Byfu9NRKXCtXN3DuMYguKI/Authenticated-Experience-Pattern-Library?node-id=513-2&node-type=canvas&t=evcSwuvf1rHYDFKO-0)

**Comment by twoangstroms** [comment]
@mtcA6 Hear you on mobile. Hoping to get some info from the DS team (or whether I should connect with the Mobile (big M) team) to clear up some potential issues in this pattern. 

By "working tabs", do you mean what Figma calls Pages (I know, all the proprietary terms are confusing; Matt and I hope to disambiguate)?

**Comment by mtcA6** [comment]
We already connected with Mobile and [Ryan Thurlwell gave a thorough signoff here for us to move forward](https://dsva.slack.com/archives/C018V2JCWRJ/p1725486673229769?thread_ts=1725458182.734139&cid=C018V2JCWRJ)

**Comment by twoangstroms** [comment]
Thanks for the link. I was thinking someone who is working on the web product would be better for signing off on a pattern for the web, but we can refer back to Ryan.

**Comment by twoangstroms** [comment]
Dan Brady (Design System) gave the nod.

**Comment by asiisii** [comment]
Here's the FE ticket for this enhancement 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/92656

cc: @mtcA6 @twoangstroms
