### ISSUE TITLE
HLR: Manage react widget for launch

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#86215]
## Description
The Higher-Level Review (HLR) online form has been updated.

We need to create, publish, and remove a react widget on the HLR static page to support the incremental launch of the new online form.

## Resources
- Static page: [Higher-Level Reviews](https://www.va.gov/decision-reviews/higher-level-review/)

## Tasks
- [ ] LS: Confirm launch date and engineer with product team
- [ ] KF: Draft react widget (with support from AP, as needed)
- [ ] MZ: Copyedit react widget (with support from engineer)
- [ ] MZ: Publish react widget (when incremental launch begins)
- [ ] KF: Remove react widget (when incremental launch ends) and update content on page
- [ ] MZ: Copyedit and publish page

## Criteria
- [ ] React widget has been published on page for incremental launch
- [ ] React widget has been removed and page has been published after incremental launch

**Comment by katherine-fung** [comment]
Closing this ticket as I reached out to @Mottie to confirm we don't need to make any static page updates for this launch. We didn't do any work on this ticket so it doesn't need to be entered on the metrics sheet. 

cc @strelichl @aprocik1 @NaomiPMC
