### ISSUE TITLE
Create Public-Facing Tip of the Sprint Archive

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#86211]
We decided to create a public-facing Tip of the Sprint Archive. Once created, we could link to it instead of old Slack posts. We could also include it in our orientation takeaway document (which will be on another ticket). 

### TASKS

- [x] Copy ToTs Archive and move to private space
- [x] Remove all Internal-facing content
- [x] Re-format all the posts to have headings that are more useful to non-PCT users
- [x] Create a new Public-facing intro
- [x] Make the document more scannable 
- [x] Move edit doc back to "How we work" space
- [x] Remove "Copy of" from the title

### Acceptance Criteria

- [x] Public-Facing Archive now exists in our "How we work" space

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance Criteria met. Public facing doc can be found here: https://vfs.atlassian.net/wiki/spaces/CIT/pages/3239444481/TIP+OF+THE+SPRINT+-+Archive Ticket ready to close.

**Comment by jknipes** [comment]
Closing per the comments above
