### ISSUE TITLE
Consolidate Contact Center Guides & Videos

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8621]
## User Story or Problem Statement
As a VFS product manager, I need to know where my previous product guide/video is located so I can easily update it when I update my features.

## Goal
Consolidate all available product guides and product videos into a single, searchable location.

## Tasks
- [ ] Add all the available product guides to one place
- [ ] Add all the available product training videos to one place
- [ ] Share out new location to VFS teams

## Acceptance Criteria
- [x] Users can easily search for their product guides
- [x] Users can easily search for the product training videos

**Comment by clantosswett** [comment]
Created two folders in the contact center folder on github. I have uploaded the product guides. I will be adding product videos today. 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/contact-center/vfs-product-guides

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/contact-center/vfs-product-videos

**Comment by clantosswett** [comment]
Finished uploading the demo videos we have (we don't have a lot). I also created a folder for our monthly reports so that teams can find those on github as well as in slack:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/contact-center/monthly-reports
