### ISSUE TITLE
Argo RCA1 certificates 

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#86224]
## Issue Description
This was work that Platform Product team resources got pulled into, post-Sprint planning, that took a significant amount of time. The work was reviewing and troubleshooting certificate issue when trying to sync multiple applications in Argo. 

There was an error - x509: certificate signed by unknown authority - in Argo that looks like the old RCA1 is still floating around our clusters. It could be that that has finally been put to bed and RCA2 is required to traverse the TIC.

## Tasks
- [X] Work with Kyle/Infra to update certificates 
- [X] Check certificates
- [X] Ensure that applications can sync in Argo.

## Success Metrics
No more application issues when trying to sync in Argo

## Acceptance Criteria
- [X] Certificate is updated
- [X] No more application errors when trying to sync

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
End result/solution was that VA RCA1 vs VA RCA2 CA Certificate
