### ISSUE TITLE
Bump outdated gems

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#86235]
## Issue Description
Here is the current list of outdated gems:

```
aws-sdk-kms (newest 1.85.0, installed 1.83.0)
aws-sdk-sns (newest 1.77.0, installed 1.76.0, requested ~> 1)
bgs_ext (newest 0.22.0 a7fcba0, installed 0.21.3 dc1b693)
ddtrace (newest 1.23.2, installed 1.19.0)
faraday (newest 2.9.2, installed 2.9.0, requested ~> 2.9)
flipper (newest 1.3.0, installed 1.2.2)
flipper-active_record (newest 1.3.0, installed 1.2.2)
flipper-active_support_cache_store (newest 1.3.0, installed 1.2.2)
flipper-ui (newest 1.3.0, installed 1.2.2)
google-protobuf (newest 4.27.1, installed 4.27.0)
hexapdf (newest 0.45.0, installed 0.44.0)
jwt (newest 2.8.2, installed 2.8.1)
lockbox (newest 1.3.3, installed 1.3.0)
mini_magick (newest 4.13.1, installed 4.12.0)
nokogiri (newest 1.16.6, installed 1.16.5)
octokit (newest 9.1.0, installed 8.1.0)
oj (newest 3.16.4, installed 3.16.3)
parallel (newest 1.25.1, installed 1.24.0)
pdf-forms (newest 1.5.1, installed 1.5.0)
prawn (newest 2.5.0, installed 2.4.0)
rack (newest 3.1.3, installed 2.2.9)
rubocop-rspec (newest 3.0.1, installed 2.30.0)
savon (newest 2.15.0, installed 2.12.0)
sidekiq-ent (newest 7.2.4, installed 7.2.2)
timecop (newest 0.9.10, installed 0.9.9)
tzinfo-data (newest 1.2024.1, installed 1.2023.4)
vets_json_schema (newest 22.3.3 d78aabb, installed 22.3.3 274f291)
will_paginate (newest 4.0.1, installed 4.0.0)
```

This ticket will consist of making a pass at each gem, bumping if possible, and spinning of extra tickets if the upgrade requires significant work.

---
## Tasks
- [ ] aws-sdk-kms
- [ ] aws-sdk-sns
- [ ] bgs_ext
- [ ] ddtrace
- [ ] faraday
- [ ] flipper
- [ ] flipper-active_record
- [ ] flipper-active_support_cache_store
- [ ] flipper-ui
- [ ] google-protobuf
- [ ] hexapdf
- [ ] jwt
- [ ] lockbox
- [ ] mini_magick
- [ ] nokogiri
- [ ] octokit
- [ ] oj
- [ ] parallel
- [ ] pdf-forms
- [ ] prawn
- [ ] rack
- [ ] rubocop-rspec
- [ ] savon
- [ ] sidekiq-ent
- [ ] timecop
- [ ] tzinfo-data
- [ ] vets_json_schema
- [ ] will_paginate

## Acceptance Criteria
- [ ] Gems bumped or tickets created

**Comment by ryan-mcneil** [comment]
Updated gem list
