### ISSUE TITLE
Memorials: Review address validation content

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#86234]
## Description
The [pre-need eligibility for burial in a VA cemetery](https://www.va.gov/burials-memorials/pre-need-eligibility/) online form has been updated with a new address validation design. We need to review the content in that design.

## Resources
- [Content source of truth](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EemmigYlPvlMjKFOhMnG4fYBp6nc1aXkC3tOROHcLPJ7ZQ?e=b9Svzh) (SharePoint)
- [New design](https://www.figma.com/design/QIMsAdHJjctTKDM1I34uXV/Medallions---Baseline-Prototype?node-id=4-44933&t=YqhC7djPF0tZdI3u-4) (Figma)

## Tasks
- [x] AP: Review content and develop recommendations
- [x] AP: Share recommendations with product team

## Criteria
- [x] Content recommendations have been shared with the product team

**Comment by aprocik1** [comment]
## Applicant information

### Your mailing address

Country (*Required)
Street address (*Required)
Street address line 2 (*Required)
City (*Required)
State or territory (*Required)
Postal code (*Required)

### Your contact information
Phone number (*Required)
Email address (*Required)

<details>
<summary>Why we ask for this information</summary>
We may need to contact you to ask for more information after your submit your application.
</details>

**Comment by aprocik1** [comment]
# Step 2: Memorial services

## Screen 1: [Figma reference](https://www.figma.com/design/QIMsAdHJjctTKDM1I34uXV/Medallions---Baseline-Prototype?node-id=388-25502&t=3O2v0xuaolAyC7Vr-4)

### Cemetery mailing address
Country (*Required)
Street address (*Required)
Street address line 2
City (*Required)
State or territory (*Required)
Postal code (*Required)

Cemetery contact information
Phone number (*Required)
Email address (*Required)

**Note:** 

Why we ask for this information

**Comment by aprocik1** [comment]
# Step 4: Medallion information

## Screen 1: [Figma reference](https://www.figma.com/design/QIMsAdHJjctTKDM1I34uXV/Medallions---Baseline-Prototype?node-id=388-23168&t=3O2v0xuaolAyC7Vr-4)

### Medallion delivery address

The VA will ship a medallion to the address listed. 

Country (*Required)
Street address (*Required)
Street address line 2
City (*Required)
State or territory (*Required)
Postal code (*Required)

### Contact details
Phone number (*Required)
Email address (*Required)

## Screen 2: [Figma reference](https://www.figma.com/design/QIMsAdHJjctTKDM1I34uXV/Medallions---Baseline-Prototype?node-id=388-25602&t=3O2v0xuaolAyC7Vr-4)

### Edit mailing address
Tell us which of these addresses you'd like to use. (*Required)

- [ ] Address you entered: 120 Fix Street, Charleston, South Carolina, 13579
- [ ] Suggested address: 
124 Fix St, Charleston, South Carolina, 13579

[Buttons] Back, Continue

**Comment by aprocik1** [comment]
Update: I returned to this to remove dynamic content and headers based on the user story. The product team found in their user research for the pre-need online form that users prefer to use these static descriptors: preparer, applicant, sponsor, recipient. The dynamic content and headers that used "your" based on the user story confused users.
