### ISSUE TITLE
Top Down Modeling for Incoming Cases 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#86237]
## Issue Description
As a Veteran Support Customer Success Manager, I need to tally historical data of incoming cases so I can calculate the percentage of cases that can be reasonably closed by the Support team on a per sprint basis.  

--
## Tasks
- [x] Analyze historical data for case closure per quarter
- [x] Determine individual closed cases performance per quarter 
- [x] Calculate average incoming cases per sprint
- [x] Create target case closure amount per Support team member per sprint

## Acceptance Criteria

 - [x] **Scenario: Analyze historical data for case closure per quarter**
  - Given the historical data of incoming cases is available
  - When the data is analyzed for case closure per quarter
  - Then the percentage of cases that can be reasonably closed by the Support team on a per sprint basis should be calculated
- [x] **Scenario: Determine individual closed cases performance per quarter**
  - Given the historical data of incoming cases is available
  - When the data is analyzed for individual closed cases performance per quarter
  - Then the average performance of each case should be determined
- [x] **Scenario: Calculate average incoming cases per sprint**
  - Given the historical data of incoming cases is available
  - When the data is analyzed to calculate the average incoming cases per sprint
  - Then the average number of cases per sprint should be calculated
- [x] **Scenario: Create target case closure amount per Support team member per sprint**
  - Given the historical data of incoming cases and the average performance of each case
  - When the data is used to create a target case closure amount per Support team member per sprint
  - Then the target case closure amount should be calculated for each team member per sprint
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Get with Sarifa early next week to extract data and complete first 3 tasks.

**Comment by ATMiddleton** [comment]
Kimberley. Sarifa and Anita will collaborate to glean the required data. W/o 6/24/24

**Comment by Kimberley2023-CSM** [comment]
Meeting was held.  Sarifa will create a report in Salesforce and provide Anita and I with the example.  Information will only be from Salesforce as of now due to being in discovery phase for AVA data.

**Comment by Kimberley2023-CSM** [comment]
Next steps are for Anita and Kimberley to calculate the target.

**Comment by ATMiddleton** [comment]
Veteran Support Salesforce reporting for Q1/Q2 2024
[New_VAHotline Tier 2_Q1_Q2.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a19689b1dd6bfe8304480b428908e7822a14f29/New_VAHotline%20Tier%202_Q1_Q2.xlsx)

**Comment by ATMiddleton** [comment]
The report requires additional review.  Will create additional ticket to address

**Comment by ATMiddleton** [comment]
We have learned that the Salesforce data is incomplete.   Further investigation is required to validate the accuracy of the data.

<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3VmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc753da5fb38f62777501a42de5826b8204087e1/image.png" alt="image.png" />

**Comment by ATMiddleton** [comment]
Team will meet Wednesday, July 3rd to confirm targets.

**Comment by ATMiddleton** [comment]
Revised closed cases target 
<img width="567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f282f15c44f9cbbe6bcd41a3269e603e6e239fc/image.png" alt="image.png" />
