### ISSUE TITLE
Update Contact Center Training Video Documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8623]
## User Story or Problem Statement
As a VFS PM, I need to understand how to make a product training video for contact centers so that I can complete the contact center portion of the collaboration cycle.

## Goal
Create product training video how-to on Github.

## Tasks
- [x] Write up how-to
- [ ] QA guide
- [x] Update collab cycle-facing documentation with the updated link

## Acceptance Criteria
- [ ] VFS teams can easily understand how to create contact center training videos for their products

**Comment by Kimberley2019** [comment]
@clantosswett can you review the documentation below?

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/training-video-process.md

**Comment by joanneesteban** [comment]
@Kimberley2019 

Thanks for doing this!

Can you edit the format of it to include:
- Overview or summary (this can be the first sentence that's already in the document)
- Audience

Some other edits:
- Can you specify product team as "VFS product team" or "VFS application team"?
- Can you limit the recording to Zoom calls so that we can grab the captions? (unless, @clantosswett, you don't think this is necessary?)
- Double check the word, "should" on the document

**Comment by Kimberley2019** [comment]
Thanks for the edits @joanneesteban they have now been incorporated.

**Comment by joanneesteban** [comment]
Made some additional edits & created a PR for your review, @Kimberley2019 @clantosswett . 

Also, when the product video documentation is complete, please update the [Contact Center Review documentation of the Collab Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md#prepare-for-contact-center-review) with the video documentation link.

**Comment by Kimberley2019** [comment]
PR complete.  Changes incorporated, updated the collab cycle.
