### ISSUE TITLE
Onboarding Training Schedule 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#86243]
## Issue Description
As a Veteran Support Customer Success Manager, I need to document the order of trainings for new Veteran Support members so that the Veteran Support team has clarity and consistency for the sequence of training activities improving efficiency. 
---
## Tasks
- [x] Identify all required training modules
- [x] Determine order of importance 
- [x] Calculate time required to complete training session
- [x] Document in Onboarding summary documentation 

## Acceptance Criteria
 - [x] **Scenario: Identify all required training modules**
  - Given the Onboarding Training Schedule issue is created
  - When the Veteran Support team identifies all required training modules for new members
  - Then a list of training modules should be documented in the Onboarding summary documentation
- [x] **Scenario: Determine order of importance**
  - Given the Onboarding Training Schedule issue is created
  - When the Veteran Support team determines the order of importance for training modules
  - Then the priority sequence should be documented in the Onboarding summary documentation
- [x] **Scenario: Calculate time required to complete training session**
  - Given the Onboarding Training Schedule issue is created
  - When the Veteran Support team calculates the time required for each training module
  - Then the estimated time for each training should be documented in the Onboarding summary documentation
- [x] **Scenario: Document in Onboarding summary documentation**
  - Given the Onboarding Training Schedule issue is created
  - When the Veteran Support team documents the order of trainings and their respective time requirements in the Onboarding summary documentation
  - Then the finalized onboarding training schedule should be available for reference and consistency
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Training Schedule added to https://docs.google.com/document/d/1w69RkZtBAlUUkT5dPF7Lx2k8I11mMEuVlGDfFapow2g/edit 

Week 1 - Getting settled - company onboarding - internal meetings/Formal introductions/review newsletters
"Week 2 - Introduction to Veteran Support team - Overall 
-Who We Are - Veteran Support team breakdown 
-What We Do 
-Why We Do What We Do
-How We Do What We Do
How Veteran Support fits into the VA.gov big picture "
"Week 3 - confirm access for all applications 
- introduce to confluence and visually to Salesforce/AskVA/SNOW
- shadow existing team members - 1 hour each day "
Week 4 - Complete all training modules 
Week 5 - dive in

**Comment by ATMiddleton** [comment]
Added @startlow for visibility

**Comment by ATMiddleton** [comment]
Complete
