### ISSUE TITLE
Copy of Toxic Exposure - EVSS to LH `transform`  service: empty `treatment['startDate']` causes errors

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#86251]
## Story
The question was posed:
> should a treatment value (nested in the 526 form at form['form526']['form526']['treatments']) always have a startDate?
🤔

Sending a `null/nil` value for `startDate` from vets-website to vets-api for an item in the `treatments` list should be allowed, but the `EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform#transform` method is blowing up.

This [line of code here](https://github.com/department-of-veterans-affairs/vets-api/blob/f3b600a43613deb08f2dd1b6008f012831529164/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L174) is the culprit
Why?
When parsing a `nil` date to be in a certain format, ruby no likey. 💎😡

Lighthouse's submit endpoint(s) allow for this attribute to be nullable - need to check if it is also allowed to be an empty string. (i have a feeling it won't)

## Question
Should we look for other places where optional fields are not parsing correctly in our LH transformer? 🤔

## Tasks
- [ ] enhance `EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform#transform` to not blow up when sending a `nil` empty string `startDate`
- [ ] enhance `EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform` unit tests to account for `nil` or empty string `startDate`

## Acceptance criteria
With the `disability_526_toxic_exposure` feature flag on:
- [ ] submitting a claim with null or empty `treatments` objects from vets-website does not blow up 🚫💥

references:
- [Slack thread](https://dsva.slack.com/archives/C053U7BUT27/p1717015993433529)
- Lighthouse docs (POST /veterans/{veteranId}/526): https://developer.va.gov/explore/api/benefits-claims/docs?version=current
- https://github.com/department-of-veterans-affairs/vets-api/blob/f3b600a43613deb08f2dd1b6008f012831529164/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb#L174

<img width="991" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bac557b8927b6bdac9cb82b8f3a88d5718e7839/image.png" alt="image.png" />

**Comment by sethdarragile6** [comment]
Duplicated, decided not to use it. Closing.
