### ISSUE TITLE
[Documents to Lighthouse] Add configuration for argo

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#86253]
### Background
We need to add the settings for vets-api for the Lighthouse Benefits Documents Service to argo. Currently all envs are using the settings defined in `settings.yml` in the vets-api codebase, but they should all have their own sets fo settings in argo

## Tasks
- [x] Add the settings for dev and staging and create a PR
- [x] Add the settings for prod and create a PR

## Acceptance Criteria
- [x] Settings are added for all envs for the Lighthouse Benefits Documents Service
