### ISSUE TITLE
Toxic Exposure 1.1: Manual e2e tests of IPF to VBMS

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#86257]
As a Veteran, I want the experience of continuing my IPF to be free of errors and bugs so that I can submit my claim without issue.
Testing scenario:
Continuing an IPF without errors or bugs
  - Given a Veteran is continuing their IPF in the Toxic Exposure 1.1 system
  - When the Veteran navigates through the pages and submits their claim
  - Then the alerts, pages, and submission data should be displayed/saved as designed
 
## Acceptance Criteria
 - [x] Testing for the different Veteran states of Toxic Exposure including In Progress Forms
 - [x] Update TestRail with IPF use case

## Tasks
how to test Toxic Exposure 1.1:
- turn off all TE flags
- create a new form
- ensure formData does not have a startedFormVersion attribute
- with the user having an IPF, turn on the disability_526_toxic_exposure_ipf flag
- return to the IPF
- ensure formData does have a startedFormVersion attribute as 2019
- Create a TestRail outlining the way to get the user in this state

Checklist
- [x]  run through several permutations of the data state, i.e. only 15A checked YES, 15A checked NO, only data for herbicide sent, etc.
- [x]  "Maximal" view - test all the variations of the possible TE dates end to end shown on the PDF
- [x]  "Minimal" - Checkbox on TE "I'm not claiming any conditions related to toxic exposure" is checked

**Comment by christinec-fftc** [comment]
Updates made to test rail
- Added claim type page to Standard claim, BDD, no TE, and FDC, Edge Cases test cases 
- BDD flow incorrectly had pages such as retirement pay, separation pay, pow, supporting evidence, housing situation, terminally ill, fdc, disability follow up pages. Pages removed.
- Added service treatment page to BDD flow
- Created consistency throughout steps and shared steps with 'Steps' on the left side and 'Results' on the right (some had steps in the results)
- Housing situation and Terminally ill questions were in the wrong chapter for multiple test cases. Moved them to their current locations in ch 1.
- Herbicide and Additional Exposures pages: Updated screenshots with new error message for invalid character error on other location field

Created new wiki page for sharing generated pdf's: [Generated PDFs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/tests/Generated%20PDFs.md)

**Comment by christinec-fftc** [comment]
Test case updates, documentation and test results reviewed with the team today. Also shared with OCTO and VBA.
