### ISSUE TITLE
Flipper UI access for [Napoleon Kernessant]

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#86261]
### Your Name

Napoleon Kernessant

### Your GitHub handle (Flipper UI access is managed through GitHub)

@gcioNapoleon

### Team, Role, and Company of the target individual

govcio-vfep-codereviewers

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need access before we'll be creating several new pages / forms in the near future.

**Comment by bdech** [comment]
Confirmed in Atlas
E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67036)

**Comment by bdech** [comment]
@GcioNapoleon You've been granted Flipper UI access to `lower` environments.
