### ISSUE TITLE
Tip of The Sprint [S4]:  

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#86269]
## Issue Description

---
## Tasks
- [ ] Draft Tip of The Sprint
- [ ] Review draft with PC Team
- [ ] Schedule ToTS for _____ in #platform-content channel in Slack

## Acceptance Criteria
- [ ] Tip of The Sprint posted
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
There was no Tip of the Sprint for S4, closing this ticket
