### ISSUE TITLE
Edit: Health Quest Service

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#86271]
## Issue Description

- Health Quest Service and Authorization Design Doc and many other documents in Confluence use personal names. This is not appropriate on the Platform website because team members roles from time to time, making documents go quickly out of date.

- Additionally, there should be no headers without further text.

## Tasks
- [x] Review style guide guidelines regarding personal names
### CONTENT TEAM:
- [x] Review and edit [Health Quest Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831341/Health+Quest+Service) re: inclusion of names
- [ ] Edit empty headers at bottom of page and the text underneath in [Health Quest Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831341/Health+Quest+Service) 
(Known External Dependencies, Outage Status and Maintenance Windows, Service Level Agreement, and Escalation Procedure) 
- [ ] Under **Known External Dependencies** heading, say "There are no known external dependencies" if appropriate 
- [ ] Fix grammar in the text under **Troubleshooting**
- [ ] Remove the name **Laurence Guild** and replace with an alternative slack channel or team to contact for help
- [ ] **Product Team** review page content for accuracy
- [ ] **Content Team** review page for launch blockers
- [ ] Prepare page for deployment

## Acceptance Criteria
- [x] This page been updated and is ready to be published
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Tasks have been refined and this ticket requires input from Platform Product Team, to be executed in a future sprint. Content Team is pausing our work on this and moving it to the **Backlog**

**Comment by jennb33** [comment]
Changed the Content team's story points to "5" to better align with the Platform Product team's metric

**Comment by jknipes** [comment]
Sprint automation added this to Jul 4th sprint incorrectly. We are removing sprint dates and keeping in backlog pending availability from Product team

**Comment by jennb33** [comment]
We have this scheduled for Sprint 6 (7/18-7/31/2024)
@jknipes @laucon 
Thank you!

**Comment by jennb33** [comment]
7/17 update: we will be reviewing the code in order to determine the owners of the blank content at the bottom of the page (Task step 3)

**Comment by BSmolensky** [comment]
This ticket seems like it should either be one ticket in a long list of tickets, or it should be folded into one much larger ticket. Why? Well, because each and every page under [External Service Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) has major content issues. Nearly all of them list names. Most have empty headers, formatting errors, and/or jumbled text. This entire section could use an Audit. 
For quick reference, I have included links to every page in this section below: 

1. [Active Directory Federation Services](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1888485505/Active+Directory+Federation+Services) 
2. [Appeals/Caseflow](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887502340/Appeals+Caseflow) 
3. [ArcGIS.com](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814279/ArcGIS.com) 
4. [Benefits Gateway Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887272987/Benefits+Gateway+Service) 
5. [CARMA](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781482/CARMA)
6. [(Deprecated) Central Mail API](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798523/Deprecated+Central+Mail+API) -- Doesn't have name issue but Should this page even be on the PW?
7. [Certificate of Eligibility (COE)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2363555845/Certificate+of+Eligibility+COE)
8. [CMS-SSOi](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887600699/CMS-SSOi) - No names here either, but this page has no intro and no info. It just points the user to a diff page. Consider revising. 
9. [Coronavirus Chatbot](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814308/Coronavirus+Chatbot) - This page names names...but is this chatbot still valid?
10. [DS Logon ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912543/DS+Logon)- No names, but email address in contacts section needs to be checked. 
11. [Debts](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887764481/Debts)
12. [EVSS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240213/EVSS) - No names listed, but pages states that EVSS is being migrated to Lighthouse. Has that been completed?
13. [EWIS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305740/EWIS) 
14. [Enrollment Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601919/Enrollment+Service)
15. [GSA API](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885667529/GSA+API)
16. [GIDS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912583/GIDS) - This pages is strange and should be looked at.
17. [ID.me](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912590/ID.me)
18. [Lighthouse SSOi Oauth](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436803/Lighthouse+SSOi+Oauth)
19. [MDT - Denver Logistics Center](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798533/MDT+-+Denver+Logistics+Center)
20. [Master Person Index (MPI)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847049) -- HURRAY! This page in GREAT SHAPE. Recently updated. Should be used as the standard for the rest of the pages listed here. 
21. [MVI request XML](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567937/MVI+request+XML)
22. [My Healthe Vet](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885667536/My+Healthe+Vet) -- This page has "TODO (additional contacts required)" under contacts. That makes this a DRAFT and an incomplete page. 
23. [Pre-Needs Burial (EOAS)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305747/Pre-Needs+Burial+EOAS)
24. [SSOe OAuth: Token Introspect Service and Secure Token Service (STS)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887698956/SSOe+OAuth+Token+Introspect+Service+and+Secure+Token+Service+STS)
25. [SSOe](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436810/SSOe) - Page has a notice from 2020 about "Currently in beta" 
26. [Search.gov](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887043657/Search.gov)
27. [TIMS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798540/TIMS)
28. [VANotify](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885634900/VANotify)
29. [VBS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2120319089/VBS)
30. [VHA Access to Care](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240236/VHA+Access+to+Care)
31. [VONAPP](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240243/VONAPP)
32. [Template](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567914/Template) - This template seems to be the source of nearly all the issues listed here. 
33. [Health Quest Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831341/Health+Quest+Service)
34. [Integration Hub (iHub)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305754/Integration+Hub+iHub)
35. [VR&E CMS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885602009/VR+E+CMS)
36. [VA Profile](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2807693782/VA+Profile)

**Comment by jknipes** [comment]
@BSmolensky this ticket has now been added to the Q3 2024 Platform Content Team Tech Debt epic.
We will create additional tickets for the epic to address this issues found on each page in the External Service Integrations section.

**Comment by BSmolensky** [comment]
@jknipes - Sounds good.

**Comment by jennb33** [comment]
@jknipes - thank you, I would like to keep all of @BSmolensky's additional tickets as smaller deliverables, and I appreciate you breaking these out! 
@rmtolmach - FYI

**Comment by jennb33** [comment]
7/22 update: a lot of these will be addressed in our Upstream services objective. We will discuss details when we meet on Tuesday. cc: @LindseySaari @rmtolmach

**Comment by jennb33** [comment]
7/24 update: Brian S is reviewing half of this work as well. @rmtolmach will likely work on it on Friday 7/26.

**Comment by BSmolensky** [comment]
According to Adrian Rollett and Stephen Barrs, HQS is no longer in use. 

> ADRIAN: Hey Brian, I don't think the healthquest service is in active use so I'm not sure if it's worth spending time on documenting it. (at)Stephen Barrs do you have any recollection about this?
> STEPHEN: yep that was part of a Questionnaires pilot that failed successfully (it determined that the product work should not continue)

After consulting with @rmtolmach, HQS page should be archived.

**Comment by jknipes** [comment]
@jennb33 shall we leave this ticket to be closed out by your team?

**Comment by jennb33** [comment]
7/25 update: @rjohnson2011  to confirm that there is no traffic to the VetsAPI. Raise any follow-up items to the team so that future work can be scheduled.

**Comment by jknipes** [comment]
FYI @LindseySaari 
> According to Adrian Rollett and Stephen Barrs, HQS is no longer in use.
> 
> > ADRIAN: Hey Brian, I don't think the healthquest service is in active use so I'm not sure if it's worth spending time on documenting it. (at)Stephen Barrs do you have any recollection about this?
> > STEPHEN: yep that was part of a Questionnaires pilot that failed successfully (it determined that the product work should not continue)
> 
> After consulting with @rmtolmach, HQS page should be archived.

**Comment by BSmolensky** [comment]
This ticket has been completed. Moving to **Close**

**Comment by BSmolensky** [comment]
UPDATE: HQS page has been archived.
