### ISSUE TITLE
Prepare the Platform Satisfaction Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#86279]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [x] Consider all feedback and meet with Design Lead to build new survey
- [x] [Prepare Survey in Optimal Workshop](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey)
  - [x] Update w/ the new questions and format
  - [x] Ensure it is a PILOT copy
- [x] Share with PO for feedback
- [x] Recruit 1-2 pilot testers

## Acceptance Criteria
- [x] PILOT survey is created
- [x] Survey is shared w/ PO for sign-off
- [x] Survey is piloted with 1-2 participants
