### ISSUE TITLE
Update Platform Roster from sitewide-CMS GitHub (dupe 1)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#86280]
Duped from Sprint 2 [80748](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/80748) for Sprint 3. Go back to [80748](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/80748) for comments

## Issue Description
Sitewide Web Facilities brought to Product Platform's attention via [Slack](https://dsva.slack.com/archives/CT4GZBM8F/p1712874205738459) the fact that the membership on [this page](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-sitewide-cms) was incorrect for the following reasons: 

1. CMS is now a Platform team, so sitewide-cms is old / incorrect naming
2. Edmund is on CMS team. Other CMS folks are not in this group.
3. Laura is on Sitewide. Other Sitewide folks are not in this group.

Per Erica Washburn, the decision was to add those CMS members to the [Platform roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster) now.

## Tasks
- [x] Deprecate sitewide-cms Github team
- [x] Move those folks from sitewide over to the [Platform Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] Delete entries from Atlas
- [x] Investigate if we are missing something in onboarding/offboarding? It could be that the initial import from the roster spreadsheet was incorrect - inquire with on/off boarding procedures with the support team
- [x] Review Atlas for references to siteside-cms and update accordingly

## Success Metrics
- Jill Adam's request has been satisfied

## Acceptance Criteria
- [x] [Platform roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster) will be updated with CMS team info and correct
- [x] sitewide-cms Github team will be deprecated
- [x] Atlas references to siteside-cms is updated accordingly

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
