### ISSUE TITLE
Set up Confluence space for Q2 2024 Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#86282]
## Purpose
Duplicate any Confluence views from q1
-We'll want it for complete results when the survey closes

Reference: [Old Metrics page](https://vfs.atlassian.net/wiki/spaces/AP/pages/2616164361/Metrics+for+the+Quarterly+Platform+Services+Satisfaction+Survey) | [Newer Metrics page](https://vfs.atlassian.net/wiki/spaces/AP/pages/3077111862/Platform+Satisfaction+Metrics)

## Tasks
- [x] Duplicate previous survey confluence space
- [x] Modify space for new direction allowing for updated questions and format

## Acceptance Criteria
- [x] Q2 space is ready
