### ISSUE TITLE
Populate data in Confluence space for Q2 2024 Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#86289]
## Purpose
Populate the data onto the newly created confluence page

## Tasks
- [x] upload new survey quantitative data after initial spreadsheet is created
- [x] ensure all visualizations are accurate on the [page](https://vfs.atlassian.net/wiki/spaces/AP/pages/3297542216/updated+Platform+Satisfaction+Survey)(s)
- [x] upload qualitative feedback to the [Feedback Repo](https://vfs.atlassian.net/wiki/spaces/SDT/database/3120759313)

## Acceptance Criteria
- [x] Q2 survey recap reflects data received
