### ISSUE TITLE
Synthesize Platform Satisfaction Survey Results

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#86287]
## Purpose
Close out the survey and perform the synthesis of the results

## Tasks
- [x] Download survey data onto [new spreadsheet](https://docs.google.com/spreadsheets/d/1SwvqzdYOpmhz7Zatvf5aSvwS8t7HVte8/edit?usp=sharing&ouid=115483211310637945003&rtpof=true&sd=true) and separate quantitative and qualitative data
- [x] Schedule workshops with stakeholders/SDT for synthesizing as a group 
- [x] Discuss and collaborate with Design Lead
- [x] Synthesize quantitative data
  - [x] Use [this spreadsheet](https://docs.google.com/spreadsheets/d/17t_lCRO54PXfnpseTREZs7ykQUszxZ9pL1lTQUVNuWw/edit?gid=753481210#gid=753481210) for visualizations
- [x] Create mural for qualitative data
- [x] Synthesize qualitative data (SDT group session)
- [x] Ensure any [related documentation](https://vfs.atlassian.net/wiki/spaces/SDT/pages/1445724309/How-to+Launch+the+Platform+Satisfaction+Survey) is current and updated

## Acceptance Criteria
- [x] Results are synthesized
