### ISSUE TITLE
[Discovery] Understanding pension rating and the handling of pension claims within the internal VA processes

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#86296]
## Value Statement
**_As a_** Designer
**_I want to_** understand the pension rating processs and claim steps involved
**_So that_** we can determine how to represent the claims process in the new accordion UI

---
## Background Context

There are many different claim types that exist in CST: [Full list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/appeals-type-list).

Our new understanding is that we can specify which claims will use the new claims process UI (accordion UI) and provide bespoke content based on the claim type. Our goal is to learn more about this claims process so that we can determine the most effective way to represent the claim using the new UI.

### New Feature
- Why are we doing this work?
- [Epic Link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84260)

## Tasks
- [x] _Document claim phase steps_
- [x] _Have an overview understanding of what happens at each step_

## Definition of Done 
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] _Document findings in github [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/research/2024-06-Claim-Phase-Experience-non-disability-claims)_

**Comment by uxgary** [comment]
Completed requirements for this tickets. Links to the deliverables are listed below: 

[Documented findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/2024-06-Claim-Phase-Experience-non-disability-claims/VBA%20SME%20Workshop%20for%20Pension%20claims%20process%20experience.md)
[Mural doc](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718906654073/9f6298e5f0b2a25a06a714c05b129918e2cbc92f?sender=u606d6bea4af40ec4fe659363)
