### ISSUE TITLE
Prepare presentation of Survey Feedback data

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#86291]
## Purpose
Prepare artifacts associated with the synthesis of the survey.  Our goal w/ this updated Survey is to be able to track changes qtr-over-qtr, and make these results easily accessed and absorbed by Leadership and Platform teams.

**Pivot:**  moving to Excel for visualizations, probably letting Domo go as it requires considerable manipulation for seemingly simple needs at times.

## Notes
- Important to relay info in a way that Leadership understands its significance, and hopefully is actionable for them as well when it comes to prioritization.

## Tasks
- [x] Collect Q2 2024 data visualizations
- [x] Create new data visualizations to compare Q2 2024 vs Q1 2024
- [x] Prepare [slide deck](https://docs.google.com/presentation/d/1o8VrL3JzguDvhP_9kmd8vGbGn_DJ1kZ74JKqXQTlEDI/edit#slide=id.p1) to present at Demo Day
- [x] Share with team for feedback
- [x] Process feedback from team
- [x] Make final adjustments to slide deck with any updated visualizations

## Acceptance Criteria
- [x] [Confluence site is updated](https://vfs.atlassian.net/wiki/spaces/AP/pages/2629173255/new+Customer+Satisfaction+Survey+2023+and+beyond) and ready
- [x] [Deck](https://docs.google.com/presentation/d/1YJUk4xaFYiJdYCeZZgkS5wt1Se96pOCJy3Plu-Vd5uo/edit#slide=id.p1) is ready to present for Demo Day
