### ISSUE TITLE
New VFS Team Onboarding next steps: VSA Authenticated Experience

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#863]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [x] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist

- [x] Attend general onboarding meeting
- [x] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/request-access-to-tools.md)
- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/README.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/code-of-conduct.md)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md)
- [x] Review the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to learn the syntax for formatting documents in GitHub
- [x] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [x] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/getting-started.md)
  - [x] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [x] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
- [x] Designers: Attend breakout session
- [x] Engineers: Attend breakout session
- [x] Full team: Attend the Discovery and Logistics Workshop
- [x] Front-end Engineers: Attend deep-dive session
- [x] Back-end Engineers: Attend deep-dive session
- [x] PM and Content Writer(s): Request content intro
- [x] PM and Front-End Engineers: Request analytics intro
- [x] PM: Request 508 intro
- [x] PM, designers, and content writers: Request IA intro
- [x] PM and Engineers: Request load testing, privacy, and security intro
- [x] PM and Engineers: Request ATO intro

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [x] Assign the issues to individual(s) to complete
- [x] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [x] Attach the issues to this Epic

**Comment by rroueche** [comment]
Updated title to differentiate from VSP's epic to actually onboard this team.

**Comment by meganhkelley** [comment]
Added to checklist: `PM, designers, and content writers: Request IA intro` — there is already an in progress ticket for this (#870)

**Comment by Justin-Pickett** [comment]
@1Copenut , Authenticated Experience team has completed all of the above on-boarding checklist items. I am closing this Epic ticket. Thank you.

**Comment by lkoenigsberg** [comment]
@Justin-Pickett , looks like all items on this are done.  Can it be closed now?

**Comment by Justin-Pickett** [comment]
This was closed, i will close it again now. When Brad joined I re-opened it to make sure he completed the necessary items as a new team member.
