### ISSUE TITLE
Test link to headings

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#86301]
**Background**
When we deployed [Screen reader instructions and troubleshooting during research](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-instructions-and-troubleshooting-dur), we found that when we linked to headers, this made it so that the link got linked to an edit-confluence page instead of to a header on the Platform site.

**Additional info**:
Older documents with the link-to-heading feature, like [Accessing Internal Tools (via SOCKS Proxy)](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy), still work correctly. It seems to be new additions of this link-to-heading feature that have bugs.

**Tasks**:

- [x] Test this problem on a new tester document
- [ ] If the problem continues, tell K15t about it and see if they can fix the bug

**Possible alternative idea**:
- [ ] Just use Jill's workaround by linking to headings in the Platform document
(use header from published page)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/86301?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by laucon** [comment]
I feel like Joe did this already. Or, I thought he did.

**Comment by BSmolensky** [comment]
@laucon - I thought so too.

**Comment by taylojill** [comment]
I tested four different scenarios. The results are below. It appears that we have to link to a heading/section of a published page. All links setup in Confluence edit mode opened in edit mode or there was no response. 

1. Link to h2 using "Copy link to heading" on Confluence page. **Result - page opens in Confluence edit mode at top of page, then advances to heading.**

2. Link to h2 using copy/paste of heading URL on Confluence page. **Result - no response to click.**

3. Link to h3 heading using copy/paste of heading URL on Confluence page. **Result - page opens in Confluence edit mode at top of page.**

4. Link to heading using “Copy to clipboard” on Test space web site page. **Result - page linked and opened correctly to test web site page.**

**Comment by taylojill** [comment]
Brian posted [the solution in our Slack channel](https://oddball.slack.com/archives/C02LYB7QXS5/p1721160646481629?thread_ts=1721156790.275349&cid=C02LYB7QXS5).
