### ISSUE TITLE
Investigate the Design Implications of MVI Supplied Info

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8630]
## Story
As a Veteran using the 686, I may be presented with pre-filled info that may or not be correct and I need to understand that info I enter may not change my regular, more permanent record, above and beyond what I fill out in that instance.

## Considerations
 - ✔**Form 526** presents some info that says that is what the VA knows about you, but if you need to make a change, there is a contact number
- **Form 1010** presents some language that says that you can edit what is pre-filled and it will update for your account. **UPDATE:** The 1010ez can be filled in while not signed in, and does not directly establish claims in CORP, this is not our pattern.
- This should also be addressed when the Veteran is presented with address fields.  [Reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md#addresses)
- Micah may have some comments below that will help inform further action.

## Questions
- **Does this need to be implemented before 686 launch?**
_Yes._
- **Do we need remove the 4 MVI fields from Veterans Info?**
_Yes.  We don't want to risk confusion._

## Tasks
- [x] Find out if we need to address this pre-fill issue for the 686 and what is recommended.

## Acceptance Criteria
- [x] A path forward has been established 
- [x] A mockup has been created

**Comment by jason-gcio** [comment]
526 MVI info confirmation
![526-mvi-info](https://user-images.githubusercontent.com/53826255/80760992-c25b0b80-8b07-11ea-8259-1332b86d3fcb.JPG)

1010 MVI messaging
![1010-mvi-info](https://user-images.githubusercontent.com/53826255/80761051-d868cc00-8b07-11ea-87f4-32ded4278501.png)

**Comment by jason-gcio** [comment]
@sporeboy - What other questions do we need to answer?  We can compile them in the description.

**Comment by micahchiang** [comment]
Adding a page to the front of the 686 form _should_ be fairly simple. The 526 does something similar, and we should be able to re-use most of the code found here - https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/526EZ/helpers.jsx#L589. 

We should probably completely remove the field inputs for name, ssn, and dob from the frontend application if we want to avoid any potential side effects caused by allowing a user to enter values different from what is found on their profile. On payload submission, data for name, ssn, and dob should be pulled from current profile application state and added to the data that gets sent to `vets-api`.

**Comment by sporeboy** [comment]
Path of least resistance: screen-for-screen substitution for page 2 of the 686. Replace the Veteran contact info screen with the details screen. Here is the amended XD: https://xd.adobe.com/view/ca825c11-2268-458f-4fec-6aaecfec5b2d-bcb3/
