### ISSUE TITLE
Finalize artifacts for Midpoint Review

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#86339]
## User Story
As a Governance team member, I want to have consistent artifacts to review at each Midpoint Review, so that I know what to expect from the VFS team.

Assignee: @erinrwhite
Peer Reviewer: @allison0034

## Description
While refining the Midpoint Review Process Improvements initiative, Governance team acknowledged that the artifacts requested from VFS teams at Staging Review are pretty loose. Since VFS teams have Midpoint Review's at varying points in their build process, there has never really been any consistency and or requirements with what VFS teams are expected to share. With the introduction of user flows being required at DI, and the SR requirements, both other Governance-owned touchpoints in the Collab Cycle have a bit more structure and expectations are clear. With Midpoint Review, that's not always true.

The purpose of this ticket is to determine specifically which artifacts VFS teams are asked to share at Midpoint Review. This ticket will also determine if any artifacts are required, and/or if any should be contingent upon whether or not the team is doing Veteran research. We may also want to consider if we have different artifacts for teams that skipped DI vs. teams that attended DI, teams that work with CAIA vs. don't work with CAIA, and also sync vs. asynch MPR. 

See [thoughts](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80545#issuecomment-2168222177) from former Governance team member Rebecca re: how we might make recommendations to teams. Assignee is also encouraged to reach out to other Governance team members for their thoughts/opinions.

**Note:** No updates will be made to any VFS-facing guidance per this ticket. Those updates will take place in ticket #85049.

## Tasks
- [ ] Draft recommendations for updated MPR artifact guidance for team discussion

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have determined how artifacts at Midpoint Review are recommended and/or requested

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@allison0034 late breaking update! Feel free to wait til we get back to look at this: [Draft recommendations for MPR artifacts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/86339+-+Updates+to+MPR+artifact+guidance)

**Comment by erinrwhite** [comment]
Planning to discuss with the team at Weekly Initiative meeting on Monday 7/1.

**Comment by erinrwhite** [comment]
Team is reviewing [recommended updates to artifacts for midpoint reviews](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/86339+-+Updates+to+MPR+artifact+guidance#Recommendations-from-the-team), based on our discussion yesterday. Moving to review/QA stage!

**Comment by erinrwhite** [comment]
Team agreed on [new list of required/optional artifacts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/86339+-+Updates+to+MPR+artifact+guidance#Recommendations-from-the-team). All set!
