### ISSUE TITLE
Copy of Delay to Vets-API ELB during deployments (dupe 1)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#86348]
DUPLICATE OF [81916](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81916), because the work is still in progress 

**HIGH PRIORITY**

## Issue Description

As developers and users, 
We need deployments to go smoothly and without significant delay
So that the deployments do not hang up other deployments and delay other users of the Vets-API. 

It was brought to the team's attention back in January ([here](https://dsva.slack.com/archives/CBU0KDSB1/p1706631322227849)) that there have been error responses that occur during the Vets API deployment reported from the Lighthouse team. Some Lighthouse requests call out to Vets API and they see error responses returned for a short window that aligns with the Vets API deployment. While it is expected that the vets-api ELB during deployments, may take up to 180s, we may need to partner with the Lighthouse team to reduce timeouts and failures and try to create a solution that will minimize these. The problem could lie on any where from Kong to the traefik layer in the stack. The potential problem area is depicted in this graph:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1sQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffc0a116b7857cf53ff963991ceedb7f2b29d7be/image%20%2816%29.png" alt="image (16).png" />

## Tasks
- [X] Review current logs (see Slack thread) - Rachal has a list of the current endpoints (could they be put into their own bulkheads?)
- [ ] Troubleshoot what could be causing the timeouts and failures during the daily deployment
- [ ] Document the timeouts and failures, see if there is a common thread
- [ ] Meet with Lighthouse team (Beau Grantham?) to ideate on solutions for minimizing timeouts and failures
- [ ] Test ideas for minimizing timeouts and failures

## Success Metrics
- [ ] That the root cause of the delays and timeouts are identified
- [ ] That a solution is created and successfully tested to limit delays and timeouts during the daily deployment

## Acceptance Criteria
- [ ] That there will be a viable and better solution that has fewer failures and timeouts in the daily deploy for the Vets-API ELB
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
THIS IS AN EXTRA DUPE
