### ISSUE TITLE
Explore rep detail page in Find search results

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86341]
## Background
The representative cards in the Find search results are getting bigger as we add in information around digital submission.  The team has discussed a standalone "detail page" for representatives in the past, it seems like it's time to pick that exploration back up.  Having the detail page will give us more space to highlight things like VSOs that accept digital submission.  It also sets us up for a future state where we could have more info around reps to show.

## Tasks
- [x] Create a rep detail page
- [x] Share with team for feedback
- [x] Adjust based on team's feedback
- [ ] Discuss next steps with the team (midpoint? include in a future user test?  right to dev?)

## Acceptance Criteria
- [ ] Find a Representative returns a list of representatives, and users can click into a representative to see a page that has more information about that rep.

**Comment by mtri** [comment]
Links:

Desktop -
[Search](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=7531%3A184743&node-id=7636-352027&t=q2IVgSh1cJISMFaw-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7636%3A352027&show-proto-sidebar=1)\
[Detail](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=7531%3A184743&node-id=7636-352029&viewport=-25%2C1197%2C0.5&t=c4V5atSLMAEN6LYQ-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7636%3A352027)

Mobile -
[Search](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=7531%3A184743&node-id=7708-375641&t=ORpgjC6TPJVftb91-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7531%3A184744&show-proto-sidebar=1)\
[Detail](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=7531%3A184743&node-id=7708-375232&t=ORpgjC6TPJVftb91-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7531%3A184744&show-proto-sidebar=1)

**Comment by oddball-lindsay** [comment]
Designs are settling, but content is not finalized.

**Comment by mtri** [comment]
Received new content. Adding into design

**Comment by oddball-lindsay** [comment]
Closing this out, will open a new ticket after research to update according to study findings.
