### ISSUE TITLE
Copy of [FE] 10-10EZ - Reg Only MVP: Update UI with new content and alert

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#86346]
## Benefit to the Veteran
By updating the 10-10EZ to reflect the proposed user flow and displaying alerts in a timely and logical manner, we will reduce confusion and burden for the Veteran completing the application.
The Veteran will be better informed about the actions to take to Register for service connected care only, rather than enrolling in the full VA health care benefits package.

## Background
As part of the Reg Only MVP, we want to reorganize the pages for Authenticated and Unauthenticated users, so that they are prompted with the Registration alert early and avoid completing too much of the form before being redirected to call the Health Enrollment center.
We also want to address the alerts on the pages, including Short Form alerts, so that they display appropriately.

### Resources
- [User flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1711487582087/34c3dab41845b8a2ca33afa97e05671703ca8395?sender=uadf1ed7fe7c76f0914967329) (v2 option)
- [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=3025-106249&mode=design&t=dP0IHGHa1YNy0FY8-0)
- [UX github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/Registration/ux)

## Tasks
- [ ] Update the UI to reflect the user flow for Authenticated and Unauthenticated users
- [ ] Update alerts to display in the appropriate pages
- [ ] Review with the team
- [ ] Inform QA/Team when ready to start testing
     - #81104
     - #81115 

## Acceptance Criteria
- UI is updated and ready for QA testing

**Comment by hdjustice** [comment]
@aagosto90 - I see this is a duplicate of #81103 - Do you want to repurpose it?

**Comment by hdjustice** [comment]
closing as duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/81103
