### ISSUE TITLE
DR | Hand off full history of failures for identifying remediation cases

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#86343]
## Value Statement

**_As a_** VA staff member responsible for remediating supplemental claims or board appeals that silently failed
**_I want to_** know the exact nature of each types of transaction failure
**_So that_** I can create a remediation plan to make the Veteran's claim whole. 

---

## Background Context

Follow-up ticket to #81303. This covers handing off the gathered data to CorpDB so that they can confirm which errors led to failures that need remediation

## Acceptance Criteria

- [ ] Data (spreadsheets) are accessible in Sharepoint

## Out of scope

- Any follow-up work that is identified after CorpDB does their investigations

## Open questions

- Who exactly is going to work with the data we're passing on?

## Tasks
- [ ] Identify who we are handing off data to (@amylai-va is working on that currently)
- [ ] Send formatted data
- [ ] Identify any additional steps for remediation (create tickets as needed)

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by shaunburdick** [comment]
[Canavas](https://dsva.slack.com/docs/T03FECE8V/F078FJ5S1ND) created with notes and comments.
Next steps will be working with VBA/BVA/OCTO on messaging and sending data for validation to CorpDB.

**Comment by eileen-coforma** [comment]
Shaun to meet with Michael Hobson today and Wednesday to kick-off remediation efforts.

**Comment by eileen-coforma** [comment]
Had meeting yesterday. Skip trying to filter any out. Difficult to determine if they submit a 0995 if it was a duplicate or not. 
Turn the ICNs in and get Participant ID + SSN. Work with VBA and BVA to craft messaging that will be sent out.

**Comment by eileen-coforma** [comment]
Meeting later in the week with VBA and BVA. Wait and see time.

**Comment by shaunburdick** [comment]
Data has been handed off, meeting with VBA/BVA to discuss responses and any additional data they need.
