### ISSUE TITLE
Domo Data QCs -- Resolve Remaining Outstanding Items

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#86340]
### Description
This ticket is to account for the remaining QC items flagged on our Confluence page found from our priority reports. 
https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/Data+QC+Mapping+Findings+Log

> -  Follow up with Phil for any changes that need to be made to the dataset.
> -  Look for and document differences in variable names, formatting, etc.
> -  Check if event labels, categories, actions -- etc that are used within BeastModes 
> -  If data issue, or discrepancy is found, mark in ticket and notify team.
> -  Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).

### Tasks
The following Domo reports/dashboards need fixing

**Priority Dashboards**
- [ ] [Content dashboard](https://va-gov.domo.com/page/426422632) has high hit counts, may not be resolved however should be investigated
- [x] [Search dashboard](https://va-gov.domo.com/page/1964748112) has no metric error just count errors, investigate
- [x] [Forms Dashboard](https://va-gov.domo.com/page/447193050) hit time is in milliseconds, need to run checks on specific forms

**Wave 1:** 

- [x] [KPIs - Health Care Application](https://va-gov.domo.com/page/980067552) trying to figure out event action, may not be possible
- [x] [VAOS KPIs](https://va-gov.domo.com/page/1769944412) need to check when more data is loaded
- [ ] [Online Caregiver Application - KPIs](https://va-gov.domo.com/page/1905395623)
- [ ] [VA Notify KPIs](https://va-gov.domo.com/page/2040841289)
- [ ] [Profile KPIs](https://va-gov.domo.com/page/1834995012?userId=1539186973)
- [ ] [MyVA KPIs Report](https://va-gov.domo.com/page/1167851935)
- [ ] [VA Chatbot KPIs](https://va-gov.domo.com/page/939649897) Chatbot hits needs updating specifically the resource_link, prev_page_name and next_page_name have errors. Chatbot sessions is missing seconds_engaged and login_status
- [ ]  [Monthly VA.gov Summary ](https://va-gov.domo.com/page/681633878) waiting on claims and forms loads to finalize QC, test once loaded
- [ ]  [All VA.gov Summary](https://va-gov.domo.com/page/460669845) re QC myVA API request by status once updated, My VA events by day event action is not functional

**Wave 2:**

- [ ] [Combined Debt Portal KPIs](https://va-gov.domo.com/page/1976847942) event metrics still have issues, needs to be looked at further
- [ ] [KPIs - Authenticated Experience - Profile 2.0](https://va-gov.domo.com/page/492918243)
- [ ] [Site-wide Homepage-Engagement KPIs](https://va-gov.domo.com/page/80919003) cards are functional however some metrics are off, noted in Domo QC artifact

### Acceptance Criteria

- [x] First round of QCs have been completed for the all of the above Domo dashboards in Priority Dashboards.
- [x] Second round of QCs have been completed for the all of the above Domo dashboards in Wave 1b.
- [x] Second round of QCs have been completed for the all of the above Domo dashboards in Wave 2.

---

**Comment by Blivaditis** [comment]
Updated the QC actions we need to take, added notes for specific errors we need to look at. Additionally all metric discrepancies are documented in our [Domo record](https://docs.google.com/spreadsheets/d/1oaoXivzL854woEIUzgsPReoKW55Spz2p4S5WI_u_QHQ/edit#gid=1044752152).

**Comment by Blivaditis** [comment]
@johnny-jesensky-adhoc maybe we update this to an 8 since it has been a majority of mine and Christines work this week.

**Comment by ChristineYoungZA** [comment]
Final metric counts need to be verified for various datasets. Any major discrepancies will be flagged in QC spreadsheet.

**Comment by johnny-jesensky-adhoc** [comment]
@Blivaditis, @ChristineYoungZA  -- Note -- we've done a few passes on the QC, but still want to do another pass/comb through to ensure we have trusted data for all of our datasets. That work will be monitored in the below ticket that is queued up for next sprint. 

Moving this to _**Done**_ to reflect the work done on these QCs in this sprint.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/87447 -- Domo Monitoring & QC Clean-Up
