### ISSUE TITLE
[CST] write tests for index.unit.spec.js functions

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#86359]
## Background Context
The following functions do not have test coverage and should have test coverage
- submitFiles()
- submitFilesLighthouse()

## Outcome, Success Measure, KPI(S), and Tracking Link
- Test coverage for `index.unit.spec.js` is improved so everything is 80% or more when running `yarn test:coverage-app claims-status`
Current Coverage:
- Statements 58.97%
- Branches 46.83%
- Functions 71.21%
- Lines 59.16%

## Tasks
- [ ] Write tests for submitFiles()
- [ ] Write tests for submitFilesLighthouse()

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Test coverage is above 80% for `index.unit.spec.js`
