### ISSUE TITLE
Remove commented code from LoC count in Dangerbot

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#86369]
## Issue Description
A VFS team member [brought up](https://dsva.slack.com/archives/C0460N83Y9G/p1718392085562669) concerns about the LoC check. It counts comments, which discourages developers from leaving comments in their code–if they are close to the limit, comments are the first to go.  

## Tasks
- [ ] Edit the [Dangerfile](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Dangerfile) to exclude comments in the code. 
- [ ] Also in the Dangerfile, edit any relevant messages to reflect the change. 

## Success Metrics
Ruby comments don't count against the LoC count. 

## Acceptance Criteria
- [ ] PR is reviewed, tested, and validated
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by wayne-weibel** [comment]
https://danger.systems/guides/troubleshooting
https://github.com/danger/danger/issues/382
