### ISSUE TITLE
Claimant Contact Information - Mailing Address

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86382]
## Issue Description

The Claimant Contact Information - Mailing Address page will be available to:
1. Non-Veteran users ONLY
2. Authenticated users who do not have all required information (phone, email and mailing address) on file 
3. Unauthenticated users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is **authenticated**, there will be mentions of Save-In-Progress.  
      1. If the auth user has **some of the information** we need, show the **unauthenticated design** and **prefill** any text inputs when possible
      2. If the auth user has **none of the information** we need, show the **unauthenticated design** with empty text inputs
   2. If the user is **unauthenticated**, show the **unauthenticated design** with empty text inputs
   3. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 12: Claimant's Mailing Address (number and street, apt/unit number, city, state, country code, zip code)
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 13: Claimant's Mailing Address (number and street, apt/unit number, city, state, country code, zip code)

**URL**: `/claimant-contact-mailing`

**Previous path**: `/claimant-contact-phone-email` 

**Next paths**: `/veteran-personal-information`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Unauth" Designs (Input fields)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145489&t=Px0Ccnsof1SBP3NU-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=455%3A148692&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145489&t=Px0Ccnsof1SBP3NU-4)

<details><summary>Screenshots</summary>

<img width="205" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd04xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be7e22a91fde989b059f9d25515505faeb6eb09f/image.png" alt="image.png" />

<img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0oxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fd5bc4196fb1a8c374579984c069427dfb6b189/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Claimant Contact Information - Mailing Address page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Claimant Contact Information - Mailing Address page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
8/8 update: part of an active PR with CI checks that need to be addressed.

**Comment by cosu419** [comment]
8/12 update: CI checks passing, PR pending review

**Comment by cosu419** [comment]
This is ready for review @mtri

**Comment by mtri** [comment]
Looks good!

**Comment by mtri** [comment]
Sorry, I commented on the wrong issue, still have to review

**Comment by mtri** [comment]
I don't seem to be able to get past this screen which is showing on the unauthenticated experience.

<img width="803" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzliQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4087bfa6b4b76150fd8fb4024d74c8d94f2aec33/Screenshot%202024-08-14%20at%205.06.34%20PM.png" alt="Screenshot 2024-08-14 at 5.06.34 PM.png" />

**Comment by cosu419** [comment]
Path to this page was being blocked for unauthenticated users, fixed in above PR.

**Comment by cosu419** [comment]
Should be good to go @mtri

**Comment by mtri** [comment]
The [Veteran mailing address design](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80628&t=s0nxQjzK9bWEFgbC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1) was linked instead of the [Your mailing address design](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80616&t=s0nxQjzK9bWEFgbC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1).

Your mailing address content should be used here.

The differences are minor:
• "Veteran’s mailing address" should be "Your mailing address"
• Copy appears before the form input "We'll send any important information about your form to this address."

Already implemented difference:
• Checkbox content is "I live on a United States military base outside of the U.S." as opposed to "The Veteran lives on a United States military base outside of the U.S."

Other than that, looks good!

**Comment by oddball-lindsay** [comment]
Thanks for catching that @mtri and apologies @cosu419 for the misdirect!

**Comment by oddball-lindsay** [comment]
Peeked in Staging and the only thing lingering is the checkbox copy.  The content in Staging should be updated to match [Figma](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80616&t=s0nxQjzK9bWEFgbC-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1) and the [Design System](https://design.va.gov/patterns/ask-users-for/addresses).
> I live on a United States military base outside of the U.S.


<img width="456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFd1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9499ec689ff237a408dcf72b452391ab8465d9eb/image.png" alt="image.png" />

**Comment by cosu419** [comment]
Thanks @oddball-lindsay - that piece is removed in the second PR linked here which is pending approval.

**Comment by oddball-lindsay** [comment]
Thanks @cosu419! I just noticed that comment from @mtri :).

If we decide to keep the checkbox copy as-is for the Veteran Mailing Address I think it's fine to carry that over here too for Claimant Mailing Address.  In which case you can disregard my comment and close this out!
