### ISSUE TITLE
Claimant Contact Information - Phone, Email

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86381]
## Issue Description

The Claimant Contact Information - Phone, Email page will be available to:
1. Non-Veteran users ONLY
2. Authenticated users who do not have all required information (phone, email and mailing address) on file 
3. Unauthenticated users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is **authenticated**, there will be mentions of Save-In-Progress.  
      1. If the auth user has **some of the information** we need, show the **unauthenticated design** and **prefill** any text inputs when possible
      2. If the auth user has **none of the information** we need, show the **unauthenticated design** with empty text inputs
   2. If the user is **unauthenticated**, show the **unauthenticated design** with empty text inputs
   3. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 13: Claimant's Telephone Number (xxx-xxx-xxxx)
   - Field 14: Claimant's Email Address
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 14: Claimant's Telephone Number (xxx-xxx-xxxx)
   - Field 15: Claimant's Email Address

**URL**: `/claimant-contact-phone-email`

**Previous path**: `/claimant-personal-information` 

**Next paths**: `/claimant-contact-mailing`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Unauth" Designs (Input fields)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145714&t=Px0Ccnsof1SBP3NU-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=455%3A148692&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145714&t=Px0Ccnsof1SBP3NU-4)

<details><summary>Screenshots</summary>

<img width="276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzkwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d549323739355f7709809d51b2da82e38233a6f2/image.png" alt="image.png" />

<img width="972" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0IxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2295924850a5238299d78e3b992b6814aed83e88/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Claimant Contact Information - Phone, Email page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Claimant Contact Information - Phone, Email page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
This is ready for review @mtri, thanks.

**Comment by mtri** [comment]
Looks good!

**Comment by mtri** [comment]
The [Veteran mailing address design](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80628&t=0FJF8OgfcXnAsPX3-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1) was linked instead of the [Your mailing address design](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80616&viewport=7233%2C-1532%2C0.5&t=nPyRc2oxWL2Q0H3D-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1).

Your mailing address content should be used here.

The differences are minor:
• "Veteran’s mailing address" should be "Your mailing address"
• Copy appears before the form input "We'll send any important information about your form to this address."

Already implemented difference:
• Checkbox content is "I live on a United States military base outside of the U.S." as opposed to "The Veteran lives on a United States military base outside of the U.S."

Other than that, looks good!
