### ISSUE TITLE
Claimant Contact Information (Prefill Pattern)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86380]
## Issue Description

The Claimant Contact Information page will be available to:
1. Non-Veteran users ONLY
2. Authenticated users with all required information on file (phone, email and mailing address)
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 12: Claimant's Mailing Address (number and street, apt/unit number, city, state, country code, zip code)
   - Field 13: Claimant's Telephone Number (xxx-xxx-xxxx)
   - Field 14: Claimant's Email Address
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 13: Claimant's Mailing Address (number and street, apt/unit number, city, state, country code, zip code)
   - Field 14: Claimant's Telephone Number (xxx-xxx-xxxx)
   - Field 15: Claimant's Email Address

**URL**: `/claimant-contact`

**Previous path**: `/claimant-personal-information` 

**Next paths**: `/veteran-personal-information`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Auth" Designs (Prefill)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-134676&t=Px0Ccnsof1SBP3NU-0&scaling=scale-down&content-scaling=fixed&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-134676&t=Px0Ccnsof1SBP3NU-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153448&t=Px0Ccnsof1SBP3NU-4)

<details><summary>Screenshots</summary>

<img width="214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3QwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d0a2bed6437b5aba33ecaeec5394a1c81a2a184/image.png" alt="image.png" />

<img width="903" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3gwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47055f3a0f7a965bb5b404b63c817c38f646c7d7/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Claimant Contact Information page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Claimant Contact Information page has been implemented, with the specs outlined above.

**Comment by oddball-lindsay** [comment]
PR was experiencing some CI issues, re-running checks and if that doesn't work will investigate further.

**Comment by oddball-lindsay** [comment]
Small update caught in demo -- update "Home Number" to "Primary Number"

**Comment by cosu419** [comment]
8/12 update: Passing "primary" is not an option for the platform utility function. 

[Slack thread](https://dsva.slack.com/archives/C05L6HSJLHM/p1723477199186409)

**Comment by oddball-lindsay** [comment]
Pending work for this screen:
- Lean on "mobile" and "home" number labels, already in VADS
- Surface both "mobile" and "home" in prefill, if both exist in the pattern

**Comment by cosu419** [comment]
Inspecting the redux state, `user.profile` info is populating with profile data of the test user, but `formData.veteran` (used for prefill) is blank. Will need to learn where `formData.veteran` is supposed to hydrate from and why it isn't happening here. Maybe an issue with the test user setup?

**Comment by oddball-lindsay** [comment]
Updated the Epic association so this is no longer part of "MVP" but part of "v1.1" where we add on the prefill pattern.  @cosu419 thanks for the note on where we're leaving off.  Ready to put this back into the Product Backlog?

**Comment by oddball-lindsay** [comment]
Prefill patterns have changed, this ticket is no longer relevant
