### ISSUE TITLE
Edit: "Adding a new feature" page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#86403]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/86403?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by BSmolensky** [comment]
Upon Further Review: this ticket has been recategorized as an EPIC and moved to Future initiatives Column.

**Comment by BSmolensky** [comment]
Work on this epic should include: 

- [ ] Dividing the PW up into small, manageable sections
- [ ] Then Assigning each PCT member a select number of pages within that section of the PW to review. 
- [ ] Spreadsheet should be created to track results
- [ ] New Tickets Created to fix pages that need fixing. 
- [ ] Repeat process until all 550+ pages on the PW have been reviewed and fixed

**Comment by laucon** [comment]
Writing a note here: Contact Us document

**Comment by BSmolensky** [comment]
**NOTE**: This Epic is labeled "Low Priority" because if we are going to review every page on the PW, we should probable review them for EVERYTHING. This Epic will likely become part of a much larger epic wherein we audit every page on the PW. Such an audit will likely involve several other teams. As we are finding out with the ESI audit (a very small corner of the PW), some pages will need archiving as they are no longer in active use. That will require working with SMEs and, likely, entire teams. A full PW audit, should we decided to take it on, would a major, collaborative, group effort that will need to be broken down into very small, manageable parts.
