### ISSUE TITLE
Create Tip of the Sprint Master List for PCT members

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#86418]
Since we turned our Tip of the Sprint Archive into a public-facing doc, we need an internal resource for the Tips of the Sprint. This new, internal doc should include a list of all old Tips of the sprint as well as a list of all potential future Tips. The goal will be for PCT members to use this new doc as a repository for their Tip of the Sprint ideas. 

### TASKS

- [x] Create new list of old Tips of the Sprint, keeping descriptions to a few words.
- [x] Cull through old Slack posts to find any and all PCT member Tip suggestions.
- [x] Add the above list to the list that exists on my desktop
- [x] Format new page
- [x] Write intro to new page
- [x] Publish new page
- [x] Share link with teammate

### ACCEPTANCE CRITERIA

- [x] New Internal Tip of the Sprint Master List exists on Platform Team Confluence page
- [x] Link to new doc share with team on Slack

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance Criteria met. Ticket ready to close.

**Comment by BSmolensky** [comment]
Here is the link to the doc: https://vfs.atlassian.net/wiki/spaces/CIT/pages/2493743148/TIP+OF+THE+SPRINT+-+Master+List

**Comment by jknipes** [comment]
work is complete, moving to _Closed_
