### ISSUE TITLE
[DevOps] Terraform Apply workflows should be skipped if Plan doesn't have changes.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86414]
## Description
Just saves time.

## Tasks
- [ ] [DevOps] Determine the most reliable way of seeing whether Plan has meaningful changes.
- [ ] [DevOps] Implement this in the relevant workflows.

## Acceptance Criteria
- [ ] Apply actions are not attempted when Plan is empty.

**Comment by ndouglas** [comment]
This is hard because Terragrunt doesn't support the detailed exit codes that Terraform can return. It's a nice-to-have but unless that changes upstream, there's unlikely to be much we can do about this that doesn't increase fragility.

**Comment by ndouglas** [comment]
Or we can just plan xor apply. No reason to do both in the same operation.
