### ISSUE TITLE
[BE] 10-10CG - OAuth2.0: Test OAuth 2.0 Authorization Flow E2E with Mulesoft team in Staging

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#86430]
## Background
Now that we have implemented the service to use OAuth2.0, we need to test the new flow with the Mulesoft team.

## Tasks
- [x] Turn on flipper toggle for new OAuth 2.0 Authorization Flow for the 10-10CG form and validate that MuleSoft receives the payload. 
-  [x] Coordinate with CARMA/MuleSoft team for full testing
     - It should be a pretty simple auth failed or did not fail. Nothing else as far as payload data should change. 
- [x] Share test results with PM/team for signoff
     - [x] Signoff is documented in the comments within this ticket.

## Acceptance Criteria
- Staging testing has been completed successfully with the Mulesoft team to ensure the end-to-end flow is working as expected and there is no impact to the online 10-10CG form

**Comment by allanto-ah** [comment]
Testing was completed and verification and sign off can be seen in this ticket: [89109](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89109)
