### ISSUE TITLE
[DevOps] Proof-of-Concept LoROTA Lambda post-deployment test in Terratest

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86440]
## Description
Followup to #86891.

Currently, we have lovely unit tests that cover our Lambdas very well. However, unit tests only demonstrate correct function of the code itself; any nontrivial change to infrastructure usually leads to manual testing on staging just to see if things connect correctly, IAM permissions are valid, etc. We should have some end-to-end tests.

Unfortunately, Terratest is in Go and I've never done anything like this, so I think we should do a PoC to see whether this is a valid, defensible, helpful approach given its costs in times and requirements in experience, etc.

It should also be noted that this creates and tears down infrastructure, which means this will incur significant costs in time and resource expenditure. It might be better just to test things in place with Python or NodeJS scripts.

It might also be that we decide shortly after commencing this that this is an absolutely stupid approach and we shouldn't move forward with it to any degree.

## Tasks
- [ ] [DevOps] Create a simple Terratest test that e.g. retrieves a token from the LoROTA /token endpoint.
- [ ] [DevOps] Evaluate this approach, its costs, its benefits, the lift for each test, and so forth.
- [ ] [DevOps] Document findings in this thread.

## Acceptance Criteria
- [ ] Terratest test has been created and the process, experience, and outcomes documented in this thread.

**Comment by ndouglas** [comment]
Not gonna do this; Node seems to be the way forward.
