### ISSUE TITLE
Add monitoring/alerting for new iamActivityAudit lambda function

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#8644]
## User Story or Problem Statement
An additional requirement from ATO for the automated IAM activity auditing task is to monitor said solution so we are informed if it were to break / stop working as intended. 

## Goal
Alerting on the new solution that was put in place for monitoring IAM activity. 

## Objectives or Key Results this is meant to further
- Complete automation with proper monitoring of solutions implemented. 
---
## Tasks
- [ ] Add alerting for informing the Ops team of any breakage of the lambda function that is monitoring IAM activity. 

## Acceptance Criteria
- [ ] Alarm in place and alerts being sent correctly.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
