### ISSUE TITLE
Map out editor experience for form builder for Drupal in Figma

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-team#86459]
### Description
To explore editor workflow for publishing forms that meet the criteria defined by the VA-facing forms team, we can experiment with a simple set of questions (such as VA-form pattern “personal information”) and map out a workflow using Drupal DS components and paragraphs.
 
### Acceptance Criteria
- [ ] * Map out an editor workflow in Figma using Drupal DS components for a editor to create a single step for a veteran-facing form. 

```[tasklist]
### Tasks
- [ ] Create an experimental Drupal paragraph as a model for editing a single step 
- [ ] Include the attributes and text an editor an editor is requirement to manage (Per VADS pattern guidelines. 
- [ ] Develop reusable pattern for step layout and editing workflow
```
### Additional work
* A workflow that that can adapt to changing attribute requirements.
* A "View" and "Edit"mode for editors help editors update form content
* Help text for the editor may require CMS design collab cycle review
* Additional updates to CMS DS components and paragraphs
