### ISSUE TITLE
Design Intent - IA Feedback - Benefits Non-Disability, COE (26-1880), Form Updates

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#86455]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thank you for accounting for unverified/LOA1 users in your user flows!
- I am really excited about the automatic COE. That's fantastic.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must: clarify flow for properties affected by natural disasters** Right now, there are two separate multi-page multi-response patterns: one for entering properties financed by VA loans; one for entering properties financed by VA loans **and** impacted by natural disasters. It seems like these two flows could be consolidate by asking "Has this property been impacted by a natural disaster?" as part of the initial form flow where Veterans are entering information about properties they own. As we discussed in the meeting, if there is a way to consolidate this flow, please do.
- [x] **Should: determine how users will check form status after submission** How will the Veteran be able to understand the status of the submitted form? Will the submission be visible in My VA or Profile?
- [ ] **Consider: context for previous names** If possible, when asking for previous names, indicate why this information is needed and how it will be used. Are you asking which names might have been included on previous loan applications, previous military service records, or any/all legal names or names of use the person has had?

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by fiorella-io** [comment]
We got clarity from our SMEs on 7/2. When claimant adds a property that they still own that used the VA loan program, they will also be asked if that property has been damaged by a natural disaster. 

The existing COE form has a link to [check for their COE status](https://www.va.gov/housing-assistance/home-loans/check-coe-status/). We won't be updating this.

**Comment by erinrwhite** [comment]
@fiorella-io awesome news about the flow! Thanks for the update.
