### ISSUE TITLE
[Pension Module] Flipper implementation of API calls to Module paths

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#86460]
## Issue Description

Implement FE and BE flipper redirection to module controlled paths

---
## Tasks
- [ ] FE flipper implemented
- [ ] BE flipper implemented

## Acceptance Criteria
- [ ] when the flipper is enabled, api calls will direct to the module controlled paths
- [ ] when the flipper is disabled, a forbidden response will be returned
