### ISSUE TITLE
Copy of Merge VAProfile Demographics Services into V3::ProfileInformation

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#86486]
## User Story
As the engineers working on the EVSS PCIU migration objective,
It is is important that the v2::ContactInformation is updated to v3::ProfileInformation
So that the [EVSS PCIU migration](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73776) work can be completed

## Issue Description
V3::ProfileInformation is a service that pulls data from multiple VAProfile services currently being used in Vets-API. Upgrading from V2::ContactInformation to V3::ProfileInformation will reduce the number of requests and simplify the Vets-API infrastructure. This ticket is to replace each applicable service to use V3::ProfileInformation. The following services can be merged into V3::ProfileInformation:
- VaProfile::Profile
- VaProfile::Communication
- VAProfile::Demographics
- VeteranVerification::DisabilityRating
- VaProfile::HealthBenefit
- VaProfile::MilitaryPersonnel

## Tasks
- [ ] Merge Demographic Services into V3::ProfileInformation
- [ ] Test Demographic Services on V3::ProfileInformation
- [ ] Deprecate V2::ContactInformation
- [ ] Update any relevant documentation for VAProfile

## Success Metrics
- [ ] Number of requests to Vets-API have been reduced after the merge of all profiles by X%
- [ ] Vets-API infrastructure is simplified (**_how was it simplified? Process?_**)

## Acceptance Criteria
- [ ] All Demographic Services profiles have been merged
- [ ] All Demographic Services profiles have been tested and validated post-merge
- [ ] All relevant documentation has been updated 
---

The services were derived from this list of Va::ProfileInformation data
```
- contactInformation
- militaryPerson.transferOfEligibility
- benefitAwardInformation
- communicationPermissions
- demographics
- disabilityRating
- healthBenefit
- militaryPerson.adminDecisions
- militaryPerson.dentalIndicators
- militaryPerson.militaryOccupations
- militaryPerson.payGradeRanks
- militaryPerson.prisonerOfWars
- militaryPerson.militaryServiceHistory
- militaryPerson.militarySummary
- militaryPerson.militarySummary.customerType.dodServiceSummary
- personAttributes
- militaryPerson.adminEpisodes
- genderIdentityTraits
- militaryPerson.retirements
- militaryPerson.separationPays
- militaryPerson.retirementPays
- militaryPerson.combatPays
- militaryPerson.unitAssignments
- militaryPerson.medalsAndAwards

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
