### ISSUE TITLE
Toxic Exposure 1.0: Fix known issues with Form526ToLighthouseTransform service and determine launch blocking and non-launch blocking errors

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#86496]
## Issue Description
Thomas and Dewayne of Carbs🥖 ran audits on the Lighthouse submit endpoint and reported their findings in the comments of [this ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/84199) (which was originally created for 1 issue with treatment dates- which has already been resolved). This ticket is to fix these issues:

Issues found in Production (in priority Order):

1. undefined method []' for nil:NilClass -- /app/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:187:in transform_service_information'

7. undefined method 'icn' for nil:NilClass -- /app/app/models/form526_submission.rb:528:in `lighthouse_service'

Issues found in Staging:

11. `undefined method '[]' for nil:NilClass -- /app/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:173:in 'transform_service_information'`
   - Form526Submission.id = 1246
   - created_at = 2024-05-28 03:04:11.010697000 +0000
   - [form526.1246.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd7999f39caa065b06d08e86d30f2f9ee94c4557/form526.1246.json.txt)

12. `undefined method '[]' for nil:NilClass -- /app/lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:481:in 'convert_approximate_date'`
   - Form526Submission.id = 1245
   - created_at = 2024-05-28 02:25:44.710640000 +0000
   - [form526.1245.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0a6c285af9de0046e45f03d69913594adcb2626/form526.1245.json.txt)

13. Validation Failed - Claimed Disabilities
  - Form526Submission.id = 1238
  - created_at = 2024-05-20 18:38:29.355686000 +0000
  - [form526_error_1238.hash.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--646a012f0aeb719eadcff1d5673c78709e9fe71b/form526_error_1238.hash.txt)
  - [form526.1238.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8f7b30f4b1302b7c27e69e73ea355d90de1b4da/form526.1238.json.txt)

14. Validation Failed - Account number for the direct deposit.
  - Form526Submission.id = 1229
  - created_at = 2024-05-17 17:22:22.001616000 +0000
  - [form526_error_1229.hash.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca0a52d54edea3c5c8584b4f7939af879ef0c4c1/form526_error_1229.hash.txt)
  - [form526.1229.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54ed866d7767857de4afcf2e41df2c419b8b65cb/form526.1229.json.txt)
 
---
## Tasks
- [ ] Understand the outcomes of each of the errors in #[86252](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/86252)
- [ ] Determine which are launch blocking, which are not
- [ ] Fix the errors 1,7,11,12,13,14 listed in this ticket
- [ ] Split the non-launch blocking work and launch blocking work into separate tickets

## Acceptance Criteria
- [ ] Known issues are fixed/resolved.
- [ ] New tickets are created for the launch-blocking errors (that is NOT in scope for this ticket), and non-launch-blocking errors

## Notes:
It's okay with OCTO if the release date gets pushed back due to fixing launch-blocking errors. Thorough testing is accepted and encouraged. Suggested that we run another testing batch to validate fixes and/or reveal new errors before our Canary test with VA employees.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aurora-a-k-a-lightning** [comment]
1. done - this was happening because `reservesNationalGuardService.title10Activation` was `nil`
2. done - user_account_id is optional on a Form526Submission record. hopefully looking up by the user_uuid if user account is not available on the model will suffice
11. done - i think this was in the same boat as #1, something to do with service periods
12. done - this was the treatment['startDate'] issue, but also put check around another method that uses `convert_approximate_date`
13. non-issue/known-issue: that request did not have `disabilities`, i.e. `"disabilities": []` in the Form526Submission record - this may have been the request Christine and I were testing with the rated disabilities + CFI (a known issue)
14. take back to lighthouse? lighthouse expects account numbers to be 14 characters or less. the account number given in this example was more than 14 characters at 17 characters (12345678901234567). would this ever happen?
