### ISSUE TITLE
[Design] Shipping address (C1P2) - Update content to reflect addresses will only update in the form

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8651]
## User Story or Problem Statement
How might we provide clarifying content that updated shipping addresses will only apply to this form?

## Goal
_Updated mockup of the use case of a Veteran updating their shipping address to include clarification that the update will only apply to this order form_

## Objectives or Key Results this is meant to further
- _Finalizing MDT_
---
## Tasks
- [x] _Update one of the mockups displaying the edit state of an address card with [content following Peggy's guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md#addresses)_
- [x] _Link the InVision mockup to this ticket_
- [ ] _Create a ticket for FE development and attach to this ticket_

## Acceptance Criteria
- [ ] _InVision mockup is linked in a comment_
- [ ] _Ticket for FE is attached_
---

**Comment by rileyorr** [comment]
An [example of how this content should be displayed](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/407910003_C1_P2-_Both_Address_Passed_-_Edit_Address) has been uploaded to InVision.

**Note:** I did not update all of the mockups that feature the address in an editable state. However, this content should be included in these use cases: edit permanent address, edit permanent address + military checkbox selected, temporary address, temporary address + military checkbox selected, adding a temporary address if one was not pulled in through the API. Basically, any use case where the Veteran is editing one of their shipping addresses or adding a new temporary address.

**Comment by rileyorr** [comment]
[I've created the frontend ticket. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8655)
