### ISSUE TITLE
Resolution/Resolution Ticket: SPA Tracking Issue in GA4

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#86516]
### Description
Jamie discovered a page view tracking issue that seems to affect products using a single-page application (SPA) structure -- pages load dynamically instead of an HTML page load. Specifically, it was noticed as she was working on funnel repots for secure messaging and claims status tracking. This has required some investigation on our part to understand what might be going on and how to fix it.

This ticket is to implement the fix.

---

### Tasks

- [ ] Implement fix for SPA issue -- two funnel tickets.
- [ ] Confirm that the fix is indeed working.

### Acceptance Criteria

- [ ] Single-page applications are successfully tracking in GA4.
