### ISSUE TITLE
[DevOps] Set up Vista API core functionality in `checkin-devops`

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86524]
## Description
Followup to #86523.

Just create the Terragrunt project structure, determine what (if any) dependencies it has or that other services have on it, which inputs and outputs are used where, and declare those. Goal is just to have the plan and apply succeed, even if nothing is actually created.

## Tasks
- [x] [DevOps] Create `vista_api` settings within `checkin-devops`.
- [x] [DevOps] Create `vista_api` deploy IAM policy within `iam` module.
- [x] [DevOps] Ensure v0.0.0 or whatever can be deployed to all environments.

## Acceptance Criteria
- [ ] `checkin-devops` and `octo-vista-api` correctly plan and apply, even if they don't actually plan or apply anything.
