### ISSUE TITLE
[DevOps] Set up Vista API Terraform module in `octo-vista-api`

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86523]
## Description
This might mean creating a new repository, might mean getting access to an existing one. Use `octo-vista-api` if possible.

## Tasks
- [x] [DevOps] Create `vista_api` terraform module in `terraform/` of `octo-vista-api` or some other repository.
- [x] [DevOps] Tag a v0.0.0 release or something, just a module that doesn't actively break anything.

## Acceptance Criteria
- [x] TF module exists in appropriate place.

**Comment by ndouglas** [comment]
Created, waiting on #86524.
