### ISSUE TITLE
Design intent Collaboration Debt Letters MVP (BAM2)

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#8652]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> BAM2 design intent collaboration meeting completed
- [ ] Design experts leave feedback and relevant resources on this ticket
- [ ] VFS designer acknowledge receipt of feedback/resources
- [ ] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp)
- [Wireflows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md)

## Meeting attendees from **requesting team**
- Designer(s) (required): Rebecca Walsh, Riley Orr
- Product Manager (optional): Leah Keeler
- DEPO design lead (required as applicable): Matt Self

## Scheduling
Preferred dates or times: 
Monday, June 1st - all day

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, (content?), (IA?)

**Comment by rebeccawalsh** [comment]
@CrystabelReiter @andreahewitt-odd 

Here is the link to our wireframey sketches in Github!: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md

**Comment by 1Copenut** [comment]
@rebeccawalsh I'll leave my accessibility design comments here as a list. LMK if you prefer another means or want them broken out to a separate ticket.

* The Need help? phone number should be a link. This will be a nice way to jump to action immediately using the OS phone support or dialing directly on a mobile device.
* Any downloadable and printable letters (PDFs?) will need to be checked for accessibility. Do we know where these are going to be coming from? Are they generated or linked from another group at VA?
* Really like how the pages are divided up using headings and type hierarchy. This makes scanning easy and accurate.

**Comment by jenstrickland** [comment]
[IN PROGRESS] 

**VSA Accessibility Feedback** 

1. **Consider** adding an intro paragraph of 1-3 sentences explaining what the content on the page is, and that there is guidance for how to pay. For mobile and screen reader users, the "How to pay" and "Need help?" information will be very far down in the reading order. The stress of reading about the debts may overwhelm, and they may not get to it.

**Comment by CrystabelReiter** [comment]
@rebeccawalsh awesome work! ticket shall be closed.
