### ISSUE TITLE
[DevOps] Determine additional privileges needed for CHIP Lambda Role

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86522]
## Description
Looks like it has some S3, KMS (see #86521), etc permissions too. What does this imply?

## Tasks
- [x] [DevOps] Determine why additional privileges exist in the CHIP Lambda Role and document in this thread.
- [x] [DevOps] Open followup ticket(s) to address appropriately.

## Acceptance Criteria
- [x] Additional privileges in the CHIP Lambda Role are understood and have been documented in this thread.
- [x] Followup ticket(s) opened to address.

**Comment by ndouglas** [comment]
S3 is openAPI retrieval, I think. KMS is dealt with in #86521.

**Comment by ndouglas** [comment]
All is well; no need for followup tickets. I already merged the work to enhance the policy.
