### ISSUE TITLE
Content Edits for 86475

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#86534]
## Issue Description
Content edits according to support ticket [86475](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86475)

---
## Tasks
- [x] Review support ticket 86475
- [x] Contact SMEs to verify accuracy of suggested update
- [x] Update website according to suggestions provided by customer  
- [x] Prepare page for deployment

## SMEs for this work:
@acrollet - has participated in recent updates to this page

## Acceptance Criteria
- [x] Create a New Application page will be updated to include the changes
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/86534?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by laucon** [comment]
This is done. We can close it. :)

**Comment by jknipes** [comment]
Closing per the above comment, _Done_
