### ISSUE TITLE
Standards Documentation: Page Titles for Forms

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#86543]
# Overview

Define the page title format for online forms.

### Current documentation

[Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)

## Tasks
- [x] Review/analyze existing documentation and implementation - IA
- [x] Establish scope of effort and where guidance lives - IA
- [x] Draft revised standard - Jenny
- [ ] Review with Mikki - Jenny
- [ ] Review with Erin - Jenny
- [ ] Format for publishing (if going into VADS) - Erin
- [ ] Final review and approval by Mikki - Erin/Mikki
- [ ] Publish - Erin/IA
- [ ] Communicate out to teams - IA/Mikki

## Acceptance criteria
- [ ] Clear guidance for placement and inclusion of content or links on the home page is clearly defined and approved by IA lead, Sitewide design lead, and home page PO
- [ ] New template on VADS is communicated out to teams

**Comment by jennymayoco** [comment]
[Draft](https://docs.google.com/document/d/1PJZYNiJ1ejQWAeias0qeZd9Sv5xMHyBJfHLuHB5ftv4/edit)

**Comment by jennymayoco** [comment]
Passed on documentation to Content team as this is content style guidance
