### ISSUE TITLE
Auto Applying Platform Support Ticket Label to All Support Tickets

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#86556]
## Description 
We would like to research the ability to add the platform-support-ticket label to the following categories:

- Access Requests
- VFS New Team/New Member Tickets
- The entire Active Support Issues column of tickets (tickets that come from Slack)

I am curious if we just apply the label to all tickets in the Active Support Issues column if all tickets would be covered then?

---

## Definition of Done
All tasks below are complete.

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Identify potential solutions to help us avoid a manual process of adding a label each time
- [x] Identify the best solution and create a ticket for executing on it in the backlog
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Resolved on a call regarding GH projects. No longer need this ticket. Closing!
