### ISSUE TITLE
Submit Dash + TE Doc Updates for 1.0 Benchmarks

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#86569]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [x] Benchmarks for volume, errors, expected traffic
- [x] Rollout intervals
- [x] Document risks
- [x] Update submit dash w/submit job (submit_form526) activity for submit
- [x] Update TE Plan document

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alatempa24** [comment]
Updated the TE plan based on benchmarks.
