### ISSUE TITLE
[CST][ENG] Status Tab, Recent activity (claimPhaseDates)

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#86582]
## Value Statement
As a veteran with a disability claim
I want to to be able to clearly identify what actions are being taken on my claim by the VA, as well as requests that are for third parties
So that I'm aware of what's going on with the claim, and I'm what other people are responsible to provide on my behalf and so I can take follow up actions with those third parties if necessary

---
## Background Context
The "Recent Activity" section of the Status tab informs Veterans about actions being taken on the claim by the VA and show a blue alert for any open 3P evidence requests. Currently it shows tracked items but it also needs to show claimPhaseDates.

## Design
- [Recent Activity](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?node-id=966-7066&t=LfCKQQw6AHB6U0GM-0)

<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2fadaac24b4a589705a40240dd5d8ba6ee4e9a9/Screenshot%202024-06-21%20at%202.45.59%E2%80%AFPM.png" alt="Screenshot 2024-06-21 at 2.45.59 PM.png" />

## Engineering 
- Can use some of the logic that is in `generatePhases()` that is on OverviewPage.jsx and add it to RecentActivity.jsx when we `getSortedItems()`
- We want to show **ALL** of the claim phase dates so logic will be different then what we have in the current timeline
- We want to use the feature flag `cst_claim_phases` so that we are accounting for when there are 5 vs 8 steps

## Tasks
- [x] Add all claimPhaseDates to the recent activity section - this should also include logic around `currentPhaseBack`
- [x] When feature flag `cst_claim_phases` is enabled and when the claim is a disability compensation claim we show 8 steps
- [x] When feature flag `cst_claim_phases` is disabled and when the claim is a disability compensation claim we show 5 steps
- [x] Update vets-api-mockdata so that mock claims have the correct phase information
- [x] Add unit tests for this work
- [x] Add cypress tests for this work

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The recent activity section includes ALL claim phase changes
- [ ] The recent activity section includes claim phase changes where the phase has `currentPhaseBack`
- [ ] When feature flag `cst_claim_phases` is enabled and when the claim is a disability compensation claim we show the text for 8 steps
- [ ] When feature flag `cst_claim_phases` is disabled and when the claim is a disability compensation claim we show the text for 5 steps
- [ ] mockdata is accurate for phases

**Comment by pmclaren19** [comment]
@jerekshoe @skylerschain not sure if its possible to add the logic for claim phase back since we cant tell on which step something was phased back. Let me know your thoughts!

**Comment by pmclaren19** [comment]
Started a chat about some questions in slack regarding this ticket https://dsva.slack.com/archives/C056854SVT8/p1719355843964119

Updating the points and ac to reflect some of the things we have discussed!

- We want to show all of the claim phase dates so logic will be different then what we have in the current timeline
- We want to use the feature flag `cst_claim_phases` so that we are accounting for when there are 5 vs 8 steps

**Comment by pmclaren19** [comment]
Met with team in parking lot heres what we learned:

- When a claim is `completed` BGS only returns the `phase7CompleteDate` and removes all of the other dates from the `claim. claimPhaseDates.previousPhases` field. @skylerschain is going to start a chat with @jacobworrell to see if he can reach out to BGS and have them change this so that we are still receiving all of the previousPhases instead of just `phase7CompleteDate`
- When a claim is in step 6 and `claim. claimPhaseDates.previousPhases` has phase1CompleteDate, phase2CompleteDate, phase3CompleteDate, phase4CompleteDate, phase5CompleteDate ... when you phase back to say phase 3, phase3CompleteDate, phase4CompleteDate, and phase5CompleteDate are removed from `claim. claimPhaseDates.previousPhases` and `currentPhaseBack` is set to true. @skylerschain is going to start a chat with @jacobworrell to see if he can reach out to Lighthouse and have them change this so that we are receiving ALL of the previousPhases, including the dates of the phased back ones. **Note this change would require us to change how we store the  `claim. claimPhaseDates.previousPhases`.**

Moving forward witht his ticket we will do the following:

- We will show all of the claim phase dates currently available to us
- When is a claim is phased back we will change the text to say `Your claim moved back to [Step X]` using the logic of `currentPhaseBack` being true. Understanding that when we move forward in steps that the text will change back to `Your claim moved to [Step X]` since `currentPhaseBack` is set back to false.
- When a claim is moved back to a step the previous step information no longer exists

**Comment by pmclaren19** [comment]
@jacobworrell I think we actually need to update the ticket/ac so that we are only showing the 8 steps when the feature flag cst_claim_phases is enabled and when the claim is a disability compensation claim - we determine this based off of the claim type code. Will update AC/ticket.

**Comment by pmclaren19** [comment]
@skylerschain @jacobworrell verified changes in Staging using user 23 and things looked good. Also [this](https://github.com/department-of-veterans-affairs/vets-website/pull/30585) pr has screen shots of what the recent activity section looks like for claims in various phases. Moving to closed but feel free to validate yourselves if needed and let me know if you have any questions or concerns!
