### ISSUE TITLE
[CST] Status Tab, Recent activity (claimPhaseDates)

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#86580]
## Value Statement
As a veteran with a disability claim
I want to to be able to clearly identify what actions are being taken on my claim by the VA, as well as requests that are for third parties
So that I'm aware of what's going on with the claim, and I'm what other people are responsible to provide on my behalf and so I can take follow up actions with those third parties if necessary

---
## Background Context
The "Recent Activity" section of the Status tab informs Veterans about actions being taken on the claim by the VA and show a blue alert for any open 3P evidence requests. Currently it shows tracked items but it also needs to show claimPhaseDates.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- [Recent Activity](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?node-id=966-7066&t=LfCKQQw6AHB6U0GM-0)

<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2fadaac24b4a589705a40240dd5d8ba6ee4e9a9/Screenshot%202024-06-21%20at%202.45.59%E2%80%AFPM.png" alt="Screenshot 2024-06-21 at 2.45.59 PM.png" />

## Engineering 
- Take the logic  for `generatePhases()` that is on OverviewPage.jsx and add it to RecentActivity.jsx when we `getSortedItems()`

## Tasks
- [ ] Add claimPhaseDates to the recent activity section
- [ ] Add unit tests for this work

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The recent activity section includes claim phase changes

**Comment by skylerschain** [comment]
Rereading this and I'm a bit confused. This ticket suggests that claim phase updates don't show in Recent Activity, but I currently see them in staging:

![Image](https://github.com/user-attachments/assets/336a1397-8c7d-4dc0-b0c6-a2c8dc24c375)

@jerekshoe can you make any sense of this ticket from your perspective? Is there anything currently missing from implementation that I'm overlooking here, or is this ticket simply not accurate?

**Comment by jerekshoe** [comment]
Pretty sure this ticket can be closed
