### ISSUE TITLE
Toxic Exposure: Refactor TE flag implementation out of prefill

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#86598]
## Issue Description
It was discovered during local development that the [initialization of the toxic exposure flag within the prefill method](https://github.com/department-of-veterans-affairs/vets-api/blob/c75117ce4afa6b087c07959bc741a5619d87dcff/app/models/form_profiles/va_526ez.rb#L88) is brittle. If any of the many external calls within the prefill method fail, then _all_ results within that method are lost- including our TE flag. This story is to refactor it _out_ of prefill, such that any failure in that method will still preserve the TE flag.

Aurora's suggestion (from slack):
1. start the form data
2. insert our toxic exposure indicator
3. do prefill separately
4. merge the two together
if prefill fails, we return whatever made it

---
## Tasks
- [ ] move TE indicator logic out of external prefill flow 
- [ ] not raise an exception when prefill fails

## Acceptance Criteria
- [ ] TE flag initialization refactored away from prefill, such that it is reliably set each time
- [ ] TE pages reliably display even when there is an external service outage

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
