### ISSUE TITLE
[Backend] Modify MDOT Service Authentication Process

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#8659]
## Problem Statement

In order for the MDOT Service to make successful calls to the DLC's API, the service will need to authenticate against an authentication endpoint provided by the DLC.

Attached is documentation that details the requirements for authentication with the DLC.

[https://app.zenhub.com/files/133843125/31180d41-2da5-421d-8471-5f4fba0ed17d/download](https://app.zenhub.com/files/133843125/31180d41-2da5-421d-8471-5f4fba0ed17d/download)

## Goal
Authentication mechanism is incorporated into the MDOT Service.

## Objectives or Key Results this is meant to further
- [ ] Will allow MDOT Service to make successful calls to the DLC API

## Tasks
- [ ] Add authentication method to MDOT service.
- [ ] Utilize authentication method during MDOT service initialization to get JWT, which will be used with subsequent requests.

## Acceptance Criteria
- [ ] With working authentication in the MDOT service, successful calls will be possible
