### ISSUE TITLE
Streamlined Waiver Calculation Check

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#86679]
## Issue Description

VHA has reported a potential miscalculation on a streamlined waiver submission, this ticket is to investigate and determine if there are any changes needed. 

## Background Details
- Communication came via va.gov email containing transactional data to @denisecoveyduc  and @HeatherRienks . (Please reach out if further clarity is needed)
- Email states that a "Automatically Approved, Waiver" came thru but that based on the information it should have required manual review. 
- Transaction ID: `c6c65a4fa0ba4340af8bedb9fd77b631`
- Submission date: `6/15/2024`

---
## Tasks
- [x] Clarify VODA System calculated an automatic approval
- [x] Review submission for any edge cases or abnormalities
- [x] Determine and communicate any actions needed
- [ ] Email Huron with news of fix
## Acceptance Criteria
- [ ] We have a clear understanding of why the discrepancy occurred and have defined next steps as needed. 
---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by digitaldrk** [comment]
Here is the GMT data we pulled from the form
```
{
  "gmt_data" => {
    "is_eligible_for_streamlined" => true,
    "pension_threshold" => 16037,
    "national_threshold" => 39849,
    "gmt_threshold" => 43050,
    "income_upper_threshold" => 64575,
    "asset_threshold" => 2798.25,
    "discretionary_income_threshold" => 538.125,
    "error" => nil,
    "income_below_gmt" => true,
    "income_below_one_fifty_gmt" => true,
    "liquid_assets_below_gmt" => true },
  "social_security" => { "spouse" => {} },
  "employment_history" => { "spouse" => {} },
  "agreed" => true
}
```

FE is returning shortform approved but from our calculations they _MIGHT_ approve for longform, likely not.

We think this is a FE ticket, will provide data as needed.

**Comment by digitaldrk** [comment]
Pinged in the dev chat about this ticket. I think we'll have a plan to sort this out tomorrow.

**Comment by amponce** [comment]
Maybe we can set up a test with the data you pulled? 

Should one of these values have been false?
```
"income_below_gmt" => true,
"income_below_one_fifty_gmt" => true,
"liquid_assets_below_gmt" => true 
```

**Comment by digitaldrk** [comment]
I am going to pivot to the debts controller alert we are getting and prepare for a meeting with regards to that. I'll cirle back here.

**Comment by digitaldrk** [comment]
No updates at the moment.

Kevin and I paired and we had a hunch that this was a FE issue as mentioned above. One evening this week, I took the form data we saved from this ticket and ran it through our backend FSR transform code to see what it determined. I ended up finding bugs in our BE FSR transform code and worked on that:

https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87011

Between that and the debts controller, haven't gotten back to this.

I plan to hop on this tonight/tomorrow

**Comment by HeatherRienks** [comment]
I emailed Aleena and Varun to let them know that we are still working on this.

**Comment by digitaldrk** [comment]
I formally wrote up a document and shard it with the team (mentioning FE particularly). The document outlines financial values the veteran has, the shortform criteria in the FE code has, and how there are discrepancies.

I think this is a frontend issue I will be available to pair and get any data needed to help run this down.

**Comment by digitaldrk** [comment]
This is either a misunderstanding or a FE issue. The streamlined decision happens in the FE and it sends the following data to the BE:

`'streamlined' => { 'value' => true, 'type' => 'short' }`

We read the 'value' which is 'true' in this case and add the 'Automatically Approved, Waiver' to the payload we send off.

Who can I talk to about this to determine what business logic they are using to determine this should not receive 'Automatically Approved, Waiver' Aleena and Varun?

**Comment by HeatherRienks** [comment]
Update:  Derek has been troubleshooting this issue.
I have added @digitaldrk and @maxx1128  to email thread with Varun & Aleena so we can determine next steps needed. We may need to coordinate a quick meeting with them to discuss. This ticket will roll over to S129.

**Comment by digitaldrk** [comment]
From what I can tell, this should NOT be a streamlined. It definitely does not make the requirements for **short** and from what I can tell, does not make the requirements for **long**. For long, it seems to fail at the discretionary income threshold, it passes all others for long though. 

All of this is calculated in the frontend from what I can tell. I know that Aaron did some tests, I can’t remember what his result was.

IMO this ticket should be closed and either a FE ticket is created or we say that we will keep an eye out for issues in the future since this calculation is actively moving to the BE in server-side transform.

**Comment by Tom-Davis** [comment]
I agree- this is sounding like we can close and have FE open a validation ticket or add it to an existing ticket in the acceptance criteria - @Dr-Pongo can you please spin up or add this check to your ticket?

**Comment by Dr-Pongo** [comment]
FE taking over investigation to find root cause!

**Comment by HeatherRienks** [comment]
I emailed Aleena and Varun (Huron) that FE is taking this effort over and that I would reach out to them by end of week with a status update.

**Comment by Dr-Pongo** [comment]
Closing out now that PR has been merged!

**Comment by HeatherRienks** [comment]
I wrote Varun & Aleena on Monday, 7/22/24 with this: 
_"Our team is working on this issue and we believe we've identified and resolved the issue that could potentially cause false positives for automatic approvals. The remainder of additional logging for us to track potential issues and any related fixes should all be merged and in production by EOD today. We will keep you posted."_


@Dr-Pongo - Can you please provide a blurb that I can email to Huron to close the loop on this? Thank you!!
