### ISSUE TITLE
527EZ: Review form for usability improvements V2

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#86677]
## Description
The pension team is updating the income sources screens in the financial information section of the online form. We need to review those screens and provide recommendations.

## Resource
[Figma file](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=4750-65638&t=puW0RiAxOrzkylEy-4)

## Tasks
- [x] AP: Draft recommendations
- [x] AP: Share recommendations with product team

## Criteria
- [x] Content recommendations have been shared with product team

**Comment by aprocik1** [comment]
## Your monthly income
In the next few questions, we'll ask you about your monthly income.

<details>
<summary>How we define income</summary>

You income is the money you earn from a job, or from retirement or annuity payments. Your income may include these types of payments:

- Salary or hourly pay
- Bonuses
- Commissions
- Overtime
- Tips

We may subtract certain expenses from your income when we review your application. We call these applicable deductible expenses. They include educational expenses and medical expenses you’re not reimbursed for.

</details>

[Buttons] Back, Continue

**Comment by aprocik1** [comment]
If there are more than 4 total sources of income between the Veteran and their dependents:

## Submit supporting documents

Based on your answer, you’ll need to submit a supporting document about your income and assets.

We’ll give you instructions for submitting your supporting document at the end of this application.

**Comment by aprocik1** [comment]
## Your dependents' monthly income

### Screen 1
In the next few questions, we'll ask you about your dependents' source of monthly income.

<details>
<summary>Who we consider a dependent</summary>

**A dependent is:**
- A spouse (**Note:** We recognize same-sex and common-law marriages)
- A parent, if you’re directly caring for them and their income and net worth are below a certain amount
- An unmarried child (including an adopted child or stepchild) who meets one of the eligibility requirements listed here

**To be considered a dependent, one of these must be true of an unmarried child:**
- They're under 18 years old, **or**
- They're between the ages of 18 and 23 years old and enrolled in school full time, **or**
- They became permanently disabled before they turned 18

</details>

<details>
<summary>How we define income</summary>

Your dependents' income is the money they earn from a job, or from retirement or annuity payments. Their income may include these types of payments:

- Salary or hourly pay
- Bonuses
- Commissions
- Overtime
- Tips

We may subtract certain expenses from your dependents' income when we review your application. We call these applicable deductible expenses. They include educational expenses and medical expenses your dependents aren't reimbursed for.

</details>

[Buttons] Back, Continue

### Screen 2
Do you any of your dependents receive a monthly income?
- [x] Yes
- [ ] No

[Buttons] Back, Continue

You can submit multiple sources of monthly income for all your dependents. Add one source of monthly income at a time.

### Screen 3
Which of your dependents receive monthly income? (*Required)
- [ ] My child
- [ ] My parent
- [ ] My spouse

What type of monthly income does your dependent receive? (*Required)
- [ ] Civil service
- [ ] Interest or dividend payments
- [ ] Pension or retirement payments
- [ ] Social Security payments
- [ ] Other
Describe the type of monthly income

Who pays your dependent's monthly income? (*Required)
[Hint] Enter the name of a company, government agency, or another organization

What's your dependent's monthly income amount? (*Required)

[Button] Cancel adding this monthly income

[Buttons] Back, Continue

### Screen 4

[Header] Monthly income for your [child / spouse / parent]
> ### Monthly income from [source 1]
> - Type of monthly income: 
> - Amount of monthly income: 
> [Buttons] Edit, Delete

[Header] Monthly income for your [child / spouse / parent]
> ### Monthly income from [source 1]
> - Type of monthly income: 
> - Amount of monthly income: 
> [Buttons] Edit, Delete

> ### Monthly income from [source 2]
> - Type of monthly income: 
> - Amount of monthly income: 
> [Buttons] Edit, Delete

Do you need to add another source of monthly income for any of your dependents?
- [ ] Yes
- [ ] No

[Buttons] Back, Continue

**Comment by aprocik1** [comment]
If there are more than 4 total sources of income between the Veteran and their dependents:

## Submit supporting documents

Based on your answer, you’ll need to submit a supporting document about your income and assets.

We’ll give you instructions for submitting your supporting document at the end of this application.

[Buttons] Back, Continue

**Comment by aprocik1** [comment]
Update: I created a [CAIA recommendations board](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5800-8169&t=tYqzeAdQKF292fFZ-4) in the Figma file. I shared this board with the product team. I'm moving this ticket to validate, but keeping it open for now, in case I need to return to it.
