### ISSUE TITLE
SC | Investigate and re-enable maximal e2e test

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#86685]
## Value Statement

**_As a_** Decision Reviews Team developer
**_I want to_** investigate and re-enable the disabled maximal e2e test
**_So that_** we can ensure our Supplemental Claim app has complete testing coverage at all times

---

## Background Context

While the platform team upgraded Cypress to v13.11.0, they needed to disable our SC maximal e2e test. So now our team needs to investigate why it was required to be disabled, fix it and re-enable the end-to-end test.

## Acceptance Criteria

- [ ] Cause of maximal e2e test found & fixed
- [ ] Maximal e2e test re-enabled

## Tasks

- [ ] Determine cause of e2e test failure
- [ ] Investigate fixing the problem
- [ ] Fix the problem, if possible
- [ ] If required, split up the e2e test into smaller tests

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design
