### ISSUE TITLE
BDD and 526 form content page edits from Benefits and Memorials 1

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#8668]
## Why you're here
- Content support for static public website pages
- Content support for authenticated application or tools
- For specific copy editing tasks
- Support for redirects that have **first been vetted by the VSP IA team**
- Engineering support for implementation of REACT sign in widgets

## Steps to complete intake request
- [ ] Submit this request when VSA Public Website team intervention is required
- [ ] Provide detailed information of your request to help us understand our role in completing your request 
- [ ] Link to this issue in #vsa-public-websites in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Background
*Provide a background of your tool/functionality.*
This is a request for the Benefits Delivery at Discharge functionality (allowing service members to file a claim online before they separate from the military) that is to be added into the 526 form functionality. Presently, the Benefits Delivery at Discharge application process is available only on ebenefits and via a paper form submission.

The current design for the proposed BDD form can be viewed here: https://vsateams.invisionapp.com/share/BUWOTNKFPK7

The findings from our usability testing research initiative can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/Initial-usability-March2020/BDD-research-findings.md

### Request Type
*Select all applicable and provide details behind your request* 

           
- [ ] **Content support for a static public website page**
   * Is this to update existing static content? 
      * Yes
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * No
   * Provide a list of URL/s that need to be reviewed or updated. 
      * https://staging.va.gov/disability/how-to-file-claim/ (526 disability info/wizard page)
      * https://staging.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/ (BDD info page)

** Further details **

#### 526 Disability Info Page

We believe this page can be improved in a couple key ways:

- There may be value in letting the user know exactly what types of claims they could file via the 526 form. There is excellent information outlining exactly what the Veteran or SM can file on the 526 via [this page](https://www.va.gov/disability/how-to-file-claim/when-to-file/). All disability filing types listed in the accordions on this page will be available via the 526 online form (we're getting original claims wrapped up now) and we will additionally be able to handle BDD via the 526 as well (est launch date in late June).
- There may be value in moving the 'action' button up a bit on the page - though we do understand that this is already in the works via the gating/wizard refactor your team is currently working on.

**if you would prefer us to supply a visual/design mock on what we're thinking for this, we can do that as well. Please let us know!**

#### BDD Info Page

- There may be value in condensing the information on this page - specifically removing the blue box and creating sections about certain eligibility (date ranges from separation date) and outlining what options are available for those specific dates.
- There may be value in nesting actions that the user can take for the date range they fall into (e.g. 'if you're 180-90 days out and meet the above requirements, you can file a BDD claim **online** or via the **paper form**." - links denoted in bold) 

**We plan on supplying a visual on this. We will upload to Invision and link to it next week (week of May 4)**

### Desired/target implementation date

We are anticipating a launch for BDD in late June. This request can be satisfied anytime before then.

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: *Benefits and Memorials 1*
- DEPO product owner: *Andrea Schneider*
- Product manager: *Lukasz Majewski*
- Designer: *Kevin Stachura* and *Christian Valla*
- FE engineer: *Nicholas Sprinkle*
- Product/team Slack channel: *vsa-benefits-memorial*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by stephorkandatx** [comment]
Selina to set up a kick-off meeting for this, to confirm the request

**Comment by stephorkandatx** [comment]
@lunascoop I'm turning this into an Epic + creating at least 1 ticket to track forward

**Comment by lunascoop** [comment]
Met w/ Mikki and Danielle yesterday. IA needs to finalize strategy before moving forward w/content work.

**Comment by FranECross** [comment]
All tickets in this epic are closed; closing.
