### ISSUE TITLE
Content Edit: #86476

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#86732]
## Issue Description
It looks like our Platform deploys docs are not in sync with when the deployments for content-build actually take place: https://dsva.slack.com/archives/C02VD909V08/p1718731255111909. Should the docs here say content-build is 2 ET / 3 ET instead? https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments Basing this on the messaging in the #status-content-build channel.

## Slack Thread Link: 
https://dsva.slack.com/archives/CBU0KDSB1/p1718906549147049

## Screenshot showing confirmed correct time
![Screenshot 2024-06-24 at 12 19 58 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/3ce0582a-e8e0-4a7a-a2ce-0a42864618f6)

---
## Tasks
- [x] Update page with correct time per screenshot above

## Acceptance Criteria
- [x] Page is updated and ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Work is complete, moving to _Closed_
