### ISSUE TITLE
Create Staging Review in Engineering and Security track of Collaboration Cycle

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#86735]
## Status
| Date | Status | Launch Date | Notes |
| ----- | ------ | ------------------------- | ------ | 
| 8/11/2025 | Post-launch |8/4/2024 | Successfully launched on Aug 4, however we still need to deprecate PSIRR, update active CC Request tickets to ensure teams have the correct guidance, as well as other small tasks.|
| 8/1/2025 | In progress | | On track to launch Monday Aug 4. Still have other tasks to complete post-launch.|
| 7/25/2025 | In progress | | Finalizing updates to Platform Website. On track to launch the week of August 4.|
| 7/14/2025 | In progress | | New Engineering & Security Checklist page created. Adding eng and sec to SR slide and script.|
| 6/27/2025 | In progress | | Shared options for Eng/sec to provide written feedback. Decision to be made 6/30. Will draft updates to VFS-facing guidance next sprint.|
| 6/20/2025 | In progress | | Governance is making small changes to distribution list and timeslots. Standup with all involved scheduled for Monday afternoon, recurring. Need to make decision on feedback method for Arch Intent and SR |
| 6/13/2025 | In progress | | Engineering TL's defined - Curt, Lindsay and Kyle M. Work breakdown identified, and we've proposed a change to _how_ feedback for Arch Intent and Staging Review will be documented. Shira to connect with new engineers, Platform Security and OCTO leads next week to confirm plan. |
| 6/9/2025 | In progress | | Looking at how to staff the engineering component and the possibility of utilizing TLs for Arch Intent and Staging Review. Will need tickets created for issues and someone to create/manage these. Throttle reviews down to 2 per week (half of what we offer now) to help accommodate engineering resource constraints. **GOAL:** Start by July 11th. |
| 6/6/2025 | In progress | | Platform Security is still determining which docs/guidance they'd need to update. Shira and Kelly syncing 6/9 to discuss Governance support.|
| 5/30/2025 | In progress | | Received proposal for updates to Architecture Intent and PSIRR. Synching with Kelly next week to break down the work and determine Governance involvement.|
| 5/23/2025 | In progress | | No updates. |
| 5/16/2025 | In progress | | Platform Security is auditing scope of PSIRR vs. Architecture Intent. Will follow up May 27.|
| 5/12/2025 | In progress | | Meeting with Platform Security today to discuss MVP for security only. No engineering to be discussed.|
| 5/1/2025 | In progress | | Meeting held. Still need to discuss next steps with OCTO-DE Lead.|
| 4/18/2025 | In progress | | Starting conversations with OCTO leads. Meeting scheduled for 4/22. |

## Problem Statement 
Currently, Collaboration Cycle provides governance and support for Content, Design, IA, Accessibility, and QA. As VFS teams have grown, there is a need to provide engineering and security governance and support. Since Collaboration Cycle already has the infrastructure to work with VFS team, we want to integrate engineering and security standards into the current process. 

Currently, Platform teams do not go through collaboration cycle consistently. The experience standards are not usually relevant to them but these new engineering and security standards will be. 

How might we validate early in a VFS or Platform team's development that they are building with the shared products that Platform provides and. engineering and security standards in mind? 

## OCTO OKR
O1.3: 100% of transactions received via our digital experiences are either processed correctly or we have notified the user of an error.

This effort is related to our Zero Silent Failure initiative. Staging review on the Engineering & Security track will be responsible, along with Staging Review on the Design track of Collab Cycle, for ensuring that new products do not create silent failures and that existing products have eliminated them or are on the way to eliminating any silent failure.

## Hypothesis or Bet
If we can validate that VFS and Platform teams are following engineering and security standards early, those teams will not waste cycles building out a product that does not follow the standards. 

## We will know we're done when... ("Definition of Done")

- [ ] VFS teams can easily understand Engineering standards
- [ ] VFS teams can easily understand Security standards
- [ ] Platform teams can easily understand Engineering standards
- [ ] Platform teams can easily understand Security standards
- [ ] The Engineering and Security Governance team can provide feedback to VFS and Platform teams early
- [ ] The Engineering and Security Governance team sees all technical projects before they go to production
- [ ] These touch points are worked into the collab cycle documentation 

We need teams to be able to find them and know the exist -- we want to give them something that they can take and use to judge their product. 

## Projected Launch Date
* We launched the Architecture Intent in October
* We hope to launch the Staging Review by the end of CY Q1 2025

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [Platform Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Configure your communication to teams about your work using the [Change Communication Guide](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide)
- [ ] Conduct a [go/no-go](https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

## Required Artifacts

* See the punch list for what we need to update

### Testing

* We're going to run a pilot with PatrickV in VES
* We're also going to pilot with the Veteran-facing Forms team
* Then we'll nominate some additional VFS teams to pilot with

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## AI Punch List

* [x] By 9/13 Don to work with Matt to shift questions in the Architecture Intent into the Kick-off ticket so Governance can determine if a VFS team needs to come to Architecture Review or not
* [x] By 9/17 Don to revise doc to mention zero silent failure strategy
* [x] By 9/17 Communicate to Shira that is is time to move what is required to provide at the Architecture Intent into the Collab Cycle Request ticket which is how VFS team discover which touchpoints we recommend they attend. Shira will update the Collab Cycle Request ticket template.
* [x] Allison to iterate on the flow diagram Governance has that helps them determine if the Architecture Intent is recommended (and then required or optional)
* [x] By 9/19 Matt to ask Shira to schedule SamR for the first Monday slot (or to communicate to Sam that he needs to go sign up his team)
* [x] By 9/16 Andrea to create touch point document in Confluence
* [x] By 9/16 Matt to create folder in sensitive team repo for arch intent docs to live.
* [x] By 9/17 update the Team of Teams slide
* [x] By 9/17 Shira will add Architecture Intent to Calendly - [Architecture Intent Calendly event](https://calendly.com/collaboration-cycle/architecture-intent?month=2024-09)
* [x] By 9/13 agree on Architectural Intent time slots
* [x] By 9/23 Shira and Andrea to discuss who is going to do the scheduling until a PM is added for the Engineering & Security track as well as whether we manage everything out of #platform-governance-team Slack channel or split the team into the 2 tracks we have.
   - Note from Shira 9/19: for now, Governance team can schedule via governance Slack channel. any confirmed Arch Intent meeting will be shared to #platform-collaboration-cycle channel and all folks involved in Arch Intent will be added to channel. 
* [x] Shira will propose new times. Turns out that Calendly limits us here and we have to have unique times that don't overlap with current day and time windows.
* [x] Give Shira the list of required attendees for Architecture intent so that you create an Oddball mailing list (Shira owns the distribution lists)

## Staging Review Punch List

- [ ] ~~Figure out available times for staging reviews — must not conflict with any other time in Calendly so we will probably need Shira’s help~~
- [ ] ~~Calendly set up - Will need Naomi/Shira’s help.~~
- [ ] ~~Update [Touchpoints doc](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints)~~
- [ ] ~~Adjust name of current staging review - Design Staging Review?~~

~~Write up docs for new staging review - Engineering Staging Review?~~
- [ ] 	~~Engineering Staging Review~~
- [ ] 	~~Engineering Staging Review - Scheduling~~
- [ ] 	~~Engineering Staging Review - Verifying artifacts and following up with VFS team~~
- [ ] 	~~Engineering Staging Review - During the meeting~~
- [ ] 	~~Engineering Staging Review - After the Meeting~~
- [ ] 	~~How to document findings for Engineering Staging Review~~
- [ ] 	~~We will want to work[ this document](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/1949696041/Conduct+a+Privacy+and+Security+Review) into the other documentation and retire that one.~~
- [ ] 	~~Move QA standards to Engineering Staging Review~~

~~Discussions/solutioning:~~
~~How might we make sure the discussion points from AI are addressed in the team’s staging review?~~

~~What do we want teams to fill out before they come to staging review?~~

~~Do we want to provide feedback the same way the teams do now for Staging review or should we make our own process and doc?~~

The above items are no longer relevant as we've decided to bring engineering and security into the existing Staging Review (alongside Governance) opposed to having a separate Staging Review. The punch/task list items are sub-issues to this initiative, and the proposed solution is below.

## Solution (as of 6/23/2025)

- Engineering and Security will be brought into the existing Staging Review, alongside Governance and the design, content, information architecture, accessibility, and quality assurance practice areas.
- Engineering and security will validate the same checklist (or questionnaire) at Architecture Intent and at Staging Review.
   - The current checklist is being modified to include both engineering and security questions. 
      - Need ticket
   - The current checklist will need to be renamed from "Architecture Intent Template) and moved (from va.gov-team repo to va.gov-team-sensitive repo)
      - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112130
- The number of available timeslots for Staging Review will be reduced from 4 a week to 2 a week.
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112128
- VFS teams will be asked to meet new requirements and follow new guidance for Staging Review. Engineering and security support will be needed for Governance to complete these tasks.
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112129
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112132
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112133
- Governance will continue to handle scheduling Staging Review meeting
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112131
- Governance will continue to handling hosting the Staging Review meeting
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112136
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112137
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112138
- Engineering and Security will need to define how they validate artifacts and how they provide written feedback to VFS teams within 4 day window leading up to Staging Review. Governance can assist with this work, but decisions can/should be made by security lead and supporting engineers.
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112134
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112135
      - Ideally engineers and security will create a pull request to the checklist/questionnaire to serve as the "feedback" ticket. We will need to have specific guidance to Platform side as well as specific instructions for VFS on how to handle the ticket.  
- Goal is to launch changes by July 11, and enforce changes in Staging Review by XX date.
   - https://github.com/department-of-veterans-affairs/va.gov-team/issues/112140

**Comment by humancompanion-usds** [comment]
## Requirements to start a new Collab Cycle

1. Fledgling Standards
2. Define the touchpoints
3. What are the assets teams need to produce at each touchpoint?
4. What type of changes need to come to this Collab Cycle?
5. What is launch-blocking at Staging?

### Goal: Pilot with Security 

* Goal is to pilot with Security after 8/1
* Security standards to be ready by 8/1
* AndreaH to PM the effort
* Current members of security team to create the security standards
* NOTE: Ray will be at officer candidate school in August
* Security standards to go on Platform content site
* Engineering tickets to be public but Security tickets to be private -- Jonathan wants to think more about how we do this
  * Networks maps shouldn't be public
* Agreed on the 3 minimum touchpoints:
  1. Architectural intent (optional but highly encouraged)
  2. Mid point review (optional)
  3. Staging review (required)
* Security has a list of questions that will be asked of teams for the first touchpoint.
* Assign a platform content person to work with Security folks on updating CollabCycle docs

**Comment by humancompanion-usds** [comment]
* Ragesh, Bill, Don, and Jeff met last week on what the cycle should be. Not going to be a PR review. Touchpoint on architectural changes to the platforms. 
* Going to come up with the architectural intent questions. [Don has a draft of that](https://github.com/department-of-veterans-affairs/va.gov-team/pull/87289). Bill has reviewed it. Jeff to review.
* What are going to do first for a pilot for the arch. intent?
  * Preview environments
  * PatrickV has a testing framework
  * User profile API (EVSS to PCIU)
  * Status project between Forms team and Auth. Exp. team
* Should have first pilot scheduled by 8/1
* Invite AndreaH to start PMing the effort
* Don to attend a Design Intent
* Engineering and security will share the architectural intent touchpoint
* Review time SLA will be 2 days. Trying to keep it a lightweight review.
* Structure the meeting
* Launch blocking at Staging remains to be done.
* Matt to add SteveA, AdrianR, Sanja, Sam Wiley, to the Mural board for Governance

**Comment by humancompanion-usds** [comment]
* Don continues to iterate on the Architecture Intent template
  * What do we have in terms of docs and what do we not have? 
    * Sidekick
    * Redis
* Jonathan has some additional initiatives for Security that we'll file and tackle
* Andrea to PM - Matt to reach out (Andrea has tentatively agreed to this meeting but hasn't attended yet)
* JonathanK: Document what should be done in a PR
  * JeffK: Platform is a bottleneck. Manual review of all PRs, given the scale, we need to automation.
  * Matt: Document what you expect to happen during PRs, at least keep a list, and what will be reviewed during Collab touchpoints.
* JeffK wants to use a project PatrickV has initiated as the pilot test for this process.
  * However, it is not also going through the Design side of Collab Cycle
  * Matt to reach out to Andrea and Jeff to find a time

**Comment by andreahewitt-odd** [comment]
Security standards still in flight 

Security short term goal: Shift left in touch points about security in collab cycle
Security long term goal: Expand our expectations for security across VFS/Platform teams.

**Comment by andreahewitt-odd** [comment]
Need to figure out the dates for Travel Pay

**Comment by andreahewitt-odd** [comment]
Goal is to get security and engineering standards done by the end of the first week of August (8th or 9th).

**Comment by andreahewitt-odd** [comment]
Let's connect Matt/Jonathan/Don/Jeff with Shira to provide a training on how feedback is provided in collab cycle -- Andrea owns this.

**Comment by andreahewitt-odd** [comment]
Use [Travel Pay ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79471) as the guinea pig for usability testing.

**Comment by andreahewitt-odd** [comment]
[Collab cycle info](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1278) for Travel Pay MVP.

**Comment by andreahewitt-odd** [comment]
Need to nail down time for windows for these reviews.

**Comment by andreahewitt-odd** [comment]
Draft of architecture Intent Meeting info: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md

**Comment by humancompanion-usds** [comment]
### Action items

* [ ] Matt to share the existing Collab Cycle slot times and we'll see if those work for folks and adjust accordingly.
* [ ] Jeff to reach out to PatrickV this week to see if he's okay with the initial conversation. Targeting the week of the 19th.
* [ ] Matt to ask if Shira can create the touchpoint issue (i.e. Architectural Review issue that manages the other issues)

### Notes

* Andrea and Jason are out this week. Ray is out 8/7-8/16. Jeff is out next week. Matt is out starting on 8/16.
* Shira provided the docs on how feedback is provided.
* We have the next 2 weeks to sort out the security part of Architectural Review.
* Jeff & Matt want to talk about staffing strategy when Andrea returns.
* Need clarity from Andrea when she returns on whether Identity team was asking to be a potential pilot team or whether they wanted to be a part of the review staff for the Engineering track.

**Comment by andreahewitt-odd** [comment]
First meeting for Architecture Intent meeting is 8/22 and the document is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md

**Comment by andreahewitt-odd** [comment]
From summary for 8/22 meeting:   *   We in VES are working on making veteran submissions traceable end-end across VA by instrumenting various systems to forward key events to Kafka, and from there to the CX Insights Data Warehouse where they can be aggregated/analyzed.
  *   VA.gov<http://va.gov/> is a key originating point for veteran submissions!
  *   We've talked with various folks like Steve Albers, Patrick Bateman, Bill Chapman and they are supportive of the idea of instrumenting vets-api in this way.
  *   Why FluentD? While we could have vets-api do a direct connection to Kafka, this would be a bigger implementation burden for teams, and a runtime dependency - what if Kafka is unavailable, is the logic for issuing an event the same from a controller as from a sidekiq job, what about retries, etc.
  *   Instead we want to source events from logs - this reduces the burden for app teams to "when something important happens, log a message with this specific format" (which we can provide a rails utility method to perform). FluentD can be configured to pick up only those log messages and convert them to Kafka events and they will flow where they need to.
  *   We have the healthcare application team ready to work on this, we just need to tell them what format of log message to generate, and then we need the FluentD-Enterprise Event Bus connection configured, presumably by platform.
  *   FluentD is in the TRM and had been used by platform as an approach for log forwarding in the past (when logs were going to Loki), I think they wound up not needing it when the switch to Datadog was decided upon.
Proposal Doc
Intentional Logging Proposal VA.gov.docx (<https://dvagov-my.sharepoint.com/:w:/r/personal/patrick_vinograd_va_gov/_layouts/15/Doc.aspx?sourcedoc=%7Bb09703bb-802b-4a1b-9ec6-3087ab7b5766%7D&action=view&wdAccPdf=0&wdparaid=143C6D6D>sharepoint.com<http://sharepoint.com/>)<https://dvagov-my.sharepoint.com/:w:/r/personal/patrick_vinograd_va_gov/_layouts/15/Doc.aspx?sourcedoc=%7Bb09703bb-802b-4a1b-9ec6-3087ab7b5766%7D&action=view&wdAccPdf=0&wdparaid=143C6D6D>

**Comment by andreahewitt-odd** [comment]
Moved the original arch intent test out so that the team could answer the security questions.

**Comment by andreahewitt-odd** [comment]
Andrea work with Clint to change the PR template to link to the kick off ticket (or a better artifact to show what the team is doing and why)

**Comment by andreahewitt-odd** [comment]
Potentially need to consider how to integrate this with SNOW and other VA communication management.

**Comment by andreahewitt-odd** [comment]
Let's all dive into figuring out what teams are using SNOW and how we could duplicate it.

**Comment by andreahewitt-odd** [comment]
Figure out who should be at arch intent based on the area the team presenting is working on. Work that into the flow so it's very clear what the process is and who needs to be invited to each meeting.

**Comment by humancompanion-usds** [comment]
* 2 pilots. Informal feedback is Arch. Intent is fine, about the right level of detail.
* Staging review is the next goal.
* Pick time slots for Architectural Intent.
* Create a script for AIntent. Andrea creating that.
* Set SLA of 2 business days for a response for a touchpoint.
* Need a note taker on the vendor side. KyleC is nominated.
* Goal is to announce in Team of Teams next week (9/17) and launch week of 9/23.

**Comment by andreahewitt-odd** [comment]
Updates from me: 

[Architectural Intent - During the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/edit-v2/3454238727?draftShareId=e7232f57-1c83-4910-b73a-1e3446497235)
Please read through this and make any adjustments needed. 

[How to document feedback for a Architectural Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3455156244/How+to+document+feedback+for+a+Architectural+Intent)
Please read through this and make any adjustments needed.


https://docs.google.com/presentation/d/1QK7ExtJ-iPlJg2Wlb6NxOJbZDabcJiVeNShywZxgD-s/edit#slide=id.g23db8d1d252_0_248
Add anyone or adjust any information you’d like on the slide. This is linked in the Architectural Intent - During the Meeting documentation. If we need to move it to Sharepoint, we can I just need to know where to put it. 

**Process items needed before launch:**
Update Collaboration Cycle Request ticket:
- Add Architectural Intent section
- Add Checkbox for each practice area

Create documentation for platform website:
- Draft
- Review
- Publish

**Comment by humancompanion-usds** [comment]
We have agreement on time slots. Here they are in order of most votes:

1. Monday at 4:30pm ET (4 votes)
2. Friday at 12:30pm ET (3 votes - Jonathan, Jeff, and Don)
3. Tuesday at 1:30pm ET (3 votes - Jonathan, Ray, and Don - Jeff will have to accommodate)
4. Thursday at 2:30pm ET (3 votes - Jonathan, Ray, and Jeff - Don will have to accommodate)

Let's go with these!

**Comment by humancompanion-usds** [comment]
I created a folder to hold the diagrams and dropped in a README: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/engineering/collaboration-cycle/architecture-intent/diagrams

**Comment by humancompanion-usds** [comment]
Architecture Intent touchpoint page created: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent

**Comment by humancompanion-usds** [comment]
@andreahewitt-odd and @jwoodman5 - We need two resources to support this effort:

1. Project Manager
2. Architecture and Data engineer

Here is a task breakdown:

### Project manager
* Run the calendar for the engineering and security track of Collab Cycle (which will expand to add Staging review touchpoint very soon). This includes managing Calendly, a shared calendar, holds for those conducting the review in their calendars. 
* Participating in Governance Office Hours

( more to come - forced reboot from my gfe)

**Comment by humancompanion-usds** [comment]
Talked today in a prioritization meeting that we'd hand-off from OCTO to a contract team to run this in March 2025 for both Architecture Intent and Staging review.

We talked earlier today about the punch list added to the initial comment to spin up the Staging Review touch point such that teams will be able to start attending in January 2025.

**Comment by humancompanion-usds** [comment]
Shira and I have hatched a plan to pilot combining the Staging reviews for both design and engineering & security into one touch point for VFS teams. This has some advantages:
* It keeps the scheduling simple - we just reuse the same time slots offered today
* Keeps it simple for VFS teams. No additional touch point for them to worry about.
* We would start by keeping the meeting at 30 minutes and just going through launch blockers. If there are no launch blockers the Governance team members will select the finding issues they want to highlight and ensure there is equal time for design and engineering & security.
* It's a shorter path towards getting engineering & security involved in Staging review

To get this going we need to do a few things:

* What do our engineers need to be evaluating once a team says they are production ready?
  * Engineers and security folks need to go through the current checklist we use at Architecture intent and evaluate if the team satisfied all of the items, then file issues when they have not. 
  * To do this we'll need some input from the folks doing these evaluations on what they need from teams that would help them with this task. At the moment, I believe that to be pointers from the VFS team on where they believe a checklist item to manifest itself (could be code, a datadog dashboard or monitor, etc.)
  * Security needs to evaluate the PSIRR and determine what should move into the Staging review and what can happen after shipping.
* Announce to VFS teams that they will need to be ready for both design and engineering & security review at the Staging touch point.
  * Governance is going to create documentation on what teams need to provide for their Staging review

**Comment by shiragoodman** [comment]
@va-albers @amo-va-octo @little-oddball please see Matt's comment above.

I'll be reaching out soon to discuss next steps for how we can begin to create an engineering staging review, alongside the existing design Staging Review. Please feel free to comment here if you have any immediate concerns or questions.

**Comment by humancompanion-usds** [comment]
We set a goal today of being able to start this pilot on 7/11.

**Comment by shiragoodman** [comment]
@kell-y @cmarion93 This is the list of actions I captured from our meeting today: 
- Determine what timeslots we want to cut
- Determine changes to SR requirements
   - Checklist needs to live in sensitive repo
- Determine who we need to invite to the SR from eng and sec
- Determine what changes need to be made to the SR artifact list 
- Add a task for Governance to verify checklist is included from VFS team
- Updates Staging Review touchpoint page
- Determine what the validation process is for eng and security in 4 day window
- Do we want to use the pull request process for documenting eng and sec concerns at Arch Itnent and SR?
- Add eng and security to SR Slide
- Modify SR script to include eng and security
- Determine new flow for SR meeting - how will we deliver our findings to VFS teams?

**Comment by shiragoodman** [comment]
Notes from standup 6/23:

- Andrew to check in with Steve on existing Arch Intent questions to see if improvements are needed.
- We might need to inform teams of Engineering Office hours - when are they? Shira to connect with Andrew on this.
- Shira shared her proposal to use pull requests on the checklist/questionnaire as an MVP solution for providing written feedback to teams. 
   - We assume VFS teams will want something in writing. We want to make sure we have recommendation vs. firm requirement with regards to our feedback.
      - Shira shared the Governance teams [Must, Should, and Consider Framework for Feedback](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). This is the framework Governance team uses when providing feedback to VFS teams at Design Intent and Midpoint Review.
      - [Example Design Intent feedback tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue%20state%3Aopen%20label%3Acollab-cycle-feedback%20label%3Adesign-intent), [Example Midpoint Review feedback tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue%20state%3Aopen%20label%3Acollab-cycle-feedback%20label%3Amidpoint-review)
   - Shira will create example of how a pull request could be used to document feedback for VFS teams at Arch Intent and Staging Review

**Comment by shiragoodman** [comment]
Standup agenda 7/14:

- Requested feedback on 7/8 for the new Engineering and Security Checklist
- Plan to skip making changes to Staging Review Requirements (via ticket [#112129](https://github.com/department-of-veterans-affairs/va.gov-team/issues/112129)) for time being
- Updates to touchpoint pages (Architecture Intent and Staging Review) planned for this sprint
- Updates to code blocks (Architecture Intent and Staging Review) in Collaboration Cycle Request ticket planned for this sprint
- New ticket: #114230 
- Still need to define process for sec and eng to follow at Arch Intent and Staging Review (re ticket #112135 )

**Comment by shiragoodman** [comment]
@jwoodman5 we still have some post-launch tasks that we need to complete, including deprecating PSIRR. I am reopening this. LMK if you'd like to discuss.

**Comment by humancompanion-usds** [comment]
## Key Results (KR) Assessment & Recommendations

**Current KR Status:** ⚠️ **WEAK MEASURABLE OUTCOMES**

### Issue Identified:
This initiative has a comprehensive definition of done focused on process establishment, but lacks specific, measurable key results to assess the impact and effectiveness of the new Engineering & Security governance track.

### Recommended Key Results:

**KR1: VFS Team Coverage & Compliance**
- **Metric:** All active project teams complete an Engineering and Security staging review and 80% receive recorded feedback by end of FY26 Q1
- **Measurement Plan:** Track staging review completion rates via governance project dashboard (https://github.com/orgs/department-of-veterans-affairs/projects/998/views/1)
- **Current Status:** Successfully launched August 4, 2025; process operational

**KR2: Silent Failure Elimination**
- **Metric:** Zero silent failures recorded in FY26 Q1
- **Measurement Plan:** Track and monitor silent failure incidents across all teams that have completed Engineering & Security staging review
- **Data Source:** Silent failure tracking systems and incident reports
- **OCTO Alignment:** Directly supports FY25 1.3 (100% correct processing/error notification)

**KR3: Review Process Efficiency**
- **Metric:** Average staging review feedback resolution time <4 business days
- **Measurement Plan:** Track time from staging review completion to VFS team issue resolution using governance dashboard timestamps
- **Current Challenge:** Engineering/security findings are in kick-off issue comments (measurable but requires comment parsing)

### OCTO OKR Alignment:
Directly maps to **FY25 1.3** (100% correct processing/error notification) as this initiative ensures new products don't create silent failures and existing products eliminate them through enhanced engineering and security oversight.

### Measurement Infrastructure:
- **Primary Dashboard:** https://github.com/orgs/department-of-veterans-affairs/projects/998/views/1
- **Data Collection:** Kick-off issue comments contain engineering/security findings
- **Process Improvement Opportunity:** Consider structured finding templates for easier tracking

### Next Steps:
1. Establish silent failure tracking baseline and monitoring systems
2. Develop comment parsing methodology for engineering/security findings
3. Enhance governance dashboard to better track findings categorization
4. Schedule 6-month effectiveness review and KR assessment

cc: @humancompanion-usds
