### ISSUE TITLE
Usability Testing Prep: GIBCT Estimate Your Benefits

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#8675]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager / Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/product-outline.md)
- Link to prototypes (Testing will be conducted on staging - updates are underway. Here are prototypes that show the UI)
  - [IHL Desktop](https://bahdigital.invisionapp.com/share/J5IADLE7CEF)
  - [IHL Mobile](https://bahdigital.invisionapp.com/share/3XIADLG2GJD)
  - [OJT Desktop](https://bahdigital.invisionapp.com/share/74IADLI2G58)
  - [OJT Mobile](https://bahdigital.invisionapp.com/share/Z9IADLWBV7U)
  - [VET TEC Desktop](https://bahdigital.invisionapp.com/share/EFIADM08NJA)
  - [VET TEC Mobile](https://bahdigital.invisionapp.com/share/D9IADLYPTBC)

- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/research/research-plan.md) and [script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/research/discussion-guide.md)  
- [Link to test cases/test plan in TestRail](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8675)

- Link to regression test plan:  
The “regression” that we would be testing for is making sure all the calculator fields still update the estimations the way they did before. Since we’re really updating how this whole section works, we already covered that in the test cases for the stories. 

## Meeting attendees from **requesting team**
- Product Manager (required): **Darrell Neel**
- DEPO product lead (required): **Matt Self**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Amy Knox, Jen Jones, Cindy Cruz, Will McCormack, Michael Delli-Gatti, Adam Sonntag**

## Scheduling
Preferred dates or times: Wed., May 6, 11:30am

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by meganhkelley** [comment]
Scheduled for 5/6

**Comment by CrystabelReiter** [comment]
This looks good from the VSP design side, no feedback needed.

**Comment by peggygannon** [comment]
This looks good from VSP content side. No additional feedback.

**Comment by dneel-bah** [comment]
Closing this issue as all linked issues have been addressed.
