### ISSUE TITLE
674 | Trigger for In-Progress Email

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#86755]
## Issue Description
_As a Veteran, I need to receive a "submission in-progress" email when I submit a claim on VA.gov._

## Resources
- [VA Notify Platform Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes)
- [VA Notify GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify)
- [VA Notify Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/VA%20Notify%20Playbook.pdf)
- [API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#reviewing-our-api-docs)
- [Completing the "create trigger" tickets](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Strike/Completing%20Trigger%20Tickets/create_trigger.md)
- [Forms Strike Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/form%20confirmations) can assist with setting up a confirmation email trigger
- **Template ID:** 574cee6d-ddd3-42ca-83a4-8c4032549976

---
## Tasks
- [ ] Build notification code to call the VA Notify API
   - [ ] Notification should trigger an email when a claim is submitted on VA.gov
   - [ ] The default email address should be the email the user entered into the form. If no email exists within the form, use their MyVA profile email.
- [ ] Test notification by logging into staging with a test user, updating the profile ID to something that sends to you
- [ ] Determine alerting and error handling if email fails to deliver

## Acceptance Criteria
- [ ] A notification trigger that sends an email to claimant when their claim is submitted on VA.gov
- [ ] Logging and monitoring for failed sends
