### ISSUE TITLE
Implement emoji response workflows for Kickoff, DI, MPR and SR

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#86769]
## User Story
As a Governance team member, I want to set up the emoji response workflows in Slack for DI, MPR and SR so that we can define and edit our new workflows for future VFS team use.

Assignee: @briandeconinck
Peer Reviewer: @shiragoodman

## Description
In ticket #84492, Governance team proposed 2 possible solutions for how we might initiate touchpoint scheduling workflows for Collaboration Cycle. We decided on the emoji reaction solution, which allows us to add a specific emoji to the Calendly notification post on Slack in order to initiate the workflow associated with that specific emoji. The same decision was made for ticket #84494 re: kickoff.

The purpose of this ticket is implement the 4 specific workflows for kickoff, DI, MPR and SR within the Governance team Slack channel (#platform-governance-team).

Note: This ticket only includes implementation of the 4 workflows. It does not include updates to Governance team guidance or testing the new workflows with VFS PMs.

## Impacted Artifacts
No existing artifacts impacted in this ticket. Four new Slack workflows created.

## Tasks
- [x] Identify if new information would need to be requested in Calendly
   - Determined that no new information is needed from Calendly.
- [x] Create emojis for:
   - [x] Kickoff
   - [x] Design Intent
   - [x] Midpoint Review
   - [x] Staging Review
- [x] Create new workflows for:
   - [x] Kickoff
   - [x] Design Intent
   - [x] Midpoint Review
   - [x] Staging Review

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have created specific emojis in Slack for the 4 Collab Cycle touchpoints
- [x] We were able to successfully implement the Kickoff emoji reaction workflow
- [x] We were able to successfully implement the Design Intent emoji reaction workflow
- [x] We were able to successfully implement the Midpoint Review emoji reaction workflow
- [x] We were able to successfully implement the Staging Review emoji reaction workflow
- [x] We were able to test all 4 workflows internally with Governance team 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
End-of-sprint update: Unplanned ticket picked up mid-sprint and is carrying over into the next sprint. Workflows complete for Kickoff and Design Intent. Should wrap up Midpoint Review and Staging Review early next week after the holiday and Friday PTO. Will be presenting to the Governance team at the weekly initiative meeting on Monday.

**Comment by briandeconinck** [comment]
@shiragoodman Ready for review! All four workflows are in place and available in the Governance channel, with the language and form edits recommended at the Monday weekly initiative meeting. You should be able to test them on any test post with the `:cc-kickoff:`, `:cc-designintent:`, etc. emojis. Let me know if you have any questions!

**Comment by shiragoodman** [comment]
@briandeconinck - I tested the happy paths for all 4 touchpoints (including both sync and async for MPR) and everything looks good! The only comment I have, which is very minor, is that kickoff is the only workflow where the VFS team, product and feature name is italicized. That doesn't happen in the DI, MPR or SR flows.

Great work!

**Comment by briandeconinck** [comment]
Closing as complete!
