### ISSUE TITLE
SC | Update 4142/4142a submission

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#86760]
## Value Statement

**_As a_** Decision Reviews Team member
**_I want to_** update our 4142/4142a form to use the latest document
**_So that_** that VBA will accept these forms

---

## Background Context

For our Supplemental Claim (Form 0995) form, we collect 4142/4142a data. And upon submission, our backend uses the same endpoint as 526EZ to build 4142/4142a as a PDF ([based on this version that expired in 3/2021](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/pdf_fill/forms/pdfs/21-4142.pdf)) which we then submit to directly to central mail.

The simple forms team has already built a stand-alone form 4142/4142a, and so instead of updating the backend code to fill out a newer PDF for submission to Central mail, we should use that same simple forms endpoint to submit the form using either the frontend, or backend.

## Acceptance Criteria

- [ ] Supplemental Claim submits the newest 4142/4142a form
- [ ] Update backend & frontend tests
- [ ] Update 4142/4142a OMB info in the 0995 form

## Out of scope

- Update existing backend 4142/4142a code which we share with form 526

## Open questions

- How do we know which 4142 (we need to show the expiration date) the simple forms team is submitting? 

## Tasks

- [ ] Determine how to use the simple forms 4142/4142a endpoint (find swagger docs)
- [ ] Evaluate FE & BE to determine where to actually submit the form
- [ ] Update tests
- [ ] Update OMB expiration date & burden time in Supplemental Claims

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
This ticket has been replaced by #85680
