### ISSUE TITLE
Content Updates - Accordions, Verbiage, Links for Yellow Ribbon

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8677]
Content Updates to Apply to Yellow Ribbon initiative, to make final updates to the Yellow Ribbon page so that we can finalize the initiative and launch

These changes are intended to go to staging as soon as ready, and then would roll to Production *after* the Tool is made available on production & verified.
---
## Tasks
- [ ] Content to create content and prompts to guide users
- [ ] Pull in search results currently living on legacy benefit.va.gov pages, and linked to from accordions on main YR page
- [ ] Remove state accordions from Yellow Ribbon page (https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/)
 - [ ] Update verbiage on URL at the bottom of the Do I qualify... box on the YR page (https://gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/)
 - [ ] Link to tool with contextual content where the accordions are
 - [ ] Add to left navigation on Education pages
- [ ] Include link and contextual content to tool on:
* GI Bill Benefit page
* GI Bill Comparison Tool landing page
* Add link and contextual content under More information + resources on va.gov/education

**Comment by stephorkandatx** [comment]
Invision at https://vsateams.invisionapp.com/share/P4W04QPWHTK#/screens/406250516/comments

**Comment by stephorkandatx** [comment]
Copy at (https://app.zenhub.com/files/133843125/95f5100c-ed99-4286-ad95-a7cdb753dcaa/download)

**Comment by stephorkandatx** [comment]
@DanielleThierryUSDSVA & @AnneHurley This ticket is lifted from the longer list of launch items at #6691. Please review and sync on what remains and anything we need to list out in detail so that we can action on this ticket as we get closer to launch. Thank you!

**Comment by AnneHurley** [comment]
@ncksllvn or @kelsonic  -- Can one of you help me with getting a link teaser onto the GI Bill Comparison Tool page.

We don't yet have the link to the Yellow Ribbon finder page, so not sure if you can do anything with this yet, or perhaps you can use some kind of placeholder URL. 

For this page:
https://www.va.gov/gi-bill-comparison-tool/

In the right-hand rail list of links, let's make it the top link:
<Find a participating Yellow Ribbon School> -- links to new school finder page.

**Comment by AnneHurley** [comment]
Awhile back, @andaleliz, @jenniferlee-dsva and I discussed a little revamp of the right rail links on the GI Bill comparison tool page. Currently it looks like this:
![GI Bill Right Rail]
(https://images.zenhubusercontent.com/5c6313e20f871b64caae9909/837146b4-3e3b-4284-be5e-8ad4ef6a9d59)

We'd discussed reordering the links while we are adding a new one to the YR tool. I would suggest:

- Apply for education benefits
- Get help choosing a school
- Learn about the Yellow Ribbon program [[[link to the main YR page]]
- Find a participating Yellow Ribbon school [[[link to our new tool page]]
- Get started with CareerScope
- Submit a complaint through our Feedback System

This way all the education related ones are at the top, in order of how you might need to tackle them; then career scope, then submit a complaint. What do you think?
@DanielleThierryUSDSVA and @stephorkandatx  FYSA

**Comment by AnneHurley** [comment]
And general content strategy question related to ^above comment. Right now this list says to add just a link to the YR search tool, which I'm doing. But I feel like we should link to the main YR page in those instances too - "Learn about..." and then "Find a ...." - so that "Find a..." isn't alone without the context of the main page. @DanielleThierryUSDSVA @peggygannon What do you think?

**Comment by jenniferlee-dsva** [comment]
I can answer the last question in the ^ ticket: `Question: Where have we landed on historic rates?`
Two chunks:
1/ 2019-2020 school tables -  we will redirect to the tool itself. (ETA TBD by release plan and Mikki's redirect ticket. It can happen during release or shortly after tool is fully live.)

2/ 2018- and prior year table pages - we will not link to these and we will not redirect these.

**Comment by ncksllvn** [comment]
I opened a PR for adding the link to the GIBCT - https://github.com/department-of-veterans-affairs/vets-website/pull/12524. How do we want to do this? Just keep it pending until we're ready to launch YR, or a feature flag of some sort?

**Comment by ncksllvn** [comment]
There are also links under `Additional Resources` on the VET TEC profiles - https://www.va.gov/gi-bill-comparison-tool/profile/2V000125/JAVA%20FULL%20STACK%20SOFTWARE%20DEVELOPER - in case we want to add a link there too

**Comment by AnneHurley** [comment]
Anne to:

- Reach out to Matt Self about adding a link to the YR tool to the GI Bill Comparison tool in right rail, and suggest a reordering of the current links if they are amenable
- Add the tool URL -- **www.va.gov/education/yellow-ribbon-participating-schools**  -- to all the pages in the checklist 
@jenniferlee-dsva @stephorkandatx  FYSA

**Comment by AnneHurley** [comment]
@peggygannon Here are the pages with contextual copy and links to the new tool, for your review:
1. **Main Yellow Ribbon page**: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/ -- Copy will stay the same in the bottom of the blue "do I qualify box" but now will link to the tool
2. **Main Yellow Ribbon page**: state accordions removed and replace with wording directing people to the tool. Top sentence will have link to new tool. Second sentence is to GI Bill CT: preview-prod.vfs.va.gov/preview?nodeId=936
3. **GI Bill Comparison Tool page**: https://www.va.gov/gi-bill-comparison-tool/ -- Have reached out to @mattpointzxer0 with our request to add two links to right rail (to Yellow Ribbon program info overall and to search tool) as well as a suggested reordering of the links.
4. **GI Bill Benefits page**: prod.cms.va.gov/node/1009/edit
5. **Main education hub,** add link + text under more resources: prod.cms.va.gov/node/71/edit
@jenniferlee-dsva and @stephorkandatx FYSA

**Comment by peggygannon** [comment]
@AnneHurley I have a question about an edit on preview-prod.vfs.va.gov/preview?nodeId=936

Can users no longer search for Yellow Ribbon schools using the GI Comparison Tool? 

on the current page, we say users can search for YR school using the GICT ... Will this no longer be the case with the launch of the new YR tool?

**Comment by peggygannon** [comment]
Hello, @AnneHurley 
I've reviewed the YR pages in Drupal and made content updates to. Please let me know if you have any questions. Thx! 

--Main Yellow Ribbon page: preview-prod.vfs.va.gov/preview?nodeId=936

--Education landing page: prod.cms.va.gov/node/71/


cc @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@AnneHurley The Drupal pages looks all right though just want to make sure there is an item on a checklist somewhere that we will switch out the links to the new tool page instead of the main YR page.

@peggygannon We need to make one copy change on staging—remove the period at the end of the "Find out if you qualify for the Yellow Ribbon Program" link. Can you do this?

**Comment by AnneHurley** [comment]
@RLHecht  Good idea, I'll make a checklist with all the prod links, that need to have the YR URL added.

The YR URL is: www.va.gov/education/yellow-ribbon-participating-schools

**Comment by AnneHurley** [comment]
@mattpointzxer0  Here is the text and the 2 links we'd like to add to the GIBCT right rail:

1. URL of main Yellow Ribbon page: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/
Link text: Learn about the Yellow Ribbon Program

2. URL of the search tool: www.va.gov/education/yellow-ribbon-participating-schools
Link text: Find a Yellow Ribbon school
@peggygannon and @RLHecht  FYSA

**Comment by peggygannon** [comment]
@RLHecht Yes, regarding removing the period from that line of text...I believe @kelsonic has an open PR for updates to the tool,  and we could make that change in that PR.

**Comment by AnneHurley** [comment]
Pages to update with live YR URL:
**1. Main Yellow Ribbon page:** https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/ -- Copy will stay the same in the bottom of the blue "do I qualify box" but now will link to the tool
**2. Main Yellow Ribbon page:** state accordions removed and replace with wording directing people to the tool. Top sentence will have link to new tool. Second sentence is to GI Bill CT: preview-prod.vfs.va.gov/preview?nodeId=936
**3. GI Bill Comparison Tool page:** https://www.va.gov/gi-bill-comparison-tool/ -- Have reached out to @mattpointzxer0 with our request to add two links to right rail (to Yellow Ribbon program info overall and to search tool) as well as a suggested reordering of the links.
**4. GI Bill Benefits page:** prod.cms.va.gov/node/1009/edit
**5. Main education hub, add link + text under more resources:** prod.cms.va.gov/node/71/edit

**Comment by stephorkandatx** [comment]
Thanks @AnneHurley . @RLHecht please let us know when you review thanks!

**Comment by RLHecht** [comment]
@AnneHurley @stephorkandatx I published the changes on:
- Main YR page
- Main GI Bill page
Main education hub

Anne is checking if the link should be going on the Post-9/11 GI Bill Benefits page or the Post-9/11 GI Bill Benefits Rates page, or both.

**Comment by AnneHurley** [comment]
@RLHecht I've added a link to the tool, under the first mention of YR, on Post-9/11 GI Bill (Chapter 33) page:  http://preview-prod.vfs.va.gov/preview?nodeId=935

Ready for your review.
The addition to the rates page isn't on our checklist, so we don't need to include one there. I did, coming out of our updating all the GI Bill pages, since that page seems to be the full list of all the $/resources someone can get. But I agree, the page is already long, so if we decide not to add it there, that's fine.
^this page ready for your review. Then we should be good on all the pages linking to the tool.
@stephorkandatx FYSA

**Comment by RLHecht** [comment]
Published the Post-9/11 GI Bill page. We missed today's deploy so we should be able to validate tomorrow afternoon.

**Comment by RLHecht** [comment]
@stephorkandatx New links on the four education pages are live.
