### ISSUE TITLE
Usability test emoji response workflows with VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#86775]
## User Story
As a Governance team member, I want to test the new emoji response flow with VFS teams so that we can address any concerns or issues teams have before formally launching the changes.

Assignee: @briandeconinck
Peer Reviewer: @erinrwhite

## Description
In ticket #86769 we implemented 4 new workflows that only work on the #platform-governance-team Slack channel for initiating scheduling of DI, MPR and SR, and for completing tasks associated with the Kickoff. We have tested the workflows internally, but now would like to test them with actual VFS teams. 

Shira has already shared in Team of Teams that Governance team will be seeking VFS teams help in testing the new workflows. The goal would be to have VFS teams follow the new process (aka completing the 1st step, which is scheduling in Calendly, but no longer completing the workflow step) and then share with us their feelings about the new experience. This could be completed informally with a short Optimal Workshop Survey, or even via Slack.

The purpose of this ticket is to test the new workflows with VFS teams and collect feedback from the VFS team on the new workflows. We will not be putting together a formal research plan.

## Impacted Artifacts
- [Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3301507204/Research+Plan+for+usability+testing+of+emoji+response+workflows+with+VFS+teams)
- Slack workflows (under Slack left menu bar > More > Automations > Managed By Me)
   - CC Kickoff
   - CC Design Intent
   - CC Midpoint Review
   - CC Staging Review

## Tasks
- [x] Determine how we should collect feedback from VFS teams
   -  Open feedback?
   -  Scale of 1-5?
   -  Via Slack (not anonymous) vs. via Optimal Workshop? 
   - **Decision:** Survey conducted via "CC Feedback" Slack workflow triggered at the end of the emoji response workflows.
- [x] Confirm communication plan for announcing at Team of Teams (aka how we'll recruit) to Shira
   - Shared quick-and-dirty plan with Shira

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have tested the new kickoff workflow with at least 1 VFS team
- [ ] We have tested one of the new touchpoint scheduling workflows with at least 2 VFS teams
- [ ] We have validated that the touchpoint scheduling workflow is the same for all three touchpoints (except content)
- [ ] We have collected feedback from at least 4 VFS teams on the new process. 

## Team Notification
- [x] Slack post on #platform-governance-team (share results)
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
[Quick and dirty plan to test our new workflow](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3301507204/86775+-+Usability+test+emoji+response+workflows+with+VFS+teams). Would love some thoughts @erinrwhite and @shiragoodman!

**Comment by shiragoodman** [comment]
I provided my feedback. Looks good, Brian! There were a couple areas where I think we could expand a bit. I'm interested to hear Erin's thoughts too.

**Comment by erinrwhite** [comment]
@shiragoodman @briandeconinck This looks good! +1 to Shira's recommendations. I really like the idea of following up with teams who forget to use the `Collab Cycle` command to invite them to test the workflow.

**Comment by briandeconinck** [comment]
@shiragoodman Messaging for VSF PMs is updated, and the doc is in the Research section of Confluence. I've also added the triggers for the feedback Slack workflow, so we should be good to go!

**Comment by erinrwhite** [comment]
Looking good from here! @briandeconinck

**Comment by shiragoodman** [comment]
thanks, Brian!! glad to hear it

**Comment by briandeconinck** [comment]
End-of-sprint update: Work on our end is complete, but ticket is staying open until we've had VFS teams test each workflow. Carrying into the next sprint.

**Comment by shiragoodman** [comment]
since we haven't been able to test the DI, let's just validate that the workflows are consistent across DI, MPR and SR, with the exception of content.

**Comment by briandeconinck** [comment]
We've received unanimously positive feedback and verified that all of the workflows are equivalent to the ones that have been tested. Per team discussion, closing as complete!
