### ISSUE TITLE
ITF not found in staging

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#86771]
## Issue Description
Existing ITF not found in staging environment.
To reproduce:
1. user 220 - had an in-progress 526 form which I accessed from MyVA.
2. Select continue application (not start a new application).
3. This is the ITF message received next:
<img width="1229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2VKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--510610bf899b405e1c7f60825855f33003097c1d/image%20%2820%29.png" alt="image (20).png" />

It should have found an existing, valid ITF and not created a new one... the messaging says the ITF expired on June 10, 2025, which is in the future.

---
## Tasks
- [ ] Reproduce bug following steps above

## Acceptance Criteria
- [ ] Determine if there is a fix the 526 teams can implement or contact platform for support.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
