### ISSUE TITLE
Fix `transformForSubmit` Function to Not Strip Out "Report a Divorce"

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#8678]
## Description
There is an issue when submitting the 686 to the back end that is causing the data for the "Report a Divorce" workflow to be stripped out of the payload. We tested and it seems like the issue is coming from the default `transformForSubmit` function. We need to create a custom function to pass into the `transformForSubmit` that does not strip the data out.

## Tasks
- [x] Research why the default `transformForSubmit` function is stripping the "Report a Divorce" data
- [x]  Build a custom submit function that does not strip the "Report a Divorce" data out

## Acceptance Criteria
- [ ] The "Report a Divorce" data is not stripped out of the submitted data to the back end
