### ISSUE TITLE
Toxic Exposure 1.1: Remove unused includeToxicExposure flag 

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#86798]
## Overview
Once vets-api changes are completed and deployed to replace the `includeToxicExposure` flag in favor of `startedFormVersion`, update vets-website to remove any references to the old flag

## Tasks
- [x] Remove FE logic to look for old flag
- [x] Unit and e2e tests updated to remove old flag

## Acceptance Criteria
- [x] TE pages continue to display for new applications (started version 2022)
- [x] TE pages continue to display for IPF forms with logic enabled (started version 2019)
- [x] TE pages do not display for IPF forms not enabled (not the chosen ones)
- [x] TE pages do not display for new applications not enabled (not the chosen ones)
