### ISSUE TITLE
[FE] SPIKE - don't refresh old sessions

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#86797]
## Description
After a patient completes check-in or pre-check-in, it is common for them to close their browser and continue on with their life. The next time they use their mobile device's browser, our app wakes up and tries to refresh data, this causes the app to not be able to fetch data due to the non-existent LoROTA entry, and it eventually resolves to the error page.

This is not a great user experience plus it also logs errors for the the failed api requests.

This spike is to investigate ways to mitigate this problem. One idea is to set a timestamp in session along with the complete status. Then we can decide to not try to refresh data if complete was set x amount of hours ago. Instead of refreshing we could send the suer to the homepage or a generic "your done" type of page.

[slack convo](https://dsva.slack.com/archives/C02G6AB3ZRS/p1719232940187839)

## Tasks
- [x] [FE] Research the issue
- [x] [FE] create POC
- [ ] [FE] discuss solution with team
- [ ] [FE] write follow up tickets
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
These are the resulting tickets:
[FE](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87499)
[UX](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87509)
