### ISSUE TITLE
Conduct Research Study for Timely and Truthful Submission (526 Submission Status Evaluative Research)

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#86806]
## Issue Description

This ticket represents the work of running 5-7 sessions of the upcoming research study (526 Submission Status). This evaluative research will assess the clarity of the proposed submission model to see if Veterans have accurate expectations for the timeline in the days following submission. 

### Research Goals
1. Evaluate how effectively the submission model sets clear expectations for claim submission timeline.
2. Evaluate if submission touchpoints are timely and useful for Veterans.
3. Generate ideas for the next design milestone to improve the claim record.

### Impact to the Veteran
As a result of this work, Veterans have clarity on their claim status in the days following submission.
Research findings will inform the changes we make to the submission model as communicated through the confirmation page and emails. Insight learned about claim record and tracking will drive the next phase of design. 

### Relevant material 
1. [Link to research folder in Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/2024-07-Submission-Status)
2. [Note-taking guide in Google Sheets](https://docs.google.com/spreadsheets/d/1aLcrsj2iVmFcxzVi11X6fruCcQTPBjsgVvj3ayOVtf0/edit?gid=555217803#gid=555217803)
3. Enjoy HQ [link forthcoming]

## Tasks

- [ ] Moderate and note take 5-7 research sessions (60 min max each)
- [ ] Manage sign-up sheet and slack backchannel 
- [ ] Clean up notes
- [ ] Upload videos to Sharepoint 
- [ ] Upload videos to Enjoy HQ
- [ ] Collect key findings from observers/notetakers

## Acceptance Criteria 

- [ ] Research sessions are complete
- [ ] Data is managed and ready for synthesis

**Comment by mengA6** [comment]
I think this duplicates [Run Recruitment for Research Study ["Veterans have clear expectations on claim status" study]#85869](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85869)

**Comment by evelynhilbrichdavis** [comment]
Synthesis will take place in the google sheet [as well as in this Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720708456061/7a6257427af05587cdbb03d6bf42d5b7fc4b6b4b?sender=u56bc6ddb4215a92830844228)

**Comment by evelynhilbrichdavis** [comment]
Perigean has scheduled another session for Monday in case one of our remaining two participants cancel today. We are currently at P=4 and need to get to P=6 for the study to close.

**Comment by evelynhilbrichdavis** [comment]
Finished 8 sessions today. All audio is uploaded to Enjoy HQ. Once @mengA6 has all audio/video/transcript on Sharepoint he can close this ticket.

**Comment by mengA6** [comment]
I had all the video recordings and just added audio recordings from EnjoyHQ into [the sharepoint folder](https://dvagov.sharepoint.com/:f:/s/vaabdvro/EgClpik4g09KuYCp4wHSt3MBWhQmME18pi_w3OipVD6FNw?e=Nfdo6e). Sharepoint auto generated transcripts from the video files, so you can view them alongside the video files in Sharepoint. Sorry I didn't get the transcripts directly from zoom before they were removed.
