### ISSUE TITLE
[DevOps] Remove LoROTA Cleanup Lambda and schedule.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86812]
## Description
Replaces #83454.

Per this:
- https://dsva.slack.com/archives/C04G3EY2F5W/p1686543809242819
- https://dsva.slack.com/archives/C038C047X2P/p1681476474614209

the existing Cleanup Lambda is not useful and has no reason for existing, and creates some log spam each and every day.

## Tasks
- [x] [DevOps] Remove references to Cleanup Lambda from CloudFormation and Terraform templates.
- [x] [DevOps] Remove Cleanup Lambda and any tests from codebase.
- [x] [DevOps] Preview CloudFormation plan; are there any other unexpected changes resulting from drift?
- [x] [DevOps] If not, apply CloudFormation changes on lower environments.
- [x] [DevOps] Consider how to move forward on production; should we just disable the cleanup lambda? Applying the CF is scary at this point. Probably discuss with Brian, John, Gaurav, and Kanchana.

## Acceptance Criteria
- [x] The Cleanup Lambda does not run in `vaec-cms` on any environment.
- [x] The Cleanup Lambda does not run in `vaec-cie` on any environment.
- [x] The Cleanup Lambda is removed from the codebase and IaC.

**Comment by ndouglas** [comment]
Created a dashboard [here](https://tevi.ddog-gov.com/dashboard/zx7-mfc-yzw?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1719409453319&to_ts=1719413053319&live=true) I can review to monitor whether there is an unanticipated growth in item count because of these changes.

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/312ec981-c047-4bf3-8f6d-b6e5a3a3d333)

**Comment by ndouglas** [comment]
Posted comment in Slack here [1], disabled the Amazon EventBridge rule (`LoROTA_scheduled_cleanup_prod`) that triggers the Lambda. Now we wait 😎 

[1] https://dsva.slack.com/archives/C04G3EY2F5W/p1719414180003349

**Comment by ndouglas** [comment]
No apparent ill effects as of yet.

**Comment by ndouglas** [comment]
This is merged, has been live on staging, and there're no signs of trouble. Prod deploy is pending 🤷🏻‍♂️
