### ISSUE TITLE
[DevOps] Propose transferring `octo-vista-api` into Check-In Experience's control.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86814]
## Description
Per [this Slack thread](https://dsva.slack.com/archives/C06LVA4NGFM/p1718983864561379?thread_ts=1718980593.106289&cid=C06LVA4NGFM), and after further discussion with Stephen Barrs, it does appear that the Check-In Experience is responsible for the Vista API cache and that it is important to multiple teams, ours and others. I think that implies that we need to have ownership of this repository.

As we did with `checkin-devops`, we need to transfer this repository into our control so that we can maintain it moving forward.

## Tasks
- [x] [DevOps] Propose transferring `octo-vista-api` into Check-In Experience control.

## Acceptance Criteria
- [x] `octo-vista-api` is under Check-In Experience control or the idea has been rejected.
- [x] If control was transferred, repo is added to list of PCI responsibilities in va.gov-teams documentation.

**Comment by ndouglas** [comment]
Posted a message in Slack here: https://dsva.slack.com/archives/C051S52N1C6/p1719419190484539
