### ISSUE TITLE
Research and re-submit failed submission

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#86836]
# Overview
There was a failed submission over the weekend that errored out:

`{"data":{"id":"d10d3dc5-9dfb-4f8f-8a3b-246d0a0f7381","type":"document_upload","attributes":{"guid":"d10d3dc5-9dfb-4f8f-8a3b-246d0a0f7381","status":"error","code":"DOC202","detail":"Upstream status: Unidentified Mail: We could not associate part or all of this submission with a Veteran. Please verify the identifying information and resubmit.","location":null,"updated_at":"2024-06-21T13:47:09.990Z","uploaded_pdf":{"total_documents":6,"total_pages":13,"content":{"page_count":8,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":712202,"attachments":[{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":1777412},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":2255230},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":1816883},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":246289},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":209390}]},"line_of_business":"PMC"}}}}%`

https://vagov.ddog-gov.com/logs?query=%40named_tags.dd.env%3Aeks-prod+%40payload.to_state%3Afailure+%40payload.form_type%3A21P-527EZ&from_ts=1718949600000&to_ts=1719028938000&live=false&agg_m=count&agg_t=count&index=%2A&source=monitor_notif

According to the API Intake Channel:

>  the Unidentifiable Mail error is generated after folks in the intake process verify that they can't locate a veteran using the information provided in the submission. In order to re-process the submission, we'll need the original submitter to verify the veteran information is correct and then resubmit it.

# Tasks
- [ ] - Determine if the user was logged in or anonymous

- [ ] - If the veteran was logged in, we will need to either re-submit the claim and/or find out why it was kicked back.
- [ ] - If the veteran was anonymous, determine if it seems legitimate or junk

**Comment by wayne-weibel** [comment]
```
irb(main):001> fs = FormSubmission.find_by(benefits_intake_uuid: 'd10d3dc5-9dfb-4f8f-8a3b-246d0a0f7381')
=> #<FormSubmission id: 43346, form_type: "21P-527EZ", benefits_intake_uuid: "d10d3dc5-9dfb-4f8f-8a3b-246d0a0f7381...
irb(main):002> fs.saved_claim_id
=> 9193137
irb(main):003> SavedClaim::Pension.find(fs.saved_claim_id)
=> #<SavedClaim::Pension id: 9193137, created_at: "2024-06-16 19:04:08.504765000 +0000", updated_at: "2024-06-16 19:04:08.504765000 +0000", form_id: "21P-527EZ", guid: "73208750-f05d-4d82-bbb0-9272b70ee0b2", form: [FILTERED], encrypted_kms_key: "v2023:AQICAHjgjYH+KWbNRYBxOGDWJ7R6hKgus/oZ2XWComyf...", uploaded_forms: nil, itf_datetime: "2024-06-16 17:42:46.242806000 +0000", form_start_date: nil>
irb(main):004> job = Lighthouse::PensionBenefitIntakeJob.new
=> #<Lighthouse::PensionBenefitIntakeJob:0x00007fd01bbd0d10>
irb(main):005> job.perform(fs.saved_claim_id)
{"host":"vets-api-sidekiq-65dc7cd78-6wfj2","application":"vets-api-server","environment":"production","timestamp":"2024-06-26T13:52:06.629350Z","level":"info","level_index":2,"pid":47958,"thread":"12240","file":"/app/lib/pension_21p527ez/monitor.rb","line":45,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"87b5a2f2d08bc05205824e885d812aae2248f275","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Lighthouse::PensionBenefitIntakeJob submission to LH begun","payload":{"claim_id":9193137,"benefits_intake_uuid":"9cf2acff-2311-44dc-9625-18ef02a72fa4","confirmation_number":"73208750-f05d-4d82-bbb0-9272b70ee0b2","user_uuid":null}}
{"host":"vets-api-sidekiq-65dc7cd78-6wfj2","application":"vets-api-server","environment":"production","timestamp":"2024-06-26T13:52:06.719147Z","level":"info","level_index":2,"pid":47958,"thread":"12240","file":"/app/lib/pension_21p527ez/monitor.rb","line":56,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"87b5a2f2d08bc05205824e885d812aae2248f275","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Lighthouse::PensionBenefitIntakeJob submission to LH attempted","payload":{"claim_id":9193137,"benefits_intake_uuid":"9cf2acff-2311-44dc-9625-18ef02a72fa4","confirmation_number":"73208750-f05d-4d82-bbb0-9272b70ee0b2","user_uuid":null,"file":null,"attachments":["tmp/878145e7c28158032394b07ed2e7903b.pdf","tmp/64a50d963554a478ec3d9ad2c2c58098.pdf","tmp/4443166434e54a27c94d436950dce03c.pdf","tmp/edec6fb0ac1e91a68871574bb8cd2903.pdf","tmp/b570837b918bab68cee6e480be5cc281.pdf"]}}
{"host":"vets-api-sidekiq-65dc7cd78-6wfj2","application":"vets-api-server","environment":"production","timestamp":"2024-06-26T13:52:06.856191Z","level":"info","level_index":2,"pid":47958,"thread":"12240","file":"/usr/local/bundle/cache/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/redis_connection.rb","line":15,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"87b5a2f2d08bc05205824e885d812aae2248f275","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Sidekiq","message":"Sidekiq 7.2.4 connecting to Redis with options {:size=>10, :pool_name=>\"internal\", :url=>\"redis://dsva-vagov-prod-sidekiq.eqe4uk.ng.0001.usgw1.cache.amazonaws.com:6379\"}"}
{"host":"vets-api-sidekiq-65dc7cd78-6wfj2","application":"vets-api-server","environment":"production","timestamp":"2024-06-26T13:52:06.876841Z","level":"info","level_index":2,"pid":47958,"thread":"12240","file":"/app/lib/pension_21p527ez/monitor.rb","line":68,"named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"87b5a2f2d08bc05205824e885d812aae2248f275","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"Lighthouse::PensionBenefitIntakeJob submission to LH succeeded","payload":{"claim_id":9193137,"benefits_intake_uuid":"9cf2acff-2311-44dc-9625-18ef02a72fa4","confirmation_number":"73208750-f05d-4d82-bbb0-9272b70ee0b2","user_uuid":null}}
=> "9cf2acff-2311-44dc-9625-18ef02a72fa4"
irb(main):006> 
```

**Comment by wayne-weibel** [comment]
<img width="527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48c3acc49243c60664bfdb778024468cddc37a99/image.png" alt="image.png" />

**Comment by wayne-weibel** [comment]
user_uuid: e6dde0615abd46658124b9ff0652acea

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5315216/1c2e8bc0-2863-4c4e-90f3-c8614b3acfc2)

**Comment by wayne-weibel** [comment]
The re-submission has reached the success state in LH
```
 status=200,
 reason_phrase="OK",
 response_body=
  {"data"=>
    {"id"=>"9cf2acff-2311-44dc-9625-18ef02a72fa4",
     "type"=>"document_upload",
     "attributes"=>
      {"guid"=>"9cf2acff-2311-44dc-9625-18ef02a72fa4",
       "status"=>"success",
       "code"=>nil,
       "detail"=>"",
       "location"=>nil,
       "updated_at"=>"2024-06-26T16:54:44.302Z",
       "uploaded_pdf"=>
        {"total_documents"=>6,
         "total_pages"=>13,
         "content"=>
          {"page_count"=>8,
           "dimensions"=>{"height"=>11.0, "width"=>8.5, "oversized_pdf"=>false},
           "file_size"=>712202,
           "attachments"=>
            [{"page_count"=>1,
              "dimensions"=>{"height"=>11.0, "width"=>8.5, "oversized_pdf"=>false},
              "file_size"=>1777412},
             {"page_count"=>1,
irb(main):010> 
irb(main):011> status = BenefitsIntake::Service.new.get_status(uuid: "9cf2acff-2311-44dc-9625-18ef02a72fa4")
=> 
#<struct Faraday::Env
...
irb(main):012> status.body['data']['attributes']['status']
=> "success"
irb(main):013> 
```
