### ISSUE TITLE
Research failed submission

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#86837]
# Overview
There was a failed submission over the weekend that errored out:

`{"data":{"id":"d10d3dc5-9dfb-4f8f-8a3b-246d0a0f7381","type":"document_upload","attributes":{"guid":"d10d3dc5-9dfb-4f8f-8a3b-246d0a0f7381","status":"error","code":"DOC202","detail":"Upstream status: Unidentified Mail: We could not associate part or all of this submission with a Veteran. Please verify the identifying information and resubmit.","location":null,"updated_at":"2024-06-21T13:47:09.990Z","uploaded_pdf":{"total_documents":6,"total_pages":13,"content":{"page_count":8,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":712202,"attachments":[{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":1777412},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":2255230},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":1816883},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":246289},{"page_count":1,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":209390}]},"line_of_business":"PMC"}}}}%`

https://vagov.ddog-gov.com/logs?query=%40named_tags.dd.env%3Aeks-prod+%40payload.to_state%3Afailure+%40payload.form_type%3A21P-527EZ&from_ts=1718949600000&to_ts=1719028938000&live=false&agg_m=count&agg_t=count&index=%2A&source=monitor_notif

According to the API Intake Channel:

>  the Unidentifiable Mail error is generated after folks in the intake process verify that they can't locate a veteran using the information provided in the submission. In order to re-process the submission, we'll need the original submitter to verify the veteran information is correct and then resubmit it.

# Tasks
- [ ] - Determine if the user was logged in or anonymous

- [ ] - If the veteran was logged in, we will need to either re-submit the claim and/or find out why it was kicked back.
- [ ] - If the veteran was anonymous, determine if it seems legitimate or junk
