### ISSUE TITLE
FE | Ch33 Migration | Upcoming Downtime Alert and Downtime Alert Updates

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#86840]
## Background 

We need to update the upcoming downtime alert and the downtime alert 

#### Direct Deposit Page
[Upcoming downtime maint  we need to modify the start and end dates](https://www.figma.com/design/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?node-id=972-4456&t=4Y98ZpHyYaXSzMRf-4)

Start: Wednesday, June 26, 2024, at 5:00 p.m. ET
End: Wednesday, July 10, 2024, at 5:00 p.m. ET

#### Hub alert
[for the hub alert we'd need to modify the last sentence of the first paragraph](https://www.figma.com/design/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?node-id=972-4457&t=4Y98ZpHyYaXSzMRf-4)
"We expect the maintenance period will last for 14 days."

---

### Downtime period 
the maint alert would also need a modified sentence

[I don't have a design that's updated but the last pull request shows this](https://github.com/department-of-veterans-affairs/vets-website/pull/29319)

"We expect to complete this work by Wednesday, July 10, 2024 at 5pm ET"

Source of this ticket [Slack Message](https://dsva.slack.com/archives/C909ZG2BB/p1719323860264179?thread_ts=1719323615.788879&cid=C909ZG2BB)

## Tasks 
- [x] as soon as the code is ready merge and deploy, we want to enable the downtime alert ASAP today, deploy to staging and attach screen grabs to the ticket confirming you've QA'd this, that should be sufficient for validation 
- [x] enable the upcoming alert ASAP (we'll enable the downtime period at 5pm Wednesday afternoon) 

## Acceptance Criteria 

- [x] the upcoming alert on DD page has a modified start and end date 
- [x] upcoming alert on Hub page has a modified period of days 
- [x] downtime alert has updated dates

**Comment by mtcA6** [comment]
https://dsva.slack.com/archives/C909ZG2BB/p1719334660950639?thread_ts=1719323615.788879&cid=C909ZG2BB
confirmation this is in staging and in prod

**Comment by mtcA6** [comment]
We need to update the time on the downtime alert for the C&P hotline from 7PM to 9PM. 

cc: @asiisii
