### ISSUE TITLE
[DevOps] LoROTA Lambda logging not making it to Datadog in `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86846]
## Description
Evidently, I've screwed something up. Let's figure out why.

## Tasks
- [x] [DevOps] Look at Lambda logs in CloudWatch and determine what is complaining if anything.
- [x] [DevOps] Document findings and open ticket to address.

## Acceptance Criteria
- [x] Root cause has been determined and documented in this thread.
- [x] Followup ticket(s) opened to address findings.

**Comment by ndouglas** [comment]
Lambda policy didn't include secretsmanager access, so it couldn't load the DD API key, and didn't have CloudWatch permissions. .... yeah, that'll do it 😑
