### ISSUE TITLE
[DevOps] Determine why `vaec-cms` Lambda log messages are logged twice.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86844]
## Description
Lambda log messages are being logged twice in `vaec-cms` and presumably will be in `vaec-cie` as well.

See [this Slack thread](https://dsva.slack.com/archives/C04G3EY2F5W/p1719263485075629).

## Tasks
- [x] [DevOps] Determine why log messages are being recorded twice.
- [x] [DevOps] Determine which set of messages should be kept (since they have different attributes).
- [x] [DevOps] Document the reason why in this thread and the decision on which to keep.
- [x] [DevOps] Open up a followup ticket to address appropriately.

## Acceptance Criteria
- [x] Root cause has been determined and documented in this thread.
- [x] Followup ticket(s) opened to address findings.

**Comment by ndouglas** [comment]
As suspected, this is caused by the Datadog Lambda Forwarder log subscriptions, which are superfluous when you're using the Datadog Lambda Extension. Opened #87597 and #87599 to address.
