### ISSUE TITLE
Check in w/ Matt S to discuss qtrly update timing

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#86845]
## Purpose
Let's try to align our wrap-up of the Qtrly Survey so that Matt Self can include the results in his update.  In the past, his update may have been released before those results reach him.

[Notes](https://vfs.atlassian.net/wiki/spaces/SDT/pages/3246981132/6+20+24+-+PO+PM+Sync#PO-comments%3A) from sync

## Tasks
- [x] Reach out to Matt to learn how his timetable works
- [x] Figure out when it'd be ideal to get updates to him
- [x] Agree on outputs and timing from our team.
- [x] Adjust any tickets/timing on our end to meet this schedule

## Acceptance Criteria
- [x] Our planning schedule is adjusted for affected tickets
