### ISSUE TITLE
[DevOps] ESECC documentation for outgoing connection to Vista API

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86853]
## Description
This needs to be researched and completed.

## Tasks
- [ ] [DevOps] Determine what needs to be documented in order to support this functionality.
- [ ] [DevOps] Complete this documentation or open up followup ticket(s) to address necessary details.

## Acceptance Criteria
- [ ] Documentation is completed and submitted, or
- [ ] Followup ticket(s) opened to address complications.

**Comment by olivereri** [comment]
Lucky for us this appears to be well documented:
https://github.com/department-of-veterans-affairs/checkin-devops/blob/main/docs/esecc-requests.md

**Comment by olivereri** [comment]
I keep seeing mention of needing an ATO before submitting ESECC requests. That does make sense that a system without an ATO shouldn't connect to ones that do:

1. Set up functional of Check-in related
1. Get an ATO
1. Get WASA Scan
1. Submit ESECC request.

**Comment by olivereri** [comment]
Documentation exists to implement the desired changes.
