### ISSUE TITLE
[DevOps] Prepare for July 1 Migration Check-In

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86855]
## Description
Compile a list of what to discuss.

Take notes in this ticket thread.

## Tasks
- [x] [DevOps] Things to discuss:
  - [x] We're not going to make that August 8th deadline.
  - [x] TLS certificate management; some certificates (for Vista API) are managed in `vaec-cms` and currently owned by what is now the VeTEXT team. Should we ask for our own group? Has a group been created for us? What AD groups are created for us?
  - [x] #81998 (specifically ESECC for Vista API)
  - [x] #81999 
  - [x] #82000

## Acceptance Criteria
- [x] We went to the meeting, it's all okay.

**Comment by ndouglas** [comment]
Well, there wasn't a meeting, but I asked in Teams 🙂

**Comment by ndouglas** [comment]
Shalom responded.

- "If you are sending packets to anything outside of port 80/443, then you will need an ESECC. We can get tht process started... once you have your source and destination IPs."
- "The only AD group which ECSO creates is the Project Admin group. If you need more AD groups you will need to create a service request and request the needed groups."
- "Once everything is deployed we want to utilize the MSR systems at first. Then we will setup time with the ScienceLogic team for an integration for monitoring at a level of your comfort."
- "It's a check to ensure all the documentation and all tasks from step 5 and 6 have been completed correctly... we will not check the deployment from a technical nature... we will ensure things have been tagged correctly for example and check to ensure that you can pass the PDB. Once you pass deployment QA, I setup the PDB approval immediately and then you are free to go live."
