### ISSUE TITLE
[DevOps] Add ECR lifecycle policy to `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86868]
## Description
Followup to #86861.

Add an appropriate ECR lifecycle policy for our ECR repository.

## Tasks
- [x] [DevOps] Create an `aws_ecr_lifecycle_policy` block in IaC.
- [x] [DevOps] Determine an appropriate policy that will:
  - [x] not waste space
  - [x] not delete images out from under us, regardless of environment 
  - [x] maybe keep last 5 images, don't delete based on age

## Acceptance Criteria
- [x] Appropriate policy is designed
- [x] Policy is deployed in all environments

**Comment by ndouglas** [comment]
Keeping 5 images on prod, 2 on other environments.
