### ISSUE TITLE
[DevOps] Create Registry scanning configuration for Vista API ECR module.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86863]
## Description
Followup to #86861.

I don't know if we currently have scanning set up for `vaec-cms` ECR, but we absolutely should moving forward.

## Tasks
- [x] [DevOps] Determine appropriate scanning configuration
- [x] [DevOps] Create corresponding `aws_ecr_registry_scanning_configuration` block.

## Acceptance Criteria
- [x] Block exists in IaC and registry scanning configuration is in place.
