### ISSUE TITLE
[DevOps] Create Terraform module for Vista API ECR resources in `octo-vista-api`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86861]
## Description
`vaec-cms` has large clusters running Vista API cache containers. The container repositories need to be mirrored in `vaec-cie`.

Followup to #86523 and #86988.

## Tasks
- [x] [DevOps] Create `ecr` module within `octo-vista-api` repository (i.e. `terraform/ecr`).
- [x] [DevOps] Create the following resources (per environment):
  - [x] `aws_ecr_repository`
  - [x] `aws_ecr_repository_policy`

## Acceptance Criteria
- [x] Terraform module exists in appropriate location.
- [x] Resources are created appropriately with sufficient permissions.

**Comment by ndouglas** [comment]
The four repositories known to be relevant to `octo-vista-api` are created with (possibly adequate) repository policies.
