### ISSUE TITLE
[DevOps] Determine if we need a pull-through container registry cache in `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86865]
## Description
I don't _think_ that we use any public or third-party Docker containers, but we should determine this for sure. It might be that the `octo-vista-api` image is a derivative, in which case we should keep the base image available.

## Tasks
- [ ] [DevOps] Determine need for pull-through container registry cache.
- [ ] [DevOps] If necessary, implement in Terraform with `aws_ecr_pull_through_cache_rule`.
- [ ] [DevOps] Do we need Docker Hub credentials?

## Acceptance Criteria
- [ ] If a good idea, `aws_ecr_pull_through_cache_rule` block has been added to IaC and deployed in all environments.

**Comment by ndouglas** [comment]
Nevermind.

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/8b2d4446-c051-40c3-a047-a7416905632a)
