### ISSUE TITLE
Reinstall CMS DS in figma

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-team#86860]
## Description

To design a form engine UI that meet the CMS design and content criteria, Using the CMS DS will streamline the design process. An initial draft will contain the standard tokens and components that we will use to create patterns based on the attribute requirements for an editor to build a front end form. Edits to the DS will be published ongoing, but the overall management of the CMS DS is the responsibility of the CMS team. 

## Acceptance criteria
- [x] Publish in Figma a version the CMS DS that reflects the Claro theme in Drupal

## Tasks
- [x] Review deprecated DS tokens in figma and copy to the new project team
- [x] Edit components for consistency
- [x] Publish library in new project team

## Additional info
Updates to the DS will be ongoing for the following reasons:
- Add or update component attributes
- Technical updates to figma may offer ways to simply the system
- Any input from the CMS team may require updates
- If the CMS team decides to standup the entire CMS DS we should adapt to their system

CMS patterns
I've also copied current paragraphs, field groups, and other "patterns" that that make up the editor UI for creating web pages. These patterns are not part of the DS but are built out of the DS components. As we use and/or reconfigure to build out the form engine UI we will publish those  as well
