### ISSUE TITLE
[DevOps] Discovery on Vista API ECS resources

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86873]
## Description
`vaec-cms` has ECS resources for Vista API; these should exist also in `vaec-cie`.

## Tasks
- [x] [DevOps] Review and record current resources from AWS:
  - [x] Any special account settings
  - [x] Any capacity provider configurations
  - [x] Notes on the cluster configurations
  - [x] Any cluster capacity provider configurations
  - [x] Service definitions
  - [x] Task definitions
  - [x] Task sets

## Acceptance Criteria
- [x] All resources above have been studied and documented in this thread.

**Comment by ndouglas** [comment]
- No meaningful special account settings
- Not seeing capacity provider configurations ATM
- Single cluster, which I'll be splitting per-env
- Have service definitions in hand
- Have task definitions in hand, but they contain some secrets
- No task sets
