### ISSUE TITLE
[DevOps] Vista API usage discovery

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86874]
## Description
Review usage patterns over time. Would the VA benefit from autoscaling? How does this affect our configuration, e.g. with ignoring changes to capacity?

## Tasks
- [ ] [DevOps] Determine if autoscaling would be suitable for Vista API
- [ ] [DevOps] Determine what additional infrastructure (e.g. logging and monitoring) might be necessary to support this
- [ ] [DevOps] Determine what additional infrastructure (e.g. automated testing apparatuses) are needed to validate functionality

## Acceptance Criteria
- [ ] Discovery has been performed and findings documented in this thread.
