### ISSUE TITLE
PDF Overflow Volume

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#86881]
## Issue Description
_VA Comp and Pension would like to understand how many VA.gov claims have name and address info that overflows to the addendum page. The MAS system that is involved in automated claim processing cannot process name or address info on the addendum page, which is causing incorrect addresses to be used when mailing Veterans information or issues matching claimants with dependents. At minimum, the would like to understand the volume for 530EZ, 526EZ, 686c, and 674 claims. Ideally, they would like the volume for all VA.gov claims that hit MAS:_

0995
526EZ
4142
527EZ
10206
0996
686c
674
674b
0845
10210
0781
526EZ
0966
530EZ

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Volume of VA.gov 530EZ claims with any name and address info on the addendum page
- [ ] Volume of VA.gov 686c claims with any name and address info on the addendum page
- [ ] Volume of VA.gov 674 claims with any name and address info on the addendum page
- [ ] Volume of VA.gov 526EZ claims with any name and address info on the addendum page
---

**Comment by steele-lm** [comment]
for 530,
134 claims have a street address > 30 characters
62 claims have a city > 18 characters
this is against ~15000 claims since October 2023
about 1.3% rate.
With ~1875 claims per month, guestimate of 25 claims per month.

**Comment by steele-lm** [comment]
3.4% on 686C,
33 Address 1
151 Address 2
14 City

**Comment by steele-lm** [comment]
527:
38 Address 1
742 Address 2
21 City
5130 submissions
15.6 % error rate

**Comment by steele-lm** [comment]
Pension script:
```
batches = SavedClaim::Pension.where(id: 0..).find_in_batches(batch_size: 100)
recordsProcessed = 0
address_result = []
address2_result = []
city_result = []
batches.each do |batch|
  puts "#{Time.now} | RECORDS PROCESSED #{recordsProcessed}"
  batch.each do |claim|
    recordsProcessed += 1  
    form = claim.parsed_form
    address_result << claim.id if form.dig("veteranAddress", "street").size > 30
    address2 = form.dig("veteranAddress", "street2")
    address2_result << claim.id if address2.present? && address2.size > 5 
    city_result << claim.id if form.dig("veteranAddress", "city").size > 18 
  end
end

pp "#{address_result.size} Address 1"
pp "#{address2_result.size} Address 2"
pp "#{city_result.size} Address 3"
num_claims = SavedClaim::Pension.all.size
pp "#{num_claims} Pension claims"
errors = address_result.size + address2_result.size + city_result.size
error_rate = ((errors.to_f / num_claims.to_f) * 100.0).round(2)
pp "#{error_rate}% error rate"
```
