### ISSUE TITLE
[DevOps] Proof-of-concept NodeJS end-to-end test.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86889]
## Description
Similarly to #86440, this ticket is for evaluating possible approaches to end-to-end tests (including infrastructure) within `vaec-cie`. This approach uses a separate NodeJS package or suite of packages that would contain tests.

## Tasks
- [ ] [DevOps] At least one test using a NodeJS package has been written that matches the desired criteria.
- [ ] [DevOps] Process, experience, and outcomes have been documented in this thread.

## Acceptance Criteria
- [ ] Experience of a PoC E2E test has been documented in this thread.

**Comment by ndouglas** [comment]
I wrote a test of the `POST` `/token` LoROTA endpoint. This endpoint expects a claims token in the header and will generate and return a JWT permitting access to the LoROTA CRUD operations (`delete`/`get`/`patch`/`post`/`put`). In the course of writing the test and getting it to pass, I found a number of issues with the infrastructure, so 🎉 I think these system tests will accomplish exactly what I hoped they would.
