### ISSUE TITLE
Debt Letters Frontend  API Integration 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#8689]
## User Story or Problem Statement
As a  veteran who has incurred debt I receive debt letters in the mail. I would like to be able to see the information online @ va.gov so i can understand the source of the debt, the amount of the debt and what my options are for payment or any other remediation I can take.

## Goal
_Ability to display the information the veteran received in mail online from DMC API so the veteran can clearly see the debt owed, how it was incurred and next steps. 

## Tasks
- [ ] _Parse JSON from API to provide FE data 
- [ ]_Display data per Design UI 

## Acceptance Criteria
- [ ] _For any given the user the values retuned in API can be captured and displayed 
- [ ] _Page Design matches mock-ups provided 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
