### ISSUE TITLE
[DevOps] Determine requirements for end-to-end tests.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86891]
## Description

These tests should:
- originate outside of the target VPCs (to test transiting the VPCEs)
- target e.g. API Gateway VPCE, not Lambdas directly
- be environment-independent, e.g. we should be able to run these on dev/int/stg and ideally prod too (at least for unhappy path tests)
- be runnable via GitHub Actions workflows (self-hosted runners?)
- be account-independent, e.g. we should be able to execute these against `vaec-cms` and `vaec-cie`.

## Tasks
- [x] [DevOps] Determine appropriate requirements for end-to-end tests.
- [x] [DevOps] Document requirements in this thread.

## Acceptance Criteria
- [x] We've determined appropriate requirements for end-to-end tests that will improve confidence in our infrastructure across upper and lower environments prior to switchover
- [x] Followup ticket(s) opened to address additional infrastructural requirements (e.g. self-hosted runners) necessary for supporting end-to-end tests.

**Comment by ndouglas** [comment]
The above seems like a good place to start.
