### ISSUE TITLE
Support showing Profile v1 or Profile 2.0 at the same route

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8690]
We want to show either the old or the new Profile at the main `/profile` route. We want to remove the `profile-2/` route entirely.

During development of the Profile, our team wants access to the new Profile locally and on staging, but we don't want to disrupt or confuse other teams who are expecting to see or need access to the old profile.

**AC:**
- To see the new Profile 2.0 locally or on staging, the `profileShowProfile2` feature flag needs to be turned on _and_ a special URL param/local storage key must be set correctly.
- But on prod it will work a little bit differently. On prod we will show the new Profile 2.0 if the `profileShowProfile2` feature flag is turned on; we won't care about the URL param/local storage key at all.

- This way we won't disrupt anyone else who is working on or accessing the profile locally or on staging but will still give us access if we want it.
- This will also prevent the new Profile 2.0 from showing on production at all until we are ready.
- When we are closer to shipping we might want to flip the behavior on localhost/staging; that is, show the new Profile 2.0 if the `profileShowProfile2` feature flag is on but allow for showing the old profile if a URL param/local storage value is set.

**TODO:**
Switch to using the React-based Breadcrumps on the old Profile:
- [ ] Remove `"includeBreadcrumbs": true,` from src/applications/personalization/profile360/manifest.json
- [ ] Modify the src/applications/personalization/profile360/containers/VAProfileApp.jsx and add the Breadcrumb component

Make changes to src/applications/personalization/profile360/profile-360-entry.jsx to stop using `startApp()` to bootstrap the app. Instead we need to roll our own solution for a wrapper that will do the following:
- [ ] Be a Redux-connected component that determines which profile to show depending on the value of the `profileShowProfile2` feature flag and a URL param/local storage value.
- [ ] Based on the combination of feature flag + local storage/URL param it will render either the src/applications/personalization/profile360/containers/VAProfileApp.jsx or the src/applications/personalization/profile-2/components/ProfileWrapper.jsx
- [ ] Handle setting up the correct routes for React Router depending on if we are showing the old or new profile.
	- the old profile doesn't really need React Router as it only has a single route.
	- The new Profile 2.0 will need to have its sub-page routes set correctly.

**Comment by erikphansen** [comment]
Closing this. This is old and Profile v1 has been dead for some time.
