### ISSUE TITLE
Support showing Profile v1 or Profile 2.0 at the same route

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8691]
## Background
We want to show either the old or the new Profile at the main `/profile` route. We want to remove the `profile-2/` route entirely.

During development of the Profile, our team wants access to the new Profile locally and on staging, but we don't want to disrupt or confuse other teams who are expecting to see or need access to the old profile.

Associated tickets
~- [ ] [FE] Remove Direct Deposit on the profile if users are not eligible #8571~ this item is not part of this epic, IMO (eph)
- [x] [FE] Switch to using React based breadcrumbs on the old profile #8692
- [x] [FE] Mount a new profile wrapper that will be responsible for showing either the old or new Profiles #8698 
- [x] [FE] Remove everything related to "Account" if profile is turned on #8699

**Acceptance Criteria:**
- To see the new Profile 2.0 locally or on staging, the `profileShowProfile2` feature flag needs to be turned on _and_ a special URL param/local storage key must be set correctly.
- But on prod it will work a little bit differently. On prod we will show the new Profile 2.0 if the `profileShowProfile2` feature flag is turned on; we won't care about the URL param/local storage key at all.

- This way we won't disrupt anyone else who is working on or accessing the profile locally or on staging but will still give us access if we want it.
- This will also prevent the new Profile 2.0 from showing on production at all until we are ready.
- When we are closer to shipping we might want to flip the behavior on localhost/staging; that is, show the new Profile 2.0 if the `profileShowProfile2` feature flag is on but allow for showing the old profile if a URL param/local storage value is set.

**Comment by erikphansen** [comment]
One more thing that popped up when Sandra and I just talked: we also need to remove everything related to the Account section when we Profile 2.0 is turned on.

So if Profile 2.0 is enable, we also need to:
- [ ] remove the Account link in the user drop down menu
- [ ] change how the `/account` route behaves. Either have it automatically redirect the user to `/profile/account-security` or maybe the better solution is change the content of the Account page to tell the user that the account features live on the new Profile.
- [ ] consolidate the Profile and Account links at the bottom of the My VA Dashboard into a single button https://github.com/department-of-veterans-affairs/va.gov-team/issues/8400

**Comment by erikphansen** [comment]
@mshea0606 This info was added to the wrong ticket. This work will need to be set up in its own ticket

- [ ] Make changes to src/applications/personalization/profile360/profile-360-entry.jsx to mount a new profile wrapper that will be responsible for showing either the old or new Profiles. We might need to stop using `startApp()` to bootstrap the app and instead roll our own solution for a wrapper that will do the following:

## Acceptance Criteria:
- [ ] Be a Redux-connected component that determines which profile to show depending on the value of the profileShowProfile2 feature flag and a URL param/local storage value.
- [ ] Based on the combination of feature flag + local storage/URL param it will render either the src/applications/personalization/profile360/containers/VAProfileApp.jsx or the src/applications/personalization/profile-2/components/ProfileWrapper.jsx
- [ ] Handle setting up the correct routes for React Router depending on if we are showing the old or new profile. The old profile doesn't really need React Router as it only has a single route.
The new Profile 2.0 will need to have its sub-page routes set correctly.
    - This task is the trickiest and biggest unknown at this point. We need to change the child routes that the React Router app has access to after the app has spun up. But we also need to be able to do this when we disable the [Direct Deposit link and route](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8571) and disable most routes when the user is LOA1 (no ticket for FE work, but [this is the design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8570)).

**Comment by mshea0606** [comment]
@erikphansen  the info above is in this ticket [FE] Mount a new profile wrapper that will be responsible for showing either the old or new Profiles #8698

**Comment by mshea0606** [comment]
@erikphansen also just created [FE] Remove everything related to "Account" if profile is turned on #8699 and tied it to this epic

**Comment by erikphansen** [comment]
just curious: is this supposed to be in the Backlog? I'm not sure how epics work.

**Comment by mshea0606** [comment]
@erikphansen oops, i just moved it to "current sprint"
