### ISSUE TITLE
Switch to using React based breadcrumbs on the old profile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8692]
Related [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8691)

## Tasks
Switch to using the React-based Breadcrumps on the old Profile:

 - [x] Remove "includeBreadcrumbs": true, from src/applications/personalization/profile360/manifest.json

 - [x] Modify the src/applications/personalization/profile360/containers/VAProfileApp.jsx and add the Breadcrumb component

**Comment by erikphansen** [comment]
I removed the follow from this ticket as its unrelated work:

- [ ] Make changes to src/applications/personalization/profile360/profile-360-entry.jsx to stop using startApp() to bootstrap the app. Instead we need to roll our own solution for a wrapper that will do the following:


## Acceptance Criteria:
- [ ] Be a Redux-connected component that determines which profile to show depending on the value of the profileShowProfile2 feature flag and a URL param/local storage value.

- [ ] Based on the combination of feature flag + local storage/URL param it will render either the src/applications/personalization/profile360/containers/VAProfileApp.jsx or the src/applications/personalization/profile-2/components/ProfileWrapper.jsx

- [ ] Handle setting up the correct routes for React Router depending on if we are showing the old or new profile. The old profile doesn't really need React Router as it only has a single route.
The new Profile 2.0 will need to have its sub-page routes set correctly.

**Comment by sanlouise** [comment]
@mshea0606 Could you please validate this ticket? Thank you!
