### ISSUE TITLE
Request Midpoint Review for Profile/MyVA designs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86934]
## Issue Description
This is to track the request of a Midpoint Review meeting, a touchpoint for the Collaboration Cycle, to get Governance's feedback on our Profile and MyVA Rep Status designs.

---
## Tasks
- [x] Create new Collab Cycle intake for the Profile/MyVA design work
- [x] Kick off new Collab Cycle 
- [x] Schedule Midpoint Review and invite team members
- [x] Notify the Collaboration Cycle via Slack

## Acceptance Criteria
- A Midpoint Review has been scheduled
- All materials have been provided for the Midpoint Review meeting

**Comment by oddball-lindsay** [comment]
Midpoint Review scheduled for next Thurs 7/18 at 3:30pm ET.  Invited ARM team, as well as Profile/MyVA folks.
