### ISSUE TITLE
Review Accreditation Site for any other Veteran-facing information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86945]
## Background
We recently replaced OGC's link to https://www.va.gov/ogc/accreditation.asp in the footer of VA.gov with our landing page for accredited representatives.

OGC is concerned that we are losing valuable Veteran-facing information with this change.  To address their concerns, I have offered to review their accreditation page and identify opportunities to enhance our landing page or FAQ page with additional content from that source.

## Tasks
- [ ] Review the accreditation site and identify any Veteran-facing information not covered in the FAQ or landing page
- [ ] Summarize content opportunities in a Sharepoint document
- [ ] Share the document with OGC to confirm
- [ ] Share the document with CAIA for incorporating into future iterations of the FAQ or landing page

## Acceptance Criteria
- [ ] We are confident that all Veteran-facing information on the accreditation site is available for Veterans on our FAQ or landing page.
