### ISSUE TITLE
Review Accreditation Site for any other Veteran-facing information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#86946]
## Background
We recently replaced OGC's link to https://www.va.gov/ogc/accreditation.asp in the footer of VA.gov with our landing page for accredited representatives.

OGC is concerned that we are losing valuable Veteran-facing information with this change.  To address their concerns, I have offered to review their accreditation page and identify opportunities to enhance our landing page or FAQ page with additional content from that source.

We also want to review https://www.va.gov/ogc/accred_faqs.asp

## Tasks
- [x] Review the OGC web pages and identify any Veteran-facing information not covered in the VA.gov FAQ or landing page
- [ ] Summarize content opportunities in a Sharepoint document
- [ ] Share the document with OGC to confirm
- [ ] Share the document with CAIA for incorporating into future iterations of the FAQ or landing page

## Acceptance Criteria
- [x] We are confident that all Veteran-facing information on the accreditation site is available for Veterans on our FAQ or landing page.

**Comment by oddball-lindsay** [comment]
It might be worth reviewing https://www.va.gov/ogc/accred_faqs.asp too -- will ask OGC if there are other URLs I should consider with this content review.

**Comment by oddball-lindsay** [comment]
Nathan confirmed https://www.va.gov/ogc/accred_faqs.asp is worth reviewing, no other web pages for now.  Updated issue description to reflect this.

**Comment by oddball-lindsay** [comment]
Nathan confirmed https://www.va.gov/ogc/accred_faqs.asp is worth reviewing, no other web pages for now.  Updated issue description to reflect this.

**Comment by oddball-lindsay** [comment]
There are some small nuances that we do not cover around qualifications for accreditation, but I think that level of detail may not be relevant to Veterans at the time of reviewing our content.  It's most crucial to impart that the representative must be accredited to assist with claims.

**Comment by jfinnerty13** [comment]
Two topics I'd consider for the FAQ @oddball-lindsay 
1. Any direction to shark information in the future but we can discuss with CAIA on that.
2. A link at the bottom mentioning 'are you a rep, you can go to OGCs site here'. With us directing a lot of pages to our content now there's no direct way to access it, so having a link to help might be worth while.
Otherwise agree with your assessment and remember A reviewing the FAQs on OGCs site when working on this :) 

Thanks for reviewing!

**Comment by oddball-lindsay** [comment]
Thanks for the review @jfinnerty13!  I'll keep my ears/eyes out for emerging information around claim sharks so we can work with A to  incorporate that into our FAQ page.

> A link at the bottom mentioning 'are you a rep, you can go to OGCs site here'. With us directing a lot of pages to our content now there's no direct way to access it, so having a link to help might be worth while.
I can start a ticket with A for linking to OGC's site https://www.va.gov/ogc/accreditation.asp.  I'm curious to get their opinion on placement as the FAQ content is for Veterans, but the link is for representatives.

**Comment by oddball-lindsay** [comment]
Closing this out, will discuss the link to OGC's site directly with CAIA.
