### ISSUE TITLE
[Design] 10-10CG Design + Content Source of Truth File Updates

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#86960]
## Issue Description
Once the online form is live with the July paper form set of updates, make sure all the design files, Figma files, Mural user flows, reflect the correct state in production. 

Ticket Description: To make sure the source of truth designs are accurate and up-to-date, they need to be maintained and updated after every new update to production where the content/UI is impacted.

- **[Figma file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=0-1&t=104bLnGOpjrdMbOF-0)**
- [Mural User Flow](#)
- [Mural Error Audit](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683656893560/fccf821394d1cf693ad1c036e912e11a18ff88bd?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks

- [x] Create a content component page in Figma to move over new template setup out of working page
- [x]  update the Figma source of truth pages.
- [x]  Update the Mural product user flow
- [x] Update the Mural error audit board 

## Acceptance Criteria
All source of truth documents listed are updated with the recently launched changes.

---
