### ISSUE TITLE
Toxic Exposure 1.1 Release

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#86968]
This ticket is a placeholder for the effort required by the team to perform the TE 1.1 release. If we decide not to use it, that's fine. I just wanted a ticket to capture the effort.
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92806
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92807
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92808
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92809
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92810
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92811
```
