### ISSUE TITLE
Other AWS accounts need attention

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#8696]
## User Story or Problem Statement
As admins of all the various VA AWS accounts we use within our workflows, we need to be more conscious of compliance/security/etc. with the less used ones also.

## Goal
Ideally, all the accounts would be managed in code via Terraform for all resource pieces like IAM users, VPC's, etc. This may be a bit of an undertaking though, so I would say the most immediate / current concerns would be auditing those accounts and making sure offboarded users do not still have accounts.

## Objectives or Key Results this is meant to further
- ATO Compliance, security, better off-boarding process(es).
---
## Tasks
- [ ] Decide as a team if we want to go ahead and try to get these accounts managed more in code or push forward for now manually.
- [ ] Remove off-boarded users, unused resources, outdated objects, etc.

## Acceptance Criteria
- [ ] Cleaner AWS account management (ideally in code, but if nothing else the removal of old accounts, resources, etc. should be completed within the near future),
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
Need to add checking all the accounts as part of the off boarding process.

**Comment by ricetj** [comment]
Added to  offboarding process
