### ISSUE TITLE
Payment History VBA MVP 1.5 - Remove accordion on Debt Details page

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#86969]
## Issue Description
Accordion removal from “How to Pay” & text updates on the Debt Details page
Add address to Pay by Mail section.

Here is the placeholder HTML for the new versions:
```
       <h2>How to pay your VA debt</h2>
        <h3>Pay online</h3>
        <p>Pay directly from your bank account or by debit or credit card on the secure pay.va.gov website.</p>
        <p>You will need the following details to pay this debt online:</p>

        <ul>
          <li><strong>Current balance</strong>: $930.00</li>
          <li><strong>File Number</strong>: 796123018</li>
          <li><strong>Payee Number</strong>: 00</li>
          <li><strong>Person Entitled</strong>: HSMITH</li>
          <li><strong>Deduction Code</strong>: 44 - Education CH 35</li>
        </ul>

        <h3>Pay by phone</h3>
        <p>Call us at <va-telephone contact="8008270648"></va-telephone>. (
          <va-telephone contact="6127136415" />
          </va-telephone> from overseas) (
          <va-telephone contact="711" tty="true" />
          </va-telephone>). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET. 
        </p>

        <h3>Pay by mail</h3>
        <p>Send a separate check or money order for each debt, payable to “U.S. Department of Veterans Affairs.” On each, print your full name, VA file number or Social Security number, and deduction code. Include your payment stubs or a note with the amount you’re paying on each debt.</p>
        <p>Mail to this address:</p>
        <p class="va-address-block">U.S. Department of Veterans Affairs<br>
          Debt Management Center<br>
          P.O. Box 11930<br>
          St. Paul, MN 55111<br>
          United States of America
        </p>
        <h2>Request financial help</h2>
        <p>If you need financial help, you can request:</p>
        <ul>
          <li>An extended monthly payment plan, <strong>or</strong>
          </li>
          <li>A compromise (ask us to accept a lower amount of money as full payment of the debt), <strong>or</strong>
          </li>
          <li>A waiver (ask us to stop collection on the debt
          </li>
        </ul>
        <p>
          <a class="vads-c-action-link--blue" href="javascript:void(0)">Request help with your debt</a>
        </p>
        <h2>Dispute this debt</h2>
        <p>If you think a debt was created in error, you can dispute it. Get information about disputing a debt by calling the Debt Management Center at <va-telephone contact="8008270648"></va-telephone> (
          <va-telephone contact="711" tty="true" />
          </va-telephone>). For international callers, use
          <va-telephone contact="6127136415" />
          </va-telephone>. We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET. 
        </p>
```

Screenshot of updated section: 
## Tasks
<img width="717" alt="Screenshot 2024-06-26 at 4 55 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/434a4f4b-3e43-40ec-aabe-ae0797353240">

Link to [Figma file](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-16864&t=0A5wQ6ENgB0pCHz4-11).

- [ ] _Remove accordion
- [ ] Add address to "Pay by Mail" section

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
Pending code review- will most likely roll over to S130.
