### ISSUE TITLE
Full Accessibility & 508 Office Audit Public Websites [AMA pt. 2]

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8697]
## Steps to complete the Full Accessibility & 508 Audit: 
- [x] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts when you request a full review_
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

* Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.

### Required

  - [x] Conduct axe browser scan, and document or address issues found (required)
  - [x] Ensure end-to-end tests - including the axe check, pass (required)
  - [x] Check color pairing for proper contrast (required)
  - [x] Check for colorblindness issues (required)
  - [x] Zoom to 200% and confirm readability, no info cut off, etc (required)
  - [x] Repeat for 300% (required)
  - [x] Repeat for 400% (required)
  - [x] Navigate all pages and core functionality with keyboard only (required)
  - [x] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox (required)

### Recommended

  - [x] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) (recommended)
  - [ ] Add keyboard end-to-end tests in CI/CD test runs (recommended)
  - [ ] Conduct axe-coconut browser scan, document or address issues found (recommended)
  - [ ] Test with [WAVE](https://wave.webaim.org/) tool (recommended)

Known issues (if applicable):
* [Staging Review Issues Found](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7647) — itemized here:

    * Icebox
      - #7708 **CMS** — 508-defect-2 [AXE-CORE]: Heading levels SHOULD increase by one - alert headings | Not estimated
      - #7710 **CMS** — 508-defect-4 [AXE-CORE]: All page content MUST be contained by landmarks - div.veteran-banner | Not estimated
va.gov-team
      - #7723 **CMS, components, design system** — 508-defect-2 [KEYBOARD]: Landmarks MUST have a unique role or role/label/title (i.e. accessible name) combination; main nav and sidebar nav conflict | Not estimated
      - #7755 **sitewide, design system, CMS** — 508-defect-2 [AXE-CORE]: Heading levels should increase by one - footer issue | Not estimated
      - #7757 **CMS** — 508-defect-4 [AXE-CORE]: All page content MUST be contained by landmarks | Not estimated
      - #7840 **design system, components, cms** — 508-defect-4 [SEMANTIC MARKUP] Download links SHOULD use the download attribute | Not estimated
      - #7844 **CMS, components, design system** — 508-defect-2 [SCREENREADER] Aside MUST not be contained in another landmark | Not estimated
      - #7877 **sitewide, design system, CMS** — 508-defect-2 [AXE-CORE]: Heading levels SHOULD increase by one, On this page component | Not estimated
    * Backlog
      - #7770 508-defect-2 [SCREENREADER, COGNITION]: Bold text SHOULD be made headings, in this instance | Not estimated
      - #7808 508-defect-3 [SCREENREADER, COGNITION]: State abbreviations SHOULD be coded as such | Not estimated
    * Ready
      - #7803 508-defect-2 [COGNITION]: SHOULD use a list for a list of options | Not estimated
      - #7839 508-defect-3 [MOBILE] There SHOULD be sufficient space between interactive elements, to avoid errors | Not estimated
    * Current Sprint
      - #7834 508-defect-3 [SCREENREADER, COGNITION]: CONSIDER using semantic markup for screen reader users | Not estimated
    * Closed
      - #7769 508-defect-1 ❗ Launchblocker [SCREENREADER]: ARIA attributes MUST conform to valid values | Not estimated
      - #7847 508-defect-4 [COGNITION] CONSIDER adding a heading before "Longer than 1 year" | Not estimated

## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

## URLs to test:

https://www.va.gov/decision-reviews/
https://www.va.gov/decision-reviews/after-you-request-review/
https://www.va.gov/decision-reviews/supplemental-claim/
https://www.va.gov/decision-reviews/higher-level-review/
https://www.va.gov/decision-reviews/board-appeal/
https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/
~~https://www.va.gov/decision-reviews/multiple-party-claims/~~ => https://www.va.gov/decision-reviews/contested-claims/
https://www.va.gov/decision-reviews/fiduciary-claims/
https://www.va.gov/decision-reviews/insurance-claims/
https://www.va.gov/decision-reviews/faq/
https://www.va.gov/decision-reviews/get-help-with-review-request/
https://www.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing/

**Comment by stephorkandatx** [comment]
Need to add a list of the pages that were a part of AMA pt. 2 (modified, created).

**Comment by jenstrickland** [comment]
@stephorkandatx Does this help? https://github.com/department-of-veterans-affairs/va.gov-team/issues/7521#issuecomment-611102928

**Comment by stephorkandatx** [comment]
Thank you! I meant that as a note for me, I am sorry about not clarifying that!! And thank you for pulling that information for me

**Comment by stephorkandatx** [comment]
@kelsonic to follow up with @ncksllvn on end-to-end tests for Liquid templates.

**Comment by kelsonic** [comment]
> For reference, the urls to check — in the VA environment — are:
> 
> 1. Decision reviews and appeals —  https://preview-prod.vfs.va.gov/preview?nodeid=3071
> 2. After you request a decision review — https://preview-prod.vfs.va.gov/preview?nodeId=3008
> 3. Supplemental Claims — https://preview-prod.vfs.va.gov/preview?nodeId=3011
> 4. Higher-Level Reviews — https://preview-prod.vfs.va.gov/preview?nodeId=3003
> 5. Board Appeals — https://preview-prod.vfs.va.gov/preview?nodeId=3029
> 6. After a Board Appeal — https://preview-prod.vfs.va.gov/preview?nodeId=3013
> 7. Contested Claims — https://preview-prod.vfs.va.gov/preview?nodeId=3030
> 8. Fiduciary claims — https://preview-prod.vfs.va.gov/preview?nodeId=3016
> 9. Insurance claims — https://preview-prod.vfs.va.gov/preview?nodeId=3025
> 10. FAQs — https://preview-prod.vfs.va.gov/preview?nodeId=3004
> 11. Get help with review request — https://preview-prod.vfs.va.gov/preview?nodeId=3009
> 12. Board hearings with a VLJ — https://preview-prod.vfs.va.gov/preview?nodeId=3010

^^ This is super helpful 🙂Unfortunately, I think the preview links aren't resolving anymore. Could we perhaps republish them on the preview-server @RLHecht?

**Comment by jenstrickland** [comment]
Do you have prod links available?

**Comment by kelsonic** [comment]
@jenstrickland Good question! I actually don't know but Randi or @stephorkandatx might! 🙂

**Comment by RLHecht** [comment]
@kelsonic @jenstrickland Those preview links above will still work but put them in without the https:// when in Drupal.

**Comment by kelsonic** [comment]
That worked! Thank you!!

**Comment by jenstrickland** [comment]
The Full Accessibility & 508 Office Audit would need the live page links in production.

**Comment by ncksllvn** [comment]
@jenstrickland  We have a step in our continuous integration that steps through our generated sitemap and executes an Axe Check on every listed page.

For an example, click the `accessibility` node on http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-website/detail/master/6963/pipeline/154

![image](https://user-images.githubusercontent.com/1915775/82232774-0cf8c800-98fd-11ea-8d59-cb31e4047b82.png)

If you click that, the output will list every page it processed - 

![image](https://user-images.githubusercontent.com/1915775/82232842-2437b580-98fd-11ea-86ae-095c0e51a116.png)

**Comment by ncksllvn** [comment]
It looks like the Axe Check executes with the `section508`, `wcag2a`, and `wcag2aa` settings.

**Comment by jenstrickland** [comment]
@ncksllvn Awesome! Does it open all hidden content before running the axe check?

**Comment by ncksllvn** [comment]
@jenstrickland No, it's a generic test, so it doesn't apply any page-specific behavior to toggle state. It just loads the page in a browser, then executes the axe check.

**Comment by jenstrickland** [comment]
Looping in @1Copenut — is this sufficient? Iirc, the tests are supposed to open all hidden content and run the axe check.

**Comment by ncksllvn** [comment]
Is it specifically just the accordions that we want to toggle? That could be a way to rephrase the ask here...In the standard axe check for all content pages, also toggle accordion content and re-execute the axe check. Seems feasible. It wouldn't be feasible to have a specific E2E test written for every page on the website though. There are almost 600.

**Comment by kelsonic** [comment]
I'm assuming this means that we still need to do the following but just want to confirm:

```
 Check color pairing for proper contrast (required)
 Check for colorblindness issues (required)
 Zoom to 200% and confirm readability, no info cut off, etc (required)
 Repeat for 300% (required)
 Repeat for 400% (required)
 Navigate all pages and core functionality with keyboard only (required)
 Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox (required)
```

It would be great if we could figure out a way to automate ^^ tasks for if we ever release a feature that includes 10+ content page modifications/additions, this process may have a very high LOE

**Comment by ncksllvn** [comment]
We would have choice but to automate those tasks. Page-specific tests for everything from Drupal is just too high of a LOE.

Ideally, this test would be done as a pre-publish validation in Drupal, so no content can ever be published unless it passes 508. This would be a Drupal task though. We already incorporate the Axe Check into page previews but it's non-blocking and doesn't test on hidden content.

**Comment by jenstrickland** [comment]
Yes, each of the items in the checklist need to be completed and certified by checking the checkbox before requesting a staging or full accessibility review. 

These are not tasks that can be automated. Accessibility checks can only be automated to about 50%. Manual testing is part of the ATO requirements. What we tend to do for larger projects is a smart selection of the work, as it is impossible to check the hundreds of pages we often have come through. The dozen pages of the AMA efforts are viable, whereas the hundreds of pages of the VAMC or eBenefits 686 form becomes untenable.

**Comment by ncksllvn** [comment]
> These are not tasks that can be automated.

Ah yeah, I phrased my previous comment poorly. What I meant by "We would have choice but to automate those tasks" is that all of the pages would have to be automated the same way if we were to try, because it wouldn't be feasible to write an e2e test for each page.

**Comment by ncksllvn** [comment]
But okay, so then to boil down what's being asked here...

1. We want the Axe Check in CI to also test hidden content, like accordion content
1. We want to do manual testing on all these pages as described [above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8697#issuecomment-630281773)

**Comment by jenstrickland** [comment]
@ncksllvn 

1. Yes
2. Manual testing as listed in the checklist [in the initial comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8697#issue-612001590)

**Comment by 1Copenut** [comment]
@ncksllvn Weighing in after a short discussion with Jennifer.

If there's a way to extend the automated CI axe checks to look for hidden content (accordions) and open then, then run the axe check, that'd be great. I'd like to see that work get estimated and moved ahead. I anticipate it will be a long-tail effort and would need to be rolled out in waves to identify potential breaks, fix them slowly, and add the enhanced testing to another block of content URLs.

The manual testing should be done on as many pages as possible, but that comes up against hard limits fast. In cases where the page count goes much over 10-12, I look for those pages that have the most unique features, are most highly trafficked via analytics, or have the most complex content "shape". Things like detailed images, maps, data tables, lots of hidden content, are good candidates for pages to be manually reviewed.

It's a lot like security in that it's not possible to scour every URL, every line, but by making it a group effort for manual work, and adding smart automation, we can improve our coverage.

**Comment by kelsonic** [comment]
Done with auditing each page (with the exception of using VoiceOver and keyboard navigation for https://www.va.gov/decision-reviews/multiple-party-claims/)! I've attached the results to the end of the ticket's description 🙂

**Comment by kelsonic** [comment]
Main Findings:

1. Each page had this ChromeLens issue:

![image](https://user-images.githubusercontent.com/12773166/82347569-0cbc0380-99b5-11ea-990c-84c03309fe50.png)

2. Each page (except 1) had these axe issues:

https://user-images.githubusercontent.com/12773166/82346352-91a61d80-99b3-11ea-8b64-953a2fed2520.png

3. No zoom, keyboard navigation, or VoiceOver issues were found.

**Comment by jenstrickland** [comment]
🥇 Thanks for doing this, @kelsonic ! It's cool to see the sidebar on the pages. Those weren't displayed in the preview versions I reviewed previously. 

- Don't worry about providing screenshots of things, and the global issues (like the Feedback button, main navigation, footer headings, veteran banner) don't need to be documented at all because they're already ticketed and assigned to VSP. Y'all just need to check the boxes in the checklist, and write issue tickets to document anything that is actually an issue. I'm happy to help, so feel free to ping me anytime.
- The background-color "error" that comes up in the axe scan asks for a manual scan to determine if it is an issue or not (they generally aren't, but the automation says to check them, so I just select the checkbox that says it's not an issue). 
- I don't recommend using ChromeLens for the accessibility scan, because Google's tool isn't reliable (the aria on that breadcrumb is `<a aria-current="page" href="/decision-reviews">Decision reviews and appeals</a>` and that is valid). 

When I do my full review, I'll document issue tickets for the sidebar headings to get those into the backlog before sending to the VA 508 Office.

**Comment by stephorkandatx** [comment]
@jenstrickland is this ok to close out?

**Comment by jenstrickland** [comment]
I haven't done the full accessibility review or sent to the VA 508 Office. Is it ready for me to review and send?

**Comment by stephorkandatx** [comment]
Yes, I believe this is ready for review

@kelsonic please confirm this is ready for review on Jen's part. Thanks!

**Comment by kelsonic** [comment]
@stephorkandatx @jenstrickland Yes, I commented here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8697#issuecomment-631747965 Is there something that's missing?

**Comment by jenstrickland** [comment]
I'm not sure if anything is missing due to the format.

I'll get started on the full review, and send it over to the 508 Office.

**Comment by kelsonic** [comment]
How can I format it better for you in the future? 🙂 @jenstrickland

**Comment by jenstrickland** [comment]
In the future, just check the checkboxes to certify you did those things. If you found any issues open an issue ticket, then provide a linked list of those issues beneath the checklist. Also, disregard anything in the global nav, footer, and things like the Foresee button — unless you want to search the Issues to see if it isn't already ticketed. If the issues found are sitewide / design system / components / forms, assign those to one of those labels, and include it as a known issue.

I felt so bad when I saw this, because I could see how much work went into documenting this. 😭

**Comment by stephorkandatx** [comment]
@jenstrickland with the checkboxes in place, are we able to close this out on our side or does it need to remain open for the time being?

**Comment by jenstrickland** [comment]
@stephorkandatx — I need to do the full review and send to VA 508 Office before this is closed.

**Comment by jenstrickland** [comment]
@stephorkandatx 

VSA full accessibility audit complete, with three new issues documented. 

Sent to VA 508 Office for review, June 16. I'll let y'all know what their report says.

**Comment by jenstrickland** [comment]
I'm going to reopen this one, while we await the VA 508 Office report. 🤞  it is a all-okay and we'll just close this again. That's what I aim for.

**Comment by jenniferlee-dsva** [comment]
the appears completed. closing.
