### ISSUE TITLE
Payment History VBA MVP 1.5 - Update Debt card header, description and more

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#86972]
## Issue Description

Debt Card header & description updates & va-icon updates (don’t forget fancy colors)

@josephrlee can help with this PR. 

Here is the link to the [CodePen Summary page](https://codepen.io/team/Debt-Team/pen/rNgqxLY).

Here's a link to the [Figma Summary page](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2266-19932&t=xhjKBInT3WrdtGyS-1):

Here is a screenshot of the updated card component: 
![va-card screenshot](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/cadde249-cc47-4021-825a-08635d62658c)

Here is a hard-coded example card to pull these updates from:

```
            <va-card show-shadow="true" class="vads-u-padding-x--3 vads-u-padding-y--2 vads-u-margin-bottom--3 hydrated" data-testid="debt-summary-item">
              <h2 class="vads-u-margin-top--0 vads-u-margin-bottom--1p5 vads-u-font-size--h3">Chapter 35 education debt</h2>
              <p class="vads-u-margin-top--0 vads-u-margin-bottom--1p5 vads-u-font-size--md">
                <span class="vads-u-font-weight--normal">
                  Current balance:
                </span>
                <strong>$930.00</strong>
              </p>
              <div class="vads-u-display--flex vads-u-align-items--center vads-u-margin-bottom--1p5">
                <!-- TODO: Change to va-icon in production -->
                <i aria-hidden="true" class="fas fa-exclamation-triangle fa-md vads-u-margin-right--0p5 vads-color-warning-dark"></i>
                <span class="sr-only">Warning</span>
                <p class="vads-u-margin-y--0 vads-u-font-size--md">Pay your balance now or request help by <strong>April 1, 2024</strong>.</p>
              </div>
              <p class="vads-u-margin-y--0 vads-u-font-size--md"><a class="vads-u-font-weight--bold" data-testid="debt-details-button" aria-label="Check details and resolve this Chapter 35 education debt">Check details and resolve this debt<i aria-hidden="true" class="fas fa-angle-right fa-md vads-u-margin-left--1"></i></a></pc>
            </va-card>
```

Here is the [Debt Summary Card file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx).

[This is the file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/debt-letters/const/diary-codes/debtDetailsCardContent.js) that needs to be edited for the `va-icon` updates.

## Tasks
- [x] Update debt card structure according to above code snippet

## Acceptance Criteria
- [x] Card structure and styles have been updated
- [x] Has been validated by design, please add @josephrlee as a reviewer to the PR request 
- [ ] 
## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Initial draft PR passed to Joe [here](https://github.com/department-of-veterans-affairs/vets-website/pull/31043)

**Comment by HeatherRienks** [comment]
Per Planning today, this will roll over and 1pt of effort remains.

**Comment by OptionSelect** [comment]
90% of the way done, working on getting final tests to pass. PR is in review.
