### ISSUE TITLE
Payment History VBA MVP 1.5  -Removal of section on "Current Debts" pages

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#86971]
## Issue Description

Section removal from Current Debts pages (& other text updates + "Need Help")

Need to remove **How To Pay**, **How request help**, and **How to dispute** sections. 

Need to add Need Help component to debt summary and debt detail pages: 

```
      <va-need-help class="vads-u-margin-top--4">
          <div slot="content">
            <p>
              If you have any questions about your benefit overpayment or if you think your debt was created in an error, you can dispute it. Contact us online through <a href="https://ask.va.gov/">Ask VA</a> or call the Debt Management Center at <va-telephone contact="8008270648"></va-telephone> (<va-telephone contact="711" tty="true" /></va-telephone>). For international callers, use <va-telephone contact="6127136415" /></va-telephone>. We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.
            </p>
          </div>
        </va-need-help>
```

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
Shoot @OptionSelect, forgot to mention that I also wanted to remove the `on-this-page` component as well:
<img width="574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--682763e47dd378c6d27902ca3bda27a16be0d1ba/Screenshot%202024-07-16%20at%2010.12.48%E2%80%AFAM.png" alt="Screenshot 2024-07-16 at 10.12.48 AM.png" />

**Comment by OptionSelect** [comment]
Reopening per convo with Joe for removal of OTP component as addendum.
