### ISSUE TITLE
Payment History VBA MVP 1.5 - Custom Back VA link

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#86970]
## Issue Description
NEED TO ADD MORE TO SHELL!
Custom back va-link with text back to all debts

Here the code snippet, can just use the `va-link` component, will need to define the proper URL and the copy based on the designs:
```
          <va-link
            href=""
            icon-name="navigate_before"
            icon-size={3}
            text=""
            class="vads-u-font-weight--bold"
          />
```
Here is the `va-link` [component](https://design.va.gov/storybook/?path=/docs/components-va-link--docs).

Here is the [CodePen mockup](https://codepen.io/team/Debt-Team/pen/rNgqxLY):

Screenshot: 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/bbd5b74e-d98a-4805-acd9-de0134af3826)

[Figma mockup.](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2266-19932&t=0A5wQ6ENgB0pCHz4-11)

The `URL` and `text` needs to be editable. 

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by josephrlee** [comment]
@mgleo, we might need to remove this ticket then based on the midpoint feedback. What do you think?

**Comment by mgleo** [comment]
Correct, should be closed based on IA feedback [#87951](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87951)
cc @Tom-Davis

**Comment by josephrlee** [comment]
Okay, I'm marking this as closed then!
