### ISSUE TITLE
Define attributes for Hardened (content-defined) Form patterns

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-team#86977]
## Description
To publish forms that meet the criteria defined by the VA-form team, we need to understand the set of attributes an editor is responsible to control and content constraints defined within the specific content-defined form patterns. 

## Addtional information
   - Veteran personal information
   - Veteran identification information
   - Veteran mailing information
   - Veteran contact information
   - Statement of truth
   - Additional hardened form patterns
- [ ] Identify the set of attributes and content (if any) that the editor is required to manage
```[tasklist]
### Tasks
- [ ] Confirm the list of hardened form-patterns to be supported in the form engine for MVP
- [ ] Identify the set of attributes and content, if any, the editor is required to manage within the form engine
```

**Comment by Karak888** [comment]
Cindy to update this list per grooming 7/17/24
