### ISSUE TITLE
Payment History VBA MVP 1.5 - Check details link refactor

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#86973]
## Issue Description

Currently, the `<Link/>` component used in the [Check details link](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx#L38-L53) refactor to use [va-link](https://design.va.gov/storybook/?path=/docs/components-va-link--docs) component. 

It needs to be an active link. Ideally something like this: `<va-link active href="#" text="Text goes here" />`

## Tasks
- [x] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_

## Testing
- [x] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>
