### ISSUE TITLE
DBC request for Alert Banner for Chapter 33 Debts 

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#86976]
## Issue Description
Per Denise Coveyduc, the VA is moving to a new system for processing Post 9-11 Chapter 33 financial transactions. This may impact debt balances that a Veteran will see across the debt portal and DMC would like to add a message to inform Veterans to call should they have any questions during this time. 

**This will only impact Chapter 33 debts so can/should appear specifically when a Veteran is reviewing their Chapter 33 debt on the portal.**

**DMC would like to add a message - they described it as a 'banner' that stays active until July 19, 2024**

They would like the message to read as follows:

 _"VA is transitioning to a new system for processing Post 9-11 Chapter 33 financial transactions. Due to this transition, Chapter 33 debt balance information may not reflect recent payments you have made by check, credit card, or ACH.  If you believe your Chapter 33 debt balance does not reflect recent payments, we encourage you to contact the Debt Management Center: at www.ask.va.gov or call 800-827-0648, after 07/12/2024. Your payment will not be considered late and will reflect the date received once system updates are completed. This message only applies to Post 9-11, Chapter 33 debts."_ 

Many of the alerts/messages we have done in the past are placed on the unauthenticated side and live on a content page but this one will involve our FE team.

[Here's the mockup](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2245-30022&t=ZdCkMZPhLpCjyE1g-11), need to use the slim warning alert:
<img width="705" alt="Screenshot 2024-06-26 at 1 49 39 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/d584dce7-1f69-4fd9-82bc-6b18017eb779">

Here's the code snippet: 

```
  <va-alert
    class="vads-u-margin-bottom--2"
    close-btn-aria-label="Close notification"
    disable-analytics="false"
    full-width="false"
    slim
    status="warning"
    visible="true"
  >
      <p className="vads-u-margin-y--0">
        VA is transitioning to a new system for processing Post 9-11 Chapter 33 financial transactions. Due to this transition, Chapter 33 debt balance information may not reflect recent payments you have made by check, credit card, or ACH. If you believe your Chapter 33 debt balance does not reflect recent payments, we encourage you to contact the Debt Management Center: at  <va-link
      href="https://ask.va.gov/"
      text="ask.va.gov"
    /> or call  <va-telephone
    contact="800-827-0648"
  />, after 07/12/2024. Your payment will not be considered late and will reflect the date received once system updates are completed. This message only applies to Post 9-11, Chapter 33 debts.
  </va-alert>
```

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by HeatherRienks** [comment]
Not sure if this will help at all, but here is an old ticket (#47674) when DMC asked us to add a pop up re: debt relief due to a hurricane. See PR's that were merged in.

**Comment by amponce** [comment]
Merged and closed
