### ISSUE TITLE
Define attributes for the single response (SR) pattern 

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-team#86975]
## Description
To publish forms that meet the criteria defined by the VA-form team, we need to understand the set of attributes and content an editor is responsible to control for the single response pattern https://design.va.gov/patterns/ask-users-for/a-single-response

```[tasklist]
### Tasks
- [ ] Work with MD and VA-facing forms team to understand the usage guidelines for the SR pattern
- [ ] Work with MD and VA-facing form teams to understand the attributes and content requirements for the individual components that make up the SR pattern   
- [ ] Document attributes and guidelines as required features for MVP, post MVP or guidelines the VA-froms team still needs to resolve use-cases
```
## Additional information
[Single select pattern components](https://design.va.gov/patterns/ask-users-for/a-single-response)
   - Label header
   - Label hint text
   - Component patterns
         - Input text
         - Text area
         - Checkbox
         - Radio button
         - Memorial date
         - Number
         - Comb box[ (USWDS V3)](https://designsystem.digital.gov/components/combo-box/) or Search input [(VADS)](https://design.va.gov/components/search-input)
         - Statement of Truth[ (USWDS V3)](https://design.va.gov/storybook/?path=/docs/uswds-va-statement-of-truth--docs)

**Comment by Karak888** [comment]
cindy has some of the guidelines but not all but she will add that to ticket. and a list of components included in this pattern.
