### ISSUE TITLE
[FE] Mount a new profile wrapper that will be responsible for showing either the old or new Profiles

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8698]
Related Epic: [Support showing Profile v1 or Profile 2.0 at the same route #8691](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8691)

## Tasks
- [ ] Make changes to src/applications/personalization/profile360/profile-360-entry.jsx to mount a new profile wrapper that will be responsible for showing either the old or new Profiles. We might need to stop using `startApp()` to bootstrap the app and instead roll our own solution for a wrapper that will do the following:

## Acceptance Criteria:
- [x] Be a Redux-connected component that determines which profile to show depending on the value of the profileShowProfile2 feature flag and a URL param/local storage value.
- [x] Based on the combination of feature flag + local storage/URL param it will render either the src/applications/personalization/profile360/containers/VAProfileApp.jsx or the src/applications/personalization/profile-2/components/ProfileWrapper.jsx
- [ ] Handle setting up the correct routes for React Router depending on if we are showing the old or new profile. The old profile doesn't really need React Router as it only has a single route.
The new Profile 2.0 will need to have its sub-page routes set correctly.
    - This task is the trickiest and biggest unknown at this point. We need to change the child routes that the React Router app has access to after the app has spun up. But we also need to be able to do this when we disable the [Direct Deposit link and route](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8571) and disable most routes when the user is LOA1 (no ticket for FE work, but [this is the design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8570)).

**Comment by sanlouise** [comment]
@mshea0606 Hi Matt, whenever you have a moment, could you validate this ticket?

**Comment by mshea0606** [comment]
@sanlouise looks good!
