### ISSUE TITLE
Quick Reference for survey question connections

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#86982]
## Purpose
Request:  Create a quick-reference document that connects each question to a specific Team and/or Area
Matt gets this question often and a handy resource would help w/ that

## Tasks
- [ ] Create reference chart in Confluence
- [ ] Share w/ Matt via Slack

## Acceptance Criteria
- [ ] Chart is easy to understand with clear references and connections
- [ ] Chart is shared out w/ Matt

**Comment by gopixelsgo** [comment]
This item will roll over to next sprint so that the work can be completed and team can review it.

**Comment by gopixelsgo** [comment]
This item will roll over to next sprint for completion.
