### ISSUE TITLE
[DevOps] Discovery on Vista API ECR resources

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#86988]
## Description
What repositories do we have in place? Are we using the registry functionality? What are our policies for access, lifecycle, etc?

## Tasks
- [x] [DevOps] Figure out what we're using and need to continue to utilize within ECR in `vaec-cms`.
- [x] [DevOps] Document findings in this thread.

## Acceptance Criteria
- [x] Comprehensive understanding of our ECR usage is detailed in this thread.

**Comment by ndouglas** [comment]
Repositories:
- `oss/datadog/agent`: assume this can be replaced or something. I think this includes a workaround for an issue that may be solved now.
- `vagov/wildfly`: no notes
- `vagov/certificates`: see #86156, #87125.
- `vagov/vista-api`: built on wildfly, it looks like
