### ISSUE TITLE
YARDoc rake

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#86984]
## Issue Description
implement a rake ~~and github action~~, [using yardoc](https://rubydoc.info/gems/yard/file/README.md), to identify missing documentation of the code base - modules, classes, functions, class variables
the github action should emit a warning (for now) on a PR if an issue is found or there is less than 100% in changed files.

an [example](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_intake/service.rb) is in `lib/lighthouse/benefits_intake` (which itself has some errors currently)

---
## Tasks
- [x] create a rake action to run and report results of `yardoc`; should accept a file glob to override defaults in `.yardopts`
- [x] update `.gitignore` for any generated documentation folder/files
- [ ] ~~create a github action to run `yardoc` and issue a warning (see `danger` and line of code)~~

## Acceptance Criteria
- [x] rake action available to be run locally
- [ ] ~~github action runs as part of PR CI/CD (non-blocking)~~

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/86984?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by wayne-weibel** [comment]
https://github.com/lsegal/yard/issues/1007
https://github.com/zverok/yard-junk
https://gist.github.com/zverok/52243ead26db4ab32e9a352c1d8e7677

**Comment by wayne-weibel** [comment]
dropping the github action portion per https://dsva.slack.com/archives/CBU0KDSB1/p1720805607090989?thread_ts=1720799371.236729&cid=CBU0KDSB1
