### ISSUE TITLE
Remove everything related to "Account" if profile is turned on

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8699]
Related Epic: Support showing Profile v1 or Profile 2.0 at the same route #8691

## Tasks

- [x] remove the Account link in the user drop down menu
- [x] change how the `/account` route behaves. Either have it automatically redirect the user to `/profile/account-security` or maybe the better solution is change the content of the Account page to tell the user that the account features live on the new Profile.
- [x] consolidate the Profile and Account links at the bottom of the My VA Dashboard into a single button https://github.com/department-of-veterans-affairs/va.gov-team/issues/8400

**Comment by erikphansen** [comment]
@mshea0606 @tressaellen @Samara-Strauss How do you all think that we should handle the `account/` route when the new Profile, with its `profile/account-security` route, is active? I figure we can either:
- automatically redirect the user to the new route. we could start with a client-side redirect and then after we are live to 100% of users we could implement a more proper server-side 301 redirect.
- or, keep the `account/` route and change the content to tell them that the account has moved to `profile/account-security` (and optionally auto-redirect after a handful of seconds)

**Comment by Samara-Strauss** [comment]
> automatically redirect the user to the new route. we could start with a client-side redirect and then after we are live to 100% of users we could implement a more proper server-side 301 redirect.

Option 1 please!

**Comment by mshea0606** [comment]
@erikphansen I also prefer option 1

**Comment by tressaellen** [comment]
+ to option 1!

**Comment by erikphansen** [comment]
@mshea0606 @tressaellen @Samara-Strauss Also: I planned to remove Account option from the user dropdown entirely, but maybe it should stay and just direct users to the new `profile/account-security` section instead? If anyone is used to getting to the account section from the dropdown it'll leave people feeling very lost if that option is removed. ¯\_(ツ)_/¯

**Comment by Samara-Strauss** [comment]
I think it is OK to remove.
