### ISSUE TITLE
[Design] Debt Letters - Interviews Summary and Requirements 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#8700]
## Problem description. 
In order to design a landing page for debt letters, the current process and pain points for debt letter generation and process flow needs to be understood and documented. 

## Goal
_Process flow for debt generation, process flow and desired outcome for displaying debt letters information to veterans online 

## Objectives or Key Results this is meant to further
- _Allow Veterans to see the information of how debt was incurred, the amount of the debt and remediation steps tehy need to take 
---
## Tasks
- [x] _Summarize research findings from interviews with call center and stakeholders. 
- [x] _Create process flow and suggestions for next steps 
## Acceptance Criteria
- [x] _Document summarizing what the requirements are in showing debt letters information on-line
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
I've uploaded [the discovery readout from the interview sessions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/research-readout.md) onto GH. I've sent the document to @rebeccawalsh to add anything I may have missed or expound the takeaways I wrote.

**Comment by rebeccawalsh** [comment]
I've uploaded the[ first iteration of the process flow for debts to GH](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/research/discovery-may20/debt-process-flow-v1.jpg).

[It can also be seen in Miro here](https://miro.com/app/board/o9J_ksQjicc=/).

Requirements:
- Original debt amount
- Debt origin
- Debt balance
- Date debt was incurred
- Due dates (before more letters / further action)
- Payment history
- Downloads of DMC letters
- Directions for repayment
- Next steps for disputes, waivers, or compromises
