### ISSUE TITLE
Release Tracking - SEpic #75716 Portal Overall FE/BE Logic Shift

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#87013]
## Tasks
- [ ] (S)Epic #[75716](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75716) Portal Overall FE/BE Logic Shift and Code Cleanup
    - **Release Dates**
    - [x] Monday 07/01/24 - 5%
    - [x] Monday 07/01/24 - 0% due to issues discovered
    - [x] Monday 09/30/24 - 5%
    - [x] Tuesday 10/01/24 - 25%
    - [x] Monday 10/07/24 - 50%
    - [x] Wednesday 10/09/24 - 100%

## Acceptance Criteria
- [x] Production testing passed for each phase
## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by OptionSelect** [comment]
Clicked the wrong button sorry!. Flag turned on initially on 7/1 morning.

**Comment by Tom-Davis** [comment]
Upon the 5% release we identified an issue: We are finding is that the data coming from the FE does not match with the data we were coding against. It's tough to tell how much it's different.

We run the form data through 12 files that convert the data for submitting. So far we've worked our way int the 2nd of the 12 files.

Associated tickets:
- [87408](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87408)
- [87575](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87575)

**Comment by Dr-Pongo** [comment]
Just an update on this! We've made a handful of discoveries and changes to the transform logic and we're planning some additional testing before we attempt to go live again. I'll ink some more testing tickets as they are  created!

**Comment by Tom-Davis** [comment]
The release of this initiative has been moved to the end of August or early in September - as a result we are moving the release related tickets back to "ready" and will pull them into the sprint when the release is scheduled.

**Comment by Tom-Davis** [comment]
This will roll over one more sprint as the last % update is scheduled for Wednesday.

**Comment by Tom-Davis** [comment]
The release is complete
