### ISSUE TITLE
Remove settings.js from teamsite header

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#8701]
## User Story or Problem Statement

The [teamsite documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/teamsite/) still lists `settings.js` as a file that is included.  Since https://github.com/department-of-veterans-affairs/vets-website/pull/12264 it no longer exists, so we should not try to include it.

## Goal
No warning/error for failing to load a script that we don't need and that doesn't exist:

![image](https://user-images.githubusercontent.com/2008881/80996344-81f3da00-8df4-11ea-85b7-90f5a4c5a6a4.png)

---
## Tasks
- [ ] Remove `settings.js` from the header that is injected into teamsite pages

## Acceptance Criteria
- [ ] `settings.js` is no longer included in teamsite pages
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laineymajor** [comment]
Blocked. No communication from Teamsite.

**Comment by jilladams** [comment]
Hi - Public Websites team is responsible for helping new sites onboard to have the injected header, and we use TeamSite documentation to guide that process. This ticket is marked as blocked bc no response from TeamSite. Is there a path to removing the settings.js line from the TeamSite docs, or even just adding a supplementary note about the missing file, without TeamSite input?

**Comment by jilladams** [comment]
I learned today that Brad Smelley is a project manager for TeamSite, as well as Sandeep Kumar -- both are willing to talk about issues around TeamSite documentation.

**Comment by rmessina1010** [comment]
Expired. Closing.
