### ISSUE TITLE
[Design] Debt Letters - Create Preliminary Designs Landing Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#8702]
Problem description. After conducting interviews, designs need to be created to present relevant information to the veteran who have incurred debt. ?

## Goal
_Create preliminary designs based on data gathered in interviews. 

## Tasks
- [ ] _Crete designs 

## Acceptance Criteria
- [ ] Preliminary designs for landing page will be created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
dup
