### ISSUE TITLE
Change Mentions of Digital Service@VA to Office of CTO@VA

### ISSUE THREAD

**Issue by taylojill** [department-of-veterans-affairs/va.gov-team#87026]
Reference discovery ticket #75530 - VA changed the name of their Slack work space to Office of CTO @ VA. Three pages have been identified where the name needs to be changed.

### Tasks
- [x] Change mentions of Digital Service@VA to Office of CTO@VA in the pages listed below.
- [x] Add date stamp to pages
- [x] Check pages for blockers
- [x] Prepare pages for deployment
#### Pages
- [x] https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools
- [x] https://vfs.atlassian.net/wiki/spaces/RD/overview
- [x] https://vfs.atlassian.net/wiki/spaces/AP/pages/622067754/Word+list (updated, but page does not publish)

### Acceptance Criteria
- [x] Pages updated and ready for publishing

**Comment by taylojill** [comment]
Three pages updated, one page was in an unpublished space. The other two pages were date stamped and checked for blockers. Ready to publish.

**Comment by jknipes** [comment]
Work is complete, moving to _Closed_
