### ISSUE TITLE
Enable RUM on all applications

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#87048]
## Issue Description
_In order to use the product analytics feature in DataDog, RUM needs to be enabled on our forms._

From Sanja: As we are now making use of RUM in DataDog, sharing these links to be followed to protect data privacy. Anyone working with RUM, especially from engineering, please review:

- https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm&site=gov#modify-the-content-of-a-rum-event
- https://docs.datadoghq.com/data_security/real_user_monitoring/?site=gov
- https://docs.datadoghq.com/real_user_monitoring/session_replay/browser/privacy_options/?site=gov
- And from Robin Garrison: https://github.com/department-of-veterans-affairs/va.gov-team/blob/d399792fae93f49e5de7ad32a5048710b4933b89/platform/analytics/setup-real-user-monitoring.md#privacy

---
## Tasks
- [x] Create flipper for RUM, e.g. https://github.com/department-of-veterans-affairs/vets-api/pull/16748/files
- [x] Enable RUM on all of our forms, e.g. https://github.com/department-of-veterans-affairs/vets-website/pull/29780/files
- [ ] Reach out to Pension or 526 team for solutions to exposing PII

## Acceptance Criteria
- [x] RUM enabled on:
   - [x] 686/674
 ~- [ ] VRE~
  ~- [ ] PCPG~
  ~- [ ] COE~
   - [x] Burial
- [ ] Run test submissions through staging and confirm no PII is exposed
---

**Comment by mjknight50** [comment]
Moving this to backlog as we need to address logging and monitoring issues first.

**Comment by mjknight50** [comment]
What is the status of this ticket?  It has been in-progress a long time.  Do you need help?

**Comment by mjknight50** [comment]
Any update on this ticket?

**Comment by wayne-weibel** [comment]
The process for pension and burial involved asking Steve Albers to create and 'application' in DataDog, then copying the implementation from another form and updating the relevant identifiers.

src/applications/burials-ez/hooks/useBrowserMonitoring.jsx

**Comment by mjknight50** [comment]
One thing to evaluate here is whether or not it will be used.  I feel like we did this for Pension/Burial and the data hasn't been used heavily.

**Comment by steele-lm** [comment]
I (personally) would like to start leveraging the product analytics in DD around user journeys and retention, but we also have GA/Domo for that even if it's potentially less accurate.

**Comment by aplatt-coforma** [comment]
Blocked until #108527 is done

**Comment by aplatt-coforma** [comment]
Per @Mottie - We're waiting on Steve Albers to give us the Datadog initialization code before I can open the pr

**Comment by Mottie** [comment]
RUM enabled in staging... will run through sessions and look for PII/PHI exposures.
