### ISSUE TITLE
Test GA Events for "Submit 686"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8705]
## Goal
Now that we have the names for the different events that fire within the actual 686 application form implemented, we can better track what is happening within the feature and have granular visibility into its behavior after doing testing.

## Tasks
- [ ] Test the event names from the GA team in this ticket (#7560) 

## Acceptance Criteria
- [ ] Events fire successfully with the appropriate names
- [ ] A PR with these changes has been requested
