### ISSUE TITLE
[FE] BUG - date is missing from already field error.

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#87064]
## Description
Since we re-factored to only allowing a single claim per day, we are pushing the error before AUTHing in. This results in our old date stamp that was derived from the appointment start time to be null. To fix this, we should just hard code to the current date since we know that the context would always be today.

## Tasks
- [ ] [FE] fix date
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
@benbrasso-agile6 / @zach-park / @loripusey that bug of the missing date in travel has been fixed and merged, and ready to validate locally or with this screenshot:
<img width="357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8161c51cf0d3ca8fb2a857953b23d46eb863caf/localhost_3001_my-health_appointment-travel-claim__id%3D46bebc0a-b99c-464f-a5c5-560bc9eae287%20%282%29.png" alt="localhost_3001_my-health_appointment-travel-claim__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (2).png" />

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by zach-park** [comment]
LGTM. Thank you!
