### ISSUE TITLE
0781/a: Publish static page updates

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#87076]
## Description
The 0781 has been updated to include the 0781a. The new 0781 launches Friday, June 28.

We need to update the title and user story for the 0781. And we need to remove all mentions of the 0781a.

<details>
<summary>These are the pages we need to update:</summary>

- [About VA Form 21-0781](https://www.va.gov/find-forms/about-form-21-0781/)
     - Add an alert that encourages users to submit the 0781 PDF (since the 0781 online form won't be updated to match the PDF for a number of months)
     - Update this section: When to use this form
     - Remove this section: Related forms and instructions
- [About VA Form 21-0781a](https://www.va.gov/find-forms/about-form-21-0781a/)
     - Confirm this page is deprecated when the new 0781 launches
     - Note: The product team is redirecting this link to the About VA Form 21-0781 page
- [Disability compensation for PTSD](https://www.va.gov/disability/eligibility/ptsd/)
     - Update this section: What does VA consider to be a traumatic event?
     - Update this section: Additional forms you’ll need to submit
- [File additional forms for your disability claim](https://www.va.gov/disability/how-to-file-claim/additional-forms/)
     - Update this section: For a posttraumatic stress disorder (PTSD) claim
     - Update this section: For a PTSD claim based on a personal assault
- [Evidence needed for your disability claim](https://www.va.gov/disability/how-to-file-claim/evidence-needed/)
     - Update this accordion: Posttraumatic stress disorder (PTSD)

</details>

## Resource
[Product team content](https://dvagov.sharepoint.com/:w:/s/vaabdvro/EUS2iZylwKVMvQhOURm_1awBppdkUtbI36pGvkQA8NDbig?e=pd4VmV) (SharePoint)

## Tasks

<details>
<summary>Phase 1: About VA Form 21-0781</summary>

- [x] KF: Update page in Drupal (with support from AP, as needed)
- [x] Product team: Review page with SMEs
- [x] ST: Copyedit and publish

</details>

<details>
<summary>Phase 2: Other pages</summary>

- [ ] KF: Update pages in Drupal (with support from AP, as needed)
- [ ] Product team: Review pages with SMEs
- [ ] ST: Copyedit and publish

</details>

## Criteria
- [x] About VA Form 21-0781 has been updated and published
- [x] About VA Form 21-0781a has been redirected
- [x] Other pages that mention Forms 21-0781 and 21-0781a have been updated and published

**Comment by katherine-fung** [comment]
Hi @aprocik1, I've left my content recommendations for the About VA Form 21-0781 page here. They're ready for your review. Once you've reviewed, I'll let the product team know in the intake ticket and ask them to review and show to relevant SMEs to review. 

https://dvagov.sharepoint.com/:w:/s/vaabdvro/EUS2iZylwKVMvQhOURm_1awBAN7YaOV2TmnYbf_3USmFig?e=FVDyLA 

I'll turn to the 3 other static pages mentioned above in the ticket description.

**Comment by aprocik1** [comment]
Update: Katherine and I discussed this content in a meeting. She's going to share it with the product team to get SME approval.

**Comment by katherine-fung** [comment]
Hi @aprocik1, I've updated the 3 other static pages. 

Here are the in-line revisions: 

[Disability compensation for PTSD](https://prod.cms.va.gov/node/891/revisions/view/871614/901225/visual_inline)

Updated this section: What does VA consider to be a traumatic event?
Updated this section: Additional forms you’ll need to submit

[File additional forms for your disability claim](https://prod.cms.va.gov/node/906/revisions/view/894398/901218/visual_inline)

Updated this section: For a posttraumatic stress disorder (PTSD) claim
Removed this section: For a PTSD claim based on a personal assault

[Evidence needed for your disability claim](https://prod.cms.va.gov/node/907/revisions/view/828965/901217/visual_inline)
Updated this accordion: Posttraumatic stress disorder (PTSD)

**Comment by katherine-fung** [comment]
Hi @saratorres2, 

The product team and VBA stakeholders are still reviewing the copy changes for the "About Form 21-0781" page, but when the page is ready for review, I'll let you know in this ticket and on Slack. 

The preview link to review will be: http://preview-prod.vfs.va.gov/preview?nodeId=6022

Thank you!

**Comment by saratorres2** [comment]
@katherine-fung I've published changes to [About VA Form 21-0781](https://www.va.gov/find-forms/about-form-21-0781/). Many thanks for the context you provided regarding the form!

**Comment by aprocik1** [comment]
@katherine-fung, can I close this ticket? I think the other pages in phase 2 have been updated--right?

**Comment by katherine-fung** [comment]
Yep I'll close this @aprocik1! Added to tracker.
