### ISSUE TITLE
[DevOps] Determine efficient solution for creating mock LoROTA data in DynamoDB

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87078]
## Description
We're going to need to test replication of DynamoDB tables across accounts to support a live switchover from `vaec-cms` to `vaec-cie`. This will involve creating some number of records that are roughly equivalent to production data without containing PHI/PII.

## Tasks
- [x] [DevOps] Determine if there is a better way to accomplish this than literally creating crap in a loop, which would be awful, and document in this thread.
- [x] [DevOps] Create followup ticket(s) to address specifics of this process.

## Acceptance Criteria
- [x] Solution documented in this thread.
- [x] Followup ticket(s) opened to address specifics.

**Comment by ndouglas** [comment]
https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-dynamodb-supports-bulk-imports-amazon-s3-new-dynamodb-tables/

**Comment by ndouglas** [comment]
https://aws.amazon.com/dynamodb/pricing/on-demand/

![Screenshot 2024-07-31 at 6 32 01 PM](https://github.com/user-attachments/assets/35330d4b-c48c-494b-a7c9-396a4a1642f4)

I don't think we are going to import a GB of data (!) but it would be good to do some calculations and figure out how much space our current prod data would occupy at rest, etc, and document these figures in this ticket.

**Comment by ndouglas** [comment]
LoROTA prod currently has 799,993 items, a table size of 1,042,158,881 bytes, and an average item size of 1,302.71 bytes.

**Comment by ndouglas** [comment]
Will follow up in #89287, #90300
