### ISSUE TITLE
[DevOps] Review image scanning results for ECR images in `vaec-cms`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87088]
## Description
A lot of these images appear to be outdated and may have security vulnerabilities. We need to review these to determine the scope and scale of risks to our security, even though some of these images may no longer be in active use anywhere.

## Tasks
- [x] [DevOps] Review security scan results in ECR.
- [x] [DevOps] Document findings in this thread.

## Acceptance Criteria
- [x] Findings (if any) are documented in this thread.
- [x] Followup ticket(s) opened to address.

**Comment by ndouglas** [comment]
| Repository Name                      | Last Pushed | Critical | High | Medium | Low | Info |
| ------------------------------------ | ----------- | -------- | ---- | ------ | --- | ---- |
| oss/amazon/aws-for-fluent-bit        | 09/25/2022  | 0        | 63   | 121    | 33  | 0    |
| oss/datadog/agent                    | 09/26/2022  | 0        | 4    | 43     | 33  | 6    |
| tecnativa/tcp-proxy                  | 03/06/2023  | 4        | 7    | 6      | 1   | 0    |
| vagov/certificates                   | 06/09/2022  | 1        | 5    | 8      | 0   | 0    |
| vagov/chip-api                       | 10/18/2021  | 1        | 9    | 1      | 0   | 0    |
| vagov/clinician_workflow_mock_server | 02/22/2023  | 0        | 2    | 14     | 0   | 0    |
| vagov/eureka-server                  | 07/20/2022  | 1        | 4    | 7      | 0   | 0    |
| vagov/iris                           | 06/14/2022  | 0        | 9    | 125    | 64  | 14   |
| vagov/vista                          | 07/21/2022  | 0        | 9    | 136    | 74  | 14   |
| vagov/vista-api                      | 08/15/2023  | 0        | 5    | 74     | 42  | 8    |
| vagov/vista-heartbeat                | 12/07/2022  | 13       | 213  | 329    | 21  | 582  |
| vagov/wildfly                        | 02/16/2023  | 0        | 3    | 53     | 40  | 5    |
| vagov/cmsapp                         | 08/07/2019  | 22       | 197  | 722    | 417 | 433  |
| vagov/cmsdatabase                    | 08/07/2019  | 1        | 20   | 89     | 44  | 56   |
| vagov/cmsdeploy                      | 03/29/2019  | 22       | 197  | 722    | 417 | 431  |
