### ISSUE TITLE
[Frontend] Incorporate design changes on the 'Select hearing aid batteries' screen

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8708]
## User Story or Problem Statement
How might we iterate on the MDT's design based on VA form limitations and usability test findings?

## Goal
_Incorporate the updated designs on the product selection screens to reflect usability test findings and VA forms limitations_

## Objectives or Key Results this is meant to further
- _Developing MDT_
---
## Tasks
[Please reference the InVision mockup](https://vsateams.invisionapp.com/share/KWX53U12MGX)
- [x] _Remove the radio buttons + progressive disclosure_
- [x] _Update the content_
`Select the hearing aids that need batteries. (h4)
You'll be sent a 6-month supply of batteries for each device you choose below. You can only order batteries for each device once every 5 months.`
- [x] _Remove the chapter title_ 
- [ ] _Reach out to designers as necessary with questions and to confirm UI_

## Acceptance Criteria
- [ ] _UI matches design changes and has been approved by design team_
---
