### ISSUE TITLE
[DevOps] Determine which ECR repository images are actively in use.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87089]
## Description
Followup to #87088.

We have a list of ECR images with vulnerabilities. Which of these images are actually in active use at this time?

## Tasks
- [x] [DevOps] Determine which images are in use at this time.
- [x] [DevOps] Document findings for each image in this thread.
- [x] [DevOps] Open up followup ticket(s) to delete each of those that are not in use at this time.
- [x] [DevOps] Open up followup ticket(s) to perform discovery on addressing vulnerabilities in images in use, prioritized by severity of the most serious issue(s) present in each.

## Acceptance Criteria
- [x] Images in use are determined and documented in this thread.
- [x] Followup ticket(s) opened to delete images no longer in use as described above.
- [x] Followup ticket(s) opened to address discovery on images still in use as described above.

**Comment by olivereri** [comment]
# `VAEC-CMS` ECS Clusters


## tevi-int
| Service Name  | Container |   
|---|---|
| vista-service-int | /vagov/vista:2.1  |   
| vista-api-service-int | /vagov/vista-api:e6d809f7bcbd583261c41acf650b39bdebd70f5b  |  
| eureka-server-service-int |  /vagov/eureka-server:1.0  |   

## tevi-dev
| Service Name  | Container |   
|---|---|
| vista-service-dev | /vagov/vista:2.1  |   
| vista-api-service-dev  | /vagov/vista-api:c7d8608cfdb4795ed8dbdf6a1b4784842e7d7000  |  
| eureka-server-service-dev |  /vagov/eureka-server:1.0  |   

## tevi-staging
| Service Name  | Container |   
|---|---|
| vista-service-staging| /vagov/vista:2.1  |   
| vista-api-service-staging| /vagov/vista-api:c7d8608cfdb4795ed8dbdf6a1b4784842e7d7000  |  
| eureka-server-service-staging|  /vagov/eureka-server:1.0  |   

## tevi-prod
| Service Name  | Container |   
|---|---|
| vista-api-be-service-prod | /vagov/vista-api@sha256:8b74b617457198c08afc398cb43dadef4fe4e29205bedf0463ff340b26543cf7 |    
| vista-api-fe-service-prod | /vagov/vista-api@sha256:8b74b617457198c08afc398cb43dadef4fe4e29205bedf0463ff340b26543cf7 |  

# ECS Containers in Use list:
- vagov/vista
- vagov/vista-api
- vagov/eureka-server

**Comment by olivereri** [comment]
I attempted to use Amazon Athena to query Cloudtrail event history but VAEC Project teams don't have access to the S3 bucket that stores events, so athena can't query it. A CVS export of all the `BatchGetImage` events doesn't include the resource ARN of the image repository. A JSON export of the events is over 100mb in size and I'm unsure how to query that.

Thankfully, Cloudwatch records `RepositoryPullCount` metrics for all the ECR repositories:

![image](https://github.com/user-attachments/assets/703f18ed-896c-4193-aee4-b00c98871b53)

This confirms that the only images in use are:

* vagov/vista
* vagov/vista-api
* vagov/eureka-server
