### ISSUE TITLE
[DevOps] Create README for `master` branch of `octo-vista-api`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87080]
## Tasks
- [x] [DevOps] Create README in `master` branch, mentioning:
  - [x] New development is occurring in the `main` branch.
  - [x] `master` branch is being left intact as a known-working checkpoint for recovery purposes.

## Acceptance Criteria
- [x] README created as detailed above.

**Comment by ndouglas** [comment]
Forgot to mark that I had done this. This was trivial so I'd normally estimate it at 0 but gave it a 1 because it required a PR and approval.
