### ISSUE TITLE
Access CXI Data set for AskVa Data

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#87092]
## Issue Description
Veteran Support must have access to the CSI dataset in PowerBI to confirm the accuracy of the data source and confirm data validation 
---
## Tasks
- [x] Determine server owner 
- [x] Validate data in CXI
- [x] Determine how data is ingested to confirm sources 

## Acceptance Criteria

 - [x] **Scenario: Access CXI Data set for AskVa Data**
  - Given the GraphQL mutation is implemented
  - When the mutation is called with input parameters
  - Then the mutation should return the acceptance criteria for accessing the CXI dataset and confirming its accuracy
- [x] **Scenario: Determine server owner**
  - Given a task to determine the server owner
  - When the task is completed
  - Then the server owner should be identified
- [x] **Scenario: Validate data in CXI**
  - Given a task to validate data in CXI dataset
  - When the task is completed
  - Then the data validation should be confirmed
- [x] **Scenario: Determine how data is ingested to confirm sources**
  - Given a task to determine how data is ingested into the CXI dataset
  - When the task is completed
  - Then the data sources should be identified and confirmed
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by newworld2616** [comment]
CXI data reviewed. WE received access for PBI and Advance find.
