### ISSUE TITLE
DR | Removed old, unused, feature toggles

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#87096]
## Value Statement

**_As a_** Benefits Decision Reviews developer
**_I want to_** remove old, unused, feature toggles
**_So that_** we can reduce tech debt

---

## Background Context

We use feature toggles to release features; but, after they are toggled on and our release has stabilized we no longer need the toggle. Extra code within the apps make it more difficult to read.

## Acceptance Criteria

- [ ] All old feature toggles removed from DR
- [ ] All tests passing

## Tasks

- [ ] Old feature toggles removed from NOD
- [ ] Old feature toggles removed from HLR
- [ ] Old feature toggles removed from SC
- [ ] Update unit tests
- [ ] Remove feature toggles from mock data

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
PRs opened and needs review.

**Comment by eileen-coforma** [comment]
No one will verify this, but can be closed.
