### ISSUE TITLE
Medallia - Turn off intercept survey on Appointments urls

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#87097]
## Issue Description
The team managing the Appointments application has requested to disable the site-wide A11y intercept survey on all their URLs because it triggers too early in the user journey.

```
https://va.gov/my-health/appointments/schedule/type-of-care
https://va.gov/my-health/appointments/schedule/audiology-care
https://va.gov/my-health/appointments/schedule/sleep-care
https://va.gov/my-health/appointments/schedule/eye-care
https://va.gov/my-health/appointments/schedule/facility-type

https://va.gov/my-health/appointments/schedule/location
https://va.gov/my-health/appointments/schedule/how-to-schedule
https://va.gov/my-health/appointments/schedule/clinic
https://va.gov/my-health/appointments/schedule/preferred-date
https://va.gov/my-health/appointments/schedule/date-time
https://va.gov/my-health/appointments/schedule/reason
https://va.gov/my-health/appointments/schedule/contact-information
https://va.gov/my-health/appointments/schedule/review

https://va.gov/my-health/appointments/schedule/va-request/
https://va.gov/my-health/appointments/schedule/va-request/reason
https://va.gov/my-health/appointments/schedule/va-request/preferred-method
https://va.gov/my-health/appointments/schedule/va-request/contact-information
https://va.gov/my-health/appointments/schedule/va-request/review

https://va.gov/my-health/appointments/schedule/community-request/
https://va.gov/my-health/appointments/schedule/community-request/closest-city
https://va.gov/my-health/appointments/schedule/community-request/preferred-provider
https://va.gov/my-health/appointments/schedule/community-request/preferred-language
https://va.gov/my-health/appointments/schedule/community-request/reason
https://va.gov/my-health/appointments/schedule/community-request/contact-information
https://va.gov/my-health/appointments/schedule/community-request/review
```

---
## Tasks
- [ ] Coordinate with VSignals team to fulfil request
- [ ] Visit each URL and confirm intercept survey does not fire

## Acceptance Criteria
- [ ] site-wide intercept survey has been disabled on listed urls
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
