### ISSUE TITLE
Determine DST and Governance testing responsibilities

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87094]
## User Story
As an a11y specialist supporting Platform, I want to know what my responsibilities are for verifying the component is accessible at a VADS component Staging Review.

Assignee: @briandeconinck @rsmithadhoc 
Peer Reviewer:

## Description
Governance and DST worked together to put together an accessibility testing plan for all VADS components. In this ticket, Governance team and DST will define who is responsible for completing each step of the accessibility testing process.

## Tasks
- [x] Identify which a11y testing will be completed by Governance and which will be completed by DST
- [x] Identify overlapping areas in which both DST and Governance will complete tests
- [x] Verify that all assistive technology previously identified is included in the testing responsibilities

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team and DST have determined which accessibility testing will be completed by each team when a new component goes through Staging Review

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@rsmithadhoc Finally made some edits to the document in Confluence. Summary of my changes:
- Per your comment, I've added a note that DST tests for all variations/error states and Governance tests default variation and spot-checks for other variations.
- I've added a couple of extra "Future: Obtain..." items to the DST list because I think we should lean on Ad Hoc to get you some extra devices/software. If/when that happens we can revisit to either adjust the distribution of tests or not. Even if you're not formally responsible for testing on iOS, for example, you should definitely still have a device to test with outside this process.
- For Dragon on Windows, I'm proposing that I alternate Edge and Chrome for browser compatibility.
- Made some minor edits to specify when something was a full run-through of component features and when it was a spot-check.

**Comment by rsmithadhoc** [comment]
Thanks, looks good to me!
