### ISSUE TITLE
Define Incoming Case Desired Performance Metrics 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#87100]
## Issue Description
Set target amounts for incoming issues to complete per sprint
---
## Tasks
- [ ] Analyze Salesforce incoming cases reporting 
- [ ] Calculate approximate capacity per support representative 
- [ ] Publish to team 
- [ ] Implement tracking of cases activity 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Duplicate #87102
