### ISSUE TITLE
Define Incoming Case Desired Performance Metrics 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#87103]
## Issue Description
Set target amounts for incoming issues to complete per sprint
---
## Tasks
- [x] Analyze Salesforce incoming cases reporting 
- [x] Calculate approximate capacity per support representative 
- [x] Publish to team 
- [x] Implement tracking of cases activity 

## Acceptance Criteria

 - [ ] **Scenario: Incoming Case Desired Performance Metrics**
  - Given the incoming case desired performance metrics are defined
  - When the team analyzes Salesforce incoming cases reporting and calculates approximate capacity per support representative
  - Then the team should publish the target amounts for incoming issues to complete per sprint
- [ ] **Scenario: Implementing tracking of cases activity**
  - Given the team has published the target amounts for incoming issues to complete per sprint
  - When the team implements tracking of cases activity
  - Then the team can monitor and adjust performance metrics accordingly
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Calculations are approximately 75 cases closed per support rep daily. 
225 daily
1,125 weekly 
58,500 Annually 

for tracking - @kimberley will create a daily activity salesforce report and track for metrics - housed on VA side in Teams.

**Comment by Kimberley2023-CSM** [comment]
Team Daily Activity | Salesforce
