### ISSUE TITLE
Update Governance process for DST Staging Reviews

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87104]
## User Story
As an accessibility specialist supporting Governance team and the Collaboration Cycle, I want to update/modify the process I follow at Design System Staging Reviews so that it includes my responsibilities for upholding the Accessibility Testing Plan and updating the accessibility component checklist, if needed.

Assignee: @briandeconinck 
Peer Reviewer:

## Description
Governance and DST have finalized their accessibility testing plan for VADS components, and have determined how the accessibility component checklist will be updated for each component change, prior to the Staging Review. The purpose of this ticket is to update the operational process that Governance follows for completing a Design System Staging Review. 

### Live pages
- 

### Drafted pages
- [How to complete an Accessibility review for Design System staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3446472729/How+to+complete+an+Accessibility+review+for+Design+System+staging+review)

## Tasks
- [x] Write internal guidance on how to complete an accessibility review for design system components.
   - Should be consistent with:
      - The accessibility testing plan defined earlier in this initiative
      - [The division of testing responsibilities agreed to between Governance and DST](https://vfs.atlassian.net/wiki/spaces/DST/pages/3356295187/Accessibility+Testing+Responsibilities)
      - [Existing documentation for accessibility reviews of VFS products](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2059763776/How+to+complete+an+Accessibility+review+for+Staging+review+touchpoint)

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Governance operational process for supporting a Design System Staging Review has been updated to align with the Accessibility Testing Plan
- [x] The Governance operational process for supporting a Design System Staging Review has been updated so that changes to the accessibility component checklist are documented as as Staging Review finding.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by rsmithadhoc** [comment]
@briandeconinck 
One thing I'm thinking of for a testing doc (started something in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3071/files), is how much detail we go into for each one. For example:
- Keyboard compatibility - should we detail each subcategory:
  - Tab order - the tab order follows a logical sequence that matches the visual layout.
  - Focus indicator - that focus indicators are visible and clearly indicate which element is currently focused.
  - Interactive elements - (blurb about that)
  - Etc. 

Or do we outline a testing procedure:
- Keyboard compatibility
  - Tab through the page - (sentence or two about what to look for)
  - Activate page elements - (sentence or two about what to look for)
  - Navigate within elements - Arrow keys, etc. (sentence or two about what to look for)
  - Modals - Keyboard trap within, etc. (sentence or two about what to look for)

Or both? - here's what we look for, plus here's the procedure we follow to do that.

**Comment by briandeconinck** [comment]
Created [internal guidance for Governance team](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3446472729/How+to+complete+an+Accessibility+review+for+Design+System+staging+review), mostly repurposing existing documentation and then adding some extras just for VADS components. I think I'll want to review/refine a few times as we test components but I think this is a solid MVP.

No peer reviewer assigned and this is really just for my use at this time, so closing as complete.

**Comment by shiragoodman** [comment]
thanks, Brian. I'd like to find time this week to get an update on where we are with this initiative. I will reach out on Slack.
