### ISSUE TITLE
Define Incoming Case Desired Performance Metrics 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#87102]
## Issue Description
Set target amounts for incoming issues to complete per sprint
---
## Tasks
- [x] Analyze Salesforce incoming cases reporting 
- [x] Calculate approximate capacity per support representative 
- [x] Publish to team 
- [x] Implement tracking of cases activity 

## Acceptance Criteria

 - [x] **Scenario: Incoming Case Desired Performance Metrics**
  - Given the incoming case desired performance metrics are defined
  - When the team analyzes Salesforce incoming cases reporting and calculates approximate capacity per support representative
  - Then the team should publish the target amounts for incoming issues to complete per sprint
- [x] **Scenario: Implementing tracking of cases activity**
  - Given the team has published the target amounts for incoming issues to complete per sprint
  - When the team implements tracking of cases activity
  - Then the team can monitor and adjust performance metrics accordingly
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
After analyzing the data, it has been determined that each of the Support team members can process 60 - 70 cases per day across all CRMs.  Notification of the proposed case closure will be published in the next Support team synch.  

Case performance metrics will be included in the "Tracking per Sprint" documentation provided to leadership each sprint.

**Comment by ATMiddleton** [comment]
<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXlQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cefd7d1c7f682234e9b6331e29b7de08311bc26/image.png" alt="image.png" />
