### ISSUE TITLE
[DevOps] Discovery on CodeQL operational issues in `octo-vista-api`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87111]
## Description

CodeQL is not operating correctly in `octo-vista-api`. Why? I have no clue, and I don't speak Java, so this will take some time to address.

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/bba2245b-e1ad-4749-87e1-1552a8346a21)

## Tasks
- [ ] [DevOps] Try to figure out what the heck is going on and how this might be addressed.
- [ ] [DevOps] Open followup ticket(s) to address.

## Acceptance Criteria
- [ ] Followup ticket(s) opened to address problems.
