### ISSUE TITLE
[DevOps] Discovery on security issues reported in `octo-vista-api`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87110]
## Description
`octo-vista-api` is reporting some security issues. I don't speak Java, so this will take some time to figure out what is going on.

## Tasks
- [ ] [DevOps] Determine what is going on and how to address each issue.
- [ ] [DevOps] Open followup ticket(s) for each addressable issue.

## Acceptance Criteria
- [ ] Followup ticket(s) opened for addressable issues.
