### ISSUE TITLE
[DevOps] Determine a strategy for handling VA RCA and ICA certificates in Docker images.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87125]
## Description
Currently, `octo-vista-api` has resources to build a Docker image containing VA certificates. This of course requires manual action to update the repository. Is there a better way of doing this?

## Tasks
- [x] [DevOps] Figure out a good approach here.
- [x] [DevOps] Document the approach in this thread.

## Acceptance Criteria
- [x] The best approach to take to handle these certificates is documented in this thread.

**Comment by ndouglas** [comment]
Possibly relevant to #86156.

**Comment by ndouglas** [comment]
I think I'd rather use Packer or something like that than rawdog the Docker CLI. It's just nicer to be able to write this sort of thing declaratively.

**Comment by ndouglas** [comment]
I think we can just `s3 cp` the `combined.pem` into the appropriate folder.
