### ISSUE TITLE
[Frontend] Update content in the product eligibility alert component 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8712]
## User Story or Problem Statement
How might we iterate on the MDT's design based on usability test findings?

## Goal
_Update the eligibility alert component displayed on both the 'Select hearing aid batteries' and 'Select hearing aid accessories' screens for products that Veterans are currently ineligible to reorder_

## Objectives or Key Results this is meant to further
- _Developing MDT_
---
## Tasks
Please reference the InVision mockups: [Select hearing aid batteries](https://vsateams.invisionapp.com/share/KWX53U12MGX) | [Select hearing aid accessories](https://vsateams.invisionapp.com/share/R8X540UYX32)
- [ ] _Remove the 'additional info' component from the ineligible product alert boxes for hearing aid accessories_
- [ ] _Remove the 'additional info' component from the ineligible product alert boxes for hearing aid accessories_
- [ ] _Reach out to designers as necessary with questions and to confirm UI_

## Acceptance Criteria
- [ ] _UI matches design changes and has been approved by design team_
---
