### ISSUE TITLE
Launch the Platform Satisfaction Survey

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#87132]
## Purpose
Step through the tasks to prep, launch, run, and synthesize the quarterly survey

## Tasks
- [x] Launch Survey in Optimal Workshop
- [x] Confirm Survey's visibility & data funneling
- [x] Update Confluence Documentation
- [x] Update Platform website documentation

## Acceptance Criteria
- [x] Confluence documentation is updated
- [x] Platform website documentation is updated
- [x] Survey is live
