### ISSUE TITLE
Add "Decision Log" for all product outlines

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87168]
## Background
In a CAIA sync we discussed adding a decision log to our product outlines.

## Tasks
- [ ] Update product outlines for Find, Appoint, and Widget to include a decision log
- [ ] Share with team, enablement and CAIA to see if I'm missing anything

## Acceptance Criteria
- [ ] Product outlines for Find, Appoint and Widget all have accurate decision logs.

**Comment by oddball-lindsay** [comment]
First pass - figured a [Slack canvas](https://dsva.slack.com/docs/T03FECE8V/F07BVFABTAA) was easier for this early stage.  Will dig through Slack messages tomorrow for the remaining references, and to make sure I'm not missing any key decisions/updates.

**Comment by oddball-lindsay** [comment]
Reviewed the following and captured all decisions/updates:
1. Emails with stakeholders/advisors
2. ARM+CAIA meeting notes
3. ARM Leadership Sync meeting notes
4. OCTO+Lighthouse meeting notes

Will request team review on Monday, with a review date of EOD Friday 7/19.

**Comment by oddball-lindsay** [comment]
Draft is removed from Slack and Decision and Change Log content has been added to Github:
1. [Find a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/decision-change-log-find-a-representative.md)
2. [Representative Status Widget](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/decision-change-log-representative-status-widget.md)
3. [Appoint a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/decision-change-log-appoint-a-representative.md)
4. [Content Information and Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/decision-change-log-content-and-information-architecture.md)
5. [5901](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/5901/decision-change-log-5901.md)
