### ISSUE TITLE
BE | Profile | Direct Deposit | Excessive updates for a single user

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#87184]
## Background
Joe Niquette was looking to create a widget which shows when an ICN completes a direct deposit change more than 3 times in 90 days or less (for the fraud team). He found that some users have submitted direct deposit changes over 20 times, with one user submitted 223 direct deposit changes in the last month.

His thought is that some of these logs are being recorded incorrectly, and has asked us to look into why there are so many [logs for this user](https://vagov.ddog-gov.com/logs?query=%28ppiucontroller%20OR%20ch33bankaccountscontroller%20OR%20PaymentInformationController%20OR%20DisabilityCompensationsController%29%20%28%22update%20request%22%20OR%20%22create%20request%22%20OR%20%22destroy%20request%22%29%20env%3Aeks-prod%20&agg_m=count&agg_m_source=base&agg_q=%40icn&agg_q_source=base&agg_t=count&cols=%40remote_ip.geoip.country.name%2C%40payload.user_uuid%2C%40named_tags.remote_ip%2C%40payload.sso_cookie_contents.credential_used%2C%40payload.sso_cookie_contents.patientIcn&event=AgAAAZBSUVb3v1G2iQAAAAAAAAAYAAAAAEFaQlNVV0VSQUFEdmRSZEJTMDNjSndBWgAAACQAAAAAMDE5MDUyNTMtMjg5YS00Yzk3LTk2MjktODNhYzBhMDkxZjE2&fromUser=false&messageDisplay=inline&panel=%7B%22queryString%22%3A%22%40icn%3A1015862239V419043%22%2C%22filters%22%3A%5B%7B%22isClicked%22%3Atrue%2C%22source%22%3A%22log%22%2C%22path%22%3A%22icn%22%2C%22value%22%3A%221015862239V419043%22%7D%5D%2C%22timeRange%22%3A%7B%22from%22%3A1716928762000%2C%22to%22%3A1719520762000%2C%22live%22%3Atrue%7D%7D&refresh_mode=sliding&storage=hot&stream_sort=%40payload.sso_cookie_contents.credential_used%2Casc&top_n=10&top_o=top&viz=query_table&x_missing=true&from_ts=1716928642409&to_ts=1719520642409&live=true).

## Tasks
- [ ] Determine why these users have a large number of updates.
- [ ] Document discovery
- [ ] Review with Joe and Profile team

## Acceptance Criteria
- [ ] Determine the cause of the issue.
- [ ] Tickets created to fix issue (if necessary).

**Comment by tpharrison** [comment]
Not sure what is causing this issue or if this is legitimate activity.   Joe Niquette is going to have the fraud team reach out to the user.
