### ISSUE TITLE
[DevOps] Create global Terraform module in `checkin-devops`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87188]
## Description
Some AWS resources depart from the standard IaC paradigm and exist one-to-one with the account, or _could_ exist many-to-one but don't because it simply serves no benefit.

These resources should exist in a separate module, with separate workflows, with its own state. It should apply _only_ on `main`, and _only_ plan in all other situations.

## Tasks
- [x] [DevOps] Create global Terraform module (`terraform/global`).
- [x] [DevOps] Create backend for global module.
- [x] [DevOps] README in directory explains purpose.

## Acceptance Criteria
- [x] Global Terraform module exists.
- [x] Backend for global module exists.
- [x] README exists explaining purpose.

**Comment by ndouglas** [comment]
This is now verified to work, although it currently does nothing.
