### ISSUE TITLE
[DevOps] Create workflow to apply global module on pushes to `main`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87190]
## Description
Followup to #87188.

## Tasks
- [ ] [DevOps] Create GHA workflow that applies global module on:
  - [ ] pushes to `main`
  - [ ] `workflow_dispatch`
- [ ] [DevOps] Ensure workflow exits with an error on non-`main` branches.

## Acceptance Criteria
- [ ] Workflow applies global module on pushes to `main`.
- [ ] Workflow applies global module on `workflow_dispatch` on `main`.
- [ ] Workflow exits with error on any other branch.
