### ISSUE TITLE
[DevOps] Create workflow to plan global module on PRs touching files in global module.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87192]
## Description
Followup to #87188.

## Tasks
- [ ] [DevOps] Create workflow that `plan`s global module on PR touching files in that module only.

## Acceptance Criteria
- [ ] Workflow runs `terragrunt plan` on PR touching files in global module only.
- [ ] Workflow comments in PR with plan output.
- [ ] Workflow does not run when PR does not touch relevant files.
