### ISSUE TITLE
[DevOps] Move Datadog API Key secret name into `global_data` Terraform module.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87199]
## Description
Currently this is hardcoded in `global.hcl` as a string.

## Tasks
- [x] [DevOps] Use `data.aws_secretsmanager_secret` or whatever instead of a hardcoded string.
- [x] [DevOps] Create output in `global_data` for parameter.
- [x] [DevOps] Change per-env configurations to reference `global_data` output instead of hardcoded string from `global.hcl`.

## Acceptance Criteria
- [x] Environment configs reference `global_data` instead of hardcoded string.
