### ISSUE TITLE
[DevOps] Create `global_iam` Terraform module.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87202]
## Description
Followup to #87188.

This module will create an IAM role and policy for the `global` Terraform user.

## Tasks
- [x] [DevOps] Create a module in`terraform/global_iam`.
- [x] [DevOps] Declare the Terraform backend.
- [x] [DevOps] Create a README to explain why this is needed.

## Acceptance Criteria
- [x] Module exists.
- [x] Backend exists.
- [x] README exists.

**Comment by ndouglas** [comment]
This works and is sufficient for basic operations.
