### ISSUE TITLE
[DevOps] Create `global` Terraform IAM role and policy.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87201]
## Description
Followup to #87188.

For use exclusively by the `global` module.

## Tasks
- [x] [DevOps] Create `global` IAM role.
- [x] [DevOps] Create `global` IAM policy.

## Acceptance Criteria
- [x] Role exists
- [x] Policy exists
- [x] Permissions are sufficient to allow Terraform state updates, etc.
