### ISSUE TITLE
Enforce case insensitivity for json schema repo filenames

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87215]
## User Story
As the enforcers for JSON schema filenames, 
We need to create a new repo rule to not allow files with the same name while being case sensitive, 
So that no more GIT issues are caused to users on the Apple OS.

## Issue Description
The Platform Product team has identified that there are inaccuracies and inconsistencies in the JSON schema repo regarding case sensitivity. Using GHA workflow, the Platform Product team needs to enforce case insensitivity for JSON schema repo file names. A repo rule will be added to not allow files with the same name while being case sensitive, since this causes git issues on Macs.

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] Clarity around standards in JSON schema repo
- [ ] New documentation outlining the standards in the JSON schema repo
- [ ] 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
