### ISSUE TITLE
Redis POAM: Analysis of Redis application, current state (Milestone 3)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87224]
## User Story
As the Managers of the Redis tool,
We need to understand the current state of Redis, to include "at rest" and "in transit" settings
So that the Redis work can be scheduled and will begin. 

## Issue Description
Redis product-team level security risk was registered on 5/31/2024, due to not meeting encryption and password protection in the current Redis environment. The team needs to create a timeline and mitigation strategy, that includes current state of “at rest” and “in transit” settings, in order to understand the work that needs to be done to fix the security risks. 

## Tasks
- [x] Establish current state of “at rest” setting
- [x] Establish current state of “in transit” setting
- [x] Determine **_encryption_** requirements and current state, determine delta/gap
- [x] Determine _**password protection**_ requirements and current state, determine delta/gap
- [x] Determine timeframe for implementing these mitigation tasks

## Success Metrics
There is solid understanding of the work required so that proper estimates can be applied to the timeframe. 

## Acceptance Criteria
- [x] That there is documentation outlining current state of “at rest” and "in transit" settings; encryption and password protection requirements and deltas are understood, and a plan to implement these changes is well outlined and approved. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
10/3/2024 update: write up will be complete today.

**Comment by Kshitiz-devops** [comment]
https://vfs.atlassian.net/wiki/spaces/PPT/pages/3511812097/Analysis+of+Redis+Application

**Comment by jennb33** [comment]
10/7/2024 update: @flooose to review then @LindseySaari will review.

**Comment by jennb33** [comment]
10/8/2024 update: This work is complete; @LindseySaari will need to review the documentation (https://vfs.atlassian.net/wiki/spaces/PPT/pages/3511812097/Analysis+of+Redis+Application) but the ticket can be closed.
