### ISSUE TITLE
Redis POAM: Perform upgrades and testing post-fix - DEV environment (Milestone 5)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87229]
## User Story
As the Managers of the Redis tool,
We need to perform the identified upgrades in various environments after the fixes are complete,
So that the Redis POAM work is tested and complete. 

## Issue Description
Redis product-team level security risk was registered on 5/31/2024, due to not meeting encryption and password protection in the current Redis environment. The team needs to upgrade and test in the various environments to ensure that the fixes identified by the audit (ticket [87224](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87224)) can be completed. 

## Tasks
- [ ] Perform upgrades to Redis
- [ ] Test in the DEV environment
- [ ] Document the upgrade process for future state reference.

## Success Metrics
That the DEV environment gets the upgrade and is tested appropriately.

## Acceptance Criteria
- [ ] That the DEV environment is upgraded successfully and all identified issues are fixed or mitigated. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
10/8/2024 - we will be using [93500](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93500) to perform this work. Closing this ticket as a duplication.
