### ISSUE TITLE
SME written feedback for VBA payment history (survey)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#87233]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The UX team has created a survey for SMEs to provide written feedback on the VBA payment history mockups. 
The team will use this feedback to make adjustments to the mockups. 

---
## Tasks
- [x] _What work is necessary for this story to be completed?_
- [x] The survey is created
- [x] The team analyzes the feedback
- [x] The team asks follow up questions to SMEs by email
- [x] The team makes changes to the mockups based on the feedback

## Acceptance Criteria
- [x] _What will be created or happen as a result of this story?_
- [x] Refinements to mockups
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlottecesana** [comment]
Hi everyone, we had several VBA payment history UX working sessions based on the SME feedback we received through the survey. It was very helpful in informing changes we have now made to the mockups, in addition to the design intent feedback. We will be following up with an email that Bob or Denise can forward to the SMEs with the updates we made based on their feedback tomorrow. Thank you! 
cc: @josephrlee @mgleo @Tom-Davis @HeatherRienks @denisecoveyduc
