### ISSUE TITLE
SME written feedback for VBA payment history (survey)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#87231]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The UX team has created a survey for SMEs to provide written feedback on the VBA payment history mockups. 
The team will use this feedback to make adjustments to the mockups. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] The survey is created
- [ ] The team analyzes the feedback
- [ ] The team makes changes to the mockups based on the feedback

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] Refinements to mockups
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Duplicate of #87233
