### ISSUE TITLE
Expose VA.gov Platform Build Metrics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8724]
## High Level User Story/ies
As a VFS team, I need to see and understand available build metrics on my product so I can use the data to make product decisions, communicate to the team's developer as quickly as possible, and improve my product's performance.

As a VSP team, I need to expose the appropriate and available build metrics to VFS teams so that VFS teams can more easily act on my feedback on VA.gov quality standards.

## Hypothesis or Bet
**If** _we determine an approach for and follow through on exposing build metrics for VFS teams_ **then** _we expect VFS teams to more easily act on VSP's feedback and more VFS applications to meet our quality standards more often_.

## VSP OKR
- Customers meet the VA.gov platform's standards for consistency and quality 
- Customers use qualitative and quantitative user data to build new and refine existing Veteran Facing Services (VFS)

## Definition of done

- [ ] VSP has a plan on which metrics should be captured and why
- [ ] VSP knows how to store & expose the data
    - Dependency for this epic
- [ ] VSP has a plan for who the audience for these metrics should be & how they will consume the data

---
## Background
VSP Front End Tools has an engine (Circle CI) to give an overview of what's happening in the Build process. VSP Analytics & Insights has a BI Tool (Domo) and will have a data warehouse (BigQuery)that can potentially expose and store this data. VSP Analytics & Insights' vision is to ensure that VFS teams use the right data, and can help/work together with Front End determine the strategy for exposing these metrics. 

**How might we push the right experience to the right people?**

### Additional Questions
- What are we trying to show VFS teams about using the platform?
    - Is that something we want to manage on the micro or macro level?
    - Are the code quality things we're trying to push on the individual developer level?
    - Are there things on the individual manual level?
