### ISSUE TITLE
Profile: Sprint 41 (7.17.2024-7.30.2024) 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#87306]
## Sprint Links
[Previous Sprint ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86914) 
[Next Sprint ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88295)

## PTO
- _Is anyone out?_ 
- Tom 1 PTO day at some point 

## Sprint Goals
- Launch Ch33 changes w/the Single Unified Form! 
- New Team Member Onboarding 
- MHV feature toggle extravaganza 

### BE
- [x] #88488
### Design
- [x] https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/534
- [x] #80803
- [x] #80805
### FE
- [x] #88484
### PM
- [x] #79907
- [x] #80858
- [x] #80859
### BE
- [x] #88024
- [x] #88558
### Design
- [x] #85867
### FE
- [ ] #74837 - new developer environment connection issues, delayed because of getting plugged into vetsapi rolled but almost finished
### FE
- [x] #85580
- [x] #85761
- [x] #88185 (added after sprint start)
- [x] #88187 (added after sprint start)
## MHV&DS Logon Credential Retirement 
- [x] #88653 (added after the sprint start) 
## IES 
- [ ] #89420 - added late expected to roll
### FE
- [ ] #87384
### BE
- [x] https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/15
- [x] #88556
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89160

## notes on sprint 
- 16 issues added at sprint start, 14 show up in ZH, 2 are in different repositories 
- 1 unplanned item added 
- added design work for IES toward the end of sprint expected to roll
