### ISSUE TITLE
Record short video for Midpoint Review touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87302]
## User Story
As a VFS team member with an upcoming Midpoint Review meeting scheduled, I want to know what is expected of me and my team prior to the meeting so that I can ensure we are prepared.

As a VFS team member with an upcoming Midpoint Review meeting scheduled, I want to know what to expect in the meeting so that my team can be prepared and get the fullest value from the 30 minute meeting.

As a VFS team member who just completed a Midpoint Review meeting, I want to know what is expected of my team post-meeting so that I can be sure my team takes the appropriate action.

Assignee: @erinrwhite @KKitagawa-Bosch 
Peer Reviewer: @briandeconinck 

## Description
Governance team understands that people learn and absorb information in different ways - some people prefer to read text, some people prefer to hear and/or see it explained, and others might learn best from experience. While we can't currently support the latter, we are betting that introducing a short 2-3 minute video into existing context will better help VFS teams understand what is expected of them and what to expect within the process. This will hopefully result in less confusion with the VFS, less questions asked within office hours and support channels, and greater understanding of Platform processes.

We have already created a short video for the Design Intent and Staging Review. We also completed research on the video and plan to use the [findings](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3059908610/Design+Intent+short+video+Research+Findings) from the research to create a video for Midpoint Review that meets teams expectations. 

The purpose of this ticket is to draft a script, prepare a visual aid, record a video and embed the video within the Midpoint Review touchpoint page. 

Governance team reviewed the [Pain points, Recommendations, and Opportunities](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2809626855/Pain+points+Recommendations+and+Opportunities) documented by Service Design team during their DI research study. Several of their findings should be taken into consideration while working on this ticket for Midpoint Review, including:

- DI prep: Long process
- DI prep: Lots to absorb
- Documentation: Context around the documents and expectations is not as clear
- DI Review Meeting: What to expect

### Questions to answer in the video
As a VFS team member, I want to know...

- When should I schedule a Midpoint Review?
- How do I schedule a Midpoint Review?
- What should my team do to prepare for the Midpoint Review?
- Where can I go to ask questions ahead of time?
- Who should be included at the Midpoint Review?
- What should I expect during the MPR meeting?
- What should I expect after the MPR meeting?

## Impacted Artifacts
MPR touchpoint page

## Tasks
- [x] Write MPR script
- [x] Prepare visual aid
- [x] Record the video
- [x] Embed the video into the MPR touchpoint page

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have recorded an informational video about the Midpoint Review and embedded it into the Midpoint Review touchpoint page on Platform Website

## Team Notification
- [X] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
The team at Midpoint Review on 7/11 did not include mobile web designs. We plan to discuss with Matt to see if this should be a required artifact. In order to not block this ticket from moving forward, we should plan to record this MPR video at a high level and not include granular details so we don't have to rerecord later.

**Comment by erinrwhite** [comment]
### Draft artifacts in progress
- [MPR video script]()
- [MPR video slide deck](https://docs.google.com/presentation/d/170AnFegRQoJeCeB2GRpej4-3e7TiX1ychRD2C0gXoH8/edit#slide=id.p1)

### Tickets for other short videos
- **Design intent:** #75014
  - [DI video script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2972352514/75014+-+Design+Intent+video+script)
  - [DI video slide deck](https://docs.google.com/presentation/d/1wX1cj4tKC1GW4ZHR0_TX9BxwRKR6O67uDUpLG7IDMlI/edit#slide=id.p1)
- **Staging review:** #80427 
  - [SR video script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3148808241/80427+-+SR+Short+Video+Script)
  - Couldn't find the SR video slide deck

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch first draft of script and slide deck are ready for your edits!

[MPR video script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3314679885/87302+-+Record+short+video+for+Midpoint+touchpoint+page)
[MPR video slide deck](https://docs.google.com/presentation/d/170AnFegRQoJeCeB2GRpej4-3e7TiX1ychRD2C0gXoH8/edit#slide=id.p1)

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite made edits to both! All minor things, just changing a few things to active voice and using "you" in one of the headers (in order to make it active voice lol)

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch this looks good! 

@shiragoodman any feedback before we move into the recording stage? 😄

**Comment by shiragoodman** [comment]
@erinrwhite I added a few comments. Please lmk if you have any questions.

**Comment by erinrwhite** [comment]
thank you @shiragoodman! Back to you @KKitagawa-Bosch - updates to the script are noted in comments on the page. Think it's ready to move to recording? Let me know how I can support...

[MPR video script](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3314679885/87302+-+Record+short+video+for+Midpoint+touchpoint+page)
[MPR video slide deck](https://docs.google.com/presentation/d/170AnFegRQoJeCeB2GRpej4-3e7TiX1ychRD2C0gXoH8/edit#slide=id.p1)

**Comment by KKitagawa-Bosch** [comment]
Uploaded, just need the final peer review from @erinrwhite and we should be done!

**Comment by erinrwhite** [comment]
[MPR page updated in confluence](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+Review) is looking good! awaiting publishing today 👍🏻 

[Video is also up in YouTube](https://www.youtube.com/watch?v=zgq17Rs1UdM) and captions QA'd.

Let's check in at 3:30 Eastern to make sure the changes have published, then this one'll be good to close.

**Comment by erinrwhite** [comment]
@briandeconinck [ready for your peer review!](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)

**Comment by briandeconinck** [comment]
This all looks great!

**Comment by erinrwhite** [comment]
Fantastic! Closing.... cc @KKitagawa-Bosch

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch would you be willing to share this with #platform-governance-team on slack? this one has a team notification!

**Comment by KKitagawa-Bosch** [comment]
Done!
