### ISSUE TITLE
Survey Documentation Review and Additions

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#87312]
## Issue Description

The following tasks are miscellaneous documentation work that need to be done to to "finish" the pages we have right now. 

---
## Tasks
- [x] Organize "working" documents to a separate section
- [x] Validate information with Aubrey for targeting parameters
- [x] Add pre-approved questions to How to request a digital survey

## Acceptance Criteria
- [x] All tasks listed above are completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
[Survey Compilation.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e079dac50f09d401572faae6b94a9b143c92ed0/Survey%20Compilation.xlsx)

**Comment by UXCamG** [comment]
[Compilation Visuals ](https://www.figma.com/design/Fn2gJC78zHP6ptofM94MDT/Medallia-Survey's?node-id=0-1&t=On9SaHqzK8lEfgjl-1)

**Comment by ATMiddleton** [comment]
Survey compilation document (https://docs.google.com/document/d/1_8sZAVvWVGCqYto9wh7pegRmmpqOExZG/edit#heading=h.p37dosse8wld) - published to Confluence https://vfs.atlassian.net/wiki/spaces/Contact/pages/3292528642/Veteran+Support+Medallia+Surveys+Compilation

**Comment by ATMiddleton** [comment]
Pre approved questions link added to "How to request a VSignals survey on VA.gov" (https://vfs.atlassian.net/wiki/spaces/Contact/pages/1793556578/How+to+request+a+VSignals+survey+on+VA.gov)
