### ISSUE TITLE
Document design and details for all VA.gov surveys

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#87311]
## Issue Description
As part of the ongoing effort to update our documentation for VA.gov surveys, we will create a page that lists out all the existing surveys on VA.gov and includes details on targeting parameters, where is resides, and either links to the survey or provides screenshots if a link is not possible. 

Add page that lists out all VA.gov surveys that includes the questions, link to the survey if possible, but if not, include screenshots of the survey.
Organize "working" documents to a separate section.
Validate information with Aubrey for targeting parameters
Add pre-approved questions to How to request a digital survey

---
## Tasks
- [ ] Compile information for all VA.gov surveys that we manage that include the following: targeting parameters, urls where survey "lives", POC for the survey owner (i.e. if it was requested by a specific team), and then links to the survey. If links are not readily available because it is an intercept survey, we will need screenshots. 
- [ ] Publish information to confluence in accordance with desired organizational structure.  

## Acceptance Criteria
- [ ] A new confluence page with all the information listed above. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Combined with #83712
