### ISSUE TITLE
Document design and details for all VA.gov surveys

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#87310]
## Issue Description
As part of the ongoing effort to update our documentation for VA.gov surveys, we will create a page that lists out all the existing surveys on VA.gov and includes details on targeting parameters, where is resides, and either links to the survey or provides screenshots if a link is not possible. 

---
## Tasks
- [x] Compile information for all VA.gov surveys that we manage that include the following: targeting parameters, urls where survey "lives", POC for the survey owner (i.e. if it was requested by a specific team), and then links to the survey. If links are not readily available because it is an intercept survey, we will need screenshots. 
- [x] Publish information to confluence in accordance with desired organizational structure.  

## Acceptance Criteria
- [x] A new confluence page with all the information listed above. 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
https://vfs.atlassian.net/wiki/x/AgBAx

**Comment by clantosswett** [comment]
@ATMiddleton thanks for pulling this together. Let's plan to talk through this when we meet to improve the formatting and readability of this information.
