### ISSUE TITLE
[DevOps] Determine initial list of end-to-end tests for LoROTA.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87319]
## Description
Followup to #86891.

After we have requirements for end-to-end tests, we should create a list of end-to-end tests to implement.

## Tasks
- [x] [DevOps] Determine a list of end-to-end tests covering the core operations for LoROTA.
- [x] [DevOps] Document these tests in this thread.
- [x] [DevOps] Open followup tickets for implementing each of the tests.

## Acceptance Criteria
- [x] A list of end-to-end tests has been created in this thread.
- [x] Followup tickets have been opened for implementing each of the tests.

**Comment by ndouglas** [comment]
Currently I have just one test, which creates a claims token, passes that to LoROTA, and receives a valid JWT in response. This demonstrates that:
- I can invoke the API Gateway
- my API key works
- the API Gateway can invoke the Lambda
- I understand the token generation process
- LoROTA can retrieve the public key for my client from Secrets Manager
- LoROTA can verify the signature on my claims token as belonging to my test client
- LoROTA can respond, and 
- that the response is returned in a reasonable amount of time
 
Additionally, incidentally, I can see log entries in Datadog indicating that the Datadog Log Forwarder is handling API Gateway logs successfully and the Datadog Lambda Extension is handling Lambda logs successfully.

**Comment by ndouglas** [comment]
- `postData`:
  - `will create a valid data entry`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - verify UUID returned
  - `will fail to create an invalid data entry`:
    - generate a claims token with `write.full`
    - POST invalid data to LoROTA
    - verify that LoROTA returns an appropriate error response
 - `will fail to create an entry with an invalid scope`:
    - generate a claims token with an invalid scope
    - POST valid data to LoROTA
    - verify that LoROTA returns an appropriate error response
- `getData`:
  - `will retrieve basic data`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with scope `read.basic`
    - GET data with the aforementioned UUID
    - verify the basic data structure is returned and is correct
  - `will retrieve full data`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with scope `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
  - `will not retrieve data with an invalid UUID`:
    - generate a claims token with scope `read.full`
    - GET data with a random UUID
    - verify that LoROTA returns an appropirate error response
- `patchData`:
  - `will update data with valid scope`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with scope `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
    - generate a claims token with `write.full`
    - PATCH a change to the data with a valid UUID
    - generate a claims token with scope `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
  - `will not update data with invalid scope`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with scope `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
    - generate a claims token with an invalid scope
    - PATCH a change to the data with a valid UUID
    - verify that LoROTA denies the request and returns an appropriate error
    - generate a claims token with scope `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
  - `will not update non-existent data`:
    - generate a claims token with `write.full`
    - PATCH a change to the data with a random UUID
    - verify that LoROTA returns an appropriate error
- `putData`:
  - `will update data with valid scope`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
    - generate a claims token with `write.full`
    - PUT a change to the data with a valid UUID
    - generate a claims token with `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
  - `will not update data with invalid scope`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with scope `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
    - generate a claims token with `write.full`
    - PUT a change to the data with a valid UUID
    - generate a claims token with scope `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
  - `will not update non-existent data`:
    - generate a claims token with `write.full`
    - PUT a change to the data with a random UUID
    - verify that LoROTA returns an appropriate error
- `deleteData`:
  - `will delete existing data`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with `read.full`
    - GET data with the aforementioned UUID
    - generate a claims token with `delete.full`
    - DELETE a change to the data with a valid UUID
    - generate a claims token with `read.full`
    - GET data with the aforementioned UUID
    - verify that LoROTA returns an appropriate error
  - `will not delete data with an invalid scope`:  
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with `read.full`
    - GET data with the aforementioned UUID
    - generate a claims token with an invalid scope
    - DELETE a change to the data with a valid UUID
    - verify that LoROTA returns an appropriate error
    - generate a claims token with `read.full`
    - GET data with the aforementioned UUID
    - verify the full data structure is returned and is correct
  - `will not delete non-existent data`:  
    - generate a claims token with `delete.full`
    - DELETE a change to an invalid UUID
    - verify that LoROTA returns an appropriate error
- Token Expiry:
  - `will expire a token appropriately`:
    - generate a claims token with `write.full`
    - POST valid data to LoROTA
    - generate a claims token with `read.full` and a short expiry time
    - delay a brief period of time
    - GET data with the aforementioned UUID
    - verify that LoROTA returns an appropriate error    
- Unknown Issuer:
 - `will detect an unknown issuer`:
   - generate a claims token with `write.full`
   - POST valid data to LoROTA
   - generate a claims token with `read.full` and an invalid issuer
   - GET data with the aforementioned UUID
   - verify that LoROTA returns an appropriate error
