### ISSUE TITLE
Implement accessibility defects cards in SR Dashboard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87324]
## User Story
As an OCTO PO, I want to know trends in accessibility defects within the Collab Cycle so that I have data and metrics to report to my leadership.

Assignee: @allison0034 @it-harrison
Peer Reviewer: @KKitagawa-Bosch 

## Description
Governance team and their PO have approved the new cards to be added to the[ Staging Review Dashboard.](https://va-gov.domo.com/page/1340527018?userId=1646566899) The purpose of this ticket is to implement the card changes related to the accessibility defects. See [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720191529751/a3eda30d1910afbad7680620fc08910449197d7c?sender=630af6fa-cd3e-4db3-bcfa-19e6575ed63f) for details. 

## Tasks
- [x] Create a new section in the existing SR Dashboard for accessibility defects. Structure it the same way so that it starts with a questions.
   - Shira's 2 cents - since there are technically 4 cards we're trying to include in 1 section, maybe the question can be generic. "What trends are we seeing in accessibility defects found at Staging Review?" or something like that. I think it might start to look cluttered/messy and be hard to read if we ask a question for each new card.
- [x] Build out the 4 new cards
- [x] Validate that the data is correct by cross comparing with GitHub

Note: Currently only 1 of the cards (Count accessibility severity defect per quarter) is data over a specific timeframe. Are the other cards covering a specific timeframe or are they across all time? For example, is Percent of a11y defects that were a11y defect 0 a percentage of ALL tickets or a percentage from a specific quarter? Or year? Please be sure to include this detail in your cards. Possibly reach out to Martha - what would she like to see in this dashboard? What would be valuable for her?

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have added new cards to the SR Dashboard for:
   - Percent of accessibility defects that were a11y defect 0
   - Percent of accessibility defects that were a11y defect 1
   - Count accessibility severity defect per quarter
   - Time to close accessibility defects
- [x] We have validated that the card data is accurate

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@it-harrison I have created cards on the Domo dashboard but need the data set to be changed for the accessibility data. Look at the Mural and let me know if you have questions. I could not create the last accessibility card without the data set first.

**Comment by it-harrison** [comment]
@allison0034 here are the datasets:
* [a11y defect 0 summary card](https://va-gov.domo.com/datasources/a75cdb71-259a-49e8-8fa3-a4e89e192f3b/details/overview)
* [a11y defect 1 summary card](https://va-gov.domo.com/datasources/baa68406-2717-4d6f-bd66-b98e04540c95/details/overview)
* [count a11y defect severity per quarter](https://va-gov.domo.com/datasources/b035d7c6-af33-4449-9dbb-8685c432d2e7/details/data/table)
* [time to close a11y issues - table](https://va-gov.domo.com/datasources/40110d7e-b457-44e5-9598-a68034d3fabf/details/overview)
* [time to close a11y issues - multi-line chart](https://va-gov.domo.com/datasources/48872163-1f53-409c-8427-632f13d48e21/details/overview)
* [screen reader modality](https://va-gov.domo.com/datasources/5907f065-a800-4bb1-999b-45374c305c8f/details/overview) (not sure if this is included - may need to tweak data)

**Comment by allison0034** [comment]
I was able to get the first 4 in, I will work on the last 2 tomorrow.

**Comment by it-harrison** [comment]
@KKitagawa-Bosch this is ready for review

**Comment by KKitagawa-Bosch** [comment]
Looks good to me! Good to close @it-harrison @allison0034
