### ISSUE TITLE
[DevOps] Determine a list of DevOps metrics we should be recording for CIE.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87326]
## Description
Just standard things, but ATM we have multiple products and I don't think we're actually recording DevOps metrics for any of 'em.

- Delivery Lead Time
- Deployment Lead Time
- CFR
- Deployment frequency
- MTTR
- Unit test coverage
- Vulnerabilities (broken down by repo, image, severity, etc?)
- MTTDetect (security issues)
- Drift Assessment (maybe run prod/stg plan nightly, see if anything pops up?)
- Alerts generated (can we track the alarms that went off? can we track the ones we actually responded to?)
- ???

## Tasks
- [ ] [DevOps] Determine a list of DevOps metrics we should record for this project and document them in this thread.
- [ ] [DevOps] Open followup ticket(s) to address each of these metrics that aren't currently being recorded.

## Acceptance Criteria
- [ ] List of metrics has been determined and documented in this thread.
- [ ] Followup ticket(s) opened to address each metric.
