### ISSUE TITLE
Content Edit: 86759

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#87325]
## Issue Description
Content edits according to support ticket [86759](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86759)
[Current page](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si#VAFormsLibrary-HowtosetupSaveInProgress(SiP)-MyVAPage)

---
## Tasks
- [x] Review support ticket [86759](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86759)
- [x] Contact SMEs
- [x] Update website according to suggestions provided by customer  
- [x] Prepare page for deployment

## SMEs for this work:
_See original ticket author 86759_

## Acceptance Criteria
- [x] VA Forms Library page will be updated to include the changes
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/87325?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by laucon** [comment]
This is done.

**Comment by jknipes** [comment]
Closing this ticket as _Done_

**Comment by jknipes** [comment]
Issue brought into current sprint due to available capacity. Ticket 77027 is _paused_, which allowed for extra capacity
