### ISSUE TITLE
[DevOps] Design GHA workflow(s) for executing end-to-end tests

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87320]
## Description
Followup to #87319. We should be able to execute end-to-end tests to target 1) any environment on 2) any AWS account 3) from any branch.

Ideally, we should be able to execute an individual test as well and perform regular tests on all environments.

This should improve development speed, verification, and usability of end-to-end tests, as well as improve our insight into our products as deployed.

## Tasks
- [x] [DevOps] Determine a list of scenarios for how we might execute end-to-end tests (does not need to be comprehensive) and document in this thread.
- [x] [DevOps] Design a structure of workflows and actions that satisfies the above scenarios and document in this thread.
- [x] [DevOps] Open followup ticket(s) to create local actions as needed.
- [x] [DevOps] Open followup ticket(s) to create workflows as needed.

## Acceptance Criteria
- [x] Scenarios documented in this thread.
- [x] Structure of workflows and actions documented in this thread.
- [x] Followup ticket(s) opened for local actions and workflows.

**Comment by ndouglas** [comment]
This was done as a part of other work
