### ISSUE TITLE
Ask for Review of Onboarding Requirements/Access Requirement Prerequesites

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#87327]
## Description 
Send this doc for review to Ryan McNeil for review as a SME: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/83795

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Send page above for review to Ryan McNeil 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by davidpetras** [comment]
Document has been reviewed by 2 SME's Steven Cumming and Ryan McNeil as well as the Platform Content Team. After resolving comments and making a few adjustments the page has been approved and is now published for all to [see](https://depo-platform-documentation.scrollhelp.site/getting-started/prerequisites-for-access-requests).
