### ISSUE TITLE
Draft lo-fi design of proposed changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87322]
## User Story
As an OCTO lead on Platform, I want to be able to quickly and easily reference metrics on the Collab Cycle Staging Review process so that I can share trends and concerns with my own leadership.

Assignee: @allison0034
Peer Reviewer: @briandeconinck @erinrwhite

## Description
Before we can begin making changes to the SR Dashboard, we must first create some mockups or low fidelity designs of the changes we're proposing. This is so OCTO-DE lead and Governance PO @humancompanion-usds can review and provide feedback before we commit to the changes in Domo.

On June 13, Matt shared his preferences on which Descriptive tags we prioritize in the dashboard. His top 5 priorities are:

- Accessibility defect severity
   - possibly track time to close based on severity
- Design System team review*
   - possibly track count or percentage of tickets per quarter that require DST review
- Modality
   - possibly track distribution of modalities across all issues
   - `modality-screen-reader` has been flagged significantly more than the other issues. Focus only on this?
- Context*
   - possibly track distribution of context across all issues
- Imposter component (yes/no)
   - possibly track count or percentage of tickets per quarter that are imposter
   - also include which components get flagged most often

*Do we have enough data at this time where the metrics would return anything of value?

## Impacted Artifacts
[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720191529751/a3eda30d1910afbad7680620fc08910449197d7c?sender=u870c8d9c6b47768924793768)

## Tasks
- [x] Create a Mural with current dashboard image
- [x] Add cards for the following: Accessibility defect severity, Modality, and Imposter components

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have drafted lofi designs of proposed cards for the SR Dashboard in Domo that feature descriptive tag data
- [x] We have shared our proposed designs with Matt for his review/feedback

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@humancompanion-usds I ran some queries in github to get a better understanding of 2 of the descriptive tags that you prioritized - Design System Review and Context. At this time, there are only 5 Staging Review issues that we've flagged for [DST review. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3Adesign-system-review) Similarly, there are only 23 Staging Review issues that we've flagged with a[ context issue. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=label%3Acontext-flow%2Ccontext-footer%2Ccontext-headings%2Ccontext-navigation%2Ccontext-url).

I think we really need to have a better understanding of how the OCTO Practice area leads would use the context data before we prioritize building a card in our dashboard showcasing this data. With that said, I am asking the team to prioritize the accessibility defect severity, modality (possibly with a focus on screen readers) and imposter components. 

Please let me know if you agree or if you'd like to discuss this further. Thanks!

**Comment by allison0034** [comment]
Created [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720191529751/a3eda30d1910afbad7680620fc08910449197d7c?sender=u870c8d9c6b47768924793768)

**Comment by allison0034** [comment]
@briandeconinck I created a [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720191529751/a3eda30d1910afbad7680620fc08910449197d7c?sender=u870c8d9c6b47768924793768) for you to look at. There are some notes in there. If you think there is anything else that would be useful feel free to comment. I just added things off what was written in the ticket. Most of this was oriented towards accessibility.

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch would you mind taking a look at this and share your thoughts?

**Comment by briandeconinck** [comment]
Left some comments!

**Comment by allison0034** [comment]
@briandeconinck I responded to your comments.

**Comment by allison0034** [comment]
Met with Keegan to walk thru how I do peer reviews : )

**Comment by shiragoodman** [comment]
@allison0034 has the mural been shared with Matt yet? if not, please do so on our team channel by EOD. ty!

**Comment by allison0034** [comment]
@shiragoodman I was waiting for Brian to peer review, but I can go ahead and share.

**Comment by allison0034** [comment]
Shared with Matt via [Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1721239447163989).

**Comment by erinrwhite** [comment]
@allison0034 I took a look and added one comment/idea but not a showstopper at all. Looking good here to close.
