### ISSUE TITLE
[CDP] VBA Notice of Rights and Obligations

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#87352]
## Description

VHA has a button on the detail page of each copay. 
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5a240c00b4de4e701fcd66f7d886494a0716712/Screenshot%202024-06-28%20at%204.01.24%E2%80%AFPM.png" alt="copay button" />

VBA needs a button added on the detail page of each debt to notify users of their rights and obligations. 

## Tasks
- [ ] Task one to complete the work in the description

## Acceptance criteria

- [ ] Item one from the description performs as described in the description

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
duplicate, closing
