### ISSUE TITLE
[CDP] VBA Notice of Rights and Obligations

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#87353]
## Description

VHA has a button on the detail page of each copay. 
VBA does not currently display this information and needs a button added on the detail page of each debt to notify users of their rights and obligations. 

VHA shown below:
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5a240c00b4de4e701fcd66f7d886494a0716712/Screenshot%202024-06-28%20at%204.01.24%E2%80%AFPM.png" alt="copay button" />

## Tasks
- [x] Acquire approved copy
- [x] [Update Figma to match the new copy](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=6091-6369&t=DhhBAQ14wzSDiIyu-1)
- [x] Create Content ticket

## Acceptance criteria

- [x] Figma mockups created with new copy

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
[Notice of Rights and Obligations[26].pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Z4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d44d73bd82d992b7618ca5cf721263f56d7ad03e/Notice%20of%20Rights%20and%20Obligations%5B26%5D.pdf)

**Comment by HeatherRienks** [comment]
Per Refinement, need to gain approval from SME's first, implementation should be easy.

@denisecoveyduc to follow up with SMEs

**Comment by denisecoveyduc** [comment]
**Quick update on this:** I have spoken with Bob on this and he agrees that we need to add VBA information. He is currently in the process of doing a side by side comparison and discussing the information needed with additional representatives at DMC.  We discussed various thoughts around this and it might be something we wait to address until the One VA Debt Letter initiative. Consider this on hold and ok to hang out in the backlog until we hear back from his investigations and define what is truly needed. 
FYSA: @mgleo @Tom-Davis

**Comment by denisecoveyduc** [comment]
Another update on this. There are currently two version of Rights and Responsibilities (VBA and VHA versions). As @mgleo pointed out we are highlighting the VHA version on the copay side of the debt portal currently but not the VBA version.   

Those two versions are being processed through OGC to combine them into one document of Rights and Responsibilities which would be something we include with the One VA Debt Letter PDF.  

As a result I am putting it under that super epic [#84175](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84175) so we tackle this once OGC has approved.
FYSA: @Tom-Davis

**Comment by Tom-Davis** [comment]
@denisecoveyduc we reviewed this in refinement and have it ready to pull in when we have bandwidth - let us know if there were any other updates.

**Comment by denisecoveyduc** [comment]
@Tom-Davis This isn't ready to go as we don't have the copy to include at this point. Bob is working with OGC to finalize text that will support the rights and responsibilities for both VBA and VHA and could be presented to a Veteran. Until we begin work on the One VA Debt Letter (the associated Super Epic) this one is not in scope.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - I think that @digitaldrk now has the configured the disclaimers to display on the PDF. Is this still needed?

cc: @Tom-Davis

**Comment by HeatherRienks** [comment]
We need to confirm with Bob that the verbiage is correct (will be added to the Debt Portal AND the letter)

**Comment by HeatherRienks** [comment]
Per UX, we still need this ticket since we are NOT currently seeing the modal link to it on the VBA side of the Debt Portal.

**Comment by denisecoveyduc** [comment]
**April 30 - Confirmed**. The copy we used for the rights and responsibilities for the one va debt letter can be used to update the modal for both VBA and VHA. I believe there is one modal live today, we can leverage the same to point to from both 'buttons' if we want.

**Comment by mgleo** [comment]
Content source of truth (One VA Debt Letter PDF)

[one_debt_letter_2025-05-12.pdf](https://github.com/user-attachments/files/20208643/one_debt_letter_2025-05-12.pdf)

Existing VHA Rights and Responsibilities 

[Notice-of-rights-responsibilities.pdf](https://github.com/user-attachments/files/20208684/Notice-of-rights-responsibilities.pdf)

**Comment by mgleo** [comment]
Hi @denisecoveyduc and @digitaldrk 
I noticed there are some typos, content, and formatting inconsistencies on the Notice of Rights and Responsibilities/Obligations doc. (One example, we refer to copays as copays, not copayments on VA.gov.)
I made some small updates on the [Figma file](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=6091-6369&t=DhhBAQ14wzSDiIyu-1) but I think the Content team should take a look before I create a FE ticket for implementation.

Content Intake ticket for this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/109740

cc @Tom-Davis @HeatherRienks

**Comment by denisecoveyduc** [comment]
Great catch @mgleo !!!  Thanks for updating and bringing it to CAIA! 🎉
