### ISSUE TITLE
Remove v0 VA controller

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8736]
## Goal
Remove original vets API pathway after migration to v1 Facilities CCP API and v1 Facilities VA API  

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information

## Tasks
- [ ] Remove v0 VA controller
 
## Acceptance Criteria
- [ ] Data is maintained compared to vets API

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@gunsch The facilities team is no longer using the original vets-api. Per the discussion in [#9716](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9716), v0 can be deprecated.

**Comment by gunsch** [comment]
Thanks for the update! One point I'd like to clarify first. I got this message from @davem-va last week:

> Hey, so the Lighthouse team looked to see if anyone is still using the "v0" vets-api facilities API (https://api.va.gov/v0/facilities/va ).  Turns out the answer is yes :disappointed:  The underlying database is getting hit a few thousand  times a day.  As I think you're aware, this is not secured with an api-key so we can't tell who those callers might be.

@mmiddaugh can you help me reconcile your comment with what Dave has said? Are we still seeing traffic to v0 with Facilities no longer using that API? or is your comment a more accurate reflection now?

**Comment by davidconlon** [comment]
Thanks @gunsch - I think all we were trying to say is that Facility Locator has moved to v1 so we should not be the culprit of v0.  We are letting you know that we have moved over to v1 (via flipper) a while back and we are removing the flipper logic soon because we don't need it anymore as a safety blanket.  
Per our conversation about the v1 move a while back, Platform is going to figure out and manage the v0 turn-off, so whenever Platform feels they should 'turn it off and see who yells' feel free? :-)

**Comment by mmiddaugh** [comment]
@gunsch We are still using v0_ccp, although that will also end in the next day or so. But v0_va traffic should not be ours.

**Comment by gunsch** [comment]
cc @alexpappasoddball for the backlog

**Comment by annaswims** [comment]
Form526 depends on the v0 facilities api,and I'm not clear what this ticket means [grafana](http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Ffacilities%2Fva&var-frontend_app=All).  Can you be more clear what you mean by "Deprecate" and what the path forward is?

**Comment by alexpappasoddball** [comment]
@annaswims This is still in the backlog, and based on your feedback it will require more in-depth analysis before we do anything.  We will circle up as a team once we move this ticket along to make sure we fully understand it.

**Comment by mmiddaugh** [comment]
Closing as duplicate to https://github.com/department-of-veterans-affairs/va.gov-team/issues/15091
