### ISSUE TITLE
Enumerate VCR Cassettes to be Re-recorded for Savon Bump

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#87360]
## Issue Description
In order to safely bump the `savon` gem, we need to re-record various specs so that we can tease out what changes were introduced with the latest `savon` version and fix accordingly. This purpose of the ticket is to determine which specs need to be recorded, so that we can more easily estimate the time required to re-record/fix/get associated team's help with the various cassettes.

---
## Tasks
- [ ] Gather the following info for each spec containing broken examples:
  - [ ] Number of Broken examples
  - [ ] Number of Cassettes to modify
  - [ ] Associated team
  - [ ] Method to re-record (locally, ssh, Review Instance, etc), if easily determined

## Acceptance Criteria
- [ ] Requested data is gathered and copied over to #86235 for reference

**Comment by ryan-mcneil** [comment]
Stupid Zenhub duplicated
