### ISSUE TITLE
[VETS-API] Bump ruby 3.2.4 -> 3.3.3

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#87371]
## Issue Description
Ruby needs to be bumped to 3.3+

---
## Tasks
- [x] Bump in Gemfile/.ruby-version
- [x] Bump in Dockerfile
- [x] Bump in codespaces/devcontainer
- [x] Update docs/any other references to 3.2.4
- [x] Confirms app builds/runs and specs pass in respective envs.

## Acceptance Criteria
- [x] Ruby 3.3.3 is deployed to Prod.
