### ISSUE TITLE
Copy of Investigate reason for Puma backlog

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87377]
## User Story
As the managers of the Puma servers, 
It is important to have the optimal configuration in place for Puma servers
So that Vets-API availability remains consistent and high-functioning for those who utilize the APIs. 

## Summary
We have a monitor, [[Prod] [EKS] Puma Backlog](https://vagov.ddog-gov.com/monitors/116657), that notifies us when the Puma backlog is over a threshold for an amount of time. Vets-api pods in EKS spin up in response to this and then scale back down when the backlog has gone down, so there's no immediate action that needs to take place in response. However, the ideal situation is for the Puma backlog to be at zero. Why is there ever a backlog?

As a band-aid solution to quiet this noisy alert, we changed the monitor to average over 15 minutes instead of 5. See https://github.com/department-of-veterans-affairs/devops/pull/13825.

This issue was discussed at BE CoP meeting. [Meeting notes](https://vfs.atlassian.net/wiki/spaces/BCP/pages/2876473345/12+18+23#2%EF%B8%8F%E2%83%A3--Discussion).

There is a [recurring scheduled downtime](https://vagov.ddog-gov.com/monitors/downtimes?id=7cab24d2-82fa-11ee-a5b1-da7ad0900007&sort=-start_dt). The alert gets muted every day from 3-4 ET. Kyle set that up because that was a predictable time of day that it would trigger the alert. 

## Tasks
- [x] Investigate why the Puma backlog is ever greater than zero. 
- [ ] Create design document for Puma servers
- [ ] Make new tickets based on findings. Or if the fix is small, implement it. 
- [ ] Document reasons for Puma backlog and indicate where it is stored **here**

## Success Metrics
- [ ] There is reasoning for the larger Puma backlog
- [ ] There is a documented and approved strategy for addressing the Puma backlog

## Acceptability Criteria
- [ ] Output includes Puma servers design document
- [ ] Documentation is complete for this research
- [ ] New work is ticketed for future Sprints

**Comment by jennb33** [comment]
Unnecessary dupe when trying to roll original ticket. Thanks, ZenHub!
