### ISSUE TITLE
Investigate users properties, for compatibility with LH services

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87378]
## Background
Lighthouse requires a Participant ID for requesting and auto-establishing a POA.  And an EDIPI is required for creating a Participant ID, in cases where the user is missing one.

Lighthouse also only supports non-Veteran claimants that are marked as "dependent" in VBMS.  Any other non-dependent, non-Veteran claimants are out of scope.

## Tasks
- [ ] Understand what % of users have a Participant ID, EDIPI and are marked as "dependent"
- [ ] Confirm that we can see these properties (PID, EDIPI, dependent) in vets-api and tailor the experience based on compatibility with Lighthouse.

## Acceptance Criteria
- [ ] We have confidence that only users who are compatible with LH's request and establish POA services will see the digital submission experience.

**Comment by oddball-lindsay** [comment]
For the Participant ID, submitted a Service Request in the [Information Technology Request Portal](https://jira.devops.va.gov/servicedesk/customer/portal/12/user/login?destination=portal%2F12) as recommended by Damian DeAntonio.  My request **confirmation is CMDMRP-8161**. If I have questions, I can reach out to Dave Hazelbaker (IAM Governance Manager) by emailing IAMServiceRequest2@va.gov.

Also submitted a request to Identity regarding EDIPI and dependent-status: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1759

**Comment by oddball-lindsay** [comment]
My original service request was closed and I was redirected to submit a specific MPI request -- new confirmation is **CMDMRP-8167**.  Asked about PID, EDIPI _and_ dependent status, just in case Identity is unable to assist.

**Comment by oddball-lindsay** [comment]
From Identity, regarding my EDIPI and dependent status requests:

> LOA1 users dont have any verifiable data so they wont have an EDIPI or marked as dependent in VBMS. For the LOA3 users you would need to reach out to IAM (Damien) for the edipi percentage and then a contact from VBMS for the marked as dependent. 

I'll check with Damien tomorrow to see if the EDIPI data is also an SR request with MPI.  For VBMS, I might try Mary Kate Albers.

**Comment by oddball-lindsay** [comment]
Damien said that yes it's the same process for EDIPI as it is for PID, so I'm covered in my original request to MPI.  

He also said EDIPI shouldn't be required to create a ParticipantID: 
> that doesn't make sense.  EDIPI is DoD's unique ID so it shouldnt have anything to do with creating participant ID which is a unique ID assigned by VBA

I'm still curious to try and capture the % of users, and once I know that I'll share the % as well as Damien's thoughts with LH.

Also sent a message to Mary Kate about what % of LOA3 users are marked as "dependent" OR "Veteran" in VBMS.  The remianing % will be the users we cannot assist with digital submission through LH services.

**Comment by oddball-lindsay** [comment]
Mary Kate provided some names from the Corporate database team, for my inquiry about "dependent" or "Veteran" designations -- Corporate is what owns the designation in VBMS.

I also had asked Michael Harlow and he shared that 
> Today there were 129 dependents who logged in out of 58,129 active users.
Which is 0.2% of users.

Discussing with Holden though, this investigation is for a very future state and we don't need this information anytime soon.  Thinking I'll stop pursuing answers actively for now and focus on other priorities.
