### ISSUE TITLE
Copy of PgHero cleanup

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87374]
## Issue Description
PgHero (http://pghero-prod.vfs.va.gov/) is reporting some slow queries and, occasionally a long-running query.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/54c65bb9-cb17-4c5b-8e08-6c9252e41e9b)

Some of the slowest and/or most frequently called queries should be addressed. We will want to report significant findings to the teams that own the related code. 

## Tasks
- [x] investigate the yellow alerts in PgHero
- [ ] Fix issues or pass along findings to relevant teams
    - [ ] Link conversations, tickets, or PRs as comments in this issue.

## Success Metrics
The info in PgHero has been analyzed and acted upon.

## Acceptance Criteria
- [ ] Teams have been notified
- [ ] links to slack threads or tickets created from this are linked in the comments of this issue
- [ ] PG Lockout is created for extended run queries
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
Unnecessary dupe while trying to roll the ticket. Thanks, ZenHub
