### ISSUE TITLE
Mitigating RegreSSHion OpenSSH RCE bug on Platform Product Linux servers

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87388]
## User Story
As the Platform Product managers and developers, 
We need to ensure that our servers are not vulnerabilities, 
So that there are no security breaches to the Platform or other VA systems. 

## Issue Description
A new alert was brought to the team's attention, Slack link [here](https://dsva.slack.com/archives/C01CJV0L9PS/p1719852370272749). The regreSSHion flaw impacts OpenSSH servers on Linux from version 8.5p1 up to, but not including 9.8p1.
Our current Host **vetsgov-dev-jumpbox-govwest-1b** - contains OpenSSH_7.4p1
Because the system is running the patches that have been approved by AWS, there is no urgency to this particular instance, but the systems will need to be monitored for the auto updates. 
A couple of the GitHub action runner instances are running this vulnerability but it has no direct impact to our systems at this time because they are not publicly facing. 

## Tasks
- [x] Review servers that use SSH 
- [x] The regreSSHion flaw impacts OpenSSH servers on Linux from version 8.5p1 up to, but not including 9.8p1.
- [x] Host vetsgov-dev-jumpbox-govwest-1b - contains OpenSSH_7.4p1
Looks like we are good in this case because our version is below 8.5p1. Continuing to dive into our other servers

## Success Metrics
Mitigate possible risks from this security issue.
Documentation can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/SSH_Mitigation)

## Acceptance Criteria
- [ ] Validate whatever servers are running this OpenSSH
- [ ] Any vulnerable servers have been reviewed and the security patch was applied to each as needed. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
as of 7/1, our version is not directly impacted because our version is below 8.5p1. We are running whatever AWS has identified as the latest patch. Security patches will be automatically applied on a weekly basis. The Infrastructure team (Kyle M and Kyle F) will be monitoring the patches updates. 

Documentation is being tracked at [this GitHub URL](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/SSH_Mitigation)

**Comment by kell-y** [comment]
Security has reviewed the ticket and it looks good from a security perspective.
