### ISSUE TITLE
Mitigating RegreSSHion OpenSSH RCE bug on Platform Product Linux servers

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87391]
## User Story
_Please write a user story using the format: As a ___________, I want to ______________, so that _______________._

## Issue Description
A new alert was brought to the team's attention, Slack link [here](https://dsva.slack.com/archives/C01CJV0L9PS/p1719852370272749). The regreSSHion flaw impacts OpenSSH servers on Linux from version 8.5p1 up to, but not including 9.8p1.
- [ ] Host vetsgov-dev-jumpbox-govwest-1b - contains OpenSSH_7.4p1
Looks like we are good in this case because our version is below 8.5p1.

## Tasks
- [ ] Review servers that use SSH 
- [ ] The regreSSHion flaw impacts OpenSSH servers on Linux from version 8.5p1 up to, but not including 9.8p1.
- [ ] Host vetsgov-dev-jumpbox-govwest-1b - contains OpenSSH_7.4p1
Looks like we are good in this case because our version is below 8.5p1. Continuing to dive into our other servers

## Success Metrics
Mitigate possible risks from this security issue.

## Acceptance Criteria
- [ ] TBD
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
Unnecessary dupe while trying to save the ticket. Thanks, ZenHub
