### ISSUE TITLE
DR | Clean up data used for validation of decryption process

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#87405]
## Background Context

This is a follow-up to #83132.

Both unprocessed and processed evidence attachments are currently being stored in S3 along with the user password in a table so we can validate the PDFTK process for errors (via a manual unlock process). Once this validation step is complete, we will drop the records from the table and remove the code related to storing unprocessed PDFs and passwords.

## Acceptance Criteria

- [x] Sensitive data for validating the decryption process is removed

## Tasks

- [x] Disable flag/remove code related to unprocessed PDFs

## Definition of Ready

- [ ] Whoever picks this up has access to production console

## Definition of Done

- [ ] Disable `decision_review_save_encrypted_attachments` flag and/or remove logic to store passwords and unprocessed PDFs introduced in [#16652](https://github.com/department-of-veterans-affairs/vets-api/pull/16652)

**Comment by eileen-coforma** [comment]
PR will be created soon.

**Comment by eileen-coforma** [comment]
Addressed PR comments and needs to be re-reviewed.

**Comment by eileen-coforma** [comment]
Derek to message backend team to re-review.

**Comment by dfong-adh** [comment]
Changes have been merged and deployed to production.
