### ISSUE TITLE
BE Implementation Feature Flag Cleanup fsr_confirmation_email

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#87403]
## Description
 BE cleanup for  `fsr_confirmation_email` feature flag. It looks like the functionality has been removed from the FE, so let's confirm it's no longer being used in the BE and let's remove the references from the FE and the flag entirely

[Platform feature toggles guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide). Can work backwards for removal 

## Tasks
- [ ] Confirm flag is no longer necessary and unused on BE
- [ ] (optional) Create ticket to remove unnecessary functionality from BE 

## Acceptance criteria

- [ ] `fsr_confirmation_email` functionality has been confirmed no longer necessary and removed

## Testing
- [ ] No BE or FE tests/functionality failing after removal

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
