### ISSUE TITLE
[DevOps] Discovery on automating OpenAPI -> { Insomnia, Postman, Curl, etc } configuration export for LoROTA

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87433]
## Description
Per Stephen Barrs, WASA is trying to access our application but they aren't able to get this working. Currently, this process is built around manually distributing configuration files, some of which contain things like API keys that are sensitive, might need to be rotated, etc.

Given that API gateway allows generation of OpenAPI specifications, and OpenAPI specs should be fairly easily convertible to any other representation of an API, and used to generate clients, it should be straightforward to offer exports of Insomnia, Postman, etc configuration that allows access to our products.

Credential access is a bit tougher.

This ties in with automated end-to-end tests; it should be easy for us to generate, rotate, and disable credentials for a lower environment.

## Tasks
- [ ] [DevOps] Determine and document for each of LoROTA prod (and nonprod, where different):
  - [ ] requirements for access
  - [ ] desired application support
  - [ ] mechanisms for:
    - [ ] configuration generation
    - [ ] configuration vending
    - [ ] credential generation
    - [ ] credential vending
    - [ ] credential rotation
- [ ] [DevOps] Open followup ticket(s) for implementation

## Acceptance Criteria
- [ ] Above details are determined and documented in this thread.
- [ ] Followup ticket(s) opened to address specifics of implementation.
