### ISSUE TITLE
[DevOps] Generate Terraform infrastructure graph on `terragrunt plan`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87436]
## Description
This would help us:
- visualize cycles and complex areas of the infrastructure
- anticipate problems deploying "clean"
- guide refactoring to simplify and clarify architecture
- hint at dependencies that are implicit when they should be explicit (i.e. possible races)

## Tasks
- [ ] [DevOps] Run `terragrunt graph-dependencies` as part of Terragrunt Checks
- [ ] [DevOps] Run `terragrunt graph` as part of Terragrunt Checks

## Acceptance Criteria
- [ ] `terragrunt graph-dependencies` is run as part of Terragrunt Checks workflow.
- [ ] `terragrunt graph` is run as part of Terragrunt Checks workflow.
