### ISSUE TITLE
[DevOps] Discovery on creating architecture diagrams as artifacts in GHA workflows.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87440]
## Description
Followup to #87436.

It'd be nice if, instead of copypasta'ing DOT into online graphviz things, if we could generate SVG or PNG artifacts from the graph output, upload them as artifacts, and display the URLs at the end.

See the comment at the end of this thread https://github.com/actions/upload-artifact/issues/382

## Tasks
- [ ] [DevOps] Determine the best way of generating an image from the graph output
- [ ] [DevOps] Determine whether we can create artifacts, upload them, and then display the URL at the end
- [ ] [DevOps] Complete implementation if possible.

## Acceptance Criteria
- [ ] Feasibility has been determined, and we've either noped out of this or
- [ ] Implementation is in place.
