### ISSUE TITLE
Domo Monitoring & QC Clean-Up

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#87447]
### Description
We want to allow time to monitor how our Domo reports are behaving, and block out time for additional questions that might arise from the measurement changes.

The idea is for this ticket to help block some time to address any unexpected findings.

**Relevant Artifact:**
- [Final QC Checks -- Priority Domo Datasets](https://vfs.atlassian.net/wiki/spaces/AT/pages/3269525541/Final+QC+Checks+--+Priority+Domo+Datasets?focusedCommentId=3278143494)

---

### Tasks

- [x] Actively monitor vfs-analytics channel for Domo related questions
- [x] Monitor performance of cards, and existing reports
- [x] Ensure any outstanding QC items are flagged and resolved.

### Acceptance Criteria

- [x] Outstanding QC items from Domo datasets and reports have been documented and/or addressed.

**Comment by johnny-jesensky-adhoc** [comment]
Findings and discovered issues from our QC from this sprint can be found be documented here -- [Final QC Checks -- Priority Domo Datasets](https://vfs.atlassian.net/wiki/spaces/AT/pages/3269525541/Final+QC+Checks+--+Priority+Domo+Datasets?focusedCommentId=3278143494)

@Blivaditis, @ChristineYoungZA  -- with new items found from this past sprint, we will plan to wrap up our QC next sprint with [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88255), which y'all will be helping drive.

FYI @dorseypa1
