### ISSUE TITLE
Spike: Review Tracking Requirements for VA.gov Legacy Sites

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#87441]
### Description
It was identified late last week that we may need to migrate additional things from legacy VA.gov sites, over to GA4.

To our knowledge, these are not used in many Domo reports, or used as a part of custom events, but we nonetheless want to understand them.

---

### Tasks

- [ ] Seek to understand tracking requirements for VA.gov legacy sites
- [ ] Document where tracking is needed, and what reports in Domo are impacted.

### Acceptance Criteria

- [ ] We have requirements for tracking in VA.gov legacy sites
- [ ] Separate ticket is created for the actual implementation of tracking in GA4.

**Comment by johnny-jesensky-adhoc** [comment]
Implementations steps outlined in [this follow-up ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88128). 

@jestutt -- can you summarizing the findings from this, and outline the steps in that task?
