### ISSUE TITLE
Transition Staging Review issue ticket creation task to On-Support

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87459]
## User Story
As a Governance team member, I want to begin creating the SR issue tickets as part of my On-Support tasks so that this is no longer the sole responsibility of the Governance team PM.

Assignee: @it-harrison
Peer Reviewer: ~~@briandeconinck~~ @allison0034 

## Description
Governance team member @it-harrison has built an app for team use that takes the CSV file created from the DraftingTemplate and converts it into SR issue tickets in the va.gov-team repo (or the vets-design-system-documentation repo if for a DST SR). The app is called the Issue Uploader. [Guidance for installing and using](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3239870645/How+to+use+the+bulk+issue+uploader) the Issue Uploader has already been created, and [guidance for creating the SR issue tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets) has already been updated to reflect the new process.

The purpose of this ticket is to modify the On-Support Guidance and fully transition the task of creating the SR issue tickets from the team PM (@shiragoodman) to whomever is the On-Support person for Governance.

## Tasks
- [x] Talk to Shira about ensuring she is still tagged on all tickets

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The task of generating the SR issue tickets has transitioned from the PM to the Governance On-Support person
- [x] Governance has been made aware of the change

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@briandeconinck a draft is [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3301736449/87459+-+On-Support+guide#Upload-Staging-Review-Finding-Tickets)

**Comment by allison0034** [comment]
@it-harrison this looks good!
