### ISSUE TITLE
Determine if VPN affects analytics opt out

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8745]
## User Story or Problem Statement
As a VFS team member, I need to know if VPN affects my analytics opt out so I can know when to opt out of analytics.

## Goal
Determine if VPN affects the analytics opt out.

---
## Tasks
- [ ] Test if VPN affects the [analytics opt out](https://www.va.gov/analytics-opt-out.html)
- [ ] If VPN affects opt out, determine how often users will need to opt out of analytics on their devices
- [ ] Share results on the thread in the #vfs-all-teams [thread](https://dsva.slack.com/archives/CE4304QPK/p1587738535216200)
- [ ] Update [opt out instructions on Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/opting-out-google-analytics.md)

## Acceptance Criteria
- [ ] VFS teams know if their VPN affects their ability to stay opted out of analytics on VA.gov
