### ISSUE TITLE
[UX] 10-10 CG Desk and user research opportunity planning

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#87460]
## Issue Description

As _somebody_ completing the caregiver application - a Veteran, a Primary or Secondary Caregiver, a Representative or a VSO - I want it to be clear and easy to understand the impact to me (and to other applicants).

After the paper form and CARMA were updated with the July release changes, there were a few UX debt items outstanding. The CG team stakeholders also had primary/secondary caregiver clarification as a nice to have item on their feedback list.

---
## Tasks
- [x] Document and gather all the design debt and future items listed from the July form updates work
- [x] Conduct desk research to see what other teams have done **recently** around representative experiences and forms
- [x] Conduct desk research for anything else relevant around caregivers and representatives
- [x] Partner with DA Luis to gather any relevant CG analytics available
- [x] Gather all info into an organized doc and/or Mural
- [x] Draft research questions and overall UX next steps
- [x] Review and gather feedback via slack and weekly UX sync
- [x] Determine next steps and open tickets/meet with stakeholders

## Acceptance Criteria
- The internal CG team, PM, PO, UX lead are all in alignment on next steps for CG enhancements priorities post-July release

---

**Comment by jessicastump** [comment]
Next steps after chatting through as a team: It is difficult to prioritize UX issues with so little research done with caregivers. There is not enough secondary research out there to fill in the gaps.
- Review existing research plan created around baseline + facilities
- Determine what additional research questions need to be addressed to learn what is needed to proceed with backlog prioritization and to move forward with any caregiver clarification or representative work
- Research planning working session to figure out logistics of participant recruitment, number of sessions/cohorts and scheduling.
