### ISSUE TITLE
[CDP] Fix Alert on download debt letter page.

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#87478]
## Issue Description
The alert on the debt portal is incorrect. It says that the Veteran doesn't have any debt letters. We need to change it to say that debt letters are not currently available using the messaging below. Also, need to change the alert style to a warning instead of an error. 

| Current alert    | Proposed alert |
| -------- | ------- |
| <img width="580" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22cc5ea21a548476574530635234d6e76306ec73/image.png" alt="Current alert page" />  | <img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUNxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd7b1474759a83a962d9ed6158ccd726423844be/image.png" alt="Proposed alert page" />  |

Here is the updated copy:
> ## Your debt letters are currently unavailable.
> You can’t download your debt letters because something went wrong on our end.
> **What you can do**
> You can check back later or call the Debt Management Center at [800-827-0648](tel:800-827-0648) to find out more information about how to resolve your debt.

**Alert can be found on the debt-balance/letters page:**
https://staging.va.gov/manage-va-debt/summary/debt-balances/letters
https://va.gov/manage-va-debt/summary/debt-balances/letters

---
## Tasks
- [ ] Update `alert` component with above text
- [ ] Remove [existing](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/debt-letters/containers/DebtLettersDownload.jsx#L54) `h2` on the page and use the alert `h2` 
- [ ] Change `alert` to `warning` 

## Acceptance Criteria
- [ ] Alert copy has been updated and `h2` has been removed 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by josephrlee** [comment]
@OptionSelect, @amponce , it looks like the [proper Alert exists](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/debt-letters/components/Alerts.jsx#L66), it's just not displaying. I think it has something to do with the [logic on this component](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/debt-letters/components/DebtLettersTable.jsx#L34).

**Comment by amponce** [comment]
Good catch @joe, I'll get it resolved shortly

**Comment by Dr-Pongo** [comment]
Hey @josephrlee! I'm taking over this one and I think I'm going to tie the alert you described above to the same feature flag that's disabling fetching the letters on the BE. I'll update that `ErrorMessage` to match the content and styling you described in the main ticket since I can't find another reference to it elsewhere if that seems alright with you

**Comment by denisecoveyduc** [comment]
As per our discussion in slack we are changing direction of this ticket to remove the mention of downloading the debt letters until such time we have identified an adequate path forward. This will eliminated the alert message for the Veteran. 

@Dr-Pongo suggested for the purposes of this ticket we hide the content in the following screenshot behind a feature flag so it can be leveraged in the future. This is a great solution which can hopefully be contained as part of the updated scope for this ticket. @Tom-Davis will work with the team to update any estimates or capture changes as needed. 

<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkROQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcd9be98807206a7f93cea4a0cad6299d5b7cdf1/image.png" alt="image.png" />

**Comment by Dr-Pongo** [comment]
@denisecoveyduc 
Should we update the text here as well?
<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVBRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd18488d20f4dddff9e3bb030f440d0fe348bca0/image.png" alt="image.png" />

**Comment by mgleo** [comment]
> "You can check the status of this debt."
Maybe this line should be removed entirely as we are letting them know when the debt letters were sent, not the status. What do you think @denisecoveyduc?

**Comment by Dr-Pongo** [comment]
Closing out this ticket as complete. Using the `debt_letters_show_letters_vbms` feature flag we've removed references to the debt letter downloads page, and included the following alert if someone does manage to navigate there:
<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0329e642c3f0b66adb771f7b04a7920a20e5595/image.png" alt="image.png" />
