### ISSUE TITLE
TEMPLATE: PR Checklist

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#87475]
PR Review [PR #] Template #Add
PR Review Checklist
Add Link to PR: 

Summary of Changes
Provide a brief summary of the changes made in this PR.

**Review Checklist**

- [ ]  I have reviewed the code changes and they align with the ticket's acceptance criteria.
- [ ]   I have pulled the branch and manually tested the changes (if applicable).
- [ ]   The changes do not introduce any new linting warnings or security vulnerabilities.
- [ ]   Any new or updated tests are passing.

**Review Time**
Default time: 1 point
Provide an estimate of the time it took you to review this PR:

**Reviewer Notes**

**Comment by alatempa24** [comment]
This is now an issue template available for use. To modify the template, edit this [markdown file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/VA%20Debt%20PR%20Review.md).

cc @Tom-Davis @HeatherRienks
