### ISSUE TITLE
[DevOps] Discovery on AppConfig + Lambda for `vaec-cie`

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87489]
## Description
Followup to #87485. This is more centered on how best to define this infrastructure for `vaec-cie`.

## Tasks
- [ ] [DevOps] Determine how best to implement this for LoROTA
- [ ] [DevOps] Determine how best to implement this for CHIP
- [ ] [DevOps] Document any findings, including potential complications, in this thread.
- [ ] [DevOps] Open ticket(s) for followup as needed.

## Acceptance Criteria
- [ ] Determinations for implementing this in `vaec-cie` have taken place.
- [ ] Findings have been documented in this thread.
- [ ] Followup ticket(s) opened for implementation.

**Comment by ndouglas** [comment]
`stations_skip_insurance_check` might be a good pilot project for this.
