### ISSUE TITLE
[Backend] Record VCR Cassettes for Debt Letters "GET /debts"

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#8748]
## User Story or Problem Statement
Mocked response data needs to be captured in order to facilitate rapid local testing.

## Goal
A betamock is recorded for the `GET /debts` endpoint.

## Objectives or Key Results this is meant to further
- [ ] Allows testing the `GET /debts` to be done quickly in local and other environments.

## Tasks
- [ ] Establish connectivity with the DLC.

## Acceptance Criteria
- [ ] Betamocks are recorded for this endpoint and a PR is merged into vets-api-mockdata containing the recorded cassettes.
