### ISSUE TITLE
[DevOps] Discovery for AppConfig + Lambda Extension on `vaec-cms`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87485]
## Description
This might be useful with some changes that Brian has in mind.

## Tasks
- [ ] [DevOps] How much of a PITA is this to add to CHIP CF/SAM?
- [ ] [DevOps] How is this tested?
- [ ] [DevOps] How does this complicate existing tests?
- [ ] [DevOps] How can we best support updating values on the fly?

## Acceptance Criteria
- [ ] Above questions have been researched and documented in this thread.
- [ ] Discussion between DevOps and Brian to determine a good path forward if warranted.
