### ISSUE TITLE
[DevOps] Refactor `checkin-devops` policy document declarations.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87493]
## Description
There's some shared boilerplate between them, and duplication of variables, etc. We could simplify this by having multiple templates with comments, blame, etc that are merged into a single document, Sids stripped, etc.

Not a high priority, just something to think about. Role policies can be up to 10,240 characters or something like that.

## Tasks
- [x] [DevOps] Split IAM Policy into statements addressing individual services, e.g. `iam`, `secretsmanager`, etc.
- [x] [DevOps] Combine statements into a list, then split that list _n_ ways.
- [x] [DevOps] Create a policy for each chunk of statements.

## Acceptance Criteria
- [x] Policies for `checkin-devops` are implemented as template files containing statements addressing a single service.
- [x] Policies are created to get around the length limit.

**Comment by ndouglas** [comment]
This ended up becoming a problem today, so I went ahead and did it.
