### ISSUE TITLE
Set Up Domo Job Alerts

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#87497]
### Description
This ticket is to set-up Domo data set retry and alert process to help data propagate down into our reports in a timely manner and without failing.

---

### Tasks

- [x] write the code to determine if the GA4 data processing status for the day. (complete or not complete)
- [x] write the code to recheck the GA4 data processing status after a specified duration  up to a specified number of retries when status is not complete
- [x] code saved as a stored procedure

### Acceptance Criteria:

- [x] processing status code written and tested
- [x] processing code written and tested
- [x] stored procedure call added to domo query

**Comment by johnny-jesensky-adhoc** [comment]
As discussed in stand-up, these are completed -- moving to Done.

@dorseypa1
