### ISSUE TITLE
[FE] - Redirect on stale session after completion 

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#87499]
## Description
We want to reduce the amount of errors that are a result of reloading old tabs. To do this, we are going to set a timestamp in session storage. Then in the `ReloadWrapper` component we will calc the time since completion to determine if we should fetch data or redirect the user to an end page. 

This needs to happen for all 3 applications. For example, in `check-in` the setting of the timestamp would be in the `AppointmentAction` component when we also call `setCheckinComplete`. We also need to reset the timestamp to null or zero at the start of the application. In my POC I just took over the `health.care.check-in.check.in.complete` value since it already resets and is used as a bool. In discussions with John, we decided that this timestamp should be its own separate thing in session. 

POC snippet from `ReloadWrapper`
```
useEffect(
    () => {
      if (finishedTime) {
        const hoursSince =
          Date.now() / (1000 * 60 * 60) - finishedTime / (1000 * 60 * 60);
        if (hoursSince > CONFIG_STALE_DURATION) {
          window.location = CONFIG_STALE_REDIRECT_LOCATION;
        }
      }
    },
    [finishedTime],
  );
```
The `CONFIG_STALE_DURATION` & `CONFIG_STALE_REDIRECT_LOCATION` should be added as constants in our utils, and should have a unique value for each app.

For this initial work lets set the duration to 30 minutes and the location to `window.location.origin` and UX will follow up with refinements there.

## Tasks
- [x] Add finished timestamp key to session storage
- [x] Set unix timestamp value at successful finish for each app
- [x] Reset the value at the start of each app
- [x] Add redirect logic to `ReloadWrapper`
- [x] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by wullaski** [comment]
@loripusey I merged in the code that completes this ticket. We could move this to the current sprint and check it off as done.

**Comment by loripusey** [comment]
ok, I'll move it; if this is ready to close, please close it

**Comment by brianseek** [comment]
validated on stage
