### ISSUE TITLE
Set Up BigQuery Job Alerts

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#87496]
### Description
This ticket is to set-up GA4 load  job retry and logging in BigQuery to help data propagate down into our reports in a timely manner and without failing.

---

### Tasks

- [x] write the code to determine if the GA4 load status for the day. (Not loaded or loaded)
- [x] write the code to recheck the GA4 load process after a specified duration  up to a specified number of retries when status is not loaded
- [x] schedule the job to run daily

### Acceptance Criteria:

- [x] load status code written and tested
- [x] retry code written and tested
- [x] schedule configured and a successful run confirmed
