### ISSUE TITLE
[UX][Design] SPIKE: Stale reload details

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#87511]
## Description
We want to redirect patients who have old tabs still open after completion after a certain amount of time. For the first iteration we are just going to send them back to the va.gov homepage. It probably makes more sense to send them to a new page that explains that their session has expired and how to re-initiate the app (check-in, travel) along with some helpful static content like the accordion content, medication wording, how to file travel, etc. This should be static content not related to a specific appointment. We will no longer have data at this point, so we won't know anything about the patient or appointment.

The other thing to put some thought into is how long we want to allow a patient to be able to refresh the app after completion. After the time duration expires is when they would be redirected to the above mentioned page. For the initial pass at this, we are setting that time to 30 minutes for each app.

[dev ticket for reference](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87499)

## Tasks
- [ ] Create design options (team chooses fidelity based on situation)
- [ ] Get feedback from appropriate stakeholder(s). E.g., content or a11y SMEs, platform design, UX team, check in team, VA OCTO PO's, check in PO, Angela Fowler (a11y) or Sara Sterkenburg (IA).
- [ ] Incorporate feedback into solution(s) 
- [ ] Determine optimal option after peer reviews.  
- [ ] Check to see if tickets exist to implement the final design decision and are accurate (or create them, if necessary)

## Acceptance Criteria
- [ ] Design solution has been chosen
- [ ] Design solution idea has been vetted and approved by appropriate stakeholders 
- [ ] Follow up tickets have been created for content and design implementation
