### ISSUE TITLE
Discovery ticket to capture the instances of "Vets360" that need to be changed in Vets API

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87528]
## User Story
As a developer in the Department of Veterans Affairs organization,
I need to not see instances of Vet360 because it's been renamed to VA Profile,
So that any searches for VA Profile will be accurate and comprehensive. 
And so that developers without the institutional knowledge that VA Profile used to be Vet360 will not be confused about the naming.

## Issue Description
A review of the platform reveals several instances of the phrase "Vet360" and this needs to be changed across the system for continuity. Refer [to this link](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-api+vet360&type=code&p=2) for a sample search that was used to create this list. 
We need to be mindful of cascading events if something is changed in the Back End and has an impact to the Front End. 

## Tasks
- [ ] Need to review the following areas and document the level of effort to change Vet360 to VA Profile
- [ ] Controllers
- [ ] Service classes
- [ ] Models
- [ ] Swagger docs
- [ ] Policies
- [ ] Sidekiq jobs
- [ ] Specs
- [ ] Readme's
- [ ] Factories
- [ ] Various other configurations, as found during discovery
- [x] Need to determine if any of these changes impact the FrontEnd behavior, document what these impacts are and what work needs to be completed (separate tickets) 
- [ ] Documentation of the categories and level of effort needed to change this site-wide.

## Success Metrics
A documented level of effort to make the change site-wide will be approved, then tickets for the work will be created, grouping the work will be done for maximum efficiency. 

## Acceptance Criteria
- [x] The Platform Product team will have a strategy to change Vet360 to VA Profile across the site. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
8/21 update: @rjohnson2011 is working on this and gathering information on the number of instances of Vets360.
