### ISSUE TITLE
Implement new evidence content pattern in whole form experience

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#87526]
## Background
Work on https://github.com/department-of-veterans-affairs/va.gov-team/issues/79210 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/79212 led to the creation of a new content pattern to replace evidence request alerts with pages in the 527EZ experience. We need to ensure this new pattern is consistent throughout the form.

## Tasks
- [ ] Assess whole form for opportunities
- [ ] Get feedback from team
- [ ] Consult CAIA for direction and content
- [ ] Adjust designs based on feedback
- [ ] Request a Midpoint Review?

## Acceptance Criteria
- [ ] We have designed changes across the whole form experience that implement the new content pattern.

**Comment by aplatt-coforma** [comment]
Backlogging this ticket. Will plan to user test the changes that we've worked on first before we adopt changes to other areas of the form.
