### ISSUE TITLE
Reorganize Support Bot Documentation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#87535]
## Description 
We need to both reorganize the support bot page and remove the infrastructure page that exists to keep everything in one place and under the space of the team that owns the process. 
---

## Definition of Done
All tasks below are complete.
---

## Tasks 
_Steps to reach definition of done._ 
- [x] Copy included page content into our existing page [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/edit-v2/2887582468) 
- [x] Ask Clint to archive this page as the process belongs to Platform Support not SRE: https://vfs.atlassian.net/wiki/spaces/SRE/pages/1883406342/Platform+Support+Bot
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---
