### ISSUE TITLE
[FE] Investigate existing functionality for Terms & Conditions on Account page

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8753]
## Background

No one on the team seems to know what we show for the medical terms and conditions on the account settings page *if* someone is a health care user but has *not* accepted the T&Cs. What do we show — anything?

**What we already know**:

- If you have accepted the medical T&Cs, we show the confirmation seen below.
- If you are LOA1, I have confirmed we don't show the T&C section at all.
- [This may have been how we handled it on VA.gov *before* the existing iteration of the account page](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10051#issuecomment-382564825). Are we still prompting people to go to the T&Cs page if they are a health care user and need to accept the T&Cs?

**So, what happens if you are a health care user but you have not accepted the T&Cs? Can we tell from the code?**

![Screen Shot 2020-05-05 at 11.42.09 AM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/3d49fc92-3bae-4953-b0d7-7fc5a53b2e20)

## Tasks

- [ ] Look into code to explore the T&C issue described above
- [ ] Report back to the team

## Acceptance criteria

- [ ] We understand how we handle the UI for the T&C section of the Account page if someone has health care but has not accepted the T&C.

**Comment by sanlouise** [comment]
Source of truth: `applications/personalization/account/components/TermsAndConditions.jsx`

When `mhvAccount.accountState === 'needs_terms_acceptance' ` we render the following text (roughly - copied from source JSX)

Want to use VA.gov health tools to do things like refill your VA prescriptions?

To get started, you'll need to read and agree to the Terms and Conditions for Medical Information. This will give us your permission to show you your VA medical information on this site.

Once you agree to these Terms and Conditions, you'll be able to use VA.gov health tools to:
Refill your VA prescriptions
Download your VA health records
Download your VA health records

And a link to /health-care/medical-information-terms-conditions
