### ISSUE TITLE
[PM] My VA Forms Status: Analytics strategy

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#87546]
## Background
We need to determine our analytics strategy for the forms status work on My VA. In order to do this we also need to align on success metrics for the MVP and coordinate with VFF to see what and how they'll be tracking success.

## Tasks
- [x] Meet with Chante to align on success metrics
- [x] Discuss success metrics with team
- [x] Discuss with Tricia on VFF what they plan to track
- [x] Reach out to analytics as needed

## Acceptance Criteria
- [ ] We are aligned on success metrics and approach with analytics

**Comment by ajakabcin** [comment]
Discussed with Chante team and VFF yesterday:

- for the MVP metrics will be capturing a baseline since this is a brand new feature on My VA
- baseline items we'll track: downloads, clicks from confirmation page (VFF page) to My VA, if notifications are included in MVP engagement with them (email and onsite)
- we will also investigate if we can use the method that the health team used to capture engagement without clicks via the va alert component firing
