### ISSUE TITLE
ECR mirroring

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87540]
## User Story
As the developers and engineers on the VA Platform, 
We need to fix the Docker Hub rate limitations by creating a mirror of the ECR system,
So that no blockers in service begin to happen for the users. 

## Issue Description
It was discovered on 7/2/2024 that the Platform deployment affecting VetsAPI was being rate limited on Docker Hub (see DSVA Slack thread [here](https://dsva.slack.com/archives/C0460N83Y9G/p1719945661418549)). It was also discovered that, although we authenticate, but for authenticated, non-paid users there is a limit of pulling 200 images per 6 hours. We need to come up with a way to call ECR in an authenticated fashion. 

## Tasks
- [ ] Make sure we're using ECR correctly as logged in use
- [X] Make ECR login changes to dockerfile
- [ ] Test dockerfile, if the test passes, then apply to:
- [X] add the [ECR login action](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/build-and-publish.yaml#L31-L35) in both the [Code checks workflow](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/code_checks.yml) and the [Audit Service Tags](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/audit_service_tags.yml)
- [ ] Cleanup Docker login
- [ ] Pull the image from AWS ECR instead of Docker Hub
- [ ] Compare ECR vs Dockerhub rate limiting (auth vs un-auth)
- [ ] Confirm that ECR is being used correctly
- [ ] Do we need to mirror, or is it sufficient to pull public images from AWS without mirroring?
- [ ] Do we need ECR images for postgis AND redis?

## Success Metrics
Need to have ECR mirrored

## Acceptance Criteria
- [ ] That there is a backup of ECR in the mirroring database.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
This ticket was opened at the tail end of Sprint 4, when the issue was identified, and will be worked on in Sprint 5.

**Comment by flooose** [comment]
Could it be that the only tasks left for this are as follows?

- [ ] ~~Temporarily remove conditionals for the offcycle deploy for 7/2/2024~~
- [ ] ~~Build-and-push manually then revert~~
- [ ] ~~Make ECR login changes to dockerfile~~
- [ ] Make sure we're using ECR correctly as logged in use
- [ ] Test dockerfile, if the test passes, then apply to:
- [ ] ~~add the [ECR login action](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/build-and-publish.yaml#L31-L35) in both the [Code checks workflow](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/code_checks.yml) and the [Audit Service Tags](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/audit_service_tags.yml)~~
- [ ] Cleanup Docker login
- [ ] ~~Pull the image from AWS ECR instead of Docker Hub~~

**Comment by jennb33** [comment]
7/11 update: this ticket has been de-prioritized due to https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87838 (FOIA ticket)

**Comment by jennb33** [comment]
7/15: rolling this ticket to Sprint 6 because of the higher priority work that came in during Sprint 5 (FOIA request)

**Comment by jennb33** [comment]
7/25 update: this work is complete, the checked off tasks were all that remained for work. OK to close ticket.
