### ISSUE TITLE
Put Documentation Bot Article in Its Own Page

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#87554]
## Description 
To reduce the overwhelm of the Support Bot page, we want to parse out the Documentation Bot content. We will point to the new Documentation Bot content in the Support Bot page. This will help ensure no matter where someone lands, they get the same information (all roads lead to DB page).
---

## Definition of Done
All tasks below are complete. 
---

## Tasks 
_Steps to reach definition of done._ 
- [ ]  Create new documentation bot page in Platform Support Team Confluence Page
- [ ]  Edit blurb about documentation bot in Support Bot doc to point to new documentation bot article 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Duplicate ticket, closing.
