### ISSUE TITLE
Q2 2024 Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87568]
## Background
Starting a quarterly health check of qualitative feedback from users.  This feedback does not come often enough to be considered significant, so we've decided to check on a quarterly basis for now (as opposed to monthly).

## Tasks
- [x] Request contact center metrics from Medallia
- [x] Request contact center metrics from MyVA411
- [x] Remove PII from contact center exports
- [x] Summarize contact center feedback to "Recap of Responses" document
- [ ] Look at feedback from the good/bad survey at the bottom of our FAQ content page

## Acceptance Criteria
- [x] Q2 2024 metrics are in Sharepoint

**Comment by oddball-lindsay** [comment]
June Medallia feedback is in the Recap of Responses excel document in Sharepoint:
<img width="1243" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11790cf2f7ec1a920c6fac6e0197eb0733fe0838/image.png" alt="image.png" />

This took me 2 hours to remove PII and categorize the responses -- much longer than I thought, I'm not sure this is my forte.  

@jfinnerty13 The ["Medallia Report" in Domo](https://va-gov.domo.com/page/825663825) doesn't completely match up with the exported data, but I'm wondering if it's close enough that we can rely on this instead of the exports.  It takes just a minute to filter the Domo report by date and directory.  Plus we'd no longer have to request, await and clean up the exports and calculate total numbers.  

Domo has user restrictions so I'm not sure if it's ok to post a screenshot in this ticket, so give this query a shot:
1. Filter date range (upper right) from January 1, 2023 to June 1, 2024
2. Filter directory to `/get-help-from-accredited-representative` 

The dashboard gives some overall numbers, but also monthly trends.  There is no data past a certain point, because that's before we launched.  You can also do this search for the FAQ page, where the directory is `/resources` and the subdirectory is `va-accredited-representative-faqs`

**Comment by jfinnerty13** [comment]
> @jfinnerty13 I wasn't sure how to calculate CSAT and could use your help. I also wasn't sure if cell D3 (the "Yes" count for 3/11-4/13) was supposed to be empty.

1. To calculate CSAT you average column J "What is your overall satisfaction with this site?", so this month we were at an average of 2.1.
2. Yes, D3 is empty because there were no 'Yes' responses that month, I added in a zero to mark that.

> There'd be a huge time win if we can use Domo for Medallia. I wouldn't have to submit the request and wait for an export.

The only downside is we lose the comments, which do sometimes shed some light. So it might be worth pulling a couple times a year to review since our quotes are so low. Which can always be an optional task but it is good to review, especially as we find small updates we can do, such as changing the Apply button to Sort the other month. Time permitted of course, and many researchers take that on btw as a standing quarterly task at VA, so happy to do that as needed.

The other downside to DOMO is we do lose the other 3 questions of the SUS formula, the questions on how understandable and usable our tool are, which typically have higher metrics (so a good thing). Is there a way to get those on DOMO?

Great job pulling this all together thank you!

**Comment by oddball-lindsay** [comment]
Ah yes, I see the "VA.gov Understanding" for the Intercept Survey is missing in that Medallia Report in Domo.  @jfinnerty13 you mentioned we lose 3 questions, are the other two questions you're referring to the open ended qs?
- Why did you select that rating? (Intercept survey)
- What task were you trying to do today? (Feedback survey)

**Comment by oddball-lindsay** [comment]
This project is done for Q2.  I'm curious still about if we can have a dashboard for the quantitative metrics, outlined an approach to that possible reality over in https://github.com/department-of-veterans-affairs/va.gov-team/issues/87700
