### ISSUE TITLE
ECR Workaround for Docker Images

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#87577]
## User Story
As the developers and engineers on the VA Platform, 
We need to avoid Docker Hub rate limitations by using AWS ECR,
So that no blockers in service begin to happen for the users. 

## Issue Description
It was discovered on 7/2/2024 that the Platform deployment affecting VetsAPI was being [rate limited on Docker](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/9765884484/job/26958405072?pr=17377) Hub (see DSVA Slack thread [here](https://dsva.slack.com/archives/C0460N83Y9G/p1719945661418549)). The work in this issue is a first step to unblock our GHA workflows and remaining tasks should be address in [87540](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87540)

## Tasks

- [x] Make ECR login changes to dockerfile
- [x] Test dockerfile, if the test passes
- [x] add the [ECR login action](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/build-and-publish.yaml#L31-L35) in both the [Code checks workflow](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/code_checks.yml) and the [Audit Service Tags](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/audit_service_tags.yml)
- [x] Pull the image from AWS ECR instead of Docker Hub

## Acceptance Criteria
- [x] Deployment succeeds
- [x] Workflows don't fail due to rate limiting
