### ISSUE TITLE
Content Edit: 87470

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#87579]
## Issue Description
Content edits according to support ticket [87470](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/87470)
---
## Tasks
- [x] Review support ticket [87470](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/87470)
- [x] Update website according to solution below 
- [x] Prepare page for deployment

## On the [VA Forms Library - Form Config Options ](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-form-config-options) page, the section labeled `subTitle` should be replaced by this:
| Options | Value Type | Description | Example |
|---|---|---|---|
| subTitle | string or function | The subtitle of the form, usually the form number. The subtitle is rendered on all pages when there's also a title. Accepts a string or function; params include (currentLocation, formConfig, formData, children). | `subTitle: 'VA Form 10182 (Notice of Disagreement)'` or `subTitle: ({ formData }) => formData.changeSubTitle ? 'Form 345 with Form 123' : 'Form 123'` |

## Acceptance Criteria
- [x] VA Forms Library page will be updated to include the changes

## SMEs for this work:
_See original ticket author **87470**_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/87579?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by laucon** [comment]
We have edited the first subtitle heading on the [VA Forms Library - Form Config Options](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-form-config-options) page, which is what this ticket required. However, in doing this ticket, we found out that there is a second "subtitle" entry which may or may not be a mistake. We need to investigate the second "subtitle" entry and see if there is an edit that needs to be made to it, per this [slack thread](https://dsva.slack.com/archives/C044WNQT4P9/p1715178854833389).

**Comment by laucon** [comment]
This is done. We can close it. The follow up ticket, [88174](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/88174), is in the backlog.

**Comment by jknipes** [comment]
Closing ticket as _Done_
