### ISSUE TITLE
[CHIP] - Update CHIP to use stopcode endpoint instead of hardcoded list

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#87571]
## Description 
We are currently maintaining a hard coded list of stop codes in CHIP to determine the appointment kind. We would like to stop using that list and instead move to using the new endpoint for stopcodes. 

**API contrac**t: https://veteran.apps-staging.va.gov/stopcode/v1/
**Get details on a single AMIS stop code**:
https://veteran.apps-staging.va.gov/stopcode/v1/codes/131
**Get details on multiple AMIS stop codes (not pairs)**:
https://veteran.apps-staging.va.gov/stopcode/v1/codes?amisCodes=131,136,139,020
**Get details about one or more appointment stop code pairs (note the URL encoded pipes)**:
https://veteran.apps-staging.va.gov/stopcode/v1/pairs?stopCodePairs=322,323%7C179,125%7C323,999,103,189%7C136 (

I believe we will want to use the stopcode pairs endpoint.

[slack thread about endpoint](https://dsva.slack.com/archives/C06RMRJCLHH/p1715887097308579)

## Tasks
- [ ] Create a service layer for the stopcode api
- [ ] Create a function for the stopcode pairs endpoint
- [ ] Implement the API in place of our hard coded list
- [ ] Make any need tweaks to maintain our current filtering
- [ ] Create or update unit tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
Closing because a duplicate of 87570 and 3 others
