### ISSUE TITLE
Update the postgis images in the docker-compose test file

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87580]
## User Story
As developers and managers for the Postgres tool,
We need to update the postgis images in the docker-compose test file,
So that the tool is consistent and complete. 

## Issue Description
It was identified that the postgis image in the docker-compose test file was incorrect; it may have been missed during the Postgres upgrade. 

## Tasks
- [ ] Update the postgis images in the docker-compose test file. 

## Success Metrics
That the postgis images in the docker-compose test file are updated and correct throughout the docker-compose test file.

## Acceptance Criteria
- [ ] The postgis images in the docker-compose test file are updated
- [ ] Any testing is completed successfully
- [ ] Documentation is updated as necessary
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by Kshitiz-devops** [comment]
I had made changes 8 months ago and looks like PR wasn't created at that time: https://github.com/department-of-veterans-affairs/vets-api/pull/17666

**Comment by jennb33** [comment]
PR approved by @LindseySaari and communicated in Slack.
