### ISSUE TITLE
Tip of The Sprint: Emoji Guidance  

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#87606]
## Issue Description
Content team has arrived at guidance around the use of emoji on Platform Website, and published this Confluence page in the About The Platform space. We need to publicly announce this new guidance on the #platform-content channel so teams writing and editing for the website know how to use emoji.

---
## Tasks
- [x] Draft Tip of The Sprint
- [x] Review draft with PC Team
- [x] Schedule ToTS for **Mon, Oct 28, 2024 at 1pm** in #platform-content channel in Slack

## Acceptance Criteria
- [x] Tip of The Sprint posted
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Closing as _Done_
