### ISSUE TITLE
Tip of the Sprint

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#87608]
### Purpose
The Content team provides a new "content tip" every sprint with the #platform-content channel's audience. The purpose of this is to provide continuous style guidance and re-enforce content best practices for contributors of the Platform website.

### Tasks
 

- [x] Pick a content tip idea from the style guide
- [x]  Draft a content tip Slack post, similar to [any of these in the Archive.](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3239444481/TIP+OF+THE+SPRINT+-+Archive)
- [x]  Get feedback from rest of Content team
- [x]  Copy and paste the team-approved announcement of our Tip of the Sprint in to the platform-content slack channel.
- [x]  Schedule for first Monday of the Sprint

Acceptance Criteria:

- [x]  A new content tip will be posted on #platform-content for this sprint.

**Comment by BSmolensky** [comment]
Once Tip posts this afternoon, this ticket will be good to close.

**Comment by jknipes** [comment]
Topic: Don't Use Names, use position or teams name

**Comment by BSmolensky** [comment]
https://dsva.slack.com/archives/CL181NRJQ/p1720458000456059 - Post is live. Ticket can be closed.
