### ISSUE TITLE
Develop a Plan to Upload the Newly Created PDF to the eFolder via VBMS

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8760]
## Story
As a Veteran submitting the 21-686c, I want a copy saved in my folder as a pdf for my records so that I can retain them as record, validate the submission, or any number of other pdf actions.

## Considerations
- This is a utility that is used throughout the platform and most likely leverages the submitted form schema through a process ending up as a pdf, that might then need to be sent or saved for the Veteran in their eFolder.
- Lighthouse has already built a VBMS uploading function that should help.
- The submission process and the creation of the pdf is most likely independent of each other, not interdependent.
- Can we test this pdf creation, eFolder saving in staging?
- If possible, it would be great to provide this to the user to download after submission
- Kevin M had some work done in this area
- URLs from Steve: 
  - https://github.com/department-of-veterans-affairs/vets-api/tree/master/spec/lib/pdf_fill/forms
  - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/VA-Systems/VBMS/VBMS%20Web%20Services%20Startup%20Guide.pdf
- https://developer.va.gov/explore/benefits/docs/claims?version=current 
_(look under the POA endpoints)_

## Tasks
- [x] Leverage Lighthouse VBMS upload functions (Check with Charley)
- [x] Test pdf upload

## Acceptance Criteria
- [x] Develop a plan for moving PDFs through VBMS and into the eFolder
- [x] Initialize the implementation of a PDF to be found in the users eFolder shortly after submission via VBMS
