### ISSUE TITLE
Find a VA Location - Secondary Research

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#87613]
## Issue Description
Identify any secondary research on the Find a VA Location details pages. https://www.va.gov/find-locations

## Tasks
- [x] Identify team to reach out to.
- [ ] Review available research.
- [ ] Share with @mtri findings.

## Acceptance Criteria
- [ ] All tasks completed.

**Comment by jfinnerty13** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/research#facility-locator-user-research-readme

**Comment by mtri** [comment]
I dug through all studies for any relevant past research. Generally, there isn't much in depth on the detail pages and the structure of the research did not dig into usage and navigation to the detail pages. 

Overall, what may be gleaned is
- The detail pages serve their purpose in the facility locator context
- If we can avoid making a user dig through to the detail page we should (Test option 2 with contact information surfaced as discussed)

Some of what we may have to test
- CTA language, link UI, and placement
- What information is surfaced on the card vs. on the detail page
- Back button usage

**Linked below is all studies + my notes / quotes:**

[VBA Service Label Usability Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/services-benefits-taxonomy-USERS/VBA-service-labels-usability-research-findings.md)
No data on detail page or navigating to detail page.

[Emergency care mashup](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/emergency-care-mashup/research-findings.md)
No data on detail page or navigating to detail page.

[Facility Locator Assistive Technolog](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/screenreader-usability-study/research-findings.md)y
No data on detail page or navigating to detail page.

[Facility Locator Mobile experience](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/screenreader-usability-study/research-findings.md)\
No data on detail page or navigating to detail page, but similar findings to previous studies on Find:

"

-   Regarding details on the list view and cards

-   Three participants wanted to see hours of operation on the card (and "is this open now?")

-   One participant mentioned wanting to click on the notification (e.g. "limited service and hours") to learn more about what that meant.

-   One participant wanted to see type of services available on the card

-   One pariticpant was confused at why the card wasn't customized for his service type, e.g. why was he seeing the mental health line when he searched for optometry

-   Some participants were interested in more options as filters before they click "search"

-   one wanted to pick radius (in miles)

-   one wanted to pick service first e.g. pick Optometry first instead of VA Health - "I don't know the difference between "VA health" and "community care providers. Community care providers are more like little clinics -- they also do optometry, so I was unsure. I probably would've done the service type first to see if optometry is available at each facility type. It would be good to reverse the order to eliminate some options."

-   One wanted a filter where he could see if there was VA transportation available to bring him to the facility"

[Urgent care mashup](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care-mashup/research-findings.md)
No data on detail page or navigating to detail page.

[Facility Operating Status](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/facility-status/research-findings.md)

"8. Participants don't want to 'dig' or 'click too many times' for important information. While most participants expected to be able to click into each listing to get more information about each status, users did not want information "buried" in many clicks and expected accurate hours and services information surfaced at the search results screen. Participants made suggestions like, 'hover over icon for more information', 'add a bullet', and 'add a drop down' to get specific explanations about each status.

"Some participants expressed bypassing the facility locator altogether, using Google to get to the facility's website directly."

[Filter Categorization for Facility Locator](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/redesign/filter-categorization/research-findings.md)
Card sort for categories within locator. Not relevant for us.

[Facility Locator user expectations for search](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/FL-Search-march2020/research-findings.md)
No data on detail page or navigating to detail page.

[Facility Locator Urgent Care PDF](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care-PDF/research-findings.md)
No data on detail page or navigating to detail page.

[Facility Locator Urgent Care Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/urgent-care/research-findings.md)
Not 100% relevant for detail pages, but findings pointing to keeping filters visible on Find experience.

"Remove "show all filters

-   No participants clicked on the show all filters

-   Participants expected to see their results after filling out the initial search criteria

-   Sorting the search results list may be worth exploring as participants mentioned they wanted to see a long list of options to choose from for multiple reasons (e.g. location, hours)"

[Facility Locator Discovery Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/discovery-sprints/user-research/user-research-findings.md)

5\. There is a need to see some location information at a higher level. Though the location specific pages proved helpful when preparing for a visit, Veterans call a location when they have questions or need help. For that reason, partipants mentioned that showing the service(s) they chose and facility phone numbers on the search results list would prove beneficial.

[Week of 2/13/17 Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/2021-mobile-experience-research/research-findings.md)
No data on detail page or navigating to detail page.

[9/29/16 Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/archive/9.29researchfindings.md)

-   "Participants liked the detail page a lot. One expected services to be clickable to see more information."

-   "Many people begin with a web search rather than seeking the official site to find locations (stores, libraries, etc)"
