### ISSUE TITLE
Implement Sidekiq Job for 686 Submission

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8762]
## Goal
Once a user submits the 686 there are several actions, services and calls that get engaged which can take some time.  To release the user from having to watch that or interfere with it, those actions will get put into a Sidekiq job to be done "later."

## Considerations
- There is a job now that is working
- Error handling first

## Tasks
- [x] Create the job
- [x] Add tests for job

## Acceptance Criteria
- [x] A form was successfully submitted when run from a job

**Comment by digitaldrk** [comment]
Confirmed the submission calls are being made: https://dsva.slack.com/archives/CBU0KDSB1/p1594669160169600
