### ISSUE TITLE
[DevOps] Discovery on configuring GitHub Self-Hosted Runners for CIE

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87624]
## Description
I've never done this, I don't know what I don't know, so I'll just YOLO and see what I can learn.

## Tasks
- [x] [DevOps] Try to set up GHA self-hosted runners in `global`.
- [x] [DevOps] Document in thread.
- [x] [DevOps] Open followup ticket(s) to address followups if not completed within timebox.

## Acceptance Criteria
- [x] Findings documented in thiread.
- [x] Followup ticket(s) opened as appropriate.

**Comment by ndouglas** [comment]
This seemed like it was going to suck, so I opened a platform support ticket to get integrated into the existing Platform system. I wasn't enthusiastic about that, so I kept looking while I waited for someone to respond to my ticket. At some point, I found this approach [1] which I implemented in a couple hours. It's not exactly battle-tested but seems dramatically superior to the Platform system, so I'll be testing it today (Friday, July 5) to see if it does everything I need. 

[1] https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html
