### ISSUE TITLE
Add linting rule for removing totally unused code

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#8763]
## Overview

`vets-website` has lots of code that is old/unused, and its presence can cause confusion and just exists as a burden.  Here is an example from https://github.com/department-of-veterans-affairs/vets-website/pull/12489

![image](https://user-images.githubusercontent.com/2008881/81092046-e4acaa80-8eb4-11ea-82ad-54fff5164b3f.png)

With the `no-unused-exports` linting rule, this unused code would not have gotten left behind:

![image](https://user-images.githubusercontent.com/2008881/81092946-3a358700-8eb6-11ea-835c-b1f13585ca24.png)

When I install and setup this rule locally, I get 371 linting errors.

## Goal
Add a linting rule which will ensure that when some code is deleted, nothing gets "orphaned"

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Fix local linting errors in [`import/no-unused-modules`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unused-modules.md) rule
- [ ] Turn the rule on in the additional testing step
- [ ] After allowing time for feedback, move the rule into the main linting process

## Acceptance Criteria
- [ ] There will be no orphaned or unused code in `vets-website`

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by meganhkelley** [comment]
Should not create a custom rule, use something that already exists. 

Allow time to discuss with VFS teams — coordinate messaging with Megan
