### ISSUE TITLE
Define Readiness Probe for per Pod HPA for dev

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#87633]
Traefik, our Kubernetes Ingress Controller, round-robin serves requests to our ready pods. Our current check for "readiness" is an HTTP health check that must fail multiple times before it marks a pod as unready. A better metric would be Puma's pool capacity, determined as a percentage as we do for our HPA scaling. If a given pod has less than 25% availability, Traefik should not send requests to it until it has recovered and become ready again.

## Tasks

- [x] Determine proper HPA metric for Puma pods
- [x] Write script for scaling metric
- [x] Test script in dev environment

## Acceptance Criteria

- [x] A working Readiness Probe script is implemented in our EKS dev environment
