### ISSUE TITLE
Determine if user input to Appoint MVP gets pushed to Profile

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87631]
## Background
Consider the Appoint MVP experience -- both the prefill pattern (intended for auth users with complete profiles) and the text input pattern (intended for all other users) -- and if the information users enter/update should align with Profile.

It seems like users need to call VA to update:
1. Social security number
2. Date of birth
3. VA File number
4. Branch of service

But we could push updates to:
1. Email
2. Phone
3. Mailing address

## Tasks
- [x] Understand what VA Forms is doing
- [x] Look to Profile for advice
- [x] Recommend a decision to the team
- [ ] Get sign off

## Acceptance Criteria
- [x] We determine if user input to Appoint MVP should get pushed to profile and if so, what particular information gets pushed.

**Comment by oddball-lindsay** [comment]
VA Forms is not pushing info to Profile:
> When we have used prefill, we've not pushed updates to profile (this is not built into the forms library in an easy way -it's custom every time, which is why we've not used it).  I understand that name/SSN (and maybe a few others) can't be edited even in profile and a user has to call to update that info...

**Comment by oddball-lindsay** [comment]
Profile's main point is to set clear expectations that any information updates/edits in our Appoint experience will also be pushed to Profile.  If users don't understand this, they may accidentally update their Profile with information that is not intended to be permanent (i.e. they are staying with someone and have a different phone or address temporarily).

They recommend some conditional logic, if we do push to Profile:
> Could entering data or a change of data in X trigger a pattern in Y of “do you mean this or that version”? Or when new version is entered in X, the system would recognize this conflicts with an old version elsewhere and offer options? (A pattern here might be an address autofill like you see in I think Shopify.)

**Comment by oddball-lindsay** [comment]
My recommendation: If a user updates/edits contact information in Appoint a Representative MVP, **do not push those updates to the Profile**. 

Reasoning:

1. Research ([see the first quote in section 4.i](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-02-appointarep-unauth-usertest/research-findings.md#step-4-of-5-accredited-representative-permissions-address-change)) revealed that users are very wary of the address authorization step because it could result in their information being updated without their awareness and consent.
2. Adding in conditional logic to ensure user awareness increases the scope of our MVP product on both design and development, possibly research too.  I don't think this increase in scope is necessary for an MVP.

Happy to explore Profile updates (and additional designs that set those expectations) for Appoint v2 users that are taking advantage of digital submission, if we think it makes sense to enhance that experience.

**Comment by oddball-lindsay** [comment]
Can consider a warning that no information is going to push to profile, and to make any edits directly in Profile.

**Comment by oddball-lindsay** [comment]
Discussing with enablement: https://dsva.slack.com/archives/C05L6HSJLHM/p1721064185404579

**Comment by oddball-lindsay** [comment]
We need to figure out if we can store number, email and mailing in Save In Progress backend.

**Comment by oddball-lindsay** [comment]
Confirmed with the team that there are no technical concerns with not pushing information to the Profile in MVP. See Slack message linked above for context.  Added this decision to our new [Decision and Change Log: Appoint a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/decision-change-log-appoint-a-representative.md)
