### ISSUE TITLE
Test and deploy Readiness Probe to staging and prod

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#87642]
Traefik, our Kubernetes Ingress Controller, round-robin serves requests to our ready pods. Our current check for "readiness" is an HTTP health check that must fail multiple times before it marks a pod as unready. A better metric would be Puma's pool capacity, determined as a percentage as we do for our HPA scaling. If a given pod has less than 25% availability, Traefik should not send requests to it until it has recovered and become ready again.

In https://github.com/department-of-veterans-affairs/va.gov-team/issues/87633, a script was written and deployed to dev. Move this script into other environments.

## Tasks

- [ ] Deploy and test script in staging
- [ ] Deploy and test script in production

## Acceptance Criteria

- [ ] A working Readiness Probe script is implemented in our EKS staging environment
- [ ] A working Readiness Probe script is implemented in our EKS production environment
