### ISSUE TITLE
Create V3::ProfileInformation Service (dupe 2)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87645]
This is a dupe ticket of [87644](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87644), pending return of assigned developer. 

## User Story
As the developers responsible for backend work on the EVSS PCIU migration,
We want to create the V3::ProfileInformation Services configuration and responses,
So that we can perform the necessary migration of PCIU from the current EVSS environment.

## Issue Description
In this ticket, the objective is to create the V3::ProfileInformation Service's configuration and responses.

## Tasks
- [x]  Configure V3::Profileinformation service
- [x]  Configure V3::Profileinformation response (try to add duplicate methods used from other services in this response, if you can)
- [x]  Configure V3::Profileinformation's configuration
- [x]  Configure V3::Profileinformation redis

## Success Metrics
- [ ]  V3::Profileinformation service environment is created and configured
- [ ]  V3::Profileinformation response environment is created and configured (try to add duplicate methods used from other services in this response, if you can)
- [ ]  V3::Profileinformation's configuration environment is created and configured
- [ ]  V3::Profileinformation redis environment is created and configured

## Acceptance Criteria
- [ ] The V3::ProfileInformation service is configured, readying the next steps for PCIU migration. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
7/29 update: @RachalCassity will review the PRs and add summaries, then this ticket can close.

**Comment by RachalCassity** [comment]
Testing will need to be done after 3 PRs are merged.

**Comment by jennb33** [comment]
7/31 update - Should we have Tom review the PR?

**Comment by jennb33** [comment]
Duped for Sprint 7, ticket [89718](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89718)
