### ISSUE TITLE
Copy of  Create V3::ProfileInformation Service

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87644]
## User Story
As the developers responsible for backend work on the EVSS PCIU migration,
We want to create the V3::ProfileInformation Services configuration and responses,
So that we can perform the necessary migration of PCIU from the current EVSS environment.

## Issue Description
In this ticket, the objective is to create the V3::ProfileInformation Service's configuration and responses.

## Tasks
- [ ]  Configure V3::Profileinformation service
- [ ]  Configure V3::Profileinformation response (try to add duplicate methods used from other services in this response, if you can)
- [ ]  Configure V3::Profileinformation's configuration
- [ ]  Configure V3::Profileinformation redis

## Success Metrics
- [ ]  V3::Profileinformation service environment is created and configured
- [ ]  V3::Profileinformation response environment is created and configured (try to add duplicate methods used from other services in this response, if you can)
- [ ]  V3::Profileinformation's configuration environment is created and configured
- [ ]  V3::Profileinformation redis environment is created and configured

## Acceptance Criteria
- [ ] The V3::ProfileInformation service is configured, readying the next steps for PCIU migration. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
@RachalCassity needs to redefine this ticket based on the PRs and results from their review.

**Comment by jennb33** [comment]
7/10 - Closing this ticket and bumping the rest of this work to Sprint 6 due to resource availability. Dupe ticket for Sprint 6 is [87645](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87644).
