### ISSUE TITLE
Tune Vets API Puma Worker Count

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#87653]
Puma's maintainers recommend between 4 and 32 Puma Workers per Pod. We recently raised it to 6. More may work better but Kubernetes is designed around small pods, so we may want to tune this down. Metric monitoring will be needed here.

## Tasks

- [x] If it does not, decrease workers to 4 to determine if that will cause issues
- [x] Determine if nodes can be downgraded and if so, determine an appropriate instance size
- [x] If nodes can be downgraded, recommend that Infra team is aware and delegated.

## Acceptance Criteria

- [x] A pass at adjusting worker count has been performed and confidence in our current metric is higher.

**Note**: As other values are tuned, we may want to take a second pass at adjusting this value. Another ticket will be spun up if necessary.

**Comment by ericboehs** [comment]
I'd like to discuss instance size with Kyle next week.

This is mostly done but we're still tweaking the ASG min size.

**Comment by ericboehs** [comment]
We've got our min ASG down to 4. This is about the lowest we want to go here. We're tweaking three other parameters and then we can try scaling down from c5n.9xl to c5n.4xl. The other parameters:
- cpu.requests/limits
- minReplicas for all replicaSets
- Number of bulkheads (could consolidate)

**Comment by ericboehs** [comment]
After more tuning, we're going to post-pone resizing nodes until we can get a handle on ASG scaling during deployments. There's an argument for actually INCREASING their size but for now c5n.9xls seem like a good choice.
