### ISSUE TITLE
Portal Releases 2024 (July, August, September)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#87650]
## Issue Description
A quarterly epic to track releases and updates.

If a release ticket is required, it can be included under this epic allowing the original work Epic to close as all development items are closed.

## Tasks
- [ ] Note epics and super epics that release and close.
---
#### **Monthly expense work to support:**
- (S)Epic #[75716](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75716) Portal Overall FE/BE Logic Shift and Code Cleanup
- Epic #[79904](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/79904) Portal Maintenance 2024 (April, May, June)

**Release items**
Ticket #[68302](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/68302) Housing expenses (Mortgage/Rent) and Other expenses updates
Ticket #[83576](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/83576) [FSR] Housing expenses testing

- [Release Ticket #91946](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/91946)
- [x] Thursday 09/05/24 - 5%
- [x] Friday 09/06/24 - 25%
- [x] Monday  09/09/24 - 50%
- [x] Wednesday 09/11/24 - 100%
---
#### **(S)Epic #[82018](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/82018) Payment history (Pre MVP - Increase/decrease & Accordion removal from how to pay)**
- [Release Ticket #91942](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/91942)
- [x] Thursday 09/19/24 - 25%
- [x] Friday 09/20/24 - 50%
- [x] Monday  09/23/24 - 100%

---
#### **(S)Epic #[75716](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/75716) Portal Overall FE/BE Logic Shift and Code Cleanup**
- [Release Ticket #87013](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87013)
- [x] Monday 09/01/24 - 5%
- [x] Monday 09/01/24 - 0% due to issues discovered
    - [x] Monday 09/30/24 - 5%
    - [x] Tuesday 10/01/24 - 25%
    - [x] Monday 10/07/24 - 50%
    - [x] Wednesday 10/09/24 - 100%

---
#### ***(S)Epic #[48133](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/48133) Wizard Work**
- Release Ticket
- [ ] Day XX/XX/24 - X%
---
## Acceptance Criteria
- [ ] At the end of quarter (~ September 30, 2024) this epic should be closed.

**Comment by Tom-Davis** [comment]
Closing as all scheduled releases are complete.
