### ISSUE TITLE
Drupal audit: Iraq in Spanish pages

### ISSUE THREAD

**Issue by moviedosoco** [department-of-veterans-affairs/va.gov-team#87667]
## Issue description
The State's translation team responded to our question about whether to use Irak or Iraq for consistency and recommended the use of **Irak** across all the Spanish pages in VA.gov. 
Therefore, we need to do a content search in Drupal for places where it's written "Iraq" and replace it with "Irak." 

---
## Tasks

- [x] Do Drupal content search (Victoria)
- [x] Update Drupal pages with changes (Victoria)
- [x] Review changes (Sara)
- [x] Publish page (Sara)

## Acceptance Criteria
- [x] Pages are live with changes

## Configure this issue
- [ ]  #84013

**Comment by moviedosoco** [comment]
Hi @RLHecht and @saratorres2 Drupal search and updates are completed.

**Comment by moviedosoco** [comment]
@saratorres2 Hi Sara, these are the live pages where the word 'Iraq' was replaced with 'Irak':
1) [Elegibilidad para el cuidado de la salud de VA](https://www.va.gov/health-care/eligibility-esp/): In 2 places: Alert Body and Featured Content (the change in Alert Body won't show in preview).
2) [La Ley PACT y sus beneficios de VA](https://www.va.gov/resources/the-pact-act-and-your-va-benefits-esp/): In 3 places.

**Comment by saratorres2** [comment]
@moviedosoco I've reviewed and publish changes to these to pages (including publishing the change separately in the alert for the [Elegibilidad para el cuidado de la salud de VA](https://www.va.gov/health-care/eligibility-esp/) page.

**Comment by saratorres2** [comment]
@moviedosoco Confirming changes are live and closing ticket.
