### ISSUE TITLE
Update documentation for External Service Performance Monitoring product

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#8766]
## Background 

BE Tools team met with DEPO and VSP Leadership to present and brief on the External Service Performance Monitoring product. Requests were made for desired improvements.

## Goal

[External Service Performance Monitoring](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/external-service-monitoring/README.md) product v0.2 sees the requested improvements implemented. 

## Tasks

- Update product documentation to include details of:
  - [ ] How the reporting script currently works
  - [ ] How the SLI thresholds are defined
- [ ] Define thresholds per service instead of per dashboard
  - 94% availability needs to be in the red 
- [ ] Would like the SLO report to be generated weekly

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
Script and walkthrough drafted [here](https://github.com/department-of-veterans-affairs/va.gov-team/pull/8900).

The next major version of Grafana includes configurable thresholds, but it's not clear when that feature will be available to VSP. I'll do some discovery on how we might work around this limitation for the time being.

**Comment by kfrz** [comment]
Updated script and documentation in [#8900](https://github.com/department-of-veterans-affairs/va.gov-team/pull/8900/files) to `v0.0.2` -- I don't want to invest too much effort into this solution as it's not the best way by any means of doing what we need.
