### ISSUE TITLE
[spike] Investigate using GitHub codespaces

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#87670]
## Value Statement

**_As a_** person interested in reviewing app changes
**_I want to_** evaluate the app before it gets to staging
**_So that_** I don't have to rush to review, test and iterate changes before these changes get to production

---

## Background Context

While updating the Higher-Level Review content, we made changes that we'd like to review before it makes it to staging, then out to production. Production deployment is now at noon, so we now feel more rushed in the morning.

Adding a feature flag for the changes turned out to be more complicated than we anticipated. One page adds hint text to a radio, and since that only allows a string value, we have no _easy_ method to update the `uiSchema` to add or remove the hint based on a feature toggle. To work around this issue, we'd need to change from using the schema to a custom page, which is more work than is needed for a simple hint text change.

Evaluation of codespaces may allow us to review and iterate on the changes from a page outside of the staging flow. This would be similar to review instances, but hopefully less flaky.

## Acceptance Criteria

- [ ] Investigate using GitHub codespaces
- [ ] Determine feasibility of using codespaces for review, research, and iteration 
- [ ] Findings are documented

## Tasks

- [ ] Set up GitHub codespaces for a branch of work
- [ ] Determine ease of use: access, login, navigation, etc.
- [ ] Determine ease of iteration: steps to build & update
- [ ] Document findings

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Difficult to get API server running. CORS problems. Other dev using Codespaces suggested using mock API, but might not working. Timeboxed for another couple hours.

Might have to default to using review instances.

**Comment by Mottie** [comment]
I think I've exhausted my investigation on codespaces:

Steps to get running:

- Follow along with [developer docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/using-github-codespaces)
- Add `VETS_WEBSITE_BUILD_CONTENT` to `NO` in personal GitHub codespace secret setting
  - If you don't do this, [content build appears to keep failing while loading assets](https://dsva.slack.com/archives/C01UB5A823V/p1720023057795159) and also appears to be the same issue in [review instances](https://dsva.slack.com/archives/CBU0KDSB1/p1720455134638439)
  - Without the content build, you won't be able to get to the login pages
- Build codespace from GitHub branch
- Run `yarn build --pull-drupal` to get some static content set up (not all 😞) - this might be due to a build problem that was recently reported
- Attempts to set up vets-api/mock api
  - Run `yarn watch --env api=https://staging-api.va.gov` will set up vets-api in the codespace, but CORS errors will prevent you from logging in
  - Or, run a [mock server](https://github.com/department-of-veterans-affairs/vets-website?tab=readme-ov-file#running-a-mock-api-for-local-development): `yarn mock-api --responses ./src/path-to-mock-settings.js`; this doesn't appear to even work, network requests are still attempted from staging api
- Build the codespace on the web using `npx http-server build/localhost -s -c-1 -p 3002`
  - I tried `--cors` and `--proxy` settings to point to the mock api, but still no luck
  - Even with the [recommended CORS browser extension](https://mybrowseraddon.com/access-control-allow-origin.html), I wasn't able to get this working

Pros:
- Stable URL that doesn't expire after a week (review instances expire & need to be refreshed) 
- Relatively similar to how review instances behave
- Great for setting up a mock app that doesn't require authentication 

Cons:
- Setting up isn't currently working with a full content build (static pages likely won't be available)
- Setting up the staging server doesn't allow authentication due to cross-origin resource sharing (CORS) problems
- Setting up a mock server doesn't work; codespaces ignore it completely
- Codespaces don't allow you to link directly to an application; you have to load the main page first, then navigate to the app url manually

**Comment by eileen-coforma** [comment]
Robin to write some documentation before closing.

**Comment by eileen-coforma** [comment]
Not using Codespaces because it does not work for our purposes.

**Comment by Mottie** [comment]
Completed preliminary work on [testing new features on VA.gov](https://docs.google.com/document/d/1uUGG58x7RTn5rkB2wck6XBGjX-M1WAirguCIg3iwRbI/edit?usp=sharing) (feature toggles vs review instance vs codespaces vs duplicating the app) and [shared with the other vfs-engineers for feedback](https://dsva.slack.com/archives/C01UB5A823V/p1721923140068779)

**Comment by Mottie** [comment]
The document is still being reviewed. We need to ask platform support where this document should ultimately be added.

**Comment by anniebtran** [comment]
Still being reviewed, started adding new preview environment

**Comment by anniebtran** [comment]
Will open a new ticket for comparison documentation
