### ISSUE TITLE
Schedule Remaining Domo Datasets to Append GA4 Data in BigQuery 

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#87674]
### Description
Once we have finalized our data QCs, we will start to append GA4 data on top of the existing UA data in our Domo datasets that power our reports.

This will be done in a series of waves, based on impact and priority. The timing on waves can be found [here](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3213885442/GA4+Migration+Domo+Report+Updates). 

---

### Tasks
- [ ] ~For Wave 2, schedule weekly datasets to append GA4 data on **July 8 - July 12**~
- [ ] ~For Wave 3, schedule monthly datasets to append GA4 data on **July 15 - July 19**~
- [x] Confirm GA4 data has appended with relevant fields in Domo.

### Acceptance Criteria

- [ ] Wave 2 UA-driven datasets tied to prioritized Domo dashboards have been scheduled to `append` with GA4 data.
- [x] Wave 3 UA-driven datasets tied to prioritized Domo dashboards have been scheduled to `append` with GA4 data.

**Comment by johnny-jesensky-adhoc** [comment]
The GA4 append statuses of datasets are also captured in [this spreadsheet](https://docs.google.com/spreadsheets/d/1mIsJEM5sQFVi8lWIMI6eRiOUQUwO9wdVjjsBis0QqXY/edit?gid=884424480#gid=884424480.)

Moving this to _Done_. Will connect with Phil on if there are any remaining gaps that we'll want to wrap up in another ticket, (if needed).

FYI @dorseypa1
