### ISSUE TITLE
AE-Sprint 21 (5/6-5/20)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8767]
## Profile 2.0: Order of priorities

1. Resolve Direct Deposit issue 
2. Finish any open design tasks
3. Build - Continue build
4. Analytics - review (VSP cycle)

### Direct Deposit
- [x] Investigate increased Error rate on Direct Deposit #8852

### Design
- [x] [Design] - LOA1 Profile design #8570
- [x] [Design] Mobile navigation documentation #8234
- [ ] [Design] Design Mobile Sub Navigation #8233 
- [x] [Design] - Update email address mocks #8229

### Build
- [x] [FE] Profile 2.0: Build the direct deposit section #5355 
- [x] [Tech Debt] Clean up addressFormatter and use it in AddressValidationModal #8596
- [ ] [FE] Profile 2.0: Build the contact information section #5353  
- [x] [FE]  Mount a new profile wrapper that will be responsible for showing either the old or new Profiles #8698 
- [x] [FE] - Change how FE determines in an address is overseas military or not and check/uncheck box #8752 
- [x] [FE] - Switch to using React based breadcrumbs on the old profile #8692 
- [x] [FE] - Change Profile bread crumb hard reload to client side router change #8755  
- [ ] [FE] - Remove everything related to "Account" if profile is turned on #8699 

### PM
- [x] Determine what staging users we need/should use for Profile 2.0 QA #8284
- [ ] Submit Analytics Review Ticket #TBD 
- [ ] [Submit IA Review Request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#information-architecture-ia-request) #TBD

## Address validation
- [x]  VA.gov profile: Investigate why some VA.gov profiles are failing to initialize in VA Profile [101](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/101)

## Miscellaneous, bug fixes, maintenance, hardening, 508 etc
- [ ] [BE] Fix MHV session 400 errors #7814

**Comment by Samara-Strauss** [comment]
@mshea0606 can this be closed?

**Comment by mshea0606** [comment]
@Samara-Strauss Yes, closing this now.
