### ISSUE TITLE
[CDP] VHA - Format account number to match pay.gov

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#87678]
## Description

We received feedback that the **Account Number** format in the CDP is one long string which makes it hard to figure out how to fill it in Pay.gov. 

We need to figure out the proper format to make it easy to pay your debt via pay.gov

![Screenshot of issue](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/6919ed12-f256-41c4-9ccb-8dc2c091e40c)

>"[VA.gov](http://va.gov/) can help by just adding dashes to the account #, which is how it's already displayed in the PDF anyways.
it's like if a phone number was displayed 7347782311 but then you had to put it into input boxes like 734 778 2311 except you had no idea how many characters went in each box because you don't know standard phone number formatting. So displaying the number [734-778-2311](tel:7347782311) would make it more obvious

## Tasks
- [x] @denisecoveyduc will ask VHA to get the proper account number format
- [x] Once we have the format, we need to update the copay detail and copay HTML statement pages in our mockups.
- [ ] Then create a PR to update this in production

## Acceptance criteria
- [x] Account number format has been figured out
- [ ] New format has been applied to Copay Detail and HTML Statement pages
- [ ] PR for updates have been merged

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
@Tom-Davis not sure what Epic to put this ticket in. It's a usability enhancement for the debt portal. 

cc: @HeatherRienks @mgleo @denisecoveyduc

**Comment by mgleo** [comment]
On staging, I am seeing that we're sharing the first 4 sections, the numbers of their account, on the Copay Detail page. We're not sharing the letters that come after these numbers.

Screenshot of the account number on the Copay Detail page where it shows their statement ([link to page](https://staging.va.gov/manage-va-debt/summary/copay-balances/eea5e722-ced7-4812-a5e9-d1d32472f986/detail/statement)):
<img width="644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e1b5d865b48c07f963b667bdf003ea330f049b1/Screenshot%202024-07-11%20at%205.05.09%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 5.05.09 PM.png" />

Screenshot of the account number on PDF of this same statement. It looks like the letters are the first 5 letters of their last name:
<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGpUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd7dd0470fecaa26d100c88a3c2069b97b1aa622/Screenshot%202024-07-11%20at%205.05.01%E2%80%AFPM.png" alt="Screenshot 2024-07-11 at 5.05.01 PM.png" />

**Comment by HeatherRienks** [comment]
Per Sprint Planning, we will need info from Pay.gov team. This will be more of a FE effort, rather than Design.

**Comment by HeatherRienks** [comment]
@denisecoveyduc - two questions:
1- Do you have a contact at Pay.gov?
2- Who can we chat with at VHA to get the proper account number format?

**Comment by denisecoveyduc** [comment]
@HeatherRienks @Tom-Davis 
Both will be the same contact which I have yet to track down. I will keep you posted. For now I'd consider this bug blocked until we have confirmation

**Comment by denisecoveyduc** [comment]
- The Pay.gov site is looking for the account number to be written in 5 sections.  (see image)

<img width="1185" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a7b78059957c726b5aa0f3c3b79d70c12433b8a/image.png" alt="image.png" />




- The account number is written in that format on the top of the patient statement. (see image)


<img width="516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57d12b89486e779d9c21ec4a517d5cec9b984aed/image.png" alt="image.png" />

Can we compare this format to the format we receive for the account number?  
Ideally we can separate the account number into these 5 parts so that it becomes clear to the Veteran what portion of the number should be entered into each section. 

If we are not receiving all 5 sections of the account number then we need to discuss this with the VBS team. They provide the statement information and therefore I'd expect they should be able to provide a complete account number. 
FYSA: @Tom-Davis, @HeatherRienks, @mgleo, @josephrlee

**Comment by josephrlee** [comment]
@maxx1128 @digitaldrk, I have a couple of questions for y'all: we're trying to understand how the account number is formatted and how the last name part gets added. 
- Do y'all know if [Cerner Account Numbers](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/medical-copays/containers/DetailPage.jsx#L28) differ from VistA account numbers
- Can we do a lookup on prod on what the response of an account number is to better understand the format after standup this week?

cc: @mgleo @charlottecesana @Tom-Davis @alatempa24

**Comment by josephrlee** [comment]
I found [a very old thread](https://dsva.slack.com/archives/CE4304QPK/p1632242396083400) in the DVSA slack and posed the question about who we can reach out to at pay.gov to improve the account number input error handling and also figure who our best contact is. 

cc: @denisecoveyduc @Tom-Davis @mgleo

**Comment by alatempa24** [comment]
Meeting scheduled with Monica Smith & co on 8/14

**Comment by HeatherRienks** [comment]
@josephrlee - any updates to add to this ticket after the meetings with Monica and VBS? 
cc: @Tom-Davis

**Comment by josephrlee** [comment]
This will roll again. We met with VBS and @denisecoveyduc has been working with them to get a more accurate version of the breakdown to be able to get the right format.

cc: @denisecoveyduc @HeatherRienks @Tom-Davis @mgleo @charlottecesana

**Comment by denisecoveyduc** [comment]
Based on the discussions I have had I understand that for both Vista and Cerner stations CCPC is sending 16 digits to VBS. VBS is sending those 16 digits to VODA. Those 16 digits make up the information needed for the first 4 parts of the information required for the pay.gov breakdown.  (see pink color on charts below) 

The debt resolution team needs to:

- separate the 16 digit  into four parts (part 1=3 characters, part 2= 4 characters, part 3 =4 characters and part 4 = 5 characters).  
- For the fifth part the team the first 5 characters (or less) of the users last name need to be presented to represent part 5

![image](https://github.com/user-attachments/assets/e6bc7810-1536-4969-a399-5da90a7c2fe2)

**Comment by josephrlee** [comment]
@denisecoveyduc, I've [updated the mockups in Figma](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=117-27779&t=KkrF6YXWL23qGjaw-11) and have added the above table as annotations. 

<img width="1091" alt="Screenshot 2024-08-29 at 2 25 33 PM" src="https://github.com/user-attachments/assets/197ca632-365d-480f-8171-9ba6f0c48862">

@digitaldrk, let's plan on syncing up next week when I'm back to figure out how to implement this. 

cc: @Tom-Davis @mgleo

**Comment by Tom-Davis** [comment]
@denisecoveyduc Is there any source of the complete account number (with the breaks or not) that includes everything including the last name?

We can perform the logic to separate and combine the parts, but this opens us up for a potential mis match if anything ever changes upstream or in the account number presentation.

If there was a source of record that always had the full concatenated number (even without breaks) that we could reference rather than performing the current day logic we could avoid any issues in the future with changes.

One example/variable where our logic could differ would be with a short lasty name and a suffix.

EX: James Lee III (3rd)

Is the last name Lee or LeeII or III

Hopefully I am not overthinking it for the sake of futureproofing.

**Comment by denisecoveyduc** [comment]
@Tom-Davis If I am understanding the question the source would be the data feed we are getting from VBS which contains the account number as all16 digits together without the last name.  The logic you are referring to would only be used to present the account number in 5 parts for the Veteran.  
I see two options 1) We (VODA) break the account number apart to represent it for Veterans based on what we know. I think this would be the simplest because it doesn't involve any other teams to achieve.  This is also a bit of a stop gap as we will eventually have a better integration with pay.gov meaning that when a Veteran clicks to pay we prefill the information for them so they don't need to reference this account number to enter it manually. 
2) the second option would be to meet with VBS to change the 16 digits into the 5-part format but that requires code changes and I worry that would introduce more problems and cause a lot of unnecessary churn for something that is temporary. 
Happy to discuss further but hopefully that helps address your question/thoughts.

**Comment by josephrlee** [comment]
@Tom-Davis @denisecoveyduc, is it okay to continue moving forward with the plan of creating a new dev ticket for this then?

**Comment by josephrlee** [comment]
@Tom-Davis, closing this ticket out now that the [implementation ticket has been updated](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91391).

cc: @mgleo @denisecoveyduc @HeatherRienks @dhill802 @charlottecesana
