### ISSUE TITLE
[DevOps] Create AppConfig application for system tests.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87688]
## Description
In `global`. This will be used to represent the system tests, enabling them to retrieve information about the infrastructure for use in tests.

## Tasks
- [x] [DevOps] Create `system_tests` module in `global`.
- [x] [DevOps] Create `appconfig.tf` file.
- [x] [DevOps] Create `aws_appconfig_application` block.
- [x] [DevOps] Update `global_iam` as needed to accomplish.

## Acceptance Criteria
- [x] AppConfig application exists for system tests.
