### ISSUE TITLE
[DevOps] Create per-env `system_tests` module for system tests.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87689]
## Description
Followup to #87688. Create an AppConfig environment for the system tests.

## Tasks
- [x] [DevOps] Create `system_tests` module in `modules`.
- [x] [DevOps] Create `system_tests` app in each environment.
- [x] [DevOps] Create core functionality for applying app.
- [x] [DevOps] Create `aws_appconfig_environment` block for system tests.
- [x] [DevOps] Update `iam` module as needed.

## Acceptance Criteria
- [x] `system_tests` module is created and resources apply in all environments.
