### ISSUE TITLE
Build an interface for the Editor view in CMS

### ISSUE THREAD

**Issue by cjterdi** [department-of-veterans-affairs/va.gov-team#87699]
## Description
Using CMS DS components, design a UI workflow for an editor to add a "step" as part of the form engine workflow.  Using a form-pattern that is codified in the VADS as an example, the workflow must enable the editor manage the primary attributes in order meet the design and accessibility guidelines for published VA digital forms. 

## Acceptance criteria
- [ ] A figma doc with a draft layout for publishing a step within a form using components defined in the Drupal CMS DS 

```[tasklist]
### Tasks
- [ ] Create a [draft] CMS pattern for editors to add form content and configure attributes using standard Drupal CMS DS components
- [ ] Define a limited set of primary attributes for an initial draft workflow
- [ ] Provide a standard pattern for "view only" content and "editable" content and editor help text
- [ ] Provide [draft] standardized help text for the editor (may require CMS design collab cycle review)
```

## Additional info

- The first draft may not include every attribute defined in the form-patterns, but the workflow pattern for managing attributes must adapt to add/edit/remove attribute requirements. 
- A "View" and "Edit"mode may require separate tickets
- Involving the CMS design collab is not part of this ticket

**Comment by cjterdi** [comment]
Since the Drupal CMS DS has not been maintained. As I build out an interface, I may initially need to update the DS with more frequency than ideal.

**Comment by cjterdi** [comment]
Duplicate ticket [](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86459)

**Comment by cjterdi** [comment]
Duplicate ticket [https://github.com/department-of-veterans-affairs/va.gov-team/issues/86459](url)
