### ISSUE TITLE
[DevOps] Create AppConfig configuration profile, deployment strategy, and deployment for system tests.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87690]
## Description
Followup to #87688, #87689. System tests then get a configuration profile that defines a schema for the appconfig data, a deployment strategy that defines how the configuration is deployed, and a deployment that actually sets the data.

## Tasks
- [x] [DevOps] Create a configuration profile. Include the LoROTA API URL and VPC endpoint to start.
- [x] [DevOps] Create a deployment strategy.
- [x] [DevOps] Create a deployment that sets the actual data.

## Acceptance Criteria
- [x] AppConfig is populated correctly.

**Comment by ndouglas** [comment]
Done!
