### ISSUE TITLE
[FE, BE] 10-10EZ - TERA Improvements: Schema Updates

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#87693]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's service dates. 

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By introducing branching logic to the TERA questions, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)
- [Figma designs for content](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)

## Tasks
- [ ] Make updates to JSON schema to incorporate the new Gulf War questions
- [ ] Review with the team
- [ ] Inform QA/Team when ready to start testing

## Acceptance Criteria
- Backend schema is updated and ready for testing

**Comment by hdjustice** [comment]
We reference "New questions" in this ticket.  Which new questions are we referencing here?

**Comment by aagosto90** [comment]
@hdjustice The only new question is the [additional Gulf War question](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5148-22144&t=1ojvUg1lA9EMcAfl-1) that covers only the 2001 Gulf War for users who weren't old enough to service for the 1990 Gulf War. I'm not sure if we should include the Gulf War work in this ticket or a separate one, though. Let's discuss in planning :)

**Comment by hdjustice** [comment]
We may not need this afterall.  Holding ticket in backlog until we get thru the development of the TERA branching logic to be sure we don't need this effort.

**Comment by longmd** [comment]
Closing as not necessary for the initiative.
