### ISSUE TITLE
[BE] 10-10EZ - TERA Improvements: Data Mapping

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#87694]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's service dates. 

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By introducing branching logic to the TERA questions, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)
- [Figma designs for content](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)

## Tasks
- [ ] Confirm with VES there are available fields to map the additional Gulf War questions to
- [ ] Update backend data mapping to incorporate the additional questions
- [ ] Make any updates to data mapping that may be needed for questions that will be skipped (i.e. those questions should auto-fill a response of "no" - not "null")
- [ ] Review with the team
- [ ] Inform QA/Team when ready to start testing

## Acceptance Criteria
- Data mapping is updated and ready for testing

**Comment by hdjustice** [comment]
@aagosto90 - we reference "additional questions" in this ticket.  Is that still valid?

**Comment by aagosto90** [comment]
@hdjustice Yes, same as the other ticket, there is one new Gulf War question for the 2001 Gulf War and conditional date screen associated with it.

**Comment by hdjustice** [comment]
We may not need this afterall.  Holding ticket in backlog until we get thru the development of the TERA branching logic to be sure we don't need this effort.

**Comment by longmd** [comment]
Closing as not necessary for this initiative.
