### ISSUE TITLE
Prevent abusive disabling of ESLint

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#8769]
## Overview

We have ESLint in place to help with code quality in `vets-website`.  There are situations where it may be better to disable certain rules rather than conform to them.  For these cases, we want to be very specific about the ESLint rules that are being disabled.

## Goal
Specific reasons for disabling ESLint

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Find linting issues with the proposed rule and disable the specific rule(s) instead

## Acceptance Criteria
- [ ] The [`unicorn/no-abusive-eslint-disable`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-abusive-eslint-disable.md) rule is implemented
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bkjohnson** [comment]
The previous PRs have fixed all of the disabling issues in platform and app code with one exception: vaos

![image](https://user-images.githubusercontent.com/2008881/81422573-fafe7480-9107-11ea-95e4-82d7e86f84af.png)

It looks like vaos have [copied `moment-tz` into our repo](https://github.com/department-of-veterans-affairs/vets-website/blob/99b1656509130f9fc08ad55bc6a36768209d5be1/src/applications/vaos/utils/moment-tz.js).  I remember there being some problems in the past between moment and moment-tz, but I wonder if this should be in package.json instead.

**Comment by rianfowler** [comment]
can you close this ticket if it's done @bkjohnson - thanks
