### ISSUE TITLE
Indicate in 526 PDF question 16 if claim is related to Toxic Exposure

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#87706]
## Issue Description
When a Veteran is completing the 2022 Form 526 with Toxic Exposure questions, they answer "is this related to Toxic Exposure" within the application. Currently, if the answer is 'yes' that question is not making it to the PDF question 16 in the overflow. The copy for both TE and non-TE claims on the PDF is the same.
<img width="1516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0c2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c41233fad6effe5c28f51009ac261f2622a5bdcc/image%20%2824%29.png" alt="image (24).png" />

We want to update the PDF overflow for question 16 if a Veteran does claim Toxic Exposure so that it will say:
"Exposure Event: My condition was caused by an injury or exposure during my military service; Is related to toxic exposure."

[DSVA Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1720206552851579?thread_ts=1720206267.172359&cid=C04KW0B46N5)

---
## Tasks
- [ ] Add "is related to Toxic Exposure" to the exposureEvent column if a disability is related to Toxic Exposure

## Acceptance Criteria
- [ ] If a Veteran says yes their condition is related to Toxic Exposure, "is related to toxic exposure" will be present in question 16 of the PDF
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
Related to, but not blocking this ticket:
https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/87820

**Comment by pacerwow** [comment]
Today, the decision was made with OCTO to use "toxic exposure", not "Is related to toxic exposure"
