### ISSUE TITLE
Explore Domo for Quarterly Quantitative Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87700]
## Background
Quarterly metrics include user-initiated feedback, which does not come often enough to be considered significant, so we've decided to check on a quarterly basis instead of monthly.

I'm curious to see if we can track the quantitative feedback in Domo.  

These are the four A11 Questionnaire quantitative questions:
1. VA.gov experience (rating 1-5)
2. VA.gov understanding (rating 1-5)
3. General VA trust (rating 1-5)
4. Trust in VA commitment to Veterans (rating 1-5)

Best case, we show a bar chart of all four questions, where each bar represents the average across time.

These are the two VFS Questionnaire quantitative questions:
1. Were you able to do your task today? (yes/no)
2. What is your overall satisfaction with this site? (rating 1-5)

There is also the good/bad survey at the bottom our FAQ pag:
1. How do you rate your experience on this page? (good/bad)

## Tasks
- [ ] Understand if this data lives in Domo
- [ ] Connect with Mason to see if we can utilize this pre-existing data in Domo
- [ ] Mock up a quarterly metrics dashboard
- [ ] Partner with Mason to make the mock up a reality

## Acceptance Criteria
- [ ] We understand if a quarterly metrics dashboard is feasible in Domo
- [ ] If so, a quarterly metrics dashboard is created for quick quantitative insights into user-initiated feedback

**Comment by oddball-lindsay** [comment]
Existing Domo dashboards:
1. [Medallia Report](https://va-gov.domo.com/page/825663825?userId=1801042161) - covers landing page and Find a Rep.  **Does not seem to include FAQ page**.
   1. A11: VA.gov experience (rating 1-5) ✅
   2. A11: VA.gov understanding (rating 1-5) - **not in this report**
   3. A11: General VA trust (rating 1-5) - **unsure if this is in the report (is it the gauge with "How did this interaction change your trust in VA"?)**
   4. A11: Trust in VA commitment to Veterans (rating 1-5) ✅
   5. VFS: Were you able to do your task today? (yes/no) ✅
   6. VFS: What is your overall satisfaction with this site? (rating 1-5) ✅
2. [Content Engagement KPIs](https://va-gov.domo.com/page/80919003)

**Comment by oddball-lindsay** [comment]
For the FAQ good/bad survey -- one of the OCTO content leads creates a doc each month and links to a spreadsheet with all of the articles and their numbers. You can find them all [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content/unauthenticated-content-outcomes-and-metrics/monthly-experience-ratings/ratings-by-month).
