### ISSUE TITLE
DevShop prototype of sandwich content model

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8770]
## User Stories

- As a content producer, I want to be able to create content at the system or facility level so that I can provide localized information to Veterans.
- As a content producer, I want the editorial experience to be user friendly so that I can serve Veterans efficiently.
- As the VHA, I want national content to be maintained at the national level so that Veterans have a standardized experience.

## Goal(s)

- Consistent end user experience across multiple VAMCs
- Serve content producers by creating a flexible, reusable content model with governance mechanisms
- Improve the editorial experience
- Reduce support requests to CMS
- Editorial experience

## Tasks
Develop a prototype/model of sandwich content type for 
"Detail/Top Task pages"

- Make an appointment
- Register for care
- Pharmacy and prescription refills
- Request your medical records
- Billing and insurance
- Contact us

plus:

- DAV Vans: transportation for Veterans
- Policies

and Health service detail page nodes

- Caregiver support
- Mental health care
- Suicide prevention
- Homeless Veteran care
- LGBT Veteran care
- Minority Veteran care
- Women Veteran care
- Returning service member care

## Acceptance Criteria
- [ ] protoype is deployed to DevShop to test/validate 

VAMC system editor at the local level can:
- [ ] add local content
- [ ]  view national content
- [ ]  view who can edit national content
- [ ]  cannot edit national content
- [ ]  view how and where localized content will render
- [ ]  anticipate how content changes will impact updates/deployment and blast notifications to Veterans

VHA editor at the national level can:
- [ ] view all versions of these pages from all VAMC systems in one spot (Dashboard)
- [ ]  find and interact with national detail page content
- [ ]  can bulk edit national content
- [ ]  can easily access and add a token
- [ ]  can view informational errors about tokens
- [ ]  view how and where national content will render
- [ ]  anticipate how content changes will impact update/deployment and blast notifications to Veterans

**Comment by mmiddaugh** [comment]
## POC 1
https://www.loom.com/share/06027c617eb54db5ace3ada42f51f1b7
CMS DevShop: http://pr1737.ci.cms.va.gov 
Frontend: http://pr1737.web.ci.cms.va.gov/
Feedback from @kevwalsh: It’s an extremely flexible architecture, but i’m concerned about the ability to provide an intuitive editorial experience for these pages, either for the national folks or the folks on the ground at VAMCs. 

## POC 2
https://www.loom.com/share/90cdda1649634d58b9aca1e8a69ae8c5
Feedback from @kevwalsh: 
As a PAO on the ground at a VAMC, this looks like a much more intuitive experience. 
It’s worth exploring the “reusable paragraphs (content blocks)” architecture, given that the Public Websites team  this on their road map, particularly for their Q&A content.  This might allow nationally controlled content to be interspersed with the VAMC controlled content. But it’s somewhat new territory in the Drupal space and would require a lot of caution. It could be an opportunity to align with this use case of reusable content with another one, which is reusable FAQs / Q&As. I’m not sure if reusable paragraphs[Paragraphs](https://www.drupal.org/project/paragraphs) is stable enough for us to adopt without committing substantial energy.
