### ISSUE TITLE
Toxic Exposure 1.0: Validation issues - Remove duplicate service periods spike

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#87717]
## Issue Description
Validation errors were found when using the Lighthouse submit From526 validation endpoint.
This particular error happened when there were duplicate Service Periods.

We want to test if we can have the submission succeed if the data is sent to the generatePDF endpoint.

---
## Tasks
- [ ] Make a data object that is similar to the prod data and send the data object to the generatePDF endpoint

## Acceptance Criteria

- [ ] Document of result sending to minimum validation generatePDF endpoint

Out of scope - we may need to do this later
The task here is to remove duplicate service periods found in the service periods array.
- [ ] backend: check for duplicate service periods
_note: i'm pretty sure we can call `.uniq` on the service periods array and be done here?_
in lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:528 `#sorted_service_periods`
```
 def sorted_service_periods(service_information_source)
        service_information_source['servicePeriods'].sort_by do |service_period|
          service_period['activeDutyEndDate']
        end.reverse
      end
```
- [ ] backend: unit test duplicate serice period removal 
- [ ] frontend: _question: this particular record in question has the duplicate service period in its saved claim, meaning that the frontend is allowing for duplicates. should we not?_
- [ ] Run `valid_form_content?` on this Form526Submission record id  found in the error document - there should be no errors

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
@mengA6 can you advise on the error message language for this?
@christinec-fftc to look into how the serviceHistory component behaves. Nor sure if this is a Platform component or not. TBD.

**Comment by mengA6** [comment]
Okay, if it turns out we need to have the Veteran correct something, let me know and I can pull this in as a design task

**Comment by mengA6** [comment]
(discussion from huddle 16th minute)

Not sure if it's coming from prefill or the Veteran entering it. Somehow they get the same exact branch and beginning / end dates. Either way we want to avoid getting into the state. Currently it blocks submission. 

Backend discovery ticket to determine how EVSS handles this and if Lighthouse should handle it gracefully

Jared to decide / communicate if we're doing the front end validation before launch

Mike to create design ticket, Christine to do front end discovery on front end validation.

**Comment by mengA6** [comment]
I created [Design validation to prevent duplicate service periods #88216](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/88216) to capture the design work needed.

**Comment by pacerwow** [comment]
Related FE ticket:
https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/88275

**Comment by pacerwow** [comment]
EVSS allows this, we should ask LH if they should remove this validation.

**Comment by sethdarragile6** [comment]
Confirmed that calling the `generatePDF` endpoint (with minimum validation) does indeed work with duplicate service periods:
<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c6201c30841d7ecd16c75b364bfae8232d528ac/image.png" alt="image.png" /><img width="854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5d2a3898566db038fe8de2152eb43ff5d94432d/image.png" alt="image.png" />

This means that, even if the submit itself fails validation, a workaround exists to manually generate the PDF and upload it to VBMS.

**Comment by sethdarragile6** [comment]
Unexpected side quest performed under this ticket: a bug was found where the Obligation Term of Service dates were not getting populated on the PDF. [This fix](https://github.com/department-of-veterans-affairs/vets-api/pull/17586) was merged to master, and tested successfully in Staging

<img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1R5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--956725181b7d55b62c3126a3d673a18ab7dc0b67/Screenshot%202024-07-18%20145337.png" alt="Screenshot 2024-07-18 145337.png" />

<img width="802" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0x5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77665e9a07786cdc1740fc42ac28162ecc233cfd/Screenshot%202024-07-18%20145119.png" alt="Screenshot 2024-07-18 145119.png" />

<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzd4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2e0124ff43fe630d50bcae31099ec6032105f72/image.png" alt="image.png" />

**Comment by sethdarragile6** [comment]
☝️in the above example, I entered service periods duplicated on everything but BOS. In this case, Army and Air Force Reserves. As you can see below, it captures the Air Force Reserve period and presumably captures the Army one in 20D but doesn't seem to capture that BOS here or on the overflow pages. This is largely a limitation of the form itself, I think.

<img width="759" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1h5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7aff6be80b75206fe876127896c11586764f6609/Screenshot%202024-07-18%20145010.png" alt="Screenshot 2024-07-18 145010.png" />

However when I did a local test of the generatePDF with a similar scenario (except with Army and Air National Guard), the results seem more confusing. "Army" is captured in 19A+19B, and presumably "Air National Guard" is captured in 20D, but only the "National Guard" part is captured in 21B (i.e. where's the Air? 😂) Again, a limitation of the form, and nothing on the overflow page to indicate the "Air" part.

<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzN5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3555c849be75b265987e300ba60289eb1167d9b/image.png" alt="image.png" />
