### ISSUE TITLE
Toxic Exposure 1.0: Validation issues - Mailing Address1 formatting - space at the end

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#87716]
## Issue Description
Validation errors were found when using the Lighthouse submit From526 validation endpoint.
This particular error happened when there was a space ` ` at the ending of the attribute `mailingAddressLine1`.

The task here is to "trim", or remove trailing and leading spaces, from the address strings.

---
## Tasks
- [ ] `.trim` the `mailingAddress1` field before sending to Lighthouse
- [ ] _question: `.trim` the other address fields? 🤔_
in lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb:495
```
veteran_identification.mailing_address.address_line_1 = veteran['currentMailingAddress']['addressLine1']
veteran_identification.mailing_address.address_line_2 = veteran['currentMailingAddress']['addressLine2']
veteran_identification.mailing_address.address_line_3 = veteran['currentMailingAddress']['addressLine3']
```
_remember that these can be `nil`_

## Acceptance Criteria
- [ ] Run `valid_form_content?` on this Form526Submission record id  found in the error document - there should be no errors
- [ ] Requires fix to be in production in order to test
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Fixed!
<img width="1105" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC9mQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--413a2914248a23796e60f642c6e1d454b5dd86b0/image.png" alt="image.png" />

**Comment by sethdarragile6** [comment]
Fixed
<img width="1105" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c7168a41a3cb21486d6c6c4688490c8726cc3de/image.png" alt="image.png" />
