### ISSUE TITLE
[CST] [ENG] Remove the feature flag cst_use_claim_details_v2 from vets-api

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#87712]
## Background Context
Remove the feature flag `cst_use_claim_details_v2` from vets-api

## Engineering 
- remove the feature flag from features.yml

## Tasks
- [x] remove the feature flag  `cst_use_claim_details_v2` from features.yml

## Definition of Done
- [x] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] remove the feature flag  `cst_use_claim_details_v2` from features.yml

**Comment by pmclaren19** [comment]
Closed since this is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/87707

**Comment by pmclaren19** [comment]
@jacobworrell this is not a duplicate. This ticket is needed for removing the feature flag cst_use_claim_details_v2 from vets-api where as https://github.com/department-of-veterans-affairs/va.gov-team/issues/87707 is for removing it from vets-website.

**Comment by pmclaren19** [comment]
Reviewed during eng refinement.
