### ISSUE TITLE
[FE] - Add e2e test for completing check-in then going back to appointments + other unified bugs

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#87721]
## Description
Write a new e2e test that completes check-in, clicks the link to go back to appointments. The test should expect the task card of the checked-into appointment to be removed.

## Tasks
- [x] Create e2e tests

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
moving to closed since there is no further validation to be done.
