### ISSUE TITLE
Review, Resolve Link Bugs Found in L4+ Audit

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8773]
**Tasks**
- [ ] Review, write feedback on the found link bugs in the L4+ [audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/page-nav/Level%204%2B%20Pages%20Audit.xlsx) after the proposal is reviewed/finalized by Danielle & Mikki
- [ ] Resolve the link bugs
- [ ] Generate list of the updates made in the resolution of the link bugs

**Acceptance Criteria**
- [ ] List of link resolutions included in this ticket for validation
- [ ] Link resolutions implemented, able to be validated

**Comment by stephorkandatx** [comment]
Actionable after L4+ proposal solidified

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop @stephorkandatx. Here's Mikki's and my feedback on the Life Insurance bugs. Will continuing adding feedback on bugs in this issue as we go through them. Thanks so much for identifying these as part of your audit work, Selina!

[Life insurance bugs 5.7.20](https://app.zenhub.com/files/133843125/5d05d90b-265b-45f6-8d09-6777179a6af0/download)

**Comment by mnorthuis** [comment]
This audit and work is outdated.  Resources and support effort as well as other initiatives will review content depth as needed. Closing issue.
