### ISSUE TITLE
Update convo guide and CodePen prototype based on part 1 completion

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87735]
## Tasks

- [x] Update convo guide 
- [x] And CodePen prototype based on research part 1 completion
   - [x] In each of the provider list pages, make sure that the order of providers have the proper order of miles distance. If you have two providers with the same miles distance, the shorter amount of minutes should come first. Make sure these are consistent across each provider list page. 
   - [ ] Add preferred provider into the provider list on the first provider list page (not filtered result provider pages). 
   - [x] Ensure number of pending appts is consistent. I used 4 and 4 on the last two pages of the prototype.  
   - [x] Remove VA crest from text message. I.e., one participant said they liked that because there's a lot of spam. Well, the reality is, that logo is user controlled. So, change to basic avatar. [Figma link for reference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1538-33305&t=M1qnhvB8Hr7jLzpk-4).

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/87735?planning-poker) with Zenhub @cgednalske

**Comment by benbrasso-agile6** [comment]
@cgednalske FYI, added tasks above for changes I made in Figma based on P1 session

**Comment by cgednalske** [comment]
>  Add preferred provider into the provider list on the first provider list page (not filtered result provider pages).

Where did this come from? The design calls for the preferred provider remaining there (and we never discussed otherwise afaik).

> Remove VA crest from text message. I.e., one participant said they liked that because there's a lot of spam. Well, the reality is, that logo is user controlled. So, change to basic avatar. [Figma link for reference](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=1538-33305&t=M1qnhvB8Hr7jLzpk-4).

Didn't have this one to begin with. 👍 Some of these nuances are just different for the CodePen version.

**Comment by cgednalske** [comment]
Ah, I see. Can we discuss that first? Would be helpful to understand if that's the expected behavior because we knowingly didn't include it previously. Wondering if we've heard this in research or if we have more information around it.

**Comment by benbrasso-agile6** [comment]
That's fine too. Feel free to close. 

Yes, I heard a comment about it. I didn't realize we decided to not include them on purpose. But, that's cool.
