### ISSUE TITLE
[DevOps] Centralize System Tests JSON schema for validation.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#87739]
## Description
Make it so we can validate our mock against it, etc.

## Tasks
- [x] [DevOps] Move System Tests JSON schema into separate file.
- [x] [DevOps] Install a JSON Schema validator in System Tests.
- [x] [DevOps] Add a test to ensure the mock configuration validates.

## Acceptance Criteria
- [x] JSON schema for System Tests AppConfig is validated in system tests.
