### ISSUE TITLE
Update RenderErrorContainer component - ROLL

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#87753]
## Description
We need to update the RenderErrorContainer component

## Tasks
- [ ] Remove the conditional so that `login-error-no-code` is not possible
- [ ] Move `openLoginModal` from the `AuthApp` component to the `RenderErrorContainer` so that we don't have to pass it down as props. (Update unit tests accordingly)
- [ ] Update the `va-alert` to use the latest USWDS components. (Reference the design system)
- [ ] Update all buttons to be `va-button` to create more uniformity (This is optional pending the unit tests getting updated and passing)

**Comment by parkerbees** [comment]
moved to jira, closing
