### ISSUE TITLE
[ANALYTICS]  Parse data from VISN-19 Legacy Data Dump [BA}

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#8775]
## User Story or Problem Statement
As a Business Analyst, I need to know the specific details regarding the Health Services Provided and Content requirements, so I can document and create the Health Services listing correctly.

## Goal
_Parse data from Legacy website data by VISN-19 system and medical center to be used in playbook_

## Objectives or Key Results this is meant to further
- _Reduction in page count_
- _Document pages that can be created in a scalable manner_

## Tasks
_Complete parse of data into Health services, facilities, staff profiles for the following sites:_
- [ ] Eastern Oklahoma VA Health Care System (Jack C. Montgomery VAMC)
- [ ] Fort Harrison VA Medical Center
- [ ] Oklahoma City VA Health Care System
- [ ] VA Eastern Colorado Health Care System(ECHCS)
- [ ] VA Salt Lake City Health Care System
- [ ] Cheyenne VA Medical
- [ ] Miles City VA Clinic and Community Living Center
- [ ] Sheridan VA Medical Center
- [ ] VA Western Colorado Health Care System

## Acceptance Criteria
Data is parsed into sections for each of the following VISN-19 sites.
* Eastern Oklahoma VA Health Care System (Jack C. Montgomery VAMC)
* Fort Harrison VA Medical Center
* Oklahoma City VA Health Care System
* VA Eastern Colorado Health Care System(ECHCS)
* VA Salt Lake City Health Care System
* Cheyenne VA Medical
* Miles City VA Clinic and Community Living Center
* Sheridan VA Medical Center
* VA Western Colorado Health Care System
