### ISSUE TITLE
CSS usage verification

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#87759]
## Description
We need to verify if certain Sass/SCSS (CSS) is still being used in the `auth` application and if its not remove it.

## Tasks
- [x] Verify that `.overlay` and `#main .usa-alert` aren't used in the `auth` application anywhere.
    - [x] (If it IS NOT being used) Remove the `s(a|c)ss` file
    - [ ] (If it IS being used) document how its being used and see if it can be replaced by the VA design system utilities (Reference design system)
