### ISSUE TITLE
Confirm EbenefitsLinks component usage

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#87771]
## Description
We do not know if the `EbenefitsLink` component is still being used by teams even though there are references to it in code. So we should probably speak with those teams or ask CAIA if those references should still be there.

## Tasks
- [ ] Contact CAIA first to verify if links should still be going to eBenefits website.
    - [ ] (If links need to be removed) Work with the individual teams anywhere the `EbenefitsLink` component exists
    - [ ] (If links do not need to be removed) Create a Markdown file in our Identity Github folder that CAIA/teams made that determination.

**Comment by parkerbees** [comment]
Moved to Jira for Sprint 3. Closing.
