### ISSUE TITLE
Design: Capture Fields Necessary to Automate Pension Eligibility Determinations in the 686c-674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8777]
# Add Mandated Pension Questions to 686c  
Implement after launch, but Design can start thinking about it sooner  
## Description  
Pension LOB has mandated updates to BGS/ RBPS to enable simple processing of Pension applications via dependency claims. This presents several challenges, since the 686c does not ask questions about income or pension eligibility. 

This will have a few different parts, across domains that are all related. (See mini-epic for this: #7759)

## Considerations
- Helper text for context will be extremely important, especially given the fact these are financial related questions

## Outcomes
- When adding dependent, ask an additional (optional) question: **"Did this dependent have income in the last 365 days?"**
_Could be slipped in as a_ `Yes` / `No` _in that section?_
- Ask a global (optional) question: **"Did the household have a total income of less than $XXX in the last tax year?"**
_Needs more thought...Whole separate page? Include Veterans Info capture screen?_

## Tasks
- [x] Design UX for these questions. Are they inline with existing questions or part of a new "Pension" section? Is a gate needed that only shows these questions to eligible users?
- [x] Get final content for the questions and helper text
- [x] Determine which information collection can be leveraged for these questions and add it to the beginning of the application (with the 686c & 674 information collections)

## Acceptance Criteria
- [x] A mockup has been created, or an existing mockup has been updated and noted in the [686 Mockup Changelog](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)

**Comment by sporeboy** [comment]
Here is what I have at the moment...

For the individual dependent income question:
- Added yes/no radio button to the child detail screen
- Added yes/no radio button to the separated spouse screen
- This is not required
- Explanatory copy may be added later
- conditional text box can be added to enter number if "yes"

For the household income question: 
- Added new "chapter" to end of add-child and add-spouse workflows
- Has some explanatory copy regarding pension vs. disability
- Text and/or tell-me-more accordion should be revised when we get clarification from stakeholders
- This is not required
- Seems the threshold income figure may be dynamic

Looked here for the formula to determine houhold income limits: https://www.va.gov/pension/veterans-pension-rates/

**Comment by sporeboy** [comment]
Child/dependent income question here: https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/7177f4d5-995e-4906-ad80-1d7fe4e9e08e/Apply-Dependents-Add-Child-2

Spouse/dependent income question here: https://xd.adobe.com/view/e185627d-0f83-4762-747d-d646b4557713-97b4/screen/257a2892-f707-402b-a41f-3f589b12e724/Apply-Dependents-Separated-Spouse-Address-1

Household income question here: https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/1862a04d-d048-4c75-834f-eb6e7255071e/Household-Income-1

And here: https://xd.adobe.com/view/e185627d-0f83-4762-747d-d646b4557713-97b4/screen/184545c3-684a-4202-adb1-02294624e4a3/Household-Income-1

**Comment by sporeboy** [comment]
The three "add dependent" workflows are:
- Add child
- Add spouse
- Add student

Confirmation needed as to whether the 674 workflow will require this info as well.

**Comment by sporeboy** [comment]
Household income question changed to net worth question:

Child workflow: https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/72babaf1-85d1-44dd-a2b0-2ffcaa82c7f2/Household-NetWorth-1/

Spouse workflow: https://xd.adobe.com/view/e185627d-0f83-4762-747d-d646b4557713-97b4/screen/bef74b7a-6b4b-404a-a303-459bb3d29a86/Household-NetWorth-1

**Comment by sporeboy** [comment]
Did not add additional financial questions to 674... The form does include an accounting of the students income.

So, should we add the net worth question module/chapter to the 674 workflow? Or should we assume the NW question was answered when the child was added originally?  If the student is being added now but has never before been claimed, the user must go through the add child workflow. In that case, the net worth question *will* appear.
