### ISSUE TITLE
NOD | Update Confirmation Page Content

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#87782]
## Value Statement

**_As a_** Veteran that has just submitted an appeal on VA.gov
**_I want to_** have the most realistic and up-to-date information about the Board Appeal process
**_So that_** I can understand what to expect next

---

## Background Context
The Board came back with edits on the confirmation page to provide extra context on what the process is like for docketing. 

## Outcome, Success Measure, KPI(S), and Tracking Link

- CTA button click for NEW download event | Baseline: N/A | Target: TBD | Link to Data Source: TBD

## Acceptance Criteria
- [ ] User can access confirmation page after submission
- [ ] User sees updated information in the alert, what to expect next, and new PDF section.

## Designs and Build Notes

- [FIGMA](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1543-13764&m=dev)

### Enablement team (if needed)
@jstrothman 

## Out of scope
- Confirmation email
- .txt download
- Supplemental claim and HLR confirmation pages
- Other information on the confirmation page

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] LH endpoint is available
- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Changed have been merged and will be available for review in staging soon

**Comment by eileen-coforma** [comment]
Looks good to me 👍
