### ISSUE TITLE
[POST LAUNCH] Backend: Capture Fields Necessary to Automate Pension Eligibility Determinations in the 686c-674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8780]
# Add Mandated Pension Questions to 686c
Implement after launch, but start thinking about it soon
## Description 
Pension LOB has mandated updates to BGS/ RBPS to enable simple processing of Pension applications via dependency claims. This presents several challenges, since the 686c does not ask questions about income or pension eligibility. 

This will have a few different parts, across domains that are all related. (See mini-epic for this: #7759)

## Considerations
- Helper text for context will be important.
- BE data gets broken up and sent to a few different places

## Outcomes
- When adding dependent, ask an additional (optional) question "Did this dependent have income in the last 365 days?"
_Could be slipped in as a `Yes` / `No` in that section_
- Ask a global (optional) question "Did the household have a total income of less than $XXX in the last tax year?"
_Needs more thought...Whole separate page? Include Veterans Info capture screen?_

## Tasks
~~- [ ] Connect with Linda (BGS) and Christine over email and confirm where these values would go or what service they should be pointed to~~
**If Able, Next Steps:**
- [x] Add fields to form submission (`VnpPtcpntRlnshpWebService::depHasIncomeInd` and `VnpBnftClaimWebService::netWorthOverLimitInd`)
- [x] Field data is passed in with the regular payload

## Acceptance Criteria
- [x] A path forward has been established
- [x] If applicable, a PR has been requested for merging 

### Future tickets
- PR
- Lighthouse gem?
- Writing tests

**Comment by kathleencrawford** [comment]
Questions for add spouse workflow:
- "Did your spouse have income in the last 365 days?"
- "Is your net worth less than $129,094?"

Data in payload:
```
"dependents_application": {
    "household_income": true,
    "does_live_with_spouse": {
      "spouse_does_live_with_veteran": true,
      "spouse_income": true
    },
```

**Comment by kathleencrawford** [comment]
Questions for add child workflow:
- "Did this child have income in the last 365 days?"
- "Is your net worth less than $129,094?"

Data in payload:
```
"dependents_application": {
    "household_income": false,
    "children_to_add": [
      {
        "does_child_live_with_you": true,
        "previously_married": "No",
        "child_income": false,
      }
    ],
```

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5318
