### ISSUE TITLE
Spike: Identify Topics for GA4 Training Series

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#87813]
### Description
The goal for this ticket is to identify the specific topics for our GA4 Training Series. These training topics should be specific, something we can share and communicate in advance, and build upon each other if they can.

**Note:** This is separate from any 'How To' trainings we will be performing, or our traditional _Office Hours_.

---

### Tasks

- Identify topics for GA4 Training series
- Confirm with team
- List out topics below:

### GA4 Training Topics

- [x] How to locate content/pages in GA4 -- 7/12
- [x] How to locate events in GA4 using Explore reports -- 7/19
- [ ] TBD - 7/26

---

### Acceptance Criteria:

- [ ]  Training topics should be identified in this ticket.

**Comment by jestutt** [comment]
Some suggested guidelines for the trainings: 

- the live trainings are separate from the resources/how-to documentation that will live on the platform site, though they will likely support each other
- trainings should probably be a mix of basic "new to GA" information mixed with a healthy dose of this is how you do UA tasks in GA4
- while [I think] the data housed in GA is technically public information, I don't know that we want to record and post all but the most high-level trainings to the more public channels -- this is where getting a VA.gov SharePoint site could be important. Note: editing videos to blur content can be time consuming
- I'd like to keep any "how-to analyze" topics for team specific trainings or for the resource documentation
- try to fit the 30 min time slot = 20-25 min demonstration with a 5-10 min left for questions

We already have 2 topics scheduled: 

- Fri, 12 July - How to find your content/pages/URLs in GA4 with Explore reports
- Fri, 19 July - How to find your events in GA4 with Explore reports

Other topics:

- Creating a simple Funnel report in GA4 with Explore reports
- Walk-thru and filtering the GUI or GA4 default reports -- not sure on this one but could likely span 2-3 sessions since a good chunk is likely to be the dimension and metric explanations
- Segments in GA4
- Path exploration Explore reports -- I feel like we may need to do something on this one even if we're only showcasing the limitations we've run into
- Where did your traffic come from -- I think this is probably 2-3 sessions that combined create the full picture of how users are finding content -- landing page attribution + page referrer + events 
- Search reporting in GA4

@johnny-jesensky-adhoc Can you add to the list?

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt  -- Thank you! This is a great list -- I put some of your topics into the description of the ticket, and also moved that list to [this Confluence page](https://vfs.atlassian.net/wiki/spaces/AT/pages/3290660872/GA4+Training), so we won't have to dig for it after we close out this ticket.

Think this is good starting place, and something we can evolve as more feedback from teams rolls in. Think this meets the DoD for this ticket, so going to mark this as _Done_.
