### ISSUE TITLE
Appoint a Rep Digital Submit - User Test - Content Audit

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#87814]
## Issue Description
User testing of Appoint a Representative Digital Submission flow.

## Tasks
- [ ] Review content in experience based on user feedback.
- [ ] Review with the team and CAIA.
- [ ] Send content to Michael to update designs for future testing.

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
https://docs.google.com/document/d/11HRzNaHKPnY51bkroirCcoNeIdYbbGxo6XC9PAK1Kyw/edit?usp=sharing

**Comment by oddball-lindsay** [comment]
Waiting on A, expecting their feedback next week.

**Comment by oddball-lindsay** [comment]
Feedback is in!  Working through it with some back and forth, before updating designs.

**Comment by jfinnerty13** [comment]
Responded to all feedback with A - waiting on response to find time to meet to discuss changes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/88298
