### ISSUE TITLE
Consider design change of expiration to only show up at x amount of day

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87822]
## Tasks

- [ ] What did the research tell us? 
- [ ] Talk to engineers about feasibility for MVP
- [ ] Consider design change of expiration to only show up at x amount of day
- [ ] Create designs and annotate functionality
