### ISSUE TITLE
Hours of operation: data owners

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#8782]
## User Story or Problem Statement
How might we enforce consistency in the display of hours of operation?

## Current situation
Facility hours of operation are consumed by API and displayed within Facility Locator as they have been defined by the data owners. As a result, facilities may use different words or style formats to convey the same meaning. 

Areas of inconsistency with content recommendations are documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/data/hours-of-operation.md

## Goal
Consistent plain language reporting for hours of operation

---
## Tasks
- [ ] Determine best method for ensuring consistency, accuracy and plain language use at data owner level

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
