### ISSUE TITLE
Content Edits for 87802

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#87829]
## Issue Description

- Content edits according to support ticket [87802](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87802)

- Under the header **Step 2: Gain Access to Datadog** of [Get Access to Datadog page](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog) the **Steps** section needs to be updated:
---

> 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/bc2a1ec4-427d-4aa3-a720-3e851c4b822d)

---

## Complete instructions may be found in this Knowledge Article _(Requires PIV login):_ 

- [Self-Service - Datadog: Datadog Access (va.gov)](https://yourit.va.gov/va?id=kb_article_view_yourit&sys_id=3907c5e697ad8e102dcbfcc0f053af13&table=kb_knowledge)

---

## Tasks
- [ ] Review support ticket [87802](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87802)
- [ ] Review new instructions in Knowledge Article above
- [ ] Update website to include complete instructions   
- [ ] Prepare page for deployment

## Acceptance Criteria
- [ ] **Get Access to Datadog** page will be updated to include the changes
---
---
## Screenshots:
![Screenshot 2024-07-10 at 8 57 48 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/ec35e938-2ffa-416e-9296-5f72608583eb)
![Screenshot 2024-07-10 at 9 00 05 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/e5fa02c7-0e4b-4113-b9d9-91981731fa16)
![Screenshot 2024-07-10 at 9 00 31 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/feae75a9-1c3c-4a66-808c-66c618764502)
![Screenshot 2024-07-10 at 9 00 55 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/c42b3f3b-b1c3-4f99-b73e-8b3c65dc0a44)
![Screenshot 2024-07-10 at 9 01 11 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/7b5594cb-d268-4e70-b5fa-83af9ed5521e)

**Comment by BSmolensky** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/87829?planning-poker) with Zenhub @laucon @CherylEvans @taylojill

**Comment by jknipes** [comment]
Work completed and commented in [80263](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80263)
