### ISSUE TITLE
[POST 686 LAUNCH] Product: Capture Fields Necessary to Automate Pension Eligibility Determinations in the 686c-674

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8783]
# Add Mandated Pension Questions to 686c
Implement after launch, but start thinking about it soon
## Description 
Pension LOB has mandated updates to BGS/ RBPS to enable simple processing of Pension applications via dependency claims. This presents several challenges, since the 686c does not ask questions about income or pension eligibility. 

This will have a few different parts, across domains that are all related.

## Considerations
- Helper text for context will be important.

## Outcomes
- When adding dependent, ask an additional (optional) question "Did this dependent have income in the last 365 days?"
_Could be slipped in as a `Yes` / `No` in that section_
- Ask a global (optional) question "Did the household have a total income ~~of less~~ **greater** than $XXX in the last tax year?"
_Needs more thought...Whole separate page? Include Veterans Info capture screen?_

## Tasks
- [x] Update call center docs
- [x] Consider technical and usability testing

## Acceptance Criteria
- [x] Contact Center docs are updated
- [x] Facilitated usability testing, or consider folding in to UAT
- [x] [Mini-epic items](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7759) are addressed
