### ISSUE TITLE
URGENT: Implement Vets-API in clusters for EKS testing

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87848]
**Note:** This ticket needs to be completed within Sprint 5 (7/4/2024-7/17/2024) 

## User Story
As the managers of Vets-API, 
We need to implement a functioning Vets-API in the new clusters in Sprint 5, 
So that testing can begin in the new clusters even as testing in the old clusters is being done for baseline purposes. 

The [new cluster can be found here](https://argo-vetstest-next-eks.vfs.va.gov/login?return_url=https%3A%2F%2Fargo-vetstest-next-eks.vfs.va.gov%2Fapplications)

## Issue Description
The new clusters that have been created for the EKS testing currently lack a functioning Vets-API. We need to implement Vets-API into the new clusters so that the new clusters can be tested. The current ("old") clusters will be tested in order to get a baseline for comparison against the results from the new clusters. 

See this [EKS Testing Meetings document](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2925690894/EKS+Testing+Meetings) for further context. 

## Tasks
- [x] Identify "new" EKS clusters (talk to Peter or Isaac)
- [x] Implement a functioning Vets-API in the new EKS clusters
- [x] Test that the Vets-API is working from the new EKS clusters
- [x] Document process after repairing any testing errors
- [ ] Tell @lindluni or @jennb33 when this is done

## Success Metrics
That the new EKS clusters have a functioning Vets-API and they can be tested. 

## Acceptance Criteria
- [x] The testing on the new EKS clusters can begin
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
After the nodes rolled, it produced a cert error. This is a high priority to mediate.

**Comment by jennb33** [comment]
7/11 update: per @LindseySaari we have a section of values in the old cluster and the new cluster. Lindsey got all the secrets, wrote a script to compare the value differences. Having an error now connecting to Redis. DevOps to assist, Lindsey will keep working on this.

**Comment by LindseySaari** [comment]
I was able to get the Vets Next Vets API application healthy again! I got the secrets in a working state and identified the correct security group in order for Vets Next to connect to Redis. Kshitiz got the security group applied and everything is healthy!

Additionally, Rebecca and I [updated the documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2452193284/Vets+API+on+EKS) for dev secrets detailing the necessary steps to keep the secret sections up to date for the new (vets next) and current live dev deployments
