### ISSUE TITLE
Veteran Contact Information - Phone, Email

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87859]
## Issue Description

The Veteran Contact Information - Phone, Email page will be available to:
1. Authenticated and unauthenticated Veteran users
2. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is a **Veteran**, the h2 should reference "Chapter 2". If the user is a **non-Veteran** the h2 should reference "Chapter 3".
   2. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.
   2. If the user is a **Veteran**, the word "Veteran"/"Veteran's" should be replaced with "Your"
   3. Input fields designs
     1. Auth Veterans, prefill fields if information exists in their profile. The h3 should read "Your phone number and email address".
     2. Unauth Veterans. The h3 should read "Your phone number and email address".
     3. non-Veterans (auth and unauth). The h3 should read "Veteran's phone number and email address".

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 8: Telephone Number (xxx-xxx-xxxx)
   - Field 9: Email Address
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 8: Telephone Number (xxx-xxx-xxxx)
   - Field 9: Email Address

**URL**: `/veteran-contact-phone-email`

**Previous path**: `/veteran-personal-information` 

**Next paths**: `/veteran-contact-mailing`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Unauth" Designs (Input fields)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145538&t=tGHtwSW79Yu6xXvL-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=455%3A148692&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145538&t=tGHtwSW79Yu6xXvL-4)

<details><summary>Screenshots</summary>

<img width="261" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN25CQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa5dba9f984a841ea47a832e83549dcaa9a1449c/image.png" alt="image.png" />

<img width="855" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1293de364e1983e1ae1b57955dfc7086c08642d/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Veteran Contact Information - Phone, Email page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Veteran Contact Information - Phone, Email page has been implemented, with the specs outlined above.

**Comment by mtri** [comment]
**For non-Veteran, it looks like this confirmation screen is still displaying:**

<img width="662" alt="Screenshot 2024-08-28 at 10 14 22 AM" src="https://github.com/user-attachments/assets/73d92464-dd78-4b29-9e29-19a7732684dd">

**The page itself looks good other than:**
**- The progress stepper chapter H2 should change based on non-Veteran vs Veteran**
Veteran: "Your information"
Non-veteran: "Veteran's information"

**Comment by cosu419** [comment]
Ready for review @mtri

**Comment by mtri** [comment]
Looks good!
