### ISSUE TITLE
Veteran Contact Information (Prefill Pattern)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87858]
## Issue Description

The Veteran Personal Information page will be available to:
1. Authenticated Veterans who have phone number, email and mailing address on file ONLY
2. 21-22 and 21-22a forms

Content is dynamic based on:
   1.  If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 7: Mailing Address (number and street, apt/unit number, city, state, country code, zip code)
   - Field 8: Telephone Number (xxx-xxx-xxxx)
   - Field 9: Email Address
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 7: Mailing Address (number and street, apt/unit number, city, state, country code, zip code)
   - Field 8: Telephone Number (xxx-xxx-xxxx)
   - Field 9: Email Address

**URL**: `/veteran-contact`

**Previous path**: `/veteran-personal-information` 

**Next paths**: 
1. `/authorize-medical` (21-22 users)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Auth" Designs (Prefill)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-134676&t=Px0Ccnsof1SBP3NU-0&scaling=scale-down&content-scaling=fixed&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-134676&t=Px0Ccnsof1SBP3NU-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153448&t=Px0Ccnsof1SBP3NU-4)

<details><summary>Screenshots</summary>

<img width="214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3QwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d0a2bed6437b5aba33ecaeec5394a1c81a2a184/image.png" alt="image.png" />

<img width="903" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3gwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47055f3a0f7a965bb5b404b63c817c38f646c7d7/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Veteran Contact Information page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Veteran Contact Information page has been implemented, with the specs outlined above.

**Comment by oddball-lindsay** [comment]
Prefill patterns have changed, this ticket is no longer relevant
