### ISSUE TITLE
Veteran Contact Information - Mailing Address

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87860]
## Issue Description

The Veteran Contact Information - Mailing Address page will be available to:
1. Authenticated unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

Content is dynamic based on:
   1. If the user is a **Veteran**, the h2 should reference "Chapter 2". If the user is a **non-Veteran** the h2 should reference "Chapter 3".
   2. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.
   2. If the user is a **Veteran**, the word "Veteran"/"Veteran's" should be replaced with "Your" and the checkbox should read "I live outside..."
   3. Input fields designs
     1. Auth Veterans, prefill fields if information exists in their profile. The h3 should read "Your mailing address".
     2. Unauth Veterans. The h3 should read "Your mailing address".
     3. non-Veterans (auth and unauth). The h3 should read "Veteran's mailing address".

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 7: Mailing Address (number and street, apt/unit number, city, state, country code, zip code)
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
   - Field 7: Mailing Address (number and street, apt/unit number, city, state, country code, zip code)

**URL**: `/veteran-contact-mailing`

**Previous path**: `/Veteran-contact-phone-email` 

**Next paths**: 
1. `veteran-identification` (non-Veterans, Veterans who DO NOT have an SSN on file)
2. `/veteran-service` (21-22a + Veterans who have SSN, but DO NOT have a branch of service on file)
3. `/authorize-medical` (21-22 + auth Veterans who have a SSN on file, 21-22a + auth Veterans who have SSN and branch of service on file)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Unauth" Designs (Input fields)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-145489&t=tGHtwSW79Yu6xXvL-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=455%3A148692&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1185-102858&t=tGHtwSW79Yu6xXvL-4)

<details><summary>Screenshots</summary>

<img width="193" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4064c2242c281d1057c985a52dde907744e6e438/image.png" alt="image.png" />

<img width="671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVRCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90f5a029a92b5243345fcad5ca81ae69c5f0a51b/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Veteran Contact Information - Mailing Address page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Veteran Contact Information - Mailing Address page has been implemented, with the specs outlined above.

**Comment by mtri** [comment]
> - The state dropdown is State/Province/Region in design. According to the content SOT, this should be an open field instead of a dropdown. I'll update Figma. It would align with the example from VADS

Swinging back around on this, [the example cited in VADS](https://staging.va.gov/mock-form-patterns/mailing-address) functions exactly like you have it currently. Use the out of the box country + state/province/region picker. Whether it is an open field or a select dropdown changes depending on the country selected.

This UI swapping for the state/province/region box is not well-documented in VADS hence why I thought it was meant to be an open field. Sorry for any confusion. 

I'll submit a ticket to the design system team for this to be documented better.

**Comment by cosu419** [comment]
Ready for review @mtri 

> The "This address is on a United States military base outside of the U.S." default seems like it would work if changing this text is a major headache.

I don't know that it's a major headache, but formData doesn't seem to be immediately accessible to this checkbox via the forms library. Will see what I find.

**Comment by mtri** [comment]
Something very funky is happening with the "Your mailing address" form when entering this page as the Veteran.
- When selecting and unselecting the checkbox, the country is stuck as United States even after unselecting.
- State select box is showing no options.

When accessing this page as a non-Veteran, everything seems to work properly.

<img width="643" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTY1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd4ffa481fb6fba92635543be7bb1f2922af7349/Screenshot%202024-09-06%20at%202.48.12%20PM.png" alt="Screenshot 2024-09-06 at 2.48.12 PM.png" />

**Comment by cosu419** [comment]
Weird bug with the shared web component doesn't like the conditional title setting. Workaround in my next PR.

**Comment by cosu419** [comment]
Ready for re-review @mtri

**Comment by mtri** [comment]
- Now the non-Veteran version of the page seems to have the same issues as the Veteran page I described above. Weird bugs with the addresses and the checkbox.
- The Veteran version works fine.
- The page is displaying "Your mailing address" vs. "Veteran’s mailing address"

<img width="1396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1BKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c4d7934053e62e99b4156541dc853deb301c7ff/Screenshot%202024-09-11%20at%2011.22.02%20AM.png" alt="Screenshot 2024-09-11 at 11.22.02 AM.png" />


One other very minor global thing:
- For "Your information" and "Veteran information" in the progress stepper, the "I" should not be capitalized.

**Comment by cosu419** [comment]
@mtri - fixing the progress stepper in another branch, but let me know if you're still getting issues with the checkbox - couldn't replicate on my end.

**Comment by mtri** [comment]
Looks like the address input is functioning as expected now, thanks! Page looks good!

There's a couple of global edits I'm not sure where to capture. Let me know if I should put these on a different open ticket instead of here if you'd like.

- The h1 "Fill out your form to appoint a VA accredited representative or VSO" should match the breadcrumb "Request help from a VA accredited representative or VSO."

- Tell us how you’re connected to the Veteran question is displaying for the Veteran claimant path. This question should only display for non-Veteran claimants

**Comment by cosu419** [comment]
@mtri ready for review

**Comment by mtri** [comment]
Looks good, thanks!
