### ISSUE TITLE
[UX] Create Draft Wireframes for incorporating Upcoming VAOS Appointments into Pre-Check-in & eCheck-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#87871]
## Tasks 
- [x] Talk to Peter/Appointments about upcoming/pending future plans. 
- [x] Create all final wireframes (based on Option 1) that link to upcoming appts (VAOS) w/o statuses or call to actions. ([Use this page in Figma](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1887-14128).)
    - [x] Pre check in: appt list page, success page, vaos page
    - [x] Check in: appt list page, success page, vaos page 
- [x] During wireframing, evaluate if [Option 1](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1353-38167&t=8mYlg6yMQPEdgeiz-4) is still feasible, but also if there's a better solution. If not, stop and discuss and/or explore other design solutions. **This needs to happen early in the sprint if we begin to explore other solutions and go down a rabbit hole. Let's stop and discuss at that point.**
- [ ] Document questions, e.g., does it matter that Veterans don't see statuses and actions on VAOS appts. (This will be used for research study.)
   - [ ] Of the questions, determine if we need to solve for them now. Document the ones we need to solve for now.
   - [x] Evaluate if we need detail pages for VAOS appts. If we do, use annotations and/or wireframes to ensure engineers understand what's expected on the detail pages. 

   
Note: [Exploration work](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1353-38165&t=S8F7Rhk8gHVbbcIV-0) has been completed and should be reviewed. 

To do next sprint: Make time and schedule meeting with engineers to review work (whether half complete or complete) before sprint ends; leaving time for revisions.

For later ticket: Wireframe solution to mitigate missing or different info. E.g., all your appts can't be found, some information might be different on this page because of x, etc.)

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/87871?planning-poker) with Zenhub @benbrasso-agile6 @zach-park

**Comment by loripusey** [comment]
@benbrasso-agile6 please add detail

**Comment by benbrasso-agile6** [comment]
I'll add some detail and then we can poker point it, Zach

**Comment by benbrasso-agile6** [comment]
@cgednalske take a look - https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1889-29416&t=gUp9RQSFcN8Nmu6c-4

**Comment by benbrasso-agile6** [comment]
I think we decided earlier to not do an eng handoff until after midpoint review

**Comment by benbrasso-agile6** [comment]
@zach-park pls make sure to separate the final solution in its own section on the page as part of this ticket

**Comment by zach-park** [comment]
@benbrasso-agile6 @cgednalske , here is the [Figma link for the final solution](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1889-19465&t=2oEHR7D3F9SVYDkh-1). Thank you!

https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1889-19465&t=2oEHR7D3F9SVYDkh-1
