### ISSUE TITLE
[FSR] Bug - Transform and submit endpoint errors

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#87875]
### Issue
Started noticing failures when went live with the [transform and submit feature flag](https://api.va.gov/flipper/features/fsr_5655_server_side_transform). The dev team got together to investigate the root cause. 

### Solution
In short we were not sending back the entirety of the `formData` the new endpoint was expecting. The PR associated with this issue corrects that change

## Tasks
- [x] Identify the root cause of the errors
- [x] Fix any associated issues
- [x] Test and retest to confirm fix 

## Acceptance criteria

- [ ] transform_and_submit endpoint is functioning as expected
- [x] New endpoint is stable from FE perspective ~~and can be activated again on production~~

## Testing
- [ ] Confirm submissions work with new endpoint

Testing procedure:
Run through FSR with new feature flag active and confirm submissions are valid and endpoint is returning successful response. 
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Shifting to validate since initial fix was put in to send the correct data. Will close out after some additional testing locally

**Comment by Dr-Pongo** [comment]
Closing out since FE issue has been addressed
