### ISSUE TITLE
[CST] Update file type drop down list for evidence submission form

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#87899]
## Value Statement
As a Veteran submitting evidence through CST, I want to make sure VSR's can easily identify my submitted evidence so that I can get a fair decision based on all available evidence in support of my claim.

---
## Background Context
The current list of types of documents is missing some of the types lists on VA Form 20-10208 (Document Evidence Submission).
We've heard from SMEs that it's difficult for VSRs when many documents are listed as "other correspondence" -- reducing the number of those will improve findability
Docs mentioned in 10208 but not in CST list:

- Birth Certificate
- Death Certificate
- Financial Information
- Divorce Decree
- Marriage Certificate
- Court papers / documents

It would be good to also have the current list reviewed by one of our OBA partners for any that should be removed or added

Current State: 

![Screenshot 2024-07-29 084637](https://github.com/user-attachments/assets/ba042f35-4cb8-48dd-932a-6de7cea32799)

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- The component `AddFilesForm.jsx` in `vets-website` uses a helper function called DOC_TYPES that lists all the doc type options. We will want to update this list to include the value (this is the doc type EX: L149) and the label.
- Will also need up update `vets-api` in `lighthouse_document.rb ` and `evss_claim_document.rb` since this is what validates what document types can be uploaded

## Out of scope
- Add here

## Open questions
- What are the evidence type labels claim processors use to process claims? 
- What are the values of the doc types that are needed here? (this is the doc type EX: L149)

## Tasks
- [ ] Product finds appropriate L codes and document names, attaches to ticket.
- [ ] Update vets-website helper function with new doc type values and labels
- [ ] Update vets-api  lighthouse_document.rb so that the DOCUMENT_TYPES for the new doc type values and labels
- [ ] Update vets-api evss_claim_document.rb so that the DOCUMENT_TYPES for the new doc type values and labels

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Document list in dropdown is alphabetized
- [ ] Birth Certificate, Death Certificate, Financial Information, Divorce Decree, Marriage Certificate, Court papers / documents are added as drop down values for evidence submission types. 
- [ ] When a veteran submits a document with an accompanying type, that value is sent downstream as part as the file payload to be used by claims processors. 
- [ ] Dropdown is updated for got the Files tab version of the form and evidence details

**Comment by pmclaren19** [comment]
Reviewed and added some updates to tasks, questions and ac during eng refinement.

**Comment by jacobworrell** [comment]
@harshil1793 here are the relevant titles and L codes: 

- Death Certificate - L033
- Birth Certificate - L014
- Divorce Decree - L037
- Marriage Certificate/License - L051
- Court Documents - General - L418

Let's hold off on doing financial documents as they are too numerous and do not have a good generic L code or label.
