### ISSUE TITLE
Launch changes and announce to VFS

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87898]
## User Story
As a Governance team member, I want to launch changes to VADS and announce said changes to VFS teams so that they can be aware of the new accessibility testing process for VADS components.

Assignee: @briandeconinck 
Peer Reviewer:

## Description
We have implemented our new process for ensuring consistent accessibility testing across all VADS components, and have updated the guidance on the VADS website. The purpose of this ticket is to announce changes to VFS teams, and ensure all other work associated with this initiative is complete. 

### Live pages
- N/A

### Drafted pages
- [Draft Slack change announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3474260171/VADS+component+accessibility+testing+announcement)

## Tasks
- [x] Ryan - Incorporate Erin and Keegan's changes to the documentation PR.
- [x] Ryan - Remove old a11y checklists from components on the documentation site.
- [x] Write change announcement for Slack following [Platform guidelines ](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2290352129/Slack+Change+Announcement+format)

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Revised process is posted to [design.va.gov/accessibility](https://design.va.gov/about/accessibility/) or some other sensible place.
- [x] VFS teams have been made aware of the changes to VADS

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by rsmithadhoc** [comment]
Per our check-in meeting, I did the following:

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3071 - I updated the docs pages with the edits from Governance.

![Image](https://github.com/user-attachments/assets/28d2511e-5a4b-4932-aa49-4ac867aded5e)
![Image](https://github.com/user-attachments/assets/ed8fa519-9a30-4a69-bd33-b20fdd2372b0)

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3227 - I updated this to remove any old data for accessibility checklists. I was going to look at adding audit data components that have been tested since I have been on the team, but I felt it would be confusing since there would be a lot of exceptions for things we may not have done. Because of that, I think starting fresh with the next component and regularly re-auditing old components is the way to go. For components that have not been audited with the new criteria, I updated the text for the component doc page to say "While this component has been previously tested against older criteria, it has not yet been audited with the updated testing criteria." with a link to the updated testing doc.

**Comment by briandeconinck** [comment]
[Draft Slack change announcement](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3474260171/VADS+component+accessibility+testing+announcement). cc @shiragoodman @caw310 @rsmithadhoc

**Comment by caw310** [comment]
@briandeconinck that looks good. Thanks for drafting it.

**Comment by shiragoodman** [comment]
@briandeconinck I made a few small comments. Sounds like we're good to post either today or tomorrow. 

FYSA @humancompanion-usds

**Comment by briandeconinck** [comment]
Edits made per Shira's comments!

Carol and Ryan, I'm I good to post this afternoon?
