### ISSUE TITLE
Content Edit: 87709

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#87893]
## Issue Description
Per footer ticket [87709](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87709), we need to add details on ICN to the page [Personal Identifiable Information - PII Guidelines](https://depo-platform-documentation.scrollhelp.site/developer-docs/personal-identifiable-information-pii-guidelines)

## Tasks

- [x] Review ticket [87709](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87709)
- [x] Make content updates to the website accordingly
- [ ] Prepare page for deployment

## Acceptance Criteria

- [x] Page is updated with current information
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/87893?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by laucon** [comment]
This is done

**Comment by jknipes** [comment]
Brought into current sprint due to available capacity. Closing ticket as _Done_
