### ISSUE TITLE
New VFS Team Onboarding next steps: VSA Benefits and Memorials

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#879]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [ ] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist

- [ ] Attend general onboarding meeting (#1334)
- [x] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md) (#1337)
- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md) (#1338)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md) (#1339)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md) (#1340)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md) (#1341)
- [x] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub (#1342)
- [x] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/DigitalModernizationStrategy.pdf)
- [x] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/The-new-VA.gov-briefing-2019-07.pdf) documentation
- [ ] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)(#1343)
- [x] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md) (#1344)
  - [x] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [x] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [x] [Confirm that You Can Log In as a Test User](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/internal-tools)
- [ ] Designers: Attend breakout session (#1345)
- [ ] Engineers: Attend breakout session (#1346)
- [x] Full team: Attend the Discovery and Logistics Workshop (#1348)
- [x] Front-end Engineers: Attend deep-dive session (#1350)
- [ ] Back-end Engineers: Attend deep-dive session (#1351)
- [ ] PM and Content Writer(s): Request content intro (#1353)
- [ ] PM, Content Writer(s), and Designer(s): Request IA intro (#1692)
- [x] PM and Front-End Engineers: Request analytics intro (#1355)
- [ ] PM: Request 508 intro (#1356)
- [ ] PM and Engineers: Request load testing, privacy, and security intro (#1357) 
- [ ] PM and Engineers: Request ATO intro (#1358)

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [ ] Assign the issues to individual(s) to complete
- [ ] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [ ] Attach the issues to this Epic

**Comment by rroueche** [comment]
Updated title to differentiate from VSP's epic to actually onboard this team.

**Comment by mnorthuis** [comment]
Updated title to clarify that this is Benefits and Memorials team, not to be confused with eBenefits team. :-)

**Comment by YanaRoy** [comment]
@Mottie Could you please take a look at the items above and complete all applicable items to complete onboarding. Please let me know if you have questions.

**Comment by mnorthuis** [comment]
Updated links to files, links changed during va.gov-team repo work last week.  Please let me know if any links are not working for you.

**Comment by Mottie** [comment]
To do?

- Attend general onboarding meeting (#1334)
- Set up back end - mostly complete, see below.
- Attend breakout session (#1346)
- Attend deep-dive session (#1350)
- Request analytics intro (#1355)
- Request load testing, privacy, and security intro (#1357)
- Request ATO intro (#1358)

Done:

- Everything checked in the first post.
- Set up back end:
  - I have started the PIV process.
  - SOCKS proxy set up
  - Jenkins, Sentry & Grafana verified working
  - SwitchyOmega browser extension installed
- Extras: ZenHub extension installed
