### ISSUE TITLE
Update SR operational guidance for known issues 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87904]
## User Story
As a Governance team member, I want to know what steps I should take if/when a VFS team notifies us of known issues prior to their scheduled Staging Review.

Assignee: @erinrwhite 
Peer Reviewer: @KKitagawa-Bosch 

## Description
As SR, Governance team asks VFS teams to share any known issues. This could be small bugs they haven't yet fixed, or larger issues that they know are a problem, but haven't addressed yet. There has been uncertainty on the Governance team what to do if/when known issues are shared. The purpose of this ticket is to update the How to document findings for SR guidance to specify the steps Governance should take if/when known issues are present.

If/when known issues are present, Governance team should still document the issue in the DraftingTemplate. If the VFS team already has a ticket associated with the issue, the Governance team member should be sure to link the VFS ticket in the Description section (or elsewhere, if appropriate) of the DraftingTemplate. 

## Impacted Artifacts
[How to document findings for SR ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)

## Tasks
- [x] Review the How to document findings for SR guidance
- [x] Determine where it makes sense to include this guidance re: known issues
   - Possibly Reviewer responsibilities during meeting?

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team has a process to follow if/when known issues are communicated at SR

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Added this information to the [FAQ section of the page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review#FAQ) - @KKitagawa-Bosch do you think this is sufficient? If so, ready for review 👍🏻

**Comment by KKitagawa-Bosch** [comment]
Looks great! Good to go @erinrwhite

**Comment by erinrwhite** [comment]
thank you @KKitagawa-Bosch can you check the peer review boxes? I'll go 'head and close.
