### ISSUE TITLE
Modify Design Office Hours sign-up in Calendly

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87905]
## User Story
As a Platform team member, I want to know more details from VFS team members when they sign up for Design Office Hours so that I can be prepared to respond to them at the Office Hours meeting.

As a Platform team member, I want to be able to easily see the responses from VFS teams who sign up for Design Office Hours so that I don't have to rely on someone else sharing the responses in Slack.

Assignee: @allison0034 
Peer Reviewer: @briandeconinck 

## Description
Governance team would like VFS teams to share more information ahead of time when signing up for Design Office Hours. Design Office Hours currently utilizes the Group event type in Calendly which allows many folks to sign up for the same timeslot. The problem that the Group event type is that the responses VFS folks provide when answering our Office Hours sign-up questions are not shared in the Calendly event, meaning a Governance team member must go into Calendly to copy the responses, then share them with the Governance team ahead of time. This is time consuming and puts extra steps on the Governance designed.

By pivoting the Design Office hours to a One on one event type, Governance team members will be able to see the responses within the calendar, eliminating the need for 1 Governance team member to share the responses ahead of time via Slack. This is currently the set up that Collaboration Cycle Office Hours utilizes. Pivoting from a group event type to a one on one event type will also require the Design Office Hours to switch to two 15 minute time slots, opposed to one 30 minute time slot.

In addition, Governance team would also like to refine the questions currently asked at Design Office Hours sign up. Currently, the only question asked at sign up is, "Please share anything that will help prepare for our meeting."

## Impacted Artifacts
[Office hours page](https://depo-platform-documentation.scrollhelp.site/support/office-hours)

## Tasks
- [x] Add question to Calendy asking for Collab Cycle ticket
- [x] Split Calendly event into two 15 min blocks
- [x] Update links to Design Office Hours

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have refined the questions we ask VFS teams when they sign up for Design Office Hours
- [x] We are able to see the responses from the VFS teams in the Design Office Hours calendar event 

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Questions for the team:

- should we announce this change to VFS teams?
- what did we do when we made this change to Collab Cycle Office Hours?

**Comment by allison0034** [comment]
Added tasks and created a clone of current Design Office Hours in Calendly

**Comment by allison0034** [comment]
I have to wait until after Tuesday to change the event because we have someone signed up for this Tuesday aready so Calendly will not let me.

**Comment by shiragoodman** [comment]
@allison0034 I don't think you'll be able to _change_ the event from a group event to a 1:1 event.. I think you have to set up a new one and update all of our links to go to the new event.

**Comment by allison0034** [comment]
@shiragoodman I know, I did. I created a "clone". But since someone is already signed up I have to wait until after Tuesday to switch it.

**Comment by allison0034** [comment]
Received [feedback from team](https://dsva.slack.com/archives/GNF5GSD9N/p1724085298765059) about what to include.

**Comment by allison0034** [comment]
@briandeconinck the page has been updated and is linked under the artifact section.

**Comment by briandeconinck** [comment]
@allison0034 Perfect. Everything looks great to me. I think you're good to close!
