### ISSUE TITLE
Bump Faraday to 2.10.0

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#87903]
## Issue Description
Remove FaradayMiddleware Patch and bump Faraday to 2.10.0

---
## Tasks
- [x] Bump Faraday to 2.10.0 
- [x] Remove anything related to the patch

## Acceptance Criteria
- [x] Faraday 2.10.0 is released to Prod

**Comment by ryan-mcneil** [comment]
https://github.com/restforce/restforce/pull/894
