### ISSUE TITLE
Add Keegan to Governance guidance

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#87907]
## User Story
As a new Governance team member, I want my name to be added to the VFS-facing guidance so that VFS teams know who I am and what my role is.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @allison0034 

## Description
Keegan Kitagawa-Bosch is the new content specialist on the Platform Governance team. Currently, all VFS-facing guidance does not include Keegan's name, where applicable. The purpose of this ticket is to add Keegan's name to the appropriate guidance.

## Impacted Artifacts

- [Touchpoint slides ](https://docs.google.com/presentation/d/1c1U0FMX1Efbr7Rs2RfikLKdbTVWEH4n28aGZoVas4jE/edit#slide=id.g23db8d1d252_0_248)for Design Intent, Midpoint Review and Staging Review
- [DraftingTemplates](https://drive.google.com/drive/folders/1u9HVzUn4Id0p1SbzTt8J6z6bSoQLYOud) (both for VFS and DST)

## Tasks
- [x] Add photo and name to each slide of the touchpoints slide doc
- [x] Add github name and practice area to the Reviewers section of both DraftingTemplates
   - name must be listed in alphabetical order
  
## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Keegan has been added to the touchpoint slides doc
- [x] Keegan is listed as a reviewer within the DraftingTemplate for all future Staging Reviews

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Please copy the touchpoints slide into this folder: https://drive.google.com/drive/folders/1do66VEGQUkRJu1bO3LQA3E8E-XZDL1yV

And then update the "during the meeting" guidance for DI, MPR and SR to link to the VSP Drive location and no longer Cheryl's personal Drive

**Comment by KKitagawa-Bosch** [comment]
Both drafting templates updated

**Comment by KKitagawa-Bosch** [comment]
@allison0034  Do you know all of the locations of the during the meeting guidance? Just want to make sure I update all instances!

**Comment by allison0034** [comment]
@KKitagawa-Bosch we do not mention names in those docs so you should be good, but you can find our docs [here](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1978433553/Collaboration+Cycle+Touchpoints).

**Comment by KKitagawa-Bosch** [comment]
@allison0034 I need to update the google slides link on them, and just wanted to make sure if there was a location other than the confluence so I don't miss anything, thanks!

**Comment by allison0034** [comment]
Good to close!
