### ISSUE TITLE
Submit PR to Restforce Gem to Add Support for Faraday 2.10.0

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#87902]
## Issue Description
While trying to bump Faraday to 2.10.0 in Faraday (Vets API), I found that Restforce restricts Faraday to ~> 2.9.0. We need to submit a PR to Restforce, wait for them to release a version, then bump Restforce in Vets API

---
## Tasks
- [x] Submit PR to Restforce
- [x] Once merged and released, bump Restforce in Vets API

## Acceptance Criteria
- [x] New version of Restforce supporting Faraday 2.10.0 is released to Prod
