### ISSUE TITLE
Create final designs for error pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#87938]
## Tasks

- [x] Add designs to [error pages page in Figma](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1872-17169)
- [x] Pull all error pages into the Figma page
- [x] Add check in auth errors
- [x] Use unique error pages for pre-check-in, which means we need to add unique 1s to each and add the accordions.
- [x] Check links at bottom of alert for pre-check-in errors. E.g., find out how to check in on the day of your appointment.

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/87938?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by zach-park** [comment]
Validated with @cgednalske also. 
Here is the link to the the Figma file:
https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=1872-17169&t=r8sQcnbE4TufefNf-1

**Comment by benbrasso-agile6** [comment]
@zach-park would you mind linking it out to engineers in slack. Since we just met with Brian and John about it a day ago, it might be beneficial for them to give it a quick review too.
