### ISSUE TITLE
Appoint a Rep - Cross Accredited VSOR - User Test - Define

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#87946]
## Issue Description
Interviews and user test of the 21-22 with cross accredited VSORs.

## Tasks
- [ ] Meet with ARF and Lesley to determine best approach for research.
- [ ] Set up kick-off with larger team.

## Acceptance Criteria
- [ ] All tasks complete.
