### ISSUE TITLE
Facilitate issues preventing release of ruby 3.3.X

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#87947]
## Issue Description
In order to bump ruby to 3.3.X, we need to facilitate the debugging of some errors found while performing the ruby upgrade.

There are 2 examples in [claims_document_upload_spec.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/rm-bump-ruby-3.3.3/modules/mobile/spec/request/claims_document_upload_spec.rb) (lines 146 and 205) that are failing. They seem have been silently failing (/accidentally passing) for quite some time, but only just surfaced because the way that Ruby formats errors has changed.

It points back to a more widely used library/method [ServiceException::send_error_logs](https://github.com/department-of-veterans-affairs/vets-api/blob/rm-bump-ruby-3.3.3/lib/lighthouse/service_exception.rb#L91) which has gone through some iteration, most noticeable recently to fix the bug we just fixed with the new Faraday release. 

So, we have two things to tackle: simplifying/fixing the `send_error_logs` method so that it's properly handling errors AND updating the specs that have been accidentally passing to something a bit more robust.
---
## Tasks
- [ ] (Lighthouse, Seth Darr?) Update `send_error_logs`
- [ ] (Mobile, Jason Conigliari?) Update `claims_document_upload_spec`
- [ ] Confirm all tests are passing

## Acceptance Criteria
- [ ] Once merged to master confirm that failing tests are no longer failing in #17419

**Comment by ryan-mcneil** [comment]
Duplicate. I hate Zenhub.
