### ISSUE TITLE
Adjust Appoint v2 designs for cross-accredited reps study

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#87942]
## Tasks
- [ ] Adjust content and designs based on research findings
- [ ] Present to Governance (call out that we are trying new patterns)
- [ ] Incorporate Midpoint Review feedback
- [ ] Determine if we need to present to the Design Council

## Acceptance Criteria
- [ ] Appoint v2 designs are ready for testing

**Comment by mtri** [comment]
- Received new content and adding into design
- Building out prototype and AB test

**Comment by mtri** [comment]
- All new and approved content has been added, will share with team soon

**Comment by mtri** [comment]
Unauth introduction prototype start points:
[Mobile](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80885&viewport=5767%2C-727%2C0.25&t=Fn7TVItVwho3bTQC-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&hide-ui=1)\
[Desktop](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80753&viewport=-1626%2C-663%2C0.25&t=VntcwmSH5Src32pt-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80744&hide-ui=1)

Auth introduction:
[Mobile](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=4521-226018&t=qQFYyoyih7zUqVxS-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4521%3A226018)\
[Desktop](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=4521-225994&t=qQFYyoyih7zUqVxS-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4521%3A225994&show-proto-sidebar=1)\
[Canvas view](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4521-226018&t=qQFYyoyih7zUqVxS-11)

Non-prototype screens:\
[Auth / Print fill confirmation / Desktop](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=4728-131569&t=qQFYyoyih7zUqVxS-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1)\
[Auth / Print fill confirmation / Mobile](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=4615-195279&t=qQFYyoyih7zUqVxS-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1)\
[Unauth / Introduction / Desktop](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80753&viewport=-3260%2C-1450%2C0.5&t=nzTmVZMTXEW8mCe9-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80744)\
[Unauth / Introduction / Mobile](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=3717-80885&viewport=5594%2C-916%2C0.25&t=m67MT3n3oyhO4hcw-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893)

[Slack thread discussion](https://dsva.slack.com/archives/C05L6HSJLHM/p1722291464022929)

**Comment by mtri** [comment]
Waiting on conclusion to "See all representatives" vs. "Check all representatives" content conversation once Janelle is back

**Comment by oddball-lindsay** [comment]
Let's move forward with "Check all representatives" for the additional component, and test with Veterans.

**Comment by mtri** [comment]
Check all representatives dropdown added with copy to test
