### ISSUE TITLE
[UX] 10-10EZR TERA: Update designs to accept special characters in "Other" text box

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#87952]
As a Veteran, I would like to be able to enter special characters in the "other" field so that I can tell the VA what happened to me while I was serving and what toxins I was exposed to in a clear and concise manner with punctuation.

- [x] Update Designs
- [x] Update error messages (see Angela's comment below)
- [x] Demo to team
- [x] Work with FE and QA on implementation
- [x] **Success: We have updated designs for the characters . ? ! , and Veterans know about that **

Original Story:
## Description
During TERA usability research, we uncovered a bug where a user tried to enter multiple other toxic exposures separated by a comma and kept getting an error with no clear explanation as to why. We identified that this was because of the comma so CAIA helped us write a line of text to explain to Veterans how to avoid that error by not entering special characters, but we ultimately want Veterans to be able to enter whatever characters help them best explain their other toxic exposures.

Once VES is ready to accept some special characters for the "other toxic exposures" field, we can remove the text that we added to help Veterans avoid errors due to special characters. The VES team says they will be implementing this change in June 2024 (likely around the 6/10 release date) so once we have confirmation from them that the system can accept special characters, we should remove the extra text that we added to that question.

VES will only accept these 4 special characters: `. ? ! ,` so we will still need an error for any other special characters. That error should read: "You entered a character we can't accept. Remove any special characters other than these: . ? ! ," (Design to verify this with CAIA)

## Tasks
- [ ] Update designs on hint text and error text (specifically when entering other characters that are not acceptable)
- [ ] Get approval from CAIA on new error text
- [ ] Confirm with VES that their system is ready to accept special characters for other toxic exposures
- [ ] Remove text on other toxic exposures form field that says "If you're listing multiple toxins or hazards, list them without commas or any other special characters"
- [ ] Remove error state that would occur if special characters were entered that says "You entered a character we can't accept. Remove any special characters like commas or dashes."
- [ ] Verify that the field is accepting the following characters without any errors: . ? ! ,
- [ ] Create an error state for any special characters other than the 4 that VES can accept that reads: `You entered a character we can't accept. Remove any special characters other than these: . ? ! ,`
- [ ] Functionality testing
- [ ] E2E Testing
- [ ] Merge update

## Acceptance criteria

- The "Other toxic exposures" field no longer has text stating not to use special characters and it accepts the following special characters without any errors: . ? ! ,
- There is a new error state implemented for any special characters that VES cannot accept.

**Comment by aagosto90** [comment]
Hi EZR folks! I worked with Aliyah yesterday to get the error message approved. Here's the [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=4435-46569&t=P8ToTzh13XozgLoK-1) that has the hint text removed and the approved error message from CAIA if the user entered a special character other than the 4 that VES can accept.

**Comment by IMHieuVo** [comment]
[Figma](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=4142-24072&t=UDvuN5yJsauVIn1c-1) link for mocks. With the OOB post-mortem due to the Enrollment System not being able to receive the special character, we'll table this update until further notice.
