### ISSUE TITLE
Canary launch for Toxic Exposure

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#87965]
## Issue Description
We need to run a canary test for the Toxic Exposure release to make sure our solution is functioning as expected and that monitoring is accurate and useful.

This is to track the Canary section from our [BRD release plan]

We'll be scheduling times with users from [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) and verifying activity is captured properly in our [DataDog dashboard](https://vagov.ddog-gov.com/dashboard/pfj-tf3-mb4?refresh_mode=sliding&from_ts=1700158863442&to_ts=1700162463442&live=true)

---
## Tasks
- [ ] Find veteran prod users https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md
- [ ] Write up testing instructions in testrail, use for the run
- [ ] Run Canary sessions using testing instructions (or use scheduled meeting)
- [ ] Verify accuracy of metrics - we get activity, activity logs can be used to identify Canary users
- [ ] Any updates needed are made to monitoring
- [ ] Establish Comms: put message out in evss migration slack channel 

## Acceptance Criteria
- [ ] Successful calibration

**Comment by pacerwow** [comment]
Previous estimate was a 3 for BRD.
