### ISSUE TITLE
[BE] 10-10CG - Form Updates: Research for ClaimGUIDs & timestamps for 7/8-7/9

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#87961]
## Background
We received the request below from Marla asking for the ClaimGuid and Creation timestamp for all the 10-10CG submissions from 7/8-7/9.

>we need a bit of help. Would it be possible for you all to provide the ClaimGuid for the records that got created on 7/8 and 7/9 along with the timestamp of creation? We need to review the applications that we received and ensure the application received date is correct on these applications as some were in our retry queue for a while waiting for a fix that we deployed to production today.  

## Tasks
- [ ] Review logs to confirm if we collect/store ClaimGuid for 10-10CG submissions
- [ ] Review logs to confirm if we have creation timestamps for 10-10CG submissions
- [ ] If we do have this information, gather all ClaimGUIDs and creation timestamps for all submissions from 7/8 and 7/9 
- [ ] If we do not have this information, work with CG team to determine whether there are other attributes we can pull to assist.

## Acceptance Criteria
- We have gathered information to assist CG team in validating submissions, especially those that were in the Mulesoft retry queue.

**Comment by hdjustice** [comment]
It was found that we do not store information when a submission is successful, we only log the number of successful submissions.  Only for errors do we log the user's info and attributes (including ClaimGuid) for troubleshooting and outreach efforts.

There is nothing further we can do for this ticket.
