### ISSUE TITLE
Fix Typo: Master Person Index

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#87971]
## Issue Description
https://depo-platform-documentation.scrollhelp.site/developer-docs/mvi says "Master Persons Index" when it should say "**Master Person Index**", so perhaps we could fix this?

---
## Tasks
- [x] Fix typo on MVI page

## Acceptance Criteria
- [x] Typo is fixed
- [x] Page is ready for deployment

## Relevant Link
[PII Page update from Footer Ticket 87709](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87709)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
bringing this issue into current sprint due to available capacity

**Comment by BSmolensky** [comment]
Page is live on the PW: https://depo-platform-documentation.scrollhelp.site/developer-docs/mvi

**Comment by BSmolensky** [comment]
Ticket ready to close.

**Comment by jknipes** [comment]
Closing ticket as _Done_
