### ISSUE TITLE
Vets API Mockdata GHA workflow mitigation

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#87976]
## User Story
As the managers and developers for the VA Platform, 
We need to mitigate build and deploy errors,
To prevent the deploy workflow from updating the image tag when the image build fails
So that the deployments are executed without error.

## Issue Description
We need to ensure that the deploy workflow does not update the image tag if the image build/push to ECR workflow fails. Currently, the deployment (image tag update) is triggered upon the **completion** of the image build/push to ECR. However, ['completed' does not necessarily mean 'successful.'](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/.github/workflows/deploy_vets_api.yml#L10-L11) Therefore, we must introduce an additional condition, similar to what we implemented [here](https://github.com/department-of-veterans-affairs/vets-api-mockdata), to prevent the deployment action from executing if the build action fails. For context, any commits to the [Vets API mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/.github/workflows/build_vets_api.yml) automatically trigger a build in the Vets API repository so that mockdata changes are propagated to live environments.

Please refer to [this Slack thread](https://dsva.slack.com/archives/C039HRTHXDH/p1720615473077069) for context and details. 
We have to add a conditional [here](https://github.com/department-of-veterans-affairs/vets-api-mockdata) to check for success. See @LindseySaari 's PR example, [here](url). 

## Tasks
- [x] Add a conditional [here](https://github.com/department-of-veterans-affairs/vets-api-mockdata) 
- [x] Check for success
- [x] Documentation as needed

## Success Metrics
There will no longer be errors during deployment to DEV and STG. 

## Acceptance Criteria
- [x] Tests run clean after checking for success
- [x] Any documentation is completed and shared
- [x] No more errors during deploy
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
