### ISSUE TITLE
DR | Drop evidence validation table and delete files from S3

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#88016]
## Background Context

This is a follow-up to #83132.

Both unprocessed and processed evidence attachments are currently being stored in S3 along with the user password in a table so we can validate the PDFTK process for errors (via a manual unlock process). Once this validation step is complete, we will drop the table and delete the unprocessed files from S3.

## Acceptance Criteria

- [x] Sensitive data for validating the decryption process is removed

## Tasks

- [x] Drop records from `decision_review_evidence_attachment_validation`
- [x] Remove files from S3

## Definition of Ready

- [ ] Whoever picks this up has access to production console

## Definition of Done

- [x] Records are dropped from `decision_review_evidence_attachment_validation`
- [x] Encrypted files in S3 are removed

**Comment by eileen-coforma** [comment]
Ready to start. Part of PR.

**Comment by eileen-coforma** [comment]
Blocked by #87405

**Comment by eileen-coforma** [comment]
PR was reviewed and approved. Will merge today. Plan for time to run script to delete S3 file, and we can call it done 🎉

**Comment by dfong-adh** [comment]
PR to drop table merged.

**Comment by Mottie** [comment]
We'll run the script to delete S3 files today.

**Comment by dfong-adh** [comment]
Validation files stored in S3 have been deleted.
