### ISSUE TITLE
[Design] MDT - Veterans need to be alerted if they they haven't placed an order for batteries in the past 2 years or only have rechargeable aids

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8802]
## User Story or Problem Statement
Our team recently discovered that the DLC will not be able to send us data identifying rechargeable hearing aids. How might we create an empty state for Veterans who order hearing aid accessories for their rechargeable devices but do not order batteries?

There are two use cases to consider:

- Veteran has not placed an order for batteries in the past 2 years
- Veteran only has rechargeable hearing aids on file

## Goal
_An empty state design for the 'battery selection' page notifying the Veteran that the VA does not have battery-eligible devices on file and provide next steps if that information is incorrect._

## Objectives or Key Results this is meant to further
- _MDT development_
---
## Tasks
- [x] _Create a mockup of an empty state for the 'Select hearing aid batteries' screen_
- [x] _Send to the frontend team to determine if the solution aligns with the form system_
- [x] _Once design is approved, create a ticket for frontend implementation_
- [x] _Link design to this ticket as a comment_

## Acceptance Criteria
- [x] _Ticket for frontend development is created_
- [x] _InVision mockup is linked to this ticket as a comment_

**Comment by rebeccawalsh** [comment]
The 'empty state' for when Veterans have no known devices on file to display:
- [Batteries - ineligible, no products shown](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/418131333)
[Overall battery selection documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-battery-selection.md#prototype-c2-p1-battery-selection)

**Comment by rileyorr** [comment]
[I've added ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9267)a ticket for the frontend team to incorporate these designs into the form.
