### ISSUE TITLE
Datadog Tune up

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#88035]
## Description
**We have a Datadog dashboard that needs some attention:** https://vagov.ddog-gov.com/dashboard/shm-nr4-75f/debt-resolution-vets-api?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1720629299933&to_ts=1720632899933&live=true

The numbers are not that accurate it seems and there are some graphs that are not populating.

We've had a lot of issues with the debts controller but the graph says we're 100:
<img width="1589" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMC9NQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c225580345acda23dd18de84103340b6e6f01b6/image.png" alt="image.png" />

Same with Copays:
<img width="1658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMURNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1f29a6b9ee6d8c9dd7ed1dc13032ec2bd89e595/image.png" alt="image.png" />

**Here is an incredible Dashboard I found debugging debts errors:**
https://vagov.ddog-gov.com/apm/resource/vets-api/rails.action_controller/9daef478fc36cacc?query=env%3Aeks-prod%20operation_name%3Arails.action_controller%20resource_name%3A%22V0%3A%3AFormsController%23index%22%20service%3Avets-api&fromUser=false&resourceName=V0%3A%3ADebtsController%23index&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&timeFrame%5Bend%5D=1720556942696&timeFrame%5BfromUser%5D=true&timeFrame%5Bpaused%5D=false&timeFrame%5Bstart%5D=1720470542696&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1720629627757&end=1720633227757&paused=false

Maybe we can mimic some of what's going on above  

## Tasks
- [ ] Spec out what we want to clean up and add. Maybe split off new graphs into a new ticket so we can make this one closable.

## Acceptance criteria

- [ ] Our dashboard (First one mentioned in the ticket) is populating values again with errors showing

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
No testing here as there will be minimal to no coding involved.

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>
