### ISSUE TITLE
[Design] Second iteration of MDT content page to make online ordering method have more visual weight

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8803]
## User Story or Problem Statement
When our team tested the MDT content page's initial design, many participants missed the CTA for ordering products online. How might we make the online ordering method have more visual weight compared to the other methods?

## Goal
_An updated design for the MDT's content page based on usability test findings_

## Objectives or Key Results this is meant to further
- _MDT development_
---
## Tasks
- [x] _Create a second design for the MDT content page that puts more visual weight on the online ordering method_
- [ ] _Link the InVision mockup in this ticket as a comment_

## Acceptance Criteria
- [ ] _New MDT content page design is linked as a comment in this ticket_
---

**Comment by rileyorr** [comment]
[Unauthenticated content page](https://vsateams.invisionapp.com/share/KJX78T3RVHD) | [Authenticated content page](https://vsateams.invisionapp.com/share/QXX78X0SFNG)
In reviewing the content team's edits from a couple sprints ago, they suggested adding a header above the 'order online' CTA. The design reflects their recommendation.
