### ISSUE TITLE
Add guidance to FDG about adding new pages to existing forms

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#88048]
## Purpose
There was a discussion in [this slack thread ](https://dsva.slack.com/archives/C01DBGX4P45/p1720622042945439)about trying to standardize behavior for when a team adds a new page to a form, and what that does from the user's perspective

## Tasks
- [ ] research situation
- [ ] determine what decided upon approach is
- [ ] document approach in FDG
- [ ] have an involved SME verify its accuracy

## Acceptance Criteria
- [ ] guidance is added and verified for accuracy
