### ISSUE TITLE
Burial | Create Swagger Documentation

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88054]
## Issue Description
_For the [Readiness Review requirement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86756), we need to create Swagger documentation for the v0/claim_attachments API endpoint._

`app/controllers/v0/claim_documents_controller.rb`

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Swagger documentation created for v0/claim_attachments API endpoint
- [ ] Link to documentation added to #86756
---
