### ISSUE TITLE
HLR 2024 | Contact Review Prep

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#88057]
### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below
</details>

#### Tasks
- [x] Create updated [Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md) (end result would be a Word Doc)
- [x] Create [Video](https://drive.google.com/file/d/1-rjVOa8JkFAfS6ZXVK2bqCiXCzEaHjQq/view?usp=drive_link)
- [x] Include guidance around error notification email
- [x] When you're done, tag Julie for review
- [ ] Eileen will add the info to the Collab Cycle ticket

### Documents
- [Existing product guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/higher-level-review/product-guide)
- [Sample product guide (Supplemental Claims)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims/product-guides)

**Comment by eileen-coforma** [comment]
Included sample document + link to the contact guide instructions.

**Comment by Mottie** [comment]
I'll be picking up Shaun's work on this

**Comment by Mottie** [comment]
Preliminary work is done - all screenshots were added, but I seem to remember a different doc including all error states with screenshots. Is that needed for this one as well?

**Comment by anniebtran** [comment]
Eileen reviewing and adding stuff as needed

**Comment by anniebtran** [comment]
Eileen continuing to work on this. Julie did some review on Friday, need to update format a bit

**Comment by anniebtran** [comment]
Eileen did a bunch of reformatting, now DK and Julie are gonna take a look at it

**Comment by eileen-coforma** [comment]
Product guide is done. I forgot about the video walkthrough, so I'll be doing it now.

**Comment by anniebtran** [comment]
@eileen-coforma to upload it somewhere

**Comment by anniebtran** [comment]
Need to get a transcript, so uploading to drive and splitting up amongst teammates to transcribe

**Comment by eileen-coforma** [comment]
Thank you for volunteering @anniebtran @shaunburdick @Mottie 

[Video](https://drive.google.com/file/d/1-rjVOa8JkFAfS6ZXVK2bqCiXCzEaHjQq/view?usp=drive_link)
[Transcript document](https://docs.google.com/document/d/13v1ivDXH0PPCEXa8FL2QTpeqLx3Kwq8Nm-pn_YQ1of4/edit?usp=sharing)

I assigned each a section with timestamps. Thanks for helping!

**Comment by anniebtran** [comment]
Updates are done, just needs to be sent out (not urgent)

**Comment by eileen-coforma** [comment]
Updated guidance with error email notification

Submitted video walkthrough for upload

Attaching link to product guide now (also in [Sharepoint](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/Supplemental%20Claim%20(20-0995)/2024%200995%20updates%20Research/SC%202024%20Updates%20Task%20Analysis.xlsx?d=w0b46096bdbe4493e835a12b64d7c4085&csf=1&web=1&e=4Fu45S))

**Comment by eileen-coforma** [comment]
Kicked off contact center review https://github.com/department-of-veterans-affairs/va.gov-team/issues/95514
