### ISSUE TITLE
Redirect Request for Burial 21P-530EZ Form

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88067]
### Status
**[2024-07-25] [Fran]** I followed up with Jenny M to determine if the new guidelines indicated we should PR all redirects implemented by other teams, and the answer is no. (for more info see her comment). I've removed PW tags, Sprint assignment, and my name as Assignee.
**[2024-07-11] [Fran]** Laura S has made note of the Sprint 9 dates and will reach out to us when the PR is ready for our review
**[2024-07-10] [Fran]** Note that the PW team won't be doing the actual redirect; we will be PR reviewers. I'm targeting Sprint 9, and commented in the ticket to let Laura know.

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

| POC | Github alias(es) |
--- | --- 
| Product team point(s) of contact: | Product: @steele-lm, Front-end: @DLarson-Oddball |
| Content point of contact: | @aliyahblackmore  |
| IA point of contact: | @jennymayoco  |

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [x] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)
- [x] We are removing a temporary redirect: We recently launched a new version (v2) of the form by gradually incrementing traffic to the new v2 url. Now that the v2 form is 100% launched, the v1 form needs to be retired and the v2 form needs to be redirected to the original (but updated to a new format) url.

### Do you need Public Websites to implement this redirect?
- [ ] Yes
- [x] No - Please note: Redirect still needs approval from IA and PW will do PR review
   - We would like to own the PRs for the redirect, so we can revert if there are any issues with claim submissions.
      - PR to add redirect from v2 to : https://github.com/department-of-veterans-affairs/devops/pull/14526
      - PR to add redirect to updated url: https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/481

### Implementation date
When does this request need to be live? **NOTE:** Redirects deploy M-Th. Friday launches should be avoided.
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [x] Any day after an earliest possible date. **EARLIEST DATE: 07/10/2024**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
This is an update to an existing url: https://www.va.gov/burials-and-memorials/application/530 and all child pages | https://www.va.gov/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez
https://www.va.gov/burials-and-memorials-v2/application/530 and all child pages | https://www.va.gov/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez

Jm - minor changes to url 7/10
Jm - updated destination URLs 7/11

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [x] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket
- [ ] Content team: Searches for any crosslinks that use the old URL and update with the new

**Comment by FranECross** [comment]
@steele-lm I see that the PW team will just be reviewing the PR, and not the actual redirect work. I'll target Sprint 9 (our current sprint starting today is packed) for the PR review. Thanks! cc @Agile6MSkinner @jilladams

**Comment by jennymayoco** [comment]
Hi @FranECross @jilladams @steele-lm I made some changes to the URLs up above and updated the first set. Originally, `https://www.va.gov/burials-and-memorials-v2/application/530 `was listed twice and so I swapped out the first row to `http://www.va.gov/burials-and-memorials/application/530`. Other than that the URLs look good!

**Comment by jennymayoco** [comment]
@steele-lm can you let us know when the redirects have been implemented? We'll want to update any crosslinks in Drupal with the new link so there's minimal broken link alerts. 

@aliyahblackmore we've been talking about this with Megan and Randi and happy to go over the redirect process! I added this as a step at the bottom of the task list.

**Comment by jennymayoco** [comment]
Hi all - I updated the redirect destination and removed the previous `and all child pages` note since URLs would redirect to one single URL. sorry for any confusion!

**Comment by steele-lm** [comment]
@FranECross What is the date range for sprint 9? (July 24-Aug 7?). @jennymayoco I'll make a note to circle back with you once the redirects are live. Thanks!

**Comment by FranECross** [comment]
Apologies, @steele-lm ! I should have included the dates. Sprint 9 is 07/23 to 08/06. Thanks for your note!

**Comment by FranECross** [comment]
@steele-lm @jennymayoco Quick question regarding the PR review. We're curious if the new redirect guidelines have a step to ask the PW team for a review? If not, then we don't actually need to review the PR, as long as you / your team tests and everything looks fine. If it is a line item in the guidelines, we can touch base with CAIA/whoever wrote them to see if this is really necessary. :) Thanks!

**Comment by jennymayoco** [comment]
hi @FranECross thanks for flagging! I connected with @mnorthuis on this and confirmed that any redirects for product work, the product teams can implement these and test themselves so moving forward there won't be a step where PW does the PR review. IA will still review the redirect tickets, but the product teams will do the redirect implementation and review. Any non-product work will still go through the normal redirect process. Let me know if you have any questions!

@steele-lm we don't have any published documentation on this yet, but if you have any questions, please reach out to the Platform team.

**Comment by FranECross** [comment]
@jennymayoco Thanks so much for the quick response and follow-up! You're awesome! I'll share this with our team so they're in the know as well. Have an amazing day.
