### ISSUE TITLE
[CST][ENG] Replace outdated timeline with new design

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#88061]
## Background Context

We are only releasing our new Claim Phases design to disability compensation claims for now. Until we create more specific experiences for non-disability compensation claim types. That new design replaces the existing timeline (AKA Process List) component (see below) which is outdated and has some accessibility issues that have been flagged by the Platform team. 

**Note on terminology:** In this ticket description, "timeline" and "Process List" are both used. They mean essentially the same thing. "Process List" is the name of the [component in VADS](https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--docs) and "timeline" is used more broadly to refer to both the old UI component and the new official Process List component.

Current UI:
<img width="697" alt="Screenshot 2024-08-08 at 12 48 27 PM" src="https://github.com/user-attachments/assets/19836985-32cd-44c9-b95d-f1161eeb49c9">

Until we can create more refined solutions for different claim types (which might take a while) we should at least replace this component with this newer component from the design system: https://design.va.gov/components/process-list

## Design

The original design ticket for this work can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/84491

[FIGMA](https://www.figma.com/design/ifXbQZaH56bnWyCMbYkh7t/Timeline-Update-for-Non-Disability-Claims?node-id=72-1942&t=NYhOoKu53JVnxEFu-4)

<img width="733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e61fd12991105de59da3a6f7696e356eabd073f/Screenshot%202024-07-10%20at%203.26.30%E2%80%AFPM.png" alt="Screenshot 2024-07-10 at 3.26.30 PM.png" />

## Engineering notes

[va-process-list component in Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-process-list--docs)

### Enablement team (if needed)
@jstrothman 

## Tasks
- [x] _For claims that aren't using the feature flag `cst_claim_phases`, use the timeline shown in the design spec to display the 5 step process_
- [x] _Remove the "Latest update" information that was shown in the old version of the timeline. This information should not be shown in the new version, since that information will be shown in Recent Activity in the new CST design_
- [x] _Update content for Step 1 and Step 2 to reflect what is in the design spec. This is the new content that we are also showing in the 8 step process, since those step descriptions are the same._
- [x] _Content for Step 3 and Step 4 should remain the same as they were in the old version of the timeline_
- [x] _Add new content for Step 5, as defined in the design spec_
- [x] _Ensure the implementation matches the spec for a closed claim state. All steps should have the check mark icon when a claim is at Step 5: Complete._
- [x] Remove old components that are no longer used
- [x] Update cypress tests
- [x] Remove/Add/Update unit tests

## Open Questions:
- Should this work be behind a new feature flag?

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] _The UI shows the new Process List component for the 5 step process for all claims that are not covered by the Claim Phases work (i.e. all claims not behind the `cst_claim_phases` feature flag_
- [x] _The content in the Process List has been updated to match what is in the design spec and listed in Tasks above_
- [x] _"Latest update" content has been removed from the timeline_
- [x] _When a claim is closed the timeline shows the 5 step process, with all steps checked_ 
- [x] Old components are removed

**Comment by pmclaren19** [comment]
Reviewed and added some updates to tasks, questions and ac during eng refinement.

**Comment by pmclaren19** [comment]
@jacobworrell fyi the current ticket ac doesnt list that this needs to be behind a feature flag. Just want to verify that you dont want this behind a feature flag.
