### ISSUE TITLE
User reports of jenkins not being reachable over GFE VPN, even though our documentation says it should be

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#8807]
## User Story or Problem Statement
As a user with GFE over VPN, one cannot reach jenkins.vfs.va.gov. Only works over SOCKS proxy. The documentation explains that it should work on the VA network in addition to SOCKS. So either the doc is old and should be updated, or the problem needs some attention.

Relates to: https://dsva.slack.com/archives/CBU0KDSB1/p1588778184119500?thread_ts=1588777857.118700&cid=CBU0KDSB1

## Goal
If the desired service is meant to be reached over GFE VPN, it needs to be fixed as it is not currently resolving. If not, the doc should be updated to say "will only work over SOCKS."

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Confirm whether jenkins should be visible over GFE VPN or not, fix or update doc accordingly.

## Acceptance Criteria
- [ ] Working endpoint over GFE VPN OR updated documentation.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchelen-gov** [comment]
Doc link: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#internal-tools-access
DNS query on GFE VPN:
```
$ dig +short jenkins.vfs.va.gov
<blank>
```

**Comment by ricetj** [comment]
Closing, because this work will be covered in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9570

**Comment by wyattwalter** [comment]
The DNS issue was resolved, but we still have an issue with the ALB listeners when coming from GFE. Gonna fix that up today.

**Comment by wyattwalter** [comment]
This is working now!
