### ISSUE TITLE
[CST] [ENG] Update 5103 1P alert content

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#88077]
## Background Context

**NOTE:** This ticket was updated to reflect the new request and scope expanded from just alert header to alert header + body text. (Aug 22, 2024)

**ALSO NOTE:** This ticket supercedes and nullifies [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91132). Closing this ticket will make that ticket irrelevant.

---- 

We have new CAIA content recommendations for what the 1P alert content should be: 

Before (old)
<img width="429" alt="Screenshot 2024-08-22 at 10 55 47 AM" src="https://github.com/user-attachments/assets/ed02300c-ac4c-469d-a659-8dfce1a969e2">

After (new)
<img width="467" alt="Screenshot 2024-08-22 at 11 02 21 AM" src="https://github.com/user-attachments/assets/12a588d2-8571-4f67-89aa-7df6231a6e58">

## Design

[FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3498-13372&t=Pu3VW3fGEYCCKeyb-4)

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- 

## Tasks
- [x] _Update 1P alert header to match new spec for **both Custom 5103s and Standard 5103s**_

## Definition of Done
- [x] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _1P alert header and body text reflect the spec guidance for Custom 5103s **and** Standard 5103s_

**Comment by pmclaren19** [comment]
Reviewed during eng refinement.

**Comment by samcoforma** [comment]
@skylerschain update me when I can pick up these two tickets

**Comment by samcoforma** [comment]
@jacobworrell I just changed the points on this from 1 to 3, because there was logic that depended on the `displayName` content which made this involve a lot more work than a simple content update.

**Comment by samcoforma** [comment]
@jacobworrell reverting the points on this ticket back to 1 per our discussion
