### ISSUE TITLE
Rooadmap prioritization unmoderated study

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#88079]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

We want to run an unmoderated closed card sort to have Veterans who have VHA debt and VBA debt categorize roadmap items into levels of helpfulness. 

We will have multiple cohorts that will allow us to have a higher number of Veterans participate in this quantitative study. 

This study will help inform the prioritization of our[ roadmap items ](https://docs.google.com/spreadsheets/d/1PjpLz_ywN7-Rx3CpQvvkJy_UADNv8gOc/edit?gid=907339630#gid=907339630)into Veteran-centered and Veteran-driven priorities. 

---
## Tasks
_What work is necessary for this story to be completed?_
- [ ] The study draft is setup in OptimalSort
- [ ] The Veteran cohorts survey screeners are created
- [ ] The research is approved by Platform
- [ ] The study is run and analyzed
- [ ] A report out happens

## Acceptance Criteria
_What will be created or happen as a result of this story?_
- [ ] The study is setup in OptimalSort
- [ ] The study takes place
- [ ] The study data is analyzed
- [ ] A report out and recommendations
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Tom-Davis** [comment]
As of 9/4/24 a low priority for the future.
