### ISSUE TITLE
Collaboration Cycle - Add CMS touchpoint

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88087]
## Problem Statement 

The Platform CMS team has a need to work with VFS teams that are utilizing Drupal. They had previously established a "CMS Collaboration Cycle," but VFS teams found it difficult to bring their work through both the CMS Collab Cycle and the Platform Collab Cycle simultaneously. After many discussions and PO approval from both teams, it has been decided that CMS will be brought into the Platform Collaboration Cycle. The CMS team has already completed much of the work on their end. Governance must now modify their own processes and guidance in order to introduce the CMS touchpoint seamlessly into the existing Collaboration Cycle.

How might we notify VFS teams so that they are aware of any changes that may impact them?
How might we ensure that Collaboration Cycle processes are clear and consistent?

## Hypothesis or Bet
If we add CMS as a touchpoint in the Collaboration Cycle, then VFS teams who may not know that they need support from CMS team are directed to work with them.

If we add CMS as a touchpoint in the Collaboration Cycle, then CMS team can utilize the Governance touchpoint recordings, making it easier for them to understand the VFS team needs. 

## We will know we're done when... ("Definition of Done")
- [x] VFS teams are asked at Collaboration Cycle kickoff if a VA editor will notice the change they are making to VA.gov
- [x] CMS has a touchpoint page in the Collaboration Cycle section of Platform Website.
- [x] Governance operational processes at Kickoff include recommending the CMS touchpoint, when applicable.
- [x] VFS teams have been informed of the change in process

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
August 14, 2024

**Comment by shiragoodman** [comment]
All changes launched August 13, 2024. Closing as complete.
