### ISSUE TITLE
Analyze VRE (CH31) and create initial design artifacts

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8809]
## Goal 
We want to see how the VRE CH31 application works now at a high level so we can start to strategize about its functionality.

## Tasks
- [x] Create customer journey or workflow diagram of existing application
- [x] Create thumbnail path for new implementation of app on VA.gov

## Acceptance Criteria
- [x] Create a high level thumbnail view of the CH31 application (existing)
- [x] Create a high level thumbnail view of the CH31 application (proposed)

**Comment by sporeboy** [comment]
Initial thumbnail views of current eBenefits flow, and proposed VA.gov flow posted here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/research-design/ch31-user-flows.md
