### ISSUE TITLE
Update Governance operational guidance at Kickoff re: CMS

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88090]
## User Story
As a Governance team member, I need to know how to update the Collab Cycle Request ticket wrt the new question CMS is adding to kickoff so that I can be sure to give VFS teams the appropriate guidance. 

Assignee: @allison0034
Peer Reviewer: @erinrwhite

## Description
Governance operational processes need to be modified in order to successfully bring in CMS as a touchpoint in the Collaboration Cycle. This mostly includes updates to the Collaboration Cycle Kickoff - Moderator responsibilities doc, as well as the Custom Tracks flow chart.

Governance needs to know how to respond if/when a VFS team member answer yes to the new question CMS is adding to the kickoff. The new question and response from CMS can be found in their epic for [Integrate CMS into the Platform Collab Cycle](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18337).

## Impacted Artifacts

- [Collaboration Cycle Kickoff - Moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
- [Custom Tracks Flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow)

## Tasks
For the Collab Cycle Kickoff- Moderator responsibilities changes, please coordinate with the assignee for ticket #88162 so that there is only 1 draft page with changes for schedule and for CMS both included.

- [x] Create a code block for the CMS Touchpoint in the kickoff - moderator responsibilities doc
   - Code block should be similar to Analytics Request, PSIRR or Contact Center. In short, we are just directing the VFS team to the CMS touchpoint page. Include placeholder links/text where applicable as much of this information is dependent on the CMs team. 
   - Get link from CMS team
 - [x] Since the CMS touchpoint will only be recommended to a small number of VFS teams, determine how we want to handle the "combined code blocks." Maybe have 1 with CMS and 1 without? Your choice.
 - [x] For the Custom tracks flow, add the CMS kickoff question to the flow where it makes sense. It will not be applicable to Track 5. 
 - [x] When pages have been peer reviewed and approved, inform Shira so that she may share with the CMS team for their review and feedback. This ticket can still be closed if we have not yet received CMS team feedback.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have updated our operational guidance to include recommending the CMS touchpoint within the Collab Cycle
- [x] We have not published this guidance yet and it remains in a draft state

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Added code block to draft of [kickoff moderator doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3315073025/88090+-+Allison+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+2).

**Comment by allison0034** [comment]
[Asking Grace](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18337#issuecomment-2239544596) for a link to the form/guide VFS teams will go to.

**Comment by allison0034** [comment]
@erinrwhite you can get a head start on a PR if you want. The 2 drafts can be found [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3318087710/Allison-Ian+CMS+and+scheduling+pages).

Note, I am still waiting to hear from the CMS team on what link I can put in their code block for VFS teams to follow.

**Comment by erinrwhite** [comment]
@allison0034 Docs looking good - I had a couple of comments on the kickoff doc but nothing major.

On the diagram, I have the same question about wording as on the [VFS-facing materials](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88169#issuecomment-2245405712): I think "Will a VA editor notice this change?" is a good start but might not be 100% clear that we're talking about the editor experience in Drupal.

**Comment by allison0034** [comment]
@erinrwhite yes good point, and I did not realize Drupal was the only CMS... changes made!

**Comment by shiragoodman** [comment]
@allison0034 @erinrwhite for the Collab Cycle Request YAML template, there will be a link VFS teams can follow to get additional details on what the question means. [CMS team will be responsible for the content](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3092447277/CMS+Platform+Collab+Cycle#CMS-specific-Questions-for-Intake-Form%3A). We do this already for the product and feature questions. See screenshot.

If you absolutely think that we need to change the question still, please lmk since this would impact the VFS experience too.

<img width="365" alt="image" src="https://github.com/user-attachments/assets/94e7a5e0-cedb-4116-bcfd-3829e6bc5ba9">

**Comment by erinrwhite** [comment]
@shiragoodman got it! Sorry I missed this info before.

**Comment by allison0034** [comment]
@shiragoodman I think @erinrwhite may still have a good point. By adding the word "Drupal" it may clarify things. Most people know that Drupal is a CMS, however they may pause and think about it, but if we just add Drupal it might be super clear. What does everyone think?

**Comment by shiragoodman** [comment]
tagging @gracekretschmer-metrostar and @EWashb for their input since it is their question. Please read through the comments above and let us know your thoughts. Thank you!

**Comment by allison0034** [comment]
Just waiting on the link from CMS, hoping I will get it today.

**Comment by allison0034** [comment]
Marisa said the draft was approved, however I still need to official link.

**Comment by allison0034** [comment]
The 2 drafts can be found [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3318087710/Allison-Ian+CMS+and+scheduling+pages). Still waiting on link.

**Comment by erinrwhite** [comment]
Drafts are looking good.

**Comment by allison0034** [comment]
FYI @erinrwhite I removed "Drupal" from everything except the actual kickoff question per Shira's suggestion.

**Comment by erinrwhite** [comment]
@allison0034 sounds good!

**Comment by allison0034** [comment]
@shiragoodman you can share with CMS if you want, we just need their link... and the touchpoint page.

**Comment by erinrwhite** [comment]
@allison0034 peer review boxes checked! good to close
