### ISSUE TITLE
Discovery: Research enable trace correlation for logs in Datadog

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88092]
## User Story
As the managers and developers of DataDog for the VA Platform,
We need to determine the capacity of Datadog to enable trace correlation for fwdproxy logs,
So that when it is time to deprecate the EVSS tool, there is a plan in place for doing this work, and confidence in the outcome. 

## Issue Description
This ticket stems from [this Slack ticket](https://dsva.slack.com/archives/CJRQ85PQB/p1720637409589609). 
We think that shutting the FT off would be ok, and need to confirm that the test suite has examples for both the on and off FT scenarios.

## Tasks
- [ ] Research level of effort required to setup revproxy layer with the trace_id to forward on (maybe via the headers?) through the layers of the stack
- [ ] Research level of effort required to setup Vets Website layer with the trace_id to forward on (maybe via the headers?) through the layers of the stack
- [ ] Research level of effort required to setup VetsAPI layer with the trace_id to forward on (maybe via the headers?) through the layers of the stack
- [ ] Research level of effort required to setup fwdproxy layer with the trace_id to forward on (maybe via the headers?) through the layers of the stack
- [ ] Create documentation for strategy

## Success Metrics
That there is a plausible way forward to enable trace correlation when the effort begins. 

## Acceptance Criteria
- [ ] The team will have a strategy for enabling trace correlation for logs in DataDog
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by AshleyGuerrant** [comment]
Hi @LindseySaari & @flooose - is this ticket still relevant in preparation for the EVSS deprecation? Thanks in advance!

**Comment by flooose** [comment]
@AshleyGuerrant I'm not familiar with this ticket, so I can't say. Not sure how I was assigned :)
