### ISSUE TITLE
Finalize PCPG CH36 Mockups

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8810]
## Goal
We want to have a working mockup/ prototype of the CH36 application to work from

## Tasks
- [ ] Obtain stakeholders feedback (share mockup pdf an/or schedule meeting)
- [x] Finalize the mockup for the CH36 mockup/ prototype

## Acceptance Criteria
-  [x] The mockup/prototype has been updated

**Comment by sporeboy** [comment]
Adjustments made to mockups here: https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/

Workflows include intro and confirmation screens. Three use cases covered:
- Veteran or service member unauthenticated
- Veteran or service member authenticated with static biographical info
- Dependents unauthenticated

**Comment by sporeboy** [comment]
Required fields Identified:
- First name
- Last name
- SSN
- Country
- Street
- City
- State
- ZIP
- Phone
- Email
- Veteran’s name and SSN

**Comment by sporeboy** [comment]
Questions for TED office...

Does the business want to include (from the paper form):
- VA file number
- Military service history 
- If yes, do we need to allow the Veteran upload a copy of their DD214?
- Chapter 31 and education assistance questions
- Other special information questions (Part III)
