### ISSUE TITLE
[Task] Draft confirmation email language based on up-to-date submission page

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#88106]
## Value Statement

**_As a_** Veteran

**_I want to_** have my expectations of submission timelines be accurately and consistently set

**_So that_** I know how long I should expect my submission to take before I can see its status in the Claim Status Tool

---

## Background Context

- See Ticket #85786

## Outcome, Success Measure, KPI(S), and Tracking Link

- All notifications post-submission set an accurate expectation of timeline to prevent re-submitting claims or reaching out for support prematurely

## Acceptance Criteria

- [ ] _All post submission notifications (both page and email) set the expectation that it may take 7-10 days for a claim to show in the various systems after submission_

## Designs and Build Notes

   - [_Supplemental Claim_](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1110-15413&t=urvHtrc5qYXwWQhk-11)
   - [_Higher Level Review_](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=782-41758&t=15BQIFJvtOgHLPqp-11)
   - [_Board Appeal (Notice of Disagreement)_](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=840-81126&t=gR1BH0wXZoyCkrU3-11)

### Enablement team (if needed)
@jstrothman 

## Out of scope
- Non-Veteran confirmation email
- Updating emails (Lighthouse)

## Open questions

- Add here

## Tasks

- [x] _Draft confirmation email design for:_
   - [x] [_Supplemental Claim_](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1110-15413&t=urvHtrc5qYXwWQhk-11)
   - [x] [_Higher Level Review_](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=782-41758&t=15BQIFJvtOgHLPqp-11)
   - [x] [_Board Appeal (Notice of Disagreement)_](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=840-81126&t=gR1BH0wXZoyCkrU3-11)
- [ ] _Hand over to Lighthouse_

## Definition of Ready

- [x] Clear value description
- [x] Testable acceptance criteria
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by product and/or design
- [ ] Shared with Lighthouse

**Comment by eileen-coforma** [comment]
Linked for Julie [to review](https://dsva.slack.com/archives/C06V3RU6HA9/p1720800582119159).

**Comment by eileen-coforma** [comment]
@shaunburdick The files are ready to share with Michael Hobson for the email updates. Let me know if they prefer it to be exported into a format other than a FIGMA file.

**Comment by eileen-coforma** [comment]
Handed it off to Michael Hobson, so done. Will keep checking VANotify templates to see if it's updated.
