### ISSUE TITLE
Update SOCKS user guide page for Platform Website

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#88111]
## Description
The SOCKS update is going to require a user guide to help anyone who needs to apply the update. This user guide should conform to the guidelines provided by the Platform Content Team to ensure consistency across our VFS-facing documentation regarding formatting, tone, etc.

**Reference** - The user guide should utilize the [How-to guide template](https://vfs.atlassian.net/wiki/templates?space=~672346535&template=1477083205) from platform content team

## Tasks
- [x] Create a draft version of the document
- [x] Test the steps of the document to ensure they are accurate/current, or to account for slight variations in the experience
- [x] Add additional text to detail the context, background, prelim steps, excerpt for meta-data, etc.
- [x] Have another team member review for spelling/grammar

# Acceptance Criteria
- [x] Complete user guide is created that conforms to the template and has been peer reviewed
- [x] Page is located in the appropriate section of Confluence that will have the page published to Platform Website
