### ISSUE TITLE
[FSR] Update GMT year for 2025 (Due xx, 2025)

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#88119]
## Description
Every year 2025 rates get updated on the HUD website, and when VHA updates their calculations we also need to adjust the calculations in the FSR. 

The notes below are helpful, but also included in our new documentation: 
### Notes:
- [Potentially relevant thread in public websites channel](https://dsva.slack.com/archives/C52CL1PKQ/p1720550218119789?thread_ts=1716395837.636079&cid=C52CL1PKQ)
- [HUD 2024 data set](https://www.huduser.gov/portal/datasets/il.html#data_2024)
  - _for validation, it should contain the latest info_
- [Income limits application documentation for data source](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/data/README.md)

Shifting to a more proactive approach on this one. The HUD data is usually released around April 1st, so let's plan to pull this recurring ticket at that time every year. When we start the ticket first check the HUD has the data for the new year, and then let VHA (and our PO) know we are ready to move forward so they can use the same data source.

## Tasks
- [x] Confirm the new year HUD data is available by contacting `sitewide-public-websites` team to confirm their `income_limits` endpoint has the most recent data. 
  - **Note:** You may be able to just hit the endpoint with a new year and see if the response is valid
- [x] If the HUD data is up to date coordinate with PO and VHA folks so they can update at the same time
- [ ] Update year in gmt calculation for the FSR
- [ ] Test changes, update relevant tests
- [ ] Clone this ticket for the next calendar year with a due day of April 1st
  - **Note:** Don't forget to make any relevant updates to the content of this ticket and/or the documentation

## Acceptance criteria

- [ ] FSR is now using new year data to calculate streamlined waiver eligibility 
- [ ] All existing tests are passing 

## Testing
- [ ] Test new endpoint is receiving updated GMT data

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by HeatherRienks** [comment]
@Dr-Pongo  and @denisecoveyduc to discuss further

**Comment by HeatherRienks** [comment]
@Dr-Pongo  and @denisecoveyduc - any updates on this and when the deadline is? :)

**Comment by HeatherRienks** [comment]
Per Slack convo wtiht Andrew & Denise, we still need to update to 2025.

@denisecoveyduc to follow up to ensure they know our plan to update the calculations as soon as they are available (Approximately April 1st each year)

**Comment by amponce** [comment]
Notes:

- 2024 HUD income limit data was automatically uploaded on Jan 1, 2025.
- Next upload will be on Jan 1, 2026, and will contain the 2025 data.
- Confirmed: the previous year’s data drives the current year’s limits.
- There’s a tool referenced in the ticket to check available data, but it’s currently not accessible via CAG.
