### ISSUE TITLE
[Design] Provide clearer content on the product selection screens' alerts

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8811]
## User Story or Problem Statement
During usability testing, we uncovered that some participants thought if they were ineligible to order one set of products (batteries/accessories), they were ineligible to place an order entirely. How might we make content improvements to product selection screens' alerts based on our findings?

## Goal
_Alerts that are clearer for our users to understand_

**The product selection screens' alerts:**
- Hearing aid batteries
   - [No devices are eligible for resupply](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/406054376_C2_P1-_Select_Supplies_-_Rechargeable_Only)
- Hearing aid accessories
   - [All available accessories have been ordered within the past 5 months](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/407889090_C2_P2-_Select_Supplies_-_Accessories_-_Ineligible) 
   - [No accessories have been ordered within the past 2 years ](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/411094793_C2_P2-_Select_Supplies_-_Accessories_-_No_Accessories_On_Record)

## Objectives or Key Results this is meant to further
- _MDT development_
---
## Tasks
- [x] _Review the existing alerts on the product selection screens_
- [x] _Make content edits to alerts as needed_
- [x] _Link updated designs to this ticket, or if no edits are made please provide details why_
- [x] _Create a ticket for the frontend team to implement changes_

## Acceptance Criteria
- [ ] _Updated mockups have been added as a comment_
- [ ] _A ticket has been created for frontend implementation_
---

**Comment by rebeccawalsh** [comment]
Changes have been made to the messaging on the following pages:

[Overall battery selection documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-battery-selection.md#prototype-c2-p1-battery-selection)
[Batteries - eligible](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/416259607)
[Batteries - ineligible, products shown](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/418131332)
[Batteries - ineligible, no products shown](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/418131333)

[Overall accessories documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/prototype-accessory-selection.md)
[Accessories - eligible](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/416259608)
[Accessories - ineligible, products shown](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407889090)
[Accessories - ineligible, no products shown](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/411094793)

**Comment by rebeccawalsh** [comment]
@leahkeeler I have written an [issue for frontend to implement these changes](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9290)
