### ISSUE TITLE
FMB Phase 2 Redirect Coordination

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#88114]
```[tasklist]
### Tasks
- [x] Submit redirect ticket to PW (https://github.com/department-of-veterans-affairs/va.gov-team/issues/88112)
- [x] Update ticket with final URLs
- [ ] Email stakeholders about redirects
- [ ] Tell PW when we're ready to implement
```

**Comment by laurwill** [comment]
Hey @kristinoletmuskat , I found a few more URLs we need to add to the redirect ticket. 

All 3 of these URLs need to redirect to the main CHAMPVA page: 
https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/index.asp 
https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/champva-eligibility.asp
https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/champva-apply.asp 

All 3 of these URLs need to redirect to the Getting care through CHAMPVA page:
- https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/CHAMPVA-faq.asp 
- https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/CITI.asp 
- https://www.va.gov/COMMUNITYCARE/programs/dependents/locate_provider.asp
