### ISSUE TITLE
Spike | Burial | Determine types of accounts submitting claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88122]
## Issue Description
_In order to better understand and design the burial form user experience, we need to understand what types of accounts are submitting claims._

A few starting points:
- MPI is the [authoritative source](https://dsva.slack.com/archives/C7TE0PFTL/p1704808861898369?thread_ts=1704745234.276589&cid=C7TE0PFTL) for the deceased (and incompetent?) indicators, and it sounds like we may be able to leverage an existing API to identify accounts with these indicators
- VA Profile has some indicators for deceased and incompetent [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/account_security/frontend_documentation.md#fiduciary-flag--blocked-profile-logic) to understand the types of flag that can be added to a user's VA profile.

```
{
  "data": {
    "attributes": {
      "responses": [
        {
          "control_information": {
            "can_update_address": true,
            "corp_avail_indicator": true,
            "corp_rec_found_indicator": true,
            "has_no_bdn_payments_indicator": true,
            "identity_indicator": true,
            "index_indicator": true,
            "is_competent_indicator": true,
            "no_fiduciary_assigned_indicator": true,
            "not_deceased_indicator": true
          },
```
---
## Tasks
Create a (Datadog?) dashboard that shows:
   - [ ] How many submissions are using a deceased Veteran's account
   - [ ] How many submissions are using an incapacitated Veteran's account
   - [ ] How many submissions are using a non-deceased Veteran's account (e.g., family member who is a Veteran)
   - [ ] How many submissions are unauthenticated

## Acceptance Criteria
- [ ] Dashboard that breaks down claim submissions by account type
---

**Comment by steele-lm** [comment]
@fiorella-io Created a ticket to try and determine account types for burial submissions.
