### ISSUE TITLE
[FSR] Update GMT year for 2024 

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#88120]
## Description
Every year 2024 rates get updated on the HUD website, and when VHA updates their calculations we also need to adjust the calculations in the FSR. 

### Notes:
- [Potentially relevant thread in public websites channel](https://dsva.slack.com/archives/C52CL1PKQ/p1720550218119789?thread_ts=1716395837.636079&cid=C52CL1PKQ)
- [HUD 2024 data set](https://www.huduser.gov/portal/datasets/il.html#data_2024)
  - _for validation, it should contain the latest info_
- [Income limits application documentation for data source](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/data/README.md)

## Tasks
- [x] Contact `sitewide-public-websites` team to confirm their `income_limits` endpoint has the most recent data. 
- [x] Update year in gmt calculation for the FSR
- [x] Test changes, update relevant tests
- [x] Generate ticket for following year (see **[FSR] Update GMT year for 2025 [#88119](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88119)**)
- [ ] Outline repeatable update process in GH documentation **(need to create this and then add to [Debt Team Documentation Summary](https://docs.google.com/document/d/1v7P2AEJZ6-6LbAhvUNB5tzgLqV7TlElc-qeymcmTPZ8/edit)!)**

## Acceptance criteria

- [x] Ticket and process generated for 2025 update
- [ ] Process has been documented in GH 
- [x] FSR is now using new year data to calculate streamlined waiver eligibility 
- [x] All existing tests are passing 

## Testing
- [x] Test new endpoint is receiving updated GMT data

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
### Notes
--- 
Updating with a note about the calendar year vs available GMT data in this previous conversation:
https://dsva.slack.com/archives/C52CL1PKQ/p1698161355128349?thread_ts=1698156487.939009&cid=C52CL1PKQ 

The GMT data is for the previous calendar year (ish), so we pass in 2024 and get 2023 data.

**Comment by Dr-Pongo** [comment]
New year has been merged, will monitor Sentry this week for any potential bugs and then close the ticket

**Comment by HeatherRienks** [comment]
@denisecoveyduc - we have questions about this. Need to coordinate with VHA regarding timing of this.

**Comment by Dr-Pongo** [comment]
Closing out with follow on ticket generated for documentation:
- **[FSR] Update documentation for GMT year update [#90545](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/90545)**
