### ISSUE TITLE
Partner w/ Support to append Feedback Workflow to close out message

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#88130]
## Purpose
We want to look at ways to get the Feedback Workflow out into the VFS consciousness.  Since people are in that mindset when visiting Support, what if their closeout message included advice for the user to contact the workflow for any related or future feedback on an issue that they experience?

## Tasks
- [ ] Figure out what we're after
- [ ] Discuss w/ Alyssa to get a sense of what they have and how best to mesh with it
- [ ] Create language
- [ ] Support installs language
- [ ] test
- [ ] profit

## Acceptance Criteria
- [ ] new reference to FW in Support message is active

**Comment by tayism** [comment]
This tool has been deprecated.
