### ISSUE TITLE
Clarify Staging Review artifacts requirements

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#88140]
## User Story
As a VFS team member, I want to understand which artifacts are absolutely required for my team to provide at a Staging Review.

As a Governance Team member, I want to have the information I need to complete a review. 

As on-support Governance Team member, I want to know what artifacts need to be present to verify four days in advance that teams' Collab Cycle tickets have the artifacts necessary for a Staging Review.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description

At Staging Reviews we currently ask VFS teams for a number of artifacts for Governance's review. If these required elements are not present, Governance cancels the review and asks the VFS team to reschedule. In our Collab Cycle ticket template and our Staging Review requirements list, it is not currently 100% clear which of these artifacts are actually required ahead of time, and which are optional, nice to have, or otherwise would not cause the team to need to reschedule the Staging Review. 

This ticket should be completed alongside #88107

Is @it-harrison able to help rewrite the script for updating the Collaboration Cycle Request tickets so that ALL open Collab Cycle Request tickets have the up to date guidance re: required artifacts?

## Impacted Artifacts

- Wherever Staging Review requirements text appears:
  - [Calendly](https://calendly.com/collaboration-cycle/staging-review?month=2024-07)
Slack workflows? 
  - [Staging Review page on Platform website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
  - [How to document findings at SR](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)
    - note from Shira: I do not believe that the requirements should be in this doc. The SR requirements are VFS facing and should not be copy/pasted in operational docs. This doc should instead point to the SR requirements on Platform Website.
- Artifacts list on [Collab Cycle ticket template (in kickoff instructions)](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities?search_id=45e3f47f-46a4-4f1b-984a-2834bb615128)

## Tasks
- [x] Update Staging Review Requirements text to reflect current practice and specifically list needed artifacts and/or tasks to be completed ahead of SR.
- [x] Update Staging Review section of Collab Cycle ticket to clearly reflect required vs optional or non-review-blocking artifacts.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Staging Review requirements have been updated to clearly state which artifacts are required
- [x] All VFS-facing guidance regarding the artifacts and requirements has been updated to reflect the change

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@shiragoodman a draft of another ticket about clarifying required SR artifacts based on our convo this morning

**Comment by erinrwhite** [comment]
@shiragoodman yes! While we're in there...

**Comment by erinrwhite** [comment]
Prepping for conversation with team at weekly initiative meeting on Monday

**Comment by erinrwhite** [comment]
Started [draft doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/88140+-+Erin+-+Updates+to+Staging+Review+artifact+guidance) for team review on Monday

**Comment by erinrwhite** [comment]
Next steps from team meeting:

- Erin update CC ticket SR artifacts section (including changes for #88107) and share for review, then
- Ian run script to update existing CC tickets
- Shira - write ticket to announce to VFS teams via change history and slack

**Comment by erinrwhite** [comment]
@allison0034 [Draft page of SR requirements](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/88140+-+Erin+-+Updates+to+Staging+Review+artifact+guidance) ready for your review before I share out again with the team

**Comment by allison0034** [comment]
@erinrwhite this is much more clear! I did make some comments. My only concern is we know from past user testing that this ticket is a lot and overwhelms VFS teams. I know there is more content now with your changes. We need to trim any unnecessary content. Typically I see if I remove something, does the sentence still make sense. We tend to repeat a lot of what we say.

Take a look and see if anything I commented makes sense.

**Comment by erinrwhite** [comment]
thank you @allison0034 those are good edits! I [incorporated those and whittled it down even more](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/88140+-+Erin+-+Updates+to+Staging+Review+artifact+guidance). Going to share with the team for a last gut-check before implementing edits.

**Comment by erinrwhite** [comment]
@allison0034 I think this is ready for your review (next week! it's quittin' time for the week...)

**Source of truth for updated requirements**
- [X] [Doc with finalized SR requirements and list of artifacts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/88140+-+Erin+-+Updates+to+Staging+Review+artifact+guidance).


**Pages already updated:**
- [x] Updated [How to document findings at staging review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review) to link to the SR page on Platform Website instead of re-listing the requirements.

**In draft/ready to be published as part of #89357:**

- [x] Calendly should be updated using the text on this [doc of finalized language](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/88140+-+Erin+-+Updates+to+Staging+Review+artifact+guidance#Updates-to-broader-requirements-in-Calendly-and-Platform-Website)
- [x] Created a [Draft Kickoff code blocks page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3407085597/89357+-+Collaboration+Cycle+Kickoff+-+Code+Blocks) for our operational docs
- [x] Created a [Draft Staging Review page for Platform Website](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3407085570/89357+-+Platform+website+Staging+review), to be published in the next sprint

**Comment by allison0034** [comment]
@erinrwhite everything looks good, I made one comment about italics on Draft Staging Review page for Platform Website.

Quick question about  Draft Kickoff code blocks page, should the Kickoff moderator doc change also since you are moving the code blocks out of that page?

**Comment by erinrwhite** [comment]
@allison0034 the [code blocks page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks) is already separated out from the [kickoff moderator doc](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Admin+Tasks) 👍🏻  that's a fresh change, though - happened last sprint.

Updated the SR page to not use italics too. Unless you object I'll close this one.

**Comment by allison0034** [comment]
Good to close! TY!

**Comment by erinrwhite** [comment]
thank you!
