### ISSUE TITLE
Update our Monthly Reporting Automation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#8814]
## User Story or Problem Statement
As DEPO, I need to have updated monthly VA.gov metrics so I can easily report VA.gov's successes.

## Goal
Create separate Domo reports for each recurring monthly request so that we can 

## Objectives or Key Results this is meant to further
Customers use qualitative and quantitative user data to build and iterate on VFSs.

---
## Tasks
- [ ] Create an automated VEO dashboard
- [ ] Create an automated OMB dashboard
- [ ] Create an automated Digital Modernization Council dashboard

*Can we pull these dashboards as "subpages" in Domo so they're organized?

## Acceptance Criteria
- [ ] VSP can _easily_ pull each monthly report for the respective stakeholder in a timely manner without a single source of failure
---
## Additional Issue Resources

OMB Metrics: #8021
    - Adding Status System Status to the OMB Metrics #6758

Specific requirements for each dashboard in comments below.

**Comment by joanneesteban** [comment]
# Additional Info

- Ensure each report is titled with "VA.gov" metrics and the month they are referring to. Each report goes to a different audience, but essentially all show the "success" or "performance" of VA.gov.
- Enable an easy way to add annotations or summary that Insights can easily edit to explain the latest metrics
- Think of potential other metrics that show the success of VA.gov, including the difference between pre-modernization and post-modernization.

## OMB:

- Year over Year view
- Access to Chris J
- Due COB the first Monday of each month

**Metrics:**

- [ ] Total users
- [ ] Total Burials Submission
- [ ] Unique Log-ins (DSLogon, ID.me, and MHV)
- [ ] Total Claims Status Views
- [ ] Customer Satisfaction
- [ ] System Status
- [ ] HCA Submissions
- [ ] 526 Claim Submissions

## Digital Modernization Council:

- Year over Year view
- Access to Chris J
- Due COB the 8th of each month

**Metrics:**

- [ ] Total users
- [ ] Total Burials Submission
- [ ] Unique Log-ins (DSLogon, ID.me, and MHV)
- [ ] Total Claims Status Views
- [ ] Customer Satisfaction
- [ ] HCA Submissions
- [ ] 526 Claim Submissions

## VEO

- 13 month view
- Access to Lacey
- Due COB the 8th of each month

**Metrics:**

- [ ] Total users
- [ ] Total Burials Submission
- [ ] Unique Log-ins (DSLogon, ID.me, and MHV)
- [ ] Total Claims Status Views
- [ ] Customer Satisfaction
- [ ] HCA Submissions
- [ ] Ed Benefits

**Comment by joanneesteban** [comment]
@amycesal (Not urgent, we can figure this out when we're figuring out our dashboarding infrastructure), would we be able to add these 3 as sub-pages or group them together in some way?
