### ISSUE TITLE
Update VFS-facing guidance re: CMS

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88169]
## User Story
As a VFS team member, I want to be made aware of the new CMS touchpoint so that I can engage in it if it makes sense for my team.

Assignee: @allison0034
Peer Reviewer: @erinrwhite

## Description
In order to bring in CMS as a touchpoint into the Collab Cycle, we need to update all VFS-facing guidance within the Collab Cycle where CMS needs to be introduced. In addition to adding the new question CMS defined to the list of questions at kickoff, we also need to update pages where CMS will be mentioned. 

**Note**: a new touchpoint page for CMS will be created, however the content of the page will be determined and written by the CMS team. See [Integrate CMS into the Platform Collab Cycl](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18337)e for reference. This is where the new question at kickoff can be found. Will publish with #88170.

## Impacted Artifacts

- [Collab Cycle Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/overview)
- [Collab Cycle Kickoff Request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff)
- [Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)
- [Collaboration Cycle Request YAML template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)
- [Swimlane diagram](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2710864175/Collaboration+Cycle+Swim+Lanes+Diagram) (added to scope on 7/30)

## Tasks

For the Collab Cycle Kickoff Request page and the Collab Cycle Request YAML template, please coordinate with the assignee for ticket #88162 so that there is only 1 draft page and 1 PR with changes for scheduling and for CMS included in both.
- [x] Create draft version of the impacted artifacts
- [x] Add the CMS question to the kickoff request page
- [x] Add CMS to the Contact Us page
- [x] Add CMS as a practice area in the overview page. 
   - maybe spell out the acronym? Content Management System
- [x] In the YAML template, add the CMS question so that it aligns with what is on the Platform Website kickoff page

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have created draft pages of all Platform Website pages impacted by the addition of the CMS touchpoint
- [x] We have created a pull request for the collab cycle request YAML template that includes the new CMS kickoff question

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Created a draft of Copy of [Collaboration cycle kickoff request ](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3318710287/Copy+of+Collaboration+cycle+kickoff+request)and let Ian know location of draft pages.

**Comment by allison0034** [comment]
@gracekretschmer-metrostar do you know who I can put down as a POC for CMS on [this page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3318710305/Copy+of+Contact+us+2)?

**Comment by allison0034** [comment]
Created PR for yaml template. #89012

**Comment by erinrwhite** [comment]
@allison0034 [the YAML template is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml) - the PR you linked to is for an older document that probably needs to be removed!

**Comment by erinrwhite** [comment]
@allison0034 For the question for VFS teams in the template, we might need to provide more information about what we mean by VA editor:

Current text
> 7. Will a VA editor notice this change?

What if it was something like:
> 7. Will content editors using Drupal notice this change?

Grace might have a recommendation here too.

**Comment by shiragoodman** [comment]
The VA editor question info _can_ and likely _should_ live on the new CMS touchpoint page.

**Comment by erinrwhite** [comment]
thank you @shiragoodman I should have finished reading the ticket! So should the YAML ticket be updated with [all three of these questions](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3092447277/CMS+Platform+Collab+Cycle#CMS-specific-Questions-for-Intake-Form%3A)?

**Comment by shiragoodman** [comment]
@erinrwhite no, we decided with the CMS team that the follow up questions will be communicated on their end... no need to include them in kickoff.

**Comment by allison0034** [comment]
New PR is #89146

**Comment by allison0034** [comment]
Yes @erinrwhite , it isn't quite ready for your review... this is still a WIP. : ) Good point for the description.

**Comment by allison0034** [comment]
Tagged Grace in [Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1722009156291039).

**Comment by MDomngz** [comment]
@allison0034 thank you for helping get our ducks in a row. 

The POC set for CMS Collab-Cycle - 

- Product Manager: Grace Kretschmer Tran
- Design: Marisa Dominguez
- Accessibility: Steve Rancour
- Quality Assurance (QA): Jon Keister

cc: @gracekretschmer-metrostar

**Comment by allison0034** [comment]
Added POC to contact us draft

**Comment by shiragoodman** [comment]
@allison0034 I realized late on Friday that we forgot to include the[ swim lane diagram](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2710864175/Collaboration+Cycle+Swim+Lanes+Diagram) in this list of VFS-facing guidance. How quickly are you able to act on that? Please lmk. If you can act quickly, I'll adjust the scope of this ticket. Otherwise, I'll create a new ticket for the upcoming sprint. Thank you!

**Comment by allison0034** [comment]
@shiragoodman I will work on it today. We still need a link form the CMS team which I may have today. I also need a small blurb for the description, I am reaching out today.

**Comment by MDomngz** [comment]
@allison0034 can we please add these folks to our POC list? 

Engineering: Tim Cosgrove
DevOps: Tyler Bird

TY!!

**Comment by allison0034** [comment]
@erinrwhite all drafts are in [this folder](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3318087727/Allison+Ian+scheduling+and+CMS+pages) and ready. I still need to update the swim lanes.

**Comment by erinrwhite** [comment]
@allison0034 Draft docs are looking good!

**Comment by allison0034** [comment]
@erinrwhite [swim lane](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713545938981/37e39668eee6d6756e56b687f9c7851632340258?sender=u870c8d9c6b47768924793768) is ready

**Comment by allison0034** [comment]
All drafts moved and waiting to publish on Platform Website.

**Comment by allison0034** [comment]
Doh! @erinrwhite thank you!

**Comment by allison0034** [comment]
@erinrwhite am I good to close?
