### ISSUE TITLE
Update VFS-facing guidance for scheduling and kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88162]
## User Story
As a VFS team member, I want to know how to notify Collaboration Cycle/Governance team that I am ready for a Kickoff so that the Governance team can take the appropriate action.

As a VFS team member, I want to know how to schedule a CC touchpoint so that I can meet with Governance team and get feedback on my teams product.

Assignee: @it-harrison
Peer Reviewer: @erinrwhite

## Description
With the change in our Slack workflow for kickoff and touchpoint scheduling, the VFS-facing guidance on Platform Website and within the Collab Cycle Request ticket needs to be modified. The purpose of this ticket is to get those guidance docs updated and ready to go. We will not be publishing the changes within this ticket. Changes will be published in ticket #84496.

## Impacted Artifacts

- [Collab Cycle Kickoff page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff)*
- [Design Intent touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)
   - review what Erin did for the current MPR touchpoint page. Maybe we should just copypasta this guidance for DI? and for SR?
- ~~[Design Intent short video](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)~~
   - note: There is 1 line in this video that tells the VFS team they must inform us of the Calendly event in Slack. Instead of re-recording the whole video, is there a way we can just cut that out? Maybe add in a correction?
- [Midpoint Review touchpoint page ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)????
- [Staging Review touchpoint page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
- [Staging Review short video](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)
   - note: I _think_ this video is good as is however please watch the video and note if any of the scheduling guidance is incorrect and need of an update.
- [Collaboration Cycle Request YAML template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)*
- DI, MPR and SR code blocks on [Collab Cycle Kickoff - Moderator Responsibilities page ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)*
   - note: once the language here has been updated and approved, please share with @it-harrison so that he may update the script written in ticket #84495. The script should NOT be executed after being updated.

## Tasks
For the Collab Cycle Kickoff Request page, please coordinate with the assignee for ticket #88169 so that there is only 1 draft page with changes for schedule and for CMs both included.

- [x] Create documentation draft pages for all Platform Website/Confluence pages
- [x] Create pull request for the yaml template
- [x] Modify the scheduling guidance to remove the "Notify the Collaboration Cycle team of this event by using the /Collab Cycle XXX "slash-command" in your team channel. Provide information as prompted by the Slack workflow."
   - Should we add a line communicating to the VFS what to expect after scheduling in Calendly? or after submitting the kickoff ticket?
- [x] For the DI video, notify Shira if the change can be made easily. If not, the video updates can be pulled from scope of this ticket and handled in a separate ticket. Same for the SR video, if necessary. 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] All VFS facing guidance has been updated to reflect the new scheduling workflow
- [x] No changes have been published to Platform Website and all remain in a draft state

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@it-harrison [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3318087710/Allison-Ian+CMS+and+scheduling+pages) is a folder to put any drafts that overlap in.

**Comment by allison0034** [comment]
@it-harrison [here is the pull request](https://github.com/department-of-veterans-affairs/va.gov-team/pull/89012) for the yaml template.

**Comment by it-harrison** [comment]
@erinrwhite this is ready for review
* [draft of updated VFS collab cycle kickoff request document](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3318710287/Copy+of+Collaboration+cycle+kickoff+request)
* [draft of updated VFS Design Intent guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3327394287/Copy+of+Design+intent+88162)
* Midpoint does not need updating
* [draft of updated VFS Staging Review guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3328966657/Copy+of+Staging+review+88162)
* [commit to collab cycle template PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/89146/commits/656f9c1742e96f5f0e54f36d7a4d9e1ea9260087)
* [updated code blocks](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3334537242/Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+88162)

**Comment by shiragoodman** [comment]
@erinrwhite great suggestions. And thank you for the reminder on the last updated date. I haven't built up the habit with that one, yet!

**Comment by shiragoodman** [comment]
@it-harrison please post a status update by EOD - ty!

**Comment by it-harrison** [comment]
@erinrwhite all guidance docs updated as per your suggestion...I am holding off on updating the date since the pages will not be published as part of this ticket.

**Comment by erinrwhite** [comment]
@it-harrison docs are looking good!

What about this last item on the task list?

> - [ ] For the DI video, notify Shira if the change can be made easily. If not, the video updates can be pulled from scope of this ticket and handled in a separate ticket. Same for the SR video, if necessary.

**Comment by it-harrison** [comment]
@erinrwhite for the DI video I believe @KKitagawa-Bosch has the ability to modify the video and that @shiragoodman is going to assign it to him in an upcoming sprint

@shiragoodman as far as the SR short video, it's good as far as the audio - it does include a screenshot of the soon-to-be-obsolete instructions for the VFS team to schedule via the Slack command. I don't think this requires modification though.
