### ISSUE TITLE
Update Operational guidance for scheduling and kickoff per research findings

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88161]
## User Story
As a Governance team member supporting the Collaboration Cycle, I want to ensure the guidance my team follows is up to date and accurate per our new workflows so that all touchpoints are scheduled consistently.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @briandeconinck 

## Description
In ticket #86775 Governance team tested 4 new workflows associated with the kickoff, DI, MPR and SR. VFS teams shared their feedback of the new workflow via Slack survey, and Governance team members also documented their feedback in the feedback section of the [Research Plan.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3301507204/Research+Plan+for+usability+testing+of+emoji+response+workflows+with+VFS+teams) The purpose of this ticket is to review both VFS and Governance feedback, document any proposed changes, and share with the Governance team via Slack. If Governance has no objections to the proposed changes, then we will make the proposed changes and update Governance operational docs to reflect the change in process.

## Impacted Artifacts

- Slack workflows
- [Managing Slack "slash command" workflows](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2750677091/Managing+Slack+slash+command+workflows)
- [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
   - Note: the code blocks in this doc have already been updated, but the steps Governance follows to complete the kickoff have not. Please hold off on making changes until the current documentation draft (via tickets #88162 and #88090 are published, aka the CMS touchpoint and Slack workflow changes have launched. Since it's just the operational steps that are out of sync, and not the VFS-facing guidance, I think it will be ok to launch with this doc not fully up to date.
- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)

## Tasks
- [x] Review VFS and Governance feedback on workflows.
- [x] Document (as a comment is fine) proposed changes to workflow and share with Governance team in #platform-governance-team Slack channel. Ask for full team sign off (via emoji response is fine).
- [x] Once team approves, implement proposed changes in Slack workflows. Be sure to remove survey.
   - If team does not approve, contact Shira for next steps
- [ ] Update the operational guidance to reflect the steps in the kickoff and touchpoint workflows
- [ ] Update the Team guidance on managing the slash command workflows 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance has made final changes to the Slack workflows for KO, DI, MPR and SR
- [ ] Operational guidance supporting the new workflows is accurate and up to date.

## Team Notification
- [x] Slack post on #platform-governance-team (for proposed changes approval from team - no need to post again once operational docs are updated)
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck I believe the workflows have all been changed, could you double check my work and I'll get started on the operational guidance in the meantime? Thanks!

**Comment by briandeconinck** [comment]
@KKitagawa-Bosch Workflows all look good to me!

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck 

Drafts of the [managing slash commands](https://vfs.atlassian.net/wiki/spaces/PPST/pages/edit-v2/3375267889?draftShareId=e9fae499-b98e-433d-9c69-4e197ebfdda1) and [moderator responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/edit-v2/3374809147?draftShareId=8074a2f7-d1cc-4547-af29-a88a8d3ad6e2) are ready for review! The scheduling docs were already updated (not sure by who) a few days ago and the lines about workflows were already removed, so those should be good to go already! 

I left one comment on slash commands with a question for you, and we should probably also change the title because they're no longer slash commands, any thoughts on a new title?

**Comment by briandeconinck** [comment]
@KKitagawa-Bosch Replied to your comment on the slash command one. For title, I think "Managing Slack workflows" would probably be fine.

Everything else looks great! I think you're good to close once you make those final edits.

**Comment by KKitagawa-Bosch** [comment]
Those edits have been made, and they've both been updated! Closing now.

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck 

Erin and I realized that we forgot to update the scheduling docs, so here are the links to those with info updated! 
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling
https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling
https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling
