### ISSUE TITLE
SOCKS Triage Documentation Update

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#88163]
## Description 
We would like to review and add any updates to the SOCKS triaging process in documentation. We need to update these two docs:

https://vfs.atlassian.net/wiki/spaces/PTST/pages/2829517026/SOCKS+Access+on+a+GFE
https://vfs.atlassian.net/wiki/spaces/PTST/pages/2633236495/SOCKS+Troubleshooting+Best+Practices

They should mirror our current best practices.
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Update best practices SOCKS doc
- [x] Update SOCKS access on a GFE doc
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
@AnthonyWFlowers Assigning this to you and you can ask @lindsay-insco or @bdech questions as you go. Putting into the backlog for now though!

**Comment by AnthonyWFlowers** [comment]
Updated Best Practices with a new error seen recently: "Connection timed out" 
Tested the best practice "things to try" and the steps still are relevant.

**Comment by AnthonyWFlowers** [comment]
Cross referenced GFE Guide with recent support requests.
Added information to clarify the "passphrase" portion of the GFE guide
added a step for creating the directory in GitBash to include a command to ensure you are in the home directory.

**Comment by alyssagallion** [comment]
Added a table of contents and formatted with blue H1 headers to keep our documentation consistent. Thanks! 

CC: @AnthonyWFlowers
