### ISSUE TITLE
Discovery Ticket: Research Checklist

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88178]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) contains links to Google Docs. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

## Tasks
- [x] Identify SME to provide guidance for this page
- [x] decide whether to remove, replace or otherwise redirect users toward a new source.
 
## Acceptance Criteria
- [x] Page is ready to be updated

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)
---
## Screen Shot:
![Selected July 11 2024 18:19:56](https://github.com/user-attachments/assets/701dcc83-5200-430f-a5b8-77ddea92d93a)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
![Selected July 11 2024 18:19:56](https://github.com/user-attachments/assets/701dcc83-5200-430f-a5b8-77ddea92d93a)

**Comment by jknipes** [comment]
@naomimarcussen please advise how to address these links

**Comment by naomimarcussen** [comment]
I've included links to these Google slide presentation templates in the #design channel canvas. We can refer them there to get the templates.

**Comment by jknipes** [comment]
The above solution has also been approved and endorsed by leadership. Page is ready to be updated.

**Comment by laucon** [comment]
Done

**Comment by jknipes** [comment]
Closing this issue as _Done_
