### ISSUE TITLE
Launch CMS touchpoint changes and announce to VFS teams

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88170]
## User Story
As a VFS team participating in the Collab Cycle, I want to be aware of new touchpoints in the process so that I can connect with those teams if recommended for my product.

Assignee: @allison0034 
Peer Reviewer: @erinrwhite 

## Description
Governance team is almost ready to launch changes to add CMS as an official touchpoint in the Collaboration Cycle. The purpose of this ticket is to publish all guidance and materials associated with the new touchpoint, as well as communicate changes to VFS teams.

Please coordinate with the assignee for ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/84496 as change announcements, change history posts and the publishing of shared drafts pages should be aligned.

Governance team is dependent on the CMS Request touchpoint page as well as the CMS github ticket for the completion of this ticket. Both of these artifacts have been created by the CMS Team. CC @gracekretschmer-metrostar 

### Platform website
- [Touchpoints page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints)
- [New CMS touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/cms-request)
- [Collab Cycle Overview](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/overview)
- [Contact Us](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/contact-us)
- [Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)

#### Drafts
- [New CMS touchpoint draft](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3339976899/CMS+Request+-+Overview)
- [All other drafts](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3318087727/Allison+Ian+scheduling+and+CMS+pages)

### Governance Team
- [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
- [Custom Tracks Flow](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1872822276/Custom+Tracks+Flow)
- [Swim lanes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1713545938981/37e39668eee6d6756e56b687f9c7851632340258?sender=u870c8d9c6b47768924793768)

#### Drafts
- GH kickoff templete [PR 89146](https://github.com/department-of-veterans-affairs/va.gov-team/pull/89146)
- [All drafts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3318087710/Allison-Ian+CMS+and+scheduling+pages)

### Slack announcement:
Attention: VFS Teams
A CMS touchpoint has now been added to the Collaboration CycleOn [xx/xx/xx]
If a team is making a change that a VA content editor may notice, the team will be directed to fill out a CMS request.
Documentation: CMS touchpoint (link to CMS touchpoint on PW)
Questions: Please post any questions in thread or reach out to the CMS Team at #sitewide-cms-platform

## Tasks
- [x] Draft change announcement following [Platform guidelines](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2290352129/Slack+Change+Announcement+format)
- [x] Draft [change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history) post for Platform Website
- [x] Hold sync with CMS team to walk through all artifacts for final review
   - Shira will schedule
- [x] Publish the CMS Request touchpoint page
   - content is the responsibility of the CMS team
- [x] Link CMS touchpoint in [Touchpoints page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3365732353/Copy+of+Touchpoints), change history, Slack announcement.
- [x] Ensure Last Updated date on all PW pages is updated to current date
- [x] Verify link to CMS Github ticket has been correctly copied into both the CMS Request touchpoint page as well as the code block for CMS Request
- [x] Merge PR for kickoff template
- [x] Publish all pages that were drafted in previous tickets

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have published our changes to the Collaboration Cycle to include CMS Request as a formal touchpoint
- [x]  We have notified VFS teams of the new touchpoint

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Change announcement draft...

Attention: CMS users
A CMS touchpoint has now been added to the Collaboration CycleOn [xx/xx/xx], CMS team will be added as a touchpoint in the Collaboration Cycle.
Any change that a VA editor (Drupal) may notice will be recommended to fill out a CMS request.Documentation: [Link to user guide, instructions, etc]
Questions: Please post any questions in thread or reach out to the Governance Team or CMS Team

**Comment by allison0034** [comment]
@shiragoodman I would love to get your opinion on the change announcement above and the [change history page for the CMS changes](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3350429697/Copy+of+Change+history+2).

**Comment by erinrwhite** [comment]
@allison0034 Rolling! I would include at least as much information on the change history page as we do in the Slack post (specifically adding the more detail about when the touchpoint will be recommended). 

Also - would it be **Attention: VFS teams**?

Last thing - grammar suggestion on this sentence:

> If a team is making a change that a VA content editor may notice, the team will be directed to fill out a CMS request.

**Comment by allison0034** [comment]
Updated both the change announcement and draft, how does that sound?

**Comment by erinrwhite** [comment]
Looking good! 2 questions:

- Where will we link to the new CMS page from the change announcement page?
- Should the Slack announcement be **Attention: VFS teams**?

**Comment by shiragoodman** [comment]
> @shiragoodman for
> 
> > Please coordinate with the assignee for ticket #84496 as change announcements, change history posts and the publishing of shared drafts pages should be aligned.
> 
> > 
> 
> Should the change announcements be 2 different announcements?

The change announcement on Slack can be 2 different posts, but the change history post should be 1 post with 2 bullets. [Like this post from April 22. ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history#Changehistory-April22,2024)

I am of the belief that the change history post should have more detail and lots of information for the VFS team, where the change announcement is more of a high level summary, pointing the VFS team to the change post where they can get more information, if needed.

**Comment by allison0034** [comment]
Thank you @shiragoodman ! @erinrwhite I am on the fence about using VFS teams, I don't want to alarm them thinking they have an extra touchpoint, this is only for CMS users. Maybe "VFS teams that use CMS"? Any suggestions?

As far as the link, I have not gotten that far yet. This is still a WIP.

**Comment by shiragoodman** [comment]
I think you should say Attention: VFS teams. it may not pertain to a lot of them, but there's no need to call out VFS teams that use CMS specifically. Plus I'd rather have a team see it and acknowledge it's not for them than have a team skip over it completely bc they think they're exempt.

**Comment by allison0034** [comment]
Capturing Erin's question suggestion: Are you building products/features in the Drupal content management system?

**Comment by shiragoodman** [comment]
@allison0034 as stated on the call with CMS team today, please be sure to create a draft [Touchpoints page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints) so that we can get CMS Request added. LMK if you have any questions - thank you!

**Comment by shiragoodman** [comment]
Final walkthrough with CMS team scheduled for Monday 8/12 at 11:30am ET.

**Comment by shiragoodman** [comment]
@allison0034 - 1 more thing. Can you please update the Impacted Artifacts section to include the PR for updating the YAML Collab Cycle Request ticket? I am not sure where the PR is so it would be nice to have it for easy reference. Please and thank you!

**Comment by allison0034** [comment]
@erinrwhite I know these docs have been reviewed but we meet with the CMS Team next week. Want to take one more peek? Look for "Drafts" under the artifacts section.

**Comment by erinrwhite** [comment]
@allison0034 quick note, this is [the correct PR 89146](https://github.com/department-of-veterans-affairs/va.gov-team/pull/89146) - the other erroneous PR #89012 should be closed

**Comment by erinrwhite** [comment]
@allison0034 

### Governance team docs
- A couple of comments on the [kickoff operational docs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3315073025/88090+-+Allison+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+2) including a new link for the CMS request ticket code block
- others good to go!

### VFS facing docs
- [CMS Request page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3339976899/CMS+Request+-+Overview) will need Last updated information, and the new link to the CMS request (both changes noted in comments)
- others good to go!
- Note for all pages: update the last updated date (I've been burned by this which is why I'm such a stickler now)

And collab cycle ticket pr is #89146, looking good - reviewed and approved, ready to squash and merge next week.

**Comment by allison0034** [comment]
Thanks @erinrwhite good on everything except this...

- A couple of comments on the [kickoff operational docs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3315073025/88090+-+Allison+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+2) including a new link for the CMS request ticket code block, based on the new ticket title and GH labels in the [CMS github ticket doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3353313399/CMS+Github+ticket)

I compared the link I have and it looks the same and goes to the same page. What am I missing?

**Comment by allison0034** [comment]
Thanks @erinrwhite , I made all changes except this...
A couple of comments on the [kickoff operational docs](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3315073025/88090+-+Allison+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+2) including a new link for the CMS request ticket code block, based on the new ticket title and GH labels in the [CMS github ticket doc](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3353313399/CMS+Github+ticket)

My link is the same as yours and title and labels look the same, or am I missing something?

**Comment by erinrwhite** [comment]
Weird! the link I pasted in the comment displayed one URL but linked to another 🙃 I'm sorry for the confusion but/and I think I fixed it!

The correct link should be: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=CMS+Team%2C+Needs+Analysis%2C+Epic&projects=&template=cms-collaboration-cycle-request.yml&title=CMS+Request+for+[Team+Name%2C+Product+Name%2C+Feature+Name]

**Comment by shiragoodman** [comment]
Update Slack change announcement to include CMS team Slack channel (#sitewide-cms-platform) and remove Governance.

**Comment by allison0034** [comment]
Made updates to New CMS touchpoint draft and moved it to be published.

**Comment by erinrwhite** [comment]
[CMS touchpoint page published!](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/cms-request)

**Comment by allison0034** [comment]
All other docs are waiting to be published.

**Comment by allison0034** [comment]
@erinrwhite ready for you!!!

**Comment by erinrwhite** [comment]
@allison0034 Platform website pages looking good! Good to announce changes to teams!
