### ISSUE TITLE
Edit Ticket: Research Checklist Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88173]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) contains links to Google Docs. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

### Screen Shot of links to Google slides:
> ![Selected July 11 2024 18:19:56](https://github.com/user-attachments/assets/9ec455c9-3ddf-4a13-9eca-b898401bbe68)

---
## Tasks
- [x] Replace the 2 links with directions pointing to the [**Canvas** in the #design channel in Slack ](https://dsva.slack.com/canvas/C0NGDDXME) where users can access the templates
- [x] Review changes with Naomi Marcusson for approval
- [x] Move page into deployment space
- [x] Check for LBs

## Acceptance Criteria
- [x] Page is ready for deployment

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)

## Discovery Ticket: 
[88178](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88178)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laucon** [comment]
Done

**Comment by jknipes** [comment]
Closing this issue as _Done_
