### ISSUE TITLE
Reassess the level of effort to update review instance provisioning to use the standard AL2 Image

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#88199]
## Issue Description
Reassess the level of effort to update review instance provisioning to use the standard AL2 Image

---
## Tasks
- [x] Update documentation around review image build and deploy
- [x] Determine if it is possible to update without impacting other Ansible AL2 deployments.

## Acceptance Criteria
 - [x] **Scenario: Reassess the level of effort for updating review instance provisioning**
  - Given the current documentation around review image build and deploy
  - When determining if it's possible to update without impacting other Ansible AL2 deployments
  - Then the level of effort should be reassessed based on the findings

**Comment by ben-allen-oddball** [comment]
Latest jenkins failure.
http://jenkins.vfs.va.gov/job/deploys/job/vets-review-instance-deploy/147554/console

**Comment by ben-allen-oddball** [comment]
Specific problem:

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/devops/blob/52bcf3c708f1fe7c62fdaf5a6ca1dc0b40be85b9/ansible/build/roles/common/base-os/tasks/amazon.yml#L93

**Comment by ben-allen-oddball** [comment]
99% there.  Because of the very old version of ansible we use some modules will never work on the AL2 base image.  So I am swapping out for shell commands which is very bad...

To make this better we would duplicate the ansible to a new repo, Use a new version and upgrade to modern modules.  This would be a significant effort.  But would allow for a complete refactor of the deployment.

**Comment by ben-allen-oddball** [comment]
Success.  It is up and running.  I just need to tweek the image discovery because the al2 images are short lived.

**Comment by ben-allen-oddball** [comment]
http://72e418898c4bff41650f88b279af2aed-api.review.vetsgov-internal/

**Comment by ben-allen-oddball** [comment]
http://72e418898c4bff41650f88b279af2aed.review.vetsgov-internal/

**Comment by ben-allen-oddball** [comment]
Remaining efforts:
* Why cleanup happens early on these instances
* Solve Legacy Ansible Image discovery issue
