### ISSUE TITLE
DMC request for Alert Banner for Chapter 33 Debts 2/3

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#88191]
## Description

The transition is ongoing and DMC is getting caught up but it's taking longer than expected.

As a result DMC would like to remove the sentence about contacting DMC for the time being.  They are asking that we remove "If you believe... to ... 07/12/2024"

The original work was in ticket #[86976](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/86976)

[Here's the mockup](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=2245-30022&t=ZdCkMZPhLpCjyE1g-11), need to use the slim warning alert:
<img width="705" alt="Screenshot 2024-06-26 at 1 49 39 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/d584dce7-1f69-4fd9-82bc-6b18017eb779">

Here's the code snippet: 

```
  <va-alert
    class="vads-u-margin-bottom--2"
    close-btn-aria-label="Close notification"
    disable-analytics="false"
    full-width="false"
    slim
    status="warning"
    visible="true"
  >
      <p className="vads-u-margin-y--0">
        VA is transitioning to a new system for processing Post 9-11 Chapter 33 financial transactions. Due to this transition, Chapter 33 debt balance information may not reflect recent payments you have made by check, credit card, or ACH. If you believe your Chapter 33 debt balance does not reflect recent payments, we encourage you to contact the Debt Management Center: at  <va-link
      href="https://ask.va.gov/"
      text="ask.va.gov"
    /> or call  <va-telephone
    contact="800-827-0648"
  />, after 07/12/2024. Your payment will not be considered late and will reflect the date received once system updates are completed. This message only applies to Post 9-11, Chapter 33 debts.
  </va-alert>
```

## Tasks
- [x] Update the text
- [x] Save the current version for reimplementation in the future (Ticket #[88192](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88192))

## Acceptance criteria

- [x] The text is updated

## Testing
- [x] N/A if non development work
- [x] Testing passed and documented in this ticket

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>
