### ISSUE TITLE
Require Backend review on PRs

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88204]
## User Story
As the developers and managers on the Platform,
We need to implement the GHA workflow 
So that we will have a consistent backend review process and avoid potential deploy blockers.

## Issue Description
See the Slack thread [here](https://dsva.slack.com/archives/CBU0KDSB1/p1720718385180709) from DSVA. 

We have been waiting for the bandwidth to change the conveyor belt to prod flow before adding be-review-group to the team PR approvals. However, a change was released to prod that logs sensitive data to Datadog (and the overall design was poor). It's in the vye module, so it didn't require code review. These kinds of releases need to be avoided; it would be best to implement the GHA workflow and ensure a consistent backend review process. 

## Tasks
- [x] Implement the GHA workflow
- [ ] Test after implementation
- [ ] Document process and any exceptional notes or things for other teams to watch out for
- [ ] Communicate these changes to VFS teams
- [ ] After workflow is implemented, revert the work done in https://github.com/department-of-veterans-affairs/vets-api/pull/17537

## Success Metrics
- [ ] All* PRs require a backend review group approval 

## Acceptance Criteria
- [ ] There will be a more consistent and smooth approval process, ensuring that things are not missed. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

*Not all PRs, This process is not required for all Identity, Mobile, Lighthouse PRs

**Comment by rmtolmach** [comment]
Exceptions to requiring a review from backend-review-group: identity, mobile, and lighthouse.

**Comment by jennb33** [comment]
7/25 update: Per @rjohnson2011 this is moving forward. We need to make a GHA that requires feedback and possibly group approval on all PRs minus identity, mobile and lighthouse.

**Comment by jennb33** [comment]
7/29 update: @rjohnson2011 has the GHA written out, now we need to review it with VFS teams.
