### ISSUE TITLE
Publish socks / jumpbox sync image in a dedicated repo

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#88214]
## Issue Description
Update, publish, document and automate the build and deploy of the user sync docker image for Jump Boxes and Socks proxy syncing.

---
## Tasks
- [ ] Publish Docker Image
- [ ] GH Action to build and publish image
- [ ] Document details and manual process
