### ISSUE TITLE
[CST][ENG]: Add required prop to the checkbox on the Document Request page for tracked items that are a 5103 Notice

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#88219]
## Value Statement
**_As a_** Veteran
**_I want to_** understand which fields are required on a form
**_So that_** I can fill them out without errors

---
### Bug

Based on this [conversation in the Figma file](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1?node-id=2131-2763#866309601), and a [related ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87336), we need to add "required" to the label for the "I’m finished adding evidence to support my claim." checkbox on the "Review the list of evidence we need" page. [Check out the design files](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=2131-2763&t=P4x91wJn0o539vud-0).

## Engineering Notes
- [x] Add the required prop to the checkbox on `Automated5103Notice.jsx`
- [x] Add unit test

## Tasks
- [x] Add required to label

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Required is added to label

**Comment by samcoforma** [comment]
Note to self: there is a prop to add "required"
