### ISSUE TITLE
Design validation to prevent duplicate service periods 

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#88216]
## Issue Description
From [Toxic Exposure 1.0: Validation issues - Remove duplicate service periods#87717](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/87717), design front end validation to prevent the Veteran from entering duplicate service periods.

---
## Tasks
- [ ] Get definition on business logic for what exactly we want to prevent (exact duplicates including branch? any branch with same start and end dates? any overlap in dates?)
- [ ] Design validation message(s)
- [ ] Relay proposed design to OCTO
- [ ] Get OCTO signoff
- [ ] Create / adjust implementation ticket as needed

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by mengA6** [comment]
[Discussion in Slack](https://dsva.slack.com/archives/C04KW0B46N5/p1720800562299269)

**Comment by pacerwow** [comment]
Just noting here that I wonder if it's more efficient to think about this work as part of #[84305](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/84305), since we're looking at date range validation in scope of that ticket anyway.
