### ISSUE TITLE
Burial | Usability Testing Research

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88225]
## Issue Description
Our team launched a new version of the form in May 2024, so it’s now in parity with the paper form. We want to uncover any problems and opportunities for enhancement that the current claimants face when filling out the new Burial Benefits form.

Method: Moderated usability testing, remote 
Research lead: Fiorella Geedi
Focused users: Non-veterans, Veterans, VSOs and VSRs
Research Timeline: 7/22 - 9/6~

## Key links
- Research plan: [Non-veterans and Veterans](https://docs.google.com/document/d/1fsXQr2tAzxnE_TkpYP0Z-camLkQmiESY4iH0lSBdjrQ/edit)
- Conversation guide
- Findings report
- Study Mural link

---
## Tasks
- [x] Create a research plan 
- [ ] Consult with trauma-inform experts 
- [ ] Recruitment + planning 
     - [ ] Create recruitment ticket: [Github](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=sstrassberg&labels=recruitment-criteria&template=recruitment+criteria.yaml&title=%5BRecruitment+Request%5D%3A+YYYY-MM+name+of+your+study) | [Recruitment checker for equality (https://docs.google.com/spreadsheets/d/1CCTyhF85QewEzp1CRQgM1_Nd7EN9D2RTqga3OA8vmDI/edit?gid=0#gid=0)
     - [ ] Create screener questions
     - [ ] Create conversation guide word and Github
     - [ ] Learn how to access Perigean's Zoom account
- [ ] Research
     - [ ] Create a sign-up sheet for notetakers and observers
     - [ ] Send meeting invites
     - [ ] Schedule debrief sessions 
- [ ] Synthesis
- [ ] Create a shareout of findings 
- [ ] Decide which recommendations to create as tickets on Github

## Acceptance Criteria
- [ ] Usability testing plan
---
