### ISSUE TITLE
Burial | Turn on GA for Relationship Type

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88231]
## Issue Description
_In order to better understand who is filling out the application for burial benefits form, we need to collect analytics for the "relationship to Veteran" and "types of costs" questions._

<img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1827715d02b31ae00f0fa39daa2658df4a3fb429/image.png" alt="image.png" />

<img width="458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8c40e37948643d7ff7f5761ef54a0f8e84966f6/image.png" alt="image.png" />

---
## Tasks
- [ ] Enable google analytics for the "relationship to Veteran" radio component
   - See guidance [here](https://dsva.slack.com/archives/C1Q4294JJ/p1720796381419759?thread_ts=1720793518.358369&cid=C1Q4294JJ) and [here](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/design-system-components#DesignSystemComponents-SensitiveFormComponents)

## Acceptance Criteria
- [ ] GA collected for the "relationship to Veteran" question
- [ ] GA collected for the "types of cost" question
---

**Comment by steele-lm** [comment]
Closing as a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/122252
