### ISSUE TITLE
Medallia change request - Turn off A11y intercept survey on Appointments URLs

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#88239]
## Issue Description
This is a request to turn off the Medallia intercept survey on the following Appointment URLs:

```
https://va.gov/my-health/appointments/schedule/type-of-care
https://va.gov/my-health/appointments/schedule/audiology-care
https://va.gov/my-health/appointments/schedule/sleep-care
https://va.gov/my-health/appointments/schedule/eye-care
https://va.gov/my-health/appointments/schedule/facility-type

https://va.gov/my-health/appointments/schedule/location
https://va.gov/my-health/appointments/schedule/how-to-schedule
https://va.gov/my-health/appointments/schedule/clinic
https://va.gov/my-health/appointments/schedule/preferred-date
https://va.gov/my-health/appointments/schedule/date-time
https://va.gov/my-health/appointments/schedule/reason
https://va.gov/my-health/appointments/schedule/contact-information
https://va.gov/my-health/appointments/schedule/review

https://va.gov/my-health/appointments/schedule/va-request/
https://va.gov/my-health/appointments/schedule/va-request/reason
https://va.gov/my-health/appointments/schedule/va-request/preferred-method
https://va.gov/my-health/appointments/schedule/va-request/contact-information
https://va.gov/my-health/appointments/schedule/va-request/review

https://va.gov/my-health/appointments/schedule/community-request/
https://va.gov/my-health/appointments/schedule/community-request/closest-city
https://va.gov/my-health/appointments/schedule/community-request/preferred-provider
https://va.gov/my-health/appointments/schedule/community-request/preferred-language
https://va.gov/my-health/appointments/schedule/community-request/reason
https://va.gov/my-health/appointments/schedule/community-request/contact-information
https://va.gov/my-health/appointments/schedule/community-request/review
```

---
## Tasks
- [ ] Turn off a11y intercept survey on all urls
- [ ] QA a11y intercept survey on all urls to confirm 

## Acceptance Criteria
- [ ] A11y intercept survey does not pop up on the listed urls
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aubreyarcangel** [comment]
Request submitted via EMD Intake Form.

Ticket # 6DAD649

**Comment by ATMiddleton** [comment]
The request has been approved, however, VSignals team has not assigned to a Sprint.  They have 3 week sprints and should schedule shortly.

**Comment by aubreyarcangel** [comment]
Brian Brown has approved this work, but the VSIgnals team has not scheduled this into any future sprints yet.

**Comment by ATMiddleton** [comment]
Scheduled for October.

**Comment by clantosswett** [comment]
Not seeing any updates here but I'm assuming this should be closed?

**Comment by ATMiddleton** [comment]
@aubreyarcangel will discuss with Galen as some of the URLs are still receiving data when the URLS are supposed to be excluded.

**Comment by clantosswett** [comment]
@aubreyarcangel what is the update here? Has this been completed? If yes, can you please update the ticket and close?

**Comment by ATMiddleton** [comment]
Incomplete - will discuss with VSignals 1/22/25

**Comment by ATMiddleton** [comment]
Met with VSignal team and forwarded to Brian Brown the outstanding URLs that require removal of A11y surveys. 

@aubreyarcangel will follow up with VSignals to completion.

**Comment by ATMiddleton** [comment]
VSignals stated that this work is scheduled for the month of March.

**Comment by ATMiddleton** [comment]
@aubreyarcangel will verify in staging.

**Comment by ATMiddleton** [comment]
Verified in Live feed & Search that all the sitewide A11 is no longer firing on any of the URLs in the exclusion list.

This ticket is complete.
