### ISSUE TITLE
Edit Ticket: Research Checklist

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88249]
## Issue Description
Government and VA users cannot view links to Google Drive on their work computers. 
Our links need to be viewable by all users. Therefore, we do not link to Google Drive on the Platform Website.
The PW page [Research Checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) contains links to Google Docs. 
Content Team needs guidance from a SME to decide whether to remove, replace or otherwise redirect users toward a new source.

Discovery Ticket: 
88178 
---
## Tasks
- [ ] Replace the 2 links with directions to the **Canvas** in the #design channel on Slack, where users can access the templates
- [ ] Review updated page with SME
- [ ] Move page into deployment space
- [ ] Check for LBs

## Acceptance Criteria
- [ ] Page is ready for deployment

## Google Drive links found on PW pages
[HERE](https://docs.google.com/spreadsheets/d/1viaO29qr60xVNYuj20RnvhMGbuP5T_ttPjSC_slybpg/edit#gid=0)
---
## Screen shot of links:
<img width="866" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8d463fe9f82dc2b6075d1032590994962fef8ce/Selected%20July%2011%202024%2018-19-56.jpeg" alt="Selected July 11 2024 18-19-56.jpeg" />

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/88249?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by BSmolensky** [comment]
Upon Further Review: this ticket has been recategorized as an EPIC and moved to the Future Initiatives Column.

**Comment by BSmolensky** [comment]
Work on this epic should include: 

- [ ] Dividing the PW up into small, manageable sections
- [ ] Then Assigning each PCT member a select number of pages within that section of the PW to review. 
- [ ] Spreadsheet should be created to track results
- [ ] New Tickets Created to fix pages that need fixing. 
- [ ] Repeat process until all 550+ pages on the PW have been reviewed and fixed

**Comment by BSmolensky** [comment]
**NOTE**: This Epic is labeled "Low Priority" because if we are going to review every page on the PW, we should probably review them for EVERYTHING. This Epic will likely become part of a much larger epic wherein we perform a full content audit of every page on the PW. Such an audit will likely involve several other teams. As we are finding out with the ESI audit (a very small corner of the PW), some pages will need archiving as they are no longer in active use. That will require working with SMEs and, likely, entire teams. A full PW audit, should we decided to take it on, would a major, collaborative, group effort that will need to be broken down into very small, manageable parts.
