### ISSUE TITLE
Appoint a Rep - Cross Accredited VSOR - User Test - Kick-off

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#88248]
## Issue Description
Interviews and user test of the 21-22 with cross accredited VSORs.

## Tasks
- [ ] Ideation workshop with ARF designer/research team
- [ ] Ideation workshop with ARM team
- [ ] Generate themes and questions for test plan

## Acceptance Criteria
- [ ] All tasks complete.

**Comment by jfinnerty13** [comment]
Anything I should add or change for Friday @mtri @oddball-lindsay ?
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721134693026/fea1769a7de6a15f29b3333cfa8ba86aad0b7f68?sender=u36b374887f74c9a3de2d0750
