### ISSUE TITLE
Q3 2024 Platform Content Team Tech Debt

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88259]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Platform Content Team member, I need to solve outstanding tech debt issues so I can remove impediments for users of Platform Website.

As a user of Platform Website, I need to successfully navigate Platform Website so I can find the information I need

As a member of the Leadership Team, I need to be able to know that Tech Debt issues have been resolved so I can recommend Platform Website as a source of truth to VFS Teams and OCTODE

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done

- [x] va.gov hyperlinks researched
- [x] audit for links in page headers
- [x] audit for personal names that should be replaced with departments, teams or positions

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by jknipes** [comment]
Audits completed, closing this epic
