### ISSUE TITLE
QA Test Plan to Finalize Remaining Domo Datasets 

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#88255]
### Description
This is designed to create a more formalized data QC testing plan, that will allow us to clearly identify the remaining issues with datasets 

Things to incorporate and what to test for:
1. **Volume** -- ensuring the volume is in the right ballpark
2. **Expected key/utilized attributes** are present in GA4 data, with how it's being consumed in Domo.
3. **Metric counts** identifying any discrepancies, determining the cause of the discrepancy and either find a solution or be able to explain discrepancies.

**Note:** If need to review in meetings throughout the sprint, have the following prepared:
- Well-defined agenda/topics to cover, what datasets/dashboards are we looking at
- What needs to be asked? 
- Do changes need to be made?
- If something is off (metric count, metric values, etc)-- what information can we provide on it?

### Tasks

- [x] Create QA test plan for outstanding QC/QA items.
- [x] Use criteria from test plan to indicate when remaining Domo datasets as 'Ready' for GA4 appends.
- [x] Mark completed datasets are marked as _**Ready**_ on [this document](https://vfs.atlassian.net/wiki/spaces/AT/pages/3213885442/GA4+Migration+Domo+Dataset+Updates).

---

### Acceptance Criteria

- [x] QA Test Plan has been created
- [x] Outstanding Domo datasets are fully QC'd
- [x] Datasets are ready for appended GA4 data

**Comment by Blivaditis** [comment]
Mid sprint update for this card, the new QC process is going well. Significantly more datasets have been marked as ready to append ([link](https://vfs.atlassian.net/wiki/spaces/AT/pages/3213885442/GA4+Migration+Domo+Dataset+Updates)), while all of the datasets marked as not ready have a open issue which can be found [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/edit-v2/3318775809).

FYI @johnny-jesensky-adhoc @ChristineYoungZA @dorseypa1

**Comment by Blivaditis** [comment]
End of sprint update for this card:
A majority of datasets have now been marked as ready to append, we are still waiting to append 6 data sets ([record](https://docs.google.com/spreadsheets/d/1mIsJEM5sQFVi8lWIMI6eRiOUQUwO9wdVjjsBis0QqXY/edit?gid=884424480#gid=884424480)). There are a few open issues we are still trying to solve which can be found in our [confluence document. ](https://vfs.atlassian.net/wiki/spaces/AT/pages/3318775809/Round+3+Domo+Data+QC+Checks)

**Comment by Blivaditis** [comment]
There will be a new card to track the final parts of this task, along with a new card to re QC appended datasets.
