### ISSUE TITLE
Analytics & Insights: BigQuery Cost & Processing Optimization

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#88292]
## Epic Description
Our team has managed our BigQuery account, and have historically been the ones to monitor the costs incurred via our consumption model of bytes processed.

The largest cause for high unexpected costs have come from the Flagship Mobile Looker report.

A more comprehensive overview of problem, and our progress can be found in our most recent demo deck.

- [Optimizing Mobile Team’s Looker Report](https://docs.google.com/presentation/d/1t0zGCorH-z1DD_muf3Ct5NBRq02GAAxlEYFyTA8wJb8/edit#slide=id.p)

### Status:
| Date | Status | Launch Date  | Notes |
| ----- | ------ | ------------------------- | ------ |
| 8 November 2024 | _In Progress_ | August 2024 - On Track | We've seen notable cost savings for the last 30 days, as we have finished implementing the first phase of changes. We are continuing to wrap up Phase II enhancements to the report. |
| 17 October 2024 | _In Progress_ | August 2024 - On Track | Velocity is dependent in part on Mobile Team to implement our recommended changes.|
| January 2024 | Completed | August 2024 - On Track | This work was completed late 2024 -- closing. |

### High Level User Story
As a member of the Platform Analytics & Insights Team, I want to improve the efficiency of queries that generate processing costs in BigQuery, so that we can lower our monthly costs, and ensure reports that use BigQuery data are performant.

### Hypothesis or Bet
If we devote time to optimizing jobs run by the Flagship Mobile Looker report, our BigQuery costs will dramatically go down, while also improving the experience for report consumers, using the report.

### OKR
1. Our platforms are the best way to deliver products at VA.
- Our platforms measure and improve the satisfaction of their internal users.
- Our platforms power twice as many interactions compared to last year.

### We will know we're done when... ("Definition of Done")- 

- [x] BigQuery monthly costs have been reduced.
- [x] Flagship Mobile Report continues to be functional, with a higher performance (faster processing time for jobs it runs).
- [x] Improvements have been quantified and documented.

---

### Launch Date
August 2024

### Projected End Date
November 2024

### How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
