### ISSUE TITLE
PgHero monitor and support for slow queries

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88315]
## User Story
As the managers and developers for the Platform,
We need to monitor and provide support for the 6 remaining slow queries, 
So that dependent teams can remediate the issues and the PgHero tool will work as designed. 

## Issue Description
PgHero (http://pghero-prod.vfs.va.gov/) is reporting some slow queries.
![image](https://github.com/user-attachments/assets/2e502ecc-a77c-41e0-9771-62712dc7f838)

We would like to manage the slow queries and fix the low-hanging issues, then delegate anything that needs a bigger lift to the owning teams. 

## Tasks
- [x] investigate the slow queries in PgHero and determine level of effort to mitigate
- [x] Fix issues or pass along findings to relevant teams
    - [x] Link conversations, tickets, or PRs as comments in this issue.

## Success Metrics
Slow queries are mitigated and solved. 

## Acceptance Criteria
- [x] Teams have been notified
- [x] links to slack threads or tickets created from this are linked in the comments of this issue
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
The `vba_documents_upload_submissions` query is the slowest of the bunch. There has been an effort to speed up this query before. In 2021 https://github.com/department-of-veterans-affairs/vets-api/pull/8320 by Trevor and more recently by Ryan https://github.com/department-of-veterans-affairs/vets-api/pull/17377 and it looks like the owning team tried to improve it as well in this commit https://github.com/department-of-veterans-affairs/vets-api/commit/873f9fb0fbe0ac0cdb0cada99ad86db26f066487 from last year. I think [this is where it’s called](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/app/sidekiq/vba_documents/upload_remover.rb#L24-L25) in vets-api. Based on the commit history of the vba module, Lighthouse are the owners. I have reached out and am waiting to hear back. 

Steve Albers is from Benefits. Form 526 is the disability benefits form. Steve created a Datadog Dashboard [Benefits - sql performance](https://vagov.ddog-gov.com/dashboard/f4u-52t-9jx/benefits---sql-performance?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1722954426151&to_ts=1723559226151&live=true) which lists the top queries by duration.

**Comment by rmtolmach** [comment]
✅ Passed off `vba_documents_upload_submissions` to Lighthouse in [#api-benefits-intake channel](https://dsva.slack.com/archives/CDRSFMWFL/p1723577052497749) (private channel).

**Comment by jennb33** [comment]
@rmtolmach because `vba_documents_upload_submissions` and the `va_forms_forms` have been passed to LH, does that complete our work? Thanks!

**Comment by rmtolmach** [comment]
Michel McDonald says the `va_forms_forms` table slow queries are coming from [here in vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_forms/app/models/va_forms/form.rb#L5) and that is also owned by them. Michel says, "Its a text search that backs the https://www.va.gov/find-forms  page. Is this a case where the query is pretty fast, but it's called a lot(it's a ~pretty hot endpoint, wide open to public, no login needed)"

I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/90676 to circle back on this in a few weeks since there's nothing much else to do now.

**Comment by rmtolmach** [comment]
sorry, reopen to put in review.

**Comment by jennb33** [comment]
@LindseySaari approved this ticket to close, as there is no more work for us to complete and Lighthouse has been made aware.
