### ISSUE TITLE
Data validation CXI, PBI and Advanced Find  Data set for AskVa Data

### ISSUE THREAD

**Issue by newworld2616** [department-of-veterans-affairs/va.gov-team#88310]
## Issue Description
Veteran Support must have access to the CSI dataset in PowerBI to confirm the accuracy of the data source and confirm data validation 
---
## Tasks
- [x] Determine server owner 
- [x] Validate data in CXI
- [x] Determine how data is ingested to confirm sources 

## Acceptance Criteria

 - [x] **Scenario: Access CXI Data set for AskVa Data**
  - Given the GraphQL mutation is implemented
  - When the mutation is called with input parameters
  - Then the mutation should return the acceptance criteria for accessing the CXI dataset and confirming its accuracy
- [x] **Scenario: Determine server owner**
  - Given a task to determine the server owner
  - When the task is completed
  - Then the server owner should be identified
- [x] **Scenario: Validate data in CXI**
  - Given a task to validate data in CXI dataset
  - When the task is completed
  - Then the data validation should be confirmed
- [x] **Scenario: Determine how data is ingested to confirm sources**
  - Given a task to determine how data is ingested into the CXI dataset
  - When the task is completed
  - Then the data sources should be identified and confirmed
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
CXI data is incomplete - a new team is being stood up and advised 2-3 weeks until accurate tables would be available.  

There is a meeting with Christopher Clemens to review available data and update on new team.

**Comment by ATMiddleton** [comment]
Mason Crane
  8:53 AM
Good morning team, after our lovely chat last week, where I explained how my other team would be working on UAT and pushing data to prod.. we found out that a competitor of the RISE contract has challenged the decision, and so the whole thing is under review. We have been told to stop billing and working on the contract until further notice.
This in turn will delay the work to get this data available. I wanted to share this update for transparency.  Please let me know if you have any questions or concerns that I may be able to help with

**Comment by newworld2616** [comment]
We have the access to AVA data, and it has been extracted and transferred to DOMO dashboard successfully from Advanced Find.
