### ISSUE TITLE
Puma Monitor Tuning - Sprint 6

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88319]
## User Story
As the managers of the Puma servers, 
It is important to have the optimal configuration in place for Puma servers
So that Vets-API availability remains consistent and high-functioning for those who utilize the APIs. 

## Summary
We have a monitor, [[Prod] [EKS] Puma Backlog](https://vagov.ddog-gov.com/monitors/116657), that notifies us when the Puma backlog is over a threshold for an amount of time. We need to tune these monitors so that they are running accurately.

There is a [recurring scheduled downtime](https://vagov.ddog-gov.com/monitors/downtimes?id=7cab24d2-82fa-11ee-a5b1-da7ad0900007&sort=-start_dt). The alert gets muted every day from 3-4 ET. Kyle set that up because that was a predictable time of day that it would trigger the alert. 

## Tasks
- [ ] Tune the Puma monitors
- [ ] Make new tickets based on findings. Or if the fix is small, implement it. 
- [ ] Document any specific Puma tuning work and indicate where it is stored

## Success Metrics
- [ ] Puma monitors have been tuned

## Acceptability Criteria
- [ ] Puma monitors have been tuned and documentation is available for what was done, when, and by whom.
- [ ] New work is ticketed for future Sprints

**Comment by jennb33** [comment]
Unnecessary dupe
