### ISSUE TITLE
VFS Team/Team Member Orientation Template Review

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#88326]
## Description 
We were asked to review the VFS Team/Team Member Orientation Template [here](https://dsva.slack.com/archives/CJRQ85PQB/p1721058955228499). Please check off your name when your review is complete. 
---

## Definition of Done
All tasks below are complete. 

---

- [x] lindsay-insco
- [x] alyssagallion
- [x] bdech
- [x] bmatos312
- [x] AnthonyWFlowers
- [x] davidpetras

## Tasks 
_Steps to reach definition of done._ 
- [x] Verify all links/references are accurate
- [x] Verify that there are no gaps in what new teams and team members need to know.
- [x] Make recommendations and/or suggestions for improvement and share with Governance team, if applicable.
- [x] [Review Platform Orientation video for Platform Support ](https://depo-platform-documentation.scrollhelp.site/support/support-overview)
- [x] Submit any recommendations for edits [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&projects=&template=orientation-feedback.md&title=Platform+Orientation+feedback+ticket+from+XX+team) 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
**Standup feedback:** We'd like to add a disclaimer that you must have repo access prior to submitting this ticket template. We'd also like to link to the place you request said access prior to submitting this ticket. We've noticed an influx in tickets where people don't have proper access.

**Comment by davidpetras** [comment]
<img width="1680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9cc023a1ae236456b4edc899c4e397897e579200/Screenshot%202024-07-24%20at%208.23.58%E2%80%AFAM.png" alt="Screenshot 2024-07-24 at 8.23.58 AM.png" />

Perhaps we could move the "**Note**" to the top of Platform Support, it seems to be a bit buried in its current place. We could also add the https://depo-platform-documentation.scrollhelp.site/getting-started/prerequisites-for-access-requests to review as well.

**Comment by AnthonyWFlowers** [comment]
I second what David mentioned; "Platform will not be able to complete this task if you are not a member of the VA GitHub Organization." Maybe we mention that We cannot make them a full member, they cannot get any tools, etc. I don't think "this task" does enough of a job explaining how important that step is to any other steps regarding access/tools.

**Comment by bmatos312** [comment]
Within the intro of the template in bold letters we should make a disclaimer and highlight the areas where VA email is needed so people know that they have to wait and being adjudicated will not suffice as they need the e-quip and access to their VA email
<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f406c52a35902a7f356566aa839116c68f1629bc/image.png" alt="image.png" />

**Comment by lindsay-insco** [comment]
We could add that they need to have an email that says “you have been sponsored” the email title is usually ‘USAccess PIV Sponsored’ to be as cleared as possible that that is what we need. “Transmittal notice” doesn’t sound quite the same as “you can go and receive your PIV and we need the email that says that exactly”

**Comment by alyssagallion** [comment]
Passed along feedback in feedback template. [Ticket link here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89500). Additionally, we [created a ticket for updating the Platform Support Orientation Video here](Re-Record Platform Orientation Video for Platform Support  #89498). Closing!

Let @shiragoodman know via Slack and an FYI here. Thank you!
