### ISSUE TITLE
[CST] Add design for second type of 5103 Notice request so that we can fully remove "Ask for your claim decision" banner

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#88335]
## Background Context

As @jerekshoe pointed out [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82491#issuecomment-2203841595), the Standard 5103 request is treated differently in CST than the Custom 5103 request. 

The Custom 5103 shows up as "Automated 5103 Notice" and our [new design](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=1587-1313) will apply to this case. But Standard 5103 requests don't show up in CST (until the request is closed). The Veteran will still get a letter for this request though, so it makes sense to have some alert for this in CST and some way for them to close the tracked item.

## Open questions
- For @jerekshoe: Can we connect this backend logic to a frontend that is the same as the new 5103 design? It wouldn't technically be a 1P request from BGS but we could make it look like one in our frontend (until we can get BGS to change this for us).
- Assuming we can do the above, what are the other implications of the fact that Standard 5103 tracked items are not treated as requests by BGS? (e.g. It will not show up in Recent Activity until it's closed)

## Design
- Need to figure out what the design should be for Standard 5103 requests in CST. 

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- Add here

## Tasks
- [ ] _Define what design should be for Standard 5103 tracked item in CST_
- [ ] _Create a design that allows the Veteran to close the "5103 Notice Response" (i.e. Standard 5103) tracked item via CST, similar to what we designed for "Automated 5103 Notice Response" (i.e. Custom 5103)_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Veteran has the same functionality to them available via the Standard 5103 Notice design that they had with the "Ask for your claim decision" banner (i.e. the ability to close the tracked item)_
- [ ] _AC_
- [ ] _AC_
