### ISSUE TITLE
[FSR] Testing transform and submit endpoint

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#88357]
## Description
Test the new `transform_and_submit` endpoint with different payloads on staging and locally 

## Tasks
- [x] Run submissions
  - [x] Test full FSR Submission
  - [x] Test streamlined waiver short
  - [x] Test streamlined waiver long
- [x] Capture relevant data & errors 

## Acceptance criteria

- [x] Testing is complete and feedback has been provided
- [x] No additional testing remaining

## Testing
- [x] Yes please

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Testing completed, follow on tickets created from findings:
- [FSR transform] Streamlined Long Exception [#88509](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88509)
- [FSR transform] Streamlined Short Exception [#88499](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88499)
