### ISSUE TITLE
Create New Page: Content Team - What We Can Help With

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88359]
## User Story
As a PO, I want to be able to share and point to a page on Platform website that details the services of the Platform Content team, while differentiating between the website and va.gov and between roles and services of Platform Content team and CAIA (Content, accessibility, and information architecture) team.

As a VFS Team member, I need to know what needs are served by the Platform Website and the Platform Content team. I also need to know the difference between Content Team and CAIA and between Platform Website and va.gov.

As a Platform Content team member I need a page on the website that highlights the team's roles and services, and which I can share as a quick-view guide for VFS team members looking for documentation help while building on va.gov.

Assignee: @taylojill 

## Issue Description
Platform Content Team needs to create a page on Platform Website detailing what sort of issues the team can help with and examples of some things we don't do.
The format of this page will follow that of [What We Can Help With - Platform Support](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support)

[Here is the Content Team DRAFT PAGE in Confluence](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3366617104/DRAFT+external+What+We+Can+Help+With+-+Platform+Content+88359)
Per Erika Washburn, we should compare and contrast what Content Team does vs. CAIA and va.gov for **What We Don't Do**
### Example: 
What We Don't Do
- **VA.gov** Content, accessibility, and information architecture guidance for product teams
- Management of unauthenticated content and IA on va.gov
- Content style guide for va.gov
These are handled by the **CAIA Team**  

What We Do
Platform Website documentation for VFS teams building on Platform is handled by **Platform Content Team** 

---
## Tasks
Team member edits new page in draft space. 
- [x] Jill create page based on [88540](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88540) and [89083](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89083)
- [ ] Team decides IA
- [ ] Schedule announcement for next Platform Demo

## Acceptance Criteria
- [ ] Document is approved and ready for publishing, demo **OR**
- [x] Additional ticket created to capture further work on this project
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/88359?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
Providing examples of each topic will take time, and this should appear in a future sprint. Some topics will not have easy examples

**Comment by taylojill** [comment]
Submitted draft page for team review via our internal Slack channel. Waiting for feedback.

**Comment by taylojill** [comment]
Incorporated team's feedback and worked with @jknipes to create two pages, one external (web site) and one internal. The external version is being reviewed by leadership; waiting for the go-ahead to publish after IA decision is made.

**Comment by jknipes** [comment]
Per leadership, VFS-facing/external version needs more specific, relevant examples

**Comment by jknipes** [comment]
- Further revisions needed to this page, which were unknown at the start.  
- Page was created, many edits were made and the work grew beyond original scope. We will be closing this ticket and continuing the work in _______

**Comment by jknipes** [comment]
Work is complete, moving to _Closed_
