### ISSUE TITLE
AMA Claim Establishment in VBMS Support

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#88356]
## Value Statement

**_As a_** veteran

**_I want to_** file a claim

**_So that_** the content is established and stored correctly

---

## Background Context

- Part of the AMA process, they have updated how SC/HLR claims are established. It have been moved from CaseFlow to VBMS once the claim reaches CMS. They need our support to send test data so they can verify that claims are established correctly. 

## Outcome, Success Measure, KPI(S), and Tracking Link

- Send test claims using the VA.gov Staging environment to support their testing.
- 

## Acceptance Criteria

- [ ] _Testing is complete and all submissions are established as expected_

### Enablement team (if needed)
@amylai-va is helping to coordinate with the IBM team

## Out of scope

- Code changes, this should just be testing as the changes are past Lighthouse

## Open questions

- With establishing these claims in VBMS directly effect CST

## Tasks

- [ ] _Monitor MS Teams thread and send tests as needed_
- [ ] _Collect GUID of submissions and send to Jacob Shepherd_

**Comment by shaunburdick** [comment]
Sent tests on:
- 7/9: Didn't work as they had test addresses
- 7/11: Valid address but contained keywords that got it off boarded
- 7/17: Sent a single SC claim with valid address and single contention

**Comment by eileen-coforma** [comment]
Waiting to know if it works, or if more tests are needed.

**Comment by Mottie** [comment]
Meeting canceled. Team is still investigating why they have failures. Will meet tomorrow in VBMS Appeals ART sync to discuss

**Comment by anniebtran** [comment]
@Mottie to send another SC request

**Comment by dfong-adh** [comment]
No updates yet - still need response from AMA (Steven @ ibm)

**Comment by dfong-adh** [comment]
Shaun to talk to Amy later today

**Comment by dfong-adh** [comment]
Shaun will write up expectations for the tests (building a test plan) and send it to VBMS

**Comment by Mottie** [comment]
Shaun submitted a Supplemental Claim on 9/24/2024. We're waiting to hear back.

**Comment by kayline** [comment]
Follow up with CMP this week

**Comment by kayline** [comment]
@shaunburdick Should we ping again?

**Comment by dfong-adh** [comment]
Maurice will follow up with Amy/Julie for any remaining steps needed.

**Comment by comaurice** [comment]
Confirmed all good
