### ISSUE TITLE
Create New Page: Content Team - What We Can Help With

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88360]
## Issue Description
Platform Content Team needs to create a page on Platform Website detailing what sort of issues the team can help with and examples of some things we don't do.
The format of this page will follow that of [What We Can Help With - Platform Support](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support)

[DRAFT PAGE in Confluence](https://vfs.atlassian.net/wiki/spaces/PWD/pages/edit-v2/3301736519)

---
## Tasks
Each team member contribute and edit document
- [ ] Lauren
- [ ] Cheryl
- [ ] Joe
- [ ] Jill
- [ ] Brian
- [ ] Schedule announcement for next Platform Demo

## Acceptance Criteria
- [ ] Document is approved and ready for publishing, demo
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
11/5 Jason mentioned the ESI tickets might be spread to the Back End CoP as the Product team has low capacity due to OOO, Tier 2 Support duty and FOIA request.
