### ISSUE TITLE
Hybrid Microservices Architecture Design document discovery

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88366]
## User Story
As the developers and managers of the Platform Product team,
We need to do the discovery work for the objective, 
So that a design document for the Hybrid Microservices Architecture objective can be created to support the work.

## Issue Description
The Platform Product team will undergo the discovery for Hybrid Microservices Architecture, from which a design document will be created, outlining the strategy and requirements to get the work done. 

## Tasks
- [x] Discovery on the Hybrid Microservices Architecture objective
- [x] Create documentation from discovery work which will inform the Design Document. Documentation can be found [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3311075329/Hybrid+Microservices+Design+discovery+documentation).

## Success Metrics
That discovery is complete and a design document can be created. 

## Acceptance Criteria
- [x] Discovery is complete and documentation can be created for the Hybrid Microservices Architecture design document. See [ticket 88704](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/88704) for the design document creation. 
- [x] Documentation should be captured [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3311075329/Hybrid+Microservices+Design+discovery+documentation)
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
7/22 update: @LindseySaari says she is heads-down on this ticket, it's a lot of work and it's on track. @Kshitiz-devops is working on servicems and Kafka/SBus elements.

**Comment by jennb33** [comment]
7/24 update: document has been populated with DevOps information by @Kshitiz-devops and is being finalized by @LindseySaari. @jennb33 is going to review the work to date.

**Comment by jennb33** [comment]
@LindseySaari I've reviewed the document [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3311075329/Hybrid+Microservices+Design+discovery+documentation) and it looks great!!

**Comment by LindseySaari** [comment]
I'm going to close this, but the doc is still open for commentary! Thanks @flooose for the feedback
