### ISSUE TITLE
Edit: ESI Pages - MDT - Denver Logistics Center

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88361]
## User Stories
_"As a VFS Team member, I need to know the information on the External Service Integrations
is up-to-date and complete, so that I can build on va.gov with confidence"_

## Issue Description

The [External Service Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) section of Platform Website contains pages with several formatting errors and missing information, as well as use of personal names. We need to edit the pages in this section.

## SME:

- Steven Cumming - SRE team, BE CoP
---
- ### [Spreadsheet with comments for each page](https://docs.google.com/spreadsheets/d/1fmV4M-mV4wIVCPsxYzxK_c2KjsdlQaGepG1B9VwFQvE/edit?gid=0#gid=0)

### This ticket is for the editing of the 
[MDT - Denver Logistics Center](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798533/MDT+-+Denver+Logistics+Center) page
---
## Tasks

- [x] Content team ticket assignee: Review page comments first
- [x] Add additional comments if necessary
- [x] Copy page and move copy to DRAFT Space (page **Copy** will not retain comments)
- [x] Review comments with SME
- [x] Make formatting corrections
- [x] With SME update information including any links
- [x] SME review Final Draft for accuracy
- [x] Prepare page for deployment

## Acceptance Criteria
- [x] Updates and corrections made
- [x] Page is ready for deployment 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
11/5 Jason mentioned the ESI tickets might be spread to the Back End CoP as the Product team has low capacity due to OOO, Tier 2 Support duty and FOIA request.

**Comment by stevenjcumming** [comment]
First draft is complete, I did change the title to help searchers: https://vfs.atlassian.net/wiki/spaces/PWD/pages/4000219154/Denver+Logistics+Center+MDOT

**Comment by jknipes** [comment]
Thanks @stevenjcumming , we will review shortly.

**Comment by BSmolensky** [comment]
I have reviewed doc and made additional in-line comments. Will work with SME to fine-tune the document before publication.

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance criteria met. Updated page should deploy today during normal deployment cycle.  Ticket is ready to close.

**Comment by jknipes** [comment]
Moving into current sprint due to available capacity and need for use by ADE team. Planned tickets completed earlier than expected.

**Comment by jknipes** [comment]
@BSmolensky the warning box on the page says `The above host links are not accessible via the browser.` In other places, we say `requires network access` - do we have a SG about this?

**Comment by BSmolensky** [comment]
@jknipes - There is not standard language in the SG about inaccessible link. However, they are not supposed to be active links. In the draft doc that Steven wrote they were urls but not hyperlinks. They must have flipped to hyperlinks in the move to the PW.  I will "un-link" them so they are simply spelled out URLs like the SME intended. Once they are spelled out urls and not hyperlinks, they do not require the same treatment as hyperlinks. To the PCT they are basically like code. 

**Side note**: I did flag the wording of the call-out box for the SME but the SME assured me that he used common programmer jargon and that the user would 100% understand the language in the callout box.

**Comment by BSmolensky** [comment]
Mistaken hyperlinks have been returned to non-active url addresses. Page will get re-deployed during tomorrow's scheduled deployment.

**Comment by jknipes** [comment]
Work is complete, closing as _Done_.
