### ISSUE TITLE
[IA] Logged-in homepage: Investigate how banners/alerts work on the logged out homepage and in the navigation

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#8836]
## Background

We will need to consider some of the elements of the global UX in the new logged in homepage, namely how banners and alerts work. This is necessary so that what we design does not conflict with any existing global features.

**5.13.20 From Ryan Thurlwell**

Re: how global alert banners will be changing:

> What we're accounting for is managing multiple alerts on the home page at one time (for example: System maintenance, coronavirus and locally a hurricane message).
> we've decided:
> 1) they will all be dismissable
> 2) emergency banners are topmost
> 3) limit the number of characters to avoid big banners

When I asked about whether they decided not to make alerts collapsible, Ryan said:

> b/c of accessibility, the alerts needs to either collapse/expand or be dismissable. we chose dismissable because
> 1) these alerts are kinda big and obnoxious and despite our best efforts, there will always be a situations where there can be 2 or 3 alerts.
> 2) we wanted to give users the choice to keep the alert or dismiss—not all alerts apply to all users (for example, i dont care about coronavirus, i can dismiss it)
> 3) if we are worried about recalling the dismissed alert, we can control it with cookies, and bring them back on a daily basis.

Jen also added:

> PW team is going to pull out the sitewide downtime system banner to work on bc we want to have this ready the next time instead of continuing to rely on the promo banner.
>
> It's not groomed yet but that will get worked on first/separately because the others look like it may need more engineering product work -- for example if they're built as Drupal driven banners that can be published across Drupal products like VAMCs.
>
> I think the Drupal part doesn't apply to authenticated experience though? If so, then maybe all that auth teams would need are the design and content and ux specs via the design system?

Ryan:

> imho Samara (She/Her) i would design with the assumption that there can be alerts (up to 3) across the top of whatever "home page" a user visits, and they will be full width, stacked, pushing all content below (not overlaying content on the page)

And Jen followed up with a link to [this Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1589203638468900).

[More on banners](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/banners/banner-alerts.md)

## Tasks

- [x] Investigate and document existing global alerts and banners.
- [x] Make sure findings are documented in the [logged-in homepage folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia).
- [x] Review with Ryan Thurlwell or Jen Lee to make sure you've accounted for everything.
- [ ] Update docs if necessary.

## Acceptance criteria

- [ ] Global banner and alert behavior is fully documented and understood.

**Comment by tressaellen** [comment]
[Banner GH document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/design-ia/banner-discovery.md)

I've asked Ryan Thurlwell to review this and will post when I hear back.

**Comment by tressaellen** [comment]
Meeting scheduled for 08/17
