### ISSUE TITLE
Automate upload of missing PDF for established claim

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#88376]
## Issue Description
In [#84389](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/84389), we created a polling job and a series of scripts to aid in the manual remediation of the (hopefully) unlikely event that a claim is established synchronously, but the PDF generation/upload has failed on the Lighthouse side. The scripts are detailed [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/lighthouse_submission_remediation.md)

As a stretch goal, a 3rd script was begun to more fully automate the remediation by generating and uploading PDFs of submissions that were found to be missing them after 50 hours. However, due to many challenges in and around the actual upload of the file (and the sands of the hourglass running down), the script was not completed. In meetings with Lighthouse, Octo and Carbs, it was determined that although this script would be nice to have, full remediation could be handled via existing processes employed by Team Carbs and/or by Lighthouse (with whom the onus of the failure most likely resides anyway).

All that said, this story is to complete the aforementioned script, so that remediation could be employ immediately and directly.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Complete the full auto-remediation script described above (and begun in the [last section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/lighthouse_submission_remediation.md#manual-remediation-steps-in-progress) of the remediation plan)
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
