### ISSUE TITLE
[DevOps] Zap VPC parameters kept in `vpc` module.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#88379]
## Description
These are not necessary; we can just use `data` blocks to query them as needed.

## Tasks
- [x] [DevOps] Remove IaC referring to the parameters.
- [x] [DevOps] Remove the parameters themselves.

## Acceptance Criteria
- [x] No IaC refers to these.
- [x] No parameters exist.
