### ISSUE TITLE
[DevOps] Discovery on copying secrets necessary for Vista API backend to function into `vaec-cie`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#88378]
## Description
- What are these secrets?
- What is their provenance?
- Can they be rotated automatically?
- Should they be rotated now?
- Is this immediately necessary?
- Why are they necessary?
- What is the appropriate protocol for handling them?

## Tasks
- [x] [DevOps] Determine what secrets we have in place and document in this thread.
- [ ] [DevOps] Open followup ticket(s) to address each as appropriate.

## Acceptance Criteria
- [x] Secrets are documented in this thread.
- [ ] A followup ticket is opened for each secret that needs to be managed in `vaec-cie`.

**Comment by ndouglas** [comment]
## Secrets Manager
- DD_API_KEY: nbd there
- MGMT_PASSWORD: Password for the management interface
- JWT_CONFIGURATION: A JSON-encoded object like so:
```
{
  "jwt.application.name": "OCTO-VISTA-API",
  "jwt.application.key": <some string>,
  "jwt.issuer": "gov.va.ovac.vetext.smsbatch",
  "jwt.ttl": "60",
  "jwt.refreshttl": "240",
  "jwt.clockSkew": "5",
  "jwt.audience": "VETEXT-SMS-BATCH",
  "jwt.public.key": <base64-encoded public key>,
  "jwt.private.key": <base64-encoded private key>,
  "jwt.ssoi.public.key": <base64-encoded public key>
}
```
- AWS_ACCESS_KEY_ID: this could conceivably be an issue
- AWS_SECRET_ACCESS_KEY: this could conceivably be an issue
- VISTA_CONNECTORS: A JSON-encoded object containing a list of objects like so:
```
{
  "connectors": [
    {
      "primaryStation": "<number>",
      "jndiName": "java:jboss/vlj/tevivista" OR "java:jboss/vlj/vlj<number>",
      "ip": "10.x.x.x" OR "hostname.va.gov",
      "port": "<number>",
      "accessCode": "base64-encoded string",
      "verifyCode": "base64-encoded string",
      "encrypted": "true",
      "alwaysUseDefaultAsMin": "false",
      "enabled": "true"
    }
  ]
}
```
- WILDFLY_CONFIGURATION: A JSON-encoded object like so:
```
{
  "datasource": {
    "host": "<rds cluster endpoint hostname I think>",
    "port": "5432",
    "databaseName": "<string>",
    "databaseUsername": "<string>",
    "databasePassword": "<string>"
  },
  "vistaLinkResourceAdapters": [
    {
      "jndiName": "java:jboss/vlj/tevivista" OR "java:jboss/vlj/vlj<number>",
      "poolName": "vljDevPool",
      "minPoolSize": "0",
      "maxPoolSize": "50",
      "prefill": "false",
      "useStrictMin": "false",
      "flushStrategy": "FailingConnectionOnly",
      "blockingTimeoutMillis": "30000",
      "idleTimeoutMinutes": "1"
    },
  ],
  "vistalinkLogLevel": "DEBUG",
  "vistaApiLogLevel": "DEBUG"
}
```
- APP_CONFIG_SETTINGS: A JSON-encoded object like so:
```
{
    "name": "ecs-vista-api",
    "environment": "<env>",
    "configProfile": "<config-profile-name>"
}
```

The problem I see here is that these aren't really consistent across environments. So I'm going to have to dig in here to see what is actually happening and how these are used.

**Comment by ndouglas** [comment]
- [Why stuff is different between non-prod and prod](https://github.com/department-of-veterans-affairs/octo-vista-api/blob/2830a21a0f656050a1c3d2ade0b05a66a31aabb0/gha/vista-api/VistA-API-Start-Up.md)
- [Config generator](https://github.com/department-of-veterans-affairs/vista-api-config-generator)

**Comment by ndouglas** [comment]
Tentative plan.
- `DD_API_KEY` is fine.
- `MGMT_PASSWORD` is fine, needs to be regenerated though
- `JWT_CONFIGURATION` is fine, should be generated though
- nuke `WILDFLY_CONFIGURATION` and `VISTA_CONNECTORS`
- AppConfig on every environment; add AppConfig to ECS task role policy.

**Comment by benbrasso-agile6** [comment]
Testing something with that label real quick

**Comment by ndouglas** [comment]
In summary, all of these that matter are provided by the [Vista API Config Generator](https://github.com/department-of-veterans-affairs/vista-api-config-generator/). These do not need to be copied, _per se_, but I need to verify experimentally that the appropriate resources will be created, and I'm still not really close to that.
