### ISSUE TITLE
[DevOps] Discovery on `vista_api_frontend` in `octo-vista-api`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#88377]
## Description

Looks... similar to the "backend" service. This is only on prod. This might be the same container, but acting in a different role. Why? What's going on here? How do the container and the configuration actually differ?

## Tasks
- [x] [DevOps] Figure out what is going on here.
- [x] [DevOps] Open followup ticket(s) to address.

## Acceptance Criteria
- [x] I've figured out what is going on here.
- [x] Followup ticket(s) opened to address.

**Comment by ndouglas** [comment]
This is essentially the same as the Backend. I will need to centralize the task definition in some intelligent way.
