### ISSUE TITLE
Clarify medical evidence request

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#88388]
## Description
As part of the usability studying conducted in early spring, we found some opportunities to improve the experience for veterans while they complete the 527EZ form.

Design ticket #79210 has the background information for this specific change to the help veterans understand why they need to provide medical evidence 

## Designs
- [Figma for Engineering](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5352-82099&t=V5dUy3B0nNzkKbAT-11)

## Acceptance Criteria
- [x] This change is kept behind a feature flag; will need to go through Collab Cycle
- [x] Web pages(s) are update to match the designs
- [x] All automated tests are update and passes

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Back-end work to set up feature flag
- [x] Front-end work

## Review
- [x] Designer/Product has signed off on pages in staging
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89969
```

**Comment by aplatt-coforma** [comment]
Staging review link: https://staging.va.gov/pension/apply-for-veteran-pension-form-21p-527ez

**Comment by danbrady** [comment]
Staging review complete. Only difference I noticed is a missing line break, but that might be something from the Forms Engine. Differences captured in [this figma file](https://www.figma.com/design/DvZN50R2KnQbdSfwkw8Rgm/527-Staging-Reviews?node-id=23-101322&t=4jB2oojdgQsxi29d-1).

**Comment by ToddWebDev** [comment]
@danbrady I was able to fix this line break issue and it will be included in the updates

**Comment by danbrady** [comment]
@ToddWebDev LGTM! Confirmed all fixes in this issue are on staging.

**Comment by aplatt-coforma** [comment]
Closing this ticket with the sign off with @danbrady. 
We are keeping these changes on staging for now to allow research study with pension eligible Veterans (#82213)
