### ISSUE TITLE
Profile Data Component for Gating the 686 Progression

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8838]
## Description
We want to perform eligibility for the Veteran before they continue on to the 686 application, VA File number is the first thing to check for.  Eventually, there needs to be a check for 30%+ total combined disability rating, but that can wait until after launch.

## Tasks
- [x] As seen in [this mockup](https://xd.adobe.com/view/057055ba-4c2b-4367-667b-7d7034cb43b4-7341/) messaging will be as follows:
- Data is present = move on
- Data is not present = ask user to call a number

## Acceptance Criteria
- [x] The gateway page indicates whether there is a passable level of eligibility to proceed
- [x] A PR has been requested for merging

**Comment by sporeboy** [comment]
The three screens that will change to address static biographical data presented in the form:
- The first Veteran info screen will show static info; the address screen will remain... [(Mockup)](https://xd.adobe.com/view/ca825c11-2268-458f-4fec-6aaecfec5b2d-bcb3/screen/dc153448-40b1-4d35-b890-698dca690305/Add-Modify-Dependents-Veteran-Details)
- Following the precedent in the 526 form, the Veteran info screen will display Name, Gender and DOB; SSN and VA File Numbers are not presented
- If one of Name, Gender, DOB, SSN or VAFN are missing, the form will error and show the user an alert... [(Mockup)](https://xd.adobe.com/view/057055ba-4c2b-4367-667b-7d7034cb43b4-7341/screen/457ed757-b2d0-46c1-9beb-f89980f6d5ca/Add-Dependents-Intro-LoggedIn-Error-1)
- Content/copy in the alert may change/pending review
- The 686 form review screen will not present the static Veteran biographical info, but will present and editable review of the address... [(Mockup)](https://xd.adobe.com/view/88794e80-ae26-4f3e-509e-94d09eb571f7-fe48/screen/f6ccacc0-0160-4213-a085-b3876cb6daa9/Verification-1A-ALT)

**Comment by micahchiang** [comment]
Hey @sporeboy - Your comments are great, but I think they belong on ticket #8829 since that's the one in charge of displaying Name, Gender, and DOB. I'll copy your comment over to that ticket.
