### ISSUE TITLE
[DevOps] Initial discovery on initial set of system tests for Vista API

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#88386]
## Description
This is not intended to be a complete set. I'll find more things that need to be tested as I go.

But we want to confirm basic operation on non-prod environments (which is all we'll have for now).

## Tasks
- [ ] [DevOps] **_insert DevOps work_**
- [ ] [DevOps] Open up followup ticket(s) for another batch of these.

## Acceptance Criteria
- [ ] Followup ticket(s) opened as needed for more batches of tests.
