### ISSUE TITLE
Review Backend CoP orientation materials

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#88392]
## Issue Description
This work is to address [Shira's comment in Slack](https://dsva.slack.com/archives/CJRQ85PQB/p1721058955228499) with a Backend CoP lens. 

## Tasks
⚠️ _Review items in the templates that are relevant to the Backend CoP only!_
- [x] Review [New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D)
    - [x] Verify all links/references are accurate
    - [x] Verify that there are no gaps in what new teams and team members need to know.
    - [x] Make recommendations and/or suggestions for improvement and share with Governance team, if applicable. Use this [feedback template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&projects=&template=orientation-feedback.md&title=Platform+Orientation+feedback+ticket+from+XX+team)
- [x] Review [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team%2C+platform-tech-team-support&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D)
    - [x] Verify all links/references are accurate
    - [x] Verify that there are no gaps in what new teams and team members need to know.
    - [x] Make recommendations and/or suggestions for improvement and share with Governance team, if applicable. Use this [feedback template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&projects=&template=orientation-feedback.md&title=Platform+Orientation+feedback+ticket+from+XX+team)
- [x] Edit the [orientation slidedeck](https://docs.google.com/presentation/d/1_ui4c8ucMMZhoQGCdX6Q6dPAa_gkSfwtswJMjrcbIdI/edit#slide=id.gb46c4886c8_0_280). There are a few inaccuracies (specifically, the info about the deployment on Slide 5. But check the rest of the deck for anything else outdated). 
- [x] Address the [Backend orientation video](https://www.youtube.com/watch?v=UD5ENuP8p7M&ab_channel=PlatformCrew). You may need to re-record the orientation video (instructions for that [here](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Guidance)), or you might be able to get away with editing the current video to add corrections.

## Acceptance Criteria
- [x] All tasks are complete.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
I intended to do this while on support, but I had too much on my plate! I am off of support tomorrow, so I will be able to get this done. Hopefully by end of week!

**Comment by rmtolmach** [comment]
The links from the BE eng section are accurate, but the content that's linked to on the platform website could use a refresh. I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/89848 for that and plan to do it during CoP meetings.

**Comment by jennb33** [comment]
8/5 update: this is still being worked on, but per @rmtolmach it could be completed COB today.

**Comment by rmtolmach** [comment]
I updated the BE orientation video and re-uploaded it. [YouTube Link](https://studio.youtube.com/video/3FEs7GPdkJ8). I also updated the link on Orientation Sessions page on the Platform Website. 
To do:
- [ ] set the older video to Private after the Orientation Sessions page is published.

**Comment by rmtolmach** [comment]
I submitted my recommended changes to the Governance team in https://github.com/department-of-veterans-affairs/va.gov-team/issues/90019.

**Comment by rmtolmach** [comment]
✅ I verified that the the new video is published here: https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Back-endOrientation
And that close captions work and that the video has the updates I made (at these times: 5:05, 9:53, 16:54, 19:12)

**Comment by shiragoodman** [comment]
thank you @rmtolmach !!
