### ISSUE TITLE
[DevOps] Determine initial set of system tests for CHIP.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#88390]
## Description
See #87319 and #88386. This should cover CHIP and its basic interactions with LoROTA and Vista API.

## Tasks
- [ ] [DevOps] **_insert DevOps work_**
- [ ] [DevOps] Open followup ticket(s) for the next batch of tests.

## Acceptance Criteria
- [ ] Followup ticket(s) opened for the next batch of tests.
