### ISSUE TITLE
[BGS-EXT] Bump `savon` to 2.15.1 (or latest) and release new version

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#88401]
## Issue Description
In order to bump savon (and a few other dependencies) in vets-api, we need to bump savon in [bgs-ext](https://github.com/department-of-veterans-affairs/bgs-ext) as its gemspec is pinned to `~> 2.14.0.`. Upon bumping, we need to release a new version. NOTE: This also requires `ruby >= 3.0`

Note: `savon 3.0.0.rc` was just released today (as of writing this ticket, 7/15). I'll check to see if we can easily bump without breaking anything, BUT there are a ton of breaking changes in the changelog, so it may not be worth spending the time to go to 3.0.0 at this point.

---

## Tasks
- [ ] Bump to 2.15.1 (or 3.0.0 if it's a clean jump)
- [ ] Publish new version of `bgs_ext`

## Acceptance Criteria
- [ ] New Version of `bgs_ext` has been published

**Comment by ryan-mcneil** [comment]
Created separate PRs for [ruby 3.3.3](https://github.com/department-of-veterans-affairs/bgs-ext/pull/120) and [savon 2.15.1](https://github.com/department-of-veterans-affairs/bgs-ext/pull/119)
