### ISSUE TITLE
IA Guidance: URLs for form flows

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#88407]
### Description
Define clear standards for identifying URL slugs for pages within form flows.

Goal:
Establish clear standards for URL slugs of individual pages within a form flow that will help product teams to identify accurate URLs.  

### Tasks
- [x] Review/analyze existing documentation and implementation  - Jenny
- [x] Establish scope of effort and where guidance lives - Jenny
- [x] Draft revised standard - Jenny
- [x] IA lead review - Mikki
- [x] Review with appropriate OCTO leads - Mikki
- [x] Create PR for VADS - Erin
- [x] PR review - Mikki
- [x] Publish - Erin
- [x] Communicate out to teams - TBD

## Acceptance Criteria
- [x] Standards are approved by OCTO IA lead, OCTO design lead(s)
- [x] Standards are published to VADS
- [ ] New standards are communicated out to teams

**Comment by mnorthuis** [comment]
@jennymayoco  I didn't see a ticket for this yet, so created one. 

Your draft with changes/comments from review: https://docs.google.com/document/d/1GPxTV7RPuBZ66WAFeNtxbE_jvoMaAFEf9N_1p99L0lk/edit?usp=sharing

**Comment by jennymayoco** [comment]
Hi @erinrwhite! I just went through the doc and updated the recs Mikki added so I think this is ready for your review.

Doc link: https://docs.google.com/document/d/1GPxTV7RPuBZ66WAFeNtxbE_jvoMaAFEf9N_1p99L0lk/edit#heading=h.6vyg7djv19m3

**Comment by erinrwhite** [comment]
Update 7/25: Ready to publish in VADS, in Erin's court

**Comment by mnorthuis** [comment]
@erinrwhite Was there a PR created for this one?  Want to make sure I didn't miss one somewhere.

**Comment by erinrwhite** [comment]
@mnorthuis not yet! 

Should this page still be a part of the URL Standards page as planned, or a sub-page like Vanity URLs will be?

**Comment by mnorthuis** [comment]
This can be part of the main URLs page.  Thank you!

**Comment by erinrwhite** [comment]
[PR created!](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3293) Combining efforts with the Vanity URL guidance in #90080

**Comment by erinrwhite** [comment]
[Standards published to VADS](https://design.va.gov/components/url-standards/#guidelines-for-urls-in-form-flows), over to @mnorthuis for sharing with teams, perhaps alongside #90080
