### ISSUE TITLE
[Design] Create wireframe(s) to handle an alert when Veteran is about to schedule an appt on a day/time where they have something already scheduled or pending

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88406]
## Tasks

- [ ] Determine what information to tell the Veteran. E.g., how much information about their appointments for the day? 
- [ ] Determine what actions the Veteran has. E.g., pick a different day/time. 
- [ ] Create wireframe(s) to handle an alert when Veteran is about to schedule an appt on a day/time where they have something already scheduled or pending. Reference: [Profile](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=0-787&t=XPi72yTHsk3E7YrX-0) uses a couple designs, which we could review. Inline below the component or a modal.

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/88406?planning-poker) with Zenhub @cgednalske @Cieramaddox
