### ISSUE TITLE
[DevOps] Make AWS Inventory Data Usable

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#88405]
## Description
We've dumped the output of AWS's script `aws-auto-inventory` into [S3](https://us-gov-west-1.console.amazonaws-us-gov.com/s3/object/aws-auto-inventory?region=us-gov-west-1&prefix=aws-auto-inventory.tar). It spans 629 JSON files that contains all of the LIST, GET, DESCRIBE data from each service used in `vaec-cms`. The number of files is unruly and the data is not yet actionable to support resource migration to `vaec-cie`

## Tasks
- [ ] Organize data by service, remove unnecessary, empty, or unrelated resources.
- [ ] Find a useful way to present the data to make findings actionable.

## Acceptance Criteria
- [ ] Inventory data is organized, parsed, etc., to take some _action_ on _all resources_ e.g. Ignore, migrate, remove.
- [ ] Follow up ticket(s) created to take action on data, or improve data usefulness.

## Relations
https://github.com/department-of-veterans-affairs/va.gov-team/issues/86930
