### ISSUE TITLE
Toxic Exposure: Prepare artifacts for Contact Center review

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#88403]
## Issue Description
As a Contact Center rep I want 526 toxic exposure documentation and information available to me so that I can support Veterans when they call in with questions about the toxic exposure section of the 526 form.

---
## Tasks
- [x] Update the product guide

## Acceptance Criteria
- [x] Add IPF to product guide
- [x] Merge with latest version of the product guide (incorporate EE, CC, Team 2 versions v1-v3)
- [x] Update the BDD product guide
- [x] Gather feedback via internal review
- [x] Create contact center ticket(s) for 526 and 526 BDD guides

Out of scope:
- [ ] Create and upload a product video - not required, will add a follow up ticket if needed

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
Are any updates needed to the product guide? If not, we can submit without the video and see if they think we should create one. What do we think? Is a video a good the right thing to do? I'm not intimately familiar yet with the needs of Contact Center Reps, so it's hard to make that call without more information - but if the team has background info that could be helpful in decision making.

**Comment by pacerwow** [comment]
Do we need to update the BDD guide? Reach out to Contact Center to find out.

**Comment by christinec-fftc** [comment]
Both product guides have been updated and shared for internal review. Once approved internally, will create the CC tickets.

**Comment by pacerwow** [comment]
Both Product Guides look great!! Ship it.

**Comment by christinec-fftc** [comment]
Thanks @pacerwow! All comments have been addressed. Will move to the next step which is creating the CC tickets

**Comment by christinec-fftc** [comment]
CC ticket created https://github.com/department-of-veterans-affairs/va.gov-team/issues/89438

**Comment by christinec-fftc** [comment]
Example of headings cleanup. Many lines were improperly labelled, making it difficult to view hierarchy <img width="862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1FaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03b24722fe385c5ad5f9b3649c73e9bc80749378/Screenshot%202024-07-29%20at%205.16.38%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 5.16.38 PM.png" />
