### ISSUE TITLE
[DevOps] Configure automatic credential rotation for LoROTA test account.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#88429]
## Description
Followup to #88428. The credentials for this account should be rotated frequently, perhaps daily.

## Tasks
- [ ] [DevOps] Research how this would be done.
- [ ] [DevOps] Implement this or, if tricky, open a followup ticket to implement.

## Acceptance Criteria
- [ ] Research on automatic credential rotation for the test account has been performed.
- [ ] Credential rotation has been automated or followup ticket(s) opened to address.
