### ISSUE TITLE
Verify Platform Orientation Materials incl Content Video

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88422]
## Issue Description

- Governance Team needs your help validating that Platform Orientation materials are still up to date and accurate. 
- Content Team also needs to verify the orientation videos that they have previously recorded are still accurate.
- Depending on the finding, it may be Governance Team's responsibility to fix it or it may be that of Content Team. 
- All videos are the responsibility of Content Team, not Governance.

---
## Tasks
- [x] review the [New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D) 
- [x] and the [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team%2C+platform-tech-team-support&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D). 

For any content relevant to Content Team's work, please:

- [x] Verify all links/references are accurate
- [x] Verify that there are no gaps in what new teams and team members need to know.
- [x] Make recommendations and/or suggestions for improvement and share with Governance team, if applicable.
- [x] Verify **the Content Team orientation videos** previously recorded are still accurate
- [x] Use this [feedback template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&projects=&template=orientation-feedback.md&title=Platform+Orientation+feedback+ticket+from+XX+team) to notify Governance of any outdated materials.

## Acceptance Criteria
- [x] Platform Content Orientation video materials are reviewed.
- [x] If needed, ticket created in backlog to update any content team videos that are out of date.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/88422?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by taylojill** [comment]
Videos to check:
1. [https://www.youtube.com/watch?v=yzl6nyLmqkA&ab_channel=PlatformCrew](url)
2. [https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation)(url)
3. [https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions](url)
4. [https://dsva.slack.com/archives/CJRQ85PQB/p1721058955228499](url)

**Comment by jknipes** [comment]
While not originally planned for this sprint, this ticket is high priority and should be completed in this sprint

**Comment by taylojill** [comment]
I reviewed two videos, one recorded/owned by the content team, [the other is on the Platform Orientation page](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-orientation#PlatformOrientation-Purpose). 
Submitted [new issue ticket to Governance team using their Platform Orientation feedback template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89348).
See my input on the screenshot below.
<img width="1660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cda780aa88d76daa29905db1892e0a3ede0d7c08/2024-07-25_14-18-44.png" alt="2024-07-25_14-18-44.png" />

**Comment by jknipes** [comment]
@shiragoodman we have checked the Content Team videos. we made a separate ticket to update a mention of our footer ticket, but otherwise everything is current.

**Comment by shiragoodman** [comment]
thank you @jknipes !
