### ISSUE TITLE
DR | Retrieve veteran details for remediation

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#88433]
## Value Statement

**_As a_** user type

**_I want to_** job to be done

**_So that_** desired outcome(s)

---

## Background Context

Follow up to #86343. This ticket covers the work to retrieve additional details about the veterans (the SSN/Participant ID/etc.) that will be reached out to as a part of our remediation efforts. This may include chatting with other teams who might be able to pull this data or running a script ourselves.

## Acceptance Criteria

- [x] Remediation spreadsheets in Sharepoint are populated with additional veteran data as requested by VBA/BVA

## Tasks

- [x] Meet with VBA to discuss what additional information is needed for Supplemental Claim and Higher Level Review remediation comms
- [x] Meet with BVA to discuss what additional information is needed for Supplemental Claim and Higher Level Review remediation comms
- [x] If necessary, write and run a script to retrieve the additional veteran data

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by shaunburdick** [comment]
Initial script written by Thomas. Will start collection soon.

```ruby
icns = []
output_csv_path = "tmp/veteran_email_and_file_numbers.csv"
headers = ['icn', 'first_name', 'last_name', 'dob', 'ssn', 'file_number' ]
mpi_service = MPI::Service.new

CSV.open(output_csv_path, 'wb') do |csv|
  csv << headers
  icns.each do |icn| 
    mpi_profile = mpi_service.find_profile_by_identifier(identifier: icn, identifier_type: MPI::Constants::ICN)&.profile
    birth_date = mpi_profile.birth_date.dup
    birth_date.insert(6,'-').insert(4,'-')
    csv << [icn, mpi_profile.given_names.join(" "), mpi_profile.family_name, birth_date,mpi_profile.ssn, mpi_profile.birls_id ] if mpi_profile.present?
    csv << [icn, 'not_found', 'not_found', 'not_found', 'not_found', 'not_found'] if mpi_profile.nil?
  rescue
    csv << [icn, 'error', 'error', 'error', 'error', 'error']
  end
end

s3_resource = Reports::Uploader.new_s3_resource
s3_bucket = Reports::Uploader.s3_bucket
obj = s3_resource.bucket(s3_bucket).object('benefits_research/veteran_email_and_file_numbers.csv')
obj.upload_file(output_csv_path, content_type: 'text/csv')
```

**Comment by eileen-coforma** [comment]
Annie meeting with Thomas tomorrow to run script for extra Veteran data. Checking sheets that Amy shared.

**Comment by anniebtran** [comment]
Met with Thomas and he pulled the additional Veteran data for us. I've added all of it to the spreadsheets and left an update for the different remediation groups in Teams

**Comment by Mottie** [comment]
Veteran information now in spreadsheet and handed off to VBA & BVA.

**Comment by anniebtran** [comment]
Haven't heard any questions or additional requests from VBA or BVA, so closing this ticket since the main task is finished. We can open more tickets for any other follow-up work.
