### ISSUE TITLE
[FE ] My VA Maintenance Period Alerts: Refactor existing dashboard code

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#88436]
## Background
As a follow up to #85711, we need to add/update maintenance window mappings on My VA so that we can have downtime alerts for each benefit section on the page as well as a global downtime notice. 

## Tasks
FE (reach out to Nick Gaydosh to clarify steps):
- [ ] Audit for additional Maintenance windows
- [ ] move code wrapping <ClaimsAndAppeals /> inside of component
- [ ] ensure each component section has a DowntimeNotification inside parent component
- [ ] ensure there is a global DowntimeNotification

## Acceptance Criteria
- [ ] We have the ability to trigger maintenance windows for each benefit section as well as a global notice for the entire page.

**Comment by ajakabcin** [comment]
Moving this to backlog for further discussion with @tpharrison. Ari to add some additional notes!

**Comment by ariperez** [comment]
Currently there are only a few services that are mapped to an active PagerDuty service and they lack meaningful 1:1 mapping to the UI.  In order to add more components to support active Maintenance Windows, we would need to identify the granularity of services, add the additional services in Pager Duty, and then create the frontend UI components.  

![image](https://github.com/user-attachments/assets/1cf98f7d-ec24-4b74-a8cb-26d6554dd819)

**Comment by ACParker89** [comment]
@nickjg231 does this need to roll into 49?

**Comment by mattmarino-adhoc** [comment]
See: https://github.com/department-of-veterans-affairs/va.gov-team/issues/85711#issuecomment-2494880174
@nickjg231

**Comment by ACParker89** [comment]
rollover @a6marinos @ACParker89

**Comment by nickjg231** [comment]
Pull request (still in progress): https://github.com/department-of-veterans-affairs/vets-website/pull/33196

# **Update on Maintenance Window Implementation for My VA Dashboard**

## **What Has Been Done**

### 1. **Per-Component Maintenance Windows**
- Updated the My VA page to use **per-component maintenance windows** instead of a page-wide window.  
- Each component handles its own maintenance status based on one or more external services.  
- Components determine what to show or hide during downtime based on requirements outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85711#issuecomment-2494880174).

### 2. **Logic for Showing Links**
- Links to other pages are generally still shown, even if the destination service is down. This avoids user confusion and ensures they can still navigate to services.  
- Maintenance windows mainly hide **dynamic content** displayed directly on the My VA page, not static links.

### 3. **Component-Specific Logic**
- Different components handle maintenance windows uniquely:
  - Some components hide entirely during downtime.
  - Others hide only specific parts (e.g., appointment cards or message counts) while still showing links.
- Updated components:
  - **Benefits Application Drafts**
  - **Claims and Appeals**
  - **Health Care**
  - **Outstanding Debts**
  - **Benefit Payments**

### 4. **Code Changes**
- Significant rewrites were required to incorporate downtime logic while maintaining existing behavior where possible.  
- Updated components to include downtime logic and their dependencies on external systems.

### 5. **Mapping External Systems**
Below is a mapping of the external systems, their Vets API endpoints, and associated identifiers:

| **Feature**                 | **Vets API**                        | **External System**      |
|-----------------------------|-------------------------------------|--------------------------|
| Benefits Application Drafts | `/v0/my_va/submission_statuses`     | Lighthouse               |
| Claims and Appeals          | `/v0/benefits_claims`               | Lighthouse               |
| Claims and Appeals          | `/v0/appeals`                       | VBMS                    |
| Health Care                 | `/vaos/v2/appointments`             | VBMS                    |
| Health Care Messaging       | `/my_health/v1/messaging`           | VAPRO? (This needs verified)                   |
| Outstanding Debts           | `/v0/debts`                         | DMC                     |
| Outstanding Debts           | `/v0/medical_copays`                | VBS                     |
| Benefit Payments            | `/v0/profile/payment_history`       | BGS                     |

- External system identifiers in code (defined in `src/platform/monitoring/DowntimeNotification/config/externalServices.js`):
  - `LIGHTHOUSE_SUBMISSION_STATUSES`
  - `LIGHTHOUSE_BENEFITS_CLAIMS`
  - `VBMS_APPEALS`
  - `VBMS_APPOINTMENTS`
  - `VAPRO_MESSAGING`
  - `DMC_DEBTS`
  - `VBS_MEDICAL_COPAYS`
  - `BGS_PAYMENT_HISTORY`

### 6. **Figma Documentation**
- Referenced [Figma designs](https://www.figma.com/design/15yOY4VEzitxm5tRMDiAzz/My-VA?node-id=0-1&t=5awh2m2zTAdQYg5R-1) to ensure alignment with visual and behavioral expectations.

---

## **Challenges**

### 1. **Preserving Existing Behavior**
- Maintaining existing functionality while adding downtime logic was challenging due to interdependencies among components and the variety of scenarios handled.

### 2. **Testing Updates**
- Updated **unit tests** and **Cypress tests** for all affected components.
- Resolved issues caused by dynamic behavior during downtime.

### 3. **Manual Testing**
- Verified component behavior for all possible maintenance scenarios.
- Confirmed that links, alerts, and dynamic content were displayed or hidden correctly.

### 4. **Mocking Maintenance Windows**
- Local testing involved mocking maintenance windows in `src/applications/personalization/dashboard/mocks/server.js`.  
- By default, most services are marked as down for testing purposes:
  ```javascript
  'GET /v0/maintenance_windows': (_req, res) => {
    return res.json(
      maintenanceWindows.createDowntimeActiveNotification([
        maintenanceWindows.SERVICES.BGS_PAYMENT_HISTORY,
        maintenanceWindows.SERVICES.DMC_DEBTS,
        maintenanceWindows.SERVICES.LIGHTHOUSE_BENEFITS_CLAIMS,
        maintenanceWindows.SERVICES.LIGHTHOUSE_SUBMISSION_STATUSES,
        maintenanceWindows.SERVICES.VAPRO_MESSAGING,
        maintenanceWindows.SERVICES.VBMS_APPEALS,
        maintenanceWindows.SERVICES.VBMS_APPOINTMENTS,
        maintenanceWindows.SERVICES.VBS_MEDICAL_COPAYS,
      ]),
    );
  };
### 5. **Handling Conditional Logic**

- Added logic to handle downtime visibility while minimizing disruption to the existing code structure.

---

## **Next Steps**

### 1. **Address Failing Tests**

- Resolve failing tests in the pull request.
- Ensure that all new tests reflect the updated component behavior.

### 2. **Manual Validation**

- Conduct further manual testing to confirm that all test cases are covered.
- Test edge cases, such as overlapping maintenance windows for multiple services.

### 3. **Health Care Messaging Verification**

- Confirm whether the Health Care messaging service is correctly linked to `VAPRO_MESSAGING` or another external system.

### 4. **Finalize Documentation**

- Finalize documentation for future reference, especially regarding the updated logic and external system mapping.

### 5. **Create Visual Documentation for Service Mapping**

- A new task should be created to document the relationships between external services, API URLs, and the specific components on the My VA page where those APIs are utilized.
- The documentation should include an image with arrows pointing from external services to API endpoints and corresponding screenshots of the components on the page.
- The visual mapping should help developers quickly identify which services and APIs are associated with each component.
- The image should be added to the following folder:  
  [My VA Folder](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/identity-personalization/my-va)
- Use this image from the Profile backend documentation as a reference:  
  ![Reference Image](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/raw/master/products/identity-personalization/profile/images/navigation.png)  
  Source page: [Profile Backend Documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/profile_backend.md)

**Comment by ACParker89** [comment]
Closing- will need follow up work based on @nickjg231 comment
