### ISSUE TITLE
Adjust Puma Thread Count

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#88463]
Adjust PUMA_THREAD count higher and monitor metrics.

## Tasks

- [x] Increase PUMA_THREAD count in lower envs (e.g. to 12)
- [x] Monitor performance of lower envs
- [x] Increase PUMA_THREAD count in upper envs
- [x] Monitor performance of uppers

## Acceptance Criteria

- [x] Vets API (all envs) is more performant due to puma thread count being increased

## Notes

Extracted from https://github.com/department-of-veterans-affairs/va.gov-team/issues/87124.

**Comment by ericboehs** [comment]
12 is looking like a good place to stop. We're able to scale down our workers a lot as each worker has more threads.
