### ISSUE TITLE
[CST] error messages in support of synchronous tasks for evidence submissions

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#88467]
## Value Statement
**_As a_** user uploading a file via CST
**_I want to_** understand that my file has been received by the VA and attached to the claim, even if the file doesn't immediately show up in CST
**_So that_** I can rest assured knowing my file has been added to the claim and I can go about my business without feeling the need to re-upload the file multiple times

---
## Background Context
Right now @jerekshoe is seeing some users uploading the same file multiple times, and theorizes it might have to do with the language in this banner. The "Note: It may take a few minutes for your file to show here" line is buried, which might be why users miss it and think they need to upload the file again.

[More context in this Slack thread
](https://dsva.slack.com/archives/C056854SVT8/p1706288144959889?thread_ts=1706284907.017799&cid=C056854SVT8)

![Screenshot 2024-01-26 at 10 21 51 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/0064ade5-4b8f-4e13-ade7-a837e3699690)

## Acceptance Criteria

- [x] Put behind synchronous task feature flag
- [x] Investigate whether we need to change the error messages for synchronous calls
- [x] When the API returns an error we tell the user their submission was not a success
- [x] If the transaction is a success, we tell the user the submission was a success

## Engineering Notes
- Add here

## Out of scope
- Add here

## Open questions
- How do we respond to maintenance windows or lack thereof? 
- Argument for using asynchronous jobs is that temporary issues don't prevent submissions necessarily and the user also has a more seamless experience; however, in the case when the job ultimately fails, there is a silent failure. How do we alleviate this tension? 
- Are there cases in which CST remains up but a downstream service is down for maintenance which allows users to still upload files? 
- Should we use 5103 as a test for the synchronous task approach? 
- What are the distribution of errors currently? Knowing this can help us understand better the potential value of using synchronous tasks. We can do this once LH makes their benefits updates. 

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by pmclaren19** [comment]
@jacobworrell Is this a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/76660? Or is this ticket related and something we would work after the above ticket is implemented?
