### ISSUE TITLE
[FE]- Show a more specific error message when we cannot initialize somebody in VA Profile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8847]
## Background
Related ticket : [https://github.com/department-of-veterans-affairs/va.gov-team/issues/6012](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6012)
Related ticket: #9353 

[Slack Convo](https://dsva.slack.com/archives/C909ZG2BB/p1588797312090200?thread_ts=1588795690.086000&cid=C909ZG2BB)

##Content

We can’t load some of your information

We're sorry. We can’t load some of the information in your profile. This may be because you have multiple IDs or accounts at VA.
To find out if this about an account on My HealtheVet:
Contact us at 877-327-0022. We’re here Monday - Friday, 8:00 a.m.- 8:00 p.m. ET. If you have hearing loss, call 800-877-3399.
Tell the representative that you tried to sign in to VA.gov, but got an error message that you may have more than one My HealtheVet account or ID.
Or, you can [fill out a My HealtheVet online help form to get help signing in.](https://www.myhealth.va.gov/mhv-portal-web/contact-us)
To find out if this about an account with the Department of Defense:
You can [submit a request to get help signing in.](https://www.accesstocare.va.gov/sign-in-help)

![Screen Shot 2020-05-29 at 3.52.44 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/0a01faf9-d198-450c-b018-68bec9f49e18)

## Tasks
- [ ] Show a more specific error message when we cannot initialize somebody in VA Profile

## Acceptance Criteria
- [ ] More specific error message has been created
- [ ] investigating the current list of error codes from VA Profile?

**Comment by Samara-Strauss** [comment]
Per conversation in [101](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/101), we think that the issue here is that the veteran we've been talking to has multiple IDs somewhere, so we can't initialize him in VA profile. It appears that the SSOe team is working on this in [4235](https://github.com/department-of-veterans-affairs/vets-api/pull/4235) and [12548](https://github.com/department-of-veterans-affairs/vets-website/pull/12548), and once this work goes out, it seems like we would not let people log in at all if we detect they have multiple IDs. If that's the case, that would mean that this problem would have to be resolved before someone could get to the profile.

In the meantime, we should provide some sort of messaging that lets people know we can't load their profile. @mshea0606 this will need a design ticket. I'm thinking a couple decisions need to be made:

- Do we keep this messaging super generic?
- If we decide to get specific, do we want to include mention of the potential ID issue? If we did, we could over some helpful avenues that [Peggy outlined here](https://github.com/department-of-veterans-affairs/vets-website/pull/12548#issuecomment-627494857) to resolve the ID issue.

**Comment by erikphansen** [comment]
TODO:
- [ ]  determine which VA Profile error codes are related to failure to initialized.

**Comment by mshea0606** [comment]
[VA Profile error codes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Profile%20Error%20Codes.md)

**Comment by erikphansen** [comment]
Looks like CORE100. I took a screenshot of the console during the screenshare. @Samara-Strauss did you happen to record that session on May 6?

<img width="1433" alt="vet360 init error response redacted" src="https://user-images.githubusercontent.com/20728956/83207228-82d40f00-a107-11ea-9707-f5a7aec44c7d.png">

**Comment by erikphansen** [comment]
I don't understand why the error codes we are looking for (https://github.com/department-of-veterans-affairs/vets-website/blob/655fca74b24378320141777a409dc351f72a3bb6/src/platform/user/profile/vet360/util/transactions.js#L19-L57) all have `VET360_` prefixes but the code the vet got back from the API (https://github.com/department-of-veterans-affairs/vets-website/blob/655fca74b24378320141777a409dc351f72a3bb6/src/platform/user/profile/vet360/util/transactions.js#L19-L57) does not. @lihanli or @ncksllvn do you have any idea why our FE code would look for `VET360_` errors? I know the VA Profile folks [said that they don't use that prefix](https://dsva.slack.com/archives/C7TE0PFTL/p1588797757094300), so I assume we must add it or we used to add it or something along those lines.

**Comment by ncksllvn** [comment]
I'm not sure. I think it was just that we were allowing certain Vet360 error codes to pass through the API, but prefixing them with `VET360_` to indicate to Vets-API where the error originated

**Comment by Samara-Strauss** [comment]
> @Samara-Strauss did you happen to record that session on May 6?

I did – I think I can safely email it to you. We're not allowed to upload to Github because of PII.

**Comment by lihanli** [comment]
@erikphansen the `VET360_` prefix is added by vets-api. we receive an error code from va profile, then add the `VET360_` prefix, this only occurs during non-asynchronous vet360 calls though. when you make an api request to lookup the status of a transaction, we don't do this error handling and the vet360 error code is passed through unchanged.

**Comment by erikphansen** [comment]
Thanks @lihanli. That makes me think there was an oversight or miscommunication somewhere because the FE is only looking for codes with that prefix. I see no good reason we shouldn't adjust our FE code to simply look for the existence of the VA Profile codes, with or without the prefix.

**Comment by erikphansen** [comment]
A PR for this has been merged. I don't think we can really accurately validate it so I'm just closing this.
