### ISSUE TITLE
BE | Profile | Direct Deposit | Update Control Info Logging

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#88488]
## Background
The `V0::Profile::DirectDepositController` is logging control information on `GET` and `PUT` requests.

## Tasks
- [x] Remove control info logging on GET requests.
- [x] Remove control info logging on PUT requests.

## Acceptance Criteria
-  [x] Verify control info is not being logged in staging.
