### ISSUE TITLE
[Design] Iterate on address selection screen for when only a permanent address is displayed 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8849]
## User Story or Problem Statement
When a Veteran only has a permanent address being passed through the API, there is only one radio button to select. This goes against convention, so we need a design to account for that. How might we update the card's design to align with UI best practice?

## Goal
_For the designers and frontend engineers to come up with a solution to display one address being passed through the API that aligns with UI best practices_

## Objectives or Key Results this is meant to further
- _MDT development_
---
## Tasks
- [x] _Designers and frontend engineers sync to discuss the issue with the existing design and collaborate on a solution_
- [x] _New design is uploaded to InVision for the frontend engineers to reference as they develop_
- [x] _InVision mockup is linked in this ticket as a comment_
- [x] _Ticket for frontend implementation is created_

## Acceptance Criteria
- [x] _InVision mockup is linked to this ticket as a comment_
- [x] _Ticket for frontend implementation is created_
---

**Comment by rileyorr** [comment]
I've uploaded [the design](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/416620566_C1_P2-_Only_Perm_Address_-_Radio_Will_Just_Be_A_Button) to InVision

**Comment by rileyorr** [comment]
I created a [ticket for the frontend team to implement the new design](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8878) and posted it in Slack for the team's awareness.
