### ISSUE TITLE
PgHero cleanup: Resolve unused indexes in prod

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#88500]
## User Story
As an owner of vets-api's postgres database, I want to remove unused indexes, so that database writes are faster.

## Issue Description
http://pghero-prod.vfs.va.gov/space says there are 65 unused indexes. The list is pasted below. Some of these could be used in lower environments but unused in higher envs because of a feature flag. Or they could be new and not used enough yet. The source code for [unused_indexes](https://github.com/ankane/pghero/blob/master/lib/pghero/methods/indexes.rb#L71) returns a list of indexes that have been scanned less than 50 times (`max_scans`) and are not unique indexes.
```
index_account_login_stats_on_current_verification
index_account_login_stats_on_dslogon_at
index_account_login_stats_on_idme_at
index_account_login_stats_on_logingov_at
index_account_login_stats_on_myhealthevet_at
index_accreditations_on_accredited_organization_id
index_accredited_individuals_on_full_name
index_accredited_individuals_on_location
index_accredited_individuals_on_poa_code
index_accredited_organizations_on_location
index_accredited_organizations_on_name
index_appeal_submissions_on_user_account_id
index_async_transactions_on_created_at
index_async_transactions_on_id_and_type
index_async_transactions_on_source_id
index_base_facilities_on_lat
index_base_facilities_on_location
index_base_facilities_on_name
index_claims_api_auto_established_claims_on_source
index_covid_vaccine_registry_submissions_2
index_disability_contentions_on_lay_term
index_disability_contentions_on_medical_term
index_dr_evidence_attachment_validation_on_guid
index_drivetime_bands_on_polygon
index_education_benefits_claims_on_created_at
index_education_benefits_claims_on_submitted_at
index_education_stem_automated_decisions_on_claim_id
index_education_stem_automated_decisions_on_user_account_id
index_form526_job_statuses_on_bgjob_errors
index_gibs_not_found_users_on_edipi
index_health_quest_questionnaire_responses_on_user_account_id
index_invalid_letter_address_edipis_on_edipi
index_ivc_champva_forms_on_form_uuid
index_lighthouse526_document_uploads_on_aasm_state
index_lighthouse526_document_uploads_on_form526_submission_id
index_lighthouse526_document_uploads_on_status_last_polled_at
index_mhv_opt_in_flags_on_feature
index_mhv_opt_in_flags_on_user_account_id
index_oauth_sessions_on_hashed_device_secret
index_oauth_sessions_on_refresh_creation
index_oauth_sessions_on_user_verification_id
index_on_reg_num_and_type_for_accredited_individuals
index_va_notify_in_progress_reminders_sent_on_user_account_id
index_vba_docs_upload_submissions_status_created_at
index_verified_representatives_on_email
index_verified_representatives_on_ogc_number
index_veteran_device_records_on_device_id
index_veteran_organizations_on_location
index_veteran_organizations_on_name
index_vye_address_changes_on_user_info_id
index_vye_awards_on_user_info_id
index_vye_bdn_clones_on_export_ready
index_vye_bdn_clones_on_is_active
index_vye_direct_deposit_changes_on_user_info_id
index_vye_user_infos_on_bdn_clone_active
index_vye_user_infos_on_bdn_clone_id
index_vye_user_infos_on_bdn_clone_line
index_vye_verifications_on_user_profile_id
index_vye_verifications_on_user_info_id
index_webhooks_subscription
index_wh_assoc_attempt_id
index_wh_assoc_notification_id
index_wh_notify
index_wk_notify_processing
```
_note: ChatGPT arranged and alphabetized this list, so there could be errors. It could also be outdated by the time this ticket is being worked on. Please verify at [PgHero](http://pghero-prod.vfs.va.gov/space)._
## Tasks
- [ ] Before starting, share this list in #vfs-all-teams Slack asking teams to address any indexes on tables they own. 
- [ ] We don't want to delete any that will be used, so it might be safe to start with the oldest ones. For each index, if the index was created a year (9 months? 🤷)  or more ago, create a migration to remove it.
- [ ] Monitor the deploy to each environment, ensuring the migration goes through. 

## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] All unused indexes are accounted for (either removed or have a reason to be considered "unused")
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
- Check that there are fewer than 65 unused indexes on http://pghero-prod.vfs.va.gov/space
