### ISSUE TITLE
Remove the "My" from all VA311 references in the right rail section of benefit hub pages

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8851]
In a review, we were informed by the VA311 team that there was a change to move away from using "MyVA311" and to just use "VA311". 

## Goal
- Find and update any instances of "MyVA311" to instead read as "VA311" on the site. We have removed some references already, but need content update to remove from the benefits hub page in the "Right Rail" section in the right rail or by editing the content directly (content type: Support Service).

---
## Tasks
- [x] Review, investigate this section of content that references "MyVA311"
- [x] Update to instead be "VA311"

## Acceptance Criteria
- [x] No instances of "MyVA311" remain on the right nav of the benefit hub pages
---
Known places we currently have MyVA311 on the site:
* ~~"Contact Us" in the header~~ (done)
* Some of the "Ask Questions" modules on hubpages

**Comment by kelsonic** [comment]
PR closed as @ncksllvn already merged in fixes into `vets-website`, but it looks like all references to this are actually in Drupal. @RLHecht could you help with this on the Drupal-side? 🙂

**Comment by RLHecht** [comment]
I've updated the right rail for all the benefit hubs to change MYVA311 to VA311.

**Comment by RLHecht** [comment]
These are validated on the live site. Closing ticket. FYSA @stephorkandatx
