### ISSUE TITLE
[SC/HLR] Filter out Disqualifying Issues

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#88513]
## Value Statement

**_As a_** veteran

**_I want to_** see a list of contestable issues that does not contain items that would disqualify the request

**_So that_** my request is processed in a timely and accurate manner.

---

## Background Context

- After speaking with Steven NG from the IBM Mail Solutions team, I learned that a request with issues that match the keywords "apportionment" or "attorney fees" would be disqualified and require more processing. We currently filter out issues that contain "deferred", so we should do the same.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Veterans are not presented with issues they cannot contest.

## Acceptance Criteria

- [ ] _Issues that contain the keywords are filtered out_

## Open questions

- Add here

## Tasks

- [ ] _Filter out the issues_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
@skylerschain to test in staging after updating VBMS mock data (since he has access)

Notes:
- Contestable issues page in [Supplemental Claims](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/contestable-issues) and [HLR](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/contestable-issues)
  
  <img width="579" alt="Supplemental claim contestable issues page" src="https://github.com/user-attachments/assets/906c1f11-bc60-4953-99d2-4e1ae880afee">

- HLR contestable issues won't show up if their decision date is more than one year in the past
- When adding "deferred", "apportionment" or "attorney fees" text to the issue, include it in the key-phrase in either the `ratingIssueSubjectText`, `description`, or both

  <img width="923" alt="contestable issues API response in JSON format" src="https://github.com/user-attachments/assets/ed09db66-c7ba-4b6d-9596-27adbdb8d2b4">

**Comment by anniebtran** [comment]
@Mottie needs help to add issues in VBMS cc: @skylerschain

**Comment by anniebtran** [comment]
Same as above ^

**Comment by skylerschain** [comment]
Since we don't know exactly what maps to the fields referenced above, we have to test a few things from VBMS to see if contentions get filtered. 

I added "Attorney fees" as what's called a "Special issue" for the following contention and user:
vets.gov.user+46@gmail.com
Contention: Abscess, brain

I've asked Andrew to push this claim (ID 600471711) through to rating, and once that's done we can check to see if that contention is filtered out of the contestable issues list.

**Comment by dfong-adh** [comment]
Robin to schedule meeting with Skyler

**Comment by dfong-adh** [comment]
Delayed due to issues with VBMS, should be able to check again once fixed

**Comment by dfong-adh** [comment]
Skyler working on getting a claim with disqualifying issues passed through to verify a filter is working. Robin will help support validation

**Comment by dfong-adh** [comment]
Skyler and Robin to discuss what's causing the disqualifying issues aren't showing up

**Comment by shaunburdick** [comment]
Added 'attorney fees' to a claim and it didn't see them come through.
Unsure how the keywords are getting associated to a claim.

Need JSON examples of issues with the keywords. @shaunburdick will reach out to Stephen Ng and/or Michel McDonald.

**Comment by eileen-coforma** [comment]
Skyler to meet with LH (Michael Hobson) to get examples of contestable-issues list to see if we can filter out by terms.
OR reach out to Stephen Ng

**Comment by eileen-coforma** [comment]
Robin reached out. No response yet.

**Comment by eileen-coforma** [comment]
Still no response from Steven
