### ISSUE TITLE
Improve supporting documents page

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#88521]
## Description
As part of the usability study conducted in early spring, we found some opportunities to improve the experience for veterans as they complete the 527EZ form.

Design ticket #88400 has the background information for this specific change to the dependent assets that would result in changes to the supporting docs page

## Designs
- [Supporting docs](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5134-33078&t=wPk9ygJ7Bd4uJIpS-11)
- [Submit docs](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5134-35974&t=wPk9ygJ7Bd4uJIpS-11)
- [Confirmation page](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5134-37445&t=wPk9ygJ7Bd4uJIpS-11)

## Acceptance Criteria
- [x] This change is kept behind a feature flag; will need to go through Collab Cycle (TBD whether this is the same feature flag that will be created for the other tickets or we create a new feature flag specific for this change.)
- [x] Web pages(s) are update to match the designs
- [x] All automated tests are update and passes

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)
- [x] Back-end work to set up feature flag (TBD)
- [x] Front-end work

## Review
- [ ] Designer/Product has signed off on pages in staging
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89967
```

**Comment by mtri** [comment]
Figma:
[Supporting docs](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5134-33078&t=wPk9ygJ7Bd4uJIpS-11)
[Submit docs](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5134-35974&t=wPk9ygJ7Bd4uJIpS-11)
[Confirmation page](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5134-37445&t=wPk9ygJ7Bd4uJIpS-11)

**Comment by aplatt-coforma** [comment]
Staging review link: https://staging.va.gov/pension/apply-for-veteran-pension-form-21p-527ez

**Comment by danbrady** [comment]
Differences in content between staging and design found in this [figma file](https://www.figma.com/design/DvZN50R2KnQbdSfwkw8Rgm/527-Staging-Reviews?node-id=7-844&t=tbEeQdYPoK0eK2Ir-1).

Note: Confirmation page wasn't checked as we discovered an issue accessing it. @ToddWebDev confirmed the issue and is currently debugging it.

**Comment by danbrady** [comment]
Issue fixed and staging review completed. Differences can be seen in [this figma file](https://www.figma.com/design/DvZN50R2KnQbdSfwkw8Rgm/527-Staging-Reviews?node-id=7-844&t=4jB2oojdgQsxi29d-1).

**Comment by danbrady** [comment]
Staging fixes confirmed.
