### ISSUE TITLE
Investigate increased Error rate on Direct Deposit

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8852]
## Background

We are still seeing a pretty high error rate for the "Other" errors for direct deposit even since the EVSS issue from last week was resolved.

[Direct Deposit Analytics](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p187673796/_u.date00=20200430&_u.date01=20200506/)

"Other" errors are normally in single digits. Here are the stats from right before the EVSS problem:

<img width="1269" alt="Screen Shot 2020-05-06 at 5 19 53 PM" src="https://user-images.githubusercontent.com/34068740/81311611-9e418200-9053-11ea-8771-7a3b4c3099ab.png">

However, since the EVSS problem was resolved, we are seeing a really high amount of "other" errors and NO additional errors, which seems wrong given that we normally were seeing pretty regular occurrences of different DD errors:

![image.png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/b05663d2-5348-4fac-878e-6014f5dfb95a)

<img width="1274" alt="Screen Shot 2020-05-06 at 5 20 45 PM" src="https://user-images.githubusercontent.com/34068740/81311659-aef1f800-9053-11ea-81cb-f3e2898c23ed.png">

## Tasks
- [x] Explore why we may be seeing increased "other" errors 
- [x] Discuss with team as needed
- [ ] Resolve issue, or create plan to resolve issue if significant follow up work/tickets are needed

**Comment by lihanli** [comment]
direct deposit backend errors:
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/116350/?query=is%3Aunresolved%20controller_name%3Appiu

**Comment by erikphansen** [comment]
To confirm, those form submission events that include `direct-deposit-information` _are_ indicative of a successful submission/save/update

**Comment by erikphansen** [comment]
I'm guessing that the error codes we get from EVSS PPIU changed after their fix and nothing is really wrong in a _major_ way. We just aren't able to accurately record the error type which means we also aren't showing the user specific error messages, just the default/fallback error.

**Comment by erikphansen** [comment]
@lihanli Based on what I see in Sentry, it looks like EVSS has changed how it's reporting errors and our API layer isn't handling them properly. What do you think?

**Comment by erikphansen** [comment]
@lihanli When I was investigating DD errors in the fall I was looking at this http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/76846/ and you can see that those errors stopped getting reported around the time these errors started showing up: http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/116350/

**Comment by lihanli** [comment]
@erikphansen ok thanks for the info i'll work on getting it fixed

**Comment by mshea0606** [comment]
Update VetsAPI processing of changed EVSS data #8887 has been created.

**Comment by mshea0606** [comment]
Thanks @lihanli !  [Backend] Update VetsAPI error handling of EVSS data #8887 has been created

**Comment by Samara-Strauss** [comment]
Thanks for this, guys! @erikphansen is your work done here? If so, we can close this ticket. If not, let's leave it open.

**Comment by erikphansen** [comment]
yeah. more work might come out of the BE ticket Matt made, but I really doubt it.

**Comment by Samara-Strauss** [comment]
Sounds good. We can create follow-up tickets if needed.
