### ISSUE TITLE
HLR & NOD | On review page show checkbox selections in question answer format instead of selected value

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#88527]
## Value Statement

**_As a_** Veteran

**_I want to_** know the options I've selected

**_So that_** I can easily review my answers

---

## Background Context

- On HLR and NOD, we currently show selected checkbox values as individual line items with "selected" as a value, which isn't as plain-language or user-friendly.

IE. Instead of "The service connection" on the right, and "selected", it could say
"What you disagree with" and on the right, and "The service connection" (or selected options)

Current format:
<img width="316" alt="Screenshot 2024-07-16 at 4 16 11 PM" src="https://github.com/user-attachments/assets/1ffa1ee3-4c7f-4077-b255-643e4700a11b">

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] On Review and Submit pages, checkbox values show in question and answer format, instead of answer and selection format.

## Designs and Build Notes

- Board Appeal [FIGMA](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1595-8805&t=Pgw48PC51tZeNUXn-11)
- Higher-Level Review [FIGMA](https://www.figma.com/design/OxukHeNtSkCDbdmLxD5k9A/Higher-Level-Review-(VA-0996)?node-id=853-43283&t=fURpMzBiXB2HaknW-11)

### Enablement team (if needed)
@jstrothman 

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Changes are now available in staging for validation

**Comment by eileen-coforma** [comment]
Looks good 👍
