### ISSUE TITLE
Discovery: Create List of Topics for What We Can Help With page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88540]
## Issue Description
Platform Content Team needs to create a [list of topics](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3306520577/Complete+List+of+Content+Team+Topics) we frequently handle as a first step toward a What We Can Help With page. 
  
---
## Tasks
Each Content Team Member add topics 
- [ ] Joe
- [ ] Cheryl
- [ ] Jill
- [ ] Brian
- [ ] Lauren

## Acceptance Criteria
- [ ] Team will have a list of topics ready for the What We Can Help With page
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
List has been created, moving on to categories

**Comment by jknipes** [comment]
Reopening ticket, was closed prematurely. Need to give team more time to contribute.

**Comment by jknipes** [comment]
Confirmed with team, Topics chosen, closing ticket as _Done_
