### ISSUE TITLE
BE | Profile | Personal Information | Confirm that preferred name accepts non-ASCII characters

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#88556]
## Background
VA Profile has stated that the preferred name validation rules should allow for non-ASCII characters.

## Tasks
- [x] Run tests against VA Pro QA environment to determine if preferred name accepts non-ASCII characters.
- [x] Record details of each request (including date/time) and outcome.

## Acceptance
- [x] Email results to Danny Reed's team (reply to email thread).

**Comment by tpharrison** [comment]
@mtcA6 This ticket is linked to https://github.com/department-of-veterans-affairs/va.gov-team/issues/71381.

I'll leave them both open for now, but will close both out if the tests pass.

**Comment by tpharrison** [comment]
@mtcA6 I ran the tests and they failed (except for using a blank space).  I'm going to close this out since the other ticket is still open in the backlog.

**Comment by mtcA6** [comment]
VAPROFILE-10427 - this is a research ticket the team could undertake but they might need a more formal intake.
