### ISSUE TITLE
Collaboration Cycle for Modernized Check-in, Pre-Check-in, Medication Review

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#88553]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1339) for all feedback and findings tickets associated with this Collaboration Cycle initiative. 
 
 ## VFS product information

### VFS team name

Modernized Check-in

### Product name

Pre-Check-in

### Feature name

Medication Review

### GitHub label for team

HCE-Checkin

### GitHub label for product

pre-check-in

### GitHub label for feature

medication-review

### Public DSVA Slack channel for VFS team

https://dsva.slack.com/archives/C022AC2STBM

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

June 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [X] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.
Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C022AC2STBM/p1721222230917189)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent instructions</summary>

**NOTE: Design Intent was done together with the Appointments Team via this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85480)**

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts for review**
[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [x] User flow - The user flow won't change as a result of this text addition, but here are the current flows where the text will show.
    - [Pre-check-in](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=937-28573)

Not required, but nice to have:
- [x] Wireframes
    - [Pre-check-in](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32909&t=MybgwPnCCJcgmy0u-4)

Optional:
- [ ] Research plan
- [x] Any other artifacts you have so far
    - [Shared component (annotated)](https://www.figma.com/design/enGXBfuvpWJOQp0onrWgHs/%5BDRAFT%5D-Content-Library-%7C-MHV---Unified-Appointments?node-id=299-1327&t=vjIvoMm3qNEDnAU8-4)
    - [All locations we expect the content to show](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/projects/2024-05-medication-language-update/medication-content-locations.md)
    - [CAIA Ticket](https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/82472)
  
##### Governance Team actions
- [ ] [Design Intent Slack thread with VFS team](https://dsva.slack.com/archives/CMNQT72LX/p1718130007564409)
- [ ] Meeting date/time: June 14 at 11:30am ET
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/0l7-xVSXnNM-wjTr3DfQ4AjIH7-iPOt13XqvX0wjWP7jtEAQUTG4sPqm_PO_Jjzi.nzr5LgOxPE9iGHqW)
  - Passcode: %d@@5ZNX
- Accessibility
  - [x] Feedback added to milestone
  - [ ] No feedback
- Design
  - [x] Feedback added to milestone
  - [ ] No feedback
- IA
  - [x] Feedback added to milestone
  - [ ] No feedback
  
##### VFS team actions
- [x] Not needed
- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Not needed
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**
  
See Platform guidance on [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts). Platform findings are based solely on the staging URL and test users provided, as reviewed during the four days before the Staging Review meeting. Any test cases not covered or any ongoing work taking place during the review period may not be reflected in those findings.  

**Product artifacts** 
- [x] Staging URL
    - staging.va.gov/health-care/appointment-pre-check-in (NOTE: each URL is customized per Veteran session, see instructions below)
- [x] Specify which pages are included in the review      
     - /health-care/appointment-pre-check-in/complete
     - /health-care/appointment-pre-check-in/appointment-details
     - /health-care/appointment-pre-check-in/what-to-bring
- [x] Staging test user information 
    - URLs are customized per Veteran session, please refer to the [Instructions for Accessing Patient Check-in in the Staging Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/staging-instructions.md)
  
**Note:** Please double-check that you've provided staging access information appropriate for testing the tool or feature. Don't put staging credentials in your va.gov-team ticket; store [test user information, passwords, and tasks](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-accessible-example.md) in a .md file in the va.gov-team-sensitive repository.

**Content artifacts**
- [x] [CAIA Ticket](https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/82472)
  
**IA artifacts**
- [x] Please include a link to any [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) feedback you received, including an IA review document or intake form.
  - [x] Content and IA feedback has been collected and addressed in [Figma](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32909&t=YxOMov2wQ4dsnXwq-4) with Laura L, Mikki and Kristen M. [CAIA Ticket for tracking purposes](https://app.zenhub.com/workspaces/appointments-fe-ux-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/82472).   

**QA artifacts**

An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
- [x] [Regression test plan](https://dsvavsp.testrail.io/index.php?/plans/view/5719)
- [x] [Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/5718)
- [x] [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/910)
- [x] [Summary(Defects) reports](https://dsvavsp.testrail.io/index.php?/reports/view/908)
- [x] E2E tests
  - [Day-of](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/day-of/tests/e2e)
  - [Pre-Check-in](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/pre-check-in/tests/e2e)
  - [Shared](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in/tests/e2e)
- [x] [Code coverage](https://github.com/user-attachments/assets/b5b9ebff-51c8-4bd4-9993-d61e4ea44118)

| Statements | Branches | Functions | Lines |
|---|---|---|---|
| 89.78% | 82.18% | 87.41% | 89.77% |
  
**Accessibility artifacts**
  
- [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90152).
  
##### Platform actions
- [ ] [Slack thread with VFS team](https://dsva.slack.com/archives/CMNQT72LX/p1723035040304709)
- [ ] Meeting date/time: August 15, 2024 at 1:30pm ET

##### Platform actions

- [x] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/WGHSVeAN2qRGDHVLVSzyd6Yta7mTgntNRWVXPRDVQTZX9AX0RWF7rXXayMYqeOev.W15IS7vOUfbfJ4kk) 
  - Password: `wDiY5eW&`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [x] Not needed, ONLY static non PHI/PII content added to existing application
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by loripusey** [comment]
Please note that we are adding content only and the content has already gone through CAIA and IVC approval via this [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85480)for the Appointments Team; we would like to skip to Staging Review

**Comment by loripusey** [comment]
All issues have been addressed; will go to production on 8/27; closing this ticket
