### ISSUE TITLE
Tip of the Sprint [S6]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88567]
### Purpose
The Content team provides a new "content tip" every sprint with the #platform-content channel's audience. The purpose of this is to provide continuous style guidance and re-enforce content best practices for contributors of the Platform website.

### Tasks
 

- [x] Pick a content tip idea from the style guide
- [x]  Draft a content tip Slack post, similar to [any of these in the Archive.](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3239444481/TIP+OF+THE+SPRINT+-+Archive)
- [x]  Get feedback from rest of Content team
- [x]  Copy and paste the team-approved announcement of our Tip of the Sprint in to the platform-content slack channel.
- [x]  Schedule for first Monday of the Sprint
- [x]  Copy and paste Tip in the [Tip of the Sprint Archive](https://vfs.atlassian.net/wiki/spaces/CIT/pages/3239444481/TIP+OF+THE+SPRINT+-+Archive). 
- [x]  Update the [Tip of the Sprint Master List](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2493743148/TIP+OF+THE+SPRINT+-+Master+List) to reflect this new post. 

Acceptance Criteria:

- [x]  A new content tip will be posted on #platform-content for this sprint.

**Comment by BSmolensky** [comment]
All tasks complete. Once post goes live at 1pm on 7/22, this ticket can be closed.

**Comment by jknipes** [comment]
Closing this ticket as _Done_
