### ISSUE TITLE
Finalize designs for dashboard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88573]
## User Story
As a Governance team member, I want to finalize the designs proposed for the Staging Review dashboard so that I may begin working on implementation.

Assignee: @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
In ticket #87322 we drafted some lo-fi designs of proposed changes to the SR Dashboard that use the new descriptive tag data. Now we must implement feedback from our PO as well as take into consideration any feasibility concerns from ticket #87323.

## Impacted Artifacts
[mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720191529751/a3eda30d1910afbad7680620fc08910449197d7c?sender=4d3b1176-3e52-4b46-9191-8af1e6066add)

## Tasks
- [x] If applicable, update designs so that they mock what would be seen in Domo
   - No need to use real data, but all labels should be accurate
- [x] If applicable, update designs to reflect feedback from PO
- [x] If applicable, update designs per feasibility findings from ticket #87323

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have finalized our designs for the Staging Review dashboard in Domo

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@KKitagawa-Bosch I looked thru the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720191529751/a3eda30d1910afbad7680620fc08910449197d7c?sender=u870c8d9c6b47768924793768) again and resolved any outstanding comments. No changes need per Matt (PO) or Ian. Ready for your review.

**Comment by KKitagawa-Bosch** [comment]
Looks good to me! Compared everything to those comments and looks like it's all resolved.
