### ISSUE TITLE
[CST] Add margin top to the Need Help section

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#88588]
## Background Context
@jstrothman reached out and asked if we could add a top margin of 80px to the `NeedHelp.jsx` element for all CST pages.

It currently looks like this where there is no top margin:
<img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnJwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ccb74ac3177de4e08e64dc647032b77397e4036/Screenshot%202024-07-17%20at%208.45.39%E2%80%AFAM.png" alt="Screenshot 2024-07-17 at 8.45.39 AM.png" />

Julie would like it to look like this:
<img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0hwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef36f43be50a13ae5f372376ec7e023a8da3cb5d/Screenshot%202024-07-16%20at%209.45.48%E2%80%AFAM.png" alt="Screenshot 2024-07-16 at 9.45.48 AM.png" />

### Design
@skylerschain 

### Enablement team (if needed)
@member of team

## Engineering 

Components that use the Need Help section:
- ClaimDetailLayout
- AppealHelpSidebar
- AskVAPage
- ClaimEstimationPage
- DocumentRequestPage
- YourClaimsPageV2

## Open questions
- @skylerschain 

## Tasks
- [ ] Update the NeedHelp section to have top padding `className="vads-u-margin-top--10"`
- [ ] Verify that the components that use the Need Help section look correct with 80 px padding

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The Need Help section has a top padding of 80 px

**Comment by pmclaren19** [comment]
Duplicate ticket - replaced by https://github.com/department-of-veterans-affairs/va.gov-team/issues/88581
