### ISSUE TITLE
[PRODUCT] Run Test Cases for Functional Testing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#88602]
## Description
As a team, we need to perform functional testing so that we can ensure our feature is ready for release. 

## Tasks
- [x] Run these TestRail Test Cases
  - [x] [Medication Review - Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/5718)
  - [x] [Medication Review - Regression Plan](https://dsvavsp.testrail.io/index.php?/plans/view/5719)
