### ISSUE TITLE
[A11Y/Platform]: Create accessibility cookbook article

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#88618]
## Value Statement
**_As a_** accessibility specialist
**_I want to_**  write the second recipe for the accessibility cookbook
**_So that_** the accessibility cookbook has another recipe completed.

---
## Background

We created the [accessibility cookbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/accessibility-cookbook.md) as a place to record solutions for all sorts of accessibility issues we run into in our day-to-day work. We want to create some content around accessibility annotations.

## Acceptance Criteria
- [x] New recipe is complete and uploaded to cookbook directory

## Tasks

- N/A

## How to Measure Success
_- Define the expected result and where to measure it._

- N/A

## Out of scope

- N/A

## Definition of Ready

- N/A

## Definition of Done
- [x] One topic is completed, and added to the cookbook.
- [x] A consistent "recipe" structure is followed. See cookbook.
- [x] One accessibility specialist has reviewed the content.

**Comment by davidakennedy** [comment]
I've picked this ticket up, and am working on an Accessibility Cookbook article on "When a screen reader needs to announce content".

**Comment by davidakennedy** [comment]
This is drafted, and getting some feedback from another accessibility specialist on the ADE team.

**Comment by davidakennedy** [comment]
Edits have been made and the content is published in the [accessibility cookbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/ADE/accessibility-cookbook.md#when-a-screen-reader-needs-to-announce-content).
