### ISSUE TITLE
[CAIA Intake] <Benefits Dependents Experience>: <Claim Submission Failure Email Notification>

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88620]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Benefits - Dependent Experience
- **OCTO product owner:** Ryan Powers
- **Product name:** 21-686c and 21-674 online form flow
- **Product manager:**  Laura Steele
- **Slack channel:** #benefits-dependents-management
- **Dedicated content writer on your team (if you have one):** none
- **Dedicated a11y specialist on your team (if you have one):** none

### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [x] Something else: Updating copy in the existing failure notification email and then adding that email notification to all benefit claims.

### What's the nature of your initiative and desired outcomes?

Send an email notifying Veterans that their benefit claim failed to submit on VA.gov. This email will only be sent if all backup submission pathways have been exhausted, and VA.gov is unable to submit the claim. This email currently exists in some form on the 686c/674 (dependents) and 526 (disability) claims, but the language needs to be standardized, so the email can be added to all benefit claims.

Outcome summary:
- Notify claimants of a failed claim on VA.gov
- Claimants understand next steps
- Claimants have a clear understanding of their failed claims status (e.g., it was not submitted)

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

- Failure notification email currently exists on the 686c/674 and 526 claims, but the language is outdated and not consistent 

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
 **Note** If you checked yes: Incremental launches require dynamic content. You'll need to ask your developer to build a React widget and provide CAIA with the ID code. CAIA will provide widget content and add the widget to your product’s static page. Please refer to this [GitHub page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md) for more information.
 
- [x]  I acknowledge that if I change the launch to be incremental, or change it from incremental to 100%, I must notify CAIA of this change as these additional steps will impact deadlines.

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Copy from existing 686c/674 and 526 failure emails](https://docs.google.com/document/d/1ikFTS19QHdYJb3Oi8IU8iI7-IAkuy0XT7M3iVJKDdbU/edit?usp=sharing)

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by steele-lm** [comment]
@emilytheis @ryan-powers-va @tblackwe @Dene-human @fiorella-io @ajialeilani @lisacapaccioli This is a request to CAIA to standardize the failure email notification language across all benefit forms. I included [examples](https://docs.google.com/document/d/1ikFTS19QHdYJb3Oi8IU8iI7-IAkuy0XT7M3iVJKDdbU/edit?usp=sharing) of the current email language from 686c/674 and 526 forms.

**Comment by fiorella-io** [comment]
Hi Lily, Laura is out this week. I just granted you access

**Comment by steele-lm** [comment]
Noting that OCTO is currently working on a failure email template that all benefit forms will leverage through VA Notify.

**Comment by fiorella-io** [comment]
Hello @strelichl 

We want to use this ticket to review the content of the following email templates:
- [674 action needed email](https://dsva.slack.com/docs/T03FECE8V/F07S0PD89MY?focus_section_id=temp:C:OSMca9b625be60a4e048c839fa39)
- [686c and 674 action needed template](https://dsva.slack.com/docs/T03FECE8V/F07S0PD89MY?focus_section_id=temp:C:OSM591dc76e19f24b7ca6be2a191)

## 674 email
In the current [674 paper form](http://www.vba.va.gov/pubs/forms/VBA-21-674-ARE.pdf), we list two addresses on page 3. If the Veteran receives disability benefits, they need to mail the paper form to the Evidence Intake Center. If the Veteran receives pension benefits, they need to mail it to the Pension Intake Center. [See flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727982161909/b7dea52f3be33a212120eac7c9de80b7a58ea786?wid=0-1730146880504). We'd like to get a second set of eyes to this email to ensure Veterans understand the difference between the addresses.


## 686c and 674 combined email
Also, we'd like your help with the combined 686c and 674 action-needed email.

Currently, when the Veteran is going through the add/remove dependent flow(686c) in the current online form, they are unaware of when they triggered the 674 (add/remove school-age dependent child) embedded form. Please take a look at [this simplified flow ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727982161909/b7dea52f3be33a212120eac7c9de80b7a58ea786?wid=0-1730148093175)for reference. 

For this combined email, we'd like to ensure the Veteran understands that they have completed two forms. (We'll be adding tickets to our backlog to improve this awareness in the online form). Also, it is important to ensure that Veterans fully understand that they might need to mail both paper forms to the same Evidence Intake Center or different Intake Centers (Pension). 

Please let us know when we can meet to explain this complexity better. 

cc/ @steele-lm @ajialeilani @Dene-human

**Comment by aprocik1** [comment]
@fiorella-io, can you grant me edit access on your canvas? There a few small updates I'd like to recommend in comments. Thanks!

**Comment by aprocik1** [comment]
@fiorella-io, I just reviewed your 674 email draft. I left two comments with recommended updates. Let me know if you have any questions!
