### ISSUE TITLE
Medallia - Add feedback button to checklist resource page template

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#88656]
## Issue Description
It appears the digital survey feedback button is missing from this[ resource page](https://www.va.gov/resources/what-to-bring-to-create-your-online-sign-in-account/)

<img width="1202" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46d258e4c9da414477f22f5b98a6267eefc32bed/Screenshot%202024-07-17%20at%202.37.06%20PM.png" alt="Screenshot 2024-07-17 at 2.37.06 PM.png" />

As a user visiting the VA resource page, I want to leave feedback, but cannot find the feedback button that is on other pages of the site. This button is crucial for providing feedback on the resources provided, which helps improve the content and user experience.

---
## Tasks
- [ ] Add feedback button to checklist drupal template

## Acceptance Criteria
- [ ] The digital survey feedback button is visible on the resource page
- [ ] The button is functional and allows users to submit feedback
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
