### ISSUE TITLE
[Design] My VA Forms Status: Update figma files

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#88655]
## Background
Follow usability study synthesis, discussing findings with the team and determining final design and content decisions to proceed with for implementation, we'll need to update our figma files to reflect those decisions.

## Tasks
- [x] Review/discuss action items
- [x] Update figma files with final design and content decisions
- [x] Review/share with devs (async or via screenshare per your preference)

## Acceptance Criteria
- [x] Figma files are updated and shared with devs

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Review figma files and confirm designs and content reflect final decisions

**Comment by mattmarino-adhoc** [comment]
Sharing did occur on July 30th, but additional content work needs to happen still. The hope is this is finalized by end of day July 31st, TBD.
