### ISSUE TITLE
[CST] [ENG] Add prop wrapping to breadcrumbs

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#88663]
## Value Statement
**_As a_** user  of the CST
**_I want to_** be able to view the breadcrumb text 
**_So that_** I can see where a given breadcrumb link is taking me

---
## Background Context
Many of the breadcrumbs in the CST are long and thus the text is getting cut off, making it so that users cannot see what the breadcrumb text says. 

EX: <img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFRyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3d45f5c7f0d408b5cc27fefe55157c2997718a7/Screenshot%202024-07-16%20at%209.45.48%E2%80%AFAM.png" alt="Screenshot 2024-07-16 at 9.45.48 AM.png" />

There is a `wrapping` prop that we can use on breadcrumbs to allow the breadcrumbs to be wrapped. We should update all breadcrumbs in CST to use this 

EX of wrapping prop: <img width="1332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGpyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7526623bb01472090f47e9ffe4be90474544ce0a/Screenshot%202024-07-17%20at%201.07.25%E2%80%AFPM.png" alt="Screenshot 2024-07-17 at 1.07.25 PM.png" />

## Outcome, Success Measure, KPI(S), and Tracking Link
- Users can view the breadcrumb text

## Design
- @skylerschain 

## Engineering 
- Update `ClaimsBreadcrumbs.jsx` to have the prop `wrapping`

## Tasks
- [ ] Add prop wrapping
- [ ] Verify in staging that long breadcrumb chains wrap according to our AC
- [ ] If they do, GREAT, if they don't, well, we don't do this
- [ ] Add unit test

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] Users are able to view breadcrumb text in CST
- [ ] Breadcrumb links wrap to their own line and will not appear on multiple line.

**Comment by pmclaren19** [comment]
Reviewed during eng refinement.
