### ISSUE TITLE
Spike | Understand pdf upload failures

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#88685]
## Issue Description
_From 7/1-10, Datadog shows failures in primary path submissions but no logs for the sidekiq jobs. The `FormSubmission` table also does not have the submissions recorded. See [slack thread](https://dsva.slack.com/archives/C0547Q0K0LF/p1721233576034359)._

Initial research uncovered some oddness in the way we handle PDF upload failures. We send the PDF to backup path AND we tell the Veteran there was a failure. Work in #88652 will create an alert that will sound when the back up path fails to start.

Note: #75418 also relates to pdf failures

The following claims were affected and were manually resubmitted on 7/17:
9311730
9311689
9309742
9302665
9301502
9293294

---
## Tasks
- [ ] Determine why the sidekiq jobs are not firing for the failures
- [ ] Document the various failure scenarios and meet with stakeholders to determine how VA.gov should handle them (e.g., send failure email)

## Acceptance Criteria
- [ ] Root cause of sidekiq job failure documented
- [ ] Follow-on tickets to remediate problem created
- [ ] Documentation outlining the failure scenarios and course of action for each
- [ ] Follow-on tickets to implement any new courses of action
---
