### ISSUE TITLE
Change 'featured content' to 'summary box'

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88706]
## User Story
As a Governance team member supporting Collab Cycle SRs, I want the names of the VADS components to be accurately displayed in the SR issue tickets so that there is no confusion for VFS teams.

Assignee: @briandeconinck 
Peer Reviewer: @erinrwhite 

## Description
Per [this thread,](https://dsva.slack.com/archives/G01DXP10GCA/p1721247601242359) the 'featured content' VADS component has been renamed '[summary box](https://design.va.gov/components/summary-box).' Governance team needs to update the name of the component in our DraftingTemplate's and the source of truth documents so that the name is accurately displayed in SR issue tickets. 

## Impacted Artifacts
- [Source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit?gid=500057009#gid=500057009)
- [DraftingTemplate 2.0](https://docs.google.com/spreadsheets/d/1PfgoHa1jctln9NTI6ZhEwcQitDqWiRt0OnkQuGZFV8Y/edit?gid=605465842#gid=605465842)
- [DraftingTemplate 2.0 - DST](https://docs.google.com/spreadsheets/d/1rkORbwvrsKP4fBxxamuP_6plYOGRKXCaqBw3Qd55pTU/edit?gid=605465842#gid=605465842)
- Upcoming staging review drafting templates
   - [Pre-check-in medication review](https://docs.google.com/spreadsheets/d/1idpTpHvoCeEKcxVM9VQupgd9lkPKcU3iD4hFJYlBSLQ/edit?gid=605465842#gid=605465842)
   - [Resources for schools SCO](https://docs.google.com/spreadsheets/d/19oG-EI66wFUvskvpZ7r2ojehlOf1ydcIG8Z1DZ_8Ic8/edit?gid=605465842#gid=605465842)
   - [FMP registration](https://docs.google.com/spreadsheets/d/1djyvPR9XrJcHXFFBNVQccMLk8DDPgmLZm4T1IM6LAxU/edit?gid=605465842#gid=605465842)

## Tasks
- [x] Follow the guidance on the [VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards) page for how to update descriptive tags

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The descriptive tags for Featured Content no longer exists and has been replaces with Summary box

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@erinrwhite Ready for review! Files edited are linked in the Impacted Artifacts section.

**Comment by erinrwhite** [comment]
@briandeconinck looking good! 👍🏻 Boxes checked. All set to close.
