### ISSUE TITLE
Hybrid Microservices Architecture - create Design document

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88704]
## User Story
As the developers and managers of the Platform Product team,
We need to create a design document for the Hybrid Microservices Architecture objective 
So that the strategy for implementation of this objective is understood for those working to complete it.

## Issue Description
The Platform Product team will create a design document for the Hybrid Microservices Architecture objective so that the goals and outputs are clearly outlined, and there is a strategy in place for implementation. 

## Tasks
- [ ] Discovery on the Hybrid Microservices Architecture objective
- [ ] Outline the strategy necessary to achieve the objective
- [ ] Create documentation that represents the objective and strategy

## Success Metrics
That there is a design document which clearly outlines the work and steps needed to complete this objective.

## Acceptance Criteria
- [ ] Design document
- [ ] Approved strategy
- [ ] Estimate of the level of effort required for this objective
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by LindseySaari** [comment]
[Created the start of the document here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3342860293/MVP+Hybrid+Microservices+Design+Doc)

**Comment by jennb33** [comment]
8/5 update: @Kshitiz-devops will review the draft document from a DevOps perspective.
