### ISSUE TITLE
[UX] Synthesize and share lessons from NNg courses

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#88707]
### I took two Nielsen Norman Group classes (July 15 & 16) that are directly relevant to the type of work our team does - Successful Stakeholder Relationships and Practical AI for UX Practitioners. As a result I'd like to synthesize the most important and applicable learnings in a takeaway format as well as in a presentable format so the rest of the team can benefit from the courses.

---
## Tasks
- [x] Clean up notes from both classes
- [x] Create a deck of important takeaways and resources
- [x] Present lessons to the team
- [x] Share documents/resources in a takeaway format for the team

## Acceptance Criteria
- [x] Lessons learned are captured in a deck and have been shared with the 1010 team
---
