### ISSUE TITLE
Improve Medallia Intercept Survey data collection

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#88712]
## Issue Description

This ticket is scoped to dial in the Medallia Intercept survey so the quantitative and qualitative data collected helps DBEX to establish a baseline for measuring improvement. 

### Context 
The 526ez features [two Medallia surveys](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/accessing-and-utilizing-contact-center-data#AccessingandUtilizingContactCenterData-WhattoDoWiththeData) that collect Veteran feedback during the filing experience: Feedback and Intercept. The Medallia Intercept survey is enabled across all of modernized VA.gov. It randomly “intercepts” 5% of VA.gov users who have had a 20-second or more extended session. 

### Current state
DBEX UX Teams 1 and 2 have reviewed Medallia data in the last year, but focused on Feedback responses. Other product teams have described the Intercept survey appearing too early in the form; other teams (such as Debt) have explore moving the Intercept to the end of the form to avoid pop-ups and fragmenting the filing experience. 

---
## Tasks
- [ ] Review current month of Medallia data 
- [ ] Look at other solutions (such as Debt) for addressing problems
- [ ] Develop options for improving the survey 
- [ ] Collaborate w/ OCTO and Contact Center to discuss and implement changes

## Acceptance Criteria
- [ ] Changes to Intercept survey are proposed to OCTO and Contact Center
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by pacerwow** [comment]
@evelynhilbrichdavis I'd like to be Consulted on this task "Develop options for improving the survey" please.
CC @lisacapaccioli in case you're also interested.

**Comment by pacerwow** [comment]
Open question - Is it possible to target the Veterans who see the new Toxic Exposure questions?

**Comment by evelynhilbrichdavis** [comment]
Confirming problems with our intercept survey distribution with a recent data pull.  Of the 85 Intercept responses received for Medallia Intercept (July-Aug 9 2024), 65% of them were from the very beginning of the form. 
- 48 responses came from Start and Introduction pages (before form is begun) 
- 7 responses from the first page, Veteran-information
