### ISSUE TITLE
Medallia - Remove A11y intercept survey on pre-checkin/checkin pages

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#88729]
## Issue Description
This is a [request](https://dsva.slack.com/archives/CNCEXNXK4/p1721228485921879?thread_ts=1721221404.946229&cid=CNCEXNXK4) to exclude the Medallia a11y intercept survey from the following paths:

/health-care/appointment-check-in/verify
/health-care/appointment-check-in/loading-appointments
/health-care/appointment-check-in/appointments
/health-care/appointment-check-in/arrived
/health-care/appointment-check-in/contact-information
/health-care/appointment-check-in/emergency-contact
/health-care/appointment-check-in/next-of-kin
/health-care/appointment-check-in/travel-pay
/health-care/appointment-check-in/travel-mileage
/health-care/appointment-check-in/travel-vehicle
/health-care/appointment-check-in/travel-address
/health-care/appointment-check-in/travel-review
/health-care/appointment-check-in/travel-agreement
/health-care/appointment-check-in/details
/health-care/appointment-check-in/error

This URL will have an appended (not query string) UUID
/health-care/appointment-check-in/appointment-details

/health-care/appointment-pre-check-in/verify
/health-care/appointment-pre-check-in/appointments
/health-care/appointment-pre-check-in/introduction
/health-care/appointment-pre-check-in/contact-information
/health-care/appointment-pre-check-in/emergency-contact
/health-care/appointment-pre-check-in/next-of-kin
/health-care/appointment-pre-check-in/error

This URL will have an appended (not query string) UUID
/health-care/appointment-pre-check-in/appointment-details

/my-health/appointment-travel-claim/verify
/my-health/appointment-travel-claim/travel-pay
/my-health/appointment-travel-claim/travel-mileage
/my-health/appointment-travel-claim/travel-vehicle
/my-health/appointment-travel-claim/travel-address
/my-health/appointment-travel-claim/travel-review
/my-health/appointment-travel-claim/travel-agreement

/my-health/appointments/schedule-referral/
/my-health/appointments/schedule-referral/date-time

Full list [found here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/Medalia/urls-to-exclude-from-intercept-survey.md):

---
## Tasks
- [x] Coordinate with VSignals EMACs team 
- [ ] QA removal on URLs

## Acceptance Criteria
- [ ] A11y intercept survey only appears on precheckin/checkin URLs listed above
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Vsignals team has to prioritize

**Comment by loripusey** [comment]
Is it too late to add 2 additional URLs to the list to exclude @aubreyarcangel ?

**Comment by clantosswett** [comment]
@aubreyarcangel did VSignals complete this work? If yes can you come in here and update the ticket and close this? For now moving to the backlog in case it hasn't happened and is dependent on VSignals.

**Comment by ATMiddleton** [comment]
A11 is off on the Myhealth URLs
But still on Healthcare appointment and pre check in 

We can follow up on the monthly Vsignals meeting 1/22/25

**Comment by ATMiddleton** [comment]
Sent follow email to Brian, 

Hey Brian, 

I hope you are well. 

I'm following up on my previous request to disable the A11y intercept survey on the URLs I provided. Could you please provide an update on the status of this request?

Thank you,

Best regards, 

Anita 
Product Manager 
305-522-2306

**Comment by ATMiddleton** [comment]
The exclusions have been completed in staging.  Awaiting completion in production.
