### ISSUE TITLE
[CDP] VBA Debt Detail — On this page link updates

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#88742]
### Summary
We need to add two anchor links on the Payment History detail page that drop down to specific content sections on the same page.

**Current:** 
<img width="254" alt="Screenshot 2024-08-01 at 2 25 55 PM" src="https://github.com/user-attachments/assets/5e6da072-2492-44a6-af9f-23c2e978c160">

**Solution**
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=1963-16864&t=xh6qJIrZlx3L48Gb-11
<img width="300" alt="Figma screenshot" src="https://github.com/user-attachments/assets/da8b9015-98b4-4cd7-a3b1-36112d632924">

 Scenario: Display "How to request financial help" link in the "On this page" section
- **Given** the "Payment History" page is displayed
- **When** the user clicks on the "How to request financial help" link in the "On this page" section
- **Then** the page should scroll to the "How to request financial help" section and the instructions for requesting financial help should be clearly presented

### Tasks
- [x] Remove Need help link
- [x] Hide debt details link until payment history table goes live
- [x] Add how request help link
- [x] Add dispute this debt link

### Acceptance Criteria
- [x] The need help link has been removed
- [x] The debt details link has been hidden
- [x] The How to request help and dispute debt anchor links have been added
- [ ] PR has been reviewed by design (add @josephrlee to the PR review please)

**Comment by josephrlee** [comment]
@OptionSelect, I can help with the review on this ticket!
