### ISSUE TITLE
[DevOps] Create API Gateway account settings necessary to support logging.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#88743]
## Description
This will require changes to `global` and `global_iam`, as this is per-account settings.

## Tasks
- [x] [DevOps] Create an `aws_iam_role` that API Gateway can assume.
- [x] [DevOps] Attach the `arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs` policy to the above role.
- [x] [DevOps] Create an `aws_api_gateway_account` block setting the cloudwatch role ARN to the above role.
- [x] [DevOps] Make changes in `global_iam` as necessary to support account updates, role creation and modification, etc.

## Acceptance Criteria
- [x] Configuration plans and applies cleanly.
- [x] All API Gateway implementations can log to CloudWatch Logs as expected.
