### ISSUE TITLE
Burial | VSOs Research

### ISSUE THREAD

**Issue by fiorella-io** [department-of-veterans-affairs/va.gov-team#88745]
## Issue Description
Our team launched a new version of the form in May 2024, so it’s now in parity with the paper form. We want to uncover any problems and opportunities for enhancement that the current claimants face when filling out the new Burial Benefits form.

Method: Moderated session
Research lead: Fiorella Geedi
Focused users: VSOs
Research Timeline: 9/1 - 10/18

## Key links
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/research/2024-09-VSO-Research/research-plan.md) | [Word](https://docs.google.com/document/d/1oormpo3GqDZ8P87M9NboqHDuZKWPe1TcFYxtR_M6tSs/edit)
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/research/2024-09-VSO-Research/conversation-guide.md)
- [Notetaking space](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725033549559/772d53bbe384123c0c85266a229597a8a38194e4?wid=0-1725385164368)
- [Findings report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/research/2024-09-VSO-Research/Burial_VSO_Research%20Findings-Knowledge_Transfer.pdf)

---
## Tasks
- [x] Recruitment + planning 
     - [x] Consult with trauma-inform experts 
     - [x] Create recruitment ticket: [Github](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=sstrassberg&labels=recruitment-criteria&template=recruitment+criteria.yaml&title=%5BRecruitment+Request%5D%3A+YYYY-MM+name+of+your+study) | [Recruitment checker for equality](https://docs.google.com/spreadsheets/d/1CCTyhF85QewEzp1CRQgM1_Nd7EN9D2RTqga3OA8vmDI/edit?gid=0#gid=0)
     - [x] Create screener questions
     - [x] Create [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/research/2024-09-VSO-Research/research-plan.md)
     - [x] Create [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/burial-allowance/research/2024-09-VSO-Research/conversation-guide.md)
     - [x] Create [booking link](https://outlook.office.com/bookwithme/user/df6210595a96492eb07b2df2aa46e9a8@va.gov/meetingtype/3s4UeIGiG0OUzyLtiZPhdQ2?anonymous&ep=mcard)
     - [x]  Create [notetaking space on Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725033549559/772d53bbe384123c0c85266a229597a8a38194e4?wid=0-1725385164368)
- [x] Research
     - [x] Create a [sign-up sheet](https://dvagov.sharepoint.com/:x:/s/vaabdvro/ESDi05wluvZCosoEIg45VAcBmTldEGfhac0O8m457lyYDA?e=YiBPaH) for notetakers and observers
     - [x] Send meeting invites
     - [x] Schedule debrief sessions 
     - [x] Facilitate interviews
- [x] Synthesis
     - [x] Create a shareout of findings 
     - [x] Decide which recommendations to create as tickets on GitHub

**Comment by fiorella-io** [comment]
I sent an email to Daniel on 8/1, and a week and a half later, on 8/9, I sent a message to all of our SMEs on Teams asking if they could connect us to VSRs. Daniel Gifford mentioned that Tim, the chief of POI for P&F, no longer has access to VSRs helping POI. 
I am still waiting for someone else to reply. So, I'm blocked until someone replies. I'll connect with Dene to see if we should reach out to someone else or start VSO research instead.

**Comment by fiorella-io** [comment]
Updates: On 8/22, Dene mentioned holding off VSR research until October or so. They are currently busy until the end of this fiscal year. She suggested switching gears and starting VSO research, specifically with the folks that Allexe spoke to that also help claimants with Burial benefits

**Comment by fiorella-io** [comment]
Updates: 
- Emails were sent yesterday, 9/11, to 5 VSOs who participated in the Pension VSO research study. 
- Scheduled two dry runs 
- We have 2 VSOs out of the five that have scheduled a session 🎉
- I created a [sign-up sheet](https://dvagov.sharepoint.com/:x:/s/vaabdvro/ESDi05wluvZCosoEIg45VAcBmTldEGfhac0O8m457lyYDA?e=YiBPaH)
- I created a session notes space [in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725033549559/772d53bbe384123c0c85266a229597a8a38194e4?sender=uafd725f4e06b54f700de9374)

**Comment by kristinoletmuskat** [comment]
Closing because this is done! I think it just got reopened accidentally when it moved github boards.
