### ISSUE TITLE
[CAIA Intake] Veteran Facing Forms - Form 21-8940 VETERAN'S APPLICATION FOR INCREASED COMPENSATION BASED ON UNEMPLOYABILITY

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#88748]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: Veteran Facing Forms
- **OCTO product owner:** Matthew Dingee
- **Product name:** Form 21-8940 VETERAN'S APPLICATION FOR INCREASED COMPENSATION BASED ON UNEMPLOYABILITY
- **Product manager:**  Tricia Baker
- **Slack channel:** veteran-facing-forms
- **Dedicated content writer on your team (if you have one):** `Insert name and/or GH handle`
- **Dedicated a11y specialist on your team (if you have one):** Jeana Clark
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [x] Digitizing a new form
- [ ] Creating a new digital tool
- [ ] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Digitizing this form and would like content review on Statement of Truth & entry points & URL's
[Possible Entry Point](https://www.va.gov/disability/eligibility/special-claims/unemployability/)
## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [x] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

- Working on the source of truth
- Figma files are WIP (so have not shared them here yet)
- No deadlines

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [x]  Yes
- [ ]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `Enter dates`
- **What is the name of your engineer who will build the React widget?** `Name`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `[88572](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88752)

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
-[Product Outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-8940%20Increased%20Compensation/Product%20Outline.md)
[Source of Truth
](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-8940%20Increased%20Compensation/source-of-truth.md)
## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89269
```

**Comment by kristinoletmuskat** [comment]
Hey @tbaker1026 and @JaciWilkinson -- I did some prelim thinking on the IA for this form in this mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701808829216/178998265b5996341a48a0b7c499292188b223fb?wid=14-1721841061234

IAs are going to chat today about placement of this form -- you will see 3 options we're considering. One thing I'm unclear on is the user journey for a user who has already completed the 526 when they search for this form, vs someone who hasn't done it yet. I'm assuming ya'll have more context than me -- would it be possible to build out that section of the user flow in this mural? Or, if you already have a mural you're working from, I can copy/paste this info into that! Whatever works for ya'll. Thanks for opening the ticket so early!

**Comment by tbaker1026** [comment]
@kristinoletmuskat  Here is our [Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697742707868/222c3dd5f2f953d164220dee5db362ef4ff94d57?sender=u2dd1818fc590a5b2e62f8183)- however we have not thought about the User journey if they completed the 526. [ Here](https://www.va.gov/disability/eligibility/special-claims/unemployability/) is where the form currently resides

**Comment by kristinoletmuskat** [comment]
Thank you! I also reached out to the 526 team because I could have sworn that Individual Unemployability was part of 526. It sounds like they have the code and design ready for that integration but it isn't deployed. Just an FYI! Here's the [slack thread](https://dsva.slack.com/archives/C053UDWMH7U/p1721843720062039).

**Comment by kristinoletmuskat** [comment]
Another note: we think we're going to go with a modified version of the Option 1 placement. Mikki and Danielle are going to chat about other changes we might make to Drupal pages in the disability hub, so that we can place this form in line with the vision for the disability hub, so that we don't have to change the URL later.

**Comment by tbaker1026** [comment]
@kristinoletmuskat Some more information.  A Veteran could have filled out a claim and received a disability rating but was still employed.  Later their service-connected disability made it so they could not remain employed.   They would use this form to increase their compensation due to unemployability.

**Comment by megzehn** [comment]
Hi @tbaker1026! Are there Figma files for this one?

**Comment by tbaker1026** [comment]
@megzehn They are not complete yet.  Did you want to review figma rather than source of truth

**Comment by megzehn** [comment]
Ah ok, thanks @tbaker1026, No worries, I'll start with the github SOT! Just wanted to make sure I wasn't missing the Figma mocks.

**Comment by kristinoletmuskat** [comment]
Note from Jenny: the forms builder team is going to take this on, so we don't need to do any content team as yet, but it shouldn't change any of the IA proposals already made.

**Comment by tbaker1026** [comment]
@kristinoletmuskat @megzehn @Karak888 - This ticket can be paused or put in backlog for now.  The VFF team is handing this form over to the TMF Form builder team and will be addressed at a later time

**Comment by kristinoletmuskat** [comment]
Moved to backlog, but noting for future: we're going to put this in the disability hub in the new 'special claims' sections we'll be making. I'll link that ticket once I create it. 

![Screenshot 2024-07-29 at 12 37 08 PM](https://github.com/user-attachments/assets/8e0ef2d1-78cb-419d-b65f-da82b8069f26)

**Comment by Karak888** [comment]
Thank you @kristinoletmuskat I appreciate your including this information.

**Comment by tbaker1026** [comment]
Closing ticket since another team is taking over this form
