### ISSUE TITLE
Require Governance to add screenshots when documenting SR findings

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#88759]
## User Story
As a VFS team member participating in Staging Review, I'd like to see a screenshot of the finding documented by Governance team so that I have a clear understanding of what needs to be fixed.

Assignee: @erinrwhite 
Peer Reviewer: @briandeconinck 

## Description
It has been common for VFS team members to request screenshots when Governance walks through the findings at the SR meeting. Adding screenshots should be default for Governance team so we're not having to follow up post-SR.

## Impacted Artifacts

- [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)
- [How to Add Images or Videos to Staging Review findings tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2396619099/How+to+Add+Images+or+Videos+to+Staging+Review+findings+tickets)
- [How to generate staging review tickets - step 6: notify the team](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#Step-6%3A-Notify-the-team)

## Tasks
- [x] Determine which guidance docs should be updated to address this change
- [x] Add the requirement to the guidance.
   - [x] If you believe there should be criteria for when to add an image (or video) and when an image is not necessary, please define if and share with the full Governance team for their review and input

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have added a requirement for Governance team members to add a screenshot to SR findings tickets if/when it would be valuable to the VFS
- [x] The Collaboration Cycle operational guidance has been updated to include requiring a screenshot 

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This work was deprioritized due to the Zero Silent failures mandate taking priority. This ticket will be put back on the backlog and picked up later on.

**Comment by erinrwhite** [comment]
[Started work on this in the live documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)

**Comment by erinrwhite** [comment]
Updated our documentation - ready for review @briandeconinck !

- [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review) - added information to `3. Add your findings` step:
  > [Add an image or video for each finding](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2396619099), unless the finding won’t, or can’t, be clarified with an image or video. If in doubt, add a visual. This can sometimes feel redundant, but capturing the interface at this moment in time greatly clarifies findings for VFS teams at Staging Review and is often helpful for future conversations.

- [How to Add Images or Videos to Staging Review findings tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2396619099/How+to+Add+Images+or+Videos+to+Staging+Review+findings+tickets) - added note at top of page
  > Governance Team members are asked to add images or videos to their Staging Review findings unless the finding won’t, or can’t, be clarified with an image or video. If in doubt, add a visual!

- [How to generate staging review tickets - step 6: notify the team](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets#Step-6%3A-Notify-the-team) - updated Slack message sent to team to include
  > If you still need to upload images or video for your findings, please do so now.

**Comment by briandeconinck** [comment]
@erinrwhite This all looks great! I think you're good to close it out.

**Comment by erinrwhite** [comment]
thanks @briandeconinck! Closing and announcing to the team

**Comment by erinrwhite** [comment]
announced! closing..
