### ISSUE TITLE
Redis POAM: Analysis of Rails application, current state (Milestone 3)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#88755]
## User Story
As the Managers of the Rails tool,
We need to understand the current state of Rails, to include "at rest" and "in transit" settings
So that any Rails work can be scheduled and will begin with the Redis POAM work. 

## Issue Description
Redis product-team level security risk was registered on 5/31/2024, due to not meeting encryption and password protection in the current Redis environment. The team needs to create a timeline and mitigation strategy, that includes current state of “at rest” and “in transit” settings, in order to understand the work that needs to be done to fix the security risks. 

Note: this ticket can be completed in parallel with [87224](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/87224)

## Tasks
- [x] Establish current state of “at rest” setting
- [x] Establish current state of “in transit” setting
- [x] Determine **_encryption_** requirements and current state, determine delta/gap
- [x] Determine _**password protection**_ requirements and current state, determine delta/gap
- [x] Determine timeframe for implementing these mitigation tasks

## Success Metrics
There is solid understanding of the work required so that proper estimates can be applied to the timeframe. 

## Acceptance Criteria
- [ ] That there is documentation outlining current state of “at rest” and "in transit" settings; encryption and password protection requirements and deltas are understood, and a plan to implement these changes is well outlined and approved. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rjohnson2011** [comment]
Here is the current draft of the Redis Analysis -> https://vfs.atlassian.net/wiki/spaces/PPT/pages/3450830855/Analysis+of+Rails+Application+-+Current+State

**Comment by LindseySaari** [comment]
@rjohnson2011,  you'll want to identify any all all configs in the manifest for all envs that will need an updated redis protocol and uri. e.g. [for example here in dev](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/dev/values.yaml#L728-L739 )

**Comment by jennb33** [comment]
9/18/2024: there are still some things that require exploration and documentation. @rjohnson2011 will need to address those and the comments in the document before this can be closed.

**Comment by rjohnson2011** [comment]
Made modifications from @LindseySaari 's suggestions and closing this.
https://vfs.atlassian.net/wiki/spaces/PPT/pages/3450830855/Analysis+of+Rails+Application+-+Current+State
