### ISSUE TITLE
[Frontend] Implement UI changes on address selection screen for when only a permanent address is displayed

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#8878]
## User Story or Problem Statement
When a Veteran only has a permanent address being passed through the API, there is only one radio button to select. This goes against convention, so we need a design to account for that. How might we update the card's design to align with UI best practice?

## Goal
_Implement UI changes the frontend engineers and designers collaborated on for the use case of one address being passed through the API_

## Objectives or Key Results this is meant to further
- _MDT development_
---
## Tasks
- [ ] _Update the address screen's UI based off the new design_
Please reference [the InVision mockup](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/416620566_C1_P2-_Only_Perm_Address_-_Radio_Will_Just_Be_A_Button) as needed
- [ ] _Once UI is updated, confirm changes with the design team_

## Acceptance Criteria
- [ ] _UI updates have been incorporated_
- [ ] _UI updates have been shared with design team and approved_
---
