### ISSUE TITLE
IA Guidance: Header and Footer

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#88782]
## Overview
Define what is added to header and footer.

[WIP Documentation](https://docs.google.com/document/d/1LuLX1dXL01FaCBXDqDmogDgsk50OkmyvPrLk-dl_RMM/edit)

## Tasks

- [x] Review/analyze existing documentation and implementation - IA
- [x] Establish scope of effort and where guidance lives - IA
- [x] Draft revised standard ([header](https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/IA/Standards/Header.docx?d=wf31ee57166f04d7584ac7225a4fd41c0&csf=1&web=1&e=MNGek1), [footer](https://dvagov-my.sharepoint.com/:w:/r/personal/michelle_northuis_va_gov/Documents/IA/Standards/Header.docx?d=wf31ee57166f04d7584ac7225a4fd41c0&csf=1&web=1&e=MNGek1), and [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?wid=0-1727901579916)) - Kristin
- [ ] Mikki first pass review
- [ ] Final review and approval by Mikki - Erin/Mikki
- [ ] Publish - Erin/IA
- [ ] Communicate out to teams - IA/Mikki

## Acceptance Criteria
- [ ] Clear guidance for placement and inclusion of content or links on the home page is clearly defined and approved by IA lead, Sitewide design lead, and home page PO
- [ ] New template on VADS is communicated out to teams

**Comment by jennymayoco** [comment]
Hi @mnorthuis I've written a [draft](https://docs.google.com/document/d/1LuLX1dXL01FaCBXDqDmogDgsk50OkmyvPrLk-dl_RMM/edit#heading=h.h647mg64927v) for header and footer with updates in pink that is ready for your review. Michelle's original documentation is right below `suggested placement`

**Comment by kristinoletmuskat** [comment]
Hey @mnorthuis , I have a draft of header/footer standards for you to review in [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?wid=0-1728526706921). 

In addition to the descriptions there, we have a WIP draft of the [Header](https://docs.google.com/document/d/1LuLX1dXL01FaCBXDqDmogDgsk50OkmyvPrLk-dl_RMM/edit?tab=t.0) and [Footer](https://docs.google.com/document/d/1GhP31slErtrgOHV3SXdOuwmTcASZCrXVTCHqVNiYe3g/edit?tab=t.0#heading=h.6hkyhsrda246) in google docs. 

FYI @erinrwhite

**Comment by mistymg** [comment]
Moving to Tasks - Ready as this has been assigned.

**Comment by mnorthuis** [comment]
Recent work related to OSDBU request
[header-footer-data.xlsx](https://github.com/user-attachments/files/20715529/header-footer-data.xlsx)

**Comment by jonichan-ia** [comment]
@mnorthuis[ Draft of footer guidance](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Standards%20and%20governance/IA%20Standards/[Footer-IA-standards.docx](https://dvagov.sharepoint.com/:w:/r/sites/oitcontentiateam/Shared%20Documents/Standards%20and%20governance/IA%20Standards/Footer-IA-standards.docx?d=wa0701926c91c4f1b9989f0a7d057081a&csf=1&web=1&e=WemQbf)?d=wa0701926c91c4f1b9989f0a7d057081a&csf=1&web=1&e=WemQbf) is ready for your review:

**Comment by jonichan-ia** [comment]
I have a draft pull request and tagged you for review, @mnorthuis
