### ISSUE TITLE
[FSR] Update expense endpoint for housing expense change

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#88798]
## Description
Update expense calculations to account for housing expenses updates. 

- [FE implementation ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/68302)
- PRs for new expense feature flag (`financial_status_report_expenses_update`)
  - [Frontend](https://github.com/department-of-veterans-affairs/vets-website/pull/29563)
  - [Backend](https://github.com/department-of-veterans-affairs/vets-api/pull/16623)
- FE Code changes
  - Initial code change: [**[FSR] 68302 - Updating rent/mortgage expenses #29829**](https://github.com/department-of-veterans-affairs/vets-website/pull/29829)
  - FE tests for changes: [**[FSR] 83576 Adding tests for new expense page functionality #30275**](https://github.com/department-of-veterans-affairs/vets-website/pull/30275)

[Meat and potatoes of calculation changes](https://github.com/department-of-veterans-affairs/vets-website/pull/29829/files#diff-9e6f0e5c660a80c32068092ca809775cb40d92ba75797286eb93076bf1b78f54R73-R75) with feature flag that can be implemented in the BE controller.

In short we're moving rent and mortgage values out of `expenseRecords` and into it's own property in formdata `expenses` as `monthlyHousingExpenses`.

## Tasks
- [ ] Update controller
- [ ] Write new tests
- [ ] ???
- [ ] Success

## Acceptance criteria

- [ ] BE is using `financial_status_report_expenses_update` to use `monthlyHousingExpenses` in expense calculations
- [ ] New tests exist and are passing 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
