### ISSUE TITLE
[UX] 10-10EZ - Insurance: Designs for Multiple responses pattern on general insurance questions

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#88804]
## Issue Description
As a Veteran, I want the application to contain easy to use patterns when adding multiple insurance policies. 

The insurance sections uses an old deprecated wizard list-and-loop pattern. This ticket is to update the designs on the general insurance page to use the updated pattern.

- [Design system pattern guidance
](https://design.va.gov/patterns/ask-users-for/multiple-responses)

---
## Tasks
- [x] Update designs in Figma for the general insurance multiple responses pattern used
- [x] Review with UX team at weekly sync
- [x] Make adjustments + additional pattern investigation 
- [x] Review with EZ/CG team + PM for sign off

## Acceptance Criteria
- The designs using the latest design system guidance for the pattern are ready for engineering.

**Comment by jessicastump** [comment]
[Figma link here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5139-31117&t=woLnK8KPCTNMdZlV-0) - planning to review at UX sync Monday 8/5/24

**Comment by jessicastump** [comment]
[Mural with user flow updates](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722616362876/97c219cd385f5b1402a429617a802f8375a63bb6?sender=uadf1ed7fe7c76f0914967329)

**Comment by jessicastump** [comment]
Summary after UX team sync on 8/5:
- Team and Lois want to see the insurance pattern explored as a single-page instead of multiple page add (JS to update a design option)
- Hieu mentioned that the out-of-the box list-and-loop does allow conditional logic and pointed to a 3-month old Slack post (JS to confirm)
- Need to document the exact differences between the custom version of the pattern and the forms library version. (delete vs remove button for example)

**Comment by jessicastump** [comment]
Adding discovery on differences between the custom version currently implemented on the 10-10EZ forms and the forms library array builder pattern version. - [Mural here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699485613760/d40578dbce4f0433d792988db24e4dec8d5b4fd1?wid=0-1723041889608)
- [Slack thread](https://dsva.slack.com/archives/C05QKRZGHFS/p1723046102004769)

**Comment by jessicastump** [comment]
Updates have been made to the design file to include a [single page option](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5317-57655&t=1yqvGLShLkcV2RKV-4) and to account for the [authenticated save-in-progress screens](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5378-75689&t=1yqvGLShLkcV2RKV-4).

**Comment by jessicastump** [comment]
[[PATTERN] Multiple Responses  List and Loop_2024-08-07_21-31-17.pdf](https://github.com/user-attachments/files/16534549/PATTERN.Multiple.Responses.List.and.Loop_2024-08-07_21-31-17.pdf)

**Comment by hdjustice** [comment]
@jessicastump We can review async and if there are any questions that could benefit from a quick chat, we can wait til you get back

**Comment by jessicastump** [comment]
After meeting at the UX weekly sync we all decided the one-page version is the route to go with, [marked in design file here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5139-31117&t=OPU0WiRwHdRsMtZb-0) - closing the design ticket
