### ISSUE TITLE
[FE] 10-10EZ - Insurance: Add Info page to the beginning of Insurance section

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#88810]
## Issue Description
As a Veteran, I want the application to display an accessible list of items, when adding multiple insurance policies, so that I can quickly and easily determine if I have entered all the information I want to include.

The insurance sections uses an old deprecated wizard list-and-loop pattern. This ticket is to update the code on the general insurance page to use the updated pattern.

- [Design system pattern guidance
](https://design.va.gov/patterns/ask-users-for/multiple-responses)
- [Figma design file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5317-57655&t=dcuzV9Py8dY2R0ol-0)

---
## Tasks
- [x] Create feature toggle for the Insurance section updates
- [x] Reference [Figma design file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5317-57655&t=dcuzV9Py8dY2R0ol-0) ([ticket #88804](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88804))
- [x] Create Insurance Info page
- [x] Review with PM/Team
     - PM signoff required before moving to QA
- [x] Inform teammate of QA readiness
     - #91134 

## Acceptance Criteria
- The 10-10EZ Insurance section is using the latest design system guidance for the insurance multiple responses pattern.

**Comment by hdjustice** [comment]
Add Cypress test ticket

**Comment by hdjustice** [comment]
Add task for feature toggle

**Comment by longmd** [comment]
@hdjustice / @jessicastump , [here is the RI](http://0d40a03e63f956c386e55b709c4c668f.review.vetsgov-internal/health-care/apply-for-health-care-form-10-10ez/) for the content updates. Let me know when we're good to proceed with getting this merged in.

**Comment by hdjustice** [comment]
Looks perfect @longmd !

**Comment by longmd** [comment]
@allanto-ah , you're welcome to review using the RI link above.

**Comment by longmd** [comment]
Here are the screenshots from this work:

| Before | After |
| ------ | ----- |
| ![Screenshot 2024-09-03 at 13 01 58](https://github.com/user-attachments/assets/7d4947f5-6e3a-43f2-9349-02e54486a169) | ![Screenshot 2024-09-03 at 12 59 56](https://github.com/user-attachments/assets/62efbce8-698f-40c9-b919-a84a41ec859b) ![Screenshot 2024-09-03 at 13 00 48](https://github.com/user-attachments/assets/e0f8dd38-d730-4af3-8383-e5dd2d497d42) |

**Comment by allanto-ah** [comment]
Environment: RI

Verified that the insurance intro page has been added. Content is also verified to match the Figma. The changes with the multiple response pattern is being done in a different ticket, this one was only to add the intro page and move the question to the next page. No regression issues.

https://github.com/user-attachments/assets/d5ff131e-fdca-4e80-8cc2-44fd8c75c307

**Comment by longmd** [comment]
Merged into prod on 09/09.
