### ISSUE TITLE
Create new fwdproxy backend - MDT

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#8883]
## User Story or Problem Statement

VFS team needs to connect to Medical Device Reordering Tool / Denver Logistics Center. https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/MDT%20-%20Denver%20Logistics%20Center.md

The service only has test environment setup and we want to map this to our staging environment.

This is a new service and doesn't have a healthcheck as of 5/7/2020.

Test Endpoint: `https://vaww.dalctest.oamm.va.gov:9443`

ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8174

## Goal
Create new backend in staging fwdproxy.

## Tasks
- [ ] create/update esccb/esecc ticket to open up networking to the endpoint
- [ ] add config to fwdproxy staging
- [ ] update fwdproxy staging terraform to create new listener on new port

## Acceptance Criteria
- [ ] connection established from fwdproxy to new backend
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tskinn** [comment]
Firewall has been opened. They are using a self signed certificate so we are waiting for a response about what their plans are for that.

**Comment by tskinn** [comment]
The other environments for this backend don't exist yet so there is nothing left to do for now.
