### ISSUE TITLE
Create new fwdproxy backend - debts api

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#8884]
## User Story or Problem Statement
VFS devs need to connect to new debts backend. A doc has been created for it here https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/Debts.md

Backends: 
- dev: gateway.test.dmc.va.gov:8443
- staging: gateway.preprod.dmc.va.gov:8443
- prod: gateway.dmc.va.gov:8443

## Goal
Create new backend in staging fwdproxy.

## Tasks
- [ ] create/update esccb/esecc ticket to open up networking to the endpoint
- [ ] add config to fwdproxy staging
- [ ] update fwdproxy staging terraform to create new listener on new port

## Acceptance Criteria
- [ ] connection established from fwdproxy to new backend
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tskinn** [comment]
Firewalls were opened but staging -> preprod doesn't seem to have worked. Boris has reached out to them. https://dsva.slack.com/archives/CC3C62R0S/p1589569709040900?thread_ts=1589486879.034500&cid=CC3C62R0S
