### ISSUE TITLE
Expand test coverage on TE Lighthouse submit requests

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#88843]
## Issue Description
Recently we found a bug (see [comments](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/87717)) where the Obligation Term of Service dates were not getting populated in the 526 PDF due to a typo in in the field name of the submit request ([fixed in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/17586)). Although there was generally some existing test coverage for the submit request, the bug would've been caught much sooner had we explicitly checked for more field values in our test.

This ticket is more expand the [existing tests](https://github.com/department-of-veterans-affairs/vets-api/blob/f595b5818a2f57060f90370c50cb49b77a23b7f0/spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb#L175) to explicitly check for most (if not all) fields in the 526 submit request

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Add more checks in `form526_to_lighthouse_transform_spec.rb` to test as many fields on the submit request as feasible

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
