### ISSUE TITLE
[FE] - Review and merge PR last sprints tickets

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#88841]
## Description

Since we were code freezing and down a code reviewer last sprint, we didn't merge the UX validated work from last sprint.

These tickets:
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87416
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87422
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87756
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87810

The goal of this ticket is to code review the above work. PR to come after MVP for upcoming is merged

Combined PR: https://github.com/department-of-veterans-affairs/vets-website/pull/31078

## Tasks
- [ ] code review work
- [ ] merge work

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/88841?planning-poker) with Zenhub @wullaski

**Comment by brianseek** [comment]
closing this ticket, since @wullaski completed it and the PR was merged
