### ISSUE TITLE
Form 21-0958 Retirement -- Copy updates

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#8885]
## User Story or Problem Statement
As a user looking for form 21-0958, I need to understand the form is no longer in use but that I can still manage my legacy appeal or use the new decision review process. 

---
## Tasks
- [ ] _Copy to be updated on legacy appeals page and faqs page. 

## Acceptance Criteria
- 
- [x] Write copy (Laura)
- [x] Get internal approval (Laura/Jen)
- [x] Copy approved by SME (Laura/Paul Shute)
- [x] Copy updated in Drupal (Laura)
- [x] Drupal pages published (Randi)
- [x] Alert Mikki that updates to legacy appeal page are live (Laura)

---

**Comment by lwalsh617** [comment]
Paul Shute approved copy. I need to make updates in Drupal.

**Comment by lwalsh617** [comment]
@RLHecht - I updated the copy on the legacy appeals page: (
![image](https://user-images.githubusercontent.com/53535663/82350071-e1431400-99c8-11ea-80f6-7be79586f4bc.png)) and on the faqs page:
preview-prod.vfs.va.gov/preview?node=3004

**Comment by RLHecht** [comment]
@lwalsh617 These two pages were reviewed and published. Moving to validate.

**Comment by RLHecht** [comment]
@lwalsh617 @stephorkandatx These two pages' updates are validated on live site. Last step is to alert Mikki and then we can close ticket!

**Comment by lwalsh617** [comment]
@mnorthuis @stephorkandatx -- The legacy appeals page copy has been updated to reflect the retirement of the NOD form. We want to redirect to #1 in subway map. This ticket can now be closed. I couldn't find a redirect ticket--do we need to open one before closing this?

**Comment by stephorkandatx** [comment]
@lwalsh617 can you spin up a new ticket for the redirect in the subway map? we can close this one out
