### ISSUE TITLE
Copy of Appoint a Rep - Cross Accredited VSOR - User Test - Kick-off

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#88858]
## Issue Description
Interviews and user test of the 21-22 with cross accredited VSORs.

## Tasks
- [ ] Ideation workshop with ARF designer/research team
- [ ] Ideation workshop with ARM team
- [ ] Generate themes and questions for test plan

## Acceptance Criteria
- [ ] All tasks complete.

**Comment by jfinnerty13** [comment]
Research plan created and submitted for review with Lesley and Dene: https://docs.google.com/document/d/13OW308uagwS_E6obQyi87zbwVSQJtBsb_LZ4H4iQWtI/edit?usp=sharing

Conversation guide in progress, will complete next week and send to team for review: https://docs.google.com/document/d/16NcVzNOaMLbpiowpV3x4-c8NQ80M4pzHsbVis04vppo/edit?usp=sharing

**Comment by jfinnerty13** [comment]
Complete and sent to team for review
