### ISSUE TITLE
Re-record Analytics & Insights Orientation Video

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#88850]
### Description:
The Platform Analytics & Insights Orientation training video is over 9 months old, and has some outdated content. 

This ticket is designed to record that video, and make sure the deck is up to date.

- [Platform Analytics & Insights Orientation - (Updated 2024)](https://docs.google.com/presentation/d/1TKYK88pHqNAJ0HrGtXIjnDYPQT-ccBQcOTy64kd0cd4/edit#slide=id.g5f29ec5fc2_4_71)

---

### Tasks:
- Update supporting slides for Analytics Orientation slide deck
- Make edits to the deck
- Record an updated orientation video.
- Share recording link with Governance Team

### Acceptance Criteria:

- [x] Orientation slide deck has been updated.
- [x] New orientation video for Platform Analytics has been recorded
- [x] Recording has been shared with Governance Team.

**Comment by johnny-jesensky-adhoc** [comment]
The Analytics orientation video has been re-recorded and uploaded to Youtube [here](https://www.youtube.com/watch?v=j2yWCL3FRGg). The link has also been updated on Platform Website on [this page](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions) -- should be picked up in the deployment today, or tomorrow.

Moving this to _**Done**_.
