### ISSUE TITLE
[CST] [ENG] Update the text in the CST Page tab titles

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#88868]
## Background Context
Update the CST Page tab titles from `${tabName} For ${claimDate} ${claimType} Claim` and `${tabName} Of ${claimDate} ${claimType} Claim` to `${tabName} for ${claimDate} ${claimType} Claim` and `${tabName} of ${claimDate} ${claimType} Claim` 

## Tasks
- [ ] update page title text on overview, files and status tabs

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] The status tab page title is `Status of ${claimDate} ${claimType} Claim`
- [ ] The overview tab page is `Overview of ${claimDate} ${claimType} Claim`
- [ ] The files tab page is `Files for ${claimDate} ${claimType} Claim`

**Comment by pmclaren19** [comment]
Reviewed during eng refinement.

**Comment by pmclaren19** [comment]
@jacobworrell Closing this ticket, it was worked on in [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86080) ticket with [this](https://github.com/department-of-veterans-affairs/vets-website/pull/31802) pr!
