### ISSUE TITLE
Create a dropdown component with an option to trigger an action

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#88860]
## Task Description

Create a new dropdown component that has a button to trigger an action. This will replace our current dropdown components that change the page without any additional user interaction:

- Past appointments date ranges filter
- "Sort by" filter on locations pages in scheduling flow
- "Sort by" filter on provider search in CC request flow

## Notes and References
- This has been mentioned in a couple different collab cycle tickets: 
   - [88700](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/88700)
   -  #55849

One example of how this could work would be including an "Apply" action directly in the dropdown. Also see @Cieramaddox 's work on CC scheduling filters for inspiration.

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlgyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86f1f061614056df743f7c3fa6c934f7525cee19/Small%20Improvements%202024%20_%20Appointments%20FE%20%281%29.png" alt="Small Improvements 2024 _ Appointments FE (1).png" />

## Acceptance Criteria
- [x] Design spec created
- [ ] Reviewed with design at office hours
- [ ] Reviewed with SMEs at SME sync
- [ ] Submitted ticket to the experimental design system

## Deliverables
- [Figma Design Link](https://www.figma.com/design/n7gi8dXPxEehLpFErznAMu/Component-Dropdown-exploration-%7C-Appointments-FE?node-id=2003-38709&t=2zIoQI56SYcayl45-1)

**Comment by Cieramaddox** [comment]
Bring to design office hours for feedback

**Comment by Cieramaddox** [comment]
This is currently being discussed at a higher level. Awaiting further direction
