### ISSUE TITLE
Add indicators to links to VA.gov that open in a new tab

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#88871]
## Task Description

This updates links across the Appointments tool to follow [DS guidance](https://design.va.gov/components/link/#behavior) when opening in a new browser tab:

- Links to VA.gov should open in the same tab UNLESS they are in the scheduling flow. 
- In that case, they should open in a new tab, with additional text (and possibly an aria label)
- See guidance [here](https://design.va.gov/content-style-guide/links#linking-to-external-sites)

Any links that open in a new tab should include link text at the end of the link that says “(opens in a new tab)”. That said, because users are not in a form flow where they might lose form prgress, links should open in the same tab. See DS guidance on link behavior for more information.

## Notes and References
Collab cycle specifically wants us to address the following (#88444):
- Links in the application footer
- The link to the directions in Google Maps on appointments details page 

## Acceptance Criteria
- [ ] Audit/list of all links that open in new tab
- [ ] Audit/list of all links in scheduling flow that do not open in a new tab
- [ ] Designs showing how links that open in a new tab should be treated

## Deliverables
- [Design spec](https://www.figma.com/design/zBxgJvco4njdDIA2Botv4O/Links-open-in-a-new-tab-without-warning-%2388444-%7C-Appointments-FE?node-id=8002-23783)
- All scheduling flow footers
- All details pages with directions link.

**Comment by outerpress** [comment]
Note: need to break this up:
Appointment list
- Need help section
- OH redirect alert

Details pages
- Need help section

Scheduling flows
- Need help section

**Comment by outerpress** [comment]
* #96729 will cover the issues noted in #88444. No need for design file as the visual UI isn't changing, we're just changing those links to not open in a new tab.
* OH alert work is being handled in #93262

This is all covered and tracked so closing this ticket.
