### ISSUE TITLE
[Backend] Update VetsAPI error handling of EVSS data

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8887]
## Background
See ticket: Investigate increased Error rate on Direct Deposit #8852

## Tasks
- [ ] Update error handling of EVSS data into VetsAPI
- [ ] Update VetsAPI data sent to the Frontend

## Acceptance Criteria
- [ ] EVSS data is correctly processed by VetsAPI
- [ ] VetsAPI sends correct data to Front End resulting in appropriate error messaging/alerts being displayed

**Comment by lihanli** [comment]
@mshea0606 this has been merged and deployed to production. in the logs i'm seeing the updating error codes.

**Comment by mshea0606** [comment]
@lihanli Great!
