### ISSUE TITLE
[Design] Create design when Veteran already has an appointment at that time

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88887]
## Scenario 

Veteran attempts to book a date and time, but they already have an appointment at that time. Here's what's currently in production, which shows up after submission:

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWozQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b9a1b722985690c255f257a51f023b60c1cf157/Screenshot%202024-07-16%20at%205.02.39%E2%80%AFPM.png" alt="Screenshot 2024-07-16 at 5.02.39 PM.png" />

Can also reference: [Profile](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=0-787&t=XPi72yTHsk3E7YrX-0) uses a couple designs, which we could review. Inline below the component or a modal.
## Tasks

- [ ] Decide on where the interaction goes. E.g., inline alert on the date and time page when selecting the continue button. 
- [ ] Decide on the content to appear. 
- [ ] Create final wireframe with content. 
- [ ] Place wireframe in WellHive API usage and MVP scope pages in Figma file.

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/88887?planning-poker) with Zenhub @cgednalske @Cieramaddox

**Comment by benbrasso-agile6** [comment]
@Cieramaddox ready to close this ticket?

Cc @cgednalske
