### ISSUE TITLE
[Research] Complete research synthesis

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88888]
## Tasks

- [ ] Decide on how to present the research synthesis
- [ ] Complete research synthesis
- [ ] Post artifacts to Github repo

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/88888?planning-poker) with Zenhub @cgednalske
