### ISSUE TITLE
Move Filtering of providers page to stg eng

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88896]
## Tasks

- [ ] Move Filtering of providers page to stg eng
   - [ ] [Filter page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3173-87105&t=DW3AEvGREtFtyiuJ-4)
   - [ ] [Sort by values](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3173-79831&t=DW3AEvGREtFtyiuJ-4)
   - [ ] [Practice values](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3173-79832&t=DW3AEvGREtFtyiuJ-4)
   - [ ] [Results page](https://www.figma.com/design/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?node-id=3173-79807&t=DW3AEvGREtFtyiuJ-4)

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/88896?planning-poker) with Zenhub @lee-delarm6
