### ISSUE TITLE
Get vets-website staging env pointing to WellHive Sandbox

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88892]
## Tasks

- [ ] Get vets-website staging env pointing to WellHive Sandbox
- [x] Store API key (and decide where)
- [x] Test and validate the connection

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/88892?planning-poker) with Zenhub @simiadebowale

**Comment by lee-delarm6** [comment]
AWS key and URL is stored on our keychain

**Comment by lee-delarm6** [comment]
Let's get together to just go over what I've done here @simiadebowale (and @benbrasso-agile6 if you want). We are able to replicate what I've done on repeat for all other Wellhive endpoints. A new third party (like HSRM or CDW) should be MUCH faster to replicate this work as well.

I'd appreciate a person who specializes in just backend to take a look at what I've done to see if there's anything I should change

<img width="880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWMrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c4df133888ef73041f2bbe321e11b6ec9186495/Screenshot%202024-08-07%20at%204.56.07%E2%80%AFPM.png" alt="Screenshot 2024-08-07 at 4.56.07 PM.png" />

**Comment by lee-delarm6** [comment]
<img width="1893" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWcrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2771ecb439f0c590e5c9abdbee069fa9191c2dfb/Screenshot%202024-08-07%20at%204.36.52%E2%80%AFPM.png" alt="Screenshot 2024-08-07 at 4.36.52 PM.png" />

**Comment by benbrasso-agile6** [comment]
It sounds like Kanchana or Gaurav will be coming over. If Corey can't get to it in the short term, it sounds like we'll have Kanchana or Gaurav in a week or so. cc @JRRoof

**Comment by benbrasso-agile6** [comment]
I know Appointments is working on a prod issue ATM

**Comment by benbrasso-agile6** [comment]
@loripusey as conversations have been progressing with PMD and IVC about testing, specifically: 

> From an EPS perspective, I believe the following two tests are needed:
> 
> System integration test. Purpose is to test the end-to-end functionality between VA.gov and EPS in a test environment, performed by the Appointments and EPS teams.

We'll need to start considering how to move this ticket along. No timing yet on the above. But, I don't believe we have any blockers for this ticket.

**Comment by loripusey** [comment]
closing for now, will replace with new FE & BE tickets being created
