### ISSUE TITLE
Edit: Health Quest Service pt. 2

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88907]
## Issue Description

- Health Quest Service and Authorization Design Doc and many other documents in Confluence use personal names. This is not appropriate on the Platform website because team members roles from time to time, making documents go quickly out of date.

- Additionally, there should be no headers without further text.

## Tasks
- [x] Review style guide guidelines regarding personal names
### CONTENT TEAM:
- [x] Review and edit [Health Quest Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831341/Health+Quest+Service) re: inclusion of names
- [ ] Edit empty headers at bottom of page and the text underneath in [Health Quest Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831341/Health+Quest+Service) 
(Known External Dependencies, Outage Status and Maintenance Windows, Service Level Agreement, and Escalation Procedure) 
- [ ] Under **Known External Dependencies** heading, say "There are no known external dependencies" if appropriate 
- [ ] Fix grammar in the text under **Troubleshooting**
- [ ] Remove the name **Laurence Guild** and replace with an alternative slack channel or team to contact for help
- [ ] **Product Team** review page content for accuracy
- [ ] **Content Team** review page for launch blockers
- [ ] Prepare page for deployment

## Acceptance Criteria
- [ ] This page been updated and is ready to be published
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@BSmolensky this ticket is to capture the additional work involved in completing the issue. Please score it to account for the additional points.

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/88907?planning-poker) with Zenhub @BSmolensky

**Comment by BSmolensky** [comment]
SME contacted. SME is "On Support" this sprint and my have low bandwidth for this. Searching Slack/Github for potential alternate SME.

**Comment by BSmolensky** [comment]
SME contacted. SME is "On Support" this sprint and my have low bandwidth for this. Searching Slack/Github for potential alternate SME.

**Comment by BSmolensky** [comment]
According to Adrian Rollett and Stephen Barrs, HQS is no longer in use. 

> ADRIAN: Hey Brian, I don't think the healthquest service is in active use so I'm not sure if it's worth spending time on documenting it. (at)Stephen Barrs do you have any recollection about this?
> STEPHEN: yep that was part of a Questionnaires pilot that failed successfully (it determined that the product work should not continue)

After consulting with SME, HQS page should be archived.

**Comment by BSmolensky** [comment]
UPDATE: HSQ Page has been archived.
