### ISSUE TITLE
Audit: External Service Integrations pages

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88901]
## User Stories
_"As a VFS Team member, I need to know the information on the External Service Integrations
is up-to-date and complete, so that I can build on va.gov with confidence_

## Issue Description

- The [External Service Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) section of Platform Website contains pages with several formatting errors and missing information, as well as use of personal names. We need to audit this section and create a list of the violations, in order address problems on each page.

---
## Audit (Part One) - this work can most likely be completed in a single sprint
- [x] Conduct audit of [External Service Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) section of PW
- [x] Assign each member of the PCT equal number of pages to review
- [x] Create [Spreadsheet](https://docs.google.com/spreadsheets/d/1fmV4M-mV4wIVCPsxYzxK_c2KjsdlQaGepG1B9VwFQvE/edit?usp=sharing) to allow team to document their findings and create list of pages with details of each issue
## Audit (Part Two) - This work can likely be completed in separate, single sprint
- [x] Create separate edit tickets to fix the violations
- [x] Identify SMEs for each page
## Audit (Part Three) - this work might take several sprints
- [x] Work with SMEs to fix issues
- [x] Deploy SME-approved updated pages

## Acceptance Criteria
- [x] PCT has reviews all pages
- [x] Separate tickets have been created to fix each page of the ESI section of the PW that needs fixing. 
- [x] SMEs have been identified and assigned
- [x] All pages updated and fixed
- [x] All updated pages deployed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/88901?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by BSmolensky** [comment]
I took a quick look at this section for another ticket. For quick reference, I have included links to every page in this section below: 
(NOTE: All pages listed have issues, save for one, but I have included notes to certain issues that jumped out at me while quickly scrolling through. These notes are not an exhaustive list of issues by any means)

1. [Active Directory Federation Services](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1888485505/Active+Directory+Federation+Services) 
2. [Appeals/Caseflow](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887502340/Appeals+Caseflow) 
3. [ArcGIS.com](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814279/ArcGIS.com) 
4. [Benefits Gateway Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887272987/Benefits+Gateway+Service) 
5. [CARMA](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781482/CARMA)
6. [(Deprecated) Central Mail API](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798523/Deprecated+Central+Mail+API) -- Doesn't have name issue but Should this page even be on the PW?
7. [Certificate of Eligibility (COE)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2363555845/Certificate+of+Eligibility+COE)
8. [CMS-SSOi](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887600699/CMS-SSOi) - No names here either, but this page has no intro and no info. It just points the user to a diff page. Consider revising. 
9. [Coronavirus Chatbot](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886814308/Coronavirus+Chatbot) - This page names names...but is this chatbot still valid?
10. [DS Logon ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912543/DS+Logon)- No names, but email address in contacts section needs to be checked. 
11. [Debts](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887764481/Debts)
12. [EVSS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240213/EVSS) - No names listed, but pages states that EVSS is being migrated to Lighthouse. Has that been completed?
13. [EWIS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305740/EWIS) 
14. [Enrollment Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601919/Enrollment+Service)
15. [GSA API](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885667529/GSA+API)
16. [GIDS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912583/GIDS) - This pages is strange and should be looked at.
17. [ID.me](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886912590/ID.me)
18. [Lighthouse SSOi Oauth](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436803/Lighthouse+SSOi+Oauth)
19. [MDT - Denver Logistics Center](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798533/MDT+-+Denver+Logistics+Center)
20. [Master Person Index (MPI)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886847049) -- HURRAY! This page in GREAT SHAPE. Recently updated. Should be used as the standard for the rest of the pages listed here. 
21. [MVI request XML](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567937/MVI+request+XML)
22. [My Healthe Vet](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885667536/My+Healthe+Vet) -- This page has "TODO (additional contacts required)" under contacts. That makes this a DRAFT and an incomplete page. 
23. [Pre-Needs Burial (EOAS)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305747/Pre-Needs+Burial+EOAS)
24. [SSOe OAuth: Token Introspect Service and Secure Token Service (STS)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887698956/SSOe+OAuth+Token+Introspect+Service+and+Secure+Token+Service+STS)
25. [SSOe](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887436810/SSOe) - Page has a notice from 2020 about "Currently in beta" 
26. [Search.gov](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887043657/Search.gov)
27. [TIMS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885798540/TIMS)
28. [VANotify](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885634900/VANotify)
29. [VBS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2120319089/VBS)
30. [VHA Access to Care](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240236/VHA+Access+to+Care)
31. [VONAPP](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887240243/VONAPP)
32. [Template](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887567914/Template) - This template seems to be the source of nearly all the issues listed here. 
33. [Health Quest Service](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885831341/Health+Quest+Service)
34. [Integration Hub (iHub)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1887305754/Integration+Hub+iHub)
35. [VR&E CMS](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885602009/VR+E+CMS)
36. [VA Profile](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2807693782/VA+Profile)

So ticket will likely create around **35 additional tickets**.

**Comment by jknipes** [comment]
@department-of-veterans-affairs/platform-content I finalized the score on the higher side at an 8 due to the length of the list above

**Comment by BSmolensky** [comment]
After Further review: this ticket has been recategorized as an EPIC. New, smaller, tickets will be created and assigned to each PCT member.

**Comment by jknipes** [comment]
All issues complete, closing this Epic as _Done_

**Comment by jknipes** [comment]
Reopening ticket: Only the review portion of the audit is complete.

**Comment by jknipes** [comment]
working with Back End CoP to complete the edits

**Comment by jknipes** [comment]
Timeline has been extended on the Roadmap to reflect current velocity and anticipated availability of SMEs.
