### ISSUE TITLE
Platform Security Access Reviews - Google Analytics

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#88915]
### Description
OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

- [ACCESS REVIEW - Google Analytics](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3213787639/ACCESS+REVIEW+-+Google+Analytics) - @jestutt 

---

### Tasks
- [ ] ~Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.~ -- User list generated, just need to remove.
- [x] Review the default/standard permissions we grant out.
- [x] Identify list of current administrators
- [x] Determine who from the VA should be granted as an administrator. -- Should be Ray Wang, our team's PO.
- [ ] ~Document the results of the review using the below template.~ 
- [ACCESS REVIEW - Google Analytics](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3213787639/ACCESS+REVIEW+-+Google+Analytics)

---

### Acceptance Criteria

- [ ] Necessary information on the access review template is filled out.
- [x] Additional work needed is created in a separate ticket.

**Comment by johnny-jesensky-adhoc** [comment]
First steps -- remove users who haven't accessed tools in the last 12 months. Likely will need to make an announcement.

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc 
Here's the export of Google Analytics (GA) and Tag Manager (GTM) user account from the Google Marketing Platform (GMP): [gmp_org_users_20240813_075350.xls](https://github.com/user-attachments/files/16599487/gmp_org_users_20240813_075350.xls)

I've added a "Login Status" column with the following labels: 
- good (263) - no action
- 12m (12) - haven't logged in since last Aug and I recommend going by the month as a while and deleting
- more than 12m (99) - delete
- n/a delete (12) - not attached to any product and need to be deleted
- never (198) - no login history which means they've never logged in or any login preceded the move to 360. Need to confirm that access was not granted in the last 3 months and delete any who have gone longer than that

It's a little telling about our process and/or the organizational view that a third of current users (198/584) have never logged in. 

Could @Blivaditis and @ChristineYoungZA process the deletions?   

Here's the GMP Org Admins. We do not seem to have anyone from the VA but I still wonder if we need that with this tool. 

<img width="1143" alt="Screenshot 2024-08-13 at 7 57 03 AM" src="https://github.com/user-attachments/assets/f00d7cd7-f2a3-44e0-8ab0-f0f15692dea0">

Admin level access to individual Properties is harder to find -- you have to look at each user to see their settings. We may have to do this because Property admins can add users to their properties and this might be something we need to reconsider.

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc 
Google Analytics
@Blivaditis or @ChristineYoungZA can correct me here but current process give everyone "Analyst" level access to all GA Properties in the VA's account unless we have some indicator that it's a special access like the Lighthouse team or the VA Notify team who only need their property and/or "Editor" level permissions. 

Google Tag Manager
@jestutt manages these and are almost always special requests and evaluated by need before granting "Read", "Edit" or "Publish" level access.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks for the solid start on this @jestutt  -- follow-up work will be tracked in #90715, which will be picked up next sprint by @ChristineYoungZA and @Blivaditis.
