### ISSUE TITLE
Investigate Pre-Fill on Frontend for 686

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#8891]
## User Story
As a Veteran, I want to have as much info filled in for me as possible so that I can get through these transactional forms as quickly and easily as I can.

## Considerations
- Pre-Fill has been setup [from the backend (#7883)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7883#issuecomment-624241167) but it needs to be integrated into the frontend.
- Here is his PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4188

## Tasks
- [x] Investigate how FE can implement pre-fill (#VFS-platform-support; Chris Valerida)
- [x] Establish a plan to move forward

## Acceptance Criteria
- [x] Define and document in GH what the procedures are for implementing Pre-Fill 

## Next Steps
- [ ] A PR for Pre-Fill has been requested for merging with the intent to show in staging, fields that have known information are pre-filled in
- [ ] Implement the fix as necessary

**Comment by jason-gcio** [comment]
Lihan's BE ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7883

**Comment by cohnjesse** [comment]
Here is the MD file with a synopsis of the prefill issues https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/686_prefill.md
