### ISSUE TITLE
Skills Build: Review online form flow

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#88922]
## Description
The product team is digitizing VA Form 22-10282. We need to review the online form flow.

## Resource
[Current designs](https://www.figma.com/design/QTjUfSK6tYBSu7I1dYJaeO/VEBT-Form-22-10282%3A-IBM-Skillsbuild?node-id=783-44595&t=sKOvFrlEGv8pUbv0-1) (Figma)

## Tasks
- [x] KF: Draft recommendations (with support from AP, as needed)
- [ ] KF: Share recommendations with product team
- [ ] KF: Finalize recommendations with product team

## Criteria
- [ ] Our content recommendations have been finalized with the product team

**Comment by katherine-fung** [comment]
Welcome back @aprocik1! 

I've reviewed the IBM Skillsbuild form updates. I let the team know that we need clarification for the stakeholder on 3 areas of the form (questions are in the intake ticket #87265). If you can reiterate to the team that we do need to make that content more clear, that would be great too. 

Otherwise, I'd love your review of the recommendations I left in comments on these pages (I marked them "draft"). Thank you! 

- intro page: 

https://www.figma.com/design/QTjUfSK6tYBSu7I1dYJaeO/VEBT-Form-22-10282%3A-IBM-Skillsbuild?node-id=923-31222&t=NTBHszZye4qibf9p-0

- salary question: 

https://www.figma.com/design/QTjUfSK6tYBSu7I1dYJaeO/VEBT-Form-22-10282%3A-IBM-Skillsbuild?node-id=923-31222&t=NTBHszZye4qibf9p-0

- confirmation page: 

https://www.figma.com/design/QTjUfSK6tYBSu7I1dYJaeO/VEBT-Form-22-10282%3A-IBM-Skillsbuild?node-id=783-44973&t=NTBHszZye4qibf9p-0

**Comment by aprocik1** [comment]
@katherine-fung, thanks for drafting these recommendations. I've responded to all your comments, including the three outstanding questions you've identified for the product team. Let me know if there's any other support you'd like on this.

**Comment by katherine-fung** [comment]
Noting that A and I have discussed the static page with Beth, Danielle and Jenny. We've asked the designers to pass questions on to the SMEs to help us determine where information about Skillsbuild and the entry point should live on va.gov.

**Comment by katherine-fung** [comment]
Adding that design system/governance and SMEs currently disagree about whether this form needs to include race and gender questions. We're waiting for them to discuss the week of 8/26 and provide us with an update about how they'll move forward.

**Comment by katherine-fung** [comment]
ticket is blocked while we wait for clarification from the team/governance/design system about the race and gender questions

**Comment by katherine-fung** [comment]
Updating this to reflect that the team has confirmed they should keep the demographic questions, until someone explicitly tells them to remove the questions. 

The team is placing the questions at the end of Step 1 for Veteran's personal information. The team has implemented @aprocik1's recommendation for a stop screen before the race and gender questions. After the demographic questions, the form will ask Veterans other optional questions. Kristin's thoughts: "I think we want to make it clear that the education and employment questions are also for statistical purposes and wont effect the user's eligibility for the program. However y'all want to do that."

@aprocik1 can we discuss this in our next one-on-one?

**Comment by katherine-fung** [comment]
Closing this ticket because we've provided all the recommendations the form needs going into staging review. cc @strelichl
