### ISSUE TITLE
ARM: Add OGC to disability hub landing page

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#88926]
## Description
We need to update the right rail on the disability hub landing page right to add this OGC link: [Accreditation, Discipline, & Fees Program](https://www.va.gov/ogc/accreditation.asp)

## Resource
[Draft for product team review](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692888741111/2474c0612887653142ab991d234898b6968dbf0e?wid=0-1721217459911) (Mural)

## Tasks
- [x] AP: Draft recommendation
- [x] Product team: Approve recommendation
- [x] AP: Update in Drupal
- [x] AP: Share with MZ
- [x] MZ: Copyedit and publish

## Criteria
- [x] The right rail on the disability hub landing page includes the OGC link above

**Comment by aprocik1** [comment]
@megzehn, can you publish the update on this page? I just added a link for accredited representatives to the right rail. Here's the Drupal page: https://prod.cms.va.gov/disability

Thanks in advance!

**Comment by aprocik1** [comment]
I shared the live page with the product team and tracked this ticket for "capacity metrics." I'm closing this ticket as complete.
