### ISSUE TITLE
Record video with updated Feedback Footer

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#88944]
## Issue Description
We discovered the existence of a Platform YouTube video that contains video of an outdated Feedback Footer on Platform Website, and we need all such videos to display the current, updated footer.

---
## Tasks
- [x] Record new visual segment that displays the Feedback Footer currently in use on Platform Website
- [x] Edit into current video
- [x] Peer review of video by Content teammate for accuracy, quality

## Acceptance Criteria
- [x] video is ready to be published
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
@jilladams : FYI

**Comment by jilladams** [comment]
@jknipes do you need something from me on this one?

**Comment by jknipes** [comment]
@jilladams whoops, wrong Jill. Sorry!

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/88944?planning-poker) with Zenhub @BSmolensky @CherylEvans @laucon @taylojill

**Comment by jknipes** [comment]
@laucon could you please add the link to the video in the Issue Description?

**Comment by laucon** [comment]
Actually, I can't because the video on the internet right now is the old version. And the new version is on my desktop. It's not in the cloud like a confluence doc would be. The next ticket in this process would be to publish the new version of the video. I could put a link to the old, inaccurate version of the video, if you like.

**Comment by jknipes** [comment]
This portion of the project is complete, closing ticket
