### ISSUE TITLE
[Team] 10-10 apps: Work with Josh Faulkner to identify additional resources with VES

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#88967]
## Background
As an action item on the [Postmortem for Special Characters](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/51cb41e9fd0a6a465acd6ea08acc37933628307c/Postmortems/2024/2024-07-18%2010-10%20Special%20Character%20OOB%20Post%20Mortem.md), the team has determined additional process and documentation improvements are needed to ensure we follow all proper steps and precautions to avoid negatively impacting Veterans and causing additional work for ourselves and other VA teams.

Postmortem Action Item: Increase VES Resource Availability with the VES team 
- Problem to solve:
     - The 10-10 team has a dependency on the Enrollment system, and we have a single point-of-contact to use (Joshua Faulkner) when testing. This causes delays when that contact is out of the office or unavailable.
- Action Plan: 
     - The 10-10 team would like to request another dedicated resource be available from the VES team to assist in testing/validation. This resource would need to be reachable/available in DSVA slack.  
- Implementation & Measurement: 
     - POCs are documented and their contact details are available to the 10-10 team. POCs are added to all relevant 10-10 channels and tagged as needed with the expectation of reply within an agreed upon amount of time (to be determined with the VES team).
- Failure Detection:
     - The 10-10 team is unable to get in contact with the VES team in a timely manner

## Tasks
- [x] Team will set up a discussion with Joshua Faulkner (and other VES contacts if applicable)
- [x] Team will discuss identifying an additional resource that can be contacted for testing needs
- [x] Team will discuss response times and efforts involved when testing is performed
- [ ] Notes and action items from the discussion(s) will be documented and stored in our Github folder
- [x] A teammate is assigned to track action items to completion

## Acceptance Criteria
- Discussion(s) held between 10-10 and VES teams, an additional resource is identified, a testing communication plan is defined and action items will be tracked.

**Comment by emily-brown34** [comment]
Josh Faulker, Ramya Venkataraman, Ramya to send her back ups in slack - will document here once received

**Comment by emily-brown34** [comment]
Reetu Dhanda 
SQA Test Engineer (on VES PACT Act scrum team)
reetu.dhanda@va.gov

Turkan Kasamanli
Test Automation Engineer (on VES PACT Act scrum team)
turkan.kasamanli@va.gov

**Comment by hdjustice** [comment]
added to [Team Charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/team-charter.md#va-relationships) contacts list and [OOB process](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/application/1010EZR-Runbook.md#oob-process-steps) section of Runbook doc
