### ISSUE TITLE
[Team] 10-10 apps: Revise ticket templating/writing to include order/handoffs/sign offs required

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#88969]
## Background
As an action item on the [Postmortem for Special Characters](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/51cb41e9fd0a6a465acd6ea08acc37933628307c/Postmortems/2024/2024-07-18%2010-10%20Special%20Character%20OOB%20Post%20Mortem.md), the team has determined additional process and documentation improvements are needed to ensure we follow all proper steps and precautions to avoid negatively impacting Veterans and causing additional work for ourselves and other VA teams.

Postmortem Action Item: Embedded Tasking in Order of Operations:
- Problem to solve:
     - Development work has the potential to be deployed to production without team/PM reviews and approvals, or safeguards in place to restrict impact to Veterans.
- Action Plan: 
     - Embed tasks in the correct order of operations within the ZenHub ticket, with clear pairing, review, handoff, and signoff points. Link and track all associated tickets and blockers to ensure all requirements have been met and testing has been completed prior to launching.
- Implementation & Measurement: 
     - Create ZenHub ticket template to ensure order of operations is clearly understood and agreed on by the team prior to starting on work. Measure success by the smooth progression through stages, clear communication, and nothing going to production without several checks and documented signoff* (see below)
- Failure Detection: 
     - Identify any stage where progress is blocked or delayed due to missing handoff or signoff.

## Tasks
- [ ] Team members will identify their "ideal" ticket details
- [ ] Team will hold a workshop to create GH template(s) that include an outline of details and tasks needed
     - [ ] Required demo/review, reviewer signoff and documentation tasks will be marked to ensure they are included in every ticket before considered complete and handing off to the next step, if applicable
     - [ ] Include additional steps, such as paired merging and other suggestions that have come from this postmortem.
- [ ] Team agrees to the outline and required line items
- [ ] Team will include links to the Template(s) in the team channel (pinned/saved), and team charter documents

## Acceptance Criteria
- An easy-to-use template(s) is created and the team has agreed to begin using it immediately
- Tickets that are not in progress will be re-written to align with the new template outline

**Comment by hdjustice** [comment]
Template created and in progress.  You can find the template in [this GH Folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/1010-base-template.md).  It is available to select when creating a new ticket

**Comment by hdjustice** [comment]
In discussion with the team, we have decided to try a new approach.  We use epics and "stories" (aka tickets or issues) today, but rely less on the Epic details and include alot of detail in the stories.  We would like to utilize the Epics more as a high level, end-to-end Epic with problem statement, links, background, etc, as well as include a "task list" that we talk through during refinement.  This will help us identify the order of operations and dependencies. This task list is easily converted into stories (GH function Yay!) where story-specific details can be added and dependencies linked, as well as bake-in team reviews & approvals/signoffs.  

We will start with the EZ Insurance work (sort of already has stories, but can be adjusted a bit to this format), and continue doing this with new work that comes in.  We may be able adjust some other in-flight work into this format as well.
