### ISSUE TITLE
[Team] 10-10 apps: Document OOB Process steps

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#88968]
## Background
As an action item on the [Postmortem for Special Characters](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/51cb41e9fd0a6a465acd6ea08acc37933628307c/Postmortems/2024/2024-07-18%2010-10%20Special%20Character%20OOB%20Post%20Mortem.md), the team has determined additional process and documentation improvements are needed to ensure we follow all proper steps and precautions to avoid negatively impacting Veterans and causing additional work for ourselves and other VA teams.

Postmortem Action Item: Add OOB Process steps into troubleshooting document
- Problem to solve:
     - When an OOB is requested, stress is high and a fix is urgent.  During this time, the team missed important, critical testing steps that are required to be followed, and would have prevented further rework and impact to Veterans.
- Action Plan: 
     - The 10-10 team would like to create an Out-of-band deployment protocol section within the troubleshooting document to follow in the event of an OOB deployment request.
- Implementation & Measurement: 
     - The OOB deployment is smooth and easily managed, all testing is successful and no additional rework or negative impact is introduced.
- Failure Detection: 
     - The OOB deployment process is not followed and the team experiences avoidable difficulty or causes negative impact to Veterans

## Tasks
- [x] Outline common steps of an OOB deployment request
     - Possibly the [Runbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/application/1010EZR-Runbook.md)?
     - Or a separate document?
- [x] Add internal team steps to take to ensure successful deployment, including e-2-e testing and documentation
- [x] Add accountability steps for second review to confirm all steps were followed
- [x] Team agrees to OOB deployment protocol
- [ ] OOB Outline is documented and stored in Github folder for future reference
- [ ] OOB Outline is referenced in OOB tickets 

## Acceptance Criteria
- OOB Deployment outline is created and ready for use on the next OOB request.

**Comment by hdjustice** [comment]
This has been reviewed with the team and added to the [Runbook document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/application/1010EZR-Runbook.md#oob-process-steps).
