### ISSUE TITLE
[SD] Type Ahead POC

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#8896]
## Product Outline

- Slack channel: #va-search 
- On-site Search [Master Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/onsite-search#search-product-outline---vagov---this-is-a-draft)

| Name          | Role                                          |
| ------------- | --------------------------------------------- |
| John Hashimoto  | Public Websites Product Lead                 |
| Liz Lantz     | Designer/Researcher                           |
| Nick Sullivan | FE Engineer                                   |
| Danielle Thierry   | Content                                       |
| Ayush Chakravarty   | Search.gov Product Manager                         |

### Table of Contents

- [High Level User Story/ies](##high-level-user-story/ies)
- [Hypothesis](##hypothesis)
- [OKR](##OKR)
- [Bets](##bets)
- [How It Works](##how-it-works)
- [API Calls and Dependent Systems](##api-calls-and-dependent-systems)
- [The Plan](##the-plan)
- [Screenshots](#screenshots)

## High Level User Story/ies
As a veteran, I need a faster, easier way to search for information on VA.gov so I can save time and avoid wading through lots of content.

## Hypothesis
**If** _we leverage the type-ahead feature from Search.gov in on-site search_ **then** _we can expect VA.gov site users to find what they need faster, saving time and reducing cognitive load_.

## OKR
- **Public Websites 2020 Strategy Goal**: Decrease the time users spend waiting for an outcome.
- **Objective**: Make VA.gov site search a more effective, reliable way for users to more quickly get the information they seek
- **Success metrics**: Custom tagging may be required to capture the following KPIs -- 
1. Increased use of on-site search
2. High click throughs for type-ahead "suggestions"
3. Increased conversion from search to most popular pages and tasks

## Bets
- Site users will use the on-site search tool more often
- Site users will rate the search experience as more valuable (faster, more accurate)
- Overall satisfaction for VA.gov will increase (via Foresee scoring), as users find site utility has significantly improved

## How It Works

- Suggestions are derived from the searches performed on the VA.gov website.
- Up to five suggestions related to VA.gov visitors’ search terms are returned and are updated in near real time.
- A given term/phrase must be searched 5 times in a 24 hour period to appear as a suggestion. Suggestions then remain for a 30-day period. Certain queries will not appear as suggestions for privacy and security purposes.
- If you VA.gov wants a specific term to always appear as a suggestion, we will need to collaborate with the Search.gov team, which will manually input and whitelist the term. The recommendation is to use this for hard to spell terms, particularly long ones and alphanumeric form titles.
- Search.gov's implementation of type-ahead does support fuzzy string matching to help with typos.

## API Calls and Dependent Systems
- Search.gov [Type-Ahead suggestions API](https://open.gsa.gov/api/searchgov-suggestions/)

## The Plan
- **Design:** Conduct design discovery to consider the options for implementation in the site header and on the main Search page.  _Consider ( via @drorva ) : Should search be positioned more prominently on the home page?_
- **Technical:** Conduct technical analysis to (a) validate VA.gov implementation of the Search.gov API is conducive to utilizing the type-ahead suggestions API "as is" and (b) determine the LOE
- **Product:**  Via an audit of the feature, validate that the type-ahead suggestions API delivers expected--and valuable--results/recommendations **(Note: Our analysis has revealed that the type-ahead suggestions powered by Search.gov are not as "relevant/valuable" as expected.  Further investigation by Search.gov has determined that the feature logic is not working as expected and is under active investigation for resolution.**

## MVP POC Release Plan
   
- We will implement the flipper "gating" feature in order to release to 10% of audience for a testing period that allows us to gather enough data to glean insights.
- Our hypothesis:

  - **We believe** that enabling type-ahead as a search feature
  - **Will result In** more relevant search results for users 
  - **We will know we have succeeded when we see** a significant decrease in bounce rate compared to the overall site search average of 48% and a decrease in paging associated with search.

_NOTE: According to two years of Google Analytics data (July 2018-July 2020):

    - Exits (Bounces): The number of exits from VA.gov site that occurred following a result from an internal search: 48% (This is the percent of searches where the user left without clicking through any result.)

   - Paging: The average number of pages a user viewed after conducting a search: 3.36 (viewing 1 page is considered optimal)_

- After a period of testing, we may implement and further test "curated or Best Bet" Type-Ahead suggestions to determine if they result in higher yield.
- Via Google Analytics, we will track the following: 
   - What percentage of users search by using the type-ahead feature?
   - What terms are users querying when they use type-ahead?
   - What suggestions are users clicking on?
   - What is the percentage of suggestions clicked vs. ignored?
   - What is the bounce rate from pages clicked to from the type-ahead results/suggestions?
- Questions/Bets
   - Does type-ahead reduce "wayward queries" by offering a shortcut to the most popular and/or trending topics/content (e.g. instead of a general phrase such as "disability" type-ahead suggests "disability rating," "disability ratings," etc.)?
  - Does type-ahead reduce search bounce rate?

## Curating Type-Ahead Suggestions 

As a follow on test during the MVP phase, we may implement an iteration of the auto-complete feature by white-listing popular terms for key queries such as GI Bill.  We can do this in one of two ways, according to Search.gov:

1. Protect an existing term from being ever removed (Search.gov checks a box on the relevant term(s))
2. Add a new set of terms and protect them from being removed (Search.gov pastes the terms into the backend interface and checks the box)

At this time, there is no automated way to manually manage suggestions, and no Admin Center interface for this.

## Tasks for MVP/POC Launch

- [X] Hold project kickoff with Platform team to determine required Collab Cycle touch points ahead of MVP launch to 10% of VA.gov users.  The results of the meeting recapped here:
  - [X]  Design Intent: **Not needed**
  - [X] Usability Testing and Research Plan review: **Not needed**
  - [X] IA Request: **Not needed**
  - [X] Analytics Request: ([Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13494))
  - [X] Full Accessibility and 508 office audit: Needed, with[ initial assessment captured in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13343#issuecomment-690856372)
  - [x] Contact Centers: We can clarify with Chante whether this is needed or not ([Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13746))
  - [x] Privacy and security review: @Michael Fleet determining need for review ([Ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/169))
  - [x] Staging review: Yes — this is where we will ensure base level of accessibility and QA efforts but will allow all reviewers to give feedback. Can be done asynchronously
  - [x] Accessibility Spot Check #16914 
  - [x] QA Spot Check
  - [x] Post-launch check-in: definitely!!

## Pre-Release Checklist

- [x] Instrument analytics [FE Engineer] ([Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13494))
- [x] Integrate Flipper [FE Engineer] ([Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14452))

## Screenshots

Initial design and accessibility consideration [ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10489)

Search.gov Preview of Type-Ahead for VA.gov
<img width="1050" alt="Screen Shot 2020-05-07 at 2 33 11 PM" src="https://user-images.githubusercontent.com/63107147/81336015-892a1a80-9076-11ea-98a6-3b0bd804682e.png">

Current VA.gov Search (Site Header)
<img width="866" alt="Screen Shot 2020-05-07 at 2 55 56 PM" src="https://user-images.githubusercontent.com/63107147/81336073-a959d980-9076-11ea-8ff7-e2057c744d2e.png">

Current VA.gov Search (Results Page)
<img width="872" alt="Screen Shot 2020-05-07 at 2 56 24 PM" src="https://user-images.githubusercontent.com/63107147/81336131-baa2e600-9076-11ea-830d-269b9dfa7178.png">

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by johnhashva** [comment]
Adding audit results of Type-Ahead suggestions -- with open issues identified for Search.gov assessment.

[Search.gov_Type-ahead_Issues.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4842300/Search.gov_Type-ahead_Issues.docx)

**Comment by andaleliz** [comment]
@johnhashva Is it okay I remove myself as an assignee on this since there is nothing actionable for me to do?  Also, I'm thinking the product outline should be migrated to [the product folder,](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/search) from this issue, so that it is easily accessible/findable once this epic is closed.

**Comment by johnhashva** [comment]
9/17 Update with @ncksllvn -- here is our task list:

- [ ] John check with Chante on Contact Center

- [ ] John check on Security review (probably needed, because its a new API)

- [ ] John work with Analytics to finalize tagging

- [ ] Nick to do accessibility/screen reader testing (limited to voice-over due to OS)

- [ ] Nick integrate Flipper and rules

- [ ] Consider moving from datalist element to downshift for zoom in support (accessibilty)

**Comment by denisecoveyduc** [comment]
@shiragoodman A post launch check in is outlined in the above tasks. I wanted to follow up with you regarding scheduling if this is needed. What are your thoughts?

**Comment by shiragoodman** [comment]
hey @denisecoveyduc per our convo via Slack, the post-launch check in is just a follow up to ensure you're completing the Release Plan and validating your KPIs (and not launching and forgetting). There is no need for a meeting with our team. If you have any questions, please feel free to reach out!

**Comment by denisecoveyduc** [comment]
### POC (December 23- January 31) Conclusion Summary 

**POC Summary**
The initial POC for typeahead was expected to run for 4-6 weeks with a user base of 5% of all va.gov users after which time the plan was to assess the data collected and determine how effective the typeahead feature was at improving the experience for veterans. A variety of factors (explained in more detail below) have blocked our ability to interpret the data from the POC and as a result we have decided to declare this POC inconclusive and reset the dates for a second POC which we believe will be more representative of the actual typeahead feature and its implications. 

**Search.gov Suggestions Database Purge**
Search.gov resolved a bug fix which was preventing suggestions older than 30 days from being purged from the database. This bug as well as the purge have distorted the suggestions database to the point that conclusions can not be drawn because of a lack of high quality/ targeted suggestions that improve the users ability to find relevant results. 

**Analytics Implementation**
Various analytics discoveries and changes due to implementation changes or accessibility fixes created an environment where the data has been distorted and not easily interpreted or used for definitive conclusions. 


**Conclusions**
**_Engagement:_** We did see a large percentage of user engagement (approximately 42.8%) with the feature showing appetite for the experience, despite suggestion relevance being a negative factor.
| Month         | Total # of users who had typeahead available to use | Used Typeahead | Did not use typeahead |
|---------------|-----------------------------------------------------|----------------|-----------------------|
| December 2020 | 2524                                                | 1046           | 1478                  |
| January 2021  | 13081                                               | 5638           | 7443                  |
| TOTALS        | 15605                                               | 6684           | 8921                  |

[**CAVEAT:** This data is what was presented on our DOMO dashboard; however given the analytics implementation discussed above we are making some assumptions knowing that this data may be inaccurate]

**_Importance of Quality Suggestions:_**  We discovered that the quality of a typeahead suggestions played an important factor in the users ability to find relevant results. Our hypothesis is that suggestions that added irrelevant additional phrases and words lowered the likelihood of a user getting a relevant result as a top result and lowered the likelihood of the user getting a best bet. This contributed to a lower-than-average click-through rate and we believe that incorporating suggestions relevant to the VA will improve the users ability to find relevant content. 

**_Sample Size:_** We believe that a 5% sampling of users is too small of a sample pool to get accurate user interaction results. On average only 10% of visitors use search, and we believe that releasing to 25% of users will give us more consistent usage data.

**Comment by denisecoveyduc** [comment]
All issues for this Epic have been achieved and therefore closing this epic. 

POC2 will be established (#21316) to re-examine the typeahead feature using quality suggestions and accurate analytics, which we believe will be more representative of the typeahead feature and its implications.

**Comment by johnhashva** [comment]
@denisecoveyduc solid write-through here -- thanks for making sure we captured the What Happened and Whys.   Important learning as we move to next phase -- on more solid ground.
