### ISSUE TITLE
[Team] 10-10 apps:  Increase Active Collaboration and Communication with the VES team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#88971]
## Background
As an action item on the [Postmortem for Special Characters](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/51cb41e9fd0a6a465acd6ea08acc37933628307c/Postmortems/2024/2024-07-18%2010-10%20Special%20Character%20OOB%20Post%20Mortem.md), the team has determined additional process and documentation improvements are needed to ensure we follow all proper steps and precautions to avoid negatively impacting Veterans and causing additional work for ourselves and other VA teams.

Postmortem Action Item: Increase Active Collaboration and Communication with the VES team
- Problem to solve: 
     - The 10-10 team and VES team are not aligned on understanding system behaviors and schedule of expected release items.
- Action Plan: 
     - The 10-10 team would like to request release notes from the VES team any time changes are implemented on their side to ensure that the 10-10 team is aware of them, and API specs so we know what constraints they impose on the data we send them.
- Implementation & Measurement: 
     - The 10-10 team receives automated notices corresponding to VES updates, indicating the changes introduced in some publicly visible medium (such as Slack), and access to something specifying their invocation API and any internal requirements we need to respect.
- Failure Detection: 
     - The 10-10 team is not aware of changes that the VES team has made, experience errors due to unexpected VES changes, or continue to lack documentation for how they work and what they need.

## Tasks
- [x] Team will set up a discussion with Joshua Faulkner and other VES contacts
- [x] Team will discuss setting up a standardized release notes communication process between the teams
- [x] Team will discuss API specification documentation for VES endpoints
     - How to obtain these
     - How/when they will be updated
     - How/when the updates will be communicated
- [x] Notes and action items from the discussion(s) will be documented and stored in our Github folder
- [x] A teammate is assigned to track action items to completion

## Acceptance Criteria
- Discussion(s) held between 10-10 and VES teams, a go-forward communication plan is defined and action items will be tracked.

**Comment by emily-brown34** [comment]
https://dsva.slack.com/archives/C06FDF2EN0H/p1722869568603369 request to meet with VES folks sent 8/5 11am ET

**Comment by emily-brown34** [comment]
Meeting scheduled for 8/9 at 3pm ET

**Comment by emily-brown34** [comment]
https://dsva.slack.com/archives/CMJ2V70UV/p1723230704332469 great chat with the VES team

**Comment by hdjustice** [comment]
Chat details (if link above does not work)

> **Emily Brown**
>   Aug 9th at 12:11 PM
> VES TB Thread 
> 
> **Emily Brown**
> Josh F back up is Ramya and her team, Ramya will slack her backups so we have their emails
>
>**Alex Seelig**
> SOAP service "old as dirt" and will be replaced. Super old and creates problems and never configured the right way (15 years old). Josh F doesn't have dates, unplug it, have openAPI spec. Make everything easier and more modern. SOAP will be replaced with RestAPI. No timeline yet, will involve us once they start and schedule a cutover. (edited) 
> 
> **Emily Brown**
> Josh F: sending us release notes CAN be done but he doesn't see how it would help / relate to our team.
> Might take a lot of work to parse through release notes but it would be helpful for our team to have the info available  in case something breaks we can investigate and see if anything might have contributed to the issue.
> Holly noted they do post release announcements which are exports from JIRA - the VES team will add us to the post release announcements (what channel is this delivered in? Holly will add our [1010_team@agile6.com](mailto:1010_team@agile6.com) to these announcements
>  can you add notes to what you mentioned about the API question you had?
> 

> **Alex Seelig**
> I added some of it to my note about the SOAP service but would definitely be good to have Brandon's knowledgeable notes
> 

> **Emily Brown**
> Engineers don't forget we wanted to ask about getting API specs from them as well - please ask for whatever you need! 
> [@Mitch Saltykov (he/him)](https://dsva.slack.com/team/U06EHNFG16X)
>  [@Brandon Cooper](https://dsva.slack.com/team/U072EPPPK6E)
>  [@Joshua Drumm](https://dsva.slack.com/team/U04SEFZDN0Z)
>  [@Derrick Ellerbie](https://dsva.slack.com/team/U04QVUW3LVA)
>  [@Matthew Kerns](https://dsva.slack.com/team/U052TUDHHMJ)
> 
> **Alex Seelig**

> Bribes to make this move faster=TBD
> 
> **Emily Brown**
> from josh f: sub-schema is completely undocumented itself. some documentation on restraints and required fields but is left stagnant
> 

> **Brandon Cooper**
>  Plan to move the VES to a new REST api. New documentation would be included with the release of the new api. Current api is largely undocumented/it is out of date.
> 
> **Emily Brown**
> mitch asked if the code base is accessible to us, josh f said he can give us error messages but most you'd need to look at the data - source code itself is in a private repo though so we wouldn't be able to see that (edited) 
>josh f said that a lot of people don't pay attention to slack so try email or teams if you can't reach someone - ramya and holly echoed this as well
> teams is the quickest way to reach VES folks
> scheduled downtime is once a quarter on sundays - we SHOULD be getting an outage notification the week of or two days prior. our team wasn't on these before. next is august 25th on sunday. next will be november - usually 3rd or 4th sunday of the months (edited) 
> 

> **Brandon Cooper**
> :point_up: For submissions without emails, they would fail during this window (planned outages). Any that include an email would be retried in sidekiq and should be fine.
> 
> **Joshua Drumm**
> Yeah, I think it's more about the alerts we get in the apm channel. Knowing ahead of time that it was intended would be good.
> 
> **Emily Brown**
>i think that went really well!
