### ISSUE TITLE
Remove mentions of the "Report Outdated Information" in the Contact Center Guide

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#88989]
## Background
We have received guidance from Jen to remove the "Report Outdated Information" feature from Find a Representative.

## Tasks
- [x] Remove the "Report Outdated Information" button from the Find a Representative contact center guide
- [x] Upload a new contact center guide to our Product Documentation folder

## Acceptance Criteria
- [x] The "Report Outdated Information" feature is no longer referenced in the Find a Representative Contact Center Guide.

**Comment by oddball-lindsay** [comment]
New, updated contact center guide has been uploaded: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/contact-center/product-guide-find-a-representative-2.3.docx
