### ISSUE TITLE
Display VSO / VSO Representative info in "Next Steps" of 21-22 PDF

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#88987]
## Background
We have code in place to generate a completed 21-22 or 21-22a form (#82223), but for the 21-22 we do not yet have the functionality to show the VSO Representative's information (only the VSO) -- we need the frontend to pass that to the backend.

Once the frontend Representative Chapter is built, we'll want to incorporate that VSO Representative information into the PDF download.

Dependent on https://github.com/department-of-veterans-affairs/va.gov-team/issues/92779

## Tasks
- [x] Receive the VSO / VSO Rep ID from the frontend request
- [x] Look up the related contact information -- default to our old tables and if not info exists, look at our new tables -- display in the 21-22 PDF

## Acceptance Criteria
- [x] The 21-22 PDF download includes contact information for the VSO or VSO Representative the user selected.

**Comment by opticbob** [comment]
The scaffolding for generating a 2122 next steps page is done, next is writing the code to query the old and new tables for rep info with a rep id.

**Comment by opticbob** [comment]
I'm going to use the same method to lookup the org and rep here that I used in https://github.com/department-of-veterans-affairs/vets-api/pull/18877.

**Comment by opticbob** [comment]
The lookups are done and the next steps page is up and running in the PR.  I just need to update some tests and clean it up a bit and it'll be ready for review.

**Comment by opticbob** [comment]
All the fixture PDFs were updated, the database lookups are in place and a lot of test data standardization is in this PR.  It's now in review.

**Comment by opticbob** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/18857 has merged, this is done.
