### ISSUE TITLE
Rename Rspec Request Example Groups 

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#88996]
## Summary

Many request specs name the example group with impossible to search titles. Such as

```ruby
RSpec.describe 'Education Benefits Claims Integration'...
```

Although this is common and technically correct, it can make testing and finding the controller-related tests difficult. A better approach would be to use the controller class name:

```ruby
RSpec.describe V0::EducationBenefitsClaimsController...
```

There are currently 266 request specs with this naming pattern, not including `requests/swagger_spec.rb` which is appropriately named.  

## Tasks
- [x] determine if the above conversion can be automated
- [x] rename controller specs (266x)
~- [ ] add a cop to prevent future misuse~

## Acceptance Criteria
- [x] all request specs (except swagger_spec.rb) uses the controller class name as the example group name

**Comment by stevenjcumming** [comment]
A custom cop would be required, so this functionality could be moved to a new ticket. However, I don't believe that would be worth it.
