### ISSUE TITLE
Final numbers for "Report Outdated Information" feature

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#88990]
## Background
We have received guidance from Jen to remove the "Report Outdated Information" feature from Find a Representative.  The team would like to pull final numbers from this feature into our [Reports of Outdated Info Domo dashboard](https://va-gov.domo.com/page/1509130506), so we can preserve the outdated information we've collected from users.

## Tasks
Holden:
- [x] Confirm that the "Report Outdated Information" feature has been removed (#88988)
- [x] Update Domo dashboard with final numbers
- [x] Convey date range of these reports in Domo to Lindsay

Lindsay:
- [x] Add in the Total Users metric up top, based on the date range Holden conveys
- [x] Update the dashboard description to document the "last updated" date, and to inform viewers that this feature is no longer available in Find a Representative (no more biweekly updates)

## Acceptance Criteria
- [ ] User reports of outdated information are stored in our Domo dashboard, for the lifespan of this feature.

**Comment by holdenhinkle** [comment]
Support request for prod data - https://dsva.slack.com/archives/CBU0KDSB1/p1722283701212049

**Comment by holdenhinkle** [comment]
@oddball-lindsay The data range for the records is 3/12/24-7/27/24.

The DOMO dashboard has been updated but the data platform gave me appears to be missing ~250 records. I asked them to send the data chunk with the missing rows. I'll updated DOMO again when I get it.

**Comment by oddball-lindsay** [comment]
Thank you!  Updated the [Domo dashboard](https://va-gov.domo.com/page/1509130506?userId=1801042161) with this date range in mind:

<img width="1266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1kQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2eb15d0613ce7a2abf439889a8b501ade42aeb3c/image.png" alt="image.png" />

That covers my contributions, so @holdenhinkle feel free to close this after you update with that missing data :).

**Comment by holdenhinkle** [comment]
DOMO was updated yesterday with all the data.
