### ISSUE TITLE
Detailed tech spec for Request POA service in vets-api

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#88993]
## Background
Last sprint we outlined an initial tech spec, to explore if the Request POA service can exist in vets-api (#87565).  

There were no major concerns, so we're on to the next step which is to create a more detailed tech spec that includes things like pseudo code and a database schema.  This will help leadership fully understand how this service could function in vets-api, and serve as evidence for them to make an informed decision.

## Tasks
- [ ] Create a detailed tech spec
- [ ] Share with ARM and ARF engineers for feedback
- [ ] Update tech spec with feedback
- [ ] Share tech spec with Sam Raudabaugh

## Acceptance Criteria
- [ ] A detailed tech spec for the Request POA service in vets-api has been shared with our VA Enablement teammate Sam Raudabaugh, to aid him in deciding if we proceed with this work in vets-api (and not Lighthouse).

**Comment by jvcAdHoc** [comment]
[draft pr](https://github.com/department-of-veterans-affairs/va.gov-team/pull/89536)

**Comment by oddball-lindsay** [comment]
Regarding understanding the MVP expectations for ARP -- @jvcAdHoc no good time with ARF's UX folks until next Weds, and we might actually be able to just use the existing Accredited Reps Crew meeting to talk about this.

**Comment by oddball-lindsay** [comment]
On our call to explore the UX needs for accepting/declining POA requests, ARF shared some resources.  Storing here for reference:

1. [ARP Pilot Decision Record](https://docs.google.com/spreadsheets/d/1E4muMKOZJGPYe4vQGwmwj9_aViSun8wPq5PkZyT5bVM/edit?gid=0#gid=0)
2. [SEP Screenshots](https://docs.google.com/presentation/d/1aDd9MVh-fg8bl040WeEAX_-0sZBnTntkgfhl1LEGxbg/edit#slide=id.g26c8e1bc7fa_0_94) - Slide 16 shows the SEP experience for searching for requests

**Comment by jvcAdHoc** [comment]
This is on hold for now. Will discuss it more at next crew meeting.

**Comment by oddball-lindsay** [comment]
@jvcAdHoc do you mind expanding on why this is on hold?  

My understanding was the discussion around Accredited Rep Portal designs was a "nice to have" but not required to pass this tech spec along to Sam.  But perhaps I misinterpreted!

**Comment by jvcAdHoc** [comment]
Got it, I misinterpreted your comment in Tuesday's slack up thread

**Comment by oddball-lindsay** [comment]
It'd be nice if we can wrap this up this sprint and get something over to Sam.  And if needed we can do a smaller ticket next sprint to update tech specs based on anything new we discover from the ARF/ARP discussion.

**Comment by jvcAdHoc** [comment]
I merged the tech spec and shared it with Sam. Going to close out this ticket.
