### ISSUE TITLE
Include "Note" to authenticated users that contact info updates in Appoint do not push to Profile

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#88991]
## Background
We have agreed that any contact information updates in Appoint MVP do not push to the Profile.  To make this clear to users, we'll want to add in a "Note" to the contact info screens, to set proper expectations with users.

## Tasks
Update content (based on the designs above) for the following screens. **Content is not the same for all screens**.

[Authenticated **non-Veteran** claimant designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=11012-296381&node-type=frame&t=FNLpcDuz9mWrPnV8-0)
- [x] `/claimant-personal information` 
- [x] `/claimant-contact-phone-email`
- [x] `/claimant-contact-mailing` 

[Authenticated **Veteran** claimant designs](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9725-449126&node-type=frame&t=dViXLnRWDfiMBEdM-11)
- [x] `/veteran-personal-information` 
- [x] `/veteran-contact-phone-email` 
- [x] `/veteran-contact-mailing` 
- [x] `/veteran-identification`
- [x] `/veteran-service`

## Acceptance Criteria
- [ ] Any authenticated user will see a note, setting expectations that updating their information in the Appoint a Rep form-fill experience will not update in the Profile.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/32388

**Comment by holdenhinkle** [comment]
I finished this yesterday and Colin approved it. I just updated the PR description. Waiting for Platform to approve.
