### ISSUE TITLE
Spike | Determine why 686c backup submission failed

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89013]
## Issue Description
_Datadog [alert triggered](https://dsva.slack.com/archives/C063YELFVLM/p1721707353251759) for a failed 686c backup submission due to invalid Veteran name. Veteran was not notified of issue. Team will research root cause of failure and mitigate._

---
## Tasks
- [ ] Determine cause of invalid name error
- [ ] Determine if regex or front end updates are needed

## Acceptance Criteria
- [ ] Failed claim is mitigated
- [ ] Root cause it determined
- [ ] Follow on ticket created
---

**Comment by steele-lm** [comment]
The Veteran has a `'` in their given name, error we got back is
`Names must match the regular expression /\\A[a-zA-Z\\-\\/\\s]{1,50}\\z/`

**Comment by steele-lm** [comment]
Determined that backup submission path was not validating metadata. #75323
