### ISSUE TITLE
[DevOps] File ticket with AWS for increasing IAM quotas.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89011]
## Description
The IAM quota of ten managed policies per role might cramp our style a bit. I should open a ticket to get that addressed.

## Tasks
- [x] [DevOps] Open ticket with VAEC to get quota increased from 10 to 20.

## Acceptance Criteria
- [x] Ticket opened with service desk.
- [ ] Leave open for tracking.

**Comment by ndouglas** [comment]
This is _probably_ done; an AWS person said that they did the thing. I just can't tell because AWS' tools for determining the current value for a service quota are absolutely broken. I'm just going to assume this is done even though I can't verify it without creating 15 more policies and assigning 'em to a role.
