### ISSUE TITLE
[FE] 10-10EZR: Create shortened URL for temporary text campaign

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89015]
## Background

Our Health Eligibility/Enrollment stakeholders have just asked if we can provide a shortened URL for our 10-10EZR form ahead of a text message campaign to Veterans who are in Priority groups 7 or 8, to encourage them to update their health info and provide info/evidence of Toxic Exposure.  This could help them get additional care/higher priority group.  There will be emails and letters sent as well, using the full URL.  A total of 1.9 million Veterans will be contacted as part of this campaign.

After contacting CAIA team, we received a shortened URL and guidance from Mikki Northuis
>I would suggest redirecting people to the unauth/static page instead of the actual form so they are not immediately presented with a sign in modal and instead can understand what is being asked.

- This was agreed upon with Simone Gully via Teams chat on VA Network

>It would save time for your team to implement Heather Justice so you aren't waiting for PW to get it on their sprint plan. The PR review can likely be skipped as well unless your team wants SME assistance.
>We can set the URL to use a 6 digit alpha-numeric code.  For this sake, let's go with www.va.gov/8wrs2a (completely random) to redirect to https://www.va.gov/health-care/update-health-information/

## Tasks
- [x] Redirect URL is requested for www.va.gov/8wrs2a to redirect to the unauth static page https://www.va.gov/health-care/update-health-information/ - [request ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+franecross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+sitewide%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [x] Redirect is tested to ensure the new shortened URL is being directed to the unauth static page for updating health benefits
- [ ] Redirect is validated and signed off by PM
- [ ] Redirect is launched to production

## Acceptance Criteria
- A shortened URL is created for a HEC/VEO text campaign to send PG 7 & 8 Veterans to the 10-10EZR, encouraging them to provide Toxic Exposure details which could qualify them for additional care with VA.
