### ISSUE TITLE
SC | Fix "Value at 'plaintext' failed to satisfy constraint: Member must have length less than or equal to 4096" error

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#89020]
## Value Statement

**_As a_** Veteran

**_I want to_** submit my Supplemental Claim without errors

**_So that_** I feel confident that my form my submitted successfully without data loss

---

## Background Context

We discovered in https://github.com/department-of-veterans-affairs/va.gov-team/issues/73584 that one of the Supplemental Claim errors that caused the `stack level too deep` error in our logs was:

```
Exception occurred while submitting Supplemental Claim: 1 validation error detected: Value at 'plaintext' failed to satisfy constraint: Member must have length less than or equal to 4096
```

After digging around, I found [another team that had run into that error](https://dsva.slack.com/archives/C05Q6411HPF/p1695703347564959?thread_ts=1695677742.715099&cid=C05Q6411HPF) and [their solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66291) was to switch the encryption library they used for their form. We're currently using the one they replaced in our 4142 processing. I spot checked a few of the SC in progress forms that encountered this error and one had a very long `limited_consent` field and the other selected a lot of issues, some with pretty long names under their `provider_facility`, so I'm guessing those _may_ have triggered the validation error.

[This](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/utilities/helpers.rb#L20-L22) is where it's called and since it's a part of our synchronous transaction for submissions, this error has sometimes resulted in incomplete submissions because it leads to a `stack level too deep` error and we don't reach the evidence submission step.

## Acceptance Criteria

- [ ] Reduced number of error logs with the validation error message

## Open questions

- The other team had a model initialized with lockbox `HealthCareApplication::LOCKBOX` in order to use it for their encryption — do we need to set things up in a similar way?

## Tasks

- [ ] Figure out approach for setting up new Lockbox encryption for our 4142 submissions
- [ ] Update the [encryption](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/utilities/helpers.rb#L21) / [decryption](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/decision_review/form4142_submit.rb#L17) in 4142 processing 

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Fix merged in, will continue to monitor logs

**Comment by eileen-coforma** [comment]
Spot checking failures, and making sure fix hasn't broken anything. Will monitor for the next few days.

**Comment by anniebtran** [comment]
A few Veterans haven't tried re-submitting, so I started [a thread](https://dsva.slack.com/archives/CNCEXNXK4/p1722530711561509) with the Contact Center to have them let those Veterans know that a bug was fixed and to ask them to try submitting again. I also added a Veteran to the SC remediation spreadsheet as they may have had data loss / evidence upload issues as a result of running into this error

**Comment by anniebtran** [comment]
Contact center has reached out and will let us know if they hear back from them

**Comment by anniebtran** [comment]
Checked on a few of the users who experienced this error and it seems like they were able to submit successfully in the past few days, so going to go ahead and close this 🎉
