### ISSUE TITLE
[FSR] FE testing `transform_and_submit` endpoint with updates

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#89029]
## Description
Manually test changes to the new `transform_and_submit` FSR endpoint in preparation for launch. A few improvements have been made to the endpoint, so let's do some exhaustive manual testing to see if we can break anything. 

## Tasks
- [x] Test Full FSR maximal & minimal
- [x] Test Streamlined short FSR maximal & minimal
- [x] Test Streamlined long FSR maximal & minimal
- [x] FSR submissions with failed/errored GMT data
- [x] FSR submissions with failed/errored calculated expense data
- [x] FSR submissions with failed/errored calculated income data

## Acceptance criteria

- [x] Testing reveals no major issues
- [ ] (optional) Follow on tickets have been created for any bugs found

## Testing
- [x] Yeah pretty much

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Testing has complete and associated PR for feature flag update has been merged
