### ISSUE TITLE
[Event Bus] Determine on-boarding requirements (ATO, PTA, PIA, ESECC) 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#89036]
## Tasks

- [x] Reach out to Jonathan Kamens 
- [x] ask EventBus about ESECC *

## Acceptance Criteria

- [ ] Determine and document on-boarding requirements for ATO, PTA, PIA
- [ ] Determine and document on-boarding requirements for ESECC
