### ISSUE TITLE
Platform Security Access Reviews - Domo

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#89033]
### Description
OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

As we manage and own 4 different tools/applications, we are responsible for completing the access review for these items. This will likely be broken into 4 separate tasks, to complete iteratively.

- [ACCESS REVIEW - Domo](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3214245889/ACCESS+REVIEW+-+DOMO) - @ChristineYoungZA 

---

### Tasks
- [x] Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.
- [x] Review the default/standard permissions we grant out.
- [x] Identify list of current administrators
- [x] Determine who from the VA should be granted as an administrator.
- [x] Document the results of the review using the below template. 
- [ACCESS REVIEW - Domo](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3214245889/ACCESS+REVIEW+-+DOMO)

---

### Acceptance Criteria

- [x] Necessary information on the access review template is filled out.
- [ ] Additional work needed is created in a separate ticket.

**Comment by johnny-jesensky-adhoc** [comment]
First step -- remove users, connect with Johnny before doing so so communications can be scheduled. 

Identify answers to questions

Questions 

- We need to define what default access is, and includes. 
- Who should serve as the VA admin?

**Comment by ChristineYoungZA** [comment]
- Default access - user added as Participant. Admin's identified below in screenshot. 
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3e647c550291372e2217792c69781929ee63a4b/Image%208-2-24%20at%209.53%E2%80%AFAM.jpeg" alt="Image 8-2-24 at 9.53 AM.jpeg" />

**Comment by ChristineYoungZA** [comment]
Spreadsheet of Deleted Users. https://docs.google.com/spreadsheets/d/1OBrgFUFkkDqjsDDUkoxazZC676_bgjI2O1766PafaPU/edit?gid=1429544807#gid=1429544807

**Comment by johnny-jesensky-adhoc** [comment]
@ChristineYoungZA -- I would connect with Kelly to determine what remaining tasks/work need to be completed for this. If there is follow-up work, please create a separate ticket, and populate with tasks, and a description.

Moving this to _**Done**_ for now.
