### ISSUE TITLE
Platform Security Access Reviews - Google Tag Manager (GTM)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#89031]
### Description
OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

- [ACCESS REVIEW - Google Tag Manager](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3218145281/ACCESS+REVIEW+-+Google+Tag+Manager) - @jestutt 

---

### Tasks
- [ ] ~Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.~
- [x] Review the default/standard permissions we grant out.
- [x] Identify list of current administrators
- [x] Determine who from the VA should be granted as an administrator. -- _Should likely be Ray Wang, our PO._
- [ ] ~Document the results of the review using the below template.~
[ACCESS REVIEW - Google Tag Manager](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3218145281/ACCESS+REVIEW+-+Google+Tag+Manager) 
---

### Acceptance Criteria

- [ ] Necessary information on the access review template is filled out.
- [x] Additional work needed is created in a separate ticket.

**Comment by jestutt** [comment]
The comments #88915 apply here as well: 

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88915#issuecomment-2286151409
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88915#issuecomment-2286166399

**Comment by johnny-jesensky-adhoc** [comment]
Thanks for the solid start on this @jestutt  -- follow-up work will be tracked in #90715, which will be picked up next sprint by @ChristineYoungZA and @Blivaditis.
