### ISSUE TITLE
Platform Security Access Reviews - BigQuery

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#89032]
### Description
OCTO-DE teams are responsible for periodically reviewing access to systems and applications they manage to ensure that only authorized personnel have the required access and permissions.

As we manage and own 4 different tools/applications, we are responsible for completing the access review for these items. This will likely be broken into 4 separate tasks, to complete iteratively.

- [ACCESS REVIEW - BigQuery](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3213885514/ACCESS+REVIEW+-+BigQuery) - @dorseypa1 

---

### Tasks
- [ ] Remove any users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.
- [x] Review the default/standard permissions we grant out.
- [x] Identify list of current administrators
- [x] Determine who from the VA should be granted as an administrator.
- [ ] Document the results of the review using the below template. 
- [ACCESS REVIEW - BigQuery](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3213885514/ACCESS+REVIEW+-+BigQuery)

---

### Acceptance Criteria

- [ ] Necessary information on the access review template is filled out.
- [x] Additional work needed is created in a separate ticket.

**Comment by dorseypa1** [comment]
The security audit for BigQuery is done.  The results of the audit are here https://docs.google.com/spreadsheets/d/1nRwZ24SmBs9cUrRfbVhZssN5JSFbez-XBIw5ij7z22g/edit?gid=823670825#gid=823670825

**Comment by dorseypa1** [comment]
Here is another report of seemingly inactive BigQuery users and the datasets they can access.   https://docs.google.com/spreadsheets/d/1l2FYXsjJre-GAkTHsB3LYDZZ57mRB89P9T2gQpYB2KI/edit?gid=1520006998#gid=1520006998

**Comment by johnny-jesensky-adhoc** [comment]
Thanks @dorseypa1 -- given we want to be extra careful here, so moving the deletion tasks into [this separate ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90745), as well as finalizing the Confluence access review.
