### ISSUE TITLE
[UX + Content] 10-10EZ Toxic Exposure Updates - Gulf War Questions

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#89055]
## Issue Description
Now that research synthesis for 10-10EZ TERA questions is complete and we've identified next steps as team, the UX team will work on branching logic, content updates, and changes to the Gulf War question.

We currently have one question for both Gulf Wars. Following confusion that came up in testing about which Gulf War the question refers to, we will be splitting the Gulf War question up so there's one for the 1990 Gulf War, one for the 2001 Gulf War, and one combined question if a user served during both Gulf Wars. The branching logic that's based on service dates will determine which question the user will see, if any.

- [Figma designs for TERA updates](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)
- [Mural for branching logic user flow updates](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)

---
## Tasks
- [x] Create designs for each Gulf War question
- [x] Collaborate with CAIA on content review for Gulf War questions
- [x] Update user flow in Mural to reflect new Gulf War questions and criteria
- [x] Update Lois and Patrick on team's decisions
- [x] Review with devs

## Acceptance Criteria
- Content updates and branching logic for Gulf War questions have been finalized and updates are ready for dev
---
