### ISSUE TITLE
[UX + Content] 10-10EZ Toxic Exposure Updates - Branching Logic

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#89059]
## Issue Description
Now that research synthesis for 10-10EZ TERA questions is complete and we've identified next steps as team, the UX team will work on the necessary designs and user flows for introducing branching logic in the TERA questions. 

Currently, the 10-10EZ only asks for the user's last branch of service and we will need to collect **all** periods of service in order for the system to determine which TERA questions to show the user. Once we've decided on a flow for this action, we need to prep all materials for developers and review the changes with them.

- [Branching logic user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)
- [Figma designs for TERA updates](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)

---
## Tasks
- [x] Explore design options for asking the user to enter all branches of service, not just last
- [x] Meet with developers to discuss options and find out if this information definitely cannot be pulled from an API
- [x] Update Lois and Patrick on the team's approach
- [x] Update Figma designs with the team's decision
- [x] Update Mural user flow with the team's decision
- [x] Set up a separate section in Figma file that contains just the updates needed for branching logic
- [x] Get approval from HEC on proposed branching logic solution
- [x] Get minimum age we should accommodate that someone may have joined the military so we can use birth date for branching logic

## Acceptance Criteria
- Branching logic materials (Figma file and Mural) for TERA questions have been finalized and updates are ready for dev
---

**Comment by aagosto90** [comment]
[Figma page](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5148-33527) with small content update for branching logic
[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060) with user flow showing updates for phase 1 of branching logic as well as phase 2 (this will just be phase 1)
