### ISSUE TITLE
[CDP] Text updates (from midpoint review)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#89053]
## Description

Small content updates from Midpoint Review feedback [#87821](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87821)

**Overpayment Summary Page**
https://staging.va.gov/manage-va-debt/summary/debt-balances
- Under Diary codes **Benefit and Education Benefit offset** (430, 431) (450, 101, 602, 607, 608, 610, 611, 614, 615, 617)displayed on card, change `We’re offsetting your education benefits each month until your debt is paid` to `We’re reducing your education benefits each month until your debt is paid`
<p></p>

- Under Diary code **Treasury offset** (681, 682) displayed on card, change text `The U.S. Department of the Treasury is offsetting your federal payments until your debt is paid` to `The U.S. Department of the Treasury is reducing your federal payments until your debt is paid`
<p></p>

- Under Diary code **Contact Treasury** (080, 850, 852, 860, 855), change text `Contact the U.S. Department of the Treasury to pay this debt` to `Call the U.S. Department of the Treasury's Debt Management Services at 888-826-3127, 8:30 a.m. to 6:30 p.m. ET.  to pay this debt`

**Overpayment Detail Page**
https://staging.va.gov/manage-va-debt/summary/debt-balances/details/79612301872
- Under **Pay Online**, change `You will need to provide the following details to pay this debt online:` to `You'll need to provide the following details to pay this debt online:`
<p></p>

- Under **Pay Online**, change `Pay on pay.va.gov` to `Pay at pay.va.gov`
<p></p>

- Under **Pay by Mail**, change `United States of America` to `USA`
<p></p>

- Under Diary code **Benefit and Education Benefit offset** (430, 431)(450, 101, 602, 607, 608, 610, 611, 614, 615, 617) displayed on card, change **title** `We’re offsetting your education benefits each month until your debt is paid` to `We’re reducing your education benefits each month until your debt is paid`
<p></p>

- Under Diary code **Treasury offset** (681, 682) displayed on card, change **title** `The U.S. Department of the Treasury is offsetting your federal payments until your debt is paid` to `The U.S. Department of the Treasury is reducing your federal payments until your debt is paid`

## Tasks
- [x] Make updates to Overpayment Detail page
- [x] Make updates to Diary Codes

## Acceptance criteria

- [x] Updates are made to Overpayment Detail page
- [x] Updates are made to Diary Codes

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
