### ISSUE TITLE
Optimize Feature Toggles

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89074]
Our feature toggles endpoint gets 2-3 million requests per day. It spends 80%+ of its request time in redis/cache fetching. This is because it fetches every feature on every request. It isn't cached in any way.

Here's the flame graph in DD:
![Screenshot 2024-07-22 at 17 56 39@2x](https://github.com/user-attachments/assets/64fabdff-02ca-4558-a7d4-f27b2d1b0099)

You can see hundreds have requests to Redis.

## Tasks

- [x] Investigate options for decreasing feature toggle latency
- [x] Implement, test, and deploy a minimal approach to reducing latency
- [x] Monitor feature toggle endpoint for errors and reduced latency
- [ ] ~Open new tickets if further optimization is needed~

## Acceptance Criteria

- [x] Feature toggles endpoint is notably faster (measured in average latency per request)

**Comment by ericboehs** [comment]
Going back before any tuning was done, our p90 for Feature Toggle controller was around 1000ms for an average daytime request (1pm CT):
![Screenshot 2024-07-29 at 09 20 37@2x](https://github.com/user-attachments/assets/48dbdd9b-57bc-4f4a-87ef-a2c1fcabfe71)

Looking at last Thursday (July 25th) after our optimization were in place, our average request is around 60ms:

![Screenshot 2024-07-29 at 09 22 22@2x](https://github.com/user-attachments/assets/d18f8098-6cff-456c-9678-06f474fdcefb)

This is approximiately a 16x performance gain meaning we can use 16x fewer pods/servers.
