### ISSUE TITLE
[UX + Content] 10-10EZR Toxic Exposure Branching Logic with Service Date

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#89072]
## Issue Description
With the research for the 10-10EZ TERA questions completed, the EZ team moved forward with the suggested recommendations per the UX team regarding the branching logic using the Veteran's Service Date. The EZR team will follow those changes closely as the TERA on EZR should have a very similar experience to the EZ.

[10-10 EZ ticket here](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/81910).

- [Slack thread with team follow-up items](https://dsva.slack.com/archives/CMJ2V70UV/p1714151834266889)
- [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy)

---
## Tasks
- [x] Work with the EZ/CG team to match the content updates in Figma
- [x] Work with the EZ/CG team and Devs to determine the branching logic and update it in userflow in Mural.
- [ ] Work with CAIA both asynchronously and in Friday's content sync meeting on outstanding content items
- [x] Demo the changes with the team 
- [ ] Share with the benefits team and sitewide team in case they may want to make the same changes to their TERA questions

## Acceptance Criteria
- Content updates for TERA questions have been finalized and updates are ready for dev

**Comment by IMHieuVo** [comment]
When we initially developed the branching logic, it was based on the Veteran's service period. But the EZ only collects the Vetearn's last branch of service so to effectively do the branching logic, we must collect additional service dates from the Veteran. The team talked about how the tradeoff is not worth it since we would be interesting more complexity into the flow without saving time for the Veterans. 

Alternatively, the team is looking to develop the branching logic based on birthday. While not as  personalized, it still potentially removes one to two questions from flow and it is an easier development.

I will also break this into smaller tickets:
- [Repurpose this ticket and closing it] Branching Logic using service dates
- Open Branching Logic using birthdays
- Gulf War Branching in EZR
- Content Update for TERA
