### ISSUE TITLE
Zenhub Requirements Communications

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#89075]
## Description 
We have noticed that quite a few tickets requesting Zenhub access are missing the requirement for being added to the repo. We would like to educate folks that this is necessary in two ways (see tasks below).

---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 

- [x] [Update request access to tools page on Platform Site with a blurb about this requirement](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GitHub)
- [x] Sync with Alyssa on the steps to add an auto responder
- [x] Adding an automation responder using existing technology in the [Platform Support Responses sheet here](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=0) (column titled AdditionalContextPostText) 
- [x] Link to template where they request access to repo access in both scenarios 
- [x]  Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by AnthonyWFlowers** [comment]
Updated the platform site -Request to access Tools with the following:
"In order to be added to Zenhub you must meet all of the following prerequisites: 

- On the VFS or Platform roster.
- In the Department of Veterans affairs GitHub org. 
- Have a VA email address when making the request. "

**Comment by AnthonyWFlowers** [comment]
Added a Link to VA Github access request
Left statement mentioning its requirement for Zenhub access. 
Tested the support bot- successful

**Comment by alyssagallion** [comment]
Complete. Closing.
