### ISSUE TITLE
Categorize List of Topics for What We Help With Page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#89083]
## Issue Description
Platform Content Team needs to take the [list of topics](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3306520577/Complete+List+of+Content+Team+Topics) we frequently handle and organize them into categories.
**Note:** _OK to add new topics during this exercise._

---
## Tasks
- [x] tag each of the [topics](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3306520577/Complete+List+of+Content+Team+Topics) with a category of your choice on [the Categories page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/edit-v2/3321626694?draftShareId=66396a71-7814-4779-938f-7709ced7b8cb)
- [x] Joe
- [x] Lauren
- [x] Brian
- [x] Jill
- [x] Cheryl
 
## Acceptance Criteria
- [x]Topics will be categorized, all tasks complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
work is complete, closing
