### ISSUE TITLE
Confirm backup path calls metadata validation

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89095]
## Issue Description
_A recent backup path submission failure (#89013) uncovered that that backup submission pathway may not be calling for metadata validation._

---
## Tasks
- [ ] Confirm whether or not the backup submission pathway is calling metadata validation

## Acceptance Criteria
- [ ] Determine if metadata validation is implemented on backup 686c submissions
- [ ] If not, create follow on tickets to fix
---
