### ISSUE TITLE
[DevOps] Create ESECC Request to Open VistA Connection for Lower Environments

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#89107]
## Description
Adequate documentation exists to request connections from `vaec-cie` VPCs to on-premises VA systems, specifically VistA.  Follow documentation in the related ticket to create a BPE worksheet and initiate an in-scope change.

## Tasks
- [x] Determine which network connections need to be opened by reviewing previous BPE spreadsheets
- [x] Consolidate connections into a new BPE spreadsheet
- [x] Initiate an in-scope change and provide an context required by ESECC team

## Acceptance Criteria
- [x] Development Environment VPC
  - [x] In scope ESECC change is created by providing connection information in a BPE worksheet.
- [x] Staging Environment VPC
  - [x] In scope ESECC change is created by providing connection information in a BPE worksheet.

## Relations
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88645
[RFC-008811](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fesecc.va.gov%2Fcgweb%2FMainUI%2FMainFrame.aspx%3FID%3D11803%26moduleName%3DRFC&data=05%7C01%7C%7C17f781f985174487b11808da9b2dc44e%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637992918108148859%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sCLx%2ByH0oS%2FZzeMjQ8dJChhukYI2syIn5DPX1cgk%2F5o%3D&reserved=0)
[RFC-009118](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fesecc.va.gov%2Fcgweb%2FMainUI%2FMainFrame.aspx%3FID%3D12110%26moduleName%3DRFC&data=05%7C01%7C%7Cfa2fc6823ed74461419108db0dce01f2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638118950696343019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Pj%2FnTXf7L2hdFBZzRWfle8Rl6ZF%2FhmjtZb4bo1Ku0a8%3D&reserved=0)

**Comment by olivereri** [comment]
>  Determine which network connections need to be opened by reviewing previous BPE spreadsheets

All previous BPE worksheets are attached to the respective RFC. Just had to review the changes.

Dev implementation SNOW Ticket: **INC34330615**
Dev implementation SNOW Ticket: **INC34330694**
