### ISSUE TITLE
DR | Fix processing & submission of phone extension

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#89102]
## Value Statement

**_As a_** veteran
**_I want_** add my phone extension
**_So that_** they get properly included in submissions

---

## Background Context

Profile data includes a phone number with extension (as `extension`) but when submitted, Lighthouse expects a `phoneNumberExt` value; but this value isn't being consistently processed and submitted

## Outcome, Success Measure, KPI(S), and Tracking Link

- Veterans phone extension is included with their submission

## Acceptance Criteria

- [ ] Process & submit Veteran phone extensions
- [ ] Process & submit additional phone number extensions (e.g. representative phone)

## Open questions

- Add here

## Tasks

- [ ] Fix phone extension processing
- [ ] Update test data
- [ ] Update transformed data
- [ ] Fix submit transformers, if needed
- [ ] Update unit tests
- [ ] Update e2e tests

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Code has been merged and validated to work in staging
