### ISSUE TITLE
[BE] 10-10CG - OAuth2.0: Update Form1010cg::Service to new OAuth 2.0 Authorization Flow in Staging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89109]
## Background
Now that the OAuth2.0 has been implemented in the Dev environment, and manual testing has validated the flow in Postman, we need to validate the vets-api code.
Additional code changes may be needed once additional validation can be done with the Mulesoft team.

### Resources
- [Exploration ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85120) 
- [Initial Development ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86425)
- Helpful info for OAuth 2.0 Client Credential flow with Okta is [here](https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/)

## Tasks
- [x]  Confirm Stating environment is ready for end-to-end testing with Mulesoft
     - This is on hold until after 8/20, as per Ramakrishna Ravirala.  
     - SI (DEV/QA) or DTC-I team (Stage/Prod) will create the application through AnyPoint Exchange for the API which is requested access by the consumer (va.gov)
     - DTC-I team will provide us the auth server URL, Client Id, and Client Secret in an encrypted email.
- [x] Add the credentials above to AWS Parameter Store (if no access create a Platform support ticket)
- [x] Merge https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2996 once the value are in AWS Parameter Store
- [x] Coordinate with Mulesoft team to complete end-to-end testing
- [x] Determine if additional code changes are needed to ensure successful testing
- [x] Validate results with PM for signoff
     - [x] Signoff is documented within the comments of this ticket

## Acceptance Criteria
- End-to-end Staging testing of OAuth2.0 is completed successfully to the satisfaction of CG stakeholders and VA.gov team, and we are ready to begin coordination of production launch

**Comment by coope93** [comment]
Added sms values in aws and updated and merged changes to reference them [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2996)

**Comment by allanto-ah** [comment]
Environment: Staging

E2E testing in slack: [Link](https://dsva.slack.com/archives/C02MJCT59S7/p1727718157038319)

Verified user is able to submit 1010cg form as expected. No regression issues found.

**Comment by allanto-ah** [comment]
It closed for some reason. Re-opened to get PM sign-off before closing.

@hdjustice when you get a chance, can you review and see if we're good to close? Thank you!

**Comment by hdjustice** [comment]
Also validated via Slack channel with Waleed Jaffar (Salesforce/CARMA tech team) that the submission in staging was successful.  Brandon also provided a [Datadog log](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20%40message_content%3A%22%5BForm%2010-10CG%5D%20Submitting%20to%20%27v2%2Fapplication%2F1010CG%2Fsubmit%27%20using%20bearer%20token%22%20-%40named_tags.request_id%3Af8adfb1d-4210-4dfe-9c6c-0568e31935fd%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZJEBcVomfW5IQAAAAAAAAAYAAAAAEFaSkVCYzg5QUFCdkN0RllfYzNtZVFBVAAAACQAAAAAMDE5MjQ0MDktMTk0Zi00ODNiLTg3MzMtNmE4ZTA3YmU3MzA1&fromUser=true&messageDisplay=inline&refresh_mode=sliding&source=monitor_notif&storage=hot&stream_sort=desc&viz=stream&from_ts=1727186947092&to_ts=1727791747092&live=true) for the test

Ok to close and move to the next step of coordinating a production launch
