### ISSUE TITLE
MVP - List of Upstream Services

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89114]
## User Story
As the Managers and Developers of the VA Platform, 
We need to deliver an MVP of the Comprehensive List of Upstream Services, 
So that there is value delivered, given the scope and duration of the original ticket (#67192).

## Issue Description

We need an MVP comprehensive list of the upstream services that Vets API calls out to. There is some existing documentation and diagrams around this, but they're pretty stale and outdated. We should comb through the various sources of truth to determine an up to date list. This includes the fwdproxy, Vets API code, [existing topology graphs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf), [documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations), etc. This task could be a combined effort for Devops and Backend engineers. 

Please refer to this document for [VSP Downstream Map](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf)

Please refer to [this document ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) for External Service Integrations information. 

## OKR
**O2.** Our platforms are the best way to deliver products at VA
**OKR 1:** Our platforms hit the "elite" level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.

Note: Jesse may have some updated info here too.

[This doc](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/2716303371/Interconnected+Systems) may also be helpful

## Tasks
- [ ] Create a list of current upstream services with a broad overview of each service (ticket: #89190)
- [ ] Investigate whether or not all services go through [FWDProxy](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-prod.yml) (ticket: #89193)
- [ ] Establish "Best Practices" around integration with external services (ticket: #89207)
- [ ] Investigate mapping on a high level from Platform to external service environments (ticket: #89212); see [this sample](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Services/#upstream-service-map) from Mobile; can this be leveraged?
- [ ] Building on the above, does the external service env, contain PII (is pre-prod data living in our test suite?) (ticket: #89221)
- [ ] Confirm that the external services in pre-prod doesn't live in the Platform environment (ticket: #89232)
- [ ] Review config for all Platform environments (dev, staging, sandbox, prod) (ticket: #89246)
- [ ] We may be combining efforts with Platform Security, and they have listed [this information](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3393552723/System+Interconnections) as what they are collecting in a priority schedule. 

## Success Metrics
That all MVP tasks are complete as listed above, and documented as required.

## Acceptance Criteria
- [ ] The Platform Product team will be able to deliver accurate information regarding the upstream services used by the VA Platform at a high level, to inform stakeholders on the work. 
- [ ] All documentation is completed for all tickets. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89246
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89190
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89193
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/93600
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89207
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89212
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89221
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89232
```

**Comment by AshleyGuerrant** [comment]
**Epic cleanup:** Currently, work is not in progress on this epic because it has not been identified a roadmap priority by leadership and stakeholders. Moving this epic to the backlog.
