### ISSUE TITLE
[BE] 10-10CG - OAuth2.0: Update engineering documentation to reflect OAuth2.0 flow

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89111]
## Background
Now that the OAuth2.0 has been implemented in Production, we need to create and/or update engineering documentation to include this information.
This may consist of simple diagrams, a short write-up, or other similar documentation that will be a useful resource.

### Resources
- [Exploration ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85120) 
- Development ticket - #86425 
- Helpful info for OAuth 2.0 Client Credential flow with Okta is [here](https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/)

## Tasks
- [x]  Create documentation that best outlines how OAuth2.0 impacts our workflow and codebase
- [x] Review with the team/PM
     - [x] Signoff is documented within the comments of this ticket

## Acceptance Criteria
- Engineering documentation includes the new OAuth2.0 details.

**Comment by hdjustice** [comment]
Reviewed documentation and it captures all connections and flow, including OAuth changes.  Thanks!
