### ISSUE TITLE
[DevOps] Create ESECC Request to Open VistA Connection for Production Environment

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#89110]
## Description
Adequate documentation exists to request connections from `vaec-cie` VPCs to on-premises VA systems, specifically VistA.  Follow documentation in the related ticket to create a BPE worksheet and initiate an in-scope change.

## Tasks
- [x] Determine which network connections need to be opened by reviewing previous BPE spreadsheets
- [x] Consolidate connections into a new BPE spreadsheet
- [x] Initiate an in-scope change and provide an context required by ESECC team

## Acceptance Criteria
- [x] Production Environment VPC
  - [x] In scope ESECC change is created by providing connection information in a BPE worksheet.

## Relations
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88645
[RFC-008812](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fesecc.va.gov%2Fcgweb%2FMainUI%2FMainFrame.aspx%3FID%3D11804%26moduleName%3DRFC&data=05%7C01%7C%7C338ca941f5a84fb88fe708da7af49a16%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637957488211410217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=khuSRTjNd%2FHJ11BSnGY8yGdOpG07qzK4cFl%2FgTyuE3g%3D&reserved=0)
