### ISSUE TITLE
Develop a "vets-api postman" docker image

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#89117]
# Description
Presently, the most promising solution for running a Postman collection that can test the EKS infrastructure starts with the development of a docker image that would run as part of a helm test, or via post-install/upgrade hooks.  

# Tasks

- [x] Create the Dockerfile

# Acceptance Criteria

The created image would need to accomplish the following objectives:
- [x] Image grabs the Postman docker image
- [x] Image uploads the Postman collection file holding the desired tests
- [x] Image launches the Postman image, authenticates as needed, then runs Postman/Newman

**Comment by IGallupSoCo** [comment]
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0llQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--303d856d1a21dbb5d8a9a3d708c53d3b499337de/image.png" alt="image.png" />

**Comment by IGallupSoCo** [comment]
We have a working docker image.  The next steps will likely include an effort to establish the means of passing in a valid address for the collection to be run against.  There will also be a need to ensure that the existing Datadog Agent is able to receive the logs generated by collection test runs.

**Comment by IGallupSoCo** [comment]
https://github.com/department-of-veterans-affairs/vets-api/tree/helm-test-postman-docker-image

My current work can be found at the above branch.

**Comment by JoeTice** [comment]
SPRINT 6 UPDATE: DONE - This ticket was completed on 7/31, but didn't get marked as closed
