### ISSUE TITLE
Enable Toxic Exposure 1.0 New Forms in Production 50% traffic

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#89125]
This ticket allocates Sprint effort for the 50% Toxic Exposure release. It includes the responsibilities of Release Monitoring, which is coordinated by the team. Typically, this is one person who assumes this responsibility for the sprint.

## Tasks
- [ ]  Each Friday before EST COB, share application health metrics for the previous week relative to the release with OCTO, including any baseline metrics that are applicable
- [ ] Share application health metrics as needed ad hoc, as this may sometimes be necessary
- [ ] Make any necessary changes to our monitoring, alerting, and dashboards to accurately monitor the release and respond to any stakeholder questions
- [ ] Perform manual remediation when necessary
- [ ] Update Release Monitoring documentation, or other documentation as needed - be proactive
- [ ] Respond to Slack messages as needed
- [ ] The next business day after the team has incremented to 75%, help gather release metrics 
- [ ] update release increment metrics here: [Monitoring Toxic Exposure Release](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/2024-08-Toxic-Exposure/TE-Monitoring.md)

## Release Monitor Playbook
`<put link here>`

## references
- [Toxic Exposure Submission Troubleshooting](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/TREX/DEBUG/SOP-Toxic-Exposure-Lighthouse-Form526-Submission-Troubleshooting.md)
- [Team 1 526 Submission Remediation Playbook](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/TREX/DEBUG/remediation_playbook.md)

## Metrics
**Baseline**
EVSS submissions from April 1 to July 31
209,770 total submissions (primary, backup, and failure)
99.04% used the primary path (207,772)
0.94% used the backup path (1,959)
0.00019% completely failed (4)

Toxic Exposure
**Toxic Exposure N% incremental rollout (Date 1 - Date 2):**
Lighthouse total submissions: N

**Primary Path Submissions**
N% used the Lighthouse primary path (2,993)

**Backup Path Submissions**
N% used the Lighthouse backup path (68)

**Failures**
N% of Lighthouse submissions failed (14)

**Technical Notes:**
Here, add notes about technical fixes, issues we're experiencing, details for remediating them

**Next Steps:**
Next steps for the release, including details on anything mentioned in Technical Notes

**## Acceptance Criteria**
- [ ] You've done due diligence to make sure that the team has the information they need to continue with the release and ensure OCTO's questions are answered in a timely manner
- [ ] Documentation and processes are updated so that the next Release Monitor's job is easier

## Additional Information
The team should @ mention the Release Monitor so that managing Slack threads is trivial for them. Keeping conversations organized in a thread will help reduce the cognitive load of managing the release.
