### ISSUE TITLE
[DevOps] Implement connection retrying in System Tests

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89135]
## Description
The tests create a flurry of responses, which can lead to throttling. I should implement something that retries failures to avoid flakiness.

## Tasks
- [ ] [DevOps] Research possible solutions.
- [ ] [DevOps] Implement one.
- [ ] [DevOps] Verify current implementation's flakiness.
- [ ] [DevOps] Demonstrate new implementation's effectiveness.

## Acceptance Criteria
- [ ] We have connection retrying in place and it works measurably.

**Comment by ndouglas** [comment]
I increased the spamminess of the tests (running the test suite 5 times in a row on each environment) and failed 4/5 times. I implemented a retry system (well, configured the existing AWS solution), and that passed 5/5 times. I then reverted to running the test once. This seems to be resolved.
