### ISSUE TITLE
MVP Platform Product Tool Audit - Create list and description of each Tool

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89148]
## User Story
As the Managers and Developers of the Platform, 
We need to compile a list and high-level description of the Platform Tools, 
So that there is value delivered against this Epic. 

## Issue Description
_from the Epic:_ 
We need an MVP deliverable for the Platform Product Tools Audit.
Since the initial deployment of various tools and software in our stack back in 2018, there have been continuous development and upgrades in these technologies. However, a methodical review to leverage new feature sets introduced in subsequent releases has been lacking. This gap in our process has potentially led to missed opportunities for enhancing our systems' efficiency, security, and performance.

A prime example of this situation is Redis (ElastiCache), which despite being upgraded, may not fully utilize features introduced in newer versions such as Cluster mode - which would allow for high availability via automatic failover and replication. This scenario could very likely extend to other components of our stack, such as Postgres, among others. Additionally, the absence of historical documentation on decision-making processes further complicates our ability to assess historical decisions.

We are also being asked by @tayism for a 'cheat sheet' list of the tools, services, or processes your team owns or manages so that Oddball and AdHoc knows who to notify when pointed feedback comes in.
Examples include:
-  feature request process
-  ideas for platform
-  feedback in slack; feedback survey; platform surveys; etc

Documentation of the original objective can be found [here](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/77700).

## Tasks
- [ ] Reference [this document](https://docs.google.com/spreadsheets/d/1g07HFgncUu5qP3EfN-PYzbRgnEXWkFZT54-49aauyuY/edit?gid=803968964#gid=803968964) for the list of known tools that are used by the Platform Product team. 
- [ ] Create a high-level description that encompases the who, what and how this tool is used and document it in [this tab](https://docs.google.com/spreadsheets/d/1g07HFgncUu5qP3EfN-PYzbRgnEXWkFZT54-49aauyuY/edit?gid=1050925785#gid=1050925785)
- [ ] Have someone review the list and write-up of the tools and their high-level description. 

## Success Metrics
A comprehensive list and high-level description of the tools is created and shared with Platform leadership and OCTO PO. 

## Acceptance Criteria
- [ ] There is a list of the Platform tools and a high-level description of each tool. 
- [ ] That the list is completed and shared with leadership and the OCTO PO
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
This has been split into 4 new tickets: [89152](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89152), [89540](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89540), [89537](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89537) and [89538](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89538). Closing this holistic ticket.
