### ISSUE TITLE
Collaboration Cycle for Modernized Check-in, Appointments, Travel Claims for Past Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#89153]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1348) for all feedback and findings tickets associated with this Collaboration Cycle initiative. 
 
### VFS team name

Modernized Check-in and Travel Pay

### Product name

Travel Pay (BTSSS on VA.gov)

### Feature name

Travel Claims for Past Appointments

### GitHub label for team

HCE_Checkin 

### GitHub label for product

appointments

### GitHub label for feature

travel-claims-for-past-appts

### Public DSVA Slack channel for VFS team

[#travel-pay](https://dsva.slack.com/archives/C05Q9HH47PS)

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

07-24-2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/vaos-product-outline.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [ ] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.
- Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C022AC2STBM/p1721831450685609)
</details>

### Design Intent
<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [x] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [x] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [x] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.

**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [x] [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722263210448/33062955940eb08d097dbd88a8dc98488ac2ffcc?sender=u37bb983bd3fc3cc00c7d3286)

Not required, but nice to have:
- [x] Wireframes
  - [x] [Appointment detail pages](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2160-2072&t=gZNPMN44lKrP1827-4)
  - [x] [BT claim submission form flow wireframes](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2187-30609&t=gZNPMN44lKrP1827-4)
  - [x] [Wireframes that were used in a completed research study (for reference only; do not review and provide feedback)](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2085-5826&t=Hzx3AGgJ8NStRoUr-4)

Optional:
- [x] Research plan
  - Planned in-person Veteran intercept and BT Office staff interviews at pilot facility due to the need to test the end-to-end experience, including how BT claims are appearing in MS Dynamics staff application.
- [x] Any other artifacts you have so far

**Previous research** 

- **Most relevant research that tested the end-to-end Veteran user flow:** [2023-11 Past Appointments Travel Reimbursement Generative Usability Study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/93738300a77e4cb6236cb225d6b2b871abf85f8f/products/health-care/checkin/research/2023-11%20Past%20Appointments%20Travel%20Reimbursement%20Generative%20Usability%20Study)
- [2024-06-Travel-Claim-Status-Language-Generative-Study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/beneficiary-travel/research/2024-06-Travel-Claim-Status-Language-Generative-Study)
- [2024-04-Reimbursement-Status-Look-and-Feel-Study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/beneficiary-travel/research/2024-04-Reimbursement-Status-Look-and-Feel-Study)
- [2024-01-Status Visibility IA Study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/beneficiary-travel/research/2024-01-Status%20Visibility%20IA%20Study)
- [2022-12 Patient Check In Travel Reimbursement Staff Interviews at Wilkes-Barre](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/2022-12%20Patient%20Check%20In%20Travel%20Reimbursement%20Staff%20Interviews%20at%20Wilkes-Barre)
- [2022-12 Patient Check In Travel Reimbursement Veteran Intercept at Wilkes-Barre](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/2022-12%20Patient%20Check%20In%20Travel%20Reimbursement%20Veteran%20Intercept%20at%20Wilkes-Barre)
- [2022-08 Travel Reimbursement MPV Remote Test](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test)

 
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team: https://dsva.slack.com/archives/GNF5GSD9N/p1722455341706999
- [ ] Meeting date/time: August 8, 2024 at 1.30 PM ET
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/7zBf95zU4cH929X9n79CI_fnQUgj7PtLsh6YIhRtS6Ss_bl5paipx8nkCFV7RF2U.ekhk1CXLuCaNEJFH)
  - Passcode: %&B0D4cB
- Accessibility
  - [x] Feedback added to milestone
  - [ ] No feedback
- Design
  - [x] Feedback added to milestone
  - [ ] No feedback
- IA
  - [x] Feedback added to milestone
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [x] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [x] Design prototype or high-fidelity mockup
  - Specify which pages are included in the review
  - [Simple mileage-only travel reimbursement claim submission for past appointments on VA.gov](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2187-30609&t=2Sdf3ssk1wyVggXL-4). All frames in the section are part of the review.
  - [MVP of a travel reimbursement claim detail page - desktop](https://www.figma.com/design/RJ6OVm0MWD2WprVfO7E3lp/Travel-reimbursement-status-page?node-id=2111-5020&node-type=canvas&t=D3hfS9Ypt07TRZze-0)
). All frames in the section are open for review but the focus is on the claim detail page frame.
  - [Appointment detail page - starting a claim](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2135-3&node-type=canvas&t=VoMc605He9yTznRF-0) 
- [x] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
[User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722263210448/33062955940eb08d097dbd88a8dc98488ac2ffcc?sender=u37bb983bd3fc3cc00c7d3286)
- [x] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) 
  - [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69896). 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
##### Platform actions
- [ ] Slack thread with VFS team:  https://dsva.slack.com/archives/C05UTPZRZFY/p1725566558281959
- [ ] Meeting date/time: Sept 12, 2024 at 3.30 PM ET

##### Platform actions

* Accessibility
  * [x] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [x] No feedback
* IA
  * [ ] Feedback added to milestone
  * [x] No feedback
* [ ] Update this ticket with the Zoom recording
  - [Recording link](https://oddball-io.zoom.us/rec/share/92vuCkSzNCji9ZbMAwMXegqIVkzE9PjDnyE0dILoAymTCWAddmLgZ01i61LInEcH.Ukqv1DdB4Q_DrJhv)
  - Passcode: $M4=iRG.
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [X] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [X] [Link to the Analytics Implementation and QA Request ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1525/views/3?filterQuery=&pane=issue&itemId=96971468&issue=department-of-veterans-affairs%7Cva.gov-team%7C102691)

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below https://github.com/department-of-veterans-affairs/va.gov-team/issues/108031

</details>

### Staging Review

<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [x] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [x] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [X] I confirm the environment is available and test users have been provided.
- [X] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

**Required artifacts**
- [x] **URL(s) to review the product**
  - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
https://staging.va.gov/my-health/appointments/past
  - Select an appointment details and file for a mileage-only submission.

  - List pages, sections of pages, and/or user flows impacted by this work.
- [x] **Drupal or Staging URL for updated primary entry point:** the main way Veterans will access the tool through site navigation (not search): https://staging.va.gov/my-health/appointments/past
  - If the primary entry point is not a page on VA.gov, include information about how to view it. Reach out to `@platform-governance-team-members` on Slack with any questions.
- [X] **Test users and scenarios** (when applicable)
  - Info [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-travel-pay.md)
  - Make sure all user scenarios can be tested, i.e.: in-progress form, submitted form, new form.
- [X] **[Link to Sitewide CAIA intake ticket]**(https://github.com/department-of-veterans-affairs/va.gov-team/issues/69896)
- [X] **Completed accessibility testing artifact:** Ticket [here](https://github.com/orgs/department-of-veterans-affairs/projects/1525/views/3?filterQuery=accessibi&pane=issue&itemId=93561959&issue=department-of-veterans-affairs%7Cva.gov-team%7C100924)
- [x] **QA Artifacts:** artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
  - [X] [Regression test plan](https://dsvavsp.testrail.io/index.php?/plans/view/6458)
  - [X] [Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/6462)
  - [X] [Coverage for References](https://private-user-images.githubusercontent.com/16626560/412608568-61d7de36-d643-4c22-acc3-29c0ef38d7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA0MjIzODQsIm5iZiI6MTc0MDQyMjA4NCwicGF0aCI6Ii8xNjYyNjU2MC80MTI2MDg1NjgtNjFkN2RlMzYtZDY0My00YzIyLWFjYzMtMjljMGVmMzhkN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDE4MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZjY3YjY2OTBhOTk0OTQ1MTk2MTE0NDg5ZDcwZDY0ZDRmNmQ3M2RhYzE0MzAwNzlhYWQ1OTUxZjE2YjRhZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pkNDuPUS7Wlh70Mp2-9heKpLedHcLb9xygbvs82uHD8)
  - [X] Summary (Defects) reports: [there are no known issues at this time](https://dsvavsp.testrail.io/index.php?/plans/view/6462).
  - [X] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/pull/34617)
  - [X] [Code coverage](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/) Ctrl+F "travel pay"
  - [X] [Endpoint monitoring channel](https://dsva.slack.com/archives/C076YMDJRBQ) - we currently do not have an official playbook, but all components are monitored using datadog and in this channel
  - [x] [Incident response playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/e26c1ed2b1e24113aeb93d3c9a896bba29bd4a96/products/health-care/beneficiary-travel/product/incident_response.md?plain=1#L1)
  - [x] [Logging silent failures](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/zero-silent-failures-checklist.md)

**Not required, but nice to have artifacts**
- [ ] **Content source of truth:** link to CAIA Content feedback, such as a content source of truth.
- [ ] **Information Architecture spec:** link to CAIA IA feedback, such as an IA spec.
  
##### Platform actions
- [x] [Slack thread with VFS team
](https://dsva.slack.com/archives/C05Q9HH47PS/p1738339237796549)
- [x] Meeting date/time: 03:30pm - Thursday, February 27, 2025 (Eastern Time - US & Canada)

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link ](https://urldefense.com/v3/__https://oddball-io.zoom.us/rec/share/kBL_ITVrxUmBmREJ0532eQuc2Lx1r695OZBZ5DZVBvwzefGvCQZrJPCtESKQOeaT.smI1Z6r9NIjTOnQC__;!!K2n62VMvFw!HSti6cKpfV-niye0Sf-UMblzJQHyX_C06IXrXPhIekKrIGEdzoAs4DxNbQh_7DzCz1P9f_8-WBBq0mW9moyUT2s%24)
  - Password: `%1wSy7DB`
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
- [ ] [Complete Collaboration Cycle feedback survey](https://ows.io/qs/gb1dfnkl)

</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [X] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [X] Link to the Readiness Review ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/101764

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by aprocik1** [comment]
Note: CAIA offered content recommendations on the early iterations of these designs in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/69896

**Comment by loripusey** [comment]
Per @ayush-chak's conversation with @shiragoodman, we are closing this collab cycle ticket because the remainder of the collab cycle touchpoints will be done as part of the Travel team's ticket.

**Comment by KKitagawa-Bosch** [comment]
Reopening as this seems to have been closed errantly.
