### ISSUE TITLE
526e Missing Information Message - Product Guide update

### ISSUE THREAD

**Issue by juliepedtke** [department-of-veterans-affairs/va.gov-team#89179]
Update product guide to reflect changes to missing info error message. 

Background: This step was missed when update was launched, as the team was still learning about the process of updating product guides. 

- [ ]  Prepare update
- [ ]  Submit ticket
- [ ]  Notify team of approval
```[tasklist]
### Tasks
- [x] STEP 0: chat with Nathan about what was included in this change (was it just the copy change from the design ticket, or something more?) Nathan’s deployment ticket: https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=missing+id&pane=issue&itemId=70516739
- [x] STEP 1: Review all related tickets
- [x] STEP 2: Write up a product guide update
- [x] STEP 3: Internal 2-to-go
- [x] STEP 4: Submit to Contact Center and await approval
```

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/89576
```

**Comment by nnicholas7** [comment]
Original Design ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/89576

**Comment by nnicholas7** [comment]
Saving Ticket information here for reference just in case:
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
There are two error messages that we would like for the Contact Center to review for both the 526 and BDD Product Guides. The first error message is an ITF error message that has been updated to allow Veterans to continue their disability claims online. In the past, Veterans were not able to move forward with their disability benefits claim if the system was unable to determine if they had an existing ITF.  The second error message is a missing information error. We updated this to help Veterans understand exactly what information is missing from their claim.  Veterans could see a message that will prompt them to submit mission information (ie. date of birth, social security number, BIRLS ID (Beneficiary Identification and Records Locator (Sub)System), EDIPI (Electronic Data Interchange Personal Identifier), and Participant ID.) by calling the VA in order to move forward in their application process. 

### Launch Date
- ITF Error Message: Content changes related to the specific missing information were released on May 13, 2024. Changes to the VA hours of operation are forthcoming and will be launched after the engineering team fixes the front end. This launch could take place by the end of the month.
- Missing Information Error: The missing information error was discovered in April 2023 and the solution will be launched after the engineering team fixes the content on the front end. This launch could take place by the end of the month.

### Version Number
526 Product Guide - 4.3
526 BDD Product Guide - 3.3

### Product Guide
DON'T FORGET THE ATTACHMENT

### Product Video
No product video.

### Product Video Transcript
No product transcript.



## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated


## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by nnicholas7** [comment]
Getting a 2 to go on this document. Will also need a screenshot from Sam with the new content to add to the document.

**Comment by AmyPlange** [comment]
@SamStuckey to send updated screenshot for product guide

**Comment by rubensun** [comment]
@nnicholas7 one small adjustment to the copy above, can you specify what the changes to the hours will be?

> ITF Error Message: Content changes related to the specific missing information were released on May 13, 2024. Changes to the VA hours of operation are forthcoming and will be launched after the engineering team fixes the front end. `Currently, VA hours of operation are listed as Monday through Friday, 8a to 9p ET`. This will be revised to state that VA is available 24/7. This launch could take place by the end of the month.

**Comment by nnicholas7** [comment]
Thanks @rubensun ! Change made.

**Comment by rubensun** [comment]
@nnicholas7 I got my wires crossed. Please shift all the info related to changes in hours to the second item.

> - ITF Error Message: Content changes related to the specific missing information were released on May 13, 2024.
> 
> - Missing Information Error: The missing information error was discovered in April 2023 and the solution will be launched after the engineering team fixes the content on the front end. Changes to the VA hours of operation are forthcoming and will be launched after the engineering team fixes the front end. Currently, VA hours of operation are listed as Monday through Friday, 8a to 9p ET. This will be revised to state that VA is available 24/7. This launch could take place by the end of the month.

**Comment by nnicholas7** [comment]
Product Guide Updates- Drafts look good and have been forwarded to VEO for review. There is an anticipated clearance/closure for today. Not sure what that means, but it sounds like it will impact the review time.

**Comment by nnicholas7** [comment]
VEO approved the changes to the product guide. Please see the [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93826#issuecomment-2394119110) for details.
