### ISSUE TITLE
Lock Pre-Filled DOB, name, and ssn

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89180]
## Issue Description
_On the current forms, prefilled name and DOB data can be edited and submitted on VA.gov. This introduces risk for fraud. The VBA has requested that VA.gov not allow users to edit their name or DOB if the data is prefilled. The address can still be edited. See related design ticket: #87401._

## Designs
- [Ch 31 VR&E](https://www.figma.com/design/gqBtkNOCslhEwes7TsBaQy/Ch31-VR%26E--2024-Updates?node-id=1293-9357&t=oVd0pqgjf9MQ3Uzq-1) 
- [COE](https://www.figma.com/design/I40qWfEd6F4CSPfDSMqGeQ/COE-2024-Updates?node-id=355-67393&t=9YaIdj8hvGanPlSu-1)
- [Ch 36 PCPG](https://www.figma.com/design/DEnVQXRrNvwJ3UkKkYYJ1Q/Ch-36-PCPG-2024-Updates?node-id=855-11670&t=s9c0Ux9xktccmhGU-1)

---
## Acceptance Criteria
- [ ] VRE updates implemented
- [ ] COE updates implemented
- [ ] PCPG updates implemented

---
