### ISSUE TITLE
[CST] add re opened disability compensation claims to the list of claims that show 8 step process

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#89189]
## Value Statement
**_As a_** veteran with a re-opened disability compensation claim
**_I want to_** see the 8 step claim process experience in CST
**_So that_** I get a consistent disability claim process experience in CST

---
### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Add EP codes  020RCOMP, 020RN and 020RI to list of claims that will show the 8 step process.
- [ ] Behind claim phase feature toggle
- [ ] Re-opened disability compensation claims show the 8 step process in all places they're supposed to.
