### ISSUE TITLE
[FE] My VA Health Care: Update secondary links to MHV on VA.gov links

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#89198]
## Background
The new MHV on VA.gov tools are ready to go live from My VA. We need to update our secondary/tool links in the Health Care section on My VA to point to the new tool urls (instead of the legacy MHV tools).

## Tasks
- [ ] Update all health care links to point to new MHV on VA.gov health tools (new urls TK)
   - [ ] schedule and manage your appointments
   - [ ] go to your inbox
   - [ ] refill and track your prescriptions
   - [ ] request travel reimbursement
   - [ ] get your VA medical records and lab and test results
- [ ] Make sure analytics tracking is updated (coordinate with PM as needed for this)

## Acceptance Criteria
- [ ] Health care tool links connect to new MHV on VA.gov links

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Confirm links point all point to MHV on VA.gov and not legacy MHV

**Comment by ACParker89** [comment]
@allisonlu @DanielMiller-agile6 do we still need this ticket? 

CC @a6marinos
