### ISSUE TITLE
MVP Upstream Services - Create list and description of each Service

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89190]
## User Story
As the Managers and Developers of the Platform,
We need to compile a list and high-level description of the Upstream Services,
So that there is value delivered against this Epic.

## Issue Description
We need an MVP list of the upstream services that Vets API calls out to. There is some existing documentation and diagrams around this, but they're pretty stale and outdated. We should comb through the various sources of truth to determine an up to date list. This includes the fwdproxy, Vets API code, [existing topology graphs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf), [documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations), etc. This task could be a combined effort for Devops and Backend engineers. 

Please refer to this document for [VSP Downstream Map](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf)

Please refer to [this document ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) for External Service Integrations information. 
We may be combining efforts with Platform Security, and they have listed [this information](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3393552723/System+Interconnections) as what they are collecting in a priority schedule. 

## Tasks
- [x]  Create a list of the Services that are used by the Platform Product team, capture information [here](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations). 
- [x]  Create a high-level description that encompases the who, what and how each Service is used and and how the service relates to the FWDProxy. Document it in [this tab](https://docs.google.com/spreadsheets/d/12Qt19KwWCPBmSeTzx-e_OfErqni_HESb71x_2Gsw3OE/edit?gid=1050925785#gid=1050925785) 
- [x]  Have the list and description of the Services reviewed internally, before delivering to the OCTO PO.

## Success Metrics
A comprehensive list and high-level description of the Upstream Services is created and shared with Platform leadership and OCTO PO.

## Acceptance Criteria
- [x] There is a list of the Platform Upstream Services and a high-level description of each services. 
- [ ] That the list is completed and shared with leadership and the OCTO PO
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rjohnson2011** [comment]
Here is the updated External Services list -> https://docs.google.com/spreadsheets/d/12Qt19KwWCPBmSeTzx-e_OfErqni_HESb71x_2Gsw3OE/edit?gid=1050925785#gid=1050925785
