### ISSUE TITLE
OH-Scheduling  research sessions

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#89204]
## Task Description
Run research sessions

## Notes and References
- Use the [mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719850140543/7d684cc9f91989c4caa1ac5c208879875a4634ec?sender=uc6180068871478c530ab2434) for notes. There is a general note taking area organized by session, and an area for adding notes by screen. Feel free to do whatever works for you. Think of your top 3 takeaways and add them in the session notes by the end of the session.
[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2024-05-oh-scheduling/conversation-guide.md)
[Observer guidelines](https://depo-platform-documentation.scrollhelp.site/research-design/observer-guidelines)

## Acceptance Criteria
- [ ] 10 min before session post in feedback-backchanel
- [ ] Remind observers to [sign up](https://dsva.slack.com/canvas/C06RMRJCLHH)
- [ ] Fill out [task tracker](https://docs.google.com/spreadsheets/d/112rjfJMmtj_S1VeUBdNOgYPVghFwThVDhpvjGt-42Y0/edit?gid=0#gid=0) after each session

## Deliverables
-
