### ISSUE TITLE
Copy of MVP Upstream Services - Confirm Services that interface with FWDProxy

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89207]
## User Story
As the Managers and Developers of the Platform,
We need to review all Upstream Services to confirm their relationship with FWDProxy,
So that the Services can be properly mapped in relation to FWDProxy. 

## Issue Description
We need an MVP list of the upstream services that Vets API calls out to. There is some existing documentation and diagrams around this, but they're pretty stale and outdated. We should comb through the various sources of truth to determine an up to date list. This includes the fwdproxy, Vets API code, [existing topology graphs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf), [documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations), etc. This task could be a combined effort for Devops and Backend engineers. 

Please refer to this document for [VSP Downstream Map](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf)

Please refer to [this document ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) for External Service Integrations information. 

## Tasks
- [ ]  Using this document, [here](https://docs.google.com/spreadsheets/d/12Qt19KwWCPBmSeTzx-e_OfErqni_HESb71x_2Gsw3OE/edit?gid=1050925785#gid=1050925785), identify and capture the relationship with [FWDProxy](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-prod.yml) for each Service that are used by the Platform Product team, capture information in Column E
- [ ]  Have the FWDProxy relationship of the Services reviewed internally, before delivering to the OCTO PO.

## Success Metrics
An understanding of the relationship between FWDProxy and Upstream Services is created and shared with Platform leadership and OCTO PO.

## Acceptance Criteria
- [ ] There is a concrete understanding of the relationship between FWDProxy and Upstream Services and it is documented as current state. 
- [ ] Make any adjustments to Services that should run through FWDProxy (separate tickets).
- [ ] That the list is completed and shared with leadership and the OCTO PO.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jwoodman5** [comment]
Review current documentation to see if there are any gaps.

**Comment by AshleyGuerrant** [comment]
**Refinement notes:** 
Reviewed with the team. This ticket needs to be broken out into separate tickets, because there are multiple requests in the ticket description. What is needed:
- Comprehensive list of all external service integrations (we have documentation but there maybe some gaps)
- Potentially update the VFS-facing document that outlines best practices and standards - [Adding a new External Service Integration](https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration)
