### ISSUE TITLE
[Research][DA] 10-10EZ Registration - Research plan for mvp

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#89214]
## Issue Description
To measure the impact of the mvp registration only path, we need to create a proposal that will outline what and how we will track. It should outline specific to what is quantitative (GA, Domo, Datadog) and if ux recommends a qualitative study too.
- [See an example from another team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2024-05-recent-locations-analytics/research-plan.md)

---
## Tasks
- [x] Confirm with PM/PO/DA what measurement parameters to track - [DA] 10-10EZ - Reg Only MVP: Analytics updates#80832
- [x] Collab and document metrics to track
- [x] Recommend if a qualitative interview study is needed along with quant data
- [x] Review draft with team
- [x] PM to review proposal with PO

## Acceptance Criteria
- There is a research plan documented for the details on success metrics for registration mvp.

---

**Comment by jessicastump** [comment]
write up a proposal to share our approach, what we are doing, the proposed timeframe to monitor traffic, what threshold is considered "enough registration interest" to keep or expand on the process If it is under that threshold, what would we want to do then (remove it? revise it? etc)	(posted via Slack from Heather post PO meeting)

**Comment by jessicastump** [comment]
- Will/should this be on for 100% of users? Or will this be to a lower percentage like 50%/50?
- Some thoughts on numbers below?

> If after month 1, there are about 25-40% of lower SC Veterans interested in registration per data gathered in Datadog/GA tracking, we will also launch a usability study during month 2 and 3 to gather additional insights to prepare for post-mvp anticipated changes and content refinement.
> 
> If after month 1, there is not showing an interest in registration (less than 25% click that option), we will continue to let the experiment run for the 90 days.
> 
> If the 90 month data shows at least a 35% interest in registration, we will explore a fully online registration option for this use case group and start prioritizing other registration use cases next.

Do you think we need UX research plan version too? Example Angela [shared here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2024-05-recent-locations-analytics/research-plan.md)

- The experiment proposal document might be more focused on the product decision on if registration should exist or not, but maybe the research plan is focused on what we need to learn from a design and content perspective to iterate past MVP? - if that is a thing, but be prepared :)

**Comment by jessicastump** [comment]
**Draft research questions** 
1. Is there enough interest in registering for service connected care only?
2. Is there significant redirection - do Veterans frequently go back after seeing the alert to call or download a paper form? 
3. How many of these complete the application (after seeing the registration alert) all they way to the confirmation page?


Contact Center:
1. Is there a significant increase in calls from service connected Veterans asking about registration?
2. If so, do they end up registering them or does the call center staff talk the Veteran into enrolling instead?
3. How do they help the Veteran decide? 


Qual / maybe if registration interest shown in analytics: 
1. Are Veterans clear and confident in their understanding of the difference (between registration and enrollment) and what they will get?
2. What information is missing to help this group of Veterans choose between registration and enrollment?


- maybe we can chat tomorrow before adding to the GitHub doc @hdjustice ?

**Comment by hdjustice** [comment]
@jessicastump - yep, we can find some time and chat about this

**Comment by jessicastump** [comment]
@hdjustice I updated the ticket tasks after we chatted today. I also added the research questions to the github proposal doc so they wouldn't get lost in this ticket! Thoughts on those adjustments? :)

**Comment by hdjustice** [comment]
@jessicastump I think that looks good!  I talked to Luis this morning and showed him the proposal.  We talked about adding some supplemental metrics, so I added this to the doc:

## Supplemental metrics

- If Veterans are exiting the form when they reach the Registration information page, where are they going/what are they doing?
     - Are they leaving VA.gov?
     - Are they searching for a facility?
     - Are they looking for another way/more information to get health care without enrolling?
     - Are they looking for more information on what "Register" means?

**Comment by jessicastump** [comment]
@hdjustice - should this ticket be closed or is anything else needed first?

**Comment by hdjustice** [comment]
I think this is good to close.  We have our plan, I will be reviewing the experiment on the next HEC call.
