### ISSUE TITLE
Pull DORA Metrics Q2 2024

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#89237]
## Description 
_Please include a brief description of the purpose of this ticket._

---

## Definition of Done
_What must be done to officially complete this task?_

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Pull metrics as outline [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2946236529/DORA+Metrics+-+Platform+Support+Team) 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Result for Deploy Count: https://docs.google.com/spreadsheets/d/175Qe5Xfn4jdfMBCy64isUgXmATk397cvfgb6gtzF8HQ/edit?gid=1244951371#gid=1244951371

Results for OOB Deploys: https://docs.google.com/spreadsheets/d/1BmuewD5GQecP5S1FX6EQnEj1grQWaAmUpBWoizupb5s/edit?gid=1258212134#gid=1258212134

Will calculate change failure rate and time to restore in next sprint using this ticket: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/90306

Closing!
