### ISSUE TITLE
Update a11y testing at SR per CMS suggestion

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89247]
## User Story
_"As a team building for Drupal, I want accessibility testing procedures that I can successfully follow, so that the products I build can be tested to the same standards as other VA.gov products."_

Assignee: @briandeconinck 
Peer Reviewer: @it-harrison 

## Description
[CMS suggestions re a11y](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/cms-collab-cycle/collab-cycle-accessibility.md):
> **Mouse-only and touchscreen checks**
> For CMS specifically, since Drupal is not accessible via mobile devices unless they have a GFE phone, we need a secondary way of completing the step of `Using a mobile device, make sure you can use the full functionality of a feature with only one finger to gesture (tapping, swiping, etc.)` by being able to `change the view in developer tools to be mobile`. The test should still be done for those users who want to use GFE tablets or phones to access Drupal.

## Impacted Artifacts
- [Mouse-only and touchscreen](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#mouse-and-touch) section of Preparing for an accessibility staging review.
   - Note: These are in the Advanced section, so not covered by the testing artifact.

## Tasks
- [x] Update the Mouse-only and touchscreen section to account for testing in Drupal.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Mouse-only and touchscreen testing guidance accounts for situations where users cannot access Drupal via mobile device

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
Made some updates

**Comment by briandeconinck** [comment]
@it-harrison Edits made to [Prepare for an accessibility staging review](https://vfs.atlassian.net/wiki/spaces/CC/pages/1909293137/Prepare+for+an+accessibility+staging+review) in Confluence, ready for review. In addition to the changes requested, I tweaked a few other things in the same section to clean it up -- but all minor edits.

**Comment by it-harrison** [comment]
@briandeconinck - looks good!
