### ISSUE TITLE
Audit: Rename DSVA Slack to OCTO Slack

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89248]
## User Story
_"As a user of Platform Website, I want to see OCTO Slack used to reference the workplace in Slack, I know the related information is current."_

## Description
There are currently ~8 pages on Platform Website still using **DSVA Slack** to refer to the VA's workspace. 
The name has been changed to **Office of CTO at VA** some time ago. 
We need to update all references to the workspace.

## Tasks
- [x] Audit Platform Website + Confluence for uses of the term _DSVA Slack_ in **published pages**
- [x] Create a list of the outdated pages
- [x] Joe create separate edit ticket(s) to update the pages

## Acceptance Criteria
- [x] All tasks are complete

**Comment by shiragoodman** [comment]
@jknipes this came up in our refinement - might make more sense for your team to handle this for all instances on PW

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/89248?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by cmarion93** [comment]
Searched both the VA Platform site and corresponding Confluence pages for mentions of DSVA Slack. Here's a spreadsheet of my findings:

https://docs.google.com/spreadsheets/d/1xdlq0Ssg6mBqE5_KSqytiSQLScMk1g1klY2vxKbCPv8/edit?usp=sharing

**Comment by jknipes** [comment]
Moved this ticket into the sprint due to available capacity. Work is complete, closing as _Done_
