### ISSUE TITLE
Copy of MVP Upstream Services - Confirm status of External Services

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89246]
## User Story
As the Managers and Developers of the Platform,
We need to confirm that the external services in pre-prod don't live in the Platform environment 
So that there are no possible errors being introduced in to PROD. 

## Issue Description
We need an MVP list of the upstream services that Vets API calls out to. There is some existing documentation and diagrams around this, but they're pretty stale and outdated. We should comb through the various sources of truth to determine an up to date list. This includes the fwdproxy, Vets API code, [existing topology graphs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf), [documentation](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations), etc. This task could be a combined effort for Devops and Backend engineers. 

Please refer to this document for [VSP Downstream Map](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/VSP%20Topology%20-%20VSP%20Downstream%20Connection%20Map.pdf)

Please refer to [this document ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1889599494/External+Service+Integrations) for External Service Integrations information. 

Please refer to the [Mobile mapping document](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Services/#upstream-service-map), is this something we can replicate and even integrate with (eventually)?

## Tasks
- [ ] Review the External Services environment to see if there is any is pre-production data (PII) living in our test suites
- [ ] Ticket any additional work that will need to be done to remove pre-production data from the Platform's test suites

## Success Metrics
That we have confirmed there is no pre-production data or PII living in Platform test suites. 

## Acceptance Criteria
- [ ] That all test suites have been reviewed to ensure that there is no pre-production data or PII living in Platform test suites.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
