### ISSUE TITLE
Audit DataDog dashboard to show # and %

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89253]
## Issue Description
_OCTO has outlined a [standard set of form analytics](https://dsva.slack.com/archives/C055573C508/p1721768647619279) that need to be collected for each form on VA.gov. Part of the requirement is that each metric show both the number AND % of submissions._

---
## Tasks
- [ ] Audit existing DataDog dashboards to ensure both # and % of submissions are included for:
   - [ ] Submission total failure error (# and % of submissions that are submitted on VA.gov (user receives a successful confirmation message) but never reach the next system
   - [ ] Backup path usage (# and $ of submissions that are submitted on VA.gov (user receives a successful confirmation message) and fail automatic establishment but succeed using a backup path of a document
   - [ ] Separate ticket to track evidence upload submissions and errors is #89252

## Acceptance Criteria
- [ ] All form dashboards include % and # for submission total failure error (COE, VRE, PCPG, ~~Burial~~, 686, 674)
- [ ] All form dashboards include % and # for backup path usage (COE, VRE, PCPG, ~~Burial~~, 686, 674)
---

**Comment by steele-lm** [comment]
This work will be done with #102379
