### ISSUE TITLE
Track evidence upload submission volume and errors

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89252]
## Issue Description
_OCTO has compiled a list of [must-have metrics](https://dsva.slack.com/archives/C055573C508/p1721768647619279) for all VA.gov forms, which now includes:_

- Evidence overall submission volume - Count of unique pieces of evidence submitted with forms, total and per form
- Evidence submission error %: Number and % of submissions that are submitted on Va.gov (user receives a successful confirmation message) but never reach the next system

---
## Tasks
- [ ] Add evidence overall submission volume to existing Datadog dashboards for each form
- [ ] Add evidence submission error % to existing Datadog dashboards for each form

## Acceptance Criteria
- [ ] evidence overall submission volume dashboard for:
   - [ ] COE
   - [ ] VRE
   - [ ] PCPG
   ~~- [ ] Burial~~
   - [ ] 686
   - [ ] 674
- [ ] evidence submission error % dashboard for:
   - [ ] COE
   - [ ] VRE
   - [ ] PCPG
   ~~- [ ] Burial~~
   - [ ] 686
   - [ ] 674
---

**Comment by steele-lm** [comment]
Dupe of #102379
