### ISSUE TITLE
Implement verify sign-in widget on supply reorder page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89275]
### User story
As a Veteran, I want to know I need to be signed in before accessing the supply reorder form accessible from the [supply reorder page](https://va.gov/health-care/order-medical-supplies/).

### Notes
- See notes in https://github.com/department-of-veterans-affairs/va.gov-team/issues/88547 about findings on suggested implementation.
- Text for the alerts can be found at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/sign-in-alerts.md#verify-alert-for-loa1ial1-logingov-and-idme-accounts
- The CTA widget has provided similar alerts for other pages, but the code is cumbersome and hard to maintain. Suggestion is to create a new component/widget for this work.
- Are these alerts currently being used in the landing page? Perhaps we need to use just this component.

Possible tasks:
- 

## Acceptance criteria
- Alerts are designed and styled in Figma.
- Alerts are implemented as React component(s) that can be inserted in static pages.
- Test that alert can be added to a static page and it displays content as expected.
- QA review
- A11y review

```[tasklist]
### Tasks
- [ ] UX: Design and style alerts in Figma
- [ ] Dev: Implement alert(s) as a static page widget
- [ ] Test alert(s) in a static page.
```

**Comment by wesrowe** [comment]
@carlosfelix2 @LynneJohnson224 – FYSA it would be nice to let stakeholders know when this widget gets implemented in prod. That might not happen till after the CAIA steps.

Patrick knows the stakeholders and could probably handle the notification.

**Comment by carlosfelix2** [comment]
[Figma link](https://www.figma.com/design/m992k2m1DSl9MXV9hDytsQ/MHV-Account-Security-%26-Sign-In?node-id=58-3&t=v00gMmVF6P8lrSB8-0) to the alerts.

**Comment by carlosfelix2** [comment]
BLOCKED: Waiting on approval of dompurify. Will submit write up 8/22/24.

**Comment by carlosfelix2** [comment]
dompurify approved

**Comment by allanto-ah** [comment]
As of Sept 20, 2024 CAIA will need to add the widget to the page before we can start testing. There is already a ticket with CAIA to get this done. We will QA once the widget has been added

**Comment by wesrowe** [comment]
Sara checked in with LauraW about this [in slack](https://dsva.slack.com/archives/C0581MN69TJ/p1727977433121009?thread_ts=1727976963.067609&cid=C0581MN69TJ).
This might be [the relevant CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77499).

**Comment by allanto-ah** [comment]
Moving to Blocked until it is ready for us to QA

**Comment by wesrowe** [comment]
Does anyone have the link to the CAIA ticket, or is there a slack thread seeking status?

**Comment by allanto-ah** [comment]
@wesrowe Yeah, here is the [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77499)

**Comment by wesrowe** [comment]
Thanks @allanto-ah, I just pinged CAIA in that ticket.

**Comment by wesrowe** [comment]
Closing. Per refinement 12/11, the ball is back in our court to update the widget. #[94862](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94862) takes over.
