### ISSUE TITLE
[DevOps] Consider moving from `jsonschema` to another validator.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89299]
## Description
Like `ajv`, which is _much_ faster. MUCH. 

https://github.com/ajv-validator/ajv

![Image](https://github.com/user-attachments/assets/26db2481-a17e-401c-9925-8201dcf80852)

## Tasks
- [x] [DevOps] Perform comparative benchmark of `ajv` and `jsonschema`.
- [x] [DevOps] Determine whether the change is worth making.
- [x] [DevOps] If so, transition `system_tests` to use `ajv` instead of `jsonschema`.

## Acceptance Criteria
- [x] Benchmarks performed.
- [x] If worthwhile, migrate `system_tests` to use `ajv`.

**Comment by ndouglas** [comment]
Yeah, AJV is way better. I've already transitioned `system_tests`.

Compare and contrast my simple benchmark as reported in this conversation: https://dsva.slack.com/archives/C02G6AB3ZRS/p1721923779915829?thread_ts=1721923301.482739&cid=C02G6AB3ZRS
