### ISSUE TITLE
Update housing status questions to match paper form

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#89294]
## Issue Description
per @jeana-adhoc :

> There was a recent update to the PDF, changing up a question centered around their housing status. This change was also made to 20-10207 and 20-0995. We worked with the design system to create a pattern for it, that if you all are updating to match the PDF. [This pattern](https://design.va.gov/patterns/ask-users-for/housing-status) should work for ya'll.

---
## Tasks
- [ ] Check business requirements around these questions with OCTO and VBA
- [ ] Review how [housing status pattern](https://design.va.gov/patterns/ask-users-for/housing-status) might work in our form - check with current branching logic and specify any necessary form behavior adjustments
- [ ] Check feasibility with engineers
- [ ] Update mockups
- [ ] Create ticket(s) for implementation

## Acceptance Criteria
- [ ] OCTO and VBA aligned on business requirements
- [ ] Team, including engineers, aligned on a feasible solution
- [ ] Documentation and tickets ready for implementation to begin
