### ISSUE TITLE
Update QA standard to include alert playbook

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89300]
## User Story
As a Governance team member, I want to modify the endpoint monitoring QA standard to ensure VFS teams are providing a playbook in addition to alert monitoring so that there are steps to take if certain endpoints fail.

Assignee: @it-harrison 
Peer Reviewer: @erinrwhite 

## Description
Steve Albers, who is part of the OCTO-DE Benefits crew, wrote [endpoint monitoring guidance](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/endpoint-monitoring.md) that he plans to present to the Engineering COP in their upcoming meeting. In addition to the guidance, he has also written an[ alert playbook template ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/template.md)that, once approved, will become part of the endpoint monitoring process. VFS teams will not only be asked to provide a link to a Datadog dashboard for their product to satisfy Platform QA Standards, but teams will also be asked to provide a playbook that details how to review and address alerts for the product. 

~~Once the guidance and playbook template have been presented to the Engineering COP and then approved,~~ Governance team will need to:

- incorporate the endpoint monitoring doc into VFS-facing guidance (the doc can remain on GitHub)
- make the alert playbook template available to VFS teams via the guidance
- modify the endpoint monitoring standard description to include the playbook

Guidance from @humancompanion-usds via Slack:

> We'd likely just need to amend this:
>      _To satisfy this standard, provide a link to a Datadog dashboard for the product._
> to something like this:
>      _To satisfy this standard, provide a link to a Datadog dashboard, and a playbook that details how to review and address alerts, for the product._

Drafts for all VFS-facing and operational guidance have already been created, so please be sure to refer to the other tickets associated with this initiative.

## Impacted Artifacts

- [QA Collab Cycle Findings for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-feedback%2C+QA%2C+Staging%2C+qa-standards&projects=&template=collab-cycle-qa-findings-staging.md&title=QA+Standards+-+VFS+Team+-+VFS+Product)
- [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) on Platform Website
- [How to complete a QA review for the Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2428010558/How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)

**Note:** All drafts of these pages can be found [here.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83521#issuecomment-2174305478)

## Tasks
- [x] Update the QA Standards page to include a reference/link to the endpoint monitoring doc. Communicate that this page can be viewed for further guidance on endpoint monitoring.
- [x] Modify the endpoint monitoring standard to specify that the alert playbook must be completed and shared with Platform in order for the QA standard to be met. Change the standard from warning to launch-blocking.
- [x] Include a link to the alert playbook template
- [x] Update the QA feedback template to include a check for the alert playbook
- [x] Update the operational guidance to include a check for the alert playbook

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have modified the QA Standard for endpoint monitoring to include the alert playbook
- [x] We have included more detailed guidance to VFS teams on endpoint monitoring (this is the gh page Steve wrote)
- [x] We have escalated the endpoint monitoring standard to launch-blocking

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@humancompanion-usds with the changes to the endpoint monitoring QA standard now requiring VFS teams submit an alert playbook, I think it might also make sense for us to escalate the new standard from warning to launch-blocking. What do you think? Do you agree?

**Comment by it-harrison** [comment]
@erinrwhite the artifacts have been updated:
* [QA Standards draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3237838852/83521+-+Copy+of+QA+standards)
* [How to complete a QA review for the Staging review touchpoint](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3237904385/83521+-+How+to+complete+a+QA+review+for+the+Staging+review+touchpoint)
* [PR to update QA Collab Cycle Findings for Staging](https://github.com/department-of-veterans-affairs/va.gov-team/pull/86108)

**Comment by it-harrison** [comment]
closing - all tasks complete
