### ISSUE TITLE
686 Updates | Compare old vs new 686c payload

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89311]
## Issue Description
_The ensure none of the phase 1 updates to 686c impact RBPS, we need to compare the existing payload sent to BIS to the new payload that will be sent to BIS and consumed by RBPS._

---
## Tasks
- [x] Pull old 686c payload
- [x] Pull new 686c payload
- [x] Compare two and identify the delta between the two

## Acceptance Criteria
- [x] Confirm fields in old and new payloads are identical
---

**Comment by Midge-dev** [comment]
@steele-lm 
#### New Properties in modified 686c-674 From:

- **`veteranContactInformation.internationalPhoneNumber`**:
  - Value: `+44-20-7946-0958`

- **`veteranContactInformation.electronicCorrespondence`**:
  - Value: `true`

- **`agencyOrProgram`**:
  - **`agencyName`**: `9A on the PDF form`
  - **`datePaymentsBegan`**: `2022-02-02`
  - **`typeOfProgramOrBenefit`**: `9B on the PDF form`

- **`currentTermDates.isSchoolAccredited`**:
  - Value: `true`

- **`currentMarriageInformation.type`**:
  - Value: `CIVIL` (changed from `CEREMONIAL`)

#### JSON Payloads
- [686data.json](https://github.com/user-attachments/files/16382960/686data.json)
- [686data_lodash.json](https://github.com/user-attachments/files/16382961/686data_lodash.json)
