### ISSUE TITLE
Investigate PG Query times increasing

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89310]
Since ~July 15th our [DB latency has started to increase](https://vagov.ddog-gov.com/monitors/199084?event_id=7677153036613591709&source=monitor_notif&view=spans&from_ts=1720662770000&to_ts=1721872370000&eval_ts=1721872370000). There's also been a small spike at 2p CT since July 10th:

**July 10th:**
![Screenshot 2024-07-24 at 21 04 18@2x](https://github.com/user-attachments/assets/fa8c29b0-8a1c-43f7-b358-cbef9f78792a)

**Two weeks:**
![Screenshot 2024-07-24 at 21 01 11@2x](https://github.com/user-attachments/assets/97a2d77c-f37e-4b03-b76c-c4f975e50575)

**July 15th:**
![Screenshot 2024-07-24 at 21 02 40@2x](https://github.com/user-attachments/assets/e98729f1-a5ac-4629-9615-85cae74bca07)

- [July 15th: Thread count increased to 12](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/f065a019c3aaae9a0faad281476cf02ceb967e01)
- [July 16h: Redis and PG synced to thread count](https://github.com/department-of-veterans-affairs/vets-api/pull/17560) and [sister PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/6f43471c81404bad5951684389b66933011e6995)

## Tasks

- [x] Investigate the cause of the increase in average Postgres query time

## Acceptance Criteria

- [ ] The cause for the Postgres query times increase is known
- [ ] Issues are created to address resolution

**Comment by ericboehs** [comment]
Starting around the time (July 16th) we increased the connection pool/max threads to 12 (from 5), we started seeing problems with DB latency. As we tuned our nodes and pods down in size, the problems got worse.

<img width="660" alt="image" src="https://github.com/user-attachments/assets/4f40f352-6394-4948-a82f-a47395b12171">

Today we decreased threads and that helped us signficiantly. We're furthering tuning these values down to help with db latency.

<img width="620" alt="image" src="https://github.com/user-attachments/assets/baef4ca7-8ff9-4522-b327-6fbb8ad628c6">

Related: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3021

**Comment by ericboehs** [comment]
It looks like a select few queries our skewing our metrics. Not sure what to conclude from this:

![Screenshot 2024-07-29 at 12 53 21@2x](https://github.com/user-attachments/assets/08b6618d-dfe3-4ff8-a4f8-71eefcb0ab91)

**Comment by ericboehs** [comment]
It appears the form526 queries are sporadic and skewing our metrics. Benefits Disablity is [going to take a look](https://dsva.slack.com/archives/C04KW0B46N5/p1722362597688769?thread_ts=1722282894.292629&cid=C04KW0B46N5). Closing for now.
