### ISSUE TITLE
Edit or rerecord DI short video re: scheduling

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89346]
## User Story
As a Governance team member supporting the Collaboration Cycle, I want to make sure that all video guidance is up to date and accurate so that VFS teams are not following outdated processes. 

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @briandeconinck 

## Description
The current DI short video includes directions on how to schedule your Design Intent touchpoint that are now outdated. The purpose of this ticket is to 1) look into editing the video to see how easily we can remove the audio and possibly edit the video, and 2) if 1 is not possible, then we will rerecord the DI video.

## Impacted Artifacts
[DI touchpoint page and video](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent)

## Tasks
- [x] Determine if we can edit the current DI video.
   - Note: the only copy we have is the video that's currently on the [Platform YouTube channel](https://studio.youtube.com/channel/UCq3F4c_-IIdantkT8hQxS9g/videos/upload?filter=%5B%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D). We no longer have the original recording.
- [ ] If the video is not able to be edited, then rerecord the DI video, updating the scheduling section to reflect what was recently communicated in the MPR short video.
   - The [original ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75014) likely has links to materials used. 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The DI short video is up to date and no longer includes outdated scheduling guidance

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck Confluence and Slides have been updated. Need a new screenshot for the slides, how would I get a blank ticket to grab that info from? 

[Confluence](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2972352514/Restored+for+89346+-+75014+-+Design+Intent+video+script)
[Slides](https://docs.google.com/presentation/d/1wX1cj4tKC1GW4ZHR0_TX9BxwRKR6O67uDUpLG7IDMlI/edit#slide=id.p1)

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch what do you mean "need a new screenshot for the slides"? Screenshot of what?

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch not yet, unless we manually update a ticket. Once @it-harrison runs the script next week to automatically update all of the tickets , then we will have plenty of tickets to choose from. If you don't want to wait, you are free to choose a Collab Cycle Request ticket at random (seriously, it's ok if it's random) and edit the Design Intent section of the ticket to match what is documented in the code block for DI on [this draft page.](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3315073025/88090+-+Allison+Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+2) The only thing that's changing from the old DI guidance to the new DI guidance is that we've dropped the line:

> - [ ]  Notify the Collaboration Cycle team of this event by using the /Collab Cycle Design Intent slash-command in your team channel. Provide information as prompted by the Slack workflow.

Let me know if this is helpful or if you have any other questions.

**Comment by KKitagawa-Bosch** [comment]
Awesome, that makes sense @shiragoodman thank you! 

@briandeconinck that slide is updated and the confluence is updated with the new script, let me know when those look good and I'll record!

**Comment by briandeconinck** [comment]
@KKitagawa-Bosch If we're editing these anyway, I think it makes sense to edit Slide #10 too. The focus of the slide isn't scheduling, but the slash-command is visible on screen. Worth being consistent from 10 to 11.

Script changes look good!

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck Ooh good call, I'll do that and then get the recording started! Thanks!

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck 

Confluence page is updated with the new video: https://vfs.atlassian.net/wiki/spaces/CC/pages/1782153235/Design+Intent

**Comment by KKitagawa-Bosch** [comment]
Should be good to close once you've watched it and confirmed!

**Comment by briandeconinck** [comment]
Looks good! Feel free to close!

**Comment by shiragoodman** [comment]
Sorry, opening this back up. I should have been more clear in the Acceptance Criteria. The DI video that Rebecca recorded is still [what's live](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) on Platform Website. The video is also no longer embedded in the page, and is just a link.

@briandeconinck can you please work with @KKitagawa-Bosch to show them how to embed the video correctly? And please be sure it is the new video with Keegan's voice and not Rebecca's. 

Please let me know if you have any questions.
