### ISSUE TITLE
[FE, QA] 10-10EZ - TERA: Remove UI validation restriction from "Other" freeform text field 

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89343]
## Benefit to the Veteran
By allowing the comma, period, question mark and exclamation point to the Toxic Exposure "Other" freeform text field, Veterans will be able to clearly communicate the exposures that they want to identify but did not see listed in other pages.

## Background
At first launch for Toxic Exposure questions, we knew that the Enrollment System would not be able to accept any special characters typed in the "Other" freeform text field.  We could only allow letters, numbers and spaces.  We were advised that the special characters - comma, period, question mark and exclamation point (. ? ! ,)- would be added in a future release.

We have now been informed by the VES tech team that the code is ready to accept the agreed upon special characters for the "other toxic exposures" field.  We need to remove the UI validation on the freeform field and test with the VES team/ 

## Tasks
- [x] Verify that the field is accepting the following characters without any errors: . ? ! , 
- [x] Validate that these special characters can be entered and an application submitted successfully
- [x] Verify with Ramya Venkataraman (VES team) that test has been submitted and received successfully
     - Test results/response from Ramya is copied in comments below
- [x] Validate with PM that special characters are now allowed with application submission
     - PM signoff documented in comment below

## Acceptance criteria
- The freeform "Other" field can allow the four identified special characters and an application is submitted from VA.gov and received by Enrollment system successfully.

**Comment by hdjustice** [comment]
E-2-E Testing completed with Ramya (VES) and [successful results](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZ-EZR-special-characters-E2E.md) were captured.  This work is approved and ready to go live today in production.

**Comment by hdjustice** [comment]
@Mitch-A6 could you add an estimate to this ticket?
