### ISSUE TITLE
Transition GTM Triggered Events to GA4 -- Continued Work

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#89345]
### Description

Not all tracking events are triggered by dataLayer event pushes (e.g. web/form components and custom events). Others are solely created in GTM, mostly using HTML and CSS as triggers. These events need to be transitioned.  

_This is part of an ongoing task, with roughly 40% still to complete._ 

---

### Tasks

- [ ] continue review GTM to identify these events
- [ ] continue implementing the identified events for GA4

### Acceptance Criteria

- [ ] identified events have been implemented for GA4

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- pulling this one out of the current sprint to allow adequate bandwidth the GA4 audit we've been asked to prioritize, https://github.com/department-of-veterans-affairs/va.gov-team/issues/90164. Will likely try to pull this one back in, depending on how quickly we wrap up the audit.

FYI @jwoodman5, @raywangoctova

**Comment by AdamOye** [comment]
Identified as a ticket for deletion. Closed

**Comment by jwoodman5** [comment]
@AdamOye Why was this identified for deletion?
