### ISSUE TITLE
Implement imposter component cards in SR Dashboard

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89358]
## User Story
As an OCTO PO, I want to know trends in imposter components within the Collab Cycle so that I have data and metrics to report to my leadership.

Assignee: @it-harrison @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
Governance team and their PO have approved the new cards to be added to the[ Staging Review Dashboard.](https://va-gov.domo.com/page/1340527018?userId=1646566899) The purpose of this ticket is to implement the card changes related to the imposter components. See [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720191529751/a3eda30d1910afbad7680620fc08910449197d7c?sender=630af6fa-cd3e-4db3-bcfa-19e6575ed63f) for details. 

## Tasks
- [x] Create a new section in the existing SR Dashboard for imposter components. Structure it the same way so that it starts with a questions.
   - Shira's 2 cents - since there are technically 4 cards we're trying to include in 1 section, maybe the question can be generic. "What trends are we seeing in imposter components found at Staging Review?" or something like that. I think it might start to look cluttered/messy and be hard to read if we ask a question for each new card.
- [x] Build out the 3 new cards
   - [x] Count of imposter components by quarter
   - [x] Most common imposter components
   - [x] Count of experience standard for screen reader modality issues
- [x] Validate that the data is correct by cross comparing with GitHub

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have added new cards to the SR Dashboard for:
   - Count of imposter components by quarter
   - Most common imposter components
   - Count of experience standard for screen reader modality issues
- [x] We have validated that the card data is accurate

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
@it-harrison the new cards have been added to the Domo dashboard and need the right data flow.

**Comment by shiragoodman** [comment]
@allison0034 @it-harrison - i updated this ticket to add the screen reader card. please lmk if you have any questions.

**Comment by allison0034** [comment]
@KKitagawa-Bosch this is ready for your review.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 one small question: for "count of tickets with imposter components v. tickets with components" is the "tickets with components" inclusive of those with imposter components? Or those that include non-imposter components? Might be worth clarifying with something like "count of tickets with imposter components v. all tickets with components of any type" or something along those lines. 

Otherwise, looks great!

**Comment by allison0034** [comment]
@KKitagawa-Bosch good question. If you look to the right there is a key. The chart shows all tickets and then breaks it down by tickets with imposter components vs VA components. 

@it-harrison can we change the key to "All tickets" Imposter components" and "VA components"?

**Comment by allison0034** [comment]
@KKitagawa-Bosch take a look and see if that is more clear.

**Comment by KKitagawa-Bosch** [comment]
I think that's perfect! Everything looks good to me!
