### ISSUE TITLE
Investigate pods being terminated before new pods are ready

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89365]
During a deploy, it is our expectation that old pods will be shut down a few at a time while new ones are spun up. Once the new ones are ready to serve traffic, Kubernetes will then shut down more pods until all pods in the replica sets are updated.

Now that we have our EKS cluster's min ASG set below our desired nodes, our prod cluster scales up and down as pods scale up and down. This means that during deploys, more nodes are provisioned and our deploy takes a little longer while we wait for the new nodes to be available to schedule our new pods.

What seems to be happening is that too many old pods are being terminated before new pods can become available. This causes a tremendous backlog on Vets API and things become very slow/unresponsive.

## Tasks 

- [ ] Investigate if pods are being terminated early

## Acceptance Criteria

- [ ] Pod termination is understood better
- [ ] Issues are created to address resolution of pod termination issues

## Related

https://github.com/department-of-veterans-affairs/va.gov-team/issues/89310

**Comment by ericboehs** [comment]
Since it's a Friday tomorrow. We're thinking we'll just try increasing our min ASG nodes (maybe to 20?) to see if it smoothes things out.

We may want to try modifying `bin/is_ready` next week to account for total pods desired instead of using [a fixed number of 3](https://github.com/department-of-veterans-affairs/vets-api/blob/2499c41fcf3081ee89190858f4852256f74628ed/bin/is_ready#L67) for `MIN_READY_PODS`.

**Comment by ericboehs** [comment]
4 threads made our puma backlog go up. More workers may have helped but we went ahead and moved our ASG min back to 20 and did a deploy. It went really smooth. Query times are good too.

Perhaps our cpu request/limits are too low since over provisioning our ASG to 20 makes 8 threads/worker work fine.

**Comment by ericboehs** [comment]
This issue was experienced during deployments when we had our node autoscaler active (min nodes at 4). Due to pact, we never had our min nodes at 4 so I was unable to test this in Sprint 7.

Sprint 8 will be after the PACT traffic surge so we can decrease min nodes to troubleshoot this again.

**Comment by ericboehs** [comment]
This issue did not come back as we scaled down our nodes (two weeks ago). Closing.
