### ISSUE TITLE
Define Test Users for Appoint a Rep MVP

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#89370]
## Background
We are starting to QA Appoint MVP pages/chapters that have conditional designs and content based on specific user attributes.  This ticket is to start defining test users for all scenarios, to support ongoing QA as well as the future goal of a comprehensive QA prior to Staging Review.

## Tasks
- [x] Create a document in Github to store our Appoint test users
- [x] Find a LOA3 test user with a complete Profile
~- [ ] Find a LOA3 test user with an incomplete Profile~ Not a realistic scenario
- [x] Find a LOA1 test user

## Acceptance Criteria
- [x] There is a documented resource in the `va.gov-team-sensitive` repo that outlines the test users relevant to Appoint a Rep MVP.

**Comment by oddball-lindsay** [comment]
Defined test users for:

- LOA1 (no profile info)
- LOA3, complete profile
- LOA3, no mobile/work phone number
- LOA3, no home/work phone number
- LOA3, no phone number
- LOA3, no email

Still need to find LOA3, no address.  Will upload the file w test user info to GH after that.

**Comment by oddball-lindsay** [comment]
Would also be good to capture test users for:

- Claims agents or attorney as POA
- VSO as POA
- Non Veteran claimant

**Comment by oddball-lindsay** [comment]
vets.gov.user+224@gmail.com is the test user the AE Design Patterns Team is using to test pre-fill capabilities on the 1010EZR and 10182 forms

**Comment by oddball-lindsay** [comment]
Maybe LOA3 users require an address? Struggling to find one that doesn't have an address. Asked the larger team for help in Slack: https://dsva.slack.com/archives/C909ZG2BB/p1726075009470219

**Comment by oddball-lindsay** [comment]
Turns out LOA3 users without an address is not a realistic scenario.

Technically, address isn't required by MPI so the concept exists in theory. But in reality, ID.me and Login.gov will require the user to input an address when verifying their identity and becoming an LOA3 user.

Calling this ticket done and test users are ready for future QA.
