### ISSUE TITLE
Update Appoint MVP content

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#89371]
## Background
We just had a very in-depth conversation with A about content for Appoint.  This was based on the research for Appoint v2, but it sounded like there are some opportunities to make the MVP content more clear for users.  

The MVP is currently in development, so we need to tread carefully when updating content!  We have an opportunity to update content for any screens that have not yet been developed.  For screens that have already been developed and the related ticket has been closed (or is close and In Review), I would prefer to minimize scope changes and save any content updates for v2 unless absolutely critical.  **Please stay close with Lindsay to understand what screens are okay to update the MVP content for!**  This will be a bit of a moving target.

## Tasks
- [ ] Confirm with Lindsay which screens we are able to adjust MVP content for
- [ ] Update MVP Figma designs with the updated content 
- [ ] Confirm design updates with Lindsay, so she can ensure updates are reflected in future dev tickets
 
## Acceptance Criteria
- [ ] MVP content has been updated to improve user comprehension, but only for screens that have yet to be developed (to minimize scope creep for this MVP).

**Comment by mtri** [comment]
Bringing in the following:
- [Content recommended for MVP PDF Form Filler in the content doc](https://docs.google.com/document/d/11HRzNaHKPnY51bkroirCcoNeIdYbbGxo6XC9PAK1Kyw/edit#heading=h.paumgwubj4zl)
- VSO search
- Contact content
- Moved Contact before VSO selection

**Comment by mtri** [comment]
[Mobile / Authenticated](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=1475-217022&t=zG98f6tg7s9VyPSI-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A217022)\
[Desktop / Authenticated](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=1475-216659&t=zG98f6tg7s9VyPSI-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A216659&show-proto-sidebar=1)\
[Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-216659&t=zG98f6tg7s9VyPSI-11)

[Mobile / Unauthenticated](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=455%3A76935&node-id=3848-261853&t=zG98f6tg7s9VyPSI-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=456%3A171489)\
     [Step 0 (Since unauth intro links to auth right now)](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=455%3A76935&node-id=455-150293&t=zG98f6tg7s9VyPSI-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=456%3A171489)\
[Desktop / Unauthenticated](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=455%3A76935&node-id=455-148802&t=zG98f6tg7s9VyPSI-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=455%3A148692)\
    [Step 0 (Since unauth intro links to auth right now)](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=455%3A76935&node-id=455-148554&t=zG98f6tg7s9VyPSI-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=455%3A148692)\
[Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-148802&t=zG98f6tg7s9VyPSI-11)

[Updated Annotations](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2194-153573&mode=design&t=J2lhbyovmo9Ntv4V-11)

TODO: Design empty state for search results.

**Comment by mtri** [comment]
[Search result empty state](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=8996-281931&t=q2RgXOd9qtkB7vL2-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1)

Waiting on conclusion to "See all representatives" vs. "Check all representatives" content conversation once Janelle is back

**Comment by oddball-lindsay** [comment]
Let's move forward with "Check all representatives" for the additional component, and test with Veterans.

**Comment by mtri** [comment]
Check all representatives dropdown added with copy to test
