### ISSUE TITLE
[BE] 10-10CG - BUG: Investigate duplicate submission issue discovered by Mulesoft team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89378]
## Background
An email was received from the CG stakeholder/tech team that there were 3 duplicate submissions received on 3 separate dates (6/25, 6/26, 7/12).  The CG team would like the 10-10 team to review and determine if the duplicate submissions originated from VA.gov when the forms were submitted online. 
This may help to uncover the root cause for the duplications.

### Reference info (Log .xlsx file linked in comments within this ticket)
- Message from Ramesh
     - The reason we are looking into this is, based on the logs we believe [va.gov](http://va.gov/) is submitting same payload twice sometimes, so wanted to investigate this further and understand why we are seeing this behavior.

## Tasks
- [ ] Review email and duplicate submission details sent by CG team
- [ ] Determine if the provided information can be found and correlated to any details we may have on VA.gov side
- [ ] If yes, determine if duplicate submissions were sent from VA.gov side to Mulesoft
- [ ] If no, determine if there is any logging change we can make to help investigate these types of issues in the future
- [ ] Document findings (either way) and discuss with team/PM on next steps

## Acceptance Criteria
- We have determined whether we can identify the submission details on VA.gov side and can provide the CG team with an update of our findings.

**Comment by hdjustice** [comment]
[Carma_Duplicates.xlsx](https://github.com/user-attachments/files/16393004/Carma_Duplicates.xlsx)

**Comment by coope93** [comment]
I found an SSL error that occurred around the same time as the most recent duplicate submission.  https://vagov.ddog-gov.com/apm/traces?agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40_span.count%2C%40_duration.by_service&colsTraces=service%2Cresource_name%2C%40duration%2C%40_span.count%2C%40_duration.by_service&destG=core_network.server.auto_grouping_tags&fromUser=false&graphType=flamegraph&historicalData=true&netviz=sent_vol%3A%3A%2Ctcp_r_pct%3A%3A%2Crtt%3A%3A&query_a=%40_top_level%3A1%20env%3Aeks-prod%20resource_name%3A%22Form1010cg%3A%3ASubmissionJob%22%20-status%3Aok&query_translation_version=v0&saved-view-id=1609&shouldShowLegend=true&sort=time&spanID=2666070901931074238&spanType=service-entry&spanViewType=metadata&srcG=core_network.client.auto_grouping_tags&target-span=a&timeHint=1720821476770&trace=1340479063989965401&traceID=1340479063989965401&traceQuery=a&view=traces&viz=stream&start=1720756800000&end=1720843140000&paused=true

**Comment by coope93** [comment]
Another SSL Error around another duplicate submission: https://vagov.ddog-gov.com/apm/trace/4281198912979467811?colorBy=service&env=eks-prod&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=3267447019145779648&spanViewType=logs&timeHint=1721679642834.141&view=spans

**Comment by coope93** [comment]
Added additional logging that should be helpful in correlating any future duplicates. We have requested that the mulesoft team notify us of any further duplicates so we can continue to look into them, but for now my best guess is it is related to those SSL errors.

**Comment by hdjustice** [comment]
FYI - this may come up on this Friday's call with CG team
