### ISSUE TITLE
[DevOps] Remove mentions of SSN4 from LoROTA.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89381]
## Description
There's a lot of code, tests, example data, etc in LoROTA that make it appear as though we pass SSN4 around. This is no longer the case. We should remove these references, simplify the resulting code, and update documentation.

Target `master` branch and cherrypick to `main`.

## Tasks
- [ ] [DevOps] Remove references to SSN4 within additionalValidation-related functions.
- [ ] [DevOps] Remove references to SSN4 within tests and example data.
- [ ] [DevOps] Remove references to SSN4 in documentation.

## Acceptance Criteria
- [ ] "SSN4" is not a thing anymore in LoROTA in `master` or `main` branches.
- [ ] Tests continue to pass.
