### ISSUE TITLE
[DevOps] Store LoROTA secret in environment variable rather than retrieving from AWS on-the-fly.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89383]
## Description
According to [this ticket](https://app.slack.com/client/T03FECE8V/C02U11L00TF), this appears to be a design oversight and not an explicit choice.

Slack thread: https://dsva.slack.com/archives/C02U11L00TF/p1660574846190819

> This also seems like a super easy place to save latency. We could put the secret in environment variables like we do in CHIP, or just pull the value once and cache it in-memory

That refers to this:

![Screenshot 2024-07-26 at 10 32 49 AM](https://github.com/user-attachments/assets/4c5e89a9-d551-4dd5-b305-384d00b109e1)

Which indeed is unnecessary and should be a small amount of work. I was wondering why this was retrieved in this way...

## Tasks
- [ ] [DevOps] Remove `LOROTA_SECRET_NAME` environment variable.
- [ ] [DevOps] Create `LOROTA_SECRET` environment variable.
- [ ] [DevOps] Replace references to the former and related logic with references to the latter.

## Acceptance Criteria
- [ ] LoROTA manages its secret directly in the environment rather than retrieving it from Secrets Manager.

**Comment by ndouglas** [comment]
Duplicate of #89695.
