### ISSUE TITLE
[CAIA Intake] <GOVCIO>: <Update VA Form 22-1995 to integrate VA Form 22-5495>

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#89382]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: VFEP / VEBT
- **OCTO product owner:** `Education`
- **Product name:** `VA Form 22-1995`
- **Product manager:**  `Darla van Nieukerk /  Kara Ciprich`
- **Slack channel:** `govcio-vfep-team`
- **Dedicated content writer on your team (if you have one):** `Garry Forbes`
- **Dedicated a11y specialist on your team (if you have one):** `Insert name and/or GH handle`
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

Education has requested that questions from VA form 22-5495 be placed into the VA form 22-1995 making the 1995 form all-inclusive for requests related to:
- You’re a Veteran or service member, or
- You’re a dependent of a Veteran or service member using transferred Post-9/11 GI Bill benefits, or
- spouse or dependent is applying for educational benefits under Chapter 35 Survivors' and Dependents' Education Assistance (DEA), or
- Chapter 33 Fry Scholarship

####  Change your GI Bill School or Program
Under the header of How do I request changes to my GI Bill or other VA education benefits? - Survivors’ and Dependents’ Educational Assistance (DEA) or Fry Scholarship:
- Will need the text of "VA Form 22-5495" to be updated to "VA Form 22-1995". 
- Text in Link to be updated from "Complete VA Form 22-5495 online" to be updated to "Complete VA Form 22-1995 online"
- Link changed from "https://www.va.gov/education/apply-for-education-benefits/application/5495/introduction" to "https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction"

#### About VA Form 22-1995
- add the text "Family member benefits" to the Related to section:  "Related to: Education and training, Service member benefits, Family member benefits"
- Change the date from "July 2022" to "August 2024" for the Form last updated:
- Update the "Use VA Form 22-1995 to request changes to your education benefits if:" section to:
- - Use VA Form 22-1995 to request changes to your education benefits if:
You’re a Veteran or service member, or
You’re a dependent of a Veteran or service member using transferred Post-9/11 GI Bill benefits, or
If you're using one of these programs:
You're using Survivors’ and Dependents’ Educational Assistance (DEA) program, or
You're using Fry Scholarship
Note: As of [date], VA Form-22-1995 incorporates elements deprecated from 22-5495 to better serve Veterans and their families.

Due to the merger of forms, we are requesting static page updates to the About VA Form 22-1995 and the removal of the About VA Form 22-5495 page. The URL for the About 5495 page will be redirected to the About 1995 page. 

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

The goal set was to release the updated VA form 22-1995 on Aug 6th, 2024. However, we are aware that this date might not be feasible.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [ ] No
- [x] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

We have been working on combining the 1995 and 5495 for a few sprints based on tasks given to our team by our EDU/Stakeholders. We are ready to release the updated 1995 and take down the 5495. Before we release the updates we want to make sure we have URL redirects in place and content changes made to eliminate broken links and misinformation.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [x]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `Enter dates`
- **What is the name of your engineer who will build the React widget?** `Name`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [x] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Supporting artifact<name>]
- Artifacts that I have are in the form of JIRA tickets.

## Next steps
- [ ] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [x] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90371
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/90372
```

**Comment by jsimonVA** [comment]
Looking through the ticket, It looks like I left out a content change that will need to be made. I have added the details into the body of the ticket. This is for the page Change your GI Bill School or Program.

**Comment by aprocik1** [comment]
@jsimonVA, thanks for your patience. We're handing this work from Laura Willwerth to me, so I'll be your content point of contact moving forward.

I've reviewed this ticket and all the relevant Slack conversations. Can you review the updates I've synthesized below and confirm that they accurately represent this work? Can you also review my question about updating the form intro page?

## Page 1: [About VA Form 22-5495](https://www.va.gov/find-forms/about-form-22-5495/)

- Archive in Drupal
- Redirect to Form 22-1995

## Page 2: [About VA Form 22-1995](https://www.va.gov/find-forms/about-form-22-1995/)

- Add alert or note about Form 22-5495
- Update these sections:
  - "Related to:"
  - "When to use this form"

## Page 3: [Change your education benefits](https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=false)

- Add intro that mentions Form 22-5495, instead of alert or note

**Note:** Cinda Quattrini reviewed this page and recommended that we correct these two inaccuracies:

- Refer to this as a "request," instead of an "application"
- Clarify that not everyone receives a COE, which is mentioned in step 4
 
We should also update the content about VSOs in step 1 to include the new page related to finding and appointing accredited representatives. And we should make these formatting updates:
 - Align process list with [VADS pattern](https://design.va.gov/templates/forms/introduction#process-list-for-applications)
 - Move sign in widget below process list

**Question:** Is a full update to this page within your scope of work? We'd like to make all the updates listed above at once.

## Page 4: [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/)

- Remove mentions of Form 22-5495
- Merge these sections to follow the "How do I apply?" pattern on [this page](https://www.va.gov/pension/how-to-apply/):
  - How do I request changes to my GI Bill or other VA education benefits?
  - Are there other ways to submit my request?

**Comment by jsimonVA** [comment]
@aprocik1 thanks for taking this task on. I looked over everything in your comments and it looks like we are on the same page with the changes. 

For the 1995 Intro page, we have a change that will go out with added verbiage to address the new additions to the 1995. 

I will confirm with Cinda in one of our weekly meetings on the inaccuracies mentioned above.

We wont be able to make all these changes at once since we have several of these education forms and we want to maintain uniformity throughout all the forms (for instance, if we change the placement of the sign in, we should do that with all the intro page forms). With that said I will note your comments in our backlog and address them as soon as we can.

**Comment by aprocik1** [comment]
@jsimonVA, thanks for your review. I'll create two content task tickets for this work. 

When should I complete task ticket 1? This is dependent on when you plan to deprecate the old Form 22-5495 and launch the new Form 22-1995. Also, can you share the updated Form 22-1995 intro page you referenced?

When do you expect we'll start working on task ticket 2? I want to make sure we're prepared for this on our end.

## Task ticket 1
In the short term, we'll update these pages:

- [About VA Form 22-5495](https://www.va.gov/find-forms/about-form-22-5495/)
- [About VA Form 22-1995](https://www.va.gov/find-forms/about-form-22-1995/)
- [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/)

And we'll update the [Change your education benefits](https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=false) page with these changes:

- Add content about new additions to Form 22-1995
- Correct any inaccuracies identified by Cinda

## Task ticket 2
In the long term, we'll update the [Change your education benefits](https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=false) page with these changes:

- Align process list with [VADS pattern](https://design.va.gov/templates/forms/introduction#process-list-for-applications)
- Move sign in widget below process list
- Update accredited representative content

**Comment by jsimonVA** [comment]
@aprocik1 Task 1 can be completed as soon as you can. We are ready to remove the 5495 as early as Monday the 12th of Aug.

Here is a link to [staging](https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=true) that contains updates to the intro page for the 1995, in prep for the 5495/1995 merge. 

We have added the items in Task 2 to our backlog. We just kicked off a new sprint today and might be able to work it in, but it might need to wait until the following sprint.

**Comment by aprocik1** [comment]
@jsimonVA, please review my content recommendations below. After we finalize these pages, we can align on a timeline for publishing them on VA.gov. My copyeditor will archive page 1 and publish pages 2 and 4. Your team will need to publish the updates to page 3.

## Page 1: [About VA Form 22-5495](https://www.va.gov/find-forms/about-form-22-5495/)

Before we archive this page, we'll need to confirm that the redirect is working properly. Have you opened a redirect ticket?

## Page 2: [About VA Form 22-1995](https://www.va.gov/find-forms/about-form-22-1995/)

Here's the link to the [Drupal preview](http://preview-prod.vfs.va.gov/preview?nodeId=5977). Note: You need to be on the VA network to access the preview, and links on preview pages don't work.

The "form last updated" content will automatically update when the PDF is updated in the forms database. My team doesn't control that content or process.

## Page 3: [Change your education benefits](https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=false)

Here's my content recommendation for the intro in [staging](https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=true):
> If you're a Veteran or dependent, you can use this form to request changes to your GI Bill school, program, or other VA education benefits.
> 
> **Note:** We recently combined this form with Dependents’ Request for Change of Program or Place of Training (VA Form 22-5495). This is now the only form to request changes to your education benefits.

Let me know if you'd like me to review any of the accuracy updates from Cinda.

## Page 4: [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/)

Here's the link to the [Drupal preview](http://preview-prod.vfs.va.gov/preview?nodeId=939). Note: You need to be on the VA network to access the preview, and links on preview pages don't work.

**Comment by jennymayoco** [comment]
Related redirect ticket #88975

**Comment by jsimonVA** [comment]
> @jsimonVA, please review my content recommendations below. After we finalize these pages, we can align on a timeline for publishing them on VA.gov. My copyeditor will archive page 1 and publish pages 2 and 4. Your team will need to publish the updates to page 3.
> 
> ## Page 1: [About VA Form 22-5495](https://www.va.gov/find-forms/about-form-22-5495/)
> Before we archive this page, we'll need to confirm that the redirect is working properly. Have you opened a redirect ticket?
> 
> ## Page 2: [About VA Form 22-1995](https://www.va.gov/find-forms/about-form-22-1995/)
> Here's the link to the [Drupal preview](http://preview-prod.vfs.va.gov/preview?nodeId=5977). Note: You need to be on the VA network to access the preview, and links on preview pages don't work.
> 
> The "form last updated" content will automatically update when the PDF is updated in the forms database. My team doesn't control that content or process.
> 
> ## Page 3: [Change your education benefits](https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=false)
> Here's my content recommendation for the intro in [staging](https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=true):
> 
> > If you're a Veteran or dependent, you can use this form to request changes to your GI Bill school, program, or other VA education benefits.
> > **Note:** We recently combined this form with Dependents’ Request for Change of Program or Place of Training (VA Form 22-5495). This is now the only form to request changes to your education benefits.
> 
> Let me know if you'd like me to review any of the accuracy updates from Cinda.
> 
> ## Page 4: [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/)
> Here's the link to the [Drupal preview](http://preview-prod.vfs.va.gov/preview?nodeId=939). Note: You need to be on the VA network to access the preview, and links on preview pages don't work.

@aprocik1 Changes look good! :)

**Comment by aprocik1** [comment]
@jsimonVA, thanks for this confirmation! I sent these pages to my copyeditor. I'll let you know their timeline for publishing these pages this week.

Do you have a timeline for publishing the note on the form intro page ([Change your education benefits](https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction?toggle=false))? And do you have a timeline for redirecting the [About VA Form 22-5495](https://www.va.gov/find-forms/about-form-22-5495/) page to the [About VA Form 22-1995](https://www.va.gov/find-forms/about-form-22-1995/) page?

**Comment by jsimonVA** [comment]
@aprocik1 Good morning. Our timeline is, as soon as possible. We have already pushed the updated 1995 with Intro page.
Until the redirect can be put in place we have updated the [intro page of the 5495](https://www.va.gov/education/apply-for-education-benefits/application/5495/introduction?toggle=true) as well.

**Comment by aprocik1** [comment]
@jsimonVA, that's great! We'll publish the updates to these pages today:

- [About VA Form 22-1995](https://www.va.gov/find-forms/about-form-22-1995/)
- [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/)

Let me know when you redirect the [About VA Form 22-5495](https://www.va.gov/find-forms/about-form-22-5495/) page and we'll archive it in Drupal. Thanks for your collaboration on this!

**Comment by aprocik1** [comment]
@jsimonVA, I know the Public Websites team implemented the redirect from the About VA Form 22-5495 page to the About VA Form 22-1995 page. As a result, I confirmed that all mentions of VA Form 22-5495 are removed on VA.gov. Then I archived the the About VA Form 22-5495 page in Drupal.

The only remaining work on this ticket is to update the VA Form 22-1995 form intro page to align with the VADS. I haven't drafted those updates yet. Do you have a sense of when your team may be ready to work on this with me?

**Comment by mistymg** [comment]
Followed up with @jsimonVA in [Slack](https://dsva.slack.com/archives/C04D5FS91BK/p1751573984766319).
