### ISSUE TITLE
[CST] Update Recent Activity logic so tracked items show multiple dates

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#89408]
## Value Proposition

As a veteran checking the status of my claim, I want to see both open and closed dates in Recent Activity, so that I have a comprehensive "paper trail" showing major claim events that can inform how I pursue follow up claim and decision review actions.

## Background Context
Noticed while working in the CST that the tracked items in the Recent Activity section are not showing both open and closed dates, they only show the MOST RECENT date based on the tracked item status. Talked to @skylerschain and he would like for us to change this logic so that we are showing both the open and closed date of a tracked item if we have it. 

This is also related to this older ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/76275

### New Feature
- Users want the ability to view both the open and closed date of a tracked item

## Design
- [Link to figma designs](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?node-id=2559-4745&t=XJDBb3QmW1Ro7pWN-0)

## Engineering 
- An eng will need to go to `src/applications/claims-status/components/claim-status-tab/RecentActivity.jsx` and update the logic that we use in `generateTrackedItems()` for tracked items so that we show both the open, closed, oldest doc upload, completed review and requested dates. We will likely need to update the logic so that a tracked item date isnt dependent on the item status. 
- I think we will want to have logic that looks at a given date field for a tracked item and if it exists then then we will want certain wording
- `item.requestedDate` -> `We opened a request for "${displayName}"`
- `item.closedDate` -> `We closed a request for "${displayName}"`
- Get the oldest document date using current function `getOldestDocumentDate(item)` -> `We received your document(s) for "${displayName}"`
- `item.receivedDate` -> `We completed a review for "${displayName}"`
- `item.requestedDate` -> `'There was an update to this item'`

## Open questions
- Does the above logic make sense???

## Tasks

Design:
- [ ] Figma Design link has been added

Engineering:
- [ ] Update logic for recent activity to show multiple dates regarding a given tracked item

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] Recent activity section shows multiple dates regarding a given tracked item

**Comment by pmclaren19** [comment]
Reviewed during eng refinement.

**Comment by pmclaren19** [comment]
Tested in Staging on user 19 and looks great!
