### ISSUE TITLE
[DevOps] Automatically export API Gateway OpenAPI spec for LoROTA.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89403]
## Description
Probably use that for triggering the deployment too, maybe. Admittedly I think it'd have to depend on half of Creation but whatever.

Throw it in an S3 bucket.

## Tasks
- [x] [DevOps] Create `aws_api_gateway_export` block.
- [x] [DevOps] Create resources necessary to make this available in an S3 bucket.
- [x] [DevOps] Add outputs for S3 bucket and key.

## Acceptance Criteria
- [x] OpenAPI export is uploaded to S3 bucket after deployment.

**Comment by ndouglas** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/api_gateway_export
