### ISSUE TITLE
Onboarding Maya Carroll

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#89404]
## Issue Description
Onboarding new designer to DBEX-TREX Maya Carroll. This ticket is to track UX onboarding activities. Start date is 8/5. Note @mengA6 will be out the week of 8/12 and possibly also 8/19 - 8/21.

---
## Tasks
- [x] Help facilitate new team onboarding by sharing [welcome doc](https://docs.google.com/document/d/1sIxEwm-qUlWAMnRHDWf2AsP3wsSiv0HyelrL70Z3Wws/edit?usp=sharing) with Maya.
- [x] Help mitigate any design tooling access issues in collaboration with the delivery manager.
    - [x] [Figma request ticket created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89788)
- [x] Set up time to meet with Maya to give an overview of the tools & work.
- [x] Set up to begin platform onboarding
- [x] Orient to Submission Experience work

## Acceptance Criteria
- [ ] Maya will complete welcome doc checklist.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mengA6** [comment]
I shared the welcome doc and invited Maya to all the relevant program meetings I could find. Also started an [A6 Slack channel](https://agilesix.slack.com/archives/C07EWFUBNUD) to coordinate with people ops.

**Comment by mengA6** [comment]
Also sent an invitation to Figma to her email - not sure if we need someone else to approve it

**Comment by evelynhilbrichdavis** [comment]
Scheduled three 30 min check-ins w/ Maya while Mike is out! I'll answer her questions, introduce her to the product, and share research.

**Comment by mayacarrolluxa6** [comment]
Daily Huddle Update: Onboarding Progress

**Last Week**
- Completed Week 1 of onboarding documentation
- Achieved 50% completion of Agile Six company onboarding tasks
- Processed SAC Adjudication
- Gained access to VA Remote Desktop, Outlook, Teams, VA GitHub, and VA Figma

**Today**
- Continue working through New VFS Team Member Onboarding tasks
- Sync with the PM
- Progress with remaining Agile Six company onboarding tasks

**Impediments**
- No access to VA Slack or Zenhub
- Potential issue with Zenhub license availability that needs to be addressed

**Comment by mayacarrolluxa6** [comment]
Daily Huddle Update: Onboarding Progress

**Yesterday**
- Continued Agile Six onboarding
- Continued VFS New Team Member onboarding
- Synced on upcoming roadmap items with the product team
- Initiated discussions about planning ideation sessions around Truthful and Timely Submission and Submission Records

**Today**
- Continued DBEX-TREX UX onboarding
- Shadowed DBEX-TREX Sprint Review and Backlog Refinement
- Continued Agile Six onboarding
- Continued VFS New Team Member onboarding

**Impediments**
- Waiting for PIV card
- Awaiting VA approval for access to Okta and Mural

**Comment by mayacarrolluxa6** [comment]
Yesterday
- Completed VFS new team member onboarding.
- Continued A6 onboarding.
- Meet n’ Greets with Scrum team members

Today
- Attend a walkthrough of the Toxic Exposure section of the form in Staging hosted by Christine.
- Write an outline and agenda for the Ideation Workshop and share with the team for feedback.
- Set up a Mural board for the Ideation Workshop and share with the team for feedback.
- Attend an onboarding session hosted by Evelyn for Google Analytics and Medallia.
- Start Benefits Portfolio onboarding and complete VA trainings.
- Sync with Product Manager & Delivery Manager

Impediments
- Waiting on access to Medallia, a tool owned by Aubrey Arcangel.
- Submitted requests to the VFS Platform Support team, awaiting access to Zenhub, Google Analytics, and Demo.

**Comment by mayacarrolluxa6** [comment]
Yesterday
* Attend a walkthrough of the Toxic Exposure section of the form in Staging hosted by Christine.
* Write an outline and agenda for the Ideation Workshop and share with the team for feedback.
* Set up a Mural board for the Ideation Workshop and share with the team for feedback.
* Attend an onboarding session hosted by Evelyn for Google Analytics and Medallia.
* Start Benefits Portfolio onboarding and complete VA trainings.
* Sync with Jared and Sarah
* Attend DBEx2 0781 Research findings readout

Today
* Shadow TE production Testing Sessions
* Continue with Submission Ideation workshop prep
* Continue A6 onboarding meetings
* Sync with Sam Wiley 

Impediments
* Troubleshoot access issues Zenhub, Google Analytics, and Domo

**Comment by mayacarrolluxa6** [comment]
Frday
* Shadowed TE production Testing Sessions
* Attended DBEX-TREX and Carbs Design Sync with Shannon and did some design critique on 0781 conditions form
* Finished and shared the Submission Ideation Workshop plan and mural board. 
* Continue A6 onboarding meetings

Today
* Start Benefits Portfolio Onboarding
* Continue A6 onboarding meetings
* Sync with Sam & Shannon
* Continue meet n’ greets with DBEX-TREX Team members 

Impediments
* Troubleshoot access issues Zenhub, Google Analytics, and Domo

**Comment by mayacarrolluxa6** [comment]
8.19.2024 Standup Update

Yesterday:
* Began Benefits Portfolio Onboarding.
* Continued A6 onboarding meetings.
* Synced with Sam & Shannon.
* Continued meeting with DBEX-TREX Team members.
* Paired with Evelyn for Medallia synthesis [link](https://cityfriends-my.sharepoint.com/:x:/g/personal/evelyndavis_cityfriends_onmicrosoft_com/ET3nGpy3UQNFo7IzF40T_ioB-kr25Cw0NMrTyE2ao8JU1w?e=8xXqN2).

Today:
* Participated in a VBMS walkthrough with Christine.
* Product <> UX Sync.
* Synced with VBA and VA onboarding buddy.
* TE monitoring with Evelyn.
* Continued Benefits onboarding.

Impediments:
* Troubleshooting VBMS access issues.

**Comment by mayacarrolluxa6** [comment]
Yesterday:
* Resolved issues with PIV card
* Prep for Submission Ideation workshop on Monday
* Continued Benefits portfolio onboarding

Today:
* Shadow TE testing sessions on prod.
* Complete VA TMS trainings
* Final prep for Submission Ideation workshop on Monday 

Impediments:
* No access to ZenHub

**Comment by mayacarrolluxa6** [comment]
@mengA6 @sarahknoppA6 
I now have access to Zenhub and GA4. The only remaining issue is making sure I can view VA calendar events for the Benefits portfolio. Do you have any suggestions on how to troubleshoot this? Thanks!"

**Comment by sarahknoppA6** [comment]
@mayacarrolluxa6 @mengA6 I'm curious if this is something Mike can help with- I do not know if I have all those calendar events and where I might be able to see them.

**Comment by mengA6** [comment]
I have [this ask to Naomi for the Weekly Design Sync](https://dsva.slack.com/archives/C04JC38EMHC/p1724687136636619?thread_ts=1723478820.520099&cid=C04JC38EMHC) and will keep an eye out for any other OCTO events.

**Comment by mayacarrolluxa6** [comment]
I have onboarded.
