### ISSUE TITLE
Staging review artifacts testing

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#89411]
Follow up from [Toxic Exposure: Prepare artifacts for staging review #67022](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/67022)

Test users:
50, 15, 68, 54

[Slack thread](https://agilesix.slack.com/archives/C04MJV66ZPC/p1722267173258059)

## Overview 
Perform manual testing needed for [staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review).  Out of all the [QA artifacts](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards) needed, the scope of this ticket is specifically for the [Traceability Reports ](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-traceability-reportsTraceabilityReports)

In order to generate these reports, the following manual test cases will be run by product and design:

Regression Tests <tbd>

1. [C37806 526 Minimal Test](https://dsvavsp.testrail.io/index.php?/cases/view/37806)

Product Changes Tests

2. [C79056 Standard Claim + TE (all of 15B, 15C, 15D)](https://dsvavsp.testrail.io/index.php?/cases/view/79056)
2. [C79947 BDD (Benefits Delivery at Discharge) + TE](https://dsvavsp.testrail.io/index.php?/cases/view/79947)
3. [C79948 FDC (Fully Developed Claim) + TE](https://dsvavsp.testrail.io/index.php?/cases/view/79948)
4. [C79949 Standard Claim + Explicit no TE](https://dsvavsp.testrail.io/index.php?/cases/view/79949)
5. [C79058 Edge Cases](https://dsvavsp.testrail.io/index.php?/cases/view/79058)
6. [C87890	1.1 In Progress Form (IPF) - Standard Claim + TE (alll of 15B, 15C, 15D)](https://dsvavsp.testrail.io/index.php?/cases/view/87890)
7. [C79934 VBMS Verifications](https://dsvavsp.testrail.io/index.php?/cases/view/79934)

## Tasks
- [x] Create Test Run(s) in Test Rail: the following test runs
    - [x] @mengA6 test in Windows using CAG, Edge browser, user 54, [C37806 526 Minimal Test](https://dsvavsp.testrail.io/index.php?/cases/view/37806) and [C79056 Standard Claim + TE (all of 15B, 15C, 15D)](https://dsvavsp.testrail.io/index.php?/cases/view/79056)
    - [x] @pacerwow test in Mac OS using another [supported browser](https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy), all tests
    - [x] someone test in iOS Safari, user 54 - test [standard claim + TE](https://dsvavsp.testrail.io/index.php?/cases/view/79056), optionally test [IPF](https://dsvavsp.testrail.io/index.php?/cases/view/87890)
- [ ] Manually step through each test case
- [ ] Create tickets for any issues found

## Acceptance Criteria
- [ ] Traceability reports artifacts are generated and linked in [TE collab cycle ticket ](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60140)

**Comment by mengA6** [comment]
Completed regression test in Windows > Edge. One thing to note that will be hard to find in the reports:

throughout the form, Did not see application ID with "save in progress" alert or in the text under the progress bar. https://jmp.sh/84ELIVEC (this isn't marked as a failure, since there wasn't a place for it in the steps - it's just in the notes at the top of the run)

**Comment by mengA6** [comment]
Pausing on this per [blocking Lighthouse issues](https://agilesix.slack.com/archives/C04MJV66ZPC/p1722460572093259?thread_ts=1722267173.258059&cid=C04MJV66ZPC).

I completed the regression test as mentioned above and also the Standard Claim + TE test in Windows > Edge using Citrix Access Gateway. 

Notes and links to some screenshots on actual results are viewable in testrail under "[R5765 Staging review artifacts testing#89411 - Mike](https://dsvavsp.testrail.io/index.php?/runs/view/5765&group_by=cases:section_id&group_id=19004&group_order=asc)". Scroll midway down on the center-right panel and look under "actual result" ([screenshot](https://jmp.sh/EkZ8BTf7)).

**Comment by mengA6** [comment]
Decided to prioritize the first two tests in the list. Got a [submission error with an international address](https://agilesix.slack.com/archives/C04MJV66ZPC/p1723138941398509?thread_ts=1722267173.258059&cid=C04MJV66ZPC). Need to still test with a US address.

**Comment by mengA6** [comment]
I've completed multiple runs of C37806 526 Minimal Test, C79056 Standard Claim + TE (all of 15B, 15C, 15D), and C79934 VBMS Verifications . 

C37806 526 Minimal Test passed.

C79056 Standard Claim + TE (all of 15B, 15C, 15D) failed, but I don't think any of the issues are launch-blocking.

Will need someone to retest C79934 VBMS Verifications with claim ID 600536064, submitted 8/9/24. It's not showing in VBMS 50 mins after submission. Compare against the following info:
> phone: 666-666-6666. Marine Corps 5/25/2001 - 8/10/2003. Providence, RI 02906. Neck Strain (cervical strain). VA employee: yes. checking account / routing number: 987654321. mike's bank.

You should be able to see / edit any of my test runs in testrail under [Staging review artifacts testing#89411 - Mike](https://dsvavsp.testrail.io/index.php?/runs/view/5765&group_by=cases:section_id&group_order=asc)

**Comment by mengA6** [comment]
created non-launch-blocking bug tickets:

1. [change "learn more about toxic exposure" link#90445](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/90445)
2. [Validation errors setting date fields to null #90446](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/90446)
3. [not seeing "your application will be saved on every change" under "step 2 of 5 conditions"#90447](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/90447)
4. [summary page for "other toxic exposures" Vertical spacing between list items is uneven#90448](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/90448)
5. [on "what type of evidence do you want us to review as part of your claim" - initial click on "private medical records" checkbox triggers a validation error and does not check the box#90449](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/90449)
5. [uploading private medical records, inline error "we couldn't upload your file"#90450](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/90450)

**Comment by pacerwow** [comment]
I think this can be closed as we've provided Platform what they asked for re QA artifacts and it looks like no remaining tasks.
