### ISSUE TITLE
[FE] 10-10EZ: Create shortened URL for temporary text campaign

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89414]
## Background

Our Health Eligibility/Enrollment stakeholders have just asked if we can provide a shortened URL for our 10-10EZ form ahead of a text message campaign to Veterans who are in Priority groups 8e or 8g, to encourage them to reapply for health care and provide info/evidence of Toxic Exposure.  This could help them get additional care/higher priority group.  There will be emails and letters sent as well, using the full URL.  A total of 1.9 million Veterans will be contacted as part of this campaign.

We can set the URL to use a 6 digit alpha-numeric code.  Using the same random method from Mikki's suggestion on the [EZR ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89015), we will use www.va.gov/4ktd8b as the shortened URL

## Tasks
- [x] Redirect URL is requested for www.va.gov/4ktd8b to redirect to the health care application introduction page https://www.va.gov/health-care/apply-for-health-care-form-10-10ez/introduction - [request ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+franecross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+sitewide%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [x] Redirect is tested to ensure the new shortened URL is being directed to the health care introduction page to apply for VA health care
- [x] Redirect is validated and signed off by PM
- [x] Redirect is launched to production

## Acceptance Criteria
- A shortened URL is created for a HEC/VEO text campaign to send PG 8e & 8g Veterans to the 10-10EZ, encouraging them to provide Toxic Exposure details which could qualify them for enrollment/additional care with VA.

**Comment by emily-brown34** [comment]
waiting to hear back from CAIA before we can proceed

**Comment by longmd** [comment]
@hdjustice , this has been published to dev for verification. All good on my end. As we learned last time, staging and prod will go together tomorrow at 10a.

**Comment by hdjustice** [comment]
Validated that the dev environment successfully redirects dev.va.gov/4ktd8b to the 10-10EZ Introduction page!  We will validate once in staging & production tomorrow at 10am ET.

**Comment by hdjustice** [comment]
Validated that the Production environment successfully redirects www.va.gov/4ktd8b to the 10-10EZ Introduction page!
