### ISSUE TITLE
Rerecord design orientation video

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#89428]
## User Story
As a Platform team member supporting Platform Orientation, I want to make sure orientation materials are up to date so that VFS teams are learning our current processes. 

Assignee: @allison0034 @naomimarcussen 
Peer Reviewer:

## Description
In a recent review of orientation materials, it was noted that the Design and Research Orientation video is not up to date. Per @allison0034, we need to , "Update office hours, v1 vs v3, run thru of design system, Storybook run thru."

The purpose of this ticket is to rerecord the Design and Research Orientation video, ensure it is transcribed correctly, upload to YouTube and ensure the link on Platform Website Orientation Sessions page has been updated.

Please be sure to reference the[ guidance ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Guidance)Brian put together on recording accessible videos. 

#### Drafts
[Orientation sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3398795265/Allison+Brian+Ian+Copy+of+Orientation+Sessions+2)

#### Production
[Orientation sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions)

## Tasks
- [x] Meet with Naomi and decide what sections should be recorded and list them here
  - [x] Intro to [Design and Research](https://docs.google.com/presentation/d/1hGTPJ622-249nWCJIuKnJSlGozNLqJfqJ92MY_SG16g/edit#slide=id.p1) (Naomi)
  - [x] [Intro to Research at VA](https://docs.google.com/presentation/d/1gZkqnX5piYkRJoF72FgKKytY3pS3OO6I-FIC6Ua_wOg/edit#slide=id.p16) (Naomi)
  - [x] [Intro to Design System and Storybook](https://docs.google.com/presentation/d/1QkHcMvfd_Hjt4Wg-1R2q_37FUU3VGgc6fKCqL5S8KmE/edit#slide=id.p22) (Allison)
  - [x] [How to use Figma](https://docs.google.com/presentation/d/1YAdWccowX0bQ2b1umWPUMpfKio4_TSlCzKqnX58hWnc/edit#slide=id.g27facc0d73a_0_10) (DST is responsible and Carol has made a ticket)
- [x] Review [slide deck](https://docs.google.com/presentation/d/1gSeffl2STubvPDH9EoB-wUE2Al73wAwsG9QPQQU6eqw/edit#slide=id.p24)
- [x] Rerecord video(s)
- [x] Update link on orientation page

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Design and Research Orientation video for VFS teams is up to date and accurate
-

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Met with Naomi and we will be splitting this into 4 videos since things are ever changing.

**Comment by allison0034** [comment]
This will move into the next sprint as Naomi is out of office and being on support last week took up a larger than expected chunk of time.

**Comment by allison0034** [comment]
[Reached out to DST](https://dsva.slack.com/archives/C01DBGX4P45/p1723818235130529)

**Comment by allison0034** [comment]
Carol has created a DST ticket and it will likely be completed in the next sprint.

**Comment by allison0034** [comment]
Cleaned up the design slide deck

**Comment by allison0034** [comment]
Intro to DS and Storybook is edited and uploaded, I updated the draft [copy of orientation page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Guidance) with my link.

**Comment by naomimarcussen** [comment]
Research and Design Orientation Overview is edited and uploaded to YouTube. I've updated the [draft copy of orientation page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3398795265/Allison+Brian+Ian+Copy+of+Orientation+Sessions+2) with my link.

**Comment by naomimarcussen** [comment]
The Intro to research video has been edited and uploaded to YouTube. I've updated the [draft copy of orientation page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3398795265/Allison+Brian+Ian+Copy+of+Orientation+Sessions+2) with my link.

**Comment by naomimarcussen** [comment]
I've re-recorded and uploaded my video for Intro to research. The closed captions on the first were off. I also updated the link on the [draft copy of orientation page].(https://vfs.atlassian.net/wiki/spaces/PPST/pages/3398795265/Allison+Brian+Ian+Copy+of+Orientation+Sessions+2)

**Comment by allison0034** [comment]
Updated PW page and waiting for that to publish.

**Comment by shiragoodman** [comment]
Hey @caw310 - can you please share your ticket for recording the How to use Figma video? ty!

**Comment by caw310** [comment]
@shiragoodman here is the ticket which is in sprint 9 [Create video on how to use the DS component library in Figma](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3192)
