### ISSUE TITLE
Broaden request specs for 2122 and 2122a PDF generation endpoints

### ISSUE THREAD

**Issue by opticbob** [department-of-veterans-affairs/va.gov-team#89429]
## Background
Right now only very basic happy/sad path specs exist.  Let's add specs that check for valid data, incomplete data, and invalid data.

## Tasks
- [x] Add valid with missing optional data specs to 2122
- [x] Add incomplete data specs to 2122
- [x] Add invalid data specs to 2122
- [x] Add valid with missing optional data specs to 2122a
- [x] Add incomplete data specs to 2122a
- [x] Add invalid data specs to 2122a

## Acceptance Criteria
- [x] The endpoints for PDF generation of the 2122 and 2122a have much better test coverage beyond just the happy and sad path

**Comment by opticbob** [comment]
###### Daily Update

- Specs have been added to the 2122 endpoint covering optional data, incomplete data, and invalid data.
- The 2122a is next.

**Comment by opticbob** [comment]
Daily update

Changes based on PR feedback
- Simplified guard clause on custom validation
- Clarified description statements on specs
- Reduced request specs that were duplicating model validation specs
