### ISSUE TITLE
IA Playbook for Migration Work

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#89426]
### Description
Create a playbook focusing on IA tasks so that CAIA is better aligned on role expectations and timing. We're building on [existing documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/process/content-migration.md) that Mikki has started.

### Timeline
Review with Derek and A in two weeks (week of 8/12)

```[tasklist]
### Tasks
- [x] Update existing doc in GH
- [x] Share with Mikki for feedback
- [x] Make any changes
- [x] Share with A and Derek
```

**Comment by jennymayoco** [comment]
Update: shared draft with A, Derek and Beth for feedback. Made minor updates as per A's feedback in Slack

As for the suggestion to do redirects all at once, we need OCTO feedback on this

**Comment by scjwalker** [comment]
@strelichl Kristin is going to wrap up the Education Migration initiative IA work - assigning this ticket over to her.

**Comment by kristinoletmuskat** [comment]
All IA steps added to content github doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-strategy-ia-collaboration/continued-content-migration-strategy/benefits.va.gov/migration-process.md
