### ISSUE TITLE
Research | IES | Desk Research about ILER

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89420]
## Background 
We're going to explore adding an affordance/component/open item to VA.gov Profile to download a veteran's ILER record. There has been a lot of research previously related to ILER and Military History Information. 

As a new researcher to the team, this ticket is to review as much information as possible that has already been surfaced as it relates to ILER and summarize what the immediate next steps might be based on the previous research. However, we must keep in mind there is a strong legislative mandate behind surfacing ILER and VBA does believe VA.gov is the right place to surface the IES download. 

### Artifacts from prior research (not exhaustive) 
- [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695126310753/6ab8c3953d2eeaa067f666d5a03a754c5ded3d82?sender=uaa72d11015d3f7c704a64191)
- [2023 enhanced military ask](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information)
- [sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/identity-personalization/profile/military_info/2023-enhanced-military-information)
- [Mural from Benefits Decision Review](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1439-10305)
- [Benefits Decision Review team research findings for above](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement/Research/012024-accessible-submission-download)
- [Enhanced Military Information research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery)

## Tasks 
- [x] locate previous research on related issues for Veterans
- [x] review new info from stakeholder and MCT ILER research
- [x] summarize above
- [x] make recommendations

## Acceptance Criteria 
at the end of this ticket we will
- [x] have a summary document w/the immediate recommendations 
- [x] what do we say about editing / correcting (if anything at all)
- [x] peer review

**Comment by twoangstroms** [comment]
@mtcA6 Is there a solid requirement that this is a button (as stated in Background)?

**Comment by mtcA6** [comment]
Nope, was simply operating from the "buttons do things and links go places"

**Comment by twoangstroms** [comment]
@mtcA6 Thanks. I wasn't sure if "button" was direct from stakeholders. The counter is this from the VADS: https://design.va.gov/components/link/#when-to-use-a-download-link

**Comment by twoangstroms** [comment]
@mtcA6 Thanks! I'm learning how to read these tickets, and wanted to be explicit about the background and ask. Digging into the Epic, it seems there were a lot of learnings and branches, so when I saw "button", I wasn't sure if that was a hard ask.

LMK If  you have a link to that "blue button" example.

I'm [asking across teams](https://dsva.slack.com/archives/C0NGDDXME/p1722343376037609?thread_ts=1722302484.792499&cid=C0NGDDXME) to see if anyone is working on anything similar. It looks like Benefits Decision Reviews [is](https://www.figma.com/design/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?node-id=1439-10305&t=Nbcg8i9lyGhUd5lJ-0).

**Comment by mtcA6** [comment]
@twoangstroms oh oh forgot, could you point this? 

Also I saw this in your slackup but it wasn't in the "in progress" column. Updated that, i know we haven't yet talked norms for tickets, it's on @ACParker89 's list for norming. In the meantime sharing some important tidbits. I know it can be tedious at first but this is a team norm. Each ticket owner is responsible for making sure the ticket is sitting in the correct columns and if it's a new thing being added to sprint it's really important to call that out for Alex and I by mentioning us on the ticket. We can get into more process things later on during retro/norming or give me a ring and i can talk through more of this as well if you have questions.

**Comment by twoangstroms** [comment]
@mtcA6 Okay, great! I saw it wasn't in In Progress but I assumed (I know...) that you'd had it there for a reason. Bad assumption! Thanks for moving it. I'll work on collating the "what I'd need to get this done and dusted" list.

**Comment by twoangstroms** [comment]
@mtcA6 Quick blocker question from me: Where and how should I create a page for the findings? Newbie to GH and to how this team organizes documentation in it.

**Comment by mtcA6** [comment]
@twoangstroms good question, [somewhere in the profile directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile).

I think maybe we start in the military information section and if we move it out of there we can do that. 

I believe there was platform guidance on research best practices that each product should have a research folder and any research goes in there. We can start out by placing the research [in here in a new folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/discovery-and-research). Would probably be easiest to hop on a 5 min call to create the pages you need.

**Comment by twoangstroms** [comment]
Carrying over to next sprint

**Comment by ACParker89** [comment]
@twoangstroms - please add tasks to this ticket, and provide a status update. Thanks! 

CC:@mtcA6

**Comment by twoangstroms** [comment]
Need to validate some information before making recommendations, rolling over ticket

**Comment by mtcA6** [comment]
@twoangstroms morning! what do you need from me to close this ticket up and roll into the process flow and readouts?

**Comment by mtcA6** [comment]
@twoangstroms could you add a link to the document?

**Comment by twoangstroms** [comment]
@mtcA6 Sorry. Done! https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2024-ies/ILER%20Desk%20Research%202024.md

**Comment by mtcA6** [comment]
🙇‍♂️ thanks!
