### ISSUE TITLE
Copy of Appoint a Rep - Cross Accredited VSOR - User Test - Planning

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#89439]
## Issue Description
Interviews and user test of the 21-22 with cross accredited VSORs.

## Tasks
- [ ] Create GitHub research folder
- [ ] Create research plan
- [ ] Define screener questions
- [ ] Create conversation guide
- [ ] Submit all materials to team for review
- [ ] Create revisions Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete.

**Comment by jfinnerty13** [comment]
Recruitment selection and emails complete - closing ticket
