### ISSUE TITLE
Document - How to log-into Staging

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#89431]
## Description

Create a step by step document demonstrating how to log-into Staging

## Tasks
- [x] Create a GitHub document
- [x] Add the link to the ticket
- [x] Notify the PO/PM so they can add the link to [this document](https://docs.google.com/document/d/1v7P2AEJZ6-6LbAhvUNB5tzgLqV7TlElc-qeymcmTPZ8/edit)

## Acceptance criteria

- [x] The link is shared and added to appropriate locations

## Testing
- [x] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by digitaldrk** [comment]
I have the content written, I'm not sure which repo/area to post the document. Will follow up with the team about which one.

**Comment by digitaldrk** [comment]
@denisecoveyduc , here you go! :)

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/back-end/logging_into_staging.md
