### ISSUE TITLE
Cypress videos upload fails due to no files

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#89430]
## Issue Description
Typically when Cypress fails tests, there will be recorded videos of the failures stored in the `cypress/videos` directory. However, for unknown reasons, the directory is empty and the artifact upload step fails to find any videos. These videos are critical to engineers diagnosing and fixing their failing tests.

---
## Tasks
- [x] Investigate why videos are not being stored in the videos directory in the cypress-tests workflow
- [ ] Fix the problem and verify that the videos are being uploaded as artifacts as expected.

## Acceptance Criteria
- [ ] Developers once again have access to their test fail videos.

**Comment by CBonade** [comment]
Worked in a test branch and I've merged the change into main. Just awaiting some failing cypress tests in CI to check and ensure it's fixed for everyone.
