### ISSUE TITLE
Re-watch Videos to Capture notes in Mural

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#89442]
## Task Description
Review each research question and find supporting data from the research. Re-watch videos to ensure notes are accurately captured in Mural and extract and highlight quotes from participants.

## Notes and References
-

## Acceptance Criteria
- [x] All research questions reviewed.
- [ ] Supporting data for each question identified.
- [ ] Videos re-watched.
- [ ] Notes accurately captured in Mural.
- [x] Quotes from participants extracted and highlighted.

## Deliverables
- Updated [Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719850140543/7d684cc9f91989c4caa1ac5c208879875a4634ec?sender=uc6180068871478c530ab2434)with accurate notes and highlighted quotes.
