### ISSUE TITLE
Re-Organize Upcoming Sprint Tickets

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#89441]
PM pre-scheduled the Upcoming Sprint before going OOO. He will be OOO for the last few days of this sprint and the first few days of the next sprint. PM asked @BSmolensky to take charge of the board while he is OOO. There was not a lot of time to review/discuss plan for upcoming sprint. Had there been, we are certain these issues would have been identified and our PM would have signed off on these changes. But seeing as he is OOO right now, the task of changing the board fall to Brian. So, we created a ticket to track that additional work. 

### TASKS

- [x] Review Upcoming Sprint
- [x] Create Plan to fix Up Coming Sprint Tickets
- [x] Get Team Sign off on plan
- [x] Make Changes to the board. 
 
### Acceptance Criteria

- [x] Upcoming Sprint Column has bee adjusted to meet team's ability to complete tasks.

**Comment by BSmolensky** [comment]
### **Plan of action**: 

- [ ] Turn Audit PW for People Names into Epic (but do not being work on it)
- [ ] Turn Audit PW for Links in Headings into Epic (but do not begin work on it)
- [ ] Turn Audit External Service Integrations (ESI) into Epic
- [ ] Divvy up ESI pages so that each team member gets 9 pages to review
- [ ] Create and Add Archive HSQ ticket to Upcoming Sprint

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance Criteria met. Closing ticket.
