### ISSUE TITLE
Archive Health Quest Service Page

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#89455]
After work on ticket #[88907](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/88907) SME and PCT determined that the Health Quest Service product was no longer in active use. Therefore, we all agreed that the HQS page should get archived. 

### TASKS

- [x] Follow approved PW Archiving procedures
- [x] Archive the HQS page
- [x] Check to make sure that the IA reflects this change

### Acceptance Criteria

- [x] HQS page has been properly archived and no longer appears in the PW IA.

**Comment by taylojill** [comment]
Health Quest Service page archived per archiving instructions. IA checked to verify page is archived.

Reference [this ticket for more information](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/88907).

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance Criteria Met. Closing ticket.
