### ISSUE TITLE
Re-Record Platform Orientation Video for Platform Support 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#89498]
## Description 
Need to update the [Platform Orientation video](https://www.youtube.com/watch?v=iwIQU4XepNQ). See tasks for info to update. 
---

## Definition of Done
All tasks below are complete. 

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Re-record with the with the updated What We Can Help with Page content and correct navigation (no longer on general support page, in left hand navigation) 
- [x] Identify escalation strategy for end of video 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [ ] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Script to original video here: https://docs.google.com/document/d/103tLHRdjFM35uZpFPLwbYI3M7S1AL2_iAj9RmEq5n8M/edit

**Comment by bdech** [comment]
Navigation for the What We Can Help with Page on the Platform Website

Old Navigation: [Home](https://depo-platform-documentation.scrollhelp.site/) page --> [Support](https://depo-platform-documentation.scrollhelp.site/support/) --> What We Can Help With - Platform Support

New Navigation: [Home](https://depo-platform-documentation.scrollhelp.site/) --> [Support](https://depo-platform-documentation.scrollhelp.site/support/) --> [Support Best Practices](https://depo-platform-documentation.scrollhelp.site/support/support-best-practices) --> [What We Can Help With - Platform Support](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support)

**Comment by AnthonyWFlowers** [comment]
Link to recording [here](https://drive.google.com/file/d/1aVYjhIj27C_8CJZsRc6iZXZUK4ZqZE5d/view?usp=drive_link). 
I do not have access to upload to the Platform YT page. 
Updated escalation strategy at the end to reach platform support 
Added Launched Item to LSECD
re-assigning to Alyssa

**Comment by alyssagallion** [comment]
Sending to Governance and closing this ticket!
