### ISSUE TITLE
Contract Spin-Down Checklist

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#89494]
## Background
As we near the end of our first-year of ARM contract, we have been asked to document all of our work in a [Contract Spin-Down Checklist](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7Bd55fdfd9-f09c-462e-9e5b-40e798e70e8c%7D&action=edit&wdPreviousSession=f83eadb3-c399-9eb6-6abb-ab309d693961).

## Tasks
- [x] Janelle: Add links to research resources
- [x] Holden: Add links to technical resources
- [x] Lindsay: Add links to product resources

## Acceptance Criteria
- [x] Contract Spin-Down Checklist is completed.

**Comment by oddball-lindsay** [comment]
Added in what I could, awaiting an example from Jen for the "Audit Google Analytics custom events" piece as I'm not sure what that entails and couldn't find a specific reference in the linked example.

**Comment by holdenhinkle** [comment]
Holden:

- [ ] Document any custom scripts run for production support or remediation; check them into GitHub, along with a ReadMe file.
- [ ] Document anything that runs on a background schedule.
- [ ] Ensure there are no uncommitted branches.
- [ ] Share an upstream service map with contacts, following [this example](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Services/).

**Comment by holdenhinkle** [comment]
Update how to get flagged data - https://github.com/department-of-veterans-affairs/va.gov-team/pull/89930

**Comment by holdenhinkle** [comment]
List of background jobs:

Daily to get OGC data:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/veteran/app/sidekiq/veteran/base_reloader.rb

Daily to update org names:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/veteran/app/sidekiq/organizations/update_names.rb

Process Trexler File:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/veteran/app/sidekiq/representatives/update.rb

**Comment by holdenhinkle** [comment]
PR documenting Sidekiq jobs - https://github.com/department-of-veterans-affairs/va.gov-team/pull/89980

**Comment by oddball-lindsay** [comment]
Calling my contributions complete -- I don't have an example of the GA custom event audit that I requested from Jen, but she said that it was okay to proceed without that if need be.  

@holdenhinkle feel free to close this ticket when you feel your part is complete!

**Comment by holdenhinkle** [comment]
Service maps for FAR and POA widget:

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/launch-materials/arm-architecture-diagrams.pdf
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/launch-materials/architecture_diagrams.pdf

**Comment by holdenhinkle** [comment]
@oddball-lindsay 
The checklist requires us to provide "service maps" for our products. I'm using these which already exist. We're also supposed to provide contact information for each service.

Where do you think I should put this? I was thinking here? https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/product-documentation

**Comment by oddball-lindsay** [comment]
@holdenhinkle in each of my Product Outlines, I have contact info, would that work?

[Find a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/product-outline-find-a-representative.md#communications)
[Representative Status Widget](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/product-outline-representative-status-widget.md#communications)
[Appoint a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/appoint-a-representative/product-outline-appoint-a-representative.md#communications)

**Comment by holdenhinkle** [comment]
I added 'Service map' links on the following pages to the new Service Map pages I added:

- [Find a Representative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/find-a-representative/product-outline-find-a-representative.md#communications)
- [Representative Status Widget](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/product-documentation/representative-status-widget/product-outline-representative-status-widget.md#communications)
