### ISSUE TITLE
[Backend] Download Debt Letters from VBMS/eFolders (U) 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#8950]
## User Story 
As a Veteran who received a debt letter in the mail I would like the ability to see and download the letter online 

## Goal
_Give Veterans the ability to see debt letters online and have the ability to download them to print etc. 

---
## Tasks
- [ ] _Connect to VBMS/eFolders_
- [ ] _Authenticate user
- [ ] _Identify letters to be downloaded/viewed
- [ ] _View/download letter by type
## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
duplicate tix

**Comment by leahkeeler** [comment]
duplicate tix
