### ISSUE TITLE
EPIC | Profile | Contact Info Refresh 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89505]
## Background
We have uncovered a handful of data quality issues that are likely stemming from the UX/UI of our contact information page. 

Given this, we need to implement some process changes to the contact information address features. 

## Tasks 

```[tasklist]
### Initial Discovery/ Brain Dump
- [ ] tbd
```

```[tasklist]
### Design Intent
- [ ] review our design decisions/moks/journey
- [ ] make changes to design post design intent
``` 

```[tasklist]
### Research/Design Midpoint Prep
- [ ] Usability Research Plan
- [ ] Usability Convo Guide
- [ ] Usability Research Logistics
- [ ] Conduct the Study
- [ ] Synthesize the Research
``` 

```[tasklist]
### BE/FE Development 
- [ ] This ends with midpoint review
- [ ] GA ticket for any FE work 
- [ ] PM | Domo or GA Updates
- [ ] BE | Data Dog Dashboard Updates
``` 

```[tasklist]
### Midpoint Feedback Implementation
- [ ] implement an midpoint review changes if needed 
``` 

```[tasklist]
### QA
- [ ] QA Spreadsheet 
- [ ] QA testing plan document  
- [ ] QA team ticket
``` 

```[tasklist]
### UAT
- [ ] Conversation Guide 
- [ ] UAT Research Plan 
- [ ] PM | go/no-go convo
- [ ] UAT Study Logistics / Kickoff
- [ ] Conduct UAT
- [ ] Research Synthesis 
``` 

```[tasklist]
### Launch Planning
- [ ] Release Plan 
- [ ] Contact Center Guide Updates - submit before staging review 
- [ ] Staging Review 
``` 

```[tasklist]
### Incorporate Staging Review Feedback 
- [ ] add staging review tickets
``` 

```[tasklist]
### Launch
- [ ] Go/no-go prod convo
``` 

```[tasklist]
### Post Launch
- [ ] Documentation Updates 
``` 

```[tasklist]
### Tasks
- [ ] tasks
```

**Comment by mtcA6** [comment]
@jfinnerty13 maybe this is why they are there.... there are times when no override key is present and the user will NOT be allowed to save.
