### ISSUE TITLE
[HCD] Plan research for Downloadable Copy of an Appeal

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#89502]
## Value Statement

**_I want to_** develop a validation-oriented research plan with Veterans who want to file a Supplemental Claim

**_so that_** the team is able to validate whether our additions to the 20-0995 form are usable and accessible by Veterans

---
### Questions we want answered

- Does the new form flow make sense for Veterans?
- Are there any areas of friction caused by the new questions?
- Are there any considerations we aren't aware of with the new questions?

## Acceptance Criteria
- [ ] The plan has been reviewed and approved by the platform team
- [ ] Timing for the research study has been established, and the study is prepped for research recruitment
- [ ] Code prototype is ready for research

## Definition of Ready 
- [ ] Design artifacts for testing have been created and approved for evaluation

## Tasks
- [ ] Create a prototype
- [ ] Research Planning
	- [ ] Draft research plan
	- [ ] Draft conversation guide
	- [ ] Draft screener
- [ ] Review and Approval
	- [ ] Internal Review with Product Management, Research, and Accessibility
	- [ ] Schedule research review with Platform research team
- [ ]  Initiate Research Recruitment

## Design and Build 
- [Research Plan](#)
- [Conversation Guide](#)
- [Assumption Tests](#)

## Open Questions
- Should we plan for both accessibility testing and usability testing at the same time, or separate out the work?
- How can we test the form without authentication?

**Comment by anniebtran** [comment]
Might need to update design based on content updates

**Comment by anniebtran** [comment]
Eileen to work on research plan today

**Comment by anniebtran** [comment]
On hold until HLR is ready

**Comment by dfong-adh** [comment]
Research plan draft is complete, waiting for Julie to review. Working on conversation guide.

**Comment by dfong-adh** [comment]
Conversation guide in progress

**Comment by dfong-adh** [comment]
Julie to review and provide feedback on the conversation guide

**Comment by eileen-coforma** [comment]
Did not manage to start research review. Will pick this back up today. Going over suggestions by Julie in the convo guide and then moving content to GH.
