### ISSUE TITLE
Update 'Submit documents' page

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#89519]
## Description
As part of the usability study conducted in early spring, we found some opportunities to improve the experience for veterans as they complete the 527EZ form.

Design ticket #88400 has the background information for this specific change to the 'submit documents' page

## Designs
- [Submit docs](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5134-35974&t=wPk9ygJ7Bd4uJIpS-11)

## Acceptance Criteria
- [x] This change is kept behind a feature flag; will need to go through Collab Cycle (TBD whether this is the same feature flag that will be created for the other tickets or we create a new feature flag specific for this change.)
- [x] Web pages(s) are update to match the designs
- [x] All automated tests are update and passes

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)
- [x] Back-end work to set up feature flag (TBD)
- [x] Front-end work

## Review
- [ ] Designer/Product has signed off on pages in staging

**Comment by danbrady** [comment]
Staging review complete. Only minor grammatical issues found. Differences captured in [this figma file](https://www.figma.com/design/DvZN50R2KnQbdSfwkw8Rgm/527-Staging-Reviews?node-id=73-2168&t=YsJ0WFr6AbfqJn3i-1).
