### ISSUE TITLE
FE | Contact Info Refresh | Null out form on edit

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89515]
## Background
Veterans have been saving incorrect addresses and this feature change is to hopefully avoid some of those errors

## Steps to recreate
- Go to the profile page
- Click on `Contact Information` to navigate to its page
- The first section should be `Addresses`, containing `Mailing` and `Home` sub-sections
- Click on the Edit button to open the form for either sub-section
- [new behavior] the form should be empty/null

## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Ensure that no data requests are made when the edit form is displayed
- [ ] Ensure this logic is not broken ` const method = payload?.id ? 'PUT' : 'POST';`

## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] The change shouldn't break any functionalities

**Comment by ACParker89** [comment]
This ticket will require further research, and will need to be repointed. Moving out of "in progress" 

@mtcA6 @asiisii

**Comment by mtcA6** [comment]
@asiisii could you all document more about what the changes we need to make are in order to null out the form on edit? 

cc: @adamwhitlock1

**Comment by mtcA6** [comment]
discussed w/asiisii, he thinks he has workaround here by creating a new boolean attribute to toggle on and off the "null on edit" behavior

**Comment by asiisii** [comment]
Moving the ticket back to the backlog as we still need to determine if this work is necessary

**Comment by ACParker89** [comment]
@a6marinos @MikeC-A6 

Can we do discovery on if this is needed

**Comment by MikeC-A6** [comment]
@ACParker89 I believe we can close this one based on the discovery that was done. Could not trace this back to a user need.
