### ISSUE TITLE
HLR: End 2 End Testing

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#89522]
## Value Statement

Test the new HLR form from end to end to verify the content changes did not alter the form functionality. 

In staging, submit a test request and have LH orchestrate it to the point of PDF creation. Get a copy of the PDF and verify that the data matches what is sent from the form.
---

## Background Context

- The content changes shouldn't have modified the form payload

## Outcome, Success Measure, KPI(S), and Tracking Link

- Everything is as it should be

## Acceptance Criteria

- [ ] Data on the PDF matches what was sent from the form

## Tasks

- [ ] _Submit a test HLR submission to LH_
- [ ] _Work with LH to get a copy of the resulting PDF file_
- [ ] _Compare data on PDF with what is submitted_

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@shaunburdick is this redundant to #89863 since we've decided that we'll only be in charge of testing LH endpoint for content data.

**Comment by shaunburdick** [comment]
Closing as duplicate
