### ISSUE TITLE
FE + BE | MHV Notifications | Finish Wiring our 4 Feature Toggles

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89528]
## Background
We started to create feature toggles in the last sprint. We created them but need to finish wiring up all of the different scenarios to ensure we can turn each toggle on based on MHV's notification needs. Each toggle some nuance and you should refer to the moble flow figma file. 

### Feature toggles we're going to finish wiring 🔌 
- profileShowMhvNotificationSettingsEmailAppointmentReminders
- profileShowMhvNotificationSettingsNewSecureMessaging
- profileShowMhvNotificationSettingsEmailRxShipment
- profileShowMhvNotificationSettingsMedicalImages

## Tasks
- [ ] Conduct Unit tests 
- [ ] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
- [ ] confirm w/BE that changes have been made to the yml file

  
## Acceptance Criteria
- [ ] Complete all unit testing
- [ ] End-to-end tests showing 0 violations
- [ ] Notify Product Manager that the change is ready to be validated on Staging
- [ ] UI should display correctly for a user with healthcare - we should see different behaviors for a user with a mobile number, a user with an email, or a user with both. 
     - [ ] double check the information alerts on the page

**Comment by ACParker89** [comment]
waiting on PR review from @tpharrison

**Comment by tpharrison** [comment]
@ACParker89 I think this is all FE code so an FE dev should review.
