### ISSUE TITLE
Update user flow screenshots

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#89521]
## Task Description

Grab screenshots for primary user flows - both types of requests and ds - and update them in the user flows.

Error states can be omitted as those are hard to recreate, but feel free to update any you run across.

## Acceptance Criteria
- [x] Update user flow screenshots
- [x] Create a version in the file noting when the update was made
- [x] Add a link to that version in Deliverables section in this ticket

## Deliverables
[User flow](https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=1-3855&t=q5zuyOBjckTzlyD7-1)

**Comment by melissa-lefevre** [comment]
Updated user flows: 

- [ ] Direct schedule
- [ ] Requests
- [ ] Covid-19

Still need:

- [ ] CC request flow
- [ ] Alerts

**Comment by Jenny-yw** [comment]
CC request flow and location errors are already in the user flow Figma file. Is there a testing account I can use to see what other screens are missing? Maybe I can take on this task. @outerpress

**Comment by outerpress** [comment]
@outerpress to review

**Comment by outerpress** [comment]
@Jenny-yw I think I missed this in your original comment - the goal here is to update the existing screenshots to what's in staging.

Looking at the CC flow, the screens are out of sync with staging. For example, compare this screenshot from staging with the user flows - the back link and buttons are different:

<img width="735" alt="Image" src="https://github.com/user-attachments/assets/13e32c13-9f7f-4a5b-834b-c6bbfe0e5e00" />

So those will still need to be updated

**Comment by Jenny-yw** [comment]
@outerpress Gotcha. I misunderstood the task. I thought it was to add screens, not to update them. I will update the screens for CC to match staging, and tag you again once it's done.

**Comment by benbrasso-agile6** [comment]
Going to update the label on this to Sprint 2

**Comment by Jenny-yw** [comment]
Updated the flow, and created [SPIKE ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105076) to investigate if the second home address check is a requirement or bug in CC request.

**Comment by outerpress** [comment]
Thanks @Jenny-yw ! CC request flow looks good. I'll drop comments on the Spike ticket if I have any 👍
