### ISSUE TITLE
Document appt details and cancelation flow

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#89527]
## Description

Match the following to staging:
- Appointment details cards/pages
- Cancelation pages

## Tasks

- [x] Add details page flow to feature reference
- [x] Add cancelation flow to feature reference
- [x] Add details and cancelation content matrix
- [x] Add ICS file content

## Acceptance Criteria

- [x] Feature reference updated 

## Deliverables
- [Details and cancelation cards](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=54-11449)
- [Details pages](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1150-105402)
- [Cancelation pages](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1087-86861)
- [Content matrix](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1087-84974)
- [Add to calendar ICS files](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=2441-53001)

**Comment by outerpress** [comment]
Notes on remaining work:
- The [core content components](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1078-25166&t=dFuSktyk3Q4PYWM8-4) need to be updated so they make sense when reused across cards
- The [ICS file content](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=2441-53001) needs to be completed - source document [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/add-to-calendar-ics.md)

**Comment by Jenny-yw** [comment]
I’m creating another ticket for updating the content components, as it requires more collaboration and a strategic approach to making the components reusable. Then, I will close the ticket since the rest of the tasks are done.
