### ISSUE TITLE
Copy of Monitor PACT Act Fall 2024 Submissions

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89535]
## Issue Description
This ticket is to monitor the DataDog dashboard created by the Platform Product team [here](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms?fromUser=false&index=%2A&refresh_mode=sliding&view=spans&from_ts=1710421711677&to_ts=1711026511677&live=true) for T1 and T2 folk to check daily, beginning on 8/7, and ensure that there is no unusual activity or issues. 

---
## Tasks
- [ ] Daily monitoring by Platform Product or T1/T2 Support teams for unusual activity
- [ ] Action by the appropriate team in the event of unusual or blocked activity 
- [ ] Reroute issues to appropriate team when they are found, if they can not be mitigated by Platform Product team
- [ ] Follow up with assigned team to ensure that the fix has been implemented 
- [ ] PLATFORM PRODUCT TEAM MAJOR RESPONSIBILITY IS TO MONITOR AND MAKE OTHER TEAMS AWARE

## Acceptance Criteria
- [ ] Any unusual activity will be flagged by Platform Product or T1/T2 Support teams and rerouted to the appropriate team for their immediate attention as soon as PACT Act submissions begin to roll in.

**Comment by alyssagallion** [comment]
@jennb33 Hey! What is needed from Platform Support on this? Thanks!

**Comment by alyssagallion** [comment]
Going to take the label off for now so that it doesn't mess with our metrics, but add it back when you are ready for us!

**Comment by jennb33** [comment]
8/19 update: no update as of today.

**Comment by LindseySaari** [comment]
We've been instructed to pull down the related PACT act bulkhead and are creating a ticket for next sprint

**Comment by jennb33** [comment]
Closing this ticket at the end of Sprint 8.
