### ISSUE TITLE
Monitor PACT Act Fall 2024 Submissions - Sprint 7

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89533]
## Issue Description
This ticket is to monitor the DataDog dashboard created by the Platform Product team [here](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms?fromUser=false&index=%2A&refresh_mode=sliding&view=spans&from_ts=1710421711677&to_ts=1711026511677&live=true) for T1 and T2 folk to check daily, beginning on 8/7, and ensure that there is no unusual activity or issues. 

---
## Tasks
- [x] Daily monitoring by Platform Product or T1/T2 Support teams for unusual activity
- [x] Action by the appropriate team in the event of unusual or blocked activity 
- [x] Reroute issues to appropriate team when they are found, if they can not be mitigated by Platform Product team
- [x] Follow up with assigned team to ensure that the fix has been implemented 
- [x] PLATFORM PRODUCT TEAM MAJOR RESPONSIBILITY IS TO MONITOR AND MAKE OTHER TEAMS AWARE

## Acceptance Criteria
- [x] Any unusual activity will be flagged by Platform Product or T1/T2 Support teams and rerouted to the appropriate team for their immediate attention as soon as PACT Act submissions begin to roll in.

**Comment by LindseySaari** [comment]
We may need to add additional endpoints to the bulkhead along with slightly over provisioning. Steve Albers has this as an action item for determining the routes necessary for the PACT bulkhead(s)

**Comment by alyssagallion** [comment]
@jennb33 Hey! What is needed from Platform Support on this? Thanks!

**Comment by jennb33** [comment]
8/5 update: @LindseySaari raised this with Steve. We still need the endpoints for the bulkhead, and she will be meeting with a bunch of folks today and will raise it again.

**Comment by jennb33** [comment]
@alyssagallion - we are still pending the bulkhead, but once we get it implemented there may be some work for the Support team. Stay tuned!

**Comment by alyssagallion** [comment]
Cool. Going to take the label off for now so that it doesn't mess with our metrics, but add it back when you are ready for us!

**Comment by rmtolmach** [comment]
Bulkheads created: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3055

Everything looks fine so far. Datadog dashboard: [PACT Act August bulkheads (ITF, Pact Claims) 2024](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-august-bulkheads-itf-pact-claims-2024?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1723043947877&to_ts=1723130347877&live=true)

**Comment by LindseySaari** [comment]
Continuing to monitor while meeting with the greater team each Monday. Bulkheads are looking good on a high level.
