### ISSUE TITLE
Use Utilization for Sidekiq's HPA Metric

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89549]
Currently Sidekiq scales once there's a line of at least 30 jobs. We should instead scale on a percentage of busy (utilization).

## Tasks

- [ ] Craft query for Sidekiq Utilization
- [ ] Test it via `curl`
- [ ] Update Helm Chart and ensure template matches crafted query
- [ ] Update manifests repo to point to new helm chart
- [ ] Deploy and test in prod (watch metrics)

## Acceptance Criteria

- [ ] Production Sidekiq scales based on % busy (utilization) rather than number of jobs in line.

**Comment by ericboehs** [comment]
New HPA is deployed and working well. See [DD chart](https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/zub-r2c-zmz).
