### ISSUE TITLE
Configure Test Pod to Store Test Results

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#89543]
# Description
Postman test execution records need to be preserved for subsequent review. Implement a way of preserving execution records by outputting the postman execution logs to Datadog.

## Tasks

- [ ] Ensure logs are in a format that Datadog can consume
- [ ] Ensure logs are going to STDOUT so Datadog will pick them up

## Acceptance Criteria
- [ ] Postman execution records from within the postman test container are stored for long term review

**Comment by patrick-black-oddball** [comment]
postman logs are going to STDOUT and will be forwarded to datadog
