### ISSUE TITLE
[Design] Create mock up for BDD content page

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#8955]
## User Story or Problem Statement
As a UX Designer, I need to create a mock up for public websites so they have a visual of what we're thinking might improve the BDD content page user experience. 

## Goal
_A completed mock up of the [benefits delivery at discharge page](https://staging.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/)_

## Objectives or Key Results this is meant to further
- Prep the website content user experience for the launch of the BDD form - intended to go live in late June.

## Tasks
- [x] Create Sketch mockup of page
- [x] Upload page to Invision prototype
- [ ] Comment the Invision prototype link to the public websites intake request form #8668

## Acceptance Criteria
- [ ] The above tasks have been accomplished

**Comment by kevinstachura** [comment]
This page has been completed and can be found here: https://vsateams.invisionapp.com/share/CPXAPZRWHD8#/417745278_BDD_-_Info_Content_Page
