### ISSUE TITLE
Use Sidekiq Enterprise's Health Check

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89574]
Sidekiq Enterprise now has a built-in [Health Check endpoint](https://github.com/sidekiq/sidekiq/wiki/Kubernetes#sidekiq-enterprise). We should use this instead of the third-party gem, sidekiq_alive.

## Tasks

- [X] Remove sidekiq_alive
- [X] Add native health check
- [X] Test in lower envs
- [X] Deploy to production
- [X] Monitor health check is working appropriately

## Acceptance Criteria

- [X] Sidekiq Enterprise's native health check is in use in all environments

**Comment by ericboehs** [comment]
Completed via https://github.com/department-of-veterans-affairs/vets-api/pull/17784

Healthcheck is working well in production.
