### ISSUE TITLE
Plan approach to splitting CD off of CI

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#89577]
## Issue Description
Right now, the apps that have Continuous Deploy enabled deploy during the CI workflow. While this consolidated method works, it also restricts our ability to code freeze everyone across the board without having to shut down the CI workflow entirely. We ideally would like to leave CI open during code freezes so code can still be deployed to staging even during freeze times, as the freeze is only meant to apply to production. We need to come up with an approach to splitting off this deployment that remains functionally the same, but restores control to platform to switch off this deployment if necessary. 

---
## Tasks
- [x] Decide the best method for splitting the deployment of CD apps from the CI workflow.
- [x] Document the decided-upon method in a ticket for implementation.

## Acceptance Criteria
- [x] A solution to split this deployment from CI has been documented in a ticket to be implemented.

**Comment by CBonade** [comment]
Plan:

In order to accomplish this, we are going to use a `dispatch` event in GitHub actions. This will allow us to conditionally trigger a production deploy of this build. The `github.sha` variable that's currently referenced in the deploy step will need to be passed as a workflow env variable as part of the dispatch payload, as currently it's referencing it on its current workflow. If an app is an isolated app build, it will then dispatch the production workflow with the set commit sha, and follow the steps as it does now. 

This will accomplish a few things:

1. Keeps changes to a minimum
2. Removes clutter and complex logic from the CI workflow
3. Keeps the new workflow clean.

The new workflow will be named "CD Production Deploy" and will be able to be disabled from the GItHub UI the same way we disable the "Daily Production Deploy".

**Comment by JoeTice** [comment]
SPRINT 6 UPDATE: DONE - This ticket was completed on 7/31, but didn't get marked as closed
