### ISSUE TITLE
Confirm mitigation of failed claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89578]
## Issue Description
_We [recently discovered](https://dsva.slack.com/archives/C0547Q0K0LF/p1722285080051819?thread_ts=1722274335.667439&cid=C0547Q0K0LF) 6 claims that "resulted in failed" state since January 2024 and require manual intervention to submit and process successfully._

|Date                    |payload.uuid                        |@payload.claim_id| Notes| 
|------------------------|------------------------------------|-----------------|------|
|2024-07-29T21:19:56.050Z|`4e211ee5-b9c3-40bd-ae32-b2530c88e748`|9418101          |Invalid character in name, metadata validator should have caught this|
|2024-07-22T16:49:11.934Z|`b68f6d0c-7c7a-4bf6-8d86-1ba93aa3d6c0`|9418101          |Invalid character in name, metadata validator should have caught this|
|2024-06-21T14:25:11.727Z|`61cd713e-58d7-414e-90f3-a7b7a2dfe6ba`|9224663          |Attachment page too large|
|2024-05-30T15:52:27.006Z|`9c397fc1-ec1a-4199-a18b-71bacb430580`|9091673          |Attachment page too large|
|2024-05-30T13:24:39.728Z|`25f8e830-2be6-431d-b22d-09e03ff701cf`|9090483          |Attachment page too large|
|2024-05-30T03:42:22.502Z|`0de8d85e-ce5d-4e56-80a4-e0d7e07d2100`|9089383          |Attachment page too large|
|2024-05-24T19:54:05.201Z|`ea1e383e-4b73-4861-a1fd-0ec097327881`|9061565          |Resolved, is now in VBMS|
|[2024-09-12T04:02:26.435644Z](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3ABenefitsIntakeStatusJob+%40named_tags.dd.env%3Aeks-prod+%40payload.to_state%3Afailure+%40payload.form_type%3A686C-674&from_ts=1726034400000&to_ts=1726113782000&live=false&agg_m=count&agg_t=count&index=%2A&source=monitor_notif)|`8eb8ba1f-2a55-4158-bcca-4b2789013200`|9811436|Attachment page too large|
---
## Tasks
- [ ] Remove automatic recovery from the alert notification. Once the claim(s) associated with the alert is mitigated, the team should post the update on the alert within the alert channel.
- [ ] Confirm if the 6 failed claims were remediated
- [ ] If not, ask VBA to research and establish as necessary using the claim PDF

## Acceptance Criteria
- [ ] Determine if 6 failed claims were mediated
---

**Comment by evansmith** [comment]
9418101 was resubmitted successfully

**Comment by steele-lm** [comment]
Thomas to sync with Sam Stucky to decide how to remediate remaining claims. They all include pdfs that are too large.

**Comment by steele-lm** [comment]
Kyle Soskin is leading an effort to determine a comprehensive approach to preventing and mitigating claims that include uploads with pages that are too large to submit.

**Comment by mjknight50** [comment]
@TaiWilkin May have a solution to zip these up so that they can be manually remediated.

Also, this ticket is for the same topic:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/92522

**Comment by steele-lm** [comment]
OCTO is working on an SOP for failures and manual uploads that need remediation that will involve putting them in SharePoint with an Excel doc. The Veteran Facing Forms Team is team is working on abstracting the tools so all the teams put their failed forms in the same folder. They should have the approach finalized by the end of September.

**Comment by TaiWilkin** [comment]
@mjknight50 As much data as I was able to recover has been uploaded to Sharepoint for each claim.

**Comment by steele-lm** [comment]
@tbaker1026, @TaiWilkin recently collected and uploaded data and attachments for 6, 21-686c claims to the designated SharePoint folder. As a next step, I'm working with Emily/Amy to understand if we need to reach out to the VBA and establish a point-of-contact to access that folder and remediate those claims or if that point-of-contact has already been established. cc @mjknight50

**Comment by steele-lm** [comment]
Emily confirmed a process is in place to monitor the SharePoint folder. No further work is needed from our team.
