### ISSUE TITLE
[design] Claim Status Tool Research - Gather quantitative analytics

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#8957]
## User Story or Problem Statement
As a UX Designer, I need to aggregate quantitative data in order to plan a proper research initiative around the claim status tool. 

## Goal
Collect whatever data we can to support the research initiative around claim status. Specifically, we're looking for the following:

- How many claims, on average, does a user have within the claim status tool? (likely backend data)
- What call center data can we collect for the claim status tool? What were people calling in about? (call center data)
- What are the most prevalent types of documents uploaded in the 'additional evidence' tool? (likely backend data)
- When users exit the CST, where do they go? (likely analytics)
- How do users enter the CST? What page(s) do they come from? (likely analytics)

We also need to be mindful of:

- What other useful data can we collect from the reports our data outputs we receive? Anything that will help us identify key opportunity areas within the claim status tool experience?

## Objectives or Key Results this is meant to further
- This should help us in gaining perspective and insight into opportunity areas as well as help us formulate hypotheses around CST usability issues.

## Tasks
- [x] Reach out to call center team to see if we can capture the amount of calls related to CST (this would likely be Chante Lantos-Swett, Kimberly Daniels)
- [x] Reach out to analytics team to see if we can aggregate data around user behavior - entrances, exits, drops (this would likely be Joanne Esteban or Nedie Recel)
- [x] Reach out to backend engineers to understand where we can get specific data points such as average number of claims (Would start with Anna Carey, Sarah-Jaine Szekeresh)
- [x] Gather data into spreadsheet or appropriate medium (google sheets, Mural board, etc)

## Acceptance Criteria
- [x] Data has been gathered (from reports, spreadsheets or other mediums)
- [x] Key data is pulled from reports so we can synthesize it (future ticket)

**Comment by kevinstachura** [comment]
Monthly contact center reports provided by Chante:

Dec: Provided as download

Jan: Provided as download

Feb: https://drive.google.com/file/d/1ytpv0UOdDrl8itRDiCYX7EOwm8dlStvX/view

March: https://drive.google.com/file/d/162Cn_srmNNQ3d7X62HIOOTdVrm2HSwQN/view

We can go through these reports and extract data related to CST.

**Comment by kevinstachura** [comment]
Nick W. created a summary of the call center data: https://docs.google.com/document/d/19TJLQ3-OyOcelIUH-l2C8XUVE0eiUmGrKL5U43oSDTw/edit?usp=sharing

**Comment by kevinstachura** [comment]
Put in a request for data from the insights team via ticket #9002
