### ISSUE TITLE
Enact changes from FDG testing

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#89604]
## Purpose
Take the takeaways from the synthesis step and enact them upon the guide

## Tasks
- [ ] make planned [alterations](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720821240181/b16bd8f2e8407a33b4c0752711245f1edba91499?wid=0-1722620446953)
- [ ] team review

## Acceptance Criteria
- [ ] changes are updated
- [ ] changes are visible on Platform Docs
