### ISSUE TITLE
Demo Q2 Survey at Demo day

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#89607]
## Purpose
Deliver presentation of results

## Tasks
- [x] share [presentation](https://docs.google.com/presentation/d/1ZC2PnM5Ug3cKSZSC9LlC3tkf3za5WOusMCE5lb72-zg/edit#slide=id.p1)
- [x] share out the Platform Metrics page in Slack to product managers

## Acceptance Criteria
- [x] demo delivered
- [x] Platform Metrics page shared out
