### ISSUE TITLE
[UX, FE] 10-10CG - Improvement: Remove days and times from 10-10CG pages

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89636]
## Background
Michelle Middaugh, PO for Facilities team, reached out to inform 10-10 team of a request (from VHA Digital Media) that the days and times currently listed in two places on the 10-10CG Introduction page and Confirmation page should be removed.  
I confirmed with our CG Stakeholders (Matt Brown) that we will need to remove the days and times from the CG support line details.

### References
- Introduction page - Section 2 and Need Help
     - <img width="312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2NlQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f20a09743af50f7105dd1ebd36142009b13d929d/image.png" alt="image.png" />

- Confirmation page - "What to do if you have questions now" section
     - ![image](https://github.com/user-attachments/assets/e84947cb-74bf-43de-9455-acf75cb4b6ee)

## Tasks
- [x] [UX] Update designs on Intro sections 2 and Need Help, Confirmation page - removing days and times from CG support line
- [x] [UX] Review with PM and FE to confirm content changes
- [x] [FE] Update content for Intro page sections to remove days and times
- [x] [FE] Review with UX and PM to validate changes and signoff before Prod deployment
- [x] [PM] Document validation and signoff
- [x] [FE] Launch to production

## Acceptance Criteria
- 10-10CG Introduction page & Confirmation page will be updated to list only the CG support line, and not specify days and times.

**Comment by hdjustice** [comment]
Failed to submit alert box and Successful submission page include these days & times

**Comment by hdjustice** [comment]
Screenshots updated to include all places that currently include the days and times with the CG support line

**Comment by jessicastump** [comment]
The source of truth design files have been updated removing the mentions of the day/time.
- [Introduction page](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=0-2342&t=XMh8fLLuSsEG5ooW-0)
- [Review page with fail to submit alert](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=0-4274&t=XMh8fLLuSsEG5ooW-0)
- [Confirmation page](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=0-4727&t=XMh8fLLuSsEG5ooW-0)
- [All pages - Need help footer](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2159-54971&t=XMh8fLLuSsEG5ooW-4)


Let me know if y'all want to review async or chat/walkthrough @longmd and @hdjustice :)

**Comment by hdjustice** [comment]
@jessicastump Thanks!  One question.  The Confirmation page in Figma has a "What you can do if your application is denied" section, but in staging, I am not seeing that, just the stuff above that.  Is this something new or maybe old? I don't remember seeing it.

**Comment by jessicastump** [comment]
That was added during the content updates for the July release... Recall flagging this in the [SME review docs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=1319-27691&t=XMh8fLLuSsEG5ooW-4) for them to review, but I can't find any mention from them about it in their feedback provided - ticket #84352

**Comment by longmd** [comment]
@jessicastump , just noting that the submission failure directs users to call the VA.gov help desk, not the Caregiver Support Line. So we can leave that alone. I will modify the other three spots.

**Comment by hdjustice** [comment]
@longmd thanks Matt, it sure does. I will update the ticket.

**Comment by hdjustice** [comment]
@jessicastump thanks, it is coming back to me now.

**Comment by jessicastump** [comment]
The screenshot above and the design files from the July updates don't align I just noticed. This is the alert updated after content/SME review:
![image (3)](https://github.com/user-attachments/assets/5377cd90-d137-465d-9ee5-2d0fc8a002a8)

**Comment by hdjustice** [comment]
Ok. @longmd - Keep working on what you already know.

**Comment by hdjustice** [comment]
@jessicastump - let's re-review the content updates and see what is not lining up

**Comment by longmd** [comment]
@jessicastump  / @hdjustice , the updates for what content is currently live is ready for review. [You can use this RI.](http://2dfcde62d582cf9d6d7c9dd8ffea484f.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg/)

**Comment by hdjustice** [comment]
Checking it out

**Comment by hdjustice** [comment]
- Confirmed Intro page is updated, no longer displaying the days & times for the CG support line
![image](https://github.com/user-attachments/assets/8b00013f-e9a1-45d1-88e4-8cb55efaef39)

- Confirmed Need Help section is updated, no longer displaying the days and times for CG support line
![image](https://github.com/user-attachments/assets/058be115-a32a-4785-902f-548138061161)

- Confirmed Confirmation page is updated, no longer displaying the days & times for the CG support line
![image](https://github.com/user-attachments/assets/6e08e4ad-33f4-4c31-864c-be19d4ad3891)
