### ISSUE TITLE
[CDP] VHA - One-thing-per-page/ Balance mockups (1 of 3)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#89638]
## Description

VHA (Copay) section should, for the most part, match VBA (Overpayment) section in Debt Portal in regards to IA. Since we are breaking up pages on VBA we should create mockups for the VHA (Copay) Section

## Tasks
- [x] Update VHA summary page
- [x] Update VHA Details page
- [x] Update VHA Resolve page
- [x] User flow created

## Acceptance criteria

- [x] [Mockups have been created in Figma](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=3212-30062&t=Cc0qv0ry4kJVHcpC-1)
- [x] [User flow created](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=3107-43147&t=Cc0qv0ry4kJVHcpC-1)

**Comment by Tom-Davis** [comment]
Closing as it is a duplicate

**Comment by mgleo** [comment]
User flow: https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=3107-43147&t=Cc0qv0ry4kJVHcpC-1

Mock ups (in progress): https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=3212-30062&t=Cc0qv0ry4kJVHcpC-1

**Comment by mgleo** [comment]
Added user flow to this ticket and increased points.
