### ISSUE TITLE
[CDP] VHA - Update cards

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#89640]
## Description

Cards displayed on the VHA (Copay) section should match updates made on the VBA (Overpayment) section in Debt Portal. Take the updated cards and have them match in production. 

## Tasks
- [x] Update [VHA cards on Figma](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=0-11158&p=f&t=W6wJNrDLlpb3slx6-11)
- [x] Update VHA cards on Production

## Acceptance criteria

- [x] [VHA cards updated on Figma](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=4361-49823&t=W6wJNrDLlpb3slx6-11)
- [x] Update VHA cards updated on Production

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
<img width="664" alt="Image" src="https://github.com/user-attachments/assets/f9b4355a-c895-49d5-a103-54d9d0267608" />

@OptionSelect Attaching a screenshot of the new card format here as well. 
The header of the card should be the location and the amount is moved below as "Current balance: $". 
The link on the card should read "Check details and resolve this bill"

**Comment by josephrlee** [comment]
@OptionSelect I can help with the validation and a11y testing on this ticket. Let me know once you have a PR ready for it and I can review it. It should match the [VBA cards pretty closely](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/combined-debt-portal/debt-letters/components/DebtSummaryCard.jsx).

**Comment by josephrlee** [comment]
Chatted with @OptionSelect yesterday and said that I would take this on since he's out on PTO. 

PR is ready for review from FE (@Dr-Pongo), and @denisecoveyduc has approved the content changes. Denise will also inform VHA SMEs of the minor copy edits.  

This is now in validate. 

cc: @mgleo @dhill802 @Tom-Davis

**Comment by josephrlee** [comment]
This has been completed and merged! 

cc: @Tom-Davis @dhill802!
