### ISSUE TITLE
CDP - Replace Mocked Payment History Data with API Response Data

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#89653]
## Description

Local data has been standing in place of API response, to aid in implementing the design, that should be the real data we use.

## Tasks
- [x] API response implemented and local mock payment history removed
- [x] Joe's TODO's added in previous PR fixed

## Acceptance criteria

- [x] API response implemented and local mock payment history removed
- [x] Joe's TODO's added in previous PR fixed

**Comment by OptionSelect** [comment]
This ticket was created as a follow up to [this one](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/85887)

Which merged [this pr](https://github.com/department-of-veterans-affairs/vets-website/pull/30863)

**Comment by mgleo** [comment]
@OptionSelect 
Questions (based on [Transaction code file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/Transaction_Code_Mappings.md))


What text will we display for:

- Other
- Reversal
- Write Off?

Is there initial transaction where we can display when the overpayment was first acquired?

**Comment by OptionSelect** [comment]
@mgleo 

Text Display Q:
Currently we don't handle them! For this initial implementation I think we were just going with the two cases shown here. Next steps would be to incorporate a switch that works with your transaction code file linked above I believe. Provided I understand ya correctly!
<img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUk5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e86846c2042ba20df6f18ce316e14fce5ea50ec/image.png" alt="image.png" />

Initial transaction Q:
Yes, in the screenshot of the PaymentHistoryTable.jsx file we have a hardcoded row that will always display the corresponding initial overpayment info <img width="985" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWc5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c612614e5c51304ee11985b3e051c563cf5b82e/image.png" alt="image.png" />

**Comment by mgleo** [comment]
Thanks @OptionSelect 
What will the user see if there is a transaction labeled Other, Reversal, Write Off? Will the transaction not show up at all?
I'm wondering if we can add some text to these 3 labels? Maybe even adding "Other, Reversal, Write Off" to the corresponding label? Is that possible?

Also, I'm seeing 04Q and 08Q on your first screenshot (thank you for sharing it). Are the other codes for decrease and increase being accounted for? The [Transaction Mapping file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/Transaction_Code_Mappings.md) shows several more codes. What will a user see if they get a code other than 04Q and 08Q?

cc @josephrlee

**Comment by OptionSelect** [comment]
1. Yep afaik we're returning null so nothing will show beyond the initial overpayment cell. We can certainly try, Ill mess with that while doing the dev here.
2. Again nothing if not having those codes I think lol. Its what it all comes down to displaying the text in the Description cell! Let us know what you want us to say for each code and we can do it! But it looked to me like some reported under the same so not sure.

**Comment by mgleo** [comment]
Thanks @OptionSelect -- It would be ideal to display all transactions, otherwise the total displayed won't add up. 

For now can all codes within the categories display text with the same name?
Other: "Other"
Reversal: "Reversal"
Write Off: "Write off"

**Comment by OptionSelect** [comment]
Let me finish hooking up the variables and get back to you on adding on!

**Comment by OptionSelect** [comment]
Worked with Megan on display text, replaced variables. PR is up.
