### ISSUE TITLE
Bump minReplicas and min EKS ASG Nodes for PACT

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89656]
A larger volume of traffic is expected for the PACT act which has a deadline of 8/14. We should pre-scale our pods and nodes accordingly.

## Tasks

- [x] Increase [EKS min nodes](https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#AutoScalingGroupDetails:id=dsva-vagov-prod-eks-node-group-main-dsva-vagov-prod-cluster;view=details) to 25 
- [ ] Increase minReplicas for Vets API pods

## Acceptance Criteria

- [x] Vets API server resources are overprovisioned in expectation of higher traffic for PACT

**Comment by ericboehs** [comment]
We actually ended up decreasing our maxReplicas as we were getting close to our max RDS connection limit. We also decreased our HPA target value so pods would scale sooner.
