### ISSUE TITLE
Implement splitting of CD prod deploy from CI

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#89655]
## Issue Description
Following on from ticket [#89577](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89577) we need to split out the CD production deploy from the CI workflow. This needs to be done in a way that allows platform to disable the workflow during code freezes or for any other necessary reason.

## Tasks
- [x] Implement the strategy from ticket [#89577](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89577)
- [x] Test to ensure CD deployments work as expected.

## Acceptance Criteria
- [x] CD deployment is now separated from the CI workflow and is able to be frozen as necessary.

**Comment by CBonade** [comment]
Plan:

In order to accomplish this, we are going to use a dispatch event in GitHub actions. This will allow us to conditionally trigger a production deploy of this build. The github.sha variable that's currently referenced in the deploy step will need to be passed as a workflow env variable as part of the dispatch payload, as currently it's referencing it on its current workflow. If an app is an isolated app build, it will then dispatch the production workflow with the set commit sha, and follow the steps as it does now.

This will accomplish a few things:

Keeps changes to a minimum
Removes clutter and complex logic from the CI workflow
Keeps the new workflow clean.
The new workflow will be named "CD Production Deploy" and will be able to be disabled from the GItHub UI the same way we disable the "Daily Production Deploy".

**Comment by CBonade** [comment]
Logic for this is implemented, however, it's still in testing currently.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/actions/runs/10582434559/job/29322113000

Successful CD deploy here

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/b54466b6-26d8-4f3a-896a-2bed2dda1173">

FE Dashboard seems to indicate it went to production successfully
