### ISSUE TITLE
Investigate Puma Backlog on Appeals & BGS

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89661]
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/89663

Appeals and BGS bulkheads experience Puma Backlog spikes throughout the day and especially around deploys.

![Screenshot 2024-07-30 at 15 51 10@2x](https://github.com/user-attachments/assets/68963f61-2230-4574-837b-9b6db06536de)

APM Traces, by service and resource
* for [vets-api-appeals](https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20container_name%3Avets-api-web%20operation_name%3Arack.request%20kube_deployment%3Avets-api-appeals&agg_m=count&agg_m_source=base&agg_q=service%2Cresource_name&agg_q_source=base%2Cbase&agg_t=count&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&historicalData=true&messageDisplay=inline&query_translation_version=v0&sort=desc&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&spanType=all&step=auto&top_n=10%2C10&top_o=top%2Ctop&view=spans&viz=sunburst&x_missing=true%2Ctrue&start=1722867051114&end=1722953451114&paused=true)
* for [vets-api-web-bgs-evss](https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20container_name%3Avets-api-web%20operation_name%3Arack.request%20kube_deployment%3Avets-api-web-bgs-evss&agg_m=count&agg_m_source=base&agg_q=service%2Cresource_name&agg_q_source=base%2Cbase&agg_t=count&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&historicalData=true&messageDisplay=inline&query_translation_version=v0&sort=desc&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&spanType=all&step=auto&top_n=10%2C10&top_o=top%2Ctop&view=spans&viz=sunburst&x_missing=true%2Ctrue&start=1722867051114&end=1722953451114&paused=true)
## Tasks

- [x] Research into why these bulkheads are slow (e.g. determine endpoints that are slow, decide if more/less threads/workers would be beneficial, determine is bin/is_ready isn't working for this bulkhead)
- [x] Create new issues for solution implementation if necessary

Tickets (also in Confluence doc below):
* #90444
* #90525
* #90526
* #90529
* #90530
* #90531
* #90532
* #90533
* #90534

## Acceptance Criteria

- [x] The reason for Puma Backlog spikes on Appeals & BGS bulkheads are known and documented ([here](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3363766282/Investigate+Puma+Backlog))
- [x] Issues are created to address resolutoin
