### ISSUE TITLE
[CST] Explore how to add more specific info about claim letters types to Claim Letters page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#89668]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to see exactly which types of letters the Claim Letters page supports
**_So that_** I know whether or not the letter I'm looking for is available without having to download letters and open them up

---
## Background Context

There are a variety of ways we could do this: 
- Add these details in text to the top of the Claim Letters page
- Add a selector to be able to toggle letter types in the letters list

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
Explore variations options and come up with a proposal

### Enablement team (if needed)
@juliaelman 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Explore variations options and come up with a design proposal_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _AC_
- [ ] _AC_
- [ ] _AC_
