### ISSUE TITLE
Investigate Backlog on vets-api-hca, itf, and web bulkheads

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#89663]
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/89661

Vets API Web Bulkhead experiences Puma Backlog spikes throughout the day and especially around deploys.

![Screenshot 2024-07-30 at 15 51 10@2x](https://github.com/user-attachments/assets/68963f61-2230-4574-837b-9b6db06536de)

## Tasks

- [ ] Research into why this bulkhead is slow (e.g. determine endpoints that are slow, decide if more/less threads/workers would be beneficial, determine is bin/is_ready isn't working for this bulkhead)
- [x] Determine if db-migrate is causing a backlog
- [ ] Create new issues for solution implementation if necessary

## Acceptance Criteria

- [ ] The reason for Puma Backlog spikes on Vets API Web bulkhead is known
- [ ] Issues are created to address resolution

**Comment by stevenjcumming** [comment]
db-migrate is _not_ causing backlog issues

**Comment by stevenjcumming** [comment]
The issue appears to be a timeout issue. Which in some cases can be updated but other require more effort to reduce the backlog, such as moving to background jobs.
