### ISSUE TITLE
Epic | Profile | Maintenance Periods (Phase 2 - UI Component to Service Mapping) 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#89678]
## Current Status 
`Work In Progress` 

> [!CAUTION]
> Downtime in 2023 was Nov 18th - we need to be prepared for roughly a similar downtime period this year

## Background 
This is a follow on ticket to our work completed in 2023. We had a COLA adjustment to rapidly prepare for and created hard coded alerts with feature toggles. 
- #68877 

We then enhanced that work to create a stronger process using pager duty. This follow on epic is to:
1. confirm we have complete code coverage within the profile 
2. Add missing code coverage 

The automation of maint. windows will be in Epic #92169
3. create a utility to automate the creation of maintenance windows within pager duty 

## Important Artifacts 
- [spreadsheet for mapping/coverage check](https://docs.google.com/spreadsheets/d/1ApEzV8z7NGXs3kNw2HSCjTAb96b4R26Cw9E0TyASw14/edit?gid=39041782#gid=39041782)

## Tasks 
```[tasklist]
### map service to FE features / components
- [ ] #82051
```

```[tasklist]
### Map Components to Services 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92103
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92106
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92107
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92108
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92109
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92110
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92111
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92112
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92113
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/92114
```

**Comment by mtcA6** [comment]
It appears this work was completed based on BE engineers comments on the underlying tickets, closing this wokr out
