### ISSUE TITLE
[Design] Create mockup for 526 content (info) page

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#8967]
## User Story or Problem Statement
As a UX Designer, I need to create a mock up for public websites so they have a visual of what we're thinking might improve the [526 content page](https://www.va.gov/disability/how-to-file-claim/) user experience. 

## Goal
_A completed mock up of the [526 content page](https://www.va.gov/disability/how-to-file-claim/)_

## Objectives or Key Results this is meant to further
- Prep the website content user experience for the launch of the BDD form and original claims - intended to go live in late June.

## Tasks
- [ ] Create Sketch mockup of page
- [ ] Upload page to Invision prototype
- [ ] Comment the Invision prototype link to the public websites intake request form #8668

## Acceptance Criteria
- [ ] The above tasks have been accomplished

**Comment by kevinstachura** [comment]
Mockup is complete and can be located here: https://vsateams.invisionapp.com/share/CPXAPZRWHD8#/418108118_Information_Page_-_526
