### ISSUE TITLE
[QA] 10-10EZ - TERA Improvements: Testing Gulf War locations question to display only applicable locations

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89689]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. To improve this experience, we are going to add logic to the Gulf War locations question, based on the time period for each location, so that we are displaying only those locations that were in effect after the Veteran's birth date.

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By displaying the Gulf War locations question based on time period, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)
- [Figma designs for content](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)

## Tasks
- [x] Create test cases based on designs and user flow
- [x] Perform testing on the Gulf War locations question changes
- [x] Review with the team/PM to confirm expected behavior
     - PM signoff required to be documented in comments below
- [x] QA results and signoff required to be documented in comments below
- [x] Inform team that the effort has completed QA and is ready for launch

## Acceptance Criteria
- The Gulf War location question displays only those applicable locations based on time period compared to the Veteran's birth date.
- The updates are ready for launch

**Comment by longmd** [comment]
[Here will be the link for the Review Instance.](http://5541c2b787899b4696adde7a19d6817a.review.vetsgov-internal/health-care/apply-for-health-care-form-10-10ez/) It is still building. I will follow up when its ready.

**Comment by longmd** [comment]
@allanto-ah , the Review Instance is live and good to go. You could, in theory do all the branching on there, since it has everything but the content edits discussed in the other ticket.

**Comment by allanto-ah** [comment]
@longmd For the service date section of the gulf war questions, did we want to add any date validation to the fields? Currently I can enter in a service date before the gulf wars and continue

![Image](https://github.com/user-attachments/assets/bd5ae250-9e39-47d4-b495-a7ce156a2c06)
![Image](https://github.com/user-attachments/assets/ba397f87-cbcb-4763-b8d0-cc9d435f4a5c)

**Comment by hdjustice** [comment]
Agreed, that is out of scope for this work.  We can talk about it later, and the pros/cons of restricting that input.

**Comment by allanto-ah** [comment]
@longmd Looks like the Review Instance stopped working for me. Is it still working for you? If not, are you able to build a new one? Thank you!

**Comment by longmd** [comment]
@allanto-ah , the link has been updated in my comment above.

**Comment by allanto-ah** [comment]
### Issue 1

For the 2001 Gulf War question, users that are not 15 years old yet sees this question. Is that expected? For example, I entered in today's date as the birth date and I'm still seeing this question. 

https://github.com/user-attachments/assets/c8cd38dd-f714-4993-b385-a468da9009d6

**Comment by allanto-ah** [comment]
Environment: RI 

Verified that the TERA Gulf War locations question is working as expected. Content looks good and matches Figma. There was one last thing that Matt has fixed and will need to be verified, but everything else is good to go
