### ISSUE TITLE
Atlas MVP: Document current technical functionality of the Atlas tool

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89692]
## User Story
As the managers of the Platform Atlas tool,
We need to understand the current technical functionality of Atlas
So that we can determine next steps for the Atlas tool. 

## Issue Description
We have done exports of the current Atlas tool ([Product Directory Export](https://docs.google.com/spreadsheets/d/1KHVUtBrEi0UCEtkw6OMwwo0Lc_GpRpi7/edit?gid=705694569#gid=705694569)) and ([Atlas Export](https://docs.google.com/spreadsheets/d/180IyCbsulU0_zFtVw33xFZX2wZ_yNByk/edit?gid=433470585#gid=433470585)), and now we need to establish the current technical functionality of the tool.

We need to find the original requirements for this tool, and determine which of those functional requirements are met in the current Atlas tool, and which were not prioritized in the original MVP work.

## Tasks
- [ ] Determine original requirements of Atlas
- [ ] Determine current technical functionality of Atlas
- [ ] Document current technical functionality

## Success Metrics
We will have a better understanding of the tool and it's current functionality.

## Acceptance Criteria
- [ ] We will have a better understanding of the current technical functionality for the Atlas MVP tool. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by RachalCassity** [comment]
Possible solutions:
1) Add documentation to README
2) Add an about page aka "What is Platform Atlas?"

Why was this created? What is its purpose? How is it maintained? Potential future capabilities?
What teams are currently using Atlas and how are they using atlas? What repositories contribute to Atlas and how are the repos contributing?
