### ISSUE TITLE
[QA] 10-10EZ - TERA Improvements: Testing branching logic based on Veteran's birth date

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89694]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. 

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By introducing branching logic to the TERA questions, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060)
- [Figma designs for content](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3206-87867)

## Tasks
- [x] Create test cases based on designs and user flow
- [x] Perform testing on the branching logic of TERA questions that display based on birth date
- [x] Review with the team/PM to confirm expected behavior
     - PM signoff required to be documented in comments below
- [x] QA results and signoff required to be documented in comments below
- [x] Inform team that the effort has completed QA and is ready for launch

## Acceptance Criteria
- The Toxic Exposure questions display based on time period compared to the Veteran's birth date.
- The updates are ready for launch

**Comment by longmd** [comment]
@allanto-ah , this is ready for QA on staging. The feature is turned on there. We will be QAing everything minus any content-related or anything related to the Gulf War questions, as those have their own separate efforts. Let me know if you have any questions.

**Comment by allanto-ah** [comment]
### Issue 1
For the "Cleanup or response efforts" page, based on the dates in the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717425866304/ada07b73aa758ef4d41c0d287a0ed5f2850afd8f?sender=ud5c82d652d231345efaf6060), users with a birth date between Jan 1 1966 and Jan 31 1966 shouldn't be seeing this page, but they currently are. Starting on Feb 1 1966, users are not seeing this question as expected. 

I might be messing up my calculations, so let me know if I'm getting the dates wrong

**Comment by allanto-ah** [comment]
### Issue 2

For the "Agent Orange" page, based on the dates in the Mural, users with a birth date between Aug 1 1965 and Aug 31 1965 shouldn't be seeing this page, but they currently are. Starting on Sept 1 1965, users are not seeing this questions as expected.

As with the previous one, let me know if I'm getting the dates wrong

**Comment by allanto-ah** [comment]
### Issue 3

For the "Operations" page, users (no matter the birth date) seem to always see this question. Is that expected?

https://github.com/user-attachments/assets/a4dab4ac-2657-4d0d-8438-25a30c9ceea0

**Comment by longmd** [comment]
1. Issues 1 & 2 - Same issue for both. Updated date formatting to be a string, and not provided digits, which were one month off with that value being 0-based in JavaScripts date functions. Strings match the format of the birthdate string that has been passed in. 
3. Issue 3 - Treating this the same as we did the post-9/11 question --- no need to do an end constriction as the use case is unlikely. 

Both issues tested and validated during paired session today.

**Comment by allanto-ah** [comment]
Environment: RI

Verified that this is working as expected. TERA questions are shown to the user based on their birth date. All the issues have been fixed and content is matching Figma.

**Comment by longmd** [comment]
@hdjustice , the TERA branching effort is ready for final PM signoff. We have QA signoff on all items, with those being in staging behind the feature flag. The flag is fully enabled in staging and ready for final review.

**Comment by hdjustice** [comment]
Reviewed TERA updates and recent changes against the test cases.  All pages are appearing or not appearing as expected based on birth date.  This is good to go!  

Next step: Review release plan with the team and prepare to launch to production!
