### ISSUE TITLE
[DevOps] Read LoROTA secret directly from environment variable rather than through Secrets Manager.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89695]
## Description

See department-of-veterans-affairs/lorota#64.

This can just be populated directly, which should reduce latency and complexity.

## Tasks
- [x] [DevOps] Update CF IaC on `master` to populate new environment variable with value of secret.
- [x] [DevOps] Update TF IaC on `main` to populate new environment variable with value of secret.
- [x] [DevOps] Update references to and uses of environment variable within Lambdas.

## Acceptance Criteria
- [x] CF IaC uses secret directly.
- [x] TF IaC uses secret directly.
- [x] Lambdas use new environment variable and use secret directly rather than Secrets Manager API.
