### ISSUE TITLE
Migrate Feature Request to new Projects version 

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#89693]
## Purpose
Github is sunsetting the existing Projects version.  We must migrate to the new version.

## Tasks
- [ ] Step through migration process
- [ ] update any links to the old board in Confluence
- [ ] update any links to the old board in Platform docs
- [ ] verify that change is live after PCT updates the site

## Acceptance Criteria
- [ ] board is accessible in Confluence links
- [ ] board is accessible on Platform Docs
