### ISSUE TITLE
FE | MHV&DS Logon Retirement | Updated Dates for Credential Requirements

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#89716]
## Background
Based on an email sent on 7/17/2024 there are new dates for the credential retirement. We'll need to revisit and update the designs set out here:

[#73358](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73358)
[...]
In 2025, VA will transition from four online sign-in account options (Login.gov, ID.me, My HealtheVet, and DS Logon) to two sign-in account options: Login.gov and ID.me accounts. Veterans will be able to use either of these two options to sign in to VA.gov, VA mobile applications, or other VA online services.

Veterans and other beneficiaries will no longer be able to use usernames and passwords for My HealtheVet after Jan. 31, 2025, or DS Logon after Sept. 30, 2025. After these deadlines, Veterans who have not yet transitioned will still be able to access their data and resume managing their benefits and services online once they have created their new account.
[...]
[Updated designs can be found here for the alerts on the Account Security page and Contact Info Page](https://www.figma.com/design/OmY3qqcBnK043nnnUvlsjh/%2373358---Auth-Exp-Credential-Retirement-Phase-1?node-id=1-2509) - previous story was #89716

Please Slack @danturner with any questions

## Tasks
- [ ] Update text to match the text in the green areas with the lock icon
- [ ] Make sure the elements flow correctly after the text change

## Acceptance Criteria
- [ ] Get sign-off on design and text from @twoangstroms 
- [ ] Changes are pushed (and still behind the feature toggle)

**Comment by mtcA6** [comment]
## What happens/ what is the problem 

### Copy as it sits currently 
"Starting December 31, 2024, you’ll no longer be able to sign in with your [credential] username and password. You’ll need to use a verified Login.gov or ID.me account to access your profile.

If you don’t have one of these accounts, you can create one and verify your identity now."


### Copy from #89716
"SAfter January 31, 2025, you will no longer be able to sign in with your [credential] username and password, or use DS Logon after September 30, 2025. You’ll need to use a verified Login.gov or ID.me account to access your profile.  

If you don't have one of these accounts, you can create one and verify your identity now."

### if we use this copy with DS Logon user we repeat "DS Logon" 
"After January 31, 2025, you will no longer be able to sign in with your **_DS Logon_** username and password, or use DS Logon after September 30, 2025. You’ll need to use a verified Login.gov or ID.me account to access your profile.  

If you don't have one of these accounts, you can create one and verify your identity now."

### if we use this copy with MHV user we tell the user about a logon credential that is irrelevant to them
"After January 31, 2025, you will no longer be able to sign in with your **_My HealtheVet_** username and password, or use DS Logon after September 30, 2025. You’ll need to use a verified Login.gov or ID.me account to access your profile.  

If you don't have one of these accounts, you can create one and verify your identity now."


# Proposal 
The alert is already built to inject the name of whatever credential the user logged in with. We should maintain that behavior and change the copy based on the respective login credential service. 

- If a user is logged in with MHV > inject the credential name and pair that w/the January 31st retirement date
- If a user is logged in with DS Logon > inject the credential name and pair that w/the September 30th retirement date

## Proposed copy for account security page LOA3
### MHV user 
"After January 31, 2025, you will no longer be able to sign in with your My HealtheVet username and password. You’ll need to use a verified Login.gov or ID.me account to access your profile.  

If you don't have one of these accounts, you can create one and verify your identity now."

###  DS Logon user 
"After September 30, 2025, you will no longer be able to sign in with your **_DS Logon_** username and password. You’ll need to use a verified Login.gov or ID.me account to access your profile.  

If you don't have one of these accounts, you can create one and verify your identity now."


<details><summary>screenshots for additional context</summary>

### Current design 
![image](https://github.com/user-attachments/assets/49c48192-74c7-42c0-ade4-c61de80c5cb2)

The [credential] renders based on what each respective user has logged in with. 

### Current Build for a User w DS Logon 

![image](https://github.com/user-attachments/assets/92b66fa6-fd68-49ec-9a76-d3aa40368b93)

### Current Build for a User w/ MHV Logon 
![image](https://github.com/user-attachments/assets/70bc6463-a53e-4332-abb2-6c7f8c2660af)

</details> 


## Proposed copy for contact information LOA3
### we can scrap this for this round 
reading the comments on the figma file it looks like Adam and Liz arrived at the conclusion to not build this one and were going to check with Samara. I checked the FE ticket and we did not add the[ contact info ](https://www.figma.com/design/OmY3qqcBnK043nnnUvlsjh/%2373358---Auth-Exp-Credential-Retirement-Phase-1?node-id=1-1587&t=O9deW02b2gDZFsOD-4)

## Proposed copy for account security page LOA1
###  DS Logon user 
[...]If you don't have one of these accounts, you can create one and verify your identity now. After September 30, 2025, you will no longer be able to sign in with your DS Logon username and password.[...]
### MHV user 
[...]If you don't have one of these accounts, you can create one and verify your identity now. After January 31, 2025, you will no longer be able to sign in with your MyHealtheVet username and password.[...]

## Proposed copy for direct deposit alert 
we should probably add this [to the figma file ](https://www.figma.com/design/OmY3qqcBnK043nnnUvlsjh/%2373358---Auth-Exp-Credential-Retirement-Phase-1?node-id=1-1587&t=O9deW02b2gDZFsOD-0)

### Current alert copy
Verify your identity with Login.gov or ID.me to change your direct deposit information online
Before we give you access to change your direct deposit information, we need to make sure you’re you—and not someone pretending to be you. This helps us protect your bank account and prevent fraud.
If you have a verified Login.gov or ID.me account, sign out now. Then sign back in with that account to continue.
If you don’t have one of these accounts, you can create one and verify your identity now. Starting December 31, 2024, you’ll no longer be able to sign in with your DS Logon username and password.
[Create an account with ID.me](http://127.0.0.1:3000/v1/sessions/idme_signup_verified/new)
[Create an account with Login.gov](http://127.0.0.1:3000/v1/sessions/logingov_signup_verified/new)
Note: If you need help updating your direct deposit information, call us at 800-827-1000 (711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

###  DS Logon user 
[...]Starting September 30, 2025, you’ll no longer be able to sign in with your **_DS Logon_** username and password.[...]

### MHV user
 [...]Starting January 31, 2025, you’ll no longer be able to sign in with your **_My HealtheVet_** username and password.[...]
 
 ## Design updates 
@twoangstroms can you create a new ticket to update the designs to use the details highlighted above and add in the direct deposit alert? The FE is injecting whatever credential type the user has logged in with into that `[credential]` field in the design. 
 
cc: @ACParker89 @asiisii

**Comment by mtcA6** [comment]
@twoangstroms thoughts on my last message?

**Comment by twoangstroms** [comment]
@mtcA6 (Wish the system that emails me notifications had a link to the ticket...)

If I'm understanding this, there are a few things going on:

1. The [credential] is not only a variable (I got that on initial exposure to the ticket), but it means that there is more than one credential name that this variable resolves to (that I did not know). 
2. Ergo, we need two sets of copy. One for when the credential is DS Logon and one for when it is MHV.
3. Additionally, there's the previously skipped-over info about direct deposit that needs to be added.

Is that correct?
