### ISSUE TITLE
Puma Monitor Tuning

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89717]
## User Story
As the managers of the Puma servers, 
It is important to have the optimal configuration in place for Puma servers
So that Vets-API availability remains consistent and high-functioning for those who utilize the APIs. 

## Summary
We have a monitor, [[Prod] [EKS] Puma Backlog](https://vagov.ddog-gov.com/monitors/116657), that notifies us when the Puma backlog is over a threshold for an amount of time. We need to tune these monitors so that they are running accurately.

There is a [recurring scheduled downtime](https://vagov.ddog-gov.com/monitors/downtimes?id=7cab24d2-82fa-11ee-a5b1-da7ad0900007&sort=-start_dt). The alert gets muted every day from 3-4 ET. Kyle set that up because that was a predictable time of day that it would trigger the alert. 

## Tasks
- [x] Tune the Puma monitors
- [x] Make new tickets based on findings. Or if the fix is small, implement it. 
- [x] Document any specific Puma tuning work and indicate where it is stored

## Success Metrics
- [x] Puma monitors have been tuned

## Acceptability Criteria
- [x] Puma monitors have been tuned and documentation is available for what was done, when, and by whom.
- [x] New work is ticketed for future Sprints

**Comment by LindseySaari** [comment]
Having adjusted the threads to 8 today, the puma backlog is looking ok. It seems that 30 is still appropriate over a 15 minute span. We did see a small spike during the deploy, in which was quickly resolved (most likely after HPA caught up). Eventhough the spike went above 30, it never sat above the alert level for for more than ~40 seconds. [Uploading... Screenshot 2024-08-01 at 1.59.30 PM.png]

**Comment by jennb33** [comment]
8/5 update: monitoring Puma backlog, working through Postgres iteration, latent endpoints. Trying to possibly bulkhead some of the endpoints to address the slow query situation.

**Comment by jennb33** [comment]
8/7 update: this is associated with the PgHero work as well. We reached out to Steve Albers regarding the slow queries. This wasn't a priority beforehand, but because of the ongoing middle of the night alerts that wake people up, we need to address it.

**Comment by rmtolmach** [comment]
- In progress https://github.com/department-of-veterans-affairs/vets-api/pull/17934

**Comment by LindseySaari** [comment]
Continuing to monitor backlog, HPA, unavailable and the PG connections
