### ISSUE TITLE
[UX] 10-10EZR Overview Document and Resources for Renata

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#89727]
## Issue Description
A new member is joining the team, it would be helpful to give them a document to reference while they adjust to the team and the work we're doing.

---
## Tasks
- [x] Generate an overview document of EZR (summary, descriptions, and major decisions).
- [x] Provide resources such as Mural links and helpful Github locations.
- [ ] Work with Renata to walk through any include any additional information.

## Acceptance Criteria
- Document is clear and helpful for Renata to use as a reference material.

**Comment by IMHieuVo** [comment]
https://docs.google.com/document/d/1Kygh67SaCwPKqVCWvrIkGm8ii2dC8qSS7gWb53mmtRE/edit?usp=sharing
