### ISSUE TITLE
0781 post-concept test designs

### ISSUE THREAD

**Issue by jinaryu** [department-of-veterans-affairs/va.gov-team#89782]
### Design considerations based on research findings
[Link to findings](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/6?filterQuery=assignee%3A%40me+sprint%3A%22Sprint+35%22&visibleFields=%5B%22Title%22%2C%22Status%22%2C114028471%2C114028474%2C114028472%2C114028473%2C%22Linked+pull+requests%22%5D&pane=issue&itemId=69137821&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=114028471)

**What's locked in**

- [x] Keep blue support alerts
- [x] Break out the evidence portions of 0781 into 526ez evidence section, while keeping rest of 0781 questions in additional forms 
- [x] Ask SC questions for 0781 conditions
- [x] Introduce the 0781 in additional forms step (rather than conditions)

**What's still in flux**

- [x] How to streamline 0781 and 526 evidence (learned on 8/21 from Kayce White that there will be an update to the 526 that matches the 0781 section!)
- [x] How to ask SC questions for 0781 conditions

**Other notes**

- How to handle review & submit for additional forms (look at example of additional disability benefits page)

### Tasks

- [x] Design wireframes
- [x] CAIA review 
- [x] OCTO review
- [x] VBA review

### Acceptance Criteria

- [x] Completed design
- [ ] Reviewed by CAIA, OCTO, and VBA
- [x] Schedule midpoint review

**Comment by jinaryu** [comment]
**Support page to-do**
Opportunities for improvement include:

- [ ] Clarifying if/when links will take users out of the form flow
- [ ] Looking into the most familiar phone lines (one Veteran expressed concern that older Veterans would be 
- [ ] looking for a toll-free 800 number and might not be familiar with the 988 number)
- [ ] Bucketing resources to clarify which are standard emergency response such as 911

**Comment by jinaryu** [comment]
**More to-do**

- [ ] figure out how to show SC question responses on first page of traumatic experiences L&L
- [ ] embed 0781 supporting docs 
- [ ] embed 0781 treatment details
- [ ] moving additional disability benefits questions to additional forms step - check if this is in scope

**Comment by jinaryu** [comment]
8/20 sync with @shannonkford and @nnicholas7 

Shannon's sketch: 

- integrating 0781 screener question into SC question (for mental health conditions)
- if it's free text, then we ask them
- 0781 not relevant to secondary SC
- we could test if screener idea messes people up, and if it does then we could punt back to asking in step 2
- if they say - yes it's a traumatic event show add experiences screen, and once they get to 0781, prefill?

Are there other forms with a screening process?

- deprecated wizard pattern 

Looking at figma

- you could have one event linked to multiple conditions
- select condition that maps to experience
- we can't get away with them not filling out initial SC questions in step 2: conditions
- can we see what people are writing in SC questions for PTSD? 
- ask VBA: what are examples of SC for these types of conditions that aren't traumatic experiences?     

Summary

- avoid writing same thing twice
- but its not that big of a lift to write it twice 

Treatment facility

- JP: it's nice to consolidate treatment cards; feels weird to split out supporting docs; feels it should be split out 
- can we step them through every type of evidence and decide if you want to add more? (do you have other evidence? do you have VA medical records? do you have private records?) - this isn't a huge change 
- don't have to worry about not seeing 0781 
- facility type becomes required, combine treatment into one? 
- even combining 0781 supporting docs with 526 supporting docs? 
- maybe we don't have to write that content of how to educate on evidence. it's more integrating types of evidence 
- also thinking about in progress forms with these step 3 changes

**Comment by jinaryu** [comment]
**Action items from 8/21 0781 update meeting**
[Notes](https://docs.google.com/document/d/10edqeirvqZvujfTjj4XX78n5b8v_J6qhQZFFm8UMcCc/edit)

- [ ] change experiences back to event
- [ ] change corpsman example to "corpsman on medical ship in combat area" 
- [ ] add combat event example and have that be in hint text 
- [ ] change harassment back to assault
- [ ] revise USS example to "U.S.S. Repose"
- [ ] change time frame dates back to what's on the paper form
- [ ] change "buddy statement" to just "statement"

**Comment by jinaryu** [comment]
Roadmap:

- [ ] by EOW 9/6, finalize prototype C and send out for review
- [ ] by 9/13, get feedback from team and Shannon
- [ ] schedule check in with kayce week of 9/23
- [ ] schedule midpoint review for week of 9/30

**Comment by jinaryu** [comment]
Finished [proto C](https://www.figma.com/proto/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?page-id=6476%3A97460&node-id=6872-66391&node-type=FRAME&viewport=3825%2C2619%2C0.36&t=Ew4Km0l1Vdq0M3Fk-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6872%3A66391), sent out for review

**Comment by rubensun** [comment]
Reviewed proposed flow changes with @kristinoletmuskat
We're continuing to make adjustments to the **Supporting Evidence sections** and exploring alternate treatments to the **multi-prompt list and loop patterns** to eliminate preceived "foreshadowing" and "confirmation fatigue".

**Comment by jinaryu** [comment]
Finished [prototpying](https://www.figma.com/proto/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?page-id=7770%3A111546&node-id=7817-294216&node-type=frame&viewport=105%2C1959%2C0.03&t=4yUTAQfewklr3cBG-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=7817%3A294216&show-proto-sidebar=1) the most recent version

Notable changes:

- consistent multiple responses pattern, using button CTA instead of static question as an anchor
- splitting up VA and private medical records for sake of simplicity in data collection, since date fields are different for both 
- updated all footers to the "VSO" version (more updated than currrent "Benefits" version)
- updated "forms to complete" cards 

More detailed changelog [here](https://docs.google.com/document/d/1NWX2uRKO_QXthEoLx6hPyOzs7rMb8zQuwlEncqhCS4E/edit)

cc: @rubensun

**Comment by jinaryu** [comment]
**Wrap up tasks (to be done before midpoint on 10/3)**

- [ ] Map optional and required fields for 0781 and evidence (526 treatment, 4142)
- [ ] Collect character counts from PDF form (figure out overflow situation.. are we able to just have all overflow go to the additional remarks section of 0781?)
- [ ] Get feedback from Kayce White (VBA) on 9/23
- [ ] Add annotations 
- [ ] Resolve outstanding Figma comments

**Comment by rubensun** [comment]
We also need to collect and incorporate any final content feedback from CAIA.
We currently have a touch-base scheduled with @katherine-fung on 9/24.

**Comment by rubensun** [comment]
Kayce White and Abigail Werner (VBA) provided input into a few pieces of copy adjustments marked as comments in the figma prototype. Overall, Kayce and Abigail have expressed alignment with how we’re approaching the form overall and how we’re referencing physical forms throughout the flow.

**Comment by jinaryu** [comment]
Rough timeline

**9/23-27**
By EOD 9/25: send out Figma for CAIA content review (ask how long they need.. I’m thinking setting a due date of 10/11?)
By EOD 9/25: send out prototype C to Shannon for review
9/27: During biweekly design sync, talk through prototype C with Shannon (hopefully get sign off)

**9/30-10/4**
10/3: midpoint review
Data mapping 
Confirm  which fields are optional vs. required
Character counts
Overflow?

**10/7-10/11 (SF out)**
make changes as needed from midpoint
add accessibility annotations

**10/14-10/18 (SF out)**
Target: handoff to engineers, meet as needed 

**10/21-10/25**
Target: handoff to engineers, meet as needed 

**10/28-11/1**
Buffer week in case things take longer than expected

**Comment by jinaryu** [comment]
10/1 from Emily:

- generally speaking, overflow creates more work, but we'll have to do it anyways down the line
- not doing overflow is an MVP approach
- SF - we typically don't try to figure out how much fields based on paper form, take out character counts

Action items:
- [ ] Jina - take out character counts. 
- [ ] Jina - sync with Lisa to determine overflow approach

**Comment by jinaryu** [comment]
**Note:** current 0781 doesn't show up in BDD flow and that is intentional because active service members are asked about this during their exit interview/exam, so they don't need to see it in our form. this should also be the case for new 0781 ([slack thread](https://dsva.slack.com/archives/C053UDWMH7U/p1728501724249339))

**Comment by jinaryu** [comment]
I have finished the [0781 designs with annotations.](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9250-77233&t=b7wRBeUmCJ2mR0Dq-1) We still have _some_ pending items that @rubensun will take the lead on finalizing.

**Comment by rubensun** [comment]
Current gaps to fill

- [ ] Indirect actions impacting 0781 opt-in (removal or deselection of mental health conditions)
- [ ] Handling of documents uploaded post opt-out
- [ ] Placement of MST resources content block

**Comment by kylesoskin** [comment]
@rubensun will update and close out, creating a new ticket linking to this if related and required.

**Comment by rubensun** [comment]
Moving forward we'll be each individual design item in separate tickets and move them through "exploration", "design review" and "content review".
