### ISSUE TITLE
Store Submitted Form Status/Metadata

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#89790]
## Value Statement

**_As a_** Veteran

**_I want to_** be confident that my submission is monitored

**_So that_** any issues with their submission will be addressed in a timely manner

---

## Background Context
As a followup to #84332, we want to store form data/metadata related to the status of submitted forms that have been passed downstream. The data here can then be used for other processes, such as notifying Veterans in the event there is an issue with their form.

- Currently, once the NOD/CS/HLR form is submitted, it is passed downstream. If something happens to the submission downstream, we rely on a daily email or logs to notify that there was an issue. This can cause items to be missed.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Update the process created in #84332 to store relevant metadata based on the form status downstream

## Acceptance Criteria

- [ ] The process updates the form records with any changes

### Enablement team (if needed)
@ member of team

## Out of scope

- Polling/Status determination, it's handled in #84332
- The deletion/long term storage of the submission, handled via #84348 

## Tasks

- [ ] Design a job that runs periodically, checking the status of any in progress submission
- [ ] Update any submissions who's status has changed
- [ ] Determine if the submission was a success and mark it for future deletion/storage

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
PR to add metadata column: https://github.com/department-of-veterans-affairs/vets-api/pull/17951

**Comment by dfong-adh** [comment]
Verified in staging, will enable in production tomorrow.

**Comment by dfong-adh** [comment]
Enabled in production.
