### ISSUE TITLE
Migration discovery to move away from Virtus Gem

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89816]
## User Story
As the Managers and Developers on the VA Platform, 
We need to perform discovery migrate away from the discontinued "Virtus Gem" that is heavily used on Vets API,
So that our tools and programs continue to function properly. 

## Issue Description
We noticed on Wednesday, 7/31/2024, that the [Virtus Gem](https://github.com/solnic/virtus) (used heavily in Vets API) has been discontinued. We need to migrate use from Virtus Gem to either **dry-types**, **dry-struct** and/or **dry-schema**, which we believe has been integrated in Vets API. 

## Tasks
- [ ] Review which of the three suggested Gems (**dry-types**, **dry-struct** and/or **dry-schema**) should be used to migrate from Virtus Gems.
- [ ] Is there a better or more suitable Gem to use? What are Developers doing since Virtus Gem was discontinued?
- [ ] Document the discovery process and share documentation in this ticket.

## Success Metrics
A complete migration of Virtus Gems usage in Vets API to one (or more) of these: **dry-types**, **dry-struct** and/or **dry-schema**.

## Acceptance Criteria
- [ ] There is a clear path forward for which new Gem to migrate to, from Virtus Gem
- [ ] Documentation is complete for migration
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
Closing. Steven is currently working on this and has a custom lib here: https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/vets
