### ISSUE TITLE
Clean up How to complete SR guidance

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#89815]
## User Story

As a Governance Team member, I want to have clear guidance about how to complete a Staging Review or Design System Staging Review.

Assignee: @erinrwhite 
Peer Reviewer: @allison0034 

## Description

While working on #87904 the team realized that the `How to complete a staging review` page is in need of significant restructuring and editing. Some of the guidance, including how to cancel a touchpoint, should be placed elsewhere in our operational documents. There is also some duplication of content, and the organization of the page is not clear. 

There's an analogous page for Design System Staging Reviews that could also benefit from updates and reorganization.

## Impacted Artifacts

- [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)
- [How to Document Findings for a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572189697/How+to+Document+Findings+for+a+Design+System+Staging+Review)

## Draft pages
- [DRAFT How to document findings for staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3510108161/89815+-+Erin+-+How+to+document+findings+for+Staging+Review)
- [Draft How to document findings for design system staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3510140929/89815+-+Erin+-+How+to+Document+Findings+for+a+Design+System+Staging+Review)
- [Draft NEW Staging Review - Verify artifacts and follow up with VFS team](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3524198402/89815+-+Erin+-+Staging+Review+-+Verify+artifacts+and+follow+up+with+VFS+team) operational docs to go alongside scheduling, during and after meeting documents

## Tasks
- [x] Update structure of pages to better match workflow for completing a Staging Review or Design System Staging Review
- [x] Update pages' content to make sure it is up to date and accurate
- [x] Remove duplicate information
- [x] Where possible, align the format/outline of content to be similar on both pages
- [x] Move operational documentation about cancelling the touchpoint to the parent Staging Review section alongside other moderator documentation

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] How to complete a Staging Review page content is accurate and clearly organized 
- [x] How to complete a Design System Staging Review page content is accurate and clearly organized 

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This work wasn't able to be picked up this sprint due to change in priorities with the introduction of Architecture Intent. This work will move into the next sprint.

**Comment by erinrwhite** [comment]
[DRAFT How to document findings for staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3510108161/89815+-+Erin+-+How+to+document+findings+for+Staging+Review)
[Draft How to document findings for design system staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3510140929/89815+-+Erin+-+How+to+Document+Findings+for+a+Design+System+Staging+Review)

**Comment by erinrwhite** [comment]
Okay, this is ready for review! @allison0034 

- [DRAFT How to document findings for staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3510108161/89815+-+Erin+-+How+to+document+findings+for+Staging+Review)
- [DRAFT How to document findings for design system staging review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3510140929/89815+-+Erin+-+How+to+Document+Findings+for+a+Design+System+Staging+Review)

And I pulled out the information about verifying artifacts and following up with the VFS team into a separate page to sit alongside our scheduling, during and after meeting guidance
- [DRAFT NEW Staging Review - Verify artifacts and follow up with VFS team](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3524198402/89815+-+Erin+-+Staging+Review+-+Verify+artifacts+and+follow+up+with+VFS+team)

**Comment by allison0034** [comment]
@erinrwhite I will review this tomorrow morning.

**Comment by allison0034** [comment]
This looks good. I made a couple if comments,=.

**Comment by erinrwhite** [comment]
Final pages published!

[How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)

[How to Document Findings for a Design System Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2572189697/How+to+Document+Findings+for+a+Design+System+Staging+Review)

[Staging Review - Verifying artifacts and following up with VFS team](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3525738521/Staging+Review+-+Verifying+artifacts+and+following+up+with+VFS+team)

@allison0034 looking okay to close? If so I will announce to team and close ticket. Thanks!

**Comment by allison0034** [comment]
@erinrwhite  good to close!
