### ISSUE TITLE
Design pending POA states for widget and Appoint

### ISSUE THREAD

**Issue by mtri** [department-of-veterans-affairs/va.gov-team#89847]
## Background
Pending POA states are possible with Vets API so we can support them in the Representative Status Widget and Appoint.

[Slack thread](https://dsva.slack.com/archives/C05L6HSJLHM/p1722367622696289)

## Tasks
- [x] Design pending Representative Status Widget states
- [x] Design Appoint introduction with pending representative status states
- [x] Engage CAIA for final content
- [x] Implement final content

## Acceptance Criteria
- [x] Designed states are ready for Midpoint Review

**Comment by mtri** [comment]
WIP on iteration of placement and content

[Slack conversation](https://dsva.slack.com/archives/C05L6HSJLHM/p1722612060531179)

[Option 4 - Skinny alert appears with Widget](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9081-137619&t=wEni7xzHCqnUMD2m-11)\
[Option 4b - Skinny alert appears in Widget](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9081-137620&t=wEni7xzHCqnUMD2m-11)\
[Option 5 - Link to profile for information on requested representative](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9081-137621&t=wEni7xzHCqnUMD2m-11)\
[Option 6 - Include requested representative info on Appoint intro and Profile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9081-137622&t=wEni7xzHCqnUMD2m-11)

**Comment by mtri** [comment]
[Engaged CAIA here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65809#issuecomment-2276682129)

**Comment by oddball-lindsay** [comment]
Carrying over A's recommendation for the "pending" alert here for quick access: https://github.com/department-of-veterans-affairs/va.gov-team/issues/90398#issuecomment-2287075132

**Comment by mtri** [comment]
The discussed CAIA content is in --

v2 Representative Status Widget pending states with new CAIA content:\
[Pending states](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9405-149521&t=0FJF8OgfcXnAsPX3-11)\
[Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=9405-150014&t=0FJF8OgfcXnAsPX3-11)

Pending/replacement state on v2 Appoint introduction:\
[Mobile](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=9405-220870&t=0FJF8OgfcXnAsPX3-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893&show-proto-sidebar=1)\
[Desktop](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=9405-318588&t=0FJF8OgfcXnAsPX3-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893)\
(Now included with other page states on the Figma page for Appoint v2)
