### ISSUE TITLE
Update operational guidance for GH Projects

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89851]
## User Story
As a Governance team member, I want to begin using the new Collaboration Cycle Reviews GH Projects board so that we can sunset ZenHub.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @briandeconinck 

## Description
Governance needs to update our operational guidance for supporting Collaboration Cycle so that it reflects the Collaboration Cycle Reviews GH Projects board opposed to the Collaboration Cycle Reviews ZenHub board (aka the Zenhub workspace). The operational guidance currently has many references to ZH, and those will need to be updated to GH Projects.

For the Touchpoint - Scheduling docs, most changes will need to be made to the  "Update Github ticket metadata" section. For Touchpoint - After the Meeting docs, most changes will need to be made to the "Advance to the next touchpoint" section. The status names do not changes, however the process for how we update the status does. You no longer have to make sure you're in the right workspace. You just have to have the ticket open in GH (not ZH) and can change the status there. See screenshot below:
<img width="492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eeaa68bd53e6dbc899a93d5d0e74e73e9bb3df1b/image.png" alt="image.png" />

In addition, Governance should add reminders into the documentation to no longer include the ZH links in the Calendar events for touchpoints. The GH link should be shared instead. This is very important as ZH links are inaccessible to someone without a ZH license.

**Note:** Similar to the split code blocks ticket, this ticket is also exempt from creating documentation drafts. Please edit the live docs directly. 

## Impacted Artifacts

- [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
   - The name of this document is being modified in ticket #90034, so please be mindful
- [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
- [Design Intent - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775253404/Design+Intent+-+After+the+Meeting)
- [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
- [Midpoint Review - After the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790686759/Midpoint+Review+-+After+the+Meeting)
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
- [Staging Review - After the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting)

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance operational guidance docs for Kickoff, DI, MPR and SR are updated to specify changes to the GH Projects board and no longer the ZH workspace

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@briandeconinck docs are updated! Rather than giving you the whole list of links again, it's just everything in the "impacted artifacts" list in the ticket!

**Comment by briandeconinck** [comment]
@KKitagawa-Bosch this all looks good to me! I think you're good to close it out.
