### ISSUE TITLE
Update Platform Website to reference GH Projects

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#89852]
## User Story
As a VFS team member, I want to locate my Collaboration Cycle request ticket so that I can schedule my next touchpoint or find previously provided feedback.

Assignee: @shiragoodman 
Peer Reviewer: @KKitagawa-Bosch 

## Description
With the switch from our Zenhub board to the Github Projects board, Governance needs to ensure all VFS-facing references to the ZH board are replaced with references to the GH Projects board.

The purpose of this ticket is to update the pages on Platform Website to reference our GH Projects Collaboration Cycle Reviews board.

## Impacted Artifacts
Collaboration Cycle - [Resources](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/resources) page on Platform Website

## Tasks
- [ ] Replace link and content on Resources page to reference the Collaboration Cycle Reviews GitHub Projects board. The link should go to the [Board view](https://github.com/orgs/department-of-veterans-affairs/projects/998/views/2).
- [ ] Remove reference to the "Done" pipeline as it is no longer used. Guidance can be updated to direct VFS teams to close their ticket once in the Post Staging Review pipeline.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS-facing guidance no longer references the Collaboration Cycle Reviews Zenhub board
- [ ] VFS-facing guidance includes a reference to the Collaboration Cycle Reviews GitHub projects board

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman changes have been made but not pushed to update, I'll push update as soon as you get a chance to look at them! 

https://vfs.atlassian.net/wiki/spaces/CC/pages/1764491265/Resources

**Comment by shiragoodman** [comment]
@KKitagawa-Bosch took me a minute to figure out where your changes are. I had thought you just linked the live page, but I realized that if I hit Edit, it shows me the changes you made that have not yet been published. `#TIL`

Everything looks good! Only 1 comment which is to change the title to GitHub Projects board in both places it's referenced. 

Thank you for picking this up!

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman added "projects" to both of those instances and pushed changes live! I'll close the ticket once the site update goes through today
