### ISSUE TITLE
HLR |  Lighthouse Testing for Form Version Update

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#89863]
## Value Statement

**_As a_** Dev

**_I want to_** ensure there are no adverse impacts of the latest HLR form updates

**_So that_** I can confirm the final confirmation PDF that veterans see is accurate

---

## Background Context

Once we finish all the updates to the HLR form, we want to ensure that we did not have any unintended effects on the final PDF that is generated by Lighthouse

## Acceptance Criteria

- [ ] The PDF generated by Lighthouse appears as expected when submitting an HLR with the updated form

## Out of scope

- Full E2E testing beyond Lighthouse coordination. 

## Tasks

- [ ] Coordinate with Lighthouse team and figure out who can help us with testing
- [ ] Submit test HLRs in staging environment
- [ ] Check if there are issues with resulting PDFs; create additional bug tickets as needed

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by comaurice** [comment]
Will reach out to Hobson to start collaboration on this.

**Comment by dfong-adh** [comment]
Maurice spoke with Hobson and LH team will help with testing. To confirm which days for testing next week.

**Comment by dfong-adh** [comment]
Maurice will have an update on this today - tests should be ready.

**Comment by comaurice** [comment]
Completed submission tests in staging. working with LH on PDFs

**Comment by comaurice** [comment]
Received PDFs from LH. Discovered a bug with the homelessness question. Even when checked yes, it appears unchecked on PDF. LH confirmed this is a bug on their end. They are correcting the bug but also need to go back at historical submissions of the last 2 months. We opened #97042 to provide them with the submissions we have.

**Comment by Mottie** [comment]
We just finished another test with Lighthouse. Once reviewed, we can close this ticket

**Comment by eileen-coforma** [comment]
Testing is complete 🎉
