### ISSUE TITLE
[FE] - Added start/end query params to upcoming appointments GET

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#89875]
## Description 
vets-api requires a start and end query param for the upcoming appointments endpoint. This ticket is to add those values. Start will be the current day, and end is current day + 13 months. Sample date format: `2024-8-01`

Also update payload values with latest from BE

## Tasks
- [ ] [FE] add GET params
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/89875?planning-poker) with Zenhub @wullaski
