### ISSUE TITLE
[FE] SPIKE - discover all the possible values for the 'kind' field

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#89876]
## Description
We are using the `kind` field to determine appointment modality for upcoming appointments from VAOS. Get with Simi or someone on the appointments team to see if we can get a list of expected values. Once we have that list, compare with the proposed designs of appointment modality types.

## Tasks
- [ ] [FE] find possible 'kind' values
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] we understand modalities from VAOS endpoint

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/89876?planning-poker) with Zenhub @brianseek @wullaski

**Comment by loripusey** [comment]
@wullaski @brianseek please estimate

**Comment by brianseek** [comment]
In the `kind` field in the VAOS payload there are only 4 possible values:
```
  clinic
  cc
  telehealth
  phone
```
Sources:
 - https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/docs/vaos/v2/vaos_v2.yaml
 - https://veteran.apps.va.gov/vaos/v1/
 - [slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1723497497705179)

**Comment by brianseek** [comment]
@zach-park / @benbrasso-agile6 See my comment above. This limits what we can do for modalities in upcoming appointments. I'll bring it up as a PL tomorrow too.

**Comment by benbrasso-agile6** [comment]
Maybe async help with the mapping from the larger list of appt types that are available through various systems via VAOS Backend service: 

- VA in-person > clinic 
- VA in-person vaccine > clinic 
- VVC > telehealth
- VVC at VA facility > clinic 
- VVC on GFE > telehealth
- VVC at ATLAS facility > ??
- Phone > phone
- Community care > cc
- Claim exam appointment  > clinic ??

**Comment by brianseek** [comment]
I think the 4 types are our limitation for now. If we can use another service, that will be another phase type of thing.

**Comment by benbrasso-agile6** [comment]
Right, but what’s the mapping?

We just assume that means:

clinic = VA in-person
Telehealth = ??
Cc = community care 
Phone = phone

and the rest we won’t ever retrieve? Just need some validation is all.

**Comment by brianseek** [comment]
ah I see, yes you have it correct and telehealth is defined as "A virtual appointment" so we will just need the design to be generic enough for that.

**Comment by benbrasso-agile6** [comment]
K cool

**Comment by benbrasso-agile6** [comment]
I guess we need to make them all generic enough since we won't know which type of in-person. Eh, we'll give it a whirl on the design side.

**Comment by brianseek** [comment]
we can chat in a PL tomorrow and get some backend input too. We may have a path to knowing more in the next phase but for this phase we don't

**Comment by loripusey** [comment]
but there must be a way to further determine if the "clinic" appointment is a face-to-face or VA video appointment; can we ask that question?

**Comment by benbrasso-agile6** [comment]
That was sort of my point; the full authenticated experience is able to categorize appts down to: 

VA in-person 
VA in-person vaccine 
VVC
VVC at VA facility
VVC on GFE 
VVC at ATLAS facility 
Phone 
Community care 
Claim exam appointment 

But, I think it's because we're not using the same backend services. I'm sure Brian will clear it up.

**Comment by loripusey** [comment]
What about Brad's new API tool where we supply stop codes and it tells us the modality? Can we use that if we don't have access to the data another way?

**Comment by brianseek** [comment]
this is all the stuff that I want to talk about in the PL with backend too. We just need to wrap our understanding around the effort here.

**Comment by brianseek** [comment]
Peter provided this, which is extremely useful: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/backend-logic.md#appointment-types

**Comment by benbrasso-agile6** [comment]
Ooooh, nice. That's helpful.

**Comment by brianseek** [comment]
moving this to closed, we determined the values for kind and how to ID the remaining modalities. The work is now shifting to the backend to see practical examples of those in a a payload to be able to map the expected values
