### ISSUE TITLE
[CDP] Add full deduction codes to debt detail page

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#89873]
## Description

Enter a detailed description of the work - gherkin syntax below is acceptable.

Given: A veteran view their overpayment 
When: A veteran wants to know the full deduction code to pay the debt
Then: They should be able to see the whole deduction code that matches pay.va.gov and not just the number

Here is the list of deduction codes on pay.va.gov:
<img width="686" alt="Screenshot 2024-08-01 at 3 55 38 PM" src="https://github.com/user-attachments/assets/25896b42-9185-419d-b42d-b16eb2f06e90">

We only need to update the ones that are in the [debt portal](https://github.com/department-of-veterans-affairs/vets-website/blob/ae9033e994597e19feeb199791ac314d29de0e32/src/applications/combined-debt-portal/debt-letters/const/deduction-codes/index.js): 

## Tasks
- [ ] Add the whole deduction code text from pay.va.gov to the deduction code on the debt detail page

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [ ] The full deduction code has been added the debt detail page
- [ ] It matches the verbiage on pay.va.gov

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>
