### ISSUE TITLE
[DevOps] Create assumable IAM role w/ policy in `vaec-cms` for CHIP deploys.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89884]
## Description
Let's get rid of the access key secrets now.

## Tasks
- [x] [DevOps] Create or re-use an IAM role with sufficient permissions.
- [x] [DevOps] Configure CHIP to deploy via the above role.
- [x] [DevOps] Ensure deployment to `int` environment works.
- [x] [DevOps] Open ticket to followup with cleanup.

## Acceptance Criteria
- [x] CHIP uses OIDC instead of access keys to assume IAM role and deploy updates.
- [x] Ticket opened to followup.
