### ISSUE TITLE
[DevOps] Create assumable IAM role w/ policy in `vaec-cms` for LoROTA deploys

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89883]
## Description
Let's get rid of the access key secrets now.

## Tasks
- [x] [DevOps] Create or re-use an IAM role with sufficient permissions.
- [x] [DevOps] Configure LoROTA to deploy via the above role.
- [x] [DevOps] Ensure deployment to `int` environment works.
- [ ] [DevOps] Open ticket to followup with cleanup.

## Acceptance Criteria
- [x] LoROTA uses OIDC instead of access keys to assume IAM role and deploy updates.
- [ ] Ticket opened to followup.

**Comment by ndouglas** [comment]
Closed in department-of-veterans-affairs/lorota#142.
