### ISSUE TITLE
[FE, QA] 10-10EZ - Diagnose and update service history validation for age range

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#89895]
## Description

It was discovered during some recent testing regarding services dates the additional validation mechanism isn't firing for minimum age and date range. We need to accurately block any invalid date ranges and age requirements to ensure the upcoming changes to the conditional logic for the TERA questions can be applied accurately.

## Tasks

- [x] Diagnose current validation function
- [x] Apply updates for any bugs found
- [x] Validate the acceptance criteria and document
- [x] Publish update(s)

## Acceptance Criteria

- Veterans are not permitted to enter an entry date that would be less than 15 years before their birthdate
- Veterans are not permitted to enter a discharge date beyond one year from the current date
- Veterans are not permitted to enter a discharge date that is before their declared entry date

**Comment by longmd** [comment]
| After today + 1 year | Before entry date | Age 15+ |
| --- | --- | --- |
| <img width="546" alt="Screenshot 2024-08-02 at 10 26 06" src="https://github.com/user-attachments/assets/840f5b74-f89d-4e39-8ce5-32644acb8cfb"> | <img width="546" alt="Screenshot 2024-08-02 at 10 25 51" src="https://github.com/user-attachments/assets/d53737d4-33fe-47ee-8d87-2f10b925fc4e"> | 
<img width="546" alt="Screenshot 2024-08-02 at 10 25 28" src="https://github.com/user-attachments/assets/23e7924d-1664-48c7-bbcd-165998b6f1b3"> |

**Comment by longmd** [comment]
@allanto-ah / @hdjustice , this update is ready for sign-off and approval. [You can test in this RI.](http://59777f69c0c6b8ac27faffa463b67249.review.vetsgov-internal/health-care/apply-for-health-care-form-10-10ez/)

**Comment by hdjustice** [comment]
I am checking it out

**Comment by hdjustice** [comment]
- Confirmed Service Start date restriction to 15 years or more
![image](https://github.com/user-attachments/assets/300df9f8-d2f0-4ca5-ac3f-d7e4bfa99d53)

- Confirmed Service end date restriction to 1 year and 1 day or more
![image](https://github.com/user-attachments/assets/6b7559ab-325f-447a-8f6b-6a04f4f8888f)


- Confirmed service end date restriction to 1 year and 1 day or less 
![image](https://github.com/user-attachments/assets/cbc572b3-1287-45db-b8ec-81da02278fe0)

- Confirmed the happy path as well
![image](https://github.com/user-attachments/assets/a16f7472-7197-4648-b52b-e55ac9d1451a)
![image](https://github.com/user-attachments/assets/d56e2be8-4877-4e59-91e8-0adbec9adda5)

**Comment by allanto-ah** [comment]
Environment: RI

Verified that the error messages appear as expected. No regression issues found as well
