### ISSUE TITLE
Allow veteran to download the PDF

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#89897]
# Overview
When a veteran completes the 527 form, they should be able to download a copy of the PDF that was generated and submitted on their behalf.  

# Tasks
On the confirmation page, present the veteran with some text and a button that would allow them to download the PDF that was generated.  

- [ ] - Create a flipper to hide this.
- [ ] - Create a separate ticket to remember to clean up the flipper
- [ ] -  Change vets-website code (which Todd already mocked up)
- [ ] - Create new endpoint on vets-website for the action.  Maybe `v0/pdf`   Passing in `saved_claim_id` 
- [ ] - API checks that `current_user` is the owner of that content and PDF so that you can't just grab PDF's that don't belong to you.
- [ ] - API returns the PDF.

## Mockup Confirmation Page
| Cropped | Full Page |
| ------ | ------ |
|![Screenshot 2024-08-02 at 8 53 14 AM](https://github.com/user-attachments/assets/3527b0c2-2dbe-497e-ba7a-1b851d03a473)|![localhost_3001_pension_apply-for-veteran-pension-form-21p-527ez_ (4)](https://github.com/user-attachments/assets/2e4ebd41-d9c2-450d-a93c-5a4cefe99a32)|

**Comment by ToddWebDev** [comment]
We should also consider using a confirmation modal when the Veteran clicks the [ Download PDF document ] button to prevent accidental downloads.

**Comment by mjknight50** [comment]
Closing this in favor of the epic:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/90275
