### ISSUE TITLE
Discovery: Unit Test Coverage Report

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#89903]
## Summary

Targeting `vets-api`, the level of unit test coverage is not currently reported. Create a "report" on GitHub Action that shows the code coverage for unit tests. The underlying goal is to bring awareness of the lack of unit tests.

Likely solution is to copy the current Coverage Reporting and only include unit tests 

Explore the possibilities of grouping specs in an integration or unit directory. 

### Characteristics
- Report unit test coverage as a comment in the PR.
- Consider dispatching a workflow to process unit test coverage.

### Concerns
- Concerned about adding time to the workflow.
- Can the unit test coverage be completely separated from CI? We want to be preventing merge with code coverage below NN%.

## Tasks

- [ ] report unit test coverage %
- [ ] document findings as you go

## Acceptance Criteria 

- [ ] doesn't block merging
- [ ] coverage % is reported
- [ ] document the findings from efforts related to this ticket (ongoing issues, possible solutions, performance of attempted solutions, etc.)

**Comment by stevenjcumming** [comment]
Here's an example of what the unit test coverage report could look like:

![Screenshot 2024-08-05 at 2 57 02 PM](https://github.com/user-attachments/assets/bfcd0253-5939-4c3e-8842-f8c7132dd1e1)

**Comment by stevenjcumming** [comment]
Here's a doc with findings

https://vfs.atlassian.net/wiki/spaces/PRT/pages/3352723470/Reporting+Unit+Test+Coverage
