### ISSUE TITLE
Code Health Reporting

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#89902]
## Summary

Create a "report" in GitHub Actions to analyze the code for bad practices and areas for improvement. This should focus on Pull Requests. The underlying goal is to create a better PR review process. 

## Tasks

- [ ] report code smells (`reek`)

*Note*: Code that flay reports as similar is a good candidate for refactoring.

## Acceptance Criteria 

- [x] only code diff is checked
- [x] doesn't block merging
