### ISSUE TITLE
Confirm 686c off-ramp behavior for pension claims

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89909]
## Issue Description
_Code was added in 2021 that was intended to off-ramp 686c requests to remove a dependent if the claimant was receiving pension, but the code was never turned on (placed behind a flipper) because the BGS Award Service API was not working (see this spike #76465). Before fixing the API and turning on the flipper, we need to understand if the current logic for off-ramping pension claims is still correct._

---
## Tasks
- [x] Talk with pension and RBPS stakeholders to confirm that 686c claims should only be off-ramped if a dependent is being removed from pension benefits

## Acceptance Criteria
- [x] Document the logic and the reason why
- [x] Create follow-on tickets if needed
---

**Comment by steele-lm** [comment]
From Jennifer Feuer:
In a perfect world, when a pension dependency claim comes through RBPS, the following will occur based on the responses:

1. Did the dependent that you are submitting this claim for have income in the last 365 days?  If the answer is yes, then the claim will off ramp and go for a manual review.  If the answer is no, the claim can continue through RBPS claims processing.
2. Is the household net worth less than the threshold (and there is a yearly amount that is updated in this question every year)?.  If the answer is yes, then the claim can continue through RBPS claims processing – assuming the answer to the question above is no.  If the answer is no, the claim will offramp for manual review.
 
So, an RBPS auto pension dependency claims processing option has to be a NO to Question 1 and a YES to Question 2 to automatically be processed through RBPS.  The submitter must state that the dependent does NOT have any income for the last 365 days AND that the household net worth IS less than the current threshold.  We did that on purpose so that it wasn’t just all the same answer, and we can make sure the submitter is providing the right responses – essentially making it so that the submitter is having to read and really respond correctly.
