### ISSUE TITLE
Spike | Determine if/how VRE can implement OAuth

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#89921]
## Issue Description
_From Hope Lam: Currently, the VA.gov integration with RES completes authentication utilizing a static API key.  While this method is secure and functional, the OAuth authentication approach could provide enhanced security compared to the static API key._

---
## Tasks
- [ ] Is VA.gov capable of supporting OAuth authentication?
- [ ] If yes, what needs to be done?
- [ ] How long will it take to implement?

## Acceptance Criteria
- [ ] Determine how to implement OAuth on VRE
- [ ] Create follow-on ticket to implement
---
