### ISSUE TITLE
[Design] 10-10CG - Improvements: Content Cleanup post-July update

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#89939]
## Background
Now that the July form updates have been released, we want to review content and make some adjustments to better align with VADS guidelines.
These changes include removing "please" from some error messages, updating the confirmation page Caregiver address, and a few others outlined in the design file and list below.

### Resources
- [Figma file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=36hh5JZXFLBpFqvj-0)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683656893560/fccf821394d1cf693ad1c036e912e11a18ff88bd?sender=uadf1ed7fe7c76f0914967329)

## Tasks
- [x] Review and and identify content items that are changing (in Mural)
- [x] Create side by side comparisons in Figma with annotations
- [x] Review with team/PM
- [ ] [PM] Create checklist of items and breakdown into smaller UI tickets.

## Acceptance Criteria
- Content updates are clearly identified and tickets are created

**Comment by jessicastump** [comment]
Setup/started a staging and ideal state view in [Figma here](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=XMh8fLLuSsEG5ooW-0); and updated [Mural source of truth with notes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683656893560/fccf821394d1cf693ad1c036e912e11a18ff88bd?sender=uadf1ed7fe7c76f0914967329)

**Comment by jessicastump** [comment]
hey @hdjustice -- The [figma](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=36hh5JZXFLBpFqvj-0) file side-by-sdie is ready to review/walk through together.

I noticed a couple other minor updates and spacing issues noted those too in the Figma file summary here: 
- The memorable date component has a few variations that I was trying to capture them all but not sure if they are accounted for
- The relationship to Veteran label (on all caregivers) needs updated to "What's" instead of "What is"
- The warning alert for the upload file should only appear after upload not when first arriving at the page
- There are content updates needed to the alert when no caregiver is added (need to remove change references)

**Comment by hdjustice** [comment]
i love the side by side.  I know that was a lot of work, but i think it will help when we start working on it.

@longmd - when you have a moment, check out the [Figma file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=36hh5JZXFLBpFqvj-0) and see if there is anything that stands out to you.  We can also review in a call if you would like to.

**Comment by longmd** [comment]
@hdjustice / @jessicastump , I agree. Love the breakout and description of what each change needs to be. Great work on this! 🙃

**Comment by jessicastump** [comment]
@hdjustice - With the various FE tickets opened, is this good to close or should we wait until we hear back from CAIA on the "please" convo? 

Slack thread convo from Aliyah:

> The CAIA team has been working on updating error messages, including removing "please", and getting that guidance in the design system. I'm not sure if that overlaps at all with the forms library and what Platform asked you all to do. But in alignment with our content guidance, where possible, we recommend that teams remove "Please" in their content.
> As mentioned in previous convos, if the "please" is locked in to the error message component (i.e. it's not customizable) it's fine to leave that in for now. And once the design system is updated, CAIA can circle back about the error messages. I'm not entirely sure why Platform recommended a bug ticket for this, since CAIA is working on error message updates.
> Laura Willwerth
>  I know you've been working with one of our copy editors on these error message updates. Do you recommend that Jessica and Matt hold on opening a bug ticket with the design system since you're working on getting error message updates in the design system?

**Comment by longmd** [comment]
RE: the "Please" stuff... I'm of the opinion now, I'll just go in to the forms code and update everything to remove it. Then, I'll link to the guidance you gathered in the PR and use that to push it through. I don't think we need to do a bug ticket or hold off on the update.

**Comment by hdjustice** [comment]
I am good with that direction, thank you both!  @jessicastump - If you have a few minutes today, I want to go through the content list really quick and make sure we have what we need there.

**Comment by jessicastump** [comment]
Closing this ticket and adding a note - there are some spacing discrepancies within the address blocks and checkboxes used but they are not consistent. We will review and open up bug tickets (our team or Platform) that come up during QA but the design part of the content clean up is done :) 
cc @hdjustice
