### ISSUE TITLE
Copy of DataDog cost discovery 

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89934]
## User Story
As the managers and developers of the Platform and the DataDog tool, 
We need to understand the cost restrictions of DataDog, 
So that we keep all costs regarding DataDog constrained and should hopefully keep the tool as well. 

## Issue Description
We need to research the DataDog tools and cost contract so that we understand how the cost model works. We want to create a best practices user guide for DataDog (see ticket # ) and this is the discovery work that will inform that document. The goal of the document will be to convey to users how to avoid incurring extra costs, with regard to building with DataDog (for example, the unique queries added significantly to the DataDog bill, and we want to guide users so that cost mistakes aren't made).

## Tasks
- [ ] Review the DataDog pricing structure
- [ ] Document current state of DataDog costs 
- [ ] Identify where cost increases occur, and document how to avoid these areas when developing
- [ ] Identify where other cost savings are possible and document those best practices. 

## Success Metrics
That we have a better idea of how to keep costs lower than ($XX) while using the DataDog tool.

## Acceptance Criteria
- [ ] There will be documentation to inform the Best Practices when using DataDog
- [ ] The Platform Product team can continue to monitor DataDog costs and advise when teams incur additional costs. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
Document started here: https://vfs.atlassian.net/wiki/spaces/BCP/pages/3356590105/Cost-saving+best+practices+for+Datadog
