### ISSUE TITLE
Update Out-Of-Band Deployment GitHub Template

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#89937]
## Description 
_Update the Out-Of-Band deployment GitHub template to better define approval requirements_

---

## Definition of Done
_Create a pull request with changes, have Clint review and approve, then merge PR into Main._

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Work with Clint to identify when and if approvals are needed from the Infrastructure/Operations, and Security teams
- [x] Create Pull Request with proposed changes
- [x] Have Clint review and approve changes
- [x] Merge PR into Main 
- [ ] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/89936

**Comment by bdech** [comment]
PR has been approved by Clint, and merged into Main.

Now the checkboxes in the template look like this <img width="1042" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0d41a9cbcb314f830f2a6601d206f0f27bb67d4/image.png" alt="image.png" />
