### ISSUE TITLE
Copy of DataDog "Best Practices" documentation for cost savings

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#89935]
## User Story
As the managers and developers of the Platform and the DataDog tool, 
We need to document the opportunities for cost savings for the DataDog tool, 
So that users are all familiar with how to prevent unexpected cost increases

## Issue Description
Based on the outcomes from the DataDog cost discovery ticket (#[89933](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89933)), this is the ticket to document and create a best practices user guide for DataDog. The goal of the document will be to convey to users how to avoid incurring extra costs, with regard to building with DataDog (for example, the unique queries added significantly to the DataDog bill, and we want to guide users so that cost mistakes aren't made).

## Tasks
- [ ] Based on [ticket 89933](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89933) findings, pull out and document best practices when using DataDog. 
- [ ] Identify where cost increases occur, and document how to avoid these areas when developing
- [ ] Identify where other cost savings are possible and document those best practices. 

## Success Metrics
That users have been informed on best practices to implement when using DataDog

## Acceptance Criteria
- [ ] An approved document outlining DataDog best practices will be created
- [ ] The DataDog best practices document will be shared with relevant teams 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
