### ISSUE TITLE
[UX] 10-10EZR Toxic Exposure Gulf War Branching

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#89949]
## Issue Description
With the research for the 10-10EZ TERA questions completed, the EZ team moved forward with the suggested recommendations per the UX team regarding the branching logic using the Veteran's Service Date. During the design phase, the team discussed the complexity of getting the Veteran's service timeframe beyond the "Last Service Branch". The tradeoff was not worth it since it introduced complexity to the system and flow without making the Veteran's journey easier. So the team decided to pivot into an easier development: TERA branching logic based on the Veteran's birthday.

The EZ is heading this approach with EZR as support. 

---
## Tasks
- [x] Work with the EZ/CG team to confirm the changes.
- [x] Working with the EZ/CG team to update the user flow and mockup
- [x] Demo the changes to the engineering team.

## Acceptance Criteria
- Dev understands the ask and can proceed with their work.
