### ISSUE TITLE
BE | Profile | Direct Deposit | 200 response missing control info

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#89955]
## Background
Mobile team was investigating [this 500 error](https://vagov.ddog-gov.com/apm/trace/553128145445929076?colorBy=service&env=eks-prod&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=1479858768715494983&spanViewType=errors&timeHint=1722445650746.984&view=spans). The `Mobile::V0::Adapters::LighthouseDirectDeposit` is throwing an error because `account_control_info['can_update_direct_deposit']` is nil. 

Reached out to the LH team to ask is a [200 response can be missing control information](https://dsva.slack.com/archives/C03P6C3FYMR/p1722861886357689).

## Tasks
- [ ] Reproduce scenario in production.

## Acceptance Criteria
- [ ] Determine if 200 responses can be missing control information (and possibly payment information).
- [ ] If a code fix is required, create a ticket for patching.

**Comment by tpharrison** [comment]
@mtcA6 Who should we reach out to at BGS about this?

**Comment by mtcA6** [comment]
@tpharrison John Dell and Jinmay Patel

**Comment by tpharrison** [comment]
Reached out to Jinmay on Aug14.

**Comment by tpharrison** [comment]
[Followed up on this issue](https://dsva.slack.com/archives/C03P6C3FYMR/p1725640151398369?thread_ts=1722861886.357689&cid=C03P6C3FYMR) on Sept 6th.

The BIS and LH responses don't seem consistent.  I've discussed with Kris Pethtel (mobile team) and we've decided to raise a `404` error if control information is missing from a `200` response from LH.

**Comment by mtcA6** [comment]
@tpharrison do you need another ticket to implement that change or have you already taken care of that? 

Also, I agree w/the approach for what it's worth. My only reservation is around the quantity of these errors. Roughly how many have we seen since launching? and can you tell if they are unique visits or happening for a select few?

**Comment by tpharrison** [comment]
@mtcA6 Mobile-related traffic has seen about 2 of these errors per day (different users).  These errors haven't shown up in web-related traffic (but I'll check again).

I believe Kris is going to make the change which will apply to both mobile and web.  If not, then I'll let you know and we can create a ticket.
