### ISSUE TITLE
[DevOps] Create IAM role assumable by Datadog to retrieve metrics from `vaec-cms`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89974]
## Description
This isn't quite as appealing as the CloudWatch Metrics + Firehose solution, but it's at least easier to debug.

## Tasks
- [x] [DevOps] Create a secret to store the external ID for Datadog.
- [x] [DevOps] Create an IAM role that can be assumed by Datadog.
- [x] [DevOps] Transition the Datadog integration to use the assumable role.

## Acceptance Criteria
- [x] New role exists in IaC.
- [x] Datadog uses new role to retrieve metrics.
