### ISSUE TITLE
Automate SOCKS adoption / migration rates

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#89972]
## Issue Description
Automate SOCKS adoption / migration rates and publish to confluence

## Tasks

- [ ] Automate the collection of socks adoption stats for legacy and new environments
- [ ] Automate generation of report and publish to confluence
- [ ] Ideally this solution is event driven rather than scraping data from log files or cloud watch.
- [ ] Stretch Goal: If an event driven approach can be taken, the support team has requested a dashboard providing realtime health and usage.

**Comment by ericboehs** [comment]
Testing something.

**Comment by JoeTice** [comment]
SPRINT 7 UPDATE: IN PROGRESS - Work on this task is ongoing. but not completed by the end of the sprint due to unforeseen circumstances w/ power loss. @ben-allen-oddball, can you please provide a status update and share links to in progress or final outputs.

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3374415876/Users+on+Legacy+Environment

**Comment by ben-allen-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3376709822/Users+on+New+Socks
