### ISSUE TITLE
[DevOps] See about getting a VistA service account for Check-In Experience.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#89978]
## Description
As this is no longer in the domain of VeTEXT, their service account is being sunset and we need to assume that responsibility.

Questions:
- Is this the same process for getting a service account in the pre-prod environment?
- If not, what is that process like?

## Tasks
- [x] [DevOps] Scream until somebody pays attention to me.
- [x] [DevOps] Do whatever they tell me to do.
- [x] [DevOps] Open followup ticket(s) to continue down the yellow brick road as needed until I have valid service account credentials.
- [x] [DevOps] Document findings in this thread. But not the credentials. Put those in Secrets Manager.

## Acceptance Criteria
- [ ] We have valid credentials for a service account for VistA, or
- [x] Followup ticket(s) opened to address the next steps in the process.

**Comment by ndouglas** [comment]
VistA has a customer portal: https://dvagov.sharepoint.com/sites/OITEPMOVistAOffice/SitePages/VO-Customer-Portal.aspx
I need to complete this form to proceed with intake: https://dvagov.sharepoint.com/sites/OITEPMOVistAOffice/SitePages/VistA%20Office%20Review%20Board%20Form.aspx
