### ISSUE TITLE
Move "prep" for video visit instructions to a resources page

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#89998]
## Task Description

This moves the instructions to prepare for a video visit to a new page, and updates the content in those instructions. This follows a similar pattern to what we used for medication review.

## Notes and References

This work comes out of these collab cycle tickets:
- 

## Acceptance Criteria
- [ ] Design spec is complete
- [ ] Dev tickets have been created

## Deliverables
- [Design spec (WIP)](https://www.figma.com/design/HnExAM5SGNXzUlv9yRS87t/Details-Page-Changes?node-id=2011-2251&t=VIZ0GwslGoDqq7QG-4)

---
## How to configure this issue
- [ ] Add title and task description
- [ ] Attach to an Epic
- [ ] Add labels based on work type: design, discovery, documentation, strategy
- [ ] Delete this section

**Comment by outerpress** [comment]
@laurwill here's the ticket we talked about in the SME sync today. Design file is linked in the ticket, as are the collab cycle tickets that this came out of.

For next steps, I'm thinking we need you to create the resources page, and make any content adjustments there. After that this one should be pretty much ready to go.

Let me know if you want a separate CAIA ticket for this one. Thanks!

**Comment by outerpress** [comment]
This ticket is blocked - to move it forward we'll need to identify who will create a new resources page and update the language based on collab cycle feedback. This blocks a couple of collab cycle tickets:

- #89765 
- #91562 

FYI @JRRoof @kristenmcconnell @anita-halici 

Putting into our backlog for now.

**Comment by outerpress** [comment]
Talked to @ala-yna about moving this one forward. Next steps: re-engage with content team

**Comment by outerpress** [comment]
Todo: Bring to office hours

**Comment by outerpress** [comment]
Resolved in https://github.com/department-of-veterans-affairs/va.gov-team/issues/111533
