### ISSUE TITLE
Resolve Daily Product Scan Unexpected input(s) 'branch' warning in vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90025]
## Issue Description
The Daily Product Scan has a warning "Unexpected input(s) 'branch' " every time it runs. This warning should be resolved.

---
## Tasks
- [ ] Diagnose the warning on this workflow.
- [ ] Correct the warning so it no longer happens.

## Acceptance Criteria
- [ ] The Daily Product Scan workflow no longer throws a warning about unexpected inputs.
