### ISSUE TITLE
Split code blocks from CC Kickoff operational guidance and remove Platform Collaboration Point Tracker

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#90034]
## User Story
As a Governance team member supporting Collaboration Cycle guidance, I want to ensure that the guidance docs are easy to maintain and edit, so that we encounter fewer blockers and dependencies when making changes to our guidance.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @erinrwhite 

## Description
The [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1979121669/Collaboration+Cycle+Kickoff) guidance is used by Governance team to complete Collaboration Cycle Kickoff requests from VFS teams. The guidance doc includes both steps for Governance team, as well as content to be copy/pasted into the Collaboration Cycle Request ticket (aka the code blocks).

Although it is easy and convenient for the code blocks to be within the operational guidance for the team, it becomes very challenging to edit this doc if both operational and VFS-facing changes need to be made to the kickoff process. For this reason, we will be moving the code blocks into a separate Confluence page.

In addition, Governance team nor OCTO currently uses the Platform Collaboration Point Tracker. It is no longer necessary for Governance team to maintain this document. This step should be removed from the Kickoff operational process.

Lastly, the name of the Collaboration Cycle Kickoff - Moderator Responsibilities doc is misleading. The guidance doc should be named to reflect what steps are actually performed by Governance. Collaboration Cycle Kickoff - Set up CC Request ticket? Something appropriate.

**Note:** Since this change is being made for Governance benefit and we're only removing & rearranging content and not writing anything new, there is no need to create a documentation draft. Please feel free to edit the live docs directly. However, please inform the On-Support person so that they are aware.

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

## Tasks
- [x] Remove the code blocks from the Collab Cycle Kickoff - Moderator Responsibilities guidance
- [x] Add the code blocks to a separate/new Confluence doc
- [x] Ensure the new code block Confluence page is referenced/linked in the Moderator Responsibilities guidance
- [x] Remove all steps in the Moderator Responsibilities guidance for updating the Platform Collaboration Point Tracker
- [x] Rename the Moderator Responsibilities guidance to something more appropriate
- [x] After we rename the page, it is possible that the url will change. IF that's the case, we need to ensure our Slack workflow for Kickoff is updated with the new links.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have removed the VFS-facing code blocks from the Collaboration Cycle Kickoff - Moderator Responsibilities doc and created a new Confluence doc for them.
- [x] We have removed the steps from the Collaboration Cycle Kickoff - Moderator Responsibilities doc for updating the Platform Collaboration Point Tracker
- [x] We have renamed the Collaboration Cycle Kickoff - Moderator Responsibilities doc to something more appropriate
- [x] We have verified that our Slack workflow for Kickoff references the correct guidance.

## Team Notification
- [x] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite everything except the slack workflow updates are good (because I wanna make sure the name is permanent/final before I mess with those links) let me know when you've taken a look!

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch This is looking excellent! two things:

**Title for the kickoff main page:** What if we brought it in line with the language we're using on the governance-facing and VFS-facing messages in the Slack workflow? `Collab Cycle Kickoff - Admin tasks`?

**Headings on [Code blocks page](https://vfs.atlassian.net/wiki/spaces/PPS/pages/3387457549/Collaboration+Cycle+Kickoff+-+Code+Blocks)** headers on the page would help make the content scannable. So that might look like:

 - for the first 2 collapsed sections, a header, then a collapsed section below each header with the code
 - for the "individual code blocks" section, it might be
    ## Individual code blocks

    ### Code block name 
    > collapsed section with code

    ### Second code block name
    > collapsed section with code

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite made those changes!

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch looks good! Check the toggles - I'm seeing a few empty code blocks and some code blocks that have extra spaces at the beginning or end, or extra characters at the beginning:

![Screenshot 2024-08-15 at 1 52 20 PM](https://github.com/user-attachments/assets/fec99b07-6557-4d09-b5db-7b79932fbdbc)

**Comment by KKitagawa-Bosch** [comment]
confluence....I am literally begging you to work. Why did it delete two of the code blocks that were just there before I hit update. 

One second while I try to fix this.

**Comment by KKitagawa-Bosch** [comment]
Okay those things should all be cleaned up and saved, hopefully confluence behaves this time. @erinrwhite

**Comment by erinrwhite** [comment]
This is looking good! 👍🏻 good to move on to the Slack workflows 🤓

**Comment by shiragoodman** [comment]
thank you both for prioritizing this right at the start of the sprint! I like the solution you landed on.

**Comment by KKitagawa-Bosch** [comment]
Updated the slack workflow @erinrwhite !

**Comment by erinrwhite** [comment]
[Slack link is working great!](https://dsva.slack.com/archives/GNF5GSD9N/p1723750178925699?thread_ts=1723750133.170369&cid=GNF5GSD9N)

**Comment by erinrwhite** [comment]
Peer review checkboxes checked. Okay to close @KKitagawa-Bosch
