### ISSUE TITLE
[Design] Update medication review info and/or manage appointment links

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#90043]
## Background
We need to determine how the medication review information and format will affect the new link collection on the confirmation page. Peter encouraged and is ok with us breaking up the medication review information so that "Prepare for your appointment" and "Manage your appointments" are different sections.

[Figma file](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=2201-10449&t=mJv8ZqlzFzcZGE5t-1)

<img width="741" alt="Screenshot 2024-08-05 at 11 58 54 AM" src="https://github.com/user-attachments/assets/a812fe5f-c541-4cea-85ca-4d5d12fc4aa1">

## Tasks
- [ ] Determine how to consolidate medication review work and appointment link collection work
- [ ] Get feedback from CIE UX and Appointments UX
- [ ] Create final wireframes with content
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by UAE UX (Check-in and Appointments)
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/90043?planning-poker) with Zenhub @benbrasso-agile6 @cgednalske @zach-park

**Comment by benbrasso-agile6** [comment]
@cgednalske @zach-park still feels like we need move away from our Unified Figma file. This is a good example where it gets confusing. We got medication review content in one file, while the new landing page content is in the Unified file.

**Comment by benbrasso-agile6** [comment]
Got something started to review - https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=2201-10449&t=tCdgw6alrRvvkxW0-4

Make sure links are duplicated in med review + manage appointments sections

**Comment by benbrasso-agile6** [comment]
Got something started to review - https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=2201-10449&t=tCdgw6alrRvvkxW0-4

Make sure links are duplicated in med review + manage appointments sections

**Comment by cgednalske** [comment]
> @cgednalske @zach-park still feels like we need move away from our Unified Figma file. This is a good example where it gets confusing. We got medication review content in one file, while the new landing page content is in the Unified file.

@benbrasso-agile6 Yes we will. I'd like to work on that this sprint, so we're set up for the change. Is the new landing page in prod btw (can't remember atm)?

**Comment by benbrasso-agile6** [comment]
New landing page is in prod, yes.

**Comment by zach-park** [comment]
Validated:
https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=276-22919&t=XEnzCPgVyUQ3ANKj-1

**Comment by benbrasso-agile6** [comment]
Validated
