### ISSUE TITLE
RUSH: add 526 controllers with additional physical separation to a separate Argo bulkhead prior to PACT Act update

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#90051]
## User Story
As the managers and developers of the Platform, 
We need to add 526 controllers that should have additional physical separation to a separate Argo bulkhead prior to the next PACT Act update, 
So that there are no issues with the 526 traffic.

## Issue Description
See [this Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1722881386814709) for original request. 

These are the controllers that may be impacted by the 526 form and need to be bulkheaded:
- GET /v0/disability_compensation_in_progress_forms/:id - get or create 21-526EZ form for user, plus prefill if creating
- PUT /v0/in_progress_forms/:id - save in progress (NOTE: This particular process is used by other forms as well!)
- POST /v0/disability_compensation_form/submit_all_claim - submit the form 21-526EZ for a user with the formData as payload
- GET /v0/disability_compensation_form/submission_status/:job_id - after submit, is pinged for submission to VBMS status/claim_id
- GET /v0/benefits_reference_data/:path - gets lists of locations and (i believe) disabilities from LH BRD endpoint

## Tasks
- [ ] We need to bulkhead these controllers in a separate Argo bulkhead
- [ ] Test as necessary
- [ ] Create documentation as required

## Success Metrics
The five indicated connections will be placed into a separate Argo bulkhead. 

## Acceptance Criteria
- [ ] New bulkhead created to handle the PACT Act traffic.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by LindseySaari** [comment]
[The bulkhead ](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3055)has been added here and synced.

Traffic is flowing into the bulkhead and I've also updated this board to reflect [this current round of submissions](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms-2024?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1722873026152&to_ts=1722959426152&live=true)
