### ISSUE TITLE
Componentize Appt Summary View

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#90054]
## User Story
As the VA, we would like to create a Design System component for the appointments summary so that it will be consistent across products that have them.

## Resources
 - [Slack thread](https://dsva.slack.com/archives/C06RMRJCLHH/p1723647972920749)
 - [Canvas](https://dsva.slack.com/archives/C06RMRJCLHH/p1723647972920749)
 - [Experimental Design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3090)

## Things to Do
- [ ] Hold kick-off with Kristen & Ryan Thurwell to define scope 
- [ ] Engineering
     - [ ] Spike on how to create a VA Design System component
     - [ ] Compare Appts & PCI to understand differences
     - [ ] Create implementation tickets
     - [ ] Implement
     - [ ] A11y testing?
     - [ ] DS documentation?
- [ ] UX
    - [ ] Determine the changes listed in the Canvas
    - [ ] Wireframes?
