### ISSUE TITLE
[DevOps] Remove AWS service account credentials from `octo-vista-api`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90064]
## Description
Followup to #90030.

After the next production release, the AWS service account credentials should not be necessary and can be removed.

## Tasks
- [ ] [DevOps] Remove AWS service account credentials from `octo-vista-api`.
- [ ] [DevOps] Remove mention of `octo-vista-api` from [rotating-iam-keys.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/rotating-iam-keys.md).

## Acceptance Criteria
- [ ] Service account credential secrets removed from repository.
- [ ] `octo-vista-api` no longer mentioned in rotating-iam-keys.md.
