### ISSUE TITLE
[DevOps] Can we even still deploy Vista API?

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90065]
## Description
It has been so long since `octo-vista-api` has been deployed that I'm concerned it may not work at all anymore.

I should run a deploy on `dev` or `int` or something just to see what happens.

## Tasks
- [ ] [DevOps] Attempt a deploy on a non-staging, non-prod environment.
- [ ] [DevOps] Document outcomes in this thread.
- [ ] [DevOps] Open followup ticket(s) to address issues discovered.
- [ ] [DevOps] Open a followup ticket to perform similar procedure on staging.

## Acceptance Criteria
- [ ] Outcomes have been documented in this thread.
- [ ] Followup ticket(s) opened to address issues discovered.
- [ ] Followup ticket opened to perform a similar procedure on staging.
