### ISSUE TITLE
[Research & Design] My VA general: Review mobile app research/demo on personalized homescreen

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#90061]
## Background
The mobile team conducted a demo/research of the personalized home screen they've been working on. Matt is reviewing their findings to see what would be helpful to our work on My VA.

## Tasks
- [x] Review demo/research
- [x] Create write up with findings/recommendations

## Acceptance Criteria
- [x] We understand mobile team's findings and how they can helpful to our work

**Comment by mattmarino-adhoc** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-design/VA%20Mobile%20App%20-%202024%20Personalized%20Home%20Screen%20Evaluative%20Research%20-%20Takeaways%20for%20AuthExp.md
