### ISSUE TITLE
[Design] Discovery/design work for implementing tabs for upcoming appts

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#90077]
## Background

Though we’d still like to head in the tab direction, we’re running into more reasons not to switch than to switch. Both UX and FE had concerns emerge in our convo that we’ll still need to figure out before we can confidently say it’s an ideal experience for Veterans.

The main issues we ran into were confusion around the naming of the different lists (proving super difficult to find a solution for) and confusion around the differences or similarities between the two lists if some information/actions are available in one but not the other. 

To thoroughly flesh out these concerns before jumping into the tab approach, we’d like to propose releasing the link solution this sprint that’s already been updated based on midpoint review feedback, and using the next sprint to dig into the tabs further - maybe looking at doing some research or a/b testing to inform our next move with tabs.

It’s important to note that the link solution will be released on the confirmation page in either case, and this simply adds the one link to the appointment list page as we see if the tab solution will work. The link is also closer to what we tested in our Unified Check-in research, so we feel confident this release will not present any problems.

## Tasks

- [x] Identify pros and cons of implementing tabs for upcoming appts
- [x] Create design options
- [x] Sync with engineers on feasibility of options
- [ ] Present idea to Kristen and others to see how we want to move forward
- [ ] Create next design tickets that are needed

## AC

- [x] Discovery complete
- [ ] Synced with engineers
- [ ] Direction is approved 
- [ ] Design tickets created for anything else that's needed next

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/90077?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by cgednalske** [comment]
UX has a path forward for the "tabs" approach, but will now review together with FE to make sure there are no technical concerns.

Figma pages:
[Check-in tabs discovery](https://www.google.com/url?q=https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%257C-PCI?node-id%3D4014-89812%26t%3DVjK3R8HDyGxcUYF5-1&sa=D&source=calendar&ust=1724107098041837&usg=AOvVaw2pEKTxCKzpxGRj6vUwLgia)
[Pre-Check-in tabs discovery](https://www.google.com/url?q=https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%257C-PCI?node-id%3D391-24614%26t%3DNJp49BUfXpqlot8S-1&sa=D&source=calendar&ust=1724107098041837&usg=AOvVaw3FAKBATXGkwCSJFSB-sZ-G)

**Comment by benbrasso-agile6** [comment]
@cgednalske can we document our next steps? In the sprint goals, all it says we were committed to is exploring this idea. Would like to try and close this ticket out and create tickets for the next steps, whether it's going to Design office hours or creating FE tickets for the work and placing it in the backlog.

**Comment by cgednalske** [comment]
Yep - working on that today and will add info here. 👍

**Comment by zach-park** [comment]
@cgednalske @benbrasso-agile6 , I made the updated to the tabs, but I'm not 100% sure if they are right. Could you please take a look and comment? Thank you!
PCI: https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=391-23703&t=oTI2iEsP5kvgQKJD-1
CI: https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4014-88901&t=H71qUVtWkRZ1AWod-1

**Comment by cgednalske** [comment]
Adding in my comment here from [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1723849958866409?thread_ts=1723849752.456909&cid=C02GXKL8WM6), which summarizes our results for this discovery ticket:

> UX completed more discovery around the tabs approach and came up with some possibilities for how to resolve some of the concerns we had ([Check-in](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4014-89812&t=YBewrthbKlcV8Fbu-1) and [Pre-Check-in](https://www.figma.com/design/mVg6S9xgiQpWbAOAvptQOZ/Pre-check-in-%7C-PCI?node-id=391-24614&t=QwRKiSo1zQEuY6KA-1)). However, we met and discussed these with Brian and John yesterday and determined that, unless we can fully research the tab approach, we collectively don’t feel comfortable moving forward with tabs. The same concerns are still there (folks getting stuck and not checking in or having a confusing experience with side-by-side lists that have different information, as well as content challenges) and too many band-aid solutions are needed to try and address them. Though we recognize the tabs pattern works for Appointments, our situation is different enough that it’s not translating as we’d hoped.

> We’d like to close this exploration and stick with the link solution we took to midpoint, while at the same time [adding an alert to the Upcoming appointments](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4015-16649&t=YBewrthbKlcV8Fbu-1) page to proactively indicate some appointment data may be missing. If there is still interest in the tabs, we are definitely up for looking into research capacity for later on! 

Going to move to validation, as the alert work will be completed in Zach's ticket and any subsequent tab research or discovery would be entirely separate.

**Comment by cgednalske** [comment]
Next steps:

- Confirm with Kristen and Lori we will stick with link solution
- @cgednalske will send [alert](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4014-91433&t=YBewrthbKlcV8Fbu-1) to Laura for content review
- @zach-park to finish detail page work unblocked by FE Spike ticket
- @zach-park to incorporate [alert](https://www.figma.com/design/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-PCI?node-id=4014-91433&t=YBewrthbKlcV8Fbu-1) into detail page work and Upcoming appointment list 

I believe these are all part of Zach's current detail page ticket? @benbrasso-agile6 Or will adding the alert go in next sprint?

**Comment by benbrasso-agile6** [comment]
The spike is still blocking us. It got kicked to BE to figure out. Once the BE spike is complete, then Zach can finish up the appt detail pages and add the expandable alerts at the same time.

**Comment by benbrasso-agile6** [comment]
Would go ahead and close this ticket :)

**Comment by cgednalske** [comment]
Sounds good! Will close. @zach-park I left a few comments in Figma where you linked above about not having the tabs btw.
