### ISSUE TITLE
[DevOps] Discovery into what is going on with Vista API IAM keys.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90076]
## Description
The frontend and backend prod Vista API services use different sets of Secrets Manager secrets to store an IAM access key ID and secret access key.

Questions:
- Why?
- What does this imply?
- When were these last updated?
- Has this caused problems that nobody noticed?

## Tasks
- [ ] [DevOps] Try to find out what is going on here.
- [ ] [DevOps] Document findings in this thread.
- [ ] [DevOps] Open followup ticket(s) to address.

## Acceptance Criteria
- [ ]
