### ISSUE TITLE
Appoint a Rep - Cross Accredited VSOR - User Test - Conduct Interviews

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#90089]
## Issue Description
Interviews and user test of the 21-22 with cross accredited VSORs.

## Tasks
- [ ] Complete interviews
- [ ] Manage interview day to day (team and recruiter coordination, debriefs, interviews, etc.)
- [ ] Download videos and transcripts
- [ ] Compile notes
- [ ] Upload notes, transcripts, and video to Sharepoint
- [ ] Upload notes and transcripts to EnjoyHQ
- [ ] Create analysis and reporting Zenhub ticket

## Acceptance Criteria
- [ ] All tasks complete

**Comment by jfinnerty13** [comment]
Final top level themes https://dsva.slack.com/archives/C06QVMQV97D/p1724781092661839
