### ISSUE TITLE
IA standards: Updates to vanity URL standards 

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#90080]
Update:  Tighten rules around when we will or will not issue a vanity URL.  Tie this into redirect guidance, which also refers to "claiming URLs". 

### Tasks
- [x] Review/analyze existing documentation and implementation - Mikki
- [x] Establish scope of effort and where guidance lives - Mikki
- [x] Draft revised standard  - Mikki
- [x] Review with appropriate OCTO leads - Mikki
- [x] Create PR - Erin
- [x] PR review - Mikki 
- [x] Publish - Erin
- [x] Communicate out to teams - Mikki

**Comment by mnorthuis** [comment]
### Existing guidance

A vanity URL is a short, simple, memorable and readable URL that utilizes the existing domain (va.gov) and redirects users to a specific page of the va.gov site.

- Example: www.va.gov/vre takes users to https://www.va.gov/careers-employment/vocational-rehabilitation/

A “shortened URL” is a short, simple URL, but is generally made up of a randomized set of characters. VA does not currently provide a URL shortener service. We also do not recommend using external shortening services (i.e. bitly.com) as they can often be blocked and not always trusted by Veterans.

**About vanity URLs**

- The structure of a VA.gov vanity URL is the “va.gov” plus a short 1-2 keyword segment - www.va.gov/[keyword-keyword]
  - We do not use sub-domains for vanity urls (i.e. education.va.gov)
  - We do not use custom top-level domains for vanity urls (i.e. www.va.apply)
- We do not maintain the visibility of the vanity URL in a user’s browser. Once they enter the vanity URL, they are immediately redirected to the appropriate landing page and the actual canonical URL for that page will be displayed in their browser.

**When to use a vanity URL**

- To provide a short and memorable URL for high profile content or tool on va.gov that lives 3 or more levels deep or has a URL with 70 or more characters.
- To provide an easy to remember and speak/type URL for a campaign landing page.

**When not to use a vanity URL:**

- For content that exists external to va.gov.
- For files or documents such as a pdf.
- For content or tools that live within the top 1-2 levels of the site already (i.e. www.va.gov/health-care).
- For content in the Resources and Support area of the site.

**Guidance for choosing a vanity URL**

- Vanity URLs must be easy to say and type, as they are often used in print, video and audio campaigns where users have to understand, remember and then enter them into their browser.
- Avoid the need to change keyboards on a device to enter the vanity URL (i.e. switching between alpha and numeric character keyboards) when possible.
- Ensure assisted tech users easily speak the URL to access it.
- Use keywords that match the meaning and context of the landing page.
- Vanity URL cannot create confusion or alarm when seen out of on it’s own. Vanity URLs are top level URLs of VA.gov, so creating a vanity URL using sensitive or alarming keywords can create confusion if someone encounters it without the context of the campaign message.
- Follow all URL standards when determining your vanity URL, to ensure it is unique, accurate, readable and properly formatted.


### Proposed updates

**[H2]Vanity URLs**
A vanity URL is a short, simple, memorable, and readable URL that utilizes the existing domain (va.gov) and redirects users to a specific page of the va.gov site.

- Example: www.va.gov/trust takes users to https://www.va.gov/initiatives/veteran-trust-in-va/

A “shortened URL” is also a short URL, but is generally made up of a randomized set of characters. VA does not currently provide a URL-shortener service. We do not recommend using external URL-shortener services (i.e. bitly.com or tinyurl.com) as they are often blocked and not always trusted.

**[H3]About vanity URLs**

- Vanity URLs at VA always begin with “www.va.gov” 
  - We do not use or create sub-domains for vanity urls (i.e. education.va.gov)
  - We do not use or create custom top-level domains for vanity urls (i.e. www.va.apply)
- The "vanity" segment of the URL should be short, easy to type, and easy to remember, and should follow the general URL standards in formatting
- We do not maintain the visibility of the vanity URL in a user’s browser. Once they enter the vanity URL, they are immediately redirected to the appropriate landing page and the actual canonical URL for that page will be displayed in their browser.

**[H3]When to use a vanity URL**

- To provide a short and memorable URL for campaigns that meet the following criteria
  - Campaign is for Veterans or their family members and caregivers
  - AND has a national level focus (not just for a local facility or single area)
  - AND has a campaign landing page that the vanity URL will point to


**[H3]When not to use a vanity URL:**

- For content that exists external to va.gov
- For files or documents such as a pdf
- For general benefit content or tools (i.e. www.va.gov/health-care).
- For content in Resources and support
- To "claim" a URL that doesn't have content 

**[H3]Guidance for choosing a vanity URL**

- Vanity URLs must be easy to say and type because they are often used in print, video and audio campaigns where users have to understand, remember, and sometimes manually enter them into their browser.
- Use keywords that match the meaning and context of the landing page and ensure the meaning is upheld when shortening titles to just a few keywords. For example, shortening a campaign called "Eligibility for disability compensation" to just www.va.gov/eligibility results in an overly broad URL that can be misunderstood outside of the campaign messaging. 
- A vanity URL should not include sensitive or alarming keywords that could create confusion when seen out of context on it’s own (i.e. www.va.gov/evacuation).  
- Follow all general URL standards to ensure it is unique, accurate, readable and properly formatted.


**[H2] Vanity URL requests and implementation process**
Vanity URL requests must be submitted to VA.gov Information Architecture for validation, approval, and implementation.

[action link]Submit a vanity URL request on GitHub

**Comment by mnorthuis** [comment]
@erinrwhite would love your feedback

My goal is to tighten this guidance so it discourages vanity URL requests for anything other than large campaigns.

**Comment by erinrwhite** [comment]
@mnorthuis This draft is looking good - I think the criteria are helpful. Were you hoping to pull this out as a child page under URLs, or leave as part of that parent URLs page?

**Comment by mnorthuis** [comment]
Let's pull it out as a child page.

**Comment by erinrwhite** [comment]
[PR created!](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3293) Combining efforts with the sub-URL guidance in #88407

**Comment by erinrwhite** [comment]
[Vanity URLs guidance updated](https://design.va.gov/components/url-standards/vanity-urls) - over to @mnorthuis for sharing w/teams

**Comment by mnorthuis** [comment]
communicated out, closing issue
