### ISSUE TITLE
[ENG] 10-10CG - Facilities Selection: Familiarize with initiative, designs & current progress

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#90097]
## Background
We are ready to pick the CG Facilities work back up, but we need to make sure we are confident in the direction, functionality, and designs, as well as where we left off.

There is work existing behind a feature toggle that has the Search page and Results page developed, however we were waiting on Lighthouse and Facilities APIs to be updated with the information we need (parent facility with CG support mapping with Veteran selected facility).

## Tasks
- [x] Review documentation
     - [x] [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
     - [x] [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19433)
     - [x] [Figma Designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2346-26823&t=0QqRP67JIvlL793d-0) (Jessica is working to make the final design more clear & identifyable)
- [x] Review with team and/or PM on designs, functionality and any questions
- [x] Talk with Matt K and Josh on the work they did, any questions they pondered still outstanding, and any blockers (outside of Lighthouse API)
- [x] Review tickets remaining
     - [x]  #70846
     - [x]  #70847
     - [x]  #61768
     - [x]  #61786

## Acceptance Criteria
- Teammember will have a clear understanding of what has been done, what is remaining, and what outcome we are working toward.
