### ISSUE TITLE
DR | Create DD Dashboard for Form Submission Storage

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#90103]
## Value Statement

**_As a_** developer

**_I want to_** have a DD dashboard for form submission storage/updates/deletions

**_So that_** I can monitor the health of the form submission storage process

---

## Background Context

After #84329 and the associated tickets are completed, we want to have a DD dashboard to observe and monitor the health of the storage process. This will also allow for alerts to be configured as necessary.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Datadog dashboard to observe form submission storage metrics

## Acceptance Criteria

- [x] A datadog dashboard is created that summarizes the necessary stats (creations/updates/deletions)

### Enablement team (if needed)
@ member of team

## Open questions

- Add here

## Tasks

- [x] Add metrics for tracking creation/update/deletion stats
- [x] Create datadog dashboard

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Submitted request to YourIT for permissions to create dashboards in datadog

**Comment by dfong-adh** [comment]
New dashboard created: https://vagov.ddog-gov.com/dashboard/fps-2wj-ceb

**Comment by dfong-adh** [comment]
Dashboard updated with Evidence status charts and tables.

**Comment by eileen-coforma** [comment]
Set up dashboard to go over with the team

**Comment by dfong-adh** [comment]
Dashboard updated with evidence error details.
