### ISSUE TITLE
[DevOps] Discovery on VistA Office Review Board Intake Form

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90107]
## Description
Followup to #89978.

My understanding is that this process is necessary to be assigned a service account for use with VistA.

VistA has a customer portal: https://dvagov.sharepoint.com/sites/OITEPMOVistAOffice/SitePages/VO-Customer-Portal.aspx

I need to complete this form to proceed with intake: https://dvagov.sharepoint.com/sites/OITEPMOVistAOffice/SitePages/VistA%20Office%20Review%20Board%20Form.aspx

I'm currently reviewing the VORB Review Request Process Guide to figure out the finer points of this.

## Tasks
- [x] [DevOps] Read the VORB Review Request Process Guide to determine what is needed.
- [x] [DevOps] Determine whether we have sufficient information to complete and submit the form.
- [x] [DevOps] If so, complete and submit the form.
- [x] [DevOps] If not, open followup ticket(s) to collect that information.

## Acceptance Criteria
- [x] Form is completed and submitted, or
- [ ] Followup ticket(s) opened to address problems.

**Comment by ndouglas** [comment]
## Things I know
- Title of the Request
- Requestor
- Requested Completion Date
- Detailed Description of Request: eh, I'll come up with something
- Additional Information: 
- What is the origin of the system/application users?: My understanding is that this should be Veteran self-service.
  - Internal User (SSOi) = VA Employee
  - External User (SSOe) = Non-VA (Non-VA Provider)
  - Other Federal Agencies
  - Veteran self-service
  - Other
- How many users does the system/application have?: Greater than 1000.
- Where does the application/system reside?: Cloud AWS, Azure.
  - VA Data Center
  - Non-VA Data Center
  - Cloud AWS, Azure
  - Other
- Does the system/application have an approved ATO?: Yes
- EMASS ID:
- VASI ID: 

## Things I don't know:
- Does or will this application/product use VDIF as middleware to connect to VistA?: I think the answer is no, need to confirm.
- How does the system/application connect and authenticate to VistA? (If Applicable): My understanding is this is one of the VistALink options.
  - N/A
  - Reflections via A/V
  - Reflections via IAM STS Token
  - RPC broker via A/V
  - RPC Broker via IAM STS Token
  - RPC Broker via BSE Token
  - VistALink via A/V
  - VistALink via IAM STS Token
  - HL7
  - Other
- What is the authorization process for your system/application user(s) to access VistA? (If Applicable): 
  - MenuMan Options/Security Keys
  - RPC Broker B-type options
  - HL7 sending application/receiving application
  - Web Endpoint Options
  - Other
  - N/A
- What are the types of users for the system/application?
  - Human
  - Application
  - BOT
- Please provide an Architectural Diagram:
- Please provide any additional supporting documentation:

**Comment by ndouglas** [comment]
gonna tell ~my kids~ VORB this was our architecture

![Screenshot 2024-08-07 at 9 27 46 AM](https://github.com/user-attachments/assets/ffd2d412-e961-4cc7-885b-974c8b2a3f7b)

**Comment by ndouglas** [comment]
I filled out and submitted this form to the best of my ability. I included @olivereri as a second point of contact 🚌 📏
