### ISSUE TITLE
Manual Staging/dev deploy workflow failing build

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90115]
## Issue Description
When a manual staging/dev deployment is done, the build step is failing. It appears that this build is using an old build method and has not been kept in sync with the way CI and deployment does builds. We need to get this workflow caught up to prevent errors. 

---
## Tasks
- [x] Update the workflow to the current build method/runners to see if it resolves the issue.
- [x] If not, further diagnose the issue.
- [x] Fix the error so the build passes every time its run.
- [x] Test both the dev and staging environments to ensure they deploy correctly.

## Acceptance Criteria
- [x] Manual staging/dev deployments can once again be triggered and complete successfully.
