### ISSUE TITLE
Unit test Stability Review - processes not completing

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90119]
## Issue Description
The [unit test stability review](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/10259122439/job/28383128943) processes are erroring with an exit code of 1 and are not finishing. The result of this is causing there to be no results files to do any processing of. This needs to be fixed to ensure that bad unit tests are addressed accordingly.

---

## Tasks
- [ ] Diagnose the error with unit test runs
- [ ] Correct the error if possible. Ensure that memory is being managed with the Mocha process.

## Acceptance Criteria
- [ ] The unit test stability review can complete successfully and is quarantining tests accordingly again.
