### ISSUE TITLE
Puma Tuning Improvements White Paper

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#90111]
When we have finalized our performance tuning of Puma and EKS, we should have a whitepaper outlining improvements and cost savings now that Vets API doesn't require overprovisioning.

## Tasks

- [x] Collect information on what was tuned
- [x] Determine the average number of nodes required throughout the day compared to our previous requirements (which was 45 nodes)
- [x] Determine the approximate cost difference

## Acceptance Criteria

- [x] A whitepaper is available in Confluence that outline performance and cost changes related to Vets API's Puma/EKS tuning epic

**Comment by ericboehs** [comment]
Can't releize these benefits until we #92667.

**Comment by ericboehs** [comment]
On hold until 504s due to scaling is resolved.

**Comment by ericboehs** [comment]
Proceeded with the assumption that benefits will be realized once EKS Next resolves 504s.

[Optimizing EKS Cluster Efficiency: Infrastructure Cost Reduction Through Dynamic Pod Management - Platform Reliability Team - Confluence](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3797385269/Optimizing+EKS+Cluster+Efficiency+Infrastructure+Cost+Reduction+Through+Dynamic+Pod+Management)
