### ISSUE TITLE
UX analytics: Set up report for tracking clicks / engagement on LP

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#90116]
## Description

HIGH PRIORITY
What are users doing / clicking on on the landing page?

### User story

As a Cartography team member, I want to understand what users are doing / clicking on on the landing page.

### Notes
- Use GA4; we learned last sprint that Datadog is failing to capture clicks
- Track every url on the landing page and on the MR interstitial page
- Wes has already built a report that tracks most of the clicks on the landing page: [see the "Link clicks" tab in this Exploration](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/dvxmtHCqTaaeZKalrojazw)

Possible tasks:
- [ ] Attend analytics office hours and/or watch past trainings to gain understanding 
- [ ] Validate what you create w Jamie Stutt and / or Wes Rowe

## Acceptance criteria
- [x] Landing page link clicks are tracked in GA4 report

**Comment by wesrowe** [comment]
I added in Notes the already-built GA report that @fmccaf1 and I looked at today: [link clicks on the MHV Home page](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/dvxmtHCqTaaeZKalrojazw).

**Comment by fmccaf1** [comment]
[Worked with the data in this spreadsheet.](https://agile6-my.sharepoint.com/:x:/p/florence_mccafferty/EX2iJaezgztKtotjqwvrwPcBWmZjpLlU_bDxpz5kFqHI_A?e=xJzKS5)
