### ISSUE TITLE
Update Office Hours Slack Message

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90117]
## Pain Point
No one has attended Content Team Office Hours in several months. This valuable resource for communicating with VFS teams is not being used, and it deserves greater awareness.

## Issue Description

- Content Office Hours Slackbot reminder is set for Friday 12pm ET in the #platform-content Slack channel. 
- We should consider using the same workflow concept as the Analytics Team, where there is no RSVP, just a reminder in the channel 15-30min. prior to Office Hours, and a link to the Zoom meeting.

---
## Tasks
- [x] Test: Reschedule the reminder for every Tuesday, 2pm ET, in the #platform-content Slack channel
- [ ] Record results, if any on 9/17

## Acceptance Criteria
- [x] Reminder is scheduled to post every week
- [ ] Results recorded, additional tasks added as necessary 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Slack workflow updated and working as intended, no further effort necessary, closing ticket.
