### ISSUE TITLE
[CST] Update 5103 evidence waiver submission to synchronous task

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#90129]
## Value Statement
**_As a_** Veteran
**_I want to_** see that submitting the evidence waiver removed the 5103 tracked item alert
**_So that_** I can feel confident that there is no longer any action required of me to resolve the 5103 tracked item request

---
## Background Context

Currently, when the user submits the 5103 evidence waiver, they see the confirmation message but the 5103 alert is still showing up. This is confusing, since the user has completed the action required of them and the request should be gone.

<img width="763" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDQ1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92a1637a0b533b7bb35a4146fc49f5abaaac5df3/Screenshot%202024-08-06%20at%206.29.01%E2%80%AFPM.png" alt="Screenshot 2024-08-06 at 6.29.01 PM.png" />

We've [discussed this in the past](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82575#issuecomment-2196006552) but have yet to implement this for 5103. 

We are currently working this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/76660 to do the same thing for file uploads. Once we figure out how to do the asynchronous task for other evidence uploads, we can then figure it out for 5103.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] __
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _After a user submits the evidence waiver for a Standard 5103 or Custom 5103 via the document request page, and the user has received confirmation that the waiver was submitted, the 1P alert for 5103 should no longer be showing in the Status and Files tab_
- [ ] _AC_
- [ ] _AC_

**Comment by skylerschain** [comment]
Staging Review ticket related to this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/90129

**Comment by skylerschain** [comment]
I think we are doing Document Status (showing "In progress" state) instead of making this a synchronous task.

@jerekshoe @jacobworrell does that sound right to you? If so, we can close this.
