### ISSUE TITLE
[FE] Build LOA1 Account Security Screen

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#9012]
## User story

We realized we need to create a profile design for users who are LOA1 and hide certain features of the profile

From Slack:
Right now, LOA1 users can view the account settings page to verify their identities, add 2FA, and see info on how to update their sign-in email address. But for the profile, they can't view it at all because we don't know they are who they say they are. That's great and works for an approach where profile and account are two separate pages.
However, we can't take the same approach with Profile 2.0 and just hide the whole profile from LOA1 users because they still need to see the options to verify their identity, add 2FA, and update their sign in email addresses. This means we need an LOA1 version of the profile which is basically the account settings stuff only.

## Additional background

Epic #

## Design & Specs

- [InVision prototype](https://vsateams.invisionapp.com/share/2BX9CAY89GN)
![Screen Shot 2020-05-12 at 11.48.51 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/18aafb68-b27e-4b6e-8e96-3b051b4cd80c)
![Screen Shot 2020-05-12 at 11.49.02 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/048d7d85-4329-4c26-8467-cacf4870aac5)

##Copy
**ALERT:** 
Verify your identity to view your profile 

We need to make sure you’re you - and not someone pretending to be you - before we can give you access to your personal and health-related information.  This helps to keep your information safe, and to prevent fraud and identity theft.  

**This one-time process takes about 5-10 minutes.**

**DROPDOWN:** 
How will VA.gov verify my identity?

We use ID.me, our Veteran-owned technology partner that provides the strongest identity verification system available to prevent fraud and identity theft.

**To verify your identity, you’ll need both of these:**

- A smartphone (or a landline or mobile phone and a computer with an Internet connection), 
**and**
- Your Social Security number

**You’ll also need one of these:**

- A digital image of your driver’s license or passport,
**or**
- The ability to answer certain questions based on private and public data (like your credit report or mortgage history) to prove you’re you

## Tasks

- [x] Build the LOA1 Account Security Screen
- [x] Implement correct copy.
- [ ] Get Tressa to test out this section and make sure it looks OK.

## Acceptance criteria

- [ ] This section has been built and reviewed by Tressa.

**Comment by erikphansen** [comment]
I changed to a 3 because everything we do on the profile is proving to be more complicated than we expect.

**Comment by sanlouise** [comment]
@mshea0606 @tressaellen @Samara-Strauss 

- The profile wrapper PR took care of hiding any other routes than /account-security when the user is LOA1. 

- We already have a component with almost identical text that shows in Profile 2 in the identity verification row when the user is LOA1 (src/applications/personalization/profile-2/components/IdentityVerificationStatus.jsx)

To make sure I understand the requirements of this ticket:

(1) We want to show the Alert outside of the table when LOA1
(2) We still want to show the existing confirmation that the identity is verified when LOA3 in teh table

So this ticket only takes care of a design/minor copy change?

**Comment by Samara-Strauss** [comment]
> (1) We want to show the Alert outside of the table when LOA1
> (2) We still want to show the existing confirmation that the identity is verified when LOA3 in the table

Yes, I believe this is correct:

- For LOA1 users, we'll show the "verify your identity" alert above the table and no longer have the identity verification row in the table.
- Yes, no changes to the LOA3 account settings layout.

**Comment by sanlouise** [comment]
@mshea0606 This ticket is ready for validation whenever you have a moment 😄

**Comment by mshea0606** [comment]
I just tried to validate this ticket, it appears it is not in staging yet. I am waiting for the update from @sanlouise that is is available in staging and I will validate this ticket asap.
