### ISSUE TITLE
[FE] 10-10EZR TERA Improvements: Create branching logic based on Veteran's birth date

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#90130]
## Background
As a result of usability testing for TERA by the EZ/CG team, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. 

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By introducing branching logic to the TERA questions, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721926812596/33735a713bc60e29e0eedefe21c0bca6769c6ada?sender=ubf5503bf47b6eb1e92730053)

## Tasks
- [x] Update/create branching logic of questions so that the birth date determines the TERA questions that display to the Veteran
- [x] Review with the team/PM to confirm expected behavior
     - PM signoff is required to be documented in the comments below
- [x] Inform QA/Team when the updates are ready to start testing 

## Acceptance Criteria
- The Toxic Exposure questions displayed based on time period compared to the Veteran's birth date.
- The updates are ready for QA testing

**Comment by JoshingYou1** [comment]
@alexseelig Can you please sign off on the review when you have a chance?

**Comment by alexseelig** [comment]
I'm good!

**Comment by JoshingYou1** [comment]
There's an issue with the app loading when trying to place the branching logic behind a feature toggle. I've created a platform ticket here: https://dsva.slack.com/archives/CBU0KDSB1/p1724857807444519

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that this has been implemented and working as expected. 

Test cases linked here in [Testrail](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_id=26031&group_order=asc&display_deleted_cases=0)
E2E test link in slack [here](https://dsva.slack.com/archives/CMJ2V70UV/p1731083273799339)

**Comment by allanto-ah** [comment]
Once this is merged, we can can close this ticket
