### ISSUE TITLE
[FE] 10-10EZR - TERA Improvements: Update Gulf War locations question to display only applicable locations

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#90134]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. To improve this experience, we are going to add logic to the Gulf War locations question, based on the time period for each location, so that we are displaying only those locations that were in effect after the Veteran's birth date.

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By displaying the Gulf War locations question based on time period, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721926812596/33735a713bc60e29e0eedefe21c0bca6769c6ada?sender=ubf5503bf47b6eb1e92730053)
- [Figma designs for content](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=4069-48334&t=OqU5Xap8dTeYJ97T-1)

## Tasks
- [x] Update the Gulf War locations question so that only those locations that were in effect after the Veteran's birth date will display
     - Pending age limit confirmation from HEC
     - This could mean that all or a subset of locations will display
- [x] Review with the team/PM to confirm expected behavior
     - PM signoff is required to be documented in the comments below
- [x] Inform QA/Team when ready to start testing

## Acceptance Criteria
- The Gulf War location question displays only those applicable locations based on time period compared to the Veteran's birth date.
- The updates are ready for QA testing

**Comment by JoshingYou1** [comment]
Demo'd to @IMHieuVo and @RenataKeck on 11/22. Found a small content error that has since been corrected.

**Comment by allanto-ah** [comment]
Environment: RI

@JoshingYou1 I found two minor UI issues. I'll post them in two separate comments

### Issue 1: In the "Learn more about enhanced eligibility status for VA health care" collapsible link on the page where the user is asked if they want to provide TERA information, there should be line breaks where the red arrows are in the screenshot. The left is Figma and the right is the RI
![Image](https://github.com/user-attachments/assets/a8a89382-e08b-48a6-9672-dc927839d202)

**Comment by allanto-ah** [comment]
Environment: RI

Verified that Issue 1 has been fixed. 

![Image](https://github.com/user-attachments/assets/8b567e85-d55c-4a30-a2e9-ecbfe7ddb211)

**Comment by allanto-ah** [comment]
QA has been completed and results can be found in the QA [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90135)
