### ISSUE TITLE
[QA] 10-10EZR - TERA Improvements: Testing branching logic based on Veteran's birth date

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#90133]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. 

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By introducing branching logic to the TERA questions, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721926812596/33735a713bc60e29e0eedefe21c0bca6769c6ada?sender=ubf5503bf47b6eb1e92730053)

## Tasks
- [x] Create test cases based on designs and user flow
- [x] Perform testing on the branching logic of TERA questions that display based on birth date
- [x] Conduct E2E testing to make sure correct data still makes it to VES
- [x] Review with the team/PM to confirm expected behavior
     - PM signoff is required to be documented in the comments below
- [x] QA results and signoff are required to be documented in the comments below
- [x] Inform team that the effort has completed QA and is ready for launch

## Acceptance Criteria
- The Toxic Exposure questions displayed based on time period compared to the Veteran's birth date.
- The updates are ready for launch

**Comment by allanto-ah** [comment]
Testing has been completed for this task. The results can be found in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90130). Closing this ticket.
