### ISSUE TITLE
[QA] 10-10EZR - TERA Improvements: Testing Gulf War locations question to display only applicable locations

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#90135]
## Background
As a result of usability testing, we're making changes to introduce branching logic so we only ask questions that are relevant to the user's birth date. To improve this experience, we are going to add logic to the Gulf War locations question, based on the time period for each location, so that we are displaying only those locations that were in effect after the Veteran's birth date.

## Benefit to the Veteran
In [usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2024-04-ToxicExposure-UsabilityStudy/research-findings.md), we heard Veterans repeatedly say the TERA questions seemed generic and they thought some of the questions should be eliminated based on previous answers or things VA already knows about them. By displaying the Gulf War locations question based on time period, we'll create a smarter form flow that cuts down on the time it takes the Veteran to complete the questions by only asking about toxic exposure that may have occurred during their service dates.

### Resources
- [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721926812596/33735a713bc60e29e0eedefe21c0bca6769c6ada?sender=ubf5503bf47b6eb1e92730053)
- [Figma designs for content](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=4069-48334&t=OqU5Xap8dTeYJ97T-1)

## Tasks
- [x] Create test cases based on designs and user flow
- [x] Perform testing on the Gulf War locations question changes
- [x] Review with the team/PM to confirm expected behavior
     - PM signoff required to be documented in comments below
- [x] QA results and signoff required to be documented in comments below
- [x] Inform team that the effort has completed QA and is ready for launch

## Acceptance Criteria
- The Gulf War location question displays only those applicable locations based on time period compared to the Veteran's birth date.
- The updates are ready for launch

**Comment by allanto-ah** [comment]
Environment: RI

Verified the Gulf War locations questions branching logic update is working as expected. 

E2E [link](https://dsva.slack.com/archives/CMJ2V70UV/p1733508435035199)

Test cases:
[tera-v2-branching-logic.pdf](https://github.com/user-attachments/files/18101266/tera-v2-branching-logic.pdf)
