### ISSUE TITLE
Define scope for PO Sync

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#90156]
## User Story
As a Governance team member, I want to understand what OCTO is hoping to achieve with the introduction of the PO Sync so that I can plan the new sync accordingly.

Assignee: @shiragoodman 

## Description
As we begin work for this initiative, we need to understand the level of effort, availability and goals of our OCTO-DE leads so that we can build a solution that is easily upheld and not burdensome for anyone involved.

### Notes from MD 8/15
No time taken to review product brief and KO tickets until seen at DI. No expectation with OCTO PO that anyone is looking at it and pushing back and/or questioning. FB from OCTO POs:
1. no vision/strat/place for discussion around that stuff
2. perception that teams are overlapping. Per Kevin, "overlapping work across teams is perceived as a problem when it is unavoidable at an enterprise" aka someone is stepping on my toes. 50+ teams, they can't all work in a silo. 
What area of the site are you working in specifically?
  - come up with a list of options. what portfolio? benefits, health, etc.

### Notes from Refinement 8/8, responses from Matt on 8/15

- What is the outcome for a VFS team?
   - Likely differs between OCTO teams and non-OCTO teams?
   - For OCTO teams, blessing from Matt and Danielle
   - MD: Outcome for Danielle and I, get a chance to understand the purpose and vision behind the work tht the team is doing. Hoping some of these conovs will be short. D might have more. iterating or ne work is a helpful thing. 
   - different convo with non-OCTO PO. 
   - MVP is for OCTO POs only. Danielle likely knows more since teams have to go through CAIA if they want content help.
   - outcome - we know early on whether they should be talking to the mobile team or not.
   - non-octo - triage which projects should be escalated to CJ. 
   - OCTO PO - them to understand resource constraint and prioritization amongst shared services. may have to tell teams that they need to wait.
- What artifacts is OCTO looking for?
   - Are they having discussions around IA, content, design, a11y? If so, and Gov is not there to hear it, this could be problematic.
   - MD: more at a product level. understanding the context of what they're doing and how it fits the vision.
   - Governance wants to be assured that practice area specific guidance or recommendations aren't taking place at this meeting.
   - MD: product brief template* (completed!). not just product outline. both should be complete. start there. 
 - Who from OCTO needs to be there?
    - concerns about OCTO schedules
    - MD: Danielle and I, Mikki, Martha, Shane, Ryan (Kevin's design leads)
 - Should VFS be there?
   - OCTO only!
 - Appointment or adhoc?
    - set time. 
 - how long would a call be?
    - 30 min. 
 - When should the call occur ?
    - MD: post kickoff, however if this fails, we'll know to move earlier.
 - Is this a required touchpoint?
    - MDL for OCTO yes.
 - Can VFS teams bypass this and go straight to DI?
    - MD: they cannot have DI until this convo takes place
 - Is there a green light to go ahead? Who gives it? How is it communicated?
    - MD: intent isn't to block them. If they're doing something that raises a red flag, then we'll determine how we deal with this. We're not the experts in all things. more education and knowledge sharing. more about giving us context for the initial discussion. they can schedule the DI.
 - In KO we ask for a product outline, this seems like "bring your outline to the conversation." This is the 1st step.
 - Do we as Gov team need to know anything other than the greenlight outcome?
    - MD:  if so, Matt and Danielle will take notes and put something somewhere.
 - If there are situations where teams are not proceeding, there needs to be a process in place for closing the ticket.
    - MD:  sounds good.
 - Gov doesn't respond to kickoff until AFTER this new PO Sync occurs.
    - MD: as long as we don't become a bottleneck.
 - We need a way to have OCTO communicate to us that this took place. 

## Tasks
- [x] Meet with Matt to ask teams questions from refinement, and clarify expectations from Matt
- [x] Draft proposal of what new PO sync would look like, how it would be incorporated into the Collab Cycle, who it's for, what artifacts are required, and what the expected outcome would be.
   - [PO Sync - proposal](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3407773924/PO+Sync+-+proposal)
- [x] Share with Matt and Danielle for their review and feedback.
- [ ] Incorporate any feedback, if critical, into proposal

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have defined the scope for the new Collaboration Cycle touchpoint - the PO Sync
- [ ] We have received OCTO approval to move forward with implementation

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Draft proposal shared with Danielle and Matt on 8/26.

**Comment by shiragoodman** [comment]
This ticket is closed as of 8/28/2024.
