### ISSUE TITLE
GA4 & BigQuery Audit

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#90164]
### Description
 This ticket is to account for the work that we are doing for our audit of our Google Analytics Properties and BigQuery.
 
_This was unplanned work for the sprint, but given we've been spending significant time on it, we are injecting it into our sprint. Details of the audit can be found in the postmortem in the sensitive repo_

---

### Tasks

- [x] Perform audit of Google Analytics 4 Property
- [x] Perform audit of Google BigQuery
- [x] If needed, perform audit of Domo.
- [x] Log findings in postmortem

### Acceptance Criteria

- [x] Findings from audit have been shared in private Slack message.
- [x] Findings and outcome have been logged in postmortem.

**Comment by johnny-jesensky-adhoc** [comment]
FYI -- this ticket is to account for the work that we are doing for our audit. This was unplanned work for the sprint, but given we've been spending significant time on it, so are injecting it into our sprint.

Will likely be removing a few other tickets to make room for this.

FYI @raywangoctova, @jwoodman5 , @dorseypa1, @jestutt

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt -- as discussed, this overall audit effort will continue into the following sprint, but we've made progress on the tasks outlined in this ticket, so marking this one as _**Done**_. We've created a separate tasks to account for Jamie's work on this, here (#90681).

FYI @dorseypa1
