### ISSUE TITLE
Groom VAOS KPIs for the Product Success Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9016]
## User Story or Problem Statement
How might we understand the requirements for adding VAOS KPIs to Domo so that when we start building on Domo, we can share which metrics we can add, which metrics will have a BigQuery or a GTM dependency, and how we can proceed with building?

## Goal
Determine efforts and sources of provided KPIs.

---
## Tasks
- [ ] Determine data sources for each KPI
- [ ] Determine dependencies for KPIs (BigQuery or GTM)

## Acceptance Criteria
- [ ] VSP Analytics has sources & dependencies for provided KPIs

---

## Links

**Comment by bsmartin-ep** [comment]
@joanneesteban -

Here's an (almost done) doc with GA links for these KPIs / metrics:

https://docs.google.com/document/d/1EbyzheTkLZa8WAdInXImolduOggwReEflIzJTDBnPuk/edit#

I messaged Lenae in the primary ticket about this one:

> KPI - # of Veterans who schedule an appointment ongoing

@jonwehausen -

> KPI - Success/failure rate per scheduling type (VA Request, CC Request, Self Schedule)

We're still limited to just _va-request_ in the VAOS flow CD, correct?

![image](https://user-images.githubusercontent.com/62304138/82674838-e3e47a00-9c11-11ea-8979-bc20911a651d.png)

**Comment by bsmartin-ep** [comment]
@joanneesteban -

I believe these GA links are ready for Lenae...

https://docs.google.com/document/d/1EbyzheTkLZa8WAdInXImolduOggwReEflIzJTDBnPuk/edit?usp=sharing

The far majority are events with the _vaos-_ prefix so only a single dataset is needed for those.  I created two custom funnels but those are just visualizations of _vaos-_ events.

Really the only somewhat "special" case is the Frequency and Recency report, which will require us to have a dataset with _Count of Sessions_ and _Days Since Last Session_ dimensions and a custom segment:

> KPI - # and frequency of Veterans returning to VAOS - [Frequency & Recency report ](https://analytics.google.com/analytics/web/#/report/visitors-frequency-recency/a50123418w177519031p176188361/_.useg=user9Jr_6XpMRJ-e09dZxubM6Q&histogramTab-sectionControl.sectionId=count/) with[ custom segment](https://analytics.google.com/analytics/web/template?uid=g4pL5jrQT5-1jKhCutmVew)

**Comment by bsmartin-ep** [comment]
Closing.

https://va-gov.domo.com/page/565662008?userId=2108773409
