### ISSUE TITLE
Finalize Domo Dataset Review & QC

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#90174]
### Description
This ticket is to account for the remaining QC items flagged on our Confluence page found from our priority reports.

- [Round 3 Domo Data QC Checks](https://vfs.atlassian.net/wiki/spaces/AT/pages/3318775809/Round+3+Domo+Data+QC+Checks)

- Follow up with Phil for any changes that need to be made to the dataset.
- Look for and document differences in variable names, formatting, etc.
- Check if event labels, categories, actions -- etc that are used within BeastModes
- If data issue, or discrepancy is found, mark in ticket and notify team.
- Document findings from QC, and potential changes [here](https://vfs.atlassian.net/wiki/spaces/AT/pages/3149791233/GA4+Documentation+Data+QC+Mapping).

---

### Tasks

- [x] Work with Phil to resolve remaining data QC items.
- [x] Mark any _Open_ issues as Resolved after addressing them.

### Acceptance Criteria

- [x] Remaining dataset issues have all been marked as _Resolved_.

**Comment by Blivaditis** [comment]
Three datasets marked as not appended, and four open metric discrepancies we have made a ton of progress on appends and pushing data. Will continue to work on solving these in the next sprint.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks for the update @Blivaditis -- planning to keep this one open until we finalize the outstanding datasets.

FYI @ChristineYoungZA, @jwoodman5

**Comment by Blivaditis** [comment]
Wanted to make sure the work done this sprint is properly reflected in the closed out tickets.

**Comment by johnny-jesensky-adhoc** [comment]
Given our progress here, I'm moving this to _**Done**_. We have some questions around the Combined Debt Portal dataset, which I have moved to another ticket, as may require a closer look at GA as well.

- [Round 3: Domo Data QC Checks](https://vfs.atlassian.net/wiki/spaces/AT/pages/3318775809/Round+3+Domo+Data+QC+Checks)

FYI @Blivaditis, @dorseypa1, @ChristineYoungZA
