### ISSUE TITLE
ITF | Generate participant_id for all veterans missing one 

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#90176]
# Overview 
Before we can [manually generate ITF's](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81413) for veterans, we need to create `participant_id` for any veterans that are missing one.

# Order
#90364 - First because it addresses the overall issue and should prevent future cases
#90176 - (this one) -  This ticket sets the participant_id for all of the pension in_progress veterans.
#81413 - Last because it is the remediation for the overall issue

# Tasks
- [ ] - Get a count for how many pension veterans are lacking `participant_id` 
- [ ] - Using work that has been in this [ticket](https://github.com/department-of-veterans-affairs/vets-api/pull/17741) as a model, generate participant_id for those veterans
- [ ] - Post a report of any success/failure counts.

**Comment by mjknight50** [comment]
Setting this one as blocked by:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/90364

**Comment by aplatt-coforma** [comment]
We are going to backlog this ticket for now. We feel the right place to make this change is within LightHouse and will wait for them to prioritize the work. In the interim we are monitoring the number of effected veterans and reporting on those in our sprint reviews.

**Comment by matt4su** [comment]
Suggest change occurs in Lighthouse
