### ISSUE TITLE
Toxic Exposure 1.0: update submitted to primary scope for reporting

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#90175]
Essentially, we want the definition of success for the primary path to be updated to include the 526 pdf submission polling for 2022 claims only.

### Tasks
- [x] add to scope `accepted_to_primary_path` - accepted means there's a submitted claimId - if the claim is submitted to LH the 526 pdf polling job is status "success" 
- [x] create new scope to granularly report on the `pdf_not_found `status - this reports out on the ones that don't have a successful pdf polling job
- [x] add to this documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_scopes.md#accepted_to_primary_path

### Additional Information
Simply having the claim ID isn't actually a truthful measure of "success", as background jobs can fail, systems can timeout, the pdf can fail to generate, etc. so we've moved in the direction of considering "success" to mean that the pdf is in the Vet's eFolder as this
