### ISSUE TITLE
Collaboration Cycle for Decision Reviews Team, Higher-Level Review, Form Updates

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#90188]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1375) for all feedback and findings tickets associated with this Collaboration Cycle initiative. 
 
### VFS team name

Benefits Decision Review

### Product name

Higher Level Review

### Feature name

N/A

### GitHub label for team

Decision-Reviews-Team

### GitHub label for product

HLR

### Public DSVA Slack channel for VFS team

#benefits-decision-reviews

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

May 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

No

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

Yes

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/README.md

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

### Notify the Collaboration Cycle team of this ticket in your team's public Slack channel.

- [ ] I acknowledge that I must notify the Governance team by completing the Collab Cycle Kickoff workflow in my team's Slack channel after submitting this issue. This can be completed by typing "/collab cycle" and selecting the kickoff workflow.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C5AGLBNRK/p1723053428042859)
</details>

### PO Sync
<details open>
  <summary>Toggle PO Sync instructions</summary>

##### OCTO Product Owner
- [x] Review [PO Sync Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/po-sync) to understand what this sync involves.
- [ ] Schedule your PO Sync (with at least 2 business days lead time from now):
  - Open the [Calendly PO Sync calendar](https://calendly.com/collaboration-cycle/po-sync)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Schedule Event"
- [ ] Link all artifacts in the `PO Sync artifacts for review` section below at least two business days before the scheduled PO Sync. Please don't add artifacts in the comments section.

**PO Sync artifacts for review**
[See guidance on PO Sync artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/po-sync#POSync-Whatartifactswillbeneeded?) Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] Product outline

Optional:
- [ ] Any other artifacts you have so far

##### Governance Team actions
- [ ] Meeting date/time:

##### OCTO Design Leads
- [ ] If the initiative receives OCTO alignment to proceed, add the PO-Sync-approved label to this ticket.
- [ ] If the initiative does not receive OCTO alignment to proceed, comment and close this ticket. 

</details>

### Design Intent

<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [ ] No feedback
- IA
  - [ ] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  

</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Midpoint Review

<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [ ] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [ ] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [ ] Design prototype or high-fidelity mockup (must include mobile prototype/mockup)
  - Specify which pages are included in the review
- [ ] Up to date user flow
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), link to CAIA intake ticket. 

**Not required, but nice to have artifacts**
- [ ] Accessibility annotations included as part of your design
- [ ] Research plan
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
 
##### Platform actions
- [ ] Slack thread with VFS team
- [ ] Meeting date/time:

##### Platform actions

* Accessibility
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [ ] No feedback
* IA
  * [ ] Feedback added to milestone
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode: 
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns

</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below

</details>

### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [x] Link to the Contact Center review request ticket below

</details>

### Staging Review
<details>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [ ] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/experimental-design/), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [ ] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).

**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

#### Required artifacts
  - [x] **URL(s) to review the product**: https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996
    
    Overview of updates:
    - Updating introduction to add MST resource information (Introduction)
    - Adding question about homelessness (Section 1: Veteran information)
    - Updates to "Issues for review" content (Section 2: Issues for review)
    - Updates to "Informal conference" content (Section 3: Informal conference)
    - Added a screen to “Informal conference” to choose who to contact (Section 3: Informal conference)
    - Updates to "Review application" content (Section 4: Review application)

  - [x] **Entry points to access HLR**:
  - https://staging.va.gov/decision-reviews/
  - https://staging.va.gov/decision-reviews/higher-level-review/
  - https://staging.va.gov/resources/choosing-a-decision-review-option/

  - [x] **Test users and scenarios**
    Test user information: Use [test user vetsgov+test233@id.me](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md)
  - [x] **[Link to Sitewide CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90188), if applicable.**
  - [ ] **[Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91384)**
  - [ ] **QA Artifacts**: artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
    - [x] Regression test plan [testrail-report-956.pdf](https://github.com/user-attachments/files/16948189/testrail-report-956.pdf) 
    - [x] [Test plan](https://dsvavsp.testrail.io/index.php?/cases/view/92233&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=22018)
    - [x] [Coverage for References](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90554)
    - [x] [Summary (Defects) reports](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90554)
    - [x] [E2E tests](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90553#issuecomment-2286970328)
    - [x] [Code coverage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90553#issuecomment-2286970328)
    - [x] [Endpoint monitoring](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/playbooks/decision-reviews/hlr_get-contestable-issues_error-rate.md)

#### Not required, but nice to have artifacts
  - [ ] **Content source of truth**: (See Figma)
  - [ ] **Information Architecture spec**: link to CAIA IA feedback, such as an IA spec.

[CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/82516)

##### Platform actions
- [ ] Slack thread with VFS team: https://dsva.slack.com/archives/C5AGLBNRK/p1728500338400409
- [ ] Meeting date/time: Oct 17, 2024 at 3.30 PM ET

- [ ] Update this ticket with the Zoom recording
  - [Recording link ](https://oddball-io.zoom.us/rec/share/Gd3IWCCOO7XtP-QPH3Wo3MS4Ly_kL_lv_4sM-zM2d9ejPq7_y_CQkBFjP0Wu7qYZ.5ml_RUqJ1xI3awYc)
  - Password: Wu%?f50W
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>

### Privacy, Security, Infrastructure Readiness Review
<details>
  <summary>Toggle Privacy, Security, Infrastructure Readiness Review</summary>
  
#### VFS actions
- [ ] Complete the [Privacy, security, infrastructure readiness review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)
- [ ] Link to the Readiness Review ticket below

#### Platform actions
- [ ] Privacy, security, infrastructure readiness review is complete

</details>

**Comment by eileen-coforma** [comment]
We already have a CAIA request in progress: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82516

**Comment by comaurice** [comment]
Staging review scheduled for Thursday 10/17 @ 3:30pm. ![Image](https://github.com/user-attachments/assets/10aee3c9-a9ec-45f5-852d-9a7a42e8e83a)
@eileen-coforma FYI

**Comment by kayline** [comment]
Opened 2 tickets that are launch-blocking, @Mottie is assigned

**Comment by eileen-coforma** [comment]
Submitted ticket for [Contact Center Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95514)

**Comment by kayline** [comment]
Contact Center came back, product guide is OK. Ready to launch HLRs.
@comaurice will follow up.

**Comment by dfong-adh** [comment]
Maurice will have an update on this today.
