### ISSUE TITLE
Mental Health Phone Numbers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9019]
## What happened?
Mental health phone numbers are incorrect (reported in Prod)
According to Lighthouse team, API provides correct info
```
$ curl -sHapikey:$API_KEY https://api.va.gov/services/va_facilities/v0/facilities/vha_688QA | jq .data.attributes.phone.mental_health_clinic
"202-745-3012"
$ curl -sHapikey:$API_KEY https://api.va.gov/services/va_facilities/v0/facilities/vha_688GF | jq .data.attributes.phone.mental_health_clinic
"301-591-5858"
$ curl -sHapikey:$API_KEY https://api.va.gov/services/va_facilities/v0/facilities/vha_688GG | jq .data.attributes.phone.mental_health_clinic
"240-237-1625"
```

We are in the process of moving over to Lighthouse but currently, production still uses the old API. The switch to Lighthouse should resolve this issue. 

## Tasks
- This issue is for the non-ideal work around option

## Desired behavior
Correct information is displayed for mental health phone numbers

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Should be resolved by the v1 migration
