### ISSUE TITLE
Design | Contact Info Refresh | Reword the military base outside US checkbox

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#90194]
## Background 
users are misreading the checkbox and selecting this when they're actually on a military base in the US. This ticket is to change the verbiage so it's clear the checkbox is only to be used when on a military base **outside** of the US. 

![image](https://github.com/user-attachments/assets/c34440ed-df08-4992-8dc3-4b72e6279c04)

```[tasklist]
### Tasks
- [x] [Locate and link to Figma file or files that contain this feature](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=600-3166&t=TlPxp36vy4FvhcfD-0)
- [x] Locate and link to any research and findings previously held
- [x] Locate and include any stakeholder requests and/or requirements and/or context
- [x] [get confirmation from caia on our verbiage choices](https://dsva.slack.com/archives/C0NGDDXME/p1723755910044539) < the linked item is design channel not so much caia but caia folks did opine and said in the slack thread that the checkbox copy was an editable string
```

## Acceptance Criteria 
- [x] update the FE ticket w/ a link to the confirmed design copy in our figma file (see fe ticket here https://github.com/department-of-veterans-affairs/va.gov-team/issues/89514)

### Output 
- [contact info desktop](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=600-3166&t=pYrfpe3QlpJUXScN-0)
- [contact info mobile](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=666-7606&t=D1PQFrXKiBrCRGwW-0)

**Comment by mtcA6** [comment]
@twoangstroms could you fill out this ticket as we discussed on refinement? would be great if oyu could also point this

**Comment by mtcA6** [comment]
@twoangstroms bumping this, can you add in the context for this ticket before planning later today?

**Comment by twoangstroms** [comment]
@mtcA6 Wasn't this Medium priority yesterday?

**Comment by mtcA6** [comment]
@twoangstroms i don't see that I added a priority to this yet at least no tin the history. It would show if i added that

**Comment by mtcA6** [comment]
huh i guess it doesn't show in the history but I thought it did. I changed it ahead of sprint planning based on what I've got in mind for sprint goals and based on how this is a blocker for the FE to take the next step.

**Comment by twoangstroms** [comment]
Got confirmation in Slack that we can use "U.S." in place of "United States" (so that cleans up and shortens text a bit)

**Comment by twoangstroms** [comment]
@mtcA6 Documenting that conversation with Laura Willwerth reminded us both that the text for this checkbox is built into the [VADS "Mailing address" pattern](https://staging.va.gov/mock-form-patterns/mailing-address)

**Comment by twoangstroms** [comment]
Received support for proposed new text in Slack, proceeding with [requesting an update to Design System](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update), as other teams have seen problems with the existing text.

**Comment by mtcA6** [comment]
before we request an update of the design system can we hold off? there are other changes we're making in this epic that we should send all of those together

**Comment by mtcA6** [comment]
can you as part of this ticket firm up the copy for the checkbox and we can take care of going to teh design system as part of a separate ticket?

**Comment by twoangstroms** [comment]
Can do. Do you think those other changes would move that out of the "small update" category? 

The copy I shared for review with VFF and CAIA people in Slack seemed to get a positive response, right?

**Comment by mtcA6** [comment]
Is there an updated figma file?

**Comment by mtcA6** [comment]
Realizing now maybe the AC is a touch unclear. For the FE engineer we generally have tried to ensure there's an updated design in hand so the developer can work from the designs. 

is it ok if i change the AC to specifically call out the need for a figma file here?  
- [ ] update the FE ticket w/ a link to a revised figma file with the confirmed design copy https://github.com/department-of-veterans-affairs/va.gov-team/issues/89514

**Comment by twoangstroms** [comment]
[Updated Figma link](I live outside of the United States on a U.S. military base) using an override for the new text

**Comment by mtcA6** [comment]
Are we using the same verbiage for home and mailing? 
Can you make the change on a non-production file?

**Comment by twoangstroms** [comment]
Ah, my bad. I didn't zoom out. Updated on all the other frames/screens where the text appears on that page.

As for non-production files, do you mean the frames/screens in 'Address - Military base update'?

**Comment by mtcA6** [comment]
alex, travis, dan caught up and discussed [adding the designs here](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=600-3166&t=y59xDNBVBjmKPuCP-0)

comments made in line on that page for the missing items.

**Comment by twoangstroms** [comment]
@mtcA6 Please check out the "mailing" frames for [mobile](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=666-7606&t=G5G0fj7Y6oMsAlym-0) and [desktop](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=600-3166&t=G5G0fj7Y6oMsAlym-0)

**Comment by mtcA6** [comment]
@twoangstroms responded w comments, let me know if you wanna hop on a call this afternoon to review.

**Comment by twoangstroms** [comment]
@mtcA6 Commented back in the Figma comments. Seems that the Figma files aren't up to sync with what's released out into the world (or at least the Staging server), but that component (related to the APO etc. options) isn't relevant to the verbiage that's this ticket?

**Comment by mtcA6** [comment]
no not related to this ticket, but may be related to the broader contact information page updates we're making

**Comment by twoangstroms** [comment]
My recommendation (open to push back): use the "Contact info changes - Desktop" and "Contact info changes - Mobile" for the FE ticket and make updating other pages in the Figma files other tickets for later, so FE isn't blocked.

**Comment by twoangstroms** [comment]
Agreed. Sounds like a good idea.

Let's also think about how to organize that in the AE... space? folder?... in Figma, and also include some visual or worded indicator of the state of the numbered file (In Progress, In Production, etc.?). We don't want to have a) work done in the numbered file not make it to prod b) someone later get confused as to whether this or an unnumbered file is the source of truth to build upon.

**Comment by twoangstroms** [comment]
Created the Figma file ["#90194 - AE Profile - Reword the military base outside US checkbox"](https://www.figma.com/design/9XT1LkxHFs4EPTkWMrp9l0/%2390194---AE-Profile-Reword-the-military-base-outside-US-checkbox?node-id=0-1&t=B1IId3FBuh2l4fcf-0). 

I think that's an okay pattern for naming files: [Ticket number] - [Team] - [last section of ticket name]? Thoughts?

@mtcA6 @mattmarino-adhoc

**Comment by twoangstroms** [comment]
Though on a single page, for disambiguating, had to prepend each frame with "Mobile - " or "Desktop - ", which doesn't seem optimal?

**Comment by twoangstroms** [comment]
@mtcA6 Updated [Github ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89514)

**Comment by mtcA6** [comment]
@twoangstroms i think we just need another design ticket? for updating the prod designs to the correct formatting? 

![image](https://github.com/user-attachments/assets/eb0ed901-18e4-467f-a690-26647dc8a66c)
