### ISSUE TITLE
Use a cta-widget or similar embedded component for links to eBenefits

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#9020]
## User Story or Problem Statement
How might we take best advantage of SSOe capability when linking users to complete actions on eBenefits?

Today various health tool pages that link to MHV use the cta-widget, which can be embedded in a static page and provide some smart capabilities - making sure the user is logged in, identity proofed, and has appropriate access for the specific MHV feature they are being linked to.

For the most part, links to eBenefits don't do this. They look kind of similar to the CTA widget, but they are just static alerts, such as the one here: https://staging.va.gov/va-payment-history/
 This has been fine because there was no way to link a user over to eBenefits in a logged in state, and eBenefits only accepted DSLogon credentials.

But, VA.gov is near to launching outbound SSOe integration, and eBenefits is near to accepting SSOe sessions for all three credential types that VA.gov uses. This means we can soon link a user to a specific feature on eBenefits and have them be logged in when they get there.

Given that, it seems worthwhile to consider using the CTA widget or a variant thereof for links to eBenefits:
- Would encourage the user to use VA.gov's sign-in experience instead of eBenefits/AccessVA
- Could do prerequisite checks like making sure the user has identity proofed.
- Can also, if necessary, conditionalize the links to eBenefits based on whether SSOe is in use or not (though probably this ticket won't get done until we are 100% on SSOe). 

## Goal
Users are prompted to sign in and identity proof on VA.gov (if not already done so), before being linked directly to eBenefits via an SSOe session and arriving in  a logged-in state.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] Probably, split up the current cta-widget into a health-cta-widget and a benefits-cta-widget, because it is getting real messy to support both.
- [ ] Update the supporting text to remove mentions about needing DSLogon only, and having to sign in again.
- [ ] Enable the new benefits-cta-widget in CMS.
- [ ] Update existing static alert links to eBenefits  to use the new widget.
- [ ] Consider the various inline links to eBenefits (such as the "Q&A" links on the "download-letters" page) and whether there are enough of them to justify an even "slimmer" embedded link helper that can be environment-aware enough to generate the right link URL. Not sure if this is feasible in the CMS's current block-oriented system. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by patrickvinograd** [comment]
I tagged this issue as such because the current static links to eBenefits are owned by `vsa-public-websites` but presumably moving them in to dynamic components might be the purview of the `vsa-authenticated-experience` team.

**Comment by brianalloyd** [comment]
Reviewed this ticket in team grooming and don't see it as relevant however if you review and determine it has some merit we can reopen if needed. Please advise.
