### ISSUE TITLE
[Design, FE] 10-10EZ Improvement: Update Need Help section with new Accredited Representative content

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#90206]
## Background
A request came to the team from the Accredited Representative Management team (ARM) to replace the VSO contact guidance with Accredited Representative contact guidance.
This is part of an ongoing effort for the ARM team to streamline the information for Veterans around this subject.  

### References

<details>
<Summary>Slack Message details</Summary>

**Lindsay Li-Smith**
- Hi 1010 team!  Popping in from the Accredited Representation Management (ARM) team with a content request update.
- We have been partnering with CAIA to create content pages around accredited representation, and have an ongoing project to streamline the information for Veterans around this subject.  Would your team be open / have bandwidth to update the footer of the 10-10EZ intro page, so it references our landing page instead of the older https://www.va.gov/vso/ page?
- I have specific content recommendations from our CAIA partner, which I'll elaborate on in the thread :thread:

- Here's the content from our CAIA partner for all three pages, which fits the updated content standard of having the link on a separate line:

> If you need help gathering your information or filling out your application, you can appoint a VA accredited representative.
> [Get help filling out an application](https://www.va.gov/get-help-from-accredited-representative/)

- That content ^ is intended to replace the content and link target currently on the page.
![image](https://github.com/user-attachments/assets/9bdd2003-9e9e-4ee3-befe-7d8029453dcf)

- We took a backwards approach to discover this page -- we first found the legacy https://va.gov/vso/ link, then looked at Google Analytics to try and figure out what pages were pointing to that link.
- If there are other products/pages of yours that also reference this legacy https://www.va.gov/vso/ link, please let me know!
- And if there's a more formal process to request updates from the VA Forms team, feel free to point me in that direction
va.gov

**Heather Justice**
- Thanks Lindsay!  The only thing that might be a little wonky is that the paper form references VSO, so we will need to share the intent with the stakeholders.  Can you give us any background on how VSO changed to AR? (edited) 

**Lindsay Li-Smith**
- Sure!  The term "Accredited Representative" encompasses a few types of representatives that can assist Veterans:
     - Accredited VSOs (Veteran Service Organizations) -- this is by far the most common and they are free of charge
     - Accredited attorneys
     - Accredited claims agents
- We understand that Veterans resonate much more with the term "VSO" than the term "accredited representative" which is why our [landing page](https://www.va.gov/get-help-from-accredited-representative/) Get help from a VA accredited representative or VSO includes the term VSO in it's title.
- At the start of the landing page, we briefly mention these types and link out to an FAQ page that goes into more detail about these different representative types.  That FAQ page VA accredited representative FAQs is another page we've partnered with CAIA (and stakeholders) to publish.

- All that said, for the content update we're requesting, we're focused more on the value to Veterans.  If you're concerned about "VSO" term going away, I can circle back with our CAIA partner to discuss :slightly_smiling_face: (edited) 

**Heather Justice**
- We do also own the 10-10EZR that includes the same reference in the footer

**Lindsay Li-Smith**
- Awesome, would be great to get both updated to align Veterans to the most up-to-date guidance! :pray:

- Really appreciate that!  We're tracking traffic to our content pages, so would love to know when the changes on your products take effect so we can map that back to any traffic increases.  You can confirm with me in this thread, or you can alert us through the actual ticket if you use Github -- our team label is `accredited-representation-management-team` (dark green color). 

**Heather Justice**
- awesome, we'll add yall to the ticket and tag you when done

</details>

The current content is:
>If you need help to gather your information or fill out your application, [contact a local Veterans Service Organization (VSO)](https://staging.va.gov/vso/).
<img width="589" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGc5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba2066622f2529dd1c764962e4a1765cb00610e9/image.png" alt="image.png" />

The CAIA-approved content is:
>If you need help gathering your information or filling out your form, you can appoint a VA accredited representative.
[Get help filling out a form](https://www.va.gov/get-help-from-accredited-representative/)

## Tasks
- [x] [Design] Update designs to replace the VSO content with Accredited Representative content
- [x] Review with team/Engineers
- [x] [FE] Update Need Help section to reflect the new content change
- [x] Validate with team/PM
     - Signoff required to be documented in the comments
- [ ] Launch to Prod after signoff
- [ ] Tag `accredited-representation-management-team` when this ticket is closed

## Acceptance Criteria
- The Need Help section of the 10-10ez is updated to reflect the new Accredited Representative content.

**Comment by hdjustice** [comment]
Matt confirmed this is the only place the VSO reference is on the 10-10EZ

**Comment by IMHieuVo** [comment]
Products that use the legacy VSO link:

- Education Benefits & Applications (#benefits-education)
- Benefits Disability Experience Team 1 & 2 (#benefits-disability)
- Contention Classification Team (#benefits-contention-classification)
- Pension Benefits (#benefits-pension)
- Integrated Veteran Care Forms (#ivc-forms)

**Comment by jessicastump** [comment]
- [Figma link to EZ footer designs](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5722-10522&t=Mh52HgtAnHxP0Syg-0)
- @longmd or @hdjustice - let me know if we need to review at all or good to check that task off the list :)

**Comment by hdjustice** [comment]
I think it looks good to go, thank you @jessicastump

**Comment by longmd** [comment]
Yup... alll good from me, too!!

**Comment by jessicastump** [comment]
A little note on the design source of truth clean up once this is live -- we can adjust/override the "Need Help?" component in Figma for now - manually by each individual page, but there is a ticket opened to have this content variation available in the Figma design system component library - [#3203](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3203)

**Comment by longmd** [comment]
@jessicastump / @hdjustice , this has been updated, approved and is ready for sign-off to merge. Here is the updated content: 

![Screenshot 2024-08-28 at 10 02 22](https://github.com/user-attachments/assets/bd3c9460-f6eb-4d54-9af6-85d1180f520e)

**Comment by jessicastump** [comment]
Matches the designs! :) Confirming the link destination in the screen captures for "Get help filling out a form" is https://www.va.gov/get-help-from-accredited-representative/

**Comment by hdjustice** [comment]
Looks good!  The updates match the guidance provided by CAIA and the ARM team

**Comment by longmd** [comment]
@jessicastump / @hdjustice , you're welcome to [confirm the link via this RI](http://91379a2cdd502f732d02a9065af02d4d.review.vetsgov-internal/health-care/apply-for-health-care-form-10-10ez/). When you're good, just let me know and we can ship it.

**Comment by hdjustice** [comment]
Thanks @longmd!! - Confirmed via RI, the Need Help section has been updated as expected, as well as the updated link directs the user to the appropriate page.

**Comment by hdjustice** [comment]
All good to go for release into Production!

**Comment by longmd** [comment]
This has been released and is available in prod.

**Comment by hdjustice** [comment]
Validated in production, looks great!  Thanks @longmd ‼️
