### ISSUE TITLE
Qa Standards Dashboard Data: workflows.yml javascript heap out of memory

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90214]
## Issue Description
The [workflows file](https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/actions/runs/10279709841/job/28445579271) is having its javascript heap run out of memory when it runs. The runner size likely needs to be bumped up, or the js heap maximum size needs to be adjusted in the node command.

---
## Tasks
- [ ] Correct the JS heap out of memory error in the workflows file in the qa-standards-dashboard-data repository
- [ ] Run the workflow to ensure all missing updates are backfilled.

## Acceptance Criteria
- [x] The workflows file can now run without errors on its schedule.

**Comment by CBonade** [comment]
We decided instead of investing the time to fix this, while we reevaluate the necessity and format of the data as part of our upcoming QA dashboard initiative, we will disable the workflow to stop the error.
