### ISSUE TITLE
PBP | Track evidence upload submission volume and errors

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#90213]
## Issue Description
_OCTO has compiled a list of [must-have metrics](https://dsva.slack.com/archives/C055573C508/p1721768647619279) for all VA.gov forms, which now includes:_

- Evidence overall submission volume - Count of unique pieces of evidence submitted with forms, total and per form
- Evidence submission error %: Number and % of submissions that are submitted on Va.gov (user receives a successful confirmation message) but never reach the next system

---
## Tasks
- [ ] Add evidence overall submission volume to existing Datadog dashboard for Pension and Burial
- [ ] Add evidence submission error % to existing Datadog dashboard for Pension and Burial

## Acceptance Criteria
- [ ] evidence overall submission volume dashboard for burial form for Pension and Burial
- [ ] evidence submission error % dashboard for burial form for Pension and Burial
---

**Comment by steele-lm** [comment]
@mjknight50 The request it to create a dashboard with these (ongoing) metrics or add them to an existing one.

**Comment by mjknight50** [comment]
The widget that we use to address this ticket should be applied to both pension and burial.

**Comment by sanjabaj2** [comment]
Did you try to edit in 'coding' mode? Clicking this icon will enable you to type anything you want. 
![Image](https://github.com/user-attachments/assets/481598b9-c2b2-4c25-bd53-25aafba366b1)

**Comment by balexandr** [comment]
Dev Note:
`StatsD.increment('api.document_upload.attempt', tags: {form_id: 21P-527EZ})`
Need Failure
Need Success
CC: @danlim715

**Comment by danlim715** [comment]
> Dev Note: `StatsD.increment('api.document_upload.attempt', tags: {form_id: 21P-527EZ})` Need Failure Need Success CC: [@danlim715](https://github.com/danlim715)

`StatsD.increment("api.document_upload.success", tags: ["form_id: 21P-527EZ"])`
`StatsD.increment("api.document_upload.failure", tags: ["form_id: 21P-527EZ"])`

**Comment by balexandr** [comment]
Updated Burial and Pension widgets (3 each) to use newer stated keys:

- api.claim_documents.attempt
- api.claim_documents.success
- api.claim_documents.failure

**Comment by balexandr** [comment]
@aplatt-coforma 
Daniel Lim 4:21 PM
oh FYI, even after this doc uploads backend change is merged, u still won't see data funneling into the widgets cuz we need to keep the flipper turned off until we get CAIA approval on all the new frontend validation messages we need to add.

**Comment by aplatt-coforma** [comment]
Thanks for the note @balexandr @danlim715. CAIA approved frontend changes are in the ENG queue now. Tracked with #99351 and #99509. @ToddWebDev will be working on these two tickets in sprint 9 & 10.

**Comment by wayne-weibel** [comment]
https://vagov.ddog-gov.com/dashboard/vk2-6zi-zzu/benefits---form-527-pension-benefits?fromUser=true&refresh_mode=paused&view=spans&from_ts=1738183869420&to_ts=1738270269420&live=false&tile_focus=5085745061842496
https://vagov.ddog-gov.com/dashboard/q5u-4h7-bfh/benefits-form-530-burial-claims?fromUser=false&refresh_mode=paused&from_ts=1737665354322&to_ts=1738270154322&live=false&tile_focus=5494054599692566

**Comment by wayne-weibel** [comment]
https://vagov.ddog-gov.com/monitors/316888
https://vagov.ddog-gov.com/monitors/316892
