### ISSUE TITLE
Burial | Clarify submission logging and monitors

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#90226]
## Issue Description

clarify existing logs to specify info vs error, correct payload (claim_id, user_account_uuid, class name, etc), and update [Burials DataDog dashboard](https://vagov.ddog-gov.com/dashboard/q5u-4h7-bfh/benefits-form-530-burial-claims)

---
## Tasks
- [ ] use existing logging examples to clarify Burial submission logging

## Acceptance Criteria
- [ ] logs will indicate its type - info vs error
- [ ] logs will contain necessary payload for identifying and debugging a specific submission
- [ ] datadog monitors will be updated (or added) to monitor these logs
---

**Comment by mjknight50** [comment]
A good example of this is the inconsistency of how we log errors
e.g. 		Logging:
        * Burials —> raise Common::Exceptions::ValidationErrors, claim
        * Pension —> raise Common::Exceptions::ValidationErrors, claim.errors
        

Also, logging when jobs are started, attempted, and thrown.

**Comment by mjknight50** [comment]
Hold this one back until https://github.com/department-of-veterans-affairs/va.gov-team/issues/90177 is completed.

**Comment by matt4su** [comment]
Is this work covered by  ticket #91824?  Might be a dupe?

**Comment by balexandr** [comment]
@matt4su I think its worth going through to compare between pensions and burials per Wayne's inconsistency above

**Comment by wayne-weibel** [comment]
@balexandr does the work be done here make #90212 a duplicate?

**Comment by balexandr** [comment]
@wayne-weibel The work done under this ticket has been strictly in DD. No code changes.

![Image](https://github.com/user-attachments/assets/a765b030-0d63-47de-9d1b-bd37256570c9)

**Comment by wayne-weibel** [comment]
This is looking good. A couple more widgets to add though (can crib from pension)

The important one is:
![Image](https://github.com/user-attachments/assets/1d3c49b4-9aff-495e-a147-fdc1706bfff7)

This are helpful for reporting
![Image](https://github.com/user-attachments/assets/66aca6a7-e3bb-45e8-a698-63b1fd700540)

**Comment by balexandr** [comment]
@wayne-weibel They've all been added and updated for Burial
