### ISSUE TITLE
[DevOps] Determine if there are monitors we should configure for VeTEXT.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90222]
## Description
In the discussion about #90221, it was suggested that we would need to know of failures to VeTEXT ASAP so we can hit the killswitch and limit frustration with our service.

## Tasks
- [ ] [DevOps] Determine if there are monitors we should configure for VeTEXT.
- [ ] [DevOps] If so, document them in this thread.
- [ ] [DevOps] Open followup ticket(s) to address individually.

## Acceptance Criteria
- [ ] Useful VeTEXT monitors have been identified and documented in this thread.
- [ ] Followup ticket(s) opened to address implementation of each.
