### ISSUE TITLE
Burial | Refactor away from CentralMail

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#90229]
## Issue Description

Any use of CentralMail namespaces within the Burials submission workflow needs to be refactored, ie. `CentralMailSubmissionSerializer` and `CentralMail::DatestampPdf`, etc

https://github.com/department-of-veterans-affairs/vets-website/pull/30141/files

https://github.com/department-of-veterans-affairs/va.gov-team/issues/90237

---
## Tasks
- [ ] refactor Burial submission code to remove "CentralMail" references, reuse other existing class if possible

## Acceptance Criteria
- [ ] no use of CentralMail classes within the Burial submission workflow
- [ ] new code is 100% covered by unit tests
- [ ] new code is 100% documented - yardoc syntax
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mjknight50** [comment]
Wayne has partly addressed this already.
Reminder to update monitors if not already done.
