### ISSUE TITLE
Improve a11y usability testing experience for designers and participants

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#90224]
## OCTO OKR
1.1: Improve satisfaction with our web and mobile products by 5 points.

This maps to 1.1 as we believe that by improving our ability to perform a11y usability testing across the platform we will be able to improve the overall UX for users of assistive tech on VA.gov and the Health & Benefits mobile app.

Key result: Pilot 1 VFS team using Codespaces to work around authentication 

## Description
(This is borrowed from the work of the Forms team, specifically @jeana-adhoc and @rachelshearerux, on 2 recent studies)

The Veteran Facing Forms team participated in two separate studies in June and July 2024. The form status and form upload usability studies included users of assistive technology.

Only 2 participants out of 6 were able to start the study on their device.

Testing with users of assistive technology has been a north star of the research practice on VA.gov. When those users can't access the study from their device, it frustrates researchers and participants.

A retro was held with the designer-researchers and product manager on the Veteran Forms Team, a designer-researcher from My VA, and 3 CAIA accessibility support staff who supported these research sessions.

In total, CAIA attended 13 of the scheduled 17 assistive tech studies. Over half of those studies (7) were either no shows (3) or the participant did not use the technology they identified on the screener (4).
In the remaining 6 studies CAIA worked patiently with the participants to try to enable screen sharing, and at times even coaching/training the participants in how to use their assistive tech. In the end, only 2 participants were able to start the study.

## Key findings
1. Many processes already exist that help with successful studies. Successful processes focus on simplicity. CAIAʼs support is immensely valuable and much appreciated.
2. Pivoting to a Q&A session yielded valuable information for the researchers. Even when participants could not start the study using their device, we still learned valuable information from Veterans.
3. Veterans want to be self-sufficient and independent in their interactions with VA, and participating in research sessions helps them do that.
4. Some participants joined the studies and did not need to use the assistive tech they listed in the recruitment surveys. Perigean struggled to find additional participants to fill these assistive tech slots.
5. Participants needed help switching apps, screen sharing, and loading URLs in browsers when using their assistive technology. Veterans who struggled with screen sharing or using their assistive tech for the study felt they had failed. They thought they were not helpful.
6. Some participants had not used VA.gov before to apply for benefits. They lacked the self-trust that they could successfully complete an application. Researchers assumed that participants had used VA.gov before.

## Recommendations
1. Consider the ʻmagic wandʼ ideas (see below)
2. Continue to work on ways to make accessible prototypes in staging, codepen, or another system.
3. Work with VA.govʼs Accessibility Lead, Martha Wilkes, to define what a completed assistive technology usability session looks like.
4. Work with full-time researchers to improve the process of conducting usability studies with assistive tech users.

#### Magic wand ideas
If you had a magic wand to create your ideal research session what would it look like?

1. Before the session begins, Perigean should ensure participants are ready to start the study on their device using the assistive technology that they identified in recruiting.
2. More studies would be in-person.
3. Logging in would never be required, even to test an authenticated experience.
4. There would be at least two “levels” of testing. Are we testing, does this thing technically & functionally work? Or are we testing what the user experience like?
5. Continue to use CAIA for support. Also, train embedded Accessibility specialists to provide the same support.
6. Coded prototypes are the norm. They're easy for engineers to build without duplicating effort.

## Tasks
* [ ] Have Jeana and Rachel present to Shane and Martha the findings from the Forms team so they can ask questions.
* [ ] Matt, Martha, and Shane to brainstorm additions to this initiative based on the findings and recommendations. Then refine this initiative (or create sub-initiatives)
* [ ] Talk to Perigean about how they can help us
* [ ] Determine who can help move us forward on using either Preview environments or Codespaces to setup better usability testing environments in staging
* [ ] Improve platform documentation as we go
* [ ] Incorporate findings from upcoming AT retros to inform any changes to the research processes

**Comment by humancompanion-usds** [comment]
Full PDF report from the Veteran-facing Forms team:
[Form status and Form Upload Assistive Tech Usability Study Retro.pdf](https://github.com/user-attachments/files/16534442/Form.status.and.Form.Upload.Assistive.Tech.Usability.Study.Retro.pdf)

**Comment by artsymartha68** [comment]
Four assistive tech retros are now complete, with one additional retro from a product team. Next step is to synthesize, waiting for Robyn Singleton who wants to be involved.

**Comment by humancompanion-usds** [comment]
* Could be picked up by new contract folks. Putting this into the new PWS.

**Comment by artsymartha68** [comment]
Looking to new Accessibility DE team to take these findings and decide how to improve the a11y research processes.

**Comment by artsymartha68** [comment]
Linking the tasks that @cindymerrill has underway.
#103744 
#104068 
#104131 
#104337

**Comment by cindymerrill** [comment]
Thank you for looping me in, @artsymartha68 ! This is helpful feedback from @jeana-adhoc and @rachelshearerux. I have a few responses:

1. To better support VFS researchers/designers, this week I submitted 3 tickets for updates to Platform research documentation (unknown when the documentation will be updated, FYI @naomimarcussen ): 

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104228
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104258
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104268

2. Re participants showing up for research participants and not needing to use the AT they specified in the screener, I included an updated screener question in #104228 that has been successful in my AT studies and that I strongly recommend that everyone uses to recruit AT users:

> Do you need a screen reader or screen magnifier EVERY TIME you use the Internet? We ask this question because we want to make sure that our website works for people who rely on these types of technologies. (Note that this question specifies "every time" and also doesn't list examples of AT that the potential participant could use to answer subsequent screening questions.)

3. Re the magic wand idea of "More studies would be in-person", I would hesitate doing that for AT users, who are most comfortable and skilled using their own AT in their own environment and without having to deal with the challenges of navigating to somewhere new.

My goal is to make the process of conducting accessibility research easier and more productive for VFS designers/researchers. I'm happy to work with @sstrassberg and others on this.

**Comment by cindymerrill** [comment]
@lakper This ticket doesn't show up in my sprint board. I just added the "ADE Research" label, but it might need something else, too?

**Comment by artsymartha68** [comment]
@cindymerrill I believe it may be in a separate repo? I sorry and I wish I understood GitHub better. But I think Matt has manually added tickets to his dashboard when needed, this may be in the same situation?

**Comment by cindymerrill** [comment]
Thanks @artsymartha68 !

@lakper could you please help me?

**Comment by artsymartha68** [comment]
I'm going to close this epic/initiative since @cindymerrill has closed all the sub-tickets. Of course, as she discovered more opportunities to improve documentation or processes, she will do so!
