### ISSUE TITLE
Refactor CentralMail::DatestampPdf to PDFUtilities::DatestampPdf

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#90237]
## Issue Description

Refactor class for clarity, encourage reuse.  Moving off of CentralMail, and in the case of DatestampPdf, CentralMail is misleading and a misnomer since it is not specific to CentralMail

---
## Tasks
- [x] move `lib/central_mail/datestamp_pdf.rb` to `lib/pdf_utilities` renaming the module namespace
- [x] replace each use of CentralMail::DatestampPdf with new PDFUtilities::DatestampPdf
- [ ] update all unit tests
- [x] delete `lib/central_mail/datestamp_pdf.rb`

## Acceptance Criteria
- [ ] all existing tests pass
- [ ] all forms perviously using CentralMail::DatestampPdf still successfully submit
- [ ] 100% unit test coverage for new PDFUtilities::DatestampPdf
- [ ] 100% documentation for new PDFUtilities::DatestampPdf - yardoc syntax 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
