### ISSUE TITLE
Determine process for Tier 3 Contact Center Issues

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9024]
## User Story or Problem Statement
How might we close Tier 3 contact center issues when no progress has been made for weeks?

## Goal
Tier 3 Contact Center issues have a closed feedback loop when no progress has been made.

---
## Tasks
- [ ] Determine how to close Tier 3 issues when there has been no update for a while
- [ ] Document the risks that may happen due to the solution and the pain points the solution solves
- [ ] Document how the feedback loop will be closed with veterans
- [ ] Document how the feedback loop will be closed with VFS teams

## Acceptance Criteria
- [ ] VSP Analytics & Insights and VFS teams understand when and why a Tier 3 issue will be closed
- [ ] Veterans have closure for their issues

**Comment by clantosswett** [comment]
We met to discuss the possible options for dealing with open/unresolved Tier 3 issues and decided to implement Closing and/or transferring a tier 3 issue after 30 days of being opened. See notes below for brainstorm of options. Identified next steps

- [ ] Outline process with details on timeline of notifications/milestones (Kimberley and Chante)

- [ ] Create notification templates to VFS team

- [ ] Update documentation and determine if this needs to be added to collab cycle and announce at ToT.


_1. Determine when an issue should be "closed" and who should "close" the issue. 
2. Should an issue  be closed if there hasn't been a resolution?

1. We don't close an issue unless it has been resolved or an external VFS team has to do something to fix the problem.

2. Transfer (unassign the contact center team) the issue once we notify the VFS team and they have made contact with the veteran. 

3. Close or transfer issue after 30 days of issue being opened. 

4. Mark the issue as blocked and move to icebox after 30 days of issue being opened._

**Comment by joanneesteban** [comment]
Has the Github documentation been updated with this?

One question is if step 4 is completed (contact center label is unassigned), do we need to close it on our end?

**Comment by Kimberley2019** [comment]
@joanneesteban Number 4 was an option, not a step in an option if that makes sense.

Please see updated documentation below.
@clantosswett can you please review the updated documentation?

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/tier-3-process-updated.md

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/milestone-templates.md

**Comment by clantosswett** [comment]
I reviewed and this all looks good and makes sense. Starting now, we will follow this process for all Tier 3 issues.

**Comment by joanneesteban** [comment]
Looks good! A couple of (nitpicky) items for the Tier 3 Process doc. @Kimberley2019 , can you please,
- [ ] update the doc name to be "tier-3-process"
- [ ] add a title to the document

**Comment by joanneesteban** [comment]
Also, I think the Tier 3 process and the Contact Center review process docs should be added to the #vsp-contact-center-support channel. Either in the topic or pinned.

**Comment by Kimberley2019** [comment]
The document name has been updated and added to the platform repo as well as the internal repo.
I have also pinned the two suggested documents to the contact center channel.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/tier-3-process.md

Closing this issue.
