### ISSUE TITLE
[DevOps] Configure VeTEXT Datadog to assume IAM role.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90250]
## Description
Followup to #89870.

This covers the actual transition to the new IAM role.

## Tasks
- [ ] [DevOps] Have access key ID and secret access key handy in case we need to revert.
- [ ] [DevOps] Screenshot each tab of existing integration.
- [ ] [DevOps] Create duplicate Datadog configuration for `vaec-cms` AWS account _but do not submit it_.
- [ ] [DevOps] Copy generated secret into Secrets Manager secret.
- [ ] [DevOps] Re-run deploy to update policy with new Secrets Manager secret value.
- [ ] [DevOps] Wait a few minutes for the IAM policy to "settle", then delete the existing integration configuration and submit the new integration configuration.
- [ ] [DevOps] Replace integration configuration, using screenshots as references.
- [ ] [DevOps] Wait 15-20 minutes (integration latency).
- [ ] [DevOps] Verify that metrics are being delivered appropriately.

## Acceptance Criteria
- [ ] VeTEXT Datadog uses IAM role instead of access keys.
