### ISSUE TITLE
Begin discovery on new Contact Center reporting

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9025]
## User Story or Problem Statement
There are currently some contact centers who are providing no reporting data. How might we communicate with these contact centers to provide reporting that helps VFS teams build better services on VA.gov for veterans?

## Goal
Determine the process and feedback loop for communicating with contact centers on retrieving reporting data.

---
## Tasks
- [x] Create a folder in Github to store meetings minutes
- [x] Research what has worked in the past
- [x] Draft process for communicating with contact centers that
   - [ ] Gives us a clear feedback loop 
   - [ ] Allows us to retrieve reports in either CSVs, Excel, or through an API

## Acceptance Criteria
- [ ] VSP Analytics & Insights understands how to communicate with contact centers to retrieve data that has not previously been provided by that contact center before

**Comment by Kimberley2019** [comment]
Below is the link for the meeting notes repo.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/meeting-notes.md

**Comment by Kimberley2019** [comment]
There have been attempts in the past to obtain data from contact centers and many have been slow to provide information or have provided no information at all.
Due to this, a process cannot be established until each contact center has replied back.  Currently, the process is to simply reach out to the contact center leadership in an attempt to obtain data.

Data will be requested from the following contact centers:

- NCC: National Call Center

- Education

- NCA: National Cemetery Administration

- HEC: Health Eligibility Center

- HRC: Health Resource Center

**Comment by joanneesteban** [comment]
@Kimberley2019 Can you please add a title, audience, and overview for the document above?

example:

# This is a Title

**Audience**: Who should read this document

**Overview**: What this document is

Reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/insights-team-gh-structure.md

**Comment by Kimberley2019** [comment]
@clantosswett  or @joanneesteban can you please Q/A the updated document?

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/data-request-monthly-reporting-process.md

**Comment by Kimberley2019** [comment]
Please see updates below:

- NCC: National Call Center
    - Receive call information currently after reaching out monthly to obtain.
- Education
    - 
- NCA: National Cemetery Administration
    - Waiting on response 
- HEC: Health Eligibility Center
    - POC (Amanda) Has stated that they do NOT receive any calls related to VA.gov technical issues. 
- HRC: Health Resource Center
    - POC (Sylvia) has provided the information below.  Since this is such a manual process (and due to the history), I am unsure if I will be able to continue to retrieve this information on a continuous basis.
      - For this calendar year we have taken 2054 VA.gov calls mostly related to claims. Last month 379 calls from VA.gov and 126 of those were transferred to Veterans Benefits administration. It is hard to capture calls as they may be documented under a different entry point like My HealtheVet or eBenefits since features are still redirected for some use cases. I would say the actual number is between 500-700 calls we received last month for VA.gov for the following topics:

Claims
Direct Deposit
VA Letters
Education Benefits

**Comment by Kimberley2019** [comment]
Update from Jay at NCA: National Cemetery Administration:

** The spreadsheet that was provided did not offer any information for VA.gov calls.

Kimberley,

Our operation is a little unique when compared to the others. At the National Cemetery Scheduling Office (NCSO), we have 3 primary services being provided:

1)	Scheduling – for scheduling of burials at a National Cemetery
2)	Time of Need – for verification of eligibility of Veterans for burials
3)	Pre-Need – For verification of eligibility of Veterans who are living and may be planning their burial arrangements

It would be very rare for our center to have cross-over requests for other VA contact centers.

Within NCA, we also have a small center in Washington DC called the Application Assistance Unit (AAU).  They are more singularly focused with their services as well.  I have included their volumes in the attachment also.

Please let me know if there is any additional information needed.
Thank you,

**Comment by joanneesteban** [comment]
@Kimberley2019 to follow up on Slack with @joanneesteban & @clantosswett for closing this ticket.

Thoughts: we can probably pause on this issue until we receive more case studies on actual contact center data usage to improve services and contact center issues to go with our asks.

**Comment by joanneesteban** [comment]
@Kimberley2019 @clantosswett Backlogging this issue until we get more case studies throughout Q3 2020.

**Comment by Kimberley2019** [comment]
This ticket should stay backlogged or iceboxed until we can meet with the appropriate teams, develop a streamlined process for current data gathering and team data needs.
