### ISSUE TITLE
DR | Move remaining Sentry logging to DataDog

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#90265]
## Value Statement

**_As a_** developer

**_I want to_** be able to find helpful logging in DataDog

**_So that_** we can fully deprecate our usage of Sentry

---

## Background Context

Some errors get additional context logged to Sentry, such as 422s ([example here](http://sentry.vfs.va.gov/organizations/vsp/issues/277562/?project=3&query=user.id%3Af314d4cfb3ed4005bf1e287e2b89871b&statsPeriod=14d)) and this additional context can help us diagnose what validation issue the user may have encountered. Since we're moving away from using Sentry, we'll want this additional context to get logged to DataDog.

## Acceptance Criteria

- [ ] 422s logged to DataDog have additional logging to give us context for the validation error that occurred
- [ ] Other types of errors are sufficiently covered by logging in DataDog

## Open questions

- What other types of errors might need extra data logged to DataDog that would be helpful in triaging errors?

## Tasks

- [ ] Investigate how the additional data for 422s is getting logged to Sentry
- [ ] Add equivalent DataDog logging for 422s
- [ ] Investigate and add additional logging for other error types that might be helpful for us when triaging errors

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by anniebtran** [comment]
Started adding a check for 422s [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/service.rb#L430-L439) on a local branch, still need to add tests
