### ISSUE TITLE
Automate the Contact Center report on Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9026]
## User Story or Problem Statement
How might we automate the contact center report so that it's easier to pull every month and we can focus on more strategic work, such as analysis of the reports for VFS teams and obtaining more data?

## Goal
Automate the monthly contact center report in Domo.

## Objectives or Key Results this is meant to further
Customers use qualitative and quantitative user data to build and iterate on VFSs.

---
## Tasks
- [ ] Transfer the contact center report to Domo
- [ ] Automate the tasks as referred to in [8552](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8552)

## Acceptance Criteria
- [ ] VSP Analytics & Insights can more easily create the monthly contact center report
---
## Links
- See [8552](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8552)

**Comment by joanneesteban** [comment]
Reference [8552](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8552)

**Comment by Kimberley2019** [comment]
When attempting to view the mock up reporting from ticket 8552 nothing populates.

I receive two different messages depending on which link I select:

- There was an error loading the dataset and return to the data center and try again later.  

- The card is no loner available.

I have notified @jonwehausen and will try again later today.

**Comment by Kimberley2019** [comment]
After meeting with @jonwehausen @bsmartin-ep and @clantosswett, the automation of the raw data appears to be operating correctly.

One last task for @jonwehausen is to attempt to automate the NCC reporting portion that is received, update will be provided.  

Reminder to always update the date range each month in order for the data to populate accurately.

**Comment by jonwehausen** [comment]
@Kimberley2019 @clantosswett @joanneesteban 

I believe this is in a good position for a trial run with April data. 

Here are the steps to get updated for April (and on a monthly basis): 
1) Go to the [**raw** contact center dataset](https://va-gov.domo.com/datasources/5f033e5c-f6d4-46e0-b684-b89f4cbc41b4/details/overview) (this should mirror your excel spreadsheet)
2) In the top right hand corner, click the wrench > Edit Webform
3) Paste in your new data for the month (or if needing to do a full CTRL+A+delete + CTRL+A+PASTE)
4) Click Save & Continue
5) Next go to [NCC raw dataset](https://va-gov.domo.com/datasources/bc5e0dc6-ebfd-4fb0-862f-9a73856377c3/details/overview)
6) In the top right hand corner, click the wrench > Edit Webform 
7) This is the tricky part -- Start typing in the next available row. In the `DATE_CREATED` column we need to add in a date indicating the new month. I would suggest we just set this as the first or last of the month for the report you're generating. 
8) For general inquiries and technical issues, we need to create as many rows as there are issues based on what was given by NCC -- Highlight the row you just created and drag the small square in the corner down the number of times for the number of issues. For example, if there are 30 general inquiries for ncc, create one row, and then drag it down 29 more times. Repeat 7+8 for technical issues. 
9) The automation should kick off once these updates are done. 
10) Navigate to the [dashboard](**url**)
11) Hover over each chart and click the wrench dropdown on the right hand side and click "Edit in Analyzer"
12) Within each chart, under "FILTERS" on the left hand side, push "DATE_CREATED" date range forward to reflect the new month you're trying to display. 

![image](https://user-images.githubusercontent.com/48527022/82952513-1924fb00-9f77-11ea-81f1-38e7ec6767d9.png)

13) Click Save and Close in the top right and do this for each chart. 
14) At this point, the dashboard should now be updated with only the relevant month's data

**Comment by Kimberley2019** [comment]
@jonwehausen thank you very much for working on this and the breakdown that you did above.  Hopefully tomorrow we can do a dry run to ensure that @clantosswett and I have the process together and all of the right access and permissions.  I have one question currently:  Will it be simple to add additional contact centers as we begin to receive information from them (like NCC) or will that have to be something that is managed by an admin?  Looking forward to connecting tomorrow.

**Comment by jonwehausen** [comment]
Hi @Kimberley2019 ,

Good question. The goal is to have you and Chante be able to add-in directly the raw data for IRIS, SF, WHH, NCC issues (mirroring the spreadsheet). 

For NCC, (a separate dataset than IRIS/SF/WHH) the dataset has been staged to fit when you guys receive the VA.gov general inquiries and technical issues. See steps in prior comment for updating. 

In terms of other contact center sources, we would need to look at the format / structure in which you've received data in the past from them. Potentially, we could re-purpose the NCC dataset for these other sources. Otherwise, we may need to setup an additional dataset when other contact center data is received to optimize for you both to add-in in the data directly. 

Can help explain in further detail today.

**Comment by Kimberley2019** [comment]
Thanks for that explanation J.  Looking forward to our call.

**Comment by Kimberley2019** [comment]
Below is the write up for how to upload data into DOMO.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/domo-upload.md

**Comment by Kimberley2019** [comment]
I am unable to upload raw data into webform for DOMO.
Receive error message stating:
There was an error loading this DataSet.  Please return to Data Center and try again later.
While I'm on the VA Network when this message populates.  I do NOT receive this message when I'm on this side.

**Comment by Kimberley2019** [comment]
The progress on this has been ongoing.  There are a few issues that are being addressed currently by Jon and Kim. 
Most May issues have been uploaded into DOMO.
The NCC report that is received needs to be incorporated into DOMO.  This is what we are currently trying to do in order to share out the April and May reports.
I asked if it was conducive to still send out the report without the NCC breakdown, Joanne would like to revisit that on 6/9/2020.

**Comment by jonwehausen** [comment]
### 6/9/2020 Update
cc: @Kimberley2019 @clantosswett @joanneesteban 

### Summary of updates
- We should be very close to a finished product, would like to request your assistance on final things to check
- [NCC dataset](https://va-gov.domo.com/redirect-to-datasource-details/782d5a54-3145-4111-b6d1-a06db66bf5e4) has been added and will serve as the location to upload monthly NCC data received in this format: 
![image](https://user-images.githubusercontent.com/48527022/84151577-9483b380-aa31-11ea-94c9-cd6a4efd5dc4.png)
- A new card has been created that inherently mirrors the NCC spreadsheet ([currently on bottom of dashboard](https://va-gov.domo.com/page/1744754544)) 
- The separate card of just va.gov issues has been maintained and is right above
--------------------
### Items to check / QA
- [ ] All of the filters for `DATE_CREATED` within each card are set to be between May 1 - May 30
![image](https://user-images.githubusercontent.com/48527022/84151959-0cea7480-aa32-11ea-9d02-16a1641fb718.png)

- [ ] The `SYSTEM` filter within each card is set to the relevant system necessary
![image](https://user-images.githubusercontent.com/48527022/84152022-2095db00-aa32-11ea-8259-98033827ff50.png)

- [ ] Headers of table columns accurately reflect necessary verbiage 
![image](https://user-images.githubusercontent.com/48527022/84152223-5b980e80-aa32-11ea-9547-3132d165af1e.png)

- [ ] Numbers in charts are accurate per datasets & raw data

**Comment by Kimberley2019** [comment]
Report has been reviewed and updated.  April and May reporting have been sent out.
