### ISSUE TITLE
[FSR] Bug - Console errors showing for button groups

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#90307]
## Description

Platform merged a change to update the props for our button groups, but missed a spot so we're seeing some console errors of a mismatched proptype. 

Platform PR: https://github.com/department-of-veterans-affairs/vets-website/pull/31161 

[Platform updated proptype](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/financial-status-report/components/shared/ButtonGroup.jsx#L29)

[Proptype that needs updating](-website/blob/main/src/applications/financial-status-report/components/shared/ButtonGroup.jsx#L55)

## Tasks
- [ ] Update Proptypes
- [ ] Confirm platform changes don't effect current form functionality 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [ ] Button groups working as intended
- [ ] No console warnings related to this issue

## Testing
- [ ] Confirm locations of button groups don't throw proptype errors

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
Looks like this was fixed in [a recent PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31426) (thanks Aaron!). Going to close out after I peek at another potential button issue I noticed while testing with `FormNavButtons`; I'll make an appropriate ticket if it warrants more digging

**Comment by Dr-Pongo** [comment]
Closing out since the issue has been addressed!
