### ISSUE TITLE
DORA Metrics Q2 2024 - Metric Calculation

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#90306]
## Description 
This ticket is intended to document the work of calculating the two metrics Platform Support is responsible for: Change Failure Rate and Time to Restore Service.

---

## Definition of Done
All tasks below are done

---

## Tasks 
_Steps to reach definition of done._ 
- [x] Change Failure Rate
- [x] Time to Restore Service
- [x] Present the findings both in [this document](xhttps://vfs.atlassian.net/wiki/spaces/PTST/pages/3351019528/Q2+DORA+Metrics+April+1+2024+-+June+30+2024) and in a spreadsheet format 
- [x] Add launched item to the [Launched Support Enhancements Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2632286220/Launched+Support+Enhancements+Documentation)
- [x] Alyssa to communicate to relevant channels (Alyssa will update which channels in the tasks after the ticket is assigned to her)
--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Work complete. Doc here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/3351019528/Q2+DORA+Metrics+April+1+2024+-+June+30+2024

Closing.
