### ISSUE TITLE
[DevOps] Create Node.js function to generate LoROTA data

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90308]
## Description
Use the LoROTA schemas and the CHIP schemas (see #90300).

This should be able to generate data at 1MB, 10MB, 100MB, 1GB, 10GB levels.

## Tasks
- [ ] [DevOps] Create the function.
- [ ] [DevOps] Document performance in this thread.

## Acceptance Criteria
- [ ] Function can create 1-10000 GB of fake data when invoked.
- [ ] Performance is documented in this thread.
