### ISSUE TITLE
[DevOps] Perform Discovery on Addressing Vulnerabilities in ECR `vagov/vista-api` Container Images

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#90319]
## Description
Elastic Container Repository (ECR) enhanced scanning has been enabled for the `vagov/vista-api` repository which has generated a list of Critical, High, Medium, and Low security findings for the container images in it the repo.

As a DevOps engineer I need to investigate how to address, at a minimum Critical and High security findings in the repository container images to improve the security posture of VistA-API.

Organizing this work is important as there are hundreds of findings. This could take the form of an epic to track individual security finding remediation. Chunking the work in this way makes it easier to visualize and completable within the confines of a sprint to prevent long-lived roll-over issues.

## Tasks
- [ ] Document vulnerabilities of images in this issue
- [ ] Develop a plan to address each Critical and High security finding. 

## Acceptance Criteria
- [ ] Discovery has been performed on how to best address security findings in VistA-API container images.
- [ ] Open follow-up ticket(s)/Epic(s) to address security findings

## References:

https://console.amazonaws-us-gov.com/inspector/v2/home?region=us-gov-west-1#/findings/repository/432896750513/vagov%2Fvista-api
