### ISSUE TITLE
[DevOps] Determine specifics of executing LoROTA data generation Lambda

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90311]
## Description
Followup to #87078 and #90308.

A few possibilities on this:
- Create an API Gateway (which will likely be helpful for other reasons)
- Invoke on deploy (if s3 object is missing; will add time to deploy for no great reason)
- Invoke manually with a custom event (don't like unless it's a GHA workflow or something)
- ???

## Tasks
- [ ] [DevOps] Determine one or more appropriate strategies for executing the LoROTA data generation Lambda.
- [ ] [DevOps] Document in this thread.
- [ ] [DevOps] Open followup ticket(s) to address.

## Acceptance Criteria
- [ ] Strategies documented in this thread.
- [ ] Followup ticket(s) opened to address.
