### ISSUE TITLE
Outline VA Notify approach

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#90325]
## Background
We are planning to use the VA Notify service for sending out a confirmation email to users after they complete the Appoint MVP process.  This email notification will confirm the completion and reiterate next steps.

Kick off with VA Notify is here, for context on the experience.

But we'll need to outline what specifically we need to do to engage VA Notify and get that confirmation email out.

## Tasks
- [ ] Review VA Notify Playbook
- [ ] Review VA Notify API Docs (must be in the VA network to see)
- [ ] Outline an approach to use VA Notify to send this confirmation email

## Acceptance Criteria
- [ ] We have an understanding of how to use VA Notify to send a confirmation email at the end of Appoint a Rep, which will guide the actual implementation tickets to make that a reality.

**Comment by holdenhinkle** [comment]
I went over this ticket with Josh. He's going to meet with Jon to discuss his approach to integration VA Notify into Appoint before he closes this.

**Comment by oddball-lindsay** [comment]
Thanks!  @opticbob if you could leave some notes here, or in Slack for your rough approach that'll help me to queue up future tickets 🙏

**Comment by oddball-lindsay** [comment]
Handing this over to Josh to own for first focus on this upcoming sprint.  Leaving Holden assigned, but more of a consultant role.

**Comment by opticbob** [comment]
VA Notify Intake Form:  **Update as needed before submitting**

## Your Details
1.  Josh Fike
​
2.  **Business Line**
    Benefits
​
## Notification Details
1.  **Notification type**
    Email
​
2.  **Please describe your use case.**
    After a veteran or claimant fills out a 2122 or 2122a form online and downloads a filled out PDF we want to send them an email reminding them of the next steps they need to take.
​
3.  **What actions can the user take based on the notification they receive?**
    Schedule an appointment with an individual or organization to sign their form.
​
4.  **What is the desired business outcome?**
    Easier establishment of POA relationships.
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    vets-api
​
6.  **What will trigger the notification?**
    Clicking submit on the online form filler for the 2122 and 2122a.
​
7.  **Provide sample content per notification type, if you have it.**
    _This is the next steps page, right?_
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    **???**
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    We'll provide the contact information, we aren't requiring users to be logged in for the form fill experience.
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)
​
11.  **What is the anticipated volume of notifications per day, week, month?**
​
12.  **When does this notification need to be in production?**

**Comment by oddball-lindsay** [comment]
@opticbob we actually have an intake already!  https://github.com/department-of-veterans-affairs/va.gov-team/issues/84313

We can use that for general support questions related to our work, and I have it hanging out the board's "In Progress" column for quick access.  Is there anything in particular you are looking for help with, or just doing that intake bc the process says to start with an Intake?

**Comment by opticbob** [comment]
@oddball-lindsay That's perfect!  I just completely missed it at the top of the ticket.

**Comment by opticbob** [comment]
Daily Update

- Read through the VA Notify Playbook
- Started (unnecessary) intake form

**Comment by oddball-lindsay** [comment]
@opticbob here are the variables that the template is looking for.  The only guideline the VA Notify template has is that personalization variables get wrapped in the double parenthesis.  At some point I imagine I'll need to know what we call these variables in the backend and then we can update the template in VA Notify Staging, accordingly.

1. First name (I think this might be `first_name` universally, from Profile)
2. Form name
3. Form number
4. Representative name
5. Representative address
6. Representative type

**Comment by holdenhinkle** [comment]
A new endpoint to trigger the email will have to be created. We'll hit the endpoint when the user clicks on the final 'Continue' button as displayed here - https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/91412

**Comment by opticbob** [comment]
Tasks for VA Notify intergration:
- **New endpoint to trigger email.**  On the mockup on [Download page #91412](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/91412) you can see how the pdf download is a seperate link and the email will be triggered by the `Continue >>` button.  That button needs an endpoint.
- **Confirm if template keys with spaces are allowed.**  Right now only `first_name` has an underscore and no spaces.  All other keys in the template are something like `form name` and `form number`.  This is probably in the docs but we can confirm in the `#va-notify-public` slack channel if necessary.
- **Send email in new endpoint.**  Example [here](https://github.com/department-of-Veterans-affairs/vets-api/blob/master/modules/va_notify/README.md#using-the-wrapper-sidekiq-class-async-sending).  Our template is titled `Appoint a Representative v1 - Confirmation and Next Steps`.  The Service and Template IDs are both available on the template page at `staging.notifications.va.gov`.  I've confirmed with the VA Notify team that we don't need a specific API key, we are free to use the default which means we don't have to specify one at all.
- **Copy the template into production.**  Once the template is confirmed to be working correctly in staging we can copy it as is into production.  I'm not sure if there is an interface for this or if we just copy and paste it into the production tab on `notifications.va.gov`.
