### ISSUE TITLE
VSP - Views & Cancel VA appointments

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9032]
As a veteran, I want to view all of my VA appointments in one interface so that I don't have to look at multiple tools.

As a VA stakeholder, I want VA appointments shown to Veterans to use the latest VistA Scheduling Provider endpoint and the FHIR data format. 

## Definition of done
- [ ] Veteran can see all of their confirmed VA appointments
- [ ] Veteran can cancel their VA appointments
- [ ] Appointments list follows appropriate display behavior
- [ ] Design review complete ?
- [ ] Full QA testing complete for view/cancel
- [ ] 508 review complete for view/cancel

**Comment by laurenernest** [comment]
No longer needed
