### ISSUE TITLE
DevOps] Discovery on automating LoROTA private key propagation to `vets-api`.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#90324]
## Description
See #86718 and #90260.

Currently, there is no automation in place to convey the LoROTA private key used for client-server communication between `vets-api` and LoROTA to `vets-api`. This introduces delays and introduces risks from human fallibility and unclear security procedures.

We should determine a way to automate this process to make it more reliable and secure.

## Tasks
- [ ] [DevOps] Determine how this private key is currently maintained within `dsvagovcloud` and deployed to `vets-api`. If this is read and deployed at deploy time, what delay does this incur? Is this avoidable?
- [ ] [DevOps] Determine how best to automate this update. Depending on outcomes from #86717 and #86718, this may require changes to `vets-api` code to allow seamless verification of data encrypted with previous versions of the key. Document in this thread.
- [ ] [DevOps] Determine what actions are needed to be able to assume a role within `dsvagov` AWS and if we have a solution in place to achieve this or if we need to perform additional work. If so, open ticket(s) to address.
- [ ] [DevOps] Determine a testing strategy that will reassure Gaurav and Kanchana about the reliability of this process, and open followup ticket(s) to address specifics.
- [ ] [DevOps] Open followup ticket(s) to address specifics of implementation.

## Acceptance Criteria
- [ ] Unavoidable delays determined and documented in this thread.
- [ ] Automation strategy determined and documented in this thread.
- [ ] Followup ticket(s) opened if necessary to be able to perform related actions in `dsvagov` AWS account.
- [ ] Followup ticket(s) opened to address specifics of manual and automated testing strategy.
- [ ] Followup ticket(s) opened to address specifics of implementation.
