### ISSUE TITLE
Address EKS Postman collection test hangup - test user 228 lacks certain data points in vets-api-mockdata

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#90336]
## Issue Description
The Postman collection being developed for the Product Team's vets-api EKS cluster upgrade effort relies on the use of a test user account for testing authenticated endpoints.  The current test user, 228, has credentials configured in vets-api-mockdata, but it is missing key data values, such as contacts, or dependents, which hampers effective testing of those endpoints.

To this end, I am cloning 228 into a new user, 2280, on the vets-api-mockdata repo.  Then, it will be 

---
## Tasks
- [ ] _Create a PR for vets-api-mockdata that adds the user alongside the needed, relevant data._
- [ ] _Get the PR merged._
- [ ] _Change the Postman collection variables to use the newly added, properly configured mock user._

## Acceptance Criteria
- [ ] _The Postman Collection successfully authenticates and runs using the new test user(s)._
---

**Comment by IGallupSoCo** [comment]
After extensive personal review of the mockdata repo and conversations with members of the Product Team, it turns out that some data points for mock users are stored in the dev environment of VADIR- The VA Department of Defense Identity Repository.

To round out the data we need is simply impossible due to this integration.
