### ISSUE TITLE
VSP - View & Cancel VA requests

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9033]
As a veteran, I want to view all of my VA appointment requests in one interface so that I don't have to look at multiple tools.

As a VA stakeholder, I want Veterans to see their VA appointment requests using the VSP endpoint and FHIR data modal. 

## Definition of Done:
- [ ]  Veteran can see all of their confirmed VA appointments
- [ ] Veteran can cancel their VA appointments
- [ ] Appointments list follows appropriate display behavior
- [ ] Design review complete ?
- [ ] Full QA testing complete for view/cancel
- [ ] 508 review complete for view/cancel

**Comment by laurenernest** [comment]
No longer needed
