### ISSUE TITLE
[FE] My VA: Investigate/de-bug My VA crashing in prod and staging

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#90343]
## Background
We first noticed that My VA was not loading in staging, particularly after attempting to create a draft form/application. After investigating further, we noticed this was also happening in production. The issue was flagged for platform support originally as a staging issue and later escalated to a production issue.

## Tasks
- [x] Investigate and triage issue
- [x] Formulate solution (short term is fine)
- [x] Execute necessary steps for out of band deployment
- [x] Create post-mortem doc and discuss with team
- [x] work with AJ to create an follow-up tickets for future improvement

## Acceptance Criteria
- [ ] My VA is functioning again in production and staging

## Resources
- [VFS platform support thread](https://dsva.slack.com/archives/CBU0KDSB1/p1723142981021689)
- [OOB deployment request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90350)

**Comment by allisonlu** [comment]
[PR was merged](https://github.com/department-of-veterans-affairs/vets-website/pull/31286) yesterday evening

some future improvements can include:
- refactor?
- add unit + e2e tests
- implement analytics tracking - get errors sent to Datadog

**Comment by allisonlu** [comment]
PR for post-mortem has been opened: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1834

**Comment by ajakabcin** [comment]
closing this out - we'll have one follow up ticket for now to improve error monitoring
