### ISSUE TITLE
VSP - Self-schedule VA apppointment

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9034]
As a veteran, I want to be able to self-schedule an appointment directly without needing to request an appointment for a VA provider that I've already seen.

## Definition of Done:
- [ ] A eligible Veteran can self-schedule VA appointments
- [ ] To be eligible a Veteran must:
   - Direct scheduling is configured for the selected type of care at the selected facility
   - Veteran has been seen for the selected type of care at the given clinic in the past 2 years 
- [ ] Full QA testing complete for view/cancel
- [ ] 508 review complete for view/cancel

**Comment by laurenernest** [comment]
No longer needed
