### ISSUE TITLE
Review and finalize accessibility testing plan for VADS publishing

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#90358]
## User Story
As a content and IA specialist on Governance team, I want to review the Accessibility Testing Plan documented by Governance and DST a11y specialists to modify/edit it for a VFS audience and VFS-facing consumption on the VA Design System website.

Assignee: @erinrwhite @KKitagawa-Bosch 
Peer Reviewer: @shiragoodman 

## Description
Governance and DST team members wrote an accessibility testing plan for VADS components that now needs to get ready to publish to the VADS. The purpose of this ticket is to have Governance content and IA specialists review the document and make edits/modifications to ensure it's easily understood by VFS teams, as well as to ensure it follows our own standards for content and IA on VA.gov.

This ticket will also include a review of the current[ Accessibility page](https://design.va.gov/about/accessibility/) on VADS. The Accessibility testing plan will live as a new document under the Accessibility hierarchy. The goal is to have both pages aligned and cohesive.

## Tasks
- [x] Create a documentation draft of the page in Confluence for easy editing. Feel free to do the same for the existing [accessibility page. ](https://design.va.gov/about/accessibility/)
- [x] Modify and edit the accessibility testing plan so that is easy to read and comprehend. Feel free to reach out to @briandeconinck or @rsmithadhoc for questions and/or clarity
- [x] When the page is ready, share with Shira, Carol and Matt for input.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The accessibility testing plan is ready to be published to the VA Design System website.
- [x] The accessibility page that currently lives on VADS has proposed changes so that it flows nicely with the accessibility testing plan and does not contradict anything within the plan

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by briandeconinck** [comment]
@erinrwhite and @KKitagawa-Bosch the [accessibility testing plan draft](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/8b49df2eddc3956daf9cff03728430311c597631/src/_about/accessibility/accessibility-testing.md) is ready for you to do your thing!

**Comment by briandeconinck** [comment]
Please ping me with any questions / things that aren't clear in what @rsmithadhoc and I have so far.

**Comment by erinrwhite** [comment]
thanks @briandeconinck ! 

@briandeconinck and @rsmithadhoc: Can y'all verify that the purpose of this new page is to share our accessibility testing process **for VADS components**? Or will it be a resource for VFS folks hoping to understand how to complete accessibility testing in general? Or both? Either way, we will need to be very clear with the title of the page. thank you!

@KKitagawa-Bosch I have created [draft copies of the pages in Confluence](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3397779483/90358+-+Erin+and+Keegan+-+Accessibility+testing+plan+for+VADS) I can spend a little time Wednesday morning reviewing the structure/flow of the doc, as well as headings, links and crosslinking. Then I could toss it to you?

**Comment by briandeconinck** [comment]
Good clarification! The purpose of this document is to describe how design system components are tested -- nothing else.

Not in scope: patterns and templates (not yet anyway!) and VFS products.

I think there's a lot VFS teams could learn from the document, but it's not prescriptive "you should do this" or even a "how to do this if you want to" document.

**Comment by shiragoodman** [comment]
great questions! Happy to jump in and help too, if needed. Brian is right. It's not a "you should do this" or a "how to do this if you want", but instead it's a "this is what was done."

Please let me know if you need anything!

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite 

Answered those questions on [Accessibility testing page structure](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3397320716/90358+-+Accessibility+testing) and moved that info to the [Accessibility page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3397517323/90358+-+Accessibility). Also added a comment/question on the Accessibility page!

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite seems good to me! I would have (B)R(y/i)an take a look!

**Comment by erinrwhite** [comment]
@briandeconinck @rsmithadhoc 

Hi you two! We have been working on suggested updates to the accessibility testing and accessibility pages in VADS:

- [(New) Accessibility testing page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3397320716/90358+-+Accessibility+testing)
- [Accessibility page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3397517323/90358+-+Accessibility)

@shiragoodman thoughts on how to proceed once Brian and Ryan have reviewed? A pull request for this in GitHub?

**Comment by shiragoodman** [comment]
this ticket can be closed when Shira and Brian provide feedback. We do not need fb from Matt, Carol and/or Ryan in order to close this ticket.

**Comment by shiragoodman** [comment]
@erinrwhite @KKitagawa-Bosch @briandeconinck I think both new pages look good. The only comment I have is on the new Accessibility Testing Page. The _Testing Methodology_ section is basically the categories of the Accessibility Component checklist which is included on each component page (or apparently, only for the ones that have a BEST PRACTICE maturity scale). There's no content that ties this section of the doc back to the component checklist. 

The accessibility component checklist is changing, so the live versions on component pages now (such as [list](https://design.va.gov/components/list#component-checklist)) will not align with what's in the Testing Methodology section, but please make an attempt to connect the 2. Please lmk if you have any questions.

**Comment by erinrwhite** [comment]
> @erinrwhite @KKitagawa-Bosch @briandeconinck I think both new pages look good. The only comment I have is on the new Accessibility Testing Page. The _Testing Methodology_ section is basically the categories of the Accessibility Component checklist which is included on each component page (or apparently, only for the ones that have a BEST PRACTICE maturity scale). There's no content that ties this section of the doc back to the component checklist.
> 
> The accessibility component checklist is changing, so the live versions on component pages now (such as [list](https://design.va.gov/components/list#component-checklist)) will not align with what's in the Testing Methodology section, but please make an attempt to connect the 2. Please lmk if you have any questions.

@briandeconinck I think this is maybe a question for you - is there a way to explicitly tie the current or future version of the accessibility checklist that appears on each component's page back to this [accessibility testing for components page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3397320716/90358+-+Accessibility+testing)?

![Screenshot 2024-09-03 at 4 07 44 PM](https://github.com/user-attachments/assets/75bbf12d-9403-4c9c-8e80-da51022eb32f)

**Comment by briandeconinck** [comment]
@erinrwhite and @KKitagawa-Bosch Finally coming back to this! I've made some very minor edits, plus added another section to the end of the document to address @shiragoodman's comments. Could you all read what I've added and make any edits needed if it doesn't make any sense?

Otherwise I think this looks great and is good to go! cc @rsmithadhoc

**Comment by KKitagawa-Bosch** [comment]
Looks good to me @briandeconinck !

**Comment by erinrwhite** [comment]
@briandeconinck What's the new section you added? Not sure I'm seeing it...

**Comment by briandeconinck** [comment]
@erinrwhite Very bottom of the testing page, the bit about the component checklist (after the methodology section)

**Comment by erinrwhite** [comment]
@briandeconinck Is your version published? This is what I'm seeing at the bottom of the page...


![Screenshot 2024-09-06 at 11 37 38 AM](https://github.com/user-attachments/assets/7fe32bdf-0ac7-46be-8f3b-33c87d8b9ff1)

**Comment by briandeconinck** [comment]
@erinrwhite Apparently not! But they are now! [Accessibility testing page, now with bonus content](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3397320716/90358+-+Accessibility+testing)

**Comment by erinrwhite** [comment]
@briandeconinck That looks excellent! @KKitagawa-Bosch One last look? Then I think the next step is that we share with Matt and Carol - @briandeconinck @rsmithadhoc does that make sense, or do y'all want more time?

**Comment by briandeconinck** [comment]
I am good to let this move on to the next thing 🙂

**Comment by KKitagawa-Bosch** [comment]
Looks good to me! Love the example, that clarified all the questions I had from the first part lol

**Comment by erinrwhite** [comment]
[Shared with Carol and Matt on Slack.](https://dsva.slack.com/archives/CJRQ85PQB/p1725887383237039) 

@KKitagawa-Bosch I think this means we are good to close. Can you review?

**Comment by erinrwhite** [comment]
thank you!
