### ISSUE TITLE
[UX] Personas + Journey Maps - Start docs and research gathering

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#90352]
## Issue Description
Being an HCD focused UX team; we are missing key resources that can help us build empathy for Veterans and Caregivers and when storytelling and presenting UX problems to solve.

We have some existing research and knowns we can start to gather into one central place representing to start a collection of living documents. 

- [Mural folder for UX Docs](https://app.mural.co/t/departmentofveteransaffairs9999/r/1670613238628?folderUuid=d25d50be-c36e-434e-bfb7-b6e4c54e329a)

---
## Tasks
- [ ] Start with template gathering of what could be useful
- [ ] Pull from existing research - team user research and desk research
- [ ] Team working sessions
- [ ] Review with design lead
- [ ] Review / show-and-tell with the entire EZ/CG and EZR teams

## Acceptance Criteria
There is a place and a process to ad to a living collection of helpful UX documentation. We will decide if future research is needed to fill in the gaps.
---

**Comment by jessicastump** [comment]
Duplicate of #90351 - zen hub and slow wifi
