### ISSUE TITLE
CCSP - View CC appointment & request

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9035]
As a Veteran, I want to see my Community Care appointments and requests in one list so I do not have to go between different tools to see all of my appointments. 

## Definition of Done:
- [ ] Veteran can see all of their confirmed CC appointments
- [ ] Veteran can see all of their CC appointment requests
- [ ] Appointments list follows appropriate display behavior
- [ ] Design review complete ?
- [ ] Full QA testing complete for view/cancel
- [ ] 508 review complete for view/cancel

**Comment by laurenernest** [comment]
No longer needed
