### ISSUE TITLE
[UX] Personas + Journey Maps - Start docs and research gathering

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#90351]
## Issue Description
Being an HCD focused UX team; we are missing key resources that can help us build empathy for Veterans and when storytelling and presenting UX initiatives. 
We have some existing research and knowns we can start to gather into one central place representing to start a collection of living documents. 

---- 

#### Benefit to the Veteran
Improve their experience with the online health care enrollment and update process and/or better understand what pain points exist and why so we can prioritize work.

#### Where
This was initiated by the UX team through weekly convos and the last UX retro - [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709744287345/b4e1721b91ff249571787e3e267a42ba9c4de18d?sender=uadf1ed7fe7c76f0914967329).

#### Why
We want to better understand the variety of people that interact with both the forms and their various journeys. We want to be better positioned as a UX team to have these living documents started and available to evolve.

#### What
- Start by creating templates to use with definitions
- Gather existing supporting journey mapping research to buidl docs

#### References / Resources

- [Mural folder for UX Docs](https://app.mural.co/t/departmentofveteransaffairs9999/r/1670613238628?folderUuid=d25d50be-c36e-434e-bfb7-b6e4c54e329a)

---

## Tasks 
- [x] Start with template gathering of what could be useful (folder listed in resources)
- [x] Setup the initial health care enrollment scenario journey and area to brainstorm sub journeys
- [x] Pull from existing research - team user research, desk research and UGC work and voice of customer data from medalia
- [x] Schedule team working sessions 
- [x] Review with design lead at a UX sync
- [x] Review / show-and-tell with the entire EZ/CG and EZR teams

## Acceptance Criteria
There is a place and a process to ad to a living collection of helpful UX documentation. We will decide if future research is needed to fill in the gaps.

---

**Comment by jessicastump** [comment]
Wondering if we should repurpose this ticket or close it? Can chat async or will add to the agenda for the next UX weekly sync. 

There is a [folder in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/r/1670613238628?folderUuid=d25d50be-c36e-434e-bfb7-b6e4c54e329a) with a few templates and what artifacts have been created or referenced so far:
- [A few empathy maps started for health care enrollment](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1736887060487/2d71d53262d31b6db104d6a345089976f925d57c)
- [Journey maps from social listening research](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1726015217433/addfbc4bd436b875581210230719532d11839e7f)
- [Journey maps from HEC SME registration sessions](https://app.mural.co/t/departmentofveteransaffairs9999/r/1670613238628?folderUuid=4d5b2470-9820-44e2-80f7-6e807bb94f8e)
- [Content map [WIP]](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1733859977673/4674b85aaaeca1ee7be90edbf964ef773adc8be4)

**Comment by jessicastump** [comment]
Closing - what we have is gathered in Mural what we have to date per various initiatives of registration, health care journey, empathy maps and the eligibility content map.
