### ISSUE TITLE
Content Edit: Footer Ticket 90104

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90357]
## Issue Description
Per [Feedback Footer request ticket 90104](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90104), Content Team needs to add an alert box to the top of the [PII Guidelines Page ](https://depo-platform-documentation.scrollhelp.site/developer-docs/personal-identifiable-information-pii-guidelines)reminding VFS Teams that people aren't allowed to copy VA PII outside of VA.

---
## Tasks
- [x] Read [footer ticket 90104](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90104)
- [x] Add an info box to the top of the [PII Guidelines page](https://depo-platform-documentation.scrollhelp.site/developer-docs/personal-identifiable-information-pii-guidelines) with the following message:
>## PII storage and processing restrictions
>
>VA PII may never be stored on, processed on, or transmitted through non-VA assets.
>
>This means, for example, that you may not email files containing PII to non-VA email addresses, or store or process PII on non-VA computers, or store PII within non-VA cloud services such as Google Drive, even temporarily.
>
>This restriction is clearly enunciated in the training which all VA employees and contractors are required to take during onboarding and periodically thereafter.
>
>PII may be stored and processed, e.g.:
>
>* on VA government-furnished equipment;
>* within VA Azure Virtual Desktop or VA Citrix Access Gateway; and
>* within the production VA.gov AWS account.
>
>Please reach out to platform support for assistance if you need to process PII and the computing resources accessible to you are insufficient to the task .

- [x] Review page update with ticket author @JonathanKamensDVA , confirming info box color and style, any external links to channels in Slack, etc.
- [x] Prepare updated page for deployment
- [x] Check for launch blockers

## Acceptance Criteria
- [x] Page is updated and ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90357?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by BSmolensky** [comment]
Read through original ticket. Created Copy/Draft version of page. Working on solution.

**Comment by BSmolensky** [comment]
Link to DRAFT changes sent to SME. Waiting for response/approval.

**Comment by BSmolensky** [comment]
SME approved update. Updated page is ready for deployment. Once deployed, this ticket can be closed. 
Link to changes: https://vfs.atlassian.net/wiki/spaces/pilot/pages/894271679/Personal+Identifiable+Information+PII+guidelines

**Comment by BSmolensky** [comment]
Pages is now live on the PW: https://depo-platform-documentation.scrollhelp.site/developer-docs/personal-identifiable-information-pii-guidelines

Closing Ticket.
