### ISSUE TITLE
Disco: Determine how we might log users out when session expires

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#90360]
## Issue Description
As a Veteran I don't want my submission to fail because I lingered on the Review & Submit page longer than the session timeout window (I also don't know what that is). I expect to be logged out automatically if my session expires, not continue to use the app assuming it's still functional.

---
## Tasks
- [ ] What would it take to get this implemented?

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by christinec-fftc** [comment]
This issue occurred during UAT testing, where we were on the review page for 8 minutes reviewing the data, then tried to submit, but the session had expired. User name was still displaying in the header when the error occurred.

Some related older tickets
Log users out on inactivity (session timeout) #84533
Session timeout in form 526 - better handling #20543

**Comment by pacerwow** [comment]
[Uploading... screencapture-staging-va-gov-disability-file-disability-claim-form-21-526ez-review-and-submit-2024-08-08-12_47_54.png]
