### ISSUE TITLE
CCSP - Make a CC appointment request

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9037]
As a veteran eligible for community care, I want to be able to request Community Care appointments online the same way that I request VA appointments so that I don't have to waste my time by calling into the VA instead.

#Definition of Done:
- [ ] Veterans can submit appointment requests for Community Care appointments
- [ ] Veterans who are eligible for Community Care and choose a CC-supported type of care get to choose between CC & VA care
- [ ] Veterans who are not eligible for Community Care don't see any Community Care options in their scheduling flow.

**Comment by laurenernest** [comment]
No longer needed
