### ISSUE TITLE
[FE] 10-10CG - Facility page: Create confirmation screen for selected facility and render parent facility if selected does not offer caregiver services

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#90381]
As a caregiver who is signing up for caregiver services, I want my submission to go to a health care facility that can process my application so that my submission can be processed as fast and accurately as possible. 

- If a selected facility does not offer caregiver services, display the parent facility and pass that on in the submission data.
- If selected facility does offer caregiver services, skip the page.

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- Figma designs
     - [Search Input](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2475-14725&t=xgkK7brjz069I7kE-0)
     - [Search Error](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2475-16237&t=xgkK7brjz069I7kE-0)
     - [Search Results](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2476-14650&t=xgkK7brjz069I7kE-0)
     - [Search Selection](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2476-15276&t=xgkK7brjz069I7kE-0)
     - [Search Selection - error](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2476-15822&t=xgkK7brjz069I7kE-0)
     - [Confirmation - different](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18217&t=xgkK7brjz069I7kE-0)

## Tasks
- [x] Add conditional logic to render/not render the facility confirmation page
- [x] Render both the selected facility and parent facility
- [x] Pass the facility with caregiver services as the selected facility to the submission data
- [x] Ensure all work is implemented behind feature flag and not visible in production

## Acceptance Criteria
- Facility confirmation component successfully renders the parent data of the selected facility (if no CG services offered) or its own data (if CG services are offered)
- The facility passed in the submission data and rendered on the 10-10CG PDF will be a facility that can process caregiver requests
- All created components match the provided designs from the UX team

**Comment by hdjustice** [comment]
Updated design links

**Comment by allanto-ah** [comment]
Environment: Dev

Based on this conversation in [slack](https://dsva.slack.com/archives/CMJ2V70UV/p1725899858091259), this is a required question. The following issues below in this comment is related to that.

### Issue 1: The "Required" tag is missing
<img width="1238" alt="Screenshot 2024-09-09 at 9 19 47 AM" src="https://github.com/user-attachments/assets/c656d33e-488e-4074-9b2f-a85644b9ca7b">

### Issue 2: I can continue through this question without selecting any options
https://github.com/user-attachments/assets/ac2aaa6d-0900-44f4-a729-c6a701c01118

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the above issues have been fixed. Review screen [(70847)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70847) and "show more" functionality [(70846)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70846) will be verified on their own tickets
