### ISSUE TITLE
Implement page size limit and error message

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#90383]
## Issue Description
_Claim attachments submitted through Data Dimensions are limited to a page size of 78"x101". If the page size exceeds that amount, the attachment fails to submit, but the user is not currently notified. The Burial, PCPG, VRE, and 686/674 form need to check for page size and then show an error to the user when they attempt to upload a page that is too large._

See similar work on the 526 [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77041), and they suggest reading the file content and extracting the image dimensions. The 'pdjs-dist' library (already installed) might be used to find a PDF's dimensions.

[CAIA approved](https://dsva.slack.com/archives/C01K37HRUAH/p1706636655605619?thread_ts=1706627044.030149&cid=C01K37HRUAH) error message:
`Your file can't have a [width/height] larger than [dimension]. Follow the instructions for your device on how to resize the file and try again.`

---
## Tasks
- [ ] Add page size check to Burial, PCPG, VRE, and 686/674
- [ ] Add error message to Burial, PCPG, VRE, and 686/674

## Acceptance Criteria
- [ ] Burial, PCPG, VRE, and 686/674 check for page size limit
- [ ] Burial, PCPG, VRE, and 686/674 display error message if upload exceeds page size limit
---

**Comment by mjknight50** [comment]
This is being discussed more broadly and should not be worked on.

**Comment by mjknight50** [comment]
We should revisit this with the work that @danlim715 did for pension/burial

**Comment by Mottie** [comment]
In the Decision Reviews forms, uploads to the backend are first validated using this [Lighthouse `/uploads/validate_document` API endpoint](https://developer.va.gov/explore/api/benefits-intake/docs?version=current). Any errors are returned and immediately displayed before saving the document to the S3 bucket on the backend

**Comment by wayne-weibel** [comment]
@mjknight50  There may still be limitations to the file uploads, but nothing is called out in the api docs.  But there already exists the evidence upload validation for pension and burial (assumes using LH Benefits Intake) which is active and a message returned to the user at the time of upload. `app/controllers/v0/claim_documents_controller.rb#validate_pdf_document`

**Comment by steele-lm** [comment]
Wayne and Huy to test Claim Evidence API integration to see if validations are in place and working.

**Comment by steele-lm** [comment]
See related work for pension/burial in #109765

**Comment by wayne-weibel** [comment]
<img width="741" height="345" alt="Image" src="https://github.com/user-attachments/assets/6edb307b-eee1-44de-bb19-1360d22193cb" />
