### ISSUE TITLE
Update Form 5655 intro page footer URL

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#90395]
## Issue Description
The ARM team has requested VODA to update the [Form 5655](https://www.va.gov/manage-va-debt/request-debt-help-form-5655/introduction) to reference the ARM team landing page as the default in the footer.

[DSVA Slack thread reference](https://dsva.slack.com/archives/CPE4AJ6Q0/p1723148366330879)

CAIA Content:
If you need help gathering your information or filling out your form, you can appoint a VA accredited representative.
[Get help filling out a form](https://www.va.gov/get-help-from-accredited-representative/)

<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce2b8fe6554c30be3e48429f63a5def29b5a4b1f/image%20%2829%29.png" alt="image (29).png" />

---
## Tasks
- [x] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [x] ARM team landing page is referenced as the default for VA form 5655
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
