### ISSUE TITLE
[UX] 10-10EZR NOK/EC: Update the design for the List&Loop pattern

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#90399]
## Issue Description

Currently, Veterans can only VIEW their Emergency Contact information and Next of Kin information on the Profile and Check-in flow. Adjacent team research shows that Veterans strongly desire a way to edit their NOK/EC information. 

This work is to add Emergency Contact (then Next of Kin) into the EZR flow so there is a place for Veterans to edit this information.

We will utilize the recent release of Form Library's List & Loop pattern.

## References/Resources
- [NOK/EC Figma ](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=0-11540&t=fsBR7ZlEDM89SauC-1)
- [Design system pattern guidance
](https://design.va.gov/patterns/ask-users-for/multiple-responses)

---
## Tasks
- [x] Refresh the NOK/EC with the EZR team
- [x] Update designs and references in Figma with capture notes and callouts
- [x] Review with UX team and align changes with EZ/CG
- [x] Make adjustments + additional pattern investigation 
- [x] Review with EZR team 

## Acceptance Criteria
- The designs using the latest design system guidance and aligned with EZ.

**Comment by IMHieuVo** [comment]
**Aug 8, Team Refresher summary**:
- Hieu presents an overview of the project: why we're doing this, where it will be located, and how it aligns with our EZR v2.
- The EZ/CG team is doing adjacent work with insurance information using the next list & loop pattern. We'll be sharing notes.
- Hieu shows the graphical out-of-the-box list & loop pattern and Devs notes that the current vs changes comparison in recent projects has been helpful.  
- Action Item: Hieu to create a comparison between out-of-box vs our version.
- Hieu notes that the text and icon can be changed, Save-in-progress works, and conditional (in theory) should be possible.
- Josh notes that this work is try-quickly and fail-quickly approach. Devs show hesitation since EZ is also doing similar work and would be 'failing' as well.

**Comment by IMHieuVo** [comment]
Aug 20 Design Office Hour summary, regarding list & loop component:
- Visual changes are not a big deal, proceed with frontend since it does not change how they are coded.
- Team should connect with Jeana Clark when they diverge from the Forms pattern
- Platform is okay with differing versions (Forms vs Custom) as long as it is not on the same page and there is an intent to update the Custom at a later date. It will not be a launch blocker. 
- Platform will now call out custom List & Loop in their reviews.

**Comment by emily-brown34** [comment]
content/design is fine with the emergency contact fields NOT being labeled primary and secondary

**Comment by IMHieuVo** [comment]
**Primary and Secondary Emergency Contacts/ Next of Kin** conversation note from [Slack](https://dsva.slack.com/archives/C05QKRZGHFS/p1725916078825379).
- The paper form only asks for 1 EC/ 1 NOK. The VES schema has 4 data points - Primary EC, Other EC, Primary NOK, and Other NOK.
- The team is using the Forms Library’s List&Loop and there isn’t an out-of-box “primary” and “secondary” label. - UX is okay with excluding the primary/secondary label since the team notes that a typical emergency contact is usually a phone call to see who picks up first and the paper form only asks for 1 contact.
- Renata notes that while this logic works for EC, NOK is trickier since it involves representation and people do have designated primary and secondary decision-makers.
- The following requires discovery/testing from developers:
  - The main point of friction is between UX and the backend. How does the backend VES schema determine a Primary EC vs a Secondary EC value?
  - If we determine value by the submitted order, what if the Veteran saved-in-progress and comes back to change the data?
If we determine value by the submitted order, it may be better for the backend to break the VES schema into an EC schema and a NOK schema.
  - Instead of trying to submit for Primary EC and Other EC, can the frontend submit 2 primary instead?
  - Is it possible for the frontend to modify the List&Loop component to display the Primary vs secondary label?
  
- - - - -

- Devs also ran into serval launch blocking bugs with the List&Loop component.
- Due to the above reasons, the content review was put on hold (9/9). Everything else has been reviewed and commented on.
- I've added tags to all of the Content changes.
