### ISSUE TITLE
Tactics for OKRs

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#90393]
## Background
We have been working with our PO to define [Objectives and Key Results](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718224425278/b300ea8d63dcaaa0cdad0ebf6b4a65a20fcc9371?sender=ubac5f0487f25bc4431288699) for our products.  This ticket is to add in "tactics" which will define how we will measure the key results.

## Tasks
- [x] Add in tactics for the content OKRs
- [x] Add in tactics for Find a Rep OKRs
- [x] Add in tactics for Widget OKRs

## Acceptance Criteria
- [ ] Tactics have been defined, and ready for review in the next leadership sync 8/13.

**Comment by oddball-lindsay** [comment]
@jfinnerty13 I added in tactics to our [ARM OKRs Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718224425278/b300ea8d63dcaaa0cdad0ebf6b4a65a20fcc9371?sender=ubac5f0487f25bc4431288699), heavily inspired by what you have already pulled in GA4.  

If you have time, I'm curious about your initial thoughts -- feel free to comment directly in Mural!  And if not, no worries - I think we'll have time to discuss together with Jen in the leadership sync on Tues 8/13.

**Comment by oddball-lindsay** [comment]
Calling this "good enough" for now.  Didn't get a chance to discuss in the 8/13 leadership sync, but can find a different time for that discussion.
