### ISSUE TITLE
[Design] 10-10CG Figma clean up for facilities search

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#90406]
## Issue Description

The designs for the facility search were done in Sketch over a year ago. The page was migrated during the Figma migration work, but the page is very cluttered with past versions that are not relevant. The figma file is also not using the correct page template/component structure setup (things are not all linked to VADS library they are all local components)

This ticket is for Figma clean up to move the final designs into the most recent component setup and move to it's own page.

### Benefit to the Veteran/Caregiver/Representative: 
Veterans and their Caregivers will have confidence in selecting the Veteran's preferred facility, which will also ensure the submitted application is routed to the appropriate Caregiver service facility for processing. 

### Where
Internal initiated UX request - minor clean up / enhancement

### Why
No ensure the designs reflect the most resent USWDS v3 upgrades and content standards known since the initial designs / design intent was before the upgrades.

### What
Figma work - some could impact development - to ensure we are using the latest design system components available.

-----

#### References + Resources

- [Original page in Figma](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=0-5034&t=36hh5JZXFLBpFqvj-0) - Highlighted section at bottom was final designs
- [New figma page](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18708&t=36hh5JZXFLBpFqvj-4)
- [Mural user flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723306412955/870b3cdf19a7f27c2b699e0fadb14c0d022ae3cc?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks (order of operations)
- [x] Create a page in Figma and move over final designs
- [x] Make sure all components and screens are linked to the most recent templates (create content templates for this to work)
- [x] Annotate the designs with any relevant notes or callouts for development
- [x] Review with UX team at weekly sync or async
 

## Acceptance Criteria
- There is a page in Figma that shows only the final designs with the most recent VADS components. 
### Signoff
Designer will review with PM and Devs.

----

**Comment by jessicastump** [comment]
**[New figma page](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18708&t=36hh5JZXFLBpFqvj-0)**

- Updates to VADS Figma component libraries 
- Content components created
- Production screens used for reference
- Original approved designs from Sketch for reference

**Comment by jessicastump** [comment]
@hdjustice - went over this with @aagosto90 during our ux working session so she is up-to-date on this while I'm out. I think this ticket is good to close?

**Comment by hdjustice** [comment]
Yep, I think it is good to go, thank you!
