### ISSUE TITLE
BE | My VA | Post mortem metrics

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#90409]
## Background
There was a [production issue](https://dsva.slack.com/archives/CBU0KDSB1/p1723146894966669) on Aug 10 that affected My VA.

As part of the post mortem, we need to include the number of users that were affected.

## Tasks
- [x] Write a Datadog query that shows the unique number of users affected by the issue.

## Acceptance Criteria
- [x] Review with the team.
- [x] Add results to post mortem document.
