### ISSUE TITLE
[Research] 10-10CG Research planning session + next steps 

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#90402]
## Issue Description
Need to review as a UX team, the existing usability study written for when the facilities search is implemented and what we need to learn to move forward with the caregiver clarification epic work and other post-July update UX debt items.

----

### Benefit to Veteran/Caregiver:
Better understanding of pain points and what is working on the 10-10CG form today and understanding of their overall process experience. This research will help prioritize and plan the usability and content issues that are the most important to the form users. 

### Where:  
Outcome of team working session going over CG ux backlog. We decided starting with research before prioritization made sense but need to evaluate logistics with the upcoming facilities work.

### Why: 
Develop a plan to fully cover what we need to learn to keep moving forward with at least two main initiative priorities - facilities and caregiver clarification.

### What: 
Prepare for and conduct a working session with UX team to create overall research next steps strategy. Once that is done, meet with PM/team to finalize any other tasks before submitting to research repo/review.

### References Resources
- [Mural discovery board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721340803913/0adab3113f083b21f225142fa83d28296648e31c?sender=uadf1ed7fe7c76f0914967329)
- Research ticket - facilities + baseline study [#47976](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47976)

---
## Tasks / Order of Operations

- [x] Schedule working session (Sept 20)
- [x] Prepare Mural board to include goals/questions from existing planned study and from ux debt list. 
- [x] Conduct a working session (or two) with UX team to complete research planning
- [x] Review with UX lead (if not attending all of working session(s))
- [x] Meet with PM to go over research strategy + action items needed before submitting to research repo/review

## Acceptance Criteria

UX team decision on direction for next steps for research on the 10-10CG form.
Will have information needed to complete any needed research plans/convo guides.

**Sign-off:** From Design Lead + PM

---

**Comment by jessicastump** [comment]
[Area added to Mural board here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721340803913/0adab3113f083b21f225142fa83d28296648e31c?wid=0-1723228965662)

**Comment by jessicastump** [comment]
@aagosto90 - Thinking this is a 3 or a 5 as the plan writing will probably be other tickets :) 

The [Mural board area is setup here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721340803913/0adab3113f083b21f225142fa83d28296648e31c?wid=0-1723228965662) - feel free to add anything else to this if you want this week, otherwise I think this is ready to go for the first working session next week on Tuesday.

**Comment by jessicastump** [comment]
Recap from [Slack](https://dsva.slack.com/archives/C05QKRZGHFS/p1724250919972829) of working session:

1. Went over background and research questions (in table) and from old facilities research planning
2. Decided representatives audience is not a primary group to do research with at this time (challenges there with recruitment)
3. Plan to focus on two cohorts within the caregiver audience group - using screener questions with Perigean -- a) those who are currently enrolled in the Caregiver Program and b) those who could be potential/new (?) caregivers
4. Have this be 1 study; a combo study of interview questions and content usability
5. We will have 2 cohorts and each will need their own convo guide

**Comment by jessicastump** [comment]
**Action items from meeting:**
1. Timing of facilities - Heather to confirm; team would like to get feedback on that confirmation page content
2. Clean up of research questions / goals based off of caregiver cohort focus discussed (updated on :mural: board)
3. Work with Luis to discover more about the paths before the introduction page.
4. Are Caregivers/Veterans getting the eligibility and benefits information they need before starting the application and additional content is not needed within the form?
Should we open a ticket for this and/or schedule a working session?
5. Adjust/open new tickets to create/update the research plan and convo guides
6. Schedule another meeting to go over timeline + research plan/convo guide drafts

**Comment by jessicastump** [comment]
[Post-July 2024 UX Backlog desk research + opportunity planning_2024-08-22_14-55-31.pdf](https://github.com/user-attachments/files/16713784/Post-July.2024.UX.Backlog.desk.research.%2B.opportunity.planning_2024-08-22_14-55-31.pdf)

**Comment by jessicastump** [comment]
With ticket number #91231 as next steps, I think we can close this ticket (Lois and Heather both joined the working session). For ticket #91231 the tasks are the next steps mentioned here and the AC includes reviewing with both Lois and Heather again for sign off before submitting to the research repo.
