### ISSUE TITLE
[BE] 10-10CG - OAuth2.0: Submit forms using new auth flow in Production

### ISSUE THREAD

**Issue by coope93** [department-of-veterans-affairs/va.gov-team#90419]
## Background
Now that the OAuth2.0 has been implemented in the Staging environment, and manual testing has validated the flow in Postman, we need to validate the vets-api code.
Additional code changes may be needed once additional validation can be done with the Mulesoft team.

### Resources
- [Exploration ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85120) 
- [Initial Development ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86425)

## Tasks
- [x]  Confirm Production environment is ready for Mulesoftis requested access by the consumer (va.gov)
     - DTC-I team will provide us the auth server URL, Client Id, and Client Secret in an encrypted email.
- [x] Add the production credentials to AWS Parameter Store
- [x] Validate that production credentials are set in prod environments (These will populate after the daily deploy at 1pm est)
    - Ensure the client_id, client_secret, token_url, and auth_token_path are all set and correct 
- [x] Validate results with PM for signoff
     - [x] Signoff is documented within the comments of this ticket
- [x] Turn flipper toggle on in production
- [x] Confirm submission in production after turning toggle on 
## Acceptance Criteria
- 10-10CG Submissions are using the new OAuth 2.0 authentication flow in production.

**Comment by coope93** [comment]
We met yesterday with the OCTO team and they still have some work on their end to get it ready in their production environment. This feature won't be turned on in production until January 2025 at the earliest.

**Comment by hdjustice** [comment]
Received note from CG team that they are ready to test. Responded that we are available to support testing.

**Comment by coope93** [comment]
They updated the config values for staging. After receiving all of the updated config values we are successfully submitting in staging again with OAuth 2.0. Next step is to get prod config values and update them. I created the variables in aws and just need to get the production values now.

**Comment by coope93** [comment]
[Slack thread from deployment](https://dsva.slack.com/archives/CMJ2V70UV/p1743630758822949). Deployment went smoothly yesterday evening. We had the maintenance banner on from 5:55pm est - 6:55pm est. We have been monitoring submissions since then and all submissions have been successful.

**Comment by coope93** [comment]
@alexseelig Can you add a note per the task list that a PM has signed off on this work?
