### ISSUE TITLE
Write front end documentation for process of implementing a new package in vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90428]
## Issue Description
Currently, no documentation exists advising VFS teams of the process they should follow if they wish to add a new package to vets-website. This documentation should be written and added to platform website as part of our developer docs for the front end.

---
## Tasks
- [ ] Write documentation for the process VFS teams should follow to add a package to vets-website.
- [ ] Add documentation to a location that will be published to platform website.

## Acceptance Criteria
- [ ] Documentation now is accessible to VFS team members for how to add a package to vets-website.
