### ISSUE TITLE
Collect Data on E2E tests that run too long

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90422]
## Issue Description
There are a few E2E tests that have started dragging out our test suite times in CI. These tests run significantly longer than the rest of the testing suite and need to be addressed by those teams. In order to establish a standard of what we expect for E2E test run times, we need to collect data on the average times tests take to run and see who the outliers are, and what the average is amongst the bulk of the tests.

---
## Tasks
- [x] Check E2E results data that's already being collected to see if runtime of test specs can be extracted from it.
- [x] If not, implement collection of test runtime data.
- [x] Aggregate data to spotlight outliers and averages of the bulk of the specs that are not running long.

## Acceptance Criteria
- [x] We can confidently implement a QA standard for test spec run time.
- [x] We have identified outliers and can make a plan to address these with the appropriate teams.

**Comment by CBonade** [comment]
https://va-gov.domo.com/page/604433393 Working dashboard is here. Cards can be added and rearranged easily.
