### ISSUE TITLE
Document process to add a package to vets-website

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90432]
## Issue Description
Currently no documentation exists documenting the process for VFS teams to add a package to vets-website. This documentation needs to be written and added to the Platform Website Developer Docs.

---
## Tasks
- [x] Write documentation covering the process of adding a package to vets-website.
- [x] Move the document to a location to be published in the Platform Website Developer Docs

## Acceptance Criteria
- [x] Documentation now exists for the process to add a package to vets-website.

**Comment by CBonade** [comment]
Document is in progress - will be finished today.

**Comment by CBonade** [comment]
https://vfs.atlassian.net/wiki/spaces/pilot/pages/3416064001/Third-party+Libraries
