### ISSUE TITLE
Track users who have been removed from github org

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#90438]
## User Story
As a _____, I want to catch users who have left the organization but have not officially been offboarded, so that they can be fully offboarded.

### Background
When a member of the VA ecosystem leaves, they or their manager are required to fill out an [offboarding ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+Offboarding%2C+operations&projects=&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D). Once submitted, Platform Support checks their access and removes them from any tools they're found in.

This process works but sometimes users fall through the cracks, meaning they leave without anyone submitting an offboarding request. 

### Proposed Solution
We could leverage the `github-inactive-user-mentions` repository, which automatically removes users from the department-of-veterans-affairs GitHub organization after 90 days of inactivity. We could be notified when someone is automatically removed, and Tier 1 support could investigate to see whether they've actually left. An offboarding ticket could then be opened to ensure all tools they had access to are checked for access.

We have the capability to receive these notifications in Slack, but we need to determine:
- What's involved in setting up these notifications?
- Is Tier 1 support okay with handling this? There are dozens of removal requests per month, so this could be a significant workload.

### Example Removal
Here's an example removal: https://github.com/department-of-veterans-affairs/github-inactive-user-mentions/issues/10204

## Tasks
- [ ] Determine if it's worth leveraging the `github-inactive-user-mentions` repo.
- [ ] If it's worth it, what's the best way to get the list of github users that have been removed? (Slack?)
- [ ] Discuss with Tier 1 support to determine if they can handle the workload of investigating these removals.
- [ ] Document the process for Tier 1 support to follow when they receive these notifications.

## Success Metrics
No (or fewer) offboardings are missed due to users being removed from GitHub without follow-up.

## Acceptance Criteria
- [ ] Notifications are set up in Slack for GitHub user removals. (or however we decide to get notified)
- [ ] A documented process for Tier 1 support to follow when investigating removals.
- [ ] Tier 1 support confirms that the process is manageable and effective.

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
