### ISSUE TITLE
on "what type of evidence do you want us to review as part of your claim" - initial click on "private medical records" checkbox triggers a validation error and does not check the box

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#90449]
## Issue Description
in Windows > Edge (via citrix access gateway)
also Chrome and Safari iOS

Initial click on "private medical records" checkbox value triggers a validation error and does not check the box. https://jmp.sh/MLUeeVfD . Can later click it again and save the value and clear the validation error.

---
## Tasks
- [x] Check to see if this is a V2 component, if it is consider updating it to V3
- [x] Look into the validation function to see if it's working properly
- [ ] 

## Acceptance Criteria
- [ ] Initial click on this checkbox selects the checkbox
- [ ] There is no validation error

**Comment by pacerwow** [comment]
Can reproduce on Chrome too.
https://www.loom.com/share/f151067de8754857a38e5e5a52d6e3a8?sid=6676bc94-ce19-4723-a26c-7e339306ac5a

**Comment by mchae-nava** [comment]
Pulling this back real quick, taking a second look
