### ISSUE TITLE
Create Policy Regarding va.gov Hyperlink

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90443]
## Issue Description
Per [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76566), Content Team should create a policy around when to make va.gov an active hyperlink and when not to hyperlink.
---
## Tasks
- [ ] Review [internal Slack discussion](https://oddball.slack.com/archives/C02LYB7QXS5/p1721831859537839) regarding this issue
- [ ] Team hold discussion to create new policy
- [ ] Decide how to check for hyperlink as a launch blocker
- [ ] Decide how best to deactivate links during deployment
- [ ] Create Tip of The Sprint ticket for this policy

## Acceptance Criteria
- [ ] All tasks complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Research result: k15t has responded regarding whether we can turn off all linking for va.gov with a single effort:
Hi Joe,

thank you for reaching out to us.

The way I understand your issue is that you’re authoring your documentation in Confluence and whenever you refer to [va.gov](http://va.gov/) the editor converts it to a hyperlink.

Currently, there is no direct way I know of to disable the automatic creation of hyperlinks when typing or inserting a URL into the Confluence Cloud editor. However, you can manually remove the hyperlink after it has been created by clicking on the hyperlink to select it, then use the toolbar that appears to remove the link.

Unfortunately this is a manual process and can’t be configured as the default.

I hope this helps.

Feel free to reach out to us again if you encounter any issues or have questions.

Cheers,

Paul
