### ISSUE TITLE
Change "learn more about toxic exposure" link

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#90445]
## Issue Description

Currently on "Are any of your new conditions related to toxic exposure during your military service? Check any that are related." in staging, What is toxic exposure > learn more about toxic exposure link goes to https://www.va.gov/resources/the-pact-act-and-your-va-benefits/  

Should go to https://www.va.gov/disability/eligibility/hazardous-materials-exposure/ per [Figma prototype](https://www.figma.com/proto/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?page-id=1236%3A54775&node-id=1236-54788&viewport=-3821%2C-2833%2C0.58&t=yLZnRseAzQzxbvYH-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1236%3A54956&show-proto-sidebar=1) 
also page in [design view](https://www.figma.com/design/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?node-id=1236-54788&t=8p9ttOiJxZWkG7hg-11) 

---
## Tasks
- [x] update the link
- [ ] …

## Acceptance Criteria
- [x] link points to new location
- [ ] …
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
