### ISSUE TITLE
Discussion: Link Appearance

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90442]
## Issue Description
Content Team needs to discuss whether to underline all links on Platform Website, per results of [this Discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76566)

---
## Tasks
- [ ] schedule discussion
- [ ] make determination on policy
- [ ] create action plan if necessaryt

## Acceptance Criteria
- [ ] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
