### ISSUE TITLE
Implement Final Table Solution into Mockups for "View your VA payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9045]
## Goal 
The final piece to the "View your VA payment history" mockups is centered around how the tables are presented.  Once the mockups are updated with this, FE should be able to get started in framing that feature.

## Tasks
- [x] Update View Payments mockup/prototype to show the tables with all possible types of information for both desktop and mobile
- [x] Meet and share with Jennifer Strickland to include any notes on how tables can be more accessible (1 hour meeting)
- [x] Share with the team

## Acceptance Criteria
- [x] The mockup/prototype has been updated and shared with the team
