### ISSUE TITLE
Create Initial Prototype for VRE (CH31)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9046]
## Goal
Based on existing product documentation, high level thumbnail workflows, and our experience with PCPG (CH36) work, we need to start thinking about how the VRE (CH31) workflows will look on regular screens.

## Tasks
- [ ] Build out the necessary screens for VRE (CH31) in UXPin that show its first happy path based on an authenticated Veteran
- [ ] If able, build out the remaining screens for other log in states, users.

## Acceptance Criteria
- [ ] A prototype has been created and shared with the team.

**Comment by sporeboy** [comment]
Initial CH31/28-1900 prototype here: https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526674

**Comment by sporeboy** [comment]
Some content refinement required... Also need to resolve expanding expansion on address block. Landing page is all FPO content.
