### ISSUE TITLE
QA - Personal Discovery

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#90469]
## Summary

I am not familiar enough we the QA Dashboard initiative and current QA Standards and Practices from the FE/Product perspective.

## Tasks

- [ ] Review [Initiative Proposal: QA Dashboards](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3229581313/Initiative+Proposal+QA+Dashboards)
- [ ] Review existing QA Standards
- [ ] Review existing QA Practices 

## Acceptance Criteria 

- [ ] A document defining existing QA Standards and Practices

_Edit:_ There isn't a separation between BE/FE/Product so one document will suffice for acceptance criteria instead of three.

**Comment by stevenjcumming** [comment]
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3377463302/Defining+QA+Standards
