### ISSUE TITLE
Create Initial Prototype for "View my VA representative"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9047]
## Goal
Based on existing product documentation, high-level thumbnail workflows, and our experience with other VA Search work, we need to start thinking about how Search workflows will look on regular screens for "View and update my VA representative."

## Tasks
- [x] Build out the necessary screens for Representative search that show its first happy path based on an authenticated Veteran
- [x] Build out the remaining screens for other log in states, users.

## Acceptance Criteria
- [ ] An initial prototype has been created and shared with the team.

**Comment by sporeboy** [comment]
Initial click-through available here: https://preview.uxpin.com/00985ac7bf2e8454786086efbf1c89de82d5cb3c#/pages/127894496

Included:
- Mock landing screen with FPO content
- View Rep tool with initial content
- View Rep loading, error and no-rep states
- Mock intro screen for 21-22/22a

Advance through the states using the left/right arrows.
