### ISSUE TITLE
Missing Urgent Community Care providers 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9049]
## User Story or Problem Statement
As a Veteran, I need to see all relevant results for my urgent community care search so that I can select the best location. 

## Situation: 
Victoria, TX 77904
Multiple Nextcare urgent care facilities, only show one address in Victoria, Texas (3002 Sam Houston Drive)

PPMS shows another location on Twin Fountains Drive which is not returned: 

![image](https://user-images.githubusercontent.com/55411834/81839265-8c088d80-9504-11ea-8982-8f4ad7c24d33.png)

![image](https://user-images.githubusercontent.com/55411834/81839433-bbb79580-9504-11ea-9796-bde56c4d9b50.png)

## Goal
Return all possible results meeting the search criteria

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Facilities/providers with the same name (Walgreen's) will be returned as unique locations, even with similar addresses.
- [ ] Different facilities with the same address are returned as unique locations. 
- [ ] All locations meeting the search criteria will be returned 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
Query for 20

https://dws.ppms.va.gov/v1.0/PlaceOfServiceLocator?address=77904&radius=50&driveTime=80&posCodes=20&network=0&maxResults=11


`{
  "@odata.context": "https://dws.ppms.va.gov/v1.0/$metadata#Collection(PpmsDataWebService.Models.ProviderLocatorResult)",
  "value": [
    {
      "Miles": 2.244,
      "Minutes": 8.15,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "3002 Sam Houston Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "3002 Sam Houston Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615785730",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.838918,
      "Longitude": -96.991917
    },
    {
      "Miles": 2.244,
      "Minutes": 8.15,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "3002 Sam Houston Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "3002 Sam Houston Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615785730",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.838918,
      "Longitude": -96.991917
    },
    {
      "Miles": 2.244,
      "Minutes": 8.15,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "3002 Sam Houston Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "3002 Sam Houston Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615785730",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - Choice",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.838918,
      "Longitude": -96.991917
    },
    {
      "Miles": 2.244,
      "Minutes": 8.15,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "3002 Sam Houston Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "3002 Sam Houston Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615785730",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "CCN Region 4",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.838918,
      "Longitude": -96.991917
    },
    {
      "Miles": 2.244,
      "Minutes": 8.15,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "3002 Sam Houston Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "3002 Sam Houston Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615785730",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.838918,
      "Longitude": -96.991917
    },
    {
      "Miles": 3.035,
      "Minutes": 8.033,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "108 Twin Fountains Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "108 Twin Fountains Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615783363",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.854649,
      "Longitude": -97.023664
    },
    {
      "Miles": 3.035,
      "Minutes": 8.033,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "108 Twin Fountains Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "108 Twin Fountains Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615783363",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.854649,
      "Longitude": -97.023664
    },
    {
      "Miles": 3.035,
      "Minutes": 8.033,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Urgent Care",
      "CareSiteAddress": "108 Twin Fountains Dr Victoria, TX 77904",
      "CareSiteAddressStreet": "108 Twin Fountains Dr",
      "CareSiteAddressCity": "Victoria",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77904",
      "CareSitePhoneNumber": "3615783363",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.854649,
      "Longitude": -97.023664
    },
    {
      "Miles": 34.41,
      "Minutes": 42.317,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Ugent Care",
      "CareSiteAddress": "603 State Highway 35 S Port Lavaca, TX 77979",
      "CareSiteAddressStreet": "603 State Highway 35 S",
      "CareSiteAddressCity": "Port Lavaca",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77979",
      "CareSitePhoneNumber": "3615536400",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.62165,
      "Longitude": -96.63914
    },
    {
      "Miles": 34.41,
      "Minutes": 42.317,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Ugent Care",
      "CareSiteAddress": "603 State Highway 35 S Port Lavaca, TX 77979",
      "CareSiteAddressStreet": "603 State Highway 35 S",
      "CareSiteAddressCity": "Port Lavaca",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77979",
      "CareSitePhoneNumber": "3615536400",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - PC3",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.62165,
      "Longitude": -96.63914
    },
    {
      "Miles": 34.41,
      "Minutes": 42.317,
      "ProviderName": "UCP Physicians of Central Texas PLLC",
      "ProviderSpecialty": "Clinic/Center - Urgent Care",
      "SpecialtyCode": "261QU0200X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "HPP": "Unknown",
      "CareSite": "NextCare Ugent Care",
      "CareSiteAddress": "603 State Highway 35 S Port Lavaca, TX 77979",
      "CareSiteAddressStreet": "603 State Highway 35 S",
      "CareSiteAddressCity": "Port Lavaca",
      "CareSiteAddressState": "TX",
      "CareSiteAddressZipCode": "77979",
      "CareSitePhoneNumber": "3615536400",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "TriWest - Choice",
      "NetworkId": null,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1922289412",
      "Latitude": 28.62165,
      "Longitude": -96.63914
    }
  ]
}
`

**Comment by mmiddaugh** [comment]
**Root cause:** "unique identifiers" are not truly unique. In the set tested, there were 14 locations with only 4 unique identifiers. 
- We return the first result among multiple locations with shared ID. 
- Detail pages are impacted because the additional detail is requested based on the identifier. 
- Lack of a unique identifier means we cannot anticipate which set of details will be returned for the ID sent.
**Decision:** Lance will remove ID or assign different ID for place of service locator results (impacting community urgent care locations only). 
- Community urgent care locations do not have detail pages so there is not a need to suppress detail pages. 
**Future:** Consider suppressing all community care detail pages.
