### ISSUE TITLE
[CDP] Updated diary codes in figma and in production

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#90499]
## Description

Follow on ticket from #80146 based on Bob's feedback spreadsheet. 

Given: A veteran views an overpayment in the debt portal
When: They look at a specific debt and see a status
Then: They should be able to see the correct stats (info or warning) based on SME feedback from Bob

## Tasks
- [x] Update diary codes in Figma with the right icon (info or warning) on the summary and detail pages
- [x] Update codebase with correct icons and alerts

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [x] Icons and alerts have been updated in Figma 
- [x] Diary and status code icons and alert statuses have been updated in production 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
[Figma diary codes have been updated](https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=0-10321&t=6XdTI47KX5kPRdjr-11).
