### ISSUE TITLE
[CDP] VHA - One-thing-per-page/ Balance prototypes (3 of 3)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#90506]
## Description

VHA (Copay) section should, for the most part, match VBA (Overpayment) section in Debt Portal in regards to IA. Since we are breaking up pages on VBA we should create mockups for the VHA (Copay) Section

## Tasks
- [x] Create a Codepen prototype 
## Acceptance criteria

- [x] Prototype has been created
- [x] Prototype has been QA'd

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
This will roll over as we need further information from SMEs in order to refine our mock ups before moving forward with a prototype.

**Comment by mgleo** [comment]
Prototype link: https://codepen.io/team/Debt-Team/live/yLddmpm
