### ISSUE TITLE
Conduct a research conversation with IIR team

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#90507]
# Description
Given the IIR team's specific work arounds, documentation, and extensive experience testing products from a `vets-api` context, we will conduct a research session with the IIR team in order to document their insights and inform our solutioning effort for local test environment consistency. We will aim to discover deficiencies, desired features, and pitfalls encountered by the team. Research data will be documented in Confluence, and analysis will be synthesized from the raw research data.

## Tasks
- [x] Work with IIR team to schedule a meeting with key team members
- [x] Conduct the research meeting
- [x] Record research data
- [x] Analyze data and produce a synthesis document

## Acceptance Criteria
- [x] Research session data is available in Confluence
- [ ] Research analysis is available in Confluence

**Comment by pjhill** [comment]
I've added key take aways to the notes document --
https://vfs.atlassian.net/wiki/spaces/PRT/pages/3387064321/Testing+Consistency+Conversation+with+IIR+Team
