### ISSUE TITLE
Conduct discussion with PRT SMEs regarding `vets-api` test consistency

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#90508]
# Description
In order to get a better understanding of the current `vets-api` local vs. CI testing experience, we will conduct a discussion with back-end engineers working with the Platform Reliability Team. Discussion should include deficiencies in local testing of `vets-api`, desired features in the local testing environment, key discrepancies between test execution locally vs. in the CI pipeline, and pitfalls associated with `vets-api` testing.

## Tasks
- [x] Recruit PRT team members for discussion
- [x] Conduct a research meeting with team members
- [x] Record and synthesize research notes

## Acceptance Criteria
- [x] Platform Reliability Team backend subject matter experts' research notes have been recorded in Confluence
- [ ] Research analysis and synthesiis is available in Confluence

**Comment by IGallupSoCo** [comment]
On a semi-related note, Ben noted that the Platform has the resources to provide users like me (who run into frustrating hardware limitations) with a virtual machine that would have far more processing power available to perform "local" testing.

**Comment by IGallupSoCo** [comment]
There are gems like [TestProf](https://test-prof.evilmartians.io/) that would have the potential to further streamline local testing.  GitLab reportedly reduced their API test timeline by 39%.  Ryan has a [ticket](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/83501) in the backlog to explore such solutions.

**Comment by IGallupSoCo** [comment]
My discovery and research notes can be found [here](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3382312971/Discovery+vets-api+local+testing+consistency+with+PRT+SME+input).
