### ISSUE TITLE
[CDP] Design component to show/hide sensitive information

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#90513]
## Description

Design a component in Figma to show/hide sensitive information such as a SSN number.

## Tasks
- [ ] Design component in Figma
- [ ] Meet with Platform during Office hours to discuss
- [ ] Review with the design team to track all display location
- [ ] Create a FE implementation ticket
## Acceptance criteria
- [ ] Component has been created in Figma
- [ ] Component has been discussed during Office hours
- [ ] FE implementation ticket created

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
Relevant article from Nielsen Norman Group:
https://www.nngroup.com/articles/stop-password-masking/

**Comment by dhill802** [comment]
Will look for guidance from design office hours.

**Comment by mgleo** [comment]
@dhill802 @Tom-Davis Closing this ticket as this is not a security concern. Displaying this information is only a concern if it displayed within a "page title tag, breadcrumbs, or contained in any other link text".
