### ISSUE TITLE
[VETS-API] Reduce impact of Mobile::V0::DecisionLettersController#index latency on Puma backlog

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#90529]
## Issue Description
While investigating the increase in the puma backlog, specifically within the `vets-api-appeals` bulkhead, It was determined that the `Mobile::V0::DecisionLettersController#index` resource/controller action is hogging a bunch of threads unnecessarily with higher-than-average latency (p95 ~4-6s) up to 20s

More info:
* [Mobile::V0::DecisionLettersController#index](https://vagov.ddog-gov.com/apm/resource/mobile-app/rack.request/237e8e0e809249b4?query=env%3Aeks-prod%20operation_name%3Arack.request%20resource_name%3A%22Mobile%3A%3AV0%3A%3ADecisionLettersController%23index%22%20service%3Amobile-app&env=eks-prod&fromUser=false&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1723502288329&end=1723505888329&paused=false)

<img width="838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efad161379d5fb34628c4b0a0131ae0839b6a662/image.png" alt="image.png" />

<img width="832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--596e63a95fffa1b15073de1dc8b64b15e9f5db51/image.png" alt="image.png" />

---
## Tasks
- [ ] Step 1 - move resource to a new "long timeout" bulkhead 
- [ ] Step 2 - Work with team to rework solution (This may involve abstracting request to a sidekiq job and creating a new action to check the status)

## Acceptance Criteria
- [ ] Resource has been moved to a new bulkhead, and is working properly in production
- [ ] A conversation has been started with respective team and the ticket/status is documented in the [confluence doc](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3363766282/Investigate+Puma+Backlog)
