### ISSUE TITLE
Implement GA Event name for the Veteran Info Review Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9053]
## Goal
When the VA File Number gating loads at the beginning of the 686c there is an API call made that checks if the user has a VA File Number or not. We need to add a GA event in that API call on the front end so that we can record if a VA File Number was successfully loaded or not.

## Considerations
- Backend needs to set up the API endpoint for this page but we can set up the GA events on the front end before they finish setting up the API endpoint.
- Take note of status of #9518 so that merge conflicts are minimized

## Tasks
- [ ] Work with Jon W on getting GA event names -> [results](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7560#issuecomment-642617014)
- [ ] Add the GA events into the Redux code for the API call
- [ ] Test the GA events

## Acceptance Criteria
- [x] Events are accurately firing for the API call
