### ISSUE TITLE
[VETS-API] Reduce impact of V0::ClaimLettersController#index latency on Puma backlog

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#90532]
## Issue Description
While investigating the increase in the puma backlog, specifically within the `vets-api-appeals` bulkhead, It was determined that the `V0::ClaimLettersController#index` resource/controller action is hogging a bunch of threads unnecessarily with higher-than-average latency (p95 ~4-7s) up to 40s

More info:
* [V0::ClaimLettersController#index Resource](https://vagov.ddog-gov.com/apm/resource/claim-status/rack.request/14092b087d04e426?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Aclaim-status&env=eks-prod&fromUser=false&sort_by=%40duration&sort_order=desc&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1720916387537&end=1723508387537&paused=false)
* Many of the errors are due to a `CipherError`. This could be worth looking into.

<img width="845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77132d8184c236ceb870f00a9e47192e9b15e0a0/image.png" alt="image.png" />

<img width="977" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTlQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ae57c52d8e1a273da0ac6503d4e80be3521a0b6/image.png" alt="image.png" />

---
## Tasks
- [ ] Step 1 - move resource to a new "long timeout" bulkhead 
- [ ] Step 2 - Work with team to rework solution (This may involve abstracting request to a sidekiq job and creating a new action to check the status)

## Acceptance Criteria
- [ ] Resource has been moved to a new bulkhead, and is working properly in production
- [ ] A conversation has been started with respective team and the ticket/status is documented in the [confluence doc](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3363766282/Investigate+Puma+Backlog)
