### ISSUE TITLE
[VETS-API] Reduce impact of V0::Profile::PaymentHistoryController#index latency on Puma backlog

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#90534]
## Issue Description
While investigating the increase in the puma backlog, specifically within the `vets-api-web-bgs-evss` bulkhead, It was determined that the `V0::Profile::PaymentHistoryController#index` resource/controller action is hogging a bunch of threads unnecessarily with higher-than-average latency (p95 ~4s) up to 60s

More info:
* [V0::Profile::PaymentHistoryController#index Resource](https://vagov.ddog-gov.com/apm/resource/payment-history/rack.request/6ca31712f89b7ddc?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Apayment-history&env=eks-prod&fromUser=false&sort_by=%40duration&sort_order=desc&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&start=1722905130039&end=1723509930039&paused=false)

<img width="835" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a38c21cb7f65e157c3017049590cd58a5ebb511b/image.png" alt="image.png" />

<img width="936" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d1c10a76c9fb708f511f6ff5fc3bcf714bf83fd/image.png" alt="image.png" />

---
## Tasks
- [ ] Step 1 - move resource to a new "long timeout" bulkhead 
- [ ] Step 2 - Work with team to rework solution (This may involve abstracting request to a sidekiq job and creating a new action to check the status)

## Acceptance Criteria
- [ ] Resource has been moved to a new bulkhead, and is working properly in production
- [ ] A conversation has been started with respective team and the ticket/status is documented in the [confluence doc](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3363766282/Investigate+Puma+Backlog)
