### ISSUE TITLE
Audit: Partner Services (Upstream Services) page

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90535]
## Issue Description
The document, [Partner Services (Upstream Services)](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1885601877/Partner+Services+Upstream+Services), contains many broken links as well as link emojis instead of proper link formatting. The page needs a thorough audit and is presently of limited use to VFS Teams.

Results of the audit are:

- Links should not be represented by a chain link emoji.
- 14 of those links are broken or problematic as of August 28 2024. Here are the broken or bad links as of Aug 28. The list shows where in the grid each link is :

1. MPI- outage- This link leads to a GitHub page that says “File not Found”
2. MPI-Contacts - This link leads to a GitHub page that says “File not Found”
3. MPI - monitoring- This link leads to a page that says "server not found".
4. Appeals-outage- This link leads to a page that says "server not found".
5. Appeals-Monitoring - This link leads to a page that "says server not found". 
6. VA profile - contacts - This link leads to a confluence document in drafts, which VFS team members can’t access.
7. EVSS- monitoring- Server not found
8. EWIS - monitoring- Server not found
9. Central mail - monitoring- server not found
10. Central Mail - VFT docs- This leads to a Platform document that technically exists but says at the top “This API has been deprecated. Please use the Benefits Intake API.”
11. MHV - monitoring- server not found
12. Search.gov- monitoring- server not found
13. eMIS - VFT docs- This leads to a Platform document that technically exists but says at the top “THIS PAGE WAS ARCHIVED ON 2/15/24 - Loki, Grafana, and Prometheus have been sunsetted and replaced by Datadog. This page contains only information about affected programs and DOES NOT contain any additional information that people need. As a result, this page was not edited and kept on the Platform Website. Instead, it was archived. For more information about Datadog, contact #dots-dsva.”
14. eMIS - devops docs- This also leads to that Platform document page that technically exists but that says at the top, “THIS PAGE WAS ARCHIVED ON 2/15/24 - Loki, Grafana, and Prometheus have been sunsetted and replaced by Datadog. This page contains only information about affected programs and DOES NOT contain any additional information that people need. As a result, this page was not edited and kept on the Platform Website. Instead, it was archived. For more information about Datadog, contact #dots-dsva.”

---
## Tasks

- [X] Audit the page for issues
- [X] List the issues and details 
- [X] Decide whether to create edit tickets for the work or archive the page

## People/SMEs

- Jennifer Brown and Platform Product team

## Slack thread
See [this slack thread](https://dsva.slack.com/archives/CL181NRJQ/p1724865276408069).

## Acceptance Criteria
- [X] Audit of page is complete

**Comment by jknipes** [comment]
@taylojill just FYI, in case we can fold this into the work for 88359 during Sprint 8

**Comment by jknipes** [comment]
Bringing this ticket into the current sprint to account for the work completed, and setting the stage for the next part of this project: editing the page.

**Comment by jknipes** [comment]
Audit is complete, moving to _Closed_
