### ISSUE TITLE
Document a plan to get some level of quality control in place prior to pushing CD for everyone

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#90549]
## Description
As we plan to move the remainder of the apps to continuous deployment that do not already take advantage of it, we need to devise a plan to do it in the most safe, secure way possible. Some level of quality control will be necessary to ensure that the veterans using va.gov continue to receive a great experience. Continuous deployment opens the door for poor quality code to go out the door with little testing being mandatory outside of automated testing.

## Tasks

- [x] Review automated testing current implementation to determine if coverage is comprehensive enough. Come up with any improvements necessary
- [x] Write up implementation plan for implementing quality control checks in the CI pipeline to protect us as we move to CD.
- [x] Socialize written plan to Clint for final review
- [x] Send written plan to Jeff Keene for approval

## Acceptance Criteria
- [x] A plan is documented for moving vets-website apps to CD
- [x] The plan has been socialized to all appropriate parties.
