### ISSUE TITLE
[FSR] Update documentation for GMT year update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#90545]
## Description
This is a follow on ticket to **[FSR] Update GMT year for 2024 [#88120](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88120)** Generate documentation for the process of updating the GMT year for FSR streamlined waiver process. 

Let's start with a copy of the doc(s) in the team folder here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end 

## Tasks
- [ ] Coordinate with stakeholders and downstream services to establish order of operations to update GMT year
- [x] Document relevant files and list of points of contact for updating GMT year
- [x] Link documentation to new year ticket for visibility 
   - **[FSR] Update GMT year for 2025 [#88119](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/88119)** 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required

## Acceptance criteria
- [x] Documentation is complete for updating GMT year

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
N/A
---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
</details>

**Comment by Dr-Pongo** [comment]
New document!
**[GMT yearly update](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/benefits-memorials-2/engineering/front-end/GMT%20yearly%20update.md)**

**Comment by Dr-Pongo** [comment]
Initial set of docs complete! Updated after some feedback, and waiting to close out until @denisecoveyduc has a few minutes to give it a once over.

**Comment by denisecoveyduc** [comment]
@Dr-Pongo sorry for the delay. This is fantastic! I made a few small changes but nothing significant.  We should make a note on the 2025 ticket to review this write up and if needed update for accuracy at that time.
