### ISSUE TITLE
[CDP] Feature Flag Cleanup

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#90559]
## Issue Description
After some recent testing updates, we've identified some unused feature flags that can probably be removed. Some of them were app specific when copays and debts were separated, so they can likely be removed now they are no longer being used. 

- `debt_letters_show_letters` aka `debtLettersShowLetters` 
- `show_medical_copays` aka `mcpFeatureToggle` & `showMedicalCopays` 
- `medical_copays_html_medical_statements_view_enabled` aka `medicalCopaysHtmlMedicalStatementsViewEnabled` & `mcpHTMLStatementToggle`

Most of these references can still be found in the combined helpers file:
- `src/applications/combined-debt-portal/combined/utils/helpers.js` 

## Tasks
- [x] Check for any other unused feature flag not listed here
- [x] Review feature flags to ensure they are no longer being used in our application.
- [x] Remove unused feature toggles from CDP
- [x] Coordinate with BE to confirm they no longer need the flags before moving to the next step
- [x] Remove feature toggles from feature list if there are no other applications that use them 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] No more unused feature flags rolling around in the CDP

## Testing
- [x] Confirm flag removal won't effect other applications
- [x] Confirm relevant tests are still passing

Test procedures:      
N/A

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
OO now this one is spicey, found a reference to `show_medical_copays` in [a static page definition](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/medical-copays-cta/components/App/index.js). This is likely completely deprecated because of the new combined debt portal , but it'll be good to follow up and get this removed if we no longer need it.
