### ISSUE TITLE
Add Sentry Alerts for When VA File Number is Null

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9055]
## Description
We would very much like to know when a VA file number is not found so we can try and help with that but we want to be careful with the personal information aspect.

## Tasks
- [x] Establish PII requirements in using Sentry
- [x] Add code that reports missing VA File number to Sentry

## Acceptance Criteria
- [x] The changes have been updated and a PR has been requested for merging

**Comment by annaswims** [comment]
[PII guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/pii-guidelines.md)

**Comment by digitaldrk** [comment]
Since this PR is still waiting, I thought it would be a good idea to add the code to it for this task.

https://github.com/department-of-veterans-affairs/vets-api/pull/4331
