### ISSUE TITLE
SC | update prototype to match design

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#90568]
## Value Statement

**_As a_** researcher
**_I want to_** be able to test our form changes with AT-users
**_So that_** we can identify possible points of friction *within* the form

---

## Background Context

Now that the Supplemental Claim prototype has been set up, we need to update the internal content to match the design.

## Outcome, Success Measure, KPI(S), and Tracking Link

- Add here

## Acceptance Criteria

- [ ] Update form and add new pages
- [ ] Ensure the prototype is usable as an unauthenticated user
- [ ] Verify prototype matches design

## Designs and Build Notes

- [Design](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1158-32895&t=lBuKA2NuJ2NkegI9-0)
- [Create SC prototype](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89715) (completed)

### Enablement team (if needed)
@ member of team

## Out of scope

- Don't add unit/e2e tests for this prototype

## Open questions

- Add here

## Tasks

- [ ] Update form introduction
- [ ] Add mock ITF, Veteran info & contact info pages (unauthenticated)
- [ ] Add housing risk
- [ ] Add living situation pages
- [ ] Add point of contact page
- [ ] Add VHA notifications page
- [ ] Add facilities types page
- [ ] Update VA/military treatment location page
- [ ] Update review & submit page as needed

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
PRs ready for code review

**Comment by dfong-adh** [comment]
One more PR to merge, then ready for staging validation

**Comment by Mottie** [comment]
All changes are now available in staging for testing: https://staging.va.gov/decision-reviews/test-sc

**Comment by dfong-adh** [comment]
Needs staging validation then this ticket can be closed

**Comment by eileen-coforma** [comment]
<img width="611" alt="Screenshot 2024-08-23 at 4 54 44 PM" src="https://github.com/user-attachments/assets/c1c83384-54df-47b1-a5fa-7c138eedaead">

The issue description for headaches is wrong. Also, this is my fault, but can you remove tinnitus. There shouldn't be an issue that's pre-added.

@Mottie 

One other major thing. How do we clear the information from the form, so that if they're not logging in, it's not cached data? I tried hard-refreshing, but the previous selections remained.

**Comment by eileen-coforma** [comment]
<img width="732" alt="Screenshot 2024-08-23 at 5 15 37 PM" src="https://github.com/user-attachments/assets/41777e50-834e-46a0-8333-2faf5303c8bf">

Funky behavior with the accordion errors. It shows the section error, but the icon is separate?

**Comment by eileen-coforma** [comment]
<img width="529" alt="Screenshot 2024-08-23 at 5 17 27 PM" src="https://github.com/user-attachments/assets/61231ca4-894b-4b57-b9df-db6d8bca8212">

Weird gap between question and radio options

**Comment by dfong-adh** [comment]
Robin to start working on this today

**Comment by Mottie** [comment]
> The issue description for headaches is wrong. Also, this is my fault, but can you remove tinnitus. There shouldn't be an issue that's pre-added.

There isn't any consistency between the issues on the issues page, review & submit page and [overall flow page](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=1394-21883&t=MlgF4VmzlXs19naL-0), so I went with the overall flow. This page has Tinnitus and Headaches as the issues.

> How do we clear the information from the form

We can't the way the prototype is now. It can either be completely blank, or prefilled without however much data you want. I have it completely filled out for testing, but we can easily change that.

> Funky behavior with the accordion errors

Platform code issue, which I will look into

> Weird gap between question and radio options

Web component issue that the [Design System team has already fixed](https://dsva.slack.com/archives/C01DBGX4P45/p1724450881182959?thread_ts=1724445319.663739&cid=C01DBGX4P45)!

**Comment by Mottie** [comment]
I also wanted to point out that the contact info edit links don't work

**Comment by dfong-adh** [comment]
Fixes have been merged - Robin to check with Eileen once she's back regarding clearing out all form values

**Comment by Mottie** [comment]
Changes are now available in staging

**Comment by eileen-coforma** [comment]
Looks good 👍

**Comment by eileen-coforma** [comment]
Re-opened to fix 2 bugs found in the prototype

**Comment by eileen-coforma** [comment]
@Mottie  Fix typo CBOC on evidence location screen, use start link instead of button and text link for beginning prototype

**Comment by Mottie** [comment]
Fixes merged in, and will be available in staging soon

**Comment by Mottie** [comment]
All Supplemental Claim prototype changes have been merged in, please validate in staging

**Comment by eileen-coforma** [comment]
LGTM
