### ISSUE TITLE
[FE] Profile Name Tag and H1 Updates - Desktop and Mobile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#9059]
## Background
See ticket: [Design] Create mocks for new mobile view (name tag) #8231

Change navigation from 'Profile' to 'Your profile' and implement this text as H1.

## Tasks
- [ ] Build updated profile name tag

## Acceptance Criteria
- [ ] Name tag has been built 
- [ ] H1 has been implemented into the side nav
- [ ] Name tag and side nav have been reviewed by Tressa

**Comment by mshea0606** [comment]
@tressaellen please add screenshot

**Comment by sanlouise** [comment]
@mshea0606 This ticket is ready for validation whenever you have a moment :)
