### ISSUE TITLE
Add Content + Links to Public Slack Channel CANVAS

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90590]
## Issue Description
We should add important links and info that can be used by VFS Teams (Platform Teams) to our Canvas in the **#platform-content** channel in Slack.
Other teams are doing this and it would be good for Content Team to have similar

---
## Tasks
- [ ] Discuss with the team what content belongs in our Slack channel Canvas
- [ ] 
## Acceptance Criteria
- [ ] All tasks have been completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90590?planning-poker) with Zenhub @BSmolensky @cmarion93 @taylojill

**Comment by jknipes** [comment]
Closing as _Done_
