### ISSUE TITLE
Testing VBA transaction history in production (canary testing)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#90604]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Canary testing with at least 2 SMEs that have a VA.gov login and can help us:

1) Confirm that the VBA payment history MVP designs are displaying correctly
2) Match what they are seeing with what DMC is seeing in the system

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [x] _ Session 1_ (8/20/24)
- [x] _ Session 2_ (8/28/24)

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [x] Confirmation that the designs and content are displaying correctly
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlottecesana** [comment]
I will close this ticket on Wednesday 8/28 (a day after the end of the sprint) after we have our final canary test. 
cc: @HeatherRienks @Tom-Davis

**Comment by josephrlee** [comment]
We had two successful tests; everything is looking correct! I am going to mark this as closed now!

cc: @charlottecesana @mgleo @Tom-Davis @denisecoveyduc
