### ISSUE TITLE
Create V3::ProfileInformation Service (dupe 4)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#90618]
This is a dupe ticket of [89718](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/89718), for Sprint 8 to complete the work. 

## User Story
As the developers responsible for backend work on the EVSS PCIU migration,
We want to create the V3::ProfileInformation Services configuration and responses,
So that we can perform the necessary migration of PCIU from the current EVSS environment.

## Issue Description
In this ticket, the objective is to create the V3::ProfileInformation Service's configuration and responses.

## Tasks
- [x]  Configure V3::Profileinformation service
- [x]  Configure V3::Profileinformation response (try to add duplicate methods used from other services in this response, if you can)
- [x]  Configure V3::Profileinformation's configuration
- [x]  Configure V3::Profileinformation redis

## Success Metrics
- [ ]  V3::Profileinformation service environment is created and configured
- [ ]  V3::Profileinformation response environment is created and configured (try to add duplicate methods used from other services in this response, if you can)
- [ ]  V3::Profileinformation's configuration environment is created and configured
- [ ]  V3::Profileinformation redis environment is created and configured

## Acceptance Criteria
- [ ] The V3::ProfileInformation service is configured, readying the next steps for PCIU migration. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
8/19. update: @RachalCassity met with Tom on Friday 8/16, after the PR was reviewed by their team. Apparently the vision has changed; there is a read and a write service now and these are going to be combined as a part of the code organization. After these PRs are updated, Tom's team will be taking on more of this work. Rachal copied the code from V1 to V2.

**Comment by jennb33** [comment]
8/22 updates: per @RachalCassity the tests are passing locally and they take a while to execute. They are not passing otherwise. She has had to update the branch frequently. Tom is ready to do the testing, and he and Rachal are going to create a test plan (perhaps)

**Comment by jennb33** [comment]
8/28 update: @RachalCassity has completed and pushed this work.
