### ISSUE TITLE
Investigate if user needs to complete both home/mobile numbers, before selecting their "primary" number

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#90617]
## Background
Do users need both home/mobile numbers on their profile before proceeding to select a primary number?  The [VA Form 20-0995](https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995) has this experience ([screenshots](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707507504743/416bbf09f639569b08eda27e932984dd50ba02bc?wid=0-1723491763340)), but we currently feel like that's uncessary.

UX points: If only one number exists, just use the one number as the primary (why force users to complete two number if we only need the one) but curious about technical implications.

## Tasks
- [ ] Take a look at VA Form 20-0995 code to see if there are any technical gains of requiring users to have both home/mobile number on file
- [ ] Share findings with the team

## Acceptance Criteria
- [ ] Design has guidance on if we need to require both home/mobile numbers before proceeding to select a primary number

**Comment by cosu419** [comment]
It looks like the forms library would allow us to conditionally display either number for users with one or two. We can set that as the default primary number for this group of users, while conditionally displaying the "primary" page for users who have both.

**Comment by oddball-lindsay** [comment]
Adding that there is the option to include "Work" number -- really anything in Profile can be included in the prefill pattern, it's just that other teams deemed this particular number to be irrelevant to their forms so they do not include it in the prefill pattern.

Slack discussion: https://dsva.slack.com/archives/C044AGZFG2W/p1723734000877639
