### ISSUE TITLE
Appoint ask users to select their "primary" number

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#90623]
## Background
We have determined that users need to indicate which number is their primary number, since Profile may have multiple numbers but our forms only accept one number.

There was an open question (https://github.com/department-of-veterans-affairs/va.gov-team/issues/90617) -- do we first need users to complete both home and mobile numbers before specifying a primary number?  Or if there's only one number on file, can we simply call that the Primary number?

Answer: 
- If there's only one phone number, we can simply surface that as the primary number and the user can confirm.
- If there are multiple phone numbers, then we will need to ask which of these is the "primary".  We could pull from the [20-0995 experience](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707507504743/416bbf09f639569b08eda27e932984dd50ba02bc?wid=0-1723491783230) where first the user confirms any/all phone numbers on file, then selects their primary.
  
## Tasks
- [x] Await guidance from Colin
- [x] Design according to guidance from Colin's findings

## Acceptance Criteria
- [x] We have designs for a user to select their primary phone number

**Comment by oddball-lindsay** [comment]
Removing "MVP" from this ticket since we have decided to explore the prefill pattern after MVP.  And left a note in the description around Colin's findings for the 20-0995 experience.

**Comment by mtri** [comment]
This has been added into the v2 designs.
[Mobile](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4521-225930&node-type=frame&t=DDENUzowx8xXBqQV-11)
[Desktop](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10209-402524&node-type=frame&t=DDENUzowx8xXBqQV-11)
