### ISSUE TITLE
[UX][Research] Monitor Metrics for an Epic

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#90624]
## Tasks
- [ ] Decide on frequency to monitor the metrics for the Epic
- [ ] Monitor the metrics
- [ ] Present to the team

**Comment by outerpress** [comment]
@Dottifacilities I think this one is for you; if you need UX work for this let us know. FYI @StevenStraily

**Comment by Dottifacilities** [comment]
Thanks @outerpress!
