### ISSUE TITLE
Replace V2::ContactInformation with V3::ProfileInformation (dupe 1)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#90625]
This ticket is a duplicate of [83187](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/83187), for Sprint 8, to finish the work. The resource was assigned to support and wasn't able to complete the work.

## Summary
In this ticket, the objective is to replace all V2::ContactInformation requests with V3::ProfileInformation. This work has to be done behind a feature flipper for testing purposes.
Example:
`VAProfile::ContactInformation::Service.new(@current_user)`
to
`VAProfile::ProfileInformation::Service.new(@current_user)`

## Tasks
- [x] Create Feature Flipper
- [x] Replace V2::ContactInformation calls in Vets-API Controllers
- [x] Replace V2::ContactInformation calls in Vets-API Concerns
- [x] Replace V2::ContactInformation calls in Vets-API Models
- [x] Replace V2::ContactInformation calls in Vets-API Sidekiq Jobs
- [ ] Replace V2::ContactInformation calls in Vets-API Modules
- [x] Replace V2::ContactInformation calls in Vets-API Rake Tasks
- [x] Replace V2::ContactInformation calls in Vets-API Spec Tests
- [x] Add Rails logs to each method inside VAProfile::ContactInformation Service to ensure all requests have stopped before tearing down the service

## Acceptable Criteria
- [ ] Auth Experience Team completes testing

**Comment by jennb33** [comment]
8/26 update: @RachalCassity is currently re-recording the cassettes, and this is moving forward. She will update the Design docs and will link in ticket.
