### ISSUE TITLE
[Design] My VA Form Status: Update "60 day" language for accordion content

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#90639]
## Background
Not all draft forms expire after 60 days of inactivity. Our content for the "what if you can't find your application or form" accordion references a 60 day expiration so we need to update that statement.

## Tasks
- [x] Simplify the language and remove the 60 day reference
- [x] Update content in figma
- [x] Update content in [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/FE-documentation-MVP.md#expanded-state)

## Acceptance Criteria
- [x] Accordion content no longer references a 60 day expiration for draft forms

**Comment by mattmarino-adhoc** [comment]
The new content replacing the 60 day draft callout is:
"If you can’t find a draft application or form, it may have expired. We only save draft applications and forms for a limited time. This helps us protect your personal data. After a draft application or form expires, you’ll need to start over."

**Comment by mattmarino-adhoc** [comment]
@ajakabcin I'm closing this out but please take a look when you're back
