### ISSUE TITLE
[FE] 10-10CG - Form Updates: Update file upload error messaging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#90633]
## Benefit to the Veteran
As a Veteran, I want to see clear messaging on file upload alerts and errors, so that I can make decisions and adjustments to my attachment for a successful application.

## Background
Now that the July form updates have been released, we want to review content and make some adjustments to better align with VADS guidelines.
The changes included in this ticket are listed below.  Refer to [Figma design file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=2FrxXdW6Q7EbOvWb-0) for visual guidance.

1. "Check your upload" alert box should appear after the file is uploaded, not before.

### Resources
- [Figma file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=2FrxXdW6Q7EbOvWb-0)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683656893560/fccf821394d1cf693ad1c036e912e11a18ff88bd?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks
- [x] Update File Upload screen
- [x] Review with the team/PM to confirm expected design/behavior
     - PM Signoff required to be documented in comments below
- [x] Inform [QA/Teammate] when the next step can begin

## Acceptance Criteria
- 10-10CG File Upload screen is updated with the correct order of information to display

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`1010-team`)
- [x] **Labeled with Form** (`1010-ez`, `1010-ezr`, `1010-cg`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `ux`, `design`, `research`, `product`, `qa`, `1010-analytics`)
- [x] **Labeled with Project** (`facilities-cg`, `registration`,  `toxic-exposure`, etc.)
- [x] **Add Assignees** (who will do this work?)
- [x] **Add Estimate effort  (or `needs refinement` label)
- [x] **Add Dependencies 'blocked by' and 'blocking'** (link tickets in the Dependencies section below)

**Comment by hdjustice** [comment]
File upload pattern not yet available

**Comment by hdjustice** [comment]
created ticket #90735

**Comment by longmd** [comment]
@allanto-ah / @hdjustice  , this is ready for review [using this RI](http://8e125e530840a11365ef29b50a21c800.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg). I have validated its now functioning as intended.

| Before upload | After upload |
| -------------- | ------------ |
| ![Image](https://github.com/user-attachments/assets/a354e5c3-05fa-49ec-bb65-f8e152ea46e7) | ![Image](https://github.com/user-attachments/assets/849a4519-e615-4228-bb07-5d56ca8f8cc4) |

**Comment by hdjustice** [comment]
This looks good and is functioning as expected.  Thank you Matt!

**Comment by allanto-ah** [comment]
@hdjustice / @longmd 

I think we don't show alerts in the review and submit page correct? Currently there isn't any alert before or after file upload, but wanted to confirm.

![Image](https://github.com/user-attachments/assets/aa36066b-aced-4296-b301-73b46db09345)

**Comment by longmd** [comment]
@allanto-ah , that is correct. The functionality that controls the show/hide is disabled on the review page, if I remember right.

**Comment by allanto-ah** [comment]
Environment: RI

Verified that the alert appears after uploading a file and not before.
