### ISSUE TITLE
Single Claim View

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#90645]
## Description
_What details are necessary for understanding the specific work racked by this epic?_

Equivalent project JIRA issue: Issue Number [Link to JIRA]()

## High Level User Story
As a _____, I _____, so that _____.

## Success Metrics
- 

## Tasks
- [ ] 

### VSP Collaboration Cycle
- [ ] Project Kickoff
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging Review
- [ ] Privacy & Security Review
- [ ] Full Accessibility & 508 Audit

## Acceptance Criteria
- [ ] 

## Definition of Done
- [ ] 

---

**[Note:]** _Use below for top level initiative grouping. Delete if standard epic._ 

## Description

Equivalent project JIRA issue: Issue Number [Link to JIRA]()

_List out the epics in this initiative and planned release date for tracking purposes_
| Epic | Release Date | Status | 
| ------- | ---------- | ----- | 
| Epic [Link to feature epic]() | Month Year  |   | 
| Epic [Link to feature epic]() | Month Year  |   | 
| Epic [Link to feature epic]() | Month Year  |   | 
| Epic [Link to feature epic]() | Month Year  |   | 
| Epic [Link to feature epic]() | Month Year  |   | 

---
## How to configure this issue
- [ ] **Attached to an Initiative**
