### ISSUE TITLE
Design/Research | IES | Process flow

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#90655]
## Background 
Now that we've finished our IES desk research we should map out a process flow documenting the different systems and teams and people at play for generating an IES download. 

### Example of previous work 
- [ch33 example ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707938676024/48a9e34150b8a3058c8709b241373cb9515afee6?wid=0-1708028100709)

### Goals
Have an artifact that can serve as a discussion and discovery framework, and be built out as we learn from stakeholders, technical partners, and other sources. This will serve both to capture knowledge and generate insights.

## Tasks
- [x] build [canvas framework](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725569346643/fd28cd77f4dc39baa50f3aa752a85e7dc99b03fa?sender=u304c8d504aa1d0ae42659303)
- [x] enter User actions
- [x] work with BE to build out frontstage and backstage actors
- [ ] work with stakeholders to build out steps and interactions

## Acceptance Criteria 

- [ ] I'm envisioning at the end of this we'll have a process flow with a few different swim lanes and we've mapped out the different connections and pieces of the puzzle (it doesn't have to be in mural but it can be)

> [!NOTE]
> We are planning to have a readout in early/mid-September using desk research, user story mapping, process flow to VEO and Chris Johnson

**Comment by mtcA6** [comment]
@ACParker89 is this the one you're moving from the sprint?

**Comment by ACParker89** [comment]
@mtcA6 - we will move this to Sprint 44
@twoangstroms - we are planning to have a readout in mid-September using desk research, user story mapping, process flow to VEO and Chris Johnson

**Comment by twoangstroms** [comment]
After discussion with @tpharrison, this ticket is blocked by [90654](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90654). 90655 requires knowing what systems are involved and what teams manage them; 90654 is the best chance of learning some of this/

**Comment by mtcA6** [comment]
@twoangstroms did you start to create a template process flow without all the BE specifics?

**Comment by twoangstroms** [comment]
@mtcA6 I'm trying to collect and clean up some Mural templates, but what we discover will determine what kind of diagram we produce, of course.

**Comment by mtcA6** [comment]
oh cool, can you link to your draft?

**Comment by tpharrison** [comment]
@mtcA6 I think it might be best to hold off on creating a process template until we get more information on 9/4. After reviewing the documentation, it's unclear whether a PDF will be generated on the fly. If the PDF is generated upon request, my main concern is the response time. Any significant delay could impact the process flow. For instance, if there is a delay, we might need to implement asynchronous processing and notify the user when the document is ready (assuming it's a PDF). This would, of course, introduce additional complexity.

Given this uncertainty, I suggest we keep the artifacts minimal for now until we have more clarity. If things turn out to be simpler 🤞, we should still have enough time to create the necessary artifacts by the end of the sprint. On the other hand, if things are more complex, we'll have avoided the need to redo our work.

I've invited Dan to the meeting on 9/4.

**Comment by mtcA6** [comment]
I really think we should build what we can now and not wait for the call. I'm not saying go down the path of building out all the hypothetical options/permutation but for now we could have one sticky that says synchronous quick process or asynchronous slow process. And if our process flow stops there it stops there but mural is tricky and annoying to work in so I want us to put pen to paper to get the brain juices flowing. 

It would be great to go into that Wednesday call showing we've done our homework based on the two confluence pages they've linked us to. If we have something in hand to show them, they might say OH NOPE that's trash and not how it works and that's OK. That said, we already know at least the "option 2" Lisa gave us is likely the more fruitful option. 

Additionally they've said it takes ~5seconds to generate. Why do we think this wouldn't hold true?

**Comment by twoangstroms** [comment]
I don't know if that makes sense, at least from the information I have at hand? We don't know the actors and systems involved and how communications/information flows between them, especially in critical-to-map fail states. And I don't have access to those Confluence pages but am working on it (probably no response until Tuesday).

**Comment by twoangstroms** [comment]
I think if we have a solid documentation of questions, what we need to learn and how to go about learning it, and a plan (which Tom outlined and is working on presenting), we'll be able to demonstrate that we have been working on building understanding and a path to delivering clarity and artifacts in a stronger way, and a way that will require less backtracking or bothering other stakeholders.

**Comment by tpharrison** [comment]
@mtcA6 I probably should have provided a bit more context.  We are planning on going into the meeting with an outline of questions and high-level diagrams based on our current assumptions. I have spent some time preparing some notes, questions, and assumptions, and I just need a bit more time to finalize everything before sharing. We should be able to review what I have by Tuesday afternoon or Wednesday morning. This should give us a solid framework to build on and help generate additional questions. 

I was thinking a simple slide deck should be sufficient for now, so I recommended to Dan that we hold off on creating anything more substantial until after the meeting.

I can address your other questions when we meet next week.

**Comment by mtcA6** [comment]
I still think a process flow is needed and it might help us generate questions/concerns for our call tomorrow. Can copy paste from the work I had from Direct Deposit stuffs

**Comment by tpharrison** [comment]
@mtcA6 Agreed.  I think some basic flows can be mapped out (particularly around how the user navigates to the link to download the ILER report).

@twoangstroms For our meeting tomorrow, if you identify any design questions that might be influenced by technical constraints (apart from the sync/async options), please add them to the slides.  Let me know if you want to meet and discuss.

**Comment by ACParker89** [comment]
9/5- Based on learnings in the meeting on 9/4, creating a proposed flow with a possible solution for the missing API and user flow (basic, with knowledge of the potential for change) 

_Create a "canvas" for what our ideal state is_ 

1. Base FE user Flow 

> what are the needs for users to do this successfully 

> what happens if they do not have the needs above 

2. Base BE flow for proposed API 

CC: @tpharrison @twoangstroms @mtcA6

**Comment by twoangstroms** [comment]
Carrying over – making progress but uncovering unknowns

**Comment by mtcA6** [comment]
@twoangstroms [added this link ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725569346643/fd28cd77f4dc39baa50f3aa752a85e7dc99b03fa?sender=uaa72d11015d3f7c704a64191) as the output but please update it if that's not the correct file.

**Comment by twoangstroms** [comment]
@mtcA6 Spot on. I had the link to it in the Tasks.

Deleted the comments to clean up before sharing out.
