### ISSUE TITLE
How to restructure Zenhub for VSP Analytics & Insights

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9065]
## User Story or Problem Statement
As a VSP Analytics & Insights PM, I need to be able to see my team's sprint work in one view on Zenhub so I can quickly understand which work needs to be reprioritized, which work is done, and which work requires swarming.

## Goal
Determine a better way to organize our team's Zenhub board.

---
## Tasks
- [ ] List out pain points
- [ ] Brainstorm edits
- [ ] Discuss with the team & try out a new method, if any

## Acceptance Criteria
- [ ] We can better understand the team's sprint work

**Comment by joanneesteban** [comment]
Created an Analytics Customer Support Project Board. Closing this ticket.
