### ISSUE TITLE
[FE] 10-10CG - Form Updates: Update field error messaging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#90660]
## Benefit to the Veteran
As a Veteran, I want to see clear messaging on field errors, so that I can make decisions and adjustments to my input for a successful application.

## Background
Now that the July form updates have been released, we want to review content and make some adjustments to better align with VADS guidelines.
The changes included in this ticket are listed below (toggle to expand).  Refer to [Figma design file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2347-27136&t=2FrxXdW6Q7EbOvWb-0) for visual guidance.

1. All DOB - Update the DOB error message to reflect "1900 and 2024"
2. All DOB - Add a comma within the date example of the DOB Hint text
3. All SSN - Remove mention of “tax identification number” add number, dashes clarification
4. All Street address - Change error message
5. All City - Change error message
6. All State - Change error message
7. All Postal code - Change error message, add reference to "5- or 9- digit postal code"
8. Veteran County - Change error message
9. Facility State - Change error message
10. Facility - Change error message
11. Primary CG relationship - Change error message, update question from "What is" to "What's"
12. P CG Mailing address ("same as" question) - Change error message
13. Secondary CG relationship - Change error message, update question from "What is" to "What's"
14. Addt'l Secondary CG relationship - Change error message, update question from "What is" to "What's"
15. [TBD] Remove "Please" from all error messaging (TBD Matt Dingee consult)
16. [TBD] P CG Home & Mailing Street address - Update spacing
17. [TBD] Addt'l S CG Home address - Update spacing

### Resources
- [Figma file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2347-27136&t=2FrxXdW6Q7EbOvWb-0)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683656893560/fccf821394d1cf693ad1c036e912e11a18ff88bd?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks
- [ ] Update field error messages
- [ ] Review with the team/PM to confirm expected design/behavior
     - PM Signoff required to be documented in comments below
- [ ] Inform [QA/Teammate] when the next step can begin

## Acceptance Criteria
- 10-10CG field error messages are updated and align with VADS standards

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`1010-team`)
- [x] **Labeled with Form** (`1010-ez`, `1010-ezr`, `1010-cg`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `ux`, `design`, `research`, `product`, `qa`, `1010-analytics`)
- [x] **Labeled with Project** (`facilities-cg`, `registration`,  `toxic-exposure`, etc.)
- [ ] **Add Assignees** (who will do this work?)
- [x] **Add Estimate effort  (or `needs refinement` label)
- [ ] **Add Dependencies 'blocked by' and 'blocking'** (link tickets in the Dependencies section below)

**Comment by hdjustice** [comment]
Need to review list and identify those items that must be done through the forms library and discuss with Matt Dingee & team

**Comment by allanto-ah** [comment]
Environment: RI

Verified that the alert has been moved towards the top of the page instead of the bottom. No regression issues found

![Image](https://github.com/user-attachments/assets/7afe0788-2c38-48bf-83a4-284295b75c3c)
