### ISSUE TITLE
[NOD / SC] Evidence uploads with long filenames encounter tempfile error

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#90663]
## Value Statement

**_As a_** user

**_I want to_** to be able to upload evidence files with the correct filename length

**_So that_** my evidence upload doesn't fail when it's uploaded to Lighthouse

---

## Background Context

We have previously tried to [resolve an error related to evidence uploads with long file names](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75029) but it's popped up again — it seems to be related to the tempfile name as it also includes the `tmp` directory and a timestamp/hash added to the extension. See [Slack thread](https://dsva.slack.com/archives/C05UPRR0HK3/p1723562000319539?thread_ts=1723266007.465019&cid=C05UPRR0HK3) for more discussion between the devs

## Acceptance Criteria

- [ ] No longer seeing error for uploads with really long file names

## Tasks

- [ ] Determine technical approach — could make file name limit on the FE shorter or more explicitly specify extension on BE so that it doesn't add the extra timestamp/hash at the end
- [ ] Implement fix

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
https://dsva.slack.com/archives/C05UPRR0HK3/p1723568350903069?thread_ts=1723266007.465019&cid=C05UPRR0HK3

**Comment by anniebtran** [comment]
Just merged this — don't think we can really test this once it deploys, so we could probably close this and monitor our alerts to see if the error pops up again

**Comment by anniebtran** [comment]
Closing as we haven't seen the error since this has been deployed. We can reopen/create a new ticket if the problem appears again
