### ISSUE TITLE
Follow up on slow Postgres queries

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#90676]
## User Story
As a vets-api eng, I want Postgres to run efficient queries, so that vets-api is snappy.

## Issue Description
- Follow-up ticket to https://github.com/department-of-veterans-affairs/va.gov-team/issues/88315

Lighthouse was notified [in Slack](https://dsva.slack.com/archives/CDRSFMWFL/p1723577052497749) and they are working on a fix. Check on progress.

## Tasks
- [ ] Check PgHero for slow queries http://pghero-prod.vfs.va.gov/
- [ ] If the same slow queries (`vba_documents_upload_submissions` and `va_forms_forms`) are showing up, follow up with the thread linked above.
- [ ] If there are different queries showing up, investigate and follow up with relevant team.

## Success Metrics
_Describe what success looks like for this work. Define specific, measurable outcomes that indicate success._

## Acceptance Criteria
- [ ] There are no slow queries or a follow-up ticket is created to check back in with team. 
---

## Validation
- No slow queries listed at http://pghero-prod.vfs.va.gov/
- OR follow-up ticket created and linked in this ticket.

**Comment by AshleyGuerrant** [comment]
Closing out as a duplicate of #97380.
