### ISSUE TITLE
[FE] My VA: Update icons on My VA

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#90677]
## Background
_There are two icons that need to be updated on My VA, due to a change in the documentation for icons_

https://design.va.gov/foundation/icons

<details><summary>Icon details</summary>
<p>

**Current icons:**

![Image](https://github.com/user-attachments/assets/028749ef-afd7-4529-b5e4-21cd0df79fcb)

**Updated icons:**

![Image](https://github.com/user-attachments/assets/6743096b-35f5-4dce-b919-88fa37bca176)

![Image](https://github.com/user-attachments/assets/1bcb877f-d4af-487e-aa09-d4333178755c)

</p>
</details> 

## Where we need to make the change 
[Code pointer](https://github.com/department-of-veterans-affairs/vets-website/blob/e07156ff444dcfc8f40609587af9452eda70744e/src/applications/personalization/dashboard/components/education-and-training/EducationAndTraining.jsx#L34-L46)

Should be able to simply update the icon attribute from "assessment" to "assignment":

```javascript
    <IconCTALink
      text="Compare GI Bill benefits by school"
      icon="assessment"
      href="/education/gi-bill-comparison-tool"
      testId="compare-gi-benefits-from-cta"
      onClick={() =>
        rE({
          event: 'nav-linkslist',
          'links-list-header': 'Compare GI Bill benefits by school',
          'links-list-section-header': 'Education and training',
        })
      }
    />
```

## Sizing commentary 
<details><summary>sizing slack thread</summary>
<p>

![Image](https://github.com/user-attachments/assets/b9d298ac-c821-4a60-bb2b-2ff00f31eb5d)

</p>
</details> 

## Tasks
- [ ] Replace the current icon for "Compare GI Bill benefits by school" with 'assignment' icon
- [x] Replace the current icon "Go to your inbox" with the 'forum' icon
- [ ] Ask Ashley/Janelle/Travis/Other Dev to review for validation

## Acceptance Criteria
- [ ] Icons are replaced successfully

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Design
- _How can this work be validated?_ Visual check 

## Resources
https://design.va.gov/foundation/icons

**Comment by ajakabcin** [comment]
@mattmarino-adhoc to confer with DSC on appropriate icons to use for these scenarios

**Comment by ajakabcin** [comment]
@mattmarino-adhoc to add screenshots/specs for before and after icons

**Comment by mtcA6** [comment]
- The go to inbox was updated 3/2025
- "Compare GI Bill benefits by school" has yet to be updated

![Image](https://github.com/user-attachments/assets/ae6a055c-74ed-4eb2-87d1-ba0bce4c024f)

**Comment by emisparkles** [comment]
[Code pointer](https://github.com/department-of-veterans-affairs/vets-website/blob/e07156ff444dcfc8f40609587af9452eda70744e/src/applications/personalization/dashboard/components/education-and-training/EducationAndTraining.jsx#L34-L46)

Should be able to simply update the icon attribute from "assessment" to "assignment":

```javascript
    <IconCTALink
      text="Compare GI Bill benefits by school"
      icon="assessment"
      href="/education/gi-bill-comparison-tool"
      testId="compare-gi-benefits-from-cta"
      onClick={() =>
        rE({
          event: 'nav-linkslist',
          'links-list-header': 'Compare GI Bill benefits by school',
          'links-list-section-header': 'Education and training',
        })
      }
    />
```

**Comment by mtcA6** [comment]
@emisparkles @Diana20920 looks like the PR was approved and merged. I see the updated icon in staging. 

Not yet in prod I think after 2pm ET you can log into a prod account. If you haven't created a LO3 Prod account now is a good time to do so.

**Comment by Diana20920** [comment]
> Not yet in prod I think after 2pm ET you can log into a prod account. If you haven't created a LO3 Prod account now is a good time to do so.

🎉 Change confirmed in Prod 🎉
