### ISSUE TITLE
July Monthly Metrics

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#90674]
## Background
Quick tag team on July monthly metrics, since Jen was asking.

## Tasks
- [x] Complete monthly metrics pull for July in Google Sheets
- [x] Download as an Excel file and remove excess tabs/sheets
- [x] Upload Excel file to Sharepoint

## Acceptance Criteria
- [x] Sharepoint has reporting for July

**Comment by oddball-lindsay** [comment]
Updated "All Analytics" tab with Janelle, to include July metrics.  Left the other tabs alone (currently with June only metrics), for Lisa to add July metrics as a training exercise.
