### ISSUE TITLE
Remove field validation on Military Service Number

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#90673]
## Issue Description
With #88432, we are now pre-filling military history for those veterans who have that info available in their profile. One issue we encountered was when pre filling service number, Veterans who enrolled after 1971 have their SSN as their service number, so that's what we're using for them. The front-end validation for that field is trigged since it doesn't match the expected service number format.

VBA input: 

> Feedback from our VBA Stakeholder (Derek Uttley) is that we should remove format validation from this field. Any data provided in this field could be useful downstream and will save the Veteran some keystrokes, the VBA team will take whatever the system provides in this field.

---
## Tasks
- [ ] Remove the front end field format validation for the Military Service Number so the error message does not display regardless of what is entered or prefilled.

## Acceptance Criteria
- [ ] Field accepts all inputs regardless of character or number combos
- [ ] User is able to get to the next step on the form regardless of what they put into the Military Service Number field

**Comment by matt4su** [comment]
Perhaps unrelated to Service Number change which tested fine, i did see instances where the error messaging associated with the "Date Initially entered active duty" and "Final release date looked repeated and misaligned.  Steps to recreate: On step 2 of 7 (Military history) in the pension app populate all required fields on the page, except leave blank the "day" or "year" value" of the Date initially entered active duty or Final release date from active duty.  Note the "Please enter a complete date" verbiage is repeated and the second instance of the verbiage rpushes down the input box in a way I would not expect.  See screenshot.   <img width="808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--504780ebf8e20c942d4dc067682d07df2883ab4a/Screenshot%202024-08-20%20at%201.53.13%E2%80%AFPM.png" alt="Screenshot 2024-08-20 at 1.53.13 PM.png" />

**Comment by TaiWilkin** [comment]
@matt4su I'm seeing it for other date fields, so it's definitely not related to the service number change. We should make a ticket to look into it
<img width="497" alt="Screenshot 2024-08-20 at 3 12 26 PM" src="https://github.com/user-attachments/assets/eb0ff33a-9571-4ca3-9204-98809b852dea">

**Comment by matt4su** [comment]
@TaiWilkin it appears this issue is in another team's backlog.  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3113.    Once they address would we have to do anything additional to benefit from the change (e.g a pension app specific ticket to implement?)

**Comment by TaiWilkin** [comment]
@matt4su A fix to the component will likely fix our issue as well without additional work on our end, but we should check after the fix is released

**Comment by matt4su** [comment]
Will do, thanks @TaiWilkin

**Comment by aplatt-coforma** [comment]
Closing this ticket since Matt verified that the original issue is fixed. 

Well test the issue noted in https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3113 once it's ready on staging.
