### ISSUE TITLE
Discovery phase for VHA payment history design ideation

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#90671]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

We have completed the study for VBA payment history. As we launch into the VHA payment history design phase, we will use the VBA study findings to inform our design process of one-thing-per-page as it pertains to the VHA paths. 

We will also gather the relevant data from Medallia feedback as it pertains to VHA pages. 

To organize our efforts, we will have a team workshop to look at the points of similarity, and where the experience differs. 

The goal is to have these 2 experiences as congruent as possible. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_
- [ ] UX team to create a Mural and/or spreadsheet 
- [ ] UXR to gather pertinent Medallia copay pages feedback to add as considerations for the workshop
- [ ] UX team will analyze, compare, and contrast to inform the design process for VHA payment history and one thing per page

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
- [ ] A mural and/or spreadsheet to guide design ideation
- [ ] VHA copay Medallia feedback doc
- [ ] UX design can launch into formal design mockups to prepare for sharing with SMEs and Veterans in a study

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mgleo** [comment]
Several discovery meetings with VHA stake holders (08/19, 09/09) and lighthouse developers (09/04, 09/05) helped inform mockups. 
https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=3212-30062&t=bMQpcT5bhvDpcHsk-1
