### ISSUE TITLE
Continue GA4 & BigQuery Audit

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#90681]
### Description
 This ticket is to account for the work that we are doing for our audit of our Google Analytics Properties and BigQuery.
 
_This was unplanned work for the sprint, but given we've been spending significant time on it, we are injecting it into our sprint. Details of the audit can be found in the postmortem in the sensitive repo_

---

### Tasks

- [x] Perform audit of Google Analytics 4 Property
- [x] Perform audit of Google BigQuery
- [x] If needed, perform audit of Domo.
- [x] Log findings in postmortem

### Acceptance Criteria

- [x] Findings from audit have been shared in private Slack message.
- [x] Findings and outcome have been logged in postmortem.

**Comment by johnny-jesensky-adhoc** [comment]
This audit work has continued to be the priority, and as accounted for a large portion of Jamie's time this sprint. We have been documenting our findings, and are looking to finalize the audit from our side in next sprint, continued in this separate ticket -- #91702 

FYI @jestutt, @dorseypa1
