### ISSUE TITLE
Discovery: Update the Feedback Footer links

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90696]
## Issue Description
The `Submit new Platform Website content' link in our Feedback Footer sends users to the [Provide or Suggest New Content for the Platform Website
](https://depo-platform-documentation.scrollhelp.site/support/how-to-provide-and-suggest-new-content-for-the-pla) page, where the user has to read all of the instructions before finding the link to the [Documentation Support Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=documentation-support&template=documentation-support-request.yml&title=Documentation+support). Would it be simpler for the user to go right to the GitHub form from the Footer link?

---
## Tasks
- [x] discuss with the team
- [x] decide whether to link directly to the GitHub form
- [x] create separate ticket to update the Footer link if necessary

## Acceptance Criteria
- [x] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90696?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
pulling into current sprint due to available capacity and low estimate

**Comment by jknipes** [comment]
Closing as _Done_
