### ISSUE TITLE
Discovery: Update Instructions on Provide or Suggest New Content for the Platform Website

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90693]
## Issue Description
The page [Provide or Suggest New Content for the Platform Website
](https://depo-platform-documentation.scrollhelp.site/support/how-to-provide-and-suggest-new-content-for-the-pla)contains a link to our public Slack channel and a link to the GitHub form [Issue: Documentation Support Request
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=documentation-support&template=documentation-support-request.yml&title=Documentation+support) 
Suggested changes: 

1. break out the links into to separate bullets so they are easier to notice
2. make the links **bold type** to stand out
3. change the link text for the GitHub ticket to read `Documentation Support Request` instead of `this form`

---
## Tasks
- [ ] Discuss these changes among the team
- [ ] Decide what changes will be made and how to implement
- [ ] Create edit ticket for the work

## Acceptance Criteria
- [ ] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by BSmolensky** [comment]
PCT discussed proposed changes in Slack. Consensus reached. Creating edit ticket.

**Comment by BSmolensky** [comment]
All Tasks Complete. Acceptance Criteria Met. Ticket is ready to close.

**Comment by jknipes** [comment]
Closing as _Done_
