### ISSUE TITLE
Submit google analytics implementation request for setting up tracking

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#90703]
### User story
As a Cartography team member, I want all relevant links to be tracked clearly in GA4 so I can track movement around the portal and on the landing page.

### Notes
- Learned from work on [ticket 89722](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/89722) that multiple important links do not currently track clicks in a way that is easy to find and/or use

Possible tasks:
- [x] Record all tracked click events on the landing page
- [x] Record all links we want tracked, how they're currently showing up (via adswerve)
- [x] Submit ticket to analytics team to communicate desired changes

## Acceptance criteria
- [x] Ticket to analytics team has been submitted

**Comment by fmccaf1** [comment]
[Submitted this ticket to explain some of the weird things we're seeing in click reports](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91507)
