### ISSUE TITLE
Creat Round of GA4 'How-To' Resources - Using Comparisons

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#90718]
### Description
This task is to create "how-to" guides and other resources to help GA4 users navigate and use the new GA tool for the platform documentation site. Resources should work for those new to GA in general as well as for the existing UA users who are just looking to reproduce [as close as possible] what they did  in the old GA version. "How-to" guides should, at least initially, support the live trainings. 

**Topic**: Comparisons in GA4

### Tasks

- [x] Each "how-to" and most other resource should include written step-by-step instructions with accompanying supportive visualizations (screenshots, animated gifs, infographic, etc)
- [x] Initial drafts shared with and reviewed by other A&I team members (someone who did not write it)
- [x] Shared on Confluence site.

---

### Acceptance Criteria

- [x] Resources topics have been identified
- [x] Written resources have been created
- [x] Drafts have been shared with and reviewed by other A&I team members (someone who did not write it)

**Comment by Blivaditis** [comment]
Here is the link to my completed comparison training in confluence, will update if any new findings come up while working through the training session tomorrow.

**Comment by johnny-jesensky-adhoc** [comment]
Thanks @Blivaditis -- think you may have forgotten to link, but I found it here in Confluence. 

[How to Reporting: Comparisons]- (https://vfs.atlassian.net/wiki/spaces/AT/pages/3403907099/How+to+Reporting+Comparison)

Just reviewed, made a few formatting edits, and left you a couple of comments, but this is mostly looking good. A note that when we eventually publish these to the Platform Website docs, we'll need to do to the following, though will likely be in a separate ticket.

- Confirm with Security Team we can post screenshots from GA.
- Formatting is structured appropriately.
- Confirm there are no launch-blocking issues, (we'll need to include alt-text on the images, and a few other changes in order for these to get published).

 Given that is going to be separate work, marking as _**Done**_.
