### ISSUE TITLE
[FE] My VA Ben App Drafts: Improve isolated error monitoring/handling on draft forms & apps (pt 1)

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#90712]
## Background
Following up from the incident on 8/8/24, we identified areas where we can improve our isolated error monitoring and handling on My VA for draft forms and applications. The root cause of the incident was that the name of a form was changed by another team but was not changed in all places where that form exists, specifically in the `platform/forms/constants` file. We will be working separately with Platform to figure out how to avoid situations like this in the future, but in the meantime we should also improve our error monitoring and handling so that if this happens again, our page fails gracefully instead of crashing.

## Tasks
- [x] Add unit and e2e tests for getAppURL
- [x] Add unit and e2e tests for tryGetAppURL

## Acceptance Criteria
- [ ] The page can fail gracefully (doesn't crash)
- [x] confirm error in browser console, but My VA is still loading

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ 
- _How can this work be validated?_

**Comment by allisonlu** [comment]
@ajakabcin 

i didn't get as much work done on this as i wanted to, so i will need to bring this into the next sprint with the same amount of points

**Comment by allisonlu** [comment]
@ajakabcin 

This is ready for validation! Tagging @DanielMiller-agile6 since this change isn't front-facing. 

Can you confirm the following:
- [ ] the [corresponding PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32018) is merged
- [ ] my [`c7d4eee` commit](https://github.com/department-of-veterans-affairs/vets-website/commit/c7d4eee2ca9ef0d118aaf84e114bc3c6f38ca257) has deployed to staging (via the [deploy status on FE dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/))

**Comment by DanielMiller-agile6** [comment]
@allisonlu verified changes on main, lgtm 👍
