### ISSUE TITLE
Platform Security Access Review: Removal of Users in GTM and GA

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#90715]
### Description
This work is to account for the follow-up work needed for the security access reviews of Google Analytics and Google Tag Manager. This work was started by Jamie in two previous tickets, but follow-up work will be transferred to Basil and Christine.

**Previous Tickets**
- [Platform Security Access Reviews - Google Tag Manager (GTM)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89031)
- [Platform Security Access Reviews - Google Analytics #88915](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88915)

- Findings from Jamie from previous ticket can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/88915#issuecomment-2286151409

---

### Tasks

- [x]  Remove any GA users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.
- [x] Remove any GTM users that should no longer have access to the systems or applications. Results must include a list of user access that was changed and why. Note -- we have guidance to deactivate users who have not been active in more than 1 year.
- [x]  Determine who from the VA should be granted as an administrator, then add them.
- [x] Document the results of the review using the below templates.
- [ACCESS REVIEW - Google Analytics](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3213787639/ACCESS+REVIEW+-+Google+Analytics)
- [ACCESS REVIEW - Google Tag Manager](https://vfs.atlassian.net/wiki/spaces/PSEC/pages/3218145281/ACCESS+REVIEW+-+Google+Tag+Manager)

### Acceptance Criteria

- [x] Security Access Reviews have been completed for Google Tag Manager
- [x] Security Access Reviews have been completed for Google Analytics

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc Ray Wang was an Account-level Admin so it makes sense to elevate him to Org Admin in the Google Marketing Platform. He should have received an email to raywangoctova@gmail.com confirming this access. 

@ChristineYoungZA You indicated that all that all the GMP accounts marked for deletion had been removed but I don't see that you uploaded an updated excel file confirming this. I'd also like to continue to use that file as we set up user groups.

**Comment by jestutt** [comment]
@ChristineYoungZA  Screenshot of the GMP Org Admins:
![Screenshot 2024-08-21 at 1 09 12 PM](https://github.com/user-attachments/assets/0f2270a3-7cb8-4561-9782-859c5771575a)

**Comment by ChristineYoungZA** [comment]
The admin list and deleted user list has been added to the website, updated Kelly about the changes.

**Comment by johnny-jesensky-adhoc** [comment]
Kelly confirmed that access reviews for GTM and GA are looking good -- marking as _**Done**_.

FYI @ChristineYoungZA, @jestutt
