### ISSUE TITLE
[Research] My VA Forms Status: UAT strategy discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#90721]
## Background
We need to settle on a strategy for conducting UAT on the forms status work in partnership with the VFF team. It may not be possible to do traditional UAT with Veterans but we need to do some internal discovery on options so we know how to proceed with a UAT plan and documentation.

## Tasks
- [x] Discuss current state with VFF partners
- [x] Reach out to Platform to discuss our options
- [x] Create outline/draft of conversation guide and potential tasks, for conversation with Perigean
- [x] Set up time to speak with Perigean about recruitment

## Acceptance Criteria
- [x] We are ready to meet with Perigean, as well as internally discuss approach and plan strategy 

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ PM
- _How can this work be validated?_ Discussion with Matt

**Comment by mattmarino-adhoc** [comment]
Reached out to VFF, waiting to hear back more from platform research before any potential contact with Perigean

**Comment by mattmarino-adhoc** [comment]
Shane Strassberg has recommended that we could attempt to proceed with testing through Perigean by being very specific about the criteria required while being broad otherwise with other aspects of who we recruit from.

**Comment by mattmarino-adhoc** [comment]
Made some initial edits/adds to QA test cases, which can inform UAT tasks. Next step will be to come up with a preliminary UAT plan/conversation guide for criteria we can potentially test in Production with users (draft, submission in progress, received). Action needed and any system error scenarios should be excluded. We will need to have limited expectations with submission in progress testing. After this is created, we can have platform assist us with talking with Perigean about what we will need for recruitment.

**Comment by ACParker89** [comment]
Next steps: 
- talk to Chante about proceeding with UAT and minimal criteria 
- modify ticket- can we close out some of this and spin off another ticket based on conversation with Shane/Chante
@mattmarino-adhoc @ajakabcin

**Comment by mattmarino-adhoc** [comment]
Shane Strassberg is helping us arrange a meeting with Perigean to discuss our specific recruiting criteria, exact time TBD but I am aiming for ASAP (maybe today if we're lucky).

**Comment by mattmarino-adhoc** [comment]
Closing this out with modified AC, we'll pick up the remaining criteria as a new story next sprint (meeting with Perigean, next steps with VFF team, planning approach and strategy)
