### ISSUE TITLE
[Design] My VA Forms Status: Post-MVP documentation

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#90723]
## Background
Capturing post-MVP needs/tasks for forms status 

Items for post-mvp:
- download functionality
- top level/page onsite notification/alert
- revisit process list 
- in-take process for scaling (non-Veteran facing)
- revisit expansion of error scenarios (e.g. when drafts work but submitted forms don't)
- revisit draft card designs (expiration date ux)

## Tasks
- [x] Document future state concepts for post-mvp
- [x] For items identified as "revisit" determine next steps (i.e. in or out of next phase of work, or if additional design work is needed)
- [x] Sync with Mike/PM to go over prioritization 

## Acceptance Criteria
- [ ] Comprehensive documentation of post-mvp options

**Comment by ajakabcin** [comment]
@mattmarino-adhoc I'm moving this to sprint after next (47) given higher priority items

**Comment by mattmarino-adhoc** [comment]
We will now add PDF download related details, as they will not be in MVP

**Comment by mattmarino-adhoc** [comment]
Going to next sprint

**Comment by mattmarino-adhoc** [comment]
[Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/forms-status-on-My-VA/Future%20enhancements/Post-MVP%20Forms%20Status%20on%20My%20VA%20Frontend%20Documentation%20(WIP).md)

**Comment by mattmarino-adhoc** [comment]
This is the updated list of post-MVP items to address, both ones we are certain to take on and ones we will need to review further before taking action:


-  PDF download support on form status cards (Submission in progress, Received, Action needed)
-  Support for 21-0966 (Intent to file)
-  The addition of a page level alert that appears at the top of My VA, indicating when a form submission has had a detectable system-based error
-  Possible addition of a Process List component, mirroring the one shown on the submission confirmation page
-  Possible removal of the 'error' icon on the Draft cards
-  Possible addition of truncation and dedicated page for form status cards
-  Possible addition of secondary link going to a dedicated Resources page for form statuses
-  In-take process for scaling (non-Veteran facing)
-  Revisit expansion of error scenarios (e.g. when drafts work but submitted forms don't)
-  Revisit draft card expiration dates
-  Revisit overall card content

**Comment by mattmarino-adhoc** [comment]
More detailed design documentation for enhancements for the following will be part of this ticket:
- Specs for PDF downloads
- Initial specs for page-level alerts

**Comment by mattmarino-adhoc** [comment]
Closing this ticket out, but we will update documentation as needed in the future as we further solidify priorities/details.
