### ISSUE TITLE
[UX/FE] 10-10EZR: Update Need Help section with new Accredited Representative content

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#90736]
## Background
A request came to the team from the Accredited Representative Management team (ARM) to replace the VSO contact guidance with Accredited Representative contact guidance.
This is part of an ongoing effort for the ARM team to streamline the information for Veterans around this subject.  

### References

<details>
<Summary>Expand for Slack Message details</Summary>

**Lindsay Li-Smith**
- Hi 1010 team!  Popping in from the Accredited Representation Management (ARM) team with a content request update.
- We have been partnering with CAIA to create content pages around accredited representation, and have an ongoing project to streamline the information for Veterans around this subject.  Would your team be open / have bandwidth to update the footer of the 10-10EZ intro page, so it references our landing page instead of the older https://www.va.gov/vso/ page?
- I have specific content recommendations from our CAIA partner, which I'll elaborate on in the thread :thread:

- Here's the content from our CAIA partner for all three pages, which fits the updated content standard of having the link on a separate line:

> If you need help gathering your information or filling out your application, you can appoint a VA accredited representative.
> [Get help filling out an application](https://www.va.gov/get-help-from-accredited-representative/)

- That content ^ is intended to replace the content and link target currently on the page.
![image](https://github.com/user-attachments/assets/9bdd2003-9e9e-4ee3-befe-7d8029453dcf)

- We took a backwards approach to discover this page -- we first found the legacy https://va.gov/vso/ link, then looked at Google Analytics to try and figure out what pages were pointing to that link.
- If there are other products/pages of yours that also reference this legacy https://www.va.gov/vso/ link, please let me know!
- And if there's a more formal process to request updates from the VA Forms team, feel free to point me in that direction
va.gov

**Heather Justice**
- Thanks Lindsay!  The only thing that might be a little wonky is that the paper form references VSO, so we will need to share the intent with the stakeholders.  Can you give us any background on how VSO changed to AR? (edited) 

**Lindsay Li-Smith**
- Sure!  The term "Accredited Representative" encompasses a few types of representatives that can assist Veterans:
     - Accredited VSOs (Veteran Service Organizations) -- this is by far the most common and they are free of charge
     - Accredited attorneys
     - Accredited claims agents
- We understand that Veterans resonate much more with the term "VSO" than the term "accredited representative" which is why our [landing page](https://www.va.gov/get-help-from-accredited-representative/) Get help from a VA accredited representative or VSO includes the term VSO in it's title.
- At the start of the landing page, we briefly mention these types and link out to an FAQ page that goes into more detail about these different representative types.  That FAQ page VA accredited representative FAQs is another page we've partnered with CAIA (and stakeholders) to publish.

- All that said, for the content update we're requesting, we're focused more on the value to Veterans.  If you're concerned about "VSO" term going away, I can circle back with our CAIA partner to discuss :slightly_smiling_face: (edited) 

**Heather Justice**
- We do also own the 10-10EZR that includes the same reference in the footer

**Lindsay Li-Smith**
- Awesome, would be great to get both updated to align Veterans to the most up-to-date guidance! :pray:

- Really appreciate that!  We're tracking traffic to our content pages, so would love to know when the changes on your products take effect so we can map that back to any traffic increases.  You can confirm with me in this thread, or you can alert us through the actual ticket if you use Github -- our team label is `accredited-representation-management-team` (dark green color). 

**Heather Justice**
- awesome, we'll add yall to the ticket and tag you when done

</details>

The current content is:
>If you need help to gather your information or fill out your application, [contact a local Veterans Service Organization (VSO)](https://staging.va.gov/vso/).
<img width="589" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGc5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba2066622f2529dd1c764962e4a1765cb00610e9/image.png" alt="image.png" />

The CAIA-approved content is:
>If you need help gathering your information or filling out your form, you can appoint a VA accredited representative.
[Get help filling out a form](https://www.va.gov/get-help-from-accredited-representative/)

## Tasks
- [x] [Design] Update designs to replace the VSO content with Accredited Representative content
- [x] Review with team/Engineers
- [x] [FE] Update Need Help section to reflect the new content change
- [x] Validate with team/PM
     - Signoff required to be documented in the comments
- [x] Launch to Prod after signoff
- [ ] Tag `accredited-representation-management-team` when this ticket is closed

## Acceptance Criteria
- The Need Help section of the 10-10ezr is updated to reflect the new Accredited Representative content.

**Comment by IMHieuVo** [comment]
[Figma Link](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=4484-63685&t=QJikR7LCVM9DXS2u-1)

**Comment by IMHieuVo** [comment]
Products that use the legacy VSO link:

- Education Benefits & Applications (#benefits-education)
- Benefits Disability Experience Team 1 & 2 (#benefits-disability)
- Contention Classification Team (#benefits-contention-classification)
- Pension Benefits (#benefits-pension)
- Integrated Veteran Care Forms (#ivc-forms)

**Comment by allanto-ah** [comment]
Environment: Staging, Production

Verified that this has been updated. We also went through it together as a team on a call. Also verified that it is in production. 

![Image](https://github.com/user-attachments/assets/709ba0fc-31a2-4285-9037-0e09df6ce404)

**Comment by allanto-ah** [comment]
The accredited representation management team has been notified via [Slack](https://dsva.slack.com/archives/CMJ2V70UV/p1723062021733149)
