### ISSUE TITLE
[FE] 10-10CG - Form Updates: Update file upload pattern

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#90735]
# BLOCKED - Pending File Upload pattern V3 availability

## Benefit to the Veteran
As a Veteran, I want to see clear messaging on file upload alerts and errors, so that I can make decisions and adjustments to my attachment for a successful application.

## Background
Now that the July form updates have been released, we want to review content and make some adjustments to better align with VADS guidelines.
The changes included in this ticket are listed below.  Refer to [Figma design file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=2FrxXdW6Q7EbOvWb-0) for visual guidance.

1. Update the File Upload pattern

### Resources
- [Figma file](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2330-45640&t=2FrxXdW6Q7EbOvWb-0)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683656893560/fccf821394d1cf693ad1c036e912e11a18ff88bd?sender=uadf1ed7fe7c76f0914967329)

---
## Tasks
- [ ] Update File Upload patter
- [ ] Review with the team/PM to confirm expected design/behavior
     - PM Signoff required to be documented in comments below
- [ ] Inform [QA/Teammate] when the next step can begin

## Acceptance Criteria
- 10-10CG File Upload screen is updated with the correct order of information to display

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`1010-team`)
- [x] **Labeled with Form** (`1010-ez`, `1010-ezr`, `1010-cg`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `ux`, `design`, `research`, `product`, `qa`, `1010-analytics`)
- [x] **Labeled with Project** (`facilities-cg`, `registration`,  `toxic-exposure`, etc.)
- [ ] **Add Assignees** (who will do this work?)
- [x] **Add Estimate effort  (or `needs refinement` label)
- [x] **Add Dependencies 'blocked by' and 'blocking'** (link tickets in the Dependencies section below)

**Comment by hdjustice** [comment]
Discussion held with DST and they will address the first two blockers so that our team can move forward on using the new File Upload pattern (VaFileInputField)
- As of 1/27/2026, Issue 1 ([ticket #5500](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/5500)) [has been fixed](https://github.com/department-of-veterans-affairs/va.gov-team/issues/120242#issuecomment-3812682085)
- Issue 2 ([ticket #5520](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/5520)) is In-Progress
