### ISSUE TITLE
Content Edits: Footer Ticket 90461

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90742]
## Issue Description
Per footer ticket 90461, we need to add an "alert box" at the top of the page with the text
`As a matter of policy no non-production environment may be interconnected with an outside system that contains real PII/PHI.`

---
## Tasks
- [ ] add alert box to the page
- [ ] check for launch blocking issues
- [ ] prepare for deployment

## Acceptance Criteria
- [ ] alert box has been added
- [ ] page is ready for deployment 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90742?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by jknipes** [comment]
Tasks completed, moving to _Closed_
