### ISSUE TITLE
Content Edit: Footer Ticket 90634

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90767]
## Issue Description
Per Footer Ticket [90634](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90634), and confirmation from the CAIA team, we need to fix a link on the [Collaboration Cycle page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) to show the correct GitHub template.
![image](https://github.com/user-attachments/assets/33ad4ac9-c2f6-4025-b2b5-a67b803e51c5)

---
## Tasks
- [x] Remove the link shown above from the Collaboration Cycle page
- [x] Replace the link with [this link to the correct intake form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=strelichl%2CNaomiPMC&labels=sitewide+CAIA&projects=&template=CAIA-intake-form.md&title=%5BCAIA+Intake%5D+%3CTeam+Name%3E%3A+%3CInitiative+Name%3E)
- [x] check that link is functional
- [x] check page for launch blockers

## Acceptance Criteria
- [x] All tasks complete
- [x] page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90767?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by taylojill** [comment]
Link updated and checked, date stamp added, no launch blockers. Ready to publish.

**Comment by jknipes** [comment]
work is complete, closing ticket
