### ISSUE TITLE
Transfer FDG ownership to VA Forms team

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#90766]
## Purpose
Transfer editing rights and general ownership of the Guide to the VA Forms team.

## Tasks
- [x] Advise team leads of handover
- [x] Link them to the location of the source material for editing (Confluence)
- [ ] field any immediate questions
## Acceptance Criteria
- [x] Team is notified
- [x] Team is aware of Confluence source material for guide
