### ISSUE TITLE
BE | Profile | Remove domain name from VCR cassettes

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#90764]
## Background
Hide the domain name in  all Profile-related VCR cassettes. It be defined in the[ VCR configuration](https://github.com/department-of-veterans-affairs/vets-api/blob/16239c47337635c36aa1b7d2cfd474d469513227/spec/support/vcr.rb#L9).

## Tasks
- [ ] Hide domain name from all contact-info cassettes
- [ ] Hide domain name from all communication-preferences cassettes
- [ ] Hide domain name from all direct-deposit cassettes
- [ ] Hide domain name from all military-history cassettes

## Acceptance Criteria
- [ ] Approved by platform.
