### ISSUE TITLE
Ensure Clamav Client is being properly used throughout vets-api

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#90773]
## User Story
As a developer, I want to ensure the new Clamav Client is being properly used, so that necessary files are being scanned for viruses.

## Issue Description

The [generate_clamav_temp_file](generate_clamav_temp_file) method replaces generate_temp_file when an attachment is being uploaded to vets-api. Generating a temp clamav file creates a temp file in the /clamav_tmp directory. This is a shared directory between vets-api and clamav containers to allow clamav to scan for viruses.
Files uing generate_temp_file:
- app/models/saved_claim/coe_claim.rb
- app/sidekiq/vbms/submit_dependents_pdf_job.rb
- lib/benefits_intake_service/service.rb
- lib/common/convert_to_pdf.rb
- lib/lighthouse/benefits_intake/service.rb
- lib/simple_forms_api_submission/service.rb
- modules/claims_api/app/services/claims_api/disability_compensation/pdf_generation_service.rb
- modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_pdf_generator.rb
- spec/services/form1010cg/service_spec.rb

## Tasks
- [ ]  Update any documentation
- [x]  Ensure the generate_temp_file/generate_clamav_temp_file is being properly used in the 9 files:

## Success Metrics
- [ ] Update documentation regarding this change
- [x] Ensure/replace generate_temp_file with generate_clamav_temp_file when the file is being uploaded to vets-api.. Ensure Common::VirusScan is being ran when needed.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by jennb33** [comment]
8/28 update: @rjohnson2011 is writing specs for this ticket; it should be ready for review shortly.
