### ISSUE TITLE
IA Tracker: Form Uploader tool

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#90793]
### Description
Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723739688312/66816378c17c92835f7a65108057fc255226cb10?sender=ua67f17f1c416a96ea04d2476

### Links

- [Intake Ticket #81623 ](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/26?pane=issue&itemId=60919068)

### Team

Team name: Veteran Facing Forms
OCTO product owner: Matthew Dingee
Product name: Document Upload
Product manager: Tricia Baker
**Slack channel:**veteran-facing-forms

### Timeline
Went through midpoint in mid-May. After user research, determined there were some problems with findability. Additionally, Mikki flagged scalability of putting separate upload tools under find-a-form, so we talked with the team on 8/15 to come up with a new page placement, URLs, and breadcrumbs. 

### Work needed

- IA spec: Needed
- Feedback for product team: Needed (already provided in ticket and meetings)

```[tasklist]
### IA deliverables
- [x] [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/find-a-form-upload.md)
- [x] Feedback
- [x] [IA mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723739688312/66816378c17c92835f7a65108057fc255226cb10?sender=ua67f17f1c416a96ea04d2476)
```

## Acceptance Criteria
- [x] Feedback is shared with product team in Intake Ticket.
- [x] IA Spec is shared with product team in Intake Ticket.

**Comment by kristinoletmuskat** [comment]
Closing because IA spec has been shared with team.
