### ISSUE TITLE
Finalize Conversation Guide with "Veteran Info Review Page" in Place

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#9080]
## Goal
We need to include the latest screens and functionality in the usability sessions and conversation guide to account for their review by the Veteran.

## Considerations
- Usability Sessions are time intensive and as a final launch activities go, we want to get any last minute feedback in from the Veteran that we can that may inform us of items to correct either before or after launch.

## Tasks
- [x] Incorporate new screens in mockups in the event that staging is unavailable during the usability sessions.
- [ ] Ensure that the workflows are fleshed-out and completed in staging
- [x] Ensure that the intended workflow makes sense at a high level but take care to inform the Veteran why this page is necessary
- [x] Include an exploration of the 686 Review Screen in the convo guide

## Acceptance Criteria
- [x] Mockups and Conversation Guide are in sync, updated, and ready for usability sessions

### Next steps
- [ ] 686 in Staging is tested and stable; supports all workflows
- [ ] Convo guide reviewed by Shawna; feedback incorporated
