### ISSUE TITLE
[CST] Update claim letters page to accommodate new letter types

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#90814]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to easily navigate and understand the Claim Letters page when there are a bunch of different letters in it
**_So that_** I can easily find the letter I'm looking for 

---
## Background Context
The VA has a goal of making more letters available to Veterans in the Claim Letters page, so that Veterans can more easily find communications, download letters, and take any necessary action without having to wait for letters to arrive in the mail.

Now that we are adding new claim types to the Claim Letters page, we need to rethink the design of the page so that it doesn't become overwhelming to view. We've thought about section headers, filtering options, etc.

We have started some [initial design explorations](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/claims-letters/CST%20-%20Letter%20Download%20Codes.xlsx?d=w266d54b5b5db471f84bf21212761bb88&csf=1&web=1&e=gidSj6) but the design has not been finalized.

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design

Initial design explorations
<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1926e2838e71fa86605611be8a16b2207f480332/Screenshot%202024-08-15%20at%202.40.58%E2%80%AFPM.png" alt="Screenshot 2024-08-15 at 2.40.58 PM.png" />

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Add here

## Out of scope
- This ticket is just focused on the claim letters page. The scope does not include 5103 redesign work, content modeling, or other design work related to letters or tracked items outside of the Claim Letters page.
- 
## Open questions
- Add here

## Tasks
- [ ] _Design what this experience should be_
- [ ] _Align with team on design approach_
- [ ] _Implement new design for Claim Letters page_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _New design has been spec'd in Figma_
- [ ] _Team has aligned on design approach_
- [ ] _New design is implemented in Claim Letters_
