### ISSUE TITLE
[CST] Content Modeling to create more consistent presentation of information in requests to Veterans

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#90828]
## Value Statement
**_As a_** Veteran
**_I want to_** be presented with a more consistent display of information related to requests of various types
**_So that_** I can better navigate the requests and more easily figure out which actions, if any, I need to take for my claim

---
## Background Context

@jstrothman Has initiated an effort to create "content modeling" documentation for requests (1P and 3P) for both alerts that show up on the details page and the content that displays on the document request page.

Some work in progress related to this:
- [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581824942/975bd9a22e21177415cdb238525b3e1aac95a288?sender=u80fb5a3b8f7951f35d701197)
- [Figma](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=2773-22270&t=ZtfppmVFmBMO3UBg-4)
- Technical annotations for existing [1P requests](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---V2-(Evidence-Submission)?node-id=2698-3151&t=bkgRcY0tGJfP02pW-4) and [3P requests ](https://www.figma.com/design/F8U4wddaFouUPVd4mGBMDI/CST---V2-(Evidence-Submission)?node-id=2712-3254&t=bkgRcY0tGJfP02pW-4)
- [Evidence requests descriptions drafting doc](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/evidence-requests/evidence%20request%20descriptions%20drafting.docx?d=w384ff0e8c5e943ee92522e04d2ad05f3&csf=1&web=1&e=o7l9B9)

## Design

Work in progress content modeling
<img width="947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM05nQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b66213ecea01553dd03d6b7686926a6d9365b13c/Screenshot%202024-08-15%20at%204.37.51%E2%80%AFPM.png" alt="Screenshot 2024-08-15 at 4.37.51 PM.png" />

### Enablement team (if needed)
@jstrothman 

## Engineering 
- Current und

## Out of scope
- Add here

## Open questions
- Overall, what does a template look like that will work the most broadly for various tracked items?
- How do we think of something that’s consumable by mobile for the content modeling work?
- How can we associate letters to tracked items? 
- Our current understanding is that all 1P tracked items will have a development letter associated with them, but not all development letters will have a 1P tracked item associated with them. How do we handle getting Veterans to the development letter if there is no 1P alert "bridge" to get them there?
- How do we handle different content types (e.g. unordered lists) that might show up in tracked item descriptions?

## Tasks
- [ ] _Create a a new Figma spec that shows the content model for 1P alerts, document request page, and claim letters, and provides examples from request types that are either in production or to be released in the near future_
- [ ] _Incorporate guidance from Andrew that is documented in [evidence request drafting doc](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/evidence-requests/evidence%20request%20descriptions%20drafting.docx?d=w384ff0e8c5e943ee92522e04d2ad05f3&csf=1&web=1&e=Tg9PC6)_
- [ ] _Share this new spec with the team_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _The Figma spec contains a scalable content model, documenting existing requests that are in production and leaving room for requests that have not yet been added_
- [ ] _AC_
- [ ] _AC_

**Comment by jacobworrell** [comment]
@skylerschain what are the tasks for us related to this effort? I can't pull this into Backlog refinement for sizing without a clear sense of what we're proposing to do.

**Comment by skylerschain** [comment]
@jacobworrell – I added some tasks above. @jstrothman will pick this up.

**Comment by rallencf** [comment]
Closing this old ticket which is captured in—and linked from—the more current [evidence request content models
(#102178)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/102178).
