### ISSUE TITLE
[CAIA Intake] Benefits Management Tools - CST: Adding new letters to Claim Letters Page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#90830]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: `Benefits Management Tools`
- **OCTO product owner:** @amylai-va @jstrothman 
- **Product name:** `Claim Status Tool`
- **Product manager:**  @jacobworrell 
- **Slack channel:** https://dsva.slack.com/archives/C04KHCT3ZMY
- **Dedicated content writer on your team (if you have one):** @laurwill 
- **Dedicated a11y specialist on your team (if you have one):** @davidakennedy 
 
## Your CAIA team:
- **IA:** @kristinoletmuskat 
- **Content:** @laurwill 
- **Accessibility:** Not needed for this ticket

### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [x] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

As we [make more development letters available](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90814) to Veterans in the Claim Status Tool, we need to ensure that the Claim Letters page doesn't become overwhelming. This might involve restructuring the page to ensure it remains navigable and clear.

We are primarily looking for IA support in figuring out the best way to restructure the Claim Letters page, but we may need some content and a11y support as well. 

Current Claim Letters Page
<img width="375" alt="18" src="https://github.com/user-attachments/assets/4627efd6-86d5-4e80-88c2-df88ae701e59">

**There are two distinct phases to this work**

**PHASE 1:** 
Update the existing Claim Letters page so that development letters show up there. This will involve a few small UI updates like making the ListItem header more unique, and putting the "Letter dated" string below in the subheader to help more easily distinguish between letter types at a glance.

Exploratory mock
<img width="500" alt="Screenshot 2024-08-26 at 6 08 05 PM" src="https://github.com/user-attachments/assets/161e0a18-2f68-4884-b2b0-cff2500e11de">

**PHASE 2:** 
Explore more robust ways of filtering and sorting the page so that is more navigable and Veterans have an easier time finding the letter they are looking for. This may involve leveraging new VADS design patterns to allow Veterans to filter and sort the list in different way. 

<img width="1030" alt="Screenshot 2024-08-26 at 6 07 58 PM" src="https://github.com/user-attachments/assets/56ee71b4-2593-411b-9a3b-cafe21ed01c0">

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [x] Yes
- [ ] No
- [ ] I’m not sure

We have committed internally to making these new letters available at some point in September.

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

Initial design explorations, which can be found [here](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3230-24448&t=ZtfppmVFmBMO3UBg-4) but are in the very early stages.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [x]  Yes
- [ ]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** `Enter dates`
- **What is the name of your engineer who will build the React widget?** `Name`

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [ ] None. This initiative isn’t going through the collaboration cycle.

**Not sure yet which, if any, collaboration cycle checkpoints this will go through.** 

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide your ticket number and link:
- **Ticket Number:** `xxxxxx`

## Supporting artifacts

Nothing beyond what is linked above

## Next steps
- [x] Post a link to this issue in the [#sitewide-content-sitewide-content-accessibility-ia](https://dsva.slack.com/channels/sitewide-content-accessibility-ia) slack channel and tag `@Naomi Eke`, and we’ll then acknowledge receipt. We'll then review the artifacts in more detail and work with you to determine timing for collaboration. Depending on the work, we may schedule a kickoff meeting to better understand how we'll partner together.
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by kristinoletmuskat** [comment]
Hey @skylerschain thank you for submitting! I just requested access to the sharepoint. A few Qs so that I have the right context!

1. What are all of the attributes we have for a letter? Here are the ones I see, and wanted to double check there aren't more:
- Date
- Type (ex: notification, 5103, etc)
- PDF attachment
2. What is the median # of letters a veteran has in here, and what is the max a veteran has the system? Like w/ the new letter types included, so we might have to cobble together some metrics. 
3. Do letters ever get removed from this list?
4. Do any of the EXISTING letters have any associated actions a user needs to take? Like adding evidence?
5. Do any of the NEW letters have any associated actions a user needs to take? Like adding evidence to a claim in CST?
6. When a letter has a date, what exact date is it referring to? Like is it the date it was generated, or the date it was posted on the CST, or something else?

Thank youuuu
Kristin

**Comment by jstrothman** [comment]
@kristinoletmuskat Re #2, in July, I asked one of our Office of Benefits Administration partners for the data below. I just sent him a check-in message to see if their data team has been able to look into numbers:

> We'd love to get a picture of how many claims people tend to have: open and all time. An average, whether median or mean, won't help us assess what we need to provide in the way of filters on the claim status tool (hence the histogram request). 
> Ranges would help us a lot more, e.g. how many Veterans with claims (open and all-time) have:
> 1-5
> 6-10
> 11-15
> more than 15
> 
> Related distribution question: How many letters are sent per claim? (Distribution by same range as above would be much more helpful than median average.)

Re #4 & #5, Skyler may have additional info, but here's what I know

4. Yes, the 5103 notice has a list of evidence we may need that they could upload in CST (see [example letter on SharePoint](https://dvagov.sharepoint.com/:b:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management%20-%20CST/claims-letters/ClaimLetter-5103-staging%202024-7-26.pdf?csf=1&web=1&e=PGMNfL)) _and_ it has a waiver form that they can submit, though they also can use the 5103 evidence request page on their claim to submit the waiver instead of signing and uploading the pdf. 

5. Yes, most of the new letters include some sort of call to action. I added a column to the letters spreadsheet with which ones have a call to action. 

Note: On the letters page, we have no ability to know which claim the letter is related to, nor what specific calls to action it may have, so we're unable to link to a specific claim in Claim Status Tool

**Comment by skylerschain** [comment]
Hey @kristinoletmuskat: [I added a couple possible variations for this design](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3884-33467&t=wjcPMyqiD8zbW4uN-4). Would love your feedback. In the first version we have a new header that says "Claim letters, listed by most recent first". The second version does not have that header. In both versions, we have swapped the letter name into the header of the list item itself so that it leads with the name, not the date (e.g. "Notification letter" instead of "Letter dated September 14, 2024". 

<img width="761" alt="Screenshot 2024-08-30 at 12 40 10 PM" src="https://github.com/user-attachments/assets/ef21aa81-bcac-41f3-aed7-4a8e28fa80c8">

As a reminder, for "Phase 1" we are just updating at this level, not introducing filters or anything like that.

Thanks in advance!

**Comment by kristinoletmuskat** [comment]
Hey @skylerschain, I left a comment in your Figma. I think given what we know, it's helpful to show X most recent letters with a button to display more ('show past letters') so that the user isn't overwhelmed by a potentially large number of letters. 

I also see your note about choosing 3 months as a potential time band because the average claim processing time is 5 months. If the main use case is users trying to find letters related to an open claim/appeal, it seems helpful somewhere to indicate how the list is default sorted as you did with the H2, but I have 2 thoughts about why we might not want to do that in the H2, and an alternate idea. 

**Why we might not want specific recency bands:**
1. A user might have letters from 3 years ago but none in the last 3 months, which means we would need a different or dynamic header for them. It might make more sense to just list the most recent letters at the top regardless of how recent they are.
2. If the average claim processing time is 5 months but a particular users takes longer, like 7-12 months, their letters would not show up in this section, so similar problem with the above. 
3. A user might have letters in some of the time bands (like 6 months, 2022, etc) and not others, so we could have null state messages for each of those sections, which I think would create a noisy page!

For these 2 reasons I feel like we maybe shouldn't limit the first section to a certain recency. It might make sense to wait for the filters to be able to pull like more specific date ranges. 

Idea for how to indicate default sort:
1. Maybe we could just put a line of text in the description saying the default sort is newest. 
2. Or, could we pop in a sort component-looking thing that's frozen to "newest"? If we think we'll want a sort in V2. I don't think we have filter/sort components in the design system, no not sure what governance will tell you!

![Screenshot 2024-08-30 at 4 43 50 PM](https://github.com/user-attachments/assets/383a43ac-4ba0-4a68-b035-a3cfdbcb0619)
![Screenshot 2024-08-30 at 4 56 19 PM](https://github.com/user-attachments/assets/4a988f91-108f-436d-9071-a15aff47636a)

I see @jstrothman your open question about number of claims/letters -- any movement on that? Or is this information that your devs could query from somewhere? Or even some user research observations? I think we could have a much more informed design with this info!

**Comment by jstrothman** [comment]
@kristinoletmuskat We don't have distribution data yet on number of claims/letters. Our Benefits Automation partners' data team has the assignment and they have best access to determine this. (Rather than our dev teams.) I last asked for an update on 8/20 and they hadn't gotten to it yet -- I'll follow up again.

**Comment by skylerschain** [comment]
Hey @kristinoletmuskat – thanks for the input. I think most of that applies to what we're calling "Phase 2" where we'll be exploring filters, etc. Do you have any thoughts for now on the header question from my comment above? 

You can see the latest version in that comment too for reference, with a link to the Figma.

**Comment by kristinoletmuskat** [comment]
@skylerschain Yes! I don't think repeating 'claim letters' in the H2 is super helpful, since it's in the H1. But then I'm wondering if there is a different way to indicate how the list is sorted, because I think that's helpful information. What if we replaced the H2 with 'Sort by: Most recent'? Then if/when we introduced actual sorting, that component would then be manipulatable instead of read only. I don't have figma edit access otherwise I would sketch it out in there. Does that make sense? I'm not sure if that would be allowed in the design system, but there is no guidance anyway for sorts/filters, so it might be allowed.

**Comment by kristinoletmuskat** [comment]
@skylerschain looks in the figma comments like y'all made a decision! Do you need any more input from us or can I close this one?

**Comment by jstrothman** [comment]
We'll also be interested in input on letter-naming when we work on the phase 2. (Timing tbd)

**Comment by kristinoletmuskat** [comment]
We can keep this one open for now since it has past thinking etc! Just make sure to retag Laura and I when you're ready to start this again.

**Comment by jstrothman** [comment]
For when we come back to the IA and UX of the claim letters page, we now have distribution data about open (pending) claims. Veterans will only receive letters related to open claims, so this data gives us some sense of findability of letters despite:

1. Vague letter titles
2. Our inability to associate a letter with a specific claim

In brief: 
**96% of Veterans with pending claims have only 1-2 pending claims.**

![Image](https://github.com/user-attachments/assets/8835f9ce-2f42-49bc-bd0a-1b67faeed008)

Data is offered for `all EPs` and `non-rating EPs` which are defined as:

- Rating Bundle: Claims for disability compensation, dependency and indemnity compensation, and Veterans’ pension benefits, including both original and supplemental claims. Rating Bundle claims normally require a rating decision during processing. VA’s goal of eliminating the backlog in 2015 is specific to the Rating Bundle.
- Not-Rating: Claims for disability compensation, dependency and indemnity compensation, and Veterans’ pension benefits, which can but normally do not require a rating decision (i.e. claim to add dependent to award).

**Comment by kristinoletmuskat** [comment]
Thank you @jstrothman! One follow up Q while this is top of mind:

1. I thought that the claim letters tool also includes decision letters -- is that true? And if so, are those included in this data? Like, does the letter get posted when the claim is still pending, and then it gets closed? Or do the decision letters live elsewhere?

**Comment by jstrothman** [comment]
@kristinoletmuskat Yes, claim letters in Claim Status Tool includes decision letters. 
When I said "Veterans will only receive letters related to open claims, so this data gives us some sense of findability of letters despite..." I was including decision letters as the final letter in an open (pending) claim, and effectively closing the claim. With regard to current findability -- it's helpful to know that 96% of Veterans only have letters coming in for 1-2 claims, as that means recency is likely adequate for finding what you're looking for. (Filters or sorting might still be useful but I'm not very worried about not having them yet.)

The data shown is number of pending claims per Veteran w/pending claims.
We were unable to get number of letters per claim, because there isn't an association between letters and claims. Some letters are associated with an EP/claim label but not a specific claim ID. Some Veterans may have more than one claim with the same EP/Claim label over time. For "Subsequent Development Letter,” the vast majority (99.3%) do have an EP associated (but again, not a specific Claim ID).

**Comment by kristinoletmuskat** [comment]
We shipped these letters, so closing this ticket.
