### ISSUE TITLE
Copy of MVP Hybrid Microservices: Helm Templating for Manifest and Environment Specific Configurations

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#90840]
## User Story
As the managers and developers for the VA Platform, 
We need to simplify the management of the deployment manifests and configs across multiple environments, 
So that the manifests and configurations process is simplified and standardized. 

## Issue Description
Simplify the management of deployment manifests and configurations across multiple environments.

## Tasks
- [ ] Use Helm for templating the manifests
    - [ ] Discover and document reusable Helm chart templates for deploying the microservice.
        - [ ] We could potentially try to re-use or modify the existing Vets API monolith helm chart
- [ ] Define environment specific values and configurations (e.g. development, staging, sandbox, production)
    - [ ] Define common values and configurations to be used across services
    - [ ] These values will be stored in the manifest values.yaml specifically
- [ ] Ensure secure management of sensitive configurations and secrets using Parameter Store
- [ ] Document the usage of Helm charts for deploying microservices
- [ ] Semantic version the Microservices architecture
- [ ] Establish best practices for Helm chart usage and begin to host helm charts in ECR 

## Success Metrics
That the management of deployment manifests and configurations across multiple environments is simplified and standardized for use. 

## Acceptance Criteria
- [ ] There are templates in place for Manifest and Environment-specific conditions
- [ ] That the templates are standardized across products
- [ ] There will be documentation on how this work was done
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
