### ISSUE TITLE
BE | Profile | Contact Information PCIU | Migration Support

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#90866]
## Background
Vets-API is migrating from VA Profile contact information v1 to v2.  The Platform Product Team is leading the migration, but they require assistance and support from various VFS teams.

## Tasks
- [x] Review PRs created for the migration.
- [x] Feedback on migration approach.
- [x] Answer any questions that arise.

**Comment by tpharrison** [comment]
Worked on this about 2-3 hours on Friday, Aug 17.
