### ISSUE TITLE
Update Slack Channel Name for Identity Team

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90860]
## Issue Description
Per [this Slack announcement ](https://dsva.slack.com/archives/CE4304QPK/p1723753970083219), the Identity team's Slack channel name has changed. Platform Website has 2 pages that reference the old channel name. We need to update these pages with the new name.

---
## Tasks
- [x] Go to deployment page for [Master Person Index (MPI)](https://depo-platform-documentation.scrollhelp.site/developer-docs/mvi)
- [x] Change all instances of **#VSP-Identity** to **#identity-support**
- [x] Go to deployment page for [Console Services (Backend)](https://depo-platform-documentation.scrollhelp.site/support/console-services-backend)
- [x] Change all instances of **#VSP-Identity** to **#identity-support**
- [x] Check pages for launch blockers

## Acceptance Criteria
- [x] Pages are updated with the correct name of the Slack channel
- [x] pagers are ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90860?planning-poker) with Zenhub @BSmolensky @laucon @taylojill

**Comment by laucon** [comment]
Just FYI, the SMEs updated the second page themselves. So that was perfect.

**Comment by laucon** [comment]
This ticket is done and can be closed. :)

**Comment by jknipes** [comment]
Closing ticket as _Done_
