### ISSUE TITLE
Reorganize Root Request Specs

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#90877]
## Summary

Request specs lack consistency and deviate from conventions either set by the Rails community or Vets-Api. There are 110 root request specs, but not all of them need to be updated. 

## Tasks
- Establish a naming convention
   - naming based on the routes 
- Update filenames
- Update example group names
- Create doc for new conventions

## Acceptance Criteria
- [x] root request specs files are named and organized based on established convention 
- [x] root request specs example group names are named based on established convention 
- [x] A developer doc exists for request spec conventions

## Example
Existing Request Spec
```ruby
# spec/requests/v0/lgy_coe_request_spec.rb

describe 'LGY API' do
  context 'when user is signed in' do
    describe 'GET v0/coe/status' do
    end
  end
end  
```
 
Update Request Spec
```ruby
# spec/requests/v0/coe_spec.rb

describe 'V0::Coe' do
  context 'when user is signed in' do
    describe 'GET v0/coe/status' do
    end
  end
end  
```
