### ISSUE TITLE
[BE] Remove Unwanted Feature Flags

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#90876]
## Description
Remove below unwanted feature flags,
check_in_experience_pre_check_in_handoff_enabled
check_in_experience_phone_appointments_enabled
check_in_experience_unified_landing_page

## Tasks
- [ ] [FE] **Remove flags from featureFlagNames.json**
- [ ] [BE] **Remove flags from feature.yml**

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging
