### ISSUE TITLE
Update Instructions for Date Stamp

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90895]
## Pain point:
Users of Platform website cannot tell when a document was last updated. A last updated date needs to be present at the top of every page. The calendar macro in Confluence produces a date configuration that is counter to our style guide, and that of the design.va.gov style guide.

## Issue Description
 - Current guidance asks users to type `/` and the word `date`, or simply type `//` to show a calendar and enter today's date on a document. Research shows that both the [VA Content Style Guide ](https://design.va.gov/content-style-guide/dates-and-numbers) and [our own Confluence style guide ](https://vfs.atlassian.net/wiki/spaces/AP/pages/1807810577/Dates+times+and+numbers) recommend using the format day-of-week, month day, year. Since our date stamp feature does not produce the recommended date configuration, we need to change our guidance to requiring manual entry of the date when creating or editing a document.
---
## Tasks
- [x] Read our style guide 
- [x] reach out to k15t re: can they help us configure date stamp so it matches our Style Guide.
- [x] update all pages in Confluence pertaining to Date Stamp with this instruction

## Acceptance Criteria
- [x] Guidance regarding Date Stamp will be updated in Confluence

### Research result added 8/23: 
 - k15t has confirmed the date configuration of the calendar macro in Confluence cannot be changed to match that of [our style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/1807810577/Dates+times+and+numbers).
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90895?planning-poker) with Zenhub @BSmolensky @taylojill @laucon @cmarion93

**Comment by BSmolensky** [comment]
If // or /date cannot be updated to match our style guide, then, in my opinion, we should update the instructions so that users write the date on each doc according to [our style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/1807810577/Dates+times+and+numbers#Dates-and-years).

**Comment by jknipes** [comment]
@BSmolensky I would hate to start all over with Date Stamp instructions, and we would have to undo all of the date stamping published to date. At the moment, Confluence shows this for the // or / method:
![image](https://github.com/user-attachments/assets/8e2750ed-aee2-483a-9279-197369134d4a)

... and when published, it looks like this:
![image](https://github.com/user-attachments/assets/e675dac5-2aee-4e37-aff3-66c8526a8dd3)

**Comment by BSmolensky** [comment]
@jknipes - I understand your concerns. But there are 550+ pages on the PW. We have not date stamped the majority of pages yet. I think correcting this now would be the most prudent move. Incorrect date-stamp formatting does not have to be a Launch Blocking Issue. But our instructions to the rest of the Platform should adhere to our Style Guide.

**Comment by jknipes** [comment]
@BSmolensky please see updated issue description and tasks

**Comment by BSmolensky** [comment]
@jknipes - looks great!

**Comment by BSmolensky** [comment]
Completed search of Confluence for all locations where these instructions located. Identified relevant pages. Made copy of page. Determined scope of edit by making Inline comments throughout the doc. Preparing to edit.

**Comment by BSmolensky** [comment]
Half-way through my edit, I realized that we need to update our LB list. I created t[his ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/92290) for the work. I completed the work on that new ticket and I am now ready to resume my edit work.

**Comment by BSmolensky** [comment]
First draft of edit complete. Working on copy editing, finalizing formatting, and locking in the language.

**Comment by BSmolensky** [comment]
Edit complete. Changes moved from draft doc to original doc. Here is a [link to the updated Date Stamp document](https://vfs.atlassian.net/wiki/spaces/AP/pages/3065708550/Date+Stamp+New+Documentation+Requirement).

**Comment by BSmolensky** [comment]
All tasks complete. Acceptance Criteria met. Ticket is ready to close.

**Comment by jknipes** [comment]
Closing ticket as _Done_
