### ISSUE TITLE
Veteran Personal Information (Prefill Pattern)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#90904]
## Issue Description

The Veteran Personal Information page (prefill pattern) will be available to:
1. Authenticated Veterans with all info on file -- only these users will see the pre-fill pattern
   1. 21-22 info = first name, last name, date of birth, SSN
   2. 21-22a info = first name, last name, date of birth, SSN, branch of service

Content is dynamic based on:
   1. If the user is a **Veteran**, the `h2` should reference "Chapter 2".  If the user is a **non-Veteran** the `h2` should reference "Chapter 3".
   2.  If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 1: Veteran's Name (First, Middle Initial, Last)
   - Field 4: Veteran's Date of Birth (MM-DD-YYYY)
   - Field 2: Social Security Number (xxx-xx-xxxx)
   - Field 3: VA File Number (if applicable)
 
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    - Field 1: Veteran's Name (First, Middle Initial, Last)
    - Field 4: Veteran's Date of Birth (MM-DD-YYYY)
    - Field 2: Social Security Number (xxx-xx-xxxx)
    - Field 3: VA File Number (if applicable)
    - Field 6: Branch of Service (checkbox) 

URL: `/veteran-personal-information`

Previous paths: 
1. `/representative-contact` (Veteran users) 
2. `/claimant-contact` (non-Veteran auth with all info on file)
3. `/claimant-contact-mailing` (all other non-Veteran users)  

Next paths: 
1. `/veteran-contact` (auth Veterans with phone, email and mailing address on file)
2. `/veteran-contact-phone-email` (all other Veteran users, all non-Veteran users)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Auth" Designs (Prefill, for Veterans only)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-134715&t=76HE35X9xQ4MyVIC-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-214235&t=76HE35X9xQ4MyVIC-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153447&t=76HE35X9xQ4MyVIC-4)

These designs are _only_ for authenticated Veterans who have the following information in their Profile: first name, last name, date of birth, SSN.

<details><summary>Screenshots</summary>

<img width="221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmYrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b26cdb08031919b25ec08eb96b67d00567509a7a/image.png" alt="image.png" />

<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmorQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12c6e5a5963b28cbe0da22b6eb5517d131ebf7c1/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Veteran Personal Information page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Veteran Personal Information page has been implemented, with the specs outlined above.
