### ISSUE TITLE
Build functionality to put the Veteran’s answer for Terminally Ill on the 526 Overflow page

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#90902]
## Issue Description
Build functionality to put the Veteran’s answer for Terminally Ill on the 526 Overflow page

While Terminally Ill is sent to BGS, it's not making it's way to the generated pdf when leveraging Lighthouse's  /generatePDF endpoint. The generated pdf should include the Veteran's response for Terminally Ill.

---
## Tasks
- [ ] Verify Terminally Ill is sent to BGS
- [ ] Add claim notes to our request object
- [ ] quick unit test 
     - [ ] get request that has terminally ill included, make a FE request that looks like this, put this in test harness
     - [ ] in staging, look at the pdf to see if terminally ill is included
     - [ ] 

## Acceptance Criteria
- [ ] The generated pdf should include the Veteran's response for Terminally Ill
- [ ] BGS should still get the Terminally Ill response
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
