### ISSUE TITLE
[BE] SPIKE - get examples of appointment modalities in a stage payload and map the expected values

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#90911]
## Description
There are a few fields in conjunction with the `kind` field that determines appointment modality. We think that everything is coming back in the v1 VAOS endpoints. See this [reference doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/backend-logic.md#appointment-types). This ticket is to work with appointments to see what these appointments look like on stage, so we can send the fields to the frontend. 

[See this thread](https://dsva.slack.com/archives/CMNQT72LX/p1723497497705179)

## Tasks
- [ ] [BE] find possible 'kind' values
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] we understand modalities from VAOS endpoint

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/90911?planning-poker) with Zenhub @randomsync @kanchanasuriya

**Comment by brianseek** [comment]
> This ticket title and description is not right. We have done this work, I will update it to make sense.

Updated the title and description.

**Comment by kanchanasuriya** [comment]
**Phone Appointment Payload**
```
    {
      "id": "8b3582e7576e26efddafc19560d1e3b3de1e2cb9a0cf52022436057e782a7391",
      "identifier": [
        {
          "system": "Appointment/",
          "value": "523938333137353734"
        },
        {
          "system": http://www.va.gov/Terminology/VistADefinedTerms/409_85,
          "value": "983:17574"
        }
      ],
      "kind": "phone",
      "status": "proposed",
      "serviceType": "amputation",
      "serviceTypes": [
        {
          "coding": [
            {
              "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,
              "code": "amputation"
            }
          ]
        }
      ],
      "serviceCategory": [
        {
          "coding": [
            {
              "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,
              "code": "REGULAR",
              "display": "REGULAR"
            }
          ],
          "text": "REGULAR"
        }
      ],
      "reasonCode": {
        "text": "station id: 983GD|preferred modality: TELEPHONE|phone number: 2011001000|email: test@id.me|preferred dates:08/20/2024 PM|reason code:OTHER_REASON|comments:This is a request comment test 8/12 - LD "
      },
      "patientIcn": "1013120787V412913",
      "locationId": "983GD",
      "start": "2024-08-20T00:00:00Z",
      "minutesDuration": 0,
      "created": "2024-08-13T00:41:04Z",
      "requestedPeriods": [
        {
          "start": "2024-08-20T00:00:00Z",
          "end": "2024-08-20T00:00:00Z"
        }
      ],
      "cancellable": true,
      "extension": {
        "ccLocation": {
          "address": {}
        }
      }
    },
```

**Comment by kanchanasuriya** [comment]
**Community Care Appointment Payload**
```
    {
      "id": "e1f3e202d3a0614a043f2bb34205d3885e32a588536389d9eeddd63d63b14087",
      "identifier": [
        {
          "system": http://med.va.gov/fhir/urn/vaos/hsrm/id,
          "value": "16820"
        }
      ],
      "kind": "cc",
      "status": "fulfilled",
      "serviceType": "foodAndNutrition",
      "serviceTypes": [
        {
          "text": "foodAndNutrition"
        }
      ],
      "reasonCode": {
        "text": "test data for VAOSR-8434 - 1"
      },
      "patientIcn": "1013120787V412913",
      "locationId": "984",
      "created": "2024-08-07T15:21:00Z",
      "requestedPeriods": [
        {
          "start": "2024-08-27T16:00:00Z"
        }
      ],
      "contact": {
        "telecom": [
          {
            "type": "phone",
            "value": "8013239812"
          },
          {
            "type": "email",
            "value": beth.wodzinski@va.gov
          }
        ]
      },
      "preferredTimesForPhoneCall": [
        "Evening"
      ],
      "preferredLocation": {
        "city": "Naknek",
        "state": "AK"
      },
      "preferredLanguage": "Chinese",
      "cancellable": true,
      "extension": {
        "ccLocation": {
          "address": {}
        },
        "ccRequestedCancellation": false,
        "hsrmTaskId": "16820"
      }
    },
```

**Comment by kanchanasuriya** [comment]
**Clinic Appointment Payload**

```
    {
      "id": "b42005fad91b718dca9f62cd7fb4e186f38c5de7b2a7b1ae5f73ad5df1bc6535",
      "identifier": [
        {
          "system": "Appointment/",
          "value": "413938333134303333"
        },
        {
          "system": http://www.va.gov/Terminology/VistADefinedTerms/409_84,
          "value": "983:14033"
        }
      ],
      "kind": "clinic",
      "status": "booked",
      "serviceType": "moveProgram",
      "serviceTypes": [
        {
          "coding": [
            {
              "system": http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type,
              "code": "moveProgram"
            }
          ]
        }
      ],
      "serviceCategory": [
        {
          "coding": [
            {
              "system": http://www.va.gov/Terminology/VistADefinedTerms/409_1,
              "code": "REGULAR",
              "display": "REGULAR"
            }
          ],
          "text": "REGULAR"
        }
      ],
      "patientIcn": "1013120787V412913",
      "locationId": "983",
      "clinic": "1111",
      "start": "2024-08-23T16:00:00Z",
      "end": "2024-08-23T16:30:00Z",
      "minutesDuration": 30,
      "slot": {
        "id": "3230323430383233313630303A323032343038323331363330",
        "start": "2024-08-23T16:00:00Z",
        "end": "2024-08-23T16:30:00Z"
      },
      "created": "2024-08-09T00:00:00Z",
      "cancellable": true,
      "extension": {
        "ccLocation": {
          "address": {}
        },
        "vistaStatus": [
          "NO ACTION TAKEN"
        ],
        "preCheckinAllowed": false,
        "eCheckinAllowed": false,
        "clinic": {
          "physicalLocation": "CHEY",
          "phoneNumber": "723434",
          "phoneNumberExtension": "7345"
        }
      }
    },

```

**Comment by loripusey** [comment]
@kanchanasuriya can this be closed?

**Comment by kanchanasuriya** [comment]
We didn't get a response from appointments team from Thursday, Lori. Will reach out to them again today & see if it is possible to get the data today to close this task.

**Comment by kanchanasuriya** [comment]
**Atlas Appointment Payload**

```
{
			"id": "0fbc293324755816b690f11eab25c827b5e4fbea375ac06e8e9694205f95590e",
			"identifier": [
				{
					"system": "http://med.va.gov/fhir/urn/vaos/vvs/id",
					"value": "5c21ee08-7bc9-4cc3-b557-0fc543c40148"
				}
			],
			"kind": "telehealth",
			"status": "booked",
			"patientIcn": "1013124304V115761",
			"locationId": "983",
			"practitioners": [
				{
					"identifier": [
						{
							"system": "dfn-983",
							"value": "520647710"
						}
					],
					"name": {
						"family": "Poldass",
						"given": [
							"Aarathi"
						]
					},
					"practiceName": "Cheyenne VA Medical Center"
				}
			],
			"start": "2024-12-01T15:00:00Z",
			"end": "2024-12-01T15:30:00Z",
			"minutesDuration": 30,
			"created": "2024-03-01T18:52:19.23Z",
			"comment": "Testing ATLAS appt for VAOS team (Marcy)",
			"cancellable": true,
			"patientInstruction": "Medication Review\n\nAs part of your video visit, your provider will review all the medications, vitamins, herbs, and supplements you are taking\n(even items you get from a local store, another provider, or another VA clinic). Please have information about everything you\ntake available during the visit. Informing your provider about all these will help you get the best and safest care possible.\nRemember, it is your medications, your life. Play it safe by reviewing all your medications with your health care team.\n",
			"telehealth": {
				"url": "https://dev.care2.va.gov/vvc-app/?join=1&media=1&escalate=1&userType=guest&conference=VAC000003896@dev.care2.va.gov&pin=104039&aid=5c21ee08-7bc9-4cc3-b557-0fc543c40148#",
				"atlas": {
					"siteCode": "VFW-DC-20011-02",
					"confirmationCode": "075041",
					"address": {
						"streetAddress": "5929 Georgia Ave NW",
						"city": "Washington",
						"state": "DC",
						"zipCode": "20011",
						"country": "USA",
						"latitutde": 38.961979,
						"longitude": -77.027908,
						"additionalDetails": ""
					}
				},
				"group": false,
				"vvsKind": "ADHOC"
			},
			"extension": {
				"ccLocation": {
					"address": {}
				},
				"vistaStatus": [],
				"patientHasMobileGfe": false
			}
		},
```

**Comment by kanchanasuriya** [comment]
**Video Appointment Payload**

```
{
"id": "78355d9ddc15c539da9dcb6aa452f2f50ebc19b1a83b47796d89563a4795f8cd",
"identifier": [
{
"system": "http://med.va.gov/fhir/urn/vaos/vvs/id",
"value": "0703f6b2-a033-489a-bf54-1162e6f3019d"
}
],
"kind": "telehealth",
"status": "booked",
"patientIcn": "1013125218V696863",
"locationId": "983",
"practitioners": [
{
"identifier": [
{
"system": "dfn-983",
"value": "520647923"
}
],
"name": {
"family": "GONZALEZ",
"given": [
"ARTURO"
]
},
"practiceName": "Cheyenne VA Medical Center"
}
],
"start": "2024-09-06T14:00:00Z",
"end": "2024-09-06T14:20:00Z",
"minutesDuration": 20,
"created": "2024-09-03T14:58:22.623Z",
"cancellable": true,
"patientInstruction": "Video Visit Preparation\n\nThe Virtual Medical Room platform is simple to use and will only require an\napplication download for Apple and Android tablets or phones. Other devices will NOT require any software/application\ndownload. Because we want you to have the best possible video experience, we suggest the following:\n\nConnect to your video appointment from a location that is quiet, private, and well lit.\nMake sure to have a strong internet connection.\nIf using a cell phone, use a Wi-Fi connection so your data plan is not used.\nTo use a Virtual Medical Room, home devices must have a webcam and microphone. External cameras\nand microphones may be used if your device does not have a built-in camera or microphone.\nIf you will be using an iPad or iPhone, download the required iOS app in advance: VideoConnect.\nYou can connect to your Virtual Medical Room through the VA Video Appointment App using the link in your appointment\nconfirmation email.\n",
"telehealth": {
"url": "https://pexip.mapsandbox.net/vvc-app/?join=1&media=1&escalate=1&userType=guest&conference=VAC000056916@pexip.mapsandbox.net&pin=351792&aid=0703f6b2-a033-489a-bf54-1162e6f3019d#",
"group": true,
"vvsKind": "ADHOC"
},
"extension": {
"ccLocation": {
"address": {}
},
"vistaStatus": [],
"patientHasMobileGfe": false
}
},
```

**Comment by loripusey** [comment]
@kanchanasuriya is this going to roll over?

**Comment by kanchanasuriya** [comment]
I will close it by EOD.  We were not able to find sample data for the claim exam appointment.  Checking with the appointments team to confirm the attributes to differentiate claim appointments.

**Comment by kanchanasuriya** [comment]
**Claim Exam Appointment Data**
```
{
    "data": {
        "id": "9726bd1ca2a1cf349d6d56071140e02c3883fc275bde03dd3c44e855b19b3a67",
        "type": "appointments",
        "attributes": {
            "id": "9726bd1ca2a1cf349d6d56071140e02c3883fc275bde03dd3c44e855b19b3a67",
            "identifier": [
                {
                    "system": "Appointment/",
                    "value": "413938333132333035"
                },
                {
                    "system": "http://www.va.gov/Terminology/VistADefinedTerms/409_84",
                    "value": "983:12305"
                }
            ],
            "kind": "clinic",
            "status": "booked",
            "serviceType": "audiology",
            "serviceTypes": [
                {
                    "coding": [
                        {
                            "system": "http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type",
                            "code": "audiology"
                        }
                    ]
                }
            ],
            "serviceCategory": [
                {
                    "coding": [
                        {
                            "system": "http://www.va.gov/Terminology/VistADefinedTerms/409_1",
                            "code": "COMPENSATION & PENSION",
                            "display": "COMPENSATION & PENSION"
                        }
                    ],
                    "text": "COMPENSATION & PENSION"
                }
            ],
            "patientIcn": "1013678363V916823",
            "locationId": "983GC",
            "clinic": "945",
            "start": "2024-12-19T15:40:00Z",
            "end": "2024-12-19T16:40:00Z",
            "minutesDuration": 60,
            "slot": {
                "id": "3230323431323139313534303A323032343132313931363430",
                "start": "2024-12-19T15:40:00Z",
                "end": "2024-12-19T16:40:00Z"
            },
            "created": "2024-01-08T00:00:00Z",
            "cancellable": false,
            "extension": {
                "ccLocation": {
                    "address": {}
                },
                "vistaStatus": [
                    "FUTURE"
                ],
                "preCheckinAllowed": false,
                "eCheckinAllowed": false,
                "clinic": {
                    "physicalLocation": "FORT COLLINS AUDIO"
                }
            },
            "localStartTime": "2024-12-19T08:40:00.000-07:00",
            "serviceName": "C&P BEV AUDIO FTC",
            "friendlyName": "C&P BEV AUDIO FTC",
            "physicalLocation": "FORT COLLINS AUDIO",
            "location": {
                "id": "983GC",
                "type": "appointments",
                "attributes": {
                    "id": "983GC",
                    "vistaSite": "983",
                    "vastParent": "983",
                    "type": "va_facilities",
                    "name": "Fort Collins VA Clinic",
                    "classification": "Multi-Specialty CBOC",
                    "timezone": {
                        "timeZoneId": "America/Denver"
                    },
                    "lat": 40.553875,
                    "long": -105.08795,
                    "website": "https://www.cheyenne.va.gov/locations/Fort_Collins_VA_CBOC.asp",
                    "phone": {
                        "main": "970-224-1550"
                    },
                    "physicalAddress": {
                        "line": [
                            "2509 Research Boulevard"
                        ],
                        "city": "Fort Collins",
                        "state": "CO",
                        "postalCode": "80526-8108"
                    },
                    "healthService": [
                        "Audiology",
                        "EmergencyCare",
                        "MentalHealthCare",
                        "PrimaryCare",
                        "SpecialtyCare"
                    ]
                }
            }
        }
    }
}
```
