### ISSUE TITLE
Content Edit: Footer Ticket 92041 pt. 2

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#90917]
## User Story
As a VFS Team member, I need an up-to-date list of Platform data sources, so I can monitor performance on the Front End.

## Issue Description
In June 2023, there was a discussion in Slack ([reference](https://dsva.slack.com/archives/C04868KS69L/p1685557467880359)) where it was revealed that we no longer use **SpeedCurve** for web performance testing. 
Per [Footer Ticket 92041](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92041), There are still 3 pages referencing this tool in a table of data sources, and we need to remove this information.

### This Ticket is for the removal of SpeedCurve information from the **Platform Tools** page, **[Monitoring Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools#Platformtools-Monitoringtools)** section

![image](https://github.com/user-attachments/assets/b1bb1457-0a63-4949-b04f-e6cd2f70877e)

---
## Tasks
- [ ] Create copy of [Platform Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools) in Draft space
- [x] [Monitoring Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools#Platformtools-Monitoringtools) table should be updated to remove SpeedCurve information
- [ ] copy and paste the content of your page in the drafts space to the equivalent page in the Platform website content source
- [x] Prepare for deployment
 
## Acceptance Criteria
- [x] SpeedCurve information is removed from the page
- [x] Page is ready for deployment

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/90917?planning-poker) with Zenhub @BSmolensky @cmarion93 @laucon @taylojill

**Comment by taylojill** [comment]
Speedcurve removed from page, date stamp updated, no blockers, ready to publish.
https://vfs.atlassian.net/wiki/spaces/GS/pages/1872855066/Platform+tools
