### ISSUE TITLE
[CST] [ENG] Add sorting logic to place "In progress" claims above "Closed" claims in sort order

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#90931]
## Value Statement
**_As a_** Veteran
**_I want to_** be able to see my most relevant claims most easily in CST
**_So that_** I can easily get to the claims that I'm most likely to be interested in the status of or need to action on

---
## Background Context

[Original Slack thread](https://dsva.slack.com/archives/C056854SVT8/p1723648470864759)

Currently, there is no logic to sort "In progress" claims higher than "Closed" ones. If there are multiple claims that have the same "Moved to this step" date, we don't prioritize one over the other. But "In progress" claims are more important for the Veteran, so those should be above closed claims. 

We should add this to the existing logic so that if there are multiple claims with the same "Moved to this step on" date, the "In progress" claims are sorted above the closed claims in the claim cards list.

<img width="872" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05xQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5767bf0f3cb6bb6f555bc2bf4cf525a084a21df1/Screenshot%202024-08-14%20at%2011.11.57%E2%80%AFAM.png" alt="Screenshot 2024-08-14 at 11.11.57 AM.png" />

 
### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- N/A

### Enablement team (if needed)
@member of team

## Engineering 
Currently we sort claim cards for claims that are "In Progress" and have the `documentsNeeded` flag set to true above all other claim cards. "In Progress" claims cards that DO NOT have the `documentsNeeded` flag set to true can be interleaved with claim cards for closed claims, depending on the last updated date (i.e. the claim card for a claim that closed yesterday will show above a claim that is "In Progress", but was last updated last week)

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _If there are multiple claims with the same "Moved to this step" date, in progress claims should be sorted higher than closed claims_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] Claim cards for "In Progress" claims sort above "Closed" claims.
- [x] Claim cards for "In Progress" claims that have tracked items needing attention are still sorted above all other claim cards
