### ISSUE TITLE
[CST] Update claim title when claim_type is null from "claim for disability compensation" to something else

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#90936]
## Value Statement
**_As a_** Veteran
**_I want to_** see a clear and accurate claim card title
**_So that_** I can clearly understand which claims types are which in the CST claim list

---
## Background Context
- Currently we show "Claim for disability compensation" when the claim_type is `null`, which is why we see that claim card title. Our best guess is that certain EP codes aren't assigned a claim type so it returns `null`, but we would have to confirm with BGS.
- The problem is that normal disability compensation claims are labeled "Claim for compensation" so this label of "Claim for disability compensation" creates confusion, since true disability compensation claims are not labeled that way.

## Design
- We should ask content team what to return in the case of `null` value for claim_type. Maybe "Unknown" or something similar.

## Enablement team
- @jstrothman 

## Engineering 
- Todo: How often is null returned for claimType from BGS?
  - Potential Follow-Up: Why is null return for claimType from BGS?
- Frontend code:
  - If claimType is 'Death' then title is 'Claim for expenses related to death or burial'
  - If claimType is null then title is 'Claim for disability compensation'
  - If claimTypeCode is a specific code then 'Claim for request to add or remove a dependent'
  - If claimType is anything else (including Compensation) then 'Claim for [claimType]'
```
export function getClaimType(claim) {
  if (claim?.attributes?.claimType) {
    const { claimType } = claim.attributes;
    return claimType === 'Death'
      ? 'expenses related to death or burial'
      : claimType;
  }
  return 'Disability Compensation';
}

export const generateClaimTitle = (claim, placement, tab) => {
  // This will default to 'disability compensation'
  const claimType = getClaimType(claim).toLowerCase();`
  const isRequestToAddOrRemoveDependent = addOrRemoveDependentClaimTypeCodes.includes(
    claim?.attributes?.claimTypeCode,
  );
  ...
  const addOrRemoveDependentClaimTitle = 'request to add or remove a dependent';
  ...
  default:
      return isRequestToAddOrRemoveDependent
        ? sentenceCase(addOrRemoveDependentClaimTitle)
        : `Claim for ${claimType}`
``` 

## Out of scope
- In order to more fully solve this problem, we should ask BGS why the `null` value is getting returned and perhaps reclassify these claims so that there is no `null` value. 
- But as part of this ticket we should just figure out how often this is happening. 

## Open questions
- How often do claims get returned with a null value?
- What EP codes are associated with the null value? 

## Tasks
- [ ] _Figure out how many claims are showing `null` value for claim_status_type in production_
- [ ] _Getting an exhaustive list of EP Codes that have a null value for claim_type_
- [ ] _Update title from "Claim for disability compensation" when value is `null` to whatever the content team recommends_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] BGS associates an EP Code with the appropriate label and sends it to LH

**Comment by jstrothman** [comment]
Example screenshot from vets.gov.user+14@gmail.com


![2024-08-20-compensation-claims-varied-step-total](https://github.com/user-attachments/assets/84965b47-1ff7-4d35-be20-f9d1a7d974ca)

**Comment by pmclaren19** [comment]
@skylerschain did you ever get a recommendation from content on this one?

**Comment by jstrothman** [comment]
I think we should make the effort to find out more about what these claims that come back `null`. 

Do we already have data for the first two tasks in the Task list?
Once that's been done and we know if this is a production issue vs just a staging issue:
Could one of you reach out to BGS to describe the problem and ask if they can provide information about the scenarios that would return a null value for claim_status_type?

**Comment by pmclaren19** [comment]
Hey @jstrothman taking a look at your comment now. There are more claims on this user then when you took the screen shot but looks like most of them have the claimType of `Compensation`. Three of them (claimIds: 600596284, 600046147, 276161) have the claim type of `Dependency`. One of them (claimId: 270907) has the claim type of `Eligibility Determination`.

The 8 step and 5 step process depends on if the flipper `cstClaimPhases` is on (which it is on for staging) and if the claim type code is for a disability compensation. We determined a list with you a while back so it compares the claimTypeCode with that list and if its on the list then it shows 8 steps instead of 5.

**Comment by pmclaren19** [comment]
@skylerschain maybe you can share more information on this since you wrote the ticket? Do you have an example where this is occurring? Also there is no claim status type field so I'm not sure what you are referring to. Can you please clarify?

**Comment by samcoforma** [comment]
Discussed in parking lot, it appears that when `claim_type` is `null` it shows "Disability compensation claim".

[Local dev example](http://localhost:3001/track-claims/your-claims/600590762/status)

Look at this code:

```export function getClaimType(claim) {
  if (claim?.attributes?.claimType) {
    const { claimType } = claim.attributes;
    return claimType === 'Death'
      ? 'expenses related to death or burial'
      : claimType;
  }
  return 'Disability Compensation';
}```

**Comment by samcoforma** [comment]
Updated the ticket to reference `claim_type` instead of what it used to incorrectly say `claim_status_type`

**Comment by pmclaren19** [comment]
@jstrothman discussed this issue with @skylerschain. We are thinking that our fix for this one will be anything with a null `claimType` will show the following:
|CST Component to be changed | Current | Change |
| ------- | ----------- | ---------------- | ----- |
| Claim List Section Header | Claim for disability compensation | Claim for Unknown | 
| Claim Page Header | Your disability compensation claim | Your unknown claim |
| Claim Page Breadcrumb | Status of your disability compensation claim | Status of your unknown claim  |
| Claim Page Tab Title | `Status of November 21, 2024 Disability Compensation Claim | Veterans Affairs` | `Status of November 21, 2024 Unknown Claim | Veterans Affairs` |

Please let us know if you are okay with this change. 

Additionally investigating into one of these records that dont have a claim type I see that the `claimTypeCode: 290HE7131R`. Googling it looks like this corresponds to Healthcare Eligibility - 7131 Review. Any idea why this wouldnt have a claim type? If not, we could reach out to BGS and ask why? Let me know if you want us to further investigate this issue.

**Comment by jstrothman** [comment]
I'm not in favor of referring to the claims as "unknown" as I think it diminishes confidence in VA. I'll read through the details you've put together in this issue and make a recommendation.

**Comment by pmclaren19** [comment]
Sounds good @jstrothman please let me know if you have any other questions while reviewing! 
Here are some additional screenshots to help!

![Image](https://github.com/user-attachments/assets/26014286-2304-41a8-8f88-544d7c2f4f2f)

![Image](https://github.com/user-attachments/assets/054eab06-c2b4-40a8-9aba-ef9d33e099f7)

**Comment by pmclaren19** [comment]
@jstrothman @jacobworrell Hey guys worked with @Sam Cormier and we added 2 new widgets to the [Claim Status Tool Statistics dashboard](https://vagov.ddog-gov.com/dashboard/p2a-9ii-9hz/claim-status-tool-statistics?fromUser=false&refresh_mode=sliding&from_ts=1740076260325&to_ts=1742491860325&live=true) in Datadog! Looks like in the last month we have had around 3.84k claims with a null claim type.  Please view the dashboard widgets named `Top 100 Claim Type Codes with a Null Claim Type` and `Claim Type Codes with a Null Claim Type`. Please let me know if you have any questions!

**Comment by jacobworrell** [comment]
After speaking w/ Andrew and team, best options for 960 seems to be to suppress those claim types. For 290s, best option is to determine unique claim type labels for each subtype. Moving into "new tickets" for refinement.
