### ISSUE TITLE
Remove spaces in direct deposit account number for Form 526 submission to LH

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#90952]
## Issue Description
We found this when testing previously passing EVSS submissions against the Lighthouse validate endpoint. Any accidental spaces will block submissions from going through with Lighthouse.

---
## Tasks
- [x] Verify account number has no spaces
- [x] quick unit test 
     - [x] get request with spaces in accoun tnumber, make a FE request that looks like this, put this in test harness
     - [ ] in staging, look at the pdf to see if account number is correct

## Acceptance Criteria
- [x] The generated pdf should include the Veteran's response for account number
- [ ] 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
