### ISSUE TITLE
Appoint a Rep - Cross Accredited VSOR - User Test - Analysis

### ISSUE THREAD

**Issue by jfinnerty13** [department-of-veterans-affairs/va.gov-team#90965]
## Issue Description
Interviews and user test of the 21-22 with cross accredited VSORs.

## Tasks
- [ ] Analyze interview findings
- [ ] Clean-up transcripts

## Acceptance Criteria
- [ ] All tasks complete
