### ISSUE TITLE
EVSS PCIU Migration: Step 2: Forms

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#90976]
## User Story
As the developers responsible for backend work on the EVSS PCIU migration,
We want to create the V3::ProfileInformation Services configuration and responses,
So that we can perform the necessary migration of PCIU from the current EVSS environment.

## Issue Description
We need to go through the existing forms on [this page](https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/form_profile_mappings) and find all instances of ContactInformation and change those references to ServiceInformation

## Tasks
- [ ]  Identify forms that contain ContactInformation, list forms here:
    - [ ]  
- [ ]  Change reference to "ContactInformation" to "ServiceInformation" on all forms
- [ ]  Test forms with 10-10EZ team

## Success Metrics
- [ ]  ContactInformation reference has been removed and replaced by ServiceInformation

## Acceptance Criteria
- [ ] All forms that reference ContactInformation has been removed and replaced by ServiceInformation on [this page](https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/form_profile_mappings) of forms. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
Unnecessary dupe.
