### ISSUE TITLE
[0 pts left] [FE] - Add past appointments features to details page

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#90975]
## Description 
Create or use existing feature flag for this work. When the feature is on and its an in-person appointment, call the claims endpoint. Based on the result determine if we should add the action link and/or the Travel reimbursement content block. The action link only shows if there is no claim. When there is no claim the content block should show a count down of how many days are left to file. If there is a claim the content block should link to it. 

[Sequence Diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/submit-claim/integration/work-streams.md)

question: What do we do if the api call fails?

## Wireframes
- [Wireframes](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2135-3&t=EB4SQXyZ7hTp0tFj-0)

## Tasks
- [ ] create action link
- [ ] create Travel reimbursement content block
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@benbrasso-agile6 @cgednalske are these the correct current wireframes? Is this ready for FE to work on?
cc: @brianseek @wullaski

**Comment by benbrasso-agile6** [comment]
Yes, correct wireframes. 

It's ready, but we will be doing a research study for these. E.g., actions on appt detail pages. 

Tough to say whether to complete these or wait for the results of that study. It will be unmoderated study, so it will be quicker.

**Comment by loripusey** [comment]
Perhaps it will give FE time to "get acquainted" with the Appointments code base; just want to make sure FE knows that there may be changes
cc: @brianseek @wullaski

**Comment by benbrasso-agile6** [comment]
I won't be at stand up today, maybe see what Christina and FE think is the best approach.

**Comment by loripusey** [comment]
there is no stand up today (planning day); it's up to @brianseek and @wullaski

**Comment by benbrasso-agile6** [comment]
I see a comment from bring about api Call fails. We could create a ticket for UX to create that wireframe. Should be a small pointer that can be completed in this upcoming sprint.

**Comment by benbrasso-agile6** [comment]
Yes; def think there will be small-ish design changes as a result of what we're going to test in research.

**Comment by wullaski** [comment]
I started a draft PR where the claim endpoint is called on the front-end. There's a new plan to move that call to the back-end and get the data we need along with the appointment data for past appointments. More info in this [thread](https://dsva.slack.com/archives/C05Q9HH47PS/p1724874648211019)

**Comment by loripusey** [comment]
@wullaski Look at and refine this ticket (or create additional ones)
