### ISSUE TITLE
[FE] - Create mock api for travel claim status endpoint

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#90973]
## Description
We need a mock api do to the travel claim for past appts. work. We don't know what it will look like yet, but we can make a guess and update it later. We can also bounce it back and forth with Kevin if he has thoughts. 

## Tasks
 - Determine path (ask BE Kevin)
 - create a sample payload (success no claim)
 - create a sample payload (success existing claim)
 - create an api failed response

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings
