### ISSUE TITLE
Claimant Personal Information (Prefill Pattern)

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#90986]
## Issue Description

-------
⚠️ **Note** ⚠️ 
This work originally began in https://github.com/department-of-veterans-affairs/va.gov-team/issues/66104, before we broke this into a separate ticket.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/66104 was reserved for the text-input patter only.

Rendering the auth state is wrapped up in the same issue as Claimant Contact Information (https://github.com/department-of-veterans-affairs/va.gov-team/issues/86380). Need to figure out why formData.veteran is empty for test users.

-------

The Claimant Personal Information page (prefill pattern) will be available to:
1. Non-Veteran users ONLY
2. Authenticated users that have **all of the required information** (first name, last name, date of birth) in their profile.
3. 21-22 and 21-22a forms.

Content is dynamic based on:
   1. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page.  If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

The information collected on this page will be routed to the forms as follows:
- [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
   - Field 10: Claimant's Name (First, Middle Initial, Last)
   - Field 11a: Claimant's Date of Birth (MM-DD-YYYY)
 - [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    - Field 10: Claimant's Name (First, Middle Initial, Last)
    - Field 11: Claimant's Date of Birth (MM-DD-YYYY)

**URL**: `/claimant-personal-information`

**Previous paths**: 
1. `/claimant-relationship` 

**Next paths**: 
1. `/claimant-contact` (non-Veteran auth with all required info on file)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## "Auth" Designs (Prefill)
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-134715&t=76HE35X9xQ4MyVIC-0&scaling=min-zoom&page-id=1475%3A128342&starting-point-node-id=1500%3A153719&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-214235&t=76HE35X9xQ4MyVIC-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153447&t=76HE35X9xQ4MyVIC-4)

**Disclaimer**: We only designed the authenticated experience for a Veteran user.  In this case where we have a non-Veteran claimant that sees this prefill pattern, **we'd only need to display the first name, last name and date of birth**.  

SSN, Branch of Service and VA File Number are **not required** for the prefill experience in the Claimant section of the 21-22 and 21-22a.

<details><summary>Screenshots</summary>

<img width="221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmYrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b26cdb08031919b25ec08eb96b67d00567509a7a/image.png" alt="image.png" />

<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmorQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12c6e5a5963b28cbe0da22b6eb5517d131ebf7c1/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Claimant Personal Information page (prefill pattern) based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Claimant Personal Information page (prefill pattern) has been implemented, with the specs outlined above.

**Comment by oddball-lindsay** [comment]
Prefill patterns have changed, this ticket is no longer relevant
