### ISSUE TITLE
EVSS PCIU Migration: Forms review

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#90980]
## User Story
As the developers responsible for backend work on the EVSS PCIU migration,
We need VFS teams to test their forms,
So that we can validate the migration of PCIU from the current EVSS environment.

## Issue Description
The table below was created by looking at the [form_profile_mappings](https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/form_profile_mappings) in vets-api and finding all instances of forms using `contact_information`. Almost all forms (33 of them) use `contact_information` for some of their fields, but there is considerable overlap, so we don't need to test all 33 of the forms. Two forms cover all fields, `10-7959` and `21-0966` (but I'm also sharing an alternative to `10-7959` in case that one one is easier to test).

**`10-7959`**
```yaml
    street: [contact_information, address, street]
    street2: [contact_information, address, street2]
    city: [contact_information, address, city]
    state: [contact_information, address, state]
    country: [contact_information, address, country]
    postalCode: [contact_information, address, postal_code]
  phone_number: [contact_information, us_phone]
  email_address: [contact_information, email]
```
**`28-8832` (aka `27-8832`?) (alternate to the one above. Either can be used to test these fields)**
```yaml
claimantAddress:
  country: [contact_information, address, country]
  street: [contact_information, address, street]
  street2: [contact_information, address, street2]
  city: [contact_information, address, city]
  state: [contact_information, address, state]
  postalCode: [contact_information, address, postal_code]
claimantPhoneNumber: [contact_information, us_phone]
claimantEmailAddress: [contact_information, email]
```
**Form `21-0966` covers the remaining fields**
```yaml
  mobilePhone: [contact_information, mobile_phone]
  homePhone: [contact_information, home_phone]
  email: [contact_information, email]
  address: [contact_information, address]
```
| Form     | GitHub Team                           | Contacted | Slack channel |
| -------------- | ------------------------------------ | ------------------ | ---- |
| `10-7959c`       | [IVC CHAMPVA](https://github.com/orgs/department-of-veterans-affairs/teams/champva-engineering)                            | | #ivc-forms |
| `28-8832`  (aka `27-8832`?)       | [benefits-non-disability](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-non-disability)            | | #benefits-non-disability |
| `21-0966`| [platform-va-product-forms](https://github.com/orgs/department-of-veterans-affairs/teams/platform-va-product-forms) | | #veteran-facing-forms |

Form numbers can be searched here: https://www.va.gov/find-forms

## Tasks
- [x]  Contact teams to test prefill functionality for their forms (we're specifically interested in the contact info fields being prefilled).
- [x] Communicate that the flipper for this functionality needs to be on in Staging for accurate testing (test the flipper on/off scenarios for a user and make sure the data is prefilled in each scenario).
- [x] Put instructions for testing locally and in staging

## Success Metrics
Two forms are tested.

## Acceptance Criteria
- [x] All contact information on forms `21-0966` and either `28-8832` or `10-7959` was successfully prefilled using a test user in Staging.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jwoodman5** [comment]
We are waiting for contact information integration to wrap so we can complete this. Carrying to next sprint.

**Comment by RachalCassity** [comment]
Testing will continue after V3/AddressValidation has been deployed to staging.

**Comment by LindseySaari** [comment]
@rjohnson2011 Reach out to the benefits team around advice for how to test their forms. (Test users, data, etc)

**Comment by rjohnson2011** [comment]
Reached out to platform-va-product-forms re: testing form 21-0966. Got this reply:
```
Tricia Baker
  Thursday at 1:19 PM
This form has several paths - if you are the Veteran and we can find the ICN then we use the Intent API and don’t really ask for any information just show the existing Intent expiration date or create a new one depending on what they select.
If they are a dependent or third party, I don’t believe we prefill any of the data but Robert can verify


Robert Hasselle
  Thursday at 1:50 PM
hi, the 21-0966 form is a bit unique in this approach.
While homePhone, mobilePhone, and email are part of that [prefill ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/form_profile_mappings/21-0966.yml), they won't actually appear anywhere in the form. We instead skip all relevant pages in the UI and just show them a "here's your data" page (which doesn't currently show any of the above 3 fields, more like full name, ssn, dob).
Although we don't show them those 3 prefill fields homePhone, etc... we just send it a long when they press submit if they already had it behind the scenes.
So if we want to update this to give the user the opportunity to see and correct these fields, then we would need a ticket for this.  I think this is a unique problem for 0966, and other forms may not have this issue.


Robert Hasselle
  Thursday at 1:56 PM
As for just the original question about ensuring that prefill actually worked based on new changes, we won't get any UI indication it worked (currently), so to test we'll need to press submit, and look at the network request, and see if those fields are properly sent in the payload, then we know prefill behind the scenes worked correctly. (edited)
```

Reached out to IVC CHAMPVA re: testing form 10-7959c. Got this response:
```
Michael Clement
Hello, Ryan! We have not actually set up the frontend of that form to accept the contact info via prefill, so while we do have a mapping in vets-api, it's not actively used (there are some unanswered questions about prefill on that form, so that functionality has been on hold).
I'd be happy to try out the flipper scenarios, but I'm not sure if it'll be useful to you given the form's state. Just let me know!
```

**Comment by rjohnson2011** [comment]
For benefits-non-disability:

Sean Midgley
 Looking at the pre-filled data only with both flippers ON and then both flippers OFF in staging makes no difference to the data being pre-filled the JSON is the same. No difference in data
{
    "fullName": {},
    "claimantAddress": {
      "view:militaryBaseDescription": {},
      "country": "USA",
      "street": "PSC 817 Box 300",
      "city": "FPO",
      "state": "AE",
      "postalCode": "09622"
    },
    "claimantPhoneNumber": "3453453455",
    "claimantEmailAddress": "vets.gov.user+99@gmail.com",
    "veteranInformation": {
      "fullName": {}
    }
  }
