### ISSUE TITLE
Update Moderated Production Testing Playbook

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#90995]
## Issue Description
As a T-REX team member, I want our Moderated Production Testing (MPT) Playbook updated with what we learned during the Toxic Exposure MPT sessions so that we can improve this for next time.

Let's make this so routine to run that anyone can do it, adding additional information, links and context so that a non-technical person could run sessions if needed. It's okay for this to be highly task oriented.

---
## Tasks
- [ ] Update the playbook

## Acceptance Criteria
- [ ] An engineer could use the Playbook to run an MPT session
- [ ] Learnings from Toxic Exposure 1.0 MPT are included in the document
- [ ] Playbook is published in the DBEX Github document repo

## Additional Information
Micro Retro for Moderated Production Testing

- Can we record these session in the future? It can be hard to remember every detail of the submission when troubleshooting and this causes some uncertainty around what the Vet submitted questions and a longer troubleshooting time
- Ensure that the async jobs we expect to run have all completed before turning off the Production Tester toggle for the Vet. When turning this off too shortly after the submission, can cause some uncertainty knowing if the async jobs ran correctly.
- Does the Flipper admin log somewhere? Knowing the times where the value has changed is helpful when troubleshooting.
- Add time between each Moderated Production Testing sessions, so that we have time to debrief between each session
- Create separate threads for each Moderated Production Testing session. When all messages are combined, it can be difficult to know which topics refer to which sessions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mchae-nava** [comment]
https://docs.google.com/document/d/1p09g0NSFT3fC35eO5RIdVBMYxuo_rHnTS6ECPJtVyPQ/edit?usp=sharing

Playbook updated and uploaded to team drive
