### ISSUE TITLE
Create BDD test case for editing service date and exiting BDD flow

### ISSUE THREAD

**Issue by pacerwow** [department-of-veterans-affairs/va.gov-team#90994]
## Issue Description
As an engineer, I need to make sure that a Veteran who is in the BDD flow can successfully change their exit date and leave the BDD flow without error so that they feel confident that any changes they make are saved, where needed they can navigate the form without error, and that the application is submitted with the correct information.

---
## Tasks
- [ ] Figure out how to trigger BDD flow
- [ ] Determine how a Veteran would exit BDD flow
- [ ] Write a test case that covers a Veteran entering and exiting BDD flow
- [ ] Execute the test case
- [ ] Check the Veteran's submission to ensure the claim isn't BDD
- [ ] If there are errors discovered, create a ticket to address those errors

## Acceptance Criteria
- [ ]  Given a test case doesn't exist for a veteran exiting the BDD flow
- [ ]  And Veterans expect to be able to edit and save changes the make to their application
- [ ]  Then a test case should exist to ensure this feature works as expected for the Veteran
- [ ]  And it should cover a case when the exit date is changed from a future date to a past date
- [ ]  And when Veterans make this change from the Veteran Information page
- [ ]  And when Veterans hit the back button to make this change from a page past the Veteran Information page
- [ ]  And be tested by the team to ensure the feature is working as the Veteran expects it to
- [ ]  Test is built in Test Rail

## Additional Context & Information
During Moderated Production Testing, something happened (needing to exit BDD) that we didn't intend to happen. Part of that concern was that we were unclear if this logic works as desired, so we just want to be sure that this works as expected. BDD claims represent 17.28% of monthly claims, conversely, non BDD claims represent 82.72% of monthly claims.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] When a Veteran changes their service period from a future date to a past date, the claim is not considered BDD
- [ ] When service period date is set to the past, the UX should be a non-BDD UX
- [ ] "Active duty" is not set to "yes" on all downstream systems
- [ ] Active service period is set to the past on the generated 526 pdf
- [ ] No validation errors occur as a result of changing the service period dates

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bacitracin** [comment]
Test lives under the BDD folder https://dsvavsp.testrail.io/index.php?/cases/view/101757
