### ISSUE TITLE
Enhance production tester feature toggle to prevent EP merges

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#90990]
## Issue Description
During production testing of the TE release, we avoided doing EP merges with our users purely by chance. This ticket is to extend the existing functionality of the `disability_compensation_production_tester ` flipper flag to explicitly prevent them.

[This is the point on code](https://github.com/department-of-veterans-affairs/vets-api/blob/75ac1bd0c2cca98af2ddc8cda93b9c7cbe7b060e/app/models/concerns/form526_claim_fast_tracking_concern.rb#L153)  where the feature flag `disability_526_ep_merge_api` currently gates the functionality. This fix should simply require another check after this line to see if the production tester flag is enabled or not.

---
## Tasks
- [ ] 

## Acceptance Criteria
- [ ] EP merge functionality disabled when the `disability_compensation_production_tester` is enabled for a particular user
- [ ] Unit tests
- [ ]
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
