### ISSUE TITLE
Announce Staging Review requirement changes to VFS team

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91003]
## User Story
As a VFS team member going through Staging Review, I want to know what is required of my team prior to the review so that I can be sure we share everything as requested.

Assignee:
Peer Reviewer:

## Description
In tickets #88107 and #88140, we refined our Staging Review requirements and Staging Review required artifacts. Even though the changes made to both the artifact list and SR requirements are minimal and really shouldn't have much impact to VFS teams, we do think it is worth communicating these changes for VFS team awareness. The changes remove some ambiguity with regards to what is required and what is optional, and help provide better clarity to teams.

The purpose of this ticket is to create a change history post for Platform Website and a change announcement for Slack.

## Impacted Artifacts
Change history

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] We have notified VFS teams via Slack and our change history page of the required Staging Review artifacts and the changes to our Staging Review requirements

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket has been absorbed into #89357 and is no longer applicable. Closing.
