### ISSUE TITLE
Train Governance team members on TestRail

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91007]
## User Story
As a Governance team member, I want to gain access to and learn how to use TestRail so that I can verify all required artifacts have been submitted for a Staging Review.

Assignee: @it-harrison 
Peer Reviewer: @KKitagawa-Bosch  @erinrwhite @briandeconinck @allison0034 

## Description
In ticket #88140, we clarified which artifacts are absolutely required for Staging Review. If VFS teams do not provide said artifacts, their Staging Review will be cancelled or postponed. Since this list of required artifacts includes a couple QA artifacts, such as the Test Plan and Regression Test Plan, all Governance team members need to be able to verify that the artifacts have been provided. Test Plans and Regression Test Plans are often provided via TestRail.

The purpose of this ticket is to ensure all Governance team members have access to TestRail and have been trained to use the tool.

## Tasks
- [ ] Request access for Governance team members per [TestRail access](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-TestRailaccess) guidance.
   - Note: TestRail accounts are limited. It may be advisable for Governance team members to all share 1 TestRail account, however please confirm with Platform Support
- [ ] Set up training session to walk through the various use cases of TestRail, such as validating Test Plan, Regression Test Plan and Traceability Reports.
   - [TestRail Guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/testrail-guide) on Platform Website may be helpful

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team members (excluding PM) all have verified their access to TestRail
- [ ] Governance team members have received some training in TestRail and will be able to verify VFS team required QA artifacts have been created

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
Training session held on 9/23. It was determined in the session that due to the current state of the QA Standards, it does not make sense for Governance team members on support to verify if QA artifacts are provided prior to the Staging Review in order to determine if the SR should continue as the presence of the artifacts is how QA standards are currently verified. Having Governance team members verify artifacts prior to the SR would duplicate work that @it-harrison is doing for the SR itself.

The QA Specialist on Governance will remain the only individual with TestRail access as it is not necessary for the full team to have access. 

This ticket can be closed although not all AC was met.
