### ISSUE TITLE
[UX] Resources: OCTO Product team POC

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#91035]
## Issue Description

Being a part of a larger collective, the team spends a good amount of time locating adjacent teams to connect with for desk research, sharing notes, and coordination. 

UX has a mural for a collective resource (UX Landscape) that this resource can add. 

## Resources
- [CX Catalogue](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690222373907/c3f581ef4e016b5644ce4e3097d0c15c41cb1a8e?sender=ubf5503bf47b6eb1e92730053) (for OCTO team)
- [UX Landscape](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697039977149/b8a5ea90748703093cdcb405b84463e515cfea2a?sender=ubf5503bf47b6eb1e92730053)

---
## Tasks
- [x] Determine all OCTO product teams
- [x] Provide the team's product folder (mostly Github)
- [x] Provide the team's public Slack channel
- [x] Provide the team's Figma folder if applicable
- [x] Demo/inform the resource to the team/PM

## Acceptance Criteria
There is a place to reference all of the OCTO product team for when the team needs to do desk research, connect with an adjacent team, or coordinate a larger effort.
