### ISSUE TITLE
Sentry Error: "expect the argument to be a String, got Hash" - 674 manual submission

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#91034]
## Issue Description
[Sentry exception error](http://sentry.vfs.va.gov/organizations/vsp/issues/267110/?environment=production&project=3&query=&statsPeriod=14d): `Unable to create_note: expect the argument to be a String, got Hash ({:clm_id=>"110259379", :txt=>"Claim set to manual by VA.gov: This application needs manual review because a 674 was submitted."}): try 1 of 3"`
List of all Sentry instances [can be seen here](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&project=3&query=%22expect+the+argument+to+be+a+String%22&statsPeriod=14d).

The code is crashing and no monitor is going off.

---
## Tasks
- [ ] Determine why code is crashing and monitor is not alerting

## Acceptance Criteria
- [ ] Code does not crash
- [ ] Monitor alerts as expected
---

**Comment by evansmith** [comment]
I have a theory that this may be related to what @tfink419 was investigating and is caused by this line ` log_message_to_sentry(message, :info, {}, { team: 'vfs-ebenefits' })` in the create_note method. message is a sliced hash wtih clm_id and txt. cc @sanjabaj2 @mjknight50 @tblackwe

**Comment by evansmith** [comment]
This has been deployed to production and has had no errors in the past hour since deployment.
