### ISSUE TITLE
[CDP] Use new compositeDebtId

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#91030]
## Issue Description
Moving away from using Filenumber, BE added a unique id `compositeDebtId` that we can now leverage in the URL for debt details

Backend implementation
- **(ticket) Add compositeDebtId to debts payload [#90865](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/90865)**
- **[BE PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18061)**

## Tasks
- [x] Identify all references to URLs using file number
- [x] Replace all identified references
- [x] Update associated tests and mock data

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [x] Debt details no longer uses filenumber in the URL 
- [x] All tests are passing

## Testing
- [x] Confirm new URL 
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points

**Comment by Dr-Pongo** [comment]
No new issues cropping up in Sentry, closing out the ticket and we can manage any issues as bugs after this!
