### ISSUE TITLE
Prepare Documentation for UX/UI Work for Preview Environments

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#91032]
## Description
Based on the findings of our Milestone 2 Usability Testing, we know that there is room for improvement with the current user flows and overall User Experience. In order to address that, we would like to go through a full UX Design process. Some of this work can be done internally on the team, but some of the design work will need to be done by a UX Designer.

This ticket is intended to collect and prepare information that will equip and enable a UX Design resource to understand the user needs, functional requirements, anticipated user flows, and desired look/feel, in order to effectively design an effective UX/UI.

---
## Tasks
- [x] Based on past research, define User Types - Including goals, needs and desired behaviors
- [x] Define the known functional requirements of each user type
- [x] Create draft user flows for each user type
- [x] Create a proposed user flow that incorporates the needs of each user type
- [x] Detail the expected interactions/interface requirements & features in each of those screens
- [x] Review internally w/ the team for any suggested tweaks
- [x] Review w/ Platform Design Lead

## Acceptance Criteria
- [x] Proposed user flows have been defined and reviewed
- [x] Proposed interaction requirements have been defined and reviewed
- [x] Mural documentation is ready for handoff to a UX Designer

**Comment by JoeTice** [comment]
Mural Board is here - https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722550950686/c0b1e9f31ea5fbfe83adafdfed2453a0fd4dd9e1?sender=u4d12c8e887ecbbf46bb48152

Has been sent out for review by PRT and Platform Design Lead
