### ISSUE TITLE
Build and publish Creating an Account page into Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#91037]
## Issue description
This content needs to be translated as part of the sign in transition work:

https://www.va.gov/resources/creating-an-account-for-vagov/
- Spanish only

---
## Tasks
- [x] Send materials for translation to State Dept. (Randi)
- [x] Build out Spanish translation of live pages (Victoria)
- [x] Copy edit pages in Drupal (Sara)
- [x] Verify changes are live and send to State Department for QA (Sara, Victoria)
- [x] PW publishes with Spanish toggle (Randi)

## Acceptance Criteria
- [x] Updated content is live on the site

**Comment by RLHecht** [comment]
@moviedosoco Here's the content to build out in Drupal:

[LS-2024-0122945-SPA-FINAL_Creating an account for VA.gov_for translation.docx](https://github.com/user-attachments/files/16678818/LS-2024-0122945-SPA-FINAL_Creating.an.account.for.VA.gov_for.translation.docx)

**Comment by moviedosoco** [comment]
@RLHecht The Spanish page _Creación de una cuenta para VA.gov_ is built in Drupal.

@saratorres2 This page is ready to be reviewed and published https://prod.cms.va.gov/resources/creacion-de-una-cuenta-para-vagov
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=71958

You will notice in prod that it says there´s a broken link. It is the second CTA (_Cree una cuenta de ID.me_) that redirects to an external site of ID.me. I have tested it from the preview and it works. I'm not sure if once published it will also display correctly. 
This is the link that it suppose to go in _Cree una cuenta de ID.me_ : 
https://api.id.me/es/registration/new

Also, as a reminder, once the Spanish web pages are published, we will change the English links to their Spanish versions.

Let me know if I can be of any help.
Thank you!

**Comment by saratorres2** [comment]
@moviedosoco This page is published; we're waiting for it to go live.

**Comment by moviedosoco** [comment]
@saratorres2 Perfect, thank you.

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2 The live Spanish page was emailed today to State for QA:

https://www.va.gov/resources/creating-an-account-for-vagov-esp/

**Comment by RLHecht** [comment]
@moviedosoco Here is the QA back from State. Please make any changes needed and then we can republish. Thanks!

[LS-2024-0122945-LQA Notes-es_v1__Creating an account for VA.gov.docx](https://github.com/user-attachments/files/16993977/LS-2024-0122945-LQA.Notes-es_v1__Creating.an.account.for.VA.gov.docx)

**Comment by moviedosoco** [comment]
This page was sent back for translation as the English page has new updated content.

**Comment by RLHecht** [comment]
@moviedosoco here's the new translation back from State:

[SPA-FINAL_Creating an account for VA.gov_UPDATED CHANGES_for translation_09132024.docx](https://github.com/user-attachments/files/17131059/SPA-FINAL_Creating.an.account.for.VA.gov_UPDATED.CHANGES_for.translation_09132024.docx)

**Comment by moviedosoco** [comment]
Thank you, @RLHecht The updates were made in Drupal.

@saratorres2 This page is ready to be republished. Thank you!
https://preview-prod.vfs.va.gov/preview?nodeId=71958

**Comment by saratorres2** [comment]
@moviedosoco I edited and published this page, and @laurwill will take a second look at it later today once it is live. At that point, @RLHecht or I can open a Public Websites ticket to set up the toggle.

**Comment by moviedosoco** [comment]
As we published the translated updates, the page was sent to State for QA on 10/11.

**Comment by moviedosoco** [comment]
@saratorres2 The QA in _Creación de una cuenta para VA.gov_ is done. The page can now be published. Thank you!
https://prod.cms.va.gov/node/71958/latest

Preview in Drupal: https://preview-prod.vfs.va.gov/preview?nodeId=71958

**Comment by saratorres2** [comment]
@moviedosoco @RLHecht I've published changes and am waiting for the updates to go live.
