### ISSUE TITLE
Build and publish Signing In page in Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#91040]
## Issue description
This content needs to be translated as part of the sign in transition work:

https://www.va.gov/resources/signing-in-to-vagov/
- Spanish only

---
## Tasks
- [x] Send materials for translation to State Dept. (Randi)
- [x]  Build out Spanish translation of live pages (Victoria)
- [x]  Copy edit pages in Drupal (Sara)
- [x]  Verify changes are live and send to State Department for QA (Sara, Victoria)
- [x]   Publish with Spanish toggle (Sara, Randi)

## Acceptance Criteria
- [x] Updated content is live on the site

**Comment by RLHecht** [comment]
@moviedosoco here's the content back from State. This page is ready to be built in Drupal. Thanks!

[LS-2024-0122945-SPA-FINAL_Signing in to VA.gov_for translation.docx](https://github.com/user-attachments/files/16679769/LS-2024-0122945-SPA-FINAL_Signing.in.to.VA.gov_for.translation.docx)

**Comment by moviedosoco** [comment]
@RLHecht This Spanish page _Iniciar sesión en VA.gov_ it's built in Drupal. 

@saratorres2 This page is ready to be reviewed and published https://prod.cms.va.gov/resources/iniciar-sesion-en-vagov

Please note that the Preview shows telephone numbers hyperlinked although they don't have the aria labels. You can verify this in 'Source'.

Also, there are English links. Once the Spanish pages are published, we will change those links to their Spanish versions. Thank you!

**Comment by moviedosoco** [comment]
@saratorres2 This is the Preview: http://preview-prod.vfs.va.gov/preview?nodeId=72039

**Comment by saratorres2** [comment]
@moviedosoco This page is now updated, live, and ready to send for QA.

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2  The live Spanish page was emailed today to State for QA:
https://www.va.gov/resources/signing-in-to-vagov-esp/

**Comment by moviedosoco** [comment]
The QA came back with no edits needed.

@RLHecht, @saratorres2  The 2 URLs in the Related Information section were changed to their Spanish versions, and the "(in English)" phrase was deleted. 

This page is ready to be republished: https://prod.cms.va.gov/node/72039/latest
Drupal preview: http://preview-prod.vfs.va.gov/preview?nodeId=72039

Thank you!

**Comment by saratorres2** [comment]
@moviedosoco @RLHecht I've published Victoria's changes (updated links) to this page and am waiting for the changes to go live. TY!

**Comment by saratorres2** [comment]
Work completed on this ticket, moving to validate.
