### ISSUE TITLE
MVP Hybrid Microservice: Versioning development for the microservice

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91043]
## User Story
As the managers and developers for the VA Platform, 
We need to provide semantic versioning for the microservices architecture,
So that when future work is scheduled and in progress there are templates provided to ease the work.

## Issue Description
Provide semantic versioning for the microservices architecture.

## Tasks
- [ ] Include the versioning as part of the standardization and templating efforts
- [ ] Document the process and identify any potential issues with this work. 

## Success Metrics
Having templates in place for the microservices architecture will allow for consistent work across the program. 

## Acceptance Criteria
- [ ] Versioning process is clear for developers
- [ ] The versioning process is documented for the microservices architecture. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
