### ISSUE TITLE
MVP Hybrid Microservices: Encryption Discovery

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91053]
## User Story
As the managers and developers for the VA Platform, 
We need to do research and discovery on encryption for the microservices, 
So that there are no issues with encryption for data at rest and in transit

## Issue Description
Need to consider things like encryption at rest and in transit for the new microservices architecture. 

## Tasks
- [ ] Perform discovery for encrypted data at rest and in transit.
- [ ] Document the process and identify any potential issues with this work. 

## Success Metrics
That there is future work for encryption in the microservices architecture laid out and clear for implementation.

## Acceptance Criteria
- [ ] That there is a clear path forward for how to encrypt data at rest and in transit, for the microservices. 
- [ ] That the research is documented for the selection of an encryption method. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
