### ISSUE TITLE
[Spike] Decrypting password protected documents

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#91069]
Today in production users can upload evidence documents that are password protected and the system doesn't know the password, the document is considered a failure. 

The purpose of this spike is to research and confirm both the user experience and system performance in the situation where a Veteran/user uploaded a password protected document as evidence and how it is handled. 

Example of some of the things we should be checking for: 
- [x] Is there something in production today that would recognize that the document is protected/locked? 
- [x] If yes, is there something that notifies the user that a password is required? 
- [x] If yes, does this notification also ask the user to provide the password? 
- [x] Is decrypting the file successful in the system? (in other words, does it work) 
- [ ] If we are able to decrypt the document is LH able to accept it then? 
```[tasklist]
### Tasks
- [ ] Report on the findings, include screen shots and message content if possible.
```

**Comment by ajones446** [comment]
On staging, locked PDFs are checked during the upload supporting evidence step. Overview of the user's perspective:

1. If a locked PDF is added, the password is requested. The file cannot be added without the correct password. 

![Screenshot 2024-08-21 at 4 06 22 PM](https://github.com/user-attachments/assets/f30fd744-b641-43a4-ab5d-b4b2bf99f5a1)


2. This error message appears if the password is incorrect: `Error We couldn’t unlock your PDF. Save the PDF without a password and try again.`

![Screenshot 2024-08-21 at 4 21 42 PM](https://github.com/user-attachments/assets/11cd394e-8e34-4131-9b61-cdba0402d990)


3. When the correct password is entered, this message is displayed: `The PDF password has been added.`  
<img width="890" alt="Screenshot 2024-08-21 at 4 23 40 PM" src="https://github.com/user-attachments/assets/e49ef7d9-e993-439c-80b8-301ac4915606">

**Comment by lisacapaccioli** [comment]
Thanks @ajones446. I think the last thing we need to confirm from the list above is whether once it's decrypted if LH is able to accept it. I don't want to assume that will work. 

Honestly I am not sure how this all works, do we actually decrypt it and store it that way so that the adjudicator doesn't need the password, or do we save the password and the adjudicator has access to it and knows to use it???

**Comment by ajones446** [comment]
> Honestly I am not sure how this all works, do we actually decrypt it and store it that way so that the adjudicator doesn't need the password, or do we save the password and the adjudicator has access to it and knows to use it???

Quick update @lisacapaccioli: We store and send the file as a decrypted PDF. The adjudicator does not need the password to open it.

**Comment by ajones446** [comment]
> Thanks [@ajones446](https://github.com/ajones446). I think the last thing we need to confirm from the list above is whether once it's decrypted if LH is able to accept it. I don't want to assume that will work.

Confirming all the LH requirements will be part of the next spike: [#91097 LH migration for evidence uploads error responses](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91097)
