### ISSUE TITLE
686 Updates | Map new arrays to pdf

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#91068]
## Issue Description
Since the initial mapping of existing online 686 and 674 form data to the new version of the form pdf in phase 1, the form arrays have been updated and need to be re-mapped to the pdf to ensure a complete claim is submitted.

We had talked about passing a payload version from front-end to back-end, but a flipper would also work to differentiate which version to validate against.

---
## Tasks
- [ ] Map new form fields to new pdf
- [ ] Map new arrays to pdf
- [ ] Remove any depreciated fields from database and new pdf

## Acceptance Criteria
- [ ] A submitted online 686 claim generates a pdf that includes all necessary form fields
- [ ] A submitted online 674 claim generates a pdf that includes all necessary form fields

**Comment by mjknight50** [comment]
@mreed101 - Can you please pair program with @evansmith on this?
