### ISSUE TITLE
Contact Accredited Representative

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91079]
## Issue Description

After users select a representative, we confirm their selection and ask them to contact the accredited representative to make sure they're available to help. 

The Contact Accredited Representative page will be available to **all users**:
1. Authenticated and unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

Content is dynamic based on:

1. If the user selects a VSO for representation, they will see "VA Form 21-22" at the top of the page. If the user selects an attorney/claims agent for representation, they will see "VA Form 21-22a" at the top of the page.

No form fields for 21-22 or 21-22a are being completed on this step.
  
**URL**: `/representative-contact`

**Previous path**: `/representative-select` 

**Next paths**: 
If the user selects a VSO representative that has multiple organizations:
1. `/representative-organization`

If the user selects an entire organization OR a VSO representative that has a single organization OR an attorney/claims agent:
2. `/representative-replace` (Auth Veterans and auth non-Veterans that have existing representation)
3. `/claimant-relationship` (Unauth non-Veterans)
4. `/veteran-personal-information` (Unauth Veterans)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-150195&t=fkguCB8py5SDtFNk-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=456%3A171489&show-proto-sidebar=1) 
[Organization selected state](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8890-504746&t=6P2FrNHsTjCllIiW-11)
[Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1185-102154&t=fkguCB8py5SDtFNk-4)
[Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8967-307598&t=59GH1GNhwWZjFyWO-4)

**Implementation Note**: when showing the individual search results, VSO representatives may have associated organizations to show.  I don't believe we have this "organization association" concept for attorneys/claims agents.

Variations:
1. [Individual selected](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-150195&t=59GH1GNhwWZjFyWO-4)
2. [Organization selected](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8890-495323&t=59GH1GNhwWZjFyWO-4)

<details><summary>Screenshots</summary>

#### Individual selected

<img width="176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354f53f5d2ad0e9f75615f2a86f98f48135fb242/image.png" alt="image.png" />

<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3R4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac278adbf359fda56516b08ca4fc38351f148646/image.png" alt="image.png" />

#### Organization selected

<img width="197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWh4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--765e40d430cc36942bd08ca46fd7bc1ef8f6763b/image.png" alt="image.png" />
</details> 

---
## Tasks
- [ ] Create the Contact Accredited Representative page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Contact Accredited Representative page has been implemented, with the specs outlined above.

**Comment by oddball-lindsay** [comment]
Waiting for this PR to be approved, to address existing issues in Staging so that Michael can see this screen and QA https://github.com/department-of-veterans-affairs/vets-website/pull/32262

**Comment by mtri** [comment]
QA: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94719
