### ISSUE TITLE
Select Accredited Representative

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91077]
## Issue Description

This screen allows users to select the representative they'd like to appoint.  The search results are powered by our new `accredited_entities_for_appoint` endpoint, which has been built/tested locally over in https://github.com/department-of-veterans-affairs/va.gov-team/issues/82840.

The Select Accredited Representative page will be available to **all users**:
1. Authenticated and unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

If the user selects:
1. An attorney/claims agent, complete section 16 of the [21-22a](https://www.vba.va.gov/pubs/forms/vba-21-22a-are.pdf):
    1. Field 16a: representative name
    2. Field 16b: representative type
    3. Field 16 c,d,e: representative contact information, as it exists in the database
2. A VSO representative **that is only accredited with a single organization**, complete field 15 of the [21-22](https://www.vba.va.gov/pubs/forms/VBA-21-22-ARE.pdf):
    1. Field 15: Veteran Service Organization name
  
**URL**: `/representative-select`

**Previous path**: `/claimant-type` 

**Next paths**: 
1. `/representative-contact`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-150224&t=fkguCB8py5SDtFNk-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=456%3A171489&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=467-32065&t=fkguCB8py5SDtFNk-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8967-298516&t=59GH1GNhwWZjFyWO-4) 

There are a few states to consider: 
1. [Initial state ](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=6329-256212&t=6P2FrNHsTjCllIiW-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893)
2. [Search results state](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6329-256216&t=6P2FrNHsTjCllIiW-11)
3. [No search results state (not in Prototype)](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8996-204699&t=6P2FrNHsTjCllIiW-11)
4. [Organization search results (not in Prototype)](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=5138%3A420728&node-id=8890-504749&t=6P2FrNHsTjCllIiW-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3717%3A80893)

And a couple of things to keep in mind...
**Initial state**: 
1. We talked about having a minimum character input of 2 characters.  I believe the backend is enforcing this, but we could have an error state on the frontend too to give that feedback to users.

**Search results state**: 
1. The "Select this representative" button on search results cards are what advances to the next path.  We have an error state (last screenshot) which will come into play if a user tries to click "Continue", as they need to select a representative here. 
1. When showing the individual search results, VSO representatives may have associated organizations to show.  I don't believe we have this "organization association" concept for attorneys/claims agents.
2. We are only showing the top 10 matches for the search input (no pagination), the backend should be operating with a higher trigram threshold so we don't anticipate more than 10 search results if the full name is searched.
3. This is likely an edge case, but there _could_ be a scenario where search results contain a mix of both individual and organization results. (E.g. searching "Dale" or "Graham" could bring up individual representatives named "Dale" or "Graham", but the VSO "Dale K. Graham Veterans Foundation" could also come up)

<details><summary>Screenshots</summary>

#### Initial State
<img width="266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTV4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1a23a4ba7f0830b8e312c28422e2ad748c5b40a/image.png" alt="image.png" />

<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0p4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--460ccdc3a5cb02e876be9f6b4178ac43a970b24d/image.png" alt="image.png" />

#### Individual search results
<img width="176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354f53f5d2ad0e9f75615f2a86f98f48135fb242/image.png" alt="image.png" />

<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1J4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2c5a1c03067e5848bb2b6092d22edf4b07bb646/image.png" alt="image.png" />

#### Organization search results
<img width="166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekp4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81ff52af17a56f4b98253753b45b746b6d313d7a/image.png" alt="image.png" />

#### No search results
<img width="221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek54Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca5285d43ce07f17c99d667d4bd442a15f81d9d0/image.png" alt="image.png" />

#### Empty search
<img width="233" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlp4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--defe11f06504e489001abddc07c1c6ebeaa06218/image.png" alt="image.png" />

<img width="1111" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1p4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73575e97432ccfbfa5c30837d5aa696c7bc030e4/image.png" alt="image.png" />

#### Error state
<img width="214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXh4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15af617bb8a5ff6cf75c40733aa887147e8d7983/image.png" alt="image.png" />

<img width="1050" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1Z4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a7f5939a56356ed11d3a76ada3fe4cc97672875/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Select Accredited Representative page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Select Accredited Representative page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
8/27 update - VASearchInput component doesn't function properly within a form flow and needs to be implemented as a custom component.

**Comment by oddball-lindsay** [comment]
Remaining things: styling and search results

Once this ticket is completed, the team can divide and conquer other screens in this chapter.

**Comment by cosu419** [comment]
9/16 update: about to wrap up the final PR on this ticket

**Comment by cosu419** [comment]
@mtri ready for review. Getting the error message not to wrap the results is going to take some refactoring, but let me know what else you find.

**Comment by mtri** [comment]
Looks like the address input is functioning as expected now, thanks! Page looks good!

There's a couple of global edits I'm not sure where to capture. Let me know if I should put these on a different open ticket instead of here if you'd like.

- The h1 "Fill out your form to appoint a VA accredited representative or VSO" should match the breadcrumb "Request help from a VA accredited representative or VSO."

- Tell us how you’re connected to the Veteran question is displaying for the Veteran claimant path. This question should only display for non-Veteran claimants

**Comment by cosu419** [comment]
> Is it possible to use the same design of the search component that exists in VADS with the attached search button? It also has a built-in responsive breakpoint to switch to a search icon which is nice. (Resize your window when viewing the link.)

Some other teams have discovered issues with this component in a form context (none of the callbacks are fired on submit). I spoke with another team who settled on this as a near term workaround until the component is properly supported within forms.

**Comment by cosu419** [comment]
@mtri ready for review - looking into getting a search result with just one org in the test data

**Comment by jvcAdHoc** [comment]
test user `Catheryn Baumbach` has only 1 org

**Comment by mtri** [comment]
QA ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94087
