### ISSUE TITLE
Copy of Indicate in 526 PDF question 16 if claim is related to Toxic Exposure

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#91091]
## Issue Description
When a Veteran is completing the 2022 Form 526 with Toxic Exposure questions, they answer "is this related to Toxic Exposure" within the application. Currently, if the answer is 'yes' that question is not making it to the PDF question 16 in the overflow. The copy for both TE and non-TE claims on the PDF is the same.
<img width="1516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0c2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c41233fad6effe5c28f51009ac261f2622a5bdcc/image%20%2824%29.png" alt="image (24).png" />

We want to update the PDF overflow for question 16 if a Veteran does claim Toxic Exposure so that it will say:
"Exposure Event: My condition was caused by an injury or exposure during my military service; Is related to toxic exposure."

[DSVA Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1720206552851579?thread_ts=1720206267.172359&cid=C04KW0B46N5)

---
## Tasks
- [ ] Add "is related to Toxic Exposure" to the exposureEvent column if a disability is related to Toxic Exposure

## Acceptance Criteria
- [ ] If a Veteran says yes their condition is related to Toxic Exposure, "is related to toxic exposure" will be present in question 16 of the PDF
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tommasina-va** [comment]
Notes from Lisa: https://dsva.slack.com/archives/C04KW0B46N5/p1724259085961149
Info we learned from Jeremy Haas:
Are Veterans familiar with what a BIRLS ID is? No, generally not.
Is there another term that BIRLS ID might go by that is more familiar to Veterans and would make sense to the Help Desk? Not that I am aware of. On a VA site it refers to BIRLS as “A tool the Center For Verification and Evaluation (CVE) uses to verify an applicant is an eligible Veteran”
How would the Help Desk describe it to the Veteran (or wouldn’t they) if a message displayed that said it was missing and was needed? It is a database similar to DEERS that contains military history, used to verify is the applicant is an eligible veteran
Does the Help Desk know what to do if the BIRLS ID is missing? What if we called it something different? Ideally the error description would be modified to something along the lines of “An error occurred, we’ve found a mismatch in your BIRLS Record”
Notes from Thomas:
EVSS requires a SSN, DoB, EDIPI, BIRLS ID & Participant ID just to submit an ITF
When we pass the data downstream, MPI is used to find the eFolder. If they can’t find the PID in MPI, then they can’t find the efolder to associate with Intent To File (ITF)
Once Lighthouse takes over the ITF, most of those ID requirements will go away. I believe only an ICN is needed
Additional Notes:
The Beneficiary Identification Records Locator Subsystem (BIRLS) is a tool the Center for Verification and Evaluation (CVE) uses to verify an applicant is an eligible Veteran. Fact Sheet
What I do recall hearing was that BIRLS may NOT always be the SSN. The when and why I don’t recall.
I have some slack channels with some discussions around these, but it was mainly focusing on the PID. Just let me know if you want me to share them so you can check them out.
