### ISSUE TITLE
Build and publish "What to bring to create your online sign in account" page into Spanish

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#91090]
## Issue description
This content needs to be translated as part of the sign in transition work:
---
## Tasks
- [x]  Send materials for translation to State Dept. (Randi)
- [x]  Build out Spanish translation of live pages (Victoria)
- [x]  Copy edit pages in Drupal (Sara)
- [x]  Verify changes are live and send to State Department for QA (Sara, Victoria)
- [x]   Publish with Spanish toggle (Sara, Randi)

## Acceptance Criteria
- [x] Updated content is live on the site

**Comment by RLHecht** [comment]
@moviedosoco Here's the content back from State. This is ready to be built in Drupal. Thanks!

[LS-2024-0122945-SPA-FINAL_What to bring to create your online sign-in account_for translation.docx](https://github.com/user-attachments/files/16681046/LS-2024-0122945-SPA-FINAL_What.to.bring.to.create.your.online.sign-in.account_for.translation.docx)

**Comment by moviedosoco** [comment]
Thank you @RLHecht 
I can start building this page first since it's linked with the third fact sheet.

**Comment by moviedosoco** [comment]
@RLHecht The Spanish page for "[What to bring to create your online sign-in account](https://www.va.gov/resources/what-to-bring-to-create-your-online-sign-in-account/)" is built in Drupal.

SPA: _**Qué traer para crear su cuenta de inicio de sesión en línea**_

@saratorres2 This is ready to be reviewed and published https://preview-prod.vfs.va.gov/preview?nodeId=71792

Please note that that we're currently using English links to two of our pages that are being translated. They are in the Related Information section:
_Creación de una cuenta para VA.gov (en inglés)_ and 
_Verificación de su identidad en VA.gov (en inglés)_. 

We will change them to our Spanish version once they´re ready. 
Thank you!

**Comment by saratorres2** [comment]
@moviedosoco Changed published; waiting on live version.

**Comment by saratorres2** [comment]
@moviedosoco @RLHecht Confirming that the changes to this page are live.

**Comment by moviedosoco** [comment]
@RLHecht @saratorres2 The live Spanish page was emailed to State for QA:
https://www.va.gov/resources/what-to-bring-to-create-your-online-sign-in-account-esp/

**Comment by moviedosoco** [comment]
Hi @RLHecht and @saratorres2,   since we now have the _Creación de una cuenta para VA.gov_, and
_Verificación de su identidad en VA_.gov Spanish pages live,  I changed the 2 URLs to their Spanish versions and deleted the "(in English)" phrase. These are in the Related Information section. 

This page is ready to be republished: https://prod.cms.va.gov/node/71792/latest
Drupal preview: https://preview-prod.vfs.va.gov/preview?nodeId=71792

Thank you!

**Comment by saratorres2** [comment]
@RLHecht @moviedosoco I've published Victoria's changes (updated links) to this page and am waiting for the changes to go live. TY!

**Comment by moviedosoco** [comment]
@saratorres2 Sara will add the phrase 'Related information' in the last checkbox of the page since that component isn't translated into English:

_Más documentos de identificación si cambió recientemente su nombre legal o dirección, desea hacer la verificación en una videollamada o vive fuera de los EE. UU. (Lea la sección Información Relacionada para encontrar enlaces a más información)_

**Comment by saratorres2** [comment]
We weren't able to make the change above (or to use boldface for "Informacion Relacionada" because of character limits in the checkbox component. @moviedosoco @aprocik1 Work on this page is now complete. Moving to validate.
