### ISSUE TITLE
Content Edit: Footer Ticket 92041 pt. 1

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91105]
## User Story
As a VFS Team member, I need an up-to-date list of Platform data sources, so I can monitor performance on the Front End.

## Issue Description
In June 2023, there was a discussion in Slack ([reference](https://dsva.slack.com/archives/C04868KS69L/p1685557467880359)) where it was revealed that we no longer use **SpeedCurve** for web performance testing. 
Per [Footer Ticket 92041](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92041), There are still 3 pages referencing this tool in a table of data sources, and we need to remove this information.

- ### This Ticket is for the removal of SpeedCurve information from the **[Track Your KPIs](https://vfs.atlassian.net/wiki/spaces/APM/pages/1824063586/Track+your+KPIs)** page

![image](https://github.com/user-attachments/assets/a9683b78-40c8-4093-9c14-d54e7b0f90c9)

---
## Tasks
- [ ] Create copy of [Track Your KPIs](https://vfs.atlassian.net/wiki/spaces/APM/pages/1824063586/Track+your+KPIs) in Draft space
- [x] Table should be updated to remove SpeedCurve information
- [ ] copy and paste the content of your page in the drafts space to the equivalent page in the Platform website content source
- [x] Prepare for deployment
 
## Acceptance Criteria
- [x] SpeedCurve information is removed from the page
- [x] Page is ready for deployment

**Comment by jknipes** [comment]
was duplicate ticket

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91105?planning-poker) with Zenhub @BSmolensky @cmarion93 @laucon @taylojill

**Comment by taylojill** [comment]
I searched website and Confluence. I removed Speedcurve from the following pages:
1. https://vfs.atlassian.net/wiki/spaces/APM/pages/1797881953/Platform+data+sources
2. https://vfs.atlassian.net/wiki/spaces/APM/pages/1824063586/Track+your+KPIs
3. https://vfs.atlassian.net/wiki/spaces/GS/pages/1872855066/Platform+tools

**Comment by taylojill** [comment]
Speedcurve removed from two website pages, date stamp added/updated, no blockers, ready to publish.
