### ISSUE TITLE
Replace Current Representative

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91104]
## Issue Description

If a user is authenticated and has existing representation, they need to confirm that they're looking to replace that existing representation with the selected representative. 

The Replace Current Representative page will be available to:
1. Authenticated Veterans and authenticated non-Veterans ONLY
3. Users who have existing representation ONLY
4. 21-22 and 21-22a forms

Content is dynamic based on:

1. If the user selects a VSO for representation, they will see "VA Form 21-22" at the top of the page. If the user selects an attorney/claims agent for representation, they will see "VA Form 21-22a" at the top of the page.

No form fields for 21-22 or 21-22a are being completed on this step.
  
**URL**: `/representative-replace`

**Previous path**: 
1. `/representative-contact` (If the user selected an entire organization OR a VSO representative that has a single organization OR an attorney/claims agent)
2. `/representative-organization` (If the user selected a VSO representative that has multiple organizations)

**Next paths**: 
1. `/claimant-relationship` (non-Veterans)
2. `/veteran-personal-information` (Veterans)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1475-212843&t=59GH1GNhwWZjFyWO-4), [Annotation](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8967-303471&t=59GH1GNhwWZjFyWO-4)

<details><summary>Screenshots</summary>

<img width="169" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1Z5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac127019d41189453e66e6057e757a66433d1721/image.png" alt="image.png" />

<img width="893" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2h5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82f206ca00eda9bfb7172641c211be3877a99988/image.png" alt="image.png" />

</details> 

---
## Tasks
- [ ] Create the Replace Current Representative page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Replace Current Representative page has been implemented, with the specs outlined above.

**Comment by cosu419** [comment]
@mtri this is ready for review

**Comment by mtri** [comment]
QA ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/93763
