### ISSUE TITLE
Copy of Contact the Accredited Representative

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91101]
## Issue Description

After users select a representative, we confirm their selection and ask them to contact the accredited representative to make sure they're available to help. 

The Contact the Accredited Representative page will be available to:
1. Authenticated and unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

Content is dynamic based on:

1. If the user selects a VSO for representation, they will see "VA Form 21-22" at the top of the page. If the user selects an attorney/claims agent for representation, they will see "VA Form 21-22a" at the top of the page.

No form fields for 21-22 or 21-22a are being completed on this step.
  
**URL**: `/representative-contact`

**Previous path**: `/representative-select` 

**Next paths**: 
If the user selects a VSO representative that has multiple organizations:
1. `representative-organization`

If the user selects a VSO representative that has a single organization OR the user selects an attorney/claims agent:
2. `representative-replace` (Auth users only bc we need login to confirm any existing representation)
3. `claimant-relationship` (Unauth non-Veterans)
4. `veteran-personal-information` (Unauth Veterans)

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-150195&t=fkguCB8py5SDtFNk-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=456%3A171489&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=1185-102154&t=fkguCB8py5SDtFNk-4)

**Implementation Note**: when showing the individual search results, VSO representatives may have associated organizations to show.  I don't believe we have this "organization association" concept for attorneys/claims agents.

<details><summary>Screenshots</summary>

#### Individual selected

<img width="176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354f53f5d2ad0e9f75615f2a86f98f48135fb242/image.png" alt="image.png" />

<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3R4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac278adbf359fda56516b08ca4fc38351f148646/image.png" alt="image.png" />

#### Organization selected

<img width="197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWh4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--765e40d430cc36942bd08ca46fd7bc1ef8f6763b/image.png" alt="image.png" />
</details> 

---
## Tasks
- [ ] Create the Contact the Accredited Representative page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Contact the Accredited Representative page has been implemented, with the specs outlined above.

**Comment by jvcAdHoc** [comment]
[pr merged in](https://github.com/department-of-veterans-affairs/vets-website/pull/31943)

**Comment by mtri** [comment]
-   There should be a link to "Find an accredited representative" below the "Note: If you don't know who you'd like to appoint, you can use our online tool to search for an accredited attorney, claims agent, or VSO representative." [See screen](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=1475-217018&node-type=frame&t=RChOdV79mEC79MrJ-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A217022&show-proto-sidebar=1)

-   The "i" in "If" should be capitalized in the Note.

-   Search result card front end doesn't appear to be implemented yet for reps or organizations. It aligns with what's in Find.\
    [Individual rep search with individual card to reference\
    ](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=8637-357138&node-type=frame&t=RChOdV79mEC79MrJ-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A217022&show-proto-sidebar=1)[Organization rep search with organization card to reference](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=8890-493086&node-type=frame&t=RChOdV79mEC79MrJ-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A217022&show-proto-sidebar=1)

-   The button on the card will have text "Select this representative" and be a [secondary action button](https://design.va.gov/storybook/?path=/docs/uswds-va-button--secondary).

-   [Is it possible to use the same design of the search component that exists in VADS with the attached search button?](https://design.va.gov/storybook/?path=/docs/uswds-va-button--secondary) It also has a built-in responsive breakpoint to switch to a search icon which is nice. (Resize your window when viewing the link.)

-   Can we set an enter keyboard key press to trigger the search? This is how it works on Find as well.

Thanks!

**Comment by jvcAdHoc** [comment]
@mtri the feedback looks to all be related to the `representative-select` page. This ticket is for `representative-organization`

**Comment by mtri** [comment]
Sorry for any confusion with the previous feedback. No feedback on the organization selection page. Looks good!
