### ISSUE TITLE
Jill Meet with New Team Member: Casey

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91107]
## Issue Description
Jill Taylor will meet with new team member Casey Marion

---
## Tasks
- [x] contact each other
- [x] schedule time to meet ~30min
- [x] Hold Q&A session

## Acceptance Criteria
- [x] All tasks complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by taylojill** [comment]
Calendar invite sent to sync on Thursday September 5th.

**Comment by taylojill** [comment]
Completed!

**Comment by jknipes** [comment]
Closing this ticket as _Done_
