### ISSUE TITLE
Hold Intro for New Team Member: Casey Marion

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91103]
## Issue Description

- New team member's first day is Wednesday, August 21
- We need to meet as a team to introduce ourselves to them.

---
## Tasks
- [x] Schedule 30 min - 1 hour to meet as a team; preferably **not** on their first day
- [x] Do individual introductions
- [x] Run through our team's mission and the services that we provide on a day-to-day basis; use the [Platform Content Team space](https://vfs.atlassian.net/wiki/spaces/CIT/overview) as a starting point.
- [x] Team meetings
- [x] Tools we use (Slack, ZenHub, Confluence, etc.) 
- [x] Show them our main product, Platform website, and our secondary services
- [x] Questions

## Acceptance Criteria
- [x] We will have met with the new team member to do more formal introductions and explain our services at a deeper level.

**Comment by jknipes** [comment]
ticket created to document onboarding efforts in place of daily stand up. These steps are historically accounted for whenever onboarding a new team member

**Comment by jknipes** [comment]
closing as _Done_
