### ISSUE TITLE
Appoint Introduction

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91108]
## Issue Description

The introduction page is available to all!  This is the start of our Appoint a Rep experience and the entry point will live on our landing page ([expected design](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=456-171489&t=59GH1GNhwWZjFyWO-4)).  We already have a rough outline of this page, and just need to adjust that to match our Figma design.
  
**URL**: `/appoint-rep/introduction`

**Previous path**: most likely our Get help from a VA accredited representative or VSO landing page (https://www.va.gov/get-help-from-accredited-representative/), but folks could start directly on this page if they come here through search or a direct link.

**Next paths**: 
1. `/appoint-rep/claimant-type`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=3848-261853&t=59GH1GNhwWZjFyWO-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=456%3A171489&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=3848-261853&t=59GH1GNhwWZjFyWO-4), [Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8967-301319&t=59GH1GNhwWZjFyWO-4)

Variations:
1. [Unauthenticated](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=3870-275494&t=59GH1GNhwWZjFyWO-4)
   1. The Widget has a condensed version of the unauthenticated state 
   2. There is an alert at the bottom of the page encouraging users to sign in (but allowing them to continue without signing in)
2. [Authenticated](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=3870-275689&t=59GH1GNhwWZjFyWO-4)
   1. The Widget displays the current rep status
   2. There is an alert mentioning prefill and save in progress, below the Widget.  (While we are not using the prefill pattern, I think the mention of prefill still applies since we can prefill the text input fields with any information from the user's profile)

### Screenshot (Unauthenticated)

<img width="570" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZ5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96dcea2dd91d4a5d35466549befabf9ad9d5fdd8/image.png" alt="image.png" />

---
## Tasks
- [ ] Create the Appoint Introduction page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Appoint Introduction page has been implemented, with the specs outlined above.

**Comment by jvcAdHoc** [comment]
[Draft pr](https://github.com/department-of-veterans-affairs/vets-website/pull/31654) - need to figure out build failures

**Comment by mtri** [comment]
- **H1 and breadcrumb need to be the same. The H1 text recently was changed to:**
`Request help from a VA accredited representative or VSO`

Breadcrumb should match. This is also true for the entirety of the form CC: @cosu419 

- **Your branch of service (only if you’d like to appoint a VSO)**
This text matches our source of truth but it is an incorrect statement. The branch of service is only collected on the 21-22a when appointing an attorney or claims agent. This can be switched to
`Your branch of service (only if you’d like to appoint an attorney or claims agent)`

And we'll get it updated on the content source of truth & in Figma as well. CC: @oddball-lindsay

**Comment by jvcAdHoc** [comment]
Addressing feedback today

**Comment by jvcAdHoc** [comment]
[pr for fixups](https://github.com/department-of-veterans-affairs/vets-website/pull/31952)

**Comment by mtri** [comment]
Couple more things:
- [On the authenticated screen](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?page-id=1475%3A128342&node-id=1475-217022&node-type=frame&viewport=3338%2C363%2C0.13&t=b6oIYr3xkDJ0Qvef-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1475%3A217022&show-proto-sidebar=1), the action button link text should be "Fill out your form to request help" as opposed to "Get started"
- On the authenticated screen, the action button should appear both above and below the process list.
- On the authenticated screen the note alert with the content "Since you’re signed in to your account, we can prefill..." should appear below the Representative Status Widget.

[There may be changes to sign in alert copy based on this conversation](https://dsva.slack.com/archives/C07FKH4NH35/p1726602933191299)

**Comment by jvcAdHoc** [comment]
[pr for auth state fixups](https://github.com/department-of-veterans-affairs/vets-website/pull/31995)

**Comment by jvcAdHoc** [comment]
@mtri the auth state should be ready for testing on staging

**Comment by mtri** [comment]
This likely is a representative status widget issue rather than an intro page issue so we may need to document elsewhere: 

- The heading is appearing styled as an h2 causing the text to wrap awkwardly. It should be read as an h2 but always styled as an h3.
<img width="761" alt="Screenshot 2024-09-19 at 11 06 52 AM" src="https://github.com/user-attachments/assets/53cd3be3-131b-49c7-94aa-6d918f97575a">

Other than that looks good, thank you!

**Comment by jvcAdHoc** [comment]
I'm 95% sure this is on me. I saw `h2` in the linked annotations and set that as the base header.

**Comment by jvcAdHoc** [comment]
[pr for the styling change](https://github.com/department-of-veterans-affairs/vets-website/pull/32015)

**Comment by jvcAdHoc** [comment]
The header change is on staging now

**Comment by mtri** [comment]
Looks good, thanks!
