### ISSUE TITLE
Brian Meet with New Team Member: Casey

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91106]
## Issue Description

- Brian Smolensky meeting with new team member Casey Marion  

---
## Tasks
- [x] contact each other
- [x] schedule time to meet ~30min
- [x] Hold Q&A session

## Acceptance Criteria
- [x] All tasks complete
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Meeting held, closing this as _done_
