### ISSUE TITLE
[Design] Update Filter options and evaluate filter/sort link UI

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#91116]
## Background
In research, the filter pattern did not present any usability concerns, but our results lacked conclusive evidence that Veterans would use the feature prior to prompting them to use it. Though participants said the filters met overall expectations, some called out specific filters as confusing or missing.

Most notably: 

- Participants found the Practice filter confusing. 
- Participants mentioned other filters that could be added, like years practicing, patient ratings and reviews, language spoken, specialties and services.

We need to consider if including the filter and sort for MVP is worth the engineering effort knowing that not all Veterans would utilize this feature. If included, we should determine how additional value and clarity can be brought to the filter options, and test with real scenarios when possible.

## Details

- 9 of 15 participants noticed the filter and sort link without help from the moderator when asked how they’d narrow down the list of providers. 4 participants found the filter and sort link only with moderator help, while 2 participants never noticed it or were not asked about it due to time. 

- 12 of 13 participants reported that the type of filters on the filter and sort page met their expectations, although 2 participants mentioned expecting a language filter and 1 of these participants suggested adding filters for religion and provider’s years practicing. 3 participants said they were unsure of what the practice filter meant before reviewing the field options.

> P13: "So you can select a practice meaning you can select from this menu of physicians. I think what you're trying to say is physical therapy or heart specialist."

> P6: "So that’s good, like I said I can pick a male or a female, but it doesn’t give you, like, languages. And for some people, maybe religion is a really big thing, though I don’t know why for a doctor. Maybe also how long has he or she has been a doctor."

## Tasks
- [ ] Determine if any additional changes are needed for the filter and sort link to make it more prominent and easier for Veterans to locate and use without assistance
- [ ] Update the name of the Practice filter to remove confusion
- [ ] Work towards adding additional filters or information based on Veteran feedback, or other factors Veterans use to find a provider (e.g., years practicing, patient ratings and reviews, language spoken, specialties and services, etc.). 

## Acceptance Criteria
- [ ] Proposed changes shared with UX
- [ ] Figma files updated

**Comment by benbrasso-agile6** [comment]
Keeping this ticket in Icebox. Going to duplicate, but isolate it to rethink the "Practice" field.
