### ISSUE TITLE
Run Coverband in production so we understand what codepaths are unused

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#9111]
## Background

Code rot is the process of legacy code becoming defunct while remaining in the repository. A useful way to analyze what codepaths are unused is to run coverage tools in production. 

[Coverband](https://github.com/danmayer/coverband) can provide us with details on what code is actively used in our application and what code is candidate for removal.

## Goals

This will help us further reduce technical debt in the codebase and illustrate high-volume codepaths that may warrant closer inspection.

## Acceptance Criteria

- [ ] Coverband UI is available at api.va.gov/coverage
- [ ] Coverband UI is protected with authorization/authentication somehow

## Tasks

- [ ] Add `gem 'coverband'` to `Gemfile`
- [ ] Configure a standalone Redis instance in the utility environment
- [ ] Set a web admin UI password in Credstash? Or use in-app logic like we do w/ Flipper? (Auth it either way)
- [ ] Modify [config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2) files to pull details for redis

Avoiding adding a container to docker-compose here because it doesn't need to be there. Maybe more discovery needs to happen.

**Comment by ericboehs** [comment]
Done!
