### ISSUE TITLE
[Design] Update referral introduction page

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#91115]
## Background
1) In research, Veterans understood the information on the referral introduction page as a whole, but had some questions around specific details and suggestions for additional information. 

2) Veteran will not be "choosing" a provider. Therefore, what changes need to be made to the page to communicate to the Veteran their provider. (I.e., it was either chosen WITH THEM on the phone or in person, or an MSA selected them for them based on who's closest, who's available, etc.) 

## Details
- 13/14 participants understood the information on the referral page and knew how to continue with scheduling their appointment, although 1 screen reader participant mentioned confusion and had suggestions for content changes around the expiration date and referral number.

> P13: "What do you mean expiration date? Does the referral expire in 30 days? I don't understand. Say 'your referral will expire in 30 days.'" Referral number: "What does that mean? I have no idea."

- 2 participants mentioned additional information they’d expect to find on the page, such as what type of services their appointment would include and what to do if, later on, they aren’t satisfied with their provider choice and want to change providers for a second opinion. 

> P19: "I would want to know, after so many appointments, what do I do if I'm not satisfied with that provider? ... How do I get a second opinion? Those are the things that I would want."

- 2 participants interpreted “number of visits” as needing to complete 10 visits before the expiration date, 1 participant said they’d need to schedule 10 visits before that date, and 1 participant thought they already had 10 visits with this provider.

> P13: "When it says number of visits: 10. Are you saying the person has 10 visits or had 10 visits? I assume that the number of visits I (already) had with this person is 10. [I would suggest it reads,] you are approved for 10 visits"

## Tasks
- [x] Determine where content can be tweaked to help with questions/concerns that Veterans brought up about the information on the referral page, e.g., number of visits. In addition, simplify information about how to schedule remaining community care appointments. 
- [ ] Consider if any additional information should be included, e.g. services included
- [ ] Have content reviewed by Laura if needed
      
## Acceptance Criteria
- [ ] Proposed changes shared with UX
- [ ] Content reviewed
- [ ] Figma files updated

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/91115?planning-poker) with Zenhub @Cieramaddox @cgednalske

**Comment by benbrasso-agile6** [comment]
Moved to MVP page
