### ISSUE TITLE
[Design] Change expiration date format in task card

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#91114]
## Background
In CC research, Veterans found the presence of the expiration date helpful, but often said the specific format/wording confusing or misleading. Participants preferred the format used on the referral introduction date "expires [DATE]."

- 8 participants cited confusion around wording or expiration length.

> P14: "I'd recommend putting something like referral expires in 310 days [for the tag] because I don't know what expires in 310 days. It says you can schedule your appointment now. So, there's nothing to me that explains what expires." 

- 2 participants felt a long expiration date was misleading or a sign of slow care from VA.

> P4: "I think that's pretty awesome that you get 310 days, but I also really would not know why anybody would get 310 days because that also gets a little frustrating. Because then you get along the lines of one of the issues at VA is it takes so long to get seen, so I really don't want to get 310 days. I'd rather get 30 days or 90 days in which the doctor's going to see me within a smaller window. If I'm coming in with a complaint, I'm coming in with a pain, I'm coming in with an issue, I want to get seen as soon as I can.

## Tasks
- [x] Consider new phrasing for the expiration date in the task card, possibly mirroring the expiration date on the referral introduction page. 
- [ ] Have content reviewed by Laura if needed
      
## Acceptance Criteria
- [ ] Proposed change shared with UX
- [ ] Content reviewed
- [ ] Figma files updated

**Comment by benbrasso-agile6** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/91114?planning-poker) with Zenhub @Cieramaddox

**Comment by Cieramaddox** [comment]
@benbrasso-agile6 Can we revisit the idea of only showing the expiration when there are X amount of days/weeks before that date?

**Comment by benbrasso-agile6** [comment]
@Cieramaddox maybe could you create an example of what you're thinking? I'm sort of forgetting some of this context. Unless @cgednalske has more thoughts on the problem that needs to be solved.

**Comment by Cieramaddox** [comment]
I think you're right @cgednalske. 

Here is the suggested change. Will bring it up in the next SME sync

 <img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1dwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e63fec4a1a1c9e06f96823578fd7b1fb1abf20f/Screenshot%202024-09-03%20at%202.49.51%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 2.49.51 PM.png" />

**Comment by benbrasso-agile6** [comment]
Closing this ticket; seems to be solved. Can have Laura review async if we need to.
