### ISSUE TITLE
[FE] 10-10EZ - Insurance: Implement Multi-Response pattern to Insurance section

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#91136]
## Issue Description
As a Veteran, I want the application to display an accessible list of items, when adding multiple insurance policies, so that I can quickly and easily determine if I have entered all the information I want to include.

The insurance sections uses an old deprecated wizard list-and-loop pattern. This ticket is to update the code on the general insurance page to use the updated pattern.

- [Design system pattern guidance
](https://design.va.gov/patterns/ask-users-for/multiple-responses)
- [Figma design file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5317-57655&t=dcuzV9Py8dY2R0ol-0)

---
## Tasks
- [x] Reference [Figma design file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5317-57655&t=dcuzV9Py8dY2R0ol-0) ([ticket #88804](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88804))
- [x] Implement Multi-response pattern for non-required path (summary and information page)
- [x] Confirm form Review Page includes the expected insurance input

## Acceptance Criteria
- The 10-10EZ Insurance section is using the latest design system guidance for the insurance multiple responses pattern.

**Comment by longmd** [comment]
Review screen confirmation: 

![Screenshot 2024-09-10 at 15 03 57](https://github.com/user-attachments/assets/2087cc22-c71f-4b59-a345-842cf6890c70)

**Comment by longmd** [comment]
ArrayBuilder confirmation: 

| Question | Item | Review |
| ------- | ------ | ----- |
| ![Screenshot 2024-09-10 at 12 34 22](https://github.com/user-attachments/assets/91d36df0-9f4c-4656-bf84-86d11f5ecb2f) | <img width="601" alt="Screenshot 2024-09-10 at 12 34 50" src="https://github.com/user-attachments/assets/f31e36c2-2b01-40e1-8559-e4ced1f6e512"> | <img width="601" alt="Screenshot 2024-09-10 at 12 35 16" src="https://github.com/user-attachments/assets/ce08cdd5-12af-4fd7-b637-9e828579c6ab"> |

**Comment by longmd** [comment]
@allanto-ah , similar to the Reg Only flow. We will do QA after the Cypress tests have been created and verified.
