### ISSUE TITLE
[Design] Team Figma best practices: create and document

### ISSUE THREAD

**Issue by mattmarino-adhoc** [department-of-veterans-affairs/va.gov-team#91131]
## Background
The Authenticated Experience team has not previously formalized any best practices for our Figma design files with:

- File Names
- Page names
- Symbol naming
- Handling shared custom components that apply just to our files (ex. the Nametag)

@twoangstroms and @mattmarino-adhoc want to create some basic documentation on how Auth. Exp. Figma files are standardized, and use that as the basis to better organize our files and their contents (in a future ticket(s)).

---
## Tasks
- [x] Establish naming conventions
- [x] Establish practices with the Auth. Exp. Pattern Library for shared custom components
- [x] Document all decisions on github

## Acceptance Criteria
- [x] Documentation created in the identity-personalization folder in github

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Looking at github documentation

## Resources
[Figma folder](https://www.figma.com/files/team/1278375444205744118/project/176473451/Account-Experience?fuid=1316126118700040443)

**Comment by mattmarino-adhoc** [comment]
[10-10EZ Figma links page provides a model to consider for moving forward](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/ux-team/figma-links.md)

**Comment by twoangstroms** [comment]
Good find! That team really manages their GitHub space very well for documentation and Ways of Working, too.
