### ISSUE TITLE
Design | Contact Info Refresh | Error when save is not allowed

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#91168]
### What we have today 

![Image](https://github.com/user-attachments/assets/2caf2006-daed-44b8-a445-616cb4460014)

[Source: Profile - Contact Information - Mobile](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=0-1&node-type=canvas&t=rrX6SIHpS8DdePlX-0)

[Source: Profile - Contact Information - Desktop](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=873-3304&node-type=instance&t=rrX6SIHpS8DdePlX-0) 

### Update 18 Sep 2024
Changes to address and ZIP code validation may obviate some of the designs above, and recommendations below.

Only not allowing user to select a bad address if we do not received a validation/override key. What this means is that the API recognizes that the address will not be accepted by the system. An example: a city name with more than 255 characters. 

See [Figma file, page titled "#91168 - address error states"](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=926-6897&node-type=frame&t=Zd6DeA8cPv4vbRnW-0)

## Tasks 
- [x] FE and Design collaborate to understand the behavior, and inform designs 
- [x] Designs are discussed with FE and BE to ensure feasibility

## Acceptance Criteria 
- [x] figma designs (desktop and mobile) so we can go into development
- [x] [FE ticket is created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92664)
