### ISSUE TITLE
Design | Contact Info Refresh | Incorporate military address recommendations from 686C team

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#91174]
## Background 
We need to make changes to our address form to better support veterans who live on military bases outside the US. 

The 686C team has already done most of this work in this [figma](https://www.figma.com/design/LgjF3Kf8ozrBWMjPOQEKVV/686C---Military-Base-Outside-the-U.S.-Address-Issues?node-id=0-12&t=HUmqRWrGle24dsAn-0)

We've pulled the specific enhancements from the 686C team's figma into the [contact info mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724336887395/0f107c7e971dc93f275a3585cb916cc9ceea55af?wid=0-1724337342688)

The pieces we need to incorporate into our designs are:
- [enhancements to the expand ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92409)
- updated behavior for the city
- updated behavior for the state
- updated behavior for the zip code 

## Tasks 
- [x] identify which AE Figma files need updating
- [x] Review [VADS Patterns for addresses](https://www.figma.com/design/4A3O3mVx4xDAKfHE7fPF1U/VADS-Templates%2C-Patterns%2C-and-Forms?node-id=2987-36363&node-type=CANVAS&t=J81HewlNmYuALH4Y-0)
- [x] update figma file(s)
  - [x] [Profile - Contact Information](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=0-787&node-type=CANVAS&t=rBLtf2S9Su0797tl-0) 
    - [x] updated behavior for the city – look for Note Details 1
    - [x] updated behavior for the state - look for "#91174 - military address entry update" page
    - [x] updated behavior for the ZIP code - "#91174 - military address entry update" page
- [x] peer review
- [x] check w/FE on the changes 

## Acceptance criteria 
- [x] peer reviewed signoff (shared w PM/PO)
- [x] we're ready to pick up - #91175 

## Output 
- The "#91174 - military address entry update" page [here](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=1010-9076&node-type=instance&t=so0HpKXU9a7ylq0y-0)

**Comment by twoangstroms** [comment]
@asiisii Is this clear, if we were to put this into an FE ticket? From [here](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=873-3304&node-type=instance&t=dpewiGsEY6lClU4H-0).

![Image](https://github.com/user-attachments/assets/6ec19994-9028-4845-ab5a-7cd226aa646e)

**Comment by ACParker89** [comment]
> @asiisii Is this clear, if we were to put this into an FE ticket? From [here](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=873-3304&node-type=instance&t=dpewiGsEY6lClU4H-0). If not, I can try to create a screenflow that'll illustrate the steps.
> 
> ![Image](https://private-user-images.githubusercontent.com/62673202/367930790-6ec19994-9028-4845-ab5a-7cd226aa646e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTcwOTcsIm5iZiI6MTcyNjU5Njc5NywicGF0aCI6Ii82MjY3MzIwMi8zNjc5MzA3OTAtNmVjMTk5OTQtOTAyOC00ODQ1LWFiNWEtN2NkMjI2YWE2NDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE4MTMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYzYzMzZlMTUzMjNkNzI1ZDYwNmVmMGM3MTg5MzMxMDA3MzEzNjU3NTY0ZmRmYmJiOGJiZmY5YmZiZmNlMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nMrd2uJZo7fbuI7LuvnAbz9-vk33LrsiaCsqHlrjAR8)

@nickjg231 - can you look into this solution and reply to @twoangstroms

**Comment by ACParker89** [comment]
Rolling into 46 

Add to AC: Build FE ticket
