### ISSUE TITLE
Migration away from Virtus Gem

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91172]
## User Story
As the Managers and Developers on the VA Platform, 
We need to migrate away from the discontinued "Virtus Gem" that is heavily used on Vets API,
So that our tools and programs continue to function properly. 

## Issue Description
We noticed on Wednesday, 7/31/2024, that the [Virtus Gem](https://github.com/solnic/virtus) (used heavily in Vets API) has been discontinued. We need to migrate use from Virtus Gem to either **dry-types**, **dry-struct** and/or **dry-schema**, which we believe has been integrated in Vets API. 

## Tasks
- [ ] Based on the outcomes from [89816](https://github.com/orgs/department-of-veterans-affairs/projects/1335/views/7?filterQuery=89816&pane=issue&itemId=75083281), the use of Virtus Gem needs to be moved to a new Gem
- [ ] Migrate to **dry-types**, **dry-struct** and/or **dry-schema** from Virtus, based on the findings from the first task.
- [ ] Perform testing as required after the migration is complete.
- [ ] Document process and share documentation in this ticket.

## Success Metrics
A complete migration of Virtus Gems usage in Vets API to one (or more) of these: **dry-types**, **dry-struct** and/or **dry-schema**.

## Acceptance Criteria
- [ ] Migration away from Virtus Gems is complete
- [ ] Testing is complete and produces no errors
- [ ] Documentation is complete for migration
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by rmtolmach** [comment]
Closing. Steven is currently working on this (see [all relevant tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue%20virtus%20gem%20%20assignee%3Astevenjcumming%20)) and has a custom lib here: https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/vets
