### ISSUE TITLE
CDP - Payment History - Currency Not Displaying Correct Format

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#91180]
## Description
Discovered from QA for Payment History Table, amounts in the balance decrease lines were displaying -25 instead of a monetary format like the hardcoded row at bottom of table.

https://dsva.slack.com/archives/G01KBHYEXV2/p1724095057994399
Thread about issue 

## Tasks
- [x] Currency now displays correctly

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [ X ] Not Required

## Acceptance criteria
- [x] Item one from the description performs as described in the description

## Testing
- [ ] N/A if non development work
- [x] Testing passed and documented in this ticket based off the "Then" statement in the description
