### ISSUE TITLE
[VETS-API] Investigate use and deprecation of connect_vbms gem

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#91199]
## Issue Description
It was discovered that the SOAP endpoints of `connect_vbms` (which may be all of `connect_vbms`... still gathering info) will be decommissioned with the year. Here's a screenshot that Charley sent me from a convo between him and Matthew Roth (BAH Engineer, VA slack):

![image](https://github.com/user-attachments/assets/ac3d201f-867a-46df-bbcd-201332e871b1)

We need to investigate which services/modules in vets-api still use `connect_vbms`/`VBMS::Client`, and start conversations with respective teams to confirm that they are aware of these changes, and determine if we (Platform) need to own any of these changes.

---
## Tasks
- [x] Gather a better understanding of what `connect_vbms` does, 
- [x] Gather a list of all affected areas of the application, and determine ownership of each instance
- [x] Reach out to relevant teams, determine status (if they're not aware, make them aware), document status (confluence?)
- [x] Create necessary tickets if our team needs to own any of this

## Acceptance Criteria
- [x] Document use of `connect_vbms` gem. If it's all going away, including notes in this ticket is sufficient
- [x] Document is created that lays out relevant parts of the update, who owns it, and the status of conversations
- [x] Relevant tickets have been created for our team, if applicable

**Comment by ryan-mcneil** [comment]
[Confluence Doc](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3434119169/VBMS+connect_vbms+Gem+Deprecation) and [whiteboard](https://vfs.atlassian.net/wiki/spaces/PRT/whiteboard/3444047878)
