### ISSUE TITLE
Copy of VRE | Refactor code away from Central Mail

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#91196]
## Issue Description
_Any use of CentralMail namespaces within the VRE submission workflow needs to be refactored, ie. `CentralMailSubmissionSerializer` and `CentralMail::DatestampPdf`, etc._

---
## Tasks
- [ ] refactor submission code to remove "CentralMail" references, reuse other existing class if possible

## Acceptance Criteria
- [ ] no use of CentralMail classes within the submission workflow
- [ ] new code is 100% covered by unit tests
- [ ] new code is 100% documented - yardoc syntax
