### ISSUE TITLE
[Design] Badge Indicator: Finalize Designs for Badge Indicator 

### ISSUE THREAD

**Issue by ACParker89** [department-of-veterans-affairs/va.gov-team#91204]
### Background 
Based on [https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/badge-indicator#user-outcomes](url) My VA will be updating the dot indicator to a badge indicator in the Health Care section

### Tasks
- [x] Update designs pending any feedback from DSC or design intent
- [ ] Review changes with team (if needed)
- [x] Final check with team to proceed with dev

### Acceptance Criteria 
Final designs are fully approved by 
- [x] FE
- [x] BE 
- [x] PM
- [x] PO

**Comment by ajakabcin** [comment]
No issues reported from Design Intent or DSC - moving forward!
