### ISSUE TITLE
[FE] Badge indicator: Implement badge indicator on My VA

### ISSUE THREAD

**Issue by ACParker89** [department-of-veterans-affairs/va.gov-team#91205]
### Background 
We will be upgrading the dot indicator currently in production indicating unread messages in the health care section on My VA to be a badge indicator - that is an icon with a count telling the user how many unread messages they have.

### Tasks
- [ ] Create feature flag for badge indicator on My VA
- [ ] (Pending outcome of #91209) Make necessary updates to Secure Messaging connection to call number of unread messages
- [ ] Include error handling when we are unable to determine if there are unread messages
- [ ] Replace dot indicator with badge indicator per design specs
- [ ] Write/update unit and e2e tests
- [ ] Move to validation 

### Acceptance Criteria
- [ ] Feature flag exists on the va.gov feature flag list and is ready to be enabled or disabled once work is complete
- [ ] Connection to SM is working properly
- [ ] Badge indicator is visible on My VA

**Comment by ACParker89** [comment]
@nickjg231 - will review in case of capacity!

**Comment by mtcA6** [comment]
In lieu of this work we've been asked to redesign MyVA incorporating this as an idea within that effort. 

The new epic is: [EPIC | MyVA Refocus on Driving User Actions #104965](https://github.com/department-of-veterans-affairs/va.gov-team/issues/104965)
