### ISSUE TITLE
[FE, PM] Badge Indicator: Confirm technical approach with SM and Mobile teams

### ISSUE THREAD

**Issue by ACParker89** [department-of-veterans-affairs/va.gov-team#91209]
## Background
Current dot indicator implementation calls the secure messaging endpoint to tell us whether there are unread messages or not. We also pull in the unread count for folders that are not created by the Veteran. We need to make sure this will give us an accurate count of unread messages and that it is consistent with how the mobile team reads the number of unread messages.

## Tasks
- [x] PM to schedule meeting with secure messaging team and mobile team to confirm how they are determining unread messages count
- [x] Create draft documentation outlining our technical approach
- [x] Align technical strategy so we are consistent with both experiences
- [x] Discuss testing strategy with SM team

## Acceptance Criteria
- technical approach for implementing unread messages count via badge indicator is in alignment with secure messaging and mobile teams

**Comment by allisonlu** [comment]
I've updated the technical implementation section on dot indicator FE docs: 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/dot-indicator/create-dot-indicator/documentation/my-va-health-care-inbox-dot-indicator-FE-documentation.md#technical-implementation
