### ISSUE TITLE
Investigate KMS Rotation Job decryption failed

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#91228]
Steve Albers contacted Ryan and I with a concern over [some KMS rotation jobs that failed in the past week](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20-%28%22Couldn%27t%20find%20InProgressForm%20with%20%27id%27%22%20OR%20%22Mobile%3A%3AV0%3A%3AVet360LinkingJob%22%20OR%20%22BGS%3A%3ASubmitForm686cEncryptedJob%22%20OR%20%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20OR%20%28%22HCA%3A%3ALogEmailDiffJob%22%20%22could%2Bnot%2Bobtain%2Ba%2Bconnection%2Bfrom%2Bthe%2Bpool%22%29%29%20status%3Aerror%20%22kmskeyrotation%20rotatekeysjob%22%20%22died%20with%20error%20decryption%20failed%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=false&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1723667123928&to_ts=1724271923928&live=true).

## Tasks
- [ ] Investigate why we're receiving these errors
- [ ] Contact associated teams to resolve or create a new issue to resolve (whichever is applicable)

## Acceptance Criteria
- [ ] The cause of the listed KMS key rotation issues are known and addressed

**Comment by stevenjcumming** [comment]
The error "died with error Decryption failed." comes from Aws::KMS::Errors::InvalidCiphertextException which is generally caused by corrupted, missing, or otherwise invalid ciphertext. 

I couldn't find a specific dead job in production to verify the exact cause of the error.

**Comment by stevenjcumming** [comment]
The errors are cause by a specific record for `CovidVaccine::V0::ExpandedRegistrationSubmission` decryption failure
