### ISSUE TITLE
Add COVID-19 alert to Pre-discharge claim page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#9122]
## User Story or Problem Statement
As a Veteran using the BDD program, I need to know how COVID-19 is affecting claims so I can plan accordingly.

VBA has provided alert messaging that will need to be approved by the JTF before being published on the [Pre-discharge claim page](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/).

## Goal
Approved COVID-19 alert at top of Pre-discharge claim page

## Objectives or Key Results this is meant to further
Alert Veterans and service members of COVID related issues to claims.

## Tasks
- [ ] Alert text approved by JTF
- [ ] Alert text added to page and copyedited
- [ ] Publish page
- [ ] Validate on live site

## Acceptance Criteria
- [ ] Alert confirmed on live page
---

**Comment by stephorkandatx** [comment]
Closing this out, no longer needed. Work is being covered by another item
