### ISSUE TITLE
[CST] Remove error message when user removes problematic file

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#91235]
## Value Statement
**_As a_** Veteran
**_I want to_** understand which files are causing errors and which aren't
**_So that_** I feel comfortable knowing my file uploads have been successful

---
## Background Context

When adding a file that causes an error, removing that file does not remove the error message. Even after adding a **new** second file, the error message from the first file remains. See screenshots below.

<img width="1755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejE0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9036f45b631279a20c49143cae638757d53c251/Screenshot%202024-08-21%20at%205.11.27%E2%80%AFPM.png" alt="Screenshot 2024-08-21 at 5.11.27 PM.png" />

Steps to reproduce:
1. Add a file that triggers the error message "Error uploading <file name>" (do not submit it)
2. Remove that file
3. Error message is still there
4. Add a new file
5. Error message from the previous file is still there

Noticed while doing [5103 design QA](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724247726542/35234e4a506bf814d8ab1f89038b05a72ca3c9d8?sender=u80fb5a3b8f7951f35d701197)

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
There are a few possible design solutions that should be discussed as a team to determine which one is most feasible:

1. The error message goes away on its own after a certain amount of time. 
2. The error message goes away once the problematic file has been removed
3. The error message goes away if a new file upload occurs

### Enablement team (if needed)
@member of team

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Determine best design solution_
- [ ] _Implement agreed upon solution_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Veterans are no longer confused about errors that relate to files that they've removed or replaced_
- [ ] _AC_
- [ ] _AC_
