### ISSUE TITLE
[Research] 10-10CG: Write convo guides and research plan for caregiver study

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#91231]
## Issue Description
To prep for a research study with caregivers to fill in gaps post desk research and in preparation for work on the caregiver clarification epic.

### Benefit to the Veteran/Caregiver
Provide helpful and relevant content to the caregivers in the most applicable location - before or during the online application. 

## Where: 
- Research planning working session 8/20/24
- Post July updates, we evaluated ux opportunities and next steps and conducted a planning working session (UX team, PM and OCTO UX Lead). 
- We decided to recruit 2 cohorts of caregivers and ask them feedback on the content of the current form and ask them additional interview questions depending on their caregiver program status.
- The conversation guides and research plan needs to be created to review with the team before the next working session.

### Why:
- Better understand what content is clear and what could use more clarification from the caregivers' perspective
- Better understand where caregivers expect that content to be within the application journey

### What
- Create the research plan
- Create the convo guides with interview questions for both cohorts
- Include planning to test the new facilities search and confirmation page via both staging and prototype

### References/Resources

- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721340803913/0adab3113f083b21f225142fa83d28296648e31c?wid=0-1723228965662)
- [Facilities research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/research/2023-04-Facilities%20and%20Overall%20Usability%20Research) - (needs updated)
- [Platform research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- [Platform convo guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

---
## Tasks/Order of Operations
- [x] Use templates to draft research plan and convo guides
- [x] Write draft of research plan (AA)
- [x] Write draft of convo guides (JS)
- [ ] Work with Luis to gather analytics around journey before intro page
- [x] Review with UX team, UX lead and PM 
- [x] Create simple prototype for facilities flow + confirmation page (as backup plan)
- [x] Make any changes + finalize dates

### Sign offs
- PM (Heather)
- UX lead (Lois)
- [ ] Add approval notes/dates to research plan before submitting

## Acceptance Criteria
- All research artifacts are ready to submit for research review + recruitment
---

**Comment by aagosto90** [comment]
@jessicastump Created a folder for this research study [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2024-09-1010CG%20Caregiver%20Study). Feel free to rename it if you want

**Comment by jessicastump** [comment]
I started the convo guide over [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/research/2024-09-%20Caregivers%20Study%20-%20form%20content%20and%20user%20interviews) in the caregiver product folder...a research folder we haven't got to use in awhile! ;)

**Comment by aagosto90** [comment]
> I started the convo guide over [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/research/2024-09-%20Caregivers%20Study%20-%20form%20content%20and%20user%20interviews) in the caregiver product folder...a research folder we haven't got to use in awhile! ;)

Oh okay - I deleted that folder I created and moved the research plan to there :) Thanks!

**Comment by jessicastump** [comment]
Noting here from Slack convo:
All items are out for team review and getting feedback from Lois (which will happen sometime next week)

- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/research/2024-09-%20Caregivers%20Study%20-%20form%20content%20and%20user%20interviews/research-plan.md)
- [Convo guide cohort 1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/research/2024-09-%20Caregivers%20Study%20-%20form%20content%20and%20user%20interviews/convo-guide-cohort1.md) - for mostly caregivers who said in the screener question they are enrolled in the program
- [Convo guide cohort 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/research/2024-09-%20Caregivers%20Study%20-%20form%20content%20and%20user%20interviews/convo-guide-cohort2.md) - for caregivers + Veterans, 2 assistive tech users

**Comment by jessicastump** [comment]
Link to Slack Canvas for drafts and feedback convo from Lois:
- [Research Plan](https://dsva.slack.com/docs/T03FECE8V/F07KURC2H6G)
- [Convo Guide 1](https://dsva.slack.com/docs/T03FECE8V/F07KBQS608P)
- [Convo Guide 2](https://dsva.slack.com/docs/T03FECE8V/F07LF5TU9NC)

**Comment by jessicastump** [comment]
Prototype links:
- [Confirmation page](https://www.figma.com/proto/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2930-67957&node-type=instance&t=EUUhWg1tjIgVWLwc-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A4727&starting-point-node-id=2930%3A67957)
- [Facilities search](https://www.figma.com/proto/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2938-72931&node-type=instance&t=Zu7Tk6YxVsoRXLWF-1&scaling=min-zoom&content-scaling=fixed&page-id=2468%3A21603&starting-point-node-id=2938%3A72931)

**Comment by jessicastump** [comment]
[Link to research repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/674)
