### ISSUE TITLE
[Design] Add info to confirmation/detail page to clarify steps for rescheduling

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#91239]
## Background
On the confirmation/detail page, we need to ensure information is included to Veterans know how to reschedule, as our research findings pointed towards confusion around how this will work.

## Details
Rescheduling: 3 participants mentioned being unsure about how to reschedule their appointment after canceling. 

> 	P7: "If I wanted to reschedule, I would probably go ahead and schedule a new appointment first and then cancel this one. Because I don’t see a link here to revise this appointment. I don’t see anything on this page to change it."

> 	P15: "I would schedule a new appointment (from the appointment details page to schedule the remaining  appointments of the referral).

## Tasks
- [ ] Determine what content or UI changes are needed on the page to communicate/clarify the rescheduling process 
- [ ] Ensure no overlap with [adding cancelation information](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/92733)
- [ ] Have content reviewed by Laura if needed
      
## Acceptance Criteria
- [ ] Proposed changes shared with UX
- [ ] Content reviewed
- [ ] Figma files updated

**Comment by cgednalske** [comment]
@benbrasso-agile6 added another ticket we had discussed (but then I forgot about)

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/91239?planning-poker) with Zenhub @cgednalske @Cieramaddox
