### ISSUE TITLE
EPIC | Oracle Health (formerly Cerner) Notification Preference Migration 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#91245]
## Background

We've received one email chain related to Oracle Health notification preferences. Creating this epic should we need it. 

The only notification preference from OH that is novel to VA.gov is "Health Records". MHV today doesn't have something similar.  

<details><summary>Additional context shared </summary>
<p> 

Presentation below was shared by Carnetta 
- [CB11 Patient portal modernization release notes - 6-21-2024.pptx](https://github.com/user-attachments/files/16711161/CB11.Patient.portal.modernization.release.notes.-.6-21-2024.pptx)

The presentation contains, new screen shots of interest from My VA Health patient portal (Oracle Health previously Cerner):
- List of My VA Health features that sends notifications
- Patient preference page to enter edit their notification preferences and email address
- Notification email sent (note no PII)

Additional Notes from Carnetta:
- OH (Cerner) has one patient portal framework that both VA and DoD purchased.
     - Any frame-work changes made to DoD’s version, [MHS Genesis](https://myaccess.dmdc.osd.mil/identitymanagement/app/login), will reflect in VA’s version [My VA Health](http://www.patientportal.health/).  
- OH (Cerner) is still VA’s replacement for all VAMC’s VistA (CPRS) electronic health databases that will store VA patient and DoD patient health records together.
     - I believe all DoD hospitals already converted to using OH (Cerner)
- DoD will continue to use [MHS Genesis](https://myaccess.dmdc.osd.mil/identitymanagement/app/login) as their DoD patient facing portal requiring the DS Logon credential.
- VA will use [VA.gov](http://www.va.gov/) as the VA Health and Benefit portal that will include VA health data from the VistA and OH data bases requiring a Login.gov or ID.me credential.
     - VA will then stop using My VA Health and My HealtheVet as patient facing portals.

</p>
</details>

## Tasks 

```[tasklist]
### Initial Discovery/ Brain Dump
- [ ] tbd
```

```[tasklist]
### Design Intent
- [ ] review our design decisions/moks/journey
- [ ] make changes to design post design intent
``` 

```[tasklist]
### Research/Design Midpoint Prep
- [ ] Usability Research Plan
- [ ] Usability Convo Guide
- [ ] Usability Research Logistics
- [ ] Conduct the Study
- [ ] Synthesize the Research
``` 

```[tasklist]
### BE/FE Development 
- [ ] This ends with midpoint review
- [ ] GA ticket for any FE work 
- [ ] PM | Domo or GA Updates
- [ ] BE | Data Dog Dashboard Updates
``` 

```[tasklist]
### Midpoint Feedback Implementation
- [ ] implement an midpoint review changes if needed 
``` 

```[tasklist]
### QA
- [ ] QA Spreadsheet 
- [ ] QA testing plan document  
- [ ] QA team ticket
``` 

```[tasklist]
### UAT
- [ ] Conversation Guide 
- [ ] UAT Research Plan 
- [ ] PM | go/no-go convo
- [ ] UAT Study Logistics / Kickoff
- [ ] Conduct UAT
- [ ] Research Synthesis 
``` 

```[tasklist]
### Launch Planning
- [ ] Release Plan 
- [ ] Contact Center Guide Updates - submit before staging review 
- [ ] Staging Review 
``` 

```[tasklist]
### Incorporate Staging Review Feedback 
- [ ] add staging review tickets
``` 

```[tasklist]
### Launch
- [ ] Go/no-go prod convo
``` 

```[tasklist]
### Post Launch
- [ ] Documentation Updates 
```

**Comment by jfinnerty13** [comment]
Also noting that it's been a year and this team hasn't reached out to us about adding a new notification. Do we want to close this since it's been over a year? @PatSiebenlist @alatempa

**Comment by alatempa** [comment]
After reading the thread I believe this one can be closed.
