### ISSUE TITLE
[CONTENT] Transform Health Services Library into Excel and save as .CSV file for Automation [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9125]
## User Story or Problem Statement
As a Engineer, I must have a full health services library transformed into Excel format, so I can automate and import this content into Drupal System Health Services.

## Goal
_Perform update of Health Service Library to include external (National) hyperlinks and improved writing _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Health Services Library update](https://drive.google.com/drive/folders/13ZTUm1U40BsC5MQcgGulcZ_DxvJAkDIQ)
[Excel format Automation Page](https://drive.google.com/drive/folders/13ZTUm1U40BsC5MQcgGulcZ_DxvJAkDIQ)

## Tasks
_Transform Health Services Library into Excel spreadsheet that can be saved as .CSV file:_
- [ ] Pull content from HSL, move to Notepad to drop bullets and formatting
- [ ] Copy and pull data into new Excel Spread Sheet line by Line
- [ ] Add related Hyperlinks required for each Health Service at end of excel
- [ ] Upload final copy into Google drives.

## Acceptance Criteria
* Pull content from HSL, move to Notepad to drop bullets and formatting
* Copy and pull data into new Excel Spread Sheet line by Line
* Add related Hyperlinks required for each Health Service at end of excel
* Upload final copy into Google drives.
