### ISSUE TITLE
Add Platform Website Orientation and Platform Support Overview videos to Orientation Sessions page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91268]
## User Story
As a VFS team member, I want to be able to find all of the orientation session videos in 1 place so that I can quickly and easily become oriented with the VA.gov Platform.

As a Governance team member who manages the Platform Orientation materials, I want to add all of the orientation videos to the Orientation Sessions page so that it's easier to maintain and keep up to date.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @erinrwhite 

## Description
Since the launch of the Platform Orientation process, we have added a couple new orientation videos: [Platform Website Orientation](https://www.youtube.com/watch?v=I3RFCuTEfBI&ab_channel=PlatformCrew) and [Platform Support Overview.](https://www.youtube.com/watch?v=iwIQU4XepNQ) For reasons unknown, these videos have been directly linked to in the New VFS Team Member github template, instead of added to the Orientation Sessions page where the other orientation videos are accessed. 

The purpose of this ticket is to add the Platform Website Overview video and the Platform Website Orientation video to the Orientation Sessions page. The benefit of this is that 1) all orientation videos are now maintained in the same space, 2) VFS teams who access the Orientation Sessions page but do not open a New VFS Team Member ticket will be able to view them,  3) the New VFS Team Member ticket will no longer need to be updated if/when the videos are updated, meaning older tickets will always point to the most up to date videos.

**Note:** This ticket will only cover adding the 2 videos to Platform Website, not updating the New VFS Team Member ticket to link to the Orientation Sessions page instead of directly to the videos. That work will take place in ticket #91263.

### Live pages
- [Orientation Sessions](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions) (Platform Website)
- [Platform Website Orientation](https://www.youtube.com/watch?v=I3RFCuTEfBI) (YouTube video)
- [Platform Support Overview](https://www.youtube.com/watch?v=iwIQU4XepNQ) (YouTube video)
- [Operational Guidance for Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Operational+Guidance+for+Orientation+Sessions) (Confluence operational)

### Drafted pages
- [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3433496577/91268+-+Copy+of+Orientation+Sessions)
- [Operational Support](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3433529345/91268+-+Copy+of+Operational+Guidance+for+Orientation+Sessions)

## Tasks
- [x] Following the existing format of the Orientation Sessions page, add the 2 videos to the page
   - If you need help completing the Overview section or the Questions/Support section, please reach out to @alyssagallion for Platform Support Overview and @jknipes for Platform Website Orientation. 
   - Both videos are for All new VFS team members
- [x] Be sure to update the Last Updated Date
- [x] Add both videos to the Operational Guidance for Orientation Sessions page on Confluence. The session owners are Platform Support team and Platform Content team

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] The Platform Support Overview video and the Platform Website Orientation video are now available to VFS teams via the Platform Website
- [x] The operational guidance for supporting Platform Orientation is up to date and accurate.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@jknipes @alyssagallion as PMs of the 2 teams who own these videos, I wanted to let you know that we're moving them out of the ticket and onto the Orientation Sessions page. Please lmk if you have any questions!

**Comment by KKitagawa-Bosch** [comment]
@erinrwhite drafted pages for [operational guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3433529345/91268+-+Copy+of+Operational+Guidance+for+Orientation+Sessions) and [orientation sessions](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3433496577/91268+-+Copy+of+Orientation+Sessions) are added to the ticket and linked here. 

I added the new info to both draft pages and it's ready for you to look over. One question: any strong feelings about what order they should be in? Are they alright where they're at? 

Additionally, the ticket says to add the videos to the operational guidance page, but the other sessions don't have the video links, any ideas there? Just wanna make sure I get it right!

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch I think the placement/order of info is looking good!

For the operational guidance, it kinda makes sense that none of the videos are linked, and that there's a link at the top of the page to the Platform orientation sessions page. So, for the operational guidance I would match the format of the other orientations and not add direct links to the videos - just the info _about_ the videos.

**Comment by KKitagawa-Bosch** [comment]
Fantastic! In that case, are we good to publish these Monday? @erinrwhite

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch yes! 👍🏻

**Comment by KKitagawa-Bosch** [comment]
Confluence updated for both [Orientation Sessions](https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Orientation+Sessions) and [Operational Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2062024864/Operational+Guidance+for+Orientation+Sessions) @erinrwhite

**Comment by erinrwhite** [comment]
@KKitagawa-Bosch looking good! Will check again this afternoon to make sure the platform website published.

**Comment by erinrwhite** [comment]
[Page live on the Platform website!](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions) Looking good to close; boxes checked. @KKitagawa-Bosch
