### ISSUE TITLE
Update New VFS Team Member templates per Platform Team feedback

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91263]
## User Story
As a Platform team member, I want to ensure that VFS teams are following the most up to date guidance on Platform policies and processes so that they're able to quickly begin supporting their team to build on VA.gov.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: @shiragoodman 

## Description
Governance team reached out to all of the Platform teams and Platform COPs via ticket #87434 for help in getting the New VFS Team Member template and New VFS Team template up to date.

The purpose of this ticket is to review all of the completed tickets from the other Platform teams and COPs and make the requested changes to both the New VFS Team template and the New VFS Team Member template.

In addition, we will also make the following changes:

- Add `Watch the Analytics orientation recording` to the Designer & Research section of the New VFS Team Member template [per request of Naomi](https://dsva.slack.com/archives/GNF5GSD9N/p1724279313251299)
- In the General section of the New VFS Team Member template, change the language and the link re: the Platform Support Overview video and the VFS Orientation for Platform Website video (AKA Platform Website Orientation) to point to the a appropriate anchor link on the Orientation Sessions page per ticket #91268.

### Live pages

- [New VFS Team Member template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D) (gh template)

- [New VFS Team template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team%2C+platform-tech-team-support&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D) (gh template)

### Drafted pages
- [To-Do List](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3466199279/91263+-+Update+New+VFS+Team+Member+Templates)
- [New Team Member Template](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3467739261/New+VFS+Team+Member+Template)
- [New Team Template](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3466395866/New+VFS+Team+Template)

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have updated the New VFS Team member template based on feedback from Platform teams
- [x] We have updated the New VFS Team template based on feedback from Platform teams

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by KKitagawa-Bosch** [comment]
Created a to-do list based on guidance 
Added draft pages to ticket info

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman updated both of the drafts in confluence! You can also find the to-do list linked in the drafts section, which will tell you (1) what I changed and (2) what I have questions/comments about!

**Comment by shiragoodman** [comment]
thanks @KKitagawa-Bosch ! I will take a look soon.

**Comment by shiragoodman** [comment]
lol @KKitagawa-Bosch can you share the Confluence link? Sorry, I am a bit delayed getting to this and I'd like to review. For that reason, I think it's safe to say that this ticket will move into the next sprint.

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman I know we discussed in refinement yesterday, but for posterity, the confluence links are in the ticket under "Drafted pages"!

**Comment by shiragoodman** [comment]
Ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/93990 created to rerecord the VA.gov Overview video

**Comment by KKitagawa-Bosch** [comment]
Changes committed to tickets! Had to do them all over again because the markdown from confluence didn't copy correctly which is...cool. Lesson learned for next time!

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman how would you like me to handle keeping track of the three videos we're still waiting on?

**Comment by shiragoodman** [comment]
Good question @KKitagawa-Bosch ! Could you create a ticket for our backlog and then tag me in it?

**Comment by KKitagawa-Bosch** [comment]
Created #91437 to handle videos, and closing this ticket!
