### ISSUE TITLE
[CST] Update link to Claim Letters page from 5103 document request page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#91277]
## Background Context

Based on most recent CAIA content recommendation we want to update the language of the link to the claim letters page

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
[FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3531-11403&t=Pu3VW3fGEYCCKeyb-4)

### Enablement team (if needed)
@jstrothman @laurwill 

## Engineering 
- The link to be updated can be found in `src/applications/claims-status/components/claim-document-request-pages/Default5103EvidenceNotice.jsx`

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] Update link text in `Default5103EvidenceNotice` component
- [x] Update unit tests to reflect new wording

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] _Link language has been updated_
- [x] _Behind 5103 feature flag_
