### ISSUE TITLE
Design documentation project plan definition

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#91278]
Create a project plan for documenting design processes and ways of working.

#### Background
In the beginning of this project, the team only had one designer. They were primarily focused on driving towards a hard deadline to relaunch the Pension form. Documenting processes was not a priority at that time. Once the form was launched, the processes that had worked well to launch the form were not working well to iterate on the form. Also, at about the time the form relaunched the VA switched design tools from Sketch to Figma. With still only one designer on the team, efforts to refine and document processes and norms typically were not prioritized above work on the product. Since then, there have been several designers on the program and the lack of clearly defined processes and expectations has led to inefficiencies and confusion.

#### Problem statement
Lack of design process documentation causes inefficiencies, inconsistencies, and confusion.

#### Tasks
- [x] Review Slack Canvas from recent ways of working conversation
- [x] Meet with Daniela, Elisabeth, Dan, Maddy (as needed) for additional context and collaboration
- [x] Collect relevant resources to reference (e.g., documentation from other teams, relevant OCTO/Platform documents, guidelines, expectations
- [x] Define deliverables
- [x] Define project scope (we want to take a lean approach so this doesn't take away from other work)
- [ ] Define milestones and timing

#### Acceptance criteria
- [x] Project plan created that includes: scope, deliverables, project information sources, milestones and timing, assumptions, and people involved

**Comment by gmaciolek** [comment]
We've talked through and documented a high-level plan: [Project plan definition document](https://docs.google.com/document/d/12SY-4qwtOJyumyZE3gBA0MmaoIrYyj7L6tORt448UiI/edit?usp=sharing)

Instead of defining project milestones and timing, we'll plan to create a few tickets for the backlog to get us started and then revisit this doc regularly. We can add to or adjust the plan and make new tickets, based on priority.

Next steps:
- Gretchen: create a ticket to document the design ticket workflow and standards (for Gretchen)
- Gretchen and Elizabeth: continue to update our new Figma source of truth file so it matches production
