### ISSUE TITLE
[CST] Update 5103 document request page header (and breadcrumb on larger screen size)

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#91276]
## Background Context

Update the header of the 5103 document request page to match the latest content recommendation. The breadcrumb (on larger screen sizes) and browser tab title must also be updated to match the new H1.

### Before (old)
<img width="367" alt="Screenshot 2024-08-22 at 12 09 02 PM" src="https://github.com/user-attachments/assets/d0ad8233-a544-4297-885f-621ebd469110">

### After (new)
<img width="355" alt="Screenshot 2024-09-10 at 12 27 39 PM" src="https://github.com/user-attachments/assets/6d644fea-943f-4120-9f4e-8268f0784a2e">

### Old breadcrumb: "5103 Evidence Notice"
<img width="736" alt="Screenshot 2024-08-22 at 11 57 26 AM" src="https://github.com/user-attachments/assets/1e2f14f9-b958-4c0f-8209-34bcadfd9692">

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
[FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3531-11416&t=Htx2UI7ZCs1wH0xE-4)

### Enablement team (if needed)
@jstrothman @laurwill 

## Engineering 
- **Note:** This change needs to be reflected for both the `Automated 5103 Notice Response` and `5103 Notice Response` tracked item alerts / pages

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] Update h1 of 5103 document request page to match spec for both Custom 5103 and Standard 5103
- [x] Update breadcrumb to match h1 for both Custom 5103 and Standard 5103 (on larger screen size)
- [ ] Update browser tab title to match the h1 for both Custom and Standard 5103
- [ ] Remove outdated logic related to differentiating language between two types of 5103s

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _h1 for Custom 5103 and Standard 5103 document request page matches the latest content in the spec_
- [ ] _Breadcrumb for larger screen sizes has been updates to match what is in the spec_
- [ ] _Browser Tab title is updated to match the new h1_
- [ ] _Behind 5103 feature flag_

**Comment by skylerschain** [comment]
Updated new breadcrumb suggestion from: "Review **your** evidence list (5103 notice)" to "Review evidence list (5103 notice)"
