### ISSUE TITLE
[CST] Update content in 5103 document request page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#91281]
## Background Context

Aside from the [header](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91276) and [links](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91277), the rest of the content in the 5103 document request page needs to be updated to match the most recent content suggestions.

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
[FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3531-11428&t=Pu3VW3fGEYCCKeyb-4)

### Enablement team (if needed)
@jstrothman @laurwill 

## Engineering 
- The component to be updated can be found here: `src/applications/claims-status/components/claim-document-request-pages/Default5103EvidenceNotice.jsx`

## Open questions
- Add here

## Tasks
- [ ] Design to add any necessary annotations to mocks/screenshots. 
- [ ] _pdate the content in the `Default5103EvidenceNotice` component to match what is in the spec - includes headers, paragraph text, and link text

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Content matches most recent CAIA content suggestions as defined in the spec_
- [ ] _Behind 5103 feature flag_

**Comment by skylerschain** [comment]
Scope of content updates is highlighted by the green lasso annotation:

<img width="959" alt="Screenshot 2024-08-26 at 4 38 16 PM" src="https://github.com/user-attachments/assets/c8ed8f05-83e9-4a07-8f10-4a49923a1e66">

**Comment by jstrothman** [comment]
After [slack discussion](https://dsva.slack.com/archives/C04KHCT3ZMY/p1725374961284919) with @KKitagawa-Bosch I agree we should make the [governance content recommendations in this GH issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91814) specifically to adjust the sentence re adding evidence at any time.

Change from:
>"Note: You can add evidence at any time. But if you add evidence later in the process, your claim will move back to this step. So we encourage you to add all your evidence now."


Change to:
> Note: You can add evidence to support your claim at any time. However, if you add evidence later, your claim will move back to this step, so we encourage you to add all your evidence now.

**Comment by skylerschain** [comment]
Updated language in mock to reflect the above. 

@samcoforma we can discuss when we review these tickets today

**Comment by skylerschain** [comment]
Adding one AC item to update this text on the 1P alert as shown [here](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=4109-31799&t=3ReHT6Ncnk9MSs0M-4). This ticket is updating the same wording on the document request page, so adding an AC for the 1P alert wording as part of this ticket.
