### ISSUE TITLE
DR | Fix prototype issues

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#91286]
## Value Statement

**_As a_** Decision Reviews team member
**_I want to_** review our prototypes & fix issues 
**_So that_** we always have it available for testing & review

---

## Background Context

Our NOD prototype has broken path references. We need to fix them and review it, and other prototypes to ensure they still work.

## Acceptance Criteria

- [ ] Completed review of all DR prototypes for issues

## Tasks

- [ ] Fix NOD prototype links
- [ ] Review all DR prototypes for issues

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by shaunburdick** [comment]
All fixed... for now.
