### ISSUE TITLE
Migrate to RESTful APIs

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#91282]
## Issue Description
_The BGS SOAP service that the 686/674 form currently uses is being depreciated, so those services need to be migrated to the RESTful API replacements. The target to depreciate the SOAP service is March 2025._

Note, there is an [ongoing discussion](https://dsva.slack.com/archives/C0547Q0K0LF/p1724183314708689) about whether or not VA.gov should manage the assignment/creation of EPs and that convo should be revisited when the migration work is picked up.

An epic most likely needs to be created to organize this work.

---
## Tasks
- [ ] Migrate services to RESTful API replacement
- [ ] Validate that field validations used for BGS SOAP still align with those used for RESTful API (e.g. 10 digit phone number)

## Acceptance Criteria
- [ ] All BGS SOAP services have been migrated to their RESTful API counterparts.
- [ ] Validation on VA.gov matches validation used by RESTful API counterparts.
---

**Comment by sanjabaj2** [comment]
Attaching a procs flow that MAS uses. Mass is recently integrated using RESTfull APIs. 

[RBPS 686c Process Flow Chart V3 1.pdf](https://github.com/user-attachments/files/24777595/RBPS.686c.Process.Flow.Chart.V3.1.pdf)
