### ISSUE TITLE
Limit phone number to 11 digits

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#91285]
## Issue Description
_#91155 uncovered that the 686/674 application attempts to insert a value into the PHONE_NBR column of the VNP_PTCPNT_PHONE table, but the value's length exceeds the maximum allowed for that column. This error is coming the 3rd party API as we're sending it 12 characters instead of the maximum of 11._

An example of the error that is occurring is in [this link](https://vagov.ddog-gov.com/logs?query=%22BGS%3A%3ASubmitForm686cJob%20received%20error%2C%20retrying...%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZF2Yg-deFyyZAAAAAAAAAAYAAAAAEFaRjJZaDJtQUFEck9hTmVBSGt4TkFBNAAAACQAAAAAMDE5MTc2NjUtZDk4MC00NDE0LTk5YzgtYzMxMTJjZmUxZjg2&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718028344681&to_ts=1718633144681&live=true) in the payload key "nested_error". This is causing the expected display of a phone numbers (907-707-9107) to trigger an error.

This ticket should not be worked on until https://github.com/department-of-veterans-affairs/va.gov-team/issues/91155 is resolved.

Several open questions remain about this change. See [this thread](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91155#issuecomment-2305714212).
- Why are we now seeing the error in #91155? What changed?
~~- RBPS may be relying on dashes, so we need to confirm the change with them first.~~
- Could this error be related to adding international phone numbers?
- Do we need to work with RBPS to support accepting international numbers that exceed 11 digits?

---
## Tasks
- [ ] Remove dashes in phone numbers
- [ ] .strip the phone number
- [ ] Review logs to confirm change prevents claim failures

## Acceptance Criteria
- [ ] 686/674 application sends a maximum of 11 digit phone numbers to BGS
- [ ] Phone number error no longer occurs
---

**Comment by mjknight50** [comment]
Moving this over to @tfink419 as it relates to the https://github.com/department-of-veterans-affairs/va.gov-team/issues/91155

**Comment by sanjabaj2** [comment]
The [dependent ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91155) is closed. Should be able to unblock this. It would reduce number of cases that go via backup path.

**Comment by steele-lm** [comment]
@sanjabaj2 I think we had a lot of [unanswered questions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91155#issuecomment-2305714212) around why we're now seeing this issue and if we need to account for international numbers, which can exceed 11 digits. I'll add the questions to this ticket.

**Comment by steele-lm** [comment]
BGS confirmed that VA.gov can strip out the dashes from the phone number value with no negative impact on BGS.
