### ISSUE TITLE
[CST] Update subheader text for 5103 letter in Claim Letters page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#91308]
## Background Context

We want to update this string to match the most recent CAIA content recommendations

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
[FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3561-11114&t=S0SzSYMzmoo66M3y-4)

### Enablement team (if needed)
@jstrothman @laurwill 

## Engineering 
- Component to be updated can be found here: `/src/applications/claims-status/components/claim-letters/ClaimLetterListItem.jsx`
- Should just require updating the `docTypeToDescription` method

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [ ] _Update subheader language for a 5103 letter list item (both Custom and Standard 5103s) in the Claim Letters page_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _In the claim letters section of CST, change the "5103 letter" label to read "Evidence list (5103 notice)"_
- [ ] _Behind 5103 feature flag_

**Comment by skylerschain** [comment]
Updated "After" image to add latest content suggestion
