### ISSUE TITLE
[Design] Create Userflow options

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91305]
## Tasks
- [ ] Perform "desk research" as needed, to inform the work. E.g., is there DS guidance to review? Are there past research findings to review? 
- [ ] Create userflow options
- [ ] Create any needed markup into Figma Page or frames for heading annotations, aria label values, link paths and/or GA Event values
- [ ] Identify pros and cons of options 
- [ ] Review options and get feedback from Kristen to ensure alignment with IPT needs

### Who needs to review? Remove rows that aren't needed for this work.   
- [ ] UX team
- [ ] Check in team (e.g., PO, DM, engineers)  
- [ ] VA OCTO PO's (e.g., Kay, Kristen, Mark, Stephen)

### Does Check-in PO need links or content for f/u tickets? If Yes, provide details in comments. 
- [ ] Yes
- [ ] No
      
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work was reviewed by groups indicated above
- [ ] If needed, provide Check-in PO with links or content for f/u tickets

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/91305?planning-poker) with Zenhub @cgednalske @zach-park

**Comment by benbrasso-agile6** [comment]
Let's go ahead and close this ticket. Next step can be to create some low-fi wireframes. Ticket to point for next sprint - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/92856

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1725552606300/0a937e565b2d6f1704eb410eedaae09a8696e661?sender=uff786461dfce1a1982aa7640
