### ISSUE TITLE
Add git SHA into environment for referencing in initializers/app_info.rb

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#9131]
## Background

We used to have the current SHA of the release available in the initializer. This was broken when infra moved to Docker.

See discussion towards end of [this thread](https://dsva.slack.com/archives/CQHBJ5U06/p1587585568413700)

## Acceptance Criteria

- [ ] `X-Git-Sha` header is populated from each environment
- [ ] `api.va.gov/v0/status` returns the correct SHA

## Tasks

- [ ] Add the `ref` to environment deployment [here](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-worker-vagov-prod.yml#L50) in each env for `vets-api`
- [ ] :point_up: in each env for `vets-worker`
