### ISSUE TITLE
All Content Team Members: Platform Security Survey

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91317]
## Issue Description
Platform Security is asking all Platform and VFS teams to complete **[this survey](https://forms.office.com/Pages/ResponsePage.aspx?id=Ixtf6a-r7kWCHberJRqzv8ddiLA4xJ1LrUjuXVjyRLdURElERkNFU1FBNVMzU09XSlI3STdEU1laSS4u)** so that they can gather information about security-related information as we start to prepare our ATO package for next year. We're sending the survey out to Platform teams first as a way to test the survey and make sure the questions are clear before we send it out to VFS teams.

"_Unfortunately, we were asked to use Microsoft Forms over the survey tool Platform teams typically use since the responses might include more sensitive information. We were unable to configure it to be available outside of the VA network, so a person completing this form would need to be **logged in to the VA network to complete it**. Please let us know if this causes any major issues as this is feedback we would like to have_!"

### Estimated time to complete survey: 5-10 minutes
---
## Tasks
All Team Members Complete the Survey + report any problems in the comments
- [x] Joe Knipes
- [ ] Jill Taylor
- [ ] Lauren Conrad
- [ ] Brian Smolensky

## Acceptance Criteria
- [ ] All tasks completed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91317?planning-poker) with Zenhub @BSmolensky @taylojill @laucon

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91317?planning-poker) with Zenhub @cmarion93

**Comment by jknipes** [comment]
Joe Knipes: I was unable to open the link to the survey directly, and received the message `Set up your device to get access`. I was unable to paste the survey link into Chrome on my remote desktop, as VA browser setups prohibit pasting links. I had to manually enter the very long URL into Chrome on my remote desktop to take the survey.

**Comment by jknipes** [comment]
Closing ticket per this clarification in Slack: [Only one member from each team needs to take the survey](https://dsva.slack.com/archives/GMX26FF9D/p1724865360529999?thread_ts=1724348279.986269&cid=GMX26FF9D)
