### ISSUE TITLE
Modify Collab Cycle Request update script to include SR artifact & endpoint monitoring changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91315]
## User Story
As a VFS team member going through Collaboration Cycle, I want to rely on the guidance within my Collaboration Cycle Request ticket for Staging Review prep so that I know I'm sharing the right artifacts with Governance team.

Assignee: @it-harrison 
Peer Reviewer: @erinrwhite 

## Description
We are changing the Staging Review artifact requirements, as well as adding a new QA standard re: endpoint monitoring. In order to ensure VFS teams that are already involved in the Collaboration Cycle have the most up to date guidance in their Collaboration Cycle Request GitHub ticket, we need to edit their open tickets.

The purpose of this ticket is to modify the script for updating Collaboration Cycle Request tickets to change the Staging Review artifacts section to our current guidelines. Please see [draft SR artifact section](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3250847791/88140+-+Erin+-+Updates+to+Staging+Review+artifact+guidance#Updated-SR-ticket) from ticket #88140. 

Note: Do not execute the script. That will occur in the ticket #89357 

## Impacted Artifacts
Script to update the Collaboration Cycle Request tickets

## Tasks
- [x] Modify the script so that it looks for the Staging Review Artifacts section and replaces it with the updates Staging Review Artifacts section per ticket #88140.

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have written a script that will update the SR artifacts section of all open Collab Cycle Request tickets
- [x] We have written a script that will update the QA artifacts section of all open Collab Cycle Request tickets

## Team Notification
- [x] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@it-harrison @erinrwhite heads up. this ticket is a top priority. please work on this and ensure it is complete before ANY other ticket this sprint. See comments made on ticket #89357 for additional details.

**Comment by it-harrison** [comment]
@erinrwhite 
* [This is the commit](https://github.com/it-harrison/ticket-body-update/commit/386ce0ee60fa4e751bfeead6c4c8beffd9364042) to the repo that adds support for this ticket
* And here is a [dummy ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91939) that was created by copying an existing ticket then updated by running the new script

**Comment by erinrwhite** [comment]
@it-harrison looking good **except** I am seeing extra spacing between the list items in the revised ticket, and I think that is because there are extra line breaks in `src/update_sr_artifacts/text.md` lines 14 and 16. Can you remove those line breaks and re-run?

![Screenshot 2024-09-03 at 1 11 17 PM](https://github.com/user-attachments/assets/1bc53927-97d6-43bf-a8aa-f6cd972548b7)

**Comment by it-harrison** [comment]
@erinrwhite the file has been updated and the [dummy file](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91939) looks better:

<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMld0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cad0dda87f59396a1c7b741d1216afa300de584/Screenshot%202024-09-04%20at%208.48.17%20AM.png" alt="Screenshot 2024-09-04 at 8.48.17 AM.png" />

**Comment by erinrwhite** [comment]
@it-harrison Looks great!! Full steam ahead.
