### ISSUE TITLE
Add evidence tracking to saved claims process

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#91326]
## Value Statement

Verify and/or add evidence tracking to the `saved_claims` process

---

## Background Context

- We are tracking the submission of forms but may not be tracking any evidence submissions that go along with it

## Outcome, Success Measure, KPI(S), and Tracking Link

- We track all aspects of a submission

## Open questions

- Can we track submissions as a subtask of the form submission or does each piece of evidence need their own entry?

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
Meeting setup for Thursday with Kyle

**Comment by eileen-coforma** [comment]
Currently in progress

**Comment by eileen-coforma** [comment]
Update when meeting today is over

**Comment by dfong-adh** [comment]
Synced with Kyle, unfortunately there are enough differences in how we will be handling the polling/processing that we believe maintaining separate solutions is the better solution for now.

**Comment by eileen-coforma** [comment]
Continuing to work on a separate solution, following conversation with Kyle

**Comment by eileen-coforma** [comment]
PR ready by today

**Comment by dfong-adh** [comment]
Created PR: https://github.com/department-of-veterans-affairs/vets-api/pull/18421

**Comment by eileen-coforma** [comment]
Will pair with @Mottie for review

**Comment by dfong-adh** [comment]
Merged, verified in staging

**Comment by eileen-coforma** [comment]
Verified in staging. Once production is in deploy today, will verify in prod as well.

**Comment by dfong-adh** [comment]
Verified in production.
