### ISSUE TITLE
Staging Review Medical Device Reordering Tool  

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#9133]
## Steps to complete Staging Review: 

- [X] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [X] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [X] Andrea and Megan to schedule meeting with VSP reviewers and **BAM2** attendees (as listed below)
- [X] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **BAM2** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/product-outline.md

- Link to [release plan] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/Release%20Plan.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)

- Link to the tool https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction
- Access information for the tool or feature in staging _*https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/benefits-memorials-2/qa-test-plan-users.md

- Link to your product test cases/test plan in TestRail with test execution logs Test Cases: https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_id=57&group_order=asc

  - MDT Test Plans: [Round 1](https://dsvavsp.testrail.io/index.php?/plans/view/35); [Round 2](https://dsvavsp.testrail.io/index.php?/plans/view/434)
  - MDT Reports: [Both Rounds](https://dsvavsp.testrail.io/index.php?/reports/overview/7) (6/1 & 6/4)

- Link to your accessibility test cases:
  - Certify that the following required accessibility tests are complete by checking each of these boxes (your accessibility specialist is available to help). Recommended items are optional, but highly encouraged.
  
    Required:
    - [ ] Read the [accessibility staging review documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) 
    - [X] Conduct axe browser scan, and document or address issues found 
    - [X] Ensure end-to-end tests - including the axe check, pass 
    - [X] Check color pairing for proper contrast 
    - [X] Check for colorblindness issues 
    - [X] Zoom to 200% at 1280px wide and confirm readability, no info cut off, etc 
    - [X] Repeat for 300% 
    - [X] Repeat for 400% 
    - [X] Navigate all pages and core functionality with keyboard only 
    - [X] Test all pages and core functionality happy path with MacOs + VoiceOver and/or NVDA+Firefox 
    
    Recommended:
    - [ ] Read the [accessibility post-launch processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/post-launch-audit-processes.md) 
    - [ ] Add keyboard end-to-end tests in CI/CD test runs 
    - [X] Conduct axe-coconut browser scan, document or address issues found 
    - [ ] Test with [WAVE tool](https://wave.webaim.org/) 

### Known issues

From [spot check](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5868)

* [#9113](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9113) - sitewide, forms [SCREENREADER]: Decorative content MUST be implemented in a way it can be ignored by assistive technology 

* [#9114](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9114) - sitewide, forms [SCREENREADER]: Consider updating phone number documentation in design system, to include spacing in the aria-label

* [#9115](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9115) - sitewide, forms [AXE-CORE]: Heading levels SHOULD increase by one

* [#9116](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9116) - sitewide, forms [FOCUS MANAGEMENT]: Focus outline SHOULD be removed from non-linked heading

Meeting attendees from **requesting team**
- Product Manager (required): Leah 
- DEPO product lead (required): Matt 
- Anyone else from your team who significantly contributed to the artifacts provided (required): Becca, Riley, Brad, Mahariel

## Scheduling
Preferred dates or times: Any time after  5/28 

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by meganhkelley** [comment]
hi @leahkeeler it looks like you're just using this template as a draft for now? that's great! just be sure to let @andreahewitt-odd and I know when you're ready to get something on the calendar :)

**Comment by tlei123** [comment]
@pjhill , fyi, I'm having Staging login issues trying to complete the copy/layout test-runs, BUT all _functional_ runs are completed.

Pls. let us know if lack of timely copy/layout test-results would hold up Staging Review or scheduling.

Thx much!

cc @leahkeeler

**Comment by pjhill** [comment]
> @pjhill , fyi, I'm having [Staging login issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5952#issuecomment-628943611) trying to complete the copy/layout test-runs, BUT all _functional_ runs are completed.
> 
> Pls. let us know if lack of timely copy/layout test-results would hold up Staging Review or scheduling.
> 
> Thx much!
> 
> cc @leahkeeler

@tzelei , understood, verification of copy and the resolution of any issues are usually less intense and disruptive, so I'm not overly concerned. It looks like this staging review is not scheduled yet, so you have some time to attempt to work out the login issues.

**Comment by leahkeeler** [comment]
@tzelei @pjhill I was going to schedule a staging review for next sprint - I can request it to be the 2nd week of the sprint - will that give you enough time?

**Comment by tlei123** [comment]
> @tzelei @pjhill I was going to schedule a staging review for next sprint - I can request it to be the 2nd week of the sprint - will that give you enough time?

Yep, 2nd week of next Sprint sounds good.

**Comment by jenstrickland** [comment]
@leahkeeler The accessibility test cases or the checklist criteria is not included on this staging review. I'm not sure if all the the issues from the [spot check](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5868) were remediated. 

Would your team please complete your accessibility testing and certify it on this review request? The options are to provide in TestRail, Markdown, or in the format of the [checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-test-cases-checklist.md) I previously showed the VSA Product Managers. The Markdown link above is for QA test cases, not the accessibility scans the team needs to do before a staging review.

**Comment by mnorthuis** [comment]
Hi all, it doesn't appear that the IA recommendations are in place - the URL and breadcrumb for the order form is incorrect, and I don't see the 2 static pages to validate those.  
- The IA work is accessible directly here https://github.com/department-of-veterans-affairs/va.gov-team/issues/6378 or linked to in the IA Request ticket here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-med-device-order.md

To complete a check on the IA work, I need to know:
- What is status of static content page, top nav, hub page and left nav changes?
- What is status of best bet changes within search?
- Has redirect request been submitted?

**Comment by rebeccawalsh** [comment]
Hi everyone,

I wanted to reach out to you all about some changes that happened after the MDT staging review.
Before, we were requiring at least one selection from a list that spans 2 pages, which made error handling an issue, both technically and design-wise. The form system also prevented us from building the (overdesigned) fix for it. **The solution was to combine the battery and accessory selections pages into one by stacking the pages' components**. It basically works the same, just on one longer page rather than two. Besides making the initial product selection simpler, it also simplified the process of editing selected products on the Review page. We were planning to explore new combined designs in the next iteration based on usability feedback, and we still will, but we wanted to keep our design changes minimal so that we don't push out our release date.

I just wanted to let you all know and get any feedback on the concept if you have any. Sketch of what we were thinking:

![image__3_.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/88e3d79f-4c08-4fb8-82d5-53cd6d6adf1e)

This can also be viewed in staging, though there may be a few hiccups there, with the API going offline.

@emilywaggoner @CrystabelReiter @meganhkelley @mnorthuis @peggygannon @jenstrickland @1Copenut @tlei123 @pjhill (Forgive me if I missed anyone)

CC: @rileyorr @leahkeeler

**Comment by jenstrickland** [comment]
Thanks for the update! This is a significant enough change that I'd like to re-audit at least that part of the application flow. Do you have a user and test case that I should use to audit?

**Comment by tlei123** [comment]
@camerontesterman , would **`vets.gov.user+1@gmail.com`** (Greg) be a good candidate for pre-populating the 6 device/accessory options (per Rebecaa's screenshot above)?

Like @jenstrickland just commented, I'd also like to QA this updated form-page.

**Comment by jenstrickland** [comment]
@tlei123 — @rebeccawalsh Slack messaged me to use that user, #1 — Greg.

**Comment by tlei123** [comment]
Updated my affected test-cases for the combined product-selection page, but for some reason when I started test-runs the authenticated form-intro page was blank after sign-in.

@camerontesterman, any ideas?

**Mac Chrome example**
![Screen Shot 2020-06-22 at 5 15 26 PM](https://user-images.githubusercontent.com/587583/85346997-0f29e580-b4ac-11ea-9b04-8e3325719b2d.png)

cc @jenstrickland

**Comment by jenstrickland** [comment]
I find this happens on occasion. Also sometimes when I load the intro page, the sign-in block doesn't load and I have to refresh.
