### ISSUE TITLE
MVP Hybrid Microservices: Set up Argo application definitions

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91348]
## User Story
As the managers and developers for the VA Platform, 
We need to onboard the new application using existing Argo automation,
So that the work is as automated as possible and requires little-to-no manual intervention.

## Issue Description
Integrate the new microservice into the existing cluster using the automated onboarding setup for ArgoCD.
This ticket needs to follow 90819.

## Tasks
- [ ] Set up ArgoCD application definitions to manage the new microservice

## Success Metrics
Application definitions for the new microservices are clear and complete. 

## Acceptance Criteria
- [ ] Application definitions are complete and accepted
- [ ] There will be documentation on any work that was executed under this ticket. Please include the link to the documentation in this ticket. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
