### ISSUE TITLE
MVP Hybrid Architecture: Integrate new microservices app CI/CD pipeline

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91350]
## User Story
As the managers and developers for the VA Platform, 
We need to integrate the new application's CI/CD pipeline with ArgoCD,
So that automated deployments can be tested and integrated for the microservices work.

## Issue Description
Integrate the new microservice's CI/CD pipeline with Argo. Note: this ticket follows ticket X

## Tasks
- [ ] Integrate the new application's CI/CD pipeline with ArgoCD for automated deployments.
- [ ] Document the onboarding process and update the documentation to include the onboarding setup

## Success Metrics
The new microservice will be automated for deployments

## Acceptance Criteria
- [ ] That the configuration using Argo will be successfully tested.
- [ ] That any errors will be fixed in this ticket before it is finalized and closed.
- [ ] There will be documentation on the onboarding process and updated to include the onboarding setup.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
