### ISSUE TITLE
MVP Hybrid Microservices: Implement Health Checks & monitoring into ArgoCD and DataDog

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91357]
## User Story
As the managers and developers for the VA Platform, 
We need to implement the health checks & monitoring within ArgoCD and DataDog
So that the automated deployments are a success.

## Issue Description
Integrate the new microservice into the existing cluster using the automated onboarding setup for ArgoCD. This should follow ticket X

## Tasks
- [ ] Integrate the new microservice into the existing cluster using the automated onboarding setup for ArgoCD.
- [ ] Document the onboarding process and update the documentation to include the onboarding setup

## Success Metrics
The new microservice will be integrated in the existing cluster in an automated way.

## Acceptance Criteria
- [ ] That the integration process is implemented and tested without new errors.
- [ ] That the new integration processes are automated as much as possible.
- [ ] There will be documentation on the onboarding process and updated to include the onboarding setup.
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
