### ISSUE TITLE
Discovery: Jill meet with Erika Washburn re: Scope of CMS Doc work

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91363]
## User Stories
As a Platform Content team member, I need to dedicate time to working in support of other teams, so that I can help them develop and publish documentation on Platform website.

As a CMS Team member, I need help updating our documentation on Platform website to reflect the migration to next build process, so that VFS Teams will be able to use next build.

## Issue Description
Providing support to other teams is one service of the Platform Content Team.
CMS team has a need for some content assistance before their contract wraps up on Oct. 11. 
CMS / Accelerated Publishing is moving from **content build to next build** , and they will need documentation on Platform Website to support VFS Teams working with Next Build.

---
## Tasks
- [x] Schedule meeting with Erika Washburn for week of 8/26/24
- [x] Hold meeting with Erika Washburn and Joe Knipes
 
## Acceptance Criteria
- [x] Meeting held
- [x] Next steps determined
 
### Relevant Links: 

- Next build: https://vfs.atlassian.net/wiki/spaces/AP1/pages/2166063172/next-build

- Accelerated Publishing: https://vfs.atlassian.net/wiki/spaces/AP1/overview?homepageId=2686288313

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91363?planning-poker) with Zenhub @taylojill

**Comment by jknipes** [comment]
cc: @michelle-dooley , @EWashb

**Comment by taylojill** [comment]
I met with Erika Washburn and Joe Knipes to discuss the project scope. I have a good idea about the way forward regarding the audience and topics that need to be covered. This ticket can be closed, and a new ticket should be created for the initial draft pages/outline.

**Comment by jknipes** [comment]
Closing ticket per the previous comments
