### ISSUE TITLE
Discover how many pages on average Veterans see in the TE flow

### ISSUE THREAD

**Issue by evelynhilbrichdavis** [department-of-veterans-affairs/va.gov-team#91388]
## Issue Description
After the 1.0 release of Toxic Exposure is complete, it would be helpful to understand how long (how many pages) the TE flow is for the average Veteran. 

Having the answer to this question will help UX consider how fatigue may be playing into the feature-- which we will be able to explore more completely in upcoming usability testing. 

---
## Tasks
- [ ] _Engineering discovery to look at submission data and get us an approximate answer! 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
