### ISSUE TITLE
FMB Phase 4 IA plan

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#91389]
```[tasklist]
### Tasks
- [x] IA tickets created
- [x] Completed [mural template](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1724431824265)
- [x] [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-4-survivor-comp.md)
- [x] [Redirect ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91851) created
- [x] [Language toggle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91910) created for DIC
```
