### ISSUE TITLE
[FSR] Add currency prop to VaTextInputField for all remaining form system pages

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#91410]
## Description

[Based on updates to form system input page](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1591), the currency symbol can be added to form system fields. 

Given: A veteran fills out an FSR
When: Enters a dollar amount
Then: They should see a $ symbol when they enter in the amount

## Tasks
- [x] Update all `'ui:webComponentField': VaTextInputField` to include `currency` `ui:option` 
- [x] Remove outdated `schemaform-currency-input` CSS class.

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [X] Not Required

## Acceptance criteria
- [x] All form system pages that use `'ui:webComponentField': VaTextInputField` have the currency symbol in the input 
- [x] Extra old CSS classes have been removed from `ui:options` 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [X] Description written
- [X] Tasks defined
- [X] Acceptance criteria written
- [X] Testing defined
- [X] Add Labels
- [X] Attach to an Epic
- [X] Estimate Points
</details>
