### ISSUE TITLE
Copy of Update Appoint MVP designs based on stakeholder feedback

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91414]
## Background
After presenting our Appoint MVP designs to stakeholders in Compensation Services, we learned that we don't have the medical authorization quite right.  When a claimant is seeking benefits for themselves, then the medical authorizations pertain to them ...UNLESS the Veteran is deceased in which case the medical authorizations apply to the Veteran.

We discussed adjusting the radio options at the start of this flow to account for this logic, and also updating the medical authorizations screen to reflect the situation described above.

## Tasks
- [x] Update Appoint MVP designs based on stakeholder feedback
- [x] Review updates with the ARM team
- [x] Schedule a meeting for review with stakeholders (CS, OGC, OPO)

## Acceptance Criteria
- [x] Appoint MVP designs have been updated for accuracy and ready for a second round of stakeholder review

**Comment by oddball-lindsay** [comment]
@mtri ticket has been updated with feedback we got today, and is ready for pickup :).
