### ISSUE TITLE
Download page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91412]
## Issue Description 

The Download page instructs users to download, print and sign their form.  The Review page will be available to **all users**:
1. Authenticated and unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

Content is dynamic based on:
1. If the user is a **Veteran**, the h2 should reference "Chapter 5". If the user is a **non-Veteran** the h2 should reference "Chapter 6".
2. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page. If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.
  
Implementation note: If a user **has entered an email address**, engage VA Notify when they select "Continue"(See #90325 for our approach)

**URL**: ~`/download`~ `/confirmation`
_Note: Had to update the URL here because the forms library requires the last page of the form experience (following the Review page) to be `/confirmation`._

**Previous path**: 
1. `/review`

**Next paths**: 
1. `/next-steps`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4311-279442&t=7ShW8oqmmrjY8jRD-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=456%3A171489&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4323-286115&t=7ShW8oqmmrjY8jRD-4), [Annotations + Desktop design](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153573&t=7ShW8oqmmrjY8jRD-4) 

<img width="306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8611182bae8a27216e5b3dbb60bc634bc35d54b9/image.png" alt="image.png" />

---
## Tasks
- [x] Create the Download page based on the designs above
- [x] Set up the proper logic for displaying the page, as well as the content within
- [x] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Download page has been implemented, with the specs outlined above.

**Comment by holdenhinkle** [comment]
I'll pick this up tomorrow, Thursday, August 29th.

**Comment by holdenhinkle** [comment]
From https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview

Forms Library general flow:

Introduction Page → Form Pages Start → Form Pages → Review Page → Submission → Confirmation Page

***

Submission happens on the 'Review Page'.

It seems that the 'Download' page is the 'Confirmation' page in Forms Library.

Here are the options for and related to submit:

col 1 | col 2 | col 3| col 4
-- | -- | -- | --
submitUrl | string | Path to vets-api controller for form submission. | submitUrl: `${environment.API_URL}/v0/health_care_applications`
submit | function | Function that’s called upon form submission.Optional: If a custom submit isn’t provided, there’s a system default that runs. | `submit: (form, formConfig) => {}`
transformForSubmit | function | Called during form submission to transform submitted schema data (Optional).Calling `transformForSubmit` in `platform/forms-system/src/js/helpers` will remove view fields from the schema data. | `transformForSubmit: (formConfig, form) => {}`
errorText | component | Component used as part of the default error message if submission of the form fails. | `errorText: ErrorText`
submissionError | function | Component that replaces the default error message component if submission of the form fails. | `submissionError: ({ form }) => {}`

Here's the info on the 'Confirmation' page:

col 1 | col 2 | col 3| col 4
-- | -- | -- | --
confirmation | component | The confirmation page component that will render after the user successfully submits the form. | `confirmation: ConfirmationPage`

**Comment by holdenhinkle** [comment]
This is 99% done:

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMStwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90f67da89c8537fe18c466108c2bfb528f11090b/image.png" alt="image.png" />

I’m trying to force the h2 to look like an h3 using the `vads-font-size-heading-level-3` class found here and it’s not working - https://design.va.gov/foundation/typography

I don’t see any classes being used that start with `vads-font-size` on vets-website.

I asked Colin if I'm using it correctly.

**Comment by oddball-lindsay** [comment]
Per the [annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153573&t=P1tG7vaFmmvRTNF7-4) it seems like the "Download, print, and sign your form" is an `h3`.

...but I think that's because the progress stepper was `h2`. 

Now that we're removing the progress stepper, I wonder if `h2` is actually correct in which case there'd be no need to force it to `h3`.  @mtri what do you think?

**Comment by mtri** [comment]
It can be an h2 without restyling it. I don't think there's any problem with that. I'll update in Figma as well.

**Comment by holdenhinkle** [comment]
This is done and is in review.

**Comment by holdenhinkle** [comment]
I just saw this:

> It can be an h2 without restyling it. I don't think there's any problem with that. I'll update in Figma as well.

Yes, it has to be h2. But I made it look like h3 to match the (original?) design. Should it look like a normal h2?

**Comment by oddball-lindsay** [comment]
@holdenhinkle yes h2! Michael updated the [annotation](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=5373-211093&t=bYB35plvtRxzFQ9W-4) to reflect that.

<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1c1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94e38a38776e6a56046495c1c5ffa511e1a223f7/image.png" alt="image.png" />

**Comment by mtri** [comment]
- Very small thing 🙂, can we increase the space here here so the download action and the checkbox action have some visual separation?  
<img width="1166" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGk1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d05ddfb6234f93afde1e69a3f6939ef0ede6aca6/Fill%20Out%20Your%20Form%20To%20Appoint%20A%20VA%20Accredited%20Representative%20Or%20VSO%20Veterans%20Affairs%202024-09-06%20at%202.34.28%20PM.jpg" alt="Fill Out Your Form To Appoint A VA Accredited Representative Or VSO Veterans Affairs 2024-09-06 at 2.34.28 PM.jpg" />

- I don't mind the h3 styling as is since it has a kind of visual consistency with the previous page, but we did swap to the h2 styled as h2 which has its own benefits (It's good when an h2 looks like an h2) so we should probably go that route. Sorry for the back and forth there.

Thanks!

**Comment by oddball-lindsay** [comment]
Also need to add in the "Need help" section at the bottom.

**Comment by holdenhinkle** [comment]
Updated:
<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8750bc530fd7e1da1c1e766848ec9401fe235a27/image.png" alt="image.png" />

**Comment by mtri** [comment]
Currently can't get past the review page to test. I'll QA once this is fixed.
<img width="878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUg2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6871a692592b0217b80009901a6daa5a311e4299/Screenshot%202024-09-24%20at%209.03.03%20AM.png" alt="Screenshot 2024-09-24 at 9.03.03 AM.png" />

**Comment by mtri** [comment]
Evaluated using the screenshots at https://github.com/department-of-veterans-affairs/vets-website/pull/31833

Looks good, thanks!
