### ISSUE TITLE
Next Steps page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91413]
## Issue Description 

The Next Steps page instructs users to download, print and sign their form.  The Next Steps page will be available to **all users**.

**Dynamic content**: If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page. If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

**URL**: `/next-steps`

**Previous path**: 
1. ~`/download`~ `/confirmation`

**Next paths**: None!  This is the end!

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
1. [Mobile Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4311-279442&t=7ShW8oqmmrjY8jRD-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=456%3A171489&show-proto-sidebar=1)
2. [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4311-279442&t=7ShW8oqmmrjY8jRD-4)
3. [Desktop Annotations](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=5373-210712&t=7ShW8oqmmrjY8jRD-4) 

---
## Tasks
- [x] Create the Next Steps page based on the designs above
- [x] Set up the proper logic for displaying the page, as well as the content within
- [x] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Next Steps page has been implemented, with the specs outlined above.

**Comment by holdenhinkle** [comment]
This is done for now. I'm waiting to pull in the PR that Colin submitted for review today which adds the selected rep to the redux store and the PR with the select rep/org results. This will allow me to build the rep/org card in the design. I'll also then mock the formData properly.

**Comment by holdenhinkle** [comment]
Pic with mocked data:

<img width="513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73206a93b68ae5510e567879c90724c43e674285/image.png" alt="image.png" />

**Comment by holdenhinkle** [comment]
Just have to update some tests and tweak some styling.

<img width="597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e3186cea1d234a35feca19cdcbdc2a04fabcd67/image.png" alt="image.png" />

**Comment by holdenhinkle** [comment]
Done

**Comment by holdenhinkle** [comment]
@mtri

**Comment by holdenhinkle** [comment]
@mtri you can see screenshots of the confirmation/download page, and the next-steps page here - https://github.com/department-of-veterans-affairs/vets-website/pull/31833

**Comment by oddball-lindsay** [comment]
Closing this, will address QA findings in an upcoming sprint. Thanks for the QA and ticket @mtri!
