### ISSUE TITLE
Review page

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#91411]
## Issue Description 

The Review page consists of multiple accordion components, which will allow users to review all of the information entered throughout the Appoint a Representative experience. An early version exists: `https://staging.va.gov/get-help-from-accredited-representative/appoint-rep/review-and-submit`but the URL needs to be updated and the design should match what's in Figma, details for both are below.

The Review page will be available to **all users**:
1. Authenticated and unauthenticated Veteran users
3. Authenticated and unauthenticated non-Veteran users
3. 21-22 and 21-22a forms

Content is dynamic based on:
1. User input entered throughout the form flow should guide all content in the expanded accordions. 
2. If the user is a **Veteran**
   1. "Your Information" accordion should reflect information from the Veteran chapter.
   2. There will be no accordion labeled "Veteran Information".  (Veteran information is shown in the accordion above).
   3. _Hide the Claimant chapter accordion and rename the Veteran chapter accordion?_
2. If the user is a **Veteran**, the h2 should reference "Chapter 4". If the user is a **non-Veteran** the h2 should reference "Chapter 5".
2. If the user selects a **VSO** for representation, they will see "VA Form 21-22" at the top of the page. If the user selects an **attorney/claims agent** for representation, they will see "VA Form 21-22a" at the top of the page.

No form fields for 21-22 or 21-22a are being completed on this step.
  
#### Implementation details
1. Upon the user selecting "Continue", push all information gathered to the backend for PDF generation (see #82223 for PDF generation)
2. Include the selected VSO Representative's information in this backend hand off
3. The "Edit" for the authorization sections will bring the radio selection back up

**Note: We are saving the behavior for editing the rep selection for a different ticket**

**URL**: `/review`

**Previous path**: 
1. `/authorize-address` (21-22)
2. `/authorize-outside-va/names` (21-22a)

**Next paths**: 
1. ~`/download`~ `/confirmation`

[MVP Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714785369605/65b1ce20d08478615fe2ef8c347cf19305cbffab?wid=4-1714808680763)

## Designs
[Prototype](https://www.figma.com/proto/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-144912&t=7ShW8oqmmrjY8jRD-0&scaling=min-zoom&content-scaling=fixed&page-id=455%3A76935&starting-point-node-id=456%3A171489&show-proto-sidebar=1), [Canvas](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-144912&t=7ShW8oqmmrjY8jRD-4), [Annotations + Desktop design](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=2194-153450&t=7ShW8oqmmrjY8jRD-4) 

Two states to consider: 
1. [Collapsed, initial state](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-144912&t=7ShW8oqmmrjY8jRD-4)
2. [Expanded state](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=455-144838&t=7ShW8oqmmrjY8jRD-4)

---
## Tasks
- [ ] Create the Review page based on the designs above
- [ ] Set up the proper logic for displaying the page, as well as the content within
- [ ] Set up routing to the proper form fields

## Acceptance Criteria
- [ ] A Review page has been implemented, with the specs outlined above.

**Comment by oddball-lindsay** [comment]
If the user wants to revisit the rep selection, we're not sure how to re-route to the original page. May be easier to allow them to select a new rep in the accordion expansion, but what does the UI look like? Will consult UX.

**Comment by oddball-lindsay** [comment]
After discussing today, please include the "View" portion of the Accredited Rep accordion in this ticket scope.

The "Edit" portion will be handled in #94256

**Comment by mtri** [comment]
QA ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95020
