### ISSUE TITLE
Trigger Pension and Burial Action Needed email notification

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#91426]
## Issue Description
Trigger an email notifying applicants that their pension and burial applications failed to submit on VA.gov. This email should only be sent if all backup submission pathways have been exhausted, and the submission meets the [criteria of a silent failure](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/zero-silent-failures-categories.md), and the applicant has provided an email address.

Trigger: A failure occurs that meets zero silent failure criteria as identified in [Pension Submission Monitoring documentation](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1723151514073/384e8cb5052fd80bfd6d93da645b97e5b22984b2?sender=ud143866fd5369378295a0267).

Design mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1728920302611/0e9b48b0886e0ba427fb3d6bd1b9dfc15918a5ae?sender=ua4b11671f027a66286586953

-Case 1: Sidekiq exhaustion  
-(Future) VA Notify accept email and tries to send and fail  

- Build out the functionality to call VA Notify
- Use the email address entered in the form
- Build out monitor and alert if email fails (may be addressed by statsd ticket)

Leverage for Stage testing the template created in VA Notify (note Production template dependent on VA Notify team implementation of [VA Notify Business intake form for Pension and Burial team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94099):
Pension:
Public endpoint: https://staging-api.va.gov/vanotify
Internal VA Network endpoint: https://staging.api.notifications.va.gov/
Service ID: 066bd626-5082-45a3-84a1-349dabd2b6baTemplate Name: 21P-527EZ – Action Needed Template
Template ID: ea0cae3a-3638-4524-8042-7259ebb0c437

Burial:
Public endpoint: https://staging-api.va.gov/vanotify
Internal VA Network endpoint: https://staging.api.notifications.va.gov/
Template Name: 21P-530EZ – Action Needed Template
Template ID: f78126ea-eab3-4ff7-a4e0-b77d31a93904

__Production VA Notify template info__

_Pension_

Public endpoint: https://api.va.gov/vanotify
Internal VA Network endpoint: https://api.notifications.va.gov/
Service ID: 066bd626-5082-45a3-84a1-349dabd2b6ba
Service Name: Pension Benefits
Template Name: 21P-527EZ - Action Needed Template
Template ID: b68ed06d-cefe-4e2d-adb1-955e37c21d9b

_Burial_

Public endpoint: https://api.va.gov/vanotify
Internal VA Network endpoint: https://api.notifications.va.gov/
Service ID: 5e5cded3-3c76-46a3-9eef-cb63589e76be
Service Name: [va.gov](http://va.gov/)
Template Name: 21P-530EZ - Action Needed Template
Template ID: 71de8b72-c5e4-41f9-93d1-14fca2a9828c

Important note: The deadline for this work is 11/12 as part of Zero Silent Failures initiative.  Other notifications for the Zero Silent failure Initiative will be documented in separate tickets.

---
## Tasks

- [ ]  Trigger send of the Action Needed template when a silent failure occurs
- [ ] Build out the functionality to call VA Notify
- [ ] Build out monitor and alert if email fails

## Acceptance Criteria
- [ ] Submissions that meet zero silent failure criteria are identified through backend process
- [ ] Notifications sent to applicants that provided email address when trigger logic met.
- [ ] Monitors and alerts identify when emails fail

**Comment by matt4su** [comment]
Created a staging instance of this form template.  ID: ea0cae3a-3638-4524-8042-7259ebb0c437

**Comment by matt4su** [comment]
Ticket updated with Production environment info for VA Notify Action Needed templates for Pension and Burial notifications.
