### ISSUE TITLE
[EPIC] 10-10 Health Enrollment: Adding Next of Kin to 10-10 EZR Form

### ISSUE THREAD

**Issue by IMHieuVo** [department-of-veterans-affairs/va.gov-team#91447]
# Content, accessibility, information architecture (CAIA) new initiative collaboration request

Use this ticket to request collaboration on a new initiative with the sitewide content, accessibility, and information architecture (CAIA) team.

## About your team

- **Team name**: 10-10 Health Enrollment Team
- **OCTO product owner:** Patrick Bateman
- **Product name:** 10-10EZR Health Benefit Information Update form
- **Product manager:**  Alex Seelig
- **Slack channel:** [#1010-health-apps](https://dsva.slack.com/archives/CMJ2V70UV)
- **Dedicated content writer on your team (if you have one):** N/A
- **Dedicated a11y specialist on your team (if you have one):** N/A
 
### Which of these descriptions best fits the work we’ll partner on?
Select all that apply.
- [ ] Digitizing a new form
- [ ] Creating a new digital tool
- [X] Updating an existing form or tool
- [ ] Translating a form or tool into Spanish
- [ ] Adding new unauthenticated content to VA.gov
- [ ] Updating existing unauthenticated content on VA.gov
- [ ] Something else:  `insert description`

### What's the nature of your initiative and desired outcomes?

The 10-10EZR Health Benefits Update paper form asks for Next of Kin and Emergency Contact information but we left it off our online form MVP launch. Now the team is circling back and adding the Next of Kin and Emergency Contact to our online form. We will start with the Emergency Contact and then add Next of Kin. This intake is for Next of Kin.

## Collaboration timeframe

**Note:** We work on nearly every OCTO product and manage all unauthenticated content on VA.gov, so we will need to prioritize intake requests based on overall workload and VA and OCTO priorities.

### Is this work tied to a Congressional mandate, change in law or policy, or upcoming event with a specific deadline?
- [ ] Yes
- [X] No
- [ ] I’m not sure

### Where are you at in your timeline?
Tell us briefly about what you're working on now (such as initial discovery, wireframing, or usability research planning) and add any known dates for upcoming milestones or deadlines.

The Figma wireframe is ready and we have most of the content in place, ready for review. It is very similar work to the Emergency Contact. 

This ticket is a timebox/placeholder ticket for the work proceeding the Emergency Contact work. We currently do not have a deadline.

### Will you release this new product incrementally (for example, release to 25% of users to start)?

- [ ]  Yes
- [X]  No
 
 **Note:** For an incremental launch, we use React widgets to display dynamic content. We'll need at least 2 weeks of extra time to coordinate the content for this and work with your engineer. [Learn more about our process for dynamic content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/processes/dynamic-content-process.md). If your launch plans change, notify CAIA of the change as soon as possible so we can talk about how that will impact the timeline.

**If you are releasing incrementally:**
- **What dates do you anticipate starting and ending your incremental launch?** N/A
- **What is the name of your engineer who will build the React widget?** N/A

### Which phases of the collaboration cycle have you completed?
Select all that apply.
- [ ] Design intent 
- [ ] Midpoint review 
- [ ] Staging 
- [X] None. This initiative isn’t going through the collaboration cycle.

### Collaboration cycle ticket 

If you’re going through the collaboration cycle, provide a link to your Collaboration Cycle Request:
- **Hyperlinked Ticket Number: N/A** 

## Supporting artifacts
Provide links to any supporting artifacts that can help us better understand your initiative and begin collaboration. Include artifacts like your product outline, user flows, mockups and prototypes, or any draft content.
- [Mural NoK-EC](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698340057865/2e2eced8589757c192a1601579a871cab97d3565?sender=ubf5503bf47b6eb1e92730053)
- [Figma Link](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=2614-34432&t=kjqB9kvXOYsMkeRV-1)

## Next steps
- [ ] Review the remaining next steps in the **VFS team tasks** section here.
- [ ] **If you also need engineering support from the public websites team**, fill out their intake request form as well: [Open a public websites intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
- [ ] **If you're requesting a page/URL redirect, a URL change, or a vanity URL**, submit an additional request for this work: [Open a redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
- [ ] **If you're creating an experimental design**, also contact the design system team: [Read more about experimental designs](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) <br> [Suggest an addition or update to the design system team](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- [ ] **If you're requesting a11y support for usability research**, submit a research support request next: [Open an a11y research support request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)
- [ ] **If you are requesting content support**, please share your content source of truth (preferably as a SharePoint document).

**Comment by aliyahblackmore** [comment]
The product team shared that this work is now ready. They'll share the designs in the next 1-2 weeks.

**Comment by aliyahblackmore** [comment]
**Updates here:**

Content feedback is ready for the designers in their [Figma file](https://www.figma.com/design/tggcJk382w9yQ0ElwKfh3N/10-10EZR?node-id=6081-70662&node-type=instance&t=3pzDZcGsGBSr6AjX-0). We may need some additional updates after the team chats with their SMEs.
    
- I adjusted the content here based on the information from the designs and the definitions from the designers/product team. The product team will review with their SMEs have them confirm/okay that the definition here (that’s aligned with VA profile and check in) works. We can make adjustments if needed (i.e. whether we leave “medical documentation and benefits”).

- Team shared on 10/25 that if they can’t move forward with two entries for NOK, they’ll mock up designs for one entry at that time. There may be some slight content adjustments there (i.e. using “This is the person” instead of “These are the people").

- I added the tentative static page update to the “Personal information” point on the static page mock up in their designs. We can revisit that when you all are ready to launch to Veterans. We’ll want to ensure we coordinate timing for publishing - if NOK is coming after EC, we can assess.

- I added in the form intro page mock up to the NOK section and tracked the update to the “Personal information” bullet point. I also noted the areas of the mock up that don’t align with what’s in production and tracked changes.

- It seems like the appointments/check-in team is having ongoing conversations to learn more about NOK and how VA health facilities use that information. As the product team gets any more info about how facilities using this information and continue their conversations with the check in and VA profile teams, we can revisit and update any of the definitions. I recommend continuing conversation with the VA profile and check in teams to keep these definitions aligned where possible if all data is eventually going to the same API.

**Comment by aliyahblackmore** [comment]
Update here:

- I'll turn back to screens next week.
- They learned that they can include a standalone intro screen for this list&loop. TBD on whether designers want to use an intro screen for V1.

**Comment by aliyahblackmore** [comment]
**Update here** 

The designers decided to use a standalone intro screen for the NOK questions. 

I reviewed and updated content. Whenever you all review with SMEs, we can make accuracy of information updates if needed.

**Here are some notes:**

- After looking at the NOK standalone screen again, I went back and forth on whether that content, along with hint text, makes some things a bit repetitive. So I moved some of the information to the hint text on the question screen (i.e. "the first person you add...") since that information is more relevant when we ask if they'd like to add someone.
- On the NOK "Review/Add screen", I used the hint text to capture helpful and need to know info (see comments on screens) given that screen will show in a few instances (like someone sharing that info for the first time, someone returning, or someone editing later on). It's my understanding that those screens should be the same as the ones from the "Adding for the first time" section - but let me know if that's not the case (i.e. it's not connected to the Add for first time flow).
- If the list&loop pattern is more flexible in the future, we can consider if something like an additional info component about who VA considers NOK is helpful on the "Add another review" screen. Could that be helpful when someone is returning to the form to add or edit?

**Comment by VCM86** [comment]
Closing--reach out if you have any questions.
