### ISSUE TITLE
Publish GA4 How-Tos to Platform Website

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#91444]
### Description
In recent sprints, we have been drafting some how-to resources on Google Analytics 4 (GA4). While teams would benefit from having access to these, they are currently sitting in our internal Confluence space, and haven't yet been published to the Platform Website. 

This ticket is to ensure the three resources we've created our live on the Platform Website.

- [How to: Event Reporting with Explore Reports](https://vfs.atlassian.net/wiki/spaces/AT/pages/3291119647/How+to+Event+Reporting+with+Explore+Reports)
- [How to: Sampling in GA4](https://vfs.atlassian.net/wiki/spaces/AT/pages/3346923522/How+to+Sampling+in+GA4)
- [How to Reporting: Comparisons](https://vfs.atlassian.net/wiki/spaces/AT/pages/3403907099/How+to+Reporting+Comparisons)

---

### Tasks

- ~[ ] **Important!** -- Confirm we are able to post screenshots from GA4 on Platform Website. We may need to pose this question to the Platform Security Slack channel~ 
- [x] Update -- we decided to scrub screenshots of any data.
- [x] Have Jamie review for accuracy
- [x] Review guidance for posting on Platform Website, including checking for any launch blocking issues -- [here](https://vfs.atlassian.net/wiki/spaces/~637b96fdfde064eda2ed7417/pages/3101163521/LAUNCH+BLOCKING+ISSUES).

### Acceptance Criteria
The following pages are published on the Platform Website:
- [x] [How to: Event Reporting with Explore Reports](https://vfs.atlassian.net/wiki/spaces/AT/pages/3291119647/How+to+Event+Reporting+with+Explore+Reports)
- [x] [How to: Sampling in GA4](https://vfs.atlassian.net/wiki/spaces/AT/pages/3346923522/How+to+Sampling+in+GA4)
- [x] [How to Reporting: Comparisons](https://vfs.atlassian.net/wiki/spaces/AT/pages/3403907099/How+to+Reporting+Comparisons)

**Comment by johnny-jesensky-adhoc** [comment]
We have published three GA4 How-To resources as of yesterday (9/9). They can be found on the Platform Website, under the new [GA4 Training Resources](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/ga4-training-resources) section.
Path: Analytics & Insights → Reporting & Insights → Google Analytics → [GA4 Training Resources](https://vfs.atlassian.net/wiki/spaces/APM/pages/3435692033/GA4+Training+Resources)
- [How-To: Event Reporting with Explore Reports](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/how-to-event-reporting-with-explore-reports) 
- [How-To: Sampling in GA4](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/how-to-sampling-in-ga4)
- [How-To: Reporting Comparisons](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/how-to-reporting-comparisons)

Moving this to _Done_.

FYI @Blivaditis
