### ISSUE TITLE
[Design] Update Filter filed value for practice

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91450]
## Background
In research, the filter pattern did not present any usability concerns, but our results lacked conclusive evidence that Veterans would use the feature prior to prompting them to use it. Though participants said the filters met overall expectations, some called out specific filters as confusing or missing.

Most notably: 

- Participants found the Practice filter confusing. 

## Details

> P13: "So you can select a practice meaning you can select from this menu of physicians. I think what you're trying to say is physical therapy or heart specialist."

## Tasks
- [ ] Ask Simi and Lee for the values (examples) that are being returned from WellHive for [Provider organization name] and [Address line 1]
- [ ] Update the name of the Practice filter to remove confusion
- [ ] Update other pages where practice might be mentioned to be consistent with any changes

## Acceptance Criteria
- [ ] Proposed changes shared with UX
- [ ] Figma files updated

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-CC-Direct-Scheduling-660abc13699bfa00195d685a/issues/department-of-veterans-affairs/va.gov-team/91450?planning-poker) with Zenhub @cgednalske @Cieramaddox
