### ISSUE TITLE
OH Scheduling improvements: Provider selection screen

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#91452]
Here's a template for your task ticket:

---

## Task Description
Create a "provider selection" page as part of the new Oracle Health scheduling flow. Incorporate feedback from usability research to ensure an intuitive and user-friendly design. The final deliverable should be a comprehensive Figma file showcasing the design.

## Notes and References
- Use the usability [research insights ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2024-05-oh-scheduling/findings.md#oh-provider-selection---key-findings)

## Acceptance Criteria
- [x] Provider selection page is designed according to feedback from usability research.
- [x] Design is consistent with the clinic selection page for VistA
- [x] Create a CAIA ticket with designs

## Deliverables
-[ Figma file](https://www.figma.com/design/z00OSRBCfytdUlrlYzdvQg/Provider-selection-screen%2391452%7C-Appointments-FE-(Copy)?node-id=1-16&t=R0baoyZrUHaraaSm-1) with the completed "provider selection" page design.
