### ISSUE TITLE
[Design]- Update profile page for when a user is not in MPI

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#9145]
## Background

We noticed that we do not have a state in profile for when a user is not in the MVI.  We need to create a design that will work with profile 2.0 to represent this. There is no user who is not in the MVI to show this - Erik hacked it locally.

## Additional information

Epic # 

![profilev1-not-in-mvi.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/44731345-e17e-4250-acbf-f84b2b1825ec)

![image (2).png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/bebbfa38-6a67-49f1-922f-6c7be2bac209)

##Tasks

- [x] Create updated design for profile landing page
- [x] Create updated design for Account security page
- [x] Update any copy that is needed

##Acceptance criteria

- [x] All mocks have been updated and added to prototype

**Comment by tressaellen** [comment]
@peggygannon I think this messaging is something that could use some simplifying. Do you have any thoughts on how we could do that?

We’re having trouble matching your information to our Veteran records

We’re sorry.  We’re having trouble matching your information to our Veteran records, so we can’t give you access to tools for managing your health and benefits.
If you’d like to use these tools on VA.gov, please contact your nearest VA medical center.  Let them know you need to verify the information in your records, and update it as needed.  The operator, or a patient advocate, can connect you with the right person who can help.

Find your nearest VA medical center

![Account Security - Not in MPI.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/31254eac-8730-49d5-a5f4-74315cb3bce4)

**Comment by peggygannon** [comment]
Hi, @tressaellen Here is my content recommendation. Please let me know if this messaging will work for this scenario. 

**We can’t match your information with our Veteran records**
We’re sorry. We can’t match the information you entered to our Veteran records. We can't give you access to health and benefit tools until we can match the information and verify your identity.
If you’d like to use these tools on VA.gov, please contact your nearest VA medical center to verify and update your records.  

[Find your nearest VA medical center]

**Comment by tressaellen** [comment]
Thanks @peggygannon - this works!

<img width="575" alt="Screen Shot 2020-05-29 at 8 27 15 AM" src="https://user-images.githubusercontent.com/58752772/83282560-3b409800-a186-11ea-84b9-9006456c312a.png">
