### ISSUE TITLE
HLR | Switch to new Lighthouse endpoint

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#91454]
## Value Statement

**_As a_** Decision Reviews team member
**_I want to_** switch our Higher-Level Review (HLR) endpoint to use the new Lighthouse (LH) endpoint
**_So that_** the HLR updates match the form submitted to LH

---

## Background Context

We have been working on HLR updates, behind a feature toggle, to match the newest HLR form. LH recently finished work on this newest HLR form endpoint, so now we need to add an endpoint to our backend, and switch our frontend - still behind a feature toggle - to use the endpoint

## Outcome, Success Measure, KPI(S), and Tracking Link

- Newest HLR form is being submitted to LH's newest HLR endpoint

## Acceptance Criteria

- [ ] BE HLR endpoint uses newest LH endpoint
- [ ] FE HLR submission to the newest endpoint when feature toggle is enabled
- [ ] FE HLR submission to previous endpoint when feature toggle is disabled
- [ ] New HLR submissions have been validated in staging
- [ ] Tests updated & all passig

## Designs and Build Notes

- Add here

### Enablement team (if needed)
@ member of team

## Out of scope

- Add here

## Open questions

- Add here

## Tasks

- [ ] BE sets up new endpoint to use LH's new endpoint
- [ ] FE sets up submission to new BE endpoint when feature toggle is enabled
- [ ] Add tests
- [ ] Validate endpoints in staging

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@Mottie is this necessary since there's no v3 endpoint, they just updated their v2 endpoint

**Comment by Mottie** [comment]
@shaunburdick I think we can close this ticket
