### ISSUE TITLE
[FSR] BE support for housing expenses update

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#91473]
## Issue Description
Just wanted to confirm the BE can support enabling the housing expense feature flag changes before we work on a release plan. Most of the calculation logic is set up on the FE, but wanted to confirm the BE full transforms supports the new data structure.

Feature flag: `financial_status_report_expenses_update` 
FE structure changes:
**Before:** `data.expenses.expenseRecords` (array)
**After:**    `data.expenses.monthlyHousingExpenses` (string)

Note from Derek:
We may need backwards compatability in the data we are storing for in progress/submitted forms.\

Look into calculate expenses endpoint

## Tasks
- [ ] Confirm BE expense calculator helper supports the new structure
- [ ] Confirm BE full transform supports this feature 

## Design and Front End sync on implementation of design
- [ ] Required
- [ ] Complete
- [x] Not Required           

## Acceptance Criteria
- [ ] Confirmation that BE can support new feature
- [ ] (OR) BE ticket created to support new feature 

## Testing
- [x] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description     

Test procedures:      
*If additional testing steps or credentials to perform testing are needed list them here*    

## Ticket Creation - Definition of Ready
- [x] Description written
- [x] Tasks defined
- [x] Acceptance criteria written
- [x] Testing defined
- [x] Add Labels
- [ ] Attach to an Epic
- [x] Estimate Points

**Comment by digitaldrk** [comment]
Search for `expenseRecords` in vets-api

**Comment by maxx1128** [comment]
I checked the codebase and can confirm that `monthlyHousingExpenses` is part of the new expense calculator. It's specifically at `modules/debts_api/lib/debts_api/v0/fsr_form_transform/enhanced_expense_calculator.rb:23`. It is saved under the `rentOrMortgage` key in the form's `expenses` property.

cc: @Dr-Pongo @digitaldrk

**Comment by maxx1128** [comment]
@Dr-Pongo and @digitaldrk confirmed this as well, so this ticket is good to close 👍
