### ISSUE TITLE
Copy of [Design] Create low-fi design options for referrals in Appts app

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#91480]
## Tasks

- [ ] [Review background on problem to address](https://dsva.slack.com/docs/T03FECE8V/F07HMS86ASD) 
- [ ] Create low-fi design options for referrals in Appts app
- [ ] Review with Appts team and Kristen 

## AC

- [ ] Direction decided
- [ ] Create high-fi design ticket
