### ISSUE TITLE
EVSS PCIU Migration: Internal testing after V1::ContactInformation is upgraded to V2::ProfileInformation

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91488]
## User Story
As the managers and engineers of the VA Platform, 
We need to perform internal spot checking on the EVSS PCIU work, 
So that when other teams are ready to test, there should be no unexpected issues.

## Issue Description
We need to perform spot testing after the upgrade from V1::ContactInformation with V2::ProfileInformation (in DEV and STG) so that when other dependent teams perform their testing, we are confident that there will be no unexpected issues with this upgrade. 

## Tasks
- [x] Spot check current PCIU environment for errors in the STG environment, please check 1 or 2 in DEV as well
- [ ] Note any found issues for fixing
- [x] Document how spot check testing was completed, along with any outstanding issues

## Success Metrics
For this work, spot checking the upgrade will ideally eliminate errors before the dependent teams do their testing.

## Acceptance Criteria
- [x] We will be ready and confident in the upgrade work before external teams begin their testing

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
9/26/2024 - @RachalCassity will reach out to Tom H about testing, the PR should be done today and then they can start.

**Comment by jennb33** [comment]
10/9/2024 update: The Identity team did something to the forms that @RachalCassity is looking into.

**Comment by jwoodman5** [comment]
@RachalCassity making a ticket for address validation. Will finish that then revisit this.

**Comment by RachalCassity** [comment]
Testing will continue after V3/AddressValidation has been deployed to staging.

**Comment by jwoodman5** [comment]
Testing in staging now plus a PR is up for review.
