### ISSUE TITLE
[CONTENT] Create content template for "VOLUNTEER & DONATE" Page for understanding of areas on the page and where to find content [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#9149]
## User Story or Problem Statement
As a Content writer, I must have a full understanding of areas of writing, so I can write the areas of the VAMC more accurately and efficiently.

## Goal
_Create new template to be used in creation of standard content pages/nodes _

## Objectives or Key Results this is meant to further
- _Increase overall quality experience for veteran's accessibility_
- _Assist and reduce time for complete accessibility and 508 compliance checks_

## Resources - Tools - Documentation
[Copy Edited INTERNSHIPS documents](https://drive.google.com/drive/folders/1nH-Zz1rgd8xNAYFj84Zy-JmDOFSEp0jf)

## Tasks
_Complete Template to include areas and comments like:_
- [ ] Clean up / accept all changes of Managing/copy editor for clean example page.
- [ ] List areas in document as Required, Not-Required(Optional dependent on System)
- [ ] Comment where to find content (i.e. Can be found in Annual Report, or in Jobs and Careers page, etc)
- [ ] Save final template in Content folder in Google Drive

## Acceptance Criteria
*Clean up / accept all changes of Managing/copy editor for clean example page.
*Required, Not-Required(Optional dependent on System)
*Content can be found in Annual Report, or in Jobs and Careers page
*Save final template in Content folder in Google Drive
