### ISSUE TITLE
OH Scheduling improvements: Dead ends from facility page 

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#91499]
## Task Description
Examine current dead ends from the facility page that are based on clinics and design a similar error for provider related issues for Oracle Health (OH) facilities.

## Notes and References
- Review [existing error designs for clinic-based dead ends](https://www.figma.com/design/ugE1APC20v8OcArGB2IMQy/User-Flows-%7C-Appointments-FE?node-id=1-3471).

## Acceptance Criteria
- [x] [No facilities available - dead ends](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=5561-38589&node-type=section&t=SLrjLhAJ8okL1ilQ-11)
- [x] [Alerts for User is registered at 1 facility ](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=5640-56505&node-type=section&t=SLrjLhAJ8okL1ilQ-11)
- [ ] [Single facility: Requests enabled - dead end](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=5956-12479&node-type=section&t=SLrjLhAJ8okL1ilQ-11)
- [ ] [Multi facility alerts](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=5561-38679&node-type=section&t=SLrjLhAJ8okL1ilQ-11)

## Deliverables
- [Figma file](https://www.figma.com/design/EHR9zBpGnAgc7bHqeIGEoT/OH-Direct-Schedule-MVP-%7C-Appointments-FE?node-id=5373-7023&node-type=section&t=yFnD1Htr775EXfi2-11) with the new error design for provider issues on the facility page.

**Comment by melissa-lefevre** [comment]
[Update alert on choose a VA location page - Part 1#96379](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/96379)
[Update alert on choose a VA location page - Part 2#96475](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/96475)
[Update alert on choose a VA location page - Part 3#96525](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/96525)
[Update Error on which VA facility would you like to go to page#96482](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/96482)

**Comment by outerpress** [comment]
@melissa-lefevre all the dev tickets are closed so I'm closing this one out.
