### ISSUE TITLE
[FSR] Refactor resolution options radio button group to use design system component

### ISSUE THREAD

**Issue by josephrlee** [department-of-veterans-affairs/va.gov-team#91546]
## Description

Enter a detailed description of the work - gherkin syntax below is acceptable.

Given: A veteran fills out the FSR
When:  They select a resolution option to resolve a debt
Then: They should see a design system component instead of our custom component 

 <img width="486" alt="Screenshot 2024-08-27 at 10 34 38 AM" src="https://github.com/user-attachments/assets/06fbaf98-b489-49c0-b4b4-ffdba59e6e4f">

<img width="674" alt="Screenshot 2024-08-27 at 10 38 50 AM" src="https://github.com/user-attachments/assets/44eb7a16-0d25-4ef5-aa0b-3e212edf1649">

<img width="600" alt="Screenshot 2024-08-27 at 10 40 32 AM" src="https://github.com/user-attachments/assets/f944962c-4374-4ecb-a3a3-d928676d0e74">
<img width="594" alt="Screenshot 2024-08-27 at 10 43 14 AM" src="https://github.com/user-attachments/assets/45a0b54c-f9ea-4a7c-9e72-18163fa30d29">
<img width="610" alt="Screenshot 2024-08-27 at 10 43 32 AM" src="https://github.com/user-attachments/assets/e9549d1e-25c6-4a56-a96c-e00da8025a2d">

## Tasks
- [x] Use [radio button component](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--docs) to replace the custom [ResolutionOptions.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/e66872a4d24eb0b552ac55ad4aa7400172fcd933/src/applications/financial-status-report/components/resolution/ResolutionOptions.jsx) and update logic
- [x] Use the `required` label from the component and not our custom one that shows up randomly after the text
- [x] Fix the display of the really small text after an option is selected to [match the design in Figma](https://www.figma.com/design/ea8baIDr09ncgr1P4Rfh8i/Financial-Status-Report-(VA5655)---(including-Streamlined-Waiver)?node-id=0-5425&t=JRZGrsk8gSsT515R-11) and get rid of the extra required labels 

## Design and Front End sync on implementation of design
- [X] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [ ] Resolution options use the design system component 
- [ ] Extra required labels have been removed 
- [ ] Insoncistient type sizing has been fixed 

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by josephrlee** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/91546?planning-poker) with Zenhub @Dr-Pongo @OptionSelect @amponce

**Comment by OptionSelect** [comment]
Pulled in late to sprint 133
