### ISSUE TITLE
Edit: Provide or Suggest New Content for the Platform Website

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#91548]
### BACKGROUND
After completing this discovery ticket, the PCT decided to edit/update [the Provide or Suggest New Content for the Platform Website page](https://depo-platform-documentation.scrollhelp.site/support/how-to-provide-and-suggest-new-content-for-the-pla) to include the following changes:

1. break out the links into to separate bullets so they are easier to notice (instead of having two links in one bullet)
2. change the link text for the GitHub ticket to read "Documentation Support Request" instead of "this form"

(1) refers to this bullet:

> Once you have your topic idea or a completed draft of your new content, send it to our team via the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) Slack channel or [this form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=documentation-support&template=documentation-support-request.yml&title=Documentation+support). If possible, please let us know where in the IA of the Platform Website you think your new content might fit best.

The team-approved change in #1 is to make the above into, at least, two separate bullets instead of one, long bullet with 2 links in it. 

(2) refers to the "this link" hyper text in the above quote from the site. 
"This link" should be changed to "Documentation Support Request". 
The link, itself, needs to point to [the proper template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=vbellissimo%2C+amygoldman&labels=documentation-support%2C+platform-content-team&projects=&template=documentation-support-request.yml&title=Documentation+support) AND the hyperlink text should change. 

### TASKS

- [x] Copy PW page
- [x] Update copy as described above
- [x] If needed, share exact wording of changes with PCT to get approve and/or have it checked. 
- [x] Once checked and finalized, copy changes and paste them in original doc; replacing the old version. 
- [x] Check updated page for Launch Blockers
- [x] Deploy Page

### Acceptance Criteria 

- [x] Updated version of page exists on PW

**Comment by jknipes** [comment]
@BSmolensky just FYI: the link in (2) has been updated to the correct template; the old one doesn't put a ticket on our board (!)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91548?planning-poker) with Zenhub @BSmolensky @cmarion93 @laucon @taylojill

**Comment by BSmolensky** [comment]
Thanks, Joe!

**Comment by jknipes** [comment]
I am removing mention of the two templates, as VFS teams cannot access them:

[Overview Guide Template](https://vfs.atlassian.net/wiki/templates?space=~637b96fdfde064eda2ed7417&template=1476558950)
[How-to Guide Template](https://vfs.atlassian.net/wiki/templates?space=~637b96fdfde064eda2ed7417&template=1477083205)

**Comment by BSmolensky** [comment]
Assigned myself to the ticket. Reviewed the tasks. Should be able to complete before end of this sprint. Moving ticket into "in progress."

**Comment by BSmolensky** [comment]
Updated the page. Page is ready to deploy. Once deployed, this ticket can be closed. Until then, moving to _Review QA_

**Comment by jknipes** [comment]
- Issue pulled into this sprint due to available capacity and **priority** level of the work
- Work is completed, moving to _Closed_
