### ISSUE TITLE
Design | Contact Info Refresh | Update Figma file so "Current Production" frames match what is in Production

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#91541]
## Background 
The files in "[Profile - Contact Information](https://www.figma.com/design/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?node-id=0-1005&t=e7cdyWICEce3EpcH-0)" do not currently match what we see live on the Staging Server. This can cause confusion for Design and Dev.

![image](https://github.com/user-attachments/assets/c34440ed-df08-4992-8dc3-4b72e6279c04)

```[tasklist]
### Tasks
- [ ] Identify all frames in the "Current Production" pages that do not match what we see live on the Staging Server
- [ ] Manually update frames to match what is live on the Staging Server 
```

## Acceptance Criteria 
- [ ] Above are completed
- [ ] PM and DM review

**Comment by mtcA6** [comment]
@twoangstroms i think this is actually a dupe of:
- #90190

**Comment by jfinnerty13** [comment]
With us updating the content info pages are you ok if we close this out @mtcA6 ?
