### ISSUE TITLE
Pt. 2 Create New Page - Continuation from issue

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91557]
## User Story
As a PO, I want to be able to share and point to a page on Platform website that details the services of the Platform Content team, while differentiating between the website and va.gov and between roles and services of Platform Content team and CAIA (Content, accessibility, and information architecture) team.

As a VFS Team member, I need to know what needs are served by the Platform Website and the Platform Content team. I also need to know the difference between Content Team and CAIA and between Platform Website and va.gov.

As a Platform Content team member I need to continue editing a page for the website that highlights the team's roles and services, and which I can share as a quick-view guide for VFS team members looking for documentation help while building on va.gov.

Assignee: @taylojill 

## Issue Description
Platform Content Team needs to create a page on Platform Website detailing what sort of issues the team can help with and examples of some things we don't do.
The format of this page will follow that of [What We Can Help With - Platform Support](https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support)

[Here is the Content Team DRAFT PAGE in Confluence](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3366617104/DRAFT+external+What+We+Can+Help+With+-+Platform+Content+88359)
Per Erika Washburn, we should compare and contrast what Content Team does vs. CAIA and va.gov for **What We Don't Do**
### Example: 
What We Don't Do
- **VA.gov** Content, accessibility, and information architecture guidance for product teams
- Management of unauthenticated content and IA on va.gov
- Content style guide for va.gov
These are handled by the **CAIA Team**  

What We Do
Platform Website documentation for VFS teams building on Platform is handled by **Platform Content Team** 

---
## Tasks
Team member edits new page in draft space. 
- [ ] Jill finish creation of page from ticket _______
- [ ] Review with Jason Woodman
- [ ] Team decides IA
- [ ] Schedule announcement for next Platform Demo

## Acceptance Criteria
- [ ] Document is approved and ready for publishing, demo
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
Adding this ticket to the current sprint due to available capacity and most tasks already completed during an earlier sprint.

**Comment by jknipes** [comment]
Per previous comment, we are closing this issue as _Done_
