### ISSUE TITLE
[CDP] Unique Page Titles for Debt Portal

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#91555]
## Description

**Similar to [Unique Page Title for FSR #66851](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/66851).**

H1's should be succinct and descriptive. The text of the h1, the current breadcrumb and the first part of the title tag before | Veterans Affairs should be the same text. 
So, if your H1 is "Current overpayments", the current breadcrumb should be "Current overpayments" and the `<title>` would be "Current Overpayments | Veterans Affairs". [See Design System guidance on page titles for more info.](https://design.va.gov/content-style-guide/title-tags)

Design System guidance:
- https://design.va.gov/content-style-guide/title-tags
- https://design.va.gov/content-style-guide/page-titles-and-section-titles
- https://design.va.gov/components/breadcrumbs
- [Recent Slack conversation](https://dsva.slack.com/archives/C01DBGX4P45/p1724336998726839)

This ticket addresses Midpoint review feedback [#87951](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87951)

Given: The title on all pages on the Combined Debt Portal read "Combined Debt Portal | Veterans Affairs"
When: All paths, VHA and VBA
Then: Titles on all pages should show the text within the H1. Example: "Your VA debt and bills | Veterans Affairs"

## Tasks
- [x] Update titles on all pages of the Debt Portal to  "H1 | Veterans Affairs"
- [x] Updated breadcrumbs to match H1s (debt-balances/details/customid --see comment below)

## Design and Front End sync on implementation of design
- [x] Required
- [ ] Complete
- [ ] Not Required

## Acceptance criteria
- [x] The titles of all pages of the Debt Portal have been updated to "H1 | Veterans Affairs"
- [x] Breadcrumbs match H1s

## Testing
- [ ] N/A if non development work
- [ ] Testing passed and documented in this ticket based off the "Then" statement in the description

Testing procedure:
If additional testing steps or credentials to perform testing are needed list them here

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
Page on the Debt Portal where Breadcrumbs and H1s do not match:

- https://staging.va.gov/manage-va-debt/summary/debt-balances/details/customid
   - Breadcrumb: **Debt details**
   - H1: **Your Post-9/11 GI Bill debt for housing**
