### ISSUE TITLE
Final review of SR dashboard changes

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91558]
## User Story
As a Governance team member, I want to validate that the changes to the SR Dashboard in Domo are accurate and easily understood so that others outside of Governance can rely on this data and metrics.

Assignee: @erinrwhite  / @allison0034 @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
Governance team members added several new cards to the Staging Review Dashboard in Domo, highlighting trends in accessibility defects as well as imposter components. Before marking this initiative as complete, we'd like to get fresh eyes on the changes to ensure that everything is accurate, easily understood and the chart types make sense for the data.

The purpose of this ticket is to complete a final, critical review of the new cards in the Staging Review dashboard. Any changes that need to be made will be completed by Allison and Ian, who designed and built the cards in Domo over the last few sprints.

### Live pages
- [Staging Review Dashboard](https://va-gov.domo.com/page/1340527018?userId=1646566899) (Domo)
### Drafted pages
- 

## Tasks
- [x] Complete a review of the Staging Review Dashboard
- [x] Document any concerns, bugs, issues, or proposed design changes as a comment in this ticket for Allison and Ian to review. Feel free to bring in other Governance team members for their input if helpful.
- [ ] Once in agreement on changes, Allison/Ian will update the cards

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] All bugs and issues in the SR Dashboard have been resolved.
- [ ] Agreed upon changes to card designs have been implemented in the SR Dashboard.
- [ ] The Staging Review Dashboard is ready for VFS and OCTO to view and trust.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Hi @allison0034 @it-harrison A few things I'm seeing. Handing off to @briandeconinck for review as well.

### changes I made 
- **Labels for a11y defect graphs** I added more context about what the a11y 0 and a11y 1 labels mean, and added a link to our rubric for reference.
![Screenshot 2024-09-05 at 8 45 08 AM](https://github.com/user-attachments/assets/131e0a62-12b1-4309-b817-c9dbaef9cf75)

### suggested changes to graphs
- **a11y level 0 and 1 widgets - change to whole number?** Percentage here is unclear - percentage of total tickets? percentage of a11y tickets? Recommend changing this graph from a percentage to a whole number (count), for clarity and ease of understanding. 
  ![Screenshot 2024-09-05 at 11 10 27 AM](https://github.com/user-attachments/assets/cb919472-eb5e-4e8c-8a0b-265f2446852a)

- **Count accessibility severity defect per quarter** - can this graph show the total number of a11y tickets for each quarter as well as the breakdown of defect severity? So that we can also see how many a11y tickets there were overall each quarter. This would be similar to how we are doing with the two launch-blocking graphs.
  ![Screenshot 2024-09-05 at 11 09 26 AM](https://github.com/user-attachments/assets/7e3f626d-2969-4eb1-9087-117cb41b1876)

- **Count of tickets with imposter components vs tickets with VA components** The `va components` count is a little confusing since we don't necessarily always tag va components in use. Can the VA components be removed from this graph, making it just a count of imposter components findings, as compared to a total count of all findings by quarter?

- **Count of most common imposter components** Maybe this should be a bar or H bar graph - to better reflect the differences in the `count`s. i.e. the breadcrumbs are way more frequent than any of the others (twice as frequent as the next item on the list), but the funnel graph doesn't make it look that way.

**Comment by briandeconinck** [comment]
Thoughts on the accessibility stuff:
- I like the label change that Erin made
- a11y 0 and 1 widgets, I actually like percentages better than a straight count --- so long as there's some kind of labeling that makes clear what they're out of. Just a count doesn't really provide enough context for the overall "how are teams doing," which is where I think there's value here.
- For the quarterly breakdown on a11y defects, I think what's there now is fine but I do agree that it might be nice to see a total count per quarter as Erin suggested.

**Comment by erinrwhite** [comment]
Thank you @briandeconinck! @allison0034 @it-harrison In your court - let us know what questions you have on this.

**Comment by allison0034** [comment]
I am fine with all the suggestions.

**Comment by it-harrison** [comment]
@allison0034 @erinrwhite @briandeconinck 
I incorporated your feedback but would like to draw your attention to:
1. the gauge chart powering the "widget" summaries is not designed to do exactly what we want; I have done the best I could to incorporate all the info but we might need to switch to a different chart type if it doesn't work
2. "Count of tickets with imposter components vs all other tickets": showing the total of all tickets obscures the imposter ticket trend because the imposter counts are so much lower. should we just have a bar graph of imposter ticket counts per quarter?

**Comment by erinrwhite** [comment]
thank you @it-harrison !

1. The gauge chart for the a11y defects seems okay to me - was there anything in particular that is not working as it should? 👀 If it feels too hacky, I defer to @briandeconinck's [feedback above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91558#issuecomment-2334639482) "I actually like percentages better than a straight count --- so long as there's some kind of labeling that makes clear what they're out of."

2. "Count of tickets with imposter components vs all other tickets" - I agree this can just be a count of imposter ticket counts by quarter 👍🏻 

Thank you for making these changes!
