### ISSUE TITLE
Add Travel Pay controller to Mobile API Module

### ISSUE THREAD

**Issue by liztownd** [department-of-veterans-affairs/va.gov-team#91552]
## Issue Description
All VAHB API calls are routed through the mobile module in `vets-api`. A new controller for travel pay needs to be added to the mobile app module, leveraging the travel pay service and business logic.

---
## Tasks
- [ ] A new travel-pay controller is created in the `mobile` API module
- [ ] TODO: (Not sure which endpoints will need to be available yet, WIP)

## Acceptance Criteria
- [ ] All required endpoints are available within the `mobile` module providing the same functionality as the web versions
- [ ] TODO: list endpoints and required data returns for testing
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ayush-chak** [comment]
This might be something we can ask of the core mobile team - will need to investigate

**Comment by ayush-chak** [comment]
This is going to have to be broken down further - serializer, tests, update the docs, add schema, add model, etc.
