### ISSUE TITLE
Simple Mileage-Only Claim in VAHB Mobile App (MVP)

### ISSUE THREAD

**Issue by liztownd** [department-of-veterans-affairs/va.gov-team#91550]
## Description
Frontend work for adding SMOC to VAHB Mobile App

[Mobile Team Epic](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9663)

Existing branch: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9749/files

## User Story
As a Veteran or Caregiver, I want to submit a Mileage-only Claim in the Mobile App, so that I can be reimbursed for travel expenses.

## Risks
Requires #91552 (API) and #91570 (React Query integration) and #91573 (remote config feature flag)

### Claim submission
- [ ] Users are able to submit a SMOC through the VAHB Mobile App
  - [ ] Travel Pay help is available on every screen
  - [ ] Answering "No" to any question displays the ineligible type screen
    - [ ] Tapping "close" on an error screen (ineligible type or no address) returns the user to the appointment details screen
  - [ ] Cannot submit until travel agreement checkbox is checked
  - [ ] After successful submission tapping "close" or "go to appointment" takes the user to the updated appointment details screen where there is now travel claim details component and no longer a "file travel claim" alert

### Appending travel claim data to appointments:
Appointments eligibility:
- Appointment is less than 30 days ago
- Only In person and Atlas appointments are eligible to file through the VAHB app at this time
- Other appointments may have existing claims filed through the existing BTSSS portal (e.g. community care)

- [ ] Travel Claim information is available in the appointment list and appointment details where applicable
  - [ ] **On appointment list:**
    - [ ] If existing claim is not present and meets eligibility requirements:
      - [ ] A blue pill with "[x] days to file travel claim" is present on appointment list item
  - [ ] **On appointment details screen:**
    - [ ] If Claim is present
      - [ ] Displays claim information (regardless of mobile app _filing_ eligibility)
    - [ ] If claim is not present:
      - [ ]  There are no errors retrieving claims and meets eligibility requirements:
        - [ ] File claim alert appears at the top of the appointment details screen
      - [ ]  There are no errors retrieving claims and appointment is MORE than 30 days old and meets eligibility requirements:
        - [ ] Messaging that a claim was not filed and there is a 30 day limit appears
      - [ ] There were errors appending claims to appointments:
        - [ ] Messaging that travel claims are unavailable with Help text is displayed

### Updating user address:
- [ ] If the user doesn't have an address they are routed to the "No Address" error screen when they tap yes on the vehicle question screen
- [ ] The "No Address" error screen will link the user to the place in the app where they can update their address right from the Travel Pay flow and would return them back to the flow after saving
- [ ] After saving their address the user will be brought back to the Travel pay flow on the address question screen

## Definition of Done
- [ ] Users can submit a SMOC for an appointment at a VAMC for mileage-only travel reimbursement
- [ ] Documentation is updated

---
## How to configure this issue
- [x] **Attached to an Epic**

**Comment by kellylein** [comment]
The VAHB App team will be tracking our work under this Epic: https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9563
