### ISSUE TITLE
2024 Q3 PACT Act bulkhead removal

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91578]
## User Story
As the managers and developers for the VA Platform, 
We need to pull down the bulkheads from the Q3 PACT Act work, 
So that there are no remaining endpoints present. 

## Issue Description
Need to pull down the bulkheads that were stood up for the PACT Act Q3 monitoring, as the Pact Act surge for Q3 seems to be over. See [this Slack thread](https://adhoc.slack.com/archives/C06G2QB9X8T/p1724343446903649) for managerial direction. 

## Tasks
- [x] Remove the Q3 PACT Act bulkheads
- [x] Perform testing as necessary
- [x] Document any issues as necessary

## Success Metrics
Q3 PACT Act bulkheads have been removed from the Platform.

## Acceptance Criteria
- [x] Q3 PACT Act bulkheads have been removed. 
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by LindseySaari** [comment]
[PR has been merged](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3072)

**Comment by jennb33** [comment]
Closing ticket on 9/4/2024
