### ISSUE TITLE
EKS Testing: Reliability team; MVP testing with the unauthenticated endpoints

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91587]
## User Story
As the Reliability team resources, 
We need to perform the EKS MVP testing with the unauthenticated endpoints, 
So that any errors with the unauthenticated endpoints can be discovered and mitigated before being released to a live environment

## Issue Description
Postman tests have been assembled into a single collection in Postman cloud account, and the Postman test collection is stored in the Platform Postman Cloud account [VA.gov Platform Reliability Team | Public APIs | Postman API Network](https://www.postman.com/vagov-prt). 
Postman test collection is configured to prepend request urls with an environment variable `env_url`
Refer to general Postman best practices – [Document Your API Like a Pro: Postman Collection Best Practices | Postman Blog](https://blog.postman.com/document-your-api-like-a-pro-postman-collection-best-practices/) 

## Tasks
- [x] Postman test scripts are retrieved into the postman/newman container provided by the PRT through Docker hub and executed by the default postman installation in the container
- [x] Exception Handling: Exceptions while executing tests are reported as a test fail
- [x] Document MVP testing and outcomes of testing in the Test Plan Confluence [documentation](https://vfs.atlassian.net/wiki/spaces/PRT/pages/3307569516/Design+Document+Using+Helm+Test+for+vets-api+Internal+Testing+Option+5)

## Success Metrics
Testing will be completed with a low error rate. Any outstanding issues that are discovered during testing need to be ticketed separately for mitigation work.

## Acceptance Criteria
- [x] Testing the MVP EKS work with unauthenticated endpoints is complete
- [x] Documenting the testing work process and outcomes
- [x] Documenting future work that are outcomes from testing

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by IGallupSoCo** [comment]
[Vets-api branch with the collection added at a root level.](https://github.com/department-of-veterans-affairs/vets-api/tree/postman-collection-integration)

**Comment by IGallupSoCo** [comment]
<img width="971" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1haQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dd6ff9ab4b0bdb3ea20de8f7c144630ae503ef6/image.png" alt="image.png" />

**Comment by IGallupSoCo** [comment]
Local manipulation of the target url is working as intended.

**Comment by IGallupSoCo** [comment]
Five endpoints, all tied to the FHIR service, have been removed from the collection.  These endpoints are not currently being covered by tests of any kind within the vets-api repo, and cannot be found (404) within the Staging environment.  [We have some scattered info on the FHIR endpoints, and their placement within the Lighthouse API.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/questionnaire-trigger/01.using.fhir.4.md?plain=1#L15)
