### ISSUE TITLE
Staging Review: Section 103 Updates to the GI Bill Comparison Tool

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#9158]
## Steps to complete Staging Review:
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey
## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/product-outline.md)
- [Link to release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/Sec103ReleasePlan.md)
- Access information for the tool or feature in staging:
    - The information displayed is dependent upon the institution type.  Below are examples where the indicator is displayed.
    a. https://staging.va.gov/gi-bill-comparison-tool/profile/11929140
    b. https://staging.va.gov/gi-bill-comparison-tool/profile/31002227
    - Some institutions do not display the new 103 information intentionally.  Ex: https://staging.va.gov/gi-bill-comparison-tool/profile/10643840
- Link to your product test cases/test plan in TestRail with test execution logs:
    - https://dsvavsp.testrail.io/index.php?/plans/view/399
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
   - https://dsvavsp.testrail.io/index.php?/reports/view/78
   - https://dsvavsp.testrail.io/index.php?/reports/view/85
- Link to your accessibility test cases:
   - ~~https://dsvavsp.testrail.io/index.php?/reports/view/81~~
   - ~~https://dsvavsp.testrail.io/index.php?/reports/view/82~~
   - https://dsvavsp.testrail.io/index.php?/tests/view/5852&group_by=cases:section_id&group_order=asc&group_id=46
- List of known issues (with links to tickets when applicable)
    - https://dsvavsp.testrail.io/index.php?/reports/view/79
    - https://dsvavsp.testrail.io/index.php?/reports/view/86
## Meeting attendees from **Education Application Team - BAH**
- Product Manager (required): **Darrell Neel**
- DEPO product lead (required): **Matt Self**
- Anyone else from your team who significantly contributed to the artifacts provided (required):
    - Will McCormack
    - Desiree Turner
    - Dan Shawkey
    - Amy Knox
    - Michael Delli-Gatti
    - Adam Sonntag
## Scheduling
Preferred dates or times: All Times Eastern
05/18 - 10:30am - 11am, 1pm - 1:30pm
05/19 - 11am - 12pm, 1pm - 2:30pm
05/20 - 10am - 11am, 1pm - 2pm
## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by meganhkelley** [comment]
Scheduled for 5/19

**Comment by 1Copenut** [comment]
Accessibility issues are logged in the epic here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9239

Six issues total, but none are launch blockers. Small adjustments and a couple of higher priority items for IE11 that appear to be regressions from production for handling focus after the modal windows are closed.

**Comment by peggygannon** [comment]
@dneel-bah @amyknox Content recommendations have been uploaded to this ticket: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/9233

**Comment by dneel-bah** [comment]
All steps completed as of 06/01.  Closing out this ticket.
