### ISSUE TITLE
EKS Testing: Reliability team; Create a Postman docker image

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91591]
## User Story
As the Reliability team resources,
We need to create and deploy a postman docker image, 
So that this part of the functional requirements is complete. 

## Issue Description
Create a postman docker image: a “vets-api postman” docker image be built & published as part of the vets-api github build workflow to ECR. This container would have the Postman/Newman executables as well as the associated postman scripts.

## Tasks
- [x] Docker image to contain postman executable and configurations
- [x] Created and versioned at build 
- [x] Docker image needs to live in this new directory
- [x] Modify these build workflows as necessary
- [x] Document the build of the docker image, including any information that may be prudent to understand for other dev resources.

## Success Metrics
Docker image has been created and integrated without causing any new errors or issues. 

## Acceptance Criteria
- [ ] Postman docker image that has been created and versioned at build, residing in the new directory. 

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by IGallupSoCo** [comment]
I made a bunch of headway on this a while back before putting it down for other priorities.  I'll pull together links for the ticket and branch.

**Comment by IGallupSoCo** [comment]
- [Initial work ticket](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/79237)
- [Current work's state](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/85089)
- [Branch with the unfinished work](https://github.com/department-of-veterans-affairs/prt-preview-control/tree/integrate-postman-testing-to-publish-workflow)

**Comment by IGallupSoCo** [comment]
To summarize what's left to do:
- The integration itself is finished.  
<img width="1154" alt="Screenshot 2024-09-06 at 9 33 36 AM" src="https://github.com/user-attachments/assets/8685e939-fb01-4244-8ed6-74b41459aa44">
The Postman test collection was integrated into the build-and-publish workflow.  First, it takes the just-built image and spins up containers for both postgres and the control plane.  Then it installs Newman, a Postman CLI utility, checks up on the control plane container, and sets it up for testing the control plane container at port 50000.  If the tests fail, the GHA runner will exit the workflow and leave the publish job undone.  Either way, logs should have been captured by docker for review as needed.  The containers are then destroyed 

What's left:
- The collection currently stored within the prt-control-plane repo on that branch is a dummy collection that will neither pass nor do anything useful.  I was working with it before the vets-api EKS initiative work, and understood far less about how to properly configure the collection or about the endpoints that would be under test.
- As this effort has moved on and progressed, the configurations set within some of my added commands are almost certainly outdated or may need a complete rework
- The test cleanup job was written at a time when we believed we only needed one container running to successfully run the test collection.  It needs updated to destroy both test containers used.

**Comment by IGallupSoCo** [comment]
The image is ready, pending some helm chart adjustments by Patrick.

**Comment by IGallupSoCo** [comment]
PR 1 of 3 is done!

**Comment by IGallupSoCo** [comment]
The docker image for our collection runs has been merged into the master branch of vets-api

**Comment by IGallupSoCo** [comment]
The final version of the collection's Dockerfile: 
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3p3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31a7d522a3b617cdc9fb18b42b0a24282fa939fd/Screenshot%202024-09-20%20at%202.21.30%E2%80%AFPM.png" alt="Screenshot 2024-09-20 at 2.21.30 PM.png" />
