### ISSUE TITLE
EKS Testing: Reliability; Create a helm test after sync hook

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91595]
## User Story
As the Reliability team resources,
We need to create a Helm test hook on after sync,
So that the helm chart is complete, tested, and operational. 

## Issue Description
Create a helm test after sync hook. This will need to be done after the [creation of the helm chart](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91593)

## Tasks
- [ ] Create a helm test after sync hook
- [ ] Test the new Helm test as necessary
- [ ] Document the creation of the new Helm test, including any information that may be prudent to understand for other dev resources.

## Success Metrics
Helm tests are complete, with no new issues or errors

## Acceptance Criteria
- [ ] Create a k8s job in the parent helm chart that is a post upgrade hook

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by jennb33** [comment]
9/25/2024: closing this ticket as completed.
