### ISSUE TITLE
EKS Testing: Reliability; create new helm chart for the Postman work

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#91593]
## User Story
As the Reliability team resources,
We need to create a new helm chart for the postman test execution work, 
So that the helm chart is complete, tested, and operational. 

## Issue Description
Create a new helm chart for the postman work in the parent helm chart. This could live in Vets API next to the Vets API chart, or separately
The postman helm test will be placed as a resource in the “parent” helm chart - the parent is Helm 3.

## Tasks
- [x] Create new helm chart for the Postman work in the parent helm chart
- [x] Test this new helm chart as necessary
- [ ] Confirm that the Kubernetes  job within the vets-api parent helm chart is utilizing the post-install and post-upgrade hooks
- [ ] Confirm that the Kubernetes job for the Postman tests is a resource in vets-api deployment
- [ ] Document the creation of the new helm chart for the Postman work, including any information that may be prudent to understand for other dev resources.

## Success Metrics
New parent helm chart is created and lives in the parent helm chart and has been confirmed to be using the post-install and post-upgrade hooks, resulting in no functional errors after creation and testing.

## Acceptance Criteria
- [ ] There is a new, approved helm chart for the Postman work that lives in the parent helm chart that uses the post-install and post-upgrade hooks. 

---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._

**Comment by IGallupSoCo** [comment]
<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm53Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acc1d10817ecdacd726b9ad90940df1a3678b7a4/Screenshot%202024-09-20%20at%203.02.21%E2%80%AFPM.png" alt="Screenshot 2024-09-20 at 3.02.21 PM.png" />
