### ISSUE TITLE
[CST] Update some text in Standard 5103 document request page

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#91601]
## Background Context

We have one additional content recommendation for the Standard 5103 document request page text

Before (old)
<img width="1138" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53cd9c314f7fce422d571f5fbba9398cae3737c4/Screenshot%202024-08-27%20at%2012.01.02%E2%80%AFPM.png" alt="Screenshot 2024-08-27 at 12.01.02 PM.png" />

After (new)
<img width="1114" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUdQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed09caf6a5d4ca7c7269ac9d68a6ef4449982548/Screenshot%202024-08-27%20at%2012.01.08%E2%80%AFPM.png" alt="Screenshot 2024-08-27 at 12.01.08 PM.png" />

### New Feature
- Why are we doing this work?
- Epic Link

## Outcome, Success Measure, KPI(S), and Tracking Link
- Add here

## Design
[FIGMA](https://www.figma.com/design/BUdMIxAiIutG12rZxZ0cg1/Claim-Letters-Navigation-%2B-5103-Alert-Updates?node-id=3769-26687&t=ar9HiwvAFmL4MqlZ-4)

### Enablement team (if needed)
@jstrothman @laurwill 

## Engineering 
- Add here

## Out of scope
- Add here

## Open questions
- Add here

## Tasks
- [x] _Update string based on spec_
- [ ] _Task_
- [ ] _Task_

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _String is updated_
- [ ] _AC_
- [ ] _AC_
