### ISSUE TITLE
[CDP]VHA One-thing-per-page/ Balance mockups - Updates (2 of 3)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#91613]
## Description

Make updates based on SME feedback

## Tasks
- [x] Update VHA summary page
- [x] Update VHA Details page
- [x] Update VHA Resolve page

## Acceptance criteria

- [x] Updates have been made

---

## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [ ] Description written
- [ ] Tasks defined
- [ ] Acceptance criteria written
- [ ] Testing defined
- [ ] Add Labels
- [ ] Attach to an Epic
- [ ] Estimate Points
</details>

**Comment by mgleo** [comment]
Mock ups updated https://www.figma.com/design/OiiDTTVTCf8j0GngRg0xxD/VA-Debt-Portal?node-id=3212-30062&t=rdvTuXpPGEpXiX9l-1
