### ISSUE TITLE
Design changes for Left Nav Release

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9162]
## Problem Statement
How might we ensure implementation is consistent with design before release?

---
## Tasks
- [ ] Make white space in left nav menu consistent
    White space should be visibly the same above, below and between all line items, whether the menu is open or closed. 
    Current padding above SERVICES AND LOCATIONS is 33 pixels and should be 22 pixels

- [ ] Section Headings (ie: SERVICES AND LOCATIONS) need to be rendered in 14
    Current headings are rendering at 15

- [ ] Address mobile scrolling bug
    Bug was introduced that prevents mobile nav scrolling if the user clicks on active element

![spacing](https://user-images.githubusercontent.com/55411834/82070917-a07a9080-9692-11ea-8811-1e61f3c9030d.png)

![typography](https://user-images.githubusercontent.com/55411834/82070952-a8d2cb80-9692-11ea-914f-988fbfe1af86.png)

## Acceptance Criteria
- [ ] White space above, below and between all line items, is visibly the same (22 pixels) whether the menu is open or closed. (In particular, the space above SERVICES AND LOCATIONS should be checked.)
- [ ] If a mobile user clicks on any interactive element, scrolling is still available in the left nav.
- [ ] Mobile users can see "In this section" when the nav menu is collapsed. 
- [ ] Section Headings (ie: SERVICES AND LOCATIONS) render at 14

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Additional notes:
- Mobile Nav is fine above the H1 heading, per @rtwell 
- We will look at the left nav behavior in mobile experience separately (overlapying content vs pushing down)

**Comment by rtwell** [comment]
last note: the quirky interaction of clicking a parent page (e.g.Locations), and before the page reloads to take the user to the Locations page, the nav section is visible **before** the page loads. the page should load first.

**Comment by mmiddaugh** [comment]
@rtwell, these changes are ready for your review in https://staging.va.gov/pittsburgh-health-care/

**Comment by rtwell** [comment]
looks like we've missed a couple items:

1. on mobile, when the In this section menu is exposed, scrolling does not work, unless you scroll in a dead zone (like the "SERVICES AND LOCATIONS" header). I'm wondering if it's because we are using the hover state on tap? On va.gov mobile main nav, users can scroll up and down without a problem, but there is no hover state/on-tap state. 

2. the quirky behavior of children navs displaying before the page loads is still happening. 

3. we need a tad more white space above "Services and locations"—that's my fault for not providing a comp, so i'm attaching here. on mobile, "In this section" is too close to "Services and locations", and i have attached the spacing here as well

![image](https://user-images.githubusercontent.com/12564977/83908052-74ec4280-a734-11ea-9305-dbf804322b6f.png)
![image](https://user-images.githubusercontent.com/12564977/83908203-afee7600-a734-11ea-8df5-9a5c022b85f4.png)

**Comment by mmiddaugh** [comment]
Splitting these items into individual issues to be prioritized, groomed and resolved:
1. Mobile scrolling [#9942](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9942)
2. Quirky page loading behavior [#9943]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/9943)
3. Padding [#9945]( https://github.com/department-of-veterans-affairs/va.gov-team/issues/9945)

Closing this issue.
