### ISSUE TITLE
[Prototype] Development Sprint - Schema.org COVID-19 Announce

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#9163]
## User Story or Problem Statement

How might we use organic search (e.g. Google, Bing) to more effectively communicate COVID-19 announcements (e.g. emergency national protocols, etc.) to veterans and stakeholders?

## Goal
Determine if new schema markup -- or [via Google submission process](https://developers.google.com/search/docs/data-types/special-announcements#using-search-console) can be "easily" implemented, maintained and tracked for performance by VA.gov.

## Government Policy or Mandate

On April 15, 2020, a blog post from the White House directed that federal government websites add “SpecialAnnouncement” schema.org tags on web pages with information pertaining to the coronavirus pandemic to help ensure these critical resources appear in search engine results.

## Objectives or Key Results this is meant to further

- Increase VA.gov Search Authority
- Improve VA.gov search ranking for COVID-19 related keywords
- Drive broader awareness of emergency operational state of VA.gov facilities and services across service-member and stakeholder community
- Increase referral traffic from search engines to VA.gov as the single source of truth
---
## Tasks
- [x] Review implementation details from [Google here](https://developers.google.com/search/docs/data-types/special-announcements#using-search-console) and from [USA.gov blog post here](https://digital.gov/2020/05/11/experimenting-with-specialannouncement-markup).
- [x] Create mockups or prototypes of various COVID-19 announcement types available via special markup and/or submission process
- [ ] Define how the process of maintaining the announcements will be feasible -- e.g. via mappable data elements in existing content or via specialized publishing workflow.

## Acceptance Criteria
- [ ] A demo and proposal for how VA.gov would move forward with this opportunity would be provided to stakeholders and decision-makers for Go/No.

## Example Screenshots

USA.gov COVID-19 Special Announcement
<img width="659" alt="Screen Shot 2020-05-20 at 3 07 19 PM" src="https://user-images.githubusercontent.com/63107147/82487429-53405980-9aac-11ea-88bf-c39e73bd73ca.png">

Current VA.gov COVID-19 Search Results
<img width="350" alt="Screen Shot 2020-05-21 at 1 03 53 PM" src="https://user-images.githubusercontent.com/63107147/82585247-b3de9d80-9b63-11ea-9885-13c9e32eb082.png">

Low Fidelity Wireframe of VA.gov Special Announcement
<img width="448" alt="Screen Shot 2020-05-21 at 1 04 03 PM" src="https://user-images.githubusercontent.com/63107147/82585281-c22cb980-9b63-11ea-92c3-fb3aaf1070de.png">

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
Recap of discussion with Jen and follow-ons:

Per Jen convo:
- Confirm this is a White House priority/mandate -- or more directional. (John following up with USA.gov)
- Determine the value -- e.g. Will this improve VA.gov's COVID-19 keyword rankings -- and/or improved Search Authority, as measured by SEMRush.   (John is checking via the Google Dev Forum. It appears there is no explicit guarantee of this)

Other updates:

- We will need a Search Console account in order to submit a Special Announcement.  (VFS-Platform team plans to tackle in next sprint).
- Submitted special announcements expire after 30 days; markup Special Announcements can be configured to expire as the publisher/entity sees fit.

**Comment by johnhashva** [comment]
[White House directive on Schema.org Special Announcement for COVID-19 information](https://www.whitehouse.gov/articles/connecting-americans-coronavirus-information-online/):

In an effort to enhance the visibility of coronavirus information online for the American public, The White House Office of Science and Technology Policy (OSTP) and Office of Management and Budget (OMB) have directed Federal Chief Information Officers to incorporate these new Schema.org standard tags into all federally maintained webpages related to COVID-19. In addition, OSTP and OMB are encouraging the private sector, State and local governments, and the academic community to do the same.

**Comment by johnhashva** [comment]
Per David Kaufmann at USA.gov: Adding the markup will not improve the results ranking for any given page. A page won’t be listed higher in search results pages than it normally would by adding the markup. But while using schema.org tags like this does not improve position in search results, if a page already ranks highly for a certain query and that page has supported schema.org markup on it, the special treatment for that page’s listing may be triggered.

**Comment by johnhashva** [comment]
Manual submission of Special Announcements (as opposed to implementation of the Schema.org markup) come with two caveats: the announcements have early expiration dates, and Bing and other search engines do not get the information.

**Comment by stephorkandatx** [comment]
@ncksllvn noting that Kevin Walsh has said there may be areas CMS team can support us on with this, or some implications related to the output of this discovery. Something to keep in mind as we move forward

**Comment by johnhashva** [comment]
@jenniferlee-dsva Update on White House directive about this -- David Kaufmann at USA.gov says his interpretation is that implementation of Schema.org COVID-19 markup is a "mandate."

**Comment by ncksllvn** [comment]
The Facility Locator may actually be a pretty good use case. Check out my [Google results](https://www.google.com/search?q=florence+va+clinic&rlz=1C5CHFA_enUS762US762&oq=florence+va+clinic&aqs=chrome.0.0l7j69i60.2807j0j7&sourceid=chrome&ie=UTF-8) - 

![image](https://user-images.githubusercontent.com/1915775/82682692-a685e980-9c1d-11ea-8ef6-3170cec0edf9.png)

So then this little [banner](https://www.va.gov/find-locations/facility/vha_539GD) could be really easily converted into a special announcements...

![image](https://user-images.githubusercontent.com/1915775/82682788-cfa67a00-9c1d-11ea-81be-ad9208ccca84.png)

The only part of the special announcement that still throws me off is that special announcements _have_ to have an expiration

**Comment by johnhashva** [comment]
Update from @DanielleThierryUSDSVA :  @lalexanderson-dsva and @jenniferlee-dsva have approved the wireframe mockup and our approach for the VA COVID-19 Search Results prototype test (e.g. we will build, deploy and use Google Search Console to track impressions, CTRs and bounce rate).  Next steps:

- @DanielleThierryUSDSVA will help us firm up the content/links (including order and wording).  One link to be included is this data page -- https://www.accesstocare.va.gov/Healthcare/COVID19NationalSummary

- I will work to confirm we will be able to track performance of this special search result via Google Search Console and GA.

**Comment by johnhashva** [comment]
6/5 Update:
- @DanielleThierryUSDSVA has delivered the content deck for the search results card -- Ticket #9863

**Comment by johnhashva** [comment]
6/8 Update:

@ncksllvn [here are details](https://www.searchenginejournal.com/google-search-console-reports-on-covid-19-special-announcement-schema/366150/#close) on how we can track the performance of our COVID-19 Special Announcement/FAQs via Google Search Console.  The TL/DR:

- After adding the markup to a page, test to make sure it is working[ via the rich results tool](https://search.google.com/test/rich-results?utm_source=support.google.com/webmasters/&utm_medium=referral&utm_campaign=7445569) prior to publish.

- With verified code, we will be able to track the performance of the COVID FAQs via the Rich Results performance tab in GSC

![image](https://user-images.githubusercontent.com/63107147/84033902-96814000-a967-11ea-9ffa-888c5e5fd1c9.png)

**Comment by ncksllvn** [comment]
I'm checking USA.gov Coronavirus FAQs via Google in an In Cognito tab while trying to figure out how we're supposed to properly encode the HTML inside the JSON. Pretty cool -

![image](https://user-images.githubusercontent.com/1915775/84042329-ec0f1a00-a972-11ea-9314-08efe9cc9b70.png)

![image](https://user-images.githubusercontent.com/1915775/84042968-bb7bb000-a973-11ea-8acc-e26dbe8a260e.png)

They have _a lot_ of content packed in there.

**Comment by ncksllvn** [comment]
First attempt at drafting this into schema.org - https://github.com/department-of-veterans-affairs/vets-website/blob/9c9b305021b77dbf2a90a013682bdcc229a497f8/src/site/includes/coronavirus-schema-org.json.liquid -

```
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "How will COVID-19 affect my VA health care and benefit services?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "&lt;p&gt;Visit our &lt;a href=&quot;https://www.va.gov/coronavirus-chatbot/&quot;&gt;coronavirus chatbot&lt;/a&gt; or &lt;a href=&quot;https://www.va.gov/coronavirus-veteran-frequently-asked-questions/&quot;&gt;frequently asked questions (FAQs)&lt;/a&gt; for up-to-date answers.&lt;/p&gt;"
        }
      },
      {
        "@type": "Question",
        "name": "Is my local VA health facility or regional office open?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "&lt;p&gt;Get the latest information about hours, services, and COVID-19 safety measures for &lt;a href=&quot;https://www.va.gov/find-locations&quot;&gt;VA locations&lt;/a&gt;.&lt;/p&gt;"
        }
      },
      {
        "@type": "Question",
        "name": "How many COVID-19 patients have been tested or treated at VA facilities?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "&lt;p&gt;Review our &lt;a href=&quot;https://www.accesstocare.va.gov/Healthcare/COVID19NationalSummary&quot;&gt;COVID-19 national summary&lt;/a&gt; for data by state and VA facility.&lt;/p&gt;"
        }
      },
      {
        "@type": "Question",
        "name": "What's VA doing to deal with COVID-19?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "&lt;p&gt;Learn&nbsp;about our &lt;a href=&quot;https://www.publichealth.va.gov/n-coronavirus/&quot;&gt;public health response&lt;/a&gt; to the coronavirus pandemic.&lt;/p&gt;"
        }
      }
    ]
  }
</script>
```

**Comment by johnhashva** [comment]
6/9: Note to @ncksllvn -- @DanielleThierryUSDSVA is working to get approval for the FAQ content.  She will provide an update when this week when that's in hand.

**Comment by ncksllvn** [comment]
### Schema.org PoC
- Awaiting Danielle and Lauren's approval for content
- Confirm w/Google how long until we can see the FAQPage widget on search results (and also clarify any criteria for how the widget is shown - how come I can Google the same thing as John but only one of us sees usa.gov's schema.org widget?)
    - For external links, should we add a flag into the URL to carry tracking data to help measure success? 
- Has to go straight to prod because staging is not indexed 

### TypeAhead (unrelated to this issue)
- What UI changes do we need to make? Sync w/Liz
- Data - how is this data seeded? The suggestions for query `file` aren't what we expected.
- Tracking - if we were to launch this in X sprints, are we okay with measuring success via a single dedicated Google Analytics event?

**Comment by ncksllvn** [comment]
Per this - https://github.com/department-of-veterans-affairs/va.gov-team/issues/9863 - we are good to go for launching the FAQ Page schema!

**Comment by ncksllvn** [comment]
Merged the work for implementing the schema.org structure - https://github.com/department-of-veterans-affairs/vets-website/pull/13002

This will go on the website today, but we'll need to manually search Google for the coming days to see when it takes effect. 

Last time we tried verifying schema.org changes, it was difficult - we weren't able to see the effects on Google search. We were using the Microdata format then though, so we may see better results with the JSON LD format.

**Comment by johnhashva** [comment]
Note: I will begin monitoring Google Search Console which should capture impressions and clicks for this FAQ in the rich results tab.  Will report out results weekly for the first two full weeks of run.

**Comment by stephorkandatx** [comment]
@johnhashva thank you in advance for the monitoring. I will close this out later today, after this work is in production. Future updates will be written separately.

**Comment by stephorkandatx** [comment]
Keeping in Validate as the analytics are captured. Will take at least a few days to ensure data is flowing correctly

**Comment by stephorkandatx** [comment]
@johnhashva I'd like to close this one out - any future improvements or learnings can be captured in another ticket. Let me know if you have any concerns. Thanks!

**Comment by johnhashva** [comment]
@stephorkandatx I'm of two thoughts here: We keep it open until we confirm it is "working as intended" -- e.g. generating impressions and clicks to measure effectiveness in driving referral traffic (I should have made it clear that this is part of the acceptance criteria).   OR, close it, and I can generate another ticket that covers what we may need to do to make sure this feature is index-able by Google (we think there may be a page error that disqualifies it for Rich Results).   Let me know which you think is wiser and I'll make it happen.

**Comment by stephorkandatx** [comment]
Because of the current acceptance criteria, and the fact that we did the work last sprint but the ticket remains "open" and is lingering, I recommend we close this out and create a new ticket to make the work indexable. It will be better to track what work was done, and when.

**Comment by johnhashva** [comment]
Got it -- I'll compose a new ticket once I validate the work effort with Nick (we are scheduled to meet on this tomorrow).   TY.

**Comment by MickinSahni** [comment]
#10772 - follow-on work re this ticket. 

Closing this particular ticket out.
