### ISSUE TITLE
Analytics Product Success Tool Request for VAOS-R

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9164]
# Request the Product Success Tool

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request the PST Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/product-success-tool-request.md)
- [ ] Ensure your KPIs are clearly linked back to your OKRs or goals
- [ ] Link your KPIs below
- [ ] Submit this ticket as an epic
- [ ] Add your team label to follow progress

### KPIs
[VAOS-R KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/vaos-kpis.md)
*Notes:* 

- Much of the data we are collecting now didn't exist before for the legacy tool. I am trying to find what I can, but where a baseline doesn't exist I am considering using our current stats as baseline. 
- Also, there is a section in our OKR/KPI .md titled "Add't Product Health Metrics". These are items that provide more visibility into what users are doing in the app. They are also reporting metrics used back to stakeholders that I would like to populate into this tool if possible (currently we collect these in our GA dashboard). 

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by lenaecb** [comment]
Let me know if you want me to drop the existing funnels and dashboards links we're already using in GA, Grafana, and Sentry in here.

**Comment by bsmartin-ep** [comment]
@lenaecb -

From your KPI document...

> KPI - # of Veterans who schedule an appointment ongoing

What do you mean by "appointment ongoing"

**Comment by lenaecb** [comment]
@bsmartin-ep - sorry, poor phrasing...

This is more about coming back to use the tool frequently. The KPI aligns with the retention objective. 

So, I would think it would be reframed around # of appointments submitted over a length of time to show the Veteran is returning to the tool and continuing to use it for scheduling?

**Comment by joanneesteban** [comment]
@lenaecb A couple of OKR follow up questions as well. Would it be possible to rephrase some of these in terms of goals? A couple of suggestions:

> OBJECTIVE 2: Increase veteran satisfaction rates of VA Online Scheduling experience.
KR - Current baseline as of 5/12/20 from Foresee 4.3

- KR Suggestion: Increase satisfaction rating by X%

> OBJECTIVE 3: Surface impact of site configuration/conditional checks on scheduling completion and appointment cancellation rates.
KR - As of 5/15/20, failed eligibility is impact 20% of users and causing 14% dropoff in scheduling funnel.

- KR Suggestion: Decrease user dropoff by X% 

> OBJECTIVE 4: Improve retention of Veterans using VAOS
KR - No baseline currently exists

- KR Suggestion: Increase VAOS user retention by X%

---

Also, for the Customer Satisfaction KPIs, do you have the sources for these:
- KPI -VA Mobile rating and feedback
- KPI - Qualitative feedback collection from VA Mobile feedback source

---

Happy to meet up on this, and let me know if you have any questions! You can find additional resources [here](https://docs.google.com/presentation/d/1OGdCLFYGA4cb5nDUTJOme_7UBdAM49bX5zpYZ-zg6rw/edit#slide=id.g6d866f9dc2_0_175).

**Comment by lenaecb** [comment]
@joanneesteban - yes, I can rewrite those, but I wanted to point out that we do not currently have a baseline. I was hoping we could get tracking started for these items and once they are being track, take a snapshot of the tool and use existing analytics as baseline for update objective and goals.

**Comment by joanneesteban** [comment]
@lenaecb - Ok! Wanted to make sure that was on your radar for the resulting Product Success Tool.

Also, here's the ForeSee data as of today (6/8/20). So far, there are 30 responses with an avg of 4 stars. Let me know if you have any questions!
[VAOS - 5 Stars - 6.8.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4747894/VAOS.-.5.Stars.-.6.8.20.xlsx)

**Comment by lenaecb** [comment]
@joanneesteban - I realized I never updated you that I updated our KPI doc - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/vaos-kpis.md

Not sure if you need/want me to update in the working google doc that Brian has been using. 

Also, still working on how to get access to the source of the VA Mobile data. More to come hopefully soon.

**Comment by lenaecb** [comment]
@joanneesteban - I am doing to future planning, and would like to setup time with some of the OCC (office of connect care) folks who also do analytics for VAOS. 

I wanted to show them the v1 of the DOMO dashboard based on the objectives/kpis we established. When do you think we'll have something stood up? I'll set the meeting up for after that date/estimate. 

Also, let me know if there is anything else you need from me!

Thanks!

**Comment by joanneesteban** [comment]
@lenaecb thanks for checking in and sending the update over! The team will reconvene on this today and get back to you!

**Comment by joanneesteban** [comment]
@lenaecb we're adding you to the Domo dashboard, but just an FYI it's not in its "finished state." The datasets are good to go, so please let us know if you have any feedback! 

We should be ready before the end of the week; would you be able to meet with us next Monday or Tuesday for the hand off?

**Comment by joanneesteban** [comment]
@lenaecb - checking on the Domo dashboard before closing this out! Is there anything else you'd like to see from us for this dashboard?
