### ISSUE TITLE
Add Page on FOIA Requests

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#91658]
## Pain Point
- Currently, no guidance on FOIA requests exists on Platform website, so anyone on a VFS wanting to make or triage a request does not have instructions.
 
## Issue Description
We need to choose the location on Platform website for [this FOIA requests guidance page](https://vfs.atlassian.net/wiki/x/KwBVyw), the content of which has been approved by leadership.

---
## Tasks
Determine among team where in IA should the new page live
- [ ] Getting Started landing page 
- [ ] Support landing page

## Acceptance Criteria
- [ ] IA for page will be decided
- [ ] page is ready for deployment
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jknipes** [comment]
[Slack conversation for context](https://dsva.slack.com/archives/CL181NRJQ/p1723737994730659)

**Comment by jknipes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/91658?planning-poker) with Zenhub @BSmolensky @cmarion93 @laucon @taylojill
