### ISSUE TITLE
[PM] My VA Forms Status: Coordinate analytics needs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#91662]
## Background
Previously we had determined that our metric focus for the mvp would be as follows:

- for the MVP metrics will be capturing a baseline since this is a brand new feature on My VA
- baseline items we'll track: downloads, clicks from confirmation page (VFF page) to My VA, if notifications are included in MVP engagement with them (email and onsite)
- we will also investigate if we can use the method that the health team used to capture engagement without clicks via the va alert component firing

We need to work with Analytics and submit our analytics request to get appropriate tagging implemented where needed. Ideally we'll need to have all statuses functioning on staging + download functionality if before moving forward with this just to make sure we can capture everything in our request.

## Tasks
- [x] Attend analytics off hours with FE dev and designer
- [x] Submit analytics request

## Acceptance Criteria
- [x] Analytics request is submitted

**Comment by ajakabcin** [comment]
submitted request #93283
