### ISSUE TITLE
Migrate VAMC endpoint to new V1: React

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#9168]
## User Story or Problem Statement
How might we maintain VAMC data flow with the new API endpoint  ?

## Goal
VAMC functionality is maintained once endpoint is switched

---
## Tasks
- [ ] Ensure React content on VAMC facility pages which is dependent on API uses new v1 endpoint and renders correctly on the page

## Acceptance Criteria
- [ ] Content functionality is maintained
- [ ] Access to care, satisfaction scores and wait time data all renders on the page as appropriate
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
@mmiddaugh this a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/9167
