### ISSUE TITLE
[CST] Frontend changes to rename claims for death benefits 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#91689]
## Value Statement
**_As a_** person looking for a status on a  "Death" claim
**_I want to_** see a title for those claims that is more compassionate
**_So that_** I feel my loss is being respected

---
## Background Context
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/99273
From Julie: 

In the last 30 days, DataDog indicates we showed "Claim for Death" ~450 times. Not a huge number, but there are 2 things I think we should look into. Could you log issues?
What are more informative/less harsh names we could use for these claims? EP codes include: 169, 165, 299, 160, and 110. I found the following in M21 appendix B
EP 110 - These are Initial Disability Compensation Claims - Seven Issues or Less, so I'm not sure what data point we use to label it "Claim for Death"
EP 160 - Claim for reimbursement of burial-related expenses? -  "EP 160 applies to claims for the statutory burial allowance, plot allowance, reopened claims for reconsideration of a prior decision, and claim for reimbursement of headstone, marker, or additional engraving expenses."
EP 165 - Claim for reimbursement for death-related expenses? - "EP 165 applies to claims solely for compensation or pension payable as reimbursement of the expenses of last sickness and burial or claims for accrued benefits payable based on relationship when EP 140 or 190 is not involved."

Current:
![Image](https://github.com/user-attachments/assets/b1fd9f50-4c64-4c6a-a13e-e904ce81a0e7)
![Image](https://github.com/user-attachments/assets/6cff4ef6-4dfa-4d21-a6d4-eea8a5517b01)

## Engineering 
- Change displayed claim title from `Claim for Death` to `Claim for expenses related to death or burial` for web and mobile *** Address mobile changes via a different pr since we wont be able to test mobile changes
- Change display name for claims of type "Death" to say "Claim for expenses related to death or burial"

## Out of scope
- Add here

## Open questions
- How do we add one of these locally

## Tasks
- [x] Figure out a better name for each "Death" claim
- [ ] Update mock data to have one of these
- [ ] Implement new titles for each

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Design performs design QA and verifies the implementation matches the design spec
- [ ] Accessibility specialist performs accessibility review (in code or design)
- [ ] Engineering identifies staging users required to test and shares account and credentials with design and product
- [ ] Product performs functional QA and verifies acceptance criteria was met

## Acceptance Criteria
- [ ] _Each "Death" related claim gets renamed to “Claim for expenses related to death or burial"_
- [ ] _Mock Data has one of these claims
- [ ] _Changes are in vets-website

**Comment by jstrothman** [comment]
Added questions to OBA + BMT sync agenda so we can move this forward.

**Comment by jstrothman** [comment]
Andrew Gray says the suggested wording is fine for all of them, but would like us to provide a few of the Claim IDs that are pulling in for an EP110, because he doesn't think EP110's should ever be death-related.

@jerekshoe In DataDog, for the last 30 days, under `EP Code to Claim Type mapping` for a search for `death`, I don't see any EP Code 110s, though I did see some in August. Is it accurate that we only have 30 days of data, or is there a way to go back further? And if we can, would we be able to get claim ID's for a few (or other identifier) for Andrew?

**Comment by jstrothman** [comment]
We can go ahead and implement the wording change as described

**Comment by jerekshoe** [comment]
> Andrew Gray says the suggested wording is fine for all of them, but would like us to provide a few of the Claim IDs that are pulling in for an EP110, because he doesn't think EP110's should ever be death-related.
> 
> [@jerekshoe](https://github.com/jerekshoe) In DataDog, for the last 30 days, under `EP Code to Claim Type mapping` for a search for `death`, I don't see any EP Code 110s, though I did see some in August. Is it accurate that we only have 30 days of data, or is there a way to go back further? And if we can, would we be able to get claim ID's for a few (or other identifier) for Andrew?

Hey @jstrothman sorry I missed the email for this comment. I updated the dashboard widgets for the claim type section to be able to look at dates further out than the last 30 days. Included are a few screenshot

#### July 1 - July 31
<img width="456" alt="Image" src="https://github.com/user-attachments/assets/778295f7-7fd7-483d-8d8a-8a3a1de180b1" />

#### August 1 - August 31
<img width="445" alt="Image" src="https://github.com/user-attachments/assets/9e427664-1cb0-4e7c-afb2-c05fc7136ba4" />

**Comment by pmclaren19** [comment]
@jacobworrell updated acceptance criteria to also add one of these to mockdata so we can test

**Comment by pmclaren19** [comment]
@jacobworrell Also updated acceptance criteria so that this change is just for the frontend since we wont be ablet o address mobile changes, since the mobile team isnt able to test it.

**Comment by pmclaren19** [comment]
Good morning @jacobworrell @jstrothman! We have merged these changes.

In this pr: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/573 we added to our mock data so that their is a Death claim for future testing.

In this pr: https://github.com/department-of-veterans-affairs/vets-website/pull/33884 we renamed the title for Death claims in the Claims List, on the Claims Page, and on the Claims Page Breadcrumbs. 
|         | Before | After |
| ------- | ------ | ----- |
| Claims List |  ![Screenshot 2025-01-02 at 2 46 36 PM](https://github.com/user-attachments/assets/611714e9-c539-4919-9c96-4b571f9f1a29)  |     ![Screenshot 2025-01-03 at 1 12 50 PM](https://github.com/user-attachments/assets/921cbc03-0b5a-4649-9630-48d76f76a35b)  |
| Claim Page |  ![Screenshot 2025-01-02 at 2 47 33 PM](https://github.com/user-attachments/assets/2f4b7b65-cc9a-4b39-9931-ac3b6fcbf686)      |   ![Screenshot 2025-01-03 at 1 17 00 PM](https://github.com/user-attachments/assets/e32fa510-5935-4b74-a17c-41dbd38f53c1)    |

Please let me know if you guys have any questions!
