### ISSUE TITLE
DR | Fix, update & add keyboard-only e2e tests

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#91696]
## Value Statement

**_As a_** developer
**_I want to_** fix, update, and add Decision Review keyboard-only end-to-end tests
**_So that_** we have confidence that our forms are keyboard accessible

---

## Background Context

- NOD keyboard-only e2e test is currently disabled due to flakiness
- SC does not have a keyboard-only e2e test
- HLR has a keyboard-only e2e test that is working as expected; but maybe we can remove the `cy.wait()` with some changes

## Acceptance Criteria

- [x] Keyboard-only e2e tests enabled and working for all 3 DR apps
- [x] Check e2e tests for flakiness (CI testing)

## Tasks

- [x] Fix NOD keyboard-only e2e test
- [x] Add SC keyboard-only e2e test
- [x] Update HLR keyboard-only e2e test
- [x] Update platform code as needed

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@anniebtran to review the code review comments before merging
