### ISSUE TITLE
Collaboration Cycle for Identity, sign-in transition interstitial

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#91699]
Please view the [Milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1395) for all feedback and findings tickets associated with this Collaboration Cycle initiative. 
 
### VFS team name

Identity

### Product name

sign-in transition

### Feature name

interstitial

### GitHub label for team

identity

### GitHub label for product

identity-ux

### Public DSVA Slack channel for VFS team

#secure-sign-in-transition

## Kickoff questions
<details><summary>Toggle kickoff questions</summary>

### When did/will you start working on this product/feature?

July 2024

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Yes

### Will your work involve changes to...

Static pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Will a VA editor (Drupal) notice this change?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/login/usip-legacy-logins

### Verify all relevant materials provided to Governance Team

- [X] I have provided all relevant and up-to-date links, screenshots, images, designs, etc. of the as-is version of the product

### Add the GitHub labels for your team, product, and feature to this ticket.

- [X] I acknowledge that I must add the GitHub labels for my team, product, and feature to this ticket.

Kickoff Slack Thread with VFS team: [Kickoff thread](https://dsva.slack.com/archives/C068QM7CCKG/p1724855992357629)
</details>

### Design Intent

<details>
  <summary>Toggle Design Intent instructions</summary>

##### VFS team actions
- [ ] Review [Design Intent Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent) to understand what this touchpoint involves.
- [ ] Schedule your Design Intent (with at least 2 business days lead time from now):
  - Open the [Calendly design intent calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
  - Select a date and time and click "Confirm"
  - Add your name and email
  - Click "Add Guests" and enter the email addresses for VFS team attendees
  - Click "Schedule Event"
- [ ] Link all artifacts in the `Design Intent artifacts for review` section below at least two business days before the scheduled Design Intent. Please don't add artifacts in the comments section.
  
**Design Intent artifacts for review**

[See guidance on Design Intent artifacts.](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent#Designintent-Artifacts) Governance Team feedback is based on the artifacts provided here as well as information provided during the meeting. Please provide links to artifacts **at least two business days** before the scheduled meeting.

Required:
- [ ] User flow

Not required, but nice to have:
- [ ] Wireframes (if provided, must include mobile wireframes)

Optional:
- [ ] Research plan
- [ ] Any other artifacts you have so far
  
##### Governance Team actions
- [ ] Design Intent Slack thread with VFS team
- [ ] Meeting date/time:
  
##### Governance Team actions

- [ ] Update this ticket with the Zoom recording
  - Recording link
  - Passcode:
- Accessibility
  - [ ] Feedback ticket attached
  - [ ] No feedback
- Design
  - [ ] Feedback ticket attached
  - [ ] No feedback
- IA
  - [ ] Feedback ticket attached
  - [ ] No feedback
  
##### VFS team actions

- [ ] Review feedback tickets. Comment on the ticket if there are any questions or concerns.
  

</details>

### Midpoint Review
<details>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

**Required artifacts**
- [x] Design prototypes
   - [ ] [Desktop, interstitial a - user has a modern account](https://www.figma.com/design/skWgD0gHYGlKSoLdH097OX/USiP-and-sign-in-modal---deemphasize-DSL%2FMHV?node-id=938-458117&node-type=FRAME&t=tLCi0DgPtr4XEIOH-0)
   - [ ] [Desktop, interstitial b - user hasn't used a modern account with VA](https://www.figma.com/design/skWgD0gHYGlKSoLdH097OX/USiP-and-sign-in-modal---deemphasize-DSL%2FMHV?node-id=938-466411&node-type=FRAME&t=tLCi0DgPtr4XEIOH-0)
   - [ ] [Mobile, interstitial a - user has a modern account](https://www.figma.com/design/skWgD0gHYGlKSoLdH097OX/USiP-and-sign-in-modal---deemphasize-DSL%2FMHV?node-id=922-458497&node-type=FRAME&t=tLCi0DgPtr4XEIOH-0)
   - [ ] [Mobile, interstitial b - user hasn't used a modern account with VA](https://www.figma.com/design/skWgD0gHYGlKSoLdH097OX/USiP-and-sign-in-modal---deemphasize-DSL%2FMHV?node-id=938-482991&node-type=FRAME&t=tLCi0DgPtr4XEIOH-0)
- [x] [Up to date user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724333905063/6c6192d24519142a244970b2db83539d4c2b1b2e?sender=u2bba352d5b2fc0f0969e0146) (see section for interstitial titled "Option 1: unauthenticated"
  - [Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [x] If working with [Sitewide CAIA](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request), [link to CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91700).

**Not required, but nice to have artifacts**
- [x] Accessibility annotations included as part of your design (desktop views only)
- [x] [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2024-08%20Sign%20in%20transition/2024-08%20Sign%20in%20transition%20research%20plan.md) - this research is being combined with our [sign in page changes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90672)
- [x] [research convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2024-08%20Sign%20in%20transition/2024-08%20Sign%20in%20transition%20conversation%20guide.md)
- Links to specific CAIA artifacts:
  - [ ] IA spec
  - [ ] Content source of truth
- Any other artifacts you have so far
##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C068QM7CCKG/p1724325740045879)
- [x] Meeting date/time: 03:30pm - Thursday, September 5, 2024 (Eastern Time - US & Canada)

##### Platform actions

* Accessibility
  * [x] Feedback added to milestone
  * [ ] No feedback
* Content
  * [ ] Feedback added to milestone
  * [ ] No feedback
* Design
  * [ ] Feedback added to milestone
  * [x] No feedback
* IA
  * [x] Feedback added to milestone
  * [ ] No feedback
* [ ] Update this ticket with the Zoom recording
  - Recording link: https://oddball-io.zoom.us/rec/share/SHx8oGQpP6hjjgIcOYGKYLQGbXdux9uAmBnU_ZBAXZ7aJspC2Po3EQQTpxHzI0sp.HE5p1t52osE6ha2Z
  - Passcode: Q+tY?W4K
  
##### VFS actions
  
- [ ] Review feedback tickets and comment on the ticket if there are any questions or concerns
  
</details>

### Research Review
<details>
  <summary>Toggle Research Review</summary>

#### VFS actions
- [ ] Complete the [research review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)

</details>

### Analytics Request
<details>
  <summary>Toggle Analytics Request</summary>

#### VFS actions
- [ ] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [x] Link to the Analytics Implementation and QA Request ticket below

</details>

### Staging Review
<details open>
  <summary>Toggle Staging Review</summary>
  
##### VFS actions
- Navigate to reference link: [Staging Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review)  
- [x] Schedule your Staging Review when ready:
   - Open the [Calendly staging review calendar](https://calendly.com/collaboration-cycle/staging-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] If this product contains any [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), add the `experimental-design` label and schedule a meeting with DSC to present the research findings.
- [ ] Link all artifacts **ONLY** in the Staging Review artifacts section below at least four days before the scheduled Staging Review.  **Do NOT add artifacts to Comments section**
- [x] I confirm the environment is available and test users have been provided.
- [ ] Please verify your product information in the [Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
 
**Staging Review artifacts**

Links to [Staging Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html#Stagingreview-Artifacts) must be added to this ticket 4 business days ahead of the scheduled meeting. Please do not make changes to the product or artifacts during the 4-day review period. 

#### Required artifacts
  - [x] **URL(s) to review the product**
    - The product should be available on an [approved staging environment](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-environment-guidance-for-vfs-teams). 
    - List pages, sections of pages, and/or user flows impacted by this work.
    - https://staging.va.gov/sign-in-changes-reminder
  - [ ] **Drupal or Staging URL for updated primary entry point**: the main way Veterans will access the tool through site navigation (not search)
  - [x] **Test users and scenarios (when applicable)**
    - Many (but not all) test users can be used (appears to only accept verified users). Ones that are confirmed:
       - vets.gov.user+7@gmail.com
       - vets.gov.user+8@gmail.com
       - vets.gov.user+210@gmail.com 
    - The page will show similarly no matter which user you use, only one is needed.
    - To see the page you should
       - navigate to [staging.va.gov](https://staging.va.gov/)
       - then sign in with test user (see confirmed options above)
       - then navigate to [https://staging.va.gov/sign-in-changes-reminder](https://staging.va.gov/sign-in-changes-reminder)
       - *note - this flow/page will only be displayed to users signing in with MHV credentials, so signing in with a test user (login.gov or ID.me) you must specifically navigate to the page
       - [We made a video](https://drive.google.com/file/d/1CaIAoEgzgwYLR4TKccx93vi_emrji0H4/view?usp=drive_link), to walk through each [test case from the test plan](https://docs.google.com/spreadsheets/d/1g_CM9I0orpXWikR-BJPSKH3grgKS9VbRRMejCADZtDg/edit?gid=1962900419#gid=1962900419) (each version or view of the page).
          - Instructions to follow along with the video (also found in the test plan:
             - Authenticate with ID.me > Use vets.gov.user+210@gmail.com > Navigate to /sign-in-changes-reminder
             - Open Chrome DevTools > Network tab
             - Right-click on credential_emails > Override content
             - If prompted provide a temporary folder for overrides to live
             - Copy the response provided in the Notes column into the Overrides response for credential_emails"
  - [x] **Link to Sitewide [CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91700), if applicable.** 
  - [x] **Completed accessibility testing artifact**: [see instructions and link to accessibility testing template](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review). 
  - [x] **QA Artifacts**: artifacts that correspond to each of the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards).
    - [x] [Regression test plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Secure%20Sign-in%20Transition/regression-test-plan.md#2-interstitial-page)
    - [x] [Test plan](https://docs.google.com/spreadsheets/d/1g_CM9I0orpXWikR-BJPSKH3grgKS9VbRRMejCADZtDg/edit?gid=1962900419#gid=1962900419)
    - [ ] Coverage for References
    - [ ] Summary (Defects) reports
    - [x] [E2E tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/sign-in-changes/tests/SignInChangesReminder.cypress.spec.js)
    - [x] [Code coverage - application: "sign-in-changes"](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/)
    - [x] [Endpoint monitoring playbook](https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vagov-identity-monitor-dashboard?fromUser=false&refresh_mode=paused&from_ts=1732133621472&to_ts=1732738421472&live=false&tile_focus=2297554485859298)
    - [ ] Logging silent failures

#### Not required, but nice to have artifacts
  - [ ] **Content source of truth**: link to CAIA Content feedback, such as a content source of truth.
  - [ ] **Information Architecture spec**: link to CAIA IA feedback, such as an IA spec.

##### Platform actions
- [x] [Slack thread with VFS team](https://dsva.slack.com/archives/C068QM7CCKG/p1731521597469589)
- [x] Meeting date/time: **Dec 5, 2024 at 1.30 PM ET**

##### Platform actions

- [ ] Update this ticket with the Zoom recording
  - [Recording link ](https://oddball-io.zoom.us/rec/share/qGp30FduoDjZNT3lITVUCYof7WwKLyj_xysTYghHanFRSx0rnSEJJkok9yF_WAyd.qcVHB3JbYozC_Rfh)
  - Password: ujQ0e?c@
  
##### VFS actions
  
- [ ] Review the findings tickets and comment on the ticket if there are any questions or concerns
- [ ] Close individual findings tickets when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment on the issue ticket.
- [ ] After launch, [request an accessibility audit from the VA 508 Office](https://depo-platform-documentation.scrollhelp.site/developer-docs/request-support-from-the-va-508-office#RequestsupportfromtheVA508office-AuditRequest). This is required even if no accessibility issues were found during the Staging Review.
  - [ ] Share ServiceNow ticket number here: ______
- [ ] Close ticket once Privacy, Security, Infrastructure Readiness Review has been completed, VA 508 Office audit is requested, and all other post-Staging actions are complete
</details>
