### ISSUE TITLE
Align on Experimental Design process, flow and definitions

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91693]
## User Story
As a Governance team member who is responsible for recommending Experimental Design to VFS teams in the Collaboration Cycle, I want to have better clarify on when Experimental Design should be recommended so that I am giving teams proper guidance and not asking them to do more than necessary.

Assignee: @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
Earlier this year, Governance team drafted a [new flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715279885465/a8a7701ed5948be8cd98f972ee930a16b9e7444b?sender=18d9b85e-46ce-4d30-98fc-1cbd794c5434) for Experimental Design to help Governance and VFS teams determine when the experimental design process is needed. We had planned to publish the flow to the VADS per ticket #85474, however additional concerns about the flow were raised by @humancompanion-usds. Governance assumes that the disconnect on what experimental design is, how it's recommended and what process VFS teams follow is due to unclear documentation and guidance. 

The purpose of this ticket is to align on Experimental Design including:

- what is the Experimental Design process?
- when would the Experimental Design process be recommended to a VFS team for a new design?
- how to we determine if the new design should be added to the VADS?
- how can we capture all of the variations of the new design if they're NOT added to the VADS?
- what is the process the Design System Council (DSC) follows for approving a new design?

Once Governance, DST and OCTO are aligned on the above, we will make any necessary changes to the flow chart, as well as creating a legend/key with definitions of common terms. Governance also assumes that the disconnect on the process is also due to a lack of controlled vocabulary. VFS teams often incorrectly assume that "Experimental Design" refers to the research process AND the process for adding to the VADS.

### Live pages
- [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1715279885465/a8a7701ed5948be8cd98f972ee930a16b9e7444b?sender=u870c8d9c6b47768924793768)
- [How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)
- [How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review)
- [How to document findings for Staging Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1839530098/How+to+document+findings+for+Staging+Review)

### Drafted pages
- 

## Tasks
- [x] Meet with Matt, DST, Naomi and Governance team members on 8/29 to align on Experimental Design
- [x] Update Mural
   - Add new flow for things that are new but do not need to go thru experimental design
   - Update current experimental design
   - Update decision tree
- [x] Review current Governance team documentation docs to see if the new flows have any impact
- [x] Reach out to Matt Dingee for his feedback

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We are in alignment across Platform and OCTO-DE with what the Experimental Design process is.
- [x] We have agreed upon an updated flow for recommending Experimental Design 
- [x] We have agreed upon definitions of Experimental Design and other common terms

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by allison0034** [comment]
Met with the team and updated tasks.

**Comment by allison0034** [comment]
This will move into the next sprint. My priorities were moved to an MVP for the new po sync

**Comment by allison0034** [comment]
@KKitagawa-Bosch I have updated the Mural linked above, please take a look! The change was that only components or patterns that are going to be useful by other teams will go thru experimental design.

**Comment by allison0034** [comment]
@KKitagawa-Bosch I also updated the verbiage on experimental design in How to document feedback for a Design Intent. I commented where I made the change. Once you approve that I will update the other touchpoints.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 

(1) In the mural, I don't see a "yes" flow option for "was it approved by DSC" or a "no" option for "are you making a new change or variation". Also do we want to align tenses throughout the flow? Some boxes are present simple i.e., "the team makes a decision" while other are imperative i.e., "make a decision" 

(2) additions in "how to document feedback" look great!

**Comment by KKitagawa-Bosch** [comment]
(1) I figured as much, but wanted to be sure. Works for me! 

(2) can do!

**Comment by allison0034** [comment]
Reached out to Matt on [Slack](https://dsva.slack.com/archives/GNF5GSD9N/p1727182380280589).

**Comment by allison0034** [comment]
@KKitagawa-Bosch thank you!!! Good to close?

**Comment by shiragoodman** [comment]
@allison0034 just took a quick look and noticed right away that there isn't a "No" path for the first question on the Decision Tree. Can you please fix?

**Comment by shiragoodman** [comment]
@allison0034 sorry, please just take another look at the Decision Tree. I'm seeing a lot of missing paths and I think you need to take some time to make sure all paths are accounted for. I haven't looked at the Process yet, but I'd like to ensure the Decision Tree is correct and I understand the flow before I verify the process has been updated correctly.

**Comment by shiragoodman** [comment]
there's no rush to have this ticket closed by end of sprint today. I 'd also like to ensure @humancompanion-usds has a chance to review the flow and process before we move into next steps for updating documentation.

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman just FYSA I mentioned some of those missing paths above but Allison mentioned that those are options that nobody will ever really take. Do we want to consider rephrasing them so they aren't yes/no questions at that point, but rather like..."make sure that you have this before moving to the next step"

**Comment by shiragoodman** [comment]
Thanks @KKitagawa-Bosch . I saw your comments, and while Allison is likely right, I don't think it's a good practice for us to publish a flow with missing paths. If I'm new to a VFS and I'm trying to learn about experimental design, my assumption would be that the Decision Tree has errors bc I wouldn't know to assume that no one takes those paths. 

If the path means that Experimental Design is not needed, like in the case of the first question, then it should be explicitly clear.

**Comment by KKitagawa-Bosch** [comment]
@shiragoodman makes sense, thank you! (for the record, not disagreeing with you, just know I have things to learn about decision trees specifically so I wanted to ask)

**Comment by allison0034** [comment]
Going to pause and rethink the flow part to make it simpler and more clear.

**Comment by shiragoodman** [comment]
Thanks, @allison0034 . 

Something I said to Allison via DM that I'll state here as well for transparency purposes - we have to hold ourselves to a higher standard. If a VFS team submitted a flow to us with missing paths, we'd immediately call it out to them and ask where those paths lead. We're in a position where we're critiquing, and sometimes criticizing, other teams' design choices. We need to ensure we practice what we preach, or else we could risk losing the respect we've worked so hard to earn. 

Thank you both for taking a second look at this! Please lmk if you'd like to discuss over a call.

**Comment by allison0034** [comment]
@KKitagawa-Bosch I spent some time reorg some things and updating and simplifing things. Can you take a look?

**Comment by KKitagawa-Bosch** [comment]
@allison0034 left some comments! Let me know what you think then I'll do another pass for content specifically

**Comment by allison0034** [comment]
Thanks @KKitagawa-Bosch, I made all your suggested changes except 1 and commented on that. Let me know what you think.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 That comment makes sense! I can't really think of a way to rephrase it that isn't significantly more wordy (I was thinking like "some teams may stop here"), so I think it's fine as is!

**Comment by allison0034** [comment]
@shiragoodman ready for your review.

**Comment by shiragoodman** [comment]
@allison0034 i took a look at the updates to the decision tree and swimlane diagram. This looks great! I did have 1 question and added a comment to the mural, so please be sure to check that out.

**Comment by allison0034** [comment]
Aligned with Shira and [reached out to Matt](https://dsva.slack.com/archives/GNF5GSD9N/p1728064860483119).

**Comment by allison0034** [comment]
This will move into the next sprint as Matt is still reviewing.

**Comment by shiragoodman** [comment]
hey @allison0034 . Per our convo, I talked to @humancompanion-usds re: the updated Experimental Design flow. Matt noted that we're missing the path for VFS teams to contribute the component change themselves per the [Contributing ](https://design.va.gov/about/developers/contributing)guidance. For the “You may now use your design on VA.gov” block, there should be 2 lines off of that... possibly a diamond decision of “do you have the resources to contribute this pattern yourself?” 

Let me know if you have any questions. Once you and @KKitagawa-Bosch are on the same page, please share with Matt again for his final review and approval.

**Comment by allison0034** [comment]
[Reaching out to Matt about new flow.](https://dsva.slack.com/archives/GNF5GSD9N/p1728915826406079)

**Comment by allison0034** [comment]
Matt has made changes to the flow. @KKitagawa-Bosch @shiragoodman want to take a peek and then I can close if we are good?

**Comment by shiragoodman** [comment]
hey @allison0034 - my only question here is how DST would know if the VFS doesn't have the resources to help update the pattern? I would assume there would be a step or something that they need to take to indicate to DST that DST needs to take action. OR maybe the other way around instead? A step or action the VFS team takes to indicate to DST that the VFS does have resources to support and is working on it. I don't see that reflected here, and I think it should occur.

@humancompanion-usds what do you think?

**Comment by allison0034** [comment]
@shiragoodman that is a great question. Matt is this something that could be asked at the end of the DSC meeting?

**Comment by shiragoodman** [comment]
I talked to @humancompanion-usds about this at our 1:1 this morning. He agreed with me... I think a good, easy solution for now would be for the VFS team to comment on the ticket notifying DST that they have the resources and will be working on contributing this themselves. Can you incorporate that into the flow? 

@allison0034 I also added a comment in the mural re: the language in 1 of the boxes. 

Last thing... @KKitagawa-Bosch can you please help Allison to ensure the entire swimlane flow uses consistent voice and tone? Right now, it's a bit all over the place. For example, the box I commented on currently says, "VFS team may now use your design on VA.gov" - your design? whose design? do we mean their design? Please read through all of it an ensure it's consistent throughout.

**Comment by KKitagawa-Bosch** [comment]
@allison0034 Just to confirm before I try to align all those tenses, the target audience here is the VFS team? Trying to determine if the VFS team should be referred to in third-person like the other teams, or if we should refer to them directly as the reader throughout

**Comment by KKitagawa-Bosch** [comment]
@allison0034 Everything should match now! Since the audience could be any team, I stuck with the present indicative 3rd-person (i.e., waits, sends, etc.) so it reads the same regardless of who is viewing it. Also made the clarification on that one box that Shira recommended.

**Comment by allison0034** [comment]
@shiragoodman @KKitagawa-Bosch am I good to close?

**Comment by shiragoodman** [comment]
@allison0034 I still don't see how the VFS is notifying DST that they're contributing the component. Also can we clarify the question, "Does the VFS team have the resources to contribute to this pattern?" to specify VADS? I know it seems self explanatory, but please make it crystal clear. 

Also, please address this line break, and double check that everything is formatted correctly (eg yes/no is correct, arrows are correct, all arrows are present, etc.)

![Image](https://github.com/user-attachments/assets/dd2e0782-9ac3-4c80-9819-b456ebc25428)

**Comment by allison0034** [comment]
@shiragoodman sorry I missed the first time you comment about " VFS comments on ticket they will be working on this themselves"... there are sooo many comments in this ticket.

Everything should have been addressed now.

-  VFS comments on ticket they will be working on this themselves.
- Added VADS to the resources question
- Fixed line break

**Comment by KKitagawa-Bosch** [comment]
I went and looked back to confirm those three bullets and they look right on my end, but now I'm seeing some weird formatting over there with the first bullet. 

![Image](https://github.com/user-attachments/assets/b163c4d7-4117-4b81-83ce-e1f30c815fae)
