### ISSUE TITLE
New VFS Team Onboarding next steps: VSA Global UX

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#917]
## User Story
As a new VA.gov team member, I need to complete onboarding activities so I can successfully work on my project.

## Acceptance Criteria
- [ ] Each team member has completed each item in the onboarding checklist below.

## Onboarding Checklist

- [x] Attend general onboarding meeting
- [x] [Request Access to Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Administrative/Onboarding/request-access-to-tools.md)
- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [x] Review the [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [x] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [x] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/DigitalModernizationStrategy.pdf)
- [x] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/VA.gov%20Relaunch%202018/new-vagov-strategy/The-new-VA.gov-briefing-2019-07.pdf) documentation
- [x] Designers: Review [Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)
- [x] Engineers: [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/getting-started.md)
  - [ ] [Set Up Front-end](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
  - [ ] [Set Up Back-end](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
  - [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
  - [ ] [Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md)
- [x] Designers: Attend breakout session
- [x] Engineers: Attend breakout session
- [x] Full team: Attend the Discovery and Logistics Workshop
- [x] Front-end Engineers: Attend deep-dive session
- [ ] Back-end Engineers: Attend deep-dive session
- [x] PM, Designers and Content Writer(s): Request content and IA intro
- [x] PM and Front-End Engineers: Request analytics intro
- [x] PM Request 508 intro
- [x] PM and Engineers: Request load testing, privacy, and security intro
- [ ] PM and Engineers: Request ATO intro
- [x] PM, designers, and content writers: Request IA intro

## Notes:
To track the work needed to complete the items in this checklist, you may want to create GitHub issues. 
- [ ] Assign the issues to individual(s) to complete
- [ ] Label the issues appropriately ( `onboarding`, `[your-team-name]`)
- [ ] Attach the issues to this Epic

**Comment by lwalsh617** [comment]
FYI, the third link in the Onboarding Checklist, "Guidelines for Working Safely in an Open Source Repo," produces a 404 error.

**Comment by 1Copenut** [comment]
@lwalsh617 This is in our sensitive repository, so you'll need to be logged in. Please let me know if it still 404's and we'll work to get you the right access.

**Comment by rroueche** [comment]
Updated title so this epic is clearly differentiated from VSP's epic to actually onboard this team.

**Comment by meganhkelley** [comment]
Added to checklist: `PM, designers, and content writers: Request IA intro` and made a new ticket for this (#1636)

**Comment by mnorthuis** [comment]
Updated the links above. These all changed with the updates to the va.gov-team repo last week.
