### ISSUE TITLE
Draft PO Sync touchpoint page

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91703]
## User Story
As a Governance team member, I want to draft the PO Sync touchpoint page so that VFS teams will be able to understand what the PO Sync meeting is, who it is for and how it's recommended.

Assignee: @KKitagawa-Bosch 
Peer Reviewer: ~~@briandeconinck~~ @allison0034  

## Description
Governance team received approval from OCTO-DE Design leads for creating the PO Sync touchpoint and introducing it to the Collaboration Cycle. The [PO Sync - proposal](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3407773924/PO+sync+-+proposal), drafted in ticket #90156, includes details of what this touchpoint is, who it is for, why it exists, when it will occur in the Collaboration Cycle, and what the expected outcome will be. The touchpoint is required for all OCTO VFS teams.

The purpose of this ticket is to draft a new touchpoint page for the PO Sync. The format should be similar to the [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent), [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review) and [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) touchpoint pages, however since it has a very different scope of work and does not include contractors, the format and structure of the page can differ. Please use your best judgement when creating the page. 

Note: the PO Sync touchpoint page will not be published to Platform Website at this time. Publishing will occur in ticket #91708. It is also possible that the draft PO Sync page may require additional changes as this initiative continues.

### Live pages
- [PW Touchpoints page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/touchpoints)

### Drafted pages
- [PO Sync](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3426844715/91703+PO+Sync+Touchpoint+Page)
- [PW Touchpoints page](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3432120322/91703+Touchpoints)

## Tasks
- [x] Create a documentation draft of the new PO Sync touchpoint page
- [x] Determine what content should be included in the page by reviewing the Description above, the proposal doc, as well as the existing DI, MPR and SR touchpoint pages.
- [x] Create a draft of PW Touchpoints page and add PO Sync
- [x] Share with Peer reviewer for their feedback
- [x] Implement changes, if any, from peer reviewer
- [x] Share with @humancompanion-usds for review and feedback on #platform-governance-team channel, and share with @DanielleThierryUSDSVA via DM.
   - We do not need Matt and Danielle's feedback in order to close the ticket as we will not be launching changes right away. 

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have documented a draft of the new PO Sync touchpoint page for Platform Website
- [x] We have shared the draft page with Matt and Danielle for their review and feedback

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck I have removed you as peer reviewer for this ticket and assigned @allison0034  as the peer reviewer in your place.

**Comment by KKitagawa-Bosch** [comment]
Draft is in progress [here](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3426844715/91703+PO+Sync+Touchpoint+Page)

Waiting to hear from Matt about some questions, then that draft will be finalized soon after

**Comment by allison0034** [comment]
@KKitagawa-Bosch I added a new task (draft PW Touchpoints page). I put the live page in the live artifact section. You will need to create a draft in our space and add the PO sync to that page.

**Comment by allison0034** [comment]
Also, just keep in mind, your draft needs to be approved and ready to published on 9/10 when Platform website pushes changes (I think they do it at 3pm ET). We need your link to update the other pages. I have documented this as part of [Launch PO Sync and announce changes](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/91708).

**Comment by KKitagawa-Bosch** [comment]
> @KKitagawa-Bosch I added a new task (draft PW Touchpoints page). I put the live page in the live artifact section. You will need to create a draft in our space and add the PO sync to that page.

Cool! Added that doc and I'll comment when it's drafted. 

Re: the 9/10 publication date, I imagine that will be plenty of lead time. At this point I figure we're one revision away from being ready with the touchpoint page, just need the info from Matt then you can do a lookover for last edits

**Comment by KKitagawa-Bosch** [comment]
@allison0034 the [Touchpoint Page Draft](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3426844715/91703+PO+Sync+Touchpoint+Page) is updated with comments from Matt! I've left one very small comment on there with a question for you, but otherwise it should all be good to review and all the info is Matt-approved!

**Comment by KKitagawa-Bosch** [comment]
Shared with Danielle via Slack DM per the ticket. 

Anything else left to do here before closing since this ticket doesn't include publishing the draft @allison0034?

**Comment by allison0034** [comment]
Nope, you can close!
