### ISSUE TITLE
Create new Calendly event for PO Sync

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91705]
## User Story
As an OCTO Design lead supporting the new PO Sync touchpoint, I will want to have the meeting at specific times each week so that it works well with my schedule.

Assignee: @allison0034 
Peer Reviewer: @KKitagawa-Bosch 

## Description
The PO Sync touchpoint will be set up the same way the DI, MPR and SR touchpoint are. There will be a unique PO Sync event on Calendly. Governance will need to coordinate with @humancompanion-usds and @DanielleThierryUSDSVA to find 2-3 timeslots per week that are 30 minutes in length and that work for them both. The availability of the other OCTO-DE Design leads (Martha, Mikki, Shane, and Ryan) should also be considered, however Matt and Danielle's availability will be prioritized.

In order for this event to be set up in Calendly and for the PO Sync meetings to be displayed on the Collab Cycle Calendar alongside the other CC events, the PO Sync meeting cannot exist at the same time as other Collab Cycle meetings (and we likely don't want it to overlap anything bc then the PO from Governance and VFS will be double-booked). The assignee of this ticket will need to reach out to all OCTO-DE Design leads via the #platform-collaboration-cycle channel with proposed timeslots and determine availability.

Once we have determined which 2-3 timeslots work best (ideally 3, however we may have to settle for 2 since these are busy people!), create the event in Calendly. Please refer to the draft PO Sync touchpoint page created in ticket #91703 to help determine what info should also exist in Calendly.  

### Live pages
- 

### Drafted pages
- [PO Sync Calendly event](https://calendly.com/collaboration-cycle/po-sync)
- [Table with possible timeslots](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3421470753/91705+Times+for+PO+Sync+-+Allison)

## Tasks
- [x] Reach out to OCTO-DE Design leads with proposed timeslots for the PO Sync
- [x] Choose 2-3 timeslots where majority of the OCTO-DE Design leads are available. Matt and Danielle's availability will be prioritized. 
- [x] Ask Matt and Danielle how much _minimum notice_ they would like for the event. For example, Governance asks for 48 hours minimum notice when scheduling DI and MPR. How much minimum notice would Danielle and Matt like for the PO Sync? (_Minimum notice_ is what the feature is called in Calendly)
- [x] ~~Zoom~~ MS Teams details for the PO Sync event will be filled in later on
- [x] Add information to the Description/instruction based on the PO Sync touchpoint page draft, if needed. 
   - For example, the SR page has the SR requirements, but the DI/MPR page has nothing. Use your best judgement to determine if content should be included or not, and if so, which content.
- [x] On the Calendly Booking Page Options, do not let the invitee add guests
- [x] Determine if other Booking Page Options should be added based on the PO Sync touchpoint page

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have determined 2-3 weekly timeslots for hosting the PO Sync that largely meet the availability of the OCTO-DE Design Leads 
- [x] We have created a new event in Calendly for the PO Sync with the specified timeslots
- [x] The _minimum notice_ for the PO Sync Calendly event meets the specifications of Matt & Danielle
- [x] The PO Sync Calendly event does not give the person the option to add guests to the event.

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [x] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket has been moved to the current sprint and will be prioritized.

**Comment by allison0034** [comment]
Hi @humancompanion-usds and @DanielleThierryUSDSVA , I have [created a document](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3421470753/91705+Times+for+PO+Sync+-+Allison) to try to help find 3 timeslots that the 2 of you can hold for a PO Sync. Can you please take a look and put "preferred" next to any times that you prefer? Feel free to add or remove any times.

**Comment by shiragoodman** [comment]
@allison0034 I'd encourage you reach out on Slack too. Sometimes it takes a while for folks to see messages on gh

**Comment by allison0034** [comment]
[Reached out](https://dsva.slack.com/archives/G01DXP10GCA/p1725046794529889) to Matt and Danielle about minimum notice.

**Comment by allison0034** [comment]
The time slots will be Tuesdays 11:00-11:30am and Wednesdays 2:00-2:30. They will require at least 48 hours notice.

**Comment by allison0034** [comment]
Waiting on #91703 to be complete so I can fill in some of the gaps. I will start on Determine changes to Kickoff process.

**Comment by allison0034** [comment]
Added MS Team link from Matt and updated Calendly info per the draft of PO Sync touchpoint page. [Shared with Keegan and Matt](https://dsva.slack.com/archives/GNF5GSD9N/p1725644330552209) to get feedback.

**Comment by KKitagawa-Bosch** [comment]
Ran a test and everything looks good from my end!
